<?php

// Themes
$themes = array(
	array(
		"name" => "Classic",
		"version" => "1.0.0",
		"mail" => "pragma [at] kvirc [dot] net",
		"author" => "Pragma",
		"desc" => $template['themes']['theme0'],
		"home" => "",
		"download" => "Classic-1.0.0.kvt",
		"screen" => "classic.png",
		"release_date" => "2015.08.26",
		"min_version" => "4.2.0"
	),
	array(
		"name" => "Marble Theme",
		"version" => "1.0.4",
		"mail" => "sbrokka [at] openlug [dot] org",
		"author" => "Sbrokka",
		"desc" => $template['themes']['theme1'],
		"home" => "",
		"download" => "Marble-1.0.4.kvt",
		"screen" => "marble.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Crystal",
		"version" => "0.3",
		"mail" => "trisk-kvirc [at] quasarnet [dot] org",
		"author" => "Triskelios",
		"desc" => $template['themes']['theme2'],
		"home" => "",
		"download" => "Crystal-0.3.kvt",
		"screen" => "crystal.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Green Theme",
		"version" => "1.1",
		"mail" => "",
		"author" => "F.F (have more fun)",
		"desc" => $template['themes']['theme3'],
		"home" => "",
		"download" => "Green-1.1.kvt",
		"screen" => "green.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Ircii Like",
		"version" => "1.0",
		"mail" => "eva [at] cyberbeat [dot] it",
		"author" => "Penny",
		"desc" => $template['themes']['theme4'],
		"home" => "",
		"download" => "Ircii-like-1.0.kvt",
		"screen" => "ircii.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Yisus",
		"version" => "0.3",
		"mail" => "fnotari [at] comtron.com [dot] ar",
		"author" => "Fernando Notari",
		"desc" => $template['themes']['theme5'],
		"home" => "",
		"download" => "Yisus-0.3.kvt",
		"screen" => "notari.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Kitsch Theme",
		"version" => "1.0",
		"mail" => "eva [at] cyberbeat [dot] it",
		"author" => "Penny",
		"desc" => $template['themes']['theme6'],
		"home" => "",
		"download" => "Kitsch-1.0.kvt",
		"screen" => "kitsch.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Ghost",
		"version" => "1.0",
		"mail" => "darkstalker [at] insightbb [dot] com",
		"author" => "Jason Carter",
		"desc" => $template['themes']['theme7'],
		"home" => "",
		"download" => "Ghost-1.0.kvt",
		"screen" => "ghost.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "PayneReactor",
		"version" => "1.0",
		"mail" => "webmaster [at] paynereactor [dot] net",
		"author" => "Kristian Hollund",
		"desc" => $template['themes']['theme8'],
		"home" => "http://www.PayneReactor.com",
		"download" => "PayneReactor-1.0.kvt",
		"screen" => "payne.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "XCrystall Black",
		"version" => "0.0.1",
		"mail" => "wizard at opendoor [dot] ru",
		"author" => "Alexey",
		"desc" => $template['themes']['theme9'],
		"home" => "",
		"download" => "XCrystall-black-0.0.1.kvt",
		"screen" => "xcrystall.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "DarkBaghira",
		"version" => "0.6",
		"mail" => "hellvis69 [at] gmail [dot] com",
		"author" => "HelLViS69",
		"desc" => $template['themes']['theme10'],
		"home" => "",
		"download" => "DarkBaghira-0.6.kvt",
		"screen" => "darkbaghira.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Time makes no sense",
		"version" => "3.3.2",
		"mail" => "cle [at] virg0 [dot] org",
		"author" => "etherea`",
		"desc" => $template['themes']['theme11'],
		"home" => "http://kvirc.virg0.org",
		"download" => "Time-3.3.2.kvt",
		"screen" => "time.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Pure",
		"version" => "1.0.1",
		"mail" => "cle [at] virg0 [dot] org",
		"author" => "etherea`",
		"desc" => $template['themes']['theme12'],
		"home" => "http://kvirc.virg0.org",
		"download" => "Pure-1.0.1.kvt",
		"screen" => "pure.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Dark Glass",
		"version" => "1.0",
		"mail" => "grifisx [at] barmes.org",
		"author" => "Grifisx &amp; Noldor",
		"desc" => $template['themes']['theme13'],
		"home" => "",
		"download" => "DarkGlass-1.0.kvt",
		"screen" => "darkglass.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Black Heart",
		"version" => "1.0",
		"mail" => "grifisx [at] barmes.org",
		"author" => "Grifisx &amp; Noldor",
		"desc" => $template['themes']['theme14'],
		"home" => "",
		"download" => "BlackHeart-1.0.kvt",
		"screen" => "blackheart.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "X-KVIrc-mas",
		"version" => "1.0",
		"mail" => "grifisx [at] barmes.org",
		"author" => "Grifisx &amp; Noldor",
		"desc" => $template['themes']['theme15'],
		"home" => "",
		"download" => "X-KVIrc-mas-1.0.kvt",
		"screen" => "X-KVIrcmas.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Words are Perversion",
		"version" => "1.0.3",
		"mail" => "cle [at] virg0 [dot] org",
		"author" => "etherea`",
		"desc" => $template['themes']['theme16'],
		"home" => "http://kvirc.virg0.org",
		"download" => "Words_are_Perversion-1.0.3.kvt",
		"screen" => "words.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Erotica",
		"version" => "0.6.9",
		"mail" => "cle [at] virg0 [dot] org",
		"author" => "etherea`",
		"desc" => $template['themes']['theme17'],
		"home" => "http://kvirc.virg0.org",
		"download" => "Erotica-0.6.9.kvt",
		"screen" => "erotica.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Anger",
		"version" => "0.0.1",
		"mail" => "cle [at] virg0 [dot] org",
		"author" => "etherea`",
		"desc" => $template['themes']['theme18'],
		"home" => "http://kvirc.virg0.org",
		"download" => "Anger-0.0.1.kvt",
		"screen" => "anger.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Dark Blue",
		"version" => "0.9",
		"mail" => "lgxco [at] yahoo [dot] it",
		"author" => "Puk",
		"desc" => $template['themes']['theme19'],
		"home" => "",
		"download" => "DarkBlue-0.9.0.kvt",
		"screen" => "darkblue.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Soft Blue",
		"version" => "2.0",
		"mail" => "gestenigd [at] gmail [dot] com",
		"author" => "lsd",
		"desc" => $template['themes']['theme20'],
		"home" => "http://stato-brodo.blogspot.com",
		"download" => "Soft_blue-2.0.kvt",
		"screen" => "softblue.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Snow",
		"version" => "1.1",
		"mail" => "youpiter [at] mail [dot] ru",
		"author" => "Youpiter",
		"desc" => $template['themes']['theme21'],
		"home" => "",
		"download" => "Snow-1.1.kvt",
		"screen" => "snow.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Zima",
		"version" => "1.3",
		"mail" => "youpiter [at] mail [dot] ru",
		"author" => "Youpiter",
		"desc" => $template['themes']['theme22'],
		"home" => "",
		"download" => "Zima-1.3.kvt",
		"screen" => "zima.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "GreenKDE",
		"version" => "1.0",
		"mail" => "youpiter [at] mail [dot] ru",
		"author" => "Youpiter",
		"desc" => $template['themes']['theme23'],
		"home" => "",
		"download" => "GreenKDE-1.0.kvt",
		"downbig" => "GreenKDE-1.1.2.kvt",
		"screen" => "greenkde.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Minimalist",
		"version" => "1.0",
		"mail" => "",
		"author" => "Stan",
		"desc" => $template['themes']['theme24'],
		"home" => "http://www.stantown.de",
		"download" => "Minimalist-1.0.kvt",
		"screen" => "minimalist.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "Slightly Yellow",
		"version" => "1.0",
		"mail" => "mren [at] mrmx [dot] de",
		"author" => "mren_",
		"desc" => $template['themes']['theme25'],
		"home" => "",
		"download" => "Slightly_Yellow-1.0.kvt",
		"screen" => "slightly.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "YellowIRC",
		"version" => "1.0",
		"mail" => "pragma [at] kvirc [dot] net",
		"author" => "Pragma",
		"desc" => $template['themes']['theme26'],
		"home" => "http://pragmaware.net",
		"download" => "YellowIRC-1.0.kvt",
		"screen" => "yellowirc.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Love And Death",
		"version" => "1.0.5",
		"mail" => "",
		"author" => "DanBadJar",
		"desc" => $template['themes']['theme27'],
		"home" => "",
		"download" => "Love_and_Death-1.0.5.kvt",
		"screen" => "loveanddeath.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "mIRC",
		"version" => "2.1",
		"mail" => "sonichedgehog_hyperblast00 [at] yahoo [dot] com",
		"author" => "Taoki",
		"desc" => $template['themes']['theme28'],
		"home" => "",
		"download" => "mIRC-2.1.kvt",
		"screen" => "mirc.png",
		"release_date" => "2011.06.10",
		"min_version" => "4.0.0"
	),
	array("name" => "SilverEx_Clone",
		"version" => "0.1",
		"mail" => "vampiermsx [at] gmail [dot] com",
		"author" => "Vampier",
		"desc" => $template['themes']['theme29'],
		"home" => "",
		"download" => "SilverEx_Clone-0.1.kvt",
		"screen" => "silverexclone.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Light My Fire!",
		"version" => "0.4",
		"mail" => "k0smik0 [at] logorroici [dot] org",
		"author" => "k0sm|k0",
		"desc" => $template['themes']['theme30'],
		"home" => "",
		"download" => "Light_My_Fire-0.4.kvt",
		"screen" => "lightmyfire.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Drow",
		"version" => "1.0",
		"mail" => "yoyo.pete [at] gmail [dot] com",
		"author" => "YoYo-Pete",
		"desc" => $template['themes']['theme31'],
		"home" => "",
		"download" => "Drow-1.0.kvt",
		"screen" => "drow.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Fractalize",
		"version" => "0.6",
		"mail" => "k0smik0 [at] logorroici [dot] org",
		"author" => "k0sm|k0",
		"desc" => $template['themes']['theme32'],
		"home" => "",
		"download" => "Fractalize-0.6.kvt",
		"screen" => "fractalize.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "System",
		"version" => "2.0",
		"mail" => "sonichedgehog_hyperblast00 [at] yahoo [dot] com",
		"author" => "Taoki",
		"desc" => $template['themes']['theme33'],
		"home" => "",
		"download" => "System-2.0.kvt",
		"screen" => "system.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "CoreZeam",
		"version" => "1.0",
		"mail" => "aerodynamythes [at] aliceadsl [dot] fr",
		"author" => "leox",
		"desc" => $template['themes']['theme34'],
		"home" => "http://corezeam.org/index.php/aide/53-lirc-internet-relay-chat/129-kvirc.html?lang=fr",
		"download" => "CoreZeam-1.0.0.kvt",
		"screen" => "corezeam.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Black",
		"version" => "1.4",
		"mail" => "",
		"author" => "Radicand",
		"desc" => $template['themes']['theme35'],
		"home" => "",
		"download" => "Black-1.4.kvt",
		"screen" => "black.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Hello Kitty",
		"version" => "1.0",
		"mail" => "",
		"author" => "Sc0rPiOn-BaBy",
		"desc" => $template['themes']['theme36'],
		"home" => "",
		"download" => "HelloKitty-1.0.kvt",
		"screen" => "hellokitty.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "CoherEase",
		"version" => "1.1 GR",
		"mail" => "",
		"author" => "Chapoolin",
		"desc" => $template['themes']['theme37'],
		"home" => "",
		"download" => "CoherEase-1.1_GR.kvt",
		"screen" => "coherease.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Celebration",
		"version" => "0.6.9",
		"mail" => "etherea [at] kvirc [dot] net",
		"author" => "etherea",
		"desc" => $template['themes']['theme38'],
		"home" => "http://kvirc.virg0.org",
		"download" => "Celebration-0.6.9.kvt",
		"screen" => "celebration.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "Savannah",
		"version" => "1.5",
		"mail" => "kult [at] tsure [dot] ru",
		"author" => "Kult",
		"desc" => $template['themes']['theme39'],
		"home" => "http://irc.tsure.ru",
		"download" => "Savannah-1.5.kvt",
		"screen" => "savannah.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "VDark",
		"version" => "1.0.1",
		"mail" => "",
		"author" => "RoadRunner",
		"desc" => $template['themes']['theme40'],
		"home" => "",
		"download" => "VDark-1.0.1.kvt",
		"screen" => "vdark.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "VLight",
		"version" => "1.0.2",
		"mail" => "",
		"author" => "RoadRunner",
		"desc" => $template['themes']['theme41'],
		"home" => "",
		"download" => "VLight-1.0.2.kvt",
		"screen" => "vlight.png",
		"release_date" => "2008.11.28",
		"min_version" => "4.0.0"
	),
	array("name" => "DarkMatter",
		"version" => "1.0",
		"mail" => "swarfega [at] swarfegaonline [dot] co.uk",
		"author" => "swarfega",
		"desc" => $template['themes']['theme42'],
		"home" => "http://www.swarfegaonline.co.uk",
		"download" => "DarkMatter-1.0.kvt",
		"screen" => "darkmatter.png",
		"release_date" => "2011.06.06",
		"min_version" => "4.0.0"
	),
	array("name" => "DarkEnergy",
		"version" => "1.0",
		"mail" => "swarfega [at] swarfegaonline [dot] co.uk",
		"author" => "swarfega",
		"desc" => $template['themes']['theme43'],
		"home" => "http://www.swarfegaonline.co.uk",
		"download" => "DarkEnergy-1.0.kvt",
		"screen" => "darkenergy.png",
		"release_date" => "2012.08.05",
		"min_version" => "4.0.0"
	),
	array(
		"name" => "VoidLight",
		"version" => "1.0.3",
		"mail" => "swarfega [at] swarfegaonline [dot] co.uk",
		"author" => "swarfega",
		"desc" => $template['themes']['theme44'],
		"home" => "https://github.com/swarfega",
		"download" => "VoidLight-1.0.3.kvt",
		"screen" => "voidlight.png",
		"release_date" => "2016.02.17",
		"min_version" => "4.9.1"
	),
	array(
		"name" => "VoidDark",
		"version" => "1.0.2",
		"mail" => "swarfega [at] swarfegaonline [dot] co.uk",
		"author" => "swarfega",
		"desc" => $template['themes']['theme45'],
		"home" => "https://github.com/swarfega",
		"download" => "VoidDark-1.0.2.kvt",
		"screen" => "voiddark.png",
		"release_date" => "2016.02.17",
		"min_version" => "4.9.1"
	)
	
	/*
	 * Without info, not listed
	 *
	array("name" => "Burst Rebird",
		"version" => "0.1",
		"mail" => "",
		"author" => "",
		"desc" => "",
		"home" => "",
		"download" => "BurstRebird-0.1.kvt",
		"screen" => ""
	),
	array("name" => "Kvinvision", "version" => "1.0",
		"mail" => "",
		"author" => "LoSko",
		"desc" => "",
		"home" => "",
		"download" => "Kvinvision-1.0.kvt",
		"screen" => ""
	)
	*/
);
?>
