<?
// Security check
if(isset($_GET['checkNetHack'])||!isset($checkNetHack))
	echo "<script type=\"text/javascript\">location.href='..';</script>";

/* index.php start */
// languages
$template['index']['italian']="Italian";
$template['index']['english']="English";
$template['index']['german']="German";
$template['index']['russian']="Russian";
$template['index']['french']="French";
$template['index']['spanish']="Spanish";
$template['index']['bulgarian']="Bulgarian";
$template['index']['czech']="Czech";
$template['index']['dutch']="Dutch";
$template['index']['polish']="Polish";
$template['index']['portuguese']="Portuguese";
$template['index']['brazilian']="Brazilian";
$template['index']['serbian']="Serbian";
$template['index']['hungarian']="Hungarian";
$template['index']['croatian']="Croatian";
$template['index']['latvian']="Latvian";

// the project
$template['index']['theproject']="the project";
$template['index']['status']="status";
$template['index']['features']="features";
$template['index']['license']="license";
$template['index']['require']="requirements";
$template['index']['screens']="screenshots";
$template['index']['bugtrack']="KVIrc bugtrack";
// running kvirc
$template['index']['running']="running KVIrc";
$template['index']['download']="download";
$template['index']['releases']="official releases";
$template['index']['snapshots']="snapshots";
$template['index']['svn']="SVN";
$template['index']['install']="installation";
// documentation
$template['index']['docs']="documentation";
$template['index']['faq']="FAQ";
$template['index']['kviman']="KVIrc manual";
$template['index']['tutorials']="tutorials";
$template['index']['translations']="translations";
// graphic suite
$template['index']['graphsuite']="graphic suite";
$template['index']['themes']="themes";
$template['index']['splash']="splash screens";
$template['index']['banners']="banners";
$template['index']['arts']="arts";
// misc
$template['index']['misc']="misc";
$template['index']['honor']="honor &amp; glory";
$template['index']['scripts']="scripts";
$template['index']['addons']="addons";
$template['index']['tools']="tools";
$template['index']['changelog']="changeLog";
$template['index']['svncommits']="SVN commits";
// contact
$template['index']['contact']="contact";
$template['index']['ml']="KVIrc mailing list";
$template['index']['archive']="archive";
$template['index']['contribute']="collaboration";
$template['index']['help']="finding help";
$template['index']['donation']="make a donation";
// forum
$template['index']['forum']="forum";
// other
$template['index']['quickdnl']="quick download";
// search
$template['index']['search']="Search";
$template['index']['go']="GO";
// news
$template['index']['latestnews']="latest news";
$template['index']['allnews']="All News";
// mirrors
$template['index']['mirrors']="mirrors";
$template['index']['wwwmirrors']="WWW mirrors";
$template['index']['ftpmirrors']="FTP mirrors";
$template['index']['mirrorstext1a']="Contributing to the KVIrc project by mirroring its files is really easy and appreciated; in";
$template['index']['mirrorstext1b']="this page";
$template['index']['mirrorstext1c']="you'll find step by step instructions to create a www or ftp mirror (or both).";
$template['index']['mirrorstext2']="Also, non European ftps are gladly needed.";
$template['index']['mirrorstitle']="www and ftp mirroring";
// layouts
$template['index']['oldlayout']="old site layouts";
$template['index']['oldsite']="old KVIrc site";
$template['index']['iakkohome']="iakko's home";
// help
$template['index']['helptext1a']="if you need any help the fastest way is to refer to the";
$template['index']['helptext1b']="KVIrc public mailing list";
$template['index']['helptext1c']="or join dedicated channels";
// bugs
$template['index']['bugreport']="bug report";
$template['index']['bugstext']="bugs can be reported and viewed by using the KVIrc bugtrack system available at the";
// more docs
$template['index']['moredocs']="more docs";
$template['index']['officialdocs']="KVIrc official documentation";
$template['index']['docsauto']="autogenerated index query";
// other
$template['index']['latestscreen']="latest screenshot";
$template['index']['footer']="this site is best viewed with a monitor";
/* index.php end */

/* custom vars start */
$template['custom']['author']="Author";
$template['custom']['description']="Description";
$template['custom']['homepage']="Homepage";
$template['custom']['download']="Download";
$template['custom']['date']="Date";
$template['custom']['size']="Size";
$template['custom']['version']="Version";
$template['custom']['type']="Type";
/* custom vars end */

/* addons.php start */
$template['addons']['title']="Addons";
$template['addons']['text1']="Here you can find a set of script-based addons for KVIrc";
$template['addons']['text1b']="
	All of these require at least version 3.2.1 (SVN snapshot).<br />
	Please, <b>choose your version</b> of KVIrc";
$template['addons']['text2']="To install an addon";
$template['addons']['tree1']="<b>Download</b> the addon and <b>unzip</b> it somewhere";
$template['addons']['tree2']="
	Press <b>CTRL+Alt+M</b> to open the Addon Management dialog (or open it from the Settings menu)";
$template['addons']['tree3']="Press the \"<b>Install Addon</b>\" button on the right";
$template['addons']['tree4']="
	Navigate to the place where you have unzipped the addon and select the <b>install.kvs</b> file";
$template['addons']['sorry']="Sorry, no addons were found for the specified version of KVIrc";
$template['addons']['addon1']="Automatically enters away state after a period of inactivity";
$template['addons']['addon2']="Provides toolbar buttons for several commonly used channel operations";
$template['addons']['addon3']="Shows Statistics for a joined channel";
$template['addons']['addon4']="A simple script to know where a host come from";
$template['addons']['addon5']="Automatically enters cryption-data for your crypted objects";
$template['addons']['addon6']="Provides shortcuts and toolbar buttons for EZBounce IRC proxy commands";
$template['addons']['addon7']="A simple one-o-one game";
$template['addons']['addon8']="A simple F-Server";
$template['addons']['addon9']="A simple script for lol and kiss with F3-F8 keys and for funny writing";
$template['addons']['addon10']="A simple script for announcing mp3s that are played and sharing option";
$template['addons']['addon11']="A nice \"time eater\"";
$template['addons']['addon12']="Displays RSS news feeds from various sources";
$template['addons']['addon13']="
	Allows advertising and eventually sharing the currently played media on IRC channels and queries";
$template['addons']['addon14']="A simple script to manage public lessons";
$template['addons']['addon15']="Implements a simple Quiz Bot";
$template['addons']['addon16']="Allows sending SMS messages through several web-based services";
$template['addons']['addon17']="It allows the user to warn, kick, and ban who says forbidden words";
$template['addons']['addon18']="An auto op/voice/ban system for your channels (addon from the Twins script)";
$template['addons']['addon19']="
	Colorizes your input text in channel, queries and DCC chats (addon from the Twins script)";
$template['addons']['addon20']="A simple lag bar with three different colors (addon from the Twins script)";
$template['addons']['addon21']="
	Remote control your media player with a simple user interface, and offer your music to other users (addon from the Twins script)";
$template['addons']['addon22']="Check previous host of an user";
$template['addons']['addon23']="Simple icons sets changer. You can choose old icons, new icons with old smiles or new icons";
/* addons.php end */

/* archive.php start */
$template['archive']['title']="Mailing List Archive";
$template['archive']['text']="
	Here you can find the mailing list archives: this is the first place to look at if you have any problem.<br />
	You can browse the archive manually or use the form below to search in.";
$template['archive']['search']="Google Search";
$template['archive']['jan']="January";
$template['archive']['feb']="February";
$template['archive']['mar']="March";
$template['archive']['apr']="April";
$template['archive']['may']="May";
$template['archive']['jun']="June";
$template['archive']['jul']="July";
$template['archive']['aug']="August";
$template['archive']['sep']="September";
$template['archive']['oct']="October";
$template['archive']['nov']="November";
$template['archive']['dec']="December";
/* archive.php end */

/* arts.php start */
$template['arts']['title']="Arts";
$template['arts']['text']="A collection of miscelaneous arts related to KVIrc.";
$template['arts']['desc1']="
	Six colorful variations of a nice comix-like theme for these splash screen replacements. Just save the choosen image as \$HOME/.kvirc/pics/kvi_splash.png. You can also use these nice splashes as banners or as starting point for your own art.
	";
$template['arts']['desc2']="Yet another vision of \"Marmalade\" by suspiria :)";
$template['arts']['desc3']="Huh ?";
$template['arts']['desc4']="A starting point for an avatar.";
$template['arts']['desc6']="She uses this as splash screen... :)";
/* arts.php end */

/* banners.php start */
$template['banners']['title']="Banners";
$template['banners']['text1']="
	This is a collection of KVIrc banners made by various artits: just save the image and use it on your own site :)";
$template['banners']['text2']="Send your banners to";
$template['banners']['bannerby']="Banners By";
/* banners.php end */

/* contribute.php start */
$template['contribute']['title']="Getting Involved";
$template['contribute']['text1']="
	The KVIrc project is open to contributions in many ways. You can get involved in different tasks that require various degrees of development skill (from \"almost none\" to \"guru\").";
$template['contribute']['text2']="Contributing code";
$template['contribute']['text3']="
	The main task is obviously code writing. The developement of the KVIrc core and external modules requires a reasonable knowledge of C++.<br />
	The KVIrc GUI uses the Qt library (and eventually KDE) thus some knowledge of these libraries might be needed too. There are many areas of interest in the source tree: networking, cryptography, data compression, language parsers...<br />
	Every level of conribution is precious: from two-line patches to core feature implementation and manteinance.";
$template['contribute']['text4']="Contributing artwork";
$template['contribute']['text5']="
	The \"V\" in KVIrc stands for \"Visual\". Graphics help the users in navigating the program interface and recognizing quickly the many functions the program provides. We need icons, dialog images, splash-screens, logos, a mascotte character... A nice idea would be to implement a complete theme of graphics...";
$template['contribute']['text6']="Contributing documentation";
$template['contribute']['text7']="
	Documentation is as important as the program itself.<br />
	Many KVIrc features are invisible to the average user just because they're not mentioned in any publicly available document.<br />
	Contributing documentation means: collecting FAQs and putting them in a readable and searchable form, writing documents about specific features, writing tutorials.<br />
	A well-written \"introduction to KVIrc for beginners\" is needed (this could be a sort of introduction to IRC too).";
$template['contribute']['text8']="Translating KVIrc messages";
$template['contribute']['text9']="
	KVIrc is a text-based application: the interface strings need to be translated to as many languages as possible. You only need the knowledge of a non-English language: the translation scheme is gettext based and requires very little knowledge about coding.";
$template['contribute']['text10']="Translating documentation";
$template['contribute']['text11']="
	The most basic parts of the documentation should be translated to non-English languages so that everyone can understand fully the \"core\" features of KVIrc.<br />
	This requires yet less coding knowledge than translating messages.";
$template['contribute']['text12']="Site management/development";
$template['contribute']['text13']="
	The web site needs to be extended and mantained.<br />
	For this task you need knowledge of php, xhtml, css and some ideas :)";
$template['contribute']['text14']="Mirroring";
$template['contribute']['text15']="
	FTP and WWW mirrors are always welcome: we're actually missing mirrors outside Europe.<br />
	The www site is written in php and updated via SVN thus the mirroring machine must have a php-capable web server and a SVN client installed.<br />
	The FTP archive is around 200 MB; partial mirroring schemes can be also arranged.<br />
	The detailed instructions for setting up a www or ftp mirror are available <a href=\"?id=mirroring&amp;lang=$lang\">here</a>.";
$template['contribute']['text16']="Public relations";
$template['contribute']['text17']="
	We need people that talk about KVIrc, write articles, descriptions, reviews, look for contributors...";
$template['contribute']['text18']="Who to contact";
$template['contribute']['text19']="
	Once you decide that you want to contribute in some way you can mail your proposal to <a href=\"mailto:pragma@kvirc.REMOVE.THE.ANTISPAM.WORDS.net\">Pragma</a>.<br />
	Another place where you can announce your availability/proposal is the <a href=\"irc://chat.ircnet.org/#kvirc\">#KVIrc</a> IRC channel on IRCNet, <a href=\"irc://irc.azzurra.org/#KVIrc.net\">#KVIrc.net</a> on Azzurra or <a href=\"irc://irc.freenode.org/#kvirc\">#KVIrc</a> on FreeNode (formerly known as OpenProjects network).";
/* contribute.php end */

/* donate.php start */
$template['donate']['title']="Supporting the KVIrc Project by Money Donations";
$template['donate']['text1']="
	KVIrc is available for free and will always be available for free: no payment is required to download, use, modify and redistribute the source code.";
$template['donate']['text2']="
	Most of the physical resources that KVIrc lives from (such as www or ftp servers) are contributed for free by the KVIrc team members. On the other side the project requires an incredible amount of coding hours as well as several things that need to be paid for such as hardware upgrades, domain name registrations, hosting fees, books... If you enjoy KVIrc please consider supporting the project financially: you can make the donation by using PayPal.";
$template['donate']['text3']="
	The button below will bring you to the PayPal site where you will be able to specify the donation amount and the currency you want to use. You can donate any amount you wish: all will be appreciated. If you have never used PayPal before, then the site will ask you about your credit card details, your country, address and your home phone number. This information is required by PayPal to do the money transaction and is not required by or visible to the KVIrc team.";
$template['donate']['text4']="
	After you have made the donation you will be contacted by e-mail and asked if your donation can be listed on this page. Once the donated money is used, its destination will be listed along with the donator and the donation amount.";
$template['donate']['text5']="Thank you! :)";
$template['donate']['title2']="Recent Donations";
$template['donate']['donation']="donated by";
$template['donate']['alttext']="Make a donation to the KVIrc Project by PayPal";
/* donate.php end */

/* download.php start */
$template['download']['title']="Downloading KVIrc";
$template['download']['text1']="You can obtain KVIrc in three ways:";
$template['download']['text2']="Official release packages";
$template['download']['text3']="
	The official packages are released least frequently but are the most stable ones. Each official source package is well tested and will probably compile on your system. You also have more possibilities to find a binary package suitable for your system. The on-line FAQs and documentation refer to this type of package.";
$template['download']['text4']="Development snapshots";
$template['download']['text5']="
	The development snapshots are unofficial packages extracted from the SVN on a non-regular basis. Each snapshot reflects the SVN state on a particular revision and you're likely to find a really recent one. The packages have been tested on at least a couple of systems and have a good possibility to compile on yours. There are also some binary builds available.";
$template['download']['text6']="Up to date sources from SVN";
$template['download']['text7']="
	The latest bleeding-edge sources can be downloaded by using the SVN system. We're trying to keep the SVN as \"clean\" as possible but finally the sources are not guaranteed to compile. The SVN method provides only sources: there are no binaries.";
/* download.php end */

/* faq.php start */
$template['faq']['title']="FAQ";
$template['faq']['text1a']="How do i join a channel";
$template['faq']['text1b']="Type \"/join #channelname\"";
$template['faq']['text2a']="I can't compile kvirc (any version)";
$template['faq']['text2b']="
	READ the instructions in the INSTALL file: the most common problems can be solved by setting the correct enviroinement variables and fiddling with the ./configure options. If the INSTALL file doesn't help you you can try to join #kvirc on IRCNet or FreeNode: there are many experienced users that can try to help you. If you still can't get out of it, you might try posting your error on the KVIrc mailing list";
$template['faq']['text3a']="I can't connect to an IPV6 server";
$template['faq']['text3b1']="
	First of all make sure that your IPV6 stack is setup correctly.<br />
	Can you ping6 other IPV6 other machines";
$template['faq']['text3b2']="
	Is the IPV6 support enabled in your kvirc executable.<br />
	To find it out, try";
$template['faq']['text3b3']="
	in the KVIrc commandline. You should get a comma separated list of features compiled in the executable. If the list contains \"IPv6\" then the support is compiled in, otherwise you must check your compilation stage to guess what went wrong.
	To connect to an IPV6 server you can use /server -i &lt;servername&gt;
	If you can ping other IPV6 machines, the IPv6 support is compiled in your executable and you still can't connect to an *existing* IPv6 server then you may have found a bug :) Report it";
$template['faq']['text4a']="How do i autojoin channels";
$template['faq']['text4b1']="
	There are many ways to do it.
	For example";
$template['faq']['text4b2']="
	Select \"Scripting/Events\" from the KVIrc menu<br />
	Lookup the \"OnIrc\" entry in the left pane of the window that pops up.<br />
	Right-click on that entry and select \"Add handler\".<br />
	A \"default\" handler will be created. In the right pane write:<br />
	join #kvirc<br />
	join #kde-users<br />
	join #somechannel<br />
	....<br />
	Now click OK and you're done: you have just created a handler for an event.<br />
	Reconnect to a server and KVIrc will autojoin the channels that you have selected";
$template['faq']['text4b3']="
	Another option (nicer, if you use several servers) is to go to the servers options page and click the button labeled 'Advanced' on the entry for the single server.<br />
	There is a server-specific \"On connect execute...\" event";
$template['faq']['text5a']="On Windows KVIrc seems to slow-down sometimes";
$template['faq']['text5b']="
	This is usually caused by the heavy graphics: try removing some graphic effects like the pseudo-transparency. I have experimented that it happens almost always on 32-bit displays. Switching to 16 or 24 bits may also help";
$template['faq']['text6a']="How do I connect to an SSL-enabled IRC server";
$template['faq']['text6b1']="Use";
$template['faq']['text6b2']="It should work also over IPv6.<br />
	If it doesn't work then your executable might have no SSL support compiled in.<br />
	To find it out type";
$template['faq']['text6b3']="in the KVIrc commandline. If \"SSL\" is not in the list then you must go back to the compilation phase and see what went wrong";
$template['faq']['text7a']="How do I use DCC over SSL";
$template['faq']['text7b']="should work";
$template['faq']['text8a']="Do I need a SSL certificate";
$template['faq']['text8b']="No you shouldn't need it, but you can use it if you want";
$template['faq']['text9a']="How do I create a SSL certificate";
$template['faq']['text9b']="
	A test self-signed certificate can be created by using the CA.pl perl script included in the OpenSSL distribution. It will be something like";
$template['faq']['text10a']="I can't get KVIrc to use my SSL certificate in a DCC";
$template['faq']['text10b']="
	The SSL protocol doesn't require the \"client\" to send the certificate: it is sent only if the \"server side\" requests it (it is not the KVIrc case).<br />
	The server side may have a certificate and you can set it in the SSL options page.<br />
	If your Private Key is stored in the certificate file pass the same filename to both Certificate and PrivateKey option.<br />
	Remember to set the password if needed";
$template['faq']['text11a']="KVIrc crashes when a certificate is used under Windows";
$template['faq']['text11b']="
	This is probably a bug of the SSL dll shipped with the windows version of KVIrc.<br />
	You might try with a different version of this dll";
$template['faq']['text12a']="/me doesn't support the '\$' character";
$template['faq']['text12b']="
	This is NOT a bug : this is a feature : kvirc supports (and substitutes!) variables in all the commands. You can escape your $ sign by using the backslash character: /me has gained \\\$100 will work correctly";
$template['faq']['text13a']="/me doesn't support the '&quot;' (double quote) character";
$template['faq']['text13b']="
	This is NOT a bug : this is a feature : a string enclosed in double quotes will have its whitespace preserved while the other strings will have the whitespace simplified. This is valid for ANY command.<br />
	You can escape your &quot; sign by using the backslash character: /me feels a bit \\\"foo\\\" will work correctly";
$template['faq']['text14a']="/me can't contain the ';' character";
$template['faq']['text14b']="
	This is NOT a bug : this is a feature : kvirc supports multiple commands on a single line and uses ';' as a command separator. You can escape your ';' sign by using the backslash character: /me is hungry \;) will work correctly";
$template['faq']['text15a']="I don't see the channel popup menus anymore";
$template['faq']['text15b']="
	If something went wrong with KVIrc settings (a crash when the script settings were saved ?) or if you have messed with the scripting options and you want to get back the original behaviour (default script) you can choose \"Scripting/Restore default script\" from the KVIrc menu.<br />
	(<b>WARNING:</b> It will erase any script modification you have made!)";
$template['faq']['text16a']="
	I'm getting compile errors like this:<br />
	&nbsp; &nbsp; In file [somefile]:[someline] internal error:<br />
	&nbsp; &nbsp; Segmentation fault<br />
	&nbsp; &nbsp; Please submit a full bug report,<br />
	&nbsp; &nbsp; with preprocessed source if appropriate.<br />
	&nbsp; &nbsp; See &lt;URL:http:...";
$template['faq']['text16b1']="This error can have multiple reasons";
$template['faq']['text16b1a']="
	A compiler bug: my GCC 3.2 20020903 (default on RH 8.0) spits out 5-6 of them daily. Usually it is solved by simply restarting the \"make\" command.<br />
	If it doesn't go away or if it gets really frequent and annoying you might try to upgrade the compiler";
$template['faq']['text16b1b']="
	A memory corruption: this is really frequent: one of your memory banks is spitting random bytes sometimes. Usually the problems come out under heavy system load (kernel, KDE or kvirc compilation for example). You can check for memory corruption by trying different RAM modules (or removing them one at a time to discover the broken bank). You can also try a program called memtest and a kernel patch that can force the broken memory banks to be ignored by the kernel (allocated permanently to a dummy kernel task).<br />
	These tools can be found by digging the web with your favorite search engine";
$template['faq']['text16b1c']="
	A deeper hardware problem: if upgrading the compiler and changing memory banks doesn't help then it *might* be a deeper hardware problem: bus errors , faulty IDE (or SCSI) controller or even buggy CPU... Well";
$template['faq']['text17a']="KVIrc crashes when an URL is printed in the output window";
$template['faq']['text17b']="
	This might be caused by the URL module: the causes are being investigated.<br />Try";
$template['faq']['text18a']="KVIrc crashes when the multiline text input is opened (or in the script center)";
$template['faq']['text18b']="
	If you have installed a new version of KVIrc over a previous installation or if you have changed the Qt libraries that KVIrc is linked to then it might be caused by a broken multiline text editor config.<br />
	Try removing \$HOME/.kvircssexeditorrc and starting KVIrc again";
/* faq.php end */

/* features.php start */
$template['features']['title']="Features";
$template['features']['text1']="
	Hmmm.. listing the KVIrc features ?<br />
	Well... why not ?<br />
	Here are some key-phrases that came in my mind.";
$template['features']['tree1']="User interface";
$template['features']['tree1a']="Full GUI Based configuration";
$template['features']['tree1b']="MDI floatable windows";
$template['features']['tree1c']="Built-in help browser";
$template['features']['tree1d']="Themes support (all configurable by GUI or scripting)";
$template['features']['tree1e']="Pseudo-transparency support (up to the desktop on KDE)";
$template['features']['tree1f']="Drag &amp; Drop toolbar editing";
$template['features']['tree1g']="Activity Notifier Pop-Up";
$template['features']['tree1h']="Status bar with Applet support";
$template['features']['tree1i']="Unread text mark";
$template['features']['tree1j']="14 Languages Translations";
$template['features']['tree2']="Network";
$template['features']['tree2a']="Proxy support (SOCKSv4, SOCKSv5, HTTP)";
$template['features']['tree2b']="Full IPv6 support (also for DCC transfers)";
$template['features']['tree2c']="SSL support (also over IPv6)";
$template['features']['tree2d']="Micryption support";
$template['features']['tree3']="Core";
$template['features']['tree3a']="
	Modular architecture: unfrequently used features reside in external modules and are loaded only when necessary";
$template['features']['tree3b']="Extensibility: a huge API for writing extension modules";
$template['features']['tree3c']="UNICODE support";
$template['features']['tree4']="IRC";
$template['features']['tree4a']="Multiserver connection";
$template['features']['tree4b']="Notify lists (yes, WATCH is supported)";
$template['features']['tree4c']="Ignore lists";
$template['features']['tree4d']="Registered users database";
$template['features']['tree4e']="Lag meter";
$template['features']['tree4f']="Configurable logging";
$template['features']['tree4g']="Standard DCC CHAT and SEND (with resume) support";
$template['features']['tree4h']="Extended DCC types: VOICE, RSEND, GET, RECV";
$template['features']['tree4i']="DCC CHAT over SSL";
$template['features']['tree4j']="DCC bandwidth limit (ability to set it \"on the fly\")";
$template['features']['tree5']="Scripting";
$template['features']['tree5a']="Built-in scripting language interpreter";
$template['features']['tree5a1']="scalars, arrays and hashes...";
$template['features']['tree5a2']="aliases";
$template['features']['tree5a3']="popups";
$template['features']['tree5a4']="events";
$template['features']['tree5a5']="scriptable toolbars";
$template['features']['tree5a6']="Perl support";
$template['features']['tree5a7']="Ability to translate scripts (by the means of the tr() function)";
$template['features']['tree5b']="
	Objects support in scripting language: yes, now you can do <acronym title=\"Object Oriented Programming\">OOP</acronym>";
$template['features']['text2']="Hmmm...I hope that's enough to make you curious :D";
/* features.php end */

/* help.php start */
$template['help']['title']="Help Wanted";
$template['help']['text1']="
	The first place to look at when you have a problem is the KVIrc mailing list.";
$template['help']['text2']="
	If something goes wrong, or if you have a question, a suggestion, or are simply interested in KVIrc developement, you can join the";
$template['help']['text3']="
	The developers follow the mailing list and will answer questions as soon as is possible.";
$template['help']['text4a']="The official KVIrc support channel is located on the";
$template['help']['text4b']="Freenode network";
$template['help']['text4c']="and the channel is obviously named";
$template['help']['text4d']="The official Italian channel is";
$template['help']['text4e']="on the";
$template['help']['text4f']="Azzurra network";
$template['help']['text4g']="You can also find some movement on the";
$template['help']['text4h']="IRCNet network";
$template['help']['text4i']="in the";
$template['help']['text4j']="channel too :)";
$template['help']['text5']="Bugs can be reported and viewed by using the";
$template['help']['text6']="
	For suggestions, news, corrections and whatever related with the website please drop an email to";
$template['help']['text7']="
	For any kind of help in graphics, translations, and documentation please contact";
/* help.php end */

/* honor.php start */
$template['honor']['title']="Honor and Glory";
$template['honor']['text1']="This is a list of the people that have contributed in some way to the KVIrc project.";
$template['honor']['text2']="This list is far from being complete. A lot of more or less \"anonymous\" people have wasted their time, eyes, bandwidth and brain resources on this project. If you're one of those, then well, don't hesitate to contact";
$template['honor']['text3']="If your avatar doesn't appear, or it's wrong, send me the right picture. If you've found something incorrect, broken links, or missing on this page, please drop an email to";
$template['honor']['made1']="The \"Creator\" of KVIrc. Mental work, hand work, eyes consuming and coffee drinking";
$template['honor']['quote1']="I'll check... lemme check...&quot;<br />&quot;I'll fix it tomorrow...&quot;<br />&quot;KVIrc: the client that can't make coffee";
$template['honor']['made2']="Webmaster, bughunter, snapshot maintainer, support gay^Wguy :o) and the man that gives you KVIrc through IPv6";
$template['honor']['made3']="Documentation, bug searching, public relations";
$template['honor']['quote3']="No idea of what you're talking about... or why you need it :)";
$template['honor']['made4']="Bug hunting, plugin development, bug fixes, windows porting and snapshots";
$template['honor']['quote4']="&lt;YaP&gt; why you haven't implemented a class like DoEverythingByYourself ? :)&quot;<br />&quot;&lt;Pragma&gt; a wonderful recursive function :)&quot;<br />&quot;&lt;YaP&gt; Damn...I knew it eheheheheh";
$template['honor']['made5']="Test scripter, bug hunting  ideator &amp; creator of the first www.kvirc.net";
$template['honor']['quote5']="whassup?";
$template['honor']['made6']="The official C++ manual and plugin developer";
$template['honor']['quote6']="prepare yourselves..&quot; &quot; #include &lt;iostream.h&gt;&quot;<br />&quot;class testing {...&quot;<br />&quot;&lt;oehansen&gt; I must admit, I'm getting confused :-)&quot;<br />&quot;&lt;Pragma&gt; Me too , at this point :)";
$template['honor']['made7']="Slackware Packages";
$template['honor']['made8']="Italian translation, bug hunting, moral support :))))";
$template['honor']['quote8']="KVIrc? Ah! The dinosaur...";
$template['honor']['made9']="German translation, bug hunting, new ideas. Some scripting, Code improvements + new code ;)";
$template['honor']['quote9']="Pragma: Short question...";
$template['honor']['made10']="Breaking everything, and correcting grammar when there isn't anything left to break. Also, listening to Aeri's requests and getting about half of them done...";
$template['honor']['quote10']="Hey, it's not my responsibility to find a funny quote of myself ^_~";
$template['honor']['made11']="Italian translations, code improvements and many useful suggestions";
$template['honor']['made12']="Official polish beer provider and plugin developer";
$template['honor']['quote12']="echo &quot;STOP IT&quot; &gt; /dev/neighbour&quot; &quot;cd ./neighbour &amp;&amp; make clean&quot;<br />&quot;Pragma...erm...bugs ? WHICH bugs ? ;))";
$template['honor']['made13']="Old site creator, some suggestions, tea drinker (Thanks Szymon, your tea is excellent ;) ) and.. why I'm listed here?";
$template['honor']['quote13']="Hey mum, look!! My name is in the KVIrc Honor &amp; Glory section!!";
$template['honor']['made14']="Newsauthor, bugtracker and constant user support on #kvirc";
$template['honor']['made15']="French translation, betatesting and heavy bughunting";
$template['honor']['made16']="Object classes developer, code improvements, betatesting, bugfixing, exotic scripting, documentation...";
$template['honor']['quote16']="&lt;Grifisx&gt;...damned brackets ! ...there are always too many...<br />&lt;Noldor&gt;....or too few...";
$template['honor']['made17']="Object classes developer, code improvements, betatesting, bugfixing, exotic scripting, documentation...";
$template['honor']['quote17']="&lt;Grifisx&gt; The difference between me and you is just that, You see things and you say &quot;Why?&quot; But I dream things that never were and I say...&quot;Why not?";
$template['honor']['made18']="Internationalization, bugfixing, bughunting, new ideas and more...";
$template['honor']['made19']="New site creator, site mantainer, Italian translation, scripting, bughunting, Slackware packages, new ideas...";
$template['honor']['quote19']="&lt;HelLViS69&gt; Blessed gdb, in the name of ritchie, kerningham and rms";
$template['honor']['made20']="Italian translation, graphics, true believer";
$template['honor']['quote20']="Time makes no sense";
$template['honor']['made21']="FAQ and Italian translations";
$template['honor']['made22']="Debian packages, moral support";
$template['honor']['quote22']="One must make one's self superior to humanity, in power, in loftiness of soul, in contempt. - Friedrich Nietzsche";
$template['honor']['made23']="Bug hunting and fixing, doc fixes, scripting (NGL File Server)";
$template['honor']['quote23']="I don't know what I want, but I know how to get it.";
$template['honor']['made24']="Away system, colored nicks, general programming, spanish translantation";
$template['honor']['quote24']="Pragma: think of KVIrc as a tool for scripters... we have to left them something to do :)";
$template['honor']['made25']="The 'light' inside the GNU clouds. Generic (??!) official project supporter :)";
$template['honor']['quote25']="Pragma: seems that kvirc with all its plugins is becoming a desktop environment&quot; &quot;echo espresso &gt; /dev/coffee&quot; &quot;Pragma: you reached the user limit. WTF!";
$template['honor']['made26']="Ideator of www.kvirc.org";
$template['honor']['quote26']="This free project is better that shareware&quot; &quot;mIrc for windows even in alpha stage";
$template['honor']['made27']="Makes sure that nobody is lazy, bug-hunter, a LOT of suggestions and maker of RealityX IRC.";
$template['honor']['quote27']="Skydiving is almost as exciting as KVIrc scripting!&quot;<br />&quot;Pragma: could you add these functions: \$rubmyback() and \$makecoffe()?";
$template['honor']['made28']="Debugging and improvements.";
$template['honor']['quote28']="I'm just *really* good at doing things when I have no idea of what I'm actually doing";
$template['honor']['made29']="Improvements of KVIrc code and of my linux knowledge. I like to think him as a 'spiritual guide'... :D";
$template['honor']['made30']="The KDE man! Making sure that KVIrc has a reason to have a K in the beginning";
$template['honor']['quote30']="Could I please make KVIrc a pure KDE application today?? Pleeease...";
$template['honor']['made31']="Some \"tiny\" pieces of code.";
$template['honor']['quote32']="&lt;Error403&gt;Number1: I imagined you looking crazy :)&quot;<br />&quot;&lt;NumeroUno&gt; I was drunk";
$template['honor']['made33']="The \"open hand\" for the KVIrc project. Provider of the SVN service, www &amp; ftp mirroring, bandwidth, great ideas and fun while coding.";
$template['honor']['made34']="Bug hunter, ideas source :)";
$template['honor']['quote34']="buy a pigeon traveller and pass dcc transfers to him";
$template['honor']['made35']="Various funky improvements.";
$template['honor']['quote35']="I can program anything I set my mind to!";
$template['honor']['made36']="Beta testing, language structure improvements.";
$template['honor']['quote36']="...it's enough for 100 IPs per meter on earth, so every lightswitch can have its own IP...then you telnet to your lightswitch and turn it off!";
$template['honor']['made37']="MacOSX porting";
$template['honor']['made38']="Portuguese translation, default script patches.";
$template['honor']['made39']="Russian translation";
/* honor.php end */

/* install.php start */
$template['install']['title1']="Installation";
$template['install']['title2']="Guru Installation";
$template['install']['title3']="Hacker Installation";
$template['install']['title4']="Human (detailed) Installation";
$template['install']['text1']="General notes for the installation of the release 3.2.0 of KVIrc";
$template['install']['text2']="You NEED automake 1.5";
$template['install']['text3']="If you're compiling the SVN version of KVIrc run ./autogen.sh";
$template['install']['text4']="your qtlibrary path";
$template['install']['text5']="eventually";
$template['install']['text6']="your kde library path";
$template['install']['text7']="We're using GNU tools here.";
$template['install']['text8']="your options";
$template['install']['text9']="
	If you're not a guru, or have problems with the installation read these instructions carefully.";
$template['install']['step']="Step";
$template['install']['text10']="
	If (and ONLY IF) you're compiling the SVN version of KVIrc you need to generate the configure script.";
$template['install']['text11']="
	If it does not run correctly, check your automake version.<br />
	You need automake 1.5, older versions will NOT WORK with the current SVN.<br />
	You can check the automake version with the command";
$template['install']['text12']="
	If your automake version is lower than 1.5 upgrade it.<br />
	You can find it at http://www.gnu.org/software/automake/ (source version) or on your favorite distribution site as auto-installing package.<br /><br />
	Automake installation tip: automake installs in /usr/local/ by default.<br />
	If you have an older automake installation that resides in /usr/ it's better to remove it: the files to be removed are /usr/bin/automake /usr/bin/aclocal /usr/share/automake /usr/share/aclocal<br />
	If you feel unsure about removing it, rename it.<br />
        Also make sure that /usr/local/bin is in your \$PATH.<br /><br />
	If you have downloaded the sources as tar.gz (or tar.bz2) package or if you don't even know what SVN is, ignore this step and skip to the next one.";
$template['install']['steptitle1']="Matching the requirements";
$template['install']['tree1a']="
	You need the Qt library.<br />
        You can download the latest version from ftp.trolltech.com.<br />
        The main Qt www site is www.trolltech.com.<br />
        Note for the GPL maniacs: Qt IS GPL.<br />
        The minimum required version is 3.0.5 (older versions *might* work)<br />
        Download and install it by following the rules explained in the documentation that comes with the library";
$template['install']['tree1b']="
	You need a decent pthread implementation.<br />
        This is usually included in your distribution and is probably already installed. The library is libpthread.so.<br />
        You can look for it with the \"find\" command";
$template['install']['tree1btext1']="On my system the output is";
$template['install']['tree1btext2']="
	If you don't have it (the configure script will tell you) you can download it from your favorite GNU mirror.<br />
        On Solaris you can use the native libthread.so library instead but you will have to pass the specific option to configure (see below).<br />
        FreeBSD has a native implementation of pthreads in libc_r and the gcc compiler has a special -pthread flag to link to it.<br />
        If you're on FreeBSD, use the --with-freebsd-pthread configure option and make sure that you don't have other pthread wrappers installed (that might collide with the native header files).";
$template['install']['tree1btext3']="
	The configure script will also fail if the library is hidden somewhere on your system (eg. not in /lib , /usr/lib or /usr/local/lib): you should probably move it";
$template['install']['tree1c']="
	You need the dynamic linker interface library libdl.so.<br />
        This is usually installed on your system, so don't care until configure complatins about it. Some system have the interface builtin in libc. The configure script can detect it";
$template['install']['tree1d']="
	(Optional) If you want to compile the KDE integration support you obviousy need KDE. The kdelibs package should suffice. On some distros you have to install also kdelibs-devel";
$template['install']['tree1e']="
	(Optional) If you want DCC VOICE to support the gsm codec, you need a recent copy of libgsm. This is not strictly required at compile time since KVIrc will look for the library at run-time, and only if the DCC VOICE with the gsm codec is requested.<br />
        You can check for libgsm using the 'find' command.";
$template['install']['tree1etext1']="The output should be sometihg like";
$template['install']['tree1etext2']="
	This library is included in most distributions. Some distros ship only the static version of the library \"libgsm.a\": if the previous find returned something similar to \"/usr/lib/libgsm.a\" , you might create manually the shared archive by running:";
$template['install']['tree1etext3']="
	If you don't have it installed at all, you might have a look in your distribution CD, or download it from the web";
$template['install']['tree1f']="
	(Optional) If you want the /snd plugin to play various audio formats
        you either need a running artsd , a running esd or a reasonably recent audiofile library.
        Without these KVIrc will be only able to play *.au files";
$template['install']['tree1g']="
	(Optional) If you want to generate the on-line documentation you also need perl: any version will do (I guess)";
$template['install']['tree1h']="
	(Optional) If you want the secure socket layer support to be compiled
        you need the OpenSSL library and headers. (libssl.so e openssl/ssl.h)";
$template['install']['steptitle2']="Running the configure script (mandatory)";
$template['install']['text13']="
	First of all you must run the configure script that will guess some info about your system and prepare the compilation.<br />
        You may try to \"simply run\" it and check if it works...the configure script tries to be smart, but in many cases it will fail.<br /><br />
        So before running the script make sure that the enviroinement variable \$QTDIR points to the right location. This will help in finding the correct version of Qt.<br />
        You might eventually set it with the command:";
$template['install']['text14']="your qt dir";
$template['install']['text15']="
	On my system qt is installed in /usr/local/kde/qt<br />
        so I actually execute";
$template['install']['text16']="
	If you want to compile the KDE support you might want to do the same with \$KDEDIR";
$template['install']['text17']="your kde dir";
$template['install']['text18']="In my case KDE is installed in /usr/local/kde so I use";
$template['install']['text19']="The configure script has a lot of options that can be listed by using";
$template['install']['text20']="Here's a list with explainations (the most common are at the top):";
$template['install']['tree2a']="
	This is for debugging and reporting problems. It sets the compiler options in order to leave the debugging informations into the kvirc executable and the libraries.
	In this way you will be able to produce a gdb backtrace in case of a crash.<br />
	YOU NEED THIS OPTION IF YOU WANT TO REPORT A PROGRAM CRASH";
$template['install']['tree2b']="
	Asks the compiler to use pipes instead of files for the compilation stage. The pipes will help in reducing disk usage and will probably shorten the compilation a bit. Use this option if your platform supports it";
$template['install']['tree2c']="
	This is an experimental support for object prelinking that improves significantly the executable startup time. In order to use it you need to have the \"objprelink\" program in the PATH. The objprelink program is included in the distribution in the admin directory. In order to use it, you will need to:";
$template['install']['tree2ctext1']="somewhere_on_your_path";
$template['install']['tree2ctext2']="All this AFTER running ./configure and BEFORE running make";
$template['install']['tree2d']="
	KVIrc contains some ix86 assembly routines that could performs some things faster (this is not always true, depends on the compiler). You might want to try it";
$template['install']['tree2e1']="NUMBER";
$template['install']['tree2e']="
	Enables the compiler optimisation flag -o&lt;NUMBER&gt;.<br />
	Possible values are 0 , 1, 2 and 3 (but if you compiler supports more optimisation levels, you might use other numbers here).<br />
	Increases compilation time but may produce a slightly faster executable";
$template['install']['tree2f']="
	Do not check if the pthread stuff works.<br />
	If configure fails in the pthread library check , you might want to try this...(but then you will have really to \"pray\" that the check has been broken by some \"unusual\" conditions and the compilation will succeed)";
$template['install']['tree2g']="
	Specifies explicitly the path to the X header files. You might want to use this if the configure script has trouble in finding it";
$template['install']['tree2h']="
	Specifies explicitly the path to the X libraries. You might want to use this if the configure script has trouble in finding it";
$template['install']['tree2i']="
	Use &lt;NAME&gt; instead of \"qt\" as the Qt library name.<br />
	This is useful on systems where Qt has been installed with a name different than the default \"qt\".<br />
	It happens often that to allow multiple copies of qt to work the newest have the version name appended to it.<br />
	For example, on FreeBSD I have found \"qt\" being Qt1.* and \"qt2\" being Qt 2.*. Since you need Qt 3.* for kvirc to work, you will need to use --with-qt-name=qt3.<br />
	If you use this option, you will probably also need to remap the moc compiler path/name with --with-qt-moc";
$template['install']['tree2j']="
	Disable checking for the multithreaded version of Qt. By default, KVIrc will try to link to the multithreaded version if found on the system.<br />
	NOTE: if you enable the KDE support , KVIrc MUST be linked to the qt library that KDE is linked to";
$template['install']['tree2k']="
	Look for the qt library in &lt;DIR&gt;.<br />
	You might want to use this if the configure script has trouble in finding the qt library.<br />
	You should have no problems if you use export QTDIR=\"&lt;DIR&gt;\" before launching the configure script, but it might help you if you have a non standard Qt installation";
$template['install']['tree2l']="
	Look for the qt headers in &lt;DIR&gt;.<br />
	You might want to use this if the configure script has trouble in finding the qt headers.<br />
	You should have no problems if you use export QTDIR=\"&lt;DIR&gt;\" before launching the configure script, but it might help you if you have a non standard Qt installation";
$template['install']['tree2m']="
	Use the qt meta-object compiler found in &lt;PATH&gt;<br />
	The path is usually \$QTDIR/bin/moc , and the configure script will find it if you have a standard Qt installation and \$QTDIR points to the right directory.<br />
	Thus should have no problems if you use export QTDIR=\"&lt;DIR&gt;\" before launching the configure script, but it might help you if you have a non standard Qt installation.<br />
	This will also help if you have the moc compiler renamed in some way: like \"moc2\" or sth...<br />
	&lt;PATH&gt; in this case is a FULL path: directory/program_name!";
$template['install']['tree2n']="
	This disables Qt checking at compilation time.<br />
	If this is the only way to compile and run the kvirc executable , then there is something wrong with the configure script";
$template['install']['tree2o']="
	The configure script will look for the KDE headers and libraries and if found it will enable the KDE support. If you don't want the KDE support even if KDE is detected, just use this switch";
$template['install']['tree2p']="
	Look for the KDE libraries in &lt;DIR&gt;<br />
	If \$KDEDIR points to the right place, you shouldn't need this";
$template['install']['tree2q']="
	Look for the KDE headers in &lt;DIR&gt;<br />
	If \$KDEDIR points to the right place, you shouldn't need this";
$template['install']['tree2r']="
	Install the kde service protocol files in &lt;DIR&gt;<br />
	If \$KDEDIR points to the right place, you shouldn't need this.<br />
	This is also non-critical for kvirc: if the configure script can't find this directory, you will only looose the support for irc:// urls in konqueror";
$template['install']['tree2s']="Similar to --without-qt-check but for KDE";
$template['install']['tree2t']="
	The IPV6 support is compiled by default on the platforms that support it: this option disables it.<br />
	Even if you have a plain IPV4-only connection, you might want to keep the IPV6 support: you will be able to lookup IPV6 hostnames";
$template['install']['tree2u']="
	This will disable the use of the system memmove() memcpy() and memset() functions and enable the bundled implementations. Use it if you have undefined references to these functions while compiling";
$template['install']['tree2v']="
	This is a hack mainly for Solaris.<br />
	Use this option if kvirc exits with no apparent reason and the system prints a message related to an \"Alarm\" :)";
$template['install']['tree2w']="
	Disables the cryptographic engines and the whole cryptography/text-transformation support. Produces a slightly smaller executable.<br />
	Anyway, if you don't know what the ctryptography/text-transformation support is ,I suggest you to avoid using this option";
$template['install']['tree2x']="
	This option disables pseudo-transparency support.<br />
	The pseudo transparency support makes the KVirc windows look like semi-transparent (this is NOT real transparency: this is just a nice-looking hack).<br />
	If KDE support is enabled, KVirc will have an option that makes all windows use a faded KDE desktop background image as background. Without KDE support you will be able to choose a fake background image and use it as background. (You can still choose your desktop wallpaper: this will (more-or-less) work in all the window managers). It is cool-looking but usually eats some memory when enabled. It also eats some executable size.<br />
	So this option allows to disable the pseudo-transparency";
$template['install']['tree2y']="
	If you're on Solaris and don't have the pthread library (A wrapper I guess) you might try this option: it attempts to use the native Solaris threading support";
$template['install']['tree2z']="
	If you're on FreeBSD, you NEED this option. This enables the usage of the native FreeBSD pthread implementation found in libc_r.<br />
	This requires you to use the native gcc compiler: it has a special -pthread flag that enables the linkage to libc_r instead of plain libc";
$template['install']['tree2a1']="Link to libresolv. I guess that this is required for Solaris";
$template['install']['tree2a2']="Link to libsocket. I guess that this is required for Solaris";
$template['install']['tree2a3']="Link to libnsl. I guess that this is required for Solaris";
$template['install']['tree2a4']="
	Link to libcompat. This might be required for some systems...<br />
	but I have no idea which ones. If you find it useful: mail me";
$template['install']['tree2a5']="
	Disables compiler runtime type information generation. This is mainly needed with qt-embedded";
$template['install']['tree2a6']="
	Disables the usage of the XBell function (needed if you want to compile KVIrc with qt-embedded (no X at all))";
$template['install']['tree2a7']="You need this to compile KVIrc with qt-embedded";
$template['install']['tree2a8']="
	Explicitly link to the specified libraries.<br />
	Example: --with-other-libs=\"-lmylib -lstrangesystemsupport -lmybraindamagedsyscallfix\"";
$template['install']['tree2a9']="
	Explicitly add the specified library search paths<br />
	Example: --with-other-ldirs=\"-L/home/pippo/lib/ -L/my/safe/library/place/\"";
$template['install']['tree2b1']="
	Explicitly add the specified include search path<br />
	Example: --with-other-idirs=\"-I/home/pippo/include/ -I/tmp/include/\"";
$template['install']['tree2b2']="
	Disables support for inter-process communication.<br />
	You will be not able to send remote commands to running KVIrc sessions: this basically means that every time you run the KVIrc executable, a new session will be started.<br />
	If you don't use this switch, a new session will be started only if no session is running on the same display or \"new session\" has been forced by a commandline switch.<br />
	If a session is already running, the commandline will be passed to that session via IPC (X-event-based communication). This option saves some KB of the KVIrc executable, so if you're really short in memory, you might use it, otherwise, IPC is a nice feature";
$template['install']['tree2b3']="
	You should not need this option.<br />
	It disables compilation of code that relies on a particular compiler feature (jumping to a dynamic label with a goto). Not all compilers support this , but configure shoud detect it automatically. Anyway , if you get compilation errors on kvi_ircview.cpp, you may try this option...<br />
	This may also help if the configure script seems to hang when checking for the \"compiler dynamic label support\"";
$template['install']['tree2b4']="
	Disables completly the X drawing calls (always enabled with Qt >= 3.0.0). This can help if you have font problems in the view window";
$template['install']['tree2b5']="
	Do not compile the splash screen code.<br />
	This will remove you that nice \"banner\" image that pops up while kvirc is starting up. It will maybe help in making an executable smaller by a couple of KB and save a couple of extra milliseconds during the startup. Use it if you're tring to build a performance critical executable and you're short both in memory and CPU time :)";
$template['install']['tree2b6']="
	This will disable some informational tooltips in the option dialogs. It will help in making a smaller executable and modules. Use this option if you're a KVIrc guru and you don't need tips about using the options";
$template['install']['tree2b7']="
	Explicitly disable the usage of the GSM library. This will disable the DCC VOICE gsm codec but might help when the compilation stops complaining of something related to GSM :)";
$template['install']['tree2b8']="
	Explicitly disable the DCC VOICE sound support. This might help if you have problems in compilation of src/modules/dcc/voice.cpp. It will disable the sound support (and thus make DCC VOICE not usable)";
$template['install']['tree2b9']="
	Disables the secure socket layer support. The SSL support is automatically enabled if OpenSSL is detected at ./configure time. This option forces it to be left out";
$template['install']['tree2c1']="Debug stuff...enables memory allocation profiling (don't use it :)";
$template['install']['tree2c2']="
	Enables malloc() memory checks. This will print a nice message if your system goes out of memory... It can't save you from buying new RAM, but at least you will know that your system went out of memory and it is not a proper kvirc fault. Actually you probably have no reason in using it";
$template['install']['tree2c3']="
	Minor hash table optimisations: higher memory usage but faster user lookups. Use it if you often stay in channels with a lot of users. (this is not critical anyway)";
$template['install']['text21']="So finally you have to run";
$template['install']['text22']="For example, my common options are:";
$template['install']['text23']="On FreeBSD I have found useful this command line:";
$template['install']['text24']="Once the configure script ran succesfully you can go to the next step.";
$template['install']['text25']="Compiling (mandatory)";
$template['install']['text26']="This step is easy:";
$template['install']['text27']="Cross your fingers and run";
$template['install']['text28']="
	If your make is not a GNU make (this happens on FreeBSD for example) you should use \"gmake\" instead.<br />
	The compilation process will take from 6-7 minutes to several hours depending on the machine capabilities and load.<br />br />
	Once the compilation has been succesfull, run";
$template['install']['text29']="
	Same as above: use \"gmake install\" if your make is not GNU make.<br /><br />
        This will install the executable in /usr/local/bin<br />
        (if you don't have specified a different --prefix option in the configure script) , the libraries in /usr/local/lib and the shared data in /usr/local/share/kvirc.<br />
        If you had a previous kvirc installation, the default prefix will be referring to the directory where the old kvirc executable was found.<br /><br />
        Make sure that /usr/local/lib is in your /etc/ld.so.conf, if it isn't there, put it there and run";
$template['install']['text30']="
	If you have decided to use the KDE support the installation might have placed all these files in your \$KDEDIR tree instead of /usr/local. In this case you should be OK since
        KDE requires its library dir to be in /etc/ld.so.conf";
$template['install']['text31']="Having fun";
$template['install']['text32']="That's all folks.";
/* install.php end */

/* license.php start */
$template['license']['title']="The KVIrc License";
$template['license']['text']="KVIrc is a free software: it is released under an extended version of the General Public License.";
$template['license']['text2']="
	This is the KVIrc Irc Client license.<br />
	It is based on the GNU General Public License Version 2.<br />
	It contains all the GPL terms and conditions and adds a special exception (see Terms and Conditions, clause 13) to the distribution limitations.<br /><br />
	Note that the GPL below is copyrighted by the Free Software Foundation, but the instance of code that it refers to is copyrighted by Szymon Stefanek and other members of the KVIrc Development Team.<br /><br />
	The source code for all versions of KVIrc is available at <a href=\"?id=releases&amp;platform=source&amp;lang=$lang\">this url</a>.<br /><br />
	Have fun!";
/* license.php end */

/* mailinglist.php start */
$template['ml']['title']="KVIrc Public Mailing List";
$template['ml']['text1a']="
	If something goes wrong, or if you have a question, a suggestion, or are simply interested in KVIrc developement, you can join the KVIrc public mailing list.";
$template['ml']['text1b']="
	The developers follow the mailing list and will answer questions as soon as is possible.";
$template['ml']['text2']="Web interface";
$template['ml']['text3']="
	The list has a web interface available <a href=\"http://lists.omnikron.net/mailman/listinfo/kvirc/\">here</a>.<br />
	The interface allows you to subscribe, unsubscribe and manage your account.";
$template['ml']['text4']="To subscribe by mail";
$template['ml']['text5']="
	Send an empty mail (empty body, empty subject) to <a href=\"mailto:kvirc-subscribe@lists.omnikron.net\">this address</a> from the address that you want to subscribe.<br />
	In some minutes you will receive a confirmation request mail that will contain the instructions to complete your subscription.";
$template['ml']['text6']="To unsubscribe by mail";
$template['ml']['text7']="
	Send an empty mail (leave body and subject empty) to <a href=\"mailto:kvirc-unsubscribe@lists.omnikron.net\">this address</a> from the address that you want to unsubscribe.<br />
	In some minutes you will receive a confirmation request mail that will contain the instructions to complete your unsubscription.";
$template['ml']['text8']="Mailing list archives";
$template['ml']['text9']="
	The complete archive of the list messages is available <a href=\"http://lists.omnikron.net/pipermail/kvirc/\">here</a>.";
/* mailinglist.php end */

/* mirroring.php start */
$template['mirror']['title']="Mirroring the KVIrc Project";
$template['mirror']['text1']="
	This page contains step by step instructions to create a ftp mirror";
$template['mirror']['text2']="
	Contributing to the KVIrc project by mirroring its files is really easy.<br />";
$template['mirror']['text3']="Non european ftp mirrors are especially needed";
$template['mirror']['title2']="Setting up a mirror of ftp.kvirc.net";
$template['mirror']['tree']="Requirements";
$template['mirror']['tree1']="An ftp server";
$template['mirror']['tree2']="A cron daemon (or equivalent) in order to keep the mirror in sync";
$template['mirror']['text4']="Setup procedure";
$template['mirror']['text5']="
	Setting up an ftp mirror is really easy: it is done by using the mirroring feature of the program";
$template['mirror']['text6']="
	The commandline to retrieve the whole kvirc ftp archive is the following:";
$template['mirror']['text7']="your_ftp_server_root";
$template['mirror']['text8']="
	So all you need to do is to set up your ftp server to accept anonymous connections and instruct cron to sync the mirror every N hours.";
$template['mirror']['text9']="
	Now you need to setup the automatic updates.<br />
	This is usually accomplished by a cron daemon and involves adding a couple of lines to the crontab.<br />
	An example of such a crontab file might be:";
$template['mirror']['text10a']="
	This crontab file tells the cron daemon to run the command";
$template['mirror']['text10b']="at 6.30 am of every day";
$template['mirror']['text11a']="In this case";
$template['mirror']['text11b']="would look as follows:";
$template['mirror']['text12']="yourdomain";
$template['mirror']['text13']="
	At the moment of writing the complete ftp archive is around 500 MB. If you don't have the space for a complete mirror you can achieve partial mirroring by retrieving only a subset of the ftp.kvirc.net directories.";
$template['mirror']['text14']="
	Once you have succesfully set up your mirror please drop a mail to <b>pragma at kvirc dot net</b> or to the <a href=\"?id=mailinglist&amp;lang=$lang\">mailing list</a> so we can link you from the main site.";
/* mirroring.php end */

/* news.php start */
$template['news']['title']="News archives";
$template['news']['latest']="Latest news";
$template['news']['error']="Error reading story";
$template['news']['nonews']="No such news entry.";
$template['news']['news']="News";
$template['news']['readmore']="Read more";
/* news.php end */

/* releases.php start */
$template['releases']['title']="Download Official Releases";
$template['releases']['text1']="
	Here you can download the <b>official release</b> packages of KVIrc.<br />
	The official packages are released least frequently but are also the most stable ones.<br />
	Please select the type of the package that you want to download";
$template['releases']['text2']="
	Below you have a list of available versions for the platform you have selected.<br />Please select the version of the package that you want to download";
$template['releases']['text3']="
	More than one package group is available for the platform and version that you have selected.<br /><br />Please select the group you want to download";
$template['releases']['latest']="Latest release";
$template['releases']['older']="Older releases";
$template['releases']['available']="Available download locations";
/* releases.php end */

/* require.php start */
$template['require']['title']="Requirements (3.0.0 branch)";
$template['require']['tree1']="Unix version (sources):";
$template['require']['tree1a']="A working UNIX system suitable for compiling stuff";
$template['require']['tree1b']="
	The <a href=\"http://www.trolltech.com\">QT GUI toolkit</a> >= 3.0.5 (older versions <b>might</b> work)";
$template['require']['tree1c']="
	<a href=\"http://www.gnu.org/software/automake/\">automake</a> 1.5";
$template['require']['tree1d']="<a href=\"http://www.zlib.org/\">Zlib library</a>";
$template['require']['tree1e']="
	<a href=\"http://www.cpan.org\">Perl</a> (for generating online documentation)";
$template['require']['tree1f']="
	<a href=\"http://www.kde.org\">KDE</a> libs linked to <b>the same</b> version of Qt (optional)";
$template['require']['tree1g']="
	Check if your distro split devel libraries; if so you have to install the packages which contains them. Those packages have often \"-dev\" in their name";
$template['require']['tree2']="Unix version (binaries):";
$template['require']['tree2a']="A working unix system";
$template['require']['tree2b']="
	The <a href=\"http://www.trolltech.com\">QT GUI toolkit</a> >= 3.0.5 (older versions <b>might</b> work)";
$template['require']['tree3']="Windows version (sources):";
$template['require']['tree3a']="
	The free version of the <a href=\"ftp://ftp.trolltech.com\">QT GUI toolkit</a> for Windows >= 2.3.0";
$template['require']['tree3b']="<a href=\"http://www.zlib.org/\">Zlib library</a>";
$template['require']['tree3c']="Some luck";
$template['require']['tree4']="Windows version (binaries):";
$template['require']['tree4a']="Hopefully nothing";
$template['require']['tree5']="Mac OS X (source):";
$template['require']['tree5a']="Follow the instructions in \"doc (INSTALL-MacOS.txt)\"";
$template['require']['tree6']="Mac OS X (binaries):";
$template['require']['tree6a']="
	Hopefully nothing. Just open the .dmg file and drag the icon into your application folder.";
$template['require']['titleold']="Requirements (old 2.1.1 branch)";
$template['require']['treeold1']="A working UNIX system";
$template['require']['treeold2']="The <a href=\"http://www.trolltech.com\">QT GUI toolkit</a> >= 2.3.0";
$template['require']['treeold3']="<a href=\"http://www.kde.org\">KDE</a> libs (optional)";
/* require.php end */

/* screen.php start */
$template['screen']['title']="Screenshots";
$template['screen']['text']="Do you have a nice screenshot? Send it to";
$template['screen']['prev']="previous";
$template['screen']['next']="next";
$template['screen']['screen1']="General Option Dialog";
$template['screen']['screen2']="Script Center";
$template['screen']['screen3']="URL plugin &amp; an object mail script";
$template['screen']['screen4']="More dialogs";
$template['screen']['screen5']="Channel Popup menus";
$template['screen']['screen6']="Channel Ban &amp; Mode Dialogs";
$template['screen']['screen7']="Help and directory browser";
$template['screen']['screen8']="Directory browser";
$template['screen']['screen9']="KVIrc CVS happily running on Solaris";
$template['screen']['screen10']="Window list, DCC send and Userlist Popup";
$template['screen']['screen11']="I/O Graph, Terminal Emulator and Avatars";
$template['screen']['screen12']="3 active server connections";
$template['screen']['screen13']="Avatars, I/O Graph and serverlinks";
$template['screen']['screen14']="Yes! trust your eyes! KVIrc on aberrations :)";
$template['screen']['screen15']="Help window and the dock widget";
$template['screen']['screen16']="Fancy Default Theme with Transfers Window";
$template['screen']['screen17']="Minimalist Theme and one of the contextual pop-up";
$template['screen']['screen18']="
	Four special windows. File transfers, Log View, Terminal and Shared Files: here to simplify your daily ircing.";
$template['screen']['screen19']="Are you a scripter? KVIrc has various tools for you.";
$template['screen']['screen20']="Helix on three servers and a lot of channels";
$template['screen']['screen21']="Helix connecting thru psyBNC and the nice KVIrc desktop shortcut :D";
$template['screen']['screen22']="
	Four servers. Note the tree window on the left showing the most active channels.";
$template['screen']['screen23']="The DCC exploits don't work with KVIrc :)";
$template['screen']['screen24']="A snapshot by bongwater: it is running since 10 days :)";
$template['screen']['screen25']="
	A snapshot by <a href=\"http://kvirc.virg0.org\">etherea`</a>: Time makes no sense";
$template['screen']['screen26']="A shot by Xemanth^: a 'hackish' KVIrc on windows";
$template['screen']['screen27']="
	A snapshot by <a href=\"http://kvirc.virg0.org\">etherea`</a>: Pragma's Newsticker in action :)";
$template['screen']['screen28']="
	A snapshot by <a href=\"http://hellvis69.altervista.org\">HelLViS69</a>: Clonescanner working :)";
$template['screen']['screen29']="
	The Twins' script and its <a href=\"?id=addons&amp;lang=$lang&amp;version=3.2.3\">media player</a> on 'Anomalies'. Also  the new namespace scripting environment in the alias editor window.";
$template['screen']['screen30']="
	The SilverIRC theme, the default since KVIrc 3.2.6 after a fresh installation. Screenshot provided by thexception";
$template['screen']['screen31']="
	SilverIRC theme. The theme manager. Screenshot provided by thexception";
$template['screen']['screen32']="SilverIRC theme. The Aliases Editor. Screenshot provided by thexception";
$template['screen']['screen33']="SilverIRC theme. The Events Editor. Screenshot provided by thexception";
$template['screen']['screen34']="SilverIRC theme. The Popups Editor. Screenshot provided by thexception";
/* screen.php end */

/* scripts.php start */
$template['scripts']['title']="Scripts";
$template['scripts']['text1']="Example scripts are included into the distribution and the SVN";
$template['scripts']['text2a']="Use";
$template['scripts']['text2b']="to install the script. The default script should be installed at";
$template['scripts']['script1']="
	Italian script with autojoin, capscontrol, autovoice... Completely configurable via GUI.";
$template['scripts']['script2']="
	SaNVirC is a script for KVirc that includes functions like nick identification, autojoin, defense, attack, bots management, an away system, etc.<br /> It was written for IRC-Hispano bots but is very easy to adapt to other servers.";
$template['scripts']['script3']="
	Savage Script is a script for Gamers with XQF support, system informations, qauth...";
$template['scripts']['script4']="
	This is the first public release of the script with some improvements for the notify list. It also adds AutoOp, AutoVoice functions, fix OPless chan, etc.";
/* scripts.php end */

/* snapshots.php start */
$template['snapshots']['title']="Development Snapshots";
$template['snapshots']['text1']="
	The development snapshots are unofficial packages extracted from the SVN on a non-regular basis. Each snapshot reflects the SVN state on a particular date and you're likely to find a really recent one. The packages have been tested on at least a couple of systems and have a good possibility to compile on yours. There are also some binary builds available.";
$template['snapshots']['text2']="
	The source snapshots are kindly provided by the KVIrc Development Team.<br />
	Honor and Glory! :)";
$template['snapshots']['text3']="
	To download the latest snapshot you have to dig in 
	<a href=\"ftp://ftp.kvirc.net/pub/kvirc/snapshots/\">the KVIrc ftp</a> or in the \"snapshots\" subdirectory of one of the ftp mirrors.";
/* snapshots.php end */

/* splash.php start */
$template['splash']['title']="Splash Screens";
$template['splash']['text']="This is a collection of splash screens that KVIrc used in the past.";
$template['splash']['date']="Release Date";
$template['splash']['in']="Splash Present in";
/* splash.php end */

/* status.php start */
$template['status']['title']="Project Status";
$template['status']['text']="
	<p>After 7 years of development KVIrc is a mature and full featured IRC client, an excellent companion for your daily IRC sessions.</p>
	<p>The latest stable release is <a href=\"/?id=news&amp;story=2005.02.27.16.29.1.story&amp;dir=2005.02&amp;lang=$lang\">3.2.0 \"Realia\"</a>.
	It has been published on Feb 27 2005.
	It can be obtained in source form from the <a href=\"?id=download&amp;lang=$lang\">download</a> page.</p>
	<p>If you are looking for official releases have a look at <a href=\"?id=releases&amp;lang=$lang\">this section</a>, those are released less often but are most stable. Choose your release between Linux, Windows, MacOSX or source package.</p>
	<p>Snapshots are located <a href=\"?id=snapshots&amp;lang=$lang\">here</a> while SVN are found <a href=\"?id=SVN&amp;lang=$lang\">here</a>.</p>
	<p>Also be sure to check for <a href=\"?id=install&amp;lang=$lang\">installation notes</a>, <a href=\"?id=tutorials&amp;lang=$lang\">tutorials</a>, <a href=\"?id=translation&amp;lang=$lang\">translations</a> and <a href=\"?id=themes&amp;lang=$lang\">themes</a> for a more customized version of your KVIrc =)</p>";
/* status.php end */

/* SVN.php start */
$template['svn']['title']="Checking Out SVN";
$template['svn']['text1']="
	From the SVN server you can download the latest development version of KVIrc.<br />
	Once you've made sure that Subversion is on your system you only need enter this line:";
$template['svn']['text2']="
	You will be downloading the kvirc core sources.<br />
	If you want to checkout also the modules sources you have to enter this line:";
$template['svn']['text3']="
	To compile the executable and the core modules just enter the source directory:";
$template['svn']['text4']="
	and then follow the common <a href=\"?id=install&amp;lang=$lang\">installation instructions</a>.<br />
	The latest installation instructions for the SVN version of KVIrc can be also found in the INSTALL file.<br />
	We're trying to keep the SVN as \"clean\" as possible but it *might* happen that the sources you have downloaded do not compile or run properly.<br />
	You can also browse trough the SVN via <a href=\"https://SVN.kvirc.de/kvirc/browser/\">https://SVN.kvirc.de/</a>";
/* SVN.php end */

/* themes.php start */
$template['themes']['title']="Themes";
$template['themes']['text1']="Here you can download some nice themes";
$template['themes']['text2a']="How can I install a theme";
$template['themes']['text2b1']="Download the theme";
$template['themes']['text2b2']="Unpack the downloaded file in";
$template['themes']['text2b2a']="path to the downloaded theme file";
$template['themes']['text2b3']="Open the KVIrc's Theme Manager";
$template['themes']['text2b4']="Double-click the new theme";
$template['themes']['text2b5']="Enjoy";
$template['themes']['text3a']="How can I create a theme";
$template['themes']['text3b1']="There is a small HOWTO, you can find it";
$template['themes']['text3b2']="here";
$template['themes']['text3b3']="and an Italian version";
$template['themes']['text3b4']="The English HOWTO is also included in the KVIrc distribution package";
$template['themes']['text4a']="I've made a theme. How can I share it";
$template['themes']['text4b']="You can send it to";
$template['themes']['text4c']="including a theme name, description, version, nickname, homepage and email, allowing us or not to display it on the page";
$template['themes']['screenshot']="screenshot";
$template['themes']['theme1']="An eye-candy based on the Marble icon set.";
$template['themes']['theme2']="A clear theme with Crystal icons. Some icons are taken from the Marble icon set.";
$template['themes']['theme3']="A theme with a green background.";
$template['themes']['theme4']="A dark theme.";
$template['themes']['theme5']="White aqua rounded.";
$template['themes']['theme6']="Just a pink example...";
$template['themes']['theme7']="A transparent theme meant mainly for use with the KDE background. Set for good visibility and contrast.";
$template['themes']['theme8']="A quite relaxed theme inspired by the site http://www.PayneReactor.com";
$template['themes']['theme9']="A nice black theme, based on other crystall theme :)";
$template['themes']['theme10']="Another dark theme with Slackware logo and a black baghira";
$template['themes']['theme11']="A dark theme based on XCrystall-black";
$template['themes']['theme12']="Pure Love. Pure White. A clean, neat pure theme";
$template['themes']['theme13']="A glass dark theme";
$template['themes']['theme14']="Yet another dark theme";
$template['themes']['theme15']="A X-mas theme for KVIrc";
$template['themes']['theme16']="Perversion is another way of living; darkly theme with less gamma";
$template['themes']['theme17']="erotica.. mh..";
$template['themes']['theme18']="Anger is a variation of erotica. Keep on lick your lips!";
$template['themes']['theme19']="Dark Blue is a variation of marble. Enjoy it";
/* themes.php end */

/* tools.php start */
$template['tools']['title']="Tools";
$template['tools']['text1']="Here you can find some KVIrc-related tools";
$template['tools']['tool1']="KVS syntax highlight for Notepad++";
/* tools.php end */

/* translation.php start */
$template['translation']['title']="Translations";
$template['translation']['step']="Step";
$template['translation']['text1']="
	In this page you can find some informations on the KVIrc translations status. To see if your language is supported, please look at the list below.";
$template['translation']['text2']="
	Many people are working hard to support as many languages as possible. To join them all you need to know is your own language: <b>no conding skills are needed</b>.";
$template['translation']['text3']="
	All translators <b>MUST USE UTF-8</b> as coding standard. Translation files with other standards will be deprecated.";
$template['translation']['text4']="
	If you are interested in translating KVIrc in a new language you can find here a nice How-To.<br />
	Some language are updated (almost) daily, others need to find a new manteiner. If you want to help to improve the current support of your language, please contact its <b>Last translator</b>, listed here:";
$template['translation']['text5a']="Don't forget to subscribe to the";
$template['translation']['text5b']="to keep in touch with the developers!";
$template['translation']['text6']="This mini-howto describes the procedure for translating KVIrc in a new language";
$template['translation']['text7']="Getting the right sources.";
$template['translation']['text8a']="
	First of all you need the SVN version of KVIrc. To obtain the SVN version you can follow the instructions on";
$template['translation']['text8b']="The translation stuff is in";
$template['translation']['text9']="Finding out your language code";
$template['translation']['text10a']="
	You must find out the contents of your language code. Usually this is a string formed of at least two letters and it can be found by examining the contents of your \$LANG shell variable or by looking";
$template['translation']['text10b']="here";
$template['translation']['text10c']="Examples of such codes are";
$template['translation']['text11']="Generating the list of messages to translate";
$template['translation']['text12']="
	You must perform this step only if it is the first time that KVIrc is translated to your language. If you're going to update an existing translation then you can jump directly to Step 3.<br />
	Run the command to extract the messages from the sources.";
$template['translation']['text13']="
	A file named <code>kvirc.pot</code> will be created. You have to rename this file to <code>kvirc_xxx.po</code>, where xxx is your language code found in Step 1.";
$template['translation']['text14']="Translating the messages";
$template['translation']['text15a']="
	If you did the Step 2 then you have just created the <code>kvirc_xxx.po</code> file where xxx stands for your language code (found in Step 1).<br />
	If you jumped directly here from 1 then you need to find and existing <code>kvirc_xxx.po</code> in the <code>kvirc/po/kvirc</code> directory.<br />
	If there isn't one then go back to Step 2.";
$template['translation']['text15b']="
	The file <code>kvirc_xxx.po</code> contains a set of strings like the following one:";
$template['translation']['text100a']="/path/to/the/file/which/contains/the/string: line number";
$template['translation']['text100b']="Translating the messages";
$template['translation']['text100c']="The translation goes here";
$template['translation']['text16']="
	The <i>msgid</i> is the original message that needs to be translated and <i>msgstr</i> is the translation (that will be initially empty, when the file <code>kvirc_xxx.po</code> is created).";
$template['translation']['text17']="
	The msgid can contain html tags, escapes like \"\\n\" and format specifications like \"%s\". You <b>MUST</b> match the tags, escapes and format specs in the msgstr strings. <b>Keep special attention</b> to the format specifications (%s, %W, %Q...).<br />
	They must remain in <b>EXACTLY the same order</b> as in the msgid: exchanging the order or writing a wrong format spec will make KVIrc crash sooner or later.";
$template['translation']['text18']="Adding the translation to the Makefile.am";
$template['translation']['text19']="
	Once you have translated some strings you can try to run the translation in KVIrc. If you are updating an existing translation then you can jump directly to Step 5.";
$template['translation']['text20']="
	You must force the make process to pick up your translation file and compile it. This is again an one time step. In <code>kvirc/src/kvirc</code> there is a file named <code>Makefile.am</code>. You should edit it and add <code>kvirc_xxx.po</code> where the other *.po files are mentioned. You should have no problems in guessing what needs to be added by looking at the other *.po entries in that file.";
$template['translation']['text21']="Then just run:";
$template['translation']['text22']="
	and you build KVIrc as usual. After it has finished building, run KVIrc after making sure that your \$LANG variable is set correctly.";
$template['translation']['text23']="Trying the translation";
$template['translation']['text24']="Run make and wait until it finishes.";
$template['translation']['text25']="KVIrc should then pick up your translation file and use it.";
$template['translation']['text26']="Updating the translation when the sources change";
$template['translation']['text27']="
	While the development goes on new messages are added to the sources and a small part of the existing messages change. When you do a SVN update to obtain the latest sources you should cd to <code>kvirc/po/kvirc</code> and run:";
$template['translation']['text28']="
	This procedure will update your file <code>kvirc_xxx.po</code> with the new messages and mark the old messages as either <i>fuzzy</i> or invalid. The invalid entries must be re-translated completly again while the <i>fuzzy</i> entries have minor changes and can be probably adjusted in few seconds.";
$template['translation']['text29']="Misc";
$template['translation']['text30']="
	If you're in doubt about some translation, you should take a look at how similar sentences have been translated in the KDE *.po files: there should be a translation file for KDE available on the KDE SVN.";
$template['translation']['text31']="
	Since many of the modules have their own translation files then the procedure above may (but not must) be repeated for the <code>po/modules/*/</code> subdirectories.";
$template['translation']['text32a']="
	When you're satisfied with your translation you may send your *.po files to";
$template['translation']['text32b']="
	asking for inclusion in the SVN. If you want to mantain the translation then you may also ask for a writeable SVN account.";
$template['translation']['text33']="Happy translating :)";
/* translation.php end */

/* tutorials.php start */
$template['tutorials']['title']="Tutorials";
$template['tutorials']['archive']="Complete archive";
$template['tutorials']['tutorial']="Tutorial";
$template['tutorials']['madeby']="made by";
$template['tutorials']['text1a']="The Art Of Scripting";
$template['tutorials']['text1b']="A very rich scripting tutorial";
$template['tutorials']['tree1c']="Language introduction";
$template['tutorials']['tree1d']="Cicles, conditions and aliases";
$template['tutorials']['tree1e']="Arrays, dictionaries, objects and classes";
$template['tutorials']['tree1f']="Events and popups";
$template['tutorials']['tree1g']="Graphical objects and layout";
$template['tutorials']['tree1h']="The wrapper class";
$template['tutorials']['tree1i']="Slots and signals";
$template['tutorials']['tree1j']="Raw events and actions";
$template['tutorials']['tree1k']="Sockets and perl";
$template['tutorials']['text2a']="Win32 KVIrc Compiling";
$template['tutorials']['text2b']="A tutorial to compile KVIrc under Win32";
$template['tutorials']['text3a']="KVIrc Scripting Tutorial For Beginners";
$template['tutorials']['text3b']="A totally beginners guide";
$template['tutorials']['text4a']="KVIrc Installation Under Win32";
$template['tutorials']['text4b']="A short tutorial how to install KVIrc, connect to a server and join a channel on windows";
$template['tutorials']['dropmail']="If you have written a FAQ, tutorial or guide to KVIrc in any language please drop a mail to";
/* tutorials.php end */

/* welcome.php start */
$template['welcome']['title']="Welcome!";
$template['welcome']['text']="
	KVIrc is a <a href=\"http://www.gnu.org\">free</a> portable <acronym title=\"Internet Relay Chat\">IRC</acronym> client based on the excellent <a href=\"http://www.trolltech.com\">Qt GUI toolkit</a>.
	KVirc is being written by <a href=\"http://www.pragmaware.net\">Szymon Stefanek</a> and the KVIrc Development Team with the contribution of many IRC addicted developers around the world.";
$template['welcome']['text2']="be part of the project!";
$template['welcome']['alttext']="how to help the KVIrc project";
/* welcome.php end */
?>