KVIrc: KviThemedLineEdit Class Reference
KviThemedLineEdit Class Reference
#include <KviThemedLineEdit.h>
Public Member Functions
void applyOptions ()
int dummyRead () const
KviThemedLineEdit (QWidget *par, KviWindow *pWindow, const char *name)
~KviThemedLineEdit ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
Properties
int TransparencyCapable
Private Attributes
KviWindow * m_pKviWindow
Constructor & Destructor Documentation
KviThemedLineEdit::KviThemedLineEdit (QWidget * par, KviWindow * pWindow, const char * name)
References applyOptions(), and m_pKviWindow.
KviThemedLineEdit::~KviThemedLineEdit ()
Member Function Documentation
void KviThemedLineEdit::applyOptions ()
References KviMircCntrl::Bold, g_pApp, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_FONT, KVI_OPTION_MIRCCOLOR, KVI_OPTION_MSGTYPE, KVI_OUT_NONE, KviOption_boolUseCompositingForTransparency, KviOption_colorLabelBackground, KviOption_colorLabelForeground, KviOption_fontLabel, KviOsInfo::name(), and KviApplication::supportsCompositing().
Referenced by ListWindow::applyOptions(), KviChannelWindow::applyOptions(), and KviThemedLineEdit().
int KviThemedLineEdit::dummyRead () const [inline]
void KviThemedLineEdit::paintEvent (QPaintEvent * event) [protected, virtual]
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_uintGlobalTransparencyChildFadeFactor, m_pKviWindow, KviMainWindow::mdiManager(), KviWindow::mdiParent(), p, r, KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
Member Data Documentation
KviWindow* KviThemedLineEdit::m_pKviWindow [private]
Referenced by KviThemedLineEdit(), and paintEvent().
Property Documentation
int KviThemedLineEdit::TransparencyCapable [read]
The documentation for this class was generated from the following files:
src/kvirc/ui/KviThemedLineEdit.h
src/kvirc/ui/KviThemedLineEdit.cpp