KVIrc: KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot Class Reference
KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot Class Reference
#include <KviKvsTreeNodeExpression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot (const QChar *pLocation, KviKvsTreeNodeExpression *pData)
virtual int precedence ()
~KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot ()
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot (const QChar * pLocation, KviKvsTreeNodeExpression * pData)
KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::~KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot ()
Member Function Documentation
void KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeExpressionUnaryOperator.
void KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeExpressionUnaryOperator.
References KviKvsTreeNodeExpression::dump(), and KviKvsTreeNodeExpressionUnaryOperator::m_pData.
bool KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand(), KviKvsNumber::integer(), KviKvsNumber::isReal(), KviKvsTreeNodeExpressionUnaryOperator::m_nData, KviKvsNumber::real(), and KviKvsVariant::setInteger().
int KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::precedence () [virtual]
Reimplemented from KviKvsTreeNodeExpression.
References PREC_OP_BITWISENOT.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.h
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.cpp