KVIrc: KviSharedFile Class Reference
KviSharedFile Class Reference
#include <KviSharedFile.h>
Public Member Functions
const QString & absFilePath ()
bool expires ()
time_t expireTime ()
unsigned int fileSize ()
KviSharedFile (const QString &szName, const QString &szAbsPath, const QString &szUserMask, time_t expireTime, unsigned int uFileSize)
int maskLength ()
const QString & name ()
unsigned int nonWildcardCount ()
const QString & userMask ()
unsigned int wildcardCount ()
~KviSharedFile ()
Private Attributes
time_t m_expireTime
QString m_szAbsFilePath
QString m_szName
QString m_szUserMask
unsigned int m_uFileSize
unsigned int m_uNonWildCount
unsigned int m_uWildCount
Constructor & Destructor Documentation
KviSharedFile::KviSharedFile (const QString & szName, const QString & szAbsPath, const QString & szUserMask, time_t expireTime, unsigned int uFileSize)
References expireTime(), m_expireTime, m_szAbsFilePath, m_szName, m_szUserMask, m_uFileSize, m_uNonWildCount, and m_uWildCount.
KviSharedFile::~KviSharedFile ()
Member Function Documentation
const QString& KviSharedFile::absFilePath () [inline]
Referenced by avatar_kvs_cmd_notify(), dccModuleParseDccGet(), dccModuleParseDccRecv(), SharedFileEditDialog::SharedFileEditDialog(), and SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem().
bool KviSharedFile::expires () [inline]
Referenced by SharedFileEditDialog::SharedFileEditDialog(), and SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem().
time_t KviSharedFile::expireTime () [inline]
Referenced by KviSharedFilesManager::addSharedFile(), KviSharedFile(), SharedFileEditDialog::SharedFileEditDialog(), and SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem().
unsigned int KviSharedFile::fileSize () [inline]
Referenced by avatar_kvs_cmd_notify(), dccModuleParseDccGet(), and dccModuleParseDccRecv().
int KviSharedFile::maskLength () [inline]
Referenced by KviSharedFilesManager::doInsert().
const QString& KviSharedFile::name () [inline]
Referenced by KviSharedFilesManager::addSharedFile(), dccModuleParseDccGet(), SharedFilesWindow::editClicked(), SharedFilesWindow::removeClicked(), SharedFileEditDialog::SharedFileEditDialog(), and SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem().
unsigned int KviSharedFile::nonWildcardCount () [inline]
Referenced by KviSharedFilesManager::doInsert().
const QString& KviSharedFile::userMask () [inline]
Referenced by avatar_kvs_cmd_notify(), SharedFileEditDialog::SharedFileEditDialog(), and SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem().
unsigned int KviSharedFile::wildcardCount () [inline]
Referenced by KviSharedFilesManager::doInsert().
Member Data Documentation
time_t KviSharedFile::m_expireTime [private]
Referenced by KviSharedFile().
QString KviSharedFile::m_szAbsFilePath [private]
Referenced by KviSharedFile().
QString KviSharedFile::m_szName [private]
Referenced by KviSharedFile().
QString KviSharedFile::m_szUserMask [private]
Referenced by KviSharedFile().
unsigned int KviSharedFile::m_uFileSize [private]
Referenced by KviSharedFile().
unsigned int KviSharedFile::m_uNonWildCount [private]
Referenced by KviSharedFile().
unsigned int KviSharedFile::m_uWildCount [private]
Referenced by KviSharedFile().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviSharedFile.h
src/kvilib/ext/KviSharedFile.cpp