KVIrc: OptionsWidget_windowListTreeBackground Class Reference
OptionsWidget_windowListTreeBackground Class Reference
#include <OptionsWidget_windowList.h>
Public Member Functions
virtual void commit ()
OptionsWidget_windowListTreeBackground (QWidget *parent)
~OptionsWidget_windowListTreeBackground ()
Private Attributes
QComboBox * m_pHorizontalAlign
QComboBox * m_pVerticalAlign
Constructor & Destructor Documentation
OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), g, KVI_OPTION_UINT, KviOption_colorTreeWindowListActiveBackground, KviOption_colorTreeWindowListBackground, KviOption_pixmapTreeWindowListBackground, KviOption_uintTreeWindowListPixmapAlign, KviOptionsWidget::layout(), m_pHorizontalAlign, and m_pVerticalAlign.
OptionsWidget_windowListTreeBackground::~OptionsWidget_windowListTreeBackground ()
Member Function Documentation
void OptionsWidget_windowListTreeBackground::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintTreeWindowListPixmapAlign, m_pHorizontalAlign, and m_pVerticalAlign.
Member Data Documentation
QComboBox* OptionsWidget_windowListTreeBackground::m_pHorizontalAlign [private]
Referenced by commit(), and OptionsWidget_windowListTreeBackground().
QComboBox* OptionsWidget_windowListTreeBackground::m_pVerticalAlign [private]
Referenced by commit(), and OptionsWidget_windowListTreeBackground().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_windowList.h
src/modules/options/OptionsWidget_windowList.cpp