KVIrc: ClassEditorWidget Class Reference
ClassEditorWidget Class Reference
The Class Editor module.
#include <ClassEditorWindow.h>
Public Member Functions
void build ()
Builds the class!
ClassEditorWidget (QWidget *pParent)
Constructs the class editor object.
void cutItem (ClassEditorTreeWidgetItem *pItem)
Removes the item from the tree.
void exportClasses (bool bSelectedOnly, bool bSingleFiles=false)
Exports class to a file.
void exportSelectionInSinglesFiles (KviPointerList< ClassEditorTreeWidgetItem > *pList)
Exports the current selection to single files.
ClassEditorTreeWidgetItem * findFunction (const QString &szFunctionName, ClassEditorTreeWidgetItem *pClass)
Searches a function.
void loadNotBuiltClasses ()
Loads non-built classes to a file.
virtual void loadProperties (KviConfigurationFile *pCfg)
Called to load the window properties.
void saveNotBuiltClasses ()
Saves non-built classes to a file.
virtual void saveProperties (KviConfigurationFile *pCfg)
Called to save the window properties.
~ClassEditorWidget ()
Destroys the class editor object.
Public Attributes
bool m_bSaving
QLabel * m_pClassNameLabel
QPushButton * m_pClassNameRenameButton
KviTalPopupMenu * m_pContextPopup
KviScriptEditor * m_pEditor
QLabel * m_pFunctionNameLabel
QPushButton * m_pFunctionNameRenameButton
ClassEditorTreeWidgetItem * m_pLastClickedItem
ClassEditorTreeWidgetItem * m_pLastEditedItem
QLabel * m_pReminderLabel
QSplitter * m_pSplitter
ClassEditorTreeWidget * m_pTreeWidget
QString m_szDir
Protected Slots
void currentItemChanged (QTreeWidgetItem *pItem, QTreeWidgetItem *)
void customContextMenuRequested (QPoint)
void exportAll ()
void exportSelected ()
void exportSelectedSepFiles ()
void newClass ()
ClassEditorTreeWidgetItem * newItem (QString &szName, ClassEditorTreeWidgetItem::Type eType)
void newMemberFunction ()
void newNamespace ()
void recursiveCollapseItems (ClassEditorTreeWidgetItem *pItem)
Called when we collapse an item recursively.
void removeSelectedItems ()
Called when we want to remove all selected items.
void renameFunction ()
void renameItem ()
void searchReplace (const QString &szSearch, bool bReplace=false, const QString &szReplace="n")
void slotCollapseItems ()
Called when we collapse an item.
void slotFind ()
void slotFindWord (const QString &)
void slotReplaceAll (const QString &szBefore, const QString &szAfter)
Called when we replace text everywhere.
Protected Member Functions
void activateItem (QTreeWidgetItem *pItem)
void appendAllClassItems (KviPointerList< ClassEditorTreeWidgetItem > *pList)
void appendAllClassItemsRecursive (KviPointerList< ClassEditorTreeWidgetItem > *l, QTreeWidgetItem *pStartFrom)
void appendSelectedClassItems (KviPointerList< ClassEditorTreeWidgetItem > *pList)
void appendSelectedClassItemsRecursive (KviPointerList< ClassEditorTreeWidgetItem > *pList, QTreeWidgetItem *pStartFrom)
bool askForClassName (QString &szClassName, QString &szInheritsClassName, bool bEdit)
bool askForFunction (QString &szFunctionName, QString &szReminder, bool *pbInternal, const QString &szClassName, bool bRenameMode)
bool askForNamespaceName (const QString &szAction, const QString &szText, const QString &szInitialText, QString &szNameBuffer)
QString buildFullClassName (ClassEditorTreeWidgetItem *pItem)
void buildFullItemPath (ClassEditorTreeWidgetItem *pItem, QString &szBuffer)
bool classExists (QString &szName)
Returns true if the class exists, false otherwise.
void createFullClass (KviKvsObjectClass *pClass, ClassEditorTreeWidgetItem *pItem, const QString &szClassName)
ClassEditorTreeWidgetItem * createFullItem (const QString &szFullName)
ClassEditorTreeWidgetItem * createFullItemRecursive (QTreeWidgetItem *pCurrent, QStringList &lNameSpaces, int &iLevel, bool bCreateNameSpace=0)
ClassEditorTreeWidgetItem * createFullNamespace (const QString &szFullName)
void exportClassBuffer (QString &szBuffer, ClassEditorTreeWidgetItem *pItem)
ClassEditorTreeWidgetItem * findItem (const QString &szName)
Searches an item.
ClassEditorTreeWidgetItem * findTopLevelItem (const QString &szName)
bool hasSelectedItems ()
void oneTimeSetup ()
void openParentItems (QTreeWidgetItem *pItem)
bool removeItem (ClassEditorTreeWidgetItem *pItem, KviPointerList< ClassEditorTreeWidgetItem > &lRemovedItems, bool *pbYesToAll)
void removeItemChildren (ClassEditorTreeWidgetItem *pItem, KviPointerList< ClassEditorTreeWidgetItem > &lRemovedItems)
void renameClass (ClassEditorTreeWidgetItem *pClass)
Renames a class.
void renameNamespace (ClassEditorTreeWidgetItem *pNamespace)
Renames a namespace.
void saveLastEditedItem ()
void searchInheritedClasses (const QString szClass, KviPointerList< ClassEditorTreeWidgetItem > &lInheritsedClasses)
void updateClassHierarchy (ClassEditorTreeWidgetItem *pClass)
Protected Attributes
KviPointerHashTable< QString,
ClassEditorTreeWidgetItem > * m_pClasses
Detailed Description
The Class Editor module.
Constructor & Destructor Documentation
ClassEditorWidget::ClassEditorWidget (QWidget * pParent)
Constructs the class editor object.
Parameters:
pParent The parent widget
Returns:
ClassEditorWidget
References __tr2qs_ctx(), connect(), KviScriptEditor::createInstance(), currentItemChanged(), KviQString::find(), m_pClasses, m_pClassNameLabel, m_pClassNameRenameButton, m_pContextPopup, m_pEditor, m_pFunctionNameLabel, m_pFunctionNameRenameButton, m_pLastClickedItem, m_pLastEditedItem, m_pReminderLabel, m_pSplitter, m_pTreeWidget, m_szDir, oneTimeSetup(), renameFunction(), renameItem(), KviPointerHashTable< Key, T >::setAutoDelete(), KviTalHBox::setMargin(), KviTalVBox::setMargin(), KviTalHBox::setSpacing(), KviTalVBox::setSpacing(), KviTalHBox::setStretchFactor(), slotFindWord(), and slotReplaceAll().
ClassEditorWidget::~ClassEditorWidget ()
Destroys the class editor object.
References KviPointerHashTable< Key, T >::clear(), and m_pClasses.
Member Function Documentation
void ClassEditorWidget::activateItem (QTreeWidgetItem * pItem) [protected]
References m_pTreeWidget, and openParentItems().
Referenced by loadProperties(), newClass(), newMemberFunction(), newNamespace(), renameClass(), renameFunction(), and renameNamespace().
void ClassEditorWidget::appendAllClassItems (KviPointerList< ClassEditorTreeWidgetItem > * pList) [protected]
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), and m_pClasses.
Referenced by exportClasses().
void ClassEditorWidget::appendAllClassItemsRecursive (KviPointerList< ClassEditorTreeWidgetItem > * l, QTreeWidgetItem * pStartFrom) [protected]
References KviPointerList< T >::append(), and i.
Referenced by renameNamespace().
void ClassEditorWidget::appendSelectedClassItems (KviPointerList< ClassEditorTreeWidgetItem > * pList) [protected]
References KviPointerList< T >::append(), appendSelectedClassItemsRecursive(), KviPointerList< T >::at(), i, and m_pTreeWidget.
Referenced by exportClasses().
void ClassEditorWidget::appendSelectedClassItemsRecursive (KviPointerList< ClassEditorTreeWidgetItem > * pList, QTreeWidgetItem * pStartFrom) [protected]
References KviPointerList< T >::append(), and i.
Referenced by appendSelectedClassItems().
bool ClassEditorWidget::askForClassName (QString & szClassName, QString & szInheritsClassName, bool bEdit) [protected]
References KviClassEditorDialog::className(), KviClassEditorDialog::inheritsClassName(), KviModule::lock(), m_pClasses, and KviModule::unlock().
Referenced by newClass(), and renameClass().
bool ClassEditorWidget::askForFunction (QString & szFunctionName, QString & szReminder, bool * pbInternal, const QString & szClassName, bool bRenameMode) [protected]
References KviClassEditorFunctionDialog::functionName(), KviClassEditorFunctionDialog::isInternalFunction(), KviModule::lock(), KviClassEditorFunctionDialog::reminder(), and KviModule::unlock().
Referenced by newMemberFunction(), and renameFunction().
bool ClassEditorWidget::askForNamespaceName (const QString & szAction, const QString & szText, const QString & szInitialText, QString & szNameBuffer) [protected]
References __tr2qs_ctx(), KviMessageBox::information(), KviModule::lock(), Normal, KviModule::unlock(), and KviMessageBox::warning().
Referenced by newNamespace(), and renameNamespace().
void ClassEditorWidget::build ()
Builds the class!
Returns:
void
References __tr2qs_ctx(), KviPointerList< T >::append(), KviPointerList< T >::at(), buildFullClassName(), ClassEditorTreeWidgetItem::classNotBuilt(), KviConfigurationFile::clear(), KviApplication::ConfigPlugins, KviPointerList< T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviKvsObjectController::deleteClass(), exportClassBuffer(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::findRef(), KviKvsObjectController::flushUserClasses(), g_pActiveWindow, g_pApp, KviApplication::getLocalKvircDirectory(), i, ClassEditorTreeWidgetItem::inheritsClass(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), m_pClasses, m_pEditor, KviKvsKernel::objectController(), KviIrcUrl::run(), saveLastEditedItem(), saveNotBuiltClasses(), searchInheritedClasses(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setClassNotBuilt(), KviScriptEditor::setModified(), KviConfigurationFile::sync(), szBuffer, u, and KviConfigurationFile::Write.
Referenced by ClassEditorWindow::buildClicked().
QString ClassEditorWidget::buildFullClassName (ClassEditorTreeWidgetItem * pItem) [protected]
References ClassEditorTreeWidgetItem::name().
Referenced by build(), currentItemChanged(), exportClassBuffer(), exportClasses(), exportSelectionInSinglesFiles(), newMemberFunction(), removeItem(), removeItemChildren(), renameClass(), renameFunction(), renameNamespace(), and saveProperties().
void ClassEditorWidget::buildFullItemPath (ClassEditorTreeWidgetItem * pItem, QString & szBuffer) [protected]
References ClassEditorTreeWidgetItem::name().
Referenced by newItem().
bool ClassEditorWidget::classExists (QString & szName) [protected]
Returns true if the class exists, false otherwise.
Parameters:
szName The name of the class
Returns:
bool
References KviPointerHashTable< Key, T >::find(), and m_pClasses.
Referenced by renameClass().
void ClassEditorWidget::createFullClass (KviKvsObjectClass * pClass, ClassEditorTreeWidgetItem * pItem, const QString & szClassName) [protected]
References findFunction(), KviKvsObjectFunctionHandler::flags(), KviKvsObjectClass::getFunctionCode(), KviKvsObjectClass::getHandlers(), i, KviPointerHashTable< Key, T >::insert(), KviKvsObjectFunctionHandler::Internal, KviKvsObjectFunctionHandler::isClone(), KviKvsObjectClass::isScriptHandler(), KviKvsObjectClass::lookupFunctionHandler(), m_pClasses, ClassEditorTreeWidgetItem::Method, KviKvsObjectClass::name(), KviKvsObjectClass::parentClass(), KviKvsObjectClass::reminder(), ClassEditorTreeWidgetItem::setBuffer(), ClassEditorTreeWidgetItem::setInheritsClass(), ClassEditorTreeWidgetItem::setInternalFunction(), and ClassEditorTreeWidgetItem::setReminder().
Referenced by oneTimeSetup().
ClassEditorTreeWidgetItem * ClassEditorWidget::createFullItem (const QString & szFullName) [protected]
References ClassEditorTreeWidgetItem::Class, KviQString::equalCI(), findTopLevelItem(), i, j, m_pTreeWidget, and ClassEditorTreeWidgetItem::Namespace.
Referenced by loadNotBuiltClasses(), newItem(), and oneTimeSetup().
ClassEditorTreeWidgetItem* ClassEditorWidget::createFullItemRecursive (QTreeWidgetItem * pCurrent, QStringList & lNameSpaces, int & iLevel, bool bCreateNameSpace = 0) [protected]
ClassEditorTreeWidgetItem * ClassEditorWidget::createFullNamespace (const QString & szFullName) [protected]
References KviQString::equalCI(), findTopLevelItem(), i, j, m_pTreeWidget, and ClassEditorTreeWidgetItem::Namespace.
Referenced by renameClass(), and renameNamespace().
void ClassEditorWidget::currentItemChanged (QTreeWidgetItem * pItem, QTreeWidgetItem *) [protected, slot]
References __tr2qs_ctx(), buildFullClassName(), KviPointerHashTable< Key, T >::find(), i, ClassEditorTreeWidgetItem::inheritsClass(), KviPointerHashTable< Key, T >::insert(), ClassEditorTreeWidgetItem::isClass(), ClassEditorTreeWidgetItem::isMethod(), ClassEditorTreeWidgetItem::isNamespace(), m_pClassNameLabel, m_pClassNameRenameButton, m_pEditor, m_pFunctionNameLabel, m_pFunctionNameRenameButton, m_pLastEditedItem, m_pReminderLabel, m_pTreeWidget, ClassEditorTreeWidgetItem::name(), ClassEditorTreeWidgetItem::reminder(), saveLastEditedItem(), KviPointerHashTable< Key, T >::setAutoDelete(), KviScriptEditor::setCursorPosition(), KviScriptEditor::setReadOnly(), KviScriptEditor::setText(), KviScriptEditor::setUnHighlightedText(), and szBuffer.
Referenced by ClassEditorWidget(), oneTimeSetup(), and renameFunction().
void ClassEditorWidget::customContextMenuRequested (QPoint pnt) [protected, slot]
References __tr2qs_ctx(), KviIconManager::Class, KviTalPopupMenu::clear(), exportAll(), exportSelected(), exportSelectedSepFiles(), KviIconManager::Folder, KviIconManager::Function, g_pIconManager, KviIconManager::getSmallIcon(), hasSelectedItems(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), ClassEditorTreeWidgetItem::isClass(), ClassEditorTreeWidgetItem::isMethod(), ClassEditorTreeWidgetItem::isNamespace(), m_pContextPopup, m_pLastClickedItem, m_pTreeWidget, KviIconManager::NameSpace, newClass(), newMemberFunction(), newNamespace(), KviIconManager::Quit, removeSelectedItems(), KviIconManager::Search, KviTalPopupMenu::setItemEnabled(), slotCollapseItems(), and slotFind().
Referenced by oneTimeSetup().
void ClassEditorWidget::cutItem (ClassEditorTreeWidgetItem * pItem)
Removes the item from the tree.
Parameters:
pItem The item to remove
Returns:
void
References m_pTreeWidget.
Referenced by renameClass(), and renameNamespace().
void ClassEditorWidget::exportAll () [protected, slot]
References exportClasses().
Referenced by customContextMenuRequested().
void ClassEditorWidget::exportClassBuffer (QString & szBuffer, ClassEditorTreeWidgetItem * pItem) [protected]
References KviCommandFormatter::blockFromBuffer(), ClassEditorTreeWidgetItem::buffer(), buildFullClassName(), i, ClassEditorTreeWidgetItem::inheritsClass(), ClassEditorTreeWidgetItem::isInternalFunction(), ClassEditorTreeWidgetItem::isMethod(), ClassEditorTreeWidgetItem::name(), and ClassEditorTreeWidgetItem::reminder().
Referenced by build(), exportClasses(), and exportSelectionInSinglesFiles().
void ClassEditorWidget::exportClasses (bool bSelectedOnly, bool bSingleFiles = false)
Exports class to a file.
Parameters:
bSelectedOnly Whether to export only selected files
bSingleFiles Whether to export to single files
Returns:
void
References __tr2qs_ctx(), appendAllClassItems(), appendSelectedClassItems(), KviFileDialog::askForSaveFileName(), buildFullClassName(), exportClassBuffer(), exportSelectionInSinglesFiles(), KviPointerList< T >::first(), KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, KviModule::lock(), m_szDir, KviPointerList< T >::next(), saveLastEditedItem(), KviPointerList< T >::setAutoDelete(), KviModule::unlock(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by exportAll(), exportSelected(), and exportSelectedSepFiles().
void ClassEditorWidget::exportSelected () [protected, slot]
References exportClasses().
Referenced by customContextMenuRequested().
void ClassEditorWidget::exportSelectedSepFiles () [protected, slot]
References exportClasses().
Referenced by customContextMenuRequested().
void ClassEditorWidget::exportSelectionInSinglesFiles (KviPointerList< ClassEditorTreeWidgetItem > * pList)
Exports the current selection to single files.
Parameters:
pList The list of file to export
Returns:
void
References __tr2qs_ctx(), KviFileDialog::askForDirectoryName(), buildFullClassName(), exportClassBuffer(), KviFileUtils::fileExists(), KviPointerList< T >::first(), KVI_PATH_SEPARATOR, KviModule::lock(), m_szDir, KviPointerList< T >::next(), KviModule::unlock(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by exportClasses().
ClassEditorTreeWidgetItem * ClassEditorWidget::findFunction (const QString & szFunctionName, ClassEditorTreeWidgetItem * pClass)
Searches a function.
Parameters:
szFunctionName The name of the function
pClass The class in which the function is
Returns:
ClassEditorTreeWidgetItem *
References KviQString::equalCI(), i, and KviOsInfo::name().
Referenced by createFullClass(), and loadNotBuiltClasses().
ClassEditorTreeWidgetItem * ClassEditorWidget::findItem (const QString & szName) [protected]
Searches an item.
Parameters:
szName The name of the item to find
Returns:
ClassEditorTreeWidgetItem *
References KviQString::equalCI(), findTopLevelItem(), i, and j.
Referenced by loadProperties(), newItem(), and renameNamespace().
ClassEditorTreeWidgetItem * ClassEditorWidget::findTopLevelItem (const QString & szName) [protected]
References KviQString::equalCI(), i, and m_pTreeWidget.
Referenced by createFullItem(), createFullNamespace(), and findItem().
bool ClassEditorWidget::hasSelectedItems () [protected]
References m_pTreeWidget.
Referenced by customContextMenuRequested().
void ClassEditorWidget::loadNotBuiltClasses ()
Loads non-built classes to a file.
Returns:
void
References KviPointerList< T >::append(), KviApplication::ConfigPlugins, createFullItem(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviQString::equalCI(), KviPointerHashTable< Key, T >::find(), findFunction(), KviPointerList< T >::first(), g_pApp, KviApplication::getLocalKvircDirectory(), KviPointerHashTable< Key, T >::insert(), l, m_pClasses, ClassEditorTreeWidgetItem::Method, KviPointerList< T >::next(), KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setBuffer(), ClassEditorTreeWidgetItem::setClassNotBuilt(), KviConfigurationFile::setGroup(), ClassEditorTreeWidgetItem::setInheritsClass(), ClassEditorTreeWidgetItem::setReminder(), and szBuffer.
Referenced by oneTimeSetup().
void ClassEditorWidget::loadProperties (KviConfigurationFile * pCfg) [virtual]
Called to load the window properties.
Parameters:
pCfg The configuration file
Returns:
void
References activateItem(), findItem(), m_pSplitter, KviConfigurationFile::readEntry(), and KviConfigurationFile::readIntListEntry().
Referenced by ClassEditorWindow::loadProperties().
void ClassEditorWidget::newClass () [protected, slot]
References activateItem(), askForClassName(), ClassEditorTreeWidgetItem::Class, KviQString::escapeKvs(), KviQString::EscapeSpace, g_pActiveWindow, KviPointerHashTable< Key, T >::insert(), m_pClasses, newItem(), KviIrcUrl::run(), and ClassEditorTreeWidgetItem::setInheritsClass().
Referenced by customContextMenuRequested().
ClassEditorTreeWidgetItem * ClassEditorWidget::newItem (QString & szName, ClassEditorTreeWidgetItem::Type eType) [protected, slot]
References buildFullItemPath(), createFullItem(), findItem(), m_pLastClickedItem, and ClassEditorTreeWidgetItem::setType().
Referenced by newClass(), newMemberFunction(), and newNamespace().
void ClassEditorWidget::newMemberFunction () [protected, slot]
References activateItem(), askForFunction(), buildFullClassName(), ClassEditorTreeWidgetItem::isMethod(), m_pLastClickedItem, ClassEditorTreeWidgetItem::Method, newItem(), ClassEditorTreeWidgetItem::setInternalFunction(), and ClassEditorTreeWidgetItem::setReminder().
Referenced by customContextMenuRequested().
void ClassEditorWidget::newNamespace () [protected, slot]
References __tr2qs_ctx(), activateItem(), askForNamespaceName(), ClassEditorTreeWidgetItem::Namespace, and newItem().
Referenced by customContextMenuRequested().
void ClassEditorWidget::oneTimeSetup () [protected]
References KviApplication::Classes, connect(), createFullClass(), createFullItem(), KviPointerHashTableIterator< Key, T >::current(), currentItemChanged(), KviPointerHashTableIterator< Key, T >::currentKey(), customContextMenuRequested(), d, g_pApp, g_pModuleManager, KviApplication::getLocalKvircDirectory(), KviModuleManager::getModule(), i, KviPointerHashTable< Key, T >::insert(), KviKvsKernel::instance(), KviKvsObjectClass::isBuiltin(), KVI_FILEEXTENSION_SCRIPT, loadNotBuiltClasses(), KviKvsObjectController::lookupClass(), m_pClasses, m_pTreeWidget, and KviKvsKernel::objectController().
Referenced by ClassEditorWidget().
void ClassEditorWidget::openParentItems (QTreeWidgetItem * pItem) [protected]
Referenced by activateItem(), and searchReplace().
void ClassEditorWidget::recursiveCollapseItems (ClassEditorTreeWidgetItem * pItem) [protected, slot]
Called when we collapse an item recursively.
Parameters:
pItem The starting item to collapse
Returns:
void
References i.
Referenced by slotCollapseItems().
bool ClassEditorWidget::removeItem (ClassEditorTreeWidgetItem * pItem, KviPointerList< ClassEditorTreeWidgetItem > & lRemovedItems, bool * pbYesToAll) [protected]
References __tr2qs_ctx(), KviPointerList< T >::append(), buildFullClassName(), KviApplication::Classes, d, KviKvsObjectController::deleteClass(), g_pApp, KviApplication::getLocalKvircDirectory(), KviKvsKernel::instance(), ClassEditorTreeWidgetItem::isClass(), ClassEditorTreeWidgetItem::isMethod(), ClassEditorTreeWidgetItem::isNamespace(), KVI_FILEEXTENSION_SCRIPT, KviModule::lock(), KviKvsObjectController::lookupClass(), m_pClasses, m_pLastClickedItem, m_pLastEditedItem, ClassEditorTreeWidgetItem::name(), KviKvsKernel::objectController(), removeItemChildren(), KviPointerHashTable< Key, T >::removeRef(), saveLastEditedItem(), KviModule::unlock(), and updateClassHierarchy().
Referenced by removeSelectedItems().
void ClassEditorWidget::removeItemChildren (ClassEditorTreeWidgetItem * pItem, KviPointerList< ClassEditorTreeWidgetItem > & lRemovedItems) [protected]
References KviPointerList< T >::append(), KviPointerList< T >::at(), buildFullClassName(), KviPointerList< T >::count(), KviKvsObjectController::deleteClass(), KviKvsKernel::instance(), ClassEditorTreeWidgetItem::isClass(), KviKvsObjectController::lookupClass(), m_pClasses, KviKvsKernel::objectController(), KviPointerHashTable< Key, T >::removeRef(), searchInheritedClasses(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setClassNotBuilt(), ClassEditorTreeWidgetItem::setInheritsClass(), and u.
Referenced by removeItem().
void ClassEditorWidget::removeSelectedItems () [protected, slot]
Called when we want to remove all selected items.
Returns:
void
References KviPointerList< T >::findRef(), i, m_pTreeWidget, removeItem(), and KviPointerList< T >::setAutoDelete().
Referenced by customContextMenuRequested().
void ClassEditorWidget::renameClass (ClassEditorTreeWidgetItem * pClass) [protected]
Renames a class.
Parameters:
pClass The class to rename
Returns:
void
References __tr2qs_ctx(), activateItem(), askForClassName(), KviPointerList< T >::at(), buildFullClassName(), classExists(), KviPointerList< T >::count(), createFullNamespace(), cutItem(), KviKvsObjectController::deleteClass(), KviQString::equalCS(), i, KviMessageBox::information(), ClassEditorTreeWidgetItem::inheritsClass(), KviPointerHashTable< Key, T >::insert(), KviKvsKernel::instance(), KviModule::lock(), KviKvsObjectController::lookupClass(), m_pClasses, m_pTreeWidget, KviKvsKernel::objectController(), KviPointerHashTable< Key, T >::removeRef(), searchInheritedClasses(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setClassNotBuilt(), ClassEditorTreeWidgetItem::setInheritsClass(), ClassEditorTreeWidgetItem::setName(), and KviModule::unlock().
Referenced by renameItem().
void ClassEditorWidget::renameFunction () [protected, slot]
References __tr2qs_ctx(), activateItem(), askForFunction(), KviPointerList< T >::at(), buildFullClassName(), KviApplication::Classes, KviPointerList< T >::count(), currentItemChanged(), KviQString::equalCS(), g_pApp, KviApplication::getLocalKvircDirectory(), i, KviMessageBox::information(), KviKvsKernel::instance(), ClassEditorTreeWidgetItem::isInternalFunction(), KviModule::lock(), KviKvsObjectController::lookupClass(), KviKvsObjectClass::lookupFunctionHandler(), m_pLastEditedItem, ClassEditorTreeWidgetItem::name(), KviKvsKernel::objectController(), ClassEditorTreeWidgetItem::reminder(), KviKvsObjectClass::save(), searchInheritedClasses(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setClassNotBuilt(), ClassEditorTreeWidgetItem::setInternalFunction(), ClassEditorTreeWidgetItem::setName(), KviKvsObjectClass::setReminder(), ClassEditorTreeWidgetItem::setReminder(), and KviModule::unlock().
Referenced by ClassEditorWidget().
void ClassEditorWidget::renameItem () [protected, slot]
References ClassEditorTreeWidgetItem::isClass(), ClassEditorTreeWidgetItem::isNamespace(), m_pLastEditedItem, renameClass(), and renameNamespace().
Referenced by ClassEditorWidget().
void ClassEditorWidget::renameNamespace (ClassEditorTreeWidgetItem * pNamespace) [protected]
Renames a namespace.
Parameters:
pNamespace The namespace to rename
Returns:
void
References __tr2qs_ctx(), activateItem(), appendAllClassItemsRecursive(), askForNamespaceName(), KviPointerList< T >::at(), buildFullClassName(), KviPointerList< T >::count(), createFullNamespace(), cutItem(), KviKvsObjectController::deleteClass(), KviQString::equalCI(), findItem(), KviPointerHashTable< Key, T >::findRef(), KviMessageBox::information(), KviPointerHashTable< Key, T >::insert(), KviKvsKernel::instance(), ClassEditorTreeWidgetItem::isClass(), KviPointerHashTableEntry< Key, T >::key(), KviModule::lock(), KviKvsObjectController::lookupClass(), m_pClasses, m_pLastEditedItem, m_pTreeWidget, KviKvsKernel::objectController(), KviPointerHashTable< Key, T >::removeRef(), searchInheritedClasses(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setClassNotBuilt(), ClassEditorTreeWidgetItem::setInheritsClass(), ClassEditorTreeWidgetItem::setName(), u, KviModule::unlock(), and v.
Referenced by renameItem().
void ClassEditorWidget::saveLastEditedItem () [protected]
References KviScriptEditor::getCursor(), KviScriptEditor::getText(), ClassEditorTreeWidgetItem::isClass(), KviScriptEditor::isModified(), ClassEditorTreeWidgetItem::isNamespace(), m_pEditor, and m_pLastEditedItem.
Referenced by build(), currentItemChanged(), exportClasses(), removeItem(), and saveNotBuiltClasses().
void ClassEditorWidget::saveNotBuiltClasses ()
Saves non-built classes to a file.
Returns:
void
References ClassEditorTreeWidgetItem::classNotBuilt(), KviConfigurationFile::clear(), KviApplication::ConfigPlugins, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviKvsObjectController::deleteClass(), g_pApp, KviApplication::getLocalKvircDirectory(), i, ClassEditorTreeWidgetItem::inheritsClass(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), m_pClasses, KviOsInfo::name(), KviKvsKernel::objectController(), saveLastEditedItem(), KviConfigurationFile::setGroup(), KviConfigurationFile::sync(), szBuffer, KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by build(), and ClassEditorWindow::saveClicked().
void ClassEditorWidget::saveProperties (KviConfigurationFile * pCfg) [virtual]
Called to save the window properties.
Parameters:
pCfg The configuration file
Returns:
void
References buildFullClassName(), m_pLastEditedItem, m_pSplitter, and KviConfigurationFile::writeEntry().
Referenced by ClassEditorWindow::saveProperties().
void ClassEditorWidget::searchInheritedClasses (const QString szClass, KviPointerList< ClassEditorTreeWidgetItem > & lInheritsedClasses) [protected]
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), ClassEditorTreeWidgetItem::inheritsClass(), and m_pClasses.
Referenced by build(), removeItemChildren(), renameClass(), renameFunction(), renameNamespace(), and updateClassHierarchy().
void ClassEditorWidget::searchReplace (const QString & szSearch, bool bReplace = false, const QString & szReplace = "n") [protected, slot]
References KviPointerHashTableIterator< Key, T >::current(), j, m_pClasses, openParentItems(), and ClassEditorTreeWidgetItem::setClassNotBuilt().
Referenced by slotFind(), and slotReplaceAll().
void ClassEditorWidget::slotCollapseItems () [protected, slot]
Called when we collapse an item.
Parameters:
pItem The item to collapse
Returns:
void
References i, m_pTreeWidget, and recursiveCollapseItems().
Referenced by customContextMenuRequested().
void ClassEditorWidget::slotFind () [protected, slot]
References __tr2qs_ctx(), KviModule::lock(), m_pEditor, Normal, searchReplace(), KviScriptEditor::setFindText(), and KviModule::unlock().
Referenced by customContextMenuRequested().
void ClassEditorWidget::slotFindWord (const QString & szSearch) [protected, slot]
References m_pEditor, and KviScriptEditor::setFindText().
Referenced by ClassEditorWidget().
void ClassEditorWidget::slotReplaceAll (const QString & szBefore, const QString & szAfter) [protected, slot]
Called when we replace text everywhere.
Parameters:
szBefore The text before the replace
szAfter The text after the replace
Returns:
void
References m_pEditor, searchReplace(), and KviScriptEditor::setFindText().
Referenced by ClassEditorWidget().
void ClassEditorWidget::updateClassHierarchy (ClassEditorTreeWidgetItem * pClass) [protected]
References KviPointerList< T >::at(), KviPointerList< T >::count(), ClassEditorTreeWidgetItem::name(), searchInheritedClasses(), KviPointerList< T >::setAutoDelete(), ClassEditorTreeWidgetItem::setClassNotBuilt(), ClassEditorTreeWidgetItem::setInheritsClass(), and u.
Referenced by removeItem().
Member Data Documentation
bool ClassEditorWidget::m_bSaving
KviPointerHashTable<QString,ClassEditorTreeWidgetItem>* ClassEditorWidget::m_pClasses [protected]
Referenced by appendAllClassItems(), askForClassName(), build(), ClassEditorWidget(), classExists(), createFullClass(), loadNotBuiltClasses(), newClass(), oneTimeSetup(), removeItem(), removeItemChildren(), renameClass(), renameNamespace(), saveNotBuiltClasses(), searchInheritedClasses(), searchReplace(), and ~ClassEditorWidget().
QLabel* ClassEditorWidget::m_pClassNameLabel
Referenced by ClassEditorWidget(), and currentItemChanged().
QPushButton* ClassEditorWidget::m_pClassNameRenameButton
Referenced by ClassEditorWidget(), and currentItemChanged().
KviTalPopupMenu* ClassEditorWidget::m_pContextPopup
Referenced by ClassEditorWidget(), and customContextMenuRequested().
KviScriptEditor* ClassEditorWidget::m_pEditor
Referenced by build(), ClassEditorWidget(), currentItemChanged(), saveLastEditedItem(), slotFind(), slotFindWord(), and slotReplaceAll().
QLabel* ClassEditorWidget::m_pFunctionNameLabel
Referenced by ClassEditorWidget(), and currentItemChanged().
QPushButton* ClassEditorWidget::m_pFunctionNameRenameButton
Referenced by ClassEditorWidget(), and currentItemChanged().
ClassEditorTreeWidgetItem* ClassEditorWidget::m_pLastClickedItem
Referenced by ClassEditorWidget(), customContextMenuRequested(), newItem(), newMemberFunction(), and removeItem().
ClassEditorTreeWidgetItem* ClassEditorWidget::m_pLastEditedItem
Referenced by ClassEditorWidget(), currentItemChanged(), removeItem(), renameFunction(), renameItem(), renameNamespace(), saveLastEditedItem(), and saveProperties().
QLabel* ClassEditorWidget::m_pReminderLabel
Referenced by ClassEditorWidget(), and currentItemChanged().
QSplitter* ClassEditorWidget::m_pSplitter
Referenced by ClassEditorWidget(), loadProperties(), and saveProperties().
ClassEditorTreeWidget* ClassEditorWidget::m_pTreeWidget
Referenced by activateItem(), appendSelectedClassItems(), ClassEditorWidget(), createFullItem(), createFullNamespace(), currentItemChanged(), customContextMenuRequested(), cutItem(), findTopLevelItem(), hasSelectedItems(), oneTimeSetup(), removeSelectedItems(), renameClass(), renameNamespace(), and slotCollapseItems().
QString ClassEditorWidget::m_szDir
Referenced by ClassEditorWidget(), exportClasses(), and exportSelectionInSinglesFiles().
The documentation for this class was generated from the following files:
src/modules/classeditor/ClassEditorWindow.h
src/modules/classeditor/ClassEditorWindow.cpp