KVIrc: KviIrcViewToolWidget Class Reference
KviIrcViewToolWidget Class Reference
#include <KviIrcView_tools.h>
Public Member Functions
void forceRepaint ()
bool messageEnabled (int msg_type)
void setFindResult (const QString &text)
Protected Slots
void filterEnableAll ()
void filterEnableNone ()
void filterLoad ()
void filterSave ()
void findNext ()
void findPrev ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
virtual void hideEvent (QHideEvent *)
KviIrcViewToolWidget (KviIrcView *par)
virtual void mouseMoveEvent (QMouseEvent *)
virtual void mousePressEvent (QMouseEvent *)
~KviIrcViewToolWidget ()
Protected Attributes
QCheckBox * m_pCaseSensitive
QCheckBox * m_pExtendedRegExp
KviIrcMessageCheckListItem ** m_pFilterItems
QTreeWidget * m_pFilterView
QLabel * m_pFindResult
KviIrcView * m_pIrcView
QCheckBox * m_pRegExp
QPoint m_pressPoint
QLineEdit * m_pStringToFind
Friends
class KviIrcView
Constructor & Destructor Documentation
KviIrcViewToolWidget::KviIrcViewToolWidget (KviIrcView * par) [protected]
COMPILE_ON_MAC
References __tr2qs, KviMemory::allocate(), KviIconManager::Close, connect(), filterEnableAll(), filterEnableNone(), filterLoad(), filterSave(), findNext(), findPrev(), g, g_pIconManager, KviIconManager::getSmallIcon(), i, KVI_NUM_MSGTYPE_OPTIONS, KVI_SHORTCUTS_WIN_SEARCH, l, m_pCaseSensitive, m_pExtendedRegExp, m_pFilterItems, m_pFilterView, m_pFindResult, m_pIrcView, m_pRegExp, m_pStringToFind, p, and w.
KviIrcViewToolWidget::~KviIrcViewToolWidget () [protected]
References KviWindow::input(), m_pFilterView, m_pIrcView, KviIrcView::parentKviWindow(), and KviInput::setFocus().
Member Function Documentation
void KviIrcViewToolWidget::closeEvent (QCloseEvent * e) [protected, virtual]
References m_pIrcView, and KviIrcView::toggleToolWidget().
void KviIrcViewToolWidget::filterEnableAll () [protected, slot]
References i, KVI_NUM_MSGTYPE_OPTIONS, m_pFilterItems, and KviIrcMessageCheckListItem::setOn().
Referenced by KviIrcViewToolWidget().
void KviIrcViewToolWidget::filterEnableNone () [protected, slot]
References i, KVI_NUM_MSGTYPE_OPTIONS, m_pFilterItems, and KviIrcMessageCheckListItem::setOn().
Referenced by KviIrcViewToolWidget().
void KviIrcViewToolWidget::filterLoad () [protected, slot]
References __tr2qs, KviFileDialog::askForOpenFileName(), f, KviApplication::Filters, forceRepaint(), g_pApp, KviApplication::getLocalKvircDirectory(), i, KVI_NUM_MSGTYPE_OPTIONS, m_pFilterItems, KviMemory::set(), KviIrcMessageCheckListItem::setOn(), and KviMessageBox::warning().
Referenced by KviIrcViewToolWidget().
void KviIrcViewToolWidget::filterSave () [protected, slot]
References __tr2qs, KviFileDialog::askForSaveFileName(), f, KviApplication::Filters, g_pApp, KviApplication::getLocalKvircDirectory(), i, KVI_NUM_MSGTYPE_OPTIONS, messageEnabled(), and KviMessageBox::warning().
Referenced by KviIrcViewToolWidget().
void KviIrcViewToolWidget::findNext () [protected, slot]
References KviIrcView::findNext(), m_pCaseSensitive, m_pExtendedRegExp, m_pIrcView, m_pRegExp, and m_pStringToFind.
Referenced by KviIrcViewToolWidget().
void KviIrcViewToolWidget::findPrev () [protected, slot]
References KviIrcView::findPrev(), m_pCaseSensitive, m_pExtendedRegExp, m_pIrcView, m_pRegExp, and m_pStringToFind.
Referenced by KviIrcViewToolWidget().
void KviIrcViewToolWidget::forceRepaint ()
References m_pIrcView, and KviIrcView::paintEvent().
Referenced by filterLoad().
void KviIrcViewToolWidget::hideEvent (QHideEvent *) [protected, virtual]
References m_pIrcView, and KviIrcView::toggleToolWidget().
bool KviIrcViewToolWidget::messageEnabled (int msg_type) [inline]
References KviIrcMessageCheckListItem::isOn(), and m_pFilterItems.
Referenced by filterSave(), KviIrcView::findNext(), KviIrcView::findPrev(), and KviIrcView::paintEvent().
void KviIrcViewToolWidget::mouseMoveEvent (QMouseEvent *) [protected, virtual]
References m_pIrcView, m_pressPoint, KviIrcView::m_pScrollBar, KviMemory::move(), and p.
void KviIrcViewToolWidget::mousePressEvent (QMouseEvent * e) [protected, virtual]
References m_pressPoint.
void KviIrcViewToolWidget::setFindResult (const QString & text)
References m_pFindResult.
Referenced by KviIrcView::findNext(), and KviIrcView::findPrev().
Friends And Related Function Documentation
friend class KviIrcView [friend]
Member Data Documentation
QCheckBox* KviIrcViewToolWidget::m_pCaseSensitive [protected]
Referenced by findNext(), findPrev(), and KviIrcViewToolWidget().
QCheckBox* KviIrcViewToolWidget::m_pExtendedRegExp [protected]
Referenced by findNext(), findPrev(), and KviIrcViewToolWidget().
KviIrcMessageCheckListItem** KviIrcViewToolWidget::m_pFilterItems [protected]
Referenced by filterEnableAll(), filterEnableNone(), filterLoad(), KviIrcViewToolWidget(), and messageEnabled().
QTreeWidget* KviIrcViewToolWidget::m_pFilterView [protected]
Referenced by KviIrcViewToolWidget(), and ~KviIrcViewToolWidget().
QLabel* KviIrcViewToolWidget::m_pFindResult [protected]
Referenced by KviIrcViewToolWidget(), and setFindResult().
KviIrcView* KviIrcViewToolWidget::m_pIrcView [protected]
Referenced by closeEvent(), findNext(), findPrev(), forceRepaint(), hideEvent(), KviIrcViewToolWidget(), mouseMoveEvent(), and ~KviIrcViewToolWidget().
QCheckBox* KviIrcViewToolWidget::m_pRegExp [protected]
Referenced by findNext(), findPrev(), and KviIrcViewToolWidget().
QPoint KviIrcViewToolWidget::m_pressPoint [protected]
Referenced by mouseMoveEvent(), and mousePressEvent().
QLineEdit* KviIrcViewToolWidget::m_pStringToFind [protected]
Referenced by findNext(), findPrev(), and KviIrcViewToolWidget().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviIrcView_tools.h
src/kvirc/ui/KviIrcView_tools.cpp