KVIrc: OptionsWidget_antispam Class Reference
OptionsWidget_antispam Class Reference
#include <OptionsWidget_antiSpam.h>
Public Member Functions
OptionsWidget_antispam (QWidget *parent)
~OptionsWidget_antispam ()
Protected Slots
void reenableStuff (bool)
Protected Attributes
KviBoolSelector * m_b1
KviBoolSelector * m_b2
KviBoolSelector * m_b3
KviStringListSelector * m_sl
Constructor & Destructor Documentation
OptionsWidget_antispam::OptionsWidget_antispam (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addStringListSelector(), connect(), KviOptionsWidget::createLayout(), g, KviOption_boolSilentAntiSpam, KviOption_boolUseAntiSpamOnNotice, KviOption_boolUseAntiSpamOnPrivmsg, KviOption_stringlistSpamWords, KviOptionsWidget::layout(), m_b1, m_b2, m_b3, m_sl, and reenableStuff().
OptionsWidget_antispam::~OptionsWidget_antispam ()
Member Function Documentation
void OptionsWidget_antispam::reenableStuff (bool) [protected, slot]
References m_b1, m_b2, m_b3, m_sl, KviStringListSelector::setEnabled(), and KviBoolSelector::setEnabled().
Referenced by OptionsWidget_antispam().
Member Data Documentation
KviBoolSelector* OptionsWidget_antispam::m_b1 [protected]
Referenced by OptionsWidget_antispam(), and reenableStuff().
KviBoolSelector* OptionsWidget_antispam::m_b2 [protected]
Referenced by OptionsWidget_antispam(), and reenableStuff().
KviBoolSelector* OptionsWidget_antispam::m_b3 [protected]
Referenced by OptionsWidget_antispam(), and reenableStuff().
KviStringListSelector* OptionsWidget_antispam::m_sl [protected]
Referenced by OptionsWidget_antispam(), and reenableStuff().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_antiSpam.h
src/modules/options/OptionsWidget_antiSpam.cpp