KVIrc: KviNickServRuleSet Class Reference
KviNickServRuleSet Class Reference
#include <KviNickServRuleSet.h>
Public Member Functions
void addRule (KviNickServRule *r)
void clear ()
void copyFrom (const KviNickServRuleSet &src)
bool isEmpty ()
bool isEnabled ()
KviNickServRuleSet ()
KviNickServRuleSet (const KviNickServRuleSet &s)
void load (const QString &szConfigFile)
KviNickServRule * matchRule (const QString &szNick, const KviIrcMask *nickServ, const QString &szMsg, const QString &szServer=QString::null)
KviPointerList< KviNickServRule > * rules ()
void save (const QString &szConfigFile)
void save (KviConfigurationFile *cfg, const QString &prefix)
void setEnabled (bool bEnabled)
~KviNickServRuleSet ()
Static Public Member Functions
static KviNickServRuleSet * createInstance ()
static KviNickServRuleSet * load (KviConfigurationFile *cfg, const QString &prefix)
Protected Member Functions
bool loadPrivate (KviConfigurationFile *cfg, const QString &prefix, unsigned int nEntries)
Protected Attributes
bool m_bEnabled
KviPointerList< KviNickServRule > * m_pRules
Constructor & Destructor Documentation
KviNickServRuleSet::KviNickServRuleSet ()
References m_bEnabled, and m_pRules.
Referenced by createInstance(), and load().
KviNickServRuleSet::KviNickServRuleSet (const KviNickServRuleSet & s)
References copyFrom(), and m_pRules.
KviNickServRuleSet::~KviNickServRuleSet ()
References m_pRules.
Member Function Documentation
void KviNickServRuleSet::addRule (KviNickServRule * r)
References KviPointerList< T >::append(), m_pRules, and KviPointerList< T >::setAutoDelete().
Referenced by OptionsWidget_nickServ::commit(), and IrcNetworkDetailsWidget::fillData().
void KviNickServRuleSet::clear ()
References m_bEnabled, and m_pRules.
Referenced by OptionsWidget_nickServ::commit(), and load().
void KviNickServRuleSet::copyFrom (const KviNickServRuleSet & src)
References KviPointerList< T >::append(), c, KviPointerList< T >::clear(), KviNickServRule::copyFrom(), KviPointerList< T >::first(), KviPointerList< T >::isEmpty(), m_bEnabled, m_pRules, KviPointerList< T >::next(), r, and KviPointerList< T >::setAutoDelete().
Referenced by KviNickServRuleSet().
KviNickServRuleSet * KviNickServRuleSet::createInstance () static
References KviNickServRuleSet().
Referenced by IrcNetworkDetailsWidget::fillData().
bool KviNickServRuleSet::isEmpty () inline
Referenced by IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), OptionsWidget_nickServ::OptionsWidget_nickServ(), and KviIrcServerParser::parseLiteralNotice().
bool KviNickServRuleSet::isEnabled () inline
Referenced by IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), OptionsWidget_nickServ::OptionsWidget_nickServ(), and KviIrcServerParser::parseLiteralNotice().
void KviNickServRuleSet::load (const QString & szConfigFile)
References clear(), loadPrivate(), KviConfigurationFile::Read, and KviConfigurationFile::readUIntEntry().
Referenced by KviIrcServerDataBase::load(), and KviApplication::setup().
KviNickServRuleSet * KviNickServRuleSet::load (KviConfigurationFile * cfg, const QString & prefix) static
References KviNickServRuleSet(), loadPrivate(), and KviConfigurationFile::readUIntEntry().
bool KviNickServRuleSet::loadPrivate (KviConfigurationFile * cfg, const QString & prefix, unsigned int nEntries) protected
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerList< T >::isEmpty(), KviNickServRule::load(), m_bEnabled, m_pRules, KviConfigurationFile::readBoolEntry(), KviPointerList< T >::setAutoDelete(), and u.
Referenced by load().
KviNickServRule * KviNickServRuleSet::matchRule (const QString & szNick, const KviIrcMask * nickServ, const QString & szMsg, const QString & szServer = QString::null)
References KviPointerList< T >::first(), m_pRules, KviIrcMask::matchedBy(), KviQString::matchString(), KviPointerList< T >::next(), and r.
Referenced by KviIrcServerParser::parseLiteralNotice().
KviPointerList<KviNickServRule>* KviNickServRuleSet::rules () inline
Referenced by IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), and OptionsWidget_nickServ::OptionsWidget_nickServ().
void KviNickServRuleSet::save (const QString & szConfigFile)
References KviConfigurationFile::clear(), and KviConfigurationFile::Write.
Referenced by KviApplication::saveNickServ().
void KviNickServRuleSet::save (KviConfigurationFile * cfg, const QString & prefix)
References KviPointerList< T >::count(), KviPointerList< T >::first(), i, KviPointerList< T >::isEmpty(), m_bEnabled, m_pRules, KviPointerList< T >::next(), and KviConfigurationFile::writeEntry().
void KviNickServRuleSet::setEnabled (bool bEnabled) inline
Referenced by OptionsWidget_nickServ::commit(), and IrcNetworkDetailsWidget::fillData().
Member Data Documentation
bool KviNickServRuleSet::m_bEnabled protected
Referenced by clear(), copyFrom(), KviNickServRuleSet(), loadPrivate(), and save().
KviPointerList<KviNickServRule>* KviNickServRuleSet::m_pRules protected
Referenced by addRule(), clear(), copyFrom(), KviNickServRuleSet(), loadPrivate(), matchRule(), save(), and ~KviNickServRuleSet().
The documentation for this class was generated from the following files:
src/kvilib/irc/KviNickServRuleSet.h
src/kvilib/irc/KviNickServRuleSet.cpp