KVIrc: KviWindowListButton Class Reference
KviWindowListButton Class Reference
#include <KviWindowListBase.h>
Public Member Functions
virtual bool active ()
virtual void captionChanged ()
virtual void highlight (int iLevel=1)
KviWindowListButton (QWidget *par, KviWindow *wnd, const char *name)
virtual void setProgress (int progress)
virtual void unhighlight ()
~KviWindowListButton ()
Protected Slots
void tipRequest (KviDynamicToolTip *tip, const QPoint &pnt)
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *e)
virtual void drawButtonLabel (QPainter *p)
virtual void mousePressEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
void setActive (bool bActive)
Protected Attributes
bool m_bActive
KviDynamicToolTip * m_pTip
Friends
class KviClassicWindowList
Constructor & Destructor Documentation
KviWindowListButton::KviWindowListButton (QWidget * par, KviWindow * wnd, const char * name)
References connect(), m_bActive, m_pTip, and tipRequest().
KviWindowListButton::~KviWindowListButton ()
References m_pTip.
Member Function Documentation
virtual bool KviWindowListButton::active () [inline, virtual]
Reimplemented from KviWindowListItem.
void KviWindowListButton::captionChanged () [virtual]
Reimplemented from KviWindowListItem.
void KviWindowListButton::contextMenuEvent (QContextMenuEvent * e) [protected, virtual]
References KviWindow::contextPopup(), and KviWindowListItem::m_pWindow.
void KviWindowListButton::drawButtonLabel (QPainter * p) [protected, virtual]
References KviWindow::activityMeter(), KviWindow::Channel, KviWindow::Console, KviWindow::console(), KviConsoleWindow::context(), KviWindow::DeadChannel, KviWindow::DeadQuery, f, g_pActivityMeterPixmap, KviWindowListBase::getTextForConsole(), KviIrcContext::id(), KviWindow::isMinimized(), KVI_NUM_ICCOLOR_OPTIONS, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_FONT, KVI_OPTION_ICCOLOR, KVI_WINDOWLISTBUTTON_BOTTOM_MARGIN, KVI_WINDOWLISTBUTTON_CONTEXTINDICATORHEIGHT, KVI_WINDOWLISTBUTTON_CONTEXTINDICATORSPACING, KVI_WINDOWLISTBUTTON_LEFT_MARGIN, KVI_WINDOWLISTBUTTON_RIGHT_MARGIN, KVI_WINDOWLISTBUTTON_TOP_MARGIN, KviOption_boolUseWindowListActivityMeter, KviOption_boolUseWindowListIcons, KviOption_boolUseWindowListIrcContextIndicator, KviOption_colorWindowListHighlight1Text, KviOption_colorWindowListHighlight2Text, KviOption_colorWindowListHighlight3Text, KviOption_colorWindowListHighlight4Text, KviOption_colorWindowListHighlight5Text, KviOption_colorWindowListMinimizedText, KviOption_colorWindowListNormalText, KviOption_colorWindowListProgressBar, KviOption_fontWindowList, m_bActive, KviWindowListItem::m_iHighlightLevel, KviWindowListItem::m_iProgress, KviWindowListItem::m_pWindow, KviWindow::myIconPtr(), KviWindow::plainTextCaption(), KviWindow::Query, KviWindow::type(), and KviWindow::windowName().
Referenced by paintEvent().
void KviWindowListButton::highlight (int iLevel = 1) [virtual]
Reimplemented from KviWindowListItem.
References g_pMainWindow, m_bActive, KviWindowListItem::m_iHighlightLevel, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
void KviWindowListButton::mousePressEvent (QMouseEvent * e) [protected, virtual]
References KviWindow::contextPopup(), KviWindow::delayedClose(), g_pActiveWindow, g_pMainWindow, KviWindow::isMinimized(), KviWindowListItem::m_pWindow, KviWindow::minimize(), and KviMainWindow::setActiveWindow().
void KviWindowListButton::paintEvent (QPaintEvent * e) [protected, virtual]
References drawButtonLabel(), KVI_OPTION_BOOL, KviOption_boolUseFlatClassicWindowListButtons, and p.
void KviWindowListButton::setActive (bool bActive) [protected]
References m_bActive, and KviWindowListItem::m_iHighlightLevel.
void KviWindowListButton::setProgress (int progress) [virtual]
Reimplemented from KviWindowListItem.
References KviWindowListItem::m_iProgress, and KviWindowListItem::progress().
void KviWindowListButton::tipRequest (KviDynamicToolTip * tip, const QPoint & pnt) [protected, slot]
References KviWindow::getWindowListTipText(), KVI_OPTION_BOOL, KviOption_boolShowWindowListToolTips, m_pTip, KviWindowListItem::m_pWindow, and KviDynamicToolTip::tip().
Referenced by KviWindowListButton().
void KviWindowListButton::unhighlight () [virtual]
Reimplemented from KviWindowListItem.
References g_pMainWindow, KviWindowListItem::m_iHighlightLevel, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
Friends And Related Function Documentation
friend class KviClassicWindowList [friend]
Member Data Documentation
bool KviWindowListButton::m_bActive [protected]
Referenced by drawButtonLabel(), highlight(), KviWindowListButton(), and setActive().
KviDynamicToolTip* KviWindowListButton::m_pTip [protected]
Referenced by KviWindowListButton(), tipRequest(), and ~KviWindowListButton().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviWindowListBase.h
src/kvirc/ui/KviWindowListBase.cpp