KVIrc: KviKvsTreeNodeSpecialCommandWhile Class Reference
KviKvsTreeNodeSpecialCommandWhile Class Reference
#include <KviKvsTreeNodeSpecialCommandWhile.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandWhile (const QChar *pLocation, KviKvsTreeNodeExpression *e, KviKvsTreeNodeInstruction *i)
~KviKvsTreeNodeSpecialCommandWhile ()
Private Attributes
KviKvsTreeNodeExpression * m_pExpression
KviKvsTreeNodeInstruction * m_pInstruction
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandWhile::KviKvsTreeNodeSpecialCommandWhile (const QChar * pLocation, KviKvsTreeNodeExpression * e, KviKvsTreeNodeInstruction * i)
References e, i, m_pExpression, m_pInstruction, and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandWhile::~KviKvsTreeNodeSpecialCommandWhile ()
References m_pExpression, and m_pInstruction.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandWhile::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandWhile::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
bool KviKvsTreeNodeSpecialCommandWhile::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariant::asBoolean(), KviKvsRunTimeContext::breakPending(), KviKvsRunTimeContext::continuePending(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviKvsRunTimeContext::handleBreak(), KviKvsRunTimeContext::handleContinue(), m_pExpression, m_pInstruction, and v.
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeSpecialCommandWhile::m_pExpression [private]
Referenced by execute(), KviKvsTreeNodeSpecialCommandWhile(), and ~KviKvsTreeNodeSpecialCommandWhile().
KviKvsTreeNodeInstruction* KviKvsTreeNodeSpecialCommandWhile::m_pInstruction [private]
Referenced by execute(), KviKvsTreeNodeSpecialCommandWhile(), and ~KviKvsTreeNodeSpecialCommandWhile().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandWhile.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandWhile.cpp