KVIrc: AboutDialog Class Reference
AboutDialog Class Reference
#include <AboutDialog.h>
Public Member Functions
AboutDialog ()
~AboutDialog ()
Public Member Functions inherited from KviTalTabDialog
KviTalTabDialog (QWidget *pParent=0, const char *name=0, bool bModal=false)
~KviTalTabDialog ()
Protected Slots
void closeButtonPressed ()
Protected Slots inherited from KviTalTabDialog
void cancelPressed ()
void okPressed ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Protected Member Functions inherited from KviTalTabDialog
void addTab (QWidget *, const QString &)
void setCancelButton (const QString &)
void setOkButton (const QString &)
Additional Inherited Members
Signals inherited from KviTalTabDialog
void applyButtonPressed ()
void cancelButtonPressed ()
Constructor & Destructor Documentation
AboutDialog::AboutDialog ()
References __tr2qs_ctx(), KviTalTabDialog::addTab(), KviTalTabDialog::applyButtonPressed(), KviBuildInfo::buildCommand(), KviBuildInfo::buildCompiler(), KviBuildInfo::buildCompilerFlags(), KviBuildInfo::buildCPU(), KviBuildInfo::buildDate(), KviBuildInfo::buildFlags(), KviBuildInfo::buildRevision(), KviBuildInfo::buildSourcesDate(), KviBuildInfo::buildSystem(), closeButtonPressed(), connect(), KviApplication::findImage(), g, g_pApp, KviApplication::getGlobalKvircDirectory(), KVI_RELEASE_NAME, KVI_VERSION, l, KviApplication::License, KviFileUtils::loadFile(), KviOsInfo::machine(), KviOsInfo::name(), p, KviOsInfo::release(), KviTalTabDialog::setOkButton(), v, KviOsInfo::version(), and w.
AboutDialog::~AboutDialog ()
Member Function Documentation
void AboutDialog::closeButtonPressed () protected slot
Referenced by AboutDialog().
void AboutDialog::closeEvent (QCloseEvent * e) protected virtual
The documentation for this class was generated from the following files:
src/modules/about/AboutDialog.h
src/modules/about/AboutDialog.cpp