KVIrc: UPnP::SsdpConnection Class Reference
UPnP::SsdpConnection Class Reference
#include <SsdpConnection.h>
Signals
void deviceFound (const QString &hostname, int port, const QString &rootUrl)
Public Member Functions
void queryDevices (int bindPort=1500)
SsdpConnection ()
virtual ~SsdpConnection ()
Private Slots
void slotDataReceived ()
Private Attributes
QUdpSocket * m_pSocket
Detailed Description
The Simple Service Discovery Protocol allows UPnP clients to discover UPnP devices on a network. This is achieved by broadcasting a HTTP-like message over UDP. Devices can respond with their location and root service name. The RootService class uses this information to query the device for it's meta information and service list.
Author:
Diederik van der Boor
Constructor & Destructor Documentation
UPnP::SsdpConnection::SsdpConnection ()
References connect(), m_pSocket, and slotDataReceived().
UPnP::SsdpConnection::~SsdpConnection () [virtual]
References m_pSocket.
Member Function Documentation
void UPnP::SsdpConnection::deviceFound (const QString & hostname, int port, const QString & rootUrl) [signal]
Referenced by slotDataReceived().
void UPnP::SsdpConnection::queryDevices (int bindPort = 1500)
References m_pSocket.
Referenced by UPnP::Manager::initialize().
void UPnP::SsdpConnection::slotDataReceived () [private, slot]
References deviceFound(), and m_pSocket.
Referenced by SsdpConnection().
Member Data Documentation
QUdpSocket* UPnP::SsdpConnection::m_pSocket [private]
Referenced by queryDevices(), slotDataReceived(), SsdpConnection(), and ~SsdpConnection().
The documentation for this class was generated from the following files:
src/modules/upnp/SsdpConnection.h
src/modules/upnp/SsdpConnection.cpp