KVIrc: KviKvsTreeNodeOperationStringAppendWithComma Class Reference
KviKvsTreeNodeOperationStringAppendWithComma Class Reference
#include <kvi_kvs_treenode_operation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationStringAppendWithComma (const QChar *pLocation, KviKvsTreeNodeData *pRightSide)
~KviKvsTreeNodeOperationStringAppendWithComma ()
Protected Attributes
KviKvsTreeNodeData * m_pRightSide
Constructor & Destructor Documentation
KviKvsTreeNodeOperationStringAppendWithComma::KviKvsTreeNodeOperationStringAppendWithComma (const QChar * pLocation, KviKvsTreeNodeData * pRightSide)
References m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationStringAppendWithComma::~KviKvsTreeNodeOperationStringAppendWithComma ()
References m_pRightSide.
Member Function Documentation
void KviKvsTreeNodeOperationStringAppendWithComma::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationStringAppendWithComma::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pRightSide, and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationStringAppendWithComma::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), m_pRightSide, KviKvsTreeNodeOperation::m_pTargetData, KviKvsRWEvaluationResult::result(), and KviKvsVariant::setString().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringAppendWithComma::m_pRightSide [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationStringAppendWithComma(), and ~KviKvsTreeNodeOperationStringAppendWithComma().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.cpp