KVIrc: KviModeEditor Class Reference
KviModeEditor Class Reference
#include <KviModeEditor.h>
Signals
void done ()
void setMode (QString &szMode)
Public Member Functions
KviModeEditor (QWidget *par, KviWindowToolPageButton *button, const char *name, KviChannelWindow *pChan)
~KviModeEditor ()
Public Member Functions inherited from KviWindowToolWidget
KviWindowToolWidget (QWidget *pParent, KviWindowToolPageButton *pButton)
~KviWindowToolWidget ()
Protected Slots
void checkBoxToggled (bool bChecked)
void commit ()
void updateOpStatus ()
Protected Member Functions
const QString * getModeDescription (char cMode)
bool modeNeedsParameterOnlyWhenSet (char cMode)
Protected Attributes
QPushButton * m_pButton
KviChannelWindow * m_pChannel
QMap< char, QCheckBox * > m_pCheckBoxes
QMap< char, QLineEdit * > m_pLineEdits
Protected Attributes inherited from KviWindowToolWidget
Constructor & Destructor Documentation
KviModeEditor::KviModeEditor (QWidget * par, KviWindowToolPageButton * button, const char * name, KviChannelWindow * pChan)
References __tr2qs, KviHtmlGenerator::Background, KviChannelWindow::channelModeParam(), checkBoxToggled(), commit(), connect(), f, g, g_pIconManager, getModeDescription(), KviIconManager::getSmallIcon(), KviChannelWindow::hasChannelMode(), l, m_pButton, m_pChannel, m_pCheckBoxes, m_pLineEdits, KviIconManager::Mode, KviChannelWindow::plainChannelMode(), KviChannelWindow::serverInfo(), KviIrcConnectionServerInfo::supportedParameterModes(), KviIrcConnectionServerInfo::supportedParameterWhenSetModes(), KviIrcConnectionServerInfo::supportedPlainModes(), and updateOpStatus().
KviModeEditor::~KviModeEditor ()
References m_pCheckBoxes, and m_pLineEdits.
Member Function Documentation
void KviModeEditor::checkBoxToggled (bool bChecked) protected slot
References c, m_pCheckBoxes, and m_pLineEdits.
Referenced by KviModeEditor().
void KviModeEditor::commit () protected slot
References KviChannelWindow::channelModeParam(), done(), KviChannelWindow::hasChannelMode(), i, m_pChannel, m_pCheckBoxes, m_pLineEdits, KviIrcConnectionServerInfo::maxModeChanges(), modeNeedsParameterOnlyWhenSet(), KviChannelWindow::plainChannelMode(), KviChannelWindow::serverInfo(), and setMode().
Referenced by KviModeEditor().
void KviModeEditor::done () signal
Referenced by commit().
const QString * KviModeEditor::getModeDescription (char cMode) inline protected
References KviIrcConnectionServerInfo::getChannelModeDescription(), m_pChannel, and KviChannelWindow::serverInfo().
Referenced by KviModeEditor().
bool KviModeEditor::modeNeedsParameterOnlyWhenSet (char cMode) inline protected
References m_pChannel, KviChannelWindow::serverInfo(), and KviIrcConnectionServerInfo::supportedParameterWhenSetModes().
Referenced by commit().
void KviModeEditor::setMode (QString & szMode) signal
Referenced by commit().
void KviModeEditor::updateOpStatus () protected slot
References __tr2qs, KviWindow::connection(), KviIrcConnectionUserInfo::hasUserMode(), KviChannelWindow::isMeChanAdmin(), KviChannelWindow::isMeChanOwner(), KviChannelWindow::isMeHalfOp(), KviChannelWindow::isMeOp(), m_pButton, m_pChannel, m_pCheckBoxes, m_pLineEdits, and KviIrcConnection::userInfo().
Referenced by KviModeEditor().
Member Data Documentation
QPushButton* KviModeEditor::m_pButton protected
Reimplemented from KviWindowToolWidget.
Referenced by KviModeEditor(), and updateOpStatus().
KviChannelWindow* KviModeEditor::m_pChannel protected
Referenced by commit(), getModeDescription(), KviModeEditor(), modeNeedsParameterOnlyWhenSet(), and updateOpStatus().
QMap<char, QCheckBox *> KviModeEditor::m_pCheckBoxes protected
Referenced by checkBoxToggled(), commit(), KviModeEditor(), updateOpStatus(), and ~KviModeEditor().
QMap<char, QLineEdit *> KviModeEditor::m_pLineEdits protected
Referenced by checkBoxToggled(), commit(), KviModeEditor(), updateOpStatus(), and ~KviModeEditor().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviModeEditor.h
src/kvirc/ui/KviModeEditor.cpp