KVIrc: KviKvsTreeNodeObjectField Class Reference
KviKvsTreeNodeObjectField Class Reference
#include <KviKvsTreeNodeObjectField.h>
Public Member Functions
virtual bool canEvaluateInObjectScope ()
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pResult)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
KviKvsTreeNodeObjectField (const QChar *pLocation, const QString &szIdentifier)
~KviKvsTreeNodeObjectField ()
Public Member Functions inherited from KviKvsTreeNodeVariable
KviKvsTreeNodeVariable (const QChar *pLocation, const QString &szIdentifier)
~KviKvsTreeNodeVariable ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeVariable
virtual bool canEvaluateToObjectReference ()
virtual bool isReadOnly ()
Protected Attributes inherited from KviKvsTreeNodeVariable
QString m_szIdentifier
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeObjectField::KviKvsTreeNodeObjectField (const QChar * pLocation, const QString & szIdentifier)
KviKvsTreeNodeObjectField::~KviKvsTreeNodeObjectField ()
Member Function Documentation
bool KviKvsTreeNodeObjectField::canEvaluateInObjectScope () virtual
Reimplemented from KviKvsTreeNodeVariable.
void KviKvsTreeNodeObjectField::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
void KviKvsTreeNodeObjectField::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
bool KviKvsTreeNodeObjectField::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pResult) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::copyFrom(), KviKvsObject::dataContainer(), KviKvsHash::find(), KviKvsTreeNodeVariable::m_szIdentifier, KviKvsVariant::setNothing(), and v.
KviKvsRWEvaluationResult * KviKvsTreeNodeObjectField::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsObject::dataContainer(), KviKvsHash::get(), and KviKvsTreeNodeVariable::m_szIdentifier.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeObjectField.h
src/kvirc/kvs/tree/KviKvsTreeNodeObjectField.cpp