KVIrc: OptionsWidget_dccVoice Class Reference
OptionsWidget_dccVoice Class Reference
#include <OptionsWidget_dcc.h>
Public Member Functions
OptionsWidget_dccVoice (QWidget *)
~OptionsWidget_dccVoice ()
Public Member Functions inherited from KviOptionsWidget
void addAdvancedButton (int x1, int y1, int x2, int y2)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
virtual void commit ()
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Additional Inherited Members
Signals inherited from KviOptionsWidget
void wantToSwitchToAdvancedPage (KviOptionsWidget *)
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
void switchToAdvancedPage ()
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_dccVoice::OptionsWidget_dccVoice (QWidget * p)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolAutoAcceptDccVoice, KviOption_boolCreateMinimizedDccVoice, KviOption_boolCreateMinimizedDccVoiceWhenAutoAccepted, KviOption_boolDccVoiceForceHalfDuplex, KviOption_boolDccVoiceVolumeSliderControlsPCM, KviOption_stringDccVoiceMixerDevice, KviOption_stringDccVoiceSoundDevice, KviOption_uintDccVoicePreBufferSize, KviStringSelector::setMinimumLabelWidth(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_dccVoice::~OptionsWidget_dccVoice ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_dcc.h
src/modules/options/OptionsWidget_dcc.cpp