KVIrc: KviIrcdRatboxIrcServerInfo Class Reference
KviIrcdRatboxIrcServerInfo Class Reference
#include <KviIrcConnectionServerInfo.h>
Public Member Functions
virtual const QString & getChannelModeDescription (char mode)
virtual bool getNeedsOpToListModeseI ()
virtual char getRegisterModeChar ()
virtual const char * getSoftware ()
virtual const QString & getUserModeDescription (QChar mode)
virtual QChar getUserModeRequirement (QChar mode)
KviIrcdRatboxIrcServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
Public Member Functions inherited from KviHybridServerInfo
KviHybridServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
Public Member Functions inherited from KviBasicIrcServerInfo
virtual bool getNeedsOperToSetS ()
KviBasicIrcServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
virtual ~KviBasicIrcServerInfo ()
Additional Inherited Members
Protected Attributes inherited from KviBasicIrcServerInfo
KviIrcConnectionServerInfo * m_pParent
QString m_szServerVersion
Constructor & Destructor Documentation
KviIrcdRatboxIrcServerInfo::KviIrcdRatboxIrcServerInfo (KviIrcConnectionServerInfo * pParent = 0, const QString & version = KviQString::Empty) inline
Member Function Documentation
const QString & KviIrcdRatboxIrcServerInfo::getChannelModeDescription (char mode) virtual
Reimplemented from KviHybridServerInfo.
Reimplemented in KviCharybdisServerInfo.
References __tr2qs, and KviHybridServerInfo::getChannelModeDescription().
Referenced by KviCharybdisServerInfo::getChannelModeDescription().
virtual bool KviIrcdRatboxIrcServerInfo::getNeedsOpToListModeseI () inline virtual
Reimplemented from KviBasicIrcServerInfo.
virtual char KviIrcdRatboxIrcServerInfo::getRegisterModeChar () inline virtual
Reimplemented from KviHybridServerInfo.
Reimplemented in KviIrcdSevenIrcServerInfo.
virtual const char* KviIrcdRatboxIrcServerInfo::getSoftware () inline virtual
Reimplemented from KviHybridServerInfo.
Reimplemented in KviIrcdSevenIrcServerInfo, and KviCharybdisServerInfo.
const QString & KviIrcdRatboxIrcServerInfo::getUserModeDescription (QChar mode) virtual
Reimplemented from KviHybridServerInfo.
Reimplemented in KviIrcdSevenIrcServerInfo, and KviCharybdisServerInfo.
References __tr2qs, and KviHybridServerInfo::getUserModeDescription().
Referenced by KviCharybdisServerInfo::getUserModeDescription().
QChar KviIrcdRatboxIrcServerInfo::getUserModeRequirement (QChar mode) virtual
Reimplemented from KviHybridServerInfo.
Reimplemented in KviIrcdSevenIrcServerInfo, and KviCharybdisServerInfo.
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionServerInfo.h
src/kvirc/kernel/KviIrcConnectionServerInfo.cpp