KVIrc: KviLagMeter Class Reference
KviLagMeter Class Reference
#include <kvi_lagmeter.h>
Public Member Functions
unsigned int lag ()
void lagCheckAbort (const char *key)
bool lagCheckComplete (const char *key)
void lagCheckRegister (const char *key, unsigned int uReliability=50)
unsigned int secondsSinceLastCompleted ()
Protected Member Functions
KviLagMeter (KviIrcConnection *c)
virtual void timerEvent (QTimerEvent *e)
~KviLagMeter ()
Protected Attributes
bool m_bOnAlarm
KviPointerList< KviLagCheck > * m_pCheckList
KviIrcConnection * m_pConnection
bool * m_pDeletionSignal
long m_tFirstOwnCheck
long m_tLastCompleted
long m_tLastOwnCheck
unsigned int m_uLag
unsigned int m_uLastEmittedLag
unsigned int m_uLastReliability
Friends
class KviIrcConnection
Constructor & Destructor Documentation
KviLagMeter::KviLagMeter (KviIrcConnection * c) [protected]
References KVI_OPTION_UINT, KviOption_uintLagMeterHeartbeat, m_bOnAlarm, m_pCheckList, m_pConnection, m_pDeletionSignal, m_tFirstOwnCheck, m_tLastCompleted, m_tLastOwnCheck, m_uLag, m_uLastEmittedLag, m_uLastReliability, and KviPointerList< T >::setAutoDelete().
KviLagMeter::~KviLagMeter () [protected]
References m_pCheckList, and m_pDeletionSignal.
Member Function Documentation
unsigned int KviLagMeter::lag () [inline]
Referenced by KviIrcContextDisplay::drawContents(), KviIrcContextDisplay::tipRequest(), KviStatusBarLagIndicator::tipText(), and KviStatusBarLagIndicator::updateDisplay().
void KviLagMeter::lagCheckAbort (const char * key)
References __tr2qs, _OUTPUT_PARANOIC, KviPointerList< T >::append(), c, KviIrcConnection::console(), KviPointerList< T >::first(), KVI_OUT_VERBOSE, kvi_strEqualCS(), m_pCheckList, m_pConnection, KviPointerList< T >::next(), KviWindow::output(), KviStr::ptr(), KviPointerList< T >::removeRef(), KviPointerList< T >::setAutoDelete(), and KviLagCheck::szKey.
Referenced by KviStupidNotifyListManager::stop(), and KviIsOnNotifyListManager::stop().
bool KviLagMeter::lagCheckComplete (const char * key)
References __tr2qs, _OUTPUT_PARANOIC, c, KviIrcConnection::console(), KviPointerList< T >::first(), kvi_gettimeofday(), KVI_OUT_VERBOSE, kvi_strEqualCS(), KviLagCheck::lSecs, KviLagCheck::lUSecs, m_pCheckList, m_pConnection, m_tFirstOwnCheck, m_tLastCompleted, m_tLastOwnCheck, m_uLag, m_uLastReliability, KviPointerList< T >::next(), KviWindow::output(), KviStr::ptr(), KviPointerList< T >::removeFirst(), KviLagCheck::szKey, and KviLagCheck::uReliability.
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviServerParser::parseCtcpReplyLagcheck(), KviServerParser::parseLiteralPong(), and KviServerParser::parseNumericEndOfWho().
void KviLagMeter::lagCheckRegister (const char * key, unsigned int uReliability = 50)
References __tr2qs, _OUTPUT_PARANOIC, KviPointerList< T >::append(), c, KviIrcConnection::console(), KviPointerList< T >::count(), kvi_gettimeofday(), KVI_OUT_VERBOSE, KviLagCheck::lSecs, KviLagCheck::lUSecs, m_pCheckList, m_pConnection, KviWindow::output(), KviPointerList< T >::removeFirst(), KviLagCheck::szKey, and KviLagCheck::uReliability.
Referenced by KviIrcConnection::heartbeat(), KviServerParser::parseLiteralJoin(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), and timerEvent().
unsigned int KviLagMeter::secondsSinceLastCompleted ()
References kvi_gettimeofday(), and m_tLastCompleted.
Referenced by KviStatusBarLagIndicator::tipText().
void KviLagMeter::timerEvent (QTimerEvent * e) [protected, virtual]
References __tr2qs, _OUTPUT_PARANOIC, c, KviFrame::childConnectionLagChange(), KviIrcConnection::Connected, KviIrcConnection::console(), KviPointerList< T >::count(), KviIrcConnection::encodeText(), KviPointerList< T >::first(), KviStr::Format, g_pFrame, kvi_gettimeofday(), KVI_OPTION_UINT, KVI_OUT_VERBOSE, KviEvent_OnLagAlarmTimeDown, KviEvent_OnLagAlarmTimeUp, KviEvent_OnLagCheck, KviOption_uintLagAlarmTime, KviOption_uintLagMeterHeartbeat, KVS_TRIGGER_EVENT_2_HALTED, lagCheckRegister(), KviLagCheck::lSecs, m_bOnAlarm, m_pCheckList, m_pConnection, m_pDeletionSignal, m_tFirstOwnCheck, m_tLastCompleted, m_tLastOwnCheck, m_uLag, m_uLastEmittedLag, m_uLastReliability, KviIrcConnectionServerInfo::name(), KviIrcConnectionUserInfo::nickName(), KviWindow::output(), KviStr::ptr(), KviIrcConnection::sendFmtData(), KviIrcConnection::serverInfo(), KviIrcConnection::state(), and KviIrcConnection::userInfo().
Friends And Related Function Documentation
friend class KviIrcConnection [friend]
Member Data Documentation
bool KviLagMeter::m_bOnAlarm [protected]
Referenced by KviLagMeter(), and timerEvent().
KviPointerList<KviLagCheck>* KviLagMeter::m_pCheckList [protected]
Referenced by KviLagMeter(), lagCheckAbort(), lagCheckComplete(), lagCheckRegister(), timerEvent(), and ~KviLagMeter().
KviIrcConnection* KviLagMeter::m_pConnection [protected]
Referenced by KviLagMeter(), lagCheckAbort(), lagCheckComplete(), lagCheckRegister(), and timerEvent().
bool* KviLagMeter::m_pDeletionSignal [protected]
Referenced by KviLagMeter(), timerEvent(), and ~KviLagMeter().
long KviLagMeter::m_tFirstOwnCheck [protected]
Referenced by KviLagMeter(), lagCheckComplete(), and timerEvent().
long KviLagMeter::m_tLastCompleted [protected]
Referenced by KviLagMeter(), lagCheckComplete(), secondsSinceLastCompleted(), and timerEvent().
long KviLagMeter::m_tLastOwnCheck [protected]
Referenced by KviLagMeter(), lagCheckComplete(), and timerEvent().
unsigned int KviLagMeter::m_uLag [protected]
Referenced by KviLagMeter(), lagCheckComplete(), and timerEvent().
unsigned int KviLagMeter::m_uLastEmittedLag [protected]
Referenced by KviLagMeter(), and timerEvent().
unsigned int KviLagMeter::m_uLastReliability [protected]
Referenced by KviLagMeter(), lagCheckComplete(), and timerEvent().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_lagmeter.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_lagmeter.cpp