KVIrc: KviStr Class Reference
KviStr Class Reference
#include <kvi_string.h>
Public Types
enum KviFormatConstructorTag { Format, Sprintf }
Public Member Functions
void append (const KviStr &str)
void append (const QString &str)
void append (char c)
void append (const char *str)
void append (const char *str, int len)
void append (KviFormatConstructorTag dummy, const char *fmt,...)
char & at (int idx) const
int base64ToBuffer (char **buffer, bool bNullToNewlines=false)
void bufferToBase64 (const char *buffer, int len)
void bufferToHex (const char *buffer, int len)
void clear ()
bool contains (const char *str, bool caseS=true) const
bool contains (char c, bool caseS=true) const
KviStr & cut (int idx, int len)
KviStr & cutFromFirst (char c, bool bIncluded=true)
KviStr & cutFromFirst (const char *c, bool bIncluded=true)
KviStr & cutFromLast (char c, bool bIncluded=true)
KviStr & cutFromLast (const char *c, bool bIncluded=true)
KviStr & cutLeft (int len)
KviStr & cutRight (int len)
KviStr & cutToFirst (char c, bool bIncluded=true)
KviStr & cutToFirst (const char *c, bool bIncluded=true)
KviStr & cutToLast (char c, bool bIncluded=true)
KviStr & cutToLast (const char *c, bool bIncluded=true)
void ensureLastCharIs (char ch)
bool equalsCI (const KviStr &other) const
bool equalsCI (const char *other) const
bool equalsCIN (const char *other, int len) const
bool equalsCS (const char *other) const
bool equalsCS (const KviStr &other) const
bool equalsCSN (const char *other, int len) const
void extractFromString (const char *begin, const char *end)
int find (char c, int startIdx) const
int find (const char *str, int startIdx, bool caseS=true) const
int findFirstIdx (const char *str, bool caseS=true) const
int findFirstIdx (char c) const
int findLastIdx (const char *str, bool caseS=true) const
int findLastIdx (char c) const
int findRev (const char *str, int startIdx, bool caseS=true) const
bool firstCharIs (char ch) const
bool getLine (KviStr &str)
bool getToken (KviStr &str, char sep)
KviStr getToken (char sep)
bool hasData () const
bool hasNonWhiteSpaceData () const
KviStr & hexDecode (const char *pFrom)
KviStr & hexDecode ()
KviStr & hexEncodeWhiteSpace ()
KviStr & hexEncodeWithTable (const unsigned char table[256])
int hexToBuffer (char **buffer, bool bNullToNewlines=false)
KviStr & insert (int idx, const char *data)
KviStr & insert (int idx, char c)
bool isEmpty () const
bool isNum () const
bool isUnsignedNum () const
void joinFromArray (KviStr **strings, const char *sep=0, bool bLastSep=false)
KviStr (const char *str)
KviStr (const char *bg, const char *end)
KviStr (char c, int fillLen=1)
KviStr ()
KviStr (const kvi_wchar_t *unicode)
KviStr (const QByteArray &str)
KviStr (KviFormatConstructorTag tag, const char *fmt,...)
KviStr (const kvi_wchar_t *unicode, int len)
KviStr (const KviStr &str)
KviStr (const char *str, int len)
KviStr (const QString &str)
bool lastCharIs (char ch) const
KviStr left (int maxLen) const
KviStr leftToFirst (char c, bool bIncluded=false) const
KviStr leftToLast (char c, bool bIncluded=false) const
int len () const
KviStr lower () const
KviStr lowerISO88591 () const
KviStr middle (int idx, int maxLen) const
int occurences (const char *str, bool caseS=true) const
int occurences (char c, bool caseS=true) const
operator const char * () const
KviStr & operator+= (char c)
KviStr & operator+= (const KviStr &str)
KviStr & operator+= (const char *str)
KviStr & operator+= (const QString &str)
KviStr & operator= (const QString &str)
KviStr & operator= (const QByteArray &str)
KviStr & operator= (const char *str)
KviStr & operator= (const KviStr &str)
KviStr & operator= (char c)
void prepend (const KviStr &str)
void prepend (const char *str)
void prepend (const char *str, int len)
char * ptr () const
KviStr & replaceAll (const char *toFind, const char *str, bool bCaseS=true)
KviStr & replaceAll (const char c, const char *str)
KviStr right (int maxLen) const
KviStr & setLen (int len)
void setLength (int iLen)
KviStr & setNum (unsigned long num)
KviStr & setNum (unsigned char num)
KviStr & setNum (short num)
KviStr & setNum (unsigned short num)
KviStr & setNum (unsigned int num)
KviStr & setNum (int num)
KviStr & setNum (char num)
KviStr & setNum (long num)
KviStr & setStr (const char *str, int len=-1)
KviStr ** splitToArray (char sep, int max, int *realCount) const
KviStr & sprintf (const char *fmt,...)
KviStr & stripLeft (char c)
KviStr & stripLeftWhiteSpace ()
KviStr & stripRight (char c)
KviStr & stripRightWhiteSpace ()
KviStr & stripSpace ()
char toChar (bool *bOk=0) const
int toInt (bool *bOk=0) const
long toLong (bool *bOk=0) const
long toLongExt (bool *bOk=0, int base=0)
long long toLongLong (bool *bOk=0) const
void toLower ()
void toLowerISO88591 ()
short toShort (bool *bOk=0) const
unsigned char toUChar (bool *bOk=0) const
unsigned int toUInt (bool *bOk=0) const
unsigned long toULong (bool *bOk=0) const
unsigned long long toULongLong (bool *bOk=0) const
void toUpper ()
void toUpperISO88591 ()
unsigned short toUShort (bool *bOk=0) const
KviStr & transliterate (const char *szToFind, const char *szReplacement)
KviStr & trimmed ()
KviStr upper () const
KviStr upperISO88591 () const
KviStr & vsprintf (const char *fmt, kvi_va_list list)
~KviStr ()
Static Public Member Functions
static KviStr & emptyString ()
static bool ext_contains (register const char *data, const char *item, bool caseS=true)
static void freeArray (KviStr **strings)
static void freeBuffer (char *buffer)
Public Attributes
int m_len
char * m_ptr
Member Enumeration Documentation
enum KviStr::KviFormatConstructorTag
Enumerator:
Format
Sprintf
Constructor & Destructor Documentation
KviStr::KviStr ()
References kvi_malloc, m_len, and m_ptr.
Referenced by leftToFirst(), leftToLast(), and splitToArray().
KviStr::KviStr (const char * str)
References kvi_fastmove(), kvi_malloc, m_len, and m_ptr.
KviStr::KviStr (const char * str, int len)
References KVI_ASSERT, kvi_fastmove(), kvi_malloc, len(), m_len, and m_ptr.
KviStr::KviStr (const char * bg, const char * end)
References KVI_ASSERT, kvi_fastmove(), kvi_malloc, m_len, and m_ptr.
KviStr::KviStr (KviFormatConstructorTag tag, const char * fmt, ...)
References kvi_malloc, kvi_realloc, kvi_va_end, kvi_va_list, kvi_va_start, kvi_vsnprintf(), m_len, and m_ptr.
KviStr::KviStr (const KviStr & str)
References KVI_ASSERT, kvi_fastmove(), kvi_malloc, m_len, and m_ptr.
KviStr::KviStr (const QString & str)
References kvi_fastmove(), kvi_malloc, m_len, m_ptr, and KviQString::toUtf8().
KviStr::KviStr (const QByteArray & str)
References kvi_fastmove(), kvi_malloc, m_len, and m_ptr.
KviStr::KviStr (char c, int fillLen = 1)
References c, KVI_ASSERT, kvi_malloc, m_len, and m_ptr.
KviStr::KviStr (const kvi_wchar_t * unicode)
References kvi_malloc, kvi_wstrlen(), m_len, and m_ptr.
KviStr::KviStr (const kvi_wchar_t * unicode, int len)
References kvi_malloc, len(), m_len, and m_ptr.
KviStr::~KviStr ()
References kvi_free, and m_ptr.
Member Function Documentation
void KviStr::append (const KviStr & str)
References KVI_ASSERT, kvi_fastmove(), kvi_realloc, m_len, and m_ptr.
Referenced by KviServerParser::decodeCtcpEscape(), KviServerParser::encodeCtcpParameter(), KviServerParser::extractCtcpParameter(), joinFromArray(), KviDebugContext::KviDebugContext(), main(), KviIrcUrl::parse(), parseArgs(), KviServerParser::parseNumeric004(), KviServerParser::parseNumericStats(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), replaceAll(), KviHttpRequestThread::runInternal(), KviIrcContextDisplay::tipRequest(), KviDebugContext::trace(), KviUserListView::updateUsersLabel(), KviConfig::writeEntry(), and KviDebugContext::~KviDebugContext().
void KviStr::append (const QString & str)
References kvi_fastmove(), kvi_realloc, m_len, m_ptr, and KviQString::toUtf8().
void KviStr::append (char c)
References kvi_realloc, m_len, and m_ptr.
void KviStr::append (const char * str)
References kvi_fastmove(), kvi_realloc, len(), m_len, and m_ptr.
void KviStr::append (const char * str, int len)
References KVI_ASSERT, kvi_fastmove(), kvi_realloc, len(), m_len, and m_ptr.
void KviStr::append (KviFormatConstructorTag dummy, const char * fmt, ...)
References kvi_realloc, kvi_va_end, kvi_va_list, kvi_va_start, kvi_vsnprintf(), m_len, and m_ptr.
char& KviStr::at (int idx) const [inline]
Referenced by KviIrcMessage::paramString().
int KviStr::base64ToBuffer (char ** buffer, bool bNullToNewlines = false)
References get_base64_idx(), kvi_free, kvi_malloc, kvi_realloc, len(), m_len, and m_ptr.
void KviStr::bufferToBase64 (const char * buffer, int len)
References base64_chars, kvi_realloc, m_len, and m_ptr.
Referenced by KviKvsCoreFunctions::KVSCF(), and KviIrcSocket::proxyLoginHttp().
void KviStr::bufferToHex (const char * buffer, int len)
References hexdigits, KVI_ASSERT, kvi_realloc, m_len, and m_ptr.
Referenced by KviKvsCoreFunctions::KVSCF().
void KviStr::clear ()
References kvi_realloc, m_len, and m_ptr.
Referenced by setStr().
bool KviStr::contains (const char * str, bool caseS = true) const
References c, KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), and m_ptr.
Referenced by KviStringConversion::fromString(), KviServerParser::parseCtcpReplyPing(), and KviServerParser::parseNumeric004().
bool KviStr::contains (char c, bool caseS = true) const
References m_ptr.
KviStr & KviStr::cut (int idx, int len)
References KVI_ASSERT, kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
KviStr & KviStr::cutFromFirst (char c, bool bIncluded = true)
References cutRight(), findFirstIdx(), and m_len.
Referenced by KviLocale::codecForName(), KviLocale::findCatalogue(), KviLocale::init(), KviMessageCatalogue::load(), KviServerParser::parseCtcpReplyPing(), KviHttpRequest::processData(), and KviIrcSocket::proxyHandleHttpFinalReply().
KviStr & KviStr::cutFromFirst (const char * c, bool bIncluded = true)
References cutRight(), findFirstIdx(), len(), and m_len.
KviStr & KviStr::cutFromLast (char c, bool bIncluded = true)
References cutRight(), findLastIdx(), and m_len.
KviStr & KviStr::cutFromLast (const char * c, bool bIncluded = true)
References cutRight(), findLastIdx(), len(), and m_len.
KviStr & KviStr::cutLeft (int len)
References KVI_ASSERT, kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
Referenced by cutToFirst(), cutToLast(), getLine(), getToken(), KviIsOnNotifyListManager::handleUserhost(), KviMessageCatalogue::load(), KviIrcUrl::parse(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), KviHttpRequest::processHeader(), and replaceAll().
KviStr & KviStr::cutRight (int len)
References KVI_ASSERT, kvi_realloc, len(), m_len, and m_ptr.
Referenced by cutFromFirst(), cutFromLast(), KviIsOnNotifyListManager::handleUserhost(), KviApp::ipcMessage(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), and KviDebugContext::~KviDebugContext().
KviStr & KviStr::cutToFirst (const char * c, bool bIncluded = true)
References cutLeft(), findFirstIdx(), and len().
KviStr & KviStr::cutToFirst (char c, bool bIncluded = true)
References cutLeft(), and findFirstIdx().
Referenced by KviServerParser::parseCtcpReplyPing(), and KviHttpRequest::processHeader().
KviStr & KviStr::cutToLast (char c, bool bIncluded = true)
References cutLeft(), and findLastIdx().
Referenced by KviMediaManager::findMediaType().
KviStr & KviStr::cutToLast (const char * c, bool bIncluded = true)
References cutLeft(), findLastIdx(), and len().
KviStr & KviStr::emptyString () [static]
References g_szApplicationWideEmptyString.
Referenced by kvi_hash_key_default(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), and KviIrcMessage::safeTrailingString().
void KviStr::ensureLastCharIs (char ch) [inline]
References KviQString::lastCharIs().
Referenced by KviMediaManager::findMediaType().
bool KviStr::equalsCI (const KviStr & other) const [inline]
References kvi_strEqualCI(), m_len, and m_ptr.
Referenced by KviModuleExtensionManager::allocateExtension(), and KviHttpRequest::processHeader().
bool KviStr::equalsCI (const char * other) const [inline]
References kvi_strEqualCI().
bool KviStr::equalsCIN (const char * other, int len) const [inline]
References kvi_strEqualCIN().
bool KviStr::equalsCS (const KviStr & other) const [inline]
References kvi_strEqualCS(), m_len, and m_ptr.
bool KviStr::equalsCS (const char * other) const [inline]
References kvi_strEqualCS().
bool KviStr::equalsCSN (const char * other, int len) const [inline]
References kvi_strEqualCSN().
bool KviStr::ext_contains (register const char * data, const char * item, bool caseS = true) [static]
References c, kvi_strEqualCIN(), kvi_strEqualCSN(), and len().
void KviStr::extractFromString (const char * begin, const char * end)
References KVI_ASSERT, kvi_fastmove(), kvi_realloc, m_len, and m_ptr.
Referenced by KviIrcMessage::KviIrcMessage().
int KviStr::find (char c, int startIdx) const
References m_len, and m_ptr.
int KviStr::find (const char * str, int startIdx, bool caseS = true) const
References kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_len, and m_ptr.
int KviStr::findFirstIdx (char c) const
References m_ptr.
Referenced by KviLocale::codecForName(), cutFromFirst(), cutToFirst(), KviLocale::findCatalogue(), KviIsOnNotifyListManager::handleUserhost(), KviApp::ipcMessage(), kvi_mayBeSpam(), leftToFirst(), KviMessageCatalogue::load(), KviIrcUrl::parse(), KviHttpRequest::processHeader(), KviIrcSocket::proxyHandleHttpFinalReply(), and replaceAll().
int KviStr::findFirstIdx (const char * str, bool caseS = true) const
References KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), and m_ptr.
int KviStr::findLastIdx (char c) const
References m_len, and m_ptr.
Referenced by cutFromLast(), cutToLast(), and leftToLast().
int KviStr::findLastIdx (const char * str, bool caseS = true) const
References KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_len, and m_ptr.
int KviStr::findRev (const char * str, int startIdx, bool caseS = true) const
References kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_len, and m_ptr.
bool KviStr::firstCharIs (char ch) const [inline]
Referenced by KviIsOnNotifyListManager::handleUserhost(), and KviIrcUrl::parse().
void KviStr::freeArray (KviStr ** strings) [static]
References kvi_free.
Referenced by KviCommandFormatter::unindent().
void KviStr::freeBuffer (char * buffer) [static]
References kvi_free.
Referenced by KviKvsCoreFunctions::KVSCF().
bool KviStr::getLine (KviStr & str)
References cutLeft(), KVI_ASSERT, kvi_fastmove(), kvi_realloc, m_len, and m_ptr.
KviStr KviStr::getToken (char sep)
References cutLeft(), and m_ptr.
bool KviStr::getToken (KviStr & str, char sep)
References cutLeft(), KVI_ASSERT, kvi_fastmove(), kvi_realloc, m_len, and m_ptr.
Referenced by KviStringConversion::fromString(), KviServerParser::parseNumericWhoReply(), and KviConfig::readColorEntry().
bool KviStr::hasData () const [inline]
Referenced by KviApp::createFrame(), KviIrcMessage::decodeAndSplitPrefix(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviCommandFormatter::hasLeadingChars(), KviLocale::init(), KviInputEditor::keyReleaseEvent(), KviMessageCatalogue::load(), main(), KviIrcUrl::parse(), parseArgs(), KviServerParser::parseNumeric004(), KviServerParser::parseNumeric005(), KviServerParser::parseNumericStats(), KviServerParser::parseNumericTopicWhoTime(), KviHttpRequest::processHeader(), KviIrcSocket::proxyLoginV4(), KviIrcMessage::safePrefix(), and KviConfig::writeEntry().
bool KviStr::hasNonWhiteSpaceData () const
References m_ptr.
KviStr & KviStr::hexDecode (const char * pFrom)
References get_decimal_from_hex_digit_char(), kvi_free, kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
Referenced by KviConfig::load().
KviStr& KviStr::hexDecode () [inline]
References hexDecode().
Referenced by hexDecode().
KviStr & KviStr::hexEncodeWhiteSpace ()
References hexEncodeWithTable().
Referenced by KviConfig::save().
KviStr & KviStr::hexEncodeWithTable (const unsigned char table[256])
References hexdigits, kvi_free, kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
Referenced by hexEncodeWhiteSpace(), and KviConfig::save().
int KviStr::hexToBuffer (char ** buffer, bool bNullToNewlines = false)
References get_decimal_from_hex_digit_char(), kvi_free, kvi_malloc, len(), m_len, m_ptr, and ptr().
KviStr & KviStr::insert (int idx, const char * data)
References KVI_ASSERT, kvi_fastmove(), kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
KviStr & KviStr::insert (int idx, char c)
References kvi_memmove(), kvi_realloc, m_len, and m_ptr.
bool KviStr::isEmpty () const [inline]
Referenced by KviStringConversion::fromString(), KviLocale::init(), KviConfig::load(), main(), KviIrcUrl::parse(), KviServerParser::parseCtcpRequestClientinfo(), and KviServerParser::parseCtcpRequestFinger().
bool KviStr::isNum () const
References m_ptr.
bool KviStr::isUnsignedNum () const
References m_ptr.
Referenced by KviServerParser::parseNumericCreationTime(), and KviConfig::readColorEntry().
void KviStr::joinFromArray (KviStr ** strings, const char * sep = 0, bool bLastSep = false)
References append(), and setLen().
Referenced by KviCommandFormatter::unindent().
bool KviStr::lastCharIs (char ch) const [inline]
Referenced by KviIsOnNotifyListManager::handleUserhost(), KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
KviStr KviStr::left (int maxLen) const
References m_len, and m_ptr.
Referenced by KviIsOnNotifyListManager::handleUserhost(), KviIrcUrl::parse(), KviHttpRequest::processHeader(), replaceAll(), stripSpace(), and trimmed().
KviStr KviStr::leftToFirst (char c, bool bIncluded = false) const
References findFirstIdx(), KviStr(), and m_ptr.
KviStr KviStr::leftToLast (char c, bool bIncluded = false) const
References findLastIdx(), KviStr(), and m_ptr.
int KviStr::len () const [inline]
Referenced by append(), base64ToBuffer(), contains(), cut(), cutFromFirst(), cutFromLast(), cutLeft(), cutRight(), cutToFirst(), cutToLast(), ext_contains(), find(), findFirstIdx(), findLastIdx(), findRev(), hexDecode(), hexEncodeWithTable(), hexToBuffer(), insert(), KviMediaManager::insertMediaType(), KviApp::ipcMessage(), KviIpcSentinel::KviIpcSentinel(), KviIrcMessage::KviIrcMessage(), KviStr(), KviMessageCatalogue::load(), KviConfig::load(), occurences(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), KviServerParser::parseNumeric005(), prepend(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), replaceAll(), KviFile::save(), KviConfig::save(), setLen(), setStr(), KviQString::vsprintf(), and KviDebugContext::~KviDebugContext().
KviStr KviStr::lower () const
References toLower().
KviStr KviStr::lowerISO88591 () const
References toLowerISO88591().
KviStr KviStr::middle (int idx, int maxLen) const
References KVI_ASSERT, m_len, and m_ptr.
int KviStr::occurences (const char * str, bool caseS = true) const
References c, KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), and m_ptr.
Referenced by KviMediaManager::insertMediaType(), and KviServerParser::parseNumeric004().
int KviStr::occurences (char c, bool caseS = true) const
References m_ptr.
KviStr::operator const char * () const [inline]
KviStr& KviStr::operator+= (const char * str) [inline]
KviStr& KviStr::operator+= (char c) [inline]
KviStr& KviStr::operator+= (const KviStr & str) [inline]
KviStr& KviStr::operator+= (const QString & str) [inline]
KviStr & KviStr::operator= (const KviStr & str)
References KVI_ASSERT, kvi_fastmove(), kvi_realloc, m_len, and m_ptr.
KviStr & KviStr::operator= (const char * str)
References kvi_memmove(), kvi_realloc, m_len, and m_ptr.
KviStr & KviStr::operator= (char c)
References c, kvi_realloc, m_len, and m_ptr.
KviStr & KviStr::operator= (const QByteArray & str)
References kvi_fastmove(), kvi_realloc, m_len, and m_ptr.
KviStr & KviStr::operator= (const QString & str)
References kvi_fastmove(), kvi_realloc, m_len, m_ptr, and KviQString::toUtf8().
void KviStr::prepend (const KviStr & str)
References KVI_ASSERT, kvi_fastmove(), kvi_memmove(), kvi_realloc, m_len, and m_ptr.
Referenced by KviMediaManager::findMediaType(), and KviIrcUrl::parse().
void KviStr::prepend (const char * str)
References kvi_fastmove(), kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
void KviStr::prepend (const char * str, int len)
References KVI_ASSERT, kvi_fastmove(), kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
char* KviStr::ptr () const [inline]
Referenced by KviModuleExtensionManager::allocateExtension(), KviModuleExtensionManager::allocateExtensionGetDescriptorList(), KviLocale::codecForName(), KviApp::createFrame(), KviIrcMessage::decodeAndSplitPrefix(), KviHttpRequest::event(), KviLocale::findCatalogue(), KviModuleExtensionManager::findExtensionDescriptor(), KviMediaManager::findMediaType(), KviStringConversion::fromString(), KviParameterList::getBool(), KviModuleExtensionManager::getExtensionList(), KviApp::getLocalKvircDirectory(), KviIrcConnection::handleAuthenticate(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), hexToBuffer(), KviIconWidget::init(), KviLocale::init(), KviApp::ipcMessage(), kvi_compare(), kvi_hash_hash(), kvi_hash_key_equal(), KviDebugContext::KviDebugContext(), KviIpcSentinel::KviIpcSentinel(), KviIrcMessage::KviIrcMessage(), KviSockaddr::KviSockaddr(), KviKvsCoreFunctions::KVSCF(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviStatusBar::load(), KviInputHistory::load(), KviMessageCatalogue::load(), KviFile::load(), KviProxyDataBase::load(), KviMediaManager::load(), KviConfig::load(), KviStatusBarUpdateIndicator::loadState(), KviStatusBarConnectionTimer::loadState(), KviStatusBarClock::loadState(), KviStatusBarAwayIndicator::loadState(), KviIrcConnection::loginComplete(), main(), KviMenuBar::newConnectionToServer(), KviQuery::ownMessage(), KviChannel::ownMessage(), KviTopicWidget::paintColoredText(), KviColorWindow::paintEvent(), KviIrcUrl::parse(), KviServerParser::parseChannelMode(), KviServerParser::parseCtcpReplyLagcheck(), KviServerParser::parseCtcpRequestAction(), KviServerParser::parseCtcpRequestClientinfo(), KviServerParser::parseCtcpRequestDcc(), KviServerParser::parseCtcpRequestFinger(), KviServerParser::parseCtcpRequestPage(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), KviServerParser::parseLiteralQuit(), KviServerParser::parseMessage(), KviServerParser::parseNumeric004(), KviServerParser::parseNumeric005(), KviServerParser::parseNumericNames(), KviServerParser::parseNumericWhoReply(), KviConnectToServerAction::popupActivated(), KviHttpRequest::processData(), KviHttpRequest::processHeader(), KviIrcSocket::proxyHandleHttpFinalReply(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), KviConfig::readKviStrEntry(), KviModuleExtensionManager::registerExtension(), KviHttpRequestThread::runInternal(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviIrcMessage::safeTrailing(), KviStatusBar::save(), KviInputHistory::save(), KviFile::save(), KviProxyDataBase::save(), KviMediaManager::save(), KviConfig::save(), KviStatusBarUpdateIndicator::saveState(), KviStatusBarConnectionTimer::saveState(), KviStatusBarClock::saveState(), KviStatusBarAwayIndicator::saveState(), KviConfig::setFontProperties(), KviFile::skipFirst(), splitToArray(), KviHttpRequestThread::sslFailure(), KviLagMeter::timerEvent(), KviRequestQueue::timerSlot(), KviIrcContextDisplay::tipRequest(), KviDebugContext::trace(), KviIrcMessage::trailing(), KviMessageCatalogue::translate(), KviMessageCatalogue::translateToQString(), KviChannel::updateModeLabel(), KviUserListView::updateUsersLabel(), KviQString::vsprintf(), KviConfig::writeEntry(), and KviDebugContext::~KviDebugContext().
KviStr & KviStr::replaceAll (const char c, const char * str)
References append(), cutLeft(), findFirstIdx(), kvi_fastmove(), kvi_realloc, left(), m_len, and m_ptr.
Referenced by KviLocale::codecForName(), and parseArgs().
KviStr & KviStr::replaceAll (const char * toFind, const char * str, bool bCaseS = true)
References append(), cutLeft(), findFirstIdx(), kvi_fastmove(), kvi_realloc, left(), len(), m_len, and m_ptr.
KviStr KviStr::right (int maxLen) const
References m_len, and m_ptr.
Referenced by parseArgs(), stripRight(), stripRightWhiteSpace(), stripSpace(), and trimmed().
KviStr & KviStr::setLen (int len)
References KVI_ASSERT, kvi_realloc, len(), m_len, and m_ptr.
Referenced by joinFromArray().
void KviStr::setLength (int iLen)
References KVI_ASSERT, kvi_realloc, m_len, and m_ptr.
Referenced by KviFile::load().
KviStr & KviStr::setNum (unsigned long num)
References kvi_realloc, m_len, and m_ptr.
KviStr& KviStr::setNum (unsigned int num) [inline]
References setNum().
Referenced by setNum().
KviStr& KviStr::setNum (unsigned short num) [inline]
References setNum().
Referenced by setNum().
KviStr& KviStr::setNum (int num) [inline]
References setNum().
Referenced by setNum().
KviStr & KviStr::setNum (long num)
References kvi_realloc, m_len, and m_ptr.
KviStr& KviStr::setNum (unsigned char num) [inline]
References setNum().
Referenced by setNum().
KviStr& KviStr::setNum (short num) [inline]
References setNum().
Referenced by setNum().
KviStr& KviStr::setNum (char num) [inline]
References setNum().
Referenced by setNum().
KviStr & KviStr::setStr (const char * str, int len = -1)
References clear(), kvi_memmove(), kvi_realloc, len(), m_len, and m_ptr.
KviStr ** KviStr::splitToArray (char sep, int max, int * realCount) const
References kvi_malloc, kvi_realloc, KviStr(), m_ptr, and ptr().
Referenced by KviCommandFormatter::unindent().
KviStr & KviStr::sprintf (const char * fmt, ...)
References kvi_realloc, kvi_va_end, kvi_va_list, kvi_va_start, kvi_vsnprintf(), m_len, and m_ptr.
Referenced by KviInputHistory::load(), KviProxyDataBase::load(), KviMediaManager::load(), KviInputHistory::save(), KviProxyDataBase::save(), KviMediaManager::save(), KviRequestQueue::timerSlot(), and KviUserListView::updateUsersLabel().
KviStr & KviStr::stripLeft (char c)
References KVI_ASSERT, kvi_memmove(), kvi_realloc, m_len, and m_ptr.
KviStr & KviStr::stripLeftWhiteSpace ()
References kvi_memmove(), kvi_realloc, m_len, and m_ptr.
Referenced by KviConfig::readColorEntry(), and KviConfig::readFontEntry().
KviStr & KviStr::stripRight (char c)
References kvi_realloc, m_len, m_ptr, and right().
Referenced by KviHttpRequest::emitLines().
KviStr & KviStr::stripRightWhiteSpace ()
References kvi_realloc, m_len, m_ptr, and right().
Referenced by KviConfig::load().
KviStr & KviStr::stripSpace ()
References kvi_memmove(), kvi_realloc, left(), m_len, m_ptr, and right().
char KviStr::toChar (bool * bOk = 0) const [inline]
int KviStr::toInt (bool * bOk = 0) const [inline]
Referenced by KviIconWidget::eventFilter(), KviStringConversion::fromString(), KviParameterList::getInt(), KviParameterList::getPoint(), KviParameterList::getRect(), KviParameterList::getSize(), KviServerParser::parseNumericWhoReply(), and KviConfig::readColorEntry().
long KviStr::toLong (bool * bOk = 0) const
References m_ptr.
long KviStr::toLongExt (bool * bOk = 0, int base = 0)
References m_len, and m_ptr.
long long KviStr::toLongLong (bool * bOk = 0) const
References m_ptr.
void KviStr::toLower ()
References m_ptr.
Referenced by KviLocale::findCatalogue(), KviLocale::init(), and lower().
void KviStr::toLowerISO88591 ()
References iso88591_toLower_map, and m_ptr.
Referenced by lowerISO88591().
short KviStr::toShort (bool * bOk = 0) const [inline]
unsigned char KviStr::toUChar (bool * bOk = 0) const [inline]
unsigned int KviStr::toUInt (bool * bOk = 0) const [inline]
Referenced by KviUIntSelector::commit(), getDateTimeStringFromCharTimeT(), KviParameterList::getUInt(), KviIrcUrl::parse(), KviServerParser::parseCtcpReplyPing(), KviServerParser::parseNumericCreationTime(), KviServerParser::parseNumericTopicWhoTime(), KviServerParser::parseNumericWhoisIdle(), and KviHttpRequest::processHeader().
unsigned long KviStr::toULong (bool * bOk = 0) const
References m_ptr.
unsigned long long KviStr::toULongLong (bool * bOk = 0) const
References m_ptr.
void KviStr::toUpper ()
References m_ptr.
Referenced by KviIrcMessage::KviIrcMessage(), KviServerParser::parseCtcpRequestClientinfo(), and upper().
void KviStr::toUpperISO88591 ()
References iso88591_toUpper_map, and m_ptr.
Referenced by upperISO88591().
unsigned short KviStr::toUShort (bool * bOk = 0) const [inline]
Referenced by KviInputEditor::keyReleaseEvent().
KviStr & KviStr::transliterate (const char * szToFind, const char * szReplacement)
References m_ptr.
KviStr & KviStr::trimmed ()
References kvi_memmove(), kvi_realloc, left(), m_len, m_ptr, and right().
Referenced by KviCommandFormatter::hasLeadingChars(), KviLocale::init(), KviMessageCatalogue::load(), KviServerParser::parseCtcpRequestClientinfo(), KviHttpRequest::processHeader(), and KviIrcSocket::proxyHandleHttpFinalReply().
KviStr KviStr::upper () const
References toUpper().
KviStr KviStr::upperISO88591 () const
References toUpperISO88591().
KviStr & KviStr::vsprintf (const char * fmt, kvi_va_list list)
References kvi_realloc, kvi_va_copy, kvi_va_list, kvi_vsnprintf(), m_len, m_ptr, and KviTheme::save().
Referenced by KviDebugContext::KviDebugContext(), and KviDebugContext::trace().
Member Data Documentation
int KviStr::m_len
Referenced by append(), base64ToBuffer(), bufferToBase64(), bufferToHex(), clear(), cut(), cutFromFirst(), cutFromLast(), cutLeft(), cutRight(), equalsCI(), equalsCS(), extractFromString(), find(), findLastIdx(), findRev(), getLine(), getToken(), hexDecode(), hexEncodeWithTable(), hexToBuffer(), insert(), kvi_extractToken(), kvi_extractUpTo(), KviStr(), left(), middle(), operator=(), operator==(), prepend(), replaceAll(), right(), setLen(), setLength(), setNum(), setStr(), sprintf(), stripLeft(), stripLeftWhiteSpace(), stripRight(), stripRightWhiteSpace(), stripSpace(), toLongExt(), trimmed(), and vsprintf().
char* KviStr::m_ptr
Referenced by append(), base64ToBuffer(), bufferToBase64(), bufferToHex(), clear(), contains(), cut(), cutLeft(), cutRight(), equalsCI(), equalsCS(), extractFromString(), find(), findFirstIdx(), findLastIdx(), findRev(), getLine(), getToken(), hasNonWhiteSpaceData(), hexDecode(), hexEncodeWithTable(), hexToBuffer(), insert(), isNum(), isUnsignedNum(), kvi_extractToken(), kvi_extractUpTo(), KviStr(), left(), leftToFirst(), leftToLast(), middle(), occurences(), operator!=(), operator=(), operator==(), prepend(), replaceAll(), right(), setLen(), setLength(), setNum(), setStr(), splitToArray(), sprintf(), stripLeft(), stripLeftWhiteSpace(), stripRight(), stripRightWhiteSpace(), stripSpace(), toLong(), toLongExt(), toLongLong(), toLower(), toLowerISO88591(), toULong(), toULongLong(), toUpper(), toUpperISO88591(), transliterate(), trimmed(), vsprintf(), and ~KviStr().
The documentation for this class was generated from the following files:
src/kvilib/core/kvi_string.h
src/kvilib/core/kvi_string.cpp