KVIrc: ClassEditorTreeWidget Class Reference
ClassEditorTreeWidget Class Reference
Describes the tree widget hierarchy.
#include <ClassEditorWindow.h>
Signals
void rightButtonPressed (QTreeWidgetItem *pItem, QPoint pos)
Emitted when we press the mouse right button.
Public Member Functions
ClassEditorTreeWidget (QWidget *pParent)
Construct the tree widget.
~ClassEditorTreeWidget ()
Destroys the tree widget.
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *e)
Detailed Description
Describes the tree widget hierarchy.
Constructor & Destructor Documentation
ClassEditorTreeWidget::ClassEditorTreeWidget (QWidget * pParent)
Construct the tree widget.
Parameters:
pParent The parent widget
Returns:
ClassEditorTreeWidget
References __tr2qs_ctx().
ClassEditorTreeWidget::~ClassEditorTreeWidget ()
Destroys the tree widget.
References clear().
Member Function Documentation
void ClassEditorTreeWidget::mousePressEvent (QMouseEvent * e) [protected, virtual]
References rightButtonPressed().
void ClassEditorTreeWidget::rightButtonPressed (QTreeWidgetItem * pItem, QPoint pos) [signal]
Emitted when we press the mouse right button.
Parameters:
pItem The item clicked
pos The position of the cursor
Returns:
void
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
src/modules/classeditor/ClassEditorWindow.h
src/modules/classeditor/ClassEditorWindow.cpp