KVIrc: KviTalToolTip Class Reference
KviTalToolTip Class Reference
#include <KviTalToolTip.h>
Public Member Functions
KviTalToolTip (QWidget *pParent)
virtual void tip (const QRect &rect, const QString &text)
virtual ~KviTalToolTip ()
Static Public Member Functions
static void add (QWidget *widget, const QString &text)
static void remove (QWidget *widget)
Protected Member Functions
void helperDying ()
virtual void maybeTip (const QPoint &p)
Protected Attributes
KviTalToolTipHelper * m_pHelper
QWidget * m_pParent
Friends
class KviTalToolTipHelper
Constructor & Destructor Documentation
KviTalToolTip::KviTalToolTip (QWidget * pParent)
References KviTalToolTipHelper, m_pHelper, and m_pParent.
KviTalToolTip::~KviTalToolTip () virtual
References m_pHelper, and KviTalToolTipHelper::toolTipDying().
Member Function Documentation
void KviTalToolTip::add (QWidget * widget, const QString & text) static
Referenced by KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addDirectorySelector(), KviOptionsWidget::addFileSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addMircTextColorSelector(), AddonManagementDialog::AddonManagementDialog(), KviOptionsWidget::addPasswordSelector(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::addSoundSelector(), KviOptionsWidget::addStringListSelector(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), KviInput::applyOptions(), KviWindow::createToolButton(), IdentityProfileEditor::IdentityProfileEditor(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviChannelWindow::KviChannelWindow(), KviConsoleWindow::KviConsoleWindow(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), KviInput::KviInput(), KviIrcView::KviIrcView(), KviUserListView::KviUserListView(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreSimpleCommands::KVSCSC(), ListWindow::ListWindow(), KviOptionsWidget::mergeTip(), NickServRuleEditor::NickServRuleEditor(), OptionsDialog::OptionsDialog(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), OptionsWidget_nickServ::OptionsWidget_nickServ(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_theme::OptionsWidget_theme(), KviTopicWidget::reset(), OptionsWidgetContainer::setup(), KviTopicWidget::switchMode(), TrashcanLabel::TrashcanLabel(), KviQueryWindow::updateLabelText(), KviChannelWindow::updateModeLabel(), and KviTopicWidget::updateToolTip().
void KviTalToolTip::helperDying () protected
References m_pHelper.
Referenced by KviTalToolTipHelper::~KviTalToolTipHelper().
void KviTalToolTip::maybeTip (const QPoint & p) protected virtual
Reimplemented in KviUserListToolTip, KviIrcViewToolTip, and KviDynamicToolTipHelper.
Referenced by KviTalToolTipHelper::eventFilter().
void KviTalToolTip::remove (QWidget * widget) static
Referenced by KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreSimpleCommands::KVSCSC(), KviTopicWidget::reset(), KviChannelWindow::updateModeLabel(), and KviTopicWidget::updateToolTip().
void KviTalToolTip::tip (const QRect & rect, const QString & text) virtual
References m_pParent.
Referenced by KviIrcViewToolTip::doTip(), KviUserListToolTip::doTip(), and KviDynamicToolTip::tip().
Friends And Related Function Documentation
friend class KviTalToolTipHelper friend
Referenced by KviTalToolTip().
Member Data Documentation
KviTalToolTipHelper* KviTalToolTip::m_pHelper protected
Referenced by helperDying(), KviTalToolTip(), and ~KviTalToolTip().
QWidget* KviTalToolTip::m_pParent protected
Referenced by KviTalToolTip(), and tip().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalToolTip.h
src/kvilib/tal/KviTalToolTip.cpp