KVIrc: RegisteredUserPropertiesDialog Class Reference
RegisteredUserPropertiesDialog Class Reference
#include <RegisteredUserEntryDialog.h>
Public Member Functions
RegisteredUserPropertiesDialog (QWidget *p, KviPointerHashTable< QString, QString > *dict)
~RegisteredUserPropertiesDialog ()
Protected Slots
void addClicked ()
void delClicked ()
void okClicked ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
void fillData ()
Protected Attributes
QPushButton * m_pAddButton
QPushButton * m_pDelButton
KviPointerHashTable< QString,
QString > * m_pPropertyDict
QTableWidget * m_pTable
Constructor & Destructor Documentation
RegisteredUserPropertiesDialog::RegisteredUserPropertiesDialog (QWidget * p, KviPointerHashTable< QString, QString > * dict)
References __tr2qs_ctx(), KviIconManager::Accept, addClicked(), connect(), delClicked(), KviIconManager::DeleteItem, KviIconManager::Discard, fillData(), g, g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Linux, m_pAddButton, m_pDelButton, m_pPropertyDict, m_pTable, KviIconManager::NewItem, okClicked(), KviTalHBox::setSpacing(), and KviTalVBox::setSpacing().
RegisteredUserPropertiesDialog::~RegisteredUserPropertiesDialog ()
Member Function Documentation
void RegisteredUserPropertiesDialog::addClicked () [protected, slot]
References m_pDelButton, and m_pTable.
Referenced by RegisteredUserPropertiesDialog().
void RegisteredUserPropertiesDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void RegisteredUserPropertiesDialog::delClicked () [protected, slot]
References i, m_pDelButton, and m_pTable.
Referenced by RegisteredUserPropertiesDialog().
void RegisteredUserPropertiesDialog::fillData () [protected]
References KviPointerHashTable< Key, T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pDelButton, m_pPropertyDict, and m_pTable.
Referenced by RegisteredUserPropertiesDialog().
void RegisteredUserPropertiesDialog::okClicked () [protected, slot]
References KviPointerHashTable< Key, T >::clear(), i, m_pPropertyDict, m_pTable, n, and KviPointerHashTable< Key, T >::replace().
Referenced by RegisteredUserPropertiesDialog().
Member Data Documentation
QPushButton* RegisteredUserPropertiesDialog::m_pAddButton [protected]
Referenced by RegisteredUserPropertiesDialog().
QPushButton* RegisteredUserPropertiesDialog::m_pDelButton [protected]
Referenced by addClicked(), delClicked(), fillData(), and RegisteredUserPropertiesDialog().
KviPointerHashTable<QString,QString>* RegisteredUserPropertiesDialog::m_pPropertyDict [protected]
Referenced by fillData(), okClicked(), and RegisteredUserPropertiesDialog().
QTableWidget* RegisteredUserPropertiesDialog::m_pTable [protected]
Referenced by addClicked(), delClicked(), fillData(), okClicked(), and RegisteredUserPropertiesDialog().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUserEntryDialog.h
src/modules/reguser/RegisteredUserEntryDialog.cpp