KVIrc: ChannelTreeWidgetItem Class Reference
ChannelTreeWidgetItem Class Reference
#include <ListWindow.h>
Public Member Functions
ChannelTreeWidgetItem (QTreeWidget *pWidget, ChannelTreeWidgetItemData *pData)
ChannelTreeWidgetItemData * itemData ()
bool operator< (const QTreeWidgetItem &other) const
int width (const QFontMetrics &fm, const QTreeWidget *pWidget, int iColumn) const
~ChannelTreeWidgetItem ()
Private Attributes
ChannelTreeWidgetItemData * m_pData
Friends
class ListWindow
Constructor & Destructor Documentation
ChannelTreeWidgetItem::ChannelTreeWidgetItem (QTreeWidget * pWidget, ChannelTreeWidgetItemData * pData)
References KviHtmlGenerator::convertToHtml(), m_pData, ChannelTreeWidgetItemData::m_szChan, ChannelTreeWidgetItemData::m_szTopic, and ChannelTreeWidgetItemData::m_szUsers.
ChannelTreeWidgetItem::~ChannelTreeWidgetItem ()
Member Function Documentation
ChannelTreeWidgetItemData* ChannelTreeWidgetItem::itemData () [inline]
References m_pData.
Referenced by ListWindow::exportList(), ListWindow::liveSearch(), and ChannelTreeWidgetItemDelegate::paint().
bool ChannelTreeWidgetItem::operator< (const QTreeWidgetItem & other) const
References m_pData, ChannelTreeWidgetItemData::m_szChan, ChannelTreeWidgetItemData::m_szTopic, ChannelTreeWidgetItemData::m_szUsers, and KviMircCntrl::stripControlBytes().
int ChannelTreeWidgetItem::width (const QFontMetrics & fm, const QTreeWidget * pWidget, int iColumn) const
References m_pData, ChannelTreeWidgetItemData::m_szChan, ChannelTreeWidgetItemData::m_szTopic, ChannelTreeWidgetItemData::m_szUsers, and KviMircCntrl::stripControlBytes().
Friends And Related Function Documentation
friend class ListWindow [friend]
Member Data Documentation
ChannelTreeWidgetItemData* ChannelTreeWidgetItem::m_pData [private]
Referenced by ChannelTreeWidgetItem(), itemData(), operator<(), and width().
The documentation for this class was generated from the following files:
src/modules/list/ListWindow.h
src/modules/list/ListWindow.cpp