KVIrc: KviChannelListSelector Class Reference
KviChannelListSelector Class Reference
#include <kvi_selectors.h>
Public Member Functions
virtual void commit ()
KviChannelListSelector (QWidget *par, const QString &txt, QStringList *pOption, bool bEnabled)
virtual void setEnabled (bool bEnabled)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviChannelListSelector ()
Private Slots
void addClicked ()
void itemSelectionChanged ()
void removeClicked ()
void textChanged (const QString &str)
Private Attributes
QPushButton * m_pAddButton
QLineEdit * m_pChanLineEdit
QLabel * m_pLabel
QStringList * m_pOption
QLineEdit * m_pPassLineEdit
QPushButton * m_pRemoveButton
QTreeWidget * m_pTreeWidget
Constructor & Destructor Documentation
KviChannelListSelector::KviChannelListSelector (QWidget * par, const QString & txt, QStringList * pOption, bool bEnabled)
References __tr2qs, addClicked(), itemSelectionChanged(), m_pAddButton, m_pChanLineEdit, m_pLabel, m_pOption, m_pPassLineEdit, m_pRemoveButton, m_pTreeWidget, removeClicked(), setEnabled(), KviTalVBox::setSpacing(), KviTalVBox::setStretchFactor(), and textChanged().
KviChannelListSelector::~KviChannelListSelector ()
Member Function Documentation
void KviChannelListSelector::addClicked () [private, slot]
References m_pChanLineEdit, m_pPassLineEdit, and m_pTreeWidget.
Referenced by KviChannelListSelector().
void KviChannelListSelector::commit () [virtual]
Reimplemented from KviSelectorInterface.
References m_pOption, m_pTreeWidget, and KviChanTreeViewItem::pass().
void KviChannelListSelector::itemSelectionChanged () [private, slot]
Referenced by KviChannelListSelector().
void KviChannelListSelector::removeClicked () [private, slot]
References KviPointerList< T >::append(), KviPointerList< T >::clear(), m_pTreeWidget, and KviPointerList< T >::setAutoDelete().
Referenced by KviChannelListSelector().
void KviChannelListSelector::setEnabled (bool bEnabled) [virtual]
References m_pAddButton, m_pChanLineEdit, m_pLabel, m_pPassLineEdit, m_pRemoveButton, and m_pTreeWidget.
Referenced by KviChannelListSelector().
void KviChannelListSelector::textChanged (const QString & str) [private, slot]
References m_pAddButton, and m_pChanLineEdit.
Referenced by KviChannelListSelector().
QString KviChannelListSelector::textForSearch () [inline, virtual]
Reimplemented from KviSelectorInterface.
QWidget* KviChannelListSelector::widgetToHighlight () [inline, virtual]
Reimplemented from KviSelectorInterface.
Member Data Documentation
QPushButton* KviChannelListSelector::m_pAddButton [private]
Referenced by KviChannelListSelector(), setEnabled(), and textChanged().
QLineEdit* KviChannelListSelector::m_pChanLineEdit [private]
Referenced by addClicked(), KviChannelListSelector(), setEnabled(), and textChanged().
QLabel* KviChannelListSelector::m_pLabel [private]
Referenced by KviChannelListSelector(), and setEnabled().
QStringList* KviChannelListSelector::m_pOption [private]
Referenced by commit(), and KviChannelListSelector().
QLineEdit* KviChannelListSelector::m_pPassLineEdit [private]
Referenced by addClicked(), KviChannelListSelector(), and setEnabled().
QPushButton* KviChannelListSelector::m_pRemoveButton [private]
Referenced by KviChannelListSelector(), and setEnabled().
QTreeWidget* KviChannelListSelector::m_pTreeWidget [private]
Referenced by addClicked(), commit(), KviChannelListSelector(), removeClicked(), and setEnabled().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_selectors.h
src/kvirc/ui/kvi_selectors.cpp