KVIrc: KviServer Class Reference
KviServer Class Reference
The class which manages the irc servers.
#include <kvi_ircserver.h>
Public Member Functions
bool autoConnect () const
Returns true if the server is in autoconnect mode.
QStringList * autoJoinChannelList ()
Returns the list of the channels in the autojoin list.
bool cacheIp () const
Returns true if the server caches the IP.
const QString & description () const
Returns the description of the server.
bool enabledCAP () const
Returns true if the CAP protocol is enabled for this server.
bool enabledSASL () const
Returns true if the SASL protocol is enabled for this server.
bool enabledSTARTTLS () const
Returns true if the STARTTLS protocol is enabled for this server.
const QString & encoding () const
Returns the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server.
void generateUniqueId ()
Generates an unique id for the server and sets it.
const QString & hostName () const
Returns the hostname of the user associated to the server.
const QString & id () const
Returns the id of the server.
const QString & initUMode () const
Returns the user modes of the user associated to the server.
const QString & ip () const
Returns the IP address of the server.
QString ircUri ()
Returns the irc URI for the server The URI is in the form irc[[s]6]://name.serverhost.tld.
bool isIPv6 () const
Returns true if the server uses IPv6.
KviServer (const KviServer &serv)
Carbon copy.
KviServer ()
Constructs the server object.
const QString & linkFilter () const
bool load (KviConfig *cfg, const QString &szPrefix)
Loads the information from the configuration file.
const QString & nickName () const
Returns the nickname of the user associated to the server.
const QString & onConnectCommand () const
Returns the commands to run on server connection.
const QString & onLoginCommand () const
Returns the commands to run on server login.
void operator= (const KviServer &s)
Carbon copy.
const QString & password () const
Returns the password of the user associated to the server.
kvi_u32_t port () const
Returns the port number.
int proxy ()
Returns the proxy server's id.
KviProxy * proxyServer (KviProxyDataBase *pDb)
Returns the proxy server.
const QString & realName () const
Returns the realname of the user associated to the server.
const QString & saslNick () const
Returns the nickname used for sasl auth.
const QString & saslPass () const
Returns the password used for sasl auth.
void save (KviConfig *cfg, const QString &szPrefix)
Saves the information to the configuration file.
void setAutoConnect (bool bAutoConnect)
Sets the autoconnection mode for the server.
void setAutoJoinChannelList (QStringList *pNewChannelList)
Sets the list of channels to autojoin after connection The channel list must be allocated with a new!
void setCacheIp (bool bSet)
Sets if the server caches the IP.
void setDescription (const QString &szDesc)
Sets the description for the server.
void setEnabledCAP (bool bSet)
Sets if CAP support is enabled/disabled for this server.
void setEnabledSASL (bool bSet)
Sets if SASL support is enabled/disabled for this server.
void setEnabledSTARTTLS (bool bSet)
Sets if STARTTLS support is enabled/disabled for this server.
void setEncoding (const QString &szEncoding)
Sets the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server This is the default encoding when talking on channels or queries.
void setHostName (const QString &szHost)
Sets the hostname for the server.
void setId (const QString &szId)
Sets an unique id for the server.
void setInitUMode (const QString &szUMode)
Sets the user modes of the user associated to the server.
void setIp (const QString &szIp)
Sets the IP for the server.
void setIPv6 (bool bSet)
Sets if the server uses IPv6.
void setLinkFilter (const QString &szFilter)
void setNickName (const QString &szNick)
Sets the nickname of the user associated to the server.
void setOnConnectCommand (const QString &szCmd)
Sets the commands to run on server connection.
void setOnLoginCommand (const QString &szCmd)
Sets the commands to run on server login.
void setPassword (const QString &szPass)
Sets the password of the user associated to the server.
void setPort (kvi_u32_t uPort)
Sets the port for the server.
void setProxy (int iProxy)
Sets the proxy server for the server.
void setRealName (const QString &szReal)
Sets the realname of the user associated to the server.
void setSaslNick (const QString &szNick)
Sets the nickname used for sasl auth.
void setSaslPass (const QString &szPass)
Sets the password used for sasl auth.
void setTextEncoding (const QString &szEncoding)
Sets the encoding associated to the server This is the default encoding when talking on channels or queries.
void setUserIdentityId (const QString &szUserIdentityId)
Sets the id of the user associated to the server.
void setUserName (const QString &szUser)
Sets the username of the user associated to the server.
void setUseSSL (bool bSet)
Sets if the server uses SSL.
const QString & textEncoding () const
Returns the text encoding associated to the server This is the default encoding when talking on channels or queries.
const QString & userIdentityId () const
Returns the id of the user associated to the server.
const QString & userName () const
Returns the username of the user associated to the server.
bool useSSL () const
Returns true if the server uses SSL.
~KviServer ()
Destroys the server object.
Public Attributes
bool m_bAutoConnect
int m_iProxy
QStringList * m_pAutoJoinChannelList
KviServerReconnectInfo * m_pReconnectInfo
QString m_szDescription
QString m_szEncoding
QString m_szHostname
QString m_szId
QString m_szInitUMode
QString m_szIp
QString m_szLinkFilter
QString m_szNick
QString m_szOnConnectCommand
QString m_szOnLoginCommand
QString m_szPass
QString m_szRealName
QString m_szSaslNick
QString m_szSaslPass
QString m_szTextEncoding
QString m_szUser
QString m_szUserIdentityId
unsigned short int m_uFlags
kvi_u32_t m_uPort
Detailed Description
The class which manages the irc servers.
Constructor & Destructor Documentation
KviServer::KviServer ()
Constructs the server object.
Returns:
KviServer
References m_bAutoConnect, m_iProxy, m_pAutoJoinChannelList, m_pReconnectInfo, m_uFlags, and m_uPort.
KviServer::KviServer (const KviServer & serv)
Carbon copy.
Parameters:
serv The irc server
Returns:
KviServer
References m_bAutoConnect, m_iProxy, m_pAutoJoinChannelList, m_pReconnectInfo, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uFlags, and m_uPort.
KviServer::~KviServer ()
Destroys the server object.
References m_pAutoJoinChannelList, and m_pReconnectInfo.
Member Function Documentation
bool KviServer::autoConnect () const [inline]
Returns true if the server is in autoconnect mode.
Returns:
bool
Referenced by KviServerDataBase::load(), and save().
QStringList* KviServer::autoJoinChannelList () [inline]
Returns the list of the channels in the autojoin list.
Returns:
QStringList *
Referenced by KviIrcConnection::loginComplete(), and save().
bool KviServer::cacheIp () const [inline]
Returns true if the server caches the IP.
Returns:
bool
References KVI_IRCSERVER_FLAG_CACHEIP.
Referenced by KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcSocket::proxySendTargetDataV5(), and save().
const QString& KviServer::description () const [inline]
Returns the description of the server.
Returns:
const QString &
bool KviServer::enabledCAP () const [inline]
Returns true if the CAP protocol is enabled for this server.
Returns:
bool
References KVI_IRCSERVER_FLAG_CAP.
Referenced by save().
bool KviServer::enabledSASL () const [inline]
Returns true if the SASL protocol is enabled for this server.
Returns:
bool
References KVI_IRCSERVER_FLAG_SASL.
Referenced by save().
bool KviServer::enabledSTARTTLS () const [inline]
Returns true if the STARTTLS protocol is enabled for this server.
Returns:
bool
References KVI_IRCSERVER_FLAG_STARTTLS.
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), and save().
const QString& KviServer::encoding () const [inline]
Returns the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server.
Returns:
const QString &
Referenced by KviIrcConnection::setupSrvCodec().
void KviServer::generateUniqueId ()
Generates an unique id for the server and sets it.
Returns:
void
References kvi_gettimeofday(), m_szId, and KviQString::sprintf().
Referenced by load().
const QString& KviServer::hostName () const [inline]
Returns the hostname of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionTerminated(), KviIrcUrl::join(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxySendTargetDataV5(), and KviIrcUrl::run().
const QString& KviServer::id () const [inline]
Returns the id of the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), and KviIrcContext::connectToCurrentServer().
const QString& KviServer::initUMode () const [inline]
Returns the user modes of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcConnection::loginComplete().
const QString& KviServer::ip () const [inline]
Returns the IP address of the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionTerminated(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), and KviIrcSocket::startConnection().
QString KviServer::ircUri ()
Returns the irc URI for the server The URI is in the form irc[[s]6]://name.serverhost.tld.
Returns:
QString
References isIPv6(), m_szHostname, m_uPort, and useSSL().
bool KviServer::isIPv6 () const [inline]
Returns true if the server uses IPv6.
Returns:
bool
References KVI_IRCSERVER_FLAG_IPV6.
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviNetwork::findServer(), KviIrcConnectionTargetResolver::haveServerIp(), ircUri(), KviConsole::isIPv6Connection(), KviIrcUrl::join(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcSocket::proxySendTargetDataV5(), KviIrcUrl::run(), save(), KviIrcConnectionTargetResolver::serverLookupTerminated(), KviIrcSocket::startConnection(), and KviIrcConnectionTargetResolver::validateLocalAddress().
const QString& KviServer::linkFilter () const [inline]
Returns:
const QString &
Referenced by KviIrcLink::resolverTerminated().
bool KviServer::load (KviConfig * cfg, const QString & szPrefix)
Loads the information from the configuration file.
Parameters:
cfg The configuration file
szPrefix The prefix of the server
Returns:
bool
References generateUniqueId(), m_bAutoConnect, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uPort, KviConfig::readBoolEntry(), KviConfig::readIntEntry(), KviConfig::readQStringEntry(), KviConfig::readStringListEntry(), KviConfig::readUIntEntry(), setAutoJoinChannelList(), setCacheIp(), setEnabledCAP(), setEnabledSASL(), setEnabledSTARTTLS(), setIPv6(), setProxy(), setUseSSL(), and KviQString::sprintf().
Referenced by KviServerDataBase::load().
const QString& KviServer::nickName () const [inline]
Returns the nickname of the user associated to the server.
Returns:
const QString &
const QString& KviServer::onConnectCommand () const [inline]
Returns the commands to run on server connection.
Returns:
const QString &
Referenced by KviIrcConnection::loginToIrcServer().
const QString& KviServer::onLoginCommand () const [inline]
Returns the commands to run on server login.
Returns:
const QString &
Referenced by KviIrcConnection::loginComplete().
void KviServer::operator= (const KviServer & s)
Carbon copy.
Parameters:
s The server to copy
Returns:
void
References m_bAutoConnect, m_iProxy, m_pAutoJoinChannelList, m_pReconnectInfo, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uFlags, and m_uPort.
const QString& KviServer::password () const [inline]
Returns the password of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), and KviIrcContext::connectToCurrentServer().
kvi_u32_t KviServer::port () const [inline]
Returns the port number.
Returns:
kvi_u32_t
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviIrcUrl::join(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), KviIrcUrl::run(), and KviIrcSocket::startConnection().
int KviServer::proxy () [inline]
Returns the proxy server's id.
Returns:
int
Referenced by KviIrcContext::connectToCurrentServer(), proxyServer(), and save().
KviProxy * KviServer::proxyServer (KviProxyDataBase * pDb)
Returns the proxy server.
Parameters:
pDb The proxy database
Returns:
KviProxy
References KviPointerList< T >::first(), KviPointerList< T >::next(), proxy(), and KviProxyDataBase::proxyList().
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviServer::realName () const [inline]
Returns the realname of the user associated to the server.
Returns:
const QString &
const QString& KviServer::saslNick () const [inline]
Returns the nickname used for sasl auth.
Returns:
const QString &
const QString& KviServer::saslPass () const [inline]
Returns the password used for sasl auth.
Returns:
const QString &
void KviServer::save (KviConfig * cfg, const QString & szPrefix)
Saves the information to the configuration file.
Parameters:
cfg The configuration file
szPrefix The prefix of the server
Returns:
void
References autoConnect(), autoJoinChannelList(), cacheIp(), enabledCAP(), enabledSASL(), enabledSTARTTLS(), isIPv6(), m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uPort, proxy(), KviQString::sprintf(), useSSL(), and KviConfig::writeEntry().
void KviServer::setAutoConnect (bool bAutoConnect) [inline]
Sets the autoconnection mode for the server.
Parameters:
bAutoConnect Whether to set the autoconnection
Returns:
void
void KviServer::setAutoJoinChannelList (QStringList * pNewChannelList)
Sets the list of channels to autojoin after connection The channel list must be allocated with a new!
Parameters:
pNewChannelList The list of channels to autojoin
Returns:
void
References m_pAutoJoinChannelList.
Referenced by load().
void KviServer::setCacheIp (bool bSet) [inline]
Sets if the server caches the IP.
Parameters:
bSet Whether to set the cache for the IP
Returns:
void
References KVI_IRCSERVER_FLAG_CACHEIP.
Referenced by load(), and KviServerDataBase::makeCurrentServer().
void KviServer::setDescription (const QString & szDesc) [inline]
Sets the description for the server.
Parameters:
szDesc The description of the server
Returns:
void
void KviServer::setEnabledCAP (bool bSet) [inline]
Sets if CAP support is enabled/disabled for this server.
Parameters:
bSet Whether to enable the support for CAP
Returns:
void
References KVI_IRCSERVER_FLAG_CAP.
Referenced by load().
void KviServer::setEnabledSASL (bool bSet) [inline]
Sets if SASL support is enabled/disabled for this server.
Parameters:
bSet Whether to enable the support for SASL
Returns:
void
References KVI_IRCSERVER_FLAG_SASL.
Referenced by load().
void KviServer::setEnabledSTARTTLS (bool bSet) [inline]
Sets if STARTTLS support is enabled/disabled for this server.
Parameters:
bSet Whether to enable the support for STARTTLS
Returns:
void
References KVI_IRCSERVER_FLAG_STARTTLS.
Referenced by load().
void KviServer::setEncoding (const QString & szEncoding) [inline]
Sets the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server This is the default encoding when talking on channels or queries.
Parameters:
szEncoding The default encoding of the text
Returns:
void
void KviServer::setHostName (const QString & szHost) [inline]
Sets the hostname for the server.
Parameters:
szHost The host name of the user
Returns:
void
void KviServer::setId (const QString & szId) [inline]
Sets an unique id for the server.
Parameters:
szId The id of the server
Returns:
void
void KviServer::setInitUMode (const QString & szUMode) [inline]
Sets the user modes of the user associated to the server.
Parameters:
szUMode The user modes of the user
Returns:
void
void KviServer::setIp (const QString & szIp) [inline]
Sets the IP for the server.
Parameters:
szIp The IP of the server
Returns:
void
Referenced by KviIrcConnectionTargetResolver::serverLookupTerminated().
void KviServer::setIPv6 (bool bSet) [inline]
Sets if the server uses IPv6.
Parameters:
bSet Whether to set the support for IPv6
Returns:
void
References KVI_IRCSERVER_FLAG_IPV6.
Referenced by load().
void KviServer::setLinkFilter (const QString & szFilter) [inline]
Parameters:
szFilter
Returns:
void
void KviServer::setNickName (const QString & szNick) [inline]
Sets the nickname of the user associated to the server.
Parameters:
szNick The nick name of the user
Returns:
void
void KviServer::setOnConnectCommand (const QString & szCmd) [inline]
Sets the commands to run on server connection.
Parameters:
szCmd The comands to run on connection
Returns:
void
void KviServer::setOnLoginCommand (const QString & szCmd) [inline]
Sets the commands to run on server login.
Parameters:
szCmd The comands to run on login
Returns:
void
void KviServer::setPassword (const QString & szPass) [inline]
Sets the password of the user associated to the server.
Parameters:
szPass The password of the user
Returns:
void
void KviServer::setPort (kvi_u32_t uPort) [inline]
Sets the port for the server.
Parameters:
uPort The port of the server
Returns:
void
void KviServer::setProxy (int iProxy) [inline]
Sets the proxy server for the server.
Parameters:
iProxy The proxy to connect through
Returns:
void
Referenced by load().
void KviServer::setRealName (const QString & szReal) [inline]
Sets the realname of the user associated to the server.
Parameters:
szReal The real name of the user
Returns:
void
void KviServer::setSaslNick (const QString & szNick) [inline]
Sets the nickname used for sasl auth.
Parameters:
szNick The nick name of the user
Returns:
void
void KviServer::setSaslPass (const QString & szPass) [inline]
Sets the password used for sasl auth.
Parameters:
szPass The password of the user
Returns:
void
void KviServer::setTextEncoding (const QString & szEncoding) [inline]
Sets the encoding associated to the server This is the default encoding when talking on channels or queries.
Parameters:
szEncoding The default encoding of the text
Returns:
void
void KviServer::setUserIdentityId (const QString & szUserIdentityId) [inline]
Sets the id of the user associated to the server.
Parameters:
szUserIdentityId The user identity id to set
Returns:
void
void KviServer::setUserName (const QString & szUser) [inline]
Sets the username of the user associated to the server.
Parameters:
szUser The user name of the user
Returns:
void
void KviServer::setUseSSL (bool bSet) [inline]
Sets if the server uses SSL.
Parameters:
bSet Whether to set the support for SSL
Returns:
void
References KVI_IRCSERVER_FLAG_SSL.
Referenced by load().
const QString& KviServer::textEncoding () const [inline]
Returns the text encoding associated to the server This is the default encoding when talking on channels or queries.
Returns:
const QString &
Referenced by KviIrcConnection::setupTextCodec().
const QString& KviServer::userIdentityId () const [inline]
Returns the id of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviServer::userName () const [inline]
Returns the username of the user associated to the server.
Returns:
const QString &
bool KviServer::useSSL () const [inline]
Returns true if the server uses SSL.
Returns:
bool
References KVI_IRCSERVER_FLAG_SSL.
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcSocket::connectedToIrcServer(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviNetwork::findServer(), ircUri(), KviIrcUrl::join(), KviIrcUrl::run(), save(), and KviIrcSocket::startConnection().
Member Data Documentation
bool KviServer::m_bAutoConnect
Referenced by KviServer(), load(), and operator=().
int KviServer::m_iProxy
Referenced by KviServer(), and operator=().
QStringList* KviServer::m_pAutoJoinChannelList
Referenced by KviServer(), operator=(), setAutoJoinChannelList(), and ~KviServer().
KviServerReconnectInfo* KviServer::m_pReconnectInfo
Referenced by KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviServer(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), operator=(), and ~KviServer().
QString KviServer::m_szDescription
Referenced by KviServerDataBase::importFromMircIni(), KviServer(), load(), operator=(), and save().
QString KviServer::m_szEncoding
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szHostname
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviNetwork::findServer(), KviServerDataBase::importFromMircIni(), ircUri(), KviServer(), load(), KviIrcConnection::loginToIrcServer(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviServerDataBase::makeCurrentServer(), operator=(), save(), KviIrcConnectionTargetResolver::serverLookupTerminated(), and KviIrcLink::socketStateChange().
QString KviServer::m_szId
Referenced by generateUniqueId(), KviServer(), load(), operator=(), and save().
QString KviServer::m_szInitUMode
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviServer(), load(), KviServerDataBase::makeCurrentServer(), operator=(), and save().
QString KviServer::m_szIp
Referenced by KviIrcContext::connectionEstabilished(), KviServer(), load(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviServerDataBase::makeCurrentServer(), operator=(), save(), KviIrcConnectionTargetResolver::serverLookupTerminated(), and KviIrcLink::socketStateChange().
QString KviServer::m_szLinkFilter
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szNick
Referenced by KviServer(), load(), KviIrcConnection::loginToIrcServer(), KviServerDataBase::makeCurrentServer(), operator=(), and save().
QString KviServer::m_szOnConnectCommand
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szOnLoginCommand
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szPass
Referenced by KviServer(), load(), KviIrcConnection::loginToIrcServer(), KviServerDataBase::makeCurrentServer(), operator=(), and save().
QString KviServer::m_szRealName
Referenced by KviServer(), load(), KviIrcConnection::loginToIrcServer(), operator=(), and save().
QString KviServer::m_szSaslNick
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szSaslPass
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szTextEncoding
Referenced by KviServer(), load(), operator=(), and save().
QString KviServer::m_szUser
Referenced by KviServer(), load(), KviIrcConnection::loginToIrcServer(), operator=(), and save().
QString KviServer::m_szUserIdentityId
Referenced by KviServer(), load(), operator=(), and save().
unsigned short int KviServer::m_uFlags
Referenced by KviServer(), and operator=().
kvi_u32_t KviServer::m_uPort
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcContext::connectionEstabilished(), KviNetwork::findServer(), KviServerDataBase::importFromMircIni(), ircUri(), KviServer(), load(), operator=(), save(), and KviIrcLink::socketStateChange().
The documentation for this class was generated from the following files:
src/kvilib/irc/kvi_ircserver.h
src/kvilib/irc/kvi_ircserver.cpp