KVIrc: KviKvsTreeNodeStringCast Class Reference
KviKvsTreeNodeStringCast Class Reference
#include <KviKvsTreeNodeStringCase.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeStringCast (const QChar *pLocation, KviKvsTreeNodeData *pChildData)
~KviKvsTreeNodeStringCast ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeData * m_pChildData
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeStringCast::KviKvsTreeNodeStringCast (const QChar * pLocation, KviKvsTreeNodeData * pChildData)
References m_pChildData, and KviKvsTreeNode::setParent().
KviKvsTreeNodeStringCast::~KviKvsTreeNodeStringCast ()
References m_pChildData.
Member Function Documentation
void KviKvsTreeNodeStringCast::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeStringCast::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::dump(), and m_pChildData.
bool KviKvsTreeNodeStringCast::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsVariant::isString(), m_pChildData, and KviKvsVariant::setString().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeStringCast::m_pChildData protected
Referenced by dump(), evaluateReadOnly(), KviKvsTreeNodeStringCast(), and ~KviKvsTreeNodeStringCast().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeStringCase.h
src/kvirc/kvs/tree/KviKvsTreeNodeStringCase.cpp