KVIrc: KviQueryWindow Class Reference
KviQueryWindow Class Reference
The class which manages a query.
#include <KviQueryWindow.h>
Public Types
enum Flag { Dead = 1 }
Holds the flags of a query.
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Member Functions
virtual void applyOptions ()
Applies the options.
bool avatarChanged (const QString &szNick)
Called when the target changes the avatar.
QFrame * buttonContainer ()
Returns the button container.
bool isDeadQuery ()
Returns true if the query is dead.
KviQueryWindow (KviConsoleWindow *lpConsole, const QString &szNick)
Constructs the query object.
QByteArray loadLogFile (const QString &szFileName, bool bGzip)
Loads a log file.
void mergeQuery (KviQueryWindow *pQuery)
Merges a query into the one we're using.
bool nickChange (const QString &szOldNick, const QString &szNewNick)
Called when the target changes the nick.
void notifyCommonChannels (const QString &szNick, const QString &szUser, const QString &szHost, int iChans, const QString &szChans)
Notify us if we have common channels with the target.
void ownAction (const QString &szBuffer)
Called when we perform an action.
void ownMessage (const QString &szBuffer, bool bUserFeedback=true)
Called when we send a message to the query target.
void pasteLastLog ()
Pastes the most recent channel log into the buffer.
int selectedCount ()
Returns the number of selected users in the userlist.
void setAliveQuery ()
Sets the status of the query as alive.
void setDeadQuery ()
Sets the status of the query as dead.
KviUserListEntry * setTarget (const QString &szNick, const QString &szUser, const QString &szHost)
Sets the target of the query.
void showListView (bool bShow, bool bIgnoreSizeChange=false)
Shows the userlist view.
virtual QSize sizeHint () const
Returns the size of the query object.
virtual const QString & target ()
Returns the name of the query target.
void updateLabelText ()
Updates the text of the tooltip.
void userAction (KviIrcMask *user, unsigned int uActionType)
Called when a user performs an action.
void userAction (const QString &szNick, unsigned int uActionType)
Called when a user performs an action.
void userAction (const QString &szNick, const QString &szUser, const QString &szHost, unsigned int uActionType)
Called when a user performs an action.
KviUserListView * userListView ()
Returns the userlist of the query (the remote peer)
~KviQueryWindow ()
Destroys the query object.
Public Member Functions inherited from KviWindow
void activateSelf ()
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Protected Slots
void slotDndEvents (const QString &szFile)
Triggers the OnQueryFileDropped event.
void textViewRightClicked ()
Triggers the OnQueryPopupRequest event.
void toggleListView ()
Toggles the userlist view.
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual void fillCaptionBuffers ()
Fills in the caption buffers.
virtual void getBaseLogFileName (QString &szBuffer)
Gets the base of the log file name.
QString getInfoLabelText ()
Gets the info of the text in the upper part of the query.
virtual void getWindowListTipText (QString &szBuffer)
Gets the window list and info label tooltip text.
virtual void loadProperties (KviConfigurationFile *pCfg)
Loads the properties from file.
virtual QPixmap * myIconPtr ()
Returns the icon associated to the query.
void notifyTargetChange (const QString &szOldNick, const QString &szOldUser, const QString &szOldHost, const QString &szNick, const QString &szUser, const QString &szHost)
Called to notify us that the target of the query is changed.
virtual void resizeEvent (QResizeEvent *)
virtual void saveProperties (KviConfigurationFile *pCfg)
Saves the properties to file.
virtual void triggerCreationEvents ()
Trigger the OnQueryWindowCreated event.
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
virtual void closeEvent (QCloseEvent *pEvent)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual void preprocessMessage (QString &szMessage)
void setType (Type eType)
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
int m_iFlags
QFrame * m_pButtonGrid
KviThemedLabel * m_pLabel
KviWindowToolPageButton * m_pListViewButton
KviUserListView * m_pUserListView
QList< int > m_SplitterSizesList
Protected Attributes inherited from KviWindow
bool m_bIsDocked
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Additional Inherited Members
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void maximize ()
void minimize ()
void reloadImages ()
void restore ()
void savePropertiesAsDefault ()
void undock ()
Signals inherited from KviWindow
void windowNameChanged ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Detailed Description
The class which manages a query.
Member Enumeration Documentation
enum KviQueryWindow::Flag
Holds the flags of a query.
Enumerator:
Dead
Constructor & Destructor Documentation
KviQueryWindow::KviQueryWindow (KviConsoleWindow * lpConsole, const QString & szNick)
Constructs the query object.
Parameters:
lpConsole The associated console
szNick The nickname with who we open a query
Returns:
KviQueryWindow
References __tr2qs, buttonContainer(), connect(), KviWindow::connection(), KviWindow::createCryptControllerButton(), KviWindow::createTextEncodingButton(), KviIrcView::enableDnd(), KviIconManager::HideListView, KVI_OPTION_BOOL, KviWindow::KviInput, KviOption_boolAutoLogQueries, KviTalSplitter, m_iFlags, KviWindow::m_pButtonBox, m_pButtonGrid, KviWindow::m_pInput, KviWindow::m_pIrcView, m_pLabel, m_pListViewButton, KviWindow::m_pSplitter, m_pUserListView, KviIrcConnection::registerQuery(), KviTalHBox::setStretchFactor(), KviIconManager::ShowListView, slotDndEvents(), KviIrcView::startLogging(), textViewRightClicked(), toggleListView(), KviWindow::updateCaption(), and updateLabelText().
KviQueryWindow::~KviQueryWindow ()
Destroys the query object.
References KviWindow::connection(), KviWindow::context(), KviWindow::DeadQuery, m_pUserListView, KviUserListView::partAll(), KviWindow::type(), KviIrcContext::unregisterDeadQuery(), and KviIrcConnection::unregisterQuery().
Member Function Documentation
void KviQueryWindow::applyOptions () virtual
Applies the options.
Returns:
void
Reimplemented from KviWindow.
References KviUserListView::applyOptions(), m_pUserListView, and updateLabelText().
bool KviQueryWindow::avatarChanged (const QString & szNick) inline
Called when the target changes the avatar.
Parameters:
szNick The nickname of the user
Returns:
bool
QFrame* KviQueryWindow::buttonContainer () inline virtual
Returns the button container.
Returns:
QFrame *
Reimplemented from KviWindow.
Referenced by KviQueryWindow().
void KviQueryWindow::fillCaptionBuffers () protected virtual
Fills in the caption buffers.
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), KviWindow::m_szPlainTextCaption, and KviWindow::windowName().
void KviQueryWindow::getBaseLogFileName (QString & szBuffer) protected virtual
Gets the base of the log file name.
Parameters:
szBuffer The buffer where to save the info
Returns:
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviWindow::console(), KviConsoleWindow::context(), KviWindow::context(), KviConsoleWindow::currentNetworkName(), KviIrcContext::id(), and KviWindow::windowName().
QString KviQueryWindow::getInfoLabelText () protected
Gets the info of the text in the upper part of the query.
Returns:
QString
References __tr2qs, KviWindow::connection(), KviIrcUserDataBase::find(), KviIrcConnection::getCommonChannels(), KviIrcUserEntry::hasHops(), KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasRealName(), KviIrcUserEntry::hasServer(), KviIrcUserEntry::hasUser(), KviIrcUserEntry::hops(), KviIrcUserEntry::host(), KviIrcUserEntry::isAway(), KVI_OPTION_BOOL, KviOption_boolShowExtendedInfoInQueryLabel, KviWindow::m_szName, KviIrcUserEntry::realName(), KviIrcUserEntry::server(), KviControlCodes::stripControlBytes(), KviIrcUserEntry::user(), and KviIrcConnection::userDataBase().
Referenced by updateLabelText().
void KviQueryWindow::getWindowListTipText (QString & szBuffer) protected virtual
Gets the window list and info label tooltip text.
Returns:
QString
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviWindow::console(), KviIrcUserDataBase::find(), KviConsoleWindow::getUserTipText(), KviWindow::m_szName, and KviIrcConnection::userDataBase().
Referenced by updateLabelText().
bool KviQueryWindow::isDeadQuery () inline
Returns true if the query is dead.
Returns:
bool
Referenced by myIconPtr().
QByteArray KviQueryWindow::loadLogFile (const QString & szFileName, bool bGzip)
Loads a log file.
It opens a logfile, gzipped or not, and returns the content in a buffer
Parameters:
szFileName The filename of the log file
bGzip Whether the log file is gzipped
Returns:
QByteArray
Referenced by pasteLastLog().
void KviQueryWindow::loadProperties (KviConfigurationFile * pCfg) protected virtual
Loads the properties from file.
Parameters:
pCfg The configuration file
Returns:
void
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, m_SplitterSizesList, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readIntListEntry(), and showListView().
void KviQueryWindow::mergeQuery (KviQueryWindow * pQuery)
Merges a query into the one we're using.
Parameters:
pQuery The source query
Returns:
void
References KviIrcView::appendMessagesFrom(), KviWindow::m_pIrcView, and updateLabelText().
Referenced by KviIrcServerParser::parseLiteralNick().
QPixmap * KviQueryWindow::myIconPtr () protected virtual
Returns the icon associated to the query.
Returns:
QPixmap *
Reimplemented from KviWindow.
References KviIconManager::DeadQuery, g_pIconManager, KviIconManager::getSmallIcon(), isDeadQuery(), and KviIconManager::Query.
bool KviQueryWindow::nickChange (const QString & szOldNick, const QString & szNewNick)
Called when the target changes the nick.
Parameters:
szOldNick The old nickname of the user
szNewNick The new nickname of the user
Returns:
bool
References m_pUserListView, KviUserListView::nickChange(), KviWindow::setWindowName(), KviWindow::updateCaption(), and updateLabelText().
Referenced by KviIrcServerParser::parseLiteralNick().
void KviQueryWindow::notifyCommonChannels (const QString & szNick, const QString & szUser, const QString & szHost, int iChans, const QString & szChans)
Notify us if we have common channels with the target.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
iChans The number of common channels
szChans The common channels
Returns:
void
References __tr2qs, KVI_OUT_QUERYTRACE, KviWindow::output(), szHost, and updateLabelText().
Referenced by KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralPart(), and setTarget().
void KviQueryWindow::notifyTargetChange (const QString & szOldNick, const QString & szOldUser, const QString & szOldHost, const QString & szNick, const QString & szUser, const QString & szHost) protected
Called to notify us that the target of the query is changed.
Parameters:
szOldNick The old nickname of the target
szOldUser The old username of the target
szOldHost The old hostname of the target
szNick The new nickname of the target
szUser The new username of the target
szHost The new hostname of the target
Returns:
void
References __tr2qs, KVI_OUT_QUERYTRACE, KviWindow::output(), and updateLabelText().
Referenced by userAction().
void KviQueryWindow::ownAction (const QString & szBuffer) virtual
Called when we perform an action.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviWindow::encodeText(), KVI_OPTION_BOOL, KVI_OUT_ACTION, KVI_OUT_SYSTEMWARNING, KVI_USERACTION_ACTION, KviEvent_OnMeAction, KviOption_boolStripMircColorsInUserMessages, KVS_TRIGGER_EVENT_2_HALTED, m_pUserListView, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcConnection::sendFmtData(), KviControlCodes::stripControlBytes(), szBuffer, KviUserListView::userAction(), and KviWindow::windowName().
void KviQueryWindow::ownMessage (const QString & szBuffer, bool bUserFeedback = true) virtual
Called when we send a message to the query target.
Parameters:
szBuffer The buffer where to store the data
bUserFeedback Whether to display the echo feedback to the user
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviControlCodes::CryptEscape, KviWindow::decodeText(), KviCryptEngine::Encoded, KviWindow::encodeText(), KviIrcConnection::encodeText(), KviCryptEngine::Encrypted, KviIrcConnectionUserInfo::hostName(), KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMWARNING, KVI_USERACTION_PRIVMSG, KviWindow::m_pConsole, KviWindow::makeEncoder(), KviIrcConnectionUserInfo::nickName(), KviConsoleWindow::NoNotifications, KviWindow::output(), KviWindow::outputNoFmt(), KviConsoleWindow::outputPrivmsg(), KviCString::ptr(), KviIrcConnection::sendFmtData(), userAction(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), and KviWindow::windowName().
void KviQueryWindow::pasteLastLog ()
Pastes the most recent channel log into the buffer.
It searches for the most recent channel log of the channel we have just joined, and pastes into the buffer the last N lines, where N is get from the options
Returns:
void
References __tr2qs, KviWindow::console(), KviConsoleWindow::currentNetworkName(), g_pApp, KviApplication::getLocalKvircDirectory(), i, KVI_OPTION_UINT, KVI_OUT_QUERYPRIVMSG, KviOption_uintDaysIntervalToPasteOnQueryJoin, KviOption_uintLinesToPasteOnQueryJoin, loadLogFile(), KviApplication::Log, KviWindow::output(), and target().
Referenced by KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
void KviQueryWindow::resizeEvent (QResizeEvent *) protected virtual
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, and KviWindow::m_pSplitter.
void KviQueryWindow::saveProperties (KviConfigurationFile * pCfg) protected virtual
Saves the properties to file.
Parameters:
pCfg The configuration file
Returns:
void
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, m_pUserListView, m_SplitterSizesList, and KviConfigurationFile::writeEntry().
int KviQueryWindow::selectedCount () inline
Returns the number of selected users in the userlist.
Returns:
int
void KviQueryWindow::setAliveQuery ()
Sets the status of the query as alive.
Returns:
void
References KviWindow::connection(), KviWindow::context(), Dead, KviIrcUserDataBase::find(), KviIrcUserEntry::host(), KviIrcView::isLogging(), m_iFlags, KviWindow::m_pIrcView, m_pUserListView, KviWindow::Query, KviIrcConnection::registerQuery(), setTarget(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcView::startLogging(), szHost, target(), KviIrcContext::unregisterDeadQuery(), KviWindow::updateIcon(), KviIrcUserEntry::user(), and KviIrcConnection::userDataBase().
Referenced by KviIrcConnection::createQuery().
void KviQueryWindow::setDeadQuery ()
Sets the status of the query as dead.
Returns:
void
References KviWindow::connection(), KviWindow::context(), Dead, KviWindow::DeadQuery, KviUserListView::enableUpdates(), m_iFlags, m_pUserListView, KviUserListView::partAll(), KviIrcContext::registerDeadQuery(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcConnection::unregisterQuery(), KviWindow::updateCaption(), KviWindow::updateIcon(), and updateLabelText().
KviUserListEntry * KviQueryWindow::setTarget (const QString & szNick, const QString & szUser, const QString & szHost)
Sets the target of the query.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
Returns:
KviUserListEntry *
References KviIrcUserEntry::avatar(), KviConsoleWindow::checkDefaultAvatar(), KviWindow::connection(), KviIrcConnection::getCommonChannels(), KviUserListEntry::globalData(), KviUserListView::join(), KVI_OPTION_BOOL, KviEvent_OnQueryTargetAdded, KviOption_boolEnableQueryTracing, KVS_TRIGGER_EVENT_3, KviWindow::m_pConsole, m_pUserListView, notifyCommonChannels(), KviWindow::setWindowName(), szHost, KviWindow::updateCaption(), and updateLabelText().
Referenced by KviIrcConnection::loginComplete(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), and setAliveQuery().
void KviQueryWindow::showListView (bool bShow, bool bIgnoreSizeChange = false)
Shows the userlist view.
Parameters:
bShow Whether to show or hide the view
bIgnoreSizeChange Whether to ignore the size change
Returns:
void
References m_pListViewButton, KviWindow::m_pSplitter, m_pUserListView, and m_SplitterSizesList.
Referenced by loadProperties(), and toggleListView().
QSize KviQueryWindow::sizeHint () const virtual
Returns the size of the query object.
Returns:
QSize
References KviInput::heightHint(), KviWindow::m_pInput, KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviIrcView::sizeHint().
void KviQueryWindow::slotDndEvents (const QString & szFile) protected slot
Triggers the OnQueryFileDropped event.
Parameters:
szFile The file dropped in the query
Returns:
void
References KviEvent_OnQueryFileDropped, and KVS_TRIGGER_EVENT_1.
Referenced by KviQueryWindow().
virtual const QString& KviQueryWindow::target () inline virtual
Returns the name of the query target.
Returns:
const QString &
Reimplemented from KviWindow.
References KviWindow::windowName().
Referenced by pasteLastLog(), and setAliveQuery().
void KviQueryWindow::textViewRightClicked () protected slot
Triggers the OnQueryPopupRequest event.
Returns:
void
References KviEvent_OnQueryPopupRequest, and KVS_TRIGGER_EVENT_0.
Referenced by KviQueryWindow().
void KviQueryWindow::toggleListView () protected slot
Toggles the userlist view.
Returns:
void
References m_pUserListView, and showListView().
Referenced by KviQueryWindow().
void KviQueryWindow::triggerCreationEvents () protected virtual
Trigger the OnQueryWindowCreated event.
Returns:
void
Reimplemented from KviWindow.
References KviEvent_OnQueryWindowCreated, and KVS_TRIGGER_EVENT_0.
void KviQueryWindow::updateLabelText ()
Updates the text of the tooltip.
Returns:
void
References KviTalToolTip::add(), getInfoLabelText(), getWindowListTipText(), m_pLabel, and szBuffer.
Referenced by applyOptions(), KviQueryWindow(), mergeQuery(), nickChange(), notifyCommonChannels(), notifyTargetChange(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhoReply(), setDeadQuery(), setTarget(), and userAction().
void KviQueryWindow::userAction (KviIrcMask * user, unsigned int uActionType)
Called when a user performs an action.
Parameters:
user The source user
uActionType The type of the action
Returns:
void
References KviIrcMask::host(), kvi_getUserActionTemperature(), KVI_OPTION_BOOL, KviOption_boolEnableQueryTracing, m_pUserListView, KviIrcMask::nick(), notifyTargetChange(), updateLabelText(), KviIrcMask::user(), KviUserListView::userAction(), and KviUserListView::userActionVerifyMask().
Referenced by ownMessage(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
void KviQueryWindow::userAction (const QString & szNick, unsigned int uActionType)
Called when a user performs an action.
Parameters:
szNick The nickname of the user
uActionType The type of the action
Returns:
void
References kvi_getUserActionTemperature(), m_pUserListView, updateLabelText(), and KviUserListView::userAction().
void KviQueryWindow::userAction (const QString & szNick, const QString & szUser, const QString & szHost, unsigned int uActionType)
Called when a user performs an action.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
uActionType The type of the action
Returns:
void
References kvi_getUserActionTemperature(), KVI_OPTION_BOOL, KviOption_boolEnableQueryTracing, m_pUserListView, notifyTargetChange(), updateLabelText(), KviUserListView::userAction(), and KviUserListView::userActionVerifyMask().
KviUserListView* KviQueryWindow::userListView () inline
Returns the userlist of the query (the remote peer)
Returns:
KviUserListView *
Member Data Documentation
int KviQueryWindow::m_iFlags protected
Referenced by KviQueryWindow(), setAliveQuery(), and setDeadQuery().
QFrame* KviQueryWindow::m_pButtonGrid protected
Referenced by KviQueryWindow().
KviThemedLabel* KviQueryWindow::m_pLabel protected
Referenced by KviQueryWindow(), and updateLabelText().
KviWindowToolPageButton* KviQueryWindow::m_pListViewButton protected
Referenced by KviQueryWindow(), and showListView().
KviUserListView* KviQueryWindow::m_pUserListView protected
Referenced by applyOptions(), KviQueryWindow(), nickChange(), ownAction(), saveProperties(), setAliveQuery(), setDeadQuery(), setTarget(), showListView(), toggleListView(), userAction(), and ~KviQueryWindow().
QList<int> KviQueryWindow::m_SplitterSizesList protected
Referenced by loadProperties(), saveProperties(), and showListView().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviQueryWindow.h
src/kvirc/ui/KviQueryWindow.cpp