KVIrc: KviDnsResolverThread Class Reference
KviDnsResolverThread Class Reference
#include <KviDnsResolver.h>
Public Member Functions
void setQuery (const QString &szQuery, KviDnsResolver::QueryType type)
Protected Member Functions
KviDnsResolverThread (KviDnsResolver *pDns)
void postDnsError (KviDnsResolverResult *pDns, KviError::Code error)
virtual void run ()
KviError::Code translateDnsError (int iErr)
virtual ~KviDnsResolverThread ()
Protected Attributes
KviDnsResolver * m_pParentDns
KviDnsResolver::QueryType m_queryType
QString m_szQuery
Friends
class KviDnsResolver
Constructor & Destructor Documentation
KviDnsResolverThread::KviDnsResolverThread (KviDnsResolver * pDns) protected
References m_pParentDns.
KviDnsResolverThread::~KviDnsResolverThread () protected virtual
Member Function Documentation
void KviDnsResolverThread::postDnsError (KviDnsResolverResult * pDns, KviError::Code error) protected
References m_pParentDns, and KviDnsResolverResult::setError().
Referenced by run().
void KviDnsResolverThread::run () protected virtual
References KviDnsResolverResult::appendAddress(), KviDnsResolverResult::appendHostname(), KviNetUtils::binaryIpToStringIp(), KviError::DNSQueryFailed, KviError::DNSTemporaneousFault, KviError::HostNotFound, KviDnsResolver::IPv4, KviDnsResolver::IPv6, m_pParentDns, m_queryType, m_szQuery, KviError::NoHostToResolve, KviError::NoIPv6Support, postDnsError(), KviDnsResolverResult::setError(), KviDnsResolverResult::setQuery(), KviNetUtils::stringIpToBinaryIp(), translateDnsError(), KviError::UnrecoverableNameserverError, and KviError::ValidNameButNoIpAddress.
void KviDnsResolverThread::setQuery (const QString & szQuery, KviDnsResolver::QueryType type) inline
References m_queryType, m_szQuery, and KviOsInfo::type().
Referenced by KviDnsResolver::lookup().
KviError::Code KviDnsResolverThread::translateDnsError (int iErr) protected
References KviError::DNSInternalErrorBadFlags, KviError::DNSInternalErrorOutOfMemory, KviError::DNSInternalErrorServiceNotSupported, KviError::DNSInternalErrorUnsupportedSocketType, KviError::DNSNoName, KviError::DNSQueryFailed, KviError::DNSTemporaneousFault, EAI_ADDRFAMILY, EAI_NODATA, KviError::UnrecoverableNameserverError, KviError::UnsupportedAddressFamily, and KviError::ValidNameButNoIpAddress.
Referenced by run().
Friends And Related Function Documentation
friend class KviDnsResolver friend
Member Data Documentation
KviDnsResolver* KviDnsResolverThread::m_pParentDns protected
Referenced by KviDnsResolverThread(), postDnsError(), and run().
KviDnsResolver::QueryType KviDnsResolverThread::m_queryType protected
Referenced by run(), and setQuery().
QString KviDnsResolverThread::m_szQuery protected
Referenced by KviDnsResolverResult::query(), run(), KviDnsResolverResult::setQuery(), and setQuery().
The documentation for this class was generated from the following files:
src/kvilib/net/KviDnsResolver.h
src/kvilib/net/KviDnsResolver.cpp