KVIrc: KviIrcToolsAction Class Reference
KviIrcToolsAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
KviIrcToolsAction (QObject *pParent)
Public Member Functions inherited from KviSubmenuAction
virtual QAction * addToCustomToolBar (KviCustomToolBar *pTool)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
KviSubmenuAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIcoNId=QString(), unsigned int uFlags=0)
~KviSubmenuAction ()
Public Member Functions inherited from KviKvsAction
virtual void activate ()
Executes the action.
KviKvsAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Contructs the action object.
const QString & scriptCode ()
Returns the code of the script contained in the action.
virtual ~KviKvsAction ()
Destroys the action object.
Public Member Functions inherited from KviAction
QPixmap * bigIcon ()
Returns the big icon associated to the action.
const QString & bigIconId () const
Returns the id of the big icon associated to the action.
KviActionCategory * category () const
Returns the category of the action.
virtual const QString & description ()
Returns the description of the action.
unsigned int flags ()
Returns the flag associated to the action.
bool isEnabled () const
Returns true if the action is enabled.
virtual bool isKviUserActionNeverOverrideThis ()
Returns true if the action is user-defined.
const QString & keySequence () const
Returns the shortcut of the action.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const KviIconManager::SmallIcon eIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
const QString & name () const
Returns the name of the action.
virtual void setEnabled (bool bEnabled)
Enables the action.
QPixmap * smallIcon ()
Returns the small icon associated to the action.
const QString & smallIconId () const
Returns the id of the small icon associated to the action.
void suicide ()
Destroys itself. Maybe the best function in the whole APIs :)
virtual const QString & visibleName ()
Returns the visible name of the action.
virtual ~KviAction ()
Destroys the action object.
Protected Slots
void popupAboutToShow ()
void popupActivated (QAction *pAction)
Protected Slots inherited from KviSubmenuAction
virtual void popupAboutToShow ()
virtual void popupActivated (QAction *pAction)
Protected Slots inherited from KviAction
virtual void actionDestroyed ()
Removes the action from the list.
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual void activeWindowChanged ()
Enables or disables the action upon checking the active window.
virtual void activeWindowSelectionStateChanged (bool bSelectedNow)
Enables or disables the action upon checking the active window.
virtual void reloadImages ()
Reloads the images.
Additional Inherited Members
Public Types inherited from KviAction
enum Flags {
NeedsContext = 1, NeedsConnection = 2, WindowConsole = 4, WindowChannel = 8,
WindowQuery = 16, WindowDccChat = 32, InternalWindowMask = WindowConsole | WindowChannel | WindowQuery | WindowDccChat, EnableAtLogin = 64,
WindowOnlyIfUsersSelected = 128
}
Holds the flags of an action.
enum InternalFlags { Enabled = 1, SetupDone = 2 }
Holds the internal flags of an action.
Public Slots inherited from KviAction
Signals inherited from KviAction
void activated ()
Emitted when the action is being activated.
Static Public Member Functions inherited from KviAction
static int validateFlags (int iFlagsToValidate)
Validates the flags of the action.
Protected Member Functions inherited from KviSubmenuAction
virtual void setup ()
Enables or disables the action upon starting KVIrc.
Protected Member Functions inherited from KviAction
KviPointerList< QAction > * actionList ()
Returns the list of actions associated to the action.
void registerAccelerator ()
Registers the action shortcut in the application.
void registerAction (QAction *pAction)
Adds the action to the list.
bool setupDone () const
Returns true if the setup is finished.
void unregisterAccelerator ()
Removes the action shortcut from the application.
Protected Attributes inherited from KviSubmenuAction
QMenu * m_pPopup
Protected Attributes inherited from KviKvsAction
QString m_szScript
Protected Attributes inherited from KviAction
QString m_eIcon
QPointer< QShortcut > m_pAccel
KviPointerList< QAction > * m_pActionList
KviActionCategory * m_pCategory
QString m_szBigIconId
QString m_szDescription
QString m_szKeySequence
QString m_szName
QString m_szSmallIconId
QString m_szVisibleName
unsigned int m_uFlags
unsigned short int m_uInternalFlags
Constructor & Destructor Documentation
KviIrcToolsAction::KviIrcToolsAction (QObject * pParent)
Member Function Documentation
void KviIrcToolsAction::popupAboutToShow () protected slot
References a, KviAction::addToPopupMenu(), KviActionManager::getAction(), KviActionManager::instance(), KVI_COREACTION_CHANNELLIST, KVI_COREACTION_NETWORKLINKS, KVI_COREACTION_SEPARATOR, KVI_COREACTION_SOCKETSPY, and KviSubmenuAction::m_pPopup.
void KviIrcToolsAction::popupActivated (QAction * pAction) protected slot
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp