KVIrc: FileTransferWindow Class Reference
FileTransferWindow Class Reference
#include <FileTransferWindow.h>
Public Member Functions
virtual void die ()
FileTransferWindow (KviModuleExtensionDescriptor *d)
int lineSpacing ()
virtual QSize sizeHint () const
~FileTransferWindow ()
Protected Slots
void clearAll ()
void clearTerminated ()
void copyLocalFileToClipboard ()
void deleteLocalFile ()
void doubleClicked (FileTransferItem *it, const QPoint &pnt)
void heartbeat ()
void openFilePopupActivated (int id)
void openLocalFile ()
void openLocalFileFolder ()
void openLocalFileTerminal ()
void openLocalFileWith ()
void rightButtonPressed (FileTransferItem *it, const QPoint &pnt)
void tipRequest (KviDynamicToolTip *tip, const QPoint &pnt)
void transferRegistered (KviFileTransfer *t)
void transferUnregistering (KviFileTransfer *t)
Protected Member Functions
virtual void applyOptions ()
bool eventFilter (QObject *obj, QEvent *ev)
virtual void fillCaptionBuffers ()
void fillTransferView ()
FileTransferItem * findItem (KviFileTransfer *t)
virtual void fontChange (const QFont &oldFont)
virtual void getBaseLogFileName (QString &buffer)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
KviFileTransfer * selectedTransfer ()
Protected Attributes
int m_iLineSpacing
KviTalPopupMenu * m_pContextPopup
QAbstractItemDelegate * m_pItemDelegate
KviTalPopupMenu * m_pLocalFilePopup
KviTalPopupMenu * m_pOpenFilePopup
FileTransferWidget * m_pTableWidget
QTimer * m_pTimer
QSplitter * m_pVertSplitter
Friends
class FileTransferItem
class FileTransferItemDelegate
Constructor & Destructor Documentation
FileTransferWindow::FileTransferWindow (KviModuleExtensionDescriptor * d)
References connect(), doubleClicked(), FileTransferItemDelegate, fillTransferView(), heartbeat(), KviFileTransferManager::instance(), KviTalSplitter, m_iLineSpacing, m_pContextPopup, KviWindow::m_pIrcView, m_pItemDelegate, m_pLocalFilePopup, m_pOpenFilePopup, KviWindow::m_pSplitter, m_pTableWidget, m_pTimer, m_pVertSplitter, rightButtonPressed(), KviFileTransferManager::setTransferWindow(), transferRegistered(), and transferUnregistering().
FileTransferWindow::~FileTransferWindow ()
References KviFileTransferManager::instance(), and KviFileTransferManager::setTransferWindow().
Member Function Documentation
void FileTransferWindow::applyOptions () [protected, virtual]
Reimplemented from KviWindow.
References KviIrcView::applyOptions(), and KviWindow::m_pIrcView.
void FileTransferWindow::clearAll () [protected, slot]
References __tr2qs_ctx(), i, KviFileTransferManager::instance(), KviFileTransferManager::killAllTransfers(), m_pTableWidget, KviFileTransfer::terminated(), FileTransferItem::transfer(), and KviMessageBox::warning().
Referenced by rightButtonPressed().
void FileTransferWindow::clearTerminated () [protected, slot]
References KviFileTransferManager::instance(), and KviFileTransferManager::killTerminatedTransfers().
Referenced by rightButtonPressed().
void FileTransferWindow::copyLocalFileToClipboard () [protected, slot]
References KviFileTransfer::localFileName(), selectedTransfer(), and t().
Referenced by rightButtonPressed().
void FileTransferWindow::deleteLocalFile () [protected, slot]
References __tr2qs_ctx(), KviFileTransfer::localFileName(), selectedTransfer(), and KviMessageBox::warning().
Referenced by rightButtonPressed().
void FileTransferWindow::die () [virtual]
Implements KviModuleExtension.
void FileTransferWindow::doubleClicked (FileTransferItem * it, const QPoint & pnt) [protected, slot]
References openLocalFile().
Referenced by FileTransferWindow().
bool FileTransferWindow::eventFilter (QObject * obj, QEvent * ev) [protected]
Reimplemented from KviWindow.
References m_pTableWidget.
void FileTransferWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void FileTransferWindow::fillTransferView () [protected]
References FileTransferItem, KviPointerList< T >::first(), KviFileTransferManager::instance(), l, m_pTableWidget, KviPointerList< T >::next(), t(), and KviFileTransferManager::transferList().
Referenced by FileTransferWindow().
FileTransferItem * FileTransferWindow::findItem (KviFileTransfer * t) [protected]
References i, m_pTableWidget, t(), and FileTransferItem::transfer().
Referenced by transferUnregistering().
void FileTransferWindow::fontChange (const QFont & oldFont) [protected, virtual]
References m_iLineSpacing.
void FileTransferWindow::getBaseLogFileName (QString & buffer) [protected, virtual]
Reimplemented from KviWindow.
void FileTransferWindow::heartbeat () [protected, slot]
References KviFileTransfer::active(), i, m_pTableWidget, NULL, and FileTransferItem::transfer().
Referenced by FileTransferWindow().
int FileTransferWindow::lineSpacing () [inline]
References m_iLineSpacing.
QPixmap * FileTransferWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References KviIconManager::FileTransfer, g_pIconManager, and KviIconManager::getSmallIcon().
void FileTransferWindow::openFilePopupActivated (int id) [protected, slot]
References g_pMainWindow, KviTalPopupMenu::itemParameter(), KviFileTransfer::localFileName(), m_pOpenFilePopup, KviIrcUrl::run(), selectedTransfer(), and t().
Referenced by rightButtonPressed().
void FileTransferWindow::openLocalFile () [protected, slot]
References g_pMainWindow, KviFileTransfer::localFileName(), NULL, openLocalFileWith(), KviIrcUrl::run(), selectedTransfer(), and t().
Referenced by doubleClicked(), and rightButtonPressed().
void FileTransferWindow::openLocalFileFolder () [protected, slot]
References g_pMainWindow, KviFileTransfer::localFileName(), KviIrcUrl::run(), selectedTransfer(), and t().
Referenced by rightButtonPressed().
void FileTransferWindow::openLocalFileTerminal () [protected, slot]
References g_pMainWindow, KviFileTransfer::localFileName(), selectedTransfer(), and t().
Referenced by rightButtonPressed().
void FileTransferWindow::openLocalFileWith () [protected, slot]
References g_pMainWindow, KviFileTransfer::localFileName(), selectedTransfer(), and t().
Referenced by openLocalFile(), and rightButtonPressed().
void FileTransferWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviWindow::m_pSplitter.
void FileTransferWindow::rightButtonPressed (FileTransferItem * it, const QPoint & pnt) [protected, slot]
References __tr2qs_ctx(), KviTalPopupMenu::clear(), clearAll(), clearTerminated(), connect(), copyLocalFileToClipboard(), deleteLocalFile(), KviFileTransfer::fillContextPopup(), i, KviWindow::id(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), l, KviFileTransfer::localFileName(), m_pContextPopup, m_pLocalFilePopup, m_pOpenFilePopup, m_pTableWidget, KviQString::makeSizeReadable(), Normal, openFilePopupActivated(), openLocalFile(), openLocalFileFolder(), openLocalFileTerminal(), openLocalFileWith(), p, KviTalPopupMenu::setItemEnabled(), KviTalPopupMenu::setItemParameter(), KviFileTransfer::terminated(), and FileTransferItem::transfer().
Referenced by FileTransferWindow().
KviFileTransfer * FileTransferWindow::selectedTransfer () [protected]
References i, m_pTableWidget, and FileTransferItem::transfer().
Referenced by copyLocalFileToClipboard(), deleteLocalFile(), openFilePopupActivated(), openLocalFile(), openLocalFileFolder(), openLocalFileTerminal(), and openLocalFileWith().
QSize FileTransferWindow::sizeHint () const [virtual]
References KviWindow::m_pSplitter.
void FileTransferWindow::tipRequest (KviDynamicToolTip * tip, const QPoint & pnt) [protected, slot]
References m_pTableWidget, KviDynamicToolTip::tip(), KviFileTransfer::tipText(), and FileTransferItem::transfer().
void FileTransferWindow::transferRegistered (KviFileTransfer * t) [protected, slot]
References FileTransferItem, and m_pTableWidget.
Referenced by FileTransferWindow().
void FileTransferWindow::transferUnregistering (KviFileTransfer * t) [protected, slot]
References findItem().
Referenced by FileTransferWindow().
Friends And Related Function Documentation
friend class FileTransferItem [friend]
Referenced by fillTransferView(), and transferRegistered().
friend class FileTransferItemDelegate [friend]
Referenced by FileTransferWindow().
Member Data Documentation
int FileTransferWindow::m_iLineSpacing [protected]
Referenced by FileTransferWindow(), fontChange(), and lineSpacing().
KviTalPopupMenu* FileTransferWindow::m_pContextPopup [protected]
Referenced by FileTransferWindow(), and rightButtonPressed().
QAbstractItemDelegate* FileTransferWindow::m_pItemDelegate [protected]
Referenced by FileTransferWindow().
KviTalPopupMenu* FileTransferWindow::m_pLocalFilePopup [protected]
Referenced by FileTransferWindow(), and rightButtonPressed().
KviTalPopupMenu* FileTransferWindow::m_pOpenFilePopup [protected]
Referenced by FileTransferWindow(), openFilePopupActivated(), and rightButtonPressed().
FileTransferWidget* FileTransferWindow::m_pTableWidget [protected]
Referenced by clearAll(), eventFilter(), FileTransferWindow(), fillTransferView(), findItem(), heartbeat(), rightButtonPressed(), selectedTransfer(), tipRequest(), and transferRegistered().
QTimer* FileTransferWindow::m_pTimer [protected]
Referenced by FileTransferWindow().
QSplitter* FileTransferWindow::m_pVertSplitter [protected]
Referenced by FileTransferWindow().
The documentation for this class was generated from the following files:
src/modules/filetransferwindow/FileTransferWindow.h
src/modules/filetransferwindow/FileTransferWindow.cpp