KVIrc: UPnP::WanConnectionService Class Reference
UPnP::WanConnectionService Class Reference
#include <WanConnectionService.h>
Public Member Functions
void addPortMapping (const QString &protocol, const QString &remoteHost, int externalPort, const QString &internalClient, int internalPort, const QString &description, bool enabled=true, int leaseDuration=0)
void deletePortMapping (const QString &protocol, const QString &remoteHost, int externalPort)
QString getExternalIpAddress () const
bool getNatEnabled () const
const KviPointerList
< PortMapping > & getPortMappings () const
void queryExternalIpAddress ()
void queryNatEnabled ()
void queryPortMappingEntry (int index)
WanConnectionService (const ServiceParameters &params)
virtual ~WanConnectionService ()
Public Member Functions inherited from UPnP::Service
int getPendingRequests () const
Service (const QString &hostname, int port, const QString &informationUrl)
Service (const ServiceParameters &params)
virtual ~Service ()
Protected Member Functions
virtual void gotActionResponse (const QString &responseType, const QMap< QString, QString > &resultValues)
Protected Member Functions inherited from UPnP::Service
int callAction (const QString &actionName, const QString &prefix)
int callAction (const QString &actionName, const QMap< QString, QString > &arguments, const QString &prefix)
int callInformationUrl ()
virtual void gotActionErrorResponse (const QDomNode &response)
virtual void gotInformationResponse (const QDomNode &response)
Private Attributes
bool m_bNatEnabled
KviPointerList< PortMapping > m_lPortMappings
QString m_szExternalIpAddress
Additional Inherited Members
Signals inherited from UPnP::Service
void queryFinished (bool error)
Detailed Description
The Wan(IP/PPP)Connection service controls the connection and port forwarding settings of a router. The Layer3ForwardingService result either defines a WanIPConnection or WanPPPConnection service. Which one is returned depends on the external connection type. This class implements the common actions both services support, which is sufficient to control the port mappings of the router.
Author:
Diederik van der Boor
Constructor & Destructor Documentation
UPnP::WanConnectionService::WanConnectionService (const ServiceParameters & params)
UPnP::WanConnectionService::~WanConnectionService () virtual
Member Function Documentation
void UPnP::WanConnectionService::addPortMapping (const QString & protocol, const QString & remoteHost, int externalPort, const QString & internalClient, int internalPort, const QString & description, bool enabled = true, int leaseDuration = 0)
References UPnP::Service::callAction().
Referenced by UPnP::IgdControlPoint::addPortMapping().
void UPnP::WanConnectionService::deletePortMapping (const QString & protocol, const QString & remoteHost, int externalPort)
References UPnP::Service::callAction().
Referenced by UPnP::IgdControlPoint::deletePortMapping().
QString UPnP::WanConnectionService::getExternalIpAddress () const
References m_szExternalIpAddress.
Referenced by UPnP::IgdControlPoint::getExternalIpAddress().
bool UPnP::WanConnectionService::getNatEnabled () const
References m_bNatEnabled.
const KviPointerList< PortMapping > & UPnP::WanConnectionService::getPortMappings () const
References m_lPortMappings.
void UPnP::WanConnectionService::gotActionResponse (const QString & responseType, const QMap< QString, QString > & resultValues) protected virtual
Reimplemented from UPnP::Service.
References KviPointerList< T >::append(), UPnP::PortMapping::description, UPnP::PortMapping::enabled, UPnP::PortMapping::externalPort, UPnP::PortMapping::internalClient, UPnP::PortMapping::internalPort, UPnP::PortMapping::leaseDuration, m_bNatEnabled, m_lPortMappings, m_szExternalIpAddress, UPnP::PortMapping::protocol, and UPnP::PortMapping::remoteHost.
void UPnP::WanConnectionService::queryExternalIpAddress ()
References UPnP::Service::callAction().
Referenced by UPnP::IgdControlPoint::slotDeviceQueried().
void UPnP::WanConnectionService::queryNatEnabled ()
References UPnP::Service::callAction().
void UPnP::WanConnectionService::queryPortMappingEntry (int index)
References UPnP::Service::callAction().
Member Data Documentation
bool UPnP::WanConnectionService::m_bNatEnabled private
Referenced by getNatEnabled(), and gotActionResponse().
KviPointerList<PortMapping> UPnP::WanConnectionService::m_lPortMappings private
Referenced by getPortMappings(), and gotActionResponse().
QString UPnP::WanConnectionService::m_szExternalIpAddress private
Referenced by getExternalIpAddress(), and gotActionResponse().
The documentation for this class was generated from the following files:
src/modules/upnp/WanConnectionService.h
src/modules/upnp/WanConnectionService.cpp