KVIrc: NickServRuleEditor Class Reference
NickServRuleEditor Class Reference
#include <OptionsWidget_nickserv.h>
Public Member Functions
bool editRule (KviNickServRule *r)
NickServRuleEditor (QWidget *par, bool bUseServerMaskField=false)
~NickServRuleEditor ()
Protected Slots
void okPressed ()
Protected Member Functions
bool validate ()
Protected Attributes
QLineEdit * m_pIdentifyCommandEdit
QLineEdit * m_pMessageRegexpEdit
QLineEdit * m_pNickServMaskEdit
QPushButton * m_pOkButton
QLineEdit * m_pRegisteredNickEdit
QLineEdit * m_pServerMaskEdit
Constructor & Destructor Documentation
NickServRuleEditor::NickServRuleEditor (QWidget * par, bool bUseServerMaskField = false)
References __tr2qs_ctx(), KviTalToolTip::add(), connect(), l, m_pIdentifyCommandEdit, m_pMessageRegexpEdit, m_pNickServMaskEdit, m_pOkButton, m_pRegisteredNickEdit, m_pServerMaskEdit, okPressed(), and p.
NickServRuleEditor::~NickServRuleEditor ()
Member Function Documentation
bool NickServRuleEditor::editRule (KviNickServRule * r)
References KviNickServRule::identifyCommand(), m_pIdentifyCommandEdit, m_pMessageRegexpEdit, m_pNickServMaskEdit, m_pRegisteredNickEdit, m_pServerMaskEdit, KviNickServRule::messageRegexp(), KviNickServRule::nickServMask(), KviNickServRule::registeredNick(), KviNickServRule::serverMask(), KviNickServRule::setIdentifyCommand(), KviNickServRule::setMessageRegexp(), KviNickServRule::setNickServMask(), KviNickServRule::setRegisteredNick(), and KviNickServRule::setServerMask().
Referenced by IrcNetworkDetailsWidget::addNickServRule(), and OptionsWidget_nickServ::addNickServRule().
void NickServRuleEditor::okPressed () [protected, slot]
References validate().
Referenced by NickServRuleEditor().
bool NickServRuleEditor::validate () [protected]
References __tr2qs_ctx(), m, m_pIdentifyCommandEdit, m_pMessageRegexpEdit, m_pNickServMaskEdit, m_pRegisteredNickEdit, o, s, and KviMessageBox::warning().
Referenced by okPressed().
Member Data Documentation
QLineEdit* NickServRuleEditor::m_pIdentifyCommandEdit [protected]
Referenced by editRule(), NickServRuleEditor(), and validate().
QLineEdit* NickServRuleEditor::m_pMessageRegexpEdit [protected]
Referenced by editRule(), NickServRuleEditor(), and validate().
QLineEdit* NickServRuleEditor::m_pNickServMaskEdit [protected]
Referenced by editRule(), NickServRuleEditor(), and validate().
QPushButton* NickServRuleEditor::m_pOkButton [protected]
Referenced by NickServRuleEditor().
QLineEdit* NickServRuleEditor::m_pRegisteredNickEdit [protected]
Referenced by editRule(), NickServRuleEditor(), and validate().
QLineEdit* NickServRuleEditor::m_pServerMaskEdit [protected]
Referenced by editRule(), and NickServRuleEditor().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_nickserv.h
src/modules/options/OptionsWidget_nickserv.cpp