KVIrc: DccChatThread Class Reference
DccChatThread Class Reference
#include <DccChatWindow.h>
Public Member Functions
DccChatThread (KviWindow *wnd, kvi_socket_t fd)
virtual void sendRawData (const void *buffer, int len)
~DccChatThread ()
Public Member Functions inherited from DccThread
DccThread (QObject *par, kvi_socket_t fd)
QObject * parent ()
void postErrorEvent (int err)
void postMessageEvent (const char *message)
~DccThread ()
Public Member Functions inherited from KviSensitiveThread
void enqueueEvent (KviThreadEvent *e)
KviSensitiveThread ()
void terminate ()
virtual ~KviSensitiveThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
virtual bool handleIncomingData (KviDccThreadIncomingData *data, bool bCritical)
virtual void run ()
bool tryFlushOutBuffers ()
Protected Member Functions inherited from DccThread
bool handleInvalidSocketRead (int readLen)
Protected Member Functions inherited from KviSensitiveThread
KviThreadEvent * dequeueEvent ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
Protected Attributes
KviPointerList< KviDataBuffer > * m_pOutBuffers
Protected Attributes inherited from DccThread
kvi_socket_t m_fd
KviMutex * m_pMutex
QObject * m_pParent
Protected Attributes inherited from KviSensitiveThread
KviPointerList< KviThreadEvent > * m_pLocalEventQueue
KviMutex * m_pLocalEventQueueMutex
Constructor & Destructor Documentation
DccChatThread::DccChatThread (KviWindow * wnd, kvi_socket_t fd)
References m_pOutBuffers, and KviPointerList< T >::setAutoDelete().
DccChatThread::~DccChatThread ()
References m_pOutBuffers.
Member Function Documentation
bool DccChatThread::handleIncomingData (KviDccThreadIncomingData * data, bool bCritical) protected virtual
References _KviDccThreadIncomingData::buffer, KviCString::cutRight(), e, KviMemory::free(), _KviDccThreadIncomingData::iLen, KVI_ASSERT, KVI_DCC_THREAD_EVENT_DATA, KviCString::lastCharIs(), KviMemory::move(), DccThread::parent(), KviThread::postEvent(), KviMemory::reallocate(), s, and KviThreadDataEvent< TData >::setData().
Referenced by run().
void DccChatThread::run () protected virtual
Reimplemented from KviThread.
References _KviDccThreadIncomingData::buffer, KviSensitiveThread::dequeueEvent(), e, KviMemory::free(), handleIncomingData(), DccThread::handleInvalidSocketRead(), _KviDccThreadIncomingData::iLen, KVI_ASSERT, KVI_INVALID_SOCKET, kvi_select(), kvi_socket_close, kvi_socket_recv(), KVI_THREAD_EVENT_TERMINATE, DccThread::m_fd, KviThread::msleep(), DccThread::postErrorEvent(), KviMemory::reallocate(), KviError::SSLError, and tryFlushOutBuffers().
void DccChatThread::sendRawData (const void * buffer, int len) virtual
References KviPointerList< T >::append(), KviMutex::lock(), DccThread::m_pMutex, m_pOutBuffers, and KviMutex::unlock().
Referenced by DccChatWindow::ownAction(), and DccChatWindow::ownMessage().
bool DccChatThread::tryFlushOutBuffers () protected
References KviPointerList< T >::first(), kvi_socket_error(), kvi_socket_send(), KviMutex::lock(), DccThread::m_fd, DccThread::m_pMutex, m_pOutBuffers, DccThread::postErrorEvent(), KviError::RemoteEndClosedConnection, KviPointerList< T >::removeFirst(), KviError::SSLError, KviError::translateSystemError(), and KviMutex::unlock().
Referenced by run().
Member Data Documentation
KviPointerList<KviDataBuffer>* DccChatThread::m_pOutBuffers protected
Referenced by DccChatThread(), sendRawData(), tryFlushOutBuffers(), and ~DccChatThread().
The documentation for this class was generated from the following files:
src/modules/dcc/DccChatWindow.h
src/modules/dcc/DccChatWindow.cpp