KVIrc: TorrentInterface Class Reference
TorrentInterface Class Reference
#include <TorrentInterface.h>
Public Member Functions
virtual bool announce (int i)=0
virtual int count ()=0
virtual int detect ()=0
virtual int fileCount (int i)=0
virtual QString fileName (int i, int file)=0
virtual QString filePriority (int i, int file)=0
QString lastError ()
virtual int maxDownloadSpeed ()=0
virtual int maxUploadSpeed ()=0
virtual QString name (int i)=0
virtual bool setFilePriority (int i, int file, const QString &prio)=0
virtual bool setMaxDownloadSpeed (int kbytes_per_sec)=0
virtual bool setMaxUploadSpeed (int kbytes_per_sec)=0
virtual float speedDown ()=0
virtual float speedUp ()=0
virtual bool start (int i)=0
virtual bool startAll ()=0
virtual QString state (int i)=0
virtual bool stop (int i)=0
virtual bool stopAll ()=0
TorrentInterface ()
virtual float trafficDown ()=0
virtual float trafficUp ()=0
virtual ~TorrentInterface ()
Static Public Member Functions
static void select (TorrentInterface *i)
static TorrentInterface * selected ()
Protected Attributes
QString m_lastError
Static Protected Attributes
static TorrentInterface * m_selected = 0
Constructor & Destructor Documentation
TorrentInterface::TorrentInterface () [inline]
virtual TorrentInterface::~TorrentInterface () [inline, virtual]
Member Function Documentation
virtual bool TorrentInterface::announce (int i) [pure virtual]
virtual int TorrentInterface::count () [pure virtual]
virtual int TorrentInterface::detect () [pure virtual]
Referenced by auto_detect_torrent_client().
virtual int TorrentInterface::fileCount (int i) [pure virtual]
virtual QString TorrentInterface::fileName (int i, int file) [pure virtual]
virtual QString TorrentInterface::filePriority (int i, int file) [pure virtual]
QString TorrentInterface::lastError () [inline]
References m_lastError.
virtual int TorrentInterface::maxDownloadSpeed () [pure virtual]
virtual int TorrentInterface::maxUploadSpeed () [pure virtual]
virtual QString TorrentInterface::name (int i) [pure virtual]
static void TorrentInterface::select (TorrentInterface * i) [inline, static]
References i, and m_selected.
Referenced by TC_KVS_COMMAND(), and torrent_module_init().
static TorrentInterface* TorrentInterface::selected () [inline, static]
References m_selected.
Referenced by StatusBarApplet::update().
virtual bool TorrentInterface::setFilePriority (int i, int file, const QString & prio) [pure virtual]
virtual bool TorrentInterface::setMaxDownloadSpeed (int kbytes_per_sec) [pure virtual]
virtual bool TorrentInterface::setMaxUploadSpeed (int kbytes_per_sec) [pure virtual]
virtual float TorrentInterface::speedDown () [pure virtual]
virtual float TorrentInterface::speedUp () [pure virtual]
virtual bool TorrentInterface::start (int i) [pure virtual]
virtual bool TorrentInterface::startAll () [pure virtual]
virtual QString TorrentInterface::state (int i) [pure virtual]
virtual bool TorrentInterface::stop (int i) [pure virtual]
virtual bool TorrentInterface::stopAll () [pure virtual]
virtual float TorrentInterface::trafficDown () [pure virtual]
virtual float TorrentInterface::trafficUp () [pure virtual]
Member Data Documentation
QString TorrentInterface::m_lastError [protected]
Referenced by lastError().
TorrentInterface * TorrentInterface::m_selected = 0 [static, protected]
Referenced by select(), and selected().
The documentation for this class was generated from the following files:
src/modules/torrent/TorrentInterface.h
src/modules/torrent/TorrentInterface.cpp