KVIrc: KviPointerHashTable< Key, T > Class Template Reference
KviPointerHashTable< Key, T > Class Template Reference
A fast pointer hash table implementation.
#include <KviPointerHashTable.h>
Public Member Functions
void clear ()
Removes all the items from the hash table.
void copyFrom (KviPointerHashTable< Key, T > &t)
Removes all items in the hash table and then makes a complete shallow copy of the data contained in t.
unsigned int count () const
Returns the number of items in this hash table.
T * current ()
Returns the data value pointer pointed by the hash table iterator.
KviPointerHashTableEntry< Key,
T > * currentEntry ()
Returns the entry pointed by the hash table iterator.
const Key & currentKey ()
Returns the key pointed by the hash table iterator.
T * find (const Key &hKey)
Returns the item associated to the key.
KviPointerHashTableEntry< Key,
T > * findRef (const T *pRef)
Searches for the item pointer pRef.
T * first ()
Places the hash table iterator at the first entry.
KviPointerHashTableEntry< Key,
T > * firstEntry ()
Places the hash table iterator at the first entry and returns it.
void insert (const Key &hKey, T *pData)
Inserts the item pData at the position specified by the key hKey.
void insert (KviPointerHashTable< Key, T > &t)
Inserts a complete shallow copy of the data contained in t.
bool isEmpty () const
Returns true if the hash table is empty.
KviPointerHashTable (unsigned int uSize=32, bool bCaseSensitive=true, bool bDeepCopyKeys=true)
Creates an empty hash table.
KviPointerHashTable (KviPointerHashTable< Key, T > &t)
First creates an empty hash table and then inserts a copy of all the item pointers present in t.
T * next ()
Places the hash table iterator at the next entry and returns the associated data value pointer.
KviPointerHashTableEntry< Key,
T > * nextEntry ()
Places the hash table iterator at the next entry and returns it.
T * operator[] (const Key &hKey)
Returns the item associated to the key hKey.
bool remove (const Key &hKey)
Removes the item pointer associated to the key hKey, if such an item exists in the hash table.
bool removeRef (const T *pRef)
Removes the first occurence of the item pointer pRef.
void replace (const Key &hKey, T *pData)
Inserts the item pData at the position specified by the key hKey.
void setAutoDelete (bool bAutoDelete)
Enables or disabled the autodeletion feature.
~KviPointerHashTable ()
Destroys the hash table and all the items contained within.
Protected Attributes
bool m_bAutoDelete
bool m_bCaseSensitive
bool m_bDeepCopyKeys
KviPointerList
< KviPointerHashTableEntry
< Key, T > > ** m_pDataArray
unsigned int m_uCount
unsigned int m_uIteratorIdx
unsigned int m_uSize
Friends
class KviPointerHashTableIterator< Key, T >
Detailed Description
template<class Key, class T>
class KviPointerHashTable< Key, T >
A fast pointer hash table implementation.
A very cool, very fast hash table implementation :P
To use this hash table you need to provide implementations for the following functions:
* unsigned int kvi_hash_hash(const Key & hKey, bool bCaseSensitive);
* bool kvi_hash_key_equal(const Key & hKey1, const Key & hKey2, bool
* bCaseSensitive);
* void kvi_hash_key_copy(const Key & hKeyFrom, Key & hKeyTo, bool bDeepCopy);
* void kvi_hash_key_destroy(Key & hKey, bool bIsDeepCopy);
* const Key & kvi_hash_key_default(Key *);
*
Implementations for the most likey Key data types are provided below. KviPointerHashTable will automagically work with const char, QString, KviCString and integer types as keys.
For string Key types, the hash table may or may not be case sensitive. For other Key types the case sensitive flag has no meaning and will (hopefully) be optimized out by the compiler.
For pointer based keys the hash table may or may not mantain deep copies of Key data. For example, with char * keys, if deep copying is enabled then a private copy of the string data will be mantained. With deep copying disabled only char * pointers will be kept. For types that do not have meaning of deep copy the deep copying code will (hopefully) be optimized out by the compiler.
The hashtable mantains an array of KviPointerList based buckets. The number of buckets may be specified by the application user and does NOT need to be a prime number. Yet better to have it a power of two so the memory allocation routines will feel better and are less likely to waste space.
Constructor & Destructor Documentation
template<class Key, class T> KviPointerHashTable< Key, T >::KviPointerHashTable (unsigned int uSize = 32, bool bCaseSensitive = true, bool bDeepCopyKeys = true) inline
Creates an empty hash table.
Automatic deletion is enabled.
Parameters:
uSize The number of hash buckets: does NOT necesairly need to be prime
bCaseSensitive Are the key comparisons case sensitive ?
bDeepCopyKeys Do we need to mantain deep copies of keys ?
Returns:
KviPointerHashTable
template<class Key, class T> KviPointerHashTable< Key, T >::KviPointerHashTable (KviPointerHashTable< Key, T > & t) inline
First creates an empty hash table and then inserts a copy of all the item pointers present in t.
The autodelete feature is automatically disabled (take care!).
Parameters:
t The data to copy
Returns:
KviPointerHashTable
template<class Key, class T> KviPointerHashTable< Key, T >::~KviPointerHashTable () inline
Destroys the hash table and all the items contained within.
Items are deleted if autodeletion is enabled.
Member Function Documentation
template<class Key, class T> void KviPointerHashTable< Key, T >::clear () inline
Removes all the items from the hash table.
The items are deleted if autodeletion is enabled. Invalidates the hash table iterator.
Returns:
void
Referenced by KviIsOnNotifyListManager::buildRegUserDict(), KviWatchNotifyListManager::buildRegUserDict(), KviCustomToolBarManager::clear(), KviSharedFilesManager::clear(), KviIrcServerDataBase::clear(), KviKvsScriptAddonManager::clear(), KviTextIconManager::clear(), KviIconManager::clearCache(), KviRegisteredUserDataBase::copyFrom(), KviUserIdentityManager::copyFrom(), KviPointerHashTable< QString, KviActionCategory >::copyFrom(), KviKvsPopupManager::load(), KviKvsAliasManager::load(), KviAvatarCache::load(), KviUserIdentityManager::load(), KviTextIconManager::load(), RegisteredUserPropertiesDialog::okClicked(), KviKvsParser::parse(), KviKvsParser::parseAsExpression(), KviKvsParser::parseAsParameter(), KviPackageReader::readHeaderInternal(), KviUserListView::removeAllEntries(), KviIsOnNotifyListManager::stop(), KviWatchNotifyListManager::stop(), ClassEditorWidget::~ClassEditorWidget(), and KviPointerHashTable< QString, KviActionCategory >::~KviPointerHashTable().
template<class Key, class T> void KviPointerHashTable< Key, T >::copyFrom (KviPointerHashTable< Key, T > & t) inline
Removes all items in the hash table and then makes a complete shallow copy of the data contained in t.
The removed items are deleted if autodeletion is enabled. The hash table iterator is invalidated. Does not change autodelete flag: make sure you don't delete the items twice :)
Parameters:
t The data to copy
Returns:
void
Referenced by KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable().
template<class Key, class T> unsigned int KviPointerHashTable< Key, T >::count () const inline
Returns the number of items in this hash table.
Returns:
unsigned int
Referenced by KviAvatarCache::cleanup(), KviConfigurationFile::clearKey(), RegisteredUsersDialog::exportClicked(), RegisteredUserPropertiesDialog::fillData(), OptionsWidget_textIcons::fillTable(), KviIrcServerDataBase::networkCount(), KviPackageWriter::packInternal(), perlcore_module_can_unload(), pythoncore_module_can_unload(), reguser_kvs_cmd_showlist(), KviAvatarCache::replace(), KviConfigurationFile::save(), KviUserListView::updateUsersLabel(), KviUserListView::userStats(), and DccDescriptor::~DccDescriptor().
template<class Key, class T> T* KviPointerHashTable< Key, T >::current () inline
Returns the data value pointer pointed by the hash table iterator.
This function must be preceeded by a call to firstEntry(), first() or findRef().
Returns:
T *
template<class Key, class T> KviPointerHashTableEntry<Key,T>* KviPointerHashTable< Key, T >::currentEntry () inline
Returns the entry pointed by the hash table iterator.
This function must be preceeded by a call to firstEntry(), first() or findRef().
Returns:
KviPointerHashTableEntry<Key,T> *
template<class Key, class T> const Key& KviPointerHashTable< Key, T >::currentKey () inline
Returns the key pointed by the hash table iterator.
This function must be preceeded by a call to firstEntry(), first() or findRef().
Returns:
const Key &
template<class Key, class T> T* KviPointerHashTable< Key, T >::find (const Key & hKey) inline
Returns the item associated to the key.
Returns NULL if no such item exists in the hash table. Places the hash table iterator at the position of the item found.
Parameters:
hKey The key to find
Returns:
T *
Referenced by KviRegisteredUserDataBase::addGroup(), KviRegisteredUserDataBase::addMask(), KviApplication::addRecentChannel(), KviSharedFilesManager::addSharedFile(), KviKvsTimerManager::addTimer(), KviRegisteredUserDataBase::addUser(), AliasEditorWidget::aliasRefresh(), KviModuleExtensionManager::allocateExtensionGetDescriptorList(), KviUserListView::avatarChanged(), ClassEditorWidget::build(), KviApplication::buildRecentChannels(), KviActionManager::category(), KviTextIconManager::checkDefaultAssociations(), ClassEditorWidget::classExists(), KviConfigurationFile::clearGroup(), KviLocale::codecForName(), config_kvs_cmd_clear(), config_kvs_cmd_clearsection(), config_kvs_cmd_close(), config_kvs_cmd_flush(), config_kvs_cmd_setsection(), config_kvs_cmd_write(), config_kvs_fnc_filename(), config_kvs_fnc_hassection(), config_kvs_fnc_keylist(), config_kvs_fnc_read(), config_kvs_fnc_readonly(), config_kvs_fnc_section(), config_kvs_fnc_sectionlist(), KviKvsObject::connectSignal(), KviActionManager::coreActionExists(), KviCustomToolBarManager::create(), KviStatusBar::createApplet(), ClassEditorWidget::currentItemChanged(), KviIrcServerDataBase::currentNetwork(), KviUserIdentityManager::defaultIdentity(), KviKvsTimerManager::deleteTimer(), KviCustomToolBarManager::destroyDescriptor(), KviKvsObject::disconnectSignal(), KviKvsDnsManager::dnsLookupTerminated(), KviIsOnNotifyListManager::doMatchUser(), KviWatchNotifyListManager::doMatchUser(), RegisteredUserEntryDialog::editAllPropertiesClicked(), KviKvsObject::emitSignal(), KviUserListView::ensureVisible(), ClassEditorWidget::exportClasses(), KviActionDrawer::fill(), RegisteredUsersDialog::fillList(), DccDescriptor::find(), KviKvsScriptAddonManager::findAddon(), KviRegisteredUserDataBase::findExactMask(), KviModuleExtensionManager::findExtensionDescriptor(), KviRegisteredUserDataBase::findMatchingMask(), KviModuleManager::findModule(), KviIrcServerDataBase::findNetwork(), DccBroker::findZeroPortTag(), KviUserListView::flags(), KviKvsHash::get(), KviActionManager::getAction(), KviRegisteredUser::getBoolProperty(), KviConfigurationFile::getCurrentGroup(), KviModuleExtensionManager::getExtensionList(), KviLocale::getLoadedCatalogue(), KviModuleManager::getModule(), KviIconManager::getPixmapWithCache(), KviIconManager::getPixmapWithCacheScaleOnLoad(), PluginManager::getPlugin(), KviRegisteredUser::getProperty(), KviIconManager::getSmallIconIdFromName(), KviKvsTreeNodeSwitchList::getStandardRebindingSwitch(), KviPackageReader::getStringInfoField(), KviRegisteredUserDataBase::getUser(), KviUserListView::getUserJoinTime(), KviUserListView::getUserLastActionTime(), KviUserListView::getUserModeLevel(), KviWatchNotifyListManager::handleWatchReply(), KviConfigurationFile::hasGroup(), KviConfigurationFile::hasKey(), KviCustomToolBarManager::idForNewToolBar(), KviIrcUserDataBase::insertUser(), AddonFunctions::installAddonPackage(), ThemeFunctions::installThemePackage(), PluginManager::isPluginLoaded(), KviUserListView::join(), KviKvsObjectClass::KviKvsObjectClass(), KviConfigurationFile::load(), KviRegisteredUserDataBase::load(), KviTextIconManager::load(), KviLocale::loadCatalogue(), ClassEditorWidget::loadNotBuiltClasses(), KviAvatarCache::lookup(), KviKvsObjectController::lookupClass(), KviKvsObject::lookupFunctionHandler(), KviSharedFilesManager::lookupSharedFile(), KviIrcServerDataBase::makeCurrentServer(), KviActionManager::nameForAutomaticAction(), KviUserListView::nickChange(), KviPointerHashTable< QString, KviActionCategory >::operator[](), options_kvs_cmd_dialog(), options_kvs_fnc_isdialog(), KviKvsParser::parsePercent(), KviUserListView::partInternal(), KviSoundPlayer::play(), PopupEditorWidget::popupRefresh(), KviHttpRequest::processHeader(), KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readCharEntry(), KviConfigurationFile::readColorEntry(), KviConfigurationFile::readEntry(), KviConfigurationFile::readFontEntry(), KviConfigurationFile::readIntEntry(), KviConfigurationFile::readIntListEntry(), KviConfigurationFile::readMsgTypeEntry(), KviConfigurationFile::readPixmapEntry(), KviConfigurationFile::readRectEntry(), KviConfigurationFile::readStringListEntry(), KviConfigurationFile::readUCharEntry(), KviConfigurationFile::readUIntEntry(), KviConfigurationFile::readUShortEntry(), KviApplication::recentChannelsForNetwork(), KviActionManager::registerAction(), KviModuleExtensionManager::registerExtension(), KviRegisteredUserDataBase::removeMaskByPointer(), KviSharedFilesManager::removeSharedFile(), KviRegisteredUserDataBase::removeUser(), KviCustomToolBarManager::renameDescriptor(), KviUserListView::select(), KviKvsTimerManager::timerEvent(), KviMessageCatalogue::translate(), KviLocale::translate(), KviMessageCatalogue::translateToQString(), KviLocale::translateToQString(), KviCustomToolBar::unfilterChild(), KviActionManager::unregisterAction(), KviUserListView::userAction(), and KviUserListView::userActionVerifyMask().
template<class Key, class T> KviPointerHashTableEntry<Key,T>* KviPointerHashTable< Key, T >::findRef (const T * pRef) inline
Searches for the item pointer pRef.
Returns its hash table entry, if found, and NULL otherwise. The hash table iterator is placed at the item found.
Parameters:
pRef The pointer to search
Returns:
KviPointerHashTableEntry<Key,T> *
Referenced by KviKvsObjectController::clearUserClasses(), and ClassEditorWidget::renameNamespace().
template<class Key, class T> T* KviPointerHashTable< Key, T >::first () inline
Places the hash table iterator at the first entry.
It returns the associated data value pointer.
Returns:
T *
Referenced by KviTextIconManager::applyOptions(), ChannelsJoinDialog::deleteClicked(), RegisteredUsersDialog::editGroup(), RegisteredUsersDialog::fillList(), ChannelsJoinDialog::fillListView(), KviPointerHashTable< QString, KviActionCategory >::find(), KviPointerHashTable< QString, KviActionCategory >::findRef(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::remove(), and KviPointerHashTable< QString, KviActionCategory >::removeRef().
template<class Key, class T> KviPointerHashTableEntry<Key,T>* KviPointerHashTable< Key, T >::firstEntry () inline
Places the hash table iterator at the first entry and returns it.
Returns:
KviPointerHashTableEntry<Key,T> *
Referenced by KviPointerHashTable< QString, KviActionCategory >::copyFrom(), RegisteredUsersDialog::exportClicked(), KviPointerHashTable< QString, KviActionCategory >::insert(), RegisteredUsersDialog::rightButtonPressed(), and KviKvsObject::~KviKvsObject().
template<class Key, class T> void KviPointerHashTable< Key, T >::insert (const Key & hKey, T * pData) inline
Inserts the item pData at the position specified by the key hKey.
Replaces any previous item with the same key The replaced item is deleted if autodelete is enabled. The hash table iterator is placed at the newly inserted item.
Parameters:
hKey The key where to insert data
pData The data to insert
Returns:
void
Referenced by KviRegisteredUserDataBase::addMask(), KviApplication::addRecentChannel(), KviKvsTimerManager::addTimer(), KviIconManager::addToCache(), DccBroker::addZeroPortTag(), KviApplication::buildRecentChannels(), config_kvs_fnc_open(), KviKvsObject::connectSignal(), KviPointerHashTable< QString, KviActionCategory >::copyFrom(), ClassEditorWidget::createFullClass(), ClassEditorWidget::currentItemChanged(), RegisteredUsersDialog::editGroup(), RegisteredUsersDialog::fillList(), KviCustomToolBar::filterChild(), KviConfigurationFile::getCurrentGroup(), KviKvsObjectController::init(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviIrcUserDataBase::insertUser(), KviUserListView::insertUserEntry(), KviKvsObjectClass::KviKvsObjectClass(), KviSoundPlayer::KviSoundPlayer(), KviKvsPopupManager::load(), KviKvsAliasManager::load(), KviConfigurationFile::load(), KviMessageCatalogue::load(), KviLocale::loadCatalogue(), KviModuleManager::loadModule(), ClassEditorWidget::loadNotBuiltClasses(), PluginManager::loadPlugin(), ClassEditorWidget::newClass(), objects_kvs_fnc_classes(), ClassEditorWidget::oneTimeSetup(), options_kvs_cmd_dialog(), KviActionManager::registerAction(), KviKvsObjectController::registerClass(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), KviModuleExtensionManager::registerExtension(), KviKvsObjectController::registerObject(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameNamespace(), KviPointerHashTable< QString, KviActionCategory >::replace(), KviLocale::translate(), KviMessageCatalogue::translateToQString(), and KviLocale::translateToQString().
template<class Key, class T> void KviPointerHashTable< Key, T >::insert (KviPointerHashTable< Key, T > & t) inline
Inserts a complete shallow copy of the data contained in t.
The hash table iterator is invalidated.
Parameters:
t The data to insert
Returns:
void
template<class Key, class T> bool KviPointerHashTable< Key, T >::isEmpty () const inline
Returns true if the hash table is empty.
Returns:
bool
Referenced by config_module_can_unload(), KviKvsTimerManager::deleteAllTimers(), KviKvsObject::disconnectSignal(), options_module_can_unload(), KviKvsObject::registerPrivateImplementation(), KviPointerHashTable< QString, KviActionCategory >::remove(), KviPointerHashTable< QString, KviActionCategory >::removeRef(), KviIsOnNotifyListManager::start(), and KviModuleManager::unloadModule().
template<class Key, class T> T* KviPointerHashTable< Key, T >::next () inline
Places the hash table iterator at the next entry and returns the associated data value pointer.
This function must be preceeded by a call to firstEntry(), first() or findRef().
Returns:
T *
Referenced by KviTextIconManager::applyOptions(), ChannelsJoinDialog::deleteClicked(), RegisteredUsersDialog::editGroup(), RegisteredUsersDialog::fillList(), and ChannelsJoinDialog::fillListView().
template<class Key, class T> KviPointerHashTableEntry<Key,T>* KviPointerHashTable< Key, T >::nextEntry () inline
Places the hash table iterator at the next entry and returns it.
This function must be preceeded by a call to firstEntry(), first() or findRef().
Returns:
KviPointerHashTableEntry<Key,T> *
Referenced by KviPointerHashTable< QString, KviActionCategory >::copyFrom(), RegisteredUsersDialog::exportClicked(), KviPointerHashTable< QString, KviActionCategory >::insert(), and RegisteredUsersDialog::rightButtonPressed().
template<class Key, class T> T* KviPointerHashTable< Key, T >::operator[] (const Key & hKey) inline
Returns the item associated to the key hKey.
Returns NULL if no such item exists in the hash table. Places the hash table iterator at the position of the item found. This is an alias to find().
Parameters:
hKey The key to find
Returns:
T *
template<class Key, class T> bool KviPointerHashTable< Key, T >::remove (const Key & hKey) inline
Removes the item pointer associated to the key hKey, if such an item exists in the hash table.
The item is deleted if autodeletion is enabled. Returns true if the item was found and removed and false if it wasn't found. Invalidates the hash table iterator.
Parameters:
hKey The key where to remove the pointer
Returns:
bool
Referenced by KviActionManager::actionDestroyed(), PluginManager::checkUnload(), KviSharedFilesManager::cleanup(), KviAvatarCache::cleanup(), KviConfigurationFile::clearGroup(), KviConfigurationFile::clearKey(), PopupEditorWidget::commit(), config_kvs_cmd_close(), KviKvsTimerManager::deleteTimer(), KviCustomToolBarManager::destroyDescriptor(), KviKvsObject::disconnectSignal(), KviKvsDnsManager::dnsLookupTerminated(), RegisteredUserEntryDialog::editAllPropertiesClicked(), RegisteredUsersDialog::editGroup(), KviCustomToolBar::filteredChildDestroyed(), DccBroker::findZeroPortTag(), KviKvsTreeNodeSwitchList::getStandardRebindingSwitch(), KviWatchNotifyListManager::handleWatchReply(), RegisteredUserEntryDialog::okClicked(), KviUserListView::partInternal(), KviKvsObject::registerPrivateImplementation(), KviAvatarCache::remove(), KviRegisteredUserDataBase::removeGroup(), KviRegisteredUserDataBase::removeMaskByPointer(), KviSharedFilesManager::removeSharedFile(), KviRegisteredUserDataBase::removeUser(), KviIrcUserDataBase::removeUser(), DccBroker::removeZeroPortTag(), KviCustomToolBarManager::renameDescriptor(), KviRegisteredUser::setProperty(), texticons_kvs_cmd_set(), PluginManager::unloadAll(), KviLocale::unloadCatalogue(), KviModuleManager::unloadModule(), KviActionManager::unregisterAction(), KviKvsScriptAddonManager::unregisterAddon(), KviKvsObjectController::unregisterClass(), KviModuleExtensionManager::unregisterExtensionsByModule(), KviKvsObjectController::unregisterObject(), DccDescriptor::~DccDescriptor(), and OptionsDialog::~OptionsDialog().
template<class Key, class T> bool KviPointerHashTable< Key, T >::removeRef (const T * pRef) inline
Removes the first occurence of the item pointer pRef.
The item is deleted if autodeletion is enabled. Returns true if the pointer was found and false otherwise. Invalidates the hash table iterator.
Parameters:
pRef The pointer to remove the first occurence
Returns:
bool
Referenced by ClassEditorWidget::removeItem(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), and ClassEditorWidget::renameNamespace().
template<class Key, class T> void KviPointerHashTable< Key, T >::replace (const Key & hKey, T * pData) inline
Inserts the item pData at the position specified by the key hKey.
Replaces any previous item with the same key. The replaced item is deleted if autodelete is enabled. The hash table iterator is placed at the newly inserted item. This is just an alias to insert() with a different name.
Parameters:
hKey The key where to insert data
pData The new data to insert
Returns:
void
Referenced by KviKvsPopupManager::add(), KviKvsAliasManager::add(), KviKvsDnsManager::addDns(), KviRegisteredUserDataBase::addGroup(), KviPackageWriter::addInfoField(), KviKvsSwitchList::addLong(), KviKvsTreeNodeSwitchList::addLong(), KviIrcServerDataBase::addNetwork(), KviSharedFilesManager::addSharedFile(), KviKvsSwitchList::addShort(), KviKvsTreeNodeSwitchList::addShort(), KviRegisteredUserDataBase::addUser(), KviIsOnNotifyListManager::buildRegUserDict(), KviWatchNotifyListManager::buildRegUserDict(), KviLocale::codecForName(), DccDescriptor::copyFrom(), KviUserIdentityManager::copyFrom(), KviCustomToolBarManager::create(), DccDescriptor::DccDescriptor(), KviUserIdentityManager::defaultIdentity(), KviKvsScriptAddonManager::delayedLoad(), RegisteredUserEntryDialog::editAllPropertiesClicked(), KviActionDrawer::fill(), KviKvsHash::get(), KviIconManager::getSmallIconIdFromName(), KviRegisteredUserDataBase::getUser(), KviTextIconManager::insert(), KviKvsHash::KviKvsHash(), KviKvsModuleInterface::kvsRegisterCallbackCommand(), KviKvsModuleInterface::kvsRegisterFunction(), KviKvsModuleInterface::kvsRegisterSimpleCommand(), KviCustomToolBarManager::load(), KviConfigurationFile::load(), KviAvatarCache::load(), KviUserIdentityManager::load(), KviTextIconManager::load(), KviIrcServerDataBase::makeCurrentServer(), RegisteredUserPropertiesDialog::okClicked(), KviKvsParser::parseSpecialCommandGlobal(), KviHttpRequest::processHeader(), KviPackageReader::readHeaderInternal(), KviKvsScriptAddonManager::registerAddon(), KviStatusBar::registerAppletDescriptor(), KviKvsObjectClass::registerFunctionHandler(), KviKvsObject::registerPrivateImplementation(), KviKvsObjectClass::registerStandardFalseReturnFunctionHandler(), KviKvsObjectClass::registerStandardNothingReturnFunctionHandler(), KviKvsObjectClass::registerStandardTrueReturnFunctionHandler(), KviCustomToolBarManager::renameDescriptor(), KviAvatarCache::replace(), KviRegisteredUser::setProperty(), and KviConfigurationFile::writeEntry().
template<class Key, class T> void KviPointerHashTable< Key, T >::setAutoDelete (bool bAutoDelete) inline
Enables or disabled the autodeletion feature.
Items are deleted upon removal when the feature is enabled.
Parameters:
bAutoDelete Set the autodelete state
Returns:
void
Referenced by KviKvsDnsManager::addDns(), KviKvsSwitchList::addLong(), KviKvsTreeNodeSwitchList::addLong(), KviKvsSwitchList::addShort(), KviKvsTreeNodeSwitchList::addShort(), KviCustomToolBar::beginCustomize(), KviApplication::buildRecentChannels(), ClassEditorWidget::ClassEditorWidget(), KviIrcUserDataBase::clear(), KviConfigurationFile::clear(), KviKvsObjectController::clearInstances(), PopupEditorWidget::commit(), config_module_init(), KviKvsObject::connectSignal(), DccDescriptor::copyFrom(), ClassEditorWidget::currentItemChanged(), DccBroker::DccBroker(), DccDescriptor::DccDescriptor(), RegisteredUsersDialog::editGroup(), KviActionDrawer::fill(), RegisteredUsersDialog::fillList(), KviChannelWindow::getChannelActivityStats(), KviConfigurationFile::getCurrentGroup(), KviIconManager::getSmallIconIdFromName(), KviKvsTreeNodeSwitchList::getStandardRebindingSwitch(), KviActionManager::KviActionManager(), KviAvatarCache::KviAvatarCache(), KviConfigurationFile::KviConfigurationFile(), KviCustomToolBarManager::KviCustomToolBarManager(), KviIconManager::KviIconManager(), KviIrcServerDataBase::KviIrcServerDataBase(), KviIrcUserDataBase::KviIrcUserDataBase(), KviIsOnNotifyListManager::KviIsOnNotifyListManager(), KviKvsAliasManager::KviKvsAliasManager(), KviKvsHash::KviKvsHash(), KviKvsKernel::KviKvsKernel(), KviKvsModuleInterface::KviKvsModuleInterface(), KviKvsObjectClass::KviKvsObjectClass(), KviKvsObjectController::KviKvsObjectController(), KviKvsPopupManager::KviKvsPopupManager(), KviKvsScriptAddonManager::KviKvsScriptAddonManager(), KviKvsTimerManager::KviKvsTimerManager(), KviLocale::KviLocale(), KviMessageCatalogue::KviMessageCatalogue(), KviModuleExtensionManager::KviModuleExtensionManager(), KviModuleManager::KviModuleManager(), KviPackageIOEngine::KviPackageIOEngine(), KviRegisteredUserDataBase::KviRegisteredUserDataBase(), KviSharedFilesManager::KviSharedFilesManager(), KviSoundPlayer::KviSoundPlayer(), KviStatusBar::KviStatusBar(), KviTextIconManager::KviTextIconManager(), KviUserIdentityManager::KviUserIdentityManager(), KviUserListView::KviUserListView(), KviWatchNotifyListManager::KviWatchNotifyListManager(), KviConfigurationFile::load(), KviMessageCatalogue::load(), objects_kvs_fnc_classes(), options_module_init(), KviKvsParser::parseSpecialCommandGlobal(), perlcore_module_init(), PluginManager::PluginManager(), KviHttpRequest::processHeader(), pythoncore_module_init(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), KviKvsObject::registerPrivateImplementation(), KviCustomToolBarManager::renameDescriptor(), KviRegisteredUser::setProperty(), KviKvsScriptAddonManager::unregisterAddon(), and KviKvsTimerManager::~KviKvsTimerManager().
Friends And Related Function Documentation
template<class Key, class T> friend class KviPointerHashTableIterator< Key, T > friend
Member Data Documentation
template<class Key, class T> bool KviPointerHashTable< Key, T >::m_bAutoDelete protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::clear(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable(), KviPointerHashTable< QString, KviActionCategory >::remove(), KviPointerHashTable< QString, KviActionCategory >::removeRef(), and KviPointerHashTable< QString, KviActionCategory >::setAutoDelete().
template<class Key, class T> bool KviPointerHashTable< Key, T >::m_bCaseSensitive protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::find(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable(), and KviPointerHashTable< QString, KviActionCategory >::remove().
template<class Key, class T> bool KviPointerHashTable< Key, T >::m_bDeepCopyKeys protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::clear(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable(), KviPointerHashTable< QString, KviActionCategory >::remove(), and KviPointerHashTable< QString, KviActionCategory >::removeRef().
template<class Key, class T> KviPointerList<KviPointerHashTableEntry<Key,T> >** KviPointerHashTable< Key, T >::m_pDataArray protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::clear(), KviPointerHashTable< QString, KviActionCategory >::current(), KviPointerHashTable< QString, KviActionCategory >::currentEntry(), KviPointerHashTable< QString, KviActionCategory >::currentKey(), KviPointerHashTable< QString, KviActionCategory >::find(), KviPointerHashTable< QString, KviActionCategory >::findRef(), KviPointerHashTable< QString, KviActionCategory >::first(), KviPointerHashTable< QString, KviActionCategory >::firstEntry(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable(), KviPointerHashTable< QString, KviActionCategory >::next(), KviPointerHashTable< QString, KviActionCategory >::nextEntry(), KviPointerHashTable< QString, KviActionCategory >::remove(), KviPointerHashTable< QString, KviActionCategory >::removeRef(), and KviPointerHashTable< QString, KviActionCategory >::~KviPointerHashTable().
template<class Key, class T> unsigned int KviPointerHashTable< Key, T >::m_uCount protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::clear(), KviPointerHashTable< QString, KviActionCategory >::count(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::isEmpty(), KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable(), KviPointerHashTable< QString, KviActionCategory >::remove(), and KviPointerHashTable< QString, KviActionCategory >::removeRef().
template<class Key, class T> unsigned int KviPointerHashTable< Key, T >::m_uIteratorIdx protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::current(), KviPointerHashTable< QString, KviActionCategory >::currentEntry(), KviPointerHashTable< QString, KviActionCategory >::currentKey(), KviPointerHashTable< QString, KviActionCategory >::find(), KviPointerHashTable< QString, KviActionCategory >::findRef(), KviPointerHashTable< QString, KviActionCategory >::first(), KviPointerHashTable< QString, KviActionCategory >::firstEntry(), KviPointerHashTable< QString, KviActionCategory >::next(), and KviPointerHashTable< QString, KviActionCategory >::nextEntry().
template<class Key, class T> unsigned int KviPointerHashTable< Key, T >::m_uSize protected
Referenced by KviPointerHashTable< QString, KviActionCategory >::clear(), KviPointerHashTable< QString, KviActionCategory >::current(), KviPointerHashTable< QString, KviActionCategory >::currentEntry(), KviPointerHashTable< QString, KviActionCategory >::currentKey(), KviPointerHashTable< QString, KviActionCategory >::find(), KviPointerHashTable< QString, KviActionCategory >::findRef(), KviPointerHashTable< QString, KviActionCategory >::first(), KviPointerHashTable< QString, KviActionCategory >::firstEntry(), KviPointerHashTable< QString, KviActionCategory >::insert(), KviPointerHashTable< QString, KviActionCategory >::KviPointerHashTable(), KviPointerHashTable< QString, KviActionCategory >::next(), KviPointerHashTable< QString, KviActionCategory >::nextEntry(), KviPointerHashTable< QString, KviActionCategory >::remove(), and KviPointerHashTable< QString, KviActionCategory >::removeRef().
The documentation for this class was generated from the following file:
src/kvilib/core/KviPointerHashTable.h