KVIrc: KvsObject_widget Class Reference
KvsObject_widget Class Reference
#include <KvsObject_widget.h>
Signals
void aboutToDie ()
Public Member Functions
QWidget * widget ()
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Protected Member Functions
bool addWidgetToWrappedLayout (KviKvsObjectFunctionCall *c)
bool backgroundColor (KviKvsObjectFunctionCall *c)
bool centerToScreen (KviKvsObjectFunctionCall *c)
bool colorPalette (KviKvsObjectFunctionCall *c)
virtual bool eventFilter (QObject *o, QEvent *e)
bool fontAscent (KviKvsObjectFunctionCall *c)
bool fontDescent (KviKvsObjectFunctionCall *c)
bool fontMetricsHeight (KviKvsObjectFunctionCall *c)
bool fontMetricsLineSpacing (KviKvsObjectFunctionCall *c)
bool fontMetricsWidth (KviKvsObjectFunctionCall *c)
bool foregroundColor (KviKvsObjectFunctionCall *c)
bool geometry (KviKvsObjectFunctionCall *c)
bool globalCursorX (KviKvsObjectFunctionCall *c)
bool globalCursorY (KviKvsObjectFunctionCall *c)
bool grab (KviKvsObjectFunctionCall *)
bool hasFocus (KviKvsObjectFunctionCall *c)
bool height (KviKvsObjectFunctionCall *)
bool hide (KviKvsObjectFunctionCall *)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertIntoStatusBar (KviKvsObjectFunctionCall *c)
bool isEnabled (KviKvsObjectFunctionCall *c)
bool isTopLevel (KviKvsObjectFunctionCall *c)
bool isVisible (KviKvsObjectFunctionCall *c)
bool loadInterface (KviKvsObjectFunctionCall *c)
bool lower (KviKvsObjectFunctionCall *)
bool mapFromGlobal (KviKvsObjectFunctionCall *c)
bool mapToGlobal (KviKvsObjectFunctionCall *c)
bool move (KviKvsObjectFunctionCall *c)
bool parentWidget (KviKvsObjectFunctionCall *c)
bool raise (KviKvsObjectFunctionCall *)
bool removeFromStatusBar (KviKvsObjectFunctionCall *c)
bool repaint (KviKvsObjectFunctionCall *c)
bool resize (KviKvsObjectFunctionCall *c)
bool screenResolution (KviKvsObjectFunctionCall *c)
bool setAttribute (KviKvsObjectFunctionCall *c)
bool setBackgroundColor (KviKvsObjectFunctionCall *c)
bool setBackgroundImage (KviKvsObjectFunctionCall *c)
bool setEnabled (KviKvsObjectFunctionCall *c)
bool setFocus (KviKvsObjectFunctionCall *c)
bool setFocusPolicy (KviKvsObjectFunctionCall *c)
bool setFont (KviKvsObjectFunctionCall *c)
bool setForegroundColor (KviKvsObjectFunctionCall *c)
bool setGeometry (KviKvsObjectFunctionCall *c)
bool setKeyShortcut (KviKvsObjectFunctionCall *c)
bool setMask (KviKvsObjectFunctionCall *c)
bool setMaximumHeight (KviKvsObjectFunctionCall *c)
bool setMaximumWidth (KviKvsObjectFunctionCall *c)
bool setMinimumHeight (KviKvsObjectFunctionCall *c)
bool setMinimumWidth (KviKvsObjectFunctionCall *c)
bool setMouseTracking (KviKvsObjectFunctionCall *c)
bool setParent (KviKvsObjectFunctionCall *c)
bool setStyleSheet (KviKvsObjectFunctionCall *c)
bool setToolTip (KviKvsObjectFunctionCall *)
bool setWFlags (KviKvsObjectFunctionCall *c)
bool setWindowIcon (KviKvsObjectFunctionCall *c)
bool setWindowTitle (KviKvsObjectFunctionCall *c)
bool show (KviKvsObjectFunctionCall *c)
bool sizeHint (KviKvsObjectFunctionCall *c)
bool update (KviKvsObjectFunctionCall *c)
bool width (KviKvsObjectFunctionCall *)
bool windowTitle (KviKvsObjectFunctionCall *c)
bool x (KviKvsObjectFunctionCall *)
bool y (KviKvsObjectFunctionCall *)
Protected Member Functions inherited from KviKvsObject
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
KviKvsRunTimeContext * m_pContext
QGraphicsDropShadowEffect * pGraphicsEffect
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Additional Inherited Members
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Member Function Documentation
void KvsObject_widget::aboutToDie () signal
bool KvsObject_widget::addWidgetToWrappedLayout (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::backgroundColor (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::centerToScreen (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::colorPalette (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::eventFilter (QObject * o, QEvent * e) protected virtual
Reimplemented from KviKvsObject.
References KviKvsObjectClass::allocateInstance(), KviKvsVariantList::append(), KviKvsVariant::asBoolean(), KviKvsVariant::asString(), KviKvsObject::callFunction(), KviKvsObject::dieNow(), e, KviKvsObject::handle(), height(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), KviKvsObjectController::lookupObject(), m_pContext, KviKvsKernel::objectController(), p, widget(), width(), x(), and y().
bool KvsObject_widget::fontAscent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::fontDescent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::fontMetricsHeight (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::fontMetricsLineSpacing (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::fontMetricsWidth (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::foregroundColor (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::geometry (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::globalCursorX (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::globalCursorY (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::grab (KviKvsObjectFunctionCall *) protected
bool KvsObject_widget::hasFocus (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::height (KviKvsObjectFunctionCall *) protected
Referenced by eventFilter().
bool KvsObject_widget::hide (KviKvsObjectFunctionCall *) protected
bool KvsObject_widget::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) protected virtual
Reimplemented from KviKvsObject.
Reimplemented in KvsObject_window, KvsObject_tableWidget, KvsObject_lineEdit, KvsObject_popupMenu, KvsObject_wizard, KvsObject_dateTimeEdit, KvsObject_treeWidget, KvsObject_wrapper, KvsObject_checkBox, KvsObject_colorDialog, KvsObject_comboBox, KvsObject_button, KvsObject_groupBox, KvsObject_spinBox, KvsObject_textBrowser, KvsObject_toolButton, KvsObject_lcd, KvsObject_listWidget, KvsObject_textedit, KvsObject_label, KvsObject_mainWindow, KvsObject_progressBar, KvsObject_radioButton, KvsObject_slider, KvsObject_tabWidget, KvsObject_vBox, KvsObject_workspace, KvsObject_dialog, KvsObject_menuBar, KvsObject_toolBar, KvsObject_dockWindow, and KvsObject_hBox.
References c.
bool KvsObject_widget::insertIntoStatusBar (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::isEnabled (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::isTopLevel (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::isVisible (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::loadInterface (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::lower (KviKvsObjectFunctionCall *) protected
bool KvsObject_widget::mapFromGlobal (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::mapToGlobal (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::move (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::parentWidget (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::raise (KviKvsObjectFunctionCall *) protected
bool KvsObject_widget::removeFromStatusBar (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::repaint (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::resize (KviKvsObjectFunctionCall * c) protected
Reimplemented in KvsObject_file.
bool KvsObject_widget::screenResolution (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setAttribute (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setBackgroundColor (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setBackgroundImage (KviKvsObjectFunctionCall * c) protected
Reimplemented in KvsObject_treeWidget.
bool KvsObject_widget::setEnabled (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setFocus (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setFocusPolicy (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setFont (KviKvsObjectFunctionCall * c) protected
Reimplemented in KvsObject_listWidget.
bool KvsObject_widget::setForegroundColor (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setGeometry (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setKeyShortcut (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setMask (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setMaximumHeight (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setMaximumWidth (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setMinimumHeight (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setMinimumWidth (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setMouseTracking (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setParent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setStyleSheet (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setToolTip (KviKvsObjectFunctionCall *) protected
Reimplemented in KvsObject_tableWidget.
bool KvsObject_widget::setWFlags (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setWindowIcon (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::setWindowTitle (KviKvsObjectFunctionCall * c) protected
Reimplemented in KvsObject_window.
bool KvsObject_widget::show (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::sizeHint (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::update (KviKvsObjectFunctionCall * c) protected
QWidget* KvsObject_widget::widget () inline
Reimplemented in KvsObject_window, KvsObject_tableWidget, KvsObject_popupMenu, KvsObject_dateTimeEdit, KvsObject_lineEdit, KvsObject_treeWidget, KvsObject_wrapper, KvsObject_checkBox, KvsObject_colorDialog, KvsObject_comboBox, KvsObject_button, KvsObject_groupBox, KvsObject_spinBox, KvsObject_textBrowser, KvsObject_toolButton, KvsObject_lcd, KvsObject_listWidget, KvsObject_textedit, KvsObject_label, KvsObject_mainWindow, KvsObject_progressBar, KvsObject_radioButton, KvsObject_slider, KvsObject_tabWidget, KvsObject_vBox, KvsObject_wizard, KvsObject_dialog, KvsObject_menuBar, KvsObject_toolBar, KvsObject_workspace, and KvsObject_hBox.
References KviKvsObject::object().
Referenced by eventFilter().
bool KvsObject_widget::width (KviKvsObjectFunctionCall *) protected
Referenced by eventFilter().
bool KvsObject_widget::windowTitle (KviKvsObjectFunctionCall * c) protected
bool KvsObject_widget::x (KviKvsObjectFunctionCall *) protected
Referenced by eventFilter().
bool KvsObject_widget::y (KviKvsObjectFunctionCall *) protected
Referenced by eventFilter().
Member Data Documentation
KviKvsRunTimeContext* KvsObject_widget::m_pContext protected
Reimplemented in KvsObject_tableWidget.
Referenced by eventFilter().
QGraphicsDropShadowEffect* KvsObject_widget::pGraphicsEffect protected
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_widget.h
src/modules/objects/KvsObject_widget.cpp