KVIrc: LogViewWindow Class Reference
LogViewWindow Class Reference
#include <LogViewWindow.h>
Public Member Functions
void createLog (LogFile *pLog, int iId, QString *pszFile=0)
Exports the log and creates the file in the selected format.
LogViewWindow ()
~LogViewWindow ()
Public Member Functions inherited from KviWindow
void activateSelf ()
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual void applyOptions ()
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getBaseLogFileName (QString &szBuffer)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual void ownAction (const QString &)
virtual void ownMessage (const QString &, bool=true)
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
virtual const QString & target ()
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Protected Slots
void abortFilter ()
void applyFilter ()
void cacheFileList ()
void deleteCurrent ()
void exportLog (QAction *pAction)
void filterNext ()
void itemSelected (QTreeWidgetItem *pItem, QTreeWidgetItem *)
void rightButtonClicked (QTreeWidgetItem *, const QPoint &)
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual void die ()
void exportLog (int iId)
virtual void fillCaptionBuffers ()
virtual void keyPressEvent (QKeyEvent *pEvent)
virtual QPixmap * myIconPtr ()
void recurseDirectory (const QString &szDir)
virtual void resizeEvent (QResizeEvent *pEvent)
void setupItemList ()
virtual QSize sizeHint () const
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
virtual void closeEvent (QCloseEvent *pEvent)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void loadProperties (KviConfigurationFile *pCfg)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual void preprocessMessage (QString &szMessage)
virtual void saveProperties (KviConfigurationFile *pCfg)
void setType (Type eType)
virtual void triggerCreationEvents ()
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
bool m_bAborted
KviPointerList< LogFile > m_logList
KviTalHBox * m_pBottomLayout
QPushButton * m_pCancelButton
QLineEdit * m_pContentsMask
QCheckBox * m_pEnableFromFilter
QCheckBox * m_pEnableToFilter
QMenu * m_pExportLogPopup
QLineEdit * m_pFileNameMask
QStringList * m_pFileNames
QPushButton * m_pFilterButton
QDateEdit * m_pFromDateEdit
KviTalVBox * m_pIndexTab
LogListViewItem * m_pLastCategory
LogListViewItemFolder * m_pLastGroupItem
KviTalVBox * m_pLeftLayout
LogViewListView * m_pListView
QProgressBar * m_pProgressBar
QWidget * m_pSearchTab
QCheckBox * m_pShowChannelsCheck
QCheckBox * m_pShowConsolesCheck
QCheckBox * m_pShowDccChatCheck
QCheckBox * m_pShowOtherCheck
QCheckBox * m_pShowQueryesCheck
QTabWidget * m_pTabWidget
QTimer * m_pTimer
QDateEdit * m_pToDateEdit
QString m_szLastGroup
Protected Attributes inherited from KviWindow
bool m_bIsDocked
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Additional Inherited Members
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void maximize ()
void minimize ()
void reloadImages ()
void restore ()
void savePropertiesAsDefault ()
void undock ()
Signals inherited from KviWindow
void windowNameChanged ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Constructor & Destructor Documentation
LogViewWindow::LogViewWindow ()
References __tr2qs_ctx(), abortFilter(), applyFilter(), cacheFileList(), connect(), exportLog(), filterNext(), LogFile::HTML, itemSelected(), KviTalSplitter, m_pBottomLayout, m_pCancelButton, m_pContentsMask, m_pEnableFromFilter, m_pEnableToFilter, m_pExportLogPopup, m_pFileNameMask, m_pFilterButton, m_pFromDateEdit, m_pIndexTab, KviWindow::m_pIrcView, m_pLeftLayout, m_pListView, m_pProgressBar, m_pSearchTab, m_pShowChannelsCheck, m_pShowConsolesCheck, m_pShowDccChatCheck, m_pShowOtherCheck, m_pShowQueryesCheck, KviWindow::m_pSplitter, m_pTabWidget, m_pTimer, m_pToDateEdit, LogFile::PlainText, rightButtonClicked(), and KviIrcView::setMaxBufferSize().
LogViewWindow::~LogViewWindow ()
Member Function Documentation
void LogViewWindow::abortFilter () protected slot
References m_bAborted.
Referenced by LogViewWindow().
void LogViewWindow::applyFilter () protected slot
References setupItemList().
Referenced by LogViewWindow().
void LogViewWindow::cacheFileList () protected slot
References g_pApp, KviApplication::getLocalKvircDirectory(), KviApplication::Log, recurseDirectory(), and setupItemList().
Referenced by LogViewWindow().
void LogViewWindow::createLog (LogFile * pLog, int iId, QString * pszFile = 0)
Exports the log and creates the file in the selected format.
Parameters
pLog The log file associated with the item selected in the popup
iId The id of the item in the popup
pszFile The buffer to store the exported log name
Returns
void
References __tr2qs_ctx(), KviFileUtils::adjustFilePath(), KviFileDialog::askForSaveFileName(), LogFile::Channel, LogFile::Console, KviHtmlGenerator::convertToHtml(), KviFileUtils::copyFile(), LogFile::date(), LogFile::DccChat, KviFileUtils::directoryExists(), KviQString::ensureLastCharIs(), g_pApp, g_pIconManager, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviIconManager::getSmallIconResourceName(), LogFile::getText(), LogFile::HTML, i, KVI_OPTION_MSGTYPE, KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KVI_RELEASE_NAME, KVI_VERSION, KviOption_stringIconThemeSubdir, KviOption_stringLogsExportPath, LogFile::name(), LogFile::network(), NULL, LogFile::Other, KviWindow::output(), KviApplication::Pics, KviMessageTypeSettings::pixId(), LogFile::PlainText, LogFile::Query, KviControlCodes::stripControlBytes(), KviApplication::Themes, LogFile::type(), and LogFile::typeString().
Referenced by exportLog(), and logview_module_ctrl().
void LogViewWindow::deleteCurrent () protected slot
References __tr2qs, __tr2qs_ctx(), KviPointerList< T >::append(), KviPointerList< T >::at(), KviIrcView::clearBuffer(), KviPointerList< T >::count(), LogListViewItem::fileName(), i, j, KviWindow::m_pIrcView, m_pListView, KviFileUtils::removeFile(), KviPointerList< T >::setAutoDelete(), and u.
Referenced by rightButtonClicked().
void LogViewWindow::die () protected virtual
References close().
void LogViewWindow::exportLog (int iId) protected
References KviPointerList< T >::append(), KviPointerList< T >::at(), KviPointerList< T >::count(), createLog(), i, j, LogListViewItem::log(), m_pListView, KviPointerList< T >::setAutoDelete(), and u.
Referenced by exportLog(), and LogViewWindow().
void LogViewWindow::exportLog (QAction * pAction) protected slot
References exportLog().
void LogViewWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void LogViewWindow::filterNext () protected slot
References __tr2qs_ctx(), LogFile::Channel, LogFile::Console, KviPointerList< T >::current(), LogFile::date(), LogFile::DccChat, LogFile::getText(), i, m_bAborted, LogListViewItem::m_eType, m_logList, m_pBottomLayout, m_pContentsMask, m_pEnableFromFilter, m_pEnableToFilter, m_pFileNameMask, m_pFilterButton, m_pFromDateEdit, m_pLastCategory, m_pLastGroupItem, m_pListView, m_pProgressBar, m_pShowChannelsCheck, m_pShowConsolesCheck, m_pShowDccChatCheck, m_pShowOtherCheck, m_pShowQueryesCheck, m_pTimer, m_pToDateEdit, m_szLastGroup, KviQString::matchString(), LogFile::name(), LogFile::network(), KviPointerList< T >::next(), LogFile::Other, pFile, LogFile::Query, szBuffer, and LogFile::type().
Referenced by LogViewWindow().
void LogViewWindow::itemSelected (QTreeWidgetItem * pItem, QTreeWidgetItem *) protected slot
References KviIrcView::clearBuffer(), KVI_NUM_MSGTYPE_OPTIONS, KviWindow::m_pIrcView, KviIrcView::NoRepaint, KviIrcView::NoTimestamp, and KviWindow::outputNoFmt().
Referenced by LogViewWindow().
void LogViewWindow::keyPressEvent (QKeyEvent * pEvent) protected virtual
References KviWindow::m_pIrcView, and KviIrcView::toggleToolWidget().
QPixmap * LogViewWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::Log.
void LogViewWindow::recurseDirectory (const QString & szDir) protected
References KviPointerList< T >::append(), i, and m_logList.
Referenced by cacheFileList().
void LogViewWindow::resizeEvent (QResizeEvent * pEvent) protected virtual
References KviWindow::m_pSplitter.
void LogViewWindow::rightButtonClicked (QTreeWidgetItem * pItem, const QPoint &) protected slot
References __tr2qs_ctx(), deleteCurrent(), g_pIconManager, KviIconManager::getSmallIcon(), m_pExportLogPopup, m_pListView, KviIconManager::Quit, and KviIconManager::UserList.
Referenced by LogViewWindow().
void LogViewWindow::setupItemList () protected
References KviPointerList< T >::count(), KviPointerList< T >::first(), KviPointerList< T >::isEmpty(), m_bAborted, m_logList, m_pBottomLayout, m_pFilterButton, m_pLastCategory, m_pLastGroupItem, m_pListView, m_pProgressBar, and m_pTimer.
Referenced by applyFilter(), and cacheFileList().
QSize LogViewWindow::sizeHint () const protected virtual
References KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviIrcView::sizeHint().
Member Data Documentation
bool LogViewWindow::m_bAborted protected
Referenced by abortFilter(), filterNext(), and setupItemList().
KviPointerList<LogFile> LogViewWindow::m_logList protected
Referenced by filterNext(), recurseDirectory(), and setupItemList().
KviTalHBox* LogViewWindow::m_pBottomLayout protected
Referenced by filterNext(), LogViewWindow(), and setupItemList().
QPushButton* LogViewWindow::m_pCancelButton protected
Referenced by LogViewWindow().
QLineEdit* LogViewWindow::m_pContentsMask protected
Referenced by filterNext(), and LogViewWindow().
QCheckBox* LogViewWindow::m_pEnableFromFilter protected
Referenced by filterNext(), and LogViewWindow().
QCheckBox* LogViewWindow::m_pEnableToFilter protected
Referenced by filterNext(), and LogViewWindow().
QMenu* LogViewWindow::m_pExportLogPopup protected
Referenced by LogViewWindow(), and rightButtonClicked().
QLineEdit* LogViewWindow::m_pFileNameMask protected
Referenced by filterNext(), and LogViewWindow().
QStringList* LogViewWindow::m_pFileNames protected
QPushButton* LogViewWindow::m_pFilterButton protected
Referenced by filterNext(), LogViewWindow(), and setupItemList().
QDateEdit* LogViewWindow::m_pFromDateEdit protected
Referenced by filterNext(), and LogViewWindow().
KviTalVBox* LogViewWindow::m_pIndexTab protected
Referenced by LogViewWindow().
LogListViewItem* LogViewWindow::m_pLastCategory protected
Referenced by filterNext(), and setupItemList().
LogListViewItemFolder* LogViewWindow::m_pLastGroupItem protected
Referenced by filterNext(), and setupItemList().
KviTalVBox* LogViewWindow::m_pLeftLayout protected
Referenced by LogViewWindow().
LogViewListView* LogViewWindow::m_pListView protected
Referenced by deleteCurrent(), exportLog(), filterNext(), LogViewWindow(), rightButtonClicked(), and setupItemList().
QProgressBar* LogViewWindow::m_pProgressBar protected
Referenced by filterNext(), LogViewWindow(), and setupItemList().
QWidget* LogViewWindow::m_pSearchTab protected
Referenced by LogViewWindow().
QCheckBox* LogViewWindow::m_pShowChannelsCheck protected
Referenced by filterNext(), and LogViewWindow().
QCheckBox* LogViewWindow::m_pShowConsolesCheck protected
Referenced by filterNext(), and LogViewWindow().
QCheckBox* LogViewWindow::m_pShowDccChatCheck protected
Referenced by filterNext(), and LogViewWindow().
QCheckBox* LogViewWindow::m_pShowOtherCheck protected
Referenced by filterNext(), and LogViewWindow().
QCheckBox* LogViewWindow::m_pShowQueryesCheck protected
Referenced by filterNext(), and LogViewWindow().
QTabWidget* LogViewWindow::m_pTabWidget protected
Referenced by LogViewWindow().
QTimer* LogViewWindow::m_pTimer protected
Referenced by filterNext(), LogViewWindow(), and setupItemList().
QDateEdit* LogViewWindow::m_pToDateEdit protected
Referenced by filterNext(), and LogViewWindow().
QString LogViewWindow::m_szLastGroup protected
Referenced by filterNext().
The documentation for this class was generated from the following files:
src/modules/logview/LogViewWindow.h
src/modules/logview/LogViewWindow.cpp