KVIrc: OptionsWidget_servers Class Reference
OptionsWidget_servers Class Reference
#include <OptionsWidget_servers.h>
Public Member Functions
virtual void commit ()
OptionsWidget_servers (QWidget *parent)
~OptionsWidget_servers ()
Public Member Functions inherited from KviOptionsWidget
void addAdvancedButton (int x1, int y1, int x2, int y2)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void clearList ()
void connectCurrentClicked ()
void copyServer ()
void currentItemChanged (QTreeWidgetItem *cur, QTreeWidgetItem *prev)
void customContextMenuRequested (const QPoint &pnt)
void detailsClicked ()
void filterTextEdited (const QString &szNewText)
void importerDead ()
void importPopupAboutToShow ()
void importPopupActivated (QAction *pAction)
void importServer (const KviIrcServer &s, const QString &network)
void itemDoubleClicked (QTreeWidgetItem *, int)
void newNetwork ()
void newServer ()
void pasteServer ()
void recentServersPopupAboutToShow ()
void recentServersPopupClicked (QAction *pAction)
void removeCurrent ()
void serverNetworkEditTextEdited (const QString &szNewText)
void slotShowThisDialogAtStartupSelectorDestroyed ()
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
void switchToAdvancedPage ()
Protected Attributes
KviIrcServer * m_pClipboard
QPushButton * m_pConnectCurrent
QPushButton * m_pConnectNew
QMenu * m_pContextPopup
QToolButton * m_pCopyServerButton
QPushButton * m_pDetailsButton
QLineEdit * m_pFilterEdit
QLabel * m_pFilterLabel
QToolButton * m_pImportButton
KviMexServerImport * m_pImportFilter
QMenu * m_pImportPopup
IrcServerOptionsTreeWidgetItem * m_pLastEditedItem
IrcNetworkDetailsWidget * m_pNetworkDetailsDialog
QToolButton * m_pNewNetworkButton
QToolButton * m_pNewServerButton
QToolButton * m_pPasteServerButton
QMenu * m_pRecentPopup
QToolButton * m_pRemoveButton
IrcServerDetailsWidget * m_pServerDetailsDialog
KviBoolSelector * m_pShowThisDialogAtStartupSelector
QLineEdit * m_pSrvNetEdit
QLabel * m_pSrvNetLabel
QTreeWidget * m_pTreeWidget
Private Member Functions
void fillServerList ()
IrcServerOptionsTreeWidgetItem * findNetItem (const QString &netname)
void saveLastItem ()
void selectBestServerByUrl (const QString &szUrl)
Additional Inherited Members
Signals inherited from KviOptionsWidget
void wantToSwitchToAdvancedPage (KviOptionsWidget *)
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_servers::OptionsWidget_servers (QWidget * parent)
References __tr2qs_ctx(), KviTalToolTip::add(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addWidgetToLayout(), connect(), connectCurrentClicked(), KviIconManager::Copy, copyServer(), KviOptionsWidget::createLayout(), currentItemChanged(), customContextMenuRequested(), KviIconManager::Cut, detailsClicked(), f, fillServerList(), filterTextEdited(), KviIconManager::Folder, g_pIconManager, KviIconManager::getSmallIcon(), importPopupAboutToShow(), importPopupActivated(), itemDoubleClicked(), KviOption_boolShowServersConnectDialogOnStart, KviOptionsWidget::layout(), m_pClipboard, m_pConnectCurrent, m_pContextPopup, m_pCopyServerButton, m_pDetailsButton, m_pFilterEdit, m_pFilterLabel, m_pImportButton, m_pImportFilter, m_pImportPopup, m_pLastEditedItem, m_pNetworkDetailsDialog, m_pNewNetworkButton, m_pNewServerButton, m_pPasteServerButton, m_pRecentPopup, m_pRemoveButton, m_pServerDetailsDialog, m_pShowThisDialogAtStartupSelector, m_pSrvNetEdit, m_pSrvNetLabel, m_pTreeWidget, newNetwork(), newServer(), NULL, KviIconManager::Paste, pasteServer(), recentServersPopupAboutToShow(), recentServersPopupClicked(), removeCurrent(), KviIconManager::Server, serverNetworkEditTextEdited(), OptionsWidgetContainer::setLeftCornerWidget(), slotShowThisDialogAtStartupSelectorDestroyed(), KviIconManager::Time, and KviIconManager::World.
OptionsWidget_servers::~OptionsWidget_servers ()
References KviMexServerImport::die(), m_pClipboard, m_pImportFilter, m_pNetworkDetailsDialog, and m_pServerDetailsDialog.
Member Function Documentation
void OptionsWidget_servers::clearList () protected slot
References currentItemChanged(), m_pLastEditedItem, and m_pTreeWidget.
Referenced by customContextMenuRequested().
void OptionsWidget_servers::commit (void) virtual
Reimplemented from KviOptionsWidget.
References KviIrcServerDataBase::addNetwork(), KviIrcServerDataBase::clear(), KviIrcNetwork::copyFrom(), KviIrcServerDataBase::findNetwork(), KviIrcNetwork::findServer(), g_pApp, g_pServerDataBase, KviIrcServer::generateUniqueId(), KviIrcServer::hostName(), i, KviIrcServer::id(), KviIrcNetwork::insertServer(), j, m_pLastEditedItem, IrcServerOptionsTreeWidgetItem::m_pNetworkData, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pTreeWidget, KviIrcNetwork::name(), KviApplication::saveIrcServerDataBase(), saveLastItem(), KviIrcServerDataBase::setCurrentNetwork(), and KviIrcNetwork::setCurrentServer().
Referenced by connectCurrentClicked().
void OptionsWidget_servers::connectCurrentClicked () protected slot
References KviApplication::activeConsole(), commit(), g_pApp, KviCString::isEmpty(), m_pSrvNetEdit, KviIrcUrl::run(), and saveLastItem().
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::copyServer () protected slot
References m_pClipboard, m_pLastEditedItem, m_pPasteServerButton, and IrcServerOptionsTreeWidgetItem::m_pServerData.
Referenced by customContextMenuRequested(), and OptionsWidget_servers().
void OptionsWidget_servers::currentItemChanged (QTreeWidgetItem * cur, QTreeWidgetItem * prev) protected slot
References __tr2qs_ctx(), KviIrcServer::hostName(), m_pConnectCurrent, m_pCopyServerButton, m_pDetailsButton, m_pLastEditedItem, m_pRemoveButton, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pSrvNetEdit, m_pSrvNetLabel, and saveLastItem().
Referenced by clearList(), and OptionsWidget_servers().
void OptionsWidget_servers::customContextMenuRequested (const QPoint & pnt) protected slot
References __tr2qs_ctx(), clearList(), KviIconManager::Copy, copyServer(), KviIconManager::Cut, g_pIconManager, KviIconManager::getSmallIcon(), m_pClipboard, m_pContextPopup, m_pImportPopup, m_pTreeWidget, newNetwork(), newServer(), KviIconManager::Paste, pasteServer(), removeCurrent(), KviIconManager::Server, and KviIconManager::World.
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::detailsClicked () protected slot
References IrcNetworkDetailsWidget::fillData(), IrcServerDetailsWidget::fillData(), m_pLastEditedItem, IrcServerOptionsTreeWidgetItem::m_pNetworkData, m_pNetworkDetailsDialog, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pServerDetailsDialog, and saveLastItem().
Referenced by itemDoubleClicked(), and OptionsWidget_servers().
void OptionsWidget_servers::fillServerList () private
References KviPointerHashTableIterator< Key, T >::current(), KviIrcServerDataBase::currentNetworkName(), KviPointerList< T >::first(), g_pIconManager, g_pServerDataBase, KviIconManager::getSmallIcon(), m_pConnectCurrent, m_pTreeWidget, KviPointerList< T >::next(), r, KviIrcServerDataBase::recordDict(), s, KviIconManager::Server, and KviIconManager::World.
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::filterTextEdited (const QString & szNewText) protected slot
References KviIrcNetwork::description(), KviIrcServer::description(), KviIrcServer::hostName(), i, j, m_pFilterEdit, IrcServerOptionsTreeWidgetItem::m_pNetworkData, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pTreeWidget, and KviIrcNetwork::name().
Referenced by OptionsWidget_servers().
IrcServerOptionsTreeWidgetItem * OptionsWidget_servers::findNetItem (const QString & netname) private
References KviQString::equalCI(), i, and m_pTreeWidget.
Referenced by importServer().
void OptionsWidget_servers::importerDead () protected slot
References m_pImportFilter.
Referenced by importPopupActivated().
void OptionsWidget_servers::importPopupAboutToShow () protected slot
References d, KviPointerList< T >::first(), g_pModuleManager, KviModuleExtensionManager::getExtensionList(), KviModuleExtensionManager::instance(), l, KviModuleManager::loadModulesByCaps(), m_pImportPopup, and KviPointerList< T >::next().
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::importPopupActivated (QAction * pAction) protected slot
References __tr2qs_ctx(), KviModuleExtensionManager::allocateExtension(), connect(), KviMexServerImport::die(), g_pModuleManager, KviModuleExtensionManager::getExtensionList(), importerDead(), importServer(), KviModuleExtensionManager::instance(), l, KviModuleManager::loadModulesByCaps(), m_pImportFilter, KviMexServerImport::start(), and KviMessageBox::warning().
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::importServer (const KviIrcServer & s, const QString & network) protected slot
References d, KviQString::equalCI(), findNetItem(), g_pIconManager, KviIconManager::getSmallIcon(), KviIrcServer::hostName(), i, KviIrcServer::ip(), KviIrcServer::isIPv6(), IrcServerOptionsTreeWidgetItem::m_pServerData, m_pTreeWidget, newServer(), KviIrcServer::nickName(), KviIrcServer::password(), KviIrcServer::port(), KviIconManager::Server, KviIrcServer::setIp(), KviIrcServer::setNickName(), KviIrcServer::setPassword(), KviIrcServer::setPort(), KviIrcServer::useSSL(), and KviIconManager::World.
Referenced by importPopupActivated().
void OptionsWidget_servers::itemDoubleClicked (QTreeWidgetItem * , int) protected slot
References detailsClicked().
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::newNetwork () protected slot
References __tr2qs_ctx(), d, g_pIconManager, KviIconManager::getSmallIcon(), m_pTreeWidget, and KviIconManager::World.
Referenced by customContextMenuRequested(), and OptionsWidget_servers().
void OptionsWidget_servers::newServer () protected slot
References __tr2qs_ctx(), g_pIconManager, KviIrcServer::generateUniqueId(), KviIconManager::getSmallIcon(), m_pLastEditedItem, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pTreeWidget, KviIconManager::Server, KviIrcServer::setCacheIp(), and KviIrcServer::setHostName().
Referenced by customContextMenuRequested(), importServer(), and OptionsWidget_servers().
void OptionsWidget_servers::pasteServer () protected slot
References g_pIconManager, KviIrcServer::generateUniqueId(), KviIconManager::getSmallIcon(), m_pClipboard, m_pLastEditedItem, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pTreeWidget, and KviIconManager::Server.
Referenced by customContextMenuRequested(), and OptionsWidget_servers().
void OptionsWidget_servers::recentServersPopupAboutToShow () protected slot
References __tr2qs, KviApplication::fillRecentServersPopup(), g_pApp, and m_pRecentPopup.
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::recentServersPopupClicked (QAction * pAction) protected slot
References __tr2qs, c, KviWindow::console(), g_pActiveWindow, KviIrcUrl::run(), and selectBestServerByUrl().
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::removeCurrent () protected slot
References m_pLastEditedItem, and m_pTreeWidget.
Referenced by customContextMenuRequested(), and OptionsWidget_servers().
void OptionsWidget_servers::saveLastItem () private
References __tr2qs_ctx(), m_pLastEditedItem, IrcServerOptionsTreeWidgetItem::m_pNetworkData, IrcServerOptionsTreeWidgetItem::m_pServerData, m_pSrvNetEdit, KviIrcServer::setHostName(), KviIrcNetwork::setName(), and IrcServerOptionsTreeWidgetItem::updateVisibleStrings().
Referenced by commit(), connectCurrentClicked(), currentItemChanged(), detailsClicked(), and serverNetworkEditTextEdited().
void OptionsWidget_servers::selectBestServerByUrl (const QString & szUrl) private
References _KviIrcUrlParts::bIPv6, _KviIrcUrlParts::bSsl, KviIrcServer::hostName(), _KviIrcUrlParts::iPort, KviIrcServer::isIPv6(), m_pTreeWidget, NULL, KviIrcServer::port(), IrcServerOptionsTreeWidgetItem::serverData(), KviIrcUrl::split(), _KviIrcUrlParts::szHost, and KviIrcServer::useSSL().
Referenced by recentServersPopupClicked().
void OptionsWidget_servers::serverNetworkEditTextEdited (const QString & szNewText) protected slot
References m_pLastEditedItem, m_pTreeWidget, and saveLastItem().
Referenced by OptionsWidget_servers().
void OptionsWidget_servers::slotShowThisDialogAtStartupSelectorDestroyed () protected slot
References KVI_ASSERT, m_pShowThisDialogAtStartupSelector, NULL, and KviOptionsWidget::removeSelector().
Referenced by OptionsWidget_servers().
Member Data Documentation
KviIrcServer* OptionsWidget_servers::m_pClipboard protected
Referenced by copyServer(), customContextMenuRequested(), OptionsWidget_servers(), pasteServer(), and ~OptionsWidget_servers().
QPushButton* OptionsWidget_servers::m_pConnectCurrent protected
Referenced by currentItemChanged(), fillServerList(), and OptionsWidget_servers().
QPushButton* OptionsWidget_servers::m_pConnectNew protected
QMenu* OptionsWidget_servers::m_pContextPopup protected
Referenced by customContextMenuRequested(), and OptionsWidget_servers().
QToolButton* OptionsWidget_servers::m_pCopyServerButton protected
Referenced by currentItemChanged(), and OptionsWidget_servers().
QPushButton* OptionsWidget_servers::m_pDetailsButton protected
Referenced by currentItemChanged(), and OptionsWidget_servers().
QLineEdit* OptionsWidget_servers::m_pFilterEdit protected
Referenced by filterTextEdited(), and OptionsWidget_servers().
QLabel* OptionsWidget_servers::m_pFilterLabel protected
Referenced by OptionsWidget_servers().
QToolButton* OptionsWidget_servers::m_pImportButton protected
Referenced by OptionsWidget_servers().
KviMexServerImport* OptionsWidget_servers::m_pImportFilter protected
Referenced by importerDead(), importPopupActivated(), OptionsWidget_servers(), and ~OptionsWidget_servers().
QMenu* OptionsWidget_servers::m_pImportPopup protected
Referenced by customContextMenuRequested(), importPopupAboutToShow(), and OptionsWidget_servers().
IrcServerOptionsTreeWidgetItem* OptionsWidget_servers::m_pLastEditedItem protected
Referenced by clearList(), commit(), copyServer(), currentItemChanged(), detailsClicked(), newServer(), OptionsWidget_servers(), pasteServer(), removeCurrent(), saveLastItem(), and serverNetworkEditTextEdited().
IrcNetworkDetailsWidget* OptionsWidget_servers::m_pNetworkDetailsDialog protected
Referenced by detailsClicked(), OptionsWidget_servers(), and ~OptionsWidget_servers().
QToolButton* OptionsWidget_servers::m_pNewNetworkButton protected
Referenced by OptionsWidget_servers().
QToolButton* OptionsWidget_servers::m_pNewServerButton protected
Referenced by OptionsWidget_servers().
QToolButton* OptionsWidget_servers::m_pPasteServerButton protected
Referenced by copyServer(), and OptionsWidget_servers().
QMenu* OptionsWidget_servers::m_pRecentPopup protected
Referenced by OptionsWidget_servers(), and recentServersPopupAboutToShow().
QToolButton* OptionsWidget_servers::m_pRemoveButton protected
Referenced by currentItemChanged(), and OptionsWidget_servers().
IrcServerDetailsWidget* OptionsWidget_servers::m_pServerDetailsDialog protected
Referenced by detailsClicked(), OptionsWidget_servers(), and ~OptionsWidget_servers().
KviBoolSelector* OptionsWidget_servers::m_pShowThisDialogAtStartupSelector protected
Referenced by OptionsWidget_servers(), and slotShowThisDialogAtStartupSelectorDestroyed().
QLineEdit* OptionsWidget_servers::m_pSrvNetEdit protected
Referenced by connectCurrentClicked(), currentItemChanged(), OptionsWidget_servers(), and saveLastItem().
QLabel* OptionsWidget_servers::m_pSrvNetLabel protected
Referenced by currentItemChanged(), and OptionsWidget_servers().
QTreeWidget* OptionsWidget_servers::m_pTreeWidget protected
Referenced by clearList(), commit(), customContextMenuRequested(), fillServerList(), filterTextEdited(), findNetItem(), importServer(), newNetwork(), newServer(), OptionsWidget_servers(), pasteServer(), removeCurrent(), selectBestServerByUrl(), and serverNetworkEditTextEdited().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_servers.h
src/modules/options/OptionsWidget_servers.cpp