KVIrc: KviKvsTreeNodeSpecialCommandSwitchLabelCase Class Reference
KviKvsTreeNodeSpecialCommandSwitchLabelCase Class Reference
#include <KviKvsTreeNodeSpecialCommandSwitch.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool execute (KviKvsRunTimeContext *c, KviKvsVariant *pRealParameter, bool *bPassThrough)
KviKvsTreeNodeSpecialCommandSwitchLabelCase (const QChar *pLocation)
~KviKvsTreeNodeSpecialCommandSwitchLabelCase ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommandSwitchLabel
KviKvsTreeNodeSpecialCommandSwitchLabel (const QChar *pLocation)
void setInstruction (KviKvsTreeNodeInstruction *pInstruction)
void setParameter (KviKvsTreeNodeData *pParameter)
void setTerminatingBreak (bool b)
~KviKvsTreeNodeSpecialCommandSwitchLabel ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Attributes inherited from KviKvsTreeNodeSpecialCommandSwitchLabel
bool m_bHasTerminatingBreak
KviKvsTreeNodeInstruction * m_pInstruction
KviKvsTreeNodeData * m_pParameter
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandSwitchLabelCase::KviKvsTreeNodeSpecialCommandSwitchLabelCase (const QChar * pLocation)
KviKvsTreeNodeSpecialCommandSwitchLabelCase::~KviKvsTreeNodeSpecialCommandSwitchLabelCase ()
Member Function Documentation
void KviKvsTreeNodeSpecialCommandSwitchLabelCase::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeSpecialCommandSwitchLabelCase::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
References KviKvsTreeNodeData::dump(), KviKvsTreeNodeInstruction::dump(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, and KviKvsTreeNodeSpecialCommandSwitchLabel::m_pParameter.
bool KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute (KviKvsRunTimeContext * c, KviKvsVariant * pRealParameter, bool * bPassThrough) virtual
Implements KviKvsTreeNodeSpecialCommandSwitchLabel.
References KviKvsVariant::asNumber(), KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviKvsNumber::integer(), KviKvsNumber::isInteger(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_bHasTerminatingBreak, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pParameter, KviKvsNumber::real(), KviKvsRunTimeContext::setBreakPending(), and v.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandSwitch.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandSwitch.cpp