KVIrc: TipWindow Class Reference
TipWindow Class Reference
#include <libkvitip.h>
Public Slots
void nextTip ()
void prevTip ()
Public Member Functions
void closeConfig ()
bool openConfig (QString filename, bool bEnsureExists=true)
TipWindow ()
~TipWindow ()
Protected Member Functions
virtual void showEvent (QShowEvent *e)
Protected Attributes
KviConfigurationFile * m_pConfig
QCheckBox * m_pShowAtStartupCheck
TipFrame * m_pTipFrame
QString m_szConfigFileName
Constructor & Destructor Documentation
TipWindow::TipWindow ()
References __tr2qs, connect(), g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Idea, KVI_OPTION_BOOL, KviOption_boolShowTipAtStartup, m_pConfig, m_pShowAtStartupCheck, m_pTipFrame, nextTip(), and prevTip().
TipWindow::~TipWindow ()
References closeConfig(), KVI_OPTION_BOOL, KviOption_boolShowTipAtStartup, m_pConfig, and m_pShowAtStartupCheck.
Member Function Documentation
void TipWindow::closeConfig ()
References KviApplication::ConfigPlugins, g_pApp, KviApplication::getLocalKvircDirectory(), m_pConfig, m_szConfigFileName, and KviConfigurationFile::setSavePath().
Referenced by openConfig(), and ~TipWindow().
void TipWindow::nextTip () [slot]
References __tr2qs, KviCString::cutFromFirst(), KviCString::Format, KviLocale::instance(), KviLocale::localeName(), m_pConfig, m_pTipFrame, openConfig(), KviCString::ptr(), KviConfigurationFile::readEntry(), KviConfigurationFile::readUIntEntry(), TipFrame::setText(), KviCString::sprintf(), and KviConfigurationFile::writeEntry().
Referenced by tip_kvs_cmd_open(), and TipWindow().
bool TipWindow::openConfig (QString filename, bool bEnsureExists = true)
References closeConfig(), KviApplication::ConfigPlugins, KviFileUtils::fileExists(), g_pApp, KviApplication::getReadOnlyConfigPath(), m_pConfig, m_szConfigFileName, and KviConfigurationFile::Read.
Referenced by nextTip(), prevTip(), and tip_kvs_cmd_open().
void TipWindow::prevTip () [slot]
References __tr2qs, KviCString::cutFromFirst(), KviCString::Format, KviLocale::instance(), KviLocale::localeName(), m_pConfig, m_pTipFrame, openConfig(), KviCString::ptr(), KviConfigurationFile::readEntry(), KviConfigurationFile::readUIntEntry(), TipFrame::setText(), KviCString::sprintf(), and KviConfigurationFile::writeEntry().
Referenced by TipWindow().
void TipWindow::showEvent (QShowEvent * e) [protected, virtual]
References g_pApp, and KviMemory::move().
Member Data Documentation
KviConfigurationFile* TipWindow::m_pConfig [protected]
Referenced by closeConfig(), nextTip(), openConfig(), prevTip(), TipWindow(), and ~TipWindow().
QCheckBox* TipWindow::m_pShowAtStartupCheck [protected]
Referenced by TipWindow(), and ~TipWindow().
TipFrame* TipWindow::m_pTipFrame [protected]
Referenced by nextTip(), prevTip(), and TipWindow().
QString TipWindow::m_szConfigFileName [protected]
Referenced by closeConfig(), and openConfig().
The documentation for this class was generated from the following files:
src/modules/tip/libkvitip.h
src/modules/tip/libkvitip.cpp