KVIrc: KviModuleExtension Class Reference
KviModuleExtension Class Reference
#include <KviModuleExtension.h>
Public Member Functions
KviModuleExtensionDescriptor * descriptor ()
virtual void die ()=0
KviModuleExtension (KviModuleExtensionDescriptor *d)
virtual ~KviModuleExtension ()
Static Public Member Functions
static KviModuleExtensionManager * manager ()
Private Attributes
KviModuleExtensionDescriptor * m_pDescriptor
Constructor & Destructor Documentation
KviModuleExtension::KviModuleExtension (KviModuleExtensionDescriptor * d)
References d, m_pDescriptor, and KviModuleExtensionDescriptor::registerObject().
KviModuleExtension::~KviModuleExtension () [virtual]
References m_pDescriptor, and KviModuleExtensionDescriptor::unregisterObject().
Member Function Documentation
KviModuleExtensionDescriptor* KviModuleExtension::descriptor () [inline]
virtual void KviModuleExtension::die () [pure virtual]
Implemented in KviMexServerImport, FileTransferWindow, KviIOGraphWindow, LogViewWindow, KviMircServersIniImport, KviRemoteMircServersIniImport, and SharedFilesWindow.
Referenced by KviIrcLink::destroySocket().
static KviModuleExtensionManager* KviModuleExtension::manager () [inline, static]
References g_pModuleExtensionManager.
Member Data Documentation
KviModuleExtensionDescriptor* KviModuleExtension::m_pDescriptor [private]
Referenced by KviModuleExtension(), and ~KviModuleExtension().
The documentation for this class was generated from the following files:
src/kvirc/module/KviModuleExtension.h
src/kvirc/module/KviModuleExtension.cpp