KVIrc: KviClassEditorFunctionDialog Class Reference
KviClassEditorFunctionDialog Class Reference
This class constructs the dialog to create a new member function.
#include <ClassEditorWindow.h>
Public Member Functions
QString functionName ()
Returns the function name.
bool isInternalFunction ()
Returns true if the function is set as internal, false otherwise.
KviClassEditorFunctionDialog (QWidget *pParent, const QString &szName, const QString &szClassName, const QString &szFunctionName, const QString &szReminder, bool bIsInternal, bool bRenameMode=false)
Constructs the function dialog.
QString reminder ()
Returns the parameters of the function.
~KviClassEditorFunctionDialog ()
Destroys the function dialog.
Protected Slots
void textChanged (const QString &)
Triggered when the name of the function change.
Protected Attributes
QLineEdit * m_pFunctionNameLineEdit
QCheckBox * m_pInternalCheckBox
QPushButton * m_pNewFunctionButton
QLineEdit * m_pReminderLineEdit
Detailed Description
This class constructs the dialog to create a new member function.
Constructor & Destructor Documentation
KviClassEditorFunctionDialog::KviClassEditorFunctionDialog (QWidget * pParent, const QString & szName, const QString & szClassName, const QString & szFunctionName, const QString & szReminder, bool bIsInternal, bool bRenameMode = false)
Constructs the function dialog.
Parameters
pParent The parent widget
szName The name of the widget
szClassName The name of the class
szFunctionName The name of the function
szReminder The parameters of the function
bIsInternal Whether the funtion is set as internal
bRenameMode Whether the dialog is in rename mode
Returns
KviClassEditorFunctionDialog
References __tr2qs_ctx(), connect(), m_pFunctionNameLineEdit, m_pInternalCheckBox, m_pNewFunctionButton, m_pReminderLineEdit, KviTalHBox::setAlignment(), KviTalHBox::setMargin(), KviTalHBox::setSpacing(), KviTalHBox::setStretchFactor(), and textChanged().
KviClassEditorFunctionDialog::~KviClassEditorFunctionDialog ()
Destroys the function dialog.
Member Function Documentation
QString KviClassEditorFunctionDialog::functionName () inline
Returns the function name.
Returns
QString
References m_pFunctionNameLineEdit.
Referenced by ClassEditorWidget::askForFunction().
bool KviClassEditorFunctionDialog::isInternalFunction () inline
Returns true if the function is set as internal, false otherwise.
Returns
bool
References m_pInternalCheckBox.
Referenced by ClassEditorWidget::askForFunction().
QString KviClassEditorFunctionDialog::reminder () inline
Returns the parameters of the function.
Returns
QString
References m_pReminderLineEdit.
Referenced by ClassEditorWidget::askForFunction().
void KviClassEditorFunctionDialog::textChanged (const QString & szText) protected slot
Triggered when the name of the function change.
Returns
void
References m_pNewFunctionButton.
Referenced by KviClassEditorFunctionDialog().
Member Data Documentation
QLineEdit* KviClassEditorFunctionDialog::m_pFunctionNameLineEdit protected
Referenced by functionName(), and KviClassEditorFunctionDialog().
QCheckBox* KviClassEditorFunctionDialog::m_pInternalCheckBox protected
Referenced by isInternalFunction(), and KviClassEditorFunctionDialog().
QPushButton* KviClassEditorFunctionDialog::m_pNewFunctionButton protected
Referenced by KviClassEditorFunctionDialog(), and textChanged().
QLineEdit* KviClassEditorFunctionDialog::m_pReminderLineEdit protected
Referenced by KviClassEditorFunctionDialog(), and reminder().
The documentation for this class was generated from the following files:
src/modules/classeditor/ClassEditorWindow.h
src/modules/classeditor/ClassEditorWindow.cpp