KVIrc: KviFileDialog Class Reference
KviFileDialog Class Reference
File dialog class.
#include <KviFileDialog.h>
Public Member Functions
KviFileDialog (const QString &szDirName, const QString &szFilter=QString(), QWidget *pParent=0, const char *name=0, bool bModal=false)
Constructs the file dialog object.
~KviFileDialog ()
Destroys the file dialog object.
Static Public Member Functions
static bool askForDirectoryName (QString &szBuffer, const QString &szCaption, const QString &szInitial, const QString &szFilter=QString(), bool bShowHidden=false, bool bShowNative=true, QWidget *pParent=0)
static bool askForOpenFileName (QString &szBuffer, const QString &szCaption, const QString &szInitial=QString(), const QString &szFilter=QString(), bool bShowHidden=false, bool bShowNative=true, QWidget *pParent=0)
static bool askForOpenFileNames (QStringList &szBuffer, const QString &szCaption, const QString &szInitial, const QString &szFilter=QString(), bool bShowHidden=false, bool bShowNative=true, QWidget *pParent=0)
static bool askForSaveFileName (QString &szBuffer, const QString &szCaption, const QString &szInitial=QString(), const QString &szFilter=QString(), bool bShowHidden=false, bool bConfirmOverwrite=false, bool bShowNative=true, QWidget *pParent=0)
Detailed Description
File dialog class.
Constructor & Destructor Documentation
KviFileDialog::KviFileDialog (const QString & szDirName, const QString & szFilter = QString(), QWidget * pParent = 0, const char * name = 0, bool bModal = false)
Constructs the file dialog object.
Parameters:
szDirName The directory where to use the dialog
szFilter The filter to use
pParent The parent widget
name The name of the dialog
bModal Whether to have a modal behaviour
Returns:
KviFileDialog
References KviIconManager::Folder, g_pIconManager, and KviIconManager::getSmallIcon().
Referenced by askForDirectoryName(), askForOpenFileName(), askForOpenFileNames(), and askForSaveFileName().
KviFileDialog::~KviFileDialog ()
Destroys the file dialog object.
Member Function Documentation
bool KviFileDialog::askForDirectoryName (QString & szBuffer, const QString & szCaption, const QString & szInitial, const QString & szFilter = QString(), bool bShowHidden = false, bool bShowNative = true, QWidget * pParent = 0) [static]
Parameters:
szBuffer The buffer where to store the data
szCaption The caption of the dialog
szInitial The initial directory
szFilter The filter to use
bShowHidden Whether to show hidden files
bShowNative Whether to show native dialogs
pParent The parent widget
Returns:
bool
References KviFileUtils::adjustFilePath(), KviTalFileDialog::Directory, KviFileDialog(), and KviTalFileDialog::setFileMode().
Referenced by ClassEditorWidget::exportSelectionInSinglesFiles(), AliasEditorWidget::exportSelectionInSinglesFiles(), and KviDirectorySelector::select().
bool KviFileDialog::askForOpenFileName (QString & szBuffer, const QString & szCaption, const QString & szInitial = QString(), const QString & szFilter = QString(), bool bShowHidden = false, bool bShowNative = true, QWidget * pParent = 0) [static]
Parameters:
szBuffer The buffer where to store the data
szCaption The caption of the dialog
szInitial The initial directory
szFilter The filter to use
bShowHidden Whether to show hidden files
bShowNative Whether to show native dialogs
pParent The parent widget
Returns:
bool
References KviFileUtils::adjustFilePath(), KviTalFileDialog::ExistingFile, KviFileDialog(), and KviTalFileDialog::setFileMode().
Referenced by SharedFileEditDialog::browse(), KviIrcView::chooseBackground(), AvatarSelectionDialog::chooseFileClicked(), KviAsyncAvatarSelectionDialog::chooseFileClicked(), OptionsWidget_textIcons::chooseFromFile(), KviPixmapSelector::choosePixmap(), KviIrcViewToolWidget::filterLoad(), RegisteredUsersDialog::importClicked(), ListWindow::importList(), ThemeManagementDialog::installFromFile(), AddonManagementDialog::installScript(), KviKvsCoreSimpleCommands::KVSCSC(), OptionsWidget_messageColors::load(), ScriptEditorImplementation::loadFromFile(), KviFileSelector::select(), and KviMircServersIniImport::start().
bool KviFileDialog::askForOpenFileNames (QStringList & szBuffer, const QString & szCaption, const QString & szInitial, const QString & szFilter = QString(), bool bShowHidden = false, bool bShowNative = true, QWidget * pParent = 0) [static]
Parameters:
szBuffer The buffer where to store the data
szCaption The caption of the dialog
szInitial The initial directory
szFilter The filter to use
bShowHidden Whether to show hidden files
bShowNative Whether to show native dialogs
pParent The parent widget
Returns:
bool
References KviTalFileDialog::ExistingFiles, KviFileDialog(), and KviTalFileDialog::setFileMode().
Referenced by DccBroker::rsendAskForFileName(), and DccBroker::sendFileManage().
bool KviFileDialog::askForSaveFileName (QString & szBuffer, const QString & szCaption, const QString & szInitial = QString(), const QString & szFilter = QString(), bool bShowHidden = false, bool bConfirmOverwrite = false, bool bShowNative = true, QWidget * pParent = 0) [static]
Parameters:
szBuffer The buffer where to store the data
szCaption The caption of the dialog
szInitial The initial directory
szFilter The filter to use
bShowHidden Whether to show hidden files
bConfirmOverwrite Whether to avoid the check for an already existing file being overwritten
bShowNative Whether to show native dialogs
pParent The parent widget
Returns:
bool
References __tr2qs, KviFileUtils::adjustFilePath(), KviTalFileDialog::AnyFile, KviControlCodes::Escape, KviFileUtils::fileExists(), KviMessageBox::information(), KviFileDialog(), and KviTalFileDialog::setFileMode().
Referenced by DccBroker::chooseSaveFileName(), ActionEditor::exportActions(), AliasEditorWidget::exportAliases(), RawEditorWidget::exportAllEvents(), EventEditor::exportAllEvents(), ClassEditorWidget::exportClasses(), RegisteredUsersDialog::exportClicked(), RawEditorWidget::exportCurrentHandler(), EventEditor::exportCurrentHandler(), PopupEditorWidget::exportCurrentPopup(), ListWindow::exportList(), PopupEditorWidget::exportPopups(), CustomizeToolBarsDialog::exportToolBar(), KviIrcViewToolWidget::filterSave(), http_kvs_complete_get(), OptionsWidget_messageColors::save(), ScriptEditorImplementation::saveToFile(), KviFileSelector::select(), and theme_kvs_cmd_screenshot().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviFileDialog.h
src/kvirc/ui/KviFileDialog.cpp