KVIrc: OptionsWidget_connectionSsl Class Reference
OptionsWidget_connectionSsl Class Reference
#include <OptionsWidget_connection.h>
Public Member Functions
OptionsWidget_connectionSsl (QWidget *parent)
~OptionsWidget_connectionSsl ()
Constructor & Destructor Documentation
OptionsWidget_connectionSsl::OptionsWidget_connectionSsl (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addFileSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addPasswordSelector(), KviOptionsWidget::addRowSpacer(), connect(), KviOptionsWidget::createLayout(), f, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseSSLCertificate, KviOption_boolUseSSLPrivateKey, KviOption_stringSSLCertificatePass, KviOption_stringSSLCertificatePath, KviOption_stringSSLPrivateKeyPass, KviOption_stringSSLPrivateKeyPath, and p.
OptionsWidget_connectionSsl::~OptionsWidget_connectionSsl ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_connection.h
src/modules/options/OptionsWidget_connection.cpp