KVIrc: MessageListWidgetItemDelegate Class Reference
MessageListWidgetItemDelegate Class Reference
#include <OptionsWidget_message.h>
Public Member Functions
MessageListWidgetItemDelegate (QAbstractItemView *pWidget=0)
void paint (QPainter *p, const QStyleOptionViewItem &opt, const QModelIndex &index) const
~MessageListWidgetItemDelegate ()
Constructor & Destructor Documentation
MessageListWidgetItemDelegate::MessageListWidgetItemDelegate (QAbstractItemView * pWidget = 0) [inline]
MessageListWidgetItemDelegate::~MessageListWidgetItemDelegate () [inline]
Member Function Documentation
void MessageListWidgetItemDelegate::paint (QPainter * p, const QStyleOptionViewItem & opt, const QModelIndex & index) const
References KviMessageTypeSettings::back(), KviMessageTypeSettings::fore(), g_pApp, g_pIconManager, KviIconManager::getSmallIcon(), KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_MIRCCOLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorIrcViewBackground, KviOption_pixmapIrcViewBackground, KviOption_uintGlobalTransparencyChildFadeFactor, MessageListWidgetItem::msgType(), KviMessageTypeSettings::pixId(), and KviApplication::supportsCompositing().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_message.h
src/modules/options/OptionsWidget_message.cpp