KVIrc: KviStatusBarClock Class Reference
KviStatusBarClock Class Reference
#include <KviStatusBarApplet.h>
Public Types
enum Format { HMS, HM }
Public Member Functions
KviStatusBarClock (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
virtual ~KviStatusBarClock ()
Public Member Functions inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * descriptor ()
KviMainWindow * frame ()
int index () const
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Static Public Member Functions
static void selfRegister (KviStatusBar *pBar)
Protected Slots
void changeFormat (QAction *)
void toggle24h ()
void toggleUtc ()
Protected Member Functions
void adjustMinWidth ()
virtual void fillContextPopup (QMenu *p)
virtual void loadState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual void saveState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual void timerEvent (QTimerEvent *e)
Protected Member Functions inherited from KviStatusBarApplet
virtual QString tipText (const QPoint &)
Protected Attributes
bool m_b24h
bool m_bUtc
int m_iType
Protected Attributes inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Member Enumeration Documentation
enum KviStatusBarClock::Format
Enumerator:
HMS
HM
Constructor & Destructor Documentation
KviStatusBarClock::KviStatusBarClock (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
References adjustMinWidth(), HMS, m_b24h, m_bUtc, and m_iType.
KviStatusBarClock::~KviStatusBarClock () virtual
Member Function Documentation
void KviStatusBarClock::adjustMinWidth () protected
References HMS, m_b24h, and m_iType.
Referenced by changeFormat(), KviStatusBarClock(), loadState(), and toggle24h().
void KviStatusBarClock::changeFormat (QAction * pAct) protected slot
References adjustMinWidth(), and m_iType.
Referenced by fillContextPopup().
void KviStatusBarClock::fillContextPopup (QMenu * p) protected virtual
Reimplemented from KviStatusBarApplet.
References __tr2qs, changeFormat(), connect(), HM, HMS, m_b24h, m_bUtc, toggle24h(), and toggleUtc().
void KviStatusBarClock::loadState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References adjustMinWidth(), KviCString::Format, HMS, m_b24h, m_bUtc, m_iType, KviCString::ptr(), KviConfigurationFile::readBoolEntry(), and KviConfigurationFile::readIntEntry().
void KviStatusBarClock::saveState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References KviCString::Format, m_b24h, m_bUtc, m_iType, KviCString::ptr(), and KviConfigurationFile::writeEntry().
void KviStatusBarClock::selfRegister (KviStatusBar * pBar) static
References __tr2qs, CreateStatusBarClock(), d, g_pIconManager, KviIconManager::getSmallIcon(), KviStatusBar::registerAppletDescriptor(), and KviIconManager::Time.
Referenced by KviStatusBar::KviStatusBar().
void KviStatusBarClock::timerEvent (QTimerEvent * e) protected virtual
References HM, HMS, kvi_time_t, kvi_unixTime, m_b24h, m_bUtc, m_iType, and t().
Referenced by toggle24h(), and toggleUtc().
void KviStatusBarClock::toggle24h () protected slot
References adjustMinWidth(), m_b24h, and timerEvent().
Referenced by fillContextPopup().
void KviStatusBarClock::toggleUtc () protected slot
References m_bUtc, and timerEvent().
Referenced by fillContextPopup().
Member Data Documentation
bool KviStatusBarClock::m_b24h protected
Referenced by adjustMinWidth(), fillContextPopup(), KviStatusBarClock(), loadState(), saveState(), timerEvent(), and toggle24h().
bool KviStatusBarClock::m_bUtc protected
Referenced by fillContextPopup(), KviStatusBarClock(), loadState(), saveState(), timerEvent(), and toggleUtc().
int KviStatusBarClock::m_iType protected
Referenced by adjustMinWidth(), changeFormat(), KviStatusBarClock(), loadState(), saveState(), and timerEvent().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviStatusBarApplet.h
src/kvirc/ui/KviStatusBarApplet.cpp