KVIrc: KvsObject_treeWidgetItem Class Reference
KvsObject_treeWidgetItem Class Reference
#include <KvsObject_treeWidgeteItem.h>
Public Member Functions
void childDestroyed ()
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Static Public Member Functions
static kvs_hobject_t itemToHandle (QTreeWidgetItem *it)
Protected Member Functions
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertItem (KviKvsObjectFunctionCall *c)
bool isCheckable (KviKvsObjectFunctionCall *c)
bool isChecked (KviKvsObjectFunctionCall *c)
bool isEnabled (KviKvsObjectFunctionCall *c)
bool isItemEditable (KviKvsObjectFunctionCall *c)
bool isOpen (KviKvsObjectFunctionCall *c)
bool setCheckable (KviKvsObjectFunctionCall *c)
bool setChecked (KviKvsObjectFunctionCall *c)
bool setEnabled (KviKvsObjectFunctionCall *c)
bool setFlags (KviKvsObjectFunctionCall *c)
bool setItemEditable (KviKvsObjectFunctionCall *c)
bool setOpen (KviKvsObjectFunctionCall *c)
bool setPixmap (KviKvsObjectFunctionCall *c)
bool setText (KviKvsObjectFunctionCall *c)
bool text (KviKvsObjectFunctionCall *c)
Protected Member Functions inherited from KviKvsObject
virtual bool eventFilter (QObject *o, QEvent *e)
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
QTreeWidgetItem * m_pTreeWidgetItem
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Additional Inherited Members
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Member Function Documentation
void KvsObject_treeWidgetItem::childDestroyed ()
References KviKvsObject::die(), and m_pTreeWidgetItem.
Referenced by KviKvsStandardTreeWidgetItem::~KviKvsStandardTreeWidgetItem().
bool KvsObject_treeWidgetItem::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) protected virtual
Reimplemented from KviKvsObject.
References __tr2qs_ctx().
bool KvsObject_treeWidgetItem::insertItem (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::isCheckable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::isChecked (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::isEnabled (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::isItemEditable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::isOpen (KviKvsObjectFunctionCall * c) protected
kvs_hobject_t KvsObject_treeWidgetItem::itemToHandle (QTreeWidgetItem * it) static
References KviKvsObject::handle().
Referenced by KvsObject_treeWidget::fileDropped(), KVSO_CLASS_FUNCTION(), KvsObject_treeWidget::slotClicked(), KvsObject_treeWidget::slotCurrentChanged(), KvsObject_treeWidget::slotItemActivated(), KvsObject_treeWidget::slotItemChanged(), KvsObject_treeWidget::slotItemCollapsed(), KvsObject_treeWidget::slotItemExpanded(), KvsObject_treeWidget::slotOnItemEntered(), and KvsObject_treeWidget::slotSelectionChanged().
bool KvsObject_treeWidgetItem::setCheckable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setChecked (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setEnabled (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setFlags (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setItemEditable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setOpen (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setPixmap (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::setText (KviKvsObjectFunctionCall * c) protected
bool KvsObject_treeWidgetItem::text (KviKvsObjectFunctionCall * c) protected
Member Data Documentation
QTreeWidgetItem* KvsObject_treeWidgetItem::m_pTreeWidgetItem protected
Referenced by childDestroyed().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_treeWidgeteItem.h
src/modules/objects/KvsObject_treeWidgeteItem.cpp