KVIrc: KviTreeWindowList Class Reference
KviTreeWindowList Class Reference
#include <KviTreeWindowList.h>
Public Member Functions
virtual KviWindowListItem * addItem (KviWindow *)
virtual KviWindowListItem * firstItem ()
KviTreeWindowList ()
virtual KviWindowListItem * lastItem ()
virtual KviWindowListItem * nextItem (void)
virtual KviWindowListItem * prevItem (void)
virtual bool removeItem (KviWindowListItem *)
virtual void setActiveItem (KviWindowListItem *)
virtual bool setIterationPointer (KviWindowListItem *it)
virtual void updateActivityMeter ()
virtual void updatePseudoTransparency ()
~KviTreeWindowList ()
Public Member Functions inherited from KviWindowListBase
virtual void applyOptions ()
Qt::DockWidgetArea currentDockArea ()
virtual KviWindowListItem * item (int number)
KviWindowListBase ()
virtual void switchWindow (bool bNext, bool bInContextOnly, bool bHighlightedOnly=false)
virtual void wheelEvent (QWheelEvent *e)
virtual ~KviWindowListBase ()
Protected Slots
void tipRequest (KviDynamicToolTip *tip, const QPoint &pnt)
Protected Slots inherited from KviWindowListBase
void updateDockLocation (Qt::DockWidgetArea newArea)
Protected Member Functions
virtual void moveEvent (QMoveEvent *)
Private Attributes
KviTreeWindowListItem * m_pCurrentItem
QStyledItemDelegate * m_pItemDelegate
KviDynamicToolTip * m_pToolTip
KviTreeWindowListTreeWidget * m_pTreeWidget
Additional Inherited Members
Static Public Member Functions inherited from KviWindowListBase
static void getTextForConsole (QString &szText, KviConsoleWindow *pConsole)
Protected Attributes inherited from KviWindowListBase
Qt::DockWidgetArea currentArea
QTimer * m_pActivityMeterTimer
KviMainWindow * m_pFrm
QWidget * m_pTitleWidget
Constructor & Destructor Documentation
KviTreeWindowList::KviTreeWindowList ()
References KviWindowListBase::applyOptions(), connect(), KVI_OPTION_UINT, KviOption_uintTreeWindowListMinimumWidth, m_pItemDelegate, m_pToolTip, m_pTreeWidget, and tipRequest().
KviTreeWindowList::~KviTreeWindowList () default
Member Function Documentation
KviWindowListItem * KviTreeWindowList::addItem (KviWindow * wnd) virtual
Reimplemented from KviWindowListBase.
References KviWindow::Console, KviWindow::console(), m_pTreeWidget, KviWindow::m_pWindowListItem, and KviWindow::type().
KviWindowListItem * KviTreeWindowList::firstItem () virtual
Reimplemented from KviWindowListBase.
References m_pCurrentItem, and m_pTreeWidget.
KviWindowListItem * KviTreeWindowList::lastItem (void) virtual
Reimplemented from KviWindowListBase.
References m_pCurrentItem, and m_pTreeWidget.
void KviTreeWindowList::moveEvent (QMoveEvent *) protected virtual
References updatePseudoTransparency().
KviWindowListItem * KviTreeWindowList::nextItem (void) virtual
Reimplemented from KviWindowListBase.
References m_pCurrentItem, and m_pTreeWidget.
KviWindowListItem * KviTreeWindowList::prevItem (void) virtual
Reimplemented from KviWindowListBase.
References m_pCurrentItem, and m_pTreeWidget.
bool KviTreeWindowList::removeItem (KviWindowListItem * it) virtual
Reimplemented from KviWindowListBase.
References KviWindowListBase::item(), and m_pTreeWidget.
void KviTreeWindowList::setActiveItem (KviWindowListItem * it) virtual
Reimplemented from KviWindowListBase.
References g_pMainWindow, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
bool KviTreeWindowList::setIterationPointer (KviWindowListItem * it) virtual
Reimplemented from KviWindowListBase.
References m_pCurrentItem, and m_pTreeWidget.
void KviTreeWindowList::tipRequest (KviDynamicToolTip * tip, const QPoint & pnt) protected slot
References KVI_OPTION_BOOL, KviOption_boolShowWindowListToolTips, m_pToolTip, m_pTreeWidget, and KviDynamicToolTip::tip().
Referenced by KviTreeWindowList().
void KviTreeWindowList::updateActivityMeter () virtual
Reimplemented from KviWindowListBase.
References KVI_OPTION_BOOL, KviOption_boolUseWindowListActivityMeter, and m_pTreeWidget.
void KviTreeWindowList::updatePseudoTransparency () virtual
Reimplemented from KviWindowListBase.
References m_pTreeWidget.
Referenced by moveEvent().
Member Data Documentation
KviTreeWindowListItem* KviTreeWindowList::m_pCurrentItem private
Referenced by firstItem(), lastItem(), nextItem(), prevItem(), and setIterationPointer().
QStyledItemDelegate* KviTreeWindowList::m_pItemDelegate private
Referenced by KviTreeWindowList().
KviDynamicToolTip* KviTreeWindowList::m_pToolTip private
Referenced by KviTreeWindowList(), and tipRequest().
KviTreeWindowListTreeWidget* KviTreeWindowList::m_pTreeWidget private
Referenced by addItem(), firstItem(), KviTreeWindowList(), lastItem(), nextItem(), prevItem(), removeItem(), setIterationPointer(), tipRequest(), updateActivityMeter(), and updatePseudoTransparency().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviTreeWindowList.h
src/kvirc/ui/KviTreeWindowList.cpp