KVIrc: KviKvsEvent Class Reference
KviKvsEvent Class Reference
#include <KviKvsEvent.h>
Public Member Functions
void addHandler (KviKvsEventHandler *h)
void clear ()
void clearScriptHandlers ()
KviPointerList
< KviKvsEventHandler > * handlers ()
bool hasHandlers ()
KviKvsEvent (const char *szEventName, const char *szParameterDescription)
const QString & name ()
const QString & parameterDescription ()
void removeHandler (KviKvsEventHandler *h)
~KviKvsEvent ()
Protected Attributes
KviPointerList
< KviKvsEventHandler > * m_pHandlers
QString m_szName
QString m_szParameterDescription
Constructor & Destructor Documentation
KviKvsEvent::KviKvsEvent (const char * szEventName, const char * szParameterDescription) [inline]
KviKvsEvent::~KviKvsEvent ()
References clear().
Member Function Documentation
void KviKvsEvent::addHandler (KviKvsEventHandler * h)
References KviPointerList< T >::append(), m_pHandlers, and KviPointerList< T >::setAutoDelete().
Referenced by KviKvsEventManager::addAppHandler(), and KviKvsEventManager::loadAppEvents().
void KviKvsEvent::clear ()
References m_pHandlers.
Referenced by KviKvsEventManager::clearAppEvents(), and ~KviKvsEvent().
void KviKvsEvent::clearScriptHandlers ()
References KviPointerList< T >::append(), e, KviPointerList< T >::first(), KviPointerList< T >::isEmpty(), m_pHandlers, KviPointerList< T >::next(), KviPointerList< T >::removeRef(), KviKvsEventHandler::Script, KviPointerList< T >::setAutoDelete(), and KviKvsEventHandler::type().
Referenced by KviKvsEventManager::removeAllScriptAppHandlers().
KviPointerList<KviKvsEventHandler>* KviKvsEvent::handlers () [inline]
Referenced by KviKvsEventManager::findScriptAppHandler(), EventEditor::oneTimeSetup(), KviKvsEventManager::removeAllModuleAppHandlers(), KviKvsEventManager::removeModuleAppHandler(), KviKvsEventManager::removeScriptAppHandler(), and KviKvsEventManager::saveAppEvents().
bool KviKvsEvent::hasHandlers () [inline]
const QString& KviKvsEvent::name () [inline]
Referenced by EventEditor::oneTimeSetup().
const QString& KviKvsEvent::parameterDescription () [inline]
Referenced by EventEditor::oneTimeSetup().
void KviKvsEvent::removeHandler (KviKvsEventHandler * h)
References KviPointerList< T >::isEmpty(), m_pHandlers, and KviPointerList< T >::removeRef().
Referenced by KviKvsEventManager::removeModuleAppHandler(), and KviKvsEventManager::removeScriptAppHandler().
Member Data Documentation
KviPointerList<KviKvsEventHandler>* KviKvsEvent::m_pHandlers [protected]
Referenced by addHandler(), clear(), clearScriptHandlers(), and removeHandler().
QString KviKvsEvent::m_szName [protected]
QString KviKvsEvent::m_szParameterDescription [protected]
The documentation for this class was generated from the following files:
src/kvirc/kvs/event/KviKvsEvent.h
src/kvirc/kvs/event/KviKvsEvent.cpp