KVIrc: KviClassEditorDialog Class Reference
KviClassEditorDialog Class Reference
This class constructs the dialog to create a new class.
#include <ClassEditorWindow.h>
Public Member Functions
QString className ()
Returns the class name.
QString inheritsClassName ()
Returns the class name of the parent classes.
KviClassEditorDialog (QWidget *pParent, const QString &szName, KviPointerHashTable< QString, ClassEditorTreeWidgetItem > *pClasses, const QString &szClassName, const QString &szInheritsClassName, bool bRenameMode=false)
Constructs the class dialog.
~KviClassEditorDialog ()
Destroys the class dialog.
Protected Slots
void textChanged (const QString &)
Triggered when the name of the class change.
Protected Attributes
QLineEdit * m_pClassNameLineEdit
QComboBox * m_pInheritsClassComboBox
QPushButton * m_pNewClassButton
Detailed Description
This class constructs the dialog to create a new class.
Constructor & Destructor Documentation
KviClassEditorDialog::KviClassEditorDialog (QWidget * pParent, const QString & szName, KviPointerHashTable< QString, ClassEditorTreeWidgetItem > * pClasses, const QString & szClassName, const QString & szInheritsClassName, bool bRenameMode = false)
Constructs the class dialog.
Parameters:
pParent The parent widget
szName The name of the widget
pClasses The container of all classes of our namespace
szClassName The name of the class
szInheritsClassName The name of the classes in which this inherits from
bRenameMode Whether the dialog is in rename mode
Returns:
KviClassEditorDialog
References __tr2qs_ctx(), connect(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviQString::equalCI(), i, KviKvsKernel::instance(), KviKvsObjectClass::isBuiltin(), m_pClassNameLineEdit, m_pInheritsClassComboBox, m_pNewClassButton, KviTalHBox::setMargin(), KviTalHBox::setSpacing(), and textChanged().
KviClassEditorDialog::~KviClassEditorDialog ()
Destroys the class dialog.
Member Function Documentation
QString KviClassEditorDialog::className () [inline]
Returns the class name.
Returns:
QString
References m_pClassNameLineEdit.
Referenced by ClassEditorWidget::askForClassName().
QString KviClassEditorDialog::inheritsClassName () [inline]
Returns the class name of the parent classes.
Returns:
QString
References m_pInheritsClassComboBox.
Referenced by ClassEditorWidget::askForClassName().
void KviClassEditorDialog::textChanged (const QString & szText) [protected, slot]
Triggered when the name of the class change.
Returns:
void
References m_pNewClassButton.
Referenced by KviClassEditorDialog().
Member Data Documentation
QLineEdit* KviClassEditorDialog::m_pClassNameLineEdit [protected]
Referenced by className(), and KviClassEditorDialog().
QComboBox* KviClassEditorDialog::m_pInheritsClassComboBox [protected]
Referenced by inheritsClassName(), and KviClassEditorDialog().
QPushButton* KviClassEditorDialog::m_pNewClassButton [protected]
Referenced by KviClassEditorDialog(), and textChanged().
The documentation for this class was generated from the following files:
src/modules/classeditor/ClassEditorWindow.h
src/modules/classeditor/ClassEditorWindow.cpp