KVIrc: KviKvsTreeNodeBaseObjectFunctionCall Class Reference
KviKvsTreeNodeBaseObjectFunctionCall Class Reference
#include <KviKvsTreeNodeBaseObjectFunctionCall.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeBaseObjectFunctionCall (const QChar *pLocation, const QString &szBaseClass, const QString &szFncName, KviKvsTreeNodeDataList *pParams)
~KviKvsTreeNodeBaseObjectFunctionCall ()
Public Member Functions inherited from KviKvsTreeNodeObjectFunctionCall
virtual bool canEvaluateInObjectScope ()
KviKvsTreeNodeObjectFunctionCall (const QChar *pLocation, const QString &szFncName, KviKvsTreeNodeDataList *pParams)
~KviKvsTreeNodeObjectFunctionCall ()
Public Member Functions inherited from KviKvsTreeNodeFunctionCall
virtual bool canEvaluateToObjectReference ()
virtual bool isFunctionCall ()
KviKvsTreeNodeFunctionCall (const QChar *pLocation, const QString &szFunctionName, KviKvsTreeNodeDataList *pParams)
~KviKvsTreeNodeFunctionCall ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
QString m_szBaseClass
Protected Attributes inherited from KviKvsTreeNodeFunctionCall
KviKvsTreeNodeDataList * m_pParams
QString m_szFunctionName
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeBaseObjectFunctionCall::KviKvsTreeNodeBaseObjectFunctionCall (const QChar * pLocation, const QString & szBaseClass, const QString & szFncName, KviKvsTreeNodeDataList * pParams)
References m_szBaseClass.
KviKvsTreeNodeBaseObjectFunctionCall::~KviKvsTreeNodeBaseObjectFunctionCall () default
Member Function Documentation
void KviKvsTreeNodeBaseObjectFunctionCall::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeObjectFunctionCall.
References m_szBaseClass, and KviKvsTreeNodeFunctionCall::m_szFunctionName.
void KviKvsTreeNodeBaseObjectFunctionCall::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeObjectFunctionCall.
References KviKvsTreeNodeDataList::dump(), KviKvsTreeNodeFunctionCall::m_pParams, m_szBaseClass, and KviKvsTreeNodeFunctionCall::m_szFunctionName.
bool KviKvsTreeNodeBaseObjectFunctionCall::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References c, KviKvsObject::callFunction(), KviKvsTreeNodeDataList::evaluate(), l, KviKvsTreeNodeFunctionCall::m_pParams, m_szBaseClass, KviKvsTreeNodeFunctionCall::m_szFunctionName, KviKvsRunTimeContext::setDefaultReportLocation(), KviKvsVariant::setNothing(), and KviKvsRunTimeContext::thisObject().
Member Data Documentation
QString KviKvsTreeNodeBaseObjectFunctionCall::m_szBaseClass protected
Referenced by contextDescription(), dump(), evaluateReadOnlyInObjectScope(), and KviKvsTreeNodeBaseObjectFunctionCall().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeBaseObjectFunctionCall.h
src/kvirc/kvs/tree/KviKvsTreeNodeBaseObjectFunctionCall.cpp