KVIrc: StatusBarApplet Class Reference
StatusBarApplet Class Reference
#include <StatusBarApplet.h>
Public Member Functions
StatusBarApplet (KviStatusBar *parent, KviStatusBarAppletDescriptor *desc)
virtual ~StatusBarApplet ()
Public Member Functions inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * descriptor ()
KviMainWindow * frame ()
int index () const
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Static Public Member Functions
static void selfRegister (KviStatusBar *bar)
Private Slots
void update ()
Additional Inherited Members
Protected Member Functions inherited from KviStatusBarApplet
virtual void fillContextPopup (QMenu *)
virtual void loadState (const char *, KviConfigurationFile *)
virtual void saveState (const char *, KviConfigurationFile *)
virtual QString tipText (const QPoint &)
Protected Attributes inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Constructor & Destructor Documentation
StatusBarApplet::StatusBarApplet (KviStatusBar * parent, KviStatusBarAppletDescriptor * desc)
References __tr2qs_ctx(), connect(), and update().
StatusBarApplet::~StatusBarApplet () virtual default
Member Function Documentation
void StatusBarApplet::selfRegister (KviStatusBar * bar) static
References __tr2qs_ctx(), KviIconManager::Away, CreateTorrentClientApplet(), d, g_pIconManager, KviIconManager::getSmallIcon(), and KviStatusBar::registerAppletDescriptor().
Referenced by torrent_module_init().
void StatusBarApplet::update () private slot
References __tr2qs_ctx(), formatSize(), and TorrentInterface::selected().
Referenced by StatusBarApplet().
The documentation for this class was generated from the following files:
src/modules/torrent/StatusBarApplet.h
src/modules/torrent/StatusBarApplet.cpp