KVIrc: DccVideoThread Class Reference
DccVideoThread Class Reference
#include <DccVideoWindow.h>
Public Member Functions
DccVideoThread (KviWindow *wnd, kvi_socket_t fd, KviDccVideoThreadOptions *opt)
~DccVideoThread ()
Public Member Functions inherited from DccThread
DccThread (QObject *par, kvi_socket_t fd)
QObject * parent ()
void postErrorEvent (int err)
void postMessageEvent (const char *message)
~DccThread ()
Public Member Functions inherited from KviSensitiveThread
void enqueueEvent (KviThreadEvent *e)
KviSensitiveThread ()
void terminate ()
virtual ~KviSensitiveThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
virtual bool handleIncomingData (KviDccThreadIncomingData *data, bool bCritical)
bool isPlaying ()
bool readWriteStep ()
void restartRecording (int iDevice, int iInput, int iStandard)
virtual void run ()
void startPlaying ()
void startRecording ()
void stopPlaying ()
void stopRecording ()
bool textStep ()
bool videoStep ()
Protected Member Functions inherited from DccThread
bool handleInvalidSocketRead (int readLen)
Protected Member Functions inherited from KviSensitiveThread
KviThreadEvent * dequeueEvent ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
Protected Attributes
bool m_bPlaying
bool m_bRecording
KviDataBuffer m_inFrameBuffer
QImage m_inImage
KviDataBuffer m_outFrameBuffer
QImage m_outImage
KviDccVideoThreadOptions * m_pOpt
KviDataBuffer m_textInSignalBuffer
KviDataBuffer m_textOutSignalBuffer
KviDataBuffer m_videoInSignalBuffer
KviDataBuffer m_videoOutSignalBuffer
Protected Attributes inherited from DccThread
kvi_socket_t m_fd
KviMutex * m_pMutex
QObject * m_pParent
Protected Attributes inherited from KviSensitiveThread
KviPointerList< KviThreadEvent > * m_pLocalEventQueue
KviMutex * m_pLocalEventQueueMutex
Friends
class DccVideoWindow
Additional Inherited Members
Static Public Member Functions inherited from KviThread
static void msleep (unsigned long msec)
static void sleep (unsigned long sec)
static void usleep (unsigned long usec)
Constructor & Destructor Documentation
DccVideoThread::DccVideoThread (KviWindow * wnd, kvi_socket_t fd, KviDccVideoThreadOptions * opt)
References m_bPlaying, m_bRecording, m_pOpt, startPlaying(), and startRecording().
DccVideoThread::~DccVideoThread ()
References m_pOpt, _KviDccVideoThreadOptions::pCodec, and stopRecording().
Member Function Documentation
bool DccVideoThread::handleIncomingData (KviDccThreadIncomingData * data, bool bCritical) protected virtual
References _KviDccThreadIncomingData::buffer, KviCString::cutRight(), e, KviMemory::free(), _KviDccThreadIncomingData::iLen, KVI_ASSERT, KVI_DCC_THREAD_EVENT_DATA, KviCString::lastCharIs(), KviMemory::move(), DccThread::parent(), KviThread::postEvent(), KviMemory::reallocate(), s, and KviThreadDataEvent< TData >::setData().
Referenced by textStep().
bool DccVideoThread::isPlaying () inline protected
References m_bPlaying.
bool DccVideoThread::readWriteStep () protected
References KviDataBuffer::data(), DccVideoCodec::decode(), DccThread::handleInvalidSocketRead(), kvi_select(), kvi_socket_recv(), kvi_socket_send(), DccThread::m_fd, m_inFrameBuffer, m_outFrameBuffer, m_pOpt, m_textInSignalBuffer, m_videoInSignalBuffer, _KviDccVideoThreadOptions::pCodec, KviDataBuffer::remove(), KviDataBuffer::resize(), and KviDataBuffer::size().
Referenced by run().
void DccVideoThread::restartRecording (int iDevice, int iInput, int iStandard) protected
References m_bRecording.
void DccVideoThread::run () protected virtual
Reimplemented from KviThread.
References KviSensitiveThread::dequeueEvent(), e, FRAME_DURATION, KVI_DCC_THREAD_EVENT_ACTION, KVI_INVALID_SOCKET, kvi_socket_close, KVI_THREAD_EVENT_TERMINATE, DccThread::m_fd, readWriteStep(), startRecording(), stopRecording(), textStep(), KviThread::usleep(), and videoStep().
void DccVideoThread::startPlaying () protected
References e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VIDEO_THREAD_ACTION_START_PLAYING, m_bPlaying, DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by DccVideoThread().
void DccVideoThread::startRecording () protected
References e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VIDEO_THREAD_ACTION_START_RECORDING, m_bRecording, DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by DccVideoThread(), and run().
void DccVideoThread::stopPlaying () protected
References e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VIDEO_THREAD_ACTION_STOP_PLAYING, m_bPlaying, DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
void DccVideoThread::stopRecording () protected
References e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VIDEO_THREAD_ACTION_STOP_RECORDING, m_bRecording, DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by run(), and ~DccVideoThread().
bool DccVideoThread::textStep () protected
References KviMemory::allocate(), KviDataBuffer::append(), _KviDccThreadIncomingData::buffer, KviDataBuffer::clear(), KviDataBuffer::data(), DccVideoCodec::encodeText(), handleIncomingData(), _KviDccThreadIncomingData::iLen, m_bPlaying, m_bRecording, m_outFrameBuffer, m_pOpt, m_textInSignalBuffer, m_textOutSignalBuffer, DccThread::parent(), _KviDccVideoThreadOptions::pCodec, and KviDataBuffer::size().
Referenced by run().
bool DccVideoThread::videoStep () protected
References KviDataBuffer::append(), KviDataBuffer::data(), e, DccVideoCodec::encodeVideo(), KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VIDEO_THREAD_ACTION_GRAB_FRAME, m_bPlaying, m_bRecording, m_inImage, m_outFrameBuffer, m_pOpt, m_videoInSignalBuffer, m_videoOutSignalBuffer, DccThread::parent(), _KviDccVideoThreadOptions::pCodec, KviThread::postEvent(), KviThreadDataEvent< TData >::setData(), and KviDataBuffer::size().
Referenced by run().
Friends And Related Function Documentation
friend class DccVideoWindow friend
Member Data Documentation
bool DccVideoThread::m_bPlaying protected
Referenced by DccVideoThread(), isPlaying(), startPlaying(), stopPlaying(), textStep(), and videoStep().
bool DccVideoThread::m_bRecording protected
Referenced by DccVideoThread(), restartRecording(), startRecording(), stopRecording(), textStep(), and videoStep().
KviDataBuffer DccVideoThread::m_inFrameBuffer protected
Referenced by readWriteStep().
QImage DccVideoThread::m_inImage protected
Referenced by DccVideoWindow::slotUpdateImage(), and videoStep().
KviDataBuffer DccVideoThread::m_outFrameBuffer protected
Referenced by readWriteStep(), textStep(), and videoStep().
QImage DccVideoThread::m_outImage protected
KviDccVideoThreadOptions* DccVideoThread::m_pOpt protected
Referenced by DccVideoThread(), readWriteStep(), textStep(), videoStep(), and ~DccVideoThread().
KviDataBuffer DccVideoThread::m_textInSignalBuffer protected
Referenced by readWriteStep(), and textStep().
KviDataBuffer DccVideoThread::m_textOutSignalBuffer protected
Referenced by textStep().
KviDataBuffer DccVideoThread::m_videoInSignalBuffer protected
Referenced by readWriteStep(), and videoStep().
KviDataBuffer DccVideoThread::m_videoOutSignalBuffer protected
Referenced by videoStep().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVideoWindow.h
src/modules/dcc/DccVideoWindow.cpp