KVIrc: OptionsWidget_ctcp Class Reference
OptionsWidget_ctcp Class Reference
#include <OptionsWidget_ctcp.h>
Public Member Functions
OptionsWidget_ctcp (QWidget *parent)
~OptionsWidget_ctcp ()
Constructor & Destructor Documentation
OptionsWidget_ctcp::OptionsWidget_ctcp (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::createLayout(), KviOption_boolCtcpRepliesToActiveWindow, KviOption_boolShowDialogOnCtcpPage, KviOption_stringCtcpPageReply, KviOption_stringCtcpSourcePostfix, KviOption_stringCtcpVersionPostfix, KviOptionsWidget::mergeTip(), and s.
OptionsWidget_ctcp::~OptionsWidget_ctcp ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_ctcp.h
src/modules/options/OptionsWidget_ctcp.cpp