KVIrc: OptionsWidget_themeToolBarApplets Class Reference
OptionsWidget_themeToolBarApplets Class Reference
#include <OptionsWidget_theme.h>
Public Member Functions
OptionsWidget_themeToolBarApplets (QWidget *parent)
~OptionsWidget_themeToolBarApplets ()
Constructor & Destructor Documentation
OptionsWidget_themeToolBarApplets::OptionsWidget_themeToolBarApplets (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::createLayout(), KviOption_colorIrcToolBarAppletBackground, KviOption_colorIrcToolBarAppletForegroundHighContrastActive1, KviOption_colorIrcToolBarAppletForegroundHighContrastActive2, KviOption_colorIrcToolBarAppletForegroundHighContrastInactive1, KviOption_colorIrcToolBarAppletForegroundHighContrastInactive2, KviOption_colorIrcToolBarAppletForegroundLowContrast, KviOption_colorIrcToolBarAppletForegroundMidContrast, KviOption_fontIrcToolBarApplet, KviOption_pixmapIrcToolBarAppletBackground, and KviOptionsWidget::layout().
OptionsWidget_themeToolBarApplets::~OptionsWidget_themeToolBarApplets ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_theme.h
src/modules/options/OptionsWidget_theme.cpp