KVIrc: KviPointerListIterator< T > Class Template Reference
KviPointerListIterator< T > Class Template Reference
A fast KviPointerList iterator.
#include <kvi_pointerlist.h>
Public Member Functions
T * current ()
Returs the value pointed by the iterator.
bool isValid ()
Returns true if this iterator points to a valid element.
KviPointerListIterator (KviPointerList< T > &l, KviPointerListNode *pNode)
Creates an iterator for the list l.
KviPointerListIterator (KviPointerList< T > &l)
Creates an iterator for the list l.
KviPointerListIterator (const KviPointerListIterator< T > &src)
Creates an iterator copy.
bool moveFirst ()
Moves the iterator to the first element of the list.
bool moveLast ()
Moves the iterator to the last element of the list.
bool moveNext ()
Moves the iterator to the next element of the list.
bool movePrev ()
Moves the iterator to the previous element of the list.
T * operator* ()
Returs the value pointed by the iterator.
bool operator++ ()
Moves the iterator to the next element of the list.
bool operator-- ()
Moves the iterator to the previous element of the list.
void operator= (const KviPointerListIterator< T > &src)
Creates an iterator copy.
Protected Attributes
KviPointerList< T > * m_pList
KviPointerListNode * m_pNode
Detailed Description
template<typename T>
class KviPointerListIterator< T >
A fast KviPointerList iterator.
This class allows traversing the list sequentially. Multilpe iterators can traverse the list at the same time.
Iteration example 1:
* KviPointerListIterator<T> it(list);
* for(bool b = it.moveFirst(); b; b = it.moveNext())
* {
*     T * pData = it.data();
*     doSomethingWithData(pData);
* }
*
Iteration example 2:
* KviPointerListIterator<T> it(list);
* if(it.moveFirst())
* {
*     do {
*         T * pData = it.data();
*         doSomethingWithData(pData);
*     } while(it.moveNext());
* }
*
Iteration example 3:
* KviPointerListIterator<T> it(list.iteratorAt(10));
* if(it.isValid())
* {
*    do {
*         T * pData = it.data();
*         doSomethingWithData(pData);
*    while(it.movePrev());
* }
*
Please note that you must NOT remove any item from the list when using the iterators. An iterator pointing to a removed item will crash your application if you use it. The following code will NOT work (and crash):
* KviPointerList<T> l;
* l.append(new KviStr("x"));
* l.append(new KviStr("y"));
* KviPointerListIterator<T> it(l);
* it.moveFirst();
* l.removeFirst();
* KviStr * tmp = it.data(); <-- this will crash
*
In the rare cases in that you need to remove items while traversing the list you should put them in a temporary list and remove them after the iteration.
I've chosen this way because usually you don't modify the list while traversing it and a fix for this would add a constant overhead to several list operation. You just must take care of it yourself.
Warning:
This class is not thread safe by itself.
Constructor & Destructor Documentation
template<typename T> KviPointerListIterator< T >::KviPointerListIterator (const KviPointerListIterator< T > & src) [inline]
Creates an iterator copy.
The new iterator points exactly to the item pointed by src.
Parameters:
src The source item to point to
Returns:
KviPointerListIterator
template<typename T> KviPointerListIterator< T >::KviPointerListIterator (KviPointerList< T > & l) [inline]
Creates an iterator for the list l.
The iterator points to the first list item, if any.
Parameters:
l The source list to point to
Returns:
KviPointerListIterator
template<typename T> KviPointerListIterator< T >::KviPointerListIterator (KviPointerList< T > & l, KviPointerListNode * pNode) [inline]
Creates an iterator for the list l.
The iterator points to the specified list node.
Parameters:
l The source list
pNode The list node to point to
Returns:
KviPointerListIterator
Member Function Documentation
template<typename T> T* KviPointerListIterator< T >::current () [inline]
Returs the value pointed by the iterator.
If the iterator is not valid, returns NULL.
Returns:
T *
Referenced by KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviKvsObject::disconnectSignal(), KviKvsObject::emitSignal(), KviKvsTreeNodeDataList::evaluate(), KviKvsTreeNodeCompositeData::evaluateReadOnly(), KviKvsTreeNodeInstructionBlock::execute(), KviPointerHashTableIterator< Key, T >::operator*(), and KviKvsObject::~KviKvsObject().
template<typename T> bool KviPointerListIterator< T >::isValid () [inline]
Returns true if this iterator points to a valid element.
Returns false otherwise.
Returns:
bool
template<typename T> bool KviPointerListIterator< T >::moveFirst () [inline]
Moves the iterator to the first element of the list.
Returns true in case of success or false if the list is empty.
Returns:
bool
Referenced by KviPointerHashTableIterator< Key, T >::moveFirst(), and KviPointerHashTableIterator< Key, T >::moveNext().
template<typename T> bool KviPointerListIterator< T >::moveLast () [inline]
Moves the iterator to the last element of the list.
Returns true in case of success or false if the list is empty.
Returns:
bool
Referenced by KviPointerHashTableIterator< Key, T >::moveLast(), and KviPointerHashTableIterator< Key, T >::movePrev().
template<typename T> bool KviPointerListIterator< T >::moveNext () [inline]
Moves the iterator to the next element of the list.
The iterator must be actually valid for this function to work. Returns true in case of success or false if there is no next item.
Returns:
bool
Referenced by KviPointerHashTableIterator< Key, T >::moveNext().
template<typename T> bool KviPointerListIterator< T >::movePrev () [inline]
Moves the iterator to the previous element of the list.
The iterator must be actually valid for this function to work. Returns true in case of success or false if there is no previous item.
Returns:
bool
Referenced by KviPointerHashTableIterator< Key, T >::movePrev().
template<typename T> T* KviPointerListIterator< T >::operator* () [inline]
Returs the value pointed by the iterator.
If the iterator is not valid, returns NULL. This is just an alias to current().
Returns:
T *
template<typename T> bool KviPointerListIterator< T >::operator++ () [inline]
Moves the iterator to the next element of the list.
The iterator must be actually valid for this operator to work. Returns true in case of success or false if there is no next item. This is just a convenient alias to moveNext().
Returns:
bool
template<typename T> bool KviPointerListIterator< T >::operator-- () [inline]
Moves the iterator to the previous element of the list.
The iterator must be actually valid for this operator to work. Returns true in case of success or false if there is no previous item. This is just a convenient alias to movePrev().
Returns:
bool
template<typename T> void KviPointerListIterator< T >::operator= (const KviPointerListIterator< T > & src) [inline]
Creates an iterator copy.
The new iterator points exactly to the item pointed by src.
Parameters:
src The source item to copy
Returns:
void
Member Data Documentation
template<typename T> KviPointerList<T>* KviPointerListIterator< T >::m_pList [protected]
Referenced by KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::KviPointerListIterator(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::moveFirst(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::moveLast(), and KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::operator=().
template<typename T> KviPointerListNode* KviPointerListIterator< T >::m_pNode [protected]
Referenced by KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::current(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::isValid(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::KviPointerListIterator(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::moveFirst(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::moveLast(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::moveNext(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::movePrev(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::operator*(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::operator++(), KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::operator--(), and KviPointerListIterator< KviPointerHashTableEntry< Key, T > >::operator=().
The documentation for this class was generated from the following file:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerlist.h