KVIrc: LogListViewItem Class Reference
LogListViewItem Class Reference
#include <LogViewWidget.h>
Public Member Functions
virtual QString fileName () const
LogFile * log ()
LogListViewItem (QTreeWidget *pPar, LogFile::Type eType, LogFile *pLog)
LogListViewItem (QTreeWidgetItem *pPar, LogFile::Type eType, LogFile *pLog)
~LogListViewItem ()
Public Attributes
LogFile::Type m_eType
LogFile * m_pFileData
Constructor & Destructor Documentation
LogListViewItem::LogListViewItem (QTreeWidgetItem * pPar, LogFile::Type eType, LogFile * pLog)
References m_pFileData, and LogFile::name().
LogListViewItem::LogListViewItem (QTreeWidget * pPar, LogFile::Type eType, LogFile * pLog)
References m_pFileData, and LogFile::name().
LogListViewItem::~LogListViewItem () [inline]
Member Function Documentation
virtual QString LogListViewItem::fileName () const [inline, virtual]
Reimplemented in LogListViewLog.
Referenced by LogViewWindow::deleteCurrent().
LogFile* LogListViewItem::log () [inline]
References m_pFileData.
Referenced by LogViewWindow::exportLog().
Member Data Documentation
LogFile::Type LogListViewItem::m_eType
Referenced by LogViewWindow::filterNext(), and LogListViewItemType::LogListViewItemType().
LogFile* LogListViewItem::m_pFileData
Referenced by LogListViewLog::fileName(), log(), LogListViewItem(), LogListViewLog::LogListViewLog(), and LogListViewLog::operator<().
The documentation for this class was generated from the following files:
src/modules/logview/LogViewWidget.h
src/modules/logview/LogViewWidget.cpp