KVIrc: ScriptEditorImplementation Class Reference
ScriptEditorImplementation Class Reference
#include <ScriptEditorImplementation.h>
Signals
void find (const QString &)
void initFind ()
void nextFind (const QString &szText)
void replaceAll (const QString &szToReplace, const QString &szReplaceWith)
Public Member Functions
int cursor ()
QLineEdit * findLineEdit ()
int getCursor ()
virtual void getText (QString &szText)
virtual void getText (QByteArray &szText)
virtual bool isModified ()
ScriptEditorImplementation (QWidget *par)
void setCursorPosition (int iPos)
virtual void setEnabled (bool bEnabled)
virtual void setFindText (const QString &szText)
virtual void setFocus ()
virtual void setModified (bool)
virtual void setReadOnly (bool bReadOnly)
virtual void setText (const char *txt)
virtual void setText (const QString &szText)
virtual void setText (const QByteArray &szText)
void setUnHighlightedText (const QString &szText)
virtual ~ScriptEditorImplementation ()
Public Member Functions inherited from KviScriptEditor
virtual void setFindLineeditReadOnly (bool b)
virtual void setInfoText (const QString &text)
Public Attributes
QLineEdit * m_pFindLineEdit
Protected Slots
void configureColors ()
void loadFromFile ()
void optionsDialogFinished (int iResult)
void saveToFile ()
void slotFind ()
void slotInitFind ()
void slotNextFind (const QString &)
void slotReplaceAll (const QString &szToReplace, const QString &szReplaceWith)
void updateRowColLabel ()
Protected Member Functions
virtual void focusInEvent (QFocusEvent *e)
void loadOptions ()
void saveOptions ()
Protected Member Functions inherited from KviScriptEditor
KviScriptEditor (QWidget *par)
~KviScriptEditor ()
Protected Attributes
int m_lastCursorPos
ScriptEditorWidget * m_pEditor
ScriptEditorWidgetColorOptions * m_pOptionsDialog
QLabel * m_pRowColLabel
Protected Attributes inherited from KviScriptEditor
QLineEdit * m_pFindLineedit
Additional Inherited Members
Static Public Member Functions inherited from KviScriptEditor
static KviScriptEditor * createInstance (QWidget *par)
static void destroyInstance (KviScriptEditor *e)
static KviScriptEditor * getDummyEditor (QWidget *par)
Constructor & Destructor Documentation
ScriptEditorImplementation::ScriptEditorImplementation (QWidget * par)
References __tr2qs_ctx(), KviPointerList< T >::append(), configureColors(), connect(), g, g_clrFind(), g_pIconManager, KviIconManager::getSmallIcon(), KviPointerList< T >::isEmpty(), loadFromFile(), loadOptions(), m_lastCursorPos, m_pEditor, m_pFindLineEdit, m_pOptionsDialog, m_pRowColLabel, KviIconManager::Options, p, saveToFile(), slotFind(), and updateRowColLabel().
ScriptEditorImplementation::~ScriptEditorImplementation () virtual
References KviPointerList< T >::isEmpty(), m_pOptionsDialog, KviPointerList< T >::removeRef(), and saveOptions().
Member Function Documentation
void ScriptEditorImplementation::configureColors () protected slot
References connect(), m_pOptionsDialog, and optionsDialogFinished().
Referenced by ScriptEditorImplementation().
int ScriptEditorImplementation::cursor () inline
References m_lastCursorPos.
void ScriptEditorImplementation::find (const QString &) signal
Referenced by slotFind().
QLineEdit* ScriptEditorImplementation::findLineEdit () inline
References m_pFindLineEdit.
void ScriptEditorImplementation::focusInEvent (QFocusEvent * e) protected virtual
References m_pEditor.
int ScriptEditorImplementation::getCursor () inline virtual
Reimplemented from KviScriptEditor.
References m_pEditor.
void ScriptEditorImplementation::getText (QString & szText) virtual
Reimplemented from KviScriptEditor.
References m_pEditor.
void ScriptEditorImplementation::getText (QByteArray & szText) virtual
Reimplemented from KviScriptEditor.
References m_pEditor.
void ScriptEditorImplementation::initFind () signal
Referenced by slotInitFind().
bool ScriptEditorImplementation::isModified () virtual
Reimplemented from KviScriptEditor.
References m_pEditor.
void ScriptEditorImplementation::loadFromFile () protected slot
References __tr2qs_ctx(), KviFileDialog::askForOpenFileName(), KVI_FILTER_SCRIPT, KviFileUtils::loadFile(), m_pEditor, setCursorPosition(), szBuffer, and KviMessageBox::warning().
Referenced by ScriptEditorImplementation().
void ScriptEditorImplementation::loadOptions () protected
References g_clrBackground(), g_clrBracket(), g_clrComment(), g_clrFind(), g_clrFunction(), g_clrKeyword(), g_clrNormalText(), g_clrPunctuation(), g_clrVariable(), g_fntNormal(), KviModule::getDefaultConfigFileName(), KVI_SCRIPTEDITOR_DEFAULT_FONT, KviConfigurationFile::Read, KviConfigurationFile::readColorEntry(), and KviConfigurationFile::readFontEntry().
Referenced by ScriptEditorImplementation().
void ScriptEditorImplementation::nextFind (const QString & szText) signal
void ScriptEditorImplementation::optionsDialogFinished (int iResult) protected slot
References m_pEditor, saveOptions(), and ScriptEditorWidget::updateOptions().
Referenced by configureColors().
void ScriptEditorImplementation::replaceAll (const QString & szToReplace, const QString & szReplaceWith) signal
Referenced by slotReplaceAll().
void ScriptEditorImplementation::saveOptions () protected
References g_clrBackground(), g_clrBracket(), g_clrComment(), g_clrFind(), g_clrFunction(), g_clrKeyword(), g_clrNormalText(), g_clrPunctuation(), g_clrVariable(), g_fntNormal(), KviModule::getDefaultConfigFileName(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by optionsDialogFinished(), and ~ScriptEditorImplementation().
void ScriptEditorImplementation::saveToFile () protected slot
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), m_pEditor, szBuffer, KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by ScriptEditorImplementation().
void ScriptEditorImplementation::setCursorPosition (int iPos) virtual
Reimplemented from KviScriptEditor.
References m_pEditor, and updateRowColLabel().
Referenced by loadFromFile().
void ScriptEditorImplementation::setEnabled (bool bEnabled) virtual
References m_pEditor, and m_pRowColLabel.
void ScriptEditorImplementation::setFindText (const QString & szText) virtual
Reimplemented from KviScriptEditor.
References m_pEditor, m_pFindLineEdit, and ScriptEditorWidget::slotFind().
void ScriptEditorImplementation::setFocus () virtual
References m_pEditor.
void ScriptEditorImplementation::setModified (bool bModified) virtual
Reimplemented from KviScriptEditor.
References m_pEditor.
void ScriptEditorImplementation::setReadOnly (bool bReadOnly) virtual
Reimplemented from KviScriptEditor.
References m_pEditor.
void ScriptEditorImplementation::setText (const char * txt) virtual
Reimplemented from KviScriptEditor.
void ScriptEditorImplementation::setText (const QString & szText) virtual
Reimplemented from KviScriptEditor.
References ScriptEditorWidget::enableSyntaxHighlighter(), m_pEditor, and updateRowColLabel().
void ScriptEditorImplementation::setText (const QByteArray & szText) virtual
Reimplemented from KviScriptEditor.
References m_pEditor, and updateRowColLabel().
void ScriptEditorImplementation::setUnHighlightedText (const QString & szText) virtual
Reimplemented from KviScriptEditor.
References ScriptEditorWidget::disableSyntaxHighlighter(), and m_pEditor.
void ScriptEditorImplementation::slotFind () protected slot
References find(), and m_pFindLineEdit.
Referenced by ScriptEditorImplementation().
void ScriptEditorImplementation::slotInitFind () protected slot
References initFind().
void ScriptEditorImplementation::slotNextFind (const QString &) protected slot
void ScriptEditorImplementation::slotReplaceAll (const QString & szToReplace, const QString & szReplaceWith) protected slot
References replaceAll().
void ScriptEditorImplementation::updateRowColLabel () protected slot
References __tr2qs_ctx(), m_lastCursorPos, m_pEditor, and m_pRowColLabel.
Referenced by ScriptEditorImplementation(), setCursorPosition(), and setText().
Member Data Documentation
int ScriptEditorImplementation::m_lastCursorPos protected
Referenced by cursor(), ScriptEditorImplementation(), and updateRowColLabel().
ScriptEditorWidget* ScriptEditorImplementation::m_pEditor protected
Referenced by focusInEvent(), getCursor(), getText(), isModified(), loadFromFile(), optionsDialogFinished(), saveToFile(), ScriptEditorImplementation(), setCursorPosition(), setEnabled(), setFindText(), setFocus(), setModified(), setReadOnly(), setText(), setUnHighlightedText(), and updateRowColLabel().
QLineEdit* ScriptEditorImplementation::m_pFindLineEdit
Referenced by findLineEdit(), ScriptEditorImplementation(), setFindText(), and slotFind().
ScriptEditorWidgetColorOptions* ScriptEditorImplementation::m_pOptionsDialog protected
Referenced by configureColors(), ScriptEditorImplementation(), and ~ScriptEditorImplementation().
QLabel* ScriptEditorImplementation::m_pRowColLabel protected
Referenced by ScriptEditorImplementation(), setEnabled(), and updateRowColLabel().
The documentation for this class was generated from the following files:
src/modules/editor/ScriptEditorImplementation.h
src/modules/editor/ScriptEditorImplementation.cpp