KVIrc: KviKvsTreeNodeOperationSelfMultiplication Class Reference
KviKvsTreeNodeOperationSelfMultiplication Class Reference
#include <KviKvsTreeNodeOperation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationSelfMultiplication (const QChar *pLocation, KviKvsTreeNodeData *pRightSide)
~KviKvsTreeNodeOperationSelfMultiplication ()
Protected Attributes
KviKvsTreeNodeData * m_pRightSide
Constructor & Destructor Documentation
KviKvsTreeNodeOperationSelfMultiplication::KviKvsTreeNodeOperationSelfMultiplication (const QChar * pLocation, KviKvsTreeNodeData * pRightSide)
References m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationSelfMultiplication::~KviKvsTreeNodeOperationSelfMultiplication ()
References m_pRightSide.
Member Function Documentation
void KviKvsTreeNodeOperationSelfMultiplication::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationSelfMultiplication::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pRightSide, and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationSelfMultiplication::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsVariant::asNumber(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsNumber::integer(), KviKvsNumber::isInteger(), m_pRightSide, KviKvsTreeNodeOperation::m_pTargetData, KviKvsNumber::real(), KviKvsRWEvaluationResult::result(), KviKvsVariant::setInteger(), KviKvsVariant::setReal(), and v.
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationSelfMultiplication::m_pRightSide [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationSelfMultiplication(), and ~KviKvsTreeNodeOperationSelfMultiplication().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.h
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.cpp