KVIrc: KviHistoryWindow Class Reference
KviHistoryWindow Class Reference
History window class.
#include <kvi_historywin.h>
Public Slots
void itemSelected (QListWidgetItem *pItem)
Called when an item is selected.
void ownerDead ()
Called when the owner is dead.
Public Member Functions
void doHide ()
Hides the parent and set the focus to the owner.
KviHistoryWindow (QWidget *pParent)
Constructs the history window object.
void popup (KviInput *pOwner)
Shows the popup.
~KviHistoryWindow ()
Destroys the history window object.
Private Member Functions
void fill ()
Fills in the window with strings from input history.
virtual void hideEvent (QHideEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void show ()
Shows the widget.
virtual void timerEvent (QTimerEvent *e)
Private Attributes
int m_iTimerId
KviInput * m_pOwner
QWidget * m_pParent
Detailed Description
History window class.
Constructor & Destructor Documentation
KviHistoryWindow::KviHistoryWindow (QWidget * pParent)
Constructs the history window object.
Parameters:
pParent The parent widget
Returns:
KviHistoryWindow
References itemSelected(), m_iTimerId, m_pOwner, and m_pParent.
KviHistoryWindow::~KviHistoryWindow ()
Destroys the history window object.
References m_iTimerId.
Member Function Documentation
void KviHistoryWindow::doHide ()
Hides the parent and set the focus to the owner.
Returns:
void
References m_iTimerId, m_pOwner, m_pParent, and KviInput::setFocus().
Referenced by itemSelected(), keyPressEvent(), mousePressEvent(), ownerDead(), and timerEvent().
void KviHistoryWindow::fill () [private]
Fills in the window with strings from input history.
Returns:
void
References KviInputHistory::instance(), KviInputHistory::list(), and KviPointerList< T >::prev().
Referenced by popup().
void KviHistoryWindow::hideEvent (QHideEvent * e) [private, virtual]
References m_iTimerId.
void KviHistoryWindow::itemSelected (QListWidgetItem * pItem) [slot]
Called when an item is selected.
Parameters:
pItem The selected item
Returns:
void
References doHide(), m_pOwner, and KviInput::setText().
Referenced by KviHistoryWindow().
void KviHistoryWindow::keyPressEvent (QKeyEvent * e) [private, virtual]
References doHide(), g_pApp, and m_pOwner.
void KviHistoryWindow::mousePressEvent (QMouseEvent * e) [private, virtual]
References doHide().
void KviHistoryWindow::ownerDead () [slot]
Called when the owner is dead.
Returns:
void
References doHide(), and m_pOwner.
Referenced by popup().
void KviHistoryWindow::popup (KviInput * pOwner)
Shows the popup.
Parameters:
pOwner The owner of the popup
Returns:
void
References fill(), m_pOwner, ownerDead(), and show().
Referenced by KviHistoryWindowWidget::popup().
void KviHistoryWindow::show () [private, virtual]
Shows the widget.
Returns:
void
References m_iTimerId.
Referenced by popup().
void KviHistoryWindow::timerEvent (QTimerEvent * e) [private, virtual]
References doHide(), m_iTimerId, and m_pOwner.
Member Data Documentation
int KviHistoryWindow::m_iTimerId [private]
Referenced by doHide(), hideEvent(), KviHistoryWindow(), show(), timerEvent(), and ~KviHistoryWindow().
KviInput* KviHistoryWindow::m_pOwner [private]
Referenced by doHide(), itemSelected(), keyPressEvent(), KviHistoryWindow(), ownerDead(), popup(), and timerEvent().
QWidget* KviHistoryWindow::m_pParent [private]
Referenced by doHide(), and KviHistoryWindow().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_historywin.h
src/kvirc/ui/kvi_historywin.cpp