KVIrc: KviMaskItem Class Reference
KviMaskItem Class Reference
#include <kvi_maskeditor.h>
Public Member Functions
virtual int compare (QTreeWidgetItem *i, int col, bool ascending) const
KviMaskItem (QTreeWidget *parent, KviMaskEntry *entry)
KviMaskEntry * mask ()
~KviMaskItem ()
Protected Attributes
KviMaskEntry m_Mask
Constructor & Destructor Documentation
KviMaskItem::KviMaskItem (QTreeWidget * parent, KviMaskEntry * entry)
References KVI_OPTION_UINT, KviOption_uintOutputDatetimeFormat, and mask().
KviMaskItem::~KviMaskItem ()
Member Function Documentation
int KviMaskItem::compare (QTreeWidgetItem * i, int col, bool ascending) const [virtual]
References m_Mask, mask(), and _KviMaskEntry::uSetAt.
KviMaskEntry* KviMaskItem::mask () [inline]
References m_Mask.
Referenced by compare(), KviMaskItem(), KviMaskEditor::removeClicked(), KviMaskEditor::removeMask(), and KviMaskEditor::searchTextChanged().
Member Data Documentation
KviMaskEntry KviMaskItem::m_Mask [protected]
Referenced by compare(), and mask().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_maskeditor.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_maskeditor.cpp