KVIrc: RegisteredUsersDialogItemDelegate Class Reference
RegisteredUsersDialogItemDelegate Class Reference
#include <RegisteredUsersDialog.h>
Public Member Functions
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
RegisteredUsersDialogItemDelegate (KviRegisteredUsersListView *pWidget=0)
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
~RegisteredUsersDialogItemDelegate ()
Constructor & Destructor Documentation
RegisteredUsersDialogItemDelegate::RegisteredUsersDialogItemDelegate (KviRegisteredUsersListView * pWidget = 0) [inline]
RegisteredUsersDialogItemDelegate::~RegisteredUsersDialogItemDelegate () [inline]
Member Function Documentation
void RegisteredUsersDialogItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const
References g_pIconManager, KviIconManager::getBigIcon(), KviRegisteredUser::getProperty(), KviIconManager::getSmallIcon(), RegisteredUsersDialogItemBase::Group, KviIconManager::Ignore, KviRegisteredUser::ignoreEnagled(), KVI_BIGICON_REGUSERS, LVI_BORDER, LVI_ICON_SIZE, LVI_SPACING, RegisteredUsersDialogItem::m_pText, KviIconManager::NotifyOffLine, KviIconManager::NotifyOnLine, RegisteredUsersDialogItemBase::type(), and RegisteredUsersDialogItem::user().
QSize RegisteredUsersDialogItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const
References RegisteredUsersDialogItemBase::Group, LVI_BORDER, LVI_ICON_SIZE, and RegisteredUsersDialogItemBase::type().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUsersDialog.h
src/modules/reguser/RegisteredUsersDialog.cpp