KVIrc: DccVoiceCodec Class Reference
DccVoiceCodec Class Reference
#include <DccVoiceCodec.h>
Public Member Functions
DccVoiceCodec ()
virtual void decode (KviDataBuffer *stream, KviDataBuffer *signal)
virtual int decodedFrameSize ()
virtual void encode (KviDataBuffer *signal, KviDataBuffer *stream)
virtual int encodedFrameSize ()
const char * name ()
virtual ~DccVoiceCodec ()
Protected Attributes
KviCString m_szName
Constructor & Destructor Documentation
DccVoiceCodec::DccVoiceCodec ()
DccVoiceCodec::~DccVoiceCodec () [virtual]
Member Function Documentation
void DccVoiceCodec::decode (KviDataBuffer * stream, KviDataBuffer * signal) [virtual]
Reimplemented in DccVoiceAdpcmCodec, and DccVoiceNullCodec.
Referenced by DccVoiceThread::readWriteStep().
int DccVoiceCodec::decodedFrameSize () [virtual]
Reimplemented in DccVoiceAdpcmCodec, and DccVoiceNullCodec.
Referenced by DccVoiceThread::run().
void DccVoiceCodec::encode (KviDataBuffer * signal, KviDataBuffer * stream) [virtual]
Reimplemented in DccVoiceAdpcmCodec, and DccVoiceNullCodec.
Referenced by DccVoiceThread::soundStep().
int DccVoiceCodec::encodedFrameSize () [virtual]
Reimplemented in DccVoiceAdpcmCodec, and DccVoiceNullCodec.
Referenced by DccVoiceThread::run().
const char * DccVoiceCodec::name ()
References m_szName, and KviCString::ptr().
Referenced by DccVoiceWindow::connected().
Member Data Documentation
KviCString DccVoiceCodec::m_szName [protected]
Referenced by DccVoiceAdpcmCodec::DccVoiceAdpcmCodec(), DccVoiceNullCodec::DccVoiceNullCodec(), and name().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceCodec.h
src/modules/dcc/DccVoiceCodec.cpp