KVIrc: KviTreeWindowListTreeWidget Class Reference
KviTreeWindowListTreeWidget Class Reference
#include <kvi_windowlist_tree.h>
Public Slots
void reverseSort ()
void sort ()
Signals
void leftMousePress (QTreeWidgetItem *it)
void rightMousePress (QTreeWidgetItem *it)
Public Member Functions
KviTreeWindowListTreeWidget (QWidget *par)
~KviTreeWindowListTreeWidget ()
Protected Member Functions
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *event)
Private Member Functions
KviWindowListItem * lastItem ()
Private Attributes
KviTreeWindowListItem * m_pPrevItem
Friends
class KviTreeWindowListItem
class KviTreeWindowListItemDelegate
Constructor & Destructor Documentation
KviTreeWindowListTreeWidget::KviTreeWindowListTreeWidget (QWidget * par)
References KVI_OPTION_FONT, KviOption_fontTreeWindowList, and m_pPrevItem.
KviTreeWindowListTreeWidget::~KviTreeWindowListTreeWidget ()
Member Function Documentation
KviWindowListItem* KviTreeWindowListTreeWidget::lastItem () [private]
void KviTreeWindowListTreeWidget::leftMousePress (QTreeWidgetItem * it) [signal]
void KviTreeWindowListTreeWidget::mouseDoubleClickEvent (QMouseEvent * e) [protected, virtual]
void KviTreeWindowListTreeWidget::mouseMoveEvent (QMouseEvent * e) [protected, virtual]
void KviTreeWindowListTreeWidget::mousePressEvent (QMouseEvent * e) [protected, virtual]
References __tr2qs, KviWindow::contextPopup(), KviWindow::delayedClose(), g_pActiveWindow, g_pFrame, KviTalPopupMenu::insertItem(), KviWindow::isMinimized(), KviWindowListItem::kviWindow(), KviWindow::minimize(), reverseSort(), KviFrame::setActiveWindow(), and sort().
void KviTreeWindowListTreeWidget::paintEvent (QPaintEvent * event) [protected, virtual]
References KviPixmapUtils::drawPixmapWithPainter(), g_pApp, g_pFrame, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorTreeWindowListBackground, KviOption_pixmapTreeWindowListBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviOption_uintTreeWindowListPixmapAlign, and KviApp::supportsCompositing().
void KviTreeWindowListTreeWidget::reverseSort () [slot]
Referenced by mousePressEvent().
void KviTreeWindowListTreeWidget::rightMousePress (QTreeWidgetItem * it) [signal]
void KviTreeWindowListTreeWidget::sort () [slot]
Referenced by mousePressEvent().
Friends And Related Function Documentation
friend class KviTreeWindowListItem [friend]
friend class KviTreeWindowListItemDelegate [friend]
Member Data Documentation
KviTreeWindowListItem* KviTreeWindowListTreeWidget::m_pPrevItem [private]
Referenced by KviTreeWindowListTreeWidget(), and KviTreeWindowListItem::~KviTreeWindowListItem().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_windowlist_tree.h
src/kvirc/ui/kvi_windowlist_tree.cpp