KVIrc: KviIrcConnectionTarget Class Reference
KviIrcConnectionTarget Class Reference
#include <kvi_ircconnectiontarget.h>
Public Member Functions
const QString & bindAddress ()
bool hasBindAddress ()
KviIrcConnectionTarget (const KviNetwork *pNetwork, const KviServer *pServer, const KviProxy *pProxy=0, const QString &szBindAddress=QString())
KviNetwork * network ()
const QString & networkName ()
KviProxy * proxy ()
KviServer * server ()
void setNetworkName (const QString &szNetName)
~KviIrcConnectionTarget ()
Protected Member Functions
void clearProxy ()
void setBindAddress (const QString &szBindAddress)
Private Attributes
KviNetwork * m_pNetwork
KviProxy * m_pProxy
KviServer * m_pServer
QString m_szBindAddress
Friends
class KviIrcConnectionTargetResolver
Constructor & Destructor Documentation
KviIrcConnectionTarget::KviIrcConnectionTarget (const KviNetwork * pNetwork, const KviServer * pServer, const KviProxy * pProxy = 0, const QString & szBindAddress = QString())
References m_pNetwork, m_pProxy, m_pServer, and m_szBindAddress.
KviIrcConnectionTarget::~KviIrcConnectionTarget ()
References m_pNetwork, m_pProxy, and m_pServer.
Member Function Documentation
const QString& KviIrcConnectionTarget::bindAddress () [inline]
Referenced by KviIrcConnectionTargetResolver::haveServerIp(), and KviIrcLink::resolverTerminated().
void KviIrcConnectionTarget::clearProxy () [protected]
References m_pProxy.
Referenced by KviIrcConnectionTargetResolver::lookupProxyHostname(), and KviIrcConnectionTargetResolver::proxyLookupTerminated().
bool KviIrcConnectionTarget::hasBindAddress () [inline]
Referenced by KviIrcConnectionTargetResolver::haveServerIp().
KviNetwork* KviIrcConnectionTarget::network () [inline]
Referenced by KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviServerParser::parseLiteralNotice(), KviMdiChild::setClient(), KviIrcConnection::setupSrvCodec(), and KviIrcConnection::setupTextCodec().
const QString & KviIrcConnectionTarget::networkName ()
References m_pNetwork, and KviNetwork::name().
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcConnection::networkName(), and KviIrcConnection::registerChannel().
KviProxy* KviIrcConnectionTarget::proxy () [inline]
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), KviIrcLink::resolverTerminated(), and KviIrcLink::socketStateChange().
KviServer* KviIrcConnectionTarget::server () [inline]
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcContext::connectionEstabilished(), KviIrcContext::connectionFailed(), KviIrcConnectionTargetResolver::haveServerIp(), KviConsole::isIPv6Connection(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcLink::resolverTerminated(), KviIrcUrl::run(), KviIrcConnectionTargetResolver::serverLookupTerminated(), KviIrcConnection::setupSrvCodec(), KviIrcConnection::setupTextCodec(), KviIrcLink::socketStateChange(), KviConsole::updateUri(), and KviIrcConnectionTargetResolver::validateLocalAddress().
void KviIrcConnectionTarget::setBindAddress (const QString & szBindAddress) [inline, protected]
Referenced by KviIrcConnectionTargetResolver::haveServerIp().
void KviIrcConnectionTarget::setNetworkName (const QString & szNetName)
References m_pNetwork, and KviNetwork::setName().
Referenced by KviServerParser::parseNumeric005().
Friends And Related Function Documentation
friend class KviIrcConnectionTargetResolver [friend]
Member Data Documentation
KviNetwork* KviIrcConnectionTarget::m_pNetwork [private]
Referenced by KviIrcConnectionTarget(), networkName(), setNetworkName(), and ~KviIrcConnectionTarget().
KviProxy* KviIrcConnectionTarget::m_pProxy [private]
Referenced by clearProxy(), KviIrcConnectionTarget(), and ~KviIrcConnectionTarget().
KviServer* KviIrcConnectionTarget::m_pServer [private]
Referenced by KviIrcConnectionTarget(), and ~KviIrcConnectionTarget().
QString KviIrcConnectionTarget::m_szBindAddress [private]
Referenced by KviIrcConnectionTarget().
The documentation for this class was generated from the following files:
src/kvirc/kernel/kvi_ircconnectiontarget.h
src/kvirc/kernel/kvi_ircconnectiontarget.cpp