KVIrc: KviCellItemDelegate Class Reference
KviCellItemDelegate Class Reference
#include <KvsObject_tableWidget.h>
Public Member Functions
KviCellItemDelegate (QAbstractItemView *pWidget=0, KvsObject_tableWidget *pParent=0)
void paint (QPainter *pPainter, const QStyleOptionViewItem &option, const QModelIndex &index) const
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
~KviCellItemDelegate ()
Protected Attributes
KvsObject_tableWidget * m_pParentScript
Constructor & Destructor Documentation
KviCellItemDelegate::KviCellItemDelegate (QAbstractItemView * pWidget = 0, KvsObject_tableWidget * pParent = 0)
KviCellItemDelegate::~KviCellItemDelegate ()
Member Function Documentation
void KviCellItemDelegate::paint (QPainter * pPainter, const QStyleOptionViewItem & option, const QModelIndex & index) const
References m_pParentScript, and KvsObject_tableWidget::paint().
QSize KviCellItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const
References KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsArray::at(), KviKvsObject::callFunction(), h, KviKvsVariant::isArray(), m_pParentScript, KviKvsArray::size(), and w.
Member Data Documentation
KvsObject_tableWidget* KviCellItemDelegate::m_pParentScript protected
Referenced by paint(), and sizeHint().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_tableWidget.h
src/modules/objects/KvsObject_tableWidget.cpp