KVIrc: DccVoiceAdpcmCodec Class Reference
DccVoiceAdpcmCodec Class Reference
#include <DccVoiceAdpcmCodec.h>
Public Member Functions
DccVoiceAdpcmCodec ()
virtual void decode (KviDataBuffer *stream, KviDataBuffer *signal)
virtual int decodedFrameSize ()
virtual void encode (KviDataBuffer *signal, KviDataBuffer *stream)
virtual int encodedFrameSize ()
virtual ~DccVoiceAdpcmCodec ()
Private Attributes
ADPCM_state * m_pDecodeState
ADPCM_state * m_pEncodeState
Constructor & Destructor Documentation
DccVoiceAdpcmCodec::DccVoiceAdpcmCodec ()
References adpcm_state::index, m_pDecodeState, m_pEncodeState, DccVoiceCodec::m_szName, and adpcm_state::valprev.
DccVoiceAdpcmCodec::~DccVoiceAdpcmCodec () [virtual]
References m_pDecodeState, and m_pEncodeState.
Member Function Documentation
void DccVoiceAdpcmCodec::decode (KviDataBuffer * stream, KviDataBuffer * signal) [virtual]
Reimplemented from DccVoiceCodec.
References KviDataBuffer::addSize(), ADPCM_PACKED_FRAME_SIZE_IN_BYTES, ADPCM_uncompress(), ADPCM_UNPACKED_FRAME_SIZE_IN_BYTES, ADPCM_UNPACKED_FRAME_SIZE_IN_SHORTS, KviDataBuffer::data(), m_pDecodeState, KviDataBuffer::remove(), and KviDataBuffer::size().
int DccVoiceAdpcmCodec::decodedFrameSize () [virtual]
Reimplemented from DccVoiceCodec.
References ADPCM_UNPACKED_FRAME_SIZE_IN_BYTES.
void DccVoiceAdpcmCodec::encode (KviDataBuffer * signal, KviDataBuffer * stream) [virtual]
Reimplemented from DccVoiceCodec.
References KviDataBuffer::addSize(), ADPCM_compress(), ADPCM_PACKED_FRAME_SIZE_IN_BYTES, ADPCM_UNPACKED_FRAME_SIZE_IN_BYTES, ADPCM_UNPACKED_FRAME_SIZE_IN_SHORTS, KviDataBuffer::data(), m_pEncodeState, KviDataBuffer::remove(), and KviDataBuffer::size().
int DccVoiceAdpcmCodec::encodedFrameSize () [virtual]
Reimplemented from DccVoiceCodec.
References ADPCM_PACKED_FRAME_SIZE_IN_BYTES.
Member Data Documentation
ADPCM_state* DccVoiceAdpcmCodec::m_pDecodeState [private]
Referenced by DccVoiceAdpcmCodec(), decode(), and ~DccVoiceAdpcmCodec().
ADPCM_state* DccVoiceAdpcmCodec::m_pEncodeState [private]
Referenced by DccVoiceAdpcmCodec(), encode(), and ~DccVoiceAdpcmCodec().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceAdpcmCodec.h
src/modules/dcc/DccVoiceAdpcmCodec.cpp