KVIrc: KviKvsTreeNodeSpecialCommandForeach Class Reference
KviKvsTreeNodeSpecialCommandForeach Class Reference
#include <KviKvsTreeNodeSpecialCommandForeach.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandForeach (const QChar *pLocation, KviKvsTreeNodeData *pVar, KviKvsTreeNodeDataList *pArgs, KviKvsTreeNodeInstruction *pLoop)
~KviKvsTreeNodeSpecialCommandForeach ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommand
KviKvsTreeNodeSpecialCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeSpecialCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviKvsTreeNodeDataList * m_pIterationData
KviKvsTreeNodeData * m_pIterationVariable
KviKvsTreeNodeInstruction * m_pLoop
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandForeach::KviKvsTreeNodeSpecialCommandForeach (const QChar * pLocation, KviKvsTreeNodeData * pVar, KviKvsTreeNodeDataList * pArgs, KviKvsTreeNodeInstruction * pLoop)
References m_pIterationData, m_pIterationVariable, m_pLoop, and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandForeach::~KviKvsTreeNodeSpecialCommandForeach ()
References m_pIterationData, m_pIterationVariable, and m_pLoop.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandForeach::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandForeach::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
References KviKvsTreeNodeData::dump(), KviKvsTreeNodeDataList::dump(), KviKvsTreeNodeInstruction::dump(), m_pIterationData, m_pIterationVariable, and m_pLoop.
bool KviKvsTreeNodeSpecialCommandForeach::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariantData::Array, KviKvsVariant::array(), KviKvsArray::at(), KviKvsRunTimeContext::breakPending(), KviKvsRunTimeContext::continuePending(), KviKvsVariant::copyFrom(), KviKvsRunTimeContext::error(), KviKvsTreeNodeDataList::evaluate(), KviKvsTreeNodeSwitchList::evaluate(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeInstruction::execute(), KviKvsSwitchList::find(), KviKvsVariantList::first(), KviKvsRunTimeContext::handleBreak(), KviKvsRunTimeContext::handleContinue(), KviKvsVariantData::Hash, KviKvsVariant::isEmpty(), l, m_pIterationData, m_pIterationVariable, m_pLoop, KviKvsTreeNodeCommand::m_pSwitches, KviKvsVariantList::next(), KviKvsRWEvaluationResult::result(), KviKvsVariantList::setAutoDelete(), KviKvsVariant::setNothing(), swl, and v.
Member Data Documentation
KviKvsTreeNodeDataList* KviKvsTreeNodeSpecialCommandForeach::m_pIterationData private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandForeach(), and ~KviKvsTreeNodeSpecialCommandForeach().
KviKvsTreeNodeData* KviKvsTreeNodeSpecialCommandForeach::m_pIterationVariable private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandForeach(), and ~KviKvsTreeNodeSpecialCommandForeach().
KviKvsTreeNodeInstruction* KviKvsTreeNodeSpecialCommandForeach::m_pLoop private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandForeach(), and ~KviKvsTreeNodeSpecialCommandForeach().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandForeach.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandForeach.cpp