KVIrc: KviConfig Class Reference
KviConfig Class Reference
#include <kvi_config.h>
Public Types
enum FileMode { Read = 1, Write = 2, ReadWrite = 3 }
Public Member Functions
void clear ()
void clearDirtyFlag ()
void clearGroup (const QString &szGroup)
void clearKey (const QString &szKey)
KviPointerHashTable< QString,
KviConfigGroup > * dict ()
bool dirty ()
bool ensureWritable ()
const QString & fileName ()
const QString & group ()
unsigned int groupsCount ()
bool hasGroup (const QString &szGroup)
bool hasKey (const QString &szKey)
KviConfig (const QString &filename, FileMode f, bool bLocal8Bit=false)
KviConfig (const char *filename, FileMode f, bool bLocal8Bit=false)
void preserveEmptyGroups (bool bPreserve)
bool readBoolEntry (const QString &szKey, bool bTrue)
char readCharEntry (const QString &szKey, char iDefault)
QColor readColorEntry (const QString &szKey, const QColor &clr)
QString readEntry (const QString &szKey, const QString &szDefault=QString())
QFont readFontEntry (const QString &szKey, const QFont &fnt)
int readIntEntry (const QString &szKey, int iDefault)
QList< int > readIntListEntry (const QString &, const QList< int > &list)
QString readKviStrEntry (const QString &szKey, const KviStr &szDefault)
KviMsgType readMsgTypeEntry (const QString &szKey, const KviMsgType &msgDef)
bool readOnly ()
KviPixmap readPixmapEntry (const QString &szKey, const KviPixmap &pixDef)
QRect readRectEntry (const QString &szKey, const QRect &rct)
QStringList readStringListEntry (const QString &szKey, const QStringList &list=QStringList())
unsigned char readUCharEntry (const QString &szKey, unsigned char iDefault)
unsigned int readUIntEntry (const QString &szKey, unsigned int iDefault)
unsigned short int readUShortEntry (const QString &szKey, unsigned short int usDefault)
void setGroup (const QString &szGroup)
void setReadOnly (bool bReadOnly)
void setSavePath (const QString &savePath)
bool sync ()
void writeEntry (const QString &szKey, unsigned short int usValue)
void writeEntry (const QString &szKey, const QStringList &list)
void writeEntry (const QString &szKey, const QColor &clr)
void writeEntry (const QString &szKey, bool bTrue)
void writeEntry (const QString &szKey, const char *szValue)
void writeEntry (const QString &szKey, int iValue)
void writeEntry (const QString &szKey, QFont &fnt)
void writeEntry (const QString &szKey, const QString &szValue)
void writeEntry (const QString &szKey, unsigned char iValue)
void writeEntry (const QString &szKey, const QRect &rct)
void writeEntry (const QString &szKey, char iValue)
void writeEntry (const QString &szKey, const QList< int > &list)
void writeEntry (const QString &szKey, unsigned int iValue)
void writeEntry (const QString &szKey, const KviPixmap &pixmap)
void writeEntry (const QString &szKey, const KviMsgType &msg)
~KviConfig ()
Static Public Member Functions
static void getFontProperties (KviStr &buffer, QFont *fnt)
static void setFontProperties (KviStr &str, QFont *fnt)
Private Member Functions
KviConfigGroup * getCurrentGroup ()
bool load ()
bool save ()
Private Attributes
bool m_bDirty
bool m_bLocal8Bit
bool m_bPreserveEmptyGroups
bool m_bReadOnly
KviPointerHashTable< QString,
KviConfigGroup > * m_pDict
QString m_szFileName
QString m_szGroup
QString m_szStrBuffer
Member Enumeration Documentation
enum KviConfig::FileMode
Enumerator:
Read
Write
ReadWrite
Constructor & Destructor Documentation
KviConfig::KviConfig (const QString & filename, FileMode f, bool bLocal8Bit = false)
References KVI_CONFIG_DEFAULT_GROUP, load(), m_bDirty, m_bLocal8Bit, m_bPreserveEmptyGroups, m_bReadOnly, m_pDict, m_szFileName, m_szGroup, Read, KviPointerHashTable< Key, T >::setAutoDelete(), and Write.
KviConfig::KviConfig (const char * filename, FileMode f, bool bLocal8Bit = false)
References KVI_CONFIG_DEFAULT_GROUP, load(), m_bDirty, m_bLocal8Bit, m_bPreserveEmptyGroups, m_bReadOnly, m_pDict, m_szFileName, m_szGroup, Read, KviPointerHashTable< Key, T >::setAutoDelete(), and Write.
KviConfig::~KviConfig ()
References m_bDirty, m_pDict, and save().
Member Function Documentation
void KviConfig::clear ()
References KVI_CONFIG_DEFAULT_GROUP, m_bDirty, m_pDict, m_szGroup, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by KviInputHistory::save(), KviKvsScriptAddonManager::save(), KviKvsPopupManager::save(), KviKvsAliasManager::save(), KviThemeInfo::save(), KviDefaultScriptManager::save(), KviActionManager::save(), KviUserIdentityManager::save(), KviNickServRuleSet::save(), KviServerDataBase::save(), KviIdentityProfileSet::save(), KviSharedFilesManager::save(), KviRegisteredUserDataBase::save(), KviRegisteredChannelDataBase::save(), KviProxyDataBase::save(), KviMediaManager::save(), KviKvsEventManager::saveAppEvents(), and KviKvsEventManager::saveRawEvents().
void KviConfig::clearDirtyFlag () [inline]
void KviConfig::clearGroup (const QString & szGroup)
References KviPointerHashTable< Key, T >::find(), KVI_CONFIG_DEFAULT_GROUP, m_bDirty, m_pDict, m_szGroup, and KviPointerHashTable< Key, T >::remove().
Referenced by clearKey(), and KviFrame::saveWindowProperties().
void KviConfig::clearKey (const QString & szKey)
References clearGroup(), KviPointerHashTable< Key, T >::count(), getCurrentGroup(), m_bDirty, m_szGroup, and KviPointerHashTable< Key, T >::remove().
KviPointerHashTable<QString,KviConfigGroup>* KviConfig::dict () [inline]
Referenced by KviKvsScriptAddonManager::delayedLoad(), KviKvsPopupManager::load(), KviKvsAliasManager::load(), KviTextIconManager::load(), KviCustomToolBarManager::load(), KviActionManager::load(), KviUserIdentityManager::load(), KviServerDataBase::load(), KviAvatarCache::load(), KviRegisteredUserDataBase::load(), KviRegisteredChannelDataBase::load(), save(), and KviFrame::saveWindowProperties().
bool KviConfig::dirty () [inline]
bool KviConfig::ensureWritable ()
References m_bReadOnly, and m_szFileName.
Referenced by KviApp::saveOptions().
const QString& KviConfig::fileName () [inline]
KviConfigGroup * KviConfig::getCurrentGroup () [private]
References KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), KVI_CONFIG_DEFAULT_GROUP, m_pDict, m_szGroup, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by clearKey(), hasKey(), readBoolEntry(), readCharEntry(), readColorEntry(), readEntry(), readFontEntry(), readIntEntry(), readIntListEntry(), readMsgTypeEntry(), readPixmapEntry(), readRectEntry(), readStringListEntry(), readUCharEntry(), readUIntEntry(), readUShortEntry(), setGroup(), and writeEntry().
void KviConfig::getFontProperties (KviStr & buffer, QFont * fnt) [static]
References KviStringConversion::toString().
const QString& KviConfig::group () [inline]
Referenced by KviKvsUserAction::load(), KviCustomToolBarDescriptor::load(), KviUserIdentity::load(), and save().
unsigned int KviConfig::groupsCount () [inline]
Referenced by KviFrame::saveWindowProperties().
bool KviConfig::hasGroup (const QString & szGroup)
References KviPointerHashTable< Key, T >::find(), and m_pDict.
Referenced by KviFrame::addWindow(), KviServerDataBase::importFromMircIni(), KviKvsEventManager::loadAppEvents(), KviKvsEventManager::loadRawEvents(), KviKvsEventManager::saveAppEvents(), and setGroup().
bool KviConfig::hasKey (const QString & szKey)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
Referenced by KviTheme::load().
bool KviConfig::load () [private]
References KviPointerHashTable< Key, T >::find(), KviStr::hexDecode(), KviPointerHashTable< Key, T >::insert(), KviStr::isEmpty(), KVI_CONFIG_DEFAULT_GROUP, kvi_free, kvi_malloc, kvi_memmove(), kvi_realloc, KviStr::len(), LOAD_BLOCK_SIZE, m_bLocal8Bit, m_pDict, m_szFileName, KviStr::ptr(), KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviStr::stripRightWhiteSpace().
Referenced by KviConfig().
void KviConfig::preserveEmptyGroups (bool bPreserve) [inline]
Referenced by KviRegisteredUserDataBase::save(), and KviRegisteredChannelDataBase::save().
bool KviConfig::readBoolEntry (const QString & szKey, bool bTrue)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
Referenced by KviFrame::addWindow(), KviServerDataBase::load(), KviServer::load(), KviRegisteredUserDataBase::load(), KviProxyDataBase::load(), KviKvsEventManager::loadAppEvents(), KviNickServRuleSet::loadPrivate(), KviIdentityProfileSet::loadPrivate(), KviWindow::loadProperties(), KviQuery::loadProperties(), KviConsole::loadProperties(), KviChannel::loadProperties(), KviKvsEventManager::loadRawEvents(), KviStatusBarUpdateIndicator::loadState(), KviStatusBarConnectionTimer::loadState(), KviStatusBarClock::loadState(), and KviStatusBarAwayIndicator::loadState().
char KviConfig::readCharEntry (const QString & szKey, char iDefault)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
QColor KviConfig::readColorEntry (const QString & szKey, const QColor & clr)
References KviPointerHashTable< Key, T >::find(), getCurrentGroup(), KviStr::getToken(), KviStr::isUnsignedNum(), KviStr::stripLeftWhiteSpace(), and KviStr::toInt().
QString KviConfig::readEntry (const QString & szKey, const QString & szDefault = QString())
References KviPointerHashTable< Key, T >::find(), getCurrentGroup(), and m_szStrBuffer.
Referenced by KviDefaultScriptManager::compareVersions(), KviApp::findLocalKvircDirectory(), KviServerDataBase::importFromMircIni(), KviDefaultScriptManager::isDefscriptUpToDate(), KviStatusBar::load(), KviInputHistory::load(), KviKvsUserAction::load(), KviKvsScriptAddon::load(), KviKvsPopupMenu::load(), KviKvsAliasManager::load(), KviThemeInfo::load(), KviTextIconManager::load(), KviTheme::load(), KviCustomToolBarDescriptor::load(), KviUserIdentityManager::load(), KviUserIdentity::load(), KviNickServRule::load(), KviServerDataBase::load(), KviServer::load(), KviIdentityProfile::load(), KviAvatarCache::load(), KviSharedFilesManager::load(), KviProxyDataBase::load(), KviMediaManager::load(), KviKvsEventManager::loadAppEvents(), KviDefaultScriptManager::loadInternal(), KviWindow::loadProperties(), KviKvsEventManager::loadRawEvents(), and KviDefaultScriptManager::restoreInternal().
QFont KviConfig::readFontEntry (const QString & szKey, const QFont & fnt)
References KviPointerHashTable< Key, T >::find(), getCurrentGroup(), setFontProperties(), and KviStr::stripLeftWhiteSpace().
int KviConfig::readIntEntry (const QString & szKey, int iDefault)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
Referenced by KviStatusBar::load(), KviInputHistory::load(), KviKvsPopupMenu::load(), KviTextIconManager::load(), KviCustomToolBarManager::load(), KviServerDataBase::load(), KviServer::load(), KviSharedFilesManager::load(), KviRegisteredUserDataBase::load(), and KviStatusBarClock::loadState().
QList< int > KviConfig::readIntListEntry (const QString & szKey, const QList< int > & list)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
Referenced by KviQuery::loadProperties(), KviDebugWindow::loadProperties(), KviConsole::loadProperties(), and KviChannel::loadProperties().
QString KviConfig::readKviStrEntry (const QString & szKey, const KviStr & szDefault) [inline]
References KviStr::ptr().
KviMsgType KviConfig::readMsgTypeEntry (const QString & szKey, const KviMsgType & msgDef)
References KviPointerHashTable< Key, T >::find(), KviStringConversion::fromString(), and getCurrentGroup().
bool KviConfig::readOnly () [inline]
KviPixmap KviConfig::readPixmapEntry (const QString & szKey, const KviPixmap & pixDef)
References KviPointerHashTable< Key, T >::find(), KviStringConversion::fromString(), and getCurrentGroup().
Referenced by KviUserIdentity::load(), and KviChannel::loadProperties().
QRect KviConfig::readRectEntry (const QString & szKey, const QRect & rct)
References KviPointerHashTable< Key, T >::find(), KviStringConversion::fromString(), and getCurrentGroup().
Referenced by KviFrame::addWindow().
QStringList KviConfig::readStringListEntry (const QString & szKey, const QStringList & list = QStringList())
References KviPointerHashTable< Key, T >::find(), g_szConfigStringListSeparator(), and getCurrentGroup().
Referenced by KviKvsScriptAddon::load(), KviServerDataBase::load(), KviServer::load(), and KviApp::loadRecentEntries().
unsigned char KviConfig::readUCharEntry (const QString & szKey, unsigned char iDefault)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
unsigned int KviConfig::readUIntEntry (const QString & szKey, unsigned int iDefault)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
Referenced by KviApp::findLocalKvircDirectory(), KviKvsUserAction::load(), KviCustomToolBarDescriptor::load(), KviNickServRuleSet::load(), KviServer::load(), KviIdentityProfileSet::load(), KviAvatarCache::load(), KviProxyDataBase::load(), KviMediaManager::load(), KviKvsEventManager::loadAppEvents(), and KviKvsEventManager::loadRawEvents().
unsigned short int KviConfig::readUShortEntry (const QString & szKey, unsigned short int usDefault)
References KviPointerHashTable< Key, T >::find(), and getCurrentGroup().
bool KviConfig::save () [private]
References KviPointerHashTable< Key, T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), dict(), group(), KviStr::hexEncodeWhiteSpace(), KviStr::hexEncodeWithTable(), KviStr::len(), m_bDirty, m_bLocal8Bit, m_bPreserveEmptyGroups, m_bReadOnly, m_pDict, m_szFileName, KviStr::ptr(), KviQString::toLocal8Bit(), and KviQString::toUtf8().
Referenced by ~KviConfig().
void KviConfig::setFontProperties (KviStr & str, QFont * fnt) [static]
References KviStringConversion::fromString(), and KviStr::ptr().
Referenced by readFontEntry().
void KviConfig::setGroup (const QString & szGroup)
References getCurrentGroup(), hasGroup(), m_bDirty, m_bPreserveEmptyGroups, and m_szGroup.
Referenced by KviFrame::addWindow(), config_set_section(), KviApp::findLocalKvircDirectory(), KviServerDataBase::importFromMircIni(), KviStatusBar::load(), KviKvsScriptAddon::load(), KviKvsPopupManager::load(), KviKvsAliasManager::load(), KviThemeInfo::load(), KviTextIconManager::load(), KviTheme::load(), KviCustomToolBarManager::load(), KviActionManager::load(), KviUserIdentityManager::load(), KviServerDataBase::load(), KviAvatarCache::load(), KviSharedFilesManager::load(), KviRegisteredUserDataBase::load(), KviMediaManager::load(), KviKvsEventManager::loadAppEvents(), KviKvsEventManager::loadRawEvents(), KviStatusBar::save(), KviKvsUserAction::save(), KviKvsScriptAddonManager::save(), KviKvsScriptAddon::save(), KviKvsPopupManager::save(), KviKvsAliasManager::save(), KviThemeInfo::save(), KviTextIconManager::save(), KviTheme::save(), KviCustomToolBarManager::save(), KviCustomToolBarDescriptor::save(), KviActionManager::save(), KviUserIdentityManager::save(), KviUserIdentity::save(), KviServerDataBase::save(), KviAvatarCache::save(), KviSharedFilesManager::save(), KviRegisteredUserDataBase::save(), KviRegisteredChannelDataBase::save(), KviMediaManager::save(), KviKvsEventManager::saveAppEvents(), KviApp::saveKvircDirectory(), KviKvsEventManager::saveRawEvents(), and KviFrame::saveWindowProperties().
void KviConfig::setReadOnly (bool bReadOnly) [inline]
void KviConfig::setSavePath (const QString & savePath) [inline]
bool KviConfig::sync () [inline]
References KviTheme::save().
Referenced by KviApp::saveConfiguration().
void KviConfig::writeEntry (const QString & szKey, const QStringList & list)
References g_szConfigStringListSeparator(), getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, const KviPixmap & pixmap)
References getCurrentGroup(), m_bDirty, KviPointerHashTable< Key, T >::replace(), and KviStringConversion::toString().
void KviConfig::writeEntry (const QString & szKey, const QList< int > & list)
References KviStr::append(), KviStr::Format, getCurrentGroup(), KviStr::hasData(), m_bDirty, KviStr::ptr(), and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, const QColor & clr)
References KviStr::Format, getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, unsigned short int usValue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, const char * szValue) [inline]
References writeEntry().
Referenced by writeEntry().
void KviConfig::writeEntry (const QString & szKey, const QString & szValue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
Referenced by KviStatusBar::save(), KviInputHistory::save(), KviKvsUserAction::save(), KviKvsScriptAddon::save(), KviKvsPopupMenu::save(), KviKvsAliasManager::save(), KviThemeInfo::save(), KviTextIconManager::save(), KviTheme::save(), KviCustomToolBarManager::save(), KviCustomToolBarDescriptor::save(), KviUserIdentityManager::save(), KviUserIdentity::save(), KviNickServRule::save(), KviNickServRuleSet::save(), KviServerDataBase::save(), KviServer::save(), KviIdentityProfileSet::save(), KviIdentityProfile::save(), KviAvatarCache::save(), KviSharedFilesManager::save(), KviRegisteredUserDataBase::save(), KviRegisteredChannelDataBase::save(), KviProxyDataBase::save(), KviMediaManager::save(), KviKvsEventManager::saveAppEvents(), KviDefaultScriptManager::saveInternal(), KviApp::saveKvircDirectory(), KviWindow::saveProperties(), KviQuery::saveProperties(), KviDebugWindow::saveProperties(), KviConsole::saveProperties(), KviChannel::saveProperties(), KviKvsEventManager::saveRawEvents(), KviApp::saveRecentEntries(), KviStatusBarUpdateIndicator::saveState(), KviStatusBarConnectionTimer::saveState(), KviStatusBarClock::saveState(), KviStatusBarAwayIndicator::saveState(), and KviFrame::saveWindowProperties().
void KviConfig::writeEntry (const QString & szKey, unsigned int iValue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, QFont & fnt)
References getCurrentGroup(), m_bDirty, KviPointerHashTable< Key, T >::replace(), and KviStringConversion::toString().
void KviConfig::writeEntry (const QString & szKey, bool bTrue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, const KviMsgType & msg)
References getCurrentGroup(), m_bDirty, KviPointerHashTable< Key, T >::replace(), and KviStringConversion::toString().
void KviConfig::writeEntry (const QString & szKey, int iValue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, const QRect & rct)
References getCurrentGroup(), m_bDirty, KviPointerHashTable< Key, T >::replace(), and KviStringConversion::toString().
void KviConfig::writeEntry (const QString & szKey, char iValue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
void KviConfig::writeEntry (const QString & szKey, unsigned char iValue)
References getCurrentGroup(), m_bDirty, and KviPointerHashTable< Key, T >::replace().
Member Data Documentation
bool KviConfig::m_bDirty [private]
Referenced by clear(), clearGroup(), clearKey(), KviConfig(), save(), setGroup(), writeEntry(), and ~KviConfig().
bool KviConfig::m_bLocal8Bit [private]
Referenced by KviConfig(), load(), and save().
bool KviConfig::m_bPreserveEmptyGroups [private]
Referenced by KviConfig(), save(), and setGroup().
bool KviConfig::m_bReadOnly [private]
Referenced by ensureWritable(), KviConfig(), and save().
KviPointerHashTable<QString,KviConfigGroup>* KviConfig::m_pDict [private]
Referenced by clear(), clearGroup(), getCurrentGroup(), hasGroup(), KviConfig(), load(), save(), and ~KviConfig().
QString KviConfig::m_szFileName [private]
Referenced by ensureWritable(), KviConfig(), load(), and save().
QString KviConfig::m_szGroup [private]
Referenced by clear(), clearGroup(), clearKey(), getCurrentGroup(), KviConfig(), and setGroup().
QString KviConfig::m_szStrBuffer [private]
Referenced by readEntry().
The documentation for this class was generated from the following files:
src/kvilib/ext/kvi_config.h
src/kvilib/ext/kvi_config.cpp