KVIrc: LogViewListView Class Reference
LogViewListView Class Reference
#include <LogViewWindow.h>
Signals
void rightButtonPressed (QTreeWidgetItem *, QPoint)
Public Member Functions
LogViewListView (QWidget *)
~LogViewListView ()
Protected Member Functions
void mousePressEvent (QMouseEvent *pEvent)
Constructor & Destructor Documentation
LogViewListView::LogViewListView (QWidget * pParent)
References __tr2qs_ctx().
LogViewListView::~LogViewListView () [inline]
Member Function Documentation
void LogViewListView::mousePressEvent (QMouseEvent * pEvent) [protected]
References rightButtonPressed().
void LogViewListView::rightButtonPressed (QTreeWidgetItem * , QPoint) [signal]
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
src/modules/logview/LogViewWindow.h
src/modules/logview/LogViewWindow.cpp