KVIrc: ActionEditor Class Reference
ActionEditor Class Reference
#include <ActionEditor.h>
Public Member Functions
ActionEditor (QWidget *par)
bool actionExists (const QString &szName)
void commit ()
~ActionEditor ()
Protected Slots
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *prev)
void deleteActions ()
void exportActions ()
void newAction ()
Protected Member Functions
QString nameForAutomaticAction (const QString &szTemplate)
int selectedCount ()
Protected Attributes
QPushButton * m_pDeleteActionsButton
QPushButton * m_pExportActionsButton
QPushButton * m_pNewActionButton
SingleActionEditor * m_pSingleActionEditor
QSplitter * m_pSplitter
ActionEditorTreeView * m_pTreeWidget
Friends
class ActionEditorWindow
Constructor & Destructor Documentation
ActionEditor::ActionEditor (QWidget * par)
References __tr2qs_ctx(), a, KviActionManager::categoryGeneric(), connect(), KviPointerHashTableIterator< Key, T >::current(), currentItemChanged(), deleteActions(), exportActions(), first(), g_szLastEditedAction, KviActionManager::instance(), l, m_pDeleteActionsButton, m_pExportActionsButton, ActionData::m_pItem, m_pNewActionButton, m_pSingleActionEditor, m_pSplitter, m_pTreeWidget, ActionData::m_szName, KviActionCategory::name(), newAction(), and KviTalVBox::setSpacing().
ActionEditor::~ActionEditor ()
Member Function Documentation
bool ActionEditor::actionExists (const QString & szName)
References i, and m_pTreeWidget.
Referenced by SingleActionEditor::commit(), and nameForAutomaticAction().
void ActionEditor::commit (void)
References a, ActionEditorTreeWidgetItem::actionData(), SingleActionEditor::commit(), KviKvsUserAction::createInstance(), i, KviCustomToolBarManager::instance(), KviActionManager::instance(), KviActionManager::killAllKvsUserActions(), m_pSingleActionEditor, m_pTreeWidget, ActionData::m_szBigIcon, ActionData::m_szCategory, ActionData::m_szDescription, ActionData::m_szKeySequence, ActionData::m_szName, ActionData::m_szScriptCode, ActionData::m_szSmallIcon, ActionData::m_szVisibleName, ActionData::m_uFlags, KviActionManager::registerAction(), and KviCustomToolBarManager::updateVisibleToolBars().
Referenced by ActionEditorWindow::applyClicked(), and ActionEditorWindow::okClicked().
void ActionEditor::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem * prev) [protected, slot]
References ActionEditorTreeWidgetItem::actionData(), SingleActionEditor::actionData(), SingleActionEditor::commit(), g_szLastEditedAction, m_pDeleteActionsButton, m_pExportActionsButton, m_pSingleActionEditor, m_pTreeWidget, ActionData::m_szName, and SingleActionEditor::setActionData().
Referenced by ActionEditor(), and newAction().
void ActionEditor::deleteActions () [protected, slot]
References SingleActionEditor::actionData(), KviPointerList< T >::append(), KviPointerList< T >::first(), i, KviPointerList< T >::isEmpty(), l, m_pSingleActionEditor, m_pTreeWidget, KviPointerList< T >::next(), SingleActionEditor::setActionData(), and KviPointerList< T >::setAutoDelete().
Referenced by ActionEditor().
void ActionEditor::exportActions () [protected, slot]
References __tr2qs_ctx(), a, KviFileDialog::askForSaveFileName(), KviKvsUserAction::exportToKvs(), i, KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, m_pTreeWidget, ActionData::m_szBigIcon, ActionData::m_szCategory, ActionData::m_szDescription, ActionData::m_szKeySequence, ActionData::m_szName, ActionData::m_szScriptCode, ActionData::m_szSmallIcon, ActionData::m_szVisibleName, ActionData::m_uFlags, KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by ActionEditor().
QString ActionEditor::nameForAutomaticAction (const QString & szTemplate) [protected]
References actionExists(), and i.
Referenced by newAction().
void ActionEditor::newAction () [protected, slot]
References __tr2qs_ctx(), KviActionManager::categoryGeneric(), currentItemChanged(), ActionData::m_pItem, m_pTreeWidget, KviOsInfo::name(), and nameForAutomaticAction().
Referenced by ActionEditor().
int ActionEditor::selectedCount () [protected]
Friends And Related Function Documentation
friend class ActionEditorWindow [friend]
Member Data Documentation
QPushButton* ActionEditor::m_pDeleteActionsButton [protected]
Referenced by ActionEditor(), and currentItemChanged().
QPushButton* ActionEditor::m_pExportActionsButton [protected]
Referenced by ActionEditor(), and currentItemChanged().
QPushButton* ActionEditor::m_pNewActionButton [protected]
Referenced by ActionEditor().
SingleActionEditor* ActionEditor::m_pSingleActionEditor [protected]
Referenced by ActionEditor(), commit(), currentItemChanged(), and deleteActions().
QSplitter* ActionEditor::m_pSplitter [protected]
Referenced by ActionEditor(), ActionEditorWindow::loadProperties(), and ActionEditorWindow::saveProperties().
ActionEditorTreeView* ActionEditor::m_pTreeWidget [protected]
Referenced by ActionEditor(), actionExists(), commit(), currentItemChanged(), deleteActions(), exportActions(), and newAction().
The documentation for this class was generated from the following files:
src/modules/actioneditor/ActionEditor.h
src/modules/actioneditor/ActionEditor.cpp