KVIrc: KviTalSplitter Class Reference
KviTalSplitter Class Reference
Toolkit Abstraction Layer: splitter class.
#include <kvi_tal_splitter.h>
Public Member Functions
KviTalSplitter (Qt::Orientation orientation, QWidget *pParent=0)
Constructs the splitter object.
void setSizes (QList< int > sizes)
Sets the initial sizes for items contained inside the splitter.
QList< int > sizes ()
Returns the list of sizes of the items contained inside the splitter.
virtual ~KviTalSplitter ()
Destroys the splitter object.
Protected Slots
void splitterHasMoved (int pos, int index)
Private Attributes
bool bHasValidSizes
QList< int > oldSizes
Detailed Description
Toolkit Abstraction Layer: splitter class.
Constructor & Destructor Documentation
KviTalSplitter::KviTalSplitter (Qt::Orientation orientation, QWidget * pParent = 0)
Constructs the splitter object.
Parameters:
orientation The orientation of the splitter: horizontal or vertical
pParent the parent object
Returns:
KviTalSplitter
References bHasValidSizes, and splitterHasMoved().
KviTalSplitter::~KviTalSplitter () [virtual]
Destroys the splitter object.
Member Function Documentation
void KviTalSplitter::setSizes (QList< int > sizes)
Sets the initial sizes for items contained inside the splitter.
Parameters:
sizes The list of sizes
Returns:
void
References oldSizes.
Referenced by KviQuery::loadProperties(), KviDebugWindow::loadProperties(), KviConsole::loadProperties(), KviChannel::loadProperties(), and KviChannel::showDoubleView().
QList< int > KviTalSplitter::sizes ()
Returns the list of sizes of the items contained inside the splitter.
Returns:
QList<int>
References bHasValidSizes, and oldSizes.
Referenced by KviQuery::saveProperties(), KviDebugWindow::saveProperties(), KviConsole::saveProperties(), KviChannel::saveProperties(), and KviChannel::showDoubleView().
void KviTalSplitter::splitterHasMoved (int pos, int index) [protected, slot]
References bHasValidSizes.
Referenced by KviTalSplitter().
Member Data Documentation
bool KviTalSplitter::bHasValidSizes [private]
Referenced by KviTalSplitter(), sizes(), and splitterHasMoved().
QList<int> KviTalSplitter::oldSizes [private]
Referenced by setSizes(), and sizes().
The documentation for this class was generated from the following files:
src/kvilib/tal/kvi_tal_splitter.h
src/kvilib/tal/kvi_tal_splitter.cpp