KVIrc: KviApplication Class Reference
KviApplication Class Reference
#include <KviApplication.h>
Public Types
enum KvircSubdir {
None, Pics, Config, Help,
HelpEN, HelpNoIntl, Log, Incoming,
Audio, Scripts, Plugins, ConfigPlugins,
Trash, MsgColors, Charmaps, Avatars,
DefScript, License, Modules, ConfigScripts,
Filters, Tmp, Locale, Themes,
Classes, SmallIcons, EasyPlugins
}
Public Slots
void addRecentUrl (const QString &text)
void restoreDefaultScript ()
void saveConfiguration ()
Saves configuration to disk.
void showParentFrame ()
void updateGui ()
void updatePseudoTransparency ()
Signals
void recentUrlsChanged ()
void reloadImages ()
void updateNotifier ()
Public Member Functions
KviConsoleWindow * activeConsole ()
void addRecentChannel (const QString &chan, const QString &net)
void addRecentNickname (const QString &newNick)
void addRecentServer (const QString &server)
void autoConnectToServers ()
void checkSuggestRestoreDefaultScript ()
void completeDirectory (const QString &word, KviPointerList< QString > *matches)
bool connectionExists (KviIrcConnection *cnn)
void fileDownloadTerminated (bool bSuccess, const QString &szRemoteUrl, const QString &szLocalFileName, const QString &szNick=QString(), const QString &szError=QString(), bool bQuiet=false)
void fillRecentChannelsPopup (QMenu *m, KviConsoleWindow *pConsole)
void fillRecentNicknamesPopup (QMenu *m, KviConsoleWindow *pConsole)
void fillRecentServersPopup (QMenu *m)
bool findAudioFile (QString &szRetPath, const QString &szFileName)
KviConsoleWindow * findConsole (unsigned int ircContextId)
KviConsoleWindow * findConsole (QString &servr, QString &nick)
bool findImage (QString &szRetPath, const QString &filename)
bool findImageInImageSearchPath (QString &szRetPath, const QString &filename)
bool findImageThemeOnlyCompat (QString &szRetPath, const QString &filename)
KviPendingAvatarChange * findPendingAvatarChange (KviConsoleWindow *pConsole, const QString &szNick, const QString &szRemoteUrl)
bool findSmallIcon (QString &szRetPath, const QString &filename)
KviWindow * findWindow (const QString &windowId)
KviWindow * findWindowByCaption (const QString &windowCaption, int iContextId=-1)
bool firstTimeRun () const
void getChannelDumpLogFileName (QString &str)
void getGlobalKvircDirectory (QString &szData, KvircSubdir dir, const QString &appendFile=QString())
void getLocalKvircDirectory (QString &szData, KvircSubdir dir, const QString &appendFile=QString(), bool bCreateIfNeeded=true)
bool getOptionString (const QString &optName, QString &buffer)
bool getReadOnlyConfigPath (QString &buffer, const char *config_name, KvircSubdir sbd=Config, bool bNoFail=false)
void getTmpFileName (QString &szBuffer, const QString &szEndingFileName=QString())
void ipcMessage (char *message)
KviApplication (int &argc, char **argv)
bool kviClosingDown () const
void listAvailableOptions (KviWindow *wnd)
void loadDefaultScript (QString szItem=QString())
void loadOptions ()
bool mapImageFile (QString &szRetPath, const QString &filename)
void notifierMessage (KviWindow *pWnd, int iIconId, const QString &szMsg, unsigned int uMessageLifetime)
void optionResetUpdate (int flags)
KviPointerHashTable< QString,
QStringList > * recentChannels () const
QStringList * recentChannelsForNetwork (const QString &net)
void resetAvatarForMatchingUsers (KviRegisteredUser *u)
void restartLagMeters ()
void restartNotifyLists ()
void saveActions ()
void saveAliases ()
void saveAppEvents ()
void saveAvatarCache ()
void saveDefaultScripts ()
void saveIdentities ()
void saveIdentityProfiles ()
void saveInputHistory ()
void saveIrcServerDataBase ()
void saveMediaTypes ()
void saveNickServ ()
void saveOptions ()
void savePopups ()
void saveProxyDataBase ()
void saveRawEvents ()
void saveRecentEntries ()
void saveRegisteredChannels ()
void saveRegisteredUsers ()
void saveScriptAddons ()
void saveSharedFiles ()
void saveTextIcons ()
void saveToolBars ()
void setAvatarFromOptions ()
void setAvatarOnFileReceived (KviConsoleWindow *pConsole, const QString &szRemoteUrl, const QString &szNick, const QString &szUser, const QString &szHost)
bool setCommonOptionValue (const QString &optName, const QString &value)
void setKviClosingDown ()
bool setOptionValue (const QString &optName, const QString &value)
void setup ()
void setupBegin ()
void setupFinish ()
bool supportsCompositing ()
QStyle * themedStyle ()
KviConsoleWindow * topmostConnectedConsole ()
void triggerUpdateGui ()
unsigned int windowCount ()
bool windowExists (KviWindow *wnd)
~KviApplication ()
Static Public Member Functions
static QTextCodec * defaultSrvCodec ()
static QTextCodec * defaultTextCodec ()
static int getGloballyUniqueId ()
Public Attributes
bool m_bCreateConfig
bool m_bShowSplashScreen
QString m_szConfigFile
QString m_szExecAfterStartup
Protected Member Functions
void buildRecentChannels ()
void frameDestructorCallback ()
void heartbeat (kvi_time_t tNow)
void registerWindow (KviWindow *wnd)
void saveRecentChannels ()
virtual void timerEvent (QTimerEvent *e)
void unregisterWindow (KviWindow *wnd)
Protected Attributes
bool m_bClosingDown
bool m_bFirstTimeRun
bool m_bSetupDone
bool m_bUpdateGuiPending
QFont m_fntDefaultFont
int m_iHeartbeatTimerId
KviWindow * m_pActiveWindow
KviIpcSentinel * m_pIpcSentinel
KviPointerList
< KviPendingAvatarChange > * m_pPendingAvatarChanges
KviPointerHashTable< QString,
QStringList > * m_pRecentChannelDict
QString m_szGlobalKvircDir
QString m_szLocalKvircDir
Private Member Functions
bool checkFileAssociations ()
bool checkGlobalKvircDirectory (const QString)
bool checkLocalKvircDirectory ()
bool checkLocalKvircDirectory (const QString &szSpecificPath)
bool checkUriAssociations (const char *proto)
void createFrame ()
void createIpcSentinel ()
void createSplashScreen ()
void destroyIpcSentinel ()
void destroySplashScreen ()
void findGlobalKvircDirectory ()
bool findLocalKvircDirectory ()
void loadDirectories ()
void loadRecentEntries ()
void saveKvircDirectory ()
void setupFileAssociations ()
void setupUriAssociations (const char *proto)
void updateApplicationFont ()
Friends
class KviMainWindow
class KviWindow
class SetupWizard
Member Enumeration Documentation
enum KviApplication::KvircSubdir
Enumerator:
None
Pics
Config
HelpEN
HelpNoIntl
Log
Incoming
Audio
Scripts
Plugins
ConfigPlugins
Trash
MsgColors
Charmaps
Avatars
DefScript
License
Modules
ConfigScripts
Filters
Tmp
Locale
Themes
Classes
SmallIcons
EasyPlugins
Constructor & Destructor Documentation
KviApplication::KviApplication (int & argc, char ** argv)
References KviFileUtils::fileExists(), g_pApp, KVI_PATH_SEPARATOR_CHAR, kvi_socket_flushTrafficCounters(), m_bClosingDown, m_bCreateConfig, m_bSetupDone, m_bShowSplashScreen, m_bUpdateGuiPending, m_fntDefaultFont, m_iHeartbeatTimerId, m_pIpcSentinel, m_pPendingAvatarChanges, m_pRecentChannelDict, m_szConfigFile, and NULL.
KviApplication::~KviApplication ()
References KviFileTransferManager::cleanup(), destroyIpcSentinel(), KviKvs::done(), g_pActiveWindow, g_pColorWindow, g_pCtcpPageDialog, g_pGlobalWindowDict, g_pHistoryWindow, g_pIconManager, g_pInputPopup, g_pMainWindow, g_pMediaManager, g_pModuleExtensionManager, g_pModuleManager, g_pNickServRuleSet, g_pProxyDataBase, g_pRecentTopicList, g_pRegisteredChannelDataBase, g_pRegisteredUserDataBase, g_pServerDataBase, g_pServerParser, g_pSharedFilesManager, g_pSplashScreen, g_pTextIconManager, g_pTextIconWindow, g_pWinPropertiesConfig, KviThreadManager::globalDestroy(), m_bClosingDown, m_bSetupDone, m_pPendingAvatarChanges, m_pRecentChannelDict, saveActions(), saveAliases(), saveAppEvents(), saveAvatarCache(), saveDefaultScripts(), saveIdentities(), saveIdentityProfiles(), saveInputHistory(), saveIrcServerDataBase(), saveMediaTypes(), saveNickServ(), saveOptions(), savePopups(), saveProxyDataBase(), saveRawEvents(), saveRecentEntries(), saveRegisteredChannels(), saveRegisteredUsers(), saveScriptAddons(), saveSharedFiles(), saveTextIcons(), and saveToolBars().
Member Function Documentation
KviConsoleWindow * KviApplication::activeConsole ()
References KviWindow::console(), KviMainWindow::firstConsole(), g_pActiveWindow, and g_pMainWindow.
Referenced by DccBroker::activeVideoExecute(), DccBroker::activeVoiceExecute(), UPnP::RootService::addDeviceServices(), autoConnectToServers(), KviKvsObject::callFunction(), OptionsWidget_servers::connectCurrentClicked(), KviIdentSentinel::event(), DccFileTransfer::event(), CodeTesterWidget::execute(), KviKvsCallbackObject::execute(), DccBroker::executeChat(), KviKvsPopupMenu::itemClicked(), KviKvsCoreSimpleCommands::KVSCSC(), KviMenuBar::newConnectionToServer(), DccBroker::passiveVideoExecute(), DccBroker::recvFileExecute(), DccBroker::rsendExecute(), DccBroker::sendFileExecute(), KviKvsPopupMenu::setupMenuContents(), KviKvsTimerManager::timerEvent(), topmostConnectedConsole(), HttpFileTransfer::transferTerminated(), KviKvsProcessAsyncOperation::trigger(), DccDescriptor::triggerCreationEvent(), and DccDescriptor::~DccDescriptor().
void KviApplication::addRecentChannel (const QString & chan, const QString & net)
References buildRecentChannels(), KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), and m_pRecentChannelDict.
Referenced by KviIrcConnection::registerChannel().
void KviApplication::addRecentNickname (const QString & newNick)
References KVI_MAX_RECENT_NICKNAMES, KviOption_stringlistRecentNicknames, and merge_to_stringlist_option().
Referenced by KviIrcConnection::loginComplete(), and KviIrcConnection::nickChange().
void KviApplication::addRecentServer (const QString & server)
References KVI_MAX_RECENT_SERVERS, KviOption_stringlistRecentServers, and merge_to_stringlist_option().
Referenced by KviIrcContext::connectionEstabilished().
void KviApplication::addRecentUrl (const QString & text) [slot]
References KviOption_stringlistRecentIrcUrls, merge_to_stringlist_option(), and recentUrlsChanged().
Referenced by KviIrcUrl::run().
void KviApplication::autoConnectToServers ()
References activeConsole(), KviIrcServerDataBase::autoConnectOnStartupNetworks(), KviIrcServerDataBase::autoConnectOnStartupServers(), KviIrcServerDataBase::clearAutoConnectOnStartupNetworks(), KviIrcServerDataBase::clearAutoConnectOnStartupServers(), KviPointerList< T >::first(), g_pServerDataBase, KviPointerList< T >::next(), and KviIrcUrl::run().
Referenced by createFrame().
void KviApplication::buildRecentChannels () [protected]
References KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), KVI_OPTION_STRINGLIST, KVI_RECENT_CHANNELS_SEPARATOR, KviOption_stringlistRecentChannels, m_pRecentChannelDict, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by addRecentChannel(), optionResetUpdate(), recentChannelsForNetwork(), and setOptionValue().
bool KviApplication::checkFileAssociations () [private]
References __tr2qs, KviMemory::free(), kvi_strEqualCI(), and kvi_strEqualCIN().
Referenced by loadDirectories().
bool KviApplication::checkGlobalKvircDirectory (const QString szDir) [private]
References KviFileUtils::directoryExists(), KviFileUtils::isReadable(), KVI_ACTIVITYMETER_IMAGE_NAME, and KVI_PATH_SEPARATOR.
Referenced by findGlobalKvircDirectory().
bool KviApplication::checkLocalKvircDirectory (const QString & szSpecificPath) [private]
References checkLocalKvircDirectory(), and m_szLocalKvircDir.
Referenced by SetupWizard::chooseOldDataPath().
bool KviApplication::checkLocalKvircDirectory () [private]
References Config, KviFileUtils::directoryExists(), getLocalKvircDirectory(), and m_szLocalKvircDir.
Referenced by checkLocalKvircDirectory(), and findLocalKvircDirectory().
void KviApplication::checkSuggestRestoreDefaultScript ()
References __tr2qs, KviKvsEventManager::instance(), KviKvsPopupManager::instance(), KviCustomToolBarManager::instance(), KviDefaultScriptManager::instance(), KVI_OPTION_BOOL, KviEvent_OnChannelNickPopupRequest, KviEvent_OnChannelPopupRequest, KviEvent_OnConsolePopupRequest, KviEvent_OnDCCChatPopupRequest, KviEvent_OnQueryNickPopupRequest, KviEvent_OnQueryPopupRequest, KviOption_boolDoNotSuggestRestoreDefaultScript, and restoreDefaultScript().
Referenced by KviUserListView::emitDoubleClick(), KviUserListView::emitRightClick(), and setup().
bool KviApplication::checkUriAssociations (const char * proto) [private]
Referenced by loadDirectories().
void KviApplication::completeDirectory (const QString & word, KviPointerList< QString > * matches)
References KviFileUtils::adjustFilePath(), KviPointerList< T >::append(), KviQString::cutFromLast(), KviQString::cutToLast(), d, KviQString::ensureLastCharIs(), KviQString::equalCIN(), KviQString::equalCS(), KviQString::equalCSN(), KVI_PATH_SEPARATOR_CHAR, and t().
Referenced by KviInputEditor::completion().
bool KviApplication::connectionExists (KviIrcConnection * cnn)
References KviWindow::connection(), KviPointerHashTableIterator< Key, T >::current(), and g_pGlobalWindowDict.
Referenced by KviAsyncAvatarSelectionDialog::okClicked().
void KviApplication::createFrame () [private]
References KviIrcServerDataBase::autoConnectOnStartupNetworks(), KviIrcServerDataBase::autoConnectOnStartupServers(), autoConnectToServers(), KviMainWindow::createNewConsole(), KviMainWindow::executeInternalCommand(), KviMainWindow::firstConsole(), g_pMainWindow, g_pServerDataBase, KVI_INTERNALCOMMAND_TRAYICON_SHOW, KVI_OPTION_BOOL, KviMainWindow, KviOption_boolShowDockExtension, KviOption_boolStartupMinimized, m_szExecAfterStartup, and KviIrcUrl::run().
Referenced by setup().
void KviApplication::createIpcSentinel () [private]
References m_pIpcSentinel.
Referenced by setup().
void KviApplication::createSplashScreen () [private]
References g_pSplashScreen.
Referenced by setup().
QTextCodec * KviApplication::defaultSrvCodec () [static]
References KviLocale::codecForName(), KviLocale::instance(), KVI_OPTION_STRING, and KviOption_stringDefaultSrvEncoding.
Referenced by KviIrcConnection::setupSrvCodec().
QTextCodec * KviApplication::defaultTextCodec () [static]
References KviLocale::codecForName(), KviLocale::instance(), KVI_OPTION_STRING, and KviOption_stringDefaultTextEncoding.
Referenced by KviIrcConnection::setupTextCodec().
void KviApplication::destroyIpcSentinel () [private]
References m_pIpcSentinel.
Referenced by ~KviApplication().
void KviApplication::destroySplashScreen () [private]
References KviSplashScreen::die(), and g_pSplashScreen.
Referenced by setup().
void KviApplication::fileDownloadTerminated (bool bSuccess, const QString & szRemoteUrl, const QString & szLocalFileName, const QString & szNick = QString(), const QString & szError = QString(), bool bQuiet = false)
References __tr2qs, _OUTPUT_MUTE, KviPointerList< T >::count(), KviIconManager::DccError, KviIconManager::DccMsg, KviQString::equalCIN(), findPendingAvatarChange(), g_pActiveWindow, KviWindow::hasAttention(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_AVATAR, KviOption_boolNotifyDccSendSuccessInNotifier, KviOption_uintNotifierAutoHideTime, m_pPendingAvatarChanges, KviWindow::MainWindowIsVisible, notifierMessage(), KviWindow::output(), _KviPendingAvatarChange::pConsole, KviPointerList< T >::removeRef(), KviConsoleWindow::setAvatar(), _KviPendingAvatarChange::szHost, _KviPendingAvatarChange::szNick, _KviPendingAvatarChange::szUser, and windowExists().
Referenced by DccFileTransfer::abort(), DccFileTransfer::event(), and HttpFileTransfer::transferTerminated().
void KviApplication::fillRecentChannelsPopup (QMenu * m, KviConsoleWindow * pConsole)
References KviIconManager::Channel, KviWindow::connection(), KviConsoleWindow::currentNetworkName(), KviIrcConnection::findChannel(), g_pIconManager, KviIconManager::getSmallIcon(), KviConsoleWindow::isConnected(), and recentChannelsForNetwork().
Referenced by KviJoinChannelAction::popupAboutToShow().
void KviApplication::fillRecentNicknamesPopup (QMenu * m, KviConsoleWindow * pConsole)
References KviWindow::connection(), KviIrcConnection::currentNickName(), KviQString::equalCS(), g_pIconManager, KviIconManager::getSmallIcon(), KviConsoleWindow::isConnected(), KVI_OPTION_STRINGLIST, KviOption_stringlistRecentNicknames, and KviIconManager::Nick.
Referenced by KviChangeNickAction::popupAboutToShow().
void KviApplication::fillRecentServersPopup (QMenu * m)
References g_pIconManager, KviIconManager::getSmallIcon(), KVI_OPTION_STRINGLIST, KviOption_stringlistRecentServers, and KviIconManager::Server.
Referenced by KviConnectToServerAction::popupAboutToShow(), OptionsWidget_servers::recentServersPopupAboutToShow(), and KviMenuBar::updateRecentServersPopup().
bool KviApplication::findAudioFile (QString & szRetPath, const QString & szFileName)
Attempts to locate the audio file specified by szFileName and put it's absolute path in szRetPath. Returns true if the audio file is found and false otherwise.
If szFileName is already an absolute path then it's returned directly after testing for its existence. If szFileName is not an absolute path then it's searched in the local KVIrc "audio" directory, then in the global one and finally in the user's home.
References Audio, KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KviFileUtils::isAbsolutePath(), and KVI_PATH_SEPARATOR_CHAR.
Referenced by OptionsWidget_soundGeneral::soundTest().
KviConsoleWindow * KviApplication::findConsole (unsigned int ircContextId)
References KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, and KviWindow::type().
Referenced by chan_kvs_fnc_common(), context_kvs_fnc_getSSLCertInfo(), KviTrayIconWidget::doAway(), KviKvsCoreFunctions::KVSCF(), and window_kvs_fnc_open().
KviConsoleWindow * KviApplication::findConsole (QString & servr, QString & nick)
References KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), g_pGlobalWindowDict, and KviWindow::type().
void KviApplication::findGlobalKvircDirectory () [private]
defined(COMPILE_KDE_SUPPORT) && !defined(COMPILE_ON_MAC)
COMPILE_ON_MAC
References KviFileUtils::adjustFilePath(), checkGlobalKvircDirectory(), m_szGlobalKvircDir, and KviMessageBox::warning().
Referenced by loadDirectories().
bool KviApplication::findImage (QString & szRetPath, const QString & filename)
References KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), findImageInImageSearchPath(), getGlobalKvircDirectory(), getLocalKvircDirectory(), i, KviFileUtils::isAbsolutePath(), KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, pics_globalsubdirs, pics_localsubdirs, and Themes.
Referenced by AboutDialog::AboutDialog(), KviIconManager::getPixmapWithCache(), KviIconManager::getPixmapWithCacheScaleOnLoad(), KviIconManager::KviIconManager(), KviSplashScreen::KviSplashScreen(), KviTextIcon::KviTextIcon(), KviTheme::load(), mircimport_module_init(), KviTextIcon::setFilename(), setOptionValue(), TipFrame::TipFrame(), and trayicon_module_init().
bool KviApplication::findImageInImageSearchPath (QString & szRetPath, const QString & filename)
References KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), KVI_OPTION_STRINGLIST, KVI_PATH_SEPARATOR_CHAR, and KviOption_stringlistImageSearchPaths.
Referenced by findImage(), findImageThemeOnlyCompat(), and findSmallIcon().
bool KviApplication::findImageThemeOnlyCompat (QString & szRetPath, const QString & filename)
References KviFileUtils::fileExists(), findImageInImageSearchPath(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, Pics, and Themes.
bool KviApplication::findLocalKvircDirectory () [private]
References checkLocalKvircDirectory(), g_pApp, KVI_HOME_CONFIG_FILE_NAME, KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, KVI_SOURCES_DATE_NUMERIC_FORCE_SETUP, m_szConfigFile, m_szLocalKvircDir, KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviConfigurationFile::readUIntEntry(), and KviConfigurationFile::setGroup().
Referenced by loadDirectories().
KviPendingAvatarChange * KviApplication::findPendingAvatarChange (KviConsoleWindow * pConsole, const QString & szNick, const QString & szRemoteUrl)
References KviPointerList< T >::first(), m_pPendingAvatarChanges, KviPointerList< T >::next(), _KviPendingAvatarChange::pConsole, _KviPendingAvatarChange::szNick, and _KviPendingAvatarChange::szRemoteUrl.
Referenced by dcc_kvs_cmd_recv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), fileDownloadTerminated(), and KviIrcServerParser::parseCtcpRequestDcc().
bool KviApplication::findSmallIcon (QString & szRetPath, const QString & filename)
References KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), findImageInImageSearchPath(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, KviOption_stringIconThemeSubdir, Pics, SmallIcons, and Themes.
Referenced by KviIconManager::loadSmallIcon().
KviWindow * KviApplication::findWindow (const QString & windowId)
References g_pGlobalWindowDict.
Referenced by chan_kvs_find_channel(), dcc_kvs_fnc_session(), KviKvsTreeNodeRebindingSwitch::execute(), KvsObject_wrapper::init(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), log_kvs_fnc_file(), notifier_kvs_cmd_message(), spaste_kvs_find_window(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_fnc_ischannelhighlighted(), window_kvs_cmd_highlight(), window_kvs_cmd_insertInInputText(), window_kvs_cmd_setBackground(), window_kvs_cmd_setCryptEngine(), window_kvs_cmd_setInputText(), and window_kvs_cmd_setWindowTitle().
KviWindow * KviApplication::findWindowByCaption (const QString & windowCaption, int iContextId = -1)
References KviWindow::context(), KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), g_pGlobalWindowDict, KviIrcContext::id(), and KviWindow::plainTextCaption().
Referenced by KviKvsCoreFunctions::KVSCF(), and UrlDialog::sayToWin().
bool KviApplication::firstTimeRun () const [inline]
Referenced by setup().
void KviApplication::frameDestructorCallback () [protected]
References KviKvsObjectController::clearInstances(), KviKvsKernel::instance(), and KviKvsKernel::objectController().
Referenced by KviMainWindow::~KviMainWindow().
void KviApplication::getChannelDumpLogFileName (QString & str)
References KviFileUtils::adjustFilePath(), KviFileUtils::fileExists(), getLocalKvircDirectory(), and Log.
void KviApplication::getGlobalKvircDirectory (QString & szData, KvircSubdir dir, const QString & appendFile = QString())
References KviFileUtils::adjustFilePath(), KviQString::appendFormatted(), Audio, Avatars, Charmaps, Classes, Config, ConfigPlugins, ConfigScripts, DefScript, KviFileUtils::directoryExists(), EasyPlugins, KviQString::ensureLastCharIs(), Filters, Help, HelpEN, HelpNoIntl, Incoming, KviLocale::instance(), KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, License, Locale, Log, m_szGlobalKvircDir, Modules, MsgColors, None, Pics, Plugins, Scripts, SmallIcons, Themes, Tmp, and Trash.
Referenced by AboutDialog::AboutDialog(), ScriptEditorWidget::asyncCompleterCreation(), KviModuleManager::completeModuleNames(), LogViewWindow::createLog(), file_kvs_fnc_globaldir(), findAudioFile(), findImage(), findImageThemeOnlyCompat(), PluginManager::findPlugin(), findSmallIcon(), KviThemeInfo::getCompleteDirPath(), getReadOnlyConfigPath(), help_kvs_cmd_open(), help_module_init(), KviIconManager::initQResourceBackend(), KviTheme::installedThemes(), KviDefaultScriptManager::isDefscriptUpToDate(), KviDefaultScriptManager::KviDefaultScriptManager(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), OptionsWidget_messageColors::load(), KviTextIconManager::load(), loadDefaultScript(), KviModuleManager::loadModule(), KviModuleManager::loadModulesByCaps(), KviKvsObjectController::lookupClass(), mapImageFile(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), KviDefaultScriptManager::restore(), KviDefaultScriptManager::restoreInternal(), KviTheme::save(), setup(), setupBegin(), SetupWizard::SetupWizard(), and HelpWidget::showIndex().
int KviApplication::getGloballyUniqueId () [static]
References g_iGloballyUniqueId.
Referenced by KviCustomToolBarDescriptor::KviCustomToolBarDescriptor(), KviFileTransfer::KviFileTransfer(), and KviModuleExtensionDescriptor::KviModuleExtensionDescriptor().
void KviApplication::getLocalKvircDirectory (QString & szData, KvircSubdir dir, const QString & appendFile = QString(), bool bCreateIfNeeded = true)
References KviFileUtils::adjustFilePath(), Audio, Avatars, Charmaps, Classes, Config, ConfigPlugins, ConfigScripts, DefScript, KviFileUtils::directoryExists(), EasyPlugins, KviQString::ensureLastCharIs(), Filters, Help, HelpEN, HelpNoIntl, Incoming, KviLocale::instance(), KVI_DEFAULT_INCOMING_SUBDIRECTORY_NAME, KVI_OPTION_STRING, KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, KviOption_stringIncomingPath, KviOption_stringLogsPath, License, Locale, KviLocale::localeName(), Log, m_szLocalKvircDir, KviFileUtils::makeDir(), Modules, MsgColors, None, Pics, Plugins, KviCString::ptr(), Scripts, SmallIcons, Themes, Tmp, and Trash.
Referenced by addon_kvs_cmd_installfiles(), ScriptEditorWidget::asyncCompleterCreation(), avatar_kvs_cmd_set(), ClassEditorWidget::build(), LogViewWindow::cacheFileList(), checkLocalKvircDirectory(), OptionsWidget_textIcons::chooseFromFile(), DccBroker::chooseSaveFileName(), TipWindow::closeConfig(), OptionsWidget_textEncoding::commit(), OptionsWidget_interfaceFeatures::commit(), KviModuleManager::completeModuleNames(), config_kvs_fnc_id(), config_kvs_fnc_open(), LogViewWindow::createLog(), KviKvsObjectController::deleteClass(), file_kvs_fnc_localdir(), KviIrcViewToolWidget::filterLoad(), KviIrcViewToolWidget::filterSave(), findAudioFile(), findImage(), findImageThemeOnlyCompat(), PluginManager::findPlugin(), findSmallIcon(), KviKvsObjectController::flushUserClasses(), KviIconManager::getAvatar(), getChannelDumpLogFileName(), KviThemeInfo::getCompleteDirPath(), KviModule::getDefaultConfigFileName(), KviWindow::getDefaultLogFileName(), getReadOnlyConfigPath(), getTmpFileName(), help_kvs_cmd_open(), help_module_init(), http_kvs_complete_get(), RegisteredUsersDialog::importClicked(), HelpWindow::initialSetup(), KviIconManager::initQResourceBackend(), AddonFunctions::installAddonPackage(), KviTheme::installedThemes(), ThemeFunctions::installThemePackage(), KviDefaultScriptManager::KviDefaultScriptManager(), KviSplashScreen::KviSplashScreen(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), OptionsWidget_messageColors::load(), KviTextIconManager::load(), KviTheme::load(), loadBanList(), ScriptEditorWidget::loadCompleterFromFile(), KviModuleManager::loadModule(), KviModuleManager::loadModulesByCaps(), ClassEditorWidget::loadNotBuiltClasses(), loadRecentEntries(), loadUrlList(), KviKvsObjectController::lookupClass(), mapImageFile(), objects_kvs_fnc_classes(), ClassEditorWidget::oneTimeSetup(), OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), KviIrcServerParser::parseCtcpReplyAvatar(), KviQueryWindow::pasteLastLog(), KviChannelWindow::pasteLastLog(), ClassEditorWidget::removeItem(), ClassEditorWidget::renameFunction(), KviMainWindow::restoreToolBarPositions(), OptionsWidget_messageColors::save(), KviStatusBar::save(), KviTextIconManager::save(), saveActions(), saveAliases(), saveAppEvents(), saveAvatarCache(), saveBanList(), saveDefaultScripts(), saveIdentities(), saveIdentityProfiles(), saveInputHistory(), saveIrcServerDataBase(), saveMediaTypes(), saveNickServ(), ClassEditorWidget::saveNotBuiltClasses(), saveOptions(), savePopups(), saveProxyDataBase(), saveRawEvents(), saveRecentEntries(), saveRegisteredChannels(), saveRegisteredUsers(), saveScriptAddons(), saveSharedFiles(), SaveThemeDialog::saveTheme(), KviMainWindow::saveToolBarPositions(), saveToolBars(), saveUrlList(), ScriptEditorWidget::ScriptEditorWidget(), setup(), AvatarDownloadDialog::startDownload(), theme_kvs_fnc_list(), KviKvsScriptAddonManager::unregisterAddon(), and url_module_init().
bool KviApplication::getOptionString (const QString & optName, QString & buffer)
References g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, GET_OPTION_STRING, KVI_BOOL_OPTIONS_PREFIX, KVI_BOOL_OPTIONS_PREFIX_LEN, KVI_COLOR_OPTIONS_PREFIX, KVI_COLOR_OPTIONS_PREFIX_LEN, KVI_FONT_OPTIONS_PREFIX, KVI_FONT_OPTIONS_PREFIX_LEN, KVI_ICCOLOR_OPTIONS_PREFIX, KVI_ICCOLOR_OPTIONS_PREFIX_LEN, KVI_MIRCCOLOR_OPTIONS_PREFIX, KVI_MIRCCOLOR_OPTIONS_PREFIX_LEN, KVI_MSGTYPE_OPTIONS_PREFIX, KVI_MSGTYPE_OPTIONS_PREFIX_LEN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KVI_PIXMAP_OPTIONS_PREFIX, KVI_PIXMAP_OPTIONS_PREFIX_LEN, KVI_STRING_OPTIONS_PREFIX, KVI_STRING_OPTIONS_PREFIX_LEN, KVI_STRINGLIST_OPTIONS_PREFIX, KVI_STRINGLIST_OPTIONS_PREFIX_LEN, KVI_UINT_OPTIONS_PREFIX, and KVI_UINT_OPTIONS_PREFIX_LEN.
Referenced by KviKvsCoreFunctions::KVSCF().
bool KviApplication::getReadOnlyConfigPath (QString & buffer, const char * config_name, KvircSubdir sbd = Config, bool bNoFail = false)
References KviFileUtils::fileExists(), getGlobalKvircDirectory(), and getLocalKvircDirectory().
Referenced by KviStatusBar::load(), KviTextIconManager::load(), loadOptions(), TipWindow::openConfig(), and setup().
void KviApplication::getTmpFileName (QString & szBuffer, const QString & szEndingFileName = QString())
References KviQString::appendFormatted(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), getLocalKvircDirectory(), kvi_gettimeofday(), KVI_PATH_SEPARATOR_CHAR, and Tmp.
Referenced by SaveThemeDialog::makeScreenshot(), and KviRemoteMircServerImportWizard::start().
void KviApplication::heartbeat (kvi_time_t tNow) [protected]
References KviPointerHashTableIterator< Key, T >::current(), g_pApp, g_pGlobalWindowDict, KviIrcView::isLogging(), KVI_OPTION_UINT, KviOption_uintTotalConnectionTime, KviIrcView::startLogging(), topmostConnectedConsole(), and KviWindow::view().
Referenced by timerEvent().
void KviApplication::ipcMessage (char * message)
References __tr2qs, _OUTPUT_VERBOSE, KviCString::cutRight(), KviCString::findFirstIdx(), KviMainWindow::firstConsole(), g_pMainWindow, KVI_OUT_SYSTEMMESSAGE, KviCString::len(), KviWindow::output(), KviCString::ptr(), and KviIrcUrl::run().
bool KviApplication::kviClosingDown () const [inline]
Referenced by KviMainWindow::closeWindow(), KviKvsRunTimeContext::leaveBlockingSection(), KviModuleManager::loadModule(), KviMdiManager::tileAllInternal(), and KviModuleManager::unloadModule().
void KviApplication::listAvailableOptions (KviWindow * wnd)
References __tr, g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, i, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, and LIST_OPTIONS.
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviApplication::loadDefaultScript (QString szItem = QString())
References DefScript, KviMainWindow::firstConsole(), g_pMainWindow, getGlobalKvircDirectory(), and KviIrcUrl::run().
Referenced by KviDefaultScriptManager::restoreInternal(), and setup_finish().
void KviApplication::loadDirectories () [private]
References checkFileAssociations(), checkUriAssociations(), findGlobalKvircDirectory(), findLocalKvircDirectory(), init(), KVI_PATH_SEPARATOR, m_bFirstTimeRun, m_szGlobalKvircDir, m_szLocalKvircDir, setupBegin(), setupFileAssociations(), and setupUriAssociations().
Referenced by setup().
void KviApplication::loadOptions ()
References KviStringConversion::decodePath(), g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, getReadOnlyConfigPath(), i, KVI_CONFIGFILE_MAIN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KviConfigurationFile::Read, and READ_OPTIONS.
Referenced by setup().
void KviApplication::loadRecentEntries () [private]
References Config, g_pRecentTopicList, getLocalKvircDirectory(), KVI_CONFIGFILE_RECENT, KviConfigurationFile::Read, and KviConfigurationFile::readStringListEntry().
Referenced by setup().
bool KviApplication::mapImageFile (QString & szRetPath, const QString & filename)
References KviQString::cutToFirst(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), getGlobalKvircDirectory(), getLocalKvircDirectory(), i, KviFileUtils::isAbsolutePath(), KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, pics_globalsubdirs, pics_localsubdirs, and szBuffer.
Referenced by KviImageDialog::itemDoubleClicked().
void KviApplication::notifierMessage (KviWindow * pWnd, int iIconId, const QString & szMsg, unsigned int uMessageLifetime)
References __tr2qs, KviIrcUserEntry::avatar(), KviIconManager::Bomb, Channel, KviWindow::Channel, connect(), KviWindow::Console, KviModule::ctrl(), KviWindow::DccChat, KviIconManager::DccMsg, KviWindow::DccTransfer, KviWindow::Debug, g_pIconManager, g_pModuleManager, KviModuleManager::getModule(), KviIconManager::getSmallIcon(), KviIconManager::getSmallIconName(), KviUserListEntry::globalData(), KVI_OPTION_BOOL, KviOption_boolUseDBusNotifier, KviOption_boolUseKDENotifier, KviIconManager::KVIrc, KviIconManager::Links, m, KviFileUtils::makeDir(), None, KviAvatar::pixmap(), _KviNotifierMessageParam::pWindow, KviIconManager::Query, KviWindow::Query, s, KviIconManager::ServerPing, showParentFrame(), KviWindow::SocketSpy, KviIconManager::Spy, KviControlCodes::stripControlBytes(), _KviNotifierMessageParam::szIcon, _KviNotifierMessageParam::szMessage, KviWindow::target(), KviWindow::type(), _KviNotifierMessageParam::uMessageLifetime, KviWindow::Unknown, KviIconManager::UserWindow, KviWindow::UserWindow, and KviFileUtils::writeFile().
Referenced by DccVideoWindow::event(), DccChatWindow::event(), fileDownloadTerminated(), KviNotifyListManager::notifyOnLine(), KviConsoleWindow::outputPrivmsg(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
void KviApplication::optionResetUpdate (int flags)
References buildRecentChannels(), KviMainWindow::executeInternalCommand(), g_iIdentDaemonRunningUsers, g_pApp, g_pIconManager, g_pMainWindow, KVI_INTERNALCOMMAND_IDENT_START, KVI_INTERNALCOMMAND_IDENT_STOP, KVI_OPTION_BOOL, KviOption_boolUseIdentService, KviOption_boolUseIdentServiceOnlyOnConnect, KviMainWindow::recreateWindowList(), reloadImages(), KviIconManager::reloadImages(), restartLagMeters(), restartNotifyLists(), triggerUpdateGui(), updateApplicationFont(), and updateNotifier().
Referenced by KviOptionsWidget::commitOptionsReset(), KviMainWindow::iconSizePopupSelected(), KviTheme::load(), RegisteredUserEntryDialog::okClicked(), and setOptionValue().
KviPointerHashTable<QString,QStringList>* KviApplication::recentChannels () const [inline]
Referenced by ChannelsJoinDialog::deleteClicked(), and ChannelsJoinDialog::fillListView().
QStringList * KviApplication::recentChannelsForNetwork (const QString & net)
References buildRecentChannels(), KviPointerHashTable< Key, T >::find(), and m_pRecentChannelDict.
Referenced by KviConsoleWindow::completeChannel(), ChannelsJoinDialog::fillListView(), and fillRecentChannelsPopup().
void KviApplication::recentUrlsChanged () [signal]
Referenced by addRecentUrl().
void KviApplication::registerWindow (KviWindow * wnd) [protected]
References g_pGlobalWindowDict, and KviWindow::id().
Referenced by KviWindow::KviWindow().
void KviApplication::reloadImages () [signal]
Referenced by optionResetUpdate().
void KviApplication::resetAvatarForMatchingUsers (KviRegisteredUser * u)
References KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, and KviWindow::type().
Referenced by RegistrationWizard::accept(), and reguser_kvs_cmd_setproperty().
void KviApplication::restartLagMeters ()
References KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, and KviWindow::type().
Referenced by KviStatusBarLagIndicator::mouseDoubleClickEvent(), and optionResetUpdate().
void KviApplication::restartNotifyLists ()
References KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, and KviWindow::type().
Referenced by RegistrationWizard::accept(), RegisteredUsersDialog::okClicked(), optionResetUpdate(), reguser_kvs_cmd_remove(), and reguser_kvs_cmd_setproperty().
void KviApplication::restoreDefaultScript () [slot]
References KviDefaultScriptManager::instance(), and KviDefaultScriptManager::restore().
Referenced by checkSuggestRestoreDefaultScript().
void KviApplication::saveActions ()
References Config, getLocalKvircDirectory(), KviActionManager::instance(), KVI_CONFIGFILE_USERACTIONS, and KviActionManager::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveAliases ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_ALIASES.
Referenced by AliasEditorWidget::commit(), saveConfiguration(), and ~KviApplication().
void KviApplication::saveAppEvents ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_EVENTS.
Referenced by EventEditor::commit(), saveConfiguration(), and ~KviApplication().
void KviApplication::saveAvatarCache ()
References Config, getLocalKvircDirectory(), KviAvatarCache::instance(), KVI_CONFIGFILE_AVATARCACHE, and KviAvatarCache::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveConfiguration () [virtual, slot]
Saves configuration to disk.
Returns:
void
Implements KviTalApplication.
References KviKvs::flushUserClasses(), KviCustomToolBarManager::instance(), saveActions(), saveAliases(), saveAppEvents(), saveAvatarCache(), saveDefaultScripts(), saveIdentities(), saveIdentityProfiles(), saveInputHistory(), saveIrcServerDataBase(), saveMediaTypes(), saveNickServ(), saveOptions(), savePopups(), saveProxyDataBase(), saveRawEvents(), saveRecentEntries(), saveRegisteredChannels(), saveRegisteredUsers(), saveScriptAddons(), saveSharedFiles(), saveTextIcons(), saveToolBars(), KviCustomToolBarManager::storeVisibilityState(), and KviConfigurationFile::sync().
Referenced by OptionsDialog::apply(), and options_kvs_cmd_save().
void KviApplication::saveDefaultScripts ()
References Config, getLocalKvircDirectory(), KviDefaultScriptManager::instance(), KVI_CONFIGFILE_DEFAULTSCRIPT, and KviDefaultScriptManager::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveIdentities ()
References Config, getLocalKvircDirectory(), KviUserIdentityManager::instance(), KVI_CONFIGFILE_IDENTITIES, and KviUserIdentityManager::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveIdentityProfiles ()
References Config, getLocalKvircDirectory(), KviIdentityProfileSet::instance(), KVI_CONFIGFILE_PROFILESDATABASE, and KviIdentityProfileSet::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveInputHistory ()
References Config, getLocalKvircDirectory(), KviInputHistory::instance(), KVI_CONFIGFILE_INPUTHISTORY, KVI_OPTION_BOOL, KviOption_boolEnableInputHistory, and KviInputHistory::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveIrcServerDataBase ()
References Config, g_pServerDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_SERVERDB, and KviIrcServerDataBase::save().
Referenced by OptionsWidget_servers::commit(), saveConfiguration(), setup_finish(), and ~KviApplication().
void KviApplication::saveKvircDirectory () [private]
References KVI_HOME_CONFIG_FILE_NAME, KVI_PATH_SEPARATOR, KVI_SOURCES_DATE_NUMERIC, m_szConfigFile, m_szLocalKvircDir, KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by SetupWizard::accept().
void KviApplication::saveMediaTypes ()
References Config, g_pMediaManager, getLocalKvircDirectory(), KVI_CONFIGFILE_MEDIATYPES, KviMutex::lock(), KviMediaManager::save(), and KviMutex::unlock().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveNickServ ()
References Config, g_pNickServRuleSet, getLocalKvircDirectory(), KVI_CONFIGFILE_NICKSERVDATABASE, and KviNickServRuleSet::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveOptions ()
References __tr2qs, Config, KviStringConversion::decodePath(), KviStringConversion::encodePath(), KviConfigurationFile::ensureWritable(), g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, getLocalKvircDirectory(), i, KVI_CONFIGFILE_MAIN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, saveRecentChannels(), KviMessageBox::warning(), KviConfigurationFile::Write, and WRITE_OPTIONS.
Referenced by OptionsWidgetContainer::okClicked(), saveConfiguration(), and ~KviApplication().
void KviApplication::savePopups ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_POPUPS.
Referenced by PopupEditorWidget::commit(), saveConfiguration(), and ~KviApplication().
void KviApplication::saveProxyDataBase ()
References Config, g_pProxyDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_PROXYDB, and KviProxyDataBase::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveRawEvents ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_RAWEVENTS.
Referenced by RawEditorWidget::commit(), saveConfiguration(), and ~KviApplication().
void KviApplication::saveRecentChannels () [protected]
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KVI_OPTION_STRINGLIST, KVI_RECENT_CHANNELS_SEPARATOR, KviOption_stringlistRecentChannels, and m_pRecentChannelDict.
Referenced by saveOptions().
void KviApplication::saveRecentEntries ()
References Config, g_pRecentTopicList, getLocalKvircDirectory(), KVI_CONFIGFILE_RECENT, KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveRegisteredChannels ()
References Config, g_pRegisteredChannelDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_REGCHANDB, and KviRegisteredChannelDataBase::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveRegisteredUsers ()
References Config, g_pRegisteredUserDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_REGUSERDB, and KviRegisteredUserDataBase::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveScriptAddons ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_SCRIPTADDONS.
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveSharedFiles ()
References Config, g_pSharedFilesManager, getLocalKvircDirectory(), KVI_CONFIGFILE_SHAREDFILES, and KviSharedFilesManager::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveTextIcons ()
References g_pTextIconManager, and KviTextIconManager::save().
Referenced by saveConfiguration(), and ~KviApplication().
void KviApplication::saveToolBars ()
References Config, getLocalKvircDirectory(), KviCustomToolBarManager::instance(), KVI_CONFIGFILE_CUSTOMTOOLBARS, and KviCustomToolBarManager::save().
Referenced by KviActionManager::customizeToolBarsDialogDestroyed(), saveConfiguration(), and ~KviApplication().
void KviApplication::setAvatarFromOptions ()
References KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, and KviWindow::type().
Referenced by OptionsWidget_identityAvatar::commit().
void KviApplication::setAvatarOnFileReceived (KviConsoleWindow * pConsole, const QString & szRemoteUrl, const QString & szNick, const QString & szUser, const QString & szHost)
References KviPointerList< T >::append(), KviPointerList< T >::count(), KVI_MAX_PENDING_AVATARS, m_pPendingAvatarChanges, _KviPendingAvatarChange::pConsole, KviPointerList< T >::removeFirst(), KviPointerList< T >::setAutoDelete(), szHost, _KviPendingAvatarChange::szHost, _KviPendingAvatarChange::szNick, _KviPendingAvatarChange::szRemoteUrl, and _KviPendingAvatarChange::szUser.
Referenced by avatar_kvs_cmd_set(), and KviIrcServerParser::parseCtcpReplyAvatar().
bool KviApplication::setCommonOptionValue (const QString & optName, const QString & value)
References g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, KVI_BOOL_OPTIONS_PREFIX, KVI_BOOL_OPTIONS_PREFIX_LEN, KVI_COLOR_OPTIONS_PREFIX, KVI_COLOR_OPTIONS_PREFIX_LEN, KVI_FONT_OPTIONS_PREFIX, KVI_FONT_OPTIONS_PREFIX_LEN, KVI_ICCOLOR_OPTIONS_PREFIX, KVI_ICCOLOR_OPTIONS_PREFIX_LEN, KVI_MIRCCOLOR_OPTIONS_PREFIX, KVI_MIRCCOLOR_OPTIONS_PREFIX_LEN, KVI_MSGTYPE_OPTIONS_PREFIX, KVI_MSGTYPE_OPTIONS_PREFIX_LEN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KVI_STRING_OPTIONS_PREFIX, KVI_STRING_OPTIONS_PREFIX_LEN, KVI_STRINGLIST_OPTIONS_PREFIX, KVI_STRINGLIST_OPTIONS_PREFIX_LEN, KVI_UINT_OPTIONS_PREFIX, KVI_UINT_OPTIONS_PREFIX_LEN, and SET_OPTION_VALUE.
Referenced by setOptionValue().
void KviApplication::setKviClosingDown () [inline]
Referenced by KviMainWindow::closeEvent().
bool KviApplication::setOptionValue (const QString & optName, const QString & value)
References buildRecentChannels(), KviQString::equalCI(), KviQString::equalCIN(), findImage(), KviStringConversion::fromString(), g_pixmapOptionsTable, i, KVI_NUM_PIXMAP_OPTIONS, KVI_PIXMAP_OPTIONS_PREFIX, KVI_PIXMAP_OPTIONS_PREFIX_LEN, KviOsInfo::name(), optionResetUpdate(), setCommonOptionValue(), and szBuffer.
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviApplication::setup ()
References checkSuggestRestoreDefaultScript(), KviLocale::codecForName(), Config, createFrame(), createIpcSentinel(), createSplashScreen(), destroySplashScreen(), KviMainWindow::executeInternalCommand(), KviFileUtils::fileExists(), firstTimeRun(), g_pGlobalWindowDict, g_pIconManager, g_pInputPopup, g_pMainWindow, g_pMediaManager, g_pModuleExtensionManager, g_pModuleManager, g_pNickServRuleSet, g_pProxyDataBase, g_pRecentTopicList, g_pRegisteredChannelDataBase, g_pRegisteredUserDataBase, g_pServerDataBase, g_pServerParser, g_pSharedFilesManager, g_pTextIconManager, getGlobalKvircDirectory(), getLocalKvircDirectory(), getReadOnlyConfigPath(), KviThreadManager::globalInit(), init(), KviDefaultScriptManager::instance(), KviInputHistory::instance(), KviAvatarCache::instance(), KviIdentityProfileSet::instance(), KviCustomToolBarManager::instance(), KviUserIdentityManager::instance(), KviActionManager::instance(), KviLocale::instance(), KVI_CONFIGFILE_ALIASES, KVI_CONFIGFILE_AVATARCACHE, KVI_CONFIGFILE_CUSTOMTOOLBARS, KVI_CONFIGFILE_DEFAULTSCRIPT, KVI_CONFIGFILE_EVENTS, KVI_CONFIGFILE_IDENTITIES, KVI_CONFIGFILE_INPUTHISTORY, KVI_CONFIGFILE_MEDIATYPES, KVI_CONFIGFILE_NICKSERVDATABASE, KVI_CONFIGFILE_POPUPS, KVI_CONFIGFILE_PROFILESDATABASE, KVI_CONFIGFILE_PROXYDB, KVI_CONFIGFILE_RAWEVENTS, KVI_CONFIGFILE_REGCHANDB, KVI_CONFIGFILE_REGUSERDB, KVI_CONFIGFILE_SCRIPTADDONS, KVI_CONFIGFILE_SERVERDB, KVI_CONFIGFILE_SHAREDFILES, KVI_CONFIGFILE_USERACTIONS, KVI_CONFIGFILE_WINPROPERTIES, KVI_INTERNALCOMMAND_SERVERSJOIN_OPEN, KVI_OPTION_BOOL, KVI_SPLASH_SET_PROGRESS, KVI_VERSION, KviMainWindow::KviIrcServerParser, KviOption_boolShowIconsInPopupMenus, KviOption_boolShowServersConnectDialogOnStart, KviDefaultScriptManager::load(), KviInputHistory::load(), KviAvatarCache::load(), KviIdentityProfileSet::load(), KviNickServRuleSet::load(), KviSharedFilesManager::load(), KviRegisteredChannelDataBase::load(), KviRegisteredUserDataBase::load(), KviMediaManager::load(), KviTextIconManager::load(), KviCustomToolBarManager::load(), KviProxyDataBase::load(), KviIrcServerDataBase::load(), KviUserIdentityManager::load(), KviActionManager::load(), KviKvs::loadAliases(), KviKvs::loadAppEvents(), loadDirectories(), loadOptions(), KviKvs::loadPopups(), KviKvs::loadRawEvents(), loadRecentEntries(), KviKvs::loadScriptAddons(), KviMutex::lock(), m_bSetupDone, m_bShowSplashScreen, m_iHeartbeatTimerId, m_szGlobalKvircDir, m_szLocalKvircDir, None, Pics, KviFileUtils::readFile(), KviConfigurationFile::ReadWrite, setupFinish(), KviMutex::unlock(), updateApplicationFont(), updatePseudoTransparency(), and w.
Referenced by main().
void KviApplication::setupBegin ()
References __tr2qs, KviQString::ensureLastCharIs(), g_pSetupLibrary, getGlobalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, Modules, and KviMessageBox::warning().
Referenced by loadDirectories().
void KviApplication::setupFileAssociations () [private]
References __tr2qs.
Referenced by loadDirectories().
void KviApplication::setupFinish ()
References __tr2qs, g_pSetupLibrary, and KviMessageBox::warning().
Referenced by setup().
void KviApplication::setupUriAssociations (const char * proto) [private]
Referenced by loadDirectories().
void KviApplication::showParentFrame () [slot]
References g_pMainWindow.
Referenced by notifierMessage().
bool KviApplication::supportsCompositing () [inline]
Referenced by KviThemedTreeWidget::applyOptions(), KviThemedLineEdit::applyOptions(), KviThemedLabel::applyOptions(), KviThemedComboBox::applyOptions(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), MessageListWidgetItemDelegate::paint(), UrlDialogTreeWidget::paintEvent(), NotifierWindowTab::paintEvent(), KviIOGraphWindow::paintEvent(), FileTransferWidget::paintEvent(), KviUserListViewArea::paintEvent(), KviTreeWindowListTreeWidget::paintEvent(), KviThemedTreeWidget::paintEvent(), KviThemedLineEdit::paintEvent(), KviThemedLabel::paintEvent(), KviThemedComboBox::paintEvent(), KviMdiManager::paintEvent(), KviIrcView::paintEvent(), KviToolBarGraphicalApplet::paintEvent(), and KviInputEditor::paintEvent().
QStyle* KviApplication::themedStyle ()
void KviApplication::timerEvent (QTimerEvent * e) [protected, virtual]
References heartbeat(), kvi_time_t, kvi_unixTime, and m_iHeartbeatTimerId.
KviConsoleWindow * KviApplication::topmostConnectedConsole ()
References activeConsole(), KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KviConsoleWindow::isConnected(), and KviWindow::type().
Referenced by ChannelsJoinDialog::clearClicked(), ChannelsJoinDialog::enableJoin(), KviTrayIconWidget::fillContextPopup(), heartbeat(), ChannelsJoinDialog::joinClicked(), KviKvsCoreFunctions::KVSCF(), and ChannelsJoinDialog::regClicked().
void KviApplication::triggerUpdateGui ()
References m_bUpdateGuiPending, and updateGui().
Referenced by optionResetUpdate().
void KviApplication::unregisterWindow (KviWindow * wnd) [protected]
References g_pGlobalWindowDict, and KviWindow::id().
Referenced by KviWindow::~KviWindow().
void KviApplication::updateApplicationFont () [private]
References g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_FONT, KviOption_boolUseGlobalApplicationFont, KviOption_fontApplication, and m_fntDefaultFont.
Referenced by optionResetUpdate(), and setup().
void KviApplication::updateGui () [slot]
References KviMainWindow::applyOptions(), g_pMainWindow, KVI_OPTION_BOOL, KviOption_boolShowIconsInPopupMenus, and m_bUpdateGuiPending.
Referenced by triggerUpdateGui().
void KviApplication::updateNotifier () [signal]
Referenced by optionResetUpdate().
void KviApplication::updatePseudoTransparency () [slot]
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_PIXMAP, KviOption_boolUseCompositingForTransparency, KviOption_boolUseGlobalPseudoTransparency, KviOption_boolUseWindowsDesktopForTransparency, KviOption_pixmapGlobalTransparencyBackground, and KviMainWindow::updatePseudoTransparency().
Referenced by setup().
unsigned int KviApplication::windowCount ()
References g_pGlobalWindowDict.
Referenced by KviWindow::~KviWindow().
bool KviApplication::windowExists (KviWindow * wnd)
References KviPointerHashTableIterator< Key, T >::current(), and g_pGlobalWindowDict.
Referenced by DccBroker::activeVideoExecute(), DccBroker::activeVoiceExecute(), KviKvsDnsManager::dnsLookupTerminated(), DccFileTransfer::event(), KviKvsCallbackObject::execute(), DccBroker::executeChat(), fileDownloadTerminated(), KviKvsPopupMenu::itemClicked(), KviKvsRunTimeContext::leaveBlockingSection(), KviKvsAsyncDnsOperation::lookupTerminated(), NotifierWindowTab::mouseDoubleClickEvent(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), DccBroker::passiveVideoExecute(), SlowPasteController::pasteClipboard(), SlowPasteController::pasteFile(), DccBroker::recvFileExecute(), KviKvsReport::report(), DccBroker::rsendExecute(), DccBroker::sendFileExecute(), KviKvsPopupMenu::setupMenuContents(), KviKvsTimerManager::timerEvent(), KviKvsProcessAsyncOperation::trigger(), and DccDescriptor::~DccDescriptor().
Friends And Related Function Documentation
friend class KviMainWindow [friend]
Referenced by createFrame().
friend class KviWindow [friend]
friend class SetupWizard [friend]
Member Data Documentation
bool KviApplication::m_bClosingDown [protected]
Referenced by KviApplication(), and ~KviApplication().
bool KviApplication::m_bCreateConfig
Referenced by KviApplication(), and main().
bool KviApplication::m_bFirstTimeRun [protected]
Referenced by loadDirectories().
bool KviApplication::m_bSetupDone [protected]
Referenced by KviApplication(), setup(), and ~KviApplication().
bool KviApplication::m_bShowSplashScreen
Referenced by KviApplication(), main(), and setup().
bool KviApplication::m_bUpdateGuiPending [protected]
Referenced by KviApplication(), triggerUpdateGui(), and updateGui().
QFont KviApplication::m_fntDefaultFont [protected]
Referenced by KviApplication(), and updateApplicationFont().
int KviApplication::m_iHeartbeatTimerId [protected]
Referenced by KviApplication(), setup(), and timerEvent().
KviWindow* KviApplication::m_pActiveWindow [protected]
KviIpcSentinel* KviApplication::m_pIpcSentinel [protected]
Referenced by createIpcSentinel(), destroyIpcSentinel(), and KviApplication().
KviPointerList<KviPendingAvatarChange>* KviApplication::m_pPendingAvatarChanges [protected]
Referenced by fileDownloadTerminated(), findPendingAvatarChange(), KviApplication(), setAvatarOnFileReceived(), and ~KviApplication().
KviPointerHashTable<QString,QStringList>* KviApplication::m_pRecentChannelDict [protected]
Referenced by addRecentChannel(), buildRecentChannels(), KviApplication(), recentChannelsForNetwork(), saveRecentChannels(), and ~KviApplication().
QString KviApplication::m_szConfigFile
Referenced by findLocalKvircDirectory(), KviApplication(), main(), and saveKvircDirectory().
QString KviApplication::m_szExecAfterStartup
Referenced by createFrame(), and main().
QString KviApplication::m_szGlobalKvircDir [protected]
Referenced by SetupWizard::accept(), findGlobalKvircDirectory(), getGlobalKvircDirectory(), loadDirectories(), SetupWizard::makeLink(), setup(), and SetupWizard::setUrlHandlers().
QString KviApplication::m_szLocalKvircDir [protected]
Referenced by SetupWizard::accept(), checkLocalKvircDirectory(), findLocalKvircDirectory(), getLocalKvircDirectory(), loadDirectories(), saveKvircDirectory(), and setup().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviApplication.h
src/kvirc/kernel/KviApplication.cpp
src/kvirc/kernel/KviApplication_filesystem.cpp
src/kvirc/kernel/KviApplication_setup.cpp
src/kvirc/kernel/KviOptions.cpp