KVIrc: KvsObject_listWidget Class Reference
KvsObject_listWidget Class Reference
#include <KvsObject_listWidget.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void currentItemChanged (QListWidgetItem *, QListWidgetItem *)
void selectionChanged ()
void slotItemChanged (QListWidgetItem *item)
void slotItemEntered (QListWidgetItem *item)
Protected Member Functions
bool changeItem (KviKvsObjectFunctionCall *c)
bool clear (KviKvsObjectFunctionCall *c)
bool count (KviKvsObjectFunctionCall *c)
bool currentItem (KviKvsObjectFunctionCall *c)
bool currentItemChangedEvent (KviKvsObjectFunctionCall *c)
bool currentText (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertItem (KviKvsObjectFunctionCall *c)
bool insertWidgetItem (KviKvsObjectFunctionCall *c)
bool isChecked (KviKvsObjectFunctionCall *c)
bool isSelected (KviKvsObjectFunctionCall *c)
bool itemAt (KviKvsObjectFunctionCall *c)
bool itemChangedEvent (KviKvsObjectFunctionCall *c)
bool itemEnteredEvent (KviKvsObjectFunctionCall *c)
bool itemRect (KviKvsObjectFunctionCall *c)
bool removeItem (KviKvsObjectFunctionCall *c)
bool selectedItems (KviKvsObjectFunctionCall *c)
bool selectionMode (KviKvsObjectFunctionCall *c)
bool setChecked (KviKvsObjectFunctionCall *c)
bool setCurrentItem (KviKvsObjectFunctionCall *c)
bool setFlags (KviKvsObjectFunctionCall *c)
bool setFont (KviKvsObjectFunctionCall *c)
bool setForeground (KviKvsObjectFunctionCall *c)
bool setIcon (KviKvsObjectFunctionCall *c)
bool setSelected (KviKvsObjectFunctionCall *c)
bool setSelectionMode (KviKvsObjectFunctionCall *c)
bool textAt (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_listWidget::changeItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::clear (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::count (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::currentItem (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_listWidget::currentItemChanged (QListWidgetItem * currentItem, QListWidgetItem *) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_listWidget::currentItemChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::currentText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_listWidget::insertItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::insertWidgetItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::isChecked (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::isSelected (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::itemAt (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::itemChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::itemEnteredEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::itemRect (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::removeItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::selectedItems (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_listWidget::selectionChanged () [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_listWidget::selectionMode (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setChecked (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setCurrentItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setFlags (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setFont (KviKvsObjectFunctionCall * c) [protected]
Reimplemented from KvsObject_widget.
bool KvsObject_listWidget::setForeground (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setIcon (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setSelected (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_listWidget::setSelectionMode (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_listWidget::slotItemChanged (QListWidgetItem * item) [protected, slot]
References KviKvsObject::callFunction(), and widget().
void KvsObject_listWidget::slotItemEntered (QListWidgetItem * item) [protected, slot]
References KviKvsObject::callFunction(), and widget().
bool KvsObject_listWidget::textAt (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_listWidget::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
Referenced by slotItemChanged(), and slotItemEntered().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_listWidget.h
src/modules/objects/KvsObject_listWidget.cpp