KVIrc: KviIdentityProfile Class Reference
KviIdentityProfile Class Reference
Class which manages the identity profile.
#include <KviIdentityProfile.h>
Public Member Functions
const QString & altNick () const
Returns the alternative nickname of the profile.
void copyFrom (const KviIdentityProfile &src)
Carbon copy.
KviIdentityProfile ()
Constructs the identity profile object.
bool load (KviConfigurationFile *pCfg, const QString &szPrefix)
Loads the configuration from file.
const QString & name () const
Returns the name of the profile.
const QString & network () const
Returns the network of the profile.
const QString & nick () const
Returns the nickname of the profile.
const QString & realName () const
Returns the realname of the profile.
void save (KviConfigurationFile *pCfg, const QString &szPrefix)
Saves the configuration to file.
void setAltNick (const QString &szAltNick)
Sets the alternative nickname of the profile.
void setName (const QString &szName)
Sets the name of the profile.
void setNetwork (const QString &szNetwork)
Sets the network of the profile.
void setNick (const QString &szNick)
Sets the nickname of the profile.
void setRealName (const QString &szRealName)
Sets the realname of the profile.
void setUserName (const QString &szUserName)
Sets the username of the profile.
const QString & userName () const
Returns the username of the profile.
~KviIdentityProfile ()
Destroys the identity profile object.
Protected Attributes
QString m_szAltNick
QString m_szName
QString m_szNetwork
QString m_szNick
QString m_szRealName
QString m_szUserName
Detailed Description
Class which manages the identity profile.
Constructor & Destructor Documentation
KviIdentityProfile::KviIdentityProfile ()
Constructs the identity profile object.
Returns:
KviIdentityProfile
KviIdentityProfile::~KviIdentityProfile ()
Destroys the identity profile object.
Returns:
KviIdentityProfile
Member Function Documentation
const QString& KviIdentityProfile::altNick () const [inline]
Returns the alternative nickname of the profile.
Returns:
const QString &
Referenced by OptionsWidget_identityProfile::addProfileEntry(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
void KviIdentityProfile::copyFrom (const KviIdentityProfile & src)
Carbon copy.
Parameters:
src The source profile
Returns:
void
References m_szAltNick, m_szName, m_szNetwork, m_szNick, m_szRealName, and m_szUserName.
Referenced by KviIdentityProfileSet::copyFrom().
bool KviIdentityProfile::load (KviConfigurationFile * pCfg, const QString & szPrefix)
Loads the configuration from file.
Returns false if the loaded data has no sense
Parameters:
pCfg The configuration file
szPrefix The prefix to use
Returns:
bool
References m_szAltNick, m_szName, m_szNetwork, m_szNick, m_szRealName, m_szUserName, and KviConfigurationFile::readEntry().
Referenced by KviIdentityProfileSet::loadPrivate().
const QString& KviIdentityProfile::name () const [inline]
Returns the name of the profile.
Returns:
const QString &
Referenced by OptionsWidget_identityProfile::addProfileEntry(), IdentityProfileEditor::editProfile(), OptionsWidget_identityProfile::editProfileEntry(), and KviIdentityProfileSet::findName().
const QString& KviIdentityProfile::network () const [inline]
Returns the network of the profile.
Returns:
const QString &
Referenced by OptionsWidget_identityProfile::addProfileEntry(), IdentityProfileEditor::editProfile(), OptionsWidget_identityProfile::editProfileEntry(), and KviIdentityProfileSet::findNetwork().
const QString& KviIdentityProfile::nick () const [inline]
Returns the nickname of the profile.
Returns:
const QString &
Referenced by OptionsWidget_identityProfile::addProfileEntry(), IdentityProfileEditor::editProfile(), OptionsWidget_identityProfile::editProfileEntry(), and KviIrcConnection::pickNextLoginNickName().
const QString& KviIdentityProfile::realName () const [inline]
Returns the realname of the profile.
Returns:
const QString &
Referenced by OptionsWidget_identityProfile::addProfileEntry(), IdentityProfileEditor::editProfile(), OptionsWidget_identityProfile::editProfileEntry(), and KviIrcConnection::useProfileData().
void KviIdentityProfile::save (KviConfigurationFile * pCfg, const QString & szPrefix)
Saves the configuration to file.
Parameters:
pCfg The configuration file
szPrefix The prefix to use
Returns:
void
References m_szAltNick, m_szName, m_szNetwork, m_szNick, m_szRealName, m_szUserName, and KviConfigurationFile::writeEntry().
void KviIdentityProfile::setAltNick (const QString & szAltNick) [inline]
Sets the alternative nickname of the profile.
Parameters:
szAltNick The alternative nickname of the profile
Returns:
void
Referenced by OptionsWidget_identityProfile::commit(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
void KviIdentityProfile::setName (const QString & szName) [inline]
Sets the name of the profile.
Parameters:
szName The name of the profile
Returns:
void
Referenced by OptionsWidget_identityProfile::commit(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
void KviIdentityProfile::setNetwork (const QString & szNetwork) [inline]
Sets the network of the profile.
Parameters:
szNetwork The network of the profile
Returns:
void
Referenced by OptionsWidget_identityProfile::commit(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
void KviIdentityProfile::setNick (const QString & szNick) [inline]
Sets the nickname of the profile.
Parameters:
szNick The nickname of the profile
Returns:
void
Referenced by OptionsWidget_identityProfile::commit(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
void KviIdentityProfile::setRealName (const QString & szRealName) [inline]
Sets the realname of the profile.
Parameters:
szRealName The realname of the profile
Returns:
void
Referenced by OptionsWidget_identityProfile::commit(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
void KviIdentityProfile::setUserName (const QString & szUserName) [inline]
Sets the username of the profile.
Parameters:
szUserName The username of the profile
Returns:
void
Referenced by OptionsWidget_identityProfile::commit(), IdentityProfileEditor::editProfile(), and OptionsWidget_identityProfile::editProfileEntry().
const QString& KviIdentityProfile::userName () const [inline]
Returns the username of the profile.
Returns:
const QString &
Referenced by OptionsWidget_identityProfile::addProfileEntry(), IdentityProfileEditor::editProfile(), OptionsWidget_identityProfile::editProfileEntry(), and KviIrcConnection::useProfileData().
Member Data Documentation
QString KviIdentityProfile::m_szAltNick [protected]
Referenced by copyFrom(), load(), and save().
QString KviIdentityProfile::m_szName [protected]
Referenced by copyFrom(), load(), and save().
QString KviIdentityProfile::m_szNetwork [protected]
Referenced by copyFrom(), load(), and save().
QString KviIdentityProfile::m_szNick [protected]
Referenced by copyFrom(), load(), and save().
QString KviIdentityProfile::m_szRealName [protected]
Referenced by copyFrom(), load(), and save().
QString KviIdentityProfile::m_szUserName [protected]
Referenced by copyFrom(), load(), and save().
The documentation for this class was generated from the following files:
src/kvilib/irc/KviIdentityProfile.h
src/kvilib/irc/KviIdentityProfile.cpp