KVIrc: OptionsInstanceManager Class Reference
OptionsInstanceManager Class Reference
#include <OptionsInstanceManager.h>
Public Member Functions
void cleanup (KviModule *)
OptionsWidgetInstanceEntry * findInstanceEntry (const char *pcName)
KviOptionsWidget * getInstance (OptionsWidgetInstanceEntry *pEntry, QWidget *pPar)
KviPointerList
< OptionsWidgetInstanceEntry > * instanceEntryTree ()
OptionsInstanceManager ()
virtual ~OptionsInstanceManager ()
Protected Slots
void widgetDestroyed ()
Protected Member Functions
void deleteInstanceTree (KviPointerList< OptionsWidgetInstanceEntry > *pList)
OptionsWidgetInstanceEntry * findInstanceEntry (const char *pcName, KviPointerList< OptionsWidgetInstanceEntry > *pList)
OptionsWidgetInstanceEntry * findInstanceEntry (const QObject *pObj, KviPointerList< OptionsWidgetInstanceEntry > *pList)
Protected Attributes
KviPointerList
< OptionsWidgetInstanceEntry > * m_pInstanceTree
Constructor & Destructor Documentation
OptionsInstanceManager::OptionsInstanceManager ()
References __tr2qs_ctx_no_xgettext, KviPointerList< T >::append(), _OptionsWidgetInstanceEntry::bIsContainer, _OptionsWidgetInstanceEntry::bIsNotContained, classKviIdentityGeneralOptionsWidget_createInstanceProc(), classOptionsWidget_alerts_createInstanceProc(), classOptionsWidget_alertsAndHighlighting_createInstanceProc(), classOptionsWidget_antispam_createInstanceProc(), classOptionsWidget_avatar_createInstanceProc(), classOptionsWidget_away_createInstanceProc(), classOptionsWidget_channel_createInstanceProc(), classOptionsWidget_channelAdvanced_createInstanceProc(), classOptionsWidget_channelGeneral_createInstanceProc(), classOptionsWidget_connection_createInstanceProc(), classOptionsWidget_connectionAdvanced_createInstanceProc(), classOptionsWidget_connectionSocket_createInstanceProc(), classOptionsWidget_connectionSsl_createInstanceProc(), classOptionsWidget_ctcp_createInstanceProc(), classOptionsWidget_ctcpFloodProtection_createInstanceProc(), classOptionsWidget_dcc_createInstanceProc(), classOptionsWidget_dccAdvanced_createInstanceProc(), classOptionsWidget_dccChat_createInstanceProc(), classOptionsWidget_dccGeneral_createInstanceProc(), classOptionsWidget_dccSend_createInstanceProc(), classOptionsWidget_dccSendAdvanced_createInstanceProc(), classOptionsWidget_dccSendGeneral_createInstanceProc(), classOptionsWidget_dccVoice_createInstanceProc(), classOptionsWidget_general_createInstanceProc(), classOptionsWidget_highlighting_createInstanceProc(), classOptionsWidget_identity_createInstanceProc(), classOptionsWidget_identityAdvanced_createInstanceProc(), classOptionsWidget_identityAvatar_createInstanceProc(), classOptionsWidget_identityProfile_createInstanceProc(), classOptionsWidget_identService_createInstanceProc(), classOptionsWidget_ignore_createInstanceProc(), classOptionsWidget_inputFeatures_createInstanceProc(), classOptionsWidget_inputLook_createInstanceProc(), classOptionsWidget_interfaceFeatures_createInstanceProc(), classOptionsWidget_irc_createInstanceProc(), classOptionsWidget_ircAdvanced_createInstanceProc(), classOptionsWidget_ircGeneral_createInstanceProc(), classOptionsWidget_ircOutput_createInstanceProc(), classOptionsWidget_ircViewFeatures_createInstanceProc(), classOptionsWidget_ircViewLook_createInstanceProc(), classOptionsWidget_ircViewMarker_createInstanceProc(), classOptionsWidget_ircViewTheme_createInstanceProc(), classOptionsWidget_lag_createInstanceProc(), classOptionsWidget_logging_createInstanceProc(), classOptionsWidget_mediaTypes_createInstanceProc(), classOptionsWidget_message_createInstanceProc(), classOptionsWidget_messageColors_createInstanceProc(), classOptionsWidget_nickServ_createInstanceProc(), classOptionsWidget_notifier_createInstanceProc(), classOptionsWidget_notifierLook_createInstanceProc(), classOptionsWidget_notify_createInstanceProc(), classOptionsWidget_privmsg_createInstanceProc(), classOptionsWidget_protection_createInstanceProc(), classOptionsWidget_proxy_createInstanceProc(), classOptionsWidget_query_createInstanceProc(), classOptionsWidget_servers_createInstanceProc(), classOptionsWidget_sound_createInstanceProc(), classOptionsWidget_soundGeneral_createInstanceProc(), classOptionsWidget_sounds_createInstanceProc(), classOptionsWidget_standardColors_createInstanceProc(), classOptionsWidget_textEncoding_createInstanceProc(), classOptionsWidget_textIcons_createInstanceProc(), classOptionsWidget_theme_createInstanceProc(), classOptionsWidget_themeMdiArea_createInstanceProc(), classOptionsWidget_themeToolBarApplets_createInstanceProc(), classOptionsWidget_themeTransparency_createInstanceProc(), classOptionsWidget_timestamp_createInstanceProc(), classOptionsWidget_tools_createInstanceProc(), classOptionsWidget_topicLabel_createInstanceProc(), classOptionsWidget_tray_createInstanceProc(), classOptionsWidget_uparser_createInstanceProc(), classOptionsWidget_urlHandlers_createInstanceProc(), classOptionsWidget_userList_createInstanceProc(), classOptionsWidget_userListBackground_createInstanceProc(), classOptionsWidget_userListFeatures_createInstanceProc(), classOptionsWidget_userListForeground_createInstanceProc(), classOptionsWidget_userListGrid_createInstanceProc(), classOptionsWidget_windowList_createInstanceProc(), classOptionsWidget_windowListClassic_createInstanceProc(), classOptionsWidget_windowListTree_createInstanceProc(), classOptionsWidget_windowListTreeBackground_createInstanceProc(), classOptionsWidget_windowListTreeFeatures_createInstanceProc(), classOptionsWidget_windowListTreeForeground_createInstanceProc(), _OptionsWidgetInstanceEntry::createProc, _OptionsWidgetInstanceEntry::eIcon, g_szClassName_KviIdentityGeneralOptionsWidget, g_szClassName_OptionsWidget_alerts, g_szClassName_OptionsWidget_alertsAndHighlighting, g_szClassName_OptionsWidget_antispam, g_szClassName_OptionsWidget_avatar, g_szClassName_OptionsWidget_away, g_szClassName_OptionsWidget_channel, g_szClassName_OptionsWidget_channelAdvanced, g_szClassName_OptionsWidget_channelGeneral, g_szClassName_OptionsWidget_connection, g_szClassName_OptionsWidget_connectionAdvanced, g_szClassName_OptionsWidget_connectionSocket, g_szClassName_OptionsWidget_connectionSsl, g_szClassName_OptionsWidget_ctcp, g_szClassName_OptionsWidget_ctcpFloodProtection, g_szClassName_OptionsWidget_dcc, g_szClassName_OptionsWidget_dccAdvanced, g_szClassName_OptionsWidget_dccChat, g_szClassName_OptionsWidget_dccGeneral, g_szClassName_OptionsWidget_dccSend, g_szClassName_OptionsWidget_dccSendAdvanced, g_szClassName_OptionsWidget_dccSendGeneral, g_szClassName_OptionsWidget_dccVoice, g_szClassName_OptionsWidget_general, g_szClassName_OptionsWidget_highlighting, g_szClassName_OptionsWidget_identity, g_szClassName_OptionsWidget_identityAdvanced, g_szClassName_OptionsWidget_identityAvatar, g_szClassName_OptionsWidget_identityProfile, g_szClassName_OptionsWidget_identService, g_szClassName_OptionsWidget_ignore, g_szClassName_OptionsWidget_inputFeatures, g_szClassName_OptionsWidget_inputLook, g_szClassName_OptionsWidget_interfaceFeatures, g_szClassName_OptionsWidget_irc, g_szClassName_OptionsWidget_ircAdvanced, g_szClassName_OptionsWidget_ircGeneral, g_szClassName_OptionsWidget_ircOutput, g_szClassName_OptionsWidget_ircViewFeatures, g_szClassName_OptionsWidget_ircViewLook, g_szClassName_OptionsWidget_ircViewMarker, g_szClassName_OptionsWidget_ircViewTheme, g_szClassName_OptionsWidget_lag, g_szClassName_OptionsWidget_logging, g_szClassName_OptionsWidget_mediaTypes, g_szClassName_OptionsWidget_message, g_szClassName_OptionsWidget_messageColors, g_szClassName_OptionsWidget_nickServ, g_szClassName_OptionsWidget_notifier, g_szClassName_OptionsWidget_notifierLook, g_szClassName_OptionsWidget_notify, g_szClassName_OptionsWidget_privmsg, g_szClassName_OptionsWidget_protection, g_szClassName_OptionsWidget_proxy, g_szClassName_OptionsWidget_query, g_szClassName_OptionsWidget_servers, g_szClassName_OptionsWidget_sound, g_szClassName_OptionsWidget_soundGeneral, g_szClassName_OptionsWidget_sounds, g_szClassName_OptionsWidget_standardColors, g_szClassName_OptionsWidget_textEncoding, g_szClassName_OptionsWidget_textIcons, g_szClassName_OptionsWidget_theme, g_szClassName_OptionsWidget_themeMdiArea, g_szClassName_OptionsWidget_themeToolBarApplets, g_szClassName_OptionsWidget_themeTransparency, g_szClassName_OptionsWidget_timestamp, g_szClassName_OptionsWidget_tools, g_szClassName_OptionsWidget_topicLabel, g_szClassName_OptionsWidget_tray, g_szClassName_OptionsWidget_uparser, g_szClassName_OptionsWidget_urlHandlers, g_szClassName_OptionsWidget_userList, g_szClassName_OptionsWidget_userListBackground, g_szClassName_OptionsWidget_userListFeatures, g_szClassName_OptionsWidget_userListForeground, g_szClassName_OptionsWidget_userListGrid, g_szClassName_OptionsWidget_windowList, g_szClassName_OptionsWidget_windowListClassic, g_szClassName_OptionsWidget_windowListTree, g_szClassName_OptionsWidget_windowListTreeBackground, g_szClassName_OptionsWidget_windowListTreeFeatures, g_szClassName_OptionsWidget_windowListTreeForeground, g_szName_KviIdentityGeneralOptionsWidget, g_szName_OptionsWidget_alerts, g_szName_OptionsWidget_alertsAndHighlighting, g_szName_OptionsWidget_antispam, g_szName_OptionsWidget_avatar, g_szName_OptionsWidget_away, g_szName_OptionsWidget_channel, g_szName_OptionsWidget_channelAdvanced, g_szName_OptionsWidget_channelGeneral, g_szName_OptionsWidget_connection, g_szName_OptionsWidget_connectionAdvanced, g_szName_OptionsWidget_connectionSocket, g_szName_OptionsWidget_connectionSsl, g_szName_OptionsWidget_ctcp, g_szName_OptionsWidget_ctcpFloodProtection, g_szName_OptionsWidget_dcc, g_szName_OptionsWidget_dccAdvanced, g_szName_OptionsWidget_dccChat, g_szName_OptionsWidget_dccGeneral, g_szName_OptionsWidget_dccSend, g_szName_OptionsWidget_dccSendAdvanced, g_szName_OptionsWidget_dccSendGeneral, g_szName_OptionsWidget_dccVoice, g_szName_OptionsWidget_general, g_szName_OptionsWidget_highlighting, g_szName_OptionsWidget_identity, g_szName_OptionsWidget_identityAdvanced, g_szName_OptionsWidget_identityAvatar, g_szName_OptionsWidget_identityProfile, g_szName_OptionsWidget_identService, g_szName_OptionsWidget_ignore, g_szName_OptionsWidget_inputFeatures, g_szName_OptionsWidget_inputLook, g_szName_OptionsWidget_interfaceFeatures, g_szName_OptionsWidget_irc, g_szName_OptionsWidget_ircAdvanced, g_szName_OptionsWidget_ircGeneral, g_szName_OptionsWidget_ircOutput, g_szName_OptionsWidget_ircViewFeatures, g_szName_OptionsWidget_ircViewLook, g_szName_OptionsWidget_ircViewMarker, g_szName_OptionsWidget_ircViewTheme, g_szName_OptionsWidget_lag, g_szName_OptionsWidget_logging, g_szName_OptionsWidget_mediaTypes, g_szName_OptionsWidget_message, g_szName_OptionsWidget_messageColors, g_szName_OptionsWidget_nickServ, g_szName_OptionsWidget_notifier, g_szName_OptionsWidget_notifierLook, g_szName_OptionsWidget_notify, g_szName_OptionsWidget_privmsg, g_szName_OptionsWidget_protection, g_szName_OptionsWidget_proxy, g_szName_OptionsWidget_query, g_szName_OptionsWidget_servers, g_szName_OptionsWidget_sound, g_szName_OptionsWidget_soundGeneral, g_szName_OptionsWidget_sounds, g_szName_OptionsWidget_standardColors, g_szName_OptionsWidget_textEncoding, g_szName_OptionsWidget_textIcons, g_szName_OptionsWidget_theme, g_szName_OptionsWidget_themeMdiArea, g_szName_OptionsWidget_themeToolBarApplets, g_szName_OptionsWidget_themeTransparency, g_szName_OptionsWidget_timestamp, g_szName_OptionsWidget_tools, g_szName_OptionsWidget_topicLabel, g_szName_OptionsWidget_tray, g_szName_OptionsWidget_uparser, g_szName_OptionsWidget_urlHandlers, g_szName_OptionsWidget_userList, g_szName_OptionsWidget_userListBackground, g_szName_OptionsWidget_userListFeatures, g_szName_OptionsWidget_userListForeground, g_szName_OptionsWidget_userListGrid, g_szName_OptionsWidget_windowList, g_szName_OptionsWidget_windowListClassic, g_szName_OptionsWidget_windowListTree, g_szName_OptionsWidget_windowListTreeBackground, g_szName_OptionsWidget_windowListTreeFeatures, g_szName_OptionsWidget_windowListTreeForeground, _OptionsWidgetInstanceEntry::iPriority, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_alertsAndHighlighting, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_channel, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_connectionAdvanced, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_dcc, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_dccSend, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_identity, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_irc, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_ircViewTheme, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_message, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_protection, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_sound, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_userList, KVI_OPTIONS_WIDGET_CONTAINER_OptionsWidget_windowListTree, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_inputLook, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_ircViewFeatures, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_ircViewLook, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_ircViewMarker, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_ircViewTheme, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_message, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_messageColors, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_notifierLook, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_privmsg, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_standardColors, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_theme, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_themeMdiArea, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_themeToolBarApplets, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_themeTransparency, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_timestamp, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_topicLabel, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_userList, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_userListBackground, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_userListForeground, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_userListGrid, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_windowList, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_windowListClassic, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_windowListTree, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_windowListTreeBackground, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_windowListTreeFeatures, KVI_OPTIONS_WIDGET_GROUP_OptionsWidget_windowListTreeForeground, KVI_OPTIONS_WIDGET_ICON_KviIdentityGeneralOptionsWidget, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_alerts, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_alertsAndHighlighting, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_antispam, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_avatar, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_away, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_channel, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_channelAdvanced, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_channelGeneral, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_connection, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_connectionAdvanced, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_connectionSocket, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_connectionSsl, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ctcp, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ctcpFloodProtection, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dcc, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccAdvanced, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccChat, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccGeneral, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccSend, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccSendAdvanced, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccSendGeneral, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_dccVoice, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_general, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_highlighting, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_identity, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_identityAdvanced, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_identityAvatar, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_identityProfile, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_identService, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ignore, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_inputFeatures, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_inputLook, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_interfaceFeatures, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_irc, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircAdvanced, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircGeneral, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircOutput, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircViewFeatures, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircViewLook, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircViewMarker, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_ircViewTheme, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_lag, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_logging, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_mediaTypes, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_message, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_messageColors, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_nickServ, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_notifier, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_notifierLook, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_notify, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_privmsg, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_protection, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_proxy, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_query, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_servers, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_sound, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_soundGeneral, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_sounds, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_standardColors, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_textEncoding, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_textIcons, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_theme, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_themeMdiArea, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_themeToolBarApplets, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_themeTransparency, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_timestamp, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_tools, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_topicLabel, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_tray, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_uparser, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_urlHandlers, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_userList, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_userListBackground, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_userListFeatures, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_userListForeground, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_userListGrid, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_windowList, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_windowListClassic, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_windowListTree, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_windowListTreeBackground, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_windowListTreeFeatures, KVI_OPTIONS_WIDGET_ICON_OptionsWidget_windowListTreeForeground, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_ignore, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_inputLook, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_ircOutput, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_ircViewLook, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_ircViewTheme, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_lag, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_logging, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_mediaTypes, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_message, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_messageColors, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_nickServ, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_notifier, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_notifierLook, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_notify, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_privmsg, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_protection, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_proxy, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_query, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_servers, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_soundGeneral, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_sounds, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_standardColors, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_textEncoding, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_textIcons, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_theme, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_themeMdiArea, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_themeToolBarApplets, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_themeTransparency, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_timestamp, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_topicLabel, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_tray, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_uparser, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_urlHandlers, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_userList, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_userListBackground, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_userListFeatures, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_userListForeground, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_userListGrid, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_windowList, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_windowListClassic, KVI_OPTIONS_WIDGET_KEYWORDS_OptionsWidget_windowListTree, KVI_OPTIONS_WIDGET_NAME_KviIdentityGeneralOptionsWidget, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_alerts, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_alertsAndHighlighting, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_antispam, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_avatar, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_away, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_channel, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_channelAdvanced, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_channelGeneral, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_connection, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_connectionAdvanced, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_connectionSocket, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_connectionSsl, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ctcp, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ctcpFloodProtection, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dcc, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccAdvanced, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccChat, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccGeneral, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccSend, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccSendAdvanced, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccSendGeneral, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_dccVoice, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_general, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_highlighting, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_identity, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_identityAdvanced, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_identityAvatar, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_identityProfile, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_identService, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ignore, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_inputFeatures, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_inputLook, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_interfaceFeatures, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_irc, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircAdvanced, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircGeneral, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircOutput, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircViewFeatures, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircViewLook, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircViewMarker, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_ircViewTheme, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_lag, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_logging, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_mediaTypes, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_message, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_messageColors, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_nickServ, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_notifier, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_notifierLook, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_notify, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_privmsg, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_protection, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_proxy, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_query, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_servers, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_sound, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_soundGeneral, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_sounds, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_standardColors, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_textEncoding, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_textIcons, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_theme, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_themeMdiArea, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_themeToolBarApplets, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_themeTransparency, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_timestamp, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_tools, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_topicLabel, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_tray, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_uparser, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_urlHandlers, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_userList, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_userListBackground, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_userListFeatures, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_userListForeground, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_userListGrid, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_windowList, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_windowListClassic, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_windowListTree, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_windowListTreeBackground, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_windowListTreeFeatures, KVI_OPTIONS_WIDGET_NAME_OptionsWidget_windowListTreeForeground, KVI_OPTIONS_WIDGET_NOTCONTAINED_OptionsWidget_channel, KVI_OPTIONS_WIDGET_NOTCONTAINED_OptionsWidget_dccChat, KVI_OPTIONS_WIDGET_NOTCONTAINED_OptionsWidget_dccVoice, KVI_OPTIONS_WIDGET_NOTCONTAINED_OptionsWidget_protection, KVI_OPTIONS_WIDGET_NOTCONTAINED_OptionsWidget_query, KVI_OPTIONS_WIDGET_NOTCONTAINED_OptionsWidget_tools, KVI_OPTIONS_WIDGET_PRIORITY_KviIdentityGeneralOptionsWidget, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_avatar, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_channel, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_connection, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_connectionSocket, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_connectionSsl, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ctcp, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_dcc, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_dccAdvanced, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_dccGeneral, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_general, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_identity, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_identityAdvanced, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_identityAvatar, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_identityProfile, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_identService, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_interfaceFeatures, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_irc, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ircAdvanced, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ircGeneral, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ircOutput, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ircViewFeatures, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ircViewLook, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_ircViewMarker, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_mediaTypes, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_messageColors, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_nickServ, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_privmsg, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_protection, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_proxy, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_query, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_servers, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_soundGeneral, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_sounds, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_standardColors, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_textEncoding, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_timestamp, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_tools, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_urlHandlers, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_userListBackground, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_userListFeatures, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_userListForeground, KVI_OPTIONS_WIDGET_PRIORITY_OptionsWidget_userListGrid, m_pInstanceTree, _OptionsWidgetInstanceEntry::pChildList, _OptionsWidgetInstanceEntry::pWidget, KviPointerList< T >::setAutoDelete(), _OptionsWidgetInstanceEntry::szClassName, _OptionsWidgetInstanceEntry::szGroup, _OptionsWidgetInstanceEntry::szKeywords, _OptionsWidgetInstanceEntry::szKeywordsNoLocale, _OptionsWidgetInstanceEntry::szName, and _OptionsWidgetInstanceEntry::szNameNoLocale.
OptionsInstanceManager::~OptionsInstanceManager () [virtual]
References m_pInstanceTree.
Member Function Documentation
void OptionsInstanceManager::cleanup (KviModule *)
References deleteInstanceTree(), and m_pInstanceTree.
Referenced by options_module_cleanup().
void OptionsInstanceManager::deleteInstanceTree (KviPointerList< OptionsWidgetInstanceEntry > * pList) [protected]
References KviPointerList< T >::first(), KviPointerList< T >::next(), and widgetDestroyed().
Referenced by cleanup().
OptionsWidgetInstanceEntry * OptionsInstanceManager::findInstanceEntry (const char * pcName)
References m_pInstanceTree.
Referenced by findInstanceEntry(), options_kvs_cmd_edit(), OptionsWidgetContainer::setup(), and widgetDestroyed().
OptionsWidgetInstanceEntry * OptionsInstanceManager::findInstanceEntry (const char * pcName, KviPointerList< OptionsWidgetInstanceEntry > * pList) [protected]
References findInstanceEntry(), KviPointerList< T >::first(), kvi_strEqualCI(), and KviPointerList< T >::next().
OptionsWidgetInstanceEntry * OptionsInstanceManager::findInstanceEntry (const QObject * pObj, KviPointerList< OptionsWidgetInstanceEntry > * pList) [protected]
References findInstanceEntry(), KviPointerList< T >::first(), and KviPointerList< T >::next().
KviOptionsWidget * OptionsInstanceManager::getInstance (OptionsWidgetInstanceEntry * pEntry, QWidget * pPar)
References KviOptionsWidget::addOptionsWidget(), _OptionsWidgetInstanceEntry::bIsContainer, connect(), _OptionsWidgetInstanceEntry::createProc, KviOptionsWidget::createTabbedPage(), KviPointerList< T >::first(), g_iOptionWidgetInstances, g_pIconManager, KviIconManager::getSmallIcon(), KviPointerList< T >::insert(), _OptionsWidgetInstanceEntry::iPriority, KviPointerList< T >::last(), KviPointerList< T >::next(), NULL, _OptionsWidgetInstanceEntry::pChildList, KviPointerList< T >::prev(), _OptionsWidgetInstanceEntry::pWidget, KviPointerList< T >::setAutoDelete(), KviOptionsWidget::tabWidget(), and widgetDestroyed().
Referenced by OptionsDialog::fillTreeWidget(), options_kvs_cmd_edit(), OptionsDialog::recursiveSearch(), and OptionsDialog::treeWidgetItemSelectionChanged().
KviPointerList<OptionsWidgetInstanceEntry>* OptionsInstanceManager::instanceEntryTree () [inline]
References m_pInstanceTree.
Referenced by options_kvs_cmd_pages(), and OptionsDialog::OptionsDialog().
void OptionsInstanceManager::widgetDestroyed () [protected, slot]
References findInstanceEntry(), g_iOptionWidgetInstances, m_pInstanceTree, and _OptionsWidgetInstanceEntry::pWidget.
Referenced by deleteInstanceTree(), and getInstance().
Member Data Documentation
KviPointerList<OptionsWidgetInstanceEntry>* OptionsInstanceManager::m_pInstanceTree [protected]
Referenced by cleanup(), findInstanceEntry(), instanceEntryTree(), OptionsInstanceManager(), widgetDestroyed(), and ~OptionsInstanceManager().
The documentation for this class was generated from the following files:
src/modules/options/OptionsInstanceManager.h
src/modules/options/OptionsInstanceManager.cpp