KVIrc: KviIrcConnectionNetsplitDetectorData Class Reference
KviIrcConnectionNetsplitDetectorData Class Reference
#include <kvi_ircconnectionnetsplitdetectordata.h>
Public Member Functions
KviIrcConnectionNetsplitDetectorData ()
const QString & lastNetsplitOnQuitReason ()
kvi_time_t lastNetsplitOnQuitTime ()
void setLastNetsplitOnQuitReason (const QString &szReason)
void setLastNetsplitOnQuitTime (kvi_time_t t)
~KviIrcConnectionNetsplitDetectorData ()
Protected Attributes
QString m_szLastNetsplitOnQuitReason
kvi_time_t m_tLastNetsplitOnQuit
Constructor & Destructor Documentation
KviIrcConnectionNetsplitDetectorData::KviIrcConnectionNetsplitDetectorData ()
References m_tLastNetsplitOnQuit.
KviIrcConnectionNetsplitDetectorData::~KviIrcConnectionNetsplitDetectorData ()
Member Function Documentation
const QString& KviIrcConnectionNetsplitDetectorData::lastNetsplitOnQuitReason () [inline]
Referenced by KviServerParser::parseLiteralQuit().
kvi_time_t KviIrcConnectionNetsplitDetectorData::lastNetsplitOnQuitTime () [inline]
Referenced by KviServerParser::parseLiteralQuit().
void KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitReason (const QString & szReason) [inline]
Referenced by KviServerParser::parseLiteralQuit().
void KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitTime (kvi_time_t t) [inline]
Referenced by KviServerParser::parseLiteralQuit().
Member Data Documentation
QString KviIrcConnectionNetsplitDetectorData::m_szLastNetsplitOnQuitReason [protected]
kvi_time_t KviIrcConnectionNetsplitDetectorData::m_tLastNetsplitOnQuit [protected]
Referenced by KviIrcConnectionNetsplitDetectorData().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnectionnetsplitdetectordata.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnectionnetsplitdetectordata.cpp