KVIrc: KviRegisteredUserGroup Class Reference
KviRegisteredUserGroup Class Reference
#include <KviRegisteredUserGroup.h>
Public Member Functions
KviRegisteredUserGroup (const QString &szName)
const QString & name ()
void setName (const QString &szName)
~KviRegisteredUserGroup ()
Private Attributes
QString m_szName
Friends
class KviRegisteredUserDataBase
Constructor & Destructor Documentation
KviRegisteredUserGroup::KviRegisteredUserGroup (const QString & szName)
References setName().
KviRegisteredUserGroup::~KviRegisteredUserGroup ()
Member Function Documentation
const QString& KviRegisteredUserGroup::name () [inline]
Referenced by KviRegisteredUserDataBase::addGroup(), RegisteredUsersDialog::editGroup(), RegisteredUsersGroupItem::RegisteredUsersGroupItem(), and KviRegisteredUserDataBase::save().
void KviRegisteredUserGroup::setName (const QString & szName) [inline]
Referenced by RegisteredUsersDialog::editGroup(), and KviRegisteredUserGroup().
Friends And Related Function Documentation
friend class KviRegisteredUserDataBase [friend]
Member Data Documentation
QString KviRegisteredUserGroup::m_szName [private]
The documentation for this class was generated from the following files:
src/kvilib/ext/KviRegisteredUserGroup.h
src/kvilib/ext/KviRegisteredUserGroup.cpp