KVIrc: AvatarDownloadDialog Class Reference
AvatarDownloadDialog Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
AvatarDownloadDialog (QWidget *par, const QString &szUrl)
~AvatarDownloadDialog ()
Protected Slots
void cancelClicked ()
void downloadMessage (const QString &szMsg)
void downloadTerminated (bool bSuccess)
void startDownload ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
const QString & errorMessage ()
const QString & localFileName ()
Protected Attributes
QLabel * m_pOutput
KviHttpRequest * m_pRequest
QString m_szErrorMessage
QString m_szLocalFileName
QString m_szUrl
Friends
class OptionsWidget_identityAvatar
Constructor & Destructor Documentation
AvatarDownloadDialog::AvatarDownloadDialog (QWidget * par, const QString & szUrl)
References __tr2qs_ctx(), cancelClicked(), connect(), g, m_pOutput, m_pRequest, m_szUrl, startDownload(), and szUrl.
AvatarDownloadDialog::~AvatarDownloadDialog ()
References m_pRequest.
Member Function Documentation
void AvatarDownloadDialog::cancelClicked () [protected, slot]
References __tr2qs_ctx(), and m_szErrorMessage.
Referenced by AvatarDownloadDialog().
void AvatarDownloadDialog::closeEvent (QCloseEvent * e) [protected, virtual]
References __tr2qs_ctx(), and m_szErrorMessage.
void AvatarDownloadDialog::downloadMessage (const QString & szMsg) [protected, slot]
References m_pOutput.
Referenced by startDownload().
void AvatarDownloadDialog::downloadTerminated (bool bSuccess) [protected, slot]
References KviHttpRequest::lastError(), m_pRequest, and m_szErrorMessage.
Referenced by startDownload().
const QString& AvatarDownloadDialog::errorMessage () [inline, protected]
References m_szErrorMessage.
Referenced by OptionsWidget_identityAvatar::chooseAvatar().
const QString& AvatarDownloadDialog::localFileName () [inline, protected]
References m_szLocalFileName.
Referenced by OptionsWidget_identityAvatar::chooseAvatar().
void AvatarDownloadDialog::startDownload () [protected, slot]
References __tr2qs_ctx(), KviApplication::Avatars, connect(), downloadMessage(), downloadTerminated(), g_pApp, g_pIconManager, KviHttpRequest::get(), KviApplication::getLocalKvircDirectory(), m_pRequest, m_szErrorMessage, m_szLocalFileName, m_szUrl, KviHttpRequest::RenameExisting, KviHttpRequest::setExistingFileAction(), KviHttpRequest::StoreToFile, and KviIconManager::urlToCachedFileName().
Referenced by AvatarDownloadDialog().
Friends And Related Function Documentation
friend class OptionsWidget_identityAvatar [friend]
Member Data Documentation
QLabel* AvatarDownloadDialog::m_pOutput [protected]
Referenced by AvatarDownloadDialog(), and downloadMessage().
KviHttpRequest* AvatarDownloadDialog::m_pRequest [protected]
Referenced by AvatarDownloadDialog(), downloadTerminated(), startDownload(), and ~AvatarDownloadDialog().
QString AvatarDownloadDialog::m_szErrorMessage [protected]
Referenced by cancelClicked(), closeEvent(), downloadTerminated(), errorMessage(), and startDownload().
QString AvatarDownloadDialog::m_szLocalFileName [protected]
Referenced by localFileName(), and startDownload().
QString AvatarDownloadDialog::m_szUrl [protected]
Referenced by AvatarDownloadDialog(), and startDownload().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp