KVIrc: LogFile Class Reference
LogFile Class Reference
The LogFile class which handle any log file.
#include <LogFile.h>
Public Types
enum ExportType { PlainText, HTML }
Holds the type of the exported log file.
enum Type {
Channel = 0, Console = 1, Query = 2, DccChat = 3,
Other = 4
}
Holds the type of the log file.
Public Member Functions
const QDate & date () const
Returns the date of the log.
const QString & fileName () const
Returns the filename of the log.
void getText (QString &szText)
Returns the text of the log file.
LogFile (const QString &szName)
Constructs the log file object.
const QString & name () const
Returns the name of the log.
const QString & network () const
Returns the network of the log.
Type type () const
Returns the type of the log.
const QString & typeString () const
Returns the type of the log.
Private Attributes
bool m_bCompressed
QDate m_date
Type m_eType
QString m_szFilename
QString m_szName
QString m_szNetwork
QString m_szType
Detailed Description
The LogFile class which handle any log file.
Log is in the format: $type_$nick.$network_$YYYY.$MM.$DD.log Examples: query_noldor.azzurra_2009.05.20.log channel_::slackware.azzurra_2009.11.03.log
Member Enumeration Documentation
enum LogFile::ExportType
Holds the type of the exported log file.
Enumerator:
PlainText
export log in plain text file
HTML
export log in a HTML archive
enum LogFile::Type
Holds the type of the log file.
Enumerator:
Channel
the log file of a channel
Console
the log file of a console
Query
the log file of a query
DccChat
the log file of a dcc chat
Other
any other log file
Constructor & Destructor Documentation
LogFile::LogFile (const QString & szName)
Constructs the log file object.
Parameters:
szName The name of the log
Returns:
LogFile
References Channel, Console, KviCString::cutToFirst(), DccChat, KviQString::equalCI(), KviStringConversion::fromString(), KviCString::hexDecode(), KVI_OPTION_UINT, KVI_PATH_SEPARATOR_CHAR, KviOption_uintOutputDatetimeFormat, m_bCompressed, m_date, m_eType, m_szFilename, m_szName, m_szNetwork, m_szType, Other, KviCString::ptr(), and Query.
Member Function Documentation
const QDate& LogFile::date () const [inline]
Returns the date of the log.
Returns:
const QDate &
References m_date.
Referenced by LogViewWindow::createLog(), LogViewWindow::filterNext(), LogListViewLog::LogListViewLog(), and LogListViewLog::operator<().
const QString& LogFile::fileName () const [inline]
Returns the filename of the log.
Returns:
const QString &
References m_szFilename.
Referenced by LogViewWindow::createLog(), LogListViewLog::fileName(), and getText().
void LogFile::getText (QString & szText)
Returns the text of the log file.
Parameters:
szText The buffer where to save the contents of the log
Returns:
void
References fileName(), and m_bCompressed.
Referenced by LogViewWindow::filterNext().
const QString& LogFile::name () const [inline]
Returns the name of the log.
Returns:
const QString &
References m_szName.
Referenced by LogViewWindow::createLog(), LogViewWindow::filterNext(), and LogListViewItem::LogListViewItem().
const QString& LogFile::network () const [inline]
Returns the network of the log.
Returns:
const QString &
References m_szNetwork.
Referenced by LogViewWindow::createLog(), and LogViewWindow::filterNext().
Type LogFile::type () const [inline]
Returns the type of the log.
Returns:
Type
References m_eType.
Referenced by LogViewWindow::createLog(), and LogViewWindow::filterNext().
const QString& LogFile::typeString () const [inline]
Returns the type of the log.
Returns:
const QString &
References m_szType.
Referenced by LogViewWindow::createLog().
Member Data Documentation
bool LogFile::m_bCompressed [private]
Referenced by getText(), and LogFile().
QDate LogFile::m_date [private]
Referenced by date(), and LogFile().
Type LogFile::m_eType [private]
Referenced by LogFile(), and type().
QString LogFile::m_szFilename [private]
Referenced by fileName(), and LogFile().
QString LogFile::m_szName [private]
Referenced by LogFile(), and name().
QString LogFile::m_szNetwork [private]
Referenced by LogFile(), and network().
QString LogFile::m_szType [private]
Referenced by LogFile(), and typeString().
The documentation for this class was generated from the following files:
src/modules/logview/LogFile.h
src/modules/logview/LogFile.cpp