KVIrc: OptionsWidget_textEncoding Class Reference
OptionsWidget_textEncoding Class Reference
#include <OptionsWidget_textEncoding.h>
Public Member Functions
virtual void commit ()
OptionsWidget_textEncoding (QWidget *parent)
~OptionsWidget_textEncoding ()
Public Member Functions inherited from KviOptionsWidget
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
QPushButton * addPushButton (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Attributes
QComboBox * m_pForcedLocaleCombo
QTableWidget * m_pSpellCheckerDictionaries
QComboBox * m_pSrvEncodingCombo
QComboBox * m_pTextEncodingCombo
QString m_szLanguage
Additional Inherited Members
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_textEncoding::OptionsWidget_textEncoding (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviKvsVariant::asString(), KviOptionsWidget::createLayout(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, KviKvsHash::dict(), KviLocale::encodingDescription(), KviQString::equalCI(), KviKvsScript::evaluate(), KviFileUtils::fileExists(), g_pApp, g_szPrevSetLocale, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviKvsVariant::hash(), i, KviLocale::instance(), KVI_FORCE_LOCALE_FILE_NAME, KVI_OPTION_STRING, KVI_OPTION_STRINGLIST, KviOption_stringDefaultSrvEncoding, KviOption_stringDefaultTextEncoding, KviOption_stringlistSpellCheckerDictionaries, KviApplication::Locale, KviLocale::localeName(), m_pForcedLocaleCombo, m_pSpellCheckerDictionaries, m_pSrvEncodingCombo, m_pTextEncodingCombo, m_szLanguage, KviPointerHashTableIterator< Key, T >::moveFirst(), KviPointerHashTableIterator< Key, T >::moveNext(), KviApplication::None, KviLocale::_EncodingDescription::pcName, and KviTalGroupBox::setLayout().
OptionsWidget_textEncoding::~OptionsWidget_textEncoding () default
Member Function Documentation
void OptionsWidget_textEncoding::commit (void) virtual
Reimplemented from KviOptionsWidget.
References __tr2qs_ctx(), KviFileUtils::fileExists(), g_pApp, g_szPrevSetLocale, KviApplication::getLocalKvircDirectory(), i, KVI_FORCE_LOCALE_FILE_NAME, KVI_OPTION_STRING, KVI_OPTION_STRINGLIST, KviOption_stringDefaultSrvEncoding, KviOption_stringDefaultTextEncoding, KviOption_stringlistSpellCheckerDictionaries, m_pForcedLocaleCombo, m_pSpellCheckerDictionaries, m_pSrvEncodingCombo, m_pTextEncodingCombo, KviApplication::None, KviFileUtils::removeFile(), KviKvsScript::run(), and KviFileUtils::writeFile().
Member Data Documentation
QComboBox* OptionsWidget_textEncoding::m_pForcedLocaleCombo protected
Referenced by commit(), and OptionsWidget_textEncoding().
QTableWidget* OptionsWidget_textEncoding::m_pSpellCheckerDictionaries protected
Referenced by commit(), and OptionsWidget_textEncoding().
QComboBox* OptionsWidget_textEncoding::m_pSrvEncodingCombo protected
Referenced by commit(), and OptionsWidget_textEncoding().
QComboBox* OptionsWidget_textEncoding::m_pTextEncodingCombo protected
Referenced by commit(), and OptionsWidget_textEncoding().
QString OptionsWidget_textEncoding::m_szLanguage protected
Referenced by OptionsWidget_textEncoding().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_textEncoding.h
src/modules/options/OptionsWidget_textEncoding.cpp