KVIrc: OptionsWidget_notifierLook Class Reference
OptionsWidget_notifierLook Class Reference
#include <OptionsWidget_notifier.h>
Public Member Functions
virtual void commit ()
OptionsWidget_notifierLook (QWidget *parent)
~OptionsWidget_notifierLook ()
Private Attributes
QComboBox * m_pHorizontalAlign
QComboBox * m_pVerticalAlign
Constructor & Destructor Documentation
OptionsWidget_notifierLook::OptionsWidget_notifierLook (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addLabel(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), KVI_OPTION_UINT, KviOption_colorNotifierBackground, KviOption_colorNotifierForeground, KviOption_colorNotifierTitleForeground, KviOption_fontNotifier, KviOption_fontNotifierTitle, KviOption_pixmapNotifierBackground, KviOption_uintNotifierPixmapAlign, KviOptionsWidget::layout(), m_pHorizontalAlign, and m_pVerticalAlign.
OptionsWidget_notifierLook::~OptionsWidget_notifierLook ()
Member Function Documentation
void OptionsWidget_notifierLook::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintNotifierPixmapAlign, m_pHorizontalAlign, and m_pVerticalAlign.
Member Data Documentation
QComboBox* OptionsWidget_notifierLook::m_pHorizontalAlign [private]
Referenced by commit(), and OptionsWidget_notifierLook().
QComboBox* OptionsWidget_notifierLook::m_pVerticalAlign [private]
Referenced by commit(), and OptionsWidget_notifierLook().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_notifier.h
src/modules/options/OptionsWidget_notifier.cpp