KVIrc: KvsObject_socket Class Reference
KvsObject_socket Class Reference
#include <KvsObject_socket.h>
Protected Slots
void slotConnected ()
void slotDisconnected ()
void slotError (QAbstractSocket::SocketError socketError)
void slotHostFound ()
void slotNewConnection ()
void slotReadyRead ()
void slotStateChanged (QAbstractSocket::SocketState socketState)
Protected Member Functions
bool bytesAvailable (KviKvsObjectFunctionCall *c)
bool close (KviKvsObjectFunctionCall *c)
bool connectedEvent (KviKvsObjectFunctionCall *c)
bool dataAvailableEvent (KviKvsObjectFunctionCall *c)
bool disconnectedEvent (KviKvsObjectFunctionCall *c)
bool errorEvent (KviKvsObjectFunctionCall *c)
bool functionConnect (KviKvsObjectFunctionCall *c)
const char * getStateString (QAbstractSocket::SocketState)
bool hostFoundEvent (KviKvsObjectFunctionCall *c)
bool incomingConnectionEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool listen (KviKvsObjectFunctionCall *c)
bool localIp (KviKvsObjectFunctionCall *c)
bool localPort (KviKvsObjectFunctionCall *c)
void makeConnections ()
bool read (KviKvsObjectFunctionCall *c)
bool remoteIp (KviKvsObjectFunctionCall *c)
bool remotePort (KviKvsObjectFunctionCall *c)
void setInternalSocket (QAbstractSocket *pSocket)
bool setProtocol (KviKvsObjectFunctionCall *c)
bool stateChangedEvent (KviKvsObjectFunctionCall *c)
bool status (KviKvsObjectFunctionCall *c)
bool write (KviKvsObjectFunctionCall *c)
Protected Attributes
KviKvsRunTimeContext * m_pContext
QTcpServer * m_pServer
QAbstractSocket * m_pSocket
Member Function Documentation
bool KvsObject_socket::bytesAvailable (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::close (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::connectedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::dataAvailableEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::disconnectedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::errorEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::functionConnect (KviKvsObjectFunctionCall * c) [protected]
const char * KvsObject_socket::getStateString (QAbstractSocket::SocketState state) [protected]
References sockstate_tbl.
Referenced by slotStateChanged().
bool KvsObject_socket::hostFoundEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::incomingConnectionEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KviKvsObject.
References c, m_pServer, and m_pSocket.
bool KvsObject_socket::listen (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::localIp (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::localPort (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_socket::makeConnections () [protected]
References connect(), m_pSocket, slotConnected(), slotDisconnected(), slotError(), slotHostFound(), slotReadyRead(), and slotStateChanged().
bool KvsObject_socket::read (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::remoteIp (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::remotePort (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_socket::setInternalSocket (QAbstractSocket * pSocket) [inline, protected]
References m_pSocket.
bool KvsObject_socket::setProtocol (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_socket::slotConnected () [protected, slot]
References KviKvsObject::callFunction().
Referenced by makeConnections().
void KvsObject_socket::slotDisconnected () [protected, slot]
References KviKvsObject::callFunction().
Referenced by makeConnections().
void KvsObject_socket::slotError (QAbstractSocket::SocketError socketError) [protected, slot]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), and sockerrors_tbl.
Referenced by makeConnections().
void KvsObject_socket::slotHostFound () [protected, slot]
References KviKvsObject::callFunction().
Referenced by makeConnections().
void KvsObject_socket::slotNewConnection () [protected, slot]
References KviKvsObjectClass::allocateInstance(), KviKvsObject::callFunction(), KviKvsObject::dieNow(), KviKvsObject::handle(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), KviKvsObjectController::lookupObject(), m_pContext, m_pServer, and KviKvsKernel::objectController().
void KvsObject_socket::slotReadyRead () [protected, slot]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), and m_pSocket.
Referenced by makeConnections().
void KvsObject_socket::slotStateChanged (QAbstractSocket::SocketState socketState) [protected, slot]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), and getStateString().
Referenced by makeConnections().
bool KvsObject_socket::stateChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::status (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_socket::write (KviKvsObjectFunctionCall * c) [protected]
Member Data Documentation
KviKvsRunTimeContext* KvsObject_socket::m_pContext [protected]
Referenced by slotNewConnection().
QTcpServer* KvsObject_socket::m_pServer [protected]
Referenced by slotNewConnection().
QAbstractSocket* KvsObject_socket::m_pSocket [protected]
Referenced by makeConnections(), setInternalSocket(), and slotReadyRead().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_socket.h
src/modules/objects/KvsObject_socket.cpp