KVIrc: KviIsOnNotifyListManager Class Reference
KviIsOnNotifyListManager Class Reference
#include <KviNotifyList.h>
Protected Member Functions
virtual bool handleIsOn (KviIrcMessage *msg)
virtual bool handleUserhost (KviIrcMessage *msg)
KviIsOnNotifyListManager (KviIrcConnection *pConnection)
virtual void start ()
virtual void stop ()
~KviIsOnNotifyListManager ()
Protected Member Functions inherited from KviNotifyListManager
virtual bool handleWatchReply (KviIrcMessage *msg)
KviNotifyListManager (KviIrcConnection *pConnection)
void notifyOffLine (const QString &nick, const QString &user=QString(), const QString &host=QString(), const QString &szReason=QString())
void notifyOnLine (const QString &nick, const QString &user=QString(), const QString &host=QString(), const QString &szReason=QString(), bool bJoin=true)
~KviNotifyListManager ()
Private Slots
void buildIsOnList ()
void buildNotifyList ()
void buildRegUserDict ()
void buildUserhostList ()
bool doMatchUser (const QString &notifyString, const KviIrcMask &mask)
void newIsOnSession ()
void newNotifySession ()
void newUserhostSession ()
void sendIsOn ()
void sendUserhost ()
Private Member Functions
void delayedIsOnSession ()
void delayedNotifySession ()
void delayedUserhostSession ()
Private Attributes
bool m_bExpectingIsOn
bool m_bExpectingUserhost
bool m_bRunning
QTimer * m_pDelayedIsOnTimer
QTimer * m_pDelayedNotifyTimer
QTimer * m_pDelayedUserhostTimer
KviPointerList< QString > * m_pIsOnList
KviPointerList< QString > * m_pNotifyList
KviPointerList< QString > * m_pOnlineList
KviPointerHashTable< QString,
QString > * m_pRegUserDict
KviPointerList< QString > * m_pUserhostList
QString m_szIsOnString
QString m_szUserhostString
Friends
class KviConsoleWindow
class KviIrcConnection
class KviIrcServerParser
Additional Inherited Members
Public Member Functions inherited from KviNotifyListManager
KviConsoleWindow * console ()
Protected Attributes inherited from KviNotifyListManager
KviIrcConnection * m_pConnection
KviConsoleWindow * m_pConsole
Constructor & Destructor Documentation
KviIsOnNotifyListManager::KviIsOnNotifyListManager (KviIrcConnection * pConnection) protected
References connect(), m_bRunning, m_pDelayedIsOnTimer, m_pDelayedNotifyTimer, m_pDelayedUserhostTimer, m_pIsOnList, m_pNotifyList, m_pOnlineList, m_pRegUserDict, m_pUserhostList, newIsOnSession(), newNotifySession(), newUserhostSession(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviPointerList< T >::setAutoDelete().
KviIsOnNotifyListManager::~KviIsOnNotifyListManager () protected
References m_bRunning, m_pDelayedIsOnTimer, m_pDelayedNotifyTimer, m_pDelayedUserhostTimer, m_pIsOnList, m_pNotifyList, m_pOnlineList, m_pRegUserDict, m_pUserhostList, and stop().
Member Function Documentation
void KviIsOnNotifyListManager::buildIsOnList () private slot
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerList< T >::first(), m_pIsOnList, m_pNotifyList, m_szIsOnString, KviPointerList< T >::removeFirst(), s, and KviPointerList< T >::setAutoDelete().
Referenced by newIsOnSession().
void KviIsOnNotifyListManager::buildNotifyList () private slot
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pNotifyList, and m_pRegUserDict.
Referenced by newNotifySession().
void KviIsOnNotifyListManager::buildRegUserDict () private slot
References KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), d, g_pRegisteredUserDataBase, m_pRegUserDict, KviPointerHashTable< Key, T >::replace(), u, and KviRegisteredUserDataBase::userDict().
Referenced by start().
void KviIsOnNotifyListManager::buildUserhostList () private slot
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerList< T >::first(), i, m_pOnlineList, m_pUserhostList, m_szUserhostString, MAX_USERHOST_ENTRIES, KviPointerList< T >::removeFirst(), s, and KviPointerList< T >::setAutoDelete().
Referenced by newUserhostSession().
void KviIsOnNotifyListManager::delayedIsOnSession () private
References __tr2qs, _OUTPUT_VERBOSE, KVI_OPTION_UINT, KVI_OUT_SYSTEMWARNING, KviOption_uintNotifyListIsOnDelayTimeInSecs, KviNotifyListManager::m_pConsole, m_pDelayedIsOnTimer, and KviWindow::output().
Referenced by handleIsOn(), handleUserhost(), and newUserhostSession().
void KviIsOnNotifyListManager::delayedNotifySession () private
References __tr2qs, _OUTPUT_VERBOSE, KVI_OPTION_UINT, KVI_OUT_SYSTEMWARNING, KviOption_uintNotifyListCheckTimeInSecs, KviNotifyListManager::m_pConsole, m_pDelayedNotifyTimer, and KviWindow::output().
Referenced by handleIsOn(), handleUserhost(), newIsOnSession(), and newUserhostSession().
void KviIsOnNotifyListManager::delayedUserhostSession () private
References __tr2qs, _OUTPUT_VERBOSE, KVI_OPTION_UINT, KVI_OUT_SYSTEMWARNING, KviOption_uintNotifyListUserhostDelayTimeInSecs, KviNotifyListManager::m_pConsole, m_pDelayedUserhostTimer, and KviWindow::output().
Referenced by handleIsOn(), handleUserhost(), and newUserhostSession().
bool KviIsOnNotifyListManager::doMatchUser (const QString & notifyString, const KviIrcMask & mask) private slot
References __tr2qs, _OUTPUT_VERBOSE, KviPointerHashTable< Key, T >::find(), KviUserListView::findEntry(), KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviIrcMask::host(), KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviNotifyListManager::m_pConsole, m_pRegUserDict, KviIrcMask::nick(), KviConsoleWindow::notifyListView(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviWindow::output(), start(), stop(), u, and KviIrcMask::user().
Referenced by handleIsOn(), and handleUserhost().
bool KviIsOnNotifyListManager::handleIsOn (KviIrcMessage * msg) protected virtual
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, KviPointerList< T >::append(), KviIrcConnection::channelList(), KviPointerList< T >::clear(), KviWindow::connection(), KviNotifyListManager::console(), KviIrcConnection::decodeText(), delayedIsOnSession(), delayedNotifySession(), delayedUserhostSession(), doMatchUser(), KviQString::equalCI(), KviIrcUserDataBase::find(), KviUserListView::findEntry(), KviPointerList< T >::first(), KviCString::hasData(), KviPointerList< T >::isEmpty(), kvi_extractToken(), KVI_OPTION_BOOL, KVI_OUT_SYSTEMMESSAGE, KviOption_boolNotifyListSendUserhostForOnlineUsers, l, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), m_bExpectingIsOn, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pIsOnList, m_pNotifyList, m_pOnlineList, KviPointerList< T >::next(), KviConsoleWindow::notifyListView(), KviNotifyListManager::notifyOffLine(), KviWindow::output(), KviCString::ptr(), KviPointerList< T >::removeFirst(), KviPointerList< T >::removeRef(), s, KviPointerList< T >::setAutoDelete(), KviIrcMessage::trailing(), and KviIrcConnection::userDataBase().
bool KviIsOnNotifyListManager::handleUserhost (KviIrcMessage * msg) protected virtual
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, KviPointerList< T >::append(), KviCString::cutLeft(), KviCString::cutRight(), KviIrcConnection::decodeText(), delayedIsOnSession(), delayedNotifySession(), delayedUserhostSession(), doMatchUser(), KviQString::equalCI(), KviCString::findFirstIdx(), KviPointerList< T >::first(), KviCString::firstCharIs(), KviCString::hasData(), KviPointerList< T >::isEmpty(), kvi_extractToken(), KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), KviCString::lastCharIs(), KviCString::left(), m_bExpectingUserhost, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pNotifyList, m_pOnlineList, m_pUserhostList, KviPointerList< T >::next(), KviWindow::output(), KviCString::ptr(), KviPointerList< T >::removeFirst(), KviPointerList< T >::removeRef(), s, KviPointerList< T >::setAutoDelete(), szHost, and KviIrcMessage::trailing().
void KviIsOnNotifyListManager::newIsOnSession () private slot
References buildIsOnList(), delayedNotifySession(), KviPointerList< T >::isEmpty(), m_pIsOnList, and sendIsOn().
Referenced by KviIsOnNotifyListManager(), and newNotifySession().
void KviIsOnNotifyListManager::newNotifySession () private slot
References __tr2qs, _OUTPUT_VERBOSE, buildNotifyList(), KviPointerList< T >::isEmpty(), KVI_OUT_SYSTEMMESSAGE, KviNotifyListManager::m_pConsole, m_pNotifyList, newIsOnSession(), KviWindow::output(), and stop().
Referenced by KviIsOnNotifyListManager(), and start().
void KviIsOnNotifyListManager::newUserhostSession () private slot
References __tr2qs, buildUserhostList(), delayedIsOnSession(), delayedNotifySession(), delayedUserhostSession(), KviPointerList< T >::isEmpty(), KVI_OUT_SYSTEMWARNING, KviNotifyListManager::m_pConsole, m_pNotifyList, m_pOnlineList, m_pUserhostList, KviWindow::output(), and sendUserhost().
Referenced by KviIsOnNotifyListManager().
void KviIsOnNotifyListManager::sendIsOn () private slot
References __tr2qs, _OUTPUT_PARANOIC, KviIrcConnection::encodeText(), KVI_OUT_SYSTEMMESSAGE, KviLagMeter::lagCheckRegister(), KviIrcConnection::lagMeter(), m_bExpectingIsOn, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_szIsOnString, KviWindow::output(), and KviIrcConnection::sendFmtData().
Referenced by newIsOnSession().
void KviIsOnNotifyListManager::sendUserhost () private slot
References __tr2qs, _OUTPUT_PARANOIC, KviIrcConnection::encodeText(), KVI_OUT_SYSTEMMESSAGE, KviLagMeter::lagCheckRegister(), KviIrcConnection::lagMeter(), m_bExpectingUserhost, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_szUserhostString, KviWindow::output(), and KviIrcConnection::sendFmtData().
Referenced by newUserhostSession().
void KviIsOnNotifyListManager::start () protected virtual
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, buildRegUserDict(), KviIrcConnection::currentNickName(), KviPointerHashTable< Key, T >::isEmpty(), KVI_OUT_SYSTEMMESSAGE, m_bExpectingIsOn, m_bExpectingUserhost, m_bRunning, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pRegUserDict, newNotifySession(), KviConsoleWindow::notifyListView(), KviWindow::output(), KviUserListView::partAllButOne(), and stop().
Referenced by doMatchUser().
void KviIsOnNotifyListManager::stop () protected virtual
Reimplemented from KviNotifyListManager.
References KviPointerHashTable< Key, T >::clear(), KviPointerList< T >::clear(), KviIrcConnection::currentNickName(), KviLagMeter::lagCheckAbort(), KviIrcConnection::lagMeter(), m_bRunning, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pDelayedIsOnTimer, m_pDelayedNotifyTimer, m_pDelayedUserhostTimer, m_pIsOnList, m_pNotifyList, m_pOnlineList, m_pRegUserDict, m_pUserhostList, m_szIsOnString, m_szUserhostString, KviConsoleWindow::notifyListView(), and KviUserListView::partAllButOne().
Referenced by doMatchUser(), newNotifySession(), start(), and ~KviIsOnNotifyListManager().
Friends And Related Function Documentation
friend class KviConsoleWindow friend
friend class KviIrcConnection friend
friend class KviIrcServerParser friend
Member Data Documentation
bool KviIsOnNotifyListManager::m_bExpectingIsOn private
Referenced by handleIsOn(), sendIsOn(), and start().
bool KviIsOnNotifyListManager::m_bExpectingUserhost private
Referenced by handleUserhost(), sendUserhost(), and start().
bool KviIsOnNotifyListManager::m_bRunning private
Referenced by KviIsOnNotifyListManager(), start(), stop(), and ~KviIsOnNotifyListManager().
QTimer* KviIsOnNotifyListManager::m_pDelayedIsOnTimer private
Referenced by delayedIsOnSession(), KviIsOnNotifyListManager(), stop(), and ~KviIsOnNotifyListManager().
QTimer* KviIsOnNotifyListManager::m_pDelayedNotifyTimer private
Referenced by delayedNotifySession(), KviIsOnNotifyListManager(), stop(), and ~KviIsOnNotifyListManager().
QTimer* KviIsOnNotifyListManager::m_pDelayedUserhostTimer private
Referenced by delayedUserhostSession(), KviIsOnNotifyListManager(), stop(), and ~KviIsOnNotifyListManager().
KviPointerList<QString>* KviIsOnNotifyListManager::m_pIsOnList private
Referenced by buildIsOnList(), handleIsOn(), KviIsOnNotifyListManager(), newIsOnSession(), stop(), and ~KviIsOnNotifyListManager().
KviPointerList<QString>* KviIsOnNotifyListManager::m_pNotifyList private
Referenced by buildIsOnList(), buildNotifyList(), handleIsOn(), handleUserhost(), KviIsOnNotifyListManager(), newNotifySession(), newUserhostSession(), stop(), and ~KviIsOnNotifyListManager().
KviPointerList<QString>* KviIsOnNotifyListManager::m_pOnlineList private
Referenced by buildUserhostList(), handleIsOn(), handleUserhost(), KviIsOnNotifyListManager(), newUserhostSession(), stop(), and ~KviIsOnNotifyListManager().
KviPointerHashTable<QString,QString>* KviIsOnNotifyListManager::m_pRegUserDict private
Referenced by buildNotifyList(), buildRegUserDict(), doMatchUser(), KviIsOnNotifyListManager(), start(), stop(), and ~KviIsOnNotifyListManager().
KviPointerList<QString>* KviIsOnNotifyListManager::m_pUserhostList private
Referenced by buildUserhostList(), handleUserhost(), KviIsOnNotifyListManager(), newUserhostSession(), stop(), and ~KviIsOnNotifyListManager().
QString KviIsOnNotifyListManager::m_szIsOnString private
Referenced by buildIsOnList(), sendIsOn(), and stop().
QString KviIsOnNotifyListManager::m_szUserhostString private
Referenced by buildUserhostList(), sendUserhost(), and stop().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviNotifyList.h
src/kvirc/kernel/KviNotifyList.cpp