KVIrc: ActionEditorWindow Class Reference
ActionEditorWindow Class Reference
#include <ActionEditor.h>
Public Member Functions
ActionEditorWindow ()
~ActionEditorWindow ()
Protected Slots
void applyClicked ()
void cancelClicked ()
void okClicked ()
Protected Member Functions
virtual void getConfigGroupName (QString &szName)
virtual void loadProperties (KviConfigurationFile *)
virtual QPixmap * myIconPtr ()
virtual void saveProperties (KviConfigurationFile *)
Protected Attributes
ActionEditor * m_pEditor
Constructor & Destructor Documentation
ActionEditorWindow::ActionEditorWindow ()
References __tr2qs_ctx(), KviIconManager::Accept, applyClicked(), cancelClicked(), connect(), KviIconManager::Discard, g, g_pIconManager, KviIconManager::getSmallIcon(), m_pEditor, okClicked(), and KviWindow::setFixedCaption().
ActionEditorWindow::~ActionEditorWindow ()
Member Function Documentation
void ActionEditorWindow::applyClicked () [protected, slot]
References ActionEditor::commit(), and m_pEditor.
Referenced by ActionEditorWindow().
void ActionEditorWindow::cancelClicked () [protected, slot]
Referenced by ActionEditorWindow().
void ActionEditorWindow::getConfigGroupName (QString & szName) [protected, virtual]
Reimplemented from KviWindow.
void ActionEditorWindow::loadProperties (KviConfigurationFile * cfg) [protected, virtual]
Reimplemented from KviWindow.
References m_pEditor, ActionEditor::m_pSplitter, KviConfigurationFile::readIntListEntry(), and w.
QPixmap * ActionEditorWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::ScriptAction.
void ActionEditorWindow::okClicked () [protected, slot]
References ActionEditor::commit(), and m_pEditor.
Referenced by ActionEditorWindow().
void ActionEditorWindow::saveProperties (KviConfigurationFile * cfg) [protected, virtual]
Reimplemented from KviWindow.
References m_pEditor, ActionEditor::m_pSplitter, and KviConfigurationFile::writeEntry().
Member Data Documentation
ActionEditor* ActionEditorWindow::m_pEditor [protected]
Referenced by ActionEditorWindow(), applyClicked(), loadProperties(), okClicked(), and saveProperties().
The documentation for this class was generated from the following files:
src/modules/actioneditor/ActionEditor.h
src/modules/actioneditor/ActionEditor.cpp