KVIrc: KviIrcConnectionAsyncData< T > Class Template Reference
KviIrcConnectionAsyncData< T > Class Template Reference
#include <KviIrcConnectionAsyncData.h>
Public Member Functions
void add (T *i)
KviIrcConnectionAsyncData ()
T * lookup (const QString &nick)
void remove (T *i)
~KviIrcConnectionAsyncData ()
Protected Attributes
KviPointerList< T > * m_pInfoList
template<class T>
class KviIrcConnectionAsyncData< T >
Constructor & Destructor Documentation
template<class T> KviIrcConnectionAsyncData< T >::KviIrcConnectionAsyncData () [inline]
template<class T> KviIrcConnectionAsyncData< T >::~KviIrcConnectionAsyncData () [inline]
Member Function Documentation
template<class T> void KviIrcConnectionAsyncData< T >::add (T * i) [inline]
template<class T> T* KviIrcConnectionAsyncData< T >::lookup (const QString & nick) [inline]
Referenced by KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), and KviIrcServerParser::parseNumericWhoisUser().
template<class T> void KviIrcConnectionAsyncData< T >::remove (T * i) [inline]
Referenced by KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), and KviIrcServerParser::parseNumericNoSuchServer().
Member Data Documentation
template<class T> KviPointerList<T>* KviIrcConnectionAsyncData< T >::m_pInfoList [protected]
The documentation for this class was generated from the following file:
src/kvirc/kernel/KviIrcConnectionAsyncData.h