KVIrc: KviShortcut Class Reference
KviShortcut Class Reference
#include <KviShortcut.h>
Static Public Member Functions
static QShortcut * create (const char *key, QWidget *parent, const char *member=0, const char *ambiguousMember=0, Qt::ShortcutContext context=Qt::WindowShortcut)
static QShortcut * create (const QKeySequence &key, QWidget *parent, const char *member=0, const char *ambiguousMember=0, Qt::ShortcutContext context=Qt::WindowShortcut)
static void create (QKeySequence::StandardKey key, QWidget *parent, const char *member=0, const char *ambiguousMember=0, Qt::ShortcutContext context=Qt::WindowShortcut, KviPointerList< QShortcut > *pBufferList=NULL)
Private Member Functions
KviShortcut ()
~KviShortcut ()
Constructor & Destructor Documentation
KviShortcut::KviShortcut () private
KviShortcut::~KviShortcut () private
Member Function Documentation
QShortcut * KviShortcut::create (const char * key, QWidget * parent, const char * member = 0, const char * ambiguousMember = 0, Qt::ShortcutContext context = Qt::WindowShortcut) static
Referenced by KviMainWindow::installAccelerators(), KviInput::installShortcuts(), KviInputEditor::installShortcuts(), and KviIrcViewToolWidget::KviIrcViewToolWidget().
QShortcut * KviShortcut::create (const QKeySequence & key, QWidget * parent, const char * member = 0, const char * ambiguousMember = 0, Qt::ShortcutContext context = Qt::WindowShortcut) static
void KviShortcut::create (QKeySequence::StandardKey key, QWidget * parent, const char * member = 0, const char * ambiguousMember = 0, Qt::ShortcutContext context = Qt::WindowShortcut, KviPointerList< QShortcut > * pBufferList = NULL) static
References KviPointerList< T >::append().
The documentation for this class was generated from the following files:
src/kvilib/core/KviShortcut.h
src/kvilib/core/KviShortcut.cpp