KVIrc: DccVideoCodec Class Reference
DccVideoCodec Class Reference
#include <DccVoiceCodec.h>
Public Member Functions
DccVideoCodec ()
virtual void decode (KviDataBuffer *stream, KviDataBuffer *videoSignal, KviDataBuffer *textSignal)
virtual int decodedFrameSize ()
virtual int encodedFrameSize ()
virtual void encodeText (KviDataBuffer *textSignal, KviDataBuffer *stream)
virtual void encodeVideo (KviDataBuffer *videoSignal, KviDataBuffer *stream)
const char * name ()
virtual ~DccVideoCodec ()
Protected Attributes
KviCString m_szName
Constructor & Destructor Documentation
DccVideoCodec::DccVideoCodec ()
DccVideoCodec::~DccVideoCodec () [virtual]
Member Function Documentation
void DccVideoCodec::decode (KviDataBuffer * stream, KviDataBuffer * videoSignal, KviDataBuffer * textSignal) [virtual]
Reimplemented in DccVideoSJpegCodec, and DccVideoTheoraCodec.
Referenced by DccVideoThread::readWriteStep().
int DccVideoCodec::decodedFrameSize () [virtual]
Reimplemented in DccVideoSJpegCodec, and DccVideoTheoraCodec.
int DccVideoCodec::encodedFrameSize () [virtual]
Reimplemented in DccVideoSJpegCodec, and DccVideoTheoraCodec.
void DccVideoCodec::encodeText (KviDataBuffer * textSignal, KviDataBuffer * stream) [virtual]
Reimplemented in DccVideoSJpegCodec, and DccVideoTheoraCodec.
Referenced by DccVideoThread::textStep().
void DccVideoCodec::encodeVideo (KviDataBuffer * videoSignal, KviDataBuffer * stream) [virtual]
Reimplemented in DccVideoSJpegCodec, and DccVideoTheoraCodec.
Referenced by DccVideoThread::videoStep().
const char * DccVideoCodec::name ()
References m_szName, and KviCString::ptr().
Referenced by DccVideoWindow::connected().
Member Data Documentation
KviCString DccVideoCodec::m_szName [protected]
Referenced by DccVideoSJpegCodec::DccVideoSJpegCodec(), DccVideoTheoraCodec::DccVideoTheoraCodec(), and name().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceCodec.h
src/modules/dcc/DccVoiceCodec.cpp