KVIrc: KviTalHBox Class Reference
KviTalHBox Class Reference
Toolkit Abstraction Layer: hbox class.
#include <KviTalHBox.h>
Public Member Functions
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Protected Member Functions
virtual void childEvent (QChildEvent *e)
Private Attributes
QHBoxLayout * m_pLayout
Detailed Description
Toolkit Abstraction Layer: hbox class.
Constructor & Destructor Documentation
KviTalHBox::KviTalHBox (QWidget * pParent, char * pcName = 0)
Constructs an horizontal box object.
Parameters:
pParent The parent object
pcName The name of the box
Returns:
KviTalHBox
References m_pLayout.
KviTalHBox::~KviTalHBox ()
Destroys an horizontal box object.
Member Function Documentation
void KviTalHBox::addSpacing (int iSpace)
Adds a non-stretchable spacing item.
Parameters:
iSpace the width of the item
Returns:
void
References m_pLayout.
Referenced by KviPasswordLineEdit::KviPasswordLineEdit(), and KviPasswordSelector::KviPasswordSelector().
void KviTalHBox::addStretch (int iStretch)
Adds the stretch factor.
Parameters:
iStretch The stretch factor
Returns:
void
References m_pLayout.
void KviTalHBox::childEvent (QChildEvent * e) [protected, virtual]
References m_pLayout.
void KviTalHBox::setAlignment (QWidget * pChild, Qt::Alignment alignment)
Sets the alignment of the box.
Parameters:
pChild The child object to align
alignment The alignment
Returns:
void
References m_pLayout.
void KviTalHBox::setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
Parameters:
alignment The alignment
Returns:
void
References m_pLayout.
Referenced by IdentityProfileEditor::IdentityProfileEditor(), and KviClassEditorFunctionDialog::KviClassEditorFunctionDialog().
void KviTalHBox::setMargin (int iMargin)
Sets the margin of the box.
Parameters:
iMargin The margin in pixels
Returns:
void
References m_pLayout.
Referenced by AddonManagementDialog::AddonManagementDialog(), AliasEditorWidget::AliasEditorWidget(), ClassEditorWidget::ClassEditorWidget(), OptionsWidget_textIcons::currentItemChanged(), DccVoiceWindow::DccVoiceWindow(), OptionsWidget_textIcons::iconSelected(), KviChannelWindow::KviChannelWindow(), KviClassEditorDialog::KviClassEditorDialog(), KviClassEditorFunctionDialog::KviClassEditorFunctionDialog(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), KviInput::KviInput(), KviPasswordLineEdit::KviPasswordLineEdit(), KviPasswordSelector::KviPasswordSelector(), KviTalWizard::KviTalWizard(), ListWindow::ListWindow(), OptionsDialog::OptionsDialog(), SetupWizard::SetupWizard(), and ThemeManagementDialog::ThemeManagementDialog().
void KviTalHBox::setSpacing (int iSpace)
Sets the spacing of the box.
Parameters:
iSpace The space in pixels
Returns:
void
References m_pLayout.
Referenced by AddonManagementDialog::AddonManagementDialog(), AliasEditorWidget::AliasEditorWidget(), AvatarSelectionDialog::AvatarSelectionDialog(), ChannelsJoinDialog::ChannelsJoinDialog(), ClassEditorWidget::ClassEditorWidget(), OptionsWidget_textIcons::currentItemChanged(), DccVoiceWindow::DccVoiceWindow(), OptionsWidget_textIcons::iconSelected(), KviAsyncAvatarSelectionDialog::KviAsyncAvatarSelectionDialog(), KviChannelWindow::KviChannelWindow(), KviClassEditorDialog::KviClassEditorDialog(), KviClassEditorFunctionDialog::KviClassEditorFunctionDialog(), KviColorSelector::KviColorSelector(), KviFontSelector::KviFontSelector(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), KviInput::KviInput(), KviMircTextColorSelector::KviMircTextColorSelector(), KviPasswordLineEdit::KviPasswordLineEdit(), KviPasswordSelector::KviPasswordSelector(), KviStringSelector::KviStringSelector(), KviTalWizard::KviTalWizard(), KviUIntSelector::KviUIntSelector(), ListWindow::ListWindow(), NickAlternativesDialog::NickAlternativesDialog(), OptionsDialog::OptionsDialog(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), RegisteredUserMaskDialog::RegisteredUserMaskDialog(), RegisteredUserPropertiesDialog::RegisteredUserPropertiesDialog(), RegisteredUsersDialog::RegisteredUsersDialog(), SetupWizard::SetupWizard(), and ThemeManagementDialog::ThemeManagementDialog().
void KviTalHBox::setStretchFactor (QWidget * pChild, int iStretch)
Sets the stretch factor for an object.
Parameters:
pChild The object to stretch
iStretch The stretch factor to use
Returns:
void
References m_pLayout.
Referenced by AliasEditorWidget::AliasEditorWidget(), ClassEditorWidget::ClassEditorWidget(), DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), DccVoiceWindow::DccVoiceWindow(), HelpWidget::HelpWidget(), KviChannelWindow::KviChannelWindow(), KviClassEditorFunctionDialog::KviClassEditorFunctionDialog(), KviColorSelector::KviColorSelector(), KviFontSelector::KviFontSelector(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), KviMircTextColorSelector::KviMircTextColorSelector(), KviPasswordLineEdit::KviPasswordLineEdit(), KviPasswordSelector::KviPasswordSelector(), KviQueryWindow::KviQueryWindow(), KviStringSelector::KviStringSelector(), KviTalWizard::KviTalWizard(), KviUIntSelector::KviUIntSelector(), LinksWindow::LinksWindow(), ListWindow::ListWindow(), and SetupWizard::SetupWizard().
Member Data Documentation
QHBoxLayout* KviTalHBox::m_pLayout [private]
Referenced by addSpacing(), addStretch(), childEvent(), KviTalHBox(), setAlignment(), setMargin(), setSpacing(), and setStretchFactor().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalHBox.h
src/kvilib/tal/KviTalHBox.cpp