KVIrc: CodeTesterWidget Class Reference
CodeTesterWidget Class Reference
#include <CodeTesterWindow.h>
Public Member Functions
CodeTesterWidget (QWidget *par)
~CodeTesterWidget ()
Private Slots
void execute ()
Private Attributes
KviScriptEditor * m_pEditor
QPushButton * m_pExecuteButton
QLabel * m_pModeLabel
QLineEdit * m_pParams
Constructor & Destructor Documentation
CodeTesterWidget::CodeTesterWidget (QWidget * par)
References __tr2qs_ctx(), connect(), KviScriptEditor::createInstance(), execute(), g, m_pEditor, m_pExecuteButton, m_pModeLabel, and m_pParams.
CodeTesterWidget::~CodeTesterWidget ()
References KviScriptEditor::destroyInstance(), and m_pEditor.
Member Function Documentation
void CodeTesterWidget::execute () [private, slot]
References KviApplication::activeConsole(), g_pApp, KviScriptEditor::getText(), m_pEditor, m_pParams, and KviIrcUrl::run().
Referenced by CodeTesterWidget().
Member Data Documentation
KviScriptEditor* CodeTesterWidget::m_pEditor [private]
Referenced by CodeTesterWidget(), execute(), and ~CodeTesterWidget().
QPushButton* CodeTesterWidget::m_pExecuteButton [private]
Referenced by CodeTesterWidget().
QLabel* CodeTesterWidget::m_pModeLabel [private]
Referenced by CodeTesterWidget().
QLineEdit* CodeTesterWidget::m_pParams [private]
Referenced by CodeTesterWidget(), and execute().
The documentation for this class was generated from the following files:
src/modules/codetester/CodeTesterWindow.h
src/modules/codetester/CodeTesterWindow.cpp