KVIrc: OptionsWidget_identityProfile Class Reference
OptionsWidget_identityProfile Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
virtual void commit ()
OptionsWidget_identityProfile (QWidget *pParent)
~OptionsWidget_identityProfile ()
Protected Slots
void addProfileEntry ()
void delProfileEntry ()
void editProfileEntry ()
void editProfileOkPressed ()
void toggleControls ()
Protected Attributes
int m_iCurrentEditedProfile
QPushButton * m_pBtnAddProfile
QPushButton * m_pBtnDelProfile
QPushButton * m_pBtnEditProfile
IdentityProfileEditor * m_pEditor
QCheckBox * m_pProfilesCheck
QTreeWidget * m_pTreeWidget
Constructor & Destructor Documentation
OptionsWidget_identityProfile::OptionsWidget_identityProfile (QWidget * pParent)
References __tr2qs_ctx(), KviTalToolTip::add(), addProfileEntry(), connect(), KviOptionsWidget::createLayout(), delProfileEntry(), editProfileEntry(), KviPointerList< T >::first(), KviIdentityProfileSet::instance(), KviIdentityProfileSet::isEmpty(), KviIdentityProfileSet::isEnabled(), KviOptionsWidget::layout(), m_iCurrentEditedProfile, m_pBtnAddProfile, m_pBtnDelProfile, m_pBtnEditProfile, m_pEditor, m_pProfilesCheck, m_pTreeWidget, KviPointerList< T >::next(), KviIdentityProfileSet::profiles(), and toggleControls().
OptionsWidget_identityProfile::~OptionsWidget_identityProfile ()
Member Function Documentation
void OptionsWidget_identityProfile::addProfileEntry () [protected, slot]
References KviIdentityProfile::altNick(), IdentityProfileEditor::editProfile(), m_iCurrentEditedProfile, m_pEditor, m_pTreeWidget, KviIdentityProfile::name(), KviIdentityProfile::network(), KviIdentityProfile::nick(), KviIdentityProfile::realName(), and KviIdentityProfile::userName().
Referenced by OptionsWidget_identityProfile().
void OptionsWidget_identityProfile::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KviIdentityProfileSet::addProfile(), KviIdentityProfileSet::clear(), i, KviIdentityProfileSet::instance(), m_pProfilesCheck, m_pTreeWidget, KviIdentityProfile::setAltNick(), KviIdentityProfileSet::setEnabled(), KviIdentityProfile::setName(), KviIdentityProfile::setNetwork(), KviIdentityProfile::setNick(), KviIdentityProfile::setRealName(), and KviIdentityProfile::setUserName().
void OptionsWidget_identityProfile::delProfileEntry () [protected, slot]
References m_pTreeWidget, and toggleControls().
Referenced by OptionsWidget_identityProfile().
void OptionsWidget_identityProfile::editProfileEntry () [protected, slot]
References KviIdentityProfile::altNick(), IdentityProfileEditor::editProfile(), m_iCurrentEditedProfile, m_pEditor, m_pTreeWidget, KviIdentityProfile::name(), KviIdentityProfile::network(), KviIdentityProfile::nick(), KviIdentityProfile::realName(), KviIdentityProfile::setAltNick(), KviIdentityProfile::setName(), KviIdentityProfile::setNetwork(), KviIdentityProfile::setNick(), KviIdentityProfile::setRealName(), KviIdentityProfile::setUserName(), and KviIdentityProfile::userName().
Referenced by OptionsWidget_identityProfile().
void OptionsWidget_identityProfile::editProfileOkPressed () [protected, slot]
References __tr2qs_ctx(), i, m_iCurrentEditedProfile, m_pEditor, IdentityProfileEditor::m_pNameEdit, m_pTreeWidget, and KviMessageBox::warning().
void OptionsWidget_identityProfile::toggleControls () [protected, slot]
References m_pBtnAddProfile, m_pBtnDelProfile, m_pBtnEditProfile, m_pProfilesCheck, and m_pTreeWidget.
Referenced by delProfileEntry(), and OptionsWidget_identityProfile().
Member Data Documentation
int OptionsWidget_identityProfile::m_iCurrentEditedProfile [protected]
Referenced by addProfileEntry(), editProfileEntry(), editProfileOkPressed(), and OptionsWidget_identityProfile().
QPushButton* OptionsWidget_identityProfile::m_pBtnAddProfile [protected]
Referenced by OptionsWidget_identityProfile(), and toggleControls().
QPushButton* OptionsWidget_identityProfile::m_pBtnDelProfile [protected]
Referenced by OptionsWidget_identityProfile(), and toggleControls().
QPushButton* OptionsWidget_identityProfile::m_pBtnEditProfile [protected]
Referenced by OptionsWidget_identityProfile(), and toggleControls().
IdentityProfileEditor* OptionsWidget_identityProfile::m_pEditor [protected]
Referenced by addProfileEntry(), editProfileEntry(), editProfileOkPressed(), and OptionsWidget_identityProfile().
QCheckBox* OptionsWidget_identityProfile::m_pProfilesCheck [protected]
Referenced by commit(), OptionsWidget_identityProfile(), and toggleControls().
QTreeWidget* OptionsWidget_identityProfile::m_pTreeWidget [protected]
Referenced by addProfileEntry(), commit(), delProfileEntry(), editProfileEntry(), editProfileOkPressed(), OptionsWidget_identityProfile(), and toggleControls().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp