KVIrc: KviRegisteredUserMask Class Reference
KviRegisteredUserMask Class Reference
#include <KviRegisteredUserMask.h>
Public Member Functions
KviRegisteredUserMask (KviRegisteredUser *pUser, KviIrcMask *pMask)
KviIrcMask * mask ()
int nonWildChars ()
KviRegisteredUser * user ()
~KviRegisteredUserMask ()
Private Attributes
int m_iMaskNonWildChars
KviIrcMask * m_pMask
KviRegisteredUser * m_pUser
Constructor & Destructor Documentation
KviRegisteredUserMask::KviRegisteredUserMask (KviRegisteredUser * pUser, KviIrcMask * pMask)
References m_iMaskNonWildChars, m_pMask, m_pUser, and KviIrcMask::nonWildChars().
KviRegisteredUserMask::~KviRegisteredUserMask () [inline]
Member Function Documentation
KviIrcMask* KviRegisteredUserMask::mask () [inline]
Referenced by KviConsoleWindow::getUserTipText(), and KviRegisteredUserDataBase::removeMask().
int KviRegisteredUserMask::nonWildChars () [inline]
Referenced by append_mask_to_list().
KviRegisteredUser* KviRegisteredUserMask::user () [inline]
Referenced by KviRegisteredUserDataBase::findMatchingUser(), KviRegisteredUserDataBase::findUserWithMask(), and KviConsoleWindow::getUserTipText().
Member Data Documentation
int KviRegisteredUserMask::m_iMaskNonWildChars [private]
Referenced by KviRegisteredUserMask().
KviIrcMask* KviRegisteredUserMask::m_pMask [private]
Referenced by KviRegisteredUserMask().
KviRegisteredUser* KviRegisteredUserMask::m_pUser [private]
Referenced by KviRegisteredUserMask().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviRegisteredUserMask.h
src/kvilib/ext/KviRegisteredUserMask.cpp