KVIrc: CodeTesterWindow Class Reference
CodeTesterWindow Class Reference
#include <CodeTesterWindow.h>
Public Member Functions
CodeTesterWindow (KviMainWindow *lpFrm)
~CodeTesterWindow ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void getConfigGroupName (QString &szName)
virtual void loadProperties (KviConfigurationFile *)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfigurationFile *)
Protected Attributes
CodeTesterWidget * m_pTester
Constructor & Destructor Documentation
CodeTesterWindow::CodeTesterWindow (KviMainWindow * lpFrm)
References KviPointerList< T >::append(), and m_pTester.
CodeTesterWindow::~CodeTesterWindow ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void CodeTesterWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void CodeTesterWindow::getConfigGroupName (QString & szName) [protected, virtual]
Reimplemented from KviWindow.
void CodeTesterWindow::loadProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
QPixmap * CodeTesterWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References KviIconManager::Bomb, g_pIconManager, and KviIconManager::getSmallIcon().
void CodeTesterWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References m_pTester.
void CodeTesterWindow::saveProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
Member Data Documentation
CodeTesterWidget* CodeTesterWindow::m_pTester [protected]
Referenced by CodeTesterWindow(), and resizeEvent().
The documentation for this class was generated from the following files:
src/modules/codetester/CodeTesterWindow.h
src/modules/codetester/CodeTesterWindow.cpp