KVIrc: EventEditorHandlerTreeWidgetItem Class Reference
EventEditorHandlerTreeWidgetItem Class Reference
#include <EventEditorWindow.h>
Public Member Functions
const int & cursorPosition ()
EventEditorHandlerTreeWidgetItem (QTreeWidgetItem *par, const QString &name, const QString &buffer, bool bEnabled)
QString name () const
void setCursorPosition (const int &cPos)
void setEnabled (const bool bEnabled)
void setName (const QString &szName)
~EventEditorHandlerTreeWidgetItem ()
Public Attributes
bool m_bEnabled
int m_cPos
QString m_szBuffer
QString m_szName
Constructor & Destructor Documentation
EventEditorHandlerTreeWidgetItem::EventEditorHandlerTreeWidgetItem (QTreeWidgetItem * par, const QString & name, const QString & buffer, bool bEnabled)
References m_cPos, setEnabled(), and setName().
EventEditorHandlerTreeWidgetItem::~EventEditorHandlerTreeWidgetItem () [inline]
Member Function Documentation
const int& EventEditorHandlerTreeWidgetItem::cursorPosition () [inline]
References m_cPos.
QString EventEditorHandlerTreeWidgetItem::name () const [inline]
References m_szName.
Referenced by EventEditor::currentItemChanged().
void EventEditorHandlerTreeWidgetItem::setCursorPosition (const int & cPos) [inline]
References m_cPos.
void EventEditorHandlerTreeWidgetItem::setEnabled (const bool bEnabled)
References g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Handler, KviIconManager::HandlerDisabled, and m_bEnabled.
Referenced by EventEditorHandlerTreeWidgetItem(), and EventEditor::toggleCurrentHandlerEnabled().
void EventEditorHandlerTreeWidgetItem::setName (const QString & szName)
References m_szName.
Referenced by EventEditorHandlerTreeWidgetItem(), and EventEditor::saveLastEditedItem().
Member Data Documentation
bool EventEditorHandlerTreeWidgetItem::m_bEnabled
Referenced by EventEditor::getExportEventBuffer(), setEnabled(), and EventEditor::toggleCurrentHandlerEnabled().
int EventEditorHandlerTreeWidgetItem::m_cPos
Referenced by cursorPosition(), EventEditorHandlerTreeWidgetItem(), and setCursorPosition().
QString EventEditorHandlerTreeWidgetItem::m_szBuffer
Referenced by EventEditor::currentItemChanged(), EventEditor::getExportEventBuffer(), and EventEditor::saveLastEditedItem().
QString EventEditorHandlerTreeWidgetItem::m_szName
Referenced by EventEditor::exportCurrentHandler(), EventEditor::getExportEventBuffer(), name(), EventEditor::saveLastEditedItem(), and setName().
The documentation for this class was generated from the following files:
src/modules/eventeditor/EventEditorWindow.h
src/modules/eventeditor/EventEditorWindow.cpp