KVIrc: OptionsWidget_away Class Reference
OptionsWidget_away Class Reference
#include <OptionsWidget_away.h>
Public Slots
void enableAwayMessage (bool)
void enableCustomAwayText (bool)
Public Member Functions
OptionsWidget_away (QWidget *parent)
~OptionsWidget_away ()
Protected Attributes
KviStringSelector * m_pAwayMessage
KviStringSelector * m_pCustomAwayNick
KviBoolSelector * m_pEnableAwayMessage
KviBoolSelector * m_pEnableAwayNick
KviBoolSelector * m_pEnableCustomAwayNick
Constructor & Destructor Documentation
OptionsWidget_away::OptionsWidget_away (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), connect(), KviOptionsWidget::createLayout(), enableAwayMessage(), enableCustomAwayText(), g, KVI_OPTION_BOOL, KviOption_boolAutoGeneratedAwayNick, KviOption_boolChangeNickAway, KviOption_boolExitAwayOnInput, KviOption_boolUseAwayMessage, KviOption_stringAwayMessage, KviOption_stringCustomAwayNick, m_pAwayMessage, m_pCustomAwayNick, m_pEnableAwayMessage, m_pEnableAwayNick, and m_pEnableCustomAwayNick.
OptionsWidget_away::~OptionsWidget_away ()
Member Function Documentation
void OptionsWidget_away::enableAwayMessage (bool) [slot]
References m_pAwayMessage, m_pEnableAwayMessage, and KviStringSelector::setEnabled().
Referenced by OptionsWidget_away().
void OptionsWidget_away::enableCustomAwayText (bool) [slot]
References m_pCustomAwayNick, m_pEnableAwayNick, m_pEnableCustomAwayNick, and KviStringSelector::setEnabled().
Referenced by OptionsWidget_away().
Member Data Documentation
KviStringSelector* OptionsWidget_away::m_pAwayMessage [protected]
Referenced by enableAwayMessage(), and OptionsWidget_away().
KviStringSelector* OptionsWidget_away::m_pCustomAwayNick [protected]
Referenced by enableCustomAwayText(), and OptionsWidget_away().
KviBoolSelector* OptionsWidget_away::m_pEnableAwayMessage [protected]
Referenced by enableAwayMessage(), and OptionsWidget_away().
KviBoolSelector* OptionsWidget_away::m_pEnableAwayNick [protected]
Referenced by enableCustomAwayText(), and OptionsWidget_away().
KviBoolSelector* OptionsWidget_away::m_pEnableCustomAwayNick [protected]
Referenced by enableCustomAwayText(), and OptionsWidget_away().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_away.h
src/modules/options/OptionsWidget_away.cpp