KVIrc: KviThreadManager Class Reference
KviThreadManager Class Reference
#include <KviThread.h>
Static Public Member Functions
static void killPendingEvents (QObject *receiver)
Protected Member Functions
void killPendingEventsByReceiver (QObject *receiver)
KviThreadManager ()
void postSlaveEvent (QObject *o, QEvent *e)
void registerSlaveThread (KviThread *t)
void threadEnteredWaitState ()
void threadLeftWaitState ()
void unregisterSlaveThread (KviThread *t)
~KviThreadManager ()
Static Protected Member Functions
static void globalDestroy ()
static void globalInit ()
Private Slots
void eventsPending (int fd)
Private Attributes
int m_fd [2]
int m_iTriggerCount
int m_iWaitingThreads
KviPointerList
< KviThreadPendingEvent > * m_pEventQueue
KviMutex * m_pMutex
QSocketNotifier * m_pSn
KviPointerList< KviThread > * m_pThreadList
Friends
class KviApplication
class KviThread
Constructor & Destructor Documentation
KviThreadManager::KviThreadManager () [protected]
References connect(), eventsPending(), KviError::getDescription(), KVI_THREAD_PIPE_SIDE_MASTER, KVI_THREAD_PIPE_SIDE_SLAVE, m_fd, m_iTriggerCount, m_iWaitingThreads, m_pEventQueue, m_pMutex, m_pSn, m_pThreadList, KviPointerList< T >::setAutoDelete(), and KviError::translateSystemError().
Referenced by globalInit().
KviThreadManager::~KviThreadManager () [protected]
References KviPointerList< T >::first(), KVI_THREAD_PIPE_SIDE_MASTER, KVI_THREAD_PIPE_SIDE_SLAVE, KviMutex::lock(), m_fd, m_pEventQueue, m_pMutex, m_pSn, m_pThreadList, KviPointerList< T >::removeFirst(), t(), and KviMutex::unlock().
Member Function Documentation
void KviThreadManager::eventsPending (int fd) [private, slot]
References KviPointerList< T >::first(), KviMutex::lock(), m_iTriggerCount, m_pEventQueue, m_pMutex, KviPointerList< T >::removeRef(), and KviMutex::unlock().
Referenced by KviThreadManager().
void KviThreadManager::globalDestroy () [static, protected]
References g_pThreadManager.
Referenced by KviApplication::~KviApplication().
void KviThreadManager::globalInit () [static, protected]
References kvi_threadInitialize(), and KviThreadManager().
Referenced by KviApplication::setup().
void KviThreadManager::killPendingEvents (QObject * receiver) [static]
References killPendingEventsByReceiver().
Referenced by DccChatWindow::~DccChatWindow(), DccFileTransfer::~DccFileTransfer(), DccVideoWindow::~DccVideoWindow(), DccVoiceWindow::~DccVoiceWindow(), KviIdentSentinel::~KviIdentSentinel(), and KviSoundPlayer::~KviSoundPlayer().
void KviThreadManager::killPendingEventsByReceiver (QObject * receiver) [protected]
References KviPointerList< T >::append(), KviPointerList< T >::first(), l, KviMutex::lock(), m_pEventQueue, m_pMutex, KviPointerList< T >::next(), KviPointerList< T >::removeRef(), KviPointerList< T >::setAutoDelete(), and KviMutex::unlock().
Referenced by killPendingEvents().
void KviThreadManager::postSlaveEvent (QObject * o, QEvent * e) [protected]
References KviPointerList< T >::append(), KviPointerList< T >::count(), e, _KviThreadPendingEvent::e, KVI_THREAD_MAX_EVENT_QUEUE_LENGTH, KVI_THREAD_PIPE_SIDE_SLAVE, KviMutex::lock(), m_fd, m_iTriggerCount, m_iWaitingThreads, m_pEventQueue, m_pMutex, o, _KviThreadPendingEvent::o, and KviMutex::unlock().
Referenced by KviThread::postEvent().
void KviThreadManager::registerSlaveThread (KviThread * t) [protected]
References KviPointerList< T >::append(), KviMutex::lock(), m_pMutex, m_pThreadList, and KviMutex::unlock().
Referenced by KviThread::KviThread().
void KviThreadManager::threadEnteredWaitState () [protected]
References KviMutex::lock(), m_iWaitingThreads, m_pMutex, and KviMutex::unlock().
Referenced by KviThread::wait().
void KviThreadManager::threadLeftWaitState () [protected]
References KviMutex::lock(), m_iWaitingThreads, m_pMutex, and KviMutex::unlock().
Referenced by KviThread::wait().
void KviThreadManager::unregisterSlaveThread (KviThread * t) [protected]
References KviMutex::lock(), m_pMutex, m_pThreadList, KviPointerList< T >::removeRef(), and KviMutex::unlock().
Referenced by KviThread::~KviThread().
Friends And Related Function Documentation
friend class KviApplication [friend]
friend class KviThread [friend]
Member Data Documentation
int KviThreadManager::m_fd[2] [private]
Referenced by KviThreadManager(), postSlaveEvent(), and ~KviThreadManager().
int KviThreadManager::m_iTriggerCount [private]
Referenced by eventsPending(), KviThreadManager(), and postSlaveEvent().
int KviThreadManager::m_iWaitingThreads [private]
Referenced by KviThreadManager(), postSlaveEvent(), threadEnteredWaitState(), and threadLeftWaitState().
KviPointerList<KviThreadPendingEvent>* KviThreadManager::m_pEventQueue [private]
Referenced by eventsPending(), killPendingEventsByReceiver(), KviThreadManager(), postSlaveEvent(), and ~KviThreadManager().
KviMutex* KviThreadManager::m_pMutex [private]
Referenced by eventsPending(), killPendingEventsByReceiver(), KviThreadManager(), postSlaveEvent(), registerSlaveThread(), threadEnteredWaitState(), threadLeftWaitState(), unregisterSlaveThread(), and ~KviThreadManager().
QSocketNotifier* KviThreadManager::m_pSn [private]
Referenced by KviThreadManager(), and ~KviThreadManager().
KviPointerList<KviThread>* KviThreadManager::m_pThreadList [private]
Referenced by KviThreadManager(), registerSlaveThread(), unregisterSlaveThread(), and ~KviThreadManager().
The documentation for this class was generated from the following files:
src/kvilib/system/KviThread.h
src/kvilib/system/KviThread.cpp