KVIrc: KviKvsSwitchList Class Reference
KviKvsSwitchList Class Reference
#include <KviKvsSwitchList.h>
Public Member Functions
void addLong (const QString &szLongKey, KviKvsVariant *pVariant)
void addShort (unsigned short uShortKey, KviKvsVariant *pVariant)
void clear ()
KviKvsVariant * find (unsigned short uShortKey)
KviKvsVariant * find (const QString &szLongKey)
KviKvsVariant * find (unsigned short uShortKey, const QString &szLongKey)
KviKvsVariant * find (const QChar &c)
bool getAsStringIfExisting (unsigned short uShortKey, const QString &szLongKey, QString &szBuffer)
bool isEmpty ()
KviKvsSwitchList ()
~KviKvsSwitchList ()
Protected Attributes
KviPointerHashTable< QString,
KviKvsVariant > * m_pLongSwitchDict
KviPointerHashTable< unsigned
short, KviKvsVariant > * m_pShortSwitchDict
Constructor & Destructor Documentation
KviKvsSwitchList::KviKvsSwitchList ()
References m_pLongSwitchDict, and m_pShortSwitchDict.
KviKvsSwitchList::~KviKvsSwitchList ()
References m_pLongSwitchDict, and m_pShortSwitchDict.
Member Function Documentation
void KviKvsSwitchList::addLong (const QString & szLongKey, KviKvsVariant * pVariant)
References m_pLongSwitchDict, KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by KviKvsTreeNodeSwitchList::evaluate().
void KviKvsSwitchList::addShort (unsigned short uShortKey, KviKvsVariant * pVariant)
References m_pShortSwitchDict, KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by KviKvsTreeNodeSwitchList::evaluate().
void KviKvsSwitchList::clear ()
References m_pLongSwitchDict, and m_pShortSwitchDict.
Referenced by KviKvsTreeNodeSwitchList::evaluate().
KviKvsVariant* KviKvsSwitchList::find (const QString & szLongKey) [inline]
KviKvsVariant* KviKvsSwitchList::find (unsigned short uShortKey, const QString & szLongKey) [inline]
References t().
KviKvsVariant* KviKvsSwitchList::find (const QChar & c) [inline]
Referenced by action_kvs_cmd_create(), action_kvs_cmd_destroy(), action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_trigger(), addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), avatar_kvs_cmd_notify(), context_kvs_cmd_clearQueue(), dcc_kvs_cmd_abort(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_setBandwidthLimit(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_parse_default_parameters(), default_module_kvs_cmd_unload(), dialog_kvs_cmd_textinput(), KviKvsTreeNodeSpecialCommandSwitch::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), file_kvs_cmd_copy(), file_kvs_cmd_remove(), file_kvs_cmd_rmdir(), file_kvs_cmd_write(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), help_kvs_cmd_open(), http_kvs_complete_get(), objects_kvs_cmd_clearObjects(), perl_kvs_cmd_begin(), perl_kvs_cmd_destroy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), python_kvs_cmd_begin(), python_kvs_cmd_destroy(), serverdb_kvs_cmd_addNetwork(), serverdb_kvs_cmd_addServer(), sharedfile_kvs_cmd_add(), toolbar_kvs_cmd_additem(), toolbar_kvs_cmd_clear(), toolbar_kvs_cmd_create(), toolbar_kvs_cmd_destroy(), toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_removeitem(), toolbar_kvs_cmd_show(), and upnp_kvs_cmd_addPortMapping().
KviKvsVariant* KviKvsSwitchList::find (unsigned short uShortKey) [inline]
bool KviKvsSwitchList::getAsStringIfExisting (unsigned short uShortKey, const QString & szLongKey, QString & szBuffer) [inline]
References KviKvsVariant::asString(), and v.
Referenced by action_kvs_cmd_create(), dialog_kvs_cmd_textinput(), http_kvs_complete_get(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), notifier_kvs_cmd_message(), reguser_kvs_cmd_add(), serverdb_kvs_cmd_addServer(), and system_kvs_cmd_runcmd().
bool KviKvsSwitchList::isEmpty () [inline]
Member Data Documentation
KviPointerHashTable<QString,KviKvsVariant>* KviKvsSwitchList::m_pLongSwitchDict [protected]
Referenced by addLong(), clear(), KviKvsSwitchList(), and ~KviKvsSwitchList().
KviPointerHashTable<unsigned short,KviKvsVariant>* KviKvsSwitchList::m_pShortSwitchDict [protected]
Referenced by addShort(), clear(), KviKvsSwitchList(), and ~KviKvsSwitchList().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsSwitchList.h
src/kvirc/kvs/KviKvsSwitchList.cpp