KVIrc: KvsObject_dateTimeEdit Class Reference
KvsObject_dateTimeEdit Class Reference
#include <KvsObject_dateTimeEdit.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void slotDateChanged (const QDate &)
void slotDateTimeChanged (const QDateTime &)
void slotTimeChanged (const QTime &)
Protected Member Functions
bool date (KviKvsObjectFunctionCall *c)
bool dateChangedEvent (KviKvsObjectFunctionCall *c)
bool dateTimeChangedEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool setDate (KviKvsObjectFunctionCall *c)
bool setTime (KviKvsObjectFunctionCall *c)
bool time (KviKvsObjectFunctionCall *c)
bool timeChangedEvent (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_dateTimeEdit::date (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_dateTimeEdit::dateChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_dateTimeEdit::dateTimeChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_dateTimeEdit::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect().
bool KvsObject_dateTimeEdit::setDate (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_dateTimeEdit::setTime (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_dateTimeEdit::slotDateChanged (const QDate &) [protected, slot]
References KviKvsObject::callFunction().
void KvsObject_dateTimeEdit::slotDateTimeChanged (const QDateTime &) [protected, slot]
References KviKvsObject::callFunction().
void KvsObject_dateTimeEdit::slotTimeChanged (const QTime &) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_dateTimeEdit::time (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_dateTimeEdit::timeChangedEvent (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_dateTimeEdit::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_dateTimeEdit.h
src/modules/objects/KvsObject_dateTimeEdit.cpp