KVIrc: KviCustomToolBarDescriptor Class Reference
KviCustomToolBarDescriptor Class Reference
#include <KviCustomToolBarDescriptor.h>
Public Member Functions
KviPointerList< QString > * actions ()
bool addAction (const QString &szAction)
void clear ()
KviCustomToolBar * createToolBar ()
const QString & iconId ()
const QString & id ()
int internalId ()
const QString & label ()
const QString & labelCode ()
bool removeAction (const QString &szAction)
bool removeAction (unsigned int iAction)
void rename (const QString &szNewName)
void setIconId (const QString &szIconId)
KviCustomToolBar * toolBar ()
void updateToolBar ()
~KviCustomToolBarDescriptor ()
Protected Member Functions
void createLabelScript (const QString &szNewLabelCode)
void fillToolBar ()
KviCustomToolBarDescriptor (const QString &szId, const QString &szLabelCode)
bool load (KviConfigurationFile *cfg)
void registerToolBar (KviCustomToolBar *t)
void save (KviConfigurationFile *cfg)
void unregisterToolBar (KviCustomToolBar *t)
Protected Attributes
bool m_bVisibleAtStartup
int m_iInternalId
KviPointerList< QString > * m_pActions
KviKvsScript * m_pLabelScript
KviCustomToolBar * m_pToolBar
QString m_szIconId
QString m_szId
QString m_szParsedLabel
Friends
class KviCustomToolBar
class KviCustomToolBarManager
Constructor & Destructor Documentation
KviCustomToolBarDescriptor::KviCustomToolBarDescriptor (const QString & szId, const QString & szLabelCode) protected
References createLabelScript(), g_pApp, KviApplication::getGloballyUniqueId(), m_bVisibleAtStartup, m_iInternalId, m_pActions, m_pToolBar, m_szId, and KviPointerList< T >::setAutoDelete().
KviCustomToolBarDescriptor::~KviCustomToolBarDescriptor ()
References m_pActions, m_pLabelScript, and m_pToolBar.
Member Function Documentation
KviPointerList<QString>* KviCustomToolBarDescriptor::actions () inline
Referenced by CustomizeToolBarsDialog::exportToolBar(), KviCustomToolBar::syncDescriptor(), and toolbar_kvs_fnc_items().
bool KviCustomToolBarDescriptor::addAction (const QString & szAction)
References a, KviAction::addToCustomToolBar(), KviPointerList< T >::append(), KviActionManager::getAction(), KviActionManager::instance(), m_pActions, and m_pToolBar.
Referenced by toolbar_kvs_cmd_additem().
void KviCustomToolBarDescriptor::clear ()
References KviPointerList< T >::clear(), m_pActions, and m_pToolBar.
Referenced by toolbar_kvs_cmd_clear(), and toolbar_kvs_cmd_create().
void KviCustomToolBarDescriptor::createLabelScript (const QString & szNewLabelCode) protected
References m_pLabelScript, m_szId, and KviKvsScript::Parameter.
Referenced by KviCustomToolBarDescriptor(), load(), and rename().
KviCustomToolBar * KviCustomToolBarDescriptor::createToolBar ()
References fillToolBar(), KviCustomToolBar, label(), and m_pToolBar.
Referenced by CustomizeToolBarsDialog::newToolBar(), toolbar_kvs_cmd_show(), and KviMainWindow::toolbarsPopupSelected().
void KviCustomToolBarDescriptor::fillToolBar () protected
References a, KviAction::addToCustomToolBar(), KviPointerList< T >::append(), KviPointerList< T >::count(), d, KviPointerList< T >::first(), KviActionManager::getAction(), KviActionManager::instance(), m_pActions, m_pToolBar, KviPointerList< T >::next(), p, KviPointerList< T >::removeRef(), and KviPointerList< T >::setAutoDelete().
Referenced by createToolBar(), removeAction(), and updateToolBar().
const QString& KviCustomToolBarDescriptor::iconId () inline
Referenced by CustomizeToolBarsDialog::exportToolBar(), and CustomizeToolBarsDialog::renameToolBar().
const QString& KviCustomToolBarDescriptor::id () inline
Referenced by CustomizeToolBarsDialog::deleteToolBar(), CustomizeToolBarsDialog::exportToolBar(), CustomizeToolBarsDialog::renameToolBar(), and toolbar_kvs_cmd_hide().
int KviCustomToolBarDescriptor::internalId () inline
const QString & KviCustomToolBarDescriptor::label ()
References KviKvsScript::code(), g_pActiveWindow, m_pLabelScript, m_szParsedLabel, and KviKvsScript::run().
Referenced by createToolBar(), and rename().
const QString & KviCustomToolBarDescriptor::labelCode ()
References KviKvsScript::code(), and m_pLabelScript.
Referenced by CustomizeToolBarsDialog::exportToolBar(), and CustomizeToolBarsDialog::renameToolBar().
bool KviCustomToolBarDescriptor::load (KviConfigurationFile * cfg) protected
References KviPointerList< T >::append(), KviPointerList< T >::clear(), createLabelScript(), KviConfigurationFile::group(), i, m_pActions, m_pLabelScript, m_szIconId, m_szId, n, p, KviConfigurationFile::readEntry(), and KviConfigurationFile::readUIntEntry().
Referenced by KviCustomToolBarManager::load().
void KviCustomToolBarDescriptor::registerToolBar (KviCustomToolBar * t) protected
References m_pToolBar, and t().
Referenced by KviCustomToolBar::KviCustomToolBar().
bool KviCustomToolBarDescriptor::removeAction (const QString & szAction)
References fillToolBar(), KviPointerList< T >::first(), m_pActions, m_pToolBar, KviPointerList< T >::next(), KviPointerList< T >::removeRef(), and s.
Referenced by toolbar_kvs_cmd_removeitem().
bool KviCustomToolBarDescriptor::removeAction (unsigned int iAction)
References KviPointerList< T >::count(), fillToolBar(), m_pActions, m_pToolBar, and KviPointerList< T >::remove().
void KviCustomToolBarDescriptor::rename (const QString & szNewName)
References createLabelScript(), label(), m_pLabelScript, and m_pToolBar.
Referenced by KviCustomToolBarManager::renameDescriptor(), and toolbar_kvs_cmd_create().
void KviCustomToolBarDescriptor::save (KviConfigurationFile * cfg) protected
References KviKvsScript::code(), KviPointerList< T >::count(), KviPointerList< T >::first(), i, m_pActions, m_pLabelScript, m_szIconId, m_szId, KviPointerList< T >::next(), p, KviConfigurationFile::setGroup(), and KviConfigurationFile::writeEntry().
void KviCustomToolBarDescriptor::setIconId (const QString & szIconId) inline
Referenced by CustomizeToolBarsDialog::newToolBar(), CustomizeToolBarsDialog::renameToolBar(), and toolbar_kvs_cmd_create().
KviCustomToolBar* KviCustomToolBarDescriptor::toolBar () inline
Referenced by toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_show(), toolbar_kvs_fnc_isVisible(), and KviMainWindow::toolbarsPopupSelected().
void KviCustomToolBarDescriptor::unregisterToolBar (KviCustomToolBar * t) protected
References m_pToolBar.
Referenced by KviCustomToolBar::~KviCustomToolBar().
void KviCustomToolBarDescriptor::updateToolBar ()
References fillToolBar(), and m_pToolBar.
Friends And Related Function Documentation
friend class KviCustomToolBar friend
Referenced by createToolBar().
friend class KviCustomToolBarManager friend
Member Data Documentation
bool KviCustomToolBarDescriptor::m_bVisibleAtStartup protected
Referenced by KviCustomToolBarDescriptor(), and KviCustomToolBarManager::load().
int KviCustomToolBarDescriptor::m_iInternalId protected
Referenced by KviCustomToolBarDescriptor().
KviPointerList<QString>* KviCustomToolBarDescriptor::m_pActions protected
Referenced by addAction(), clear(), fillToolBar(), KviCustomToolBarDescriptor(), load(), removeAction(), save(), and ~KviCustomToolBarDescriptor().
KviKvsScript* KviCustomToolBarDescriptor::m_pLabelScript protected
Referenced by createLabelScript(), label(), labelCode(), load(), rename(), save(), and ~KviCustomToolBarDescriptor().
KviCustomToolBar* KviCustomToolBarDescriptor::m_pToolBar protected
Referenced by addAction(), clear(), createToolBar(), fillToolBar(), KviCustomToolBarDescriptor(), registerToolBar(), removeAction(), rename(), unregisterToolBar(), updateToolBar(), and ~KviCustomToolBarDescriptor().
QString KviCustomToolBarDescriptor::m_szIconId protected
Referenced by load(), and save().
QString KviCustomToolBarDescriptor::m_szId protected
Referenced by createLabelScript(), KviCustomToolBarDescriptor(), load(), and save().
QString KviCustomToolBarDescriptor::m_szParsedLabel protected
Referenced by label().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCustomToolBarDescriptor.h
src/kvirc/kernel/KviCustomToolBarDescriptor.cpp