KVIrc: OptionsWidget_urlHandlers Class Reference
OptionsWidget_urlHandlers Class Reference
#include <OptionsWidget_urlHandlers.h>
Public Slots
void toggleEditors (bool)
Public Member Functions
virtual void commit ()
OptionsWidget_urlHandlers (QWidget *parent)
~OptionsWidget_urlHandlers ()
Protected Attributes
QRadioButton * m_pClickRadio
QRadioButton * m_pDoubleClickRadio
KviStringSelector * m_pFileHandler
KviStringSelector * m_pFtpHandler
KviStringSelector * m_pHttpHandler
KviStringSelector * m_pHttpsHandler
KviStringSelector * m_pMailtoHandler
KviStringSelector * m_pOtherHandler
Constructor & Destructor Documentation
OptionsWidget_urlHandlers::OptionsWidget_urlHandlers (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), connect(), KviOptionsWidget::createLayout(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolUseSystemUrlHandlers, KviOption_stringUrlFileCommand, KviOption_stringUrlFtpCommand, KviOption_stringUrlHttpCommand, KviOption_stringUrlHttpsCommand, KviOption_stringUrlMailtoCommand, KviOption_stringUrlUnknownCommand, KviOption_uintUrlMouseClickNum, m_pClickRadio, m_pDoubleClickRadio, m_pFileHandler, m_pFtpHandler, m_pHttpHandler, m_pHttpsHandler, m_pMailtoHandler, m_pOtherHandler, KviStringSelector::setEnabled(), START_ROW, and toggleEditors().
OptionsWidget_urlHandlers::~OptionsWidget_urlHandlers ()
Member Function Documentation
void OptionsWidget_urlHandlers::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_STRING, KVI_OPTION_UINT, KviOption_stringUrlFileCommand, KviOption_stringUrlFtpCommand, KviOption_stringUrlHttpCommand, KviOption_stringUrlHttpsCommand, KviOption_stringUrlMailtoCommand, KviOption_stringUrlUnknownCommand, KviOption_uintUrlMouseClickNum, m_pClickRadio, and m_pDoubleClickRadio.
void OptionsWidget_urlHandlers::toggleEditors (bool bToggled) [slot]
References m_pFileHandler, m_pFtpHandler, m_pHttpHandler, m_pHttpsHandler, m_pMailtoHandler, m_pOtherHandler, and KviStringSelector::setEnabled().
Referenced by OptionsWidget_urlHandlers().
Member Data Documentation
QRadioButton* OptionsWidget_urlHandlers::m_pClickRadio [protected]
Referenced by commit(), and OptionsWidget_urlHandlers().
QRadioButton* OptionsWidget_urlHandlers::m_pDoubleClickRadio [protected]
Referenced by commit(), and OptionsWidget_urlHandlers().
KviStringSelector* OptionsWidget_urlHandlers::m_pFileHandler [protected]
Referenced by OptionsWidget_urlHandlers(), and toggleEditors().
KviStringSelector* OptionsWidget_urlHandlers::m_pFtpHandler [protected]
Referenced by OptionsWidget_urlHandlers(), and toggleEditors().
KviStringSelector* OptionsWidget_urlHandlers::m_pHttpHandler [protected]
Referenced by OptionsWidget_urlHandlers(), and toggleEditors().
KviStringSelector* OptionsWidget_urlHandlers::m_pHttpsHandler [protected]
Referenced by OptionsWidget_urlHandlers(), and toggleEditors().
KviStringSelector* OptionsWidget_urlHandlers::m_pMailtoHandler [protected]
Referenced by OptionsWidget_urlHandlers(), and toggleEditors().
KviStringSelector* OptionsWidget_urlHandlers::m_pOtherHandler [protected]
Referenced by OptionsWidget_urlHandlers(), and toggleEditors().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_urlHandlers.h
src/modules/options/OptionsWidget_urlHandlers.cpp