KVIrc: KviKvsPopupMenuItemExtMenu Class Reference
KviKvsPopupMenuItemExtMenu Class Reference
#include <KviKvsPopupMenu.h>
Public Member Functions
virtual void clear ()
virtual KviKvsPopupMenuItem * clone () const
const QString & extName ()
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)
virtual ~KviKvsPopupMenuItemExtMenu ()
Public Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
QPixmap * evaluateIcon (KviKvsPopupMenuTopLevelData *pData)
QString evaluateText (KviKvsPopupMenuTopLevelData *pData)
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
virtual ~KviKvsPopupMenuItemWithTextAndIcon ()
Public Member Functions inherited from KviKvsPopupMenuItem
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
virtual KviKvsScript * kvsCode ()
KviKvsScript * kvsCondition ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItemExtMenu (const QString &szItemName, const QString &szMenuName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemExtMenu (const QString &szItemName, const QString &szMenuName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItem
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Protected Attributes
KviKvsPopupMenu * m_pMenu
QString m_szMenuName
Protected Attributes inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsScript * m_pKvsIcon
KviKvsScript * m_pKvsText
Protected Attributes inherited from KviKvsPopupMenuItem
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Friends
class KviKvsPopupMenu
Additional Inherited Members
Public Types inherited from KviKvsPopupMenuItem
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Constructor & Destructor Documentation
KviKvsPopupMenuItemExtMenu::KviKvsPopupMenuItemExtMenu (const QString & szItemName, const QString & szMenuName, const QString & szText, const QString & szIcon, const QString & szCondition) protected
References m_pMenu, and m_szMenuName.
Referenced by clone().
KviKvsPopupMenuItemExtMenu::KviKvsPopupMenuItemExtMenu (const QString & szItemName, const QString & szMenuName, const KviKvsScript * pText, const KviKvsScript * pIcon, const KviKvsScript * pCondition) protected
References m_pMenu, and m_szMenuName.
KviKvsPopupMenuItemExtMenu::~KviKvsPopupMenuItemExtMenu () virtual
References m_pMenu.
Member Function Documentation
void KviKvsPopupMenuItemExtMenu::clear () virtual
Reimplemented from KviKvsPopupMenuItem.
References m_pMenu.
KviKvsPopupMenuItem * KviKvsPopupMenuItemExtMenu::clone () const virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItemExtMenu(), KviKvsPopupMenuItem::m_pKvsCondition, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsIcon, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsText, KviKvsPopupMenuItem::m_szItemName, and m_szMenuName.
const QString& KviKvsPopupMenuItemExtMenu::extName () inline
void KviKvsPopupMenuItemExtMenu::fill (KviKvsPopupMenu * pMenu, KviKvsPopupMenuTopLevelData * pData, int iIdx) virtual
Implements KviKvsPopupMenuItem.
References __tr2qs_ctx(), KviKvsPopupMenu::copyFrom(), KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), KviKvsPopupManager::instance(), KviKvsPopupMenu::isHardLocked(), KVI_OUT_PARSERWARNING, KviKvsPopupMenu, KviKvsPopupManager::lookup(), m_pMenu, m_szMenuName, KviWindow::output(), KviKvsPopupMenu::popupName(), KviKvsPopupMenu::setParentPopup(), and KviKvsPopupMenuTopLevelData::window().
Friends And Related Function Documentation
friend class KviKvsPopupMenu friend
Referenced by fill().
Member Data Documentation
KviKvsPopupMenu* KviKvsPopupMenuItemExtMenu::m_pMenu protected
Referenced by clear(), fill(), KviKvsPopupMenuItemExtMenu(), and ~KviKvsPopupMenuItemExtMenu().
QString KviKvsPopupMenuItemExtMenu::m_szMenuName protected
Referenced by clone(), fill(), and KviKvsPopupMenuItemExtMenu().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp