KVIrc: KviLocale Class Reference
KviLocale Class Reference
Holds the localization functions.
#include <KviLocale.h>
Classes
struct _EncodingDescription
Holds the encoding data.
Public Types
typedef struct
KviLocale::_EncodingDescription EncodingDescription
Public Member Functions
QTextCodec * codecForName (const char *pcName)
Returns the codec associated to the given translation.
unsigned int count ()
Returns the number of instances of the class.
EncodingDescription * encodingDescription (int iIdx)
Returns the description of the encoding used.
const char * encodingGroup (int iIdx)
Returns the description of the encoding used.
bool findCatalogue (QString &szBuffer, const QString &szName, const QString &szLocaleDir)
Finds the catalogue.
KviMessageCatalogue * getLoadedCatalogue (const QString &szName)
Returns the loaded catalogue.
KviMessageCatalogue * loadCatalogue (const QString &szName, const QString &szLocaleDir)
Loads the catalogue.
const KviCString & localeName ()
Returns the language code of the localization.
const char * translate (const char *pcText, const char *pcContext)
Translates the given text from the given context.
const QString & translateToQString (const char *pcText, const char *pcContext)
Translates the given text from the given context.
bool unloadCatalogue (const QString &szName)
Unloads a catalogue.
Static Public Member Functions
static void done ()
Destroys the class instance.
static void init (QApplication *pApp, const QString &szLocaleDir, const QString &szForceLocaleDir)
Initializes the class instance.
static KviLocale * instance ()
Returns the instance of the class.
Static Public Attributes
static KviCString g_szLang = ""
Protected Member Functions
KviLocale (QApplication *pApp, const QString &szLocaleDir, const QString &szForceLocaleDir)
Constructs the KviLocale object.
~KviLocale ()
Destroys the object.
Protected Attributes
QApplication * m_pApp
Static Private Attributes
static KviLocale * m_pSelf = NULL
static unsigned int m_uCount = 0
Detailed Description
Holds the localization functions.
Member Typedef Documentation
KviLocale::EncodingDescription
Constructor & Destructor Documentation
KviLocale::KviLocale (QApplication * pApp, const QString & szLocaleDir, const QString & szForceLocaleDir) [protected]
Constructs the KviLocale object.
Parameters:
pApp The main application
szLocaleDir The directory containing the localizations
szForceLocaleDir The directory forced by the user
Returns:
KviLocale
References KviCString::cutFromFirst(), KviFileUtils::fileExists(), findCatalogue(), g_pMainCatalogue, g_szDefaultLocalePath, g_szLang, KviEnvironment::getVariable(), KviCString::hasData(), KviCString::isEmpty(), KVI_FORCE_LOCALE_FILE_NAME, kvi_strEqualCI(), KviCString::len(), KviMessageCatalogue::load(), m_pApp, KviCString::ptr(), KviFileUtils::readFile(), KviPointerHashTable< Key, T >::setAutoDelete(), szBuffer, KviCString::toLower(), and KviCString::trim().
Referenced by init().
KviLocale::~KviLocale () [protected]
Destroys the object.
Returns:
KviLocale
References g_pCatalogueDict, g_pMainCatalogue, g_pSmartCodecDict, g_pTranslator, and m_pApp.
Member Function Documentation
QTextCodec * KviLocale::codecForName (const char * pcName)
Returns the codec associated to the given translation.
Parameters:
pcName The name of the translation
Returns:
QTextCodec *
References KviCString::cutFromFirst(), KviPointerHashTable< Key, T >::find(), KviCString::findFirstIdx(), kvi_strEqualCIN(), KviSmartTextCodec::ok(), KviCString::ptr(), KviPointerHashTable< Key, T >::replace(), and KviCString::replaceAll().
Referenced by KviApplication::defaultSrvCodec(), KviApplication::defaultTextCodec(), KviMessageCatalogue::load(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcConnection::setEncoding(), KviWindow::setTextEncoding(), KviApplication::setup(), KviIrcConnection::setupSrvCodec(), and KviIrcConnection::setupTextCodec().
unsigned int KviLocale::count () [inline]
Returns the number of instances of the class.
Returns:
unsigned int
Referenced by done(), and init().
void KviLocale::done () [static]
Destroys the class instance.
Parameters:
pApp The main application
Returns:
void
References count(), m_pSelf, and m_uCount.
KviLocale::EncodingDescription * KviLocale::encodingDescription (int iIdx)
Returns the description of the encoding used.
Parameters:
iIdx The index of the description
Warning:
You MUST start iterating from 0 and terminate when you get an entry with a NULL pcName
Returns:
EncodingDescription *
References KVI_NUM_ENCODINGS.
Referenced by KviWindow::createSystemTextEncodingPopup(), IrcServerDetailsWidget::fillData(), IrcNetworkDetailsWidget::fillData(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), and OptionsWidget_textEncoding::OptionsWidget_textEncoding().
const char * KviLocale::encodingGroup (int iIdx)
Returns the description of the encoding used.
Parameters:
iIdx The index of the group
Warning:
You MUST start iterating from 0 and terminate when you get an entry with a NULL value
Returns:
const char *
References encoding_groups, and KVI_NUM_ENCODING_GROUPS.
Referenced by KviWindow::createSystemTextEncodingPopup().
bool KviLocale::findCatalogue (QString & szBuffer, const QString & szName, const QString & szLocaleDir)
Finds the catalogue.
This function attempts to determine the current locale and then load the corresponding translation file from the KVIrc locale directory. Returns true if the locale was correctly set; i.e. the locale is C or POSIX (no translation needed) or the locale is correctly defined and the translation map was sucesfully loaded
Parameters:
szBuffer The buffer where to store the translation full path
szName The name of the translation file
szLocaleDir The directory where the localizations are stored
Returns:
bool
References KviCString::cutFromFirst(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), KviCString::findFirstIdx(), g_szLang, KVI_PATH_SEPARATOR_CHAR, KviCString::ptr(), and KviCString::toLower().
Referenced by KviLocale(), and loadCatalogue().
KviMessageCatalogue * KviLocale::getLoadedCatalogue (const QString & szName)
Returns the loaded catalogue.
Parameters:
szName The name of the catalogue to get
Returns:
KviMessageCatalogue *
References KviPointerHashTable< Key, T >::find().
Referenced by KviKvsCoreFunctions::KVSCF().
void KviLocale::init (QApplication * pApp, const QString & szLocaleDir, const QString & szForceLocaleDir) [static]
Initializes the class instance.
Parameters:
pApp The main application
szLocaleDir The directory containing the localizations
szForceLocaleDir The directory forced by the user
Returns:
void
References count(), KviLocale(), m_pSelf, and m_uCount.
static KviLocale* KviLocale::instance () [inline, static]
Returns the instance of the class.
Returns:
KviLocale *
Referenced by KviWindow::createSystemTextEncodingPopup(), KviApplication::defaultSrvCodec(), KviApplication::defaultTextCodec(), IrcServerDetailsWidget::fillData(), IrcNetworkDetailsWidget::fillData(), KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviMessageCatalogue::load(), KviModuleManager::loadModule(), TipWindow::nextTip(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), KviIrcServerParser::parseNumericCodePageSet(), TipWindow::prevTip(), KviIrcConnection::setEncoding(), KviWindow::setTextEncoding(), KviApplication::setup(), KviMenuBar::setupHelpPopup(), KviIrcConnection::setupSrvCodec(), KviIrcConnection::setupTextCodec(), and KviModuleManager::unloadModule().
KviMessageCatalogue * KviLocale::loadCatalogue (const QString & szName, const QString & szLocaleDir)
Loads the catalogue.
Parameters:
szName The name of the catalogue
szLocaleDir The directory where to look for the catalogue
Returns:
KviMessageCatalogue *
References KviPointerHashTable< Key, T >::find(), findCatalogue(), KviPointerHashTable< Key, T >::insert(), KviMessageCatalogue::load(), NULL, and szBuffer.
Referenced by KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviModuleManager::loadModule(), translate(), and translateToQString().
const KviCString& KviLocale::localeName () [inline]
Returns the language code of the localization.
Returns:
const KviCString &
Referenced by KviApplication::getLocalKvircDirectory(), TipWindow::nextTip(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), and TipWindow::prevTip().
const char * KviLocale::translate (const char * pcText, const char * pcContext)
Translates the given text from the given context.
Parameters:
pcText The text to translate
pcContext The context where to look for the text
Returns:
const char *
References KviPointerHashTable< Key, T >::find(), g_pMainCatalogue, g_szDefaultLocalePath, KviPointerHashTable< Key, T >::insert(), loadCatalogue(), and KviMessageCatalogue::translate().
const QString & KviLocale::translateToQString (const char * pcText, const char * pcContext)
Translates the given text from the given context.
Parameters:
pcText The text to translate
pcContext The context where to look for the text
Returns:
const QString &
References KviPointerHashTable< Key, T >::find(), g_pMainCatalogue, g_szDefaultLocalePath, KviPointerHashTable< Key, T >::insert(), loadCatalogue(), and KviMessageCatalogue::translateToQString().
bool KviLocale::unloadCatalogue (const QString & szName)
Unloads a catalogue.
Parameters:
szName The catalogue to unload
Returns:
bool
References KviPointerHashTable< Key, T >::remove().
Referenced by KviModuleManager::loadModule(), and KviModuleManager::unloadModule().
Member Data Documentation
KviCString KviLocale::g_szLang = "" [static]
Referenced by findCatalogue(), and KviLocale().
QApplication* KviLocale::m_pApp [protected]
Referenced by KviLocale(), and ~KviLocale().
KviLocale * KviLocale::m_pSelf = NULL [static, private]
Referenced by done(), and init().
unsigned int KviLocale::m_uCount = 0 [static, private]
Referenced by done(), and init().
The documentation for this class was generated from the following files:
src/kvilib/locale/KviLocale.h
src/kvilib/locale/KviLocale.cpp