KVIrc: KviModuleExtensionDescriptor Class Reference
KviModuleExtensionDescriptor Class Reference
#include <KviModuleExtension.h>
Public Member Functions
KviModuleExtension * allocate (KviWindow *pWnd=0, KviPointerHashTable< QString, QVariant > *pParams=0, void *pSpecial=0)
const KviCString & author ()
const KviCString & description ()
int flags ()
const QPixmap * icon ()
int id ()
KviModule * module ()
const KviCString & name ()
void setAuthor (const KviCString &szAuthor)
void setDescription (const KviCString &szDescription)
void setFlags (int iFlags)
void setIcon (const QPixmap &pix)
void setVisibleName (const KviCString &szVisibleName)
const KviCString & type ()
const QString & visibleName ()
~KviModuleExtensionDescriptor ()
Protected Member Functions
KviModuleExtensionDescriptor (KviModule *m, const KviCString &szType, const KviCString &szName, const QString &szVisibleName, KviModuleExtensionAllocRoutine r, const QPixmap &pix)
void registerObject (KviModuleExtension *e)
void unregisterObject (KviModuleExtension *e)
Private Attributes
KviModuleExtensionAllocRoutine m_allocRoutine
int m_iFlags
int m_iId
QPixmap * m_pIcon
KviModule * m_pModule
KviPointerList
< KviModuleExtension > * m_pObjectList
KviCString m_szAuthor
KviCString m_szDescription
KviCString m_szName
KviCString m_szType
QString m_szVisibleName
Friends
class KviModuleExtension
class KviModuleExtensionManager
Constructor & Destructor Documentation
KviModuleExtensionDescriptor::KviModuleExtensionDescriptor (KviModule * m, const KviCString & szType, const KviCString & szName, const QString & szVisibleName, KviModuleExtensionAllocRoutine r, const QPixmap & pix) [protected]
References KviApplication::getGloballyUniqueId(), m, m_allocRoutine, m_iId, m_pIcon, m_pModule, m_pObjectList, m_szName, m_szType, m_szVisibleName, r, and KviPointerList< T >::setAutoDelete().
KviModuleExtensionDescriptor::~KviModuleExtensionDescriptor ()
References e, KviPointerList< T >::first(), m_pIcon, and m_pObjectList.
Member Function Documentation
KviModuleExtension * KviModuleExtensionDescriptor::allocate (KviWindow * pWnd = 0, KviPointerHashTable< QString, QVariant > * pParams = 0, void * pSpecial = 0)
References m_allocRoutine, _KviModuleExtensionAllocStructTag::pDescriptor, _KviModuleExtensionAllocStructTag::pParams, _KviModuleExtensionAllocStructTag::pSpecial, _KviModuleExtensionAllocStructTag::pWindow, and s.
Referenced by KviModuleExtensionManager::allocateExtension(), and filetransferwindow_kvs_cmd_open().
const KviCString& KviModuleExtensionDescriptor::author () [inline]
const KviCString& KviModuleExtensionDescriptor::description () [inline]
int KviModuleExtensionDescriptor::flags () [inline]
const QPixmap* KviModuleExtensionDescriptor::icon () [inline]
int KviModuleExtensionDescriptor::id () [inline]
References m_iId.
Referenced by KviModuleExtensionManager::allocateExtension().
KviModule* KviModuleExtensionDescriptor::module () [inline]
const KviCString& KviModuleExtensionDescriptor::name () [inline]
Referenced by KviModuleExtensionManager::allocateExtension().
void KviModuleExtensionDescriptor::registerObject (KviModuleExtension * e) [protected]
References KviPointerList< T >::append(), and m_pObjectList.
Referenced by KviModuleExtension::KviModuleExtension().
void KviModuleExtensionDescriptor::setAuthor (const KviCString & szAuthor) [inline]
void KviModuleExtensionDescriptor::setDescription (const KviCString & szDescription) [inline]
void KviModuleExtensionDescriptor::setFlags (int iFlags) [inline]
void KviModuleExtensionDescriptor::setIcon (const QPixmap & pix)
References m_pIcon.
Referenced by filetransferwindow_module_init(), and mircimport_module_init().
void KviModuleExtensionDescriptor::setVisibleName (const KviCString & szVisibleName) [inline]
const KviCString& KviModuleExtensionDescriptor::type () [inline]
void KviModuleExtensionDescriptor::unregisterObject (KviModuleExtension * e) [protected]
References m_pObjectList, and KviPointerList< T >::removeRef().
Referenced by KviModuleExtension::~KviModuleExtension().
const QString& KviModuleExtensionDescriptor::visibleName () [inline]
Friends And Related Function Documentation
friend class KviModuleExtension [friend]
friend class KviModuleExtensionManager [friend]
Member Data Documentation
KviModuleExtensionAllocRoutine KviModuleExtensionDescriptor::m_allocRoutine [private]
Referenced by allocate(), and KviModuleExtensionDescriptor().
int KviModuleExtensionDescriptor::m_iFlags [private]
int KviModuleExtensionDescriptor::m_iId [private]
Referenced by KviModuleExtensionDescriptor().
QPixmap* KviModuleExtensionDescriptor::m_pIcon [private]
Referenced by KviModuleExtensionDescriptor(), setIcon(), and ~KviModuleExtensionDescriptor().
KviModule* KviModuleExtensionDescriptor::m_pModule [private]
Referenced by KviModuleExtensionDescriptor().
KviPointerList<KviModuleExtension>* KviModuleExtensionDescriptor::m_pObjectList [private]
Referenced by KviModuleExtensionDescriptor(), registerObject(), unregisterObject(), and ~KviModuleExtensionDescriptor().
KviCString KviModuleExtensionDescriptor::m_szAuthor [private]
KviCString KviModuleExtensionDescriptor::m_szDescription [private]
KviCString KviModuleExtensionDescriptor::m_szName [private]
Referenced by KviModuleExtensionDescriptor().
KviCString KviModuleExtensionDescriptor::m_szType [private]
Referenced by KviModuleExtensionDescriptor().
QString KviModuleExtensionDescriptor::m_szVisibleName [private]
Referenced by KviModuleExtensionDescriptor().
The documentation for this class was generated from the following files:
src/kvirc/module/KviModuleExtension.h
src/kvirc/module/KviModuleExtension.cpp