KVIrc: KviKvsObjectStandardFalseReturnFunctionHandler Class Reference
KviKvsObjectStandardFalseReturnFunctionHandler Class Reference
#include <KviKvsObjectFunctionHandlerImpl.h>
Public Member Functions
virtual ~KviKvsObjectStandardFalseReturnFunctionHandler ()
Public Member Functions inherited from KviKvsObjectFunctionHandler
unsigned int flags ()
bool isClone ()
void setClone (bool bCl)
virtual ~KviKvsObjectFunctionHandler ()
Protected Member Functions
virtual bool call (KviKvsObject *pObject, KviKvsObjectFunctionCall *pCall)
virtual
KviKvsObjectFunctionHandler * clone ()
KviKvsObjectStandardFalseReturnFunctionHandler ()
Protected Member Functions inherited from KviKvsObjectFunctionHandler
virtual bool isScriptHandler ()
KviKvsObjectFunctionHandler (unsigned int uFlags=0)
virtual QString reminder ()
virtual QString scriptHandlerCode ()
virtual void setReminder (const QString &szReminder)
Friends
class KviKvsObject
class KviKvsObjectClass
Additional Inherited Members
Public Types inherited from KviKvsObjectFunctionHandler
enum Flags { Internal = 1 }
Protected Attributes inherited from KviKvsObjectFunctionHandler
bool m_bClone
unsigned int m_uFlags
Constructor & Destructor Documentation
KviKvsObjectStandardFalseReturnFunctionHandler::KviKvsObjectStandardFalseReturnFunctionHandler () inline protected
Referenced by clone().
virtual KviKvsObjectStandardFalseReturnFunctionHandler::~KviKvsObjectStandardFalseReturnFunctionHandler () inline virtual
Member Function Documentation
bool KviKvsObjectStandardFalseReturnFunctionHandler::call (KviKvsObject * pObject, KviKvsObjectFunctionCall * pCall) protected virtual
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
KviKvsObjectFunctionHandler * KviKvsObjectStandardFalseReturnFunctionHandler::clone () protected virtual
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectStandardFalseReturnFunctionHandler().
Friends And Related Function Documentation
friend class KviKvsObject friend
friend class KviKvsObjectClass friend
The documentation for this class was generated from the following files:
src/kvirc/kvs/object/KviKvsObjectFunctionHandlerImpl.h
src/kvirc/kvs/object/KviKvsObjectFunctionHandlerImpl.cpp