KVIrc: KviIrcConnectionStateData Class Reference
KviIrcConnectionStateData Class Reference
#include <KviIrcConnectionStateData.h>
Public Member Functions
void changeEnabledCapList (const QString &szCapList)
const QString & commandToExecAfterConnect ()
const QStringList & enabledCaps ()
bool identifyMsgCapabilityEnabled () const
bool ignoreOneYouHaveNotRegisteredError () const
bool isInsideAuthenticate ()
bool isInsideInitialCapLs ()
bool isInsideInitialCapReq ()
bool isInsideInitialStartTls ()
KviIrcConnectionStateData ()
kvi_time_t lastReceivedChannelWhoReply ()
kvi_time_t lastReceivedWhoisReply ()
kvi_time_t lastSentChannelWhoRequest ()
const LoginNickNameState & loginNickNameState () const
bool sentQuit ()
bool sentStartTls ()
void setCommandToExecAfterConnect (const QString &szCmd)
void setIgnoreOneYouHaveNotRegisteredError (bool bIgnore)
void setInsideAuthenticate (bool bInside)
void setInsideInitialCapLs (bool bInside)
void setInsideInitialCapReq (bool bInside)
void setInsideInitialStartTls (bool bInside)
void setLastReceivedChannelWhoReply (kvi_time_t tTime)
void setLastReceivedWhoisReply (kvi_time_t tTime)
void setLastSentChannelWhoRequest (kvi_time_t tTime)
void setLoginNickNameState (const LoginNickNameState &eLoginNickNameState)
void setSentQuit ()
void setSentStartTls ()
void setSimulateUnexpectedDisconnect (bool bSimulate)
bool simulateUnexpectedDisconnect ()
~KviIrcConnectionStateData ()
Protected Types
enum LoginNickNameState {
UsedConnectionSpecificNickName, UsedProfileSpecificNickName, UsedAlternativeProfileSpecificNickName, UsedServerSpecificNickName,
UsedAlternativeServerSpecificNickName, UsedNetworkSpecificNickName, UsedAlternativeNetworkSpecificNickName, UsedGlobalNickName1,
UsedGlobalNickName2, UsedGlobalNickName3, UsedGlobalNickName4, UsedRandomNickName1,
UsedRandomNickName2, UsedRandomNickName3, UsedRandomNickName4, UsedManualNickname
}
Protected Attributes
bool m_bIdentifyMsgCapabilityEnabled
bool m_bIgnoreOneYouHaveNotRegisteredError
bool m_bInsideAuthenticate
bool m_bInsideInitialCapLs
bool m_bInsideInitialCapReq
bool m_bInsideInitialStartTls
bool m_bSentQuit
bool m_bSentStartTls
bool m_bSimulateUnexpectedDisconnect
LoginNickNameState m_eLoginNickNameState
QStringList m_lEnabledCaps
QString m_szCommandToExecAfterConnect
kvi_time_t m_tLastReceivedChannelWhoReply
kvi_time_t m_tLastReceivedWhoisReply
kvi_time_t m_tLastSentChannelWhoRequest
Friends
class KviIrcConnection
class KviIrcServerParser
class KviUserParser
Member Enumeration Documentation
enum KviIrcConnectionStateData::LoginNickNameState protected
Enumerator:
UsedConnectionSpecificNickName
UsedProfileSpecificNickName
UsedAlternativeProfileSpecificNickName
UsedServerSpecificNickName
UsedAlternativeServerSpecificNickName
UsedNetworkSpecificNickName
UsedAlternativeNetworkSpecificNickName
UsedGlobalNickName1
UsedGlobalNickName2
UsedGlobalNickName3
UsedGlobalNickName4
UsedRandomNickName1
UsedRandomNickName2
UsedRandomNickName3
UsedRandomNickName4
UsedManualNickname
Constructor & Destructor Documentation
KviIrcConnectionStateData::KviIrcConnectionStateData ()
References kvi_unixTime, m_bIdentifyMsgCapabilityEnabled, m_bIgnoreOneYouHaveNotRegisteredError, m_bInsideInitialCapLs, m_bInsideInitialCapReq, m_bInsideInitialStartTls, m_bSentQuit, m_bSentStartTls, m_bSimulateUnexpectedDisconnect, m_eLoginNickNameState, m_tLastReceivedChannelWhoReply, m_tLastReceivedWhoisReply, m_tLastSentChannelWhoRequest, and UsedConnectionSpecificNickName.
KviIrcConnectionStateData::~KviIrcConnectionStateData ()
Member Function Documentation
void KviIrcConnectionStateData::changeEnabledCapList (const QString & szCapList)
References m_bIdentifyMsgCapabilityEnabled, and m_lEnabledCaps.
Referenced by KviIrcServerParser::parseLiteralCap().
const QString& KviIrcConnectionStateData::commandToExecAfterConnect () inline
Referenced by KviIrcConnection::loginComplete().
const QStringList& KviIrcConnectionStateData::enabledCaps () inline
Referenced by KviIrcConnection::handleInitialCapAck().
bool KviIrcConnectionStateData::identifyMsgCapabilityEnabled () const inline
Referenced by KviIrcServerParser::parseLiteralPrivmsg().
bool KviIrcConnectionStateData::ignoreOneYouHaveNotRegisteredError () const inline
Referenced by KviIrcServerParser::parseNumericNotRegistered().
bool KviIrcConnectionStateData::isInsideAuthenticate () inline
Referenced by KviIrcConnection::handleAuthenticate(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), and KviIrcServerParser::parseNumericSaslSuccess().
bool KviIrcConnectionStateData::isInsideInitialCapLs () inline
Referenced by KviIrcConnection::handleInitialCapLs(), KviIrcServerParser::parseLiteralCap(), and KviIrcServerParser::parseNumericNotRegistered().
bool KviIrcConnectionStateData::isInsideInitialCapReq () inline
Referenced by KviIrcConnection::handleInitialCapAck(), and KviIrcServerParser::parseLiteralCap().
bool KviIrcConnectionStateData::isInsideInitialStartTls () inline
Referenced by KviIrcServerParser::parseNumericNotRegistered().
kvi_time_t KviIrcConnectionStateData::lastReceivedChannelWhoReply () inline
kvi_time_t KviIrcConnectionStateData::lastReceivedWhoisReply () inline
Referenced by KviIrcServerParser::parseMessage().
kvi_time_t KviIrcConnectionStateData::lastSentChannelWhoRequest () inline
const LoginNickNameState& KviIrcConnectionStateData::loginNickNameState () const inline
Returns the current login nickname state
Referenced by KviIrcConnection::pickNextLoginNickName().
bool KviIrcConnectionStateData::sentQuit () inline
Referenced by KviIrcContext::connectionTerminated().
bool KviIrcConnectionStateData::sentStartTls () inline
Referenced by KviIrcServerParser::parseNumericStartTls().
void KviIrcConnectionStateData::setCommandToExecAfterConnect (const QString & szCmd) inline
Referenced by KviIrcContext::connectToCurrentServer().
void KviIrcConnectionStateData::setIgnoreOneYouHaveNotRegisteredError (bool bIgnore) inline
Referenced by KviIrcConnection::linkEstabilished(), KviIrcConnection::loginComplete(), and KviIrcServerParser::parseNumericNotRegistered().
void KviIrcConnectionStateData::setInsideAuthenticate (bool bInside) inline
Referenced by KviIrcConnection::endInitialCapNegotiation(), and KviIrcConnection::handleInitialCapAck().
void KviIrcConnectionStateData::setInsideInitialCapLs (bool bInside) inline
Referenced by KviIrcConnection::handleFailedInitialCapLs(), KviIrcConnection::handleInitialCapLs(), and KviIrcConnection::linkEstabilished().
void KviIrcConnectionStateData::setInsideInitialCapReq (bool bInside) inline
Referenced by KviIrcConnection::handleInitialCapAck(), and KviIrcConnection::handleInitialCapLs().
void KviIrcConnectionStateData::setInsideInitialStartTls (bool bInside) inline
Referenced by KviIrcConnection::linkEstabilished().
void KviIrcConnectionStateData::setLastReceivedChannelWhoReply (kvi_time_t tTime) inline
Referenced by KviIrcServerParser::parseNumericEndOfWho().
void KviIrcConnectionStateData::setLastReceivedWhoisReply (kvi_time_t tTime) inline
Referenced by KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), and KviIrcServerParser::parseNumericWhoisUser().
void KviIrcConnectionStateData::setLastSentChannelWhoRequest (kvi_time_t tTime) inline
Referenced by KviIrcConnection::heartbeat(), and KviIrcConnectionRequestQueue::timerSlot().
void KviIrcConnectionStateData::setLoginNickNameState (const LoginNickNameState & eLoginNickNameState) inline
Sets the current login nickname state
Referenced by KviIrcConnection::loginToIrcServer(), and KviIrcConnection::pickNextLoginNickName().
void KviIrcConnectionStateData::setSentQuit () inline
Referenced by KviIrcContext::terminateConnectionRequest().
void KviIrcConnectionStateData::setSentStartTls () inline
void KviIrcConnectionStateData::setSimulateUnexpectedDisconnect (bool bSimulate) inline
Referenced by KviIrcContext::terminateConnectionRequest().
bool KviIrcConnectionStateData::simulateUnexpectedDisconnect () inline
Referenced by KviIrcContext::connectionTerminated().
Friends And Related Function Documentation
friend class KviIrcConnection friend
friend class KviIrcServerParser friend
friend class KviUserParser friend
Member Data Documentation
bool KviIrcConnectionStateData::m_bIdentifyMsgCapabilityEnabled protected
Referenced by changeEnabledCapList(), and KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bIgnoreOneYouHaveNotRegisteredError protected
Referenced by KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bInsideAuthenticate protected
bool KviIrcConnectionStateData::m_bInsideInitialCapLs protected
Referenced by KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bInsideInitialCapReq protected
Referenced by KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bInsideInitialStartTls protected
This is set to true if a forced STARTTLS request has been sent to the server followed by a PING. We use this flag to gracefully handle a ERR_NOTREGISTERED related to the PING if STARTTLS is not supported.
Note that in this case the STARTTLS support wasn't detected by a previous CAP LS (which wasn't sent at all).
Referenced by KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bSentQuit protected
Referenced by KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bSentStartTls protected
Referenced by KviIrcConnectionStateData().
bool KviIrcConnectionStateData::m_bSimulateUnexpectedDisconnect protected
Referenced by KviIrcConnectionStateData().
LoginNickNameState KviIrcConnectionStateData::m_eLoginNickNameState protected
the current login nickname state
Referenced by KviIrcConnectionStateData().
QStringList KviIrcConnectionStateData::m_lEnabledCaps protected
Referenced by changeEnabledCapList().
QString KviIrcConnectionStateData::m_szCommandToExecAfterConnect protected
kvi_time_t KviIrcConnectionStateData::m_tLastReceivedChannelWhoReply protected
Referenced by KviIrcConnectionStateData().
kvi_time_t KviIrcConnectionStateData::m_tLastReceivedWhoisReply protected
Referenced by KviIrcConnectionStateData().
kvi_time_t KviIrcConnectionStateData::m_tLastSentChannelWhoRequest protected
Referenced by KviIrcConnectionStateData().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionStateData.h
src/kvirc/kernel/KviIrcConnectionStateData.cpp