KVIrc: Kopete::AV::VideoDevicePool Class Reference
Kopete::AV::VideoDevicePool Class Reference
#include <videodevicepool.h>
Signals
void deviceRegistered (const QString &udi)
void deviceUnregistered (const QString &udi)
Public Member Functions
int close ()
Closes the device.
int currentDevice ()
Returns the index of the current device.
QString currentDeviceUdi ()
Returns the unique device identifier (UDI) of the currently selected device.
int currentInput ()
Returns the index of the currently selected input.
void fillDeviceQComboBox (QComboBox *combobox)
void fillInputQComboBox (QComboBox *combobox)
void fillStandardQComboBox (QComboBox *combobox)
int getControlValue (quint32 ctrl_id, qint32 *value)
Reads the value of a video-control.
int getFrame ()
int getImage (QImage *qimage)
QList< ActionVideoControl > getSupportedActionControls ()
Returns the supported action-controls for the current input.
QList< BooleanVideoControl > getSupportedBooleanControls ()
Returns the supported boolean controls for the current input.
QList< MenuVideoControl > getSupportedMenuControls ()
Returns the supported menu-controls for the current input.
QList< NumericVideoControl > getSupportedNumericControls ()
Returns the supported numeric controls for the current input.
int height ()
int inputs ()
Returns the number of available inputs of the currently selected device.
bool isOpen ()
Returns true if the currently selected device is open and false othwerise.
int maxHeight ()
int maxWidth ()
int minHeight ()
int minWidth ()
int open (int device=-1)
Opens the video device with the specified index. The previously opened device is closed before.
void saveCurrentDeviceConfig ()
Saves the current device configuration.
int selectInput (int newinput)
Selects the input of the current video device.
int setControlValue (quint32 ctrl_id, qint32 value)
Sets the value of a video-control.
int setImageSize (int newwidth, int newheight)
int size ()
Returns the number of available video devices.
int startCapturing ()
Starts capturing from the currently selected video device.
int stopCapturing ()
Starts capturing from the currently selected video device.
int width ()
~VideoDevicePool ()
Destructor of class VideoDevicePool.
Static Public Member Functions
static VideoDevicePool * self ()
Returns pointer to a common instance of the VideoDevicePool.
Protected Slots
void deviceAdded (const QString &udi)
Checks the device with the specified UDI and adds to the device pool, if it is a valid video device.
void deviceRemoved (const QString &udi)
Removes the device with the specified UDI from the device pool.
Protected Member Functions
int getSavedDevice ()
Returns the index of the saved device.
void loadDeviceConfig ()
Loads and applies the configuration for the currently selected device.
int showDeviceCapabilities (int device=-1)
Protected Attributes
int m_current_device
QVector< VideoDevice * > m_videodevices
Private Member Functions
VideoDevicePool ()
Constructor of class VideoDevicePool.
Static Private Attributes
static __u64 m_clients = 0
static VideoDevicePool * s_self = NULL
Detailed Description
This class allows kopete to check for the existence, open, configure, test, set parameters, grab frames from and close a given video capture card using the Video4Linux API.
Author:
Cláudio da Silveira Pinheiro
Constructor & Destructor Documentation
Kopete::AV::VideoDevicePool::~VideoDevicePool ()
Destructor of class VideoDevicePool.
References m_videodevices.
Kopete::AV::VideoDevicePool::VideoDevicePool () [private]
Constructor of class VideoDevicePool.
References connect(), deviceAdded(), and deviceRemoved().
Referenced by self().
Member Function Documentation
int Kopete::AV::VideoDevicePool::close ()
Closes the device.
Returns:
The success of the operation: EXIT_SUCCESS or EXIT_FAILURE
References m_clients, m_current_device, and m_videodevices.
Referenced by open(), saveCurrentDeviceConfig(), and DccVideoThread::~DccVideoThread().
int Kopete::AV::VideoDevicePool::currentDevice ()
Returns the index of the current device.
Returns:
The index of the current device or -1 if no device available
References m_current_device, and m_videodevices.
QString Kopete::AV::VideoDevicePool::currentDeviceUdi ()
Returns the unique device identifier (UDI) of the currently selected device.
Returns:
The unique device identifier (UDI) of the currently selected device
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::currentInput ()
Returns the index of the currently selected input.
Returns:
The index of the currently selected input or -1, if no input is available
References m_current_device, and m_videodevices.
Referenced by fillInputQComboBox(), fillStandardQComboBox(), loadDeviceConfig(), and saveCurrentDeviceConfig().
void Kopete::AV::VideoDevicePool::deviceAdded (const QString & udi) [protected, slot]
Checks the device with the specified UDI and adds to the device pool, if it is a valid video device.
Slot called when a new device is added to the system
Parameters:
udi Unique device identifier (UDI) of the device that has been connected
References deviceRegistered().
Referenced by VideoDevicePool().
void Kopete::AV::VideoDevicePool::deviceRegistered (const QString & udi) [signal]
Provisional signatures, probably more useful to indicate which device was registered
Referenced by deviceAdded().
void Kopete::AV::VideoDevicePool::deviceRemoved (const QString & udi) [protected, slot]
Removes the device with the specified UDI from the device pool.
Parameters:
udi Unique device identifier (UDI) of the device that has been unplugged
References deviceUnregistered(), i, m_clients, m_current_device, m_videodevices, and Kopete::AV::VideoDevice::udi().
Referenced by VideoDevicePool().
void Kopete::AV::VideoDevicePool::deviceUnregistered (const QString & udi) [signal]
Referenced by deviceRemoved().
void Kopete::AV::VideoDevicePool::fillDeviceQComboBox (QComboBox * combobox)
References m_current_device, m_videodevices, and NULL.
Referenced by DccVideoWindow::connected(), DccVideoWindow::deviceRegistered(), and DccVideoWindow::deviceUnregistered().
void Kopete::AV::VideoDevicePool::fillInputQComboBox (QComboBox * combobox)
References currentInput(), inputs(), m_current_device, m_videodevices, KviOsInfo::name(), and NULL.
Referenced by DccVideoWindow::connected(), DccVideoWindow::deviceRegistered(), and DccVideoWindow::deviceUnregistered().
void Kopete::AV::VideoDevicePool::fillStandardQComboBox (QComboBox * combobox)
References currentInput(), inputs(), m_current_device, m_videodevices, and NULL.
Referenced by DccVideoWindow::connected(), DccVideoWindow::deviceRegistered(), and DccVideoWindow::deviceUnregistered().
int Kopete::AV::VideoDevicePool::getControlValue (quint32 ctrl_id, qint32 * value)
Reads the value of a video-control.
Parameters:
ctrl_id ID of the video-control
value Pointer to the variable, which recieves the value of the querried video-control. For boolean controls, the value is 0 or 1. For menu-controls, the value is the index of the currently selected option.
Returns:
The result-code, currently EXIT_SUCCESS or EXIT_FAILURE
References m_current_device, and m_videodevices.
Referenced by saveCurrentDeviceConfig().
int Kopete::AV::VideoDevicePool::getFrame ()
References m_current_device, and m_videodevices.
Referenced by DccVideoThread::videoStep().
int Kopete::AV::VideoDevicePool::getImage (QImage * qimage)
References m_current_device, and m_videodevices.
Referenced by DccVideoThread::videoStep().
int Kopete::AV::VideoDevicePool::getSavedDevice () [protected]
Returns the index of the saved device.
Returns:
The index of the saved device or -1, if the saved device is not available
References config(), and m_videodevices.
Referenced by open().
QList< ActionVideoControl > Kopete::AV::VideoDevicePool::getSupportedActionControls ()
Returns the supported action-controls for the current input.
Returns:
A list of all supported action-controls for the current input
References m_current_device, and m_videodevices.
QList< BooleanVideoControl > Kopete::AV::VideoDevicePool::getSupportedBooleanControls ()
Returns the supported boolean controls for the current input.
Returns:
A list of all supported boolean controls for the current input
References m_current_device, and m_videodevices.
QList< MenuVideoControl > Kopete::AV::VideoDevicePool::getSupportedMenuControls ()
Returns the supported menu-controls for the current input.
Returns:
A list of all supported menu-controls for the current input
References m_current_device, and m_videodevices.
QList< NumericVideoControl > Kopete::AV::VideoDevicePool::getSupportedNumericControls ()
Returns the supported numeric controls for the current input.
Returns:
A list of all supported numeric controls for the current input
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::height ()
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::inputs ()
Returns the number of available inputs of the currently selected device.
Returns:
The number of inputs of the currently selected device
References m_current_device, and m_videodevices.
Referenced by fillInputQComboBox(), and fillStandardQComboBox().
bool Kopete::AV::VideoDevicePool::isOpen ()
Returns true if the currently selected device is open and false othwerise.
Returns:
True if the device is open, false otherwise
References m_current_device, and m_videodevices.
Referenced by open(), and saveCurrentDeviceConfig().
void Kopete::AV::VideoDevicePool::loadDeviceConfig () [protected]
Loads and applies the configuration for the currently selected device.
Loads the input and the values for all video-controls and applies them.
References config(), currentInput(), m_current_device, and m_videodevices.
Referenced by open().
int Kopete::AV::VideoDevicePool::maxHeight ()
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::maxWidth ()
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::minHeight ()
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::minWidth ()
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::open (int device = -1)
Opens the video device with the specified index. The previously opened device is closed before.
Parameters:
device Index of the device that should be opened. If a negative index is passed (default), the default device will be opened, which is either the saved device (if available) or alternatively the device with index 0.
Returns:
The result-code, EXIT_SUCCESS or EXIT_FAILURE
References close(), getSavedDevice(), isOpen(), loadDeviceConfig(), m_clients, m_current_device, and m_videodevices.
Referenced by DccVideoThread::DccVideoThread(), DccVideoWindow::deviceRegistered(), DccVideoThread::restartRecording(), and saveCurrentDeviceConfig().
void Kopete::AV::VideoDevicePool::saveCurrentDeviceConfig ()
Saves the current device configuration.
Saves the current device, the current input and the current values for all supported video-controls.
References close(), config(), currentInput(), getControlValue(), Kopete::AV::ActionVideoControl::id, isOpen(), m_current_device, m_videodevices, KviOsInfo::name(), and open().
int Kopete::AV::VideoDevicePool::selectInput (int input)
Selects the input of the current video device.
Parameters:
input Index of input to be selected
Returns:
The result-code, EXIT_SUCCESS or EXIT_FAILURE
References m_current_device, and m_videodevices.
Referenced by DccVideoThread::restartRecording().
VideoDevicePool * Kopete::AV::VideoDevicePool::self () [static]
Returns pointer to a common instance of the VideoDevicePool.
Returns:
Pointer to the VideoDevicePool object
References m_clients, NULL, s_self, and VideoDevicePool().
Referenced by DccVideoThread::DccVideoThread(), and DccVideoThread::restartRecording().
int Kopete::AV::VideoDevicePool::setControlValue (quint32 ctrl_id, qint32 value)
Sets the value of a video-control.
Parameters:
ctrl_id ID of the video-control
value The value that should be set. For boolean controls, the value must be 0 or 1. For menu-controls, the value must be the index of the option. For action-controls, the value is ignored.
Returns:
The result-code, currently EXIT_SUCCESS or EXIT_FAILURE
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::setImageSize (int newwidth, int newheight)
References m_current_device, and m_videodevices.
Referenced by DccVideoThread::DccVideoThread(), DccVideoWindow::deviceRegistered(), and DccVideoThread::restartRecording().
int Kopete::AV::VideoDevicePool::showDeviceCapabilities (int device = -1) [protected]
References m_current_device, and m_videodevices.
int Kopete::AV::VideoDevicePool::size ()
Returns the number of available video devices.
Returns:
The number of available video devices
References m_videodevices.
Referenced by DccVideoWindow::deviceRegistered().
int Kopete::AV::VideoDevicePool::startCapturing ()
Starts capturing from the currently selected video device.
Returns:
The result-code, EXIT_SUCCESS or EXIT_FAILURE
References m_current_device, and m_videodevices.
Referenced by DccVideoWindow::deviceRegistered(), DccVideoThread::restartRecording(), and DccVideoThread::startRecording().
int Kopete::AV::VideoDevicePool::stopCapturing ()
Starts capturing from the currently selected video device.
Returns:
The result-code, EXIT_SUCCESS or EXIT_FAILURE
References m_current_device, and m_videodevices.
Referenced by DccVideoThread::restartRecording().
int Kopete::AV::VideoDevicePool::width ()
References m_current_device, and m_videodevices.
Member Data Documentation
__u64 Kopete::AV::VideoDevicePool::m_clients = 0 [static, private]
Referenced by close(), deviceRemoved(), open(), and self().
int Kopete::AV::VideoDevicePool::m_current_device [protected]
Referenced by close(), currentDevice(), currentDeviceUdi(), currentInput(), deviceRemoved(), fillDeviceQComboBox(), fillInputQComboBox(), fillStandardQComboBox(), getControlValue(), getFrame(), getImage(), getSupportedActionControls(), getSupportedBooleanControls(), getSupportedMenuControls(), getSupportedNumericControls(), height(), inputs(), isOpen(), loadDeviceConfig(), maxHeight(), maxWidth(), minHeight(), minWidth(), open(), saveCurrentDeviceConfig(), selectInput(), setControlValue(), setImageSize(), showDeviceCapabilities(), startCapturing(), stopCapturing(), and width().
QVector<VideoDevice*> Kopete::AV::VideoDevicePool::m_videodevices [protected]
Vector of pointers to the available video devices
Referenced by close(), currentDevice(), currentDeviceUdi(), currentInput(), deviceRemoved(), fillDeviceQComboBox(), fillInputQComboBox(), fillStandardQComboBox(), getControlValue(), getFrame(), getImage(), getSavedDevice(), getSupportedActionControls(), getSupportedBooleanControls(), getSupportedMenuControls(), getSupportedNumericControls(), height(), inputs(), isOpen(), loadDeviceConfig(), maxHeight(), maxWidth(), minHeight(), minWidth(), open(), saveCurrentDeviceConfig(), selectInput(), setControlValue(), setImageSize(), showDeviceCapabilities(), size(), startCapturing(), stopCapturing(), width(), and ~VideoDevicePool().
VideoDevicePool * Kopete::AV::VideoDevicePool::s_self = NULL [static, private]
Referenced by self().
The documentation for this class was generated from the following files:
src/kvilib/ext/avdevice/videodevicepool.h
src/kvilib/ext/avdevice/videodevicepool.cpp