KVIrc: OptionsWidget_theme Class Reference
OptionsWidget_theme Class Reference
#include <OptionsWidget_theme.h>
Public Member Functions
OptionsWidget_theme (QWidget *parent)
~OptionsWidget_theme ()
Constructor & Destructor Documentation
OptionsWidget_theme::OptionsWidget_theme (QWidget * parent)
References __tr2qs_ctx(), KviTalToolTip::add(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addRowSpacer(), connect(), KviOptionsWidget::createLayout(), f, KVI_OPTION_BOOL, KviOption_boolShowIconsInPopupMenus, KviOption_boolUseGlobalApplicationFont, and KviOption_fontApplication.
OptionsWidget_theme::~OptionsWidget_theme ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_theme.h
src/modules/options/OptionsWidget_theme.cpp