KVIrc: KviKvsTreeNodeOperationDecrement Class Reference
KviKvsTreeNodeOperationDecrement Class Reference
#include <KviKvsTreeNodeOperation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationDecrement (const QChar *pLocation)
~KviKvsTreeNodeOperationDecrement ()
Constructor & Destructor Documentation
KviKvsTreeNodeOperationDecrement::KviKvsTreeNodeOperationDecrement (const QChar * pLocation)
KviKvsTreeNodeOperationDecrement::~KviKvsTreeNodeOperationDecrement ()
Member Function Documentation
void KviKvsTreeNodeOperationDecrement::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationDecrement::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationDecrement::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsVariant::asReal(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeOperation::m_pTargetData, KviKvsRWEvaluationResult::result(), KviKvsVariant::setInteger(), KviKvsVariant::setReal(), and v.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.h
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.cpp