KVIrc: KviSubmenuAction Class Reference
KviSubmenuAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
virtual QAction * addToCustomToolBar (KviCustomToolBar *pTool)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
KviSubmenuAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIcoNId=QString(), unsigned int uFlags=0)
~KviSubmenuAction ()
Public Member Functions inherited from KviKvsAction
virtual void activate ()
Executes the action.
KviKvsAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Contructs the action object.
const QString & scriptCode ()
Returns the code of the script contained in the action.
virtual ~KviKvsAction ()
Destroys the action object.
Public Member Functions inherited from KviAction
QPixmap * bigIcon ()
Returns the big icon associated to the action.
const QString & bigIconId () const
Returns the id of the big icon associated to the action.
KviActionCategory * category () const
Returns the category of the action.
virtual const QString & description ()
Returns the description of the action.
unsigned int flags ()
Returns the flag associated to the action.
bool isEnabled () const
Returns true if the action is enabled.
virtual bool isKviUserActionNeverOverrideThis ()
Returns true if the action is user-defined.
const QString & keySequence () const
Returns the shortcut of the action.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const KviIconManager::SmallIcon eIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
const QString & name () const
Returns the name of the action.
virtual void setEnabled (bool bEnabled)
Enables the action.
QPixmap * smallIcon ()
Returns the small icon associated to the action.
const QString & smallIconId () const
Returns the id of the small icon associated to the action.
void suicide ()
Destroys itself. Maybe the best function in the whole APIs :)
virtual const QString & visibleName ()
Returns the visible name of the action.
virtual ~KviAction ()
Destroys the action object.
Protected Slots
virtual void popupAboutToShow ()
virtual void popupActivated (QAction *pAction)
Protected Member Functions
virtual void setup ()
Enables or disables the action upon starting KVIrc.
Protected Attributes
QMenu * m_pPopup
Protected Attributes inherited from KviKvsAction
QString m_szScript
Protected Attributes inherited from KviAction
QString m_eIcon
QPointer< QShortcut > m_pAccel
KviPointerList< QAction > * m_pActionList
KviActionCategory * m_pCategory
QString m_szBigIconId
QString m_szDescription
QString m_szKeySequence
QString m_szName
QString m_szSmallIconId
QString m_szVisibleName
unsigned int m_uFlags
unsigned short int m_uInternalFlags
Constructor & Destructor Documentation
KviSubmenuAction::KviSubmenuAction (QObject * pParent, const QString & szName, const QString & szScriptCode, const QString & szVisibleName, const QString & szDescription, KviActionCategory * pCategory = NULL, const QString & szBigIconId = QString(), const QString & szSmallIcoNId = QString(), unsigned int uFlags = 0)
References m_pPopup.
KviSubmenuAction::~KviSubmenuAction ()
References m_pPopup.
Member Function Documentation
QAction * KviSubmenuAction::addToCustomToolBar (KviCustomToolBar * pParentToolBar) virtual
Adds the action to the given toolbar.
Parameters:
pParentToolBar The toolbar where to add the action
Returns:
QAction *
Reimplemented from KviAction.
References KviKvsAction::activate(), KviAction::bigIcon(), connect(), KviAction::isEnabled(), m_pPopup, KviAction::name(), p, KviAction::registerAction(), KviKvsAction::scriptCode(), setup(), KviAction::setupDone(), and KviAction::visibleName().
bool KviSubmenuAction::addToPopupMenu (QMenu * pMenu) virtual
Adds the action to the given popup.
Parameters:
pMenu The menu where to add the action
Returns:
bool
Reimplemented from KviAction.
References KviAction::isEnabled(), m_pPopup, setup(), KviAction::setupDone(), KviAction::smallIcon(), and KviAction::visibleName().
void KviSubmenuAction::popupAboutToShow () protected virtual slot
Reimplemented in KviIrcOperationsAction, KviIrcToolsAction, KviChangeUserModeAction, KviConnectToServerAction, KviChangeNickAction, and KviJoinChannelAction.
Referenced by setup().
void KviSubmenuAction::popupActivated (QAction * pAction) protected virtual slot
Reimplemented in KviIrcOperationsAction, KviIrcToolsAction, KviChangeUserModeAction, KviConnectToServerAction, KviChangeNickAction, and KviJoinChannelAction.
Referenced by setup().
void KviSubmenuAction::setup () protected virtual
Enables or disables the action upon starting KVIrc.
Returns:
void
Reimplemented from KviAction.
References connect(), m_pPopup, popupAboutToShow(), and popupActivated().
Referenced by addToCustomToolBar(), and addToPopupMenu().
Member Data Documentation
QMenu* KviSubmenuAction::m_pPopup protected
Referenced by addToCustomToolBar(), addToPopupMenu(), KviSubmenuAction(), KviJoinChannelAction::popupAboutToShow(), KviChangeNickAction::popupAboutToShow(), KviConnectToServerAction::popupAboutToShow(), KviChangeUserModeAction::popupAboutToShow(), KviIrcToolsAction::popupAboutToShow(), KviIrcOperationsAction::popupAboutToShow(), setup(), and ~KviSubmenuAction().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp