KVIrc: AliasEditorTreeWidgetItem Class Reference
AliasEditorTreeWidgetItem Class Reference
#include <AliasEditorWindow.h>
Public Types
enum Type { Alias, Namespace }
Public Member Functions
AliasEditorTreeWidgetItem (QTreeWidget *pTreeWidget, Type eType, const QString &szName)
AliasEditorTreeWidgetItem (AliasEditorTreeWidgetItem *pParentItem, Type eType, const QString &szName)
const QString & buffer ()
const int & cursorPosition ()
bool isAlias ()
bool isNamespace ()
const QString & name ()
AliasEditorTreeWidgetItem * parentItem ()
void setBuffer (const QString &szBuffer)
void setCursorPosition (const int &cPos)
void setName (const QString &szName)
void setParentItem (AliasEditorTreeWidgetItem *it)
void setType (Type t)
Type type ()
~AliasEditorTreeWidgetItem ()
Protected Attributes
int m_cPos
Type m_eType
AliasEditorTreeWidgetItem * m_pParentItem
QString m_szBuffer
QString m_szName
Member Enumeration Documentation
enum AliasEditorTreeWidgetItem::Type
Enumerator:
Alias
Namespace
Constructor & Destructor Documentation
AliasEditorTreeWidgetItem::AliasEditorTreeWidgetItem (QTreeWidget * pTreeWidget, Type eType, const QString & szName)
References KviIconManager::Alias, g_pIconManager, KviIconManager::getSmallIcon(), m_cPos, KviIconManager::NameSpace, Namespace, and setName().
AliasEditorTreeWidgetItem::AliasEditorTreeWidgetItem (AliasEditorTreeWidgetItem * pParentItem, Type eType, const QString & szName)
References KviIconManager::Alias, g_pIconManager, KviIconManager::getSmallIcon(), m_cPos, KviIconManager::NameSpace, Namespace, and setName().
AliasEditorTreeWidgetItem::~AliasEditorTreeWidgetItem () [inline]
Member Function Documentation
const QString& AliasEditorTreeWidgetItem::buffer () [inline]
References m_szBuffer.
Referenced by AliasEditorWidget::commit(), AliasEditorWidget::getExportAliasBuffer(), and AliasEditorWidget::searchReplace().
const int& AliasEditorTreeWidgetItem::cursorPosition () [inline]
References m_cPos.
bool AliasEditorTreeWidgetItem::isAlias () [inline]
References Alias, and m_eType.
Referenced by AliasEditorWidget::buildFullItemPath(), AliasEditorWidget::removeItem(), and AliasEditorWidget::renameItem().
bool AliasEditorTreeWidgetItem::isNamespace () [inline]
References m_eType, and Namespace.
Referenced by AliasEditorWidget::currentItemChanged(), AliasEditorWidget::findTopLevelItem(), and AliasEditorWidget::saveLastEditedItem().
const QString& AliasEditorTreeWidgetItem::name () [inline]
References m_szName.
Referenced by AliasEditorWidget::buildFullItemName(), AliasEditorWidget::buildFullItemPath(), and AliasEditorWidget::removeItem().
AliasEditorTreeWidgetItem* AliasEditorTreeWidgetItem::parentItem () [inline]
References m_pParentItem.
Referenced by AliasEditorWidget::buildFullItemName(), and AliasEditorWidget::buildFullItemPath().
void AliasEditorTreeWidgetItem::setBuffer (const QString & szBuffer) [inline]
References m_szBuffer, and szBuffer.
Referenced by AliasEditorWidget::aliasRefresh(), AliasEditorWidget::oneTimeSetup(), and AliasEditorWidget::renameItem().
void AliasEditorTreeWidgetItem::setCursorPosition (const int & cPos) [inline]
References m_cPos.
Referenced by AliasEditorWidget::renameItem().
void AliasEditorTreeWidgetItem::setName (const QString & szName)
References m_szName.
Referenced by AliasEditorTreeWidgetItem().
void AliasEditorTreeWidgetItem::setParentItem (AliasEditorTreeWidgetItem * it) [inline]
References m_pParentItem.
void AliasEditorTreeWidgetItem::setType (Type t)
References KviIconManager::Alias, g_pIconManager, KviIconManager::getSmallIcon(), m_eType, KviIconManager::NameSpace, Namespace, and t().
Referenced by AliasEditorWidget::newItem().
Type AliasEditorTreeWidgetItem::type () [inline]
References m_eType.
Member Data Documentation
int AliasEditorTreeWidgetItem::m_cPos [protected]
Referenced by AliasEditorTreeWidgetItem(), cursorPosition(), and setCursorPosition().
Type AliasEditorTreeWidgetItem::m_eType [protected]
Referenced by isAlias(), isNamespace(), setType(), and type().
AliasEditorTreeWidgetItem* AliasEditorTreeWidgetItem::m_pParentItem [protected]
Referenced by parentItem(), and setParentItem().
QString AliasEditorTreeWidgetItem::m_szBuffer [protected]
Referenced by buffer(), and setBuffer().
QString AliasEditorTreeWidgetItem::m_szName [protected]
Referenced by name(), and setName().
The documentation for this class was generated from the following files:
src/modules/aliaseditor/AliasEditorWindow.h
src/modules/aliaseditor/AliasEditorWindow.cpp