KVIrc: ScriptEditorReplaceDialog Class Reference
ScriptEditorReplaceDialog Class Reference
#include <ScriptEditorImplementation.h>
Signals
void initFind ()
void nextFind (const QString &)
void replaceAll (const QString &, const QString &)
Public Member Functions
ScriptEditorReplaceDialog (QWidget *parent=0, const QString &szName=QString())
~ScriptEditorReplaceDialog ()
Public Attributes
QLineEdit * m_pFindLineEdit
QLineEdit * m_pReplaceLineEdit
Protected Slots
void slotNextFind ()
void slotReplace ()
void textChanged (const QString &)
Protected Attributes
QCheckBox * m_pCheckReplaceAll
QWidget * m_pParent
QPushButton * m_pReplaceButton
Constructor & Destructor Documentation
ScriptEditorReplaceDialog::ScriptEditorReplaceDialog (QWidget * parent = 0, const QString & szName = QString())
References __tr2qs_ctx(), connect(), initFind(), m_pCheckReplaceAll, m_pFindLineEdit, m_pParent, m_pReplaceButton, m_pReplaceLineEdit, p, slotReplace(), and textChanged().
ScriptEditorReplaceDialog::~ScriptEditorReplaceDialog ()
Member Function Documentation
void ScriptEditorReplaceDialog::initFind () [signal]
Referenced by ScriptEditorReplaceDialog().
void ScriptEditorReplaceDialog::nextFind (const QString &) [signal]
Referenced by slotNextFind().
void ScriptEditorReplaceDialog::replaceAll (const QString & , const QString &) [signal]
Referenced by slotReplace().
void ScriptEditorReplaceDialog::slotNextFind () [protected, slot]
References m_pFindLineEdit, and nextFind().
void ScriptEditorReplaceDialog::slotReplace () [protected, slot]
References m_pCheckReplaceAll, m_pFindLineEdit, m_pParent, m_pReplaceLineEdit, and replaceAll().
Referenced by ScriptEditorReplaceDialog().
void ScriptEditorReplaceDialog::textChanged (const QString & szText) [protected, slot]
References m_pReplaceButton.
Referenced by ScriptEditorReplaceDialog().
Member Data Documentation
QCheckBox* ScriptEditorReplaceDialog::m_pCheckReplaceAll [protected]
Referenced by ScriptEditorReplaceDialog(), and slotReplace().
QLineEdit* ScriptEditorReplaceDialog::m_pFindLineEdit
Referenced by ScriptEditorReplaceDialog(), slotNextFind(), and slotReplace().
QWidget* ScriptEditorReplaceDialog::m_pParent [protected]
Referenced by ScriptEditorReplaceDialog(), and slotReplace().
QPushButton* ScriptEditorReplaceDialog::m_pReplaceButton [protected]
Referenced by ScriptEditorReplaceDialog(), and textChanged().
QLineEdit* ScriptEditorReplaceDialog::m_pReplaceLineEdit
Referenced by ScriptEditorReplaceDialog(), and slotReplace().
The documentation for this class was generated from the following files:
src/modules/editor/ScriptEditorImplementation.h
src/modules/editor/ScriptEditorImplementation.cpp