KVIrc: KviIrcContext Class Reference
KviIrcContext Class Reference
#include <KviIrcContext.h>
Public Types
enum State { Idle, Connecting, LoggingIn, Connected }
Public Slots
void closeAllDeadChannels ()
void closeAllDeadQueries ()
Signals
void stateChanged ()
Public Member Functions
KviAsynchronousConnectionData * asynchronousConnectionData ()
void beginAsynchronousConnect (unsigned int uDelayInMSecs)
void closeAllContextWindows ()
KviIrcConnection * connection ()
void connectOrDisconnect ()
void connectToCurrentServer ()
KviConsoleWindow * console ()
void createLinksWindow ()
void createListWindow ()
void destroyAsynchronousConnectionData ()
KviChannelWindow * findDeadChannel (const QString &name)
KviQueryWindow * findDeadQuery (const QString &nick)
KviChannelWindow * firstDeadChannel ()
KviQueryWindow * firstDeadQuery ()
KviMainWindow * frame ()
unsigned int id ()
bool isConnected ()
bool isLoggingIn ()
KviExternalServerDataParser * linksWindow ()
KviExternalServerDataParser * listWindow ()
KviPointerList
< KviIrcDataStreamMonitor > * monitorList ()
void registerContextWindow (KviWindow *pWnd)
void registerDataStreamMonitor (KviIrcDataStreamMonitor *m)
void registerDeadChannel (KviChannelWindow *c)
void registerDeadQuery (KviQueryWindow *q)
void setAsynchronousConnectionData (KviAsynchronousConnectionData *d)
void setLinksWindowPointer (KviExternalServerDataParser *l)
void setListWindowPointer (KviExternalServerDataParser *l)
State state ()
void terminateConnectionRequest (bool bForce, const QString &szQuitMessage=QString(), bool bSimulateUnexpectedDisconnect=false)
bool unregisterContextWindow (KviWindow *pWnd)
void unregisterDataStreamMonitor (KviIrcDataStreamMonitor *m)
bool unregisterDeadChannel (KviChannelWindow *c)
bool unregisterDeadQuery (KviQueryWindow *q)
~KviIrcContext ()
Protected Slots
void asynchronousConnect ()
Protected Member Functions
void connectButtonClicked ()
void connectionEstabilished ()
void connectionFailed (int iError)
void connectionTerminated ()
void destroyConnection ()
KviIrcContext (KviConsoleWindow *pConsole)
void loginComplete ()
void setState (State eState)
virtual void timerEvent (QTimerEvent *e)
Protected Attributes
State m_eState
int m_iHeartbeatTimerId
KviAsynchronousConnectionData * m_pAsynchronousConnectionData
KviIrcConnection * m_pConnection
KviConsoleWindow * m_pConsole
KviPointerList< KviWindow > * m_pContextWindows
KviPointerList
< KviChannelWindow > * m_pDeadChannels
KviPointerList< KviQueryWindow > * m_pDeadQueries
KviMainWindow * m_pFrame
KviExternalServerDataParser * m_pLinksWindow
KviExternalServerDataParser * m_pListWindow
KviPointerList
< KviIrcDataStreamMonitor > * m_pMonitorList
QTimer * m_pReconnectTimer
KviAsynchronousConnectionData * m_pSavedAsynchronousConnectionData
unsigned int m_uConnectAttemptCount
unsigned int m_uId
Friends
class KviChannelWindow
class KviConsoleWindow
class KviIrcConnection
class KviIrcContextToolBar
class KviQueryWindow
Member Enumeration Documentation
enum KviIrcContext::State
Enumerator:
Idle
Connecting
LoggingIn
Connected
Constructor & Destructor Documentation
KviIrcContext::KviIrcContext (KviConsoleWindow * pConsole) [protected]
References KviWindow::frame(), g_uNextIrcContextId, Idle, m_eState, m_iHeartbeatTimerId, m_pAsynchronousConnectionData, m_pConnection, m_pConsole, m_pContextWindows, m_pDeadChannels, m_pDeadQueries, m_pFrame, m_pLinksWindow, m_pListWindow, m_pMonitorList, m_pReconnectTimer, m_pSavedAsynchronousConnectionData, m_uConnectAttemptCount, and m_uId.
KviIrcContext::~KviIrcContext ()
References closeAllContextWindows(), closeAllDeadChannels(), closeAllDeadQueries(), destroyConnection(), KviExternalServerDataParser::die(), KviIrcDataStreamMonitor::die(), KviPointerList< T >::first(), m, m_iHeartbeatTimerId, m_pAsynchronousConnectionData, m_pLinksWindow, m_pListWindow, m_pMonitorList, m_pReconnectTimer, and m_pSavedAsynchronousConnectionData.
Member Function Documentation
void KviIrcContext::asynchronousConnect () [protected, slot]
References connectToCurrentServer(), m_pReconnectTimer, state(), and terminateConnectionRequest().
Referenced by beginAsynchronousConnect().
KviAsynchronousConnectionData* KviIrcContext::asynchronousConnectionData () [inline]
void KviIrcContext::beginAsynchronousConnect (unsigned int uDelayInMSecs)
References asynchronousConnect(), connect(), and m_pReconnectTimer.
Referenced by connectionFailed(), and connectionTerminated().
void KviIrcContext::closeAllContextWindows ()
References KviMainWindow::closeWindow(), KviPointerList< T >::first(), m_pContextWindows, m_pFrame, and w.
Referenced by ~KviIrcContext().
void KviIrcContext::closeAllDeadChannels () [slot]
References c, KviMainWindow::closeWindow(), KviPointerList< T >::first(), m_pDeadChannels, and m_pFrame.
Referenced by ~KviIrcContext().
void KviIrcContext::closeAllDeadQueries () [slot]
References KviMainWindow::closeWindow(), KviPointerList< T >::first(), m_pDeadQueries, m_pFrame, and q.
Referenced by ~KviIrcContext().
void KviIrcContext::connectButtonClicked () [protected]
References __tr2qs, connection(), connectToCurrentServer(), destroyAsynchronousConnectionData(), KVI_OUT_SYSTEMERROR, m_pConsole, m_pReconnectTimer, m_uConnectAttemptCount, KviWindow::outputNoFmt(), and terminateConnectionRequest().
KviIrcConnection* KviIrcContext::connection () [inline]
Referenced by KviMainWindow::activeConnection(), KviGoAwayAction::activeContextStateChanged(), KviGoAwayAction::addToPopupMenu(), connectButtonClicked(), KviWindow::connection(), KviConsoleWindow::connectionAttached(), connectionEstabilished(), connectionFailed(), connectionTerminated(), KviStatusBar::mouseDoubleClickEvent(), KviStatusBar::setPermanentMessage(), terminateConnectionRequest(), KviStatusBarConnectionTimer::timerEvent(), KviStatusBarLagIndicator::updateDisplay(), and KviStatusBarAwayIndicator::updateDisplay().
void KviIrcContext::connectionEstabilished () [protected]
References __tr2qs, KviApplication::addRecentServer(), connection(), g_pApp, KviIrcUrl::join(), KVI_OUT_CONNECTION, KviEvent_OnIRCConnectionEstabilished, KVS_TRIGGER_EVENT_0_HALTED, LoggingIn, m_pConsole, m_uConnectAttemptCount, KviWindow::output(), setState(), and KviWindow::target().
Referenced by KviIrcConnection::linkEstabilished().
void KviIrcContext::connectionFailed (int iError) [protected]
References __tr2qs, _OUTPUT_MUTE, beginAsynchronousConnect(), KviAsynchronousConnectionData::bPortIsOk, KviAsynchronousConnectionData::bSTARTTLS, KviAsynchronousConnectionData::bUseIPv6, KviAsynchronousConnectionData::bUseSSL, connection(), KviError::ConnectionRefused, KviError::ConnectionTimedOut, d, KviIrcServer::enabledSTARTTLS(), KviIrcServer::hostName(), KviError::HostUnreachable, KviIrcServer::id(), KviIrcServer::initUMode(), KviIrcConnectionUserInfo::isAway(), KviIrcServer::isIPv6(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviOption_boolAutoReconnectOnUnexpectedDisconnect, KviOption_uintAutoReconnectDelay, KviOption_uintMaxAutoReconnectAttempts, m_pConnection, m_pConsole, m_uConnectAttemptCount, KviError::NetworkUnreachable, KviIrcConnectionUserInfo::nickName(), KviIrcConnectionUserInfo::nickNameBeforeAway(), KviError::OperationAborted, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcServer::password(), KviIrcServer::port(), KviIrcConnectionTarget::server(), setAsynchronousConnectionData(), setState(), KviAsynchronousConnectionData::szCommandToExecAfterConnect, KviAsynchronousConnectionData::szInitUMode, KviAsynchronousConnectionData::szNick, KviAsynchronousConnectionData::szPass, KviAsynchronousConnectionData::szServer, KviAsynchronousConnectionData::szServerId, KviWindow::target(), KviIrcConnection::target(), KviAsynchronousConnectionData::uPort, KviIrcConnection::userInfo(), and KviIrcServer::useSSL().
Referenced by KviIrcConnection::linkAttemptFailed().
void KviIrcContext::connectionTerminated () [protected]
References __tr2qs, _OUTPUT_MUTE, KviIrcConnectionUserInfo::awayReason(), beginAsynchronousConnect(), KviAsynchronousConnectionData::bPortIsOk, KviAsynchronousConnectionData::bSTARTTLS, KviAsynchronousConnectionData::bUseIPv6, KviAsynchronousConnectionData::bUseSSL, c, KviIrcConnection::channelList(), KviChannelWindow::channelModeParam(), KviIrcConnectionRequestQueue::clearAll(), KviIrcServer::clearReconnectInfo(), Connected, Connecting, connection(), d, KviIrcServer::enabledSTARTTLS(), first(), KviChannelWindow::hasChannelMode(), KviIrcServer::hostName(), KviIrcServer::id(), KviIrcServer::initUMode(), KviIrcServer::ip(), KviIrcConnectionUserInfo::isAway(), KviIrcServer::isIPv6(), KviIrcConnection::keepChannelsOpenAfterDisconnect(), KviIrcConnection::keepQueriesOpenAfterDisconnect(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_CONNECTION, KviEvent_OnIRCConnectionTerminated, KviOption_boolAutoReconnectOnUnexpectedDisconnect, KviOption_boolKeepChannelsOpenOnDisconnect, KviOption_boolKeepChannelsOpenOnUnexpectedDisconnect, KviOption_boolKeepQueriesOpenOnDisconnect, KviOption_boolKeepQueriesOpenOnUnexpectedDisconnect, KviOption_boolRejoinChannelsAfterReconnect, KviOption_boolReopenQueriesAfterReconnect, KviOption_uintAutoReconnectDelay, KVS_TRIGGER_EVENT_0_HALTED, KviIrcServerReconnectInfo::m_bIsAway, m_eState, m_pConnection, m_pConsole, KviAsynchronousConnectionData::m_pReconnectInfo, KviIrcServerReconnectInfo::m_szAwayReason, KviIrcServerReconnectInfo::m_szJoinChannels, KviIrcServerReconnectInfo::m_szNick, KviIrcServerReconnectInfo::m_szOpenQueryes, KviIrcServerReconnectInfo::m_szPass, KviPointerList< T >::next(), KviIrcConnectionUserInfo::nickName(), KviIrcConnectionUserInfo::nickNameBeforeAway(), KviWindow::output(), KviIrcServer::password(), KviIrcConnectionUserInfo::password(), KviIrcServer::port(), q, KviIrcConnection::queryList(), KviIrcConnection::requestQueue(), KviIrcConnectionStateData::sentQuit(), setAsynchronousConnectionData(), setState(), KviIrcConnectionStateData::simulateUnexpectedDisconnect(), KviIrcConnection::stateData(), KviAsynchronousConnectionData::szInitUMode, KviAsynchronousConnectionData::szPass, KviAsynchronousConnectionData::szServer, KviAsynchronousConnectionData::szServerId, KviWindow::target(), KviAsynchronousConnectionData::uPort, KviIrcConnection::userInfo(), KviIrcServer::useSSL(), and KviWindow::windowName().
Referenced by KviIrcConnection::linkTerminated().
void KviIrcContext::connectOrDisconnect () [inline]
Referenced by KviConnectAction::activate().
void KviIrcContext::connectToCurrentServer ()
References __tr2qs, _KviIrcServerDefinition::bIPv6, KviAsynchronousConnectionData::bPortIsOk, _KviIrcServerDefinition::bPortIsValid, _KviIrcServerDefinition::bSSL, _KviIrcServerDefinition::bSTARTTLS, KviAsynchronousConnectionData::bSTARTTLS, KviAsynchronousConnectionData::bUseIPv6, KviAsynchronousConnectionData::bUseLastServerInContext, KviAsynchronousConnectionData::bUseSSL, KviIrcServer::clearReconnectInfo(), Connecting, KviConsoleWindow::connectionAttached(), KviIrcServerDataBase::currentNetwork(), KviProxyDataBase::currentProxy(), KviIrcNetwork::currentServer(), d, KviUserIdentityManager::defaultIdentity(), destroyAsynchronousConnectionData(), KviIrcServer::enabledSTARTTLS(), KviUserIdentityManager::findIdentity(), g_pProxyDataBase, g_pServerDataBase, KviIrcServer::hostName(), KviIrcServer::id(), KviIrcServer::initUMode(), KviUserIdentityManager::instance(), KviIrcServer::isIPv6(), KVI_OPTION_BOOL, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviIrcConnection, KviOption_boolUseProxyHost, m_pAsynchronousConnectionData, m_pConnection, m_pConsole, KviAsynchronousConnectionData::m_pReconnectInfo, m_pReconnectTimer, m_pSavedAsynchronousConnectionData, KviIrcServerDataBase::makeCurrentServer(), KviIrcServerDataBase::networkCount(), KviWindow::outputNoFmt(), KviIrcServer::password(), KviIrcServer::port(), KviIrcServer::proxy(), KviIrcServer::proxyServer(), KviIrcServer::reconnectInfo(), KviKvsScript::run(), KviIrcConnectionStateData::setCommandToExecAfterConnect(), KviIrcServer::setReconnectInfo(), setState(), KviIrcConnection::start(), KviIrcConnection::stateData(), KviAsynchronousConnectionData::szBindAddress, KviAsynchronousConnectionData::szCommandToExecAfterConnect, _KviIrcServerDefinition::szId, _KviIrcServerDefinition::szInitUMode, KviAsynchronousConnectionData::szInitUMode, _KviIrcServerDefinition::szLinkFilter, KviAsynchronousConnectionData::szLinkFilter, _KviIrcServerDefinition::szNick, KviAsynchronousConnectionData::szNick, _KviIrcServerDefinition::szPass, KviAsynchronousConnectionData::szPass, _KviIrcServerDefinition::szServer, KviAsynchronousConnectionData::szServer, KviAsynchronousConnectionData::szServerId, _KviIrcServerDefinition::uPort, KviAsynchronousConnectionData::uPort, KviIrcNetwork::userIdentityId(), KviIrcServer::userIdentityId(), and KviIrcServer::useSSL().
Referenced by asynchronousConnect(), and connectButtonClicked().
KviConsoleWindow* KviIrcContext::console () [inline]
Referenced by KviIrcConnection::KviIrcConnection(), and terminateConnectionRequest().
void KviIrcContext::createLinksWindow ()
References m_pConsole, m_pLinksWindow, and KviIrcUrl::run().
Referenced by KviIrcServerParser::parseNumericLinks().
void KviIrcContext::createListWindow ()
References m_pConsole, m_pListWindow, and KviIrcUrl::run().
Referenced by KviIrcServerParser::parseNumericList(), and KviIrcServerParser::parseNumericListStart().
void KviIrcContext::destroyAsynchronousConnectionData ()
References m_pAsynchronousConnectionData.
Referenced by connectButtonClicked(), and connectToCurrentServer().
void KviIrcContext::destroyConnection () [protected]
References KviIrcConnection::closeAllChannels(), KviIrcConnection::closeAllQueries(), KviConsoleWindow::connectionDetached(), KviExternalServerDataParser::control(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_RESET, m_pConnection, m_pConsole, m_pLinksWindow, and m_pListWindow.
Referenced by setState(), and ~KviIrcContext().
KviChannelWindow * KviIrcContext::findDeadChannel (const QString & name)
References c, KviQString::equalCI(), KviPointerList< T >::first(), KVI_ASSERT, m_pDeadChannels, and KviPointerList< T >::next().
Referenced by KviIrcConnection::createChannel().
KviQueryWindow * KviIrcContext::findDeadQuery (const QString & nick)
References c, KviQString::equalCI(), KviPointerList< T >::first(), KVI_ASSERT, m_pDeadQueries, and KviPointerList< T >::next().
Referenced by KviIrcConnection::createQuery().
KviChannelWindow * KviIrcContext::firstDeadChannel ()
References KviPointerList< T >::first(), and m_pDeadChannels.
KviQueryWindow * KviIrcContext::firstDeadQuery ()
References KviPointerList< T >::first(), and m_pDeadQueries.
Referenced by KviIrcConnection::resurrectDeadQueries().
KviMainWindow* KviIrcContext::frame () [inline]
unsigned int KviIrcContext::id () [inline]
Referenced by dcc_kvs_fnc_ircContext(), KviWindowListButton::drawButtonLabel(), KviIrcContextDisplay::drawContents(), SocketSpyWindow::fillCaptionBuffers(), ListWindow::fillCaptionBuffers(), LinksWindow::fillCaptionBuffers(), TrayIcon::fillContextPopup(), KviApplication::findWindowByCaption(), KviQueryWindow::getBaseLogFileName(), KviTreeWindowListItemDelegate::paint(), KviIrcContextDisplay::tipRequest(), and window_kvs_fnc_list().
bool KviIrcContext::isConnected () [inline]
Referenced by KviConsoleWindow::isConnected(), KviStatusBarConnectionTimer::timerEvent(), KviStatusBarLagIndicator::updateDisplay(), and KviStatusBarAwayIndicator::updateDisplay().
bool KviIrcContext::isLoggingIn () [inline]
KviExternalServerDataParser* KviIrcContext::linksWindow () [inline]
Referenced by links_kvs_cmd_open(), KviIrcServerParser::parseNumericEndOfLinks(), and KviIrcServerParser::parseNumericLinks().
KviExternalServerDataParser* KviIrcContext::listWindow () [inline]
Referenced by list_kvs_cmd_open(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericListEnd(), and KviIrcServerParser::parseNumericListStart().
void KviIrcContext::loginComplete () [protected]
References Connected, and setState().
Referenced by KviIrcConnection::loginComplete().
KviPointerList<KviIrcDataStreamMonitor>* KviIrcContext::monitorList () [inline]
void KviIrcContext::registerContextWindow (KviWindow * pWnd)
References KviPointerList< T >::append(), m_pContextWindows, and KviPointerList< T >::setAutoDelete().
Referenced by UserWindow::UserWindow().
void KviIrcContext::registerDataStreamMonitor (KviIrcDataStreamMonitor * m)
References KviPointerList< T >::append(), m_pMonitorList, and KviPointerList< T >::setAutoDelete().
Referenced by KviIrcDataStreamMonitor::KviIrcDataStreamMonitor().
void KviIrcContext::registerDeadChannel (KviChannelWindow * c)
References KviPointerList< T >::append(), m_pDeadChannels, and KviPointerList< T >::setAutoDelete().
Referenced by KviChannelWindow::setDeadChan().
void KviIrcContext::registerDeadQuery (KviQueryWindow * q)
References KviPointerList< T >::append(), m_pDeadQueries, and KviPointerList< T >::setAutoDelete().
Referenced by KviQueryWindow::setDeadQuery().
void KviIrcContext::setAsynchronousConnectionData (KviAsynchronousConnectionData * d)
References d, and m_pAsynchronousConnectionData.
Referenced by connectionFailed(), and connectionTerminated().
void KviIrcContext::setLinksWindowPointer (KviExternalServerDataParser * l) [inline]
References l.
Referenced by LinksWindow::LinksWindow(), and LinksWindow::~LinksWindow().
void KviIrcContext::setListWindowPointer (KviExternalServerDataParser * l) [inline]
References l.
Referenced by ListWindow::ListWindow(), and ListWindow::~ListWindow().
void KviIrcContext::setState (State eState) [protected]
References KviMainWindow::childContextStateChange(), destroyConnection(), Idle, m_eState, m_pConsole, m_pFrame, stateChanged(), and KviWindow::updateCaption().
Referenced by connectionEstabilished(), connectionFailed(), connectionTerminated(), connectToCurrentServer(), and loginComplete().
State KviIrcContext::state () [inline]
Referenced by KviGoAwayAction::activeContextStateChanged(), KviConnectAction::activeContextStateChanged(), KviAction::activeContextStateChanged(), KviAction::activeWindowChanged(), KviGoAwayAction::addToPopupMenu(), KviConnectAction::addToPopupMenu(), asynchronousConnect(), KviConsoleWindow::closeEvent(), ListWindow::connectionStateChange(), LinksWindow::connectionStateChange(), KviStatusBar::mouseDoubleClickEvent(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviStatusBar::setPermanentMessage(), KviAction::setup(), KviMenuBar::setupMainPopup(), KviConsoleWindow::state(), and KviStatusBar::tipRequest().
void KviIrcContext::stateChanged () [signal]
Referenced by setState().
void KviIrcContext::terminateConnectionRequest (bool bForce, const QString & szQuitMessage = QString(), bool bSimulateUnexpectedDisconnect = false)
References __tr2qs, KviIrcConnection::abort(), KviKvsVariant::asString(), Connected, Connecting, connection(), console(), KviIrcConnection::encodeText(), KviQString::escapeKvs(), KviKvsScript::evaluate(), KVI_ASSERT, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_SYSTEMMESSAGE, KviEvent_OnDisconnectRequest, KviOption_boolForceBrutalQuit, KviOption_stringQuitMessage, KVS_TRIGGER_EVENT_0, LoggingIn, m_eState, m_pConsole, KviThread::msleep(), KviWindow::outputNoFmt(), KviQString::PermitFunctions, KviQString::PermitVariables, KviIrcConnection::sendFmtData(), KviIrcConnectionStateData::setSentQuit(), KviIrcConnectionStateData::setSimulateUnexpectedDisconnect(), and KviIrcConnection::stateData().
Referenced by asynchronousConnect(), KviConsoleWindow::closeEvent(), connectButtonClicked(), and KviConsoleWindow::~KviConsoleWindow().
void KviIrcContext::timerEvent (QTimerEvent * e) [protected, virtual]
References KviIrcConnection::heartbeat(), kvi_time_t, kvi_unixTime, m_iHeartbeatTimerId, and m_pConnection.
bool KviIrcContext::unregisterContextWindow (KviWindow * pWnd)
References KviPointerList< T >::isEmpty(), m_pContextWindows, and KviPointerList< T >::removeRef().
Referenced by UserWindow::~UserWindow().
void KviIrcContext::unregisterDataStreamMonitor (KviIrcDataStreamMonitor * m)
References KviPointerList< T >::isEmpty(), m_pMonitorList, and KviPointerList< T >::removeRef().
Referenced by KviIrcDataStreamMonitor::~KviIrcDataStreamMonitor().
bool KviIrcContext::unregisterDeadChannel (KviChannelWindow * c)
References KviPointerList< T >::isEmpty(), m_pDeadChannels, and KviPointerList< T >::removeRef().
Referenced by KviChannelWindow::closeEvent(), KviChannelWindow::setAliveChan(), and KviChannelWindow::~KviChannelWindow().
bool KviIrcContext::unregisterDeadQuery (KviQueryWindow * q)
References KviPointerList< T >::isEmpty(), m_pDeadQueries, and KviPointerList< T >::removeRef().
Referenced by KviQueryWindow::setAliveQuery(), and KviQueryWindow::~KviQueryWindow().
Friends And Related Function Documentation
friend class KviChannelWindow [friend]
friend class KviConsoleWindow [friend]
friend class KviIrcConnection [friend]
Referenced by connectToCurrentServer().
friend class KviIrcContextToolBar [friend]
friend class KviQueryWindow [friend]
Member Data Documentation
State KviIrcContext::m_eState [protected]
Referenced by connectionTerminated(), KviIrcContext(), setState(), and terminateConnectionRequest().
int KviIrcContext::m_iHeartbeatTimerId [protected]
Referenced by KviIrcContext(), timerEvent(), and ~KviIrcContext().
KviAsynchronousConnectionData* KviIrcContext::m_pAsynchronousConnectionData [protected]
Referenced by connectToCurrentServer(), destroyAsynchronousConnectionData(), KviIrcContext(), setAsynchronousConnectionData(), and ~KviIrcContext().
KviIrcConnection* KviIrcContext::m_pConnection [protected]
Referenced by connectionFailed(), connectionTerminated(), connectToCurrentServer(), destroyConnection(), KviIrcContext(), and timerEvent().
KviConsoleWindow* KviIrcContext::m_pConsole [protected]
Referenced by connectButtonClicked(), connectionEstabilished(), connectionFailed(), connectionTerminated(), connectToCurrentServer(), createLinksWindow(), createListWindow(), destroyConnection(), KviIrcContext(), setState(), and terminateConnectionRequest().
KviPointerList<KviWindow>* KviIrcContext::m_pContextWindows [protected]
Referenced by closeAllContextWindows(), KviIrcContext(), registerContextWindow(), and unregisterContextWindow().
KviPointerList<KviChannelWindow>* KviIrcContext::m_pDeadChannels [protected]
Referenced by closeAllDeadChannels(), findDeadChannel(), firstDeadChannel(), KviIrcContext(), registerDeadChannel(), and unregisterDeadChannel().
KviPointerList<KviQueryWindow>* KviIrcContext::m_pDeadQueries [protected]
Referenced by closeAllDeadQueries(), findDeadQuery(), firstDeadQuery(), KviIrcContext(), registerDeadQuery(), and unregisterDeadQuery().
KviMainWindow* KviIrcContext::m_pFrame [protected]
Referenced by closeAllContextWindows(), closeAllDeadChannels(), closeAllDeadQueries(), KviIrcContext(), and setState().
KviExternalServerDataParser* KviIrcContext::m_pLinksWindow [protected]
Referenced by createLinksWindow(), destroyConnection(), KviIrcContext(), and ~KviIrcContext().
KviExternalServerDataParser* KviIrcContext::m_pListWindow [protected]
Referenced by createListWindow(), destroyConnection(), KviIrcContext(), and ~KviIrcContext().
KviPointerList<KviIrcDataStreamMonitor>* KviIrcContext::m_pMonitorList [protected]
Referenced by KviIrcContext(), registerDataStreamMonitor(), unregisterDataStreamMonitor(), and ~KviIrcContext().
QTimer* KviIrcContext::m_pReconnectTimer [protected]
Referenced by asynchronousConnect(), beginAsynchronousConnect(), connectButtonClicked(), connectToCurrentServer(), KviIrcContext(), and ~KviIrcContext().
KviAsynchronousConnectionData* KviIrcContext::m_pSavedAsynchronousConnectionData [protected]
Referenced by connectToCurrentServer(), KviIrcContext(), and ~KviIrcContext().
unsigned int KviIrcContext::m_uConnectAttemptCount [protected]
Referenced by connectButtonClicked(), connectionEstabilished(), connectionFailed(), and KviIrcContext().
unsigned int KviIrcContext::m_uId [protected]
Referenced by KviIrcContext().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcContext.h
src/kvirc/kernel/KviIrcContext.cpp