KVIrc: KviKvsArrayCast Class Reference
KviKvsArrayCast Class Reference
#include <KviKvsArrayCast.h>
Public Member Functions
KviKvsArray * array ()
void clear ()
KviKvsArrayCast ()
void release ()
void set (KviKvsArray *pArry, bool bOwned)
~KviKvsArrayCast ()
Protected Attributes
bool m_bOwned
KviKvsArray * m_pArray
Constructor & Destructor Documentation
KviKvsArrayCast::KviKvsArrayCast () inline
KviKvsArrayCast::~KviKvsArrayCast ()
References m_bOwned, and m_pArray.
Member Function Documentation
KviKvsArray* KviKvsArrayCast::array () inline
Referenced by file_kvs_cmd_writeLines(), KviInputEditor::fillSpellCheckerCorrectionsPopup(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), str_kvs_fnc_grep(), str_kvs_fnc_join(), and theme_kvs_cmd_pack().
void KviKvsArrayCast::clear ()
References m_bOwned, and m_pArray.
void KviKvsArrayCast::release () inline
void KviKvsArrayCast::set (KviKvsArray * pArry, bool bOwned) inline
Referenced by KviKvsVariant::castToArray().
Member Data Documentation
bool KviKvsArrayCast::m_bOwned protected
Referenced by clear(), and ~KviKvsArrayCast().
KviKvsArray* KviKvsArrayCast::m_pArray protected
Referenced by clear(), and ~KviKvsArrayCast().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsArrayCast.h
src/kvirc/kvs/KviKvsArrayCast.cpp