KVIrc: OptionsWidget_ircViewFeatures Class Reference
OptionsWidget_ircViewFeatures Class Reference
#include <OptionsWidget_ircView.h>
Public Member Functions
OptionsWidget_ircViewFeatures (QWidget *parent)
~OptionsWidget_ircViewFeatures ()
Constructor & Destructor Documentation
OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::createLayout(), KviOption_boolEnableAnimatedSmiles, KviOption_boolEnableChannelLinkToolTip, KviOption_boolEnableEscapeLinkToolTip, KviOption_boolEnableHostLinkToolTip, KviOption_boolEnableModeLinkToolTip, KviOption_boolEnableNickLinkToolTip, KviOption_boolEnableServerLinkToolTip, KviOption_boolEnableUrlLinkToolTip, KviOption_boolIrcViewUrlHighlighting, KviOption_boolIrcViewWrapMargin, KviOption_uintIrcViewMaxBufferSize, KviOption_uintIrcViewToolTipHideTimeoutInMsec, KviOption_uintIrcViewToolTipTimeoutInMsec, s, and KviUIntSelector::setSuffix().
OptionsWidget_ircViewFeatures::~OptionsWidget_ircViewFeatures ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_ircView.h
src/modules/options/OptionsWidget_ircView.cpp