KVIrc: KviIrcConnectionAntiCtcpFloodData Class Reference
KviIrcConnectionAntiCtcpFloodData Class Reference
#include <kvi_ircconnectionantictcpflooddata.h>
Public Member Functions
unsigned int ctcpCount ()
void increaseCtcpCount ()
KviIrcConnectionAntiCtcpFloodData ()
kvi_time_t lastCtcpTime ()
void setCtcpCount (unsigned int uCtcpCount)
void setLastCtcpTime (kvi_time_t tLastCtcp)
~KviIrcConnectionAntiCtcpFloodData ()
Protected Attributes
kvi_time_t m_tLastCtcp
unsigned int m_uCtcpCount
Constructor & Destructor Documentation
KviIrcConnectionAntiCtcpFloodData::KviIrcConnectionAntiCtcpFloodData ()
References m_tLastCtcp, and m_uCtcpCount.
KviIrcConnectionAntiCtcpFloodData::~KviIrcConnectionAntiCtcpFloodData ()
Member Function Documentation
unsigned int KviIrcConnectionAntiCtcpFloodData::ctcpCount () [inline]
Referenced by KviServerParser::checkCtcpFlood().
void KviIrcConnectionAntiCtcpFloodData::increaseCtcpCount () [inline]
Referenced by KviServerParser::checkCtcpFlood().
kvi_time_t KviIrcConnectionAntiCtcpFloodData::lastCtcpTime () [inline]
Referenced by KviServerParser::checkCtcpFlood().
void KviIrcConnectionAntiCtcpFloodData::setCtcpCount (unsigned int uCtcpCount) [inline]
Referenced by KviServerParser::checkCtcpFlood().
void KviIrcConnectionAntiCtcpFloodData::setLastCtcpTime (kvi_time_t tLastCtcp) [inline]
Referenced by KviServerParser::checkCtcpFlood().
Member Data Documentation
kvi_time_t KviIrcConnectionAntiCtcpFloodData::m_tLastCtcp [protected]
Referenced by KviIrcConnectionAntiCtcpFloodData().
unsigned int KviIrcConnectionAntiCtcpFloodData::m_uCtcpCount [protected]
Referenced by KviIrcConnectionAntiCtcpFloodData().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnectionantictcpflooddata.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnectionantictcpflooddata.cpp