KVIrc: KviModule Class Reference
KviModule Class Reference
#include <KviModule.h>
Public Member Functions
bool ctrl (const char *operation, void *param)
const QString & filename ()
KviModuleExtensionDescriptor * findExtensionDescriptor (const KviCString &szType, const KviCString &szName)
void getDefaultConfigFileName (QString &szBuffer)
void * getSymbol (const char *symname)
QLibrary * handle ()
bool isLocked ()
void lock ()
KviModuleInfo * moduleInfo ()
const QString & name ()
KviModuleExtensionDescriptor * registerExtension (const KviCString &szType, const KviCString &szName, const QString &szVisibleName, KviModuleExtensionAllocRoutine r)
KviModuleExtensionDescriptor * registerExtension (const KviCString &szType, const KviCString &szName, const QString &szVisibleName, KviModuleExtensionAllocRoutine r, const QPixmap &icon)
void unlock ()
void unregisterAllExtensions ()
~KviModule ()
Public Member Functions inherited from KviKvsModuleInterface
void completeCommand (const QString &cmd, KviPointerList< QString > *matches)
void completeFunction (const QString &cmd, KviPointerList< QString > *matches)
void getAllFunctionsCommandsModule (QStringList *list, QString &szModuleName)
KviKvsModuleInterface ()
KviKvsModuleCallbackCommandExecRoutine * kvsFindCallbackCommand (const QString &szCommand)
KviKvsModuleFunctionExecRoutine * kvsFindFunction (const QString &szFunction)
KviKvsModuleSimpleCommandExecRoutine * kvsFindSimpleCommand (const QString &szCommand)
bool kvsRegisterAppEventHandler (unsigned int iEventIdx, KviKvsModuleEventHandlerRoutine r)
void kvsRegisterCallbackCommand (const QString &szCommand, KviKvsModuleCallbackCommandExecRoutine r)
void kvsRegisterFunction (const QString &szFunction, KviKvsModuleFunctionExecRoutine r)
bool kvsRegisterRawEventHandler (unsigned int iRawIdx, KviKvsModuleEventHandlerRoutine r)
void kvsRegisterSimpleCommand (const QString &szCommand, KviKvsModuleSimpleCommandExecRoutine r)
void kvsUnregisterAllAppEventHandlers ()
void kvsUnregisterAllCallbackCommands ()
void kvsUnregisterAllEventHandlers ()
void kvsUnregisterAllFunctions ()
void kvsUnregisterAllRawEventHandlers ()
void kvsUnregisterAllSimpleCommands ()
void kvsUnregisterAppEventHandler (unsigned int iEventIdx)
void kvsUnregisterCallbackCommand (const QString &szCommand)
void kvsUnregisterFunction (const QString &szFunction)
void kvsUnregisterRawEventHandler (unsigned int iRawIdx)
void kvsUnregisterSimpleCommand (const QString &szCommand)
~KviKvsModuleInterface ()
Static Public Member Functions
static void unregisterMetaObject (const char *metaObjName)
Protected Member Functions
KviModule (QLibrary *handle, KviModuleInfo *info, const QString &name, const QString &filename)
unsigned int secondsSinceLastAccess ()
void updateAccessTime ()
Protected Member Functions inherited from KviKvsModuleInterface
void registerDefaultCommands ()
Private Attributes
long int m_lastAccessTime
QLibrary * m_pLibrary
KviModuleInfo * m_pModuleInfo
QString m_szFileName
QString m_szName
unsigned int m_uLock
Friends
class KviModuleManager
class KviPointerHashTable< const char *, KviModule >
class KviUserParser
Additional Inherited Members
Protected Attributes inherited from KviKvsModuleInterface
KviPointerHashTable< QString,
KviKvsModuleCallbackCommandExecRoutine > * m_pModuleCallbackCommandExecRoutineDict
KviPointerHashTable< QString,
KviKvsModuleFunctionExecRoutine > * m_pModuleFunctionExecRoutineDict
KviPointerHashTable< QString,
KviKvsModuleSimpleCommandExecRoutine > * m_pModuleSimpleCommandExecRoutineDict
Constructor & Destructor Documentation
KviModule::KviModule (QLibrary * handle, KviModuleInfo * info, const QString & name, const QString & filename) protected
References filename(), handle(), m_lastAccessTime, m_pLibrary, m_pModuleInfo, m_szFileName, m_szName, m_uLock, and name().
KviModule::~KviModule ()
References m_pLibrary, and unregisterAllExtensions().
Member Function Documentation
bool KviModule::ctrl (const char * operation, void * param)
References _KviModuleInfo::ctrl_routine, and m_pModuleInfo.
Referenced by log_kvs_fnc_export(), OptionsWidget_soundGeneral::mediaAutoDetect(), OptionsWidget_soundGeneral::mediaFillBox(), KviApplication::notifierMessage(), perl_kvs_cmd_begin(), perl_kvs_cmd_destroy(), python_kvs_cmd_begin(), python_kvs_cmd_destroy(), OptionsWidget_soundGeneral::soundAutoDetect(), OptionsWidget_soundGeneral::soundFillBox(), and OptionsWidget_soundGeneral::soundTest().
const QString& KviModule::filename () inline
Referenced by KviModule().
KviModuleExtensionDescriptor * KviModule::findExtensionDescriptor (const KviCString & szType, const KviCString & szName)
References KviModuleExtensionManager::findExtensionDescriptor(), and g_pModuleExtensionManager.
void KviModule::getDefaultConfigFileName (QString & szBuffer)
References KviApplication::ConfigPlugins, g_pApp, KviApplication::getLocalKvircDirectory(), and m_szName.
Referenced by addon_module_cleanup(), addon_module_init(), channelsjoin_module_cleanup(), channelsjoin_module_init(), ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), theme_module_cleanup(), theme_module_init(), toolbareditor_module_cleanup(), and toolbareditor_module_init().
void * KviModule::getSymbol (const char * symname)
References m_pLibrary.
Referenced by KviScriptEditor::createInstance(), KviScriptEditor::destroyInstance(), and KviIrcServerParser::parseCtcpRequestDcc().
QLibrary* KviModule::handle () inline
Referenced by KviModule(), and KviModuleManager::unloadModule().
bool KviModule::isLocked () inline
Referenced by KviModuleManager::cleanupUnusedModules(), and default_module_kvs_cmd_unload().
void KviModule::lock () inline
Referenced by AliasEditorWidget::askForAliasName(), ClassEditorWidget::askForClassName(), ClassEditorWidget::askForFunction(), AliasEditorWidget::askForNamespaceName(), ClassEditorWidget::askForNamespaceName(), AliasEditorWidget::exportAliases(), ClassEditorWidget::exportClasses(), AliasEditorWidget::exportSelectionInSinglesFiles(), ClassEditorWidget::exportSelectionInSinglesFiles(), AliasEditorWidget::removeItem(), ClassEditorWidget::removeItem(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), AliasEditorWidget::renameItem(), ClassEditorWidget::renameNamespace(), AliasEditorWidget::slotFind(), ClassEditorWidget::slotFind(), and term_kvs_cmd_open().
KviModuleInfo* KviModule::moduleInfo () inline
Referenced by KviModuleManager::cleanupUnusedModules(), and KviModuleManager::unloadModule().
const QString& KviModule::name () inline
Referenced by default_module_kvs_cmd_unload(), KviModule(), and KviModuleManager::unloadModule().
KviModuleExtensionDescriptor * KviModule::registerExtension (const KviCString & szType, const KviCString & szName, const QString & szVisibleName, KviModuleExtensionAllocRoutine r)
References g_pModuleExtensionManager, and KviModuleExtensionManager::registerExtension().
Referenced by mircimport_module_init().
KviModuleExtensionDescriptor * KviModule::registerExtension (const KviCString & szType, const KviCString & szName, const QString & szVisibleName, KviModuleExtensionAllocRoutine r, const QPixmap & icon)
References g_pModuleExtensionManager, and KviModuleExtensionManager::registerExtension().
unsigned int KviModule::secondsSinceLastAccess () protected
References m_lastAccessTime.
Referenced by KviModuleManager::cleanupUnusedModules().
void KviModule::unlock () inline
Referenced by AliasEditorWidget::askForAliasName(), ClassEditorWidget::askForClassName(), ClassEditorWidget::askForFunction(), AliasEditorWidget::askForNamespaceName(), ClassEditorWidget::askForNamespaceName(), AliasEditorWidget::exportAliases(), ClassEditorWidget::exportClasses(), AliasEditorWidget::exportSelectionInSinglesFiles(), ClassEditorWidget::exportSelectionInSinglesFiles(), AliasEditorWidget::removeItem(), ClassEditorWidget::removeItem(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), AliasEditorWidget::renameItem(), ClassEditorWidget::renameNamespace(), AliasEditorWidget::slotFind(), and ClassEditorWidget::slotFind().
void KviModule::unregisterAllExtensions ()
References g_pModuleExtensionManager, and KviModuleExtensionManager::unregisterExtensionsByModule().
Referenced by ~KviModule().
static void KviModule::unregisterMetaObject (const char * metaObjName) static
void KviModule::updateAccessTime () protected
References m_lastAccessTime.
Referenced by KviModuleManager::cleanupUnusedModules(), KviModuleManager::findModule(), and KviModuleManager::getModule().
Friends And Related Function Documentation
friend class KviModuleManager friend
friend class KviPointerHashTable< const char *, KviModule > friend
friend class KviUserParser friend
Member Data Documentation
long int KviModule::m_lastAccessTime private
Referenced by KviModule(), secondsSinceLastAccess(), and updateAccessTime().
QLibrary* KviModule::m_pLibrary private
Referenced by getSymbol(), KviModule(), and ~KviModule().
KviModuleInfo* KviModule::m_pModuleInfo private
Referenced by ctrl(), and KviModule().
QString KviModule::m_szFileName private
Referenced by KviModule().
QString KviModule::m_szName private
Referenced by getDefaultConfigFileName(), KviModule(), lamerizer_module_init(), and rijndael_module_init().
unsigned int KviModule::m_uLock private
Referenced by KviModule().
The documentation for this class was generated from the following files:
src/kvirc/module/KviModule.h
src/kvirc/module/KviModule.cpp