KVIrc: KviApp Class Reference
KviApp Class Reference
#include <kvi_app.h>
Public Types
enum KvircSubdir {
None, Pics, Config, Help,
HelpEN, HelpNoIntl, Log, Incoming,
Audio, Scripts, Plugins, ConfigPlugins,
Trash, MsgColors, Charmaps, Avatars,
DefScript, License, Modules, ConfigScripts,
Filters, Tmp, Locale, Themes,
Classes, SmallIcons, EasyPlugins
}
Public Slots
void addRecentUrl (const QString &text)
void restoreDefaultScript ()
void saveConfiguration ()
Saves configuration to disk.
void updateGui ()
void updatePseudoTransparency ()
Signals
void recentUrlsChanged ()
void reloadImages ()
void updateNotifier ()
Public Member Functions
KviConsole * activeConsole ()
void addRecentChannel (const QString &chan, const QString &net)
void addRecentNickname (const QString &newNick)
void addRecentServer (const QString &server)
void autoConnectToServers ()
void checkSuggestRestoreDefaultScript ()
void completeDirectory (const QString &word, KviPointerList< QString > *matches)
bool connectionExists (KviIrcConnection *cnn)
void destroyFrame ()
void fileDownloadTerminated (bool bSuccess, const QString &szRemoteUrl, const QString &szLocalFileName, const QString &szNick=QString(), const QString &szError=QString(), bool bQuiet=false)
void fillRecentChannelsPopup (KviTalPopupMenu *m, KviConsole *pConsole)
void fillRecentNicknamesPopup (KviTalPopupMenu *m, KviConsole *pConsole)
void fillRecentServersPopup (KviTalPopupMenu *m)
bool findAudioFile (QString &szRetPath, const QString &szFileName)
KviConsole * findConsole (QString &servr, QString &nick)
KviConsole * findConsole (unsigned int ircContextId)
bool findImage (QString &szRetPath, const QString &filename)
bool findImageInImageSearchPath (QString &szRetPath, const QString &filename)
bool findImageThemeOnlyCompat (QString &szRetPath, const QString &filename)
KviPendingAvatarChange * findPendingAvatarChange (KviConsole *pConsole, const QString &szNick, const QString &szRemoteUrl)
bool findSmallIcon (QString &szRetPath, const QString &filename)
KviWindow * findWindow (const QString &windowId)
KviWindow * findWindowByCaption (const QString &windowCaption, int iContextId=-1)
bool firstTimeRun ()
void getChannelDumpLogFileName (QString &str)
void getGlobalKvircDirectory (QString &szData, KvircSubdir dir, const QString &appendFile=QString())
void getLocalKvircDirectory (QString &szData, KvircSubdir dir, const QString &appendFile=QString(), bool bCreateIfNeeded=true)
bool getOptionString (const QString &optName, QString &buffer)
bool getReadOnlyConfigPath (QString &buffer, const char *config_name, KvircSubdir sbd=Config, bool bNoFail=false)
void getTmpFileName (QString &szBuffer, const QString &szEndingFileName=QString())
void ipcMessage (char *message)
KviApp (int &argc, char **argv)
void listAvailableOptions (KviWindow *wnd)
void loadDefaultScript ()
void loadOptions ()
bool mapImageFile (QString &szRetPath, const QString &filename)
void notifierMessage (KviWindow *pWnd, int iIconId, const QString &szMsg, unsigned int uMessageLifetime)
void optionResetUpdate (int flags)
KviPointerHashTable< QString,
QStringList > * recentChannels () const
QStringList * recentChannelsForNetwork (const QString &net)
void resetAvatarForMatchingUsers (KviRegisteredUser *u)
void restartLagMeters ()
void restartNotifyLists ()
void saveActions ()
void saveAliases ()
void saveAppEvents ()
void saveAvatarCache ()
void saveIdentities ()
void saveIdentityProfiles ()
void saveInputHistory ()
void saveIrcServerDataBase ()
void saveMediaTypes ()
void saveNickServ ()
void saveOptions ()
void savePopups ()
void saveProxyDataBase ()
void saveRawEvents ()
void saveRecentEntries ()
void saveRegisteredChannels ()
void saveRegisteredUsers ()
void saveScriptAddons ()
void saveSharedFiles ()
void saveTextIcons ()
void saveToolBars ()
void setAvatarFromOptions ()
void setAvatarOnFileReceived (KviConsole *pConsole, const QString &szRemoteUrl, const QString &szNick, const QString &szUser, const QString &szHost)
bool setCommonOptionValue (const QString &optName, const QString &value)
bool setOptionValue (const QString &optName, const QString &value)
void setup ()
void setupBegin ()
void setupFinish ()
bool supportsCompositing ()
KviConsole * topmostConnectedConsole ()
void triggerUpdateGui ()
unsigned int windowCount ()
bool windowExists (KviWindow *wnd)
~KviApp ()
Static Public Member Functions
static QTextCodec * defaultSrvCodec ()
static QTextCodec * defaultTextCodec ()
static int getGloballyUniqueId ()
Public Attributes
bool m_bCreateConfig
bool m_bShowSplashScreen
QString m_szConfigFile
KviStr m_szExecAfterStartup
Protected Member Functions
void buildRecentChannels ()
void frameDestructorCallback ()
void heartbeat (kvi_time_t tNow)
void registerWindow (KviWindow *wnd)
void saveRecentChannels ()
virtual void timerEvent (QTimerEvent *e)
void unregisterWindow (KviWindow *wnd)
Protected Attributes
bool m_bFirstTimeRun
bool m_bSetupDone
bool m_bUpdateGuiPending
QFont m_fntDefaultFont
int m_iHeartbeatTimerId
KviWindow * m_pActiveWindow
KviIpcSentinel * m_pIpcSentinel
KviPointerList
< KviPendingAvatarChange > * m_pPendingAvatarChanges
KviPointerHashTable< QString,
QStringList > * m_pRecentChannelDict
QString m_szGlobalKvircDir
QString m_szLocalKvircDir
Private Member Functions
bool checkFileAssociations ()
bool checkGlobalKvircDirectory (const QString)
bool checkLocalKvircDirectory ()
bool checkLocalKvircDirectory (const QString &szSpecificPath)
bool checkUriAssociations (const char *proto)
void createFrame ()
COMPILE_NO_IPC.
void createIpcSentinel ()
void createSplashScreen ()
void destroyIpcSentinel ()
void destroySplashScreen ()
void findGlobalKvircDirectory ()
bool findLocalKvircDirectory ()
void loadDirectories ()
void loadRecentEntries ()
void saveKvircDirectory ()
void setupFileAssociations ()
void setupUriAssociations (const char *proto)
void updateApplicationFont ()
Friends
class KviFrame
class KviSetupWizard
class KviWindow
Member Enumeration Documentation
enum KviApp::KvircSubdir
Enumerator:
None
Pics
Config
HelpEN
HelpNoIntl
Log
Incoming
Audio
Scripts
Plugins
ConfigPlugins
Trash
MsgColors
Charmaps
Avatars
DefScript
License
Modules
ConfigScripts
Filters
Tmp
Locale
Themes
Classes
SmallIcons
EasyPlugins
Constructor & Destructor Documentation
KviApp::KviApp (int & argc, char ** argv)
References KviFileUtils::fileExists(), g_pApp, KVI_PATH_SEPARATOR_CHAR, kvi_socket_flushTrafficCounters(), m_bCreateConfig, m_bSetupDone, m_bShowSplashScreen, m_bUpdateGuiPending, m_fntDefaultFont, m_iHeartbeatTimerId, m_pIpcSentinel, m_pPendingAvatarChanges, m_pRecentChannelDict, m_szConfigFile, and NULL.
KviApp::~KviApp ()
References KviFileTransferManager::cleanup(), destroyIpcSentinel(), KviLocale::done(), g_pActiveWindow, g_pColorWindow, g_pCtcpPageDialog, g_pFrame, g_pGlobalWindowDict, g_pHistoryWindow, g_pIconManager, g_pInputPopup, g_pMediaManager, g_pModuleExtensionManager, g_pModuleManager, g_pNickServRuleSet, g_pProxyDataBase, g_pRecentTopicList, g_pRegisteredChannelDataBase, g_pRegisteredUserDataBase, g_pServerDataBase, g_pServerParser, g_pSharedFilesManager, g_pSplashScreen, g_pTextIconManager, g_pTextIconWindow, KviThreadManager::globalDestroy(), m_bSetupDone, m_pPendingAvatarChanges, m_pRecentChannelDict, saveActions(), saveAliases(), saveAppEvents(), saveAvatarCache(), saveIdentities(), saveIdentityProfiles(), saveInputHistory(), saveIrcServerDataBase(), saveMediaTypes(), saveNickServ(), saveOptions(), savePopups(), saveProxyDataBase(), saveRawEvents(), saveRecentEntries(), saveRegisteredChannels(), saveRegisteredUsers(), saveScriptAddons(), saveSharedFiles(), saveTextIcons(), and saveToolBars().
Member Function Documentation
KviConsole * KviApp::activeConsole ()
References KviWindow::console(), KviFrame::firstConsole(), g_pActiveWindow, and g_pFrame.
Referenced by autoConnectToServers(), KviKvsObject::callFunction(), KviKvsCallbackObject::execute(), KviKvsPopupMenu::itemClicked(), KviKvsCoreSimpleCommands::KVSCSC(), KviMenuBar::newConnectionToServer(), KviKvsPopupMenu::setupMenuContents(), KviKvsTimerManager::timerEvent(), topmostConnectedConsole(), and KviKvsProcessAsyncOperation::trigger().
void KviApp::addRecentChannel (const QString & chan, const QString & net)
References buildRecentChannels(), KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), and m_pRecentChannelDict.
Referenced by KviIrcConnection::registerChannel().
void KviApp::addRecentNickname (const QString & newNick)
References KVI_MAX_RECENT_NICKNAMES, KviOption_stringlistRecentNicknames, and merge_to_stringlist_option().
Referenced by KviIrcConnection::loginComplete(), and KviIrcConnection::nickChange().
void KviApp::addRecentServer (const QString & server)
References KVI_MAX_RECENT_SERVERS, KviOption_stringlistRecentServers, and merge_to_stringlist_option().
Referenced by KviIrcContext::connectionEstabilished().
void KviApp::addRecentUrl (const QString & text) [slot]
References KviOption_stringlistRecentIrcUrls, merge_to_stringlist_option(), and recentUrlsChanged().
Referenced by KviIrcUrl::run().
void KviApp::autoConnectToServers ()
References activeConsole(), KviServerDataBase::autoConnectOnStartupNetworks(), KviServerDataBase::autoConnectOnStartupServers(), KviServerDataBase::clearAutoConnectOnStartupNetworks(), KviServerDataBase::clearAutoConnectOnStartupServers(), KviPointerList< T >::first(), g_pServerDataBase, KviPointerList< T >::next(), and KviIrcUrl::run().
Referenced by createFrame().
void KviApp::buildRecentChannels () [protected]
References KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), KVI_OPTION_STRINGLIST, KVI_RECENT_CHANNELS_SEPARATOR, KviOption_stringlistRecentChannels, m_pRecentChannelDict, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by addRecentChannel(), optionResetUpdate(), recentChannelsForNetwork(), and setOptionValue().
bool KviApp::checkFileAssociations () [private]
References __tr2qs, kvi_strEqualCI(), kvi_strEqualCIN(), and KviQString::toLocal8Bit().
Referenced by loadDirectories().
bool KviApp::checkGlobalKvircDirectory (const QString szDir) [private]
References KviFileUtils::directoryExists(), KviFileUtils::isReadable(), KVI_ACTIVITYMETER_IMAGE_NAME, and KVI_PATH_SEPARATOR.
Referenced by findGlobalKvircDirectory().
bool KviApp::checkLocalKvircDirectory () [private]
References Config, KviFileUtils::directoryExists(), getLocalKvircDirectory(), and m_szLocalKvircDir.
Referenced by checkLocalKvircDirectory(), and findLocalKvircDirectory().
bool KviApp::checkLocalKvircDirectory (const QString & szSpecificPath) [private]
References checkLocalKvircDirectory(), and m_szLocalKvircDir.
void KviApp::checkSuggestRestoreDefaultScript ()
References __tr2qs, KviKvsEventManager::instance(), KviKvsPopupManager::instance(), KviCustomToolBarManager::instance(), KVI_OPTION_BOOL, KviEvent_OnChannelNickPopupRequest, KviEvent_OnChannelPopupRequest, KviEvent_OnConsolePopupRequest, KviEvent_OnDCCChatPopupRequest, KviEvent_OnQueryNickPopupRequest, KviEvent_OnQueryPopupRequest, KviOption_boolDoNotSuggestRestoreDefaultScript, and restoreDefaultScript().
Referenced by KviUserListView::emitDoubleClick(), KviUserListView::emitRightClick(), and setup().
bool KviApp::checkUriAssociations (const char * proto) [private]
Referenced by loadDirectories().
void KviApp::completeDirectory (const QString & word, KviPointerList< QString > * matches)
References KviFileUtils::adjustFilePath(), KviPointerList< T >::append(), KviQString::cutFromLast(), KviQString::cutToLast(), d, KviQString::ensureLastCharIs(), KviQString::equalCIN(), KviQString::equalCS(), KviQString::equalCSN(), and KVI_PATH_SEPARATOR_CHAR.
Referenced by KviInputEditor::completion().
bool KviApp::connectionExists (KviIrcConnection * cnn)
References KviWindow::connection(), KviPointerHashTableIterator< Key, T >::current(), and g_pGlobalWindowDict.
void KviApp::createFrame () [private]
COMPILE_NO_IPC.
References KviServerDataBase::autoConnectOnStartupNetworks(), KviServerDataBase::autoConnectOnStartupServers(), autoConnectToServers(), KviFrame::createNewConsole(), KviFrame::executeInternalCommand(), KviFrame::firstConsole(), g_pFrame, g_pServerDataBase, KviStr::hasData(), KVI_INTERNALCOMMAND_TRAYICON_SHOW, KVI_OPTION_BOOL, KviFrame, KviOption_boolShowDockExtension, KviOption_boolStartupMinimized, m_szExecAfterStartup, KviStr::ptr(), and KviIrcUrl::run().
Referenced by setup().
void KviApp::createIpcSentinel () [private]
References m_pIpcSentinel.
Referenced by setup().
void KviApp::createSplashScreen () [private]
References g_pSplashScreen.
Referenced by setup().
QTextCodec * KviApp::defaultSrvCodec () [static]
References KviLocale::codecForName(), KVI_OPTION_STRING, and KviOption_stringDefaultSrvEncoding.
Referenced by KviIrcConnection::setupSrvCodec().
QTextCodec * KviApp::defaultTextCodec () [static]
References KviLocale::codecForName(), KVI_OPTION_STRING, and KviOption_stringDefaultTextEncoding.
Referenced by KviIrcConnection::setupTextCodec().
void KviApp::destroyFrame ()
References g_pActiveWindow, and g_pFrame.
Referenced by KviFrame::closeEvent().
void KviApp::destroyIpcSentinel () [private]
References m_pIpcSentinel.
Referenced by ~KviApp().
void KviApp::destroySplashScreen () [private]
References KviSplashScreen::die(), and g_pSplashScreen.
Referenced by setup().
void KviApp::fileDownloadTerminated (bool bSuccess, const QString & szRemoteUrl, const QString & szLocalFileName, const QString & szNick = QString(), const QString & szError = QString(), bool bQuiet = false)
References __tr2qs, _OUTPUT_MUTE, KviPointerList< T >::count(), KviQString::equalCIN(), findPendingAvatarChange(), g_pActiveWindow, KviWindow::hasAttention(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_AVATAR, KVI_SMALLICON_DCCERROR, KVI_SMALLICON_DCCMSG, KviOption_boolNotifyDccSendSuccessInNotifier, KviOption_uintNotifierAutoHideTime, m_pPendingAvatarChanges, notifierMessage(), KviWindow::output(), _KviPendingAvatarChange::pConsole, KviPointerList< T >::removeRef(), KviConsole::setAvatar(), _KviPendingAvatarChange::szHost, _KviPendingAvatarChange::szNick, _KviPendingAvatarChange::szUser, and windowExists().
void KviApp::fillRecentChannelsPopup (KviTalPopupMenu * m, KviConsole * pConsole)
References KviTalPopupMenu::clear(), KviWindow::connection(), KviConsole::currentNetworkName(), KviIrcConnection::findChannel(), g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviConsole::isConnected(), KVI_SMALLICON_CHANNEL, recentChannelsForNetwork(), and KviTalPopupMenu::setItemEnabled().
Referenced by KviJoinChannelAction::popupAboutToShow().
void KviApp::fillRecentNicknamesPopup (KviTalPopupMenu * m, KviConsole * pConsole)
References KviTalPopupMenu::clear(), KviWindow::connection(), KviIrcConnection::currentNickName(), KviQString::equalCS(), g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviConsole::isConnected(), KVI_OPTION_STRINGLIST, KVI_SMALLICON_NICK, KviOption_stringlistRecentNicknames, and KviTalPopupMenu::setItemEnabled().
Referenced by KviChangeNickAction::popupAboutToShow().
void KviApp::fillRecentServersPopup (KviTalPopupMenu * m)
References KviTalPopupMenu::clear(), g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KVI_OPTION_STRINGLIST, KVI_SMALLICON_SERVER, and KviOption_stringlistRecentServers.
Referenced by KviConnectToServerAction::popupAboutToShow(), and KviMenuBar::setupRecentServersPopup().
bool KviApp::findAudioFile (QString & szRetPath, const QString & szFileName)
Attempts to locate the audio file specified by szFileName and put it's absolute path in szRetPath. Returns true if the audio file is found and false otherwise.
If szFileName is already an absolute path then it's returned directly after testing for its existence. If szFileName is not an absolute path then it's searched in the local KVIrc "audio" directory, then in the global one and finally in the user's home.
References Audio, KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KviFileUtils::isAbsolutePath(), and KVI_PATH_SEPARATOR_CHAR.
KviConsole * KviApp::findConsole (QString & servr, QString & nick)
References KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), g_pGlobalWindowDict, KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
KviConsole * KviApp::findConsole (unsigned int ircContextId)
References KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
Referenced by KviKvsCoreFunctions::KVSCF().
void KviApp::findGlobalKvircDirectory () [private]
defined(COMPILE_KDE_SUPPORT) && !defined(COMPILE_ON_MAC)
COMPILE_ON_MAC
References KviFileUtils::adjustFilePath(), checkGlobalKvircDirectory(), m_szGlobalKvircDir, and KviMessageBox::warning().
Referenced by loadDirectories().
bool KviApp::findImage (QString & szRetPath, const QString & filename)
References KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), findImageInImageSearchPath(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KviFileUtils::isAbsolutePath(), KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, pics_globalsubdirs, pics_localsubdirs, and Themes.
Referenced by KviIconManager::getPixmapWithCache(), KviIconManager::getPixmapWithCacheScaleOnLoad(), KviIconManager::KviIconManager(), KviSplashScreen::KviSplashScreen(), KviTextIcon::KviTextIcon(), and setOptionValue().
bool KviApp::findImageInImageSearchPath (QString & szRetPath, const QString & filename)
References KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), KVI_OPTION_STRINGLIST, KVI_PATH_SEPARATOR_CHAR, and KviOption_stringlistImageSearchPaths.
Referenced by findImage(), findImageThemeOnlyCompat(), and findSmallIcon().
bool KviApp::findImageThemeOnlyCompat (QString & szRetPath, const QString & filename)
References KviFileUtils::fileExists(), findImageInImageSearchPath(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, Pics, and Themes.
bool KviApp::findLocalKvircDirectory () [private]
References checkLocalKvircDirectory(), g_pApp, KVI_HOME_CONFIG_FILE_NAME, KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, KVI_SOURCES_DATE_NUMERIC_FORCE_SETUP, m_szConfigFile, m_szLocalKvircDir, KviConfig::Read, KviConfig::readEntry(), KviConfig::readUIntEntry(), and KviConfig::setGroup().
Referenced by loadDirectories().
KviPendingAvatarChange * KviApp::findPendingAvatarChange (KviConsole * pConsole, const QString & szNick, const QString & szRemoteUrl)
References KviPointerList< T >::first(), m_pPendingAvatarChanges, KviPointerList< T >::next(), _KviPendingAvatarChange::pConsole, _KviPendingAvatarChange::szNick, and _KviPendingAvatarChange::szRemoteUrl.
Referenced by fileDownloadTerminated(), and KviServerParser::parseCtcpRequestDcc().
bool KviApp::findSmallIcon (QString & szRetPath, const QString & filename)
References KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), findImageInImageSearchPath(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, KviOption_stringIconThemeSubdir, Pics, SmallIcons, and Themes.
Referenced by KviIconManager::loadSmallIcon().
KviWindow * KviApp::findWindow (const QString & windowId)
References g_pGlobalWindowDict.
Referenced by KviKvsTreeNodeRebindingSwitch::execute(), KviKvsCoreFunctions::KVSCF(), and KviKvsCoreSimpleCommands::KVSCSC().
KviWindow * KviApp::findWindowByCaption (const QString & windowCaption, int iContextId = -1)
References KviWindow::context(), KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), g_pGlobalWindowDict, KviIrcContext::id(), and KviWindow::plainTextCaption().
Referenced by KviKvsCoreFunctions::KVSCF().
bool KviApp::firstTimeRun () [inline]
Referenced by setup().
void KviApp::frameDestructorCallback () [protected]
References KviKvsObjectController::clearInstances(), KviKvsKernel::instance(), and KviKvsKernel::objectController().
Referenced by KviFrame::~KviFrame().
void KviApp::getChannelDumpLogFileName (QString & str)
References KviFileUtils::adjustFilePath(), KviFileUtils::fileExists(), getLocalKvircDirectory(), Log, and KviQString::sprintf().
void KviApp::getGlobalKvircDirectory (QString & szData, KvircSubdir dir, const QString & appendFile = QString())
References KviFileUtils::adjustFilePath(), KviQString::appendFormatted(), Audio, Avatars, Charmaps, Classes, Config, ConfigPlugins, ConfigScripts, DefScript, KviFileUtils::directoryExists(), EasyPlugins, KviQString::ensureLastCharIs(), Filters, Help, HelpEN, HelpNoIntl, Incoming, KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, License, Locale, KviLocale::localeName(), Log, m_szGlobalKvircDir, Modules, MsgColors, None, Pics, Plugins, Scripts, SmallIcons, Themes, Tmp, and Trash.
Referenced by KviModuleManager::completeModuleNames(), findAudioFile(), findImage(), findImageThemeOnlyCompat(), findSmallIcon(), getReadOnlyConfigPath(), KviIconManager::initQResourceBackend(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviTextIconManager::load(), loadDefaultScript(), KviModuleManager::loadModule(), KviModuleManager::loadModulesByCaps(), KviKvsObjectController::lookupClass(), mapImageFile(), setup(), and setupBegin().
int KviApp::getGloballyUniqueId () [static]
References g_iGloballyUniqueId.
Referenced by KviCustomToolBarDescriptor::KviCustomToolBarDescriptor(), KviFileTransfer::KviFileTransfer(), and KviModuleExtensionDescriptor::KviModuleExtensionDescriptor().
void KviApp::getLocalKvircDirectory (QString & szData, KvircSubdir dir, const QString & appendFile = QString(), bool bCreateIfNeeded = true)
References KviFileUtils::adjustFilePath(), Audio, Avatars, Charmaps, Classes, Config, ConfigPlugins, ConfigScripts, DefScript, KviFileUtils::directoryExists(), EasyPlugins, KviQString::ensureLastCharIs(), Filters, Help, HelpEN, HelpNoIntl, Incoming, KVI_DEFAULT_INCOMING_SUBDIRECTORY_NAME, KVI_OPTION_STRING, KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, KviOption_stringIncomingPath, KviOption_stringLogsPath, License, Locale, KviLocale::localeName(), Log, m_szLocalKvircDir, KviFileUtils::makeDir(), Modules, MsgColors, None, Pics, Plugins, KviStr::ptr(), Scripts, SmallIcons, Themes, Tmp, and Trash.
Referenced by checkLocalKvircDirectory(), KviModuleManager::completeModuleNames(), KviKvsObjectController::deleteClass(), KviIrcViewToolWidget::filterLoad(), KviIrcViewToolWidget::filterSave(), findAudioFile(), findImage(), findImageThemeOnlyCompat(), findSmallIcon(), KviKvsObjectController::flushUserClasses(), KviIconManager::getAvatar(), getChannelDumpLogFileName(), KviModule::getDefaultConfigFileName(), KviWindow::getDefaultLogFileName(), getReadOnlyConfigPath(), getTmpFileName(), KviIconManager::initQResourceBackend(), KviSplashScreen::KviSplashScreen(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviModuleManager::loadModule(), KviModuleManager::loadModulesByCaps(), loadRecentEntries(), KviKvsObjectController::lookupClass(), mapImageFile(), KviServerParser::parseCtcpReplyAvatar(), KviQuery::pasteLastLog(), KviChannel::pasteLastLog(), KviFrame::restoreToolBarPositions(), KviStatusBar::save(), KviTextIconManager::save(), saveActions(), saveAliases(), saveAppEvents(), saveAvatarCache(), saveIdentities(), saveIdentityProfiles(), saveInputHistory(), saveIrcServerDataBase(), saveMediaTypes(), saveNickServ(), saveOptions(), savePopups(), saveProxyDataBase(), saveRawEvents(), saveRecentEntries(), saveRegisteredChannels(), saveRegisteredUsers(), saveScriptAddons(), saveSharedFiles(), KviFrame::saveToolBarPositions(), saveToolBars(), setup(), and KviKvsScriptAddonManager::unregisterAddon().
bool KviApp::getOptionString (const QString & optName, QString & buffer)
References g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, GET_OPTION_STRING, KVI_BOOL_OPTIONS_PREFIX, KVI_BOOL_OPTIONS_PREFIX_LEN, KVI_COLOR_OPTIONS_PREFIX, KVI_COLOR_OPTIONS_PREFIX_LEN, KVI_FONT_OPTIONS_PREFIX, KVI_FONT_OPTIONS_PREFIX_LEN, KVI_ICCOLOR_OPTIONS_PREFIX, KVI_ICCOLOR_OPTIONS_PREFIX_LEN, KVI_MIRCCOLOR_OPTIONS_PREFIX, KVI_MIRCCOLOR_OPTIONS_PREFIX_LEN, KVI_MSGTYPE_OPTIONS_PREFIX, KVI_MSGTYPE_OPTIONS_PREFIX_LEN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KVI_PIXMAP_OPTIONS_PREFIX, KVI_PIXMAP_OPTIONS_PREFIX_LEN, KVI_STRING_OPTIONS_PREFIX, KVI_STRING_OPTIONS_PREFIX_LEN, KVI_STRINGLIST_OPTIONS_PREFIX, KVI_STRINGLIST_OPTIONS_PREFIX_LEN, KVI_UINT_OPTIONS_PREFIX, and KVI_UINT_OPTIONS_PREFIX_LEN.
Referenced by KviKvsCoreFunctions::KVSCF().
bool KviApp::getReadOnlyConfigPath (QString & buffer, const char * config_name, KvircSubdir sbd = Config, bool bNoFail = false)
References KviFileUtils::fileExists(), getGlobalKvircDirectory(), and getLocalKvircDirectory().
Referenced by KviStatusBar::load(), KviTextIconManager::load(), loadOptions(), and setup().
void KviApp::getTmpFileName (QString & szBuffer, const QString & szEndingFileName = QString())
References KviQString::appendFormatted(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), getLocalKvircDirectory(), kvi_gettimeofday(), KVI_PATH_SEPARATOR_CHAR, and Tmp.
void KviApp::heartbeat (kvi_time_t tNow) [protected]
References KviPointerHashTableIterator< Key, T >::current(), g_pApp, g_pGlobalWindowDict, KviIrcView::isLogging(), KVI_OPTION_UINT, KviOption_uintTotalConnectionTime, KviIrcView::startLogging(), topmostConnectedConsole(), and KviWindow::view().
Referenced by timerEvent().
void KviApp::ipcMessage (char * message)
References __tr2qs, _OUTPUT_VERBOSE, KviStr::cutRight(), KviStr::findFirstIdx(), KviFrame::firstConsole(), g_pFrame, KVI_OUT_SYSTEMMESSAGE, KviStr::len(), KviWindow::output(), KviStr::ptr(), and KviIrcUrl::run().
void KviApp::listAvailableOptions (KviWindow * wnd)
References __tr, g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, and LIST_OPTIONS.
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviApp::loadDefaultScript ()
References DefScript, KviFrame::firstConsole(), g_pFrame, getGlobalKvircDirectory(), and KviIrcUrl::run().
Referenced by restoreDefaultScript().
void KviApp::loadDirectories () [private]
References checkFileAssociations(), checkUriAssociations(), findGlobalKvircDirectory(), findLocalKvircDirectory(), KviStringConversion::init(), KVI_PATH_SEPARATOR, m_bFirstTimeRun, m_szGlobalKvircDir, setupBegin(), setupFileAssociations(), and setupUriAssociations().
Referenced by setup().
void KviApp::loadOptions ()
References KviStringConversion::decodePath(), g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, getReadOnlyConfigPath(), KVI_CONFIGFILE_MAIN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KviConfig::Read, and READ_OPTIONS.
Referenced by setup().
void KviApp::loadRecentEntries () [private]
References Config, g_pRecentTopicList, getLocalKvircDirectory(), KVI_CONFIGFILE_RECENT, KviConfig::Read, and KviConfig::readStringListEntry().
Referenced by setup().
bool KviApp::mapImageFile (QString & szRetPath, const QString & filename)
References KviQString::cutToFirst(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), getGlobalKvircDirectory(), getLocalKvircDirectory(), KviFileUtils::isAbsolutePath(), KVI_PATH_SEPARATOR, KVI_PATH_SEPARATOR_CHAR, pics_globalsubdirs, and pics_localsubdirs.
Referenced by KviImageDialog::itemDoubleClicked().
void KviApp::notifierMessage (KviWindow * pWnd, int iIconId, const QString & szMsg, unsigned int uMessageLifetime)
References __tr2qs, KviModule::ctrl(), g_pIconManager, g_pModuleManager, KviModuleManager::getModule(), KviIconManager::getSmallIconName(), KVI_OPTION_BOOL, KviOption_boolUseDBusNotifier, _KviNotifierMessageParam::pWindow, s, KviMircCntrl::stripControlBytes(), _KviNotifierMessageParam::szIcon, _KviNotifierMessageParam::szMessage, KviWindow::target(), and _KviNotifierMessageParam::uMessageLifetime.
Referenced by fileDownloadTerminated(), KviNotifyListManager::notifyOnLine(), KviConsole::outputPrivmsg(), KviServerParser::parseCtcpRequestAction(), KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
void KviApp::optionResetUpdate (int flags)
References buildRecentChannels(), KviFrame::executeInternalCommand(), g_iIdentDaemonRunningUsers, g_pApp, g_pFrame, g_pIconManager, KVI_INTERNALCOMMAND_IDENT_START, KVI_INTERNALCOMMAND_IDENT_STOP, KVI_OPTION_BOOL, KviOption_boolUseIdentService, KviOption_boolUseIdentServiceOnlyOnConnect, KviFrame::recreateWindowList(), reloadImages(), KviIconManager::reloadImages(), restartLagMeters(), restartNotifyLists(), triggerUpdateGui(), updateApplicationFont(), and updateNotifier().
Referenced by KviOptionsWidget::commitOptionsReset(), and setOptionValue().
KviPointerHashTable<QString,QStringList>* KviApp::recentChannels () const [inline]
QStringList * KviApp::recentChannelsForNetwork (const QString & net)
References buildRecentChannels(), KviPointerHashTable< Key, T >::find(), and m_pRecentChannelDict.
Referenced by KviConsole::completeChannel(), and fillRecentChannelsPopup().
void KviApp::recentUrlsChanged () [signal]
Referenced by addRecentUrl().
void KviApp::registerWindow (KviWindow * wnd) [protected]
References g_pGlobalWindowDict, and KviWindow::id().
Referenced by KviWindow::KviWindow().
void KviApp::reloadImages () [signal]
Referenced by optionResetUpdate().
void KviApp::resetAvatarForMatchingUsers (KviRegisteredUser * u)
References KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
void KviApp::restartLagMeters ()
References KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
Referenced by KviStatusBarLagIndicator::mouseDoubleClickEvent(), and optionResetUpdate().
void KviApp::restartNotifyLists ()
References KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
Referenced by optionResetUpdate().
void KviApp::restoreDefaultScript () [slot]
References __tr2qs, KviCustomToolBarManager::clear(), KviKvs::clearAliases(), KviKvs::clearAppEvents(), KviKvs::clearPopups(), KviKvs::clearRawEvents(), KviKvs::clearScriptAddons(), KviCustomToolBarManager::instance(), KviActionManager::instance(), KviActionManager::killAllKvsUserActions(), loadDefaultScript(), saveOptions(), and KviMessageBox::warning().
Referenced by checkSuggestRestoreDefaultScript().
void KviApp::saveActions ()
References Config, getLocalKvircDirectory(), KviActionManager::instance(), KVI_CONFIGFILE_USERACTIONS, and KviActionManager::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveAliases ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_ALIASES.
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveAppEvents ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_EVENTS.
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveAvatarCache ()
References Config, getLocalKvircDirectory(), KviAvatarCache::instance(), KVI_CONFIGFILE_AVATARCACHE, and KviAvatarCache::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveConfiguration () [virtual, slot]
Saves configuration to disk.
Returns:
void
Implements KviTalApplication.
References KviKvs::flushUserClasses(), KviCustomToolBarManager::instance(), saveActions(), saveAliases(), saveAppEvents(), saveAvatarCache(), saveIdentities(), saveIdentityProfiles(), saveInputHistory(), saveIrcServerDataBase(), saveMediaTypes(), saveNickServ(), saveOptions(), savePopups(), saveProxyDataBase(), saveRawEvents(), saveRecentEntries(), saveRegisteredChannels(), saveRegisteredUsers(), saveScriptAddons(), saveSharedFiles(), saveTextIcons(), saveToolBars(), KviCustomToolBarManager::storeVisibilityState(), and KviConfig::sync().
void KviApp::saveIdentities ()
References Config, getLocalKvircDirectory(), KviUserIdentityManager::instance(), KVI_CONFIGFILE_IDENTITIES, and KviUserIdentityManager::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveIdentityProfiles ()
References Config, getLocalKvircDirectory(), KviIdentityProfileSet::instance(), KVI_CONFIGFILE_PROFILESDATABASE, and KviIdentityProfileSet::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveInputHistory ()
References Config, getLocalKvircDirectory(), KviInputHistory::instance(), KVI_CONFIGFILE_INPUTHISTORY, KVI_OPTION_BOOL, KviOption_boolEnableInputHistory, and KviInputHistory::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveIrcServerDataBase ()
References Config, g_pServerDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_SERVERDB, and KviServerDataBase::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveKvircDirectory () [private]
References KVI_HOME_CONFIG_FILE_NAME, KVI_PATH_SEPARATOR, KVI_SOURCES_DATE_NUMERIC, m_szConfigFile, m_szLocalKvircDir, KviConfig::setGroup(), KviConfig::Write, and KviConfig::writeEntry().
void KviApp::saveMediaTypes ()
References Config, g_pMediaManager, getLocalKvircDirectory(), KVI_CONFIGFILE_MEDIATYPES, KviMutex::lock(), KviMediaManager::save(), and KviMutex::unlock().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveNickServ ()
References Config, g_pNickServRuleSet, getLocalKvircDirectory(), KVI_CONFIGFILE_NICKSERVDATABASE, and KviNickServRuleSet::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveOptions ()
References Config, KviStringConversion::decodePath(), KviStringConversion::encodePath(), g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, getLocalKvircDirectory(), KVI_CONFIGFILE_MAIN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, saveRecentChannels(), KviConfig::Write, and WRITE_OPTIONS.
Referenced by restoreDefaultScript(), saveConfiguration(), and ~KviApp().
void KviApp::savePopups ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_POPUPS.
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveProxyDataBase ()
References Config, g_pProxyDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_PROXYDB, and KviProxyDataBase::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveRawEvents ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_RAWEVENTS.
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveRecentChannels () [protected]
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KVI_OPTION_STRINGLIST, KVI_RECENT_CHANNELS_SEPARATOR, KviOption_stringlistRecentChannels, and m_pRecentChannelDict.
Referenced by saveOptions().
void KviApp::saveRecentEntries ()
References Config, g_pRecentTopicList, getLocalKvircDirectory(), KVI_CONFIGFILE_RECENT, KviConfig::Write, and KviConfig::writeEntry().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveRegisteredChannels ()
References Config, g_pRegisteredChannelDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_REGCHANDB, and KviRegisteredChannelDataBase::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveRegisteredUsers ()
References Config, g_pRegisteredUserDataBase, getLocalKvircDirectory(), KVI_CONFIGFILE_REGUSERDB, and KviRegisteredUserDataBase::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveScriptAddons ()
References Config, getLocalKvircDirectory(), and KVI_CONFIGFILE_SCRIPTADDONS.
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveSharedFiles ()
References Config, g_pSharedFilesManager, getLocalKvircDirectory(), KVI_CONFIGFILE_SHAREDFILES, and KviSharedFilesManager::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveTextIcons ()
References g_pTextIconManager, and KviTextIconManager::save().
Referenced by saveConfiguration(), and ~KviApp().
void KviApp::saveToolBars ()
References Config, getLocalKvircDirectory(), KviCustomToolBarManager::instance(), KVI_CONFIGFILE_CUSTOMTOOLBARS, and KviCustomToolBarManager::save().
Referenced by KviActionManager::customizeToolBarsDialogDestroyed(), saveConfiguration(), and ~KviApp().
void KviApp::setAvatarFromOptions ()
References KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
void KviApp::setAvatarOnFileReceived (KviConsole * pConsole, const QString & szRemoteUrl, const QString & szNick, const QString & szUser, const QString & szHost)
References KviPointerList< T >::append(), KviPointerList< T >::count(), KVI_MAX_PENDING_AVATARS, m_pPendingAvatarChanges, _KviPendingAvatarChange::pConsole, KviPointerList< T >::removeFirst(), KviPointerList< T >::setAutoDelete(), _KviPendingAvatarChange::szHost, _KviPendingAvatarChange::szNick, _KviPendingAvatarChange::szRemoteUrl, and _KviPendingAvatarChange::szUser.
Referenced by KviServerParser::parseCtcpReplyAvatar().
bool KviApp::setCommonOptionValue (const QString & optName, const QString & value)
References g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, KVI_BOOL_OPTIONS_PREFIX, KVI_BOOL_OPTIONS_PREFIX_LEN, KVI_COLOR_OPTIONS_PREFIX, KVI_COLOR_OPTIONS_PREFIX_LEN, KVI_FONT_OPTIONS_PREFIX, KVI_FONT_OPTIONS_PREFIX_LEN, KVI_ICCOLOR_OPTIONS_PREFIX, KVI_ICCOLOR_OPTIONS_PREFIX_LEN, KVI_MIRCCOLOR_OPTIONS_PREFIX, KVI_MIRCCOLOR_OPTIONS_PREFIX_LEN, KVI_MSGTYPE_OPTIONS_PREFIX, KVI_MSGTYPE_OPTIONS_PREFIX_LEN, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KVI_STRING_OPTIONS_PREFIX, KVI_STRING_OPTIONS_PREFIX_LEN, KVI_STRINGLIST_OPTIONS_PREFIX, KVI_STRINGLIST_OPTIONS_PREFIX_LEN, KVI_UINT_OPTIONS_PREFIX, KVI_UINT_OPTIONS_PREFIX_LEN, and SET_OPTION_VALUE.
Referenced by setOptionValue().
bool KviApp::setOptionValue (const QString & optName, const QString & value)
References buildRecentChannels(), KviQString::equalCI(), KviQString::equalCIN(), findImage(), KviStringConversion::fromString(), g_pixmapOptionsTable, KVI_NUM_PIXMAP_OPTIONS, KVI_PIXMAP_OPTIONS_PREFIX, KVI_PIXMAP_OPTIONS_PREFIX_LEN, KviOsInfo::name(), optionResetUpdate(), and setCommonOptionValue().
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviApp::setup ()
References checkSuggestRestoreDefaultScript(), KviLocale::codecForName(), Config, createFrame(), createIpcSentinel(), createSplashScreen(), destroySplashScreen(), KviFrame::executeInternalCommand(), KviFileUtils::fileExists(), firstTimeRun(), g_pFrame, g_pGlobalWindowDict, g_pIconManager, g_pInputPopup, g_pMediaManager, g_pModuleExtensionManager, g_pModuleManager, g_pNickServRuleSet, g_pProxyDataBase, g_pRecentTopicList, g_pRegisteredChannelDataBase, g_pRegisteredUserDataBase, g_pServerDataBase, g_pServerParser, g_pSharedFilesManager, g_pTextIconManager, getGlobalKvircDirectory(), getLocalKvircDirectory(), getReadOnlyConfigPath(), KviThreadManager::globalInit(), KviStringConversion::init(), KviInputHistory::instance(), KviAvatarCache::instance(), KviIdentityProfileSet::instance(), KviCustomToolBarManager::instance(), KviUserIdentityManager::instance(), KviActionManager::instance(), KVI_CONFIGFILE_ALIASES, KVI_CONFIGFILE_AVATARCACHE, KVI_CONFIGFILE_CUSTOMTOOLBARS, KVI_CONFIGFILE_EVENTS, KVI_CONFIGFILE_IDENTITIES, KVI_CONFIGFILE_INPUTHISTORY, KVI_CONFIGFILE_MEDIATYPES, KVI_CONFIGFILE_NICKSERVDATABASE, KVI_CONFIGFILE_POPUPS, KVI_CONFIGFILE_PROFILESDATABASE, KVI_CONFIGFILE_PROXYDB, KVI_CONFIGFILE_RAWEVENTS, KVI_CONFIGFILE_REGCHANDB, KVI_CONFIGFILE_REGUSERDB, KVI_CONFIGFILE_SCRIPTADDONS, KVI_CONFIGFILE_SERVERDB, KVI_CONFIGFILE_SHAREDFILES, KVI_CONFIGFILE_USERACTIONS, KVI_CONFIGFILE_WINPROPERTIES, KVI_INTERNALCOMMAND_SERVERSJOIN_OPEN, KVI_OPTION_BOOL, KVI_SPLASH_SET_PROGRESS, KVI_VERSION, KviOption_boolShowServersConnectDialogOnStart, KviFrame::KviServerParser, KviInputHistory::load(), KviAvatarCache::load(), KviIdentityProfileSet::load(), KviNickServRuleSet::load(), KviSharedFilesManager::load(), KviRegisteredChannelDataBase::load(), KviRegisteredUserDataBase::load(), KviMediaManager::load(), KviTextIconManager::load(), KviCustomToolBarManager::load(), KviProxyDataBase::load(), KviServerDataBase::load(), KviUserIdentityManager::load(), KviActionManager::load(), KviKvs::loadAliases(), KviKvs::loadAppEvents(), loadDirectories(), loadOptions(), KviKvs::loadPopups(), KviKvs::loadRawEvents(), loadRecentEntries(), KviKvs::loadScriptAddons(), KviMutex::lock(), m_bSetupDone, m_bShowSplashScreen, m_iHeartbeatTimerId, m_szGlobalKvircDir, m_szLocalKvircDir, None, Pics, KviFileUtils::readFile(), KviConfig::ReadWrite, setupFinish(), KviMutex::unlock(), updateApplicationFont(), and updatePseudoTransparency().
Referenced by main().
void KviApp::setupBegin ()
References __tr2qs, KviQString::ensureLastCharIs(), g_pSetupLibrary, getGlobalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, Modules, and KviMessageBox::warning().
Referenced by loadDirectories().
void KviApp::setupFileAssociations () [private]
References __tr2qs.
Referenced by loadDirectories().
void KviApp::setupFinish ()
References __tr2qs, g_pSetupLibrary, and KviMessageBox::warning().
Referenced by setup().
void KviApp::setupUriAssociations (const char * proto) [private]
Referenced by loadDirectories().
bool KviApp::supportsCompositing () [inline]
Referenced by KviTreeWindowListTreeWidget::paintEvent(), KviUserListViewArea::paintEvent(), KviThemedLineEdit::paintEvent(), KviThemedLabel::paintEvent(), KviThemedComboBox::paintEvent(), KviMdiManager::paintEvent(), KviIrcView::paintEvent(), KviToolBarGraphicalApplet::paintEvent(), and KviInputEditor::paintEvent().
void KviApp::timerEvent (QTimerEvent * e) [protected, virtual]
References heartbeat(), kvi_time_t, kvi_unixTime, and m_iHeartbeatTimerId.
KviConsole * KviApp::topmostConnectedConsole ()
References activeConsole(), KviPointerHashTableIterator< Key, T >::current(), g_pGlobalWindowDict, KviConsole::isConnected(), KVI_WINDOW_TYPE_CONSOLE, and KviWindow::type().
Referenced by heartbeat(), and KviKvsCoreFunctions::KVSCF().
void KviApp::triggerUpdateGui ()
References m_bUpdateGuiPending, and updateGui().
Referenced by optionResetUpdate().
void KviApp::unregisterWindow (KviWindow * wnd) [protected]
References g_pGlobalWindowDict, and KviWindow::id().
Referenced by KviWindow::~KviWindow().
void KviApp::updateApplicationFont () [private]
References g_pFrame, KVI_OPTION_BOOL, KVI_OPTION_FONT, KviOption_boolUseGlobalApplicationFont, KviOption_fontApplication, and m_fntDefaultFont.
Referenced by optionResetUpdate(), and setup().
void KviApp::updateGui () [slot]
References KviFrame::applyOptions(), g_pFrame, and m_bUpdateGuiPending.
Referenced by triggerUpdateGui().
void KviApp::updateNotifier () [signal]
Referenced by optionResetUpdate().
void KviApp::updatePseudoTransparency () [slot]
References g_pApp, g_pFrame, KVI_OPTION_BOOL, KVI_OPTION_PIXMAP, KviOption_boolUseCompositingForTransparency, KviOption_boolUseGlobalPseudoTransparency, KviOption_boolUseWindowsDesktopForTransparency, KviOption_pixmapGlobalTransparencyBackground, and KviFrame::updatePseudoTransparency().
Referenced by setup().
unsigned int KviApp::windowCount ()
References g_pGlobalWindowDict.
Referenced by KviWindow::~KviWindow().
bool KviApp::windowExists (KviWindow * wnd)
References KviPointerHashTableIterator< Key, T >::current(), and g_pGlobalWindowDict.
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsCallbackObject::execute(), fileDownloadTerminated(), KviKvsPopupMenu::itemClicked(), KviKvsRunTimeContext::leaveBlockingSection(), KviKvsAsyncDnsOperation::lookupTerminated(), KviServerParser::parseNumericEndOfWhois(), KviServerParser::parseNumericNoSuchNick(), KviServerParser::parseNumericNoSuchServer(), KviKvsReport::report(), KviKvsPopupMenu::setupMenuContents(), KviKvsTimerManager::timerEvent(), and KviKvsProcessAsyncOperation::trigger().
Friends And Related Function Documentation
friend class KviFrame [friend]
Referenced by createFrame().
friend class KviSetupWizard [friend]
friend class KviWindow [friend]
Member Data Documentation
bool KviApp::m_bCreateConfig
Referenced by KviApp(), and main().
bool KviApp::m_bFirstTimeRun [protected]
Referenced by loadDirectories().
bool KviApp::m_bSetupDone [protected]
Referenced by KviApp(), setup(), and ~KviApp().
bool KviApp::m_bShowSplashScreen
Referenced by KviApp(), main(), and setup().
bool KviApp::m_bUpdateGuiPending [protected]
Referenced by KviApp(), triggerUpdateGui(), and updateGui().
QFont KviApp::m_fntDefaultFont [protected]
Referenced by KviApp(), and updateApplicationFont().
int KviApp::m_iHeartbeatTimerId [protected]
Referenced by KviApp(), setup(), and timerEvent().
KviWindow* KviApp::m_pActiveWindow [protected]
KviIpcSentinel* KviApp::m_pIpcSentinel [protected]
Referenced by createIpcSentinel(), destroyIpcSentinel(), and KviApp().
KviPointerList<KviPendingAvatarChange>* KviApp::m_pPendingAvatarChanges [protected]
Referenced by fileDownloadTerminated(), findPendingAvatarChange(), KviApp(), setAvatarOnFileReceived(), and ~KviApp().
KviPointerHashTable<QString,QStringList>* KviApp::m_pRecentChannelDict [protected]
Referenced by addRecentChannel(), buildRecentChannels(), KviApp(), recentChannelsForNetwork(), saveRecentChannels(), and ~KviApp().
QString KviApp::m_szConfigFile
Referenced by findLocalKvircDirectory(), KviApp(), main(), and saveKvircDirectory().
KviStr KviApp::m_szExecAfterStartup
Referenced by createFrame(), and main().
QString KviApp::m_szGlobalKvircDir [protected]
Referenced by findGlobalKvircDirectory(), getGlobalKvircDirectory(), loadDirectories(), and setup().
QString KviApp::m_szLocalKvircDir [protected]
Referenced by checkLocalKvircDirectory(), findLocalKvircDirectory(), getLocalKvircDirectory(), saveKvircDirectory(), and setup().
The documentation for this class was generated from the following files:
src/kvirc/kernel/kvi_app.h
src/kvirc/kernel/kvi_app.cpp
src/kvirc/kernel/kvi_app_fs.cpp
src/kvirc/kernel/kvi_app_setup.cpp
src/kvirc/kernel/kvi_options.cpp