KVIrc: OptionsWidget_interfaceFeatures Class Reference
OptionsWidget_interfaceFeatures Class Reference
#include <OptionsWidget_interfaceFeatures.h>
Public Member Functions
virtual void commit ()
OptionsWidget_interfaceFeatures (QWidget *parent)
~OptionsWidget_interfaceFeatures ()
Protected Attributes
QCheckBox * m_pDisableSplash
Constructor & Destructor Documentation
OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), KviFileUtils::fileExists(), g, g_pApp, KviApplication::getLocalKvircDirectory(), KVI_VERSION, KviOption_boolConfirmCloseWhenThereAreConnections, KviOption_boolEnableVisualEffects, KviOption_boolHideWindowToolButtons, KviOption_boolShowChannelsJoinDialogAsToplevel, KviOption_boolShowGeneralOptionsDialogAsToplevel, KviOption_boolShowIdentityDialogAsToplevel, KviOption_boolShowRegisteredUsersDialogAsToplevel, KviOption_boolShowServersConnectDialogAsToplevel, KviOption_boolStartupMinimized, KviOption_boolWindowsRememberProperties, m_pDisableSplash, and KviApplication::Pics.
OptionsWidget_interfaceFeatures::~OptionsWidget_interfaceFeatures ()
Member Function Documentation
void OptionsWidget_interfaceFeatures::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KviFileUtils::fileExists(), g_pApp, KviApplication::getLocalKvircDirectory(), KVI_VERSION, m_pDisableSplash, KviApplication::Pics, KviFileUtils::removeFile(), and KviFileUtils::writeFile().
Member Data Documentation
QCheckBox* OptionsWidget_interfaceFeatures::m_pDisableSplash [protected]
Referenced by commit(), and OptionsWidget_interfaceFeatures().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_interfaceFeatures.h
src/modules/options/OptionsWidget_interfaceFeatures.cpp