KVIrc: KviModuleManager Class Reference
KviModuleManager Class Reference
#include <KviModuleManager.h>
Public Slots
void cleanupUnusedModules ()
Signals
void moduleAboutToUnload (KviModule *m)
Public Member Functions
void completeModuleNames (const QString &word, KviPointerList< QString > *matches)
KviModule * findModule (const QString &modName)
KviModule * getModule (const QString &modName)
bool hasLockedModules ()
KviModuleManager ()
QString & lastError ()
bool loadModule (const QString &modName)
void loadModulesByCaps (const QString &caps, const QString &dir)
void loadModulesByCaps (const QString &caps)
void unloadAllModules ()
bool unloadModule (const QString &modName)
bool unloadModule (KviModule *module)
~KviModuleManager ()
Protected Member Functions
void completeModuleNames (const QString &path, const QString &work, KviPointerList< QString > *matches)
Private Attributes
QTimer * m_pCleanupTimer
KviPointerHashTable< QString,
KviModule > * m_pModuleDict
QString m_szLastError
Constructor & Destructor Documentation
KviModuleManager::KviModuleManager ()
References cleanupUnusedModules(), connect(), m_pCleanupTimer, m_pModuleDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviModuleManager::~KviModuleManager ()
References m_pCleanupTimer, m_pModuleDict, and unloadAllModules().
Member Function Documentation
void KviModuleManager::cleanupUnusedModules () [slot]
References KviPointerList< T >::append(), _KviModuleInfo::can_unload, KviPointerHashTableIterator< Key, T >::current(), KviPointerList< T >::first(), KviModule::isLocked(), KVI_OPTION_UINT, KviOption_uintModuleCleanupTimeout, m_pModuleDict, KviModule::moduleInfo(), KviPointerList< T >::next(), KviModule::secondsSinceLastAccess(), KviPointerList< T >::setAutoDelete(), unloadModule(), and KviModule::updateAccessTime().
Referenced by KviModuleManager().
void KviModuleManager::completeModuleNames (const QString & word, KviPointerList< QString > * matches)
References g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), and KviApplication::Modules.
Referenced by KviKvsKernel::completeCommand(), and KviKvsKernel::completeFunction().
void KviModuleManager::completeModuleNames (const QString & path, const QString & work, KviPointerList< QString > * matches) [protected]
References KviPointerList< T >::append(), KviQString::cutFromLast(), KviQString::cutToFirst(), KviQString::cutToLast(), d, KviQString::equalCIN(), and KVI_PATH_SEPARATOR_CHAR.
KviModule * KviModuleManager::findModule (const QString & modName)
References KviPointerHashTable< Key, T >::find(), m, m_pModuleDict, and KviModule::updateAccessTime().
Referenced by loadModule(), and unloadModule().
KviModule * KviModuleManager::getModule (const QString & modName)
References KviPointerHashTable< Key, T >::find(), loadModule(), m, m_pModuleDict, and KviModule::updateAccessTime().
Referenced by KviModuleExtensionManager::allocateExtensionGetDescriptorList(), ScriptEditorWidget::asyncCompleterCreation(), KviKvsKernel::completeModuleCommand(), KviKvsKernel::completeModuleFunction(), KviScriptEditor::createInstance(), KviScriptEditor::destroyInstance(), KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviActionManager::getAction(), KviKvsCoreSimpleCommands::KVSCSC(), KviStatusBar::load(), loadModulesByCaps(), KviKvsObjectController::lookupClass(), OptionsWidget_soundGeneral::mediaAutoDetect(), OptionsWidget_soundGeneral::mediaFillBox(), KviApplication::notifierMessage(), ClassEditorWidget::oneTimeSetup(), KviIrcServerParser::parseCtcpRequestDcc(), perl_kvs_fnc_isAvailable(), perl_module_init(), python_kvs_fnc_isAvailable(), python_module_init(), OptionsWidget_soundGeneral::soundAutoDetect(), OptionsWidget_soundGeneral::soundFillBox(), and OptionsWidget_soundGeneral::soundTest().
bool KviModuleManager::hasLockedModules ()
References KviPointerHashTableIterator< Key, T >::current(), m, and m_pModuleDict.
QString& KviModuleManager::lastError () [inline]
Referenced by KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), and KviIrcServerParser::parseCtcpRequestDcc().
bool KviModuleManager::loadModule (const QString & modName)
References __tr2qs, _OUTPUT_VERBOSE, KviQString::appendFormatted(), KviFileUtils::fileExists(), findModule(), KviMainWindow::firstConsole(), g_pApp, g_pMainWindow, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), _KviModuleInfo::init_routine, KviPointerHashTable< Key, T >::insert(), KviLocale::instance(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_VERBOSE, kvi_strEqualCS(), KVI_VERSION, KviApplication::kviClosingDown(), KviOption_boolCleanupUnusedModules, KviOption_boolIgnoreModuleVersions, KviOption_uintModuleCleanupTimerInterval, KVIRC_MODULE_STRUCTURE_SYMBOL, KviLocale::loadCatalogue(), KviApplication::Locale, m_pCleanupTimer, m_pModuleDict, m_szLastError, KviApplication::Modules, KviWindow::output(), KviKvsModuleInterface::registerDefaultCommands(), _KviModuleInfo::szKVIrcVersion, _KviModuleInfo::szModuleContext, and KviLocale::unloadCatalogue().
Referenced by getModule(), and system_kvs_fnc_checkModule().
void KviModuleManager::loadModulesByCaps (const QString & caps, const QString & dir)
References KviQString::cutToLast(), d, getModule(), and KVI_PATH_SEPARATOR_CHAR.
Referenced by KviModuleExtensionManager::allocateExtension(), KviModuleExtensionManager::allocateExtensionGetDescriptorList(), KviStatusBar::appletsPopupAboutToShow(), KviModuleExtensionManager::getExtensionList(), OptionsWidget_servers::importPopupAboutToShow(), OptionsWidget_servers::importPopupActivated(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviActionManager::loadAllAvailableActions(), loadModulesByCaps(), and window_kvs_cmd_setCryptEngine().
void KviModuleManager::loadModulesByCaps (const QString & caps)
References g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), loadModulesByCaps(), and KviApplication::Plugins.
void KviModuleManager::moduleAboutToUnload (KviModule * m) [signal]
Referenced by unloadModule().
void KviModuleManager::unloadAllModules ()
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), KviPointerList< T >::first(), m_pModuleDict, KviPointerList< T >::next(), KviPointerList< T >::setAutoDelete(), and unloadModule().
Referenced by ~KviModuleManager().
bool KviModuleManager::unloadModule (const QString & modName)
References findModule().
Referenced by cleanupUnusedModules(), default_module_kvs_cmd_unload(), and unloadAllModules().
bool KviModuleManager::unloadModule (KviModule * module)
References __tr2qs, _OUTPUT_VERBOSE, _KviModuleInfo::cleanup_routine, KviMainWindow::firstConsole(), g_pApp, g_pMainWindow, KviModule::handle(), KviLocale::instance(), KviPointerHashTable< Key, T >::isEmpty(), KVI_OUT_VERBOSE, KviApplication::kviClosingDown(), m_pCleanupTimer, m_pModuleDict, moduleAboutToUnload(), KviModule::moduleInfo(), KviModule::name(), KviWindow::output(), KviPointerHashTable< Key, T >::remove(), and KviLocale::unloadCatalogue().
Member Data Documentation
QTimer* KviModuleManager::m_pCleanupTimer [private]
Referenced by KviModuleManager(), loadModule(), unloadModule(), and ~KviModuleManager().
KviPointerHashTable<QString,KviModule>* KviModuleManager::m_pModuleDict [private]
Referenced by cleanupUnusedModules(), findModule(), getModule(), hasLockedModules(), KviModuleManager(), loadModule(), unloadAllModules(), unloadModule(), and ~KviModuleManager().
QString KviModuleManager::m_szLastError [private]
Referenced by loadModule().
The documentation for this class was generated from the following files:
src/kvirc/module/KviModuleManager.h
src/kvirc/module/KviModuleManager.cpp