KVIrc: RawEditorWidget Class Reference
RawEditorWidget Class Reference
#include <RawEditorWindow.h>
Public Member Functions
void commit ()
void getExportEventBuffer (QString &szBuffer, RawHandlerTreeWidgetItem *it)
void getUniqueHandlerName (RawTreeWidgetItem *it, QString &buffer)
RawEditorWidget (QWidget *par)
void saveLastEditedItem ()
~RawEditorWidget ()
Public Attributes
bool m_bOneTimeSetupDone
KviTalPopupMenu * m_pContextPopup
KviScriptEditor * m_pEditor
RawHandlerTreeWidgetItem * m_pLastEditedItem
QLineEdit * m_pNameEditor
RawTreeWidget * m_pTreeWidget
Protected Slots
void addHandlerForCurrentRaw ()
void addRaw ()
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *)
void customContextMenuRequested (const QPoint &pnt)
void exportAllEvents ()
void exportCurrentHandler ()
void removeCurrentHandler ()
void toggleCurrentHandlerEnabled ()
Protected Member Functions
void showEvent (QShowEvent *e)
Private Member Functions
void oneTimeSetup ()
Constructor & Destructor Documentation
RawEditorWidget::RawEditorWidget (QWidget * par)
References __tr2qs_ctx(), connect(), KviScriptEditor::createInstance(), currentItemChanged(), customContextMenuRequested(), exportAllEvents(), l, m_bOneTimeSetupDone, m_pContextPopup, m_pEditor, m_pLastEditedItem, m_pNameEditor, m_pTreeWidget, and spl.
RawEditorWidget::~RawEditorWidget ()
References KviScriptEditor::destroyInstance(), and m_pEditor.
Member Function Documentation
void RawEditorWidget::addHandlerForCurrentRaw () [protected, slot]
References __tr2qs_ctx(), getUniqueHandlerName(), KVI_ASSERT, m_bOneTimeSetupDone, m_pTreeWidget, and RawTreeWidgetItem::setEnabled().
Referenced by addRaw(), and customContextMenuRequested().
void RawEditorWidget::addRaw () [protected, slot]
References __tr2qs_ctx(), addHandlerForCurrentRaw(), i, and m_pTreeWidget.
Referenced by customContextMenuRequested().
void RawEditorWidget::commit (void)
References KviKvsEventManager::addRawHandler(), g_pApp, i, KviKvsEventManager::instance(), j, m_bOneTimeSetupDone, m_pTreeWidget, KviKvsEventManager::removeAllScriptRawHandlers(), s, saveLastEditedItem(), and KviApplication::saveRawEvents().
Referenced by RawEditorWindow::applyClicked(), and RawEditorWindow::okClicked().
void RawEditorWidget::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem *) [protected, slot]
References __tr2qs_ctx(), KVI_ASSERT, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, m_pNameEditor, saveLastEditedItem(), and KviScriptEditor::setText().
Referenced by RawEditorWidget(), and toggleCurrentHandlerEnabled().
void RawEditorWidget::customContextMenuRequested (const QPoint & pnt) [protected, slot]
References __tr2qs_ctx(), addHandlerForCurrentRaw(), addRaw(), KviTalPopupMenu::clear(), exportCurrentHandler(), KviIconManager::Folder, g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Handler, KviIconManager::HandlerDisabled, KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KVI_ASSERT, m_bOneTimeSetupDone, m_pContextPopup, m_pTreeWidget, KviIconManager::Quit, KviIconManager::RawEvent, removeCurrentHandler(), and toggleCurrentHandlerEnabled().
Referenced by RawEditorWidget().
void RawEditorWidget::exportAllEvents () [protected, slot]
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), getExportEventBuffer(), i, j, KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, m_pTreeWidget, saveLastEditedItem(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by RawEditorWidget().
void RawEditorWidget::exportCurrentHandler () [protected, slot]
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), getExportEventBuffer(), KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, m_pLastEditedItem, saveLastEditedItem(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by customContextMenuRequested().
void RawEditorWidget::getExportEventBuffer (QString & szBuffer, RawHandlerTreeWidgetItem * it)
References KviCommandFormatter::blockFromBuffer(), RawHandlerTreeWidgetItem::m_bEnabled, and RawHandlerTreeWidgetItem::m_szBuffer.
Referenced by exportAllEvents(), and exportCurrentHandler().
void RawEditorWidget::getUniqueHandlerName (RawTreeWidgetItem * it, QString & buffer)
References __tr2qs_ctx(), KviQString::equalCI(), i, KVI_ASSERT, and m_bOneTimeSetupDone.
Referenced by addHandlerForCurrentRaw(), and saveLastEditedItem().
void RawEditorWidget::oneTimeSetup () [private]
References KviPointerList< T >::first(), i, KviKvsEventManager::instance(), l, m_bOneTimeSetupDone, m_pTreeWidget, KviOsInfo::name(), KviPointerList< T >::next(), KviKvsEventManager::rawHandlers(), s, and KviKvsEventHandler::Script.
Referenced by showEvent().
void RawEditorWidget::removeCurrentHandler () [protected, slot]
References KVI_ASSERT, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, m_pNameEditor, and RawTreeWidgetItem::setEnabled().
Referenced by customContextMenuRequested().
void RawEditorWidget::saveLastEditedItem ()
References KviQString::equalCI(), KviScriptEditor::getText(), getUniqueHandlerName(), KVI_ASSERT, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, m_pNameEditor, RawHandlerTreeWidgetItem::m_szBuffer, and RawHandlerTreeWidgetItem::setName().
Referenced by commit(), currentItemChanged(), exportAllEvents(), and exportCurrentHandler().
void RawEditorWidget::showEvent (QShowEvent * e) [protected]
References oneTimeSetup().
void RawEditorWidget::toggleCurrentHandlerEnabled () [protected, slot]
References currentItemChanged(), KVI_ASSERT, RawHandlerTreeWidgetItem::m_bEnabled, m_bOneTimeSetupDone, m_pLastEditedItem, and RawHandlerTreeWidgetItem::setEnabled().
Referenced by customContextMenuRequested().
Member Data Documentation
bool RawEditorWidget::m_bOneTimeSetupDone
Referenced by addHandlerForCurrentRaw(), commit(), currentItemChanged(), customContextMenuRequested(), getUniqueHandlerName(), oneTimeSetup(), RawEditorWidget(), removeCurrentHandler(), saveLastEditedItem(), and toggleCurrentHandlerEnabled().
KviTalPopupMenu* RawEditorWidget::m_pContextPopup
Referenced by customContextMenuRequested(), and RawEditorWidget().
KviScriptEditor* RawEditorWidget::m_pEditor
Referenced by currentItemChanged(), RawEditorWidget(), removeCurrentHandler(), saveLastEditedItem(), and ~RawEditorWidget().
RawHandlerTreeWidgetItem* RawEditorWidget::m_pLastEditedItem
Referenced by currentItemChanged(), exportCurrentHandler(), RawEditorWidget(), removeCurrentHandler(), saveLastEditedItem(), and toggleCurrentHandlerEnabled().
QLineEdit* RawEditorWidget::m_pNameEditor
Referenced by currentItemChanged(), RawEditorWidget(), removeCurrentHandler(), and saveLastEditedItem().
RawTreeWidget* RawEditorWidget::m_pTreeWidget
Referenced by addHandlerForCurrentRaw(), addRaw(), commit(), customContextMenuRequested(), exportAllEvents(), oneTimeSetup(), and RawEditorWidget().
The documentation for this class was generated from the following files:
src/modules/raweditor/RawEditorWindow.h
src/modules/raweditor/RawEditorWindow.cpp