KVIrc: KviKvsTreeNodeSpecialCommandSwitchLabelRegexp Class Reference
KviKvsTreeNodeSpecialCommandSwitchLabelRegexp Class Reference
#include <KviKvsTreeNodeSpecialCommandSwitch.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool execute (KviKvsRunTimeContext *c, KviKvsVariant *pRealParameter, bool *bPassThrough)
KviKvsTreeNodeSpecialCommandSwitchLabelRegexp (const QChar *pLocation)
~KviKvsTreeNodeSpecialCommandSwitchLabelRegexp ()
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::KviKvsTreeNodeSpecialCommandSwitchLabelRegexp (const QChar * pLocation)
KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::~KviKvsTreeNodeSpecialCommandSwitchLabelRegexp ()
Member Function Documentation
void KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
References KviKvsTreeNodeInstruction::dump(), KviKvsTreeNodeData::dump(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, and KviKvsTreeNodeSpecialCommandSwitchLabel::m_pParameter.
bool KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::execute (KviKvsRunTimeContext * c, KviKvsVariant * pRealParameter, bool * bPassThrough) [virtual]
Implements KviKvsTreeNodeSpecialCommandSwitchLabel.
References KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_bHasTerminatingBreak, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pParameter, KviKvsRunTimeContext::setBreakPending(), and v.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandSwitch.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandSwitch.cpp