KVIrc: KviThemedTreeWidget Class Reference
KviThemedTreeWidget Class Reference
#include <KviThemedTreeWidget.h>
Public Member Functions
void applyOptions ()
int dummyRead () const
KviThemedTreeWidget (QWidget *par, KviWindow *pWindow, const char *name)
~KviThemedTreeWidget ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
KviWindow * m_pKviWindow
Properties
int TransparencyCapable
Constructor & Destructor Documentation
KviThemedTreeWidget::KviThemedTreeWidget (QWidget * par, KviWindow * pWindow, const char * name)
References applyOptions(), and m_pKviWindow.
KviThemedTreeWidget::~KviThemedTreeWidget () default
Member Function Documentation
void KviThemedTreeWidget::applyOptions ()
References KviControlCodes::Bold, g_pApp, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_FONT, KVI_OPTION_MIRCCOLOR, KVI_OPTION_MSGTYPE, KVI_OUT_NONE, KviOption_boolUseCompositingForTransparency, KviOption_colorLabelBackground, KviOption_colorLabelForeground, KviOption_fontLabel, KviRuntimeInfo::name(), and KviApplication::supportsCompositing().
Referenced by LinksWindow::applyOptions(), ListWindow::applyOptions(), and KviThemedTreeWidget().
int KviThemedTreeWidget::dummyRead () const inline
void KviThemedTreeWidget::paintEvent (QPaintEvent * event) protected virtual
References g_pApp, g_pMainWindow, KviWindow::isDocked(), KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_uintGlobalTransparencyChildFadeFactor, m_pKviWindow, p, and KviApplication::supportsCompositing().
Member Data Documentation
KviWindow* KviThemedTreeWidget::m_pKviWindow protected
Referenced by KviThemedTreeWidget(), and paintEvent().
Property Documentation
int KviThemedTreeWidget::TransparencyCapable read
The documentation for this class was generated from the following files:
src/kvirc/ui/KviThemedTreeWidget.h
src/kvirc/ui/KviThemedTreeWidget.cpp