KVIrc: KviKvsTreeNodeRebindingSwitch Class Reference
KviKvsTreeNodeRebindingSwitch Class Reference
#include <KviKvsTreeNodeRebindingSwitch.h>
Public Member Functions
const QString & commandName ()
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeRebindingSwitch (const QChar *pLocation, KviKvsTreeNodeData *pTargetWindow, KviKvsTreeNodeCommand *pChildCommand)
~KviKvsTreeNodeRebindingSwitch ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeCommand * m_pChildCommand
KviKvsTreeNodeData * m_pTargetWindow
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeRebindingSwitch::KviKvsTreeNodeRebindingSwitch (const QChar * pLocation, KviKvsTreeNodeData * pTargetWindow, KviKvsTreeNodeCommand * pChildCommand)
References m_pChildCommand, m_pTargetWindow, and KviKvsTreeNode::setParent().
KviKvsTreeNodeRebindingSwitch::~KviKvsTreeNodeRebindingSwitch ()
References m_pChildCommand, and m_pTargetWindow.
Member Function Documentation
const QString & KviKvsTreeNodeRebindingSwitch::commandName ()
References KviKvsTreeNodeCommand::commandName(), and m_pChildCommand.
void KviKvsTreeNodeRebindingSwitch::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeCommand.
void KviKvsTreeNodeRebindingSwitch::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeCommand.
References KviKvsTreeNodeCommand::dump(), KviKvsTreeNodeData::dump(), m_pChildCommand, and m_pTargetWindow.
bool KviKvsTreeNodeRebindingSwitch::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviApplication::findWindow(), g_pApp, m_pChildCommand, m_pTargetWindow, KviKvsRunTimeContext::setWindow(), KviKvsRunTimeContext::warning(), and KviKvsRunTimeContext::window().
Member Data Documentation
KviKvsTreeNodeCommand* KviKvsTreeNodeRebindingSwitch::m_pChildCommand protected
Referenced by commandName(), dump(), execute(), KviKvsTreeNodeRebindingSwitch(), and ~KviKvsTreeNodeRebindingSwitch().
KviKvsTreeNodeData* KviKvsTreeNodeRebindingSwitch::m_pTargetWindow protected
Referenced by dump(), execute(), KviKvsTreeNodeRebindingSwitch(), and ~KviKvsTreeNodeRebindingSwitch().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeRebindingSwitch.h
src/kvirc/kvs/tree/KviKvsTreeNodeRebindingSwitch.cpp