KVIrc: KviKvsTreeNodeCoreSimpleCommand Class Reference
KviKvsTreeNodeCoreSimpleCommand Class Reference
#include <KviKvsTreeNodeCoreSimpleCommand.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeCoreSimpleCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params, KviKvsCoreSimpleCommandExecRoutine *r)
~KviKvsTreeNodeCoreSimpleCommand ()
Public Member Functions inherited from KviKvsTreeNodeSimpleCommand
KviKvsTreeNodeSimpleCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
~KviKvsTreeNodeSimpleCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommandWithParameters
void dumpParameterList (const char *prefix)
KviKvsTreeNodeCommandWithParameters (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
KviKvsTreeNodeDataList * params ()
~KviKvsTreeNodeCommandWithParameters ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviKvsCoreSimpleCommandExecRoutine * m_pExecRoutine
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeCommandWithParameters
KviKvsTreeNodeDataList * m_pParams
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeCoreSimpleCommand::KviKvsTreeNodeCoreSimpleCommand (const QChar * pLocation, const QString & szCmdName, KviKvsTreeNodeDataList * params, KviKvsCoreSimpleCommandExecRoutine * r)
References m_pExecRoutine, and r.
KviKvsTreeNodeCoreSimpleCommand::~KviKvsTreeNodeCoreSimpleCommand ()
Member Function Documentation
void KviKvsTreeNodeCoreSimpleCommand::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommand::m_szCmdName.
void KviKvsTreeNodeCoreSimpleCommand::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommandWithParameters::dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), and KviKvsTreeNodeCommand::m_szCmdName.
bool KviKvsTreeNodeCoreSimpleCommand::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsTreeNodeDataList::evaluate(), KviKvsTreeNodeSwitchList::evaluate(), l, m_pExecRoutine, KviKvsTreeNodeCommandWithParameters::m_pParams, KviKvsTreeNodeCommand::m_pSwitches, _KviKvsCoreSimpleCommandExecRoutine::proc, KviKvsVariantList::setAutoDelete(), KviKvsRunTimeContext::setDefaultReportLocation(), and swl.
Member Data Documentation
KviKvsCoreSimpleCommandExecRoutine* KviKvsTreeNodeCoreSimpleCommand::m_pExecRoutine private
Referenced by execute(), and KviKvsTreeNodeCoreSimpleCommand().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeCoreSimpleCommand.h
src/kvirc/kvs/tree/KviKvsTreeNodeCoreSimpleCommand.cpp