KVIrc: KviKvsDnsObject Class Reference
KviKvsDnsObject Class Reference
#include <kvi_kvs_dnsmanager.h>
Public Member Functions
KviKvsScript * callback ()
KviDns * dns ()
KviKvsDnsObject (KviDns *pDns, KviWindow *pWnd, const QString &szQuery, bool bRebindOnWindowClose=true, KviKvsScript *pCallback=0, KviKvsVariantList *pParameterList=0)
KviKvsVariantList * parameterList ()
const QString & query ()
bool rebindOnWindowClose ()
void setParameterList (KviKvsVariantList *pList)
void setWindow (KviWindow *pWnd)
KviWindow * window ()
~KviKvsDnsObject ()
Protected Attributes
bool m_bRebindOnWindowClose
KviKvsScript * m_pCallback
KviDns * m_pDns
KviKvsVariantList * m_pParameterList
KviWindow * m_pWindow
QString m_szQuery
Constructor & Destructor Documentation
KviKvsDnsObject::KviKvsDnsObject (KviDns * pDns, KviWindow * pWnd, const QString & szQuery, bool bRebindOnWindowClose = true, KviKvsScript * pCallback = 0, KviKvsVariantList * pParameterList = 0)
References m_bRebindOnWindowClose, m_pCallback, m_pDns, m_pParameterList, m_pWindow, and m_szQuery.
KviKvsDnsObject::~KviKvsDnsObject ()
References KviDns::isRunning(), m_pCallback, m_pDns, and m_pParameterList.
Member Function Documentation
KviKvsScript* KviKvsDnsObject::callback () [inline]
References m_pCallback.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
KviDns* KviKvsDnsObject::dns () [inline]
References m_pDns.
Referenced by KviKvsDnsManager::addDns(), and KviKvsDnsManager::dnsLookupTerminated().
KviKvsVariantList* KviKvsDnsObject::parameterList () [inline]
References m_pParameterList.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
const QString& KviKvsDnsObject::query () [inline]
References m_szQuery.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
bool KviKvsDnsObject::rebindOnWindowClose () [inline]
References m_bRebindOnWindowClose.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
void KviKvsDnsObject::setParameterList (KviKvsVariantList * pList) [inline]
References m_pParameterList.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
void KviKvsDnsObject::setWindow (KviWindow * pWnd) [inline]
References m_pWindow.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
KviWindow* KviKvsDnsObject::window () [inline]
References m_pWindow.
Referenced by KviKvsDnsManager::dnsLookupTerminated().
Member Data Documentation
bool KviKvsDnsObject::m_bRebindOnWindowClose [protected]
Referenced by KviKvsDnsObject(), and rebindOnWindowClose().
KviKvsScript* KviKvsDnsObject::m_pCallback [protected]
Referenced by callback(), KviKvsDnsObject(), and ~KviKvsDnsObject().
KviDns* KviKvsDnsObject::m_pDns [protected]
Referenced by dns(), KviKvsDnsObject(), and ~KviKvsDnsObject().
KviKvsVariantList* KviKvsDnsObject::m_pParameterList [protected]
Referenced by KviKvsDnsObject(), parameterList(), setParameterList(), and ~KviKvsDnsObject().
KviWindow* KviKvsDnsObject::m_pWindow [protected]
Referenced by KviKvsDnsObject(), setWindow(), and window().
QString KviKvsDnsObject::m_szQuery [protected]
Referenced by KviKvsDnsObject(), and query().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_dnsmanager.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_dnsmanager.cpp