KVIrc: KviInputEditor::EditCommand Class Reference
KviInputEditor::EditCommand Class Reference
Holds the command used in the {un,re}do operations.
#include <kvi_input_editor.h>
Public Types
enum Type { InsertText, RemoveText }
Defines the type of the command.
Public Member Functions
EditCommand (Type eType, const QString &szText, int iStartPosition)
Contructs the command object.
void setStartPosition (int iStartPosition)
Sets the start position.
void setText (const QString &szText)
Sets the text of the command.
void setType (const Type &eType)
Sets the type of the command.
int startPosition () const
Returns the start position.
const QString & text () const
Returns the text of the command.
const Type & type () const
Returns the type of the command.
Private Attributes
Type m_eType
The type of the command.
int m_iStartPosition
The start position.
QString m_szText
The text of the command.
Detailed Description
Holds the command used in the {un,re}do operations.
Member Enumeration Documentation
enum KviInputEditor::EditCommand::Type
Defines the type of the command.
Enumerator:
InsertText
Text insertion. Has text, position previous to the insert and length of the insert
RemoveText
Text removal, Has text, position previous to the removal and length of the removed data
Constructor & Destructor Documentation
KviInputEditor::EditCommand::EditCommand (Type eType, const QString & szText, int iStartPosition) [inline]
Contructs the command object.
Parameters:
eType The type of the command
szText The text of the command
iStartPosition The start position of the command
Returns:
EditCommand
Member Function Documentation
void KviInputEditor::EditCommand::setStartPosition (int iStartPosition) [inline]
Sets the start position.
Parameters:
iStartPosition The position
Returns:
void
void KviInputEditor::EditCommand::setText (const QString & szText) [inline]
Sets the text of the command.
Parameters:
szText The text to set
void KviInputEditor::EditCommand::setType (const Type & eType) [inline]
Sets the type of the command.
Parameters:
eType The type of the command
Returns:
void
int KviInputEditor::EditCommand::startPosition () const [inline]
Returns the start position.
Returns:
int
Referenced by KviInputEditor::redo(), and KviInputEditor::undo().
const QString& KviInputEditor::EditCommand::text () const [inline]
Returns the text of the command.
Returns:
const QString &
Referenced by KviInputEditor::redo(), and KviInputEditor::undo().
const Type& KviInputEditor::EditCommand::type () const [inline]
Returns the type of the command.
Returns:
const Type &
Referenced by KviInputEditor::redo(), and KviInputEditor::undo().
Member Data Documentation
KviInputEditor::EditCommand::m_eType [private]
The type of the command.
KviInputEditor::EditCommand::m_iStartPosition [private]
The start position.
KviInputEditor::EditCommand::m_szText [private]
The text of the command.
The documentation for this class was generated from the following file:
src/kvirc/ui/kvi_input_editor.h