KVIrc: KviKvsTreeNodeSpecialCommandDefpopup Class Reference
KviKvsTreeNodeSpecialCommandDefpopup Class Reference
#include <KviKvsTreeNodeSpecialCommandDefpopup.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandDefpopup (const QChar *pLocation, KviKvsTreeNodeData *pPopupName, KviKvsTreeNodeSpecialCommandDefpopupLabelPopup *pMainPopup)
~KviKvsTreeNodeSpecialCommandDefpopup ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommand
KviKvsTreeNodeSpecialCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeSpecialCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup * m_pMainPopup
KviKvsTreeNodeData * m_pPopupName
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandDefpopup::KviKvsTreeNodeSpecialCommandDefpopup (const QChar * pLocation, KviKvsTreeNodeData * pPopupName, KviKvsTreeNodeSpecialCommandDefpopupLabelPopup * pMainPopup)
References m_pMainPopup, m_pPopupName, and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandDefpopup::~KviKvsTreeNodeSpecialCommandDefpopup ()
References m_pMainPopup, and m_pPopupName.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandDefpopup::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandDefpopup::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
References KviKvsTreeNodeData::dump(), KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::dump(), m_pMainPopup, and m_pPopupName.
bool KviKvsTreeNodeSpecialCommandDefpopup::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsPopupManager::add(), KviKvsVariant::asString(), KviKvsPopupMenu::doClear(), KviKvsPopupManager::emitRefresh(), KviKvsRunTimeContext::error(), KviKvsTreeNodeSwitchList::evaluate(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::fill(), KviKvsSwitchList::find(), KviKvsPopupManager::instance(), KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::isEmpty(), KviKvsPopupMenu::isHardLocked(), KviKvsPopupManager::lookup(), m_pMainPopup, m_pPopupName, KviKvsTreeNodeCommand::m_pSwitches, KviKvsPopupManager::remove(), swl, and v.
Member Data Documentation
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup* KviKvsTreeNodeSpecialCommandDefpopup::m_pMainPopup private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandDefpopup(), and ~KviKvsTreeNodeSpecialCommandDefpopup().
KviKvsTreeNodeData* KviKvsTreeNodeSpecialCommandDefpopup::m_pPopupName private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandDefpopup(), and ~KviKvsTreeNodeSpecialCommandDefpopup().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandDefpopup.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandDefpopup.cpp