KVIrc: KviSoundSelector Class Reference
KviSoundSelector Class Reference
#include <KviSelectors.h>
Public Member Functions
KviSoundSelector (QWidget *par, const QString &txt, QString *pOption, bool bEnabled)
virtual void setEnabled (bool bEnabled)
~KviSoundSelector ()
Public Member Functions inherited from KviFileSelector
virtual void commit ()
KviFileSelector (QWidget *par, const QString &txt, QString *pOption, bool bEnabled, unsigned int uFlags=0, const QString &szFilter=QString())
void setSelection (const QString &szSelection)
void setTmpFile (QString &szFile)
QString tmpFile ()
~KviFileSelector ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Attributes
QPushButton * m_pPlayButton
Protected Attributes inherited from KviFileSelector
QGridLayout * m_Layout
QPushButton * m_pButton
QLabel * m_pLabel
QLineEdit * m_pLineEdit
QString * m_pOption
QString m_szFilter
unsigned int m_uFlags
Private Slots
void playSound ()
Additional Inherited Members
Public Types inherited from KviFileSelector
enum Flags { ChooseSaveFileName = 1, DontConfirmOverwrite = 2, VerticalLayout = 4 }
Public Slots inherited from KviFileSelector
Signals inherited from KviFileSelector
void selectionChanged (const QString &szNewValue)
Protected Member Functions inherited from KviFileSelector
virtual void select ()
Properties inherited from KviFileSelector
QString tmpFile
Constructor & Destructor Documentation
KviSoundSelector::KviSoundSelector (QWidget * par, const QString & txt, QString * pOption, bool bEnabled)
References __tr2qs, connect(), KviFileSelector::m_Layout, m_pPlayButton, KviFileSelector::m_uFlags, playSound(), and KviFileSelector::VerticalLayout.
KviSoundSelector::~KviSoundSelector ()
Member Function Documentation
void KviSoundSelector::playSound () private slot
References KviFileSelector::m_pLineEdit, and KviKvsScript::run().
Referenced by KviSoundSelector().
void KviSoundSelector::setEnabled (bool bEnabled) virtual
Reimplemented from KviFileSelector.
References m_pPlayButton, and KviFileSelector::setEnabled().
Member Data Documentation
QPushButton* KviSoundSelector::m_pPlayButton protected
Referenced by KviSoundSelector(), and setEnabled().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp