KVIrc: KviThemeInfo Class Reference
KviThemeInfo Class Reference
A set of information about a KVIrc theme.
#include <KviTheme.h>
Public Member Functions
const QString & application ()
const QString & author ()
const QString & date ()
const QString & description ()
const QString & dirName ()
void getCompleteDirPath (QString &szBuffer)
bool isBuiltin ()
KviThemeInfo ()
const QPixmap & largeScreenshot ()
const QString & lastError ()
bool load (const QString &szThemeFileName, bool bBuiltin=false)
const QPixmap & mediumScreenshot ()
const QString & name ()
bool save (const QString &szThemeFileName)
void setApplication (const QString &szApplication)
void setAuthor (const QString &szAuthor)
void setDate (const QString &szDate)
void setDescription (const QString &szDescription)
void setLastError (const QString &szLastError)
void setName (const QString &szName)
void setSubdirectory (const QString &szSubdirectory)
void setThemeEngineVersion (const QString &szThemeEngineVersion)
void setVersion (const QString &szVersion)
const QPixmap & smallScreenshot ()
QString smallScreenshotPath ()
const QString & subdirectory ()
const QString & themeEngineVersion ()
const QString & version ()
~KviThemeInfo ()
Protected Attributes
bool m_bBuiltin
QPixmap m_pixScreenshotLarge
QPixmap m_pixScreenshotMedium
QPixmap m_pixScreenshotSmall
QString m_szApplication
QString m_szAuthor
QString m_szDate
QString m_szDescription
QString m_szDirName
QString m_szLastError
QString m_szName
QString m_szSubdirectory
QString m_szThemeEngineVersion
QString m_szVersion
Detailed Description
A set of information about a KVIrc theme.
This object contains a set of information about a theme that can be read and stored to a standard KVIrc configuration file (which is usually named themeinfo.kvc but this is not strictly necessary).
Constructor & Destructor Documentation
KviThemeInfo::KviThemeInfo ()
References m_bBuiltin.
KviThemeInfo::~KviThemeInfo ()
Member Function Documentation
const QString& KviThemeInfo::application () inline
Referenced by PackThemeDataWidget::parseThemes().
const QString& KviThemeInfo::author () inline
Referenced by PackThemeDataWidget::parseThemes(), SaveThemeDialog::SaveThemeDialog(), theme_kvs_fnc_info(), and ThemeListWidgetItem::ThemeListWidgetItem().
const QString& KviThemeInfo::date () inline
Referenced by PackThemeDataWidget::parseThemes().
const QString& KviThemeInfo::description () inline
Referenced by PackThemeDataWidget::parseThemes(), SaveThemeDialog::SaveThemeDialog(), theme_kvs_fnc_info(), and ThemeListWidgetItem::ThemeListWidgetItem().
const QString& KviThemeInfo::dirName () inline
Referenced by ThemeManagementDialog::applyCurrentTheme(), and ThemeManagementDialog::contextMenuRequested().
void KviThemeInfo::getCompleteDirPath (QString & szBuffer) inline
References KviQString::ensureLastCharIs(), g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, and KviApplication::Themes.
Referenced by ThemeManagementDialog::deleteTheme(), largeScreenshot(), load(), KviTheme::load(), mediumScreenshot(), KviTheme::save(), KviTheme::saveScreenshots(), smallScreenshot(), and smallScreenshotPath().
bool KviThemeInfo::isBuiltin () inline
Referenced by ThemeManagementDialog::applyCurrentTheme(), ThemeManagementDialog::contextMenuRequested(), ThemeManagementDialog::deleteTheme(), and ThemeManagementDialog::enableDisableButtons().
const QPixmap & KviThemeInfo::largeScreenshot ()
Attempt to load the theme screenshot from THEMEDIR/screenshot_*.png This function will work only if the absoluteDirectory() of the theme has been set, otherwise the returned pixmap will be null.
References getCompleteDirPath(), KVI_THEME_LARGE_SCREENSHOT_NAME, and m_pixScreenshotLarge.
Referenced by mediumScreenshot().
const QString& KviThemeInfo::lastError () inline
Referenced by ThemeManagementDialog::applyCurrentTheme(), SaveThemeDialog::saveTheme(), and theme_kvs_cmd_apply().
bool KviThemeInfo::load (const QString & szThemeFileName, bool bBuiltin = false)
load data from a specified theme config file
References __tr2qs, KviMiscUtils::compareVersions(), KviFileUtils::fileExists(), getCompleteDirPath(), KVI_CURRENT_THEME_ENGINE_VERSION, KVI_THEMEDATA_FILE_NAME, KVI_THEMEINFO_CONFIG_GROUP, KVI_THEMEINFO_FILE_NAME, m_bBuiltin, m_szApplication, m_szAuthor, m_szDate, m_szDescription, m_szDirName, m_szLastError, m_szName, m_szSubdirectory, m_szThemeEngineVersion, m_szVersion, KviConfigurationFile::Read, KviConfigurationFile::readEntry(), and KviConfigurationFile::setGroup().
Referenced by ThemeManagementDialog::fillThemeBox(), KviTheme::load(), SaveThemeDialog::SaveThemeDialog(), theme_kvs_cmd_apply(), and theme_kvs_fnc_info().
const QPixmap & KviThemeInfo::mediumScreenshot ()
Attempt to load the theme screenshot from THEMEDIR/screenshot_*.png This function will work only if the absoluteDirectory() of the theme has been set, otherwise the returned pixmap will be null.
References getCompleteDirPath(), KVI_THEME_MEDIUM_SCREENSHOT_NAME, largeScreenshot(), m_pixScreenshotMedium, and QIMAGE_SCALE_MIN.
Referenced by smallScreenshot().
const QString& KviThemeInfo::name () inline
Referenced by ThemeManagementDialog::applyCurrentTheme(), ThemeManagementDialog::deleteTheme(), PackThemeDataWidget::parseThemes(), SaveThemeDialog::saveTheme(), SaveThemeDialog::SaveThemeDialog(), theme_kvs_cmd_apply(), theme_kvs_fnc_info(), and ThemeListWidgetItem::ThemeListWidgetItem().
bool KviThemeInfo::save (const QString & szThemeFileName)
save the currently defined theme configuration in the specified file
References KviConfigurationFile::clear(), KVI_CURRENT_THEME_ENGINE_VERSION, KVI_SOURCES_DATE, KVI_THEMEINFO_CONFIG_GROUP, KVI_VERSION, m_szAuthor, m_szDate, m_szDescription, m_szName, m_szVersion, KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviTheme::save().
void KviThemeInfo::setApplication (const QString & szApplication) inline
Referenced by SaveThemeDialog::saveTheme().
void KviThemeInfo::setAuthor (const QString & szAuthor) inline
Referenced by SaveThemeDialog::saveTheme().
void KviThemeInfo::setDate (const QString & szDate) inline
Referenced by SaveThemeDialog::saveTheme().
void KviThemeInfo::setDescription (const QString & szDescription) inline
Referenced by SaveThemeDialog::saveTheme().
void KviThemeInfo::setLastError (const QString & szLastError) inline
Referenced by KviTheme::save(), and KviTheme::saveScreenshots().
void KviThemeInfo::setName (const QString & szName) inline
Referenced by SaveThemeDialog::saveTheme().
void KviThemeInfo::setSubdirectory (const QString & szSubdirectory) inline
Referenced by ThemeManagementDialog::fillThemeBox(), SaveThemeDialog::saveTheme(), and theme_kvs_cmd_apply().
void KviThemeInfo::setThemeEngineVersion (const QString & szThemeEngineVersion) inline
void KviThemeInfo::setVersion (const QString & szVersion) inline
Referenced by SaveThemeDialog::saveTheme().
const QPixmap & KviThemeInfo::smallScreenshot ()
Attempt to load the theme screenshot from THEMEDIR/screenshot_*.png This function will work only if the absoluteDirectory() of the theme has been set, otherwise the returned pixmap will be null.
References getCompleteDirPath(), KVI_THEME_SMALL_SCREENSHOT_NAME, m_pixScreenshotSmall, mediumScreenshot(), and QIMAGE_SCALE_MIN.
Referenced by ThemeManagementDialog::fillThemeBox(), and PackThemeDataWidget::parseThemes().
QString KviThemeInfo::smallScreenshotPath ()
Attempt to load the theme screenshot from THEMEDIR/screenshot_*.png This function will work only if the absoluteDirectory() of the theme has been set, otherwise the returned pixmap will be null.
References getCompleteDirPath(), and KVI_THEME_SMALL_SCREENSHOT_NAME.
Referenced by PackThemeDataWidget::parseThemes().
const QString& KviThemeInfo::subdirectory () inline
Referenced by PackThemeDataWidget::parseThemes(), KviTheme::save(), and SaveThemeDialog::saveTheme().
const QString& KviThemeInfo::themeEngineVersion () inline
Referenced by PackThemeDataWidget::parseThemes().
const QString& KviThemeInfo::version () inline
Referenced by ThemeManagementDialog::applyCurrentTheme(), ThemeManagementDialog::deleteTheme(), PackThemeDataWidget::parseThemes(), SaveThemeDialog::saveTheme(), SaveThemeDialog::SaveThemeDialog(), theme_kvs_cmd_apply(), theme_kvs_fnc_info(), and ThemeListWidgetItem::ThemeListWidgetItem().
Member Data Documentation
bool KviThemeInfo::m_bBuiltin protected
Referenced by KviThemeInfo(), and load().
QPixmap KviThemeInfo::m_pixScreenshotLarge protected
Referenced by largeScreenshot().
QPixmap KviThemeInfo::m_pixScreenshotMedium protected
Referenced by mediumScreenshot().
QPixmap KviThemeInfo::m_pixScreenshotSmall protected
Referenced by smallScreenshot().
QString KviThemeInfo::m_szApplication protected
Referenced by load().
QString KviThemeInfo::m_szAuthor protected
Referenced by load(), and save().
QString KviThemeInfo::m_szDate protected
Referenced by load(), and save().
QString KviThemeInfo::m_szDescription protected
Referenced by load(), and save().
QString KviThemeInfo::m_szDirName protected
Referenced by load().
QString KviThemeInfo::m_szLastError protected
Referenced by load().
QString KviThemeInfo::m_szName protected
Referenced by load(), and save().
QString KviThemeInfo::m_szSubdirectory protected
Referenced by load().
QString KviThemeInfo::m_szThemeEngineVersion protected
Referenced by load().
QString KviThemeInfo::m_szVersion protected
Referenced by load(), and save().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviTheme.h
src/kvirc/kernel/KviTheme.cpp