KVIrc: KviIrcConnectionStatistics Class Reference
KviIrcConnectionStatistics Class Reference
#include <kvi_ircconnectionstatistics.h>
Public Member Functions
kvi_time_t connectionStartTime ()
KviIrcConnectionStatistics ()
kvi_time_t lastMessageTime ()
~KviIrcConnectionStatistics ()
Protected Member Functions
void setConnectionStartTime (kvi_time_t t)
void setLastMessageTime (kvi_time_t t)
Protected Attributes
kvi_time_t m_tConnectionStart
kvi_time_t m_tLastMessage
Friends
class KviConsole
class KviIrcConnection
Constructor & Destructor Documentation
KviIrcConnectionStatistics::KviIrcConnectionStatistics ()
References m_tConnectionStart, and m_tLastMessage.
KviIrcConnectionStatistics::~KviIrcConnectionStatistics ()
Member Function Documentation
kvi_time_t KviIrcConnectionStatistics::connectionStartTime () [inline]
Referenced by KviStatusBarConnectionTimer::timerEvent().
kvi_time_t KviIrcConnectionStatistics::lastMessageTime () [inline]
void KviIrcConnectionStatistics::setConnectionStartTime (kvi_time_t t) [inline, protected]
Referenced by KviIrcConnection::linkEstabilished().
void KviIrcConnectionStatistics::setLastMessageTime (kvi_time_t t) [inline, protected]
Referenced by KviIrcConnection::incomingMessage(), KviIrcConnection::incomingMessageNoFilter(), and KviIrcConnection::linkEstabilished().
Friends And Related Function Documentation
friend class KviConsole [friend]
friend class KviIrcConnection [friend]
Member Data Documentation
kvi_time_t KviIrcConnectionStatistics::m_tConnectionStart [protected]
Referenced by KviIrcConnectionStatistics().
kvi_time_t KviIrcConnectionStatistics::m_tLastMessage [protected]
Referenced by KviIrcConnectionStatistics().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnectionstatistics.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnectionstatistics.cpp