KVIrc: KviFontSelector Class Reference
KviFontSelector Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
virtual void commit ()
KviFontSelector (QWidget *par, const QString &txt, QFont *pOption, bool bEnabled)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviFontSelector ()
Public Member Functions inherited from KviTalHBox
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual ~KviSelectorInterface ()
Private Slots
void changeClicked ()
Private Member Functions
void setButtonFont (QFont *pOption)
Private Attributes
QPushButton * m_pButton
QLabel * m_pLabel
QFont * m_pOption
Additional Inherited Members
Protected Member Functions inherited from KviTalHBox
virtual void childEvent (QChildEvent *e)
Constructor & Destructor Documentation
KviFontSelector::KviFontSelector (QWidget * par, const QString & txt, QFont * pOption, bool bEnabled)
References changeClicked(), connect(), m_pButton, m_pLabel, m_pOption, setButtonFont(), setEnabled(), KviTalHBox::setSpacing(), and KviTalHBox::setStretchFactor().
KviFontSelector::~KviFontSelector () inline
Member Function Documentation
void KviFontSelector::changeClicked () private slot
References m_pButton, and setButtonFont().
Referenced by KviFontSelector().
void KviFontSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pButton, and m_pOption.
void KviFontSelector::setButtonFont (QFont * pOption) private
References m_pButton.
Referenced by changeClicked(), and KviFontSelector().
void KviFontSelector::setEnabled (bool bEnabled) virtual slot
References m_pButton, and m_pLabel.
Referenced by KviFontSelector().
QString KviFontSelector::textForSearch () inline virtual
Reimplemented from KviSelectorInterface.
QWidget* KviFontSelector::widgetToHighlight () inline virtual
Reimplemented from KviSelectorInterface.
Member Data Documentation
QPushButton* KviFontSelector::m_pButton private
Referenced by changeClicked(), commit(), KviFontSelector(), setButtonFont(), and setEnabled().
QLabel* KviFontSelector::m_pLabel private
Referenced by KviFontSelector(), and setEnabled().
QFont* KviFontSelector::m_pOption private
Referenced by commit(), and KviFontSelector().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp