KVIrc: UPnP::Manager Class Reference
UPnP::Manager Class Reference
#include <Manager.h>
Public Member Functions
void addPortMapping (const QString &protocol, const QString &remoteHost, int externalPort, const QString &internalClient, int internalPort, const QString &description, bool enabled=true, int leaseDuration=0)
void deletePortMapping (const QString &protocol, const QString &remoteHost, int externalPort)
QString getExternalIpAddress () const
bool isGatewayAvailable ()
virtual ~Manager ()
Static Public Member Functions
static Manager * instance ()
Private Slots
void slotBroadcastTimeout ()
void slotDeviceFound (const QString &hostname, int port, const QString &rootUrl)
Private Member Functions
void initialize ()
Manager ()
Manager (const Manager &)
Manager & operator= (const Manager &)
Private Attributes
bool m_bBroadcastFailed
bool m_bBroadcastFoundIt
KviPointerList< IgdControlPoint > m_lIgdControlPoints
IgdControlPoint * m_pActiveIgdControlPoint
SsdpConnection * m_pSsdpConnection
QTimer * m_pSsdpTimer
Static Private Attributes
static Manager * m_pInstance
Detailed Description
The manager class is the public interface used by other networking classes. It's implemented as singleton to provide easy access by other classes. Devices are automatically detected at start-up, and maintained by this class. Underneath, the actual work is done by the SsdpConnection and IgdControlPoint classes.
Author
Diederik van der Boor
Constructor & Destructor Documentation
UPnP::Manager::~Manager () virtual
References m_pInstance, m_pSsdpConnection, and m_pSsdpTimer.
UPnP::Manager::Manager () private
Referenced by instance().
UPnP::Manager::Manager (const Manager &) private
Member Function Documentation
void UPnP::Manager::addPortMapping (const QString & protocol, const QString & remoteHost, int externalPort, const QString & internalClient, int internalPort, const QString & description, bool enabled = true, int leaseDuration = 0)
References UPnP::IgdControlPoint::addPortMapping(), and m_pActiveIgdControlPoint.
Referenced by upnp_kvs_cmd_addPortMapping().
void UPnP::Manager::deletePortMapping (const QString & protocol, const QString & remoteHost, int externalPort)
References UPnP::IgdControlPoint::deletePortMapping(), and m_pActiveIgdControlPoint.
Referenced by upnp_kvs_cmd_delPortMapping().
QString UPnP::Manager::getExternalIpAddress () const
References UPnP::IgdControlPoint::getExternalIpAddress(), and m_pActiveIgdControlPoint.
Referenced by upnp_kvs_fnc_getExternalIpAddress().
void UPnP::Manager::initialize () private
References connect(), m_bBroadcastFailed, m_bBroadcastFoundIt, m_pSsdpConnection, m_pSsdpTimer, UPnP::SsdpConnection::queryDevices(), slotBroadcastTimeout(), and slotDeviceFound().
Referenced by instance().
Manager * UPnP::Manager::instance () static
References initialize(), m_pInstance, and Manager().
Referenced by upnp_kvs_cmd_refresh(), and upnp_module_init().
bool UPnP::Manager::isGatewayAvailable ()
References UPnP::IgdControlPoint::isGatewayAvailable(), and m_pActiveIgdControlPoint.
Referenced by upnp_kvs_fnc_isGatewayAvailable(), and upnp_module_can_unload().
Manager& UPnP::Manager::operator= (const Manager &) private
void UPnP::Manager::slotBroadcastTimeout () private slot
References m_bBroadcastFailed, and m_bBroadcastFoundIt.
Referenced by initialize().
void UPnP::Manager::slotDeviceFound (const QString & hostname, int port, const QString & rootUrl) private slot
References UPnP::IgdControlPoint::initialize(), m_bBroadcastFoundIt, m_lIgdControlPoints, and m_pActiveIgdControlPoint.
Referenced by initialize().
Member Data Documentation
bool UPnP::Manager::m_bBroadcastFailed private
Referenced by initialize(), and slotBroadcastTimeout().
bool UPnP::Manager::m_bBroadcastFoundIt private
Referenced by initialize(), slotBroadcastTimeout(), and slotDeviceFound().
KviPointerList<IgdControlPoint> UPnP::Manager::m_lIgdControlPoints private
Referenced by slotDeviceFound().
IgdControlPoint* UPnP::Manager::m_pActiveIgdControlPoint private
Referenced by addPortMapping(), deletePortMapping(), getExternalIpAddress(), isGatewayAvailable(), and slotDeviceFound().
Manager * UPnP::Manager::m_pInstance static private
Referenced by instance(), and ~Manager().
SsdpConnection* UPnP::Manager::m_pSsdpConnection private
Referenced by initialize(), and ~Manager().
QTimer* UPnP::Manager::m_pSsdpTimer private
Referenced by initialize(), and ~Manager().
The documentation for this class was generated from the following files:
src/modules/upnp/Manager.h
src/modules/upnp/Manager.cpp