KVIrc: KvsObject_treeWidget Class Reference
KvsObject_treeWidget Class Reference
#include <KvsObject_treeWidget.h>
Public Member Functions
void fileDropped (QString &, QTreeWidgetItem *)
QWidget * widget ()
Protected Slots
void slotClicked (QTreeWidgetItem *, int)
void slotCurrentChanged (QTreeWidgetItem *, QTreeWidgetItem *)
void slotItemActivated (QTreeWidgetItem *, int col)
void slotItemChanged (QTreeWidgetItem *, int)
void slotItemCollapsed (QTreeWidgetItem *)
void slotItemExpanded (QTreeWidgetItem *)
void slotOnItemEntered (QTreeWidgetItem *, int col)
void slotSelectionChanged ()
Protected Member Functions
bool addColumn (KviKvsObjectFunctionCall *c)
bool clear (KviKvsObjectFunctionCall *c)
bool currentChangedEvent (KviKvsObjectFunctionCall *c)
bool currentItem (KviKvsObjectFunctionCall *c)
bool firstChild (KviKvsObjectFunctionCall *c)
bool hideListViewHeader (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool itemActivatedEvent (KviKvsObjectFunctionCall *c)
bool itemAt (KviKvsObjectFunctionCall *c)
bool itemChangedEvent (KviKvsObjectFunctionCall *c)
bool itemClickedEvent (KviKvsObjectFunctionCall *c)
bool itemCollapsedEvent (KviKvsObjectFunctionCall *c)
bool itemExpandedEvent (KviKvsObjectFunctionCall *c)
bool listViewHeaderIsVisible (KviKvsObjectFunctionCall *c)
bool onItemEvent (KviKvsObjectFunctionCall *c)
bool selectedItems (KviKvsObjectFunctionCall *c)
bool selectionChangedEvent (KviKvsObjectFunctionCall *c)
bool setAcceptDrops (KviKvsObjectFunctionCall *c)
bool setAllColumnsShowFocus (KviKvsObjectFunctionCall *c)
bool setBackgroundImage (KviKvsObjectFunctionCall *c)
bool setColumnCount (KviKvsObjectFunctionCall *c)
bool setColumnText (KviKvsObjectFunctionCall *c)
bool setHeaderLabels (KviKvsObjectFunctionCall *c)
bool setRootIsDecorated (KviKvsObjectFunctionCall *c)
bool setSelectionMode (KviKvsObjectFunctionCall *c)
bool setSorting (KviKvsObjectFunctionCall *c)
bool setSortingEnabled (KviKvsObjectFunctionCall *c)
bool showListViewHeader (KviKvsObjectFunctionCall *c)
bool takeItem (KviKvsObjectFunctionCall *c)
bool topLevelItem (KviKvsObjectFunctionCall *c)
bool topLevelItemCount (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_treeWidget::addColumn (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::clear (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::currentChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::currentItem (KviKvsObjectFunctionCall * c) [protected]
Referenced by slotSelectionChanged().
void KvsObject_treeWidget::fileDropped (QString & szFile, QTreeWidgetItem * item)
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
Referenced by KviKvsTreeWidget::dropEvent().
bool KvsObject_treeWidget::firstChild (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::hideListViewHeader (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect().
bool KvsObject_treeWidget::itemActivatedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::itemAt (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::itemChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::itemClickedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::itemCollapsedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::itemExpandedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::listViewHeaderIsVisible (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::onItemEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::selectedItems (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::selectionChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setAcceptDrops (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setAllColumnsShowFocus (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setBackgroundImage (KviKvsObjectFunctionCall * c) [protected]
Reimplemented from KvsObject_widget.
bool KvsObject_treeWidget::setColumnCount (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setColumnText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setHeaderLabels (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setRootIsDecorated (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setSelectionMode (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setSorting (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::setSortingEnabled (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::showListViewHeader (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_treeWidget::slotClicked (QTreeWidgetItem * i, int col) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotCurrentChanged (QTreeWidgetItem * i, QTreeWidgetItem * prev) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotItemActivated (QTreeWidgetItem * i, int col) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotItemChanged (QTreeWidgetItem * item, int col) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotItemCollapsed (QTreeWidgetItem * i) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotItemExpanded (QTreeWidgetItem * i) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotOnItemEntered (QTreeWidgetItem * i, int col) [protected, slot]
References KviKvsObject::callFunction(), and KvsObject_treeWidgetItem::itemToHandle().
void KvsObject_treeWidget::slotSelectionChanged () [protected, slot]
References KviKvsObject::callFunction(), currentItem(), KvsObject_treeWidgetItem::itemToHandle(), and widget().
bool KvsObject_treeWidget::takeItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::topLevelItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_treeWidget::topLevelItemCount (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_treeWidget::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
Referenced by slotSelectionChanged().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_treeWidget.h
src/modules/objects/KvsObject_treeWidget.cpp