KVIrc: TextIconTableItem Class Reference
TextIconTableItem Class Reference
#include <OptionsWidget_textIcons.h>
Public Member Functions
KviTextIcon * icon ()
void setId (int id)
TextIconTableItem (QTableWidget *t, KviTextIcon *icon)
~TextIconTableItem ()
Protected Attributes
KviTextIcon * m_pIcon
Friends
class OptionsWidget_textIcons
Constructor & Destructor Documentation
TextIconTableItem::TextIconTableItem (QTableWidget * t, KviTextIcon * icon)
References icon(), m_pIcon, KviIconManager::None, and KviTextIcon::pixmap().
TextIconTableItem::~TextIconTableItem ()
References m_pIcon.
Member Function Documentation
KviTextIcon* TextIconTableItem::icon () [inline]
References m_pIcon.
Referenced by OptionsWidget_textIcons::chooseFromFile(), OptionsWidget_textIcons::commit(), OptionsWidget_textIcons::iconSelected(), and TextIconTableItem().
void TextIconTableItem::setId (int id)
References m_pIcon, KviTextIcon::pixmap(), and KviTextIcon::setId().
Friends And Related Function Documentation
friend class OptionsWidget_textIcons [friend]
Member Data Documentation
KviTextIcon* TextIconTableItem::m_pIcon [protected]
Referenced by icon(), setId(), TextIconTableItem(), and ~TextIconTableItem().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_textIcons.h
src/modules/options/OptionsWidget_textIcons.cpp