KVIrc: KviScriptUserButton Class Reference
KviScriptUserButton Class Reference
#include <kvi_scriptbutton.h>
Public Member Functions
KviScriptUserButton (QWidget *par, const char *name)
void setButtonCode (KviKvsScript *pScript)
virtual void setButtonPixmap (const QPixmap &pix)
void setButtonText (const QString &text)
virtual KviWindow * window ()
~KviScriptUserButton ()
Protected Slots
void btnClicked ()
Protected Attributes
KviKvsScript * m_pScript
Constructor & Destructor Documentation
KviScriptUserButton::KviScriptUserButton (QWidget * par, const char * name)
References btnClicked(), and m_pScript.
KviScriptUserButton::~KviScriptUserButton ()
References m_pScript.
Member Function Documentation
void KviScriptUserButton::btnClicked () [protected, slot]
References KviKvsVariantList::append(), m_pScript, KviKvsScript::PreserveParams, KviKvsScript::run(), and window().
Referenced by KviScriptUserButton().
void KviScriptUserButton::setButtonCode (KviKvsScript * pScript)
References m_pScript.
virtual void KviScriptUserButton::setButtonPixmap (const QPixmap & pix) [inline, virtual]
Reimplemented in KviWindowScriptButton.
void KviScriptUserButton::setButtonText (const QString & text) [inline]
KviWindow * KviScriptUserButton::window () [virtual]
Reimplemented in KviWindowScriptButton.
References g_pActiveWindow.
Referenced by btnClicked().
Member Data Documentation
KviKvsScript* KviScriptUserButton::m_pScript [protected]
Referenced by btnClicked(), KviScriptUserButton(), setButtonCode(), and ~KviScriptUserButton().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_scriptbutton.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_scriptbutton.cpp