KVIrc: KviActionDrawer Class Reference
KviActionDrawer Class Reference
Action drawer class.
#include <KviActionDrawer.h>
Public Member Functions
void fill ()
Fills in the drawer page.
KviActionDrawer (QWidget *pParent)
Constructs an action drawer object.
~KviActionDrawer ()
Destroys an action drawer object.
Detailed Description
Action drawer class.
Action drawer page list item class.
Action drawer page list class.
Action drawer page class.
Constructor & Destructor Documentation
KviActionDrawer::KviActionDrawer (QWidget * pParent)
Constructs an action drawer object.
Parameters
pParent The parent widget
Returns
KviActionDrawer
KviActionDrawer::~KviActionDrawer () default
Destroys an action drawer object.
Member Function Documentation
void KviActionDrawer::fill ()
Fills in the drawer page.
Returns
void
References KviActionManager::actions(), KviActionDrawerPage::add(), KviActionManager::categoryGeneric(), KviActionManager::categoryIrc(), KviPointerHashTableIterator< Key, T >::current(), d, KviActionCategory::description(), KviPointerHashTable< Key, T >::find(), KviActionManager::instance(), KviActionManager::loadAllAvailableActions(), KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviActionCategory::visibleName().
Referenced by CustomizeToolBarsDialog::CustomizeToolBarsDialog().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviActionDrawer.h
src/kvirc/ui/KviActionDrawer.cpp