KVIrc: SaveThemeDialog Class Reference
SaveThemeDialog Class Reference
#include <SaveThemeDialog.h>
Public Member Functions
SaveThemeDialog (QWidget *pParent)
virtual ~SaveThemeDialog ()
Public Member Functions inherited from KviTalWizard
void addPage (QWidget *pWidget, const QString &szTitle)
QPushButton * backButton ()
QPushButton * cancelButton ()
QWidget * currentPage ()
QPushButton * finishButton ()
QPushButton * helpButton ()
void insertPage (QWidget *pWidget, const QString &szTitle, int iIndex)
KviTalWizard (QWidget *pParent)
QPushButton * nextButton ()
void setBackEnabled (QWidget *pWidget, bool bEnabled)
void setCancelEnabled (QWidget *pWidget, bool bEnabled)
bool setCurrentPage (QWidget *pWidget)
void setFinishEnabled (QWidget *pWidget, bool bEnabled)
void setHelpEnabled (QWidget *pWidget, bool bEnabled)
void setNextEnabled (QWidget *pWidget, bool bEnabled)
bool setPageEnabled (QWidget *pWidget, bool bEnabled)
bool setPageTitle (QWidget *pWidget, const QString &szTitle)
~KviTalWizard ()
Protected Slots
void imageSelectionChanged (const QString &szImagePath)
void makeScreenshot ()
Protected Slots inherited from KviTalWizard
void backButtonClicked ()
void cancelButtonClicked ()
void finishButtonClicked ()
void helpButtonClicked ()
void nextButtonClicked ()
Protected Member Functions
virtual void accept ()
bool saveTheme ()
Protected Member Functions inherited from KviTalWizard
virtual void closeEvent (QCloseEvent *e)
void setCurrentPage (KviTalWizardPageData *pData)
virtual void showEvent (QShowEvent *e)
Protected Attributes
QLineEdit * m_pAuthorNameEdit
QLabel * m_pImageLabel
QWidget * m_pImageSelectionPage
KviFileSelector * m_pImageSelector
QPushButton * m_pOkButton
QTextEdit * m_pThemeDescriptionEdit
QLineEdit * m_pThemeNameEdit
QLineEdit * m_pThemeVersionEdit
QString m_szScreenshotPath
Protected Attributes inherited from KviTalWizard
KviTalWizardPrivate * m_p
Additional Inherited Members
Signals inherited from KviTalWizard
void helpClicked ()
void pageChanged (QString title)
Constructor & Destructor Documentation
SaveThemeDialog::SaveThemeDialog (QWidget * pParent)
References __tr2qs_ctx(), KviTalWizard::addPage(), KviThemeInfo::author(), connect(), KviThemeInfo::description(), imageSelectionChanged(), KVI_FILTER_IMAGE, KVI_OPTION_STRING, KviOption_stringIconThemeSubdir, KviThemeInfo::load(), m_pAuthorNameEdit, m_pImageLabel, m_pImageSelectionPage, m_pImageSelector, m_pThemeDescriptionEdit, m_pThemeNameEdit, m_pThemeVersionEdit, m_szScreenshotPath, makeScreenshot(), KviThemeInfo::name(), KviTalWizard::setBackEnabled(), KviTalWizard::setFinishEnabled(), KviTalWizard::setHelpEnabled(), KviTalWizard::setNextEnabled(), and KviThemeInfo::version().
SaveThemeDialog::~SaveThemeDialog () virtual
Member Function Documentation
void SaveThemeDialog::accept () protected virtual
References saveTheme().
void SaveThemeDialog::imageSelectionChanged (const QString & szImagePath) protected slot
References __tr2qs_ctx(), m_pImageLabel, m_pImageSelector, and KviFileSelector::setSelection().
Referenced by makeScreenshot(), and SaveThemeDialog().
void SaveThemeDialog::makeScreenshot () protected slot
References __tr2qs_ctx(), g_pApp, KviApplication::getTmpFileName(), imageSelectionChanged(), m_pImageSelector, ThemeFunctions::makeKVIrcScreenshot(), and KviFileSelector::setSelection().
Referenced by SaveThemeDialog().
bool SaveThemeDialog::saveTheme () protected
References __tr2qs_ctx(), KviFileSelector::commit(), g_pApp, KviApplication::getLocalKvircDirectory(), KviMessageBox::information(), KVI_OPTION_UINT, KVI_SOURCES_DATE, KVI_VERSION, KviOption_uintOutputDatetimeFormat, KviThemeInfo::lastError(), m_pAuthorNameEdit, m_pImageSelectionPage, m_pImageSelector, m_pThemeDescriptionEdit, m_pThemeNameEdit, m_pThemeVersionEdit, m_szScreenshotPath, KviFileUtils::makeDir(), KviThemeInfo::name(), KviTheme::save(), KviTheme::saveScreenshots(), KviThemeInfo::setApplication(), KviThemeInfo::setAuthor(), KviTalWizard::setCurrentPage(), KviThemeInfo::setDate(), KviThemeInfo::setDescription(), KviThemeInfo::setName(), KviThemeInfo::setSubdirectory(), KviThemeInfo::setVersion(), KviThemeInfo::subdirectory(), KviApplication::Themes, and KviThemeInfo::version().
Referenced by accept().
Member Data Documentation
QLineEdit* SaveThemeDialog::m_pAuthorNameEdit protected
Referenced by saveTheme(), and SaveThemeDialog().
QLabel* SaveThemeDialog::m_pImageLabel protected
Referenced by imageSelectionChanged(), and SaveThemeDialog().
QWidget* SaveThemeDialog::m_pImageSelectionPage protected
Referenced by saveTheme(), and SaveThemeDialog().
KviFileSelector* SaveThemeDialog::m_pImageSelector protected
Referenced by imageSelectionChanged(), makeScreenshot(), saveTheme(), and SaveThemeDialog().
QPushButton* SaveThemeDialog::m_pOkButton protected
QTextEdit* SaveThemeDialog::m_pThemeDescriptionEdit protected
Referenced by saveTheme(), and SaveThemeDialog().
QLineEdit* SaveThemeDialog::m_pThemeNameEdit protected
Referenced by saveTheme(), and SaveThemeDialog().
QLineEdit* SaveThemeDialog::m_pThemeVersionEdit protected
Referenced by saveTheme(), and SaveThemeDialog().
QString SaveThemeDialog::m_szScreenshotPath protected
Referenced by saveTheme(), and SaveThemeDialog().
The documentation for this class was generated from the following files:
src/modules/theme/SaveThemeDialog.h
src/modules/theme/SaveThemeDialog.cpp