KVIrc: KviPackageIOEngine Class Reference
KviPackageIOEngine Class Reference
This class is the base class engine to work with KVIrc package files.
#include <KviPackageIOEngine.h>
Public Member Functions
KviPointerHashTable< QString,
QByteArray > * binaryInfoFields ()
Returns the binary info fields.
KviPackageIOEngine ()
Creates the I/O engine object.
const QString & lastError ()
Returns the last error.
KviPointerHashTable< QString,
QString > * stringInfoFields ()
Returns the string info fields.
virtual ~KviPackageIOEngine ()
Destroys the object.
Protected Member Functions
void hideProgressDialog ()
Hides the progress dialog.
bool readError ()
Sets the last error as read error.
void setLastError (const QString &szLastError)
Sets the last error.
void showProgressDialog (const QString &szCaption, int iTotalSteps)
Shows the progress dialog.
bool updateProgress (int iProgress, const QString &szLabel)
Updates the progress dialog.
bool writeError ()
Sets the last error as write error.
Private Attributes
KviPointerHashTable< QString,
QByteArray > * m_pBinaryInfoFields
QProgressDialog * m_pProgressDialog
QLabel * m_pProgressDialogLabel
KviPointerHashTable< QString,
QString > * m_pStringInfoFields
QString m_szLastError
Detailed Description
This class is the base class engine to work with KVIrc package files.
Constructor & Destructor Documentation
KviPackageIOEngine::KviPackageIOEngine ()
Creates the I/O engine object.
Returns
KviPackageIOEngine
References m_pBinaryInfoFields, m_pProgressDialog, m_pStringInfoFields, and KviPointerHashTable< Key, T >::setAutoDelete().
KviPackageIOEngine::~KviPackageIOEngine () virtual
Destroys the object.
References m_pBinaryInfoFields, m_pProgressDialog, and m_pStringInfoFields.
Member Function Documentation
KviPointerHashTable<QString, QByteArray>* KviPackageIOEngine::binaryInfoFields () inline
Returns the binary info fields.
Returns
KviPointerHashTable<QString,QByteArray> *
Referenced by KviPackageWriter::addInfoField(), AddonFunctions::installAddonPackage(), ThemeFunctions::installThemePackage(), package_kvs_cmd_extractField(), package_kvs_fnc_info(), KviPackageWriter::packInternal(), and KviPackageReader::readHeaderInternal().
void KviPackageIOEngine::hideProgressDialog () protected
Hides the progress dialog.
Returns
void
References m_pProgressDialog.
Referenced by KviPackageWriter::pack(), and KviPackageReader::unpack().
const QString& KviPackageIOEngine::lastError () inline
Returns the last error.
Returns
const QString &
Referenced by AddonFunctions::installAddonPackage(), ThemeFunctions::installThemePackage(), AddonFunctions::pack(), package_kvs_cmd_extractField(), package_kvs_fnc_info(), and ThemeFunctions::packageThemes().
bool KviPackageIOEngine::readError () protected
Sets the last error as read error.
This is a shortcut to setLastError()
Returns
bool
References __tr2qs, and setLastError().
Referenced by KviPackageWriter::packFile(), KviPackageReader::readHeaderInternal(), KviPackageReader::unpackFile(), and KviPackageReader::unpackInternal().
void KviPackageIOEngine::setLastError (const QString & szLastError) inline protected
Sets the last error.
Parameters
szLastError The string error
Returns
void
Referenced by KviPackageWriter::packFile(), KviPackageWriter::packInternal(), readError(), KviPackageReader::readHeader(), KviPackageReader::readHeaderInternal(), KviPackageReader::unpackFile(), KviPackageReader::unpackInternal(), updateProgress(), and writeError().
void KviPackageIOEngine::showProgressDialog (const QString & szCaption, int iTotalSteps) protected
Shows the progress dialog.
Parameters
szCaption The caption of the dialog window
iTotalSteps The total number of steps
Returns
void
References __tr2qs, m_pProgressDialog, and m_pProgressDialogLabel.
Referenced by KviPackageWriter::pack(), and KviPackageReader::unpackInternal().
KviPointerHashTable<QString, QString>* KviPackageIOEngine::stringInfoFields () inline
Returns the string info fields.
Returns
KviPointerHashTable<QString,QString> *
Referenced by KviPackageWriter::addInfoField(), KviPackageReader::getStringInfoField(), AddonFunctions::installAddonPackage(), ThemeFunctions::installThemePackage(), package_kvs_fnc_info(), KviPackageWriter::packInternal(), and KviPackageReader::readHeaderInternal().
bool KviPackageIOEngine::updateProgress (int iProgress, const QString & szLabel) protected
Updates the progress dialog.
Parameters
iProgress The value in steps of the progress bar
szLabel The label of the step
Returns
bool
References __tr2qs, m_pProgressDialog, m_pProgressDialogLabel, and setLastError().
Referenced by KviPackageWriter::pack(), KviPackageWriter::packFile(), KviPackageWriter::packInternal(), KviPackageReader::unpackFile(), and KviPackageReader::unpackInternal().
bool KviPackageIOEngine::writeError () protected
Sets the last error as write error.
This is a shortcut to setLastError()
Returns
bool
References __tr2qs, and setLastError().
Referenced by KviPackageWriter::packFile(), KviPackageWriter::packInternal(), KviPackageReader::readHeaderInternal(), and KviPackageReader::unpackFile().
Member Data Documentation
KviPointerHashTable<QString, QByteArray>* KviPackageIOEngine::m_pBinaryInfoFields private
Referenced by KviPackageIOEngine(), and ~KviPackageIOEngine().
QProgressDialog* KviPackageIOEngine::m_pProgressDialog private
Referenced by hideProgressDialog(), KviPackageIOEngine(), showProgressDialog(), updateProgress(), and ~KviPackageIOEngine().
QLabel* KviPackageIOEngine::m_pProgressDialogLabel private
Referenced by showProgressDialog(), and updateProgress().
KviPointerHashTable<QString, QString>* KviPackageIOEngine::m_pStringInfoFields private
Referenced by KviPackageIOEngine(), and ~KviPackageIOEngine().
QString KviPackageIOEngine::m_szLastError private
The documentation for this class was generated from the following files:
src/kvilib/file/KviPackageIOEngine.h
src/kvilib/file/KviPackageIOEngine.cpp