KVIrc: KviWatchNotifyListManager Class Reference
KviWatchNotifyListManager Class Reference
#include <KviNotifyList.h>
Public Member Functions
KviWatchNotifyListManager (KviIrcConnection *pConnection)
~KviWatchNotifyListManager ()
Protected Member Functions
void buildRegUserDict ()
bool doMatchUser (KviIrcMessage *msg, const QString &notifyString, const KviIrcMask &mask)
virtual bool handleWatchReply (KviIrcMessage *msg)
virtual void start ()
virtual void stop ()
Protected Attributes
KviPointerHashTable< QString,
QString > * m_pRegUserDict
Friends
class KviConsoleWindow
class KviIrcConnection
class KviIrcServerParser
Constructor & Destructor Documentation
KviWatchNotifyListManager::KviWatchNotifyListManager (KviIrcConnection * pConnection)
References m_pRegUserDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviWatchNotifyListManager::~KviWatchNotifyListManager ()
References m_pRegUserDict.
Member Function Documentation
void KviWatchNotifyListManager::buildRegUserDict () [protected]
References KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), d, g_pRegisteredUserDataBase, m_pRegUserDict, KviPointerHashTable< Key, T >::replace(), u, and KviRegisteredUserDataBase::userDict().
Referenced by start().
bool KviWatchNotifyListManager::doMatchUser (KviIrcMessage * msg, const QString & notifyString, const KviIrcMask & mask) [protected]
References __tr, __tr2qs, _OUTPUT_VERBOSE, KviPointerHashTable< Key, T >::find(), KviUserListView::findEntry(), KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviIrcMask::host(), KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviNotifyListManager::m_pConsole, m_pRegUserDict, KviIrcMask::nick(), KviConsoleWindow::notifyListView(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviIrcMessage::numeric(), KviWindow::output(), RPL_NOWON, start(), stop(), u, and KviIrcMask::user().
Referenced by handleWatchReply().
bool KviWatchNotifyListManager::handleWatchReply (KviIrcMessage * msg) [protected, virtual]
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, KviIrcConnection::decodeText(), doMatchUser(), KviPointerHashTable< Key, T >::find(), KviUserListView::findEntry(), KVI_OUT_SYSTEMMESSAGE, m, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pRegUserDict, KviConsoleWindow::notifyListView(), KviNotifyListManager::notifyOffLine(), KviIrcMessage::numeric(), KviWindow::output(), KviPointerHashTable< Key, T >::remove(), RPL_LOGOFF, RPL_LOGON, RPL_NOWOFF, RPL_NOWON, RPL_WATCHOFF, and KviIrcMessage::safeParam().
void KviWatchNotifyListManager::start () [protected, virtual]
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, KviQString::appendFormatted(), buildRegUserDict(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviIrcConnection::currentNickName(), KviIrcConnection::encodeText(), KVI_OUT_SYSTEMMESSAGE, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pRegUserDict, KviConsoleWindow::notifyListView(), KviWindow::output(), KviUserListView::partAllButOne(), and KviIrcConnection::sendFmtData().
Referenced by doMatchUser().
void KviWatchNotifyListManager::stop () [protected, virtual]
Reimplemented from KviNotifyListManager.
References KviPointerHashTable< Key, T >::clear(), KviIrcConnection::currentNickName(), KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pRegUserDict, KviConsoleWindow::notifyListView(), KviUserListView::partAllButOne(), and KviIrcConnection::sendFmtData().
Referenced by doMatchUser().
Friends And Related Function Documentation
friend class KviConsoleWindow [friend]
Reimplemented from KviNotifyListManager.
friend class KviIrcConnection [friend]
Reimplemented from KviNotifyListManager.
friend class KviIrcServerParser [friend]
Reimplemented from KviNotifyListManager.
Member Data Documentation
KviPointerHashTable<QString,QString>* KviWatchNotifyListManager::m_pRegUserDict [protected]
Referenced by buildRegUserDict(), doMatchUser(), handleWatchReply(), KviWatchNotifyListManager(), start(), stop(), and ~KviWatchNotifyListManager().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviNotifyList.h
src/kvirc/kernel/KviNotifyList.cpp