KVIrc: KvsObject_painter Class Reference
KvsObject_painter Class Reference
#include <KvsObject_painter.h>
Public Member Functions
bool begin (KviKvsObjectFunctionCall *c)
bool beginPdf (KviKvsObjectFunctionCall *c)
bool clearGradient (KviKvsObjectFunctionCall *c)
bool colorNames (KviKvsObjectFunctionCall *c)
bool drawArc (KviKvsObjectFunctionCall *c)
bool drawChord (KviKvsObjectFunctionCall *c)
bool drawEllipse (KviKvsObjectFunctionCall *c)
bool drawHtmlText (KviKvsObjectFunctionCall *c)
bool drawIcon (KviKvsObjectFunctionCall *c)
bool drawLine (KviKvsObjectFunctionCall *c)
bool drawPath (KviKvsObjectFunctionCall *c)
bool drawPie (KviKvsObjectFunctionCall *c)
bool drawPixmap (KviKvsObjectFunctionCall *c)
bool drawPixmapMirrored (KviKvsObjectFunctionCall *c)
bool drawPixmapWithColorEffect (KviKvsObjectFunctionCall *c)
bool drawPoint (KviKvsObjectFunctionCall *c)
bool drawRect (KviKvsObjectFunctionCall *c)
bool drawRoundRect (KviKvsObjectFunctionCall *c)
bool drawText (KviKvsObjectFunctionCall *c)
bool drawWinFocusRect (KviKvsObjectFunctionCall *c)
bool end (KviKvsObjectFunctionCall *c)
bool fillRect (KviKvsObjectFunctionCall *c)
bool fontAscent (KviKvsObjectFunctionCall *c)
bool fontDescent (KviKvsObjectFunctionCall *c)
bool fontMetricsHeight (KviKvsObjectFunctionCall *c)
bool fontMetricsWidth (KviKvsObjectFunctionCall *c)
bool htmlTextSize (KviKvsObjectFunctionCall *c)
bool painterDeviceHeight (KviKvsObjectFunctionCall *c)
bool painterDeviceWidth (KviKvsObjectFunctionCall *c)
bool pathAddText (KviKvsObjectFunctionCall *c)
bool pathLineTo (KviKvsObjectFunctionCall *c)
bool pathMoveTo (KviKvsObjectFunctionCall *c)
bool pen (KviKvsObjectFunctionCall *c)
bool reset (KviKvsObjectFunctionCall *c)
bool resetPath (KviKvsObjectFunctionCall *c)
bool restore (KviKvsObjectFunctionCall *c)
bool rotate (KviKvsObjectFunctionCall *c)
bool save (KviKvsObjectFunctionCall *c)
bool scale (KviKvsObjectFunctionCall *c)
bool setAntialiasing (KviKvsObjectFunctionCall *c)
bool setBackGroundMode (KviKvsObjectFunctionCall *c)
bool setBrush (KviKvsObjectFunctionCall *c)
bool setBrushStyle (KviKvsObjectFunctionCall *c)
bool setCompositionMode (KviKvsObjectFunctionCall *c)
bool setFont (KviKvsObjectFunctionCall *c)
bool setFontSize (KviKvsObjectFunctionCall *c)
bool setGradientAsBrush (KviKvsObjectFunctionCall *c)
bool setGradientColor (KviKvsObjectFunctionCall *c)
bool setGradientStart (KviKvsObjectFunctionCall *c)
bool setGradientStop (KviKvsObjectFunctionCall *c)
void setInternalPainter (QPainter *p)
bool setOpacity (KviKvsObjectFunctionCall *c)
bool setPen (KviKvsObjectFunctionCall *c)
bool setPenCapStyle (KviKvsObjectFunctionCall *c)
bool setPenJoinStyle (KviKvsObjectFunctionCall *c)
bool setPenStyle (KviKvsObjectFunctionCall *c)
bool setPenWidth (KviKvsObjectFunctionCall *c)
bool setSmoothPixmapTransform (KviKvsObjectFunctionCall *c)
bool setTextAntialiasing (KviKvsObjectFunctionCall *c)
bool shear (KviKvsObjectFunctionCall *c)
bool translate (KviKvsObjectFunctionCall *c)
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Protected Slots
void detachDevice ()
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Protected Member Functions
void attachDevice (KviKvsObject *o, QPaintDevice *p)
Protected Member Functions inherited from KviKvsObject
virtual bool eventFilter (QObject *o, QEvent *e)
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
bool bDonotdeleteinternalqpainter
QLinearGradient * m_pGradient
QMatrix m_pMatrix
QPainter * m_pPainter
QPainterPath * m_pPainterPath
QPrinter * m_pPrinter
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Private Attributes
KviKvsObject * m_pDeviceObject
Member Function Documentation
void KvsObject_painter::attachDevice (KviKvsObject * o, QPaintDevice * p) protected
References aboutToDie(), connect(), detachDevice(), m_pDeviceObject, and o.
bool KvsObject_painter::begin (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::beginPdf (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::clearGradient (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::colorNames (KviKvsObjectFunctionCall * c)
void KvsObject_painter::detachDevice () protected slot
References aboutToDie(), m_pDeviceObject, and m_pPrinter.
Referenced by attachDevice().
bool KvsObject_painter::drawArc (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawChord (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawEllipse (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawHtmlText (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawIcon (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawLine (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawPath (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawPie (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawPixmap (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawPixmapMirrored (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawPixmapWithColorEffect (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawPoint (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawRect (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawRoundRect (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawText (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::drawWinFocusRect (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::end (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::fillRect (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::fontAscent (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::fontDescent (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::fontMetricsHeight (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::fontMetricsWidth (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::htmlTextSize (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::painterDeviceHeight (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::painterDeviceWidth (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::pathAddText (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::pathLineTo (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::pathMoveTo (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::pen (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::reset (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::resetPath (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::restore (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::rotate (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::save (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::scale (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setAntialiasing (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setBackGroundMode (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setBrush (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setBrushStyle (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setCompositionMode (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setFont (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setFontSize (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setGradientAsBrush (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setGradientColor (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setGradientStart (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setGradientStop (KviKvsObjectFunctionCall * c)
void KvsObject_painter::setInternalPainter (QPainter * p)
References bDonotdeleteinternalqpainter, m_pPainter, and p.
bool KvsObject_painter::setOpacity (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setPen (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setPenCapStyle (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setPenJoinStyle (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setPenStyle (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setPenWidth (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setSmoothPixmapTransform (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::setTextAntialiasing (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::shear (KviKvsObjectFunctionCall * c)
bool KvsObject_painter::translate (KviKvsObjectFunctionCall * c)
Member Data Documentation
bool KvsObject_painter::bDonotdeleteinternalqpainter protected
Referenced by setInternalPainter().
KviKvsObject* KvsObject_painter::m_pDeviceObject private
Referenced by attachDevice(), and detachDevice().
QLinearGradient* KvsObject_painter::m_pGradient protected
QMatrix KvsObject_painter::m_pMatrix protected
QPainter* KvsObject_painter::m_pPainter protected
Referenced by setInternalPainter().
QPainterPath* KvsObject_painter::m_pPainterPath protected
QPrinter* KvsObject_painter::m_pPrinter protected
Referenced by detachDevice().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_painter.h
src/modules/objects/KvsObject_painter.cpp