KVIrc: KviIrcOperationsAction Class Reference
KviIrcOperationsAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
KviIrcOperationsAction (QObject *pParent)
Protected Slots
void popupAboutToShow ()
void popupActivated (QAction *pAction)
Constructor & Destructor Documentation
KviIrcOperationsAction::KviIrcOperationsAction (QObject * pParent)
Member Function Documentation
void KviIrcOperationsAction::popupAboutToShow () [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References a, KviAction::addToPopupMenu(), KviActionManager::getAction(), KviActionManager::instance(), KVI_COREACTION_AWAYBACK, KVI_COREACTION_CHANNELMENU, KVI_COREACTION_NICKNAMEMENU, KVI_COREACTION_SEPARATOR, KVI_COREACTION_SERVERMENU, KVI_COREACTION_USERMODEMENU, and KviSubmenuAction::m_pPopup.
void KviIrcOperationsAction::popupActivated (QAction * pAction) [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp