KVIrc: KviKvsTreeNodeOperationStringSubstitution Class Reference
KviKvsTreeNodeOperationStringSubstitution Class Reference
#include <kvi_kvs_treenode_operation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationStringSubstitution (const QChar *pLocation, KviKvsTreeNodeData *pLeft, KviKvsTreeNodeData *pRight, KviKvsTreeNodeData *pFlags)
~KviKvsTreeNodeOperationStringSubstitution ()
Protected Attributes
KviKvsTreeNodeData * m_pFlags
KviKvsTreeNodeData * m_pLeft
KviKvsTreeNodeData * m_pRight
Constructor & Destructor Documentation
KviKvsTreeNodeOperationStringSubstitution::KviKvsTreeNodeOperationStringSubstitution (const QChar * pLocation, KviKvsTreeNodeData * pLeft, KviKvsTreeNodeData * pRight, KviKvsTreeNodeData * pFlags)
References m_pFlags, m_pLeft, m_pRight, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationStringSubstitution::~KviKvsTreeNodeOperationStringSubstitution ()
References m_pFlags, m_pLeft, and m_pRight.
Member Function Documentation
void KviKvsTreeNodeOperationStringSubstitution::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationStringSubstitution::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pFlags, m_pLeft, and m_pRight.
bool KviKvsTreeNodeOperationStringSubstitution::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx, KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), m_pFlags, m_pLeft, m_pRight, KviKvsTreeNodeOperation::m_pTargetData, KviQString::nullTerminatedArray(), KviKvsRWEvaluationResult::result(), KviKvsVariant::setString(), and KviKvsRunTimeContext::warning().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringSubstitution::m_pFlags [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationStringSubstitution(), and ~KviKvsTreeNodeOperationStringSubstitution().
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringSubstitution::m_pLeft [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationStringSubstitution(), and ~KviKvsTreeNodeOperationStringSubstitution().
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringSubstitution::m_pRight [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationStringSubstitution(), and ~KviKvsTreeNodeOperationStringSubstitution().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.cpp