KVIrc: KvsObject_popupMenu Class Reference
KvsObject_popupMenu Class Reference
#include <KvsObject_popupMenu.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void aboutToDie (QObject *)
void slothovered (QAction *)
void slottriggered (QAction *)
Protected Member Functions
bool activatedEvent (KviKvsObjectFunctionCall *c)
bool addMenu (KviKvsObjectFunctionCall *c)
bool exec (KviKvsObjectFunctionCall *c)
bool highlightedEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertItem (KviKvsObjectFunctionCall *c)
bool insertSeparator (KviKvsObjectFunctionCall *c)
bool removeItem (KviKvsObjectFunctionCall *c)
bool removeItemAt (KviKvsObjectFunctionCall *c)
bool setTitle (KviKvsObjectFunctionCall *c)
Member Function Documentation
void KvsObject_popupMenu::aboutToDie (QObject * pObject) [protected, slot]
References removeMenuAllActions().
bool KvsObject_popupMenu::activatedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::addMenu (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::exec (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::highlightedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References aboutToDie(), connect(), and SET_OBJECT.
bool KvsObject_popupMenu::insertItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::insertSeparator (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::removeItem (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::removeItemAt (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_popupMenu::setTitle (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_popupMenu::slothovered (QAction * a) [protected, slot]
References a, actionsDict, KviKvsObject::callFunction(), and i.
void KvsObject_popupMenu::slottriggered (QAction * a) [protected, slot]
References a, actionsDict, KviKvsObject::callFunction(), and i.
QWidget* KvsObject_popupMenu::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_popupMenu.h
src/modules/objects/KvsObject_popupMenu.cpp