KVIrc: KviKvsRWEvaluationResult Class Reference
KviKvsRWEvaluationResult Class Reference
#include <kvi_kvs_rwevaluationresult.h>
Public Member Functions
KviKvsRWEvaluationResult (KviKvsRWEvaluationResult *pParent, KviKvsVariant *pVariant)
KviKvsVariant * result ()
virtual ~KviKvsRWEvaluationResult ()
Protected Attributes
KviKvsRWEvaluationResult * m_pParent
KviKvsVariant * m_pVariant
Constructor & Destructor Documentation
KviKvsRWEvaluationResult::KviKvsRWEvaluationResult (KviKvsRWEvaluationResult * pParent, KviKvsVariant * pVariant)
References m_pParent, and m_pVariant.
KviKvsRWEvaluationResult::~KviKvsRWEvaluationResult () [virtual]
Member Function Documentation
KviKvsVariant* KviKvsRWEvaluationResult::result () [inline]
Referenced by KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeSpecialCommandUnset::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeOperationStringSubstitution::execute(), KviKvsTreeNodeOperationStringTransliteration::execute(), KviKvsTreeNodeOperationStringAppendWithSpace::execute(), KviKvsTreeNodeOperationStringAppendWithComma::execute(), KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsTreeNodeOperationStringAppend::execute(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationDecrement::execute(), and KviKvsTreeNodeOperationAssignment::execute().
Member Data Documentation
KviKvsRWEvaluationResult* KviKvsRWEvaluationResult::m_pParent [protected]
Referenced by KviKvsRWEvaluationResult(), KviKvsArrayElement::~KviKvsArrayElement(), and KviKvsHashElement::~KviKvsHashElement().
KviKvsVariant* KviKvsRWEvaluationResult::m_pVariant [protected]
Referenced by KviKvsRWEvaluationResult(), KviKvsArrayElement::~KviKvsArrayElement(), and KviKvsHashElement::~KviKvsHashElement().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_rwevaluationresult.h
src/kvirc/kvs/kvi_kvs_rwevaluationresult.cpp