KVIrc: KviIrcContextDisplayAction Class Reference
KviIrcContextDisplayAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual QAction * addToCustomToolBar (KviCustomToolBar *pTool)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
KviIrcContextDisplayAction (QObject *pParent)
virtual void setEnabled (bool)
Enables the action.
virtual void setup ()
Enables or disables the action upon starting KVIrc.
Constructor & Destructor Documentation
KviIrcContextDisplayAction::KviIrcContextDisplayAction (QObject * pParent)
Member Function Documentation
void KviIrcContextDisplayAction::activeContextChanged () [virtual]
Enables or disables the action upon checking the active context.
If the context doesn't exist, the action is disabled
Called when the frame changes the active context.
Note:
It works only if NeedsContext is specified
Returns:
void
Reimplemented from KviAction.
References a, KviPointerList< T >::first(), KviAction::m_pActionList, KviPointerList< T >::next(), t(), and w.
void KviIrcContextDisplayAction::activeContextStateChanged () [virtual]
Enables or disables the action upon checking the active context.
Called when the frame changes the state of the context
Returns:
void
Reimplemented from KviAction.
References a, KviPointerList< T >::first(), KviAction::m_pActionList, KviPointerList< T >::next(), t(), and w.
Referenced by setup().
QAction * KviIrcContextDisplayAction::addToCustomToolBar (KviCustomToolBar * pParentToolBar) [virtual]
Adds the action to the given toolbar.
Parameters:
pParentToolBar The toolbar where to add the action
Returns:
QAction *
Reimplemented from KviAction.
References KVI_COREACTION_IRCCONTEXTDISPLAY, KviAction::registerAction(), setup(), KviAction::setupDone(), and w.
bool KviIrcContextDisplayAction::addToPopupMenu (QMenu * pMenu) [virtual]
Adds the action to the given popup.
Parameters:
pMenu The menu where to add the action
Returns:
bool
Reimplemented from KviAction.
void KviIrcContextDisplayAction::setEnabled (bool bEnabled) [virtual]
Enables the action.
Parameters:
bEnabled Whether to enable the action
Returns:
void
Reimplemented from KviAction.
void KviIrcContextDisplayAction::setup () [virtual]
Enables or disables the action upon starting KVIrc.
Returns:
void
Reimplemented from KviAction.
References activeContextStateChanged(), connect(), and g_pMainWindow.
Referenced by addToCustomToolBar().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp