KVIrc: KviRemoteMircServerImportWizard Class Reference
KviRemoteMircServerImportWizard Class Reference
#include <libkvimircimport.h>
Public Member Functions
KviRemoteMircServerImportWizard (KviRemoteMircServersIniImport *f)
~KviRemoteMircServerImportWizard ()
Public Member Functions inherited from KviTalWizard
void addPage (QWidget *pWidget, const QString &szTitle)
QPushButton * backButton ()
QPushButton * cancelButton ()
QWidget * currentPage ()
QPushButton * finishButton ()
QPushButton * helpButton ()
void insertPage (QWidget *pWidget, const QString &szTitle, int iIndex)
KviTalWizard (QWidget *pParent)
QPushButton * nextButton ()
void setBackEnabled (QWidget *pWidget, bool bEnabled)
void setCancelEnabled (QWidget *pWidget, bool bEnabled)
bool setCurrentPage (QWidget *pWidget)
void setFinishEnabled (QWidget *pWidget, bool bEnabled)
void setHelpEnabled (QWidget *pWidget, bool bEnabled)
void setNextEnabled (QWidget *pWidget, bool bEnabled)
bool setPageEnabled (QWidget *pWidget, bool bEnabled)
bool setPageTitle (QWidget *pWidget, const QString &szTitle)
~KviTalWizard ()
Protected Slots
void getListMessage (const QString &message)
void getListTerminated (bool bSuccess)
void pageSelected (const QString &title)
Protected Slots inherited from KviTalWizard
void backButtonClicked ()
void cancelButtonClicked ()
void finishButtonClicked ()
void helpButtonClicked ()
void nextButtonClicked ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
virtual void done (int r)
void start ()
Protected Member Functions inherited from KviTalWizard
void setCurrentPage (KviTalWizardPageData *pData)
virtual void showEvent (QShowEvent *e)
Protected Attributes
KviRemoteMircServersIniImport * m_pFilter
QLabel * m_pOutput
KviHttpRequest * m_pRequest
QLineEdit * m_pUrlEdit
QString m_szTmpFileName
Protected Attributes inherited from KviTalWizard
KviTalWizardPrivate * m_p
Additional Inherited Members
Signals inherited from KviTalWizard
void helpClicked ()
void pageChanged (QString title)
Constructor & Destructor Documentation
KviRemoteMircServerImportWizard::KviRemoteMircServerImportWizard (KviRemoteMircServersIniImport * f)
References __tr2qs, KviTalWizard::addPage(), connect(), f, KVI_WWWMIRCCOUK_SERVERSINI, l, m_pFilter, m_pOutput, m_pRequest, m_pUrlEdit, KviTalWizard::pageChanged(), pageSelected(), KviTalWizard::setBackEnabled(), KviTalWizard::setFinishEnabled(), KviTalWizard::setNextEnabled(), and KviTalVBox::setStretchFactor().
KviRemoteMircServerImportWizard::~KviRemoteMircServerImportWizard ()
References m_pRequest.
Member Function Documentation
void KviRemoteMircServerImportWizard::closeEvent (QCloseEvent * e) protected virtual
Handles redirects the close button to the "cancel" operation.
Reimplemented from KviTalWizard.
References KviRemoteMircServersIniImport::die(), and m_pFilter.
void KviRemoteMircServerImportWizard::done (int r) protected virtual
References KviRemoteMircServersIniImport::die(), and m_pFilter.
void KviRemoteMircServerImportWizard::getListMessage (const QString & message) protected slot
References m_pOutput.
Referenced by start().
void KviRemoteMircServerImportWizard::getListTerminated (bool bSuccess) protected slot
References __tr2qs, KviTalWizard::cancelButton(), d, KviMircServersIniImport::doImport(), KviTalWizard::finishButton(), KviHttpRequest::lastError(), m_pFilter, m_pOutput, m_pRequest, and m_szTmpFileName.
Referenced by start().
void KviRemoteMircServerImportWizard::pageSelected (const QString & title) protected slot
References __tr2qs, and start().
Referenced by KviRemoteMircServerImportWizard().
void KviRemoteMircServerImportWizard::start () protected
References __tr2qs, connect(), KviTalWizard::finishButton(), g_pApp, KviHttpRequest::get(), getListMessage(), getListTerminated(), KviApplication::getTmpFileName(), KVI_WWWMIRCCOUK_SERVERSINI, m_pOutput, m_pRequest, m_pUrlEdit, m_szTmpFileName, and KviHttpRequest::StoreToFile.
Referenced by pageSelected().
Member Data Documentation
KviRemoteMircServersIniImport* KviRemoteMircServerImportWizard::m_pFilter protected
Referenced by closeEvent(), done(), getListTerminated(), and KviRemoteMircServerImportWizard().
QLabel* KviRemoteMircServerImportWizard::m_pOutput protected
Referenced by getListMessage(), getListTerminated(), KviRemoteMircServerImportWizard(), and start().
KviHttpRequest* KviRemoteMircServerImportWizard::m_pRequest protected
Referenced by getListTerminated(), KviRemoteMircServerImportWizard(), start(), and ~KviRemoteMircServerImportWizard().
QLineEdit* KviRemoteMircServerImportWizard::m_pUrlEdit protected
Referenced by KviRemoteMircServerImportWizard(), and start().
QString KviRemoteMircServerImportWizard::m_szTmpFileName protected
Referenced by getListTerminated(), and start().
The documentation for this class was generated from the following files:
src/modules/mircimport/libkvimircimport.h
src/modules/mircimport/libkvimircimport.cpp