KVIrc: KviKvsAliasManager Class Reference
KviKvsAliasManager Class Reference
#include <kvi_kvs_aliasmanager.h>
Signals
void aliasRefresh (const QString &)
Public Member Functions
void add (const QString &szName, KviKvsScript *pAlias)
KviPointerHashTable< QString,
KviKvsScript > * aliasDict ()
void clear ()
void completeCommand (const QString &word, KviPointerList< QString > *matches)
void load (const QString &filename)
const KviKvsScript * lookup (const QString &szName)
bool remove (const QString &szName)
void save (const QString &filename)
Static Public Member Functions
static void done ()
static void init ()
static KviKvsAliasManager * instance ()
Protected Member Functions
KviKvsAliasManager ()
~KviKvsAliasManager ()
Protected Attributes
KviPointerHashTable< QString,
KviKvsScript > * m_pAliasDict
Static Protected Attributes
static KviKvsAliasManager * m_pAliasManager = 0
Constructor & Destructor Documentation
KviKvsAliasManager::KviKvsAliasManager () [protected]
References m_pAliasDict, m_pAliasManager, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviKvsAliasManager::~KviKvsAliasManager () [protected]
References m_pAliasDict, and m_pAliasManager.
Member Function Documentation
void KviKvsAliasManager::add (const QString & szName, KviKvsScript * pAlias)
References aliasRefresh(), m_pAliasDict, and KviPointerHashTable< Key, T >::replace().
Referenced by KviKvsCoreCallbackCommands::KVSCCC().
KviPointerHashTable<QString,KviKvsScript>* KviKvsAliasManager::aliasDict () [inline]
void KviKvsAliasManager::aliasRefresh (const QString &) [signal]
Referenced by add().
void KviKvsAliasManager::clear () [inline]
Referenced by KviKvs::clearAliases().
void KviKvsAliasManager::completeCommand (const QString & word, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCIN(), m_pAliasDict, and KviKvsScript::name().
void KviKvsAliasManager::done () [static]
References debug, and instance().
void KviKvsAliasManager::init () [static]
References debug, instance(), and KviKvsAliasManager().
static KviKvsAliasManager* KviKvsAliasManager::instance () [inline, static]
Referenced by KviKvs::clearAliases(), done(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeAliasSimpleCommand::execute(), init(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvs::loadAliases(), and KviKvs::saveAliases().
void KviKvsAliasManager::load (const QString & filename)
References KviPointerList< T >::append(), KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfig::dict(), KviPointerList< T >::first(), KviPointerHashTable< Key, T >::insert(), m_pAliasDict, KviPointerList< T >::next(), KviConfig::Read, KviConfig::readQStringEntry(), s, KviPointerList< T >::setAutoDelete(), and KviConfig::setGroup().
Referenced by KviKvs::loadAliases().
const KviKvsScript* KviKvsAliasManager::lookup (const QString & szName) [inline]
References KviPointerHashTable< Key, T >::find().
Referenced by KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), and KviKvsTreeNodeAliasSimpleCommand::execute().
bool KviKvsAliasManager::remove (const QString & szName) [inline]
Referenced by KviKvsCoreCallbackCommands::KVSCCC().
void KviKvsAliasManager::save (const QString & filename)
References KviConfig::clear(), KviKvsScript::code(), KviPointerHashTableIterator< Key, T >::current(), m_pAliasDict, KviKvsScript::name(), KviConfig::setGroup(), KviConfig::Write, and KviConfig::writeEntry().
Referenced by KviKvs::saveAliases().
Member Data Documentation
KviPointerHashTable<QString,KviKvsScript>* KviKvsAliasManager::m_pAliasDict [protected]
Referenced by add(), completeCommand(), KviKvsAliasManager(), load(), save(), and ~KviKvsAliasManager().
KviKvsAliasManager * KviKvsAliasManager::m_pAliasManager = 0 [static, protected]
Referenced by KviKvsAliasManager(), and ~KviKvsAliasManager().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_aliasmanager.h
src/kvirc/kvs/kvi_kvs_aliasmanager.cpp