KVIrc: KviKvsScriptAddonManager Class Reference
KviKvsScriptAddonManager Class Reference
#include <KviKvsScriptAddonManager.h>
Public Member Functions
KviPointerHashTable< QString,
KviKvsScriptAddon > * addonDict ()
void clear ()
KviKvsScriptAddon * findAddon (const QString &szName)
KviKvsScriptAddonManager ()
void load (const QString &szFileName)
bool registerAddon (KviKvsScriptAddonRegistrationData *d)
void save (const QString &szFileName)
bool unregisterAddon (const QString &szName, KviWindow *pWnd, bool bExecuteUninstallCallback=true, bool bUninstallFiles=true)
~KviKvsScriptAddonManager ()
Static Public Member Functions
static void done ()
static void init ()
static KviKvsScriptAddonManager * instance ()
Protected Member Functions
void delayedLoad ()
Protected Attributes
bool m_bLoaded
KviPointerHashTable< QString,
KviKvsScriptAddon > * m_pAddonDict
QString m_szFileName
Static Protected Attributes
static KviKvsScriptAddonManager * m_pInstance = 0
Constructor & Destructor Documentation
KviKvsScriptAddonManager::KviKvsScriptAddonManager ()
References m_bLoaded, m_pAddonDict, m_pInstance, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviKvsScriptAddonManager::~KviKvsScriptAddonManager ()
References m_pAddonDict.
Member Function Documentation
KviPointerHashTable< QString, KviKvsScriptAddon > * KviKvsScriptAddonManager::addonDict ()
References delayedLoad(), m_bLoaded, and m_pAddonDict.
Referenced by addon_kvs_cmd_list(), and AddonManagementDialog::fillListView().
void KviKvsScriptAddonManager::clear ()
References KviPointerHashTable< Key, T >::clear(), delayedLoad(), m_bLoaded, and m_pAddonDict.
Referenced by KviKvs::clearScriptAddons().
void KviKvsScriptAddonManager::delayedLoad () protected
References a, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, KviConfigurationFile::dict(), KviKvsScriptAddon::load(), m_bLoaded, m_pAddonDict, m_szFileName, KviConfigurationFile::Read, and KviPointerHashTable< Key, T >::replace().
Referenced by addonDict(), clear(), and findAddon().
void KviKvsScriptAddonManager::done () static
References instance().
Referenced by KviKvs::done().
KviKvsScriptAddon * KviKvsScriptAddonManager::findAddon (const QString & szName)
References delayedLoad(), KviPointerHashTable< Key, T >::find(), m_bLoaded, and m_pAddonDict.
Referenced by addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), addon_kvs_fnc_exists(), addon_kvs_fnc_version(), registerAddon(), and unregisterAddon().
void KviKvsScriptAddonManager::init () static
References instance(), and KviKvsScriptAddonManager().
Referenced by KviKvs::init().
static KviKvsScriptAddonManager* KviKvsScriptAddonManager::instance () inline static
Referenced by addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_list(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), addon_kvs_fnc_exists(), addon_kvs_fnc_version(), KviKvs::clearScriptAddons(), done(), AddonManagementDialog::fillListView(), init(), KviKvs::loadScriptAddons(), KviKvs::saveScriptAddons(), and AddonManagementDialog::uninstallScript().
void KviKvsScriptAddonManager::load (const QString & szFileName)
References m_bLoaded, and m_szFileName.
Referenced by KviKvs::loadScriptAddons().
bool KviKvsScriptAddonManager::registerAddon (KviKvsScriptAddonRegistrationData * d)
References a, findAddon(), m_pAddonDict, KviPointerHashTable< Key, T >::replace(), KviKvsScriptAddonRegistrationData::szDescriptionScript, KviKvsScriptAddonRegistrationData::szIconId, KviKvsScriptAddonRegistrationData::szName, KviKvsScriptAddonRegistrationData::szUninstallCallbackScript, KviKvsScriptAddonRegistrationData::szVersion, and KviKvsScriptAddonRegistrationData::szVisibleNameScript.
Referenced by addon_kvs_cmd_register().
void KviKvsScriptAddonManager::save (const QString & szFileName)
References a, KviConfigurationFile::clear(), KviPointerHashTableIterator< Key, T >::current(), m_bLoaded, m_pAddonDict, m_szFileName, KviConfigurationFile::setGroup(), and KviConfigurationFile::Write.
Referenced by KviKvs::saveScriptAddons().
bool KviKvsScriptAddonManager::unregisterAddon (const QString & szName, KviWindow * pWnd, bool bExecuteUninstallCallback = true, bool bUninstallFiles = true)
References a, KviKvsScriptAddon::executeUninstallCallback(), findAddon(), g_pApp, KviApplication::getLocalKvircDirectory(), KviKvsScriptAddon::installedFiles(), m_pAddonDict, KviApplication::None, KviPointerHashTable< Key, T >::remove(), KviFileUtils::removeFile(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by addon_kvs_cmd_register(), addon_kvs_cmd_uninstall(), and AddonManagementDialog::uninstallScript().
Member Data Documentation
bool KviKvsScriptAddonManager::m_bLoaded protected
Referenced by addonDict(), clear(), delayedLoad(), findAddon(), KviKvsScriptAddonManager(), load(), and save().
KviPointerHashTable<QString,KviKvsScriptAddon>* KviKvsScriptAddonManager::m_pAddonDict protected
Referenced by addonDict(), clear(), delayedLoad(), findAddon(), KviKvsScriptAddonManager(), registerAddon(), save(), unregisterAddon(), and ~KviKvsScriptAddonManager().
KviKvsScriptAddonManager * KviKvsScriptAddonManager::m_pInstance = 0 static protected
Referenced by KviKvsScriptAddonManager().
QString KviKvsScriptAddonManager::m_szFileName protected
Referenced by delayedLoad(), load(), and save().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsScriptAddonManager.h
src/kvirc/kvs/KviKvsScriptAddonManager.cpp