KVIrc: KviKvsVariantList Class Reference
KviKvsVariantList Class Reference
Class to handle variant variables lists.
#include <KviKvsVariantList.h>
Public Member Functions
void allAsString (QString &szBuffer)
Appends all elements in a single string delimited by spaces.
void append (KviKvsVariant *pItem)
Appends an element to the list.
void append (const QString &szParam, bool bEscape=false)
Appends an element to the list.
void append (kvs_int_t iInt)
Appends an element to the list.
void append (kvs_real_t dReal)
Appends an element to the list.
void append (bool bBoolean)
Appends an element to the list.
void append (kvs_hobject_t hObject)
Appends an element to the list.
void append (KviKvsArray *pArray)
Appends an element to the list.
void append (KviKvsHash *pHash)
Appends an element to the list.
KviKvsVariant * at (int iIdx)
Returns the element of the list at the given index.
void clear ()
Clears the list.
unsigned int count ()
Returns the size of the list.
KviKvsVariant * first ()
Returns the first element of the list.
bool firstAsString (QString &szBuffer)
Returns true if there was a first parameter at all.
KviKvsVariantList ()
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1)
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1, KviKvsVariant *pV2)
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1, KviKvsVariant *pV2, KviKvsVariant *pV3)
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1, KviKvsVariant *pV2, KviKvsVariant *pV3, KviKvsVariant *pV4)
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1, KviKvsVariant *pV2, KviKvsVariant *pV3, KviKvsVariant *pV4, KviKvsVariant *pV5)
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1, KviKvsVariant *pV2, KviKvsVariant *pV3, KviKvsVariant *pV4, KviKvsVariant *pV5, KviKvsVariant *pV6)
Constructs the KviKvsVariantList object.
KviKvsVariantList (KviKvsVariant *pV1, KviKvsVariant *pV2, KviKvsVariant *pV3, KviKvsVariant *pV4, KviKvsVariant *pV5, KviKvsVariant *pV6, KviKvsVariant *pV7)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1, QString *pS2)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1, QString *pS2, QString *pS3)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1, QString *pS2, QString *pS3, QString *pS4)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1, QString *pS2, QString *pS3, QString *pS4, QString *pS5)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1, QString *pS2, QString *pS3, QString *pS4, QString *pS5, QString *pS6)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QString *pS1, QString *pS2, QString *pS3, QString *pS4, QString *pS5, QString *pS6, QString *pS7)
Constructs the KviKvsVariantList object.
KviKvsVariantList (QStringList *pSL)
Constructs the KviKvsVariantList object.
KviKvsVariant * next ()
Returns the next element of the list.
bool nextAsString (QString &szBuffer)
Returns true if there was a next parameter at all.
void prepend (KviKvsVariant *pItem)
Prepends an element to the list.
void setAutoDelete (bool bAutoDelete)
Sets the auto delete flag on the list.
~KviKvsVariantList ()
Destroys the KviKvsVariantList object.
Protected Attributes
KviPointerList< KviKvsVariant > * m_pList
Detailed Description
Class to handle variant variables lists.
Constructor & Destructor Documentation
KviKvsVariantList::KviKvsVariantList ()
Constructs the KviKvsVariantList object.
Returns
KviKvsVariantList
References m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1, KviKvsVariant * pV2)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
pV2 The second element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1, KviKvsVariant * pV2, KviKvsVariant * pV3)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
pV2 The second element's list
pV3 The third element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1, KviKvsVariant * pV2, KviKvsVariant * pV3, KviKvsVariant * pV4)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
pV2 The second element's list
pV3 The third element's list
pV4 The fourth element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1, KviKvsVariant * pV2, KviKvsVariant * pV3, KviKvsVariant * pV4, KviKvsVariant * pV5)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
pV2 The second element's list
pV3 The third element's list
pV4 The fourth element's list
pV5 The fifth element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1, KviKvsVariant * pV2, KviKvsVariant * pV3, KviKvsVariant * pV4, KviKvsVariant * pV5, KviKvsVariant * pV6)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
pV2 The second element's list
pV3 The third element's list
pV4 The fourth element's list
pV5 The fifth element's list
pV6 The sixth element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (KviKvsVariant * pV1, KviKvsVariant * pV2, KviKvsVariant * pV3, KviKvsVariant * pV4, KviKvsVariant * pV5, KviKvsVariant * pV6, KviKvsVariant * pV7)
Constructs the KviKvsVariantList object.
Parameters
pV1 The first element's list
pV2 The second element's list
pV3 The third element's list
pV4 The fourth element's list
pV5 The fifth element's list
pV6 The sixth element's list
pV7 The seventh element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1, QString * pS2)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
pS2 The second element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1, QString * pS2, QString * pS3)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
pS2 The second element's list
pS3 The third element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1, QString * pS2, QString * pS3, QString * pS4)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
pS2 The second element's list
pS3 The third element's list
pS4 The fourth element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1, QString * pS2, QString * pS3, QString * pS4, QString * pS5)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
pS2 The second element's list
pS3 The third element's list
pS4 The fourth element's list
pS5 The fifth element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1, QString * pS2, QString * pS3, QString * pS4, QString * pS5, QString * pS6)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
pS2 The second element's list
pS3 The third element's list
pS4 The fourth element's list
pS5 The fifth element's list
pS6 The sixth element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QString * pS1, QString * pS2, QString * pS3, QString * pS4, QString * pS5, QString * pS6, QString * pS7)
Constructs the KviKvsVariantList object.
Parameters
pS1 The first element's list
pS2 The second element's list
pS3 The third element's list
pS4 The fourth element's list
pS5 The fifth element's list
pS6 The sixth element's list
pS7 The seventh element's list
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::KviKvsVariantList (QStringList * pSL)
Constructs the KviKvsVariantList object.
Parameters
pSL Pointer to a QStringList
Returns
KviKvsVariantList
References KviPointerList< T >::append(), m_pList, and KviPointerList< T >::setAutoDelete().
KviKvsVariantList::~KviKvsVariantList ()
Destroys the KviKvsVariantList object.
References m_pList.
Member Function Documentation
void KviKvsVariantList::allAsString (QString & szBuffer)
Appends all elements in a single string delimited by spaces.
Parameters
szBuffer The buffer where to store the string
Returns
void
References first(), next(), and v.
Referenced by KviKvsTreeNodeParameterReturn::execute(), and KviKvsTreeNodeAliasSimpleCommand::execute().
void KviKvsVariantList::append (KviKvsVariant * pItem) inline
Appends an element to the list.
Parameters
pItem The element to append
Returns
void
Referenced by KviKvsObjectClass::allocateInstance(), KviScriptUserButton::btnClicked(), KviXmlHandler::characters(), KviKvsCallbackMessageBox::done(), KviKvsCallbackTextInput::done(), KviKvsCallbackFileDialog::done(), KviKvsCallbackImageDialog::done(), KviUserListView::emitDoubleClick(), KviUserListView::emitRightClick(), KviXmlHandler::endElement(), KviXmlHandler::error(), KviKvsTreeNodeDataList::evaluate(), KvsObject_widget::eventFilter(), KviKvsCallbackObject::execute(), KvsObject_xmlReader::fatalError(), KviKvsCallbackObject::KviKvsCallbackObject(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreSimpleCommands::KVSCSC(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcView::mouseDoubleClickEvent(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), popup_kvs_cmd_show(), setup_finish(), KvsObject_trayIcon::slotActivated(), KvsObject_ftp::slotCommandFinished(), KvsObject_http::slotDataReadProgress(), KvsObject_http::slotDataSendProgress(), KvsObject_ftp::slotDataTransferProgress(), KvsObject_http::slotDone(), KvsObject_socket::slotError(), KvsObject_ftp::slotListInfo(), KvsObject_socket::slotReadyRead(), KvsObject_http::slotReadyRead(), KvsObject_http::slotRequestFinished(), KvsObject_http::slotRequestStarted(), KvsObject_http::slotResponseHeaderReceived(), KvsObject_http::slotSslErrors(), KvsObject_ftp::slotStateChanged(), KvsObject_socket::slotStateChanged(), KvsObject_http::slotStateChanged(), KviXmlHandler::startElement(), SinglePopupEditor::testPopup(), HttpFileTransfer::transferTerminated(), KviKvsProcessAsyncOperation::trigger(), KviIrcView::triggerMouseRelatedKvsEvents(), and KviXmlHandler::warning().
void KviKvsVariantList::append (const QString & szParam, bool bEscape = false) inline
Appends an element to the list.
Parameters
szParam The string element to append
bEscape Whether the string has to be escaped for KVS
Returns
void
void KviKvsVariantList::append (kvs_int_t iInt) inline
Appends an element to the list.
Parameters
iInt The integer element to append
Returns
void
void KviKvsVariantList::append (kvs_real_t dReal) inline
Appends an element to the list.
Parameters
dReal The real element to append
Returns
void
void KviKvsVariantList::append (bool bBoolean) inline
Appends an element to the list.
Parameters
bBoolean The boolean element to append
Returns
void
void KviKvsVariantList::append (kvs_hobject_t hObject) inline
Appends an element to the list.
Parameters
hObject The hObject element to append
Returns
void
void KviKvsVariantList::append (KviKvsArray * pArray) inline
Appends an element to the list.
Parameters
pArray The array element to append
Returns
void
void KviKvsVariantList::append (KviKvsHash * pHash) inline
Appends an element to the list.
Parameters
pHash The hash element to append
Returns
void
KviKvsVariant* KviKvsVariantList::at (int iIdx) inline
Returns the element of the list at the given index.
Parameters
iIdx The index of the list we want to extract
Returns
KviKvsVariant *
Referenced by KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeSingleParameterIdentifier::evaluateReadOnly(), and PluginManager::pluginCall().
void KviKvsVariantList::clear () inline
Clears the list.
Returns
void
Referenced by KviKvsTreeNodeDataList::evaluate().
unsigned int KviKvsVariantList::count () inline
Returns the size of the list.
Returns
unsigned int
Referenced by KviKvsTreeNodeParameterCount::evaluateReadOnly(), KviKvsTreeNodeParameterReturn::execute(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), KvsObject_textedit::functionsetColor(), KviKvsCoreSimpleCommands::KVSCSC(), str_kvs_fnc_split(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_fnc_ischannelhighlighted(), window_kvs_cmd_highlight(), and window_kvs_fnc_open().
KviKvsVariant* KviKvsVariantList::first () inline
Returns the first element of the list.
Returns
KviKvsVariant *
Referenced by allAsString(), KviKvsObjectClass::allocateInstance(), KviKvsTreeNodeParameterReturn::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsCallbackObject::execute(), firstAsString(), KviKvsCallbackObject::KviKvsCallbackObject(), perl_kvs_cmd_begin(), popup_kvs_cmd_show(), KviKvsParameterProcessor::process(), python_kvs_cmd_begin(), and str_kvs_fnc_printf().
bool KviKvsVariantList::firstAsString (QString & szBuffer)
Returns true if there was a first parameter at all.
Parameters
szBuffer The buffer where to store the string
Returns
bool
References KviKvsVariant::asString(), first(), and v.
KviKvsVariant* KviKvsVariantList::next () inline
Returns the next element of the list.
Returns
KviKvsVariant *
Referenced by allAsString(), KviKvsObjectClass::allocateInstance(), KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsCallbackObject::execute(), KviKvsCallbackObject::KviKvsCallbackObject(), nextAsString(), perl_kvs_cmd_begin(), popup_kvs_cmd_show(), KviKvsParameterProcessor::process(), python_kvs_cmd_begin(), and str_kvs_fnc_printf().
bool KviKvsVariantList::nextAsString (QString & szBuffer)
Returns true if there was a next parameter at all.
Parameters
szBuffer The buffer where to store the string
Returns
bool
References KviKvsVariant::asString(), next(), and v.
void KviKvsVariantList::prepend (KviKvsVariant * pItem) inline
Prepends an element to the list.
Parameters
pItem The element to prepend
Returns
void
Referenced by KviKvsDnsManager::dnsLookupTerminated(), and KviKvsCoreSimpleCommands::KVSCSC().
void KviKvsVariantList::setAutoDelete (bool bAutoDelete)
Sets the auto delete flag on the list.
Parameters
bAutoDelete Whether the list has to auto delete itself
Returns
void
References m_pList, and KviPointerList< T >::setAutoDelete().
Referenced by KviKvsObjectClass::allocateInstance(), KviXmlHandler::characters(), KviXmlHandler::endElement(), KviXmlHandler::error(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeCoreSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeCoreCallbackCommand::execute(), KviKvsCallbackObject::execute(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviXmlHandler::startElement(), KviKvsProcessAsyncOperation::trigger(), and KviXmlHandler::warning().
Member Data Documentation
KviPointerList<KviKvsVariant>* KviKvsVariantList::m_pList protected
Referenced by KviKvsVariantList(), setAutoDelete(), and ~KviKvsVariantList().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsVariantList.h
src/kvirc/kvs/KviKvsVariantList.cpp