KVIrc: EventEditorWindow Class Reference
EventEditorWindow Class Reference
#include <EventEditorWindow.h>
Public Member Functions
EventEditorWindow ()
~EventEditorWindow ()
Protected Slots
void applyClicked ()
void cancelClicked ()
void okClicked ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void getConfigGroupName (QString &szName)
virtual void loadProperties (KviConfigurationFile *)
virtual QPixmap * myIconPtr ()
virtual void saveProperties (KviConfigurationFile *)
Protected Attributes
EventEditor * m_pEditor
Constructor & Destructor Documentation
EventEditorWindow::EventEditorWindow ()
References __tr2qs_ctx(), KviIconManager::Accept, applyClicked(), cancelClicked(), connect(), KviIconManager::Discard, g, g_pIconManager, KviIconManager::getSmallIcon(), m_pEditor, and okClicked().
EventEditorWindow::~EventEditorWindow ()
Member Function Documentation
void EventEditorWindow::applyClicked () [protected, slot]
References EventEditor::commit(), and m_pEditor.
Referenced by EventEditorWindow().
void EventEditorWindow::cancelClicked () [protected, slot]
Referenced by EventEditorWindow().
void EventEditorWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void EventEditorWindow::getConfigGroupName (QString & szName) [protected, virtual]
Reimplemented from KviWindow.
void EventEditorWindow::loadProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
QPixmap * EventEditorWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References KviIconManager::Event, g_pIconManager, and KviIconManager::getSmallIcon().
void EventEditorWindow::okClicked () [protected, slot]
References EventEditor::commit(), and m_pEditor.
Referenced by EventEditorWindow().
void EventEditorWindow::saveProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
Member Data Documentation
EventEditor* EventEditorWindow::m_pEditor [protected]
Referenced by applyClicked(), EventEditorWindow(), and okClicked().
The documentation for this class was generated from the following files:
src/modules/eventeditor/EventEditorWindow.h
src/modules/eventeditor/EventEditorWindow.cpp