KVIrc: KviMircTextColorSelector Class Reference
KviMircTextColorSelector Class Reference
#include <KviSelectors.h>
Public Member Functions
virtual void commit ()
KviMircTextColorSelector (QWidget *par, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled)
virtual void setEnabled (bool bEnabled)
~KviMircTextColorSelector ()
Public Member Functions inherited from KviTalHBox
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void backSelected (QAction *pAction)
void buttonClicked ()
void foreSelected (QAction *pAction)
Protected Member Functions
void setButtonPalette ()
Protected Member Functions inherited from KviTalHBox
virtual void childEvent (QChildEvent *e)
Private Attributes
QMenu * m_pBackPopup
QPushButton * m_pButton
QMenu * m_pContextPopup
QMenu * m_pForePopup
QLabel * m_pLabel
unsigned int * m_pUBack
unsigned int * m_pUFore
unsigned int m_uBack
unsigned int m_uFore
Constructor & Destructor Documentation
KviMircTextColorSelector::KviMircTextColorSelector (QWidget * par, const QString & txt, unsigned int * uFore, unsigned int * uBack, bool bEnabled)
References __tr2qs, backSelected(), buttonClicked(), connect(), foreSelected(), KVI_MIRCCOLOR_MAX_BACKGROUND, KVI_MIRCCOLOR_MAX_FOREGROUND, KVI_OPTION_MIRCCOLOR, m_pBackPopup, m_pButton, m_pContextPopup, m_pForePopup, m_pLabel, m_pUBack, m_pUFore, m_uBack, m_uFore, setButtonPalette(), setEnabled(), KviTalHBox::setMargin(), KviTalHBox::setSpacing(), KviTalHBox::setStretchFactor(), and KviControlCodes::Transparent.
KviMircTextColorSelector::~KviMircTextColorSelector () default
Member Function Documentation
void KviMircTextColorSelector::backSelected (QAction * pAction) protected slot
References m_uBack, and setButtonPalette().
Referenced by KviMircTextColorSelector().
void KviMircTextColorSelector::buttonClicked () protected slot
References m_pButton, m_pContextPopup, and p.
Referenced by KviMircTextColorSelector().
void KviMircTextColorSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pUBack, m_pUFore, m_uBack, and m_uFore.
void KviMircTextColorSelector::foreSelected (QAction * pAction) protected slot
References m_uFore, and setButtonPalette().
Referenced by KviMircTextColorSelector().
void KviMircTextColorSelector::setButtonPalette () protected
References KVI_MIRCCOLOR_MAX_BACKGROUND, KVI_MIRCCOLOR_MAX_FOREGROUND, KVI_OPTION_MIRCCOLOR, m_pButton, m_uBack, m_uFore, and KviControlCodes::Transparent.
Referenced by backSelected(), foreSelected(), and KviMircTextColorSelector().
void KviMircTextColorSelector::setEnabled (bool bEnabled) virtual
References m_pButton, and m_pLabel.
Referenced by OptionsWidget_privmsg::enableDisableSmartColorSelector(), OptionsWidget_timestamp::enableDisableTimestampSelector(), and KviMircTextColorSelector().
Member Data Documentation
QMenu* KviMircTextColorSelector::m_pBackPopup private
Referenced by KviMircTextColorSelector().
QPushButton* KviMircTextColorSelector::m_pButton private
Referenced by buttonClicked(), KviMircTextColorSelector(), setButtonPalette(), and setEnabled().
QMenu* KviMircTextColorSelector::m_pContextPopup private
Referenced by buttonClicked(), and KviMircTextColorSelector().
QMenu* KviMircTextColorSelector::m_pForePopup private
Referenced by KviMircTextColorSelector().
QLabel* KviMircTextColorSelector::m_pLabel private
Referenced by KviMircTextColorSelector(), and setEnabled().
unsigned int* KviMircTextColorSelector::m_pUBack private
Referenced by commit(), and KviMircTextColorSelector().
unsigned int* KviMircTextColorSelector::m_pUFore private
Referenced by commit(), and KviMircTextColorSelector().
unsigned int KviMircTextColorSelector::m_uBack private
Referenced by backSelected(), commit(), KviMircTextColorSelector(), and setButtonPalette().
unsigned int KviMircTextColorSelector::m_uFore private
Referenced by commit(), foreSelected(), KviMircTextColorSelector(), and setButtonPalette().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp