KVIrc: KviKvsTreeNodeExpressionReturn Class Reference
KviKvsTreeNodeExpressionReturn Class Reference
#include <KviKvsTreeNodeExpressionReturn.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeExpressionReturn (const QChar *pLocation, KviKvsTreeNodeExpression *pExpression)
~KviKvsTreeNodeExpressionReturn ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeExpression * m_pExpression
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionReturn::KviKvsTreeNodeExpressionReturn (const QChar * pLocation, KviKvsTreeNodeExpression * pExpression)
References m_pExpression, and KviKvsTreeNode::setParent().
KviKvsTreeNodeExpressionReturn::~KviKvsTreeNodeExpressionReturn ()
References m_pExpression.
Member Function Documentation
void KviKvsTreeNodeExpressionReturn::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeInstruction.
void KviKvsTreeNodeExpressionReturn::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeInstruction.
References KviKvsTreeNodeExpression::dump(), and m_pExpression.
bool KviKvsTreeNodeExpressionReturn::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsTreeNodeData::evaluateReadOnly(), m_pExpression, and KviKvsRunTimeContext::returnValue().
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeExpressionReturn::m_pExpression protected
Referenced by dump(), execute(), KviKvsTreeNodeExpressionReturn(), and ~KviKvsTreeNodeExpressionReturn().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExpressionReturn.h
src/kvirc/kvs/tree/KviKvsTreeNodeExpressionReturn.cpp