KVIrc: KviKvsCallbackObject Class Reference
KviKvsCallbackObject Class Reference
#include <KviKvsCallbackObject.h>
Public Types
enum CallbackFlags { OnlyIfWindowExists = 1 }
enum CallbackStatus { Success, Error, HaltEncountered, TargetWindowDead }
Public Member Functions
KviKvsCallbackObject (const QString &szCallbackSource, KviWindow *pTargetWindow, const QString &szCallbackCode, KviKvsVariantList *pMagicParams, unsigned int uFlags=0)
virtual ~KviKvsCallbackObject ()
Protected Member Functions
CallbackStatus execute (KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0)
Protected Attributes
KviKvsVariantList * m_pMagicParams
KviKvsScript * m_pScript
KviWindow * m_pTargetConsole
KviWindow * m_pTargetWindow
unsigned int m_uFlags
Member Enumeration Documentation
enum KviKvsCallbackObject::CallbackFlags
Enumerator:
OnlyIfWindowExists
enum KviKvsCallbackObject::CallbackStatus
Enumerator:
Success
Error
HaltEncountered
TargetWindowDead
Constructor & Destructor Documentation
KviKvsCallbackObject::KviKvsCallbackObject (const QString & szCallbackSource, KviWindow * pTargetWindow, const QString & szCallbackCode, KviKvsVariantList * pMagicParams, unsigned int uFlags = 0)
References KviKvsVariantList::append(), KviWindow::console(), KviKvsVariantList::first(), m_pMagicParams, m_pScript, m_pTargetConsole, m_pTargetWindow, m_uFlags, KviKvsVariantList::next(), and v.
KviKvsCallbackObject::~KviKvsCallbackObject () [virtual]
References m_pMagicParams, and m_pScript.
Member Function Documentation
KviKvsCallbackObject::CallbackStatus KviKvsCallbackObject::execute (KviKvsVariantList * pParams = 0, KviKvsVariant * pRetVal = 0) [protected]
References KviApplication::activeConsole(), KviKvsVariantList::append(), Error, KviKvsVariantList::first(), g_pApp, HaltEncountered, KviKvsScript::HaltEncountered, m_pMagicParams, m_pScript, m_pTargetConsole, m_pTargetWindow, m_uFlags, KviKvsVariantList::next(), OnlyIfWindowExists, KviKvsScript::PreserveParams, KviKvsScript::run(), KviKvsVariantList::setAutoDelete(), Success, TargetWindowDead, v, and KviApplication::windowExists().
Referenced by KviKvsCallbackImageDialog::done(), KviKvsCallbackFileDialog::done(), KviKvsCallbackTextInput::done(), and KviKvsCallbackMessageBox::done().
Member Data Documentation
KviKvsVariantList* KviKvsCallbackObject::m_pMagicParams [protected]
Referenced by execute(), KviKvsCallbackObject(), and ~KviKvsCallbackObject().
KviKvsScript* KviKvsCallbackObject::m_pScript [protected]
Referenced by execute(), KviKvsCallbackObject(), and ~KviKvsCallbackObject().
KviWindow* KviKvsCallbackObject::m_pTargetConsole [protected]
Referenced by execute(), and KviKvsCallbackObject().
KviWindow* KviKvsCallbackObject::m_pTargetWindow [protected]
Referenced by execute(), and KviKvsCallbackObject().
unsigned int KviKvsCallbackObject::m_uFlags [protected]
Referenced by execute(), and KviKvsCallbackObject().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsCallbackObject.h
src/kvirc/kvs/KviKvsCallbackObject.cpp