KVIrc: OptionsWidget_identityAdvanced Class Reference
OptionsWidget_identityAdvanced Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
OptionsWidget_identityAdvanced (QWidget *pParent)
~OptionsWidget_identityAdvanced ()
Protected Member Functions
virtual void commit ()
Protected Attributes
bool m_bI
bool m_bS
bool m_bW
KviBoolSelector * m_pISelector
KviBoolSelector * m_pSSelector
KviBoolSelector * m_pWSelector
KviCString m_sModeStr
Constructor & Destructor Documentation
OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced (QWidget * pParent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviCString::contains(), KviOptionsWidget::createLayout(), KVI_OPTION_STRING, KviOption_stringDefaultUserMode, KviOption_stringPartMessage, KviOption_stringQuitMessage, KviOptionsWidget::layout(), m_bI, m_bS, m_bW, m_pISelector, m_pSSelector, m_pWSelector, m_sModeStr, KviOptionsWidget::mergeTip(), and KviStringSelector::setMinimumLabelWidth().
OptionsWidget_identityAdvanced::~OptionsWidget_identityAdvanced ()
Member Function Documentation
void OptionsWidget_identityAdvanced::commit (void) [protected, virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_STRING, KviOption_stringDefaultUserMode, m_bI, m_bS, m_bW, m_sModeStr, and KviCString::ptr().
Member Data Documentation
bool OptionsWidget_identityAdvanced::m_bI [protected]
Referenced by commit(), and OptionsWidget_identityAdvanced().
bool OptionsWidget_identityAdvanced::m_bS [protected]
Referenced by commit(), and OptionsWidget_identityAdvanced().
bool OptionsWidget_identityAdvanced::m_bW [protected]
Referenced by commit(), and OptionsWidget_identityAdvanced().
KviBoolSelector* OptionsWidget_identityAdvanced::m_pISelector [protected]
Referenced by OptionsWidget_identityAdvanced().
KviBoolSelector* OptionsWidget_identityAdvanced::m_pSSelector [protected]
Referenced by OptionsWidget_identityAdvanced().
KviBoolSelector* OptionsWidget_identityAdvanced::m_pWSelector [protected]
Referenced by OptionsWidget_identityAdvanced().
KviCString OptionsWidget_identityAdvanced::m_sModeStr [protected]
Referenced by commit(), and OptionsWidget_identityAdvanced().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp