KVIrc: KviStatusBarLagIndicator Class Reference
KviStatusBarLagIndicator Class Reference
#include <KviStatusBarApplet.h>
Public Member Functions
KviStatusBarLagIndicator (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
virtual ~KviStatusBarLagIndicator ()
Static Public Member Functions
static void selfRegister (KviStatusBar *pBar)
Protected Slots
void updateDisplay ()
Protected Member Functions
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual QString tipText (const QPoint &)
Constructor & Destructor Documentation
KviStatusBarLagIndicator::KviStatusBarLagIndicator (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
References KviMainWindow::activeConnectionLagChanged(), KviMainWindow::activeContextChanged(), KviMainWindow::activeContextStateChanged(), connect(), KviStatusBar::frame(), and updateDisplay().
KviStatusBarLagIndicator::~KviStatusBarLagIndicator () [virtual]
Member Function Documentation
void KviStatusBarLagIndicator::mouseDoubleClickEvent (QMouseEvent * e) [protected, virtual]
References KviMainWindow::activeConnection(), c, KviIrcConnection::Connected, KviStatusBar::frame(), g_pApp, KVI_OPTION_BOOL, KviOption_boolUseLagMeterEngine, KviIrcConnection::lagMeter(), KviApplication::restartLagMeters(), KviIrcConnection::state(), and KviStatusBarApplet::statusBar().
void KviStatusBarLagIndicator::selfRegister (KviStatusBar * pBar) [static]
References __tr2qs, CreateStatusBarLagIndicator(), d, g_pIconManager, KviIconManager::getSmallIcon(), KviStatusBar::registerAppletDescriptor(), and KviIconManager::ServerPing.
Referenced by KviStatusBar::KviStatusBar().
QString KviStatusBarLagIndicator::tipText (const QPoint &) [protected, virtual]
Reimplemented from KviStatusBarApplet.
References __tr2qs, KviMainWindow::activeConnection(), KviQString::appendFormatted(), c, KviIrcConnection::Connected, KviStatusBar::frame(), KviLagMeter::lag(), KviIrcConnection::lagMeter(), KviLagMeter::secondsSinceLastCompleted(), KviIrcConnection::state(), and KviStatusBarApplet::statusBar().
void KviStatusBarLagIndicator::updateDisplay () [protected, slot]
References __tr2qs, KviMainWindow::activeContext(), c, KviIrcContext::connection(), KviStatusBar::frame(), KviIrcContext::isConnected(), KviLagMeter::lag(), KviIrcConnection::lagMeter(), and KviStatusBarApplet::statusBar().
Referenced by KviStatusBarLagIndicator().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviStatusBarApplet.h
src/kvirc/ui/KviStatusBarApplet.cpp