KVIrc: KviIrcConnectionTargetResolver Class Reference
KviIrcConnectionTargetResolver Class Reference
#include <KviIrcConnectionTargetResolver.h>
Public Types
enum State { Idle, Running, Terminated }
enum Status { Success, Error }
Signals
void terminated ()
Public Member Functions
void abort ()
int lastError ()
void start (KviIrcConnectionTarget *t)
Status status ()
Protected Slots
void asyncStartResolve ()
void proxyLookupTerminated (KviDnsResolver *)
void serverLookupTerminated (KviDnsResolver *)
Protected Member Functions
KviIrcConnectionTargetResolver (KviIrcConnection *pConnection)
~KviIrcConnectionTargetResolver ()
Private Member Functions
void cleanup ()
void haveServerIp ()
void lookupProxyHostname ()
void lookupServerHostname ()
void terminate (Status s, int iLastError)
bool validateLocalAddress (const QString &szAddress, QString &szBuffer)
Private Attributes
State m_eState
Status m_eStatus
int m_iLastError
KviIrcConnection * m_pConnection
KviConsoleWindow * m_pConsole
KviDnsResolver * m_pProxyDns
char * m_pReadBuffer
KviDnsResolver * m_pServerDns
QTimer * m_pStartTimer
KviIrcConnectionTarget * m_pTarget
unsigned int m_uReadBufferLen
unsigned int m_uReadPackets
Friends
class KviIrcLink
Member Enumeration Documentation
enum KviIrcConnectionTargetResolver::State
Enumerator:
Idle
Running
Terminated
enum KviIrcConnectionTargetResolver::Status
Enumerator:
Success
Error
Constructor & Destructor Documentation
KviIrcConnectionTargetResolver::KviIrcConnectionTargetResolver (KviIrcConnection * pConnection) [protected]
References KviIrcConnection::console(), Idle, m_eState, m_eStatus, m_iLastError, m_pConnection, m_pConsole, m_pProxyDns, m_pServerDns, m_pStartTimer, m_pTarget, and Success.
KviIrcConnectionTargetResolver::~KviIrcConnectionTargetResolver () [protected]
References cleanup().
Member Function Documentation
void KviIrcConnectionTargetResolver::abort ()
References __tr2qs, cleanup(), Error, KVI_OUT_SYSTEMERROR, m_eState, m_pConsole, KviError::OperationAborted, KviWindow::outputNoFmt(), terminate(), and Terminated.
Referenced by KviIrcLink::abort().
void KviIrcConnectionTargetResolver::asyncStartResolve () [protected, slot]
References __tr2qs, KviProxy::hostName(), KviIrcServer::hostName(), KVI_OUT_SYSTEMMESSAGE, lookupProxyHostname(), lookupServerHostname(), m_pConsole, m_pStartTimer, m_pTarget, KviIrcNetwork::name(), KviIrcConnectionTarget::network(), KviWindow::output(), KviProxy::port(), KviIrcServer::port(), KviProxy::protocolName(), KviIrcConnectionTarget::proxy(), KviIrcConnectionTarget::server(), and KviIrcServer::useSSL().
Referenced by start().
void KviIrcConnectionTargetResolver::cleanup () [private]
References KviDnsResolver::isRunning(), m_pProxyDns, m_pServerDns, and m_pStartTimer.
Referenced by abort(), terminate(), and ~KviIrcConnectionTargetResolver().
void KviIrcConnectionTargetResolver::haveServerIp () [private]
References __tr2qs, _OUTPUT_MUTE, KviIrcConnectionTarget::bindAddress(), KviMainWindow::executeInternalCommand(), KviWindow::frame(), KviIrcConnectionTarget::hasBindAddress(), KviIrcServer::isIPv6(), KVI_INTERNALCOMMAND_IDENT_START, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_SYSTEMWARNING, KviOption_boolBindIrcIPv4ConnectionsToSpecifiedAddress, KviOption_boolBindIrcIPv6ConnectionsToSpecifiedAddress, KviOption_boolUseIdentService, KviOption_boolUseIdentServiceOnlyOnConnect, KviOption_stringIPv4ConnectionBindAddress, KviOption_stringIPv6ConnectionBindAddress, m_pConsole, m_pTarget, KviWindow::output(), KviIrcConnectionTarget::server(), KviIrcConnectionTarget::setBindAddress(), KviError::Success, Success, terminate(), and validateLocalAddress().
Referenced by lookupServerHostname(), and serverLookupTerminated().
int KviIrcConnectionTargetResolver::lastError () [inline]
Referenced by KviIrcLink::resolverTerminated().
void KviIrcConnectionTargetResolver::lookupProxyHostname () [private]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, KviIrcConnectionTarget::clearProxy(), connect(), KviProxy::hostName(), KviProxy::Http, KviProxy::ip(), KviDnsResolver::IPv4, KviDnsResolver::IPv6, KviProxy::isIPv6(), KviNetUtils::isValidStringIp(), KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviDnsResolver::lookup(), lookupServerHostname(), m_pConsole, m_pProxyDns, m_pTarget, KviWindow::output(), KviWindow::outputNoFmt(), KviProxy::protocol(), KviIrcConnectionTarget::proxy(), proxyLookupTerminated(), KviProxy::setIp(), KviProxy::Socks5, KviError::Success, Success, and terminate().
Referenced by asyncStartResolve().
void KviIrcConnectionTargetResolver::lookupServerHostname () [private]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, KviIrcServer::cacheIp(), connect(), Error, haveServerIp(), KviIrcServer::hostName(), KviError::InternalError, KviIrcServer::ip(), KviDnsResolver::IPv4, KviDnsResolver::IPv6, KviIrcServer::isIPv6(), KviNetUtils::isValidStringIp(), KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KviDnsResolver::lookup(), m_pConsole, m_pServerDns, m_pTarget, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcConnectionTarget::server(), serverLookupTerminated(), KviIrcServer::setIp(), and terminate().
Referenced by asyncStartResolve(), lookupProxyHostname(), and proxyLookupTerminated().
void KviIrcConnectionTargetResolver::proxyLookupTerminated (KviDnsResolver *) [protected, slot]
References __tr2qs, _OUTPUT_MUTE, KviIrcConnectionTarget::clearProxy(), KviDnsResolver::errorString(), KviDnsResolver::firstIpAddress(), g_pProxyDataBase, KviProxy::Http, KviProxy::ip(), KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, lookupServerHostname(), m_pConsole, m_pProxyDns, m_pTarget, KviWindow::output(), KviProxy::protocol(), KviIrcConnectionTarget::proxy(), KviProxy::setIp(), KviProxy::Socks5, KviDnsResolver::state(), KviError::Success, Success, terminate(), and KviProxyDataBase::updateProxyIp().
Referenced by lookupProxyHostname().
void KviIrcConnectionTargetResolver::serverLookupTerminated (KviDnsResolver *) [protected, slot]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, KviPointerList< T >::at(), KviQString::equalCI(), KviDnsResolver::error(), Error, KviDnsResolver::errorString(), KviDnsResolver::firstIpAddress(), haveServerIp(), KviDnsResolver::hostName(), KviIrcServer::hostName(), KviDnsResolver::ipAddressCount(), KviDnsResolver::ipAddressList(), KviIrcServer::isIPv6(), KVI_OPTION_BOOL, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KviOption_boolPickRandomIpAddressForRoundRobinServers, m_pConsole, m_pServerDns, m_pTarget, KviWindow::output(), r, KviIrcConnectionTarget::server(), KviIrcServer::setHostName(), KviIrcServer::setIp(), KviDnsResolver::state(), Success, and terminate().
Referenced by lookupServerHostname().
void KviIrcConnectionTargetResolver::start (KviIrcConnectionTarget * t)
References asyncStartResolve(), connect(), KVI_ASSERT, m_eState, m_pStartTimer, m_pTarget, Running, and t.
Referenced by KviIrcLink::start().
Status KviIrcConnectionTargetResolver::status () [inline]
Referenced by KviIrcLink::resolverTerminated().
void KviIrcConnectionTargetResolver::terminate (Status s, int iLastError) [private]
References cleanup(), KVI_ASSERT, m_eState, m_eStatus, m_iLastError, s, terminated(), and Terminated.
Referenced by abort(), haveServerIp(), lookupProxyHostname(), lookupServerHostname(), proxyLookupTerminated(), and serverLookupTerminated().
void KviIrcConnectionTargetResolver::terminated () [signal]
Referenced by terminate().
bool KviIrcConnectionTargetResolver::validateLocalAddress (const QString & szAddress, QString & szBuffer) [private]
References KviNetUtils::getInterfaceAddress(), KviIrcServer::isIPv6(), KviNetUtils::isValidStringIp(), m_pTarget, and KviIrcConnectionTarget::server().
Referenced by haveServerIp().
Friends And Related Function Documentation
friend class KviIrcLink [friend]
Member Data Documentation
State KviIrcConnectionTargetResolver::m_eState [private]
Referenced by abort(), KviIrcConnectionTargetResolver(), start(), and terminate().
Status KviIrcConnectionTargetResolver::m_eStatus [private]
Referenced by KviIrcConnectionTargetResolver(), and terminate().
int KviIrcConnectionTargetResolver::m_iLastError [private]
Referenced by KviIrcConnectionTargetResolver(), and terminate().
KviIrcConnection* KviIrcConnectionTargetResolver::m_pConnection [private]
Referenced by KviIrcConnectionTargetResolver().
KviConsoleWindow* KviIrcConnectionTargetResolver::m_pConsole [private]
Referenced by abort(), asyncStartResolve(), haveServerIp(), KviIrcConnectionTargetResolver(), lookupProxyHostname(), lookupServerHostname(), proxyLookupTerminated(), and serverLookupTerminated().
KviDnsResolver* KviIrcConnectionTargetResolver::m_pProxyDns [private]
Referenced by cleanup(), KviIrcConnectionTargetResolver(), lookupProxyHostname(), and proxyLookupTerminated().
char* KviIrcConnectionTargetResolver::m_pReadBuffer [private]
KviDnsResolver* KviIrcConnectionTargetResolver::m_pServerDns [private]
Referenced by cleanup(), KviIrcConnectionTargetResolver(), lookupServerHostname(), and serverLookupTerminated().
QTimer* KviIrcConnectionTargetResolver::m_pStartTimer [private]
Referenced by asyncStartResolve(), cleanup(), KviIrcConnectionTargetResolver(), and start().
KviIrcConnectionTarget* KviIrcConnectionTargetResolver::m_pTarget [private]
Referenced by asyncStartResolve(), haveServerIp(), KviIrcConnectionTargetResolver(), lookupProxyHostname(), lookupServerHostname(), proxyLookupTerminated(), serverLookupTerminated(), start(), and validateLocalAddress().
unsigned int KviIrcConnectionTargetResolver::m_uReadBufferLen [private]
unsigned int KviIrcConnectionTargetResolver::m_uReadPackets [private]
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionTargetResolver.h
src/kvirc/kernel/KviIrcConnectionTargetResolver.cpp