KVIrc: KviKvsCallbackFileDialog Class Reference
KviKvsCallbackFileDialog Class Reference
#include <libkvidialog.h>
Public Member Functions
KviKvsCallbackFileDialog (const QString &szCaption, const QString &szInitialSelection, const QString &szFilter, const QString &szCode, KviKvsVariantList *pMagicParams, KviWindow *pWindow, bool modal=false)
~KviKvsCallbackFileDialog ()
Public Member Functions inherited from KviFileDialog
KviFileDialog (const QString &szDirName, const QString &szFilter=QString(), QWidget *pParent=0, const char *name=0, bool bModal=false)
Constructs the file dialog object.
~KviFileDialog ()
Destroys the file dialog object.
Public Member Functions inherited from KviTalFileDialog
KviTalFileDialog (const QString &szDirName, const QString &szFilter=QString(), QWidget *pParent=0, const char *pcName=0, bool bModal=false)
Constructs the filedialog object.
void setDirectory (const QString &szDirectory)
Sets the current directory.
void setFileMode (FileMode m)
Sets the file mode.
~KviTalFileDialog ()
Destroys the filedialog object.
Public Member Functions inherited from KviKvsCallbackObject
KviKvsCallbackObject (const QString &szCallbackSource, KviWindow *pTargetWindow, const QString &szCallbackCode, KviKvsVariantList *pMagicParams, unsigned int uFlags=0)
virtual ~KviKvsCallbackObject ()
Protected Member Functions
virtual void done (int code)
Protected Member Functions inherited from KviKvsCallbackObject
CallbackStatus execute (KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0)
Additional Inherited Members
Public Types inherited from KviTalFileDialog
enum FileMode {
AnyFile, ExistingFile, ExistingFiles, Directory,
DirectoryOnly
}
Indicate what the user may select in the file dialog.
Public Types inherited from KviKvsCallbackObject
enum CallbackFlags { OnlyIfWindowExists = 1 }
enum CallbackStatus { Success, Error, HaltEncountered, TargetWindowDead }
Static Public Member Functions inherited from KviFileDialog
static bool askForDirectoryName (QString &szBuffer, const QString &szCaption, const QString &szInitial, const QString &szFilter=QString(), bool bShowHidden=false, bool bShowNative=true, QWidget *pParent=0)
static bool askForOpenFileName (QString &szBuffer, const QString &szCaption, const QString &szInitial=QString(), const QString &szFilter=QString(), bool bShowHidden=false, bool bShowNative=true, QWidget *pParent=0)
static bool askForOpenFileNames (QStringList &szBuffer, const QString &szCaption, const QString &szInitial, const QString &szFilter=QString(), bool bShowHidden=false, bool bShowNative=true, QWidget *pParent=0)
static bool askForSaveFileName (QString &szBuffer, const QString &szCaption, const QString &szInitial=QString(), const QString &szFilter=QString(), bool bShowHidden=false, bool bConfirmOverwrite=false, bool bShowNative=true, QWidget *pParent=0)
Static Public Member Functions inherited from KviTalFileDialog
static QString getExistingDirectoryPath (const QString &szDir=QString(), const QString &szCaption=QString(), QWidget *pParent=0)
Returns an existing directory selected by the user.
Protected Attributes inherited from KviKvsCallbackObject
KviKvsVariantList * m_pMagicParams
KviKvsScript * m_pScript
KviWindow * m_pTargetConsole
KviWindow * m_pTargetWindow
unsigned int m_uFlags
Constructor & Destructor Documentation
KviKvsCallbackFileDialog::KviKvsCallbackFileDialog (const QString & szCaption, const QString & szInitialSelection, const QString & szFilter, const QString & szCode, KviKvsVariantList * pMagicParams, KviWindow * pWindow, bool modal = false)
References KviPointerList< T >::append().
KviKvsCallbackFileDialog::~KviKvsCallbackFileDialog ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void KviKvsCallbackFileDialog::done (int code) protected virtual
References a, KviKvsVariantList::append(), KviKvs::done(), KviKvsCallbackObject::execute(), and KviKvsArray::set().
The documentation for this class was generated from the following files:
src/modules/dialog/libkvidialog.h
src/modules/dialog/libkvidialog.cpp