KVIrc: KviIrcMessageCheckListItem Class Reference
KviIrcMessageCheckListItem Class Reference
#include <kvi_ircviewtools.h>
Public Member Functions
bool isOn ()
KviIrcMessageCheckListItem (QTreeWidget *par, KviIrcViewToolWidget *w, int id)
void setOn (bool b)
~KviIrcMessageCheckListItem ()
Private Attributes
int m_iId
QCheckBox * m_pCbox
KviIrcViewToolWidget * m_pToolWidget
Constructor & Destructor Documentation
KviIrcMessageCheckListItem::KviIrcMessageCheckListItem (QTreeWidget * par, KviIrcViewToolWidget * w, int id)
References g_pIconManager, KviIconManager::getSmallIcon(), KVI_OPTION_MSGTYPE, m_iId, m_pToolWidget, and KviOsInfo::type().
KviIrcMessageCheckListItem::~KviIrcMessageCheckListItem ()
Member Function Documentation
bool KviIrcMessageCheckListItem::isOn () [inline]
Referenced by KviIrcViewToolWidget::messageEnabled().
void KviIrcMessageCheckListItem::setOn (bool b) [inline]
Referenced by KviIrcViewToolWidget::filterEnableAll(), KviIrcViewToolWidget::filterEnableNone(), and KviIrcViewToolWidget::filterLoad().
Member Data Documentation
int KviIrcMessageCheckListItem::m_iId [private]
Referenced by KviIrcMessageCheckListItem().
QCheckBox* KviIrcMessageCheckListItem::m_pCbox [private]
KviIrcViewToolWidget* KviIrcMessageCheckListItem::m_pToolWidget [private]
Referenced by KviIrcMessageCheckListItem().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_ircviewtools.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_ircviewtools.cpp