KVIrc: KviKvsCallbackTextInput Class Reference
KviKvsCallbackTextInput Class Reference
#include <libkvidialog.h>
Public Member Functions
KviKvsCallbackTextInput (const QString &szCaption, const QString &szLabel, const QString &szDefaultText, const QString &szIcon, bool bMultiLine, bool bPassword, const QString &szButton0, const QString &szButton1, const QString &szButton2, const QString &szCode, KviKvsVariantList *pMagicParams, KviWindow *pWindow, bool modal=false)
~KviKvsCallbackTextInput ()
Public Member Functions inherited from KviKvsCallbackObject
KviKvsCallbackObject (const QString &szCallbackSource, KviWindow *pTargetWindow, const QString &szCallbackCode, KviKvsVariantList *pMagicParams, unsigned int uFlags=0)
virtual ~KviKvsCallbackObject ()
Protected Slots
void b0Clicked ()
void b1Clicked ()
void b2Clicked ()
virtual void done (int code)
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
virtual void showEvent (QShowEvent *e)
Protected Member Functions inherited from KviKvsCallbackObject
CallbackStatus execute (KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0)
Protected Attributes
bool m_bMultiLine
bool m_bPassword
int m_iDefaultButton
int m_iEscapeButton
QWidget * m_pEdit
Protected Attributes inherited from KviKvsCallbackObject
KviKvsVariantList * m_pMagicParams
KviKvsScript * m_pScript
KviWindow * m_pTargetConsole
KviWindow * m_pTargetWindow
unsigned int m_uFlags
Additional Inherited Members
Public Types inherited from KviKvsCallbackObject
enum CallbackFlags { OnlyIfWindowExists = 1 }
enum CallbackStatus { Success, Error, HaltEncountered, TargetWindowDead }
Constructor & Destructor Documentation
KviKvsCallbackTextInput::KviKvsCallbackTextInput (const QString & szCaption, const QString & szLabel, const QString & szDefaultText, const QString & szIcon, bool bMultiLine, bool bPassword, const QString & szButton0, const QString & szButton1, const QString & szButton2, const QString & szCode, KviKvsVariantList * pMagicParams, KviWindow * pWindow, bool modal = false)
References KviPointerList< T >::append(), b0Clicked(), b1Clicked(), b2Clicked(), connect(), KviQString::equalCIN(), g, g_pIconManager, KviIconManager::getImage(), KviIconManager::getSmallIcon(), KviIconManager::KVIrc, m_bMultiLine, m_bPassword, m_iDefaultButton, m_iEscapeButton, and m_pEdit.
KviKvsCallbackTextInput::~KviKvsCallbackTextInput ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void KviKvsCallbackTextInput::b0Clicked () protected slot
References done().
Referenced by KviKvsCallbackTextInput().
void KviKvsCallbackTextInput::b1Clicked () protected slot
References done().
Referenced by KviKvsCallbackTextInput().
void KviKvsCallbackTextInput::b2Clicked () protected slot
References done().
Referenced by KviKvsCallbackTextInput().
void KviKvsCallbackTextInput::closeEvent (QCloseEvent * e) protected virtual
References done(), and m_iEscapeButton.
void KviKvsCallbackTextInput::done (int code) protected virtual slot
References KviKvsVariantList::append(), KviKvsCallbackObject::execute(), m_bMultiLine, m_iDefaultButton, m_iEscapeButton, and m_pEdit.
Referenced by b0Clicked(), b1Clicked(), b2Clicked(), and closeEvent().
void KviKvsCallbackTextInput::showEvent (QShowEvent * e) protected virtual
References g_pApp, and KviMemory::move().
Member Data Documentation
bool KviKvsCallbackTextInput::m_bMultiLine protected
Referenced by done(), and KviKvsCallbackTextInput().
bool KviKvsCallbackTextInput::m_bPassword protected
Referenced by KviKvsCallbackTextInput().
int KviKvsCallbackTextInput::m_iDefaultButton protected
Referenced by done(), and KviKvsCallbackTextInput().
int KviKvsCallbackTextInput::m_iEscapeButton protected
Referenced by closeEvent(), done(), and KviKvsCallbackTextInput().
QWidget* KviKvsCallbackTextInput::m_pEdit protected
Referenced by done(), and KviKvsCallbackTextInput().
The documentation for this class was generated from the following files:
src/modules/dialog/libkvidialog.h
src/modules/dialog/libkvidialog.cpp