KVIrc: KviKvsTreeNodeExtendedScopeVariable Class Reference
KviKvsTreeNodeExtendedScopeVariable Class Reference
#include <KviKvsTreeNodeExtendedScopeVariable.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
KviKvsTreeNodeExtendedScopeVariable (const QChar *pLocation, const QString &szIdentifier)
~KviKvsTreeNodeExtendedScopeVariable ()
Public Member Functions inherited from KviKvsTreeNodeVariable
KviKvsTreeNodeVariable (const QChar *pLocation, const QString &szIdentifier)
~KviKvsTreeNodeVariable ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeVariable
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool isReadOnly ()
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeVariable
QString m_szIdentifier
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeExtendedScopeVariable::KviKvsTreeNodeExtendedScopeVariable (const QChar * pLocation, const QString & szIdentifier)
KviKvsTreeNodeExtendedScopeVariable::~KviKvsTreeNodeExtendedScopeVariable () default
Member Function Documentation
void KviKvsTreeNodeExtendedScopeVariable::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
void KviKvsTreeNodeExtendedScopeVariable::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
bool KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) virtual
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsVariant::copyFrom(), KviKvsRunTimeContext::error(), KviKvsRunTimeContext::extendedScopeVariables(), KviKvsHash::find(), KviKvsTreeNodeVariable::m_szIdentifier, KviKvsVariant::setNothing(), and v.
KviKvsRWEvaluationResult * KviKvsTreeNodeExtendedScopeVariable::evaluateReadWrite (KviKvsRunTimeContext * c) virtual
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsRunTimeContext::error(), KviKvsRunTimeContext::extendedScopeVariables(), KviKvsHash::get(), and KviKvsTreeNodeVariable::m_szIdentifier.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExtendedScopeVariable.h
src/kvirc/kvs/tree/KviKvsTreeNodeExtendedScopeVariable.cpp