KVIrc: KviCString Class Reference
KviCString Class Reference
#include <KviCString.h>
Public Types
enum KviFormatConstructorTag { Format, Sprintf }
Public Member Functions
void append (const KviCString &str)
void append (const QString &str)
void append (char c)
void append (const char *str)
void append (const char *str, int len)
void append (KviFormatConstructorTag dummy, const char *fmt,...)
char & at (int idx) const
int base64ToBuffer (char **buffer, bool bNullToNewlines=false)
void bufferToBase64 (const char *buffer, int len)
void bufferToHex (const char *buffer, int len)
void clear ()
bool contains (const char *str, bool caseS=true) const
bool contains (char c, bool caseS=true) const
KviCString & cut (int idx, int len)
KviCString & cutFromFirst (char c, bool bIncluded=true)
KviCString & cutFromFirst (const char *c, bool bIncluded=true)
KviCString & cutFromLast (char c, bool bIncluded=true)
KviCString & cutFromLast (const char *c, bool bIncluded=true)
KviCString & cutLeft (int len)
KviCString & cutRight (int len)
KviCString & cutToFirst (char c, bool bIncluded=true)
KviCString & cutToFirst (const char *c, bool bIncluded=true)
KviCString & cutToLast (char c, bool bIncluded=true)
KviCString & cutToLast (const char *c, bool bIncluded=true)
void ensureLastCharIs (char ch)
bool equalsCI (const KviCString &other) const
bool equalsCI (const char *other) const
bool equalsCIN (const char *other, int len) const
bool equalsCS (const KviCString &other) const
bool equalsCS (const char *other) const
bool equalsCSN (const char *other, int len) const
void extractFromString (const char *begin, const char *end)
int find (char c, int startIdx) const
int find (const char *str, int startIdx, bool caseS=true) const
int findFirstIdx (char c) const
int findFirstIdx (const char *str, bool caseS=true) const
int findLastIdx (char c) const
int findLastIdx (const char *str, bool caseS=true) const
int findRev (const char *str, int startIdx, bool caseS=true) const
bool firstCharIs (char ch) const
bool getLine (KviCString &str)
bool getToken (KviCString &str, char sep)
KviCString getToken (char sep)
bool hasData () const
bool hasNonWhiteSpaceData () const
KviCString & hexDecode (const char *pFrom)
KviCString & hexDecode ()
KviCString & hexEncodeWhiteSpace ()
KviCString & hexEncodeWithTable (const unsigned char table[256])
int hexToBuffer (char **buffer, bool bNullToNewlines=false)
KviCString & insert (int idx, const char *data)
KviCString & insert (int idx, char c)
bool isEmpty () const
bool isNum () const
bool isUnsignedNum () const
void joinFromArray (KviCString **strings, const char *sep=0, bool bLastSep=false)
KviCString ()
KviCString (const char *str)
KviCString (const char *str, int len)
KviCString (const char *bg, const char *end)
KviCString (KviFormatConstructorTag tag, const char *fmt,...)
KviCString (const KviCString &str)
KviCString (const QString &str)
KviCString (const QByteArray &str)
KviCString (char c, int fillLen=1)
KviCString (const kvi_wchar_t *unicode)
KviCString (const kvi_wchar_t *unicode, int len)
bool lastCharIs (char ch) const
KviCString left (int maxLen) const
KviCString leftToFirst (char c, bool bIncluded=false) const
KviCString leftToLast (char c, bool bIncluded=false) const
int len () const
KviCString lower () const
KviCString lowerISO88591 () const
KviCString middle (int idx, int maxLen) const
int occurences (const char *str, bool caseS=true) const
int occurences (char c, bool caseS=true) const
operator const char * () const
KviCString & operator+= (const KviCString &str)
KviCString & operator+= (const char *str)
KviCString & operator+= (char c)
KviCString & operator+= (const QString &str)
KviCString & operator= (const KviCString &str)
KviCString & operator= (const char *str)
KviCString & operator= (char c)
KviCString & operator= (const QString &str)
KviCString & operator= (const QByteArray &str)
KviCString & padRight (int iLen, const char c='\0')
void prepend (const KviCString &str)
void prepend (const char *str)
void prepend (const char *str, int len)
char * ptr () const
KviCString & replaceAll (const char c, const char *str)
KviCString & replaceAll (const char *toFind, const char *str, bool bCaseS=true)
KviCString right (int maxLen) const
KviCString & setLen (int len)
KviCString & setNum (long num)
KviCString & setNum (unsigned long num)
KviCString & setNum (int num)
KviCString & setNum (unsigned int num)
KviCString & setNum (short num)
KviCString & setNum (unsigned short num)
KviCString & setNum (char num)
KviCString & setNum (unsigned char num)
KviCString & setStr (const char *str, int len=-1)
KviCString ** splitToArray (char sep, int max, int *realCount) const
KviCString & sprintf (const char *fmt,...)
KviCString & stripLeft (char c)
KviCString & stripLeftWhiteSpace ()
KviCString & stripRight (char c)
KviCString & stripRightWhiteSpace ()
KviCString & stripSpace ()
char toChar (bool *bOk=0) const
int toInt (bool *bOk=0) const
long toLong (bool *bOk=0) const
long toLongExt (bool *bOk=0, int base=0)
long long toLongLong (bool *bOk=0) const
void toLower ()
void toLowerISO88591 ()
short toShort (bool *bOk=0) const
unsigned char toUChar (bool *bOk=0) const
unsigned int toUInt (bool *bOk=0) const
unsigned long toULong (bool *bOk=0) const
unsigned long long toULongLong (bool *bOk=0) const
void toUpper ()
void toUpperISO88591 ()
unsigned short toUShort (bool *bOk=0) const
KviCString & transliterate (const char *szToFind, const char *szReplacement)
KviCString & trim ()
KviCString upper () const
KviCString upperISO88591 () const
KviCString & vsprintf (const char *fmt, kvi_va_list list)
~KviCString ()
Static Public Member Functions
static KviCString & emptyString ()
static bool ext_contains (register const char *data, const char *item, bool caseS=true)
static void freeArray (KviCString **strings)
static void freeBuffer (char *buffer)
Public Attributes
int m_len
char * m_ptr
Member Enumeration Documentation
enum KviCString::KviFormatConstructorTag
Enumerator:
Format
Sprintf
Constructor & Destructor Documentation
KviCString::KviCString ()
References KviMemory::allocate(), m_len, and m_ptr.
Referenced by leftToFirst(), leftToLast(), and splitToArray().
KviCString::KviCString (const char * str)
References KviMemory::allocate(), KviMemory::copy(), m_len, and m_ptr.
KviCString::KviCString (const char * str, int len)
References KviMemory::allocate(), KviMemory::copy(), KVI_ASSERT, len(), m_len, and m_ptr.
KviCString::KviCString (const char * bg, const char * end)
References KviMemory::allocate(), KviMemory::copy(), KVI_ASSERT, m_len, and m_ptr.
KviCString::KviCString (KviFormatConstructorTag tag, const char * fmt, ...)
References KviMemory::allocate(), kvi_va_end, kvi_va_list, kvi_va_start, kvi_vsnprintf(), m_len, m_ptr, and KviMemory::reallocate().
KviCString::KviCString (const KviCString & str)
References KviMemory::allocate(), KviMemory::copy(), KVI_ASSERT, m_len, and m_ptr.
KviCString::KviCString (const QString & str)
References KviMemory::allocate(), KviMemory::copy(), m_len, and m_ptr.
KviCString::KviCString (const QByteArray & str)
References KviMemory::allocate(), KviMemory::copy(), m_len, and m_ptr.
KviCString::KviCString (char c, int fillLen = 1)
References KviMemory::allocate(), c, KVI_ASSERT, m_len, m_ptr, and p.
KviCString::KviCString (const kvi_wchar_t * unicode)
References KviMemory::allocate(), kvi_wstrlen(), m_len, m_ptr, and p.
KviCString::KviCString (const kvi_wchar_t * unicode, int len)
References KviMemory::allocate(), len(), m_len, m_ptr, and p.
KviCString::~KviCString ()
References KviMemory::free(), and m_ptr.
Member Function Documentation
void KviCString::append (const KviCString & str)
References KviMemory::copy(), KVI_ASSERT, m_len, m_ptr, and KviMemory::reallocate().
Referenced by KviCommandFormatter::blockFromBuffer(), DccChatWindow::connectionInProgress(), KviIrcServerParser::decodeCtcpEscape(), KviIrcServerParser::encodeCtcpParameter(), LinksWindow::endOfLinks(), KviIrcServerParser::extractCtcpParameter(), IrcServerDetailsWidget::fillData(), joinFromArray(), KviDebugContext::KviDebugContext(), options_kvs_module_print_pages(), KviIrcUrl::parse(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumericStats(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), replaceAll(), KviIdentDaemon::run(), KviHttpRequest::slotSocketConnected(), KviIrcContextDisplay::tipRequest(), KviDebugContext::trace(), KviUserListView::updateUsersLabel(), KviConfigurationFile::writeEntry(), and KviDebugContext::~KviDebugContext().
void KviCString::append (const QString & str)
References KviMemory::copy(), m_len, m_ptr, and KviMemory::reallocate().
void KviCString::append (char c)
References m_len, m_ptr, and KviMemory::reallocate().
void KviCString::append (const char * str)
References KviMemory::copy(), len(), m_len, m_ptr, and KviMemory::reallocate().
void KviCString::append (const char * str, int len)
References KviMemory::copy(), KVI_ASSERT, len(), m_len, m_ptr, and KviMemory::reallocate().
void KviCString::append (KviFormatConstructorTag dummy, const char * fmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start, kvi_vsnprintf(), m_len, m_ptr, and KviMemory::reallocate().
char& KviCString::at (int idx) const inline
Referenced by KviIrcMessage::paramString().
int KviCString::base64ToBuffer (char ** buffer, bool bNullToNewlines = false)
References KviMemory::allocate(), KviMemory::free(), get_base64_idx(), len(), m_len, m_ptr, and KviMemory::reallocate().
void KviCString::bufferToBase64 (const char * buffer, int len)
References base64_chars, m_len, m_ptr, and KviMemory::reallocate().
Referenced by KviKvsCoreFunctions::KVSCF(), KviSASL::plainMethod(), and KviIrcSocket::proxyLoginHttp().
void KviCString::bufferToHex (const char * buffer, int len)
References hexdigits, KVI_ASSERT, m_len, m_ptr, and KviMemory::reallocate().
Referenced by KviKvsCoreFunctions::KVSCF().
void KviCString::clear ()
References m_len, m_ptr, and KviMemory::reallocate().
Referenced by setStr().
bool KviCString::contains (const char * str, bool caseS = true) const
References c, KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_ptr, and p.
Referenced by dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), KviStringConversion::fromString(), IrcServerDetailsWidget::IrcServerDetailsWidget(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), KviIrcServerParser::parseCtcpReplyPing(), and KviIrcServerParser::parseNumeric004().
bool KviCString::contains (char c, bool caseS = true) const
References m_ptr, and p.
KviCString & KviCString::cut (int idx, int len)
References KVI_ASSERT, len(), m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
KviCString & KviCString::cutFromFirst (char c, bool bIncluded = true)
References cutRight(), findFirstIdx(), and m_len.
Referenced by KviLocale::codecForName(), KviLocale::findCatalogue(), KviLocale::KviLocale(), KviMessageCatalogue::load(), TipWindow::nextTip(), KviIrcServerParser::parseCtcpReplyPing(), TipWindow::prevTip(), KviHttpRequest::processData(), and KviIrcSocket::proxyHandleHttpFinalReply().
KviCString & KviCString::cutFromFirst (const char * c, bool bIncluded = true)
References cutRight(), findFirstIdx(), len(), and m_len.
KviCString & KviCString::cutFromLast (char c, bool bIncluded = true)
References cutRight(), findLastIdx(), and m_len.
KviCString & KviCString::cutFromLast (const char * c, bool bIncluded = true)
References cutRight(), findLastIdx(), len(), and m_len.
KviCString & KviCString::cutLeft (int len)
References KVI_ASSERT, len(), m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
Referenced by KviCommandFormatter::bufferFromBlock(), cutToFirst(), cutToLast(), DccChatWindow::event(), DccVideoWindow::event(), getLine(), getToken(), KviIsOnNotifyListManager::handleUserhost(), KviMessageCatalogue::load(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviHttpRequest::processHeader(), replaceAll(), and KviIdentDaemon::run().
KviCString & KviCString::cutRight (int len)
References KVI_ASSERT, len(), m_len, m_ptr, and KviMemory::reallocate().
Referenced by KviCommandFormatter::bufferFromBlock(), cutFromFirst(), cutFromLast(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), DccChatWindow::event(), DccVideoWindow::event(), DccChatThread::handleIncomingData(), DccVideoThread::handleIncomingData(), KviIsOnNotifyListManager::handleUserhost(), KviApplication::ipcMessage(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), and KviDebugContext::~KviDebugContext().
KviCString & KviCString::cutToFirst (char c, bool bIncluded = true)
References cutLeft(), and findFirstIdx().
Referenced by LogFile::LogFile(), KviIrcServerParser::parseCtcpReplyPing(), KviHttpRequest::processHeader(), and system_kvs_fnc_dbus().
KviCString & KviCString::cutToFirst (const char * c, bool bIncluded = true)
References cutLeft(), findFirstIdx(), and len().
KviCString & KviCString::cutToLast (char c, bool bIncluded = true)
References cutLeft(), and findLastIdx().
Referenced by dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), and KviMediaManager::findMediaType().
KviCString & KviCString::cutToLast (const char * c, bool bIncluded = true)
References cutLeft(), findLastIdx(), and len().
KviCString & KviCString::emptyString () static
References g_szApplicationWideEmptyString.
Referenced by kvi_hash_key_default(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), and KviIrcMessage::safeTrailingString().
void KviCString::ensureLastCharIs (char ch) inline
Referenced by KviCommandFormatter::blockFromBuffer(), and KviMediaManager::findMediaType().
bool KviCString::equalsCI (const KviCString & other) const inline
References kvi_strEqualCI(), m_len, and m_ptr.
Referenced by KviModuleExtensionManager::allocateExtension(), and KviHttpRequest::processHeader().
bool KviCString::equalsCI (const char * other) const inline
References kvi_strEqualCI().
bool KviCString::equalsCIN (const char * other, int len) const inline
References kvi_strEqualCIN().
bool KviCString::equalsCS (const KviCString & other) const inline
References kvi_strEqualCS(), m_len, and m_ptr.
bool KviCString::equalsCS (const char * other) const inline
References kvi_strEqualCS().
bool KviCString::equalsCSN (const char * other, int len) const inline
References kvi_strEqualCSN().
bool KviCString::ext_contains (register const char * data, const char * item, bool caseS = true) static
References c, kvi_strEqualCIN(), kvi_strEqualCSN(), and len().
void KviCString::extractFromString (const char * begin, const char * end)
References KviMemory::copy(), KVI_ASSERT, m_len, m_ptr, and KviMemory::reallocate().
Referenced by KviIrcMessage::KviIrcMessage().
int KviCString::find (char c, int startIdx) const
References m_len, m_ptr, and p.
int KviCString::find (const char * str, int startIdx, bool caseS = true) const
References kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_len, m_ptr, and p.
int KviCString::findFirstIdx (char c) const
References m_ptr, and p.
Referenced by KviLocale::codecForName(), cutFromFirst(), cutToFirst(), KviLocale::findCatalogue(), KviIsOnNotifyListManager::handleUserhost(), KviApplication::ipcMessage(), kvi_mayBeSpam(), leftToFirst(), KviMessageCatalogue::load(), KviHttpRequest::processHeader(), KviIrcSocket::proxyHandleHttpFinalReply(), replaceAll(), and KviIdentDaemon::run().
int KviCString::findFirstIdx (const char * str, bool caseS = true) const
References KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_ptr, and p.
int KviCString::findLastIdx (char c) const
References m_len, m_ptr, and p.
Referenced by cutFromLast(), cutToLast(), leftToLast(), and DccBroker::renameDccSendFile().
int KviCString::findLastIdx (const char * str, bool caseS = true) const
References KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_len, m_ptr, and p.
int KviCString::findRev (const char * str, int startIdx, bool caseS = true) const
References kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_len, m_ptr, and p.
bool KviCString::firstCharIs (char ch) const inline
Referenced by DccChatWindow::event(), DccVideoWindow::event(), and KviIsOnNotifyListManager::handleUserhost().
void KviCString::freeArray (KviCString ** strings) static
References KviMemory::free().
Referenced by KviCommandFormatter::indent(), and KviCommandFormatter::unindent().
void KviCString::freeBuffer (char * buffer) static
References KviMemory::free().
Referenced by KviKvsCoreFunctions::KVSCF().
bool KviCString::getLine (KviCString & str)
References KviMemory::copy(), cutLeft(), KVI_ASSERT, m_len, m_ptr, p, and KviMemory::reallocate().
bool KviCString::getToken (KviCString & str, char sep)
References KviMemory::copy(), cutLeft(), KVI_ASSERT, m_len, m_ptr, p, and KviMemory::reallocate().
Referenced by KviStringConversion::fromString(), KviIrcServerParser::parseNumericWhoReply(), and KviConfigurationFile::readColorEntry().
KviCString KviCString::getToken (char sep)
References cutLeft(), m_ptr, and p.
bool KviCString::hasData () const inline
Referenced by DccChatWindow::connectionInProgress(), dccModuleParseDccChat(), dccModuleParseDccSend(), KviIrcMessage::decodeAndSplitPrefix(), KviIdentSentinel::event(), KviIsOnNotifyListManager::handleIsOn(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviCommandFormatter::hasLeadingChars(), LinksWindow::hostPopupClicked(), DccDescriptor::isZeroPortRequest(), KviInputEditor::keyReleaseEvent(), KviLocale::KviLocale(), KviMessageCatalogue::load(), RegistrationWizard::notifyNickChanged(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumericStats(), KviIrcServerParser::parseNumericTopicWhoTime(), KviHttpRequest::processHeader(), KviIrcSocket::proxyLoginV4(), reguser_kvs_fnc_mask(), KviIdentDaemon::run(), KviIrcMessage::safePrefix(), and KviConfigurationFile::writeEntry().
bool KviCString::hasNonWhiteSpaceData () const
References m_ptr.
KviCString & KviCString::hexDecode (const char * pFrom)
References KviMemory::free(), get_decimal_from_hex_digit_char(), len(), m_len, m_ptr, KviMemory::move(), n, and KviMemory::reallocate().
Referenced by KviConfigurationFile::load(), and LogFile::LogFile().
KviCString& KviCString::hexDecode () inline
References hexDecode().
Referenced by hexDecode().
KviCString & KviCString::hexEncodeWhiteSpace ()
References hexEncodeWithTable().
Referenced by KviConfigurationFile::save().
KviCString & KviCString::hexEncodeWithTable (const unsigned char table[256])
References KviMemory::free(), hexdigits, len(), m_len, m_ptr, KviMemory::move(), n, and KviMemory::reallocate().
Referenced by hexEncodeWhiteSpace(), and KviConfigurationFile::save().
int KviCString::hexToBuffer (char ** buffer, bool bNullToNewlines = false)
References KviMemory::allocate(), KviMemory::free(), get_decimal_from_hex_digit_char(), len(), m_len, m_ptr, and ptr().
KviCString & KviCString::insert (int idx, const char * data)
References KviMemory::copy(), KVI_ASSERT, len(), m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
KviCString & KviCString::insert (int idx, char c)
References m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
bool KviCString::isEmpty () const inline
Referenced by OptionsWidget_servers::connectCurrentClicked(), RegisteredUserEntryDialog::editAllPropertiesClicked(), KviStringConversion::fromString(), KviIdentDaemon::KviIdentDaemon(), KviLocale::KviLocale(), KviConfigurationFile::load(), RegistrationWizard::maskChanged(), RegisteredUserMaskDialog::okClicked(), KviIrcServerParser::parseCtcpRequestClientinfo(), KviIrcServerParser::parseCtcpRequestFinger(), KviConfigurationFile::readColorEntry(), ListWindow::requestList(), OptionsWidget_mediaTypes::saveLastItem(), OptionsWidget_proxy::saveLastItem(), LinksWindow::showHostPopup(), and system_kvs_fnc_dbus().
bool KviCString::isNum () const
References m_ptr, and p.
bool KviCString::isUnsignedNum () const
References m_ptr, and p.
Referenced by dcc_module_normalize_target_data(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), KviIrcServerParser::parseNumericCreationTime(), KviConfigurationFile::readColorEntry(), and reguser_kvs_fnc_mask().
void KviCString::joinFromArray (KviCString ** strings, const char * sep = 0, bool bLastSep = false)
References append(), and setLen().
Referenced by KviCommandFormatter::indent(), and KviCommandFormatter::unindent().
bool KviCString::lastCharIs (char ch) const inline
Referenced by KviCommandFormatter::bufferFromBlock(), DccChatWindow::event(), DccVideoWindow::event(), DccChatThread::handleIncomingData(), DccVideoThread::handleIncomingData(), KviIsOnNotifyListManager::handleUserhost(), KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
KviCString KviCString::left (int maxLen) const
References m_len, and m_ptr.
Referenced by KviIsOnNotifyListManager::handleUserhost(), KviHttpRequest::processHeader(), DccBroker::renameDccSendFile(), replaceAll(), KviIdentDaemon::run(), stripSpace(), and trim().
KviCString KviCString::leftToFirst (char c, bool bIncluded = false) const
References findFirstIdx(), KviCString(), and m_ptr.
Referenced by system_kvs_fnc_dbus().
KviCString KviCString::leftToLast (char c, bool bIncluded = false) const
References findLastIdx(), KviCString(), and m_ptr.
int KviCString::len () const inline
Referenced by append(), base64ToBuffer(), contains(), cut(), cutFromFirst(), cutFromLast(), cutLeft(), cutRight(), cutToFirst(), cutToLast(), UglyBase64::decode(), ext_contains(), find(), findFirstIdx(), findLastIdx(), findRev(), hexDecode(), hexEncodeWithTable(), hexToBuffer(), insert(), KviMediaManager::insertMediaType(), KviApplication::ipcMessage(), KviCString(), KviIpcSentinel::KviIpcSentinel(), KviIrcMessage::KviIrcMessage(), KviLocale::KviLocale(), KviConfigurationFile::load(), KviMessageCatalogue::load(), occurences(), DccChatWindow::ownAction(), DccVideoWindow::ownAction(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseNumeric005(), prepend(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), DccBroker::renameDccSendFile(), replaceAll(), KviIdentDaemon::run(), KviConfigurationFile::save(), KviFile::save(), setStr(), KviQString::vsprintf(), and KviDebugContext::~KviDebugContext().
KviCString KviCString::lower () const
References toLower().
KviCString KviCString::lowerISO88591 () const
References toLowerISO88591().
KviCString KviCString::middle (int idx, int maxLen) const
References KVI_ASSERT, m_len, and m_ptr.
int KviCString::occurences (const char * str, bool caseS = true) const
References c, KVI_ASSERT, kvi_strEqualCIN(), kvi_strEqualCSN(), len(), m_ptr, and p.
Referenced by KviMediaManager::insertMediaType(), and KviIrcServerParser::parseNumeric004().
int KviCString::occurences (char c, bool caseS = true) const
References m_ptr, and p.
KviCString::operator const char * () const inline
KviCString& KviCString::operator+= (const KviCString & str) inline
KviCString& KviCString::operator+= (const char * str) inline
KviCString& KviCString::operator+= (char c) inline
KviCString& KviCString::operator+= (const QString & str) inline
KviCString & KviCString::operator= (const KviCString & str)
References KviMemory::copy(), KVI_ASSERT, m_len, m_ptr, and KviMemory::reallocate().
KviCString & KviCString::operator= (const char * str)
References m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
KviCString & KviCString::operator= (char c)
References c, m_len, m_ptr, and KviMemory::reallocate().
KviCString & KviCString::operator= (const QString & str)
References KviMemory::copy(), m_len, m_ptr, and KviMemory::reallocate().
KviCString & KviCString::operator= (const QByteArray & str)
References KviMemory::copy(), m_len, m_ptr, and KviMemory::reallocate().
KviCString & KviCString::padRight (int iLen, const char c = '\0')
References KVI_ASSERT, m_len, m_ptr, KviMemory::reallocate(), and KviMemory::set().
void KviCString::prepend (const KviCString & str)
References KviMemory::copy(), KVI_ASSERT, m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
Referenced by KviCommandFormatter::blockFromBuffer(), DccFileTransfer::connectionInProgress(), dcc_kvs_cmd_get(), DccFileTransfer::DccFileTransfer(), dccModuleParseDccGet(), dccModuleParseDccRecv(), and KviMediaManager::findMediaType().
void KviCString::prepend (const char * str)
References KviMemory::copy(), len(), m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
void KviCString::prepend (const char * str, int len)
References KviMemory::copy(), KVI_ASSERT, len(), m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
char* KviCString::ptr () const inline
Referenced by KviModuleExtensionManager::allocateExtension(), KviModuleExtensionManager::allocateExtensionGetDescriptorList(), KviCommandFormatter::bufferFromBlock(), KviLocale::codecForName(), OptionsWidget_identityAdvanced::commit(), DccVoiceWindow::connected(), DccVideoWindow::connected(), DccChatWindow::connectionInProgress(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), MediaTypeTreeWidgetItem::copyData(), OptionsWidget_proxy::currentItemChanged(), dcc_kvs_cmd_get(), dcc_module_normalize_target_data(), dcc_module_request_error(), dccModuleCtcpDccParseRoutine(), dccModuleParseDccAccept(), dccModuleParseDccCanvas(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccResume(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), dccModuleParseDccVoice(), UglyBase64::decode(), KviIrcMessage::decodeAndSplitPrefix(), DccFileTransfer::doResume(), DccMarshal::doSSLHandshake(), UglyBase64::encode(), LinksWindow::endOfLinks(), KviIdentSentinel::event(), DccChatWindow::event(), DccVoiceWindow::event(), DccVideoWindow::event(), DccFileTransfer::event(), DccBroker::executeChat(), IrcServerDetailsWidget::fillData(), KviLocale::findCatalogue(), KviModuleExtensionManager::findExtensionDescriptor(), KviMediaManager::findMediaType(), KviStringConversion::fromString(), KviParameterList::getBool(), KviModuleExtensionManager::getExtensionList(), LinksWindow::getItemByHost(), KviApplication::getLocalKvircDirectory(), KviIrcConnection::handleAuthenticate(), KviIsOnNotifyListManager::handleIsOn(), KviStupidNotifyListManager::handleIsOn(), DccBroker::handleResumeRequest(), KviIsOnNotifyListManager::handleUserhost(), hexToBuffer(), LinksWindow::hostPopupClicked(), KviIconWidget::init(), LinksWindow::insertLink(), KviApplication::ipcMessage(), kvi_compare(), kvi_hash_hash(), kvi_hash_key_equal(), KviDebugContext::KviDebugContext(), KviIpcSentinel::KviIpcSentinel(), KviIrcMessage::KviIrcMessage(), KviLocale::KviLocale(), KviSockaddr::KviSockaddr(), KviKvsCoreFunctions::KVSCF(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviProxyDataBase::load(), KviMediaManager::load(), KviConfigurationFile::load(), KviMessageCatalogue::load(), KviInputHistory::load(), KviStatusBar::load(), KviFile::load(), KviStatusBarClock::loadState(), KviStatusBarConnectionTimer::loadState(), KviStatusBarAwayIndicator::loadState(), KviStatusBarUpdateIndicator::loadState(), LogFile::LogFile(), KviIrcConnection::loginComplete(), main(), RegistrationWizard::maskChanged(), DccVoiceCodec::name(), DccVideoCodec::name(), KviMenuBar::newConnectionToServer(), TipWindow::nextTip(), objects_kvs_fnc_listObjects(), RegisteredUserMaskDialog::okClicked(), DccVoiceThread::openSoundcard(), options_kvs_module_print_pages(), DccChatWindow::ownAction(), DccVideoWindow::ownAction(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviTopicWidget::paintColoredText(), KviColorWindow::paintEvent(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCtcpReplyLagcheck(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestClientinfo(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseCtcpRequestFinger(), KviIrcServerParser::parseCtcpRequestPage(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericWhoReply(), KviConnectToServerAction::popupActivated(), TipWindow::prevTip(), KviHttpRequest::processData(), KviHttpRequest::processHeader(), KviIrcSocket::proxyHandleHttpFinalReply(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), KviConfigurationFile::readKviCStringEntry(), KviModuleExtensionManager::registerExtension(), DccBroker::renameDccSendFile(), ListWindow::requestList(), NotifierWindow::returnPressed(), KviIdentDaemon::run(), DccSendThread::run(), DccRecvThread::run(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviIrcMessage::safeTrailing(), KviProxyDataBase::save(), KviMediaManager::save(), KviConfigurationFile::save(), KviInputHistory::save(), KviFile::save(), OptionsWidget_messageColors::save(), KviStatusBar::save(), OptionsWidget_proxy::saveLastItem(), KviStatusBarClock::saveState(), KviStatusBarConnectionTimer::saveState(), KviStatusBarAwayIndicator::saveState(), KviStatusBarUpdateIndicator::saveState(), KviConfigurationFile::setFontProperties(), OptionsWidget_mediaTypes::setLineEdits(), LinksWindow::showHostPopup(), KviFile::skipFirst(), KviHttpRequest::slotSocketConnected(), splitToArray(), DccFileTransfer::startConnection(), system_kvs_fnc_dbus(), KviLagMeter::timerEvent(), KviIrcConnectionRequestQueue::timerSlot(), KviIrcContextDisplay::tipRequest(), DccFileTransfer::tipText(), KviDebugContext::trace(), KviIrcMessage::trailing(), KviMessageCatalogue::translate(), KviMessageCatalogue::translateToQString(), DccVoiceWindow::updateInfo(), KviChannelWindow::updateModeLabel(), KviUserListView::updateUsersLabel(), KviQString::vsprintf(), KviConfigurationFile::writeEntry(), DccDescriptor::zeroPortRequestTag(), and KviDebugContext::~KviDebugContext().
KviCString & KviCString::replaceAll (const char c, const char * str)
References append(), KviMemory::copy(), cutLeft(), findFirstIdx(), left(), m_len, m_ptr, and KviMemory::reallocate().
Referenced by KviLocale::codecForName().
KviCString & KviCString::replaceAll (const char * toFind, const char * str, bool bCaseS = true)
References append(), KviMemory::copy(), cutLeft(), findFirstIdx(), left(), len(), m_len, m_ptr, and KviMemory::reallocate().
KviCString KviCString::right (int maxLen) const
References m_len, and m_ptr.
Referenced by DccBroker::renameDccSendFile(), stripRight(), stripRightWhiteSpace(), stripSpace(), and trim().
KviCString & KviCString::setLen (int len)
References KVI_ASSERT, m_len, m_ptr, and KviMemory::reallocate().
Referenced by UglyBase64::decode(), UglyBase64::encode(), joinFromArray(), and KviFile::load().
KviCString & KviCString::setNum (long num)
References m_len, m_ptr, p, and KviMemory::reallocate().
Referenced by DccChatWindow::connectionInProgress(), and DccBroker::renameDccSendFile().
KviCString & KviCString::setNum (unsigned long num)
References m_len, m_ptr, p, and KviMemory::reallocate().
KviCString& KviCString::setNum (int num) inline
References setNum().
Referenced by setNum().
KviCString& KviCString::setNum (unsigned int num) inline
References setNum().
Referenced by setNum().
KviCString& KviCString::setNum (short num) inline
References setNum().
Referenced by setNum().
KviCString& KviCString::setNum (unsigned short num) inline
References setNum().
Referenced by setNum().
KviCString& KviCString::setNum (char num) inline
References setNum().
Referenced by setNum().
KviCString& KviCString::setNum (unsigned char num) inline
References setNum().
Referenced by setNum().
KviCString & KviCString::setStr (const char * str, int len = -1)
References clear(), len(), m_len, m_ptr, KviMemory::move(), and KviMemory::reallocate().
KviCString ** KviCString::splitToArray (char sep, int max, int * realCount) const
References KviMemory::allocate(), KviCString(), m_ptr, ptr(), and KviMemory::reallocate().
Referenced by KviCommandFormatter::indent(), and KviCommandFormatter::unindent().
KviCString & KviCString::sprintf (const char * fmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start, kvi_vsnprintf(), m_len, m_ptr, and KviMemory::reallocate().
Referenced by dccModuleParseDccSend(), KviProxyDataBase::load(), KviMediaManager::load(), KviInputHistory::load(), TipWindow::nextTip(), TipWindow::prevTip(), KviProxyDataBase::save(), KviMediaManager::save(), KviInputHistory::save(), OptionsWidget_messageColors::save(), KviIrcConnectionRequestQueue::timerSlot(), DccVoiceWindow::updateInfo(), and KviUserListView::updateUsersLabel().
KviCString & KviCString::stripLeft (char c)
References KVI_ASSERT, m_len, m_ptr, KviMemory::move(), p, and KviMemory::reallocate().
KviCString & KviCString::stripLeftWhiteSpace ()
References m_len, m_ptr, KviMemory::move(), p, and KviMemory::reallocate().
Referenced by DccChatWindow::event(), DccVideoWindow::event(), KviConfigurationFile::readColorEntry(), and KviConfigurationFile::readFontEntry().
KviCString & KviCString::stripRight (char c)
References m_len, m_ptr, KviMemory::reallocate(), and right().
Referenced by KviHttpRequest::emitLines().
KviCString & KviCString::stripRightWhiteSpace ()
References m_len, m_ptr, KviMemory::reallocate(), and right().
Referenced by KviCommandFormatter::blockFromBuffer(), and KviConfigurationFile::load().
KviCString & KviCString::stripSpace ()
References left(), m_len, m_ptr, KviMemory::move(), KviMemory::reallocate(), and right().
char KviCString::toChar (bool * bOk = 0) const inline
int KviCString::toInt (bool * bOk = 0) const inline
Referenced by dccModuleParseDccVoice(), KviIconWidget::eventFilter(), KviStringConversion::fromString(), KviParameterList::getInt(), KviParameterList::getPoint(), KviParameterList::getRect(), KviParameterList::getSize(), KviIrcServerParser::parseNumericWhoReply(), LinksWindow::processData(), KviConfigurationFile::readColorEntry(), reguser_kvs_fnc_mask(), and system_kvs_fnc_dbus().
long KviCString::toLong (bool * bOk = 0) const
References m_ptr, and p.
long KviCString::toLongExt (bool * bOk = 0, int base = 0)
References m_len, and m_ptr.
long long KviCString::toLongLong (bool * bOk = 0) const
References m_ptr, and p.
void KviCString::toLower ()
References m_ptr, and p.
Referenced by DccBroker::executeChat(), KviLocale::findCatalogue(), KviLocale::KviLocale(), and lower().
void KviCString::toLowerISO88591 ()
References iso88591_toLower_map, m_ptr, and p.
Referenced by lowerISO88591().
short KviCString::toShort (bool * bOk = 0) const inline
unsigned char KviCString::toUChar (bool * bOk = 0) const inline
unsigned int KviCString::toUInt (bool * bOk = 0) const inline
Referenced by KviUIntSelector::commit(), dccModuleParseDccGet(), dccModuleParseDccRecv(), getDateTimeStringFromCharTimeT(), KviParameterList::getUInt(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericWhoisIdle(), KviHttpRequest::processHeader(), OptionsWidget_proxy::saveLastItem(), and system_kvs_fnc_dbus().
unsigned long KviCString::toULong (bool * bOk = 0) const
References m_ptr, and p.
Referenced by dcc_module_normalize_target_data().
unsigned long long KviCString::toULongLong (bool * bOk = 0) const
References m_ptr, and p.
Referenced by dccModuleParseDccResume().
void KviCString::toUpper ()
References m_ptr, and p.
Referenced by dccModuleCtcpDccParseRoutine(), KviIrcMessage::KviIrcMessage(), and upper().
void KviCString::toUpperISO88591 ()
References iso88591_toUpper_map, m_ptr, and p.
Referenced by KviIrcServerParser::parseCtcpRequestClientinfo(), and upperISO88591().
unsigned short KviCString::toUShort (bool * bOk = 0) const inline
Referenced by KviInputEditor::keyReleaseEvent().
KviCString & KviCString::transliterate (const char * szToFind, const char * szReplacement)
References m_ptr, and p.
KviCString & KviCString::trim ()
References left(), m_len, m_ptr, KviMemory::move(), KviMemory::reallocate(), and right().
Referenced by KviCommandFormatter::bufferFromBlock(), KviCommandFormatter::hasLeadingChars(), KviLocale::KviLocale(), KviMessageCatalogue::load(), KviIrcServerParser::parseCtcpRequestClientinfo(), KviHttpRequest::processHeader(), KviIrcSocket::proxyHandleHttpFinalReply(), and KviIdentDaemon::run().
KviCString KviCString::upper () const
References toUpper().
KviCString KviCString::upperISO88591 () const
References toUpperISO88591().
KviCString & KviCString::vsprintf (const char * fmt, kvi_va_list list)
References kvi_va_copy, kvi_va_list, kvi_vsnprintf(), m_len, m_ptr, KviMemory::reallocate(), and KviTheme::save().
Referenced by KviDebugContext::KviDebugContext(), and KviDebugContext::trace().
Member Data Documentation
int KviCString::m_len
Referenced by append(), base64ToBuffer(), bufferToBase64(), bufferToHex(), clear(), cut(), cutFromFirst(), cutFromLast(), cutLeft(), cutRight(), equalsCI(), equalsCS(), extractFromString(), find(), findLastIdx(), findRev(), getLine(), getToken(), hexDecode(), hexEncodeWithTable(), hexToBuffer(), insert(), kvi_extractToken(), kvi_extractUpTo(), KviCString(), left(), middle(), operator=(), operator==(), padRight(), prepend(), replaceAll(), right(), setLen(), setNum(), setStr(), sprintf(), stripLeft(), stripLeftWhiteSpace(), stripRight(), stripRightWhiteSpace(), stripSpace(), toLongExt(), trim(), and vsprintf().
char* KviCString::m_ptr
Referenced by append(), base64ToBuffer(), bufferToBase64(), bufferToHex(), clear(), contains(), cut(), cutLeft(), cutRight(), equalsCI(), equalsCS(), extractFromString(), find(), findFirstIdx(), findLastIdx(), findRev(), getLine(), getToken(), hasNonWhiteSpaceData(), hexDecode(), hexEncodeWithTable(), hexToBuffer(), insert(), isNum(), isUnsignedNum(), kvi_extractToken(), kvi_extractUpTo(), KviCString(), left(), leftToFirst(), leftToLast(), middle(), occurences(), operator!=(), operator=(), operator==(), padRight(), prepend(), replaceAll(), right(), setLen(), setNum(), setStr(), splitToArray(), sprintf(), stripLeft(), stripLeftWhiteSpace(), stripRight(), stripRightWhiteSpace(), stripSpace(), toLong(), toLongExt(), toLongLong(), toLower(), toLowerISO88591(), toULong(), toULongLong(), toUpper(), toUpperISO88591(), transliterate(), trim(), vsprintf(), and ~KviCString().
The documentation for this class was generated from the following files:
src/kvilib/core/KviCString.h
src/kvilib/core/KviCString.cpp