KVIrc: LinksWindow Class Reference
LinksWindow Class Reference
#include <LinksWindow.h>
Public Member Functions
virtual void control (int msg)
virtual void die ()
LinksWindow (KviConsoleWindow *lpConsole)
virtual void processData (KviIrcMessage *msg)
virtual QSize sizeHint () const
~LinksWindow ()
Public Member Functions inherited from KviWindow
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0, const QDateTime &datetime=QDateTime())
bool isChannel () const
bool isConsole () const
bool isDocked ()
bool isQuery () const
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, QString szFmt,...)
void output (int iMsgType, const QDateTime &datetime, const char *pcFormat,...)
void output (int iMsgType, const QDateTime &datetime, const kvi_wchar_t *pwFormat,...)
void output (int iMsgType, const QDateTime &datetime, QString szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual KviWindow * outputProxy ()
virtual void ownAction (const QString &)
virtual void ownMessage (const QString &, bool=true)
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
void setWindowTitle (QString &szTitle)
KviTalSplitter * splitter ()
Returns the splitter of this window.
virtual const QString & target ()
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Public Member Functions inherited from KviExternalServerDataParser
KviExternalServerDataParser ()
virtual ~KviExternalServerDataParser ()
Protected Slots
void connectionStateChange ()
void hostPopupClicked (QAction *pAction)
void requestLinks ()
void showHostPopup (QTreeWidgetItem *i, const QPoint &p)
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual void applyOptions ()
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &buffer)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
virtual void closeEvent (QCloseEvent *pEvent)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void inputMethodEvent (QInputMethodEvent *e)
virtual void loadProperties (KviConfigurationFile *pCfg)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual void preprocessMessage (QString &szMessage)
virtual void saveProperties (KviConfigurationFile *pCfg)
void setType (Type eType)
virtual void triggerCreationEvents ()
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
QMenu * m_pHostPopup
KviThemedLabel * m_pInfoLabel
KviPointerList< KviLink > * m_pLinkList
LinksListView * m_pListView
QToolButton * m_pRequestButton
QSplitter * m_pTopSplitter
QSplitter * m_pVertSplitter
QString m_szRootServer
Protected Attributes inherited from KviWindow
bool m_bIsDocked
bool m_bProcessingInputEvent
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Private Member Functions
void endOfLinks ()
QTreeWidgetItem * getItemByHost (const char *host, QTreeWidgetItem *par)
QTreeWidgetItem * insertLink (KviLink *l)
void reset ()
Additional Inherited Members
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void reloadImages ()
void savePropertiesAsDefault ()
void undock ()
Signals inherited from KviWindow
void windowNameChanged ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Constructor & Destructor Documentation
LinksWindow::LinksWindow (KviConsoleWindow * lpConsole)
References __tr2qs, KviPointerList< T >::append(), connect(), connectionStateChange(), KviConsoleWindow::context(), g_pIconManager, KviIconManager::getSmallIcon(), hostPopupClicked(), KviTalSplitter, l, KviWindow::m_pConsole, m_pHostPopup, m_pInfoLabel, KviWindow::m_pIrcView, m_pLinkList, m_pListView, m_pRequestButton, KviWindow::m_pSplitter, m_pTopSplitter, m_pVertSplitter, m_szRootServer, requestLinks(), KviIrcContext::setLinksWindowPointer(), KviTalHBox::setStretchFactor(), showHostPopup(), and KviIconManager::Update.
LinksWindow::~LinksWindow ()
References KviConsoleWindow::context(), KviWindow::m_pConsole, m_pHostPopup, m_pLinkList, KviPointerList< T >::removeRef(), and KviIrcContext::setLinksWindowPointer().
Member Function Documentation
void LinksWindow::applyOptions () protected virtual
Reimplemented from KviWindow.
References KviThemedTreeWidget::applyOptions(), KviThemedLabel::applyOptions(), KviIrcView::applyOptions(), KviWindow::applyOptions(), m_pInfoLabel, KviWindow::m_pIrcView, and m_pListView.
void LinksWindow::connectionStateChange () protected slot
References __tr2qs, KviIrcContext::Connected, KviWindow::connection(), KviConsoleWindow::context(), KviConsoleWindow::currentNetworkName(), KviIrcConnection::currentServerName(), KviWindow::m_pConsole, m_pInfoLabel, m_pRequestButton, and KviIrcContext::state().
Referenced by LinksWindow().
void LinksWindow::control (int msg) virtual
Reimplemented from KviExternalServerDataParser.
References endOfLinks(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_ENDOFDATA, EXTERNAL_SERVER_DATA_PARSER_CONTROL_RESET, and reset().
void LinksWindow::die () virtual
Reimplemented from KviExternalServerDataParser.
Referenced by links_module_cleanup().
void LinksWindow::endOfLinks () private
References __tr2qs, KviCString::append(), KviControlCodes::Bold, KviCString::Format, insertLink(), KVI_OUT_LINKS, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, l, m_pLinkList, m_pListView, m_pRequestButton, m_szRootServer, KviWindow::output(), KviWindow::outputNoFmt(), KviCString::ptr(), KviControlCodes::Underline, and KviWindow::updateCaption().
Referenced by control().
void LinksWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References __tr2qs, KviConsoleWindow::context(), KviIrcContext::id(), KviWindow::m_pConsole, KviWindow::m_szPlainTextCaption, and m_szRootServer.
void LinksWindow::getBaseLogFileName (QString & buffer) protected virtual
Reimplemented from KviWindow.
References KviWindow::context().
QTreeWidgetItem * LinksWindow::getItemByHost (const char * host, QTreeWidgetItem * par) private
References i, kvi_strEqualCI(), m_pListView, and KviCString::ptr().
Referenced by insertLink().
void LinksWindow::hostPopupClicked (QAction * pAction) protected slot
References __tr2qs, KviWindow::connection(), KviCString::hasData(), KVI_OUT_SYSTEMERROR, KviWindow::m_pConsole, KviWindow::output(), KviCString::ptr(), and KviIrcConnection::sendData().
Referenced by LinksWindow().
QTreeWidgetItem * LinksWindow::insertLink (KviLink * l) private
References _KviLink::description, KviCString::Format, getItemByHost(), _KviLink::hops, _KviLink::host, i, KVI_ASSERT, _KviLink::parent, and KviCString::ptr().
Referenced by endOfLinks().
QPixmap * LinksWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::Links.
void LinksWindow::processData (KviIrcMessage * msg) virtual
Reimplemented from KviExternalServerDataParser.
References __tr2qs, KviIrcMessage::allParams(), _KviLink::host, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, l, m, m_pLinkList, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), and KviCString::toInt().
void LinksWindow::requestLinks () protected slot
References __tr2qs, KviWindow::connection(), KviConsoleWindow::isConnected(), KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KviWindow::m_pConsole, m_pRequestButton, KviWindow::outputNoFmt(), and KviIrcConnection::sendFmtData().
Referenced by LinksWindow().
void LinksWindow::reset () private
References __tr2qs, KVI_OUT_SYSTEMMESSAGE, m_pLinkList, and KviWindow::outputNoFmt().
Referenced by control().
void LinksWindow::resizeEvent (QResizeEvent * e) protected virtual
References KviWindow::m_pSplitter, and m_pTopSplitter.
void LinksWindow::showHostPopup (QTreeWidgetItem * i, const QPoint & p) protected slot
References KviIconManager::ChanUnOwner, KviCString::Format, g_pIconManager, KviIconManager::getSmallIcon(), KviCString::isEmpty(), KviIconManager::KVIrc, KviIconManager::Links, m_pHostPopup, KviIconManager::Motd, KviCString::ptr(), KviIconManager::ServerInfo, KviIconManager::ServerPing, KviIconManager::Stats, KviIconManager::Time, and KviIconManager::User.
Referenced by LinksWindow().
QSize LinksWindow::sizeHint () const virtual
References KviWindow::m_pSplitter, and m_pTopSplitter.
Member Data Documentation
QMenu* LinksWindow::m_pHostPopup protected
Referenced by LinksWindow(), showHostPopup(), and ~LinksWindow().
KviThemedLabel* LinksWindow::m_pInfoLabel protected
Referenced by applyOptions(), connectionStateChange(), and LinksWindow().
KviPointerList<KviLink>* LinksWindow::m_pLinkList protected
Referenced by endOfLinks(), LinksWindow(), processData(), reset(), and ~LinksWindow().
LinksListView* LinksWindow::m_pListView protected
Referenced by applyOptions(), endOfLinks(), getItemByHost(), and LinksWindow().
QToolButton* LinksWindow::m_pRequestButton protected
Referenced by connectionStateChange(), endOfLinks(), LinksWindow(), and requestLinks().
QSplitter* LinksWindow::m_pTopSplitter protected
Referenced by LinksWindow(), resizeEvent(), and sizeHint().
QSplitter* LinksWindow::m_pVertSplitter protected
Referenced by LinksWindow().
QString LinksWindow::m_szRootServer protected
Referenced by endOfLinks(), fillCaptionBuffers(), and LinksWindow().
The documentation for this class was generated from the following files:
src/modules/links/LinksWindow.h
src/modules/links/LinksWindow.cpp