KVIrc: OptionsWidget_themeTransparency Class Reference
OptionsWidget_themeTransparency Class Reference
#include <OptionsWidget_theme.h>
Public Member Functions
OptionsWidget_themeTransparency (QWidget *parent)
~OptionsWidget_themeTransparency ()
Protected Slots
void enableGlobalBackgroundPixmapSelector (bool)
Constructor & Destructor Documentation
OptionsWidget_themeTransparency::OptionsWidget_themeTransparency (QWidget * parent)
COMPILE_PSEUDO_TRANSPARENCY
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), c, connect(), KviOptionsWidget::createLayout(), enableGlobalBackgroundPixmapSelector(), g_pApp, KVI_OPTION_BOOL, KviOption_boolUseCompositingForTransparency, KviOption_boolUseGlobalPseudoTransparency, KviOption_boolUseWindowsDesktopForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_pixmapGlobalTransparencyBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviOption_uintGlobalTransparencyParentFadeFactor, KviOption_uintGlobalWindowOpacityPercent, KviOptionsWidget::layout(), KviOptionsWidget::mergeTip(), KviApplication::supportsCompositing(), and u.
OptionsWidget_themeTransparency::~OptionsWidget_themeTransparency ()
Member Function Documentation
void OptionsWidget_themeTransparency::enableGlobalBackgroundPixmapSelector (bool) [protected, slot]
Referenced by OptionsWidget_themeTransparency().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_theme.h
src/modules/options/OptionsWidget_theme.cpp