KVIrc: KviTalMainWindow Class Reference
KviTalMainWindow Class Reference
Toolkit Abstraction Layer: mainwindow class.
#include <kvi_tal_mainwindow.h>
Public Member Functions
KviTalMainWindow (QWidget *pParent, const char *pcName)
Constructs the mainwindow object.
void setUsesBigPixmaps (bool bUse)
Sets the use of big pixmaps.
bool usesBigPixmaps ()
Returns true if the mainwindow uses big pixmaps.
~KviTalMainWindow ()
Destroys the mainwindow object.
Detailed Description
Toolkit Abstraction Layer: mainwindow class.
Constructor & Destructor Documentation
KviTalMainWindow::KviTalMainWindow (QWidget * pParent, const char * pcName)
Constructs the mainwindow object.
Parameters:
pParent The parent object
pcName The name of the object
Returns:
KviTalMainWindow
KviTalMainWindow::~KviTalMainWindow ()
Destroys the mainwindow object.
Returns:
KviTalMainWindow
Member Function Documentation
void KviTalMainWindow::setUsesBigPixmaps (bool bUse)
Sets the use of big pixmaps.
Parameters:
bUse Whether to use big pixmaps
Returns:
void
Referenced by KviFrame::KviFrame(), KviToolBar::setBigIcons(), and KviToolBar::setSmallIcons().
bool KviTalMainWindow::usesBigPixmaps ()
Returns true if the mainwindow uses big pixmaps.
Returns:
bool
Referenced by KviFrame::~KviFrame().
The documentation for this class was generated from the following files:
src/kvilib/tal/kvi_tal_mainwindow.h
src/kvilib/tal/kvi_tal_mainwindow.cpp