KVIrc: KviKvsTreeNodeSpecialCommandSwitchLabelMatch Class Reference
KviKvsTreeNodeSpecialCommandSwitchLabelMatch Class Reference
#include <kvi_kvs_treenode_specialcommandswitch.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool execute (KviKvsRunTimeContext *c, KviKvsVariant *pRealParameter)
KviKvsTreeNodeSpecialCommandSwitchLabelMatch (const QChar *pLocation)
~KviKvsTreeNodeSpecialCommandSwitchLabelMatch ()
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandSwitchLabelMatch::KviKvsTreeNodeSpecialCommandSwitchLabelMatch (const QChar * pLocation)
KviKvsTreeNodeSpecialCommandSwitchLabelMatch::~KviKvsTreeNodeSpecialCommandSwitchLabelMatch ()
Member Function Documentation
void KviKvsTreeNodeSpecialCommandSwitchLabelMatch::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeSpecialCommandSwitchLabelMatch::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
References KviKvsTreeNodeInstruction::dump(), KviKvsTreeNodeData::dump(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, and KviKvsTreeNodeSpecialCommandSwitchLabel::m_pParameter.
bool KviKvsTreeNodeSpecialCommandSwitchLabelMatch::execute (KviKvsRunTimeContext * c, KviKvsVariant * pRealParameter) [virtual]
Implements KviKvsTreeNodeSpecialCommandSwitchLabel.
References KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_bHasTerminatingBreak, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pParameter, and KviKvsRunTimeContext::setBreakPending().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_specialcommandswitch.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_specialcommandswitch.cpp