KVIrc: KviKvsPopupMenuItemLabel Class Reference
KviKvsPopupMenuItemLabel Class Reference
#include <KviKvsPopupMenu.h>
Public Member Functions
virtual void clear ()
virtual KviKvsPopupMenuItem * clone () const
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)
virtual ~KviKvsPopupMenuItemLabel ()
Public Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
QPixmap * evaluateIcon (KviKvsPopupMenuTopLevelData *pData)
QString evaluateText (KviKvsPopupMenuTopLevelData *pData)
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
virtual ~KviKvsPopupMenuItemWithTextAndIcon ()
Public Member Functions inherited from KviKvsPopupMenuItem
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
virtual KviKvsScript * kvsCode ()
KviKvsScript * kvsCondition ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItemLabel (const QString &szItemName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemLabel (const QString &szItemName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
void labelDestroyed ()
Protected Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItem
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Protected Attributes
QLabel * m_pLabel
KviKvsPopupMenuItemLabelHelper * m_pSignalRelay
Protected Attributes inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsScript * m_pKvsIcon
KviKvsScript * m_pKvsText
Protected Attributes inherited from KviKvsPopupMenuItem
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Friends
class KviKvsPopupMenu
class KviKvsPopupMenuItemLabelHelper
Additional Inherited Members
Public Types inherited from KviKvsPopupMenuItem
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Constructor & Destructor Documentation
KviKvsPopupMenuItemLabel::KviKvsPopupMenuItemLabel (const QString & szItemName, const QString & szText, const QString & szIcon, const QString & szCondition) protected
References KviKvsPopupMenuItemLabelHelper, m_pLabel, and m_pSignalRelay.
Referenced by clone().
KviKvsPopupMenuItemLabel::KviKvsPopupMenuItemLabel (const QString & szItemName, const KviKvsScript * pText, const KviKvsScript * pIcon, const KviKvsScript * pCondition) protected
References KviKvsPopupMenuItemLabelHelper, m_pLabel, and m_pSignalRelay.
KviKvsPopupMenuItemLabel::~KviKvsPopupMenuItemLabel () virtual
References labelDestroyed(), m_pLabel, and m_pSignalRelay.
Member Function Documentation
void KviKvsPopupMenuItemLabel::clear () virtual
Reimplemented from KviKvsPopupMenuItem.
References labelDestroyed(), m_pLabel, and m_pSignalRelay.
KviKvsPopupMenuItem * KviKvsPopupMenuItemLabel::clone () const virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItemLabel(), KviKvsPopupMenuItem::m_pKvsCondition, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsIcon, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsText, and KviKvsPopupMenuItem::m_szItemName.
void KviKvsPopupMenuItemLabel::fill (KviKvsPopupMenu * pMenu, KviKvsPopupMenuTopLevelData * pData, int iIdx) virtual
Implements KviKvsPopupMenuItem.
References connect(), KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), labelDestroyed(), m_pLabel, and m_pSignalRelay.
void KviKvsPopupMenuItemLabel::labelDestroyed () protected
References m_pLabel.
Referenced by clear(), fill(), KviKvsPopupMenuItemLabelHelper::labelDestroyed(), and ~KviKvsPopupMenuItemLabel().
Friends And Related Function Documentation
friend class KviKvsPopupMenu friend
friend class KviKvsPopupMenuItemLabelHelper friend
Referenced by KviKvsPopupMenuItemLabel().
Member Data Documentation
QLabel* KviKvsPopupMenuItemLabel::m_pLabel protected
Referenced by clear(), fill(), KviKvsPopupMenuItemLabel(), labelDestroyed(), and ~KviKvsPopupMenuItemLabel().
KviKvsPopupMenuItemLabelHelper* KviKvsPopupMenuItemLabel::m_pSignalRelay protected
Referenced by clear(), fill(), KviKvsPopupMenuItemLabel(), and ~KviKvsPopupMenuItemLabel().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp