KVIrc: KviXmlHandler Class Reference
KviXmlHandler Class Reference
Public Member Functions
virtual bool characters (const QString &szChars)
virtual bool endDocument ()
virtual bool endElement (const QString &szNamespaceUri, const QString &szLocalName, const QString &szQualifiedName)
virtual bool error (const QXmlParseException &exception)
virtual QString errorString () const
virtual bool fatalError (const QXmlParseException &exception)
KviXmlHandler (KvsObject_xmlReader *pReader)
virtual bool startDocument ()
virtual bool startElement (const QString &szNamespaceUri, const QString &szLocalName, const QString &szQualifiedName, const QXmlAttributes &attrs)
virtual bool warning (const QXmlParseException &exception)
~KviXmlHandler ()
Protected Attributes
KvsObject_xmlReader * m_pReader
QString m_szErrorString
Private Member Functions
void decodeException (QString &szMsg, bool bError, const QXmlParseException &exception)
bool handleKvsCallReturnValue (KviKvsVariant *pRetVal)
bool kvsCodeAbort ()
bool kvsCodeFailure ()
Constructor & Destructor Documentation
KviXmlHandler::KviXmlHandler (KvsObject_xmlReader * pReader) [inline]
References m_pReader.
KviXmlHandler::~KviXmlHandler () [inline]
Member Function Documentation
virtual bool KviXmlHandler::characters (const QString & szChars) [inline, virtual]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), handleKvsCallReturnValue(), kvsCodeFailure(), m_pReader, and KviKvsVariantList::setAutoDelete().
void KviXmlHandler::decodeException (QString & szMsg, bool bError, const QXmlParseException & exception) [inline, private]
References __tr2qs_ctx().
Referenced by error(), fatalError(), and warning().
virtual bool KviXmlHandler::endDocument () [inline, virtual]
References KviKvsObject::callFunction(), handleKvsCallReturnValue(), kvsCodeFailure(), and m_pReader.
virtual bool KviXmlHandler::endElement (const QString & szNamespaceUri, const QString & szLocalName, const QString & szQualifiedName) [inline, virtual]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), handleKvsCallReturnValue(), kvsCodeFailure(), m_pReader, and KviKvsVariantList::setAutoDelete().
virtual bool KviXmlHandler::error (const QXmlParseException & exception) [inline, virtual]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), decodeException(), handleKvsCallReturnValue(), kvsCodeFailure(), m_pReader, and KviKvsVariantList::setAutoDelete().
virtual QString KviXmlHandler::errorString () const [inline, virtual]
References m_szErrorString.
virtual bool KviXmlHandler::fatalError (const QXmlParseException & exception) [inline, virtual]
References decodeException(), KvsObject_xmlReader::fatalError(), and m_pReader.
bool KviXmlHandler::handleKvsCallReturnValue (KviKvsVariant * pRetVal) [inline, private]
References KviKvsVariant::asBoolean(), and kvsCodeAbort().
Referenced by characters(), endDocument(), endElement(), error(), startDocument(), startElement(), and warning().
bool KviXmlHandler::kvsCodeAbort () [inline, private]
References __tr2qs_ctx(), and m_szErrorString.
Referenced by handleKvsCallReturnValue().
bool KviXmlHandler::kvsCodeFailure () [inline, private]
References __tr2qs_ctx(), and m_szErrorString.
Referenced by characters(), endDocument(), endElement(), error(), startDocument(), startElement(), and warning().
virtual bool KviXmlHandler::startDocument () [inline, virtual]
References KviKvsObject::callFunction(), handleKvsCallReturnValue(), kvsCodeFailure(), and m_pReader.
virtual bool KviXmlHandler::startElement (const QString & szNamespaceUri, const QString & szLocalName, const QString & szQualifiedName, const QXmlAttributes & attrs) [inline, virtual]
References KviKvsVariantList::append(), c, KviKvsObject::callFunction(), handleKvsCallReturnValue(), i, kvsCodeFailure(), m_pReader, KviKvsHash::set(), and KviKvsVariantList::setAutoDelete().
virtual bool KviXmlHandler::warning (const QXmlParseException & exception) [inline, virtual]
References KviKvsVariantList::append(), KviKvsObject::callFunction(), decodeException(), handleKvsCallReturnValue(), kvsCodeFailure(), m_pReader, and KviKvsVariantList::setAutoDelete().
Member Data Documentation
KvsObject_xmlReader* KviXmlHandler::m_pReader [protected]
Referenced by characters(), endDocument(), endElement(), error(), fatalError(), KviXmlHandler(), startDocument(), startElement(), and warning().
QString KviXmlHandler::m_szErrorString [protected]
Referenced by errorString(), kvsCodeAbort(), and kvsCodeFailure().
The documentation for this class was generated from the following file:
src/modules/objects/KvsObject_xmlreader.cpp