KVIrc: KviKvsTreeNodeParameterReturn Class Reference
KviKvsTreeNodeParameterReturn Class Reference
#include <KviKvsTreeNodeParameterReturn.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeParameterReturn (const QChar *pLocation, KviKvsTreeNodeDataList *pDataList)
~KviKvsTreeNodeParameterReturn ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeDataList * m_pDataList
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeParameterReturn::KviKvsTreeNodeParameterReturn (const QChar * pLocation, KviKvsTreeNodeDataList * pDataList)
References m_pDataList, and KviKvsTreeNode::setParent().
KviKvsTreeNodeParameterReturn::~KviKvsTreeNodeParameterReturn ()
References m_pDataList.
Member Function Documentation
void KviKvsTreeNodeParameterReturn::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeInstruction.
void KviKvsTreeNodeParameterReturn::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeInstruction.
References KviKvsTreeNodeDataList::dump(), and m_pDataList.
bool KviKvsTreeNodeParameterReturn::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariantList::allAsString(), KviKvsVariant::copyFrom(), KviKvsVariantList::count(), KviKvsTreeNodeDataList::evaluate(), KviKvsVariantList::first(), m_pDataList, KviKvsRunTimeContext::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Member Data Documentation
KviKvsTreeNodeDataList* KviKvsTreeNodeParameterReturn::m_pDataList protected
Referenced by dump(), execute(), KviKvsTreeNodeParameterReturn(), and ~KviKvsTreeNodeParameterReturn().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeParameterReturn.h
src/kvirc/kvs/tree/KviKvsTreeNodeParameterReturn.cpp