KVIrc: UrlDialog Class Reference
UrlDialog Class Reference
#include <libkviurl.h>
Public Member Functions
void addUrl (QString url, QString window, QString count, QString timestamp)
UrlDialog (KviPointerList< KviUrl > *g_pList)
~UrlDialog ()
Public Attributes
UrlDialogTreeWidget * m_pUrlList
Protected Slots
void clear ()
void close_slot ()
void config ()
void contextMenu (const QPoint &p)
void dblclk_url (QTreeWidgetItem *item, int)
void findtext ()
void help ()
void loadList ()
void popup (QTreeWidgetItem *item, const QPoint &p)
void remove ()
void saveList ()
void sayToWin (QAction *act)
Protected Member Functions
QPixmap * myIconPtr ()
void resizeEvent (QResizeEvent *)
Private Attributes
KviTalPopupMenu * m_pListPopup
KviTalMenuBar * m_pMenuBar
QString m_szUrl
Constructor & Destructor Documentation
UrlDialog::UrlDialog (KviPointerList< KviUrl > * g_pList)
References __tr2qs, connect(), contextMenu(), dblclk_url(), m_pMenuBar, m_pUrlList, popup(), KviConfigurationFile::Read, and szConfigPath.
UrlDialog::~UrlDialog ()
References _UrlDlgList::dlg, findFrame(), and m_pUrlList.
Member Function Documentation
void UrlDialog::addUrl (QString url, QString window, QString count, QString timestamp)
References KVI_OPTION_MIRCCOLOR, KVI_OPTION_MSGTYPE, KVI_OUT_NONE, KVI_OUT_URL, and m_pUrlList.
Referenced by urllist().
void UrlDialog::clear () [protected, slot]
References KviPointerList< T >::clear(), KviPointerList< T >::first(), and KviPointerList< T >::next().
void UrlDialog::close_slot () [protected, slot]
void UrlDialog::config () [protected, slot]
Referenced by contextMenu().
void UrlDialog::contextMenu (const QPoint & p) [protected, slot]
References __tr2qs, config(), KviTalPopupMenu::insertItem(), and p.
Referenced by UrlDialog().
void UrlDialog::dblclk_url (QTreeWidgetItem * item, int) [protected, slot]
References KviQString::escapeKvs(), KviIrcUrl::run(), and szUrl.
Referenced by UrlDialog().
void UrlDialog::findtext () [protected, slot]
void UrlDialog::help () [protected, slot]
void UrlDialog::loadList () [protected, slot]
References loadUrlList().
QPixmap * UrlDialog::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::Url.
void UrlDialog::popup (QTreeWidgetItem * item, const QPoint & p) [protected, slot]
References __tr2qs, KviWindow::Channel, connect(), KviWindow::DccChat, KviPointerList< T >::first(), g_pMainWindow, KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), m_pListPopup, m_szUrl, KviPointerList< T >::next(), p, KviWindow::Query, sayToWin(), w, and KviMainWindow::windowList().
Referenced by UrlDialog().
void UrlDialog::remove () [protected, slot]
References __tr2qs, KviPointerList< T >::first(), m_pUrlList, KviPointerList< T >::next(), KviPointerList< T >::removeRef(), and KviMessageBox::warning().
void UrlDialog::resizeEvent (QResizeEvent *) [protected]
References m_pMenuBar, and m_pUrlList.
void UrlDialog::saveList () [protected, slot]
References saveUrlList().
void UrlDialog::sayToWin (QAction * act) [protected, slot]
References __tr2qs, KviQString::escapeKvs(), KviApplication::findWindowByCaption(), g_pApp, g_pMainWindow, m_szUrl, KviIrcUrl::run(), KviMainWindow::setActiveWindow(), szUrl, KviMessageBox::warning(), and KviWindow::windowName().
Referenced by popup().
Member Data Documentation
KviTalPopupMenu* UrlDialog::m_pListPopup [private]
Referenced by popup().
KviTalMenuBar* UrlDialog::m_pMenuBar [private]
Referenced by resizeEvent(), and UrlDialog().
UrlDialogTreeWidget* UrlDialog::m_pUrlList
Referenced by addUrl(), remove(), resizeEvent(), UrlDialog(), and ~UrlDialog().
QString UrlDialog::m_szUrl [private]
Referenced by popup(), and sayToWin().
The documentation for this class was generated from the following files:
src/modules/url/libkviurl.h
src/modules/url/libkviurl.cpp