KVIrc: KviIrcConnectionAsyncWhoisData Class Reference
KviIrcConnectionAsyncWhoisData Class Reference
#include <kvi_ircconnectionasyncwhoisdata.h>
Public Member Functions
void add (KviAsyncWhoisInfo *i)
KviIrcConnectionAsyncWhoisData ()
KviAsyncWhoisInfo * lookup (const QString &nick)
void remove (KviAsyncWhoisInfo *i)
~KviIrcConnectionAsyncWhoisData ()
Protected Attributes
KviPointerList
< KviAsyncWhoisInfo > * m_pWhoisInfoList
Constructor & Destructor Documentation
KviIrcConnectionAsyncWhoisData::KviIrcConnectionAsyncWhoisData ()
References m_pWhoisInfoList.
KviIrcConnectionAsyncWhoisData::~KviIrcConnectionAsyncWhoisData ()
References m_pWhoisInfoList.
Member Function Documentation
void KviIrcConnectionAsyncWhoisData::add (KviAsyncWhoisInfo * i)
References KviPointerList< T >::append(), m_pWhoisInfoList, and KviPointerList< T >::setAutoDelete().
KviAsyncWhoisInfo * KviIrcConnectionAsyncWhoisData::lookup (const QString & nick)
References KviQString::equalCI(), KviPointerList< T >::first(), m_pWhoisInfoList, and KviPointerList< T >::next().
Referenced by KviServerParser::parseNumericEndOfWhois(), KviServerParser::parseNumericNoSuchNick(), KviServerParser::parseNumericWhoisAway(), KviServerParser::parseNumericWhoisChannels(), KviServerParser::parseNumericWhoisIdle(), KviServerParser::parseNumericWhoisOther(), KviServerParser::parseNumericWhoisServer(), and KviServerParser::parseNumericWhoisUser().
void KviIrcConnectionAsyncWhoisData::remove (KviAsyncWhoisInfo * i)
References KviPointerList< T >::isEmpty(), m_pWhoisInfoList, and KviPointerList< T >::removeRef().
Referenced by KviServerParser::parseNumericEndOfWhois(), and KviServerParser::parseNumericNoSuchNick().
Member Data Documentation
KviPointerList<KviAsyncWhoisInfo>* KviIrcConnectionAsyncWhoisData::m_pWhoisInfoList [protected]
Referenced by add(), KviIrcConnectionAsyncWhoisData(), lookup(), remove(), and ~KviIrcConnectionAsyncWhoisData().
The documentation for this class was generated from the following files:
src/kvirc/kernel/kvi_ircconnectionasyncwhoisdata.h
src/kvirc/kernel/kvi_ircconnectionasyncwhoisdata.cpp