KVIrc: UPnP::IgdControlPoint Class Reference
UPnP::IgdControlPoint Class Reference
#include <igdcontrolpoint.h>
Public Member Functions
void addPortMapping (const QString &protocol, const QString &remoteHost, int externalPort, const QString &internalClient, int internalPort, const QString &description, bool enabled=true, int leaseDuration=0)
void deletePortMapping (const QString &protocol, const QString &remoteHost, int externalPort)
QString getExternalIpAddress () const
IgdControlPoint (const QString &hostname, int port, const QString &rootUrl)
void initialize ()
bool isGatewayAvailable ()
virtual ~IgdControlPoint ()
Private Slots
void slotDeviceQueried (bool error)
void slotWanQueryFinished (bool error)
Private Attributes
bool m_bGatewayAvailable
int m_iIgdPort
RootService * m_pRootService
WanConnectionService * m_pWanConnectionService
QString m_szIgdHostname
Detailed Description
A control point is a UPnP term for "client". It's the host that controls the UPnP device. This control point specifically handles Internet Gateway Devices (routers in UPnP terminology). It queries the device for its port mapping service (an instance of a WanIPConnection or WanPPPConnection service). Once the service is found, it can be used from the Manager class to configure port mappings.
Author:
Diederik van der Boor
Constructor & Destructor Documentation
UPnP::IgdControlPoint::IgdControlPoint (const QString & hostname, int port, const QString & rootUrl)
References connect(), and KviOsInfo::hostname().
UPnP::IgdControlPoint::~IgdControlPoint () [virtual]
Member Function Documentation
void UPnP::IgdControlPoint::addPortMapping (const QString & protocol, const QString & remoteHost, int externalPort, const QString & internalClient, int internalPort, const QString & description, bool enabled = true, int leaseDuration = 0)
References UPnP::WanConnectionService::addPortMapping(), and m_pWanConnectionService.
Referenced by UPnP::Manager::addPortMapping().
void UPnP::IgdControlPoint::deletePortMapping (const QString & protocol, const QString & remoteHost, int externalPort)
References UPnP::WanConnectionService::deletePortMapping(), and m_pWanConnectionService.
Referenced by UPnP::Manager::deletePortMapping().
QString UPnP::IgdControlPoint::getExternalIpAddress () const
References UPnP::WanConnectionService::getExternalIpAddress(), and m_pWanConnectionService.
Referenced by UPnP::Manager::getExternalIpAddress().
void UPnP::IgdControlPoint::initialize ()
Referenced by UPnP::Manager::slotDeviceFound().
bool UPnP::IgdControlPoint::isGatewayAvailable ()
Referenced by UPnP::Manager::isGatewayAvailable().
void UPnP::IgdControlPoint::slotDeviceQueried (bool error) [private, slot]
References connect(), UPnP::ServiceParameters::controlUrl, UPnP::RootService::getServiceByType(), m_bGatewayAvailable, m_pRootService, m_pWanConnectionService, UPnP::WanConnectionService::queryExternalIpAddress(), UPnP::ServiceParameters::serviceId, slotWanQueryFinished(), WanIpConnectionType, and WanPPPConnectionType.
void UPnP::IgdControlPoint::slotWanQueryFinished (bool error) [private, slot]
Referenced by slotDeviceQueried().
Member Data Documentation
bool UPnP::IgdControlPoint::m_bGatewayAvailable [private]
Referenced by slotDeviceQueried().
int UPnP::IgdControlPoint::m_iIgdPort [private]
RootService* UPnP::IgdControlPoint::m_pRootService [private]
Referenced by slotDeviceQueried().
WanConnectionService* UPnP::IgdControlPoint::m_pWanConnectionService [private]
Referenced by addPortMapping(), deletePortMapping(), getExternalIpAddress(), and slotDeviceQueried().
QString UPnP::IgdControlPoint::m_szIgdHostname [private]
The documentation for this class was generated from the following files:
src/modules/upnp/igdcontrolpoint.h
src/modules/upnp/igdcontrolpoint.cpp