KVIrc: KvsObject_tableWidget Class Reference
KvsObject_tableWidget Class Reference
#include <KvsObject_tableWidget.h>
Public Member Functions
bool paint (QPainter *pPainter, const QStyleOptionViewItem &option, const QModelIndex &index)
QWidget * widget ()
Public Member Functions inherited from KvsObject_widget
QWidget * widget ()
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Protected Slots
void cellActivated (int iRow, int iCol)
void cellDoubleClicked (int iRow, int iCol)
void slotItemEntered (QTableWidgetItem *)
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Protected Member Functions
bool cellActivatedEvent (KviKvsObjectFunctionCall *c)
bool cellDoubleClickedEvent (KviKvsObjectFunctionCall *c)
bool clear (KviKvsObjectFunctionCall *c)
bool columnCount (KviKvsObjectFunctionCall *c)
bool currentColumn (KviKvsObjectFunctionCall *c)
bool currentRow (KviKvsObjectFunctionCall *c)
bool hideColumn (KviKvsObjectFunctionCall *c)
bool hideHorizontalHeader (KviKvsObjectFunctionCall *c)
bool hideRow (KviKvsObjectFunctionCall *c)
bool hideVerticalHeader (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertColumn (KviKvsObjectFunctionCall *c)
bool insertRow (KviKvsObjectFunctionCall *c)
bool itemEnteredEvent (KviKvsObjectFunctionCall *c)
bool itemRowColAt (KviKvsObjectFunctionCall *c)
bool removeColumn (KviKvsObjectFunctionCall *c)
bool removeRow (KviKvsObjectFunctionCall *c)
bool resizeColumnsToContents (KviKvsObjectFunctionCall *c)
bool resizeRowsToContents (KviKvsObjectFunctionCall *c)
bool rowCount (KviKvsObjectFunctionCall *c)
bool setCellWidget (KviKvsObjectFunctionCall *c)
bool setColumnCount (KviKvsObjectFunctionCall *c)
bool setForeground (KviKvsObjectFunctionCall *c)
bool setHorizontalHeaderLabels (KviKvsObjectFunctionCall *c)
bool setIcon (KviKvsObjectFunctionCall *c)
bool setItemFlags (KviKvsObjectFunctionCall *c)
bool setNumber (KviKvsObjectFunctionCall *c)
bool setRowCount (KviKvsObjectFunctionCall *c)
bool setText (KviKvsObjectFunctionCall *c)
bool setToolTip (KviKvsObjectFunctionCall *c)
bool setVerticalHeaderLabels (KviKvsObjectFunctionCall *c)
bool showColumn (KviKvsObjectFunctionCall *c)
bool showHorizontalHeader (KviKvsObjectFunctionCall *c)
bool showRow (KviKvsObjectFunctionCall *c)
bool showVerticalHeader (KviKvsObjectFunctionCall *c)
bool text (KviKvsObjectFunctionCall *c)
Protected Member Functions inherited from KvsObject_widget
bool addWidgetToWrappedLayout (KviKvsObjectFunctionCall *c)
bool backgroundColor (KviKvsObjectFunctionCall *c)
bool centerToScreen (KviKvsObjectFunctionCall *c)
bool colorPalette (KviKvsObjectFunctionCall *c)
virtual bool eventFilter (QObject *o, QEvent *e)
bool fontAscent (KviKvsObjectFunctionCall *c)
bool fontDescent (KviKvsObjectFunctionCall *c)
bool fontMetricsHeight (KviKvsObjectFunctionCall *c)
bool fontMetricsLineSpacing (KviKvsObjectFunctionCall *c)
bool fontMetricsWidth (KviKvsObjectFunctionCall *c)
bool foregroundColor (KviKvsObjectFunctionCall *c)
bool geometry (KviKvsObjectFunctionCall *c)
bool globalCursorX (KviKvsObjectFunctionCall *c)
bool globalCursorY (KviKvsObjectFunctionCall *c)
bool grab (KviKvsObjectFunctionCall *)
bool hasFocus (KviKvsObjectFunctionCall *c)
bool height (KviKvsObjectFunctionCall *)
bool hide (KviKvsObjectFunctionCall *)
bool insertIntoStatusBar (KviKvsObjectFunctionCall *c)
bool isEnabled (KviKvsObjectFunctionCall *c)
bool isTopLevel (KviKvsObjectFunctionCall *c)
bool isVisible (KviKvsObjectFunctionCall *c)
bool loadInterface (KviKvsObjectFunctionCall *c)
bool lower (KviKvsObjectFunctionCall *)
bool mapFromGlobal (KviKvsObjectFunctionCall *c)
bool mapToGlobal (KviKvsObjectFunctionCall *c)
bool move (KviKvsObjectFunctionCall *c)
bool parentWidget (KviKvsObjectFunctionCall *c)
bool raise (KviKvsObjectFunctionCall *)
bool removeFromStatusBar (KviKvsObjectFunctionCall *c)
bool repaint (KviKvsObjectFunctionCall *c)
bool resize (KviKvsObjectFunctionCall *c)
bool screenResolution (KviKvsObjectFunctionCall *c)
bool setAttribute (KviKvsObjectFunctionCall *c)
bool setBackgroundColor (KviKvsObjectFunctionCall *c)
bool setBackgroundImage (KviKvsObjectFunctionCall *c)
bool setEnabled (KviKvsObjectFunctionCall *c)
bool setFocus (KviKvsObjectFunctionCall *c)
bool setFocusPolicy (KviKvsObjectFunctionCall *c)
bool setFont (KviKvsObjectFunctionCall *c)
bool setForegroundColor (KviKvsObjectFunctionCall *c)
bool setGeometry (KviKvsObjectFunctionCall *c)
bool setKeyShortcut (KviKvsObjectFunctionCall *c)
bool setMask (KviKvsObjectFunctionCall *c)
bool setMaximumHeight (KviKvsObjectFunctionCall *c)
bool setMaximumWidth (KviKvsObjectFunctionCall *c)
bool setMinimumHeight (KviKvsObjectFunctionCall *c)
bool setMinimumWidth (KviKvsObjectFunctionCall *c)
bool setMouseTracking (KviKvsObjectFunctionCall *c)
bool setParent (KviKvsObjectFunctionCall *c)
bool setStyleSheet (KviKvsObjectFunctionCall *c)
bool setToolTip (KviKvsObjectFunctionCall *)
bool setWFlags (KviKvsObjectFunctionCall *c)
bool setWindowIcon (KviKvsObjectFunctionCall *c)
bool setWindowTitle (KviKvsObjectFunctionCall *c)
bool show (KviKvsObjectFunctionCall *c)
bool sizeHint (KviKvsObjectFunctionCall *c)
bool update (KviKvsObjectFunctionCall *c)
bool width (KviKvsObjectFunctionCall *)
bool windowTitle (KviKvsObjectFunctionCall *c)
bool x (KviKvsObjectFunctionCall *)
bool y (KviKvsObjectFunctionCall *)
Protected Member Functions inherited from KviKvsObject
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
KviCellItemDelegate * m_pCellItemDelegate
KviKvsRunTimeContext * m_pContext
Protected Attributes inherited from KvsObject_widget
KviKvsRunTimeContext * m_pContext
QGraphicsDropShadowEffect * pGraphicsEffect
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Additional Inherited Members
Signals inherited from KvsObject_widget
void aboutToDie ()
Member Function Documentation
void KvsObject_tableWidget::cellActivated (int iRow, int iCol) protected slot
References KviKvsObject::callFunction().
bool KvsObject_tableWidget::cellActivatedEvent (KviKvsObjectFunctionCall * c) protected
void KvsObject_tableWidget::cellDoubleClicked (int iRow, int iCol) protected slot
References KviKvsObject::callFunction().
bool KvsObject_tableWidget::cellDoubleClickedEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::clear (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::columnCount (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::currentColumn (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::currentRow (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::hideColumn (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::hideHorizontalHeader (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::hideRow (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::hideVerticalHeader (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) protected virtual
Reimplemented from KvsObject_widget.
References c, connect(), and SET_OBJECT.
bool KvsObject_tableWidget::insertColumn (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::insertRow (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::itemEnteredEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::itemRowColAt (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::paint (QPainter * pPainter, const QStyleOptionViewItem & option, const QModelIndex & index)
References KviKvsObjectClass::allocateInstance(), KviKvsVariant::asBoolean(), KviKvsObject::callFunction(), KviKvsObject::dieNow(), KviKvsObject::handle(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), KviKvsObjectController::lookupObject(), m_pContext, and KviKvsKernel::objectController().
Referenced by KviCellItemDelegate::paint().
bool KvsObject_tableWidget::removeColumn (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::removeRow (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::resizeColumnsToContents (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::resizeRowsToContents (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::rowCount (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setCellWidget (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setColumnCount (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setForeground (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setHorizontalHeaderLabels (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setIcon (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setItemFlags (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setNumber (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setRowCount (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setText (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setToolTip (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::setVerticalHeaderLabels (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::showColumn (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::showHorizontalHeader (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::showRow (KviKvsObjectFunctionCall * c) protected
bool KvsObject_tableWidget::showVerticalHeader (KviKvsObjectFunctionCall * c) protected
void KvsObject_tableWidget::slotItemEntered (QTableWidgetItem * i) protected slot
References KviKvsObject::callFunction().
bool KvsObject_tableWidget::text (KviKvsObjectFunctionCall * c) protected
QWidget* KvsObject_tableWidget::widget () inline
References KviKvsObject::object().
Member Data Documentation
KviCellItemDelegate* KvsObject_tableWidget::m_pCellItemDelegate protected
KviKvsRunTimeContext* KvsObject_tableWidget::m_pContext protected
Referenced by paint().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_tableWidget.h
src/modules/objects/KvsObject_tableWidget.cpp