KVIrc: KviFileSelector Class Reference
KviFileSelector Class Reference
#include <KviSelectors.h>
Public Types
enum Flags { ChooseSaveFileName = 1, DontConfirmOverwrite = 2, VerticalLayout = 4 }
Public Slots
virtual void setEnabled (bool bEnabled)
Signals
void selectionChanged (const QString &szNewValue)
Public Member Functions
virtual void commit ()
KviFileSelector (QWidget *par, const QString &txt, QString *pOption, bool bEnabled, unsigned int uFlags=0, const QString &szFilter=QString())
void setSelection (const QString &szSelection)
void setTmpFile (QString &szFile)
QString tmpFile ()
~KviFileSelector ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Member Functions
virtual void select ()
Protected Attributes
QGridLayout * m_Layout
QPushButton * m_pButton
QLabel * m_pLabel
QLineEdit * m_pLineEdit
QString * m_pOption
QString m_szFilter
unsigned int m_uFlags
Properties
QString tmpFile
Private Slots
void browseClicked ()
Member Enumeration Documentation
enum KviFileSelector::Flags
Enumerator
ChooseSaveFileName
DontConfirmOverwrite
VerticalLayout
Constructor & Destructor Documentation
KviFileSelector::KviFileSelector (QWidget * par, const QString & txt, QString * pOption, bool bEnabled, unsigned int uFlags = 0, const QString & szFilter = QString())
References __tr2qs, browseClicked(), connect(), m_Layout, m_pButton, m_pLabel, m_pLineEdit, m_pOption, m_szFilter, m_uFlags, setEnabled(), and VerticalLayout.
KviFileSelector::~KviFileSelector () inline
Member Function Documentation
void KviFileSelector::browseClicked () private slot
References select().
Referenced by KviFileSelector().
void KviFileSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pLineEdit, and m_pOption.
Referenced by SaveThemeDialog::saveTheme().
void KviFileSelector::select () protected virtual
Reimplemented in KviDirectorySelector.
References __tr2qs, KviFileDialog::askForOpenFileName(), KviFileDialog::askForSaveFileName(), ChooseSaveFileName, DontConfirmOverwrite, m_pLineEdit, m_pOption, m_szFilter, m_uFlags, and selectionChanged().
Referenced by browseClicked().
void KviFileSelector::selectionChanged (const QString & szNewValue) signal
Referenced by select(), and KviDirectorySelector::select().
void KviFileSelector::setEnabled (bool bEnabled) virtual slot
Reimplemented in KviSoundSelector.
References m_pButton, m_pLabel, and m_pLineEdit.
Referenced by KviFileSelector(), and KviSoundSelector::setEnabled().
void KviFileSelector::setSelection (const QString & szSelection)
References m_pLineEdit.
Referenced by SaveThemeDialog::imageSelectionChanged(), PackThemeImageWidget::imageSelectionChanged(), and SaveThemeDialog::makeScreenshot().
void KviFileSelector::setTmpFile (QString & szFile) inline
Referenced by PackAddonSaveSelectionWidget::initializePage().
QString KviFileSelector::tmpFile () inline
Member Data Documentation
QGridLayout* KviFileSelector::m_Layout protected
Referenced by KviFileSelector(), and KviSoundSelector::KviSoundSelector().
QPushButton* KviFileSelector::m_pButton protected
Referenced by KviFileSelector(), and setEnabled().
QLabel* KviFileSelector::m_pLabel protected
Referenced by KviFileSelector(), and setEnabled().
QLineEdit* KviFileSelector::m_pLineEdit protected
Referenced by commit(), KviFileSelector(), KviSoundSelector::playSound(), select(), KviDirectorySelector::select(), setEnabled(), and setSelection().
QString* KviFileSelector::m_pOption protected
Referenced by commit(), KviFileSelector(), and select().
QString KviFileSelector::m_szFilter protected
Referenced by KviFileSelector(), and select().
unsigned int KviFileSelector::m_uFlags protected
Referenced by KviFileSelector(), KviSoundSelector::KviSoundSelector(), and select().
Property Documentation
QString KviFileSelector::tmpFile read write
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp