KVIrc: KviIconWidget Class Reference
KviIconWidget Class Reference
The widget with holds the table of icons.
#include <KviIconManager.h>
Signals
void closed ()
Emitted when we close the table widget.
void selected (KviIconManager::SmallIcon eIcon)
Emitted when we select an icon from the table.
Public Member Functions
KviIconWidget ()
Constructs the icon table widget.
KviIconWidget (QWidget *pPar)
Constructs the icon table widget.
~KviIconWidget ()
Destroys the icon table widget.
Protected Member Functions
virtual void closeEvent (QCloseEvent *pEvent)
virtual bool eventFilter (QObject *pObject, QEvent *pEvent)
void init ()
Initializes the table containing the icons.
Detailed Description
The widget with holds the table of icons.
Constructor & Destructor Documentation
KviIconWidget::KviIconWidget ()
Constructs the icon table widget.
Returns
KviIconWidget
References init().
KviIconWidget::KviIconWidget (QWidget * pPar)
Constructs the icon table widget.
Parameters
pPar The parent object
Returns
KviIconWidget
References init().
KviIconWidget::~KviIconWidget () default
Destroys the icon table widget.
Member Function Documentation
void KviIconWidget::closed () signal
Emitted when we close the table widget.
Returns
void
Referenced by closeEvent().
void KviIconWidget::closeEvent (QCloseEvent * pEvent) protected virtual
References closed().
bool KviIconWidget::eventFilter (QObject * pObject, QEvent * pEvent) protected virtual
References selected(), and KviCString::toInt().
void KviIconWidget::init () protected
Initializes the table containing the icons.
Returns
void
References __tr2qs, KviCString::Format, KviIconManager::getSmallIcon(), i, KviIconManager::IconCount, KviIconManager::IconManager, and KviCString::ptr().
Referenced by KviIconWidget().
void KviIconWidget::selected (KviIconManager::SmallIcon eIcon) signal
Emitted when we select an icon from the table.
Parameters
eIcon The index of the icon selected
Returns
void
Referenced by eventFilter().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIconManager.h
src/kvirc/kernel/KviIconManager.cpp