KVIrc: KviKvsModuleRunTimeCall Class Reference
KviKvsModuleRunTimeCall Class Reference
#include <KviKvsModuleInterface.h>
Public Member Functions
KviKvsModuleRunTimeCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
KviModule * module ()
~KviKvsModuleRunTimeCall ()
Protected Attributes
KviModule * m_pModule
Constructor & Destructor Documentation
KviKvsModuleRunTimeCall::KviKvsModuleRunTimeCall (KviModule * pModule, KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [inline]
KviKvsModuleRunTimeCall::~KviKvsModuleRunTimeCall () [inline]
Member Function Documentation
KviModule* KviKvsModuleRunTimeCall::module () [inline]
Referenced by default_module_kvs_cmd_unload(), filetransferwindow_kvs_cmd_open(), iograph_module_cmd_open(), logview_kvs_cmd_open(), sharedfileswindow_kvs_cmd_open(), and term_kvs_cmd_open().
Member Data Documentation
KviModule* KviKvsModuleRunTimeCall::m_pModule [protected]
The documentation for this class was generated from the following file:
src/kvirc/kvs/KviKvsModuleInterface.h