KVIrc: RawEditorWindow Class Reference
RawEditorWindow Class Reference
#include <RawEditorWindow.h>
Public Member Functions
RawEditorWindow ()
~RawEditorWindow ()
Protected Slots
void applyClicked ()
void cancelClicked ()
void okClicked ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void getConfigGroupName (QString &szName)
virtual void loadProperties (KviConfigurationFile *)
virtual QPixmap * myIconPtr ()
virtual void saveProperties (KviConfigurationFile *)
Protected Attributes
RawEditorWidget * m_pEditor
Constructor & Destructor Documentation
RawEditorWindow::RawEditorWindow ()
References __tr2qs_ctx(), KviIconManager::Accept, applyClicked(), cancelClicked(), connect(), KviIconManager::Discard, g, g_pIconManager, KviIconManager::getSmallIcon(), m_pEditor, and okClicked().
RawEditorWindow::~RawEditorWindow ()
Member Function Documentation
void RawEditorWindow::applyClicked () [protected, slot]
References RawEditorWidget::commit(), and m_pEditor.
Referenced by RawEditorWindow().
void RawEditorWindow::cancelClicked () [protected, slot]
Referenced by RawEditorWindow().
void RawEditorWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void RawEditorWindow::getConfigGroupName (QString & szName) [protected, virtual]
Reimplemented from KviWindow.
void RawEditorWindow::loadProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
QPixmap * RawEditorWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::RawEvent.
void RawEditorWindow::okClicked () [protected, slot]
References RawEditorWidget::commit(), and m_pEditor.
Referenced by RawEditorWindow().
void RawEditorWindow::saveProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
Member Data Documentation
RawEditorWidget* RawEditorWindow::m_pEditor [protected]
Referenced by applyClicked(), okClicked(), and RawEditorWindow().
The documentation for this class was generated from the following files:
src/modules/raweditor/RawEditorWindow.h
src/modules/raweditor/RawEditorWindow.cpp