KVIrc: KviIrcConnectionServerInfo Class Reference
KviIrcConnectionServerInfo Class Reference
#include <KviIrcConnectionServerInfo.h>
Public Member Functions
const QString & getChannelModeDescription (char mode)
bool getNeedsOpToListModeseI ()
const QString & getUserModeDescription (QChar mode)
bool isSupportedModeFlag (QChar c)
bool isSupportedModePrefix (QChar c)
int maxModeChanges ()
int maxTopicLen ()
QChar modeFlagChar (kvi_u32_t flag)
kvi_u32_t modeFlagFromModeChar (QChar c)
kvi_u32_t modeFlagFromPrefixChar (QChar c)
QChar modePrefixChar (kvi_u32_t flag)
const QString & name ()
const QString & networkName ()
char registerModeChar ()
void setServerVersion (const QString &version)
const char * software ()
const QStringList & supportedCaps ()
const QString & supportedChannelModes ()
const QString & supportedChannelTypes ()
const QString & supportedListModes ()
const QString & supportedModeFlags ()
const QString & supportedModePrefixes ()
const QString & supportedParameterModes ()
const QString & supportedParameterWhenSetModes ()
const QString & supportedPlainModes ()
const QString & supportedUserModes ()
bool supportsCap ()
bool supportsCodePages ()
bool supportsWatchList ()
Protected Member Functions
void addSupportedCaps (const QString &szCapList)
KviIrcConnectionServerInfo ()
void setMaxModeChanges (int iModes)
void setMaxTopicLen (int iTopLen)
void setName (const QString &szName)
void setNetworkName (const QString &szName)
void setSupportedChannelModes (const QString &szSupportedChannelModes)
void setSupportedChannelTypes (const QString &szSupportedChannelTypes)
void setSupportedModePrefixes (const QString &szSupportedModePrefixes, const QString &szSupportedModeFlags)
void setSupportedUserModes (const QString &szSupportedUserModes)
void setSupportsCodePages (bool bSupportsCodePages)
void setSupportsWatchList (bool bSupportsWatchList)
~KviIrcConnectionServerInfo ()
Private Member Functions
void buildModePrefixTable ()
Private Attributes
bool m_bSupportsCap
bool m_bSupportsCodePages
bool m_bSupportsWatchList
int m_iMaxModeChanges
int m_iMaxTopicLen
QStringList m_lSupportedCaps
kvi_u32_t * m_pModePrefixTable
KviBasicIrcServerInfo * m_pServInfo
QString m_szListModes
QString m_szName
QString m_szNetworkName
QString m_szParameterModes
QString m_szParameterWhenSetModes
QString m_szPlainModes
QString m_szSupportedChannelModes
QString m_szSupportedChannelTypes
QString m_szSupportedModeFlags
QString m_szSupportedModePrefixes
QString m_szSupportedUserModes
unsigned int m_uPrefixes
Friends
class KviConsoleWindow
class KviIrcConnection
class KviIrcServerParser
Constructor & Destructor Documentation
KviIrcConnectionServerInfo::KviIrcConnectionServerInfo () [protected]
References buildModePrefixTable(), m_bSupportsCap, m_bSupportsCodePages, m_bSupportsWatchList, m_iMaxModeChanges, m_iMaxTopicLen, m_pModePrefixTable, m_pServInfo, m_szListModes, m_szParameterModes, m_szParameterWhenSetModes, m_szPlainModes, m_szSupportedChannelModes, m_szSupportedChannelTypes, m_szSupportedModeFlags, and m_szSupportedModePrefixes.
KviIrcConnectionServerInfo::~KviIrcConnectionServerInfo () [protected]
References KviMemory::free(), m_pModePrefixTable, and m_pServInfo.
Member Function Documentation
void KviIrcConnectionServerInfo::addSupportedCaps (const QString & szCapList) [protected]
References m_bSupportsCap, and m_lSupportedCaps.
Referenced by KviIrcServerParser::parseLiteralCap().
void KviIrcConnectionServerInfo::buildModePrefixTable () [private]
References KviMemory::allocate(), KviIrcUserEntry::ChanAdmin, KviIrcUserEntry::ChanOwner, KviMemory::free(), KviIrcUserEntry::HalfOp, i, m_pModePrefixTable, m_szSupportedModeFlags, m_szSupportedModePrefixes, m_uPrefixes, KviIrcUserEntry::Op, KviIrcUserEntry::UserOp, and KviIrcUserEntry::Voice.
Referenced by KviIrcConnectionServerInfo(), and setSupportedModePrefixes().
const QString& KviIrcConnectionServerInfo::getChannelModeDescription (char mode) [inline]
Referenced by KviModeEditor::getModeDescription(), KviChannelWindow::KviChannelWindow(), KviMaskEditor::KviMaskEditor(), KviIrcServerParser::parseNumeric004(), and KviChannelWindow::updateModeLabel().
bool KviIrcConnectionServerInfo::getNeedsOpToListModeseI () [inline]
Referenced by KviIrcConnectionRequestQueue::timerSlot().
const QString& KviIrcConnectionServerInfo::getUserModeDescription (QChar mode) [inline]
Referenced by KviIrcServerParser::parseNumeric004().
bool KviIrcConnectionServerInfo::isSupportedModeFlag (QChar c)
References i, m_pModePrefixTable, and m_uPrefixes.
Referenced by KviUserListView::insertUserEntry(), and KviIrcServerParser::parseChannelMode().
bool KviIrcConnectionServerInfo::isSupportedModePrefix (QChar c)
References i, m_pModePrefixTable, and m_uPrefixes.
Referenced by KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), and KviIrcServerParser::parseNumericNames().
int KviIrcConnectionServerInfo::maxModeChanges () [inline]
Referenced by KviModeEditor::commit(), KviModeWidget::editorReturnPressed(), and KviChannelWindow::removeMasks().
int KviIrcConnectionServerInfo::maxTopicLen () [inline]
Referenced by KviTopicWidget::switchMode().
QChar KviIrcConnectionServerInfo::modeFlagChar (kvi_u32_t flag)
References i, m_pModePrefixTable, and m_uPrefixes.
kvi_u32_t KviIrcConnectionServerInfo::modeFlagFromModeChar (QChar c)
References i, m_pModePrefixTable, and m_uPrefixes.
Referenced by KviIrcServerParser::parseLiteralJoin().
kvi_u32_t KviIrcConnectionServerInfo::modeFlagFromPrefixChar (QChar c)
References i, m_pModePrefixTable, and m_uPrefixes.
Referenced by KviIrcServerParser::parseNumericNames().
QChar KviIrcConnectionServerInfo::modePrefixChar (kvi_u32_t flag)
References i, m_pModePrefixTable, and m_uPrefixes.
Referenced by KviUserListView::getUserFlag().
const QString& KviIrcConnectionServerInfo::name () [inline]
Referenced by KviIrcConnection::currentServerName(), KviConsoleWindow::fillStatusString(), and KviLagMeter::timerEvent().
const QString& KviIrcConnectionServerInfo::networkName () [inline]
Referenced by KviIrcConnection::currentNetworkName(), and KviIrcConnection::registerChannel().
char KviIrcConnectionServerInfo::registerModeChar () [inline]
Referenced by KviIrcServerParser::parseUserMode().
void KviIrcConnectionServerInfo::setMaxModeChanges (int iModes) [inline, protected]
Referenced by KviIrcServerParser::parseNumeric005().
void KviIrcConnectionServerInfo::setMaxTopicLen (int iTopLen) [inline, protected]
Referenced by KviIrcServerParser::parseNumeric005().
void KviIrcConnectionServerInfo::setName (const QString & szName) [inline, protected]
Referenced by KviIrcConnection::linkEstabilished(), KviIrcConnection::loginToIrcServer(), and KviIrcConnection::serverInfoReceived().
void KviIrcConnectionServerInfo::setNetworkName (const QString & szName) [inline, protected]
Referenced by KviIrcConnection::linkEstabilished(), and KviIrcServerParser::parseNumeric005().
void KviIrcConnectionServerInfo::setServerVersion (const QString & version)
References m_pServInfo.
Referenced by KviIrcServerParser::parseNumeric004().
void KviIrcConnectionServerInfo::setSupportedChannelModes (const QString & szSupportedChannelModes) [protected]
References m_szListModes, m_szParameterModes, m_szParameterWhenSetModes, m_szPlainModes, and m_szSupportedChannelModes.
Referenced by KviIrcServerParser::parseNumeric005(), and KviIrcConnection::serverInfoReceived().
void KviIrcConnectionServerInfo::setSupportedChannelTypes (const QString & szSupportedChannelTypes) [inline, protected]
Referenced by KviIrcServerParser::parseNumeric005().
void KviIrcConnectionServerInfo::setSupportedModePrefixes (const QString & szSupportedModePrefixes, const QString & szSupportedModeFlags) [protected]
References buildModePrefixTable(), m_szSupportedModeFlags, and m_szSupportedModePrefixes.
Referenced by KviIrcServerParser::parseNumeric005().
void KviIrcConnectionServerInfo::setSupportedUserModes (const QString & szSupportedUserModes) [inline, protected]
Referenced by KviIrcConnection::serverInfoReceived().
void KviIrcConnectionServerInfo::setSupportsCodePages (bool bSupportsCodePages) [inline, protected]
Referenced by KviIrcServerParser::parseNumeric005().
void KviIrcConnectionServerInfo::setSupportsWatchList (bool bSupportsWatchList) [inline, protected]
Referenced by KviIrcServerParser::parseNumeric005().
const char* KviIrcConnectionServerInfo::software () [inline]
const QStringList& KviIrcConnectionServerInfo::supportedCaps () [inline]
const QString& KviIrcConnectionServerInfo::supportedChannelModes () [inline]
const QString& KviIrcConnectionServerInfo::supportedChannelTypes () [inline]
Referenced by KviWindow::preprocessMessage(), and KviChannelWindow::preprocessMessage().
const QString& KviIrcConnectionServerInfo::supportedListModes () [inline]
Referenced by KviChannelWindow::KviChannelWindow(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviChannelWindow::setChannelMode(), and KviIrcConnectionRequestQueue::timerSlot().
const QString& KviIrcConnectionServerInfo::supportedModeFlags () [inline]
const QString& KviIrcConnectionServerInfo::supportedModePrefixes () [inline]
const QString& KviIrcConnectionServerInfo::supportedParameterModes () [inline]
Referenced by KviModeEditor::KviModeEditor(), and KviIrcServerParser::parseChannelMode().
const QString& KviIrcConnectionServerInfo::supportedParameterWhenSetModes () [inline]
Referenced by KviModeEditor::KviModeEditor(), KviModeWidget::modeNeedsParameterOnlyWhenSet(), KviModeEditor::modeNeedsParameterOnlyWhenSet(), and KviIrcServerParser::parseChannelMode().
const QString& KviIrcConnectionServerInfo::supportedPlainModes () [inline]
Referenced by KviBahamutIrcServerInfo::getChannelModeDescription(), and KviModeEditor::KviModeEditor().
const QString& KviIrcConnectionServerInfo::supportedUserModes () [inline]
Referenced by KviChangeUserModeAction::popupAboutToShow().
bool KviIrcConnectionServerInfo::supportsCap () [inline]
bool KviIrcConnectionServerInfo::supportsCodePages () [inline]
Referenced by KviIrcServerParser::parseNumericCodePageScheme(), and KviIrcServerParser::parseNumericCodePageSet().
bool KviIrcConnectionServerInfo::supportsWatchList () [inline]
Friends And Related Function Documentation
friend class KviConsoleWindow [friend]
friend class KviIrcConnection [friend]
friend class KviIrcServerParser [friend]
Member Data Documentation
bool KviIrcConnectionServerInfo::m_bSupportsCap [private]
Referenced by addSupportedCaps(), and KviIrcConnectionServerInfo().
bool KviIrcConnectionServerInfo::m_bSupportsCodePages [private]
Referenced by KviIrcConnectionServerInfo().
bool KviIrcConnectionServerInfo::m_bSupportsWatchList [private]
Referenced by KviIrcConnectionServerInfo().
int KviIrcConnectionServerInfo::m_iMaxModeChanges [private]
Referenced by KviIrcConnectionServerInfo().
int KviIrcConnectionServerInfo::m_iMaxTopicLen [private]
Referenced by KviIrcConnectionServerInfo().
QStringList KviIrcConnectionServerInfo::m_lSupportedCaps [private]
Referenced by addSupportedCaps().
kvi_u32_t* KviIrcConnectionServerInfo::m_pModePrefixTable [private]
Referenced by buildModePrefixTable(), isSupportedModeFlag(), isSupportedModePrefix(), KviIrcConnectionServerInfo(), modeFlagChar(), modeFlagFromModeChar(), modeFlagFromPrefixChar(), modePrefixChar(), and ~KviIrcConnectionServerInfo().
KviBasicIrcServerInfo* KviIrcConnectionServerInfo::m_pServInfo [private]
Referenced by KviIrcConnectionServerInfo(), setServerVersion(), and ~KviIrcConnectionServerInfo().
QString KviIrcConnectionServerInfo::m_szListModes [private]
Referenced by KviIrcConnectionServerInfo(), and setSupportedChannelModes().
QString KviIrcConnectionServerInfo::m_szName [private]
QString KviIrcConnectionServerInfo::m_szNetworkName [private]
QString KviIrcConnectionServerInfo::m_szParameterModes [private]
Referenced by KviIrcConnectionServerInfo(), and setSupportedChannelModes().
QString KviIrcConnectionServerInfo::m_szParameterWhenSetModes [private]
Referenced by KviIrcConnectionServerInfo(), and setSupportedChannelModes().
QString KviIrcConnectionServerInfo::m_szPlainModes [private]
Referenced by KviIrcConnectionServerInfo(), and setSupportedChannelModes().
QString KviIrcConnectionServerInfo::m_szSupportedChannelModes [private]
Referenced by KviIrcConnectionServerInfo(), and setSupportedChannelModes().
QString KviIrcConnectionServerInfo::m_szSupportedChannelTypes [private]
Referenced by KviIrcConnectionServerInfo().
QString KviIrcConnectionServerInfo::m_szSupportedModeFlags [private]
Referenced by buildModePrefixTable(), KviIrcConnectionServerInfo(), and setSupportedModePrefixes().
QString KviIrcConnectionServerInfo::m_szSupportedModePrefixes [private]
Referenced by buildModePrefixTable(), KviIrcConnectionServerInfo(), and setSupportedModePrefixes().
QString KviIrcConnectionServerInfo::m_szSupportedUserModes [private]
unsigned int KviIrcConnectionServerInfo::m_uPrefixes [private]
Referenced by buildModePrefixTable(), isSupportedModeFlag(), isSupportedModePrefix(), modeFlagChar(), modeFlagFromModeChar(), modeFlagFromPrefixChar(), and modePrefixChar().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionServerInfo.h
src/kvirc/kernel/KviIrcConnectionServerInfo.cpp