KVIrc: KvsObject_button Class Reference
KvsObject_button Class Reference
#include <KvsObject_button.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void slotClicked ()
Protected Member Functions
bool clickEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool setImage (KviKvsObjectFunctionCall *c)
bool setText (KviKvsObjectFunctionCall *c)
bool text (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_button::clickEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_button::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
Reimplemented in KvsObject_checkBox.
References connect(), and SET_OBJECT.
bool KvsObject_button::setImage (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_button::setText (KviKvsObjectFunctionCall * c) [protected]
Reimplemented in KvsObject_checkBox.
void KvsObject_button::slotClicked () [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_button::text (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_button::widget () [inline]
Reimplemented from KvsObject_widget.
Reimplemented in KvsObject_checkBox.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_button.h
src/modules/objects/KvsObject_button.cpp