KVIrc: AliasEditorWidget Class Reference
AliasEditorWidget Class Reference
#include <AliasEditorWindow.h>
Public Member Functions
AliasEditorWidget (QWidget *par)
void commit ()
void exportAliases (bool, bool=false)
void exportSelectionInSinglesFiles (KviPointerList< AliasEditorTreeWidgetItem > *l)
void loadProperties (KviConfigurationFile *)
void saveProperties (KviConfigurationFile *)
~AliasEditorWidget ()
Static Public Member Functions
static void splitFullAliasOrNamespaceName (const QString &szFullName, QStringList &lNamespaces, QString &szName)
Public Attributes
bool m_bSaving
KviTalPopupMenu * m_pContextPopup
KviScriptEditor * m_pEditor
AliasEditorTreeWidgetItem * m_pLastClickedItem
AliasEditorTreeWidgetItem * m_pLastEditedItem
QLabel * m_pNameLabel
QPushButton * m_pRenameButton
QSplitter * m_pSplitter
AliasEditorTreeWidget * m_pTreeWidget
QString m_szDir
Protected Slots
void aliasRefresh (const QString &szName)
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *)
void customContextMenuRequested (const QPoint pnt)
void exportAll ()
void exportSelected ()
void exportSelectedSepFiles ()
void itemRenamed (QTreeWidgetItem *it, int col)
void newAlias ()
void newItem (QString &szName, AliasEditorTreeWidgetItem::Type eType)
void newNamespace ()
void removeSelectedItems ()
void renameItem ()
void slotCollapseNamespaces ()
void slotFind ()
void slotFindWord (const QString &)
void slotReplaceAll (const QString &before, const QString &after)
Protected Member Functions
void activateItem (QTreeWidgetItem *it)
bool aliasExists (QString &szFullItemName)
void appendAllItems (KviPointerList< AliasEditorTreeWidgetItem > *l, AliasEditorTreeWidgetItem::Type)
void appendAllItemsRecursive (KviPointerList< AliasEditorTreeWidgetItem > *l, QTreeWidgetItem *pStartFrom, AliasEditorTreeWidgetItem::Type)
void appendSelectedAliasItems (KviPointerList< AliasEditorTreeWidgetItem > *l)
void appendSelectedAliasItemsRecursive (KviPointerList< AliasEditorTreeWidgetItem > *l, QTreeWidgetItem *pStartFrom)
void appendSelectedItems (KviPointerList< AliasEditorTreeWidgetItem > *l)
void appendSelectedItemsRecursive (KviPointerList< AliasEditorTreeWidgetItem > *l, QTreeWidgetItem *pStartFrom)
QString askForAliasName (const QString &szAction, const QString &szText, const QString &szInitialText)
QString askForNamespaceName (const QString &szAction, const QString &szText, const QString &szInitialText)
void buildAliasesFile (KviPointerList< AliasEditorTreeWidgetItem > *l, QString &szBuffer)
QString buildFullItemName (AliasEditorTreeWidgetItem *it)
void buildFullItemPath (AliasEditorTreeWidgetItem *it, QString &szBuffer)
AliasEditorTreeWidgetItem * createFullItem (const QString &szFullName)
AliasEditorTreeWidgetItem * findItem (const QString &szName)
AliasEditorTreeWidgetItem * findTopLevelItem (const QString &szName)
void getExportAliasBuffer (QString &buffer, AliasEditorTreeWidgetItem *it)
void getUniqueItemName (AliasEditorTreeWidgetItem *item, QString &buffer, AliasEditorTreeWidgetItem::Type eType)
bool hasSelectedItems ()
bool itemExists (QTreeWidgetItem *pSearchFor)
bool namespaceExists (QString &szFullItemName)
void oneTimeSetup ()
void openParentItems (QTreeWidgetItem *it)
void recursiveCollapseNamespaces (AliasEditorTreeWidgetItem *it)
bool removeItem (AliasEditorTreeWidgetItem *it, bool *pbYesToAll, bool bDeleteEmptyTree)
void removeItemChildren (AliasEditorTreeWidgetItem *it)
void saveLastEditedItem ()
void searchReplace (const QString &szSearch, bool bReplace=false, const QString &szReplace="n")
Protected Attributes
KviPointerList
< AliasEditorTreeWidgetItem > * m_pAliases
Constructor & Destructor Documentation
AliasEditorWidget::AliasEditorWidget (QWidget * par)
References __tr2qs_ctx(), connect(), KviScriptEditor::createInstance(), currentItemChanged(), l, m_bSaving, m_pAliases, m_pContextPopup, m_pEditor, m_pLastClickedItem, m_pLastEditedItem, m_pNameLabel, m_pRenameButton, m_pSplitter, m_pTreeWidget, m_szDir, oneTimeSetup(), renameItem(), KviPointerList< T >::setAutoDelete(), KviTalHBox::setMargin(), KviTalVBox::setMargin(), KviTalHBox::setSpacing(), KviTalVBox::setSpacing(), KviTalHBox::setStretchFactor(), slotFindWord(), and slotReplaceAll().
AliasEditorWidget::~AliasEditorWidget ()
References KviScriptEditor::destroyInstance(), m_pAliases, and m_pEditor.
Member Function Documentation
void AliasEditorWidget::activateItem (QTreeWidgetItem * it) [protected]
References m_pTreeWidget, and openParentItems().
Referenced by loadProperties(), newItem(), and renameItem().
bool AliasEditorWidget::aliasExists (QString & szFullItemName) [protected]
References AliasEditorTreeWidgetItem::Alias, appendAllItems(), buildFullItemName(), KviQString::equalCI(), KviPointerList< T >::first(), l, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by renameItem().
void AliasEditorWidget::aliasRefresh (const QString & szName) [protected, slot]
References __tr2qs_ctx(), AliasEditorTreeWidgetItem::Alias, KviKvsAliasManager::aliasDict(), KviPointerList< T >::append(), appendAllItems(), buildFullItemName(), KviKvsScript::code(), createFullItem(), KviQString::equalCI(), KviControlCodes::Escape, KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), KviKvsAliasManager::instance(), l, m_bSaving, m_pAliases, m_pEditor, m_pLastEditedItem, KviPointerList< T >::next(), KviPointerList< T >::setAutoDelete(), AliasEditorTreeWidgetItem::setBuffer(), KviScriptEditor::setText(), and KviMessageBox::warning().
Referenced by oneTimeSetup().
void AliasEditorWidget::appendAllItems (KviPointerList< AliasEditorTreeWidgetItem > * l, AliasEditorTreeWidgetItem::Type eType) [protected]
References KviPointerList< T >::append(), appendAllItemsRecursive(), i, m_pTreeWidget, and KviOsInfo::type().
Referenced by aliasExists(), aliasRefresh(), and namespaceExists().
void AliasEditorWidget::appendAllItemsRecursive (KviPointerList< AliasEditorTreeWidgetItem > * l, QTreeWidgetItem * pStartFrom, AliasEditorTreeWidgetItem::Type eType) [protected]
References KviPointerList< T >::append(), i, and KviOsInfo::type().
Referenced by appendAllItems().
void AliasEditorWidget::appendSelectedAliasItems (KviPointerList< AliasEditorTreeWidgetItem > * l) [protected]
References KviPointerList< T >::append(), appendSelectedAliasItemsRecursive(), KviPointerList< T >::at(), i, and m_pTreeWidget.
Referenced by exportAliases().
void AliasEditorWidget::appendSelectedAliasItemsRecursive (KviPointerList< AliasEditorTreeWidgetItem > * l, QTreeWidgetItem * pStartFrom) [protected]
References KviPointerList< T >::append(), and i.
Referenced by appendSelectedAliasItems(), and appendSelectedItemsRecursive().
void AliasEditorWidget::appendSelectedItems (KviPointerList< AliasEditorTreeWidgetItem > * l) [protected]
References KviPointerList< T >::append(), i, and m_pTreeWidget.
Referenced by removeSelectedItems().
void AliasEditorWidget::appendSelectedItemsRecursive (KviPointerList< AliasEditorTreeWidgetItem > * l, QTreeWidgetItem * pStartFrom) [protected]
References KviPointerList< T >::append(), appendSelectedAliasItemsRecursive(), and i.
QString AliasEditorWidget::askForAliasName (const QString & szAction, const QString & szText, const QString & szInitialText) [protected]
References __tr2qs_ctx(), KviMessageBox::information(), KviModule::lock(), Normal, KviModule::unlock(), and KviMessageBox::warning().
Referenced by newAlias(), and renameItem().
QString AliasEditorWidget::askForNamespaceName (const QString & szAction, const QString & szText, const QString & szInitialText) [protected]
References __tr2qs_ctx(), KviMessageBox::information(), KviModule::lock(), Normal, KviModule::unlock(), and KviMessageBox::warning().
Referenced by newNamespace(), and renameItem().
void AliasEditorWidget::buildAliasesFile (KviPointerList< AliasEditorTreeWidgetItem > * l, QString & szBuffer) [protected]
References KviPointerList< T >::first(), getExportAliasBuffer(), and KviPointerList< T >::next().
Referenced by exportAliases().
QString AliasEditorWidget::buildFullItemName (AliasEditorTreeWidgetItem * it) [protected]
References AliasEditorTreeWidgetItem::name(), and AliasEditorTreeWidgetItem::parentItem().
Referenced by aliasExists(), aliasRefresh(), commit(), currentItemChanged(), exportAliases(), exportSelectionInSinglesFiles(), getExportAliasBuffer(), itemRenamed(), namespaceExists(), renameItem(), and saveProperties().
void AliasEditorWidget::buildFullItemPath (AliasEditorTreeWidgetItem * it, QString & szBuffer) [protected]
References AliasEditorTreeWidgetItem::isAlias(), AliasEditorTreeWidgetItem::name(), and AliasEditorTreeWidgetItem::parentItem().
Referenced by newItem().
void AliasEditorWidget::commit (void)
References a, KviKvsAliasManager::add(), KviPointerList< T >::at(), AliasEditorTreeWidgetItem::buffer(), buildFullItemName(), KviKvsAliasManager::clear(), KviPointerList< T >::count(), g_pApp, i, KviKvsAliasManager::instance(), m_bSaving, m_pAliases, KviApplication::saveAliases(), and saveLastEditedItem().
Referenced by AliasEditorWindow::applyClicked(), and AliasEditorWindow::okClicked().
AliasEditorTreeWidgetItem * AliasEditorWidget::createFullItem (const QString & szFullName) [protected]
References AliasEditorTreeWidgetItem::Alias, KviQString::equalCI(), findTopLevelItem(), i, j, m_pTreeWidget, and AliasEditorTreeWidgetItem::Namespace.
Referenced by aliasRefresh(), newItem(), oneTimeSetup(), and renameItem().
void AliasEditorWidget::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem *) [protected, slot]
References __tr2qs_ctx(), buildFullItemName(), AliasEditorTreeWidgetItem::isNamespace(), m_pEditor, m_pLastEditedItem, m_pNameLabel, m_pRenameButton, m_pTreeWidget, saveLastEditedItem(), KviScriptEditor::setCursorPosition(), and KviScriptEditor::setText().
Referenced by AliasEditorWidget(), and oneTimeSetup().
void AliasEditorWidget::customContextMenuRequested (const QPoint pnt) [protected, slot]
References __tr2qs_ctx(), KviIconManager::Alias, KviTalPopupMenu::clear(), exportAll(), exportSelected(), exportSelectedSepFiles(), KviIconManager::Folder, g_pIconManager, KviIconManager::getSmallIcon(), hasSelectedItems(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), m_pContextPopup, m_pLastClickedItem, m_pTreeWidget, KviIconManager::NameSpace, newAlias(), newNamespace(), KviIconManager::Quit, removeSelectedItems(), KviIconManager::Search, KviTalPopupMenu::setItemEnabled(), slotCollapseNamespaces(), and slotFind().
Referenced by oneTimeSetup().
void AliasEditorWidget::exportAliases (bool bSelectedOnly, bool bSingleFiles = false)
References __tr2qs_ctx(), appendSelectedAliasItems(), KviFileDialog::askForSaveFileName(), KviPointerList< T >::at(), buildAliasesFile(), buildFullItemName(), KviPointerList< T >::count(), exportSelectionInSinglesFiles(), KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, l, KviModule::lock(), m_pAliases, m_szDir, saveLastEditedItem(), KviPointerList< T >::setAutoDelete(), KviModule::unlock(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by exportAll(), exportSelected(), and exportSelectedSepFiles().
void AliasEditorWidget::exportAll () [protected, slot]
References exportAliases().
Referenced by customContextMenuRequested().
void AliasEditorWidget::exportSelected () [protected, slot]
References exportAliases().
Referenced by customContextMenuRequested().
void AliasEditorWidget::exportSelectedSepFiles () [protected, slot]
References exportAliases().
Referenced by customContextMenuRequested().
void AliasEditorWidget::exportSelectionInSinglesFiles (KviPointerList< AliasEditorTreeWidgetItem > * l)
References __tr2qs_ctx(), KviFileDialog::askForDirectoryName(), buildFullItemName(), KviFileUtils::fileExists(), KviPointerList< T >::first(), getExportAliasBuffer(), KVI_PATH_SEPARATOR, KviModule::lock(), m_szDir, KviPointerList< T >::next(), KviModule::unlock(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by exportAliases().
AliasEditorTreeWidgetItem * AliasEditorWidget::findItem (const QString & szName) [protected]
References KviQString::equalCI(), findTopLevelItem(), i, and j.
Referenced by loadProperties(), and newItem().
AliasEditorTreeWidgetItem * AliasEditorWidget::findTopLevelItem (const QString & szName) [protected]
References i, AliasEditorTreeWidgetItem::isNamespace(), and m_pTreeWidget.
Referenced by createFullItem(), and findItem().
void AliasEditorWidget::getExportAliasBuffer (QString & buffer, AliasEditorTreeWidgetItem * it) [protected]
References KviCommandFormatter::blockFromBuffer(), AliasEditorTreeWidgetItem::buffer(), and buildFullItemName().
Referenced by buildAliasesFile(), and exportSelectionInSinglesFiles().
void AliasEditorWidget::getUniqueItemName (AliasEditorTreeWidgetItem * item, QString & buffer, AliasEditorTreeWidgetItem::Type eType) [protected]
bool AliasEditorWidget::hasSelectedItems () [protected]
References m_pTreeWidget.
Referenced by customContextMenuRequested().
bool AliasEditorWidget::itemExists (QTreeWidgetItem * pSearchFor) [protected]
References KviPointerList< T >::findRef(), and m_pAliases.
Referenced by newItem(), and saveLastEditedItem().
void AliasEditorWidget::itemRenamed (QTreeWidgetItem * it, int col) [protected, slot]
References __tr2qs_ctx(), buildFullItemName(), m_pLastEditedItem, and m_pNameLabel.
Referenced by oneTimeSetup().
void AliasEditorWidget::loadProperties (KviConfigurationFile * cfg)
References activateItem(), findItem(), m_pSplitter, KviConfigurationFile::readEntry(), and KviConfigurationFile::readIntListEntry().
Referenced by AliasEditorWindow::loadProperties().
bool AliasEditorWidget::namespaceExists (QString & szFullItemName) [protected]
References appendAllItems(), buildFullItemName(), KviQString::equalCI(), KviPointerList< T >::first(), l, AliasEditorTreeWidgetItem::Namespace, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by renameItem().
void AliasEditorWidget::newAlias () [protected, slot]
References __tr2qs_ctx(), AliasEditorTreeWidgetItem::Alias, askForAliasName(), and newItem().
Referenced by customContextMenuRequested().
void AliasEditorWidget::newItem (QString & szName, AliasEditorTreeWidgetItem::Type eType) [protected, slot]
References activateItem(), KviPointerList< T >::append(), buildFullItemPath(), createFullItem(), findItem(), itemExists(), m_pAliases, m_pLastClickedItem, and AliasEditorTreeWidgetItem::setType().
Referenced by newAlias(), and newNamespace().
void AliasEditorWidget::newNamespace () [protected, slot]
References __tr2qs_ctx(), askForNamespaceName(), AliasEditorTreeWidgetItem::Namespace, and newItem().
Referenced by customContextMenuRequested().
void AliasEditorWidget::oneTimeSetup () [protected]
References a, KviKvsAliasManager::aliasDict(), aliasRefresh(), KviPointerList< T >::append(), KviKvsScript::code(), connect(), createFullItem(), KviPointerHashTableIterator< Key, T >::current(), currentItemChanged(), customContextMenuRequested(), KviKvsAliasManager::instance(), itemRenamed(), m_pAliases, m_pTreeWidget, KviKvsScript::name(), and AliasEditorTreeWidgetItem::setBuffer().
Referenced by AliasEditorWidget().
void AliasEditorWidget::openParentItems (QTreeWidgetItem * it) [protected]
Referenced by activateItem(), and searchReplace().
void AliasEditorWidget::recursiveCollapseNamespaces (AliasEditorTreeWidgetItem * it) [protected]
References i.
Referenced by slotCollapseNamespaces().
bool AliasEditorWidget::removeItem (AliasEditorTreeWidgetItem * it, bool * pbYesToAll, bool bDeleteEmptyTree) [protected]
References __tr2qs_ctx(), AliasEditorTreeWidgetItem::isAlias(), KviModule::lock(), m_pAliases, m_pLastClickedItem, m_pLastEditedItem, AliasEditorTreeWidgetItem::name(), removeItemChildren(), KviPointerList< T >::removeRef(), and KviModule::unlock().
Referenced by removeSelectedItems(), and renameItem().
void AliasEditorWidget::removeItemChildren (AliasEditorTreeWidgetItem * it) [protected]
References m_pAliases, and KviPointerList< T >::removeRef().
Referenced by removeItem().
void AliasEditorWidget::removeSelectedItems () [protected, slot]
References appendSelectedItems(), KviPointerList< T >::first(), l, KviPointerList< T >::next(), removeItem(), and KviPointerList< T >::setAutoDelete().
Referenced by customContextMenuRequested().
void AliasEditorWidget::renameItem () [protected, slot]
References __tr2qs_ctx(), activateItem(), aliasExists(), KviPointerList< T >::append(), askForAliasName(), askForNamespaceName(), buildFullItemName(), createFullItem(), KviScriptEditor::getCursor(), KviScriptEditor::getText(), i, KviMessageBox::information(), AliasEditorTreeWidgetItem::isAlias(), KviModule::lock(), m_pAliases, m_pEditor, m_pLastClickedItem, m_pLastEditedItem, namespaceExists(), removeItem(), AliasEditorTreeWidgetItem::setBuffer(), AliasEditorTreeWidgetItem::setCursorPosition(), and KviModule::unlock().
Referenced by AliasEditorWidget().
void AliasEditorWidget::saveLastEditedItem () [protected]
References KviScriptEditor::getCursor(), KviScriptEditor::getText(), KviScriptEditor::isModified(), AliasEditorTreeWidgetItem::isNamespace(), itemExists(), m_pEditor, and m_pLastEditedItem.
Referenced by commit(), currentItemChanged(), and exportAliases().
void AliasEditorWidget::saveProperties (KviConfigurationFile * cfg)
References buildFullItemName(), m_pLastEditedItem, m_pSplitter, and KviConfigurationFile::writeEntry().
Referenced by AliasEditorWindow::saveProperties().
void AliasEditorWidget::searchReplace (const QString & szSearch, bool bReplace = false, const QString & szReplace = "n") [protected]
References KviPointerList< T >::at(), AliasEditorTreeWidgetItem::buffer(), KviPointerList< T >::count(), i, m_pAliases, and openParentItems().
Referenced by slotFind(), and slotReplaceAll().
void AliasEditorWidget::slotCollapseNamespaces () [protected, slot]
References i, m_pTreeWidget, and recursiveCollapseNamespaces().
Referenced by customContextMenuRequested().
void AliasEditorWidget::slotFind () [protected, slot]
References __tr2qs_ctx(), KviModule::lock(), m_pEditor, Normal, searchReplace(), KviScriptEditor::setFindText(), and KviModule::unlock().
Referenced by customContextMenuRequested().
void AliasEditorWidget::slotFindWord (const QString & szSearch) [protected, slot]
References m_pEditor, and KviScriptEditor::setFindText().
Referenced by AliasEditorWidget().
void AliasEditorWidget::slotReplaceAll (const QString & before, const QString & after) [protected, slot]
References m_pEditor, searchReplace(), and KviScriptEditor::setFindText().
Referenced by AliasEditorWidget().
static void AliasEditorWidget::splitFullAliasOrNamespaceName (const QString & szFullName, QStringList & lNamespaces, QString & szName) [static]
Member Data Documentation
bool AliasEditorWidget::m_bSaving
Referenced by AliasEditorWidget(), aliasRefresh(), and commit().
KviPointerList<AliasEditorTreeWidgetItem>* AliasEditorWidget::m_pAliases [protected]
Referenced by AliasEditorWidget(), aliasRefresh(), commit(), exportAliases(), itemExists(), newItem(), oneTimeSetup(), removeItem(), removeItemChildren(), renameItem(), searchReplace(), and ~AliasEditorWidget().
KviTalPopupMenu* AliasEditorWidget::m_pContextPopup
Referenced by AliasEditorWidget(), and customContextMenuRequested().
KviScriptEditor* AliasEditorWidget::m_pEditor
Referenced by AliasEditorWidget(), aliasRefresh(), currentItemChanged(), renameItem(), saveLastEditedItem(), slotFind(), slotFindWord(), slotReplaceAll(), and ~AliasEditorWidget().
AliasEditorTreeWidgetItem* AliasEditorWidget::m_pLastClickedItem
Referenced by AliasEditorWidget(), customContextMenuRequested(), newItem(), removeItem(), and renameItem().
AliasEditorTreeWidgetItem* AliasEditorWidget::m_pLastEditedItem
Referenced by AliasEditorWidget(), aliasRefresh(), currentItemChanged(), itemRenamed(), removeItem(), renameItem(), saveLastEditedItem(), and saveProperties().
QLabel* AliasEditorWidget::m_pNameLabel
Referenced by AliasEditorWidget(), currentItemChanged(), and itemRenamed().
QPushButton* AliasEditorWidget::m_pRenameButton
Referenced by AliasEditorWidget(), and currentItemChanged().
QSplitter* AliasEditorWidget::m_pSplitter
Referenced by AliasEditorWidget(), loadProperties(), and saveProperties().
AliasEditorTreeWidget* AliasEditorWidget::m_pTreeWidget
Referenced by activateItem(), AliasEditorWidget(), appendAllItems(), appendSelectedAliasItems(), appendSelectedItems(), createFullItem(), currentItemChanged(), customContextMenuRequested(), findTopLevelItem(), hasSelectedItems(), oneTimeSetup(), and slotCollapseNamespaces().
QString AliasEditorWidget::m_szDir
Referenced by AliasEditorWidget(), exportAliases(), and exportSelectionInSinglesFiles().
The documentation for this class was generated from the following files:
src/modules/aliaseditor/AliasEditorWindow.h
src/modules/aliaseditor/AliasEditorWindow.cpp