KVIrc: KviColorSelector Class Reference
KviColorSelector Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
virtual void commit ()
void forceColor (QColor clr)
QColor getColor ()
KviColorSelector (QWidget *par, const QString &txt, QColor *pOption, bool bEnabled)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviColorSelector ()
Private Slots
void changeClicked ()
Private Member Functions
void setButtonPalette (QColor *pOption)
Private Attributes
QColor m_memColor
QPushButton * m_pButton
QLabel * m_pLabel
QColor * m_pOption
Constructor & Destructor Documentation
KviColorSelector::KviColorSelector (QWidget * par, const QString & txt, QColor * pOption, bool bEnabled)
References changeClicked(), connect(), m_pButton, m_pLabel, m_pOption, setButtonPalette(), setEnabled(), KviTalHBox::setSpacing(), and KviTalHBox::setStretchFactor().
KviColorSelector::~KviColorSelector () [inline]
Member Function Documentation
void KviColorSelector::changeClicked () [private, slot]
References __tr2qs, getColor(), m_memColor, and setButtonPalette().
Referenced by KviColorSelector().
void KviColorSelector::commit (void) [virtual]
Reimplemented from KviSelectorInterface.
References m_memColor, and m_pOption.
void KviColorSelector::forceColor (QColor clr)
References setButtonPalette().
QColor KviColorSelector::getColor () [inline]
Referenced by changeClicked(), and RegisteredUserEntryDialog::okClicked().
void KviColorSelector::setButtonPalette (QColor * pOption) [private]
References m_memColor, and m_pButton.
Referenced by changeClicked(), forceColor(), and KviColorSelector().
void KviColorSelector::setEnabled (bool bEnabled) [virtual, slot]
References m_pButton, and m_pLabel.
Referenced by KviColorSelector().
QString KviColorSelector::textForSearch () [inline, virtual]
Reimplemented from KviSelectorInterface.
QWidget* KviColorSelector::widgetToHighlight () [inline, virtual]
Reimplemented from KviSelectorInterface.
Member Data Documentation
QColor KviColorSelector::m_memColor [private]
Referenced by changeClicked(), commit(), and setButtonPalette().
QPushButton* KviColorSelector::m_pButton [private]
Referenced by KviColorSelector(), setButtonPalette(), and setEnabled().
QLabel* KviColorSelector::m_pLabel [private]
Referenced by KviColorSelector(), and setEnabled().
QColor* KviColorSelector::m_pOption [private]
Referenced by commit(), and KviColorSelector().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp