KVIrc: DccThread Class Reference
DccThread Class Reference
#include <DccThread.h>
Public Member Functions
DccThread (QObject *par, kvi_socket_t fd)
QObject * parent ()
void postErrorEvent (int err)
void postMessageEvent (const char *message)
~DccThread ()
Public Member Functions inherited from KviSensitiveThread
void enqueueEvent (KviThreadEvent *e)
KviSensitiveThread ()
void terminate ()
virtual ~KviSensitiveThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
bool handleInvalidSocketRead (int readLen)
Protected Member Functions inherited from KviSensitiveThread
KviThreadEvent * dequeueEvent ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
virtual void run ()
Protected Attributes
kvi_socket_t m_fd
KviMutex * m_pMutex
QObject * m_pParent
Protected Attributes inherited from KviSensitiveThread
KviPointerList< KviThreadEvent > * m_pLocalEventQueue
KviMutex * m_pLocalEventQueueMutex
Additional Inherited Members
Static Public Member Functions inherited from KviThread
static void msleep (unsigned long msec)
static void sleep (unsigned long sec)
static void usleep (unsigned long usec)
Constructor & Destructor Documentation
DccThread::DccThread (QObject * par, kvi_socket_t fd)
References m_fd, m_pMutex, and m_pParent.
DccThread::~DccThread ()
References KVI_ASSERT, KVI_INVALID_SOCKET, kvi_socket_close, KviMutex::locked(), m_fd, and m_pMutex.
Member Function Documentation
bool DccThread::handleInvalidSocketRead (int readLen) protected
References KVI_ASSERT, kvi_socket_error(), postErrorEvent(), KviError::RemoteEndClosedConnection, and KviError::translateSystemError().
Referenced by DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), DccChatThread::run(), DccSendThread::run(), and DccRecvThread::run().
QObject* DccThread::parent () inline
References m_pParent.
Referenced by DccChatThread::handleIncomingData(), DccVideoThread::handleIncomingData(), DccRecvThread::postMessageEvent(), DccSendThread::run(), DccRecvThread::run(), DccVideoThread::startPlaying(), DccVoiceThread::startPlaying(), DccVideoThread::startRecording(), DccVoiceThread::startRecording(), DccVideoThread::stopPlaying(), DccVoiceThread::stopPlaying(), DccVideoThread::stopRecording(), DccVoiceThread::stopRecording(), DccVideoThread::textStep(), and DccVideoThread::videoStep().
void DccThread::postErrorEvent (int err)
References e, KVI_DCC_THREAD_EVENT_ERROR, m_pParent, KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by handleInvalidSocketRead(), DccChatThread::run(), DccSendThread::run(), DccRecvThread::run(), DccRecvThread::sendAck(), and DccChatThread::tryFlushOutBuffers().
void DccThread::postMessageEvent (const char * message)
References e, KVI_DCC_THREAD_EVENT_MESSAGE, m_pParent, KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by DccVoiceThread::checkSoundcard(), DccVoiceThread::openSoundcard(), and DccVoiceThread::openSoundcardWithDuplexOption().
Member Data Documentation
kvi_socket_t DccThread::m_fd protected
Referenced by DccThread(), DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), DccChatThread::run(), DccSendThread::run(), DccVideoThread::run(), DccVoiceThread::run(), DccRecvThread::run(), DccRecvThread::sendAck(), DccChatThread::tryFlushOutBuffers(), and ~DccThread().
KviMutex* DccThread::m_pMutex protected
Referenced by DccThread(), DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), DccSendThread::run(), DccRecvThread::run(), DccChatThread::sendRawData(), DccChatThread::tryFlushOutBuffers(), DccSendThread::updateStats(), DccRecvThread::updateStats(), and ~DccThread().
QObject* DccThread::m_pParent protected
Referenced by DccThread(), parent(), postErrorEvent(), and postMessageEvent().
The documentation for this class was generated from the following files:
src/modules/dcc/DccThread.h
src/modules/dcc/DccThread.cpp