KVIrc: OptionsWidget_avatar Class Reference
OptionsWidget_avatar Class Reference
#include <OptionsWidget_avatar.h>
Public Member Functions
OptionsWidget_avatar (QWidget *parent)
~OptionsWidget_avatar ()
Constructor & Destructor Documentation
OptionsWidget_avatar::OptionsWidget_avatar (QWidget * parent)
References __tr2qs_ctx(), KviTalToolTip::add(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolAutoAcceptIncomingAvatars, KviOption_boolDoNotUpscaleAvatars, KviOption_boolIgnoreChannelAvatarRequestsWhenNoAvatarSet, KviOption_boolRequestMissingAvatars, KviOption_boolScaleAvatars, KviOption_boolScaleAvatarsOnLoad, KviOption_boolSetLastAvatarAsDefaultForRegisteredUsers, KviOption_uintAvatarOfferTimeoutInSecs, KviOption_uintAvatarScaleHeight, KviOption_uintAvatarScaleWidth, KviOption_uintMaximumRequestedAvatarSize, KviOption_uintScaleAvatarsOnLoadHeight, KviOption_uintScaleAvatarsOnLoadWidth, KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_avatar::~OptionsWidget_avatar ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_avatar.h
src/modules/options/OptionsWidget_avatar.cpp