KVIrc: OptionsWidget_highlighting Class Reference
OptionsWidget_highlighting Class Reference
#include <OptionsWidget_alertsAndHighlighting.h>
Public Member Functions
OptionsWidget_highlighting (QWidget *parent)
~OptionsWidget_highlighting ()
Protected Member Functions
virtual void commit ()
Private Attributes
QRadioButton * m_pHighlightAllOccurencesRadioButton
QRadioButton * m_pHighlightWholeWordsOnlyRadioButton
QLineEdit * m_pWordSplitterCharactersEdit
Constructor & Destructor Documentation
OptionsWidget_highlighting::OptionsWidget_highlighting (QWidget * parent)
References __tr2qs_ctx(), KviTalToolTip::add(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringListSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolAlwaysHighlightNick, KviOption_boolCaseSensitiveHighlighting, KviOption_boolFlashWindowOnHighlightedMessages, KviOption_boolPopupNotifierOnHighlightedMessages, KviOption_boolUseFullWordHighlighting, KviOption_boolUseWordHighlighting, KviOption_stringlistHighlightWords, KviOption_stringWordSplitters, m_pHighlightAllOccurencesRadioButton, m_pHighlightWholeWordsOnlyRadioButton, m_pWordSplitterCharactersEdit, KviOptionsWidget::mergeTip(), and KviTalGroupBox::setLayout().
OptionsWidget_highlighting::~OptionsWidget_highlighting ()
Member Function Documentation
void OptionsWidget_highlighting::commit (void) [protected, virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseFullWordHighlighting, KviOption_stringWordSplitters, m_pHighlightAllOccurencesRadioButton, and m_pWordSplitterCharactersEdit.
Member Data Documentation
QRadioButton* OptionsWidget_highlighting::m_pHighlightAllOccurencesRadioButton [private]
Referenced by commit(), and OptionsWidget_highlighting().
QRadioButton* OptionsWidget_highlighting::m_pHighlightWholeWordsOnlyRadioButton [private]
Referenced by OptionsWidget_highlighting().
QLineEdit* OptionsWidget_highlighting::m_pWordSplitterCharactersEdit [private]
Referenced by commit(), and OptionsWidget_highlighting().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_alertsAndHighlighting.h
src/modules/options/OptionsWidget_alertsAndHighlighting.cpp