KVIrc: KviIrcViewToolTip Class Reference
KviIrcViewToolTip Class Reference
#include <KviIrcView_tools.h>
Public Member Functions
void doTip (const QRect &rct, const QString &str)
KviIrcViewToolTip (KviIrcView *pView)
virtual ~KviIrcViewToolTip ()
Public Member Functions inherited from KviTalToolTip
KviTalToolTip (QWidget *pParent)
virtual void tip (const QRect &rect, const QString &text)
virtual ~KviTalToolTip ()
Protected Member Functions
virtual void maybeTip (const QPoint &pnt)
Protected Member Functions inherited from KviTalToolTip
void helperDying ()
Protected Attributes
KviIrcView * m_pView
Protected Attributes inherited from KviTalToolTip
KviTalToolTipHelper * m_pHelper
QWidget * m_pParent
Additional Inherited Members
Static Public Member Functions inherited from KviTalToolTip
static void add (QWidget *widget, const QString &text)
static void remove (QWidget *widget)
Constructor & Destructor Documentation
KviIrcViewToolTip::KviIrcViewToolTip (KviIrcView * pView)
References m_pView.
KviIrcViewToolTip::~KviIrcViewToolTip () virtual
Member Function Documentation
void KviIrcViewToolTip::doTip (const QRect & rct, const QString & str) inline
References KviTalToolTip::tip().
Referenced by KviIrcView::doLinkToolTip(), and KviIrcView::doMarkerToolTip().
void KviIrcViewToolTip::maybeTip (const QPoint & pnt) protected virtual
Reimplemented from KviTalToolTip.
References m_pView, and KviIrcView::maybeTip().
Member Data Documentation
KviIrcView* KviIrcViewToolTip::m_pView protected
Referenced by KviIrcViewToolTip(), and maybeTip().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviIrcView_tools.h
src/kvirc/ui/KviIrcView_tools.cpp