KVIrc: KviStringSelector Class Reference
KviStringSelector Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
virtual void commit ()
KviStringSelector (QWidget *par, const QString &txt, QString *pOption, bool bEnabled)
void setMinimumLabelWidth (unsigned int uWidth)
void setText (const QString &text)
void setValidator (QValidator *v)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviStringSelector ()
Public Member Functions inherited from KviTalHBox
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual ~KviSelectorInterface ()
Protected Attributes
QLabel * m_pLabel
QLineEdit * m_pLineEdit
QString * m_pOption
Additional Inherited Members
Protected Member Functions inherited from KviTalHBox
virtual void childEvent (QChildEvent *e)
Constructor & Destructor Documentation
KviStringSelector::KviStringSelector (QWidget * par, const QString & txt, QString * pOption, bool bEnabled)
References m_pLabel, m_pLineEdit, m_pOption, setEnabled(), KviTalHBox::setSpacing(), and KviTalHBox::setStretchFactor().
KviStringSelector::~KviStringSelector ()
Member Function Documentation
void KviStringSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pLineEdit, and m_pOption.
Referenced by SetupWizard::accept().
void KviStringSelector::setEnabled (bool bEnabled) virtual slot
References m_pLabel, and m_pLineEdit.
Referenced by OptionsWidget_away::enableAwayMessage(), OptionsWidget_away::enableCustomAwayText(), KviStringSelector(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), and OptionsWidget_urlHandlers::toggleEditors().
void KviStringSelector::setMinimumLabelWidth (unsigned int uWidth) inline
Referenced by KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), and SetupWizard::SetupWizard().
void KviStringSelector::setText (const QString & text)
References m_pLineEdit.
Referenced by SetupWizard::SetupWizard().
void KviStringSelector::setValidator (QValidator * v) inline
Referenced by KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), and SetupWizard::SetupWizard().
QString KviStringSelector::textForSearch () inline virtual
Reimplemented from KviSelectorInterface.
QWidget* KviStringSelector::widgetToHighlight () inline virtual
Reimplemented from KviSelectorInterface.
Member Data Documentation
QLabel* KviStringSelector::m_pLabel protected
Referenced by KviStringSelector(), and setEnabled().
QLineEdit* KviStringSelector::m_pLineEdit protected
Referenced by commit(), KviStringSelector(), setEnabled(), and setText().
QString* KviStringSelector::m_pOption protected
Referenced by commit(), and KviStringSelector().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp