KVIrc: EventEditorTreeWidget Class Reference
EventEditorTreeWidget Class Reference
#include <EventEditorWindow.h>
Signals
void rightButtonPressed (QTreeWidgetItem *, QPoint)
Public Member Functions
EventEditorTreeWidget (QWidget *)
~EventEditorTreeWidget ()
Protected Member Functions
void mousePressEvent (QMouseEvent *e)
Constructor & Destructor Documentation
EventEditorTreeWidget::EventEditorTreeWidget (QWidget * par)
References __tr2qs_ctx().
EventEditorTreeWidget::~EventEditorTreeWidget () [inline]
Member Function Documentation
void EventEditorTreeWidget::mousePressEvent (QMouseEvent * e) [protected]
References i, and rightButtonPressed().
void EventEditorTreeWidget::rightButtonPressed (QTreeWidgetItem * , QPoint) [signal]
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
src/modules/eventeditor/EventEditorWindow.h
src/modules/eventeditor/EventEditorWindow.cpp