KVIrc: KviIpcSentinel Class Reference
KviIpcSentinel Class Reference
COMPILE_X11_SUPPORT.
#include <KviIpcSentinel.h>
Public Member Functions
KviIpcSentinel ()
~KviIpcSentinel ()
Detailed Description
COMPILE_X11_SUPPORT.
Constructor & Destructor Documentation
KviIpcSentinel::KviIpcSentinel ()
COMPILE_NO_X
References KviCString::len(), KviMemory::move(), and KviCString::ptr().
KviIpcSentinel::~KviIpcSentinel ()
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIpcSentinel.h
src/kvirc/kernel/KviIpcSentinel.cpp