KVIrc: KviKvsObjectClass Class Reference
KviKvsObjectClass Class Reference
#include <KviKvsObjectClass.h>
Public Member Functions
KviKvsObject * allocateInstance (KviKvsObject *pParent, const QString &szName, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
void clearDirtyFlag ()
void getFunctionCode (QString &szCode, KviKvsObjectFunctionHandler &h)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * getHandlers ()
bool isBuiltin ()
bool isDirty ()
bool isScriptHandler (const QString &szFunctionName)
KviKvsObjectClass (KviKvsObjectClass *pParent, const QString &szName, KviKvsObjectAllocateInstanceProc proc, bool bBuiltin=true)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &szFunc)
const QString & name ()
KviKvsObjectClass * parentClass ()
void registerFunctionHandler (const QString &szFunctionName, KviKvsObjectFunctionHandlerProc pProc, unsigned int uFlags=0)
void registerFunctionHandler (const QString &szFunctionName, const QString &szBuffer, const QString &szReminder, unsigned int uFlags=0)
void registerStandardFalseReturnFunctionHandler (const QString &szFunc)
void registerStandardNothingReturnFunctionHandler (const QString &szFunc)
void registerStandardTrueReturnFunctionHandler (const QString &szFunc)
QString reminder (KviKvsObjectFunctionHandler *h)
bool save (const QString &szFileName)
void setReminder (const QString &szReminder, KviKvsObjectFunctionHandler *h)
~KviKvsObjectClass ()
Static Public Member Functions
static bool load (const QString &szFileName)
Protected Member Functions
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
void registerChildClass (KviKvsObjectClass *pClass)
void unregisterChildClass (KviKvsObjectClass *pClass)
Protected Attributes
KviKvsObjectAllocateInstanceProc m_allocProc
bool m_bBuiltin
bool m_bDirty
KviPointerList
< KviKvsObjectClass > * m_pChildClasses
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
KviKvsObjectClass * m_pParentClass
QString m_szName
Friends
class KviKvsObject
class KviKvsObjectController
Constructor & Destructor Documentation
KviKvsObjectClass::KviKvsObjectClass (KviKvsObjectClass * pParent, const QString & szName, KviKvsObjectAllocateInstanceProc proc, bool bBuiltin = true)
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), f, KviPointerHashTable< Key, T >::find(), functionHandlers(), KviPointerHashTable< Key, T >::insert(), KviKvsKernel::instance(), KviKvsObjectFunctionHandler::isScriptHandler(), m_allocProc, m_bBuiltin, m_bDirty, m_pChildClasses, m_pFunctionHandlers, m_pParentClass, m_szName, KviKvsKernel::objectController(), registerChildClass(), KviKvsObjectController::registerClass(), KviPointerList< T >::setAutoDelete(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviKvsObjectFunctionHandler::setClone().
KviKvsObjectClass::~KviKvsObjectClass ()
References KviPointerList< T >::first(), KviKvsKernel::instance(), KviKvsObjectController::killAllObjectsWithClass(), m_pChildClasses, m_pFunctionHandlers, m_pParentClass, KviKvsKernel::objectController(), unregisterChildClass(), and KviKvsObjectController::unregisterClass().
Member Function Documentation
KviKvsObject * KviKvsObjectClass::allocateInstance (KviKvsObject * pParent, const QString & szName, KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams)
References __tr2qs_ctx(), KviKvsVariantList::append(), KviKvsObject::callFunction(), KviMemory::copy(), KviKvsObject::dieNow(), KviKvsVariantList::first(), KviKvsObject::init(), KviKvsVariant::isEmpty(), m_allocProc, KviKvsVariantList::next(), KviKvsVariantList::setAutoDelete(), v, and KviKvsRunTimeContext::warning().
Referenced by KvsObject_widget::eventFilter(), KVSO_CLASS_FUNCTION(), KvsObject_tableWidget::paint(), and KvsObject_socket::slotNewConnection().
void KviKvsObjectClass::clearDirtyFlag () [inline]
Referenced by KviKvsObjectController::deleteClass(), and KviKvsObjectController::lookupClass().
KviPointerHashTable<QString,KviKvsObjectFunctionHandler>* KviKvsObjectClass::functionHandlers () [inline, protected]
Referenced by KviKvsObjectClass().
void KviKvsObjectClass::getFunctionCode (QString & szCode, KviKvsObjectFunctionHandler & h)
References KviKvsObjectFunctionHandler::scriptHandlerCode().
Referenced by ClassEditorWidget::createFullClass(), and objects_kvs_fnc_classAllHandlers().
KviPointerHashTable<QString,KviKvsObjectFunctionHandler>* KviKvsObjectClass::getHandlers () [inline]
Referenced by ClassEditorWidget::createFullClass(), and objects_kvs_fnc_classAllHandlers().
bool KviKvsObjectClass::isBuiltin () [inline]
Referenced by KviKvsObjectController::clearUserClasses(), KviClassEditorDialog::KviClassEditorDialog(), KviKvsObjectController::lookupClass(), objects_kvs_cmd_killClass(), ClassEditorWidget::oneTimeSetup(), save(), and KviKvsObjectController::unregisterClass().
bool KviKvsObjectClass::isDirty () [inline]
Referenced by KviKvsObjectController::unregisterClass().
bool KviKvsObjectClass::isScriptHandler (const QString & szFunctionName) [inline]
References KviKvsObjectFunctionHandler::isScriptHandler().
Referenced by ClassEditorWidget::createFullClass().
bool KviKvsObjectClass::load (const QString & szFileName) [static]
References g_pActiveWindow, KviFileUtils::readFile(), KviIrcUrl::run(), and szBuffer.
Referenced by KviKvsObjectController::lookupClass().
KviKvsObjectFunctionHandler* KviKvsObjectClass::lookupFunctionHandler (const QString & szFunc) [inline]
Referenced by ClassEditorWidget::createFullClass(), KviKvsObject::lookupFunctionHandler(), objects_kvs_fnc_classAllHandlers(), and ClassEditorWidget::renameFunction().
const QString& KviKvsObjectClass::name () [inline]
Referenced by ClassEditorWidget::createFullClass(), KviKvsObjectController::deleteClass(), KviKvsObject::emitSignal(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsObject::function_listProperties(), KviKvsObject::function_property(), KviKvsObject::function_setProperty(), KviKvsObject::getClass(), KviKvsObjectController::registerClass(), KviKvsObject::registerPrivateImplementation(), save(), and KviKvsObjectController::unregisterClass().
KviKvsObjectClass* KviKvsObjectClass::parentClass () [inline]
Referenced by ClassEditorWidget::createFullClass(), and KviKvsTreeNodeSpecialCommandClass::execute().
void KviKvsObjectClass::registerChildClass (KviKvsObjectClass * pClass) [protected]
References KviPointerList< T >::append(), and m_pChildClasses.
Referenced by KviKvsObjectClass().
void KviKvsObjectClass::registerFunctionHandler (const QString & szFunctionName, const QString & szBuffer, const QString & szReminder, unsigned int uFlags = 0)
References m_pFunctionHandlers, m_szName, and KviPointerHashTable< Key, T >::replace().
void KviKvsObjectClass::registerFunctionHandler (const QString & szFunctionName, KviKvsObjectFunctionHandlerProc pProc, unsigned int uFlags = 0)
References m_pFunctionHandlers, and KviPointerHashTable< Key, T >::replace().
Referenced by KviKvsTreeNodeSpecialCommandClass::execute(), and KviKvsObjectController::init().
void KviKvsObjectClass::registerStandardFalseReturnFunctionHandler (const QString & szFunc)
References m_pFunctionHandlers, and KviPointerHashTable< Key, T >::replace().
void KviKvsObjectClass::registerStandardNothingReturnFunctionHandler (const QString & szFunc)
References m_pFunctionHandlers, and KviPointerHashTable< Key, T >::replace().
Referenced by KviKvsObjectController::init().
void KviKvsObjectClass::registerStandardTrueReturnFunctionHandler (const QString & szFunc)
References m_pFunctionHandlers, and KviPointerHashTable< Key, T >::replace().
QString KviKvsObjectClass::reminder (KviKvsObjectFunctionHandler * h)
References KviKvsObjectFunctionHandler::reminder().
Referenced by ClassEditorWidget::createFullClass().
bool KviKvsObjectClass::save (const QString & szFileName)
References KviCommandFormatter::blockFromBuffer(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), h, KviCommandFormatter::indent(), KviKvsObjectFunctionHandler::Internal, isBuiltin(), m_pFunctionHandlers, m_pParentClass, m_szName, name(), szBuffer, and KviFileUtils::writeFile().
Referenced by ClassEditorWidget::renameFunction().
void KviKvsObjectClass::setReminder (const QString & szReminder, KviKvsObjectFunctionHandler * h)
References KviKvsObjectFunctionHandler::setReminder().
Referenced by ClassEditorWidget::renameFunction().
void KviKvsObjectClass::unregisterChildClass (KviKvsObjectClass * pClass) [protected]
References m_pChildClasses, and KviPointerList< T >::removeRef().
Referenced by ~KviKvsObjectClass().
Friends And Related Function Documentation
friend class KviKvsObject [friend]
friend class KviKvsObjectController [friend]
Member Data Documentation
KviKvsObjectAllocateInstanceProc KviKvsObjectClass::m_allocProc [protected]
Referenced by allocateInstance(), and KviKvsObjectClass().
bool KviKvsObjectClass::m_bBuiltin [protected]
Referenced by KviKvsObjectClass().
bool KviKvsObjectClass::m_bDirty [protected]
Referenced by KviKvsObjectClass().
KviPointerList<KviKvsObjectClass>* KviKvsObjectClass::m_pChildClasses [protected]
Referenced by KviKvsObjectClass(), registerChildClass(), unregisterChildClass(), and ~KviKvsObjectClass().
KviPointerHashTable<QString,KviKvsObjectFunctionHandler>* KviKvsObjectClass::m_pFunctionHandlers [protected]
Referenced by KviKvsObject::functionHandlers(), KviKvsObjectClass(), registerFunctionHandler(), registerStandardFalseReturnFunctionHandler(), registerStandardNothingReturnFunctionHandler(), registerStandardTrueReturnFunctionHandler(), save(), and ~KviKvsObjectClass().
KviKvsObjectClass* KviKvsObjectClass::m_pParentClass [protected]
Referenced by KviKvsObject::getClass(), KviKvsObject::inheritsClass(), KviKvsObjectClass(), save(), and ~KviKvsObjectClass().
QString KviKvsObjectClass::m_szName [protected]
Referenced by KviKvsObject::getName(), KviKvsObjectClass(), registerFunctionHandler(), and save().
The documentation for this class was generated from the following files:
src/kvirc/kvs/object/KviKvsObjectClass.h
src/kvirc/kvs/object/KviKvsObjectClass.cpp