KVIrc: KviKvsPopupMenuItem Class Reference
KviKvsPopupMenuItem Class Reference
#include <KviKvsPopupMenu.h>
Public Types
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Public Member Functions
virtual void clear ()
virtual KviKvsPopupMenuItem * clone () const =0
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)=0
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
virtual KviKvsScript * kvsCode ()
KviKvsScript * kvsCondition ()
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Protected Attributes
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Friends
class KviKvsPopupMenu
Member Enumeration Documentation
enum KviKvsPopupMenuItem::Type
Enumerator:
Item
Menu
Label
Separator
ExtMenu
Constructor & Destructor Documentation
KviKvsPopupMenuItem::KviKvsPopupMenuItem (Type t, const QString & szItemName, const QString & szCondition) [protected]
References KviKvsScript::Expression, m_eType, m_pKvsCondition, m_szItemName, and t().
KviKvsPopupMenuItem::KviKvsPopupMenuItem (Type t, const QString & szItemName, const KviKvsScript * pCondition) [protected]
References m_eType, m_pKvsCondition, m_szItemName, and t().
KviKvsPopupMenuItem::~KviKvsPopupMenuItem () [virtual]
References m_pKvsCondition.
Member Function Documentation
void KviKvsPopupMenuItem::clear () [virtual]
Reimplemented in KviKvsPopupMenuItemLabel, KviKvsPopupMenuItemMenu, and KviKvsPopupMenuItemExtMenu.
virtual KviKvsPopupMenuItem* KviKvsPopupMenuItem::clone () const [pure virtual]
Implemented in KviKvsPopupMenuItemSeparator, KviKvsPopupMenuItemLabel, KviKvsPopupMenuItemItem, KviKvsPopupMenuItemMenu, and KviKvsPopupMenuItemExtMenu.
bool KviKvsPopupMenuItem::evaluateCondition (KviKvsPopupMenuTopLevelData * pData)
References __tr2qs_ctx(), KviKvsVariant::asBoolean(), KviKvsPopupMenuTopLevelData::extendedRunTimeData(), KVI_OUT_PARSERWARNING, m_pKvsCondition, KviWindow::output(), KviKvsPopupMenuTopLevelData::parameters(), KviKvsScript::PreserveParams, KviKvsScript::run(), and KviKvsPopupMenuTopLevelData::window().
Referenced by KviKvsPopupMenuItemExtMenu::fill(), KviKvsPopupMenuItemMenu::fill(), KviKvsPopupMenuItemItem::fill(), KviKvsPopupMenuItemLabel::fill(), and KviKvsPopupMenuItemSeparator::fill().
virtual void KviKvsPopupMenuItem::fill (KviKvsPopupMenu * pMenu, KviKvsPopupMenuTopLevelData * pData, int iIdx) [pure virtual]
Implemented in KviKvsPopupMenuItemSeparator, KviKvsPopupMenuItemLabel, KviKvsPopupMenuItemItem, KviKvsPopupMenuItemMenu, and KviKvsPopupMenuItemExtMenu.
bool KviKvsPopupMenuItem::isExtMenu () [inline]
bool KviKvsPopupMenuItem::isItem () [inline]
Referenced by KviKvsPopupMenu::itemClicked().
bool KviKvsPopupMenuItem::isLabel () [inline]
bool KviKvsPopupMenuItem::isMenu () [inline]
bool KviKvsPopupMenuItem::isSeparator () [inline]
KviKvsScript * KviKvsPopupMenuItem::kvsCode () [virtual]
Reimplemented in KviKvsPopupMenuItemItem.
Referenced by SinglePopupEditor::findMatchingItem().
KviKvsScript* KviKvsPopupMenuItem::kvsCondition () [inline]
Referenced by SinglePopupEditor::findMatchingItem(), KviKvsPopupMenu::generateDefPopupCore(), and SinglePopupEditor::populateMenu().
KviKvsScript * KviKvsPopupMenuItem::kvsIcon () [virtual]
Reimplemented in KviKvsPopupMenuItemWithTextAndIcon.
Referenced by SinglePopupEditor::findMatchingItem().
KviKvsScript * KviKvsPopupMenuItem::kvsText () [virtual]
Reimplemented in KviKvsPopupMenuItemWithTextAndIcon.
Referenced by SinglePopupEditor::findMatchingItem().
const QString& KviKvsPopupMenuItem::name () [inline]
Referenced by SinglePopupEditor::findMatchingItem(), KviKvsPopupMenu::itemClicked(), and SinglePopupEditor::populateMenu().
KviKvsPopupMenuItem::Type KviKvsPopupMenuItem::type () [inline]
Referenced by SinglePopupEditor::findMatchingItem().
Friends And Related Function Documentation
friend class KviKvsPopupMenu [friend]
Reimplemented in KviKvsPopupMenuItemSeparator, KviKvsPopupMenuItemLabel, KviKvsPopupMenuItemItem, KviKvsPopupMenuItemMenu, and KviKvsPopupMenuItemExtMenu.
Member Data Documentation
Type KviKvsPopupMenuItem::m_eType [protected]
Referenced by KviKvsPopupMenuItem().
KviKvsScript* KviKvsPopupMenuItem::m_pKvsCondition [protected]
Referenced by KviKvsPopupMenuItemExtMenu::clone(), KviKvsPopupMenuItemMenu::clone(), KviKvsPopupMenuItemItem::clone(), KviKvsPopupMenuItemLabel::clone(), KviKvsPopupMenuItemSeparator::clone(), evaluateCondition(), KviKvsPopupMenuItem(), and ~KviKvsPopupMenuItem().
QString KviKvsPopupMenuItem::m_szItemName [protected]
Referenced by KviKvsPopupMenuItemExtMenu::clone(), KviKvsPopupMenuItemMenu::clone(), KviKvsPopupMenuItemItem::clone(), KviKvsPopupMenuItemLabel::clone(), KviKvsPopupMenuItemSeparator::clone(), and KviKvsPopupMenuItem().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp