KVIrc: UPnP::Service Class Reference
UPnP::Service Class Reference
#include <Service.h>
Signals
void queryFinished (bool error)
Public Member Functions
int getPendingRequests () const
Service (const ServiceParameters &params)
Service (const QString &hostname, int port, const QString &informationUrl)
virtual ~Service ()
Protected Member Functions
int callAction (const QString &actionName, const QString &prefix)
int callAction (const QString &actionName, const QMap< QString, QString > &arguments, const QString &prefix)
int callInformationUrl ()
virtual void gotActionErrorResponse (const QDomNode &response)
virtual void gotActionResponse (const QString &responseType, const QMap< QString, QString > &resultValues)
virtual void gotInformationResponse (const QDomNode &response)
Private Slots
void slotRequestFinished (int id, bool error)
Private Member Functions
int callActionInternal (const QString &actionName, const QMap< QString, QString > *arguments, const QString &prefix)
Private Attributes
int m_iPendingRequests
int m_iPort
QHttp * m_pHttp
QString m_szBaseXmlPrefix
QString m_szControlUrl
QString m_szHostname
QString m_szInformationUrl
QString m_szServiceId
QString m_szServiceType
Detailed Description
This base class to implement calls to a UPnP-enabled device. In UPnP terminology, a client is called a Control Point, and a service is a UPnP device.
This class different kind of calls. An information request queries the service for data with a HTTP GET. An action request issues a HTTP POST call to the given service.
Author:
Diederik van der Boor
Constructor & Destructor Documentation
UPnP::Service::Service (const QString & hostname, int port, const QString & informationUrl)
References connect(), m_pHttp, m_szInformationUrl, and slotRequestFinished().
UPnP::Service::Service (const ServiceParameters & params)
References connect(), UPnP::ServiceParameters::hostname, m_pHttp, m_szControlUrl, m_szServiceId, UPnP::ServiceParameters::port, and slotRequestFinished().
UPnP::Service::~Service () [virtual]
References m_pHttp, m_szControlUrl, and m_szServiceId.
Member Function Documentation
int UPnP::Service::callAction (const QString & actionName, const QString & prefix) [protected]
References callActionInternal().
Referenced by UPnP::WanConnectionService::addPortMapping(), UPnP::WanConnectionService::deletePortMapping(), UPnP::WanConnectionService::queryExternalIpAddress(), UPnP::WanConnectionService::queryNatEnabled(), and UPnP::WanConnectionService::queryPortMappingEntry().
int UPnP::Service::callAction (const QString & actionName, const QMap< QString, QString > & arguments, const QString & prefix) [protected]
References callActionInternal().
int UPnP::Service::callActionInternal (const QString & actionName, const QMap< QString, QString > * arguments, const QString & prefix) [private]
References m_iPendingRequests, m_iPort, m_pHttp, m_szBaseXmlPrefix, m_szControlUrl, m_szHostname, and m_szServiceType.
Referenced by callAction().
int UPnP::Service::callInformationUrl () [protected]
References m_iPendingRequests, m_pHttp, and m_szInformationUrl.
Referenced by UPnP::RootService::queryDevice().
int UPnP::Service::getPendingRequests () const
References m_iPendingRequests.
void UPnP::Service::gotActionErrorResponse (const QDomNode & response) [protected, virtual]
References XmlFunctions::getNodeValue().
Referenced by slotRequestFinished().
void UPnP::Service::gotActionResponse (const QString & responseType, const QMap< QString, QString > & resultValues) [protected, virtual]
Reimplemented in UPnP::WanConnectionService.
Referenced by slotRequestFinished().
void UPnP::Service::gotInformationResponse (const QDomNode & response) [protected, virtual]
Reimplemented in UPnP::RootService.
Referenced by slotRequestFinished().
void UPnP::Service::queryFinished (bool error) [signal]
Referenced by slotRequestFinished().
void UPnP::Service::slotRequestFinished (int id, bool error) [private, slot]
References XmlFunctions::getNode(), gotActionErrorResponse(), gotActionResponse(), gotInformationResponse(), i, m_iPendingRequests, m_pHttp, m_szBaseXmlPrefix, and queryFinished().
Referenced by Service().
Member Data Documentation
int UPnP::Service::m_iPendingRequests [private]
Referenced by callActionInternal(), callInformationUrl(), getPendingRequests(), and slotRequestFinished().
int UPnP::Service::m_iPort [private]
Reimplemented in UPnP::RootService.
Referenced by callActionInternal().
QHttp* UPnP::Service::m_pHttp [private]
Referenced by callActionInternal(), callInformationUrl(), Service(), slotRequestFinished(), and ~Service().
QString UPnP::Service::m_szBaseXmlPrefix [private]
Referenced by callActionInternal(), and slotRequestFinished().
QString UPnP::Service::m_szControlUrl [private]
Referenced by callActionInternal(), Service(), and ~Service().
QString UPnP::Service::m_szHostname [private]
Reimplemented in UPnP::RootService.
Referenced by callActionInternal().
QString UPnP::Service::m_szInformationUrl [private]
Referenced by callInformationUrl(), and Service().
QString UPnP::Service::m_szServiceId [private]
Referenced by Service(), and ~Service().
QString UPnP::Service::m_szServiceType [private]
Referenced by callActionInternal().
The documentation for this class was generated from the following files:
src/modules/upnp/Service.h
src/modules/upnp/Service.cpp