KVIrc: FileTransferItem Class Reference
FileTransferItem Class Reference
#include <FileTransferWindow.h>
Public Member Functions
virtual void displayUpdate ()
FileTransferItem (FileTransferWidget *v, KviFileTransfer *t)
virtual QString key (int column, bool bAcending) const
KviFileTransfer * transfer ()
~FileTransferItem ()
Public Member Functions inherited from KviTalTableWidgetItemEx
KviTalTableWidgetItemEx (KviTalTableWidget *pParent)
KviTalTableWidgetItemEx (KviTalTableWidget *pParent, int row, int column)
KviTalTableWidgetItemEx (const KviTalTableWidgetItem &other)
Public Member Functions inherited from KviTalTableWidgetItem
KviTalTableWidgetItem (KviTalTableWidget *pParent)
KviTalTableWidgetItem (KviTalTableWidget *pParent, int row, int column)
KviTalTableWidgetItem (const KviTalTableWidgetItem &other)
Protected Attributes
KviTalTableWidgetItem * col1Item
KviTalTableWidgetItem * col2Item
KviFileTransfer * m_pTransfer
Constructor & Destructor Documentation
FileTransferItem::FileTransferItem (FileTransferWidget * v, KviFileTransfer * t)
References col1Item, col2Item, FILETRANSFERW_CELLSIZE, KviTalTableWidgetItem::KviTalTableWidgetItem(), m_pTransfer, KviFileTransfer::setDisplayItem(), and t().
FileTransferItem::~FileTransferItem ()
References col1Item, col2Item, m_pTransfer, and KviFileTransfer::setDisplayItem().
Member Function Documentation
void FileTransferItem::displayUpdate () virtual
Implements KviTalTableWidgetItemEx.
References NULL.
QString FileTransferItem::key (int column, bool bAcending) const virtual
References KviFileTransfer::id(), and m_pTransfer.
KviFileTransfer* FileTransferItem::transfer () inline
References m_pTransfer.
Referenced by FileTransferWindow::clearAll(), FileTransferWindow::findItem(), FileTransferWindow::heartbeat(), FileTransferWindow::rightButtonPressed(), FileTransferWindow::selectedTransfer(), and FileTransferWindow::tipRequest().
Member Data Documentation
KviTalTableWidgetItem* FileTransferItem::col1Item protected
Referenced by FileTransferItem(), and ~FileTransferItem().
KviTalTableWidgetItem* FileTransferItem::col2Item protected
Referenced by FileTransferItem(), and ~FileTransferItem().
KviFileTransfer* FileTransferItem::m_pTransfer protected
Referenced by FileTransferItem(), key(), transfer(), and ~FileTransferItem().
The documentation for this class was generated from the following files:
src/modules/filetransferwindow/FileTransferWindow.h
src/modules/filetransferwindow/FileTransferWindow.cpp