KVIrc: OptionsWidget_ircOutput Class Reference
OptionsWidget_ircOutput Class Reference
#include <OptionsWidget_ircOutput.h>
Public Member Functions
OptionsWidget_ircOutput (QWidget *parent)
~OptionsWidget_ircOutput ()
Protected Member Functions
virtual void commit ()
Protected Attributes
QComboBox * m_pDatetimeCombo
QComboBox * m_pVerbosityCombo
Constructor & Destructor Documentation
OptionsWidget_ircOutput::OptionsWidget_ircOutput (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), KVI_OPTION_UINT, KVI_VERBOSITY_LEVEL_NORMAL, KVI_VERBOSITY_LEVEL_PARANOIC, KviOption_boolCtcpRepliesToActiveWindow, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolInvitesToActiveWindow, KviOption_boolOperatorMessagesToActiveWindow, KviOption_boolServerNoticesToActiveWindow, KviOption_boolServerRepliesToActiveWindow, KviOption_boolServicesNoticesToActiveWindow, KviOption_boolShowCompactModeChanges, KviOption_boolShowExtendedServerInfo, KviOption_boolShowOwnParts, KviOption_boolShowPingPong, KviOption_boolWhoisRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviOption_uintOutputVerbosityLevel, m_pDatetimeCombo, and m_pVerbosityCombo.
OptionsWidget_ircOutput::~OptionsWidget_ircOutput ()
Member Function Documentation
void OptionsWidget_ircOutput::commit (void) [protected, virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KVI_VERBOSITY_LEVEL_NORMAL, KVI_VERBOSITY_LEVEL_PARANOIC, KviOption_uintOutputDatetimeFormat, KviOption_uintOutputVerbosityLevel, m_pDatetimeCombo, and m_pVerbosityCombo.
Member Data Documentation
QComboBox* OptionsWidget_ircOutput::m_pDatetimeCombo [protected]
Referenced by commit(), and OptionsWidget_ircOutput().
QComboBox* OptionsWidget_ircOutput::m_pVerbosityCombo [protected]
Referenced by commit(), and OptionsWidget_ircOutput().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_ircOutput.h
src/modules/options/OptionsWidget_ircOutput.cpp