KVIrc: KviMediaManager Class Reference
KviMediaManager Class Reference
#include <KviMediaManager.h>
Public Member Functions
void clear ()
KviMediaType * findMediaType (const char *pcFilename, bool bCheckMagic=true)
KviMediaType * findMediaTypeByFileMask (const char *pcFilemask)
KviMediaType * findMediaTypeByIanaType (const char *pcIanaType)
void insertMediaType (KviMediaType *pType)
KviMediaManager ()
void load (const QString &szFilename)
KviPointerList< KviMediaType > * mediaTypeList ()
bool removeMediaType (KviMediaType *pType)
void save (const QString &szFilename)
~KviMediaManager ()
Public Member Functions inherited from KviMutex
KviMutex ()
void lock ()
bool locked ()
void unlock ()
virtual ~KviMutex ()
Static Public Member Functions
static void copyMediaType (KviMediaType *pDst, KviMediaType *pSrc)
Protected Attributes
KviPointerList< KviMediaType > * m_pMediaTypeList
Private Member Functions
KviMediaType * findMediaTypeForRegularFile (const char *pcFullPath, const char *pcFileName, bool bCheckMagic)
Constructor & Destructor Documentation
KviMediaManager::KviMediaManager ()
References m_pMediaTypeList, and KviPointerList< T >::setAutoDelete().
KviMediaManager::~KviMediaManager ()
References m_pMediaTypeList.
Member Function Documentation
void KviMediaManager::clear () inline
Referenced by OptionsWidget_mediaTypes::commit().
void KviMediaManager::copyMediaType (KviMediaType * pDst, KviMediaType * pSrc) static
References KviMediaType::szCommandline, KviMediaType::szDescription, KviMediaType::szFileMask, KviMediaType::szIanaType, KviMediaType::szIcon, KviMediaType::szMagicBytes, KviMediaType::szRemoteExecCommandline, and KviMediaType::szSavePath.
KviMediaType * KviMediaManager::findMediaType (const char * pcFilename, bool bCheckMagic = true)
References __tr, KviCString::cutToLast(), KviCString::ensureLastCharIs(), findMediaTypeByIanaType(), findMediaTypeForRegularFile(), insertMediaType(), KviFileUtils::isAbsolutePath(), KVI_ASSERT, KviMutex::locked(), KviCString::prepend(), KviCString::ptr(), S_ISCHR, S_ISDIR, S_ISFIFO, KviMediaType::szCommandline, KviMediaType::szDescription, KviMediaType::szIanaType, and KviMediaType::szIcon.
Referenced by DccBroker::chooseSaveFileName().
KviMediaType * KviMediaManager::findMediaTypeByFileMask (const char * pcFilemask)
References KviPointerList< T >::first(), KVI_ASSERT, kvi_strEqualCI(), KviMutex::locked(), m_pMediaTypeList, and KviPointerList< T >::next().
Referenced by load().
KviMediaType * KviMediaManager::findMediaTypeByIanaType (const char * pcIanaType)
References KviPointerList< T >::first(), KVI_ASSERT, kvi_strEqualCI(), KviMutex::locked(), m_pMediaTypeList, and KviPointerList< T >::next().
Referenced by findMediaType(), and findMediaTypeForRegularFile().
KviMediaType * KviMediaManager::findMediaTypeForRegularFile (const char * pcFullPath, const char * pcFileName, bool bCheckMagic) private
References __tr, f, findMediaTypeByIanaType(), KviPointerList< T >::first(), insertMediaType(), kvi_matchWildExpr(), m, m_pMediaTypeList, KviPointerList< T >::next(), KviMediaType::szCommandline, KviMediaType::szDescription, KviMediaType::szIanaType, and KviMediaType::szIcon.
Referenced by findMediaType().
void KviMediaManager::insertMediaType (KviMediaType * pType)
References KviPointerList< T >::append(), KviPointerList< T >::first(), KviPointerList< T >::insert(), KVI_ASSERT, KviCString::len(), KviMutex::locked(), m_pMediaTypeList, KviPointerList< T >::next(), KviCString::occurrences(), and KviMediaType::szFileMask.
Referenced by OptionsWidget_mediaTypes::commit(), findMediaType(), findMediaTypeForRegularFile(), and load().
void KviMediaManager::load (const QString & szFilename)
References _KviDefaultMediaType::commandline, _KviDefaultMediaType::description, _KviDefaultMediaType::filemask, findMediaTypeByFileMask(), KviCString::Format, i, _KviDefaultMediaType::ianatype, insertMediaType(), KVI_ASSERT, KviMutex::locked(), m, _KviDefaultMediaType::magicbytes, KviCString::ptr(), KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviConfigurationFile::readUIntEntry(), KviConfigurationFile::setGroup(), KviCString::sprintf(), KviMediaType::szCommandline, KviMediaType::szDescription, KviMediaType::szFileMask, KviMediaType::szIanaType, KviMediaType::szIcon, KviMediaType::szMagicBytes, KviMediaType::szRemoteExecCommandline, KviMediaType::szSavePath, and u.
Referenced by KviApplication::setup().
KviPointerList<KviMediaType>* KviMediaManager::mediaTypeList () inline
Referenced by OptionsWidget_mediaTypes::fillTreeWidget().
bool KviMediaManager::removeMediaType (KviMediaType * pType) inline
void KviMediaManager::save (const QString & szFilename)
References KviConfigurationFile::clear(), KviPointerList< T >::count(), KviPointerList< T >::first(), KviCString::Format, KVI_ASSERT, KviMutex::locked(), m, m_pMediaTypeList, KviPointerList< T >::next(), KviCString::ptr(), KviConfigurationFile::setGroup(), KviCString::sprintf(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveMediaTypes().
Member Data Documentation
KviPointerList<KviMediaType>* KviMediaManager::m_pMediaTypeList protected
Referenced by findMediaTypeByFileMask(), findMediaTypeByIanaType(), findMediaTypeForRegularFile(), insertMediaType(), KviMediaManager(), save(), and ~KviMediaManager().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviMediaManager.h
src/kvilib/ext/KviMediaManager.cpp