KVIrc: OptionsWidget_mediaTypes Class Reference
OptionsWidget_mediaTypes Class Reference
#include <OptionsWidget_mediaTypes.h>
Public Member Functions
virtual void commit ()
OptionsWidget_mediaTypes (QWidget *parent)
~OptionsWidget_mediaTypes ()
Private Slots
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *prev)
void delMediaType ()
void newMediaType ()
Private Member Functions
void enableOrDisable ()
void fillTreeWidget ()
void saveLastItem ()
void setLineEdits ()
Private Attributes
QLineEdit * m_pCommandline
QPushButton * m_pDelete
QLineEdit * m_pDescription
QLineEdit * m_pFileMask
QLineEdit * m_pIanaType
QLineEdit * m_pIcon
MediaTypeTreeWidgetItem * m_pLastItem
QLineEdit * m_pMagicBytes
QLineEdit * m_pRemoteExecCommandline
QLineEdit * m_pSavePath
QTreeWidget * m_pTreeWidget
Constructor & Destructor Documentation
OptionsWidget_mediaTypes::OptionsWidget_mediaTypes (QWidget * parent)
References __tr2qs_ctx(), connect(), KviOptionsWidget::createLayout(), currentItemChanged(), delMediaType(), f, fillTreeWidget(), l, KviOptionsWidget::layout(), m_pCommandline, m_pDelete, m_pDescription, m_pFileMask, m_pIanaType, m_pIcon, m_pLastItem, m_pMagicBytes, m_pRemoteExecCommandline, m_pSavePath, m_pTreeWidget, KviOptionsWidget::mergeTip(), and newMediaType().
OptionsWidget_mediaTypes::~OptionsWidget_mediaTypes ()
Member Function Documentation
void OptionsWidget_mediaTypes::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KviMediaManager::clear(), copyMediaType(), g_pMediaManager, i, KviMediaManager::insertMediaType(), KviMutex::lock(), m_pTreeWidget, MediaTypeTreeWidgetItem::mydata(), saveLastItem(), t(), and KviMutex::unlock().
void OptionsWidget_mediaTypes::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem * prev) [private, slot]
References enableOrDisable(), m_pLastItem, saveLastItem(), and setLineEdits().
Referenced by OptionsWidget_mediaTypes().
void OptionsWidget_mediaTypes::delMediaType () [private, slot]
References m_pLastItem.
Referenced by OptionsWidget_mediaTypes().
void OptionsWidget_mediaTypes::enableOrDisable () [private]
References m_pCommandline, m_pDelete, m_pDescription, m_pFileMask, m_pIanaType, m_pIcon, m_pLastItem, m_pMagicBytes, m_pRemoteExecCommandline, and m_pSavePath.
Referenced by currentItemChanged(), and fillTreeWidget().
void OptionsWidget_mediaTypes::fillTreeWidget () [private]
References enableOrDisable(), KviPointerList< T >::first(), g_pMediaManager, l, KviMutex::lock(), m_pTreeWidget, KviMediaManager::mediaTypeList(), KviPointerList< T >::next(), t(), and KviMutex::unlock().
Referenced by OptionsWidget_mediaTypes().
void OptionsWidget_mediaTypes::newMediaType () [private, slot]
References __tr2qs_ctx(), m_pTreeWidget, and KviMediaType::szDescription.
Referenced by OptionsWidget_mediaTypes().
void OptionsWidget_mediaTypes::saveLastItem () [private]
References __tr2qs_ctx(), MediaTypeTreeWidgetItem::copyData(), KviCString::isEmpty(), m_pCommandline, m_pDescription, m_pFileMask, m_pIanaType, m_pIcon, m_pLastItem, m_pMagicBytes, m_pRemoteExecCommandline, m_pSavePath, KviMediaType::szCommandline, KviMediaType::szDescription, KviMediaType::szFileMask, KviMediaType::szIanaType, KviMediaType::szIcon, KviMediaType::szMagicBytes, KviMediaType::szRemoteExecCommandline, KviMediaType::szSavePath, and t().
Referenced by commit(), and currentItemChanged().
void OptionsWidget_mediaTypes::setLineEdits () [private]
References m_pCommandline, m_pDescription, m_pFileMask, m_pIanaType, m_pIcon, m_pLastItem, m_pMagicBytes, m_pRemoteExecCommandline, m_pSavePath, MediaTypeTreeWidgetItem::mydata(), KviCString::ptr(), KviMediaType::szCommandline, KviMediaType::szDescription, KviMediaType::szFileMask, KviMediaType::szIanaType, KviMediaType::szIcon, KviMediaType::szMagicBytes, KviMediaType::szRemoteExecCommandline, and KviMediaType::szSavePath.
Referenced by currentItemChanged().
Member Data Documentation
QLineEdit* OptionsWidget_mediaTypes::m_pCommandline [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QPushButton* OptionsWidget_mediaTypes::m_pDelete [private]
Referenced by enableOrDisable(), and OptionsWidget_mediaTypes().
QLineEdit* OptionsWidget_mediaTypes::m_pDescription [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QLineEdit* OptionsWidget_mediaTypes::m_pFileMask [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QLineEdit* OptionsWidget_mediaTypes::m_pIanaType [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QLineEdit* OptionsWidget_mediaTypes::m_pIcon [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
MediaTypeTreeWidgetItem* OptionsWidget_mediaTypes::m_pLastItem [private]
Referenced by currentItemChanged(), delMediaType(), enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QLineEdit* OptionsWidget_mediaTypes::m_pMagicBytes [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QLineEdit* OptionsWidget_mediaTypes::m_pRemoteExecCommandline [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QLineEdit* OptionsWidget_mediaTypes::m_pSavePath [private]
Referenced by enableOrDisable(), OptionsWidget_mediaTypes(), saveLastItem(), and setLineEdits().
QTreeWidget* OptionsWidget_mediaTypes::m_pTreeWidget [private]
Referenced by commit(), fillTreeWidget(), newMediaType(), and OptionsWidget_mediaTypes().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_mediaTypes.h
src/modules/options/OptionsWidget_mediaTypes.cpp