KVIrc: AvatarSelectionDialog Class Reference
AvatarSelectionDialog Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
AvatarSelectionDialog (QWidget *par, const QString &szInitialPath)
~AvatarSelectionDialog ()
Protected Slots
void cancelClicked ()
void chooseFileClicked ()
void okClicked ()
Protected Member Functions
const QString & avatarName ()
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
QLineEdit * m_pLineEdit
QString m_szAvatarName
Friends
class OptionsWidget_identityAvatar
Constructor & Destructor Documentation
AvatarSelectionDialog::AvatarSelectionDialog (QWidget * par, const QString & szInitialPath)
References __tr2qs_ctx(), cancelClicked(), chooseFileClicked(), connect(), g, h, l, m_pLineEdit, okClicked(), and KviTalHBox::setSpacing().
AvatarSelectionDialog::~AvatarSelectionDialog ()
Member Function Documentation
const QString& AvatarSelectionDialog::avatarName () [inline, protected]
References m_szAvatarName.
Referenced by OptionsWidget_identityAvatar::chooseAvatar().
void AvatarSelectionDialog::cancelClicked () [protected, slot]
Referenced by AvatarSelectionDialog().
void AvatarSelectionDialog::chooseFileClicked () [protected, slot]
References __tr2qs_ctx(), KviFileDialog::askForOpenFileName(), KVI_FILTER_IMAGE, and m_pLineEdit.
Referenced by AvatarSelectionDialog().
void AvatarSelectionDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void AvatarSelectionDialog::okClicked () [protected, slot]
References m_pLineEdit, and m_szAvatarName.
Referenced by AvatarSelectionDialog().
Friends And Related Function Documentation
friend class OptionsWidget_identityAvatar [friend]
Member Data Documentation
QLineEdit* AvatarSelectionDialog::m_pLineEdit [protected]
Referenced by AvatarSelectionDialog(), chooseFileClicked(), and okClicked().
QString AvatarSelectionDialog::m_szAvatarName [protected]
Referenced by avatarName(), and okClicked().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp