KVIrc: KviPasswordLineEdit Class Reference
KviPasswordLineEdit Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
KviPasswordLineEdit (QWidget *par)
void setText (const QString &text)
QString text ()
~KviPasswordLineEdit ()
Public Member Functions inherited from KviTalHBox
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Protected Slots
void checkToggled (int state)
Protected Attributes
QCheckBox * m_pCheckBox
QLineEdit * m_pLineEdit
Additional Inherited Members
Protected Member Functions inherited from KviTalHBox
virtual void childEvent (QChildEvent *e)
Constructor & Destructor Documentation
KviPasswordLineEdit::KviPasswordLineEdit (QWidget * par)
References KviTalHBox::addSpacing(), checkToggled(), connect(), m_pCheckBox, m_pLineEdit, KviTalHBox::setMargin(), KviTalHBox::setSpacing(), and KviTalHBox::setStretchFactor().
KviPasswordLineEdit::~KviPasswordLineEdit ()
Member Function Documentation
void KviPasswordLineEdit::checkToggled (int state) protected slot
References m_pLineEdit, and Normal.
Referenced by KviPasswordLineEdit().
void KviPasswordLineEdit::setEnabled (bool bEnabled) virtual slot
References m_pCheckBox, and m_pLineEdit.
void KviPasswordLineEdit::setText (const QString & text)
References m_pLineEdit.
Referenced by IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), and IrcServerDetailsWidget::IrcServerDetailsWidget().
QString KviPasswordLineEdit::text ()
References m_pLineEdit.
Referenced by IrcNetworkDetailsWidget::fillData(), and IrcServerDetailsWidget::fillData().
Member Data Documentation
QCheckBox* KviPasswordLineEdit::m_pCheckBox protected
Referenced by KviPasswordLineEdit(), and setEnabled().
QLineEdit* KviPasswordLineEdit::m_pLineEdit protected
Referenced by checkToggled(), KviPasswordLineEdit(), setEnabled(), setText(), and text().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp