KVIrc: KviMircServersIniImport Class Reference
KviMircServersIniImport Class Reference
#include <libkvimircimport.h>
Public Member Functions
virtual void die ()
int doImport (const QString &filename)
KviMircServersIniImport (KviModuleExtensionDescriptor *d)
virtual void start ()
~KviMircServersIniImport ()
Public Member Functions inherited from KviMexServerImport
KviMexServerImport (KviModuleExtensionDescriptor *d)
~KviMexServerImport ()
Public Member Functions inherited from KviModuleExtension
KviModuleExtensionDescriptor * descriptor ()
KviModuleExtension (KviModuleExtensionDescriptor *d)
virtual ~KviModuleExtension ()
Additional Inherited Members
Signals inherited from KviMexServerImport
void server (const KviIrcServer &s, const QString &network)
Static Public Member Functions inherited from KviModuleExtension
static KviModuleExtensionManager * manager ()
Constructor & Destructor Documentation
KviMircServersIniImport::KviMircServersIniImport (KviModuleExtensionDescriptor * d)
KviMircServersIniImport::~KviMircServersIniImport ()
Member Function Documentation
void KviMircServersIniImport::die () virtual
Implements KviMexServerImport.
Reimplemented in KviRemoteMircServersIniImport.
int KviMircServersIniImport::doImport (const QString & filename)
References __tr2qs, KviConfigurationFile::hasGroup(), i, key, KviConfigurationFile::Read, KviConfigurationFile::readEntry(), s, KviMexServerImport::server(), KviIrcServer::setDescription(), KviConfigurationFile::setGroup(), KviIrcServer::setHostName(), KviIrcServer::setPort(), uPort, and KviMessageBox::warning().
Referenced by KviRemoteMircServerImportWizard::getListTerminated(), and start().
void KviMircServersIniImport::start () virtual
Implements KviMexServerImport.
Reimplemented in KviRemoteMircServersIniImport.
References __tr, KviFileDialog::askForOpenFileName(), doImport(), and KVI_FILTER_INI.
The documentation for this class was generated from the following files:
src/modules/mircimport/libkvimircimport.h
src/modules/mircimport/libkvimircimport.cpp