KVIrc: KviTalPopupMenu Class Reference
KviTalPopupMenu Class Reference
#include <KviTalPopupMenu.h>
Signals
void activated (int)
Public Member Functions
void clear ()
QAction * getAction (int id)
int insertItem (const QString &szText)
int insertItem (const QPixmap &pix, const QString &szText)
int insertItem (const QPixmap &pix, const QString &szText, const QObject *pReceiver, const char *szSlot)
int insertItem (const QPixmap &pix, const QString &szText, QMenu *pMenu)
int insertItem (const QString &szText, int id)
int insertItem (const QString &szText, QMenu *pMenu)
int insertItem (QWidget *pWidget)
int insertItem (const QPixmap &pix, const QString &szText, int id)
int insertItem (const QString &szText, const QObject *pReceiver, const char *szSlot)
int insertSeparator ()
int itemParameter (int id)
KviTalPopupMenu (QWidget *pParent=0, const QString &szName=KviQString::Empty)
void setItemChecked (int id, bool check)
void setItemEnabled (int id, bool bFlag)
void setItemParameter (int id, int param)
QString text (int)
virtual ~KviTalPopupMenu ()
Protected Slots
void slotActionTriggered (bool)
void slottriggered (QAction *)
Protected Attributes
QHash< int, QAction * > actionsDict
int identifier
QHash< QAction *, QSignalMapper * > signalMapper
Constructor & Destructor Documentation
KviTalPopupMenu::KviTalPopupMenu (QWidget * pParent = 0, const QString & szName = KviQString::Empty)
References connect(), identifier, and slottriggered().
KviTalPopupMenu::~KviTalPopupMenu () [virtual]
References clear().
Member Function Documentation
void KviTalPopupMenu::activated (int) [signal]
Referenced by KviKvsPopupMenu::KviKvsPopupMenu(), and slottriggered().
void KviTalPopupMenu::clear ()
References actionsDict, identifier, and signalMapper.
Referenced by KviStatusBar::appletsPopupAboutToShow(), KviKvsPopupMenu::clearMenuContents(), ThemeManagementDialog::contextMenuRequested(), KviTopicWidget::contextPopupAboutToShow(), KviStatusBar::contextPopupAboutToShow(), RawEditorWidget::customContextMenuRequested(), PopupEditorWidget::customContextMenuRequested(), SinglePopupEditor::customContextMenuRequested(), OptionsWidget_servers::customContextMenuRequested(), OptionsWidget_proxy::customContextMenuRequested(), ClassEditorWidget::customContextMenuRequested(), AliasEditorWidget::customContextMenuRequested(), KviKvsPopupMenu::doClear(), TrayIcon::fillContextPopup(), NotifierWindow::fillContextPopup(), KviApplication::fillRecentChannelsPopup(), KviApplication::fillRecentNicknamesPopup(), KviApplication::fillRecentServersPopup(), KviMainWindow::fillToolBarsPopup(), KviMdiManager::fillWindowPopup(), OptionsWidget_servers::importPopupAboutToShow(), EventEditor::itemPressed(), KviToolBar::mousePressEvent(), KviInputEditor::mousePressEvent(), KviIrcOperationsAction::popupAboutToShow(), KviIrcToolsAction::popupAboutToShow(), KviChangeUserModeAction::popupAboutToShow(), FileTransferWindow::rightButtonPressed(), KviMenuBar::setupHelpPopup(), KviMenuBar::setupMainPopup(), KviKvsPopupMenu::setupMenuContents(), KviMenuBar::setupScriptingPopup(), KviMenuBar::setupSettingsPopup(), KviMenuBar::setupToolsPopup(), LinksWindow::showHostPopup(), KviIrcView::showToolsPopup(), and ~KviTalPopupMenu().
QAction * KviTalPopupMenu::getAction (int id)
References a, and actionsDict.
int KviTalPopupMenu::insertItem (const QPixmap & pix, const QString & szText, int id)
References a, and actionsDict.
int KviTalPopupMenu::insertItem (const QString & szText, QMenu * pMenu)
References a, actionsDict, and identifier.
int KviTalPopupMenu::insertItem (QWidget * pWidget)
int KviTalPopupMenu::insertItem (const QString & szText, int id)
References a, and actionsDict.
int KviTalPopupMenu::insertItem (const QPixmap & pix, const QString & szText, QMenu * pMenu)
References a, actionsDict, and identifier.
int KviTalPopupMenu::insertItem (const QPixmap & pix, const QString & szText)
References a, actionsDict, and identifier.
int KviTalPopupMenu::insertItem (const QString & szText, const QObject * pReceiver, const char * szSlot)
References actionsDict, connect(), identifier, and signalMapper.
int KviTalPopupMenu::insertItem (const QPixmap & pix, const QString & szText, const QObject * pReceiver, const char * szSlot)
References actionsDict, connect(), identifier, and signalMapper.
int KviTalPopupMenu::insertItem (const QString & szText)
References a, actionsDict, and identifier.
Referenced by KviGoAwayAction::addToPopupMenu(), KviSubmenuAction::addToPopupMenu(), KviConnectAction::addToPopupMenu(), KviAction::addToPopupMenu(), KviStatusBar::appletsPopupAboutToShow(), UrlDialog::contextMenu(), ThemeManagementDialog::contextMenuRequested(), KviTopicWidget::contextPopupAboutToShow(), KviStatusBar::contextPopupAboutToShow(), KviWindow::createSystemTextEncodingPopup(), RawEditorWidget::customContextMenuRequested(), PopupEditorWidget::customContextMenuRequested(), SinglePopupEditor::customContextMenuRequested(), OptionsWidget_servers::customContextMenuRequested(), OptionsWidget_proxy::customContextMenuRequested(), ClassEditorWidget::customContextMenuRequested(), AliasEditorWidget::customContextMenuRequested(), OptionsWidget_textIcons::doPopup(), KviKvsPopupMenuItemExtMenu::fill(), KviKvsPopupMenuItemMenu::fill(), KviKvsPopupMenuItemItem::fill(), KviKvsPopupMenuItemLabel::fill(), NotifierWindow::fillContextPopup(), HttpFileTransfer::fillContextPopup(), DccFileTransfer::fillContextPopup(), KviStatusBarUpdateIndicator::fillContextPopup(), KviStatusBarConnectionTimer::fillContextPopup(), KviStatusBarClock::fillContextPopup(), KviStatusBarAwayIndicator::fillContextPopup(), KviApplication::fillRecentChannelsPopup(), KviApplication::fillRecentNicknamesPopup(), KviApplication::fillRecentServersPopup(), KviMainWindow::fillToolBarsPopup(), KviMdiManager::fillWindowPopup(), OptionsWidget_servers::importPopupAboutToShow(), EventEditor::itemPressed(), KviMircTextColorSelector::KviMircTextColorSelector(), LogViewWindow::LogViewWindow(), ChannelsJoinDialogTreeWidget::mousePressEvent(), KviTreeWindowListTreeWidget::mousePressEvent(), KviToolBar::mousePressEvent(), KviInputEditor::mousePressEvent(), OptionsWidget_messageColors::OptionsWidget_messageColors(), UrlDialog::popup(), KviChangeUserModeAction::popupAboutToShow(), KviConnectToServerAction::popupAboutToShow(), KviChangeNickAction::popupAboutToShow(), KviJoinChannelAction::popupAboutToShow(), OptionsWidget_servers::recentServersPopupAboutToShow(), LogViewWindow::rightButtonClicked(), RegisteredUsersDialog::rightButtonPressed(), FileTransferWindow::rightButtonPressed(), ScriptEditorImplementation::ScriptEditorImplementation(), KviMenuBar::setupHelpPopup(), KviMenuBar::setupMainPopup(), KviMenuBar::setupRecentServersPopup(), KviMenuBar::setupScriptingPopup(), KviMenuBar::setupSettingsPopup(), KviMenuBar::setupToolsPopup(), LinksWindow::showHostPopup(), KviIrcView::showToolsPopup(), and TrayIcon::TrayIcon().
int KviTalPopupMenu::insertSeparator ()
References a, actionsDict, and identifier.
Referenced by KviSeparatorAction::addToPopupMenu(), KviStatusBar::contextPopupAboutToShow(), KviWindow::createSystemTextEncodingPopup(), RawEditorWidget::customContextMenuRequested(), SinglePopupEditor::customContextMenuRequested(), OptionsWidget_servers::customContextMenuRequested(), ClassEditorWidget::customContextMenuRequested(), AliasEditorWidget::customContextMenuRequested(), KviKvsPopupMenuItemSeparator::fill(), NotifierWindow::fillContextPopup(), DccFileTransfer::fillContextPopup(), KviStatusBarClock::fillContextPopup(), KviMainWindow::fillToolBarsPopup(), KviMdiManager::fillWindowPopup(), KviInputEditor::mousePressEvent(), UrlDialog::popup(), KviConnectToServerAction::popupAboutToShow(), KviChangeNickAction::popupAboutToShow(), KviJoinChannelAction::popupAboutToShow(), OptionsWidget_servers::recentServersPopupAboutToShow(), FileTransferWindow::rightButtonPressed(), ScriptEditorImplementation::ScriptEditorImplementation(), KviMenuBar::setupHelpPopup(), KviMenuBar::setupMainPopup(), KviMenuBar::setupRecentServersPopup(), KviMenuBar::setupScriptingPopup(), KviMenuBar::setupSettingsPopup(), KviMenuBar::setupToolsPopup(), LinksWindow::showHostPopup(), KviIrcView::showToolsPopup(), and TrayIcon::TrayIcon().
int KviTalPopupMenu::itemParameter (int id)
References actionsDict.
Referenced by KviMenuBar::actionTriggered(), KviStatusBar::appletsPopupActivated(), KviMircTextColorSelector::backSelected(), KviMircTextColorSelector::foreSelected(), OptionsWidget_servers::importPopupActivated(), KviKvsPopupMenu::itemClicked(), FileTransferWindow::openFilePopupActivated(), KviMdiManager::tileMethodMenuActivated(), and KviMenuBar::toolsPopupSelected().
void KviTalPopupMenu::setItemChecked (int id, bool check)
References actionsDict.
Referenced by KviStatusBarUpdateIndicator::fillContextPopup(), KviStatusBarConnectionTimer::fillContextPopup(), KviStatusBarClock::fillContextPopup(), KviStatusBarAwayIndicator::fillContextPopup(), KviMainWindow::fillToolBarsPopup(), KviMdiManager::fillWindowPopup(), KviChangeUserModeAction::popupAboutToShow(), and KviMenuBar::setupSettingsPopup().
void KviTalPopupMenu::setItemEnabled (int id, bool bFlag)
References actionsDict.
Referenced by KviGoAwayAction::addToPopupMenu(), KviSubmenuAction::addToPopupMenu(), KviConnectAction::addToPopupMenu(), KviAction::addToPopupMenu(), PopupEditorWidget::customContextMenuRequested(), SinglePopupEditor::customContextMenuRequested(), OptionsWidget_servers::customContextMenuRequested(), OptionsWidget_proxy::customContextMenuRequested(), ClassEditorWidget::customContextMenuRequested(), AliasEditorWidget::customContextMenuRequested(), HttpFileTransfer::fillContextPopup(), DccFileTransfer::fillContextPopup(), KviStatusBarClock::fillContextPopup(), KviApplication::fillRecentChannelsPopup(), KviApplication::fillRecentNicknamesPopup(), KviInputEditor::mousePressEvent(), FileTransferWindow::rightButtonPressed(), and KviIrcView::showToolsPopup().
void KviTalPopupMenu::setItemParameter (int id, int param)
References actionsDict, and signalMapper.
Referenced by KviStatusBar::appletsPopupAboutToShow(), KviKvsPopupMenuItemExtMenu::fill(), KviKvsPopupMenuItemMenu::fill(), KviKvsPopupMenuItemItem::fill(), KviMainWindow::fillToolBarsPopup(), KviMdiManager::fillWindowPopup(), OptionsWidget_servers::importPopupAboutToShow(), KviMircTextColorSelector::KviMircTextColorSelector(), FileTransferWindow::rightButtonPressed(), KviMenuBar::setupHelpPopup(), KviMenuBar::setupMainPopup(), and KviMenuBar::setupToolsPopup().
void KviTalPopupMenu::slotActionTriggered (bool) [protected, slot]
References slottriggered().
void KviTalPopupMenu::slottriggered (QAction * a) [protected, slot]
References actionsDict, activated(), i, and signalMapper.
Referenced by KviTalPopupMenu(), and slotActionTriggered().
QString KviTalPopupMenu::text (int id)
References actionsDict.
Referenced by LinksWindow::hostPopupClicked(), KviInputEditor::iconPopupActivated(), KviKvsPopupMenu::load(), KviMenuBar::newConnectionToServer(), KviChangeUserModeAction::popupActivated(), KviConnectToServerAction::popupActivated(), KviChangeNickAction::popupActivated(), KviJoinChannelAction::popupActivated(), and OptionsWidget_servers::recentServersPopupClicked().
Member Data Documentation
QHash<int, QAction*> KviTalPopupMenu::actionsDict [protected]
Referenced by clear(), getAction(), insertItem(), insertSeparator(), itemParameter(), setItemChecked(), setItemEnabled(), setItemParameter(), slottriggered(), and text().
int KviTalPopupMenu::identifier [protected]
Referenced by clear(), insertItem(), insertSeparator(), and KviTalPopupMenu().
QHash<QAction*, QSignalMapper*> KviTalPopupMenu::signalMapper [protected]
Referenced by clear(), insertItem(), setItemParameter(), and slottriggered().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalPopupMenu.h
src/kvilib/tal/KviTalPopupMenu.cpp