KVIrc: ActionEditorTreeWidgetItem Class Reference
ActionEditorTreeWidgetItem Class Reference
#include <ActionEditor.h>
Public Member Functions
ActionData * actionData ()
ActionEditorTreeWidgetItem (QTreeWidget *v, ActionData *a)
virtual QString key (int, bool) const
~ActionEditorTreeWidgetItem ()
Protected Attributes
ActionData * m_pActionData
QPixmap * m_pIcon
QTextDocument * m_pText
QTreeWidget * m_pTreeWidget
QString m_szKey
Constructor & Destructor Documentation
ActionEditorTreeWidgetItem::ActionEditorTreeWidgetItem (QTreeWidget * v, ActionData * a)
References a, g_pIconManager, KviIconManager::getBigIcon(), m_pActionData, m_pTreeWidget, ActionData::m_szBigIcon, m_szKey, ActionData::m_szName, ActionData::m_szVisibleName, p, t(), and v.
ActionEditorTreeWidgetItem::~ActionEditorTreeWidgetItem ()
References m_pActionData.
Member Function Documentation
ActionData* ActionEditorTreeWidgetItem::actionData () inline
References m_pActionData.
Referenced by ActionEditor::commit(), and ActionEditor::currentItemChanged().
QString ActionEditorTreeWidgetItem::key (int , bool) const virtual
References m_szKey.
Member Data Documentation
ActionData* ActionEditorTreeWidgetItem::m_pActionData protected
Referenced by actionData(), ActionEditorTreeWidgetItem(), and ~ActionEditorTreeWidgetItem().
QPixmap* ActionEditorTreeWidgetItem::m_pIcon protected
QTextDocument* ActionEditorTreeWidgetItem::m_pText protected
QTreeWidget* ActionEditorTreeWidgetItem::m_pTreeWidget protected
Referenced by ActionEditorTreeWidgetItem().
QString ActionEditorTreeWidgetItem::m_szKey protected
Referenced by ActionEditorTreeWidgetItem(), and key().
The documentation for this class was generated from the following files:
src/modules/actioneditor/ActionEditor.h
src/modules/actioneditor/ActionEditor.cpp