KVIrc: KviConsole Class Reference
KviConsole Class Reference
#include <kvi_console.h>
Public Types
enum OutputPrivmsgFlags { NoWindowFlashing = 1, NoNotifier = 2, NoHighlighting = 4, NoNotifications = 7 }
Public Slots
void executeInternalCommand (int index)
void recentUrlsChanged ()
void updateUri ()
Public Member Functions
KviWindow * activeWindow ()
void addHighlightedChannel (const QString &szChan)
Adds a channel to the highlight list.
int applyHighlighting (KviWindow *wnd, int type, const QString &nick, const QString &user, const QString &host, const QString &szMsg)
void avatarChanged (KviAvatar *avatar, const QString &nick, const QString &user, const QString &host, const QString &textLine)
void avatarChangedUpdateWindows (const QString &nick, const QString &textLine)
void checkDefaultAvatar (KviIrcUserEntry *e, const QString &nick, const QString &user, const QString &host)
void completeChannel (const QString &word, KviPointerList< QString > *matches)
void completeServer (const QString &word, KviPointerList< QString > *matches)
void connectionAttached ()
void connectionDetached ()
bool connectionInProgress ()
KviIrcContext * context ()
KviAvatar * currentAvatar ()
QString currentNetworkName ()
KviAvatar * defaultAvatarFromOptions ()
void getUserTipText (const QString &nick, KviIrcUserEntry *e, QString &buffer)
bool isConnected ()
bool isHighlightedChannel (const QString &szChan)
Returns true if the channel is highlighted.
bool isIPv6Connection ()
bool isNotConnected ()
KviUserListView * notifyListView ()
void outputPrivmsg (KviWindow *wnd, int type, const QString &nick, const QString &user, const QString &host, const QString &msg, int iFlags=0, const QString &prefix=QString(), const QString &suffix=QString())
void removeHighlightedChannel (const QString &szChan)
Removes a channel from the highlight list.
void resetAvatarForMatchingUsers (KviRegisteredUser *u)
int selectedCount ()
KviAvatar * setAvatar (const QString &nick, const QString &user, const QString &host, const QString &szLocalPath, const QString &szName)
void setAvatarFromOptions ()
KviIrcContext::State state ()
const QString & statusString ()
void terminateConnectionRequest (bool bForce=false, const char *quitMsg=0)
~KviConsole ()
Protected Slots
void ircUriChanged (const QString &)
void textViewRightClicked ()
void toggleNotifyView ()
Protected Member Functions
virtual void applyOptions ()
virtual void closeEvent (QCloseEvent *e)
void destroyConnection ()
virtual void fillCaptionBuffers ()
virtual void fillContextPopup (KviTalPopupMenu *p)
void fillStatusString ()
virtual void getBaseLogFileName (QString &buffer)
virtual void getWindowListTipText (QString &buffer)
KviConsole (KviFrame *lpFrm, int iFlags)
virtual void loadProperties (KviConfig *cfg)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfig *cfg)
void showNotifyList (bool bShow)
virtual QSize sizeHint () const
virtual void triggerCreationEvents ()
int triggerOnHighlight (KviWindow *wnd, int type, const QString &nick, const QString &user, const QString &host, const QString &szMsg, const QString &trigger)
Static Protected Member Functions
static int getSmartColorHashForNick (QString *szNick)
Protected Attributes
int m_iFlags
KviThemedComboBox * m_pAddressEdit
KviIrcContext * m_pContext
KviUserListView * m_pNotifyListView
KviWindowToolPageButton * m_pNotifyViewButton
QStringList * m_pTmpHighLightedChannels
QString m_szOwnSmartColor
QString m_szStatusString
Friends
class KviChannel
class KviFrame
class KviIrcContext
class KviIrcSocket
class KviQuery
Member Enumeration Documentation
enum KviConsole::OutputPrivmsgFlags
Enumerator:
NoWindowFlashing
NoNotifier
NoHighlighting
NoNotifications
Constructor & Destructor Documentation
KviConsole::KviConsole (KviFrame * lpFrm, int iFlags) [protected]
References __tr2qs, KviTalToolTip::add(), g_pApp, g_pIconManager, KviIconManager::getSmallIcon(), KVI_CONSOLE_FLAG_FIRSTINAPP, KVI_OPTION_BOOL, KVI_SMALLICON_HIDELISTVIEW, KVI_SMALLICON_SHOWLISTVIEW, KVI_SMALLICON_URL, KviOption_boolAutoLogConsole, and KviTalSplitter.
KviConsole::~KviConsole ()
References context(), KviEvent_OnIrcContextDestroyed, KVS_TRIGGER_EVENT_0, m_pContext, m_pTmpHighLightedChannels, and KviIrcContext::terminateConnectionRequest().
Member Function Documentation
KviWindow * KviConsole::activeWindow ()
References KviWindow::console(), and g_pActiveWindow.
Referenced by KviServerParser::echoCtcpReply(), KviServerParser::echoCtcpRequest(), KviKvsCoreFunctions::KVSCF(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviServerParser::parseCtcpReplyPing(), KviServerParser::parseCtcpRequestAction(), KviServerParser::parseLiteralInvite(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), KviServerParser::parseLiteralWallops(), KviServerParser::parseNumeric367(), KviServerParser::parseNumeric368(), KviServerParser::parseNumericAway(), KviServerParser::parseNumericBackFromAway(), KviServerParser::parseNumericChannelModeIs(), KviServerParser::parseNumericCodePageScheme(), KviServerParser::parseNumericCreationTime(), KviServerParser::parseNumericEndOfNames(), KviServerParser::parseNumericEndOfWho(), KviServerParser::parseNumericEndOfWhois(), KviServerParser::parseNumericEndOfWhowas(), KviServerParser::parseNumericIsOn(), KviServerParser::parseNumericNames(), KviServerParser::parseNumericNoSuchNick(), KviServerParser::parseNumericNoTopic(), KviServerParser::parseNumericTopic(), KviServerParser::parseNumericTopicWhoTime(), KviServerParser::parseNumericUserhost(), KviServerParser::parseNumericUserMode(), KviServerParser::parseNumericWatch(), KviServerParser::parseNumericWhoisAuth(), KviServerParser::parseNumericWhoisAway(), KviServerParser::parseNumericWhoisChannels(), KviServerParser::parseNumericWhoisIdle(), KviServerParser::parseNumericWhoisOther(), KviServerParser::parseNumericWhoisServer(), KviServerParser::parseNumericWhoisUser(), KviServerParser::parseNumericWhowasUser(), KviIrcConnection::sendData(), and KviIrcConnection::sendFmtData().
void KviConsole::addHighlightedChannel (const QString & szChan)
Adds a channel to the highlight list.
Parameters:
szChan The channel name
Returns:
void
References m_pTmpHighLightedChannels.
int KviConsole::applyHighlighting (KviWindow * wnd, int type, const QString & nick, const QString & user, const QString & host, const QString & szMsg)
References KviWindow::connection(), KviRegisteredUser::getBoolProperty(), isHighlightedChannel(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_STRINGLIST, KVI_WINDOW_TYPE_CHANNEL, KviOption_boolAlwaysHighlightNick, KviOption_boolUseFullWordHighlighting, KviOption_boolUseWordHighlighting, KviOption_stringlistHighlightWords, KviOption_stringWordSplitters, KviIrcConnectionUserInfo::nickName(), KviIrcUserDataBase::registeredUser(), KviMircCntrl::stripControlBytes(), triggerOnHighlight(), KviWindow::type(), KviIrcConnection::userDataBase(), KviIrcConnection::userInfo(), and KviWindow::windowName().
Referenced by outputPrivmsg(), and KviServerParser::parseCtcpRequestAction().
void KviConsole::applyOptions () [protected, virtual]
Reimplemented from KviWindow.
References KviIrcView::applyOptions(), KviInput::applyOptions(), KviUserListView::applyOptions(), KviThemedComboBox::applyOptions(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_TRANSPARENT, KviOption_boolUseSpecifiedSmartColorForOwnNick, KviOption_uintUserIrcViewOwnBackground, KviOption_uintUserIrcViewOwnForeground, m_pAddressEdit, KviWindow::m_pInput, KviWindow::m_pIrcView, m_pNotifyListView, m_szOwnSmartColor, and KviQString::sprintf().
void KviConsole::avatarChanged (KviAvatar * avatar, const QString & nick, const QString & user, const QString & host, const QString & textLine)
References avatarChangedUpdateWindows(), KviWindow::connection(), currentNetworkName(), KviQString::equalCI(), KviAvatar::identificationString(), KviAvatarCache::instance(), KVI_OPTION_BOOL, KviOption_boolSetLastAvatarAsDefaultForRegisteredUsers, KviIrcUserDataBase::registeredUser(), KviAvatarCache::remove(), KviAvatarCache::replace(), KviRegisteredUser::setProperty(), KviQString::toUtf8(), and KviIrcConnection::userDataBase().
Referenced by currentAvatar(), KviServerParser::parseCtcpReplyAvatar(), KviServerParser::parseLiteralJoin(), setAvatar(), and setAvatarFromOptions().
void KviConsole::avatarChangedUpdateWindows (const QString & nick, const QString & textLine)
References _OUTPUT_QUIET, KviUserListView::avatarChanged(), c, KviIrcConnection::channelList(), KviWindow::connection(), KviPointerList< T >::first(), KVI_OUT_AVATAR, m_pNotifyListView, KviPointerList< T >::next(), and KviIrcConnection::queryList().
Referenced by avatarChanged(), checkDefaultAvatar(), and resetAvatarForMatchingUsers().
void KviConsole::checkDefaultAvatar (KviIrcUserEntry * e, const QString & nick, const QString & user, const QString & host)
References avatarChangedUpdateWindows(), KviWindow::connection(), currentNetworkName(), KviFileUtils::extractFileName(), g_pIconManager, KviIconManager::getAvatar(), KviRegisteredUser::getProperty(), KviAvatarCache::instance(), KviAvatarCache::lookup(), KviIrcUserDataBase::registeredUser(), KviAvatarCache::remove(), KviIrcUserEntry::setAvatar(), and KviIrcConnection::userDataBase().
Referenced by KviServerParser::parseLiteralJoin(), KviServerParser::parseNumericWhoisUser(), and KviQuery::setTarget().
void KviConsole::closeEvent (QCloseEvent * e) [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs, KviIrcContext::Connected, KviFrame::consoleCount(), context(), g_pApp, g_pFrame, KVI_OPTION_BOOL, KviOption_boolAlwaysDisconnectClosingConnectedConsole, KviOption_boolAlwaysQuitKVIrcClosingLastConsole, KviIrcContext::state(), KviIrcContext::terminateConnectionRequest(), and KviMessageBox::warning().
void KviConsole::completeChannel (const QString & word, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), currentNetworkName(), KviQString::equalCIN(), g_pApp, and KviApp::recentChannelsForNetwork().
Referenced by KviInputEditor::completion().
void KviConsole::completeServer (const QString & word, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), KviQString::cutFromLast(), KviQString::cutToFirst(), KviQString::equalCIN(), KVI_OPTION_STRINGLIST, and KviOption_stringlistRecentServers.
Referenced by KviInputEditor::completion().
void KviConsole::connectionAttached ()
References KviWindow::connection(), KviIrcContext::connection(), m_pContext, m_pNotifyListView, KviUserListView::setUserDataBase(), and updateUri().
Referenced by KviIrcContext::connectToCurrentServer().
void KviConsole::connectionDetached ()
References m_pNotifyListView, KviUserListView::partAll(), and KviUserListView::setUserDataBase().
Referenced by KviIrcContext::destroyConnection().
bool KviConsole::connectionInProgress ()
References context(), KviIrcContext::Idle, and state().
Referenced by KviIrcUrl::run().
KviIrcContext* KviConsole::context () [inline]
Reimplemented from KviWindow.
Referenced by closeEvent(), KviWindow::connection(), connectionInProgress(), KviWindow::context(), KviWindowListButton::drawButtonLabel(), KviIrcContextDisplay::drawContents(), fillContextPopup(), fillStatusString(), KviQuery::getBaseLogFileName(), getBaseLogFileName(), getWindowListTipText(), isNotConnected(), KviTreeWindowListItemDelegate::paint(), KviServerParser::parseNumericEndOfLinks(), KviServerParser::parseNumericLinks(), KviServerParser::parseNumericList(), KviServerParser::parseNumericListEnd(), KviServerParser::parseNumericListStart(), KviIrcContextDisplay::tipRequest(), and ~KviConsole().
KviAvatar * KviConsole::currentAvatar ()
References KviIrcUserEntry::avatar(), avatarChanged(), KviWindow::connection(), defaultAvatarFromOptions(), KviIrcUserDataBase::find(), KviIrcUserEntry::setAvatar(), and KviIrcConnection::userDataBase().
Referenced by KviServerParser::parseCtcpRequestAvatar().
QString KviConsole::currentNetworkName () [inline]
References KviWindow::connection().
Referenced by avatarChanged(), checkDefaultAvatar(), completeChannel(), KviApp::fillRecentChannelsPopup(), KviQuery::getBaseLogFileName(), KviQuery::pasteLastLog(), and KviChannel::pasteLastLog().
KviAvatar * KviConsole::defaultAvatarFromOptions ()
References KviAvatar::isValid(), KVI_OPTION_PIXMAP, KVI_OPTION_STRING, KviOption_pixmapMyAvatar, and KviOption_stringMyAvatar.
Referenced by currentAvatar(), KviIrcConnection::loginToIrcServer(), KviServerParser::parseLiteralJoin(), and setAvatarFromOptions().
void KviConsole::destroyConnection () [protected]
void KviConsole::executeInternalCommand (int index) [slot]
References kvi_getInternalCommandBuffer(), and KviIrcUrl::run().
void KviConsole::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References fillStatusString(), KviWindow::m_szPlainTextCaption, m_szStatusString, and KviWindow::windowName().
void KviConsole::fillContextPopup (KviTalPopupMenu * p) [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs, KviIrcConnection::channelList(), KviWindow::connection(), context(), KviPointerList< T >::count(), KviIrcContext::firstDeadChannel(), KviIrcContext::firstDeadQuery(), g_pIconManager, KviIconManager::getSmallIcon(), KviWindow::id(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KVI_SMALLICON_CHANNEL, KVI_SMALLICON_DEADCHANNEL, KVI_SMALLICON_DEADQUERY, KVI_SMALLICON_QUERY, m_pContext, KviIrcConnection::queryList(), and KviTalPopupMenu::setItemEnabled().
void KviConsole::fillStatusString () [protected]
References __tr2qs, KviIrcContext::Connected, KviIrcContext::Connecting, KviWindow::connection(), context(), KviIrcContext::Idle, KviIrcContext::LoggingIn, m_szStatusString, KviIrcConnectionServerInfo::name(), KviIrcConnectionUserInfo::nickName(), KviIrcConnection::serverInfo(), state(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userMode().
Referenced by fillCaptionBuffers(), and getWindowListTipText().
void KviConsole::getBaseLogFileName (QString & buffer) [protected, virtual]
Reimplemented from KviWindow.
References context().
static int KviConsole::getSmartColorHashForNick (QString * szNick) [static, protected]
void KviConsole::getUserTipText (const QString & nick, KviIrcUserEntry * e, QString & buffer)
References __tr2qs, KviIrcUserEntry::avatar(), KviWindow::connection(), KviRegisteredUserDataBase::findMatchingMask(), g_pRegisteredUserDataBase, KviIrcUserEntry::gender(), KviRegisteredUser::getProperty(), KviRegisteredUser::group(), KviIrcUserEntry::hasHops(), KviIrcUserEntry::hasRealName(), KviIrcUserEntry::hasServer(), KviIrcUserEntry::hops(), KviIrcUserEntry::host(), KviIrcUserEntry::isAway(), KviAvatar::localPath(), KviIrcUserEntry::Male, KviIrcMask::mask(), KviRegisteredMask::mask(), KviRegisteredUser::name(), KviIrcUserEntry::realName(), KviIrcUserEntry::server(), KviAvatar::size(), KviMircCntrl::stripControlBytes(), KviIrcUserEntry::Unknown, KviRegisteredMask::user(), and KviIrcUserEntry::user().
Referenced by KviIrcView::doLinkToolTip(), and KviUserListView::maybeTip().
void KviConsole::getWindowListTipText (QString & buffer) [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs, KviIrcConnection::channelList(), KviIrcContext::Connected, KviWindow::connection(), context(), KviPointerList< T >::count(), END_TABLE_BOLD_ROW, fillStatusString(), KviTimeUtils::formatTimeInterval(), KVI_OPTION_UINT, kvi_secondsSince, KviOption_uintOutputDatetimeFormat, m_szStatusString, KviTimeUtils::NoLeadingEmptyIntervals, KviTimeUtils::NoLeadingZeroes, KviIrcConnection::queryList(), START_TABLE_BOLD_ROW, START_TABLE_NORMAL_ROW, and state().
void KviConsole::ircUriChanged (const QString & text) [protected, slot]
References __tr2qs, KviIrcUrl::CurrentContext, KviIrcUrl::InvalidProtocol, KviIrcUrl::run(), and KviMessageBox::warning().
bool KviConsole::isConnected () [inline]
References KviWindow::context(), and KviIrcContext::isConnected().
Referenced by KviChannel::closeEvent(), KviIrcContextDisplay::drawContents(), KviApp::fillRecentChannelsPopup(), KviApp::fillRecentNicknamesPopup(), KviWindowListBase::getTextForConsole(), KviKvsCoreSimpleCommands::KVSCSC(), myIconPtr(), KviServerParser::parseNumericNicknameProblem(), KviServerParser::parseNumericUnavailResource(), KviChangeUserModeAction::popupActivated(), and KviApp::topmostConnectedConsole().
bool KviConsole::isHighlightedChannel (const QString & szChan) [inline]
Returns true if the channel is highlighted.
Parameters:
szChan The channel name
Returns:
bool
Referenced by applyHighlighting().
bool KviConsole::isIPv6Connection () [inline]
References KviWindow::connection(), KviServer::isIPv6(), KVI_ASSERT, KviIrcConnectionTarget::server(), and KviIrcConnection::target().
Referenced by KviServerParser::parseCtcpRequestDcc().
bool KviConsole::isNotConnected () [inline]
References context(), KviIrcContext::Idle, and state().
void KviConsole::loadProperties (KviConfig * cfg) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_pIrcView, m_pNotifyListView, KviWindow::m_pSplitter, KviConfig::readBoolEntry(), KviConfig::readIntListEntry(), and showNotifyList().
QPixmap * KviConsole::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), isConnected(), KVI_SMALLICON_CONSOLE, and KVI_SMALLICON_LINKS.
KviUserListView* KviConsole::notifyListView () [inline]
Referenced by KviWatchNotifyListManager::doMatchUser(), KviIsOnNotifyListManager::doMatchUser(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviWatchNotifyListManager::handleWatchReply(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviIrcConnection::nickChange(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviServerParser::parseLoginNicknameProblem(), KviWatchNotifyListManager::start(), KviStupidNotifyListManager::start(), KviIsOnNotifyListManager::start(), KviWatchNotifyListManager::stop(), KviStupidNotifyListManager::stop(), and KviIsOnNotifyListManager::stop().
void KviConsole::outputPrivmsg (KviWindow * wnd, int type, const QString & nick, const QString & user, const QString & host, const QString & msg, int iFlags = 0, const QString & prefix = QString(), const QString & suffix = QString())
References KviQString::appendFormatted(), applyHighlighting(), KviWindow::connection(), KviWindow::demandAttention(), KviIrcUserDataBase::find(), g_pApp, KviNickColors::getSmartColor(), KviNickColors::getSmartColorForNick(), KviWindow::hasAttention(), KviIrcConnectionUserInfo::hostName(), KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_HIGHLIGHT, KVI_OUT_QUERYNOTICE, KVI_OUT_QUERYNOTICECRYPTED, KVI_TEXT_BOLD, KVI_TEXT_COLOR, KVI_WINDOW_TYPE_CHANNEL, KviOption_boolBoldedNicks, KviOption_boolColorNicks, KviOption_boolFlashWindowOnHighlightedMessages, KviOption_boolPopupNotifierOnHighlightedMessages, KviOption_boolShowChannelUserFlagInPrivmsgView, KviOption_boolShowUserAndHostInPrivmsgView, KviOption_boolStripMircColorsInUserMessages, KviOption_boolUseExtendedPrivmsgView, KviOption_boolUseSpecifiedSmartColorForOwnNick, KviOption_stringExtendedPrivmsgPostfix, KviOption_stringExtendedPrivmsgPrefix, KviOption_uintNotifierAutoHideTime, m_szOwnSmartColor, KviIrcConnectionUserInfo::nickName(), NoHighlighting, NoNotifier, KviApp::notifierMessage(), NoWindowFlashing, KviIrcUserEntry::setSmartNickColor(), KviIrcUserEntry::smartNickColor(), KviQString::sprintf(), KviMircCntrl::stripControlBytes(), KviWindow::type(), KviIrcConnection::userDataBase(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
Referenced by KviKvsCoreSimpleCommands::KVSCSC(), KviQuery::ownMessage(), KviChannel::ownMessage(), KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
void KviConsole::recentUrlsChanged () [slot]
References g_pIconManager, KviIconManager::getSmallIcon(), KVI_OPTION_STRINGLIST, KVI_SMALLICON_URL, KviOption_stringlistRecentIrcUrls, and m_pAddressEdit.
void KviConsole::removeHighlightedChannel (const QString & szChan)
Removes a channel from the highlight list.
Parameters:
szChan The channel name
Returns:
void
References m_pTmpHighLightedChannels.
void KviConsole::resetAvatarForMatchingUsers (KviRegisteredUser * u)
References avatarChangedUpdateWindows(), KviWindow::connection(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), g_pIconManager, KviIconManager::getAvatar(), KviRegisteredUser::getProperty(), and KviRegisteredUser::matchesFixed().
void KviConsole::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, and KviWindow::m_pSplitter.
void KviConsole::saveProperties (KviConfig * cfg) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_pIrcView, m_pNotifyListView, m_pNotifyViewButton, and KviConfig::writeEntry().
int KviConsole::selectedCount () [inline]
References m_pNotifyListView, and KviUserListView::selectedCount().
KviAvatar * KviConsole::setAvatar (const QString & nick, const QString & user, const QString & host, const QString & szLocalPath, const QString & szName)
References __tr2qs, _OUTPUT_PARANOIC, avatarChanged(), KviWindow::connection(), KviQString::equalCI(), KviIrcUserDataBase::find(), g_pIconManager, KviIconManager::getAvatar(), KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasUser(), KviIrcUserEntry::host(), KVI_OUT_VERBOSE, KviWindow::output(), KviIrcUserEntry::setAvatar(), KviIrcUserEntry::user(), and KviIrcConnection::userDataBase().
Referenced by KviApp::fileDownloadTerminated().
void KviConsole::setAvatarFromOptions ()
References avatarChanged(), KviWindow::connection(), defaultAvatarFromOptions(), KviIrcUserDataBase::find(), KviIrcUserEntry::setAvatar(), and KviIrcConnection::userDataBase().
void KviConsole::showNotifyList (bool bShow) [protected]
References m_pNotifyListView, and m_pNotifyViewButton.
Referenced by loadProperties(), and toggleNotifyView().
QSize KviConsole::sizeHint () const [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pInput, KviWindow::m_pIrcView, and KviIrcView::sizeHint().
KviIrcContext::State KviConsole::state () [inline]
References KviWindow::context(), and KviIrcContext::state().
Referenced by connectionInProgress(), fillStatusString(), getWindowListTipText(), and isNotConnected().
const QString& KviConsole::statusString () [inline]
Referenced by KviWindowListBase::getTextForConsole().
void KviConsole::terminateConnectionRequest (bool bForce = false, const char * quitMsg = 0)
void KviConsole::textViewRightClicked () [protected, slot]
References KviEvent_OnConsolePopupRequest, and KVS_TRIGGER_EVENT_0.
void KviConsole::toggleNotifyView () [protected, slot]
References m_pNotifyListView, and showNotifyList().
void KviConsole::triggerCreationEvents () [protected, virtual]
Reimplemented from KviWindow.
References KviFrame::executeInternalCommand(), g_pFrame, KVI_CONSOLE_FLAG_FIRSTINAPP, KVI_CONSOLE_FLAG_FIRSTINFRAME, KVI_INTERNALCOMMAND_TIP_OPEN, KVI_OPTION_BOOL, KviEvent_OnFrameWindowCreated, KviEvent_OnIrcContextCreated, KviEvent_OnKVIrcStartup, KviOption_boolShowTipAtStartup, KVS_TRIGGER_EVENT_0, and m_iFlags.
int KviConsole::triggerOnHighlight (KviWindow * wnd, int type, const QString & nick, const QString & user, const QString & host, const QString & szMsg, const QString & trigger) [protected]
References g_pActiveWindow, KVI_OPTION_STRING, KVI_OUT_ACTION, KVI_OUT_HIGHLIGHT, KviEvent_OnHighlight, KviOption_stringOnHighlightedMessageSound, KVS_TRIGGER_EVENT_7_HALTED, KviIrcUrl::run(), and KviQString::sprintf().
Referenced by applyHighlighting().
void KviConsole::updateUri () [slot]
References c, KviIrcConnection::channelList(), KviWindow::connection(), KviIrcUrl::join(), KviPointerList< T >::last(), m_pAddressEdit, KviPointerList< T >::next(), KviIrcConnectionTarget::server(), and KviIrcConnection::target().
Referenced by connectionAttached().
Friends And Related Function Documentation
friend class KviChannel [friend]
friend class KviFrame [friend]
Reimplemented from KviWindow.
friend class KviIrcContext [friend]
friend class KviIrcSocket [friend]
friend class KviQuery [friend]
Member Data Documentation
int KviConsole::m_iFlags [protected]
Referenced by triggerCreationEvents().
KviThemedComboBox* KviConsole::m_pAddressEdit [protected]
Referenced by applyOptions(), recentUrlsChanged(), and updateUri().
KviIrcContext* KviConsole::m_pContext [protected]
Referenced by connectionAttached(), fillContextPopup(), and ~KviConsole().
KviUserListView* KviConsole::m_pNotifyListView [protected]
Referenced by applyOptions(), avatarChangedUpdateWindows(), connectionAttached(), connectionDetached(), loadProperties(), saveProperties(), selectedCount(), showNotifyList(), and toggleNotifyView().
KviWindowToolPageButton* KviConsole::m_pNotifyViewButton [protected]
Referenced by saveProperties(), and showNotifyList().
QStringList* KviConsole::m_pTmpHighLightedChannels [protected]
Referenced by addHighlightedChannel(), removeHighlightedChannel(), and ~KviConsole().
QString KviConsole::m_szOwnSmartColor [protected]
Referenced by applyOptions(), and outputPrivmsg().
QString KviConsole::m_szStatusString [protected]
Referenced by fillCaptionBuffers(), fillStatusString(), and getWindowListTipText().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_console.h
src/kvirc/ui/kvi_console.cpp