KVIrc: ScriptEditorWidget Class Reference
ScriptEditorWidget Class Reference
#include <ScriptEditorImplementation.h>
Public Slots
void checkReadyCompleter ()
void insertCompletion (const QString &szCompletion)
void slotFind ()
void slotHelp ()
void slotReplace ()
Signals
void keyPressed ()
Public Member Functions
QCompleter * completer () const
bool contextSensitiveHelp () const
void createCompleter (QStringList &list)
void disableSyntaxHighlighter ()
void enableSyntaxHighlighter ()
void loadCompleterFromFile ()
ScriptEditorWidget (QWidget *pParent)
ScriptEditorSyntaxHighlighter * syntaxHighlighter ()
QString textUnderCursor () const
void updateOptions ()
virtual ~ScriptEditorWidget ()
Public Attributes
QString m_szFind
Protected Slots
void asyncCompleterCreation ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
Protected Attributes
int iIndex
int iModulesCount
QCompleter * m_pCompleter
QStringList * m_pListCompletition
QStringList * m_pListModulesNames
QWidget * m_pParent
QTimer * m_pStartTimer
ScriptEditorSyntaxHighlighter * m_pSyntaxHighlighter
QString m_szHelp
Properties
bool contextSensitiveHelp
Constructor & Destructor Documentation
ScriptEditorWidget::ScriptEditorWidget (QWidget * pParent)
References asyncCompleterCreation(), bSemaphore, checkReadyCompleter(), KviApplication::ConfigPlugins, connect(), KviFileUtils::fileExists(), g_pApp, KviApplication::getLocalKvircDirectory(), iIndex, iModulesCount, loadCompleterFromFile(), m_pCompleter, m_pParent, m_pStartTimer, m_pSyntaxHighlighter, m_szFind, m_szHelp, and updateOptions().
ScriptEditorWidget::~ScriptEditorWidget () virtual
References disableSyntaxHighlighter(), and m_pCompleter.
Member Function Documentation
void ScriptEditorWidget::asyncCompleterCreation () protected slot
References bCompleterReady, KviApplication::ConfigPlugins, createCompleter(), d, f, g_pApp, g_pModuleManager, KviKvsKernel::getAllFunctionsCommandsCore(), KviKvsModuleInterface::getAllFunctionsCommandsModule(), KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviModuleManager::getModule(), iIndex, iModulesCount, KviKvsKernel::instance(), m_pListCompletition, m_pListModulesNames, m_pStartTimer, KviApplication::Modules, and szBuffer.
Referenced by ScriptEditorWidget().
void ScriptEditorWidget::checkReadyCompleter () slot
References bCompleterReady, loadCompleterFromFile(), and m_pStartTimer.
Referenced by ScriptEditorWidget().
QCompleter* ScriptEditorWidget::completer () const inline
References m_pCompleter.
void ScriptEditorWidget::contextMenuEvent (QContextMenuEvent * e) protected
References __tr2qs_ctx(), slotHelp(), and slotReplace().
bool ScriptEditorWidget::contextSensitiveHelp () const
Referenced by slotHelp().
void ScriptEditorWidget::createCompleter (QStringList & list)
References connect(), insertCompletion(), and m_pCompleter.
Referenced by asyncCompleterCreation(), and loadCompleterFromFile().
void ScriptEditorWidget::disableSyntaxHighlighter ()
References m_pSyntaxHighlighter.
Referenced by ScriptEditorImplementation::setUnHighlightedText(), updateOptions(), and ~ScriptEditorWidget().
void ScriptEditorWidget::enableSyntaxHighlighter ()
References m_pSyntaxHighlighter.
Referenced by ScriptEditorImplementation::setText(), and updateOptions().
void ScriptEditorWidget::insertCompletion (const QString & szCompletion) slot
References m_pCompleter.
Referenced by createCompleter().
void ScriptEditorWidget::keyPressed () signal
void ScriptEditorWidget::keyPressEvent (QKeyEvent * e) protected virtual
References m_pCompleter, and textUnderCursor().
void ScriptEditorWidget::loadCompleterFromFile ()
References KviApplication::ConfigPlugins, createCompleter(), f, g_pApp, KviApplication::getLocalKvircDirectory(), and szBuffer.
Referenced by checkReadyCompleter(), and ScriptEditorWidget().
void ScriptEditorWidget::slotFind () slot
References m_pParent, and m_szFind.
Referenced by ScriptEditorImplementation::setFindText().
void ScriptEditorWidget::slotHelp () slot
References contextSensitiveHelp().
Referenced by contextMenuEvent().
void ScriptEditorWidget::slotReplace () slot
References __tr2qs_ctx(), connect(), and m_pParent.
Referenced by contextMenuEvent().
ScriptEditorSyntaxHighlighter* ScriptEditorWidget::syntaxHighlighter () inline
References m_pSyntaxHighlighter.
QString ScriptEditorWidget::textUnderCursor () const
Referenced by keyPressEvent().
void ScriptEditorWidget::updateOptions ()
References disableSyntaxHighlighter(), enableSyntaxHighlighter(), g_clrBackground(), g_clrFind(), g_clrNormalText(), g_fntNormal(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolEnableCustomCursorWidth, KviOption_uintCustomCursorWidth, m_pParent, and p.
Referenced by ScriptEditorImplementation::optionsDialogFinished(), and ScriptEditorWidget().
Member Data Documentation
int ScriptEditorWidget::iIndex protected
Referenced by asyncCompleterCreation(), and ScriptEditorWidget().
int ScriptEditorWidget::iModulesCount protected
Referenced by asyncCompleterCreation(), and ScriptEditorWidget().
QCompleter* ScriptEditorWidget::m_pCompleter protected
Referenced by completer(), createCompleter(), insertCompletion(), keyPressEvent(), ScriptEditorWidget(), and ~ScriptEditorWidget().
QStringList* ScriptEditorWidget::m_pListCompletition protected
Referenced by asyncCompleterCreation().
QStringList* ScriptEditorWidget::m_pListModulesNames protected
Referenced by asyncCompleterCreation().
QWidget* ScriptEditorWidget::m_pParent protected
Referenced by ScriptEditorWidget(), slotFind(), slotReplace(), and updateOptions().
QTimer* ScriptEditorWidget::m_pStartTimer protected
Referenced by asyncCompleterCreation(), checkReadyCompleter(), and ScriptEditorWidget().
ScriptEditorSyntaxHighlighter* ScriptEditorWidget::m_pSyntaxHighlighter protected
Referenced by disableSyntaxHighlighter(), enableSyntaxHighlighter(), ScriptEditorWidget(), and syntaxHighlighter().
QString ScriptEditorWidget::m_szFind
Referenced by ScriptEditorSyntaxHighlighter::highlightBlock(), ScriptEditorWidget(), and slotFind().
QString ScriptEditorWidget::m_szHelp protected
Referenced by ScriptEditorWidget().
Property Documentation
bool ScriptEditorWidget::contextSensitiveHelp read
The documentation for this class was generated from the following files:
src/modules/editor/ScriptEditorImplementation.h
src/modules/editor/ScriptEditorImplementation.cpp