KVIrc: ClassEditorWindow Class Reference
ClassEditorWindow Class Reference
This is the Class Editor window.
#include <ClassEditorWindow.h>
Public Member Functions
ClassEditorWindow (KviMainWindow *pFrm)
Constructs the class editor window.
~ClassEditorWindow ()
Destroys the class editor window.
Protected Slots
void buildClicked ()
Called when we want to build the class.
void cancelClicked ()
Called when we click the cancel button.
void saveClicked ()
Called when we want to save the class.
Protected Member Functions
virtual void configGroupName (QString &szName)
Sets the configuration group name as classeditor.
virtual void loadProperties (KviConfigurationFile *pCfg)
Called to load the window properties.
virtual QPixmap * myIconPtr ()
Returns the class editor small icon.
virtual void saveProperties (KviConfigurationFile *pCfg)
Called to save the window properties.
Protected Attributes
ClassEditorWidget * m_pEditor
Detailed Description
This is the Class Editor window.
Constructor & Destructor Documentation
ClassEditorWindow::ClassEditorWindow (KviMainWindow * pFrm)
Constructs the class editor window.
Parameters:
pFrm The parent frame
Returns:
ClassEditorWindow
References __tr2qs_ctx(), KviIconManager::Accept, buildClicked(), cancelClicked(), connect(), KviIconManager::Discard, g_pIconManager, KviIconManager::getSmallIcon(), m_pEditor, saveClicked(), and KviWindow::setFixedCaption().
ClassEditorWindow::~ClassEditorWindow ()
Destroys the class editor window.
Member Function Documentation
void ClassEditorWindow::buildClicked () [protected, slot]
Called when we want to build the class.
Returns:
void
References ClassEditorWidget::build(), and m_pEditor.
Referenced by ClassEditorWindow().
void ClassEditorWindow::cancelClicked () [protected, slot]
Called when we click the cancel button.
Returns:
void
Referenced by ClassEditorWindow().
void ClassEditorWindow::configGroupName (QString & szName) [protected, virtual]
Sets the configuration group name as classeditor.
Parameters:
szName The name of the group
Returns:
void
void ClassEditorWindow::loadProperties (KviConfigurationFile * pCfg) [protected, virtual]
Called to load the window properties.
Parameters:
pCfg The configuration file
Returns:
void
Reimplemented from KviWindow.
References ClassEditorWidget::loadProperties(), and m_pEditor.
QPixmap * ClassEditorWindow::myIconPtr () [protected, virtual]
Returns the class editor small icon.
Returns:
QPixmap *
Reimplemented from KviWindow.
References KviIconManager::ClassEditor, g_pIconManager, and KviIconManager::getSmallIcon().
void ClassEditorWindow::saveClicked () [protected, slot]
Called when we want to save the class.
Returns:
void
References m_pEditor, and ClassEditorWidget::saveNotBuiltClasses().
Referenced by ClassEditorWindow().
void ClassEditorWindow::saveProperties (KviConfigurationFile * pCfg) [protected, virtual]
Called to save the window properties.
Parameters:
pCfg The configuration file
Returns:
void
Reimplemented from KviWindow.
References m_pEditor, and ClassEditorWidget::saveProperties().
Member Data Documentation
ClassEditorWidget* ClassEditorWindow::m_pEditor [protected]
Referenced by buildClicked(), ClassEditorWindow(), loadProperties(), saveClicked(), and saveProperties().
The documentation for this class was generated from the following files:
src/modules/classeditor/ClassEditorWindow.h
src/modules/classeditor/ClassEditorWindow.cpp