KVIrc: KviSeparatorAction Class Reference
KviSeparatorAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
virtual QAction * addToCustomToolBar (KviCustomToolBar *pTool)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (KviTalPopupMenu *pMenu)
Adds the action to the given popup.
KviSeparatorAction (QObject *pParent)
Constructor & Destructor Documentation
KviSeparatorAction::KviSeparatorAction (QObject * pParent)
Member Function Documentation
QAction * KviSeparatorAction::addToCustomToolBar (KviCustomToolBar * pParentToolBar) [virtual]
Adds the action to the given toolbar.
Parameters:
pParentToolBar The toolbar where to add the action
Returns:
QAction *
Reimplemented from KviAction.
References KVI_COREACTION_SEPARATOR, KviAction::registerAction(), KviAction::setup(), KviAction::setupDone(), and w.
bool KviSeparatorAction::addToPopupMenu (KviTalPopupMenu * pMenu) [virtual]
Adds the action to the given popup.
Parameters:
pMenu The menu where to add the action
Returns:
bool
Reimplemented from KviAction.
References KviTalPopupMenu::insertSeparator(), KviAction::setup(), and KviAction::setupDone().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp