KVIrc: KviKvsPopupMenuItemMenu Class Reference
KviKvsPopupMenuItemMenu Class Reference
#include <KviKvsPopupMenu.h>
Public Member Functions
virtual void clear ()
virtual KviKvsPopupMenuItem * clone () const
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)
KviKvsPopupMenu * menu ()
virtual ~KviKvsPopupMenuItemMenu ()
Public Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
QPixmap * evaluateIcon (KviKvsPopupMenuTopLevelData *pData)
QString evaluateText (KviKvsPopupMenuTopLevelData *pData)
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
virtual ~KviKvsPopupMenuItemWithTextAndIcon ()
Public Member Functions inherited from KviKvsPopupMenuItem
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
virtual KviKvsScript * kvsCode ()
KviKvsScript * kvsCondition ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItemMenu (const QString &szItemName, KviKvsPopupMenu *pMenu, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemMenu (const QString &szItemName, KviKvsPopupMenu *pMenu, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItem
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Protected Attributes
KviKvsPopupMenu * m_pMenu
Protected Attributes inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsScript * m_pKvsIcon
KviKvsScript * m_pKvsText
Protected Attributes inherited from KviKvsPopupMenuItem
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Friends
class KviKvsPopupMenu
Additional Inherited Members
Public Types inherited from KviKvsPopupMenuItem
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Constructor & Destructor Documentation
KviKvsPopupMenuItemMenu::KviKvsPopupMenuItemMenu (const QString & szItemName, KviKvsPopupMenu * pMenu, const QString & szText, const QString & szIcon, const QString & szCondition) protected
References m_pMenu.
Referenced by clone().
KviKvsPopupMenuItemMenu::KviKvsPopupMenuItemMenu (const QString & szItemName, KviKvsPopupMenu * pMenu, const KviKvsScript * pText, const KviKvsScript * pIcon, const KviKvsScript * pCondition) protected
References m_pMenu.
KviKvsPopupMenuItemMenu::~KviKvsPopupMenuItemMenu () virtual
References m_pMenu.
Member Function Documentation
void KviKvsPopupMenuItemMenu::clear () virtual
Reimplemented from KviKvsPopupMenuItem.
References KviKvsPopupMenu::clearMenuContents(), and m_pMenu.
KviKvsPopupMenuItem * KviKvsPopupMenuItemMenu::clone () const virtual
Implements KviKvsPopupMenuItem.
References KviMemory::copy(), KviKvsPopupMenu::copyFrom(), KviKvsPopupMenu, KviKvsPopupMenuItemMenu(), KviKvsPopupMenuItem::m_pKvsCondition, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsIcon, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsText, m_pMenu, KviKvsPopupMenuItem::m_szItemName, and KviKvsPopupMenu::popupName().
void KviKvsPopupMenuItemMenu::fill (KviKvsPopupMenu * pMenu, KviKvsPopupMenuTopLevelData * pData, int iIdx) virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), m_pMenu, and KviKvsPopupMenu::setParentPopup().
KviKvsPopupMenu* KviKvsPopupMenuItemMenu::menu () inline
Friends And Related Function Documentation
friend class KviKvsPopupMenu friend
Referenced by clone().
Member Data Documentation
KviKvsPopupMenu* KviKvsPopupMenuItemMenu::m_pMenu protected
Referenced by clear(), clone(), fill(), KviKvsPopupMenuItemMenu(), and ~KviKvsPopupMenuItemMenu().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp