KVIrc: LogListViewLog Class Reference
LogListViewLog Class Reference
#include <LogViewWidget.h>
Public Member Functions
virtual QString fileName () const
LogListViewLog (QTreeWidgetItem *pPar, LogFile::Type eType, LogFile *pLog)
~LogListViewLog ()
Public Member Functions inherited from LogListViewItem
LogFile * log ()
LogListViewItem (QTreeWidgetItem *pPar, LogFile::Type eType, LogFile *pLog)
LogListViewItem (QTreeWidget *pPar, LogFile::Type eType, LogFile *pLog)
~LogListViewItem ()
Protected Member Functions
bool operator< (const QTreeWidgetItem &other) const
Additional Inherited Members
Public Attributes inherited from LogListViewItem
LogFile::Type m_eType
LogFile * m_pFileData
Constructor & Destructor Documentation
LogListViewLog::LogListViewLog (QTreeWidgetItem * pPar, LogFile::Type eType, LogFile * pLog)
References LogFile::date(), and LogListViewItem::m_pFileData.
LogListViewLog::~LogListViewLog () inline
Member Function Documentation
virtual QString LogListViewLog::fileName () const inline virtual
Reimplemented from LogListViewItem.
References LogFile::fileName(), and LogListViewItem::m_pFileData.
bool LogListViewLog::operator< (const QTreeWidgetItem & other) const inline protected
References LogFile::date(), and LogListViewItem::m_pFileData.
The documentation for this class was generated from the following files:
src/modules/logview/LogViewWidget.h
src/modules/logview/LogViewWidget.cpp