KVIrc: KvsObject_trayIcon Class Reference
KvsObject_trayIcon Class Reference
#include <KvsObject_trayIcon.h>
Protected Slots
void slotActivated (QSystemTrayIcon::ActivationReason)
void slotMessageClicked ()
Protected Member Functions
bool activatedEvent (KviKvsObjectFunctionCall *c)
bool hide (KviKvsObjectFunctionCall *c)
bool isVisible (KviKvsObjectFunctionCall *c)
bool messageClickedEvent (KviKvsObjectFunctionCall *c)
bool setContextMenu (KviKvsObjectFunctionCall *c)
bool setIcon (KviKvsObjectFunctionCall *c)
bool setTooltip (KviKvsObjectFunctionCall *c)
bool show (KviKvsObjectFunctionCall *c)
bool showMessage (KviKvsObjectFunctionCall *c)
Protected Attributes
QSystemTrayIcon * m_pTrayIcon
Member Function Documentation
bool KvsObject_trayIcon::activatedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::hide (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::isVisible (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::messageClickedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::setContextMenu (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::setIcon (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::setTooltip (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::show (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_trayIcon::showMessage (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_trayIcon::slotActivated (QSystemTrayIcon::ActivationReason reason) [protected, slot]
References KviKvsVariantList::append(), and KviKvsObject::callFunction().
void KvsObject_trayIcon::slotMessageClicked () [protected, slot]
References KviKvsObject::callFunction().
Member Data Documentation
QSystemTrayIcon* KvsObject_trayIcon::m_pTrayIcon [protected]
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_trayIcon.h
src/modules/objects/KvsObject_trayIcon.cpp