KVIrc: KviKvsKernel Class Reference
KviKvsKernel Class Reference
#include <KviKvsKernel.h>
Public Member Functions
KviKvsAsyncOperationManager * asyncOperationManager ()
void completeCommand (const QString &szCommandBegin, KviPointerList< QString > *pMatches)
KviPointerList< QString > * completeCommandAllocateResult (const QString &szCommandBegin)
void completeFunction (const QString &szFunctionBegin, KviPointerList< QString > *pMatches)
KviPointerList< QString > * completeFunctionAllocateResult (const QString &szFunctionBegin)
void completeModuleCommand (const QString &szModuleName, const QString &szCommandBegin, KviPointerList< QString > *matches)
void completeModuleFunction (const QString &szModuleName, const QString &szFunctionBegin, KviPointerList< QString > *matches)
KviKvsVariantList * emptyParameterList ()
KviKvsCoreCallbackCommandExecRoutine * findCoreCallbackCommandExecRoutine (const QString &szCmdName)
KviKvsCoreFunctionExecRoutine * findCoreFunctionExecRoutine (const QString &szFncName)
KviKvsCoreSimpleCommandExecRoutine * findCoreSimpleCommandExecRoutine (const QString &szCmdName)
KviKvsSpecialCommandParsingRoutine * findSpecialCommandParsingRoutine (const QString &szCmdName)
void freeCompletionResult (KviPointerList< QString > *l)
void getAllFunctionsCommandsCore (QStringList *list)
KviKvsHash * globalVariables ()
KviKvsKernel ()
KviKvsObjectController * objectController ()
void registerCoreCallbackCommandExecRoutine (const QString &szCmdName, KviKvsCoreCallbackCommandExecRoutine *r)
void registerCoreFunctionExecRoutine (const QString &szFncName, KviKvsCoreFunctionExecRoutine *r)
void registerCoreSimpleCommandExecRoutine (const QString &szCmdName, KviKvsCoreSimpleCommandExecRoutine *r)
void registerSpecialCommandParsingRoutine (const QString &szCmdName, KviKvsSpecialCommandParsingRoutine *r)
~KviKvsKernel ()
Static Public Member Functions
static void done ()
static void init ()
static KviKvsKernel * instance ()
Private Attributes
KviKvsAsyncOperationManager * m_pAsyncOperationManager
KviPointerHashTable< QString,
KviKvsCoreCallbackCommandExecRoutine > * m_pCoreCallbackCommandExecRoutineDict
KviPointerHashTable< QString,
KviKvsCoreFunctionExecRoutine > * m_pCoreFunctionExecRoutineDict
KviPointerHashTable< QString,
KviKvsCoreSimpleCommandExecRoutine > * m_pCoreSimpleCommandExecRoutineDict
KviKvsVariantList * m_pEmptyParameterList
KviKvsHash * m_pGlobalVariables
KviKvsObjectController * m_pObjectController
KviPointerHashTable< QString,
KviKvsSpecialCommandParsingRoutine > * m_pSpecialCommandParsingRoutineDict
Static Private Attributes
static KviKvsKernel * m_pKvsKernel = 0
Constructor & Destructor Documentation
KviKvsKernel::KviKvsKernel ()
References KviKvsObjectController::init(), init(), m_pAsyncOperationManager, m_pCoreCallbackCommandExecRoutineDict, m_pCoreFunctionExecRoutineDict, m_pCoreSimpleCommandExecRoutineDict, m_pEmptyParameterList, m_pGlobalVariables, m_pKvsKernel, m_pObjectController, m_pSpecialCommandParsingRoutineDict, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviKvsKernel::~KviKvsKernel ()
References m_pAsyncOperationManager, m_pCoreCallbackCommandExecRoutineDict, m_pCoreFunctionExecRoutineDict, m_pCoreSimpleCommandExecRoutineDict, m_pEmptyParameterList, m_pGlobalVariables, m_pObjectController, and m_pSpecialCommandParsingRoutineDict.
Member Function Documentation
KviKvsAsyncOperationManager* KviKvsKernel::asyncOperationManager () inline
Referenced by KviKvsAsyncOperation::KviKvsAsyncOperation(), and KviKvsAsyncOperation::~KviKvsAsyncOperation().
void KviKvsKernel::completeCommand (const QString & szCommandBegin, KviPointerList< QString > * pMatches)
References COMPLETE_COMMAND_BY_DICT, completeCommand(), completeModuleCommand(), KviModuleManager::completeModuleNames(), g_pModuleManager, instance(), m_pCoreCallbackCommandExecRoutineDict, m_pCoreSimpleCommandExecRoutineDict, and m_pSpecialCommandParsingRoutineDict.
Referenced by completeCommand(), completeFunction(), and KviInputEditor::completion().
KviPointerList<QString>* KviKvsKernel::completeCommandAllocateResult (const QString & szCommandBegin) inline
References p, and KviPointerList< T >::setAutoDelete().
void KviKvsKernel::completeFunction (const QString & szFunctionBegin, KviPointerList< QString > * pMatches)
References KviPointerList< T >::append(), completeCommand(), completeModuleFunction(), KviModuleManager::completeModuleNames(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviQString::equalCIN(), KviPointerList< T >::first(), g_pModuleManager, instance(), l, m_pCoreFunctionExecRoutineDict, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by KviInputEditor::completion().
KviPointerList<QString>* KviKvsKernel::completeFunctionAllocateResult (const QString & szFunctionBegin) inline
References p, and KviPointerList< T >::setAutoDelete().
void KviKvsKernel::completeModuleCommand (const QString & szModuleName, const QString & szCommandBegin, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), KviKvsModuleInterface::completeCommand(), KviPointerList< T >::first(), g_pModuleManager, KviModuleManager::getModule(), KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by completeCommand().
void KviKvsKernel::completeModuleFunction (const QString & szModuleName, const QString & szFunctionBegin, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), KviKvsModuleInterface::completeFunction(), KviPointerList< T >::first(), g_pModuleManager, KviModuleManager::getModule(), KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by completeFunction().
void KviKvsKernel::done () static
References m_pKvsKernel.
KviKvsVariantList* KviKvsKernel::emptyParameterList () inline
Referenced by KviKvsObject::callFunction(), and KviKvsScript::execute().
KviKvsCoreCallbackCommandExecRoutine* KviKvsKernel::findCoreCallbackCommandExecRoutine (const QString & szCmdName) inline
Referenced by KviKvsParser::parseCommand().
KviKvsCoreFunctionExecRoutine* KviKvsKernel::findCoreFunctionExecRoutine (const QString & szFncName) inline
Referenced by KviKvsParser::parseDollar(), and KviKvsParser::parsePercentOrDollar().
KviKvsCoreSimpleCommandExecRoutine* KviKvsKernel::findCoreSimpleCommandExecRoutine (const QString & szCmdName) inline
Referenced by KviKvsParser::parseCommand(), and KviKvsParser::parseSpecialCommandHelp().
KviKvsSpecialCommandParsingRoutine* KviKvsKernel::findSpecialCommandParsingRoutine (const QString & szCmdName) inline
Referenced by KviKvsParser::parseCommand().
void KviKvsKernel::freeCompletionResult (KviPointerList< QString > * l) inline
References l.
void KviKvsKernel::getAllFunctionsCommandsCore (QStringList * list)
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pCoreFunctionExecRoutineDict, and m_pCoreSimpleCommandExecRoutineDict.
Referenced by ScriptEditorWidget::asyncCompleterCreation().
KviKvsHash* KviKvsKernel::globalVariables () inline
Referenced by KviKvsRunTimeContext::globalVariables().
void KviKvsKernel::init () static
References KviKvsKernel(), and m_pKvsKernel.
Referenced by KviKvsKernel().
static KviKvsKernel* KviKvsKernel::instance () inline static
Referenced by ScriptEditorWidget::asyncCompleterCreation(), ClassEditorWidget::build(), KviKvsObject::callFunction(), completeCommand(), completeFunction(), KviInputEditor::completion(), KviKvsObject::emitSignal(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KvsObject_widget::eventFilter(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsScript::execute(), KviKvs::flushUserClasses(), KviApplication::frameDestructorCallback(), KviKvsObject::function_setProperty(), KviKvsRunTimeContext::globalVariables(), KviKvsObject::inheritsClass(), KviKvsCoreFunctions::init(), KviKvsCoreSimpleCommands::init(), KviKvsParser::init(), KviKvsCoreCallbackCommands::init(), KviClassEditorDialog::KviClassEditorDialog(), KviKvsAsyncOperation::KviKvsAsyncOperation(), KviKvsObject::KviKvsObject(), KviKvsObjectClass::KviKvsObjectClass(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), KviKvsTreeNodeScopeOperator::objectFromVariant(), objects_kvs_cmd_clearObjects(), objects_kvs_cmd_connect(), objects_kvs_cmd_disconnect(), objects_kvs_cmd_killClass(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_classes(), objects_kvs_fnc_exists(), objects_kvs_fnc_instances(), objects_kvs_fnc_name(), objects_kvs_fnc_variables(), ClassEditorWidget::oneTimeSetup(), KvsObject_tableWidget::paint(), KviKvsParser::parseCommand(), KviKvsParser::parseDollar(), KviKvsParser::parsePercentOrDollar(), KviKvsParser::parseSpecialCommandHelp(), ClassEditorWidget::removeItem(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), ClassEditorWidget::renameNamespace(), ClassEditorWidget::saveNotBuiltClasses(), KvsObject_socket::slotNewConnection(), KviKvsAsyncOperation::~KviKvsAsyncOperation(), KviKvsObject::~KviKvsObject(), and KviKvsObjectClass::~KviKvsObjectClass().
KviKvsObjectController* KviKvsKernel::objectController () inline
Referenced by ClassEditorWidget::build(), KviKvsObject::emitSignal(), KvsObject_widget::eventFilter(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvs::flushUserClasses(), KviApplication::frameDestructorCallback(), KviKvsObject::function_setProperty(), KviKvsObject::inheritsClass(), KviKvsObject::KviKvsObject(), KviKvsObjectClass::KviKvsObjectClass(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), KviKvsTreeNodeScopeOperator::objectFromVariant(), objects_kvs_cmd_clearObjects(), objects_kvs_cmd_connect(), objects_kvs_cmd_disconnect(), objects_kvs_cmd_killClass(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_exists(), objects_kvs_fnc_instances(), objects_kvs_fnc_name(), objects_kvs_fnc_variables(), ClassEditorWidget::oneTimeSetup(), KvsObject_tableWidget::paint(), ClassEditorWidget::removeItem(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), ClassEditorWidget::renameNamespace(), ClassEditorWidget::saveNotBuiltClasses(), KvsObject_socket::slotNewConnection(), KviKvsObject::~KviKvsObject(), and KviKvsObjectClass::~KviKvsObjectClass().
void KviKvsKernel::registerCoreCallbackCommandExecRoutine (const QString & szCmdName, KviKvsCoreCallbackCommandExecRoutine * r) inline
void KviKvsKernel::registerCoreFunctionExecRoutine (const QString & szFncName, KviKvsCoreFunctionExecRoutine * r) inline
void KviKvsKernel::registerCoreSimpleCommandExecRoutine (const QString & szCmdName, KviKvsCoreSimpleCommandExecRoutine * r) inline
void KviKvsKernel::registerSpecialCommandParsingRoutine (const QString & szCmdName, KviKvsSpecialCommandParsingRoutine * r) inline
Member Data Documentation
KviKvsAsyncOperationManager* KviKvsKernel::m_pAsyncOperationManager private
Referenced by KviKvsKernel(), and ~KviKvsKernel().
KviPointerHashTable<QString,KviKvsCoreCallbackCommandExecRoutine>* KviKvsKernel::m_pCoreCallbackCommandExecRoutineDict private
Referenced by completeCommand(), KviKvsKernel(), and ~KviKvsKernel().
KviPointerHashTable<QString,KviKvsCoreFunctionExecRoutine>* KviKvsKernel::m_pCoreFunctionExecRoutineDict private
Referenced by completeFunction(), getAllFunctionsCommandsCore(), KviKvsKernel(), and ~KviKvsKernel().
KviPointerHashTable<QString,KviKvsCoreSimpleCommandExecRoutine>* KviKvsKernel::m_pCoreSimpleCommandExecRoutineDict private
Referenced by completeCommand(), getAllFunctionsCommandsCore(), KviKvsKernel(), and ~KviKvsKernel().
KviKvsVariantList* KviKvsKernel::m_pEmptyParameterList private
Referenced by KviKvsKernel(), and ~KviKvsKernel().
KviKvsHash* KviKvsKernel::m_pGlobalVariables private
Referenced by KviKvsKernel(), and ~KviKvsKernel().
KviKvsKernel * KviKvsKernel::m_pKvsKernel = 0 static private
Referenced by done(), init(), and KviKvsKernel().
KviKvsObjectController* KviKvsKernel::m_pObjectController private
Referenced by KviKvsKernel(), and ~KviKvsKernel().
KviPointerHashTable<QString,KviKvsSpecialCommandParsingRoutine>* KviKvsKernel::m_pSpecialCommandParsingRoutineDict private
Referenced by completeCommand(), KviKvsKernel(), and ~KviKvsKernel().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsKernel.h
src/kvirc/kvs/KviKvsKernel.cpp