KVIrc: OptionsWidget_windowListClassic Class Reference
OptionsWidget_windowListClassic Class Reference
#include <OptionsWidget_windowList.h>
Public Member Functions
OptionsWidget_windowListClassic (QWidget *parent)
~OptionsWidget_windowListClassic ()
Constructor & Destructor Documentation
OptionsWidget_windowListClassic::OptionsWidget_windowListClassic (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::createLayout(), g, KviOption_boolClassicWindowListSetMaximumButtonWidth, KviOption_boolUseFlatClassicWindowListButtons, KviOption_colorWindowListHighlight1Text, KviOption_colorWindowListHighlight2Text, KviOption_colorWindowListHighlight3Text, KviOption_colorWindowListHighlight4Text, KviOption_colorWindowListHighlight5Text, KviOption_colorWindowListMinimizedText, KviOption_colorWindowListNormalText, KviOption_colorWindowListProgressBar, KviOption_fontWindowList, KviOption_uintClassicWindowListMaximumButtonWidth, and KviOption_uintWindowListButtonMinWidth.
OptionsWidget_windowListClassic::~OptionsWidget_windowListClassic ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_windowList.h
src/modules/options/OptionsWidget_windowList.cpp