KVIrc: KviKvsTimer Class Reference
KviKvsTimer Class Reference
#include <KviKvsTimerManager.h>
Public Types
enum Lifetime { SingleShot, WindowLifetime, Persistent }
Public Member Functions
const KviKvsScript * callback ()
int delay ()
int id ()
Lifetime lifetime ()
const QString & name ()
KviKvsVariantList * parameterList ()
KviKvsExtendedRunTimeData * runTimeData ()
KviWindow * window ()
~KviKvsTimer ()
Protected Member Functions
KviKvsTimer (const QString &szName, Lifetime l, KviWindow *pWnd, int iDelay, int iId, KviKvsScript *pCallback, KviKvsVariantList *pParams)
void setWindow (KviWindow *pWnd)
Protected Attributes
Lifetime m_eLifetime
int m_iDelay
int m_iId
KviKvsScript * m_pCallback
KviKvsVariantList * m_pParameterList
KviKvsExtendedRunTimeData * m_pRunTimeData
KviWindow * m_pWnd
QString m_szName
Friends
class KviKvsTimerManager
Member Enumeration Documentation
enum KviKvsTimer::Lifetime
Enumerator:
SingleShot
WindowLifetime
Persistent
Constructor & Destructor Documentation
KviKvsTimer::KviKvsTimer (const QString & szName, Lifetime l, KviWindow * pWnd, int iDelay, int iId, KviKvsScript * pCallback, KviKvsVariantList * pParams) [protected]
References l, m_eLifetime, m_iDelay, m_iId, m_pCallback, m_pParameterList, m_pRunTimeData, m_pWnd, and m_szName.
KviKvsTimer::~KviKvsTimer ()
References m_pCallback, m_pParameterList, and m_pRunTimeData.
Member Function Documentation
const KviKvsScript* KviKvsTimer::callback () [inline]
Referenced by KviKvsTimerManager::timerEvent().
int KviKvsTimer::delay () [inline]
int KviKvsTimer::id () [inline]
References m_iId.
Referenced by KviKvsTimerManager::addTimer(), KviKvsTimerManager::deleteTimer(), and KviKvsTimerManager::timerEvent().
Lifetime KviKvsTimer::lifetime () [inline]
Referenced by KviKvsTimerManager::timerEvent().
const QString& KviKvsTimer::name () [inline]
Referenced by KviKvsTimerManager::deleteTimer(), and KviKvsTimerManager::timerEvent().
KviKvsVariantList* KviKvsTimer::parameterList () [inline]
Referenced by KviKvsTimerManager::timerEvent().
KviKvsExtendedRunTimeData* KviKvsTimer::runTimeData () [inline]
Referenced by KviKvsTimerManager::timerEvent().
void KviKvsTimer::setWindow (KviWindow * pWnd) [inline, protected]
Referenced by KviKvsTimerManager::timerEvent().
KviWindow* KviKvsTimer::window () [inline]
Referenced by KviKvsTimerManager::timerEvent().
Friends And Related Function Documentation
friend class KviKvsTimerManager [friend]
Member Data Documentation
Lifetime KviKvsTimer::m_eLifetime [protected]
Referenced by KviKvsTimer().
int KviKvsTimer::m_iDelay [protected]
Referenced by KviKvsTimer().
int KviKvsTimer::m_iId [protected]
Referenced by KviKvsTimer().
KviKvsScript* KviKvsTimer::m_pCallback [protected]
Referenced by KviKvsTimer(), and ~KviKvsTimer().
KviKvsVariantList* KviKvsTimer::m_pParameterList [protected]
Referenced by KviKvsTimer(), and ~KviKvsTimer().
KviKvsExtendedRunTimeData* KviKvsTimer::m_pRunTimeData [protected]
Referenced by KviKvsTimer(), and ~KviKvsTimer().
KviWindow* KviKvsTimer::m_pWnd [protected]
Referenced by KviKvsTimer().
QString KviKvsTimer::m_szName [protected]
Referenced by KviKvsTimer().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsTimerManager.h
src/kvirc/kvs/KviKvsTimerManager.cpp