KVIrc: KviParameterList Class Reference
KviParameterList Class Reference
#include <KviParameterList.h>
Public Member Functions
bool getBool ()
int getInt (bool *bOk=0)
QPoint getPoint (bool *bOk=0)
QRect getRect (bool *bOk=0)
QSize getSize (bool *bOk=0)
unsigned int getUInt (bool *bOk=0)
void init ()
KviParameterList ()
KviParameterList (KviCString *p1)
KviParameterList (KviCString *p1, KviCString *p2)
KviParameterList (KviCString *p1, KviCString *p2, KviCString *p3)
KviParameterList (KviCString *p1, KviCString *p2, KviCString *p3, KviCString *p4)
KviParameterList (KviCString *p1, KviCString *p2, KviCString *p3, KviCString *p4, KviCString *p5)
KviParameterList (KviCString *p1, KviCString *p2, KviCString *p3, KviCString *p4, KviCString *p5, KviCString *p6)
KviParameterList (KviCString *p1, KviCString *p2, KviCString *p3, KviCString *p4, KviCString *p5, KviCString *p6, KviCString *p7)
KviParameterList (const char *paramBuffer)
KviCString * safeFirst ()
const char * safeFirstParam ()
KviCString * safeNext ()
const char * safeNextParam ()
virtual ~KviParameterList ()
Public Member Functions inherited from KviPointerList< KviCString >
void append (const KviCString *d)
Appends an item at the end of the list.
void append (KviPointerList< KviCString > *l)
Appends all the items from the list l to this list.
KviCString * at (int idx)
Returns the item at index position.
bool autoDelete ()
Returns the autodelete flag.
void clear ()
Removes all the items from the list.
void copyFrom (KviPointerList< KviCString > *l)
Clears the list and inserts all the items from the list l.
unsigned int count () const
Returns the count of the items in the list.
KviCString * current ()
Returns the current iteration item.
int findRef (const KviCString *d)
Returns the position of an item.
KviCString * first ()
Returns the first item in the list.
void insert (int iIndex, const KviCString *d)
Inserts the item d at the position specified by iIndex.
void insertAfter (const KviCString *ref, const KviCString *d)
Inserts the item d after the item ref.
void insertBefore (const KviCString *ref, const KviCString *d)
Inserts the item d before the item ref.
void inSort (KviCString *t)
Inserts the item respecting the sorting order inside the list.
void invert ()
Inverts the elements in the list.
bool isEmpty () const
Returns true if the list is empty.
KviPointerListIterator
< KviCString > iteratorAt (int idx)
Returns an iterator pointing to the item at the specified index.
KviPointerListIterator
< KviCString > iteratorAtCurrent ()
Returns an iterator pointing to the current item in the list.
KviPointerListIterator
< KviCString > iteratorAtFirst ()
Returns an iterator pointing to the first item of the list.
KviPointerListIterator
< KviCString > iteratorAtLast ()
Returns an iterator pointing to the first item of the list.
KviPointerListIterator
< KviCString > iteratorAtRef (const KviCString *d)
Returns an iterator pointing to the item with pointer d.
KviPointerList (bool bAutoDelete=true)
Creates a template list.
KviCString * last ()
Returns the last item in the list.
void merge (KviPointerList< KviCString > *src)
Inserts the list src inside this list.
KviCString * next ()
Returns the next item in the list.
KviPointerList< KviCString > & operator= (KviPointerList< KviCString > &l)
Clears the list and inserts all the items from the list l.
void prepend (KviPointerList< KviCString > *l)
Prepends all the items from the list l to this list.
void prepend (const KviCString *d)
Inserts the item d in the head position.
KviCString * prev ()
Returns the previous item in the list.
bool remove (int iIndex)
Removes the item at zero-based position iIndex.
bool removeCurrent ()
Removes the current iteration item.
bool removeFirst ()
Removes the first item (if any)
bool removeLast ()
Removes the firstitem (if any)
bool removeRef (const KviCString *d)
Removes the item pointed by d (if found in the list)
KviCString * safeCurrent ()
Returns the current iteration item.
void setAutoDelete (bool bAutoDelete)
Sets the autodelete flag.
void sort ()
Sorts this list in ascending order.
void swap (KviPointerList< KviCString > *src)
Swap the lists.
KviCString * takeFirst ()
Removes the first element from the list.
KviCString * takeLast ()
Removes the last item (if any) and returns it. This function obviously never deletes the item (regadless of autoDeletion()).
virtual ~KviPointerList ()
Destroys the list.
Private Attributes
KviCString m_szEmpty
Additional Inherited Members
Protected Member Functions inherited from KviPointerList< KviCString >
void grabFirstAndPrepend (KviPointerList< KviCString > *src)
Grabs the first element from the list src and puts it as the first element of this list.
void insertBeforeSafe (KviPointerListNode *ref, const KviCString *d)
Inserts the item d before the item ref.
void removeCurrentSafe ()
Removes the current iteration item assuming that it is valid.
Protected Attributes inherited from KviPointerList< KviCString >
bool m_bAutoDelete
KviPointerListNode * m_pAux
KviPointerListNode * m_pHead
KviPointerListNode * m_pTail
unsigned int m_uCount
Constructor & Destructor Documentation
KviParameterList::KviParameterList ()
References KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1, KviCString * p2)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1, KviCString * p2, KviCString * p3)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1, KviCString * p2, KviCString * p3, KviCString * p4)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1, KviCString * p2, KviCString * p3, KviCString * p4, KviCString * p5)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1, KviCString * p2, KviCString * p3, KviCString * p4, KviCString * p5, KviCString * p6)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (KviCString * p1, KviCString * p2, KviCString * p3, KviCString * p4, KviCString * p5, KviCString * p6, KviCString * p7)
References KviPointerList< KviCString >::append(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::KviParameterList (const char * paramBuffer)
References KviPointerList< KviCString >::append(), kvi_extractToken(), and KviPointerList< KviCString >::setAutoDelete().
KviParameterList::~KviParameterList () virtual
Member Function Documentation
bool KviParameterList::getBool ()
References KviPointerList< KviCString >::current(), kvi_strEqualCS(), KviPointerList< KviCString >::next(), and KviCString::ptr().
int KviParameterList::getInt (bool * bOk = 0)
References KviPointerList< KviCString >::current(), KviPointerList< KviCString >::next(), and KviCString::toInt().
QPoint KviParameterList::getPoint (bool * bOk = 0)
References KviPointerList< KviCString >::current(), i, KviPointerList< KviCString >::next(), and KviCString::toInt().
QRect KviParameterList::getRect (bool * bOk = 0)
References KviPointerList< KviCString >::current(), i, KviPointerList< KviCString >::next(), and KviCString::toInt().
QSize KviParameterList::getSize (bool * bOk = 0)
References KviPointerList< KviCString >::current(), i, KviPointerList< KviCString >::next(), and KviCString::toInt().
unsigned int KviParameterList::getUInt (bool * bOk = 0)
References KviPointerList< KviCString >::current(), KviPointerList< KviCString >::next(), and KviCString::toUInt().
void KviParameterList::init () inline
References first().
KviCString * KviParameterList::safeFirst ()
References f, KviPointerList< KviCString >::first(), and m_szEmpty.
const char* KviParameterList::safeFirstParam () inline
KviCString * KviParameterList::safeNext ()
References f, m_szEmpty, and KviPointerList< KviCString >::next().
const char* KviParameterList::safeNextParam () inline
Member Data Documentation
KviCString KviParameterList::m_szEmpty private
Referenced by safeFirst(), and safeNext().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviParameterList.h
src/kvilib/ext/KviParameterList.cpp