KVIrc: KviKvsCallbackMessageBox Class Reference
KviKvsCallbackMessageBox Class Reference
#include <libkvidialog.h>
Public Member Functions
KviKvsCallbackMessageBox (const QString &szCaption, const QString &szText, const QString &szIcon, const QString &szButton0, const QString &szButton1, const QString &szButton2, const QString &szCode, KviKvsVariantList *pMagicParams, KviWindow *pWindow, bool modal=false)
~KviKvsCallbackMessageBox ()
Public Member Functions inherited from KviKvsCallbackObject
KviKvsCallbackObject (const QString &szCallbackSource, KviWindow *pTargetWindow, const QString &szCallbackCode, KviKvsVariantList *pMagicParams, unsigned int uFlags=0)
virtual ~KviKvsCallbackObject ()
Protected Slots
virtual void done (int code)
Additional Inherited Members
Public Types inherited from KviKvsCallbackObject
enum CallbackFlags { OnlyIfWindowExists = 1 }
enum CallbackStatus { Success, Error, HaltEncountered, TargetWindowDead }
Protected Member Functions inherited from KviKvsCallbackObject
CallbackStatus execute (KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0)
Protected Attributes inherited from KviKvsCallbackObject
KviKvsVariantList * m_pMagicParams
KviKvsScript * m_pScript
KviWindow * m_pTargetConsole
KviWindow * m_pTargetWindow
unsigned int m_uFlags
Constructor & Destructor Documentation
KviKvsCallbackMessageBox::KviKvsCallbackMessageBox (const QString & szCaption, const QString & szText, const QString & szIcon, const QString & szButton0, const QString & szButton1, const QString & szButton2, const QString & szCode, KviKvsVariantList * pMagicParams, KviWindow * pWindow, bool modal = false)
References KviPointerList< T >::append(), KviQString::equalCI(), g_pIconManager, and KviIconManager::getImage().
KviKvsCallbackMessageBox::~KviKvsCallbackMessageBox ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void KviKvsCallbackMessageBox::done (int code) protected virtual slot
References KviKvsVariantList::append(), KviKvs::done(), and KviKvsCallbackObject::execute().
The documentation for this class was generated from the following files:
src/modules/dialog/libkvidialog.h
src/modules/dialog/libkvidialog.cpp