KVIrc: KviIOGraphWindow Class Reference
KviIOGraphWindow Class Reference
#include <libkviiograph.h>
Public Member Functions
KviIOGraphWindow (KviModuleExtensionDescriptor *d, KviMainWindow *lpFrm, const char *name)
~KviIOGraphWindow ()
Protected Member Functions
virtual void die ()
virtual void fillCaptionBuffers ()
virtual void moveEvent (QMoveEvent *)
virtual QPixmap * myIconPtr ()
virtual void paintEvent (QPaintEvent *e)
virtual void resizeEvent (QResizeEvent *e)
Private Member Functions
virtual void updatePseudoTransparency ()
Private Attributes
KviIOGraphWidget * m_pIOGraph
Constructor & Destructor Documentation
KviIOGraphWindow::KviIOGraphWindow (KviModuleExtensionDescriptor * d, KviMainWindow * lpFrm, const char * name)
References m_pIOGraph.
KviIOGraphWindow::~KviIOGraphWindow ()
References m_pIOGraph.
Member Function Documentation
void KviIOGraphWindow::die () [protected, virtual]
Implements KviModuleExtension.
void KviIOGraphWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs, and KviWindow::m_szPlainTextCaption.
void KviIOGraphWindow::moveEvent (QMoveEvent *) [protected, virtual]
Reimplemented from KviWindow.
References updatePseudoTransparency().
QPixmap * KviIOGraphWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::SayIcon.
void KviIOGraphWindow::paintEvent (QPaintEvent * e) [protected, virtual]
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorTreeWindowListBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviMainWindow::mdiManager(), KviWindow::mdiParent(), p, KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
void KviIOGraphWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References m_pIOGraph.
void KviIOGraphWindow::updatePseudoTransparency () [private, virtual]
Referenced by moveEvent().
Member Data Documentation
KviIOGraphWidget* KviIOGraphWindow::m_pIOGraph [private]
Referenced by KviIOGraphWindow(), resizeEvent(), and ~KviIOGraphWindow().
The documentation for this class was generated from the following files:
src/modules/iograph/libkviiograph.h
src/modules/iograph/libkviiograph.cpp