KVIrc: ListWindow Class Reference
ListWindow Class Reference
#include <ListWindow.h>
Public Member Functions
virtual void control (int iMsg)
virtual void die ()
ListWindow (KviConsoleWindow *lpConsole)
virtual void processData (KviIrcMessage *pMsg)
virtual QSize sizeHint () const
~ListWindow ()
Public Member Functions inherited from KviWindow
void activateSelf ()
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual void ownAction (const QString &)
virtual void ownMessage (const QString &, bool=true)
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
virtual const QString & target ()
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Public Member Functions inherited from KviExternalServerDataParser
KviExternalServerDataParser ()
virtual ~KviExternalServerDataParser ()
Protected Slots
void connectionStateChange ()
void exportList ()
void flush ()
void importList ()
void itemDoubleClicked (QTreeWidgetItem *it, int)
void liveSearch (const QString &szText)
void requestList ()
void stoplistdownload ()
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual void applyOptions ()
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &szBuffer)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
virtual void closeEvent (QCloseEvent *pEvent)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void loadProperties (KviConfigurationFile *pCfg)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual void preprocessMessage (QString &szMessage)
virtual void saveProperties (KviConfigurationFile *pCfg)
void setType (Type eType)
virtual void triggerCreationEvents ()
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
QTimer * m_pFlushTimer
KviThemedLabel * m_pInfoLabel
KviPointerList
< ChannelTreeWidgetItemData > * m_pItemList
QToolButton * m_pOpenButton
KviThemedLineEdit * m_pParamsEdit
QToolButton * m_pRequestButton
QToolButton * m_pSaveButton
QToolButton * m_pStopListDownloadButton
QSplitter * m_pTopSplitter
ChannelTreeWidget * m_pTreeWidget
QSplitter * m_pVertSplitter
Protected Attributes inherited from KviWindow
bool m_bIsDocked
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Private Member Functions
void endOfList ()
void reset ()
void startOfList ()
Additional Inherited Members
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void maximize ()
void minimize ()
void reloadImages ()
void restore ()
void savePropertiesAsDefault ()
void undock ()
Signals inherited from KviWindow
void windowNameChanged ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Constructor & Destructor Documentation
ListWindow::ListWindow (KviConsoleWindow * lpConsole)
References __tr2qs, KviTalToolTip::add(), KviPointerList< T >::append(), connect(), connectionStateChange(), KviConsoleWindow::context(), exportList(), g_pIconManager, KviIconManager::getBigIcon(), KviIconManager::getSmallIcon(), importList(), itemDoubleClicked(), KVI_BIGICON_OPEN, KVI_BIGICON_SAVE, KviTalSplitter, KviIconManager::List, liveSearch(), KviWindow::m_pConsole, m_pFlushTimer, m_pInfoLabel, KviWindow::m_pIrcView, m_pItemList, m_pOpenButton, m_pParamsEdit, m_pRequestButton, m_pSaveButton, KviWindow::m_pSplitter, m_pStopListDownloadButton, m_pTopSplitter, m_pTreeWidget, m_pVertSplitter, KviIconManager::NickNameProblem, requestList(), KviPointerList< T >::setAutoDelete(), KviIrcContext::setListWindowPointer(), KviTalHBox::setMargin(), KviTalHBox::setSpacing(), KviTalHBox::setStretchFactor(), and stoplistdownload().
ListWindow::~ListWindow ()
References KviConsoleWindow::context(), KviWindow::m_pConsole, m_pFlushTimer, m_pItemList, KviPointerList< T >::removeRef(), KviPointerList< T >::setAutoDelete(), and KviIrcContext::setListWindowPointer().
Member Function Documentation
void ListWindow::applyOptions () protected virtual
Reimplemented from KviWindow.
References KviThemedLineEdit::applyOptions(), KviThemedLabel::applyOptions(), KviThemedTreeWidget::applyOptions(), KviIrcView::applyOptions(), m_pInfoLabel, KviWindow::m_pIrcView, m_pParamsEdit, and m_pTreeWidget.
void ListWindow::connectionStateChange () protected slot
References __tr2qs, KviIrcContext::Connected, KviWindow::connection(), KviConsoleWindow::context(), KviConsoleWindow::currentNetworkName(), KviIrcConnection::currentServerName(), KviWindow::m_pConsole, m_pInfoLabel, m_pRequestButton, and KviIrcContext::state().
Referenced by ListWindow().
void ListWindow::control (int iMsg) virtual
Reimplemented from KviExternalServerDataParser.
References endOfList(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_ENDOFDATA, EXTERNAL_SERVER_DATA_PARSER_CONTROL_RESET, EXTERNAL_SERVER_DATA_PARSER_CONTROL_STARTOFDATA, reset(), and startOfList().
void ListWindow::die () virtual
Reimplemented from KviExternalServerDataParser.
Referenced by list_module_cleanup().
void ListWindow::endOfList () private
References __tr2qs, flush(), KVI_OUT_SYSTEMMESSAGE, m_pFlushTimer, m_pRequestButton, and KviWindow::outputNoFmt().
Referenced by control().
void ListWindow::exportList () protected slot
References __tr2qs, KviFileDialog::askForSaveFileName(), KviConfigurationFile::clear(), KviWindow::connection(), i, ChannelTreeWidgetItem::itemData(), KVI_OPTION_UINT, KviOption_uintOutputDatetimeFormat, m_pTreeWidget, ChannelTreeWidgetItemData::m_szChan, ChannelTreeWidgetItemData::m_szTopic, ChannelTreeWidgetItemData::m_szUsers, KviConfigurationFile::setGroup(), KviMessageBox::warning(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by ListWindow().
void ListWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References __tr2qs, KviConsoleWindow::context(), KviIrcContext::id(), KviWindow::m_pConsole, and KviWindow::m_szPlainTextCaption.
void ListWindow::flush () protected slot
References d, KviPointerList< T >::first(), m_pItemList, m_pTreeWidget, and KviPointerList< T >::removeFirst().
Referenced by endOfList(), importList(), and processData().
void ListWindow::getBaseLogFileName (QString & szBuffer) protected virtual
Reimplemented from KviWindow.
References KviWindow::context().
void ListWindow::importList () protected slot
References __tr2qs, KviPointerList< T >::append(), KviFileDialog::askForOpenFileName(), KviPointerList< T >::clear(), KviConfigurationFile::dict(), flush(), KVI_FILTER_CONFIG, m_pItemList, m_pTreeWidget, KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviPointerList< T >::setAutoDelete(), and KviConfigurationFile::setGroup().
Referenced by ListWindow().
void ListWindow::itemDoubleClicked (QTreeWidgetItem * it, int) protected slot
References KviWindow::connection(), KviIrcConnection::encodeText(), KviWindow::m_pConsole, and KviIrcConnection::sendFmtData().
Referenced by ListWindow().
void ListWindow::liveSearch (const QString & szText) protected slot
References i, ChannelTreeWidgetItem::itemData(), m_pTreeWidget, ChannelTreeWidgetItemData::m_szChan, and ChannelTreeWidgetItemData::m_szTopic.
Referenced by ListWindow().
QPixmap * ListWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::List.
void ListWindow::processData (KviIrcMessage * pMsg) virtual
Reimplemented from KviExternalServerDataParser.
References __tr2qs, _OUTPUT_VERBOSE, KviIrcMessage::allParams(), KviPointerList< T >::append(), connect(), KviIrcMessage::connection(), KviIrcConnection::decodeText(), flush(), KVI_OUT_LIST, m_pFlushTimer, m_pItemList, m_pParamsEdit, m_pRequestButton, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void ListWindow::requestList () protected slot
References __tr2qs, KviWindow::connection(), KviIrcConnection::encodeText(), KviConsoleWindow::isConnected(), KviCString::isEmpty(), KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KviWindow::m_pConsole, m_pParamsEdit, m_pRequestButton, KviWindow::outputNoFmt(), KviCString::ptr(), and KviIrcConnection::sendFmtData().
Referenced by ListWindow().
void ListWindow::reset () private
References __tr2qs, KVI_OUT_SYSTEMMESSAGE, and KviWindow::outputNoFmt().
Referenced by control().
void ListWindow::resizeEvent (QResizeEvent * e) protected virtual
References KviWindow::m_pSplitter, and m_pTopSplitter.
QSize ListWindow::sizeHint () const virtual
References KviWindow::m_pSplitter.
void ListWindow::startOfList () private
References KviPointerList< T >::clear(), m_pItemList, m_pRequestButton, m_pTreeWidget, and KviPointerList< T >::setAutoDelete().
Referenced by control().
void ListWindow::stoplistdownload () protected slot
References __tr2qs, KviWindow::connection(), KviConsoleWindow::isConnected(), KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KviWindow::m_pConsole, KviWindow::outputNoFmt(), and KviIrcConnection::sendFmtData().
Referenced by ListWindow().
Member Data Documentation
QTimer* ListWindow::m_pFlushTimer protected
Referenced by endOfList(), ListWindow(), processData(), and ~ListWindow().
KviThemedLabel* ListWindow::m_pInfoLabel protected
Referenced by applyOptions(), connectionStateChange(), and ListWindow().
KviPointerList<ChannelTreeWidgetItemData>* ListWindow::m_pItemList protected
Referenced by flush(), importList(), ListWindow(), processData(), startOfList(), and ~ListWindow().
QToolButton* ListWindow::m_pOpenButton protected
Referenced by ListWindow().
KviThemedLineEdit* ListWindow::m_pParamsEdit protected
Referenced by applyOptions(), ListWindow(), processData(), and requestList().
QToolButton* ListWindow::m_pRequestButton protected
Referenced by connectionStateChange(), endOfList(), ListWindow(), processData(), requestList(), and startOfList().
QToolButton* ListWindow::m_pSaveButton protected
Referenced by ListWindow().
QToolButton* ListWindow::m_pStopListDownloadButton protected
Referenced by ListWindow().
QSplitter* ListWindow::m_pTopSplitter protected
Referenced by ListWindow(), and resizeEvent().
ChannelTreeWidget* ListWindow::m_pTreeWidget protected
Referenced by applyOptions(), exportList(), flush(), importList(), ListWindow(), liveSearch(), and startOfList().
QSplitter* ListWindow::m_pVertSplitter protected
Referenced by ListWindow().
The documentation for this class was generated from the following files:
src/modules/list/ListWindow.h
src/modules/list/ListWindow.cpp