KVIrc: KviKvsRunTimeContext Class Reference
KviKvsRunTimeContext Class Reference
#include <KviKvsRunTimeContext.h>
Public Member Functions
KviKvsSwitchList * aliasSwitchList ()
bool breakPending ()
void clearError ()
KviIrcConnection * connection ()
KviConsoleWindow * console ()
KviIrcContext * context ()
bool continuePending ()
KviKvsTreeNode * defaultReportLocation ()
void disableReporting ()
void enableReporting ()
void enterBlockingSection ()
bool error () const
void error (const QString &szMsgFmt,...)
void error (KviKvsTreeNode *pNode, const QString &szMsgFmt,...)
bool errorNoIrcContext ()
KviKvsHash * extendedScopeVariables ()
KviKvsHash * globalVariables ()
bool haltCalled ()
void handleBreak ()
void handleContinue ()
bool leaveBlockingSection ()
KviKvsHash * localVariables ()
KviKvsVariantList * parameterList ()
QString * popupId ()
bool reportingDisabled ()
KviKvsVariant * returnValue ()
KviKvsScript * script ()
QString * scriptFilePath ()
void setBreakPending ()
void setContinuePending ()
void setDefaultReportLocation (KviKvsTreeNode *pNode)
void setHaltCalled ()
void setWindow (KviWindow *pWnd)
KviKvsVariant * swapReturnValuePointer (KviKvsVariant *pNewPointer)
KviKvsObject * thisObject ()
void warning (KviKvsTreeNode *pNode, const QString &szMsgFmt,...)
void warning (const QString &szMsgFmt,...)
bool warningMissingParameter ()
bool warningNoIrcConnection ()
KviWindow * window ()
~KviKvsRunTimeContext ()
Protected Types
enum RunTimeFlags { BreakPending = 1, ContinuePending = 2, HaltCalled = 4, DisableReporting = 8 }
Protected Member Functions
KviKvsRunTimeContext (KviKvsScript *pScript, KviWindow *pWnd, KviKvsVariantList *pParams, KviKvsVariant *pRetVal, KviKvsExtendedRunTimeData *pExtData=0)
void report (bool bError, KviKvsTreeNode *pNode, const QString &szMsgFmt, kvi_va_list va)
Protected Attributes
bool m_bError
KviKvsTreeNode * m_pDefaultReportLocation
KviKvsExtendedRunTimeData * m_pExtendedData
KviKvsHash * m_pLocalVariables
KviKvsVariantList * m_pParameterList
KviKvsVariant * m_pReturnValue
KviKvsScript * m_pScript
KviWindow * m_pWindow
unsigned int m_uRunTimeFlags
Friends
class KviKvsEventManager
class KviKvsObject
class KviKvsRunTimeCall
class KviKvsScript
Member Enumeration Documentation
enum KviKvsRunTimeContext::RunTimeFlags [protected]
Enumerator:
BreakPending
ContinuePending
HaltCalled
DisableReporting
Constructor & Destructor Documentation
KviKvsRunTimeContext::KviKvsRunTimeContext (KviKvsScript * pScript, KviWindow * pWnd, KviKvsVariantList * pParams, KviKvsVariant * pRetVal, KviKvsExtendedRunTimeData * pExtData = 0) [protected]
References m_bError, m_pDefaultReportLocation, m_pExtendedData, m_pLocalVariables, m_pParameterList, m_pReturnValue, m_pScript, m_pWindow, and m_uRunTimeFlags.
KviKvsRunTimeContext::~KviKvsRunTimeContext ()
References m_pLocalVariables.
Member Function Documentation
KviKvsSwitchList* KviKvsRunTimeContext::aliasSwitchList () [inline]
bool KviKvsRunTimeContext::breakPending () [inline]
Referenced by KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandSwitch::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), and KviKvsTreeNodeSpecialCommandDo::execute().
void KviKvsRunTimeContext::clearError () [inline]
KviIrcConnection* KviKvsRunTimeContext::connection () [inline]
KviConsoleWindow* KviKvsRunTimeContext::console () [inline]
References KviWindow::console().
KviIrcContext* KviKvsRunTimeContext::context () [inline]
bool KviKvsRunTimeContext::continuePending () [inline]
Referenced by KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), and KviKvsTreeNodeSpecialCommandDo::execute().
KviKvsTreeNode* KviKvsRunTimeContext::defaultReportLocation () [inline]
Referenced by KviKvsRunTimeCall::error(), and KviKvsRunTimeCall::warning().
void KviKvsRunTimeContext::disableReporting () [inline]
Referenced by KviKvsScript::execute(), and KviKvsScript::run().
void KviKvsRunTimeContext::enableReporting () [inline]
Referenced by KviKvsScript::run().
void KviKvsRunTimeContext::enterBlockingSection ()
bool KviKvsRunTimeContext::error () const [inline]
Referenced by KviKvsObject::callFunction(), errorNoIrcContext(), KviKvsTreeNodeArrayElement::evaluateIndex(), KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand(), KviKvsTreeNodeExpressionBinaryOperator::evaluateOperands(), KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeExtendedScopeVariable::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandSwitch::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), KviKvsTreeNodeSpecialCommandDo::execute(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationDecrement::execute(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsScript::executeInternal(), KviKvsParameterProcessor::handleParameterTypeError(), KviKvsTreeNodeScopeOperator::objectFromVariant(), and KviKvsParameterProcessor::process().
void KviKvsRunTimeContext::error (const QString & szMsgFmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, m_bError, m_pDefaultReportLocation, and report().
void KviKvsRunTimeContext::error (KviKvsTreeNode * pNode, const QString & szMsgFmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, m_bError, and report().
bool KviKvsRunTimeContext::errorNoIrcContext ()
References __tr2qs_ctx(), error(), and m_pDefaultReportLocation.
Referenced by links_kvs_cmd_open(), list_kvs_cmd_open(), socketspy_kvs_cmd_open(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), and tmphighlight_kvs_fnc_isnickhighlighted().
KviKvsHash* KviKvsRunTimeContext::extendedScopeVariables () [inline]
Referenced by KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly(), and KviKvsTreeNodeExtendedScopeVariable::evaluateReadWrite().
KviKvsHash * KviKvsRunTimeContext::globalVariables ()
References KviKvsKernel::globalVariables(), and KviKvsKernel::instance().
Referenced by KviKvsTreeNodeGlobalVariable::evaluateReadOnly(), and KviKvsTreeNodeGlobalVariable::evaluateReadWrite().
bool KviKvsRunTimeContext::haltCalled () [inline]
Referenced by KviKvsScript::executeInternal().
void KviKvsRunTimeContext::handleBreak () [inline]
Referenced by KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandSwitch::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), and KviKvsTreeNodeSpecialCommandDo::execute().
void KviKvsRunTimeContext::handleContinue () [inline]
Referenced by KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), and KviKvsTreeNodeSpecialCommandDo::execute().
bool KviKvsRunTimeContext::leaveBlockingSection ()
References g_pApp, KviApplication::kviClosingDown(), m_pWindow, and KviApplication::windowExists().
KviKvsHash* KviKvsRunTimeContext::localVariables () [inline]
Referenced by KviKvsTreeNodeLocalVariable::evaluateReadOnly(), and KviKvsTreeNodeLocalVariable::evaluateReadWrite().
KviKvsVariantList* KviKvsRunTimeContext::parameterList () [inline]
Referenced by KviKvsTreeNodeSingleParameterIdentifier::evaluateReadOnly(), and KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly().
QString* KviKvsRunTimeContext::popupId () [inline]
Referenced by popup_kvs_fnc_currentItemId().
void KviKvsRunTimeContext::report (bool bError, KviKvsTreeNode * pNode, const QString & szMsgFmt, kvi_va_list va) [protected]
References __tr2qs_ctx(), KviPointerList< T >::append(), KviKvsScript::buffer(), KviKvsTreeNode::contextDescription(), KviKvsReport::findLineAndCol(), KviKvsReport::findLineColAndListing(), KviKvsTreeNode::location(), m_pScript, m_pWindow, KviKvsScript::name(), KviKvsTreeNode::parent(), KviKvsReport::RunTimeError, KviKvsReport::RunTimeWarning, KviPointerList< T >::setAutoDelete(), KviKvsReport::setCallStack(), KviKvsReport::setCodeListing(), and KviQString::vsprintf().
Referenced by error(), KviKvsRunTimeCall::error(), warning(), and KviKvsRunTimeCall::warning().
bool KviKvsRunTimeContext::reportingDisabled () [inline]
Referenced by KviKvsScript::run().
KviKvsVariant* KviKvsRunTimeContext::returnValue () [inline]
Referenced by KviKvsTreeNodeParameterReturn::execute(), KviKvsTreeNodeExpressionReturn::execute(), perl_kvs_cmd_begin(), and python_kvs_cmd_begin().
KviKvsScript* KviKvsRunTimeContext::script () [inline]
QString* KviKvsRunTimeContext::scriptFilePath () [inline]
void KviKvsRunTimeContext::setBreakPending () [inline]
Referenced by KviKvsTreeNodeSpecialCommandSwitchLabelDefault::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelMatch::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), and KviKvsTreeNodeSpecialCommandBreak::execute().
void KviKvsRunTimeContext::setContinuePending () [inline]
Referenced by KviKvsTreeNodeSpecialCommandContinue::execute().
void KviKvsRunTimeContext::setDefaultReportLocation (KviKvsTreeNode * pNode)
References m_pDefaultReportLocation.
Referenced by KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeCoreFunctionCall::evaluateReadOnly(), KviKvsTreeNodeThisObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeBaseObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeCoreSimpleCommand::execute(), and KviKvsTreeNodeCoreCallbackCommand::execute().
void KviKvsRunTimeContext::setHaltCalled () [inline]
void KviKvsRunTimeContext::setWindow (KviWindow * pWnd) [inline]
Referenced by KviKvsTreeNodeRebindingSwitch::execute().
KviKvsVariant * KviKvsRunTimeContext::swapReturnValuePointer (KviKvsVariant * pNewPointer)
References m_pReturnValue.
Referenced by KviKvsTreeNodeCommandEvaluation::evaluateReadOnly().
KviKvsObject* KviKvsRunTimeContext::thisObject () [inline]
Referenced by KviKvsTreeNodeThisObjectFunctionCall::evaluateReadOnlyInObjectScope(), and KviKvsTreeNodeBaseObjectFunctionCall::evaluateReadOnlyInObjectScope().
void KviKvsRunTimeContext::warning (const QString & szMsgFmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, m_pDefaultReportLocation, and report().
void KviKvsRunTimeContext::warning (KviKvsTreeNode * pNode, const QString & szMsgFmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, and report().
Referenced by KviKvsObjectClass::allocateInstance(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeRebindingSwitch::execute(), KviKvsTreeNodeOperationStringSubstitution::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), warningMissingParameter(), and warningNoIrcConnection().
bool KviKvsRunTimeContext::warningMissingParameter ()
References __tr2qs_ctx(), m_pDefaultReportLocation, and warning().
bool KviKvsRunTimeContext::warningNoIrcConnection ()
References __tr2qs_ctx(), m_pDefaultReportLocation, and warning().
KviWindow* KviKvsRunTimeContext::window () [inline]
Referenced by KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeRebindingSwitch::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsObject::function_listProperties(), and KviKvsScript::run().
Friends And Related Function Documentation
friend class KviKvsEventManager [friend]
friend class KviKvsObject [friend]
friend class KviKvsRunTimeCall [friend]
friend class KviKvsScript [friend]
Member Data Documentation
bool KviKvsRunTimeContext::m_bError [protected]
Referenced by error(), and KviKvsRunTimeContext().
KviKvsTreeNode* KviKvsRunTimeContext::m_pDefaultReportLocation [protected]
Referenced by error(), errorNoIrcContext(), KviKvsRunTimeContext(), setDefaultReportLocation(), warning(), warningMissingParameter(), and warningNoIrcConnection().
KviKvsExtendedRunTimeData* KviKvsRunTimeContext::m_pExtendedData [protected]
Referenced by KviKvsRunTimeContext().
KviKvsHash* KviKvsRunTimeContext::m_pLocalVariables [protected]
Referenced by KviKvsRunTimeContext(), and ~KviKvsRunTimeContext().
KviKvsVariantList* KviKvsRunTimeContext::m_pParameterList [protected]
Referenced by KviKvsRunTimeContext().
KviKvsVariant* KviKvsRunTimeContext::m_pReturnValue [protected]
Referenced by KviKvsRunTimeContext(), and swapReturnValuePointer().
KviKvsScript* KviKvsRunTimeContext::m_pScript [protected]
Referenced by KviKvsRunTimeContext(), and report().
KviWindow* KviKvsRunTimeContext::m_pWindow [protected]
Referenced by KviKvsRunTimeContext(), leaveBlockingSection(), and report().
unsigned int KviKvsRunTimeContext::m_uRunTimeFlags [protected]
Referenced by KviKvsRunTimeContext().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsRunTimeContext.h
src/kvirc/kvs/KviKvsRunTimeContext.cpp