KVIrc: KviKvsTreeNodeExpressionVariableOperand Class Reference
KviKvsTreeNodeExpressionVariableOperand Class Reference
#include <kvi_kvs_treenode_expression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
KviKvsTreeNodeExpressionVariableOperand (const QChar *pLocation, KviKvsTreeNodeData *pData)
~KviKvsTreeNodeExpressionVariableOperand ()
Protected Attributes
KviKvsTreeNodeData * m_pData
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionVariableOperand::KviKvsTreeNodeExpressionVariableOperand (const QChar * pLocation, KviKvsTreeNodeData * pData)
References m_pData, and KviKvsTreeNode::setParent().
KviKvsTreeNodeExpressionVariableOperand::~KviKvsTreeNodeExpressionVariableOperand ()
References m_pData.
Member Function Documentation
void KviKvsTreeNodeExpressionVariableOperand::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeExpression.
void KviKvsTreeNodeExpressionVariableOperand::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeExpression.
References KviKvsTreeNodeData::dump(), and m_pData.
bool KviKvsTreeNodeExpressionVariableOperand::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadOnly(), and m_pData.
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeExpressionVariableOperand::m_pData [protected]
Referenced by dump(), evaluateReadOnly(), KviKvsTreeNodeExpressionVariableOperand(), and ~KviKvsTreeNodeExpressionVariableOperand().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_expression.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_expression.cpp