KVIrc: KviKvsTreeNodeInstructionBlock Class Reference
KviKvsTreeNodeInstructionBlock Class Reference
#include <KviKvsTreeNodeInstructionBlock.h>
Public Member Functions
void addInstruction (KviKvsTreeNodeInstruction *i)
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
unsigned int instructionCount ()
KviKvsTreeNodeInstructionBlock (const QChar *pLocation)
KviKvsTreeNodeInstruction * releaseFirst ()
~KviKvsTreeNodeInstructionBlock ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviPointerList
< KviKvsTreeNodeInstruction > * m_pInstructionList
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeInstructionBlock::KviKvsTreeNodeInstructionBlock (const QChar * pLocation)
References m_pInstructionList, and KviPointerList< T >::setAutoDelete().
KviKvsTreeNodeInstructionBlock::~KviKvsTreeNodeInstructionBlock ()
References m_pInstructionList.
Member Function Documentation
void KviKvsTreeNodeInstructionBlock::addInstruction (KviKvsTreeNodeInstruction * i)
References KviPointerList< T >::append(), m_pInstructionList, and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseInstructionBlock(), and KviKvsParser::parseInstructionList().
void KviKvsTreeNodeInstructionBlock::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeInstruction.
void KviKvsTreeNodeInstructionBlock::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeInstruction.
References KviPointerList< T >::first(), i, m_pInstructionList, and KviPointerList< T >::next().
bool KviKvsTreeNodeInstructionBlock::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References KviPointerListIterator< T >::current(), i, and m_pInstructionList.
unsigned int KviKvsTreeNodeInstructionBlock::instructionCount () inline
Referenced by KviKvsParser::parseInstructionBlock(), and KviKvsParser::parseInstructionList().
KviKvsTreeNodeInstruction * KviKvsTreeNodeInstructionBlock::releaseFirst ()
References KviPointerList< T >::first(), i, m_pInstructionList, KviPointerList< T >::removeFirst(), KviPointerList< T >::setAutoDelete(), and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseInstructionBlock(), and KviKvsParser::parseInstructionList().
Member Data Documentation
KviPointerList<KviKvsTreeNodeInstruction>* KviKvsTreeNodeInstructionBlock::m_pInstructionList protected
Referenced by addInstruction(), dump(), execute(), KviKvsTreeNodeInstructionBlock(), releaseFirst(), and ~KviKvsTreeNodeInstructionBlock().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeInstructionBlock.h
src/kvirc/kvs/tree/KviKvsTreeNodeInstructionBlock.cpp