KVIrc: KviKvsPopupMenuItemItem Class Reference
KviKvsPopupMenuItemItem Class Reference
#include <KviKvsPopupMenu.h>
Public Member Functions
virtual KviKvsPopupMenuItem * clone () const
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)
virtual ~KviKvsPopupMenuItemItem ()
Public Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
QPixmap * evaluateIcon (KviKvsPopupMenuTopLevelData *pData)
QString evaluateText (KviKvsPopupMenuTopLevelData *pData)
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
virtual ~KviKvsPopupMenuItemWithTextAndIcon ()
Public Member Functions inherited from KviKvsPopupMenuItem
virtual void clear ()
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
KviKvsScript * kvsCondition ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItemItem (const QString &szItemName, const QString &szCode, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemItem (const QString &szItemName, const KviKvsScript *pCode, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
virtual KviKvsScript * kvsCode ()
Protected Member Functions inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItem
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Protected Attributes
KviKvsScript * m_pKvsCode
Protected Attributes inherited from KviKvsPopupMenuItemWithTextAndIcon
KviKvsScript * m_pKvsIcon
KviKvsScript * m_pKvsText
Protected Attributes inherited from KviKvsPopupMenuItem
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Friends
class KviKvsPopupMenu
Additional Inherited Members
Public Types inherited from KviKvsPopupMenuItem
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Constructor & Destructor Documentation
KviKvsPopupMenuItemItem::KviKvsPopupMenuItemItem (const QString & szItemName, const QString & szCode, const QString & szText, const QString & szIcon, const QString & szCondition) protected
References m_pKvsCode.
Referenced by clone().
KviKvsPopupMenuItemItem::KviKvsPopupMenuItemItem (const QString & szItemName, const KviKvsScript * pCode, const KviKvsScript * pText, const KviKvsScript * pIcon, const KviKvsScript * pCondition) protected
References m_pKvsCode.
KviKvsPopupMenuItemItem::~KviKvsPopupMenuItemItem () virtual
References m_pKvsCode.
Member Function Documentation
KviKvsPopupMenuItem * KviKvsPopupMenuItemItem::clone () const virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItemItem(), m_pKvsCode, KviKvsPopupMenuItem::m_pKvsCondition, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsIcon, KviKvsPopupMenuItemWithTextAndIcon::m_pKvsText, and KviKvsPopupMenuItem::m_szItemName.
void KviKvsPopupMenuItemItem::fill (KviKvsPopupMenu * pMenu, KviKvsPopupMenuTopLevelData * pData, int iIdx) virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), and KviKvsPopupMenuItemWithTextAndIcon::evaluateText().
KviKvsScript * KviKvsPopupMenuItemItem::kvsCode () protected virtual
Reimplemented from KviKvsPopupMenuItem.
References m_pKvsCode.
Friends And Related Function Documentation
friend class KviKvsPopupMenu friend
Member Data Documentation
KviKvsScript* KviKvsPopupMenuItemItem::m_pKvsCode protected
Referenced by clone(), KviKvsPopupMenuItemItem(), kvsCode(), and ~KviKvsPopupMenuItemItem().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp