KVIrc: NotifierWindowTab Class Reference
NotifierWindowTab Class Reference
Defines an object for every single tab about the tabs area.
#include <NotifierWindowTab.h>
Public Member Functions
void appendMessage (NotifierMessage *pMessage)
Appends the given message to the window.
QString label () const
Returns the name of the current window.
NotifierWindowTab (KviWindow *pWnd, QTabWidget *pParent)
Creates the tab object.
void updateGui ()
Updates the GUI.
KviWindow * wnd () const
Returns the pointer of the current window.
~NotifierWindowTab ()
Destroys the tab object.
Protected Member Functions
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
virtual void resizeEvent (QResizeEvent *e)
Private Slots
void closeMe ()
Emitted when the window is being destroyed.
void labelChanged ()
Emitted when the window changes its name.
void scrollRangeChanged (int, int)
Emitted when the scrollbar range is changed.
Private Attributes
QTabWidget * m_pParent
QVBoxLayout * m_pVBox
QWidget * m_pVWidget
KviWindow * m_pWnd
QString m_szLabel
Detailed Description
Defines an object for every single tab about the tabs area.
Constructor & Destructor Documentation
NotifierWindowTab::NotifierWindowTab (KviWindow * pWnd, QTabWidget * pParent)
Creates the tab object.
Parameters:
pWnd The name of the window represented by the tab
pParent The parent area container
Returns:
NotifierWindowTab
References closeMe(), connect(), labelChanged(), m_pParent, m_pVBox, m_pVWidget, m_pWnd, m_szLabel, scrollRangeChanged(), SPACING, and KviWindow::windowName().
NotifierWindowTab::~NotifierWindowTab ()
Destroys the tab object.
References m_pVBox, and m_pVWidget.
Member Function Documentation
void NotifierWindowTab::appendMessage (NotifierMessage * pMessage)
Appends the given message to the window.
Parameters:
pMessage The message received to append
Returns:
void
References m_pVBox, and MAX_MESSAGES_IN_WINDOW.
Referenced by NotifierWindow::addMessage().
void NotifierWindowTab::closeMe () [private, slot]
Emitted when the window is being destroyed.
Returns:
void
References m_pParent, and NotifierWindow::slotTabCloseRequested().
Referenced by NotifierWindowTab().
QString NotifierWindowTab::label () const [inline]
Returns the name of the current window.
Returns:
QString
References m_szLabel.
void NotifierWindowTab::labelChanged () [private, slot]
Emitted when the window changes its name.
Returns:
void
References m_pParent, m_pWnd, m_szLabel, and KviWindow::windowName().
Referenced by NotifierWindowTab().
void NotifierWindowTab::mouseDoubleClickEvent (QMouseEvent * e) [protected, virtual]
References KviWindow::frame(), g_pApp, NotifierWindow::hideNow(), m_pWnd, KviWindow::mdiParent(), KviMainWindow::setActiveWindow(), and KviApplication::windowExists().
void NotifierWindowTab::paintEvent (QPaintEvent * e) [protected, virtual]
References KviPixmapUtils::drawPixmapWithPainter(), g_pApp, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorNotifierBackground, KviOption_pixmapNotifierBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviOption_uintNotifierPixmapAlign, and KviApplication::supportsCompositing().
void NotifierWindowTab::resizeEvent (QResizeEvent * e) [protected, virtual]
References i, and m_pVBox.
void NotifierWindowTab::scrollRangeChanged (int , int) [private, slot]
Emitted when the scrollbar range is changed.
Returns:
void
Referenced by NotifierWindowTab().
void NotifierWindowTab::updateGui ()
Updates the GUI.
Returns:
void
References i, m_pVBox, and NotifierMessage::updateGui().
KviWindow* NotifierWindowTab::wnd () const [inline]
Returns the pointer of the current window.
Returns:
KviWindow *
References m_pWnd.
Referenced by NotifierWindow::paintEvent(), NotifierWindow::returnPressed(), and NotifierWindow::shouldHideIfMainWindowGotAttention().
Member Data Documentation
QTabWidget* NotifierWindowTab::m_pParent [private]
Referenced by closeMe(), labelChanged(), and NotifierWindowTab().
QVBoxLayout* NotifierWindowTab::m_pVBox [private]
Referenced by appendMessage(), NotifierWindowTab(), resizeEvent(), updateGui(), and ~NotifierWindowTab().
QWidget* NotifierWindowTab::m_pVWidget [private]
Referenced by NotifierWindowTab(), and ~NotifierWindowTab().
KviWindow* NotifierWindowTab::m_pWnd [private]
Referenced by labelChanged(), mouseDoubleClickEvent(), NotifierWindowTab(), and wnd().
QString NotifierWindowTab::m_szLabel [private]
Referenced by label(), labelChanged(), and NotifierWindowTab().
The documentation for this class was generated from the following files:
src/modules/notifier/NotifierWindowTab.h
src/modules/notifier/NotifierWindowTab.cpp