KVIrc: KviKvsVariant Class Reference
KviKvsVariant Class Reference
This class defines a new data type which contains variant data.
#include <KviKvsVariant.h>
Public Member Functions
void appendAsString (QString &szBuffer) const
Appends the variant data to a representative string.
KviKvsArray * array () const
Returns the array contained in the variant data.
bool asBoolean () const
Always evaluates to a boolean value.
bool asHObject (kvs_hobject_t &hObject) const
Evaluates to an object handle.
bool asInteger (kvs_int_t &iVal) const
Eevaluates Integer, Real and String representing an Integer.
bool asNumber (KviKvsNumber &n) const
Eevaluates Integer, Real and String representing a Real or Integer.
bool asReal (kvs_real_t &dVal) const
Eevaluates Integer, Real and String representing a Real.
void asString (QString &szBuffer) const
Evaluates anything to a string.
bool boolean () const
Returns the boolean contained in the variant data.
void castToArray (KviKvsArrayCast *pCast) const
Casts the variant data to an array.
void castToInteger (kvs_int_t &iVal) const
Casts the variant data to an integer.
void castToNumber (KviKvsNumber &number) const
Casts the variant data to a number.
int compare (const KviKvsVariant *pOther, bool bPreferNumeric=false) const
Compares two variants.
void convertToArray ()
Converts this variant to an array.
void copyFrom (const KviKvsVariant &variant)
Copies a variant from another.
void copyFrom (const KviKvsVariant *pVariant)
Copies a variant from another.
void dump (const char *pcPrefix) const
Dumps the variant data.
void getTypeName (QString &szBuffer) const
Gets the type from a variant and returns its name.
KviKvsHash * hash () const
Returns the hash contained in the variant data.
kvs_hobject_t hobject () const
Returns the object handle contained in the variant data.
kvs_int_t integer () const
Returns the integer contained in the variant data.
bool isArray () const
Returns true if the variant is an array.
bool isBoolean () const
Returns true if the variant is boolean.
bool isEmpty () const
Returns true if the variant is empty.
bool isEqualToNothing () const
Returns true if the variant is nothing, false, null, 0 or an empty string.
bool isHash () const
Returns true if the variant is an hash.
bool isHObject () const
Returns true if the variant is a hObject.
bool isInteger () const
Returns true if the variant is an integer.
bool isNothing () const
Returns true if the variant is empty.
bool isNumeric () const
Returns true if the variant is numeric.
bool isReal () const
Returns true if the variant is a double floating point.
bool isScalar () const
Returns true if the variant is a scalar.
bool isString () const
Returns true if the variant is a string.
KviKvsVariant (const char *pcString, bool bEscape=false)
Constructs the variant data.
KviKvsVariant (kvs_real_t *pReal)
Constructs the variant data.
KviKvsVariant (kvs_real_t dReal)
Constructs the variant data.
KviKvsVariant (KviKvsArray *pArray)
Constructs the variant data.
KviKvsVariant (bool bBoolean)
Constructs the variant data.
KviKvsVariant ()
Constructs the variant data.
KviKvsVariant (QString *pszString, bool bEscape=false)
Constructs the variant data.
KviKvsVariant (const QString &szString, bool bEscape=false)
Constructs the variant data.
KviKvsVariant (KviKvsHash *pHash)
Constructs the variant data.
KviKvsVariant (kvs_hobject_t hObject)
Constructs the variant data.
KviKvsVariant (const KviKvsVariant &variant)
Constructs the variant data.
KviKvsVariant (kvs_int_t iInteger, bool bEscape=false)
Constructs the variant data.
void operator= (const KviKvsVariant &variant)
Allows to create a variant using a carbon copy method.
kvs_real_t real () const
Returns the double floating point contained in the variant data.
void serialize (QString &szResult)
Serializes the variant data using the JSON format.
void setArray (KviKvsArray *pArray)
Sets the variant data as array.
void setBoolean (bool bBoolean)
Sets the variant data as boolean.
void setHash (KviKvsHash *pHash)
Sets the variant data as hash.
void setHObject (kvs_hobject_t hObject)
Sets the variant data as hObject.
void setInteger (kvs_int_t iInteger)
Sets the variant data as integer.
void setNothing ()
Clears the variant data.
void setReal (kvs_real_t dReal)
Sets the variant data as double floating point.
void setReal (kvs_real_t *pReal)
Sets the variant data as double floating point.
void setString (const QString &szString)
Sets the variant data as string.
void setString (QString *pszString)
Sets the variant data as string.
const QString & string () const
Returns the string contained in the variant data.
void takeFrom (KviKvsVariant &variant)
Copies a variant from another and destroys the second one.
void takeFrom (KviKvsVariant *pVariant)
Copies a variant from another and destroys the second one.
KviKvsVariantData::Type type ()
Returns the type of the variant data.
~KviKvsVariant ()
Destroys the variant data.
Static Public Member Functions
static void serializeString (QString &szBuffer)
Replaces escapes chars and serialize the string in the given buffer.
static KviKvsVariant * unserialize (const QString &szBuffer)
Unserializes the variant data using the JSON format.
Protected Attributes
KviKvsVariantData * m_pData
Static Private Member Functions
static KviKvsVariant * unserialize (const QChar **ppAux)
Unserializes the variant data using the JSON format.
static KviKvsVariant * unserializeArray (const QChar **ppAux)
Unserializes an array into a variant data using the JSON format.
static KviKvsVariant * unserializeBool (const QChar **ppAux, bool bBool)
Unserializes a boolean into a variant data using the JSON format.
static KviKvsVariant * unserializeHash (const QChar **ppAux)
Unserializes a hash into a variant data using the JSON format.
static KviKvsVariant * unserializeInteger (const QChar **ppAux, QString &szData)
Unserializes an integer into a variant data using the JSON format.
static KviKvsVariant * unserializeNull (const QChar **ppAux)
Unserializes null into a variant data using the JSON format.
static KviKvsVariant * unserializeNumber (const QChar **ppAux)
Unserializes a number into a variant data using the JSON format.
static KviKvsVariant * unserializeReal (const QChar **ppAux, QString &szData)
Unserializes a double floating point into a variant data using the JSON format.
static void unserializeString (const QChar **ppAux, QString &szBuffer)
Unserializes a string into a variant data using the JSON format.
static KviKvsVariant * unserializeString (const QChar **ppAux)
Unserializes a string into a variant data using the JSON format.
Friends
class KviKvsVariantComparison
Detailed Description
This class defines a new data type which contains variant data.
A variant data is a data which can assume different data types. This is very useful when you don't know in advance which data type you have to manage.
Warning:
This class must NOT have virtual functions nor destructor otherwise it will happily crash on windows when it is allocated in modules and destroyed anywhere else around...
Constructor & Destructor Documentation
KviKvsVariant::KviKvsVariant ()
Constructs the variant data.
Returns:
KviKvsVariant
References m_pData.
Referenced by castToArray(), convertToArray(), unserializeArray(), unserializeBool(), unserializeHash(), unserializeInteger(), unserializeNull(), unserializeReal(), and unserializeString().
KviKvsVariant::KviKvsVariant (const KviKvsVariant & variant)
Constructs the variant data.
This is a carbon copy
Parameters:
variant The variant data to use as a copy
Returns:
KviKvsVariant
References m_pData, and KviKvsVariantData::m_uRefs.
KviKvsVariant::KviKvsVariant (const QString & szString, bool bEscape = false)
Constructs the variant data.
Parameters:
szString The string data to use as variant data
bEscape Whether to escape the data in KVS
Returns:
KviKvsVariant
References KviQString::escapeKvs(), KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::m_uRefs, and KviKvsVariantData::String.
KviKvsVariant::KviKvsVariant (const char * pcString, bool bEscape = false)
Constructs the variant data.
Parameters:
pcString The string data to use as variant data
bEscape Whether to escape the data in KVS
Warning:
Without this constructor gcc chooses the conversion (const char *)->(void *) instead of (const char *)->(QString) and obviously calls the wrong constructor
Returns:
KviKvsVariant
References KviQString::escapeKvs(), KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::m_uRefs, and KviKvsVariantData::String.
KviKvsVariant::KviKvsVariant (QString * pszString, bool bEscape = false)
Constructs the variant data.
Parameters:
pszString The string data to use as variant data
bEscape Whether to escape the data in KVS
Returns:
KviKvsVariant
References KviQString::escapeKvs(), KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::m_uRefs, and KviKvsVariantData::String.
KviKvsVariant::KviKvsVariant (kvs_int_t iInteger, bool bEscape = false)
Constructs the variant data.
Parameters:
iInteger The integer data to use as variant data
bEscape Whether to escape the data in KVS
Returns:
KviKvsVariant
References KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and KviKvsVariantData::m_uRefs.
KviKvsVariant::KviKvsVariant (kvs_real_t dReal)
Constructs the variant data.
Parameters:
dReal The double floating point data to use as variant data
Returns:
KviKvsVariant
References KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::m_uRefs, and KviKvsVariantData::Real.
KviKvsVariant::KviKvsVariant (kvs_real_t * pReal)
Constructs the variant data.
Parameters:
pReal The double floating point data to use as variant data
Returns:
KviKvsVariant
References KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::m_uRefs, and KviKvsVariantData::Real.
KviKvsVariant::KviKvsVariant (bool bBoolean)
Constructs the variant data.
Parameters:
bBoolean The boolean data to use as variant data
Returns:
KviKvsVariant
References KviKvsVariantData::Boolean, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and KviKvsVariantData::m_uRefs.
KviKvsVariant::KviKvsVariant (KviKvsArray * pArray)
Constructs the variant data.
Parameters:
pArray The array data to use as variant data
Returns:
KviKvsVariant
References KviKvsVariantData::Array, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::m_uRefs, and pArray.
KviKvsVariant::KviKvsVariant (KviKvsHash * pHash)
Constructs the variant data.
Parameters:
pHash The hash data to use as variant data
Returns:
KviKvsVariant
References KviKvsVariantData::Hash, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and KviKvsVariantData::m_uRefs.
KviKvsVariant::KviKvsVariant (kvs_hobject_t hObject)
Constructs the variant data.
Parameters:
hObject The hObject data to use as variant data
Returns:
KviKvsVariant
References KviKvsVariantData::HObject, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and KviKvsVariantData::m_uRefs.
KviKvsVariant::~KviKvsVariant ()
Destroys the variant data.
References DETACH_CONTENTS.
Member Function Documentation
void KviKvsVariant::appendAsString (QString & szBuffer) const
Appends the variant data to a representative string.
Parameters:
szBuffer The string buffer to save
Returns:
void
References KviQString::appendNumber(), KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by KviKvsArray::appendAsString(), KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeCompositeData::evaluateReadOnly(), KviKvsTreeNodeOperationStringAppend::execute(), and KviKvsParameterProcessor::process().
KviKvsArray* KviKvsVariant::array () const [inline]
Returns the array contained in the variant data.
Returns:
KviKvsArray
Referenced by KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsObject::function_setProperty(), KvsObject_textedit::functionsetColor(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), KviKvsParameterProcessor::process(), and KviCellItemDelegate::sizeHint().
bool KviKvsVariant::asBoolean () const
Always evaluates to a boolean value.
Returns:
bool
References KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, KviKvsVariantData::String, and KviQString::toI64().
Referenced by dcc_kvs_parse_default_parameters(), KviKvsPopupMenuItem::evaluateCondition(), KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::evaluateReadOnly(), KvsObject_widget::eventFilter(), KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandIf::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), KviKvsTreeNodeSpecialCommandDo::execute(), KviKvsObject::function_setProperty(), KviXmlHandler::handleKvsCallReturnValue(), KVSO_CLASS_FUNCTION(), KvsObject_tableWidget::paint(), and KviKvsParameterProcessor::process().
bool KviKvsVariant::asHObject (kvs_hobject_t & hObject) const
Evaluates to an object handle.
Parameters:
hObject The hObject buffer to save
Returns:
bool
References KviKvsVariantData::Boolean, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and KviKvsVariantData::String.
Referenced by KVSO_CLASS_FUNCTION(), KviKvsTreeNodeScopeOperator::objectFromVariant(), and KviKvsParameterProcessor::process().
bool KviKvsVariant::asInteger (kvs_int_t & iVal) const
Eevaluates Integer, Real and String representing an Integer.
Parameters:
iVal The integer buffer to save
Returns:
bool
References KviKvsVariantData::Boolean, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, KviKvsVariantData::String, and KviQString::toI64().
Referenced by asNumber(), castToNumber(), KviKvsTreeNodeConstantData::convertStringConstantToNumeric(), dcc_kvs_cmd_send(), KviKvsTreeNodeArrayElement::evaluateIndex(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationDecrement::execute(), file_kvs_cmd_writeBytes(), KviKvsObject::function_setProperty(), KvsObject_textedit::functionsetColor(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), notifier_kvs_cmd_message(), KviKvsParameterProcessor::process(), KviCellItemDelegate::sizeHint(), str_kvs_fnc_printf(), and toolbar_kvs_cmd_removeitem().
bool KviKvsVariant::asNumber (KviKvsNumber & n) const
Eevaluates Integer, Real and String representing a Real or Integer.
Parameters:
n The number buffer to save
Returns:
bool
References asInteger(), asReal(), KviKvsNumber::Integer, isInteger(), isReal(), m_pData, KviKvsNumber::m_type, KviKvsVariantData::m_u, KviKvsNumber::m_u, and KviKvsNumber::Real.
Referenced by KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand(), KviKvsTreeNodeExpressionBinaryOperator::evaluateOperands(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsCoreFunctions::KVSCF(), str_kvs_fnc_isnumber(), and str_kvs_fnc_isunsignednumber().
bool KviKvsVariant::asReal (kvs_real_t & dVal) const
Eevaluates Integer, Real and String representing a Real.
Parameters:
dVal The double floating point buffer to save
Returns:
bool
References KviKvsVariantData::Boolean, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by asNumber(), castToNumber(), compare(), KviKvsVariantComparison::compareIntString(), KviKvsVariantComparison::compareRealString(), KviKvsVariantComparison::compareStringHObject(), KviKvsTreeNodeConstantData::convertStringConstantToNumeric(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationDecrement::execute(), KviKvsObject::function_setProperty(), isEqualToNothing(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), KviKvsParameterProcessor::process(), and str_kvs_fnc_printf().
void KviKvsVariant::asString (QString & szBuffer) const
Evaluates anything to a string.
Parameters:
szBuffer The string buffer to save
Returns:
bool
References KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by KviChannelWindow::closeEvent(), KviKvsVariantComparison::compareIntString(), KviKvsVariantComparison::compareRealString(), dcc_kvs_cmd_send(), dcc_kvs_parse_default_parameters(), KviKvsScript::evaluateAsString(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsTreeNodeStringCast::evaluateReadOnly(), KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), KvsObject_widget::eventFilter(), KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelMatch::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsTreeNodeRebindingSwitch::execute(), KviKvsTreeNodeOperationStringSubstitution::execute(), KviKvsTreeNodeOperationStringTransliteration::execute(), KviKvsTreeNodeOperationStringAppendWithSpace::execute(), KviKvsTreeNodeOperationStringAppendWithComma::execute(), KviKvsTreeNodeOperationStringAppend::execute(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), KviKvsVariantList::firstAsString(), KviKvsObject::function_setProperty(), KvsObject_textedit::functionsetColor(), KviKvsSwitchList::getAsStringIfExisting(), KviWindow::getDefaultLogFileName(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), KviKvsVariantList::nextAsString(), PluginManager::pluginCall(), popup_kvs_cmd_show(), KviKvsParameterProcessor::process(), KviKvsScript::run(), str_kvs_fnc_grep(), str_kvs_fnc_join(), str_kvs_fnc_printf(), KviIrcContext::terminateConnectionRequest(), toolbar_kvs_cmd_removeitem(), KviKvsProcessAsyncOperation::trigger(), upnp_kvs_cmd_addPortMapping(), urllist_module_event_onUrl(), and KviIrcConnection::useRealName().
bool KviKvsVariant::boolean () const [inline]
Returns the boolean contained in the variant data.
Returns:
bool
void KviKvsVariant::castToArray (KviKvsArrayCast * pCast) const
Casts the variant data to an array.
Always evaluates to an array
Parameters:
pCast The array buffer to save
Returns:
void
References KviKvsVariantData::Array, KviPointerHashTableIterator< Key, T >::current(), KviKvsVariantData::Hash, KviKvsVariant(), KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, pArray, KviKvsArray::set(), and KviKvsArrayCast::set().
Referenced by KviKvsParameterProcessor::process().
void KviKvsVariant::castToInteger (kvs_int_t & iVal) const
Casts the variant data to an integer.
Always evaluates to an integer
Parameters:
iVal The integer buffer to save
Returns:
void
References KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, KviKvsVariantData::String, and KviQString::toI64().
Referenced by castToNumber(), and KviKvsCoreFunctions::KVSCF().
void KviKvsVariant::castToNumber (KviKvsNumber & number) const
Casts the variant data to a number.
Always evaluates to some number
Parameters:
number The string buffer to save
Returns:
void
References asInteger(), asReal(), castToInteger(), KviKvsNumber::Integer, isInteger(), isReal(), m_pData, KviKvsNumber::m_type, KviKvsVariantData::m_u, KviKvsNumber::m_u, and KviKvsNumber::Real.
int KviKvsVariant::compare (const KviKvsVariant * pOther, bool bPreferNumeric = false) const
Compares two variants.
Returns -1 if this variant is greater than the other, 0 if they are equal, 1 if the other is greater. If bPreferNumeric is true then a conversion to a numeric format is first attempted
Parameters:
pOther The second variant to compare
bPreferNumeric Whether to cast to a numeric format
Returns:
int
References KviKvsVariantData::Array, asReal(), KviKvsVariantData::Boolean, CMP_EQUAL, CMP_OTHERGREATER, CMP_THISGREATER, KviKvsVariantComparison::compareArrayHash(), KviKvsVariantComparison::compareBoolArray(), KviKvsVariantComparison::compareBoolHash(), KviKvsVariantComparison::compareBoolHObject(), KviKvsVariantComparison::compareBoolString(), KviKvsVariantComparison::compareHObjectArray(), KviKvsVariantComparison::compareHObjectHash(), KviKvsVariantComparison::compareIntArray(), KviKvsVariantComparison::compareIntBool(), KviKvsVariantComparison::compareIntHash(), KviKvsVariantComparison::compareIntHObject(), KviKvsVariantComparison::compareIntReal(), KviKvsVariantComparison::compareIntString(), KviKvsVariantComparison::compareRealArray(), KviKvsVariantComparison::compareRealBool(), KviKvsVariantComparison::compareRealHash(), KviKvsVariantComparison::compareRealHObject(), KviKvsVariantComparison::compareRealString(), KviKvsVariantComparison::compareStringArray(), KviKvsVariantComparison::compareStringHash(), KviKvsVariantComparison::compareStringHObject(), KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, isEqualToNothing(), KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by kvi_compare().
void KviKvsVariant::convertToArray ()
Converts this variant to an array.
Returns:
void
References KviKvsVariantData::Array, KviPointerHashTableIterator< Key, T >::current(), KviKvsVariantData::Hash, KviKvsVariant(), KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, pArray, KviKvsArray::set(), and setArray().
Referenced by KviKvsTreeNodeOperationArrayAppend::execute().
void KviKvsVariant::copyFrom (const KviKvsVariant * pVariant)
Copies a variant from another.
Parameters:
pVariant The variant to copy from
Returns:
void
References DETACH_CONTENTS, m_pData, and KviKvsVariantData::m_uRefs.
Referenced by KviKvsTreeNodeSingleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeLocalVariable::evaluateReadOnly(), KviKvsTreeNodeGlobalVariable::evaluateReadOnly(), KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly(), KviKvsTreeNodeExpressionConstantOperand::evaluateReadOnly(), KviKvsTreeNodeConstantData::evaluateReadOnly(), KviKvsTreeNodeObjectField::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeParameterReturn::execute(), and KviKvsProcessAsyncOperation::trigger().
void KviKvsVariant::copyFrom (const KviKvsVariant & variant)
Copies a variant from another.
Parameters:
variant The variant to copy from
Returns:
void
References DETACH_CONTENTS, m_pData, and KviKvsVariantData::m_uRefs.
void KviKvsVariant::dump (const char * pcPrefix) const
Dumps the variant data.
Parameters:
pcPrefix The prefix of the data
Returns:
void
References KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by KviKvsTreeNodeExpressionConstantOperand::dump(), and KviKvsTreeNodeConstantData::dump().
void KviKvsVariant::getTypeName (QString & szBuffer) const
Gets the type from a variant and returns its name.
Parameters:
szBuffer The buffer to save the type name
Returns:
void
References KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsParameterProcessor::handleParameterTypeError(), KviKvsCoreFunctions::KVSCF(), and KVSO_CLASS_FUNCTION().
KviKvsHash* KviKvsVariant::hash () const [inline]
Returns the hash contained in the variant data.
Returns:
KviKvsHash
Referenced by KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), and KviKvsParameterProcessor::process().
kvs_hobject_t KviKvsVariant::hobject () const [inline]
Returns the object handle contained in the variant data.
Returns:
kvs_hobject_t
Referenced by KviKvsObject::function_setProperty().
kvs_int_t KviKvsVariant::integer () const [inline]
Returns the integer contained in the variant data.
Returns:
kvs_int_t
bool KviKvsVariant::isArray () const [inline]
Returns true if the variant is an array.
Returns:
bool
References KviKvsVariantData::Array.
Referenced by KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsObject::function_setProperty(), KvsObject_textedit::functionsetColor(), KVSO_CLASS_FUNCTION(), KviKvsParameterProcessor::process(), and KviCellItemDelegate::sizeHint().
bool KviKvsVariant::isBoolean () const [inline]
Returns true if the variant is boolean.
Returns:
bool
References KviKvsVariantData::Boolean.
Referenced by dcc_kvs_cmd_send(), and KVSO_CLASS_FUNCTION().
bool KviKvsVariant::isEmpty () const
Returns true if the variant is empty.
Returns:
bool
References KviKvsVariantData::Array, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and KviKvsVariantData::String.
Referenced by KviKvsObjectClass::allocateInstance(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsParameterProcessor::handleParameterTypeError(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), KviKvsArrayElement::~KviKvsArrayElement(), and KviKvsHashElement::~KviKvsHashElement().
bool KviKvsVariant::isEqualToNothing () const
Returns true if the variant is nothing, false, null, 0 or an empty string.
Returns:
bool
References KviKvsVariantData::Array, asReal(), KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and KviKvsVariantData::String.
Referenced by compare(), and KviKvsVariantComparison::compareBoolString().
bool KviKvsVariant::isHash () const [inline]
Returns true if the variant is an hash.
Returns:
bool
References KviKvsVariantData::Hash.
Referenced by KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KVSO_CLASS_FUNCTION(), and KviKvsParameterProcessor::process().
bool KviKvsVariant::isHObject () const [inline]
Returns true if the variant is a hObject.
Returns:
bool
References KviKvsVariantData::HObject.
Referenced by KviKvsObject::function_setProperty(), and KVSO_CLASS_FUNCTION().
bool KviKvsVariant::isInteger () const [inline]
Returns true if the variant is an integer.
Returns:
bool
References KviKvsVariantData::Integer.
Referenced by asNumber(), castToNumber(), and KVSO_CLASS_FUNCTION().
bool KviKvsVariant::isNothing () const [inline]
Returns true if the variant is empty.
Returns:
bool
Referenced by KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KVSO_CLASS_FUNCTION(), and KviKvsProcessAsyncOperation::trigger().
bool KviKvsVariant::isNumeric () const [inline]
Returns true if the variant is numeric.
Returns:
bool
References KviKvsVariantData::Integer, and KviKvsVariantData::Real.
bool KviKvsVariant::isReal () const [inline]
Returns true if the variant is a double floating point.
Returns:
bool
References KviKvsVariantData::Real.
Referenced by asNumber(), castToNumber(), and KVSO_CLASS_FUNCTION().
bool KviKvsVariant::isScalar () const [inline]
Returns true if the variant is a scalar.
Returns:
bool
References KviKvsVariantData::Integer, KviKvsVariantData::Real, and KviKvsVariantData::String.
bool KviKvsVariant::isString () const [inline]
Returns true if the variant is a string.
Returns:
bool
References KviKvsVariantData::String.
Referenced by KviKvsTreeNodeConstantData::convertStringConstantToNumeric(), KviKvsTreeNodeStringCast::evaluateReadOnly(), KviKvsParameterProcessor::handleParameterTypeError(), and KVSO_CLASS_FUNCTION().
void KviKvsVariant::operator= (const KviKvsVariant & variant) [inline]
Allows to create a variant using a carbon copy method.
Parameters:
variant The variant to copy from
Returns:
void
kvs_real_t KviKvsVariant::real () const [inline]
Returns the double floating point contained in the variant data.
Returns:
kvs_real_t
void KviKvsVariant::serialize (QString & szResult)
Serializes the variant data using the JSON format.
Parameters:
szResult The buffer to store the serialization
Returns:
void
References KviKvsVariantData::Array, KviKvsVariantData::Boolean, KviKvsVariantData::Hash, KviKvsVariantData::HObject, KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Nothing, KviKvsVariantData::Real, serializeString(), and KviKvsVariantData::String.
Referenced by KviKvsCoreFunctions::KVSCF(), and KviKvsArray::serialize().
void KviKvsVariant::serializeString (QString & szBuffer) [static]
Replaces escapes chars and serialize the string in the given buffer.
Parameters:
szBuffer The buffer to store the serialization
Returns:
void
Referenced by serialize(), and KviKvsHash::serialize().
void KviKvsVariant::setArray (KviKvsArray * pArray)
Sets the variant data as array.
Parameters:
pArray The value to set
Returns:
void
References KviKvsVariantData::Array, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, pArray, and RENEW_VARIANT_DATA.
Referenced by chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_masklist(), chan_kvs_fnc_users(), config_kvs_fnc_filelist(), config_kvs_fnc_keylist(), config_kvs_fnc_sectionlist(), context_kvs_fnc_list(), convertToArray(), dcc_kvs_fnc_sessionList(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), file_kvs_fnc_allSizes(), file_kvs_fnc_ls(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), KviKvsObject::function_children(), KviKvsObject::function_listProperties(), KviKvsObject::function_property(), KvsObject_textedit::functionCursorPosition(), objects_kvs_fnc_classes(), objects_kvs_fnc_instances(), objects_kvs_fnc_listObjects(), regchan_kvs_fnc_list(), reguser_kvs_fnc_list(), reguser_kvs_fnc_mask(), str_kvs_fnc_grep(), str_kvs_fnc_split(), system_kvs_fnc_dbus(), toolbar_kvs_fnc_items(), toolbar_kvs_fnc_list(), userlist_kvs_fnc_selected(), and window_kvs_fnc_list().
void KviKvsVariant::setBoolean (bool bBoolean)
Sets the variant data as boolean.
Parameters:
bBoolean The value to set
Returns:
void
References KviKvsVariantData::Boolean, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and RENEW_VARIANT_DATA.
Referenced by action_kvs_fnc_exists(), action_kvs_fnc_isEnabled(), addon_kvs_fnc_exists(), KviKvsObjectStandardFalseReturnFunctionHandler::call(), KviKvsObjectStandardTrueReturnFunctionHandler::call(), chan_kvs_fnc_isdead(), chan_kvs_fnc_ison(), config_kvs_fnc_hassection(), config_kvs_fnc_readonly(), dcc_kvs_fnc_isFileDownload(), dcc_kvs_fnc_isFileTransfer(), dcc_kvs_fnc_isFileUpload(), dialog_kvs_fnc_yesno(), KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::evaluateReadOnly(), file_kvs_fnc_exists(), KviKvsObject::function_property(), KvsObject_textedit::functionAtBeginning(), KvsObject_textedit::functionAtEnd(), KvsObject_textedit::functionbold(), KvsObject_textedit::functionisUndoRedoEnabled(), KvsObject_textedit::functionitalic(), KvsObject_textedit::functionModified(), KvsObject_textedit::functionunderline(), mask_kvs_fnc_hasnumerichost(), mask_kvs_fnc_match(), math_kvs_fnc_isinf(), my_kvs_fnc_serverIsIPV6(), my_kvs_fnc_serverIsSSL(), notifier_kvs_fnc_isEnabled(), objects_kvs_fnc_exists(), options_kvs_fnc_isdialog(), perl_kvs_fnc_isAvailable(), popup_kvs_fnc_exists(), popup_kvs_fnc_isEmpty(), python_kvs_fnc_isAvailable(), regchan_kvs_fnc_find(), regchan_kvs_fnc_match(), reguser_kvs_fnc_isIgnoreEnabled(), serverdb_kvs_fnc_networkExists(), serverdb_kvs_fnc_serverExists(), snd_kvs_fnc_ismuted(), str_kvs_fnc_contains(), str_kvs_fnc_equal(), str_kvs_fnc_evpVerify(), str_kvs_fnc_isempty(), str_kvs_fnc_isnumber(), str_kvs_fnc_isunsignednumber(), str_kvs_fnc_match(), system_kvs_fnc_checkModule(), tmphighlight_kvs_fnc_ischannelhighlighted(), tmphighlight_kvs_fnc_isnickhighlighted(), toolbar_kvs_fnc_exists(), toolbar_kvs_fnc_isVisible(), trayicon_kvs_fnc_isvisible(), upnp_kvs_fnc_isGatewayAvailable(), window_kvs_fnc_exists(), window_kvs_fnc_hasInput(), window_kvs_fnc_hasOutput(), window_kvs_fnc_hasUserFocus(), window_kvs_fnc_isDocked(), window_kvs_fnc_isMaximized(), and window_kvs_fnc_isMinimized().
void KviKvsVariant::setHash (KviKvsHash * pHash)
Sets the variant data as hash.
Parameters:
pHash The value to set
Returns:
void
References KviKvsVariantData::Hash, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and RENEW_VARIANT_DATA.
Referenced by KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), file_kvs_fnc_diskSpace(), language_kvs_cmd_detect(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_variables(), texticons_kvs_fnc_get(), and theme_kvs_fnc_info().
void KviKvsVariant::setHObject (kvs_hobject_t hObject)
Sets the variant data as hObject.
Parameters:
hObject The value to set
Returns:
void
References KviKvsVariantData::HObject, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and RENEW_VARIANT_DATA.
Referenced by KviKvsObject::function_findChild(), KviKvsObject::function_parent(), and KviKvsObject::function_signalSender().
void KviKvsVariant::setInteger (kvs_int_t iInteger)
Sets the variant data as integer.
Parameters:
iInteger The value to set
Returns:
void
References KviKvsVariantData::Integer, KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, and RENEW_VARIANT_DATA.
Referenced by chan_kvs_fnc_admincount(), chan_kvs_fnc_bancount(), chan_kvs_fnc_banexceptioncount(), chan_kvs_fnc_halfopcount(), chan_kvs_fnc_invitecount(), chan_kvs_fnc_limit(), chan_kvs_fnc_maskcount(), chan_kvs_fnc_opcount(), chan_kvs_fnc_ownercount(), chan_kvs_fnc_usercount(), chan_kvs_fnc_userjointime(), chan_kvs_fnc_userlastactiontime(), chan_kvs_fnc_usermodelevel(), chan_kvs_fnc_useropcount(), chan_kvs_fnc_voicecount(), config_kvs_fnc_readonly(), context_kvs_fnc_queueSize(), KviKvsTreeNodeConstantData::convertStringConstantToNumeric(), dcc_kvs_fnc_averageSpeed(), dcc_kvs_fnc_ircContext(), dcc_kvs_fnc_session(), dcc_kvs_fnc_transferredBytes(), KviKvsTreeNodeParameterCount::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationDecrement::execute(), file_kvs_fnc_size(), KviKvsObject::function_childCount(), KviKvsObject::function_property(), KviKvsObject::function_startTimer(), KvsObject_http::functionCurrentId(), KvsObject_http::functionGet(), KvsObject_textedit::functionlines(), KvsObject_textedit::functionMaxLines(), KvsObject_textedit::functionNumLines(), KvsObject_http::functionPost(), my_kvs_fnc_globalIdle(), str_kvs_fnc_charsum(), str_kvs_fnc_cmp(), str_kvs_fnc_find(), str_kvs_fnc_findfirst(), str_kvs_fnc_findlast(), str_kvs_fnc_len(), system_kvs_fnc_dbus(), texticons_kvs_fnc_get(), KviKvsObject::timerEvent(), window_kvs_fnc_activityLevel(), window_kvs_fnc_activityTemperature(), window_kvs_fnc_console(), window_kvs_fnc_context(), window_kvs_fnc_highlightLevel(), and window_kvs_fnc_open().
void KviKvsVariant::setNothing ()
Clears the variant data.
Returns:
void
References DELETE_VARIANT_CONTENTS, m_pData, and KviKvsVariantData::m_uRefs.
Referenced by addon_kvs_fnc_version(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KviKvsObjectStandardNothingReturnFunctionHandler::call(), chan_kvs_fnc_getflag(), chan_kvs_fnc_matchban(), chan_kvs_fnc_matchbanexception(), chan_kvs_fnc_matchinvite(), chan_kvs_fnc_matchmask(), chan_kvs_fnc_matchqban(), KviKvsTreeNodeSingleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeLocalVariable::evaluateReadOnly(), KviKvsTreeNodeGlobalVariable::evaluateReadOnly(), KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly(), KviKvsTreeNodeCoreFunctionCall::evaluateReadOnly(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeThisObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeObjectField::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeBaseObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeSpecialCommandUnset::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeParameterReturn::execute(), KviKvsObject::function_listProperties(), KviKvsObject::function_property(), KviKvsObject::function_setProperty(), popup_kvs_fnc_currentItemId(), and userlist_kvs_fnc_selected().
void KviKvsVariant::setReal (kvs_real_t * pReal)
Sets the variant data as double floating point.
Parameters:
pReal The value to set
Returns:
void
References KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and RENEW_VARIANT_DATA.
void KviKvsVariant::setReal (kvs_real_t dReal)
Sets the variant data as double floating point.
Parameters:
dReal The value to set
Returns:
void
References KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, KviKvsVariantData::Real, and RENEW_VARIANT_DATA.
Referenced by KviKvsTreeNodeConstantData::convertStringConstantToNumeric(), KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationDecrement::execute(), KviKvsObject::function_property(), math_kvs_fnc_e(), math_kvs_fnc_pi(), and math_kvs_fnc_pow().
void KviKvsVariant::setString (const QString & szString)
Sets the variant data as string.
Parameters:
szString The value to set
Returns:
void
References KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, RENEW_VARIANT_DATA, and KviKvsVariantData::String.
Referenced by addon_kvs_fnc_version(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), chan_kvs_fnc_common(), chan_kvs_fnc_getflag(), chan_kvs_fnc_getUrl(), chan_kvs_fnc_key(), chan_kvs_fnc_matchban(), chan_kvs_fnc_matchbanexception(), chan_kvs_fnc_matchinvite(), chan_kvs_fnc_matchmask(), chan_kvs_fnc_matchqban(), chan_kvs_fnc_modeParam(), chan_kvs_fnc_name(), chan_kvs_fnc_topic(), chan_kvs_fnc_topicsetat(), chan_kvs_fnc_topicsetby(), config_kvs_fnc_filename(), config_kvs_fnc_id(), config_kvs_fnc_open(), config_kvs_fnc_read(), config_kvs_fnc_section(), context_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_connectionType(), dcc_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_localFileName(), dcc_kvs_fnc_localFileSize(), dcc_kvs_fnc_localHost(), dcc_kvs_fnc_localIp(), dcc_kvs_fnc_localNick(), dcc_kvs_fnc_localPort(), dcc_kvs_fnc_localUser(), dcc_kvs_fnc_protocol(), dcc_kvs_fnc_remoteFileName(), dcc_kvs_fnc_remoteFileSize(), dcc_kvs_fnc_remoteHost(), dcc_kvs_fnc_remoteIp(), dcc_kvs_fnc_remoteNick(), dcc_kvs_fnc_remotePort(), dcc_kvs_fnc_remoteUser(), dcc_kvs_fnc_transferStatus(), dumpChildObjects(), KviKvsTreeNodeStringCast::evaluateReadOnly(), KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly(), KviKvsTreeNodeCompositeData::evaluateReadOnly(), KviKvsTreeNodeParameterReturn::execute(), KviKvsTreeNodeOperationStringSubstitution::execute(), KviKvsTreeNodeOperationStringTransliteration::execute(), KviKvsTreeNodeOperationStringAppendWithSpace::execute(), KviKvsTreeNodeOperationStringAppendWithComma::execute(), KviKvsTreeNodeOperationStringAppend::execute(), file_kvs_fnc_cwd(), file_kvs_fnc_digest(), file_kvs_fnc_extractfilename(), file_kvs_fnc_extractpath(), file_kvs_fnc_fixpath(), file_kvs_fnc_globaldir(), file_kvs_fnc_homedir(), file_kvs_fnc_localdir(), file_kvs_fnc_ps(), file_kvs_fnc_read(), file_kvs_fnc_rootdir(), file_kvs_fnc_type(), KviKvsObject::function_className(), KviKvsObject::function_name(), KviKvsObject::function_property(), KviKvsObject::function_signalName(), KvsObject_http::functionErrorString(), KvsObject_http::functionReadAll(), KvsObject_textedit::functionText(), KvsObject_textedit::functiontextFormat(), KvsObject_textedit::functionTextLine(), KvsObject_textedit::functionWordWrap(), log_kvs_fnc_export(), log_kvs_fnc_file(), mask_kvs_fnc_host(), mask_kvs_fnc_nick(), mask_kvs_fnc_user(), my_kvs_fnc_host(), my_kvs_fnc_ip(), my_kvs_fnc_network(), my_kvs_fnc_nick(), my_kvs_fnc_server(), my_kvs_fnc_umode(), my_kvs_fnc_user(), objects_kvs_fnc_listObjects(), objects_kvs_fnc_name(), perl_kvs_cmd_begin(), PluginManager::pluginCall(), popup_kvs_fnc_currentItemId(), proxydb_kvs_fnc_protocol(), python_kvs_cmd_begin(), regchan_kvs_fnc_property(), reguser_kvs_fnc_exactMatch(), reguser_kvs_fnc_getIgnoreFlags(), reguser_kvs_fnc_mask(), reguser_kvs_fnc_match(), reguser_kvs_fnc_matchProperty(), reguser_kvs_fnc_property(), str_kvs_fnc_append(), str_kvs_fnc_chop(), str_kvs_fnc_digest(), str_kvs_fnc_evpSign(), str_kvs_fnc_evpVerify(), str_kvs_fnc_fromclipboard(), str_kvs_fnc_insert(), str_kvs_fnc_join(), str_kvs_fnc_left(), str_kvs_fnc_lefttofirst(), str_kvs_fnc_lefttolast(), str_kvs_fnc_localelowcase(), str_kvs_fnc_localeupcase(), str_kvs_fnc_lowcase(), str_kvs_fnc_mid(), str_kvs_fnc_prepend(), str_kvs_fnc_printf(), str_kvs_fnc_replace(), str_kvs_fnc_right(), str_kvs_fnc_rightfromfirst(), str_kvs_fnc_rightfromlast(), str_kvs_fnc_section(), str_kvs_fnc_strip(), str_kvs_fnc_stripcolors(), str_kvs_fnc_stripleft(), str_kvs_fnc_stripright(), str_kvs_fnc_token(), str_kvs_fnc_upcase(), str_kvs_fnc_urlencode(), str_kvs_fnc_word(), system_kvs_fnc_clipboard(), system_kvs_fnc_dbus(), system_kvs_fnc_getenv(), system_kvs_fnc_hostname(), system_kvs_fnc_osmachine(), system_kvs_fnc_osname(), system_kvs_fnc_osnodename(), system_kvs_fnc_osrelease(), system_kvs_fnc_ostype(), system_kvs_fnc_osversion(), system_kvs_fnc_selection(), texticons_kvs_fnc_get(), theme_kvs_fnc_list(), upnp_kvs_fnc_getExternalIpAddress(), window_kvs_fnc_caption(), window_kvs_fnc_inputText(), and window_kvs_fnc_type().
void KviKvsVariant::setString (QString * pszString)
Sets the variant data as string.
Parameters:
pszString The value to set
Returns:
void
References KviKvsVariantData::m_eType, m_pData, KviKvsVariantData::m_u, RENEW_VARIANT_DATA, and KviKvsVariantData::String.
const QString& KviKvsVariant::string () const [inline]
Returns the string contained in the variant data.
Returns:
const QString &
References KviQString::Empty.
Referenced by KviKvsParameterProcessor::handleParameterTypeError().
void KviKvsVariant::takeFrom (KviKvsVariant * pVariant)
Copies a variant from another and destroys the second one.
Parameters:
pVariant The variant to take from
Returns:
void
References DETACH_CONTENTS, and m_pData.
Referenced by KviKvsTreeNodeOperationAssignment::execute().
void KviKvsVariant::takeFrom (KviKvsVariant & variant)
Copies a variant from another and destroys the second one.
Parameters:
variant The variant to take from
Returns:
void
References DETACH_CONTENTS, and m_pData.
KviKvsVariantData::Type KviKvsVariant::type () [inline]
Returns the type of the variant data.
Returns:
KviKvsVariantData::Type
References KviKvsVariantData::Nothing.
Referenced by KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsCoreFunctions::KVSCF(), and KVSO_CLASS_FUNCTION().
KviKvsVariant * KviKvsVariant::unserialize (const QChar ** ppAux) [static, private]
Unserializes the variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
Returns:
KviKvsVariant *
References NULL, unserializeArray(), unserializeBool(), unserializeHash(), unserializeNull(), unserializeNumber(), and unserializeString().
KviKvsVariant * KviKvsVariant::unserialize (const QString & szBuffer) [static]
Unserializes the variant data using the JSON format.
Parameters:
szBuffer The buffer where is stored the serialization
Returns:
KviKvsVariant *
References NULL.
Referenced by KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), unserializeArray(), and unserializeHash().
KviKvsVariant * KviKvsVariant::unserializeArray (const QChar ** ppAux) [static, private]
Unserializes an array into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
Returns:
KviKvsVariant *
References i, KviKvsVariant(), pArray, KviKvsArray::set(), and unserialize().
Referenced by unserialize().
KviKvsVariant * KviKvsVariant::unserializeBool (const QChar ** ppAux, bool bBool) [static, private]
Unserializes a boolean into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
bBool Whether the variant is true or false
Returns:
KviKvsVariant *
References KviQString::equalCIN(), KviKvsVariant(), and NULL.
Referenced by unserialize().
KviKvsVariant * KviKvsVariant::unserializeHash (const QChar ** ppAux) [static, private]
Unserializes a hash into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
Returns:
KviKvsVariant *
References i, KviKvsVariant(), KviKvsHash::set(), unserialize(), and unserializeString().
Referenced by unserialize().
KviKvsVariant * KviKvsVariant::unserializeInteger (const QChar ** ppAux, QString & szData) [static, private]
Unserializes an integer into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
szData The buffer where the serialization is stored
Returns:
KviKvsVariant *
References KviKvsVariant().
Referenced by unserializeNumber().
KviKvsVariant * KviKvsVariant::unserializeNull (const QChar ** ppAux) [static, private]
Unserializes null into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
Returns:
KviKvsVariant *
References KviQString::equalCIN(), KviKvsVariant(), and NULL.
Referenced by unserialize().
KviKvsVariant * KviKvsVariant::unserializeNumber (const QChar ** ppAux) [static, private]
Unserializes a number into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
Returns:
KviKvsVariant *
References NULL, unserializeInteger(), and unserializeReal().
Referenced by unserialize().
KviKvsVariant * KviKvsVariant::unserializeReal (const QChar ** ppAux, QString & szData) [static, private]
Unserializes a double floating point into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
szData The buffer where the serialization is stored
Returns:
KviKvsVariant *
References KviKvsVariant().
Referenced by unserializeNumber().
void KviKvsVariant::unserializeString (const QChar ** ppAux, QString & szBuffer) [static, private]
Unserializes a string into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
szBuffer The buffer to store the unserialization
Returns:
void
References i.
Referenced by unserialize(), unserializeHash(), and unserializeString().
KviKvsVariant * KviKvsVariant::unserializeString (const QChar ** ppAux) [static, private]
Unserializes a string into a variant data using the JSON format.
Parameters:
ppAux The pointer where the serialization is located
Returns:
KviKvsVariant *
References KviKvsVariant(), szBuffer, and unserializeString().
Friends And Related Function Documentation
friend class KviKvsVariantComparison [friend]
Member Data Documentation
KviKvsVariantData* KviKvsVariant::m_pData [protected]
Referenced by appendAsString(), asBoolean(), asHObject(), asInteger(), asNumber(), asReal(), asString(), castToArray(), castToInteger(), castToNumber(), compare(), KviKvsVariantComparison::compareArrayHash(), KviKvsVariantComparison::compareBoolArray(), KviKvsVariantComparison::compareBoolHash(), KviKvsVariantComparison::compareBoolHObject(), KviKvsVariantComparison::compareBoolString(), KviKvsVariantComparison::compareHObjectArray(), KviKvsVariantComparison::compareHObjectHash(), KviKvsVariantComparison::compareIntArray(), KviKvsVariantComparison::compareIntBool(), KviKvsVariantComparison::compareIntHash(), KviKvsVariantComparison::compareIntHObject(), KviKvsVariantComparison::compareIntReal(), KviKvsVariantComparison::compareIntString(), KviKvsVariantComparison::compareRealArray(), KviKvsVariantComparison::compareRealBool(), KviKvsVariantComparison::compareRealHash(), KviKvsVariantComparison::compareRealHObject(), KviKvsVariantComparison::compareRealString(), KviKvsVariantComparison::compareStringArray(), KviKvsVariantComparison::compareStringHash(), KviKvsVariantComparison::compareStringHObject(), convertToArray(), copyFrom(), dump(), getTypeName(), isEmpty(), isEqualToNothing(), KviKvsVariant(), serialize(), setArray(), setBoolean(), setHash(), setHObject(), setInteger(), setNothing(), setReal(), setString(), and takeFrom().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsVariant.h
src/kvirc/kvs/KviKvsVariant.cpp