KVIrc: IdentityProfileEditor Class Reference
IdentityProfileEditor Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
bool editProfile (KviIdentityProfile *pProfile)
IdentityProfileEditor (QWidget *pParent)
~IdentityProfileEditor ()
Protected Slots
void toggleButton (const QString &szText)
Protected Attributes
QLineEdit * m_pAltNickEdit
QPushButton * m_pBtnOk
QLineEdit * m_pNameEdit
QLineEdit * m_pNetworkEdit
QLineEdit * m_pNickEdit
QLineEdit * m_pRealNameEdit
QLineEdit * m_pUserNameEdit
QString m_szAltNick
QString m_szName
QString m_szNetwork
QString m_szNick
QString m_szRealName
QString m_szUserName
Friends
class OptionsWidget_identityProfile
Constructor & Destructor Documentation
IdentityProfileEditor::IdentityProfileEditor (QWidget * pParent)
References __tr2qs_ctx(), KviTalToolTip::add(), connect(), m_pAltNickEdit, m_pBtnOk, m_pNameEdit, m_pNetworkEdit, m_pNickEdit, m_pRealNameEdit, m_pUserNameEdit, m_szAltNick, m_szName, m_szNetwork, m_szNick, m_szRealName, m_szUserName, p, KviTalHBox::setAlignment(), and toggleButton().
IdentityProfileEditor::~IdentityProfileEditor ()
Member Function Documentation
bool IdentityProfileEditor::editProfile (KviIdentityProfile * pProfile)
References KviIdentityProfile::altNick(), m_pAltNickEdit, m_pNameEdit, m_pNetworkEdit, m_pNickEdit, m_pRealNameEdit, m_pUserNameEdit, m_szAltNick, m_szName, m_szNetwork, m_szNick, m_szRealName, m_szUserName, KviIdentityProfile::name(), KviIdentityProfile::network(), KviIdentityProfile::nick(), KviIdentityProfile::realName(), KviIdentityProfile::setAltNick(), KviIdentityProfile::setName(), KviIdentityProfile::setNetwork(), KviIdentityProfile::setNick(), KviIdentityProfile::setRealName(), KviIdentityProfile::setUserName(), and KviIdentityProfile::userName().
Referenced by OptionsWidget_identityProfile::addProfileEntry(), and OptionsWidget_identityProfile::editProfileEntry().
void IdentityProfileEditor::toggleButton (const QString & szText) [protected, slot]
References m_pAltNickEdit, m_pBtnOk, m_pNameEdit, m_pNetworkEdit, m_pNickEdit, m_pRealNameEdit, m_pUserNameEdit, m_szAltNick, m_szName, m_szNetwork, m_szNick, m_szRealName, and m_szUserName.
Referenced by IdentityProfileEditor().
Friends And Related Function Documentation
friend class OptionsWidget_identityProfile [friend]
Member Data Documentation
QLineEdit* IdentityProfileEditor::m_pAltNickEdit [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QPushButton* IdentityProfileEditor::m_pBtnOk [protected]
Referenced by IdentityProfileEditor(), and toggleButton().
QLineEdit* IdentityProfileEditor::m_pNameEdit [protected]
Referenced by editProfile(), OptionsWidget_identityProfile::editProfileOkPressed(), IdentityProfileEditor(), and toggleButton().
QLineEdit* IdentityProfileEditor::m_pNetworkEdit [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QLineEdit* IdentityProfileEditor::m_pNickEdit [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QLineEdit* IdentityProfileEditor::m_pRealNameEdit [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QLineEdit* IdentityProfileEditor::m_pUserNameEdit [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QString IdentityProfileEditor::m_szAltNick [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QString IdentityProfileEditor::m_szName [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QString IdentityProfileEditor::m_szNetwork [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QString IdentityProfileEditor::m_szNick [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QString IdentityProfileEditor::m_szRealName [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
QString IdentityProfileEditor::m_szUserName [protected]
Referenced by editProfile(), IdentityProfileEditor(), and toggleButton().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp