KVIrc: KviTalWizardPrivate Class Reference
KviTalWizardPrivate Class Reference
Public Member Functions
KviTalWizardPageData * findFirstEnabledPage ()
KviTalWizardPageData * findLastEnabledPage ()
KviTalWizardPageData * findNextEnabledPage (QWidget *pReference)
KviTalWizardPageData * findPage (QWidget *pWidget)
KviTalWizardPageData * findPrevEnabledPage (QWidget *pReference)
int reindexPages ()
Public Attributes
int iEnabledPageCount
QPushButton * pBackButton
QPushButton * pCancelButton
KviTalWizardPageData * pCurrentPage
QPushButton * pFinishButton
QWidget * pFinishSpacer
QPushButton * pHelpButton
QGridLayout * pLayout
QPushButton * pNextButton
QWidget * pNextSpacer
KviPointerList
< KviTalWizardPageData > * pPageList
QLabel * pStepsLabel
QLabel * pTitleLabel
QStackedWidget * pWidgetStack
Member Function Documentation
KviTalWizardPageData* KviTalWizardPrivate::findFirstEnabledPage () [inline]
References KviTalWizardPageData::bEnabled, KviPointerList< T >::first(), KviPointerList< T >::next(), NULL, and pPageList.
Referenced by findNextEnabledPage(), and KviTalWizard::showEvent().
KviTalWizardPageData* KviTalWizardPrivate::findLastEnabledPage () [inline]
References KviTalWizardPageData::bEnabled, KviPointerList< T >::last(), NULL, pPageList, and KviPointerList< T >::prev().
Referenced by findPrevEnabledPage().
KviTalWizardPageData* KviTalWizardPrivate::findNextEnabledPage (QWidget * pReference) [inline]
References KviTalWizardPageData::bEnabled, findFirstEnabledPage(), findPage(), KviPointerList< T >::next(), NULL, and pPageList.
Referenced by KviTalWizard::nextButtonClicked(), and KviTalWizard::setCurrentPage().
KviTalWizardPageData* KviTalWizardPrivate::findPage (QWidget * pWidget) [inline]
References KviPointerList< T >::first(), KviPointerList< T >::next(), NULL, and pPageList.
Referenced by findNextEnabledPage(), findPrevEnabledPage(), KviTalWizard::insertPage(), KviTalWizard::setBackEnabled(), KviTalWizard::setCancelEnabled(), KviTalWizard::setCurrentPage(), KviTalWizard::setFinishEnabled(), KviTalWizard::setHelpEnabled(), KviTalWizard::setNextEnabled(), KviTalWizard::setPageEnabled(), and KviTalWizard::setPageTitle().
KviTalWizardPageData* KviTalWizardPrivate::findPrevEnabledPage (QWidget * pReference) [inline]
References KviTalWizardPageData::bEnabled, findLastEnabledPage(), findPage(), NULL, pPageList, and KviPointerList< T >::prev().
Referenced by KviTalWizard::backButtonClicked(), and KviTalWizard::setCurrentPage().
int KviTalWizardPrivate::reindexPages () [inline]
References KviPointerList< T >::first(), KviPointerList< T >::next(), and pPageList.
Referenced by KviTalWizard::insertPage(), and KviTalWizard::setPageEnabled().
Member Data Documentation
int KviTalWizardPrivate::iEnabledPageCount
Referenced by KviTalWizard::insertPage(), KviTalWizard::KviTalWizard(), KviTalWizard::setCurrentPage(), and KviTalWizard::setPageEnabled().
QPushButton* KviTalWizardPrivate::pBackButton
Referenced by KviTalWizard::backButton(), KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
QPushButton* KviTalWizardPrivate::pCancelButton
Referenced by KviTalWizard::cancelButton(), KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
KviTalWizardPageData* KviTalWizardPrivate::pCurrentPage
Referenced by KviTalWizard::backButtonClicked(), KviTalWizard::currentPage(), KviTalWizard::KviTalWizard(), KviTalWizard::nextButtonClicked(), KviTalWizard::setBackEnabled(), KviTalWizard::setCancelEnabled(), KviTalWizard::setCurrentPage(), KviTalWizard::setFinishEnabled(), KviTalWizard::setHelpEnabled(), KviTalWizard::setNextEnabled(), KviTalWizard::setPageEnabled(), and KviTalWizard::showEvent().
QPushButton* KviTalWizardPrivate::pFinishButton
Referenced by KviTalWizard::finishButton(), KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
QWidget* KviTalWizardPrivate::pFinishSpacer
Referenced by KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
QPushButton* KviTalWizardPrivate::pHelpButton
Referenced by KviTalWizard::helpButton(), KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
QGridLayout* KviTalWizardPrivate::pLayout
Referenced by KviTalWizard::KviTalWizard().
QPushButton* KviTalWizardPrivate::pNextButton
Referenced by KviTalWizard::KviTalWizard(), KviTalWizard::nextButton(), and KviTalWizard::setCurrentPage().
QWidget* KviTalWizardPrivate::pNextSpacer
Referenced by KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
KviPointerList<KviTalWizardPageData>* KviTalWizardPrivate::pPageList
Referenced by findFirstEnabledPage(), findLastEnabledPage(), findNextEnabledPage(), findPage(), findPrevEnabledPage(), KviTalWizard::insertPage(), KviTalWizard::KviTalWizard(), reindexPages(), and KviTalWizard::~KviTalWizard().
QLabel* KviTalWizardPrivate::pStepsLabel
Referenced by KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
QLabel* KviTalWizardPrivate::pTitleLabel
Referenced by KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
QStackedWidget* KviTalWizardPrivate::pWidgetStack
Referenced by KviTalWizard::insertPage(), KviTalWizard::KviTalWizard(), and KviTalWizard::setCurrentPage().
The documentation for this class was generated from the following file:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/tal/kvi_tal_wizard.cpp