KVIrc: Idle Class Reference
Idle Class Reference
#include <Idle.h>
Classes
class Private
Signals
void secondsIdle (int)
Public Member Functions
Idle ()
bool isActive () const
int secondsIdle ()
void start ()
void stop ()
bool usingPlatform () const
~Idle ()
Private Slots
void doCheck ()
Private Attributes
Private * d
Constructor & Destructor Documentation
Idle::Idle ()
References Idle::Private::active, Idle::Private::checkTimer, connect(), d, doCheck(), Idle::Private::idleTime, IdlePlatform::init(), p, and platform_ref.
Idle::~Idle ()
References d, platform, and platform_ref.
Member Function Documentation
void Idle::doCheck () [private, slot]
References secondsIdle().
Referenced by Idle().
bool Idle::isActive () const
References Idle::Private::active, and d.
int Idle::secondsIdle ()
References d, i, Idle::Private::idleSince, Idle::Private::lastMousePos, IdlePlatform::secondsIdle(), Idle::Private::startTime, and t().
Referenced by doCheck(), and my_kvs_fnc_globalIdle().
void Idle::secondsIdle (int) [signal]
void Idle::start ()
References Idle::Private::checkTimer, d, Idle::Private::idleSince, Idle::Private::lastMousePos, and Idle::Private::startTime.
Referenced by my_kvs_cmd_startIdleTimer().
void Idle::stop ()
References Idle::Private::checkTimer, and d.
Referenced by my_kvs_cmd_stopIdleTimer().
bool Idle::usingPlatform () const
Member Data Documentation
Private* Idle::d [private]
Referenced by Idle(), isActive(), secondsIdle(), start(), stop(), and ~Idle().
The documentation for this class was generated from the following files:
src/modules/my/Idle.h
src/modules/my/Idle.cpp