KVIrc: KviPixmapPreview Class Reference
KviPixmapPreview Class Reference
#include <KviSelectors.h>
Public Member Functions
KviPixmapPreview (QWidget *par)
void setPixmap (KviPixmap *pix)
~KviPixmapPreview ()
Protected Attributes
QLabel * m_pLabPixmap
Constructor & Destructor Documentation
KviPixmapPreview::KviPixmapPreview (QWidget * par)
References m_pLabPixmap.
KviPixmapPreview::~KviPixmapPreview ()
Member Function Documentation
void KviPixmapPreview::setPixmap (KviPixmap * pix)
References KviPixmap::isNull(), m_pLabPixmap, and KviPixmap::pixmap().
Referenced by OptionsWidget_identityAvatar::chooseAvatar(), KviPixmapSelector::KviPixmapSelector(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), and KviPixmapSelector::setImagePath().
Member Data Documentation
QLabel* KviPixmapPreview::m_pLabPixmap [protected]
Referenced by KviPixmapPreview(), and setPixmap().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp