KVIrc: KviWindowListBase Class Reference
KviWindowListBase Class Reference
#include <KviWindowListBase.h>
Public Member Functions
virtual KviWindowListItem * addItem (KviWindow *)
virtual void applyOptions ()
Qt::DockWidgetArea currentDockArea ()
virtual KviWindowListItem * firstItem ()
virtual KviWindowListItem * item (int number)
KviWindowListBase ()
virtual KviWindowListItem * lastItem (void)
virtual KviWindowListItem * nextItem ()
virtual KviWindowListItem * prevItem (void)
virtual bool removeItem (KviWindowListItem *)
virtual void setActiveItem (KviWindowListItem *)
virtual bool setIterationPointer (KviWindowListItem *)
virtual void switchWindow (bool bNext, bool bInContextOnly, bool bHighlightedOnly=false)
virtual void updatePseudoTransparency ()
virtual void wheelEvent (QWheelEvent *e)
virtual ~KviWindowListBase ()
Static Public Member Functions
static void getTextForConsole (QString &szText, KviConsoleWindow *pConsole)
Protected Slots
virtual void updateActivityMeter ()
void updateDockLocation (Qt::DockWidgetArea newArea)
Protected Attributes
Qt::DockWidgetArea currentArea
QTimer * m_pActivityMeterTimer
KviMainWindow * m_pFrm
QWidget * m_pTitleWidget
Constructor & Destructor Documentation
KviWindowListBase::KviWindowListBase ()
References __tr2qs, applyOptions(), connect(), m_pActivityMeterTimer, updateActivityMeter(), and updateDockLocation().
KviWindowListBase::~KviWindowListBase () [virtual]
References m_pActivityMeterTimer, and m_pTitleWidget.
Member Function Documentation
virtual KviWindowListItem* KviWindowListBase::addItem (KviWindow *) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by KviWindow::createWindowListItem().
void KviWindowListBase::applyOptions () [virtual]
Reimplemented in KviClassicWindowList.
References __tr2qs, KVI_OPTION_BOOL, KviOption_boolShowTreeWindowListHeader, and m_pTitleWidget.
Referenced by KviMainWindow::applyOptions(), KviTreeWindowList::KviTreeWindowList(), and KviWindowListBase().
Qt::DockWidgetArea KviWindowListBase::currentDockArea () [inline]
Referenced by KviMainWindow::createWindowList().
virtual KviWindowListItem* KviWindowListBase::firstItem () [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by TrayIcon::event(), TrayIcon::grabActivityInfo(), item(), and switchWindow().
void KviWindowListBase::getTextForConsole (QString & szText, KviConsoleWindow * pConsole) [static]
References KviWindow::connection(), KviIrcConnection::currentNetworkName(), KviIrcConnection::currentServerName(), KviConsoleWindow::isConnected(), KVI_OPTION_BOOL, KviOption_boolShowNetworkNameForConsoleWindowListEntry, and KviConsoleWindow::statusString().
Referenced by KviTreeWindowListItem::captionChanged(), and KviWindowListButton::drawButtonLabel().
KviWindowListItem * KviWindowListBase::item (int number) [virtual]
References firstItem(), nextItem(), and setIterationPointer().
Referenced by KviTreeWindowList::removeItem().
virtual KviWindowListItem* KviWindowListBase::lastItem (void) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by switchWindow().
virtual KviWindowListItem* KviWindowListBase::nextItem (void) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by TrayIcon::event(), TrayIcon::grabActivityInfo(), item(), and switchWindow().
virtual KviWindowListItem* KviWindowListBase::prevItem (void) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by switchWindow().
virtual bool KviWindowListBase::removeItem (KviWindowListItem *) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by KviWindow::destroyWindowListItem().
virtual void KviWindowListBase::setActiveItem (KviWindowListItem *) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by KviMainWindow::childWindowActivated(), and KviMainWindow::recreateWindowList().
virtual bool KviWindowListBase::setIterationPointer (KviWindowListItem *) [inline, virtual]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by item(), and switchWindow().
void KviWindowListBase::switchWindow (bool bNext, bool bInContextOnly, bool bHighlightedOnly = false) [virtual]
References KviWindow::console(), firstItem(), g_pActiveWindow, g_pMainWindow, KviWindowListItem::highlightLevel(), KviWindowListItem::kviWindow(), lastItem(), nextItem(), prevItem(), KviMainWindow::setActiveWindow(), setIterationPointer(), and KviWindow::windowListItem().
Referenced by KviMainWindow::switchToNextHighlightedWindow(), KviMainWindow::switchToNextWindow(), KviMainWindow::switchToNextWindowInContext(), KviMainWindow::switchToPrevHighlightedWindow(), KviMainWindow::switchToPrevWindow(), KviMainWindow::switchToPrevWindowInContext(), and wheelEvent().
void KviWindowListBase::updateActivityMeter () [protected, virtual, slot]
Reimplemented in KviTreeWindowList, and KviClassicWindowList.
Referenced by KviWindowListBase().
void KviWindowListBase::updateDockLocation (Qt::DockWidgetArea newArea) [protected, slot]
References currentArea.
Referenced by KviWindowListBase().
virtual void KviWindowListBase::updatePseudoTransparency () [inline, virtual]
Reimplemented in KviTreeWindowList.
Referenced by KviMainWindow::updatePseudoTransparency().
void KviWindowListBase::wheelEvent (QWheelEvent * e) [virtual]
References switchWindow().
Member Data Documentation
Qt::DockWidgetArea KviWindowListBase::currentArea [protected]
Referenced by updateDockLocation().
QTimer* KviWindowListBase::m_pActivityMeterTimer [protected]
Referenced by KviWindowListBase(), and ~KviWindowListBase().
KviMainWindow* KviWindowListBase::m_pFrm [protected]
QWidget* KviWindowListBase::m_pTitleWidget [protected]
Referenced by applyOptions(), and ~KviWindowListBase().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviWindowListBase.h
src/kvirc/ui/KviWindowListBase.cpp