KVIrc: DccVoiceThread Class Reference
DccVoiceThread Class Reference
#include <DccVoiceWindow.h>
Public Member Functions
DccVoiceThread (KviWindow *wnd, kvi_socket_t fd, KviDccVoiceThreadOptions *opt)
~DccVoiceThread ()
Public Member Functions inherited from DccThread
DccThread (QObject *par, kvi_socket_t fd)
QObject * parent ()
void postErrorEvent (int err)
void postMessageEvent (const char *message)
~DccThread ()
Public Member Functions inherited from KviSensitiveThread
void enqueueEvent (KviThreadEvent *e)
KviSensitiveThread ()
void terminate ()
virtual ~KviSensitiveThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
bool checkSoundcard ()
void closeSoundcard ()
bool openSoundcard (int mode)
bool openSoundcardForReading ()
bool openSoundcardForWriting ()
bool openSoundcardWithDuplexOption (int openMode, int failMode)
bool readWriteStep ()
virtual void run ()
bool soundStep ()
void startPlaying ()
void startRecording ()
void stopPlaying ()
void stopRecording ()
Protected Member Functions inherited from DccThread
bool handleInvalidSocketRead (int readLen)
Protected Member Functions inherited from KviSensitiveThread
KviThreadEvent * dequeueEvent ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
Protected Attributes
bool m_bPlaying
bool m_bRecording
bool m_bRecordingRequestPending
bool m_bSoundcardChecked
int m_iInputBufferSize
int m_iLastSignalBufferSize
long m_iLastSignalBufferTime
KviDataBuffer m_inFrameBuffer
KviDataBuffer m_inSignalBuffer
int m_iOutputBufferSize
KviDataBuffer m_outFrameBuffer
KviDataBuffer m_outSignalBuffer
KviMutex * m_pInfoMutex
KviDccVoiceThreadOptions * m_pOpt
int m_soundFd
int m_soundFdMode
Protected Attributes inherited from DccThread
kvi_socket_t m_fd
KviMutex * m_pMutex
QObject * m_pParent
Protected Attributes inherited from KviSensitiveThread
KviPointerList< KviThreadEvent > * m_pLocalEventQueue
KviMutex * m_pLocalEventQueueMutex
Friends
class DccVoiceWindow
Constructor & Destructor Documentation
DccVoiceThread::DccVoiceThread (KviWindow * wnd, kvi_socket_t fd, KviDccVoiceThreadOptions * opt)
References m_bPlaying, m_bRecording, m_bRecordingRequestPending, m_bSoundcardChecked, m_pInfoMutex, m_pOpt, m_soundFd, and m_soundFdMode.
DccVoiceThread::~DccVoiceThread ()
References m_pInfoMutex, m_pOpt, and _KviDccVoiceThreadOptions::pCodec.
Member Function Documentation
bool DccVoiceThread::checkSoundcard () protected
References __tr2qs_ctx(), _KviDccVoiceThreadOptions::bForceHalfDuplex, closeSoundcard(), m_bSoundcardChecked, m_pOpt, m_soundFd, openSoundcard(), and DccThread::postMessageEvent().
Referenced by openSoundcardWithDuplexOption().
void DccVoiceThread::closeSoundcard () protected
References m_soundFd, and m_soundFdMode.
Referenced by checkSoundcard(), openSoundcard(), stopPlaying(), and stopRecording().
bool DccVoiceThread::openSoundcard (int mode) protected
References __tr2qs_ctx(), _KviDccVoiceThreadOptions::bForceHalfDuplex, closeSoundcard(), KviCString::Format, _KviDccVoiceThreadOptions::iSampleRate, KVI_FORMAT, KVI_NUM_CHANNELS, KVI_SNDCTL_FRAG_SIZE, m_pOpt, m_soundFd, m_soundFdMode, DccThread::postMessageEvent(), KviCString::ptr(), and _KviDccVoiceThreadOptions::szSoundDevice.
Referenced by checkSoundcard(), and openSoundcardWithDuplexOption().
bool DccVoiceThread::openSoundcardForReading () protected
References openSoundcardWithDuplexOption().
Referenced by startRecording().
bool DccVoiceThread::openSoundcardForWriting () protected
References openSoundcardWithDuplexOption().
Referenced by startPlaying().
bool DccVoiceThread::openSoundcardWithDuplexOption (int openMode, int failMode) protected
References __tr2qs_ctx(), _KviDccVoiceThreadOptions::bForceHalfDuplex, checkSoundcard(), m_bSoundcardChecked, m_pOpt, m_soundFd, m_soundFdMode, openSoundcard(), and DccThread::postMessageEvent().
Referenced by openSoundcardForReading(), and openSoundcardForWriting().
bool DccVoiceThread::readWriteStep () protected
References KviDataBuffer::data(), DccVoiceCodec::decode(), DccThread::handleInvalidSocketRead(), kvi_select(), kvi_socket_recv(), kvi_socket_send(), DccThread::m_fd, m_inFrameBuffer, m_inSignalBuffer, m_outFrameBuffer, m_pOpt, _KviDccVoiceThreadOptions::pCodec, KviDataBuffer::remove(), KviDataBuffer::resize(), and KviDataBuffer::size().
Referenced by run().
void DccVoiceThread::run () protected virtual
COMPILE_DISABLE_DCC_VOICE
Reimplemented from KviThread.
References DccVoiceCodec::decodedFrameSize(), KviSensitiveThread::dequeueEvent(), e, DccVoiceCodec::encodedFrameSize(), KVI_DCC_THREAD_EVENT_ACTION, KVI_INVALID_SOCKET, kvi_socket_close, KVI_THREAD_EVENT_TERMINATE, KviMutex::lock(), m_bRecordingRequestPending, DccThread::m_fd, m_iInputBufferSize, m_inSignalBuffer, m_iOutputBufferSize, m_outFrameBuffer, m_pInfoMutex, m_pOpt, _KviDccVoiceThreadOptions::pCodec, readWriteStep(), KviDataBuffer::size(), soundStep(), startRecording(), stopRecording(), and KviMutex::unlock().
bool DccVoiceThread::soundStep () protected
References KviDataBuffer::addSize(), KviDataBuffer::data(), DccVoiceCodec::encode(), _KviDccVoiceThreadOptions::iPreBufferSize, KVI_FRAGMENT_SIZE_IN_BYTES, m_bPlaying, m_bRecording, m_iLastSignalBufferSize, m_iLastSignalBufferTime, m_inSignalBuffer, m_outFrameBuffer, m_outSignalBuffer, m_pOpt, m_soundFd, _KviDccVoiceThreadOptions::pCodec, KviDataBuffer::remove(), KviDataBuffer::resize(), KviDataBuffer::size(), startPlaying(), and stopPlaying().
Referenced by run().
void DccVoiceThread::startPlaying () protected
References e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VOICE_THREAD_ACTION_START_PLAYING, m_bPlaying, openSoundcardForWriting(), DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by soundStep().
void DccVoiceThread::startRecording () protected
References e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VOICE_THREAD_ACTION_START_RECORDING, m_bRecording, m_bRecordingRequestPending, openSoundcardForReading(), DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by run().
void DccVoiceThread::stopPlaying () protected
References closeSoundcard(), e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VOICE_THREAD_ACTION_STOP_PLAYING, m_bPlaying, m_bRecording, DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by soundStep().
void DccVoiceThread::stopRecording () protected
References closeSoundcard(), e, KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_VOICE_THREAD_ACTION_STOP_RECORDING, m_bPlaying, m_bRecording, m_bRecordingRequestPending, DccThread::parent(), KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by run().
Friends And Related Function Documentation
friend class DccVoiceWindow friend
Member Data Documentation
bool DccVoiceThread::m_bPlaying protected
Referenced by DccVoiceThread(), soundStep(), startPlaying(), stopPlaying(), and stopRecording().
bool DccVoiceThread::m_bRecording protected
Referenced by DccVoiceThread(), soundStep(), startRecording(), stopPlaying(), and stopRecording().
bool DccVoiceThread::m_bRecordingRequestPending protected
Referenced by DccVoiceThread(), run(), startRecording(), and stopRecording().
bool DccVoiceThread::m_bSoundcardChecked protected
Referenced by checkSoundcard(), DccVoiceThread(), and openSoundcardWithDuplexOption().
int DccVoiceThread::m_iInputBufferSize protected
Referenced by run(), and DccVoiceWindow::updateInfo().
int DccVoiceThread::m_iLastSignalBufferSize protected
Referenced by soundStep().
long DccVoiceThread::m_iLastSignalBufferTime protected
Referenced by soundStep().
KviDataBuffer DccVoiceThread::m_inFrameBuffer protected
Referenced by readWriteStep().
KviDataBuffer DccVoiceThread::m_inSignalBuffer protected
Referenced by readWriteStep(), run(), and soundStep().
int DccVoiceThread::m_iOutputBufferSize protected
Referenced by run(), and DccVoiceWindow::updateInfo().
KviDataBuffer DccVoiceThread::m_outFrameBuffer protected
Referenced by readWriteStep(), run(), and soundStep().
KviDataBuffer DccVoiceThread::m_outSignalBuffer protected
Referenced by soundStep().
KviMutex* DccVoiceThread::m_pInfoMutex protected
Referenced by DccVoiceThread(), run(), DccVoiceWindow::updateInfo(), and ~DccVoiceThread().
KviDccVoiceThreadOptions* DccVoiceThread::m_pOpt protected
Referenced by checkSoundcard(), DccVoiceThread(), openSoundcard(), openSoundcardWithDuplexOption(), readWriteStep(), run(), soundStep(), and ~DccVoiceThread().
int DccVoiceThread::m_soundFd protected
Referenced by checkSoundcard(), closeSoundcard(), DccVoiceThread(), openSoundcard(), openSoundcardWithDuplexOption(), and soundStep().
int DccVoiceThread::m_soundFdMode protected
Referenced by closeSoundcard(), DccVoiceThread(), openSoundcard(), and openSoundcardWithDuplexOption().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceWindow.h
src/modules/dcc/DccVoiceWindow.cpp