KVIrc: DccFileTransfer Class Reference
DccFileTransfer Class Reference
#include <DccFileTransfer.h>
Public Slots
void abort ()
void retryDCC ()
void retryRevDCC ()
void retryTDCC ()
Public Member Functions
virtual bool active ()
unsigned int averageSpeed ()
int bandwidthLimit ()
DccFileTransfer (DccDescriptor *dcc)
virtual const char * dccMarshalOutputContextString ()
virtual KviWindow * dccMarshalOutputWindow ()
virtual int displayHeight (int iLineSpacing)
virtual void displayPaint (QPainter *p, int column, QRect rect)
bool doResume (const char *filename, const char *port, quint64 filePos)
virtual bool event (QEvent *e)
virtual void fillContextPopup (QMenu *m)
virtual void fillStatusString (QString &szBuffer)
virtual DccThread * getSlaveThread ()
unsigned int instantSpeed ()
bool isFileUpload ()
virtual QString localFileName ()
bool resumeAccepted (const char *filename, const char *port, const char *szZeroPortTag)
void setBandwidthLimit (int iVal)
virtual QString tipText ()
unsigned int transferredBytes ()
~DccFileTransfer ()
Public Member Functions inherited from KviFileTransfer
virtual void die ()
void displayUpdate ()
int id ()
void invokeTransferWindow (bool bCreateMinimized=false, bool bNoRaise=false)
KviFileTransfer ()
KviFileTransferManager * manager ()
KviWindow * outputWindow ()
virtual QString retryCommand ()
void setDisplayItem (KviTalTableWidgetItemEx *i)
bool terminated ()
KviWindow * transferWindow ()
~KviFileTransfer ()
Public Member Functions inherited from DccMarshalOutputContext
DccMarshalOutputContext ()
virtual ~DccMarshalOutputContext ()
Static Public Member Functions
static void done ()
static bool handleResumeAccepted (const char *filename, const char *port, const char *szZeroPortTag)
static bool handleResumeRequest (const char *filename, const char *port, quint64 filePos)
static void init ()
static DccFileTransfer * nonFailedTransferWithLocalFileName (const QString &szLocalFileName)
static unsigned int runningTransfersCount ()
static unsigned int transferCount ()
Protected Slots
void bandwidthDialogDestroyed ()
void configureBandwidth ()
void connected ()
void connectionInProgress ()
void handleMarshalError (KviError::Code)
void resumeTimedOut ()
void sslError (const char *msg)
void startingSSLHandshake ()
Protected Member Functions
void addToTransferLog (const QString &s)
KviWindow * eventWindow ()
void listenOrConnect ()
void outputAndLog (const QString &s)
void outputAndLog (int msgtype, const QString &s)
void startConnection ()
Private Types
enum GeneralStatus { Connecting, Transferring, Success, Failure }
Private Attributes
GeneralStatus m_eGeneralStatus
DccFileTransferBandwidthDialog * m_pBandwidthDialog
DccDescriptor * m_pDescriptor
DccMarshal * m_pMarshal
QTimer * m_pResumeTimer
DccRecvThread * m_pSlaveRecvThread
DccSendThread * m_pSlaveSendThread
KviCString m_szDccType
QString m_szStatusString
KviCString m_szTarget
QString m_szTransferIdString
QString m_szTransferLog
kvi_time_t m_tTransferEndTime
kvi_time_t m_tTransferStartTime
unsigned int m_uMaxBandwidth
quint64 m_uTotalFileSize
Additional Inherited Members
Protected Attributes inherited from KviFileTransfer
int m_iId
KviTalTableWidgetItemEx * m_pDisplayItem
Member Enumeration Documentation
enum DccFileTransfer::GeneralStatus private
Enumerator
Connecting
Transferring
Success
Failure
Constructor & Destructor Documentation
DccFileTransfer::DccFileTransfer (DccDescriptor * dcc)
References __tr2qs_ctx(), KviPointerList< T >::append(), DccDescriptor::bIsTdcc, DccDescriptor::bRecvFile, connect(), connected(), Connecting, connectionInProgress(), DccMarshalOutputContext::DccMarshal, handleMarshalError(), init(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolLimitDccRecvSpeed, KviOption_boolLimitDccSendSpeed, KviOption_uintMaxDccRecvSpeed, KviOption_uintMaxDccSendSpeed, m_eGeneralStatus, m_pBandwidthDialog, m_pDescriptor, m_pMarshal, m_pResumeTimer, m_pSlaveRecvThread, m_pSlaveSendThread, m_szDccType, m_szStatusString, m_szTransferIdString, m_tTransferEndTime, m_tTransferStartTime, m_uMaxBandwidth, m_uTotalFileSize, MAX_DCC_BANDWIDTH_LIMIT, KviCString::prepend(), DccDescriptor::setTransfer(), sslError(), startConnection(), startingSSLHandshake(), DccDescriptor::szFileSize, and DccDescriptor::szLocalFileSize.
DccFileTransfer::~DccFileTransfer ()
References KviThreadManager::killPendingEvents(), m_pBandwidthDialog, m_pDescriptor, m_pMarshal, m_pResumeTimer, m_pSlaveRecvThread, m_pSlaveSendThread, KviPointerList< T >::removeRef(), and KviSensitiveThread::terminate().
Member Function Documentation
void DccFileTransfer::abort () slot
References __tr2qs_ctx(), __tr_ctx, DccMarshal::abort(), DccDescriptor::bRecvFile, KviFileTransfer::displayUpdate(), eventWindow(), Failure, KviApplication::fileDownloadTerminated(), g_pApp, DccDescriptor::idString(), KVI_OUT_DCCERROR, kvi_unixTime, KviEvent_OnDCCFileTransferFailed, KVS_TRIGGER_EVENT_3, m_eGeneralStatus, m_pDescriptor, m_pMarshal, m_pSlaveRecvThread, m_pSlaveSendThread, m_szStatusString, m_tTransferEndTime, outputAndLog(), DccRecvThread::receivedBytes(), DccSendThread::sentBytes(), DccDescriptor::szFileName, DccDescriptor::szLocalFileName, DccDescriptor::szNick, and KviSensitiveThread::terminate().
Referenced by dcc_kvs_cmd_abort(), fillContextPopup(), retryDCC(), retryRevDCC(), and retryTDCC().
bool DccFileTransfer::active () virtual
Implements KviFileTransfer.
References Connecting, m_eGeneralStatus, and Transferring.
Referenced by fillContextPopup().
void DccFileTransfer::addToTransferLog (const QString & s) protected
References m_szTransferLog, and s.
Referenced by outputAndLog().
unsigned int DccFileTransfer::averageSpeed ()
References DccSendThread::averageSpeed(), DccRecvThread::averageSpeed(), DccDescriptor::bRecvFile, DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), m_pDescriptor, m_pSlaveRecvThread, and m_pSlaveSendThread.
Referenced by dcc_kvs_fnc_averageSpeed().
void DccFileTransfer::bandwidthDialogDestroyed () protected slot
References m_pBandwidthDialog.
Referenced by configureBandwidth().
int DccFileTransfer::bandwidthLimit ()
References DccSendThread::bandwidthLimit(), DccRecvThread::bandwidthLimit(), DccDescriptor::bRecvFile, DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), m_pDescriptor, m_pSlaveRecvThread, m_pSlaveSendThread, m_uMaxBandwidth, and MAX_DCC_BANDWIDTH_LIMIT.
Referenced by DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog().
void DccFileTransfer::configureBandwidth () protected slot
References bandwidthDialogDestroyed(), connect(), g_pMainWindow, and m_pBandwidthDialog.
Referenced by fillContextPopup().
void DccFileTransfer::connected () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, _KviDccSendThreadOptions::bFastSend, _KviDccSendThreadOptions::bIsTdcc, DccDescriptor::bIsTdcc, _KviDccRecvThreadOptions::bIsTdcc, _KviDccSendThreadOptions::bNoAcks, _KviDccRecvThreadOptions::bNoAcks, DccDescriptor::bNoAcks, DccDescriptor::bRecvFile, _KviDccRecvThreadOptions::bResume, DccDescriptor::bResume, _KviDccRecvThreadOptions::bSend64BitAck, _KviDccRecvThreadOptions::bSendZeroAck, KviFileTransfer::displayUpdate(), eventWindow(), DccDescriptor::idString(), _KviDccSendThreadOptions::iIdleStepLengthInMSec, _KviDccRecvThreadOptions::iIdleStepLengthInMSec, _KviDccSendThreadOptions::iPacketSize, KVI_OPTION_BOOL, KVI_OPTION_UINT, kvi_unixTime, KviEvent_OnDCCFileTransferBegin, KviOption_boolDccSendForceIdleStep, KviOption_boolSend64BitAckInDccRecv, KviOption_boolSendZeroAckInDccRecv, KviOption_boolUseFastDccSend, KviOption_uintDccSendIdleStepInMSec, KviOption_uintDccSendPacketSize, KVS_TRIGGER_EVENT_1, DccMarshal::localIp(), DccMarshal::localPort(), m_eGeneralStatus, m_pDescriptor, m_pMarshal, m_pSlaveRecvThread, m_pSlaveSendThread, m_szStatusString, m_tTransferStartTime, m_uMaxBandwidth, o, outputAndLog(), DccMarshal::releaseSocket(), DccMarshal::remoteIp(), DccMarshal::remotePort(), s, KviThread::start(), _KviDccSendThreadOptions::szFileName, _KviDccRecvThreadOptions::szFileName, DccDescriptor::szFileSize, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szLocalFileName, DccDescriptor::szPort, Transferring, _KviDccSendThreadOptions::uMaxBandwidth, _KviDccRecvThreadOptions::uMaxBandwidth, _KviDccSendThreadOptions::uStartPosition, and _KviDccRecvThreadOptions::uTotalFileSize.
Referenced by DccFileTransfer().
void DccFileTransfer::connectionInProgress () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bIsTdcc, DccDescriptor::bSendRequest, KviWindow::connection(), DccDescriptor::console(), KviQString::cutToLast(), KviFileTransfer::displayUpdate(), KviIrcServerParser::encodeCtcpParameter(), KviIrcConnection::encodeText(), eventWindow(), KviIrcConnectionUserInfo::hostIp(), DccDescriptor::idString(), KviNetUtils::isRoutableIpString(), DccDescriptor::isZeroPortRequest(), KVI_OPTION_BOOL, KviEvent_OnDCCFileTransferConnectionInProgress, KviOption_boolDCCFileTransferReplaceOutgoingSpacesWithUnderscores, KviOption_boolDccGuessIpFromServerWhenLocalIsUnroutable, KVS_TRIGGER_EVENT_1, DccMarshal::localIp(), DccMarshal::localPort(), m_pDescriptor, m_pMarshal, m_szDccType, m_szStatusString, outputAndLog(), KviCString::prepend(), KviCString::ptr(), KviIrcConnection::sendFmtData(), KviNetUtils::stringIpToBinaryIp(), DccDescriptor::szFakeIp, DccDescriptor::szFakePort, DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szLocalFileSize, DccDescriptor::szNick, DccDescriptor::szPort, KviIrcConnection::userInfo(), and DccDescriptor::zeroPortRequestTag().
Referenced by DccFileTransfer().
const char * DccFileTransfer::dccMarshalOutputContextString () virtual
Implements DccMarshalOutputContext.
References m_szTransferIdString.
KviWindow * DccFileTransfer::dccMarshalOutputWindow () virtual
Implements DccMarshalOutputContext.
References KviFileTransfer::transferWindow().
int DccFileTransfer::displayHeight (int iLineSpacing) virtual
Reimplemented from KviFileTransfer.
void DccFileTransfer::displayPaint (QPainter * p, int column, QRect rect) virtual
Implements KviFileTransfer.
References __tr2qs_ctx(), DccSendThread::ackedBytes(), DccSendThread::averageSpeed(), DccRecvThread::averageSpeed(), DccDescriptor::bNoAcks, DccDescriptor::bRecvFile, COLUMN_FILEINFO, COLUMN_PROGRESS, COLUMN_TRANSFERTYPE, Connecting, DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), Failure, DccSendThread::filePosition(), DccRecvThread::filePosition(), KviCString::Format, KviNetUtils::formatNetworkBandwidthString(), KviTimeUtils::formatTimeInterval(), g_pDccFileTransferIcon, DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), DccSendThread::instantSpeed(), DccRecvThread::instantSpeed(), kvi_timeSpan, m_eGeneralStatus, m_pDescriptor, m_pSlaveRecvThread, m_pSlaveSendThread, m_szStatusString, m_tTransferEndTime, m_tTransferStartTime, m_uTotalFileSize, KviQString::makeSizeReadable(), KviTimeUtils::NoLeadingEmptyIntervals, KviTimeUtils::NoLeadingZeroes, Success, DccDescriptor::szFileName, DccDescriptor::szIp, DccDescriptor::szLocalFileName, DccDescriptor::szNick, DccDescriptor::szPort, and Transferring.
void DccFileTransfer::done () static
References KviPointerList< T >::first(), g_pDccFileTransferIcon, g_pDccFileTransfers, and t().
Referenced by DccBroker::~DccBroker().
bool DccFileTransfer::doResume (const char * filename, const char * port, quint64 filePos)
References __tr2qs_ctx(), _OUTPUT_VERBOSE, DccDescriptor::bRecvFile, KviWindow::connection(), DccDescriptor::console(), DccMarshal::dccPort(), KviIrcServerParser::encodeCtcpParameter(), KviIrcConnection::encodeText(), KviQString::equalCI(), KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KVI_OUT_DCCMSG, KviOption_boolAcceptBrokenFileNameDccResumeRequests, KviOption_boolAcceptMismatchedPortDccResumeRequests, m_pDescriptor, m_pMarshal, m_pSlaveRecvThread, m_pSlaveSendThread, outputAndLog(), KviCString::ptr(), KviIrcConnection::sendFmtData(), DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szLocalFileSize, and DccDescriptor::szNick.
bool DccFileTransfer::event (QEvent * e) virtual
References __tr2qs_ctx(), __tr_no_xgettext_ctx, KviApplication::activeConsole(), DccDescriptor::bIsTdcc, DccDescriptor::bRecvFile, c, DccDescriptor::console(), KviFileTransfer::die(), KviFileTransfer::displayUpdate(), eventWindow(), Failure, KviApplication::fileDownloadTerminated(), g_pApp, KviError::getDescription(), DccDescriptor::idString(), KVI_DCC_THREAD_EVENT_ERROR, KVI_DCC_THREAD_EVENT_MESSAGE, KVI_DCC_THREAD_EVENT_SUCCESS, KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KVI_OUT_DCCMSG, KVI_THREAD_EVENT, kvi_unixTime, KviEvent_OnDCCFileTransferFailed, KviEvent_OnDCCFileTransferSuccess, KviOption_boolAutoCloseDccSendOnSuccess, KviOption_boolNotifyDccSendSuccessInConsole, KVS_TRIGGER_EVENT_2, KVS_TRIGGER_EVENT_3, m_eGeneralStatus, m_pDescriptor, m_pResumeTimer, m_pSlaveRecvThread, m_pSlaveSendThread, m_szStatusString, m_tTransferEndTime, KviWindow::output(), outputAndLog(), KviCString::ptr(), DccRecvThread::receivedBytes(), DccSendThread::sentBytes(), Success, DccDescriptor::szFileName, DccDescriptor::szIp, DccDescriptor::szLocalFileName, DccDescriptor::szNick, DccDescriptor::szPort, and KviApplication::windowExists().
KviWindow * DccFileTransfer::eventWindow () protected
References DccDescriptor::console(), m_pDescriptor, KviFileTransfer::transferWindow(), and w.
Referenced by abort(), connected(), connectionInProgress(), event(), and handleMarshalError().
void DccFileTransfer::fillContextPopup (QMenu * m) virtual
Implements KviFileTransfer.
References __tr2qs_ctx(), abort(), active(), configureBandwidth(), retryDCC(), retryRevDCC(), and retryTDCC().
void DccFileTransfer::fillStatusString (QString & szBuffer) virtual
References Connecting, Failure, m_eGeneralStatus, Success, and Transferring.
Referenced by dcc_kvs_fnc_transferStatus().
DccThread * DccFileTransfer::getSlaveThread () virtual
References DccDescriptor::bRecvFile, m_pDescriptor, m_pSlaveRecvThread, and m_pSlaveSendThread.
Referenced by dcc_kvs_fnc_getSSLCertInfo().
void DccFileTransfer::handleMarshalError (KviError::Code eError) protected slot
References __tr2qs_ctx(), KviFileTransfer::displayUpdate(), eventWindow(), Failure, KviError::getDescription(), DccDescriptor::idString(), KviEvent_OnDCCFileTransferFailed, KVS_TRIGGER_EVENT_3, m_eGeneralStatus, m_pDescriptor, m_szStatusString, and outputAndLog().
Referenced by DccFileTransfer(), listenOrConnect(), and resumeTimedOut().
bool DccFileTransfer::handleResumeAccepted (const char * filename, const char * port, const char * szZeroPortTag) static
References KviPointerList< T >::first(), KviPointerList< T >::next(), and t().
Referenced by DccBroker::handleResumeAccepted().
bool DccFileTransfer::handleResumeRequest (const char * filename, const char * port, quint64 filePos) static
References KviPointerList< T >::first(), KviPointerList< T >::next(), and t().
Referenced by DccBroker::handleResumeRequest().
void DccFileTransfer::init () static
References g_pDccFileTransferIcon, g_pIconManager, KviIconManager::getImage(), and KviPointerList< T >::setAutoDelete().
Referenced by DccBroker::DccBroker(), and DccFileTransfer().
unsigned int DccFileTransfer::instantSpeed ()
References DccDescriptor::bRecvFile, DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), DccSendThread::instantSpeed(), DccRecvThread::instantSpeed(), m_pDescriptor, m_pSlaveRecvThread, and m_pSlaveSendThread.
Referenced by dcc_kvs_fnc_currentSpeed().
bool DccFileTransfer::isFileUpload () inline
References DccDescriptor::isFileUpload(), and m_pDescriptor.
Referenced by DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog().
void DccFileTransfer::listenOrConnect () protected
References DccDescriptor::bActive, DccDescriptor::bDoTimeout, DccMarshal::dccConnect(), DccMarshal::dccListen(), KviFileTransfer::displayUpdate(), handleMarshalError(), m_pDescriptor, m_pMarshal, KviError::Success, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, and DccDescriptor::szPort.
Referenced by resumeAccepted(), and startConnection().
QString DccFileTransfer::localFileName () virtual
Reimplemented from KviFileTransfer.
References m_pDescriptor, and DccDescriptor::szLocalFileName.
DccFileTransfer * DccFileTransfer::nonFailedTransferWithLocalFileName (const QString & szLocalFileName) static
References Failure, KviPointerList< T >::first(), KviPointerList< T >::next(), and t().
Referenced by DccBroker::renameOverwriteResume().
void DccFileTransfer::outputAndLog (const QString & s) protected
References addToTransferLog(), KVI_OUT_DCCMSG, m_szTransferIdString, KviWindow::output(), and KviFileTransfer::transferWindow().
Referenced by abort(), connected(), connectionInProgress(), doResume(), event(), handleMarshalError(), resumeAccepted(), sslError(), startConnection(), and startingSSLHandshake().
void DccFileTransfer::outputAndLog (int msgtype, const QString & s) protected
References addToTransferLog(), m_szTransferIdString, KviWindow::output(), and KviFileTransfer::transferWindow().
bool DccFileTransfer::resumeAccepted (const char * filename, const char * port, const char * szZeroPortTag)
References __tr2qs_ctx(), DccDescriptor::bRecvFile, DccDescriptor::bResume, KVI_OPTION_BOOL, kvi_strEqualCI(), KviOption_boolAcceptBrokenFileNameDccResumeRequests, listenOrConnect(), m_pDescriptor, m_pResumeTimer, m_pSlaveRecvThread, outputAndLog(), DccDescriptor::szFileName, DccDescriptor::szLocalFileSize, DccDescriptor::szPort, and DccDescriptor::zeroPortRequestTag().
void DccFileTransfer::resumeTimedOut () protected slot
References KviError::ConnectionTimedOut, handleMarshalError(), and m_pResumeTimer.
Referenced by startConnection().
void DccFileTransfer::retryDCC () slot
References abort(), KviQString::escapeKvs(), KviQString::EscapeSpace, g_pActiveWindow, DccDescriptor::idString(), DccDescriptor::localFileName(), m_pDescriptor, DccDescriptor::remoteNick(), and KviKvsScript::run().
Referenced by fillContextPopup().
void DccFileTransfer::retryRevDCC () slot
References abort(), KviQString::escapeKvs(), KviQString::EscapeSpace, g_pActiveWindow, DccDescriptor::idString(), DccDescriptor::localFileName(), m_pDescriptor, DccDescriptor::remoteNick(), and KviKvsScript::run().
Referenced by fillContextPopup().
void DccFileTransfer::retryTDCC () slot
References abort(), KviQString::escapeKvs(), KviQString::EscapeSpace, g_pActiveWindow, DccDescriptor::idString(), DccDescriptor::localFileName(), m_pDescriptor, DccDescriptor::remoteNick(), and KviKvsScript::run().
Referenced by fillContextPopup().
unsigned int DccFileTransfer::runningTransfersCount () static
References KviPointerList< T >::first(), KviPointerList< T >::next(), and t().
Referenced by dcc_module_check_concurrent_transfers_limit().
void DccFileTransfer::setBandwidthLimit (int iVal)
References DccDescriptor::bRecvFile, DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), m_pDescriptor, m_pSlaveRecvThread, m_pSlaveSendThread, m_uMaxBandwidth, MAX_DCC_BANDWIDTH_LIMIT, DccSendThread::setBandwidthLimit(), and DccRecvThread::setBandwidthLimit().
Referenced by dcc_kvs_cmd_setBandwidthLimit(), and DccFileTransferBandwidthDialog::okClicked().
void DccFileTransfer::sslError (const char * msg) protected slot
References __tr2qs_ctx(), KVI_OUT_DCCERROR, and outputAndLog().
Referenced by DccFileTransfer().
void DccFileTransfer::startConnection () protected
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bRecvFile, DccDescriptor::bResume, connect(), KviWindow::connection(), DccDescriptor::console(), KviFileTransfer::displayUpdate(), KviIrcServerParser::encodeCtcpParameter(), KviIrcConnection::encodeText(), DccDescriptor::isZeroPortRequest(), KVI_OPTION_UINT, KviOption_uintDccSocketTimeout, listenOrConnect(), m_pDescriptor, m_pResumeTimer, m_szDccType, m_szStatusString, outputAndLog(), KviCString::ptr(), resumeTimedOut(), KviIrcConnection::sendFmtData(), DccDescriptor::szFileName, DccDescriptor::szLocalFileSize, DccDescriptor::szNick, DccDescriptor::szPort, and DccDescriptor::zeroPortRequestTag().
Referenced by DccFileTransfer().
void DccFileTransfer::startingSSLHandshake () protected slot
References __tr2qs_ctx(), KVI_OUT_SSL, and outputAndLog().
Referenced by DccFileTransfer().
QString DccFileTransfer::tipText () virtual
Reimplemented from KviFileTransfer.
References __tr2qs_ctx(), m_szDccType, m_szTransferLog, KviCString::ptr(), and s.
unsigned int DccFileTransfer::transferCount () static
References KviPointerList< T >::count().
Referenced by DccBroker::canUnload().
unsigned int DccFileTransfer::transferredBytes ()
References DccDescriptor::bRecvFile, DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), DccSendThread::filePosition(), DccRecvThread::filePosition(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), m_pDescriptor, m_pSlaveRecvThread, and m_pSlaveSendThread.
Referenced by dcc_kvs_fnc_transferredBytes().
Member Data Documentation
GeneralStatus DccFileTransfer::m_eGeneralStatus private
Referenced by abort(), active(), connected(), DccFileTransfer(), displayPaint(), event(), fillStatusString(), and handleMarshalError().
DccFileTransferBandwidthDialog* DccFileTransfer::m_pBandwidthDialog private
Referenced by bandwidthDialogDestroyed(), configureBandwidth(), DccFileTransfer(), and ~DccFileTransfer().
DccDescriptor* DccFileTransfer::m_pDescriptor private
Referenced by abort(), averageSpeed(), bandwidthLimit(), connected(), connectionInProgress(), DccFileTransfer(), displayPaint(), doResume(), event(), eventWindow(), getSlaveThread(), handleMarshalError(), instantSpeed(), isFileUpload(), listenOrConnect(), localFileName(), resumeAccepted(), retryDCC(), retryRevDCC(), retryTDCC(), setBandwidthLimit(), startConnection(), transferredBytes(), and ~DccFileTransfer().
DccMarshal* DccFileTransfer::m_pMarshal private
Referenced by abort(), connected(), connectionInProgress(), DccFileTransfer(), doResume(), listenOrConnect(), and ~DccFileTransfer().
QTimer* DccFileTransfer::m_pResumeTimer private
Referenced by DccFileTransfer(), event(), resumeAccepted(), resumeTimedOut(), startConnection(), and ~DccFileTransfer().
DccRecvThread* DccFileTransfer::m_pSlaveRecvThread private
Referenced by abort(), averageSpeed(), bandwidthLimit(), connected(), DccFileTransfer(), displayPaint(), doResume(), event(), getSlaveThread(), instantSpeed(), resumeAccepted(), setBandwidthLimit(), transferredBytes(), and ~DccFileTransfer().
DccSendThread* DccFileTransfer::m_pSlaveSendThread private
Referenced by abort(), averageSpeed(), bandwidthLimit(), connected(), DccFileTransfer(), displayPaint(), doResume(), event(), getSlaveThread(), instantSpeed(), setBandwidthLimit(), transferredBytes(), and ~DccFileTransfer().
KviCString DccFileTransfer::m_szDccType private
Referenced by connectionInProgress(), DccFileTransfer(), startConnection(), and tipText().
QString DccFileTransfer::m_szStatusString private
Referenced by abort(), connected(), connectionInProgress(), DccFileTransfer(), displayPaint(), event(), handleMarshalError(), and startConnection().
KviCString DccFileTransfer::m_szTarget private
QString DccFileTransfer::m_szTransferIdString private
Referenced by DccFileTransfer(), dccMarshalOutputContextString(), and outputAndLog().
QString DccFileTransfer::m_szTransferLog private
Referenced by addToTransferLog(), and tipText().
kvi_time_t DccFileTransfer::m_tTransferEndTime private
Referenced by abort(), DccFileTransfer(), displayPaint(), and event().
kvi_time_t DccFileTransfer::m_tTransferStartTime private
Referenced by connected(), DccFileTransfer(), and displayPaint().
unsigned int DccFileTransfer::m_uMaxBandwidth private
Referenced by bandwidthLimit(), connected(), DccFileTransfer(), and setBandwidthLimit().
quint64 DccFileTransfer::m_uTotalFileSize private
Referenced by DccFileTransfer(), and displayPaint().
The documentation for this class was generated from the following files:
src/modules/dcc/DccFileTransfer.h
src/modules/dcc/DccFileTransfer.cpp