KVIrc: KviToolBar Class Reference
KviToolBar Class Reference
#include <kvi_toolbar.h>
Public Slots
void moveToBottom ()
void moveToLeft ()
void moveToMinimized ()
void moveToRight ()
void moveToTop ()
void moveToTornOff ()
void setBigIcons ()
void setSmallIcons ()
Public Member Functions
KviToolBar (const QString &szLabel, Qt::ToolBarArea type=Qt::TopToolBarArea, bool bNewLine=false, const char *pcName=0)
~KviToolBar ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *e)
void moveTo (Qt::ToolBarArea type)
Constructor & Destructor Documentation
KviToolBar::KviToolBar (const QString & szLabel, Qt::ToolBarArea type = Qt::TopToolBarArea, bool bNewLine = false, const char * pcName = 0)
KviToolBar::~KviToolBar ()
Member Function Documentation
void KviToolBar::mousePressEvent (QMouseEvent * e) [protected, virtual]
Reimplemented in KviCustomToolBar.
References __tr2qs, KviTalPopupMenu::clear(), KviFrame::fillToolBarsPopup(), g_pFrame, KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), moveToBottom(), moveToLeft(), moveToMinimized(), moveToRight(), moveToTop(), moveToTornOff(), setBigIcons(), and setSmallIcons().
void KviToolBar::moveTo (Qt::ToolBarArea type) [protected]
References g_pFrame.
Referenced by moveToBottom(), moveToLeft(), moveToMinimized(), moveToRight(), moveToTop(), and moveToTornOff().
void KviToolBar::moveToBottom () [slot]
References moveTo().
Referenced by mousePressEvent().
void KviToolBar::moveToLeft () [slot]
References moveTo().
Referenced by mousePressEvent().
void KviToolBar::moveToMinimized () [slot]
References moveTo(), and QT_TOOLBAR_MINIMIZED.
Referenced by mousePressEvent().
void KviToolBar::moveToRight () [slot]
References moveTo().
Referenced by mousePressEvent().
void KviToolBar::moveToTop () [slot]
References moveTo().
Referenced by mousePressEvent().
void KviToolBar::moveToTornOff () [slot]
References moveTo(), and QT_TOOLBAR_TORNOFF.
Referenced by mousePressEvent().
void KviToolBar::setBigIcons () [slot]
References g_pFrame, and KviTalMainWindow::setUsesBigPixmaps().
Referenced by mousePressEvent().
void KviToolBar::setSmallIcons () [slot]
References g_pFrame, and KviTalMainWindow::setUsesBigPixmaps().
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_toolbar.h
src/kvirc/ui/kvi_toolbar.cpp