KVIrc: KviIdentityGeneralOptionsWidget Class Reference
KviIdentityGeneralOptionsWidget Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
KviIdentityGeneralOptionsWidget (QWidget *pParent)
~KviIdentityGeneralOptionsWidget ()
Protected Slots
void setNickAlternatives ()
Protected Member Functions
virtual void commit ()
Protected Attributes
QComboBox * m_pAgeCombo
QComboBox * m_pGenderCombo
QString m_szAltNicknames [3]
Constructor & Destructor Documentation
KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget (QWidget * pParent)
References __tr2qs_ctx(), KviTalToolTip::add(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), connect(), KviOptionsWidget::createLayout(), KviQString::equalCI(), i, KVI_OPTION_STRING, KviOption_stringCtcpUserInfoAge, KviOption_stringCtcpUserInfoGender, KviOption_stringCtcpUserInfoLanguages, KviOption_stringCtcpUserInfoLocation, KviOption_stringCtcpUserInfoOther, KviOption_stringNickname1, KviOption_stringNickname2, KviOption_stringNickname3, KviOption_stringNickname4, KviOption_stringRealname, KviOption_stringUsername, l, KviOptionsWidget::layout(), m_pAgeCombo, m_pGenderCombo, m_szAltNicknames, KviOptionsWidget::mergeTip(), KviTalHBox::setMargin(), KviStringSelector::setMinimumLabelWidth(), setNickAlternatives(), KviTalHBox::setSpacing(), KviTalHBox::setStretchFactor(), KviStringSelector::setValidator(), and v.
KviIdentityGeneralOptionsWidget::~KviIdentityGeneralOptionsWidget ()
Member Function Documentation
void KviIdentityGeneralOptionsWidget::commit (void) [protected, virtual]
Reimplemented from KviOptionsWidget.
References i, KVI_DEFAULT_REALNAME, KVI_DEFAULT_USERNAME, KVI_OPTION_STRING, KviOption_stringCtcpUserInfoAge, KviOption_stringCtcpUserInfoGender, KviOption_stringNickname2, KviOption_stringNickname3, KviOption_stringNickname4, KviOption_stringRealname, KviOption_stringUsername, m_pAgeCombo, m_pGenderCombo, and m_szAltNicknames.
void KviIdentityGeneralOptionsWidget::setNickAlternatives () [protected, slot]
References NickAlternativesDialog::fill(), and m_szAltNicknames.
Referenced by KviIdentityGeneralOptionsWidget().
Member Data Documentation
QComboBox* KviIdentityGeneralOptionsWidget::m_pAgeCombo [protected]
Referenced by commit(), and KviIdentityGeneralOptionsWidget().
QComboBox* KviIdentityGeneralOptionsWidget::m_pGenderCombo [protected]
Referenced by commit(), and KviIdentityGeneralOptionsWidget().
QString KviIdentityGeneralOptionsWidget::m_szAltNicknames[3] [protected]
Referenced by commit(), KviIdentityGeneralOptionsWidget(), and setNickAlternatives().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp