KVIrc: KviKvsObjectStandardTrueReturnFunctionHandler Class Reference
KviKvsObjectStandardTrueReturnFunctionHandler Class Reference
#include <kvi_kvs_object_functionhandlerimpl.h>
Public Member Functions
virtual ~KviKvsObjectStandardTrueReturnFunctionHandler ()
Protected Member Functions
virtual bool call (KviKvsObject *pObject, KviKvsObjectFunctionCall *pCall)
virtual
KviKvsObjectFunctionHandler * clone ()
KviKvsObjectStandardTrueReturnFunctionHandler ()
Friends
class KviKvsObject
class KviKvsObjectClass
Constructor & Destructor Documentation
KviKvsObjectStandardTrueReturnFunctionHandler::KviKvsObjectStandardTrueReturnFunctionHandler () [inline, protected]
Referenced by clone().
virtual KviKvsObjectStandardTrueReturnFunctionHandler::~KviKvsObjectStandardTrueReturnFunctionHandler () [inline, virtual]
Member Function Documentation
bool KviKvsObjectStandardTrueReturnFunctionHandler::call (KviKvsObject * pObject, KviKvsObjectFunctionCall * pCall) [protected, virtual]
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
KviKvsObjectFunctionHandler * KviKvsObjectStandardTrueReturnFunctionHandler::clone () [protected, virtual]
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectStandardTrueReturnFunctionHandler().
Friends And Related Function Documentation
friend class KviKvsObject [friend]
Reimplemented from KviKvsObjectFunctionHandler.
friend class KviKvsObjectClass [friend]
Reimplemented from KviKvsObjectFunctionHandler.
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_object_functionhandlerimpl.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_object_functionhandlerimpl.cpp