KVIrc: AliasEditorWindow Class Reference
AliasEditorWindow Class Reference
#include <AliasEditorWindow.h>
Public Member Functions
AliasEditorWindow ()
~AliasEditorWindow ()
Protected Slots
void applyClicked ()
void cancelClicked ()
void okClicked ()
Protected Member Functions
virtual void getConfigGroupName (QString &szName)
virtual void loadProperties (KviConfigurationFile *)
virtual QPixmap * myIconPtr ()
virtual void saveProperties (KviConfigurationFile *)
Protected Attributes
AliasEditorWidget * m_pEditor
Constructor & Destructor Documentation
AliasEditorWindow::AliasEditorWindow ()
References __tr2qs_ctx(), KviIconManager::Accept, applyClicked(), cancelClicked(), connect(), KviIconManager::Discard, g, g_pIconManager, KviIconManager::getSmallIcon(), m_pEditor, okClicked(), and KviWindow::setFixedCaption().
AliasEditorWindow::~AliasEditorWindow ()
Member Function Documentation
void AliasEditorWindow::applyClicked () [protected, slot]
References AliasEditorWidget::commit(), and m_pEditor.
Referenced by AliasEditorWindow().
void AliasEditorWindow::cancelClicked () [protected, slot]
Referenced by AliasEditorWindow().
void AliasEditorWindow::getConfigGroupName (QString & szName) [protected, virtual]
Reimplemented from KviWindow.
void AliasEditorWindow::loadProperties (KviConfigurationFile * cfg) [protected, virtual]
Reimplemented from KviWindow.
References AliasEditorWidget::loadProperties(), and m_pEditor.
QPixmap * AliasEditorWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References KviIconManager::Alias, g_pIconManager, and KviIconManager::getSmallIcon().
void AliasEditorWindow::okClicked () [protected, slot]
References AliasEditorWidget::commit(), and m_pEditor.
Referenced by AliasEditorWindow().
void AliasEditorWindow::saveProperties (KviConfigurationFile * cfg) [protected, virtual]
Reimplemented from KviWindow.
References m_pEditor, and AliasEditorWidget::saveProperties().
Member Data Documentation
AliasEditorWidget* AliasEditorWindow::m_pEditor [protected]
Referenced by AliasEditorWindow(), applyClicked(), loadProperties(), okClicked(), and saveProperties().
The documentation for this class was generated from the following files:
src/modules/aliaseditor/AliasEditorWindow.h
src/modules/aliaseditor/AliasEditorWindow.cpp