KVIrc: KviBoolSelector Class Reference
KviBoolSelector Class Reference
#include <KviSelectors.h>
Public Slots
void setEnabled (bool bEnabled)
void setNotEnabled (bool bNotEnabled)
Public Member Functions
virtual void commit ()
KviBoolSelector (QWidget *par, const QString &txt, bool *pOption, bool bEnabled)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviBoolSelector ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual ~KviSelectorInterface ()
Private Attributes
bool * m_pOption
Constructor & Destructor Documentation
KviBoolSelector::KviBoolSelector (QWidget * par, const QString & txt, bool * pOption, bool bEnabled)
References m_pOption, and setEnabled().
KviBoolSelector::~KviBoolSelector () inline
Member Function Documentation
void KviBoolSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pOption.
void KviBoolSelector::setEnabled (bool bEnabled) slot
Referenced by OptionsWidget_identService::enableIpv4InIpv6(), OptionsWidget_ignore::enableVerbose(), KviBoolSelector(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_antispam::reenableStuff(), OptionsWidget_tray::setEnabled(), and setNotEnabled().
void KviBoolSelector::setNotEnabled (bool bNotEnabled) slot
References setEnabled().
QString KviBoolSelector::textForSearch () inline virtual
Reimplemented from KviSelectorInterface.
QWidget* KviBoolSelector::widgetToHighlight () inline virtual
Reimplemented from KviSelectorInterface.
Member Data Documentation
bool* KviBoolSelector::m_pOption private
Referenced by commit(), and KviBoolSelector().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp