KVIrc: DccDialog Class Reference
DccDialog Class Reference
#include <DccDialog.h>
Public Member Functions
DccDialog (DccBroker *br, DccDescriptor *dcc)
virtual void forgetDescriptor ()
virtual ~DccDialog ()
Protected Attributes
DccBroker * m_pBroker
DccDescriptor * m_pDescriptor
Constructor & Destructor Documentation
DccDialog::DccDialog (DccBroker * br, DccDescriptor * dcc)
References m_pBroker, and m_pDescriptor.
DccDialog::~DccDialog () [virtual]
References m_pBroker, m_pDescriptor, and DccBroker::unregisterDccBox().
Member Function Documentation
void DccDialog::forgetDescriptor () [virtual]
References m_pDescriptor.
Referenced by DccBroker::activeVideoExecute(), DccBroker::activeVoiceExecute(), DccBroker::cancelDcc(), DccBroker::chooseSaveFileName(), DccBroker::executeChat(), DccBroker::passiveVideoExecute(), DccBroker::recvFileExecute(), DccBroker::renameDccSendFile(), DccBroker::renameOverwriteResume(), DccBroker::rsendExecute(), and DccBroker::sendFileExecute().
Member Data Documentation
DccBroker* DccDialog::m_pBroker [protected]
Referenced by DccDialog(), and ~DccDialog().
DccDescriptor* DccDialog::m_pDescriptor [protected]
Referenced by DccAcceptDialog::acceptClicked(), DccRenameDialog::cancelClicked(), DccRenameDialog::closeEvent(), DccAcceptDialog::closeEvent(), DccDialog(), forgetDescriptor(), DccRenameDialog::overwriteClicked(), DccAcceptDialog::rejectClicked(), DccRenameDialog::renameClicked(), DccRenameDialog::resumeClicked(), and ~DccDialog().
The documentation for this class was generated from the following files:
src/modules/dcc/DccDialog.h
src/modules/dcc/DccDialog.cpp