KVIrc: OptionsWidget_logging Class Reference
OptionsWidget_logging Class Reference
#include <OptionsWidget_logging.h>
Public Member Functions
OptionsWidget_logging (QWidget *parent)
~OptionsWidget_logging ()
Constructor & Destructor Documentation
OptionsWidget_logging::OptionsWidget_logging (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addDirectorySelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::createLayout(), g, KviOption_boolAutoLogChannels, KviOption_boolAutoLogConsole, KviOption_boolAutoLogDccChat, KviOption_boolAutoLogQueries, KviOption_boolGzipLogs, KviOption_boolStripControlCodesInLogs, KviOption_boolStripMsgTypeInLogs, KviOption_stringLogsDynamicPath, KviOption_stringLogsPath, KviOption_uintAutoFlushLogs, KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and w.
OptionsWidget_logging::~OptionsWidget_logging ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_logging.h
src/modules/options/OptionsWidget_logging.cpp