KVIrc: PopupEditorWindow Class Reference
PopupEditorWindow Class Reference
#include <PopupEditorWindow.h>
Public Member Functions
PopupEditorWindow (KviMainWindow *lpFrm)
~PopupEditorWindow ()
Protected Slots
void applyClicked ()
void cancelClicked ()
void okClicked ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void getConfigGroupName (QString &szName)
virtual void loadProperties (KviConfigurationFile *)
virtual QPixmap * myIconPtr ()
virtual void saveProperties (KviConfigurationFile *)
Protected Attributes
PopupEditorWidget * m_pEditor
Constructor & Destructor Documentation
PopupEditorWindow::PopupEditorWindow (KviMainWindow * lpFrm)
References __tr2qs_ctx(), KviIconManager::Accept, applyClicked(), cancelClicked(), connect(), KviIconManager::Discard, g, g_pIconManager, KviIconManager::getSmallIcon(), m_pEditor, and okClicked().
PopupEditorWindow::~PopupEditorWindow ()
Member Function Documentation
void PopupEditorWindow::applyClicked () [protected, slot]
References PopupEditorWidget::commit(), and m_pEditor.
Referenced by PopupEditorWindow().
void PopupEditorWindow::cancelClicked () [protected, slot]
Referenced by PopupEditorWindow().
void PopupEditorWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void PopupEditorWindow::getConfigGroupName (QString & szName) [protected, virtual]
Reimplemented from KviWindow.
void PopupEditorWindow::loadProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
QPixmap * PopupEditorWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::Popup.
void PopupEditorWindow::okClicked () [protected, slot]
References PopupEditorWidget::commit(), and m_pEditor.
Referenced by PopupEditorWindow().
void PopupEditorWindow::saveProperties (KviConfigurationFile *) [protected, virtual]
Reimplemented from KviWindow.
Member Data Documentation
PopupEditorWidget* PopupEditorWindow::m_pEditor [protected]
Referenced by applyClicked(), okClicked(), and PopupEditorWindow().
The documentation for this class was generated from the following files:
src/modules/popupeditor/PopupEditorWindow.h
src/modules/popupeditor/PopupEditorWindow.cpp