KVIrc: KviKvsTreeNodeCompositeData Class Reference
KviKvsTreeNodeCompositeData Class Reference
#include <KviKvsTreeNodeCompositeData.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeCompositeData (const QChar *pLocation, KviPointerList< KviKvsTreeNodeData > *pSubData)
~KviKvsTreeNodeCompositeData ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviPointerList
< KviKvsTreeNodeData > * m_pSubData
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeCompositeData::KviKvsTreeNodeCompositeData (const QChar * pLocation, KviPointerList< KviKvsTreeNodeData > * pSubData)
References KviPointerList< T >::count(), d, KviPointerList< T >::first(), m_pSubData, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
KviKvsTreeNodeCompositeData::~KviKvsTreeNodeCompositeData ()
References m_pSubData.
Member Function Documentation
void KviKvsTreeNodeCompositeData::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeCompositeData::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviPointerList< T >::first(), m_pSubData, KviPointerList< T >::next(), and p.
bool KviKvsTreeNodeCompositeData::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::appendAsString(), KviPointerListIterator< T >::current(), d, m_pSubData, and KviKvsVariant::setString().
Member Data Documentation
KviPointerList<KviKvsTreeNodeData>* KviKvsTreeNodeCompositeData::m_pSubData protected
Referenced by dump(), evaluateReadOnly(), KviKvsTreeNodeCompositeData(), and ~KviKvsTreeNodeCompositeData().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeCompositeData.h
src/kvirc/kvs/tree/KviKvsTreeNodeCompositeData.cpp