KVIrc: KviInput Class Reference
KviInput Class Reference
Input handling class.
#include <KviInput.h>
Public Slots
void historyButtonClicked ()
Shows the history popup.
void iconButtonClicked ()
Shows the icon popup.
void inputEditorEnterPressed ()
Parses the text written and clears the input line.
void multiLineEditorButtonToggled (bool bOn)
Toggles the multiline editor.
void toggleToolButtons ()
Toggles the buttons.
Public Member Functions
void applyOptions ()
Saves and applies the options.
KviInputEditor * editor ()
Return the instance of the input editor.
int heightHint () const
Returns the height of the input line.
KviInputHistory * history ()
Return the instance of the input history.
void insertChar (char c)
Inserts the given character.
void insertText (const QString &szText)
Inserts the given text.
bool isButtonsHidden ()
Returns true if the buttons on the right are hidden.
bool isUserFriendly ()
Returns true if the input line is in user-friendly mode.
KviInput (KviWindow *pPar, KviUserListView *pView=0)
Constructs the input object.
void multiLinePaste (const QString &szText)
Opens the multiline editor and pastes the given text.
void setButtonsHidden (bool bHidden)
Sets the hidden status of the button on the right.
virtual void setFocus ()
Sets the focus to the input line.
void setText (const QString &szText)
Sets the given text.
void setUserFriendly (bool bSet)
Sets the user-friendly mode to the input line.
QString text ()
Returns the text written in the input line.
~KviInput ()
Destroys the input object.
Public Attributes
KviTalHBox * m_pButtonContainer
QToolButton * m_pCommandlineModeButton
QLabel * m_pHelpLabel
QToolButton * m_pHideToolsButton
QToolButton * m_pHistoryButton
QToolButton * m_pIconButton
KviInputEditor * m_pInputEditor
QGridLayout * m_pLayout
QToolButton * m_pMultiEditorButton
KviScriptEditor * m_pMultiLineEditor
KviWindow * m_pWindow
Protected Member Functions
virtual void focusInEvent (QFocusEvent *e)
void installShortcuts ()
virtual void keyPressEvent (QKeyEvent *e)
virtual void setFocusProxy (QWidget *w)
Private Slots
void toggleMultiLine ()
Toggles multiline.
Detailed Description
Input handling class.
Constructor & Destructor Documentation
KviInput::KviInput (KviWindow * pPar, KviUserListView * pView = 0)
Constructs the input object.
Parameters:
pPar The parent window
pView The userlist
Returns:
KviInput
References __tr2qs, KviTalToolTip::add(), KviIconManager::BigGrin, connect(), g_pIconManager, KviIconManager::getBigIcon(), KviIconManager::getSmallIcon(), historyButtonClicked(), iconButtonClicked(), inputEditorEnterPressed(), installShortcuts(), KVI_OPTION_BOOL, KviOption_boolCommandlineInUserFriendlyModeByDefault, KviOption_boolEnableInputHistory, m_pButtonContainer, m_pCommandlineModeButton, m_pHideToolsButton, m_pHistoryButton, m_pIconButton, m_pInputEditor, m_pLayout, m_pMultiEditorButton, m_pMultiLineEditor, m_pWindow, multiLineEditorButtonToggled(), Normal, KviIconManager::QuitSplit, KviIconManager::SayKvs, KviIconManager::SaySmile, KviTalHBox::setMargin(), KviTalHBox::setSpacing(), KviIconManager::Terminal, KviIconManager::Time, and toggleToolButtons().
KviInput::~KviInput ()
Destroys the input object.
References KviScriptEditor::destroyInstance(), and m_pMultiLineEditor.
Member Function Documentation
void KviInput::applyOptions ()
Saves and applies the options.
Returns:
void
References __tr2qs, KviTalToolTip::add(), KviInputEditor::applyOptions(), connect(), g_pIconManager, KviIconManager::getSmallIcon(), historyButtonClicked(), KVI_OPTION_BOOL, KviOption_boolEnableInputHistory, m_pHistoryButton, m_pInputEditor, KviIconManager::QuitSplit, and KviIconManager::Time.
Referenced by KviWindow::applyOptions(), and KviConsoleWindow::applyOptions().
KviInputEditor* KviInput::editor () [inline]
Return the instance of the input editor.
Returns:
KviInputEditor *
void KviInput::focusInEvent (QFocusEvent * e) [protected, virtual]
References m_pInputEditor, and m_pMultiLineEditor.
int KviInput::heightHint () const
Returns the height of the input line.
Returns:
int
References KviInputEditor::heightHint(), m_pInputEditor, and m_pMultiLineEditor.
Referenced by UserWindow::resizeEvent(), DccVideoWindow::resizeEvent(), DccChatWindow::resizeEvent(), KviQueryWindow::resizeEvent(), KviDebugWindow::resizeEvent(), KviConsoleWindow::resizeEvent(), KviChannelWindow::resizeEvent(), DccChatWindow::sizeHint(), KviQueryWindow::sizeHint(), KviDebugWindow::sizeHint(), KviConsoleWindow::sizeHint(), and KviChannelWindow::sizeHint().
KviInputHistory* KviInput::history () [inline]
Return the instance of the input history.
Returns:
KviInputHistory *
References KviInputHistory::instance().
void KviInput::historyButtonClicked () [slot]
Shows the history popup.
Returns:
void
References KVI_HISTORY_WIN_HEIGHT, and KviHistoryWindowWidget::popup().
Referenced by applyOptions(), and KviInput().
void KviInput::iconButtonClicked () [slot]
Shows the icon popup.
Returns:
void
References m_pIconButton, and KviTextIconWindow::popup().
Referenced by KviInput().
void KviInput::inputEditorEnterPressed () [slot]
Parses the text written and clears the input line.
Returns:
void
References KviInputEditor::clearUndoStack(), m_pCommandlineModeButton, m_pInputEditor, m_pWindow, KviIrcUrl::parse(), KviInputEditor::setText(), and KviInputEditor::text().
Referenced by KviInput().
void KviInput::insertChar (char c)
Inserts the given character.
Parameters:
c The character to insert
Returns:
void
References KviInputEditor::insertChar(), and m_pInputEditor.
void KviInput::insertText (const QString & szText)
Inserts the given text.
Parameters:
szText The text to insert
Returns:
void
References KviInputEditor::insertText(), and m_pInputEditor.
Referenced by window_kvs_cmd_insertInInputText().
void KviInput::installShortcuts () [protected]
References KviShortcut::create(), KVI_SHORTCUTS_INPUT_MULTILINE, KVI_SHORTCUTS_INPUT_MULTILINE_2, and toggleMultiLine().
Referenced by KviInput().
bool KviInput::isButtonsHidden ()
Returns true if the buttons on the right are hidden.
Returns:
bool
References m_pButtonContainer.
Referenced by KviWindow::saveProperties(), and toggleToolButtons().
bool KviInput::isUserFriendly () [inline]
Returns true if the input line is in user-friendly mode.
Returns:
bool
Referenced by KviWindow::saveProperties().
void KviInput::keyPressEvent (QKeyEvent * e) [protected, virtual]
References __tr2qs, KviScriptEditor::getText(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolWarnAboutPastingMultipleLines, KviOption_uintSpacesToExpandTabulationInput, m_pCommandlineModeButton, m_pMultiLineEditor, m_pWindow, KviIrcUrl::parse(), and KviScriptEditor::setText().
void KviInput::multiLineEditorButtonToggled (bool bOn) [slot]
Toggles the multiline editor.
Parameters:
bOn Whether to activate the multiline editor
Returns:
void
References __tr2qs, KviWindow::childrenTreeChanged(), KviScriptEditor::createInstance(), KviScriptEditor::destroyInstance(), KviScriptEditor::getText(), KVI_OPTION_UINT, KviOption_uintSpacesToExpandTabulationInput, m_pHelpLabel, m_pInputEditor, m_pLayout, m_pMultiEditorButton, m_pMultiLineEditor, m_pWindow, KviScriptEditor::setText(), KviInputEditor::setText(), and KviInputEditor::text().
Referenced by KviInput(), multiLinePaste(), and toggleMultiLine().
void KviInput::multiLinePaste (const QString & szText)
Opens the multiline editor and pastes the given text.
Parameters:
szText The text to paste
Returns:
void
References m_pInputEditor, m_pMultiLineEditor, multiLineEditorButtonToggled(), KviScriptEditor::setText(), and KviInputEditor::text().
void KviInput::setButtonsHidden (bool bHidden)
Sets the hidden status of the button on the right.
Parameters:
bHidden Whether to hide the buttons
Returns:
void
References g_pIconManager, KviIconManager::getBigIcon(), m_pButtonContainer, and m_pHideToolsButton.
Referenced by KviWindow::loadProperties(), and toggleToolButtons().
void KviInput::setFocus () [virtual]
Sets the focus to the input line.
Returns:
void
References m_pInputEditor, and m_pMultiLineEditor.
Referenced by KviHistoryWindow::doHide(), KviConsoleWindow::ircUriChanged(), KviIrcView::mousePressEvent(), and KviIrcViewToolWidget::~KviIrcViewToolWidget().
void KviInput::setFocusProxy (QWidget * w) [protected, virtual]
void KviInput::setText (const QString & szText)
Sets the given text.
Parameters:
szText The text to set in the input line
Returns:
void
References m_pInputEditor, m_pMultiLineEditor, KviInputEditor::setText(), and KviScriptEditor::setText().
Referenced by KviHistoryWindow::itemSelected(), and window_kvs_cmd_setInputText().
void KviInput::setUserFriendly (bool bSet) [inline]
Sets the user-friendly mode to the input line.
Parameters:
bSet Whether to set the user-friendly mode
Returns:
void
Referenced by KviWindow::loadProperties().
QString KviInput::text ()
Returns the text written in the input line.
Returns:
QString
References KviScriptEditor::getText(), m_pInputEditor, m_pMultiLineEditor, and KviInputEditor::text().
void KviInput::toggleMultiLine () [private, slot]
Toggles multiline.
Returns:
void
References m_pMultiLineEditor, and multiLineEditorButtonToggled().
Referenced by installShortcuts().
void KviInput::toggleToolButtons () [slot]
Toggles the buttons.
Returns:
void
References isButtonsHidden(), and setButtonsHidden().
Referenced by KviInput().
Member Data Documentation
KviTalHBox* KviInput::m_pButtonContainer
Referenced by isButtonsHidden(), KviInput(), and setButtonsHidden().
QToolButton* KviInput::m_pCommandlineModeButton
Referenced by inputEditorEnterPressed(), keyPressEvent(), and KviInput().
QLabel* KviInput::m_pHelpLabel
Referenced by multiLineEditorButtonToggled().
QToolButton* KviInput::m_pHideToolsButton
Referenced by KviInput(), and setButtonsHidden().
QToolButton* KviInput::m_pHistoryButton
Referenced by applyOptions(), and KviInput().
QToolButton* KviInput::m_pIconButton
Referenced by iconButtonClicked(), and KviInput().
KviInputEditor* KviInput::m_pInputEditor
Referenced by applyOptions(), focusInEvent(), heightHint(), inputEditorEnterPressed(), insertChar(), insertText(), KviInput(), multiLineEditorButtonToggled(), multiLinePaste(), setFocus(), setText(), and text().
QGridLayout* KviInput::m_pLayout
Referenced by KviInput(), and multiLineEditorButtonToggled().
QToolButton* KviInput::m_pMultiEditorButton
Referenced by KviInput(), and multiLineEditorButtonToggled().
KviScriptEditor* KviInput::m_pMultiLineEditor
Referenced by focusInEvent(), heightHint(), keyPressEvent(), KviInput(), multiLineEditorButtonToggled(), multiLinePaste(), setFocus(), setText(), text(), toggleMultiLine(), and ~KviInput().
KviWindow* KviInput::m_pWindow
Referenced by inputEditorEnterPressed(), keyPressEvent(), KviInput(), and multiLineEditorButtonToggled().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviInput.h
src/kvirc/ui/KviInput.cpp