KVIrc: KviModuleExtensionManager Class Reference
KviModuleExtensionManager Class Reference
#include <KviModuleExtension.h>
Public Member Functions
KviModuleExtension * allocateExtension (const KviCString &szType, const KviCString &szName, KviWindow *pWnd=0, KviPointerHashTable< QString, QVariant > *pParams=0, void *pSpecial=0, const QString &preloadModule=QString())
KviModuleExtension * allocateExtension (const KviCString &szType, int id, KviWindow *pWnd=0, KviPointerHashTable< QString, QVariant > *pParams=0, void *pSpecial=0, const QString &preloadModule=QString())
KviModuleExtensionDescriptor * findExtensionDescriptor (const KviCString &szType, const KviCString &szName)
KviModuleExtensionDescriptorList * getExtensionList (const KviCString &szType)
Static Public Member Functions
static KviModuleExtensionManager * instance ()
Protected Member Functions
KviModuleExtensionManager ()
KviModuleExtensionDescriptor * registerExtension (KviModule *m, const KviCString &szType, const KviCString &szName, const QString &szVisibleName, KviModuleExtensionAllocRoutine r, const QPixmap &icon)
void unregisterExtensionsByModule (KviModule *m)
~KviModuleExtensionManager ()
Protected Attributes
KviPointerHashTable< const
char
*, KviModuleExtensionDescriptorList > * m_pExtensionDict
Private Member Functions
KviModuleExtensionDescriptorList * allocateExtensionGetDescriptorList (const KviCString &szType, const QString &preloadModule)
Friends
class KviApplication
class KviModule
Constructor & Destructor Documentation
KviModuleExtensionManager::KviModuleExtensionManager () [protected]
References m_pExtensionDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviModuleExtensionManager::~KviModuleExtensionManager () [protected]
References m_pExtensionDict.
Member Function Documentation
KviModuleExtension * KviModuleExtensionManager::allocateExtension (const KviCString & szType, const KviCString & szName, KviWindow * pWnd = 0, KviPointerHashTable< QString, QVariant > * pParams = 0, void * pSpecial = 0, const QString & preloadModule = QString())
References KviModuleExtensionDescriptor::allocate(), allocateExtensionGetDescriptorList(), d, KviCString::equalsCI(), KviPointerList< T >::first(), g_pModuleManager, l, KviModuleManager::loadModulesByCaps(), KviModuleExtensionDescriptor::name(), KviPointerList< T >::next(), and KviCString::ptr().
Referenced by KviIrcLink::createSocket(), OptionsWidget_servers::importPopupActivated(), KviMainWindow::restoreModuleExtensionToolBars(), KviMainWindow::toolbarsPopupSelected(), and KviMenuBar::toolsPopupSelected().
KviModuleExtension * KviModuleExtensionManager::allocateExtension (const KviCString & szType, int id, KviWindow * pWnd = 0, KviPointerHashTable< QString, QVariant > * pParams = 0, void * pSpecial = 0, const QString & preloadModule = QString())
References KviModuleExtensionDescriptor::allocate(), allocateExtensionGetDescriptorList(), d, KviPointerList< T >::first(), g_pModuleManager, KviModuleExtensionDescriptor::id(), l, KviModuleManager::loadModulesByCaps(), KviPointerList< T >::next(), and KviCString::ptr().
KviModuleExtensionDescriptorList * KviModuleExtensionManager::allocateExtensionGetDescriptorList (const KviCString & szType, const QString & preloadModule) [private]
References KviPointerHashTable< Key, T >::find(), g_pModuleManager, KviModuleManager::getModule(), l, KviModuleManager::loadModulesByCaps(), m, m_pExtensionDict, and KviCString::ptr().
Referenced by allocateExtension().
KviModuleExtensionDescriptor * KviModuleExtensionManager::findExtensionDescriptor (const KviCString & szType, const KviCString & szName)
References d, KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), l, m_pExtensionDict, KviPointerList< T >::next(), and KviCString::ptr().
Referenced by KviModule::findExtensionDescriptor().
KviModuleExtensionDescriptorList * KviModuleExtensionManager::getExtensionList (const KviCString & szType)
References KviPointerHashTable< Key, T >::find(), g_pModuleManager, KviModuleManager::loadModulesByCaps(), m_pExtensionDict, and KviCString::ptr().
Referenced by KviMainWindow::fillToolBarsPopup(), OptionsWidget_servers::importPopupAboutToShow(), OptionsWidget_servers::importPopupActivated(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviMenuBar::setupToolsPopup().
static KviModuleExtensionManager* KviModuleExtensionManager::instance () [inline, static]
References g_pModuleExtensionManager.
Referenced by OptionsWidget_servers::importPopupAboutToShow(), OptionsWidget_servers::importPopupActivated(), and IrcServerDetailsWidget::IrcServerDetailsWidget().
KviModuleExtensionDescriptor * KviModuleExtensionManager::registerExtension (KviModule * m, const KviCString & szType, const KviCString & szName, const QString & szVisibleName, KviModuleExtensionAllocRoutine r, const QPixmap & icon) [protected]
References KviPointerList< T >::append(), d, KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), l, m_pExtensionDict, KviCString::ptr(), and KviPointerList< T >::setAutoDelete().
Referenced by KviModule::registerExtension().
void KviModuleExtensionManager::unregisterExtensionsByModule (KviModule * m) [protected]
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, KviPointerList< T >::first(), l, m, m_pExtensionDict, KviPointerList< T >::next(), KviPointerHashTable< Key, T >::remove(), and KviPointerList< T >::setAutoDelete().
Referenced by KviModule::unregisterAllExtensions().
Friends And Related Function Documentation
friend class KviApplication [friend]
friend class KviModule [friend]
Member Data Documentation
KviPointerHashTable<const char *,KviModuleExtensionDescriptorList>* KviModuleExtensionManager::m_pExtensionDict [protected]
Referenced by allocateExtensionGetDescriptorList(), findExtensionDescriptor(), getExtensionList(), KviModuleExtensionManager(), registerExtension(), unregisterExtensionsByModule(), and ~KviModuleExtensionManager().
The documentation for this class was generated from the following files:
src/kvirc/module/KviModuleExtension.h
src/kvirc/module/KviModuleExtension.cpp