KVIrc: RawHandlerTreeWidgetItem Class Reference
RawHandlerTreeWidgetItem Class Reference
#include <RawEditorWindow.h>
Public Member Functions
RawHandlerTreeWidgetItem (QTreeWidgetItem *par, const QString &name, const QString &buffer, bool bEnabled)
void setEnabled (bool bEnabled)
void setName (const QString &szName)
~RawHandlerTreeWidgetItem ()
Public Attributes
bool m_bEnabled
QString m_szBuffer
Constructor & Destructor Documentation
RawHandlerTreeWidgetItem::RawHandlerTreeWidgetItem (QTreeWidgetItem * par, const QString & name, const QString & buffer, bool bEnabled) inline
References setEnabled().
RawHandlerTreeWidgetItem::~RawHandlerTreeWidgetItem () inline
Member Function Documentation
void RawHandlerTreeWidgetItem::setEnabled (bool bEnabled) inline
References g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Handler, and KviIconManager::HandlerDisabled.
Referenced by RawHandlerTreeWidgetItem(), and RawEditorWidget::toggleCurrentHandlerEnabled().
void RawHandlerTreeWidgetItem::setName (const QString & szName)
Referenced by RawEditorWidget::saveLastEditedItem().
Member Data Documentation
bool RawHandlerTreeWidgetItem::m_bEnabled
Referenced by RawEditorWidget::getExportEventBuffer(), and RawEditorWidget::toggleCurrentHandlerEnabled().
QString RawHandlerTreeWidgetItem::m_szBuffer
Referenced by RawEditorWidget::getExportEventBuffer(), and RawEditorWidget::saveLastEditedItem().
The documentation for this class was generated from the following files:
src/modules/raweditor/RawEditorWindow.h
src/modules/raweditor/RawEditorWindow.cpp