KVIrc: KviKvsTreeNodeExpressionBinaryOperator Class Reference
KviKvsTreeNodeExpressionBinaryOperator Class Reference
#include <KviKvsTreeNodeExpression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
void dumpOperands (const char *prefix)
virtual int firstBinaryOperator ()
KviKvsTreeNodeExpressionBinaryOperator (const QChar *pLocation)
virtual KviKvsTreeNodeExpression * left ()
virtual KviKvsTreeNodeExpression * right ()
void setLeft (KviKvsTreeNodeExpression *pLeft)
void setRight (KviKvsTreeNodeExpression *pRight)
~KviKvsTreeNodeExpressionBinaryOperator ()
Public Member Functions inherited from KviKvsTreeNodeExpressionOperator
KviKvsTreeNodeExpressionOperator (const QChar *pLocation)
~KviKvsTreeNodeExpressionOperator ()
Public Member Functions inherited from KviKvsTreeNodeExpression
KviKvsTreeNodeExpression (const QChar *pLocation)
KviKvsTreeNodeExpression * parentExpression ()
virtual KviKvsTreeNodeExpression * parentWithPrecedenceLowerThan (int iPrec)
virtual int precedence ()
void setParentExpression (KviKvsTreeNodeExpression *pParent)
~KviKvsTreeNodeExpression ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Member Functions
bool evaluateOperands (KviKvsRunTimeContext *c)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes
KviKvsNumber m_nLeft
KviKvsNumber m_nRight
KviKvsTreeNodeExpression * m_pLeft
KviKvsTreeNodeExpression * m_pRight
Protected Attributes inherited from KviKvsTreeNodeExpression
KviKvsTreeNodeExpression * m_pParentExpression
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionBinaryOperator::KviKvsTreeNodeExpressionBinaryOperator (const QChar * pLocation)
References m_pLeft, and m_pRight.
KviKvsTreeNodeExpressionBinaryOperator::~KviKvsTreeNodeExpressionBinaryOperator ()
References m_pLeft, and m_pRight.
Member Function Documentation
void KviKvsTreeNodeExpressionBinaryOperator::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeExpressionOperator.
void KviKvsTreeNodeExpressionBinaryOperator::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeExpressionOperator.
References dumpOperands().
void KviKvsTreeNodeExpressionBinaryOperator::dumpOperands (const char * prefix)
References KviKvsTreeNodeExpression::dump(), m_pLeft, and m_pRight.
Referenced by dump().
bool KviKvsTreeNodeExpressionBinaryOperator::evaluateOperands (KviKvsRunTimeContext * c) protected
References __tr2qs_ctx(), KviKvsVariant::asNumber(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), m_nLeft, m_nRight, m_pLeft, and m_pRight.
int KviKvsTreeNodeExpressionBinaryOperator::firstBinaryOperator () virtual
Reimplemented from KviKvsTreeNodeExpression.
References KviKvsTreeNodeExpression::precedence().
KviKvsTreeNodeExpression * KviKvsTreeNodeExpressionBinaryOperator::left () virtual
Reimplemented from KviKvsTreeNodeExpression.
References m_pLeft.
KviKvsTreeNodeExpression * KviKvsTreeNodeExpressionBinaryOperator::right () virtual
Reimplemented from KviKvsTreeNodeExpression.
References m_pRight.
void KviKvsTreeNodeExpressionBinaryOperator::setLeft (KviKvsTreeNodeExpression * pLeft) virtual
Reimplemented from KviKvsTreeNodeExpression.
References m_pLeft, KviKvsTreeNode::setParent(), and KviKvsTreeNodeExpression::setParentExpression().
void KviKvsTreeNodeExpressionBinaryOperator::setRight (KviKvsTreeNodeExpression * pRight) virtual
Reimplemented from KviKvsTreeNodeExpression.
References m_pRight, KviKvsTreeNode::setParent(), and KviKvsTreeNodeExpression::setParentExpression().
Member Data Documentation
KviKvsNumber KviKvsTreeNodeExpressionBinaryOperator::m_nLeft protected
Referenced by evaluateOperands().
KviKvsNumber KviKvsTreeNodeExpressionBinaryOperator::m_nRight protected
Referenced by evaluateOperands().
KviKvsTreeNodeExpression* KviKvsTreeNodeExpressionBinaryOperator::m_pLeft protected
Referenced by dumpOperands(), evaluateOperands(), KviKvsTreeNodeExpressionBinaryOperator(), left(), setLeft(), and ~KviKvsTreeNodeExpressionBinaryOperator().
KviKvsTreeNodeExpression* KviKvsTreeNodeExpressionBinaryOperator::m_pRight protected
Referenced by dumpOperands(), evaluateOperands(), KviKvsTreeNodeExpressionBinaryOperator(), right(), setRight(), and ~KviKvsTreeNodeExpressionBinaryOperator().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.h
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.cpp