KVIrc: KviIconManager Class Reference
KviIconManager Class Reference
This class manages the images used by KVIrc.
#include <KviIconManager.h>
Public Types
enum SmallIcon {
None = 0, Close = 1, Maximize = 2, Minimize = 3,
Restore = 4, DefaultIcon = 5, Dock = 6, UnDock = 7,
QuitApp = 8, Console = 9, Floppy = 10, ParserError = 11,
ParserWarning = 12, Server = 13, World = 14, Proxy = 15,
KVIrc = 16, Cut = 17, Copy = 18, Paste = 19,
Options = 20, SocketMessage = 21, SocketWarning = 22, SocketError = 23,
SystemError = 24, Raw = 25, SystemWarning = 26, SystemMessage = 27,
UnHandled = 28, ServerInfo = 29, Motd = 30, Channel = 31,
HideDoubleView = 32, ShowDoubleView = 33, Op = 34, Voice = 35,
ServerPing = 36, ShowListView = 37, HideListView = 38, Join = 39,
Part = 40, Unrecognized = 41, Topic = 42, Accept = 43,
Discard = 44, OwnPrivMsg = 45, ChanPrivMsg = 46, Query = 47,
QueryPrivMsg = 48, Help = 49, MdiHelp = 50, CtcpReply = 51,
CtcpRequestReplied = 52, CtcpRequestIgnored = 53, CtcpRequestFlood = 54, CtcpRequestUnknown = 55,
Action = 56, Avatar = 57, Quit = 58, Split = 59,
QuitSplit = 60, Nick = 61, DeOp = 62, DeVoice = 63,
Mode = 64, Key = 65, Limit = 66, Ban = 67,
UnBan = 68, BanExcept = 69, BanUnExcept = 70, InviteExcept = 71,
InviteUnExcept = 72, ChanMode = 73, ChanModeHide = 74, Who = 75,
Editor = 76, DccRequest = 77, DccMsg = 78, DccError = 79,
IconManager = 80, ScriptCenter = 81, Bomb = 82, Event = 83,
EventNoHandlers = 84, Handler = 85, HandlerDisabled = 86, NickNameProblem = 87,
WhoisUser = 88, WhoisChannels = 89, WhoisIdle = 90, WhoisServer = 91,
WhoisOther = 92, Time = 93, NotifyOnLine = 94, NotifyOffLine = 95,
Locked = 96, UnLocked = 97, LockedOff = 98, UnLockedOff = 99,
OwnPrivMsgCrypted = 100, ChanPrivMsgCrypted = 101, QueryPrivMsgCrypted = 102, DccChatMsg = 103,
DccChatMsgCrypted = 104, Irc = 105, Folder = 106, Home = 107,
BookMarks = 108, Spy = 109, Kick = 110, Linux = 111,
Links = 112, RegUsers = 113, TrayIcon = 114, CascadeWindows = 115,
MaxVertical = 116, MaxHorizontal = 117, TileWindows = 118, Log = 119,
Spam = 120, File = 121, Icq = 122, IcqYellow = 123,
IcqRed = 124, IcqBlue = 125, IcqLightGreen = 126, IcqLightYellow = 127,
Message = 128, MessageSent = 129, BlueSquare = 130, VioletSquare = 131,
YellowSquare = 132, GreenSquare = 133, BlackSquare = 134, RedSquare = 135,
CyanSquare = 136, DarkGreenSquare = 137, Terminal = 138, WallOps = 139,
Invisible = 140, ServerNotice = 141, Gnutella = 142, Search = 143,
Files = 144, Transfer = 145, Package = 146, Retry = 147,
Idea = 148, Colors = 149, Gui = 150, IrcView = 151,
Alias = 152, ChannelNotice = 153, ChannelNoticeCrypted = 154, QueryNotice = 155,
QueryNoticeCrypted = 156, ServNotice = 157, Popup = 158, Prologue = 159,
Epilogue = 160, SharedFiles = 161, CtcpReplyUnknown = 162, Canvas = 163,
NickServ = 164, ChanServ = 165, DccVoice = 166, Play = 167,
Record = 168, AutoTileWindows = 169, Away = 170, Ident = 171,
HomePage = 172, List = 173, HalfOp = 174, HalfDeOp = 175,
Invite = 176, MultiMedia = 177, Look = 178, Input = 179,
Messages = 180, QueryTrace = 181, NoChannel = 182, BroadcastPrivMsg = 183,
BroadcastNotice = 184, Url = 185, RawEvent = 186, RawEventNoHandlers = 187,
MeKick = 188, MeOp = 189, MeVoice = 190, MeDeOp = 191,
MeDeVoice = 192, MeHalfOp = 193, MeDeHalfOp = 194, MeBan = 195,
MeUnBan = 196, MeBanExcept = 197, MeBanUnExcept = 198, MeInviteExcept = 199,
MeInviteUnExcept = 200, ClassicWindowList = 201, TreeWindowList = 202, Ignore = 203,
UserList = 204, Stats = 205, PopupMenu = 206, Xy = 207,
Irc0 = 208, Irc1 = 209, Irc2 = 210, Irc3 = 211,
Irc4 = 212, Irc5 = 213, Heart = 214, HeartBroken = 215,
Rose = 216, BigGrin = 217, BigGrinGlasses = 218, BigGrinEyes = 219,
TextExclamative = 220, TextPoints = 221, Kiss = 222, Surprised1 = 223,
Ugly = 224, Angry = 225, Surprised2 = 226, Smile = 227,
Tongue = 228, Ssl = 229, Cry = 230, Eye = 231,
DeadChannel = 232, DeadQuery = 233, Sound = 234, ToolBar = 235,
TextEncoding = 236, NewItem = 237, NewItemByWizard = 238, DeleteItem = 239,
EditItem = 240, FileTransfer = 241, ChanAdmin = 242, ChanUnAdmin = 243,
MeChanAdmin = 244, MeChanUnAdmin = 245, UserOp = 246, DeUserOp = 247,
MeUserOp = 248, MeDeUserOp = 249, Applet = 250, Caption = 251,
Transparent = 252, Alert = 253, UserWindow = 254, StatusBar = 255,
NotAway = 256, Plus = 257, Minus = 258, BinaryText = 259,
ChanOwner = 260, ChanUnOwner = 261, MeChanOwner = 262, MeChanUnOwner = 263,
Afraid = 264, Tongue2 = 265, SayIcon = 266, SayColors = 267,
Finger = 268, ScriptAction = 269, TearSmile = 270, Shy = 271,
ServerError = 272, Cafe = 273, Addons = 274, ChanOwnerAway = 275,
OpAway = 276, VoiceAway = 277, ChanAdminAway = 278, UserOpAway = 279,
HalfOpAway = 280, ClassEditor = 281, Demoralized = 282, Slurp = 283,
NameSpace = 284, SaySmile = 285, SayKvs = 286, ThemeOptions = 287,
Bug = 288, Refresh = 289, Theme = 290, ScreenShot = 291,
Update = 292, NotUpdate = 293, FailUpdate = 294, UnreadText = 295,
IrcOp = 296, IrcOpAway = 297, DeIrcOp = 298, MeIrcOp = 299,
MeDeIrcOp = 300, Angel = 301, Clown = 302, Devil = 303,
InLove = 304, Ninja = 305, Pirate = 306, Puke = 307,
Rage = 308, Class = 309, ClassNotBuilt = 310, Function = 311,
SexMale = 312, SexFemale = 313, SexBot = 314, SexIrcOp = 315,
MemoServ = 316, IconCount = 317
}
Contains all KVIrc's small icons.
Public Slots
void showIconWidget ()
Shows the table of icons.
Public Member Functions
void clearCache ()
Clears the cache!
KviAvatar * getAvatar (const QString &szLocalPath, const QString &szName)
Returns the avatar If szLocalPath is empty then szName can be the identification string for the avatar If szName is empty then it is found from szLocalPath.
QPixmap * getBigIcon (const QString &szName)
Returns the big icon.
QPixmap * getImage (const QString &szId, bool bCanBeNumber=true, QString *pRetPath=0)
Returns the image.
QPixmap * getPixmap (const QString &szName)
Returns the pixmap of the image.
KviCachedPixmap * getPixmapWithCache (const QString &szName)
Returns the cached pixmap of the image.
KviCachedPixmap * getPixmapWithCacheScaleOnLoad (const QString &szName, int iMaxWidth, int iMaxHeight)
Returns the cached pixmap of the image and scales it on load.
QPixmap * getSmallIcon (SmallIcon eIcon)
Returns the small icon.
QPixmap * getSmallIcon (int iIcon)
Returns the small icon.
int getSmallIconIdFromName (const QString &szName)
Returns the index of the small icon.
const char * getSmallIconName (SmallIcon eIcon)
Returns the name of the small icon.
const char * getSmallIconName (int iIcon)
Returns the name of the small icon.
QString getSmallIconResourceName (SmallIcon eIcon)
Returns the resource name of the small icon.
SmallIcon iconName (int iIcon)
Returns the name of the small icon.
KviIconManager ()
Creates the icon manager object.
void reloadImages ()
Reloads all images.
void urlToCachedFileName (QString &szName)
Returns the url of the image in cache.
~KviIconManager ()
Destroys the icon manager object.
Protected Slots
void iconWidgetClosed ()
Called when we close the table of icons.
Protected Member Functions
void addToCache (const QString &szName, KviCachedPixmap *pPix)
void initQResourceBackend ()
Initializes the Qt resource backend.
QPixmap * loadSmallIcon (int iIdx)
Returns the icon.
Private Attributes
KviPointerHashTable< QString,
KviCachedPixmap > * m_pCachedImages
KviPointerHashTable< QString,
int > * m_pIconNames
KviIconWidget * m_pIconWidget
QPixmap * m_smallIcons [IconCount]
unsigned int m_uCacheMaxSize
unsigned int m_uCacheTotalSize
Detailed Description
This class manages the images used by KVIrc.
We handle three types of images: builtin small icons, builtin big icons and generic images. The builtin small icons are in the pics/coresmall directory (this is to optimize the directory size since it's a linear search...), are 16x16 in size and are indexed by numbers in a way that their access is really fast. The icons used here are used mostly in KviIrcView (but not exclusively). The builtin big icons are (actually) just generic images that are eventually scaled to 32x32 if needed. One can request a builtin small icon indexed by number to be scaled to the size of 32x32 as a big icon too. The generic images are just "any" image that the underlying Qt engine is able to load. They are loaded by (relative) path and cached by name.
Member Enumeration Documentation
enum KviIconManager::SmallIcon
Contains all KVIrc's small icons.
Enumerator:
None
Close
Maximize
Minimize
Restore
DefaultIcon
Dock
UnDock
QuitApp
Console
Floppy
ParserError
ParserWarning
Server
World
Proxy
KVIrc
Cut
Copy
Paste
Options
SocketMessage
SocketWarning
SocketError
SystemError
Raw
SystemWarning
SystemMessage
UnHandled
ServerInfo
Motd
Channel
HideDoubleView
ShowDoubleView
Op
Voice
ServerPing
ShowListView
HideListView
Join
Part
Unrecognized
Topic
Accept
Discard
OwnPrivMsg
ChanPrivMsg
Query
QueryPrivMsg
MdiHelp
CtcpReply
CtcpRequestReplied
CtcpRequestIgnored
CtcpRequestFlood
CtcpRequestUnknown
Action
Avatar
Quit
Split
QuitSplit
Nick
DeOp
DeVoice
Mode
Key
Limit
Ban
UnBan
BanExcept
BanUnExcept
InviteExcept
InviteUnExcept
ChanMode
ChanModeHide
Who
Editor
DccRequest
DccMsg
DccError
IconManager
ScriptCenter
Bomb
Event
EventNoHandlers
Handler
HandlerDisabled
NickNameProblem
WhoisUser
WhoisChannels
WhoisIdle
WhoisServer
WhoisOther
Time
NotifyOnLine
NotifyOffLine
Locked
UnLocked
LockedOff
UnLockedOff
OwnPrivMsgCrypted
ChanPrivMsgCrypted
QueryPrivMsgCrypted
DccChatMsg
DccChatMsgCrypted
Irc
Folder
Home
BookMarks
Spy
Kick
Linux
Links
RegUsers
TrayIcon
CascadeWindows
MaxVertical
MaxHorizontal
TileWindows
Log
Spam
File
Icq
IcqYellow
IcqRed
IcqBlue
IcqLightGreen
IcqLightYellow
Message
MessageSent
BlueSquare
VioletSquare
YellowSquare
GreenSquare
BlackSquare
RedSquare
CyanSquare
DarkGreenSquare
Terminal
WallOps
Invisible
ServerNotice
Gnutella
Search
Files
Transfer
Package
Retry
Idea
Colors
Gui
IrcView
Alias
ChannelNotice
ChannelNoticeCrypted
QueryNotice
QueryNoticeCrypted
ServNotice
Popup
Prologue
Epilogue
SharedFiles
CtcpReplyUnknown
Canvas
NickServ
ChanServ
DccVoice
Play
Record
AutoTileWindows
Away
Ident
HomePage
List
HalfOp
HalfDeOp
Invite
MultiMedia
Look
Input
Messages
QueryTrace
NoChannel
BroadcastPrivMsg
BroadcastNotice
Url
RawEvent
RawEventNoHandlers
MeKick
MeOp
MeVoice
MeDeOp
MeDeVoice
MeHalfOp
MeDeHalfOp
MeBan
MeUnBan
MeBanExcept
MeBanUnExcept
MeInviteExcept
MeInviteUnExcept
ClassicWindowList
TreeWindowList
Ignore
UserList
Stats
PopupMenu
Xy
Irc0
Irc1
Irc2
Irc3
Irc4
Irc5
Heart
HeartBroken
Rose
BigGrin
BigGrinGlasses
BigGrinEyes
TextExclamative
TextPoints
Kiss
Surprised1
Ugly
Angry
Surprised2
Smile
Tongue
Ssl
Cry
Eye
DeadChannel
DeadQuery
Sound
ToolBar
TextEncoding
NewItem
NewItemByWizard
DeleteItem
EditItem
FileTransfer
ChanAdmin
ChanUnAdmin
MeChanAdmin
MeChanUnAdmin
UserOp
DeUserOp
MeUserOp
MeDeUserOp
Applet
Caption
Transparent
Alert
UserWindow
StatusBar
NotAway
Plus
Minus
BinaryText
ChanOwner
ChanUnOwner
MeChanOwner
MeChanUnOwner
Afraid
Tongue2
SayIcon
SayColors
Finger
ScriptAction
TearSmile
Shy
ServerError
Cafe
Addons
ChanOwnerAway
OpAway
VoiceAway
ChanAdminAway
UserOpAway
HalfOpAway
ClassEditor
Demoralized
Slurp
NameSpace
SaySmile
SayKvs
ThemeOptions
Bug
Refresh
Theme
ScreenShot
Update
NotUpdate
FailUpdate
UnreadText
IrcOp
IrcOpAway
DeIrcOp
MeIrcOp
MeDeIrcOp
Angel
Clown
Devil
InLove
Ninja
Pirate
Puke
Rage
Class
ClassNotBuilt
Function
SexMale
SexFemale
SexBot
SexIrcOp
MemoServ
IconCount
Constructor & Destructor Documentation
KviIconManager::KviIconManager ()
Creates the icon manager object.
Returns:
KviIconManager
References KviApplication::findImage(), g_pActivityMeterPixmap, g_pApp, g_pUserChanStatePixmap, i, IconCount, initQResourceBackend(), KVI_ACTIVITYMETER_IMAGE_NAME, KVI_USERCHANSTATE_IMAGE_NAME, m_pCachedImages, m_pIconNames, m_pIconWidget, m_smallIcons, m_uCacheMaxSize, m_uCacheTotalSize, KviPointerHashTable< Key, T >::setAutoDelete(), and szBuffer.
KviIconManager::~KviIconManager ()
Destroys the icon manager object.
References g_pActivityMeterPixmap, g_pUserChanStatePixmap, i, IconCount, m_pCachedImages, m_pIconNames, m_pIconWidget, and m_smallIcons.
Member Function Documentation
void KviIconManager::addToCache (const QString & szName, KviCachedPixmap * pPix) protected
References KviPointerHashTable< Key, T >::insert(), m_pCachedImages, m_uCacheTotalSize, and KviCachedPixmap::size().
Referenced by getBigIcon(), getPixmapWithCache(), and getPixmapWithCacheScaleOnLoad().
void KviIconManager::clearCache ()
Clears the cache!
Returns:
void
References KviPointerHashTable< Key, T >::clear(), and m_pCachedImages.
Referenced by reloadImages().
KviAvatar * KviIconManager::getAvatar (const QString & szLocalPath, const QString & szName)
Returns the avatar If szLocalPath is empty then szName can be the identification string for the avatar If szName is empty then it is found from szLocalPath.
Parameters:
szLocalPath The local path of the avatar
szName The name of the avatar
Returns:
KviAvatar *
References KviApplication::Avatars, KviQString::equalCIN(), KviFileUtils::extractFileName(), KviFileUtils::fileExists(), g_pApp, KviApplication::getLocalKvircDirectory(), KviAvatar::isValid(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolScaleAvatarsOnLoad, KviOption_uintScaleAvatarsOnLoadHeight, KviOption_uintScaleAvatarsOnLoadWidth, and urlToCachedFileName().
Referenced by avatar_kvs_cmd_set(), KviConsoleWindow::checkDefaultAvatar(), OptionsWidget_identityAvatar::chooseAvatar(), RegisteredUsersDialog::exportClicked(), KviIrcServerParser::parseCtcpReplyAvatar(), KviConsoleWindow::resetAvatarForMatchingUsers(), and KviConsoleWindow::setAvatar().
QPixmap * KviIconManager::getBigIcon (const QString & szName)
Returns the big icon.
Parameters:
szName The icon to get
Note:
This one never fails... if the icon isn't there, then a default 32x32 image is returned
Returns:
QPixmap *
References addToCache(), getPixmap(), getSmallIcon(), IconCount, and KviCachedPixmap::pixmap().
Referenced by ActionEditorTreeWidgetItem::ActionEditorTreeWidgetItem(), KviConnectAction::activeContextStateChanged(), KviGoAwayAction::activeContextStateChanged(), AddonManagementDialog::AddonManagementDialog(), KviConnectAction::addToCustomToolBar(), KviGoAwayAction::addToCustomToolBar(), ThemeManagementDialog::applyCurrentTheme(), DccVoiceWindow::DccVoiceWindow(), KviImageDialog::heartbeat(), HelpWidget::HelpWidget(), HelpWindow::HelpWindow(), KviKvsScriptAddon::icon(), AddonFunctions::installAddonPackage(), ThemeFunctions::installThemePackage(), KviChannelWindow::KviChannelWindow(), KviInput::KviInput(), ListWindow::ListWindow(), PackAddonDialog::PackAddonDialog(), PackThemeDialog::PackThemeDialog(), RegisteredUsersDialogItemDelegate::paint(), KviInput::setButtonsHidden(), ThemeManagementDialog::ThemeManagementDialog(), KviChannelWindow::toggleToolButtons(), and TrashcanLabel::TrashcanLabel().
QPixmap * KviIconManager::getImage (const QString & szId, bool bCanBeNumber = true, QString * pRetPath = 0)
Returns the image.
Parameters:
szId The ID of the image This can be a filename or a number that indicates an internal pixmap. 0 stands for "any"
bCanBeNumber Whether the image is specified by a number, especially for scripts or popups
pRetPath Holds the path of the image
Warning:
Don't store this pointer!
Returns:
QPixmap *
References getPixmapWithCache(), getSmallIcon(), getSmallIconIdFromName(), IconCount, NULL, KviCachedPixmap::path(), and KviCachedPixmap::pixmap().
Referenced by NotifierWindow::addMessage(), KviAction::bigIcon(), SingleActionEditor::displayBigIcon(), SingleActionEditor::displaySmallIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviMainWindow::fillToolBarsPopup(), KviKvsObject::function_setProperty(), CustomToolBarPropertiesDialog::iconSelected(), HttpFileTransfer::init(), DccFileTransfer::init(), KviKvsCallbackMessageBox::KviKvsCallbackMessageBox(), KviKvsCallbackTextInput::KviKvsCallbackTextInput(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), UserWindow::myIconPtr(), PopupTreeWidgetItem::setIcon(), KviAction::smallIcon(), and window_kvs_fnc_open().
QPixmap* KviIconManager::getPixmap (const QString & szName) inline
Returns the pixmap of the image.
Parameters:
szName The name of the image
Warning:
Don't store this pointer! The returned pointer is owned by the icon manager and can be deleted at any time
Returns:
QPixmap *
References KviCachedPixmap::pixmap().
Referenced by OptionsWidget_textIcons::chooseFromFile(), getBigIcon(), KviTextIconManager::load(), NotifierWindowBorder::loadImages(), and KviTextIcon::pixmap().
KviCachedPixmap * KviIconManager::getPixmapWithCache (const QString & szName)
Returns the cached pixmap of the image.
Parameters:
szName The name of the image
Warning:
Don't store this pointer! The returned pointer is owned by the icon manager and can be deleted at any time
Returns:
KviCachedPixmap *
References addToCache(), KviPointerHashTable< Key, T >::find(), KviApplication::findImage(), g_pApp, m_pCachedImages, and KviCachedPixmap::updateLastAccessTime().
Referenced by getImage(), and KviTheme::save().
KviCachedPixmap * KviIconManager::getPixmapWithCacheScaleOnLoad (const QString & szName, int iMaxWidth, int iMaxHeight)
Returns the cached pixmap of the image and scales it on load.
Parameters:
szName The name of the image
iMaxWidth The max width to scale
iMaxHeight The max height to scale
Warning:
Don't store this pointer! The returned pointer is owned by the icon manager and can be deleted at any time
Returns:
KviCachedPixmap *
References addToCache(), KviPointerHashTable< Key, T >::find(), KviApplication::findImage(), g_pApp, m_pCachedImages, and KviCachedPixmap::updateLastAccessTime().
QPixmap* KviIconManager::getSmallIcon (SmallIcon eIcon) inline
Returns the small icon.
Parameters:
eIcon The icon to get
Note:
This one never fails... if the icon isn't there, then a default 16x16 image is returned
Returns:
QPixmap *
Referenced by ActionEditorWindow::ActionEditorWindow(), EventEditor::addHandlerForCurrentEvent(), KviMaskEditor::addMask(), AddonManagementDialog::AddonManagementDialog(), KviGoAwayAction::addToPopupMenu(), AliasEditorTreeWidgetItem::AliasEditorTreeWidgetItem(), AliasEditorWindow::AliasEditorWindow(), KviInput::applyOptions(), ChannelsJoinDialog::ChannelsJoinDialog(), ClassEditorTreeWidgetItem::ClassEditorTreeWidgetItem(), ClassEditorWindow::ClassEditorWindow(), ThemeManagementDialog::contextMenuRequested(), KviTopicWidget::contextPopupAboutToShow(), KviWindow::createToolButton(), OptionsWidget_proxy::customContextMenuRequested(), RawEditorWidget::customContextMenuRequested(), AliasEditorWidget::customContextMenuRequested(), SinglePopupEditor::customContextMenuRequested(), PopupEditorWidget::customContextMenuRequested(), OptionsWidget_servers::customContextMenuRequested(), ClassEditorWidget::customContextMenuRequested(), CustomizeToolBarsDialog::CustomizeToolBarsDialog(), CustomToolBarPropertiesDialog::CustomToolBarPropertiesDialog(), DccAcceptDialog::DccAcceptDialog(), DccRenameDialog::DccRenameDialog(), DccVoiceWindow::DccVoiceWindow(), EventEditorWindow::EventEditorWindow(), KviTrayIconWidget::fillContextPopup(), NotifierWindow::fillContextPopup(), ChannelsJoinDialog::fillListView(), OptionsWidget_proxy::fillProxyList(), KviApplication::fillRecentChannelsPopup(), KviApplication::fillRecentNicknamesPopup(), KviApplication::fillRecentServersPopup(), OptionsWidget_servers::fillServerList(), KviMainWindow::fillToolBarsPopup(), KviMdiManager::fillWindowPopup(), getBigIcon(), getImage(), OptionsInstanceManager::getInstance(), KviImageDialog::heartbeat(), OptionsWidget_servers::importServer(), KviIconWidget::init(), AddonFunctions::installAddonPackage(), ThemeFunctions::installThemePackage(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), OptionsWidget_messageColors::itemChanged(), EventEditor::itemPressed(), KviConsoleWindow::KviConsoleWindow(), KviCtcpPageDialog::KviCtcpPageDialog(), KviDefaultScriptDialog::KviDefaultScriptDialog(), KviFileDialog::KviFileDialog(), KviInput::KviInput(), KviIrcMessageCheckListItem::KviIrcMessageCheckListItem(), KviIrcView::KviIrcView(), KviIrcViewToolWidget::KviIrcViewToolWidget(), KviKvsCallbackTextInput::KviKvsCallbackTextInput(), KviMainWindow::KviMainWindow(), KviMaskEditor::KviMaskEditor(), KviMaskInputDialog::KviMaskInputDialog(), KviModeEditor::KviModeEditor(), KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), KviStatusBarUpdateIndicator::KviStatusBarUpdateIndicator(), KviTrayIconWidget::KviTrayIconWidget(), KviWindowToolPageButton::KviWindowToolPageButton(), LinksWindow::LinksWindow(), ListWindow::ListWindow(), KviTextIconManager::load(), LogListViewItemType::LogListViewItemType(), MenuTreeWidgetItem::MenuTreeWidgetItem(), MessageListWidgetItem::MessageListWidgetItem(), ChannelsJoinDialogTreeWidget::mousePressEvent(), KviInputEditor::mousePressEvent(), SocketSpyWindow::myIconPtr(), UserWindow::myIconPtr(), KviKvsScriptWindowWindow::myIconPtr(), KviDebugWindow::myIconPtr(), CodeTesterWindow::myIconPtr(), KviIOGraphWindow::myIconPtr(), HelpWindow::myIconPtr(), LinksWindow::myIconPtr(), UrlDialog::myIconPtr(), DccChatWindow::myIconPtr(), SharedFilesWindow::myIconPtr(), KviConsoleWindow::myIconPtr(), ListWindow::myIconPtr(), FileTransferWindow::myIconPtr(), LogViewWindow::myIconPtr(), EventEditorWindow::myIconPtr(), DccVoiceWindow::myIconPtr(), RawEditorWindow::myIconPtr(), DccVideoWindow::myIconPtr(), AliasEditorWindow::myIconPtr(), PopupEditorWindow::myIconPtr(), ActionEditorWindow::myIconPtr(), KviQueryWindow::myIconPtr(), KviWindow::myIconPtr(), ClassEditorWindow::myIconPtr(), KviChannelWindow::myIconPtr(), OptionsWidget_messageColors::newIconSelected(), OptionsWidget_servers::newNetwork(), OptionsWidget_proxy::newProxy(), OptionsWidget_servers::newServer(), KviApplication::notifierMessage(), EventEditor::oneTimeSetup(), OptionsDialog::OptionsDialog(), OptionsDialogTreeWidgetItem::OptionsDialogTreeWidgetItem(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_servers::OptionsWidget_servers(), RegisteredUsersDialogItemDelegate::paint(), MessageListWidgetItemDelegate::paint(), KviIrcView::paintEvent(), KviUserListViewArea::paintEvent(), OptionsWidget_servers::pasteServer(), KviTextIcon::pixmap(), KviConnectToServerAction::popupAboutToShow(), KviChangeUserModeAction::popupAboutToShow(), PopupEditorWindow::PopupEditorWindow(), RawEditorWindow::RawEditorWindow(), KviConsoleWindow::recentUrlsChanged(), KviTrayIconWidget::refresh(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), RegisteredUserPropertiesDialog::RegisteredUserPropertiesDialog(), RegisteredUsersDialog::RegisteredUsersDialog(), RegistrationWizard::RegistrationWizard(), EventEditor::removeCurrentHandler(), LogViewWindow::rightButtonClicked(), KviTheme::save(), ScriptEditorImplementation::ScriptEditorImplementation(), StatusBarApplet::selfRegister(), KviStatusBarClock::selfRegister(), KviStatusBarConnectionTimer::selfRegister(), KviStatusBarAwayIndicator::selfRegister(), KviStatusBarLagIndicator::selfRegister(), KviStatusBarUpdateIndicator::selfRegister(), ClassEditorTreeWidgetItem::setClassNotBuilt(), RawTreeWidgetItem::setEnabled(), EventEditorHandlerTreeWidgetItem::setEnabled(), RawHandlerTreeWidgetItem::setEnabled(), AliasEditorTreeWidgetItem::setType(), ClassEditorTreeWidgetItem::setType(), OptionsWidgetContainer::setup(), KviMenuBar::setupHelpPopup(), KviMenuBar::setupMainPopup(), KviMenuBar::setupScriptingPopup(), KviMenuBar::setupSettingsPopup(), KviMenuBar::setupToolsPopup(), SharedFileEditDialog::SharedFileEditDialog(), LinksWindow::showHostPopup(), KviIrcView::showToolsPopup(), KviTopicWidget::switchMode(), ThemeManagementDialog::ThemeManagementDialog(), TipWindow::TipWindow(), KviStatusBarAwayIndicator::updateDisplay(), KviStatusBarUpdateIndicator::updateDisplay(), and KviMenuBar::updateRecentServersPopup().
QPixmap* KviIconManager::getSmallIcon (int iIcon) inline
Returns the small icon.
Parameters:
iIcon The icon to get
Note:
This one never fails... if the icon isn't there, then a default 16x16 image is returned. This is provided for convenience
Returns:
QPixmap *
int KviIconManager::getSmallIconIdFromName (const QString & szName)
Returns the index of the small icon.
Parameters:
szName The name of the icon
Returns:
int
References KviPointerHashTable< Key, T >::find(), g_szIconNames, i, IconCount, m_pIconNames, KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by getImage(), and KviKvsCoreFunctions::KVSCF().
const char * KviIconManager::getSmallIconName (SmallIcon eIcon)
Returns the name of the small icon.
Parameters:
eIcon The icon to get
Returns:
const char *
References g_szIconNames.
Referenced by KviImageDialog::heartbeat(), KviKvsCoreFunctions::KVSCF(), KviApplication::notifierMessage(), and KviTheme::save().
const char * KviIconManager::getSmallIconName (int iIcon)
Returns the name of the small icon.
Parameters:
iIcon The icon to get
Note:
This is provided for convenience
Returns:
const char *
References g_szIconNames.
QString KviIconManager::getSmallIconResourceName (SmallIcon eIcon)
Returns the resource name of the small icon.
Parameters:
eIcon The icon to get
Returns:
QString
References g_szIconNames.
Referenced by KviHtmlGenerator::convertToHtml(), LogViewWindow::createLog(), KviIrcView::doLinkToolTip(), and KviIrcView::doMarkerToolTip().
KviIconManager::SmallIcon KviIconManager::iconName (int iIcon)
Returns the name of the small icon.
Parameters:
iIcon The icon to get
Returns:
KviIconManager::SmallIcon
References Accept, Action, Addons, Afraid, Alert, Alias, Angel, Angry, Applet, AutoTileWindows, Avatar, Away, Ban, BanExcept, BanUnExcept, BigGrin, BigGrinEyes, BigGrinGlasses, BinaryText, BlackSquare, BlueSquare, Bomb, BookMarks, BroadcastNotice, BroadcastPrivMsg, Bug, Cafe, Canvas, Caption, CascadeWindows, ChanAdmin, ChanAdminAway, ChanMode, ChanModeHide, Channel, ChannelNotice, ChannelNoticeCrypted, ChanOwner, ChanOwnerAway, ChanPrivMsg, ChanPrivMsgCrypted, ChanServ, ChanUnAdmin, ChanUnOwner, Class, ClassEditor, ClassicWindowList, ClassNotBuilt, Close, Clown, Colors, Console, Copy, Cry, CtcpReply, CtcpReplyUnknown, CtcpRequestFlood, CtcpRequestIgnored, CtcpRequestReplied, CtcpRequestUnknown, Cut, CyanSquare, DarkGreenSquare, DccChatMsg, DccChatMsgCrypted, DccError, DccMsg, DccRequest, DccVoice, DeadChannel, DeadQuery, DefaultIcon, DeIrcOp, DeleteItem, Demoralized, DeOp, DeUserOp, Devil, DeVoice, Discard, Dock, EditItem, Editor, Epilogue, Event, EventNoHandlers, Eye, FailUpdate, File, Files, FileTransfer, Finger, Floppy, Folder, Function, Gnutella, GreenSquare, Gui, HalfDeOp, HalfOp, HalfOpAway, Handler, HandlerDisabled, Heart, HeartBroken, Help, HideDoubleView, HideListView, Home, HomePage, IconCount, IconManager, Icq, IcqBlue, IcqLightGreen, IcqLightYellow, IcqRed, IcqYellow, Idea, Ident, Ignore, InLove, Input, Invisible, Invite, InviteExcept, InviteUnExcept, Irc, Irc0, Irc1, Irc2, Irc3, Irc4, Irc5, IrcOp, IrcOpAway, IrcView, Join, Key, Kick, Kiss, KVIrc, Limit, Links, Linux, List, Locked, LockedOff, Log, Look, MaxHorizontal, Maximize, MaxVertical, MdiHelp, MeBan, MeBanExcept, MeBanUnExcept, MeChanAdmin, MeChanOwner, MeChanUnAdmin, MeChanUnOwner, MeDeHalfOp, MeDeIrcOp, MeDeOp, MeDeUserOp, MeDeVoice, MeHalfOp, MeInviteExcept, MeInviteUnExcept, MeIrcOp, MeKick, MemoServ, MeOp, Message, Messages, MessageSent, MeUnBan, MeUserOp, MeVoice, Minimize, Minus, Mode, Motd, MultiMedia, NameSpace, NewItem, NewItemByWizard, Nick, NickNameProblem, NickServ, Ninja, NoChannel, None, NotAway, NotifyOffLine, NotifyOnLine, NotUpdate, Op, OpAway, Options, OwnPrivMsg, OwnPrivMsgCrypted, Package, ParserError, ParserWarning, Part, Paste, Pirate, Play, Plus, Popup, PopupMenu, Prologue, Proxy, Puke, Query, QueryNotice, QueryNoticeCrypted, QueryPrivMsg, QueryPrivMsgCrypted, QueryTrace, Quit, QuitApp, QuitSplit, Rage, Raw, RawEvent, RawEventNoHandlers, Record, RedSquare, Refresh, RegUsers, Restore, Retry, Rose, SayColors, SayIcon, SayKvs, SaySmile, ScreenShot, ScriptAction, ScriptCenter, Search, Server, ServerError, ServerInfo, ServerNotice, ServerPing, ServNotice, SexBot, SexFemale, SexIrcOp, SexMale, SharedFiles, ShowDoubleView, ShowListView, Shy, Slurp, Smile, SocketError, SocketMessage, SocketWarning, Sound, Spam, Split, Spy, Ssl, Stats, StatusBar, Surprised1, Surprised2, SystemError, SystemMessage, SystemWarning, TearSmile, Terminal, TextEncoding, TextExclamative, TextPoints, Theme, ThemeOptions, TileWindows, Time, Tongue, Tongue2, ToolBar, Topic, Transfer, Transparent, TrayIcon, TreeWindowList, Ugly, UnBan, UnDock, UnHandled, UnLocked, UnLockedOff, UnreadText, Unrecognized, Update, Url, UserList, UserOp, UserOpAway, UserWindow, VioletSquare, Voice, VoiceAway, WallOps, Who, WhoisChannels, WhoisIdle, WhoisOther, WhoisServer, WhoisUser, World, Xy, and YellowSquare.
Referenced by KviTextIconManager::insert(), KviTextIconManager::load(), and KviTextIcon::setId().
void KviIconManager::iconWidgetClosed () protected slot
Called when we close the table of icons.
Returns:
void
References m_pIconWidget.
Referenced by showIconWidget().
void KviIconManager::initQResourceBackend () protected
Initializes the Qt resource backend.
Returns:
void
References g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviApplication::Pics, and KviApplication::SmallIcons.
Referenced by KviIconManager().
QPixmap * KviIconManager::loadSmallIcon (int iIdx) protected
Returns the icon.
Parameters:
iIdx The ID of the icon
Returns:
QPixmap *
References KviApplication::findSmallIcon(), g_pApp, g_szIconNames, IconCount, KVI_SMALLICONS_PREFIX, m_smallIcons, and szBuffer.
void KviIconManager::reloadImages ()
Reloads all images.
Returns:
void
References clearCache(), i, IconCount, and m_smallIcons.
Referenced by KviApplication::optionResetUpdate().
void KviIconManager::showIconWidget () slot
Shows the table of icons.
Returns:
void
References connect(), iconWidgetClosed(), KviIconWidget, and m_pIconWidget.
void KviIconManager::urlToCachedFileName (QString & szName)
Returns the url of the image in cache.
Parameters:
szName The path of the image
Returns:
void
Referenced by avatar_kvs_cmd_set(), getAvatar(), KviIrcServerParser::parseCtcpReplyAvatar(), and AvatarDownloadDialog::startDownload().
Member Data Documentation
KviPointerHashTable<QString,KviCachedPixmap>* KviIconManager::m_pCachedImages private
Referenced by addToCache(), clearCache(), getPixmapWithCache(), getPixmapWithCacheScaleOnLoad(), KviIconManager(), and ~KviIconManager().
KviPointerHashTable<QString,int>* KviIconManager::m_pIconNames private
Referenced by getSmallIconIdFromName(), KviIconManager(), and ~KviIconManager().
KviIconWidget* KviIconManager::m_pIconWidget private
Referenced by iconWidgetClosed(), KviIconManager(), showIconWidget(), and ~KviIconManager().
QPixmap* KviIconManager::m_smallIcons[IconCount] private
Referenced by KviIconManager(), loadSmallIcon(), reloadImages(), and ~KviIconManager().
unsigned int KviIconManager::m_uCacheMaxSize private
Referenced by KviIconManager().
unsigned int KviIconManager::m_uCacheTotalSize private
Referenced by addToCache(), and KviIconManager().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIconManager.h
src/kvirc/kernel/KviIconManager.cpp