KVIrc: KviKvsModuleCommandCall Class Reference
KviKvsModuleCommandCall Class Reference
#include <KviKvsModuleInterface.h>
Public Member Functions
KviKvsVariant * getSwitch (unsigned short u, const QString &szSwitch)
bool hasSwitch (unsigned short u, const QString &szSwitch)
KviKvsModuleCommandCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams, KviKvsSwitchList *pSwitches)
KviKvsSwitchList * switches ()
KviKvsSwitchList * switchList ()
~KviKvsModuleCommandCall ()
Public Member Functions inherited from KviKvsModuleRunTimeCall
KviKvsModuleRunTimeCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
KviModule * module ()
~KviKvsModuleRunTimeCall ()
Public Member Functions inherited from KviKvsRunTimeCall
KviKvsRunTimeContext * context ()
void enterBlockingSection ()
bool error (const QString &szFmt,...)
KviKvsVariant * firstParam ()
virtual bool getParameterCode (unsigned int uParamIdx, QString &szParamBuffer)
KviKvsRunTimeCall (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool leaveBlockingSection ()
KviKvsVariant * nextParam ()
unsigned int paramCount ()
unsigned int parameterCount ()
KviKvsVariantList * parameterList ()
KviKvsVariantList * params ()
void warning (const QString &szFmt,...)
KviWindow * window ()
virtual ~KviKvsRunTimeCall ()
Protected Attributes
KviKvsSwitchList * m_pSwitchList
Protected Attributes inherited from KviKvsModuleRunTimeCall
KviModule * m_pModule
Protected Attributes inherited from KviKvsRunTimeCall
KviKvsRunTimeContext * m_pContext
KviKvsVariantList * m_pParams
Constructor & Destructor Documentation
KviKvsModuleCommandCall::KviKvsModuleCommandCall (KviModule * pModule, KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams, KviKvsSwitchList * pSwitches) inline
KviKvsModuleCommandCall::~KviKvsModuleCommandCall () inline
Member Function Documentation
KviKvsVariant* KviKvsModuleCommandCall::getSwitch (unsigned short u, const QString & szSwitch) inline
Referenced by notifier_kvs_cmd_message(), and popup_kvs_cmd_show().
bool KviKvsModuleCommandCall::hasSwitch (unsigned short u, const QString & szSwitch) inline
Referenced by addon_kvs_cmd_dialog(), config_kvs_cmd_close(), dialog_kvs_cmd_file(), dialog_kvs_cmd_image(), dialog_kvs_cmd_message(), dialog_kvs_cmd_textinput(), filetransferwindow_kvs_cmd_open(), iograph_module_cmd_open(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), logview_kvs_cmd_open(), notifier_kvs_cmd_hide(), notifier_kvs_cmd_message(), notifier_kvs_cmd_show(), objects_kvs_cmd_killClass(), options_kvs_cmd_dialog(), options_kvs_cmd_edit(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_create(), popup_kvs_cmd_delItem(), popup_kvs_cmd_destroy(), regchan_kvs_cmd_remove(), regchan_kvs_cmd_setProperty(), reguser_kvs_cmd_add(), reguser_kvs_cmd_addmask(), reguser_kvs_cmd_edit(), reguser_kvs_cmd_remove(), reguser_kvs_cmd_setIgnoreEnabled(), reguser_kvs_cmd_setIgnoreFlags(), reguser_kvs_cmd_setproperty(), sharedfileswindow_kvs_cmd_open(), snd_kvs_cmd_play(), spaste_kvs_cmd_stop(), term_kvs_cmd_open(), theme_kvs_cmd_dialog(), toolbareditor_kvs_cmd_open(), window_kvs_cmd_highlight(), window_kvs_cmd_insertInInputText(), window_kvs_cmd_setBackground(), window_kvs_cmd_setCryptEngine(), window_kvs_cmd_setInputText(), and window_kvs_cmd_setWindowTitle().
KviKvsSwitchList* KviKvsModuleCommandCall::switches () inline
Referenced by action_kvs_cmd_create(), action_kvs_cmd_destroy(), action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_trigger(), addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), avatar_kvs_cmd_notify(), context_kvs_cmd_clearQueue(), dcc_kvs_cmd_abort(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_setBandwidthLimit(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_parse_default_parameters(), default_module_kvs_cmd_unload(), dialog_kvs_cmd_textinput(), file_kvs_cmd_copy(), file_kvs_cmd_remove(), file_kvs_cmd_rmdir(), file_kvs_cmd_write(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), help_kvs_cmd_open(), http_kvs_complete_get(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), notifier_kvs_cmd_message(), objects_kvs_cmd_clearObjects(), perl_kvs_cmd_begin(), perl_kvs_cmd_destroy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), python_kvs_cmd_begin(), python_kvs_cmd_destroy(), reguser_kvs_cmd_add(), serverdb_kvs_cmd_addNetwork(), serverdb_kvs_cmd_addServer(), sharedfile_kvs_cmd_add(), system_kvs_cmd_runcmd(), toolbar_kvs_cmd_additem(), toolbar_kvs_cmd_clear(), toolbar_kvs_cmd_create(), toolbar_kvs_cmd_destroy(), toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_removeitem(), toolbar_kvs_cmd_show(), and upnp_kvs_cmd_addPortMapping().
KviKvsSwitchList* KviKvsModuleCommandCall::switchList () inline
Member Data Documentation
KviKvsSwitchList* KviKvsModuleCommandCall::m_pSwitchList protected
The documentation for this class was generated from the following file:
src/kvirc/kvs/KviKvsModuleInterface.h