KVIrc: KviTopicWidget Class Reference
KviTopicWidget Class Reference
#include <KviTopicWidget.h>
Signals
void topicSelected (const QString &szTopic)
Public Member Functions
void applyOptions ()
int dummyRead () const
void insertChar (QChar c)
void insertText (const QString &szText)
KviTopicWidget (QWidget *pParent, KviChannelWindow *pChannel, const char *name)
void reset ()
void setTopic (const QString &szTopic)
void setTopicSetAt (const QString &szSetAt)
void setTopicSetBy (const QString &szSetBy)
virtual QSize sizeHint () const
const QString & topic ()
const QString & topicSetAt ()
const QString & topicSetBy ()
~KviTopicWidget ()
Static Public Member Functions
static void paintColoredText (QPainter *p, QString szText, const QPalette &palette, const QRect &rect)
Protected Slots
void acceptClicked ()
void complete ()
void contextPopupAboutToShow ()
void copy ()
void discardClicked ()
void historyClicked ()
void popDownListBox ()
void switchMode ()
Protected Member Functions
void deactivate ()
virtual bool eventFilter (QObject *o, QEvent *e)
void iconButtonClicked ()
virtual void keyPressEvent (QKeyEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void resizeEvent (QResizeEvent *e)
void updateToolTip ()
Protected Attributes
int m_iCursorPosition
Properties
int TransparencyCapable
Private Member Functions
QChar getSubstituteChar (unsigned short uControlCode)
Private Attributes
QPushButton * m_pAccept
KviTalListWidget * m_pCompletionBox
KviTalPopupMenu * m_pContextPopup
QPushButton * m_pDiscard
QPushButton * m_pHistory
KviInputEditor * m_pInput
QAbstractItemDelegate * m_pItemDelegate
KviChannelWindow * m_pKviChannelWindow
KviThemedLabel * m_pLabel
QString m_szSetAt
QString m_szSetBy
QString m_szTopic
Friends
class KviChannelWindow
class KviTalListWidget
Constructor & Destructor Documentation
KviTopicWidget::KviTopicWidget (QWidget * pParent, KviChannelWindow * pChannel, const char * name)
References applyOptions(), complete(), connect(), KviTalListWidget, m_iCursorPosition, m_pAccept, m_pCompletionBox, m_pContextPopup, m_pDiscard, m_pHistory, m_pInput, m_pItemDelegate, m_pKviChannelWindow, m_pLabel, reset(), and switchMode().
KviTopicWidget::~KviTopicWidget ()
References m_pCompletionBox.
Member Function Documentation
void KviTopicWidget::acceptClicked () [protected, slot]
References deactivate(), KviInputEditor::isReadOnly(), m_pInput, m_szTopic, KviInputEditor::text(), and topicSelected().
Referenced by switchMode().
void KviTopicWidget::applyOptions ()
References KviThemedLabel::applyOptions(), KVI_OPTION_FONT, KviOption_fontLabel, m_pCompletionBox, and m_pLabel.
Referenced by KviChannelWindow::applyOptions(), and KviTopicWidget().
void KviTopicWidget::complete () [protected, slot]
References m_pCompletionBox, m_pInput, popDownListBox(), and KviInputEditor::setText().
Referenced by eventFilter(), and KviTopicWidget().
void KviTopicWidget::contextPopupAboutToShow () [protected, slot]
References __tr2qs, KviTalPopupMenu::clear(), copy(), KviIconManager::Copy, g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), and m_pContextPopup.
Referenced by mousePressEvent().
void KviTopicWidget::copy () [protected, slot]
References c, and m_szTopic.
Referenced by contextPopupAboutToShow().
void KviTopicWidget::deactivate () [protected]
References m_pAccept, m_pDiscard, m_pHistory, m_pInput, m_pKviChannelWindow, m_pLabel, popDownListBox(), and resizeEvent().
Referenced by acceptClicked(), discardClicked(), KviChannelWindow::eventFilter(), and switchMode().
void KviTopicWidget::discardClicked () [protected, slot]
References deactivate().
Referenced by switchMode().
int KviTopicWidget::dummyRead () const [inline]
bool KviTopicWidget::eventFilter (QObject * o, QEvent * e) [protected, virtual]
References complete(), m_pCompletionBox, and popDownListBox().
QChar KviTopicWidget::getSubstituteChar (unsigned short uControlCode) [private]
References KviControlCodes::Bold, KviControlCodes::Icon, KviControlCodes::Reset, KviControlCodes::Reverse, and KviControlCodes::Underline.
void KviTopicWidget::historyClicked () [protected, slot]
References g_pRecentTopicList, m_pCompletionBox, and m_pInput.
Referenced by switchMode().
void KviTopicWidget::iconButtonClicked () [protected]
void KviTopicWidget::insertChar (QChar c)
References insertText().
void KviTopicWidget::insertText (const QString & szText)
References KviInputEditor::insertText(), and m_pInput.
Referenced by insertChar().
void KviTopicWidget::keyPressEvent (QKeyEvent * e) [protected, virtual]
void KviTopicWidget::mousePressEvent (QMouseEvent * e) [protected, virtual]
References connect(), contextPopupAboutToShow(), and m_pContextPopup.
void KviTopicWidget::paintColoredText (QPainter * p, QString szText, const QPalette & palette, const QRect & rect) [static]
References KviControlCodes::Bold, c, g_pTextIconManager, KviControlCodes::getUnicodeColorBytes(), KviControlCodes::Icon, KVI_LABEL_DEF_BACK, KVI_LABEL_DEF_FORE, KVI_OPTION_MIRCCOLOR, KviTextIconManager::lookupTextIcon(), KviControlCodes::NoChange, KviTextIcon::pixmap(), KviCString::ptr(), KviControlCodes::Reset, KviControlCodes::Reverse, and KviControlCodes::Underline.
Referenced by ChannelTreeWidgetItemDelegate::paint(), and KviTopicListBoxItemDelegate::paint().
void KviTopicWidget::popDownListBox () [protected, slot]
References m_pCompletionBox.
Referenced by complete(), deactivate(), and eventFilter().
void KviTopicWidget::reset ()
References __tr2qs, KviTalToolTip::add(), KviHtmlGenerator::convertToHtml(), m_pLabel, m_szSetAt, m_szSetBy, m_szTopic, and KviTalToolTip::remove().
Referenced by KviTopicWidget(), KviChannelWindow::setAliveChan(), and KviChannelWindow::setDeadChan().
void KviTopicWidget::resizeEvent (QResizeEvent * e) [protected, virtual]
References m_pAccept, m_pDiscard, m_pHistory, m_pInput, and m_pLabel.
Referenced by deactivate().
void KviTopicWidget::setTopic (const QString & szTopic)
References KviHtmlGenerator::convertToHtml(), g_pRecentTopicList, KVI_MAX_RECENT_TOPICS, m_pLabel, m_szTopic, topic(), and updateToolTip().
Referenced by KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseNumericNoTopic(), and KviIrcServerParser::parseNumericTopic().
void KviTopicWidget::setTopicSetAt (const QString & szSetAt)
References m_szSetAt, and updateToolTip().
Referenced by KviIrcServerParser::parseLiteralTopic(), and KviIrcServerParser::parseNumericTopicWhoTime().
void KviTopicWidget::setTopicSetBy (const QString & szSetBy)
References m_szSetBy, and updateToolTip().
Referenced by KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseNumericTopic(), and KviIrcServerParser::parseNumericTopicWhoTime().
QSize KviTopicWidget::sizeHint () const [virtual]
References h, KVI_INPUT_MARGIN, KVI_INPUT_PADDING, KVI_INPUT_XTRAPADDING, and w.
Referenced by KviChannelWindow::resizeEvent().
void KviTopicWidget::switchMode () [protected, slot]
References __tr2qs, KviIconManager::Accept, acceptClicked(), KviTalToolTip::add(), connect(), KviWindow::connection(), deactivate(), KviIconManager::Discard, discardClicked(), g_pIconManager, KviChannelWindow::getChannelModeString(), KviIconManager::getSmallIcon(), KviIrcConnectionUserInfo::hasUserMode(), historyClicked(), KviInputEditor::home(), KviChannelWindow::isMeChanAdmin(), KviChannelWindow::isMeChanOwner(), KviChannelWindow::isMeHalfOp(), KviChannelWindow::isMeOp(), m_pAccept, m_pDiscard, m_pHistory, m_pInput, m_pKviChannelWindow, m_pLabel, m_szTopic, KviIrcConnectionServerInfo::maxTopicLen(), KviChannelWindow::plainChannelMode(), KviIrcConnection::serverInfo(), KviInputEditor::setMaxBufferSize(), KviInputEditor::setReadOnly(), KviInputEditor::setText(), KviIconManager::Time, KviIrcConnection::userInfo(), and w.
Referenced by KviTopicWidget().
const QString& KviTopicWidget::topic () [inline]
Referenced by chan_kvs_fnc_topic(), KviIrcView::doLinkToolTip(), and setTopic().
void KviTopicWidget::topicSelected (const QString & szTopic) [signal]
Referenced by acceptClicked().
const QString& KviTopicWidget::topicSetAt () [inline]
Referenced by chan_kvs_fnc_topicsetat().
const QString& KviTopicWidget::topicSetBy () [inline]
Referenced by chan_kvs_fnc_topicsetby().
void KviTopicWidget::updateToolTip () [protected]
References __tr2qs, KviTalToolTip::add(), KviHtmlGenerator::convertToHtml(), END_TABLE_BOLD_ROW, m_szSetAt, m_szSetBy, m_szTopic, KviTalToolTip::remove(), and START_TABLE_BOLD_ROW.
Referenced by setTopic(), setTopicSetAt(), and setTopicSetBy().
Friends And Related Function Documentation
friend class KviChannelWindow [friend]
friend class KviTalListWidget [friend]
Referenced by KviTopicWidget().
Member Data Documentation
int KviTopicWidget::m_iCursorPosition [protected]
Referenced by KviTopicWidget().
QPushButton* KviTopicWidget::m_pAccept [private]
Referenced by deactivate(), KviTopicWidget(), resizeEvent(), and switchMode().
KviTalListWidget* KviTopicWidget::m_pCompletionBox [private]
Referenced by applyOptions(), complete(), eventFilter(), historyClicked(), KviTopicWidget(), popDownListBox(), and ~KviTopicWidget().
KviTalPopupMenu* KviTopicWidget::m_pContextPopup [private]
Referenced by contextPopupAboutToShow(), KviTopicWidget(), and mousePressEvent().
QPushButton* KviTopicWidget::m_pDiscard [private]
Referenced by deactivate(), KviTopicWidget(), resizeEvent(), and switchMode().
QPushButton* KviTopicWidget::m_pHistory [private]
Referenced by deactivate(), KviTopicWidget(), resizeEvent(), and switchMode().
KviInputEditor* KviTopicWidget::m_pInput [private]
Referenced by acceptClicked(), complete(), deactivate(), historyClicked(), insertText(), KviTopicWidget(), resizeEvent(), and switchMode().
QAbstractItemDelegate* KviTopicWidget::m_pItemDelegate [private]
Referenced by KviTopicWidget().
KviChannelWindow* KviTopicWidget::m_pKviChannelWindow [private]
Referenced by deactivate(), KviTopicWidget(), and switchMode().
KviThemedLabel* KviTopicWidget::m_pLabel [private]
Referenced by applyOptions(), deactivate(), KviTopicWidget(), reset(), resizeEvent(), setTopic(), and switchMode().
QString KviTopicWidget::m_szSetAt [private]
Referenced by reset(), setTopicSetAt(), and updateToolTip().
QString KviTopicWidget::m_szSetBy [private]
Referenced by reset(), setTopicSetBy(), and updateToolTip().
QString KviTopicWidget::m_szTopic [private]
Referenced by acceptClicked(), copy(), reset(), setTopic(), switchMode(), and updateToolTip().
Property Documentation
int KviTopicWidget::TransparencyCapable [read]
The documentation for this class was generated from the following files:
src/kvirc/ui/KviTopicWidget.h
src/kvirc/ui/KviTopicWidget.cpp