KVIrc: ScriptEditorWidgetColorOptions Class Reference
ScriptEditorWidgetColorOptions Class Reference
#include <ScriptEditorImplementation.h>
Public Member Functions
ScriptEditorWidgetColorOptions (QWidget *pParent)
~ScriptEditorWidgetColorOptions ()
Protected Slots
void okClicked ()
Protected Member Functions
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled)
Private Attributes
KviPointerList
< KviSelectorInterface > * m_pSelectorInterfaceList
Constructor & Destructor Documentation
ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions (QWidget * pParent)
References __tr2qs_ctx(), addColorSelector(), KviPointerList< T >::append(), connect(), f, g, g_clrBackground(), g_clrBracket(), g_clrComment(), g_clrFind(), g_clrFunction(), g_clrKeyword(), g_clrNormalText(), g_clrPunctuation(), g_clrVariable(), g_fntNormal(), m_pSelectorInterfaceList, okClicked(), KviPointerList< T >::setAutoDelete(), KviTalGroupBox::setInsideSpacing(), KviTalVBox::setMargin(), and KviTalVBox::setSpacing().
ScriptEditorWidgetColorOptions::~ScriptEditorWidgetColorOptions ()
References m_pSelectorInterfaceList.
Member Function Documentation
KviColorSelector * ScriptEditorWidgetColorOptions::addColorSelector (QWidget * pParent, const QString & txt, QColor * pOption, bool bEnabled) [protected]
References KviPointerList< T >::append(), m_pSelectorInterfaceList, and s.
Referenced by ScriptEditorWidgetColorOptions().
void ScriptEditorWidgetColorOptions::okClicked () [protected, slot]
References KviPointerList< T >::first(), i, m_pSelectorInterfaceList, and KviPointerList< T >::next().
Referenced by ScriptEditorWidgetColorOptions().
Member Data Documentation
KviPointerList<KviSelectorInterface>* ScriptEditorWidgetColorOptions::m_pSelectorInterfaceList [private]
Referenced by addColorSelector(), okClicked(), ScriptEditorWidgetColorOptions(), and ~ScriptEditorWidgetColorOptions().
The documentation for this class was generated from the following files:
src/modules/editor/ScriptEditorImplementation.h
src/modules/editor/ScriptEditorImplementation.cpp