KVIrc: TrashcanLabel Class Reference
TrashcanLabel Class Reference
#include <CustomizeToolBarsDialog.h>
Public Slots
void flash ()
Public Member Functions
TrashcanLabel (QWidget *p)
virtual ~TrashcanLabel ()
Protected Slots
void heartbeat ()
Protected Member Functions
virtual void dragEnterEvent (QDragEnterEvent *e)
virtual void dropEvent (QDropEvent *e)
Protected Attributes
QColor m_clrOriginal
QTimer * m_pFlashTimer
unsigned int m_uFlashCount
Constructor & Destructor Documentation
TrashcanLabel::TrashcanLabel (QWidget * p)
References __tr2qs_ctx(), KviTalToolTip::add(), connect(), flash(), g_pIconManager, KviIconManager::getBigIcon(), KviActionManager::instance(), m_clrOriginal, m_pFlashTimer, and m_uFlashCount.
TrashcanLabel::~TrashcanLabel () [virtual]
References m_pFlashTimer.
Member Function Documentation
void TrashcanLabel::dragEnterEvent (QDragEnterEvent * e) [protected, virtual]
void TrashcanLabel::dropEvent (QDropEvent * e) [protected, virtual]
void TrashcanLabel::flash () [slot]
References connect(), heartbeat(), m_pFlashTimer, and m_uFlashCount.
Referenced by TrashcanLabel().
void TrashcanLabel::heartbeat () [protected, slot]
References m_clrOriginal, m_pFlashTimer, m_uFlashCount, and p.
Referenced by flash().
Member Data Documentation
QColor TrashcanLabel::m_clrOriginal [protected]
Referenced by heartbeat(), and TrashcanLabel().
QTimer* TrashcanLabel::m_pFlashTimer [protected]
Referenced by flash(), heartbeat(), TrashcanLabel(), and ~TrashcanLabel().
unsigned int TrashcanLabel::m_uFlashCount [protected]
Referenced by flash(), heartbeat(), and TrashcanLabel().
The documentation for this class was generated from the following files:
src/modules/toolbareditor/CustomizeToolBarsDialog.h
src/modules/toolbareditor/CustomizeToolBarsDialog.cpp