KVIrc: ClassEditorTreeWidgetItem Class Reference
ClassEditorTreeWidgetItem Class Reference
Describes an item inside the class editor tree widget.
#include <ClassEditorWindow.h>
Public Types
enum Type { Class, Namespace, Method }
Contains the type of the class item.
Public Member Functions
const QString & buffer ()
Returns the buffer containing the code of the item.
ClassEditorTreeWidgetItem (QTreeWidget *pTreeWidget, Type eType, const QString &szName)
Constructs the class editor tree widget item.
ClassEditorTreeWidgetItem (ClassEditorTreeWidgetItem *pParentItem, Type eType, const QString &szName)
Constructs the class editor tree widget item.
bool classNotBuilt ()
Returns true if we class is not built yet, false otherwise.
const int & cursorPosition ()
Returns the cursor's position.
QString inheritsClass ()
Returns the class name of the classes we inherit from.
bool isClass ()
Returns true if the item is a class, false otherwise.
bool isInternalFunction ()
Returns true if the function is set as internal, false otherwise.
bool isMethod ()
Returns true if the item is a member function, false otherwise.
bool isNamespace ()
Returns true if the item is a namespace, false otherwise.
const QString & name ()
Returns the name of the item.
QString reminder ()
Returns the parameters list.
void setBuffer (const QString &szBuffer)
Saves the code of the item in a buffer.
void setClassNotBuilt (bool bModified)
Sets the state of the class as non-built.
void setCursorPosition (const int &iPos)
Sets the cursor position.
void setInheritsClass (QString szInheritsClassName)
Sets the class name on which the class inherits from.
void setInternalFunction (bool bInternal)
Sets the function as internal.
void setName (const QString &szName)
Sets the name of the item.
void setReminder (const QString &szRem)
Sets the list of parameters the function accept.
void setType (Type eType)
Sets the type of the item.
Type type ()
Returns the type of the item.
~ClassEditorTreeWidgetItem ()
Destroys the class editor tree widget item.
Protected Attributes
bool m_bClassModified
bool m_bInternal
Type m_eType
int m_iPos
QString m_szBuffer
QString m_szInheritsClassName
QString m_szName
QString m_szReminder
Detailed Description
Describes an item inside the class editor tree widget.
Member Enumeration Documentation
enum ClassEditorTreeWidgetItem::Type
Contains the type of the class item.
Enumerator:
Class
The item is a class
Namespace
The item is a namespace
Method
The item is a member function
Constructor & Destructor Documentation
ClassEditorTreeWidgetItem::ClassEditorTreeWidgetItem (QTreeWidget * pTreeWidget, Type eType, const QString & szName)
Constructs the class editor tree widget item.
Parameters:
pTreeWidget The parent tree widget
eType The type of the item
szName The name of the item
Returns:
ClassEditorTreeWidgetItem
References KviIconManager::Class, g_pIconManager, KviIconManager::getSmallIcon(), m_bClassModified, m_bInternal, m_iPos, m_szInheritsClassName, KviIconManager::NameSpace, Namespace, and setName().
ClassEditorTreeWidgetItem::ClassEditorTreeWidgetItem (ClassEditorTreeWidgetItem * pParentItem, Type eType, const QString & szName)
Constructs the class editor tree widget item.
Parameters:
pParentItem The parent tree widget item
eType The type of the item
szName The name of the item
Returns:
ClassEditorTreeWidgetItem
References KviIconManager::Class, Class, KviIconManager::Function, g_pIconManager, KviIconManager::getSmallIcon(), m_bClassModified, m_bInternal, m_iPos, m_szInheritsClassName, KviIconManager::NameSpace, Namespace, and setName().
ClassEditorTreeWidgetItem::~ClassEditorTreeWidgetItem () [inline]
Destroys the class editor tree widget item.
Member Function Documentation
const QString& ClassEditorTreeWidgetItem::buffer () [inline]
Returns the buffer containing the code of the item.
Returns:
const QString &
References m_szBuffer.
Referenced by ClassEditorWidget::exportClassBuffer().
bool ClassEditorTreeWidgetItem::classNotBuilt () [inline]
Returns true if we class is not built yet, false otherwise.
Returns:
bool
References m_bClassModified.
Referenced by ClassEditorWidget::build(), and ClassEditorWidget::saveNotBuiltClasses().
const int& ClassEditorTreeWidgetItem::cursorPosition () [inline]
Returns the cursor's position.
Returns:
const int &
References m_iPos.
QString ClassEditorTreeWidgetItem::inheritsClass () [inline]
Returns the class name of the classes we inherit from.
Returns:
QString
References m_szInheritsClassName.
Referenced by ClassEditorWidget::build(), ClassEditorWidget::currentItemChanged(), ClassEditorWidget::exportClassBuffer(), ClassEditorWidget::renameClass(), ClassEditorWidget::saveNotBuiltClasses(), and ClassEditorWidget::searchInheritedClasses().
bool ClassEditorTreeWidgetItem::isClass () [inline]
Returns true if the item is a class, false otherwise.
Returns:
bool
References Class, and m_eType.
Referenced by ClassEditorWidget::currentItemChanged(), ClassEditorWidget::customContextMenuRequested(), ClassEditorWidget::removeItem(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameItem(), ClassEditorWidget::renameNamespace(), and ClassEditorWidget::saveLastEditedItem().
bool ClassEditorTreeWidgetItem::isInternalFunction () [inline]
Returns true if the function is set as internal, false otherwise.
Returns:
bool
References m_bInternal.
Referenced by ClassEditorWidget::exportClassBuffer(), and ClassEditorWidget::renameFunction().
bool ClassEditorTreeWidgetItem::isMethod () [inline]
Returns true if the item is a member function, false otherwise.
Returns:
bool
References m_eType, and Method.
Referenced by ClassEditorWidget::currentItemChanged(), ClassEditorWidget::customContextMenuRequested(), ClassEditorWidget::exportClassBuffer(), ClassEditorWidget::newMemberFunction(), and ClassEditorWidget::removeItem().
bool ClassEditorTreeWidgetItem::isNamespace () [inline]
Returns true if the item is a namespace, false otherwise.
Returns:
bool
References m_eType, and Namespace.
Referenced by ClassEditorWidget::currentItemChanged(), ClassEditorWidget::customContextMenuRequested(), ClassEditorWidget::removeItem(), ClassEditorWidget::renameItem(), and ClassEditorWidget::saveLastEditedItem().
const QString& ClassEditorTreeWidgetItem::name () [inline]
Returns the name of the item.
Returns:
const QString &
References m_szName.
Referenced by ClassEditorWidget::buildFullClassName(), ClassEditorWidget::buildFullItemPath(), ClassEditorWidget::currentItemChanged(), ClassEditorWidget::exportClassBuffer(), ClassEditorWidget::removeItem(), ClassEditorWidget::renameFunction(), and ClassEditorWidget::updateClassHierarchy().
QString ClassEditorTreeWidgetItem::reminder () [inline]
Returns the parameters list.
Returns:
QString
References m_szReminder.
Referenced by ClassEditorWidget::currentItemChanged(), ClassEditorWidget::exportClassBuffer(), and ClassEditorWidget::renameFunction().
void ClassEditorTreeWidgetItem::setBuffer (const QString & szBuffer) [inline]
Saves the code of the item in a buffer.
Parameters:
szBuffer The buffer ;)
Returns:
void
References m_szBuffer, and szBuffer.
Referenced by ClassEditorWidget::createFullClass(), and ClassEditorWidget::loadNotBuiltClasses().
void ClassEditorTreeWidgetItem::setClassNotBuilt (bool bModified)
Sets the state of the class as non-built.
Parameters:
bModified Whether the class is modified
Returns:
void
References KviIconManager::Class, KviIconManager::ClassNotBuilt, g_pIconManager, KviIconManager::getSmallIcon(), and m_bClassModified.
Referenced by ClassEditorWidget::build(), ClassEditorWidget::loadNotBuiltClasses(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), ClassEditorWidget::renameNamespace(), ClassEditorWidget::searchReplace(), and ClassEditorWidget::updateClassHierarchy().
void ClassEditorTreeWidgetItem::setCursorPosition (const int & iPos) [inline]
Sets the cursor position.
Parameters:
iPos The position of the cursor
Returns:
void
References m_iPos.
void ClassEditorTreeWidgetItem::setInheritsClass (QString szInheritsClassName) [inline]
Sets the class name on which the class inherits from.
Parameters:
szInheritsClassName The parent class name
Returns:
void
References m_szInheritsClassName.
Referenced by ClassEditorWidget::createFullClass(), ClassEditorWidget::loadNotBuiltClasses(), ClassEditorWidget::newClass(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameNamespace(), and ClassEditorWidget::updateClassHierarchy().
void ClassEditorTreeWidgetItem::setInternalFunction (bool bInternal) [inline]
Sets the function as internal.
Parameters:
bInternal Whether the function is internal or not
Returns:
void
References m_bInternal.
Referenced by ClassEditorWidget::createFullClass(), ClassEditorWidget::newMemberFunction(), and ClassEditorWidget::renameFunction().
void ClassEditorTreeWidgetItem::setName (const QString & szName)
Sets the name of the item.
Parameters:
szName The name of the item :P
Returns:
void
References m_szName.
Referenced by ClassEditorTreeWidgetItem(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), and ClassEditorWidget::renameNamespace().
void ClassEditorTreeWidgetItem::setReminder (const QString & szRem) [inline]
Sets the list of parameters the function accept.
Parameters:
szRem The parameters' list
Returns:
void
References m_szReminder.
Referenced by ClassEditorWidget::createFullClass(), ClassEditorWidget::loadNotBuiltClasses(), ClassEditorWidget::newMemberFunction(), and ClassEditorWidget::renameFunction().
void ClassEditorTreeWidgetItem::setType (Type eType)
Sets the type of the item.
Parameters:
eType The type!
Returns:
void
References KviIconManager::Class, Class, KviIconManager::Function, g_pIconManager, KviIconManager::getSmallIcon(), m_eType, KviIconManager::NameSpace, and Namespace.
Referenced by ClassEditorWidget::newItem().
Type ClassEditorTreeWidgetItem::type () [inline]
Returns the type of the item.
Returns:
Type
References m_eType.
Member Data Documentation
bool ClassEditorTreeWidgetItem::m_bClassModified [protected]
Referenced by ClassEditorTreeWidgetItem(), classNotBuilt(), and setClassNotBuilt().
bool ClassEditorTreeWidgetItem::m_bInternal [protected]
Referenced by ClassEditorTreeWidgetItem(), isInternalFunction(), and setInternalFunction().
Type ClassEditorTreeWidgetItem::m_eType [protected]
Referenced by isClass(), isMethod(), isNamespace(), setType(), and type().
int ClassEditorTreeWidgetItem::m_iPos [protected]
Referenced by ClassEditorTreeWidgetItem(), cursorPosition(), and setCursorPosition().
QString ClassEditorTreeWidgetItem::m_szBuffer [protected]
Referenced by buffer(), and setBuffer().
QString ClassEditorTreeWidgetItem::m_szInheritsClassName [protected]
Referenced by ClassEditorTreeWidgetItem(), inheritsClass(), and setInheritsClass().
QString ClassEditorTreeWidgetItem::m_szName [protected]
Referenced by name(), and setName().
QString ClassEditorTreeWidgetItem::m_szReminder [protected]
Referenced by reminder(), and setReminder().
The documentation for this class was generated from the following files:
src/modules/classeditor/ClassEditorWindow.h
src/modules/classeditor/ClassEditorWindow.cpp