KVIrc: KviAvatarCache Class Reference
KviAvatarCache Class Reference
Avatar cache handling class.
#include <kvi_avatarcache.h>
Public Member Functions
void cleanup ()
Deletes the cache.
void load (const QString &szFileName)
Loads the cache.
const QString & lookup (const KviIrcMask &mask, const QString &szNetwork)
Search an user in the cache and returns the id of the avatar.
void remove (const KviIrcMask &mask, const QString &szNetwork)
Remove an avatar from the cache.
void replace (const QString &szIdString, const KviIrcMask &mask, const QString &szNetwork)
Replaces a cached avatar.
void save (const QString &szFileName)
Saves the cache.
Static Public Member Functions
static void done ()
Destroys the avatar cache.
static void init ()
Initializes the avatar cache.
static KviAvatarCache * instance ()
Returns the instance of the avatar cache.
Public Attributes
KviPointerHashTable< QString,
KviAvatarCacheEntry > * m_pAvatarDict
Protected Member Functions
KviAvatarCache ()
Constructs the avatar cache object.
~KviAvatarCache ()
Destroys the avatar cache object.
Static Protected Attributes
static KviAvatarCache * m_pAvatarCacheInstance = 0
Detailed Description
Avatar cache handling class.
Constructor & Destructor Documentation
KviAvatarCache::KviAvatarCache () [protected]
Constructs the avatar cache object.
Returns:
KviAvatarCache
References CACHE_DICT_SIZE, m_pAvatarDict, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviAvatarCache::~KviAvatarCache () [protected]
Destroys the avatar cache object.
References m_pAvatarDict.
Member Function Documentation
void KviAvatarCache::cleanup ()
Deletes the cache.
Returns:
void
References KviPointerList< T >::append(), CACHE_GUARD_LEVEL, KviPointerList< T >::count(), KviPointerHashTable< Key, T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), e, KviPointerList< T >::first(), KviPointerList< T >::insert(), kvi_time_t, kvi_unixTime, m_pAvatarDict, MAX_UNACCESSED_TIME, KviPointerList< T >::next(), KviPointerHashTable< Key, T >::remove(), s, KviPointerList< T >::setAutoDelete(), _KviAvatarCacheEntry::szIdString, _KviAvatarCacheEntry::tLastAccess, and KviPointerHashTableIterator< Key, T >::toFirst().
Referenced by replace().
void KviAvatarCache::done () [static]
Destroys the avatar cache.
Returns:
void
References debug, and m_pAvatarCacheInstance.
void KviAvatarCache::init () [static]
Initializes the avatar cache.
Returns:
void
References debug, KviAvatarCache(), and m_pAvatarCacheInstance.
static KviAvatarCache* KviAvatarCache::instance () [inline, static]
Returns the instance of the avatar cache.
Returns:
KviAvatarCache *
Referenced by KviConsole::avatarChanged(), KviConsole::checkDefaultAvatar(), KviApp::saveAvatarCache(), and KviApp::setup().
void KviAvatarCache::load (const QString & szFileName)
Loads the cache.
Parameters:
szFileName The cache filename
Returns:
void
References KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfig::dict(), e, kvi_time_t, kvi_unixTime, m_pAvatarDict, MAX_AVATARS_IN_CACHE, MAX_UNACCESSED_TIME, KviConfig::Read, KviConfig::readQStringEntry(), KviConfig::readUIntEntry(), KviPointerHashTable< Key, T >::replace(), KviConfig::setGroup(), _KviAvatarCacheEntry::szIdString, and _KviAvatarCacheEntry::tLastAccess.
Referenced by KviApp::setup().
const QString & KviAvatarCache::lookup (const KviIrcMask & mask, const QString & szNetwork)
Search an user in the cache and returns the id of the avatar.
Parameters:
mask The mask of the user
szNetwork The network where the user is on
Returns:
const QString &
References e, KviQString::Empty, KviPointerHashTable< Key, T >::find(), kvi_unixTime, m_pAvatarDict, KviIrcMask::mask(), KviIrcMask::NickCleanUserSmartNet, _KviAvatarCacheEntry::szIdString, and _KviAvatarCacheEntry::tLastAccess.
Referenced by KviConsole::checkDefaultAvatar().
void KviAvatarCache::remove (const KviIrcMask & mask, const QString & szNetwork)
Remove an avatar from the cache.
Parameters:
mask The mask of the user
szNetwork The network where the user is on
Returns:
void
References m_pAvatarDict, KviIrcMask::mask(), KviIrcMask::NickCleanUserSmartNet, and KviPointerHashTable< Key, T >::remove().
Referenced by KviConsole::avatarChanged(), and KviConsole::checkDefaultAvatar().
void KviAvatarCache::replace (const QString & szIdString, const KviIrcMask & mask, const QString & szNetwork)
Replaces a cached avatar.
Parameters:
szIdString The id of the avatar
mask The mask of the user
szNetwork The network where the user is on
Returns:
void
References cleanup(), KviPointerHashTable< Key, T >::count(), e, kvi_unixTime, m_pAvatarDict, KviIrcMask::mask(), MAX_AVATARS_IN_CACHE, KviIrcMask::NickCleanUserSmartNet, KviPointerHashTable< Key, T >::replace(), _KviAvatarCacheEntry::szIdString, and _KviAvatarCacheEntry::tLastAccess.
Referenced by KviConsole::avatarChanged().
void KviAvatarCache::save (const QString & szFileName)
Saves the cache.
Parameters:
szFileName The cache filename
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), e, m_pAvatarDict, KviConfig::setGroup(), KviConfig::Write, and KviConfig::writeEntry().
Referenced by KviApp::saveAvatarCache().
Member Data Documentation
KviAvatarCache * KviAvatarCache::m_pAvatarCacheInstance = 0 [static, protected]
Referenced by done(), and init().
KviPointerHashTable<QString,KviAvatarCacheEntry>* KviAvatarCache::m_pAvatarDict
Referenced by cleanup(), KviAvatarCache(), load(), lookup(), remove(), replace(), save(), and ~KviAvatarCache().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/irc/kvi_avatarcache.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/irc/kvi_avatarcache.cpp