KVIrc: KviRequestQueue Class Reference
KviRequestQueue Class Reference
Class to enqueue commands to IRC server.
#include <kvi_ircconnectionrequestqueue.h>
Public Member Functions
void clearAll ()
Clears the queue stack.
void dequeueChannel (KviChannel *pChan)
Removes the channel from the queue stack.
void enqueueChannel (KviChannel *pChan)
Enqueues the channel in the queue stack.
bool isQueued (KviChannel *pChan)
Checks if a channel is in the queue stack.
KviRequestQueue ()
Constructs the request queue objects.
virtual ~KviRequestQueue ()
Destroys the request queue objects.
Protected Types
enum RequestTypes {
Mode = 0, BanException = 1, Invite = 2, Who = 3,
QuietBan = 4, Ban = 5
}
Protected Attributes
QQueue< KviChannel * > m_channels
RequestTypes m_curType
QTimer m_timer
Private Slots
void timerSlot ()
Performs time based requests.
Detailed Description
Class to enqueue commands to IRC server.
This class is designed to delay channel requests like MODE and WHO to avoid excess floods on some servers
Member Enumeration Documentation
enum KviRequestQueue::RequestTypes [protected]
Warning:
MODE s b MUST BE THE LAST AUTOMATIC CHANNEL QUERY so we get RPL_ENDOFBANLIST as the last reply and we know that the channel is in sync
Enumerator:
Mode
Channel modes request
BanException
Ban exceptions request
Invite
Invites request
Who
Who request
QuietBan
Quiet ban request
Ban
Ban request
Constructor & Destructor Documentation
KviRequestQueue::KviRequestQueue ()
Constructs the request queue objects.
Returns:
KviRequestQueue
References m_curType, m_timer, Mode, and timerSlot().
KviRequestQueue::~KviRequestQueue () [virtual]
Destroys the request queue objects.
References m_timer, and timerSlot().
Member Function Documentation
void KviRequestQueue::clearAll ()
Clears the queue stack.
Returns:
void
References m_channels, m_curType, m_timer, and Mode.
Referenced by KviIrcContext::connectionTerminated(), and timerSlot().
void KviRequestQueue::dequeueChannel (KviChannel * pChan)
Removes the channel from the queue stack.
Parameters:
pChan The channel to dequeue
Returns:
void
References m_channels, and m_timer.
Referenced by KviIrcConnection::unregisterChannel().
void KviRequestQueue::enqueueChannel (KviChannel * pChan)
Enqueues the channel in the queue stack.
Parameters:
pChan The channel to enqueue
Returns:
void
References KVI_OPTION_UINT, KviOption_uintOnJoinRequestsDelay, m_channels, and m_timer.
Referenced by KviServerParser::parseLiteralJoin().
bool KviRequestQueue::isQueued (KviChannel * pChan) [inline]
Checks if a channel is in the queue stack.
Parameters:
pChan The channel to check
Returns:
bool
void KviRequestQueue::timerSlot () [private, slot]
Performs time based requests.
Returns:
void
References Ban, BanException, clearAll(), KviWindow::connection(), KviIrcConnection::encodeText(), KviIrcConnectionServerInfo::getNeedsOpToListModeseI(), Invite, KviChannel::isMeOp(), KVI_OPTION_BOOL, kvi_unixTime, KviOption_boolDisableBanExceptionListRequestOnJoin, KviOption_boolDisableBanListRequestOnJoin, KviOption_boolDisableInviteListRequestOnJoin, KviOption_boolDisableQuietBanListRequestOnJoin, KviOption_boolDisableWhoRequestOnJoin, KviLagMeter::lagCheckRegister(), KviIrcConnection::lagMeter(), m_channels, m_curType, m_timer, Mode, KviStr::ptr(), QuietBan, KviIrcConnection::sendFmtData(), KviChannel::serverInfo(), KviIrcConnectionStateData::setLastSentChannelWhoRequest(), KviChannel::setSentListRequest(), KviChannel::setSentWhoRequest(), KviStr::sprintf(), KviIrcConnection::stateData(), KviIrcConnectionServerInfo::supportedListModes(), KviChannel::target(), and Who.
Referenced by KviRequestQueue(), and ~KviRequestQueue().
Member Data Documentation
QQueue<KviChannel *> KviRequestQueue::m_channels [protected]
Referenced by clearAll(), dequeueChannel(), enqueueChannel(), and timerSlot().
RequestTypes KviRequestQueue::m_curType [protected]
Referenced by clearAll(), KviRequestQueue(), and timerSlot().
QTimer KviRequestQueue::m_timer [protected]
Referenced by clearAll(), dequeueChannel(), enqueueChannel(), KviRequestQueue(), timerSlot(), and ~KviRequestQueue().
The documentation for this class was generated from the following files:
src/kvirc/kernel/kvi_ircconnectionrequestqueue.h
src/kvirc/kernel/kvi_ircconnectionrequestqueue.cpp