KVIrc: KviTalTabDialog Class Reference
KviTalTabDialog Class Reference
#include <KviTalTabDialog.h>
Signals
void applyButtonPressed ()
void cancelButtonPressed ()
Public Member Functions
KviTalTabDialog (QWidget *pParent=0, const char *name=0, bool bModal=false)
~KviTalTabDialog ()
Protected Slots
void cancelPressed ()
void okPressed ()
Protected Member Functions
void addTab (QWidget *, const QString &)
void setCancelButton (const QString &)
void setOkButton (const QString &)
Private Attributes
QGridLayout * m_pLayout
QTabWidget * m_pTabWidget
Constructor & Destructor Documentation
KviTalTabDialog::KviTalTabDialog (QWidget * pParent = 0, const char * name = 0, bool bModal = false)
References m_pLayout, and m_pTabWidget.
KviTalTabDialog::~KviTalTabDialog ()
Member Function Documentation
void KviTalTabDialog::addTab (QWidget * widget, const QString & label) [protected]
References m_pTabWidget.
Referenced by AboutDialog::AboutDialog(), and RegisteredUserEntryDialog::RegisteredUserEntryDialog().
void KviTalTabDialog::applyButtonPressed () [signal]
Referenced by AboutDialog::AboutDialog(), okPressed(), and RegisteredUserEntryDialog::RegisteredUserEntryDialog().
void KviTalTabDialog::cancelButtonPressed () [signal]
Referenced by cancelPressed(), and RegisteredUserEntryDialog::RegisteredUserEntryDialog().
void KviTalTabDialog::cancelPressed () [protected, slot]
References cancelButtonPressed().
Referenced by setCancelButton().
void KviTalTabDialog::okPressed () [protected, slot]
References applyButtonPressed().
Referenced by setOkButton().
void KviTalTabDialog::setCancelButton (const QString & text) [protected]
References cancelPressed(), connect(), and m_pLayout.
Referenced by RegisteredUserEntryDialog::RegisteredUserEntryDialog().
void KviTalTabDialog::setOkButton (const QString & text) [protected]
References connect(), m_pLayout, and okPressed().
Referenced by AboutDialog::AboutDialog(), and RegisteredUserEntryDialog::RegisteredUserEntryDialog().
Member Data Documentation
QGridLayout* KviTalTabDialog::m_pLayout [private]
Referenced by KviTalTabDialog(), setCancelButton(), and setOkButton().
QTabWidget* KviTalTabDialog::m_pTabWidget [private]
Referenced by addTab(), and KviTalTabDialog().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalTabDialog.h
src/kvilib/tal/KviTalTabDialog.cpp