KVIrc: KviKvsTreeNodeParameterCount Class Reference
KviKvsTreeNodeParameterCount Class Reference
#include <KviKvsTreeNodeParameterCount.h>
Public Member Functions
virtual bool canEvaluateToObjectReference ()
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeParameterCount (const QChar *pLocation)
~KviKvsTreeNodeParameterCount ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeParameterCount::KviKvsTreeNodeParameterCount (const QChar * pLocation)
KviKvsTreeNodeParameterCount::~KviKvsTreeNodeParameterCount ()
Member Function Documentation
bool KviKvsTreeNodeParameterCount::canEvaluateToObjectReference () virtual
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeParameterCount::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeParameterCount::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
bool KviKvsTreeNodeParameterCount::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariantList::count(), KviKvsRunTimeContext::parameterList(), and KviKvsVariant::setInteger().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeParameterCount.h
src/kvirc/kvs/tree/KviKvsTreeNodeParameterCount.cpp