KVIrc: KviKvsTreeNodeSwitchList Class Reference
KviKvsTreeNodeSwitchList Class Reference
#include <KviKvsTreeNodeSwitchList.h>
Public Member Functions
void addLong (const QString &szLongKey, KviKvsTreeNodeData *p)
void addShort (int iShortKey, KviKvsTreeNodeData *p)
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
bool evaluate (KviKvsRunTimeContext *c, KviKvsSwitchList *pSwList)
KviKvsTreeNodeData * getStandardRebindingSwitch ()
bool isEmpty ()
KviKvsTreeNodeSwitchList (const QChar *pLocation)
~KviKvsTreeNodeSwitchList ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Public Attributes
KviPointerHashTable< QString,
KviKvsTreeNodeData > * m_pLongSwitchDict
KviPointerHashTable< int,
KviKvsTreeNodeData > * m_pShortSwitchDict
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeSwitchList::KviKvsTreeNodeSwitchList (const QChar * pLocation)
References m_pLongSwitchDict, and m_pShortSwitchDict.
KviKvsTreeNodeSwitchList::~KviKvsTreeNodeSwitchList ()
References m_pLongSwitchDict, and m_pShortSwitchDict.
Member Function Documentation
void KviKvsTreeNodeSwitchList::addLong (const QString & szLongKey, KviKvsTreeNodeData * p)
References m_pLongSwitchDict, KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseCommandSwitchList().
void KviKvsTreeNodeSwitchList::addShort (int iShortKey, KviKvsTreeNodeData * p)
References m_pShortSwitchDict, KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseCommandSwitchList().
void KviKvsTreeNodeSwitchList::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeSwitchList::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
References c, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviKvsTreeNodeData::dump(), m_pLongSwitchDict, and m_pShortSwitchDict.
Referenced by KviKvsTreeNodeCommand::dumpSwitchList().
bool KviKvsTreeNodeSwitchList::evaluate (KviKvsRunTimeContext * c, KviKvsSwitchList * pSwList)
References KviKvsSwitchList::addLong(), KviKvsSwitchList::addShort(), KviKvsSwitchList::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, m_pLongSwitchDict, m_pShortSwitchDict, and v.
Referenced by KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeCoreSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeCoreCallbackCommand::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsTreeNodeSpecialCommandSwitch::execute(), and KviKvsTreeNodeSpecialCommandDefpopup::execute().
KviKvsTreeNodeData * KviKvsTreeNodeSwitchList::getStandardRebindingSwitch ()
References d, KviPointerHashTable< Key, T >::find(), m_pLongSwitchDict, m_pShortSwitchDict, KviPointerHashTable< Key, T >::remove(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by KviKvsParser::parseCommand().
bool KviKvsTreeNodeSwitchList::isEmpty () inline
Referenced by KviKvsParser::parseCommandSwitchList().
Member Data Documentation
KviPointerHashTable<QString,KviKvsTreeNodeData>* KviKvsTreeNodeSwitchList::m_pLongSwitchDict
Referenced by addLong(), dump(), evaluate(), getStandardRebindingSwitch(), KviKvsTreeNodeSwitchList(), and ~KviKvsTreeNodeSwitchList().
KviPointerHashTable<int,KviKvsTreeNodeData>* KviKvsTreeNodeSwitchList::m_pShortSwitchDict
Referenced by addShort(), dump(), evaluate(), getStandardRebindingSwitch(), KviKvsTreeNodeSwitchList(), and ~KviKvsTreeNodeSwitchList().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSwitchList.h
src/kvirc/kvs/tree/KviKvsTreeNodeSwitchList.cpp