KVIrc: DccRenameDialog Class Reference
DccRenameDialog Class Reference
#include <DccDialog.h>
Signals
void cancelSelected (DccDialog *, DccDescriptor *)
void overwriteSelected (DccDialog *, DccDescriptor *)
void renameSelected (DccDialog *, DccDescriptor *)
Public Member Functions
DccRenameDialog (DccBroker *br, DccDescriptor *dcc, const QString &text, bool bDisableResume)
~DccRenameDialog ()
Public Member Functions inherited from DccDialog
DccDialog (DccBroker *br, DccDescriptor *dcc)
virtual void forgetDescriptor ()
virtual ~DccDialog ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
virtual void showEvent (QShowEvent *e)
Private Slots
void cancelClicked ()
void overwriteClicked ()
void renameClicked ()
void resumeClicked ()
Additional Inherited Members
Protected Attributes inherited from DccDialog
DccBroker * m_pBroker
DccDescriptor * m_pDescriptor
Constructor & Destructor Documentation
DccRenameDialog::DccRenameDialog (DccBroker * br, DccDescriptor * dcc, const QString & text, bool bDisableResume)
References __tr2qs_ctx(), cancelClicked(), connect(), KviIconManager::DccMsg, g_pIconManager, KviIconManager::getSmallIcon(), l, overwriteClicked(), renameClicked(), and resumeClicked().
DccRenameDialog::~DccRenameDialog ()
Member Function Documentation
void DccRenameDialog::cancelClicked () private slot
References cancelSelected(), and DccDialog::m_pDescriptor.
Referenced by DccRenameDialog().
void DccRenameDialog::cancelSelected (DccDialog * , DccDescriptor *) signal
Referenced by cancelClicked(), and closeEvent().
void DccRenameDialog::closeEvent (QCloseEvent * e) protected virtual
References cancelSelected(), and DccDialog::m_pDescriptor.
void DccRenameDialog::overwriteClicked () private slot
References DccDialog::m_pDescriptor, and overwriteSelected().
Referenced by DccRenameDialog().
void DccRenameDialog::overwriteSelected (DccDialog * , DccDescriptor *) signal
Referenced by overwriteClicked(), and resumeClicked().
void DccRenameDialog::renameClicked () private slot
References DccDialog::m_pDescriptor, and renameSelected().
Referenced by DccRenameDialog().
void DccRenameDialog::renameSelected (DccDialog * , DccDescriptor *) signal
Referenced by renameClicked().
void DccRenameDialog::resumeClicked () private slot
References DccDescriptor::bResume, DccDialog::m_pDescriptor, and overwriteSelected().
Referenced by DccRenameDialog().
void DccRenameDialog::showEvent (QShowEvent * e) protected virtual
References g_pApp, and KviMemory::move().
The documentation for this class was generated from the following files:
src/modules/dcc/DccDialog.h
src/modules/dcc/DccDialog.cpp