KVIrc: KviKvsTreeNodeOperationSelfSum Class Reference
KviKvsTreeNodeOperationSelfSum Class Reference
#include <KviKvsTreeNodeOperation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationSelfSum (const QChar *pLocation, KviKvsTreeNodeData *pRightSide)
~KviKvsTreeNodeOperationSelfSum ()
Public Member Functions inherited from KviKvsTreeNodeOperation
KviKvsTreeNodeOperation (const QChar *pLocation)
void setTargetVariableReference (KviKvsTreeNodeData *r)
~KviKvsTreeNodeOperation ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeData * m_pRightSide
Protected Attributes inherited from KviKvsTreeNodeOperation
KviKvsTreeNodeData * m_pTargetData
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeOperationSelfSum::KviKvsTreeNodeOperationSelfSum (const QChar * pLocation, KviKvsTreeNodeData * pRightSide)
References m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationSelfSum::~KviKvsTreeNodeOperationSelfSum ()
References m_pRightSide.
Member Function Documentation
void KviKvsTreeNodeOperationSelfSum::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationSelfSum::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pRightSide, and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationSelfSum::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsVariant::asNumber(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsNumber::integer(), KviKvsNumber::isInteger(), m_pRightSide, KviKvsTreeNodeOperation::m_pTargetData, KviKvsNumber::real(), KviKvsRWEvaluationResult::result(), KviKvsVariant::setInteger(), KviKvsVariant::setReal(), and v.
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationSelfSum::m_pRightSide protected
Referenced by dump(), execute(), KviKvsTreeNodeOperationSelfSum(), and ~KviKvsTreeNodeOperationSelfSum().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.h
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.cpp