KVIrc: KviSensitiveThread Class Reference
KviSensitiveThread Class Reference
#include <KviThread.h>
Public Member Functions
void enqueueEvent (KviThreadEvent *e)
KviSensitiveThread ()
void terminate ()
virtual ~KviSensitiveThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
KviThreadEvent * dequeueEvent ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
virtual void run ()
Protected Attributes
KviPointerList< KviThreadEvent > * m_pLocalEventQueue
KviMutex * m_pLocalEventQueueMutex
Additional Inherited Members
Static Public Member Functions inherited from KviThread
static void msleep (unsigned long msec)
static void sleep (unsigned long sec)
static void usleep (unsigned long usec)
Constructor & Destructor Documentation
KviSensitiveThread::KviSensitiveThread ()
References m_pLocalEventQueue, m_pLocalEventQueueMutex, and KviPointerList< T >::setAutoDelete().
KviSensitiveThread::~KviSensitiveThread () virtual
References KviMutex::lock(), m_pLocalEventQueue, m_pLocalEventQueueMutex, KviPointerList< T >::setAutoDelete(), terminate(), and KviMutex::unlock().
Member Function Documentation
KviThreadEvent * KviSensitiveThread::dequeueEvent () protected
References KviPointerList< T >::first(), KviMutex::lock(), m_pLocalEventQueue, m_pLocalEventQueueMutex, KviPointerList< T >::removeFirst(), and KviMutex::unlock().
Referenced by DccChatThread::run(), KviIdentDaemon::run(), DccSendThread::run(), DccVideoThread::run(), DccVoiceThread::run(), and DccRecvThread::run().
void KviSensitiveThread::enqueueEvent (KviThreadEvent * e)
References KviPointerList< T >::append(), e, KviMutex::lock(), m_pLocalEventQueue, m_pLocalEventQueueMutex, and KviMutex::unlock().
Referenced by DccVoiceWindow::startTalking(), DccVideoWindow::startTalking(), DccVoiceWindow::stopTalking(), DccVideoWindow::stopTalking(), and terminate().
void KviSensitiveThread::terminate ()
References enqueueEvent(), KVI_THREAD_EVENT_TERMINATE, and KviThread::wait().
Referenced by DccFileTransfer::abort(), DccChatWindow::~DccChatWindow(), DccFileTransfer::~DccFileTransfer(), DccVideoWindow::~DccVideoWindow(), DccVoiceWindow::~DccVoiceWindow(), KviIdentDaemon::~KviIdentDaemon(), and ~KviSensitiveThread().
Member Data Documentation
KviPointerList<KviThreadEvent>* KviSensitiveThread::m_pLocalEventQueue protected
Reimplemented from KviThread.
Referenced by dequeueEvent(), enqueueEvent(), KviSensitiveThread(), and ~KviSensitiveThread().
KviMutex* KviSensitiveThread::m_pLocalEventQueueMutex protected
Referenced by dequeueEvent(), enqueueEvent(), KviSensitiveThread(), and ~KviSensitiveThread().
The documentation for this class was generated from the following files:
src/kvilib/system/KviThread.h
src/kvilib/system/KviThread.cpp