KVIrc: KviDnsResolverResult Class Reference
KviDnsResolverResult Class Reference
#include <KviDnsResolver.h>
Public Member Functions
KviError::Code error ()
KviPointerList< QString > * hostnameList ()
KviPointerList< QString > * ipAddressList ()
const QString & query ()
~KviDnsResolverResult ()
Protected Member Functions
void appendAddress (const QString &szAddr)
void appendHostname (const QString &szHost)
KviDnsResolverResult ()
void setError (KviError::Code eError)
void setQuery (const QString &szQuery)
Protected Attributes
KviError::Code m_eError
KviPointerList< QString > * m_pHostnameList
KviPointerList< QString > * m_pIpAddressList
QString m_szQuery
Friends
class KviDnsResolver
class KviDnsResolverThread
Constructor & Destructor Documentation
KviDnsResolverResult::KviDnsResolverResult () [protected]
References m_eError, m_pHostnameList, m_pIpAddressList, KviPointerList< T >::setAutoDelete(), and KviError::Success.
KviDnsResolverResult::~KviDnsResolverResult ()
References m_pHostnameList, and m_pIpAddressList.
Member Function Documentation
void KviDnsResolverResult::appendAddress (const QString & szAddr) [protected]
References KviPointerList< T >::append(), and m_pIpAddressList.
Referenced by KviDnsResolverThread::run().
void KviDnsResolverResult::appendHostname (const QString & szHost) [protected]
References KviPointerList< T >::append(), and m_pHostnameList.
Referenced by KviDnsResolverThread::run().
KviError::Code KviDnsResolverResult::error () [inline]
Referenced by KviDnsResolver::error(), and KviDnsResolver::event().
KviPointerList<QString>* KviDnsResolverResult::hostnameList () [inline]
Referenced by KviDnsResolver::firstHostname(), KviDnsResolver::hostnameCount(), and KviDnsResolver::hostnameList().
KviPointerList<QString>* KviDnsResolverResult::ipAddressList () [inline]
Referenced by KviDnsResolver::firstIpAddress(), KviDnsResolver::ipAddressCount(), and KviDnsResolver::ipAddressList().
const QString& KviDnsResolverResult::query () [inline]
References KviDnsResolverThread::m_szQuery.
Referenced by KviDnsResolver::query().
void KviDnsResolverResult::setError (KviError::Code eError) [inline, protected]
Referenced by KviDnsResolverThread::postDnsError(), and KviDnsResolverThread::run().
void KviDnsResolverResult::setQuery (const QString & szQuery) [inline, protected]
References KviDnsResolverThread::m_szQuery.
Referenced by KviDnsResolverThread::run().
Friends And Related Function Documentation
friend class KviDnsResolver [friend]
friend class KviDnsResolverThread [friend]
Member Data Documentation
KviError::Code KviDnsResolverResult::m_eError [protected]
Referenced by KviDnsResolverResult().
KviPointerList<QString>* KviDnsResolverResult::m_pHostnameList [protected]
Referenced by appendHostname(), KviDnsResolverResult(), and ~KviDnsResolverResult().
KviPointerList<QString>* KviDnsResolverResult::m_pIpAddressList [protected]
Referenced by appendAddress(), KviDnsResolverResult(), and ~KviDnsResolverResult().
QString KviDnsResolverResult::m_szQuery [protected]
The documentation for this class was generated from the following files:
src/kvilib/net/KviDnsResolver.h
src/kvilib/net/KviDnsResolver.cpp