KVIrc: PackAddonSummaryFilesWidget Class Reference
PackAddonSummaryFilesWidget Class Reference
#include <PackAddonDialog.h>
Public Member Functions
PackAddonSummaryFilesWidget (PackAddonDialog *pParent)
void setPath (QString &szPath)
~PackAddonSummaryFilesWidget ()
Protected Slots
virtual void accept ()
virtual void reject ()
Protected Member Functions
virtual void showEvent (QShowEvent *)
Protected Attributes
QTextEdit * m_pFiles
QString m_szPath
Constructor & Destructor Documentation
PackAddonSummaryFilesWidget::PackAddonSummaryFilesWidget (PackAddonDialog * pParent)
References __tr2qs_ctx(), accept(), connect(), m_pFiles, and reject().
PackAddonSummaryFilesWidget::~PackAddonSummaryFilesWidget ()
Member Function Documentation
void PackAddonSummaryFilesWidget::accept () [protected, virtual, slot]
Referenced by PackAddonSummaryFilesWidget().
void PackAddonSummaryFilesWidget::reject () [protected, virtual, slot]
Referenced by PackAddonSummaryFilesWidget().
void PackAddonSummaryFilesWidget::setPath (QString & szPath) [inline]
References m_szPath.
Referenced by PackAddonDialog::packAddon().
void PackAddonSummaryFilesWidget::showEvent (QShowEvent *) [protected, virtual]
References m_pFiles, and m_szPath.
Member Data Documentation
QTextEdit* PackAddonSummaryFilesWidget::m_pFiles [protected]
Referenced by PackAddonSummaryFilesWidget(), and showEvent().
QString PackAddonSummaryFilesWidget::m_szPath [protected]
Referenced by setPath(), and showEvent().
The documentation for this class was generated from the following files:
src/modules/addon/PackAddonDialog.h
src/modules/addon/PackAddonDialog.cpp