KVIrc: KviDynamicToolTip Class Reference
KviDynamicToolTip Class Reference
#include <kvi_dynamictooltip.h>
Signals
void tipRequest (KviDynamicToolTip *tip, const QPoint &pnt)
Public Member Functions
KviDynamicToolTip (QWidget *parent, const char *name=0)
void tip (const QRect &rct, const QString &text)
virtual ~KviDynamicToolTip ()
Protected Member Functions
void maybeTip (const QPoint &pnt)
Protected Attributes
KviDynamicToolTipHelper * m_pHelper
Friends
class KviDynamicToolTipHelper
Constructor & Destructor Documentation
KviDynamicToolTip::KviDynamicToolTip (QWidget * parent, const char * name = 0)
References KviDynamicToolTipHelper, and m_pHelper.
KviDynamicToolTip::~KviDynamicToolTip () [virtual]
References m_pHelper.
Member Function Documentation
void KviDynamicToolTip::maybeTip (const QPoint & pnt) [protected]
References tipRequest().
Referenced by KviDynamicToolTipHelper::maybeTip().
void KviDynamicToolTip::tip (const QRect & rct, const QString & text)
References m_pHelper, and KviTalToolTip::tip().
Referenced by KviTreeWindowList::tipRequest(), KviWindowListButton::tipRequest(), KviIrcContextDisplay::tipRequest(), and KviImageDialog::tipRequest().
void KviDynamicToolTip::tipRequest (KviDynamicToolTip * tip, const QPoint & pnt) [signal]
Referenced by maybeTip().
Friends And Related Function Documentation
friend class KviDynamicToolTipHelper [friend]
Referenced by KviDynamicToolTip().
Member Data Documentation
KviDynamicToolTipHelper* KviDynamicToolTip::m_pHelper [protected]
Referenced by KviDynamicToolTip(), tip(), and ~KviDynamicToolTip().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_dynamictooltip.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_dynamictooltip.cpp