KVIrc: KviKvsObjectStandardNothingReturnFunctionHandler Class Reference
KviKvsObjectStandardNothingReturnFunctionHandler Class Reference
#include <kvi_kvs_object_functionhandlerimpl.h>
Public Member Functions
virtual ~KviKvsObjectStandardNothingReturnFunctionHandler ()
Protected Member Functions
virtual bool call (KviKvsObject *pObject, KviKvsObjectFunctionCall *pCall)
virtual
KviKvsObjectFunctionHandler * clone ()
KviKvsObjectStandardNothingReturnFunctionHandler ()
Friends
class KviKvsObject
class KviKvsObjectClass
Constructor & Destructor Documentation
KviKvsObjectStandardNothingReturnFunctionHandler::KviKvsObjectStandardNothingReturnFunctionHandler () [inline, protected]
Referenced by clone().
virtual KviKvsObjectStandardNothingReturnFunctionHandler::~KviKvsObjectStandardNothingReturnFunctionHandler () [inline, virtual]
Member Function Documentation
bool KviKvsObjectStandardNothingReturnFunctionHandler::call (KviKvsObject * pObject, KviKvsObjectFunctionCall * pCall) [protected, virtual]
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setNothing().
KviKvsObjectFunctionHandler * KviKvsObjectStandardNothingReturnFunctionHandler::clone () [protected, virtual]
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectStandardNothingReturnFunctionHandler().
Friends And Related Function Documentation
friend class KviKvsObject [friend]
Reimplemented from KviKvsObjectFunctionHandler.
friend class KviKvsObjectClass [friend]
Reimplemented from KviKvsObjectFunctionHandler.
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_object_functionhandlerimpl.h
src/kvirc/kvs/kvi_kvs_object_functionhandlerimpl.cpp