KVIrc: RegisteredUsersGroupItem Class Reference
RegisteredUsersGroupItem Class Reference
#include <RegisteredUsersDialog.h>
Public Member Functions
KviRegisteredUserGroup * group ()
RegisteredUsersGroupItem (KviRegisteredUsersListView *par, KviRegisteredUserGroup *g)
~RegisteredUsersGroupItem ()
Public Member Functions inherited from RegisteredUsersDialogItemBase
RegisteredUsersDialogItemBase::Types type ()
Protected Attributes
KviRegisteredUserGroup * m_pGroup
Additional Inherited Members
Public Types inherited from RegisteredUsersDialogItemBase
enum Types { User, Group }
Protected Member Functions inherited from RegisteredUsersDialogItemBase
RegisteredUsersDialogItemBase (Types type, KviRegisteredUsersListView *par)
RegisteredUsersDialogItemBase (Types type, QTreeWidgetItem *par)
~RegisteredUsersDialogItemBase ()
Constructor & Destructor Documentation
RegisteredUsersGroupItem::RegisteredUsersGroupItem (KviRegisteredUsersListView * par, KviRegisteredUserGroup * g) inline
References m_pGroup, and KviRegisteredUserGroup::name().
RegisteredUsersGroupItem::~RegisteredUsersGroupItem () inline
Member Function Documentation
KviRegisteredUserGroup* RegisteredUsersGroupItem::group () inline
References m_pGroup.
Referenced by RegisteredUsersDialog::editClicked(), and RegisteredUsersDialog::itemDoubleClicked().
Member Data Documentation
KviRegisteredUserGroup* RegisteredUsersGroupItem::m_pGroup protected
Referenced by group(), and RegisteredUsersGroupItem().
The documentation for this class was generated from the following file:
src/modules/reguser/RegisteredUsersDialog.h