KVIrc: KviDebugContext Class Reference
KviDebugContext Class Reference
The KviDebugContext class.
#include <KviDebugContext.h>
Public Member Functions
KviDebugContext (const char *pcContext,...)
Creates an instance of KviDebugContext.
~KviDebugContext ()
Destroys the instance of KviDebugContext and frees all the relevant resources.
Static Public Member Functions
static void trace (const char *pcFmt,...)
Private Member Functions
const KviDebugContext & operator= (const KviDebugContext &)
Private Attributes
KviCString m_szContext
Detailed Description
The KviDebugContext class.
This class...
Constructor & Destructor Documentation
KviDebugContext::KviDebugContext (const char * pcContext, ...)
Creates an instance of KviDebugContext.
Parameters:
pcContext The format list argument
... The succeding arguments
Returns:
KviDebugContext
References KviCString::append(), g_szIndentPrefix, kvi_va_end, kvi_va_list, kvi_va_start, m_szContext, KviCString::ptr(), and KviCString::vsprintf().
KviDebugContext::~KviDebugContext ()
Destroys the instance of KviDebugContext and frees all the relevant resources.
References KviCString::append(), KviCString::cutRight(), g_szIndentPrefix, KVI_ASSERT, KviCString::len(), m_szContext, and KviCString::ptr().
Member Function Documentation
const KviDebugContext& KviDebugContext::operator= (const KviDebugContext &) [inline, private]
void KviDebugContext::trace (const char * pcFmt, ...) [static]
Parameters:
szFmt The format list argument
... The succeding arguments
Returns:
void
References KviCString::append(), g_szIndentPrefix, kvi_va_end, kvi_va_list, kvi_va_start, KviCString::ptr(), and KviCString::vsprintf().
Member Data Documentation
KviCString KviDebugContext::m_szContext [private]
Referenced by KviDebugContext(), and ~KviDebugContext().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviDebugContext.h
src/kvilib/ext/KviDebugContext.cpp