KVIrc: DccAcceptDialog Class Reference
DccAcceptDialog Class Reference
#include <DccDialog.h>
Signals
void accepted (DccDialog *, DccDescriptor *)
void rejected (DccDialog *, DccDescriptor *)
Public Member Functions
DccAcceptDialog (DccBroker *br, DccDescriptor *dcc, const QString &text, const QString &capt)
~DccAcceptDialog ()
Public Member Functions inherited from DccDialog
DccDialog (DccBroker *br, DccDescriptor *dcc)
virtual void forgetDescriptor ()
virtual ~DccDialog ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
virtual void showEvent (QShowEvent *e)
Private Slots
void acceptClicked ()
void rejectClicked ()
Additional Inherited Members
Protected Attributes inherited from DccDialog
DccBroker * m_pBroker
DccDescriptor * m_pDescriptor
Constructor & Destructor Documentation
DccAcceptDialog::DccAcceptDialog (DccBroker * br, DccDescriptor * dcc, const QString & text, const QString & capt)
References __tr2qs_ctx(), acceptClicked(), connect(), KviIconManager::DccMsg, g_pIconManager, KviIconManager::getSmallIcon(), l, and rejectClicked().
DccAcceptDialog::~DccAcceptDialog ()
Member Function Documentation
void DccAcceptDialog::acceptClicked () private slot
References accepted(), and DccDialog::m_pDescriptor.
Referenced by DccAcceptDialog().
void DccAcceptDialog::accepted (DccDialog * , DccDescriptor *) signal
Referenced by acceptClicked().
void DccAcceptDialog::closeEvent (QCloseEvent * e) protected virtual
References DccDialog::m_pDescriptor, and rejected().
void DccAcceptDialog::rejectClicked () private slot
References DccDialog::m_pDescriptor, and rejected().
Referenced by DccAcceptDialog().
void DccAcceptDialog::rejected (DccDialog * , DccDescriptor *) signal
Referenced by closeEvent(), and rejectClicked().
void DccAcceptDialog::showEvent (QShowEvent * e) protected virtual
References g_pApp, and KviMemory::move().
The documentation for this class was generated from the following files:
src/modules/dcc/DccDialog.h
src/modules/dcc/DccDialog.cpp