KVIrc: KviKvsTreeNodeScopeOperator Class Reference
KviKvsTreeNodeScopeOperator Class Reference
#include <KviKvsTreeNodeScopeOperator.h>
Public Member Functions
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeScopeOperator (const QChar *pLocation, KviKvsTreeNodeData *pObject, KviKvsTreeNodeData *pData)
~KviKvsTreeNodeScopeOperator ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Public Attributes
KviKvsTreeNodeData * m_pObjectReference
KviKvsTreeNodeData * m_pRightSide
Protected Member Functions
KviKvsObject * objectFromVariant (KviKvsRunTimeContext *c, KviKvsVariant *v)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Additional Inherited Members
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeScopeOperator::KviKvsTreeNodeScopeOperator (const QChar * pLocation, KviKvsTreeNodeData * pObject, KviKvsTreeNodeData * pData)
References m_pObjectReference, m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeScopeOperator::~KviKvsTreeNodeScopeOperator ()
References m_pObjectReference, and m_pRightSide.
Member Function Documentation
bool KviKvsTreeNodeScopeOperator::canEvaluateInObjectScope () virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::canEvaluateInObjectScope(), and m_pObjectReference.
bool KviKvsTreeNodeScopeOperator::canEvaluateToObjectReference () virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::canEvaluateToObjectReference(), and m_pRightSide.
void KviKvsTreeNodeScopeOperator::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeScopeOperator::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::dump(), m_pObjectReference, and m_pRightSide.
bool KviKvsTreeNodeScopeOperator::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), m_pObjectReference, m_pRightSide, o, and objectFromVariant().
bool KviKvsTreeNodeScopeOperator::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), m_pObjectReference, m_pRightSide, and objectFromVariant().
KviKvsRWEvaluationResult * KviKvsTreeNodeScopeOperator::evaluateReadWrite (KviKvsRunTimeContext * c) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), m_pObjectReference, m_pRightSide, o, and objectFromVariant().
KviKvsRWEvaluationResult * KviKvsTreeNodeScopeOperator::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), m_pObjectReference, m_pRightSide, and objectFromVariant().
bool KviKvsTreeNodeScopeOperator::isFunctionCall () virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::isFunctionCall(), and m_pRightSide.
bool KviKvsTreeNodeScopeOperator::isReadOnly () virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::isReadOnly(), and m_pRightSide.
KviKvsObject * KviKvsTreeNodeScopeOperator::objectFromVariant (KviKvsRunTimeContext * c, KviKvsVariant * v) protected
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsRunTimeContext::error(), KviKvsKernel::instance(), KviKvsObjectController::lookupObject(), o, and KviKvsKernel::objectController().
Referenced by evaluateReadOnly(), evaluateReadOnlyInObjectScope(), evaluateReadWrite(), and evaluateReadWriteInObjectScope().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeScopeOperator::m_pObjectReference
Referenced by canEvaluateInObjectScope(), dump(), evaluateReadOnly(), evaluateReadOnlyInObjectScope(), evaluateReadWrite(), evaluateReadWriteInObjectScope(), KviKvsTreeNodeScopeOperator(), and ~KviKvsTreeNodeScopeOperator().
KviKvsTreeNodeData* KviKvsTreeNodeScopeOperator::m_pRightSide
Referenced by canEvaluateToObjectReference(), dump(), evaluateReadOnly(), evaluateReadOnlyInObjectScope(), evaluateReadWrite(), evaluateReadWriteInObjectScope(), isFunctionCall(), isReadOnly(), KviKvsTreeNodeScopeOperator(), and ~KviKvsTreeNodeScopeOperator().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeScopeOperator.h
src/kvirc/kvs/tree/KviKvsTreeNodeScopeOperator.cpp