KVIrc: KviKvsRunTimeCall Class Reference
KviKvsRunTimeCall Class Reference
#include <KviKvsRunTimeCall.h>
Public Member Functions
KviKvsRunTimeContext * context ()
void enterBlockingSection ()
bool error (const QString &szFmt,...)
KviKvsVariant * firstParam ()
virtual bool getParameterCode (unsigned int uParamIdx, QString &szParamBuffer)
KviKvsRunTimeCall (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool leaveBlockingSection ()
KviKvsVariant * nextParam ()
unsigned int paramCount ()
unsigned int parameterCount ()
KviKvsVariantList * parameterList ()
KviKvsVariantList * params ()
void warning (const QString &szFmt,...)
KviWindow * window ()
virtual ~KviKvsRunTimeCall ()
Protected Attributes
KviKvsRunTimeContext * m_pContext
KviKvsVariantList * m_pParams
Constructor & Destructor Documentation
KviKvsRunTimeCall::KviKvsRunTimeCall (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) inline
virtual KviKvsRunTimeCall::~KviKvsRunTimeCall () inline virtual
Member Function Documentation
KviKvsRunTimeContext* KviKvsRunTimeCall::context () inline
Referenced by KviKvsObject::emitSignal(), KviKvsObject::function_listProperties(), links_kvs_cmd_open(), list_kvs_cmd_open(), perl_kvs_cmd_begin(), popup_kvs_fnc_currentItemId(), python_kvs_cmd_begin(), socketspy_kvs_cmd_open(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), and tmphighlight_kvs_fnc_isnickhighlighted().
void KviKvsRunTimeCall::enterBlockingSection () inline
Referenced by dialog_kvs_fnc_yesno(), and theme_kvs_cmd_screenshot().
bool KviKvsRunTimeCall::error (const QString & szFmt, ...)
References KviKvsRunTimeContext::defaultReportLocation(), kvi_va_end, kvi_va_list, kvi_va_start_by_reference, m_pContext, and KviKvsRunTimeContext::report().
Referenced by action_kvs_cmd_create(), addon_kvs_cmd_install(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_register(), chan_kvs_fnc_getUrl(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_send(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_fnc_ircContext(), dcc_kvs_parse_default_parameters(), file_kvs_cmd_writeBytes(), KvsObject_textedit::functionsetColor(), log_kvs_fnc_export(), my_kvs_fnc_globalIdle(), perl_kvs_cmd_begin(), PluginManager::pluginCall(), popup_kvs_cmd_show(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), proxydb_kvs_fnc_protocol(), python_kvs_cmd_begin(), serverdb_kvs_cmd_addNetwork(), serverdb_kvs_cmd_addServer(), serverdb_kvs_fnc_networkExists(), serverdb_kvs_fnc_serverExists(), system_kvs_cmd_runcmd(), system_kvs_fnc_htoni(), system_kvs_fnc_ntohi(), theme_kvs_cmd_install(), theme_kvs_cmd_screenshot(), and toolbar_kvs_cmd_removeitem().
KviKvsVariant* KviKvsRunTimeCall::firstParam () inline
Referenced by urllist_module_event_onUrl().
bool KviKvsRunTimeCall::getParameterCode (unsigned int uParamIdx, QString & szParamBuffer) virtual
Reimplemented in KviKvsModuleCallbackCommandCall.
bool KviKvsRunTimeCall::leaveBlockingSection () inline
Referenced by dialog_kvs_fnc_yesno(), and theme_kvs_cmd_screenshot().
KviKvsVariant* KviKvsRunTimeCall::nextParam () inline
unsigned int KviKvsRunTimeCall::paramCount () inline
unsigned int KviKvsRunTimeCall::parameterCount () inline
Referenced by chan_kvs_fnc_common(), context_kvs_fnc_getSSLCertInfo(), and PluginManager::pluginCall().
KviKvsVariantList* KviKvsRunTimeCall::parameterList () inline
Referenced by tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_fnc_ischannelhighlighted(), window_kvs_cmd_highlight(), and window_kvs_fnc_open().
KviKvsVariantList* KviKvsRunTimeCall::params () inline
Referenced by KviKvsObjectScriptFunctionHandler::call(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), KvsObject_http::functionDataReadProgressEvent(), KvsObject_http::functionDataSendProgressEvent(), KvsObject_http::functionDoneEvent(), KvsObject_http::functionReadyReadEvent(), KvsObject_http::functionRequestFinishedEvent(), KvsObject_http::functionRequestStartedEvent(), KvsObject_http::functionResponseHeaderReceivedEvent(), KvsObject_textedit::functionsetColor(), KvsObject_http::functionSslErrorsEvent(), KvsObject_http::functionStateChangedEvent(), PluginManager::pluginCall(), popup_kvs_cmd_show(), and str_kvs_fnc_split().
void KviKvsRunTimeCall::warning (const QString & szFmt, ...)
References KviKvsRunTimeContext::defaultReportLocation(), kvi_va_end, kvi_va_list, kvi_va_start_by_reference, m_pContext, and KviKvsRunTimeContext::report().
Referenced by action_kvs_cmd_create(), action_kvs_cmd_destroy(), action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_trigger(), addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), avatar_kvs_cmd_notify(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), chan_kvs_find_channel(), config_kvs_cmd_clear(), config_kvs_cmd_clearsection(), config_kvs_cmd_close(), config_kvs_cmd_flush(), config_kvs_cmd_setsection(), config_kvs_cmd_write(), config_kvs_fnc_hassection(), config_kvs_fnc_keylist(), config_kvs_fnc_read(), config_kvs_fnc_readonly(), config_kvs_fnc_section(), config_kvs_fnc_sectionlist(), context_kvs_fnc_getSSLCertInfo(), dcc_kvs_cmd_get(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_setBandwidthLimit(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_find_dcc_descriptor(), dcc_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_session(), dcc_kvs_get_listen_ip_address(), dcc_kvs_parse_default_parameters(), default_module_kvs_cmd_unload(), KviKvsObject::emitSignal(), file_kvs_cmd_copy(), file_kvs_cmd_mkdir(), file_kvs_cmd_remove(), file_kvs_cmd_rename(), file_kvs_cmd_rmdir(), file_kvs_cmd_write(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), file_kvs_fnc_allSizes(), file_kvs_fnc_digest(), file_kvs_fnc_ls(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), file_kvs_fnc_time(), KviKvsObject::function_property(), KviKvsObject::function_setProperty(), KvsObject_http::functionGet(), KvsObject_textedit::functionloadFile(), KvsObject_textedit::functionsetAlignment(), KvsObject_textedit::functionsetColor(), KvsObject_textedit::functionsetTextFormat(), KvsObject_textedit::functionSetWordWrap(), KvsObject_textedit::functionTextLine(), http_kvs_complete_get(), links_kvs_cmd_open(), list_kvs_cmd_open(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), log_kvs_fnc_file(), notifier_kvs_cmd_message(), objects_kvs_cmd_connect(), objects_kvs_cmd_disconnect(), objects_kvs_cmd_killClass(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_instances(), objects_kvs_fnc_name(), objects_kvs_fnc_variables(), options_kvs_cmd_edit(), perl_kvs_cmd_begin(), perl_kvs_cmd_destroy(), PluginManager::pluginCall(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_create(), popup_kvs_cmd_delItem(), popup_kvs_cmd_destroy(), popup_kvs_cmd_show(), popup_kvs_fnc_exists(), python_kvs_cmd_begin(), python_kvs_cmd_destroy(), regchan_kvs_cmd_remove(), regchan_kvs_cmd_setProperty(), reguser_kvs_cmd_add(), reguser_kvs_cmd_addmask(), reguser_kvs_cmd_delmask(), reguser_kvs_cmd_remove(), reguser_kvs_cmd_setIgnoreEnabled(), reguser_kvs_cmd_setIgnoreFlags(), reguser_kvs_cmd_setproperty(), sharedfile_kvs_cmd_add(), sharedfile_kvs_cmd_remove(), snd_kvs_cmd_play(), spaste_kvs_cmd_file(), spaste_kvs_cmd_stop(), spaste_kvs_find_window(), str_kvs_fnc_digest(), str_kvs_fnc_evpSign(), str_kvs_fnc_evpVerify(), str_kvs_fnc_printf(), system_kvs_fnc_dbus(), term_kvs_cmd_open(), texticons_kvs_fnc_get(), theme_kvs_cmd_apply(), theme_kvs_fnc_info(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), tmphighlight_kvs_fnc_isnickhighlighted(), toolbar_kvs_cmd_additem(), toolbar_kvs_cmd_clear(), toolbar_kvs_cmd_destroy(), toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_removeitem(), toolbar_kvs_cmd_show(), toolbar_kvs_fnc_items(), userlist_kvs_cmd_ensureVisible(), userlist_kvs_cmd_select(), userlist_kvs_fnc_selected(), window_kvs_cmd_highlight(), window_kvs_cmd_insertInInputText(), window_kvs_cmd_setBackground(), window_kvs_cmd_setCryptEngine(), window_kvs_cmd_setInputText(), window_kvs_cmd_setWindowTitle(), window_kvs_fnc_list(), and window_kvs_fnc_open().
KviWindow* KviKvsRunTimeCall::window () inline
Referenced by action_kvs_cmd_list(), addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_list(), addon_kvs_cmd_register(), addon_kvs_cmd_uninstall(), avatar_kvs_cmd_notify(), avatar_kvs_cmd_query(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KviKvsObjectScriptFunctionHandler::call(), chan_kvs_find_channel(), chan_kvs_fnc_common(), chan_kvs_fnc_getUrl(), channelsjoin_kvs_cmd_open(), context_kvs_cmd_clearQueue(), context_kvs_fnc_getSSLCertInfo(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_find_dcc_descriptor(), dcc_kvs_fnc_session(), dialog_kvs_cmd_file(), dialog_kvs_cmd_image(), dialog_kvs_cmd_message(), dialog_kvs_cmd_textinput(), links_kvs_cmd_open(), list_kvs_cmd_open(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), log_kvs_fnc_file(), notifier_kvs_cmd_message(), objects_kvs_fnc_listObjects(), options_kvs_module_print_pages(), popup_kvs_cmd_show(), regchan_kvs_cmd_showlist(), reguser_kvs_cmd_showlist(), sharedfile_kvs_cmd_list(), snd_kvs_cmd_autodetect(), socketspy_kvs_cmd_open(), spaste_kvs_cmd_list(), spaste_kvs_cmd_stop(), spaste_kvs_find_window(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), tmphighlight_kvs_fnc_isnickhighlighted(), urllist_module_event_onUrl(), window_kvs_cmd_highlight(), window_kvs_cmd_listtypes(), and window_kvs_fnc_list().
Member Data Documentation
KviKvsRunTimeContext* KviKvsRunTimeCall::m_pContext protected
Referenced by error(), and warning().
KviKvsVariantList* KviKvsRunTimeCall::m_pParams protected
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsRunTimeCall.h
src/kvirc/kvs/KviKvsRunTimeCall.cpp