KVIrc: OptionsWidget_windowListTreeFeatures Class Reference
OptionsWidget_windowListTreeFeatures Class Reference
#include <OptionsWidget_windowList.h>
Public Member Functions
OptionsWidget_windowListTreeFeatures (QWidget *parent)
~OptionsWidget_windowListTreeFeatures ()
Constructor & Destructor Documentation
OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::createLayout(), KviOption_boolWheelScrollsWindowsList, and KviOption_uintTreeWindowListMinimumWidth.
OptionsWidget_windowListTreeFeatures::~OptionsWidget_windowListTreeFeatures ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_windowList.h
src/modules/options/OptionsWidget_windowList.cpp