KVIrc: KviKvsUserAction Class Reference
KviKvsUserAction Class Reference
#include <KviKvsUserAction.h>
Public Member Functions
const QString & category ()
virtual const QString & description ()
Returns the description of the action.
const QString & descriptionCode ()
void exportToKvs (QString &szBuffer)
KviKvsUserAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleNameCode, const QString &szDescriptionCode, const QString &szCategory, const QString &szBigIconId, const QString &szSmallIconId, unsigned int uFlags, const QString &szKeySequence=QString())
KviKvsUserAction (QObject *pParent)
void suicide ()
virtual const QString & visibleName ()
Returns the visible name of the action.
const QString & visibleNameCode ()
~KviKvsUserAction ()
Public Member Functions inherited from KviKvsAction
virtual void activate ()
Executes the action.
KviKvsAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Contructs the action object.
KviKvsAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), KviIconManager::SmallIcon eSmallIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Contructs the action object.
const QString & scriptCode ()
Returns the code of the script contained in the action.
virtual ~KviKvsAction ()
Destroys the action object.
Public Member Functions inherited from KviAction
virtual QAction * addToCustomToolBar (KviCustomToolBar *pParentToolBar)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
QPixmap * bigIcon ()
Returns the big icon associated to the action.
const QString & bigIconId () const
Returns the id of the big icon associated to the action.
KviActionCategory * category () const
Returns the category of the action.
unsigned int flags ()
Returns the flag associated to the action.
bool isEnabled () const
Returns true if the action is enabled.
const QString & keySequence () const
Returns the shortcut of the action.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), KviIconManager::SmallIcon eSmallIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
const QString & name () const
Returns the name of the action.
virtual void setEnabled (bool bEnabled)
Enables the action.
QPixmap * smallIcon ()
Returns the small icon associated to the action.
const QString & smallIconId () const
Returns the id of the small icon associated to the action.
void suicide ()
Destroys itself. Maybe the best function in the whole APIs :)
virtual ~KviAction ()
Destroys the action object.
Static Public Member Functions
static KviKvsUserAction * createInstance (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleNameCode, const QString &szDescriptionCode, const QString &szCategory, const QString &szBigIconId, const QString &szSmallIcon, unsigned int uFlags, const QString &szKeySequence=QString())
static void exportToKvs (QString &szBuffer, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, const QString &szCategory, const QString &szBigIcon, const QString &szSmallIcon, unsigned int uFlags, const QString &szKeySequence)
Static Public Member Functions inherited from KviAction
static int validateFlags (int iFlagsToValidate)
Validates the flags of the action.
Protected Member Functions
virtual bool isKviUserActionNeverOverrideThis ()
Returns true if the action is user-defined.
bool load (KviConfigurationFile *pCfg)
void save (KviConfigurationFile *pCfg)
Protected Member Functions inherited from KviAction
KviPointerList< QAction > * actionList ()
Returns the list of actions associated to the action.
void registerAccelerator ()
Registers the action shortcut in the application.
void registerAction (QAction *pAction)
Adds the action to the list.
virtual void setup ()
Enables or disables the action upon starting KVIrc.
bool setupDone () const
Returns true if the setup is finished.
void unregisterAccelerator ()
Removes the action shortcut from the application.
Protected Attributes
KviKvsScript * m_pDescriptionScript
KviKvsScript * m_pVisibleNameScript
QString m_szCategory
Protected Attributes inherited from KviKvsAction
QString m_szScript
Protected Attributes inherited from KviAction
KviIconManager::SmallIcon m_eSmallIcon
QPointer< QShortcut > m_pAccel
KviPointerList< QAction > * m_pActionList
KviActionCategory * m_pCategory
QString m_szBigIconId
QString m_szDescription
QString m_szKeySequence
QString m_szName
QString m_szSmallIconId
QString m_szVisibleName
unsigned int m_uFlags
unsigned short int m_uInternalFlags
Friends
class KviActionManager
Additional Inherited Members
Public Types inherited from KviAction
enum Flags {
NeedsContext = 1, NeedsConnection = 2, WindowConsole = 4, WindowChannel = 8,
WindowQuery = 16, WindowDccChat = 32, InternalWindowMask = WindowConsole | WindowChannel | WindowQuery | WindowDccChat, EnableAtLogin = 64,
WindowOnlyIfUsersSelected = 128
}
Holds the flags of an action.
enum InternalFlags { Enabled = 1, SetupDone = 2 }
Holds the internal flags of an action.
Public Slots inherited from KviAction
Signals inherited from KviAction
void activated ()
Emitted when the action is being activated.
Protected Slots inherited from KviAction
virtual void actionDestroyed ()
Removes the action from the list.
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual void activeWindowChanged ()
Enables or disables the action upon checking the active window.
virtual void activeWindowSelectionStateChanged (bool bSelectedNow)
Enables or disables the action upon checking the active window.
virtual void reloadImages ()
Reloads the images.
Constructor & Destructor Documentation
KviKvsUserAction::KviKvsUserAction (QObject * pParent, const QString & szName, const QString & szScriptCode, const QString & szVisibleNameCode, const QString & szDescriptionCode, const QString & szCategory, const QString & szBigIconId, const QString & szSmallIconId, unsigned int uFlags, const QString & szKeySequence = QString())
References KviActionManager::category(), KviActionManager::instance(), KviAction::m_pCategory, m_pDescriptionScript, m_pVisibleNameScript, m_szCategory, and KviKvsScript::Parameter.
Referenced by createInstance().
KviKvsUserAction::KviKvsUserAction (QObject * pParent)
References m_pDescriptionScript, and m_pVisibleNameScript.
KviKvsUserAction::~KviKvsUserAction ()
References m_pDescriptionScript, and m_pVisibleNameScript.
Member Function Documentation
const QString& KviKvsUserAction::category () inline
KviKvsUserAction * KviKvsUserAction::createInstance (QObject * pParent, const QString & szName, const QString & szScriptCode, const QString & szVisibleNameCode, const QString & szDescriptionCode, const QString & szCategory, const QString & szBigIconId, const QString & szSmallIcon, unsigned int uFlags, const QString & szKeySequence = QString()) static
References KviKvsUserAction().
Referenced by action_kvs_cmd_create(), and ActionEditor::commit().
const QString & KviKvsUserAction::description () virtual
Returns the description of the action.
Returns
const QString &
Reimplemented from KviAction.
References KviKvsScript::code(), g_pActiveWindow, m_pDescriptionScript, KviAction::m_szDescription, and KviKvsScript::run().
const QString & KviKvsUserAction::descriptionCode ()
References KviKvsScript::code(), m_pDescriptionScript, and KviAction::m_szDescription.
Referenced by exportToKvs().
void KviKvsUserAction::exportToKvs (QString & szBuffer, const QString & szName, const QString & szScriptCode, const QString & szVisibleName, const QString & szDescription, const QString & szCategory, const QString & szBigIcon, const QString & szSmallIcon, unsigned int uFlags, const QString & szKeySequence) static
References KviCommandFormatter::blockFromBuffer(), KviAction::EnableAtLogin, KviAction::InternalWindowMask, KviAction::NeedsConnection, KviAction::NeedsContext, KviAction::WindowChannel, KviAction::WindowConsole, KviAction::WindowDccChat, KviAction::WindowOnlyIfUsersSelected, and KviAction::WindowQuery.
Referenced by ActionEditor::exportActions(), and exportToKvs().
void KviKvsUserAction::exportToKvs (QString & szBuffer)
References descriptionCode(), exportToKvs(), KviAction::m_szBigIconId, m_szCategory, KviAction::m_szKeySequence, KviAction::m_szName, KviAction::m_szSmallIconId, KviAction::m_uFlags, KviKvsAction::scriptCode(), and visibleNameCode().
bool KviKvsUserAction::isKviUserActionNeverOverrideThis () protected virtual
Returns true if the action is user-defined.
Warning
By default, this function returns always false
Returns
bool
Reimplemented from KviAction.
bool KviKvsUserAction::load (KviConfigurationFile * pCfg) protected
References KviActionManager::category(), KviConfigurationFile::group(), KviActionManager::instance(), KviAction::m_pCategory, m_pDescriptionScript, m_pVisibleNameScript, KviAction::m_szBigIconId, m_szCategory, KviAction::m_szDescription, KviAction::m_szKeySequence, KviAction::m_szName, KviKvsAction::m_szScript, KviAction::m_szSmallIconId, KviAction::m_szVisibleName, KviAction::m_uFlags, KviKvsScript::Parameter, KviConfigurationFile::readEntry(), and KviConfigurationFile::readUIntEntry().
Referenced by KviActionManager::load().
void KviKvsUserAction::save (KviConfigurationFile * pCfg) protected
References KviKvsScript::code(), m_pDescriptionScript, m_pVisibleNameScript, KviAction::m_szBigIconId, m_szCategory, KviAction::m_szKeySequence, KviAction::m_szName, KviKvsAction::m_szScript, KviAction::m_szSmallIconId, KviAction::m_uFlags, KviConfigurationFile::setGroup(), and KviConfigurationFile::writeEntry().
void KviKvsUserAction::suicide () inline
const QString & KviKvsUserAction::visibleName () virtual
Returns the visible name of the action.
Returns
const QString &
Reimplemented from KviAction.
References KviKvsScript::code(), g_pActiveWindow, m_pVisibleNameScript, KviAction::m_szVisibleName, and KviKvsScript::run().
const QString & KviKvsUserAction::visibleNameCode ()
References KviKvsScript::code(), m_pVisibleNameScript, and KviAction::m_szVisibleName.
Referenced by exportToKvs().
Friends And Related Function Documentation
friend class KviActionManager friend
Member Data Documentation
KviKvsScript* KviKvsUserAction::m_pDescriptionScript protected
Referenced by description(), descriptionCode(), KviKvsUserAction(), load(), save(), and ~KviKvsUserAction().
KviKvsScript* KviKvsUserAction::m_pVisibleNameScript protected
Referenced by KviKvsUserAction(), load(), save(), visibleName(), visibleNameCode(), and ~KviKvsUserAction().
QString KviKvsUserAction::m_szCategory protected
Referenced by exportToKvs(), KviKvsUserAction(), load(), and save().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsUserAction.h
src/kvirc/kvs/KviKvsUserAction.cpp