KVIrc: KviKvsAsyncDnsOperation Class Reference
KviKvsAsyncDnsOperation Class Reference
#include <KviKvsAsyncDnsOperation.h>
Public Member Functions
KviKvsAsyncDnsOperation (KviWindow *pWnd, QString &szQuery, KviDnsResolver::QueryType eType, KviKvsScript *pCallback=0, KviKvsVariant *pMagic=0)
virtual ~KviKvsAsyncDnsOperation ()
Public Member Functions inherited from KviKvsAsyncOperation
KviKvsAsyncOperation (KviWindow *pWnd)
KviWindow * window ()
virtual ~KviKvsAsyncOperation ()
Protected Slots
void dnsStartFailed ()
void lookupTerminated (KviDnsResolver *)
Protected Attributes
KviDnsResolver::QueryType m_eType
KviKvsScript * m_pCallback
KviDnsResolver * m_pDns
KviKvsVariant * m_pMagic
QString m_szQuery
Protected Attributes inherited from KviKvsAsyncOperation
KviWindow * m_pWnd
Constructor & Destructor Documentation
KviKvsAsyncDnsOperation::KviKvsAsyncDnsOperation (KviWindow * pWnd, QString & szQuery, KviDnsResolver::QueryType eType, KviKvsScript * pCallback = 0, KviKvsVariant * pMagic = 0)
References connect(), dnsStartFailed(), KviDnsResolver::lookup(), lookupTerminated(), m_eType, m_pCallback, m_pDns, m_pMagic, and m_szQuery.
KviKvsAsyncDnsOperation::~KviKvsAsyncDnsOperation () virtual
References m_pCallback, m_pDns, and m_pMagic.
Member Function Documentation
void KviKvsAsyncDnsOperation::dnsStartFailed () protected slot
References lookupTerminated(), and m_pDns.
Referenced by KviKvsAsyncDnsOperation().
void KviKvsAsyncDnsOperation::lookupTerminated (KviDnsResolver *) protected slot
References __tr2qs_ctx(), a, KviKvsVariantList::append(), KviDnsResolver::errorString(), KviDnsResolver::Failure, KviPointerList< T >::first(), g_pActiveWindow, g_pApp, KviDnsResolver::hostName(), KviDnsResolver::ipAddressList(), KVI_OUT_HOSTLOOKUP, m_pCallback, m_pDns, m_pMagic, m_szQuery, KviPointerList< T >::next(), KviWindow::output(), KviKvsScript::PreserveParams, KviDnsResolver::query(), KviKvsScript::run(), KviKvsVariantList::setAutoDelete(), KviDnsResolver::state(), KviKvsAsyncOperation::window(), and KviApplication::windowExists().
Referenced by dnsStartFailed(), and KviKvsAsyncDnsOperation().
Member Data Documentation
KviDnsResolver::QueryType KviKvsAsyncDnsOperation::m_eType protected
Referenced by KviKvsAsyncDnsOperation().
KviKvsScript* KviKvsAsyncDnsOperation::m_pCallback protected
Referenced by KviKvsAsyncDnsOperation(), lookupTerminated(), and ~KviKvsAsyncDnsOperation().
KviDnsResolver* KviKvsAsyncDnsOperation::m_pDns protected
Referenced by dnsStartFailed(), KviKvsAsyncDnsOperation(), lookupTerminated(), and ~KviKvsAsyncDnsOperation().
KviKvsVariant* KviKvsAsyncDnsOperation::m_pMagic protected
Referenced by KviKvsAsyncDnsOperation(), lookupTerminated(), and ~KviKvsAsyncDnsOperation().
QString KviKvsAsyncDnsOperation::m_szQuery protected
Referenced by KviKvsAsyncDnsOperation(), and lookupTerminated().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsAsyncDnsOperation.h
src/kvirc/kvs/KviKvsAsyncDnsOperation.cpp