KVIrc: KviStatusBarMessage Class Reference
KviStatusBarMessage Class Reference
A class that hold the statusbar message.
#include <kvi_statusbar.h>
Public Member Functions
KviStatusBarMessage (const QString &szText, unsigned int uTimeout=8000, unsigned int uPriority=0)
Constructs the statusbar message object.
unsigned int priority ()
Returns the priority of the message.
const QString & text ()
Returns the text of the message.
unsigned int timeout ()
Returns the timeout of the message.
~KviStatusBarMessage ()
Destroys the statusbar message object.
Protected Attributes
QString m_szText
unsigned int m_uPriority
unsigned int m_uTimeout
Friends
class KviStatusBar
Detailed Description
A class that hold the statusbar message.
Constructor & Destructor Documentation
KviStatusBarMessage::KviStatusBarMessage (const QString & szText, unsigned int uTimeout = 8000, unsigned int uPriority = 0) [inline]
Constructs the statusbar message object.
Parameters:
szText The text of the message
uTimeout The timeout of the message
uPriority The priority of the message
Returns:
KviStatusBarMessage
KviStatusBarMessage::~KviStatusBarMessage () [inline]
Destroys the statusbar message object.
Member Function Documentation
unsigned int KviStatusBarMessage::priority () [inline]
Returns the priority of the message.
Returns:
unsigned int
Referenced by KviStatusBar::queueMessage().
const QString& KviStatusBarMessage::text () [inline]
Returns the text of the message.
Returns:
const QString &
Referenced by KviStatusBar::showFirstMessageInQueue().
unsigned int KviStatusBarMessage::timeout () [inline]
Returns the timeout of the message.
Returns:
unsigned int
Referenced by KviStatusBar::showFirstMessageInQueue().
Friends And Related Function Documentation
friend class KviStatusBar [friend]
Member Data Documentation
QString KviStatusBarMessage::m_szText [protected]
unsigned int KviStatusBarMessage::m_uPriority [protected]
unsigned int KviStatusBarMessage::m_uTimeout [protected]
The documentation for this class was generated from the following file:
src/kvirc/ui/kvi_statusbar.h