KVIrc: ChannelsJoinDialog Class Reference
ChannelsJoinDialog Class Reference
Channels join window class.
#include <ChannelsJoinDialog.h>
Public Member Functions
ChannelsJoinDialog (QWidget *par, const char *name)
Constructs the channels join window.
virtual void closeEvent (QCloseEvent *e)
void enableJoin ()
Enables join and register button if channel is found.
void fillListView ()
Fills in the servers' list.
void itemSelected ()
Called when the user choose an item from the list.
void setConsole (KviConsoleWindow *pConsole)
Sets the console and fills in the servers' list.
~ChannelsJoinDialog ()
Destroys the channels join window.
Protected Types
enum ItemTypes { HeaderItem, RecentChannelItem, RegisteredChannelItem }
Protected Slots
void cancelClicked ()
Called when the cancel button is pressed.
void clearClicked ()
Called when the clear button is pressed.
void deleteClicked ()
Called when the delete button is pressed.
void editReturnPressed ()
Called when the return is pressed.
void editTextChanged (const QString &)
Called when the text changes.
void joinClicked ()
Called when the join button is pressed.
void regClicked ()
Called when the register button is pressed.
Protected Attributes
QLineEdit * m_pChannelEdit
QPushButton * m_pClearButton
QCheckBox * m_pCloseAfterJoinCheck
KviConsoleWindow * m_pConsole
KviTalGroupBox * m_pGroupBox
QPushButton * m_pJoinButton
QLineEdit * m_pPass
QPushButton * m_pRegButton
QCheckBox * m_pShowAtStartupCheck
ChannelsJoinDialogTreeWidget * m_pTreeWidget
Friends
class ChannelsJoinDialogTreeWidget
Detailed Description
Channels join window class.
Member Enumeration Documentation
enum ChannelsJoinDialog::ItemTypes [protected]
Enumerator:
HeaderItem
RecentChannelItem
RegisteredChannelItem
Constructor & Destructor Documentation
ChannelsJoinDialog::ChannelsJoinDialog (QWidget * par, const char * name)
Constructs the channels join window.
Parameters:
par The parent widget
name The name of the window
Returns:
ChannelsJoinDialog
References __tr2qs, cancelClicked(), KviIconManager::Channel, ChannelsJoinDialogTreeWidget, clearClicked(), connect(), editReturnPressed(), editTextChanged(), enableJoin(), fillListView(), g, g_pApp, g_pIconManager, g_pMainWindow, g_rectChannelsJoinGeometry, KviIconManager::getSmallIcon(), joinClicked(), KVI_OPTION_BOOL, KviOption_boolShowChannelsJoinOnIrc, m_pChannelEdit, m_pClearButton, m_pConsole, m_pGroupBox, m_pJoinButton, m_pPass, m_pRegButton, m_pShowAtStartupCheck, m_pTreeWidget, KviMemory::move(), regClicked(), and KviTalHBox::setSpacing().
ChannelsJoinDialog::~ChannelsJoinDialog ()
Destroys the channels join window.
References g_rectChannelsJoinGeometry, KVI_OPTION_BOOL, KviOption_boolShowChannelsJoinOnIrc, m_pShowAtStartupCheck, x, and y.
Member Function Documentation
void ChannelsJoinDialog::cancelClicked () [protected, slot]
Called when the cancel button is pressed.
It destroys the window object
Returns:
void
Referenced by ChannelsJoinDialog().
void ChannelsJoinDialog::clearClicked () [protected, slot]
Called when the clear button is pressed.
It clears the list of recent channels
Returns:
void
References c, KviWindow::console(), fillListView(), g_pActiveWindow, g_pApp, KviIrcUrl::run(), KviApplication::topmostConnectedConsole(), and w.
Referenced by ChannelsJoinDialog().
void ChannelsJoinDialog::closeEvent (QCloseEvent * e) [virtual]
void ChannelsJoinDialog::deleteClicked () [protected, slot]
Called when the delete button is pressed.
It deletes the selected channel
Returns:
void
References KviRegisteredChannelDataBase::find(), KviPointerHashTable< Key, T >::first(), g_pApp, g_pRegisteredChannelDataBase, HeaderItem, m_pTreeWidget, KviPointerHashTable< Key, T >::next(), RecentChannelItem, KviApplication::recentChannels(), RegisteredChannelItem, and KviRegisteredChannelDataBase::remove().
void ChannelsJoinDialog::editReturnPressed () [protected, slot]
Called when the return is pressed.
It joins the selected channel
Returns:
void
References joinClicked().
Referenced by ChannelsJoinDialog().
void ChannelsJoinDialog::editTextChanged (const QString &) [protected, slot]
Called when the text changes.
Returns:
void
References enableJoin().
Referenced by ChannelsJoinDialog().
void ChannelsJoinDialog::enableJoin ()
Enables join and register button if channel is found.
Returns:
void
References c, g_pApp, m_pChannelEdit, m_pGroupBox, m_pJoinButton, m_pRegButton, m_pTreeWidget, and KviApplication::topmostConnectedConsole().
Referenced by ChannelsJoinDialog(), editTextChanged(), and itemSelected().
void ChannelsJoinDialog::fillListView ()
Fills in the servers' list.
Returns:
void
References __tr2qs, KviIconManager::Channel, KviRegisteredChannelDataBase::channelDict(), KviConsoleWindow::currentNetworkName(), d, KviPointerHashTable< Key, T >::first(), g_pApp, g_pIconManager, g_pRegisteredChannelDataBase, KviIconManager::getSmallIcon(), HeaderItem, m_pConsole, m_pTreeWidget, KviPointerHashTable< Key, T >::next(), RecentChannelItem, KviApplication::recentChannels(), KviApplication::recentChannelsForNetwork(), and RegisteredChannelItem.
Referenced by ChannelsJoinDialog(), clearClicked(), regClicked(), and setConsole().
void ChannelsJoinDialog::itemSelected ()
Called when the user choose an item from the list.
Returns:
void
References enableJoin(), HeaderItem, m_pChannelEdit, and m_pTreeWidget.
void ChannelsJoinDialog::joinClicked () [protected, slot]
Called when the join button is pressed.
It joins the selected channel
Returns:
void
References c, KviWindow::console(), KviQString::escapeKvs(), g_pActiveWindow, g_pApp, m_pChannelEdit, m_pPass, KviIrcUrl::run(), KviApplication::topmostConnectedConsole(), and w.
Referenced by ChannelsJoinDialog(), and editReturnPressed().
void ChannelsJoinDialog::regClicked () [protected, slot]
Called when the register button is pressed.
It registers the selected channel in the database
Returns:
void
References c, KviWindow::console(), KviQString::escapeKvs(), fillListView(), g_pActiveWindow, g_pApp, m_pChannelEdit, m_pTreeWidget, KviIrcUrl::run(), KviApplication::topmostConnectedConsole(), and w.
Referenced by ChannelsJoinDialog().
void ChannelsJoinDialog::setConsole (KviConsoleWindow * pConsole)
Sets the console and fills in the servers' list.
Parameters:
pConsole The source console
Returns:
void
References fillListView(), and m_pConsole.
Referenced by channelsjoin_kvs_cmd_open().
Friends And Related Function Documentation
friend class ChannelsJoinDialogTreeWidget [friend]
Referenced by ChannelsJoinDialog().
Member Data Documentation
QLineEdit* ChannelsJoinDialog::m_pChannelEdit [protected]
Referenced by ChannelsJoinDialog(), enableJoin(), itemSelected(), joinClicked(), and regClicked().
QPushButton* ChannelsJoinDialog::m_pClearButton [protected]
Referenced by ChannelsJoinDialog().
QCheckBox* ChannelsJoinDialog::m_pCloseAfterJoinCheck [protected]
KviConsoleWindow* ChannelsJoinDialog::m_pConsole [protected]
Referenced by ChannelsJoinDialog(), fillListView(), and setConsole().
KviTalGroupBox* ChannelsJoinDialog::m_pGroupBox [protected]
Referenced by ChannelsJoinDialog(), and enableJoin().
QPushButton* ChannelsJoinDialog::m_pJoinButton [protected]
Referenced by ChannelsJoinDialog(), and enableJoin().
QLineEdit* ChannelsJoinDialog::m_pPass [protected]
Referenced by ChannelsJoinDialog(), and joinClicked().
QPushButton* ChannelsJoinDialog::m_pRegButton [protected]
Referenced by ChannelsJoinDialog(), and enableJoin().
QCheckBox* ChannelsJoinDialog::m_pShowAtStartupCheck [protected]
Referenced by ChannelsJoinDialog(), and ~ChannelsJoinDialog().
ChannelsJoinDialogTreeWidget* ChannelsJoinDialog::m_pTreeWidget [protected]
Referenced by ChannelsJoinDialog(), deleteClicked(), enableJoin(), fillListView(), itemSelected(), and regClicked().
The documentation for this class was generated from the following files:
src/modules/channelsjoin/ChannelsJoinDialog.h
src/modules/channelsjoin/ChannelsJoinDialog.cpp