KVIrc: KviPixmapSelector Class Reference
KviPixmapSelector Class Reference
#include <KviSelectors.h>
Public Member Functions
virtual void commit ()
KviPixmapSelector (QWidget *par, const QString &txt, KviPixmap *pOption, bool bEnabled)
virtual void setEnabled (bool bEnabled)
void setImagePath (const QString &path)
~KviPixmapSelector ()
Protected Slots
void checkBoxToggled (bool bEnabled)
void choosePixmap ()
Private Attributes
KviPixmap m_localPixmap
QCheckBox * m_pCheckBox
QPushButton * m_pChooseButton
QLabel * m_pFileNameLabel
KviPixmap * m_pOption
KviPixmapPreview * m_pPreview
Constructor & Destructor Documentation
KviPixmapSelector::KviPixmapSelector (QWidget * par, const QString & txt, KviPixmap * pOption, bool bEnabled)
References checkBoxToggled(), choosePixmap(), connect(), g, m_localPixmap, m_pCheckBox, m_pChooseButton, m_pFileNameLabel, m_pOption, m_pPreview, KviPixmap::path(), KviPixmap::pixmap(), setEnabled(), and KviPixmapPreview::setPixmap().
KviPixmapSelector::~KviPixmapSelector ()
Member Function Documentation
void KviPixmapSelector::checkBoxToggled (bool bEnabled) [protected, slot]
References setEnabled().
Referenced by KviPixmapSelector().
void KviPixmapSelector::choosePixmap () [protected, slot]
References __tr, KviFileDialog::askForOpenFileName(), and setImagePath().
Referenced by KviPixmapSelector().
void KviPixmapSelector::commit (void) [virtual]
Reimplemented from KviSelectorInterface.
References m_localPixmap, m_pCheckBox, and m_pOption.
Referenced by RegistrationWizard::accept(), RegisteredUserEntryDialog::editAllPropertiesClicked(), and RegisteredUserEntryDialog::okClicked().
void KviPixmapSelector::setEnabled (bool bEnabled) [virtual]
References m_pCheckBox, m_pChooseButton, m_pFileNameLabel, and m_pPreview.
Referenced by checkBoxToggled(), KviPixmapSelector(), and setImagePath().
void KviPixmapSelector::setImagePath (const QString & path)
References __tr2qs, KviPixmap::isNull(), KviPixmap::load(), m_localPixmap, m_pCheckBox, m_pFileNameLabel, m_pPreview, setEnabled(), and KviPixmapPreview::setPixmap().
Referenced by choosePixmap(), and RegisteredUserEntryDialog::editAllPropertiesClicked().
Member Data Documentation
KviPixmap KviPixmapSelector::m_localPixmap [private]
Referenced by commit(), KviPixmapSelector(), and setImagePath().
QCheckBox* KviPixmapSelector::m_pCheckBox [private]
Referenced by commit(), KviPixmapSelector(), setEnabled(), and setImagePath().
QPushButton* KviPixmapSelector::m_pChooseButton [private]
Referenced by KviPixmapSelector(), and setEnabled().
QLabel* KviPixmapSelector::m_pFileNameLabel [private]
Referenced by KviPixmapSelector(), setEnabled(), and setImagePath().
KviPixmap* KviPixmapSelector::m_pOption [private]
Referenced by commit(), and KviPixmapSelector().
KviPixmapPreview* KviPixmapSelector::m_pPreview [private]
Referenced by KviPixmapSelector(), setEnabled(), and setImagePath().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp