KVIrc: Plugin Class Reference
Plugin Class Reference
#include <Plugin.h>
Public Member Functions
int call (const QString &szFunctionName, int argc, char *argv[], char **pBuffer)
bool canunload ()
QString name () const
bool pfree (char *pBuffer)
void setName (const QString &szName)
bool unload ()
~Plugin ()
Static Public Member Functions
static Plugin * load (const QString &szFileName)
Protected Member Functions
Plugin (QLibrary *pLibrary, const QString &name)
Private Attributes
QLibrary * m_pLibrary
QString m_szName
Constructor & Destructor Documentation
Plugin::Plugin (QLibrary * pLibrary, const QString & name) protected
References m_pLibrary, m_szName, and name().
Referenced by load().
Plugin::~Plugin ()
References m_pLibrary.
Member Function Documentation
int Plugin::call (const QString & szFunctionName, int argc, char * argv[], char ** pBuffer)
References m_pLibrary, and r.
Referenced by PluginManager::pluginCall().
bool Plugin::canunload ()
References m_pLibrary.
Referenced by PluginManager::checkUnload().
Plugin * Plugin::load (const QString & szFileName) static
References KviFileUtils::extractFileName(), and Plugin().
Referenced by PluginManager::loadPlugin().
QString Plugin::name () const
References m_szName.
Referenced by Plugin().
bool Plugin::pfree (char * pBuffer)
References m_pLibrary.
Referenced by PluginManager::pluginCall().
void Plugin::setName (const QString & szName)
References m_szName.
bool Plugin::unload ()
References m_pLibrary.
Referenced by PluginManager::checkUnload(), and PluginManager::unloadAll().
Member Data Documentation
QLibrary* Plugin::m_pLibrary private
Referenced by call(), canunload(), pfree(), Plugin(), unload(), and ~Plugin().
QString Plugin::m_szName private
Referenced by name(), Plugin(), and setName().
The documentation for this class was generated from the following files:
src/modules/system/Plugin.h
src/modules/system/Plugin.cpp