KVIrc: KviKvsPopupMenuItemSeparator Class Reference
KviKvsPopupMenuItemSeparator Class Reference
#include <KviKvsPopupMenu.h>
Public Member Functions
virtual KviKvsPopupMenuItem * clone () const
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)
virtual ~KviKvsPopupMenuItemSeparator ()
Public Member Functions inherited from KviKvsPopupMenuItem
virtual void clear ()
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
virtual KviKvsScript * kvsCode ()
KviKvsScript * kvsCondition ()
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItemSeparator (const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItemSeparator (const QString &szItemName, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItem
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Friends
class KviKvsPopupMenu
Additional Inherited Members
Public Types inherited from KviKvsPopupMenuItem
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Protected Attributes inherited from KviKvsPopupMenuItem
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Constructor & Destructor Documentation
KviKvsPopupMenuItemSeparator::KviKvsPopupMenuItemSeparator (const QString & szItemName, const QString & szCondition) protected
Referenced by clone().
KviKvsPopupMenuItemSeparator::KviKvsPopupMenuItemSeparator (const QString & szItemName, const KviKvsScript * pCondition) protected
KviKvsPopupMenuItemSeparator::~KviKvsPopupMenuItemSeparator () virtual
Member Function Documentation
KviKvsPopupMenuItem * KviKvsPopupMenuItemSeparator::clone () const virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItemSeparator(), KviKvsPopupMenuItem::m_pKvsCondition, and KviKvsPopupMenuItem::m_szItemName.
void KviKvsPopupMenuItemSeparator::fill (KviKvsPopupMenu * pMenu, KviKvsPopupMenuTopLevelData * pData, int iIdx) virtual
Implements KviKvsPopupMenuItem.
References KviKvsPopupMenuItem::evaluateCondition().
Friends And Related Function Documentation
friend class KviKvsPopupMenu friend
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp