KVIrc: OptionsWidget_general Class Reference
OptionsWidget_general Class Reference
#include <OptionsWidget_general.h>
Public Member Functions
OptionsWidget_general (QWidget *parent)
~OptionsWidget_general ()
Constructor & Destructor Documentation
OptionsWidget_general::OptionsWidget_general (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addAdvancedButton(), KviOptionsWidget::addLabel(), and KviOptionsWidget::createLayout().
OptionsWidget_general::~OptionsWidget_general ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_general.h
src/modules/options/OptionsWidget_general.cpp