KVIrc: DccChatWindow Class Reference
DccChatWindow Class Reference
#include <DccChatWindow.h>
Public Member Functions
QFrame * buttonContainer ()
DccChatWindow (DccDescriptor *dcc, const char *name)
~DccChatWindow ()
Public Member Functions inherited from DccWindow
virtual const char * dccMarshalOutputContextString ()
virtual KviWindow * dccMarshalOutputWindow ()
DccWindow (KviWindow::Type eType, const char *name, DccDescriptor *d)
DccDescriptor * descriptor ()
const DccMarshal * marshal ()
~DccWindow ()
Public Member Functions inherited from KviWindow
void activateSelf ()
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual void applyOptions ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Public Member Functions inherited from DccMarshalOutputContext
DccMarshalOutputContext ()
virtual ~DccMarshalOutputContext ()
Protected Slots
void connected ()
void connectionInProgress ()
void handleMarshalError (KviError::Code eError)
void sslError (const char *msg)
void startingSSLHandshake ()
void textViewRightClicked ()
Protected Member Functions
virtual bool event (QEvent *e)
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &buffer)
virtual DccThread * getSlaveThread ()
virtual const QString & localNick ()
virtual QPixmap * myIconPtr ()
virtual void ownAction (const QString &text)
virtual void ownMessage (const QString &text, bool bUserFeedback=true)
virtual void resizeEvent (QResizeEvent *e)
virtual QSize sizeHint () const
void startConnection ()
virtual const QString & target ()
virtual void triggerCreationEvents ()
virtual void triggerDestructionEvents ()
Protected Attributes
KviTalHBox * m_pButtonBox
KviTalHBox * m_pButtonContainer
KviThemedLabel * m_pLabel
DccChatThread * m_pSlaveThread
QString m_szLocalNick
QString m_szTarget
Protected Attributes inherited from DccWindow
DccDescriptor * m_pDescriptor
DccMarshal * m_pMarshal
Protected Attributes inherited from KviWindow
bool m_bIsDocked
Type m_eType
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Constructor & Destructor Documentation
DccChatWindow::DccChatWindow (DccDescriptor * dcc, const char * name)
References connect(), connected(), connectionInProgress(), KviWindow::createCryptControllerButton(), KviWindow::createTextEncodingButton(), DccMarshalOutputContext::DccMarshal, handleMarshalError(), KVI_OPTION_BOOL, KviWindow::KviInput, KviOption_boolAutoLogDccChat, KviTalSplitter, m_pButtonBox, m_pButtonContainer, KviWindow::m_pInput, KviWindow::m_pIrcView, m_pLabel, DccWindow::m_pMarshal, m_pSlaveThread, KviWindow::m_pSplitter, KviTalHBox::setStretchFactor(), sslError(), startConnection(), startingSSLHandshake(), KviIrcView::startLogging(), and textViewRightClicked().
DccChatWindow::~DccChatWindow ()
References KviThreadManager::killPendingEvents(), m_pSlaveThread, KviSensitiveThread::terminate(), and DccBroker::unregisterDccWindow().
Member Function Documentation
QFrame* DccChatWindow::buttonContainer () inline virtual
Reimplemented from KviWindow.
void DccChatWindow::connected () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::idString(), KVI_OUT_DCCMSG, KviEvent_OnDCCChatConnected, KVS_TRIGGER_EVENT_1_HALTED, DccMarshal::localIp(), DccMarshal::localPort(), DccWindow::m_pDescriptor, m_pLabel, DccWindow::m_pMarshal, m_pSlaveThread, KviWindow::output(), DccMarshal::releaseSocket(), DccMarshal::remoteIp(), DccMarshal::remotePort(), s, KviThread::start(), DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szNick, DccDescriptor::szPort, and KviWindow::updateCaption().
Referenced by DccChatWindow().
void DccChatWindow::connectionInProgress () protected slot
References __tr2qs_ctx(), a, KviCString::append(), DccDescriptor::bActive, DccDescriptor::bSendRequest, KviWindow::connection(), DccDescriptor::console(), KviIrcConnection::encodeText(), KviCString::hasData(), KviIrcConnectionUserInfo::hostIp(), DccDescriptor::idString(), DccDescriptor::isZeroPortRequest(), kvi_isRoutableIpString(), KVI_OPTION_BOOL, KVI_OUT_DCCMSG, KviEvent_OnDCCChatConnectionInProgress, KviOption_boolDccGuessIpFromServerWhenLocalIsUnroutable, KVS_TRIGGER_EVENT_1, DccMarshal::localIp(), DccMarshal::localPort(), DccWindow::m_pDescriptor, DccWindow::m_pMarshal, KviWindow::output(), KviCString::ptr(), KviIrcConnection::sendData(), KviCString::setNum(), KviNetUtils::stringIpToBinaryIp(), DccDescriptor::szFakeIp, DccDescriptor::szFakePort, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szNick, DccDescriptor::szPort, DccDescriptor::szType, KviIrcConnection::userInfo(), and DccDescriptor::zeroPortRequestTag().
Referenced by DccChatWindow().
bool DccChatWindow::event (QEvent * e) protected virtual
References __tr2qs_ctx(), KviCString::cutLeft(), KviCString::cutRight(), d, KviIconManager::DccChatMsg, KviWindow::decodeText(), KviCryptEngine::DecryptOkWasEncoded, KviCryptEngine::DecryptOkWasEncrypted, KviCryptEngine::DecryptOkWasPlainText, KviWindow::demandAttention(), KviCString::firstCharIs(), KviMainWindow::firstConsole(), g_pApp, g_pMainWindow, KviError::getDescription(), KviWindow::hasAttention(), DccDescriptor::idString(), KVI_DCC_THREAD_EVENT_DATA, KVI_DCC_THREAD_EVENT_ERROR, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_UINT, KVI_OUT_ACTION, KVI_OUT_DCCCHATMSG, KVI_OUT_DCCERROR, KVI_OUT_SYSTEMERROR, kvi_strEqualCIN(), KVI_THREAD_EVENT, KviEvent_OnDCCChatDisconnected, KviEvent_OnDCCChatError, KviEvent_OnDCCChatMessage, KviOption_boolFlashDccChatWindowOnNewMessages, KviOption_boolPopupNotifierOnNewDccChatMessages, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_1, KVS_TRIGGER_EVENT_2_HALTED, KviCString::lastCharIs(), DccWindow::m_pDescriptor, KviWindow::MainWindowIsVisible, KviApplication::notifierMessage(), KviWindow::output(), KviConsoleWindow::outputPrivmsg(), KviCString::ptr(), KviCString::stripLeftWhiteSpace(), DccDescriptor::szHost, DccDescriptor::szNick, DccDescriptor::szUser, and KviQString::toHtmlEscaped().
void DccChatWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, KviWindow::m_szPlainTextCaption, DccDescriptor::szIp, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccChatWindow::getBaseLogFileName (QString & buffer) protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, DccDescriptor::szIp, DccDescriptor::szNick, and DccDescriptor::szPort.
virtual DccThread* DccChatWindow::getSlaveThread () inline protected virtual
Reimplemented from DccWindow.
References m_pSlaveThread.
void DccChatWindow::handleMarshalError (KviError::Code eError) protected slot
References __tr2qs_ctx(), KviError::getDescription(), DccDescriptor::idString(), KVI_OUT_DCCERROR, KviEvent_OnDCCChatError, KVS_TRIGGER_EVENT_2_HALTED, DccWindow::m_pDescriptor, KviWindow::output(), and DccDescriptor::szType.
Referenced by DccChatWindow(), and startConnection().
const QString & DccChatWindow::localNick () protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, m_szLocalNick, and DccDescriptor::szLocalNick.
QPixmap * DccChatWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References KviIconManager::DccMsg, g_pIconManager, and KviIconManager::getSmallIcon().
void DccChatWindow::ownAction (const QString & text) protected virtual
Reimplemented from KviWindow.
References __tr2qs_ctx(), d, KviWindow::encodeText(), KviCString::Format, KVI_OPTION_BOOL, KVI_OUT_ACTION, KVI_OUT_SYSTEMWARNING, KviOption_boolStripMircColorsInUserMessages, KviCString::len(), DccWindow::m_pDescriptor, m_pSlaveThread, KviWindow::output(), KviCString::ptr(), DccChatThread::sendRawData(), KviControlCodes::stripControlBytes(), and DccDescriptor::szLocalNick.
void DccChatWindow::ownMessage (const QString & text, bool bUserFeedback = true) protected virtual
Reimplemented from KviWindow.
References __tr2qs_ctx(), KviControlCodes::CryptEscape, d, KviWindow::decodeText(), KviCryptEngine::Encoded, KviWindow::encodeText(), KviCryptEngine::Encrypted, KviMainWindow::firstConsole(), KviCString::Format, g_pMainWindow, KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMWARNING, KviCString::len(), DccWindow::m_pDescriptor, m_pSlaveThread, KviConsoleWindow::NoNotifications, KviWindow::output(), KviConsoleWindow::outputPrivmsg(), KviCString::ptr(), DccChatThread::sendRawData(), DccDescriptor::szLocalHost, DccDescriptor::szLocalNick, and DccDescriptor::szLocalUser.
void DccChatWindow::resizeEvent (QResizeEvent * e) protected virtual
References KviInput::heightHint(), m_pButtonBox, KviWindow::m_pInput, and KviWindow::m_pSplitter.
QSize DccChatWindow::sizeHint () const protected virtual
References KviInput::heightHint(), KviWindow::m_pInput, KviWindow::m_pIrcView, and KviIrcView::sizeHint().
void DccChatWindow::sslError (const char * msg) protected slot
References __tr2qs_ctx(), DccDescriptor::idString(), KVI_OUT_DCCERROR, KviEvent_OnDCCChatError, KVS_TRIGGER_EVENT_2_HALTED, DccWindow::m_pDescriptor, and KviWindow::output().
Referenced by DccChatWindow().
void DccChatWindow::startConnection () protected
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bDoTimeout, DccMarshal::dccConnect(), DccMarshal::dccListen(), handleMarshalError(), KVI_OUT_DCCMSG, DccWindow::m_pDescriptor, DccWindow::m_pMarshal, KviWindow::output(), KviError::Success, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szPort, and DccDescriptor::szType.
Referenced by DccChatWindow().
void DccChatWindow::startingSSLHandshake () protected slot
References __tr2qs_ctx(), KVI_OUT_SSL, and KviWindow::outputNoFmt().
Referenced by DccChatWindow().
const QString & DccChatWindow::target () protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, m_szTarget, DccDescriptor::szIp, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccChatWindow::textViewRightClicked () protected slot
References DccDescriptor::idString(), KviEvent_OnDCCChatPopupRequest, KVS_TRIGGER_EVENT_1, and DccWindow::m_pDescriptor.
Referenced by DccChatWindow().
void DccChatWindow::triggerCreationEvents () protected virtual
Reimplemented from KviWindow.
References DccDescriptor::idString(), KviEvent_OnDCCChatWindowCreated, KVS_TRIGGER_EVENT_1, and DccWindow::m_pDescriptor.
void DccChatWindow::triggerDestructionEvents () protected virtual
Reimplemented from KviWindow.
References DccDescriptor::idString(), KviEvent_OnDCCChatWindowClosing, KVS_TRIGGER_EVENT_1, and DccWindow::m_pDescriptor.
Member Data Documentation
KviTalHBox* DccChatWindow::m_pButtonBox protected
Reimplemented from KviWindow.
Referenced by DccChatWindow(), and resizeEvent().
KviTalHBox* DccChatWindow::m_pButtonContainer protected
Referenced by DccChatWindow().
KviThemedLabel* DccChatWindow::m_pLabel protected
Referenced by connected(), and DccChatWindow().
DccChatThread* DccChatWindow::m_pSlaveThread protected
Referenced by connected(), DccChatWindow(), getSlaveThread(), ownAction(), ownMessage(), and ~DccChatWindow().
QString DccChatWindow::m_szLocalNick protected
Referenced by localNick().
QString DccChatWindow::m_szTarget protected
Referenced by target().
The documentation for this class was generated from the following files:
src/modules/dcc/DccChatWindow.h
src/modules/dcc/DccChatWindow.cpp