KVIrc: KviKvsAsyncOperationManager Class Reference
KviKvsAsyncOperationManager Class Reference
#include <kvi_kvs_asyncoperation.h>
Public Member Functions
KviKvsAsyncOperationManager ()
~KviKvsAsyncOperationManager ()
Protected Member Functions
void registerOperation (KviKvsAsyncOperation *o)
void unregisterOperation (KviKvsAsyncOperation *o)
Protected Attributes
KviPointerList
< KviKvsAsyncOperation > * m_pOperationList
Friends
class KviKvsAsyncOperation
Constructor & Destructor Documentation
KviKvsAsyncOperationManager::KviKvsAsyncOperationManager ()
References m_pOperationList, and KviPointerList< T >::setAutoDelete().
KviKvsAsyncOperationManager::~KviKvsAsyncOperationManager ()
References KviPointerList< T >::first(), and m_pOperationList.
Member Function Documentation
void KviKvsAsyncOperationManager::registerOperation (KviKvsAsyncOperation * o) [protected]
References KviPointerList< T >::append(), and m_pOperationList.
Referenced by KviKvsAsyncOperation::KviKvsAsyncOperation().
void KviKvsAsyncOperationManager::unregisterOperation (KviKvsAsyncOperation * o) [protected]
References m_pOperationList, and KviPointerList< T >::removeRef().
Referenced by KviKvsAsyncOperation::~KviKvsAsyncOperation().
Friends And Related Function Documentation
friend class KviKvsAsyncOperation [friend]
Member Data Documentation
KviPointerList<KviKvsAsyncOperation>* KviKvsAsyncOperationManager::m_pOperationList [protected]
Referenced by KviKvsAsyncOperationManager(), registerOperation(), unregisterOperation(), and ~KviKvsAsyncOperationManager().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_asyncoperation.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_asyncoperation.cpp