KVIrc: KviXmmsInterface Class Reference
KviXmmsInterface Class Reference
#include <MpXmmsInterface.h>
Public Member Functions
virtual int detect (bool bStart)
virtual int getPlayListPos ()
virtual bool getRepeat ()
virtual bool getShuffle ()
virtual int getVol ()
virtual bool jumpTo (kvs_int_t &iPos)
KviXmmsInterface ()
virtual int length ()
virtual QString mrl ()
virtual bool next ()
virtual QString nowPlaying ()
virtual bool pause ()
virtual bool play ()
virtual bool playMrl (const QString &mrl)
virtual int position ()
virtual bool prev ()
virtual bool quit ()
virtual bool setRepeat (bool &bVal)
virtual bool setShuffle (bool &bVal)
virtual bool setVol (kvs_int_t &iVol)
virtual MpInterface::PlayerStatus status ()
virtual bool stop ()
virtual ~KviXmmsInterface ()
Public Member Functions inherited from MpInterface
virtual QString album ()
virtual QString amipEval (const QString &cmd)
virtual bool amipExec (const QString &cmd)
virtual QString artist ()
virtual int bitRate ()
virtual int channels ()
virtual QString comment ()
virtual QString genre ()
virtual int getEqData (kvs_int_t &i_val)
virtual int getListLength ()
virtual bool hide ()
const QString & lastError () const
virtual QString mediaType ()
virtual bool minimize ()
MpInterface ()
virtual bool mute ()
virtual int sampleRate ()
virtual bool setEqData (kvs_int_t &iPos, kvs_int_t &iVal)
void setLastError (const QString &szLastError)
virtual bool setPlayListPos (kvs_int_t &iPos)
virtual bool show ()
virtual QString title ()
virtual QString year ()
virtual ~MpInterface ()
Protected Member Functions
bool loadPlayerLibrary ()
void * lookupSymbol (const char *szSymbolName)
Protected Member Functions inherited from MpInterface
QString getLocalFile ()
void notImplemented ()
Protected Attributes
const char ** m_pLibraryPaths
QLibrary * m_pPlayerLibrary
QString m_szPlayerLibraryName
Protected Attributes inherited from MpInterface
QString m_szLastError
Additional Inherited Members
Public Types inherited from MpInterface
enum PlayerStatus { Unknown, Stopped, Playing, Paused }
Constructor & Destructor Documentation
KviXmmsInterface::KviXmmsInterface ()
References m_pLibraryPaths, m_pPlayerLibrary, and m_szPlayerLibraryName.
KviXmmsInterface::~KviXmmsInterface () virtual
References m_pPlayerLibrary.
Member Function Documentation
int KviXmmsInterface::detect (bool bStart) virtual
Implements MpInterface.
References lookupSymbol(), and sym.
int KviXmmsInterface::getPlayListPos () virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::getRepeat () virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::getShuffle () virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
int KviXmmsInterface::getVol () virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::jumpTo (kvs_int_t & iPos) virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
int KviXmmsInterface::length () virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::loadPlayerLibrary () protected
References m_pLibraryPaths, m_pPlayerLibrary, and m_szPlayerLibraryName.
Referenced by lookupSymbol().
void * KviXmmsInterface::lookupSymbol (const char * szSymbolName) protected
References __tr2qs_ctx(), loadPlayerLibrary(), m_pPlayerLibrary, m_szPlayerLibraryName, and MpInterface::setLastError().
Referenced by detect(), getPlayListPos(), getRepeat(), getShuffle(), getVol(), jumpTo(), length(), mrl(), nowPlaying(), playMrl(), position(), setRepeat(), setShuffle(), setVol(), and status().
QString KviXmmsInterface::mrl () virtual
Implements MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::next () virtual
Implements MpInterface.
References XMMS_SIMPLE_CALL.
QString KviXmmsInterface::nowPlaying () virtual
Implements MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::pause () virtual
Implements MpInterface.
References XMMS_SIMPLE_CALL.
bool KviXmmsInterface::play () virtual
Implements MpInterface.
References XMMS_SIMPLE_CALL.
bool KviXmmsInterface::playMrl (const QString & mrl) virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
int KviXmmsInterface::position () virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
bool KviXmmsInterface::prev () virtual
Implements MpInterface.
References XMMS_SIMPLE_CALL.
bool KviXmmsInterface::quit () virtual
Reimplemented from MpInterface.
References XMMS_SIMPLE_CALL.
bool KviXmmsInterface::setRepeat (bool & bVal) virtual
Reimplemented from MpInterface.
References lookupSymbol().
bool KviXmmsInterface::setShuffle (bool & bVal) virtual
Reimplemented from MpInterface.
References lookupSymbol().
bool KviXmmsInterface::setVol (kvs_int_t & iVol) virtual
Reimplemented from MpInterface.
References lookupSymbol(), and sym.
MpInterface::PlayerStatus KviXmmsInterface::status () virtual
Reimplemented from MpInterface.
References lookupSymbol(), MpInterface::Paused, MpInterface::Playing, MpInterface::Stopped, and MpInterface::Unknown.
bool KviXmmsInterface::stop () virtual
Implements MpInterface.
References XMMS_SIMPLE_CALL.
Member Data Documentation
const char** KviXmmsInterface::m_pLibraryPaths protected
Referenced by KviAudaciousClassicInterface::KviAudaciousClassicInterface(), KviXmmsInterface(), and loadPlayerLibrary().
QLibrary* KviXmmsInterface::m_pPlayerLibrary protected
Referenced by KviXmmsInterface(), loadPlayerLibrary(), lookupSymbol(), and ~KviXmmsInterface().
QString KviXmmsInterface::m_szPlayerLibraryName protected
Referenced by KviAudaciousClassicInterface::KviAudaciousClassicInterface(), KviXmmsInterface(), loadPlayerLibrary(), and lookupSymbol().
The documentation for this class was generated from the following files:
src/modules/mediaplayer/MpXmmsInterface.h
src/modules/mediaplayer/MpXmmsInterface.cpp