KVIrc: KviCustomToolBar Class Reference
KviCustomToolBar Class Reference
#include <kvi_customtoolbar.h>
Public Member Functions
KviCustomToolBarDescriptor * descriptor ()
~KviCustomToolBar ()
Protected Slots
void beginCustomize ()
void endCustomize ()
void filteredChildDestroyed ()
Protected Member Functions
QAction * actionForWidget (QWidget *pWidget)
virtual void childEvent (QChildEvent *e)
void drag (QWidget *pChild, const QPoint &pnt)
virtual void dragEnterEvent (QDragEnterEvent *e)
virtual void dragLeaveEvent (QDragLeaveEvent *e)
virtual void dragMoveEvent (QDragMoveEvent *e)
virtual void dropEvent (QDropEvent *e)
int dropIndexAt (const QPoint &pnt, QWidget *pExclude, int *piExcludeIdx)
virtual bool eventFilter (QObject *o, QEvent *e)
void filterChild (QObject *o)
KviCustomToolBar (KviCustomToolBarDescriptor *d, const QString &szLabel, Qt::ToolBarArea type=Qt::TopToolBarArea, bool bNewLine=false, const char *pcName=0)
virtual void mousePressEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
void syncDescriptor ()
void unfilterChild (QObject *o)
QWidget * widgetAt (int iIndex)
Protected Attributes
KviCustomToolBarDescriptor * m_pDescriptor
QWidget * m_pDraggedChild
KviPointerHashTable< void
*, bool > * m_pFilteredChildren
QAction * m_pMovedAction
QWidget * m_pMovedChild
Friends
class KviCustomToolBarDescriptor
Constructor & Destructor Documentation
KviCustomToolBar::KviCustomToolBar (KviCustomToolBarDescriptor * d, const QString & szLabel, Qt::ToolBarArea type = Qt::TopToolBarArea, bool bNewLine = false, const char * pcName = 0) [protected]
References beginCustomize(), KviActionManager::customizingToolBars(), endCustomize(), KviActionManager::instance(), m_pDescriptor, m_pDraggedChild, m_pFilteredChildren, m_pMovedAction, m_pMovedChild, and KviCustomToolBarDescriptor::registerToolBar().
KviCustomToolBar::~KviCustomToolBar ()
References KviActionManager::currentToolBar(), KviActionManager::customizingToolBars(), KviActionManager::instance(), m_pDescriptor, m_pFilteredChildren, KviActionManager::setCurrentToolBar(), syncDescriptor(), and KviCustomToolBarDescriptor::unregisterToolBar().
Member Function Documentation
QAction * KviCustomToolBar::actionForWidget (QWidget * pWidget) [protected]
Referenced by dragLeaveEvent(), dragMoveEvent(), and eventFilter().
void KviCustomToolBar::beginCustomize () [protected, slot]
References filterChild(), m_pFilteredChildren, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by KviCustomToolBar().
void KviCustomToolBar::childEvent (QChildEvent * e) [protected, virtual]
References KviActionManager::customizingToolBars(), KviLocale::done(), filterChild(), and unfilterChild().
KviCustomToolBarDescriptor* KviCustomToolBar::descriptor () [inline]
void KviCustomToolBar::drag (QWidget * pChild, const QPoint & pnt) [protected]
void KviCustomToolBar::dragEnterEvent (QDragEnterEvent * e) [protected, virtual]
References KviAction::addToCustomToolBar(), KviActionManager::customizingToolBars(), KviActionManager::getAction(), KviActionManager::instance(), m_pDraggedChild, and KviActionManager::setCurrentToolBar().
void KviCustomToolBar::dragLeaveEvent (QDragLeaveEvent * e) [protected, virtual]
References actionForWidget(), m_pDraggedChild, m_pFilteredChildren, and KviPointerHashTable< Key, T >::remove().
void KviCustomToolBar::dragMoveEvent (QDragMoveEvent * e) [protected, virtual]
References actionForWidget(), dropIndexAt(), m_pDraggedChild, and widgetAt().
void KviCustomToolBar::dropEvent (QDropEvent * e) [protected, virtual]
References m_pDraggedChild.
int KviCustomToolBar::dropIndexAt (const QPoint & pnt, QWidget * pExclude, int * piExcludeIdx) [protected]
Referenced by dragMoveEvent().
void KviCustomToolBar::endCustomize () [protected, slot]
References m_pFilteredChildren, syncDescriptor(), and unfilterChild().
Referenced by KviCustomToolBar().
bool KviCustomToolBar::eventFilter (QObject * o, QEvent * e) [protected, virtual]
References actionForWidget(), KviAction::bigIcon(), KviActionManager::customizingToolBars(), KviActionManager::emitRemoveActionsHintRequest(), KviActionManager::getAction(), KviActionManager::instance(), m_pMovedAction, m_pMovedChild, and KviActionManager::setCurrentToolBar().
void KviCustomToolBar::filterChild (QObject * o) [protected]
References filteredChildDestroyed(), KviPointerHashTable< Key, T >::insert(), and m_pFilteredChildren.
Referenced by beginCustomize(), and childEvent().
void KviCustomToolBar::filteredChildDestroyed () [protected, slot]
References m_pFilteredChildren, and KviPointerHashTable< Key, T >::remove().
Referenced by filterChild(), and unfilterChild().
void KviCustomToolBar::mousePressEvent (QMouseEvent * e) [protected, virtual]
Reimplemented from KviToolBar.
References KviActionManager::customizingToolBars(), KviActionManager::instance(), and KviActionManager::setCurrentToolBar().
void KviCustomToolBar::paintEvent (QPaintEvent * e) [protected, virtual]
References KviActionManager::currentToolBar(), and KviActionManager::customizingToolBars().
void KviCustomToolBar::syncDescriptor () [protected]
References KviCustomToolBarDescriptor::actions(), KviPointerList< T >::append(), KviPointerList< T >::clear(), and m_pDescriptor.
Referenced by endCustomize(), and ~KviCustomToolBar().
void KviCustomToolBar::unfilterChild (QObject * o) [protected]
References filteredChildDestroyed(), KviPointerHashTable< Key, T >::find(), and m_pFilteredChildren.
Referenced by childEvent(), and endCustomize().
QWidget * KviCustomToolBar::widgetAt (int iIndex) [protected]
References NULL.
Referenced by dragMoveEvent().
Friends And Related Function Documentation
friend class KviCustomToolBarDescriptor [friend]
Member Data Documentation
KviCustomToolBarDescriptor* KviCustomToolBar::m_pDescriptor [protected]
Referenced by KviCustomToolBar(), syncDescriptor(), and ~KviCustomToolBar().
QWidget* KviCustomToolBar::m_pDraggedChild [protected]
Referenced by dragEnterEvent(), dragLeaveEvent(), dragMoveEvent(), dropEvent(), and KviCustomToolBar().
KviPointerHashTable<void *,bool>* KviCustomToolBar::m_pFilteredChildren [protected]
Referenced by beginCustomize(), dragLeaveEvent(), endCustomize(), filterChild(), filteredChildDestroyed(), KviCustomToolBar(), unfilterChild(), and ~KviCustomToolBar().
QAction* KviCustomToolBar::m_pMovedAction [protected]
Referenced by eventFilter(), and KviCustomToolBar().
QWidget* KviCustomToolBar::m_pMovedChild [protected]
Referenced by eventFilter(), and KviCustomToolBar().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_customtoolbar.h
src/kvirc/ui/kvi_customtoolbar.cpp