KVIrc: KviKvsTreeNodeSpecialCommandDo Class Reference
KviKvsTreeNodeSpecialCommandDo Class Reference
#include <KviKvsTreeNodeSpecialCommandDo.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandDo (const QChar *pLocation, KviKvsTreeNodeExpression *e, KviKvsTreeNodeInstruction *i)
~KviKvsTreeNodeSpecialCommandDo ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommand
KviKvsTreeNodeSpecialCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeSpecialCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviKvsTreeNodeExpression * m_pExpression
KviKvsTreeNodeInstruction * m_pInstruction
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandDo::KviKvsTreeNodeSpecialCommandDo (const QChar * pLocation, KviKvsTreeNodeExpression * e, KviKvsTreeNodeInstruction * i)
References e, i, m_pExpression, m_pInstruction, and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandDo::~KviKvsTreeNodeSpecialCommandDo ()
References m_pExpression, and m_pInstruction.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandDo::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandDo::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
bool KviKvsTreeNodeSpecialCommandDo::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariant::asBoolean(), KviKvsRunTimeContext::breakPending(), KviKvsRunTimeContext::continuePending(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviKvsRunTimeContext::handleBreak(), KviKvsRunTimeContext::handleContinue(), m_pExpression, m_pInstruction, and v.
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeSpecialCommandDo::m_pExpression private
Referenced by execute(), KviKvsTreeNodeSpecialCommandDo(), and ~KviKvsTreeNodeSpecialCommandDo().
KviKvsTreeNodeInstruction* KviKvsTreeNodeSpecialCommandDo::m_pInstruction private
Referenced by execute(), KviKvsTreeNodeSpecialCommandDo(), and ~KviKvsTreeNodeSpecialCommandDo().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandDo.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandDo.cpp