KVIrc: DccVoiceNullCodec Class Reference
DccVoiceNullCodec Class Reference
#include <DccVoiceCodec.h>
Public Member Functions
DccVoiceNullCodec ()
virtual void decode (KviDataBuffer *stream, KviDataBuffer *signal)
virtual int decodedFrameSize ()
virtual void encode (KviDataBuffer *signal, KviDataBuffer *stream)
virtual int encodedFrameSize ()
virtual ~DccVoiceNullCodec ()
Public Member Functions inherited from DccVoiceCodec
DccVoiceCodec ()
const char * name ()
virtual ~DccVoiceCodec ()
Additional Inherited Members
Protected Attributes inherited from DccVoiceCodec
KviCString m_szName
Constructor & Destructor Documentation
DccVoiceNullCodec::DccVoiceNullCodec ()
References DccVoiceCodec::m_szName.
DccVoiceNullCodec::~DccVoiceNullCodec () virtual default
Member Function Documentation
void DccVoiceNullCodec::decode (KviDataBuffer * stream, KviDataBuffer * signal) virtual
Reimplemented from DccVoiceCodec.
References KviDataBuffer::append(), KviDataBuffer::data(), KviDataBuffer::resize(), and KviDataBuffer::size().
int DccVoiceNullCodec::decodedFrameSize () virtual
Reimplemented from DccVoiceCodec.
void DccVoiceNullCodec::encode (KviDataBuffer * signal, KviDataBuffer * stream) virtual
Reimplemented from DccVoiceCodec.
References KviDataBuffer::append(), KviDataBuffer::data(), KviDataBuffer::resize(), and KviDataBuffer::size().
int DccVoiceNullCodec::encodedFrameSize () virtual
Reimplemented from DccVoiceCodec.
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceCodec.h
src/modules/dcc/DccVoiceCodec.cpp