KVIrc: KviMexLinkFilter Class Reference
KviMexLinkFilter Class Reference abstract
#include <KviMexLinkFilter.h>
Public Member Functions
virtual bool clearOutputQueue (bool bPrivateMessagesOnly)=0
KviMexLinkFilter (KviModuleExtensionDescriptor *d)
virtual unsigned int outputQueueSize ()=0
virtual void processData (char *buffer, int len)=0
virtual bool sendPacket (KviDataBuffer *pData)=0
~KviMexLinkFilter ()
Public Member Functions inherited from KviModuleExtension
KviModuleExtensionDescriptor * descriptor ()
virtual void die ()=0
KviModuleExtension (KviModuleExtensionDescriptor *d)
virtual ~KviModuleExtension ()
Additional Inherited Members
Static Public Member Functions inherited from KviModuleExtension
static KviModuleExtensionManager * manager ()
Constructor & Destructor Documentation
KviMexLinkFilter::KviMexLinkFilter (KviModuleExtensionDescriptor * d)
KviMexLinkFilter::~KviMexLinkFilter ()
Member Function Documentation
virtual bool KviMexLinkFilter::clearOutputQueue (bool bPrivateMessagesOnly) pure virtual
Referenced by KviIrcLink::clearOutputQueue().
virtual unsigned int KviMexLinkFilter::outputQueueSize () pure virtual
Referenced by KviIrcLink::outputQueueSize().
virtual void KviMexLinkFilter::processData (char * buffer, int len) pure virtual
Referenced by KviIrcLink::processData().
virtual bool KviMexLinkFilter::sendPacket (KviDataBuffer * pData) pure virtual
Referenced by KviIrcLink::sendPacket().
The documentation for this class was generated from the following files:
src/kvirc/module/KviMexLinkFilter.h
src/kvirc/module/KviMexLinkFilter.cpp