KVIrc: KviKvsTreeNodeCoreCallbackCommand Class Reference
KviKvsTreeNodeCoreCallbackCommand Class Reference
#include <kvi_kvs_treenode_corecallbackcommand.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeCoreCallbackCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params, KviKvsCoreCallbackCommandExecRoutine *r, KviKvsScript *pCallback)
~KviKvsTreeNodeCoreCallbackCommand ()
Protected Attributes
KviKvsCoreCallbackCommandExecRoutine * m_pExecRoutine
Constructor & Destructor Documentation
KviKvsTreeNodeCoreCallbackCommand::KviKvsTreeNodeCoreCallbackCommand (const QChar * pLocation, const QString & szCmdName, KviKvsTreeNodeDataList * params, KviKvsCoreCallbackCommandExecRoutine * r, KviKvsScript * pCallback)
References m_pExecRoutine.
KviKvsTreeNodeCoreCallbackCommand::~KviKvsTreeNodeCoreCallbackCommand ()
Member Function Documentation
void KviKvsTreeNodeCoreCallbackCommand::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeCallbackCommand.
References KviKvsTreeNodeCommand::m_szCmdName, and KviQString::sprintf().
void KviKvsTreeNodeCoreCallbackCommand::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeCallbackCommand.
References debug, KviKvsTreeNodeCallbackCommand::dumpCallback(), KviKvsTreeNodeCommandWithParameters::dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), and KviKvsTreeNodeCommand::m_szCmdName.
bool KviKvsTreeNodeCoreCallbackCommand::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsTreeNodeSwitchList::evaluate(), KviKvsTreeNodeDataList::evaluate(), KviKvsTreeNodeCallbackCommand::m_pCallback, m_pExecRoutine, KviKvsTreeNodeCommandWithParameters::m_pParams, KviKvsTreeNodeCommand::m_pSwitches, _KviKvsCoreCallbackCommandExecRoutine::proc, KviKvsVariantList::setAutoDelete(), and KviKvsRunTimeContext::setDefaultReportLocation().
Member Data Documentation
KviKvsCoreCallbackCommandExecRoutine* KviKvsTreeNodeCoreCallbackCommand::m_pExecRoutine [protected]
Referenced by execute(), and KviKvsTreeNodeCoreCallbackCommand().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_corecallbackcommand.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_corecallbackcommand.cpp