KVIrc: KviKvsMdmWizard Class Reference
KviKvsMdmWizard Class Reference
#include <KvsObject_wizard.h>
Public Member Functions
void accept ()
KviKvsMdmWizard (QWidget *par, const char *name, KvsObject_wizard *)
void reject ()
virtual ~KviKvsMdmWizard ()
Public Member Functions inherited from KviTalWizard
void addPage (QWidget *pWidget, const QString &szTitle)
QPushButton * backButton ()
QPushButton * cancelButton ()
QWidget * currentPage ()
QPushButton * finishButton ()
QPushButton * helpButton ()
void insertPage (QWidget *pWidget, const QString &szTitle, int iIndex)
KviTalWizard (QWidget *pParent)
QPushButton * nextButton ()
void setBackEnabled (QWidget *pWidget, bool bEnabled)
void setCancelEnabled (QWidget *pWidget, bool bEnabled)
bool setCurrentPage (QWidget *pWidget)
void setFinishEnabled (QWidget *pWidget, bool bEnabled)
void setHelpEnabled (QWidget *pWidget, bool bEnabled)
void setNextEnabled (QWidget *pWidget, bool bEnabled)
bool setPageEnabled (QWidget *pWidget, bool bEnabled)
bool setPageTitle (QWidget *pWidget, const QString &szTitle)
~KviTalWizard ()
Protected Slots
void slotBackClicked ()
void slotNextClicked ()
Protected Slots inherited from KviTalWizard
void backButtonClicked ()
void cancelButtonClicked ()
void finishButtonClicked ()
void helpButtonClicked ()
void nextButtonClicked ()
Protected Attributes
KvsObject_wizard * m_pParentScript
Protected Attributes inherited from KviTalWizard
KviTalWizardPrivate * m_p
Additional Inherited Members
Signals inherited from KviTalWizard
void helpClicked ()
void pageChanged (QString title)
Protected Member Functions inherited from KviTalWizard
virtual void closeEvent (QCloseEvent *e)
void setCurrentPage (KviTalWizardPageData *pData)
virtual void showEvent (QShowEvent *e)
Constructor & Destructor Documentation
KviKvsMdmWizard::KviKvsMdmWizard (QWidget * par, const char * name, KvsObject_wizard * parent)
References KviTalWizard::backButton(), connect(), m_pParentScript, KviTalWizard::nextButton(), slotBackClicked(), and slotNextClicked().
KviKvsMdmWizard::~KviKvsMdmWizard () virtual default
Member Function Documentation
void KviKvsMdmWizard::accept ()
References KvsObject_wizard::accept(), and m_pParentScript.
void KviKvsMdmWizard::reject ()
References m_pParentScript, and KvsObject_wizard::reject().
void KviKvsMdmWizard::slotBackClicked () protected slot
References KvsObject_wizard::backClicked(), and m_pParentScript.
Referenced by KviKvsMdmWizard().
void KviKvsMdmWizard::slotNextClicked () protected slot
References m_pParentScript, and KvsObject_wizard::nextClicked().
Referenced by KviKvsMdmWizard().
Member Data Documentation
KvsObject_wizard* KviKvsMdmWizard::m_pParentScript protected
Referenced by accept(), KviKvsMdmWizard(), reject(), slotBackClicked(), and slotNextClicked().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_wizard.h
src/modules/objects/KvsObject_wizard.cpp