KVIrc: KviRegisteredUser Class Reference
KviRegisteredUser Class Reference
#include <KviRegisteredUser.h>
Public Types
enum IgnoreFlags {
Channel = 1, Query = 2, Notice = 4, Ctcp = 8,
Invite = 16, Dcc = 32, Highlight = 64
}
Public Member Functions
bool getBoolProperty (const QString &szName, bool bDef=false)
const QString & getProperty (const QString &szName)
bool getProperty (const QString &szName, QString &szValue)
const QString & group ()
bool ignoreEnabled ()
int ignoreFlags ()
bool isIgnoreEnabledFor (IgnoreFlags flag)
KviRegisteredUser (const QString &szName)
KviPointerList< KviIrcMask > * maskList ()
bool matches (const KviIrcMask &mask)
bool matchesFixed (const KviIrcMask &mask)
bool matchesFixed (const QString &szNick, const QString &szUser, const QString &szHost)
const QString & name ()
KviPointerHashTable< QString,
QString > * propertyDict ()
void setGroup (const QString &szName)
void setIgnoreEnabled (bool bEnabled)
void setIgnoreFlags (int iFlags)
void setProperty (const QString &szName, const QString &szValue)
void setProperty (const QString &szName, bool szValue)
~KviRegisteredUser ()
Protected Member Functions
bool addMask (KviIrcMask *pMask)
KviIrcMask * findMask (const KviIrcMask &mask)
bool removeMask (KviIrcMask *pMask)
Private Attributes
bool m_bIgnoreEnabled
int m_iIgnoreFlags
KviPointerList< KviIrcMask > * m_pMaskList
KviPointerHashTable< QString,
QString > * m_pPropertyDict
QString m_szGroup
QString m_szName
Friends
class KviRegisteredUserDataBase
Member Enumeration Documentation
enum KviRegisteredUser::IgnoreFlags
Enumerator
Channel
Query
Notice
Ctcp
Invite
Dcc
Highlight
Constructor & Destructor Documentation
KviRegisteredUser::KviRegisteredUser (const QString & szName)
References m_bIgnoreEnabled, m_iIgnoreFlags, m_pMaskList, m_pPropertyDict, m_szName, name(), and KviPointerList< T >::setAutoDelete().
KviRegisteredUser::~KviRegisteredUser ()
References m_pMaskList, and m_pPropertyDict.
Member Function Documentation
bool KviRegisteredUser::addMask (KviIrcMask * pMask) protected
References KviPointerList< T >::append(), findMask(), and m_pMaskList.
Referenced by KviRegisteredUserDataBase::addMask().
KviIrcMask * KviRegisteredUser::findMask (const KviIrcMask & mask) protected
References KviPointerList< T >::first(), m, m_pMaskList, and KviPointerList< T >::next().
Referenced by addMask().
bool KviRegisteredUser::getBoolProperty (const QString & szName, bool bDef = false)
References KviQString::equalCI(), KviQString::equalCS(), KviPointerHashTable< Key, T >::find(), and m_pPropertyDict.
Referenced by KviConsoleWindow::applyHighlighting(), KviIrcUserDataBase::registeredUser(), and RegisteredUserEntryDialog::RegisteredUserEntryDialog().
const QString & KviRegisteredUser::getProperty (const QString & szName)
References KviQString::Empty, KviPointerHashTable< Key, T >::find(), and m_pPropertyDict.
Referenced by KviStupidNotifyListManager::buildNickList(), KviConsoleWindow::checkDefaultAvatar(), RegisteredUsersDialog::exportClicked(), KviConsoleWindow::getUserTipText(), RegisteredUsersDialog::itemPressed(), RegisteredUsersDialogItemDelegate::paint(), KviIrcUserDataBase::registeredUser(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), RegisteredUsersDialogItem::RegisteredUsersDialogItem(), reguser_kvs_fnc_matchProperty(), reguser_kvs_fnc_property(), and KviConsoleWindow::resetAvatarForMatchingUsers().
bool KviRegisteredUser::getProperty (const QString & szName, QString & szValue)
References KviPointerHashTable< Key, T >::find(), and m_pPropertyDict.
const QString& KviRegisteredUser::group () inline
Referenced by KviConsoleWindow::getUserTipText(), RegisteredUserEntryDialog::okClicked(), and KviRegisteredUserDataBase::save().
bool KviRegisteredUser::ignoreEnabled () inline
Referenced by RegisteredUsersDialogItemDelegate::paint(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), reguser_kvs_fnc_isIgnoreEnabled(), and KviRegisteredUserDataBase::save().
int KviRegisteredUser::ignoreFlags () inline
Referenced by RegisteredUserEntryDialog::RegisteredUserEntryDialog(), reguser_kvs_fnc_getIgnoreFlags(), and KviRegisteredUserDataBase::save().
bool KviRegisteredUser::isIgnoreEnabledFor (IgnoreFlags flag)
References m_bIgnoreEnabled, and m_iIgnoreFlags.
Referenced by KviIrcServerParser::parseCtcpRequest(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), and KviConsoleWindow::triggerOnHighlight().
KviPointerList<KviIrcMask>* KviRegisteredUser::maskList () inline
Referenced by RegisteredUsersDialog::exportClicked(), RegisteredUsersDialog::itemPressed(), RegisteredUserEntryDialog::notifyCheckClicked(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), reguser_kvs_fnc_mask(), KviRegisteredUserDataBase::removeUser(), and KviRegisteredUserDataBase::save().
bool KviRegisteredUser::matches (const KviIrcMask & mask)
References KviPointerList< T >::first(), m, m_pMaskList, and KviPointerList< T >::next().
bool KviRegisteredUser::matchesFixed (const KviIrcMask & mask)
References KviPointerList< T >::first(), m, m_pMaskList, and KviPointerList< T >::next().
Referenced by KviConsoleWindow::resetAvatarForMatchingUsers().
bool KviRegisteredUser::matchesFixed (const QString & szNick, const QString & szUser, const QString & szHost)
References KviPointerList< T >::first(), m, m_pMaskList, and KviPointerList< T >::next().
const QString& KviRegisteredUser::name () inline
Referenced by KviRegisteredUserDataBase::addMask(), KviRegisteredUserDataBase::addUser(), RegisteredUsersDialog::editItem(), RegisteredUsersDialog::exportClicked(), KviRegisteredUserDataBase::getUser(), KviConsoleWindow::getUserTipText(), RegisteredUsersDialog::importClicked(), RegisteredUsersDialog::itemPressed(), RegisteredUsersDialogItem::key(), KviRegisteredUser(), RegisteredUserEntryDialog::notifyCheckClicked(), RegisteredUserEntryDialog::okClicked(), KviIrcUserDataBase::registeredUser(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), RegisteredUsersDialogItem::RegisteredUsersDialogItem(), reguser_kvs_cmd_add(), reguser_kvs_cmd_addmask(), reguser_kvs_fnc_exactMatch(), reguser_kvs_fnc_match(), and KviRegisteredUserDataBase::save().
KviPointerHashTable<QString, QString>* KviRegisteredUser::propertyDict () inline
Referenced by RegisteredUsersDialog::exportClicked(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), and KviRegisteredUserDataBase::save().
bool KviRegisteredUser::removeMask (KviIrcMask * pMask) protected
References m_pMaskList, and KviPointerList< T >::removeRef().
void KviRegisteredUser::setGroup (const QString & szName) inline
Referenced by KviRegisteredUserDataBase::copyFrom(), KviRegisteredUserDataBase::load(), RegisteredUserEntryDialog::okClicked(), and reguser_kvs_cmd_add().
void KviRegisteredUser::setIgnoreEnabled (bool bEnabled) inline
Referenced by KviRegisteredUserDataBase::load(), RegisteredUserEntryDialog::okClicked(), and reguser_kvs_cmd_setIgnoreEnabled().
void KviRegisteredUser::setIgnoreFlags (int iFlags) inline
Referenced by KviRegisteredUserDataBase::load(), RegisteredUserEntryDialog::okClicked(), and reguser_kvs_cmd_setIgnoreFlags().
void KviRegisteredUser::setProperty (const QString & szName, const QString & szValue)
References m_pPropertyDict, KviPointerHashTable< Key, T >::remove(), KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by RegistrationWizard::accept(), KviConsoleWindow::avatarChanged(), KviRegisteredUserDataBase::copyFrom(), RegisteredUsersDialog::importClicked(), RegisteredUsersDialog::itemPressed(), KviRegisteredUserDataBase::load(), RegisteredUserEntryDialog::okClicked(), reguser_kvs_cmd_setproperty(), and setProperty().
void KviRegisteredUser::setProperty (const QString & szName, bool szValue)
References setProperty().
Friends And Related Function Documentation
friend class KviRegisteredUserDataBase friend
Member Data Documentation
bool KviRegisteredUser::m_bIgnoreEnabled private
Referenced by KviRegisteredUserDataBase::copyFrom(), isIgnoreEnabledFor(), and KviRegisteredUser().
int KviRegisteredUser::m_iIgnoreFlags private
Referenced by KviRegisteredUserDataBase::copyFrom(), isIgnoreEnabledFor(), and KviRegisteredUser().
KviPointerList<KviIrcMask>* KviRegisteredUser::m_pMaskList private
Referenced by addMask(), findMask(), KviRegisteredUser(), matches(), matchesFixed(), removeMask(), and ~KviRegisteredUser().
KviPointerHashTable<QString, QString>* KviRegisteredUser::m_pPropertyDict private
Referenced by getBoolProperty(), getProperty(), KviRegisteredUser(), setProperty(), and ~KviRegisteredUser().
QString KviRegisteredUser::m_szGroup private
QString KviRegisteredUser::m_szName private
Referenced by KviRegisteredUser().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviRegisteredUser.h
src/kvilib/ext/KviRegisteredUser.cpp