KVIrc: KviKvsTreeNodeExpression Class Reference
KviKvsTreeNodeExpression Class Reference
#include <KviKvsTreeNodeExpression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual int firstBinaryOperator ()
KviKvsTreeNodeExpression (const QChar *pLocation)
virtual KviKvsTreeNodeExpression * left ()
KviKvsTreeNodeExpression * parentExpression ()
virtual KviKvsTreeNodeExpression * parentWithPrecedenceLowerThan (int iPrec)
virtual int precedence ()
virtual KviKvsTreeNodeExpression * right ()
virtual void setLeft (KviKvsTreeNodeExpression *pLeft)
void setParentExpression (KviKvsTreeNodeExpression *pParent)
virtual void setRight (KviKvsTreeNodeExpression *pRight)
~KviKvsTreeNodeExpression ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeExpression * m_pParentExpression
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeExpression::KviKvsTreeNodeExpression (const QChar * pLocation)
References m_pParentExpression.
KviKvsTreeNodeExpression::~KviKvsTreeNodeExpression () default
Member Function Documentation
void KviKvsTreeNodeExpression::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator, KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperator, KviKvsTreeNodeExpressionOperator, KviKvsTreeNodeExpressionConstantOperand, and KviKvsTreeNodeExpressionVariableOperand.
Referenced by KviKvsParser::parseExpression().
void KviKvsTreeNodeExpression::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator, KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperator, KviKvsTreeNodeExpressionOperator, KviKvsTreeNodeExpressionConstantOperand, and KviKvsTreeNodeExpressionVariableOperand.
Referenced by KviKvsTreeNodeExpressionReturn::dump(), KviKvsTreeNodeSpecialCommandFor::dump(), KviKvsTreeNodeArrayElement::dump(), KviKvsTreeNodeSpecialCommandSwitch::dump(), KviKvsTreeNodeExpressionUnaryOperator::dump(), KviKvsTreeNodeExpressionUnaryOperatorNegate::dump(), KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::dump(), KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::dump(), and KviKvsTreeNodeExpressionBinaryOperator::dumpOperands().
int KviKvsTreeNodeExpression::firstBinaryOperator () virtual
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator.
References firstBinaryOperator(), left(), and precedence().
Referenced by firstBinaryOperator().
KviKvsTreeNodeExpression * KviKvsTreeNodeExpression::left () virtual
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator.
Referenced by firstBinaryOperator().
KviKvsTreeNodeExpression* KviKvsTreeNodeExpression::parentExpression () inline
Referenced by parentWithPrecedenceLowerThan().
KviKvsTreeNodeExpression * KviKvsTreeNodeExpression::parentWithPrecedenceLowerThan (int iPrec) virtual
References parentExpression(), parentWithPrecedenceLowerThan(), and precedence().
Referenced by parentWithPrecedenceLowerThan(), and KviKvsParser::parseExpression().
int KviKvsTreeNodeExpression::precedence () virtual
Reimplemented in KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, and KviKvsTreeNodeExpressionUnaryOperatorNegate.
References PREC_MAXIMUM.
Referenced by firstBinaryOperator(), KviKvsTreeNodeExpressionBinaryOperator::firstBinaryOperator(), parentWithPrecedenceLowerThan(), and KviKvsParser::parseExpression().
KviKvsTreeNodeExpression * KviKvsTreeNodeExpression::right () virtual
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator.
Referenced by KviKvsParser::parseExpression().
void KviKvsTreeNodeExpression::setLeft (KviKvsTreeNodeExpression * pLeft) virtual
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator.
Referenced by KviKvsParser::parseExpression().
void KviKvsTreeNodeExpression::setParentExpression (KviKvsTreeNodeExpression * pParent) inline
Referenced by KviKvsTreeNodeExpressionUnaryOperator::KviKvsTreeNodeExpressionUnaryOperator(), KviKvsTreeNodeExpressionBinaryOperator::setLeft(), and KviKvsTreeNodeExpressionBinaryOperator::setRight().
void KviKvsTreeNodeExpression::setRight (KviKvsTreeNodeExpression * pRight) virtual
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator.
Referenced by KviKvsParser::parseExpression().
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeExpression::m_pParentExpression protected
Referenced by KviKvsTreeNodeExpression().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.h
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.cpp