KVIrc: KviMaskInputDialog Class Reference
KviMaskInputDialog Class Reference
#include <kvi_maskeditor.h>
Public Member Functions
KviMaskInputDialog (const QString &szMask, KviMaskEditor *pEditor, KviChannel *pChannel)
~KviMaskInputDialog ()
Protected Slots
virtual void accept ()
Protected Attributes
QPushButton * m_pChancelButton
KviChannel * m_pChannel
QLineEdit * m_pEdit
KviMaskEditor * m_pEditor
QPushButton * m_pOkButton
QString m_szOldMask
Constructor & Destructor Documentation
KviMaskInputDialog::KviMaskInputDialog (const QString & szMask, KviMaskEditor * pEditor, KviChannel * pChannel)
References __tr2qs, accept(), g_pIconManager, KviIconManager::getSmallIcon(), KVI_SMALLICON_ACCEPT, KVI_SMALLICON_DISCARD, m_pChancelButton, m_pChannel, m_pEdit, m_pEditor, m_pOkButton, and m_szOldMask.
KviMaskInputDialog::~KviMaskInputDialog ()
Member Function Documentation
void KviMaskInputDialog::accept () [protected, virtual, slot]
References KviWindow::connection(), KviIrcConnection::encodeText(), KviMaskEditor::flag(), m_pChannel, m_pEdit, m_pEditor, m_szOldMask, KviIrcConnection::sendFmtData(), and KviChannel::target().
Referenced by KviMaskInputDialog().
Member Data Documentation
QPushButton* KviMaskInputDialog::m_pChancelButton [protected]
Referenced by KviMaskInputDialog().
KviChannel* KviMaskInputDialog::m_pChannel [protected]
Referenced by accept(), and KviMaskInputDialog().
QLineEdit* KviMaskInputDialog::m_pEdit [protected]
Referenced by accept(), and KviMaskInputDialog().
KviMaskEditor* KviMaskInputDialog::m_pEditor [protected]
Referenced by accept(), and KviMaskInputDialog().
QPushButton* KviMaskInputDialog::m_pOkButton [protected]
Referenced by KviMaskInputDialog().
QString KviMaskInputDialog::m_szOldMask [protected]
Referenced by accept(), and KviMaskInputDialog().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_maskeditor.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_maskeditor.cpp