KVIrc: KvsObject_tabWidget Class Reference
KvsObject_tabWidget Class Reference
#include <KvsObject_tabWidget.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void slotCurrentChanged (int)
void slotTabCloseRequest (int)
Protected Member Functions
bool addTab (KviKvsObjectFunctionCall *c)
bool changeTab (KviKvsObjectFunctionCall *c)
bool count (KviKvsObjectFunctionCall *c)
bool currentChangedEvent (KviKvsObjectFunctionCall *c)
bool currentPageIndex (KviKvsObjectFunctionCall *c)
bool currentTabLabel (KviKvsObjectFunctionCall *c)
bool indexOf (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertTab (KviKvsObjectFunctionCall *c)
bool removePage (KviKvsObjectFunctionCall *c)
bool removeTabToolTip (KviKvsObjectFunctionCall *c)
bool setCurrentPage (KviKvsObjectFunctionCall *c)
bool setTabLabel (KviKvsObjectFunctionCall *c)
bool setTabPosition (KviKvsObjectFunctionCall *c)
bool setTabsClosable (KviKvsObjectFunctionCall *c)
bool setTabToolTip (KviKvsObjectFunctionCall *c)
bool tabCloseRequestEvent (KviKvsObjectFunctionCall *c)
bool tabLabel (KviKvsObjectFunctionCall *c)
bool widgetAt (KviKvsObjectFunctionCall *c)
Protected Attributes
QList< kvs_hobject_t > tabsList
Member Function Documentation
bool KvsObject_tabWidget::addTab (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::changeTab (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::count (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::currentChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::currentPageIndex (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::currentTabLabel (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::indexOf (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_tabWidget::insertTab (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::removePage (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::removeTabToolTip (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::setCurrentPage (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::setTabLabel (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::setTabPosition (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::setTabsClosable (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::setTabToolTip (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_tabWidget::slotCurrentChanged (int value) [protected, slot]
References KviKvsObject::callFunction().
void KvsObject_tabWidget::slotTabCloseRequest (int iIndex) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_tabWidget::tabCloseRequestEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_tabWidget::tabLabel (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_tabWidget::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
bool KvsObject_tabWidget::widgetAt (KviKvsObjectFunctionCall * c) [protected]
Member Data Documentation
QList<kvs_hobject_t> KvsObject_tabWidget::tabsList [protected]
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_tabWidget.h
src/modules/objects/KvsObject_tabWidget.cpp