KVIrc: AddonManagementDialog Class Reference
AddonManagementDialog Class Reference
#include <AddonManagementDialog.h>
Public Member Functions
~AddonManagementDialog ()
Static Public Member Functions
static void cleanup ()
static void display (bool bTopLevel)
static AddonManagementDialog * instance ()
Protected Slots
void closeClicked ()
void configureScript ()
void currentChanged (QListWidgetItem *i, QListWidgetItem *)
void getMoreScripts ()
void installScript ()
void packScript ()
virtual void reject ()
void showScriptHelp ()
void uninstallScript ()
Protected Member Functions
AddonManagementDialog (QWidget *p)
virtual void closeEvent (QCloseEvent *e)
void fillListView ()
Protected Attributes
QToolButton * m_pConfigureButton
QToolButton * m_pHelpButton
KviTalListWidget * m_pListWidget
QToolButton * m_pPackButton
QToolButton * m_pUninstallButton
Static Protected Attributes
static AddonManagementDialog * m_pInstance = 0
Constructor & Destructor Documentation
AddonManagementDialog::AddonManagementDialog (QWidget * p) protected
References __tr2qs_ctx(), KviTalToolTip::add(), KviIconManager::Addons, closeClicked(), configureScript(), connect(), currentChanged(), fillListView(), g, g_pApp, g_pIconManager, g_pMainWindow, g_rectManagementDialogGeometry, KviIconManager::getBigIcon(), getMoreScripts(), KviIconManager::getSmallIcon(), installScript(), KVI_BIGICON_ADDONS, KVI_BIGICON_HELP, KVI_BIGICON_OPEN, KVI_BIGICON_PACK, KVI_BIGICON_REMOVE, KVI_BIGICON_WWW, m_pConfigureButton, m_pHelpButton, m_pInstance, m_pListWidget, m_pPackButton, m_pUninstallButton, KviMemory::move(), NULL, packScript(), KviTalHBox::setMargin(), KviTalHBox::setSpacing(), showScriptHelp(), uninstallScript(), and w.
Referenced by display().
AddonManagementDialog::~AddonManagementDialog ()
References g_rectManagementDialogGeometry, m_pInstance, NULL, x, and y.
Member Function Documentation
void AddonManagementDialog::cleanup () static
References m_pInstance.
Referenced by addon_module_cleanup(), and reject().
void AddonManagementDialog::closeClicked () protected slot
Referenced by AddonManagementDialog().
void AddonManagementDialog::closeEvent (QCloseEvent * e) protected virtual
void AddonManagementDialog::configureScript () protected slot
References AddonListViewItem::addon(), KviKvsScriptAddon::configureCallbackCode(), KviKvsScriptAddon::executeConfigureCallback(), g_pActiveWindow, and m_pListWidget.
Referenced by AddonManagementDialog().
void AddonManagementDialog::currentChanged (QListWidgetItem * i, QListWidgetItem *) protected slot
References AddonListViewItem::addon(), KviKvsScriptAddon::configureCallbackCode(), KviKvsScriptAddon::helpCallbackCode(), m_pConfigureButton, m_pHelpButton, and m_pUninstallButton.
Referenced by AddonManagementDialog(), installScript(), and uninstallScript().
void AddonManagementDialog::display (bool bTopLevel) static
References AddonManagementDialog(), g_pMainWindow, m_pInstance, and KviMainWindow::splitter().
Referenced by addon_kvs_cmd_dialog().
void AddonManagementDialog::fillListView () protected
References a, KviPointerHashTableIterator< Key, T >::current(), d, instance(), and m_pListWidget.
Referenced by AddonManagementDialog(), installScript(), and uninstallScript().
void AddonManagementDialog::getMoreScripts () protected slot
COMPILE_WEBKIT_SUPPORT
COMPILE_WEBKIT_SUPPORT
References g_pActiveWindow, KVI_SOURCES_DATE, KVI_VERSION, and KviIrcUrl::run().
Referenced by AddonManagementDialog().
void AddonManagementDialog::installScript () protected slot
References __tr2qs_ctx(), KviFileDialog::askForOpenFileName(), currentChanged(), fillListView(), AddonFunctions::installAddonPackage(), KVI_FILTER_ADDON, and AddonFunctions::notAValidAddonPackage().
Referenced by AddonManagementDialog().
static AddonManagementDialog* AddonManagementDialog::instance () inline static
References m_pInstance.
Referenced by addon_module_can_unload(), fillListView(), and uninstallScript().
void AddonManagementDialog::packScript () protected slot
Referenced by AddonManagementDialog().
void AddonManagementDialog::reject () protected virtual slot
References cleanup().
void AddonManagementDialog::showScriptHelp () protected slot
References AddonListViewItem::addon(), KviKvsScriptAddon::executeHelpCallback(), g_pActiveWindow, KviKvsScriptAddon::helpCallbackCode(), and m_pListWidget.
Referenced by AddonManagementDialog().
void AddonManagementDialog::uninstallScript () protected slot
References __tr2qs_ctx(), AddonListViewItem::addon(), currentChanged(), fillListView(), g_pActiveWindow, instance(), m_pListWidget, KviKvsScriptAddon::name(), and KviKvsScriptAddon::visibleName().
Referenced by AddonManagementDialog().
Member Data Documentation
QToolButton* AddonManagementDialog::m_pConfigureButton protected
Referenced by AddonManagementDialog(), and currentChanged().
QToolButton* AddonManagementDialog::m_pHelpButton protected
Referenced by AddonManagementDialog(), and currentChanged().
AddonManagementDialog * AddonManagementDialog::m_pInstance = 0 static protected
Referenced by AddonManagementDialog(), cleanup(), display(), instance(), and ~AddonManagementDialog().
KviTalListWidget* AddonManagementDialog::m_pListWidget protected
Referenced by AddonManagementDialog(), configureScript(), fillListView(), showScriptHelp(), and uninstallScript().
QToolButton* AddonManagementDialog::m_pPackButton protected
Referenced by AddonManagementDialog().
QToolButton* AddonManagementDialog::m_pUninstallButton protected
Referenced by AddonManagementDialog(), and currentChanged().
The documentation for this class was generated from the following files:
src/modules/addon/AddonManagementDialog.h
src/modules/addon/AddonManagementDialog.cpp