KVIrc: KviKvsTreeNodeHashReferenceAssert Class Reference
KviKvsTreeNodeHashReferenceAssert Class Reference
#include <KviKvsTreeNodeHashReferenceAssert.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isReadOnly ()
KviKvsTreeNodeHashReferenceAssert (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeHashReferenceAssert ()
Constructor & Destructor Documentation
KviKvsTreeNodeHashReferenceAssert::KviKvsTreeNodeHashReferenceAssert (const QChar * pLocation, KviKvsTreeNodeData * pSource)
KviKvsTreeNodeHashReferenceAssert::~KviKvsTreeNodeHashReferenceAssert ()
Member Function Documentation
void KviKvsTreeNodeHashReferenceAssert::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeHashReferenceAssert::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
bool KviKvsTreeNodeHashReferenceAssert::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Reimplemented from KviKvsTreeNodeData.
References evaluateReadOnlyInObjectScope().
bool KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsVariant::getTypeName(), KviKvsVariant::isHash(), KviKvsVariant::isNothing(), and KviKvsTreeNodeIndirectData::m_pSource.
Referenced by evaluateReadOnly().
KviKvsRWEvaluationResult * KviKvsTreeNodeHashReferenceAssert::evaluateReadWrite (KviKvsRunTimeContext * c) [virtual]
Reimplemented from KviKvsTreeNodeData.
References evaluateReadWriteInObjectScope().
KviKvsRWEvaluationResult * KviKvsTreeNodeHashReferenceAssert::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), KviKvsTreeNodeIndirectData::m_pSource, and r.
Referenced by evaluateReadWrite().
bool KviKvsTreeNodeHashReferenceAssert::isReadOnly () [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::isReadOnly(), and KviKvsTreeNodeIndirectData::m_pSource.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeHashReferenceAssert.h
src/kvirc/kvs/tree/KviKvsTreeNodeHashReferenceAssert.cpp