KVIrc: KviKvsTreeNodeCallbackCommand Class Reference
KviKvsTreeNodeCallbackCommand Class Reference
#include <KviKvsTreeNodeCallbackCommand.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
void dumpCallback (const char *prefix)
KviKvsTreeNodeCallbackCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params, KviKvsScript *pCallback)
~KviKvsTreeNodeCallbackCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommandWithParameters
void dumpParameterList (const char *prefix)
KviKvsTreeNodeCommandWithParameters (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
KviKvsTreeNodeDataList * params ()
~KviKvsTreeNodeCommandWithParameters ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
virtual bool execute (KviKvsRunTimeContext *c)=0
This is the main entry point to the tree visit.
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsScript * m_pCallback
Protected Attributes inherited from KviKvsTreeNodeCommandWithParameters
KviKvsTreeNodeDataList * m_pParams
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeCallbackCommand::KviKvsTreeNodeCallbackCommand (const QChar * pLocation, const QString & szCmdName, KviKvsTreeNodeDataList * params, KviKvsScript * pCallback)
References m_pCallback.
KviKvsTreeNodeCallbackCommand::~KviKvsTreeNodeCallbackCommand ()
References m_pCallback.
Member Function Documentation
void KviKvsTreeNodeCallbackCommand::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeCommandWithParameters.
Reimplemented in KviKvsTreeNodeCoreCallbackCommand, and KviKvsTreeNodeModuleCallbackCommand.
References KviKvsTreeNodeCommand::m_szCmdName.
void KviKvsTreeNodeCallbackCommand::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeCommandWithParameters.
Reimplemented in KviKvsTreeNodeCoreCallbackCommand, and KviKvsTreeNodeModuleCallbackCommand.
References dumpCallback(), KviKvsTreeNodeCommandWithParameters::dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), and KviKvsTreeNodeCommand::m_szCmdName.
void KviKvsTreeNodeCallbackCommand::dumpCallback (const char * prefix)
References KviKvsScript::dump(), and m_pCallback.
Referenced by dump(), KviKvsTreeNodeModuleCallbackCommand::dump(), and KviKvsTreeNodeCoreCallbackCommand::dump().
Member Data Documentation
KviKvsScript* KviKvsTreeNodeCallbackCommand::m_pCallback protected
Referenced by dumpCallback(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeCoreCallbackCommand::execute(), KviKvsTreeNodeCallbackCommand(), and ~KviKvsTreeNodeCallbackCommand().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeCallbackCommand.h
src/kvirc/kvs/tree/KviKvsTreeNodeCallbackCommand.cpp