KVIrc: PackThemeDialog Class Reference
PackThemeDialog Class Reference
#include <PackThemeDialog.h>
Public Member Functions
PackThemeDialog (QWidget *pParent, KviPointerList< KviThemeInfo > *pThemeInfoList)
~PackThemeDialog ()
Protected Member Functions
virtual void accept ()
bool packTheme ()
Protected Attributes
PackThemeDataWidget * m_pPackThemeDataWidget
PackThemeImageWidget * m_pPackThemeImageWidget
PackThemeInfoWidget * m_pPackThemeInfoWidget
PackThemeSaveWidget * m_pPackThemeSaveWidget
KviPointerList< KviThemeInfo > * m_pThemeInfoList
QString m_szAuthor
QString m_szDescription
QString m_szImagePath
QString m_szName
QString m_szPackagePath
QString m_szSavePath
QString m_szVersion
Constructor & Destructor Documentation
PackThemeDialog::PackThemeDialog (QWidget * pParent, KviPointerList< KviThemeInfo > * pThemeInfoList)
References __tr2qs_ctx(), g_pIconManager, KviIconManager::getBigIcon(), m_pPackThemeDataWidget, m_pPackThemeImageWidget, m_pPackThemeInfoWidget, m_pPackThemeSaveWidget, m_pThemeInfoList, and PackThemeDataWidget::parseThemes().
PackThemeDialog::~PackThemeDialog ()
Member Function Documentation
void PackThemeDialog::accept () [protected, virtual]
References packTheme().
bool PackThemeDialog::packTheme () [protected]
References __tr2qs, __tr2qs_ctx(), KviPackageWriter::addDirectory(), KviPackageWriter::addInfoField(), KviPointerList< T >::count(), f, KviPointerList< T >::first(), KviMessageBox::information(), KVI_CURRENT_THEME_ENGINE_VERSION, KVI_OPTION_UINT, KVI_SOURCES_DATE, KVI_VERSION, KviOption_uintOutputDatetimeFormat, KviPackageIOEngine::lastError(), m_pThemeInfoList, m_szAuthor, m_szDescription, m_szImagePath, m_szName, m_szPackagePath, m_szVersion, KviPointerList< T >::next(), and KviPackageWriter::pack().
Referenced by accept().
Member Data Documentation
PackThemeDataWidget* PackThemeDialog::m_pPackThemeDataWidget [protected]
Referenced by PackThemeDialog().
PackThemeImageWidget* PackThemeDialog::m_pPackThemeImageWidget [protected]
Referenced by PackThemeDialog().
PackThemeInfoWidget* PackThemeDialog::m_pPackThemeInfoWidget [protected]
Referenced by PackThemeDialog().
PackThemeSaveWidget* PackThemeDialog::m_pPackThemeSaveWidget [protected]
Referenced by PackThemeDialog().
KviPointerList<KviThemeInfo>* PackThemeDialog::m_pThemeInfoList [protected]
Referenced by packTheme(), and PackThemeDialog().
QString PackThemeDialog::m_szAuthor [protected]
Referenced by packTheme().
QString PackThemeDialog::m_szDescription [protected]
Referenced by packTheme().
QString PackThemeDialog::m_szImagePath [protected]
Referenced by packTheme().
QString PackThemeDialog::m_szName [protected]
Referenced by packTheme().
QString PackThemeDialog::m_szPackagePath [protected]
Referenced by packTheme().
QString PackThemeDialog::m_szSavePath [protected]
QString PackThemeDialog::m_szVersion [protected]
Referenced by packTheme().
The documentation for this class was generated from the following files:
src/modules/theme/PackThemeDialog.h
src/modules/theme/PackThemeDialog.cpp