KVIrc: KviKvsTreeNodeSpecialCommandDefpopupLabelPopup Class Reference
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup Class Reference
#include <KviKvsTreeNodeSpecialCommandDefpopup.h>
Public Member Functions
void addLabel (KviKvsTreeNodeSpecialCommandDefpopupLabel *pLabel)
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool execute (KviKvsRunTimeContext *c, KviKvsPopupMenu *p)
bool fill (KviKvsRunTimeContext *c, KviKvsPopupMenu *p)
bool isEmpty ()
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup (const QChar *pLocation)
~KviKvsTreeNodeSpecialCommandDefpopupLabelPopup ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon
KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon (const QChar *pLocation, const QString &szCondition, const QString &szText, const QString &szIcon, const QString &szItemName)
void setIcon (const QString &szIcon)
void setText (const QString &szText)
~KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel
KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel (const QChar *pLocation, const QString &szCondition, const QString &szItemName)
void setCondition (const QString &szCondition)
~KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommandDefpopupLabel
KviKvsTreeNodeSpecialCommandDefpopupLabel (const QChar *pLocation, const QString &szItemName)
void setItemName (const QString &szItemName)
~KviKvsTreeNodeSpecialCommandDefpopupLabel ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviPointerList
< KviKvsTreeNodeSpecialCommandDefpopupLabel > * m_pLabels
Protected Attributes inherited from KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon
QString m_szIcon
QString m_szText
Protected Attributes inherited from KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel
QString m_szCondition
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Public Attributes inherited from KviKvsTreeNodeSpecialCommandDefpopupLabel
QString m_szItemName
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::KviKvsTreeNodeSpecialCommandDefpopupLabelPopup (const QChar * pLocation)
References m_pLabels, and KviPointerList< T >::setAutoDelete().
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::~KviKvsTreeNodeSpecialCommandDefpopupLabelPopup ()
References m_pLabels.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::addLabel (KviKvsTreeNodeSpecialCommandDefpopupLabel * pLabel)
References KviPointerList< T >::append(), m_pLabels, and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseSpecialCommandDefpopupLabelPopup().
void KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Implements KviKvsTreeNode.
References KviPointerList< T >::first(), l, m_pLabels, KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel::m_szCondition, KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon::m_szIcon, KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon::m_szText, KviPointerList< T >::next(), and x.
Referenced by KviKvsTreeNodeSpecialCommandDefpopup::dump().
bool KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::execute (KviKvsRunTimeContext * c, KviKvsPopupMenu * p) virtual
Implements KviKvsTreeNodeSpecialCommandDefpopupLabel.
References KviKvsPopupMenu::addPopup(), fill(), KviKvsPopupMenu::findChildPopupByName(), KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel::m_szCondition, KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon::m_szIcon, KviKvsTreeNodeSpecialCommandDefpopupLabel::m_szItemName, and KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon::m_szText.
bool KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::fill (KviKvsRunTimeContext * c, KviKvsPopupMenu * p)
References KviPointerList< T >::first(), l, m_pLabels, and KviPointerList< T >::next().
Referenced by execute(), and KviKvsTreeNodeSpecialCommandDefpopup::execute().
bool KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::isEmpty () inline
Referenced by KviKvsTreeNodeSpecialCommandDefpopup::execute().
Member Data Documentation
KviPointerList<KviKvsTreeNodeSpecialCommandDefpopupLabel>* KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::m_pLabels protected
Referenced by addLabel(), dump(), fill(), KviKvsTreeNodeSpecialCommandDefpopupLabelPopup(), and ~KviKvsTreeNodeSpecialCommandDefpopupLabelPopup().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandDefpopup.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandDefpopup.cpp