KVIrc: KviMircryptionEngine Class Reference
KviMircryptionEngine Class Reference
#include <libkvirijndael_cryptopp.h>
Public Member Functions
virtual
KviCryptEngine::DecryptResult decrypt (const char *pcInBuffer, KviCString &szPlainText)
virtual
KviCryptEngine::EncryptResult encrypt (const char *pcPlainText, KviCString &szOutBuffer)
virtual bool init (const char *pcEncKey, int iEncKeyLen, const char *pcDecKey, int iDecKeyLen)
KviMircryptionEngine ()
~KviMircryptionEngine ()
Private Attributes
bool m_bDecryptCBC
bool m_bEncryptCBC
std::string m_szDecKey
std::string m_szEncKey
Constructor & Destructor Documentation
KviMircryptionEngine::KviMircryptionEngine ()
References KviPointerList< T >::append(), m_szDecKey, and m_szEncKey.
KviMircryptionEngine::~KviMircryptionEngine ()
References m_szDecKey, m_szEncKey, and KviPointerList< T >::removeRef().
Member Function Documentation
KviCryptEngine::DecryptResult KviMircryptionEngine::decrypt (const char * pcInBuffer, KviCString & szPlainText) [virtual]
References __tr2qs, UglyBase64::decode(), KviCryptEngine::DecryptError, KviCryptEngine::DecryptOkWasEncrypted, KviCryptEngine::DecryptOkWasPlainText, e, KviMemory::free(), m_bDecryptCBC, m_szDecKey, and u.
KviCryptEngine::EncryptResult KviMircryptionEngine::encrypt (const char * pcPlainText, KviCString & szOutBuffer) [virtual]
References __tr2qs, e, UglyBase64::encode(), KviCryptEngine::Encrypted, KviCryptEngine::EncryptError, m_bEncryptCBC, m_szEncKey, KviCString::prepend(), and u.
bool KviMircryptionEngine::init (const char * pcEncKey, int iEncKeyLen, const char * pcDecKey, int iDecKeyLen) [virtual]
References __tr2qs, m_bDecryptCBC, m_bEncryptCBC, m_szDecKey, and m_szEncKey.
Member Data Documentation
bool KviMircryptionEngine::m_bDecryptCBC [private]
Referenced by decrypt(), and init().
bool KviMircryptionEngine::m_bEncryptCBC [private]
Referenced by encrypt(), and init().
std::string KviMircryptionEngine::m_szDecKey [private]
Referenced by decrypt(), init(), KviMircryptionEngine(), and ~KviMircryptionEngine().
std::string KviMircryptionEngine::m_szEncKey [private]
Referenced by encrypt(), init(), KviMircryptionEngine(), and ~KviMircryptionEngine().
The documentation for this class was generated from the following files:
src/modules/rijndael/libkvirijndael_cryptopp.h
src/modules/rijndael/libkvirijndael_cryptopp.cpp