KVIrc: OptionsWidget_ctcpFloodProtection Class Reference
OptionsWidget_ctcpFloodProtection Class Reference
#include <OptionsWidget_ctcpFloodProtection.h>
Public Member Functions
OptionsWidget_ctcpFloodProtection (QWidget *parent)
~OptionsWidget_ctcpFloodProtection ()
Constructor & Destructor Documentation
OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolIgnoreCtcpAvatar, KviOption_boolIgnoreCtcpClientinfo, KviOption_boolIgnoreCtcpDcc, KviOption_boolIgnoreCtcpFinger, KviOption_boolIgnoreCtcpPage, KviOption_boolIgnoreCtcpPing, KviOption_boolIgnoreCtcpSource, KviOption_boolIgnoreCtcpTime, KviOption_boolIgnoreCtcpUserinfo, KviOption_boolIgnoreCtcpVersion, KviOption_boolUseCtcpFloodProtection, KviOption_uintCtcpFloodCheckInterval, KviOption_uintMaxCtcpRequests, KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_ctcpFloodProtection::~OptionsWidget_ctcpFloodProtection ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_ctcpFloodProtection.h
src/modules/options/OptionsWidget_ctcpFloodProtection.cpp