KVIrc: KviIrcMessage Class Reference
KviIrcMessage Class Reference
#include <KviIrcMessage.h>
Public Types
enum Flags { HaltOutput = 1, Unrecognized = 2 }
Public Member Functions
const char * allParams ()
const char * command ()
KviCString * commandPtr ()
KviIrcConnection * connection ()
KviConsoleWindow * console ()
void decodeAndSplitMask (char *mask, QString &szNick, QString &szUser, QString &szHost)
void decodeAndSplitPrefix (QString &szNick, QString &szUser, QString &szHost)
KviCString * firstParam ()
bool haltOutput ()
bool hasPrefix ()
bool isEmpty ()
bool isNumeric ()
KviIrcMessage (const char *message, KviIrcConnection *pConnection)
KviCString * nextParam ()
int numeric ()
const char * param (unsigned int idx)
int paramCount ()
KviCString * paramString (unsigned int idx)
const char * prefix ()
KviCString * prefixPtr ()
const char * safeParam (unsigned int idx)
const char * safePrefix ()
const char * safeTrailing ()
KviCString & safeTrailingString ()
void setHaltOutput ()
void setUnrecognized ()
const char * trailing ()
KviCString * trailingString ()
bool unrecognized ()
~KviIrcMessage ()
Private Attributes
int m_iFlags
int m_iNumericCommand
KviIrcConnection * m_pConnection
KviConsoleWindow * m_pConsole
KviPointerList< KviCString > * m_pParams
const char * m_ptr
KviCString m_szCommand
KviCString m_szPrefix
Member Enumeration Documentation
enum KviIrcMessage::Flags
The message flags.
Enumerator:
HaltOutput
Some message processing step (most likely a script handler) requested to stop further message related output.
Unrecognized
The message is marked as unrecognized.
Constructor & Destructor Documentation
KviIrcMessage::KviIrcMessage (const char * message, KviIrcConnection * pConnection)
References allParams(), KviPointerList< T >::append(), KviIrcConnection::console(), KviCString::extractFromString(), KviCString::len(), m_iFlags, m_iNumericCommand, m_pConnection, m_pConsole, m_pParams, m_ptr, m_szCommand, m_szPrefix, KviCString::ptr(), KviPointerList< T >::setAutoDelete(), and KviCString::toUpper().
KviIrcMessage::~KviIrcMessage ()
References m_pParams.
Member Function Documentation
const char* KviIrcMessage::allParams () [inline]
Referenced by KviIrcMessage(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericWatch(), ListWindow::processData(), and LinksWindow::processData().
const char* KviIrcMessage::command () [inline]
Referenced by KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericIsOn(), and KviIrcServerParser::parseNumericWatch().
KviCString* KviIrcMessage::commandPtr () [inline]
KviIrcConnection* KviIrcMessage::connection () [inline]
Referenced by KviIrcServerParser::checkCtcpFlood(), decodeAndSplitPrefix(), KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCommandEndOfHelp(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseCtcpReply(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseCtcpReplyUserinfo(), KviIrcServerParser::parseCtcpRequest(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseCtcpRequestFinger(), KviIrcServerParser::parseCtcpRequestPage(), KviIrcServerParser::parseCtcpRequestPing(), KviIrcServerParser::parseLiteralAuthenticate(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericCommandSyntax(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfStats(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericInfo(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchChannel(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericSaslSuccess(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericServerAdminInfoTitle(), KviIrcServerParser::parseNumericStartTls(), KviIrcServerParser::parseNumericStats(), KviIrcServerParser::parseNumericTime(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericWatch(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhowasUser(), KviIrcServerParser::parseUserMode(), ListWindow::processData(), KviIrcServerParser::replyCtcp(), and safePrefix().
KviConsoleWindow* KviIrcMessage::console () [inline]
Referenced by dcc_module_reply_errmsg(), dcc_module_request_error(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), dccModuleParseDccVoice(), KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), DccBroker::handleResumeRequest(), KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseCommandEndOfHelp(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseCtcpReply(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpReplyLagcheck(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseCtcpReplyUserinfo(), KviIrcServerParser::parseCtcpRequest(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestAvatar(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric020(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericCommandSyntax(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfLinks(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfStats(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericInfo(), KviIrcServerParser::parseNumericInfoEnd(), KviIrcServerParser::parseNumericInfoStart(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericListEnd(), KviIrcServerParser::parseNumericListStart(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchChannel(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericSaslSuccess(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericServerAdminInfoTitle(), KviIrcServerParser::parseNumericStartTls(), KviIrcServerParser::parseNumericStats(), KviIrcServerParser::parseNumericTime(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericUserMode(), KviIrcServerParser::parseNumericWatch(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhowasUser(), and KviIrcServerParser::parseUserMode().
void KviIrcMessage::decodeAndSplitMask (char * mask, QString & szNick, QString & szUser, QString & szHost)
References KviIrcConnection::decodeText(), m_pConnection, and p.
Referenced by decodeAndSplitPrefix().
void KviIrcMessage::decodeAndSplitPrefix (QString & szNick, QString & szUser, QString & szHost)
References connection(), KviIrcConnection::currentServerName(), decodeAndSplitMask(), KviCString::hasData(), m_szPrefix, and KviCString::ptr().
Referenced by KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), and KviIrcServerParser::parseLiteralWallops().
KviCString* KviIrcMessage::firstParam () [inline]
Referenced by KviIrcServerParser::parseMessage(), and KviIrcServerParser::parseNumericStats().
bool KviIrcMessage::haltOutput () [inline]
Referenced by dcc_module_normalize_target_data(), dccModuleCtcpDccParseRoutine(), dccModuleParseDccAccept(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccResume(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), dccModuleParseDccVoice(), KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCommandEndOfHelp(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric020(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericCommandSyntax(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfLinks(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfStats(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericInfo(), KviIrcServerParser::parseNumericInfoEnd(), KviIrcServerParser::parseNumericInfoStart(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericListEnd(), KviIrcServerParser::parseNumericListStart(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchChannel(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericSaslSuccess(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericServerAdminInfoTitle(), KviIrcServerParser::parseNumericStartTls(), KviIrcServerParser::parseNumericStats(), KviIrcServerParser::parseNumericTime(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericUserMode(), KviIrcServerParser::parseNumericWatch(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), and KviIrcServerParser::parseNumericWhowasUser().
bool KviIrcMessage::hasPrefix () [inline]
bool KviIrcMessage::isEmpty () [inline]
Referenced by KviIrcServerParser::parseMessage().
bool KviIrcMessage::isNumeric () [inline]
Referenced by KviIrcServerParser::parseMessage().
KviCString* KviIrcMessage::nextParam () [inline]
Referenced by KviIrcServerParser::parseMessage(), and KviIrcServerParser::parseNumericStats().
int KviIrcMessage::numeric () [inline]
Referenced by KviWatchNotifyListManager::doMatchUser(), KviWatchNotifyListManager::handleWatchReply(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericStartTls(), and KviIrcServerParser::parseNumericWhoisAuth().
const char* KviIrcMessage::param (unsigned int idx) [inline]
Referenced by KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), and KviIrcServerParser::parseNumeric005().
int KviIrcMessage::paramCount () [inline]
Referenced by KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), and KviIrcServerParser::parseNumericStats().
KviCString* KviIrcMessage::paramString (unsigned int idx) [inline]
References KviCString::at().
const char* KviIrcMessage::prefix () [inline]
Referenced by KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericInfoEnd(), KviIrcServerParser::parseNumericInfoStart(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericTime(), and KviIrcServerParser::parseNumericWatch().
KviCString* KviIrcMessage::prefixPtr () [inline]
const char* KviIrcMessage::safeParam (unsigned int idx) [inline]
References KviCString::emptyString(), and KviCString::ptr().
Referenced by KviWatchNotifyListManager::handleWatchReply(), KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCommandEndOfHelp(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseLiteralAuthenticate(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchChannel(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserMode(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhowasUser(), ListWindow::processData(), and LinksWindow::processData().
const char * KviIrcMessage::safePrefix ()
References connection(), KviIrcConnection::currentServerName(), KviCString::hasData(), m_szPrefix, and KviCString::ptr().
Referenced by KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric020(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), and KviIrcServerParser::parseNumericIsOn().
const char* KviIrcMessage::safeTrailing () [inline]
References KviCString::emptyString(), and KviCString::ptr().
Referenced by KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric020(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCommandSyntax(), KviIrcServerParser::parseNumericEndOfStats(), KviIrcServerParser::parseNumericInfo(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericServerAdminInfoTitle(), KviIrcServerParser::parseNumericStats(), KviIrcServerParser::parseNumericTime(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhowasUser(), ListWindow::processData(), and LinksWindow::processData().
KviCString& KviIrcMessage::safeTrailingString () [inline]
References KviCString::emptyString().
Referenced by KviIrcServerParser::parseNumericNames().
void KviIrcMessage::setHaltOutput () [inline]
Referenced by KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), and KviIrcServerParser::parseUserMode().
void KviIrcMessage::setUnrecognized () [inline]
const char* KviIrcMessage::trailing () [inline]
References KviCString::ptr().
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), and KviIsOnNotifyListManager::handleUserhost().
KviCString* KviIrcMessage::trailingString () [inline]
Referenced by KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
bool KviIrcMessage::unrecognized () [inline]
Referenced by KviIrcServerParser::parseMessage().
Member Data Documentation
int KviIrcMessage::m_iFlags [private]
Referenced by KviIrcMessage().
int KviIrcMessage::m_iNumericCommand [private]
Referenced by KviIrcMessage().
KviIrcConnection* KviIrcMessage::m_pConnection [private]
Referenced by decodeAndSplitMask(), and KviIrcMessage().
KviConsoleWindow* KviIrcMessage::m_pConsole [private]
Referenced by KviIrcMessage().
KviPointerList<KviCString>* KviIrcMessage::m_pParams [private]
Referenced by KviIrcMessage(), and ~KviIrcMessage().
const char* KviIrcMessage::m_ptr [private]
Referenced by KviIrcMessage().
KviCString KviIrcMessage::m_szCommand [private]
Referenced by KviIrcMessage().
KviCString KviIrcMessage::m_szPrefix [private]
Referenced by decodeAndSplitPrefix(), KviIrcMessage(), and safePrefix().
The documentation for this class was generated from the following files:
src/kvirc/sparser/KviIrcMessage.h
src/kvirc/sparser/KviIrcMessage.cpp