KVIrc: KviMaskEditor Class Reference
KviMaskEditor Class Reference
#include <KviMaskEditor.h>
Signals
void removeMasks (KviMaskEditor *, KviPointerList< KviMaskEntry > *)
Public Member Functions
void addMask (KviMaskEntry *e)
void clear ()
char flag ()
KviMaskEditor (QWidget *par, KviChannelWindow *pChannel, KviWindowToolPageButton *button, KviPointerList< KviMaskEntry > *maskList, char cMode, const char *name)
void removeMask (KviMaskEntry *e)
~KviMaskEditor ()
Public Member Functions inherited from KviWindowToolWidget
KviWindowToolWidget (QWidget *pParent, KviWindowToolPageButton *pButton)
~KviWindowToolWidget ()
Protected Slots
void addClicked ()
void itemDoubleClicked (QTreeWidgetItem *, int)
void removeClicked ()
void searchTextChanged (const QString &)
void updateOpStatus ()
Protected Attributes
char m_cFlag
KviIconManager::SmallIcon m_eIcon
QPushButton * m_pAddButton
KviChannelWindow * m_pChannel
QTreeWidget * m_pMaskBox
QPushButton * m_pRemoveMask
QLineEdit * m_pSearch
Protected Attributes inherited from KviWindowToolWidget
KviWindowToolPageButton * m_pButton
Constructor & Destructor Documentation
KviMaskEditor::KviMaskEditor (QWidget * par, KviChannelWindow * pChannel, KviWindowToolPageButton * button, KviPointerList< KviMaskEntry > * maskList, char cMode, const char * name)
References __tr2qs, addClicked(), addMask(), KviIconManager::Ban, KviIconManager::BanExcept, KviIconManager::ChanAdmin, KviIconManager::ChanOwner, connect(), KviIconManager::DeleteItem, e, KviPointerList< T >::first(), g, g_pIconManager, KviIrcConnectionServerInfo::getChannelModeDescription(), KviIconManager::getSmallIcon(), KviIconManager::InviteExcept, itemDoubleClicked(), l, m_cFlag, m_eIcon, m_pAddButton, m_pChannel, m_pMaskBox, m_pRemoveMask, m_pSearch, KviIconManager::NewItem, KviPointerList< T >::next(), removeClicked(), searchTextChanged(), KviChannelWindow::serverInfo(), and updateOpStatus().
KviMaskEditor::~KviMaskEditor ()
Member Function Documentation
void KviMaskEditor::addClicked () protected slot
References KviWindow::connection(), KviIrcConnectionUserInfo::hasUserMode(), KviChannelWindow::isMeChanAdmin(), KviChannelWindow::isMeChanOwner(), KviChannelWindow::isMeHalfOp(), KviChannelWindow::isMeOp(), m_pChannel, and KviIrcConnection::userInfo().
Referenced by KviMaskEditor().
void KviMaskEditor::addMask (KviMaskEntry * e)
References g_pIconManager, KviIconManager::getSmallIcon(), m_eIcon, and m_pMaskBox.
Referenced by KviMaskEditor().
void KviMaskEditor::clear ()
References m_pMaskBox.
char KviMaskEditor::flag () inline
Referenced by KviMaskInputDialog::accept(), and KviChannelWindow::removeMasks().
void KviMaskEditor::itemDoubleClicked (QTreeWidgetItem * pItem, int) protected slot
References KviWindow::connection(), KviIrcConnectionUserInfo::hasUserMode(), KviChannelWindow::isMeChanAdmin(), KviChannelWindow::isMeChanOwner(), KviChannelWindow::isMeHalfOp(), KviChannelWindow::isMeOp(), m_pChannel, and KviIrcConnection::userInfo().
Referenced by KviMaskEditor().
void KviMaskEditor::removeClicked () protected slot
References KviPointerList< T >::append(), KviPointerList< T >::count(), e, i, l, m_pMaskBox, KviMaskItem::mask(), removeMasks(), KviPointerList< T >::setAutoDelete(), _KviMaskEntry::szMask, _KviMaskEntry::szSetBy, and _KviMaskEntry::uSetAt.
Referenced by KviMaskEditor().
void KviMaskEditor::removeMask (KviMaskEntry * e)
References KviQString::equalCI(), i, m_pMaskBox, KviMaskItem::mask(), and _KviMaskEntry::szMask.
void KviMaskEditor::removeMasks (KviMaskEditor * , KviPointerList< KviMaskEntry > *) signal
Referenced by removeClicked().
void KviMaskEditor::searchTextChanged (const QString & text) protected slot
References i, m_pMaskBox, KviMaskItem::mask(), and _KviMaskEntry::szMask.
Referenced by KviMaskEditor().
void KviMaskEditor::updateOpStatus () protected slot
References KviWindow::connection(), KviIrcConnectionUserInfo::hasUserMode(), KviChannelWindow::isMeChanAdmin(), KviChannelWindow::isMeChanOwner(), KviChannelWindow::isMeHalfOp(), KviChannelWindow::isMeOp(), m_pAddButton, m_pChannel, m_pRemoveMask, and KviIrcConnection::userInfo().
Referenced by KviMaskEditor().
Member Data Documentation
char KviMaskEditor::m_cFlag protected
Referenced by KviMaskEditor().
KviIconManager::SmallIcon KviMaskEditor::m_eIcon protected
Referenced by addMask(), and KviMaskEditor().
QPushButton* KviMaskEditor::m_pAddButton protected
Referenced by KviMaskEditor(), and updateOpStatus().
KviChannelWindow* KviMaskEditor::m_pChannel protected
Referenced by addClicked(), itemDoubleClicked(), KviMaskEditor(), and updateOpStatus().
QTreeWidget* KviMaskEditor::m_pMaskBox protected
Referenced by addMask(), clear(), KviMaskEditor(), removeClicked(), removeMask(), and searchTextChanged().
QPushButton* KviMaskEditor::m_pRemoveMask protected
Referenced by KviMaskEditor(), and updateOpStatus().
QLineEdit* KviMaskEditor::m_pSearch protected
Referenced by KviMaskEditor().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviMaskEditor.h
src/kvirc/ui/KviMaskEditor.cpp