KVIrc: DccFileTransferBandwidthDialog Class Reference
DccFileTransferBandwidthDialog Class Reference
#include <DccFileTransfer.h>
Public Member Functions
DccFileTransferBandwidthDialog (QWidget *pParent, DccFileTransfer *t)
~DccFileTransferBandwidthDialog ()
Protected Slots
void cancelClicked ()
void okClicked ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
QCheckBox * m_pEnableLimitCheck
QSpinBox * m_pLimitBox
DccFileTransfer * m_pTransfer
Constructor & Destructor Documentation
DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog (QWidget * pParent, DccFileTransfer * t)
References __tr2qs_ctx(), DccFileTransfer::bandwidthLimit(), cancelClicked(), connect(), g, KviFileTransfer::id(), DccFileTransfer::isFileUpload(), m_pEnableLimitCheck, m_pLimitBox, m_pTransfer, MAX_DCC_BANDWIDTH_LIMIT, okClicked(), and t().
DccFileTransferBandwidthDialog::~DccFileTransferBandwidthDialog ()
Member Function Documentation
void DccFileTransferBandwidthDialog::cancelClicked () [protected, slot]
Referenced by DccFileTransferBandwidthDialog().
void DccFileTransferBandwidthDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void DccFileTransferBandwidthDialog::okClicked () [protected, slot]
References m_pEnableLimitCheck, m_pLimitBox, m_pTransfer, MAX_DCC_BANDWIDTH_LIMIT, and DccFileTransfer::setBandwidthLimit().
Referenced by DccFileTransferBandwidthDialog().
Member Data Documentation
QCheckBox* DccFileTransferBandwidthDialog::m_pEnableLimitCheck [protected]
Referenced by DccFileTransferBandwidthDialog(), and okClicked().
QSpinBox* DccFileTransferBandwidthDialog::m_pLimitBox [protected]
Referenced by DccFileTransferBandwidthDialog(), and okClicked().
DccFileTransfer* DccFileTransferBandwidthDialog::m_pTransfer [protected]
Referenced by DccFileTransferBandwidthDialog(), and okClicked().
The documentation for this class was generated from the following files:
src/modules/dcc/DccFileTransfer.h
src/modules/dcc/DccFileTransfer.cpp