KVIrc: KviKvsAsyncOperation Class Reference
KviKvsAsyncOperation Class Reference
#include <kvi_kvs_asyncoperation.h>
Public Member Functions
KviKvsAsyncOperation (KviWindow *pWnd)
KviWindow * window ()
virtual ~KviKvsAsyncOperation ()
Protected Attributes
KviWindow * m_pWnd
Constructor & Destructor Documentation
KviKvsAsyncOperation::KviKvsAsyncOperation (KviWindow * pWnd)
References KviKvsKernel::asyncOperationManager(), KviKvsKernel::instance(), m_pWnd, and KviKvsAsyncOperationManager::registerOperation().
KviKvsAsyncOperation::~KviKvsAsyncOperation () [virtual]
References KviKvsKernel::asyncOperationManager(), KviKvsKernel::instance(), and KviKvsAsyncOperationManager::unregisterOperation().
Member Function Documentation
KviWindow* KviKvsAsyncOperation::window () [inline]
Referenced by KviKvsAsyncDnsOperation::lookupTerminated().
Member Data Documentation
KviWindow* KviKvsAsyncOperation::m_pWnd [protected]
Referenced by KviKvsAsyncOperation().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_asyncoperation.h
src/kvirc/kvs/kvi_kvs_asyncoperation.cpp