KVIrc: SetupPage Class Reference
SetupPage Class Reference
#include <SetupWizard.h>
Public Member Functions
SetupPage (SetupWizard *w)
~SetupPage ()
Public Attributes
QLabel * m_pPixmapLabel
QLabel * m_pTextLabel
KviTalVBox * m_pVBox
Constructor & Destructor Documentation
SetupPage::SetupPage (SetupWizard * w)
References __tr2qs, g, KVI_VERSION, l, SetupWizard::m_pLabelPixmap, m_pPixmapLabel, m_pTextLabel, m_pVBox, KviTalVBox::setMargin(), KviTalVBox::setSpacing(), and KviTalVBox::setStretchFactor().
SetupPage::~SetupPage ()
Member Data Documentation
QLabel* SetupPage::m_pPixmapLabel
Referenced by SetupPage().
QLabel* SetupPage::m_pTextLabel
Referenced by SetupPage(), and SetupWizard::SetupWizard().
KviTalVBox* SetupPage::m_pVBox
Referenced by SetupPage(), and SetupWizard::SetupWizard().
The documentation for this class was generated from the following files:
src/modules/setup/SetupWizard.h
src/modules/setup/SetupWizard.cpp