KVIrc: KviPixmap Class Reference
KviPixmap Class Reference
#include <KviPixmap.h>
Public Member Functions
bool isNull ()
KviPixmap ()
KviPixmap (const char *path)
KviPixmap (const KviPixmap &pix)
bool load (const char *path)
bool load (const QString &path)
KviPixmap & operator= (const KviPixmap &pix)
const QString & path () const
QPixmap * pixmap () const
void set (const QPixmap &pix, const QString &szPath)
void setNull ()
~KviPixmap ()
Private Attributes
QPixmap * m_pPix
QString m_szPath
Constructor & Destructor Documentation
KviPixmap::KviPixmap ()
References m_pPix.
KviPixmap::KviPixmap (const char * path)
References load(), and m_pPix.
KviPixmap::KviPixmap (const KviPixmap & pix)
References m_pPix, m_szPath, path(), and pixmap().
KviPixmap::~KviPixmap ()
References m_pPix.
Member Function Documentation
bool KviPixmap::isNull () [inline]
Referenced by RegistrationWizard::accept(), RegisteredUserEntryDialog::editAllPropertiesClicked(), RegisteredUserEntryDialog::okClicked(), KviPixmapSelector::setImagePath(), and KviPixmapPreview::setPixmap().
bool KviPixmap::load (const char * path)
References m_pPix, m_szPath, and path().
Referenced by OptionsWidget_identityAvatar::chooseAvatar(), KviStringConversion::fromString(), KviPixmap(), and KviPixmapSelector::setImagePath().
bool KviPixmap::load (const QString & path)
References m_pPix, m_szPath, and path().
KviPixmap & KviPixmap::operator= (const KviPixmap & pix)
References KviQString::equalCI(), m_pPix, m_szPath, path(), and pixmap().
const QString& KviPixmap::path () const [inline]
Referenced by RegistrationWizard::accept(), OptionsWidget_identityAvatar::chooseAvatar(), RegisteredUserEntryDialog::editAllPropertiesClicked(), KviPixmap(), KviPixmapSelector::KviPixmapSelector(), load(), RegisteredUserEntryDialog::okClicked(), operator=(), and KviStringConversion::toString().
QPixmap* KviPixmap::pixmap () const [inline]
Referenced by OptionsWidget_identityAvatar::chooseAvatar(), OptionsWidget_identityAvatar::commit(), KviPixmap(), KviPixmapSelector::KviPixmapSelector(), operator=(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), KviPixmapPreview::setPixmap(), and KviChannelWindow::showDoubleView().
void KviPixmap::set (const QPixmap & pix, const QString & szPath)
References m_pPix, m_szPath, and setNull().
Referenced by OptionsWidget_identityAvatar::chooseAvatar().
void KviPixmap::setNull ()
References m_pPix, and m_szPath.
Referenced by OptionsWidget_identityAvatar::chooseAvatar(), KviStringConversion::fromString(), and set().
Member Data Documentation
QPixmap* KviPixmap::m_pPix [private]
Referenced by KviPixmap(), load(), operator=(), set(), setNull(), and ~KviPixmap().
QString KviPixmap::m_szPath [private]
Referenced by KviPixmap(), load(), operator=(), set(), and setNull().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviPixmap.h
src/kvilib/ext/KviPixmap.cpp