KVIrc: KviInputHistory Class Reference
KviInputHistory Class Reference
Input history class.
#include <KviInputHistory.h>
Public Member Functions
void add (QString *szString)
Adds a string to the history.
unsigned int count ()
Returns the number of instances of the class.
KviInputHistory ()
Constructs the input history object.
KviPointerList< QString > * list ()
Returns the list of string in the history.
void load (const QString &szFileName)
Loads the history.
void save (const QString &szFileName)
Saves the history.
~KviInputHistory ()
Destroys the input history object.
Static Public Member Functions
static void addRef ()
Adds a reference to the class.
static void delRef ()
Removes a reference to the class.
static void done ()
Destroys the class instance.
static void init ()
Initializes the class instance.
static KviInputHistory * instance ()
Returns the instance of the class.
Protected Attributes
KviPointerList< QString > * m_pStringList
Static Private Attributes
static KviInputHistory * m_pSelf = NULL
static unsigned int m_uCount = 0
Detailed Description
Input history class.
Constructor & Destructor Documentation
KviInputHistory::KviInputHistory ()
Constructs the input history object.
Returns:
KviInputHistory
References m_pStringList, and KviPointerList< T >::setAutoDelete().
Referenced by init().
KviInputHistory::~KviInputHistory ()
Destroys the input history object.
References m_pStringList.
Member Function Documentation
void KviInputHistory::add (QString * szString)
Adds a string to the history.
Parameters:
szString The string to add
Returns:
void
References KviPointerList< T >::count(), KviPointerList< T >::insert(), KVI_INPUT_MAX_GLOBAL_HISTORY_ENTRIES, m_pStringList, and KviPointerList< T >::removeLast().
Referenced by load(), KviInputEditor::returnPressed(), KviInputEditor::sendKvs(), and KviInputEditor::sendPlain().
void KviInputHistory::addRef () static
Adds a reference to the class.
Returns:
void
References m_uCount.
Referenced by init().
unsigned int KviInputHistory::count () inline
Returns the number of instances of the class.
Returns:
unsigned int
Referenced by done(), and init().
void KviInputHistory::delRef () static
Removes a reference to the class.
Returns:
void
References m_uCount.
Referenced by done().
void KviInputHistory::done () static
Destroys the class instance.
Returns:
void
References count(), delRef(), and m_pSelf.
void KviInputHistory::init () static
Initializes the class instance.
Returns:
void
References addRef(), count(), KviInputHistory(), and m_pSelf.
static KviInputHistory* KviInputHistory::instance () inline static
Returns the instance of the class.
Returns:
KviInputHistory *
Referenced by KviHistoryWindow::fill(), KviInput::history(), KviInputEditor::returnPressed(), KviApplication::saveInputHistory(), KviInputEditor::sendKvs(), KviInputEditor::sendPlain(), and KviApplication::setup().
KviPointerList<QString>* KviInputHistory::list () inline
Returns the list of string in the history.
Returns:
KviPointerList<QString> *
Referenced by KviHistoryWindow::fill().
void KviInputHistory::load (const QString & szFileName)
Loads the history.
Parameters:
szFileName The name of the file to load
Returns:
void
References add(), c, i, KVI_INPUT_MAX_GLOBAL_HISTORY_ENTRIES, KviCString::ptr(), KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviConfigurationFile::readIntEntry(), and KviCString::sprintf().
Referenced by KviApplication::setup().
void KviInputHistory::save (const QString & szFileName)
Saves the history.
Parameters:
szFileName The name of the file where to save
Returns:
void
References c, KviConfigurationFile::clear(), KviPointerList< T >::count(), KviPointerList< T >::first(), m_pStringList, KviPointerList< T >::next(), KviCString::ptr(), KviCString::sprintf(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveInputHistory().
Member Data Documentation
KviInputHistory * KviInputHistory::m_pSelf = NULL static private
Referenced by done(), and init().
KviPointerList<QString>* KviInputHistory::m_pStringList protected
Referenced by add(), KviInputHistory(), save(), and ~KviInputHistory().
unsigned int KviInputHistory::m_uCount = 0 static private
Referenced by addRef(), and delRef().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviInputHistory.h
src/kvirc/ui/KviInputHistory.cpp