KVIrc: QFtpPrivate Class Reference
QFtpPrivate Class Reference
Public Member Functions
void _q_piConnectState (int)
void _q_piError (int, const QString &)
void _q_piFinished (const QString &)
void _q_piFtpReply (int, const QString &)
void _q_startNextCommand ()
int addCommand (QFtpCommand *cmd)
QFtpPrivate (QFtp *owner)
~QFtpPrivate ()
Public Attributes
bool close_waitForStateChange
QFtp::Error error
QString errorString
QString host
QList< QFtpCommand * > pending
QFtpPI pi
quint16 port
QString proxyHost
quint16 proxyPort
QFtp * q_ptr
QFtp::State state
QFtp::TransferMode transferMode
Constructor & Destructor Documentation
QFtpPrivate::QFtpPrivate (QFtp * owner) inline
QFtpPrivate::~QFtpPrivate () inline
References pending.
Member Function Documentation
void QFtpPrivate::_q_piConnectState (int connectState)
References _q_piFinished(), close_waitForStateChange, and state.
void QFtpPrivate::_q_piError (int errorCode, const QString & text)
References _q_startNextCommand(), c, QFtp::Cd, QFtpPI::clearPendingCommands(), QFtpCommand::command, QFtp::ConnectToHost, QFtpPI::currentCommand(), QFtpPI::dtp, error, errorString, QFtp::Get, QFtpCommand::id, QFtp::List, QFtp::Login, QFtp::Mkdir, pending, pi, QFtp::Put, q, QFtp::Remove, QFtp::Rmdir, and QFtpDTP::setBytesTotal().
void QFtpPrivate::_q_piFinished (const QString &)
References _q_startNextCommand(), c, QFtp::Close, close_waitForStateChange, QFtpCommand::command, QFtpCommand::id, pending, state, and QFtp::Unconnected.
Referenced by _q_piConnectState(), and _q_startNextCommand().
void QFtpPrivate::_q_piFtpReply (int code, const QString & text)
References pi, QFtp::RawCommand, and QFtpPI::rawCommand.
void QFtpPrivate::_q_startNextCommand ()
References _q_piFinished(), QFtpCommand::ba, c, QFtp::Close, QFtp::Closing, QFtpCommand::command, QFtp::ConnectToHost, QFtpPI::connectToHost(), QFtpCommand::data, QFtpCommand::dev, QFtpPI::dtp, error, errorString, QFtp::Get, host, QFtpCommand::id, QFtpCommand::is_ba, QFtp::Login, QFtp::NoError, pending, pi, port, proxyHost, proxyPort, QFtp::Put, q, QFtpCommand::rawCmds, QFtpPI::sendCommands(), QFtpDTP::setBytesTotal(), QFtpDTP::setData(), QFtpDTP::setDevice(), QFtp::SetProxy, QFtp::SetTransferMode, and state.
Referenced by _q_piError(), _q_piFinished(), and addCommand().
int QFtpPrivate::addCommand (QFtpCommand * cmd)
References _q_startNextCommand(), QFtpCommand::id, and pending.
Member Data Documentation
bool QFtpPrivate::close_waitForStateChange
Referenced by _q_piConnectState(), and _q_piFinished().
QFtp::Error QFtpPrivate::error
Referenced by _q_piError(), and _q_startNextCommand().
QString QFtpPrivate::errorString
Referenced by _q_piError(), and _q_startNextCommand().
QString QFtpPrivate::host
Referenced by _q_startNextCommand().
QList<QFtpCommand *> QFtpPrivate::pending
Referenced by _q_piError(), _q_piFinished(), _q_startNextCommand(), addCommand(), and ~QFtpPrivate().
QFtpPI QFtpPrivate::pi
Referenced by _q_piError(), _q_piFtpReply(), and _q_startNextCommand().
quint16 QFtpPrivate::port
Referenced by _q_startNextCommand().
QString QFtpPrivate::proxyHost
Referenced by _q_startNextCommand().
quint16 QFtpPrivate::proxyPort
Referenced by _q_startNextCommand().
QFtp* QFtpPrivate::q_ptr
QFtp::State QFtpPrivate::state
Referenced by _q_piConnectState(), _q_piFinished(), and _q_startNextCommand().
QFtp::TransferMode QFtpPrivate::transferMode
The documentation for this class was generated from the following file:
src/modules/objects/qtftp/qftp.cpp