KVIrc: KviKvsTreeNodeModuleSimpleCommand Class Reference
KviKvsTreeNodeModuleSimpleCommand Class Reference
#include <kvi_kvs_treenode_modulesimplecommand.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeModuleSimpleCommand (const QChar *pLocation, const QString &szModuleName, const QString &szCmdName, KviKvsTreeNodeDataList *params)
~KviKvsTreeNodeModuleSimpleCommand ()
Protected Attributes
QString m_szModuleName
Constructor & Destructor Documentation
KviKvsTreeNodeModuleSimpleCommand::KviKvsTreeNodeModuleSimpleCommand (const QChar * pLocation, const QString & szModuleName, const QString & szCmdName, KviKvsTreeNodeDataList * params)
References m_szModuleName.
KviKvsTreeNodeModuleSimpleCommand::~KviKvsTreeNodeModuleSimpleCommand ()
Member Function Documentation
void KviKvsTreeNodeModuleSimpleCommand::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommand::m_szCmdName, and m_szModuleName.
void KviKvsTreeNodeModuleSimpleCommand::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommandWithParameters::dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), KviKvsTreeNodeCommand::m_szCmdName, and m_szModuleName.
bool KviKvsTreeNodeModuleSimpleCommand::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx, KviKvsRunTimeContext::error(), KviKvsTreeNodeSwitchList::evaluate(), KviKvsTreeNodeDataList::evaluate(), g_pModuleManager, KviModuleManager::getModule(), KviKvsModuleInterface::kvsFindSimpleCommand(), KviModuleManager::lastError(), KviKvsTreeNodeCommandWithParameters::m_pParams, KviKvsTreeNodeCommand::m_pSwitches, KviKvsTreeNodeCommand::m_szCmdName, m_szModuleName, KviKvsVariantList::setAutoDelete(), and KviKvsRunTimeContext::setDefaultReportLocation().
Member Data Documentation
QString KviKvsTreeNodeModuleSimpleCommand::m_szModuleName [protected]
Referenced by contextDescription(), dump(), execute(), and KviKvsTreeNodeModuleSimpleCommand().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_modulesimplecommand.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_modulesimplecommand.cpp