KVIrc: KviServerParser Class Reference
KviServerParser Class Reference
#include <kvi_sparser.h>
Public Member Functions
KviServerParser ()
void parseMessage (const char *message, KviIrcConnection *pConnection)
~KviServerParser ()
Static Public Member Functions
static const char * decodeCtcpEscape (const char *msg_ptr, QByteArray &buffer)
static const char * decodeCtcpEscape (const char *msg_ptr, KviStr &buffer)
static void encodeCtcpParameter (const char *param, QString &buffer, bool bSpaceBreaks=true)
static void encodeCtcpParameter (const char *param, KviStr &buffer, bool bSpaceBreaks=true)
static const char * extractCtcpParameter (const char *msg_ptr, QString &buffer, bool bSpaceBreaks=true, bool bSafeOnly=false)
static const char * extractCtcpParameter (const char *msg_ptr, KviStr &buffer, bool bSpaceBreaks=true, bool bSafeOnly=false)
Private Member Functions
bool checkCtcpFlood (KviCtcpMessage *msg)
void echoCtcpReply (KviCtcpMessage *msg)
void echoCtcpRequest (KviCtcpMessage *msg)
void otherChannelError (KviIrcMessage *msg)
void parseChannelHelp (KviIrcMessage *msg)
void parseChannelMode (const QString &szNick, const QString &szUser, const QString &szHost, KviChannel *chan, KviStr &modefl, KviIrcMessage *msg, int curParam)
void parseCommandEndOfHelp (KviIrcMessage *msg)
void parseCommandHelp (KviIrcMessage *msg)
void parseCommandSyntaxHelp (KviIrcMessage *msg)
void parseCtcpReply (KviCtcpMessage *msg)
void parseCtcpReplyAvatar (KviCtcpMessage *msg)
void parseCtcpReplyGeneric (KviCtcpMessage *msg)
void parseCtcpReplyLagcheck (KviCtcpMessage *msg)
void parseCtcpReplyPing (KviCtcpMessage *msg)
void parseCtcpReplyUserinfo (KviCtcpMessage *msg)
void parseCtcpRequest (KviCtcpMessage *msg)
void parseCtcpRequestAction (KviCtcpMessage *msg)
void parseCtcpRequestAvatar (KviCtcpMessage *msg)
void parseCtcpRequestClientinfo (KviCtcpMessage *msg)
void parseCtcpRequestDcc (KviCtcpMessage *msg)
void parseCtcpRequestFinger (KviCtcpMessage *msg)
void parseCtcpRequestPage (KviCtcpMessage *msg)
void parseCtcpRequestPing (KviCtcpMessage *msg)
void parseCtcpRequestSource (KviCtcpMessage *msg)
void parseCtcpRequestTime (KviCtcpMessage *msg)
void parseCtcpRequestUserinfo (KviCtcpMessage *msg)
void parseCtcpRequestVersion (KviCtcpMessage *msg)
void parseLiteralAuthenticate (KviIrcMessage *msg)
void parseLiteralCap (KviIrcMessage *msg)
void parseLiteralError (KviIrcMessage *msg)
void parseLiteralInvite (KviIrcMessage *msg)
void parseLiteralJoin (KviIrcMessage *msg)
void parseLiteralKick (KviIrcMessage *msg)
void parseLiteralMode (KviIrcMessage *msg)
void parseLiteralNick (KviIrcMessage *msg)
void parseLiteralNotice (KviIrcMessage *msg)
void parseLiteralPart (KviIrcMessage *msg)
void parseLiteralPing (KviIrcMessage *msg)
void parseLiteralPong (KviIrcMessage *msg)
void parseLiteralPrivmsg (KviIrcMessage *msg)
void parseLiteralQuit (KviIrcMessage *msg)
void parseLiteralTopic (KviIrcMessage *msg)
void parseLiteralWallops (KviIrcMessage *msg)
void parseLoginNicknameProblem (KviIrcMessage *msg)
void parseNumeric001 (KviIrcMessage *msg)
void parseNumeric002 (KviIrcMessage *msg)
void parseNumeric003 (KviIrcMessage *msg)
void parseNumeric004 (KviIrcMessage *msg)
void parseNumeric005 (KviIrcMessage *msg)
void parseNumeric020 (KviIrcMessage *msg)
void parseNumeric367 (KviIrcMessage *msg)
void parseNumeric368 (KviIrcMessage *msg)
void parseNumericAList (KviIrcMessage *msg)
void parseNumericAway (KviIrcMessage *)
void parseNumericBackFromAway (KviIrcMessage *)
void parseNumericCannotSend (KviIrcMessage *msg)
void parseNumericCannotSendColor (KviIrcMessage *msg)
void parseNumericCantJoinChannel (KviIrcMessage *msg)
void parseNumericChannelModeIs (KviIrcMessage *msg)
void parseNumericCodePageScheme (KviIrcMessage *msg)
void parseNumericCodePageSet (KviIrcMessage *msg)
void parseNumericCommandSyntax (KviIrcMessage *msg)
void parseNumericCreationTime (KviIrcMessage *msg)
void parseNumericEndOfAList (KviIrcMessage *msg)
void parseNumericEndOfExceptList (KviIrcMessage *msg)
void parseNumericEndOfInviteList (KviIrcMessage *msg)
void parseNumericEndOfLinks (KviIrcMessage *msg)
void parseNumericEndOfNames (KviIrcMessage *msg)
void parseNumericEndOfQList (KviIrcMessage *msg)
void parseNumericEndOfReopList (KviIrcMessage *msg)
void parseNumericEndOfStats (KviIrcMessage *msg)
void parseNumericEndOfWho (KviIrcMessage *msg)
void parseNumericEndOfWhois (KviIrcMessage *msg)
void parseNumericEndOfWhowas (KviIrcMessage *msg)
void parseNumericExceptList (KviIrcMessage *msg)
void parseNumericInfo (KviIrcMessage *msg)
void parseNumericInfoEnd (KviIrcMessage *msg)
void parseNumericInfoStart (KviIrcMessage *msg)
void parseNumericInviteList (KviIrcMessage *msg)
void parseNumericInviting (KviIrcMessage *msg)
void parseNumericIsOn (KviIrcMessage *msg)
void parseNumericLinks (KviIrcMessage *msg)
void parseNumericList (KviIrcMessage *msg)
void parseNumericListEnd (KviIrcMessage *msg)
void parseNumericListStart (KviIrcMessage *msg)
void parseNumericMotd (KviIrcMessage *msg)
void parseNumericNames (KviIrcMessage *msg)
void parseNumericNicknameProblem (KviIrcMessage *msg)
void parseNumericNoSuchChannel (KviIrcMessage *msg)
void parseNumericNoSuchNick (KviIrcMessage *msg)
void parseNumericNoSuchServer (KviIrcMessage *msg)
void parseNumericNoTopic (KviIrcMessage *msg)
void parseNumericNotRegistered (KviIrcMessage *msg)
void parseNumericQList (KviIrcMessage *msg)
void parseNumericReopList (KviIrcMessage *msg)
void parseNumericSaslFail (KviIrcMessage *msg)
void parseNumericSaslLogin (KviIrcMessage *msg)
void parseNumericSaslSuccess (KviIrcMessage *msg)
void parseNumericServerAdminInfoAdminContact (KviIrcMessage *msg)
void parseNumericServerAdminInfoAdminName (KviIrcMessage *msg)
void parseNumericServerAdminInfoServerName (KviIrcMessage *msg)
void parseNumericServerAdminInfoTitle (KviIrcMessage *msg)
void parseNumericStartTls (KviIrcMessage *msg)
void parseNumericStats (KviIrcMessage *msg)
void parseNumericTime (KviIrcMessage *msg)
void parseNumericTopic (KviIrcMessage *msg)
void parseNumericTopicWhoTime (KviIrcMessage *msg)
void parseNumericUnavailResource (KviIrcMessage *msg)
void parseNumericUserhost (KviIrcMessage *msg)
void parseNumericUserMode (KviIrcMessage *msg)
void parseNumericWatch (KviIrcMessage *msg)
void parseNumericWhoisAuth (KviIrcMessage *msg)
void parseNumericWhoisAway (KviIrcMessage *)
void parseNumericWhoisChannels (KviIrcMessage *msg)
void parseNumericWhoisIdle (KviIrcMessage *msg)
void parseNumericWhoisOther (KviIrcMessage *msg)
void parseNumericWhoisServer (KviIrcMessage *msg)
void parseNumericWhoisUser (KviIrcMessage *msg)
void parseNumericWhoReply (KviIrcMessage *msg)
void parseNumericWhowasUser (KviIrcMessage *msg)
void parseUserMode (KviIrcMessage *msg, const char *modeflptr)
void replyCtcp (KviCtcpMessage *msg, const QString &data)
Private Attributes
KviStr m_szLastParserError
Static Private Attributes
static KviCtcpMessageParseStruct m_ctcpReplyParseProcTable []
static KviCtcpMessageParseStruct m_ctcpRequestParseProcTable []
static KviLiteralMessageParseStruct m_literalParseProcTable []
static messageParseProc m_numericParseProcTable [1000]
Constructor & Destructor Documentation
KviServerParser::KviServerParser ()
KviServerParser::~KviServerParser ()
Member Function Documentation
bool KviServerParser::checkCtcpFlood (KviCtcpMessage * msg) [private]
References KviIrcConnection::antiCtcpFloodData(), _KviCtcpMessage::bIsFlood, KviIrcMessage::connection(), KviIrcConnectionAntiCtcpFloodData::ctcpCount(), d, KviIrcConnectionAntiCtcpFloodData::increaseCtcpCount(), KVI_OPTION_BOOL, KVI_OPTION_UINT, kvi_time_t, kvi_unixTime, KviOption_boolUseCtcpFloodProtection, KviOption_uintCtcpFloodCheckInterval, KviOption_uintMaxCtcpRequests, KviIrcConnectionAntiCtcpFloodData::lastCtcpTime(), _KviCtcpMessage::msg, KviIrcConnectionAntiCtcpFloodData::setCtcpCount(), and KviIrcConnectionAntiCtcpFloodData::setLastCtcpTime().
Referenced by parseCtcpReplyAvatar(), parseCtcpRequestAvatar(), parseCtcpRequestClientinfo(), parseCtcpRequestDcc(), parseCtcpRequestFinger(), parseCtcpRequestPage(), parseCtcpRequestPing(), parseCtcpRequestSource(), parseCtcpRequestTime(), parseCtcpRequestUserinfo(), and parseCtcpRequestVersion().
const char * KviServerParser::decodeCtcpEscape (const char * msg_ptr, QByteArray & buffer) [static]
References c.
const char * KviServerParser::decodeCtcpEscape (const char * msg_ptr, KviStr & buffer) [static]
References KviStr::append(), and c.
Referenced by extractCtcpParameter().
void KviServerParser::echoCtcpReply (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_CTCPREPLY, KVI_OUT_CTCPREPLYUNKNOWN, KVI_OUT_SYSTEMWARNING, KviOption_boolCtcpRepliesToActiveWindow, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, and KviIrcMask::user().
Referenced by parseCtcpReply(), parseCtcpReplyGeneric(), and parseCtcpReplyUserinfo().
void KviServerParser::echoCtcpRequest (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), _KviCtcpMessage::bIgnored, _KviCtcpMessage::bIsFlood, _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_CTCPREQUESTFLOOD, KVI_OUT_CTCPREQUESTIGNORED, KVI_OUT_CTCPREQUESTREPLIED, KVI_OUT_CTCPREQUESTUNKNOWN, KVI_OUT_SYSTEMWARNING, KVI_TEXT_RESET, KviEvent_OnCTCPFlood, KviOption_boolCtcpRequestsToActiveWindow, KVS_TRIGGER_EVENT_6_HALTED, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, and KviIrcMask::user().
Referenced by parseCtcpRequest(), parseCtcpRequestAvatar(), parseCtcpRequestClientinfo(), parseCtcpRequestDcc(), parseCtcpRequestFinger(), parseCtcpRequestPage(), parseCtcpRequestPing(), parseCtcpRequestSource(), parseCtcpRequestTime(), parseCtcpRequestUserinfo(), and parseCtcpRequestVersion().
void KviServerParser::encodeCtcpParameter (const char * param, QString & buffer, bool bSpaceBreaks = true) [static]
void KviServerParser::encodeCtcpParameter (const char * param, KviStr & buffer, bool bSpaceBreaks = true) [static]
References KviStr::append().
Referenced by parseCtcpReplyAvatar(), and parseCtcpRequestAvatar().
const char * KviServerParser::extractCtcpParameter (const char * msg_ptr, QString & buffer, bool bSpaceBreaks = true, bool bSafeOnly = false) [static]
References decodeCtcpEscape().
const char * KviServerParser::extractCtcpParameter (const char * msg_ptr, KviStr & buffer, bool bSpaceBreaks = true, bool bSafeOnly = false) [static]
References KviStr::append(), and decodeCtcpEscape().
Referenced by parseCtcpReply(), parseCtcpReplyAvatar(), parseCtcpReplyLagcheck(), parseCtcpReplyPing(), parseCtcpRequest(), parseCtcpRequestClientinfo(), and parseCtcpRequestDcc().
void KviServerParser::otherChannelError (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseChannelHelp (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseChannelMode (const QString & szNick, const QString & szUser, const QString & szHost, KviChannel * chan, KviStr & modefl, KviIrcMessage * msg, int curParam) [private]
References __tr2qs, CHANNEL_MODE, CHANUSER_MODE, KviIrcMessage::connection(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviIrcConnectionUserInfo::hostName(), IS_ME, KviIrcConnectionServerInfo::isSupportedModeFlag(), KVI_OPTION_BOOL, KVI_OUT_BAN, KVI_OUT_BANEXCEPT, KVI_OUT_BANUNEXCEPT, KVI_OUT_CHANADMIN, KVI_OUT_CHANMODE, KVI_OUT_CHANOWNER, KVI_OUT_DECHANADMIN, KVI_OUT_DECHANOWNER, KVI_OUT_DEOP, KVI_OUT_DEVOICE, KVI_OUT_HALFDEOP, KVI_OUT_HALFOP, KVI_OUT_INVITEEXCEPT, KVI_OUT_INVITEUNEXCEPT, KVI_OUT_KEY, KVI_OUT_LIMIT, KVI_OUT_MEBAN, KVI_OUT_MEBANEXCEPT, KVI_OUT_MEBANUNEXCEPT, KVI_OUT_MECHANADMIN, KVI_OUT_MECHANOWNER, KVI_OUT_MEDECHANADMIN, KVI_OUT_MEDECHANOWNER, KVI_OUT_MEDEHALFOP, KVI_OUT_MEDEOP, KVI_OUT_MEDEUSEROP, KVI_OUT_MEDEVOICE, KVI_OUT_MEHALFOP, KVI_OUT_MEINVITEEXCEPT, KVI_OUT_MEINVITEUNEXCEPT, KVI_OUT_MEOP, KVI_OUT_MEUNBAN, KVI_OUT_MEUSEROP, KVI_OUT_MEVOICE, KVI_OUT_OP, KVI_OUT_UNBAN, KVI_OUT_USERDEOP, KVI_OUT_USEROP, KVI_OUT_VOICE, kvi_strEqualCS(), KviEvent_OnBan, KviEvent_OnBanException, KviEvent_OnBanExceptionRemove, KviEvent_OnChanAdmin, KviEvent_OnChannelModeChange, KviEvent_OnChanOwner, KviEvent_OnDeChanAdmin, KviEvent_OnDeChanOwner, KviEvent_OnDeHalfOp, KviEvent_OnDeOp, KviEvent_OnDeUserOp, KviEvent_OnDeVoice, KviEvent_OnHalfOp, KviEvent_OnInviteException, KviEvent_OnInviteExceptionRemove, KviEvent_OnKeySet, KviEvent_OnKeyUnset, KviEvent_OnLimitSet, KviEvent_OnLimitUnset, KviEvent_OnMeBan, KviEvent_OnMeBanException, KviEvent_OnMeBanExceptionRemove, KviEvent_OnMeChanAdmin, KviEvent_OnMeChanOwner, KviEvent_OnMeDeChanAdmin, KviEvent_OnMeDeChanOwner, KviEvent_OnMeDeHalfOp, KviEvent_OnMeDeOp, KviEvent_OnMeDeUserOp, KviEvent_OnMeDeVoice, KviEvent_OnMeHalfOp, KviEvent_OnMeInviteException, KviEvent_OnMeInviteExceptionRemove, KviEvent_OnMeOp, KviEvent_OnMeUnban, KviEvent_OnMeUserOp, KviEvent_OnMeVoice, KviEvent_OnOp, KviEvent_OnUnban, KviEvent_OnUserOp, KviEvent_OnVoice, KviOption_boolShowCompactModeChanges, KVS_TRIGGER_EVENT_3_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviIrcMask::matchesFixed(), KviIrcConnectionUserInfo::nickName(), KviWindow::output(), KviStr::ptr(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviIrcConnection::serverInfo(), KviChannel::setChannelMode(), KviChannel::setChannelModeWithParam(), KviChannel::setChanOwner(), KviIrcMessage::setHaltOutput(), KviChannel::setMask(), KviQString::sprintf(), KviIrcConnectionServerInfo::supportedListModes(), KviIrcConnectionServerInfo::supportedParameterModes(), KviIrcConnectionServerInfo::supportedParameterWhenSetModes(), KviWindow::updateCaption(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
Referenced by parseLiteralMode(), and parseNumericChannelModeIs().
void KviServerParser::parseCommandEndOfHelp (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::output(), and KviIrcMessage::safeParam().
void KviServerParser::parseCommandHelp (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::outputNoFmt(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseCommandSyntaxHelp (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseCtcpReply (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), echoCtcpReply(), KviQString::equalCI(), extractCtcpParameter(), KviIrcMask::host(), KVI_CTCP_MESSAGE_PARSE_TRIGGERNOEVENT, KviEvent_OnCTCPReply, KVS_TRIGGER_EVENT_6_HALTED, m_ctcpReplyParseProcTable, _KviCtcpMessage::msg, _KviCtcpMessageParseStruct::msgName, KviIrcMask::nick(), _KviCtcpMessage::pData, _KviCtcpMessageParseStruct::proc, _KviCtcpMessage::pSource, _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, and KviIrcMask::user().
Referenced by parseLiteralNotice().
void KviServerParser::parseCtcpReplyAvatar (KviCtcpMessage * msg) [private]
References __tr2qs, _OUTPUT_VERBOSE, KviQString::appendFormatted(), KviConsole::avatarChanged(), KviApp::Avatars, checkCtcpFlood(), KviIrcMessage::connection(), KviIrcMessage::console(), KviQString::cutToLast(), KviWindow::decodeText(), encodeCtcpParameter(), KviIrcConnection::encodeText(), KviQString::equalCIN(), extractCtcpParameter(), KviIrcUserEntry::Female, KviIrcUserDataBase::find(), g_pApp, g_pIconManager, KviIconManager::getAvatar(), KviApp::getLocalKvircDirectory(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_AVATAR, KviOption_boolRequestMissingAvatars, KviOption_uintMaximumRequestedAvatarSize, KviIrcUserEntry::Male, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::outputNoFmt(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviKvsScript::run(), KviIrcConnection::sendFmtData(), KviIrcUserEntry::setAvatar(), KviApp::setAvatarOnFileReceived(), KviIrcUserEntry::setGender(), KviQString::sprintf(), _KviCtcpMessage::szTarget, KviIrcUserEntry::Unknown, KviIconManager::urlToCachedFileName(), KviIrcMask::user(), and KviIrcConnection::userDataBase().
void KviServerParser::parseCtcpReplyGeneric (KviCtcpMessage * msg) [private]
References echoCtcpReply().
void KviServerParser::parseCtcpReplyLagcheck (KviCtcpMessage * msg) [private]
References KviWindow::connection(), KviIrcMessage::console(), extractCtcpParameter(), KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), _KviCtcpMessage::msg, _KviCtcpMessage::pData, and KviStr::ptr().
void KviServerParser::parseCtcpReplyPing (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviStr::contains(), KviStr::cutFromFirst(), KviStr::cutToFirst(), extractCtcpParameter(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, kvi_gettimeofday(), KVI_OPTION_BOOL, KVI_OUT_CTCPREPLY, KVI_OUT_CTCPREPLYUNKNOWN, KVI_OUT_SYSTEMWARNING, KviOption_boolCtcpRepliesToActiveWindow, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, _KviCtcpMessage::szTarget, KviStr::toUInt(), and KviIrcMask::user().
void KviServerParser::parseCtcpReplyUserinfo (KviCtcpMessage * msg) [private]
References c, KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), echoCtcpReply(), KviQString::equalCS(), KviIrcUserEntry::Female, KviIrcUserDataBase::find(), g_pActiveWindow, KviIrcUserEntry::Male, _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviIrcUserEntry::setGender(), and KviIrcConnection::userDataBase().
void KviServerParser::parseCtcpRequest (KviCtcpMessage * msg) [private]
References __tr2qs, _KviCtcpMessage::bUnknown, KviRegisteredUser::Channel, KviIrcMessage::connection(), KviIrcMessage::console(), KviRegisteredUser::Ctcp, KviIrcConnection::decodeText(), echoCtcpRequest(), KviQString::equalCI(), extractCtcpParameter(), KviIrcMask::host(), IS_ME, KviRegisteredUser::isIgnoreEnabledFor(), KVI_CTCP_MESSAGE_PARSE_TRIGGERNOEVENT, KVI_OPTION_BOOL, KVI_OUT_IGNORE, KviEvent_OnCTCPRequest, KviOption_boolIgnoreCtcpDcc, KviOption_boolVerboseIgnore, KVS_TRIGGER_EVENT_6_HALTED, m_ctcpReplyParseProcTable, m_ctcpRequestParseProcTable, _KviCtcpMessage::msg, _KviCtcpMessageParseStruct::msgName, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessageParseStruct::proc, _KviCtcpMessage::pSource, KviRegisteredUser::Query, KviIrcUserDataBase::registeredUser(), _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, KviQString::toUtf8(), KviIrcMask::user(), and KviIrcConnection::userDataBase().
Referenced by parseLiteralPrivmsg().
void KviServerParser::parseCtcpRequestAction (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviConsole::applyHighlighting(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createQuery(), KviIrcConnection::decodeText(), KviWindow::decodeText(), KviWindow::demandAttention(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pApp, KviWindow::hasAttention(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_UINT, KVI_OUT_ACTION, KVI_OUT_HIGHLIGHT, KVI_OUT_SYSTEMWARNING, KviEvent_OnAction, KviEvent_OnQueryWindowRequest, KviOption_boolCreateQueryOnPrivmsg, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolFlashWindowOnHighlightedMessages, KviOption_boolPopupNotifierOnHighlightedMessages, KviOption_boolStripMircColorsInUserMessages, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, _KviCtcpMessage::msg, KviIrcMask::nick(), KviApp::notifierMessage(), KviWindow::output(), KviWindow::outputNoFmt(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviStr::ptr(), KviIrcMessage::setHaltOutput(), KviQuery::setTarget(), KviMircCntrl::stripControlBytes(), _KviCtcpMessage::szTarget, KviOsInfo::type(), and KviIrcMask::user().
void KviServerParser::parseCtcpRequestAvatar (KviCtcpMessage * msg) [private]
References __tr2qs, _OUTPUT_VERBOSE, KviSharedFilesManager::addSharedFile(), _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::console(), KviConsole::currentAvatar(), echoCtcpRequest(), encodeCtcpParameter(), g_pSharedFilesManager, IS_ME, KviAvatar::isRemote(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviOption_boolDCCFileTransferReplaceOutgoingSpacesWithUnderscores, KviOption_boolIgnoreChannelAvatarRequestsWhenNoAvatarSet, KviOption_boolIgnoreCtcpAvatar, KviOption_stringCtcpUserInfoGender, KviOption_uintAvatarOfferTimeoutInSecs, KviAvatar::localPath(), KviIrcMask::mask(), _KviCtcpMessage::msg, KviAvatar::name(), KviWindow::output(), _KviCtcpMessage::pSource, replyCtcp(), and _KviCtcpMessage::szTarget.
void KviServerParser::parseCtcpRequestClientinfo (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), ctcpTagTable, echoCtcpRequest(), extractCtcpParameter(), KviStr::Format, KviStr::isEmpty(), KVI_OPTION_BOOL, KVI_RELEASE_NAME, KVI_SOURCES_DATE, kvi_strEqualCS(), KVI_VERSION, KviOption_boolIgnoreCtcpClientinfo, _KviCtcpMessage::pData, KviStr::ptr(), replyCtcp(), _KviCtcpMessage::szTag, KviStr::toUpper(), and KviStr::trimmed().
void KviServerParser::parseCtcpRequestDcc (KviCtcpMessage * msg) [private]
References __tr2qs, _KviDccRequest::bIPv6, checkCtcpFlood(), KviIrcMessage::connection(), KviIrcMessage::console(), _KviDccRequest::ctcpMsg, KviRegisteredUser::Dcc, KviWindow::decodeText(), echoCtcpRequest(), extractCtcpParameter(), KviApp::findPendingAvatarChange(), g_pApp, g_pModuleManager, KviModuleManager::getModule(), KviModule::getSymbol(), KviIrcMessage::haltOutput(), KviIrcMask::host(), KviRegisteredUser::isIgnoreEnabledFor(), KviConsole::isIPv6Connection(), KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KVI_OUT_DCCREQUEST, kvi_strEqualCI(), KviOption_boolVerboseIgnore, KviModuleManager::lastError(), _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), KviWindow::outputNoFmt(), _KviDccRequest::pConsole, _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviStr::ptr(), KviIrcUserDataBase::registeredUser(), _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, _KviDccRequest::szParam5, _KviCtcpMessage::szTag, _KviDccRequest::szType, KviIrcMask::user(), and KviIrcConnection::userDataBase().
void KviServerParser::parseCtcpRequestFinger (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::connection(), echoCtcpRequest(), KviStr::Format, KviStr::isEmpty(), KVI_OPTION_BOOL, KviOption_boolIgnoreCtcpFinger, _KviCtcpMessage::msg, KviStr::ptr(), replyCtcp(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
void KviServerParser::parseCtcpRequestPage (KviCtcpMessage * msg) [private]
References KviCtcpPageDialog::addPage(), _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::connection(), KviIrcConnection::decodeText(), echoCtcpRequest(), g_pCtcpPageDialog, KviIrcMask::host(), KVI_DEFAULT_CTCP_PAGE_REPLY, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolIgnoreCtcpPage, KviOption_boolShowDialogOnCtcpPage, KviOption_stringCtcpPageReply, _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pData, KviCtcpPageDialog::popup(), _KviCtcpMessage::pSource, KviStr::ptr(), replyCtcp(), and KviIrcMask::user().
void KviServerParser::parseCtcpRequestPing (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::connection(), echoCtcpRequest(), KviIrcConnection::encodeText(), KVI_OPTION_BOOL, KviOption_boolIgnoreCtcpPing, _KviCtcpMessage::msg, _KviCtcpMessage::pData, and replyCtcp().
void KviServerParser::parseCtcpRequestSource (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), echoCtcpRequest(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_RELEASE_NAME, KVI_VERSION, KviOption_boolIgnoreCtcpSource, KviOption_stringCtcpSourcePostfix, replyCtcp(), and KviOsInfo::version().
void KviServerParser::parseCtcpRequestTime (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), echoCtcpRequest(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolIgnoreCtcpTime, KviOption_uintOutputDatetimeFormat, and replyCtcp().
void KviServerParser::parseCtcpRequestUserinfo (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), echoCtcpRequest(), KVI_DEFAULT_CTCP_USERINFO_REPLY, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolIgnoreCtcpUserinfo, KviOption_stringCtcpUserInfoAge, KviOption_stringCtcpUserInfoGender, KviOption_stringCtcpUserInfoLanguages, KviOption_stringCtcpUserInfoLocation, KviOption_stringCtcpUserInfoOther, and replyCtcp().
void KviServerParser::parseCtcpRequestVersion (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, KviBuildInfo::buildDate(), KviBuildInfo::buildRevision(), checkCtcpFlood(), echoCtcpRequest(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_RELEASE_NAME, KVI_SOURCES_DATE, KVI_VERSION, KviOption_boolIgnoreCtcpVersion, KviOption_stringCtcpVersionPostfix, KviOsInfo::name(), KviOsInfo::release(), replyCtcp(), and KviOsInfo::version().
void KviServerParser::parseLiteralAuthenticate (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcConnection::handleAuthenticate(), and KviIrcMessage::safeParam().
void KviServerParser::parseLiteralCap (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcConnectionServerInfo::addSupportedCaps(), KviIrcConnectionStateData::changeEnabledCapList(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviIrcConnection::handleInitialCapAck(), KviIrcConnection::handleInitialCapLs(), KviIrcConnection::handleInitialCapNak(), KviIrcConnectionStateData::isInsideInitialCapLs(), KviIrcConnectionStateData::isInsideInitialCapReq(), KVI_OUT_CAP, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), and KviIrcConnection::stateData().
void KviServerParser::parseLiteralError (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERERROR, KviEvent_OnError, KVS_TRIGGER_EVENT_2_HALTED, KviWindow::output(), KviIrcMessage::safePrefix(), and KviIrcMessage::setHaltOutput().
void KviServerParser::parseLiteralInvite (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviRegisteredUser::Invite, IS_ME, KviRegisteredUser::isIgnoreEnabledFor(), KVI_OPTION_BOOL, KVI_OUT_IGNORE, KVI_OUT_INVITE, KviEvent_OnInvite, KviOption_boolAutoJoinOnInvite, KviOption_boolInvitesToActiveWindow, KviOption_boolVerboseIgnore, KVS_TRIGGER_EVENT_4_HALTED, KviWindow::output(), KviIrcUserDataBase::registeredUser(), KviIrcMessage::safeParam(), KviIrcConnection::sendFmtData(), KviIrcMessage::setHaltOutput(), UNRECOGNIZED_MESSAGE, and KviIrcConnection::userDataBase().
void KviServerParser::parseLiteralJoin (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviIrcUserEntry::avatar(), KviConsole::avatarChanged(), KviConsole::checkDefaultAvatar(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createChannel(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviConsole::defaultAvatarFromOptions(), KviRequestQueue::enqueueChannel(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), KviIrcConnection::getCommonChannels(), KviUserListEntry::globalData(), KviIrcMessage::haltOutput(), IS_ME, KviChannel::join(), KVI_OPTION_BOOL, KVI_OUT_JOIN, KVI_OUT_QUERYTRACE, KviEvent_OnJoin, KviEvent_OnMeJoin, KviOption_boolEnableQueryTracing, KVS_TRIGGER_EVENT_0_HALTED, KVS_TRIGGER_EVENT_3_HALTED, KviIrcConnectionServerInfo::modeFlagFromModeChar(), KviQuery::notifyCommonChannels(), KviQString::nullTerminatedArray(), KviWindow::output(), KviIrcConnection::requestQueue(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcUserEntry::setAvatar(), KviIrcMessage::setHaltOutput(), UNRECOGNIZED_MESSAGE, KviWindow::updateCaption(), KviQuery::updateLabelText(), and KviIrcConnection::userInfoReceived().
void KviServerParser::parseLiteralKick (KviIrcMessage * msg) [private]
References __tr, __tr2qs, _OUTPUT_VERBOSE, KviChannel::channelModeParam(), KviFrame::closeWindow(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcUserDataBase::find(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), KviWindow::frame(), KviIrcConnection::getCommonChannels(), KviIrcMessage::haltOutput(), KviChannel::hasChannelMode(), KviIrcUserEntry::host(), IS_ME, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_KICK, KVI_OUT_MEKICK, KVI_OUT_QUERYTRACE, KVI_OUT_SYSTEMMESSAGE, KVI_USERACTION_KICK, KviEvent_OnKick, KviEvent_OnMeKick, KviOption_boolEnableQueryTracing, KviOption_boolKeepChannelOpenOnKick, KviOption_boolRejoinChannelOnKick, KviOption_stringOnMeKickedSound, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviQuery::notifyCommonChannels(), KviWindow::output(), KviChannel::part(), KviIrcUrl::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviChannel::setDeadChan(), KviIrcMessage::setHaltOutput(), UNRECOGNIZED_MESSAGE, KviIrcUserEntry::user(), KviChannel::userAction(), and KviIrcConnection::userDataBase().
void KviServerParser::parseLiteralMode (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), IS_ME, KVI_OUT_MODE, KVI_USERACTION_CHANMODE, KviWindow::output(), parseChannelMode(), parseUserMode(), KviIrcMessage::safeParam(), UNRECOGNIZED_MESSAGE, and KviChannel::userAction().
void KviServerParser::parseLiteralNick (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, c, KviIrcConnection::channelList(), KviFrame::closeWindow(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviWindow::delayedAutoRaise(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), KviPointerList< T >::first(), KviWindow::frame(), g_pActiveWindow, KviIrcConnection::getCommonChannels(), KviIrcMessage::haltOutput(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_NICK, KVI_OUT_QUERYTRACE, KVI_OUT_SYSTEMWARNING, KVI_USERACTION_NICK, KviEvent_OnMeNickChange, KviEvent_OnNickChange, KviOption_boolEnableQueryTracing, KVS_TRIGGER_EVENT_2_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KviQuery::mergeQuery(), KviPointerList< T >::next(), KviQuery::nickChange(), KviIrcConnection::nickChange(), KviQuery::notifyCommonChannels(), KviWindow::output(), KviIrcConnection::queryList(), KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), KviIrcUserEntry::setSmartNickColor(), KviQuery::userAction(), and KviIrcConnection::userDataBase().
void KviServerParser::parseLiteralNotice (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), _KviCtcpMessage::bIgnored, _KviCtcpMessage::bIsFlood, _KviCtcpMessage::bUnknown, c, KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createQuery(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), KviStr::cutLeft(), KviStr::cutRight(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), DECRYPT_IF_NEEDED, KviWindow::demandAttention(), KviQString::equalCI(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pApp, KviIrcMessage::haltOutput(), KviWindow::hasAttention(), KviNickServRule::identifyCommand(), IS_ME, KviNickServRuleSet::isEmpty(), KviNickServRuleSet::isEnabled(), KviRegisteredUser::isIgnoreEnabledFor(), KviIrcConnectionServerInfo::isSupportedModePrefix(), kvi_mayBeSpam(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_BROADCASTNOTICE, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_CHANSERV, KVI_OUT_IGNORE, KVI_OUT_NICKSERV, KVI_OUT_QUERYNOTICE, KVI_OUT_QUERYNOTICECRYPTED, KVI_OUT_SERVERNOTICE, KVI_OUT_SPAM, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KVI_SMALLICON_QUERYNOTICE, KVI_USERACTION_NOTICE, KVI_WINDOW_TYPE_CHANNEL, KviEvent_OnChannelNotice, KviEvent_OnChanServNotice, KviEvent_OnNickServNotice, KviEvent_OnQueryNotice, KviEvent_OnQueryWindowRequest, KviEvent_OnServerNotice, KviOption_boolCreateQueryOnNotice, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolFlashQueryWindowOnNewMessages, KviOption_boolOperatorMessagesToActiveWindow, KviOption_boolPasteLastLogOnQueryJoin, KviOption_boolPopupNotifierOnNewQueryMessages, KviOption_boolServerNoticesToActiveWindow, KviOption_boolServicesNoticesToActiveWindow, KviOption_boolSilentAntiSpam, KviOption_boolUseAntiSpamOnNotice, KviOption_boolVerboseIgnore, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_2_HALTED, KVS_TRIGGER_EVENT_3_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KviStr::lastCharIs(), KviStr::len(), KviNickServRuleSet::matchRule(), _KviCtcpMessage::msg, KviIrcConnectionTarget::network(), KviNetwork::nickServRuleSet(), KviConsole::NoNotifier, KviRegisteredUser::Notice, KviApp::notifierMessage(), KviConsole::NoWindowFlashing, KviWindow::output(), KviWindow::outputNoFmt(), KviConsole::outputPrivmsg(), parseCtcpReply(), KviQuery::pasteLastLog(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviStr::ptr(), KviIrcUserDataBase::registeredUser(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcMessage::setHaltOutput(), KviQuery::setTarget(), KviQString::sprintf(), _KviCtcpMessage::szTarget, KviIrcConnection::target(), KviIrcMessage::trailingString(), KviWindow::type(), KviChannel::userAction(), KviQuery::userAction(), and KviIrcConnection::userDataBase().
void KviServerParser::parseLiteralPart (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviChannel::closeOnPart(), KviFrame::closeWindow(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), KviWindow::frame(), KviIrcConnection::getCommonChannels(), KviIrcMessage::haltOutput(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_PART, KVI_OUT_QUERYTRACE, KviEvent_OnMePart, KviEvent_OnPart, KviOption_boolEnableQueryTracing, KviOption_boolKeepChannelOpenOnPart, KviOption_boolShowOwnParts, KVS_TRIGGER_EVENT_1_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KviQuery::notifyCommonChannels(), KviWindow::output(), KviIrcMessage::paramCount(), KviChannel::part(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviChannel::setDeadChan(), KviIrcMessage::setHaltOutput(), and UNRECOGNIZED_MESSAGE.
void KviServerParser::parseLiteralPing (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_SERVERPING, KviEvent_OnPing, KviOption_boolShowPingPong, KVS_TRIGGER_EVENT_2_HALTED, KviWindow::output(), KviIrcMessage::safePrefix(), KviIrcConnection::sendFmtData(), and KviIrcMessage::setHaltOutput().
void KviServerParser::parseLiteralPong (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_SERVERPING, KviEvent_OnPong, KviOption_boolShowPingPong, KVS_TRIGGER_EVENT_2_HALTED, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), KviWindow::output(), KviIrcMessage::safePrefix(), and KviIrcMessage::setHaltOutput().
void KviServerParser::parseLiteralPrivmsg (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), _KviCtcpMessage::bIgnored, _KviCtcpMessage::bIsFlood, _KviCtcpMessage::bUnknown, c, KviRegisteredUser::Channel, KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createQuery(), KviStr::cutLeft(), KviStr::cutRight(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), DECRYPT_IF_NEEDED, KviWindow::demandAttention(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pActiveWindow, g_pApp, KviIrcMessage::haltOutput(), KviWindow::hasAttention(), KviIrcConnectionStateData::identifyMsgCapabilityEnabled(), IdentifyMsgCapNotUsed, IdentifyMsgCapUsedIdentified, IdentifyMsgCapUsedNotIdentified, IS_ME, KviRegisteredUser::isIgnoreEnabledFor(), KviIrcConnectionServerInfo::isSupportedModePrefix(), kvi_mayBeSpam(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_BROADCASTPRIVMSG, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_IGNORE, KVI_OUT_QUERYPRIVMSG, KVI_OUT_QUERYPRIVMSGCRYPTED, KVI_OUT_SPAM, KVI_SMALLICON_QUERYPRIVMSG, KVI_USERACTION_PRIVMSG, KVI_WINDOW_TYPE_CHANNEL, KviEvent_OnChannelMessage, KviEvent_OnIgnoredMessage, KviEvent_OnQueryMessage, KviEvent_OnQueryWindowRequest, KviOption_boolCreateQueryOnPrivmsg, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolFlashQueryWindowOnNewMessages, KviOption_boolOperatorMessagesToActiveWindow, KviOption_boolPasteLastLogOnQueryJoin, KviOption_boolPopupNotifierOnNewQueryMessages, KviOption_boolSilentAntiSpam, KviOption_boolUseAntiSpamOnPrivmsg, KviOption_boolVerboseIgnore, KviOption_stringOnQueryMessageSound, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviStr::lastCharIs(), KviStr::len(), _KviCtcpMessage::msg, KviConsole::NoNotifier, KviApp::notifierMessage(), KviConsole::NoWindowFlashing, KviWindow::output(), KviConsole::outputPrivmsg(), parseCtcpRequest(), KviQuery::pasteLastLog(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviStr::ptr(), KviRegisteredUser::Query, KviIrcUserDataBase::registeredUser(), KviIrcUrl::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcMessage::setHaltOutput(), KviQuery::setTarget(), KviQString::sprintf(), KviIrcConnection::stateData(), _KviCtcpMessage::szTarget, KviIrcMessage::trailingString(), KviWindow::type(), KviChannel::userAction(), KviQuery::userAction(), and KviIrcConnection::userDataBase().
void KviServerParser::parseLiteralQuit (KviIrcMessage * msg) [private]
References __tr2qs, KviKvsVariantList::append(), c, KviIrcConnection::channelList(), KviIrcMessage::connection(), KviWindow::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviQString::equalCI(), KviIrcConnection::findQuery(), KviPointerList< T >::first(), KviIrcMessage::haltOutput(), KviKvsEventManager::instance(), KVI_OUT_QUIT, KVI_OUT_SPLIT, kvi_unixTime, KviEvent_OnNetsplit, KviEvent_OnQuit, KVS_TRIGGER_EVENT_2_HALTED, KviIrcConnectionNetsplitDetectorData::lastNetsplitOnQuitReason(), KviIrcConnectionNetsplitDetectorData::lastNetsplitOnQuitTime(), KviIrcConnection::netsplitDetectorData(), KviPointerList< T >::next(), KviWindow::output(), KviStr::ptr(), KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitReason(), and KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitTime().
void KviServerParser::parseLiteralTopic (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_UINT, KVI_OUT_TOPIC, KVI_TEXT_RESET, KVI_USERACTION_TOPIC, KviEvent_OnTopic, KviOption_uintOutputDatetimeFormat, KVS_TRIGGER_EVENT_4_HALTED, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), KviTopicWidget::setTopic(), KviTopicWidget::setTopicSetAt(), KviTopicWidget::setTopicSetBy(), KviChannel::topicWidget(), UNRECOGNIZED_MESSAGE, and KviChannel::userAction().
void KviServerParser::parseLiteralWallops (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WALLOPS, KviEvent_OnWallops, KviOption_boolOperatorMessagesToActiveWindow, KVS_TRIGGER_EVENT_4_HALTED, KviWindow::output(), KviIrcMessage::safeTrailing(), and KviIrcMessage::setHaltOutput().
void KviServerParser::parseLoginNicknameProblem (KviIrcMessage * msg) [private]
References __tr2qs, KviIdentityProfile::altNick(), KviIrcMessage::connection(), KviIrcMessage::console(), d, KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIdentityProfileSet::findNetwork(), KviIrcMessage::haltOutput(), KviIdentityProfileSet::instance(), KviIdentityProfileSet::isEmpty(), KviIdentityProfileSet::isEnabled(), KVI_DEFAULT_NICKNAME1, KVI_OPTION_STRING, KVI_OUT_NICKNAMEPROBLEM, KviOption_stringNickname1, KviOption_stringNickname2, KviOption_stringNickname3, KviIrcConnectionStateData::loginNickIndex(), KviIrcConnection::networkName(), KviUserListView::nickChange(), KviIrcConnectionUserInfo::nickName(), KviConsole::notifyListView(), KviIrcMessage::numeric(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviIrcConnectionStateData::setLoginNickIndex(), KviIrcConnectionUserInfo::setNickName(), KviIrcConnection::stateData(), KviQString::trimmed(), and KviIrcConnection::userInfo().
Referenced by parseNumericNicknameProblem(), and parseNumericUnavailResource().
void KviServerParser::parseMessage (const char * message, KviIrcConnection * pConnection)
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_PARANOIC, KviIrcMessage::allParams(), KviKvsVariantList::append(), KviIrcMessage::command(), KviIrcConnection::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcMessage::firstParam(), KviIrcMessage::haltOutput(), KviKvsEventManager::hasAppHandlers(), KviKvsEventManager::hasRawHandlers(), KviKvsEventManager::instance(), KviIrcMessage::isEmpty(), KviIrcMessage::isNumeric(), KVI_OUT_UNHANDLED, KVI_OUT_UNRECOGNIZED, kvi_strEqualCS(), kvi_time_t, kvi_unixTime, KviEvent_OnUnhandledLiteral, KviIrcConnectionStateData::lastReceivedWhoisReply(), m_literalParseProcTable, m_numericParseProcTable, m_szLastParserError, _KviLiteralMessageParseStruct::msgName, KviIrcMessage::nextParam(), KviIrcMessage::numeric(), KviWindow::output(), KviIrcMessage::paramCount(), parseNumericWhoisOther(), KviIrcMessage::prefix(), _KviLiteralMessageParseStruct::proc, KviStr::ptr(), KviIrcMessage::safePrefix(), KviIrcMessage::setHaltOutput(), KviIrcConnection::stateData(), KviKvsEventManager::trigger(), KviKvsEventManager::triggerRaw(), and KviIrcMessage::unrecognized().
Referenced by KviIrcConnection::incomingMessage(), and KviIrcConnection::incomingMessageNoFilter().
void KviServerParser::parseNumeric001 (KviIrcMessage * msg) [private]
References KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviIrcConnection::loginComplete(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::safeTrailing(), KviIrcConnectionUserInfo::setNickName(), KviIrcConnectionUserInfo::setUnmaskedHostName(), KviIrcContext::state(), KviIrcConnection::userInfo(), and KviIrcConnection::userInfoReceived().
void KviServerParser::parseNumeric002 (KviIrcMessage * msg) [private]
References KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviIrcConnection::loginComplete(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::safeTrailing(), and KviIrcContext::state().
void KviServerParser::parseNumeric003 (KviIrcMessage * msg) [private]
References KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviIrcConnection::loginComplete(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::safeTrailing(), and KviIrcContext::state().
void KviServerParser::parseNumeric004 (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, KviStr::append(), KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviStr::contains(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcConnectionServerInfo::getChannelModeDescription(), KviIrcConnectionServerInfo::getUserModeDescription(), KviIrcMessage::haltOutput(), KviStr::hasData(), KVI_OPTION_BOOL, KVI_OUT_SERVERINFO, KVI_OUT_SYSTEMWARNING, KviOption_boolShowExtendedServerInfo, KviIrcConnection::loginComplete(), KviStr::occurences(), KviWindow::output(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::paramCount(), KviStr::ptr(), KviIrcMessage::safeParam(), KviIrcConnection::serverInfo(), KviIrcConnection::serverInfoReceived(), KviIrcConnectionServerInfo::setServerVersion(), KviQString::sprintf(), KviIrcContext::state(), and KviOsInfo::version().
void KviServerParser::parseNumeric005 (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, KviIrcMessage::allParams(), KviIrcContext::Connected, KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviStr::hasData(), KVI_OPTION_BOOL, KVI_OUT_SERVERINFO, kvi_strEqualCI(), kvi_strEqualCIN(), KviOption_boolShowExtendedServerInfo, KviStr::len(), KviIrcConnection::loginComplete(), KviWindow::output(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::paramCount(), KviStr::ptr(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviIrcConnection::serverInfo(), KviIrcConnectionServerInfo::setMaxModeChanges(), KviIrcConnectionServerInfo::setMaxTopicLen(), KviIrcConnectionTarget::setNetworkName(), KviIrcConnectionServerInfo::setSupportedChannelModes(), KviIrcConnectionServerInfo::setSupportedChannelTypes(), KviIrcConnectionServerInfo::setSupportedModePrefixes(), KviIrcConnectionServerInfo::setSupportsCodePages(), KviIrcConnectionServerInfo::setSupportsWatchList(), KviIrcContext::state(), and KviIrcConnection::target().
void KviServerParser::parseNumeric020 (KviIrcMessage * msg) [private]
References KviIrcMessage::console(), KviWindow::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_CONNECTION, KVI_TEXT_BOLD, KviWindow::output(), KviIrcMessage::safePrefix(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumeric367 (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), getDateTimeStringFromCharTimeT(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_BAN, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviChannel::sentListRequest(), KviIrcConnection::serverInfo(), KviChannel::setMask(), and KviIrcConnectionServerInfo::supportedListModes().
void KviServerParser::parseNumeric368 (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_BAN, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviChannel::sentListRequest(), KviIrcConnection::serverInfo(), KviChannel::setListRequestDone(), and KviIrcConnectionServerInfo::supportedListModes().
void KviServerParser::parseNumericAList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericAway (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_PARANOIC, KviConsole::activeWindow(), KviIrcConnection::changeAwayState(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_AWAY, KviEvent_OnMeAway, KviOption_boolAutoGeneratedAwayNick, KviOption_boolChangeNickAway, KviOption_boolServerRepliesToActiveWindow, KviOption_stringCustomAwayNick, KVS_TRIGGER_EVENT_1_HALTED, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), and KviIrcMessage::setHaltOutput().
void KviServerParser::parseNumericBackFromAway (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_PARANOIC, KviConsole::activeWindow(), KviIrcConnectionUserInfo::awayTime(), KviIrcConnection::changeAwayState(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KviIrcConnectionUserInfo::isAway(), KVI_OPTION_BOOL, KVI_OUT_AWAY, kvi_unixTime, KviEvent_OnMeBack, KviOption_boolChangeNickAway, KviOption_boolServerRepliesToActiveWindow, KVS_TRIGGER_EVENT_2_HALTED, KviIrcConnectionUserInfo::nickNameBeforeAway(), KviWindow::output(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviIrcMessage::setHaltOutput(), KviQString::sprintf(), and KviIrcConnection::userInfo().
void KviServerParser::parseNumericCannotSend (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericCannotSendColor (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericCantJoinChannel (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_JOINERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericChannelModeIs (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), IS_CHANNEL_TYPE_FLAG, KVI_OPTION_BOOL, KVI_OUT_CHANMODE, KVI_OUT_MODE, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), parseChannelMode(), KviIrcMessage::safeParam(), and KviIrcMessage::safePrefix().
void KviServerParser::parseNumericCodePageScheme (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::allParams(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcConnection::console(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KVI_OUT_WHOISOTHER, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::prefix(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviIrcConnectionServerInfo::supportsCodePages().
void KviServerParser::parseNumericCodePageSet (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviLocale::codecForName(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcConnection::console(), KviIrcMessage::console(), KviIrcConnection::currentNickName(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_TEXTENCODING, KVI_OUT_UNHANDLED, KviWindow::output(), KviIrcMessage::prefix(), KviIrcMessage::safeParam(), KviIrcConnection::serverInfo(), KviIrcConnection::setEncoding(), KviWindow::setTextEncoding(), and KviIrcConnectionServerInfo::supportsCodePages().
void KviServerParser::parseNumericCommandSyntax (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_STATS, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericCreationTime (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviStr::isUnsignedNum(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_CREATIONTIME, KviOption_boolServerRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviWindow::output(), KviIrcMessage::safeParam(), KviStr::toUInt(), and UNRECOGNIZED_MESSAGE.
void KviServerParser::parseNumericEndOfAList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericEndOfExceptList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericEndOfInviteList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericEndOfLinks (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviConsole::context(), KviExternalServerDataParser::control(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_ENDOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LINKS, KviIrcContext::linksWindow(), and KviWindow::output().
void KviServerParser::parseNumericEndOfNames (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviChannel::hasAllNames(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), and KviChannel::setHasAllNames().
void KviServerParser::parseNumericEndOfQList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericEndOfReopList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericEndOfStats (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_STATS, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericEndOfWho (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviChannel::clearSentSyncWhoRequest(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviStr::Format, KviIrcMessage::haltOutput(), KviChannel::hasWhoList(), IS_CHANNEL_TYPE_FLAG, KVI_OPTION_BOOL, KVI_OUT_WHO, kvi_time_t, kvi_unixTime, KviOption_boolServerRepliesToActiveWindow, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), KviWindow::output(), KviIrcMessage::safeParam(), KviChannel::sentSyncWhoRequest(), KviChannel::setHasWhoList(), KviIrcConnectionStateData::setLastReceivedChannelWhoReply(), KviChannel::setLastReceivedWhoReply(), KviIrcConnection::stateData(), KviUserListView::updateArea(), and KviChannel::userListView().
void KviServerParser::parseNumericEndOfWhois (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviKvsVariantList::append(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), g_pApp, KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, KVI_TEXT_BOLD, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviKvsScript::PreserveParams, KviAsyncWhoisInfo::pWindow, KviIrcConnectionAsyncTemplateData< T >::remove(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviKvsVariantList::setAutoDelete(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szAway, KviAsyncWhoisInfo::szChannels, KviAsyncWhoisInfo::szHost, KviAsyncWhoisInfo::szIdle, KviAsyncWhoisInfo::szNick, KviAsyncWhoisInfo::szReal, KviAsyncWhoisInfo::szServer, KviAsyncWhoisInfo::szSignon, KviAsyncWhoisInfo::szUser, and KviApp::windowExists().
void KviServerParser::parseNumericEndOfWhowas (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, KVI_TEXT_BOLD, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safePrefix().
void KviServerParser::parseNumericExceptList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericInfo (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericInfoEnd (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KVI_TEXT_BOLD, KviWindow::output(), and KviIrcMessage::prefix().
void KviServerParser::parseNumericInfoStart (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KVI_TEXT_BOLD, KviWindow::output(), and KviIrcMessage::prefix().
void KviServerParser::parseNumericInviteList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericInviting (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_INVITE, KviWindow::output(), and KviIrcMessage::safeParam().
void KviServerParser::parseNumericIsOn (KviIrcMessage * msg) [private]
References KviConsole::activeWindow(), KviIrcMessage::allParams(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviNotifyListManager::handleIsOn(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviIrcConnection::notifyListManager(), KviWindow::output(), and KviIrcMessage::safePrefix().
void KviServerParser::parseNumericLinks (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviIrcMessage::connection(), KviIrcMessage::console(), KviConsole::context(), KviIrcContext::createLinksWindow(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_LINKS, KviIrcContext::linksWindow(), KviWindow::output(), and KviExternalServerDataParser::processData().
void KviServerParser::parseNumericList (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviIrcMessage::connection(), KviIrcMessage::console(), KviConsole::context(), KviExternalServerDataParser::control(), KviIrcContext::createListWindow(), KviIrcConnection::decodeText(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_STARTOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LIST, KviIrcContext::listWindow(), KviWindow::output(), and KviExternalServerDataParser::processData().
void KviServerParser::parseNumericListEnd (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviConsole::context(), KviExternalServerDataParser::control(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_ENDOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LIST, KviIrcContext::listWindow(), and KviWindow::output().
void KviServerParser::parseNumericListStart (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviConsole::context(), KviExternalServerDataParser::control(), KviIrcContext::createListWindow(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_STARTOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LIST, KviIrcContext::listWindow(), and KviWindow::output().
void KviServerParser::parseNumericMotd (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::endOfMotdReceived(), KviIrcMessage::haltOutput(), KVI_OUT_MOTD, KviIrcMessage::numeric(), KviWindow::outputNoFmt(), RPL_ENDOFMOTD, and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericNames (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviChannel::enableUserListUpdates(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviChannel::hasAllNames(), KviIrcConnectionServerInfo::isSupportedModePrefix(), KviChannel::join(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviIrcConnectionServerInfo::modeFlagFromPrefixChar(), KviChannel::myFlags(), KviWindow::output(), KviStr::ptr(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailingString(), KviTheme::save(), KviIrcConnection::serverInfo(), and KviWindow::updateCaption().
void KviServerParser::parseNumericNicknameProblem (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviConsole::isConnected(), KVI_OUT_NICKNAMEPROBLEM, KviWindow::output(), parseLoginNicknameProblem(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericNoSuchChannel (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), and KviIrcMessage::safeParam().
void KviServerParser::parseNumericNoSuchNick (KviIrcMessage * msg) [private]
References KviConsole::activeWindow(), KviKvsVariantList::append(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), ERR_NOSUCHNICK, KviIrcConnection::findQuery(), g_pApp, KviIrcMessage::haltOutput(), KVI_OUT_NICKNAMEPROBLEM, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviIrcMessage::numeric(), KviWindow::output(), KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviKvsScript::PreserveParams, KviAsyncWhoisInfo::pWindow, KviIrcConnectionAsyncTemplateData< T >::remove(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviKvsVariantList::setAutoDelete(), KviAsyncWhoisInfo::szNick, and KviApp::windowExists().
void KviServerParser::parseNumericNoSuchServer (KviIrcMessage * msg) [private]
References __tr2qs, KviKvsVariantList::append(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), g_pApp, KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviKvsScript::PreserveParams, KviAsyncWhoisInfo::pWindow, KviIrcConnectionAsyncTemplateData< T >::remove(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviKvsVariantList::setAutoDelete(), KviAsyncWhoisInfo::szNick, and KviApp::windowExists().
void KviServerParser::parseNumericNoTopic (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_TOPIC, KviOption_boolEchoNumericTopic, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcMessage::safeParam(), KviTopicWidget::setTopic(), and KviChannel::topicWidget().
void KviServerParser::parseNumericNotRegistered (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviIrcConnection::handleFailedInitialCapLs(), KviIrcConnectionStateData::ignoreOneYouHaveNotRegisteredError(), KviIrcConnectionStateData::isInsideInitialCapLs(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setIgnoreOneYouHaveNotRegisteredError(), and KviIrcConnection::stateData().
void KviServerParser::parseNumericQList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericReopList (KviIrcMessage * msg) [private]
void KviServerParser::parseNumericSaslFail (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::endInitialCapNegotiation(), KviIrcMessage::haltOutput(), KviIrcConnectionStateData::isInsideAuthenticate(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::safeTrailing(), and KviIrcConnection::stateData().
void KviServerParser::parseNumericSaslLogin (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::endInitialCapNegotiation(), KviIrcMessage::haltOutput(), KviIrcConnectionStateData::isInsideAuthenticate(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcConnection::stateData().
void KviServerParser::parseNumericSaslSuccess (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::endInitialCapNegotiation(), KviIrcMessage::haltOutput(), KviIrcConnectionStateData::isInsideAuthenticate(), KVI_OUT_SERVERINFO, KviWindow::outputNoFmt(), and KviIrcConnection::stateData().
void KviServerParser::parseNumericServerAdminInfoAdminContact (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KVI_TEXT_BOLD, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericServerAdminInfoAdminName (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KVI_TEXT_BOLD, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericServerAdminInfoServerName (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KVI_TEXT_BOLD, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericServerAdminInfoTitle (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::outputNoFmt(), KviIrcMessage::safeTrailing(), and KviQString::toUtf8().
void KviServerParser::parseNumericStartTls (KviIrcMessage * msg) [private]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviIrcMessage::numeric(), KviWindow::output(), parseNumericWhoisOther(), RPL_STARTTLSFAIL, RPL_STARTTLSOK, KviIrcConnectionStateData::sentStartTls(), and KviIrcConnection::stateData().
void KviServerParser::parseNumericStats (KviIrcMessage * msg) [private]
References KviStr::append(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::firstParam(), KviIrcMessage::haltOutput(), KviStr::hasData(), KVI_OUT_STATS, KviIrcMessage::nextParam(), KviWindow::outputNoFmt(), KviIrcMessage::paramCount(), KviIrcMessage::safeTrailing(), and KviQString::toUtf8().
void KviServerParser::parseNumericTime (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KVI_TEXT_BOLD, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericTopic (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_TOPIC, KviOption_boolEchoNumericTopic, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviTopicWidget::setTopic(), KviTopicWidget::setTopicSetBy(), and KviChannel::topicWidget().
void KviServerParser::parseNumericTopicWhoTime (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviStr::hasData(), KviIrcMask::hasHost(), KviIrcMask::hasUser(), KviIrcMask::host(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_TOPIC, KviOption_boolEchoNumericTopic, KviOption_boolServerRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviIrcMask::nick(), KviWindow::output(), KviIrcMessage::safeParam(), KviTopicWidget::setTopicSetAt(), KviTopicWidget::setTopicSetBy(), KviQString::sprintf(), KviChannel::topicWidget(), KviStr::toUInt(), and KviIrcMask::user().
void KviServerParser::parseNumericUnavailResource (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviConsole::isConnected(), KVI_OUT_NICKNAMEPROBLEM, KviWindow::output(), parseLoginNicknameProblem(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericUserhost (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviNotifyListManager::handleUserhost(), KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, KviOption_boolServerRepliesToActiveWindow, KviIrcConnection::notifyListManager(), KviWindow::output(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseNumericUserMode (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_MODE, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), parseUserMode(), and KviIrcMessage::safeParam().
void KviServerParser::parseNumericWatch (KviIrcMessage * msg) [private]
References KviConsole::activeWindow(), KviIrcMessage::allParams(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::haltOutput(), KviNotifyListManager::handleWatchReply(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviIrcConnection::notifyListManager(), KviWindow::output(), and KviIrcMessage::prefix().
void KviServerParser::parseNumericWhoisAuth (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), and KviIrcConnection::stateData().
void KviServerParser::parseNumericWhoisAway (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcUserEntry::setAway(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szAway, KviQuery::updateLabelText(), and KviIrcConnection::userDataBase().
void KviServerParser::parseNumericWhoisChannels (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviQString::appendFormatted(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), IS_CHANNEL_TYPE_FLAG, IS_USER_MODE_PREFIX, KVI_OPTION_BOOL, KVI_OUT_WHOISCHANNELS, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviAsyncWhoisInfo::szChannels.
void KviServerParser::parseNumericWhoisIdle (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_WHOISIDLE, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szIdle, KviAsyncWhoisInfo::szSignon, KviStr::toUInt(), and UNRECOGNIZED_MESSAGE.
void KviServerParser::parseNumericWhoisOther (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviAsyncWhoisInfo::szServer.
Referenced by parseMessage(), and parseNumericStartTls().
void KviServerParser::parseNumericWhoisServer (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISSERVER, KVI_TEXT_BOLD, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcUserEntry::setServer(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szServer, KviQuery::updateLabelText(), and KviIrcConnection::userDataBase().
void KviServerParser::parseNumericWhoisUser (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcConnection::asyncWhoisData(), KviIrcUserEntry::avatar(), KviConsole::checkDefaultAvatar(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviQString::equalCS(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), g_pActiveWindow, KviIrcUserEntry::gender(), KviIrcMessage::haltOutput(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, KVI_TEXT_BOLD, KVI_TEXT_UNDERLINE, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncTemplateData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcUserEntry::setHost(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcUserEntry::setRealName(), KviIrcUserEntry::setUser(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szHost, KviAsyncWhoisInfo::szNick, KviAsyncWhoisInfo::szReal, KviAsyncWhoisInfo::szUser, KviIrcUserEntry::Unknown, KviQuery::updateLabelText(), and KviIrcConnection::userDataBase().
void KviServerParser::parseNumericWhoReply (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcUserEntry::avatar(), KviIrcUserEntry::avatarRequested(), d, KviIrcUserDataBase::find(), KviStr::getToken(), KviChannel::hasWhoList(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_WHO, KVI_TEXT_BOLD, KVI_TEXT_COLOR, KVI_TEXT_RESET, KVI_TEXT_UNDERLINE, KviOption_boolRequestMissingAvatars, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviStr::ptr(), KviChannel::sentSyncWhoRequest(), KviIrcUserEntry::setAvatarRequested(), KviIrcUserEntry::setAway(), KviIrcUserEntry::setHops(), KviIrcUserEntry::setHost(), KviIrcUserEntry::setIrcOp(), KviIrcUserEntry::setRealName(), KviIrcUserEntry::setServer(), KviIrcUserEntry::setUser(), KviIrcUserEntry::setUserFlags(), KviStr::toInt(), and KviQuery::updateLabelText().
void KviServerParser::parseNumericWhowasUser (KviIrcMessage * msg) [private]
References __tr2qs, KviConsole::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, KVI_TEXT_BOLD, KVI_TEXT_UNDERLINE, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviServerParser::parseUserMode (KviIrcMessage * msg, const char * modeflptr) [private]
References KviIrcConnection::changeUserMode(), KviIrcMessage::connection(), KviIrcMessage::console(), KviKvsEventManager::hasAppHandlers(), KviKvsEventManager::instance(), KviEvent_OnNickServAuth, KviEvent_OnUserModeChange, KviIrcConnectionServerInfo::registerModeChar(), KviIrcConnection::serverInfo(), KviIrcMessage::setHaltOutput(), and KviKvsEventManager::trigger().
Referenced by parseLiteralMode(), and parseNumericUserMode().
void KviServerParser::replyCtcp (KviCtcpMessage * msg, const QString & data) [private]
References KviIrcMessage::connection(), KviIrcConnection::encodeText(), _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pSource, KviIrcConnection::sendFmtData(), and _KviCtcpMessage::szTag.
Referenced by parseCtcpRequestAvatar(), parseCtcpRequestClientinfo(), parseCtcpRequestFinger(), parseCtcpRequestPage(), parseCtcpRequestPing(), parseCtcpRequestSource(), parseCtcpRequestTime(), parseCtcpRequestUserinfo(), and parseCtcpRequestVersion().
Member Data Documentation
KviCtcpMessageParseStruct KviServerParser::m_ctcpReplyParseProcTable [static, private]
Initial value:
{
        { "ACTION"     , PTM(parseCtcpRequestAction)     , 0 },
        { "AVATAR"     , PTM(parseCtcpReplyAvatar)       , 0 },
        { "CLIENTINFO" , PTM(parseCtcpReplyGeneric)      , 0 },
        { "DCC"        , PTM(parseCtcpRequestDcc)        , 0 },
        { "FINGER"     , PTM(parseCtcpReplyGeneric)      , 0 },
        { "LAGCHECK"   , PTM(parseCtcpReplyLagcheck)     , KVI_CTCP_MESSAGE_PARSE_TRIGGERNOEVENT },
        { "PAGE"       , PTM(parseCtcpReplyGeneric)      , 0 },
        { "PING"       , PTM(parseCtcpReplyPing)         , 0 },
        { "SOURCE"     , PTM(parseCtcpReplyGeneric)      , 0 },
        { "TDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { "TIME"       , PTM(parseCtcpReplyGeneric)      , 0 },
        { "USERINFO"   , PTM(parseCtcpReplyUserinfo)     , 0 },
        { "VERSION"    , PTM(parseCtcpReplyGeneric)      , 0 },
        { "XDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { 0            , 0                               , 0 }
}
Referenced by parseCtcpReply(), and parseCtcpRequest().
KviCtcpMessageParseStruct KviServerParser::m_ctcpRequestParseProcTable [static, private]
Initial value:
{
        { "ACTION"     , PTM(parseCtcpRequestAction)     , 0 },
        { "AVATAR"     , PTM(parseCtcpRequestAvatar)     , 0 },
        { "CLIENTINFO" , PTM(parseCtcpRequestClientinfo) , 0 },
        { "DCC"        , PTM(parseCtcpRequestDcc)        , 0 },
        { "FINGER"     , PTM(parseCtcpRequestFinger)     , 0 },
        { "PAGE"       , PTM(parseCtcpRequestPage)       , 0 },
        { "PING"       , PTM(parseCtcpRequestPing)       , 0 },
        { "SOURCE"     , PTM(parseCtcpRequestSource)     , 0 },
        { "TDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { "TIME"       , PTM(parseCtcpRequestTime)       , 0 },
        { "USERINFO"   , PTM(parseCtcpRequestUserinfo)   , 0 },
        { "VERSION"    , PTM(parseCtcpRequestVersion)    , 0 },
        { "XDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { 0            , 0                               , 0 }
}
Referenced by parseCtcpRequest().
KviLiteralMessageParseStruct KviServerParser::m_literalParseProcTable [static, private]
Initial value:
{
        { "AUTHENTICATE" , PTM(parseLiteralAuthenticate) },
        { "CAP"          , PTM(parseLiteralCap)          },
        { "ERROR"        , PTM(parseLiteralError)        },
        { "INVITE"       , PTM(parseLiteralInvite)       },
        { "JOIN"         , PTM(parseLiteralJoin)         },
        { "KICK"         , PTM(parseLiteralKick)         },
        { "MODE"         , PTM(parseLiteralMode)         },
        { "NICK"         , PTM(parseLiteralNick)         },
        { "NOTICE"       , PTM(parseLiteralNotice)       },
        { "PART"         , PTM(parseLiteralPart)         },
        { "PING"         , PTM(parseLiteralPing)         },
        { "PONG"         , PTM(parseLiteralPong)         },
        { "PRIVMSG"      , PTM(parseLiteralPrivmsg)      },
        { "QUIT"         , PTM(parseLiteralQuit)         },
        { "TOPIC"        , PTM(parseLiteralTopic)        },
        { "WALLOPS"      , PTM(parseLiteralWallops)      },
        { 0              , 0                             }
}
Referenced by parseMessage().
messageParseProc KviServerParser::m_numericParseProcTable [static, private]
Referenced by parseMessage().
KviStr KviServerParser::m_szLastParserError [private]
Referenced by parseMessage().
The documentation for this class was generated from the following files:
src/kvirc/sparser/kvi_sparser.h
src/kvirc/sparser/kvi_sp_ctcp.cpp
src/kvirc/sparser/kvi_sp_literal.cpp
src/kvirc/sparser/kvi_sp_numeric.cpp
src/kvirc/sparser/kvi_sp_tables.cpp
src/kvirc/sparser/kvi_sparser.cpp