KVIrc: OptionsWidget_userListGrid Class Reference
OptionsWidget_userListGrid Class Reference
#include <OptionsWidget_userList.h>
Public Member Functions
virtual void commit ()
OptionsWidget_userListGrid (QWidget *parent)
~OptionsWidget_userListGrid ()
Protected Attributes
QComboBox * m_pGridTypeCombo
Constructor & Destructor Documentation
OptionsWidget_userListGrid::OptionsWidget_userListGrid (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addWidgetToLayout(), connect(), KviOptionsWidget::createLayout(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolUserListViewDrawGrid, KviOption_colorUserListViewGrid, KviOption_uintUserListViewGridType, l, m_pGridTypeCombo, s, and KviTalHBox::setSpacing().
OptionsWidget_userListGrid::~OptionsWidget_userListGrid ()
Member Function Documentation
void OptionsWidget_userListGrid::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KVI_USERLISTVIEW_GRIDTYPE_DEFAULT, KVI_USERLISTVIEW_GRIDTYPE_MAXIMUM, KviOption_uintUserListViewGridType, and m_pGridTypeCombo.
Member Data Documentation
QComboBox* OptionsWidget_userListGrid::m_pGridTypeCombo [protected]
Referenced by commit(), and OptionsWidget_userListGrid().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_userList.h
src/modules/options/OptionsWidget_userList.cpp