KVIrc: KviTrayIcon Class Reference
KviTrayIcon Class Reference
The KviTrayIcon class.
#include <KviTrayIcon.h>
Public Member Functions
virtual void die ()
Qt::WindowStates getPrevWindowState ()
KviTrayIcon ()
virtual void refresh ()
void setPrevWindowState (Qt::WindowStates state)
virtual ~KviTrayIcon ()
Private Attributes
Qt::WindowStates m_oStoredWindowStates
Detailed Description
The KviTrayIcon class.
Base class for the dock extension applets..
Constructor & Destructor Documentation
KviTrayIcon::KviTrayIcon () [inline]
Creates an instance of KviTrayIcon
virtual KviTrayIcon::~KviTrayIcon () [inline, virtual]
Destroys the instance of KviTrayIcon and frees all the relevant resources
Member Function Documentation
virtual void KviTrayIcon::die () [inline, virtual]
Reimplemented in KviTrayIconWidget.
Referenced by KviMainWindow::~KviMainWindow().
Qt::WindowStates KviTrayIcon::getPrevWindowState () [inline]
virtual void KviTrayIcon::refresh () [inline, virtual]
Reimplemented in KviTrayIconWidget.
Referenced by KviClassicWindowList::addItem(), KviIrcView::clearUnreaded(), KviWindowListButton::highlight(), KviTreeWindowListItem::highlight(), KviClassicWindowList::removeItem(), KviClassicWindowList::setActiveItem(), KviTreeWindowList::setActiveItem(), KviWindowListButton::unhighlight(), and KviTreeWindowListItem::unhighlight().
void KviTrayIcon::setPrevWindowState (Qt::WindowStates state) [inline]
Member Data Documentation
Qt::WindowStates KviTrayIcon::m_oStoredWindowStates [private]
The documentation for this class was generated from the following file:
src/kvirc/ui/KviTrayIcon.h