KVIrc: KviDnsThread Class Reference
KviDnsThread Class Reference
#include <kvi_dns.h>
Public Member Functions
void setQuery (const QString &query, KviDns::QueryType type)
Protected Member Functions
KviDnsThread (KviDns *pDns)
void postDnsError (KviDnsResult *dns, int iErr)
virtual void run ()
int translateDnsError (int iErr)
~KviDnsThread ()
Protected Attributes
KviDns * m_pParentDns
KviDns::QueryType m_queryType
QString m_szQuery
Friends
class KviDns
Constructor & Destructor Documentation
KviDnsThread::KviDnsThread (KviDns * pDns) [protected]
References m_pParentDns.
KviDnsThread::~KviDnsThread () [protected]
Member Function Documentation
void KviDnsThread::postDnsError (KviDnsResult * dns, int iErr) [protected]
References e, KVI_DNS_THREAD_EVENT_DATA, m_pParentDns, KviThread::postEvent(), KviThreadDataEvent< TData >::setData(), and KviDnsResult::setError().
Referenced by run().
void KviDnsThread::run () [protected, virtual]
Reimplemented from KviThread.
References KviDnsResult::appendAddress(), KviDnsResult::appendHostname(), KviNetUtils::binaryIpToStringIp(), e, KviDns::IPv4, KviDns::IPv6, KVI_DNS_THREAD_EVENT_DATA, KviError_dnsQueryFailed, KviError_dnsTemporaneousFault, KviError_hostNotFound, KviError_noHostToResolve, KviError_noIPv6Support, KviError_unrecoverableNameserverError, KviError_validNameButNoIpAddress, m_pParentDns, m_queryType, m_szQuery, postDnsError(), KviThread::postEvent(), KviThreadDataEvent< TData >::setData(), KviDnsResult::setError(), KviDnsResult::setQuery(), KviNetUtils::stringIpToBinaryIp(), KviQString::toUtf8(), and translateDnsError().
void KviDnsThread::setQuery (const QString & query, KviDns::QueryType type) [inline]
References m_queryType, and m_szQuery.
Referenced by KviDns::lookup().
int KviDnsThread::translateDnsError (int iErr) [protected]
References EAI_ADDRFAMILY, EAI_NODATA, KviError_dnsInternalErrorBadFlags, KviError_dnsInternalErrorOutOfMemory, KviError_dnsInternalErrorServiceNotSupported, KviError_dnsInternalErrorUnsupportedSocketType, KviError_dnsNoName, KviError_dnsQueryFailed, KviError_dnsTemporaneousFault, KviError_unrecoverableNameserverError, KviError_unsupportedAddressFamily, and KviError_validNameButNoIpAddress.
Referenced by run().
Friends And Related Function Documentation
friend class KviDns [friend]
Member Data Documentation
KviDns* KviDnsThread::m_pParentDns [protected]
Referenced by KviDnsThread(), postDnsError(), and run().
KviDns::QueryType KviDnsThread::m_queryType [protected]
Referenced by run(), and setQuery().
QString KviDnsThread::m_szQuery [protected]
Referenced by KviDnsResult::query(), run(), setQuery(), and KviDnsResult::setQuery().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/net/kvi_dns.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/net/kvi_dns.cpp