KVIrc: KviConnectAction Class Reference
KviConnectAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
virtual QAction * addToCustomToolBar (KviCustomToolBar *pTool)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
KviConnectAction (QObject *pParent)
Public Member Functions inherited from KviAction
QPixmap * bigIcon ()
Returns the big icon associated to the action.
const QString & bigIconId () const
Returns the id of the big icon associated to the action.
KviActionCategory * category () const
Returns the category of the action.
virtual const QString & description ()
Returns the description of the action.
unsigned int flags ()
Returns the flag associated to the action.
bool isEnabled () const
Returns true if the action is enabled.
virtual bool isKviUserActionNeverOverrideThis ()
Returns true if the action is user-defined.
const QString & keySequence () const
Returns the shortcut of the action.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), KviIconManager::SmallIcon eSmallIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
const QString & name () const
Returns the name of the action.
virtual void setEnabled (bool bEnabled)
Enables the action.
QPixmap * smallIcon ()
Returns the small icon associated to the action.
const QString & smallIconId () const
Returns the id of the small icon associated to the action.
void suicide ()
Destroys itself. Maybe the best function in the whole APIs :)
virtual const QString & visibleName ()
Returns the visible name of the action.
virtual ~KviAction ()
Destroys the action object.
Protected Member Functions
virtual void activate ()
Activates the action.
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual void reloadImages ()
Reloads the images.
virtual void setup ()
Enables or disables the action upon starting KVIrc.
Protected Member Functions inherited from KviAction
KviPointerList< QAction > * actionList ()
Returns the list of actions associated to the action.
void registerAccelerator ()
Registers the action shortcut in the application.
void registerAction (QAction *pAction)
Adds the action to the list.
bool setupDone () const
Returns true if the setup is finished.
void unregisterAccelerator ()
Removes the action shortcut from the application.
Protected Attributes
QString m_szAbortConnectionString
QString m_szConnectString
QString m_szDisconnectString
Protected Attributes inherited from KviAction
KviIconManager::SmallIcon m_eSmallIcon
QPointer< QShortcut > m_pAccel
KviPointerList< QAction > * m_pActionList
KviActionCategory * m_pCategory
QString m_szBigIconId
QString m_szDescription
QString m_szKeySequence
QString m_szName
QString m_szSmallIconId
QString m_szVisibleName
unsigned int m_uFlags
unsigned short int m_uInternalFlags
Additional Inherited Members
Public Types inherited from KviAction
enum Flags {
NeedsContext = 1, NeedsConnection = 2, WindowConsole = 4, WindowChannel = 8,
WindowQuery = 16, WindowDccChat = 32, InternalWindowMask = WindowConsole | WindowChannel | WindowQuery | WindowDccChat, EnableAtLogin = 64,
WindowOnlyIfUsersSelected = 128
}
Holds the flags of an action.
enum InternalFlags { Enabled = 1, SetupDone = 2 }
Holds the internal flags of an action.
Public Slots inherited from KviAction
Signals inherited from KviAction
void activated ()
Emitted when the action is being activated.
Static Public Member Functions inherited from KviAction
static int validateFlags (int iFlagsToValidate)
Validates the flags of the action.
Protected Slots inherited from KviAction
virtual void actionDestroyed ()
Removes the action from the list.
virtual void activeWindowChanged ()
Enables or disables the action upon checking the active window.
virtual void activeWindowSelectionStateChanged (bool bSelectedNow)
Enables or disables the action upon checking the active window.
Constructor & Destructor Documentation
KviConnectAction::KviConnectAction (QObject * pParent)
Member Function Documentation
void KviConnectAction::activate () protected virtual
Activates the action.
It's called when the user activates the action clicking on the toolbar, the menu or by hitting its shortcut.
Returns
void
Reimplemented from KviAction.
References KviMainWindow::activeContext(), c, KviIrcContext::connectOrDisconnect(), and g_pMainWindow.
Referenced by addToCustomToolBar(), and addToPopupMenu().
void KviConnectAction::activeContextChanged () protected virtual
Enables or disables the action upon checking the active context.
If the context doesn't exist, the action is disabled
Called when the frame changes the active context.
Note
It works only if NeedsContext is specified
Returns
void
Reimplemented from KviAction.
References activeContextStateChanged().
void KviConnectAction::activeContextStateChanged () protected virtual
Enables or disables the action upon checking the active context.
Called when the frame changes the state of the context
Returns
void
Reimplemented from KviAction.
References KviAction::actionList(), KviMainWindow::activeContext(), c, KviIrcContext::Connected, KviIrcContext::Connecting, KviPointerList< T >::first(), g_pIconManager, g_pMainWindow, KviIconManager::getBigIcon(), KviIrcContext::Idle, KVI_BIGICON_CONNECTED, KVI_BIGICON_CONNECTING, KVI_BIGICON_DISCONNECTED, KVI_OPTION_BOOL, KviOption_boolShowIconsInPopupMenus, KviIrcContext::LoggingIn, m_szAbortConnectionString, m_szConnectString, m_szDisconnectString, KviPointerList< T >::next(), p, KviIrcContext::PendingReconnection, and KviIrcContext::state().
Referenced by activeContextChanged(), addToCustomToolBar(), and reloadImages().
QAction * KviConnectAction::addToCustomToolBar (KviCustomToolBar * pParentToolBar) virtual
Adds the action to the given toolbar.
Parameters
pParentToolBar The toolbar where to add the action
Returns
QAction *
Reimplemented from KviAction.
References activate(), activeContextStateChanged(), connect(), g_pIconManager, KviIconManager::getBigIcon(), KVI_BIGICON_DISCONNECTED, KVI_COREACTION_CONNECT, m_szConnectString, KviAction::registerAction(), setup(), and KviAction::setupDone().
bool KviConnectAction::addToPopupMenu (QMenu * pMenu) virtual
Adds the action to the given popup.
Parameters
pMenu The menu where to add the action
Returns
bool
Reimplemented from KviAction.
References activate(), KviMainWindow::activeContext(), c, KviIrcContext::Connected, KviIrcContext::Connecting, g_pMainWindow, KviIrcContext::Idle, KviIrcContext::LoggingIn, m_szAbortConnectionString, m_szConnectString, m_szDisconnectString, KviAction::m_szKeySequence, KviIrcContext::PendingReconnection, setup(), KviAction::setupDone(), KviIrcContext::state(), and t().
void KviConnectAction::reloadImages () protected virtual
Reloads the images.
Called when the application wants to refresh the images in the toolbar
Returns
void
Reimplemented from KviAction.
References activeContextStateChanged().
void KviConnectAction::setup () protected virtual
Enables or disables the action upon starting KVIrc.
Returns
void
Reimplemented from KviAction.
References __tr2qs, m_szAbortConnectionString, m_szConnectString, m_szDisconnectString, and KviAction::setup().
Referenced by addToCustomToolBar(), and addToPopupMenu().
Member Data Documentation
QString KviConnectAction::m_szAbortConnectionString protected
Referenced by activeContextStateChanged(), addToPopupMenu(), and setup().
QString KviConnectAction::m_szConnectString protected
Referenced by activeContextStateChanged(), addToCustomToolBar(), addToPopupMenu(), and setup().
QString KviConnectAction::m_szDisconnectString protected
Referenced by activeContextStateChanged(), addToPopupMenu(), and setup().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp