KVIrc: OptionsWidget_topicLabel Class Reference
OptionsWidget_topicLabel Class Reference
#include <OptionsWidget_topicLabel.h>
Public Member Functions
OptionsWidget_topicLabel (QWidget *)
~OptionsWidget_topicLabel ()
Constructor & Destructor Documentation
OptionsWidget_topicLabel::OptionsWidget_topicLabel (QWidget * p)
References __tr2qs_ctx(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::createLayout(), KviOption_colorLabelBackground, KviOption_colorLabelForeground, KviOption_fontLabel, KviOption_pixmapLabelBackground, and KviOptionsWidget::layout().
OptionsWidget_topicLabel::~OptionsWidget_topicLabel ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_topicLabel.h
src/modules/options/OptionsWidget_topicLabel.cpp