KVIrc: KviWindow Class Reference
KviWindow Class Reference
Base class for all windows in KVIrc.
#include <KviWindow.h>
Public Types
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Slots
void autoRaise ()
void dock ()
void maximize ()
void minimize ()
void reloadImages ()
void restore ()
void savePropertiesAsDefault ()
void undock ()
Signals
void windowNameChanged ()
Public Member Functions
void activateSelf ()
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual void applyOptions ()
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getBaseLogFileName (QString &szBuffer)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual void ownAction (const QString &)
virtual void ownMessage (const QString &, bool=true)
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
virtual const QString & target ()
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Protected Slots
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
virtual void closeEvent (QCloseEvent *pEvent)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
virtual void fillCaptionBuffers ()
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void loadProperties (KviConfigurationFile *pCfg)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual QPixmap * myIconPtr ()
virtual void preprocessMessage (QString &szMessage)
virtual void saveProperties (KviConfigurationFile *pCfg)
void setType (Type eType)
virtual void triggerCreationEvents ()
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
bool m_bIsDocked
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Static Protected Attributes
static const char * m_typeTable [TypeCount]
Properties
int KviProperty_ChildFocusOwner
Friends
class KviInput
class KviMainWindow
class KviTreeWindowList
class KviTreeWindowListItem
class KviTreeWindowListItemDelegate
class KviWindowListButton
class KviWindowListItem
Detailed Description
Base class for all windows in KVIrc.
Member Enumeration Documentation
enum KviWindow::ActivityTemperature
Holds the activity meter in temperature scale.
Enumerator:
Ice
Ice
VeryCold
Very cold
Cold
Cold
Undefined
Undefined
Hot
Hot
VeryHot
Very hot
Fire
Fire
enum KviWindow::ActivityValue
Holds the activity meter in value scale.
Enumerator:
None
None
VeryLow
Very low
Low
Low
Medium
Medium
High
High
VeryHigh
Very high
enum KviWindow::AttentionLevel
attention levels usable in hasAttention()
Enumerator:
VisibleAndActive
The window is visible and active (aka: has user focus)
MainWindowIsVisible
The kvirc frame is visible but the window is not the active one
enum KviWindow::Type
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Note:
If you add a new type, insert it just before Unknown
Enumerator:
Console
Channel
Query
DeadChannel
DeadQuery
Editor
Terminal
SocketSpy
Links
List
DccChat
DccTransfer
DccCanvas
DccVoice
DccVideo
UserWindow
Tool
IOGraph
DirBrowser
ScriptEditor
ScriptObject
LogView
Offer
Debug
Unknown
TypeCount
Constructor & Destructor Documentation
KviWindow::KviWindow (Type eType, const QString & szName, KviConsoleWindow * pConsole = 0)
Constructs the window object.
Parameters:
eType The type of the window
lpFrm The main window
szName The name of the window
pConsole The parent console
Returns:
KviWindow
References connect(), g_pApp, g_uUniqueWindowId, KVI_WINDOW_MIN_HEIGHT, KVI_WINDOW_MIN_WIDTH, m_bIsDocked, m_eType, m_pButtonBox, m_pConsole, m_pFocusHandler, m_pHideToolsButton, m_pInput, m_pIrcView, m_pLastFocusedChild, m_pSplitter, m_pTextCodec, m_pTextEncodingButton, m_pWindowListItem, m_szName, m_uId, KviApplication::registerWindow(), and reloadImages().
KviWindow::~KviWindow () virtual
Destroys the window object.
References destroyWindowListItem(), g_pApp, g_pMdiWindowSystemMainPopup, g_pMdiWindowSystemTextEncodingPopup, g_pMdiWindowSystemTextEncodingPopupSmart, g_pMdiWindowSystemTextEncodingPopupSmartUtf8, g_pMdiWindowSystemTextEncodingPopupStandard, KviApplication::unregisterWindow(), and KviApplication::windowCount().
Member Function Documentation
void KviWindow::activateSelf ()
References KviMdiChild::activate(), and mdiParent().
bool KviWindow::activityMeter (unsigned int * puActivityValue, unsigned int * puActivityTemperature) virtual
Reimplemented in KviChannelWindow.
Referenced by KviWindowListButton::drawButtonLabel(), and KviTreeWindowListItemDelegate::paint().
void KviWindow::applyOptions () virtual
Reimplemented in KviChannelWindow, KviQueryWindow, FileTransferWindow, ListWindow, KviConsoleWindow, LinksWindow, and SocketSpyWindow.
References KviInput::applyOptions(), KviIrcView::applyOptions(), m_pInput, m_pIrcView, and updateCaption().
void KviWindow::autoRaise () slot
References m_pFocusHandler, and mdiParent().
Referenced by delayedAutoRaise(), maximize(), and restore().
virtual QFrame* KviWindow::buttonContainer () inline virtual
Reimplemented in KviChannelWindow, KviQueryWindow, and DccChatWindow.
Referenced by createCryptControllerButton(), and toggleButtonContainer().
void KviWindow::childDestroyed () protected slot
References childRemoved().
Referenced by childInserted().
void KviWindow::childEvent (QChildEvent * pEvent) protected virtual
References childInserted(), and childRemoved().
void KviWindow::childInserted (QWidget * pObject) protected
References childDestroyed(), connect(), and m_pFocusHandler.
Referenced by childEvent(), and eventFilter().
void KviWindow::childRemoved (QWidget * pObject) protected
References m_pFocusHandler, m_pLastFocusedChild, and NULL.
Referenced by childDestroyed(), childEvent(), and eventFilter().
void KviWindow::childrenTreeChanged (QWidget * pAdded) protected virtual
Referenced by KviInput::multiLineEditorButtonToggled().
void KviWindow::closeEvent (QCloseEvent * pEvent) protected virtual
Reimplemented in KviChannelWindow, and KviConsoleWindow.
References KviMainWindow::childWindowCloseRequest(), and g_pMainWindow.
KviIrcConnection * KviWindow::connection ()
Returns the current IRC connection (if any)
Returns:
KviIrcConnection *
References KviIrcContext::connection(), console(), KviConsoleWindow::context(), and context().
Referenced by KviMaskInputDialog::accept(), KviMaskEditor::addClicked(), KviConsoleWindow::applyHighlighting(), avatar_kvs_cmd_notify(), avatar_kvs_cmd_query(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KviConsoleWindow::avatarChanged(), KviConsoleWindow::avatarChangedUpdateWindows(), chan_kvs_fnc_common(), chan_kvs_fnc_getUrl(), KviChannelWindow::checkChannelSync(), KviConsoleWindow::checkDefaultAvatar(), KviChannelWindow::closeEvent(), KviUserListEntry::color(), KviConsoleWindow::connectionAttached(), KviApplication::connectionExists(), DccChatWindow::connectionInProgress(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), LinksWindow::connectionStateChange(), ListWindow::connectionStateChange(), context_kvs_cmd_clearQueue(), KviConsoleWindow::currentAvatar(), KviConsoleWindow::currentNetworkName(), dcc_fill_local_nick_user_host(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_get_listen_ip_address(), dcc_kvs_parse_default_parameters(), dcc_module_reply_errmsg(), dccModuleParseDccGet(), defaultTextCodec(), KviTrayIconWidget::doAway(), KviIrcView::doLinkToolTip(), DccFileTransfer::doResume(), KviIrcContextDisplay::drawContents(), KviKvsTreeNodeAliasSimpleCommand::execute(), ListWindow::exportList(), KviQueryWindow::fillCaptionBuffers(), KviChannelWindow::fillCaptionBuffers(), KviTrayIconWidget::fillContextPopup(), KviApplication::fillRecentChannelsPopup(), KviApplication::fillRecentNicknamesPopup(), KviConsoleWindow::fillStatusString(), KviQueryWindow::getBaseLogFileName(), KviChannelWindow::getBaseLogFileName(), KviChannelWindow::getConfigGroupName(), KviQueryWindow::getInfoLabelText(), KviWindowListBase::getTextForConsole(), KviIrcView::getTextLine(), KviUserListView::getUserFlag(), KviConsoleWindow::getUserTipText(), KviConsoleWindow::getWindowListTipText(), KviQueryWindow::getWindowListTipText(), KviIsOnNotifyListManager::handleIsOn(), DccBroker::handleResumeRequest(), LinksWindow::hostPopupClicked(), KviUserListView::insertUserEntry(), KviConsoleWindow::isIPv6Connection(), KviMaskEditor::itemDoubleClicked(), ListWindow::itemDoubleClicked(), KviChannelWindow::KviChannelWindow(), KviQueryWindow::KviQueryWindow(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviModeWidget::mouseDoubleClickEvent(), KviConsoleWindow::outputPrivmsg(), KviQueryWindow::ownAction(), KviChannelWindow::ownAction(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviUserListViewArea::paintEvent(), KviIrcServerParser::parseCtcpReplyLagcheck(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviUserInput::parseNonCommand(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumericWhoReply(), KviChangeUserModeAction::popupAboutToShow(), KviChangeUserModeAction::popupActivated(), preprocessMessage(), KviChannelWindow::removeMasks(), LinksWindow::requestLinks(), ListWindow::requestList(), KviConsoleWindow::resetAvatarForMatchingUsers(), DccBroker::rsendExecute(), KviIrcUrl::run(), KviChannelWindow::serverInfo(), KviChannelWindow::setAliveChan(), KviQueryWindow::setAliveQuery(), KviConsoleWindow::setAvatar(), KviConsoleWindow::setAvatarFromOptions(), KviChannelWindow::setDeadChan(), KviQueryWindow::setDeadQuery(), KviChannelWindow::setMode(), KviChannelWindow::setModeInList(), KviQueryWindow::setTarget(), DccFileTransfer::startConnection(), ListWindow::stoplistdownload(), KviTopicWidget::switchMode(), KviIrcConnectionRequestQueue::timerSlot(), KviIrcContextDisplay::tipRequest(), KviChannelWindow::toggleListModeEditor(), KviChannelWindow::topicSelected(), KviChannelWindow::updateModeLabel(), KviModeEditor::updateOpStatus(), KviMaskEditor::updateOpStatus(), KviConsoleWindow::updateUri(), KviChannelWindow::~KviChannelWindow(), and KviQueryWindow::~KviQueryWindow().
KviConsoleWindow* KviWindow::console () inline
Returns the console that this window belongs to.
May be null for windows that aren't bound to irc contexts
Returns:
KviConsoleWindow *
Referenced by KviApplication::activeConsole(), KviConsoleWindow::activeWindow(), KviTreeWindowList::addItem(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), chan_kvs_fnc_common(), channelsjoin_kvs_cmd_open(), ChannelsJoinDialog::clearClicked(), KviInputEditor::completion(), connection(), KviKvsRunTimeContext::console(), KviIrcView::console(), context(), context_kvs_fnc_getSSLCertInfo(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), KviWindowListButton::drawButtonLabel(), KviIrcContextDisplay::drawContents(), KviQueryWindow::getBaseLogFileName(), KviQueryWindow::getWindowListTipText(), SocketSpyWindow::incomingMessage(), KviClassicWindowList::insertButton(), ChannelsJoinDialog::joinClicked(), KviKvsCallbackObject::KviKvsCallbackObject(), KviKvsCoreSimpleCommands::KVSCSC(), links_kvs_cmd_open(), list_kvs_cmd_open(), KviUserListView::maybeTip(), SocketSpyWindow::outgoingMessage(), KviTreeWindowListItemDelegate::paint(), KviUserInput::parseNonCommand(), KviQueryWindow::pasteLastLog(), KviChannelWindow::pasteLastLog(), KviJoinChannelAction::popupAboutToShow(), KviChangeNickAction::popupAboutToShow(), KviChangeUserModeAction::popupAboutToShow(), KviJoinChannelAction::popupActivated(), KviChangeNickAction::popupActivated(), KviConnectToServerAction::popupActivated(), KviChangeUserModeAction::popupActivated(), OptionsWidget_servers::recentServersPopupClicked(), ChannelsJoinDialog::regClicked(), socketspy_kvs_cmd_open(), KviWindowListBase::switchWindow(), KviIrcContextDisplay::tipRequest(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), tmphighlight_kvs_fnc_isnickhighlighted(), and window_kvs_fnc_list().
KviIrcContext * KviWindow::context ()
Reimplemented in KviConsoleWindow.
References console(), and KviConsoleWindow::context().
Referenced by KviMainWindow::addWindow(), KviMainWindow::childWindowActivated(), KviChannelWindow::closeEvent(), connection(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviApplication::findWindowByCaption(), SocketSpyWindow::getBaseLogFileName(), LinksWindow::getBaseLogFileName(), ListWindow::getBaseLogFileName(), KviQueryWindow::getBaseLogFileName(), KviChannelWindow::getBaseLogFileName(), KviConsoleWindow::isConnected(), KviKvsCoreSimpleCommands::KVSCSC(), links_kvs_cmd_open(), list_kvs_cmd_open(), KviChannelWindow::setAliveChan(), KviQueryWindow::setAliveQuery(), KviChannelWindow::setDeadChan(), KviQueryWindow::setDeadQuery(), KviConsoleWindow::state(), KviStatusBarConnectionTimer::timerEvent(), UserWindow::UserWindow(), window_kvs_fnc_list(), KviChannelWindow::~KviChannelWindow(), KviQueryWindow::~KviQueryWindow(), and UserWindow::~UserWindow().
void KviWindow::contextPopup ()
References KviEvent_OnWindowPopupRequest, and KVS_TRIGGER_EVENT_0.
Referenced by KviWindowListButton::contextMenuEvent(), KviTreeWindowListTreeWidget::mousePressEvent(), and KviWindowListButton::mousePressEvent().
void KviWindow::createCryptControllerButton (QWidget * pPar) protected
References __tr2qs, buttonContainer(), connect(), toggleCryptController(), KviIconManager::UnLocked, and KviIconManager::UnLockedOff.
Referenced by DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), KviChannelWindow::KviChannelWindow(), and KviQueryWindow::KviQueryWindow().
void KviWindow::createSystemTextEncodingPopup () protected
References __tr2qs, KviLocale::_EncodingDescription::bSendUtf8, KviLocale::_EncodingDescription::bSmart, connect(), defaultTextCodec(), KviLocale::encodingDescription(), KviLocale::encodingGroup(), KviQString::equalCI(), g_pMdiWindowSystemTextEncodingActionGroup, g_pMdiWindowSystemTextEncodingCurrentAction, g_pMdiWindowSystemTextEncodingDefaultAction, g_pMdiWindowSystemTextEncodingPopup, g_pMdiWindowSystemTextEncodingPopupSmart, g_pMdiWindowSystemTextEncodingPopupSmartUtf8, g_pMdiWindowSystemTextEncodingPopupStandard, i, KviLocale::instance(), KVI_NUM_ENCODING_GROUPS, m_szTextEncoding, NULL, KviLocale::_EncodingDescription::pcDescription, KviLocale::_EncodingDescription::pcName, systemTextEncodingPopupActivated(), u, and KviLocale::_EncodingDescription::uGroup.
Referenced by textEncodingButtonClicked().
void KviWindow::createTextEncodingButton (QWidget * pPar) protected
References __tr2qs, connect(), createToolButton(), m_pTextEncodingButton, KviIconManager::TextEncoding, and textEncodingButtonClicked().
Referenced by DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), DccWindow::DccWindow(), KviChannelWindow::KviChannelWindow(), and KviQueryWindow::KviQueryWindow().
QToolButton * KviWindow::createToolButton (QWidget * pPar, const char * pcName, KviIconManager::SmallIcon eIcon, const QString & szToolTip, bool bOn) protected
References KviTalToolTip::add(), g_pIconManager, and KviIconManager::getSmallIcon().
Referenced by createTextEncodingButton().
void KviWindow::createWindowListItem () protected virtual
References KviWindowListBase::addItem(), g_pMainWindow, KviMainWindow::m_pWindowList, and m_pWindowListItem.
Referenced by KviMainWindow::addWindow(), and KviMainWindow::recreateWindowList().
void KviWindow::cryptControllerFinished () protected slot
Referenced by toggleCryptController().
void KviWindow::cryptSessionInfoDestroyed () protected slot
References __tr2qs, KVI_OUT_SYSTEMERROR, and output().
QString KviWindow::decodeText (const char * pcText) inline
References defaultTextCodec(), and m_pTextCodec.
Referenced by dccModuleParseDccGet(), dccModuleParseDccRSend(), dccModuleParseDccSend(), DccChatWindow::event(), DccVideoWindow::event(), SocketSpyWindow::incomingMessage(), SocketSpyWindow::outgoingMessage(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpReplyUserinfo(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric020(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcSocket::proxyHandleHttpFinalReply(), and KviIrcSocket::readHttpProxyErrorData().
QTextCodec * KviWindow::defaultTextCodec () virtual
References connection(), and KviIrcConnection::textCodec().
Referenced by createSystemTextEncodingPopup(), decodeText(), encodeText(), forceTextCodec(), makeEncoder(), and saveProperties().
void KviWindow::delayedAutoRaise ()
References autoRaise().
Referenced by filetransferwindow_alloc(), iograph_module_cmd_open(), logview_kvs_cmd_open(), KviIrcServerParser::parseLiteralNick(), KviMainWindow::setActiveWindow(), and sharedfileswindow_kvs_cmd_open().
void KviWindow::delayedClose ()
Referenced by KviMdiChild::closeEvent(), dcc_kvs_cmd_abort(), KviTreeWindowListTreeWidget::mousePressEvent(), and KviWindowListButton::mousePressEvent().
void KviWindow::demandAttention ()
Notify the window manager that this window demands attention.
Depending on the os/window manager, this method uses different approaches to trigger a notification that tipically makes the application entry flash on the application bar.
Returns:
void
References g_pMainWindow, and mdiParent().
Referenced by DccChatWindow::event(), DccVideoWindow::event(), KviNotifyListManager::notifyOnLine(), KviConsoleWindow::outputPrivmsg(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
void KviWindow::destroyWindowListItem () protected virtual
References g_pMainWindow, KviMainWindow::m_pWindowList, m_pWindowListItem, and KviWindowListBase::removeItem().
Referenced by KviMainWindow::recreateWindowList(), and ~KviWindow().
void KviWindow::dock () slot
References KviMainWindow::dockWindow(), g_pMainWindow, and KviMainWindow::setActiveWindow().
QByteArray KviWindow::encodeText (const QString & szText) inline
References defaultTextCodec(), and m_pTextCodec.
Referenced by KviChannelWindow::closeEvent(), KviKvsCoreSimpleCommands::KVSCSC(), DccChatWindow::ownAction(), DccVideoWindow::ownAction(), KviQueryWindow::ownAction(), KviChannelWindow::ownAction(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), and KviChannelWindow::topicSelected().
bool KviWindow::eventFilter (QObject * pObject, QEvent * pEvent) protected
Reimplemented in KviChannelWindow, and FileTransferWindow.
References childInserted(), childRemoved(), KviMainWindow::childWindowActivated(), g_pActiveWindow, g_pMainWindow, m_pFocusHandler, and m_pLastFocusedChild.
void KviWindow::fillCaptionBuffers () protected virtual
Reimplemented in KviChannelWindow, KviQueryWindow, PopupEditorWindow, DccVideoWindow, RawEditorWindow, DccVoiceWindow, EventEditorWindow, LogViewWindow, FileTransferWindow, ListWindow, KviConsoleWindow, SharedFilesWindow, DccChatWindow, LinksWindow, HelpWindow, KviIOGraphWindow, CodeTesterWindow, KviDebugWindow, UserWindow, and SocketSpyWindow.
References fillSingleColorCaptionBuffers(), m_szName, and m_szPlainTextCaption.
Referenced by KviKvsScriptWindowWindow::setWindowTitleString(), and updateCaption().
void KviWindow::fillSingleColorCaptionBuffers (const QString & szName) inline protected
Referenced by fillCaptionBuffers(), and UserWindow::UserWindow().
void KviWindow::focusInEvent (QFocusEvent *) protected virtual
Reimplemented in DccVoiceWindow.
References KviMainWindow::childWindowActivated(), g_pActiveWindow, g_pMainWindow, m_pFocusHandler, m_pIrcView, m_pLastFocusedChild, and updateCaption().
bool KviWindow::focusNextPrevChild (bool bNext) protected virtual
void KviWindow::forceTextCodec (QTextCodec * pCodec)
References defaultTextCodec(), m_pTextCodec, and m_szTextEncoding.
void KviWindow::getBaseLogFileName (QString & szBuffer) virtual
Reimplemented in KviChannelWindow, KviQueryWindow, DccVideoWindow, DccVoiceWindow, FileTransferWindow, ListWindow, KviConsoleWindow, SharedFilesWindow, DccChatWindow, LinksWindow, KviDebugWindow, and SocketSpyWindow.
References m_szName.
Referenced by getDefaultLogFileName().
void KviWindow::getConfigGroupName (QString & szBuffer) virtual
Reimplemented in KviChannelWindow, PopupEditorWindow, ActionEditorWindow, AliasEditorWindow, RawEditorWindow, EventEditorWindow, and CodeTesterWindow.
References typeString().
Referenced by KviMainWindow::addWindow(), KviMainWindow::closeWindow(), and savePropertiesAsDefault().
void KviWindow::getDefaultLogFileName (QString & szBuffer)
References KviKvsVariant::asString(), KviFileUtils::encodeFileName(), KviQString::ensureLastCharIs(), KviQString::escapeKvs(), KviKvsScript::evaluate(), g_pApp, getBaseLogFileName(), KviApplication::getLocalKvircDirectory(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_PATH_SEPARATOR_CHAR, KviOption_boolGzipLogs, KviOption_stringLogsDynamicPath, KviOption_uintOutputDatetimeFormat, KviApplication::Log, KviFileUtils::makeDir(), KviQString::PermitFunctions, KviQString::PermitVariables, and typeString().
Referenced by log_kvs_cmd_start(), and KviIrcView::startLogging().
virtual void KviWindow::getWindowListTipText (QString & szBuffer) inline virtual
Reimplemented in KviChannelWindow, KviQueryWindow, and KviConsoleWindow.
Referenced by KviWindowListButton::tipRequest().
bool KviWindow::hasAttention (AttentionLevel eLevel = VisibleAndActive)
Returns whether this window is the active one.
This method is useful because it takes in consideration that this window can be either docked or undocked, and takes a parameter that defines the strictness of the checks used. Level MainWindowIsVisible is fine to check if we needs to trigger the notifier Level VisibleAndActive is useful to trigger highlights
Parameters:
eLevel the level of checks to be done
Returns:
bool
References g_pActiveWindow, g_pMainWindow, MainWindowIsVisible, mdiParent(), and VisibleAndActive.
Referenced by NotifierWindow::addMessage(), DccChatWindow::event(), DccVideoWindow::event(), KviApplication::fileDownloadTerminated(), internalOutput(), KviNotifyListManager::notifyOnLine(), KviConsoleWindow::outputPrivmsg(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), NotifierWindow::shouldHideIfMainWindowGotAttention(), and KviConsoleWindow::triggerOnHighlight().
bool KviWindow::highlightMe (unsigned int uValue) virtual
References KviWindowListItem::highlight(), and m_pWindowListItem.
Referenced by window_kvs_cmd_highlight().
bool KviWindow::highlightMeter (unsigned int * puValue) virtual
References KviWindowListItem::highlightLevel(), and m_pWindowListItem.
QString KviWindow::id () inline
Returns the global ID of this window.
This is unique in the application
Returns:
QString
Referenced by KviKvsCoreFunctions::KVSCF(), KviInputEditor::pasteClipboardWithConfirmation(), KviInputEditor::pasteSelectionWithConfirmation(), KviApplication::registerWindow(), spaste_kvs_cmd_list(), spaste_kvs_cmd_stop(), KviApplication::unregisterWindow(), and window_kvs_fnc_open().
KviInput* KviWindow::input () inline
Referenced by LogViewWindow::createLog(), KviUserListViewArea::keyPressEvent(), KviIrcView::mousePressEvent(), KviModeWidget::reset(), window_kvs_cmd_insertInInputText(), window_kvs_cmd_setInputText(), and KviIrcViewToolWidget::~KviIrcViewToolWidget().
void KviWindow::internalOutput (KviIrcView * pView, int iMsgType, const kvi_wchar_t * pwText, int iFlags = 0)
References KviIrcView::appendText(), hasAttention(), KviIrcView::hasLineMark(), KviWindowListItem::highlight(), KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_UINT, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_HIGHLIGHT, KVI_OUT_QUERYNOTICE, KVI_OUT_QUERYNOTICECRYPTED, KVI_OUT_QUERYPRIVMSG, KVI_OUT_QUERYPRIVMSGCRYPTED, KVI_OUT_QUERYTRACE, KviOption_boolHighlightOnlyAtCostumHighlightLevel, KviOption_boolHighlightOnlyNormalMsg, KviOption_boolHighlightOnlyNormalMsgHighlightInChanToo, KviOption_boolHighlightOnlyNormalMsgQueryToo, KviOption_uintMinHighlightLevel, m_pWindowListItem, outputNoFmt(), outputProxy(), KviIrcView::SetLineMark, and KviIrcView::TriggersNotification.
Referenced by output(), KviChannelWindow::outputMessage(), and outputNoFmt().
bool KviWindow::isDocked () inline
Referenced by KviMainWindow::saveWindowProperties().
bool KviWindow::isMaximized ()
References KviMdiChild::Maximized, and mdiParent().
Referenced by KviMainWindow::maximizeWindow(), and KviMainWindow::saveWindowProperties().
bool KviWindow::isMinimized ()
References mdiParent(), and KviMdiChild::Minimized.
Referenced by KviTreeWindowListItem::captionChanged(), KviWindowListButton::drawButtonLabel(), KviTreeWindowListTreeWidget::mousePressEvent(), KviWindowListButton::mousePressEvent(), and KviMainWindow::setActiveWindow().
const QString & KviWindow::lastLineOfText ()
References KviQString::Empty, KviIrcView::lastLineOfText(), and m_pIrcView.
const QString & KviWindow::lastMessageText ()
References KviQString::Empty, KviIrcView::lastMessageText(), and m_pIrcView.
void KviWindow::listWindowTypes ()
References __tr2qs, i, KVI_OUT_SYSTEMMESSAGE, m_typeTable, outputNoFmt(), and TypeCount.
Referenced by window_kvs_cmd_listtypes().
void KviWindow::loadProperties (KviConfigurationFile * pCfg) protected virtual
Reimplemented in KviChannelWindow, ClassEditorWindow, KviQueryWindow, PopupEditorWindow, ActionEditorWindow, AliasEditorWindow, RawEditorWindow, EventEditorWindow, KviConsoleWindow, HelpWindow, CodeTesterWindow, and KviDebugWindow.
References KviQString::Empty, KVI_OPTION_BOOL, KviOption_boolCommandlineInUserFriendlyModeByDefault, KviOption_boolHideInputToolButtons, m_pInput, m_szName, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readEntry(), KviInput::setButtonsHidden(), setTextEncoding(), and KviInput::setUserFriendly().
Referenced by KviMainWindow::addWindow().
virtual const QString& KviWindow::localNick () inline virtual
Reimplemented in DccVideoWindow, and DccChatWindow.
References KviQString::Empty.
void KviWindow::lostUserFocus () protected virtual
Reimplemented in KviChannelWindow.
References KviIrcView::clearLineMark(), KviIrcView::hasLineMark(), and m_pIrcView.
Referenced by KviMainWindow::changeEvent(), and KviMainWindow::childWindowActivated().
QTextEncoder * KviWindow::makeEncoder ()
References defaultTextCodec(), and m_pTextCodec.
Referenced by KviChannelWindow::ownAction(), KviQueryWindow::ownMessage(), and KviChannelWindow::ownMessage().
void KviWindow::maximize () slot
References autoRaise(), KviMdiChild::maximize(), and mdiParent().
Referenced by KviMainWindow::addWindow(), and KviMainWindow::maximizeWindow().
KviMdiChild* KviWindow::mdiParent () inline
Returns the mdiParent widget.
May be nulll if the window is undocked
Returns:
KviMdiChild *
Referenced by activateSelf(), autoRaise(), KviMainWindow::closeWindow(), demandAttention(), KviMainWindow::dockWindow(), hasAttention(), isMaximized(), isMinimized(), maximize(), minimize(), NotifierWindowTab::mouseDoubleClickEvent(), KviThemedComboBox::paintEvent(), KviThemedLabel::paintEvent(), KviThemedLineEdit::paintEvent(), KviThemedTreeWidget::paintEvent(), FileTransferWidget::paintEvent(), KviIOGraphWindow::paintEvent(), KviIrcView::paintEvent(), KviUserListViewArea::paintEvent(), KviInputEditor::paintEvent(), restore(), KviMainWindow::saveWindowProperties(), KviMainWindow::setActiveWindow(), KviMainWindow::undockWindow(), and updateCaption().
void KviWindow::minimize () slot
References mdiParent(), and KviMdiChild::minimize().
Referenced by DccBroker::executeChat(), KviDebugWindow::getInstance(), KvsObject_window::init(), iograph_module_cmd_open(), KviIrcConnection::loginComplete(), logview_kvs_cmd_open(), KviMainWindow::minimizeWindow(), KviTreeWindowListTreeWidget::mousePressEvent(), KviWindowListButton::mousePressEvent(), sharedfileswindow_kvs_cmd_open(), and window_kvs_fnc_open().
void KviWindow::moveEvent (QMoveEvent * pEvent) protected virtual
Reimplemented in KviIOGraphWindow.
References updateBackgrounds().
QPixmap * KviWindow::myIconPtr () protected virtual
Reimplemented in KviChannelWindow, ClassEditorWindow, KviQueryWindow, ActionEditorWindow, PopupEditorWindow, AliasEditorWindow, DccVideoWindow, RawEditorWindow, DccVoiceWindow, EventEditorWindow, FileTransferWindow, LogViewWindow, ListWindow, KviConsoleWindow, SharedFilesWindow, DccChatWindow, UrlDialog, LinksWindow, HelpWindow, KviIOGraphWindow, CodeTesterWindow, KviDebugWindow, KviKvsScriptWindowWindow, UserWindow, and SocketSpyWindow.
References KviIconManager::DefaultIcon, g_pIconManager, and KviIconManager::getSmallIcon().
Referenced by KviWindowListButton::drawButtonLabel(), KviTreeWindowListItemDelegate::paint(), updateIcon(), youAreDocked(), and youAreUndocked().
unsigned long int KviWindow::numericId () inline
Returns the global ID of this window.
This is unique in the application
Returns:
QString
Referenced by KviKvsCoreFunctions::KVSCF(), and KviKvsReport::report().
void KviWindow::output (int iMsgType, const char * pcFormat, ...) virtual
References internalOutput(), kvi_va_end, kvi_va_list, kvi_va_start, l, m_pIrcView, preprocessMessage(), and KviQString::vsprintf().
Referenced by action_kvs_cmd_list(), UPnP::RootService::addDeviceServices(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_list(), addon_kvs_cmd_register(), addon_kvs_cmd_uninstall(), KviIrcConnectionTargetResolver::asyncStartResolve(), avatar_kvs_cmd_notify(), KviChannelWindow::checkChannelSync(), DccBroker::chooseSaveFileName(), KviInputEditor::completion(), DccChatWindow::connected(), DccVoiceWindow::connected(), DccVideoWindow::connected(), KviIrcContext::connectionEstabilished(), KviIrcContext::connectionFailed(), SocketSpyWindow::connectionInitiated(), DccChatWindow::connectionInProgress(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), SocketSpyWindow::connectionTerminated(), KviIrcContext::connectionTerminated(), LogViewWindow::createLog(), KviIrcLink::createSocket(), cryptSessionInfoDestroyed(), dcc_module_request_error(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), dccModuleParseDccVoice(), KviIsOnNotifyListManager::delayedIsOnSession(), KviIsOnNotifyListManager::delayedNotifySession(), KviIsOnNotifyListManager::delayedUserhostSession(), KviKvsDnsManager::dnsLookupTerminated(), KviIsOnNotifyListManager::doMatchUser(), KviWatchNotifyListManager::doMatchUser(), dumpChildObjects(), KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), LinksWindow::endOfLinks(), KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), KviIdentSentinel::event(), DccChatWindow::event(), DccVoiceWindow::event(), DccVideoWindow::event(), DccFileTransfer::event(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsPopupMenu::executeEpilogues(), KviKvsPopupMenu::executePrologues(), KviApplication::fileDownloadTerminated(), KviKvsPopupMenuItemExtMenu::fill(), KviKvsObject::function_listProperties(), KviIrcConnection::handleFailedInitialCapLs(), KviIsOnNotifyListManager::handleIsOn(), KviStupidNotifyListManager::handleIsOn(), DccChatWindow::handleMarshalError(), DccVoiceWindow::handleMarshalError(), DccVideoWindow::handleMarshalError(), KviIsOnNotifyListManager::handleUserhost(), KviWatchNotifyListManager::handleWatchReply(), KviIrcConnectionTargetResolver::haveServerIp(), HttpFileTransfer::headersReceived(), KviIrcConnection::heartbeat(), KviIrcConnection::hostNameLookupTerminated(), LinksWindow::hostPopupClicked(), KviApplication::ipcMessage(), KviKvsCoreSimpleCommands::KVSCSC(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviLagMeter::lagCheckRegister(), KviIrcConnection::linkEstabilished(), KviIrcLink::linkFilterDestroyed(), KviModuleManager::loadModule(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcView::mouseDoubleClickEvent(), KviIsOnNotifyListManager::newNotifySession(), KviIsOnNotifyListManager::newUserhostSession(), KviQueryWindow::notifyCommonChannels(), KviQueryWindow::notifyTargetChange(), objects_kvs_fnc_listObjects(), options_kvs_module_print_pages(), KviIrcServerParser::otherChannelError(), DccFileTransfer::outputAndLog(), KviIrcSocket::outputProxyError(), KviIrcSocket::outputProxyMessage(), KviIrcSocket::outputSocketError(), KviIrcSocket::outputSocketMessage(), KviIrcSocket::outputSocketWarning(), KviIrcSocket::outputSSLError(), KviIrcSocket::outputSSLMessage(), DccChatWindow::ownAction(), DccVideoWindow::ownAction(), KviQueryWindow::ownAction(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCommandEndOfHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseCtcpRequest(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestAvatar(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseMessage(), KviUserInput::parseNonCommand(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric020(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfLinks(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericInfoEnd(), KviIrcServerParser::parseNumericInfoStart(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericListEnd(), KviIrcServerParser::parseNumericListStart(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchChannel(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericStartTls(), KviIrcServerParser::parseNumericTime(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericUserMode(), KviIrcServerParser::parseNumericWatch(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhoReply(), KviIrcServerParser::parseNumericWhowasUser(), KviQueryWindow::pasteLastLog(), LinksWindow::processData(), ListWindow::processData(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), DccBroker::recvFileManage(), regchan_kvs_cmd_showlist(), reguser_kvs_cmd_showlist(), DccBroker::renameDccSendFile(), DccBroker::renameOverwriteResume(), KviKvsReport::report(), HttpFileTransfer::requestSent(), KviIrcConnection::resolveLocalHost(), KviIrcLink::resolverTerminated(), KviIrcConnection::restartNotifyList(), DccBroker::rsendExecute(), DccBroker::sendFileExecute(), KviIsOnNotifyListManager::sendIsOn(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), KviIrcConnectionTargetResolver::serverLookupTerminated(), KviConsoleWindow::setAvatar(), KviIrcConnection::setEncoding(), sharedfile_kvs_cmd_list(), snd_kvs_cmd_autodetect(), KviIrcLink::socketStateChange(), spaste_kvs_cmd_list(), DccChatWindow::sslError(), KviIsOnNotifyListManager::start(), KviWatchNotifyListManager::start(), DccChatWindow::startConnection(), DccVoiceWindow::startConnection(), DccVideoWindow::startConnection(), HttpFileTransfer::statusMessage(), KviLagMeter::timerEvent(), KviKvsTimerManager::timerEvent(), HttpFileTransfer::transferTerminated(), KviKvsProcessAsyncOperation::trigger(), KviKvsEventManager::triggerHandlers(), KviModuleManager::unloadModule(), and KviIrcConnection::userInfoReceived().
void KviWindow::output (int iMsgType, const kvi_wchar_t * pwFormat, ...) virtual
References internalOutput(), kvi_va_end, kvi_va_list, kvi_va_start, l, m_pIrcView, preprocessMessage(), and KviQString::vsprintf().
void KviWindow::output (int iMsgType, const QString & szFmt, ...) virtual
References internalOutput(), kvi_va_end, kvi_va_list, kvi_va_start_by_reference, l, m_pIrcView, preprocessMessage(), and KviQString::vsprintf().
void KviWindow::outputNoFmt (int iMsgType, const char * pcText, int iFlags = 0) virtual
References internalOutput(), m_pIrcView, and preprocessMessage().
Referenced by KviIrcConnectionTargetResolver::abort(), KviInputEditor::completion(), KviIrcContext::connectButtonClicked(), KviIrcContext::connectionFailed(), KviIrcContext::connectToCurrentServer(), dccModuleParseDccRecv(), LinksWindow::endOfLinks(), ListWindow::endOfList(), KviIdentSentinel::event(), DccVoiceWindow::event(), DccVideoWindow::event(), KviKvsScript::execute(), KviKvsObject::function_listProperties(), SocketSpyWindow::incomingMessage(), internalOutput(), LogViewWindow::itemSelected(), KviKvsCoreSimpleCommands::KVSCSC(), listWindowTypes(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), SocketSpyWindow::outgoingMessage(), KviQueryWindow::ownAction(), KviQueryWindow::ownMessage(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumericCommandSyntax(), KviIrcServerParser::parseNumericEndOfStats(), KviIrcServerParser::parseNumericInfo(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericSaslSuccess(), KviIrcServerParser::parseNumericServerAdminInfoTitle(), KviIrcServerParser::parseNumericStats(), KviChannelWindow::partMessageSent(), LinksWindow::processData(), regchan_kvs_cmd_showlist(), reguser_kvs_cmd_showlist(), KviKvsReport::report(), LinksWindow::requestLinks(), ListWindow::requestList(), LinksWindow::reset(), ListWindow::reset(), KviIrcConnection::sendData(), KviIrcConnection::sendFmtData(), sharedfile_kvs_cmd_list(), snd_kvs_cmd_autodetect(), KviIrcLink::socketStateChange(), KviStupidNotifyListManager::start(), DccChatWindow::startingSSLHandshake(), ListWindow::stoplistdownload(), KviIrcContext::terminateConnectionRequest(), and KviIrcConnection::userInfoReceived().
virtual void KviWindow::outputNoFmt (int iMsgType, const kvi_wchar_t * pwText, int iFlags = 0) inline virtual
void KviWindow::outputNoFmt (int iMsgType, const QString & szText, int iFlags = 0) virtual
References internalOutput(), m_pIrcView, and preprocessMessage().
KviWindow * KviWindow::outputProxy () virtual
Referenced by internalOutput().
virtual void KviWindow::ownAction (const QString &) inline virtual
Reimplemented in KviChannelWindow, KviQueryWindow, DccVideoWindow, and DccChatWindow.
virtual void KviWindow::ownMessage (const QString & , bool = true) inline virtual
Reimplemented in KviChannelWindow, KviQueryWindow, DccVideoWindow, and DccChatWindow.
Referenced by KviUserInput::parseNonCommand(), SlowPasteController::pasteClipboard(), and SlowPasteController::pasteFile().
virtual const QString& KviWindow::plainTextCaption () inline virtual
Referenced by KviTreeWindowListItem::captionChanged(), check_url(), KviWindowListButton::drawButtonLabel(), KviApplication::findWindowByCaption(), NotifierWindow::paintEvent(), and urllist_module_event_onUrl().
void KviWindow::preprocessMessage (QString & szMessage) protected virtual
Reimplemented in KviChannelWindow.
References connection(), m_pConsole, KviIrcConnection::serverInfo(), KviControlCodes::stripControlBytes(), and KviIrcConnectionServerInfo::supportedChannelTypes().
Referenced by output(), and outputNoFmt().
void KviWindow::reloadImages () slot
References updateIcon().
Referenced by KviWindow().
void KviWindow::restore () slot
References autoRaise(), mdiParent(), and KviMdiChild::restore().
Referenced by KviMainWindow::maximizeWindow(), and KviMainWindow::setActiveWindow().
void KviWindow::saveProperties (KviConfigurationFile * pCfg) protected virtual
Reimplemented in KviChannelWindow, ClassEditorWindow, KviQueryWindow, PopupEditorWindow, ActionEditorWindow, AliasEditorWindow, RawEditorWindow, EventEditorWindow, KviConsoleWindow, HelpWindow, CodeTesterWindow, and KviDebugWindow.
References defaultTextCodec(), KviQString::Empty, KviQString::equalCI(), KviInput::isButtonsHidden(), KviInput::isUserFriendly(), m_pInput, m_pTextCodec, m_szTextEncoding, and KviConfigurationFile::writeEntry().
Referenced by KviMainWindow::saveWindowProperties().
void KviWindow::savePropertiesAsDefault () slot
References KviQString::equalCI(), g_pMainWindow, getConfigGroupName(), KviMainWindow::saveWindowProperties(), and typeString().
void KviWindow::setFixedCaption (const QString & szCaption) inline
Referenced by ActionEditorWindow::ActionEditorWindow(), AliasEditorWindow::AliasEditorWindow(), ClassEditorWindow::ClassEditorWindow(), and KviKvsScriptWindowWindow::setWindowTitleString().
void KviWindow::setProgress (int iProgress)
Sets the progress for the WindowList item.
If "progress" makes sense in your window, well, use this
Parameters:
iProgress The progress to set
Returns:
void
References m_pWindowListItem, and KviWindowListItem::setProgress().
bool KviWindow::setTextEncoding (const QString & szTextEncoding)
References KviLocale::codecForName(), KviLocale::instance(), m_pTextCodec, and m_szTextEncoding.
Referenced by loadProperties(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcConnection::setEncoding(), KviIrcConnection::setupSrvCodec(), and systemTextEncodingPopupActivated().
void KviWindow::setType (Type eType) inline protected
Referenced by KviChannelWindow::setAliveChan(), KviQueryWindow::setAliveQuery(), KviChannelWindow::setDeadChan(), and KviQueryWindow::setDeadQuery().
void KviWindow::setWindowName (const QString & szName)
Sets the name of the window.
Parameters:
szName The name of the window
Returns:
void
References m_szName, and windowNameChanged().
Referenced by KviQueryWindow::nickChange(), and KviQueryWindow::setTarget().
KviTalSplitter* KviWindow::splitter () inline
Returns the splitter of this window.
It shouldn't be null... but... well... who knows ? :D ...better check it
Returns:
KviTalSplitter *
void KviWindow::systemTextEncodingPopupActivated (QAction * pAction) protected slot
References KviQString::cutFromFirst(), g_pMdiWindowSystemTextEncodingCurrentAction, g_pMdiWindowSystemTextEncodingDefaultAction, and setTextEncoding().
Referenced by createSystemTextEncodingPopup().
virtual const QString& KviWindow::target () inline virtual
Reimplemented in KviChannelWindow, DccVideoWindow, DccVoiceWindow, KviQueryWindow, and DccChatWindow.
References KviQString::Empty.
Referenced by KviIrcContext::connectionEstabilished(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), and KviApplication::notifierMessage().
QTextCodec* KviWindow::textCodec () inline
const QString& KviWindow::textEncoding () inline
void KviWindow::textEncodingButtonClicked () protected slot
References createSystemTextEncodingPopup(), g_pMdiWindowSystemTextEncodingPopup, and m_pTextEncodingButton.
Referenced by createTextEncodingButton().
void KviWindow::toggleButtonContainer () virtual
References buttonContainer().
Referenced by KviChannelWindow::toggleToolButtons().
void KviWindow::toggleCryptController () protected slot
References connect(), cryptControllerFinished(), KviKvs::done(), m_pInput, and m_pSplitter.
Referenced by createCryptControllerButton().
virtual void KviWindow::triggerCreationEvents () inline protected virtual
Reimplemented in KviChannelWindow, KviQueryWindow, DccVideoWindow, KviConsoleWindow, and DccChatWindow.
Referenced by KviMainWindow::addWindow().
virtual void KviWindow::triggerDestructionEvents () inline protected virtual
Reimplemented in DccVideoWindow, and DccChatWindow.
Referenced by KviMainWindow::closeWindow().
Type KviWindow::type () const inline
Returns the type of the window.
Returns:
Type
Referenced by KviAction::activeWindowChanged(), KviAction::activeWindowSelectionStateChanged(), KviTreeWindowList::addItem(), KviMainWindow::addWindow(), KviConsoleWindow::applyHighlighting(), KviTreeWindowListItem::captionChanged(), chan_kvs_find_channel(), chan_kvs_fnc_isdead(), KviIrcView::doLinkToolTip(), KviWindowListButton::drawButtonLabel(), KviUserListView::emitDoubleClick(), KviUserListView::emitRightClick(), KviApplication::findConsole(), KviIrcView::getTextLine(), KviClassicWindowList::insertButton(), KviTreeWindowListItem::key(), KviIrcView::mouseDoubleClickEvent(), KviInputEditor::mousePressEvent(), KviApplication::notifierMessage(), KviConsoleWindow::outputPrivmsg(), KviTreeWindowListItemDelegate::paint(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviUserInput::parseNonCommand(), KviApplication::resetAvatarForMatchingUsers(), KviApplication::restartLagMeters(), KviApplication::restartNotifyLists(), KviApplication::setAvatarFromOptions(), spaste_kvs_cmd_stop(), spaste_kvs_find_window(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), tmphighlight_kvs_fnc_isnickhighlighted(), KviApplication::topmostConnectedConsole(), KviIrcView::triggerMouseRelatedKvsEvents(), window_kvs_cmd_setWindowTitle(), KviChannelWindow::~KviChannelWindow(), KviMainWindow::~KviMainWindow(), and KviQueryWindow::~KviQueryWindow().
const char * KviWindow::typeString () virtual
Returns a descriptive name of the window type.
Returns:
const char *
References m_eType, m_typeTable, TypeCount, and Unknown.
Referenced by KviMainWindow::addWindow(), getConfigGroupName(), getDefaultLogFileName(), and savePropertiesAsDefault().
void KviWindow::undock () slot
References g_pMainWindow, and KviMainWindow::undockWindow().
void KviWindow::unhighlight ()
Reimplemented in KviChannelWindow.
References m_pWindowListItem, and KviWindowListItem::unhighlight().
Referenced by window_kvs_cmd_highlight().
void KviWindow::updateBackgrounds (QObject * pObj = 0)
Referenced by moveEvent().
void KviWindow::updateCaption () virtual
References KviWindowListItem::captionChanged(), fillCaptionBuffers(), KviEvent_OnWindowTitleRequest, KVS_TRIGGER_EVENT_2_HALTED, m_pWindowListItem, m_szPlainTextCaption, mdiParent(), and KviMdiChild::setWindowTitle().
Referenced by applyOptions(), KviIrcConnection::changeAwayState(), KviIrcConnection::changeUserMode(), DccChatWindow::connected(), DccVoiceWindow::connected(), DccVideoWindow::connected(), LinksWindow::endOfLinks(), focusInEvent(), KviDebugWindow::KviDebugWindow(), KviQueryWindow::KviQueryWindow(), KviQueryWindow::nickChange(), KviIrcConnection::nickChange(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseNumericNames(), KviIrcConnection::serverInfoReceived(), KviChannelWindow::setAliveChan(), KviChannelWindow::setChannelMode(), KviChannelWindow::setChannelModeWithParam(), KviChannelWindow::setDeadChan(), KviQueryWindow::setDeadQuery(), KviIrcContext::setState(), KviQueryWindow::setTarget(), UserWindow::setWindowTitleStrings(), youAreDocked(), and youAreUndocked().
void KviWindow::updateIcon () virtual
References myIconPtr().
Referenced by reloadImages(), KviChannelWindow::setAliveChan(), KviQueryWindow::setAliveQuery(), KviChannelWindow::setDeadChan(), and KviQueryWindow::setDeadQuery().
KviIrcView* KviWindow::view () const inline
Returns the KviIrcView of this window.
May be NULL if the window has no KviIrcView (and thus supports no direct output)
Returns:
KviIrcView *
Referenced by KviMainWindow::childWindowActivated(), KviApplication::heartbeat(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), log_kvs_fnc_file(), KviInputEditor::nextLine(), KviInputEditor::nextPage(), KviInputEditor::previousLine(), KviInputEditor::previousPage(), KviInputEditor::scrollToLastReadLine(), KviInputEditor::search(), KviInputEditor::zoomDefault(), KviInputEditor::zoomIn(), and KviInputEditor::zoomOut().
KviWindowListItem* KviWindow::windowListItem () inline
Returns the windowList item.
The window has ALWAYS a WindowList item
Returns:
KviWindowListItem *
Referenced by KviMainWindow::childWindowActivated(), KviMainWindow::recreateWindowList(), and KviWindowListBase::switchWindow().
const QString& KviWindow::windowName () inline
Returns the name of this window.
Returns:
const QString &
Referenced by KviMainWindow::addWindow(), KviConsoleWindow::applyHighlighting(), KviTreeWindowListItem::captionChanged(), chan_kvs_fnc_getUrl(), chan_kvs_fnc_name(), KviMainWindow::changeEvent(), KviInputEditor::completion(), KviIrcContext::connectionTerminated(), KviIrcView::doLinkToolTip(), KviWindowListButton::drawButtonLabel(), KviDebugWindow::fillCaptionBuffers(), KviConsoleWindow::fillCaptionBuffers(), KviQueryWindow::fillCaptionBuffers(), KviQueryWindow::getBaseLogFileName(), KviChannelWindow::getBaseLogFileName(), KviChannelWindow::getConfigGroupName(), KviIrcConnection::heartbeat(), KviClassicWindowList::insertButton(), KviTreeWindowListItem::key(), NotifierWindowTab::labelChanged(), NotifierWindowTab::NotifierWindowTab(), KviQueryWindow::ownAction(), KviChannelWindow::ownAction(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcConnection::registerChannel(), KviKvsReport::report(), UrlDialog::sayToWin(), KviQueryWindow::target(), KviChannelWindow::target(), tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_removechannel(), and tmphighlight_kvs_fnc_ischannelhighlighted().
void KviWindow::windowNameChanged () signal
Referenced by setWindowName().
void KviWindow::youAreDocked () protected virtual
References m_bIsDocked, myIconPtr(), and updateCaption().
Referenced by KviMainWindow::dockWindow().
void KviWindow::youAreUndocked () protected virtual
References m_bIsDocked, myIconPtr(), and updateCaption().
Referenced by KviMainWindow::addWindow(), and KviMainWindow::undockWindow().
Friends And Related Function Documentation
friend class KviInput friend
Referenced by DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), KviChannelWindow::KviChannelWindow(), KviDebugWindow::KviDebugWindow(), KviQueryWindow::KviQueryWindow(), and UserWindow::UserWindow().
friend class KviMainWindow friend
Reimplemented in KviConsoleWindow.
friend class KviTreeWindowList friend
friend class KviTreeWindowListItem friend
friend class KviTreeWindowListItemDelegate friend
friend class KviWindowListButton friend
friend class KviWindowListItem friend
Member Data Documentation
bool KviWindow::m_bIsDocked protected
Referenced by KviWindow(), youAreDocked(), and youAreUndocked().
Type KviWindow::m_eType protected
Referenced by KviWindow(), and typeString().
KviTalHBox* KviWindow::m_pButtonBox protected
Reimplemented in DccChatWindow.
Referenced by DccVideoWindow::DccVideoWindow(), DccWindow::DccWindow(), KviChannelWindow::KviChannelWindow(), KviQueryWindow::KviQueryWindow(), KviWindow(), KviConsoleWindow::resizeEvent(), DccVideoWindow::resizeEvent(), KviQueryWindow::resizeEvent(), KviChannelWindow::resizeEvent(), DccVideoWindow::sizeHint(), and KviChannelWindow::sizeHint().
KviConsoleWindow* KviWindow::m_pConsole protected
Referenced by KviChannelWindow::closeEvent(), LinksWindow::connectionStateChange(), ListWindow::connectionStateChange(), SocketSpyWindow::fillCaptionBuffers(), LinksWindow::fillCaptionBuffers(), ListWindow::fillCaptionBuffers(), LinksWindow::hostPopupClicked(), ListWindow::itemDoubleClicked(), KviWindow(), LinksWindow::LinksWindow(), ListWindow::ListWindow(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), preprocessMessage(), LinksWindow::requestLinks(), ListWindow::requestList(), KviQueryWindow::setTarget(), ListWindow::stoplistdownload(), KviChannelWindow::updateModeLabel(), LinksWindow::~LinksWindow(), and ListWindow::~ListWindow().
QWidget* KviWindow::m_pFocusHandler protected
Referenced by autoRaise(), childInserted(), childRemoved(), eventFilter(), focusInEvent(), and KviWindow().
QToolButton* KviWindow::m_pHideToolsButton protected
Referenced by KviChannelWindow::KviChannelWindow(), KviWindow(), and KviChannelWindow::toggleToolButtons().
KviInput* KviWindow::m_pInput protected
Referenced by KviConsoleWindow::applyOptions(), applyOptions(), DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), KviConsoleWindow::ircUriChanged(), KviChannelWindow::KviChannelWindow(), KviDebugWindow::KviDebugWindow(), KviQueryWindow::KviQueryWindow(), KviWindow(), loadProperties(), UserWindow::resizeEvent(), KviDebugWindow::resizeEvent(), DccChatWindow::resizeEvent(), KviConsoleWindow::resizeEvent(), DccVideoWindow::resizeEvent(), KviQueryWindow::resizeEvent(), KviChannelWindow::resizeEvent(), saveProperties(), KviDebugWindow::sizeHint(), DccChatWindow::sizeHint(), KviConsoleWindow::sizeHint(), KviQueryWindow::sizeHint(), KviChannelWindow::sizeHint(), toggleCryptController(), and UserWindow::UserWindow().
KviIrcView* KviWindow::m_pIrcView protected
Referenced by SocketSpyWindow::applyOptions(), LinksWindow::applyOptions(), KviConsoleWindow::applyOptions(), ListWindow::applyOptions(), FileTransferWindow::applyOptions(), applyOptions(), DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), DccVoiceWindow::DccVoiceWindow(), LogViewWindow::deleteCurrent(), FileTransferWindow::FileTransferWindow(), focusInEvent(), LogViewWindow::itemSelected(), LogViewWindow::keyPressEvent(), KviChannelWindow::KviChannelWindow(), KviDebugWindow::KviDebugWindow(), KviQueryWindow::KviQueryWindow(), KviWindow(), lastLineOfText(), lastMessageText(), LinksWindow::LinksWindow(), ListWindow::ListWindow(), KviChannelWindow::loadProperties(), LogViewWindow::LogViewWindow(), lostUserFocus(), KviQueryWindow::mergeQuery(), output(), KviChannelWindow::outputMessage(), outputNoFmt(), UserWindow::resizeEvent(), KviChannelWindow::setAliveChan(), KviQueryWindow::setAliveQuery(), KviChannelWindow::showDoubleView(), SocketSpyWindow::sizeHint(), KviDebugWindow::sizeHint(), DccChatWindow::sizeHint(), KviConsoleWindow::sizeHint(), KviQueryWindow::sizeHint(), LogViewWindow::sizeHint(), DccVoiceWindow::sizeHint(), KviChannelWindow::sizeHint(), SocketSpyWindow::SocketSpyWindow(), and UserWindow::UserWindow().
QWidget* KviWindow::m_pLastFocusedChild protected
Referenced by childRemoved(), eventFilter(), focusInEvent(), and KviWindow().
KviTalSplitter* KviWindow::m_pSplitter protected
Referenced by DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), DccVoiceWindow::DccVoiceWindow(), FileTransferWindow::FileTransferWindow(), HelpWindow::HelpWindow(), KviChannelWindow::KviChannelWindow(), KviDebugWindow::KviDebugWindow(), KviQueryWindow::KviQueryWindow(), KviWindow(), LinksWindow::LinksWindow(), ListWindow::ListWindow(), KviDebugWindow::loadProperties(), HelpWindow::loadProperties(), KviConsoleWindow::loadProperties(), KviQueryWindow::loadProperties(), KviChannelWindow::loadProperties(), LogViewWindow::LogViewWindow(), SocketSpyWindow::resizeEvent(), KviDebugWindow::resizeEvent(), HelpWindow::resizeEvent(), LinksWindow::resizeEvent(), DccChatWindow::resizeEvent(), SharedFilesWindow::resizeEvent(), KviConsoleWindow::resizeEvent(), LogViewWindow::resizeEvent(), ListWindow::resizeEvent(), FileTransferWindow::resizeEvent(), DccVoiceWindow::resizeEvent(), DccVideoWindow::resizeEvent(), KviQueryWindow::resizeEvent(), KviChannelWindow::resizeEvent(), KviDebugWindow::saveProperties(), HelpWindow::saveProperties(), KviConsoleWindow::saveProperties(), KviQueryWindow::saveProperties(), KviChannelWindow::saveProperties(), SharedFilesWindow::SharedFilesWindow(), KviQueryWindow::showListView(), KviConsoleWindow::showNotifyList(), KviDebugWindow::sizeHint(), LinksWindow::sizeHint(), SharedFilesWindow::sizeHint(), KviQueryWindow::sizeHint(), ListWindow::sizeHint(), LogViewWindow::sizeHint(), FileTransferWindow::sizeHint(), DccVideoWindow::sizeHint(), KviChannelWindow::sizeHint(), SocketSpyWindow::SocketSpyWindow(), toggleCryptController(), KviChannelWindow::toggleListModeEditor(), KviChannelWindow::toggleListView(), and KviChannelWindow::toggleModeEditor().
QTextCodec* KviWindow::m_pTextCodec protected
Referenced by decodeText(), encodeText(), forceTextCodec(), KviWindow(), makeEncoder(), saveProperties(), and setTextEncoding().
QToolButton* KviWindow::m_pTextEncodingButton protected
Referenced by createTextEncodingButton(), KviWindow(), and textEncodingButtonClicked().
KviWindowListItem* KviWindow::m_pWindowListItem protected
Referenced by KviTreeWindowList::addItem(), createWindowListItem(), destroyWindowListItem(), highlightMe(), highlightMeter(), internalOutput(), KviWindow(), setProgress(), unhighlight(), KviChannelWindow::unhighlight(), updateCaption(), and KviWindowListItem::~KviWindowListItem().
QString KviWindow::m_szName protected
Referenced by KviChannelWindow::closeEvent(), fillCaptionBuffers(), KviChannelWindow::fillCaptionBuffers(), getBaseLogFileName(), KviQueryWindow::getInfoLabelText(), KviQueryWindow::getWindowListTipText(), KviWindow(), loadProperties(), KviChannelWindow::ownAction(), KviChannelWindow::removeMasks(), KviChannelWindow::setAliveChan(), KviChannelWindow::setMode(), setWindowName(), KviChannelWindow::toggleListModeEditor(), and KviChannelWindow::topicSelected().
QString KviWindow::m_szPlainTextCaption protected
Referenced by SocketSpyWindow::fillCaptionBuffers(), KviDebugWindow::fillCaptionBuffers(), CodeTesterWindow::fillCaptionBuffers(), KviIOGraphWindow::fillCaptionBuffers(), HelpWindow::fillCaptionBuffers(), LinksWindow::fillCaptionBuffers(), DccChatWindow::fillCaptionBuffers(), SharedFilesWindow::fillCaptionBuffers(), KviConsoleWindow::fillCaptionBuffers(), ListWindow::fillCaptionBuffers(), FileTransferWindow::fillCaptionBuffers(), LogViewWindow::fillCaptionBuffers(), DccVoiceWindow::fillCaptionBuffers(), EventEditorWindow::fillCaptionBuffers(), RawEditorWindow::fillCaptionBuffers(), DccVideoWindow::fillCaptionBuffers(), PopupEditorWindow::fillCaptionBuffers(), KviQueryWindow::fillCaptionBuffers(), fillCaptionBuffers(), KviChannelWindow::fillCaptionBuffers(), KviChannelWindow::getWindowListTipText(), UserWindow::setWindowTitleStrings(), updateCaption(), and UserWindow::UserWindow().
QString KviWindow::m_szTextEncoding protected
Referenced by createSystemTextEncodingPopup(), forceTextCodec(), saveProperties(), and setTextEncoding().
const char * KviWindow::m_typeTable static protected
Initial value:
{
        "console",
        "channel",
        "query",
        "deadchannel",
        "deadquery",
        "editor",
        "help",
        "terminal",
        "socketspy",
        "links",
        "list",
        "dccchat",
        "dcctransfer",
        "dcccanvas",
        "dccvoice",
        "dccvideo",
        "userwindow",
        "tool",
        "iograph",
        "dirbrowser",
        "scripteditor",
        "scriptobject",
        "logview",
        "offer",
        "debug",
        "unknown"
}
Referenced by listWindowTypes(), and typeString().
unsigned long int KviWindow::m_uId protected
Referenced by KviWindow().
Property Documentation
int KviWindow::KviProperty_ChildFocusOwner read
The documentation for this class was generated from the following files:
src/kvirc/ui/KviWindow.h
src/kvirc/ui/KviWindow.cpp