KVIrc: KviMdiManager Class Reference
KviMdiManager Class Reference
Handles all MDI windows.
#include <KviMdiManager.h>
Public Slots
void cascadeMaximized ()
void cascadeWindows ()
void expandHorizontal ()
void expandVertical ()
void minimizeAll ()
void restoreAll ()
void tile ()
void tileAnodine ()
void toggleAutoTile ()
Public Member Functions
void destroyChild (KviMdiChild *lpC)
Remove and delete the subwindow.
bool eventFilter (QObject *obj, QEvent *event)
Filters out some events: (de)activation events, window switching.
void focusPreviousTopChild (KviMdiChild *pExcludeThis=NULL)
Move the focus the the previous active window.
int getVisibleChildCount ()
Get all visible subwindows.
void hideChild (KviMdiChild *lpC)
Hides the specified child and focuses some other child.
bool isInSDIMode ()
Check if we are in SDI mode.
KviMdiManager (QWidget *pParent, KviMainWindow *pFrm, const char *pcName)
Constructs the Mdi manager object.
void manageChild (KviMdiChild *lpC, bool bCascade=true, QRect *setGeom=0)
Add an KviMdiChild to the area.
QPoint scrollBarsOffset ()
Returns the current scrollbar offsets.
void setTopChild (KviMdiChild *lpC)
Bring the KviMdiChild to the foreground.
void showAndActivate (KviMdiChild *lpC)
Show the KviMdiChild and bring it to the front.
KviMdiChild * topChild ()
Get the currently active window.
KviTalPopupMenu * windowPopup ()
Returns the window popup.
~KviMdiManager ()
Destroys the Mdi manager object.
Protected Slots
void fillWindowPopup ()
void menuActivated (int id)
void slotSubWindowActivated (QMdiSubWindow *pMdiChild)
void tileMethodMenuActivated (int id)
Protected Member Functions
virtual void paintEvent (QPaintEvent *e)
Repaints the transparent backgrounds if activated.
void setIsInSDIMode (bool bMode)
Sets if we are in SDI mode.
Protected Attributes
KviMainWindow * m_pFrm
The frame where this KviMdiManager belongs to.
KviTalPopupMenu * m_pTileMethodPopup
Holds the tiling popup.
KviTalPopupMenu * m_pWindowPopup
Holds the specialized window popup.
Private Member Functions
void ensureNoMaximized ()
Make sure that no KviMdiChild is maximized.
void tileAllInternal (int maxWnds, bool bHorizontal)
The internal member which provides the tiling methods.
Private Attributes
bool m_bInSDIMode
Friends
class KviMdiChild
Detailed Description
Handles all MDI windows.
This MDI-manager is based on QMdiArea of Qt 4. It handles all docked windows and does their tiling. Basicly all windows are managed by the KviMainWindow, which also gives the order to the MDI-manager to dock or undock a window. What does that mean? All windows in KVIrc are of the type QWidget which can be standalone windows. These are packed into a QMdiSubWindow and added to the MDI-manager. So the KviMdiManager gets a KviMdiChild which will be set as main widget of our QMdiSubWindow. When it'll be undocked QMdiSubWindow will be removed and our KviWindow is "free" again.
Constructor & Destructor Documentation
KviMdiManager::KviMdiManager (QWidget * pParent, KviMainWindow * pFrm, const char * pcName)
Constructs the Mdi manager object.
Parameters:
pParent The parent widget
pFrm The frame container
pcName The name of the manager
Returns:
KviMdiManager
References connect(), fillWindowPopup(), KVI_OPTION_BOOL, KviOption_boolMdiManagerInSdiMode, m_bInSDIMode, m_pFrm, m_pTileMethodPopup, m_pWindowPopup, menuActivated(), slotSubWindowActivated(), and tileMethodMenuActivated().
KviMdiManager::~KviMdiManager ()
Destroys the Mdi manager object.
Member Function Documentation
void KviMdiManager::cascadeMaximized () [slot]
References i, KviMdiChild::Minimized, and KviMdiChild::state().
Referenced by fillWindowPopup().
void KviMdiManager::cascadeWindows () [slot]
Referenced by fillWindowPopup().
void KviMdiManager::destroyChild (KviMdiChild * lpC)
Remove and delete the subwindow.
Parameters:
lpC The KviMdiChild which will be destroyed.
Returns:
void
References KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, m_bInSDIMode, and tile().
Referenced by KviMainWindow::closeWindow(), and KviMainWindow::undockWindow().
void KviMdiManager::ensureNoMaximized () [private]
Make sure that no KviMdiChild is maximized.
Returns:
void
Goes trough all KviMdiChild objects and checks for maximized mode and restores that windows
References i, KviMdiChild::Maximized, KviMdiChild::restore(), and KviMdiChild::state().
Referenced by expandHorizontal(), expandVertical(), and tileAllInternal().
bool KviMdiManager::eventFilter (QObject * obj, QEvent * event)
Filters out some events: (de)activation events, window switching.
Returns:
bool
References g_pMainWindow, m_bInSDIMode, KviMainWindow::switchToNextWindow(), and KviMainWindow::switchToPrevWindow().
void KviMdiManager::expandHorizontal () [slot]
References ensureNoMaximized(), i, KviMdiChild::Minimized, and KviMdiChild::state().
Referenced by fillWindowPopup().
void KviMdiManager::expandVertical () [slot]
References ensureNoMaximized(), i, KviMdiChild::Minimized, and KviMdiChild::state().
Referenced by fillWindowPopup().
void KviMdiManager::fillWindowPopup () [protected, slot]
References __tr2qs, KviIconManager::AutoTileWindows, cascadeMaximized(), cascadeWindows(), KviIconManager::CascadeWindows, KviTalPopupMenu::clear(), expandHorizontal(), expandVertical(), g_pIconManager, KviIconManager::getSmallIcon(), i, KviMdiChild::icon(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KVI_NUM_TILE_METHODS, KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_TILE_METHOD_ANODINE, KVI_TILE_METHOD_PRAGMA4HOR, KVI_TILE_METHOD_PRAGMA4VER, KVI_TILE_METHOD_PRAGMA6HOR, KVI_TILE_METHOD_PRAGMA6VER, KVI_TILE_METHOD_PRAGMA9HOR, KVI_TILE_METHOD_PRAGMA9VER, KviOption_boolAutoTileWindows, KviOption_uintTileMethod, m_pTileMethodPopup, m_pWindowPopup, KviIconManager::MaxHorizontal, KviIconManager::MaxVertical, KviIconManager::Minimize, minimizeAll(), KviMdiChild::Minimized, KviIconManager::Restore, restoreAll(), KviTalPopupMenu::setItemChecked(), KviTalPopupMenu::setItemParameter(), KviMdiChild::state(), tile(), KviIconManager::TileWindows, and toggleAutoTile().
Referenced by KviMdiManager().
void KviMdiManager::focusPreviousTopChild (KviMdiChild * pExcludeThis = NULL)
Move the focus the the previous active window.
Returns:
void
References isInSDIMode(), KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, KviMdiChild::maximize(), KviMdiChild::Minimized, NULL, KviMdiChild::state(), and tile().
Referenced by hideChild(), KviMdiChild::windowStateChangedEvent(), and KviMdiChild::~KviMdiChild().
int KviMdiManager::getVisibleChildCount ()
Get all visible subwindows.
Returns:
int
References i, and l.
Referenced by tileAllInternal().
void KviMdiManager::hideChild (KviMdiChild * lpC)
Hides the specified child and focuses some other child.
Parameters:
lpC The KviMdiChild which will be hidden.
Returns:
void
References focusPreviousTopChild().
Referenced by KviMainWindow::closeWindow().
bool KviMdiManager::isInSDIMode () [inline]
Check if we are in SDI mode.
Returns:
bool
Referenced by focusPreviousTopChild(), and KviMainWindow::~KviMainWindow().
void KviMdiManager::manageChild (KviMdiChild * lpC, bool bCascade = true, QRect * setGeom = 0)
Add an KviMdiChild to the area.
Parameters:
lpC The KviMdiChild
bCascade Cascade window or not.
setGeom Sets the windows geometry before shown
Returns:
void
References KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, m_bInSDIMode, and tile().
Referenced by KviMainWindow::dockWindow().
void KviMdiManager::menuActivated (int id) [protected, slot]
References KviMdiChild::Minimized, KviMdiChild::restore(), setTopChild(), and KviMdiChild::state().
Referenced by KviMdiManager().
void KviMdiManager::minimizeAll () [slot]
References i, KviMdiChild::minimize(), KviMdiChild::Minimized, and KviMdiChild::state().
Referenced by fillWindowPopup().
void KviMdiManager::paintEvent (QPaintEvent * e) [protected, virtual]
Repaints the transparent backgrounds if activated.
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorMdiBackground, KviOption_pixmapMdiBackground, KviOption_uintGlobalTransparencyParentFadeFactor, p, scrollBarsOffset(), and KviApplication::supportsCompositing().
void KviMdiManager::restoreAll () [slot]
References i, KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, m_bInSDIMode, KviMdiChild::Minimized, KviMdiChild::restore(), KviMdiChild::state(), and tile().
Referenced by fillWindowPopup().
QPoint KviMdiManager::scrollBarsOffset () [inline]
Returns the current scrollbar offsets.
Returns:
QPoint
Referenced by UrlDialogTreeWidget::paintEvent(), KviIOGraphWindow::paintEvent(), FileTransferWidget::paintEvent(), KviUserListViewArea::paintEvent(), KviThemedTreeWidget::paintEvent(), KviThemedLineEdit::paintEvent(), KviThemedLabel::paintEvent(), KviThemedComboBox::paintEvent(), paintEvent(), KviIrcView::paintEvent(), KviToolBarGraphicalApplet::paintEvent(), and KviInputEditor::paintEvent().
void KviMdiManager::setIsInSDIMode (bool bMode) [protected]
Sets if we are in SDI mode.
References KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, m_bInSDIMode, and tile().
Referenced by KviMdiChild::windowStateChangedEvent().
void KviMdiManager::setTopChild (KviMdiChild * lpC)
Bring the KviMdiChild to the foreground.
Parameters:
lpC The KviMdiChild
Returns:
void
Referenced by KviMdiChild::activate(), menuActivated(), and showAndActivate().
void KviMdiManager::showAndActivate (KviMdiChild * lpC)
Show the KviMdiChild and bring it to the front.
Parameters:
lpC The KviMdiChild which will be shown.
Returns:
void
References KviMdiChild::activate(), KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, m_bInSDIMode, setTopChild(), and tile().
Referenced by KviMainWindow::addWindow(), and KviMainWindow::setActiveWindow().
void KviMdiManager::slotSubWindowActivated (QMdiSubWindow * pMdiChild) [protected, slot]
References KviMainWindow::childWindowActivated(), and g_pMainWindow.
Referenced by KviMdiManager().
void KviMdiManager::tile () [slot]
References KVI_OPTION_UINT, KVI_TILE_METHOD_ANODINE, KVI_TILE_METHOD_PRAGMA4HOR, KVI_TILE_METHOD_PRAGMA4VER, KVI_TILE_METHOD_PRAGMA6HOR, KVI_TILE_METHOD_PRAGMA6VER, KVI_TILE_METHOD_PRAGMA9HOR, KVI_TILE_METHOD_PRAGMA9VER, KviOption_uintTileMethod, tileAllInternal(), and tileAnodine().
Referenced by destroyChild(), fillWindowPopup(), focusPreviousTopChild(), manageChild(), restoreAll(), setIsInSDIMode(), showAndActivate(), tileMethodMenuActivated(), and toggleAutoTile().
void KviMdiManager::tileAllInternal (int maxWnds, bool bHorizontal) [private]
The internal member which provides the tiling methods.
Parameters:
maxWnds The maximum number of windows
bHorizontal If the windows will be tiled horizontal or vertical
Returns:
void
References ensureNoMaximized(), g_pApp, getVisibleChildCount(), i, KVI_MDICHILD_MIN_HEIGHT, KVI_MDICHILD_MIN_WIDTH, KviApplication::kviClosingDown(), KviMdiChild::Minimized, KviMdiChild::state(), and topChild().
Referenced by tile().
void KviMdiManager::tileAnodine () [slot]
Referenced by tile().
void KviMdiManager::tileMethodMenuActivated (int id) [protected, slot]
References KviTalPopupMenu::itemParameter(), KVI_NUM_TILE_METHODS, KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_TILE_METHOD_PRAGMA9VER, KviOption_boolAutoTileWindows, KviOption_uintTileMethod, m_pTileMethodPopup, and tile().
Referenced by KviMdiManager().
void KviMdiManager::toggleAutoTile () [slot]
References KVI_OPTION_BOOL, KviOption_boolAutoTileWindows, and tile().
Referenced by fillWindowPopup().
KviMdiChild * KviMdiManager::topChild ()
Get the currently active window.
Returns:
KviMdiChild *
Referenced by KviMdiChild::activate(), and tileAllInternal().
KviTalPopupMenu* KviMdiManager::windowPopup () [inline]
Returns the window popup.
Returns:
KviTalPopupMenu *
Referenced by KviMenuBar::KviMenuBar().
Friends And Related Function Documentation
friend class KviMdiChild [friend]
Member Data Documentation
bool KviMdiManager::m_bInSDIMode [private]
Referenced by destroyChild(), eventFilter(), KviMdiManager(), manageChild(), restoreAll(), setIsInSDIMode(), and showAndActivate().
KviMainWindow* KviMdiManager::m_pFrm [protected]
The frame where this KviMdiManager belongs to.
Referenced by KviMdiManager().
KviTalPopupMenu* KviMdiManager::m_pTileMethodPopup [protected]
Holds the tiling popup.
Referenced by fillWindowPopup(), KviMdiManager(), and tileMethodMenuActivated().
KviTalPopupMenu* KviMdiManager::m_pWindowPopup [protected]
Holds the specialized window popup.
Referenced by fillWindowPopup(), and KviMdiManager().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviMdiManager.h
src/kvirc/ui/KviMdiManager.cpp