KVIrc: KvsObject_lineEdit Class Reference
KvsObject_lineEdit Class Reference
#include <KvsObject_lineEdit.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void slotlostFocus ()
void slotreturnPressed ()
void slottextChanged (const QString &)
Protected Member Functions
bool clear (KviKvsObjectFunctionCall *c)
bool copy (KviKvsObjectFunctionCall *c)
bool cursorPosition (KviKvsObjectFunctionCall *c)
bool cut (KviKvsObjectFunctionCall *c)
bool disableCompleter (KviKvsObjectFunctionCall *c)
bool dragAndDrop (KviKvsObjectFunctionCall *c)
bool echoMode (KviKvsObjectFunctionCall *c)
bool enableCompleter (KviKvsObjectFunctionCall *c)
bool frame (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool lostFocusEvent (KviKvsObjectFunctionCall *c)
bool maxLength (KviKvsObjectFunctionCall *c)
bool paste (KviKvsObjectFunctionCall *c)
bool returnPressedEvent (KviKvsObjectFunctionCall *c)
bool selectAll (KviKvsObjectFunctionCall *c)
bool setCompleter (KviKvsObjectFunctionCall *c)
bool setCursorPosition (KviKvsObjectFunctionCall *c)
bool setEchoMode (KviKvsObjectFunctionCall *c)
bool setFrame (KviKvsObjectFunctionCall *c)
bool setInputMask (KviKvsObjectFunctionCall *c)
bool setInputValidator (KviKvsObjectFunctionCall *c)
bool setMaxLength (KviKvsObjectFunctionCall *c)
bool setReadOnly (KviKvsObjectFunctionCall *c)
bool setSelection (KviKvsObjectFunctionCall *c)
bool setText (KviKvsObjectFunctionCall *c)
bool text (KviKvsObjectFunctionCall *c)
bool textChangedEvent (KviKvsObjectFunctionCall *c)
bool unsetCompleter (KviKvsObjectFunctionCall *c)
Protected Attributes
QCompleter * m_pCompleter
Member Function Documentation
bool KvsObject_lineEdit::clear (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::copy (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::cursorPosition (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::cut (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::disableCompleter (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::dragAndDrop (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::echoMode (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::enableCompleter (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::frame (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_lineEdit::lostFocusEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::maxLength (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::paste (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::returnPressedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::selectAll (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setCompleter (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setCursorPosition (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setEchoMode (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setFrame (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setInputMask (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setInputValidator (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setMaxLength (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setReadOnly (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setSelection (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::setText (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_lineEdit::slotlostFocus () [protected, slot]
References KviKvsObject::callFunction().
void KvsObject_lineEdit::slotreturnPressed () [protected, slot]
References KviKvsObject::callFunction().
void KvsObject_lineEdit::slottextChanged (const QString & text) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_lineEdit::text (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::textChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_lineEdit::unsetCompleter (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_lineEdit::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
Member Data Documentation
QCompleter* KvsObject_lineEdit::m_pCompleter [protected]
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_lineEdit.h
src/modules/objects/KvsObject_lineEdit.cpp