KVIrc: KviKvsReport Class Reference
KviKvsReport Class Reference
#include <KviKvsReport.h>
Public Types
enum Type { RunTimeError, RunTimeWarning, ParserError, ParserWarning }
Public Member Functions
KviPointerList< QString > * callStack ()
KviPointerList< QString > * codeListing ()
const QString & context ()
KviKvsReport (Type t, const QString &szContext, const QString &szMessage, const QString &szLocation, KviWindow *pWindow)
const QString & location ()
const QString & message ()
void setCallStack (KviPointerList< QString > *pStack)
void setCodeListing (KviPointerList< QString > *pListing)
void setContext (const QString &szContext)
void setLocation (const QString &szLocation)
void setMessage (const QString &szMessage)
Type type () const
KviWindow * window ()
~KviKvsReport ()
Static Public Member Functions
static void findLineAndCol (const QChar *pBegin, const QChar *pPoint, int &iLine, int &iCol)
static void findLineColAndListing (const QChar *pBegin, const QChar *pPoint, int &iLine, int &iCol, KviPointerList< QString > *pListing)
static void report (KviKvsReport *r, KviWindow *pOutput)
Protected Attributes
Type m_eType
KviPointerList< QString > * m_pCallStack
KviPointerList< QString > * m_pCodeListing
KviWindow * m_pWindow
QString m_szContext
QString m_szLocation
QString m_szMessage
Member Enumeration Documentation
enum KviKvsReport::Type
Enumerator:
RunTimeError
RunTimeWarning
ParserError
ParserWarning
Constructor & Destructor Documentation
KviKvsReport::KviKvsReport (Type t, const QString & szContext, const QString & szMessage, const QString & szLocation, KviWindow * pWindow)
References m_pCallStack, and m_pCodeListing.
KviKvsReport::~KviKvsReport ()
References m_pCallStack, and m_pCodeListing.
Member Function Documentation
KviPointerList<QString>* KviKvsReport::callStack () [inline]
Referenced by report().
KviPointerList<QString>* KviKvsReport::codeListing () [inline]
Referenced by report().
const QString& KviKvsReport::context () [inline]
Referenced by report().
void KviKvsReport::findLineAndCol (const QChar * pBegin, const QChar * pPoint, int & iLine, int & iCol) [static]
Referenced by KviKvsRunTimeContext::report().
void KviKvsReport::findLineColAndListing (const QChar * pBegin, const QChar * pPoint, int & iLine, int & iCol, KviPointerList< QString > * pListing) [static]
References KviPointerList< T >::append(), and KviControlCodes::Bold.
Referenced by KviKvsParser::report(), and KviKvsRunTimeContext::report().
const QString& KviKvsReport::location () [inline]
Referenced by report().
const QString& KviKvsReport::message () [inline]
Referenced by report().
void KviKvsReport::report (KviKvsReport * r, KviWindow * pOutput) [static]
References __tr2qs_ctx(), KviControlCodes::Bold, callStack(), codeListing(), context(), KviPointerList< T >::first(), g_pApp, KviDebugWindow::getInstance(), KviDebugWindow::instance(), KVI_OPTION_BOOL, KVI_OUT_PARSERERROR, KVI_OUT_PARSERWARNING, KviOption_boolScriptErrorsToDebugWindow, l, location(), message(), KviPointerList< T >::next(), KviWindow::numericId(), KviWindow::output(), KviWindow::outputNoFmt(), ParserError, ParserWarning, RunTimeError, RunTimeWarning, s, type(), window(), KviApplication::windowExists(), and KviWindow::windowName().
void KviKvsReport::setCallStack (KviPointerList< QString > * pStack) [inline]
Referenced by KviKvsRunTimeContext::report().
void KviKvsReport::setCodeListing (KviPointerList< QString > * pListing) [inline]
Referenced by KviKvsParser::report(), and KviKvsRunTimeContext::report().
void KviKvsReport::setContext (const QString & szContext) [inline]
void KviKvsReport::setLocation (const QString & szLocation) [inline]
void KviKvsReport::setMessage (const QString & szMessage) [inline]
Type KviKvsReport::type () const [inline]
Referenced by report().
KviWindow* KviKvsReport::window () [inline]
Referenced by report().
Member Data Documentation
Type KviKvsReport::m_eType [protected]
KviPointerList<QString>* KviKvsReport::m_pCallStack [protected]
Referenced by KviKvsReport(), and ~KviKvsReport().
KviPointerList<QString>* KviKvsReport::m_pCodeListing [protected]
Referenced by KviKvsReport(), and ~KviKvsReport().
KviWindow* KviKvsReport::m_pWindow [protected]
QString KviKvsReport::m_szContext [protected]
QString KviKvsReport::m_szLocation [protected]
QString KviKvsReport::m_szMessage [protected]
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsReport.h
src/kvirc/kvs/KviKvsReport.cpp