KVIrc: KviKvsEventHandler Class Reference
KviKvsEventHandler Class Reference
#include <KviKvsEventHandler.h>
Public Types
enum Type { Script, Module }
Public Member Functions
KviKvsEventHandler (Type t)
Type type ()
virtual ~KviKvsEventHandler ()
Protected Attributes
Type m_type
Member Enumeration Documentation
enum KviKvsEventHandler::Type
Enumerator:
Script
Module
Constructor & Destructor Documentation
KviKvsEventHandler::KviKvsEventHandler (Type t)
KviKvsEventHandler::~KviKvsEventHandler () [virtual]
Member Function Documentation
Type KviKvsEventHandler::type () [inline]
Referenced by KviKvsEvent::clearScriptHandlers(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), KviKvsEventManager::removeAllModuleAppHandlers(), KviKvsEventManager::removeAllModuleRawHandlers(), KviKvsEventManager::removeAllScriptRawHandlers(), KviKvsEventManager::removeModuleAppHandler(), KviKvsEventManager::removeModuleRawHandler(), KviKvsEventManager::removeScriptAppHandler(), and KviKvsEventManager::removeScriptRawHandler().
Member Data Documentation
Type KviKvsEventHandler::m_type [protected]
The documentation for this class was generated from the following files:
src/kvirc/kvs/event/KviKvsEventHandler.h
src/kvirc/kvs/event/KviKvsEventHandler.cpp