KVIrc: KviStatusBarAwayIndicator Class Reference
KviStatusBarAwayIndicator Class Reference
#include <KviStatusBarApplet.h>
Public Member Functions
KviStatusBarAwayIndicator (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
virtual ~KviStatusBarAwayIndicator ()
Public Member Functions inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * descriptor ()
KviMainWindow * frame ()
int index () const
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Static Public Member Functions
static void selfRegister (KviStatusBar *pBar)
Protected Slots
void toggleContext ()
void updateDisplay ()
Protected Member Functions
virtual void fillContextPopup (QMenu *p)
virtual void loadState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void saveState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual QString tipText (const QPoint &)
Protected Attributes
bool m_bAwayOnAllContexts
Protected Attributes inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Constructor & Destructor Documentation
KviStatusBarAwayIndicator::KviStatusBarAwayIndicator (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
References KviMainWindow::activeConnectionAwayStateChanged(), KviMainWindow::activeContextChanged(), KviMainWindow::activeContextStateChanged(), connect(), KviStatusBar::frame(), g_pIconManager, KviIconManager::getSmallIcon(), m_bAwayOnAllContexts, KviIconManager::NotAway, and updateDisplay().
KviStatusBarAwayIndicator::~KviStatusBarAwayIndicator () virtual
Member Function Documentation
void KviStatusBarAwayIndicator::fillContextPopup (QMenu * p) protected virtual
Reimplemented from KviStatusBarApplet.
References __tr2qs, m_bAwayOnAllContexts, and toggleContext().
void KviStatusBarAwayIndicator::loadState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References KviCString::Format, m_bAwayOnAllContexts, KviCString::ptr(), and KviConfigurationFile::readBoolEntry().
void KviStatusBarAwayIndicator::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
References KviMainWindow::activeConnection(), c, KviIrcConnection::Connected, KviIrcConnection::console(), KviStatusBar::frame(), m_bAwayOnAllContexts, KviIrcUrl::run(), KviIrcConnection::state(), and KviStatusBarApplet::statusBar().
void KviStatusBarAwayIndicator::saveState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References KviCString::Format, m_bAwayOnAllContexts, KviCString::ptr(), and KviConfigurationFile::writeEntry().
void KviStatusBarAwayIndicator::selfRegister (KviStatusBar * pBar) static
References __tr2qs, KviIconManager::Away, CreateStatusBarAwayIndicator(), d, g_pIconManager, KviIconManager::getSmallIcon(), and KviStatusBar::registerAppletDescriptor().
Referenced by KviStatusBar::KviStatusBar().
QString KviStatusBarAwayIndicator::tipText (const QPoint &) protected virtual
Reimplemented from KviStatusBarApplet.
References __tr2qs, KviMainWindow::activeConnection(), KviIrcConnectionUserInfo::awayTime(), c, KviIrcConnection::Connected, KviTimeUtils::formatTimeInterval(), KviStatusBar::frame(), KviIrcConnectionUserInfo::isAway(), kvi_unixTime, KviTimeUtils::NoLeadingEmptyIntervals, KviIrcConnection::state(), KviStatusBarApplet::statusBar(), and KviIrcConnection::userInfo().
void KviStatusBarAwayIndicator::toggleContext () protected slot
References m_bAwayOnAllContexts.
Referenced by fillContextPopup().
void KviStatusBarAwayIndicator::updateDisplay () protected slot
References KviMainWindow::activeContext(), KviIconManager::Away, c, KviIrcContext::connection(), KviStatusBar::frame(), g_pIconManager, KviIconManager::getSmallIcon(), KviIrcConnectionUserInfo::isAway(), KviIrcContext::isConnected(), KviIconManager::NotAway, KviStatusBarApplet::statusBar(), and KviIrcConnection::userInfo().
Referenced by KviStatusBarAwayIndicator().
Member Data Documentation
bool KviStatusBarAwayIndicator::m_bAwayOnAllContexts protected
Referenced by fillContextPopup(), KviStatusBarAwayIndicator(), loadState(), mouseDoubleClickEvent(), saveState(), and toggleContext().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviStatusBarApplet.h
src/kvirc/ui/KviStatusBarApplet.cpp