KVIrc: RegisteredUserMaskDialog Class Reference
RegisteredUserMaskDialog Class Reference
#include <RegisteredUserEntryDialog.h>
Public Member Functions
RegisteredUserMaskDialog (QWidget *p, KviIrcMask *m)
~RegisteredUserMaskDialog ()
Protected Slots
void okClicked ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Protected Attributes
QLineEdit * m_pHostEdit
KviIrcMask * m_pMask
QLineEdit * m_pNickEdit
QLineEdit * m_pUserEdit
Constructor & Destructor Documentation
RegisteredUserMaskDialog::RegisteredUserMaskDialog (QWidget * p, KviIrcMask * m)
References __tr2qs_ctx(), connect(), g, KviIrcMask::host(), l, m, m_pHostEdit, m_pMask, m_pNickEdit, m_pUserEdit, KviIrcMask::nick(), okClicked(), KviTalHBox::setSpacing(), and KviIrcMask::user().
RegisteredUserMaskDialog::~RegisteredUserMaskDialog ()
Member Function Documentation
void RegisteredUserMaskDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void RegisteredUserMaskDialog::okClicked () [protected, slot]
References KviCString::isEmpty(), m_pHostEdit, m_pMask, m_pNickEdit, m_pUserEdit, KviCString::ptr(), KviIrcMask::setHost(), KviIrcMask::setNick(), and KviIrcMask::setUsername().
Referenced by RegisteredUserMaskDialog().
Member Data Documentation
QLineEdit* RegisteredUserMaskDialog::m_pHostEdit [protected]
Referenced by okClicked(), and RegisteredUserMaskDialog().
KviIrcMask* RegisteredUserMaskDialog::m_pMask [protected]
Referenced by okClicked(), and RegisteredUserMaskDialog().
QLineEdit* RegisteredUserMaskDialog::m_pNickEdit [protected]
Referenced by okClicked(), and RegisteredUserMaskDialog().
QLineEdit* RegisteredUserMaskDialog::m_pUserEdit [protected]
Referenced by okClicked(), and RegisteredUserMaskDialog().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUserEntryDialog.h
src/modules/reguser/RegisteredUserEntryDialog.cpp