KVIrc: KviDns Class Reference
KviDns Class Reference
#include <kvi_dns.h>
Public Types
enum QueryType { IPv4, IPv6, Any }
enum State { Idle, Busy, Failure, Success }
Signals
void lookupDone (KviDns *)
Public Member Functions
int error ()
const QString & firstHostname ()
const QString & firstIpAddress ()
int hostnameCount ()
KviPointerList< QString > * hostnameList ()
int ipAddressCount ()
KviPointerList< QString > * ipAddressList ()
bool isRunning () const
KviDns ()
bool lookup (const QString &szQuery, QueryType type)
const QString & query ()
void * releaseAuxData ()
void setAuxData (void *pAuxData)
State state ()
~KviDns ()
Protected Member Functions
virtual bool event (QEvent *e)
Protected Attributes
void * m_pAuxData
KviDnsResult * m_pDnsResult
KviDnsThread * m_pSlaveThread
State m_state
Properties
bool blockingDelete
Private Member Functions
KviDnsResult * result ()
Member Enumeration Documentation
enum KviDns::QueryType
Enumerator:
IPv4
IPv6
Any
enum KviDns::State
Enumerator:
Idle
Busy
Failure
Success
Constructor & Destructor Documentation
KviDns::KviDns ()
References Idle, m_pAuxData, m_pDnsResult, m_pSlaveThread, and m_state.
Referenced by KviHttpRequest::startDnsLookup().
KviDns::~KviDns ()
References KviThreadManager::killPendingEvents(), m_pAuxData, m_pDnsResult, and m_pSlaveThread.
Member Function Documentation
int KviDns::error ()
References KviDnsResult::error(), KviError_dnsQueryFailed, and m_pDnsResult.
Referenced by KviHttpRequest::dnsLookupDone(), KviKvsDnsManager::dnsLookupTerminated(), KviIrcConnection::hostNameLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
bool KviDns::event (QEvent * e) [protected, virtual]
References KviDnsResult::error(), Failure, KVI_DNS_THREAD_EVENT_DATA, KVI_THREAD_EVENT, KviError_success, lookupDone(), m_pDnsResult, m_state, and Success.
const QString & KviDns::firstHostname ()
References KviQString::Empty, KviPointerList< T >::first(), KviDnsResult::hostnameList(), and result().
Referenced by KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
const QString & KviDns::firstIpAddress ()
References KviQString::Empty, KviPointerList< T >::first(), KviDnsResult::ipAddressList(), and result().
Referenced by KviHttpRequest::dnsLookupDone(), KviIrcConnection::hostNameLookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
int KviDns::hostnameCount ()
References KviPointerList< T >::count(), KviDnsResult::hostnameList(), and result().
Referenced by KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
KviPointerList< QString > * KviDns::hostnameList ()
References KviDnsResult::hostnameList(), and result().
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
int KviDns::ipAddressCount ()
References KviPointerList< T >::count(), KviDnsResult::ipAddressList(), and result().
Referenced by KviIrcConnectionTargetResolver::serverLookupTerminated().
KviPointerList< QString > * KviDns::ipAddressList ()
References KviDnsResult::ipAddressList(), and result().
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
bool KviDns::isRunning () const
References Busy, and m_state.
Referenced by KviIrcConnectionTargetResolver::cleanup(), KviIrcConnection::~KviIrcConnection(), and KviKvsDnsObject::~KviKvsDnsObject().
bool KviDns::lookup (const QString & szQuery, QueryType type)
References Busy, Failure, m_pSlaveThread, m_state, KviDnsThread::setQuery(), KviThread::start(), and KviQString::trimmed().
Referenced by KviKvsAsyncDnsOperation::KviKvsAsyncDnsOperation(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviHttpRequest::startDnsLookup(), and KviIrcConnection::userInfoReceived().
void KviDns::lookupDone (KviDns *) [signal]
Referenced by event(), and KviHttpRequest::startDnsLookup().
const QString & KviDns::query ()
References KviDnsResult::query(), and result().
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), and KviDnsThread::setQuery().
void* KviDns::releaseAuxData () [inline]
KviDnsResult * KviDns::result () [private]
References m_pDnsResult.
Referenced by firstHostname(), firstIpAddress(), hostnameCount(), hostnameList(), ipAddressCount(), ipAddressList(), and query().
void KviDns::setAuxData (void * pAuxData) [inline]
State KviDns::state () [inline]
Referenced by KviHttpRequest::dnsLookupDone(), KviKvsDnsManager::dnsLookupTerminated(), KviIrcConnection::hostNameLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
Member Data Documentation
void* KviDns::m_pAuxData [protected]
Referenced by KviDns(), and ~KviDns().
KviDnsResult* KviDns::m_pDnsResult [protected]
Referenced by error(), event(), KviDns(), result(), and ~KviDns().
KviDnsThread* KviDns::m_pSlaveThread [protected]
Referenced by KviDns(), lookup(), and ~KviDns().
State KviDns::m_state [protected]
Referenced by event(), isRunning(), KviDns(), and lookup().
Property Documentation
bool KviDns::blockingDelete [read]
The documentation for this class was generated from the following files:
src/kvilib/net/kvi_dns.h
src/kvilib/net/kvi_dns.cpp