KVIrc: KviKvsTreeNodeInstruction Class Reference
KviKvsTreeNodeInstruction Class Reference
Treenode class to handle instructions.
#include <kvi_kvs_treenode_instruction.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)=0
This is the main entry point to the tree visit.
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Detailed Description
Treenode class to handle instructions.
Constructor & Destructor Documentation
KviKvsTreeNodeInstruction::KviKvsTreeNodeInstruction (const QChar * pLocation) [inline]
Constructs the treenode instruction object.
Parameters:
pLocation The location char of the instruction
Returns:
KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction::~KviKvsTreeNodeInstruction () [inline]
Destroys the treenode instruction object.
Member Function Documentation
void KviKvsTreeNodeInstruction::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
Reimplemented in KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeCallbackCommand, KviKvsTreeNodeCommand, KviKvsTreeNodeCommandWithParameters, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeExpressionReturn, KviKvsTreeNodeInstructionBlock, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeModuleSimpleCommand, KviKvsTreeNodeOperation, KviKvsTreeNodeOperationAssignment, KviKvsTreeNodeOperationDecrement, KviKvsTreeNodeOperationIncrement, KviKvsTreeNodeOperationSelfAnd, KviKvsTreeNodeOperationSelfDivision, KviKvsTreeNodeOperationSelfModulus, KviKvsTreeNodeOperationSelfMultiplication, KviKvsTreeNodeOperationSelfOr, KviKvsTreeNodeOperationSelfShl, KviKvsTreeNodeOperationSelfShr, KviKvsTreeNodeOperationSelfSubtraction, KviKvsTreeNodeOperationSelfSum, KviKvsTreeNodeOperationSelfXor, KviKvsTreeNodeOperationStringAppend, KviKvsTreeNodeOperationArrayAppend, KviKvsTreeNodeOperationStringAppendWithComma, KviKvsTreeNodeOperationStringAppendWithSpace, KviKvsTreeNodeOperationStringTransliteration, KviKvsTreeNodeOperationStringSubstitution, KviKvsTreeNodeParameterReturn, KviKvsTreeNodeRebindingSwitch, KviKvsTreeNodeSimpleCommand, KviKvsTreeNodeSpecialCommand, KviKvsTreeNodeSpecialCommandBreak, KviKvsTreeNodeSpecialCommandClass, KviKvsTreeNodeSpecialCommandContinue, KviKvsTreeNodeSpecialCommandDefpopup, KviKvsTreeNodeSpecialCommandDo, KviKvsTreeNodeSpecialCommandFor, KviKvsTreeNodeSpecialCommandForeach, KviKvsTreeNodeSpecialCommandIf, KviKvsTreeNodeSpecialCommandSwitch, KviKvsTreeNodeSpecialCommandUnset, KviKvsTreeNodeSpecialCommandWhile, and KviKvsTreeNodeVoidFunctionCall.
void KviKvsTreeNodeInstruction::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
Reimplemented in KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeCallbackCommand, KviKvsTreeNodeCommand, KviKvsTreeNodeCommandWithParameters, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeExpressionReturn, KviKvsTreeNodeInstructionBlock, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeModuleSimpleCommand, KviKvsTreeNodeOperation, KviKvsTreeNodeOperationAssignment, KviKvsTreeNodeOperationDecrement, KviKvsTreeNodeOperationIncrement, KviKvsTreeNodeOperationSelfAnd, KviKvsTreeNodeOperationSelfDivision, KviKvsTreeNodeOperationSelfModulus, KviKvsTreeNodeOperationSelfMultiplication, KviKvsTreeNodeOperationSelfOr, KviKvsTreeNodeOperationSelfShl, KviKvsTreeNodeOperationSelfShr, KviKvsTreeNodeOperationSelfSubtraction, KviKvsTreeNodeOperationSelfSum, KviKvsTreeNodeOperationSelfXor, KviKvsTreeNodeOperationStringAppend, KviKvsTreeNodeOperationArrayAppend, KviKvsTreeNodeOperationStringAppendWithComma, KviKvsTreeNodeOperationStringAppendWithSpace, KviKvsTreeNodeOperationStringTransliteration, KviKvsTreeNodeOperationStringSubstitution, KviKvsTreeNodeParameterReturn, KviKvsTreeNodeRebindingSwitch, KviKvsTreeNodeSimpleCommand, KviKvsTreeNodeSpecialCommand, KviKvsTreeNodeSpecialCommandBreak, KviKvsTreeNodeSpecialCommandClass, KviKvsTreeNodeSpecialCommandContinue, KviKvsTreeNodeSpecialCommandDefpopup, KviKvsTreeNodeSpecialCommandDo, KviKvsTreeNodeSpecialCommandFor, KviKvsTreeNodeSpecialCommandForeach, KviKvsTreeNodeSpecialCommandIf, KviKvsTreeNodeSpecialCommandSwitch, KviKvsTreeNodeSpecialCommandUnset, KviKvsTreeNodeSpecialCommandWhile, and KviKvsTreeNodeVoidFunctionCall.
Referenced by KviKvsTreeNodeSpecialCommandSwitchLabelDefault::dump(), KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::dump(), KviKvsTreeNodeSpecialCommandSwitchLabelMatch::dump(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::dump(), KviKvsTreeNodeSpecialCommandForeach::dump(), KviKvsTreeNodeSpecialCommandFor::dump(), and KviKvsScript::dump().
virtual bool KviKvsTreeNodeInstruction::execute (KviKvsRunTimeContext * c) [pure virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implemented in KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeExpressionReturn, KviKvsTreeNodeInstructionBlock, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeModuleSimpleCommand, KviKvsTreeNodeOperationAssignment, KviKvsTreeNodeOperationDecrement, KviKvsTreeNodeOperationIncrement, KviKvsTreeNodeOperationSelfAnd, KviKvsTreeNodeOperationSelfDivision, KviKvsTreeNodeOperationSelfModulus, KviKvsTreeNodeOperationSelfMultiplication, KviKvsTreeNodeOperationSelfOr, KviKvsTreeNodeOperationSelfShl, KviKvsTreeNodeOperationSelfShr, KviKvsTreeNodeOperationSelfSubtraction, KviKvsTreeNodeOperationSelfSum, KviKvsTreeNodeOperationSelfXor, KviKvsTreeNodeOperationStringAppend, KviKvsTreeNodeOperationArrayAppend, KviKvsTreeNodeOperationStringAppendWithComma, KviKvsTreeNodeOperationStringAppendWithSpace, KviKvsTreeNodeOperationStringTransliteration, KviKvsTreeNodeOperationStringSubstitution, KviKvsTreeNodeParameterReturn, KviKvsTreeNodeRebindingSwitch, KviKvsTreeNodeSpecialCommandBreak, KviKvsTreeNodeSpecialCommandClass, KviKvsTreeNodeSpecialCommandContinue, KviKvsTreeNodeSpecialCommandDefpopup, KviKvsTreeNodeSpecialCommandDo, KviKvsTreeNodeSpecialCommandFor, KviKvsTreeNodeSpecialCommandForeach, KviKvsTreeNodeSpecialCommandIf, KviKvsTreeNodeSpecialCommandSwitch, KviKvsTreeNodeSpecialCommandUnset, KviKvsTreeNodeSpecialCommandWhile, and KviKvsTreeNodeVoidFunctionCall.
Referenced by KviKvsTreeNodeCommandEvaluation::evaluateReadOnly(), KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelDefault::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelMatch::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeSpecialCommandIf::execute(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), KviKvsTreeNodeSpecialCommandDo::execute(), KviKvsTreeNodeRebindingSwitch::execute(), and KviKvsScript::executeInternal().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_instruction.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_instruction.cpp