KVIrc: KviAnimatedPixmap Class Reference
KviAnimatedPixmap Class Reference
#include <kvi_animatedpixmap.h>
Signals
void frameChanged ()
Public Member Functions
uint activeFrameNumber ()
uint framesCount ()
bool isStarted ()
bool isValid ()
KviAnimatedPixmap (KviAnimatedPixmap *source)
KviAnimatedPixmap (QString fileName)
void nextFrame (bool bScheduleNext)
QPixmap * pixmap ()
void resize (QSize newSize, Qt::AspectRatioMode ratioMode)
const QSize & size ()
void start ()
void stop ()
virtual ~KviAnimatedPixmap ()
Protected Attributes
bool m_bStarted
KviAnimatedPixmapCache::Data * m_lFrames
QString m_szFileName
uint m_uCurrentFrameNumber
Detailed Description
This class should not be here, because we already have QMovie with the same functionality.
But QMovie is really stupid, bacause: 1) It does not support infinitive animation. It relies on image metadata to determine loop count. So most of pics will be played only once.
2) It dublicates QPixmap while we calls currentFrame(), that's a very big overload for us.
3) If we try to scale QMovie by using built-in scale mechanism, it will manually scale each frame each time, we will call currentFrame(). So if we plan to play movie 10,100,1000 times, it will scale image 10,100,1000 times too:(
4) KviAnimatedPixmap uses internal cache mechanism with KviAnimatedPixmapCache class. It's managed inside KviAnimatedPixmap and KviAnimatedPixmapCache. No othet actions needed to perform caching.
So... Here is my workaround. It's working in this way: You should create new pixmap with constructor KviAnimatedPixmap(QString fileName). It will automagically look at cache and use it, if possible.
KviAnimatedPixmap stores animation as a set of QPixmap's, and delays. when started (see start()) it emits frameChanged() events at the frame change.
You should use pixmap() methd to access the current frame.
This class owns all pixmaps. Do not store links to them.
Constructor & Destructor Documentation
KviAnimatedPixmap::KviAnimatedPixmap (QString fileName)
References KviTheme::load(), m_bStarted, m_lFrames, m_uCurrentFrameNumber, and start().
KviAnimatedPixmap::~KviAnimatedPixmap () [virtual]
References KviAnimatedPixmapCache::free(), m_lFrames, and KviAnimatedPixmapCache::notifyDelete().
KviAnimatedPixmap::KviAnimatedPixmap (KviAnimatedPixmap * source)
References framesCount(), isStarted(), m_lFrames, m_uCurrentFrameNumber, KviAnimatedPixmapCache::Data::refs, and KviAnimatedPixmapCache::scheduleFrameChange().
Member Function Documentation
uint KviAnimatedPixmap::activeFrameNumber () [inline]
void KviAnimatedPixmap::frameChanged () [signal]
Referenced by nextFrame().
uint KviAnimatedPixmap::framesCount () [inline]
Referenced by KviAnimatedPixmap(), and start().
bool KviAnimatedPixmap::isStarted () [inline]
Referenced by KviAnimatedPixmap(), start(), and stop().
bool KviAnimatedPixmap::isValid () [inline]
void KviAnimatedPixmap::nextFrame (bool bScheduleNext) [virtual]
Implements KviAnimatedPixmapInterface.
References frameChanged(), m_bStarted, m_lFrames, m_uCurrentFrameNumber, and KviAnimatedPixmapCache::scheduleFrameChange().
QPixmap* KviAnimatedPixmap::pixmap () [inline]
References KviAnimatedPixmapCache::dummyPixmap().
Referenced by KviUserListView::animatedAvatarUpdated(), KviUserListViewArea::paintEvent(), and KviIrcView::paintEvent().
void KviAnimatedPixmap::resize (QSize newSize, Qt::AspectRatioMode ratioMode)
References m_lFrames, and size().
Referenced by KviAvatar::forSize(), and KviAvatar::KviAvatar().
const QSize& KviAnimatedPixmap::size () [inline]
Referenced by KviAvatar::KviAvatar(), KviUserListEntry::recalcSize(), and resize().
void KviAnimatedPixmap::start ()
References framesCount(), isStarted(), m_bStarted, m_lFrames, m_uCurrentFrameNumber, and KviAnimatedPixmapCache::scheduleFrameChange().
Referenced by KviUserListView::applyOptions(), KviAnimatedPixmap(), KviAvatar::KviAvatar(), KviTextIcon::KviTextIcon(), and KviUserListEntry::updateAvatarData().
void KviAnimatedPixmap::stop ()
References isStarted(), and m_bStarted.
Referenced by KviUserListView::applyOptions(), KviTextIcon::KviTextIcon(), and KviUserListEntry::updateAvatarData().
Member Data Documentation
bool KviAnimatedPixmap::m_bStarted [protected]
Referenced by KviAnimatedPixmap(), nextFrame(), start(), and stop().
KviAnimatedPixmapCache::Data* KviAnimatedPixmap::m_lFrames [protected]
Referenced by KviAnimatedPixmap(), nextFrame(), resize(), start(), and ~KviAnimatedPixmap().
QString KviAnimatedPixmap::m_szFileName [protected]
uint KviAnimatedPixmap::m_uCurrentFrameNumber [protected]
Referenced by KviAnimatedPixmap(), nextFrame(), and start().
The documentation for this class was generated from the following files:
src/kvilib/ext/kvi_animatedpixmap.h
src/kvilib/ext/kvi_animatedpixmap.cpp