KVIrc: TrayIcon Class Reference
TrayIcon Class Reference
#include <libkvitrayicon.h>
Public Member Functions
virtual void die ()
KviMainWindow * frame ()
virtual void refresh ()
TrayIcon (KviMainWindow *win)
void updateIcon ()
~TrayIcon ()
Protected Slots
void activatedSlot (QSystemTrayIcon::ActivationReason reason)
void doAway (bool)
void executeInternalCommand (bool)
void fillContextPopup ()
void flashingTimerShot ()
void toggleParentFrame ()
Protected Member Functions
virtual bool event (QEvent *e)
void grabActivityInfo ()
Protected Attributes
bool m_bFlashed
QPixmap m_CurrentPixmap
unsigned int m_iChannels
unsigned int m_iConsoles
unsigned int m_iOther
unsigned int m_iQueries
QAction * m_pAwayMenuId
KviTalPopupMenu * m_pAwayPopup
KviTalPopupMenu * m_pContextPopup
QTimer * m_pFlashingTimer
KviMainWindow * m_pFrm
KviDynamicToolTip * m_pTip
QLabel * m_pTitleLabel
QAction * m_pToggleFrame
Constructor & Destructor Documentation
TrayIcon::TrayIcon (KviMainWindow * win)
References __tr2qs, activatedSlot(), KviPointerList< T >::append(), KviIconManager::Away, connect(), executeInternalCommand(), fillContextPopup(), flashingTimerShot(), g_pDock1, g_pIconManager, g_pMainWindow, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KVI_INTERNALCOMMAND_ABOUT_ABOUTKVIRC, KVI_INTERNALCOMMAND_OPTIONS_DIALOG, KVI_INTERNALCOMMAND_TRAYICON_HIDE, KviIconManager::KVIrc, m_bFlashed, m_iChannels, m_iConsoles, m_iOther, m_iQueries, m_pAwayMenuId, m_pAwayPopup, m_pContextPopup, m_pFlashingTimer, m_pFrm, m_pTip, m_pTitleLabel, m_pToggleFrame, Normal, KviIconManager::Options, p, KviIconManager::QuitApp, KviIconManager::Raw, KviMainWindow::setDockExtension(), toggleParentFrame(), and KviIconManager::TrayIcon.
TrayIcon::~TrayIcon ()
References m_pAwayPopup, m_pContextPopup, m_pFlashingTimer, m_pFrm, m_pTip, m_pTitleLabel, KviPointerList< T >::removeRef(), and KviMainWindow::setDockExtension().
Member Function Documentation
void TrayIcon::activatedSlot (QSystemTrayIcon::ActivationReason reason) [protected, slot]
COMPILE_ON_MAC
COMPILE_ON_MAC
References KVI_OPTION_BOOL, KviOption_boolCloseInTray, KviOption_boolMinimizeInTray, m_pFrm, and toggleParentFrame().
Referenced by TrayIcon().
void TrayIcon::die () [virtual]
Reimplemented from KviDockExtension.
void TrayIcon::doAway (bool) [protected, slot]
References KviWindow::connection(), KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), KviIrcConnection::encodeText(), KviApplication::findConsole(), g_pApp, g_pGlobalWindowDict, KviIrcConnectionUserInfo::isAway(), KviConsoleWindow::isConnected(), KVI_OPTION_STRING, KviOption_stringAwayMessage, KviIrcConnection::sendFmtData(), and KviIrcConnection::userInfo().
Referenced by fillContextPopup().
bool TrayIcon::event (QEvent * e) [protected, virtual]
References __tr2qs_no_xgettext, first(), KviWindowListBase::firstItem(), idlemsgs, m_pFrm, m_pTip, KviWindowListBase::nextItem(), NIDLEMSGS, t, KviDynamicToolTip::tip(), and KviMainWindow::windowListWidget().
void TrayIcon::executeInternalCommand (bool) [protected, slot]
References KviMainWindow::executeInternalCommand(), and m_pFrm.
Referenced by TrayIcon().
void TrayIcon::fillContextPopup () [protected, slot]
References __tr2qs, KviTalPopupMenu::clear(), KviWindow::connection(), KviWindow::Console, KviIconManager::Console, KviConsoleWindow::context(), KviPointerHashTableIterator< Key, T >::current(), KviConsoleWindow::currentNetworkName(), doAway(), g_pApp, g_pGlobalWindowDict, g_pIconManager, KviIconManager::getSmallIcon(), KviIrcContext::id(), KviIrcConnectionUserInfo::isAway(), KviConsoleWindow::isConnected(), m_pAwayMenuId, m_pAwayPopup, m_pFrm, m_pToggleFrame, KviApplication::topmostConnectedConsole(), and KviIrcConnection::userInfo().
Referenced by TrayIcon().
void TrayIcon::flashingTimerShot () [protected, slot]
References m_bFlashed, and refresh().
Referenced by TrayIcon().
KviMainWindow* TrayIcon::frame () [inline]
References m_pFrm.
void TrayIcon::grabActivityInfo () [protected]
References KviWindow::Channel, KviWindow::Console, KviWindowListBase::firstItem(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolUseLevelBasedTrayNotification, KviOption_uintMinTrayHighLevelMessage, KviOption_uintMinTrayLowLevelMessage, m_iChannels, m_iConsoles, m_iOther, m_iQueries, m_pFrm, KviWindowListBase::nextItem(), KviWindow::Query, t, and KviMainWindow::windowListWidget().
Referenced by refresh().
void TrayIcon::refresh () [virtual]
Reimplemented from KviDockExtension.
References g_pDock1, g_pDock2, g_pDock3, g_pIconManager, KviIconManager::getSmallIcon(), grabActivityInfo(), ICON_SIZE, KVI_OPTION_BOOL, KviOption_boolEnableTrayIconFlashing, m_bFlashed, m_CurrentPixmap, m_iChannels, m_iConsoles, m_iOther, m_iQueries, m_pFlashingTimer, KviIconManager::Message, and updateIcon().
Referenced by flashingTimerShot().
void TrayIcon::toggleParentFrame () [protected, slot]
References KVI_OPTION_BOOL, KviOption_boolFrameIsMaximized, and m_pFrm.
Referenced by activatedSlot(), and TrayIcon().
void TrayIcon::updateIcon ()
References m_CurrentPixmap.
Referenced by refresh().
Member Data Documentation
bool TrayIcon::m_bFlashed [protected]
Referenced by flashingTimerShot(), refresh(), and TrayIcon().
QPixmap TrayIcon::m_CurrentPixmap [protected]
Referenced by refresh(), and updateIcon().
unsigned int TrayIcon::m_iChannels [protected]
Referenced by grabActivityInfo(), refresh(), and TrayIcon().
unsigned int TrayIcon::m_iConsoles [protected]
Referenced by grabActivityInfo(), refresh(), and TrayIcon().
unsigned int TrayIcon::m_iOther [protected]
Referenced by grabActivityInfo(), refresh(), and TrayIcon().
unsigned int TrayIcon::m_iQueries [protected]
Referenced by grabActivityInfo(), refresh(), and TrayIcon().
QAction* TrayIcon::m_pAwayMenuId [protected]
Referenced by fillContextPopup(), and TrayIcon().
KviTalPopupMenu* TrayIcon::m_pAwayPopup [protected]
Referenced by fillContextPopup(), TrayIcon(), and ~TrayIcon().
KviTalPopupMenu* TrayIcon::m_pContextPopup [protected]
Referenced by TrayIcon(), and ~TrayIcon().
QTimer* TrayIcon::m_pFlashingTimer [protected]
Referenced by refresh(), TrayIcon(), and ~TrayIcon().
KviMainWindow* TrayIcon::m_pFrm [protected]
Referenced by activatedSlot(), event(), executeInternalCommand(), fillContextPopup(), frame(), grabActivityInfo(), toggleParentFrame(), TrayIcon(), and ~TrayIcon().
KviDynamicToolTip* TrayIcon::m_pTip [protected]
Referenced by event(), TrayIcon(), and ~TrayIcon().
QLabel* TrayIcon::m_pTitleLabel [protected]
Referenced by TrayIcon(), and ~TrayIcon().
QAction* TrayIcon::m_pToggleFrame [protected]
Referenced by fillContextPopup(), and TrayIcon().
The documentation for this class was generated from the following files:
src/modules/trayicon/libkvitrayicon.h
src/modules/trayicon/libkvitrayicon.cpp