KVIrc: KvsObject_http Class Reference
KvsObject_http Class Reference
#include <KvsObject_http.h>
Protected Slots
void slotDataReadProgress (int done, int total)
void slotDataSendProgress (int done, int total)
void slotDone (bool error)
void slotReadyRead (const QHttpResponseHeader &r)
void slotRequestFinished (int id, bool error)
void slotRequestStarted (int id)
void slotResponseHeaderReceived (const QHttpResponseHeader &r)
void slotSslErrors (QList< QSslError >)
void slotStateChanged (int state)
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Protected Member Functions
bool functionAbort (KviKvsObjectFunctionCall *c)
bool functionCurrentId (KviKvsObjectFunctionCall *c)
bool functionDataReadProgressEvent (KviKvsObjectFunctionCall *c)
bool functionDataSendProgressEvent (KviKvsObjectFunctionCall *c)
bool functionDoneEvent (KviKvsObjectFunctionCall *c)
bool functionErrorString (KviKvsObjectFunctionCall *c)
bool functionFollowRedirect (KviKvsObjectFunctionCall *c)
bool functionGet (KviKvsObjectFunctionCall *c)
bool functionIgnoreSslErrors (KviKvsObjectFunctionCall *c)
bool functionPost (KviKvsObjectFunctionCall *c)
bool functionReadAll (KviKvsObjectFunctionCall *c)
bool functionReadyReadEvent (KviKvsObjectFunctionCall *c)
bool functionRequestFinishedEvent (KviKvsObjectFunctionCall *c)
bool functionRequestStartedEvent (KviKvsObjectFunctionCall *c)
bool functionResponseHeaderReceivedEvent (KviKvsObjectFunctionCall *c)
bool functionSetHost (KviKvsObjectFunctionCall *c)
bool functionSetProxy (KviKvsObjectFunctionCall *c)
bool functionSetUser (KviKvsObjectFunctionCall *c)
bool functionSslErrorsEvent (KviKvsObjectFunctionCall *c)
bool functionStateChangedEvent (KviKvsObjectFunctionCall *c)
void redirect (QString &file, const QHttpResponseHeader &r)
Protected Member Functions inherited from KviKvsObject
virtual bool eventFilter (QObject *o, QEvent *e)
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
QHash< int, QFile * > getDict
bool m_bAbort
bool m_bEnableForceRedirect
QHttp * m_pHttp
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Additional Inherited Members
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Member Function Documentation
bool KvsObject_http::functionAbort (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, and m_bAbort.
bool KvsObject_http::functionCurrentId (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setInteger().
bool KvsObject_http::functionDataReadProgressEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionDataSendProgressEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionDoneEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionErrorString (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setString().
bool KvsObject_http::functionFollowRedirect (KviKvsObjectFunctionCall * c) protected
References KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_bEnableForceRedirect.
bool KvsObject_http::functionGet (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), CHECK_INTERNAL_POINTER, getDict, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviKvsRunTimeCall::warning().
bool KvsObject_http::functionIgnoreSslErrors (KviKvsObjectFunctionCall * c) protected
bool KvsObject_http::functionPost (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, getDict, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setInteger().
bool KvsObject_http::functionReadAll (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setString().
bool KvsObject_http::functionReadyReadEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionRequestFinishedEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionRequestStartedEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionResponseHeaderReceivedEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionSetHost (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), CHECK_INTERNAL_POINTER, QHttp::ConnectionModeHttp, QHttp::ConnectionModeHttps, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and szHost.
bool KvsObject_http::functionSetProxy (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and szHost.
bool KvsObject_http::functionSetUser (KviKvsObjectFunctionCall * c) protected
References CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
bool KvsObject_http::functionSslErrorsEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
bool KvsObject_http::functionStateChangedEvent (KviKvsObjectFunctionCall * c) protected
References KviKvsObject::emitSignal(), and KviKvsRunTimeCall::params().
void KvsObject_http::redirect (QString & file, const QHttpResponseHeader & r) protected
References getDict, and QHttpHeader::value().
Referenced by slotRequestFinished().
void KvsObject_http::slotDataReadProgress (int done, int total) protected slot
References KviKvsVariantList::append(), and KviKvsObject::callFunction().
void KvsObject_http::slotDataSendProgress (int done, int total) protected slot
References KviKvsVariantList::append(), and KviKvsObject::callFunction().
void KvsObject_http::slotDone (bool error) protected slot
References KviKvsVariantList::append(), and KviKvsObject::callFunction().
void KvsObject_http::slotReadyRead (const QHttpResponseHeader & r) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), m_bAbort, QHttpResponseHeader::reasonPhrase(), and QHttpResponseHeader::statusCode().
void KvsObject_http::slotRequestFinished (int id, bool error) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), getDict, m_bAbort, m_bEnableForceRedirect, KviRuntimeInfo::name(), redirect(), and t().
void KvsObject_http::slotRequestStarted (int id) protected slot
References KviKvsVariantList::append(), and KviKvsObject::callFunction().
void KvsObject_http::slotResponseHeaderReceived (const QHttpResponseHeader & r) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), m_bAbort, QHttpResponseHeader::reasonPhrase(), and QHttpResponseHeader::statusCode().
void KvsObject_http::slotSslErrors (QList< QSslError > sslerrors) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), i, pArray, KviKvsArray::set(), and ssl_errors_tbl.
void KvsObject_http::slotStateChanged (int state) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), QHttp::Closing, QHttp::Connected, QHttp::Connecting, QHttp::HostLookup, QHttp::Reading, QHttp::Sending, and QHttp::Unconnected.
Member Data Documentation
QHash<int, QFile *> KvsObject_http::getDict protected
Referenced by functionGet(), functionPost(), redirect(), and slotRequestFinished().
bool KvsObject_http::m_bAbort protected
Referenced by functionAbort(), slotReadyRead(), slotRequestFinished(), and slotResponseHeaderReceived().
bool KvsObject_http::m_bEnableForceRedirect protected
Referenced by functionFollowRedirect(), and slotRequestFinished().
QHttp* KvsObject_http::m_pHttp protected
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_http.h
src/modules/objects/KvsObject_http.cpp