KVIrc: KviKvsTreeNodeHashElement Class Reference
KviKvsTreeNodeHashElement Class Reference
#include <KviKvsTreeNodeHashElement.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
KviKvsTreeNodeHashElement (const QChar *pLocation, KviKvsTreeNodeData *pSource, KviKvsTreeNodeData *pIndex)
~KviKvsTreeNodeHashElement ()
Public Member Functions inherited from KviKvsTreeNodeArrayOrHashElement
virtual bool canEvaluateToObjectReference ()
virtual bool isReadOnly ()
KviKvsTreeNodeArrayOrHashElement (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeArrayOrHashElement ()
Public Member Functions inherited from KviKvsTreeNodeIndirectData
virtual bool canEvaluateInObjectScope ()
KviKvsTreeNodeIndirectData (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeIndirectData ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool isFunctionCall ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeData * m_pKey
Protected Attributes inherited from KviKvsTreeNodeIndirectData
KviKvsTreeNodeData * m_pSource
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeHashElement::KviKvsTreeNodeHashElement (const QChar * pLocation, KviKvsTreeNodeData * pSource, KviKvsTreeNodeData * pIndex)
References m_pKey, and KviKvsTreeNode::setParent().
KviKvsTreeNodeHashElement::~KviKvsTreeNodeHashElement ()
References m_pKey.
Member Function Documentation
void KviKvsTreeNodeHashElement::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeHashElement::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::dump(), m_pKey, and KviKvsTreeNodeIndirectData::m_pSource.
bool KviKvsTreeNodeHashElement::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References evaluateReadOnlyInObjectScope().
bool KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsVariant::asString(), KviKvsVariant::copyFrom(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsHash::find(), KviKvsVariant::getTypeName(), KviKvsVariant::hash(), KviKvsVariant::isHash(), KviKvsVariant::isNothing(), key, m_pKey, KviKvsTreeNodeIndirectData::m_pSource, KviKvsVariant::setNothing(), v, and KviKvsRunTimeContext::warning().
Referenced by evaluateReadOnly().
KviKvsRWEvaluationResult * KviKvsTreeNodeHashElement::evaluateReadWrite (KviKvsRunTimeContext * c) virtual
Reimplemented from KviKvsTreeNodeData.
References evaluateReadWriteInObjectScope().
KviKvsRWEvaluationResult * KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) virtual
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), KviKvsHash::get(), KviKvsVariant::getTypeName(), KviKvsVariant::hash(), KviKvsVariant::isHash(), KviKvsVariant::isNothing(), key, m_pKey, KviKvsTreeNodeIndirectData::m_pSource, KviKvsRWEvaluationResult::result(), KviKvsVariant::setHash(), and KviKvsRunTimeContext::warning().
Referenced by evaluateReadWrite().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeHashElement::m_pKey protected
Referenced by dump(), evaluateReadOnlyInObjectScope(), evaluateReadWriteInObjectScope(), KviKvsTreeNodeHashElement(), and ~KviKvsTreeNodeHashElement().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeHashElement.h
src/kvirc/kvs/tree/KviKvsTreeNodeHashElement.cpp