KVIrc: KviHybridServerInfo Class Reference
KviHybridServerInfo Class Reference
#include <KviIrcConnectionServerInfo.h>
Public Member Functions
virtual const QString & getChannelModeDescription (char mode)
virtual char getRegisterModeChar ()
virtual const char * getSoftware ()
virtual const QString & getUserModeDescription (QChar mode)
virtual QChar getUserModeRequirement (QChar mode)
KviHybridServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
Public Member Functions inherited from KviBasicIrcServerInfo
virtual bool getNeedsOperToSetS ()
virtual bool getNeedsOpToListModeseI ()
KviBasicIrcServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
virtual ~KviBasicIrcServerInfo ()
Additional Inherited Members
Protected Attributes inherited from KviBasicIrcServerInfo
KviIrcConnectionServerInfo * m_pParent
QString m_szServerVersion
Constructor & Destructor Documentation
KviHybridServerInfo::KviHybridServerInfo (KviIrcConnectionServerInfo * pParent = 0, const QString & version = KviQString::Empty) inline
Member Function Documentation
const QString & KviHybridServerInfo::getChannelModeDescription (char mode) virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviCharybdisServerInfo, and KviIrcdRatboxIrcServerInfo.
References __tr2qs, and KviBasicIrcServerInfo::getChannelModeDescription().
Referenced by KviIrcdRatboxIrcServerInfo::getChannelModeDescription(), KviPlexusIrcServerInfo::getChannelModeDescription(), and KviOftcIrcServerInfo::getChannelModeDescription().
virtual char KviHybridServerInfo::getRegisterModeChar () inline virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviOftcIrcServerInfo, KviIrcdSevenIrcServerInfo, and KviIrcdRatboxIrcServerInfo.
virtual const char* KviHybridServerInfo::getSoftware () inline virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviIrcdSevenIrcServerInfo, KviCharybdisServerInfo, and KviIrcdRatboxIrcServerInfo.
const QString & KviHybridServerInfo::getUserModeDescription (QChar mode) virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviIrcdSevenIrcServerInfo, KviCharybdisServerInfo, and KviIrcdRatboxIrcServerInfo.
References __tr2qs, and KviBasicIrcServerInfo::getUserModeDescription().
Referenced by KviIrcdRatboxIrcServerInfo::getUserModeDescription(), KviPlexusIrcServerInfo::getUserModeDescription(), and KviOftcIrcServerInfo::getUserModeDescription().
QChar KviHybridServerInfo::getUserModeRequirement (QChar mode) virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviIrcdSevenIrcServerInfo, KviCharybdisServerInfo, and KviIrcdRatboxIrcServerInfo.
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionServerInfo.h
src/kvirc/kernel/KviIrcConnectionServerInfo.cpp