KVIrc: ThemeManagementDialog Class Reference
ThemeManagementDialog Class Reference
#include <ThemeManagementDialog.h>
Public Member Functions
ThemeManagementDialog (QWidget *parent)
virtual ~ThemeManagementDialog ()
Static Public Member Functions
static void cleanup ()
static void display (bool bTopLevel)
static ThemeManagementDialog * instance ()
Protected Slots
void applyCurrentTheme ()
void applyTheme (QListWidgetItem *)
void closeClicked ()
void contextMenuRequested (const QPoint &pos)
void deleteTheme ()
void enableDisableButtons ()
void fillThemeBox ()
void getMoreThemes ()
void installFromFile ()
void packTheme ()
void saveCurrentTheme ()
void tipRequest (QListWidgetItem *pItem, const QPoint &pnt)
void webThemeInterfaceDialogDestroyed ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
void fillThemeBox (bool bBuiltin)
Protected Attributes
QMenu * m_pContextPopup
QLabel * m_pCurrentInstalledThemeLabel
QToolButton * m_pDeleteThemeButton
KviTalIconAndRichTextItemDelegate * m_pItemDelegate
KviTalListWidget * m_pListWidget
QToolButton * m_pPackThemeButton
Static Protected Attributes
static ThemeManagementDialog * m_pInstance = nullptr
Constructor & Destructor Documentation
ThemeManagementDialog::ThemeManagementDialog (QWidget * parent)
References __tr2qs, __tr2qs_ctx(), applyTheme(), closeClicked(), connect(), contextMenuRequested(), deleteTheme(), enableDisableButtons(), fillThemeBox(), g_pApp, g_pIconManager, g_pMainWindow, g_rectManagementDialogGeometry, KviIconManager::getBigIcon(), getMoreThemes(), KviIconManager::getSmallIcon(), installFromFile(), KVI_BIGICON_OPEN, KVI_BIGICON_PACK, KVI_BIGICON_REMOVE, KVI_BIGICON_SAVE, KVI_BIGICON_THEME, KVI_BIGICON_WWW, KVI_OPTION_STRING, KviOption_stringIconThemeSubdir, m_pContextPopup, m_pCurrentInstalledThemeLabel, m_pDeleteThemeButton, m_pInstance, m_pItemDelegate, m_pListWidget, m_pPackThemeButton, KviMemory::move(), packTheme(), saveCurrentTheme(), KviTalIconAndRichTextItemDelegate::setDefaultIcon(), KviTalIconAndRichTextItemDelegate::setIconSize(), KviTalHBox::setMargin(), KviTalIconAndRichTextItemDelegate::setMinimumSize(), KviTalHBox::setSpacing(), KviIconManager::Theme, and w.
Referenced by display().
ThemeManagementDialog::~ThemeManagementDialog () virtual
References g_rectManagementDialogGeometry, m_pInstance, m_pItemDelegate, x, and y.
Member Function Documentation
void ThemeManagementDialog::applyCurrentTheme () protected slot
References __tr2qs_ctx(), KviTheme::apply(), g_pIconManager, KviIconManager::getBigIcon(), KVI_BIGICON_THEME, KVI_OPTION_STRING, KviOption_stringIconThemeSubdir, KviThemeInfo::lastError(), KviThemeInfo::location(), m_pCurrentInstalledThemeLabel, m_pItemDelegate, m_pListWidget, KviThemeInfo::name(), KviTalIconAndRichTextItemDelegate::setDefaultIcon(), KviThemeInfo::subdirectory(), ThemeListWidgetItem::themeInfo(), KviThemeInfo::version(), and KviMessageBox::yesNo().
Referenced by applyTheme(), and contextMenuRequested().
void ThemeManagementDialog::applyTheme (QListWidgetItem * it) protected slot
References applyCurrentTheme(), and m_pListWidget.
Referenced by ThemeManagementDialog().
void ThemeManagementDialog::cleanup () static
References m_pInstance.
Referenced by theme_module_cleanup().
void ThemeManagementDialog::closeClicked () protected slot
References m_pInstance.
Referenced by ThemeManagementDialog().
void ThemeManagementDialog::closeEvent (QCloseEvent * e) protected virtual
void ThemeManagementDialog::contextMenuRequested (const QPoint & pos) protected slot
References __tr2qs_ctx(), KviIconManager::Accept, applyCurrentTheme(), deleteTheme(), KviIconManager::Discard, g_pIconManager, KviIconManager::getSmallIcon(), KviThemeInfo::isBuiltin(), m_pContextPopup, m_pListWidget, and ThemeListWidgetItem::themeInfo().
Referenced by ThemeManagementDialog().
void ThemeManagementDialog::deleteTheme () protected slot
References __tr2qs_ctx(), KviFileUtils::deleteDir(), KviThemeInfo::directory(), fillThemeBox(), i, KviThemeInfo::isBuiltin(), m_pListWidget, KviThemeInfo::name(), ThemeListWidgetItem::themeInfo(), KviThemeInfo::version(), and KviMessageBox::yesNo().
Referenced by contextMenuRequested(), and ThemeManagementDialog().
void ThemeManagementDialog::display (bool bTopLevel) static
References g_pMainWindow, m_pInstance, KviMainWindow::splitter(), and ThemeManagementDialog().
Referenced by theme_kvs_cmd_dialog().
void ThemeManagementDialog::enableDisableButtons () protected slot
References i, KviThemeInfo::isBuiltin(), m_pDeleteThemeButton, m_pListWidget, m_pPackThemeButton, ThemeListWidgetItem::themeInfo(), and u.
Referenced by fillThemeBox(), and ThemeManagementDialog().
void ThemeManagementDialog::fillThemeBox (bool bBuiltin) protected
References KviThemeInfo::Builtin, i, KviTheme::installedThemeDirectories(), KviThemeInfo::load(), m_pListWidget, KviThemeInfo::smallScreenshot(), and KviThemeInfo::User.
void ThemeManagementDialog::fillThemeBox () protected slot
References enableDisableButtons(), and m_pListWidget.
Referenced by deleteTheme(), installFromFile(), saveCurrentTheme(), ThemeManagementDialog(), and webThemeInterfaceDialogDestroyed().
void ThemeManagementDialog::getMoreThemes () protected slot
References connect(), KviMainWindow::executeInternalCommand(), g_pMainWindow, KVI_INTERNALCOMMAND_OPENURL_KVIRC_THEMES, and webThemeInterfaceDialogDestroyed().
Referenced by ThemeManagementDialog().
void ThemeManagementDialog::installFromFile () protected slot
References __tr2qs_ctx(), KviFileDialog::askForOpenFileName(), fillThemeBox(), KviMessageBox::information(), ThemeFunctions::installThemePackage(), and KVI_FILTER_THEME.
Referenced by ThemeManagementDialog().
static ThemeManagementDialog* ThemeManagementDialog::instance () inline static
References m_pInstance.
Referenced by theme_module_can_unload().
void ThemeManagementDialog::packTheme () protected slot
References KviPointerList< T >::append(), i, KviPointerList< T >::isEmpty(), m_pListWidget, and KviPointerList< T >::setAutoDelete().
Referenced by ThemeManagementDialog().
void ThemeManagementDialog::saveCurrentTheme () protected slot
References fillThemeBox().
Referenced by ThemeManagementDialog().
void ThemeManagementDialog::tipRequest (QListWidgetItem * pItem, const QPoint & pnt) protected slot
void ThemeManagementDialog::webThemeInterfaceDialogDestroyed () protected slot
References fillThemeBox().
Referenced by getMoreThemes().
Member Data Documentation
QMenu* ThemeManagementDialog::m_pContextPopup protected
Referenced by contextMenuRequested(), and ThemeManagementDialog().
QLabel* ThemeManagementDialog::m_pCurrentInstalledThemeLabel protected
Referenced by applyCurrentTheme(), and ThemeManagementDialog().
QToolButton* ThemeManagementDialog::m_pDeleteThemeButton protected
Referenced by enableDisableButtons(), and ThemeManagementDialog().
ThemeManagementDialog * ThemeManagementDialog::m_pInstance = nullptr static protected
Referenced by cleanup(), closeClicked(), display(), instance(), ThemeManagementDialog(), and ~ThemeManagementDialog().
KviTalIconAndRichTextItemDelegate* ThemeManagementDialog::m_pItemDelegate protected
Referenced by applyCurrentTheme(), ThemeManagementDialog(), and ~ThemeManagementDialog().
KviTalListWidget* ThemeManagementDialog::m_pListWidget protected
Referenced by applyCurrentTheme(), applyTheme(), contextMenuRequested(), deleteTheme(), enableDisableButtons(), fillThemeBox(), packTheme(), and ThemeManagementDialog().
QToolButton* ThemeManagementDialog::m_pPackThemeButton protected
Referenced by enableDisableButtons(), and ThemeManagementDialog().
The documentation for this class was generated from the following files:
src/modules/theme/ThemeManagementDialog.h
src/modules/theme/ThemeManagementDialog.cpp