KVIrc: RegisteredUserEntryDialog Class Reference
RegisteredUserEntryDialog Class Reference
#include <RegisteredUserEntryDialog.h>
Public Member Functions
RegisteredUserEntryDialog (QWidget *p, KviRegisteredUser *r, bool bModal=true)
virtual ~RegisteredUserEntryDialog ()
Public Member Functions inherited from KviTalTabDialog
KviTalTabDialog (QWidget *pParent=0, const char *name=0, bool bModal=false)
~KviTalTabDialog ()
Protected Slots
void addMaskClicked ()
void delMaskClicked ()
void editAllPropertiesClicked ()
void editMaskClicked ()
void maskCurrentChanged ()
void notifyCheckClicked (bool bChecked)
void okClicked ()
Protected Slots inherited from KviTalTabDialog
void cancelPressed ()
void okPressed ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
Protected Member Functions inherited from KviTalTabDialog
void addTab (QWidget *, const QString &)
void setCancelButton (const QString &)
void setOkButton (const QString &)
Protected Attributes
QPushButton * m_pAddMaskButton
KviPixmap * m_pAvatar
KviPixmapSelector * m_pAvatarSelector
QLineEdit * m_pCommentEdit
QColor * m_pCustomColor
QCheckBox * m_pCustomColorCheck
KviColorSelector * m_pCustomColorSelector
QPushButton * m_pDelMaskButton
QPushButton * m_pEditMaskButton
QCheckBox * m_pIgnoreChannel
QCheckBox * m_pIgnoreCtcp
QCheckBox * m_pIgnoreDcc
QCheckBox * m_pIgnoreEnabled
QCheckBox * m_pIgnoreHighlight
QCheckBox * m_pIgnoreInvite
QCheckBox * m_pIgnoreNotice
QCheckBox * m_pIgnoreQuery
QListWidget * m_pMaskListBox
QLineEdit * m_pNameEdit
QCheckBox * m_pNotifyCheck
QLabel * m_pNotifyLabel
QLineEdit * m_pNotifyNick
KviPointerHashTable< QString,
QString > * m_pPropertyDict
KviRegisteredUser * m_pUser
Additional Inherited Members
Signals inherited from KviTalTabDialog
void applyButtonPressed ()
void cancelButtonPressed ()
Constructor & Destructor Documentation
RegisteredUserEntryDialog::RegisteredUserEntryDialog (QWidget * p, KviRegisteredUser * r, bool bModal = true)
References __tr2qs_ctx(), addMaskClicked(), KviTalTabDialog::addTab(), KviTalTabDialog::applyButtonPressed(), KviTalTabDialog::cancelButtonPressed(), KviRegisteredUser::Channel, connect(), KviRegisteredUser::Ctcp, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviRegisteredUser::Dcc, KviIconManager::DeleteItem, delMaskClicked(), editAllPropertiesClicked(), KviIconManager::EditItem, editMaskClicked(), f, KviPointerList< T >::first(), KviStringConversion::fromString(), g, g_pIconManager, KviRegisteredUser::getBoolProperty(), KviRegisteredUser::getProperty(), KviIconManager::getSmallIcon(), KviRegisteredUser::Highlight, KviRegisteredUser::ignoreEnabled(), KviRegisteredUser::ignoreFlags(), KviPointerHashTable< Key, T >::insert(), KviRegisteredUser::Invite, l, KviIconManager::Linux, m, m_pAddMaskButton, m_pAvatar, m_pAvatarSelector, m_pCommentEdit, m_pCustomColor, m_pCustomColorCheck, m_pCustomColorSelector, m_pDelMaskButton, m_pEditMaskButton, m_pIgnoreChannel, m_pIgnoreCtcp, m_pIgnoreDcc, m_pIgnoreEnabled, m_pIgnoreHighlight, m_pIgnoreInvite, m_pIgnoreNotice, m_pIgnoreQuery, m_pMaskListBox, m_pNameEdit, m_pNotifyCheck, m_pNotifyLabel, m_pNotifyNick, m_pPropertyDict, m_pUser, maskCurrentChanged(), KviRegisteredUser::maskList(), KviRegisteredUser::name(), KviIconManager::NewItem, KviPointerList< T >::next(), KviRegisteredUser::Notice, notifyCheckClicked(), okClicked(), KviRegisteredUser::propertyDict(), KviRegisteredUser::Query, r, s, KviPointerHashTable< Key, T >::setAutoDelete(), KviTalTabDialog::setCancelButton(), KviTalVBox::setMargin(), KviTalTabDialog::setOkButton(), KviTalHBox::setSpacing(), and w.
RegisteredUserEntryDialog::~RegisteredUserEntryDialog () virtual
References m_pAvatar, m_pCustomColor, and m_pPropertyDict.
Member Function Documentation
void RegisteredUserEntryDialog::addMaskClicked () protected slot
References KviIrcMask::host(), m, m_pMaskListBox, KviIrcMask::nick(), and KviIrcMask::user().
Referenced by RegisteredUserEntryDialog().
void RegisteredUserEntryDialog::closeEvent (QCloseEvent * e) protected virtual
References okClicked().
void RegisteredUserEntryDialog::delMaskClicked () protected slot
References m_pMaskListBox.
Referenced by RegisteredUserEntryDialog().
void RegisteredUserEntryDialog::editAllPropertiesClicked () protected slot
References KviPixmapSelector::commit(), KviPointerHashTable< Key, T >::find(), KviCString::isEmpty(), KviPixmap::isNull(), m_pAvatar, m_pAvatarSelector, m_pNotifyCheck, m_pNotifyNick, m_pPropertyDict, KviPixmap::path(), KviPointerHashTable< Key, T >::remove(), KviPointerHashTable< Key, T >::replace(), and KviPixmapSelector::setImagePath().
Referenced by RegisteredUserEntryDialog().
void RegisteredUserEntryDialog::editMaskClicked () protected slot
References KviIrcMask::host(), m, m_pMaskListBox, KviIrcMask::nick(), and KviIrcMask::user().
Referenced by RegisteredUserEntryDialog().
void RegisteredUserEntryDialog::maskCurrentChanged () protected slot
References m_pDelMaskButton, m_pEditMaskButton, and m_pMaskListBox.
Referenced by RegisteredUserEntryDialog().
void RegisteredUserEntryDialog::notifyCheckClicked (bool bChecked) protected slot
References KviPointerList< T >::first(), m, m_pNotifyLabel, m_pNotifyNick, m_pUser, KviRegisteredUser::maskList(), KviRegisteredUser::name(), and KviPointerList< T >::next().
Referenced by RegisteredUserEntryDialog().
void RegisteredUserEntryDialog::okClicked () protected slot
References KviRegisteredUserDataBase::addMask(), KviRegisteredUserDataBase::addUser(), KviRegisteredUser::Channel, KviPixmapSelector::commit(), KviRegisteredUser::Ctcp, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviRegisteredUser::Dcc, KviRegisteredUserDataBase::findUserByName(), g_pApp, KviColorSelector::getColor(), KviRegisteredUser::group(), KviRegisteredUser::Highlight, KviRegisteredUser::Invite, KviPixmap::isNull(), m_pAvatar, m_pAvatarSelector, m_pCommentEdit, m_pCustomColorCheck, m_pCustomColorSelector, m_pIgnoreChannel, m_pIgnoreCtcp, m_pIgnoreDcc, m_pIgnoreEnabled, m_pIgnoreHighlight, m_pIgnoreInvite, m_pIgnoreNotice, m_pIgnoreQuery, m_pMaskListBox, m_pNameEdit, m_pNotifyCheck, m_pNotifyNick, m_pPropertyDict, m_pUser, KviRegisteredUser::name(), KviRuntimeInfo::name(), KviRegisteredUser::Notice, KviApplication::optionResetUpdate(), KviPixmap::path(), KviRegisteredUser::Query, KviPointerHashTable< Key, T >::remove(), KviRegisteredUserDataBase::removeMask(), KviRegisteredUserDataBase::removeUser(), s, KviRegisteredUser::setGroup(), KviRegisteredUser::setIgnoreEnabled(), KviRegisteredUser::setIgnoreFlags(), KviRegisteredUser::setProperty(), KviStringConversion::toString(), and u.
Referenced by closeEvent(), and RegisteredUserEntryDialog().
Member Data Documentation
QPushButton* RegisteredUserEntryDialog::m_pAddMaskButton protected
Referenced by RegisteredUserEntryDialog().
KviPixmap* RegisteredUserEntryDialog::m_pAvatar protected
Referenced by editAllPropertiesClicked(), okClicked(), RegisteredUserEntryDialog(), and ~RegisteredUserEntryDialog().
KviPixmapSelector* RegisteredUserEntryDialog::m_pAvatarSelector protected
Referenced by editAllPropertiesClicked(), okClicked(), and RegisteredUserEntryDialog().
QLineEdit* RegisteredUserEntryDialog::m_pCommentEdit protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QColor* RegisteredUserEntryDialog::m_pCustomColor protected
Referenced by RegisteredUserEntryDialog(), and ~RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pCustomColorCheck protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
KviColorSelector* RegisteredUserEntryDialog::m_pCustomColorSelector protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QPushButton* RegisteredUserEntryDialog::m_pDelMaskButton protected
Referenced by maskCurrentChanged(), and RegisteredUserEntryDialog().
QPushButton* RegisteredUserEntryDialog::m_pEditMaskButton protected
Referenced by maskCurrentChanged(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreChannel protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreCtcp protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreDcc protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreEnabled protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreHighlight protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreInvite protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreNotice protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pIgnoreQuery protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QListWidget* RegisteredUserEntryDialog::m_pMaskListBox protected
Referenced by addMaskClicked(), delMaskClicked(), editMaskClicked(), maskCurrentChanged(), okClicked(), and RegisteredUserEntryDialog().
QLineEdit* RegisteredUserEntryDialog::m_pNameEdit protected
Referenced by okClicked(), and RegisteredUserEntryDialog().
QCheckBox* RegisteredUserEntryDialog::m_pNotifyCheck protected
Referenced by editAllPropertiesClicked(), okClicked(), and RegisteredUserEntryDialog().
QLabel* RegisteredUserEntryDialog::m_pNotifyLabel protected
Referenced by notifyCheckClicked(), and RegisteredUserEntryDialog().
QLineEdit* RegisteredUserEntryDialog::m_pNotifyNick protected
Referenced by editAllPropertiesClicked(), notifyCheckClicked(), okClicked(), and RegisteredUserEntryDialog().
KviPointerHashTable<QString, QString>* RegisteredUserEntryDialog::m_pPropertyDict protected
Referenced by editAllPropertiesClicked(), okClicked(), RegisteredUserEntryDialog(), and ~RegisteredUserEntryDialog().
KviRegisteredUser* RegisteredUserEntryDialog::m_pUser protected
Referenced by notifyCheckClicked(), okClicked(), and RegisteredUserEntryDialog().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUserEntryDialog.h
src/modules/reguser/RegisteredUserEntryDialog.cpp