KVIrc: KviKvsTreeNodeSpecialCommandSwitch Class Reference
KviKvsTreeNodeSpecialCommandSwitch Class Reference
#include <KviKvsTreeNodeSpecialCommandSwitch.h>
Public Member Functions
void addLabel (KviKvsTreeNodeSpecialCommandSwitchLabel *l)
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
bool isEmpty ()
KviKvsTreeNodeSpecialCommandSwitch (const QChar *pLocation, KviKvsTreeNodeExpression *e)
~KviKvsTreeNodeSpecialCommandSwitch ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommand
KviKvsTreeNodeSpecialCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeSpecialCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviKvsTreeNodeExpression * m_pExpression
KviPointerList
< KviKvsTreeNodeSpecialCommandSwitchLabel > * m_pLabels
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandSwitch::KviKvsTreeNodeSpecialCommandSwitch (const QChar * pLocation, KviKvsTreeNodeExpression * e)
References e, m_pExpression, m_pLabels, KviPointerList< T >::setAutoDelete(), and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandSwitch::~KviKvsTreeNodeSpecialCommandSwitch ()
References m_pExpression, and m_pLabels.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandSwitch::addLabel (KviKvsTreeNodeSpecialCommandSwitchLabel * l)
References KviPointerList< T >::append(), m_pLabels, and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseSpecialCommandSwitch().
void KviKvsTreeNodeSpecialCommandSwitch::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandSwitch::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
References KviKvsTreeNodeExpression::dump(), KviPointerList< T >::first(), l, m_pExpression, m_pLabels, and KviPointerList< T >::next().
bool KviKvsTreeNodeSpecialCommandSwitch::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsRunTimeContext::breakPending(), KviKvsRunTimeContext::error(), KviKvsTreeNodeSwitchList::evaluate(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsSwitchList::find(), KviPointerList< T >::first(), KviKvsRunTimeContext::handleBreak(), l, m_pExpression, m_pLabels, KviKvsTreeNodeCommand::m_pSwitches, KviPointerList< T >::next(), swl, and v.
bool KviKvsTreeNodeSpecialCommandSwitch::isEmpty () inline
Referenced by KviKvsParser::parseSpecialCommandSwitch().
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeSpecialCommandSwitch::m_pExpression private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandSwitch(), and ~KviKvsTreeNodeSpecialCommandSwitch().
KviPointerList<KviKvsTreeNodeSpecialCommandSwitchLabel>* KviKvsTreeNodeSpecialCommandSwitch::m_pLabels private
Referenced by addLabel(), dump(), execute(), KviKvsTreeNodeSpecialCommandSwitch(), and ~KviKvsTreeNodeSpecialCommandSwitch().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandSwitch.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandSwitch.cpp