KVIrc: KviMessageTypeSettings Class Reference
KviMessageTypeSettings Class Reference
#include <KviMessageTypeSettings.h>
Public Member Functions
unsigned char back ()
void enableLogging (bool bEnable)
unsigned char fore ()
KviMessageTypeSettings (const char *type, int pixId, unsigned char fore, unsigned char back, bool bLog, int iLevel)
KviMessageTypeSettings (const KviMessageTypeSettings &msg)
int level ()
bool logEnabled ()
KviMessageTypeSettings & operator= (const KviMessageTypeSettings &msg)
int pixId ()
void setBack (char back)
void setFore (char fore)
void setLevel (int iLevel)
void setPixId (int pixId)
const char * type ()
~KviMessageTypeSettings ()
Public Attributes
bool m_bLogEnabled
unsigned char m_cBackColor
unsigned char m_cForeColor
int m_iLevel
int m_iPixId
const char * m_szType
Constructor & Destructor Documentation
KviMessageTypeSettings::KviMessageTypeSettings (const char * type, int pixId, unsigned char fore, unsigned char back, bool bLog, int iLevel)
References back(), fore(), KVI_MSGTYPE_MAXLEVEL, KVI_MSGTYPE_MINLEVEL, m_bLogEnabled, m_cBackColor, m_cForeColor, m_iLevel, m_iPixId, m_szType, pixId(), and type().
KviMessageTypeSettings::KviMessageTypeSettings (const KviMessageTypeSettings & msg)
References m_bLogEnabled, m_cBackColor, m_cForeColor, m_iLevel, m_iPixId, and m_szType.
KviMessageTypeSettings::~KviMessageTypeSettings ()
Member Function Documentation
unsigned char KviMessageTypeSettings::back () [inline]
Referenced by KviMessageTypeSettings(), OptionsWidget_messageColors::load(), MessageListWidgetItemDelegate::paint(), and OptionsWidget_messageColors::save().
void KviMessageTypeSettings::enableLogging (bool bEnable) [inline]
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::saveLastItem().
unsigned char KviMessageTypeSettings::fore () [inline]
Referenced by KviMessageTypeSettings(), OptionsWidget_messageColors::load(), MessageListWidgetItemDelegate::paint(), and OptionsWidget_messageColors::save().
int KviMessageTypeSettings::level () [inline]
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::save().
bool KviMessageTypeSettings::logEnabled () [inline]
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::save().
KviMessageTypeSettings & KviMessageTypeSettings::operator= (const KviMessageTypeSettings & msg)
References m_bLogEnabled, m_cBackColor, m_cForeColor, m_iLevel, m_iPixId, and m_szType.
int KviMessageTypeSettings::pixId () [inline]
Referenced by LogViewWindow::createLog(), KviMessageTypeSettings(), OptionsWidget_messageColors::load(), MessageListWidgetItem::MessageListWidgetItem(), MessageListWidgetItemDelegate::paint(), and OptionsWidget_messageColors::save().
void KviMessageTypeSettings::setBack (char back) [inline]
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::saveLastItem().
void KviMessageTypeSettings::setFore (char fore) [inline]
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::saveLastItem().
void KviMessageTypeSettings::setLevel (int iLevel) [inline]
References KVI_MSGTYPE_MAXLEVEL, and KVI_MSGTYPE_MINLEVEL.
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::saveLastItem().
void KviMessageTypeSettings::setPixId (int pixId) [inline]
Referenced by OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::newIconSelected().
const char* KviMessageTypeSettings::type () [inline]
Referenced by KviMessageTypeSettings(), and MessageListWidgetItem::MessageListWidgetItem().
Member Data Documentation
bool KviMessageTypeSettings::m_bLogEnabled
Referenced by KviMessageTypeSettings(), operator=(), and KviStringConversion::toString().
unsigned char KviMessageTypeSettings::m_cBackColor
Referenced by KviMessageTypeSettings(), operator=(), and KviStringConversion::toString().
unsigned char KviMessageTypeSettings::m_cForeColor
Referenced by KviMessageTypeSettings(), operator=(), and KviStringConversion::toString().
int KviMessageTypeSettings::m_iLevel
Referenced by KviMessageTypeSettings(), operator=(), and KviStringConversion::toString().
int KviMessageTypeSettings::m_iPixId
Referenced by KviMessageTypeSettings(), operator=(), and KviStringConversion::toString().
const char* KviMessageTypeSettings::m_szType
Referenced by KviStringConversion::fromString(), KviMessageTypeSettings(), and operator=().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviMessageTypeSettings.h
src/kvilib/ext/KviMessageTypeSettings.cpp