KVIrc: KviKvsParser Class Reference
KviKvsParser Class Reference
#include <kvi_kvs_parser.h>
Public Types
Public Member Functions
bool error () const
KviKvsParser (KviKvsScript *pScript, KviWindow *pOutputWindow)
KviKvsTreeNodeInstruction * parse (const QChar *pBuffer, int iFlags=0)
KviKvsTreeNodeInstruction * parseAsExpression (const QChar *pBuffer, int iFlags=0)
KviKvsTreeNodeInstruction * parseAsParameter (const QChar *pBuffer, int iFlags=0)
~KviKvsParser ()
Static Protected Member Functions
static void init ()
Private Member Functions
void error (const QChar *pLocation, const QString &szMsgFmt,...)
void errorBadChar (const QChar *pLocation, char cExpected, const char *szCommandName)
KviKvsTreeNodeData * parseAt (bool bInObjScope=false)
KviKvsTreeNodeOperation * parseBindingOperation ()
KviKvsTreeNodeConstantData * parseBindingOperationLiteralParameter ()
KviKvsTreeNodeData * parseBindingOperationParameter ()
KviKvsTreeNodeCommand * parseCommand ()
KviKvsTreeNodeConstantData * parseCommandLiteralParameter ()
KviKvsTreeNodeData * parseCommandParameter (bool bPreferNumeric=false)
KviKvsTreeNodeDataList * parseCommandParameterList ()
KviKvsTreeNodeSwitchList * parseCommandSwitchList ()
KviKvsTreeNodeConstantData * parseCommaSeparatedLiteralParameter ()
KviKvsTreeNodeData * parseCommaSeparatedParameter ()
KviKvsTreeNodeDataList * parseCommaSeparatedParameterList ()
KviPointerList< QString > * parseCommaSeparatedParameterListNoTree ()
KviKvsTreeNode * parseComment ()
KviKvsTreeNodeData * parseDollar (bool bInObjScope=false)
KviKvsTreeNodeExpression * parseExpression (char terminator)
KviKvsTreeNodeExpressionBinaryOperator * parseExpressionBinaryOperator ()
bool parseExpressionMightPointToOperator ()
KviKvsTreeNodeExpression * parseExpressionOperand (char terminator)
KviKvsTreeNodeExpression * parseExpressionOperandCore (char terminator)
KviKvsTreeNodeData * parseHashKey ()
KviKvsTreeNodeConstantData * parseHashKeyLiteralParameter ()
KviKvsTreeNodeInstruction * parseInstruction ()
KviKvsTreeNodeInstruction * parseInstructionBlock ()
KviKvsTreeNodeInstruction * parseInstructionList ()
KviKvsTreeNodeOperation * parseOperation ()
KviKvsTreeNodeData * parseOperationRightSide (bool bPreferNumeric=false)
KviKvsTreeNodeData * parseParameterPercentOrDollar ()
KviKvsTreeNodeVariable * parsePercent (bool bInObjectScope=false)
KviKvsTreeNodeData * parsePercentOrDollar (bool bInObjScope=false)
KviKvsTreeNodeConstantData * parseSingleLiteralParameterInParenthesis ()
KviKvsTreeNodeData * parseSingleParameterInParenthesis ()
KviKvsTreeNodeCommand * parseSpecialCommandBreak ()
KviKvsTreeNodeCommand * parseSpecialCommandClass ()
KviKvsTreeNodeCommand * parseSpecialCommandContinue ()
KviKvsTreeNodeCommand * parseSpecialCommandDefpopup ()
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup * parseSpecialCommandDefpopupLabelPopup ()
KviKvsTreeNodeCommand * parseSpecialCommandDo ()
KviKvsTreeNodeCommand * parseSpecialCommandFor ()
KviKvsTreeNodeCommand * parseSpecialCommandForeach ()
KviKvsTreeNodeCommand * parseSpecialCommandGlobal ()
KviKvsTreeNodeCommand * parseSpecialCommandHelp ()
KviKvsTreeNodeCommand * parseSpecialCommandIf ()
KviKvsTreeNodeCommand * parseSpecialCommandPerlBegin ()
KviKvsTreeNodeCommand * parseSpecialCommandPythonBegin ()
KviKvsTreeNodeCommand * parseSpecialCommandSwitch ()
KviKvsTreeNodeCommand * parseSpecialCommandUnset ()
KviKvsTreeNodeCommand * parseSpecialCommandWhile ()
KviKvsTreeNodeConstantData * parseStringLiteralParameter ()
KviKvsTreeNodeData * parseStringParameter ()
KviKvsTreeNodeInstruction * parseVoidFunctionCallOrOperation ()
void report (bool bError, const QChar *pLocation, const QString &szMsgFmt, kvi_va_list va)
void skipSpaces ()
bool skipSpacesAndNewlines ()
void skipToEndOfCStyleComment ()
bool skipToEndOfForControlBlock ()
void skipToNextLine ()
void warning (const QChar *pLocation, const QString &szMsgFmt,...)
Private Attributes
bool m_bError
int m_iFlags
const QChar * m_pBuffer
KviPointerHashTable< QString,
QString > * m_pGlobals
KviKvsScript * m_pScript
const QChar * m_ptr
KviWindow * m_pWindow
Friends
class KviKvsKernel
Member Enumeration Documentation
enum KviKvsParser::Flags
Enumerator:
AssumeLocals
Pedantic
Constructor & Destructor Documentation
KviKvsParser::KviKvsParser (KviKvsScript * pScript, KviWindow * pOutputWindow)
References m_pGlobals, m_pScript, and m_pWindow.
KviKvsParser::~KviKvsParser ()
References m_pGlobals.
Member Function Documentation
void KviKvsParser::error (const QChar * pLocation, const QString & szMsgFmt, ...) [private]
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, m_bError, and report().
bool KviKvsParser::error () const [inline]
Referenced by errorBadChar(), KviKvsScript::parse(), parse(), parseAsExpression(), parseAsParameter(), parseBindingOperation(), parseCommand(), parseCommandSwitchList(), parseCommaSeparatedParameterList(), parseCommaSeparatedParameterListNoTree(), parseComment(), parseDollar(), parseExpressionBinaryOperator(), parseExpressionOperand(), parseExpressionOperandCore(), parseInstruction(), parseInstructionBlock(), parseInstructionList(), parseOperation(), parsePercent(), parseSpecialCommandClass(), parseSpecialCommandDefpopupLabelPopup(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandGlobal(), parseSpecialCommandIf(), parseSpecialCommandSwitch(), parseSpecialCommandUnset(), parseSpecialCommandWhile(), parseVoidFunctionCallOrOperation(), skipSpacesAndNewlines(), and skipToEndOfForControlBlock().
void KviKvsParser::errorBadChar (const QChar * pLocation, char cExpected, const char * szCommandName) [private]
References __tr2qs_ctx, and error().
Referenced by parseSpecialCommandClass(), parseSpecialCommandDefpopup(), parseSpecialCommandDefpopupLabelPopup(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandIf(), and parseSpecialCommandSwitch().
void KviKvsParser::init () [static, protected]
References _REG_CNTRL_CMD, KviKvsKernel::instance(), parseSpecialCommandBreak(), parseSpecialCommandClass(), parseSpecialCommandContinue(), parseSpecialCommandDefpopup(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandGlobal(), parseSpecialCommandHelp(), parseSpecialCommandIf(), parseSpecialCommandSwitch(), parseSpecialCommandUnset(), and parseSpecialCommandWhile().
KviKvsTreeNodeInstruction * KviKvsParser::parse (const QChar * pBuffer, int iFlags = 0)
References __tr2qs_ctx, KviPointerHashTable< Key, T >::clear(), error(), m_bError, m_iFlags, m_pBuffer, m_pGlobals, m_ptr, and parseInstructionList().
Referenced by KviKvsScript::parse().
KviKvsTreeNodeInstruction * KviKvsParser::parseAsExpression (const QChar * pBuffer, int iFlags = 0)
References __tr2qs_ctx, KviPointerHashTable< Key, T >::clear(), error(), m_bError, m_iFlags, m_pBuffer, m_pGlobals, m_ptr, and parseExpression().
Referenced by KviKvsScript::parse().
KviKvsTreeNodeInstruction * KviKvsParser::parseAsParameter (const QChar * pBuffer, int iFlags = 0)
References __tr2qs_ctx, KviPointerHashTable< Key, T >::clear(), error(), m_bError, m_iFlags, m_pBuffer, m_pGlobals, m_ptr, and parseCommandParameterList().
Referenced by KviKvsScript::parse().
KviKvsTreeNodeData* KviKvsParser::parseAt (bool bInObjScope = false) [private]
KviKvsTreeNodeOperation * KviKvsParser::parseBindingOperation () [private]
References __tr2qs_ctx, error(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharIsLetter, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseBindingOperationParameter(), parseCommandParameter(), and skipSpaces().
Referenced by parseOperation().
KviKvsTreeNodeConstantData* KviKvsParser::parseBindingOperationLiteralParameter () [private]
Referenced by parseBindingOperationParameter().
KviKvsTreeNodeData * KviKvsParser::parseBindingOperationParameter () [private]
References KviPointerList< T >::append(), KviPointerList< T >::count(), KviPointerList< T >::first(), KVSP_curCharPointer, KVSP_curCharUnicode, parseBindingOperationLiteralParameter(), parseParameterPercentOrDollar(), parseStringParameter(), and KviPointerList< T >::setAutoDelete().
Referenced by parseBindingOperation().
KviKvsTreeNodeCommand * KviKvsParser::parseCommand () [private]
References __tr2qs_ctx, KviCommandFormatter::bufferFromBlock(), KviQString::equalCI(), error(), KviKvsKernel::findCoreCallbackCommandExecRoutine(), KviKvsKernel::findCoreSimpleCommandExecRoutine(), KviKvsKernel::findSpecialCommandParsingRoutine(), KviKvsTreeNodeSwitchList::getStandardRebindingSwitch(), KviKvsKernel::instance(), KVSP_ASSERT, KVSP_curCharIsLetter, KVSP_curCharIsLetterOrNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, KviKvsTreeNode::location(), parseCommandParameterList(), parseCommandSwitchList(), parseCommaSeparatedParameterList(), parseInstruction(), parseSpecialCommandPerlBegin(), parseSpecialCommandPythonBegin(), _KviKvsSpecialCommandParsingRoutine::proc, KviKvsTreeNode::setLocation(), KviKvsTreeNodeCommand::setSwitchList(), skipSpaces(), skipSpacesAndNewlines(), and warning().
Referenced by parseInstruction().
KviKvsTreeNodeConstantData* KviKvsParser::parseCommandLiteralParameter () [private]
KviKvsTreeNodeData* KviKvsParser::parseCommandParameter (bool bPreferNumeric = false) [private]
Referenced by parseBindingOperation(), parseCommandParameterList(), parseCommandSwitchList(), and parseOperationRightSide().
KviKvsTreeNodeDataList * KviKvsParser::parseCommandParameterList () [private]
References KviKvsTreeNodeDataList::addItem(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommandParameter(), and skipSpaces().
Referenced by parseAsParameter(), and parseCommand().
KviKvsTreeNodeSwitchList * KviKvsParser::parseCommandSwitchList () [private]
References __tr2qs_ctx, KviKvsTreeNodeSwitchList::addLong(), KviKvsTreeNodeSwitchList::addShort(), error(), KviKvsTreeNodeSwitchList::isEmpty(), KVSP_ASSERT, KVSP_curCharIsEndOfCommand, KVSP_curCharIsLetter, KVSP_curCharIsLetterOrNumber, KVSP_curCharIsNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_setCurCharPointer, KVSP_skipChar, parseCommandParameter(), skipSpaces(), and warning().
Referenced by parseCommand().
KviKvsTreeNodeConstantData* KviKvsParser::parseCommaSeparatedLiteralParameter () [private]
KviKvsTreeNodeData* KviKvsParser::parseCommaSeparatedParameter () [private]
Referenced by parseCommaSeparatedParameterList(), and parseCommaSeparatedParameterListNoTree().
KviKvsTreeNodeDataList * KviKvsParser::parseCommaSeparatedParameterList () [private]
References __tr2qs_ctx, KviKvsTreeNodeDataList::addItem(), error(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommaSeparatedParameter(), and skipSpaces().
Referenced by parseCommand(), parseDollar(), parseSpecialCommandClass(), and parseSpecialCommandForeach().
KviPointerList< QString > * KviKvsParser::parseCommaSeparatedParameterListNoTree () [private]
References __tr2qs_ctx, KviPointerList< T >::append(), error(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommaSeparatedParameter(), s, KviPointerList< T >::setAutoDelete(), and skipSpaces().
KviKvsTreeNode * KviKvsParser::parseComment () [private]
References __tr2qs_ctx, error(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, skipToNextLine(), and warning().
Referenced by parseInstruction(), parseSpecialCommandClass(), and skipSpacesAndNewlines().
KviKvsTreeNodeData * KviKvsParser::parseDollar (bool bInObjScope = false) [private]
References __tr2qs_ctx, debug, error(), KviKvsKernel::findCoreFunctionExecRoutine(), KviKvsKernel::instance(), KVSP_ASSERT, KVSP_backChar, KVSP_curCharIsFunctionStart, KVSP_curCharIsLetter, KVSP_curCharIsLetterOrNumber, KVSP_curCharIsNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_setCurCharPointer, KVSP_skipChar, parseCommaSeparatedParameterList(), parseExpression(), parseInstructionBlock(), skipSpaces(), and warning().
Referenced by parsePercentOrDollar().
KviKvsTreeNodeExpression * KviKvsParser::parseExpression (char terminator) [private]
References KviKvsTreeNodeExpression::contextDescription(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, KviKvsTreeNodeExpression::parentWithPrecedenceLowerThan(), parseExpressionBinaryOperator(), parseExpressionOperand(), KviKvsTreeNodeExpression::precedence(), KviKvsTreeNodeExpression::right(), KviKvsTreeNodeExpression::setLeft(), KviKvsTreeNodeExpression::setRight(), and skipSpaces().
Referenced by parseAsExpression(), parseDollar(), parseExpressionOperand(), parsePercentOrDollar(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandIf(), parseSpecialCommandSwitch(), and parseSpecialCommandWhile().
KviKvsTreeNodeExpressionBinaryOperator * KviKvsParser::parseExpressionBinaryOperator () [private]
References __tr2qs_ctx, error(), KVSP_curCharPointer, KVSP_curCharUnicode, and KVSP_skipChar.
Referenced by parseExpression().
bool KviKvsParser::parseExpressionMightPointToOperator () [private]
References binary_operator_initial_char, KVSP_backChar, KVSP_curCharIsLetter, KVSP_curCharUnicode, and KVSP_skipChar.
Referenced by parseExpressionOperandCore().
KviKvsTreeNodeExpression * KviKvsParser::parseExpressionOperand (char terminator) [private]
References __tr2qs_ctx, d, error(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, KviKvsTreeNode::location(), parseExpression(), parseExpressionOperandCore(), and skipSpaces().
Referenced by parseExpression().
KviKvsTreeNodeExpression * KviKvsParser::parseExpressionOperandCore (char terminator) [private]
References __tr2qs_ctx, KviPointerList< T >::append(), KviPointerList< T >::count(), d, error(), KviPointerList< T >::first(), KVSP_curCharIsLetterOrNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseExpressionMightPointToOperator(), parseParameterPercentOrDollar(), parseStringParameter(), KviPointerList< T >::setAutoDelete(), and skipSpaces().
Referenced by parseExpressionOperand().
KviKvsTreeNodeData* KviKvsParser::parseHashKey () [private]
Referenced by parsePercentOrDollar().
KviKvsTreeNodeConstantData* KviKvsParser::parseHashKeyLiteralParameter () [private]
KviKvsTreeNodeInstruction * KviKvsParser::parseInstruction () [private]
References __tr2qs_ctx, error(), KVSP_ASSERT, KVSP_curCharIsLetter, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommand(), parseComment(), parseInstructionBlock(), and parseVoidFunctionCallOrOperation().
Referenced by parseCommand(), parseInstructionBlock(), parseInstructionList(), parseSpecialCommandClass(), parseSpecialCommandDefpopupLabelPopup(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandIf(), parseSpecialCommandSwitch(), and parseSpecialCommandWhile().
KviKvsTreeNodeInstruction * KviKvsParser::parseInstructionBlock () [private]
References __tr2qs_ctx, KviKvsTreeNodeInstructionBlock::addInstruction(), b, error(), KviKvsTreeNodeInstructionBlock::instructionCount(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseInstruction(), KviKvsTreeNodeInstructionBlock::releaseFirst(), skipSpacesAndNewlines(), and warning().
Referenced by parseDollar(), and parseInstruction().
KviKvsTreeNodeInstruction * KviKvsParser::parseInstructionList () [private]
References KviKvsTreeNodeInstructionBlock::addInstruction(), error(), KviKvsTreeNodeInstructionBlock::instructionCount(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, parseInstruction(), KviKvsTreeNodeInstructionBlock::releaseFirst(), and skipSpacesAndNewlines().
Referenced by parse().
KviKvsTreeNodeOperation * KviKvsParser::parseOperation () [private]
References __tr2qs_ctx, d, error(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseBindingOperation(), parseOperationRightSide(), SELF_OPERATOR, skipSpaces(), and warning().
Referenced by parseVoidFunctionCallOrOperation().
KviKvsTreeNodeData * KviKvsParser::parseOperationRightSide (bool bPreferNumeric = false) [private]
References KviPointerList< T >::append(), KviPointerList< T >::count(), KviPointerList< T >::first(), KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommandParameter(), KviPointerList< T >::setAutoDelete(), and skipSpaces().
Referenced by parseOperation().
KviKvsTreeNodeData * KviKvsParser::parseParameterPercentOrDollar () [private]
References KVSP_ASSERT, KVSP_backChar, KVSP_curCharIsFunctionStart, KVSP_curCharIsLetter, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, and parsePercentOrDollar().
Referenced by parseBindingOperationParameter(), and parseExpressionOperandCore().
KviKvsTreeNodeVariable * KviKvsParser::parsePercent (bool bInObjectScope = false) [private]
References __tr2qs_ctx, AssumeLocals, error(), KviPointerHashTable< Key, T >::find(), KVSP_ASSERT, KVSP_curCharIsLetterOrNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, m_iFlags, and m_pGlobals.
Referenced by parsePercentOrDollar(), and parseSpecialCommandUnset().
KviKvsTreeNodeData * KviKvsParser::parsePercentOrDollar (bool bInObjScope = false) [private]
References KviKvsTreeNodeData::canEvaluateInObjectScope(), KviKvsTreeNodeData::canEvaluateToObjectReference(), e, KviKvsKernel::findCoreFunctionExecRoutine(), KviKvsKernel::instance(), KVSP_ASSERT, KVSP_backChar, KVSP_curCharIsFunctionStart, KVSP_curCharIsLetter, KVSP_curCharIsNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_setCurCharPointer, KVSP_skipChar, parseDollar(), parseExpression(), parseHashKey(), parsePercent(), and skipSpaces().
Referenced by parseParameterPercentOrDollar(), parseSpecialCommandForeach(), and parseVoidFunctionCallOrOperation().
KviKvsTreeNodeConstantData* KviKvsParser::parseSingleLiteralParameterInParenthesis () [private]
KviKvsTreeNodeData* KviKvsParser::parseSingleParameterInParenthesis () [private]
Referenced by parseSpecialCommandDefpopup(), and parseSpecialCommandSwitch().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandBreak () [private]
References __tr2qs_ctx, KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_skipChar, and KviMessageBox::warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandClass () [private]
References __tr2qs_ctx, KviKvsTreeNodeSpecialCommandClass::addFunctionDefinition(), KviCommandFormatter::bufferFromBlock(), error(), errorBadChar(), KviKvsObjectFunctionHandler::Internal, KVSP_curCharIsEndOfBuffer, KVSP_curCharIsLetter, KVSP_curCharIsLetterOrNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommaSeparatedParameterList(), parseComment(), parseInstruction(), skipSpaces(), and skipSpacesAndNewlines().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandContinue () [private]
References __tr2qs_ctx, KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_skipChar, skipSpaces(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandDefpopup () [private]
References __tr2qs_ctx, errorBadChar(), KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseSingleParameterInParenthesis(), parseSpecialCommandDefpopupLabelPopup(), skipSpacesAndNewlines(), and warning().
Referenced by init().
KviKvsTreeNodeSpecialCommandDefpopupLabelPopup * KviKvsParser::parseSpecialCommandDefpopupLabelPopup () [private]
References __tr2qs_ctx, KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::addLabel(), KviCommandFormatter::bufferFromBlock(), error(), errorBadChar(), EXTRACT_POPUP_LABEL_CONDITION, EXTRACT_POPUP_LABEL_PARAMETERS, KviPointerList< T >::first(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsLetter, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, KviPointerList< T >::next(), parseInstruction(), KviKvsTreeNodeSpecialCommandDefpopupConditionalLabel::setCondition(), KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon::setIcon(), KviKvsTreeNodeSpecialCommandDefpopupLabel::setItemName(), KviKvsTreeNodeSpecialCommandDefpopupConditionalLabelWithTextAndIcon::setText(), skipSpacesAndNewlines(), and warning().
Referenced by parseSpecialCommandDefpopup().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandDo () [private]
References __tr2qs_ctx, e, error(), errorBadChar(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseExpression(), parseInstruction(), skipSpaces(), skipSpacesAndNewlines(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandFor () [private]
References __tr2qs_ctx, e, error(), errorBadChar(), KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_setCurCharPointer, KVSP_skipChar, parseExpression(), parseInstruction(), skipSpaces(), skipSpacesAndNewlines(), skipToEndOfForControlBlock(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandForeach () [private]
References __tr2qs_ctx, d, error(), errorBadChar(), KviKvsTreeNodeData::isFunctionCall(), KviKvsTreeNodeData::isReadOnly(), KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseCommaSeparatedParameterList(), parseInstruction(), parsePercentOrDollar(), skipSpaces(), skipSpacesAndNewlines(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandGlobal () [private]
References __tr2qs_ctx, error(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharIsLetterOrNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, m_pGlobals, KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), skipSpaces(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandHelp () [private]
References KviKvsTreeNodeDataList::addItem(), KviKvsKernel::findCoreSimpleCommandExecRoutine(), KviKvsKernel::instance(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_skipChar, and skipSpaces().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandIf () [private]
References __tr2qs_ctx, e, error(), errorBadChar(), KVSP_backChar, KVSP_curCharIsLetterOrNumber, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_setCurCharPointer, KVSP_skipChar, parseExpression(), parseInstruction(), skipSpacesAndNewlines(), and warning().
Referenced by init().
KviKvsTreeNodeCommand* KviKvsParser::parseSpecialCommandPerlBegin () [private]
Referenced by parseCommand().
KviKvsTreeNodeCommand* KviKvsParser::parseSpecialCommandPythonBegin () [private]
Referenced by parseCommand().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandSwitch () [private]
References __tr2qs_ctx, KviKvsTreeNodeSpecialCommandSwitch::addLabel(), e, error(), errorBadChar(), KviKvsTreeNodeSpecialCommandSwitch::isEmpty(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsLetter, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseExpression(), parseInstruction(), parseSingleParameterInParenthesis(), KviKvsTreeNodeSpecialCommandSwitchLabel::setInstruction(), KviKvsTreeNodeSpecialCommandSwitchLabel::setParameter(), KviKvsTreeNodeSpecialCommandSwitchLabel::setTerminatingBreak(), skipSpaces(), skipSpacesAndNewlines(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandUnset () [private]
References __tr2qs_ctx, KviPointerList< T >::append(), KviPointerList< T >::count(), d, error(), KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parsePercent(), KviPointerList< T >::setAutoDelete(), skipSpaces(), and warning().
Referenced by init().
KviKvsTreeNodeCommand * KviKvsParser::parseSpecialCommandWhile () [private]
References __tr2qs_ctx, e, error(), KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, parseExpression(), parseInstruction(), skipSpacesAndNewlines(), and warning().
Referenced by init().
KviKvsTreeNodeConstantData* KviKvsParser::parseStringLiteralParameter () [private]
KviKvsTreeNodeData* KviKvsParser::parseStringParameter () [private]
Referenced by parseBindingOperationParameter(), and parseExpressionOperandCore().
KviKvsTreeNodeInstruction * KviKvsParser::parseVoidFunctionCallOrOperation () [private]
References __tr2qs_ctx, error(), KviKvsTreeNodeData::isFunctionCall(), KviKvsTreeNodeData::isReadOnly(), KVSP_ASSERT, KVSP_curCharIsEndOfBuffer, KVSP_curCharIsEndOfCommand, KVSP_curCharPointer, KVSP_curCharUnicode, KVSP_skipChar, KviKvsTreeNode::location(), parseOperation(), parsePercentOrDollar(), KviKvsTreeNodeOperation::setTargetVariableReference(), skipSpaces(), and warning().
Referenced by parseInstruction().
void KviKvsParser::report (bool bError, const QChar * pLocation, const QString & szMsgFmt, kvi_va_list va) [private]
References __tr2qs_ctx, KviKvsReport::findLineColAndListing(), m_pBuffer, m_pScript, m_pWindow, KviKvsScript::name(), KviKvsReport::ParserError, KviKvsReport::ParserWarning, KviPointerList< T >::setAutoDelete(), KviQString::sprintf(), and KviQString::vsprintf().
Referenced by error(), and warning().
void KviKvsParser::skipSpaces () [private]
References KVSP_backChar, KVSP_curCharUnicode, and KVSP_skipChar.
Referenced by parseBindingOperation(), parseCommand(), parseCommandParameterList(), parseCommandSwitchList(), parseCommaSeparatedParameterList(), parseCommaSeparatedParameterListNoTree(), parseDollar(), parseExpression(), parseExpressionOperand(), parseExpressionOperandCore(), parseOperation(), parseOperationRightSide(), parsePercentOrDollar(), parseSpecialCommandClass(), parseSpecialCommandContinue(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandGlobal(), parseSpecialCommandHelp(), parseSpecialCommandSwitch(), parseSpecialCommandUnset(), and parseVoidFunctionCallOrOperation().
bool KviKvsParser::skipSpacesAndNewlines () [private]
References error(), KVSP_backChar, KVSP_curCharUnicode, KVSP_skipChar, and parseComment().
Referenced by parseCommand(), parseInstructionBlock(), parseInstructionList(), parseSpecialCommandClass(), parseSpecialCommandDefpopup(), parseSpecialCommandDefpopupLabelPopup(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandIf(), parseSpecialCommandSwitch(), and parseSpecialCommandWhile().
void KviKvsParser::skipToEndOfCStyleComment () [private]
bool KviKvsParser::skipToEndOfForControlBlock () [private]
References __tr2qs_ctx, error(), KVSP_ASSERT, KVSP_curCharPointer, KVSP_curCharUnicode, and KVSP_skipChar.
Referenced by parseSpecialCommandFor().
void KviKvsParser::skipToNextLine () [private]
References KVSP_curCharUnicode, and KVSP_skipChar.
Referenced by parseComment().
void KviKvsParser::warning (const QChar * pLocation, const QString & szMsgFmt, ...) [private]
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, and report().
Referenced by parseCommand(), parseCommandSwitchList(), parseComment(), parseDollar(), parseInstructionBlock(), parseOperation(), parseSpecialCommandContinue(), parseSpecialCommandDefpopup(), parseSpecialCommandDefpopupLabelPopup(), parseSpecialCommandDo(), parseSpecialCommandFor(), parseSpecialCommandForeach(), parseSpecialCommandGlobal(), parseSpecialCommandIf(), parseSpecialCommandSwitch(), parseSpecialCommandUnset(), parseSpecialCommandWhile(), and parseVoidFunctionCallOrOperation().
Friends And Related Function Documentation
friend class KviKvsKernel [friend]
Member Data Documentation
bool KviKvsParser::m_bError [private]
Referenced by error(), parse(), parseAsExpression(), and parseAsParameter().
int KviKvsParser::m_iFlags [private]
Referenced by parse(), parseAsExpression(), parseAsParameter(), and parsePercent().
const QChar* KviKvsParser::m_pBuffer [private]
Referenced by parse(), parseAsExpression(), parseAsParameter(), and report().
KviPointerHashTable<QString,QString>* KviKvsParser::m_pGlobals [private]
Referenced by KviKvsParser(), parse(), parseAsExpression(), parseAsParameter(), parsePercent(), parseSpecialCommandGlobal(), and ~KviKvsParser().
KviKvsScript* KviKvsParser::m_pScript [private]
Referenced by KviKvsParser(), and report().
const QChar* KviKvsParser::m_ptr [private]
Referenced by parse(), parseAsExpression(), and parseAsParameter().
KviWindow* KviKvsParser::m_pWindow [private]
Referenced by KviKvsParser(), and report().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser.cpp
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser_command.cpp
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser_comment.cpp
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser_dollar.cpp
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser_expression.cpp
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser_lside.cpp
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_parser_specialcommands.cpp