KVIrc: OptionsWidget_notifier Class Reference
OptionsWidget_notifier Class Reference
#include <OptionsWidget_notifier.h>
Public Member Functions
OptionsWidget_notifier (QWidget *parent)
~OptionsWidget_notifier ()
Constructor & Destructor Documentation
OptionsWidget_notifier::OptionsWidget_notifier (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolDontShowNotifierIfActiveWindowIsFullScreen, KviOption_boolEnableNotifier, KviOption_boolNotifierFading, KviOption_boolNotifierFlashing, KviOption_boolUseDBusNotifier, KviOption_boolUseKDENotifier, KviOption_uintNotifierActiveTransparency, KviOption_uintNotifierAutoHideTime, KviOption_uintNotifierInactiveTransparency, KviOptionsWidget::mergeTip(), and KviBoolSelector::setEnabled().
OptionsWidget_notifier::~OptionsWidget_notifier ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_notifier.h
src/modules/options/OptionsWidget_notifier.cpp