KVIrc: IrcNetworkDetailsWidget Class Reference
IrcNetworkDetailsWidget Class Reference
#include <OptionsWidget_servers.h>
Public Member Functions
void fillData (KviIrcNetwork *d)
IrcNetworkDetailsWidget (QWidget *par, KviIrcNetwork *d)
~IrcNetworkDetailsWidget ()
Protected Slots
void addNickServRule ()
void delNickServRule ()
void editNickServRule ()
void enableDisableNickServControls ()
Protected Attributes
QStringList m_lstChannels
QPushButton * m_pAddRuleButton
QLineEdit * m_pAlternativeNickEditor
QCheckBox * m_pAutoConnectCheck
KviChannelListSelector * m_pChannelListSelector
QPushButton * m_pDelRuleButton
QLineEdit * m_pDescEditor
QPushButton * m_pEditRuleButton
QComboBox * m_pEncodingEditor
QLineEdit * m_pNickEditor
QCheckBox * m_pNickServCheck
QTreeWidget * m_pNickServTreeWidget
KviScriptEditor * m_pOnConnectEditor
KviScriptEditor * m_pOnLoginEditor
KviPasswordLineEdit * m_pPassEditor
QLineEdit * m_pRealEditor
QComboBox * m_pTextEncodingEditor
QLineEdit * m_pUserEditor
Constructor & Destructor Documentation
IrcNetworkDetailsWidget::IrcNetworkDetailsWidget (QWidget * par, KviIrcNetwork * d)
References __tr2qs_ctx(), KviTalToolTip::add(), addNickServRule(), KviIrcNetwork::alternativeNickName(), KviIrcNetwork::autoConnect(), KviIrcNetwork::autoJoinChannelList(), connect(), KviScriptEditor::createInstance(), d, delNickServRule(), KviIrcNetwork::description(), editNickServRule(), enableDisableNickServControls(), KviIrcNetwork::encoding(), KviLocale::encodingDescription(), KviQString::equalCI(), KviPointerList< T >::first(), g, g_pIconManager, KviIconManager::getSmallIcon(), i, KviLocale::instance(), KviNickServRuleSet::isEmpty(), KviNickServRuleSet::isEnabled(), l, m_lstChannels, m_pAddRuleButton, m_pAlternativeNickEditor, m_pAutoConnectCheck, m_pChannelListSelector, m_pDelRuleButton, m_pDescEditor, m_pEditRuleButton, m_pEncodingEditor, m_pNickEditor, m_pNickServCheck, m_pNickServTreeWidget, m_pOnConnectEditor, m_pOnLoginEditor, m_pPassEditor, m_pRealEditor, m_pTextEncodingEditor, m_pUserEditor, KviIrcNetwork::name(), KviPointerList< T >::next(), KviIrcNetwork::nickName(), KviIrcNetwork::nickServRuleSet(), NULL, KviIrcNetwork::onConnectCommand(), KviIrcNetwork::onLoginCommand(), KviIrcNetwork::password(), KviLocale::_EncodingDescription::pcDescription, KviLocale::_EncodingDescription::pcName, KviIrcNetwork::realName(), KviNickServRuleSet::rules(), KviTalGroupBox::setLayout(), KviScriptEditor::setText(), KviPasswordLineEdit::setText(), KviIrcNetwork::textEncoding(), KviIrcNetwork::userName(), v, and KviIconManager::World.
IrcNetworkDetailsWidget::~IrcNetworkDetailsWidget ()
References KviScriptEditor::destroyInstance(), m_pOnConnectEditor, and m_pOnLoginEditor.
Member Function Documentation
void IrcNetworkDetailsWidget::addNickServRule () [protected, slot]
References NickServRuleEditor::editRule(), KviNickServRule::identifyCommand(), m_pNickServTreeWidget, KviNickServRule::messageRegexp(), KviNickServRule::nickServMask(), r, and KviNickServRule::registeredNick().
Referenced by IrcNetworkDetailsWidget().
void IrcNetworkDetailsWidget::delNickServRule () [protected, slot]
References enableDisableNickServControls(), and m_pNickServTreeWidget.
Referenced by IrcNetworkDetailsWidget().
void IrcNetworkDetailsWidget::editNickServRule () [protected, slot]
References m_pNickServTreeWidget, and r.
Referenced by IrcNetworkDetailsWidget().
void IrcNetworkDetailsWidget::enableDisableNickServControls () [protected, slot]
References m_pAddRuleButton, m_pDelRuleButton, m_pEditRuleButton, m_pNickServCheck, and m_pNickServTreeWidget.
Referenced by delNickServRule(), and IrcNetworkDetailsWidget().
void IrcNetworkDetailsWidget::fillData (KviIrcNetwork * d)
References KviNickServRuleSet::addRule(), KviChannelListSelector::commit(), KviNickServRule::createInstance(), KviNickServRuleSet::createInstance(), d, KviLocale::encodingDescription(), KviScriptEditor::getText(), i, KviLocale::instance(), m_lstChannels, m_pAlternativeNickEditor, m_pAutoConnectCheck, m_pChannelListSelector, m_pDescEditor, m_pEncodingEditor, m_pNickEditor, m_pNickServCheck, m_pNickServTreeWidget, m_pOnConnectEditor, m_pOnLoginEditor, m_pPassEditor, m_pRealEditor, m_pTextEncodingEditor, m_pUserEditor, KviLocale::_EncodingDescription::pcName, KviIrcNetwork::setAlternativeNickName(), KviIrcNetwork::setAutoConnect(), KviIrcNetwork::setAutoJoinChannelList(), KviIrcNetwork::setDescription(), KviNickServRuleSet::setEnabled(), KviIrcNetwork::setEncoding(), KviIrcNetwork::setNickName(), KviIrcNetwork::setNickServRuleSet(), KviIrcNetwork::setOnConnectCommand(), KviIrcNetwork::setOnLoginCommand(), KviIrcNetwork::setPassword(), KviIrcNetwork::setRealName(), KviIrcNetwork::setTextEncoding(), KviIrcNetwork::setUserName(), and KviPasswordLineEdit::text().
Referenced by OptionsWidget_servers::detailsClicked().
Member Data Documentation
QStringList IrcNetworkDetailsWidget::m_lstChannels [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QPushButton* IrcNetworkDetailsWidget::m_pAddRuleButton [protected]
Referenced by enableDisableNickServControls(), and IrcNetworkDetailsWidget().
QLineEdit* IrcNetworkDetailsWidget::m_pAlternativeNickEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QCheckBox* IrcNetworkDetailsWidget::m_pAutoConnectCheck [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
KviChannelListSelector* IrcNetworkDetailsWidget::m_pChannelListSelector [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QPushButton* IrcNetworkDetailsWidget::m_pDelRuleButton [protected]
Referenced by enableDisableNickServControls(), and IrcNetworkDetailsWidget().
QLineEdit* IrcNetworkDetailsWidget::m_pDescEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QPushButton* IrcNetworkDetailsWidget::m_pEditRuleButton [protected]
Referenced by enableDisableNickServControls(), and IrcNetworkDetailsWidget().
QComboBox* IrcNetworkDetailsWidget::m_pEncodingEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QLineEdit* IrcNetworkDetailsWidget::m_pNickEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QCheckBox* IrcNetworkDetailsWidget::m_pNickServCheck [protected]
Referenced by enableDisableNickServControls(), fillData(), and IrcNetworkDetailsWidget().
QTreeWidget* IrcNetworkDetailsWidget::m_pNickServTreeWidget [protected]
Referenced by addNickServRule(), delNickServRule(), editNickServRule(), enableDisableNickServControls(), fillData(), and IrcNetworkDetailsWidget().
KviScriptEditor* IrcNetworkDetailsWidget::m_pOnConnectEditor [protected]
Referenced by fillData(), IrcNetworkDetailsWidget(), and ~IrcNetworkDetailsWidget().
KviScriptEditor* IrcNetworkDetailsWidget::m_pOnLoginEditor [protected]
Referenced by fillData(), IrcNetworkDetailsWidget(), and ~IrcNetworkDetailsWidget().
KviPasswordLineEdit* IrcNetworkDetailsWidget::m_pPassEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QLineEdit* IrcNetworkDetailsWidget::m_pRealEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QComboBox* IrcNetworkDetailsWidget::m_pTextEncodingEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
QLineEdit* IrcNetworkDetailsWidget::m_pUserEditor [protected]
Referenced by fillData(), and IrcNetworkDetailsWidget().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_servers.h
src/modules/options/OptionsWidget_servers.cpp