KVIrc: KviFileTransfer Class Reference
KviFileTransfer Class Reference
#include <KviFileTransfer.h>
Public Member Functions
virtual bool active ()=0
virtual void die ()
virtual int displayHeight (int iLineSpacing)
virtual void displayPaint (QPainter *p, int column, QRect rect)=0
void displayUpdate ()
virtual void fillContextPopup (KviTalPopupMenu *m)=0
int id ()
void invokeTransferWindow (KviWindow *pWnd=0, bool bCreateMinimized=false, bool bNoRaise=false)
KviFileTransfer ()
virtual QString localFileName ()
KviFileTransferManager * manager ()
KviWindow * outputWindow ()
virtual QString retryCommand ()
void setDisplayItem (KviTalTableWidgetItemEx *i)
bool terminated ()
virtual QString tipText ()
KviWindow * transferWindow ()
~KviFileTransfer ()
Protected Attributes
int m_iId
KviTalTableWidgetItemEx * m_pDisplayItem
Constructor & Destructor Documentation
KviFileTransfer::KviFileTransfer ()
References g_pApp, KviApplication::getGloballyUniqueId(), m_iId, m_pDisplayItem, manager(), and KviFileTransferManager::registerTransfer().
KviFileTransfer::~KviFileTransfer ()
References manager(), and KviFileTransferManager::unregisterTransfer().
Member Function Documentation
virtual bool KviFileTransfer::active () [pure virtual]
Implemented in DccFileTransfer, and HttpFileTransfer.
Referenced by FileTransferWindow::heartbeat(), FileTransferItemDelegate::paint(), and terminated().
void KviFileTransfer::die () [virtual]
References m_pDisplayItem.
Referenced by HttpFileTransfer::autoClean(), DccFileTransfer::event(), and KviFileTransferManager::killAllTransfers().
int KviFileTransfer::displayHeight (int iLineSpacing) [virtual]
Reimplemented in DccFileTransfer, and HttpFileTransfer.
virtual void KviFileTransfer::displayPaint (QPainter * p, int column, QRect rect) [pure virtual]
Implemented in DccFileTransfer, and HttpFileTransfer.
Referenced by FileTransferItemDelegate::paint().
void KviFileTransfer::displayUpdate ()
References KviTalTableWidgetItemEx::displayUpdate(), and m_pDisplayItem.
Referenced by DccFileTransfer::abort(), DccFileTransfer::connected(), HttpFileTransfer::connectionEstabilished(), DccFileTransfer::connectionInProgress(), HttpFileTransfer::contactingHost(), DccFileTransfer::event(), DccFileTransfer::handleMarshalError(), DccFileTransfer::listenOrConnect(), HttpFileTransfer::receivedResponse(), HttpFileTransfer::requestSent(), HttpFileTransfer::resolvingHost(), DccFileTransfer::startConnection(), and HttpFileTransfer::transferTerminated().
virtual void KviFileTransfer::fillContextPopup (KviTalPopupMenu * m) [pure virtual]
Implemented in DccFileTransfer, and HttpFileTransfer.
Referenced by FileTransferWindow::rightButtonPressed().
int KviFileTransfer::id () [inline]
References m_iId.
Referenced by DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog(), and FileTransferItem::key().
void KviFileTransfer::invokeTransferWindow (KviWindow * pWnd = 0, bool bCreateMinimized = false, bool bNoRaise = false)
References KviFileTransferManager::invokeTransferWindow(), and manager().
Referenced by http_kvs_complete_get(), DccBroker::recvFileExecute(), and DccBroker::sendFileExecute().
QString KviFileTransfer::localFileName () [virtual]
Reimplemented in DccFileTransfer, and HttpFileTransfer.
Referenced by FileTransferWindow::copyLocalFileToClipboard(), FileTransferWindow::deleteLocalFile(), FileTransferWindow::openFilePopupActivated(), FileTransferWindow::openLocalFile(), FileTransferWindow::openLocalFileFolder(), FileTransferWindow::openLocalFileTerminal(), FileTransferWindow::openLocalFileWith(), and FileTransferWindow::rightButtonPressed().
KviFileTransferManager* KviFileTransfer::manager () [inline]
References KviFileTransferManager::instance().
Referenced by invokeTransferWindow(), KviFileTransfer(), and ~KviFileTransfer().
KviWindow * KviFileTransfer::outputWindow ()
References g_pActiveWindow, o, and transferWindow().
QString KviFileTransfer::retryCommand () [virtual]
void KviFileTransfer::setDisplayItem (KviTalTableWidgetItemEx * i) [inline]
References i.
Referenced by FileTransferItem::FileTransferItem(), and FileTransferItem::~FileTransferItem().
bool KviFileTransfer::terminated ()
References active().
Referenced by FileTransferWindow::clearAll(), HttpFileTransfer::HttpFileTransfer(), and FileTransferWindow::rightButtonPressed().
QString KviFileTransfer::tipText () [virtual]
Reimplemented in DccFileTransfer, and HttpFileTransfer.
Referenced by FileTransferWindow::tipRequest().
KviWindow* KviFileTransfer::transferWindow () [inline]
Referenced by DccFileTransfer::dccMarshalOutputWindow(), DccFileTransfer::eventWindow(), HttpFileTransfer::headersReceived(), DccFileTransfer::outputAndLog(), outputWindow(), HttpFileTransfer::requestSent(), HttpFileTransfer::statusMessage(), and HttpFileTransfer::transferTerminated().
Member Data Documentation
int KviFileTransfer::m_iId [protected]
Referenced by KviFileTransfer().
KviTalTableWidgetItemEx* KviFileTransfer::m_pDisplayItem [protected]
Referenced by die(), displayUpdate(), and KviFileTransfer().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviFileTransfer.h
src/kvirc/kernel/KviFileTransfer.cpp