KVIrc: CustomizeToolBarsDialog Class Reference
CustomizeToolBarsDialog Class Reference
#include <CustomizeToolBarsDialog.h>
Public Member Functions
~CustomizeToolBarsDialog ()
Static Public Member Functions
static void cleanup ()
static void display (bool bTopLevel)
static CustomizeToolBarsDialog * instance ()
Protected Slots
void closeClicked ()
void currentToolBarChanged ()
void deleteToolBar ()
void exportToolBar ()
void newToolBar ()
virtual void reject ()
void renameToolBar ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
CustomizeToolBarsDialog (QWidget *p)
virtual void showEvent (QShowEvent *e)
Protected Attributes
QPushButton * m_pDeleteToolBarButton
KviActionDrawer * m_pDrawer
QPushButton * m_pExportToolBarButton
QPushButton * m_pRenameToolBarButton
Static Protected Attributes
static CustomizeToolBarsDialog * m_pInstance = 0
Constructor & Destructor Documentation
CustomizeToolBarsDialog::CustomizeToolBarsDialog (QWidget * p) [protected]
References __tr2qs_ctx(), closeClicked(), connect(), currentToolBarChanged(), deleteToolBar(), exportToolBar(), f, KviActionDrawer::fill(), g, g_pIconManager, g_rectToolBarEditorDialogGeometry, KviIconManager::getSmallIcon(), instance(), KviActionManager::instance(), m_pDeleteToolBarButton, m_pDrawer, m_pExportToolBarButton, m_pInstance, m_pRenameToolBarButton, KviMemory::move(), newToolBar(), renameToolBar(), t, and KviIconManager::ToolBar.
Referenced by display().
CustomizeToolBarsDialog::~CustomizeToolBarsDialog ()
References g_rectToolBarEditorDialogGeometry, instance(), m_pInstance, x, and y.
Member Function Documentation
void CustomizeToolBarsDialog::cleanup () [static]
References m_pInstance.
Referenced by reject(), and toolbareditor_module_cleanup().
void CustomizeToolBarsDialog::closeClicked () [protected, slot]
Referenced by CustomizeToolBarsDialog().
void CustomizeToolBarsDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void CustomizeToolBarsDialog::currentToolBarChanged () [protected, slot]
References KviActionManager::instance(), m_pDeleteToolBarButton, and m_pRenameToolBarButton.
Referenced by CustomizeToolBarsDialog().
void CustomizeToolBarsDialog::deleteToolBar () [protected, slot]
References __tr2qs_ctx(), KviActionManager::currentToolBar(), KviCustomToolBar::descriptor(), KviCustomToolBarDescriptor::id(), instance(), and t.
Referenced by CustomizeToolBarsDialog().
void CustomizeToolBarsDialog::display (bool bTopLevel) [static]
References CustomizeToolBarsDialog(), g_pMainWindow, m_pInstance, and KviMainWindow::splitter().
Referenced by toolbareditor_kvs_cmd_open().
void CustomizeToolBarsDialog::exportToolBar () [protected, slot]
References __tr2qs_ctx(), a, KviCustomToolBarDescriptor::actions(), KviFileDialog::askForSaveFileName(), KviActionManager::currentToolBar(), KviCustomToolBar::descriptor(), KviPointerList< T >::first(), KviCustomToolBarDescriptor::iconId(), KviCustomToolBarDescriptor::id(), instance(), KviAction::isKviUserActionNeverOverrideThis(), KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, KviCustomToolBarDescriptor::labelCode(), KviPointerList< T >::next(), s, t, KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by CustomizeToolBarsDialog().
static CustomizeToolBarsDialog* CustomizeToolBarsDialog::instance () [inline, static]
References m_pInstance.
Referenced by CustomizeToolBarsDialog(), deleteToolBar(), exportToolBar(), newToolBar(), renameToolBar(), toolbareditor_module_can_unload(), and ~CustomizeToolBarsDialog().
void CustomizeToolBarsDialog::newToolBar () [protected, slot]
References __tr2qs_ctx(), KviCustomToolBarDescriptor::createToolBar(), d, CustomToolBarPropertiesDialog::iconId(), CustomToolBarPropertiesDialog::id(), instance(), KviCustomToolBarManager::instance(), CustomToolBarPropertiesDialog::label(), KviCustomToolBarDescriptor::setIconId(), and t.
Referenced by CustomizeToolBarsDialog().
void CustomizeToolBarsDialog::reject () [protected, virtual, slot]
References cleanup().
void CustomizeToolBarsDialog::renameToolBar () [protected, slot]
References __tr2qs_ctx(), KviActionManager::currentToolBar(), KviCustomToolBar::descriptor(), CustomToolBarPropertiesDialog::iconId(), KviCustomToolBarDescriptor::iconId(), CustomToolBarPropertiesDialog::id(), KviCustomToolBarDescriptor::id(), instance(), CustomToolBarPropertiesDialog::label(), KviCustomToolBarDescriptor::labelCode(), KviCustomToolBarDescriptor::setIconId(), and t.
Referenced by CustomizeToolBarsDialog().
void CustomizeToolBarsDialog::showEvent (QShowEvent * e) [protected, virtual]
References g_pApp, and KviMemory::move().
Member Data Documentation
QPushButton* CustomizeToolBarsDialog::m_pDeleteToolBarButton [protected]
Referenced by currentToolBarChanged(), and CustomizeToolBarsDialog().
KviActionDrawer* CustomizeToolBarsDialog::m_pDrawer [protected]
Referenced by CustomizeToolBarsDialog().
QPushButton* CustomizeToolBarsDialog::m_pExportToolBarButton [protected]
Referenced by CustomizeToolBarsDialog().
CustomizeToolBarsDialog * CustomizeToolBarsDialog::m_pInstance = 0 [static, protected]
Referenced by cleanup(), CustomizeToolBarsDialog(), display(), instance(), and ~CustomizeToolBarsDialog().
QPushButton* CustomizeToolBarsDialog::m_pRenameToolBarButton [protected]
Referenced by currentToolBarChanged(), and CustomizeToolBarsDialog().
The documentation for this class was generated from the following files:
src/modules/toolbareditor/CustomizeToolBarsDialog.h
src/modules/toolbareditor/CustomizeToolBarsDialog.cpp