KVIrc: KviKvsTreeNodeOperationStringTransliteration Class Reference
KviKvsTreeNodeOperationStringTransliteration Class Reference
#include <KviKvsTreeNodeOperation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationStringTransliteration (const QChar *pLocation, KviKvsTreeNodeData *pLeft, KviKvsTreeNodeData *pRight, KviKvsTreeNodeData *pFlags)
~KviKvsTreeNodeOperationStringTransliteration ()
Public Member Functions inherited from KviKvsTreeNodeOperation
KviKvsTreeNodeOperation (const QChar *pLocation)
void setTargetVariableReference (KviKvsTreeNodeData *r)
~KviKvsTreeNodeOperation ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeData * m_pFlags
KviKvsTreeNodeData * m_pLeft
KviKvsTreeNodeData * m_pRight
Protected Attributes inherited from KviKvsTreeNodeOperation
KviKvsTreeNodeData * m_pTargetData
Constructor & Destructor Documentation
KviKvsTreeNodeOperationStringTransliteration::KviKvsTreeNodeOperationStringTransliteration (const QChar * pLocation, KviKvsTreeNodeData * pLeft, KviKvsTreeNodeData * pRight, KviKvsTreeNodeData * pFlags)
References m_pFlags, m_pLeft, m_pRight, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationStringTransliteration::~KviKvsTreeNodeOperationStringTransliteration ()
References m_pFlags, m_pLeft, and m_pRight.
Member Function Documentation
void KviKvsTreeNodeOperationStringTransliteration::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationStringTransliteration::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pFlags, m_pLeft, and m_pRight.
bool KviKvsTreeNodeOperationStringTransliteration::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariant::asString(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), m_pLeft, m_pRight, KviKvsTreeNodeOperation::m_pTargetData, KviKvsRWEvaluationResult::result(), KviKvsVariant::setString(), szR, and KviQString::transliterate().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringTransliteration::m_pFlags protected
Referenced by dump(), KviKvsTreeNodeOperationStringTransliteration(), and ~KviKvsTreeNodeOperationStringTransliteration().
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringTransliteration::m_pLeft protected
Referenced by dump(), execute(), KviKvsTreeNodeOperationStringTransliteration(), and ~KviKvsTreeNodeOperationStringTransliteration().
KviKvsTreeNodeData* KviKvsTreeNodeOperationStringTransliteration::m_pRight protected
Referenced by dump(), execute(), KviKvsTreeNodeOperationStringTransliteration(), and ~KviKvsTreeNodeOperationStringTransliteration().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.h
src/kvirc/kvs/tree/KviKvsTreeNodeOperation.cpp