KVIrc: KviConnectToServerAction Class Reference
KviConnectToServerAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
KviConnectToServerAction (QObject *pParent)
Protected Slots
void popupAboutToShow ()
void popupActivated (int)
Constructor & Destructor Documentation
KviConnectToServerAction::KviConnectToServerAction (QObject * pParent)
Member Function Documentation
void KviConnectToServerAction::popupAboutToShow () [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References __tr2qs, KviApplication::fillRecentServersPopup(), g_pApp, g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KviSubmenuAction::m_pPopup, and KviIconManager::Server.
void KviConnectToServerAction::popupActivated (int id) [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References __tr2qs, KviKvsAction::activate(), c, KviWindow::console(), g_pActiveWindow, KVI_IRCURL_CONTEXT_FIRSTFREE, KviSubmenuAction::m_pPopup, KviIrcUrl::parse(), KviCString::ptr(), KviIrcUrl::run(), and KviTalPopupMenu::text().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp