KVIrc: SharedFilesWindow Class Reference
SharedFilesWindow Class Reference
#include <SharedFilesWindow.h>
Public Member Functions
virtual void die ()
SharedFilesWindow (KviModuleExtensionDescriptor *d)
virtual QSize sizeHint () const
~SharedFilesWindow ()
Protected Slots
void addClicked ()
void editClicked ()
void enableButtons ()
void fillFileView ()
void removeClicked ()
void sharedFileAdded (KviSharedFile *f)
void sharedFileRemoved (KviSharedFile *f)
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &buffer)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
Protected Attributes
QPushButton * m_pAddButton
QPushButton * m_pEditButton
QPushButton * m_pRemoveButton
KviThemedTreeWidget * m_pTreeWidget
QSplitter * m_pVertSplitter
Friends
class KviSharedFilesItem
Constructor & Destructor Documentation
SharedFilesWindow::SharedFilesWindow (KviModuleExtensionDescriptor * d)
References __tr2qs_ctx(), addClicked(), connect(), editClicked(), enableButtons(), fillFileView(), g_pSharedFilesManager, KviTalSplitter, m_pAddButton, m_pEditButton, m_pRemoveButton, KviWindow::m_pSplitter, m_pTreeWidget, removeClicked(), sharedFileAdded(), and sharedFileRemoved().
SharedFilesWindow::~SharedFilesWindow ()
Member Function Documentation
void SharedFilesWindow::addClicked () [protected, slot]
References KviSharedFilesManager::addSharedFile(), f, g_pSharedFilesManager, and SharedFileEditDialog::getResult().
Referenced by SharedFilesWindow().
void SharedFilesWindow::die () [virtual]
Implements KviModuleExtension.
void SharedFilesWindow::editClicked () [protected, slot]
References KviSharedFilesManager::addSharedFile(), f, g_pSharedFilesManager, m_pTreeWidget, KviSharedFile::name(), SharedFilesTreeWidgetItem::readOnlySharedFilePointer(), and KviSharedFilesManager::removeSharedFile().
Referenced by SharedFilesWindow().
void SharedFilesWindow::enableButtons () [protected, slot]
References m_pEditButton, m_pRemoveButton, and m_pTreeWidget.
Referenced by fillFileView(), sharedFileAdded(), sharedFileRemoved(), and SharedFilesWindow().
void SharedFilesWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs_ctx(), and KviWindow::m_szPlainTextCaption.
void SharedFilesWindow::fillFileView () [protected, slot]
References KviPointerHashTableIterator< Key, T >::current(), enableButtons(), g_pSharedFilesManager, l, m_pTreeWidget, o, and KviSharedFilesManager::sharedFileListDict().
Referenced by SharedFilesWindow().
void SharedFilesWindow::getBaseLogFileName (QString & buffer) [protected, virtual]
Reimplemented from KviWindow.
QPixmap * SharedFilesWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::SharedFiles.
void SharedFilesWindow::removeClicked () [protected, slot]
References g_pSharedFilesManager, m_pTreeWidget, KviSharedFile::name(), SharedFilesTreeWidgetItem::readOnlySharedFilePointer(), and KviSharedFilesManager::removeSharedFile().
Referenced by SharedFilesWindow().
void SharedFilesWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviWindow::m_pSplitter.
void SharedFilesWindow::sharedFileAdded (KviSharedFile * f) [protected, slot]
References enableButtons(), and m_pTreeWidget.
Referenced by SharedFilesWindow().
void SharedFilesWindow::sharedFileRemoved (KviSharedFile * f) [protected, slot]
References enableButtons(), i, and m_pTreeWidget.
Referenced by SharedFilesWindow().
QSize SharedFilesWindow::sizeHint () const [virtual]
References KviWindow::m_pSplitter.
Friends And Related Function Documentation
friend class KviSharedFilesItem [friend]
Member Data Documentation
QPushButton* SharedFilesWindow::m_pAddButton [protected]
Referenced by SharedFilesWindow().
QPushButton* SharedFilesWindow::m_pEditButton [protected]
Referenced by enableButtons(), and SharedFilesWindow().
QPushButton* SharedFilesWindow::m_pRemoveButton [protected]
Referenced by enableButtons(), and SharedFilesWindow().
KviThemedTreeWidget* SharedFilesWindow::m_pTreeWidget [protected]
Referenced by editClicked(), enableButtons(), fillFileView(), removeClicked(), sharedFileAdded(), sharedFileRemoved(), and SharedFilesWindow().
QSplitter* SharedFilesWindow::m_pVertSplitter [protected]
The documentation for this class was generated from the following files:
src/modules/sharedfileswindow/SharedFilesWindow.h
src/modules/sharedfileswindow/SharedFilesWindow.cpp