KVIrc: KviIrcLink Class Reference
KviIrcLink Class Reference
Middle stack class for IRC connection.
#include <KviIrcLink.h>
Public Types
enum State { Idle, Connecting, Connected }
Signals
void connectionFailed ()
Emitted when the connection attempt has failed.
Public Member Functions
KviIrcConnection * connection ()
Returns the connection object.
KviConsoleWindow * console ()
Returns the console.
KviIrcSocket * socket ()
Returns the socket.
State state ()
Returns the state of the socket.
Protected Slots
void linkFilterDestroyed ()
Called when the link filter has been destroyed without permission :D.
Protected Member Functions
void abort ()
Aborts any connection or attempt.
virtual void clearOutputQueue (bool bPrivateMessagesOnly)
Clears the output queue.
KviIrcLink (KviIrcConnection *pConnection)
Constructs the IrcLink object.
unsigned int outputQueueSize ()
Returns the current size of the output queue.
void processData (char *buffer, int iLength)
Process a packet of raw data from the server.
virtual bool sendPacket (KviDataBuffer *pData)
Sends a data packet.
void socketStateChange ()
Called at each state change.
void start ()
Starts a connection attempt.
~KviIrcLink ()
Destroys the IrcLink object.
Private Slots
void resolverTerminated ()
Called when the DNS lookup has terminated.
Private Member Functions
void createSocket (const QString &szLinkFilterName)
Creates the socket.
void destroySocket ()
Destroys the socket.
Private Attributes
State m_eState
KviIrcConnection * m_pConnection
KviConsoleWindow * m_pConsole
KviMexLinkFilter * m_pLinkFilter
char * m_pReadBuffer
KviIrcConnectionTargetResolver * m_pResolver
KviIrcSocket * m_pSocket
KviIrcConnectionTarget * m_pTarget
unsigned int m_uReadBufferLen
unsigned int m_uReadPackets
Friends
class KviIrcConnection
class KviIrcSocket
Detailed Description
Middle stack class for IRC connection.
This class gets data from KviIrcSocket and pass it to KviIrcConnection
Member Enumeration Documentation
enum KviIrcLink::State
Enumerator:
Idle
Socket idling
Connecting
Socket connecting
Connected
Socket connected
Constructor & Destructor Documentation
KviIrcLink::KviIrcLink (KviIrcConnection * pConnection) protected
Constructs the IrcLink object.
Only KviConsoleWindow can create this. pConsole must NOT be null; pServer is a shallow pointer: Connection makes a copy of it internally, must NOT be null; pProxy may be null if a proxy is not desired. Connection makes a copy of it internally;
Parameters:
pConnection The pointer to the KviIrcConnection class
Returns:
KviIrcLink
References KviIrcConnection::console(), Idle, m_eState, m_pConnection, m_pConsole, m_pLinkFilter, m_pReadBuffer, m_pResolver, m_pSocket, m_pTarget, m_uReadBufferLen, m_uReadPackets, and KviIrcConnection::target().
KviIrcLink::~KviIrcLink () protected
Destroys the IrcLink object.
References destroySocket(), KviMemory::free(), m_pReadBuffer, and m_pResolver.
Member Function Documentation
void KviIrcLink::abort () protected
Aborts any connection or attempt.
Returns:
void
References KviIrcConnectionTargetResolver::abort(), KviIrcSocket::abort(), m_pResolver, and m_pSocket.
Referenced by KviIrcConnection::abort().
void KviIrcLink::clearOutputQueue (bool bPrivateMessagesOnly) protected virtual
Clears the output queue.
Requests to clear the underlying packet queue.
References KviMexLinkFilter::clearOutputQueue(), KviIrcSocket::clearOutputQueue(), m_pLinkFilter, and m_pSocket.
Referenced by KviIrcConnection::clearOutputQueue().
KviIrcConnection* KviIrcLink::connection () inline
Returns the connection object.
Never null
Returns:
KviIrcConnection *
Referenced by socketStateChange().
void KviIrcLink::connectionFailed () signal
Emitted when the connection attempt has failed.
Returns:
void
KviConsoleWindow* KviIrcLink::console () inline
Returns the console.
Never null
Returns:
KviConsoleWindow *
References KviIrcSocket::m_pConsole.
Referenced by KviIrcSocket::KviIrcSocket().
void KviIrcLink::createSocket (const QString & szLinkFilterName) private
Creates the socket.
Parameters:
szLinkFilterName The source linkfilter name
Returns:
void
References __tr2qs, KviModuleExtensionManager::allocateExtension(), connect(), destroySocket(), KviQString::equalCI(), g_pModuleExtensionManager, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviIrcSocket, linkFilterDestroyed(), m_pConsole, m_pLinkFilter, m_pSocket, and KviWindow::output().
Referenced by resolverTerminated().
void KviIrcLink::destroySocket () private
Destroys the socket.
Returns:
void
References KviModuleExtension::die(), m_pLinkFilter, and m_pSocket.
Referenced by createSocket(), and ~KviIrcLink().
void KviIrcLink::linkFilterDestroyed () protected slot
Called when the link filter has been destroyed without permission :D.
This should NEVER happen (?) This is part of the KviIrcSocket management
Returns:
void
References __tr2qs, KVI_OUT_SYSTEMWARNING, m_pConsole, m_pLinkFilter, and KviWindow::output().
Referenced by createSocket().
unsigned int KviIrcLink::outputQueueSize () protected
Returns the current size of the output queue.
Returns:
unsigned int
References m_pLinkFilter, m_pSocket, KviMexLinkFilter::outputQueueSize(), and KviIrcSocket::outputQueueSize().
Referenced by KviIrcConnection::outputQueueSize().
void KviIrcLink::processData (char * buffer, int iLength) protected
Process a packet of raw data from the server.
This is called by KviIrcSocket. The buffer is iLength+1 bytes long and contains a null terminator It's an interface for KviIrcSocket (lower protocol in stack)
Parameters:
buffer The buffer :)
iLength The length of the buffer
Returns:
void
References KviMemory::allocate(), Connected, KviMemory::free(), KviIrcConnection::incomingMessage(), KVI_ASSERT, m_pConnection, m_pLinkFilter, m_pReadBuffer, m_pSocket, m_uReadBufferLen, m_uReadPackets, KviMemory::move(), p, KviMexLinkFilter::processData(), KviMemory::reallocate(), and KviIrcSocket::state().
Referenced by KviIrcSocket::readData().
void KviIrcLink::resolverTerminated () private slot
Called when the DNS lookup has terminated.
Returns:
void
References __tr2qs, KviIrcConnectionTarget::bindAddress(), createSocket(), KviError::getDescription(), Idle, KVI_OUT_SYSTEMERROR, KviIrcConnectionTargetResolver::lastError(), KviIrcConnection::linkAttemptFailed(), KviIrcServer::linkFilter(), m_eState, m_pConnection, m_pConsole, m_pResolver, m_pSocket, m_pTarget, KviWindow::output(), KviIrcConnectionTarget::proxy(), KviIrcConnectionTarget::server(), KviIrcSocket::startConnection(), KviIrcConnectionTargetResolver::status(), and KviError::Success.
Referenced by start().
bool KviIrcLink::sendPacket (KviDataBuffer * pData) protected virtual
Sends a data packet.
This is used by KviIrcConnection::send*() This should be used to intercept the outgoing packets when implementing a new protocol. It's an interface for KviIrcConnection (upper protocol in stack)
Parameters:
pData The pointer to the data packet
Returns:
bool
References m_pLinkFilter, m_pSocket, KviMexLinkFilter::sendPacket(), and KviIrcSocket::sendPacket().
Referenced by KviIrcConnection::sendData(), and KviIrcConnection::sendFmtData().
KviIrcSocket* KviIrcLink::socket () inline
Returns the socket.
May be null!
Returns:
KviIrcSocket *
References m_pSocket.
Referenced by context_kvs_fnc_getSSLCertInfo(), dcc_kvs_get_listen_ip_address(), and socketStateChange().
void KviIrcLink::socketStateChange () protected
Called at each state change.
Returns:
void
References __tr2qs, Connected, KviIrcSocket::Connected, Connecting, KviIrcSocket::Connecting, connection(), Idle, KviIrcSocket::Idle, KVI_OUT_CONNECTION, KviIrcSocket::lastError(), KviIrcConnection::linkAttemptFailed(), KviIrcConnection::linkEstabilished(), KviIrcConnection::linkTerminated(), m_eState, m_pConnection, m_pConsole, m_pSocket, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcSocket::ProxyFinalHttp, KviIrcSocket::ProxyFinalV4, KviIrcSocket::ProxyFinalV5, KviIrcSocket::ProxyLogin, KviIrcSocket::ProxySelectAuthMethodV5, KviIrcSocket::ProxyUserPassV5, socket(), KviIrcSocket::SSLHandshake, and KviIrcSocket::state().
Referenced by KviIrcSocket::setState().
void KviIrcLink::start () protected
Starts a connection attempt.
It starts the server or proxy DNS lookup. The function MUST be asynchronous: it must return successfully and report any error by using m_pConnection->linkAttemptFailed() It's called internally and it's overridable
Returns:
void
References connect(), Connecting, m_eState, m_pConnection, m_pResolver, m_pTarget, resolverTerminated(), and KviIrcConnectionTargetResolver::start().
Referenced by KviIrcConnection::start().
State KviIrcLink::state () inline
Returns the state of the socket.
Returns:
State
Friends And Related Function Documentation
friend class KviIrcConnection friend
friend class KviIrcSocket friend
Referenced by createSocket().
Member Data Documentation
State KviIrcLink::m_eState private
Referenced by KviIrcLink(), resolverTerminated(), socketStateChange(), and start().
KviIrcConnection* KviIrcLink::m_pConnection private
Referenced by KviIrcLink(), processData(), resolverTerminated(), socketStateChange(), and start().
KviConsoleWindow* KviIrcLink::m_pConsole private
Referenced by createSocket(), KviIrcLink(), linkFilterDestroyed(), resolverTerminated(), and socketStateChange().
KviMexLinkFilter* KviIrcLink::m_pLinkFilter private
Referenced by clearOutputQueue(), createSocket(), destroySocket(), KviIrcLink(), linkFilterDestroyed(), outputQueueSize(), processData(), and sendPacket().
char* KviIrcLink::m_pReadBuffer private
Referenced by KviIrcLink(), processData(), and ~KviIrcLink().
KviIrcConnectionTargetResolver* KviIrcLink::m_pResolver private
Referenced by abort(), KviIrcLink(), resolverTerminated(), start(), and ~KviIrcLink().
KviIrcSocket* KviIrcLink::m_pSocket private
Referenced by abort(), clearOutputQueue(), createSocket(), destroySocket(), KviIrcLink(), outputQueueSize(), processData(), resolverTerminated(), sendPacket(), and socketStateChange().
KviIrcConnectionTarget* KviIrcLink::m_pTarget private
Referenced by KviIrcLink(), resolverTerminated(), and start().
unsigned int KviIrcLink::m_uReadBufferLen private
Referenced by KviIrcLink(), and processData().
unsigned int KviIrcLink::m_uReadPackets private
Referenced by KviIrcLink(), and processData().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcLink.h
src/kvirc/kernel/KviIrcLink.cpp