KVIrc: KviKvsPopupMenuItemWithTextAndIcon Class Reference
KviKvsPopupMenuItemWithTextAndIcon Class Reference
#include <KviKvsPopupMenu.h>
Public Member Functions
QPixmap * evaluateIcon (KviKvsPopupMenuTopLevelData *pData)
QString evaluateText (KviKvsPopupMenuTopLevelData *pData)
virtual KviKvsScript * kvsIcon ()
virtual KviKvsScript * kvsText ()
virtual ~KviKvsPopupMenuItemWithTextAndIcon ()
Public Member Functions inherited from KviKvsPopupMenuItem
virtual void clear ()
virtual KviKvsPopupMenuItem * clone () const =0
bool evaluateCondition (KviKvsPopupMenuTopLevelData *pData)
virtual void fill (KviKvsPopupMenu *pMenu, KviKvsPopupMenuTopLevelData *pData, int iIdx)=0
bool isExtMenu ()
bool isItem ()
bool isLabel ()
bool isMenu ()
bool isSeparator ()
virtual KviKvsScript * kvsCode ()
KviKvsScript * kvsCondition ()
const QString & name ()
KviKvsPopupMenuItem::Type type ()
virtual ~KviKvsPopupMenuItem ()
Protected Member Functions
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const QString &szText, const QString &szIcon, const QString &szCondition)
KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString &szItemName, const KviKvsScript *pText, const KviKvsScript *pIcon, const KviKvsScript *pCondition)
Protected Member Functions inherited from KviKvsPopupMenuItem
KviKvsPopupMenuItem (Type t, const QString &szItemName, const QString &szCondition)
KviKvsPopupMenuItem (Type t, const QString &szItemName, const KviKvsScript *pCondition)
Protected Attributes
KviKvsScript * m_pKvsIcon
KviKvsScript * m_pKvsText
Protected Attributes inherited from KviKvsPopupMenuItem
Type m_eType
KviKvsScript * m_pKvsCondition
QString m_szItemName
Additional Inherited Members
Public Types inherited from KviKvsPopupMenuItem
enum Type {
Item, Menu, Label, Separator,
ExtMenu
}
Constructor & Destructor Documentation
KviKvsPopupMenuItemWithTextAndIcon::KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString & szItemName, const QString & szText, const QString & szIcon, const QString & szCondition) protected
References m_pKvsIcon, m_pKvsText, and KviKvsScript::Parameter.
KviKvsPopupMenuItemWithTextAndIcon::KviKvsPopupMenuItemWithTextAndIcon (KviKvsPopupMenuItem::Type t, const QString & szItemName, const KviKvsScript * pText, const KviKvsScript * pIcon, const KviKvsScript * pCondition) protected
References m_pKvsIcon, m_pKvsText, and KviKvsScript::Parameter.
KviKvsPopupMenuItemWithTextAndIcon::~KviKvsPopupMenuItemWithTextAndIcon () virtual
References m_pKvsIcon, and m_pKvsText.
Member Function Documentation
QPixmap * KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon (KviKvsPopupMenuTopLevelData * pData)
References __tr2qs_ctx(), KviKvsVariant::asString(), KviKvsPopupMenuTopLevelData::extendedRunTimeData(), g_pIconManager, KviIconManager::getImage(), KVI_OPTION_BOOL, KVI_OUT_PARSERWARNING, KviOption_boolShowIconsInPopupMenus, m_pKvsIcon, KviWindow::output(), p, KviKvsPopupMenuTopLevelData::parameters(), KviKvsScript::PreserveParams, KviKvsScript::run(), and KviKvsPopupMenuTopLevelData::window().
Referenced by KviKvsPopupMenuItemLabel::fill(), KviKvsPopupMenuItemItem::fill(), KviKvsPopupMenuItemMenu::fill(), and KviKvsPopupMenuItemExtMenu::fill().
QString KviKvsPopupMenuItemWithTextAndIcon::evaluateText (KviKvsPopupMenuTopLevelData * pData)
References __tr2qs_ctx(), KviKvsVariant::asString(), KviKvsPopupMenuTopLevelData::extendedRunTimeData(), KVI_OUT_PARSERWARNING, m_pKvsText, KviWindow::output(), KviKvsPopupMenuTopLevelData::parameters(), KviKvsScript::PreserveParams, KviKvsScript::run(), and KviKvsPopupMenuTopLevelData::window().
Referenced by KviKvsPopupMenuItemLabel::fill(), KviKvsPopupMenuItemItem::fill(), KviKvsPopupMenuItemMenu::fill(), and KviKvsPopupMenuItemExtMenu::fill().
KviKvsScript * KviKvsPopupMenuItemWithTextAndIcon::kvsIcon () virtual
Reimplemented from KviKvsPopupMenuItem.
References m_pKvsIcon.
KviKvsScript * KviKvsPopupMenuItemWithTextAndIcon::kvsText () virtual
Reimplemented from KviKvsPopupMenuItem.
References m_pKvsText.
Member Data Documentation
KviKvsScript* KviKvsPopupMenuItemWithTextAndIcon::m_pKvsIcon protected
Referenced by KviKvsPopupMenuItemLabel::clone(), KviKvsPopupMenuItemItem::clone(), KviKvsPopupMenuItemMenu::clone(), KviKvsPopupMenuItemExtMenu::clone(), evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon(), kvsIcon(), and ~KviKvsPopupMenuItemWithTextAndIcon().
KviKvsScript* KviKvsPopupMenuItemWithTextAndIcon::m_pKvsText protected
Referenced by KviKvsPopupMenuItemLabel::clone(), KviKvsPopupMenuItemItem::clone(), KviKvsPopupMenuItemMenu::clone(), KviKvsPopupMenuItemExtMenu::clone(), evaluateText(), KviKvsPopupMenuItemWithTextAndIcon(), kvsText(), and ~KviKvsPopupMenuItemWithTextAndIcon().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp