KVIrc: KviKvsTreeNodeArrayReferenceAssert Class Reference
KviKvsTreeNodeArrayReferenceAssert Class Reference
Treenode array reference assert class.
#include <KviKvsTreeNodeArrayReferenceAssert.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Array Reference Assert.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the array in read-only mode.
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the array in read-only mode in the object scope.
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
Evaluates the array in read-write mode.
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
Evaluates the array in read-write mode in the object scope.
virtual bool isReadOnly ()
Returns true if the array reference is read-only.
KviKvsTreeNodeArrayReferenceAssert (const QChar *pLocation, KviKvsTreeNodeData *pSource)
Constructs the treenode array reference assert object.
~KviKvsTreeNodeArrayReferenceAssert ()
Destroys the treenode array reference assert object.
Public Member Functions inherited from KviKvsTreeNodeIndirectData
virtual bool canEvaluateInObjectScope ()
KviKvsTreeNodeIndirectData (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeIndirectData ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool isFunctionCall ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Attributes inherited from KviKvsTreeNodeIndirectData
KviKvsTreeNodeData * m_pSource
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Detailed Description
Treenode array reference assert class.
Constructor & Destructor Documentation
KviKvsTreeNodeArrayReferenceAssert::KviKvsTreeNodeArrayReferenceAssert (const QChar * pLocation, KviKvsTreeNodeData * pSource)
Constructs the treenode array reference assert object.
Parameters:
pLocation The location char of the instruction
pSource The source data
Returns:
KviKvsTreeNodeArrayReferenceAssert
KviKvsTreeNodeArrayReferenceAssert::~KviKvsTreeNodeArrayReferenceAssert ()
Destroys the treenode array reference assert object.
Returns:
KviKvsTreeNodeArrayElement
Member Function Documentation
void KviKvsTreeNodeArrayReferenceAssert::contextDescription (QString & szBuffer) virtual
Sets the buffer as Array Reference Assert.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeArrayReferenceAssert::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
bool KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Evaluates the array in read-only mode.
Parameters:
c The context where the alias is bound to
pBuffer The data buffer
Returns:
bool
Reimplemented from KviKvsTreeNodeData.
References evaluateReadOnlyInObjectScope().
bool KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Evaluates the array in read-only mode in the object scope.
Parameters:
o The source object to evaluate
c The context where the array is bound to
pBuffer The data buffer
Returns:
bool
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsVariant::getTypeName(), KviKvsVariant::isArray(), KviKvsVariant::isNothing(), and KviKvsTreeNodeIndirectData::m_pSource.
Referenced by evaluateReadOnly().
KviKvsRWEvaluationResult * KviKvsTreeNodeArrayReferenceAssert::evaluateReadWrite (KviKvsRunTimeContext * c) virtual
Evaluates the array in read-write mode.
Parameters:
c The context where the alias is bound to
Returns:
KviKvsRWEvaluationResult *
Reimplemented from KviKvsTreeNodeData.
References evaluateReadWriteInObjectScope().
KviKvsRWEvaluationResult * KviKvsTreeNodeArrayReferenceAssert::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) virtual
Evaluates the array in read-write mode in the object scope.
Parameters:
o The source object to evaluate
c The context where the array is bound to
Returns:
KviKvsRWEvaluationResult *
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), KviKvsTreeNodeIndirectData::m_pSource, and r.
Referenced by evaluateReadWrite().
bool KviKvsTreeNodeArrayReferenceAssert::isReadOnly () virtual
Returns true if the array reference is read-only.
Returns:
bool
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::isReadOnly(), and KviKvsTreeNodeIndirectData::m_pSource.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeArrayReferenceAssert.h
src/kvirc/kvs/tree/KviKvsTreeNodeArrayReferenceAssert.cpp