KVIrc: KviNetwork Class Reference
KviNetwork Class Reference
Network handling class.
#include <kvi_network.h>
Public Member Functions
bool autoConnect () const
Returns true if the network has the autoconnect state on.
QStringList * autoJoinChannelList ()
Returns the list of channels with autojoin flag.
const QString autoJoinChannelListAsString ()
Returns the list of channels with autojoin flag as a string.
void copyFrom (const KviNetwork &d)
Carbon copy.
KviServer * currentServer ()
Returns the current server.
const QString & description () const
Returns the description of the network.
const QString & encoding () const
Returns the encoding of the network.
KviServer * findServer (const KviServer *pServer)
Searches for a server in the network.
KviServer * findServer (const QString &szHostname)
Searches for a server in the network.
void insertServer (KviServer *srv)
Adds a new server to the network.
KviNetwork (const KviNetwork &src)
Carbon copy.
KviNetwork (const QString &name)
Construct the network object.
const QString & name () const
Returns the name of the network.
const QString & nickName () const
Returns the nickname of the user associated to the network.
KviNickServRuleSet * nickServRuleSet ()
Returns a set of rules for the NickServ.
const QString & onConnectCommand () const
Returns the commands to run on network connect.
const QString & onLoginCommand () const
Returns the commands to run on network login.
const QString & password () const
Returns the password of the user associated to the network.
const QString & realName () const
Returns the realname of the user associated to the network.
KviPointerList< KviServer > * serverList ()
Returns a list of servers associated to the network.
void setAutoConnect (bool bAutoConnect)
Sets the autoconnect flag.
void setAutoJoinChannelList (const QString &szNewChannelList)
Sets the list of channels to mark for autojoin.
void setAutoJoinChannelList (QStringList *pNewChannelList)
Sets the list of channels to mark for autojoin.
void setCurrentServer (KviServer *srv)
Sets the current server.
void setDescription (const QString &szDescription)
Sets the description of the network.
void setEncoding (const QString &szEncoding)
Sets the encondig of the network.
void setName (const QString &szName)
Sets the name of the network.
void setNickName (const QString &n)
Sets the nickname of the user associated to the network.
void setNickServRuleSet (KviNickServRuleSet *s)
Sets the rules for NickServ.
void setOnConnectCommand (const QString &cmd)
Sets the list of commands to run on network connection.
void setOnLoginCommand (const QString &cmd)
Sets the list of commands to run on network login.
void setPassword (const QString &p)
Sets the password of the user associated to the network.
void setRealName (const QString &r)
Sets the realname of the user associated to the network.
void setTextEncoding (const QString &szEncoding)
Sets the text encondig of the network.
void setUserIdentityId (const QString &szUserIdentityId)
Sets the user identity id of the user associated to the network.
void setUserName (const QString &u)
Sets the username of the user associated to the network.
const QString & textEncoding () const
Returns the text encoding of the network.
const QString & userIdentityId () const
Returns the user identity of the user associated to the network.
const QString & userName () const
Returns the username of the user associated to the network.
~KviNetwork ()
Destroys the network object.
Protected Attributes
bool m_bAutoConnect
QStringList * m_pChannelList
KviServer * m_pCurrentServer
KviNickServRuleSet * m_pNickServRuleSet
KviPointerList< KviServer > * m_pServerList
QString m_szDescription
QString m_szEncoding
QString m_szName
QString m_szNickName
QString m_szOnConnectCommand
QString m_szOnLoginCommand
QString m_szPass
QString m_szRealName
QString m_szTextEncoding
QString m_szUserIdentityId
QString m_szUserName
Friends
class KviServerDataBase
Detailed Description
Network handling class.
Constructor & Destructor Documentation
KviNetwork::KviNetwork (const QString & name)
Construct the network object.
Parameters:
name The name of the network
Returns:
KviNetwork
References m_bAutoConnect, m_pChannelList, m_pCurrentServer, m_pNickServRuleSet, m_pServerList, m_szName, and KviPointerList< T >::setAutoDelete().
KviNetwork::KviNetwork (const KviNetwork & src)
Carbon copy.
Parameters:
src The source network
Returns:
KviNetwork
References copyFrom(), m_pChannelList, m_pNickServRuleSet, m_pServerList, and KviPointerList< T >::setAutoDelete().
KviNetwork::~KviNetwork ()
Destroys the network object.
References m_pChannelList, m_pNickServRuleSet, and m_pServerList.
Member Function Documentation
bool KviNetwork::autoConnect () const [inline]
Returns true if the network has the autoconnect state on.
Returns:
bool
QStringList* KviNetwork::autoJoinChannelList () [inline]
Returns the list of channels with autojoin flag.
Returns:
QStringList *
Referenced by KviIrcConnection::loginComplete().
const QString KviNetwork::autoJoinChannelListAsString () [inline]
Returns the list of channels with autojoin flag as a string.
Returns:
const QString &
void KviNetwork::copyFrom (const KviNetwork & d)
Carbon copy.
Parameters:
d The source network to copy from
Returns:
void
References m_bAutoConnect, m_pChannelList, m_pNickServRuleSet, m_szDescription, m_szEncoding, m_szName, m_szNickName, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szTextEncoding, m_szUserIdentityId, and m_szUserName.
Referenced by KviNetwork().
KviServer * KviNetwork::currentServer ()
Returns the current server.
Returns:
KviServer
References KviPointerList< T >::first(), m_pCurrentServer, and m_pServerList.
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviNetwork::description () const [inline]
Returns the description of the network.
Returns:
const QString &
const QString& KviNetwork::encoding () const [inline]
Returns the encoding of the network.
Some information as nickname and channel names are encoded when communicating with the server
Returns:
const QString &
Referenced by KviIrcConnection::setupSrvCodec().
KviServer * KviNetwork::findServer (const KviServer * pServer)
Searches for a server in the network.
Parameters:
pServer The server to find
Returns:
KviServer
References KviQString::equalCI(), KviPointerList< T >::first(), KviServer::isIPv6(), m_pServerList, KviServer::m_szHostname, KviServer::m_szId, KviServer::m_uPort, KviPointerList< T >::next(), s, and KviServer::useSSL().
KviServer * KviNetwork::findServer (const QString & szHostname)
Searches for a server in the network.
Parameters:
szHostname The hostname of the server to find
Returns:
KviServer
References KviQString::equalCI(), KviPointerList< T >::first(), m_pServerList, KviPointerList< T >::next(), and s.
void KviNetwork::insertServer (KviServer * srv)
Adds a new server to the network.
Parameters:
srv The source server to add
Returns:
void
References KviPointerList< T >::append(), and m_pServerList.
const QString& KviNetwork::name () const [inline]
Returns the name of the network.
Returns:
const QString &
Referenced by KviServerDataBase::addNetwork(), KviIrcConnection::loginToIrcServer(), KviServerDataBase::makeCurrentServer(), KviIrcConnectionTarget::networkName(), and KviMdiChild::setClient().
const QString& KviNetwork::nickName () const [inline]
Returns the nickname of the user associated to the network.
Returns:
const QString &
Referenced by KviIrcConnection::loginToIrcServer().
KviNickServRuleSet* KviNetwork::nickServRuleSet () [inline]
Returns a set of rules for the NickServ.
Returns:
KviNickServRuleSet *
Referenced by KviServerParser::parseLiteralNotice().
const QString& KviNetwork::onConnectCommand () const [inline]
Returns the commands to run on network connect.
Returns:
const QString &
Referenced by KviIrcConnection::loginToIrcServer().
const QString& KviNetwork::onLoginCommand () const [inline]
Returns the commands to run on network login.
Returns:
const QString &
Referenced by KviIrcConnection::loginComplete().
const QString& KviNetwork::password () const [inline]
Returns the password of the user associated to the network.
Returns:
const QString &
Referenced by KviIrcConnection::loginToIrcServer().
const QString& KviNetwork::realName () const [inline]
Returns the realname of the user associated to the network.
Returns:
const QString &
Referenced by KviIrcConnection::loginToIrcServer().
KviPointerList<KviServer>* KviNetwork::serverList () [inline]
Returns a list of servers associated to the network.
Returns:
KviPointerList<KviServer> *
Referenced by KviServerDataBase::makeCurrentServer().
void KviNetwork::setAutoConnect (bool bAutoConnect) [inline]
Sets the autoconnect flag.
Parameters:
bAutoConnect The state of the autoconnect flag
Returns:
void
void KviNetwork::setAutoJoinChannelList (const QString & szNewChannelList)
Sets the list of channels to mark for autojoin.
Parameters:
szNewChannelList A comma separated list of channels
Returns:
void
References m_pChannelList.
void KviNetwork::setAutoJoinChannelList (QStringList * pNewChannelList)
Sets the list of channels to mark for autojoin.
Parameters:
pNewChannelList The channel list
Returns:
void
References m_pChannelList.
Referenced by KviServerDataBase::load().
void KviNetwork::setCurrentServer (KviServer * srv)
Sets the current server.
Parameters:
srv The source server
Returns:
void
References KviPointerList< T >::findRef(), m_pCurrentServer, and m_pServerList.
Referenced by KviServerDataBase::makeCurrentBestServerInNetwork(), and KviServerDataBase::makeCurrentServer().
void KviNetwork::setDescription (const QString & szDescription) [inline]
Sets the description of the network.
Parameters:
szDescription The description of the network
Returns:
void
void KviNetwork::setEncoding (const QString & szEncoding) [inline]
Sets the encondig of the network.
Some information as nickname and channel names are encoded when communicating with the server
Parameters:
szEncoding The encoding of the network
Returns:
void
void KviNetwork::setName (const QString & szName) [inline]
Sets the name of the network.
Parameters:
szName The name of the network
Returns:
void
Referenced by KviIrcConnectionTarget::setNetworkName().
void KviNetwork::setNickName (const QString & n) [inline]
Sets the nickname of the user associated to the network.
Parameters:
n The nickname
Returns:
void
void KviNetwork::setNickServRuleSet (KviNickServRuleSet * s)
Sets the rules for NickServ.
Parameters:
s The rule set where to add rules
Returns:
void
References m_pNickServRuleSet.
void KviNetwork::setOnConnectCommand (const QString & cmd) [inline]
Sets the list of commands to run on network connection.
Parameters:
cmd The commands list to run
Returns:
void
void KviNetwork::setOnLoginCommand (const QString & cmd) [inline]
Sets the list of commands to run on network login.
Parameters:
cmd The commands list to run
Returns:
void
void KviNetwork::setPassword (const QString & p) [inline]
Sets the password of the user associated to the network.
Returns:
void
void KviNetwork::setRealName (const QString & r) [inline]
Sets the realname of the user associated to the network.
Parameters:
r The realname
Returns:
void
void KviNetwork::setTextEncoding (const QString & szEncoding) [inline]
Sets the text encondig of the network.
This is the default encoding when talking on channels or queries
Parameters:
szEncoding The text encoding of the network
Returns:
void
void KviNetwork::setUserIdentityId (const QString & szUserIdentityId) [inline]
Sets the user identity id of the user associated to the network.
Parameters:
szUserIdentityId The user identity
Returns:
void
void KviNetwork::setUserName (const QString & u) [inline]
Sets the username of the user associated to the network.
Parameters:
u The username
Returns:
void
const QString& KviNetwork::textEncoding () const [inline]
Returns the text encoding of the network.
This is the default encoding when talking on channels or queries
Returns:
const QString &
Referenced by KviIrcConnection::setupTextCodec().
const QString& KviNetwork::userIdentityId () const [inline]
Returns the user identity of the user associated to the network.
Returns:
const QString &
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviNetwork::userName () const [inline]
Returns the username of the user associated to the network.
Returns:
const QString &
Referenced by KviIrcConnection::loginToIrcServer().
Friends And Related Function Documentation
friend class KviServerDataBase [friend]
Member Data Documentation
bool KviNetwork::m_bAutoConnect [protected]
Referenced by copyFrom(), KviNetwork(), and KviServerDataBase::load().
QStringList* KviNetwork::m_pChannelList [protected]
Referenced by copyFrom(), KviNetwork(), setAutoJoinChannelList(), and ~KviNetwork().
KviServer* KviNetwork::m_pCurrentServer [protected]
Referenced by currentServer(), KviNetwork(), KviServerDataBase::load(), and setCurrentServer().
KviNickServRuleSet* KviNetwork::m_pNickServRuleSet [protected]
Referenced by copyFrom(), KviNetwork(), KviServerDataBase::load(), setNickServRuleSet(), and ~KviNetwork().
KviPointerList<KviServer>* KviNetwork::m_pServerList [protected]
Referenced by currentServer(), findServer(), KviServerDataBase::importFromMircIni(), insertServer(), KviNetwork(), KviServerDataBase::load(), KviServerDataBase::makeCurrentBestServerInNetwork(), setCurrentServer(), and ~KviNetwork().
QString KviNetwork::m_szDescription [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szEncoding [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szName [protected]
Referenced by copyFrom(), and KviNetwork().
QString KviNetwork::m_szNickName [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szOnConnectCommand [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szOnLoginCommand [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szPass [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szRealName [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szTextEncoding [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szUserIdentityId [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
QString KviNetwork::m_szUserName [protected]
Referenced by copyFrom(), and KviServerDataBase::load().
The documentation for this class was generated from the following files:
src/kvilib/irc/kvi_network.h
src/kvilib/irc/kvi_network.cpp