KVIrc: KviUserListToolTip Class Reference
KviUserListToolTip Class Reference
A class to manage userlist tooltips.
#include <KviUserListView.h>
Public Member Functions
void doTip (const QRect &rect, const QString &szStr)
Shows the tooltip.
KviUserListToolTip (KviUserListView *pView, KviUserListViewArea *pArea)
Constructs the userlist tooltip.
virtual void maybeTip (const QPoint &pnt)
Checks if user activated tooltips in the option panel.
virtual ~KviUserListToolTip ()
Destroys the userlist tooltip.
Public Member Functions inherited from KviTalToolTip
KviTalToolTip (QWidget *pParent)
virtual void tip (const QRect &rect, const QString &text)
virtual ~KviTalToolTip ()
Private Attributes
KviUserListView * m_pListView
Additional Inherited Members
Static Public Member Functions inherited from KviTalToolTip
static void add (QWidget *widget, const QString &text)
static void remove (QWidget *widget)
Protected Member Functions inherited from KviTalToolTip
void helperDying ()
Protected Attributes inherited from KviTalToolTip
KviTalToolTipHelper * m_pHelper
QWidget * m_pParent
Detailed Description
A class to manage userlist tooltips.
Constructor & Destructor Documentation
KviUserListToolTip::KviUserListToolTip (KviUserListView * pView, KviUserListViewArea * pArea)
Constructs the userlist tooltip.
Parameters
pView The listview to manage tooltips
pArea The parent widget area
Returns
KviUserListToolTip
References m_pListView.
KviUserListToolTip::~KviUserListToolTip () virtual
Destroys the userlist tooltip.
Member Function Documentation
void KviUserListToolTip::doTip (const QRect & rect, const QString & szStr) inline
Shows the tooltip.
Parameters
rect The rectangle where to show the tooltip
szStr The string to show
Returns
void
References KviTalToolTip::tip().
Referenced by KviUserListView::maybeTip().
void KviUserListToolTip::maybeTip (const QPoint & pnt) virtual
Checks if user activated tooltips in the option panel.
Parameters
pnt The point where to show to tooltip
Returns
void
Reimplemented from KviTalToolTip.
References m_pListView, and KviUserListView::maybeTip().
Member Data Documentation
KviUserListView* KviUserListToolTip::m_pListView private
Referenced by KviUserListToolTip(), and maybeTip().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviUserListView.h
src/kvirc/ui/KviUserListView.cpp