KVIrc: MediaTypeTreeWidgetItem Class Reference
MediaTypeTreeWidgetItem Class Reference
#include <OptionsWidget_mediaTypes.h>
Public Member Functions
void copyData (KviMediaType *t)
MediaTypeTreeWidgetItem (QTreeWidget *w, KviMediaType *t)
const KviMediaType * mydata ()
~MediaTypeTreeWidgetItem ()
Private Attributes
KviMediaType m_data
Constructor & Destructor Documentation
MediaTypeTreeWidgetItem::MediaTypeTreeWidgetItem (QTreeWidget * w, KviMediaType * t)
References copyData().
MediaTypeTreeWidgetItem::~MediaTypeTreeWidgetItem () default
Member Function Documentation
void MediaTypeTreeWidgetItem::copyData (KviMediaType * t)
References copyMediaType(), m_data, KviCString::ptr(), KviMediaType::szDescription, KviMediaType::szFileMask, and KviMediaType::szIanaType.
Referenced by MediaTypeTreeWidgetItem(), and OptionsWidget_mediaTypes::saveLastItem().
const KviMediaType* MediaTypeTreeWidgetItem::mydata () inline
References m_data.
Referenced by OptionsWidget_mediaTypes::commit(), and OptionsWidget_mediaTypes::setLineEdits().
Member Data Documentation
KviMediaType MediaTypeTreeWidgetItem::m_data private
Referenced by copyData(), and mydata().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_mediaTypes.h
src/modules/options/OptionsWidget_mediaTypes.cpp