KVIrc: KviKvsTreeNodeOperationSelfShl Class Reference
KviKvsTreeNodeOperationSelfShl Class Reference
#include <kvi_kvs_treenode_operation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationSelfShl (const QChar *pLocation, KviKvsTreeNodeData *pRightSide)
~KviKvsTreeNodeOperationSelfShl ()
Protected Attributes
KviKvsTreeNodeData * m_pRightSide
Constructor & Destructor Documentation
KviKvsTreeNodeOperationSelfShl::KviKvsTreeNodeOperationSelfShl (const QChar * pLocation, KviKvsTreeNodeData * pRightSide)
References m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationSelfShl::~KviKvsTreeNodeOperationSelfShl ()
References m_pRightSide.
Member Function Documentation
void KviKvsTreeNodeOperationSelfShl::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationSelfShl::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pRightSide, and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationSelfShl::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx, KviKvsVariant::asInteger(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), m_pRightSide, KviKvsTreeNodeOperation::m_pTargetData, KviKvsRWEvaluationResult::result(), and KviKvsVariant::setInteger().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationSelfShl::m_pRightSide [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationSelfShl(), and ~KviKvsTreeNodeOperationSelfShl().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.cpp