KVIrc: SlowPasteController Class Reference
SlowPasteController Class Reference
#include <SlowPasteController.h>
Public Member Functions
int getId (void)
bool pasteClipboardInit (void)
bool pasteFileInit (QString &fileName)
SlowPasteController (KviWindow *w, int id)
KviWindow * window (void)
~SlowPasteController ()
Protected Slots
void pasteClipboard (void)
void pasteFile (void)
Private Attributes
QStringList * m_pClipBuff
QFile * m_pFile
int m_pId
QTimer * m_pTimer
KviWindow * m_pWindow
Constructor & Destructor Documentation
SlowPasteController::SlowPasteController (KviWindow * w, int id)
References KviPointerList< T >::append(), and m_pTimer.
SlowPasteController::~SlowPasteController ()
References m_pClipBuff, m_pFile, m_pTimer, and KviPointerList< T >::removeRef().
Member Function Documentation
int SlowPasteController::getId (void) [inline]
References m_pId.
Referenced by spaste_kvs_cmd_list(), and spaste_kvs_cmd_stop().
void SlowPasteController::pasteClipboard (void) [protected, slot]
References g_pApp, KVI_OPTION_UINT, KviOption_uintSpacesToExpandTabulationInput, m_pClipBuff, m_pWindow, KviWindow::ownMessage(), and KviApplication::windowExists().
Referenced by pasteClipboardInit().
bool SlowPasteController::pasteClipboardInit (void)
References connect(), g_pApp, KVI_OPTION_UINT, KviOption_uintPasteDelay, m_pClipBuff, m_pFile, m_pTimer, and pasteClipboard().
Referenced by spaste_kvs_cmd_clipboard().
void SlowPasteController::pasteFile (void) [protected, slot]
References g_pApp, KVI_OPTION_UINT, KviOption_uintSpacesToExpandTabulationInput, m_pFile, m_pWindow, KviWindow::ownMessage(), KviMircCntrl::Reset, and KviApplication::windowExists().
Referenced by pasteFileInit().
bool SlowPasteController::pasteFileInit (QString & fileName)
References connect(), KVI_OPTION_UINT, KviOption_uintPasteDelay, m_pClipBuff, m_pFile, m_pTimer, and pasteFile().
Referenced by spaste_kvs_cmd_file().
KviWindow* SlowPasteController::window (void) [inline]
References m_pWindow.
Referenced by spaste_kvs_cmd_list(), and spaste_kvs_cmd_stop().
Member Data Documentation
QStringList* SlowPasteController::m_pClipBuff [private]
Referenced by pasteClipboard(), pasteClipboardInit(), pasteFileInit(), and ~SlowPasteController().
QFile* SlowPasteController::m_pFile [private]
Referenced by pasteClipboardInit(), pasteFile(), pasteFileInit(), and ~SlowPasteController().
int SlowPasteController::m_pId [private]
Referenced by getId().
QTimer* SlowPasteController::m_pTimer [private]
Referenced by pasteClipboardInit(), pasteFileInit(), SlowPasteController(), and ~SlowPasteController().
KviWindow* SlowPasteController::m_pWindow [private]
Referenced by pasteClipboard(), pasteFile(), and window().
The documentation for this class was generated from the following files:
src/modules/spaste/SlowPasteController.h
src/modules/spaste/SlowPasteController.cpp