KVIrc: KviKvsTreeNodeLocalVariable Class Reference
KviKvsTreeNodeLocalVariable Class Reference
#include <kvi_kvs_treenode_localvariable.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
KviKvsTreeNodeLocalVariable (const QChar *pLocation, const QString &szIdentifier)
~KviKvsTreeNodeLocalVariable ()
Constructor & Destructor Documentation
KviKvsTreeNodeLocalVariable::KviKvsTreeNodeLocalVariable (const QChar * pLocation, const QString & szIdentifier)
KviKvsTreeNodeLocalVariable::~KviKvsTreeNodeLocalVariable ()
Member Function Documentation
void KviKvsTreeNodeLocalVariable::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
void KviKvsTreeNodeLocalVariable::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
bool KviKvsTreeNodeLocalVariable::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::copyFrom(), KviKvsHash::find(), KviKvsRunTimeContext::localVariables(), KviKvsTreeNodeVariable::m_szIdentifier, and KviKvsVariant::setNothing().
KviKvsRWEvaluationResult * KviKvsTreeNodeLocalVariable::evaluateReadWrite (KviKvsRunTimeContext * c) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsHash::get(), KviKvsRunTimeContext::localVariables(), and KviKvsTreeNodeVariable::m_szIdentifier.
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_localvariable.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_localvariable.cpp