KVIrc: KviRegisteredUserDataBase Class Reference
KviRegisteredUserDataBase Class Reference
#include <KviRegisteredUserDataBase.h>
Signals
void databaseCleared ()
void userAdded (const QString &)
void userChanged (const QString &)
void userRemoved (const QString &)
Public Member Functions
KviRegisteredUserGroup * addGroup (const QString &name)
KviRegisteredUser * addMask (KviRegisteredUser *u, KviIrcMask *mask)
KviRegisteredUser * addUser (const QString &name)
void copyFrom (KviRegisteredUserDataBase *db)
KviRegisteredUserMask * findExactMask (const KviIrcMask &mask)
KviRegisteredUserMask * findMatchingMask (const QString &nick, const QString &user, const QString &host)
KviRegisteredUser * findMatchingUser (const QString &nick, const QString &user, const QString &host)
KviRegisteredUser * findUserByName (const QString &name)
KviRegisteredUser * findUserWithMask (const KviIrcMask &mask)
KviRegisteredUser * getUser (const QString &name)
KviPointerHashTable< QString,
KviRegisteredUserGroup > * groupDict ()
KviRegisteredUserDataBase ()
void load (const QString &filename)
bool removeGroup (const QString &name)
bool removeMask (const KviIrcMask &mask)
bool removeMaskByPointer (KviIrcMask *mask)
bool removeUser (const QString &name)
void save (const QString &filename)
KviPointerHashTable< QString,
KviRegisteredUser > * userDict ()
~KviRegisteredUserDataBase ()
Private Attributes
KviPointerHashTable< QString,
KviRegisteredUserGroup > * m_pGroupDict
KviPointerHashTable< QString,
KviRegisteredUserMaskList > * m_pMaskDict
KviPointerHashTable< QString,
KviRegisteredUser > * m_pUserDict
KviRegisteredUserMaskList * m_pWildMaskList
Constructor & Destructor Documentation
KviRegisteredUserDataBase::KviRegisteredUserDataBase ()
References m_pGroupDict, m_pMaskDict, m_pUserDict, m_pWildMaskList, KviPointerList< T >::setAutoDelete(), and KviPointerHashTable< Key, T >::setAutoDelete().
KviRegisteredUserDataBase::~KviRegisteredUserDataBase ()
References databaseCleared(), m_pGroupDict, m_pMaskDict, m_pUserDict, and m_pWildMaskList.
Member Function Documentation
KviRegisteredUserGroup * KviRegisteredUserDataBase::addGroup (const QString & name)
References KviPointerHashTable< Key, T >::find(), m_pGroupDict, KviRegisteredUserGroup::name(), and KviPointerHashTable< Key, T >::replace().
Referenced by RegisteredUsersDialog::addGroupClicked(), copyFrom(), RegisteredUsersDialog::fillList(), and load().
KviRegisteredUser * KviRegisteredUserDataBase::addMask (KviRegisteredUser * u, KviIrcMask * mask)
References KviRegisteredUser::addMask(), append_mask_to_list(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), KviIrcMask::hasWildNick(), KviPointerHashTable< Key, T >::insert(), KVI_ASSERT, l, m, m_pMaskDict, m_pUserDict, m_pWildMaskList, KviRegisteredUser::name(), KviPointerList< T >::next(), KviIrcMask::nick(), and KviPointerList< T >::setAutoDelete().
Referenced by RegistrationWizard::accept(), copyFrom(), RegisteredUsersDialog::importClicked(), load(), RegisteredUserEntryDialog::okClicked(), reguser_kvs_cmd_add(), and reguser_kvs_cmd_addmask().
KviRegisteredUser * KviRegisteredUserDataBase::addUser (const QString & name)
References KviPointerHashTable< Key, T >::find(), m_pUserDict, KviRegisteredUser::name(), KviPointerHashTable< Key, T >::replace(), u, and userAdded().
Referenced by RegistrationWizard::accept(), load(), RegisteredUserEntryDialog::okClicked(), and reguser_kvs_cmd_add().
void KviRegisteredUserDataBase::copyFrom (KviRegisteredUserDataBase * db)
References addGroup(), addMask(), KviPointerList< T >::clear(), KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), databaseCleared(), getUser(), l, m, KviRegisteredUser::m_bIgnoreEnabled, KviRegisteredUser::m_iIgnoreFlags, m_pGroupDict, m_pMaskDict, m_pUserDict, m_pWildMaskList, KviRegisteredUser::setGroup(), KviRegisteredUser::setProperty(), and u.
Referenced by RegisteredUsersDialog::okClicked(), and RegisteredUsersDialog::RegisteredUsersDialog().
void KviRegisteredUserDataBase::databaseCleared () [signal]
Referenced by copyFrom(), and ~KviRegisteredUserDataBase().
KviRegisteredUserMask * KviRegisteredUserDataBase::findExactMask (const KviIrcMask & mask)
References KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), l, m, m_pMaskDict, m_pWildMaskList, KviPointerList< T >::next(), and KviIrcMask::nick().
Referenced by findUserWithMask(), and removeMask().
KviRegisteredUserMask * KviRegisteredUserDataBase::findMatchingMask (const QString & nick, const QString & user, const QString & host)
References KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), l, m, m_pMaskDict, m_pWildMaskList, and KviPointerList< T >::next().
Referenced by findMatchingUser(), and KviConsoleWindow::getUserTipText().
KviRegisteredUser * KviRegisteredUserDataBase::findMatchingUser (const QString & nick, const QString & user, const QString & host)
References findMatchingMask(), m, and KviRegisteredUserMask::user().
Referenced by KviIrcUserDataBase::registeredUser(), reguser_kvs_fnc_match(), and reguser_kvs_fnc_matchProperty().
KviRegisteredUser* KviRegisteredUserDataBase::findUserByName (const QString & name) [inline]
Referenced by RegistrationWizard::accept(), KviWatchNotifyListManager::doMatchUser(), KviIsOnNotifyListManager::doMatchUser(), RegisteredUserEntryDialog::okClicked(), reguser_kvs_cmd_add(), reguser_kvs_cmd_addmask(), reguser_kvs_cmd_setIgnoreEnabled(), reguser_kvs_cmd_setIgnoreFlags(), reguser_kvs_cmd_setproperty(), reguser_kvs_fnc_getIgnoreFlags(), reguser_kvs_fnc_isIgnoreEnabled(), reguser_kvs_fnc_mask(), and reguser_kvs_fnc_property().
KviRegisteredUser * KviRegisteredUserDataBase::findUserWithMask (const KviIrcMask & mask)
References findExactMask(), m, and KviRegisteredUserMask::user().
Referenced by reguser_kvs_fnc_exactMatch().
KviRegisteredUser * KviRegisteredUserDataBase::getUser (const QString & name)
References KviPointerHashTable< Key, T >::find(), m_pUserDict, KviRegisteredUser::name(), KviPointerHashTable< Key, T >::replace(), and u.
Referenced by copyFrom(), RegisteredUsersDialog::importClicked(), and KviIrcUserDataBase::registeredUser().
KviPointerHashTable<QString,KviRegisteredUserGroup>* KviRegisteredUserDataBase::groupDict () [inline]
Referenced by RegisteredUsersDialog::editGroup(), RegisteredUsersDialog::fillList(), and RegisteredUsersDialog::rightButtonPressed().
void KviRegisteredUserDataBase::load (const QString & filename)
References __tr, addGroup(), addMask(), addUser(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviQString::equalCI(), KviQString::equalCSN(), KviPointerHashTable< Key, T >::find(), m_pGroupDict, KviConfigurationFile::Read, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readIntEntry(), KviRegisteredUser::setGroup(), KviConfigurationFile::setGroup(), KviRegisteredUser::setIgnoreEnabled(), KviRegisteredUser::setIgnoreFlags(), KviRegisteredUser::setProperty(), and u.
Referenced by KviApplication::setup().
bool KviRegisteredUserDataBase::removeGroup (const QString & name)
References m_pGroupDict, and KviPointerHashTable< Key, T >::remove().
Referenced by RegisteredUsersDialog::removeClicked().
bool KviRegisteredUserDataBase::removeMask (const KviIrcMask & mask)
References findExactMask(), m, KviRegisteredUserMask::mask(), and removeMaskByPointer().
Referenced by RegistrationWizard::accept(), RegisteredUserEntryDialog::okClicked(), reguser_kvs_cmd_addmask(), and reguser_kvs_cmd_delmask().
bool KviRegisteredUserDataBase::removeMaskByPointer (KviIrcMask * mask)
References KviPointerList< T >::count(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), KviIrcMask::hasWildNick(), l, m, m_pMaskDict, m_pWildMaskList, KviPointerList< T >::next(), KviIrcMask::nick(), KviPointerHashTable< Key, T >::remove(), KviPointerList< T >::removeRef(), and userChanged().
Referenced by removeMask(), and removeUser().
bool KviRegisteredUserDataBase::removeUser (const QString & name)
References KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), m_pUserDict, KviRegisteredUser::maskList(), KviPointerHashTable< Key, T >::remove(), removeMaskByPointer(), u, and userRemoved().
Referenced by RegisteredUserEntryDialog::okClicked(), reguser_kvs_cmd_add(), reguser_kvs_cmd_remove(), and RegisteredUsersDialog::removeClicked().
void KviRegisteredUserDataBase::save (const QString & filename)
References KviConfigurationFile::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviPointerList< T >::first(), KviRegisteredUser::group(), i, KviRegisteredUser::ignoreEnagled(), KviRegisteredUser::ignoreFlags(), m_pGroupDict, m_pUserDict, KviRegisteredUser::maskList(), KviRegisteredUserGroup::name(), KviRegisteredUser::name(), KviPointerList< T >::next(), KviIrcMask::NickUserHost, KviConfigurationFile::preserveEmptyGroups(), KviRegisteredUser::propertyDict(), KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveRegisteredUsers().
void KviRegisteredUserDataBase::userAdded (const QString &) [signal]
Referenced by addUser().
void KviRegisteredUserDataBase::userChanged (const QString &) [signal]
Referenced by removeMaskByPointer().
KviPointerHashTable<QString,KviRegisteredUser>* KviRegisteredUserDataBase::userDict () [inline]
Referenced by KviStupidNotifyListManager::buildNickList(), KviWatchNotifyListManager::buildRegUserDict(), KviIsOnNotifyListManager::buildRegUserDict(), RegisteredUsersDialog::editGroup(), RegisteredUsersDialog::fillList(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), reguser_kvs_cmd_showlist(), and reguser_kvs_fnc_list().
void KviRegisteredUserDataBase::userRemoved (const QString &) [signal]
Referenced by removeUser().
Member Data Documentation
KviPointerHashTable<QString,KviRegisteredUserGroup>* KviRegisteredUserDataBase::m_pGroupDict [private]
Referenced by addGroup(), copyFrom(), KviRegisteredUserDataBase(), load(), removeGroup(), save(), and ~KviRegisteredUserDataBase().
KviPointerHashTable<QString,KviRegisteredUserMaskList>* KviRegisteredUserDataBase::m_pMaskDict [private]
Referenced by addMask(), copyFrom(), findExactMask(), findMatchingMask(), KviRegisteredUserDataBase(), removeMaskByPointer(), and ~KviRegisteredUserDataBase().
KviPointerHashTable<QString,KviRegisteredUser>* KviRegisteredUserDataBase::m_pUserDict [private]
Referenced by addMask(), addUser(), copyFrom(), getUser(), KviRegisteredUserDataBase(), removeUser(), save(), and ~KviRegisteredUserDataBase().
KviRegisteredUserMaskList* KviRegisteredUserDataBase::m_pWildMaskList [private]
Referenced by addMask(), copyFrom(), findExactMask(), findMatchingMask(), KviRegisteredUserDataBase(), removeMaskByPointer(), and ~KviRegisteredUserDataBase().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviRegisteredUserDataBase.h
src/kvilib/ext/KviRegisteredUserDataBase.cpp