KVIrc: QHttpPrivate Class Reference
QHttpPrivate Class Reference
Public Member Functions
void _q_continuePost ()
void _q_slotBytesWritten (qint64 numBytes)
void _q_slotClosed ()
void _q_slotConnected ()
void _q_slotDoFinished ()
void _q_slotEncryptedBytesWritten (qint64 numBytes)
void _q_slotError (QAbstractSocket::SocketError)
void _q_slotReadyRead ()
void _q_slotSendRequest ()
void _q_startNextRequest ()
int addRequest (QHttpNormalRequest *)
int addRequest (QHttpRequest *)
void closeConn ()
void finishedWithError (const QString &detail, int errorCode)
void finishedWithSuccess ()
void init ()
void postMoreData ()
QHttpPrivate (QHttp *parent)
void setSock (QTcpSocket *sock)
void setState (int)
~QHttpPrivate ()
Public Attributes
QHttpAuthenticator authenticator
QByteArray buffer
qint64 bytesDone
qint64 bytesTotal
qint64 chunkedSize
bool deleteSocket
QHttp::Error error
QString errorString
bool hasFinishedWithError
QHttpRequestHeader header
QString headerStr
QString hostName
QHttp::ConnectionMode mode
QList< QHttpRequest * > pending
bool pendingPost
quint16 port
QTimer post100ContinueTimer
QIODevice * postDevice
QNetworkProxy proxy
QHttpAuthenticator proxyAuthenticator
QHttp * q_ptr
QRingBuffer rba
bool readHeader
int reconnectAttempts
bool repost
QHttpResponseHeader response
QTcpSocket * socket
QHttp::State state
QIODevice * toDevice
Constructor & Destructor Documentation
QHttpPrivate::QHttpPrivate (QHttp * parent) inline
QHttpPrivate::~QHttpPrivate () inline
References deleteSocket, pending, and socket.
Member Function Documentation
void QHttpPrivate::_q_continuePost ()
References _q_slotBytesWritten(), pendingPost, QHttp::Sending, and setState().
Referenced by init().
void QHttpPrivate::_q_slotBytesWritten (qint64 numBytes)
References bytesDone, bytesTotal, postMoreData(), and q.
Referenced by _q_continuePost(), and setSock().
void QHttpPrivate::_q_slotClosed ()
References bytesDone, QHttp::Closing, QHttp::Connecting, QHttpHeader::contentLength(), finishedWithError(), QHttpHeader::hasKey(), postDevice, q, QHttp::Reading, response, QHttp::Sending, setState(), state, QHttp::UnexpectedClose, and QHttp::WrongContentLength.
Referenced by setSock().
void QHttpPrivate::_q_slotConnected ()
References buffer, bytesDone, bytesTotal, header, pendingPost, post100ContinueTimer, postDevice, QHttp::Sending, setState(), socket, state, QHttpRequestHeader::toString(), and QHttpHeader::value().
Referenced by _q_slotSendRequest(), and setSock().
void QHttpPrivate::_q_slotDoFinished ()
References QHttp::Connected, finishedWithSuccess(), setState(), state, and QHttp::Unconnected.
void QHttpPrivate::_q_slotEncryptedBytesWritten (qint64 numBytes)
References postMoreData(), and Q_UNUSED().
Referenced by setSock().
void QHttpPrivate::_q_slotError (QAbstractSocket::SocketError err)
References closeConn(), QHttp::Closing, QHttp::Connecting, QHttp::ConnectionRefused, finishedWithError(), QHttp::HostNotFound, postDevice, QHttp::ProxyAuthenticationRequiredError, q, QHttp::Reading, reconnectAttempts, QHttp::Sending, setState(), socket, state, QHttp::Unconnected, and QHttp::UnknownError.
Referenced by setSock().
void QHttpPrivate::_q_slotReadyRead ()
References _q_slotSendRequest(), QHttp::AuthenticationRequiredError, authenticator, buffer, bytesDone, chunkedSize, closeConn(), QHttp::Closing, QHttp::Connected, QHttpHeader::contentLength(), QHttpAuthenticator::detach(), QHttpAuthenticatorPrivate::Done, finishedWithError(), QHttpAuthenticatorPrivate::getPrivate(), QHttpHeader::hasContentLength(), QHttpHeader::hasKey(), headerStr, hostName, QHttpAuthenticatorPrivate::Invalid, QHttp::InvalidResponseHeader, QHttpAuthenticator::isNull(), QHttpHeader::isValid(), n, QHttpAuthenticatorPrivate::parseHttpResponse(), pendingPost, QHttpAuthenticatorPrivate::phase, port, post100ContinueTimer, proxy, QHttp::ProxyAuthenticationRequiredError, proxyAuthenticator, q, rba, readHeader, QHttp::Reading, repost, QRingBuffer::reserve(), response, setState(), socket, state, QHttpResponseHeader::statusCode(), toDevice, QHttpAuthenticator::toQAuthenticator(), QHttpResponseHeader::toString(), QHttp::Unconnected, QHttp::UnknownError, QHttpHeader::value(), and QHttp::WrongContentLength.
Referenced by setSock().
void QHttpPrivate::_q_slotSendRequest ()
References _q_slotConnected(), authenticator, QHttpAuthenticatorPrivate::calculateResponse(), QHttp::Connecting, QHttp::ConnectionModeHttps, finishedWithError(), QHttpAuthenticatorPrivate::getPrivate(), header, hostName, QHttpRequestHeader::majorVersion(), QHttpAuthenticatorPrivate::method, QHttpRequestHeader::method(), QHttpRequestHeader::minorVersion(), mode, QHttpAuthenticatorPrivate::None, QHttpRequestHeader::path(), port, proxy, proxyAuthenticator, response, QHttpRequestHeader::setRequest(), setState(), QHttpHeader::setValue(), socket, and QHttp::UnknownError.
Referenced by _q_slotReadyRead().
void QHttpPrivate::_q_startNextRequest ()
References error, errorString, QHttpRequest::id, QHttp::NoError, pending, q, r, and QHttpRequest::start().
Referenced by finishedWithSuccess().
int QHttpPrivate::addRequest (QHttpNormalRequest * req)
References h, QHttpRequestHeader::majorVersion(), QHttpRequestHeader::method(), QHttpRequestHeader::minorVersion(), QHttpRequestHeader::path(), QHttpNormalRequest::requestHeader(), QHttpRequestHeader::setRequest(), and QHttpNormalRequest::setRequestHeader().
int QHttpPrivate::addRequest (QHttpRequest * req)
References QHttpRequest::id, pending, and q.
void QHttpPrivate::closeConn ()
References QHttp::Closing, postDevice, q, setState(), socket, state, and QHttp::Unconnected.
Referenced by _q_slotError(), _q_slotReadyRead(), and postMoreData().
void QHttpPrivate::finishedWithError (const QString & detail, int errorCode)
References error, errorString, QHttpRequest::finished, hasFinishedWithError, QHttpRequest::id, pending, q, and r.
Referenced by _q_slotClosed(), _q_slotError(), _q_slotReadyRead(), and _q_slotSendRequest().
void QHttpPrivate::finishedWithSuccess ()
References _q_startNextRequest(), QHttpRequest::finished, hasFinishedWithError, QHttpRequest::id, pending, q, and r.
Referenced by _q_slotDoFinished().
void QHttpPrivate::init ()
References _q_continuePost(), connect(), errorString, post100ContinueTimer, and q.
void QHttpPrivate::postMoreData ()
References closeConn(), n, pendingPost, postDevice, and socket.
Referenced by _q_slotBytesWritten(), and _q_slotEncryptedBytesWritten().
void QHttpPrivate::setSock (QTcpSocket * sock)
References _q_slotBytesWritten(), _q_slotClosed(), _q_slotConnected(), _q_slotEncryptedBytesWritten(), _q_slotError(), _q_slotReadyRead(), connect(), deleteSocket, error, q, and socket.
void QHttpPrivate::setState (int s)
References q, and state.
Referenced by _q_continuePost(), _q_slotClosed(), _q_slotConnected(), _q_slotDoFinished(), _q_slotError(), _q_slotReadyRead(), _q_slotSendRequest(), and closeConn().
Member Data Documentation
QHttpAuthenticator QHttpPrivate::authenticator
Referenced by _q_slotReadyRead(), and _q_slotSendRequest().
QByteArray QHttpPrivate::buffer
Referenced by _q_slotConnected(), and _q_slotReadyRead().
qint64 QHttpPrivate::bytesDone
Referenced by _q_slotBytesWritten(), _q_slotClosed(), _q_slotConnected(), and _q_slotReadyRead().
qint64 QHttpPrivate::bytesTotal
Referenced by _q_slotBytesWritten(), and _q_slotConnected().
qint64 QHttpPrivate::chunkedSize
Referenced by _q_slotReadyRead().
bool QHttpPrivate::deleteSocket
Referenced by setSock(), and ~QHttpPrivate().
QHttp::Error QHttpPrivate::error
Referenced by _q_startNextRequest(), finishedWithError(), and setSock().
QString QHttpPrivate::errorString
Referenced by _q_startNextRequest(), finishedWithError(), and init().
bool QHttpPrivate::hasFinishedWithError
Referenced by finishedWithError(), and finishedWithSuccess().
QHttpRequestHeader QHttpPrivate::header
Referenced by _q_slotConnected(), and _q_slotSendRequest().
QString QHttpPrivate::headerStr
Referenced by _q_slotReadyRead().
QString QHttpPrivate::hostName
Referenced by _q_slotReadyRead(), and _q_slotSendRequest().
QHttp::ConnectionMode QHttpPrivate::mode
Referenced by _q_slotSendRequest().
QList<QHttpRequest *> QHttpPrivate::pending
Referenced by _q_startNextRequest(), addRequest(), finishedWithError(), finishedWithSuccess(), and ~QHttpPrivate().
bool QHttpPrivate::pendingPost
Referenced by _q_continuePost(), _q_slotConnected(), _q_slotReadyRead(), and postMoreData().
quint16 QHttpPrivate::port
Referenced by _q_slotReadyRead(), and _q_slotSendRequest().
QTimer QHttpPrivate::post100ContinueTimer
Referenced by _q_slotConnected(), _q_slotReadyRead(), and init().
QIODevice* QHttpPrivate::postDevice
Referenced by _q_slotClosed(), _q_slotConnected(), _q_slotError(), closeConn(), and postMoreData().
QNetworkProxy QHttpPrivate::proxy
Referenced by _q_slotReadyRead(), and _q_slotSendRequest().
QHttpAuthenticator QHttpPrivate::proxyAuthenticator
Referenced by _q_slotReadyRead(), and _q_slotSendRequest().
QHttp* QHttpPrivate::q_ptr
QRingBuffer QHttpPrivate::rba
Referenced by _q_slotReadyRead().
bool QHttpPrivate::readHeader
Referenced by _q_slotReadyRead().
int QHttpPrivate::reconnectAttempts
Referenced by _q_slotError().
bool QHttpPrivate::repost
Referenced by _q_slotReadyRead().
QHttpResponseHeader QHttpPrivate::response
Referenced by _q_slotClosed(), _q_slotReadyRead(), and _q_slotSendRequest().
QTcpSocket* QHttpPrivate::socket
Referenced by _q_slotConnected(), _q_slotError(), _q_slotReadyRead(), _q_slotSendRequest(), closeConn(), postMoreData(), setSock(), and ~QHttpPrivate().
QHttp::State QHttpPrivate::state
Referenced by _q_slotClosed(), _q_slotConnected(), _q_slotDoFinished(), _q_slotError(), _q_slotReadyRead(), closeConn(), and setState().
QIODevice* QHttpPrivate::toDevice
Referenced by _q_slotReadyRead().
The documentation for this class was generated from the following file:
src/modules/objects/qthttp/qhttp.cpp