KVIrc: KviActionCategory Class Reference
KviActionCategory Class Reference
Holds the categories of an action.
#include <KviAction.h>
Public Member Functions
const QString & description ()
Returns the description of the category.
KviActionCategory (const QString &szName, const QString &szVisibleName, const QString &szDescription)
Constructs an action category object.
const QString & name ()
Returns the name of the category.
const QString & visibleName ()
Returns the visible name of the category.
~KviActionCategory ()
Destroys an action category object.
Protected Attributes
QString m_szDescription
QString m_szName
QString m_szVisibleName
Detailed Description
Holds the categories of an action.
Known categories are: general (or empty), irc, script
Constructor & Destructor Documentation
KviActionCategory::KviActionCategory (const QString & szName, const QString & szVisibleName, const QString & szDescription)
Constructs an action category object.
Parameters:
szName The name of the category
szVisibleName Permanent visible name, visible at least in the action drawer
szDescription Description of the category
Returns:
KviActionCategory
KviActionCategory::~KviActionCategory ()
Destroys an action category object.
Member Function Documentation
const QString& KviActionCategory::description () [inline]
Returns the description of the category.
Returns:
const QString &
Referenced by KviActionDrawer::fill().
const QString& KviActionCategory::name () [inline]
Returns the name of the category.
Returns:
const QString &
Referenced by ActionEditor::ActionEditor().
const QString& KviActionCategory::visibleName () [inline]
Returns the visible name of the category.
Returns:
const QString &
Referenced by KviActionDrawer::fill().
Member Data Documentation
QString KviActionCategory::m_szDescription [protected]
QString KviActionCategory::m_szName [protected]
QString KviActionCategory::m_szVisibleName [protected]
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviAction.h
src/kvirc/kernel/KviAction.cpp