KVIrc: MenuTreeWidgetItem Class Reference
MenuTreeWidgetItem Class Reference
#include <PopupEditorWindow.h>
Public Member Functions
MenuTreeWidgetItem (QTreeWidget *par, KviKvsPopupMenu *popup)
KviKvsPopupMenu * popup ()
void replacePopup (KviKvsPopupMenu *popup)
~MenuTreeWidgetItem ()
Public Attributes
KviKvsPopupMenu * m_pPopup
Constructor & Destructor Documentation
MenuTreeWidgetItem::MenuTreeWidgetItem (QTreeWidget * par, KviKvsPopupMenu * popup)
References g_pIconManager, KviIconManager::getSmallIcon(), m_pPopup, popup(), KviIconManager::Popup, and KviKvsPopupMenu::popupName().
MenuTreeWidgetItem::~MenuTreeWidgetItem ()
References m_pPopup.
Member Function Documentation
KviKvsPopupMenu* MenuTreeWidgetItem::popup () [inline]
References m_pPopup.
Referenced by PopupEditorWidget::exportCurrentPopup(), PopupEditorWidget::exportPopups(), MenuTreeWidgetItem(), and replacePopup().
void MenuTreeWidgetItem::replacePopup (KviKvsPopupMenu * popup)
References m_pPopup, and popup().
Referenced by PopupEditorWidget::popupRefresh(), and PopupEditorWidget::saveLastEditedItem().
Member Data Documentation
KviKvsPopupMenu* MenuTreeWidgetItem::m_pPopup
Referenced by PopupEditorWidget::commit(), SinglePopupEditor::edit(), PopupEditorWidget::getUniquePopupName(), MenuTreeWidgetItem(), popup(), PopupEditorWidget::popupRefresh(), replacePopup(), PopupEditorWidget::saveLastEditedItem(), and ~MenuTreeWidgetItem().
The documentation for this class was generated from the following files:
src/modules/popupeditor/PopupEditorWindow.h
src/modules/popupeditor/PopupEditorWindow.cpp