KVIrc: KviWindowListItem Class Reference
KviWindowListItem Class Reference
#include <kvi_windowlist.h>
Public Member Functions
virtual bool active ()
virtual void captionChanged ()
virtual void highlight (int)
int highlightLevel ()
KviWindow * kviWindow ()
KviWindowListItem (KviWindow *wnd)
int progress ()
virtual void setProgress (int)
virtual void unhighlight ()
virtual ~KviWindowListItem ()
Protected Attributes
int m_iHighlightLevel
int m_iProgress
KviWindow * m_pWindow
Constructor & Destructor Documentation
KviWindowListItem::KviWindowListItem (KviWindow * wnd)
References m_iHighlightLevel, m_iProgress, and m_pWindow.
KviWindowListItem::~KviWindowListItem () [virtual]
References m_pWindow, and KviWindow::m_pWindowListItem.
Member Function Documentation
virtual bool KviWindowListItem::active () [inline, virtual]
Reimplemented in KviWindowListButton.
virtual void KviWindowListItem::captionChanged () [inline, virtual]
Reimplemented in KviWindowListButton, and KviTreeWindowListItem.
Referenced by KviWindow::updateCaption().
virtual void KviWindowListItem::highlight (int) [inline, virtual]
Reimplemented in KviWindowListButton, and KviTreeWindowListItem.
Referenced by KviWindow::highlightMe(), and KviWindow::internalOutput().
int KviWindowListItem::highlightLevel () [inline]
Referenced by KviWindow::highlightMeter(), and KviWindowListBase::switchWindow().
KviWindow* KviWindowListItem::kviWindow () [inline]
Referenced by KviClassicWindowList::insertButton(), KviTreeWindowListTreeWidget::mousePressEvent(), KviTreeWindowListItemDelegate::paint(), and KviWindowListBase::switchWindow().
int KviWindowListItem::progress () [inline]
Referenced by KviTreeWindowListItem::setProgress(), and KviWindowListButton::setProgress().
virtual void KviWindowListItem::setProgress (int) [inline, virtual]
Reimplemented in KviWindowListButton, and KviTreeWindowListItem.
Referenced by KviWindow::setProgress().
virtual void KviWindowListItem::unhighlight () [inline, virtual]
Reimplemented in KviWindowListButton, and KviTreeWindowListItem.
Referenced by KviWindow::unhighlight(), and KviChannel::unhighlight().
Member Data Documentation
int KviWindowListItem::m_iHighlightLevel [protected]
Referenced by KviWindowListButton::drawButtonLabel(), KviTreeWindowListItem::highlight(), KviWindowListButton::highlight(), KviWindowListItem(), KviWindowListButton::setActive(), KviTreeWindowListItem::unhighlight(), and KviWindowListButton::unhighlight().
int KviWindowListItem::m_iProgress [protected]
Referenced by KviWindowListButton::drawButtonLabel(), KviWindowListItem(), KviTreeWindowListItem::setProgress(), and KviWindowListButton::setProgress().
KviWindow* KviWindowListItem::m_pWindow [protected]
Referenced by KviTreeWindowListItem::captionChanged(), KviWindowListButton::contextMenuEvent(), KviWindowListButton::drawButtonLabel(), KviTreeWindowListItem::key(), KviWindowListItem(), KviWindowListButton::mousePressEvent(), KviWindowListButton::tipRequest(), and ~KviWindowListItem().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_windowlist.h
src/kvirc/ui/kvi_windowlist.cpp