KVIrc: KviTextIconWindow Class Reference
KviTextIconWindow Class Reference
Text icon window class.
#include <KviTextIconWindow.h>
Public Slots
void cellSelected (int row, int column)
Called when a cell is selected.
void fill ()
Fills in the text icon window.
void ownerDead ()
Called when the owner is destroyed. Then it calls doHide()
Public Member Functions
KviTextIconWindow ()
Constructs the text icon window objet.
void popup (QWidget *pOwner, bool bAltMode)
Shows the popup.
~KviTextIconWindow ()
Destroys the text icon window objet.
Private Member Functions
void doHide ()
Hides the widget and set the focus to the owner.
virtual void keyPressEvent (QKeyEvent *e)
Private Attributes
bool m_bAltMode
QWidget * m_pOwner
QTableWidget * m_pTable
Detailed Description
Text icon window class.
Constructor & Destructor Documentation
KviTextIconWindow::KviTextIconWindow ()
Constructs the text icon window objet.
Returns:
KviTextIconWindow
References cellSelected(), connect(), fill(), g_pTextIconManager, KVI_TEXTICON_WIN_HEIGHT, KVI_TEXTICON_WIN_WIDTH, m_bAltMode, m_pOwner, and m_pTable.
KviTextIconWindow::~KviTextIconWindow ()
Destroys the text icon window objet.
References m_pTable.
Member Function Documentation
void KviTextIconWindow::cellSelected (int row, int column) slot
Called when a cell is selected.
Parameters:
row The row containing selected item
column The column containing selected item
Returns:
void
References doHide(), KviControlCodes::Icon, m_bAltMode, m_pOwner, and m_pTable.
Referenced by keyPressEvent(), and KviTextIconWindow().
void KviTextIconWindow::doHide () private
Hides the widget and set the focus to the owner.
Returns:
void
References m_pOwner.
Referenced by cellSelected(), keyPressEvent(), and ownerDead().
void KviTextIconWindow::fill () slot
Fills in the text icon window.
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), g_pTextIconManager, i, KVI_TEXTICON_COLUMNS, m_pTable, and KviTextIconManager::textIconDict().
Referenced by KviTextIconWindow().
void KviTextIconWindow::keyPressEvent (QKeyEvent * e) private virtual
References cellSelected(), doHide(), and m_pTable.
void KviTextIconWindow::ownerDead () slot
Called when the owner is destroyed. Then it calls doHide()
Returns:
void
References doHide(), and m_pOwner.
Referenced by popup().
void KviTextIconWindow::popup (QWidget * pOwner, bool bAltMode)
Shows the popup.
Parameters:
pOwner The owner of the widget
bAltMode Whether to prepend the CTRL+I escape code in the inserted string
Returns:
void
References connect(), m_bAltMode, m_pOwner, and ownerDead().
Referenced by KviInput::iconButtonClicked(), and KviInputEditor::insertIcon().
Member Data Documentation
bool KviTextIconWindow::m_bAltMode private
Referenced by cellSelected(), KviTextIconWindow(), and popup().
QWidget* KviTextIconWindow::m_pOwner private
Referenced by cellSelected(), doHide(), KviTextIconWindow(), ownerDead(), and popup().
QTableWidget* KviTextIconWindow::m_pTable private
Referenced by cellSelected(), fill(), keyPressEvent(), KviTextIconWindow(), and ~KviTextIconWindow().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviTextIconWindow.h
src/kvirc/ui/KviTextIconWindow.cpp