KVIrc: KviDefaultScriptManager Class Reference
KviDefaultScriptManager Class Reference
The manager who handles the restoring of the default script.
#include <KviDefaultScript.h>
Public Member Functions
unsigned int count ()
Returns the number of instances of the class.
bool isDefscriptUpToDate ()
Checks if the local defscript is up to date.
KviDefaultScriptManager ()
Constructs the default script manager.
void load (const QString &szConfigFile)
Loads the configuration of the default script.
void loadEmptyConfig ()
Initilizes an empty configuration.
void restore ()
Restores the default script.
void save (const QString &szConfigFile)
Saves the configuration of the default script.
~KviDefaultScriptManager ()
Destroys the default script manager.
Static Public Member Functions
static void done ()
Destroys the class instance.
static void init ()
Initializes the class instance.
static KviDefaultScriptManager * instance ()
Returns the instance of the class.
Private Member Functions
bool compareVersions (QString &szConfig, QString *pszError)
Compares versions between global and personal data.
void loadInternal (KviConfigurationFile *pCfg)
Loads the configuration of the default script.
void restoreInternal ()
Restores the default script.
void saveInternal (KviConfigurationFile *pCfg)
Saves the configuration of the default script.
Private Attributes
bool m_bConfigFileMissing
bool m_bNoNeedToRestore
KviDefaultScriptDialog * m_pDialog
QString m_szAction
QString m_szAddon
QString m_szAlias
QString m_szClass
QString m_szDate
QString m_szEvent
QString m_szPopup
QString m_szRaw
QString m_szToolbar
QString m_szVersion
Static Private Attributes
static KviDefaultScriptManager * m_pSelf = NULL
static unsigned int m_uCount = 0
Detailed Description
The manager who handles the restoring of the default script.
Constructor & Destructor Documentation
KviDefaultScriptManager::KviDefaultScriptManager ()
Constructs the default script manager.
Returns
KviDefaultScriptManager
References KviApplication::Config, KviMemory::copy(), KviApplication::DefScript, KviApplication::firstTimeRun(), g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), m_bConfigFileMissing, and m_bNoNeedToRestore.
Referenced by init().
KviDefaultScriptManager::~KviDefaultScriptManager ()
Destroys the default script manager.
Member Function Documentation
bool KviDefaultScriptManager::compareVersions (QString & szConfig, QString * pszError) private
Compares versions between global and personal data.
Parameters
szConfig The global configuration file
pszError The buffer containing errors
Returns
bool
References __tr2qs, CHECK, KviStringConversion::fromString(), m_bNoNeedToRestore, m_szAction, m_szAlias, m_szClass, m_szDate, m_szEvent, m_szPopup, m_szRaw, m_szToolbar, m_szVersion, KviConfigurationFile::Read, and KviConfigurationFile::readEntry().
Referenced by restore().
unsigned int KviDefaultScriptManager::count () inline
Returns the number of instances of the class.
Returns
unsigned int
Referenced by done(), and init().
void KviDefaultScriptManager::done () static
Destroys the class instance.
Returns
void
References count(), m_pSelf, and m_uCount.
Referenced by KviApplication::~KviApplication().
void KviDefaultScriptManager::init () static
Initializes the class instance.
Returns
void
References count(), KviDefaultScriptManager(), m_pSelf, and m_uCount.
Referenced by KviApplication::setup().
static KviDefaultScriptManager* KviDefaultScriptManager::instance () inline static
Returns the instance of the class.
Returns
KviDefaultScriptManager *
Referenced by KviApplication::checkSuggestRestoreDefaultScript(), KviApplication::restoreDefaultScript(), KviApplication::saveDefaultScripts(), and KviApplication::setup().
bool KviDefaultScriptManager::isDefscriptUpToDate ()
Checks if the local defscript is up to date.
Returns
bool
References KviApplication::DefScript, KviStringConversion::fromString(), g_pApp, KviApplication::getGlobalKvircDirectory(), m_bConfigFileMissing, m_szDate, KviConfigurationFile::Read, and KviConfigurationFile::readEntry().
void KviDefaultScriptManager::load (const QString & szConfigFile)
Loads the configuration of the default script.
This is an external helper to the real function
Parameters
szConfigFile The file where to load
Returns
void
References loadInternal(), and KviConfigurationFile::Read.
Referenced by KviApplication::setup().
void KviDefaultScriptManager::loadEmptyConfig ()
Initilizes an empty configuration.
Returns
void
References m_szAction, m_szAddon, m_szAlias, m_szClass, m_szDate, m_szEvent, m_szPopup, m_szRaw, m_szToolbar, and m_szVersion.
Referenced by KviApplication::setup().
void KviDefaultScriptManager::loadInternal (KviConfigurationFile * pCfg) private
Loads the configuration of the default script.
This is the real function
Parameters
pCfg The configuration file
Returns
void
References IS_EMPTY, m_szAction, m_szAddon, m_szAlias, m_szClass, m_szDate, m_szEvent, m_szPopup, m_szRaw, m_szToolbar, m_szVersion, and KviConfigurationFile::readEntry().
Referenced by load().
void KviDefaultScriptManager::restore ()
Restores the default script.
If this function is suggested by KVIrc, the default script will be wiped out and then it will be reloaded. Otherwise, when the user wants to restore it, he can choose which part of the default script have to be restored
This is an external helper to the real function
Returns
void
References __tr2qs, compareVersions(), KviApplication::DefScript, g_pApp, KviApplication::getGlobalKvircDirectory(), m_bNoNeedToRestore, m_pDialog, restoreInternal(), and KviMessageBox::warning().
Referenced by KviApplication::restoreDefaultScript().
void KviDefaultScriptManager::restoreInternal () private
Restores the default script.
This is the real function
Returns
void
Todo:
This function still misses class clearing due to a missing function in class editor
References KviCustomToolBarManager::clear(), KviKvs::clearAliases(), KviKvs::clearAppEvents(), KviKvs::clearPopups(), KviKvs::clearRawEvents(), KviKvs::clearScriptAddons(), KviApplication::DefScript, g_pApp, KviApplication::getGlobalKvircDirectory(), KviCustomToolBarManager::instance(), KviActionManager::instance(), KviActionManager::killAllKvsUserActions(), KviApplication::loadDefaultScript(), KviDefaultScriptDialog::m_pAction, KviDefaultScriptDialog::m_pAddon, KviDefaultScriptDialog::m_pAlias, KviDefaultScriptDialog::m_pAll, KviDefaultScriptDialog::m_pClass, KviDefaultScriptDialog::m_pData, m_pDialog, KviDefaultScriptDialog::m_pEvent, KviDefaultScriptDialog::m_pPopup, KviDefaultScriptDialog::m_pRaw, KviDefaultScriptDialog::m_pToolbar, m_szAction, m_szAddon, m_szAlias, m_szClass, m_szDate, m_szEvent, m_szPopup, m_szRaw, m_szToolbar, m_szVersion, KviConfigurationFile::Read, and KviConfigurationFile::readEntry().
Referenced by restore().
void KviDefaultScriptManager::save (const QString & szConfigFile)
Saves the configuration of the default script.
This is an external helper to the real function
Parameters
szConfigFile The file to save
Returns
void
References KviConfigurationFile::clear(), saveInternal(), and KviConfigurationFile::Write.
Referenced by KviApplication::saveDefaultScripts().
void KviDefaultScriptManager::saveInternal (KviConfigurationFile * pCfg) private
Saves the configuration of the default script.
This is the real function
Parameters
pCfg The configuration file
Returns
void
References m_szAction, m_szAddon, m_szAlias, m_szClass, m_szDate, m_szEvent, m_szPopup, m_szRaw, m_szToolbar, m_szVersion, and KviConfigurationFile::writeEntry().
Referenced by save().
Member Data Documentation
bool KviDefaultScriptManager::m_bConfigFileMissing private
Referenced by isDefscriptUpToDate(), and KviDefaultScriptManager().
bool KviDefaultScriptManager::m_bNoNeedToRestore private
Referenced by compareVersions(), KviDefaultScriptManager(), and restore().
KviDefaultScriptDialog* KviDefaultScriptManager::m_pDialog private
Referenced by restore(), and restoreInternal().
KviDefaultScriptManager * KviDefaultScriptManager::m_pSelf = NULL static private
Referenced by done(), and init().
QString KviDefaultScriptManager::m_szAction private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szAddon private
Referenced by loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szAlias private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szClass private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szDate private
Referenced by compareVersions(), isDefscriptUpToDate(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szEvent private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szPopup private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szRaw private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szToolbar private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
QString KviDefaultScriptManager::m_szVersion private
Referenced by compareVersions(), loadEmptyConfig(), loadInternal(), restoreInternal(), and saveInternal().
unsigned int KviDefaultScriptManager::m_uCount = 0 static private
Referenced by done(), and init().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviDefaultScript.h
src/kvirc/kernel/KviDefaultScript.cpp