KVIrc: KviKvsModuleInterface Class Reference
KviKvsModuleInterface Class Reference
#include <KviKvsModuleInterface.h>
Public Member Functions
void completeCommand (const QString &cmd, KviPointerList< QString > *matches)
void completeFunction (const QString &cmd, KviPointerList< QString > *matches)
void getAllFunctionsCommandsModule (QStringList *list, QString &szModuleName)
KviKvsModuleInterface ()
KviKvsModuleCallbackCommandExecRoutine * kvsFindCallbackCommand (const QString &szCommand)
KviKvsModuleFunctionExecRoutine * kvsFindFunction (const QString &szFunction)
KviKvsModuleSimpleCommandExecRoutine * kvsFindSimpleCommand (const QString &szCommand)
bool kvsRegisterAppEventHandler (unsigned int iEventIdx, KviKvsModuleEventHandlerRoutine r)
void kvsRegisterCallbackCommand (const QString &szCommand, KviKvsModuleCallbackCommandExecRoutine r)
void kvsRegisterFunction (const QString &szFunction, KviKvsModuleFunctionExecRoutine r)
bool kvsRegisterRawEventHandler (unsigned int iRawIdx, KviKvsModuleEventHandlerRoutine r)
void kvsRegisterSimpleCommand (const QString &szCommand, KviKvsModuleSimpleCommandExecRoutine r)
void kvsUnregisterAllAppEventHandlers ()
void kvsUnregisterAllCallbackCommands ()
void kvsUnregisterAllEventHandlers ()
void kvsUnregisterAllFunctions ()
void kvsUnregisterAllRawEventHandlers ()
void kvsUnregisterAllSimpleCommands ()
void kvsUnregisterAppEventHandler (unsigned int iEventIdx)
void kvsUnregisterCallbackCommand (const QString &szCommand)
void kvsUnregisterFunction (const QString &szFunction)
void kvsUnregisterRawEventHandler (unsigned int iRawIdx)
void kvsUnregisterSimpleCommand (const QString &szCommand)
~KviKvsModuleInterface ()
Protected Member Functions
void registerDefaultCommands ()
Protected Attributes
KviPointerHashTable< QString,
KviKvsModuleCallbackCommandExecRoutine > * m_pModuleCallbackCommandExecRoutineDict
KviPointerHashTable< QString,
KviKvsModuleFunctionExecRoutine > * m_pModuleFunctionExecRoutineDict
KviPointerHashTable< QString,
KviKvsModuleSimpleCommandExecRoutine > * m_pModuleSimpleCommandExecRoutineDict
Friends
class KviKvsModuleManager
Constructor & Destructor Documentation
KviKvsModuleInterface::KviKvsModuleInterface ()
References m_pModuleCallbackCommandExecRoutineDict, m_pModuleFunctionExecRoutineDict, m_pModuleSimpleCommandExecRoutineDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviKvsModuleInterface::~KviKvsModuleInterface ()
References kvsUnregisterAllEventHandlers(), m_pModuleCallbackCommandExecRoutineDict, m_pModuleFunctionExecRoutineDict, and m_pModuleSimpleCommandExecRoutineDict.
Member Function Documentation
void KviKvsModuleInterface::completeCommand (const QString & cmd, KviPointerList< QString > * matches)
References COMPLETE_WORD_BY_DICT, m_pModuleCallbackCommandExecRoutineDict, and m_pModuleSimpleCommandExecRoutineDict.
Referenced by KviKvsKernel::completeModuleCommand().
void KviKvsModuleInterface::completeFunction (const QString & cmd, KviPointerList< QString > * matches)
References COMPLETE_WORD_BY_DICT, and m_pModuleFunctionExecRoutineDict.
Referenced by KviKvsKernel::completeModuleFunction().
void KviKvsModuleInterface::getAllFunctionsCommandsModule (QStringList * list, QString & szModuleName)
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pModuleFunctionExecRoutineDict, and m_pModuleSimpleCommandExecRoutineDict.
Referenced by ScriptEditorWidget::asyncCompleterCreation().
KviKvsModuleCallbackCommandExecRoutine* KviKvsModuleInterface::kvsFindCallbackCommand (const QString & szCommand) inline
Referenced by KviKvsTreeNodeModuleCallbackCommand::execute().
KviKvsModuleFunctionExecRoutine* KviKvsModuleInterface::kvsFindFunction (const QString & szFunction) inline
Referenced by KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly().
KviKvsModuleSimpleCommandExecRoutine* KviKvsModuleInterface::kvsFindSimpleCommand (const QString & szCommand) inline
Referenced by KviKvsTreeNodeModuleSimpleCommand::execute(), and KviKvsCoreSimpleCommands::KVSCSC().
bool KviKvsModuleInterface::kvsRegisterAppEventHandler (unsigned int iEventIdx, KviKvsModuleEventHandlerRoutine r)
References h, and KviKvsEventManager::instance().
Referenced by fish_module_init(), and url_module_init().
void KviKvsModuleInterface::kvsRegisterCallbackCommand (const QString & szCommand, KviKvsModuleCallbackCommandExecRoutine r)
References m_pModuleCallbackCommandExecRoutineDict, and KviPointerHashTable< Key, T >::replace().
void KviKvsModuleInterface::kvsRegisterFunction (const QString & szFunction, KviKvsModuleFunctionExecRoutine r)
References m_pModuleFunctionExecRoutineDict, and KviPointerHashTable< Key, T >::replace().
bool KviKvsModuleInterface::kvsRegisterRawEventHandler (unsigned int iRawIdx, KviKvsModuleEventHandlerRoutine r)
References h, and KviKvsEventManager::instance().
void KviKvsModuleInterface::kvsRegisterSimpleCommand (const QString & szCommand, KviKvsModuleSimpleCommandExecRoutine r)
References m_pModuleSimpleCommandExecRoutineDict, and KviPointerHashTable< Key, T >::replace().
Referenced by registerDefaultCommands().
void KviKvsModuleInterface::kvsUnregisterAllAppEventHandlers ()
References KviKvsEventManager::instance(), and KviKvsEventManager::removeAllModuleAppHandlers().
Referenced by kvsUnregisterAllEventHandlers().
void KviKvsModuleInterface::kvsUnregisterAllCallbackCommands () inline
void KviKvsModuleInterface::kvsUnregisterAllEventHandlers ()
References kvsUnregisterAllAppEventHandlers(), and kvsUnregisterAllRawEventHandlers().
Referenced by ~KviKvsModuleInterface().
void KviKvsModuleInterface::kvsUnregisterAllFunctions () inline
void KviKvsModuleInterface::kvsUnregisterAllRawEventHandlers ()
References KviKvsEventManager::instance(), and KviKvsEventManager::removeAllModuleRawHandlers().
Referenced by kvsUnregisterAllEventHandlers().
void KviKvsModuleInterface::kvsUnregisterAllSimpleCommands () inline
void KviKvsModuleInterface::kvsUnregisterAppEventHandler (unsigned int iEventIdx)
References KviKvsEventManager::instance(), and KviKvsEventManager::removeModuleAppHandler().
void KviKvsModuleInterface::kvsUnregisterCallbackCommand (const QString & szCommand) inline
void KviKvsModuleInterface::kvsUnregisterFunction (const QString & szFunction) inline
void KviKvsModuleInterface::kvsUnregisterRawEventHandler (unsigned int iRawIdx)
References KviKvsEventManager::instance(), and KviKvsEventManager::removeModuleRawHandler().
void KviKvsModuleInterface::kvsUnregisterSimpleCommand (const QString & szCommand) inline
void KviKvsModuleInterface::registerDefaultCommands () protected
References default_module_kvs_cmd_load(), default_module_kvs_cmd_unload(), and kvsRegisterSimpleCommand().
Referenced by KviModuleManager::loadModule().
Friends And Related Function Documentation
friend class KviKvsModuleManager friend
Member Data Documentation
KviPointerHashTable<QString,KviKvsModuleCallbackCommandExecRoutine>* KviKvsModuleInterface::m_pModuleCallbackCommandExecRoutineDict protected
Referenced by completeCommand(), KviKvsModuleInterface(), kvsRegisterCallbackCommand(), and ~KviKvsModuleInterface().
KviPointerHashTable<QString,KviKvsModuleFunctionExecRoutine>* KviKvsModuleInterface::m_pModuleFunctionExecRoutineDict protected
Referenced by completeFunction(), getAllFunctionsCommandsModule(), KviKvsModuleInterface(), kvsRegisterFunction(), and ~KviKvsModuleInterface().
KviPointerHashTable<QString,KviKvsModuleSimpleCommandExecRoutine>* KviKvsModuleInterface::m_pModuleSimpleCommandExecRoutineDict protected
Referenced by completeCommand(), getAllFunctionsCommandsModule(), KviKvsModuleInterface(), kvsRegisterSimpleCommand(), and ~KviKvsModuleInterface().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsModuleInterface.h
src/kvirc/kvs/KviKvsModuleInterface.cpp