KVIrc: KviKvsPopupMenuTopLevelData Class Reference
KviKvsPopupMenuTopLevelData Class Reference
#include <KviKvsPopupMenu.h>
Public Types
enum LockStatus { Unlocked, SoftLocked, HardLocked }
Public Member Functions
KviKvsExtendedRunTimeData * extendedRunTimeData ()
bool isHardLocked ()
bool isSoftLocked ()
KviKvsPopupMenuTopLevelData (KviKvsVariantList *pParameters, KviWindow *pWindow)
KviKvsVariantList * parameters ()
void setLocked (LockStatus eLocked)
void setTestMode (bool bTestMode)
void setWindow (KviWindow *pWindow)
bool testMode ()
KviWindow * window ()
~KviKvsPopupMenuTopLevelData ()
Protected Attributes
bool m_bTestMode
LockStatus m_eLocked
KviKvsExtendedRunTimeData * m_pExtendedRunTimeData
KviKvsVariantList * m_pParameters
KviWindow * m_pWindow
Friends
class KviKvsPopupMenu
Member Enumeration Documentation
enum KviKvsPopupMenuTopLevelData::LockStatus
Enumerator:
Unlocked
SoftLocked
HardLocked
Constructor & Destructor Documentation
KviKvsPopupMenuTopLevelData::KviKvsPopupMenuTopLevelData (KviKvsVariantList * pParameters, KviWindow * pWindow)
References m_bTestMode, m_eLocked, m_pExtendedRunTimeData, m_pParameters, m_pWindow, and Unlocked.
KviKvsPopupMenuTopLevelData::~KviKvsPopupMenuTopLevelData ()
References m_pExtendedRunTimeData, and m_pParameters.
Member Function Documentation
KviKvsExtendedRunTimeData* KviKvsPopupMenuTopLevelData::extendedRunTimeData () [inline]
Referenced by KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), KviKvsPopupMenu::executeEpilogues(), KviKvsPopupMenu::executePrologues(), and KviKvsPopupMenu::itemClicked().
bool KviKvsPopupMenuTopLevelData::isHardLocked () [inline]
Referenced by KviKvsPopupMenu::isHardLocked().
bool KviKvsPopupMenuTopLevelData::isSoftLocked () [inline]
Referenced by KviKvsPopupMenu::isSoftLocked().
KviKvsVariantList* KviKvsPopupMenuTopLevelData::parameters () [inline]
Referenced by KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), KviKvsPopupMenu::executeEpilogues(), KviKvsPopupMenu::executePrologues(), and KviKvsPopupMenu::itemClicked().
void KviKvsPopupMenuTopLevelData::setLocked (LockStatus eLocked) [inline]
Referenced by KviKvsPopupMenu::lock().
void KviKvsPopupMenuTopLevelData::setTestMode (bool bTestMode) [inline]
Referenced by KviKvsPopupMenu::doPopup().
void KviKvsPopupMenuTopLevelData::setWindow (KviWindow * pWindow) [inline]
Referenced by KviKvsPopupMenu::itemClicked(), and KviKvsPopupMenu::setupMenuContents().
bool KviKvsPopupMenuTopLevelData::testMode () [inline]
Referenced by KviKvsPopupMenu::itemClicked(), and KviKvsPopupMenu::setupMenuContents().
KviWindow* KviKvsPopupMenuTopLevelData::window () [inline]
Referenced by KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), KviKvsPopupMenu::executeEpilogues(), KviKvsPopupMenu::executePrologues(), KviKvsPopupMenuItemExtMenu::fill(), KviKvsPopupMenu::itemClicked(), and KviKvsPopupMenu::setupMenuContents().
Friends And Related Function Documentation
friend class KviKvsPopupMenu [friend]
Member Data Documentation
bool KviKvsPopupMenuTopLevelData::m_bTestMode [protected]
Referenced by KviKvsPopupMenuTopLevelData().
LockStatus KviKvsPopupMenuTopLevelData::m_eLocked [protected]
Referenced by KviKvsPopupMenuTopLevelData().
KviKvsExtendedRunTimeData* KviKvsPopupMenuTopLevelData::m_pExtendedRunTimeData [protected]
Referenced by KviKvsPopupMenuTopLevelData(), and ~KviKvsPopupMenuTopLevelData().
KviKvsVariantList* KviKvsPopupMenuTopLevelData::m_pParameters [protected]
Referenced by KviKvsPopupMenuTopLevelData(), and ~KviKvsPopupMenuTopLevelData().
KviWindow* KviKvsPopupMenuTopLevelData::m_pWindow [protected]
Referenced by KviKvsPopupMenuTopLevelData().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupMenu.h
src/kvirc/kvs/KviKvsPopupMenu.cpp