KVIrc: KviModeWidget Class Reference
KviModeWidget Class Reference
#include <KviModeWidget.h>
Public Slots
void editorReturnPressed ()
Signals
void setMode (QString &szMode)
Public Member Functions
KviModeWidget (QWidget *par, KviChannelWindow *chan, const char *name=0)
void refreshModes ()
void reset ()
~KviModeWidget ()
Public Member Functions inherited from KviThemedLineEdit
void applyOptions ()
int dummyRead () const
KviThemedLineEdit (QWidget *par, KviWindow *pWindow, const char *name)
~KviThemedLineEdit ()
Protected Member Functions
void keyReleaseEvent (QKeyEvent *e)
bool modeNeedsParameterOnlyWhenSet (char cMode)
void mouseDoubleClickEvent (QMouseEvent *e)
Protected Member Functions inherited from KviThemedLineEdit
virtual void paintEvent (QPaintEvent *event)
Private Attributes
KviChannelWindow * m_pChannel
Additional Inherited Members
Properties inherited from KviThemedLineEdit
int TransparencyCapable
Constructor & Destructor Documentation
KviModeWidget::KviModeWidget (QWidget * par, KviChannelWindow * chan, const char * name = 0)
References m_pChannel, and reset().
KviModeWidget::~KviModeWidget ()
Member Function Documentation
void KviModeWidget::editorReturnPressed () slot
References KviChannelWindow::channelModeParam(), KviChannelWindow::getChannelModeStringWithEmbeddedParams(), KviChannelWindow::hasChannelMode(), i, j, m_pChannel, KviIrcConnectionServerInfo::maxModeChanges(), modeNeedsParameterOnlyWhenSet(), reset(), KviChannelWindow::serverInfo(), and setMode().
Referenced by keyReleaseEvent().
void KviModeWidget::keyReleaseEvent (QKeyEvent * e) protected
References editorReturnPressed(), and reset().
bool KviModeWidget::modeNeedsParameterOnlyWhenSet (char cMode) inline protected
References m_pChannel, KviChannelWindow::serverInfo(), and KviIrcConnectionServerInfo::supportedParameterWhenSetModes().
Referenced by editorReturnPressed().
void KviModeWidget::mouseDoubleClickEvent (QMouseEvent * e) protected
References KviWindow::connection(), KviIrcConnectionUserInfo::hasUserMode(), KviChannelWindow::isMeChanAdmin(), KviChannelWindow::isMeChanOwner(), KviChannelWindow::isMeHalfOp(), KviChannelWindow::isMeOp(), m_pChannel, and KviIrcConnection::userInfo().
void KviModeWidget::refreshModes ()
References KviChannelWindow::getChannelModeStringWithEmbeddedParams(), and m_pChannel.
Referenced by reset(), and KviChannelWindow::updateModeLabel().
void KviModeWidget::reset ()
References KviWindow::input(), m_pChannel, and refreshModes().
Referenced by editorReturnPressed(), keyReleaseEvent(), and KviModeWidget().
void KviModeWidget::setMode (QString & szMode) signal
Referenced by editorReturnPressed().
Member Data Documentation
KviChannelWindow* KviModeWidget::m_pChannel private
Referenced by editorReturnPressed(), KviModeWidget(), modeNeedsParameterOnlyWhenSet(), mouseDoubleClickEvent(), refreshModes(), and reset().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviModeWidget.h
src/kvirc/ui/KviModeWidget.cpp