KVIrc: KviKvsObject Class Reference
KviKvsObject Class Reference
#include <KviKvsObject.h>
Public Member Functions
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Protected Slots
void delayedDie ()
void objectDestroyed ()
Protected Member Functions
virtual bool eventFilter (QObject *o, QEvent *e)
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Private Member Functions
void callDestructor ()
Friends
class KviKvsObjectClass
class KviKvsObjectController
Constructor & Destructor Documentation
KviKvsObject::KviKvsObject (KviKvsObjectClass * pClass, KviKvsObject * pParent, const QString & szName)
References g_hNextObjectHandle, KviKvsKernel::instance(), m_bAboutToDie, m_bDestructorCalled, m_bInDelayedDeath, m_bObjectOwner, m_hObject, m_pChildList, m_pClass, m_pConnectionList, m_pDataContainer, m_pFunctionHandlers, m_pObject, m_pSignalDict, m_szName, KviKvsKernel::objectController(), registerChild(), KviKvsObjectController::registerObject(), and KviPointerList< T >::setAutoDelete().
KviKvsObject::~KviKvsObject () virtual
References callDestructor(), KviPointerHashTableEntry< Key, T >::data(), dieNow(), disconnectSignal(), KviPointerList< T >::first(), KviKvsKernel::instance(), KviPointerHashTableEntry< Key, T >::key(), KVI_ASSERT_MSG, m_bAboutToDie, m_bDestructorCalled, m_bObjectOwner, m_pChildList, m_pConnectionList, m_pDataContainer, m_pFunctionHandlers, m_pObject, m_pSignalDict, KviKvsKernel::objectController(), objectDestroyed(), parentObject(), _KviKvsObjectConnection::pSourceObject, _KviKvsObjectConnection::szSignal, unregisterChild(), and KviKvsObjectController::unregisterObject().
Member Function Documentation
void KviKvsObject::callDestructor () private
References callFunction(), KVI_ASSERT, m_bAboutToDie, and m_bDestructorCalled.
Referenced by delayedDie(), dieNow(), and ~KviKvsObject().
bool KviKvsObject::callFunction (KviKvsObject * pCaller, const QString & fncName, const QString & classOverride, KviKvsRunTimeContext * pContext, KviKvsVariant * pRetVal, KviKvsVariantList * pParams)
References __tr2qs_ctx(), KviKvsObjectFunctionHandler::call(), KviKvsRunTimeContext::error(), KviKvsObjectFunctionHandler::flags(), getClass(), h, KviKvsObjectFunctionHandler::Internal, lookupFunctionHandler(), m_szName, and KviRuntimeInfo::name().
Referenced by KvsObject_wizard::accept(), KviKvsObjectClass::allocateInstance(), KvsObject_textBrowser::anchorClicked(), KvsObject_wizard::backClicked(), callDestructor(), callFunction(), KvsObject_tableWidget::cellActivated(), KvsObject_tableWidget::cellDoubleClicked(), KviXmlHandler::characters(), KvsObject_listWidget::currentItemChanged(), KvsObject_comboBox::editTextChanged(), emitSignal(), KviXmlHandler::endDocument(), KviXmlHandler::endElement(), KviXmlHandler::error(), KviKvsTreeNodeThisObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeBaseObjectFunctionCall::evaluateReadOnlyInObjectScope(), KvsObject_widget::eventFilter(), KvsObject_treeWidget::fileDropped(), KvsObject_pixmap::frameChanged(), KvsObject_wizard::nextClicked(), KvsObject_tableWidget::paint(), KvsObject_wizard::reject(), KvsObject_listWidget::selectionChanged(), KviCellItemDelegate::sizeHint(), KvsObject_trayIcon::slotActivated(), KvsObject_comboBox::slotActivated(), KvsObject_button::slotClicked(), KvsObject_toolButton::slotClicked(), KvsObject_treeWidget::slotClicked(), KvsObject_colorDialog::slotColorSelected(), KvsObject_ftp::slotCommandFinished(), KvsObject_socket::slotConnected(), KvsObject_tabWidget::slotCurrentChanged(), KvsObject_treeWidget::slotCurrentChanged(), KvsObject_colorDialog::slotCurrentColorChanged(), KvsObject_http::slotDataReadProgress(), KvsObject_http::slotDataSendProgress(), KvsObject_ftp::slotDataTransferProgress(), KvsObject_dateTimeEdit::slotDateChanged(), KvsObject_dateTimeEdit::slotDateTimeChanged(), KvsObject_socket::slotDisconnected(), KvsObject_http::slotDone(), KvsObject_socket::slotError(), KvsObject_socket::slotHostFound(), KvsObject_popupMenu::slothovered(), KvsObject_treeWidget::slotItemActivated(), KvsObject_listWidget::slotItemChanged(), KvsObject_treeWidget::slotItemChanged(), KvsObject_treeWidget::slotItemCollapsed(), KvsObject_listWidget::slotItemEntered(), KvsObject_tableWidget::slotItemEntered(), KvsObject_treeWidget::slotItemExpanded(), KvsObject_ftp::slotListInfo(), KvsObject_lineEdit::slotlostFocus(), KvsObject_trayIcon::slotMessageClicked(), KvsObject_socket::slotNewConnection(), KvsObject_treeWidget::slotOnItemEntered(), KvsObject_process::slotReadStderr(), KvsObject_process::slotReadStdout(), KvsObject_socket::slotReadyRead(), KvsObject_http::slotReadyRead(), KvsObject_http::slotRequestFinished(), KvsObject_http::slotRequestStarted(), KvsObject_http::slotResponseHeaderReceived(), KvsObject_lineEdit::slotreturnPressed(), KvsObject_treeWidget::slotSelectionChanged(), KvsObject_http::slotSslErrors(), KvsObject_ftp::slotStateChanged(), KvsObject_socket::slotStateChanged(), KvsObject_http::slotStateChanged(), KvsObject_tabWidget::slotTabCloseRequest(), KvsObject_lineEdit::slottextChanged(), KvsObject_dateTimeEdit::slotTimeChanged(), KvsObject_popupMenu::slottriggered(), KviXmlHandler::startDocument(), KviXmlHandler::startElement(), timerEvent(), KvsObject_checkBox::toggled(), KvsObject_radioButton::toggled(), KvsObject_slider::valueChanged(), KvsObject_spinBox::valueChanged(), and KviXmlHandler::warning().
bool KviKvsObject::callFunction (KviKvsObject * pCaller, const QString & fncName, KviKvsVariantList * pParams = 0)
References callFunction().
bool KviKvsObject::callFunction (KviKvsObject * pCaller, const QString & fncName, KviKvsVariant * pRetVal, KviKvsVariantList * pParams = 0)
References KviApplication::activeConsole(), callFunction(), KviKvsKernel::emptyParameterList(), g_pApp, and KviKvsKernel::instance().
bool KviKvsObject::connectSignal (const QString & sigName, KviKvsObject * target, const QString & slotName)
References KviPointerList< T >::append(), l, lookupFunctionHandler(), m_pSignalDict, _KviKvsObjectConnection::pSourceObject, _KviKvsObjectConnection::pTargetObject, registerConnection(), KviPointerList< T >::setAutoDelete(), _KviKvsObjectConnection::szSignal, and _KviKvsObjectConnection::szSlot.
Referenced by objects_kvs_cmd_connect().
KviKvsHash* KviKvsObject::dataContainer () inline
Referenced by KviKvsTreeNodeObjectField::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeObjectField::evaluateReadWriteInObjectScope(), and objects_kvs_fnc_variables().
void KviKvsObject::delayedDie () protected slot
References callDestructor(), KVI_ASSERT, m_bAboutToDie, m_bDestructorCalled, and m_bInDelayedDeath.
Referenced by die().
bool KviKvsObject::die ()
References delayedDie(), m_bAboutToDie, and m_bInDelayedDeath.
Referenced by KvsObject_treeWidgetItem::childDestroyed(), KviKvsCoreSimpleCommands::KVSCSC(), and objectDestroyed().
bool KviKvsObject::dieNow ()
References callDestructor(), KVI_ASSERT, m_bAboutToDie, and m_bDestructorCalled.
Referenced by KviKvsObjectClass::allocateInstance(), KviKvsObjectController::clearInstances(), KvsObject_widget::eventFilter(), KviKvsCoreSimpleCommands::KVSCSC(), KvsObject_tableWidget::paint(), KvsObject_socket::slotNewConnection(), ~KviKvsObject(), and KviKvsObjectController::~KviKvsObjectController().
bool KviKvsObject::disconnectSignal (const QString & sigName, KviKvsObjectConnection * con)
References KviPointerList< T >::isEmpty(), l, m_pSignalDict, _KviKvsObjectConnection::pTargetObject, KviPointerList< T >::removeRef(), and unregisterConnection().
Referenced by emitSignal(), objects_kvs_cmd_disconnect(), and ~KviKvsObject().
bool KviKvsObject::disconnectSignal (const QString & sigName, KviKvsObject * target, const QString & slotName)
References KviPointerListIterator< T >::current(), KviQString::equalCI(), KviPointerList< T >::isEmpty(), l, m_pSignalDict, KviPointerList< T >::removeRef(), and unregisterConnection().
int KviKvsObject::emitSignal (const QString & sigName, KviKvsObjectFunctionCall * pOuterCall, KviKvsVariantList * pParams = 0)
References __tr2qs_ctx(), KviPointerList< T >::append(), callFunction(), KviKvsRunTimeCall::context(), KviPointerListIterator< T >::current(), disconnectSignal(), KviPointerList< T >::first(), getClass(), handle(), KviKvsKernel::instance(), l, KviKvsObjectController::lookupObject(), m_hObject, m_pSignalDict, m_szName, KviKvsObjectClass::name(), KviRuntimeInfo::name(), KviPointerList< T >::next(), KviKvsKernel::objectController(), s, KviPointerList< T >::setAutoDelete(), setSignalName(), setSignalSender(), signalSender(), and KviKvsRunTimeCall::warning().
Referenced by function_destructor(), function_emit(), KvsObject_http::functionDataReadProgressEvent(), KvsObject_http::functionDataSendProgressEvent(), KvsObject_http::functionDoneEvent(), KvsObject_http::functionReadyReadEvent(), KvsObject_http::functionRequestFinishedEvent(), KvsObject_http::functionRequestStartedEvent(), KvsObject_http::functionResponseHeaderReceivedEvent(), KvsObject_http::functionSslErrorsEvent(), and KvsObject_http::functionStateChangedEvent().
bool KviKvsObject::eventFilter (QObject * o, QEvent * e) protected virtual
Reimplemented in KvsObject_widget.
Referenced by KvsObject_widget::eventFilter().
KviKvsObject * KviKvsObject::findChild (const QString & szClass, const QString & szName)
References c, KviQString::equalCI(), KviPointerList< T >::first(), m_pChildList, KviPointerList< T >::next(), and o.
Referenced by function_findChild().
bool KviKvsObject::function_childCount (KviKvsObjectFunctionCall * c) protected
References KviPointerList< T >::count(), m_pChildList, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_children (KviKvsObjectFunctionCall * c) protected
References a, KviPointerList< T >::first(), m_pChildList, KviPointerList< T >::next(), o, KviKvsObjectFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_className (KviKvsObjectFunctionCall * c) protected
References getClass(), KviRuntimeInfo::name(), KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_destructor (KviKvsObjectFunctionCall * c) protected
References emitSignal().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_emit (KviKvsObjectFunctionCall * c) protected
References emitSignal(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANTLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_findChild (KviKvsObjectFunctionCall * c) protected
References findChild(), handle(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, o, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setHObject().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_killTimer (KviKvsObjectFunctionCall * c) protected
References KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_listProperties (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), a, KviControlCodes::Bold, KviKvsRunTimeCall::context(), KVI_OUT_SYSTEMMESSAGE, KVS_PF_OPTIONAL, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_pClass, m_pObject, m_szName, KviKvsObjectClass::name(), o, KviWindow::output(), KviWindow::outputNoFmt(), p, KviKvsObjectFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsVariant::setNothing(), w, and KviKvsRunTimeContext::window().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_name (KviKvsObjectFunctionCall * c) protected
References getName(), KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_parent (KviKvsObjectFunctionCall * c) protected
References handle(), o, parentObject(), KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setHObject().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_property (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), a, f, KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_NONEMPTYSTRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_pClass, m_pObject, m_szName, KviKvsObjectClass::name(), p, KviKvsObjectFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsVariant::setBoolean(), KviKvsVariant::setInteger(), KviKvsVariant::setNothing(), KviKvsVariant::setReal(), KviKvsVariant::setString(), v, and KviKvsRunTimeCall::warning().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_setProperty (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), a, KviKvsVariant::array(), KviKvsVariant::asBoolean(), KviKvsVariant::asInteger(), KviKvsVariant::asReal(), KviKvsVariant::asString(), KviKvsArray::at(), g, g_pIconManager, KviIconManager::getImage(), h, KviKvsVariant::hobject(), i, KviControlCodes::Icon, KviKvsKernel::instance(), KviKvsVariant::isArray(), KviKvsVariant::isHObject(), KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pClass, m_pObject, m_szName, KviKvsObjectClass::name(), KviKvsKernel::objectController(), p, r, KviKvsObjectFunctionCall::returnValue(), s, KviKvsVariant::setNothing(), v, w, KviKvsRunTimeCall::warning(), WRONG_TYPE, x, and y.
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_signalName (KviKvsObjectFunctionCall * c) protected
References m_szSignalName, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_signalSender (KviKvsObjectFunctionCall * c) protected
References m_hSignalSender, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setHObject().
Referenced by KviKvsObjectController::init().
bool KviKvsObject::function_startTimer (KviKvsObjectFunctionCall * c) protected
References KVS_PT_UINT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by KviKvsObjectController::init().
KviPointerHashTable<QString, KviKvsObjectFunctionHandler>* KviKvsObject::functionHandlers () inline
References KviKvsObjectClass::m_pFunctionHandlers.
KviKvsObjectClass * KviKvsObject::getClass (const QString & classOverride = QString())
References KviQString::equalCI(), m_pClass, KviKvsObjectClass::m_pParentClass, and KviKvsObjectClass::name().
Referenced by callFunction(), emitSignal(), function_className(), killAllChildrenWithClass(), KviKvsObjectController::killAllObjectsWithClass(), and lookupFunctionHandler().
KviKvsObjectClass* KviKvsObject::getExactClass () inline
const QString& KviKvsObject::getName () inline
References KviKvsObjectClass::m_szName.
Referenced by function_name(), KvsObject_dockWindow::init(), and objects_kvs_fnc_name().
kvs_hobject_t KviKvsObject::handle () inline
Referenced by emitSignal(), KvsObject_widget::eventFilter(), function_findChild(), function_parent(), KvsObject_treeWidgetItem::itemToHandle(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), KvsObject_tableWidget::paint(), KviKvsObjectController::registerObject(), KvsObject_socket::slotNewConnection(), and KviKvsObjectController::unregisterObject().
bool KviKvsObject::inheritsClass (KviKvsObjectClass * pClass)
References m_pClass, and KviKvsObjectClass::m_pParentClass.
Referenced by inheritsClass(), and KVSO_CLASS_FUNCTION().
bool KviKvsObject::inheritsClass (const QString & szClass)
References inheritsClass(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), and KviKvsKernel::objectController().
bool KviKvsObject::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) protected virtual
Reimplemented in KvsObject_tableWidget, KvsObject_window, KvsObject_widget, KvsObject_lineEdit, KvsObject_treeWidget, KvsObject_socket, KvsObject_wizard, KvsObject_treeWidgetItem, KvsObject_dateTimeEdit, KvsObject_comboBox, KvsObject_popupMenu, KvsObject_textBrowser, KvsObject_checkBox, KvsObject_colorDialog, KvsObject_wrapper, KvsObject_button, KvsObject_groupBox, KvsObject_listWidget, KvsObject_textedit, KvsObject_radioButton, KvsObject_slider, KvsObject_spinBox, KvsObject_tabWidget, KvsObject_toolButton, KvsObject_vBox, KvsObject_workspace, KvsObject_dialog, KvsObject_label, KvsObject_mainWindow, KvsObject_menuBar, KvsObject_progressBar, KvsObject_toolBar, KvsObject_dockWindow, KvsObject_hBox, KvsObject_lcd, and KvsObject_layout.
Referenced by KviKvsObjectClass::allocateInstance().
void KviKvsObject::killAllChildrenWithClass (KviKvsObjectClass * cl)
References KviPointerList< T >::append(), KviPointerList< T >::first(), getClass(), killAllChildrenWithClass(), m_pChildList, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by killAllChildrenWithClass(), and KviKvsObjectController::killAllObjectsWithClass().
KviKvsObjectFunctionHandler * KviKvsObject::lookupFunctionHandler (const QString & funcName, const QString & classOverride = QString())
References KviPointerHashTable< Key, T >::find(), getClass(), h, KviKvsObjectClass::lookupFunctionHandler(), and m_pFunctionHandlers.
Referenced by callFunction(), and connectSignal().
QObject* KviKvsObject::object () const inline
Referenced by KvsObject_textedit::functionzoomIn(), KvsObject_textedit::functionzoomOut(), KVSO_CLASS_FUNCTION(), parentScriptWidget(), KvsObject_layout::widget(), KvsObject_hBox::widget(), KvsObject_lcd::widget(), KvsObject_menuBar::widget(), KvsObject_workspace::widget(), KvsObject_mainWindow::widget(), KvsObject_dialog::widget(), KvsObject_label::widget(), KvsObject_progressBar::widget(), KvsObject_toolBar::widget(), KvsObject_vBox::widget(), KvsObject_button::widget(), KvsObject_groupBox::widget(), KvsObject_tabWidget::widget(), KvsObject_textedit::widget(), KvsObject_radioButton::widget(), KvsObject_slider::widget(), KvsObject_spinBox::widget(), KvsObject_wizard::widget(), KvsObject_listWidget::widget(), KvsObject_toolButton::widget(), KvsObject_wrapper::widget(), KvsObject_colorDialog::widget(), KvsObject_checkBox::widget(), KvsObject_textBrowser::widget(), KvsObject_popupMenu::widget(), KvsObject_comboBox::widget(), KvsObject_lineEdit::widget(), KvsObject_dateTimeEdit::widget(), KvsObject_treeWidget::widget(), KvsObject_widget::widget(), KvsObject_tableWidget::widget(), and KvsObject_window::widget().
void KviKvsObject::objectDestroyed () protected slot
References die(), and m_pObject.
Referenced by setObject(), and ~KviKvsObject().
KviKvsObject* KviKvsObject::parentObject () inline
Referenced by function_parent(), parentScriptWidget(), and ~KviKvsObject().
QWidget * KviKvsObject::parentScriptWidget ()
References object(), and parentObject().
void KviKvsObject::registerChild (KviKvsObject * c) protected
References KviPointerList< T >::append(), and m_pChildList.
Referenced by KviKvsObject().
void KviKvsObject::registerConnection (KviKvsObjectConnection * con) protected
References KviPointerList< T >::append(), m_pConnectionList, and KviPointerList< T >::setAutoDelete().
Referenced by connectSignal().
void KviKvsObject::registerPrivateImplementation (const QString & szFunctionName, const QString & szCode)
References KviPointerHashTable< Key, T >::isEmpty(), m_pClass, m_pFunctionHandlers, KviKvsObjectClass::name(), KviPointerHashTable< Key, T >::remove(), KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
void KviKvsObject::setObject (QObject * o, bool bIsOwned = true)
References connect(), m_bObjectOwner, m_pObject, o, and objectDestroyed().
Referenced by KvsObject_dockWindow::init().
void KviKvsObject::setSignalName (const QString & szSigName) inline
Referenced by emitSignal().
void KviKvsObject::setSignalSender (kvs_hobject_t hObject) inline
Referenced by emitSignal().
kvs_hobject_t KviKvsObject::signalSender () inline
Referenced by emitSignal().
void KviKvsObject::timerEvent (QTimerEvent * e) protected virtual
References callFunction(), KviKvsVariant::setInteger(), and v.
void KviKvsObject::unregisterChild (KviKvsObject * c) protected
References m_pChildList, and KviPointerList< T >::removeRef().
Referenced by ~KviKvsObject().
bool KviKvsObject::unregisterConnection (KviKvsObjectConnection * con) protected
References KviPointerList< T >::isEmpty(), m_pConnectionList, and KviPointerList< T >::removeRef().
Referenced by disconnectSignal().
Friends And Related Function Documentation
friend class KviKvsObjectClass friend
friend class KviKvsObjectController friend
Member Data Documentation
bool KviKvsObject::m_bAboutToDie protected
Referenced by callDestructor(), delayedDie(), die(), dieNow(), KviKvsObject(), and ~KviKvsObject().
bool KviKvsObject::m_bDestructorCalled protected
Referenced by callDestructor(), delayedDie(), dieNow(), KviKvsObject(), and ~KviKvsObject().
bool KviKvsObject::m_bInDelayedDeath protected
Referenced by delayedDie(), die(), and KviKvsObject().
bool KviKvsObject::m_bObjectOwner protected
Referenced by KviKvsObject(), setObject(), and ~KviKvsObject().
kvs_hobject_t KviKvsObject::m_hObject protected
Referenced by emitSignal(), and KviKvsObject().
kvs_hobject_t KviKvsObject::m_hSignalSender protected
Referenced by function_signalSender().
KviPointerList<KviKvsObject>* KviKvsObject::m_pChildList protected
Referenced by findChild(), function_childCount(), function_children(), killAllChildrenWithClass(), KviKvsObject(), registerChild(), unregisterChild(), and ~KviKvsObject().
KviKvsObjectClass* KviKvsObject::m_pClass protected
Referenced by function_listProperties(), function_property(), function_setProperty(), getClass(), inheritsClass(), KviKvsObject(), and registerPrivateImplementation().
KviKvsObjectConnectionList* KviKvsObject::m_pConnectionList protected
Referenced by KviKvsObject(), registerConnection(), unregisterConnection(), and ~KviKvsObject().
KviKvsHash* KviKvsObject::m_pDataContainer protected
Referenced by KviKvsObject(), and ~KviKvsObject().
KviPointerHashTable<QString, KviKvsObjectFunctionHandler>* KviKvsObject::m_pFunctionHandlers protected
Referenced by KviKvsObject(), lookupFunctionHandler(), registerPrivateImplementation(), and ~KviKvsObject().
QObject* KviKvsObject::m_pObject protected
Referenced by function_listProperties(), function_property(), function_setProperty(), KviKvsObject(), objectDestroyed(), setObject(), and ~KviKvsObject().
KviPointerHashTable<QString, KviKvsObjectConnectionList>* KviKvsObject::m_pSignalDict protected
Referenced by connectSignal(), disconnectSignal(), emitSignal(), KviKvsObject(), and ~KviKvsObject().
QString KviKvsObject::m_szName protected
Referenced by callFunction(), emitSignal(), function_listProperties(), function_property(), function_setProperty(), and KviKvsObject().
QString KviKvsObject::m_szSignalName protected
Referenced by function_signalName().
The documentation for this class was generated from the following files:
src/kvirc/kvs/object/KviKvsObject.h
src/kvirc/kvs/object/KviKvsObject.cpp