KVIrc: PopupTreeWidgetItem Class Reference
PopupTreeWidgetItem Class Reference
#include <PopupEditorWindow.h>
Public Types
enum Type {
Item, Menu, Separator, Label,
Epilogue, Prologue, ExtMenu
}
Public Member Functions
PopupTreeWidgetItem (QTreeWidget *pTreeWidget, PopupTreeWidgetItem *after, Type t)
PopupTreeWidgetItem (PopupTreeWidgetItem *parent, PopupTreeWidgetItem *after, Type t)
void setCode (const QString &szCode)
void setCondition (const QString &szCondition)
void setIcon (const QString &szIcon)
void setId (const QString &szId)
void setItemText (const QString &szText)
Public Attributes
QString m_szCode
QString m_szCondition
QString m_szIcon
QString m_szId
QString m_szText
Type m_type
Private Member Functions
void init ()
Member Enumeration Documentation
enum PopupTreeWidgetItem::Type
Enumerator:
Item
Menu
Separator
Label
Epilogue
Prologue
ExtMenu
Constructor & Destructor Documentation
PopupTreeWidgetItem::PopupTreeWidgetItem (QTreeWidget * pTreeWidget, PopupTreeWidgetItem * after, Type t)
References init(), m_type, and t.
PopupTreeWidgetItem::PopupTreeWidgetItem (PopupTreeWidgetItem * parent, PopupTreeWidgetItem * after, Type t)
References init(), m_type, and t.
Member Function Documentation
void PopupTreeWidgetItem::init () [private]
References __tr2qs_ctx(), Epilogue, ExtMenu, Item, Label, m_type, Menu, Prologue, and Separator.
Referenced by PopupTreeWidgetItem().
void PopupTreeWidgetItem::setCode (const QString & szCode)
References Epilogue, ExtMenu, Item, m_szCode, m_type, and Prologue.
Referenced by SinglePopupEditor::populateMenu(), and SinglePopupEditor::saveLastSelectedItem().
void PopupTreeWidgetItem::setCondition (const QString & szCondition)
References ExtMenu, Item, Label, m_szCondition, m_type, Menu, and Separator.
Referenced by SinglePopupEditor::populateMenu(), and SinglePopupEditor::saveLastSelectedItem().
void PopupTreeWidgetItem::setIcon (const QString & szIcon)
References ExtMenu, g_pIconManager, KviIconManager::getImage(), Item, Label, m_szIcon, m_type, and Menu.
Referenced by SinglePopupEditor::populateMenu(), and SinglePopupEditor::saveLastSelectedItem().
void PopupTreeWidgetItem::setId (const QString & szId)
References m_szId.
Referenced by SinglePopupEditor::populateMenu(), and SinglePopupEditor::saveLastSelectedItem().
void PopupTreeWidgetItem::setItemText (const QString & szText)
References ExtMenu, Item, Label, m_szText, m_type, and Menu.
Referenced by SinglePopupEditor::populateMenu(), and SinglePopupEditor::saveLastSelectedItem().
Member Data Documentation
QString PopupTreeWidgetItem::m_szCode
Referenced by SinglePopupEditor::addItemToMenu(), SinglePopupEditor::findMatchingItem(), and setCode().
QString PopupTreeWidgetItem::m_szCondition
Referenced by SinglePopupEditor::addItemToMenu(), SinglePopupEditor::findMatchingItem(), and setCondition().
QString PopupTreeWidgetItem::m_szIcon
Referenced by SinglePopupEditor::addItemToMenu(), SinglePopupEditor::findMatchingItem(), and setIcon().
QString PopupTreeWidgetItem::m_szId
Referenced by SinglePopupEditor::addItemToMenu(), SinglePopupEditor::findMatchingItem(), and setId().
QString PopupTreeWidgetItem::m_szText
Referenced by SinglePopupEditor::addItemToMenu(), SinglePopupEditor::findMatchingItem(), and setItemText().
Type PopupTreeWidgetItem::m_type
Referenced by SinglePopupEditor::addItemToMenu(), SinglePopupEditor::contextPasteInside(), SinglePopupEditor::customContextMenuRequested(), SinglePopupEditor::findMatchingItem(), init(), SinglePopupEditor::newItemInside(), PopupTreeWidgetItem(), SinglePopupEditor::saveLastSelectedItem(), setCode(), setCondition(), setIcon(), and setItemText().
The documentation for this class was generated from the following files:
src/modules/popupeditor/PopupEditorWindow.h
src/modules/popupeditor/PopupEditorWindow.cpp