KVIrc: KviKvsTreeNodeConstantData Class Reference
KviKvsTreeNodeConstantData Class Reference
#include <kvi_kvs_treenode_constantdata.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual bool convertStringConstantToNumeric ()
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeConstantData (const QChar *pLocation, KviKvsVariant *v)
KviKvsVariant * value ()
~KviKvsTreeNodeConstantData ()
Protected Attributes
KviKvsVariant * m_pValue
Constructor & Destructor Documentation
KviKvsTreeNodeConstantData::KviKvsTreeNodeConstantData (const QChar * pLocation, KviKvsVariant * v)
References m_pValue.
KviKvsTreeNodeConstantData::~KviKvsTreeNodeConstantData ()
References m_pValue.
Member Function Documentation
void KviKvsTreeNodeConstantData::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
bool KviKvsTreeNodeConstantData::convertStringConstantToNumeric () [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::asInteger(), KviKvsVariant::asReal(), KviKvsVariant::isString(), m_pValue, KviKvsVariant::setInteger(), and KviKvsVariant::setReal().
void KviKvsTreeNodeConstantData::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References debug, KviKvsVariant::dump(), and m_pValue.
bool KviKvsTreeNodeConstantData::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::copyFrom(), and m_pValue.
KviKvsVariant* KviKvsTreeNodeConstantData::value () [inline]
Member Data Documentation
KviKvsVariant* KviKvsTreeNodeConstantData::m_pValue [protected]
Referenced by convertStringConstantToNumeric(), dump(), evaluateReadOnly(), KviKvsTreeNodeConstantData(), and ~KviKvsTreeNodeConstantData().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_treenode_constantdata.h
src/kvirc/kvs/kvi_kvs_treenode_constantdata.cpp