KVIrc: EventEditor Class Reference
EventEditor Class Reference
#include <EventEditorWindow.h>
Public Member Functions
void commit ()
EventEditor (QWidget *par)
void getExportEventBuffer (QString &szBuffer, EventEditorHandlerTreeWidgetItem *it)
void getUniqueHandlerName (EventEditorEventTreeWidgetItem *it, QString &buffer)
void saveLastEditedItem ()
~EventEditor ()
Public Attributes
bool m_bOneTimeSetupDone
KviTalPopupMenu * m_pContextPopup
KviScriptEditor * m_pEditor
EventEditorHandlerTreeWidgetItem * m_pLastEditedItem
QLineEdit * m_pNameEditor
EventEditorTreeWidget * m_pTreeWidget
Protected Slots
void addHandlerForCurrentEvent ()
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *)
void eventHandlerDisabled (const QString &szName)
void exportAllEvents ()
void exportCurrentHandler ()
void itemPressed (QTreeWidgetItem *it, const QPoint &pnt)
void removeCurrentHandler ()
void toggleCurrentHandlerEnabled ()
Protected Member Functions
void showEvent (QShowEvent *e)
Private Member Functions
void oneTimeSetup ()
Constructor & Destructor Documentation
EventEditor::EventEditor (QWidget * par)
References __tr2qs_ctx(), connect(), KviScriptEditor::createInstance(), exportAllEvents(), l, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, m_pNameEditor, m_pTreeWidget, KviTalVBox::setMargin(), KviTalVBox::setSpacing(), and spl.
EventEditor::~EventEditor ()
References KviScriptEditor::destroyInstance(), and m_pEditor.
Member Function Documentation
void EventEditor::addHandlerForCurrentEvent () [protected, slot]
References __tr2qs_ctx(), KviIconManager::Event, g_pIconManager, KviIconManager::getSmallIcon(), getUniqueHandlerName(), KVI_ASSERT, m_bOneTimeSetupDone, and m_pTreeWidget.
Referenced by itemPressed().
void EventEditor::commit (void)
References KviKvsEventManager::addAppHandler(), KviKvsScriptEventHandler::createInstance(), g_pApp, i, KviKvsEventManager::instance(), j, m_bOneTimeSetupDone, m_pTreeWidget, KviKvsEventManager::removeAllScriptAppHandlers(), s, KviApplication::saveAppEvents(), and saveLastEditedItem().
Referenced by EventEditorWindow::applyClicked(), and EventEditorWindow::okClicked().
void EventEditor::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem *) [protected, slot]
References __tr2qs_ctx(), KviCommandFormatter::indent(), KVI_ASSERT, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, m_pNameEditor, EventEditorHandlerTreeWidgetItem::m_szBuffer, EventEditorHandlerTreeWidgetItem::name(), saveLastEditedItem(), KviScriptEditor::setCursorPosition(), and KviScriptEditor::setText().
Referenced by oneTimeSetup(), and toggleCurrentHandlerEnabled().
void EventEditor::eventHandlerDisabled (const QString & szName) [protected, slot]
References KviQString::equalCI(), i, j, m_pTreeWidget, KviOsInfo::name(), and EventEditorEventTreeWidgetItem::name().
Referenced by oneTimeSetup().
void EventEditor::exportAllEvents () [protected, slot]
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), getExportEventBuffer(), i, j, KVI_PATH_SEPARATOR, m_pTreeWidget, saveLastEditedItem(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by EventEditor().
void EventEditor::exportCurrentHandler () [protected, slot]
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), getExportEventBuffer(), KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, m_pLastEditedItem, EventEditorHandlerTreeWidgetItem::m_szName, saveLastEditedItem(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by itemPressed().
void EventEditor::getExportEventBuffer (QString & szBuffer, EventEditorHandlerTreeWidgetItem * it)
References KviCommandFormatter::blockFromBuffer(), EventEditorHandlerTreeWidgetItem::m_bEnabled, EventEditorHandlerTreeWidgetItem::m_szBuffer, and EventEditorHandlerTreeWidgetItem::m_szName.
Referenced by exportAllEvents(), and exportCurrentHandler().
void EventEditor::getUniqueHandlerName (EventEditorEventTreeWidgetItem * it, QString & buffer)
References __tr2qs_ctx(), KviQString::equalCI(), i, KVI_ASSERT, and m_bOneTimeSetupDone.
Referenced by addHandlerForCurrentEvent(), and saveLastEditedItem().
void EventEditor::itemPressed (QTreeWidgetItem * it, const QPoint & pnt) [protected, slot]
References __tr2qs_ctx(), addHandlerForCurrentEvent(), KviTalPopupMenu::clear(), exportCurrentHandler(), KviIconManager::Folder, g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Handler, KviIconManager::HandlerDisabled, KviTalPopupMenu::insertItem(), KVI_ASSERT, m_bOneTimeSetupDone, m_pContextPopup, KviIconManager::Quit, removeCurrentHandler(), and toggleCurrentHandlerEnabled().
Referenced by oneTimeSetup().
void EventEditor::oneTimeSetup () [private]
References KviKvsEventManager::appEvent(), connect(), currentItemChanged(), e, KviIconManager::Event, eventHandlerDisabled(), KviIconManager::EventNoHandlers, g_pIconManager, KviIconManager::getSmallIcon(), KviKvsEvent::handlers(), i, KviKvsEventManager::instance(), itemPressed(), KVI_KVS_NUM_APP_EVENTS, l, m_bOneTimeSetupDone, m_pContextPopup, m_pTreeWidget, KviOsInfo::name(), KviKvsEvent::name(), KviKvsEvent::parameterDescription(), s, and KviKvsEventHandler::Script.
Referenced by showEvent().
void EventEditor::removeCurrentHandler () [protected, slot]
References KviIconManager::EventNoHandlers, g_pIconManager, KviIconManager::getSmallIcon(), KVI_ASSERT, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, and m_pNameEditor.
Referenced by itemPressed().
void EventEditor::saveLastEditedItem ()
References KviQString::equalCI(), KviScriptEditor::getCursor(), KviScriptEditor::getText(), getUniqueHandlerName(), KVI_ASSERT, m_bOneTimeSetupDone, m_pEditor, m_pLastEditedItem, m_pNameEditor, EventEditorHandlerTreeWidgetItem::m_szBuffer, EventEditorHandlerTreeWidgetItem::m_szName, and EventEditorHandlerTreeWidgetItem::setName().
Referenced by commit(), currentItemChanged(), exportAllEvents(), and exportCurrentHandler().
void EventEditor::showEvent (QShowEvent * e) [protected]
References oneTimeSetup().
void EventEditor::toggleCurrentHandlerEnabled () [protected, slot]
References currentItemChanged(), KVI_ASSERT, EventEditorHandlerTreeWidgetItem::m_bEnabled, m_bOneTimeSetupDone, m_pLastEditedItem, m_pTreeWidget, and EventEditorHandlerTreeWidgetItem::setEnabled().
Referenced by itemPressed().
Member Data Documentation
bool EventEditor::m_bOneTimeSetupDone
Referenced by addHandlerForCurrentEvent(), commit(), currentItemChanged(), EventEditor(), getUniqueHandlerName(), itemPressed(), oneTimeSetup(), removeCurrentHandler(), saveLastEditedItem(), and toggleCurrentHandlerEnabled().
KviTalPopupMenu* EventEditor::m_pContextPopup
Referenced by itemPressed(), and oneTimeSetup().
KviScriptEditor* EventEditor::m_pEditor
Referenced by currentItemChanged(), EventEditor(), removeCurrentHandler(), saveLastEditedItem(), and ~EventEditor().
EventEditorHandlerTreeWidgetItem* EventEditor::m_pLastEditedItem
Referenced by currentItemChanged(), EventEditor(), exportCurrentHandler(), removeCurrentHandler(), saveLastEditedItem(), and toggleCurrentHandlerEnabled().
QLineEdit* EventEditor::m_pNameEditor
Referenced by currentItemChanged(), EventEditor(), removeCurrentHandler(), and saveLastEditedItem().
EventEditorTreeWidget* EventEditor::m_pTreeWidget
Referenced by addHandlerForCurrentEvent(), commit(), EventEditor(), eventHandlerDisabled(), exportAllEvents(), oneTimeSetup(), and toggleCurrentHandlerEnabled().
The documentation for this class was generated from the following files:
src/modules/eventeditor/EventEditorWindow.h
src/modules/eventeditor/EventEditorWindow.cpp