KVIrc: KviAction Class Reference
KviAction Class Reference
Defines an action inside KVIrc.
#include <KviAction.h>
Public Types
enum Flags {
NeedsContext = 1, NeedsConnection = 2, WindowConsole = 4, WindowChannel = 8,
WindowQuery = 16, WindowDccChat = 32, InternalWindowMask = WindowConsole | WindowChannel | WindowQuery | WindowDccChat, EnableAtLogin = 64,
WindowOnlyIfUsersSelected = 128
}
Holds the flags of an action.
enum InternalFlags { Enabled = 1, SetupDone = 2 }
Holds the internal flags of an action.
Public Slots
virtual void activate ()
Activates the action.
Signals
void activated ()
Emitted when the action is being activated.
Public Member Functions
virtual QAction * addToCustomToolBar (KviCustomToolBar *pParentToolBar)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
QPixmap * bigIcon ()
Returns the big icon associated to the action.
const QString & bigIconId () const
Returns the id of the big icon associated to the action.
KviActionCategory * category () const
Returns the category of the action.
virtual const QString & description ()
Returns the description of the action.
unsigned int flags ()
Returns the flag associated to the action.
bool isEnabled () const
Returns true if the action is enabled.
virtual bool isKviUserActionNeverOverrideThis ()
Returns true if the action is user-defined.
const QString & keySequence () const
Returns the shortcut of the action.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const KviIconManager::SmallIcon eIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
const QString & name () const
Returns the name of the action.
virtual void setEnabled (bool bEnabled)
Enables the action.
QPixmap * smallIcon ()
Returns the small icon associated to the action.
const QString & smallIconId () const
Returns the id of the small icon associated to the action.
void suicide ()
Destroys itself. Maybe the best function in the whole APIs :)
virtual const QString & visibleName ()
Returns the visible name of the action.
virtual ~KviAction ()
Destroys the action object.
Static Public Member Functions
static int validateFlags (int iFlagsToValidate)
Validates the flags of the action.
Protected Slots
virtual void actionDestroyed ()
Removes the action from the list.
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual void activeWindowChanged ()
Enables or disables the action upon checking the active window.
virtual void activeWindowSelectionStateChanged (bool bSelectedNow)
Enables or disables the action upon checking the active window.
virtual void reloadImages ()
Reloads the images.
Protected Member Functions
KviPointerList< QAction > * actionList ()
Returns the list of actions associated to the action.
void registerAccelerator ()
Registers the action shortcut in the application.
void registerAction (QAction *pAction)
Adds the action to the list.
virtual void setup ()
Enables or disables the action upon starting KVIrc.
bool setupDone () const
Returns true if the setup is finished.
void unregisterAccelerator ()
Removes the action shortcut from the application.
Protected Attributes
QString m_eIcon
QPointer< QShortcut > m_pAccel
KviPointerList< QAction > * m_pActionList
KviActionCategory * m_pCategory
QString m_szBigIconId
QString m_szDescription
QString m_szKeySequence
QString m_szName
QString m_szSmallIconId
QString m_szVisibleName
unsigned int m_uFlags
unsigned short int m_uInternalFlags
Friends
class KviActionManager
Detailed Description
Defines an action inside KVIrc.
Member Enumeration Documentation
enum KviAction::Flags
Holds the flags of an action.
Enumerator
NeedsContext
the action needs a context
NeedsConnection
the action needs a connection; implies NeedsContext
WindowConsole
the action is bound to a console window
WindowChannel
the action is bound to a channel window
WindowQuery
the action is bound to a query window
WindowDccChat
the action is bound to a DCC Chat window
InternalWindowMask
the action is bound to a window
EnableAtLogin
the action is enabled at login; implies NeedsConnection
WindowOnlyIfUsersSelected
the action is bound to a window only if it's selected by the user; implies at least one of WindowConsole | WindowChannel | WindowQuery
enum KviAction::InternalFlags
Holds the internal flags of an action.
Enumerator
Enabled
the action is enabled
SetupDone
the setup of the action is done
Constructor & Destructor Documentation
KviAction::KviAction (QObject * pParent, const QString & szName, const QString & szVisibleName, const QString & szDescription, KviActionCategory * pCategory = NULL, const QString & szBigIconId = QString(), const QString & szSmallIconId = QString(), unsigned int uFlags = 0, const QString & szKeySequence = QString())
Constructs the action object.
Parameters
pParent The parent object
It can be 0, but using a QObject will help in deleting this action :)
Parameters
szName Internal name of this action, in form [module.]name
szVisibleName Permanent visible name, visible at least in the action drawer
szDescription What this action does
pCategory One of KviActionManager::category*() or 0 (default category), not owned!
szBigIconId The big icon associated to the action (32x32)
szSmallIconId The small icon associated to the action (16x16)
uFlags The flags of the action, like needs and configuration
szKeySequence The shortcut to activate the action
Note
The action name is INTERNAL: it should be never shown to the user. If it contains a dot then the part before the dot is considered to be a module name to be loaded when the module is loaded.
Returns
KviAction
KviAction::KviAction (QObject * pParent, const QString & szName, const QString & szVisibleName, const QString & szDescription, KviActionCategory * pCategory = NULL, const QString & szBigIconId = QString(), const KviIconManager::SmallIcon eIcon = KviIconManager::None, unsigned int uFlags = 0, const QString & szKeySequence = QString())
Constructs the action object.
Parameters
pParent The parent object
It can be 0, but using a QObject will help in deleting this action :)
Parameters
szName Internal name of this action, in form [module.]name
szVisibleName Permanent visible name, visible at least in the action drawer
szDescription What this action does
pCategory One of KviActionManager::category*() or 0 (default category), not owned!
szBigIconId The big icon associated to the action (32x32)
eIcon The small icon associated to the action (16x16)
uFlags The flags of the action, like needs and configuration
szKeySequence The shortcut to activate the action
Note
The action name is INTERNAL: it should be never shown to the user. If it contains a dot then the part before the dot is considered to be a module name to be loaded when the module is loaded.
Returns
KviAction
KviAction::~KviAction () virtual
Destroys the action object.
References actionDestroyed(), KviPointerList< T >::first(), m_pAccel, m_pActionList, KviPointerList< T >::next(), KviPointerList< T >::setAutoDelete(), and unregisterAccelerator().
Member Function Documentation
void KviAction::actionDestroyed () protected virtual slot
Removes the action from the list.
Called when the action is being destroyed
Returns
void
References m_pActionList, and KviPointerList< T >::removeRef().
Referenced by registerAction(), and ~KviAction().
KviPointerList<QAction>* KviAction::actionList () inline protected
Returns the list of actions associated to the action.
Returns
KviPointerList<QAction> *
Referenced by KviConnectAction::activeContextStateChanged(), and KviGoAwayAction::activeContextStateChanged().
void KviAction::activate () virtual slot
Activates the action.
It's called when the user activates the action clicking on the toolbar, the menu or by hitting its shortcut.
Returns
void
Reimplemented in KviKvsAction, and KviConnectAction.
References activated(), and isEnabled().
Referenced by action_kvs_cmd_trigger(), addToCustomToolBar(), addToPopupMenu(), and registerAccelerator().
void KviAction::activated () signal
Emitted when the action is being activated.
Returns
void
Referenced by activate(), and registerAccelerator().
void KviAction::activeContextChanged () protected virtual slot
Enables or disables the action upon checking the active context.
If the context doesn't exist, the action is disabled
Called when the frame changes the active context.
Note
It works only if NeedsContext is specified
Returns
void
Reimplemented in KviGoAwayAction, KviIrcContextDisplayAction, and KviConnectAction.
References KviMainWindow::activeContext(), activeContextStateChanged(), g_pMainWindow, isEnabled(), m_uFlags, NeedsConnection, and setEnabled().
Referenced by setup().
void KviAction::activeContextStateChanged () protected virtual slot
Enables or disables the action upon checking the active context.
Called when the frame changes the state of the context
Returns
void
Reimplemented in KviGoAwayAction, KviIrcContextDisplayAction, and KviConnectAction.
References KviMainWindow::activeContext(), KviIrcContext::Connected, KviIrcContext::Connecting, EnableAtLogin, g_pMainWindow, KviIrcContext::Idle, isEnabled(), KviIrcContext::LoggingIn, m_uFlags, setEnabled(), and KviIrcContext::state().
Referenced by activeContextChanged(), and setup().
void KviAction::activeWindowChanged () protected virtual slot
Enables or disables the action upon checking the active window.
Called when the frame changes the active window.
Returns
void
References KviMainWindow::activeContext(), KviWindow::Channel, KviIrcContext::Connected, KviWindow::Console, KviWindow::DccChat, EnableAtLogin, g_pActiveWindow, g_pMainWindow, InternalWindowMask, isEnabled(), KviIrcContext::LoggingIn, m_uFlags, NeedsConnection, NeedsContext, KviWindow::Query, setEnabled(), KviIrcContext::state(), KviWindow::type(), WindowChannel, WindowConsole, WindowDccChat, WindowOnlyIfUsersSelected, and WindowQuery.
Referenced by setup().
void KviAction::activeWindowSelectionStateChanged (bool bSelectedNow) protected virtual slot
Enables or disables the action upon checking the active window.
Called when the frame changes the active window.
Note
We jump here ONLY if m_uFlags & WindowOnlyIfUsersSelected and thus also m_uFlags & InternalWindowMask
Returns
void
References KviWindow::Channel, KviWindow::Console, KviWindow::DccChat, g_pActiveWindow, isEnabled(), m_uFlags, KviWindow::Query, setEnabled(), KviWindow::type(), WindowChannel, WindowConsole, WindowDccChat, and WindowQuery.
Referenced by setup().
QAction * KviAction::addToCustomToolBar (KviCustomToolBar * pParentToolBar) virtual
Adds the action to the given toolbar.
Parameters
pParentToolBar The toolbar where to add the action
Returns
QAction *
Reimplemented in KviGoAwayAction, KviIrcContextDisplayAction, KviSubmenuAction, KviSeparatorAction, and KviConnectAction.
References activate(), bigIcon(), connect(), isEnabled(), m_szName, registerAction(), setup(), setupDone(), and visibleName().
Referenced by KviCustomToolBarDescriptor::addAction(), KviCustomToolBar::dragEnterEvent(), and KviCustomToolBarDescriptor::fillToolBar().
bool KviAction::addToPopupMenu (QMenu * pMenu) virtual
Adds the action to the given popup.
Parameters
pMenu The menu where to add the action
Returns
bool
Reimplemented in KviGoAwayAction, KviIrcContextDisplayAction, KviSubmenuAction, KviSeparatorAction, and KviConnectAction.
References activate(), isEnabled(), m_szKeySequence, registerAction(), setup(), setupDone(), smallIcon(), and visibleName().
Referenced by KviIrcToolsAction::popupAboutToShow(), and KviIrcOperationsAction::popupAboutToShow().
QPixmap * KviAction::bigIcon ()
Returns the big icon associated to the action.
Returns
QPixmap *
References g_pIconManager, KviIconManager::getImage(), m_szBigIconId, and NULL.
Referenced by KviSubmenuAction::addToCustomToolBar(), addToCustomToolBar(), KviCustomToolBar::eventFilter(), KviActionDrawerPageListWidgetItem::KviActionDrawerPageListWidgetItem(), KviActionDrawerPageListWidget::mousePressEvent(), and reloadImages().
const QString& KviAction::bigIconId () const inline
Returns the id of the big icon associated to the action.
Returns
const QString &
KviActionCategory* KviAction::category () const inline
Returns the category of the action.
Returns
const QString &
const QString & KviAction::description () virtual
Returns the description of the action.
Returns
const QString &
Reimplemented in KviKvsUserAction.
References m_szDescription.
Referenced by KviActionDrawerPageListWidgetItem::KviActionDrawerPageListWidgetItem().
unsigned int KviAction::flags () inline
Returns the flag associated to the action.
Returns
unsigned int
bool KviAction::isEnabled () const inline
Returns true if the action is enabled.
Returns
bool
References Enabled.
Referenced by action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_trigger(), action_kvs_fnc_isEnabled(), KviKvsAction::activate(), activate(), activeContextChanged(), activeContextStateChanged(), activeWindowChanged(), activeWindowSelectionStateChanged(), KviSubmenuAction::addToCustomToolBar(), addToCustomToolBar(), KviSubmenuAction::addToPopupMenu(), and addToPopupMenu().
bool KviAction::isKviUserActionNeverOverrideThis () virtual
Returns true if the action is user-defined.
Warning
By default, this function returns always false
Returns
bool
Reimplemented in KviKvsUserAction.
Referenced by action_kvs_cmd_create(), action_kvs_cmd_destroy(), KviActionManager::coreActionExists(), CustomizeToolBarsDialog::exportToolBar(), and KviActionDrawerPageListWidgetItem::KviActionDrawerPageListWidgetItem().
const QString& KviAction::keySequence () const inline
Returns the shortcut of the action.
Returns
const QString &
const QString& KviAction::name () const inline
Returns the name of the action.
Returns
const QString &
Referenced by KviActionManager::actionDestroyed(), KviSubmenuAction::addToCustomToolBar(), KviActionDrawerPageListWidgetItem::KviActionDrawerPageListWidgetItem(), and KviActionManager::registerAction().
void KviAction::registerAccelerator () protected
Registers the action shortcut in the application.
Returns
void
References activate(), activated(), connect(), KviMainWindow::freeAccelleratorKeySequence(), g_pMainWindow, m_pAccel, m_szKeySequence, and NULL.
Referenced by KviActionManager::registerAction().
void KviAction::registerAction (QAction * pAction) protected
Adds the action to the list.
Parameters
pAction The action to add
Returns
void
References actionDestroyed(), KviPointerList< T >::append(), connect(), m_pActionList, and KviPointerList< T >::setAutoDelete().
Referenced by KviConnectAction::addToCustomToolBar(), KviSeparatorAction::addToCustomToolBar(), KviSubmenuAction::addToCustomToolBar(), KviIrcContextDisplayAction::addToCustomToolBar(), KviGoAwayAction::addToCustomToolBar(), addToCustomToolBar(), and addToPopupMenu().
void KviAction::reloadImages () protected virtual slot
Reloads the images.
Called when the application wants to refresh the images in the toolbar
Returns
void
Reimplemented in KviGoAwayAction, and KviConnectAction.
References bigIcon(), KviPointerList< T >::first(), m_pActionList, and KviPointerList< T >::next().
Referenced by setup().
void KviAction::setEnabled (bool bEnabled) virtual
Enables the action.
Parameters
bEnabled Whether to enable the action
Returns
void
Reimplemented in KviIrcContextDisplayAction.
References Enabled, KviPointerList< T >::first(), m_pActionList, m_uInternalFlags, and KviPointerList< T >::next().
Referenced by action_kvs_cmd_disable(), action_kvs_cmd_enable(), activeContextChanged(), KviGoAwayAction::activeContextStateChanged(), activeContextStateChanged(), activeWindowChanged(), activeWindowSelectionStateChanged(), and setup().
void KviAction::setup () protected virtual
Enables or disables the action upon starting KVIrc.
Returns
void
Reimplemented in KviGoAwayAction, KviIrcContextDisplayAction, KviSubmenuAction, and KviConnectAction.
References KviMainWindow::activeContext(), activeContextChanged(), activeContextStateChanged(), activeWindowChanged(), activeWindowSelectionStateChanged(), connect(), KviIrcContext::Connected, EnableAtLogin, g_pApp, g_pMainWindow, InternalWindowMask, KviIrcContext::LoggingIn, m_uFlags, m_uInternalFlags, NeedsConnection, NeedsContext, reloadImages(), setEnabled(), SetupDone, KviIrcContext::state(), WindowChannel, WindowConsole, WindowOnlyIfUsersSelected, and WindowQuery.
Referenced by KviSeparatorAction::addToCustomToolBar(), addToCustomToolBar(), KviSeparatorAction::addToPopupMenu(), addToPopupMenu(), KviConnectAction::setup(), KviSubmenuAction::setup(), KviIrcContextDisplayAction::setup(), and KviGoAwayAction::setup().
bool KviAction::setupDone () const inline protected
Returns true if the setup is finished.
Note
Called once before the FIRST button or menu item is created
Returns
bool
References SetupDone.
Referenced by KviConnectAction::addToCustomToolBar(), KviSeparatorAction::addToCustomToolBar(), KviSubmenuAction::addToCustomToolBar(), KviIrcContextDisplayAction::addToCustomToolBar(), KviGoAwayAction::addToCustomToolBar(), addToCustomToolBar(), KviConnectAction::addToPopupMenu(), KviSeparatorAction::addToPopupMenu(), KviSubmenuAction::addToPopupMenu(), KviGoAwayAction::addToPopupMenu(), and addToPopupMenu().
QPixmap * KviAction::smallIcon ()
Returns the small icon associated to the action.
Returns
QPixmap *
References g_pIconManager, KviIconManager::getImage(), m_szSmallIconId, and NULL.
Referenced by KviSubmenuAction::addToPopupMenu(), addToPopupMenu(), KviJoinChannelAction::popupAboutToShow(), and KviChangeNickAction::popupAboutToShow().
const QString& KviAction::smallIconId () const inline
Returns the id of the small icon associated to the action.
Returns
const QString &
void KviAction::suicide () inline
Destroys itself. Maybe the best function in the whole APIs :)
Returns
void
Referenced by action_kvs_cmd_create(), and action_kvs_cmd_destroy().
void KviAction::unregisterAccelerator () protected
Removes the action shortcut from the application.
Returns
void
References m_pAccel, and NULL.
Referenced by KviActionManager::unregisterAction(), and ~KviAction().
int KviAction::validateFlags (int iFlagsToValidate) static
Validates the flags of the action.
Parameters
iFlagsToValidate The flags to validate
Returns
int
References EnableAtLogin, InternalWindowMask, NeedsConnection, NeedsContext, and WindowOnlyIfUsersSelected.
Referenced by action_kvs_cmd_create(), SingleActionEditor::commit(), and SingleActionEditor::setActionData().
const QString & KviAction::visibleName () virtual
Returns the visible name of the action.
Returns
const QString &
Reimplemented in KviKvsUserAction.
References m_szVisibleName.
Referenced by KviSubmenuAction::addToCustomToolBar(), addToCustomToolBar(), KviSubmenuAction::addToPopupMenu(), addToPopupMenu(), and KviActionDrawerPageListWidgetItem::KviActionDrawerPageListWidgetItem().
Friends And Related Function Documentation
friend class KviActionManager friend
Member Data Documentation
QString KviAction::m_eIcon protected
QPointer<QShortcut> KviAction::m_pAccel protected
Referenced by registerAccelerator(), unregisterAccelerator(), and ~KviAction().
KviPointerList<QAction>* KviAction::m_pActionList protected
Referenced by actionDestroyed(), KviIrcContextDisplayAction::activeContextChanged(), KviIrcContextDisplayAction::activeContextStateChanged(), registerAction(), reloadImages(), setEnabled(), and ~KviAction().
KviActionCategory* KviAction::m_pCategory protected
Referenced by KviKvsUserAction::KviKvsUserAction(), and KviKvsUserAction::load().
QString KviAction::m_szBigIconId protected
Referenced by bigIcon(), KviKvsUserAction::exportToKvs(), KviKvsUserAction::load(), and KviKvsUserAction::save().
QString KviAction::m_szDescription protected
Referenced by KviKvsUserAction::description(), description(), KviKvsUserAction::descriptionCode(), and KviKvsUserAction::load().
QString KviAction::m_szKeySequence protected
Referenced by KviConnectAction::addToPopupMenu(), KviGoAwayAction::addToPopupMenu(), addToPopupMenu(), KviKvsUserAction::exportToKvs(), KviKvsUserAction::load(), registerAccelerator(), and KviKvsUserAction::save().
QString KviAction::m_szName protected
Referenced by addToCustomToolBar(), KviKvsUserAction::exportToKvs(), KviKvsUserAction::load(), and KviKvsUserAction::save().
QString KviAction::m_szSmallIconId protected
Referenced by KviKvsUserAction::exportToKvs(), KviKvsUserAction::load(), KviKvsUserAction::save(), and smallIcon().
QString KviAction::m_szVisibleName protected
Referenced by KviKvsUserAction::load(), KviKvsUserAction::visibleName(), visibleName(), and KviKvsUserAction::visibleNameCode().
unsigned int KviAction::m_uFlags protected
Referenced by activeContextChanged(), activeContextStateChanged(), activeWindowChanged(), activeWindowSelectionStateChanged(), KviKvsUserAction::exportToKvs(), KviKvsUserAction::load(), KviKvsUserAction::save(), and setup().
unsigned short int KviAction::m_uInternalFlags protected
Referenced by KviGoAwayAction::activeContextStateChanged(), setEnabled(), and setup().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviAction.h
src/kvirc/kernel/KviAction.cpp