KVIrc: KviChannelWindow Class Reference
KviChannelWindow Class Reference
The class which manages a channel.
#include <KviChannelWindow.h>
Public Types
enum ActivityLimit {
Ice = 5, VeryCold = 10, Cold = 20, Undefined = 30,
Hot = 50, VeryHot = 70
}
Holds the limits of the activity in a channel.
enum StateFlag {
HaveAllNames = 1, HaveWhoList = (1 << 2), DeadChan = (1 << 3), SentWhoRequest = (1 << 4),
SentPart = (1 << 5), Synchronized = (1 << 6), NoCloseOnPart = (1 << 7), SentSyncWhoRequest = (1 << 8)
}
Holds the state flags of the channel.
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Signals
void opStatusChanged ()
Emitted when our op status change.
Signals inherited from KviWindow
void windowNameChanged ()
Public Member Functions
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
Colors the icon who tells how much activity there is.
void addHighlightedUser (const QString &szNick)
Adds a user to the highlight list.
bool avatarChanged (const QString &szNick)
Returns true if the avatar of a user is changed.
QFrame * buttonContainer ()
Returns the button container object.
int chanAdminCount ()
Returns the number of users with chanadmin status.
void channelAction (const QString &szNick, unsigned int uActionType, int iTemperature)
Called when someone perform an action in the channel.
QString channelModeParam (char cMode) const
Returns the value (parameter) for a channel mode (eg. the password for mode k)
int chanOwnerCount ()
Returns the number of users with chanowner status.
void checkChannelSync ()
Checks the channel synchronization time.
void clearSentSyncWhoRequest ()
Clears the sync WHO request flag.
bool closeOnPart ()
Returns true if the channel has to be closed on part.
unsigned int count ()
Returns the number of users.
void enableUserListUpdates (bool bEnable)
Enables or disable the userlist updates.
KviUserListEntry * findEntry (const QString &szNick)
Searches for a user in the userlist.
QString * firstSelectedNickname ()
Returns the first selected nickname in the userlist.
void getChannelActivityStats (KviChannelActivityStats *pStats)
Gets the channel activity stats and put them in the buffer.
void getChannelModeString (QString &szBuffer)
Fills szBuffer with all set channel modes, but without any parameters (eg: lkmi)
void getChannelModeStringWithEmbeddedParams (QString &szBuffer)
Fills szBuffer with all set channel modes and any parameters (eg: mi l:10 k:password)
char getUserFlag (const QString &szNick)
Returns the flag of a user.
virtual void getWindowListTipText (QString &szBuffer)
Creates the tooltip over the channel treeview.
int halfOpCount ()
Returns the number of users with halfop status.
bool hasAllNames ()
Returns true if the channel has all names.
bool hasBanExceptionList ()
Returns true if the channel has a ban exception list.
bool hasBanList ()
Returns true if the channel has a ban list.
bool hasChannelMode (char cMode)
Returns true if the channel has a mode with parameter set (eg. mode k)
bool hasInviteList ()
Returns true if the channel has an invite list.
bool hasQuietBanList ()
Returns true if the channel has a quiet ban list.
bool hasWhoList ()
Returns true if the channel has a WHO list.
bool isChanAdmin (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a chan admin.
bool isChanOwner (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a chan owner.
bool isDeadChan ()
Returns true if the channel is dead.
bool isHalfOp (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a half operator.
bool isHighlightedUser (const QString &szNick)
Returns true if the user is highlighted.
bool isMeChanAdmin (bool bAtLeast=false)
Returns true if we are a chan admin.
bool isMeChanOwner (bool bAtLeast=false)
Returns true if we are a chan owner.
bool isMeHalfOp (bool bAtLeast=false)
Returns true if we are a half operator.
bool isMeIrcOp (bool bAtLeast=false)
Returns true if we are an ircop.
bool isMeOp (bool bAtLeast=false)
Returns true if we are an operator.
bool isMeUserOp (bool bAtLeast=false)
Returns true if we are a user operator.
bool isMeVoice (bool bAtLeast=false)
Returns true if we are a voice.
bool isOn (const QString &szNick)
Returns true if the user is on the channel.
bool isOp (const QString &szNick, bool bAtLeast=false)
Returns true if the user is an operator.
bool isUserOp (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a user operator.
bool isVoice (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a voice.
KviUserListEntry * join (const QString &szNick, const QString &szUser=QString(), const QString &szHost=QString(), int iFlags=0)
Called when a user joins the channel.
KviChannelWindow (KviConsoleWindow *lpConsole, const QString &szName)
Constructs the channel object.
kvi_time_t lastReceivedWhoReply ()
Returns the time of the last received WHO reply.
QByteArray loadLogFile (const QString &szFileName, bool bGzip)
Loads a log file.
virtual void lostUserFocus ()
Called when the channel losts the focus by the user.
unsigned int maskCount (char cMode)
Returns the number of masks is a channel mode list.
KviIrcView * messageView () const
Returns the irc view object.
KviPointerList< KviMaskEntry > * modeMasks (char cMode)
Returns a list of masks for a specific mode.
int myFlags ()
Returns our flags.
const QString & nameWithUserFlag ()
Returns the name of the channel with user flags.
QString * nextSelectedNickname ()
Returns the next selected nickname in the userlist.
bool nickChange (const QString &szOldNick, const QString &szNewNick)
Called when someone changes his nick.
int opCount ()
Returns the number of users with op status.
virtual void outputMessage (int iMsgType, const QString &szMsg)
Outputs a message to the channel window.
void ownAction (const QString &szBuffer)
Called when we perform an action.
void ownMessage (const QString &szBuffer, bool bUserFeedback=true)
Called when we send a message.
bool part (const QString &szNick)
Called when someone parts the channel.
void partMessageSent (bool bCloseOnPart=true, bool bShowMessage=true)
Called when we want to part a channel.
void pasteLastLog ()
Pastes the most recent channel log into the buffer.
QString plainChannelMode ()
Returns only the plain (parameter-less) channel modes (eg: mi)
void prependUserFlag (const QString &szNick, QString &szBuffer)
Prepends the user flag to the nickname.
void removeHighlightedUser (const QString &szNick)
Removes a user from the highlight list.
int selectedCount ()
Returns the number of selected users.
bool sentListRequest (char cMode)
Returns true if we have sent a list request for a specific channel mode.
bool sentSyncWhoRequest ()
Returns true if we have sent the sync WHO request.
bool sentWhoRequest ()
Returns true if we have sent the WHO request.
KviIrcConnectionServerInfo * serverInfo ()
Gets the KviIrcConnectionServerInfo structure associated to the current connection.
void setAliveChan ()
Sets the channel as alive.
bool setChanAdmin (const QString &szNick, bool bChanAdmin)
Sets the chan admin mode.
void setChannelMode (char cMode, bool bAdd)
Sets a plain (parameter-less) channel mode, (eg: +m)
void setChannelModeWithParam (char cMode, QString &szParam)
Sets a channel mode with a parameter; an empty parameter unsets the mode (eg: +k password)
bool setChanOwner (const QString &szNick, bool bChanOwner)
Sets the chan owner mode.
void setDeadChan ()
Sets the channel as dead.
bool setHalfOp (const QString &szNick, bool bHalfOp, bool)
Sets the half operator mode.
void setHasAllNames ()
Sets the existance of all names.
void setHasWhoList ()
Sets the existance of the WHO list.
void setLastReceivedWhoReply (kvi_time_t tTime)
Sets the time of the last received WHO reply.
void setListRequestDone (char cMode)
Clears the "sent request" flag for a specific chanel mode.
void setModeInList (char cMode, const QString &szMask, bool bAdd, const QString &szSetBy, unsigned int uSetAt, QString szChangeMask=QString())
Called when someone sets a channel mode that is stored in a list; these modes require a parameter that is tipically a mask.
bool setOp (const QString &szNick, bool bOp, bool bIsMe)
Sets the operator mode.
void setSentListRequest (char cMode)
Sets the "sent request" flag for a specific channel mode.
void setSentSyncWhoRequest ()
Sets the sync WHO request flag.
void setSentWhoRequest ()
Sets the WHO request flag.
bool setUserOp (const QString &szNick, bool bUserOp, bool)
Sets the user operator mode.
bool setVoice (const QString &szNick, bool bVoice, bool)
Sets the voice mode.
virtual QSize sizeHint () const
Returns the size of the channel.
virtual const QString & target ()
Returns the name of the channel.
KviTopicWidget * topicWidget ()
Returns the topic widget object.
void unhighlight ()
Unhighlights the windowlist item.
void updateModeLabel ()
Updates the tooltip over the channel modes.
void userAction (KviIrcMask *user, unsigned int uActionType)
Perform a user action in the channel.
void userAction (const QString &szNick, unsigned int uActionType)
Perform a user action in the channel.
void userAction (const QString &szNick, const QString &szUser, const QString &szHost, unsigned int uActionType)
Perform a user action in the channel.
KviUserListView * userListView ()
Returns the user listview object.
int userOpCount ()
Returns the number of users with userop status.
int voiceCount ()
Returns the number of users with voice status.
~KviChannelWindow ()
Destroys the channel object.
Public Member Functions inherited from KviWindow
void activateSelf ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
void getDefaultLogFileName (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Protected Member Functions
virtual void applyOptions ()
Applies the options.
virtual void closeEvent (QCloseEvent *pEvent)
bool eventFilter (QObject *pObject, QEvent *pEvent)
Filters the events.
virtual void fillCaptionBuffers ()
Fills in the caption buffers.
void fixActionHistory ()
Fixes the action history.
virtual void getBaseLogFileName (QString &szBuffer)
Gets the base name for log file.
virtual void getConfigGroupName (QString &szBuffer)
Gets the group name.
void getTalkingUsersStats (QString &szBuffer, QStringList &list, bool bPast)
Gets the talking user stats to fill in the tooltip.
void internalMask (const QString &szMask, bool bAdd, const QString &szSetBy, unsigned int uSetAt, KviPointerList< KviMaskEntry > *l, KviMaskEditor **ppEd, QString &szChangeMask)
Called when someone sets a mask in the channel's lists.
virtual void loadProperties (KviConfigurationFile *pCfg)
Loads the properties from file.
virtual QPixmap * myIconPtr ()
Returns the correct icon for the channel.
virtual void preprocessMessage (QString &szMessage)
Preprocess message stripping control bytes.
virtual void resizeEvent (QResizeEvent *)
virtual void saveProperties (KviConfigurationFile *pCfg)
Saves the properties to file.
void showDoubleView (bool bShow)
Splits the channel view into two views.
virtual void triggerCreationEvents ()
Trigger the OnChannelWindowCreated event.
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void moveEvent (QMoveEvent *pEvent)
void setType (Type eType)
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
int m_iStateFlags
QDateTime m_joinTime
KviPointerList
< KviChannelAction > * m_pActionHistory
KviTalHBox * m_pButtonContainer
QToolButton * m_pDoubleViewButton
QMap< char,
KviWindowToolPageButton * > m_pListEditorButtons
QMap< char, KviMaskEditor * > m_pListEditors
KviWindowToolPageButton * m_pListViewButton
KviIrcView * m_pMessageView
KviModeEditor * m_pModeEditor
KviWindowToolPageButton * m_pModeEditorButton
QMap< char, KviPointerList
< KviMaskEntry > * > m_pModeLists
KviModeWidget * m_pModeWidget
KviPixmap m_privateBackground
QStringList * m_pTmpHighLighted
KviTopicWidget * m_pTopicWidget
KviTalSplitter * m_pTopSplitter
KviUserListView * m_pUserListView
KviTalSplitter * m_pVertSplitter
QList< int > m_SplitterSizesList
QString m_szChannelMode
QMap< char, QString > m_szChannelParameterModes
QString m_szNameWithUserFlag
QString m_szSentModeRequests
kvi_time_t m_tLastReceivedWhoReply
unsigned int m_uActionHistoryHotActionCount
QList< int > m_VertSplitterSizesList
Protected Attributes inherited from KviWindow
bool m_bIsDocked
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Private Slots
void modeSelectorDone ()
Called when we close the mode editor.
void removeMasks (KviMaskEditor *pEd, KviPointerList< KviMaskEntry > *pList)
Removes the masks from the mask editor window.
void setMode (QString &szMode)
Called when we select the modes from the mode editor.
void textViewRightClicked ()
Called when we right-click the irc view.
void toggleDoubleView ()
Toggles the double view mode.
void toggleListModeEditor ()
Toggles a list mode editor.
void toggleListView ()
Toggles the userlist view.
void toggleModeEditor ()
Toggles the mode editor.
void toggleToolButtons ()
Toggles tool buttons widget over the listview.
void topicSelected (const QString &szTopic)
Called when we select the topic.
Additional Inherited Members
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void maximize ()
void minimize ()
void reloadImages ()
void restore ()
void savePropertiesAsDefault ()
void undock ()
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Detailed Description
The class which manages a channel.
Member Enumeration Documentation
enum KviChannelWindow::ActivityLimit
Holds the limits of the activity in a channel.
Enumerator
Ice
The limit to be "ice"
VeryCold
The limit to be "very cold"
Cold
The limit to be "cold"
Undefined
The limit to be "undefined"
Hot
The limit to be "hot"
VeryHot
The limit to be "very hot"
enum KviChannelWindow::StateFlag
Holds the state flags of the channel.
Enumerator
HaveAllNames
Flag for "have all names"
HaveWhoList
Flag for "have WHO list"
DeadChan
Flag for "dead channel"
SentWhoRequest
Flag to set WHO request
SentPart
Flag to set PART request
Synchronized
Flag to set SYNC request
NoCloseOnPart
Flag to set no close on part
SentSyncWhoRequest
Flag for SYNC request
Constructor & Destructor Documentation
KviChannelWindow::KviChannelWindow (KviConsoleWindow * lpConsole, const QString & szName)
Constructs the channel object.
Parameters
lpConsole The console of the context
szName The name of the channel
Returns
KviChannelWindow
References __tr2qs, KviTalToolTip::add(), applyOptions(), KviIconManager::Ban, KviIconManager::BanExcept, KviIconManager::BanUnExcept, buttonContainer(), KviIconManager::ChanAdmin, KviIconManager::ChanMode, KviIconManager::ChanModeHide, KviIconManager::ChanOwner, KviIconManager::ChanUnAdmin, KviIconManager::ChanUnOwner, connect(), KviWindow::connection(), KviWindow::createCryptControllerButton(), KviWindow::createTextEncodingButton(), g_pIconManager, KviIconManager::getBigIcon(), KviIrcConnectionServerInfo::getChannelModeDescription(), KviIconManager::HideDoubleView, KviIconManager::HideListView, i, KviIconManager::InviteExcept, KviIconManager::InviteUnExcept, KVI_CHANNEL_AVERAGE_USERS, KVI_OPTION_BOOL, kvi_time_t, KviWindow::KviInput, KviOption_boolAutoLogChannels, KviTalSplitter, m_iStateFlags, m_joinTime, m_pActionHistory, KviWindow::m_pButtonBox, m_pButtonContainer, m_pDoubleViewButton, KviWindow::m_pHideToolsButton, KviWindow::m_pInput, KviWindow::m_pIrcView, m_pListEditorButtons, m_pListViewButton, m_pMessageView, m_pModeEditor, m_pModeEditorButton, m_pModeWidget, KviWindow::m_pSplitter, m_pTmpHighLighted, m_pTopicWidget, m_pTopSplitter, m_pUserListView, m_pVertSplitter, m_tLastReceivedWhoReply, m_uActionHistoryHotActionCount, KviIrcConnection::registerChannel(), serverInfo(), KviTalHBox::setMargin(), setMode(), KviTalHBox::setSpacing(), KviIconManager::ShowDoubleView, KviIconManager::ShowListView, KviIrcView::startLogging(), KviIrcConnectionServerInfo::supportedListModes(), textViewRightClicked(), toggleDoubleView(), toggleListModeEditor(), toggleListView(), toggleModeEditor(), toggleToolButtons(), topicSelected(), and KviIconManager::UnBan.
KviChannelWindow::~KviChannelWindow ()
Destroys the channel object.
References KviWindow::connection(), KviWindow::context(), KviWindow::DeadChannel, KviUserListView::enableUpdates(), m_pActionHistory, m_pListEditorButtons, m_pListEditors, m_pModeLists, m_pTmpHighLighted, m_pUserListView, KviUserListView::partAll(), KviWindow::type(), KviIrcConnection::unregisterChannel(), and KviIrcContext::unregisterDeadChannel().
Member Function Documentation
bool KviChannelWindow::activityMeter (unsigned int * puActivityValue, unsigned int * puActivityTemperature) virtual
Colors the icon who tells how much activity there is.
Parameters
puActivityValue The value of the activity
puActivityTemperature The temperature of the activity
Returns
bool
Reimplemented from KviWindow.
References KviWindow::Cold, Cold, KviWindow::Fire, fixActionHistory(), KviWindow::High, KviWindow::Hot, Hot, KviWindow::Ice, Ice, KVI_CHANNEL_ACTION_HISTORY_MAX_COUNT, KVI_CHANNEL_ACTION_HISTORY_MAX_TIMESPAN, kvi_time_t, kvi_unixTime, KviWindow::Low, m_joinTime, m_pActionHistory, m_uActionHistoryHotActionCount, KviWindow::Medium, KviWindow::None, _KviChannelAction::tTime, KviWindow::Undefined, Undefined, KviWindow::VeryCold, VeryCold, KviWindow::VeryHigh, KviWindow::VeryHot, VeryHot, and KviWindow::VeryLow.
void KviChannelWindow::addHighlightedUser (const QString & szNick)
Adds a user to the highlight list.
Parameters
szNick The nickname of the user
Returns
void
References KviUserListView::findEntry(), m_pTmpHighLighted, and m_pUserListView.
void KviChannelWindow::applyOptions () protected virtual
Applies the options.
Returns
void
Reimplemented from KviWindow.
References KviThemedLineEdit::applyOptions(), KviTopicWidget::applyOptions(), KviIrcView::applyOptions(), KviUserListView::applyOptions(), KviWindow::applyOptions(), m_pMessageView, m_pModeWidget, m_pTopicWidget, and m_pUserListView.
Referenced by KviChannelWindow().
bool KviChannelWindow::avatarChanged (const QString & szNick) inline
Returns true if the avatar of a user is changed.
Parameters
szNick The nickname of the user
Returns
bool
References KviUserListView::avatarChanged().
QFrame* KviChannelWindow::buttonContainer () inline virtual
Returns the button container object.
Returns
QFrame *
Reimplemented from KviWindow.
Referenced by KviChannelWindow(), loadProperties(), saveProperties(), and toggleToolButtons().
int KviChannelWindow::chanAdminCount () inline
Returns the number of users with chanadmin status.
Returns
int
References KviUserListView::chanAdminCount().
Referenced by chan_kvs_fnc_admincount().
void KviChannelWindow::channelAction (const QString & szNick, unsigned int uActionType, int iTemperature)
Called when someone perform an action in the channel.
Parameters
szNick The nickname of the user who made the action
uActionType The type of the action
iTemperature The temperature of the action
Returns
void
References fixActionHistory(), _KviChannelAction::iTemperature, kvi_unixTime, m_pActionHistory, m_uActionHistoryHotActionCount, _KviChannelAction::szNick, _KviChannelAction::tTime, and _KviChannelAction::uActionType.
Referenced by nickChange(), part(), and userAction().
QString KviChannelWindow::channelModeParam (char cMode) const inline
Returns the value (parameter) for a channel mode (eg. the password for mode k)
Parameters
cMode The mode
Returns
QString
Referenced by chan_kvs_fnc_getUrl(), chan_kvs_fnc_key(), chan_kvs_fnc_limit(), chan_kvs_fnc_modeParam(), KviModeEditor::commit(), KviIrcContext::connectionTerminated(), KviModeWidget::editorReturnPressed(), KviModeEditor::KviModeEditor(), and KviIrcServerParser::parseLiteralKick().
int KviChannelWindow::chanOwnerCount () inline
Returns the number of users with chanowner status.
Returns
int
References KviUserListView::chanOwnerCount().
Referenced by chan_kvs_fnc_ownercount().
void KviChannelWindow::checkChannelSync ()
Checks the channel synchronization time.
Returns
void
References __tr2qs, KviWindow::connection(), HaveWhoList, KVI_OPTION_BOOL, KVI_OUT_SYSTEMMESSAGE, KviEvent_OnChannelSync, KviOption_boolShowChannelSyncTime, KVS_TRIGGER_EVENT_1_HALTED, m_iStateFlags, m_joinTime, m_szSentModeRequests, KviWindow::output(), SentWhoRequest, and Synchronized.
Referenced by KviIrcConnectionRequestQueue::timerSlot().
void KviChannelWindow::clearSentSyncWhoRequest () inline
Clears the sync WHO request flag.
Returns
void
Referenced by KviIrcServerParser::parseNumericEndOfWho().
void KviChannelWindow::closeEvent (QCloseEvent * pEvent) protected virtual
Reimplemented from KviWindow.
References KviKvsVariant::asString(), KviWindow::closeEvent(), KviWindow::connection(), KviWindow::context(), DeadChan, KviWindow::encodeText(), KviIrcConnection::encodeText(), KviQString::escapeKvs(), KviKvsScript::evaluate(), KviConsoleWindow::isConnected(), KVI_OPTION_STRING, KviOption_stringPartMessage, m_iStateFlags, KviWindow::m_pConsole, KviWindow::m_szName, KviOsInfo::name(), partMessageSent(), KviQString::PermitFunctions, KviQString::PermitVariables, KviIrcConnection::sendFmtData(), SentPart, and KviIrcContext::unregisterDeadChannel().
bool KviChannelWindow::closeOnPart () inline
Returns true if the channel has to be closed on part.
Returns
bool
Referenced by KviIrcServerParser::parseLiteralPart().
unsigned int KviChannelWindow::count () inline
Returns the number of users.
Returns
unsigned int
References KviUserListView::count().
Referenced by chan_kvs_fnc_usercount(), and KviIrcView::doLinkToolTip().
void KviChannelWindow::enableUserListUpdates (bool bEnable) inline
Enables or disable the userlist updates.
Parameters
bEnable Whether to enable the updates
Returns
void
References KviUserListView::enableUpdates().
Referenced by KviIrcServerParser::parseNumericNames().
bool KviChannelWindow::eventFilter (QObject * pObject, QEvent * pEvent) protected
Filters the events.
Parameters
pObject The object
pEvent The event
Returns
bool
References KviTopicWidget::deactivate(), KviWindow::eventFilter(), and m_pTopicWidget.
void KviChannelWindow::fillCaptionBuffers () protected virtual
Fills in the caption buffers.
Returns
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), getChannelModeString(), getUserFlag(), KviWindow::m_szName, m_szNameWithUserFlag, and KviWindow::m_szPlainTextCaption.
KviUserListEntry* KviChannelWindow::findEntry (const QString & szNick) inline
Searches for a user in the userlist.
Parameters
szNick The nickname of the user to find
Returns
KviUserListEntry *
References KviUserListView::findEntry().
Referenced by preprocessMessage().
QString* KviChannelWindow::firstSelectedNickname () inline
Returns the first selected nickname in the userlist.
Returns
QString *
References KviUserListView::firstSelectedNickname().
void KviChannelWindow::fixActionHistory () protected
Fixes the action history.
Returns
void
References _KviChannelAction::iTemperature, KVI_CHANNEL_ACTION_HISTORY_MAX_COUNT, KVI_CHANNEL_ACTION_HISTORY_MAX_TIMESPAN, kvi_time_t, m_pActionHistory, m_uActionHistoryHotActionCount, and _KviChannelAction::tTime.
Referenced by activityMeter(), channelAction(), and getChannelActivityStats().
void KviChannelWindow::getBaseLogFileName (QString & szBuffer) protected virtual
Gets the base name for log file.
Parameters
szBuffer The buffer where to save data
Returns
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviWindow::context(), and KviWindow::windowName().
void KviChannelWindow::getChannelActivityStats (KviChannelActivityStats * pStats)
Gets the channel activity stats and put them in the buffer.
Parameters
pStats The buffer where to store the data
Returns
void
References _KviChannelActivityStats::bStatsInaccurate, _KviChannelActivityStats::dActionsPerMinute, fixActionHistory(), _KviChannelActivityStats::iAverageActionTemperature, isOn(), _KviChannelAction::iTemperature, KVI_CHANNEL_ACTION_HISTORY_MAX_COUNT, KVI_CHANNEL_ACTION_HISTORY_MAX_TIMESPAN, kvi_time_t, kvi_unixTime, KVI_USERACTION_ACTION, KVI_USERACTION_NOTICE, KVI_USERACTION_PRIVMSG, _KviChannelActivityStats::lTalkingUsers, _KviChannelActivityStats::lWereTalkingUsers, m_joinTime, m_pActionHistory, KviPointerHashTable< Key, T >::setAutoDelete(), _KviChannelAction::szNick, _KviChannelAction::tTime, _KviChannelActivityStats::uActionCount, _KviChannelActivityStats::uActionsInTheLastMinute, _KviChannelAction::uActionType, _KviChannelActivityStats::uFirstActionTimeSpan, _KviChannelActivityStats::uHotActionCount, _KviChannelActivityStats::uHotActionPercent, and _KviChannelActivityStats::uLastActionTimeSpan.
Referenced by getWindowListTipText().
void KviChannelWindow::getChannelModeString (QString & szBuffer)
Fills szBuffer with all set channel modes, but without any parameters (eg: lkmi)
Parameters
szBuffer The buffer :)
Returns
void
References m_szChannelMode, and m_szChannelParameterModes.
Referenced by chan_kvs_fnc_mode(), KviIrcView::doLinkToolTip(), fillCaptionBuffers(), and KviTopicWidget::switchMode().
void KviChannelWindow::getChannelModeStringWithEmbeddedParams (QString & szBuffer)
Fills szBuffer with all set channel modes and any parameters (eg: mi l:10 k:password)
Parameters
szBuffer The buffer :)
Returns
void
References m_szChannelMode, and m_szChannelParameterModes.
Referenced by KviModeWidget::editorReturnPressed(), and KviModeWidget::refreshModes().
void KviChannelWindow::getConfigGroupName (QString & szBuffer) protected virtual
Gets the group name.
Parameters
szBuffer The buffer where to save the data
Returns
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviOsInfo::name(), target(), and KviWindow::windowName().
void KviChannelWindow::getTalkingUsersStats (QString & szBuffer, QStringList & list, bool bPast) protected
Gets the talking user stats to fill in the tooltip.
Parameters
szBuffer The buffer where to store the data
list The list of talking users
bPast Whether the activity is recent or in the past
Returns
void
References __tr2qs, and KviQString::toHtmlEscaped().
Referenced by getWindowListTipText().
char KviChannelWindow::getUserFlag (const QString & szNick) inline
Returns the flag of a user.
Parameters
szNick The nick of the user
Returns
char
References KviUserListView::getUserFlag().
Referenced by fillCaptionBuffers().
void KviChannelWindow::getWindowListTipText (QString & szBuffer) virtual
Creates the tooltip over the channel treeview.
Parameters
szBuffer The buffer where to store the data
Returns
void
Reimplemented from KviWindow.
References __tr2qs, _KviChannelActivityStats::bStatsInaccurate, _KviChannelActivityStats::dActionsPerMinute, DeadChan, END_TABLE_BOLD_ROW, getChannelActivityStats(), getTalkingUsersStats(), _KviChannelActivityStats::lTalkingUsers, _KviChannelActivityStats::lWereTalkingUsers, m_iStateFlags, m_pUserListView, KviWindow::m_szPlainTextCaption, s, START_TABLE_BOLD_ROW, KviQString::toHtmlEscaped(), _KviUserListViewUserStats::uActive, _KviUserListViewUserStats::uActiveOp, _KviUserListViewUserStats::uChanAdmin, _KviUserListViewUserStats::uChanOwner, _KviUserListViewUserStats::uHalfOp, _KviUserListViewUserStats::uHot, _KviChannelActivityStats::uHotActionPercent, _KviUserListViewUserStats::uHotOp, _KviUserListViewUserStats::uIrcOp, _KviUserListViewUserStats::uOp, KviUserListView::userStats(), _KviUserListViewUserStats::uTotal, _KviUserListViewUserStats::uUserOp, and _KviUserListViewUserStats::uVoiced.
int KviChannelWindow::halfOpCount () inline
Returns the number of users with halfop status.
Returns
int
References KviUserListView::halfOpCount().
Referenced by chan_kvs_fnc_halfopcount().
bool KviChannelWindow::hasAllNames () inline
Returns true if the channel has all names.
Returns
bool
Referenced by KviIrcServerParser::parseNumericEndOfNames(), and KviIrcServerParser::parseNumericNames().
bool KviChannelWindow::hasBanExceptionList () inline
Returns true if the channel has a ban exception list.
Returns
bool
bool KviChannelWindow::hasBanList () inline
Returns true if the channel has a ban list.
Returns
bool
bool KviChannelWindow::hasChannelMode (char cMode) inline
Returns true if the channel has a mode with parameter set (eg. mode k)
Parameters
cMode The mode
Returns
bool
Referenced by chan_kvs_fnc_getUrl(), chan_kvs_fnc_key(), chan_kvs_fnc_limit(), chan_kvs_fnc_modeParam(), KviModeEditor::commit(), KviIrcContext::connectionTerminated(), KviModeWidget::editorReturnPressed(), KviModeEditor::KviModeEditor(), and KviIrcServerParser::parseLiteralKick().
bool KviChannelWindow::hasInviteList () inline
Returns true if the channel has an invite list.
Returns
bool
bool KviChannelWindow::hasQuietBanList () inline
Returns true if the channel has a quiet ban list.
Returns
bool
bool KviChannelWindow::hasWhoList () inline
Returns true if the channel has a WHO list.
Returns
bool
Referenced by KviIrcServerParser::parseNumericEndOfWho(), and KviIrcServerParser::parseNumericWhoReply().
void KviChannelWindow::internalMask (const QString & szMask, bool bAdd, const QString & szSetBy, unsigned int uSetAt, KviPointerList< KviMaskEntry > * l, KviMaskEditor ** ppEd, QString & szChangeMask) protected
Called when someone sets a mask in the channel's lists.
Parameters
szMask The mask set
bAdd Whether to add or remove the mask
szSetBy Who set the mask
uSetAt The datetime when the mask was set
l The list of masks in the channel lists
ppEd The mask editor window
szChangeMask If bAdd is false and this string is set, the mask will be updated instead that removed
Returns
void
References __tr2qs, KviPointerList< T >::append(), KviQString::equalCI(), KviPointerList< T >::first(), KviPointerList< T >::next(), KviPointerList< T >::removeRef(), _KviMaskEntry::szMask, _KviMaskEntry::szSetBy, and _KviMaskEntry::uSetAt.
Referenced by setModeInList().
bool KviChannelWindow::isChanAdmin (const QString & szNick, bool bAtLeast = false) inline
Returns true if the user is a chan admin.
Parameters
szNick The nickname of the user to check
bAtLeast Whether the user is at least a chan admin
Returns
bool
References KviUserListView::isChanAdmin().
bool KviChannelWindow::isChanOwner (const QString & szNick, bool bAtLeast = false) inline
Returns true if the user is a chan owner.
Parameters
szNick The nickname of the user to check
bAtLeast Whether the user is at least a chan owner
Returns
bool
References KviUserListView::isChanOwner().
bool KviChannelWindow::isDeadChan () inline
Returns true if the channel is dead.
Returns
bool
bool KviChannelWindow::isHalfOp (const QString & szNick, bool bAtLeast = false) inline
Returns true if the user is a half operator.
Parameters
szNick The nickname of the user to check
bAtLeast Whether the user is at least a half operator
Returns
bool
References KviUserListView::isHalfOp().
bool KviChannelWindow::isHighlightedUser (const QString & szNick) inline
Returns true if the user is highlighted.
Parameters
szNick The nickname of the user
Returns
bool
bool KviChannelWindow::isMeChanAdmin (bool bAtLeast = false)
Returns true if we are a chan admin.
Parameters
bAtLeast Whether we are at least a chan admin
Returns
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviModeWidget::mouseDoubleClickEvent(), KviTopicWidget::switchMode(), KviModeEditor::updateOpStatus(), and KviMaskEditor::updateOpStatus().
bool KviChannelWindow::isMeChanOwner (bool bAtLeast = false)
Returns true if we are a chan owner.
Parameters
bAtLeast Whether we are at least a chan owner
Returns
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviModeWidget::mouseDoubleClickEvent(), KviTopicWidget::switchMode(), KviModeEditor::updateOpStatus(), and KviMaskEditor::updateOpStatus().
bool KviChannelWindow::isMeHalfOp (bool bAtLeast = false)
Returns true if we are a half operator.
Parameters
bAtLeast Whether we are at least a half operator
Returns
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviModeWidget::mouseDoubleClickEvent(), KviTopicWidget::switchMode(), KviModeEditor::updateOpStatus(), and KviMaskEditor::updateOpStatus().
bool KviChannelWindow::isMeIrcOp (bool bAtLeast = false)
Returns true if we are an ircop.
Parameters
bAtLeast Whether we are at least an ircop
Returns
bool
bool KviChannelWindow::isMeOp (bool bAtLeast = false)
Returns true if we are an operator.
Parameters
bAtLeast Whether we are at least an operator
Returns
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviModeWidget::mouseDoubleClickEvent(), KviTopicWidget::switchMode(), KviIrcConnectionRequestQueue::timerSlot(), KviModeEditor::updateOpStatus(), and KviMaskEditor::updateOpStatus().
bool KviChannelWindow::isMeUserOp (bool bAtLeast = false)
Returns true if we are a user operator.
Parameters
bAtLeast Whether we are at least a user operator
Returns
bool
bool KviChannelWindow::isMeVoice (bool bAtLeast = false)
Returns true if we are a voice.
Parameters
bAtLeast Whether we are at least a voice
Returns
bool
bool KviChannelWindow::isOn (const QString & szNick) inline
Returns true if the user is on the channel.
Parameters
szNick The nickname of the user
Returns
bool
References KviUserListView::findEntry().
Referenced by chan_kvs_fnc_ison(), and getChannelActivityStats().
bool KviChannelWindow::isOp (const QString & szNick, bool bAtLeast = false) inline
Returns true if the user is an operator.
Parameters
szNick The nickname of the user to check
bAtLeast Whether the user is at least an operator
Returns
bool
References KviUserListView::isOp().
bool KviChannelWindow::isUserOp (const QString & szNick, bool bAtLeast = false) inline
Returns true if the user is a user operator.
Parameters
szNick The nickname of the user to check
bAtLeast Whether the user is at least a user operator
Returns
bool
References KviUserListView::isUserOp().
bool KviChannelWindow::isVoice (const QString & szNick, bool bAtLeast = false) inline
Returns true if the user is a voice.
Parameters
szNick The nickname of the user to check
bAtLeast Whether the user is at least a voice
Returns
bool
References KviUserListView::isVoice().
KviUserListEntry* KviChannelWindow::join (const QString & szNick, const QString & szUser = QString(), const QString & szHost = QString(), int iFlags = 0) inline
Called when a user joins the channel.
Parameters
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
iFlags The flags of the user
Returns
KviUserListEntry *
References KviUserListView::join(), and szHost.
Referenced by KviIrcServerParser::parseLiteralJoin(), and KviIrcServerParser::parseNumericNames().
kvi_time_t KviChannelWindow::lastReceivedWhoReply () inline
Returns the time of the last received WHO reply.
Returns
kvi_time_t
Referenced by KviIrcConnection::heartbeat().
QByteArray KviChannelWindow::loadLogFile (const QString & szFileName, bool bGzip)
Loads a log file.
It opens a logfile, gzipped or not, and returns the content in a buffer
Parameters
szFileName The filename of the log file
bGzip Whether the log file is gzipped
Returns
QByteArray
Referenced by pasteLastLog().
void KviChannelWindow::loadProperties (KviConfigurationFile * pCfg) protected virtual
Loads the properties from file.
Parameters
pCfg The config file
Returns
void
Reimplemented from KviWindow.
References buttonContainer(), KVI_OPTION_BOOL, KviOption_boolHideWindowToolButtons, KviWindow::loadProperties(), KviWindow::m_pIrcView, m_pListViewButton, m_pMessageView, m_privateBackground, KviWindow::m_pSplitter, m_pTopSplitter, m_pUserListView, m_SplitterSizesList, m_VertSplitterSizesList, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readIntListEntry(), KviConfigurationFile::readPixmapEntry(), resizeEvent(), KviIrcView::setPrivateBackgroundPixmap(), showDoubleView(), and toggleToolButtons().
void KviChannelWindow::lostUserFocus () virtual
Called when the channel losts the focus by the user.
Returns
void
Reimplemented from KviWindow.
References KviIrcView::clearLineMark(), KviIrcView::hasLineMark(), KviWindow::lostUserFocus(), and m_pMessageView.
unsigned int KviChannelWindow::maskCount (char cMode) inline
Returns the number of masks is a channel mode list.
Returns
unsigned int
Referenced by chan_kvs_fnc_bancount(), chan_kvs_fnc_banexceptioncount(), chan_kvs_fnc_invitecount(), and chan_kvs_fnc_maskcount().
KviIrcView* KviChannelWindow::messageView () const inline
Returns the irc view object.
Returns
KviIrcView *
Referenced by window_kvs_cmd_clearOutput().
KviPointerList<KviMaskEntry>* KviChannelWindow::modeMasks (char cMode) inline
Returns a list of masks for a specific mode.
Returns
KviPointerList<KviMaskEntry> *
Referenced by chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_masklist(), chan_kvs_fnc_matchban(), chan_kvs_fnc_matchbanexception(), chan_kvs_fnc_matchinvite(), chan_kvs_fnc_matchmask(), and chan_kvs_fnc_matchqban().
void KviChannelWindow::modeSelectorDone () private slot
Called when we close the mode editor.
References m_pModeEditor, and toggleModeEditor().
Referenced by toggleModeEditor().
int KviChannelWindow::myFlags ()
Returns our flags.
Returns
int
Referenced by KviIrcServerParser::parseNumericNames().
QPixmap * KviChannelWindow::myIconPtr () protected virtual
Returns the correct icon for the channel.
Returns
QPixmap *
Reimplemented from KviWindow.
References KviIconManager::Channel, DeadChan, KviIconManager::DeadChannel, g_pIconManager, KviIconManager::getSmallIcon(), and m_iStateFlags.
const QString& KviChannelWindow::nameWithUserFlag () inline
Returns the name of the channel with user flags.
Returns
const QString &
QString* KviChannelWindow::nextSelectedNickname () inline
Returns the next selected nickname in the userlist.
Returns
QString *
References KviUserListView::nextSelectedNickname().
bool KviChannelWindow::nickChange (const QString & szOldNick, const QString & szNewNick)
Called when someone changes his nick.
Parameters
szOldNick The old nickname of the user
szNewNick The new nickname of the user
Returns
bool
References channelAction(), kvi_getUserActionTemperature(), KVI_USERACTION_NICK, m_pModeLists, m_pUserListView, KviUserListView::nickChange(), and setModeInList().
int KviChannelWindow::opCount () inline
Returns the number of users with op status.
Returns
int
References KviUserListView::opCount().
Referenced by chan_kvs_fnc_opcount().
void KviChannelWindow::opStatusChanged () signal
Emitted when our op status change.
Returns
void
Referenced by setOp().
void KviChannelWindow::outputMessage (int iMsgType, const QString & szMsg) virtual
Outputs a message to the channel window.
Parameters
iMsgType The type of the message
szMsg The message :)
Returns
void
References KviWindow::internalOutput(), KviWindow::m_pIrcView, m_pMessageView, and preprocessMessage().
Referenced by ownAction(), and pasteLastLog().
void KviChannelWindow::ownAction (const QString & szBuffer) virtual
Called when we perform an action.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviIrcConnection::currentNickName(), KviWindow::encodeText(), KviIrcConnection::encodeText(), KviIrcConnectionUserInfo::hostName(), KVI_OPTION_BOOL, KVI_OUT_ACTION, KVI_USERACTION_ACTION, KviEvent_OnMeAction, KviOption_boolStripMircColorsInUserMessages, KVS_TRIGGER_EVENT_2_HALTED, KviWindow::m_szName, KviWindow::makeEncoder(), KviOsInfo::name(), KviIrcConnectionUserInfo::nickName(), outputMessage(), KviControlCodes::stripControlBytes(), szBuffer, userAction(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), and KviWindow::windowName().
void KviChannelWindow::ownMessage (const QString & szBuffer, bool bUserFeedback = true) virtual
Called when we send a message.
Parameters
szBuffer The buffer :)
bUserFeedback Whether to display the echo feedback to the user
Returns
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviControlCodes::CryptEscape, KviWindow::decodeText(), KviCryptEngine::Encoded, KviWindow::encodeText(), KviIrcConnection::encodeText(), KviCryptEngine::Encrypted, KviIrcConnectionUserInfo::hostName(), KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_SYSTEMERROR, KVI_USERACTION_PRIVMSG, KviWindow::m_pConsole, KviWindow::makeEncoder(), KviOsInfo::name(), KviIrcConnectionUserInfo::nickName(), KviConsoleWindow::NoNotifications, KviWindow::output(), KviConsoleWindow::outputPrivmsg(), KviCString::ptr(), KviIrcConnection::sendFmtData(), userAction(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), and KviWindow::windowName().
bool KviChannelWindow::part (const QString & szNick)
Called when someone parts the channel.
Parameters
szNick The nickname of the user who parts
Returns
bool
References channelAction(), kvi_getUserActionTemperature(), KVI_USERACTION_PART, m_pModeLists, m_pUserListView, KviUserListView::part(), and setModeInList().
Referenced by KviIrcServerParser::parseLiteralKick(), and KviIrcServerParser::parseLiteralPart().
void KviChannelWindow::partMessageSent (bool bCloseOnPart = true, bool bShowMessage = true)
Called when we want to part a channel.
Parameters
bCloseOnPart Whether to leave channel open after part
bShowMessage Whether to show part message
Returns
void
References __tr2qs, KVI_OUT_SYSTEMMESSAGE, m_iStateFlags, NoCloseOnPart, KviWindow::outputNoFmt(), and SentPart.
Referenced by closeEvent(), and KviKvsCoreSimpleCommands::KVSCSC().
void KviChannelWindow::pasteLastLog ()
Pastes the most recent channel log into the buffer.
It searches for the most recent channel log of the channel we have just joined, and pastes into the buffer the last N lines, where N is get from the options
Returns
void
References __tr2qs, KviWindow::console(), KviConsoleWindow::currentNetworkName(), g_pApp, KviApplication::getLocalKvircDirectory(), KVI_OPTION_UINT, KVI_OUT_CHANPRIVMSG, KviOption_uintDaysIntervalToPasteOnChannelJoin, KviOption_uintLinesToPasteOnChannelJoin, loadLogFile(), KviApplication::Log, outputMessage(), target(), and u.
Referenced by KviIrcConnection::createChannel().
QString KviChannelWindow::plainChannelMode () inline
Returns only the plain (parameter-less) channel modes (eg: mi)
Returns
QString
Referenced by KviModeEditor::commit(), KviModeEditor::KviModeEditor(), and KviTopicWidget::switchMode().
void KviChannelWindow::prependUserFlag (const QString & szNick, QString & szBuffer) inline
Prepends the user flag to the nickname.
Parameters
szNick The nickname of the user
szBuffer The buffer :)
Returns
void
References KviUserListView::prependUserFlag().
void KviChannelWindow::preprocessMessage (QString & szMessage) protected virtual
Preprocess message stripping control bytes.
Parameters
szMessage The message :)
Returns
void
Reimplemented from KviWindow.
References findEntry(), serverInfo(), KviControlCodes::stripControlBytes(), and KviIrcConnectionServerInfo::supportedChannelTypes().
Referenced by outputMessage().
void KviChannelWindow::removeHighlightedUser (const QString & szNick)
Removes a user from the highlight list.
Parameters
szNick The nickname of the user
Returns
void
References m_pTmpHighLighted.
void KviChannelWindow::removeMasks (KviMaskEditor * pEd, KviPointerList< KviMaskEntry > * pList) private slot
Removes the masks from the mask editor window.
Parameters
pEd The mask editor
pList The list of masks to remove
Returns
void
References KviWindow::connection(), KviIrcConnection::encodeText(), KviPointerList< T >::first(), KviMaskEditor::flag(), KviWindow::m_szName, KviIrcConnectionServerInfo::maxModeChanges(), KviPointerList< T >::next(), KviPointerList< T >::prev(), KviIrcConnection::sendFmtData(), and serverInfo().
Referenced by toggleListModeEditor().
void KviChannelWindow::resizeEvent (QResizeEvent *) protected virtual
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, KviWindow::m_pSplitter, m_pTopicWidget, and KviTopicWidget::sizeHint().
Referenced by loadProperties(), and toggleModeEditor().
void KviChannelWindow::saveProperties (KviConfigurationFile * pCfg) protected virtual
Saves the properties to file.
Parameters
pCfg The config file
Returns
void
Reimplemented from KviWindow.
References buttonContainer(), m_pMessageView, m_privateBackground, KviWindow::m_pSplitter, m_pTopSplitter, m_pUserListView, m_pVertSplitter, m_SplitterSizesList, m_VertSplitterSizesList, KviWindow::saveProperties(), and KviConfigurationFile::writeEntry().
int KviChannelWindow::selectedCount () inline
Returns the number of selected users.
Returns
int
References KviUserListView::selectedCount().
bool KviChannelWindow::sentListRequest (char cMode) inline
Returns true if we have sent a list request for a specific channel mode.
Returns
bool
Referenced by KviIrcServerParser::parseNumeric367(), and KviIrcServerParser::parseNumeric368().
bool KviChannelWindow::sentSyncWhoRequest () inline
Returns true if we have sent the sync WHO request.
Returns
bool
Referenced by KviIrcServerParser::parseNumericEndOfWho(), and KviIrcServerParser::parseNumericWhoReply().
bool KviChannelWindow::sentWhoRequest () inline
Returns true if we have sent the WHO request.
Returns
bool
KviIrcConnectionServerInfo * KviChannelWindow::serverInfo ()
Gets the KviIrcConnectionServerInfo structure associated to the current connection.
Returns
KviIrcConnectionServerInfo*
References KviWindow::connection(), and KviIrcConnection::serverInfo().
Referenced by KviModeEditor::commit(), KviModeWidget::editorReturnPressed(), KviModeEditor::getModeDescription(), KviChannelWindow(), KviMaskEditor::KviMaskEditor(), KviModeEditor::KviModeEditor(), KviModeWidget::modeNeedsParameterOnlyWhenSet(), KviModeEditor::modeNeedsParameterOnlyWhenSet(), preprocessMessage(), removeMasks(), KviIrcConnectionRequestQueue::timerSlot(), and updateModeLabel().
void KviChannelWindow::setAliveChan ()
Sets the channel as alive.
Returns
void
References KviWindow::Channel, KviWindow::connection(), KviWindow::context(), KviIrcConnection::encodeText(), KviIrcView::isLogging(), m_iStateFlags, m_joinTime, KviWindow::m_pIrcView, m_pListEditors, m_pTopicWidget, m_pUserListView, KviWindow::m_szName, m_szSentModeRequests, KviIrcConnection::registerChannel(), KviTopicWidget::reset(), KviIrcConnection::sendFmtData(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcView::startLogging(), KviIrcContext::unregisterDeadChannel(), KviWindow::updateCaption(), and KviWindow::updateIcon().
Referenced by KviIrcConnection::createChannel().
bool KviChannelWindow::setChanAdmin (const QString & szNick, bool bChanAdmin) inline
Sets the chan admin mode.
Parameters
szNick The nick to set the mode on
bChanAdmin Whether to set or unset the mode on the user
Returns
bool
References KviUserListView::setChanAdmin().
Referenced by KviIrcServerParser::parseChannelMode().
void KviChannelWindow::setChannelMode (char cMode, bool bAdd)
Sets a plain (parameter-less) channel mode, (eg: +m)
Parameters
cMode The mode to set
bAdd Whether to add or remove the mode
Returns
void
References m_szChannelMode, KviWindow::updateCaption(), and updateModeLabel().
Referenced by KviIrcServerParser::parseChannelMode().
void KviChannelWindow::setChannelModeWithParam (char cMode, QString & szParam)
Sets a channel mode with a parameter; an empty parameter unsets the mode (eg: +k password)
Parameters
cMode The mode
szParam The parameter for the mode
Returns
void
References m_szChannelParameterModes, KviWindow::updateCaption(), and updateModeLabel().
Referenced by KviIrcServerParser::parseChannelMode().
bool KviChannelWindow::setChanOwner (const QString & szNick, bool bChanOwner) inline
Sets the chan owner mode.
Parameters
szNick The nick to set the mode on
bChanOwner Whether to set or unset the mode on the user
Returns
bool
References KviUserListView::setChanOwner().
Referenced by KviIrcServerParser::parseChannelMode().
void KviChannelWindow::setDeadChan ()
Sets the channel as dead.
Returns
void
References KviWindow::connection(), KviWindow::context(), DeadChan, KviWindow::DeadChannel, KviUserListView::enableUpdates(), m_iStateFlags, m_pActionHistory, m_pListEditors, m_pModeLists, m_pTopicWidget, m_pUserListView, m_szChannelMode, m_szChannelParameterModes, m_szSentModeRequests, m_uActionHistoryHotActionCount, NoCloseOnPart, KviUserListView::partAll(), KviIrcContext::registerDeadChannel(), KviTopicWidget::reset(), SentSyncWhoRequest, KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcConnection::unregisterChannel(), KviWindow::updateCaption(), KviWindow::updateIcon(), and updateModeLabel().
Referenced by KviIrcServerParser::parseLiteralKick(), and KviIrcServerParser::parseLiteralPart().
bool KviChannelWindow::setHalfOp (const QString & szNick, bool bHalfOp, bool) inline
Sets the half operator mode.
Parameters
szNick The nick to set the mode on
bHalfOp Whether to set or unset the mode on the user
Returns
bool
References KviUserListView::setHalfOp().
void KviChannelWindow::setHasAllNames () inline
Sets the existance of all names.
Returns
void
Referenced by KviIrcServerParser::parseNumericEndOfNames().
void KviChannelWindow::setHasWhoList () inline
Sets the existance of the WHO list.
Returns
void
Referenced by KviIrcServerParser::parseNumericEndOfWho().
void KviChannelWindow::setLastReceivedWhoReply (kvi_time_t tTime) inline
Sets the time of the last received WHO reply.
Parameters
tTime The source time
Returns
void
Referenced by KviIrcServerParser::parseNumericEndOfWho().
void KviChannelWindow::setListRequestDone (char cMode) inline
Clears the "sent request" flag for a specific chanel mode.
Returns
void
Referenced by KviIrcServerParser::parseNumeric368().
void KviChannelWindow::setMode (QString & szMode) private slot
Called when we select the modes from the mode editor.
Parameters
szMode The modes selected, including any plus/minus sign and parameters
Returns
void
References KviWindow::connection(), KviIrcConnection::encodeText(), KviWindow::m_szName, and KviIrcConnection::sendFmtData().
Referenced by KviChannelWindow(), and toggleModeEditor().
void KviChannelWindow::setModeInList (char cMode, const QString & szMask, bool bAdd, const QString & szSetBy, unsigned int uSetAt, QString szChangeMask = QString())
Called when someone sets a channel mode that is stored in a list; these modes require a parameter that is tipically a mask.
Examples:
b: ban with mask
e: ban exception with mask
I: invite exception with mask
q: channel owner with nick (unreal) or quiet ban (ircd-seven)
g: spam filter word (inspircd)
Parameters
cMode The type of the mask
szMask The mask set (more generically, the parameter)
bAdd Whether to add or remove the mask
szSetBy Who set the mask
uSetAt The datetime when the mask was set
szChangeMask If bAdd is false and this string is set, the mask will be updated instead that removed
Returns
void
References KviWindow::connection(), KviPointerList< T >::count(), internalMask(), m_pListEditors, m_pModeLists, m_pUserListView, KviPointerList< T >::setAutoDelete(), and KviUserListView::setMaskEntries().
Referenced by nickChange(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseNumeric367(), and part().
bool KviChannelWindow::setOp (const QString & szNick, bool bOp, bool bIsMe)
Sets the operator mode.
Parameters
szNick The nick to set the mode on
bOp Whether to set or unset the mode on the user
bIsMe Whether the user opped is us
Returns
bool
References m_pUserListView, opStatusChanged(), and KviUserListView::setOp().
void KviChannelWindow::setSentListRequest (char cMode) inline
Sets the "sent request" flag for a specific channel mode.
Returns
void
Referenced by KviIrcConnectionRequestQueue::timerSlot().
void KviChannelWindow::setSentSyncWhoRequest () inline
Sets the sync WHO request flag.
Returns
void
Referenced by KviIrcConnection::heartbeat().
void KviChannelWindow::setSentWhoRequest () inline
Sets the WHO request flag.
Returns
void
Referenced by KviIrcConnectionRequestQueue::timerSlot().
bool KviChannelWindow::setUserOp (const QString & szNick, bool bUserOp, bool) inline
Sets the user operator mode.
Parameters
szNick The nick to set the mode on
bUserOp Whether to set or unset the mode on the user
Returns
bool
References KviUserListView::setUserOp().
bool KviChannelWindow::setVoice (const QString & szNick, bool bVoice, bool) inline
Sets the voice mode.
Parameters
szNick The nick to set the mode on
bVoice Whether to set or unset the mode on the user
Returns
bool
References KviUserListView::setVoice().
void KviChannelWindow::showDoubleView (bool bShow) protected
Splits the channel view into two views.
The upper one will be used to show all system messages like join, parts, quits, topics and so on, while the lower one will be used to show the users messages.
Parameters
bShow Whether to show the double view
Returns
void
References connect(), KviIrcView::joinMessagesFrom(), m_pDoubleViewButton, KviWindow::m_pIrcView, m_pMessageView, m_privateBackground, m_pVertSplitter, m_VertSplitterSizesList, KviPixmap::pixmap(), KviIrcView::setMasterView(), KviIrcView::setPrivateBackgroundPixmap(), KviIrcView::splitMessagesTo(), and textViewRightClicked().
Referenced by loadProperties(), and toggleDoubleView().
QSize KviChannelWindow::sizeHint () const virtual
Returns the size of the channel.
Returns
QSize
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviIrcView::sizeHint().
virtual const QString& KviChannelWindow::target () inline virtual
Returns the name of the channel.
Returns
const QString &
Reimplemented from KviWindow.
References KviWindow::windowName().
Referenced by KviMaskInputDialog::accept(), getConfigGroupName(), pasteLastLog(), and KviIrcConnectionRequestQueue::timerSlot().
void KviChannelWindow::textViewRightClicked () private slot
Called when we right-click the irc view.
Trigger the OnChannelPopupRequest event
Returns
void
References KviEvent_OnChannelPopupRequest, and KVS_TRIGGER_EVENT_0.
Referenced by KviChannelWindow(), and showDoubleView().
void KviChannelWindow::toggleDoubleView () private slot
Toggles the double view mode.
Returns
void
References m_pDoubleViewButton, m_pMessageView, and showDoubleView().
Referenced by KviChannelWindow().
void KviChannelWindow::toggleListModeEditor () private slot
Toggles a list mode editor.
Returns
void
References connect(), KviWindow::connection(), KviIrcConnection::encodeText(), m_pListEditorButtons, m_pListEditors, m_pModeLists, KviWindow::m_pSplitter, KviWindow::m_szName, m_szSentModeRequests, removeMasks(), KviIrcConnection::sendFmtData(), and KviPointerList< T >::setAutoDelete().
Referenced by KviChannelWindow().
void KviChannelWindow::toggleListView () private slot
Toggles the userlist view.
Returns
void
References m_pListViewButton, KviWindow::m_pSplitter, m_pUserListView, and m_SplitterSizesList.
Referenced by KviChannelWindow().
void KviChannelWindow::toggleModeEditor () private slot
Toggles the mode editor.
Returns
void
References connect(), KviKvs::done(), m_pModeEditor, m_pModeEditorButton, KviWindow::m_pSplitter, modeSelectorDone(), resizeEvent(), and setMode().
Referenced by KviChannelWindow(), and modeSelectorDone().
void KviChannelWindow::toggleToolButtons () private slot
Toggles tool buttons widget over the listview.
Returns
void
References buttonContainer(), g_pIconManager, KviIconManager::getBigIcon(), KviWindow::m_pHideToolsButton, and KviWindow::toggleButtonContainer().
Referenced by KviChannelWindow(), and loadProperties().
void KviChannelWindow::topicSelected (const QString & szTopic) private slot
Called when we select the topic.
Parameters
szTopic The topic :)
Returns
void
References __tr2qs, KviWindow::connection(), KviControlCodes::CryptEscape, KviCryptEngine::Encoded, KviWindow::encodeText(), KviIrcConnection::encodeText(), KviCryptEngine::Encrypted, KVI_OUT_SYSTEMERROR, KviWindow::m_szName, KviOsInfo::name(), KviWindow::output(), KviCString::ptr(), and KviIrcConnection::sendFmtData().
Referenced by KviChannelWindow().
KviTopicWidget* KviChannelWindow::topicWidget () inline
Returns the topic widget object.
Returns
KviTopicWidget *
Referenced by chan_kvs_fnc_topic(), chan_kvs_fnc_topicsetat(), chan_kvs_fnc_topicsetby(), KviIrcView::doLinkToolTip(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericTopic(), and KviIrcServerParser::parseNumericTopicWhoTime().
void KviChannelWindow::triggerCreationEvents () protected virtual
Trigger the OnChannelWindowCreated event.
Returns
void
Reimplemented from KviWindow.
References KviEvent_OnChannelWindowCreated, and KVS_TRIGGER_EVENT_0.
void KviChannelWindow::unhighlight ()
Unhighlights the windowlist item.
Returns
void
References KviWindow::m_pWindowListItem, and KviWindowListItem::unhighlight().
void KviChannelWindow::updateModeLabel ()
Updates the tooltip over the channel modes.
Returns
void
References __tr2qs, KviTalToolTip::add(), KviQString::appendFormatted(), KviWindow::connection(), KviIrcConnectionServerInfo::getChannelModeDescription(), KviWindow::m_pConsole, m_pModeWidget, m_szChannelMode, m_szChannelParameterModes, KviCString::ptr(), KviModeWidget::refreshModes(), KviTalToolTip::remove(), KviIrcConnection::serverInfo(), serverInfo(), and KviQString::toHtmlEscaped().
Referenced by setChannelMode(), setChannelModeWithParam(), and setDeadChan().
void KviChannelWindow::userAction (KviIrcMask * user, unsigned int uActionType)
Perform a user action in the channel.
Parameters
user The user who made the action
uActionType The type of the action
Returns
void
References channelAction(), kvi_getUserActionTemperature(), m_pUserListView, KviIrcMask::nick(), and KviUserListView::userAction().
Referenced by ownAction(), ownMessage(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), and KviIrcServerParser::parseLiteralTopic().
void KviChannelWindow::userAction (const QString & szNick, unsigned int uActionType)
Perform a user action in the channel.
Parameters
szNick The nickname of the user who made the action
uActionType The type of the action
Returns
void
References channelAction(), kvi_getUserActionTemperature(), m_pUserListView, and KviUserListView::userAction().
void KviChannelWindow::userAction (const QString & szNick, const QString & szUser, const QString & szHost, unsigned int uActionType)
Perform a user action in the channel.
Parameters
szNick The nickname of the user who made the action
szUser The username of the user who made the action
szHost The hostname of the user who made the action
uActionType The type of the action
Returns
void
References channelAction(), kvi_getUserActionTemperature(), m_pUserListView, and KviUserListView::userAction().
KviUserListView* KviChannelWindow::userListView () inline
Returns the user listview object.
Returns
KviUserListView *
Referenced by chan_kvs_fnc_getflag(), chan_kvs_fnc_userjointime(), chan_kvs_fnc_userlastactiontime(), chan_kvs_fnc_usermodelevel(), chan_kvs_fnc_users(), and KviIrcServerParser::parseNumericEndOfWho().
int KviChannelWindow::userOpCount () inline
Returns the number of users with userop status.
Returns
int
References KviUserListView::userOpCount().
Referenced by chan_kvs_fnc_useropcount().
int KviChannelWindow::voiceCount () inline
Returns the number of users with voice status.
Returns
int
References KviUserListView::voiceCount().
Referenced by chan_kvs_fnc_voicecount().
Member Data Documentation
int KviChannelWindow::m_iStateFlags protected
Referenced by checkChannelSync(), closeEvent(), getWindowListTipText(), KviChannelWindow(), myIconPtr(), partMessageSent(), setAliveChan(), and setDeadChan().
QDateTime KviChannelWindow::m_joinTime protected
Referenced by activityMeter(), checkChannelSync(), getChannelActivityStats(), KviChannelWindow(), and setAliveChan().
KviPointerList<KviChannelAction>* KviChannelWindow::m_pActionHistory protected
Referenced by activityMeter(), channelAction(), fixActionHistory(), getChannelActivityStats(), KviChannelWindow(), setDeadChan(), and ~KviChannelWindow().
KviTalHBox* KviChannelWindow::m_pButtonContainer protected
Referenced by KviChannelWindow().
QToolButton* KviChannelWindow::m_pDoubleViewButton protected
Referenced by KviChannelWindow(), showDoubleView(), and toggleDoubleView().
QMap<char, KviWindowToolPageButton *> KviChannelWindow::m_pListEditorButtons protected
Referenced by KviChannelWindow(), toggleListModeEditor(), and ~KviChannelWindow().
QMap<char, KviMaskEditor *> KviChannelWindow::m_pListEditors protected
Referenced by setAliveChan(), setDeadChan(), setModeInList(), toggleListModeEditor(), and ~KviChannelWindow().
KviWindowToolPageButton* KviChannelWindow::m_pListViewButton protected
Referenced by KviChannelWindow(), loadProperties(), and toggleListView().
KviIrcView* KviChannelWindow::m_pMessageView protected
Referenced by applyOptions(), KviChannelWindow(), loadProperties(), lostUserFocus(), outputMessage(), saveProperties(), showDoubleView(), and toggleDoubleView().
KviModeEditor* KviChannelWindow::m_pModeEditor protected
Referenced by KviChannelWindow(), modeSelectorDone(), and toggleModeEditor().
KviWindowToolPageButton* KviChannelWindow::m_pModeEditorButton protected
Referenced by KviChannelWindow(), and toggleModeEditor().
QMap<char, KviPointerList<KviMaskEntry> *> KviChannelWindow::m_pModeLists protected
Referenced by nickChange(), part(), setDeadChan(), setModeInList(), toggleListModeEditor(), and ~KviChannelWindow().
KviModeWidget* KviChannelWindow::m_pModeWidget protected
Referenced by applyOptions(), KviChannelWindow(), and updateModeLabel().
KviPixmap KviChannelWindow::m_privateBackground protected
Referenced by loadProperties(), saveProperties(), and showDoubleView().
QStringList* KviChannelWindow::m_pTmpHighLighted protected
Referenced by addHighlightedUser(), KviChannelWindow(), removeHighlightedUser(), and ~KviChannelWindow().
KviTopicWidget* KviChannelWindow::m_pTopicWidget protected
Referenced by applyOptions(), eventFilter(), KviChannelWindow(), resizeEvent(), setAliveChan(), and setDeadChan().
KviTalSplitter* KviChannelWindow::m_pTopSplitter protected
Referenced by KviChannelWindow(), loadProperties(), and saveProperties().
KviUserListView* KviChannelWindow::m_pUserListView protected
Referenced by addHighlightedUser(), applyOptions(), getWindowListTipText(), KviChannelWindow(), loadProperties(), nickChange(), part(), saveProperties(), setAliveChan(), setDeadChan(), setModeInList(), setOp(), toggleListView(), userAction(), and ~KviChannelWindow().
KviTalSplitter* KviChannelWindow::m_pVertSplitter protected
Referenced by KviChannelWindow(), saveProperties(), and showDoubleView().
QList<int> KviChannelWindow::m_SplitterSizesList protected
Referenced by loadProperties(), saveProperties(), and toggleListView().
QString KviChannelWindow::m_szChannelMode protected
Referenced by getChannelModeString(), getChannelModeStringWithEmbeddedParams(), setChannelMode(), setDeadChan(), and updateModeLabel().
QMap<char, QString> KviChannelWindow::m_szChannelParameterModes protected
Referenced by getChannelModeString(), getChannelModeStringWithEmbeddedParams(), setChannelModeWithParam(), setDeadChan(), and updateModeLabel().
QString KviChannelWindow::m_szNameWithUserFlag protected
Referenced by fillCaptionBuffers().
QString KviChannelWindow::m_szSentModeRequests protected
Referenced by checkChannelSync(), setAliveChan(), setDeadChan(), and toggleListModeEditor().
kvi_time_t KviChannelWindow::m_tLastReceivedWhoReply protected
Referenced by KviChannelWindow().
unsigned int KviChannelWindow::m_uActionHistoryHotActionCount protected
Referenced by activityMeter(), channelAction(), fixActionHistory(), KviChannelWindow(), and setDeadChan().
QList<int> KviChannelWindow::m_VertSplitterSizesList protected
Referenced by loadProperties(), saveProperties(), and showDoubleView().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviChannelWindow.h
src/kvirc/ui/KviChannelWindow.cpp