KVIrc: KviKvsProcessAsyncOperation Class Reference
KviKvsProcessAsyncOperation Class Reference
#include <KviKvsProcessManager.h>
Public Member Functions
KviKvsProcessAsyncOperation (KviKvsProcessDescriptorData *d)
bool start ()
~KviKvsProcessAsyncOperation ()
Public Member Functions inherited from KviKvsAsyncOperation
KviKvsAsyncOperation (KviWindow *pWnd)
KviWindow * window ()
virtual ~KviKvsAsyncOperation ()
Protected Types
enum CallbackEvent {
EventStarted, EventTerminated, EventStdout, EventStderr,
EventPing
}
Private Slots
void maxRunTimeExpired ()
void ping ()
void processExited (int exitCode)
void processStarted ()
void readStderr ()
void readStdout ()
void selfDelete ()
Private Member Functions
bool trigger (CallbackEvent e, const QString &szData)
void triggerSelfDelete ()
Private Attributes
bool m_bDeletePending
KviKvsProcessDescriptorData * m_pData
KviKvsExtendedRunTimeData * m_pExtendedRunTimeData
QTimer * m_pPingTimer
QProcess * m_pProcess
QTimer * m_pRunTimeTimer
QString m_szStderrBuffer
QString m_szStdoutBuffer
Friends
class KviKvsProcessManager
Additional Inherited Members
Protected Attributes inherited from KviKvsAsyncOperation
KviWindow * m_pWnd
Member Enumeration Documentation
enum KviKvsProcessAsyncOperation::CallbackEvent protected
Enumerator
EventStarted
EventTerminated
EventStdout
EventStderr
EventPing
Constructor & Destructor Documentation
KviKvsProcessAsyncOperation::KviKvsProcessAsyncOperation (KviKvsProcessDescriptorData * d)
References d, m_bDeletePending, m_pData, m_pExtendedRunTimeData, m_pPingTimer, m_pProcess, and m_pRunTimeTimer.
KviKvsProcessAsyncOperation::~KviKvsProcessAsyncOperation ()
References m_pData, m_pExtendedRunTimeData, m_pPingTimer, m_pProcess, m_pRunTimeTimer, _KviKvsProcessDescriptorData::pCallback, and _KviKvsProcessDescriptorData::pMagic.
Member Function Documentation
void KviKvsProcessAsyncOperation::maxRunTimeExpired () private slot
References EventTerminated, trigger(), and triggerSelfDelete().
Referenced by start().
void KviKvsProcessAsyncOperation::ping () private slot
References EventPing, trigger(), and triggerSelfDelete().
Referenced by start().
void KviKvsProcessAsyncOperation::processExited (int exitCode) private slot
References EventStdout, EventTerminated, _KviKvsProcessDescriptorData::iFlags, KVI_KVS_PROCESSDESCRIPTOR_OUTPUTBYBLOCKS, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDERR, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDOUT, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERTERMINATED, m_bDeletePending, m_pData, m_szStderrBuffer, m_szStdoutBuffer, readStderr(), readStdout(), trigger(), and triggerSelfDelete().
Referenced by start().
void KviKvsProcessAsyncOperation::processStarted () private slot
References EventStarted, m_bDeletePending, m_pProcess, trigger(), and triggerSelfDelete().
Referenced by start().
void KviKvsProcessAsyncOperation::readStderr () private slot
References a, EventStderr, _KviKvsProcessDescriptorData::iFlags, KVI_KVS_PROCESSDESCRIPTOR_OUTPUTBYBLOCKS, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDERR, l, m_bDeletePending, m_pData, m_pProcess, m_szStderrBuffer, trigger(), and triggerSelfDelete().
Referenced by processExited(), and start().
void KviKvsProcessAsyncOperation::readStdout () private slot
References a, EventStdout, _KviKvsProcessDescriptorData::iFlags, KVI_KVS_PROCESSDESCRIPTOR_OUTPUTBYBLOCKS, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDOUT, l, m_bDeletePending, m_pData, m_pProcess, m_szStdoutBuffer, trigger(), and triggerSelfDelete().
Referenced by processExited(), and start().
void KviKvsProcessAsyncOperation::selfDelete () private slot
Referenced by triggerSelfDelete().
bool KviKvsProcessAsyncOperation::start ()
References connect(), _KviKvsProcessDescriptorData::iFlags, _KviKvsProcessDescriptorData::iMaxRunTime, _KviKvsProcessDescriptorData::iPingTimeout, KVI_KVS_PROCESSDESCRIPTOR_NOSHELL, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTARTED, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDERR, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDOUT, m_pData, m_pPingTimer, m_pProcess, m_pRunTimeTimer, maxRunTimeExpired(), ping(), processExited(), processStarted(), readStderr(), readStdout(), _KviKvsProcessDescriptorData::szCommandline, and _KviKvsProcessDescriptorData::szShell.
Referenced by KviKvsCoreCallbackCommands::KVSCCC().
bool KviKvsProcessAsyncOperation::trigger (CallbackEvent e, const QString & szData) private
References __tr2qs_ctx(), KviApplication::activeConsole(), KviKvsVariantList::append(), KviKvsVariant::asString(), KviKvsVariant::copyFrom(), EventPing, EventStarted, EventStderr, EventStdout, EventTerminated, g_pApp, KviKvsScript::HaltEncountered, _KviKvsProcessDescriptorData::iFlags, KviKvsVariant::isNothing(), KVI_KVS_PROCESSDESCRIPTOR_KILLIFNOWINDOW, KVI_OUT_PARSERERROR, m_bDeletePending, m_pData, m_pExtendedRunTimeData, m_pProcess, KviWindow::output(), _KviKvsProcessDescriptorData::pCallback, _KviKvsProcessDescriptorData::pMagic, KviKvsScript::PreserveParams, _KviKvsProcessDescriptorData::pWnd, KviKvsScript::run(), KviKvsVariantList::setAutoDelete(), and KviApplication::windowExists().
Referenced by maxRunTimeExpired(), ping(), processExited(), processStarted(), readStderr(), and readStdout().
void KviKvsProcessAsyncOperation::triggerSelfDelete () private
References _KviKvsProcessDescriptorData::iMaxRunTime, m_bDeletePending, m_pData, and selfDelete().
Referenced by maxRunTimeExpired(), ping(), processExited(), processStarted(), readStderr(), and readStdout().
Friends And Related Function Documentation
friend class KviKvsProcessManager friend
Member Data Documentation
bool KviKvsProcessAsyncOperation::m_bDeletePending private
Referenced by KviKvsProcessAsyncOperation(), processExited(), processStarted(), readStderr(), readStdout(), trigger(), and triggerSelfDelete().
KviKvsProcessDescriptorData* KviKvsProcessAsyncOperation::m_pData private
Referenced by KviKvsProcessAsyncOperation(), processExited(), readStderr(), readStdout(), start(), trigger(), triggerSelfDelete(), and ~KviKvsProcessAsyncOperation().
KviKvsExtendedRunTimeData* KviKvsProcessAsyncOperation::m_pExtendedRunTimeData private
Referenced by KviKvsProcessAsyncOperation(), trigger(), and ~KviKvsProcessAsyncOperation().
QTimer* KviKvsProcessAsyncOperation::m_pPingTimer private
Referenced by KviKvsProcessAsyncOperation(), start(), and ~KviKvsProcessAsyncOperation().
QProcess* KviKvsProcessAsyncOperation::m_pProcess private
Referenced by KviKvsProcessAsyncOperation(), processStarted(), readStderr(), readStdout(), start(), trigger(), and ~KviKvsProcessAsyncOperation().
QTimer* KviKvsProcessAsyncOperation::m_pRunTimeTimer private
Referenced by KviKvsProcessAsyncOperation(), start(), and ~KviKvsProcessAsyncOperation().
QString KviKvsProcessAsyncOperation::m_szStderrBuffer private
Referenced by processExited(), and readStderr().
QString KviKvsProcessAsyncOperation::m_szStdoutBuffer private
Referenced by processExited(), and readStdout().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsProcessManager.h
src/kvirc/kvs/KviKvsProcessManager.cpp