KVIrc: KviKvsDnsManager Class Reference
KviKvsDnsManager Class Reference
#include <kvi_kvs_dnsmanager.h>
Public Member Functions
void addDns (KviKvsDnsObject *pObject)
KviKvsDnsManager ()
~KviKvsDnsManager ()
Static Public Member Functions
static void done ()
static void init ()
static KviKvsDnsManager * instance ()
Protected Slots
void dnsLookupTerminated (KviDns *pDns)
Protected Attributes
KviPointerHashTable< void
*, KviKvsDnsObject > * m_pDnsObjects
Static Protected Attributes
static KviKvsDnsManager * m_pInstance = 0
Private Member Functions
void abortAll ()
Constructor & Destructor Documentation
KviKvsDnsManager::KviKvsDnsManager ()
References m_pDnsObjects.
Referenced by init().
KviKvsDnsManager::~KviKvsDnsManager ()
References m_pDnsObjects.
Member Function Documentation
void KviKvsDnsManager::abortAll () [private]
void KviKvsDnsManager::addDns (KviKvsDnsObject * pObject)
References KviKvsDnsObject::dns(), dnsLookupTerminated(), m_pDnsObjects, KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
void KviKvsDnsManager::dnsLookupTerminated (KviDns * pDns) [protected, slot]
References __tr2qs_ctx, KviKvsDnsObject::callback(), debug, KviKvsDnsObject::dns(), KviDns::error(), KviDns::Failure, KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), g_pActiveWindow, g_pApp, KviError::getDescription(), KviDns::hostnameList(), KviDns::ipAddressList(), KVI_OUT_HOSTLOOKUP, m_pDnsObjects, KviPointerList< T >::next(), KviWindow::output(), KviKvsDnsObject::parameterList(), KviKvsVariantList::prepend(), KviKvsScript::PreserveParams, KviDns::query(), KviKvsDnsObject::query(), KviKvsDnsObject::rebindOnWindowClose(), KviPointerHashTable< Key, T >::remove(), KviKvsScript::run(), KviKvsDnsObject::setParameterList(), KviKvsDnsObject::setWindow(), KviDns::state(), KviKvsDnsObject::window(), and KviApp::windowExists().
Referenced by addDns().
void KviKvsDnsManager::done () [static]
References debug.
void KviKvsDnsManager::init () [static]
References debug, and KviKvsDnsManager().
static KviKvsDnsManager* KviKvsDnsManager::instance () [inline, static]
References m_pInstance.
Member Data Documentation
KviPointerHashTable<void *,KviKvsDnsObject>* KviKvsDnsManager::m_pDnsObjects [protected]
Referenced by addDns(), dnsLookupTerminated(), KviKvsDnsManager(), and ~KviKvsDnsManager().
KviKvsDnsManager * KviKvsDnsManager::m_pInstance = 0 [static, protected]
Referenced by instance().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_dnsmanager.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_dnsmanager.cpp