KVIrc: KviBasicIrcServerInfo Class Reference
KviBasicIrcServerInfo Class Reference
#include <KviIrcConnectionServerInfo.h>
Public Member Functions
virtual const QString & getChannelModeDescription (char mode)
virtual bool getNeedsOperToSetS ()
virtual bool getNeedsOpToListModeseI ()
virtual char getRegisterModeChar ()
virtual const char * getSoftware ()
virtual const QString & getUserModeDescription (QChar mode)
virtual QChar getUserModeRequirement (QChar mode)
KviBasicIrcServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
virtual ~KviBasicIrcServerInfo ()
Protected Attributes
KviIrcConnectionServerInfo * m_pParent
QString m_szServerVersion
Constructor & Destructor Documentation
KviBasicIrcServerInfo::KviBasicIrcServerInfo (KviIrcConnectionServerInfo * pParent = 0, const QString & version = KviQString::Empty)
References m_pParent, m_szServerVersion, and KviRuntimeInfo::version().
KviBasicIrcServerInfo::~KviBasicIrcServerInfo () virtual default
Member Function Documentation
const QString & KviBasicIrcServerInfo::getChannelModeDescription (char mode) virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviBahamutIrcServerInfo, KviCritenIrcServerInfo, KviUnreal40IrcServerInfo, KviUnreal32IrcServerInfo, KviUnrealIrcServerInfo, KviDarenetIrcServerInfo, KviSnircdIrcServerInfo, KviIrcuIrcServerInfo, KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviCharybdisServerInfo, KviIrcdRatboxIrcServerInfo, and KviHybridServerInfo.
References __tr2qs, and KviQString::Empty.
Referenced by KviHybridServerInfo::getChannelModeDescription(), KviIrcuIrcServerInfo::getChannelModeDescription(), KviUnrealIrcServerInfo::getChannelModeDescription(), KviCritenIrcServerInfo::getChannelModeDescription(), KviBahamutIrcServerInfo::getChannelModeDescription(), and KviInspIRCdIrcServerInfo::getChannelModeDescription().
virtual bool KviBasicIrcServerInfo::getNeedsOperToSetS () inline virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviNemesis20IrcServerInfo, KviUnrealIrcServerInfo, KviSnircdIrcServerInfo, KviIrcuIrcServerInfo, and KviCharybdisServerInfo.
virtual bool KviBasicIrcServerInfo::getNeedsOpToListModeseI () inline virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviHyperionIrcServerInfo, KviBahamutIrcServerInfo, KviCritenIrcServerInfo, KviUnrealIrcServerInfo, KviDarenetIrcServerInfo, KviIrcuIrcServerInfo, KviOftcIrcServerInfo, KviPlexusIrcServerInfo, and KviIrcdRatboxIrcServerInfo.
virtual char KviBasicIrcServerInfo::getRegisterModeChar () inline virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviHyperionIrcServerInfo, KviBahamutIrcServerInfo, KviCritenIrcServerInfo, KviUnrealIrcServerInfo, KviDarenetIrcServerInfo, KviIrcuIrcServerInfo, KviOftcIrcServerInfo, KviIrcdSevenIrcServerInfo, KviIrcdRatboxIrcServerInfo, and KviHybridServerInfo.
virtual const char* KviBasicIrcServerInfo::getSoftware () inline virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviHyperionIrcServerInfo, KviBahamutIrcServerInfo, KviNemesis20IrcServerInfo, KviNemesisIrcServerInfo, KviCritenIrcServerInfo, KviUnreal40IrcServerInfo, KviUnreal32IrcServerInfo, KviUnrealIrcServerInfo, KviDarenetIrcServerInfo, KviSnircdIrcServerInfo, KviIrcuIrcServerInfo, KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviIrcdSevenIrcServerInfo, KviCharybdisServerInfo, KviIrcdRatboxIrcServerInfo, and KviHybridServerInfo.
const QString & KviBasicIrcServerInfo::getUserModeDescription (QChar mode) virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviHyperionIrcServerInfo, KviBahamutIrcServerInfo, KviCritenIrcServerInfo, KviUnreal32IrcServerInfo, KviDarenetIrcServerInfo, KviSnircdIrcServerInfo, KviIrcuIrcServerInfo, KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviIrcdSevenIrcServerInfo, KviCharybdisServerInfo, KviIrcdRatboxIrcServerInfo, and KviHybridServerInfo.
References __tr2qs, and KviQString::Empty.
Referenced by KviHybridServerInfo::getUserModeDescription(), KviIrcuIrcServerInfo::getUserModeDescription(), KviUnreal32IrcServerInfo::getUserModeDescription(), KviCritenIrcServerInfo::getUserModeDescription(), KviBahamutIrcServerInfo::getUserModeDescription(), KviHyperionIrcServerInfo::getUserModeDescription(), and KviInspIRCdIrcServerInfo::getUserModeDescription().
QChar KviBasicIrcServerInfo::getUserModeRequirement (QChar mode) virtual
Reimplemented in KviInspIRCdIrcServerInfo, KviHyperionIrcServerInfo, KviBahamutIrcServerInfo, KviCritenIrcServerInfo, KviUnreal32IrcServerInfo, KviDarenetIrcServerInfo, KviSnircdIrcServerInfo, KviIrcuIrcServerInfo, KviOftcIrcServerInfo, KviPlexusIrcServerInfo, KviIrcdSevenIrcServerInfo, KviCharybdisServerInfo, KviIrcdRatboxIrcServerInfo, and KviHybridServerInfo.
Member Data Documentation
KviIrcConnectionServerInfo* KviBasicIrcServerInfo::m_pParent protected
Referenced by KviBahamutIrcServerInfo::getChannelModeDescription(), and KviBasicIrcServerInfo().
QString KviBasicIrcServerInfo::m_szServerVersion protected
Referenced by KviBasicIrcServerInfo().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionServerInfo.h
src/kvirc/kernel/KviIrcConnectionServerInfo.cpp