KVIrc: ConfigDialog Class Reference
ConfigDialog Class Reference
#include <libkviurl.h>
Public Member Functions
ConfigDialog ()
~ConfigDialog ()
Protected Slots
void acceptbtn ()
void discardbtn ()
Private Member Functions
void closeEvent (QCloseEvent *)
Private Attributes
QCheckBox * cb [cbnum]
BanFrame * m_pBanFrame
Constructor & Destructor Documentation
ConfigDialog::ConfigDialog ()
References __tr2qs, acceptbtn(), cb, connect(), discardbtn(), g, m_pBanFrame, KviConfigurationFile::Read, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::setGroup(), and szConfigPath.
ConfigDialog::~ConfigDialog ()
References cb, cbnum, and i.
Member Function Documentation
void ConfigDialog::acceptbtn () [protected, slot]
References cb, m_pBanFrame, BanFrame::saveBans(), KviConfigurationFile::setGroup(), szConfigPath, KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by ConfigDialog().
void ConfigDialog::closeEvent (QCloseEvent *) [private]
void ConfigDialog::discardbtn () [protected, slot]
Referenced by ConfigDialog().
Member Data Documentation
QCheckBox* ConfigDialog::cb[cbnum] [private]
Referenced by acceptbtn(), ConfigDialog(), and ~ConfigDialog().
BanFrame* ConfigDialog::m_pBanFrame [private]
Referenced by acceptbtn(), and ConfigDialog().
The documentation for this class was generated from the following files:
src/modules/url/libkviurl.h
src/modules/url/libkviurl.cpp