KVIrc: KviKvsCallbackImageDialog Class Reference
KviKvsCallbackImageDialog Class Reference
#include <libkvidialog.h>
Public Member Functions
KviKvsCallbackImageDialog (const QString &szCaption, const QString &szInitialSelection, int iType, int iMaxSize, const QString &szCode, KviKvsVariantList *pMagicParams, KviWindow *pWindow, bool modal=false)
~KviKvsCallbackImageDialog ()
Public Member Functions inherited from KviImageDialog
KviImageDialog (QWidget *par, const QString &szCaption=QString(), int types=KID_TYPE_ALL, int initialType=0, const QString &szInitialDir=QString(), int maxPreviewFileSize=256000, bool modal=false)
const QString & selectedImage ()
virtual ~KviImageDialog ()
Public Member Functions inherited from KviKvsCallbackObject
KviKvsCallbackObject (const QString &szCallbackSource, KviWindow *pTargetWindow, const QString &szCallbackCode, KviKvsVariantList *pMagicParams, unsigned int uFlags=0)
virtual ~KviKvsCallbackObject ()
Protected Member Functions
virtual void done (int code)
Protected Member Functions inherited from KviImageDialog
virtual void closeEvent (QCloseEvent *e)
void jobTerminated ()
void startJob (int type, const QString &szInitialPath=QString())
Protected Member Functions inherited from KviKvsCallbackObject
CallbackStatus execute (KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0)
Additional Inherited Members
Public Types inherited from KviKvsCallbackObject
enum CallbackFlags { OnlyIfWindowExists = 1 }
enum CallbackStatus { Success, Error, HaltEncountered, TargetWindowDead }
Protected Slots inherited from KviImageDialog
void cancelClicked ()
void heartbeat ()
void itemDoubleClicked (QListWidgetItem *it)
void jobTypeSelected (int index)
void okClicked ()
void tipRequest (KviDynamicToolTip *, const QPoint &pnt)
Protected Attributes inherited from KviImageDialog
int m_iJobIndexHelper
int m_iJobType
int m_iMaxPreviewFileSize
QStringList m_lJobFileList
KviTalListWidget * m_pListBox
QTimer * m_pTimer
KviDynamicToolTip * m_pTip
QComboBox * m_pTypeComboBox
QList< int > * m_pTypeList
QString m_szInitialPath
QString m_szJobPath
QString m_szSelectedImage
Protected Attributes inherited from KviKvsCallbackObject
KviKvsVariantList * m_pMagicParams
KviKvsScript * m_pScript
KviWindow * m_pTargetConsole
KviWindow * m_pTargetWindow
unsigned int m_uFlags
Constructor & Destructor Documentation
KviKvsCallbackImageDialog::KviKvsCallbackImageDialog (const QString & szCaption, const QString & szInitialSelection, int iType, int iMaxSize, const QString & szCode, KviKvsVariantList * pMagicParams, KviWindow * pWindow, bool modal = false)
References KviPointerList< T >::append().
KviKvsCallbackImageDialog::~KviKvsCallbackImageDialog ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void KviKvsCallbackImageDialog::done (int code) protected virtual
References KviKvsVariantList::append(), KviKvs::done(), KviKvsCallbackObject::execute(), and KviImageDialog::selectedImage().
The documentation for this class was generated from the following files:
src/modules/dialog/libkvidialog.h
src/modules/dialog/libkvidialog.cpp