KVIrc: OptionsWidget_soundGeneral Class Reference
OptionsWidget_soundGeneral Class Reference
#include <OptionsWidget_sound.h>
Public Member Functions
OptionsWidget_soundGeneral (QWidget *parent)
~OptionsWidget_soundGeneral ()
Public Member Functions inherited from KviOptionsWidget
void addAdvancedButton (int x1, int y1, int x2, int y2)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void mediaAutoDetect ()
void mediaTest ()
void soundAutoDetect ()
void soundTest ()
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
void switchToAdvancedPage ()
Protected Member Functions
virtual void commit ()
void mediaFillBox ()
virtual void showEvent (QShowEvent *e)
void soundFillBox ()
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Protected Attributes
bool m_bFirstShow
QPushButton * m_pMediaAutoDetectButton
QComboBox * m_pMediaPlayerBox
QPushButton * m_pMediaTestButton
QPushButton * m_pSoundAutoDetectButton
QComboBox * m_pSoundSystemBox
QPushButton * m_pSoundTestButton
QComboBox * m_pTagsEncodingCombo
Additional Inherited Members
Signals inherited from KviOptionsWidget
void wantToSwitchToAdvancedPage (KviOptionsWidget *)
Constructor & Destructor Documentation
OptionsWidget_soundGeneral::OptionsWidget_soundGeneral (QWidget * parent)
References __tr2qs_ctx(), KviTalToolTip::add(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), connect(), KviOptionsWidget::createLayout(), d, KviLocale::encodingDescription(), KviQString::equalCI(), g, h, i, KviLocale::instance(), KVI_OPTION_STRING, KviOption_stringMp3TagsEncoding, KviOption_stringWinampTextEncoding, m_bFirstShow, m_pMediaAutoDetectButton, m_pMediaPlayerBox, m_pMediaTestButton, m_pSoundAutoDetectButton, m_pSoundSystemBox, m_pSoundTestButton, m_pTagsEncodingCombo, mediaAutoDetect(), mediaTest(), KviLocale::_EncodingDescription::pcName, soundAutoDetect(), and soundTest().
OptionsWidget_soundGeneral::~OptionsWidget_soundGeneral ()
Member Function Documentation
void OptionsWidget_soundGeneral::commit (void) protected virtual
Reimplemented from KviOptionsWidget.
References KVI_OPTION_STRING, KviOption_stringMp3TagsEncoding, KviOption_stringPreferredMediaPlayer, KviOption_stringSoundSystem, KviOption_stringWinampTextEncoding, m_bFirstShow, m_pMediaPlayerBox, m_pSoundSystemBox, and m_pTagsEncodingCombo.
void OptionsWidget_soundGeneral::mediaAutoDetect () protected slot
References KviModule::ctrl(), g_pApp, g_pModuleManager, KviModuleManager::getModule(), m, and mediaFillBox().
Referenced by OptionsWidget_soundGeneral().
void OptionsWidget_soundGeneral::mediaFillBox () protected
References KviModule::ctrl(), KviQString::equalCI(), g_pModuleManager, KviModuleManager::getModule(), i, KVI_OPTION_STRING, KviOption_stringPreferredMediaPlayer, l, m, m_pMediaAutoDetectButton, m_pMediaPlayerBox, m_pMediaTestButton, and t().
Referenced by mediaAutoDetect(), and showEvent().
void OptionsWidget_soundGeneral::mediaTest () protected slot
Referenced by OptionsWidget_soundGeneral().
void OptionsWidget_soundGeneral::showEvent (QShowEvent * e) protected virtual
References g_pApp, m_bFirstShow, mediaFillBox(), and soundFillBox().
void OptionsWidget_soundGeneral::soundAutoDetect () protected slot
References KviModule::ctrl(), g_pApp, g_pModuleManager, KviModuleManager::getModule(), m, and soundFillBox().
Referenced by OptionsWidget_soundGeneral().
void OptionsWidget_soundGeneral::soundFillBox () protected
References KviModule::ctrl(), KviQString::equalCI(), g_pModuleManager, KviModuleManager::getModule(), i, KVI_OPTION_STRING, KviOption_stringSoundSystem, l, m, m_pSoundAutoDetectButton, m_pSoundSystemBox, m_pSoundTestButton, and t().
Referenced by showEvent(), and soundAutoDetect().
void OptionsWidget_soundGeneral::soundTest () protected slot
References KviModule::ctrl(), KviApplication::findAudioFile(), g_pApp, g_pModuleManager, KviModuleManager::getModule(), KVI_OPTION_STRING, KviOption_stringSoundSystem, m, and m_pSoundSystemBox.
Referenced by OptionsWidget_soundGeneral().
Member Data Documentation
bool OptionsWidget_soundGeneral::m_bFirstShow protected
Referenced by commit(), OptionsWidget_soundGeneral(), and showEvent().
QPushButton* OptionsWidget_soundGeneral::m_pMediaAutoDetectButton protected
Referenced by mediaFillBox(), and OptionsWidget_soundGeneral().
QComboBox* OptionsWidget_soundGeneral::m_pMediaPlayerBox protected
Referenced by commit(), mediaFillBox(), and OptionsWidget_soundGeneral().
QPushButton* OptionsWidget_soundGeneral::m_pMediaTestButton protected
Referenced by mediaFillBox(), and OptionsWidget_soundGeneral().
QPushButton* OptionsWidget_soundGeneral::m_pSoundAutoDetectButton protected
Referenced by OptionsWidget_soundGeneral(), and soundFillBox().
QComboBox* OptionsWidget_soundGeneral::m_pSoundSystemBox protected
Referenced by commit(), OptionsWidget_soundGeneral(), soundFillBox(), and soundTest().
QPushButton* OptionsWidget_soundGeneral::m_pSoundTestButton protected
Referenced by OptionsWidget_soundGeneral(), and soundFillBox().
QComboBox* OptionsWidget_soundGeneral::m_pTagsEncodingCombo protected
Referenced by commit(), and OptionsWidget_soundGeneral().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_sound.h
src/modules/options/OptionsWidget_sound.cpp