KVIrc: KviStupidNotifyListManager Class Reference
KviStupidNotifyListManager Class Reference
#include <KviNotifyList.h>
Protected Member Functions
virtual bool handleIsOn (KviIrcMessage *msg)
KviStupidNotifyListManager (KviIrcConnection *pConnection)
virtual void start ()
virtual void stop ()
virtual void timerEvent (QTimerEvent *e)
~KviStupidNotifyListManager ()
Protected Member Functions inherited from KviNotifyListManager
virtual bool handleUserhost (KviIrcMessage *msg)
virtual bool handleWatchReply (KviIrcMessage *msg)
KviNotifyListManager (KviIrcConnection *pConnection)
void notifyOffLine (const QString &nick, const QString &user=QString(), const QString &host=QString(), const QString &szReason=QString())
void notifyOnLine (const QString &nick, const QString &user=QString(), const QString &host=QString(), const QString &szReason=QString(), bool bJoin=true)
~KviNotifyListManager ()
Protected Attributes
int m_iNextNickToCheck
int m_iRestartTimer
KviPointerList< QString > * m_pNickList
QString m_szLastIsOnMsg
Protected Attributes inherited from KviNotifyListManager
KviIrcConnection * m_pConnection
KviConsoleWindow * m_pConsole
Private Member Functions
void buildNickList ()
void sendIsOn ()
Friends
class KviConsoleWindow
class KviIrcConnection
class KviIrcServerParser
Additional Inherited Members
Public Member Functions inherited from KviNotifyListManager
KviConsoleWindow * console ()
Constructor & Destructor Documentation
KviStupidNotifyListManager::KviStupidNotifyListManager (KviIrcConnection * pConnection) protected
References m_iRestartTimer, m_pNickList, and KviPointerList< T >::setAutoDelete().
KviStupidNotifyListManager::~KviStupidNotifyListManager () protected
References m_iRestartTimer, and m_pNickList.
Member Function Documentation
void KviStupidNotifyListManager::buildNickList () private
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerHashTableIterator< Key, T >::current(), d, g_pRegisteredUserDataBase, KviRegisteredUser::getProperty(), m_pNickList, and KviRegisteredUserDataBase::userDict().
Referenced by start().
bool KviStupidNotifyListManager::handleIsOn (KviIrcMessage * msg) protected virtual
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, KviPointerList< T >::count(), KviIrcConnection::decodeText(), KviUserListView::findEntry(), KviCString::hasData(), kvi_extractToken(), KVI_OPTION_UINT, KVI_OUT_SYSTEMWARNING, KviOption_uintNotifyListCheckTimeInSecs, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), m_iNextNickToCheck, m_iRestartTimer, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pNickList, m_szLastIsOnMsg, KviConsoleWindow::notifyListView(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviWindow::output(), KviCString::ptr(), sendIsOn(), and KviIrcMessage::trailing().
void KviStupidNotifyListManager::sendIsOn () private
References __tr2qs, _OUTPUT_PARANOIC, KviQString::appendFormatted(), KviPointerList< T >::at(), KviIrcConnection::encodeText(), i, KVI_ASSERT, KVI_OUT_SYSTEMMESSAGE, KviLagMeter::lagCheckRegister(), KviIrcConnection::lagMeter(), m_iNextNickToCheck, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pNickList, m_szLastIsOnMsg, KviPointerList< T >::next(), KviWindow::output(), and KviIrcConnection::sendFmtData().
Referenced by handleIsOn(), start(), and timerEvent().
void KviStupidNotifyListManager::start () protected virtual
Reimplemented from KviNotifyListManager.
References __tr2qs, _OUTPUT_VERBOSE, buildNickList(), KviIrcConnection::currentNickName(), KviPointerList< T >::isEmpty(), KVI_OUT_SYSTEMMESSAGE, m_iNextNickToCheck, m_iRestartTimer, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, m_pNickList, KviConsoleWindow::notifyListView(), KviWindow::outputNoFmt(), KviUserListView::partAllButOne(), and sendIsOn().
void KviStupidNotifyListManager::stop () protected virtual
Reimplemented from KviNotifyListManager.
References KviIrcConnection::currentNickName(), KviLagMeter::lagCheckAbort(), KviIrcConnection::lagMeter(), m_iRestartTimer, KviNotifyListManager::m_pConnection, KviNotifyListManager::m_pConsole, KviConsoleWindow::notifyListView(), and KviUserListView::partAllButOne().
void KviStupidNotifyListManager::timerEvent (QTimerEvent * e) protected virtual
References m_iNextNickToCheck, m_iRestartTimer, and sendIsOn().
Friends And Related Function Documentation
friend class KviConsoleWindow friend
friend class KviIrcConnection friend
friend class KviIrcServerParser friend
Member Data Documentation
int KviStupidNotifyListManager::m_iNextNickToCheck protected
Referenced by handleIsOn(), sendIsOn(), start(), and timerEvent().
int KviStupidNotifyListManager::m_iRestartTimer protected
Referenced by handleIsOn(), KviStupidNotifyListManager(), start(), stop(), timerEvent(), and ~KviStupidNotifyListManager().
KviPointerList<QString>* KviStupidNotifyListManager::m_pNickList protected
Referenced by buildNickList(), handleIsOn(), KviStupidNotifyListManager(), sendIsOn(), start(), and ~KviStupidNotifyListManager().
QString KviStupidNotifyListManager::m_szLastIsOnMsg protected
Referenced by handleIsOn(), and sendIsOn().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviNotifyList.h
src/kvirc/kernel/KviNotifyList.cpp