KVIrc: KviRegisteredUsersListView Class Reference
KviRegisteredUsersListView Class Reference
#include <RegisteredUsersDialog.h>
Signals
void rightButtonPressed (QTreeWidgetItem *, QPoint)
Public Member Functions
KviRegisteredUsersListView (QWidget *)
~KviRegisteredUsersListView ()
Protected Member Functions
void mousePressEvent (QMouseEvent *e)
Constructor & Destructor Documentation
KviRegisteredUsersListView::KviRegisteredUsersListView (QWidget * par)
References __tr2qs_ctx().
KviRegisteredUsersListView::~KviRegisteredUsersListView () inline
Member Function Documentation
void KviRegisteredUsersListView::mousePressEvent (QMouseEvent * e) protected
References i, and rightButtonPressed().
void KviRegisteredUsersListView::rightButtonPressed (QTreeWidgetItem * , QPoint) signal
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUsersDialog.h
src/modules/reguser/RegisteredUsersDialog.cpp