KVIrc: KvsObject_textBrowser Class Reference
KvsObject_textBrowser Class Reference
#include <KvsObject_textBrowser.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void anchorClicked (const QUrl &)
Protected Member Functions
bool backward (KviKvsObjectFunctionCall *c)
bool forward (KviKvsObjectFunctionCall *c)
bool home (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool linkClickedEvent (KviKvsObjectFunctionCall *c)
bool reload (KviKvsObjectFunctionCall *c)
bool setSource (KviKvsObjectFunctionCall *c)
Member Function Documentation
void KvsObject_textBrowser::anchorClicked (const QUrl & url) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_textBrowser::backward (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_textBrowser::forward (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_textBrowser::home (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_textBrowser::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_textedit.
References connect(), and SET_OBJECT.
bool KvsObject_textBrowser::linkClickedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_textBrowser::reload (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_textBrowser::setSource (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_textBrowser::widget () [inline]
Reimplemented from KvsObject_textedit.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_textBrowser.h
src/modules/objects/KvsObject_textBrowser.cpp