KVIrc: KviUrl Class Reference
KviUrl Class Reference
#include <KviUrl.h>
Public Member Functions
const QString & host () const
KviUrl ()
KviUrl (const char *szUrl)
KviUrl (const QString &szUrl)
KviUrl (const KviUrl &u)
KviUrl & operator= (const QString &szUrl)
KviUrl & operator= (const KviUrl &u)
const QString & pass () const
const QString & path () const
kvi_u32_t port () const
const QString & protocol () const
const QString & url () const
const QString & user () const
~KviUrl ()
Protected Member Functions
void parse ()
Protected Attributes
QString m_szHost
QString m_szPass
QString m_szPath
QString m_szProtocol
QString m_szUrl
QString m_szUser
kvi_u32_t m_uPort
Constructor & Destructor Documentation
KviUrl::KviUrl ()
KviUrl::KviUrl (const char * szUrl)
References m_szUrl, and parse().
KviUrl::KviUrl (const QString & szUrl)
References m_szUrl, parse(), and szUrl.
KviUrl::KviUrl (const KviUrl & u)
References u.
KviUrl::~KviUrl ()
Member Function Documentation
const QString& KviUrl::host () const inline
Referenced by KviHttpRequest::doConnect(), KviHttpRequest::slotSocketConnected(), KviHttpRequest::slotSocketHostResolved(), and KviHttpRequest::start().
KviUrl & KviUrl::operator= (const QString & szUrl)
References m_szUrl, parse(), and szUrl.
KviUrl & KviUrl::operator= (const KviUrl & u)
References m_szHost, m_szPass, m_szPath, m_szProtocol, m_szUrl, m_szUser, and m_uPort.
void KviUrl::parse () protected
References m_szHost, m_szPass, m_szPath, m_szProtocol, m_szUrl, m_szUser, m_uPort, and url().
Referenced by KviUrl(), and operator=().
const QString& KviUrl::pass () const inline
const QString& KviUrl::path () const inline
Referenced by KviHttpRequest::slotSocketConnected().
kvi_u32_t KviUrl::port () const inline
Referenced by KviHttpRequest::doConnect().
const QString& KviUrl::protocol () const inline
Referenced by KviHttpRequest::start().
const QString& KviUrl::url () const inline
Referenced by HttpFileTransfer::displayPaint(), loadUrlList(), parse(), HttpFileTransfer::transferTerminated(), and urllist_module_event_onUrl().
const QString& KviUrl::user () const inline
Member Data Documentation
QString KviUrl::m_szHost protected
Referenced by operator=(), and parse().
QString KviUrl::m_szPass protected
Referenced by operator=(), and parse().
QString KviUrl::m_szPath protected
Referenced by operator=(), and parse().
QString KviUrl::m_szProtocol protected
Referenced by operator=(), and parse().
QString KviUrl::m_szUrl protected
Referenced by KviUrl(), operator=(), and parse().
QString KviUrl::m_szUser protected
Referenced by operator=(), and parse().
kvi_u32_t KviUrl::m_uPort protected
Referenced by operator=(), and parse().
The documentation for this class was generated from the following files:
src/kvilib/net/KviUrl.h
src/kvilib/net/KviUrl.cpp