KVIrc: OptionsWidget_identityAvatar Class Reference
OptionsWidget_identityAvatar Class Reference
#include <OptionsWidget_identity.h>
Public Member Functions
OptionsWidget_identityAvatar (QWidget *pParent)
~OptionsWidget_identityAvatar ()
Protected Slots
void chooseAvatar ()
Protected Member Functions
virtual void commit ()
Protected Attributes
QLineEdit * m_pAvatarNameEdit
KviPixmapPreview * m_pAvatarPreview
QPushButton * m_pChooseAvatarButton
KviPixmap * m_pLocalAvatar
QCheckBox * m_pUseAvatarCheck
Constructor & Destructor Documentation
OptionsWidget_identityAvatar::OptionsWidget_identityAvatar (QWidget * pParent)
References __tr2qs_ctx(), KviOptionsWidget::addWidgetToLayout(), chooseAvatar(), connect(), KviOptionsWidget::createLayout(), KVI_OPTION_PIXMAP, KVI_OPTION_STRING, KviOption_pixmapMyAvatar, KviOption_stringMyAvatar, KviOptionsWidget::layout(), m_pAvatarNameEdit, m_pAvatarPreview, m_pChooseAvatarButton, m_pLocalAvatar, m_pUseAvatarCheck, KviOptionsWidget::mergeTip(), KviPixmap::pixmap(), KviPixmapPreview::setPixmap(), and KviTalHBox::setSpacing().
OptionsWidget_identityAvatar::~OptionsWidget_identityAvatar ()
References m_pLocalAvatar.
Member Function Documentation
void OptionsWidget_identityAvatar::chooseAvatar () [protected, slot]
References __tr2qs_ctx(), a, AvatarSelectionDialog::avatarName(), KviQString::equalCIN(), AvatarDownloadDialog::errorMessage(), g_pIconManager, KviIconManager::getAvatar(), KviPixmap::load(), AvatarDownloadDialog::localFileName(), KviAvatar::localPath(), m_pAvatarNameEdit, m_pAvatarPreview, m_pLocalAvatar, KviPixmap::path(), KviPixmap::pixmap(), KviAvatar::pixmap(), KviPixmap::set(), KviPixmap::setNull(), KviPixmapPreview::setPixmap(), and KviMessageBox::warning().
Referenced by OptionsWidget_identityAvatar().
void OptionsWidget_identityAvatar::commit (void) [protected, virtual]
Reimplemented from KviOptionsWidget.
References g_pApp, KVI_OPTION_PIXMAP, KVI_OPTION_STRING, KviOption_pixmapMyAvatar, KviOption_stringMyAvatar, m_pAvatarNameEdit, m_pLocalAvatar, m_pUseAvatarCheck, KviPixmap::pixmap(), and KviApplication::setAvatarFromOptions().
Member Data Documentation
QLineEdit* OptionsWidget_identityAvatar::m_pAvatarNameEdit [protected]
Referenced by chooseAvatar(), commit(), and OptionsWidget_identityAvatar().
KviPixmapPreview* OptionsWidget_identityAvatar::m_pAvatarPreview [protected]
Referenced by chooseAvatar(), and OptionsWidget_identityAvatar().
QPushButton* OptionsWidget_identityAvatar::m_pChooseAvatarButton [protected]
Referenced by OptionsWidget_identityAvatar().
KviPixmap* OptionsWidget_identityAvatar::m_pLocalAvatar [protected]
Referenced by chooseAvatar(), commit(), OptionsWidget_identityAvatar(), and ~OptionsWidget_identityAvatar().
QCheckBox* OptionsWidget_identityAvatar::m_pUseAvatarCheck [protected]
Referenced by commit(), and OptionsWidget_identityAvatar().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp