KVIrc: UrlDialogTreeWidget Class Reference
UrlDialogTreeWidget Class Reference
#include <libkviurl.h>
Signals
void contextMenuRequested (QPoint)
void rightButtonPressed (QTreeWidgetItem *, QPoint)
Public Member Functions
UrlDialogTreeWidget (QWidget *)
~UrlDialogTreeWidget ()
Protected Member Functions
void mousePressEvent (QMouseEvent *e)
void paintEvent (QPaintEvent *event)
Constructor & Destructor Documentation
UrlDialogTreeWidget::UrlDialogTreeWidget (QWidget * par)
UrlDialogTreeWidget::~UrlDialogTreeWidget () [inline]
Member Function Documentation
void UrlDialogTreeWidget::contextMenuRequested (QPoint) [signal]
Referenced by mousePressEvent().
void UrlDialogTreeWidget::mousePressEvent (QMouseEvent * e) [protected]
References contextMenuRequested(), i, and rightButtonPressed().
void UrlDialogTreeWidget::paintEvent (QPaintEvent * event) [protected]
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorTreeWindowListBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviMainWindow::mdiManager(), p, KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
void UrlDialogTreeWidget::rightButtonPressed (QTreeWidgetItem * , QPoint) [signal]
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
src/modules/url/libkviurl.h
src/modules/url/libkviurl.cpp