KVIrc: KviTreeWindowListItemDelegate Class Reference
KviTreeWindowListItemDelegate Class Reference
#include <kvi_windowlist_tree.h>
Public Member Functions
KviTreeWindowListItemDelegate (QAbstractItemView *pWidget=0)
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
~KviTreeWindowListItemDelegate ()
Constructor & Destructor Documentation
KviTreeWindowListItemDelegate::KviTreeWindowListItemDelegate (QAbstractItemView * pWidget = 0) [inline]
KviTreeWindowListItemDelegate::~KviTreeWindowListItemDelegate () [inline]
Member Function Documentation
void KviTreeWindowListItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const
References KviWindow::activityMeter(), KviWindow::console(), KviConsole::context(), g_pActivityMeterPixmap, KviIrcContext::id(), KVI_NUM_ICCOLOR_OPTIONS, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_ICCOLOR, KVI_TTBID_HIGHLIGHT, KVI_TTBID_PROGRESS, KVI_WINDOW_TYPE_CHANNEL, KVI_WINDOW_TYPE_CONSOLE, KVI_WINDOW_TYPE_DEADCHANNEL, KVI_WINDOW_TYPE_DEADQUERY, KVI_WINDOW_TYPE_QUERY, KviOption_boolEnableVisualEffects, KviOption_boolUseWindowListActivityMeter, KviOption_boolUseWindowListIcons, KviOption_boolUseWindowListIrcContextIndicator, KviOption_colorTreeWindowListActiveBackground, KviOption_colorTreeWindowListActiveForeground, KviOption_colorTreeWindowListForeground, KviOption_colorTreeWindowListHighlight1Foreground, KviOption_colorTreeWindowListHighlight2Foreground, KviOption_colorTreeWindowListHighlight3Foreground, KviOption_colorTreeWindowListHighlight4Foreground, KviOption_colorTreeWindowListHighlight5Foreground, KviOption_colorTreeWindowListProgress, KviWindowListItem::kviWindow(), KviWindow::myIconPtr(), and KviWindow::type().
QSize KviTreeWindowListItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const
References KVI_OPTION_BOOL, KviOption_boolUseWindowListActivityMeter, KviOption_boolUseWindowListIcons, and KviOption_boolUseWindowListIrcContextIndicator.
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_windowlist_tree.h
src/kvirc/ui/kvi_windowlist_tree.cpp