KVIrc: CustomToolBarPropertiesDialog Class Reference
CustomToolBarPropertiesDialog Class Reference
#include <CustomizeToolBarsDialog.h>
Public Member Functions
CustomToolBarPropertiesDialog (QWidget *p, const QString &szText, const QString &szId=QString(), const QString &szLabel=QString(), const QString &szIconId=QString())
const QString & iconId ()
const QString & id ()
const QString & label ()
~CustomToolBarPropertiesDialog ()
Protected Slots
void advancedClicked ()
void iconButtonClicked ()
void labelTextChanged (const QString &s)
void okClicked ()
Protected Member Functions
void iconSelected (const QString &szIconId)
Protected Attributes
QWidget * m_pAdvanced
QPushButton * m_pAdvancedButton
QPushButton * m_pIconButton
QLineEdit * m_pIconEdit
QLineEdit * m_pIdEdit
QLineEdit * m_pLabelEdit
QString m_szIconId
QString m_szId
QString m_szLabel
QString m_szOriginalId
Constructor & Destructor Documentation
CustomToolBarPropertiesDialog::CustomToolBarPropertiesDialog (QWidget * p, const QString & szText, const QString & szId = QString(), const QString & szLabel = QString(), const QString & szIconId = QString())
References __tr2qs_ctx(), advancedClicked(), connect(), g, g_pIconManager, KviIconManager::getSmallIcon(), iconButtonClicked(), iconSelected(), l, labelTextChanged(), m_pAdvanced, m_pAdvancedButton, m_pIconButton, m_pIconEdit, m_pIdEdit, m_pLabelEdit, m_szId, m_szLabel, m_szOriginalId, okClicked(), and KviIconManager::ToolBar.
CustomToolBarPropertiesDialog::~CustomToolBarPropertiesDialog ()
Member Function Documentation
void CustomToolBarPropertiesDialog::advancedClicked () [protected, slot]
References __tr2qs_ctx(), m_pAdvanced, and m_pAdvancedButton.
Referenced by CustomToolBarPropertiesDialog().
void CustomToolBarPropertiesDialog::iconButtonClicked () [protected, slot]
References __tr2qs_ctx(), iconSelected(), s, and KviImageDialog::selectedImage().
Referenced by CustomToolBarPropertiesDialog().
const QString& CustomToolBarPropertiesDialog::iconId () [inline]
References m_szIconId.
Referenced by CustomizeToolBarsDialog::newToolBar(), and CustomizeToolBarsDialog::renameToolBar().
void CustomToolBarPropertiesDialog::iconSelected (const QString & szIconId) [protected]
References g_pIconManager, KviIconManager::getImage(), m_pIconButton, m_pIconEdit, and m_szIconId.
Referenced by CustomToolBarPropertiesDialog(), and iconButtonClicked().
const QString& CustomToolBarPropertiesDialog::id () [inline]
References m_szId.
Referenced by CustomizeToolBarsDialog::newToolBar(), and CustomizeToolBarsDialog::renameToolBar().
const QString& CustomToolBarPropertiesDialog::label () [inline]
References m_szLabel.
Referenced by CustomizeToolBarsDialog::newToolBar(), and CustomizeToolBarsDialog::renameToolBar().
void CustomToolBarPropertiesDialog::labelTextChanged (const QString & s) [protected, slot]
References KviCustomToolBarManager::idForNewToolBar(), KviCustomToolBarManager::instance(), m_pIdEdit, and m_szOriginalId.
Referenced by CustomToolBarPropertiesDialog().
void CustomToolBarPropertiesDialog::okClicked () [protected, slot]
References __tr2qs_ctx(), KviQString::find(), KviCustomToolBarManager::idForNewToolBar(), KviMessageBox::information(), KviCustomToolBarManager::instance(), m_pIdEdit, m_pLabelEdit, m_szId, m_szLabel, and m_szOriginalId.
Referenced by CustomToolBarPropertiesDialog().
Member Data Documentation
QWidget* CustomToolBarPropertiesDialog::m_pAdvanced [protected]
Referenced by advancedClicked(), and CustomToolBarPropertiesDialog().
QPushButton* CustomToolBarPropertiesDialog::m_pAdvancedButton [protected]
Referenced by advancedClicked(), and CustomToolBarPropertiesDialog().
QPushButton* CustomToolBarPropertiesDialog::m_pIconButton [protected]
Referenced by CustomToolBarPropertiesDialog(), and iconSelected().
QLineEdit* CustomToolBarPropertiesDialog::m_pIconEdit [protected]
Referenced by CustomToolBarPropertiesDialog(), and iconSelected().
QLineEdit* CustomToolBarPropertiesDialog::m_pIdEdit [protected]
Referenced by CustomToolBarPropertiesDialog(), labelTextChanged(), and okClicked().
QLineEdit* CustomToolBarPropertiesDialog::m_pLabelEdit [protected]
Referenced by CustomToolBarPropertiesDialog(), and okClicked().
QString CustomToolBarPropertiesDialog::m_szIconId [protected]
Referenced by iconId(), and iconSelected().
QString CustomToolBarPropertiesDialog::m_szId [protected]
Referenced by CustomToolBarPropertiesDialog(), id(), and okClicked().
QString CustomToolBarPropertiesDialog::m_szLabel [protected]
Referenced by CustomToolBarPropertiesDialog(), label(), and okClicked().
QString CustomToolBarPropertiesDialog::m_szOriginalId [protected]
Referenced by CustomToolBarPropertiesDialog(), labelTextChanged(), and okClicked().
The documentation for this class was generated from the following files:
src/modules/toolbareditor/CustomizeToolBarsDialog.h
src/modules/toolbareditor/CustomizeToolBarsDialog.cpp