KVIrc: KviPackageWriter Class Reference
KviPackageWriter Class Reference
This class is used to create KVIrc package files.
#include <KviPackageWriter.h>
Public Types
enum AddFileFlags { NoCompression = 1, FollowSymLinks = 2 }
enum PackFlags { NoProgressDialog = 1 }
Public Member Functions
bool addDirectory (const QString &szLocalDirectoryName, const QString &szTargetDirectoryPrefix, kvi_u32_t uAddFileFlags=0)
Adds a directory to the package.
bool addFile (const QString &szLocalFileName, const QString &szTargetFileName, kvi_u32_t uAddFileFlags=0)
Adds a file to the package.
void addInfoField (const QString &szName, const QString &szValue)
Adds an info field as a name=value pair.
void addInfoField (const QString &szName, QByteArray *pArray)
Adds an info field as a name=value pair.
KviPackageWriter ()
Creates the package writer object.
bool pack (const QString &szFileName, kvi_u32_t uPackFlags=0)
Attempts to pack everything and store it as the specified file.
virtual ~KviPackageWriter ()
Destroys the object.
Public Member Functions inherited from KviPackageIOEngine
KviPointerHashTable< QString,
QByteArray > * binaryInfoFields ()
Returns the binary info fields.
KviPackageIOEngine ()
Creates the I/O engine object.
const QString & lastError ()
Returns the last error.
KviPointerHashTable< QString,
QString > * stringInfoFields ()
Returns the string info fields.
virtual ~KviPackageIOEngine ()
Destroys the object.
Private Member Functions
bool addFileInternal (const QFileInfo *fi, const QString &szLocalFileName, const QString &szTargetFileName, kvi_u32_t uAddFileFlags=0)
Adds a file to the package.
bool packFile (KviFile *pFile, KviPackageWriterDataField *pDataField)
Attempts to pack everything and store it as the specified file.
bool packInternal (const QString &szFileName, kvi_u32_t uPackFlags=0)
Attempts to pack everything and store it as the specified file.
Private Attributes
KviPackageWriterPrivate * m_p
Additional Inherited Members
Protected Member Functions inherited from KviPackageIOEngine
void hideProgressDialog ()
Hides the progress dialog.
bool readError ()
Sets the last error as read error.
void setLastError (const QString &szLastError)
Sets the last error.
void showProgressDialog (const QString &szCaption, int iTotalSteps)
Shows the progress dialog.
bool updateProgress (int iProgress, const QString &szLabel)
Updates the progress dialog.
bool writeError ()
Sets the last error as write error.
Detailed Description
This class is used to create KVIrc package files.
You simply instantiate it, add some info fields, add some files and then call pack().
Member Enumeration Documentation
enum KviPackageWriter::AddFileFlags
Enumerator
NoCompression
If you don't want to compress the file
FollowSymLinks
If you want to follow the symlinks
enum KviPackageWriter::PackFlags
Enumerator
NoProgressDialog
If you want to avoid the progress dialog
Constructor & Destructor Documentation
KviPackageWriter::KviPackageWriter ()
Creates the package writer object.
Returns
KviPackageWriter
References m_p, KviPackageWriterPrivate::pDataFields, and KviPointerList< T >::setAutoDelete().
KviPackageWriter::~KviPackageWriter () virtual
Destroys the object.
References m_p, and KviPackageWriterPrivate::pDataFields.
Member Function Documentation
bool KviPackageWriter::addDirectory (const QString & szLocalDirectoryName, const QString & szTargetDirectoryPrefix, kvi_u32_t uAddFileFlags = 0)
Adds a directory to the package.
Parameters
szLocalDirectoryName The source directory
szTargetDirectoryPrefix The destination directory
uAddFileFlags The flags of the directory
Returns
bool
References addFileInternal(), d, KviQString::ensureLastCharIs(), KviQString::equalCS(), FollowSymLinks, j, and KVI_PATH_SEPARATOR_CHAR.
Referenced by AddonFunctions::pack(), and ThemeFunctions::packageThemes().
bool KviPackageWriter::addFile (const QString & szLocalFileName, const QString & szTargetFileName, kvi_u32_t uAddFileFlags = 0)
Adds a file to the package.
The file must be specified as absolute local path and as target path relative to the KVIrc local directory. This is a shortcut to addFileInternal() ... more ?
Parameters
szLocalFileName The source file
szTargetFileName The destination file
uAddFileFlags The flags of the file
Returns
bool
References addFileInternal().
Referenced by AddonFunctions::pack().
bool KviPackageWriter::addFileInternal (const QFileInfo * fi, const QString & szLocalFileName, const QString & szTargetFileName, kvi_u32_t uAddFileFlags = 0) private
Adds a file to the package.
This is the real addFile() function
Parameters
fi THe information of the file
szLocalFileName The source file
szTargetFileName The destination file
uAddFileFlags The flags of the file
Returns
bool
References KviPointerList< T >::append(), f, FollowSymLinks, KVI_PACKAGE_DATAFIELD_TYPE_FILE, KviPackageWriterDataField::m_bFileAllowCompression, m_p, KviPackageWriterDataField::m_szFileLocalName, KviPackageWriterDataField::m_szFileTargetName, KviPackageWriterDataField::m_uType, NoCompression, and KviPackageWriterPrivate::pDataFields.
Referenced by addDirectory(), and addFile().
void KviPackageWriter::addInfoField (const QString & szName, const QString & szValue)
Adds an info field as a name=value pair.
Parameters
szName The name of the info field
szValue The value of the info field
Returns
void
References KviPointerHashTable< Key, T >::replace(), and KviPackageIOEngine::stringInfoFields().
Referenced by AddonFunctions::pack(), and ThemeFunctions::packageThemes().
void KviPackageWriter::addInfoField (const QString & szName, QByteArray * pArray)
Adds an info field as a name=value pair.
Parameters
szName The name of the info field
pArray The value of the info field
Returns
void
References KviPackageIOEngine::binaryInfoFields(), and KviPointerHashTable< Key, T >::replace().
bool KviPackageWriter::pack (const QString & szFileName, kvi_u32_t uPackFlags = 0)
Attempts to pack everything and store it as the specified file.
This is a shortcut to packInternal() hiding the progress dialog There is no mandatory extension but you should use KVI_FILEEXTENSION_THEMEPACKAGE for themes and KVI_FILEEXTENSION_ADDONPACKAGE for addons. See kvi_fileextension.h
Parameters
szFileName The file name of the package
uPackFlags The flags of the package
Returns
bool
References __tr2qs, KviPackageIOEngine::hideProgressDialog(), KviPackageWriterPrivate::iCurrentProgress, m_p, NoProgressDialog, packInternal(), KviPackageIOEngine::showProgressDialog(), and KviPackageIOEngine::updateProgress().
Referenced by AddonFunctions::pack(), and ThemeFunctions::packageThemes().
bool KviPackageWriter::packFile (KviFile * pFile, KviPackageWriterDataField * pDataField) private
Attempts to pack everything and store it as the specified file.
This is the real pack() function
Parameters
pFile The source file package
pDataField The data field for the package
Returns
bool
References __tr2qs, BUFFER_SIZE, KviPackageWriterPrivate::iCurrentProgress, kvi_file_offset_t, KVI_PACKAGE_DATAFIELD_FLAG_FILE_DEFLATE, KviPackageWriterDataField::m_bFileAllowCompression, m_p, KviPackageWriterDataField::m_szFileLocalName, KviPackageWriterDataField::m_szFileTargetName, KviPackageWriterDataField::m_uWrittenFieldLength, KviPackageIOEngine::readError(), KviFile::save(), KviPackageIOEngine::setLastError(), KviPackageIOEngine::updateProgress(), and KviPackageIOEngine::writeError().
Referenced by packInternal().
bool KviPackageWriter::packInternal (const QString & szFileName, kvi_u32_t uPackFlags = 0) private
Attempts to pack everything and store it as the specified file.
This is a shortcut to packFile() performing some checks
Parameters
szFileName The file name of the package
uPackFlags The flags of the package
Returns
bool
References __tr2qs, KviPackageIOEngine::binaryInfoFields(), KviPointerHashTable< Key, T >::count(), KviPointerList< T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), f, KviPointerList< T >::first(), KviPackageWriterPrivate::iCurrentProgress, kvi_file_offset_t, KVI_PACKAGE_DATAFIELD_TYPE_FILE, KVI_PACKAGE_INFOFIELD_TYPE_BINARYBUFFER, KVI_PACKAGE_INFOFIELD_TYPE_STRING, m_p, KviPointerList< T >::next(), packFile(), KviPackageWriterPrivate::pDataFields, s, KviFile::save(), KviPackageIOEngine::setLastError(), KviPackageIOEngine::stringInfoFields(), KviPackageIOEngine::updateProgress(), and KviPackageIOEngine::writeError().
Referenced by pack().
Member Data Documentation
KviPackageWriterPrivate* KviPackageWriter::m_p private
Hidden private data
Referenced by addFileInternal(), KviPackageWriter(), pack(), packFile(), packInternal(), and ~KviPackageWriter().
The documentation for this class was generated from the following files:
src/kvilib/file/KviPackageWriter.h
src/kvilib/file/KviPackageWriter.cpp