KVIrc: KviCachedPixmap Class Reference
KviCachedPixmap Class Reference
Class for holding a cached pixmap.
#include <KviIconManager.h>
Public Member Functions
KviCachedPixmap (QPixmap *pPix, const QString &szPath)
Constructs the KviCachedPixmap object.
kvi_time_t lastAccessTime ()
Returns the time the image was last accessed.
const QString & path ()
Returns the path of the image.
QPixmap * pixmap ()
Returns the image.
unsigned int size ()
Returns the size of the image.
void updateLastAccessTime ()
Updates the time the image was last accessed.
~KviCachedPixmap ()
Destroys the KviCachedPixmap object.
Private Attributes
QPixmap * m_pPixmap
QString m_szPath
kvi_time_t m_tLastAccess
unsigned int m_uSize
Detailed Description
Class for holding a cached pixmap.
Constructor & Destructor Documentation
KviCachedPixmap::KviCachedPixmap (QPixmap * pPix, const QString & szPath)
Constructs the KviCachedPixmap object.
Parameters
pPix The image object
szPath The path of the image
Warning
The pixmap MUST be allocated with new QPixmap(). This class takes the ownership
Returns
KviCachedPixmap
References kvi_unixTime, m_pPixmap, m_szPath, m_tLastAccess, and m_uSize.
KviCachedPixmap::~KviCachedPixmap ()
Destroys the KviCachedPixmap object.
References m_pPixmap.
Member Function Documentation
kvi_time_t KviCachedPixmap::lastAccessTime () inline
Returns the time the image was last accessed.
Returns
kvi_time_t
const QString& KviCachedPixmap::path () inline
Returns the path of the image.
Returns
const QString &
Referenced by KviIconManager::getImage(), and KviTheme::save().
QPixmap* KviCachedPixmap::pixmap () inline
Returns the image.
Returns
QPixmap *
References m_pPixmap.
Referenced by KviIconManager::getBigIcon(), KviIconManager::getImage(), and KviIconManager::getPixmap().
unsigned int KviCachedPixmap::size () inline
Returns the size of the image.
Returns
unsigned int
Referenced by KviIconManager::addToCache().
void KviCachedPixmap::updateLastAccessTime ()
Updates the time the image was last accessed.
Returns
void
References kvi_unixTime, and m_tLastAccess.
Referenced by KviIconManager::getPixmapWithCache(), and KviIconManager::getPixmapWithCacheScaleOnLoad().
Member Data Documentation
QPixmap* KviCachedPixmap::m_pPixmap private
Referenced by KviCachedPixmap(), and ~KviCachedPixmap().
QString KviCachedPixmap::m_szPath private
Referenced by KviCachedPixmap().
kvi_time_t KviCachedPixmap::m_tLastAccess private
Referenced by KviCachedPixmap(), and updateLastAccessTime().
unsigned int KviCachedPixmap::m_uSize private
Referenced by KviCachedPixmap().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIconManager.h
src/kvirc/kernel/KviIconManager.cpp