KVIrc: KviKvsTreeNodeArrayElement Class Reference
KviKvsTreeNodeArrayElement Class Reference
Treenode array element class.
#include <KviKvsTreeNodeArrayElement.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Array Element Evaluation.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the array element in read-only mode.
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the array element in read-only mode in the object scope.
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
Evaluates the array element in read-write mode.
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
Evaluates the array element in read-write mode in the object scope.
KviKvsTreeNodeArrayElement (const QChar *pLocation, KviKvsTreeNodeData *pSource, KviKvsTreeNodeExpression *pIndex)
Constructs the treenode array element object.
~KviKvsTreeNodeArrayElement ()
Destroys the treenode array element object.
Public Member Functions inherited from KviKvsTreeNodeArrayOrHashElement
virtual bool canEvaluateToObjectReference ()
virtual bool isReadOnly ()
KviKvsTreeNodeArrayOrHashElement (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeArrayOrHashElement ()
Public Member Functions inherited from KviKvsTreeNodeIndirectData
virtual bool canEvaluateInObjectScope ()
KviKvsTreeNodeIndirectData (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeIndirectData ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool isFunctionCall ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Member Functions
bool evaluateIndex (KviKvsRunTimeContext *c, kvs_int_t &iVal)
Evaluates the index of the array.
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes
KviKvsTreeNodeExpression * m_pIndex
Protected Attributes inherited from KviKvsTreeNodeIndirectData
KviKvsTreeNodeData * m_pSource
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Detailed Description
Treenode array element class.
Constructor & Destructor Documentation
KviKvsTreeNodeArrayElement::KviKvsTreeNodeArrayElement (const QChar * pLocation, KviKvsTreeNodeData * pSource, KviKvsTreeNodeExpression * pIndex)
Constructs the treenode array element object.
Parameters
pLocation The location char of the instruction
pSource The source data
pIndex The index of the expression
Returns
KviKvsTreeNodeArrayElement
References m_pIndex, and KviKvsTreeNode::setParent().
KviKvsTreeNodeArrayElement::~KviKvsTreeNodeArrayElement ()
Destroys the treenode array element object.
References m_pIndex.
Member Function Documentation
void KviKvsTreeNodeArrayElement::contextDescription (QString & szBuffer) virtual
Sets the buffer as Array Element Evaluation.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeArrayElement::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeData::dump(), KviKvsTreeNodeExpression::dump(), m_pIndex, and KviKvsTreeNodeIndirectData::m_pSource.
bool KviKvsTreeNodeArrayElement::evaluateIndex (KviKvsRunTimeContext * c, kvs_int_t & iVal) protected
Evaluates the index of the array.
Parameters
c The context where the array is bound to
iVal The index of the array
Returns
bool
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), and m_pIndex.
Referenced by evaluateReadOnlyInObjectScope(), and evaluateReadWriteInObjectScope().
bool KviKvsTreeNodeArrayElement::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Evaluates the array element in read-only mode.
Parameters
c The context where the alias is bound to
pBuffer The data buffer
Returns
bool
Reimplemented from KviKvsTreeNodeData.
References evaluateReadOnlyInObjectScope().
bool KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Evaluates the array element in read-only mode in the object scope.
Parameters
o The source object to evaluate
c The context where the array is bound to
pBuffer The data buffer
Returns
bool
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsArray::at(), KviKvsVariant::copyFrom(), evaluateIndex(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsVariant::getTypeName(), KviKvsVariant::isArray(), KviKvsVariant::isNothing(), KviKvsTreeNodeIndirectData::m_pSource, KviKvsVariant::setNothing(), v, and KviKvsRunTimeContext::warning().
Referenced by evaluateReadOnly().
KviKvsRWEvaluationResult * KviKvsTreeNodeArrayElement::evaluateReadWrite (KviKvsRunTimeContext * c) virtual
Evaluates the array element in read-write mode.
Parameters
c The context where the alias is bound to
Returns
KviKvsRWEvaluationResult *
Reimplemented from KviKvsTreeNodeData.
References evaluateReadWriteInObjectScope().
KviKvsRWEvaluationResult * KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) virtual
Evaluates the array element in read-write mode in the object scope.
Parameters
o The source object to evaluate
c The context where the array is bound to
Returns
KviKvsRWEvaluationResult *
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsVariant::array(), evaluateIndex(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), KviKvsArray::getAt(), KviKvsVariant::getTypeName(), KviKvsVariant::isArray(), KviKvsVariant::isNothing(), KviKvsTreeNodeIndirectData::m_pSource, KviKvsRWEvaluationResult::result(), KviKvsVariant::setArray(), and KviKvsRunTimeContext::warning().
Referenced by evaluateReadWrite().
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeArrayElement::m_pIndex protected
Referenced by dump(), evaluateIndex(), KviKvsTreeNodeArrayElement(), and ~KviKvsTreeNodeArrayElement().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeArrayElement.h
src/kvirc/kvs/tree/KviKvsTreeNodeArrayElement.cpp