KVIrc: OptionsWidget_connectionSocket Class Reference
OptionsWidget_connectionSocket Class Reference
#include <OptionsWidget_connection.h>
Public Member Functions
OptionsWidget_connectionSocket (QWidget *parent)
~OptionsWidget_connectionSocket ()
Constructor & Destructor Documentation
OptionsWidget_connectionSocket::OptionsWidget_connectionSocket (QWidget * parent)
COMPILE_IPV6_SUPPORT
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolBindIrcIPv4ConnectionsToSpecifiedAddress, KviOption_boolBindIrcIPv6ConnectionsToSpecifiedAddress, KviOption_boolLimitOutgoingTraffic, KviOption_boolPickRandomIpAddressForRoundRobinServers, KviOption_stringIPv4ConnectionBindAddress, KviOption_stringIPv6ConnectionBindAddress, KviOption_uintIrcSocketTimeout, KviOption_uintOutgoingTrafficLimitUSeconds, KviOption_uintSocketQueueFlushTimeout, KviOptionsWidget::mergeTip(), s, KviUIntSelector::setSuffix(), and u.
OptionsWidget_connectionSocket::~OptionsWidget_connectionSocket ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_connection.h
src/modules/options/OptionsWidget_connection.cpp