KVIrc: PackThemeDataWidget Class Reference
PackThemeDataWidget Class Reference
#include <PackThemeDialog.h>
Public Member Functions
PackThemeDataWidget (PackThemeDialog *pParent)
void parseThemes (KviPointerList< KviThemeInfo > *pThemeInfoList)
~PackThemeDataWidget ()
Constructor & Destructor Documentation
PackThemeDataWidget::PackThemeDataWidget (PackThemeDialog * pParent)
References __tr2qs_ctx().
PackThemeDataWidget::~PackThemeDataWidget ()
Member Function Documentation
void PackThemeDataWidget::parseThemes (KviPointerList< KviThemeInfo > * pThemeInfoList)
References __tr2qs_ctx(), KviThemeInfo::application(), KviThemeInfo::author(), KviPointerList< T >::count(), KviThemeInfo::date(), KviThemeInfo::description(), KviQString::ensureLastCharIs(), KviPointerList< T >::first(), ThemeFunctions::getThemeHtmlDescription(), KVI_FILEEXTENSION_THEMEPACKAGE, KVI_PATH_SEPARATOR_CHAR, KviThemeInfo::name(), KviPointerList< T >::next(), KviThemeInfo::smallScreenshot(), KviThemeInfo::smallScreenshotPath(), KviThemeInfo::subdirectory(), KviThemeInfo::themeEngineVersion(), and KviThemeInfo::version().
Referenced by PackThemeDialog::PackThemeDialog().
The documentation for this class was generated from the following files:
src/modules/theme/PackThemeDialog.h
src/modules/theme/PackThemeDialog.cpp