KVIrc: KviActionManager Class Reference
KviActionManager Class Reference
#include <KviActionManager.h>
Signals
void beginCustomizeToolBars ()
void currentToolBarChanged ()
void endCustomizeToolBars ()
void removeActionsHintRequest ()
Public Member Functions
KviPointerHashTable< QString,
KviAction > * actions ()
KviPointerHashTable< QString,
KviActionCategory > * categories ()
KviActionCategory * category (const QString &szName)
bool coreActionExists (const QString &szName)
void emitRemoveActionsHintRequest ()
KviAction * getAction (const QString &szName)
void killAllKvsUserActions ()
KviActionManager ()
void listActionsByCategory (const QString &szCatName, KviPointerList< KviAction > *pBuffer)
void load (const QString &szFileName)
QString nameForAutomaticAction (const QString &szTemplate)
bool registerAction (KviAction *a)
void save (const QString &szFileName)
bool unregisterAction (const QString &szName)
~KviActionManager ()
Static Public Member Functions
static KviActionCategory * categoryChannel ()
static KviActionCategory * categoryGeneric ()
static KviActionCategory * categoryGUI ()
static KviActionCategory * categoryIrc ()
static KviActionCategory * categoryScripting ()
static KviActionCategory * categorySettings ()
static KviActionCategory * categoryTools ()
static KviCustomToolBar * currentToolBar ()
static bool customizingToolBars ()
static void done ()
static void init ()
static KviActionManager * instance ()
static void loadAllAvailableActions ()
Protected Slots
void actionDestroyed ()
Protected Member Functions
void customizeToolBarsDialogCreated ()
void customizeToolBarsDialogDestroyed ()
void delayedRegisterAccelerators ()
KviAction * findAction (const QString &szName)
void setCurrentToolBar (KviCustomToolBar *t)
void tryFindCurrentToolBar ()
Protected Attributes
bool m_bCoreActionsRegistered
KviPointerHashTable< QString,
KviAction > * m_pActions
KviPointerHashTable< QString,
KviActionCategory > * m_pCategories
Static Protected Attributes
static bool m_bCustomizingToolBars = false
static KviActionCategory * m_pCategoryChannel = nullptr
static KviActionCategory * m_pCategoryGeneric = nullptr
static KviActionCategory * m_pCategoryGUI = nullptr
static KviActionCategory * m_pCategoryIrc = nullptr
static KviActionCategory * m_pCategoryScripting = nullptr
static KviActionCategory * m_pCategorySettings = nullptr
static KviActionCategory * m_pCategoryTools = nullptr
static KviCustomToolBar * m_pCurrentToolBar = nullptr
static KviActionManager * m_pInstance = nullptr
Friends
class CustomizeToolBarsDialog
class KviActionDrawer
class KviCustomToolBar
class KviMainWindow
Constructor & Destructor Documentation
KviActionManager::KviActionManager ()
References __tr2qs, CATEGORY, m_bCoreActionsRegistered, m_bCustomizingToolBars, m_pActions, m_pCategories, m_pCategoryChannel, m_pCategoryGeneric, m_pCategoryGUI, m_pCategoryIrc, m_pCategoryScripting, m_pCategorySettings, m_pCategoryTools, m_pCurrentToolBar, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviActionManager::~KviActionManager ()
References a, actionDestroyed(), KviPointerHashTableIterator< Key, T >::current(), m_pActions, and m_pCategories.
Member Function Documentation
void KviActionManager::actionDestroyed () protected slot
References a, m_pActions, KviAction::name(), and KviPointerHashTable< Key, T >::remove().
Referenced by registerAction(), unregisterAction(), and ~KviActionManager().
KviPointerHashTable<QString, KviAction>* KviActionManager::actions () inline
Referenced by KviActionDrawer::fill().
void KviActionManager::beginCustomizeToolBars () signal
Referenced by customizeToolBarsDialogCreated().
KviPointerHashTable<QString, KviActionCategory>* KviActionManager::categories () inline
KviActionCategory * KviActionManager::category (const QString & szName)
References c, KviPointerHashTable< Key, T >::find(), m_pCategories, and m_pCategoryGeneric.
Referenced by KviKvsUserAction::KviKvsUserAction(), listActionsByCategory(), and KviKvsUserAction::load().
static KviActionCategory* KviActionManager::categoryChannel () inline static
static KviActionCategory* KviActionManager::categoryGeneric () inline static
Referenced by ActionEditor::ActionEditor(), KviActionDrawer::fill(), ActionEditor::newAction(), and register_core_actions().
static KviActionCategory* KviActionManager::categoryGUI () inline static
static KviActionCategory* KviActionManager::categoryIrc () inline static
Referenced by KviActionDrawer::fill(), and register_core_actions().
static KviActionCategory* KviActionManager::categoryScripting () inline static
Referenced by register_core_actions().
static KviActionCategory* KviActionManager::categorySettings () inline static
Referenced by register_core_actions().
static KviActionCategory* KviActionManager::categoryTools () inline static
bool KviActionManager::coreActionExists (const QString & szName)
References a, KviPointerHashTable< Key, T >::find(), KviAction::isKviUserActionNeverOverrideThis(), and m_pActions.
static KviCustomToolBar* KviActionManager::currentToolBar () inline static
Referenced by CustomizeToolBarsDialog::deleteToolBar(), CustomizeToolBarsDialog::exportToolBar(), KviCustomToolBar::paintEvent(), CustomizeToolBarsDialog::renameToolBar(), and KviCustomToolBar::~KviCustomToolBar().
void KviActionManager::currentToolBarChanged () signal
Referenced by setCurrentToolBar().
void KviActionManager::customizeToolBarsDialogCreated () protected
References beginCustomizeToolBars(), KviCustomToolBarManager::firstExistingToolBar(), KviCustomToolBarManager::instance(), m_bCustomizingToolBars, and m_pCurrentToolBar.
Referenced by CustomizeToolBarsDialog::CustomizeToolBarsDialog().
void KviActionManager::customizeToolBarsDialogDestroyed () protected
References endCustomizeToolBars(), g_pApp, m_bCustomizingToolBars, m_pCurrentToolBar, and KviApplication::saveToolBars().
Referenced by CustomizeToolBarsDialog::~CustomizeToolBarsDialog().
static bool KviActionManager::customizingToolBars () inline static
Referenced by KviCustomToolBar::childEvent(), KviCustomToolBar::dragEnterEvent(), KviCustomToolBar::eventFilter(), KviCustomToolBar::KviCustomToolBar(), KviCustomToolBar::paintEvent(), and KviCustomToolBar::~KviCustomToolBar().
void KviActionManager::delayedRegisterAccelerators () protected
References a, KviPointerHashTableIterator< Key, T >::current(), and m_pActions.
Referenced by KviMainWindow::createNewConsole().
void KviActionManager::done () static
References m_pInstance.
Referenced by KviApplication::~KviApplication().
void KviActionManager::emitRemoveActionsHintRequest ()
References removeActionsHintRequest().
Referenced by KviCustomToolBar::eventFilter().
void KviActionManager::endCustomizeToolBars () signal
Referenced by customizeToolBarsDialogDestroyed().
KviAction* KviActionManager::findAction (const QString & szName) inline protected
KviAction * KviActionManager::getAction (const QString & szName)
References a, KviPointerHashTable< Key, T >::find(), g_pModuleManager, KviModuleManager::getModule(), m_bCoreActionsRegistered, m_pActions, register_core_actions(), and s.
Referenced by action_kvs_cmd_create(), action_kvs_cmd_destroy(), action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_trigger(), action_kvs_fnc_isEnabled(), KviCustomToolBarDescriptor::addAction(), KviCustomToolBar::dragEnterEvent(), KviCustomToolBar::eventFilter(), CustomizeToolBarsDialog::exportToolBar(), KviCustomToolBarDescriptor::fillToolBar(), KviActionDrawerPageListWidget::mousePressEvent(), KviIrcToolsAction::popupAboutToShow(), and KviIrcOperationsAction::popupAboutToShow().
void KviActionManager::init () static
References KviActionManager(), and m_pInstance.
Referenced by KviApplication::setup().
static KviActionManager* KviActionManager::instance () inline static
Referenced by action_kvs_cmd_create(), action_kvs_cmd_destroy(), action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_list(), action_kvs_cmd_trigger(), action_kvs_fnc_exists(), action_kvs_fnc_isEnabled(), ActionEditor::ActionEditor(), KviCustomToolBarDescriptor::addAction(), SingleActionEditor::commit(), ActionEditor::commit(), KviMainWindow::createNewConsole(), CustomizeToolBarsDialog::currentToolBarChanged(), CustomizeToolBarsDialog::CustomizeToolBarsDialog(), KviCustomToolBar::dragEnterEvent(), KviCustomToolBar::eventFilter(), CustomizeToolBarsDialog::exportToolBar(), KviActionDrawer::fill(), KviCustomToolBarDescriptor::fillToolBar(), KviCustomToolBar::KviCustomToolBar(), KviKvsUserAction::KviKvsUserAction(), KviKvsUserAction::load(), loadAllAvailableActions(), KviActionDrawerPageListWidget::mousePressEvent(), CustomizeToolBarsDialog::newToolBar(), KviIrcToolsAction::popupAboutToShow(), KviIrcOperationsAction::popupAboutToShow(), KviDefaultScriptManager::restoreInternal(), KviApplication::saveActions(), KviApplication::setup(), SingleActionEditor::SingleActionEditor(), TrashcanLabel::TrashcanLabel(), KviMenuBar::updateActionsToolsPopup(), KviMenuBar::updateToolsPopup(), CustomizeToolBarsDialog::~CustomizeToolBarsDialog(), and KviCustomToolBar::~KviCustomToolBar().
void KviActionManager::killAllKvsUserActions ()
References a, KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerHashTableIterator< Key, T >::current(), m_pActions, and KviPointerList< T >::setAutoDelete().
Referenced by ActionEditor::commit(), and KviDefaultScriptManager::restoreInternal().
void KviActionManager::listActionsByCategory (const QString & szCatName, KviPointerList< KviAction > * pBuffer)
References a, KviPointerList< T >::append(), category(), KviPointerList< T >::clear(), KviPointerHashTableIterator< Key, T >::current(), loadAllAvailableActions(), m_pActions, and KviPointerList< T >::setAutoDelete().
Referenced by KviMenuBar::updateActionsToolsPopup(), and KviMenuBar::updateToolsPopup().
void KviActionManager::load (const QString & szFileName)
References a, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviKvsUserAction::load(), KviConfigurationFile::Read, registerAction(), and KviConfigurationFile::setGroup().
Referenced by KviApplication::setup().
void KviActionManager::loadAllAvailableActions () static
References g_pModuleManager, instance(), KviModuleManager::loadModulesByCaps(), m_bCoreActionsRegistered, and register_core_actions().
Referenced by KviActionDrawer::fill(), and listActionsByCategory().
QString KviActionManager::nameForAutomaticAction (const QString & szTemplate)
References KviPointerHashTable< Key, T >::find(), i, and m_pActions.
bool KviActionManager::registerAction (KviAction * a)
References a, actionDestroyed(), connect(), KviPointerHashTable< Key, T >::find(), g_pMainWindow, KviPointerHashTable< Key, T >::insert(), m_pActions, KviAction::name(), and KviAction::registerAccelerator().
Referenced by action_kvs_cmd_create(), ActionEditor::commit(), load(), and register_core_actions().
void KviActionManager::removeActionsHintRequest () signal
Referenced by emitRemoveActionsHintRequest().
void KviActionManager::save (const QString & szFileName)
References a, KviConfigurationFile::clear(), KviPointerHashTableIterator< Key, T >::current(), m_pActions, KviConfigurationFile::setGroup(), and KviConfigurationFile::Write.
Referenced by KviApplication::saveActions().
void KviActionManager::setCurrentToolBar (KviCustomToolBar * t) protected
References currentToolBarChanged(), KviCustomToolBarManager::firstExistingToolBar(), KviCustomToolBarManager::instance(), m_bCustomizingToolBars, m_pCurrentToolBar, and t().
Referenced by KviCustomToolBar::dragEnterEvent(), KviCustomToolBar::eventFilter(), CustomizeToolBarsDialog::newToolBar(), and KviCustomToolBar::~KviCustomToolBar().
void KviActionManager::tryFindCurrentToolBar () protected
bool KviActionManager::unregisterAction (const QString & szName)
References a, actionDestroyed(), KviPointerHashTable< Key, T >::find(), m_pActions, KviPointerHashTable< Key, T >::remove(), and KviAction::unregisterAccelerator().
Friends And Related Function Documentation
friend class CustomizeToolBarsDialog friend
friend class KviActionDrawer friend
friend class KviCustomToolBar friend
friend class KviMainWindow friend
Member Data Documentation
bool KviActionManager::m_bCoreActionsRegistered protected
Referenced by getAction(), KviActionManager(), and loadAllAvailableActions().
bool KviActionManager::m_bCustomizingToolBars = false static protected
Referenced by customizeToolBarsDialogCreated(), customizeToolBarsDialogDestroyed(), KviActionManager(), and setCurrentToolBar().
KviPointerHashTable<QString, KviAction>* KviActionManager::m_pActions protected
Referenced by actionDestroyed(), coreActionExists(), delayedRegisterAccelerators(), getAction(), killAllKvsUserActions(), KviActionManager(), listActionsByCategory(), nameForAutomaticAction(), registerAction(), save(), unregisterAction(), and ~KviActionManager().
KviPointerHashTable<QString, KviActionCategory>* KviActionManager::m_pCategories protected
Referenced by category(), KviActionManager(), and ~KviActionManager().
KviActionCategory * KviActionManager::m_pCategoryChannel = nullptr static protected
Referenced by KviActionManager().
KviActionCategory * KviActionManager::m_pCategoryGeneric = nullptr static protected
Referenced by category(), and KviActionManager().
KviActionCategory * KviActionManager::m_pCategoryGUI = nullptr static protected
Referenced by KviActionManager().
KviActionCategory * KviActionManager::m_pCategoryIrc = nullptr static protected
Referenced by KviActionManager().
KviActionCategory * KviActionManager::m_pCategoryScripting = nullptr static protected
Referenced by KviActionManager().
KviActionCategory * KviActionManager::m_pCategorySettings = nullptr static protected
Referenced by KviActionManager().
KviActionCategory * KviActionManager::m_pCategoryTools = nullptr static protected
Referenced by KviActionManager().
KviCustomToolBar * KviActionManager::m_pCurrentToolBar = nullptr static protected
Referenced by customizeToolBarsDialogCreated(), customizeToolBarsDialogDestroyed(), KviActionManager(), and setCurrentToolBar().
KviActionManager * KviActionManager::m_pInstance = nullptr static protected
Referenced by done(), and init().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviActionManager.h
src/kvirc/kernel/KviActionManager.cpp