KVIrc: OptionsWidget_timestamp Class Reference
OptionsWidget_timestamp Class Reference
#include <OptionsWidget_message.h>
Public Member Functions
OptionsWidget_timestamp (QWidget *parent)
~OptionsWidget_timestamp ()
Public Attributes
KviBoolSelector * m_pSpecialTimestampColorSelector
KviMircTextColorSelector * m_pTimestampColorSelector
KviBoolSelector * m_pUseTimestampSelector
Protected Slots
void enableDisableTimestampSelector (bool)
Constructor & Destructor Documentation
OptionsWidget_timestamp::OptionsWidget_timestamp (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addMircTextColorSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addWidgetToLayout(), connect(), KviOptionsWidget::createLayout(), enableDisableTimestampSelector(), KVI_OPTION_BOOL, KviOption_boolIrcViewTimestamp, KviOption_boolIrcViewTimestampUTC, KviOption_boolUseSpecialColorForTimestamp, KviOption_stringIrcViewTimestampFormat, KviOption_uintTimeStampBackground, KviOption_uintTimeStampForeground, m_pSpecialTimestampColorSelector, m_pTimestampColorSelector, and m_pUseTimestampSelector.
OptionsWidget_timestamp::~OptionsWidget_timestamp ()
Member Function Documentation
void OptionsWidget_timestamp::enableDisableTimestampSelector (bool) [protected, slot]
References m_pSpecialTimestampColorSelector, m_pTimestampColorSelector, m_pUseTimestampSelector, and KviMircTextColorSelector::setEnabled().
Referenced by OptionsWidget_timestamp().
Member Data Documentation
KviBoolSelector* OptionsWidget_timestamp::m_pSpecialTimestampColorSelector
Referenced by enableDisableTimestampSelector(), and OptionsWidget_timestamp().
KviMircTextColorSelector* OptionsWidget_timestamp::m_pTimestampColorSelector
Referenced by enableDisableTimestampSelector(), and OptionsWidget_timestamp().
KviBoolSelector* OptionsWidget_timestamp::m_pUseTimestampSelector
Referenced by enableDisableTimestampSelector(), and OptionsWidget_timestamp().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_message.h
src/modules/options/OptionsWidget_message.cpp