KVIrc: IrcServerDetailsWidget Class Reference
IrcServerDetailsWidget Class Reference
#include <OptionsWidget_servers.h>
Public Member Functions
void fillData (KviIrcServer *s)
IrcServerDetailsWidget (QWidget *par, KviIrcServer *s)
void setHeaderLabelText ()
~IrcServerDetailsWidget ()
Protected Slots
void portEditorTextChanged (const QString &)
void useDefaultInitUModeToggled (bool)
void useIPV6CheckToggled (bool)
Protected Attributes
QStringList m_lstChannels
QLineEdit * m_pAlternativeNickEditor
QCheckBox * m_pCacheIpCheck
KviChannelListSelector * m_pChannelListSelector
QLineEdit * m_pDescEditor
QCheckBox * m_pEnableCAPCheck
QCheckBox * m_pEnableSASLCheck
QCheckBox * m_pEnableSTARTTLSCheck
QComboBox * m_pEncodingEditor
QLabel * m_pHeaderLabel
QLineEdit * m_pIdEditor
QCheckBox * m_pIMode
KviIpEditor * m_pIpEditor
QComboBox * m_pLinkFilterEditor
QLineEdit * m_pNickEditor
KviScriptEditor * m_pOnConnectEditor
KviScriptEditor * m_pOnLoginEditor
KviPasswordLineEdit * m_pPassEditor
QLineEdit * m_pPortEditor
QComboBox * m_pProxyEditor
QLineEdit * m_pRealEditor
QLineEdit * m_pSaslNickEditor
KviPasswordLineEdit * m_pSaslPassEditor
QCheckBox * m_pSMode
QComboBox * m_pTextEncodingEditor
QCheckBox * m_pUseAutoConnect
QCheckBox * m_pUseDefaultInitUMode
QCheckBox * m_pUseIPV6Check
QLineEdit * m_pUserEditor
QCheckBox * m_pUseSSLCheck
QCheckBox * m_pWMode
QString m_szHostname
Constructor & Destructor Documentation
IrcServerDetailsWidget::IrcServerDetailsWidget (QWidget * par, KviIrcServer * s)
References __tr2qs_ctx(), KviTalToolTip::add(), KviIrcServer::alternativeNickName(), KviIrcServer::autoConnect(), KviIrcServer::autoJoinChannelList(), KviIrcServer::cacheIp(), KviIconManager::Channel, connect(), KviCString::contains(), KviScriptEditor::createInstance(), d, KviIrcServer::description(), KviIrcServer::enabledCAP(), KviIrcServer::enabledSASL(), KviIrcServer::enabledSTARTTLS(), KviIrcServer::encoding(), KviLocale::encodingDescription(), KviQString::equalCI(), KviPointerList< T >::first(), g, g_pIconManager, g_pModuleManager, g_pProxyDataBase, KviIrcServer::generateUniqueId(), KviModuleExtensionManager::getExtensionList(), KviIconManager::getSmallIcon(), KviIrcServer::hostName(), i, KviIrcServer::id(), KviIrcServer::initUMode(), KviModuleExtensionManager::instance(), KviLocale::instance(), KviIrcServer::ip(), KviIpEditor::IPv4, KviIpEditor::IPv6, KviIrcServer::isIPv6(), KVI_OPTION_STRING, KviOption_stringDefaultUserMode, l, KviIrcServer::linkFilter(), KviModuleManager::loadModulesByCaps(), m_lstChannels, m_pAlternativeNickEditor, m_pCacheIpCheck, m_pChannelListSelector, m_pDescEditor, m_pEnableCAPCheck, m_pEnableSASLCheck, m_pEnableSTARTTLSCheck, m_pEncodingEditor, m_pHeaderLabel, m_pIdEditor, m_pIMode, m_pIpEditor, m_pLinkFilterEditor, m_pNickEditor, m_pOnConnectEditor, m_pOnLoginEditor, m_pPassEditor, m_pPortEditor, m_pProxyEditor, m_pRealEditor, m_pSaslNickEditor, m_pSaslPassEditor, m_pSMode, m_pTextEncodingEditor, m_pUseAutoConnect, m_pUseDefaultInitUMode, m_pUseIPV6Check, m_pUserEditor, m_pUseSSLCheck, m_pWMode, m_szHostname, KviPointerList< T >::next(), KviIrcServer::nickName(), KviIrcServer::onConnectCommand(), KviIrcServer::onLoginCommand(), p, KviIrcServer::password(), KviLocale::_EncodingDescription::pcDescription, KviLocale::_EncodingDescription::pcName, KviIrcServer::port(), portEditorTextChanged(), KviIrcServer::proxy(), KviProxyDataBase::proxyList(), KviIrcServer::realName(), KviIrcServer::saslNick(), KviIrcServer::saslPass(), KviIconManager::Server, KviIpEditor::setAddress(), KviIpEditor::setAddressType(), setHeaderLabelText(), KviTalGroupBox::setLayout(), KviScriptEditor::setText(), KviPasswordLineEdit::setText(), KviIconManager::SocketWarning, KviIrcServer::textEncoding(), useDefaultInitUModeToggled(), useIPV6CheckToggled(), KviIrcServer::userName(), KviIrcServer::useSSL(), v, and KviIconManager::Who.
IrcServerDetailsWidget::~IrcServerDetailsWidget ()
References KviScriptEditor::destroyInstance(), m_pOnConnectEditor, and m_pOnLoginEditor.
Member Function Documentation
void IrcServerDetailsWidget::fillData (KviIrcServer * s)
References KviIpEditor::address(), KviCString::append(), KviChannelListSelector::commit(), d, KviLocale::encodingDescription(), KviQString::equalCI(), KviIrcServer::generateUniqueId(), KviScriptEditor::getText(), KviIpEditor::hasEmptyFields(), KviIrcServer::id(), KviLocale::instance(), KviIrcServer::isIPv6(), KviNetUtils::isValidStringIp(), m_lstChannels, m_pAlternativeNickEditor, m_pCacheIpCheck, m_pChannelListSelector, m_pDescEditor, m_pEnableCAPCheck, m_pEnableSASLCheck, m_pEnableSTARTTLSCheck, m_pEncodingEditor, m_pIdEditor, m_pIMode, m_pIpEditor, m_pLinkFilterEditor, m_pNickEditor, m_pOnConnectEditor, m_pOnLoginEditor, m_pPassEditor, m_pPortEditor, m_pProxyEditor, m_pRealEditor, m_pSaslNickEditor, m_pSaslPassEditor, m_pSMode, m_pTextEncodingEditor, m_pUseAutoConnect, m_pUseDefaultInitUMode, m_pUseIPV6Check, m_pUserEditor, m_pUseSSLCheck, m_pWMode, KviLocale::_EncodingDescription::pcName, KviCString::ptr(), KviIrcServer::setAlternativeNickName(), KviIrcServer::setAutoConnect(), KviIrcServer::setAutoJoinChannelList(), KviIrcServer::setCacheIp(), KviIrcServer::setDescription(), KviIrcServer::setEnabledCAP(), KviIrcServer::setEnabledSASL(), KviIrcServer::setEnabledSTARTTLS(), KviIrcServer::setEncoding(), KviIrcServer::setId(), KviIrcServer::setInitUMode(), KviIrcServer::setIp(), KviIrcServer::setIPv6(), KviIrcServer::setLinkFilter(), KviIrcServer::setNickName(), KviIrcServer::setOnConnectCommand(), KviIrcServer::setOnLoginCommand(), KviIrcServer::setPassword(), KviIrcServer::setPort(), KviIrcServer::setProxy(), KviIrcServer::setRealName(), KviIrcServer::setSaslNick(), KviIrcServer::setSaslPass(), KviIrcServer::setTextEncoding(), KviIrcServer::setUserName(), KviIrcServer::setUseSSL(), KviPasswordLineEdit::text(), and uPort.
Referenced by OptionsWidget_servers::detailsClicked().
void IrcServerDetailsWidget::portEditorTextChanged (const QString &) [protected, slot]
References setHeaderLabelText().
Referenced by IrcServerDetailsWidget().
void IrcServerDetailsWidget::setHeaderLabelText ()
References m_pHeaderLabel, m_pPortEditor, m_pUseIPV6Check, m_szHostname, and uPort.
Referenced by IrcServerDetailsWidget(), portEditorTextChanged(), and useIPV6CheckToggled().
void IrcServerDetailsWidget::useDefaultInitUModeToggled (bool b) [protected, slot]
References m_pIMode, m_pSMode, and m_pWMode.
Referenced by IrcServerDetailsWidget().
void IrcServerDetailsWidget::useIPV6CheckToggled (bool) [protected, slot]
References KviIpEditor::IPv4, KviIpEditor::IPv6, m_pIpEditor, m_pUseIPV6Check, KviIpEditor::setAddressType(), and setHeaderLabelText().
Referenced by IrcServerDetailsWidget().
Member Data Documentation
QStringList IrcServerDetailsWidget::m_lstChannels [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLineEdit* IrcServerDetailsWidget::m_pAlternativeNickEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pCacheIpCheck [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
KviChannelListSelector* IrcServerDetailsWidget::m_pChannelListSelector [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLineEdit* IrcServerDetailsWidget::m_pDescEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pEnableCAPCheck [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pEnableSASLCheck [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pEnableSTARTTLSCheck [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QComboBox* IrcServerDetailsWidget::m_pEncodingEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLabel* IrcServerDetailsWidget::m_pHeaderLabel [protected]
Referenced by IrcServerDetailsWidget(), and setHeaderLabelText().
QLineEdit* IrcServerDetailsWidget::m_pIdEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pIMode [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and useDefaultInitUModeToggled().
KviIpEditor* IrcServerDetailsWidget::m_pIpEditor [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and useIPV6CheckToggled().
QComboBox* IrcServerDetailsWidget::m_pLinkFilterEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLineEdit* IrcServerDetailsWidget::m_pNickEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
KviScriptEditor* IrcServerDetailsWidget::m_pOnConnectEditor [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and ~IrcServerDetailsWidget().
KviScriptEditor* IrcServerDetailsWidget::m_pOnLoginEditor [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and ~IrcServerDetailsWidget().
KviPasswordLineEdit* IrcServerDetailsWidget::m_pPassEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLineEdit* IrcServerDetailsWidget::m_pPortEditor [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and setHeaderLabelText().
QComboBox* IrcServerDetailsWidget::m_pProxyEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLineEdit* IrcServerDetailsWidget::m_pRealEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QLineEdit* IrcServerDetailsWidget::m_pSaslNickEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
KviPasswordLineEdit* IrcServerDetailsWidget::m_pSaslPassEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pSMode [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and useDefaultInitUModeToggled().
QComboBox* IrcServerDetailsWidget::m_pTextEncodingEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pUseAutoConnect [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pUseDefaultInitUMode [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pUseIPV6Check [protected]
Referenced by fillData(), IrcServerDetailsWidget(), setHeaderLabelText(), and useIPV6CheckToggled().
QLineEdit* IrcServerDetailsWidget::m_pUserEditor [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pUseSSLCheck [protected]
Referenced by fillData(), and IrcServerDetailsWidget().
QCheckBox* IrcServerDetailsWidget::m_pWMode [protected]
Referenced by fillData(), IrcServerDetailsWidget(), and useDefaultInitUModeToggled().
QString IrcServerDetailsWidget::m_szHostname [protected]
Referenced by IrcServerDetailsWidget(), and setHeaderLabelText().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_servers.h
src/modules/options/OptionsWidget_servers.cpp