KVIrc: KviKvsTreeNodeOperationSelfModulus Class Reference
KviKvsTreeNodeOperationSelfModulus Class Reference
#include <kvi_kvs_treenode_operation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationSelfModulus (const QChar *pLocation, KviKvsTreeNodeData *pRightSide)
~KviKvsTreeNodeOperationSelfModulus ()
Protected Attributes
KviKvsTreeNodeData * m_pRightSide
Constructor & Destructor Documentation
KviKvsTreeNodeOperationSelfModulus::KviKvsTreeNodeOperationSelfModulus (const QChar * pLocation, KviKvsTreeNodeData * pRightSide)
References m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationSelfModulus::~KviKvsTreeNodeOperationSelfModulus ()
References m_pRightSide.
Member Function Documentation
void KviKvsTreeNodeOperationSelfModulus::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationSelfModulus::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pRightSide, and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationSelfModulus::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx, KviKvsVariant::asNumber(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsNumber::integer(), KviKvsNumber::isInteger(), m_pRightSide, KviKvsTreeNodeOperation::m_pTargetData, KviKvsNumber::real(), KviKvsRWEvaluationResult::result(), KviKvsVariant::setInteger(), and KviKvsVariant::setReal().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationSelfModulus::m_pRightSide [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationSelfModulus(), and ~KviKvsTreeNodeOperationSelfModulus().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_treenode_operation.h
src/kvirc/kvs/kvi_kvs_treenode_operation.cpp