KVIrc: KviNickServRule Class Reference
KviNickServRule Class Reference
#include <KviNickServRule.h>
Public Member Functions
void copyFrom (const KviNickServRule &src)
const QString & identifyCommand () const
KviNickServRule ()
KviNickServRule (const QString &szRegisteredNick, const QString &szNickServMask, const QString &szMessageRegexp, const QString &szIdentifyCommand, const QString &szServerMask=QString::null)
bool load (KviConfigurationFile *cfg, const QString &prefix)
const QString & messageRegexp () const
const QString & nickServMask () const
const QString & registeredNick () const
void save (KviConfigurationFile *cfg, const QString &prefix)
const QString & serverMask () const
void setIdentifyCommand (const QString &szIdentifyCommand)
void setMessageRegexp (const QString &szMessageRegexp)
void setNickServMask (const QString &szNickServMask)
void setRegisteredNick (const QString &szRegisteredNick)
void setServerMask (const QString &szServerMask)
Static Public Member Functions
static KviNickServRule * createInstance (const QString &szRegisteredNick, const QString &szNickServMask, const QString &szMessageRegexp, const QString &szIdentifyCommand, const QString &szServerMask=QString::null)
Protected Attributes
QString m_szIdentifyCommand
QString m_szMessageRegexp
QString m_szNickServMask
QString m_szRegisteredNick
QString m_szServerMask
Constructor & Destructor Documentation
KviNickServRule::KviNickServRule () inline
Referenced by createInstance().
KviNickServRule::KviNickServRule (const QString & szRegisteredNick, const QString & szNickServMask, const QString & szMessageRegexp, const QString & szIdentifyCommand, const QString & szServerMask = QString::null) inline
Member Function Documentation
void KviNickServRule::copyFrom (const KviNickServRule & src)
References m_szIdentifyCommand, m_szMessageRegexp, m_szNickServMask, m_szRegisteredNick, and m_szServerMask.
Referenced by KviNickServRuleSet::copyFrom().
KviNickServRule * KviNickServRule::createInstance (const QString & szRegisteredNick, const QString & szNickServMask, const QString & szMessageRegexp, const QString & szIdentifyCommand, const QString & szServerMask = QString::null) static
References KviNickServRule().
Referenced by OptionsWidget_nickServ::commit(), and IrcNetworkDetailsWidget::fillData().
const QString& KviNickServRule::identifyCommand () const inline
Referenced by OptionsWidget_nickServ::addNickServRule(), IrcNetworkDetailsWidget::addNickServRule(), NickServRuleEditor::editRule(), and KviIrcServerParser::parseLiteralNotice().
bool KviNickServRule::load (KviConfigurationFile * cfg, const QString & prefix)
References m_szIdentifyCommand, m_szMessageRegexp, m_szNickServMask, m_szRegisteredNick, m_szServerMask, and KviConfigurationFile::readEntry().
Referenced by KviNickServRuleSet::loadPrivate().
const QString& KviNickServRule::messageRegexp () const inline
Referenced by OptionsWidget_nickServ::addNickServRule(), IrcNetworkDetailsWidget::addNickServRule(), and NickServRuleEditor::editRule().
const QString& KviNickServRule::nickServMask () const inline
Referenced by OptionsWidget_nickServ::addNickServRule(), IrcNetworkDetailsWidget::addNickServRule(), and NickServRuleEditor::editRule().
const QString& KviNickServRule::registeredNick () const inline
Referenced by OptionsWidget_nickServ::addNickServRule(), IrcNetworkDetailsWidget::addNickServRule(), and NickServRuleEditor::editRule().
void KviNickServRule::save (KviConfigurationFile * cfg, const QString & prefix)
References m_szIdentifyCommand, m_szMessageRegexp, m_szNickServMask, m_szRegisteredNick, m_szServerMask, and KviConfigurationFile::writeEntry().
const QString& KviNickServRule::serverMask () const inline
Referenced by OptionsWidget_nickServ::addNickServRule(), and NickServRuleEditor::editRule().
void KviNickServRule::setIdentifyCommand (const QString & szIdentifyCommand) inline
Referenced by NickServRuleEditor::editRule().
void KviNickServRule::setMessageRegexp (const QString & szMessageRegexp) inline
Referenced by NickServRuleEditor::editRule().
void KviNickServRule::setNickServMask (const QString & szNickServMask) inline
Referenced by NickServRuleEditor::editRule().
void KviNickServRule::setRegisteredNick (const QString & szRegisteredNick) inline
Referenced by NickServRuleEditor::editRule().
void KviNickServRule::setServerMask (const QString & szServerMask) inline
Referenced by NickServRuleEditor::editRule().
Member Data Documentation
QString KviNickServRule::m_szIdentifyCommand protected
Referenced by copyFrom(), load(), and save().
QString KviNickServRule::m_szMessageRegexp protected
Referenced by copyFrom(), load(), and save().
QString KviNickServRule::m_szNickServMask protected
Referenced by copyFrom(), load(), and save().
QString KviNickServRule::m_szRegisteredNick protected
Referenced by copyFrom(), load(), and save().
QString KviNickServRule::m_szServerMask protected
Referenced by copyFrom(), load(), and save().
The documentation for this class was generated from the following files:
src/kvilib/irc/KviNickServRule.h
src/kvilib/irc/KviNickServRule.cpp