KVIrc: OptionsWidget_uparser Class Reference
OptionsWidget_uparser Class Reference
#include <OptionsWidget_uparser.h>
Public Member Functions
OptionsWidget_uparser (QWidget *parent)
~OptionsWidget_uparser ()
Constructor & Destructor Documentation
OptionsWidget_uparser::OptionsWidget_uparser (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addSeparator(), KviOptionsWidget::createLayout(), KviOption_boolAvoidParserWarnings, KviOption_boolCleanupUnusedModules, KviOption_boolDisableBrokenEventHandlers, KviOption_boolIgnoreModuleVersions, KviOption_boolKillBrokenTimers, KviOption_boolScriptErrorsToDebugWindow, KviOption_boolSendUnknownCommandsAsRaw, KviOption_boolShowMinimizedDebugWindow, and KviOptionsWidget::mergeTip().
OptionsWidget_uparser::~OptionsWidget_uparser ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_uparser.h
src/modules/options/OptionsWidget_uparser.cpp