KVIrc: KviKvsTimerManager Class Reference
KviKvsTimerManager Class Reference
#include <KviKvsTimerManager.h>
Public Member Functions
bool addTimer (const QString &szName, KviKvsTimer::Lifetime l, KviWindow *pWnd, int iDelay, KviKvsScript *pCallback, KviKvsVariantList *pParams)
void deleteAllTimers ()
bool deleteCurrentTimer ()
bool deleteTimer (const QString &szName)
bool deleteTimer (int iId)
KviPointerHashTable< QString,
KviKvsTimer > * timerDict ()
bool timerExists (const QString &szName)
Static Public Member Functions
static void done ()
static void init ()
static KviKvsTimerManager * instance ()
Protected Member Functions
KviKvsTimerManager ()
void scheduleKill (KviKvsTimer *t)
virtual void timerEvent (QTimerEvent *e)
~KviKvsTimerManager ()
Private Attributes
int m_iAssassinTimer
int m_iCurrentTimer
KviPointerList< KviKvsTimer > * m_pKilledTimerList
KviPointerHashTable< int,
KviKvsTimer > * m_pTimerDictById
KviPointerHashTable< QString,
KviKvsTimer > * m_pTimerDictByName
Static Private Attributes
static KviKvsTimerManager * m_pInstance = nullptr
Constructor & Destructor Documentation
KviKvsTimerManager::KviKvsTimerManager () protected
References m_iAssassinTimer, m_iCurrentTimer, m_pKilledTimerList, m_pTimerDictById, m_pTimerDictByName, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviKvsTimerManager::~KviKvsTimerManager () protected
References m_pKilledTimerList, m_pTimerDictById, m_pTimerDictByName, and KviPointerHashTable< Key, T >::setAutoDelete().
Member Function Documentation
bool KviKvsTimerManager::addTimer (const QString & szName, KviKvsTimer::Lifetime l, KviWindow * pWnd, int iDelay, KviKvsScript * pCallback, KviKvsVariantList * pParams)
References deleteTimer(), KviPointerHashTable< Key, T >::find(), KviKvsTimer::id(), KviPointerHashTable< Key, T >::insert(), m_pTimerDictById, m_pTimerDictByName, and t().
void KviKvsTimerManager::deleteAllTimers ()
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), deleteTimer(), KviPointerList< T >::first(), KviPointerHashTable< Key, T >::isEmpty(), m_pTimerDictById, KviPointerList< T >::next(), KviPointerList< T >::setAutoDelete(), and t().
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
bool KviKvsTimerManager::deleteCurrentTimer ()
References deleteTimer(), and m_iCurrentTimer.
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
bool KviKvsTimerManager::deleteTimer (const QString & szName)
References KviPointerHashTable< Key, T >::find(), KviKvsTimer::id(), m_pTimerDictById, m_pTimerDictByName, KviPointerHashTable< Key, T >::remove(), scheduleKill(), and t().
Referenced by addTimer(), deleteAllTimers(), deleteCurrentTimer(), and timerEvent().
bool KviKvsTimerManager::deleteTimer (int iId)
References KviPointerHashTable< Key, T >::find(), KviKvsTimer::id(), m_pTimerDictById, m_pTimerDictByName, KviKvsTimer::name(), KviPointerHashTable< Key, T >::remove(), scheduleKill(), and t().
void KviKvsTimerManager::done () static
References m_pInstance.
Referenced by KviKvs::done().
void KviKvsTimerManager::init () static
References KviKvsTimerManager().
Referenced by KviKvs::init().
static KviKvsTimerManager* KviKvsTimerManager::instance () inline static
Referenced by KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreFunctions::KVSCF(), and KviKvsCoreSimpleCommands::KVSCSC().
void KviKvsTimerManager::scheduleKill (KviKvsTimer * t) protected
References KviPointerList< T >::append(), m_iAssassinTimer, m_pKilledTimerList, and KviPointerList< T >::setAutoDelete().
Referenced by deleteTimer().
KviPointerHashTable<QString, KviKvsTimer>* KviKvsTimerManager::timerDict () inline
Referenced by KviKvsCoreFunctions::KVSCF(), and KviKvsCoreSimpleCommands::KVSCSC().
void KviKvsTimerManager::timerEvent (QTimerEvent * e) protected virtual
References __tr2qs_ctx(), KviApplication::activeConsole(), KviKvsTimer::callback(), KviPointerList< T >::clear(), KviMemory::copy(), deleteTimer(), KviPointerHashTable< Key, T >::find(), g_pApp, KviKvsTimer::id(), KVI_OPTION_BOOL, KVI_OUT_PARSERERROR, KviOption_boolKillBrokenTimers, KviKvsTimer::lifetime(), m_iAssassinTimer, m_iCurrentTimer, m_pKilledTimerList, m_pTimerDictById, KviKvsTimer::name(), KviWindow::output(), KviKvsTimer::parameterList(), KviKvsTimer::Persistent, KviKvsScript::PreserveParams, KviKvsScript::run(), KviKvsTimer::runTimeData(), KviKvsTimer::setWindow(), KviKvsTimer::SingleShot, t(), KviKvsTimer::window(), and KviApplication::windowExists().
bool KviKvsTimerManager::timerExists (const QString & szName) inline
Member Data Documentation
int KviKvsTimerManager::m_iAssassinTimer private
Referenced by KviKvsTimerManager(), scheduleKill(), and timerEvent().
int KviKvsTimerManager::m_iCurrentTimer private
Referenced by deleteCurrentTimer(), KviKvsTimerManager(), and timerEvent().
KviKvsTimerManager * KviKvsTimerManager::m_pInstance = nullptr static private
Referenced by done().
KviPointerList<KviKvsTimer>* KviKvsTimerManager::m_pKilledTimerList private
Referenced by KviKvsTimerManager(), scheduleKill(), timerEvent(), and ~KviKvsTimerManager().
KviPointerHashTable<int, KviKvsTimer>* KviKvsTimerManager::m_pTimerDictById private
Referenced by addTimer(), deleteAllTimers(), deleteTimer(), KviKvsTimerManager(), timerEvent(), and ~KviKvsTimerManager().
KviPointerHashTable<QString, KviKvsTimer>* KviKvsTimerManager::m_pTimerDictByName private
Referenced by addTimer(), deleteTimer(), KviKvsTimerManager(), and ~KviKvsTimerManager().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsTimerManager.h
src/kvirc/kvs/KviKvsTimerManager.cpp