KVIrc: KviKvsTreeNodeArrayCount Class Reference
KviKvsTreeNodeArrayCount Class Reference
Treenode array count class.
#include <KviKvsTreeNodeArrayCount.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Array Count Operator.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the array in read-only mode.
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the array in read-only mode in the object scope.
KviKvsTreeNodeArrayCount (const QChar *pLocation, KviKvsTreeNodeData *pSource)
Constructs the treenode array count object.
~KviKvsTreeNodeArrayCount ()
Destroys the treenode array count object.
Public Member Functions inherited from KviKvsTreeNodeIndirectData
virtual bool canEvaluateInObjectScope ()
KviKvsTreeNodeIndirectData (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeIndirectData ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeIndirectData
KviKvsTreeNodeData * m_pSource
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Detailed Description
Treenode array count class.
Constructor & Destructor Documentation
KviKvsTreeNodeArrayCount::KviKvsTreeNodeArrayCount (const QChar * pLocation, KviKvsTreeNodeData * pSource)
Constructs the treenode array count object.
Parameters
pLocation The location char of the instruction
pSource The source data
Returns
KviKvsTreeNodeArrayCount
KviKvsTreeNodeArrayCount::~KviKvsTreeNodeArrayCount ()
Destroys the treenode array count object.
Member Function Documentation
void KviKvsTreeNodeArrayCount::contextDescription (QString & szBuffer) virtual
Sets the buffer as Array Count Operator.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeArrayCount::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
bool KviKvsTreeNodeArrayCount::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Evaluates the array in read-only mode.
Parameters
c The context where the alias is bound to
pBuffer The data buffer
Returns
bool
Reimplemented from KviKvsTreeNodeData.
References evaluateReadOnlyInObjectScope().
bool KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Evaluates the array in read-only mode in the object scope.
Parameters
o The source object to evaluate
c The context where the array is bound to
pBuffer The data buffer
Returns
bool
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsVariant::getTypeName(), KviKvsVariant::isArray(), KviKvsVariant::isNothing(), KviKvsTreeNodeIndirectData::m_pSource, KviKvsVariant::setInteger(), KviKvsArray::size(), and KviKvsRunTimeContext::warning().
Referenced by evaluateReadOnly().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeArrayCount.h
src/kvirc/kvs/tree/KviKvsTreeNodeArrayCount.cpp