KVIrc: KviExternalServerDataParser Class Reference
KviExternalServerDataParser Class Reference
#include <KviIrcServerParser.h>
Public Member Functions
virtual void control (int)
virtual void die ()
KviExternalServerDataParser ()
virtual void processData (KviIrcMessage *)
virtual ~KviExternalServerDataParser ()
Constructor & Destructor Documentation
KviExternalServerDataParser::KviExternalServerDataParser () [inline]
virtual KviExternalServerDataParser::~KviExternalServerDataParser () [inline, virtual]
Member Function Documentation
virtual void KviExternalServerDataParser::control (int) [inline, virtual]
Reimplemented in LinksWindow, and ListWindow.
Referenced by KviIrcContext::destroyConnection(), KviIrcServerParser::parseNumericEndOfLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericListEnd(), and KviIrcServerParser::parseNumericListStart().
virtual void KviExternalServerDataParser::die () [inline, virtual]
Reimplemented in LinksWindow, and ListWindow.
Referenced by KviIrcContext::~KviIrcContext().
virtual void KviExternalServerDataParser::processData (KviIrcMessage *) [inline, virtual]
Reimplemented in LinksWindow, and ListWindow.
Referenced by KviIrcServerParser::parseNumericLinks(), and KviIrcServerParser::parseNumericList().
The documentation for this class was generated from the following file:
src/kvirc/sparser/KviIrcServerParser.h