KVIrc: KviKvsNumber Class Reference
KviKvsNumber Class Reference
A class which maps every number.
#include <KviKvsVariant.h>
Classes
union DataType
This union holds an integer or a double floating point number.
Public Types
enum Type { Real, Integer }
Describes the type of number.
Public Member Functions
kvs_int_t integer () const
Return the integer number if the number itself is an integer.
bool isInteger () const
Returns true if the number is an integer.
bool isReal () const
Returns true if the number is a double floating point.
kvs_real_t real () const
Return the real number if the number itself is a double floating point.
Type type () const
Returns the type of the number.
Protected Attributes
Type m_type
DataType m_u
Friends
class KviKvsVariant
Detailed Description
A class which maps every number.
Member Enumeration Documentation
enum KviKvsNumber::Type
Describes the type of number.
Enumerator:
Real
The number is an integer
Integer
The number is a double floating point
Member Function Documentation
kvs_int_t KviKvsNumber::integer () const [inline]
Return the integer number if the number itself is an integer.
Returns:
kvs_int_t
Referenced by KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), and str_kvs_fnc_isunsignednumber().
bool KviKvsNumber::isInteger () const [inline]
Returns true if the number is an integer.
Returns:
bool
Referenced by KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), and str_kvs_fnc_isunsignednumber().
bool KviKvsNumber::isReal () const [inline]
Returns true if the number is a double floating point.
Returns:
bool
Referenced by KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly(), and KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly().
kvs_real_t KviKvsNumber::real () const [inline]
Return the real number if the number itself is a double floating point.
Returns:
kvs_real_t
Referenced by KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), and str_kvs_fnc_isunsignednumber().
Type KviKvsNumber::type () const [inline]
Returns the type of the number.
Returns:
Type
Friends And Related Function Documentation
friend class KviKvsVariant [friend]
Member Data Documentation
Type KviKvsNumber::m_type [protected]
Referenced by KviKvsVariant::asNumber(), and KviKvsVariant::castToNumber().
DataType KviKvsNumber::m_u [protected]
Referenced by KviKvsVariant::asNumber(), and KviKvsVariant::castToNumber().
The documentation for this class was generated from the following file:
src/kvirc/kvs/KviKvsVariant.h