KVIrc: KviFrame Class Reference
KviFrame Class Reference
#include <kvi_frame.h>
Public Slots
void customizeToolBars ()
void executeInternalCommand (int index)
void newConsole ()
void toggleStatusBar ()
Signals
void activeConnectionAwayStateChanged ()
void activeConnectionLagChanged ()
void activeConnectionNickNameChanged ()
void activeConnectionServerInfoChanged ()
void activeConnectionUserModeChanged ()
void activeContextChanged ()
void activeContextStateChanged ()
void activeWindowChanged ()
void activeWindowSelectionStateChanged (bool bGotSelectionNow)
void signalMaximizeMdiChildWindow (KviMdiChild *lpC)
Public Member Functions
KviIrcConnection * activeConnection ()
KviIrcContext * activeContext ()
void addWindow (KviWindow *wnd, bool bShow=true)
void closeWindow (KviWindow *wnd)
unsigned int consoleCount ()
KviConsole * createNewConsole (bool bFirstInFrame=false)
KviDockExtension * dockExtension ()
void fillToolBarsPopup (KviTalPopupMenu *p)
KviConsole * firstConsole ()
KviConsole * firstNotConnectedConsole ()
KviFrame ()
KviMenuBar * mainMenuBar ()
KviStatusBar * mainStatusBar ()
KviMdiManager * mdiManager ()
KviMexToolBar * moduleExtensionToolBar (int extensionId)
void saveWindowProperties (KviWindow *wnd, const QString &szSection)
void setActiveWindow (KviWindow *wnd)
void setDockExtension (KviDockExtension *e)
void setUsesBigPixmaps (bool bUse)
Sets the use of big pixmaps in toolbar.
QSplitter * splitter ()
bool windowExists (KviWindow *wnd)
KviPointerList< KviWindow > * windowList ()
KviWindowListBase * windowListWidget ()
~KviFrame ()
Protected Slots
void accelActivated ()
void maximizeWindow ()
void minimizeWindow ()
void switchToNextHighlightedWindow ()
void switchToNextWindow ()
void switchToNextWindowInContext ()
void switchToPrevHighlightedWindow ()
void switchToPrevWindow ()
void switchToPrevWindowInContext ()
void toolbarsPopupSelected (int id)
Protected Member Functions
void applyOptions ()
virtual void changeEvent (QEvent *event)
void childConnectionAwayStateChange (KviIrcConnection *c)
void childConnectionLagChange (KviIrcConnection *c)
void childConnectionNickNameChange (KviIrcConnection *c)
void childConnectionServerInfoChange (KviIrcConnection *c)
void childConnectionUserModeChange (KviIrcConnection *c)
void childContextStateChange (KviIrcContext *c)
void childWindowActivated (KviWindow *wnd, bool bForce=false)
void childWindowCloseRequest (KviWindow *wnd)
void childWindowSelectionStateChange (KviWindow *pWnd, bool bGotSelectionNow)
virtual void closeEvent (QCloseEvent *e)
virtual void contextMenuEvent (QContextMenuEvent *event)
void createWindowList ()
KviMdiChild * dockWindow (KviWindow *wnd, bool bCascade=true, QRect *setGeom=0)
virtual bool focusNextPrevChild (bool next)
void installAccelerators ()
virtual void moveEvent (QMoveEvent *e)
void recreateWindowList ()
void registerModuleExtensionToolBar (KviMexToolBar *t)
virtual void resizeEvent (QResizeEvent *e)
void restoreModuleExtensionToolBars ()
void saveModuleExtensionToolBars ()
void undockWindow (KviWindow *wnd)
void unhighlightWindowsOfContext (KviIrcContext *c)
void unregisterModuleExtensionToolBar (KviMexToolBar *t)
void updatePseudoTransparency ()
Protected Attributes
KviIrcContext * m_pActiveContext
KviDockExtension * m_pDockExtension
KviMdiManager * m_pMdi
KviMenuBar * m_pMenuBar
KviPointerList< KviMexToolBar > * m_pModuleExtensionToolBarList
QSplitter * m_pSplitter
KviStatusBar * m_pStatusBar
KviWindowListBase * m_pWindowList
KviPointerList< KviWindow > * m_pWinList
Private Member Functions
void restoreToolBarPositions ()
void saveToolBarPositions ()
Friends
class KviApp
class KviConsole
class KviIrcConnection
class KviIrcContext
class KviLagMeter
class KviMdiManager
class KviMexToolBar
class KviServerParser
class KviUserListView
class KviUserListViewArea
class KviWindow
Constructor & Destructor Documentation
KviFrame::KviFrame ()
References applyOptions(), createWindowList(), g_pApp, g_pFrame, g_pIconManager, KviIconManager::getSmallIcon(), installAccelerators(), KVI_DEFAULT_FRAME_CAPTION, KVI_OPTION_BOOL, KVI_OPTION_RECT, KVI_SMALLICON_KVIRC, KviMdiManager, KviOption_boolFrameIsMaximized, KviOption_boolStatusBarVisible, KviOption_boolUseBigIcons, KviOption_rectFrameGeometry, KviStatusBar::load(), m_pActiveContext, m_pDockExtension, m_pMdi, m_pMenuBar, m_pModuleExtensionToolBarList, m_pSplitter, m_pStatusBar, m_pWindowList, m_pWinList, KviPointerList< T >::setAutoDelete(), and setUsesBigPixmaps().
KviFrame::~KviFrame ()
References KviPointerList< T >::at(), closeWindow(), KviPointerList< T >::count(), KviDockExtension::die(), KviPointerList< T >::first(), KviApp::frameDestructorCallback(), g_pApp, g_pFrame, KviCustomToolBarManager::instance(), KviMdiManager::isInSDIMode(), KVI_OPTION_BOOL, KVI_OPTION_RECT, KVI_WINDOW_TYPE_CONSOLE, KviOption_boolFrameIsMaximized, KviOption_boolMdiManagerInSdiMode, KviOption_boolShowDockExtension, KviOption_boolStatusBarVisible, KviOption_boolUseBigIcons, KviOption_rectFrameGeometry, m_pDockExtension, m_pMdi, m_pModuleExtensionToolBarList, m_pStatusBar, m_pWinList, KviPointerList< T >::next(), saveModuleExtensionToolBars(), saveToolBarPositions(), KviCustomToolBarManager::storeVisibilityState(), KviWindow::type(), and KviTalMainWindow::usesBigPixmaps().
Member Function Documentation
void KviFrame::accelActivated () [protected, slot]
References g_pActiveWindow, KviEvent_OnAccelKeyPressed, and KVS_TRIGGER_EVENT_1.
Referenced by installAccelerators().
KviIrcConnection * KviFrame::activeConnection ()
References KviIrcContext::connection(), and m_pActiveContext.
Referenced by KviStatusBarLagIndicator::mouseDoubleClickEvent(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviStatusBarLagIndicator::tipText(), and KviStatusBarAwayIndicator::tipText().
void KviFrame::activeConnectionAwayStateChanged () [signal]
Referenced by childConnectionAwayStateChange(), and KviStatusBarAwayIndicator::KviStatusBarAwayIndicator().
void KviFrame::activeConnectionLagChanged () [signal]
Referenced by childConnectionLagChange(), and KviStatusBarLagIndicator::KviStatusBarLagIndicator().
void KviFrame::activeConnectionNickNameChanged () [signal]
Referenced by childConnectionNickNameChange().
void KviFrame::activeConnectionServerInfoChanged () [signal]
Referenced by childConnectionServerInfoChange().
void KviFrame::activeConnectionUserModeChanged () [signal]
Referenced by childConnectionUserModeChange().
KviIrcContext* KviFrame::activeContext () [inline]
Referenced by KviConnectAction::activate(), KviAction::activeContextChanged(), KviGoAwayAction::activeContextStateChanged(), KviConnectAction::activeContextStateChanged(), KviAction::activeContextStateChanged(), KviAction::activeWindowChanged(), KviGoAwayAction::addToPopupMenu(), KviConnectAction::addToPopupMenu(), KviStatusBar::mouseDoubleClickEvent(), KviStatusBar::setPermanentMessage(), KviAction::setup(), KviMenuBar::setupMainPopup(), KviStatusBar::tipRequest(), KviStatusBarLagIndicator::updateDisplay(), and KviStatusBarAwayIndicator::updateDisplay().
void KviFrame::activeContextChanged () [signal]
Referenced by childWindowActivated(), KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), and KviStatusBarLagIndicator::KviStatusBarLagIndicator().
void KviFrame::activeContextStateChanged () [signal]
Referenced by childContextStateChange(), KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), and KviStatusBarLagIndicator::KviStatusBarLagIndicator().
void KviFrame::activeWindowChanged () [signal]
Referenced by childWindowActivated().
void KviFrame::activeWindowSelectionStateChanged (bool bGotSelectionNow) [signal]
Referenced by childWindowSelectionStateChange().
void KviFrame::addWindow (KviWindow * wnd, bool bShow = true)
References KviPointerList< T >::append(), childWindowActivated(), KviWindow::context(), KviPointerList< T >::count(), KviWindow::createWindowListItem(), dockWindow(), g_pActiveWindow, KviWindow::getConfigGroupName(), KviConfig::hasGroup(), KVI_OPTION_BOOL, KviOption_boolWindowsRememberProperties, KviWindow::loadProperties(), m_pActiveContext, m_pMdi, m_pWinList, KviWindow::maximize(), KviConfig::readBoolEntry(), KviConfig::readRectEntry(), KviWindow::setFocus(), KviConfig::setGroup(), KviMdiChild::setRestoredGeometry(), KviMdiManager::showAndActivate(), KviWindow::triggerCreationEvents(), KviWindow::typeString(), and KviWindow::youAreUndocked().
Referenced by KviIrcConnection::createChannel(), createNewConsole(), KviIrcConnection::createQuery(), and KviDebugWindow::getInstance().
void KviFrame::applyOptions () [protected]
References KviTextIconManager::applyOptions(), KviWindowListBase::applyOptions(), KviPointerList< T >::first(), g_pTextIconManager, m_pMdi, m_pWindowList, m_pWinList, and KviPointerList< T >::next().
Referenced by KviFrame(), and KviApp::updateGui().
void KviFrame::changeEvent (QEvent * event) [protected, virtual]
References childWindowActivated(), g_pActiveWindow, and KviWindow::lostUserFocus().
void KviFrame::childConnectionAwayStateChange (KviIrcConnection * c) [protected]
References activeConnectionAwayStateChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::changeAwayState().
void KviFrame::childConnectionLagChange (KviIrcConnection * c) [protected]
References activeConnectionLagChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviLagMeter::timerEvent().
void KviFrame::childConnectionNickNameChange (KviIrcConnection * c) [protected]
References activeConnectionNickNameChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::nickChange().
void KviFrame::childConnectionServerInfoChange (KviIrcConnection * c) [protected]
References activeConnectionServerInfoChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::serverInfoReceived().
void KviFrame::childConnectionUserModeChange (KviIrcConnection * c) [protected]
References activeConnectionUserModeChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::changeUserMode().
void KviFrame::childContextStateChange (KviIrcContext * c) [protected]
References activeContextStateChanged(), and m_pActiveContext.
Referenced by KviIrcContext::setState().
void KviFrame::childWindowActivated (KviWindow * wnd, bool bForce = false) [protected]
References activeContextChanged(), activeWindowChanged(), KviIrcView::clearUnreaded(), KviWindow::context(), g_pActiveWindow, KviEvent_OnWindowActivated, KVS_TRIGGER_EVENT_0, KviWindow::lostUserFocus(), m_pActiveContext, m_pWindowList, KviWindowListBase::setActiveItem(), KviWindow::view(), and KviWindow::windowListItem().
Referenced by KviWindow::activateSelf(), addWindow(), changeEvent(), and KviMdiManager::slotSubWindowActivated().
void KviFrame::childWindowCloseRequest (KviWindow * wnd) [protected]
References closeWindow().
Referenced by KviWindow::closeEvent().
void KviFrame::childWindowSelectionStateChange (KviWindow * pWnd, bool bGotSelectionNow) [protected]
References activeWindowSelectionStateChanged(), and g_pActiveWindow.
Referenced by KviUserListView::insertUserEntry(), KviUserListViewArea::keyPressEvent(), KviUserListViewArea::mouseMoveEvent(), KviUserListViewArea::mousePressEvent(), KviUserListView::partInternal(), KviUserListView::removeAllEntries(), and KviUserListView::select().
void KviFrame::closeEvent (QCloseEvent * e) [protected, virtual]
References __tr2qs, KviApp::destroyFrame(), dockExtension(), executeInternalCommand(), KviPointerList< T >::first(), g_pApp, KVI_INTERNALCOMMAND_TRAYICON_SHOW, KVI_OPTION_BOOL, KVI_WINDOW_TYPE_CONSOLE, KviOption_boolCloseInTray, KviOption_boolConfirmCloseWhenThereAreConnections, m_pWinList, KviPointerList< T >::next(), and KviMessageBox::warning().
void KviFrame::closeWindow (KviWindow * wnd)
References consoleCount(), KviMdiManager::destroyChild(), g_pActiveWindow, KviWindow::getConfigGroupName(), KviMdiManager::hideChild(), KVI_OPTION_BOOL, KviEvent_OnFrameWindowDestroyed, KviEvent_OnKVIrcShutdown, KviOption_boolWindowsRememberProperties, KVS_TRIGGER_EVENT_0, m_pActiveContext, m_pMdi, m_pWinList, KviWindow::mdiParent(), KviPointerList< T >::removeRef(), saveWindowProperties(), and KviWindow::triggerDestructionEvents().
Referenced by childWindowCloseRequest(), KviIrcContext::closeAllContextWindows(), KviIrcContext::closeAllDeadChannels(), KviIrcContext::closeAllDeadQueries(), KviServerParser::parseLiteralKick(), KviServerParser::parseLiteralNick(), KviServerParser::parseLiteralPart(), and ~KviFrame().
unsigned int KviFrame::consoleCount ()
References KviPointerList< T >::first(), KVI_WINDOW_TYPE_CONSOLE, m_pWinList, and KviPointerList< T >::next().
Referenced by KviConsole::closeEvent(), and closeWindow().
void KviFrame::contextMenuEvent (QContextMenuEvent * event) [protected, virtual]
KviConsole * KviFrame::createNewConsole (bool bFirstInFrame = false)
References addWindow(), c, KviCustomToolBarManager::createToolBarsVisibleAtStartup(), KviActionManager::delayedRegisterAccelerators(), KviActionManager::instance(), KviCustomToolBarManager::instance(), KVI_CONSOLE_FLAG_FIRSTINFRAME, KviConsole, restoreModuleExtensionToolBars(), and restoreToolBarPositions().
Referenced by KviApp::createFrame(), newConsole(), and KviIrcUrl::run().
void KviFrame::createWindowList () [protected]
References KviWindowListBase::currentDockArea(), KVI_OPTION_BOOL, KviOption_boolUseTreeWindowListWindowList, and m_pWindowList.
Referenced by KviFrame(), and recreateWindowList().
void KviFrame::customizeToolBars () [slot]
References g_pActiveWindow, and KviIrcUrl::run().
Referenced by fillToolBarsPopup().
KviDockExtension* KviFrame::dockExtension () [inline]
Referenced by KviClassicWindowList::addItem(), KviIrcView::clearUnreaded(), closeEvent(), KviTreeWindowListItem::highlight(), KviWindowListButton::highlight(), KviClassicWindowList::removeItem(), KviTreeWindowList::setActiveItem(), KviClassicWindowList::setActiveItem(), KviTreeWindowListItem::unhighlight(), and KviWindowListButton::unhighlight().
KviMdiChild * KviFrame::dockWindow (KviWindow * wnd, bool bCascade = true, QRect * setGeom = 0) [protected]
References m_pMdi, KviMdiManager::manageChild(), KviWindow::mdiParent(), KviMdiChild::setClient(), and KviWindow::youAreDocked().
Referenced by addWindow(), and KviWindow::dock().
void KviFrame::executeInternalCommand (int index) [slot]
References firstConsole(), kvi_getInternalCommandBuffer(), and KviIrcUrl::run().
Referenced by KviMenuBar::actionTriggered(), closeEvent(), KviApp::createFrame(), KviIrcConnectionTargetResolver::haveServerIp(), KviIrcConnection::linkAttemptFailed(), KviIrcConnection::linkTerminated(), KviIrcConnection::loginComplete(), KviApp::optionResetUpdate(), KviApp::setup(), KviIrcConnection::start(), KviConsole::triggerCreationEvents(), and KviIrcConnection::~KviIrcConnection().
void KviFrame::fillToolBarsPopup (KviTalPopupMenu * p)
References __tr2qs, KviTalPopupMenu::clear(), KviPointerHashTableIterator< Key, T >::current(), customizeToolBars(), d, KviPointerList< T >::first(), g_pIconManager, g_pModuleExtensionManager, KviModuleExtensionManager::getExtensionList(), KviIconManager::getImage(), KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KviCustomToolBarManager::instance(), KVI_SMALLICON_TOOLBAR, moduleExtensionToolBar(), KviPointerList< T >::next(), KviTalPopupMenu::setItemChecked(), KviTalPopupMenu::setItemParameter(), and toolbarsPopupSelected().
Referenced by KviToolBar::mousePressEvent(), and KviMenuBar::setupToolbarsPopup().
KviConsole * KviFrame::firstConsole ()
References KviPointerList< T >::first(), KVI_ASSERT, KVI_WINDOW_TYPE_CONSOLE, m_pWinList, and KviPointerList< T >::next().
Referenced by KviApp::activeConsole(), KviApp::createFrame(), executeInternalCommand(), KviApp::ipcMessage(), KviApp::loadDefaultScript(), KviModuleManager::loadModule(), KviMenuBar::newConnectionToServer(), restoreModuleExtensionToolBars(), toolbarsPopupSelected(), KviMenuBar::toolsPopupSelected(), and KviModuleManager::unloadModule().
KviConsole * KviFrame::firstNotConnectedConsole ()
References KviPointerList< T >::first(), KVI_WINDOW_TYPE_CONSOLE, m_pWinList, and KviPointerList< T >::next().
Referenced by KviIrcUrl::run().
bool KviFrame::focusNextPrevChild (bool next) [protected, virtual]
void KviFrame::installAccelerators () [protected]
References accelActivated(), KVI_SHORTCUTS_WIN_MAXIMIZE, KVI_SHORTCUTS_WIN_MINIMIZE, KVI_SHORTCUTS_WIN_NEXT, KVI_SHORTCUTS_WIN_NEXT_CONTEXT, KVI_SHORTCUTS_WIN_NEXT_HIGHLIGHT, KVI_SHORTCUTS_WIN_PREV, KVI_SHORTCUTS_WIN_PREV_CONTEXT, KVI_SHORTCUTS_WIN_PREV_HIGHLIGHT, maximizeWindow(), minimizeWindow(), switchToNextHighlightedWindow(), switchToNextWindow(), switchToNextWindowInContext(), switchToPrevHighlightedWindow(), switchToPrevWindow(), and switchToPrevWindowInContext().
Referenced by KviFrame().
KviMenuBar* KviFrame::mainMenuBar () [inline]
KviStatusBar* KviFrame::mainStatusBar () [inline]
Referenced by KviKvsCoreFunctions::KVSCF(), and KviMenuBar::setupSettingsPopup().
void KviFrame::maximizeWindow (void) [protected, slot]
References g_pActiveWindow, KviWindow::isMaximized(), KviWindow::maximize(), and KviWindow::restore().
Referenced by installAccelerators().
KviMdiManager* KviFrame::mdiManager () [inline]
Referenced by KviMenuBar::KviMenuBar(), KviUserListViewArea::paintEvent(), KviThemedTreeWidget::paintEvent(), KviThemedLineEdit::paintEvent(), KviThemedLabel::paintEvent(), KviThemedComboBox::paintEvent(), KviIrcView::paintEvent(), KviToolBarGraphicalApplet::paintEvent(), KviInputEditor::paintEvent(), and register_core_actions().
void KviFrame::minimizeWindow (void) [protected, slot]
References g_pActiveWindow, and KviWindow::minimize().
Referenced by installAccelerators().
KviMexToolBar * KviFrame::moduleExtensionToolBar (int extensionId)
References KviPointerList< T >::first(), m_pModuleExtensionToolBarList, and KviPointerList< T >::next().
Referenced by fillToolBarsPopup(), and toolbarsPopupSelected().
void KviFrame::moveEvent (QMoveEvent * e) [protected, virtual]
References KVI_OPTION_RECT, KviOption_rectFrameGeometry, and updatePseudoTransparency().
void KviFrame::newConsole () [slot]
References createNewConsole().
void KviFrame::recreateWindowList () [protected]
References createWindowList(), KviWindow::createWindowListItem(), KviWindow::destroyWindowListItem(), KviPointerList< T >::first(), g_pActiveWindow, m_pWindowList, m_pWinList, KviPointerList< T >::next(), KviWindowListBase::setActiveItem(), and KviWindow::windowListItem().
Referenced by KviApp::optionResetUpdate().
void KviFrame::registerModuleExtensionToolBar (KviMexToolBar * t) [protected]
References KviPointerList< T >::append(), and m_pModuleExtensionToolBarList.
Referenced by KviMexToolBar::KviMexToolBar().
void KviFrame::resizeEvent (QResizeEvent * e) [protected, virtual]
References KVI_OPTION_RECT, and KviOption_rectFrameGeometry.
void KviFrame::restoreModuleExtensionToolBars () [protected]
References KviModuleExtensionManager::allocateExtension(), firstConsole(), g_pModuleExtensionManager, KVI_OPTION_STRINGLIST, and KviOption_stringlistModuleExtensionToolbars.
Referenced by createNewConsole().
void KviFrame::restoreToolBarPositions () [private]
References KviApp::Config, g_pApp, KviApp::getLocalKvircDirectory(), KVI_CONFIGFILE_TOOLBARS, and m_pWindowList.
Referenced by createNewConsole().
void KviFrame::saveModuleExtensionToolBars () [protected]
References KviPointerList< T >::first(), KVI_OPTION_STRINGLIST, KviOption_stringlistModuleExtensionToolbars, m_pModuleExtensionToolBarList, KviPointerList< T >::next(), and s.
Referenced by ~KviFrame().
void KviFrame::saveToolBarPositions () [private]
References KviApp::Config, g_pApp, KviApp::getLocalKvircDirectory(), and KVI_CONFIGFILE_TOOLBARS.
Referenced by ~KviFrame().
void KviFrame::saveWindowProperties (KviWindow * wnd, const QString & szSection)
References KviConfig::clearGroup(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfig::dict(), KviWindow::externalGeometry(), KviConfig::groupsCount(), KviWindow::isDocked(), KviWindow::isMaximized(), KviWindow::mdiParent(), KviWindow::saveProperties(), KviConfig::setGroup(), and KviConfig::writeEntry().
Referenced by closeWindow(), and KviWindow::savePropertiesAsDefault().
void KviFrame::setActiveWindow (KviWindow * wnd)
References KviWindow::delayedAutoRaise(), KviWindow::isMinimized(), m_pMdi, KviWindow::mdiParent(), KviWindow::restore(), and KviMdiManager::showAndActivate().
Referenced by KviWindow::dock(), KviTreeWindowListTreeWidget::mousePressEvent(), KviWindowListButton::mousePressEvent(), and KviWindowListBase::switchWindow().
void KviFrame::setDockExtension (KviDockExtension * e) [inline]
void KviFrame::setUsesBigPixmaps (bool bUse)
Sets the use of big pixmaps in toolbar.
Parameters:
bUse Whether to use big pixmaps in toolbars
Returns:
void
Reimplemented from KviTalMainWindow.
References KviPointerHashTableIterator< Key, T >::current(), KviPointerListIterator< T >::current(), d, KviCustomToolBarManager::instance(), and m_pModuleExtensionToolBarList.
Referenced by KviFrame(), KviToolBar::setBigIcons(), and KviToolBar::setSmallIcons().
void KviFrame::signalMaximizeMdiChildWindow (KviMdiChild * lpC) [signal]
QSplitter* KviFrame::splitter () [inline]
void KviFrame::switchToNextHighlightedWindow (void) [protected, slot]
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviFrame::switchToNextWindow (void) [protected, slot]
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by KviMdiManager::eventFilter(), and installAccelerators().
void KviFrame::switchToNextWindowInContext (void) [protected, slot]
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviFrame::switchToPrevHighlightedWindow (void) [protected, slot]
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviFrame::switchToPrevWindow (void) [protected, slot]
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by KviMdiManager::eventFilter(), and installAccelerators().
void KviFrame::switchToPrevWindowInContext (void) [protected, slot]
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviFrame::toggleStatusBar () [slot]
References KviStatusBar::load(), and m_pStatusBar.
void KviFrame::toolbarsPopupSelected (int id) [protected, slot]
References KviModuleExtensionManager::allocateExtension(), KviCustomToolBarDescriptor::createToolBar(), KviCustomToolBarManager::findDescriptorByInternalId(), firstConsole(), g_pModuleExtensionManager, KviCustomToolBarManager::instance(), moduleExtensionToolBar(), and KviCustomToolBarDescriptor::toolBar().
Referenced by fillToolBarsPopup().
void KviFrame::undockWindow (KviWindow * wnd) [protected]
References KviMdiManager::destroyChild(), m_pMdi, KviWindow::mdiParent(), KviWindow::setFocus(), KviMdiChild::unsetClient(), and KviWindow::youAreUndocked().
Referenced by KviWindow::undock().
void KviFrame::unhighlightWindowsOfContext (KviIrcContext * c) [protected]
References KviPointerList< T >::first(), m_pWinList, and KviPointerList< T >::next().
Referenced by KviIrcContext::unhighlightAllWindows().
void KviFrame::unregisterModuleExtensionToolBar (KviMexToolBar * t) [protected]
References m_pModuleExtensionToolBarList, and KviPointerList< T >::removeRef().
Referenced by KviMexToolBar::~KviMexToolBar().
void KviFrame::updatePseudoTransparency () [protected]
References KviPointerList< T >::first(), KVI_OPTION_UINT, KviOption_uintGlobalWindowOpacityPercent, m_pMdi, m_pWindowList, m_pWinList, KviPointerList< T >::next(), and KviWindowListBase::updatePseudoTransparency().
Referenced by moveEvent(), and KviApp::updatePseudoTransparency().
bool KviFrame::windowExists (KviWindow * wnd) [inline]
KviPointerList<KviWindow>* KviFrame::windowList () [inline]
KviWindowListBase* KviFrame::windowListWidget () [inline]
Friends And Related Function Documentation
friend class KviApp [friend]
friend class KviConsole [friend]
Referenced by createNewConsole().
friend class KviIrcConnection [friend]
friend class KviIrcContext [friend]
friend class KviLagMeter [friend]
friend class KviMdiManager [friend]
Referenced by KviFrame().
friend class KviMexToolBar [friend]
friend class KviServerParser [friend]
Referenced by KviApp::setup().
friend class KviUserListView [friend]
friend class KviUserListViewArea [friend]
friend class KviWindow [friend]
Member Data Documentation
KviIrcContext* KviFrame::m_pActiveContext [protected]
Referenced by activeConnection(), addWindow(), childConnectionAwayStateChange(), childConnectionLagChange(), childConnectionNickNameChange(), childConnectionServerInfoChange(), childConnectionUserModeChange(), childContextStateChange(), childWindowActivated(), closeWindow(), and KviFrame().
KviDockExtension* KviFrame::m_pDockExtension [protected]
Referenced by KviFrame(), and ~KviFrame().
KviMdiManager* KviFrame::m_pMdi [protected]
Referenced by addWindow(), applyOptions(), closeWindow(), dockWindow(), KviFrame(), setActiveWindow(), undockWindow(), updatePseudoTransparency(), and ~KviFrame().
KviMenuBar* KviFrame::m_pMenuBar [protected]
Referenced by KviFrame().
KviPointerList<KviMexToolBar>* KviFrame::m_pModuleExtensionToolBarList [protected]
Referenced by KviFrame(), moduleExtensionToolBar(), registerModuleExtensionToolBar(), saveModuleExtensionToolBars(), setUsesBigPixmaps(), unregisterModuleExtensionToolBar(), and ~KviFrame().
QSplitter* KviFrame::m_pSplitter [protected]
Referenced by KviFrame().
KviStatusBar* KviFrame::m_pStatusBar [protected]
Referenced by KviFrame(), toggleStatusBar(), and ~KviFrame().
KviWindowListBase* KviFrame::m_pWindowList [protected]
Referenced by applyOptions(), childWindowActivated(), createWindowList(), KviWindow::createWindowListItem(), KviWindow::destroyWindowListItem(), KviFrame(), recreateWindowList(), restoreToolBarPositions(), switchToNextHighlightedWindow(), switchToNextWindow(), switchToNextWindowInContext(), switchToPrevHighlightedWindow(), switchToPrevWindow(), switchToPrevWindowInContext(), and updatePseudoTransparency().
KviPointerList<KviWindow>* KviFrame::m_pWinList [protected]
Referenced by addWindow(), applyOptions(), closeEvent(), closeWindow(), consoleCount(), firstConsole(), firstNotConnectedConsole(), KviFrame(), recreateWindowList(), unhighlightWindowsOfContext(), updatePseudoTransparency(), and ~KviFrame().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_frame.h
src/kvirc/ui/kvi_frame.cpp