KVIrc: HelpWindow Class Reference
HelpWindow Class Reference
#include <HelpWindow.h>
Public Slots
void indexingEnd ()
void indexingProgress (int iNum)
void indexingStart (int iNum)
void indexSelected (QListWidgetItem *)
void initialSetup ()
void refreshIndex ()
void searchInIndex (const QString &s)
void searchSelected (QListWidgetItem *)
void showIndexTopic ()
void startSearch ()
Public Member Functions
HelpWidget * helpWidget ()
HelpWindow (KviMainWindow *lpFrm, const char *name)
QTextBrowser * textBrowser ()
~HelpWindow ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void loadProperties (KviConfigurationFile *cfg)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfigurationFile *cfg)
Protected Attributes
QStringList m_foundDocs
KviTalHBox * m_pBottomLayout
QPushButton * m_pBtnRefreshIndex
QPushButton * m_pCancelButton
HelpWidget * m_pHelpWidget
KviTalListWidget * m_pIndexListWidget
QLineEdit * m_pIndexSearch
KviTalVBox * m_pIndexTab
QProgressBar * m_pProgressBar
KviTalListWidget * m_pResultBox
KviTalVBox * m_pSearchTab
QTabWidget * m_pTabWidget
QLineEdit * m_pTermsEdit
KviTalVBox * m_pToolBar
QStringList m_terms
Constructor & Destructor Documentation
HelpWindow::HelpWindow (KviMainWindow * lpFrm, const char * name)
References __tr2qs, __tr2qs_ctx(), KviPointerList< T >::append(), connect(), g_pIconManager, KviIconManager::getBigIcon(), indexingEnd(), indexingProgress(), indexingStart(), indexSelected(), initialSetup(), KVI_REFRESH_IMAGE_NAME, KviTalSplitter, m_pBottomLayout, m_pBtnRefreshIndex, m_pCancelButton, m_pHelpWidget, m_pIndexListWidget, m_pIndexSearch, m_pIndexTab, m_pProgressBar, m_pResultBox, m_pSearchTab, KviWindow::m_pSplitter, m_pTabWidget, m_pTermsEdit, m_pToolBar, refreshIndex(), searchInIndex(), searchSelected(), showIndexTopic(), and startSearch().
HelpWindow::~HelpWindow ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void HelpWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs, and KviWindow::m_szPlainTextCaption.
HelpWidget* HelpWindow::helpWidget () [inline]
References m_pHelpWidget.
void HelpWindow::indexingEnd () [slot]
References m_pBottomLayout, m_pBtnRefreshIndex, m_pIndexListWidget, m_pProgressBar, HelpIndex::titlesList(), and HelpIndex::writeDict().
Referenced by HelpWindow().
void HelpWindow::indexingProgress (int iNum) [slot]
References m_pProgressBar.
Referenced by HelpWindow().
void HelpWindow::indexingStart (int iNum) [slot]
References m_pBottomLayout, m_pBtnRefreshIndex, and m_pProgressBar.
Referenced by HelpWindow().
void HelpWindow::indexSelected (QListWidgetItem * item) [slot]
References HelpIndex::documentList(), i, textBrowser(), and HelpIndex::titlesList().
Referenced by HelpWindow().
void HelpWindow::initialSetup () [slot]
References g_pApp, KviApplication::getLocalKvircDirectory(), KviApplication::Help, KVI_SOURCES_DATE, m_pBtnRefreshIndex, m_pIndexListWidget, m_pIndexSearch, HelpIndex::makeIndex(), HelpIndex::readDict(), and HelpIndex::titlesList().
Referenced by HelpWindow().
void HelpWindow::loadProperties (KviConfigurationFile * cfg) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, KviConfigurationFile::readIntListEntry(), and w.
QPixmap * HelpWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::MdiHelp.
void HelpWindow::refreshIndex () [slot]
References HelpIndex::makeIndex().
Referenced by HelpWindow().
void HelpWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviWindow::m_pSplitter.
void HelpWindow::saveProperties (KviConfigurationFile * cfg) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, and KviConfigurationFile::writeEntry().
void HelpWindow::searchInIndex (const QString & s) [slot]
References i, m_pIndexListWidget, and t.
Referenced by HelpWindow().
void HelpWindow::searchSelected (QListWidgetItem * item) [slot]
References HelpIndex::documentList(), i, textBrowser(), and HelpIndex::titlesList().
Referenced by HelpWindow().
void HelpWindow::showIndexTopic () [slot]
References HelpIndex::documentList(), i, m_pIndexListWidget, m_pIndexSearch, textBrowser(), and HelpIndex::titlesList().
Referenced by HelpWindow().
void HelpWindow::startSearch () [slot]
References HelpIndex::getDocumentTitle(), i, m_foundDocs, m_pResultBox, m_pTermsEdit, m_terms, HelpIndex::query(), s, and KviMessageBox::warning().
Referenced by HelpWindow().
QTextBrowser * HelpWindow::textBrowser ()
Referenced by help_kvs_cmd_open(), indexSelected(), searchSelected(), and showIndexTopic().
Member Data Documentation
QStringList HelpWindow::m_foundDocs [protected]
Referenced by startSearch().
KviTalHBox* HelpWindow::m_pBottomLayout [protected]
Referenced by HelpWindow(), indexingEnd(), and indexingStart().
QPushButton* HelpWindow::m_pBtnRefreshIndex [protected]
Referenced by HelpWindow(), indexingEnd(), indexingStart(), and initialSetup().
QPushButton* HelpWindow::m_pCancelButton [protected]
Referenced by HelpWindow().
HelpWidget* HelpWindow::m_pHelpWidget [protected]
Referenced by helpWidget(), and HelpWindow().
KviTalListWidget* HelpWindow::m_pIndexListWidget [protected]
Referenced by HelpWindow(), indexingEnd(), initialSetup(), searchInIndex(), and showIndexTopic().
QLineEdit* HelpWindow::m_pIndexSearch [protected]
Referenced by HelpWindow(), initialSetup(), and showIndexTopic().
KviTalVBox* HelpWindow::m_pIndexTab [protected]
Referenced by HelpWindow().
QProgressBar* HelpWindow::m_pProgressBar [protected]
Referenced by HelpWindow(), indexingEnd(), indexingProgress(), and indexingStart().
KviTalListWidget* HelpWindow::m_pResultBox [protected]
Referenced by HelpWindow(), and startSearch().
KviTalVBox* HelpWindow::m_pSearchTab [protected]
Referenced by HelpWindow().
QTabWidget* HelpWindow::m_pTabWidget [protected]
Referenced by HelpWindow().
QLineEdit* HelpWindow::m_pTermsEdit [protected]
Referenced by HelpWindow(), and startSearch().
KviTalVBox* HelpWindow::m_pToolBar [protected]
Referenced by HelpWindow().
QStringList HelpWindow::m_terms [protected]
Referenced by startSearch().
The documentation for this class was generated from the following files:
src/modules/help/HelpWindow.h
src/modules/help/HelpWindow.cpp