KVIrc: KviKvsScriptAddon Class Reference
KviKvsScriptAddon Class Reference
#include <KviKvsScriptAddonManager.h>
Public Member Functions
void addInstalledFile (const QString &szFileName)
const QString & configureCallbackCode ()
const QString & description ()
const QString & descriptionCode ()
void executeConfigureCallback (KviWindow *pWnd)
void executeHelpCallback (KviWindow *pWnd)
const QString & helpCallbackCode ()
QPixmap * icon ()
const QString & iconId ()
const QStringList & installedFiles () const
KviKvsScriptAddon (const KviKvsScriptAddon &a)
const QString & name () const
void setConfigureCallback (const QString &szConfigureCallbackCode)
void setHelpCallback (const QString &szHelpCallbackCode)
const QString & uninstallCallbackCode ()
const QString & version () const
const QString & visibleName ()
const QString & visibleNameCode ()
~KviKvsScriptAddon ()
Protected Member Functions
void allocateScripts (const QString &sVisibleNameCode, const QString &szDescriptionCode, const QString &szUninstallCallbackCode)
void executeUninstallCallback (KviWindow *pWnd)
KviKvsScriptAddon (const QString &szName, const QString &szVersion, const QString &szVisibleNameCode, const QString &szDescriptionCode, const QString &szUninstallCallbackCode, const QString &szIconId)
KviKvsScriptAddon ()
bool load (KviConfigurationFile *cfg, const QString &szName)
void save (KviConfigurationFile *cfg)
Protected Attributes
QStringList m_lInstalledFiles
KviKvsScript * m_pConfigureCallback
KviKvsScript * m_pDescriptionScript
KviKvsScript * m_pHelpCallback
KviKvsScript * m_pUninstallCallback
KviKvsScript * m_pVisibleNameScript
QString m_szDescription
QString m_szIconId
QString m_szName
QString m_szVersion
QString m_szVisibleName
Friends
class KviKvsScriptAddonManager
Constructor & Destructor Documentation
KviKvsScriptAddon::KviKvsScriptAddon () [protected]
References m_pConfigureCallback, m_pDescriptionScript, m_pHelpCallback, m_pUninstallCallback, and m_pVisibleNameScript.
KviKvsScriptAddon::KviKvsScriptAddon (const QString & szName, const QString & szVersion, const QString & szVisibleNameCode, const QString & szDescriptionCode, const QString & szUninstallCallbackCode, const QString & szIconId) [protected]
References allocateScripts(), m_pConfigureCallback, and m_pHelpCallback.
KviKvsScriptAddon::KviKvsScriptAddon (const KviKvsScriptAddon & a)
References allocateScripts(), KviKvsScript::code(), m_pConfigureCallback, m_pDescriptionScript, m_pHelpCallback, m_pUninstallCallback, m_pVisibleNameScript, m_szIconId, m_szName, m_szVersion, setConfigureCallback(), and setHelpCallback().
KviKvsScriptAddon::~KviKvsScriptAddon ()
References m_pConfigureCallback, m_pDescriptionScript, m_pHelpCallback, m_pUninstallCallback, and m_pVisibleNameScript.
Member Function Documentation
void KviKvsScriptAddon::addInstalledFile (const QString & szFileName)
Register a file to be uninstalled after the uninstall callback. The file name *MUST* be relative to the local kvirc directory.
References m_lInstalledFiles.
Referenced by addon_kvs_cmd_installfiles().
void KviKvsScriptAddon::allocateScripts (const QString & sVisibleNameCode, const QString & szDescriptionCode, const QString & szUninstallCallbackCode) [protected]
References KviKvsScript::InstructionList, KviKvsScript::KviKvsScript(), m_pDescriptionScript, m_pUninstallCallback, m_pVisibleNameScript, m_szName, and KviKvsScript::Parameter.
Referenced by KviKvsScriptAddon(), and load().
const QString & KviKvsScriptAddon::configureCallbackCode ()
References KviKvsScript::code(), KviQString::Empty, and m_pConfigureCallback.
Referenced by addon_kvs_cmd_configure(), AddonManagementDialog::configureScript(), AddonManagementDialog::currentChanged(), and save().
const QString & KviKvsScriptAddon::description ()
References KviKvsScript::code(), g_pActiveWindow, m_pDescriptionScript, m_szDescription, and KviKvsScript::run().
Referenced by AddonListViewItem::AddonListViewItem().
const QString & KviKvsScriptAddon::descriptionCode ()
References KviKvsScript::code(), and m_pDescriptionScript.
Referenced by save().
void KviKvsScriptAddon::executeConfigureCallback (KviWindow * pWnd)
References m_pConfigureCallback, and KviKvsScript::run().
Referenced by addon_kvs_cmd_configure(), and AddonManagementDialog::configureScript().
void KviKvsScriptAddon::executeHelpCallback (KviWindow * pWnd)
References m_pHelpCallback, and KviKvsScript::run().
Referenced by addon_kvs_cmd_help(), and AddonManagementDialog::showScriptHelp().
void KviKvsScriptAddon::executeUninstallCallback (KviWindow * pWnd) [protected]
References m_pUninstallCallback, and KviKvsScript::run().
Referenced by KviKvsScriptAddonManager::unregisterAddon().
const QString & KviKvsScriptAddon::helpCallbackCode ()
References KviKvsScript::code(), KviQString::Empty, and m_pHelpCallback.
Referenced by addon_kvs_cmd_help(), AddonManagementDialog::currentChanged(), save(), and AddonManagementDialog::showScriptHelp().
QPixmap * KviKvsScriptAddon::icon ()
References g_pIconManager, KviIconManager::getBigIcon(), KVI_BIGICON_KVS, and m_szIconId.
Referenced by AddonListViewItem::AddonListViewItem().
const QString& KviKvsScriptAddon::iconId () [inline]
const QStringList& KviKvsScriptAddon::installedFiles () const [inline]
Referenced by KviKvsScriptAddonManager::unregisterAddon().
bool KviKvsScriptAddon::load (KviConfigurationFile * cfg, const QString & szName) [protected]
References allocateScripts(), m_lInstalledFiles, m_szIconId, m_szName, m_szVersion, KviConfigurationFile::readEntry(), KviConfigurationFile::readStringListEntry(), setConfigureCallback(), KviConfigurationFile::setGroup(), and setHelpCallback().
Referenced by KviKvsScriptAddonManager::delayedLoad().
const QString& KviKvsScriptAddon::name () const [inline]
Referenced by AddonListViewItem::AddonListViewItem(), and AddonManagementDialog::uninstallScript().
void KviKvsScriptAddon::save (KviConfigurationFile * cfg) [protected]
References configureCallbackCode(), descriptionCode(), helpCallbackCode(), m_lInstalledFiles, m_szIconId, m_szName, m_szVersion, KviConfigurationFile::setGroup(), uninstallCallbackCode(), visibleNameCode(), and KviConfigurationFile::writeEntry().
void KviKvsScriptAddon::setConfigureCallback (const QString & szConfigureCallbackCode)
References KviKvsScript::InstructionList, KviKvsScript::KviKvsScript(), m_pConfigureCallback, and m_szName.
Referenced by addon_kvs_cmd_setconfigurecallback(), KviKvsScriptAddon(), and load().
void KviKvsScriptAddon::setHelpCallback (const QString & szHelpCallbackCode)
References KviKvsScript::InstructionList, KviKvsScript::KviKvsScript(), m_pHelpCallback, and m_szName.
Referenced by addon_kvs_cmd_sethelpcallback(), KviKvsScriptAddon(), and load().
const QString & KviKvsScriptAddon::uninstallCallbackCode ()
References KviKvsScript::code(), and m_pUninstallCallback.
Referenced by save().
const QString& KviKvsScriptAddon::version () const [inline]
Referenced by addon_kvs_cmd_register(), addon_kvs_cmd_uninstall(), addon_kvs_fnc_exists(), addon_kvs_fnc_version(), and AddonListViewItem::AddonListViewItem().
const QString & KviKvsScriptAddon::visibleName ()
References KviKvsScript::code(), g_pActiveWindow, m_pVisibleNameScript, m_szVisibleName, and KviKvsScript::run().
Referenced by AddonListViewItem::AddonListViewItem(), and AddonManagementDialog::uninstallScript().
const QString & KviKvsScriptAddon::visibleNameCode ()
References KviKvsScript::code(), and m_pVisibleNameScript.
Referenced by save().
Friends And Related Function Documentation
friend class KviKvsScriptAddonManager [friend]
Member Data Documentation
QStringList KviKvsScriptAddon::m_lInstalledFiles [protected]
Referenced by addInstalledFile(), load(), and save().
KviKvsScript* KviKvsScriptAddon::m_pConfigureCallback [protected]
Referenced by configureCallbackCode(), executeConfigureCallback(), KviKvsScriptAddon(), setConfigureCallback(), and ~KviKvsScriptAddon().
KviKvsScript* KviKvsScriptAddon::m_pDescriptionScript [protected]
Referenced by allocateScripts(), description(), descriptionCode(), KviKvsScriptAddon(), and ~KviKvsScriptAddon().
KviKvsScript* KviKvsScriptAddon::m_pHelpCallback [protected]
Referenced by executeHelpCallback(), helpCallbackCode(), KviKvsScriptAddon(), setHelpCallback(), and ~KviKvsScriptAddon().
KviKvsScript* KviKvsScriptAddon::m_pUninstallCallback [protected]
Referenced by allocateScripts(), executeUninstallCallback(), KviKvsScriptAddon(), uninstallCallbackCode(), and ~KviKvsScriptAddon().
KviKvsScript* KviKvsScriptAddon::m_pVisibleNameScript [protected]
Referenced by allocateScripts(), KviKvsScriptAddon(), visibleName(), visibleNameCode(), and ~KviKvsScriptAddon().
QString KviKvsScriptAddon::m_szDescription [protected]
Referenced by description().
QString KviKvsScriptAddon::m_szIconId [protected]
Referenced by icon(), KviKvsScriptAddon(), load(), and save().
QString KviKvsScriptAddon::m_szName [protected]
Referenced by allocateScripts(), KviKvsScriptAddon(), load(), save(), setConfigureCallback(), and setHelpCallback().
QString KviKvsScriptAddon::m_szVersion [protected]
Referenced by KviKvsScriptAddon(), load(), and save().
QString KviKvsScriptAddon::m_szVisibleName [protected]
Referenced by visibleName().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsScriptAddonManager.h
src/kvirc/kvs/KviKvsScriptAddonManager.cpp