KVIrc: KviSharedFilesManager Class Reference
KviSharedFilesManager Class Reference
#include <KviSharedFilesManager.h>
Signals
void sharedFileAdded (KviSharedFile *f)
void sharedFileRemoved (KviSharedFile *f)
void sharedFilesChanged ()
Public Member Functions
void addSharedFile (KviSharedFile *f)
KviSharedFile * addSharedFile (const QString &szName, const QString &szAbsPath, const QString &szMask, int timeoutInSecs)
void clear ()
KviSharedFilesManager ()
void load (const QString &filename)
KviSharedFile * lookupSharedFile (const QString &szName, KviIrcMask *mask, unsigned int uFileSize=0)
bool removeSharedFile (const QString &szName, KviSharedFile *off)
bool removeSharedFile (const QString &szName, const QString &szMask, unsigned int uFileSize)
void save (const QString &filename)
KviPointerHashTable< QString,
KviSharedFileList > * sharedFileListDict ()
~KviSharedFilesManager ()
Private Slots
void cleanup ()
Private Member Functions
void doInsert (KviSharedFileList *l, KviSharedFile *o)
Private Attributes
QTimer * m_pCleanupTimer
KviPointerHashTable< QString,
KviSharedFileList > * m_pSharedListDict
Constructor & Destructor Documentation
KviSharedFilesManager::KviSharedFilesManager ()
References cleanup(), connect(), m_pCleanupTimer, m_pSharedListDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviSharedFilesManager::~KviSharedFilesManager ()
References m_pCleanupTimer, and m_pSharedListDict.
Member Function Documentation
void KviSharedFilesManager::addSharedFile (KviSharedFile * f)
References doInsert(), KviSharedFile::expireTime(), KviPointerHashTable< Key, T >::find(), l, m_pCleanupTimer, m_pSharedListDict, KviSharedFile::name(), KviPointerHashTable< Key, T >::replace(), KviPointerList< T >::setAutoDelete(), and sharedFileAdded().
Referenced by SharedFilesWindow::addClicked(), avatar_kvs_cmd_notify(), dccModuleParseDccGet(), SharedFilesWindow::editClicked(), load(), KviIrcServerParser::parseCtcpRequestAvatar(), DccBroker::rsendExecute(), and sharedfile_kvs_cmd_add().
KviSharedFile * KviSharedFilesManager::addSharedFile (const QString & szName, const QString & szAbsPath, const QString & szMask, int timeoutInSecs)
References doInsert(), KviSharedFile::expireTime(), KviPointerHashTable< Key, T >::find(), l, m_pCleanupTimer, m_pSharedListDict, o, KviPointerHashTable< Key, T >::replace(), KviPointerList< T >::setAutoDelete(), and sharedFileAdded().
void KviSharedFilesManager::cleanup () [private, slot]
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviPointerList< T >::first(), l, m_pCleanupTimer, m_pSharedListDict, KviPointerList< T >::next(), o, KviPointerHashTable< Key, T >::remove(), KviPointerList< T >::setAutoDelete(), and sharedFileRemoved().
Referenced by KviSharedFilesManager().
void KviSharedFilesManager::clear ()
References KviPointerHashTable< Key, T >::clear(), m_pSharedListDict, and sharedFilesChanged().
Referenced by sharedfile_kvs_cmd_clear().
void KviSharedFilesManager::doInsert (KviSharedFileList * l, KviSharedFile * o) [private]
References KviPointerList< T >::append(), KviPointerList< T >::first(), KviPointerList< T >::insert(), KviSharedFile::maskLength(), KviPointerList< T >::next(), KviSharedFile::nonWildcardCount(), and KviSharedFile::wildcardCount().
Referenced by addSharedFile().
void KviSharedFilesManager::load (const QString & filename)
References addSharedFile(), i, KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviConfigurationFile::readIntEntry(), and KviConfigurationFile::setGroup().
Referenced by KviApplication::setup().
KviSharedFile * KviSharedFilesManager::lookupSharedFile (const QString & szName, KviIrcMask * mask, unsigned int uFileSize = 0)
References KviQString::equalCS(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), l, m_pSharedListDict, KviIrcMask::matchedBy(), KviPointerList< T >::next(), and o.
Referenced by avatar_kvs_cmd_notify(), dccModuleParseDccGet(), and dccModuleParseDccRecv().
bool KviSharedFilesManager::removeSharedFile (const QString & szName, const QString & szMask, unsigned int uFileSize)
References KviPointerList< T >::count(), KviQString::equalCI(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), l, m_pSharedListDict, KviPointerList< T >::next(), o, KviPointerHashTable< Key, T >::remove(), KviPointerList< T >::removeRef(), save(), and sharedFileRemoved().
Referenced by SharedFilesWindow::editClicked(), SharedFilesWindow::removeClicked(), and sharedfile_kvs_cmd_remove().
bool KviSharedFilesManager::removeSharedFile (const QString & szName, KviSharedFile * off)
References KviPointerList< T >::count(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), l, m_pSharedListDict, KviPointerList< T >::next(), o, KviPointerHashTable< Key, T >::remove(), KviPointerList< T >::removeRef(), save(), and sharedFileRemoved().
void KviSharedFilesManager::save (const QString & filename)
References KviConfigurationFile::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), i, m_pSharedListDict, KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by removeSharedFile(), and KviApplication::saveSharedFiles().
void KviSharedFilesManager::sharedFileAdded (KviSharedFile * f) [signal]
Referenced by addSharedFile().
KviPointerHashTable<QString,KviSharedFileList>* KviSharedFilesManager::sharedFileListDict () [inline]
Referenced by SharedFilesWindow::fillFileView(), and sharedfile_kvs_cmd_list().
void KviSharedFilesManager::sharedFileRemoved (KviSharedFile * f) [signal]
Referenced by cleanup(), and removeSharedFile().
void KviSharedFilesManager::sharedFilesChanged () [signal]
Referenced by clear().
Member Data Documentation
QTimer* KviSharedFilesManager::m_pCleanupTimer [private]
Referenced by addSharedFile(), cleanup(), KviSharedFilesManager(), and ~KviSharedFilesManager().
KviPointerHashTable<QString,KviSharedFileList>* KviSharedFilesManager::m_pSharedListDict [private]
Referenced by addSharedFile(), cleanup(), clear(), KviSharedFilesManager(), lookupSharedFile(), removeSharedFile(), save(), and ~KviSharedFilesManager().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviSharedFilesManager.h
src/kvilib/ext/KviSharedFilesManager.cpp