KVIrc: KviGoAwayAction Class Reference
KviGoAwayAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
virtual QWidget * addToCustomToolBar (KviCustomToolBar *pTool)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (KviTalPopupMenu *pMenu)
Adds the action to the given popup.
KviGoAwayAction (QObject *pParent)
Protected Member Functions
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual void reloadImages ()
Reloads the images.
virtual void setup ()
Enables or disables the action upon starting KVIrc.
Protected Attributes
QString m_szAwayString
QString m_szBackString
Constructor & Destructor Documentation
KviGoAwayAction::KviGoAwayAction (QObject * pParent)
Member Function Documentation
void KviGoAwayAction::activeContextChanged () [protected, virtual]
Enables or disables the action upon checking the active context.
If the context doesn't exist, the action is disabled
Called when the frame changes the active context.
Note:
It works only if NeedsContext is specified
Returns:
void
Reimplemented from KviAction.
References activeContextStateChanged().
void KviGoAwayAction::activeContextStateChanged () [protected, virtual]
Enables or disables the action upon checking the active context.
Called when the frame changes the state of the context
Returns:
void
Reimplemented from KviAction.
References KviMainWindow::activeContext(), c, KviIrcContext::Connected, KviIrcContext::connection(), KviAction::Enabled, KviPointerList< T >::first(), g_pIconManager, g_pMainWindow, KviIconManager::getBigIcon(), KviIrcConnectionUserInfo::isAway(), m_szAwayString, m_szBackString, KviAction::m_uInternalFlags, KviPointerList< T >::next(), p, KviAction::setEnabled(), KviIrcContext::state(), KviIrcConnection::userInfo(), and KviAction::widgetList().
Referenced by activeContextChanged(), addToCustomToolBar(), reloadImages(), and setup().
QWidget * KviGoAwayAction::addToCustomToolBar (KviCustomToolBar * pParentToolBar) [virtual]
Adds the action to the given toolbar.
Parameters:
pParentToolBar The toolbar where to add the action
Returns:
QWidget *
Reimplemented from KviAction.
References KviKvsAction::activate(), activeContextStateChanged(), connect(), g_pIconManager, KviIconManager::getBigIcon(), m_szAwayString, KviAction::name(), KviAction::registerWidget(), setup(), and KviAction::setupDone().
bool KviGoAwayAction::addToPopupMenu (KviTalPopupMenu * pMenu) [virtual]
Adds the action to the given popup.
Parameters:
pMenu The menu where to add the action
Returns:
bool
Reimplemented from KviAction.
References KviKvsAction::activate(), KviMainWindow::activeContext(), KviIconManager::Away, c, KviIrcContext::Connected, KviIrcContext::connection(), g_pIconManager, g_pMainWindow, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviIrcConnectionUserInfo::isAway(), m_szAwayString, m_szBackString, KviAction::m_szKeySequence, KviIconManager::NotAway, KviTalPopupMenu::setItemEnabled(), setup(), KviAction::setupDone(), KviIrcContext::state(), t, and KviIrcConnection::userInfo().
void KviGoAwayAction::reloadImages () [protected, virtual]
Reloads the images.
Called when the application wants to refresh the images in the toolbar
Returns:
void
Reimplemented from KviAction.
References activeContextStateChanged().
void KviGoAwayAction::setup () [protected, virtual]
Enables or disables the action upon starting KVIrc.
Returns:
void
Reimplemented from KviAction.
References __tr2qs, activeContextStateChanged(), connect(), g_pMainWindow, m_szAwayString, and m_szBackString.
Referenced by addToCustomToolBar(), and addToPopupMenu().
Member Data Documentation
QString KviGoAwayAction::m_szAwayString [protected]
Referenced by activeContextStateChanged(), addToCustomToolBar(), addToPopupMenu(), and setup().
QString KviGoAwayAction::m_szBackString [protected]
Referenced by activeContextStateChanged(), addToPopupMenu(), and setup().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp