KVIrc: KviToolBarGraphicalApplet Class Reference
KviToolBarGraphicalApplet Class Reference
#include <KviIrcToolBar.h>
Public Member Functions
KviToolBarGraphicalApplet (QWidget *par, const char *name=0)
~KviToolBarGraphicalApplet ()
Protected Member Functions
virtual void drawContents (QPainter *p)
virtual unsigned int loadAppletWidth ()
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
virtual void resizeEvent (QResizeEvent *e)
virtual void saveAppletWidth (unsigned int uWidth)
void setupSizeHint ()
virtual QSize sizeHint () const
Private Member Functions
void resizeMemBuffer ()
Private Attributes
bool m_bResizeMode
bool m_bSizeLoaded
QSize m_sizeHint
Constructor & Destructor Documentation
KviToolBarGraphicalApplet::KviToolBarGraphicalApplet (QWidget * par, const char * name = 0)
References KviPointerList< T >::append(), g_pIccMemBuffer, m_bResizeMode, m_bSizeLoaded, m_sizeHint, and KviPointerList< T >::setAutoDelete().
KviToolBarGraphicalApplet::~KviToolBarGraphicalApplet ()
References g_pIccMemBuffer, g_pToolBarGraphicalAppletList, KviPointerList< T >::isEmpty(), m_sizeHint, KviPointerList< T >::removeRef(), resizeMemBuffer(), and saveAppletWidth().
Member Function Documentation
void KviToolBarGraphicalApplet::drawContents (QPainter * p) [protected, virtual]
Reimplemented in KviIrcContextDisplay.
Referenced by paintEvent().
unsigned int KviToolBarGraphicalApplet::loadAppletWidth () [protected, virtual]
References KVI_OPTION_UINT, and KviOption_uintIrcContextAppletWidth.
Referenced by setupSizeHint().
void KviToolBarGraphicalApplet::mouseMoveEvent (QMouseEvent * e) [protected, virtual]
References g_pApp, m_bResizeMode, m_sizeHint, and w.
void KviToolBarGraphicalApplet::mousePressEvent (QMouseEvent * e) [protected, virtual]
References m_bResizeMode.
void KviToolBarGraphicalApplet::mouseReleaseEvent (QMouseEvent * e) [protected, virtual]
References m_bResizeMode.
void KviToolBarGraphicalApplet::paintEvent (QPaintEvent * e) [protected, virtual]
References drawContents(), KviPixmapUtils::drawPixmapWithPainter(), g_pApp, g_pIccMemBuffer, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorIrcToolBarAppletBackground, KviOption_pixmapIrcToolBarAppletBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviMainWindow::mdiManager(), KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
void KviToolBarGraphicalApplet::resizeEvent (QResizeEvent * e) [protected, virtual]
References g_pIccMemBuffer, and resizeMemBuffer().
void KviToolBarGraphicalApplet::resizeMemBuffer () [private]
References a, KviPointerList< T >::first(), g_pIccMemBuffer, and KviPointerList< T >::next().
Referenced by resizeEvent(), and ~KviToolBarGraphicalApplet().
void KviToolBarGraphicalApplet::saveAppletWidth (unsigned int uWidth) [protected, virtual]
References KVI_OPTION_UINT, and KviOption_uintIrcContextAppletWidth.
Referenced by ~KviToolBarGraphicalApplet().
void KviToolBarGraphicalApplet::setupSizeHint () [protected]
References loadAppletWidth(), m_bSizeLoaded, and m_sizeHint.
Referenced by sizeHint().
QSize KviToolBarGraphicalApplet::sizeHint () const [protected, virtual]
References m_bSizeLoaded, m_sizeHint, and setupSizeHint().
Member Data Documentation
bool KviToolBarGraphicalApplet::m_bResizeMode [private]
Referenced by KviToolBarGraphicalApplet(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool KviToolBarGraphicalApplet::m_bSizeLoaded [private]
Referenced by KviToolBarGraphicalApplet(), setupSizeHint(), and sizeHint().
QSize KviToolBarGraphicalApplet::m_sizeHint [private]
Referenced by KviToolBarGraphicalApplet(), mouseMoveEvent(), setupSizeHint(), sizeHint(), and ~KviToolBarGraphicalApplet().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviIrcToolBar.h
src/kvirc/ui/KviIrcToolBar.cpp