KVIrc: KviKvsTreeNodeMultipleParameterIdentifier Class Reference
KviKvsTreeNodeMultipleParameterIdentifier Class Reference
#include <kvi_kvs_treenode_multipleparameteridentifier.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeMultipleParameterIdentifier (const QChar *pLocation, int iStart, int iEnd)
~KviKvsTreeNodeMultipleParameterIdentifier ()
Protected Attributes
int m_iEnd
int m_iStart
Constructor & Destructor Documentation
KviKvsTreeNodeMultipleParameterIdentifier::KviKvsTreeNodeMultipleParameterIdentifier (const QChar * pLocation, int iStart, int iEnd)
References m_iEnd, and m_iStart.
KviKvsTreeNodeMultipleParameterIdentifier::~KviKvsTreeNodeMultipleParameterIdentifier ()
Member Function Documentation
void KviKvsTreeNodeMultipleParameterIdentifier::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviQString::appendFormatted(), m_iEnd, and m_iStart.
void KviKvsTreeNodeMultipleParameterIdentifier::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References debug, m_iEnd, and m_iStart.
bool KviKvsTreeNodeMultipleParameterIdentifier::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::appendAsString(), KviKvsVariant::asString(), KviKvsVariantList::at(), m_iEnd, m_iStart, KviKvsVariantList::next(), KviKvsRunTimeContext::parameterList(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Member Data Documentation
int KviKvsTreeNodeMultipleParameterIdentifier::m_iEnd [protected]
Referenced by contextDescription(), dump(), evaluateReadOnly(), and KviKvsTreeNodeMultipleParameterIdentifier().
int KviKvsTreeNodeMultipleParameterIdentifier::m_iStart [protected]
Referenced by contextDescription(), dump(), evaluateReadOnly(), and KviKvsTreeNodeMultipleParameterIdentifier().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_multipleparameteridentifier.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_multipleparameteridentifier.cpp