KVIrc: OptionsWidget_notify Class Reference
OptionsWidget_notify Class Reference
#include <OptionsWidget_notify.h>
Public Member Functions
OptionsWidget_notify (QWidget *parent)
~OptionsWidget_notify ()
Constructor & Destructor Documentation
OptionsWidget_notify::OptionsWidget_notify (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolFlashWindowOnNotifyOnLine, KviOption_boolNotifyListChangesToActiveWindow, KviOption_boolNotifyListSendUserhostForOnlineUsers, KviOption_boolPopupNotifierOnNotifyOnLine, KviOption_boolUseIntelligentNotifyListManager, KviOption_boolUseNotifyList, KviOption_boolUseWatchListIfAvailable, KviOption_uintNotifyListCheckTimeInSecs, KviOption_uintNotifyListIsOnDelayTimeInSecs, and KviOption_uintNotifyListUserhostDelayTimeInSecs.
OptionsWidget_notify::~OptionsWidget_notify ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_notify.h
src/modules/options/OptionsWidget_notify.cpp