KVIrc: OptionsWidget_textIcons Class Reference
OptionsWidget_textIcons Class Reference
#include <OptionsWidget_textIcons.h>
Public Member Functions
virtual void commit ()
OptionsWidget_textIcons (QWidget *parent)
~OptionsWidget_textIcons ()
Public Member Functions inherited from KviOptionsWidget
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
QPushButton * addPushButton (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void addClicked ()
void chooseFromFile ()
void currentItemChanged (QTableWidgetItem *cur, QTableWidgetItem *prev)
void delClicked ()
void doPopup ()
void iconSelected (KviIconManager::SmallIcon)
void itemSelectionChanged ()
void restoreClicked ()
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
Protected Attributes
int m_iLastEditedRow
QPushButton * m_pAdd
QToolButton * m_pCurrentIconButton
TextIconTableItem * m_pCurrentItem
QPushButton * m_pDel
QMenu * m_pPopup
QPushButton * m_pRestore
QTableWidget * m_pTable
Private Member Functions
void fillTable ()
Additional Inherited Members
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_textIcons::OptionsWidget_textIcons (QWidget * parent)
References __tr2qs_ctx(), addClicked(), connect(), KviOptionsWidget::createLayout(), currentItemChanged(), delClicked(), fillTable(), itemSelectionChanged(), KviOptionsWidget::layout(), m_iLastEditedRow, m_pAdd, m_pCurrentIconButton, m_pDel, m_pPopup, m_pRestore, m_pTable, KviOptionsWidget::mergeTip(), and restoreClicked().
OptionsWidget_textIcons::~OptionsWidget_textIcons () default
Member Function Documentation
void OptionsWidget_textIcons::addClicked () protected slot
References __tr2qs_ctx(), m_pDel, and m_pTable.
Referenced by OptionsWidget_textIcons().
void OptionsWidget_textIcons::chooseFromFile () protected slot
References __tr2qs_ctx(), KviFileDialog::askForOpenFileName(), KviFileUtils::copyFile(), KviFileUtils::directoryExists(), g_pApp, g_pIconManager, KviApplication::getLocalKvircDirectory(), KviIconManager::getPixmap(), TextIconTableItem::icon(), KVI_FILTER_IMAGE, KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, m_pCurrentIconButton, m_pCurrentItem, KviFileUtils::makeDir(), p, KviTextIcon::pixmap(), KviTextIcon::setFilename(), and KviApplication::Themes.
Referenced by currentItemChanged(), and iconSelected().
void OptionsWidget_textIcons::commit (void) virtual
Reimplemented from KviOptionsWidget.
References KviTextIconManager::clear(), KviOptionsWidget::commit(), g_pTextIconManager, i, TextIconTableItem::icon(), KviTextIconManager::insert(), j, m_pTable, n, and KviTextIconManager::save().
void OptionsWidget_textIcons::currentItemChanged (QTableWidgetItem * cur, QTableWidgetItem * prev) protected slot
References __tr2qs, chooseFromFile(), connect(), doPopup(), m_iLastEditedRow, m_pCurrentIconButton, m_pCurrentItem, m_pTable, KviTalHBox::setMargin(), and KviTalHBox::setSpacing().
Referenced by OptionsWidget_textIcons().
void OptionsWidget_textIcons::delClicked () protected slot
References i, m_pDel, and m_pTable.
Referenced by OptionsWidget_textIcons().
void OptionsWidget_textIcons::doPopup () protected slot
References connect(), iconSelected(), KviIconWidget, and m_pPopup.
Referenced by currentItemChanged(), and iconSelected().
void OptionsWidget_textIcons::fillTable () private
References __tr2qs, KviPointerHashTable< Key, T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), g_pTextIconManager, i, m_pDel, m_pTable, and KviTextIconManager::textIconDict().
Referenced by OptionsWidget_textIcons(), and restoreClicked().
void OptionsWidget_textIcons::iconSelected (KviIconManager::SmallIcon eIcon) protected slot
References __tr2qs, chooseFromFile(), connect(), doPopup(), TextIconTableItem::icon(), m_pCurrentIconButton, m_pCurrentItem, m_pTable, KviTextIcon::pixmap(), KviTextIcon::setId(), KviTalHBox::setMargin(), and KviTalHBox::setSpacing().
Referenced by doPopup().
void OptionsWidget_textIcons::itemSelectionChanged () protected slot
References i, m_pDel, and m_pTable.
Referenced by OptionsWidget_textIcons().
void OptionsWidget_textIcons::restoreClicked () protected slot
References KviTextIconManager::checkDefaultAssociations(), fillTable(), and g_pTextIconManager.
Referenced by OptionsWidget_textIcons().
Member Data Documentation
int OptionsWidget_textIcons::m_iLastEditedRow protected
Referenced by currentItemChanged(), and OptionsWidget_textIcons().
QPushButton* OptionsWidget_textIcons::m_pAdd protected
Referenced by OptionsWidget_textIcons().
QToolButton* OptionsWidget_textIcons::m_pCurrentIconButton protected
Referenced by chooseFromFile(), currentItemChanged(), iconSelected(), and OptionsWidget_textIcons().
TextIconTableItem* OptionsWidget_textIcons::m_pCurrentItem protected
Referenced by chooseFromFile(), currentItemChanged(), and iconSelected().
QPushButton* OptionsWidget_textIcons::m_pDel protected
Referenced by addClicked(), delClicked(), fillTable(), itemSelectionChanged(), and OptionsWidget_textIcons().
QMenu* OptionsWidget_textIcons::m_pPopup protected
Referenced by doPopup(), and OptionsWidget_textIcons().
QPushButton* OptionsWidget_textIcons::m_pRestore protected
Referenced by OptionsWidget_textIcons().
QTableWidget* OptionsWidget_textIcons::m_pTable protected
Referenced by addClicked(), commit(), currentItemChanged(), delClicked(), fillTable(), iconSelected(), itemSelectionChanged(), and OptionsWidget_textIcons().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_textIcons.h
src/modules/options/OptionsWidget_textIcons.cpp