KVIrc: KviClassicWindowList Class Reference
KviClassicWindowList Class Reference
#include <KviWindowListBase.h>
Public Member Functions
virtual KviWindowListItem * addItem (KviWindow *)
virtual void applyOptions ()
virtual KviWindowListItem * firstItem ()
KviClassicWindowList ()
virtual KviWindowListItem * lastItem (void)
virtual KviWindowListItem * nextItem ()
virtual KviWindowListItem * prevItem (void)
virtual bool removeItem (KviWindowListItem *)
virtual void resizeEvent (QResizeEvent *e)
virtual void setActiveItem (KviWindowListItem *)
virtual bool setIterationPointer (KviWindowListItem *it)
virtual void updateActivityMeter ()
~KviClassicWindowList ()
Public Member Functions inherited from KviWindowListBase
Qt::DockWidgetArea currentDockArea ()
virtual KviWindowListItem * item (int number)
KviWindowListBase ()
virtual void switchWindow (bool bNext, bool bInContextOnly, bool bHighlightedOnly=false)
virtual void updatePseudoTransparency ()
virtual void wheelEvent (QWheelEvent *e)
virtual ~KviWindowListBase ()
Protected Slots
void doLayout ()
void orientationChangedSlot (Qt::Orientation o)
Protected Slots inherited from KviWindowListBase
void updateDockLocation (Qt::DockWidgetArea newArea)
Protected Member Functions
void calcButtonHeight ()
void insertButton (KviWindowListButton *b)
Protected Attributes
int m_iButtonHeight
QWidget * m_pBase
KviPointerList
< KviWindowListButton > * m_pButtonList
Protected Attributes inherited from KviWindowListBase
Qt::DockWidgetArea currentArea
QTimer * m_pActivityMeterTimer
KviMainWindow * m_pFrm
QWidget * m_pTitleWidget
Additional Inherited Members
Static Public Member Functions inherited from KviWindowListBase
static void getTextForConsole (QString &szText, KviConsoleWindow *pConsole)
Constructor & Destructor Documentation
KviClassicWindowList::KviClassicWindowList ()
References applyOptions(), calcButtonHeight(), doLayout(), KVI_OPTION_FONT, KVI_WINDOWLIST_MIN_WIDTH, KviOption_fontWindowList, m_iButtonHeight, m_pBase, m_pButtonList, and KviPointerList< T >::setAutoDelete().
KviClassicWindowList::~KviClassicWindowList ()
References m_pButtonList.
Member Function Documentation
KviWindowListItem * KviClassicWindowList::addItem (KviWindow * wnd) virtual
Reimplemented from KviWindowListBase.
References doLayout(), g_pMainWindow, insertButton(), m_pBase, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
void KviClassicWindowList::applyOptions () virtual
Reimplemented from KviWindowListBase.
References KviWindowListBase::applyOptions(), calcButtonHeight(), and doLayout().
Referenced by KviClassicWindowList().
void KviClassicWindowList::calcButtonHeight () protected
References KVI_OPTION_BOOL, KVI_WINDOWLISTBUTTON_BOTTOM_MARGIN, KVI_WINDOWLISTBUTTON_CONTEXTINDICATORHEIGHT, KVI_WINDOWLISTBUTTON_CONTEXTINDICATORSPACING, KVI_WINDOWLISTBUTTON_TOP_MARGIN, KviOption_boolUseWindowListIrcContextIndicator, and m_iButtonHeight.
Referenced by applyOptions(), and KviClassicWindowList().
void KviClassicWindowList::doLayout () protected slot
References KviPointerList< T >::count(), f, KviBuildInfo::features(), KviPointerList< T >::first(), g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolClassicWindowListSetMaximumButtonWidth, KviOption_uintClassicWindowListMaximumButtonWidth, KviOption_uintWindowListButtonMinWidth, m_iButtonHeight, m_pBase, m_pButtonList, and KviPointerList< T >::next().
Referenced by addItem(), applyOptions(), KviClassicWindowList(), orientationChangedSlot(), removeItem(), and resizeEvent().
KviWindowListItem * KviClassicWindowList::firstItem () virtual
Reimplemented from KviWindowListBase.
References KviPointerList< T >::first(), and m_pButtonList.
void KviClassicWindowList::insertButton (KviWindowListButton * b) protected
References KviPointerList< T >::append(), KviWindow::console(), KviPointerList< T >::first(), KviPointerList< T >::insert(), KVI_ASSERT, KVI_OPTION_BOOL, KviOption_boolSortWindowListItemsByName, KviWindowListItem::kviWindow(), m_pButtonList, KviPointerList< T >::next(), KviWindow::type(), and KviWindow::windowName().
Referenced by addItem().
KviWindowListItem * KviClassicWindowList::lastItem (void) virtual
Reimplemented from KviWindowListBase.
References KviPointerList< T >::last(), and m_pButtonList.
KviWindowListItem * KviClassicWindowList::nextItem (void) virtual
Reimplemented from KviWindowListBase.
References m_pButtonList, and KviPointerList< T >::next().
void KviClassicWindowList::orientationChangedSlot (Qt::Orientation o) protected slot
References doLayout().
KviWindowListItem * KviClassicWindowList::prevItem (void) virtual
Reimplemented from KviWindowListBase.
References m_pButtonList, and KviPointerList< T >::prev().
bool KviClassicWindowList::removeItem (KviWindowListItem * it) virtual
Reimplemented from KviWindowListBase.
References doLayout(), g_pMainWindow, m_pButtonList, KviTrayIcon::refresh(), KviPointerList< T >::removeRef(), and KviMainWindow::trayIcon().
void KviClassicWindowList::resizeEvent (QResizeEvent * e) virtual
References doLayout().
void KviClassicWindowList::setActiveItem (KviWindowListItem * it) virtual
Reimplemented from KviWindowListBase.
References KviPointerList< T >::first(), g_pMainWindow, m_pButtonList, KviPointerList< T >::next(), KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
bool KviClassicWindowList::setIterationPointer (KviWindowListItem * it) virtual
Reimplemented from KviWindowListBase.
References KviPointerList< T >::findRef(), and m_pButtonList.
void KviClassicWindowList::updateActivityMeter () virtual
Reimplemented from KviWindowListBase.
References KviPointerList< T >::first(), KVI_OPTION_BOOL, KviOption_boolUseWindowListActivityMeter, m_pButtonList, and KviPointerList< T >::next().
Member Data Documentation
int KviClassicWindowList::m_iButtonHeight protected
Referenced by calcButtonHeight(), doLayout(), and KviClassicWindowList().
QWidget* KviClassicWindowList::m_pBase protected
Referenced by addItem(), doLayout(), and KviClassicWindowList().
KviPointerList<KviWindowListButton>* KviClassicWindowList::m_pButtonList protected
Referenced by doLayout(), firstItem(), insertButton(), KviClassicWindowList(), lastItem(), nextItem(), prevItem(), removeItem(), setActiveItem(), setIterationPointer(), updateActivityMeter(), and ~KviClassicWindowList().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviWindowListBase.h
src/kvirc/ui/KviWindowListBase.cpp