KVIrc: KviKvsTreeNodeData Class Reference
KviKvsTreeNodeData Class Reference
#include <KviKvsTreeNodeData.h>
Public Member Functions
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual bool convertStringConstantToNumeric ()
virtual void dump (const char *prefix)
Dumps the tree.
const QChar * endingLocation ()
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeData::KviKvsTreeNodeData (const QChar * pLocation)
KviKvsTreeNodeData::~KviKvsTreeNodeData ()
Member Function Documentation
bool KviKvsTreeNodeData::canEvaluateInObjectScope () virtual
Reimplemented in KviKvsTreeNodeScopeOperator, KviKvsTreeNodeVariable, KviKvsTreeNodeObjectField, KviKvsTreeNodeObjectFunctionCall, and KviKvsTreeNodeIndirectData.
Referenced by KviKvsTreeNodeIndirectData::canEvaluateInObjectScope(), KviKvsTreeNodeScopeOperator::canEvaluateInObjectScope(), and KviKvsParser::parsePercentOrDollar().
bool KviKvsTreeNodeData::canEvaluateToObjectReference () virtual
Reimplemented in KviKvsTreeNodeSingleParameterIdentifier, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeVariable, KviKvsTreeNodeFunctionCall, KviKvsTreeNodeParameterCount, and KviKvsTreeNodeArrayOrHashElement.
Referenced by KviKvsTreeNodeScopeOperator::canEvaluateToObjectReference(), and KviKvsParser::parsePercentOrDollar().
void KviKvsTreeNodeData::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Implements KviKvsTreeNode.
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator, KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperator, KviKvsTreeNodeExpressionOperator, KviKvsTreeNodeExpressionConstantOperand, KviKvsTreeNodeExpressionVariableOperand, KviKvsTreeNodeExpression, KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeAliasFunctionCall, KviKvsTreeNodeArrayElement, KviKvsTreeNodeArrayCount, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeBaseObjectFunctionCall, KviKvsTreeNodeCoreFunctionCall, KviKvsTreeNodeHashElement, KviKvsTreeNodeModuleFunctionCall, KviKvsTreeNodeMultipleParameterIdentifier, KviKvsTreeNodeThisObjectFunctionCall, KviKvsTreeNodeSingleParameterIdentifier, KviKvsTreeNodeHashCount, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeCompositeData, KviKvsTreeNodeConstantData, KviKvsTreeNodeFunctionCall, KviKvsTreeNodeObjectField, KviKvsTreeNodeExtendedScopeVariable, KviKvsTreeNodeGlobalVariable, KviKvsTreeNodeLocalVariable, KviKvsTreeNodeObjectFunctionCall, KviKvsTreeNodeParameterCount, and KviKvsTreeNodeStringCast.
bool KviKvsTreeNodeData::convertStringConstantToNumeric () virtual
Reimplemented in KviKvsTreeNodeConstantData.
void KviKvsTreeNodeData::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Implements KviKvsTreeNode.
Reimplemented in KviKvsTreeNodeExpressionBinaryOperator, KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperator, KviKvsTreeNodeExpressionOperator, KviKvsTreeNodeExpressionConstantOperand, KviKvsTreeNodeExpressionVariableOperand, KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeExpression, KviKvsTreeNodeArrayElement, KviKvsTreeNodeArrayCount, KviKvsTreeNodeAliasFunctionCall, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeBaseObjectFunctionCall, KviKvsTreeNodeCoreFunctionCall, KviKvsTreeNodeHashElement, KviKvsTreeNodeModuleFunctionCall, KviKvsTreeNodeMultipleParameterIdentifier, KviKvsTreeNodeThisObjectFunctionCall, KviKvsTreeNodeSingleParameterIdentifier, KviKvsTreeNodeCompositeData, KviKvsTreeNodeConstantData, KviKvsTreeNodeHashCount, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeFunctionCall, KviKvsTreeNodeObjectField, KviKvsTreeNodeStringCast, KviKvsTreeNodeExtendedScopeVariable, KviKvsTreeNodeGlobalVariable, KviKvsTreeNodeLocalVariable, KviKvsTreeNodeObjectFunctionCall, and KviKvsTreeNodeParameterCount.
Referenced by KviKvsTreeNodeStringCast::dump(), KviKvsTreeNodeScopeOperator::dump(), KviKvsTreeNodeRebindingSwitch::dump(), KviKvsTreeNodeHashElement::dump(), KviKvsTreeNodeOperation::dump(), KviKvsTreeNodeSpecialCommandForeach::dump(), KviKvsTreeNodeSwitchList::dump(), KviKvsTreeNodeOperationAssignment::dump(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::dump(), KviKvsTreeNodeOperationDecrement::dump(), KviKvsTreeNodeSpecialCommandSwitchLabelMatch::dump(), KviKvsTreeNodeArrayElement::dump(), KviKvsTreeNodeOperationIncrement::dump(), KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::dump(), KviKvsTreeNodeOperationSelfAnd::dump(), KviKvsTreeNodeExpressionVariableOperand::dump(), KviKvsTreeNodeOperationSelfDivision::dump(), KviKvsTreeNodeOperationSelfModulus::dump(), KviKvsTreeNodeOperationSelfMultiplication::dump(), KviKvsTreeNodeOperationSelfOr::dump(), KviKvsTreeNodeOperationSelfShl::dump(), KviKvsTreeNodeOperationSelfShr::dump(), KviKvsTreeNodeOperationSelfSubtraction::dump(), KviKvsTreeNodeSpecialCommandDefpopup::dump(), KviKvsTreeNodeOperationSelfSum::dump(), KviKvsTreeNodeOperationSelfXor::dump(), KviKvsTreeNodeOperationStringAppend::dump(), KviKvsTreeNodeOperationArrayAppend::dump(), KviKvsTreeNodeOperationStringAppendWithComma::dump(), KviKvsTreeNodeOperationStringAppendWithSpace::dump(), KviKvsTreeNodeOperationStringTransliteration::dump(), and KviKvsTreeNodeOperationStringSubstitution::dump().
const QChar* KviKvsTreeNodeData::endingLocation () inline
Referenced by KviKvsModuleCallbackCommandCall::getParameterCode().
bool KviKvsTreeNodeData::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented in KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionConstantOperand, KviKvsTreeNodeExpressionVariableOperand, KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeArrayElement, KviKvsTreeNodeAliasFunctionCall, KviKvsTreeNodeArrayCount, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeSingleParameterIdentifier, KviKvsTreeNodeCoreFunctionCall, KviKvsTreeNodeHashElement, KviKvsTreeNodeModuleFunctionCall, KviKvsTreeNodeMultipleParameterIdentifier, KviKvsTreeNodeCommandEvaluation, KviKvsTreeNodeHashCount, KviKvsTreeNodeParameterCount, KviKvsTreeNodeExtendedScopeVariable, KviKvsTreeNodeGlobalVariable, KviKvsTreeNodeLocalVariable, KviKvsTreeNodeCompositeData, KviKvsTreeNodeConstantData, and KviKvsTreeNodeStringCast.
References __tr2qs_ctx(), and KviKvsRunTimeContext::error().
Referenced by KviKvsTreeNodeArrayElement::evaluateIndex(), KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand(), KviKvsTreeNodeExpressionBinaryOperator::evaluateOperands(), KviKvsTreeNodeStringCast::evaluateReadOnly(), KviKvsTreeNodeScopeOperator::evaluateReadOnly(), KviKvsTreeNodeExpressionVariableOperand::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::evaluateReadOnly(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeScopeOperator::evaluateReadWrite(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeExpressionReturn::execute(), KviKvsTreeNodeVoidFunctionCall::execute(), KviKvsTreeNodeRebindingSwitch::execute(), KviKvsTreeNodeSpecialCommandDo::execute(), KviKvsTreeNodeSpecialCommandIf::execute(), KviKvsTreeNodeSpecialCommandWhile::execute(), KviKvsTreeNodeSpecialCommandFor::execute(), KviKvsTreeNodeOperationAssignment::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelCase::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelMatch::execute(), KviKvsTreeNodeSpecialCommandSwitchLabelRegexp::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeSpecialCommandSwitch::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationStringAppend::execute(), KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsTreeNodeOperationStringAppendWithComma::execute(), KviKvsTreeNodeOperationStringAppendWithSpace::execute(), KviKvsTreeNodeOperationStringTransliteration::execute(), and KviKvsTreeNodeOperationStringSubstitution::execute().
bool KviKvsTreeNodeData::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented in KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeArrayElement, KviKvsTreeNodeArrayCount, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeBaseObjectFunctionCall, KviKvsTreeNodeHashElement, KviKvsTreeNodeThisObjectFunctionCall, KviKvsTreeNodeHashCount, and KviKvsTreeNodeObjectField.
References __tr2qs_ctx(), and KviKvsRunTimeContext::error().
Referenced by KviKvsTreeNodeScopeOperator::evaluateReadOnly(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeScopeOperator::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), and KviKvsTreeNodeScopeOperator::evaluateReadWriteInObjectScope().
KviKvsRWEvaluationResult * KviKvsTreeNodeData::evaluateReadWrite (KviKvsRunTimeContext * c) virtual
Reimplemented in KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeArrayElement, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeHashElement, KviKvsTreeNodeExtendedScopeVariable, KviKvsTreeNodeGlobalVariable, and KviKvsTreeNodeLocalVariable.
References __tr2qs_ctx(), and KviKvsRunTimeContext::error().
Referenced by KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeHashReferenceAssert::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadWriteInObjectScope(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeOperationAssignment::execute(), KviKvsTreeNodeOperationDecrement::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationStringAppend::execute(), KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsTreeNodeOperationStringAppendWithComma::execute(), KviKvsTreeNodeOperationStringAppendWithSpace::execute(), KviKvsTreeNodeOperationStringTransliteration::execute(), and KviKvsTreeNodeOperationStringSubstitution::execute().
KviKvsRWEvaluationResult * KviKvsTreeNodeData::evaluateReadWriteInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c) virtual
Reimplemented in KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeArrayElement, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeHashElement, and KviKvsTreeNodeObjectField.
References __tr2qs_ctx(), and KviKvsRunTimeContext::error().
Referenced by KviKvsTreeNodeScopeOperator::evaluateReadWrite(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeHashReferenceAssert::evaluateReadWriteInObjectScope(), KviKvsTreeNodeScopeOperator::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), and KviKvsTreeNodeArrayReferenceAssert::evaluateReadWriteInObjectScope().
bool KviKvsTreeNodeData::isFunctionCall () virtual
Reimplemented in KviKvsTreeNodeScopeOperator, and KviKvsTreeNodeFunctionCall.
Referenced by KviKvsTreeNodeScopeOperator::isFunctionCall(), KviKvsParser::parseSpecialCommandForeach(), and KviKvsParser::parseVoidFunctionCallOrOperation().
bool KviKvsTreeNodeData::isReadOnly () virtual
Reimplemented in KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeVariable, and KviKvsTreeNodeArrayOrHashElement.
Referenced by KviKvsTreeNodeArrayOrHashElement::isReadOnly(), KviKvsTreeNodeScopeOperator::isReadOnly(), KviKvsTreeNodeHashReferenceAssert::isReadOnly(), KviKvsTreeNodeArrayReferenceAssert::isReadOnly(), KviKvsParser::parseSpecialCommandForeach(), and KviKvsParser::parseVoidFunctionCallOrOperation().
void KviKvsTreeNodeData::setEndingLocation (const QChar * pEndingLocation) inline
Member Data Documentation
const QChar* KviKvsTreeNodeData::m_pEndingLocation protected
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeData.h
src/kvirc/kvs/tree/KviKvsTreeNodeData.cpp