KVIrc: FileTransferWidget Class Reference
FileTransferWidget Class Reference
#include <FileTransferWindow.h>
Signals
void doubleClicked (FileTransferItem *, QPoint pnt)
void rightButtonPressed (FileTransferItem *, QPoint pnt)
Public Member Functions
int dummyRead () const
FileTransferWidget (QWidget *pParent)
void paintEvent (QPaintEvent *event)
~FileTransferWidget ()
Public Member Functions inherited from KviTalTableWidget
KviTalTableWidget (QWidget *pParent)
virtual ~KviTalTableWidget ()
Protected Member Functions
void mouseDoubleClickEvent (QMouseEvent *e)
void mousePressEvent (QMouseEvent *e)
Properties
int TransparencyCapable
Friends
class FileTransferItemDelegate
Constructor & Destructor Documentation
FileTransferWidget::FileTransferWidget (QWidget * pParent)
References __tr2qs_ctx(), and FILETRANSFERW_CELLSIZE.
FileTransferWidget::~FileTransferWidget () inline
Member Function Documentation
void FileTransferWidget::doubleClicked (FileTransferItem * , QPoint pnt) signal
Referenced by mouseDoubleClickEvent().
int FileTransferWidget::dummyRead () const inline
void FileTransferWidget::mouseDoubleClickEvent (QMouseEvent * e) protected
References doubleClicked(), and i.
void FileTransferWidget::mousePressEvent (QMouseEvent * e) protected
References i, and rightButtonPressed().
void FileTransferWidget::paintEvent (QPaintEvent * event)
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorTreeWindowListBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviMainWindow::mdiManager(), KviWindow::mdiParent(), p, KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
void FileTransferWidget::rightButtonPressed (FileTransferItem * , QPoint pnt) signal
Referenced by mousePressEvent().
Friends And Related Function Documentation
friend class FileTransferItemDelegate friend
Property Documentation
int FileTransferWidget::TransparencyCapable read
The documentation for this class was generated from the following files:
src/modules/filetransferwindow/FileTransferWindow.h
src/modules/filetransferwindow/FileTransferWindow.cpp