KVIrc: OptionsWidget_alerts Class Reference
OptionsWidget_alerts Class Reference
#include <OptionsWidget_alertsAndHighlighting.h>
Public Member Functions
OptionsWidget_alerts (QWidget *parent)
~OptionsWidget_alerts ()
Constructor & Destructor Documentation
OptionsWidget_alerts::OptionsWidget_alerts (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_MSGTYPE_MAXLEVEL, KVI_OPTION_BOOL, KviOption_boolHighlightOnlyAtCostumHighlightLevel, KviOption_boolHighlightOnlyNormalMsg, KviOption_boolHighlightOnlyNormalMsgHighlightInChanToo, KviOption_boolHighlightOnlyNormalMsgQueryToo, KviOption_uintMinHighlightLevel, KviOptionsWidget::mergeTip(), and KviUIntSelector::setEnabled().
OptionsWidget_alerts::~OptionsWidget_alerts ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_alertsAndHighlighting.h
src/modules/options/OptionsWidget_alertsAndHighlighting.cpp