KVIrc: OptionsWidget_dccSendGeneral Class Reference
OptionsWidget_dccSendGeneral Class Reference
#include <OptionsWidget_dcc.h>
Public Member Functions
OptionsWidget_dccSendGeneral (QWidget *parent)
~OptionsWidget_dccSendGeneral ()
Constructor & Destructor Documentation
OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addDirectorySelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolAutoAcceptDccSend, KviOption_boolAutoCloseDccSendOnSuccess, KviOption_boolAutoResumeDccSendWhenAutoAccepted, KviOption_boolCreateMinimizedDccSend, KviOption_boolCreateMinimizedDccSendWhenAutoAccepted, KviOption_boolNotifyDccSendSuccessInConsole, KviOption_boolNotifyDccSendSuccessInNotifier, KviOption_boolSortReceivedByDccFilesByNicks, KviOption_boolUseIncomingDccMediaTypeSavePath, KviOption_stringIncomingPath, and KviOptionsWidget::mergeTip().
OptionsWidget_dccSendGeneral::~OptionsWidget_dccSendGeneral ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_dcc.h
src/modules/options/OptionsWidget_dcc.cpp