KVIrc: KviCtcpPageDialog Class Reference
KviCtcpPageDialog Class Reference
#include <kvi_ctcppagedialog.h>
Public Member Functions
void addPage (const QString &szNick, const QString &szUser, const QString &szHost, const QString &szMsg)
KviCtcpPageDialog ()
void popup ()
~KviCtcpPageDialog ()
Protected Slots
void die ()
Protected Member Functions
void center ()
virtual void closeEvent (QCloseEvent *e)
virtual void showEvent (QShowEvent *e)
Protected Attributes
QPushButton * m_pCloseButton
QTabWidget * m_pTabBar
Constructor & Destructor Documentation
KviCtcpPageDialog::KviCtcpPageDialog ()
References __tr2qs, die(), g_pIconManager, KviIconManager::getSmallIcon(), KVI_SMALLICON_CTCPREQUESTREPLIED, m_pCloseButton, and m_pTabBar.
KviCtcpPageDialog::~KviCtcpPageDialog ()
References g_pCtcpPageDialog.
Member Function Documentation
void KviCtcpPageDialog::addPage (const QString & szNick, const QString & szUser, const QString & szHost, const QString & szMsg)
References __tr2qs, KVI_OPTION_UINT, KviOption_uintOutputDatetimeFormat, and m_pTabBar.
Referenced by KviServerParser::parseCtcpRequestPage().
void KviCtcpPageDialog::center () [protected]
References g_pApp.
Referenced by showEvent().
void KviCtcpPageDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void KviCtcpPageDialog::die () [protected, slot]
Referenced by KviCtcpPageDialog().
void KviCtcpPageDialog::popup ()
References m_pCloseButton.
Referenced by KviServerParser::parseCtcpRequestPage().
void KviCtcpPageDialog::showEvent (QShowEvent * e) [protected, virtual]
References center().
Member Data Documentation
QPushButton* KviCtcpPageDialog::m_pCloseButton [protected]
Referenced by KviCtcpPageDialog(), and popup().
QTabWidget* KviCtcpPageDialog::m_pTabBar [protected]
Referenced by addPage(), and KviCtcpPageDialog().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_ctcppagedialog.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_ctcppagedialog.cpp