KVIrc: OptionsWidget_identService Class Reference
OptionsWidget_identService Class Reference
#include <OptionsWidget_connection.h>
Public Slots
void enableIpv4InIpv6 (bool)
Public Member Functions
virtual void commit ()
OptionsWidget_identService (QWidget *parent)
~OptionsWidget_identService ()
Protected Attributes
QRadioButton * m_pActiveRadio
QRadioButton * m_pConsoleRadio
KviBoolSelector * m_pEnableIdent
KviBoolSelector * m_pEnableIpv6
KviBoolSelector * m_pIpv4InIpv6
QRadioButton * m_pQuietRadio
Constructor & Destructor Documentation
OptionsWidget_identService::OptionsWidget_identService (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), enableIpv4InIpv6(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolIdentdEnableIPv6, KviOption_boolIdentdIPv6ContainsIPv4, KviOption_boolUseIdentService, KviOption_boolUseIdentServiceOnlyOnConnect, KviOption_stringIdentdUser, KviOption_uintIdentdOutputMode, KviOption_uintIdentdPort, m_pActiveRadio, m_pConsoleRadio, m_pEnableIdent, m_pEnableIpv6, m_pIpv4InIpv6, m_pQuietRadio, KviIdentdOutputMode::Quiet, s, KviBoolSelector::setEnabled(), KviIdentdOutputMode::ToActiveWindow, KviIdentdOutputMode::ToConsole, and u.
OptionsWidget_identService::~OptionsWidget_identService ()
Member Function Documentation
void OptionsWidget_identService::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintIdentdOutputMode, m_pActiveRadio, m_pConsoleRadio, m_pQuietRadio, KviIdentdOutputMode::Quiet, KviIdentdOutputMode::ToActiveWindow, and KviIdentdOutputMode::ToConsole.
void OptionsWidget_identService::enableIpv4InIpv6 (bool) [slot]
References m_pEnableIdent, m_pEnableIpv6, m_pIpv4InIpv6, and KviBoolSelector::setEnabled().
Referenced by OptionsWidget_identService().
Member Data Documentation
QRadioButton* OptionsWidget_identService::m_pActiveRadio [protected]
Referenced by commit(), and OptionsWidget_identService().
QRadioButton* OptionsWidget_identService::m_pConsoleRadio [protected]
Referenced by commit(), and OptionsWidget_identService().
KviBoolSelector* OptionsWidget_identService::m_pEnableIdent [protected]
Referenced by enableIpv4InIpv6(), and OptionsWidget_identService().
KviBoolSelector* OptionsWidget_identService::m_pEnableIpv6 [protected]
Referenced by enableIpv4InIpv6(), and OptionsWidget_identService().
KviBoolSelector* OptionsWidget_identService::m_pIpv4InIpv6 [protected]
Referenced by enableIpv4InIpv6(), and OptionsWidget_identService().
QRadioButton* OptionsWidget_identService::m_pQuietRadio [protected]
Referenced by commit(), and OptionsWidget_identService().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_connection.h
src/modules/options/OptionsWidget_connection.cpp