KVIrc: KviIrcServer Class Reference
KviIrcServer Class Reference
The class which manages the irc servers.
#include <KviIrcServer.h>
Public Types
enum Flags {
IPv6 = 1, CacheIP = 2, SSL = 4, STARTTLS = 8,
SASL = 16, CAP = 32
}
Contains the features supported by the server.
Public Member Functions
const QString & alternativeNickName () const
Returns the alternative nickname of the user associated to the server.
bool autoConnect () const
Returns true if the server is in autoconnect mode.
QStringList * autoJoinChannelList ()
Returns the list of the channels in the autojoin list.
const QString autoJoinChannelListAsString ()
Returns the list of the channels in the autojoin list as a string.
bool cacheIp () const
Returns true if the server caches the IP.
void clearReconnectInfo ()
const QString & description () const
Returns the description of the server.
bool enabledCAP () const
Returns true if the CAP protocol is enabled for this server.
bool enabledSASL () const
Returns true if the SASL protocol is enabled for this server.
bool enabledSTARTTLS () const
Returns true if the STARTTLS protocol is enabled for this server.
const QString & encoding () const
Returns the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server.
void generateUniqueId ()
Generates an unique id for the server and sets it.
const QString & hostName () const
Returns the hostname of the user associated to the server.
const QString & id () const
Returns the id of the server.
const QString & initUMode () const
Returns the user modes of the user associated to the server.
const QString & ip () const
Returns the IP address of the server.
QString ircUri ()
Returns the irc URI for the server The URI is in the form irc[[s]6]://name.serverhost.tld.
bool isIPv6 () const
Returns true if the server uses IPv6.
KviIrcServer ()
Constructs the server object.
KviIrcServer (const KviIrcServer &serv)
Carbon copy.
const QString & linkFilter () const
Returns the filter applied on the server.
bool load (KviConfigurationFile *pCfg, const QString &szPrefix)
Loads the information from the configuration file.
const QString & nickName () const
Returns the nickname of the user associated to the server.
const QString & onConnectCommand () const
Returns the commands to run on server connection.
const QString & onLoginCommand () const
Returns the commands to run on server login.
void operator= (const KviIrcServer &serv)
Carbon copy.
const QString & password () const
Returns the password of the user associated to the server.
kvi_u32_t port () const
Returns the port number.
int proxy ()
Returns the proxy server's id.
KviProxy * proxyServer (KviProxyDataBase *pDb)
Returns the proxy server.
const QString & realName () const
Returns the realname of the user associated to the server.
KviIrcServerReconnectInfo * reconnectInfo ()
const QString & saslNick () const
Returns the nickname used for sasl auth.
const QString & saslPass () const
Returns the password used for sasl auth.
void save (KviConfigurationFile *pCfg, const QString &szPrefix)
Saves the information to the configuration file.
void setAlternativeNickName (const QString &szNick)
Sets the alternative nickname of the user associated to the server.
void setAutoConnect (bool bAutoConnect)
Sets the autoconnection mode for the server.
void setAutoJoinChannelList (QStringList *pNewChannelList)
Sets the list of channels to autojoin after connection The channel list must be allocated with a new!
void setAutoJoinChannelList (const QString &szNewChannelList)
Sets the list of channels to mark for autojoin.
void setCacheIp (bool bSet)
Sets if the server caches the IP.
void setDescription (const QString &szDesc)
Sets the description for the server.
void setEnabledCAP (bool bSet)
Sets if CAP support is enabled/disabled for this server.
void setEnabledSASL (bool bSet)
Sets if SASL support is enabled/disabled for this server.
void setEnabledSTARTTLS (bool bSet)
Sets if STARTTLS support is enabled/disabled for this server.
void setEncoding (const QString &szEncoding)
Sets the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server This is the default encoding when talking on channels or queries.
void setHostName (const QString &szHost)
Sets the hostname for the server.
void setId (const QString &szId)
Sets an unique id for the server.
void setInitUMode (const QString &szUMode)
Sets the user modes of the user associated to the server.
void setIp (const QString &szIp)
Sets the IP for the server.
void setIPv6 (bool bSet)
Sets if the server uses IPv6.
void setLinkFilter (const QString &szFilter)
Applies the filter to the server.
void setNickName (const QString &szNick)
Sets the nickname of the user associated to the server.
void setOnConnectCommand (const QString &szCmd)
Sets the commands to run on server connection.
void setOnLoginCommand (const QString &szCmd)
Sets the commands to run on server login.
void setPassword (const QString &szPass)
Sets the password of the user associated to the server.
void setPort (kvi_u32_t uPort)
Sets the port for the server.
void setProxy (int iProxy)
Sets the proxy server for the server.
void setRealName (const QString &szReal)
Sets the realname of the user associated to the server.
void setReconnectInfo (KviIrcServerReconnectInfo *pInfo)
void setSaslNick (const QString &szNick)
Sets the nickname used for sasl auth.
void setSaslPass (const QString &szPass)
Sets the password used for sasl auth.
void setTextEncoding (const QString &szEncoding)
Sets the encoding associated to the server This is the default encoding when talking on channels or queries.
void setUserIdentityId (const QString &szUserIdentityId)
Sets the id of the user associated to the server.
void setUserName (const QString &szUser)
Sets the username of the user associated to the server.
void setUseSSL (bool bSet)
Sets if the server uses SSL.
const QString & textEncoding () const
Returns the text encoding associated to the server This is the default encoding when talking on channels or queries.
const QString & userIdentityId () const
Returns the id of the user associated to the server.
const QString & userName () const
Returns the username of the user associated to the server.
bool useSSL () const
Returns true if the server uses SSL.
~KviIrcServer ()
Destroys the server object.
Private Attributes
bool m_bAutoConnect
int m_iProxy
QStringList * m_pAutoJoinChannelList
KviIrcServerReconnectInfo * m_pReconnectInfo
QString m_szAlternativeNick
QString m_szDescription
QString m_szEncoding
QString m_szHostname
QString m_szId
QString m_szInitUMode
QString m_szIp
QString m_szLinkFilter
QString m_szNick
QString m_szOnConnectCommand
QString m_szOnLoginCommand
QString m_szPass
QString m_szRealName
QString m_szSaslNick
QString m_szSaslPass
QString m_szTextEncoding
QString m_szUser
QString m_szUserIdentityId
unsigned short int m_uFlags
kvi_u32_t m_uPort
Detailed Description
The class which manages the irc servers.
Member Enumeration Documentation
enum KviIrcServer::Flags
Contains the features supported by the server.
Enumerator:
IPv6
IPv6 support
CacheIP
whether we cache the server's IP
SSL
SSL support
STARTTLS
STARTTLS support
SASL
SASL support
CAP
CAP support
Constructor & Destructor Documentation
KviIrcServer::KviIrcServer ()
Constructs the server object.
Returns:
KviIrcServer
References m_bAutoConnect, m_iProxy, m_pAutoJoinChannelList, m_pReconnectInfo, m_uFlags, m_uPort, and NULL.
KviIrcServer::KviIrcServer (const KviIrcServer & serv)
Carbon copy.
Parameters:
serv The irc server
Returns:
KviIrcServer
References m_bAutoConnect, m_iProxy, m_pAutoJoinChannelList, m_pReconnectInfo, m_szAlternativeNick, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uFlags, m_uPort, and NULL.
KviIrcServer::~KviIrcServer ()
Destroys the server object.
References m_pAutoJoinChannelList, m_pReconnectInfo, and NULL.
Member Function Documentation
const QString& KviIrcServer::alternativeNickName () const inline
Returns the alternative nickname of the user associated to the server.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::pickNextLoginNickName().
bool KviIrcServer::autoConnect () const inline
Returns true if the server is in autoconnect mode.
Returns:
bool
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), KviIrcServerDataBase::load(), and save().
QStringList* KviIrcServer::autoJoinChannelList () inline
Returns the list of the channels in the autojoin list.
Returns:
QStringList *
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), KviIrcConnection::loginComplete(), and save().
const QString KviIrcServer::autoJoinChannelListAsString () inline
Returns the list of the channels in the autojoin list as a string.
Returns:
const QString &
bool KviIrcServer::cacheIp () const inline
Returns true if the server caches the IP.
Returns:
bool
References CacheIP.
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcSocket::proxySendTargetDataV5(), and save().
void KviIrcServer::clearReconnectInfo ()
References m_pReconnectInfo, and NULL.
Referenced by KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), and KviIrcConnection::loginComplete().
const QString& KviIrcServer::description () const inline
Returns the description of the server.
Returns:
const QString &
Referenced by OptionsWidget_servers::filterTextEdited(), IrcServerDetailsWidget::IrcServerDetailsWidget(), IrcServerOptionsTreeWidgetItem::IrcServerOptionsTreeWidgetItem(), and IrcServerOptionsTreeWidgetItem::updateVisibleStrings().
bool KviIrcServer::enabledCAP () const inline
Returns true if the CAP protocol is enabled for this server.
Returns:
bool
References CAP.
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and save().
bool KviIrcServer::enabledSASL () const inline
Returns true if the SASL protocol is enabled for this server.
Returns:
bool
References SASL.
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and save().
bool KviIrcServer::enabledSTARTTLS () const inline
Returns true if the STARTTLS protocol is enabled for this server.
Returns:
bool
References STARTTLS.
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and save().
const QString& KviIrcServer::encoding () const inline
Returns the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::setupSrvCodec().
void KviIrcServer::generateUniqueId ()
Generates an unique id for the server and sets it.
Returns:
void
References kvi_gettimeofday(), and m_szId.
Referenced by OptionsWidget_servers::commit(), IrcServerDetailsWidget::fillData(), IrcServerDetailsWidget::IrcServerDetailsWidget(), load(), OptionsWidget_servers::newServer(), and OptionsWidget_servers::pasteServer().
const QString& KviIrcServer::hostName () const inline
Returns the hostname of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), OptionsWidget_servers::commit(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), OptionsWidget_servers::currentItemChanged(), OptionsWidget_servers::filterTextEdited(), KviIrcNetwork::findServer(), OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), IrcServerOptionsTreeWidgetItem::IrcServerOptionsTreeWidgetItem(), KviIrcUrl::join(), KviIrcConnection::loginToIrcServer(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxySendTargetDataV5(), KviIrcUrl::run(), OptionsWidget_servers::selectBestServerByUrl(), KviIrcConnectionTargetResolver::serverLookupTerminated(), and IrcServerOptionsTreeWidgetItem::updateVisibleStrings().
const QString& KviIrcServer::id () const inline
Returns the id of the server.
Returns:
const QString &
Referenced by OptionsWidget_servers::commit(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), IrcServerDetailsWidget::fillData(), KviIrcNetwork::findServer(), and IrcServerDetailsWidget::IrcServerDetailsWidget().
const QString& KviIrcServer::initUMode () const inline
Returns the user modes of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::loginComplete().
const QString& KviIrcServer::ip () const inline
Returns the IP address of the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionTerminated(), OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), and KviIrcSocket::startConnection().
QString KviIrcServer::ircUri ()
Returns the irc URI for the server The URI is in the form irc[[s]6]://name.serverhost.tld.
Returns:
QString
References isIPv6(), m_szHostname, m_uPort, and useSSL().
bool KviIrcServer::isIPv6 () const inline
Returns true if the server uses IPv6.
Returns:
bool
References IPv6.
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), IrcServerDetailsWidget::fillData(), KviIrcNetwork::findServer(), KviIrcConnectionTargetResolver::haveServerIp(), OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), ircUri(), KviConsoleWindow::isIPv6Connection(), KviIrcUrl::join(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcSocket::proxySendTargetDataV5(), KviIrcUrl::run(), save(), OptionsWidget_servers::selectBestServerByUrl(), KviIrcConnectionTargetResolver::serverLookupTerminated(), KviIrcSocket::startConnection(), and KviIrcConnectionTargetResolver::validateLocalAddress().
const QString& KviIrcServer::linkFilter () const inline
Returns the filter applied on the server.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcLink::resolverTerminated().
bool KviIrcServer::load (KviConfigurationFile * pCfg, const QString & szPrefix)
Loads the information from the configuration file.
Parameters:
pCfg The configuration file
szPrefix The prefix of the server
Returns:
bool
References generateUniqueId(), l, m_bAutoConnect, m_szAlternativeNick, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uPort, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readEntry(), KviConfigurationFile::readIntEntry(), KviConfigurationFile::readStringListEntry(), KviConfigurationFile::readUIntEntry(), setAutoJoinChannelList(), setCacheIp(), setEnabledCAP(), setEnabledSASL(), setEnabledSTARTTLS(), setIPv6(), setProxy(), and setUseSSL().
Referenced by KviIrcServerDataBase::load().
const QString& KviIrcServer::nickName () const inline
Returns the nickname of the user associated to the server.
Returns:
const QString &
Referenced by OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::pickNextLoginNickName().
const QString& KviIrcServer::onConnectCommand () const inline
Returns the commands to run on server connection.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::loginToIrcServer().
const QString& KviIrcServer::onLoginCommand () const inline
Returns the commands to run on server login.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::loginComplete().
void KviIrcServer::operator= (const KviIrcServer & serv)
Carbon copy.
Parameters:
serv The server to copy
Returns:
void
References m_bAutoConnect, m_iProxy, m_pAutoJoinChannelList, m_pReconnectInfo, m_szAlternativeNick, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uFlags, m_uPort, and NULL.
const QString& KviIrcServer::password () const inline
Returns the password of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::loginToIrcServer().
kvi_u32_t KviIrcServer::port () const inline
Returns the port number.
Returns:
kvi_u32_t
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviIrcNetwork::findServer(), OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviIrcUrl::join(), KviIrcSocket::proxyLoginHttp(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), KviIrcUrl::run(), OptionsWidget_servers::selectBestServerByUrl(), and KviIrcSocket::startConnection().
int KviIrcServer::proxy () inline
Returns the proxy server's id.
Returns:
int
Referenced by KviIrcContext::connectToCurrentServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), proxyServer(), and save().
KviProxy * KviIrcServer::proxyServer (KviProxyDataBase * pDb)
Returns the proxy server.
Parameters:
pDb The proxy database
Returns:
KviProxy
References KviPointerList< T >::first(), i, KviPointerList< T >::next(), proxy(), and KviProxyDataBase::proxyList().
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviIrcServer::realName () const inline
Returns the realname of the user associated to the server.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::loginToIrcServer().
KviIrcServerReconnectInfo* KviIrcServer::reconnectInfo () inline
Referenced by KviIrcContext::connectToCurrentServer(), KviIrcConnection::loginComplete(), and KviIrcConnection::loginToIrcServer().
const QString& KviIrcServer::saslNick () const inline
Returns the nickname used for sasl auth.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget().
const QString& KviIrcServer::saslPass () const inline
Returns the password used for sasl auth.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget().
void KviIrcServer::save (KviConfigurationFile * pCfg, const QString & szPrefix)
Saves the information to the configuration file.
Parameters:
pCfg The configuration file
szPrefix The prefix of the server
Returns:
void
References autoConnect(), autoJoinChannelList(), cacheIp(), enabledCAP(), enabledSASL(), enabledSTARTTLS(), isIPv6(), m_szAlternativeNick, m_szDescription, m_szEncoding, m_szHostname, m_szId, m_szInitUMode, m_szIp, m_szLinkFilter, m_szNick, m_szOnConnectCommand, m_szOnLoginCommand, m_szPass, m_szRealName, m_szSaslNick, m_szSaslPass, m_szTextEncoding, m_szUser, m_szUserIdentityId, m_uPort, proxy(), useSSL(), and KviConfigurationFile::writeEntry().
void KviIrcServer::setAlternativeNickName (const QString & szNick) inline
Sets the alternative nickname of the user associated to the server.
Parameters:
szNick The nick name of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setAutoConnect (bool bAutoConnect) inline
Sets the autoconnection mode for the server.
Parameters:
bAutoConnect Whether to set the autoconnection
Returns:
void
Referenced by IrcServerDetailsWidget::fillData(), and serverdb_kvs_cmd_addServer().
void KviIrcServer::setAutoJoinChannelList (QStringList * pNewChannelList)
Sets the list of channels to autojoin after connection The channel list must be allocated with a new!
Parameters:
pNewChannelList The list of channels to autojoin
Returns:
void
References m_pAutoJoinChannelList.
Referenced by IrcServerDetailsWidget::fillData(), and load().
void KviIrcServer::setAutoJoinChannelList (const QString & szNewChannelList)
Sets the list of channels to mark for autojoin.
Parameters:
szNewChannelList A comma separated list of channels
Returns:
void
References m_pAutoJoinChannelList, and NULL.
void KviIrcServer::setCacheIp (bool bSet) inline
Sets if the server caches the IP.
Parameters:
bSet Whether to set the cache for the IP
Returns:
void
References CacheIP.
Referenced by IrcServerDetailsWidget::fillData(), load(), KviIrcServerDataBase::makeCurrentServer(), OptionsWidget_servers::newServer(), and serverdb_kvs_cmd_addServer().
void KviIrcServer::setDescription (const QString & szDesc) inline
Sets the description for the server.
Parameters:
szDesc The description of the server
Returns:
void
Referenced by KviMircServersIniImport::doImport(), IrcServerDetailsWidget::fillData(), and KviIrcServerDataBase::importFromMircIni().
void KviIrcServer::setEnabledCAP (bool bSet) inline
Sets if CAP support is enabled/disabled for this server.
Parameters:
bSet Whether to enable the support for CAP
Returns:
void
References CAP.
Referenced by IrcServerDetailsWidget::fillData(), and load().
void KviIrcServer::setEnabledSASL (bool bSet) inline
Sets if SASL support is enabled/disabled for this server.
Parameters:
bSet Whether to enable the support for SASL
Returns:
void
References SASL.
Referenced by IrcServerDetailsWidget::fillData(), and load().
void KviIrcServer::setEnabledSTARTTLS (bool bSet) inline
Sets if STARTTLS support is enabled/disabled for this server.
Parameters:
bSet Whether to enable the support for STARTTLS
Returns:
void
References STARTTLS.
Referenced by IrcServerDetailsWidget::fillData(), and load().
void KviIrcServer::setEncoding (const QString & szEncoding) inline
Sets the encoding associated to the server Some information as nickname and channel names are encoded when communicating with the server This is the default encoding when talking on channels or queries.
Parameters:
szEncoding The default encoding of the text
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setHostName (const QString & szHost) inline
Sets the hostname for the server.
Parameters:
szHost The host name of the user
Returns:
void
References szHost.
Referenced by KviMircServersIniImport::doImport(), KviIrcServerDataBase::importFromMircIni(), KviIrcServerDataBase::makeCurrentServer(), OptionsWidget_servers::newServer(), OptionsWidget_servers::saveLastItem(), serverdb_kvs_cmd_addServer(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
void KviIrcServer::setId (const QString & szId) inline
Sets an unique id for the server.
Parameters:
szId The id of the server
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setInitUMode (const QString & szUMode) inline
Sets the user modes of the user associated to the server.
Parameters:
szUMode The user modes of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setIp (const QString & szIp) inline
Sets the IP for the server.
Parameters:
szIp The IP of the server
Returns:
void
Referenced by IrcServerDetailsWidget::fillData(), OptionsWidget_servers::importServer(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcServerDataBase::makeCurrentServer(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
void KviIrcServer::setIPv6 (bool bSet) inline
Sets if the server uses IPv6.
Parameters:
bSet Whether to set the support for IPv6
Returns:
void
References IPv6.
Referenced by IrcServerDetailsWidget::fillData(), load(), and serverdb_kvs_cmd_addServer().
void KviIrcServer::setLinkFilter (const QString & szFilter) inline
Applies the filter to the server.
A link filter resides between the low-level socket, which send/receive blocks of bytes, and the connection which talk using IRC messages. The filter can remap blocks of bytes in any direction
Parameters:
szFilter
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setNickName (const QString & szNick) inline
Sets the nickname of the user associated to the server.
Parameters:
szNick The nick name of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData(), and OptionsWidget_servers::importServer().
void KviIrcServer::setOnConnectCommand (const QString & szCmd) inline
Sets the commands to run on server connection.
Parameters:
szCmd The comands to run on connection
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setOnLoginCommand (const QString & szCmd) inline
Sets the commands to run on server login.
Parameters:
szCmd The comands to run on login
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setPassword (const QString & szPass) inline
Sets the password of the user associated to the server.
Parameters:
szPass The password of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData(), OptionsWidget_servers::importServer(), and serverdb_kvs_cmd_addServer().
void KviIrcServer::setPort (kvi_u32_t uPort) inline
Sets the port for the server.
Parameters:
uPort The port of the server
Returns:
void
References uPort.
Referenced by KviMircServersIniImport::doImport(), IrcServerDetailsWidget::fillData(), KviIrcServerDataBase::importFromMircIni(), OptionsWidget_servers::importServer(), and serverdb_kvs_cmd_addServer().
void KviIrcServer::setProxy (int iProxy) inline
Sets the proxy server for the server.
Parameters:
iProxy The proxy to connect through
Returns:
void
Referenced by IrcServerDetailsWidget::fillData(), and load().
void KviIrcServer::setRealName (const QString & szReal) inline
Sets the realname of the user associated to the server.
Parameters:
szReal The real name of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setReconnectInfo (KviIrcServerReconnectInfo * pInfo)
References m_pReconnectInfo.
Referenced by KviIrcContext::connectToCurrentServer().
void KviIrcServer::setSaslNick (const QString & szNick) inline
Sets the nickname used for sasl auth.
Parameters:
szNick The nick name of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setSaslPass (const QString & szPass) inline
Sets the password used for sasl auth.
Parameters:
szPass The password of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setTextEncoding (const QString & szEncoding) inline
Sets the encoding associated to the server This is the default encoding when talking on channels or queries.
Parameters:
szEncoding The default encoding of the text
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setUserIdentityId (const QString & szUserIdentityId) inline
Sets the id of the user associated to the server.
Parameters:
szUserIdentityId The user identity id to set
Returns:
void
void KviIrcServer::setUserName (const QString & szUser) inline
Sets the username of the user associated to the server.
Parameters:
szUser The user name of the user
Returns:
void
Referenced by IrcServerDetailsWidget::fillData().
void KviIrcServer::setUseSSL (bool bSet) inline
Sets if the server uses SSL.
Parameters:
bSet Whether to set the support for SSL
Returns:
void
References SSL.
Referenced by IrcServerDetailsWidget::fillData(), load(), and serverdb_kvs_cmd_addServer().
const QString& KviIrcServer::textEncoding () const inline
Returns the text encoding associated to the server This is the default encoding when talking on channels or queries.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::setupTextCodec().
const QString& KviIrcServer::userIdentityId () const inline
Returns the id of the user associated to the server.
Returns:
const QString &
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviIrcServer::userName () const inline
Returns the username of the user associated to the server.
Returns:
const QString &
Referenced by IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcConnection::loginToIrcServer().
bool KviIrcServer::useSSL () const inline
Returns true if the server uses SSL.
Returns:
bool
References SSL.
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), KviIrcSocket::connectedToIrcServer(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), KviIrcNetwork::findServer(), OptionsWidget_servers::importServer(), IrcServerDetailsWidget::IrcServerDetailsWidget(), ircUri(), KviIrcUrl::join(), KviIrcUrl::run(), save(), OptionsWidget_servers::selectBestServerByUrl(), and KviIrcSocket::startConnection().
Member Data Documentation
bool KviIrcServer::m_bAutoConnect private
autoconnect
Referenced by KviIrcServer(), load(), and operator=().
int KviIrcServer::m_iProxy private
proxy server's id
Referenced by KviIrcServer(), and operator=().
QStringList* KviIrcServer::m_pAutoJoinChannelList private
Channels to auto join
Referenced by KviIrcServer(), operator=(), setAutoJoinChannelList(), and ~KviIrcServer().
KviIrcServerReconnectInfo* KviIrcServer::m_pReconnectInfo private
Referenced by clearReconnectInfo(), KviIrcServer(), operator=(), setReconnectInfo(), and ~KviIrcServer().
QString KviIrcServer::m_szAlternativeNick private
alternate special nickname
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szDescription private
the server description
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szEncoding private
if empty, use network encoding
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szHostname private
the server hostname (or IP eventually)
Referenced by ircUri(), KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szId private
the server's may-be-unique id, may be auto-generated
Referenced by generateUniqueId(), KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szInitUMode private
special user mode
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szIp private
the server's cached ip (if we're caching)
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szLinkFilter private
the link filter object
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szNick private
special nickname
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szOnConnectCommand private
the command to run on connect
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szOnLoginCommand private
the command to run after login
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szPass private
special password
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szRealName private
special real name
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szSaslNick private
nickname for sasl auth
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szSaslPass private
password for sasl auth
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szTextEncoding private
if empty, use network encoding
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szUser private
special username
Referenced by KviIrcServer(), load(), operator=(), and save().
QString KviIrcServer::m_szUserIdentityId private
the user identity to use for this server: if empty, then use the network identity instead
Referenced by KviIrcServer(), load(), operator=(), and save().
unsigned short int KviIrcServer::m_uFlags private
flags
Referenced by KviIrcServer(), and operator=().
kvi_u32_t KviIrcServer::m_uPort private
the server's port
Referenced by ircUri(), KviIrcServer(), load(), operator=(), and save().
The documentation for this class was generated from the following files:
src/kvilib/irc/KviIrcServer.h
src/kvilib/irc/KviIrcServer.cpp