KVIrc: KviSoundThread Class Reference
KviSoundThread Class Reference
#include <libkvisnd.h>
Public Member Functions
KviSoundThread (const QString &szFileName)
void terminate ()
virtual ~KviSoundThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
virtual void play ()
virtual void run ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
Protected Attributes
bool m_bTerminate
QString m_szFileName
Additional Inherited Members
Static Public Member Functions inherited from KviThread
static void msleep (unsigned long msec)
static void sleep (unsigned long sec)
static void usleep (unsigned long usec)
Constructor & Destructor Documentation
KviSoundThread::KviSoundThread (const QString & szFileName)
References m_bTerminate, m_szFileName, and KviSoundPlayer::registerSoundThread().
KviSoundThread::~KviSoundThread () virtual
References m_bTerminate, and KviSoundPlayer::unregisterSoundThread().
Member Function Documentation
void KviSoundThread::play () protected virtual
Referenced by run().
void KviSoundThread::run () protected virtual
Reimplemented from KviThread.
References KVI_THREAD_EVENT_SUCCESS, play(), and KviThread::postEvent().
void KviSoundThread::terminate ()
References m_bTerminate.
Member Data Documentation
bool KviSoundThread::m_bTerminate protected
Referenced by KviSoundThread(), terminate(), and ~KviSoundThread().
QString KviSoundThread::m_szFileName protected
Referenced by KviSoundThread().
The documentation for this class was generated from the following files:
src/modules/snd/libkvisnd.h
src/modules/snd/libkvisnd.cpp