KVIrc: RegisteredUsersDialog Class Reference
RegisteredUsersDialog Class Reference
#include <RegisteredUsersDialog.h>
Public Member Functions
RegisteredUsersDialog (QWidget *par=0)
~RegisteredUsersDialog ()
Public Attributes
QPushButton * m_pAddButton
QPushButton * m_pAddGroupButton
QPushButton * m_pEditButton
QPushButton * m_pExportButton
QPushButton * m_pImportButton
KviRegisteredUsersListView * m_pListView
QPushButton * m_pRemoveButton
QPushButton * m_pSelectAllButton
QPushButton * m_pWizardAddButton
Protected Slots
void addClicked ()
void addGroupClicked ()
void addWizardClicked ()
void cancelClicked ()
void editClicked ()
void exportClicked ()
void importClicked ()
void itemDoubleClicked (QTreeWidgetItem *it, int)
void itemPressed (QTreeWidgetItem *it, int c)
void moveToGroupMenuClicked (QAction *pAction)
void okClicked ()
void removeClicked ()
void rightButtonPressed (QTreeWidgetItem *, QPoint)
void selectAllClicked ()
void selectionChanged ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
void editGroup (KviRegisteredUserGroup *group)
void editItem (RegisteredUsersDialogItem *i)
void fillList ()
Constructor & Destructor Documentation
RegisteredUsersDialog::RegisteredUsersDialog (QWidget * par = 0)
References __tr2qs_ctx(), KviIconManager::Accept, addClicked(), addGroupClicked(), addWizardClicked(), cancelClicked(), connect(), KviRegisteredUserDataBase::copyFrom(), KviIconManager::DeleteItem, KviIconManager::Discard, editClicked(), KviIconManager::EditItem, exportClicked(), f, fillList(), KviIconManager::Floppy, KviIconManager::Folder, g, g_pApp, g_pIconManager, g_pLocalRegisteredUserDataBase, g_pMainWindow, g_pRegisteredUserDataBase, KviIconManager::getSmallIcon(), importClicked(), itemDoubleClicked(), itemPressed(), KVI_OPTION_RECT, KviOption_rectRegisteredUsersDialogGeometry, m_pAddButton, m_pAddGroupButton, m_pEditButton, m_pExportButton, m_pImportButton, m_pListView, m_pRemoveButton, m_pSelectAllButton, m_pWizardAddButton, KviMemory::move(), KviIconManager::NewItem, KviIconManager::NewItemByWizard, okClicked(), KviIconManager::Plus, KviIconManager::RegUsers, removeClicked(), rightButtonPressed(), selectAllClicked(), selectionChanged(), KviTalVBox::setSpacing(), KviTalHBox::setSpacing(), and y.
RegisteredUsersDialog::~RegisteredUsersDialog ()
References g_pLocalRegisteredUserDataBase, KVI_OPTION_RECT, KviOption_rectRegisteredUsersDialogGeometry, x, and y.
Member Function Documentation
void RegisteredUsersDialog::addClicked () protected slot
References fillList().
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::addGroupClicked () protected slot
References __tr2qs_ctx(), KviRegisteredUserDataBase::addGroup(), fillList(), g_pLocalRegisteredUserDataBase, and Normal.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::addWizardClicked () protected slot
References fillList(), g_pLocalRegisteredUserDataBase, and w.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::cancelClicked () protected slot
References m_pListView.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::closeEvent (QCloseEvent * e) protected virtual
References m_pListView, and okClicked().
void RegisteredUsersDialog::editClicked () protected slot
References editGroup(), editItem(), RegisteredUsersGroupItem::group(), i, m_pListView, RegisteredUsersDialogItemBase::type(), and RegisteredUsersDialogItemBase::User.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::editGroup (KviRegisteredUserGroup * group) protected
References __tr2qs_ctx(), c, d, KviQString::equalCI(), fillList(), KviPointerHashTable< Key, T >::first(), g_pLocalRegisteredUserDataBase, KviRegisteredUserDataBase::groupDict(), KviPointerHashTable< Key, T >::insert(), m_pListView, KviRegisteredUserGroup::name(), KviPointerHashTable< Key, T >::next(), Normal, KviPointerHashTable< Key, T >::remove(), KviPointerHashTable< Key, T >::setAutoDelete(), KviRegisteredUserGroup::setName(), u, and KviRegisteredUserDataBase::userDict().
Referenced by editClicked(), and itemDoubleClicked().
void RegisteredUsersDialog::editItem (RegisteredUsersDialogItem * i) protected
References c, d, KviQString::equalCI(), fillList(), m_pListView, KviRegisteredUser::name(), RegisteredUsersDialogItem::setUser(), u, and RegisteredUsersDialogItem::user().
Referenced by editClicked(), and itemDoubleClicked().
void RegisteredUsersDialog::exportClicked () protected slot
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), KviPointerHashTable< Key, T >::count(), KviPointerList< T >::count(), f, KviPointerList< T >::first(), KviPointerHashTable< Key, T >::firstEntry(), g_pIconManager, KviIconManager::getAvatar(), KviRegisteredUser::getProperty(), i, key, KVI_REGUSER_DB_FILE_MAGIC, KVI_REGUSER_DB_FILE_VERSION, m, m_pListView, _KviReguserDbFileHeader::magic, KviRegisteredUser::maskList(), KviRegisteredUser::name(), _KviReguserDbFileHeader::nentries, KviPointerList< T >::next(), KviPointerHashTable< Key, T >::nextEntry(), KviIrcMask::NickUserHost, KviAvatar::pixmap(), KviRegisteredUser::propertyDict(), KviFile::save(), RegisteredUsersDialogItemBase::type(), KviOsInfo::type(), u, RegisteredUsersDialogItemBase::User, _KviReguserDbFileHeader::version, and KviMessageBox::warning().
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::fillList () protected
References __tr2qs_ctx(), KviRegisteredUserDataBase::addGroup(), d, KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::first(), g, g_pLocalRegisteredUserDataBase, KviRegisteredUserDataBase::groupDict(), KviPointerHashTable< Key, T >::insert(), m_pListView, KviPointerHashTable< Key, T >::next(), Q_UNUSED(), KviPointerHashTable< Key, T >::setAutoDelete(), u, and KviRegisteredUserDataBase::userDict().
Referenced by addClicked(), addGroupClicked(), addWizardClicked(), editGroup(), editItem(), importClicked(), moveToGroupMenuClicked(), RegisteredUsersDialog(), and removeClicked().
void RegisteredUsersDialog::importClicked () protected slot
References __tr2qs_ctx(), KviRegisteredUserDataBase::addMask(), KviFileUtils::adjustFilePath(), KviFileDialog::askForOpenFileName(), KviApplication::Avatars, f, KviFileUtils::fileExists(), fillList(), g_pApp, g_pLocalRegisteredUserDataBase, KviApplication::getLocalKvircDirectory(), KviRegisteredUserDataBase::getUser(), KVI_REGUSER_DB_FILE_MAGIC, KVI_REGUSER_DB_FILE_VERSION, KviFile::load(), m, _KviReguserDbFileHeader::magic, KviRegisteredUser::name(), _KviReguserDbFileHeader::nentries, KviRegisteredUser::setProperty(), u, _KviReguserDbFileHeader::version, and KviMessageBox::warning().
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::itemDoubleClicked (QTreeWidgetItem * it, int) protected slot
References editGroup(), editItem(), RegisteredUsersGroupItem::group(), i, RegisteredUsersDialogItemBase::type(), and RegisteredUsersDialogItemBase::User.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::itemPressed (QTreeWidgetItem * it, int c) protected slot
References KviPointerList< T >::first(), KviRegisteredUser::getProperty(), i, m, m_pListView, KviRegisteredUser::maskList(), KviRegisteredUser::name(), KviPointerList< T >::next(), r, KviRegisteredUser::setProperty(), RegisteredUsersDialogItemBase::type(), RegisteredUsersDialogItemBase::User, and RegisteredUsersDialogItem::user().
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::moveToGroupMenuClicked (QAction * pAction) protected slot
References fillList(), i, m_pListView, RegisteredUsersDialogItemBase::type(), and RegisteredUsersDialogItemBase::User.
Referenced by rightButtonPressed().
void RegisteredUsersDialog::okClicked () protected slot
References KviRegisteredUserDataBase::copyFrom(), g_pApp, g_pLocalRegisteredUserDataBase, g_pRegisteredUserDataBase, m_pListView, and KviApplication::restartNotifyLists().
Referenced by closeEvent(), and RegisteredUsersDialog().
void RegisteredUsersDialog::removeClicked () protected slot
References fillList(), g_pLocalRegisteredUserDataBase, i, m_pListView, KviRegisteredUserDataBase::removeGroup(), KviRegisteredUserDataBase::removeUser(), RegisteredUsersDialogItemBase::type(), and RegisteredUsersDialogItemBase::User.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::rightButtonPressed (QTreeWidgetItem * pItem, QPoint pnt) protected slot
References __tr2qs_ctx(), connect(), KviPointerHashTable< Key, T >::firstEntry(), g, g_pLocalRegisteredUserDataBase, KviRegisteredUserDataBase::groupDict(), moveToGroupMenuClicked(), KviPointerHashTable< Key, T >::nextEntry(), RegisteredUsersDialogItemBase::type(), and RegisteredUsersDialogItemBase::User.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::selectAllClicked () protected slot
References m_pListView.
Referenced by RegisteredUsersDialog().
void RegisteredUsersDialog::selectionChanged () protected slot
References m_pEditButton, m_pExportButton, m_pListView, and m_pRemoveButton.
Referenced by RegisteredUsersDialog().
Member Data Documentation
QPushButton* RegisteredUsersDialog::m_pAddButton
Referenced by RegisteredUsersDialog().
QPushButton* RegisteredUsersDialog::m_pAddGroupButton
Referenced by RegisteredUsersDialog().
QPushButton* RegisteredUsersDialog::m_pEditButton
Referenced by RegisteredUsersDialog(), and selectionChanged().
QPushButton* RegisteredUsersDialog::m_pExportButton
Referenced by RegisteredUsersDialog(), and selectionChanged().
QPushButton* RegisteredUsersDialog::m_pImportButton
Referenced by RegisteredUsersDialog().
KviRegisteredUsersListView* RegisteredUsersDialog::m_pListView
Referenced by cancelClicked(), closeEvent(), editClicked(), editGroup(), editItem(), exportClicked(), fillList(), itemPressed(), moveToGroupMenuClicked(), okClicked(), RegisteredUsersDialog(), removeClicked(), selectAllClicked(), and selectionChanged().
QPushButton* RegisteredUsersDialog::m_pRemoveButton
Referenced by RegisteredUsersDialog(), and selectionChanged().
QPushButton* RegisteredUsersDialog::m_pSelectAllButton
Referenced by RegisteredUsersDialog().
QPushButton* RegisteredUsersDialog::m_pWizardAddButton
Referenced by RegisteredUsersDialog().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUsersDialog.h
src/modules/reguser/RegisteredUsersDialog.cpp