KVIrc: KviKvsObjectFunctionHandler Class Reference
KviKvsObjectFunctionHandler Class Reference
#include <KviKvsObjectFunctionHandler.h>
Public Types
enum Flags { Internal = 1 }
Public Member Functions
unsigned int flags ()
bool isClone ()
void setClone (bool bCl)
virtual ~KviKvsObjectFunctionHandler ()
Protected Member Functions
virtual bool call (KviKvsObject *pObject, KviKvsObjectFunctionCall *pCall)=0
virtual
KviKvsObjectFunctionHandler * clone ()=0
virtual bool isScriptHandler ()
KviKvsObjectFunctionHandler (unsigned int uFlags=0)
virtual QString reminder ()
virtual QString scriptHandlerCode ()
virtual void setReminder (const QString &szReminder)
Protected Attributes
bool m_bClone
unsigned int m_uFlags
Friends
class KviKvsObject
class KviKvsObjectClass
Member Enumeration Documentation
enum KviKvsObjectFunctionHandler::Flags
Enumerator:
Internal
Constructor & Destructor Documentation
KviKvsObjectFunctionHandler::KviKvsObjectFunctionHandler (unsigned int uFlags = 0) [protected]
References m_bClone.
KviKvsObjectFunctionHandler::~KviKvsObjectFunctionHandler () [virtual]
Member Function Documentation
virtual bool KviKvsObjectFunctionHandler::call (KviKvsObject * pObject, KviKvsObjectFunctionCall * pCall) [protected, pure virtual]
Implemented in KviKvsObjectCoreCallFunctionHandler, KviKvsObjectScriptFunctionHandler, KviKvsObjectStandardTrueReturnFunctionHandler, KviKvsObjectStandardFalseReturnFunctionHandler, and KviKvsObjectStandardNothingReturnFunctionHandler.
Referenced by KviKvsObject::callFunction().
virtual KviKvsObjectFunctionHandler* KviKvsObjectFunctionHandler::clone () [protected, pure virtual]
Implemented in KviKvsObjectCoreCallFunctionHandler, KviKvsObjectScriptFunctionHandler, KviKvsObjectStandardTrueReturnFunctionHandler, KviKvsObjectStandardFalseReturnFunctionHandler, and KviKvsObjectStandardNothingReturnFunctionHandler.
unsigned int KviKvsObjectFunctionHandler::flags () [inline]
Referenced by KviKvsObject::callFunction(), and ClassEditorWidget::createFullClass().
bool KviKvsObjectFunctionHandler::isClone ()
References m_bClone.
Referenced by ClassEditorWidget::createFullClass().
bool KviKvsObjectFunctionHandler::isScriptHandler () [protected, virtual]
Reimplemented in KviKvsObjectScriptFunctionHandler.
Referenced by KviKvsObjectClass::isScriptHandler(), and KviKvsObjectClass::KviKvsObjectClass().
QString KviKvsObjectFunctionHandler::reminder () [protected, virtual]
Reimplemented in KviKvsObjectScriptFunctionHandler.
Referenced by KviKvsObjectClass::reminder().
QString KviKvsObjectFunctionHandler::scriptHandlerCode () [protected, virtual]
Reimplemented in KviKvsObjectScriptFunctionHandler.
Referenced by KviKvsObjectClass::getFunctionCode().
void KviKvsObjectFunctionHandler::setClone (bool bCl) [inline]
Referenced by KviKvsObjectClass::KviKvsObjectClass().
void KviKvsObjectFunctionHandler::setReminder (const QString & szReminder) [protected, virtual]
Reimplemented in KviKvsObjectScriptFunctionHandler.
Referenced by KviKvsObjectClass::setReminder().
Friends And Related Function Documentation
friend class KviKvsObject [friend]
Reimplemented in KviKvsObjectCoreCallFunctionHandler, KviKvsObjectScriptFunctionHandler, KviKvsObjectStandardTrueReturnFunctionHandler, KviKvsObjectStandardFalseReturnFunctionHandler, and KviKvsObjectStandardNothingReturnFunctionHandler.
friend class KviKvsObjectClass [friend]
Reimplemented in KviKvsObjectCoreCallFunctionHandler, KviKvsObjectScriptFunctionHandler, KviKvsObjectStandardTrueReturnFunctionHandler, KviKvsObjectStandardFalseReturnFunctionHandler, and KviKvsObjectStandardNothingReturnFunctionHandler.
Member Data Documentation
bool KviKvsObjectFunctionHandler::m_bClone [protected]
Referenced by isClone(), and KviKvsObjectFunctionHandler().
unsigned int KviKvsObjectFunctionHandler::m_uFlags [protected]
The documentation for this class was generated from the following files:
src/kvirc/kvs/object/KviKvsObjectFunctionHandler.h
src/kvirc/kvs/object/KviKvsObjectFunctionHandler.cpp