KVIrc: KviStatusBarConnectionTimer Class Reference
KviStatusBarConnectionTimer Class Reference
#include <KviStatusBarApplet.h>
Public Member Functions
KviStatusBarConnectionTimer (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
virtual ~KviStatusBarConnectionTimer ()
Public Member Functions inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * descriptor ()
KviMainWindow * frame ()
int index () const
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Static Public Member Functions
static void selfRegister (KviStatusBar *pBar)
Protected Slots
void toggleTotal ()
Protected Member Functions
virtual void fillContextPopup (QMenu *p)
virtual void loadState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual void saveState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual void timerEvent (QTimerEvent *e)
Protected Member Functions inherited from KviStatusBarApplet
virtual QString tipText (const QPoint &)
Protected Attributes
bool m_bTotal
Protected Attributes inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Constructor & Destructor Documentation
KviStatusBarConnectionTimer::KviStatusBarConnectionTimer (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
References m_bTotal.
KviStatusBarConnectionTimer::~KviStatusBarConnectionTimer () virtual
Member Function Documentation
void KviStatusBarConnectionTimer::fillContextPopup (QMenu * p) protected virtual
Reimplemented from KviStatusBarApplet.
References __tr2qs, m_bTotal, and toggleTotal().
void KviStatusBarConnectionTimer::loadState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References KviCString::Format, m_bTotal, KviCString::ptr(), and KviConfigurationFile::readBoolEntry().
void KviStatusBarConnectionTimer::saveState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References KviCString::Format, m_bTotal, KviCString::ptr(), and KviConfigurationFile::writeEntry().
void KviStatusBarConnectionTimer::selfRegister (KviStatusBar * pBar) static
References __tr2qs, CreateStatusBarConnectionTimer(), d, g_pIconManager, KviIconManager::getSmallIcon(), KviStatusBar::registerAppletDescriptor(), and KviIconManager::Time.
Referenced by KviStatusBar::KviStatusBar().
void KviStatusBarConnectionTimer::timerEvent (QTimerEvent * e) protected virtual
References c, KviIrcContext::connection(), KviIrcConnectionStatistics::connectionStartTime(), KviWindow::context(), KviTimeUtils::FillWithHypens, KviTimeUtils::formatTimeInterval(), g_pActiveWindow, KviIrcContext::isConnected(), KVI_OPTION_UINT, kvi_unixTime, KviOption_uintTotalConnectionTime, m_bTotal, and KviIrcConnection::statistics().
void KviStatusBarConnectionTimer::toggleTotal () protected slot
References m_bTotal.
Referenced by fillContextPopup().
Member Data Documentation
bool KviStatusBarConnectionTimer::m_bTotal protected
Referenced by fillContextPopup(), KviStatusBarConnectionTimer(), loadState(), saveState(), timerEvent(), and toggleTotal().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviStatusBarApplet.h
src/kvirc/ui/KviStatusBarApplet.cpp