KVIrc: OptionsWidget_query Class Reference
OptionsWidget_query Class Reference
#include <OptionsWidget_query.h>
Public Member Functions
OptionsWidget_query (QWidget *parent)
~OptionsWidget_query ()
Constructor & Destructor Documentation
OptionsWidget_query::OptionsWidget_query (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::addWidgetToLayout(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolCreateIncomingQueriesAsMinimized, KviOption_boolCreateQueryOnNotice, KviOption_boolCreateQueryOnPrivmsg, KviOption_boolEnableQueryTracing, KviOption_boolFlashQueryWindowOnNewMessages, KviOption_boolPasteLastLogOnQueryJoin, KviOption_boolPopupNotifierOnNewQueryMessages, KviOption_boolShowExtendedInfoInQueryLabel, KviOption_uintDaysIntervalToPasteOnQueryJoin, KviOption_uintLinesToPasteOnQueryJoin, KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_query::~OptionsWidget_query ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_query.h
src/modules/options/OptionsWidget_query.cpp