KVIrc: KviIrcConnectionAsyncTemplateData< T > Class Template Reference
KviIrcConnectionAsyncTemplateData< T > Class Template Reference
#include <kvi_ircconnectionasynctemplatedata.h>
Public Member Functions
void add (T *i)
KviIrcConnectionAsyncTemplateData ()
T * lookup (const QString &nick)
void remove (T *i)
~KviIrcConnectionAsyncTemplateData ()
Protected Attributes
KviPointerList< T > * m_pInfoList
template<class T>
class KviIrcConnectionAsyncTemplateData< T >
Constructor & Destructor Documentation
template<class T> KviIrcConnectionAsyncTemplateData< T >::KviIrcConnectionAsyncTemplateData () [inline]
template<class T> KviIrcConnectionAsyncTemplateData< T >::~KviIrcConnectionAsyncTemplateData () [inline]
Member Function Documentation
template<class T> void KviIrcConnectionAsyncTemplateData< T >::add (T * i) [inline]
template<class T> T* KviIrcConnectionAsyncTemplateData< T >::lookup (const QString & nick) [inline]
Referenced by KviServerParser::parseNumericEndOfWhois(), KviServerParser::parseNumericNoSuchNick(), KviServerParser::parseNumericNoSuchServer(), KviServerParser::parseNumericWhoisActually(), KviServerParser::parseNumericWhoisAuth(), KviServerParser::parseNumericWhoisAway(), KviServerParser::parseNumericWhoisChannels(), KviServerParser::parseNumericWhoisIdle(), KviServerParser::parseNumericWhoisOther(), KviServerParser::parseNumericWhoisServer(), and KviServerParser::parseNumericWhoisUser().
template<class T> void KviIrcConnectionAsyncTemplateData< T >::remove (T * i) [inline]
Referenced by KviServerParser::parseNumericEndOfWhois(), KviServerParser::parseNumericNoSuchNick(), and KviServerParser::parseNumericNoSuchServer().
Member Data Documentation
template<class T> KviPointerList<T>* KviIrcConnectionAsyncTemplateData< T >::m_pInfoList [protected]
The documentation for this class was generated from the following file:
src/kvirc/kernel/kvi_ircconnectionasynctemplatedata.h