KVIrc: KviChannel Class Reference
KviChannel Class Reference
The class which manages a channel.
#include <kvi_channel.h>
Public Member Functions
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
Colors the icon who tells how much activity there is.
void addHighlightedUser (const QString &szNick)
Adds a user to the highlight list.
bool avatarChanged (const QString &szNick)
Returns true if the avatar of a user is changed.
unsigned int banCount ()
Returns the number of ban masks.
unsigned int banExceptionCount ()
Returns the number of ban exceptions masks list.
KviPointerList< KviMaskEntry > * banExceptionList ()
Returns the list of ban exceptions set.
KviPointerList< KviMaskEntry > * banList ()
Returns the list of bans set.
QFrame * buttonContainer ()
Returns the button container object.
int chanAdminCount ()
Returns the number of users with chanadmin status.
void channelAction (const QString &szNick, unsigned int uActionType, int iTemperature)
Called when someone perform an action in the channel.
QString & channelKey ()
Returns the channel key.
QString & channelLimit ()
Returns the limit number.
QString channelMode ()
Returns the channel mode.
int chanOwnerCount ()
Returns the number of users with chanowner status.
void clearSentSyncWhoRequest ()
Clears the sync WHO request flag.
bool closeOnPart ()
Returns true if the channel has to be closed on part.
unsigned int count ()
Returns the number of users.
void enableUserListUpdates (bool bEnable)
Enables or disable the userlist updates.
KviUserListEntry * findEntry (const QString &szNick)
Searches for a user in the userlist.
QString * firstSelectedNickname ()
Returns the first selected nickname in the userlist.
void getChannelActivityStats (KviChannelActivityStats *s)
Gets the channel activity stats and put them in the buffer.
void getChannelModeString (QString &szBuffer)
Gets the channel mode string and saves it in the buffer.
char getUserFlag (const QString &szNick)
Returns the flag of a user.
virtual void getWindowListTipText (QString &szBuffer)
Creates the tooltip over the channel treeview.
int halfOpCount ()
Returns the number of users with halfop status.
bool hasAllNames ()
Returns true if the channel has all names.
bool hasBanExceptionList ()
Returns true if the channel has a ban exception list.
bool hasBanList ()
Returns true if the channel has a ban list.
bool hasChannelKey ()
Returns true if the channel has a key set.
bool hasChannelLimit ()
Returns true if the channel has a limit set.
bool hasInviteList ()
Returns true if the channel has an invite list.
bool hasQuietBanList ()
Returns true if the channel has a quiet ban list.
bool hasWhoList ()
Returns true if the channel has a WHO list.
unsigned int inviteCount ()
Returns the number of invite masks.
KviPointerList< KviMaskEntry > * inviteList ()
Returns the list of invites set.
bool isChanAdmin (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a chan admin.
bool isChanOwner (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a chan owner.
bool isDeadChan ()
Returns true if the channel is dead.
bool isHalfOp (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a half operator.
bool isHighlightedUser (const QString &szNick)
Returns true if the user is highlighted.
bool isMeChanAdmin (bool bAtLeast=false)
Returns true if we are a chan admin.
bool isMeChanOwner (bool bAtLeast=false)
Returns true if we are a chan owner.
bool isMeHalfOp (bool bAtLeast=false)
Returns true if we are a half operator.
bool isMeIrcOp (bool bAtLeast=false)
Returns true if we are an ircop.
bool isMeOp (bool bAtLeast=false)
Returns true if we are an operator.
bool isMeUserOp (bool bAtLeast=false)
Returns true if we are a user operator.
bool isMeVoice (bool bAtLeast=false)
Returns true if we are a voice.
bool isOn (const QString &szNick)
Returns true if the user is on the channel.
bool isOp (const QString &szNick, bool bAtLeast=false)
Returns true if the user is an operator.
bool isUserOp (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a user operator.
bool isVoice (const QString &szNick, bool bAtLeast=false)
Returns true if the user is a voice.
KviUserListEntry * join (const QString &szNick, const QString &szUser=QString(), const QString &szHost=QString(), int iFlags=0)
Called when a user joins the channel.
KviChannel (KviFrame *lpFrm, KviConsole *lpConsole, const QString &szName)
Constructs the channel object.
kvi_time_t lastReceivedWhoReply ()
Returns the time of the last received WHO reply.
QByteArray loadLogFile (const QString &szFileName, bool bGzip)
Loads a log file.
virtual void lostUserFocus ()
Called when the channel losts the focus by the user.
KviIrcView * messageView () const
Returns the irc view object.
int myFlags ()
Returns our flags.
const QString & nameWithUserFlag ()
Returns the name of the channel with user flags.
QString * nextSelectedNickname ()
Returns the next selected nickname in the userlist.
bool nickChange (const QString &szOldNick, const QString &szNewNick)
Called when someone changes his nick.
int opCount ()
Returns the number of users with op status.
virtual void outputMessage (int iMsgType, const QString &szMsg)
Outputs a message to the channel window.
void ownAction (const QString &szBuffer)
Called when we perform an action.
void ownMessage (const QString &szBuffer)
Called when we send a message.
bool part (const QString &szNick)
Called when someone parts the channel.
void partMessageSent (bool bCloseOnPart=true, bool bShowMessage=true)
Called when we want to part a channel.
void pasteLastLog ()
Pastes the most recent channel log into the buffer.
void prependUserFlag (const QString &szNick, QString &szBuffer)
Prepends the user flag to the nickname.
unsigned int quietBanCount ()
Returns the number of quiet ban masks.
KviPointerList< KviMaskEntry > * quietBanList ()
Returns the list of quiet bans set.
void removeHighlightedUser (const QString &szNick)
Removes a user from the highlight list.
int selectedCount ()
Returns the number of selected users.
bool sentBanExceptionListRequest ()
Returns true if we have sent the ban exception list request.
bool sentBanListRequest ()
Returns true if we have sent the ban list request.
bool sentInviteListRequest ()
Returns true if we have sent the invite list request.
bool sentQuietBanListRequest ()
Returns true if we have sent the quiet ban list request.
bool sentSyncWhoRequest ()
Returns true if we have sent the sync WHO request.
bool sentWhoRequest ()
Returns true if we have sent the WHO request.
void setAliveChan ()
Sets the channel as alive.
void setBanExceptionListDone ()
Clears the ban exception request flag.
void setBanListDone ()
Clears the ban request flag.
bool setChanAdmin (const QString &szNick, bool bChanAdmin)
Sets the chan admin mode.
void setChannelKey (const char *pcKey)
Sets the key for the channel.
void setChannelLimit (const char *pcLimit)
Sets the limit for the channel.
void setChannelMode (char cMode, bool bAdd)
Sets the channel mode.
bool setChanOwner (const QString &szNick, bool bChanOwner)
Sets the chan owner mode.
void setDeadChan ()
Sets the channel as dead.
bool setHalfOp (const QString &szNick, bool bHalfOp)
Sets the half operator mode.
void setHasAllNames ()
Sets the existance of all names.
void setHasBanExceptionList ()
Sets the existance of the ban exception list.
void setHasBanList ()
Sets the existance of the ban list.
void setHasInviteList ()
Sets the existance of the invite list.
void setHasQuietBanList ()
Sets the existance of the quiet ban list.
void setHasWhoList ()
Sets the existance of the WHO list.
void setInviteListDone ()
Clears the invite request flag.
void setLastReceivedWhoReply (kvi_time_t tTime)
Sets the time of the last received WHO reply.
void setMask (char cFlag, const QString &szMask, bool bAdd, const QString &szSetBy, unsigned int uSetAt)
Called when someone sets a mask in the channel's lists.
bool setOp (const QString &szNick, bool bOp)
Sets the operator mode.
void setQuietBanListDone ()
Clears the quiet ban request flag.
void setSentBanExceptionListRequest ()
Sets the ban exception request flag.
void setSentBanListRequest ()
Sets the ban request flag.
void setSentInviteListRequest ()
Sets the invite request flag.
void setSentQuietBanListRequest ()
Sets the quiet ban request flag.
void setSentSyncWhoRequest ()
Sets the sync WHO request flag.
void setSentWhoRequest ()
Sets the WHO request flag.
bool setUserOp (const QString &szNick, bool bUserOp)
Sets the user operator mode.
bool setVoice (const QString &szNick, bool bVoice)
Sets the voice mode.
virtual QSize sizeHint () const
Returns the size of the channel.
virtual const QString & target ()
Returns the name of the channel.
KviTopicWidget * topicWidget ()
Returns the topic widget object.
void unhighlight ()
Unhighlights the windowlist item.
void updateModeLabel ()
Updates the tooltip over the channel modes.
void userAction (const QString &szNick, const QString &szUser, const QString &szHost, unsigned int uActionType)
Perform a user action in the channel.
void userAction (const QString &szNick, unsigned int uActionType)
Perform a user action in the channel.
void userAction (KviIrcMask *user, unsigned int uActionType)
Perform a user action in the channel.
KviUserListView * userListView ()
Returns the user listview object.
int userOpCount ()
Returns the number of users with userop status.
int voiceCount ()
Returns the number of users with voice status.
~KviChannel ()
Destroys the channel object.
Protected Member Functions
virtual void applyOptions ()
Applies the options.
void checkChannelSync ()
Checks the channel synchronization time.
virtual void closeEvent (QCloseEvent *e)
bool eventFilter (QObject *o, QEvent *e)
Filters the events.
virtual void fillCaptionBuffers ()
Fills in the caption buffers.
void fixActionHistory ()
Fixes the action history.
virtual void getBaseLogFileName (QString &szBuffer)
Gets the base name for log file.
virtual void getConfigGroupName (QString &szBuffer)
Gets the group name.
void getTalkingUsersStats (QString &szBuffer, QStringList &list, bool bPast)
Gets the talking user stats to fill in the tooltip.
void internalMask (const QString &szMask, bool bAdd, const QString &szSetBy, unsigned int uSetAt, KviPointerList< KviMaskEntry > *l, KviMaskEditor **ppEd)
Called when someone sets a mask in the channel's lists.
virtual void loadProperties (KviConfig *cfg)
Loads the properties from file.
virtual QPixmap * myIconPtr ()
Returns the correct icon for the channel.
virtual void preprocessMessage (QString &szMessage)
Preprocess message stripping control bytes.
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfig *cfg)
Saves the properties to file.
void showDoubleView (bool bShow)
Splits the channel view into two views.
void toggleEditor (KviMaskEditor **ppEd, KviWindowToolPageButton **ppBtn, KviPointerList< KviMaskEntry > *l, char cFlag, const char *pcEdName)
Called when we toggle bans, quiet bans, exceptions or invites editor.
virtual void triggerCreationEvents ()
Trigger the OnChannelWindowCreated event.
Protected Attributes
int m_iStateFlags
QDateTime m_joinTime
KviPointerList
< KviChannelAction > * m_pActionHistory
KviMaskEditor * m_pBanEditor
KviWindowToolPageButton * m_pBanEditorButton
KviMaskEditor * m_pBanExceptionEditor
KviWindowToolPageButton * m_pBanExceptionEditorButton
KviPointerList< KviMaskEntry > * m_pBanExceptionList
KviPointerList< KviMaskEntry > * m_pBanList
KviTalHBox * m_pButtonContainer
QToolButton * m_pDoubleViewButton
KviMaskEditor * m_pInviteEditor
KviWindowToolPageButton * m_pInviteEditorButton
KviPointerList< KviMaskEntry > * m_pInviteList
KviWindowToolPageButton * m_pListViewButton
KviIrcView * m_pMessageView
KviModeEditor * m_pModeEditor
KviWindowToolPageButton * m_pModeEditorButton
KviModeWidget * m_pModeWidget
KviMaskEditor * m_pQuietBanEditor
KviWindowToolPageButton * m_pQuietBanEditorButton
KviPointerList< KviMaskEntry > * m_pQuietBanList
KviPixmap m_privateBackground
QStringList * m_pTmpHighLighted
KviTopicWidget * m_pTopicWidget
KviTalSplitter * m_pTopSplitter
KviUserListView * m_pUserListView
KviTalSplitter * m_pVertSplitter
QString m_szChannelKey
QString m_szChannelLimit
QString m_szChannelMode
QString m_szNameWithUserFlag
kvi_time_t m_tLastReceivedWhoReply
unsigned int m_uActionHistoryHotActionCount
QList< int > m_VertSplitterSizesList
Private Slots
void modeSelectorDone ()
Called when we close the mode editor.
void removeMasks (KviMaskEditor *pEd, KviPointerList< KviMaskEntry > *pList)
Removes the masks from the mask editor window.
void setMode (const char *pcMode)
Called when we select the modes from the mode editor.
void textViewRightClicked ()
Called when we right-click the irc view.
void toggleBanEditor ()
Toggles the ban editor.
void toggleBanExceptionEditor ()
Toggles the ban exception editor.
void toggleDoubleView ()
Toggles the double view mode.
void toggleInviteEditor ()
Toggles the invite editor.
void toggleListView ()
Toggles the userlist view.
void toggleModeEditor ()
Toggles the mode editor.
void toggleQuietBanEditor ()
Toggles the quiet ban editor.
void toggleToolButtons ()
Toggles tool buttons widget over the listview.
void topicSelected (const QString &szTopic)
Called when we select the topic.
Detailed Description
The class which manages a channel.
Constructor & Destructor Documentation
KviChannel::KviChannel (KviFrame * lpFrm, KviConsole * lpConsole, const QString & szName)
Constructs the channel object.
Parameters:
lpFrm The parent frame object
lpConsole The console of the context
szName The name of the channel
Returns:
KviChannel
References __tr2qs, KviTalToolTip::add(), applyOptions(), buttonContainer(), KviWindow::connection(), KviWindow::createCryptControllerButton(), KviWindow::createTextEncodingButton(), g_pIconManager, KviIconManager::getBigIcon(), KVI_OPTION_BOOL, KVI_SMALLICON_BAN, KVI_SMALLICON_BANEXCEPT, KVI_SMALLICON_BANUNEXCEPT, KVI_SMALLICON_CHANMODE, KVI_SMALLICON_CHANMODEHIDE, KVI_SMALLICON_HIDEDOUBLEVIEW, KVI_SMALLICON_HIDELISTVIEW, KVI_SMALLICON_INVITEEXCEPT, KVI_SMALLICON_INVITEUNEXCEPT, KVI_SMALLICON_SHOWDOUBLEVIEW, KVI_SMALLICON_SHOWLISTVIEW, KVI_SMALLICON_UNBAN, kvi_time_t, KviWindow::KviInput, KviOption_boolAutoLogChannels, m_iStateFlags, m_joinTime, m_pActionHistory, m_pBanEditor, m_pBanEditorButton, m_pBanExceptionEditor, m_pBanExceptionEditorButton, m_pBanExceptionList, m_pBanList, KviWindow::m_pButtonBox, m_pButtonContainer, KviWindow::m_pConsole, m_pDoubleViewButton, KviWindow::m_pHideToolsButton, KviWindow::m_pInput, m_pInviteEditor, m_pInviteEditorButton, m_pInviteList, KviWindow::m_pIrcView, m_pListViewButton, m_pMessageView, m_pModeEditor, m_pModeEditorButton, m_pModeWidget, m_pQuietBanEditor, m_pQuietBanEditorButton, m_pQuietBanList, KviWindow::m_pSplitter, m_pTmpHighLighted, m_pTopicWidget, m_pTopSplitter, m_pUserListView, m_pVertSplitter, m_tLastReceivedWhoReply, m_uActionHistoryHotActionCount, KviIrcConnection::registerChannel(), KviIrcConnection::serverInfo(), KviPointerList< T >::setAutoDelete(), KviTalHBox::setMargin(), KviTalHBox::setSpacing(), KviTalHBox::setStretchFactor(), KviIrcView::startLogging(), KviIrcConnectionServerInfo::supportedListModes(), textViewRightClicked(), toggleBanEditor(), toggleBanExceptionEditor(), toggleDoubleView(), toggleInviteEditor(), toggleListView(), toggleModeEditor(), toggleQuietBanEditor(), toggleToolButtons(), and topicSelected().
KviChannel::~KviChannel ()
Destroys the channel object.
References KviWindow::connection(), KviWindow::context(), KviUserListView::enableUpdates(), KVI_WINDOW_TYPE_DEADCHANNEL, m_pActionHistory, m_pBanExceptionList, m_pBanList, m_pInviteList, m_pQuietBanList, m_pTmpHighLighted, m_pUserListView, KviUserListView::partAll(), KviWindow::type(), KviIrcConnection::unregisterChannel(), and KviIrcContext::unregisterDeadChannel().
Member Function Documentation
bool KviChannel::activityMeter (unsigned int * puActivityValue, unsigned int * puActivityTemperature) [virtual]
Colors the icon who tells how much activity there is.
Parameters:
puActivityValue The value of the activity
puActivityTemperature The temperature of the activity
Returns:
bool
Reimplemented from KviWindow.
References KviPointerList< T >::count(), fixActionHistory(), KVI_ACTIVITY_COLD, KVI_ACTIVITY_FIRE, KVI_ACTIVITY_HIGH, KVI_ACTIVITY_HOT, KVI_ACTIVITY_ICE, KVI_ACTIVITY_LOW, KVI_ACTIVITY_MEDIUM, KVI_ACTIVITY_NONE, KVI_ACTIVITY_UNDEFINED, KVI_ACTIVITY_VERYCOLD, KVI_ACTIVITY_VERYHIGH, KVI_ACTIVITY_VERYHOT, KVI_ACTIVITY_VERYLOW, KVI_CHANACTIVITY_LIMIT_COLD, KVI_CHANACTIVITY_LIMIT_HOT, KVI_CHANACTIVITY_LIMIT_ICE, KVI_CHANACTIVITY_LIMIT_UNDEFINED, KVI_CHANACTIVITY_LIMIT_VERYCOLD, KVI_CHANACTIVITY_LIMIT_VERYHOT, KVI_CHANNEL_ACTION_HISTORY_MAX_COUNT, KVI_CHANNEL_ACTION_HISTORY_MAX_TIMESPAN, kvi_time_t, kvi_unixTime, KviPointerList< T >::last(), m_joinTime, m_pActionHistory, m_uActionHistoryHotActionCount, and _KviChannelAction::tTime.
void KviChannel::addHighlightedUser (const QString & szNick)
Adds a user to the highlight list.
Parameters:
szNick The nickname of the user
Returns:
void
References KviUserListView::findEntry(), m_pTmpHighLighted, and m_pUserListView.
void KviChannel::applyOptions () [protected, virtual]
Applies the options.
Returns:
void
Reimplemented from KviWindow.
References KviThemedLineEdit::applyOptions(), KviIrcView::applyOptions(), KviTopicWidget::applyOptions(), KviUserListView::applyOptions(), m_pMessageView, m_pModeWidget, m_pTopicWidget, and m_pUserListView.
Referenced by KviChannel().
bool KviChannel::avatarChanged (const QString & szNick) [inline]
Returns true if the avatar of a user is changed.
Parameters:
szNick The nickname of the user
Returns:
bool
unsigned int KviChannel::banCount () [inline]
Returns the number of ban masks.
Returns:
unsigned int
unsigned int KviChannel::banExceptionCount () [inline]
Returns the number of ban exceptions masks list.
Returns:
unsigned int
KviPointerList<KviMaskEntry>* KviChannel::banExceptionList () [inline]
Returns the list of ban exceptions set.
Returns:
KviPointerList<KviMaskEntry> *
KviPointerList<KviMaskEntry>* KviChannel::banList () [inline]
Returns the list of bans set.
Returns:
KviPointerList<KviMaskEntry> *
QFrame* KviChannel::buttonContainer () [inline, virtual]
Returns the button container object.
Returns:
QFrame *
Reimplemented from KviWindow.
Referenced by KviChannel(), loadProperties(), saveProperties(), and toggleToolButtons().
int KviChannel::chanAdminCount () [inline]
Returns the number of users with chanadmin status.
Returns:
int
void KviChannel::channelAction (const QString & szNick, unsigned int uActionType, int iTemperature)
Called when someone perform an action in the channel.
Parameters:
szNick The nickname of the user who made the action
uActionType The type of the action
iTemperature The temperature of the action
Returns:
void
References KviPointerList< T >::append(), fixActionHistory(), _KviChannelAction::iTemperature, kvi_unixTime, m_pActionHistory, m_uActionHistoryHotActionCount, _KviChannelAction::szNick, _KviChannelAction::tTime, and _KviChannelAction::uActionType.
Referenced by nickChange(), part(), and userAction().
QString& KviChannel::channelKey () [inline]
Returns the channel key.
Returns:
QString &
Referenced by KviIrcContext::connectionTerminated(), KviServerParser::parseLiteralKick(), and KviModeWidget::refreshModes().
QString& KviChannel::channelLimit () [inline]
Returns the limit number.
Returns:
QString &
Referenced by KviModeWidget::refreshModes().
QString KviChannel::channelMode () [inline]
Returns the channel mode.
Returns:
QString
Referenced by KviModeWidget::editorReturnPressed(), KviModeWidget::refreshModes(), and KviModeWidget::reset().
int KviChannel::chanOwnerCount () [inline]
Returns the number of users with chanowner status.
Returns:
int
void KviChannel::checkChannelSync () [protected]
Checks the channel synchronization time.
Returns:
void
References __tr2qs, KVI_CHANNEL_STATE_HAVEBANEXCEPTIONLIST, KVI_CHANNEL_STATE_HAVEBANLIST, KVI_CHANNEL_STATE_HAVEINVITELIST, KVI_CHANNEL_STATE_HAVEQUIETBANLIST, KVI_CHANNEL_STATE_HAVEWHOLIST, KVI_CHANNEL_STATE_SENTBANEXCEPTIONLISTREQUEST, KVI_CHANNEL_STATE_SENTBANLISTREQUEST, KVI_CHANNEL_STATE_SENTINVITELISTREQUEST, KVI_CHANNEL_STATE_SENTQUIETBANLISTREQUEST, KVI_CHANNEL_STATE_SENTWHOREQUEST, KVI_CHANNEL_STATE_SYNCHRONIZED, KVI_OPTION_BOOL, KVI_OUT_SYSTEMMESSAGE, KviEvent_OnChannelSync, KviOption_boolShowChannelSyncTime, KVS_TRIGGER_EVENT_1_HALTED, m_iStateFlags, m_joinTime, and KviWindow::output().
void KviChannel::clearSentSyncWhoRequest () [inline]
Clears the sync WHO request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTSYNCWHOREQUEST.
Referenced by KviServerParser::parseNumericEndOfWho().
void KviChannel::closeEvent (QCloseEvent * e) [protected, virtual]
Reimplemented from KviWindow.
References KviKvsVariant::asString(), KviWindow::connection(), KviWindow::context(), KviIrcConnection::encodeText(), KviWindow::encodeText(), KviKvsScript::evaluate(), KviConsole::isConnected(), KVI_CHANNEL_STATE_DEADCHAN, KVI_CHANNEL_STATE_SENTPART, KVI_OPTION_STRING, KviOption_stringPartMessage, m_iStateFlags, KviWindow::m_pConsole, KviWindow::m_szName, partMessageSent(), KviIrcConnection::sendFmtData(), and KviIrcContext::unregisterDeadChannel().
bool KviChannel::closeOnPart () [inline]
Returns true if the channel has to be closed on part.
Returns:
bool
References KVI_CHANNEL_STATE_NOCLOSEONPART.
Referenced by KviServerParser::parseLiteralPart().
unsigned int KviChannel::count () [inline]
Returns the number of users.
Returns:
unsigned int
Referenced by KviIrcView::doLinkToolTip().
void KviChannel::enableUserListUpdates (bool bEnable) [inline]
Enables or disable the userlist updates.
Parameters:
bEnable Whether to enable the updates
Returns:
void
Referenced by KviServerParser::parseNumericNames().
bool KviChannel::eventFilter (QObject * o, QEvent * e) [protected]
Filters the events.
Parameters:
o The object
e The event
Returns:
bool
Reimplemented from KviWindow.
References KviTopicWidget::deactivate(), and m_pTopicWidget.
void KviChannel::fillCaptionBuffers () [protected, virtual]
Fills in the caption buffers.
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), getChannelModeString(), getUserFlag(), KviWindow::m_szName, m_szNameWithUserFlag, and KviWindow::m_szPlainTextCaption.
KviUserListEntry* KviChannel::findEntry (const QString & szNick) [inline]
Searches for a user in the userlist.
Parameters:
szNick The nickname of the user to find
Returns:
KviUserListEntry *
Referenced by preprocessMessage().
QString* KviChannel::firstSelectedNickname () [inline]
Returns the first selected nickname in the userlist.
Returns:
QString *
void KviChannel::fixActionHistory () [protected]
Fixes the action history.
Returns:
void
References KviPointerList< T >::count(), KviPointerList< T >::first(), _KviChannelAction::iTemperature, KVI_CHANNEL_ACTION_HISTORY_MAX_COUNT, KVI_CHANNEL_ACTION_HISTORY_MAX_TIMESPAN, kvi_time_t, KviPointerList< T >::last(), m_pActionHistory, m_uActionHistoryHotActionCount, KviPointerList< T >::removeFirst(), and _KviChannelAction::tTime.
Referenced by activityMeter(), channelAction(), and getChannelActivityStats().
void KviChannel::getBaseLogFileName (QString & szBuffer) [protected, virtual]
Gets the base name for log file.
Parameters:
szBuffer The buffer where to save data
Returns:
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviWindow::context(), and KviWindow::windowName().
void KviChannel::getChannelActivityStats (KviChannelActivityStats * s)
Gets the channel activity stats and put them in the buffer.
Parameters:
s The buffer where to store the data
Returns:
void
References _KviChannelActivityStats::bStatsInaccurate, KviPointerList< T >::count(), _KviChannelActivityStats::dActionsPerMinute, KviPointerList< T >::first(), fixActionHistory(), _KviChannelActivityStats::iAverageActionTemperature, isOn(), _KviChannelAction::iTemperature, KVI_CHANNEL_ACTION_HISTORY_MAX_COUNT, KVI_CHANNEL_ACTION_HISTORY_MAX_TIMESPAN, kvi_time_t, kvi_unixTime, KVI_USERACTION_ACTION, KVI_USERACTION_NOTICE, KVI_USERACTION_PRIVMSG, KviPointerList< T >::last(), _KviChannelActivityStats::lTalkingUsers, _KviChannelActivityStats::lWereTalkingUsers, m_joinTime, m_pActionHistory, KviPointerList< T >::prev(), _KviChannelAction::szNick, _KviChannelAction::tTime, _KviChannelActivityStats::uActionCount, _KviChannelActivityStats::uActionsInTheLastMinute, _KviChannelAction::uActionType, _KviChannelActivityStats::uFirstActionTimeSpan, _KviChannelActivityStats::uHotActionCount, _KviChannelActivityStats::uHotActionPercent, and _KviChannelActivityStats::uLastActionTimeSpan.
Referenced by getWindowListTipText().
void KviChannel::getChannelModeString (QString & szBuffer)
Gets the channel mode string and saves it in the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
References m_szChannelKey, m_szChannelLimit, and m_szChannelMode.
Referenced by KviIrcView::doLinkToolTip(), fillCaptionBuffers(), and KviTopicWidget::switchMode().
void KviChannel::getConfigGroupName (QString & szBuffer) [protected, virtual]
Gets the group name.
Parameters:
szBuffer The buffer where to save the data
Returns:
void
Reimplemented from KviWindow.
References KviWindow::windowName().
void KviChannel::getTalkingUsersStats (QString & szBuffer, QStringList & list, bool bPast) [protected]
Gets the talking user stats to fill in the tooltip.
Parameters:
szBuffer The buffer where to store the data
list The list of talking users
bPast Whether the activity is recent or in the past
Returns:
void
References __tr2qs.
Referenced by getWindowListTipText().
char KviChannel::getUserFlag (const QString & szNick) [inline]
Returns the flag of a user.
Parameters:
szNick The nick of the user
Returns:
char
Referenced by fillCaptionBuffers().
void KviChannel::getWindowListTipText (QString & szBuffer) [virtual]
Creates the tooltip over the channel treeview.
Parameters:
szBuffer The buffer where to store the data
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, _KviChannelActivityStats::bStatsInaccurate, _KviChannelActivityStats::dActionsPerMinute, END_TABLE_BOLD_ROW, getChannelActivityStats(), getTalkingUsersStats(), KVI_CHANNEL_STATE_DEADCHAN, _KviChannelActivityStats::lTalkingUsers, _KviChannelActivityStats::lWereTalkingUsers, m_iStateFlags, m_pUserListView, KviWindow::m_szPlainTextCaption, s, START_TABLE_BOLD_ROW, _KviUserListViewUserStats::uActive, _KviUserListViewUserStats::uActiveOp, _KviUserListViewUserStats::uChanAdmin, _KviUserListViewUserStats::uChanOwner, _KviUserListViewUserStats::uHalfOp, _KviUserListViewUserStats::uHot, _KviChannelActivityStats::uHotActionPercent, _KviUserListViewUserStats::uHotOp, _KviUserListViewUserStats::uIrcOp, _KviUserListViewUserStats::uOp, KviUserListView::userStats(), _KviUserListViewUserStats::uTotal, _KviUserListViewUserStats::uUserOp, and _KviUserListViewUserStats::uVoiced.
int KviChannel::halfOpCount () [inline]
Returns the number of users with halfop status.
Returns:
int
bool KviChannel::hasAllNames () [inline]
Returns true if the channel has all names.
Returns:
bool
References KVI_CHANNEL_STATE_HAVEALLNAMES.
Referenced by KviServerParser::parseNumericEndOfNames(), and KviServerParser::parseNumericNames().
bool KviChannel::hasBanExceptionList () [inline]
Returns true if the channel has a ban exception list.
Returns:
bool
References KVI_CHANNEL_STATE_HAVEBANEXCEPTIONLIST.
Referenced by toggleEditor().
bool KviChannel::hasBanList () [inline]
Returns true if the channel has a ban list.
Returns:
bool
References KVI_CHANNEL_STATE_HAVEBANLIST.
Referenced by toggleEditor().
bool KviChannel::hasChannelKey () [inline]
Returns true if the channel has a key set.
Returns:
bool
bool KviChannel::hasChannelLimit () [inline]
Returns true if the channel has a limit set.
Returns:
bool
bool KviChannel::hasInviteList () [inline]
Returns true if the channel has an invite list.
Returns:
bool
References KVI_CHANNEL_STATE_HAVEINVITELIST.
Referenced by toggleEditor().
bool KviChannel::hasQuietBanList () [inline]
Returns true if the channel has a quiet ban list.
Returns:
bool
References KVI_CHANNEL_STATE_HAVEQUIETBANLIST.
Referenced by toggleEditor().
bool KviChannel::hasWhoList () [inline]
Returns true if the channel has a WHO list.
Returns:
bool
References KVI_CHANNEL_STATE_HAVEWHOLIST.
Referenced by KviServerParser::parseNumericEndOfWho(), and KviServerParser::parseNumericWhoReply().
void KviChannel::internalMask (const QString & szMask, bool bAdd, const QString & szSetBy, unsigned int uSetAt, KviPointerList< KviMaskEntry > * l, KviMaskEditor ** ppEd) [protected]
Called when someone sets a mask in the channel's lists.
Parameters:
szMask The mask set
bAdd Whether to add or remove the mask
szSetBy Who set the mask
uSetAt The datetime when the mask was set
l The list of masks in the channel lists
ppEd The mask editor window
Returns:
void
References __tr2qs, KviPointerList< T >::append(), KviQString::equalCI(), KviPointerList< T >::first(), KviPointerList< T >::next(), KviPointerList< T >::removeRef(), _KviMaskEntry::szMask, _KviMaskEntry::szSetBy, and _KviMaskEntry::uSetAt.
Referenced by setMask().
unsigned int KviChannel::inviteCount () [inline]
Returns the number of invite masks.
Returns:
unsigned int
KviPointerList<KviMaskEntry>* KviChannel::inviteList () [inline]
Returns the list of invites set.
Returns:
KviPointerList<KviMaskEntry> *
bool KviChannel::isChanAdmin (const QString & szNick, bool bAtLeast = false) [inline]
Returns true if the user is a chan admin.
Parameters:
szNick The nickname of the user to check
bAtLeast Whether the user is at least a chan admin
Returns:
bool
bool KviChannel::isChanOwner (const QString & szNick, bool bAtLeast = false) [inline]
Returns true if the user is a chan owner.
Parameters:
szNick The nickname of the user to check
bAtLeast Whether the user is at least a chan owner
Returns:
bool
bool KviChannel::isDeadChan () [inline]
Returns true if the channel is dead.
Returns:
bool
References KVI_CHANNEL_STATE_DEADCHAN.
bool KviChannel::isHalfOp (const QString & szNick, bool bAtLeast = false) [inline]
Returns true if the user is a half operator.
Parameters:
szNick The nickname of the user to check
bAtLeast Whether the user is at least a half operator
Returns:
bool
bool KviChannel::isHighlightedUser (const QString & szNick) [inline]
Returns true if the user is highlighted.
Parameters:
szNick The nickname of the user
Returns:
bool
bool KviChannel::isMeChanAdmin (bool bAtLeast = false)
Returns true if we are a chan admin.
Parameters:
bAtLeast Whether we are at least a chan admin
Returns:
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviMaskEditor::KviMaskEditor(), KviModeEditor::KviModeEditor(), KviModeWidget::mouseDoubleClickEvent(), and KviTopicWidget::switchMode().
bool KviChannel::isMeChanOwner (bool bAtLeast = false)
Returns true if we are a chan owner.
Parameters:
bAtLeast Whether we are at least a chan owner
Returns:
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviMaskEditor::KviMaskEditor(), KviModeEditor::KviModeEditor(), KviModeWidget::mouseDoubleClickEvent(), and KviTopicWidget::switchMode().
bool KviChannel::isMeHalfOp (bool bAtLeast = false)
Returns true if we are a half operator.
Parameters:
bAtLeast Whether we are at least a half operator
Returns:
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviMaskEditor::KviMaskEditor(), KviModeEditor::KviModeEditor(), KviModeWidget::mouseDoubleClickEvent(), and KviTopicWidget::switchMode().
bool KviChannel::isMeIrcOp (bool bAtLeast = false)
Returns true if we are an ircop.
Parameters:
bAtLeast Whether we are at least an ircop
Returns:
bool
bool KviChannel::isMeOp (bool bAtLeast = false)
Returns true if we are an operator.
Parameters:
bAtLeast Whether we are at least an operator
Returns:
bool
Referenced by KviMaskEditor::addClicked(), KviMaskEditor::itemDoubleClicked(), KviMaskEditor::KviMaskEditor(), KviModeEditor::KviModeEditor(), KviModeWidget::mouseDoubleClickEvent(), KviTopicWidget::switchMode(), and KviRequestQueue::timerSlot().
bool KviChannel::isMeUserOp (bool bAtLeast = false)
Returns true if we are a user operator.
Parameters:
bAtLeast Whether we are at least a user operator
Returns:
bool
bool KviChannel::isMeVoice (bool bAtLeast = false)
Returns true if we are a voice.
Parameters:
bAtLeast Whether we are at least a voice
Returns:
bool
bool KviChannel::isOn (const QString & szNick) [inline]
Returns true if the user is on the channel.
Parameters:
szNick The nickname of the user
Returns:
bool
Referenced by getChannelActivityStats().
bool KviChannel::isOp (const QString & szNick, bool bAtLeast = false) [inline]
Returns true if the user is an operator.
Parameters:
szNick The nickname of the user to check
bAtLeast Whether the user is at least an operator
Returns:
bool
bool KviChannel::isUserOp (const QString & szNick, bool bAtLeast = false) [inline]
Returns true if the user is a user operator.
Parameters:
szNick The nickname of the user to check
bAtLeast Whether the user is at least a user operator
Returns:
bool
bool KviChannel::isVoice (const QString & szNick, bool bAtLeast = false) [inline]
Returns true if the user is a voice.
Parameters:
szNick The nickname of the user to check
bAtLeast Whether the user is at least a voice
Returns:
bool
KviUserListEntry* KviChannel::join (const QString & szNick, const QString & szUser = QString(), const QString & szHost = QString(), int iFlags = 0) [inline]
Called when a user joins the channel.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
iFlags The flags of the user
Returns:
KviUserListEntry *
Referenced by KviServerParser::parseLiteralJoin(), and KviServerParser::parseNumericNames().
kvi_time_t KviChannel::lastReceivedWhoReply () [inline]
Returns the time of the last received WHO reply.
Returns:
kvi_time_t
Referenced by KviIrcConnection::heartbeat().
QByteArray KviChannel::loadLogFile (const QString & szFileName, bool bGzip)
Loads a log file.
It opens a logfile, gzipped or not, and returns the content in a buffer
Parameters:
szFileName The filename of the log file
bGzip Whether the log file is gzipped
Returns:
QByteArray
References debug.
Referenced by pasteLastLog().
void KviChannel::loadProperties (KviConfig * cfg) [protected, virtual]
Loads the properties from file.
Parameters:
cfg The config file
Returns:
void
Reimplemented from KviWindow.
References buttonContainer(), KVI_OPTION_BOOL, KviOption_boolHideWindowToolButtons, KviWindow::m_pIrcView, m_pMessageView, m_privateBackground, KviWindow::m_pSplitter, m_pTopSplitter, m_pUserListView, m_VertSplitterSizesList, KviConfig::readBoolEntry(), KviConfig::readIntListEntry(), KviConfig::readPixmapEntry(), resizeEvent(), KviIrcView::setPrivateBackgroundPixmap(), KviTalSplitter::setSizes(), showDoubleView(), and toggleToolButtons().
void KviChannel::lostUserFocus () [virtual]
Called when the channel losts the focus by the user.
Returns:
void
Reimplemented from KviWindow.
References KviIrcView::clearLineMark(), KviIrcView::hasLineMark(), and m_pMessageView.
KviIrcView* KviChannel::messageView () const [inline]
Returns the irc view object.
Returns:
KviIrcView *
void KviChannel::modeSelectorDone () [private, slot]
Called when we close the mode editor.
References m_pModeEditor, and toggleModeEditor().
Referenced by toggleModeEditor().
int KviChannel::myFlags ()
Returns our flags.
Returns:
int
Referenced by KviServerParser::parseNumericNames().
QPixmap * KviChannel::myIconPtr () [protected, virtual]
Returns the correct icon for the channel.
Returns:
QPixmap *
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), KVI_CHANNEL_STATE_DEADCHAN, KVI_SMALLICON_CHANNEL, KVI_SMALLICON_DEADCHANNEL, and m_iStateFlags.
const QString& KviChannel::nameWithUserFlag () [inline]
Returns the name of the channel with user flags.
Returns:
const QString &
QString* KviChannel::nextSelectedNickname () [inline]
Returns the next selected nickname in the userlist.
Returns:
QString *
bool KviChannel::nickChange (const QString & szOldNick, const QString & szNewNick)
Called when someone changes his nick.
Parameters:
szOldNick The old nickname of the user
szNewNick The new nickname of the user
Returns:
bool
References channelAction(), kvi_getUserActionTemperature(), KVI_USERACTION_NICK, m_pUserListView, and KviUserListView::nickChange().
int KviChannel::opCount () [inline]
Returns the number of users with op status.
Returns:
int
void KviChannel::outputMessage (int iMsgType, const QString & szMsg) [virtual]
Outputs a message to the channel window.
Parameters:
iMsgType The type of the message
szMsg The message :)
Returns:
void
References KviWindow::internalOutput(), KviWindow::m_pIrcView, m_pMessageView, KviQString::nullTerminatedArray(), and preprocessMessage().
Referenced by ownAction(), and pasteLastLog().
void KviChannel::ownAction (const QString & szBuffer) [virtual]
Called when we perform an action.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviIrcConnection::currentNickName(), d, KviWindow::encodeText(), KVI_OPTION_BOOL, KVI_OUT_ACTION, KVI_USERACTION_ACTION, KviEvent_OnMeAction, KviOption_boolStripMircColorsInUserMessages, KVS_TRIGGER_EVENT_2_HALTED, KviWindow::m_szName, outputMessage(), KviMircCntrl::stripControlBytes(), and userAction().
void KviChannel::ownMessage (const QString & szBuffer) [virtual]
Called when we send a message.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), d, KviWindow::decodeText(), KviWindow::encodeText(), KviIrcConnection::encodeText(), KviIrcConnectionUserInfo::hostName(), KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_SYSTEMERROR, KVI_TEXT_CRYPTESCAPE, KVI_USERACTION_PRIVMSG, KviWindow::m_pConsole, KviWindow::makeEncoder(), KviIrcConnectionUserInfo::nickName(), KviConsole::NoNotifications, KviWindow::output(), KviConsole::outputPrivmsg(), KviStr::ptr(), KviIrcConnection::sendFmtData(), userAction(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), and KviWindow::windowName().
bool KviChannel::part (const QString & szNick)
Called when someone parts the channel.
Parameters:
szNick The nickname of the user who parts
Returns:
bool
References channelAction(), kvi_getUserActionTemperature(), KVI_USERACTION_PART, m_pUserListView, and KviUserListView::part().
Referenced by KviServerParser::parseLiteralKick(), and KviServerParser::parseLiteralPart().
void KviChannel::partMessageSent (bool bCloseOnPart = true, bool bShowMessage = true)
Called when we want to part a channel.
Parameters:
bCloseOnPart Whether to leave channel open after part
bShowMessage Whether to show part message
Returns:
void
References __tr2qs, KVI_CHANNEL_STATE_NOCLOSEONPART, KVI_CHANNEL_STATE_SENTPART, KVI_OUT_SYSTEMMESSAGE, m_iStateFlags, and KviWindow::outputNoFmt().
Referenced by closeEvent(), and KviKvsCoreSimpleCommands::KVSCSC().
void KviChannel::pasteLastLog ()
Pastes the most recent channel log into the buffer.
It searches for the most recent channel log of the channel we have just joined, and pastes into the buffer the last N lines, where N is get from the options
Returns:
void
References __tr2qs, KviWindow::console(), KviConsole::currentNetworkName(), g_pApp, KviApp::getLocalKvircDirectory(), KVI_OPTION_UINT, KVI_OUT_CHANPRIVMSG, KviOption_uintDaysIntervalToPasteOnChannelJoin, KviOption_uintLinesToPasteOnChannelJoin, loadLogFile(), KviApp::Log, outputMessage(), and target().
Referenced by KviServerParser::parseLiteralJoin().
void KviChannel::prependUserFlag (const QString & szNick, QString & szBuffer) [inline]
Prepends the user flag to the nickname.
Parameters:
szNick The nickname of the user
szBuffer The buffer :)
Returns:
void
void KviChannel::preprocessMessage (QString & szMessage) [protected, virtual]
Preprocess message stripping control bytes.
Parameters:
szMessage The message :)
Returns:
void
Reimplemented from KviWindow.
References KviWindow::connection(), findEntry(), KviWindow::m_pConsole, KviIrcConnection::serverInfo(), KviMircCntrl::stripControlBytes(), and KviIrcConnectionServerInfo::supportedChannelTypes().
Referenced by outputMessage().
unsigned int KviChannel::quietBanCount () [inline]
Returns the number of quiet ban masks.
Returns:
unsigned int
KviPointerList<KviMaskEntry>* KviChannel::quietBanList () [inline]
Returns the list of quiet bans set.
Returns:
KviPointerList<KviMaskEntry> *
void KviChannel::removeHighlightedUser (const QString & szNick)
Removes a user from the highlight list.
Parameters:
szNick The nickname of the user
Returns:
void
References m_pTmpHighLighted.
void KviChannel::removeMasks (KviMaskEditor * pEd, KviPointerList< KviMaskEntry > * pList) [private, slot]
Removes the masks from the mask editor window.
Parameters:
pEd The mask editor
pList The list of masks to remove
Returns:
void
References KviWindow::connection(), KviIrcConnection::encodeText(), KviPointerList< T >::first(), KviMaskEditor::flag(), KviWindow::m_szName, KviIrcConnectionServerInfo::maxModeChanges(), KviPointerList< T >::next(), KviIrcConnection::sendFmtData(), and KviIrcConnection::serverInfo().
Referenced by toggleEditor().
void KviChannel::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, KviWindow::m_pSplitter, m_pTopicWidget, and KviTopicWidget::sizeHint().
Referenced by loadProperties(), and toggleModeEditor().
void KviChannel::saveProperties (KviConfig * cfg) [protected, virtual]
Saves the properties to file.
Parameters:
cfg The config file
Returns:
void
Reimplemented from KviWindow.
References buttonContainer(), m_pMessageView, m_privateBackground, KviWindow::m_pSplitter, m_pTopSplitter, m_pUserListView, m_pVertSplitter, m_VertSplitterSizesList, KviTalSplitter::sizes(), and KviConfig::writeEntry().
int KviChannel::selectedCount () [inline]
Returns the number of selected users.
Returns:
int
bool KviChannel::sentBanExceptionListRequest () [inline]
Returns true if we have sent the ban exception list request.
Returns:
bool
References KVI_CHANNEL_STATE_SENTBANEXCEPTIONLISTREQUEST.
bool KviChannel::sentBanListRequest () [inline]
Returns true if we have sent the ban list request.
Returns:
bool
References KVI_CHANNEL_STATE_SENTBANLISTREQUEST.
Referenced by KviServerParser::parseNumeric367(), and KviServerParser::parseNumeric368().
bool KviChannel::sentInviteListRequest () [inline]
Returns true if we have sent the invite list request.
Returns:
bool
References KVI_CHANNEL_STATE_SENTINVITELISTREQUEST.
bool KviChannel::sentQuietBanListRequest () [inline]
Returns true if we have sent the quiet ban list request.
Returns:
bool
References KVI_CHANNEL_STATE_SENTQUIETBANLISTREQUEST.
Referenced by KviServerParser::parseNumeric367(), and KviServerParser::parseNumeric368().
bool KviChannel::sentSyncWhoRequest () [inline]
Returns true if we have sent the sync WHO request.
Returns:
bool
References KVI_CHANNEL_STATE_SENTSYNCWHOREQUEST.
Referenced by KviServerParser::parseNumericEndOfWho(), and KviServerParser::parseNumericWhoReply().
bool KviChannel::sentWhoRequest () [inline]
Returns true if we have sent the WHO request.
Returns:
bool
References KVI_CHANNEL_STATE_SENTWHOREQUEST.
void KviChannel::setAliveChan ()
Sets the channel as alive.
Returns:
void
References KviWindow::connection(), KviWindow::context(), KviIrcView::isLogging(), KVI_WINDOW_TYPE_CHANNEL, m_iStateFlags, m_joinTime, KviWindow::m_pIrcView, m_pTopicWidget, m_pUserListView, KviIrcConnection::registerChannel(), KviTopicWidget::reset(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcView::startLogging(), KviIrcContext::unregisterDeadChannel(), KviWindow::updateCaption(), and KviWindow::updateIcon().
Referenced by KviIrcConnection::createChannel().
void KviChannel::setBanExceptionListDone () [inline]
Clears the ban exception request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTBANEXCEPTIONLISTREQUEST.
void KviChannel::setBanListDone () [inline]
Clears the ban request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTBANLISTREQUEST.
Referenced by KviServerParser::parseNumeric368().
bool KviChannel::setChanAdmin (const QString & szNick, bool bChanAdmin) [inline]
Sets the chan admin mode.
Parameters:
szNick The nick to set the mode on
bChanAdmin Whether to set or unset the mode on the user
Returns:
bool
void KviChannel::setChannelKey (const char * pcKey)
Sets the key for the channel.
Parameters:
pcKey The key of the channel
Returns:
void
References m_szChannelKey, KviWindow::updateCaption(), and updateModeLabel().
Referenced by KviServerParser::parseChannelMode().
void KviChannel::setChannelLimit (const char * pcLimit)
Sets the limit for the channel.
Parameters:
pcLimit The limit of the channel
Returns:
void
References m_szChannelLimit, KviWindow::updateCaption(), and updateModeLabel().
Referenced by KviServerParser::parseChannelMode().
void KviChannel::setChannelMode (char cMode, bool bAdd)
Sets the channel mode.
Parameters:
cMode The mode to set
bAdd Whether to add or remove the mode
Returns:
void
References KviWindow::connection(), KviWindow::m_pConsole, m_szChannelMode, KviIrcConnection::serverInfo(), KviIrcConnectionServerInfo::supportedListModes(), KviWindow::updateCaption(), and updateModeLabel().
Referenced by KviServerParser::parseChannelMode().
bool KviChannel::setChanOwner (const QString & szNick, bool bChanOwner) [inline]
Sets the chan owner mode.
Parameters:
szNick The nick to set the mode on
bChanOwner Whether to set or unset the mode on the user
Returns:
bool
Referenced by KviServerParser::parseChannelMode().
void KviChannel::setDeadChan ()
Sets the channel as dead.
Returns:
void
References KviPointerList< T >::clear(), KviWindow::connection(), KviWindow::context(), KviUserListView::enableUpdates(), KVI_CHANNEL_STATE_DEADCHAN, KVI_CHANNEL_STATE_NOCLOSEONPART, KVI_CHANNEL_STATE_SENTSYNCWHOREQUEST, KVI_WINDOW_TYPE_DEADCHANNEL, m_iStateFlags, m_pActionHistory, m_pBanExceptionList, m_pBanList, m_pInviteList, m_pQuietBanList, m_pTopicWidget, m_pUserListView, m_szChannelKey, m_szChannelLimit, m_szChannelMode, m_uActionHistoryHotActionCount, KviUserListView::partAll(), KviIrcContext::registerDeadChannel(), KviTopicWidget::reset(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcConnection::unregisterChannel(), KviWindow::updateCaption(), KviWindow::updateIcon(), and updateModeLabel().
Referenced by KviServerParser::parseLiteralKick(), and KviServerParser::parseLiteralPart().
bool KviChannel::setHalfOp (const QString & szNick, bool bHalfOp) [inline]
Sets the half operator mode.
Parameters:
szNick The nick to set the mode on
bHalfOp Whether to set or unset the mode on the user
Returns:
bool
void KviChannel::setHasAllNames () [inline]
Sets the existance of all names.
Returns:
void
References KVI_CHANNEL_STATE_HAVEALLNAMES.
Referenced by KviServerParser::parseNumericEndOfNames().
void KviChannel::setHasBanExceptionList () [inline]
Sets the existance of the ban exception list.
Returns:
void
References KVI_CHANNEL_STATE_HAVEBANEXCEPTIONLIST.
void KviChannel::setHasBanList () [inline]
Sets the existance of the ban list.
Returns:
void
References KVI_CHANNEL_STATE_HAVEBANLIST.
Referenced by KviServerParser::parseNumeric368().
void KviChannel::setHasInviteList () [inline]
Sets the existance of the invite list.
Returns:
void
References KVI_CHANNEL_STATE_HAVEINVITELIST.
void KviChannel::setHasQuietBanList () [inline]
Sets the existance of the quiet ban list.
Returns:
void
References KVI_CHANNEL_STATE_HAVEQUIETBANLIST.
Referenced by KviServerParser::parseNumeric368().
void KviChannel::setHasWhoList () [inline]
Sets the existance of the WHO list.
Returns:
void
References KVI_CHANNEL_STATE_HAVEWHOLIST.
Referenced by KviServerParser::parseNumericEndOfWho().
void KviChannel::setInviteListDone () [inline]
Clears the invite request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTINVITELISTREQUEST.
void KviChannel::setLastReceivedWhoReply (kvi_time_t tTime) [inline]
Sets the time of the last received WHO reply.
Parameters:
tTime The source time
Returns:
void
Referenced by KviServerParser::parseNumericEndOfWho().
void KviChannel::setMask (char cFlag, const QString & szMask, bool bAdd, const QString & szSetBy, unsigned int uSetAt)
Called when someone sets a mask in the channel's lists.
The type of the mask can be:
b: ban
e: ban exception
I: invite
q: quiet ban
Parameters:
cFlag The type of the mask
szMask The mask set
bAdd Whether to add or remove the mask
szSetBy Who set the mask
uSetAt The datetime when the mask was set
Returns:
void
References KviWindow::connection(), KviPointerList< T >::count(), internalMask(), KVI_CHANNEL_STATE_HAVEBANEXCEPTIONLIST, KVI_CHANNEL_STATE_HAVEBANLIST, KVI_CHANNEL_STATE_HAVEINVITELIST, KVI_CHANNEL_STATE_HAVEQUIETBANLIST, m_iStateFlags, m_pBanEditor, m_pBanExceptionEditor, m_pBanExceptionList, m_pBanList, m_pInviteEditor, m_pInviteList, m_pQuietBanEditor, m_pQuietBanList, m_pUserListView, and KviUserListView::setMaskEntries().
Referenced by KviServerParser::parseChannelMode(), and KviServerParser::parseNumeric367().
void KviChannel::setMode (const char * pcMode) [private, slot]
Called when we select the modes from the mode editor.
Parameters:
pcMode The modes selected
Returns:
void
References KviWindow::connection(), KviIrcConnection::encodeText(), KviWindow::m_szName, and KviIrcConnection::sendFmtData().
Referenced by toggleModeEditor().
bool KviChannel::setOp (const QString & szNick, bool bOp) [inline]
Sets the operator mode.
Parameters:
szNick The nick to set the mode on
bOp Whether to set or unset the mode on the user
Returns:
bool
void KviChannel::setQuietBanListDone () [inline]
Clears the quiet ban request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTQUIETBANLISTREQUEST.
Referenced by KviServerParser::parseNumeric368().
void KviChannel::setSentBanExceptionListRequest () [inline]
Sets the ban exception request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTBANEXCEPTIONLISTREQUEST.
Referenced by KviRequestQueue::timerSlot(), and toggleEditor().
void KviChannel::setSentBanListRequest () [inline]
Sets the ban request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTBANLISTREQUEST.
Referenced by KviRequestQueue::timerSlot(), and toggleEditor().
void KviChannel::setSentInviteListRequest () [inline]
Sets the invite request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTINVITELISTREQUEST.
Referenced by KviRequestQueue::timerSlot(), and toggleEditor().
void KviChannel::setSentQuietBanListRequest () [inline]
Sets the quiet ban request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTQUIETBANLISTREQUEST.
Referenced by KviRequestQueue::timerSlot(), and toggleEditor().
void KviChannel::setSentSyncWhoRequest () [inline]
Sets the sync WHO request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTSYNCWHOREQUEST.
Referenced by KviIrcConnection::heartbeat().
void KviChannel::setSentWhoRequest () [inline]
Sets the WHO request flag.
Returns:
void
References KVI_CHANNEL_STATE_SENTWHOREQUEST.
Referenced by KviRequestQueue::timerSlot().
bool KviChannel::setUserOp (const QString & szNick, bool bUserOp) [inline]
Sets the user operator mode.
Parameters:
szNick The nick to set the mode on
bUserOp Whether to set or unset the mode on the user
Returns:
bool
bool KviChannel::setVoice (const QString & szNick, bool bVoice) [inline]
Sets the voice mode.
Parameters:
szNick The nick to set the mode on
bVoice Whether to set or unset the mode on the user
Returns:
bool
void KviChannel::showDoubleView (bool bShow) [protected]
Splits the channel view into two views.
The upper one will be used to show all system messages like join, parts, quits, topics and so on, while the lower one will be used to show the users messages.
Parameters:
bShow Whether to show the double view
Returns:
void
References KviIrcView::joinMessagesFrom(), m_pDoubleViewButton, KviWindow::m_pFrm, KviWindow::m_pIrcView, m_pMessageView, m_privateBackground, m_pVertSplitter, m_VertSplitterSizesList, KviPixmap::pixmap(), KviIrcView::setMasterView(), KviIrcView::setPrivateBackgroundPixmap(), KviTalSplitter::setSizes(), KviTalSplitter::sizes(), KviIrcView::splitMessagesTo(), and textViewRightClicked().
Referenced by loadProperties(), and toggleDoubleView().
QSize KviChannel::sizeHint () const [virtual]
Returns the size of the channel.
Returns:
QSize
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviIrcView::sizeHint().
virtual const QString& KviChannel::target () [inline, virtual]
Returns the name of the channel.
Returns:
const QString &
Reimplemented from KviWindow.
References KviWindow::windowName().
Referenced by KviMaskInputDialog::accept(), KviModeWidget::editorReturnPressed(), pasteLastLog(), and KviRequestQueue::timerSlot().
void KviChannel::textViewRightClicked () [private, slot]
Called when we right-click the irc view.
Trigger the OnChannelPopupRequest event
Returns:
void
References KviEvent_OnChannelPopupRequest, and KVS_TRIGGER_EVENT_0.
Referenced by KviChannel(), and showDoubleView().
void KviChannel::toggleBanEditor () [private, slot]
Toggles the ban editor.
Returns:
void
References m_pBanEditor, m_pBanEditorButton, m_pBanList, and toggleEditor().
Referenced by KviChannel().
void KviChannel::toggleBanExceptionEditor () [private, slot]
Toggles the ban exception editor.
Returns:
void
References m_pBanExceptionEditor, m_pBanExceptionEditorButton, m_pBanExceptionList, and toggleEditor().
Referenced by KviChannel().
void KviChannel::toggleDoubleView () [private, slot]
Toggles the double view mode.
Returns:
void
References m_pDoubleViewButton, m_pMessageView, and showDoubleView().
Referenced by KviChannel().
void KviChannel::toggleEditor (KviMaskEditor ** ppEd, KviWindowToolPageButton ** ppBtn, KviPointerList< KviMaskEntry > * l, char cFlag, const char * pcEdName) [protected]
Called when we toggle bans, quiet bans, exceptions or invites editor.
Parameters:
ppEd The mask editor
ppBtn The toolpage button
l The masks list
cFlag The type of flag
pcEdName Tee editor name
Returns:
void
References KviPointerList< T >::clear(), KviWindow::connection(), KviIrcConnection::encodeText(), hasBanExceptionList(), hasBanList(), hasInviteList(), hasQuietBanList(), m_pBanExceptionList, m_pBanList, m_pInviteList, m_pQuietBanList, KviWindow::m_pSplitter, KviWindow::m_szName, removeMasks(), KviIrcConnection::sendFmtData(), setSentBanExceptionListRequest(), setSentBanListRequest(), setSentInviteListRequest(), and setSentQuietBanListRequest().
Referenced by toggleBanEditor(), toggleBanExceptionEditor(), toggleInviteEditor(), and toggleQuietBanEditor().
void KviChannel::toggleInviteEditor () [private, slot]
Toggles the invite editor.
Returns:
void
References m_pInviteEditor, m_pInviteEditorButton, m_pInviteList, and toggleEditor().
Referenced by KviChannel().
void KviChannel::toggleListView () [private, slot]
Toggles the userlist view.
Returns:
void
References m_pListViewButton, and m_pUserListView.
Referenced by KviChannel().
void KviChannel::toggleModeEditor () [private, slot]
Toggles the mode editor.
Returns:
void
References KviWindow::console(), KviLocale::done(), m_pModeEditor, m_pModeEditorButton, KviWindow::m_pSplitter, m_szChannelKey, m_szChannelLimit, m_szChannelMode, modeSelectorDone(), resizeEvent(), and setMode().
Referenced by KviChannel(), and modeSelectorDone().
void KviChannel::toggleQuietBanEditor () [private, slot]
Toggles the quiet ban editor.
Returns:
void
References m_pQuietBanEditor, m_pQuietBanEditorButton, m_pQuietBanList, and toggleEditor().
Referenced by KviChannel().
void KviChannel::toggleToolButtons () [private, slot]
Toggles tool buttons widget over the listview.
Returns:
void
References buttonContainer(), g_pIconManager, KviIconManager::getBigIcon(), KviWindow::m_pHideToolsButton, and KviWindow::toggleButtonContainer().
Referenced by KviChannel(), and loadProperties().
void KviChannel::topicSelected (const QString & szTopic) [private, slot]
Called when we select the topic.
Parameters:
szTopic The topic :)
Returns:
void
References KviWindow::connection(), KviIrcConnection::encodeText(), KviWindow::encodeText(), KviWindow::m_szName, and KviIrcConnection::sendFmtData().
Referenced by KviChannel().
KviTopicWidget* KviChannel::topicWidget () [inline]
Returns the topic widget object.
Returns:
KviTopicWidget *
Referenced by KviIrcView::doLinkToolTip(), KviServerParser::parseLiteralTopic(), KviServerParser::parseNumericNoTopic(), KviServerParser::parseNumericTopic(), and KviServerParser::parseNumericTopicWhoTime().
void KviChannel::triggerCreationEvents () [protected, virtual]
Trigger the OnChannelWindowCreated event.
Returns:
void
Reimplemented from KviWindow.
References KviEvent_OnChannelWindowCreated, and KVS_TRIGGER_EVENT_0.
void KviChannel::unhighlight ()
Unhighlights the windowlist item.
Returns:
void
Reimplemented from KviWindow.
References KviWindow::m_pWindowListItem, and KviWindowListItem::unhighlight().
void KviChannel::updateModeLabel ()
Updates the tooltip over the channel modes.
Returns:
void
References __tr2qs, KviTalToolTip::add(), KviQString::appendFormatted(), KviWindow::connection(), KviIrcConnectionServerInfo::getChannelModeDescription(), KviWindow::m_pConsole, m_pModeWidget, m_szChannelKey, m_szChannelLimit, m_szChannelMode, KviStr::ptr(), KviModeWidget::refreshModes(), KviTalToolTip::remove(), and KviIrcConnection::serverInfo().
Referenced by setChannelKey(), setChannelLimit(), setChannelMode(), and setDeadChan().
void KviChannel::userAction (const QString & szNick, const QString & szUser, const QString & szHost, unsigned int uActionType)
Perform a user action in the channel.
Parameters:
szNick The nickname of the user who made the action
szUser The username of the user who made the action
szHost The hostname of the user who made the action
uActionType The type of the action
Returns:
void
References channelAction(), kvi_getUserActionTemperature(), m_pUserListView, and KviUserListView::userAction().
void KviChannel::userAction (const QString & szNick, unsigned int uActionType)
Perform a user action in the channel.
Parameters:
szNick The nickname of the user who made the action
uActionType The type of the action
Returns:
void
References channelAction(), kvi_getUserActionTemperature(), m_pUserListView, and KviUserListView::userAction().
void KviChannel::userAction (KviIrcMask * user, unsigned int uActionType)
Perform a user action in the channel.
Parameters:
user The user who made the action
uActionType The type of the action
Returns:
void
References channelAction(), kvi_getUserActionTemperature(), m_pUserListView, KviIrcMask::nick(), and KviUserListView::userAction().
Referenced by ownAction(), ownMessage(), KviServerParser::parseLiteralKick(), KviServerParser::parseLiteralMode(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), and KviServerParser::parseLiteralTopic().
KviUserListView* KviChannel::userListView () [inline]
Returns the user listview object.
Returns:
KviUserListView *
Referenced by KviIrcView::mouseRealPressEvent(), and KviServerParser::parseNumericEndOfWho().
int KviChannel::userOpCount () [inline]
Returns the number of users with userop status.
Returns:
int
int KviChannel::voiceCount () [inline]
Returns the number of users with voice status.
Returns:
int
Member Data Documentation
int KviChannel::m_iStateFlags [protected]
Referenced by checkChannelSync(), closeEvent(), getWindowListTipText(), KviChannel(), myIconPtr(), partMessageSent(), setAliveChan(), setDeadChan(), and setMask().
QDateTime KviChannel::m_joinTime [protected]
Referenced by activityMeter(), checkChannelSync(), getChannelActivityStats(), KviChannel(), and setAliveChan().
KviPointerList<KviChannelAction>* KviChannel::m_pActionHistory [protected]
Referenced by activityMeter(), channelAction(), fixActionHistory(), getChannelActivityStats(), KviChannel(), setDeadChan(), and ~KviChannel().
KviMaskEditor* KviChannel::m_pBanEditor [protected]
Referenced by KviChannel(), setMask(), and toggleBanEditor().
KviWindowToolPageButton* KviChannel::m_pBanEditorButton [protected]
Referenced by KviChannel(), and toggleBanEditor().
KviMaskEditor* KviChannel::m_pBanExceptionEditor [protected]
Referenced by KviChannel(), setMask(), and toggleBanExceptionEditor().
KviWindowToolPageButton* KviChannel::m_pBanExceptionEditorButton [protected]
Referenced by KviChannel(), and toggleBanExceptionEditor().
KviPointerList<KviMaskEntry>* KviChannel::m_pBanExceptionList [protected]
Referenced by KviChannel(), setDeadChan(), setMask(), toggleBanExceptionEditor(), toggleEditor(), and ~KviChannel().
KviPointerList<KviMaskEntry>* KviChannel::m_pBanList [protected]
Referenced by KviChannel(), setDeadChan(), setMask(), toggleBanEditor(), toggleEditor(), and ~KviChannel().
KviTalHBox* KviChannel::m_pButtonContainer [protected]
Referenced by KviChannel().
QToolButton* KviChannel::m_pDoubleViewButton [protected]
Referenced by KviChannel(), showDoubleView(), and toggleDoubleView().
KviMaskEditor* KviChannel::m_pInviteEditor [protected]
Referenced by KviChannel(), setMask(), and toggleInviteEditor().
KviWindowToolPageButton* KviChannel::m_pInviteEditorButton [protected]
Referenced by KviChannel(), and toggleInviteEditor().
KviPointerList<KviMaskEntry>* KviChannel::m_pInviteList [protected]
Referenced by KviChannel(), setDeadChan(), setMask(), toggleEditor(), toggleInviteEditor(), and ~KviChannel().
KviWindowToolPageButton* KviChannel::m_pListViewButton [protected]
Referenced by KviChannel(), and toggleListView().
KviIrcView* KviChannel::m_pMessageView [protected]
Referenced by applyOptions(), KviChannel(), loadProperties(), lostUserFocus(), outputMessage(), saveProperties(), showDoubleView(), and toggleDoubleView().
KviModeEditor* KviChannel::m_pModeEditor [protected]
Referenced by KviChannel(), modeSelectorDone(), and toggleModeEditor().
KviWindowToolPageButton* KviChannel::m_pModeEditorButton [protected]
Referenced by KviChannel(), and toggleModeEditor().
KviModeWidget* KviChannel::m_pModeWidget [protected]
Referenced by applyOptions(), KviChannel(), and updateModeLabel().
KviMaskEditor* KviChannel::m_pQuietBanEditor [protected]
Referenced by KviChannel(), setMask(), and toggleQuietBanEditor().
KviWindowToolPageButton* KviChannel::m_pQuietBanEditorButton [protected]
Referenced by KviChannel(), and toggleQuietBanEditor().
KviPointerList<KviMaskEntry>* KviChannel::m_pQuietBanList [protected]
Referenced by KviChannel(), setDeadChan(), setMask(), toggleEditor(), toggleQuietBanEditor(), and ~KviChannel().
KviPixmap KviChannel::m_privateBackground [protected]
Referenced by loadProperties(), saveProperties(), and showDoubleView().
QStringList* KviChannel::m_pTmpHighLighted [protected]
Referenced by addHighlightedUser(), KviChannel(), removeHighlightedUser(), and ~KviChannel().
KviTopicWidget* KviChannel::m_pTopicWidget [protected]
Referenced by applyOptions(), eventFilter(), KviChannel(), resizeEvent(), setAliveChan(), and setDeadChan().
KviTalSplitter* KviChannel::m_pTopSplitter [protected]
Referenced by KviChannel(), loadProperties(), and saveProperties().
KviUserListView* KviChannel::m_pUserListView [protected]
Referenced by addHighlightedUser(), applyOptions(), getWindowListTipText(), KviChannel(), loadProperties(), nickChange(), part(), saveProperties(), setAliveChan(), setDeadChan(), setMask(), toggleListView(), userAction(), and ~KviChannel().
KviTalSplitter* KviChannel::m_pVertSplitter [protected]
Referenced by KviChannel(), saveProperties(), and showDoubleView().
QString KviChannel::m_szChannelKey [protected]
Referenced by getChannelModeString(), setChannelKey(), setDeadChan(), toggleModeEditor(), and updateModeLabel().
QString KviChannel::m_szChannelLimit [protected]
Referenced by getChannelModeString(), setChannelLimit(), setDeadChan(), toggleModeEditor(), and updateModeLabel().
QString KviChannel::m_szChannelMode [protected]
Referenced by getChannelModeString(), setChannelMode(), setDeadChan(), toggleModeEditor(), and updateModeLabel().
QString KviChannel::m_szNameWithUserFlag [protected]
Referenced by fillCaptionBuffers().
kvi_time_t KviChannel::m_tLastReceivedWhoReply [protected]
Referenced by KviChannel().
unsigned int KviChannel::m_uActionHistoryHotActionCount [protected]
Referenced by activityMeter(), channelAction(), fixActionHistory(), KviChannel(), and setDeadChan().
QList<int> KviChannel::m_VertSplitterSizesList [protected]
Referenced by loadProperties(), saveProperties(), and showDoubleView().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_channel.h
src/kvirc/ui/kvi_channel.cpp