KVIrc: KviPointerHashTableEntry< Key, T > Class Template Reference
KviPointerHashTableEntry< Key, T > Class Template Reference
#include <KviPointerHashTable.h>
Public Member Functions
T * data ()
Key & key ()
Protected Attributes
Key hKey
T * pData
Friends
class KviPointerHashTable< Key, T >
template<typename Key, typename T>
class KviPointerHashTableEntry< Key, T >
Member Function Documentation
template<typename Key, typename T> T* KviPointerHashTableEntry< Key, T >::data () [inline]
References KviPointerHashTableEntry< Key, T >::pData.
Referenced by KviPointerHashTable< QString, KviActionCategory >::current(), KviPointerHashTable< QString, KviActionCategory >::first(), KviPointerHashTable< QString, KviActionCategory >::next(), and KviKvsObject::~KviKvsObject().
template<typename Key, typename T> Key& KviPointerHashTableEntry< Key, T >::key () [inline]
References KviPointerHashTableEntry< Key, T >::hKey.
Referenced by KviPointerHashTable< QString, KviActionCategory >::currentKey(), ClassEditorWidget::renameNamespace(), and KviKvsObject::~KviKvsObject().
Friends And Related Function Documentation
template<typename Key, typename T> friend class KviPointerHashTable< Key, T > [friend]
Member Data Documentation
template<typename Key, typename T> Key KviPointerHashTableEntry< Key, T >::hKey [protected]
Referenced by KviPointerHashTable< QString, KviActionCategory >::insert(), and KviPointerHashTableEntry< Key, T >::key().
template<typename Key, typename T> T* KviPointerHashTableEntry< Key, T >::pData [protected]
Referenced by KviPointerHashTableEntry< Key, T >::data(), and KviPointerHashTable< QString, KviActionCategory >::insert().
The documentation for this class was generated from the following file:
src/kvilib/core/KviPointerHashTable.h