KVIrc: KviDnsResolver Class Reference
KviDnsResolver Class Reference
The KviDnsResolver class.
#include <KviDnsResolver.h>
Public Types
enum QueryType {
IPv4, IPv6, Any, IPv4,
IPv6, Any
}
enum QueryType {
IPv4, IPv6, Any, IPv4,
IPv6, Any
}
enum State {
Idle, Busy, Failure, Success,
Idle, Busy, Failure, Success
}
enum State {
Idle, Busy, Failure, Success,
Idle, Busy, Failure, Success
}
Signals
void lookupDone (KviDnsResolver *)
void lookupDone (KviDnsResolver *)
Public Member Functions
KviError::Code error () const
KviError::Code error ()
const QString & errorString () const
QString errorString ()
const QString & firstHostname ()
const QString & firstIpAddress ()
const QString & firstIpAddress ()
const QString & hostName () const
const QString & hostName ()
int hostnameCount ()
KviPointerList< QString > * hostnameList ()
int ipAddressCount () const
int ipAddressCount ()
KviPointerList< QString > * ipAddressList ()
KviPointerList< QString > * ipAddressList ()
bool isRunning () const
bool isRunning () const
KviDnsResolver (QObject *pParent=NULL)
KviDnsResolver ()
bool lookup (const QString &szQuery, QueryType eType)
bool lookup (const QString &szQuery, QueryType type)
const QString & query () const
const QString & query ()
void * releaseAuxData ()
void setAuxData (void *pAuxData)
State state () const
State state ()
virtual ~KviDnsResolver ()
virtual ~KviDnsResolver ()
Protected Member Functions
virtual bool event (QEvent *e)
Protected Attributes
void * m_pAuxData
KviDnsResolverResult * m_pDnsResult
KviDnsResolverThread * m_pSlaveThread
State m_state
Properties
bool blockingDelete
Private Slots
void slotHostLookupTerminated (const QHostInfo &oHostInfo)
Private Member Functions
KviDnsResolverResult * result ()
Private Attributes
KviDnsResolverPrivate * m_pPrivateData
Detailed Description
The KviDnsResolver class.
This class...
Member Enumeration Documentation
enum KviDnsResolver::QueryType
Enumerator
IPv4
IPv6
Any
IPv4
IPv6
Any
enum KviDnsResolver::QueryType
Enumerator
IPv4
IPv6
Any
IPv4
IPv6
Any
enum KviDnsResolver::State
Enumerator
Idle
Busy
Failure
Success
Idle
Busy
Failure
Success
enum KviDnsResolver::State
Enumerator
Idle
Busy
Failure
Success
Idle
Busy
Failure
Success
Constructor & Destructor Documentation
KviDnsResolver::KviDnsResolver ()
References Idle, m_pAuxData, m_pDnsResult, m_pSlaveThread, and m_state.
KviDnsResolver::~KviDnsResolver () virtual
References m_pAuxData, m_pDnsResult, and m_pSlaveThread.
KviDnsResolver::KviDnsResolver (QObject * pParent = NULL)
Creates an instance of KviDnsResolver
References KviDnsResolverPrivate::eState, Idle, m_pPrivateData, and KviDnsResolverPrivate::pAddressList.
virtual KviDnsResolver::~KviDnsResolver () virtual
Destroys the instance of KviDnsResolver and frees all the relevant resources
Member Function Documentation
KviError::Code KviDnsResolver::error () const
References KviDnsResolverPrivate::eError, and m_pPrivateData.
KviError::Code KviDnsResolver::error ()
References KviError::DNSQueryFailed, KviDnsResolverResult::error(), and m_pDnsResult.
Referenced by errorString(), KviIrcConnection::hostNameLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
const QString & KviDnsResolver::errorString () const
References m_pPrivateData, and KviDnsResolverPrivate::szError.
QString KviDnsResolver::errorString ()
References error(), and KviError::getDescription().
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
bool KviDnsResolver::event (QEvent * e) protected virtual
References e, KviDnsResolverResult::error(), Failure, lookupDone(), m_pDnsResult, m_state, KviDnsResolverThreadEvent::releaseResult(), KviError::Success, and Success.
const QString & KviDnsResolver::firstHostname ()
References KviQString::Empty, KviPointerList< T >::first(), KviDnsResolverResult::hostnameList(), and result().
const QString& KviDnsResolver::firstIpAddress ()
const QString & KviDnsResolver::firstIpAddress ()
References KviQString::Empty, KviPointerList< T >::first(), KviDnsResolverResult::ipAddressList(), and result().
Referenced by KviIrcConnection::hostNameLookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
const QString & KviDnsResolver::hostName () const
References m_pPrivateData, and KviDnsResolverPrivate::szHostName.
const QString& KviDnsResolver::hostName () inline
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
int KviDnsResolver::hostnameCount ()
References KviPointerList< T >::count(), KviDnsResolverResult::hostnameList(), and result().
KviPointerList< QString > * KviDnsResolver::hostnameList ()
References KviDnsResolverResult::hostnameList(), and result().
int KviDnsResolver::ipAddressCount () const
References KviPointerList< T >::count(), m_pPrivateData, and KviDnsResolverPrivate::pAddressList.
int KviDnsResolver::ipAddressCount ()
References KviPointerList< T >::count(), KviDnsResolverResult::ipAddressList(), and result().
Referenced by KviIrcConnectionTargetResolver::serverLookupTerminated().
KviPointerList<QString>* KviDnsResolver::ipAddressList ()
KviPointerList< QString > * KviDnsResolver::ipAddressList ()
References KviDnsResolverResult::ipAddressList(), and result().
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
bool KviDnsResolver::isRunning () const
bool KviDnsResolver::isRunning () const
References Busy, and m_state.
Referenced by KviIrcConnectionTargetResolver::cleanup(), KviIrcConnection::~KviIrcConnection(), and KviKvsDnsObject::~KviKvsDnsObject().
bool KviDnsResolver::lookup (const QString & szQuery, QueryType eType)
Starts a lookup for the specified DNS query of the specified type. Returns true on success and false on failure.
bool KviDnsResolver::lookup (const QString & szQuery, QueryType type)
References Busy, m_pSlaveThread, m_state, KviDnsResolverThread::setQuery(), and KviRuntimeInfo::type().
Referenced by KviKvsAsyncDnsOperation::KviKvsAsyncDnsOperation(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::lookupServerHostname(), and KviIrcConnection::userInfoReceived().
void KviDnsResolver::lookupDone (KviDnsResolver *) signal
void KviDnsResolver::lookupDone (KviDnsResolver *) signal
Referenced by event(), and slotHostLookupTerminated().
const QString & KviDnsResolver::query () const
References m_pPrivateData, and KviDnsResolverPrivate::szQuery.
const QString & KviDnsResolver::query ()
References KviDnsResolverResult::query(), and result().
Referenced by KviKvsDnsManager::dnsLookupTerminated(), and KviKvsAsyncDnsOperation::lookupTerminated().
void* KviDnsResolver::releaseAuxData () inline
KviDnsResolverResult * KviDnsResolver::result () private
References m_pDnsResult.
Referenced by firstHostname(), firstIpAddress(), hostnameCount(), hostnameList(), ipAddressCount(), ipAddressList(), and query().
void KviDnsResolver::setAuxData (void * pAuxData) inline
void KviDnsResolver::slotHostLookupTerminated (const QHostInfo & oHostInfo) private slot
References __tr2qs, Any, KviPointerList< T >::append(), KviPointerList< T >::clear(), KviError::DNSQueryFailed, KviDnsResolverPrivate::eError, KviDnsResolverPrivate::eQueryType, KviDnsResolverPrivate::eState, Failure, KviError::HostNotFound, KviError::InternalError, IPv4, IPv6, KviPointerList< T >::isEmpty(), KVI_ASSERT_MSG, lookupDone(), m_pPrivateData, KviDnsResolverPrivate::pAddressList, KviError::Success, Success, KviDnsResolverPrivate::szError, KviDnsResolverPrivate::szHostName, and KviError::ValidNameButNoIpAddress.
KviDnsResolver::State KviDnsResolver::state () const
Returns the resolver state
References KviDnsResolverPrivate::eState, and m_pPrivateData.
State KviDnsResolver::state () inline
Referenced by KviKvsDnsManager::dnsLookupTerminated(), KviIrcConnection::hostNameLookupTerminated(), KviKvsAsyncDnsOperation::lookupTerminated(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcConnectionTargetResolver::serverLookupTerminated().
Member Data Documentation
void* KviDnsResolver::m_pAuxData protected
Referenced by KviDnsResolver(), and ~KviDnsResolver().
KviDnsResolverResult* KviDnsResolver::m_pDnsResult protected
Referenced by error(), event(), KviDnsResolver(), result(), and ~KviDnsResolver().
KviDnsResolverPrivate* KviDnsResolver::m_pPrivateData private
Referenced by error(), errorString(), hostName(), ipAddressCount(), KviDnsResolver(), query(), slotHostLookupTerminated(), and state().
KviDnsResolverThread* KviDnsResolver::m_pSlaveThread protected
Referenced by KviDnsResolver(), lookup(), and ~KviDnsResolver().
State KviDnsResolver::m_state protected
Referenced by event(), isRunning(), KviDnsResolver(), and lookup().
Property Documentation
bool KviDnsResolver::blockingDelete read
The documentation for this class was generated from the following files:
src/kvilib/net/KviDnsResolver.h
src/kvilib/net/KviDnsResolverNew.h
src/kvilib/net/KviDnsResolver.cpp
src/kvilib/net/KviDnsResolverNew.cpp