KVIrc: NickAlternativesDialog Class Reference
NickAlternativesDialog Class Reference
#include <OptionsWidget_identity.h>
Protected Member Functions
void fill (QString &n1, QString &n2, QString &n3)
NickAlternativesDialog (QWidget *par, const QString &n1, const QString &n2, const QString &n3)
~NickAlternativesDialog ()
Protected Attributes
QLineEdit * m_pNickEdit1
QLineEdit * m_pNickEdit2
QLineEdit * m_pNickEdit3
Friends
class KviIdentityGeneralOptionsWidget
Constructor & Destructor Documentation
NickAlternativesDialog::NickAlternativesDialog (QWidget * par, const QString & n1, const QString & n2, const QString & n3) [protected]
References __tr2qs_ctx(), connect(), g, h, l, m_pNickEdit1, m_pNickEdit2, m_pNickEdit3, and KviTalHBox::setSpacing().
NickAlternativesDialog::~NickAlternativesDialog () [protected]
Member Function Documentation
void NickAlternativesDialog::fill (QString & n1, QString & n2, QString & n3) [protected]
References m_pNickEdit1, m_pNickEdit2, and m_pNickEdit3.
Referenced by KviIdentityGeneralOptionsWidget::setNickAlternatives().
Friends And Related Function Documentation
friend class KviIdentityGeneralOptionsWidget [friend]
Member Data Documentation
QLineEdit* NickAlternativesDialog::m_pNickEdit1 [protected]
Referenced by fill(), and NickAlternativesDialog().
QLineEdit* NickAlternativesDialog::m_pNickEdit2 [protected]
Referenced by fill(), and NickAlternativesDialog().
QLineEdit* NickAlternativesDialog::m_pNickEdit3 [protected]
Referenced by fill(), and NickAlternativesDialog().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_identity.h
src/modules/options/OptionsWidget_identity.cpp