KVIrc: DccMarshal Class Reference
DccMarshal Class Reference
#include <DccMarshal.h>
Signals
void connected ()
void error (KviError::Code)
void inProgress ()
void sslError (const char *msg)
void startingSSLHandshake ()
Public Member Functions
void abort ()
KviError::Code dccConnect (const char *ip, const char *port, bool bUseTimeout, bool bUseSSL=false)
const QString & dccIp () const
KviError::Code dccListen (const QString &ip, const QString &port, bool bUseTimeout, bool bUseSSL=false)
DccMarshal (DccMarshalOutputContext *ctx)
const QString & dccPort () const
const QString & localIp () const
const QString & localPort () const
kvi_socket_t releaseSocket ()
const QString & remoteIp () const
const QString & remotePort () const
~DccMarshal ()
Protected Attributes
bool m_bIPv6
bool m_bOutgoing
bool m_bUseTimeout
kvi_socket_t m_fd
DccMarshalOutputContext * m_pOutputContext
QSocketNotifier * m_pSn
QTimer * m_pTimeoutTimer
QString m_szIp
QString m_szPort
QString m_szSecondaryIp
QString m_szSecondaryPort
kvi_u32_t m_uPort
Private Slots
void connectionTimedOut ()
void doConnect ()
void doListen ()
void doSSLHandshake (int)
void snActivated (int)
Private Member Functions
void reset ()
Constructor & Destructor Documentation
DccMarshal::DccMarshal (DccMarshalOutputContext * ctx)
References KVI_INVALID_SOCKET, m_bIPv6, m_fd, m_pOutputContext, m_pSn, m_pTimeoutTimer, m_szIp, m_szPort, m_szSecondaryIp, and m_szSecondaryPort.
DccMarshal::~DccMarshal ()
References reset().
Member Function Documentation
void DccMarshal::abort ()
References reset().
Referenced by DccFileTransfer::abort().
void DccMarshal::connected () [signal]
Referenced by doSSLHandshake(), and snActivated().
void DccMarshal::connectionTimedOut () [private, slot]
References KviError::ConnectionTimedOut, error(), and reset().
Referenced by doConnect(), and doListen().
KviError::Code DccMarshal::dccConnect (const char * ip, const char * port, bool bUseTimeout, bool bUseSSL = false)
References KviError::AnotherConnectionInProgress, doConnect(), KVI_INVALID_SOCKET, m_bOutgoing, m_bUseTimeout, m_fd, m_szIp, m_szPort, KviError::NoSSLSupport, and KviError::Success.
Referenced by DccFileTransfer::listenOrConnect(), DccVoiceWindow::startConnection(), DccVideoWindow::startConnection(), and DccChatWindow::startConnection().
const QString& DccMarshal::dccIp () const [inline]
References m_szIp.
KviError::Code DccMarshal::dccListen (const QString & ip, const QString & port, bool bUseTimeout, bool bUseSSL = false)
References KviError::AnotherConnectionInProgress, doListen(), KVI_INVALID_SOCKET, m_bOutgoing, m_bUseTimeout, m_fd, m_pTimeoutTimer, m_szIp, m_szPort, KviError::NoSSLSupport, and KviError::Success.
Referenced by DccFileTransfer::listenOrConnect(), DccVoiceWindow::startConnection(), DccVideoWindow::startConnection(), and DccChatWindow::startConnection().
const QString& DccMarshal::dccPort () const [inline]
References m_szPort.
Referenced by DccFileTransfer::doResume().
void DccMarshal::doConnect () [private, slot]
References KviError::AsyncSocketFailed, connect(), connectionTimedOut(), error(), inProgress(), KviError::InvalidIpAddress, KviError::InvalidPortNumber, KviNetUtils::isValidStringIp(), KVI_INVALID_SOCKET, KVI_OPTION_UINT, kvi_socket_connect(), kvi_socket_create(), kvi_socket_error(), kvi_socket_getsockopt(), KVI_SOCKET_PF_INET, KVI_SOCKET_PF_INET6, KVI_SOCKET_PROTO_TCP, kvi_socket_recoverableConnectError(), kvi_socket_setNonBlocking(), KVI_SOCKET_TYPE_STREAM, KviOption_uintDccSocketTimeout, m_bIPv6, m_bUseTimeout, m_fd, m_pSn, m_pTimeoutTimer, m_szIp, m_szPort, m_uPort, reset(), snActivated(), KviError::SocketCreationFailed, KviError::translateSystemError(), and KviError::UnknownError.
Referenced by dccConnect().
void DccMarshal::doListen () [private, slot]
References KviSockaddr::addressLength(), KviError::BindFailed, connect(), connectionTimedOut(), error(), inProgress(), KviError::InvalidIpAddress, KviError::InvalidPortNumber, KviNetUtils::isValidStringIp(), KVI_INVALID_SOCKET, KVI_OPTION_BOOL, KVI_OPTION_UINT, kvi_socket_bind(), kvi_socket_create(), kvi_socket_getsockname(), kvi_socket_listen(), KVI_SOCKET_PF_INET, KVI_SOCKET_PF_INET6, KVI_SOCKET_PROTO_TCP, KVI_SOCKET_TYPE_STREAM, KviOption_boolUserDefinedPortRange, KviOption_uintDccMaxPort, KviOption_uintDccMinPort, KviOption_uintDccSocketTimeout, KviError::ListenFailed, m_bIPv6, m_bUseTimeout, m_fd, m_pSn, m_pTimeoutTimer, m_szIp, m_szPort, m_uPort, KviError::NoIPv6Support, KviSockaddr::port(), reset(), snActivated(), KviSockaddr::socketAddress(), and KviError::SocketCreationFailed.
Referenced by dccListen().
void DccMarshal::doSSLHandshake (int) [private, slot]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References connect(), connected(), error(), KviError::InternalError, kvi_socket_error(), kvi_socket_recoverableError(), m_bOutgoing, m_fd, m_pSn, KviCString::ptr(), r, KviError::RemoteEndClosedConnection, reset(), KviError::SSLError, sslError(), KviError::Success, KviError::translateSystemError(), and KviError::UnknownError.
Referenced by snActivated().
void DccMarshal::error (KviError::Code) [signal]
Referenced by connectionTimedOut(), doConnect(), doListen(), doSSLHandshake(), and snActivated().
void DccMarshal::inProgress () [signal]
Referenced by doConnect(), and doListen().
const QString& DccMarshal::localIp () const [inline]
References m_bOutgoing, m_szIp, and m_szSecondaryIp.
Referenced by DccVoiceWindow::connected(), DccVideoWindow::connected(), DccFileTransfer::connected(), DccChatWindow::connected(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), and DccChatWindow::connectionInProgress().
const QString& DccMarshal::localPort () const [inline]
References m_bOutgoing, m_szPort, and m_szSecondaryPort.
Referenced by DccVoiceWindow::connected(), DccVideoWindow::connected(), DccFileTransfer::connected(), DccChatWindow::connected(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), and DccChatWindow::connectionInProgress().
kvi_socket_t DccMarshal::releaseSocket ()
References KVI_INVALID_SOCKET, and m_fd.
Referenced by DccVoiceWindow::connected(), DccVideoWindow::connected(), DccFileTransfer::connected(), and DccChatWindow::connected().
const QString& DccMarshal::remoteIp () const [inline]
References m_bOutgoing, m_szIp, and m_szSecondaryIp.
Referenced by DccVoiceWindow::connected(), DccVideoWindow::connected(), DccFileTransfer::connected(), and DccChatWindow::connected().
const QString& DccMarshal::remotePort () const [inline]
References m_bOutgoing, m_szPort, and m_szSecondaryPort.
Referenced by DccVoiceWindow::connected(), DccVideoWindow::connected(), DccFileTransfer::connected(), and DccChatWindow::connected().
void DccMarshal::reset () [private]
References KVI_INVALID_SOCKET, kvi_socket_close, m_bIPv6, m_fd, m_pSn, and m_pTimeoutTimer.
Referenced by abort(), connectionTimedOut(), doConnect(), doListen(), doSSLHandshake(), snActivated(), and ~DccMarshal().
void DccMarshal::snActivated (int) [private, slot]
References __tr2qs_ctx(), KviError::AsyncSocketFailed, KviNetUtils::binaryIpToStringIp(), connected(), DccMarshalOutputContext::dccMarshalOutputContextString(), DccMarshalOutputContext::dccMarshalOutputWindow(), doSSLHandshake(), error(), KVI_INVALID_SOCKET, kvi_socket_accept(), kvi_socket_close, kvi_socket_getsockname(), kvi_socket_getsockopt(), kvi_socket_setNonBlocking(), m_bIPv6, m_bOutgoing, m_fd, m_pOutputContext, m_pSn, m_pTimeoutTimer, m_szSecondaryIp, m_szSecondaryPort, reset(), KviError::SSLError, startingSSLHandshake(), KviError::translateSystemError(), and KviError::UnknownError.
Referenced by doConnect(), and doListen().
void DccMarshal::sslError (const char * msg) [signal]
Referenced by doSSLHandshake().
void DccMarshal::startingSSLHandshake () [signal]
Referenced by snActivated().
Member Data Documentation
bool DccMarshal::m_bIPv6 [protected]
Referenced by DccMarshal(), doConnect(), doListen(), reset(), and snActivated().
bool DccMarshal::m_bOutgoing [protected]
Referenced by dccConnect(), dccListen(), doSSLHandshake(), localIp(), localPort(), remoteIp(), remotePort(), and snActivated().
bool DccMarshal::m_bUseTimeout [protected]
Referenced by dccConnect(), dccListen(), doConnect(), and doListen().
kvi_socket_t DccMarshal::m_fd [protected]
Referenced by dccConnect(), dccListen(), DccMarshal(), doConnect(), doListen(), doSSLHandshake(), releaseSocket(), reset(), and snActivated().
DccMarshalOutputContext* DccMarshal::m_pOutputContext [protected]
Referenced by DccMarshal(), and snActivated().
QSocketNotifier* DccMarshal::m_pSn [protected]
Referenced by DccMarshal(), doConnect(), doListen(), doSSLHandshake(), reset(), and snActivated().
QTimer* DccMarshal::m_pTimeoutTimer [protected]
Referenced by dccListen(), DccMarshal(), doConnect(), doListen(), reset(), and snActivated().
QString DccMarshal::m_szIp [protected]
Referenced by dccConnect(), dccIp(), dccListen(), DccMarshal(), doConnect(), doListen(), localIp(), and remoteIp().
QString DccMarshal::m_szPort [protected]
Referenced by dccConnect(), dccListen(), DccMarshal(), dccPort(), doConnect(), doListen(), localPort(), and remotePort().
QString DccMarshal::m_szSecondaryIp [protected]
Referenced by DccMarshal(), localIp(), remoteIp(), and snActivated().
QString DccMarshal::m_szSecondaryPort [protected]
Referenced by DccMarshal(), localPort(), remotePort(), and snActivated().
kvi_u32_t DccMarshal::m_uPort [protected]
Referenced by doConnect(), and doListen().
The documentation for this class was generated from the following files:
src/modules/dcc/DccMarshal.h
src/modules/dcc/DccMarshal.cpp