KVIrc: KviActionDrawerPageListWidget Class Reference
KviActionDrawerPageListWidget Class Reference
#include <KviActionDrawer.h>
Public Member Functions
~KviActionDrawerPageListWidget ()
Destroys an action drawer page list object.
Public Member Functions inherited from KviTalListWidget
KviTalListWidget (QWidget *pParent, QString name, Qt::WindowType f=Qt::Widget)
KviTalListWidget (QWidget *pParent)
virtual ~KviTalListWidget ()
Protected Member Functions
KviActionDrawerPageListWidget (KviActionDrawerPage *pParent)
Constructs an action drawer page list object.
virtual void mousePressEvent (QMouseEvent *e)
virtual void resizeEvent (QResizeEvent *e)
Protected Member Functions inherited from KviTalListWidget
virtual bool event (QEvent *e)
Friends
class KviActionDrawerPage
Additional Inherited Members
Signals inherited from KviTalListWidget
void tipRequest (QListWidgetItem *, const QPoint &)
Constructor & Destructor Documentation
KviActionDrawerPageListWidget::KviActionDrawerPageListWidget (KviActionDrawerPage * pParent) protected
Constructs an action drawer page list object.
Parameters
pParent The parent widget
Returns
KviActionDrawerPageListWidget
KviActionDrawerPageListWidget::~KviActionDrawerPageListWidget ()
Destroys an action drawer page list object.
Member Function Documentation
void KviActionDrawerPageListWidget::mousePressEvent (QMouseEvent * e) protected virtual
References KviAction::bigIcon(), KviActionManager::getAction(), KviActionManager::instance(), and KviActionDrawerPageListWidgetItem::name().
void KviActionDrawerPageListWidget::resizeEvent (QResizeEvent * e) protected virtual
References LVI_MINIMUM_CELL_WIDTH.
Friends And Related Function Documentation
friend class KviActionDrawerPage friend
The documentation for this class was generated from the following files:
src/kvirc/ui/KviActionDrawer.h
src/kvirc/ui/KviActionDrawer.cpp