KVIrc: KviIrcuIrcServerInfo Class Reference
KviIrcuIrcServerInfo Class Reference
#include <KviIrcConnectionServerInfo.h>
Public Member Functions
virtual const QString & getChannelModeDescription (char mode)
virtual bool getNeedsOperToSetS ()
virtual bool getNeedsOpToListModeseI ()
virtual char getRegisterModeChar ()
virtual const char * getSoftware ()
virtual const QString & getUserModeDescription (QChar mode)
virtual QChar getUserModeRequirement (QChar mode)
KviIrcuIrcServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
Public Member Functions inherited from KviBasicIrcServerInfo
KviBasicIrcServerInfo (KviIrcConnectionServerInfo *pParent=0, const QString &version=KviQString::Empty)
virtual ~KviBasicIrcServerInfo ()
Additional Inherited Members
Protected Attributes inherited from KviBasicIrcServerInfo
KviIrcConnectionServerInfo * m_pParent
QString m_szServerVersion
Constructor & Destructor Documentation
KviIrcuIrcServerInfo::KviIrcuIrcServerInfo (KviIrcConnectionServerInfo * pParent = 0, const QString & version = KviQString::Empty) inline
Member Function Documentation
const QString & KviIrcuIrcServerInfo::getChannelModeDescription (char mode) virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviDarenetIrcServerInfo, and KviSnircdIrcServerInfo.
References __tr2qs, and KviBasicIrcServerInfo::getChannelModeDescription().
Referenced by KviSnircdIrcServerInfo::getChannelModeDescription(), and KviDarenetIrcServerInfo::getChannelModeDescription().
virtual bool KviIrcuIrcServerInfo::getNeedsOperToSetS () inline virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviSnircdIrcServerInfo.
virtual bool KviIrcuIrcServerInfo::getNeedsOpToListModeseI () inline virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviDarenetIrcServerInfo.
virtual char KviIrcuIrcServerInfo::getRegisterModeChar () inline virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviDarenetIrcServerInfo.
virtual const char* KviIrcuIrcServerInfo::getSoftware () inline virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviDarenetIrcServerInfo, and KviSnircdIrcServerInfo.
const QString & KviIrcuIrcServerInfo::getUserModeDescription (QChar mode) virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviDarenetIrcServerInfo, and KviSnircdIrcServerInfo.
References __tr2qs, and KviBasicIrcServerInfo::getUserModeDescription().
Referenced by KviSnircdIrcServerInfo::getUserModeDescription(), and KviDarenetIrcServerInfo::getUserModeDescription().
QChar KviIrcuIrcServerInfo::getUserModeRequirement (QChar mode) virtual
Reimplemented from KviBasicIrcServerInfo.
Reimplemented in KviDarenetIrcServerInfo, and KviSnircdIrcServerInfo.
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionServerInfo.h
src/kvirc/kernel/KviIrcConnectionServerInfo.cpp