KVIrc: KviKvsArray Class Reference
KviKvsArray Class Reference
This class defines a new data type which contains array data.
#include <KviKvsArray.h>
Public Member Functions
void append (KviKvsVariant *pVal)
void appendAsString (QString &szBuffer)
Appends data to the array converting it into a string.
KviKvsVariant * at (kvs_uint_t uIdx) const
Returns the element at the given index.
KviKvsVariant * getAt (kvs_uint_t uIdx)
Returns the element at the given index.
bool isEmpty ()
Returns true if the array is empty.
KviKvsArray ()
Constructs the array data.
KviKvsArray (const KviKvsArray &array)
Constructs the array data.
void rsort ()
Sorts the array in reverse order.
void serialize (QString &szResult)
Serializes the array to a given buffer.
void set (kvs_uint_t uIdx, KviKvsVariant *pVal)
Sets an element into the array at the given index.
kvs_uint_t size ()
Returns the size of the array.
void sort ()
Sorts the array.
void unset (kvs_uint_t uIdx)
Unsets an element from the array.
~KviKvsArray ()
Destroys the array data.
Protected Member Functions
void findNewSize ()
Finds the new size of the array.
Protected Attributes
KviKvsVariant ** m_pData
kvs_uint_t m_uAllocSize
kvs_uint_t m_uSize
Static Private Member Functions
static int compare (const void *pV1, const void *pV2)
Compares two elements of the array.
static int compareReverse (const void *pV1, const void *pV2)
Compares two elements of the array in reverse order.
Detailed Description
This class defines a new data type which contains array data.
Warning
This class must not have virtual functions nor destructor. Otherwise it will happily crash on windows when it is allocated in modules and destroyed anywhere else around
Constructor & Destructor Documentation
KviKvsArray::KviKvsArray ()
Constructs the array data.
Returns
KviKvsArray
References m_pData, m_uAllocSize, and m_uSize.
KviKvsArray::KviKvsArray (const KviKvsArray & array)
Constructs the array data.
This is a carbon copy
Parameters
array The array to copy from
Returns
KviKvsArray
References KviMemory::allocate(), m_pData, m_uAllocSize, m_uSize, and u.
KviKvsArray::~KviKvsArray ()
Destroys the array data.
References KviMemory::free(), m_pData, m_uSize, and u.
Member Function Documentation
void KviKvsArray::append (KviKvsVariant * pVal)
Appends a variant to this array.
References m_uSize, and set().
Referenced by package_kvs_fnc_info(), and spellchecker_kvs_suggestions().
void KviKvsArray::appendAsString (QString & szBuffer)
Appends data to the array converting it into a string.
Parameters
szBuffer The string to append
Returns
void
References KviKvsVariant::appendAsString(), m_pData, m_uSize, and u.
Referenced by KviKvsVariant::appendAsString(), and KviKvsVariant::asString().
KviKvsVariant* KviKvsArray::at (kvs_uint_t uIdx) const inline
Returns the element at the given index.
Parameters
uIdx The index of the element to retrieve
Returns
KviKvsVariant *
Referenced by KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeOperationArrayAppend::execute(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), KviInputEditor::fillSpellCheckerCorrectionsPopup(), KviKvsObject::function_setProperty(), KvsObject_textedit::functionsetColor(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), KviCellItemDelegate::sizeHint(), str_kvs_fnc_grep(), and theme_kvs_cmd_pack().
int KviKvsArray::compare (const void * pV1, const void * pV2) static private
Compares two elements of the array.
Parameters
pV1 The first element to compare
pV2 The second element to compare
Returns
int
Referenced by compareReverse(), and sort().
int KviKvsArray::compareReverse (const void * pV1, const void * pV2) static private
Compares two elements of the array in reverse order.
Parameters
pV1 The first element to compare
pV2 The second element to compare
Returns
int
References compare().
Referenced by rsort().
void KviKvsArray::findNewSize () protected
Finds the new size of the array.
Returns
void
References KviMemory::free(), KVI_KVS_ARRAY_ALLOC_CHUNK, m_pData, m_uAllocSize, m_uSize, KviMemory::reallocate(), and u.
Referenced by rsort(), sort(), and unset().
KviKvsVariant * KviKvsArray::getAt (kvs_uint_t uIdx)
Returns the element at the given index.
If the element doesn't exists, it returns an empty element. If the index is out of array bounds, it increases the array size, fillin the array in with zeros.
Parameters
uIdx The index of the element to retrieve
Returns
KviKvsVariant *
References KviMemory::allocate(), KVI_KVS_ARRAY_ALLOC_CHUNK, m_pData, m_uAllocSize, m_uSize, KviMemory::reallocate(), and u.
Referenced by KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope().
bool KviKvsArray::isEmpty () inline
Returns true if the array is empty.
Returns
bool
Referenced by KviKvsVariant::asBoolean(), KviKvsVariantComparison::compareBoolArray(), KviKvsVariantComparison::compareHObjectArray(), KviKvsVariantComparison::compareIntArray(), KviKvsVariantComparison::compareRealArray(), KviKvsVariantComparison::compareStringArray(), KviKvsVariant::isEmpty(), and KviKvsVariant::isEqualToNothing().
void KviKvsArray::rsort ()
Sorts the array in reverse order.
Returns
void
References compareReverse(), findNewSize(), m_pData, and m_uSize.
Referenced by KviKvsCoreFunctions::KVSCF().
void KviKvsArray::serialize (QString & szResult)
Serializes the array to a given buffer.
Parameters
szResult The buffer to store
Returns
void
References m_pData, m_uSize, KviKvsVariant::serialize(), szBuffer, and u.
Referenced by KviKvsVariant::serialize().
void KviKvsArray::set (kvs_uint_t uIdx, KviKvsVariant * pVal)
Sets an element into the array at the given index.
Parameters
uIdx The index of the element to set
pVal The value to set
Returns
void
References KviMemory::allocate(), KVI_KVS_ARRAY_ALLOC_CHUNK, m_pData, m_uAllocSize, m_uSize, KviMemory::reallocate(), and u.
Referenced by append(), KviKvsVariant::castToArray(), chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_masklist(), chan_kvs_fnc_users(), config_kvs_fnc_filelist(), config_kvs_fnc_keylist(), config_kvs_fnc_sectionlist(), context_kvs_fnc_list(), KviKvsVariant::convertToArray(), dcc_kvs_fnc_sessionList(), KviKvsCallbackFileDialog::done(), dumpChildObjects(), KviKvsTreeNodeOperationArrayAppend::execute(), file_kvs_fnc_allSizes(), file_kvs_fnc_ls(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), KviKvsObject::function_children(), KviKvsObject::function_listProperties(), KviKvsObject::function_property(), KvsObject_textedit::functionCursorPosition(), if(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), language_kvs_cmd_detect(), MP_KVS_FUNCTION(), objects_kvs_fnc_classes(), objects_kvs_fnc_instances(), objects_kvs_fnc_listObjects(), regchan_kvs_fnc_list(), reguser_kvs_fnc_list(), reguser_kvs_fnc_mask(), KvsObject_http::slotSslErrors(), str_kvs_fnc_grep(), str_kvs_fnc_split(), TC_KVS_FUNCTION(), toolbar_kvs_fnc_items(), toolbar_kvs_fnc_list(), KviKvsVariant::unserializeArray(), userlist_kvs_fnc_selected(), and window_kvs_fnc_list().
kvs_uint_t KviKvsArray::size () inline
Returns the size of the array.
Returns
kvs_uint_t
Referenced by KviKvsVariant::castToInteger(), KviKvsVariant::compare(), KviKvsVariantComparison::compareArrayHash(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeOperationArrayAppend::execute(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), KviInputEditor::fillSpellCheckerCorrectionsPopup(), KvsObject_textedit::functionsetColor(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), KviCellItemDelegate::sizeHint(), str_kvs_fnc_grep(), and theme_kvs_cmd_pack().
void KviKvsArray::sort ()
Sorts the array.
Returns
void
References compare(), findNewSize(), m_pData, and m_uSize.
Referenced by KviKvsCoreFunctions::KVSCF().
void KviKvsArray::unset (kvs_uint_t uIdx)
Unsets an element from the array.
Parameters
uIdx The index of the element to unset
Returns
void
References findNewSize(), m_pData, and m_uSize.
Referenced by KviKvsArrayElement::~KviKvsArrayElement().
Member Data Documentation
KviKvsVariant** KviKvsArray::m_pData protected
Referenced by appendAsString(), findNewSize(), getAt(), KviKvsArray(), rsort(), serialize(), set(), sort(), unset(), and ~KviKvsArray().
kvs_uint_t KviKvsArray::m_uAllocSize protected
Referenced by findNewSize(), getAt(), KviKvsArray(), and set().
kvs_uint_t KviKvsArray::m_uSize protected
Referenced by append(), appendAsString(), findNewSize(), getAt(), KviKvsArray(), rsort(), serialize(), set(), sort(), unset(), and ~KviKvsArray().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsArray.h
src/kvirc/kvs/KviKvsArray.cpp