KVIrc: SinglePopupEditor Class Reference
SinglePopupEditor Class Reference
#include <PopupEditorWindow.h>
Public Member Functions
void edit (MenuTreeWidgetItem *it)
KviKvsPopupMenu * getMenu ()
SinglePopupEditor (QWidget *par)
~SinglePopupEditor ()
Protected Slots
void contextCopy ()
void contextCut ()
void contextNewEpilogue ()
void contextNewExtMenuAbove ()
void contextNewExtMenuBelow ()
void contextNewExtMenuInside ()
void contextNewItemAbove ()
void contextNewItemBelow ()
void contextNewItemInside ()
void contextNewLabelAbove ()
void contextNewLabelBelow ()
void contextNewLabelInside ()
void contextNewMenuAbove ()
void contextNewMenuBelow ()
void contextNewMenuInside ()
void contextNewPrologue ()
void contextNewSeparatorAbove ()
void contextNewSeparatorBelow ()
void contextNewSeparatorInside ()
void contextPasteAbove ()
void contextPasteBelow ()
void contextPasteInside ()
void customContextMenuRequested (const QPoint &pnt)
void selectionChanged ()
void testModeMenuItemClicked (KviKvsPopupMenuItem *it)
void testPopup ()
Protected Member Functions
void addItemToMenu (KviKvsPopupMenu *pop, PopupTreeWidgetItem *par)
void createNewItemAboveLastSelected (PopupTreeWidgetItem::Type t)
void createNewItemBelowLastSelected (PopupTreeWidgetItem::Type t)
void createNewItemInsideLastSelected (PopupTreeWidgetItem::Type t)
PopupTreeWidgetItem * findMatchingItem (KviKvsPopupMenuItem *it, PopupTreeWidgetItem *item)
PopupTreeWidgetItem * newItem (PopupTreeWidgetItem *par, PopupTreeWidgetItem *after, PopupTreeWidgetItem::Type t)
PopupTreeWidgetItem * newItemAbove (PopupTreeWidgetItem *it, PopupTreeWidgetItem::Type t)
PopupTreeWidgetItem * newItemBelow (PopupTreeWidgetItem *it, PopupTreeWidgetItem::Type t)
PopupTreeWidgetItem * newItemInside (PopupTreeWidgetItem *it, PopupTreeWidgetItem::Type t)
void populateMenu (KviKvsPopupMenu *pop, PopupTreeWidgetItem *par, PopupTreeWidgetItem *theItem=0)
void saveLastSelectedItem ()
Protected Attributes
KviKvsPopupMenu * m_pClipboard
QLineEdit * m_pConditionEditor
KviTalPopupMenu * m_pContextPopup
KviScriptEditor * m_pEditor
QLineEdit * m_pExtNameEditor
QLineEdit * m_pIconEditor
QLineEdit * m_pIdEditor
PopupTreeWidgetItem * m_pLastSelectedItem
QPushButton * m_pMenuButton
QLineEdit * m_pNameEditor
KviKvsPopupMenu * m_pTestPopup
QLineEdit * m_pTextEditor
QTreeWidget * m_pTreeWidget
Constructor & Destructor Documentation
SinglePopupEditor::SinglePopupEditor (QWidget * par)
References __tr2qs_ctx(), connect(), KviScriptEditor::createInstance(), customContextMenuRequested(), g, l, m_pClipboard, m_pConditionEditor, m_pContextPopup, m_pEditor, m_pExtNameEditor, m_pIconEditor, m_pIdEditor, m_pLastSelectedItem, m_pMenuButton, m_pNameEditor, m_pTestPopup, m_pTextEditor, m_pTreeWidget, selectionChanged(), spl, and testPopup().
SinglePopupEditor::~SinglePopupEditor ()
References KviScriptEditor::destroyInstance(), m_pClipboard, m_pEditor, and m_pTestPopup.
Member Function Documentation
void SinglePopupEditor::addItemToMenu (KviKvsPopupMenu * pop, PopupTreeWidgetItem * par) [protected]
References KviKvsPopupMenu::addEpilogue(), KviKvsPopupMenu::addExtPopup(), KviKvsPopupMenu::addItem(), KviKvsPopupMenu::addLabel(), KviKvsPopupMenu::addPopup(), KviKvsPopupMenu::addPrologue(), KviKvsPopupMenu::addSeparator(), PopupTreeWidgetItem::Epilogue, PopupTreeWidgetItem::ExtMenu, i, PopupTreeWidgetItem::Item, PopupTreeWidgetItem::Label, PopupTreeWidgetItem::m_szCode, PopupTreeWidgetItem::m_szCondition, PopupTreeWidgetItem::m_szIcon, PopupTreeWidgetItem::m_szId, PopupTreeWidgetItem::m_szText, PopupTreeWidgetItem::m_type, PopupTreeWidgetItem::Menu, PopupTreeWidgetItem::Prologue, and PopupTreeWidgetItem::Separator.
Referenced by contextCopy(), and getMenu().
void SinglePopupEditor::contextCopy () [protected, slot]
References addItemToMenu(), m_pClipboard, and m_pLastSelectedItem.
Referenced by contextCut(), and customContextMenuRequested().
void SinglePopupEditor::contextCut () [protected, slot]
References contextCopy(), m_pLastSelectedItem, and selectionChanged().
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewEpilogue () [protected, slot]
References PopupTreeWidgetItem::Epilogue, m_pLastSelectedItem, m_pTreeWidget, and newItem().
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewExtMenuAbove () [protected, slot]
References createNewItemAboveLastSelected(), and PopupTreeWidgetItem::ExtMenu.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewExtMenuBelow () [protected, slot]
References createNewItemBelowLastSelected(), and PopupTreeWidgetItem::ExtMenu.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewExtMenuInside () [protected, slot]
References createNewItemInsideLastSelected(), and PopupTreeWidgetItem::ExtMenu.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewItemAbove () [protected, slot]
References createNewItemAboveLastSelected(), and PopupTreeWidgetItem::Item.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewItemBelow () [protected, slot]
References createNewItemBelowLastSelected(), and PopupTreeWidgetItem::Item.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewItemInside () [protected, slot]
References createNewItemInsideLastSelected(), and PopupTreeWidgetItem::Item.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewLabelAbove () [protected, slot]
References createNewItemAboveLastSelected(), and PopupTreeWidgetItem::Label.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewLabelBelow () [protected, slot]
References createNewItemBelowLastSelected(), and PopupTreeWidgetItem::Label.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewLabelInside () [protected, slot]
References createNewItemInsideLastSelected(), and PopupTreeWidgetItem::Label.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewMenuAbove () [protected, slot]
References createNewItemAboveLastSelected(), and PopupTreeWidgetItem::Menu.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewMenuBelow () [protected, slot]
References createNewItemBelowLastSelected(), and PopupTreeWidgetItem::Menu.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewMenuInside () [protected, slot]
References createNewItemInsideLastSelected(), and PopupTreeWidgetItem::Menu.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewPrologue () [protected, slot]
References m_pLastSelectedItem, m_pTreeWidget, newItem(), and PopupTreeWidgetItem::Prologue.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewSeparatorAbove () [protected, slot]
References createNewItemAboveLastSelected(), and PopupTreeWidgetItem::Separator.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewSeparatorBelow () [protected, slot]
References createNewItemBelowLastSelected(), and PopupTreeWidgetItem::Separator.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextNewSeparatorInside () [protected, slot]
References createNewItemInsideLastSelected(), and PopupTreeWidgetItem::Separator.
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextPasteAbove () [protected, slot]
References m_pClipboard, m_pLastSelectedItem, m_pTreeWidget, and populateMenu().
Referenced by customContextMenuRequested().
void SinglePopupEditor::contextPasteBelow () [protected, slot]
References m_pClipboard, m_pLastSelectedItem, and populateMenu().
Referenced by contextPasteInside(), and customContextMenuRequested().
void SinglePopupEditor::contextPasteInside () [protected, slot]
References contextPasteBelow(), m_pClipboard, m_pLastSelectedItem, PopupTreeWidgetItem::m_type, PopupTreeWidgetItem::Menu, and populateMenu().
Referenced by customContextMenuRequested().
void SinglePopupEditor::createNewItemAboveLastSelected (PopupTreeWidgetItem::Type t) [protected]
References m_pLastSelectedItem, m_pTreeWidget, and newItemAbove().
Referenced by contextNewExtMenuAbove(), contextNewItemAbove(), contextNewLabelAbove(), contextNewMenuAbove(), and contextNewSeparatorAbove().
void SinglePopupEditor::createNewItemBelowLastSelected (PopupTreeWidgetItem::Type t) [protected]
References m_pLastSelectedItem, m_pTreeWidget, and newItemBelow().
Referenced by contextNewExtMenuBelow(), contextNewItemBelow(), contextNewLabelBelow(), contextNewMenuBelow(), and contextNewSeparatorBelow().
void SinglePopupEditor::createNewItemInsideLastSelected (PopupTreeWidgetItem::Type t) [protected]
References m_pLastSelectedItem, m_pTreeWidget, and newItemInside().
Referenced by contextNewExtMenuInside(), contextNewItemInside(), contextNewLabelInside(), contextNewMenuInside(), and contextNewSeparatorInside().
void SinglePopupEditor::customContextMenuRequested (const QPoint & pnt) [protected, slot]
References __tr2qs_ctx(), KviTalPopupMenu::clear(), contextCopy(), contextCut(), contextNewEpilogue(), contextNewExtMenuAbove(), contextNewExtMenuBelow(), contextNewExtMenuInside(), contextNewItemAbove(), contextNewItemBelow(), contextNewItemInside(), contextNewLabelAbove(), contextNewLabelBelow(), contextNewLabelInside(), contextNewMenuAbove(), contextNewMenuBelow(), contextNewMenuInside(), contextNewPrologue(), contextNewSeparatorAbove(), contextNewSeparatorBelow(), contextNewSeparatorInside(), contextPasteAbove(), contextPasteBelow(), contextPasteInside(), KviIconManager::Copy, KviIconManager::Cut, KviIconManager::Epilogue, g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), m_pClipboard, m_pContextPopup, m_pTreeWidget, PopupTreeWidgetItem::m_type, PopupTreeWidgetItem::Menu, KviIconManager::Paste, KviIconManager::Prologue, and KviTalPopupMenu::setItemEnabled().
Referenced by SinglePopupEditor().
void SinglePopupEditor::edit (MenuTreeWidgetItem * it)
References m_pConditionEditor, m_pEditor, m_pExtNameEditor, m_pIconEditor, m_pIdEditor, m_pLastSelectedItem, m_pMenuButton, m_pNameEditor, MenuTreeWidgetItem::m_pPopup, m_pTextEditor, m_pTreeWidget, populateMenu(), KviKvsPopupMenu::popupName(), saveLastSelectedItem(), selectionChanged(), and KviScriptEditor::setText().
Referenced by PopupEditorWidget::currentItemChanged(), and PopupEditorWidget::popupRefresh().
PopupTreeWidgetItem * SinglePopupEditor::findMatchingItem (KviKvsPopupMenuItem * it, PopupTreeWidgetItem * item) [protected]
References KviKvsScript::code(), i, PopupTreeWidgetItem::Item, KviKvsPopupMenuItem::Item, KviKvsPopupMenuItem::kvsCode(), KviKvsPopupMenuItem::kvsCondition(), KviKvsPopupMenuItem::kvsIcon(), KviKvsPopupMenuItem::kvsText(), PopupTreeWidgetItem::m_szCode, PopupTreeWidgetItem::m_szCondition, PopupTreeWidgetItem::m_szIcon, PopupTreeWidgetItem::m_szId, PopupTreeWidgetItem::m_szText, PopupTreeWidgetItem::m_type, KviKvsPopupMenuItem::name(), and KviKvsPopupMenuItem::type().
Referenced by testModeMenuItemClicked().
KviKvsPopupMenu * SinglePopupEditor::getMenu ()
References addItemToMenu(), i, m_pNameEditor, m_pTreeWidget, p, and saveLastSelectedItem().
Referenced by PopupEditorWidget::saveLastEditedItem(), and testPopup().
PopupTreeWidgetItem * SinglePopupEditor::newItem (PopupTreeWidgetItem * par, PopupTreeWidgetItem * after, PopupTreeWidgetItem::Type t) [protected]
References m_pTreeWidget.
Referenced by contextNewEpilogue(), contextNewPrologue(), newItemAbove(), newItemBelow(), and newItemInside().
PopupTreeWidgetItem * SinglePopupEditor::newItemAbove (PopupTreeWidgetItem * it, PopupTreeWidgetItem::Type t) [protected]
References m_pTreeWidget, newItem(), and t().
Referenced by createNewItemAboveLastSelected().
PopupTreeWidgetItem * SinglePopupEditor::newItemBelow (PopupTreeWidgetItem * it, PopupTreeWidgetItem::Type t) [protected]
References newItem(), and t().
Referenced by createNewItemBelowLastSelected(), and newItemInside().
PopupTreeWidgetItem * SinglePopupEditor::newItemInside (PopupTreeWidgetItem * it, PopupTreeWidgetItem::Type t) [protected]
References PopupTreeWidgetItem::m_type, PopupTreeWidgetItem::Menu, newItem(), and newItemBelow().
Referenced by createNewItemInsideLastSelected().
void SinglePopupEditor::populateMenu (KviKvsPopupMenu * pop, PopupTreeWidgetItem * par, PopupTreeWidgetItem * theItem = 0) [protected]
References KviKvsScript::code(), PopupTreeWidgetItem::Epilogue, KviKvsPopupMenu::epilogues(), PopupTreeWidgetItem::ExtMenu, KviKvsPopupMenuItem::ExtMenu, KviPointerList< T >::first(), PopupTreeWidgetItem::Item, KviKvsPopupMenuItem::Item, KviKvsPopupMenu::itemList(), KviKvsPopupMenuItem::kvsCondition(), KviKvsPopupMenuItemWithTextAndIcon::kvsIcon(), KviKvsPopupMenuItemWithTextAndIcon::kvsText(), PopupTreeWidgetItem::Label, KviKvsPopupMenuItem::Label, m_pTreeWidget, PopupTreeWidgetItem::Menu, KviKvsPopupMenuItem::Menu, KviKvsPopupMenuItem::name(), KviPointerList< T >::next(), PopupTreeWidgetItem::Prologue, KviKvsPopupMenu::prologues(), PopupTreeWidgetItem::Separator, KviKvsPopupMenuItem::Separator, PopupTreeWidgetItem::setCode(), PopupTreeWidgetItem::setCondition(), PopupTreeWidgetItem::setIcon(), PopupTreeWidgetItem::setId(), and PopupTreeWidgetItem::setItemText().
Referenced by contextPasteAbove(), contextPasteBelow(), contextPasteInside(), and edit().
void SinglePopupEditor::saveLastSelectedItem () [protected]
References PopupTreeWidgetItem::Epilogue, PopupTreeWidgetItem::ExtMenu, KviScriptEditor::getText(), PopupTreeWidgetItem::Item, PopupTreeWidgetItem::Label, m_pConditionEditor, m_pEditor, m_pExtNameEditor, m_pIconEditor, m_pIdEditor, m_pLastSelectedItem, m_pTextEditor, PopupTreeWidgetItem::m_type, PopupTreeWidgetItem::Menu, PopupTreeWidgetItem::Prologue, PopupTreeWidgetItem::Separator, PopupTreeWidgetItem::setCode(), PopupTreeWidgetItem::setCondition(), PopupTreeWidgetItem::setIcon(), PopupTreeWidgetItem::setId(), and PopupTreeWidgetItem::setItemText().
Referenced by edit(), getMenu(), selectionChanged(), and testModeMenuItemClicked().
void SinglePopupEditor::selectionChanged () [protected, slot]
References PopupTreeWidgetItem::Epilogue, PopupTreeWidgetItem::ExtMenu, PopupTreeWidgetItem::Item, PopupTreeWidgetItem::Label, m_pConditionEditor, m_pEditor, m_pExtNameEditor, m_pIconEditor, m_pIdEditor, m_pLastSelectedItem, m_pTextEditor, m_pTreeWidget, PopupTreeWidgetItem::Menu, PopupTreeWidgetItem::Prologue, saveLastSelectedItem(), PopupTreeWidgetItem::Separator, and KviScriptEditor::setText().
Referenced by contextCut(), edit(), SinglePopupEditor(), and testModeMenuItemClicked().
void SinglePopupEditor::testModeMenuItemClicked (KviKvsPopupMenuItem * it) [protected, slot]
References findMatchingItem(), i, m_pTreeWidget, saveLastSelectedItem(), and selectionChanged().
Referenced by testPopup().
void SinglePopupEditor::testPopup () [protected, slot]
References KviKvsVariantList::append(), connect(), KviKvsPopupMenu::doPopup(), g_pActiveWindow, getMenu(), m_pMenuButton, m_pTestPopup, and testModeMenuItemClicked().
Referenced by SinglePopupEditor().
Member Data Documentation
KviKvsPopupMenu* SinglePopupEditor::m_pClipboard [protected]
Referenced by contextCopy(), contextPasteAbove(), contextPasteBelow(), contextPasteInside(), customContextMenuRequested(), SinglePopupEditor(), and ~SinglePopupEditor().
QLineEdit* SinglePopupEditor::m_pConditionEditor [protected]
Referenced by edit(), saveLastSelectedItem(), selectionChanged(), and SinglePopupEditor().
KviTalPopupMenu* SinglePopupEditor::m_pContextPopup [protected]
Referenced by customContextMenuRequested(), and SinglePopupEditor().
KviScriptEditor* SinglePopupEditor::m_pEditor [protected]
Referenced by edit(), saveLastSelectedItem(), selectionChanged(), SinglePopupEditor(), and ~SinglePopupEditor().
QLineEdit* SinglePopupEditor::m_pExtNameEditor [protected]
Referenced by edit(), saveLastSelectedItem(), selectionChanged(), and SinglePopupEditor().
QLineEdit* SinglePopupEditor::m_pIconEditor [protected]
Referenced by edit(), saveLastSelectedItem(), selectionChanged(), and SinglePopupEditor().
QLineEdit* SinglePopupEditor::m_pIdEditor [protected]
Referenced by edit(), saveLastSelectedItem(), selectionChanged(), and SinglePopupEditor().
PopupTreeWidgetItem* SinglePopupEditor::m_pLastSelectedItem [protected]
Referenced by contextCopy(), contextCut(), contextNewEpilogue(), contextNewPrologue(), contextPasteAbove(), contextPasteBelow(), contextPasteInside(), createNewItemAboveLastSelected(), createNewItemBelowLastSelected(), createNewItemInsideLastSelected(), edit(), saveLastSelectedItem(), selectionChanged(), and SinglePopupEditor().
QPushButton* SinglePopupEditor::m_pMenuButton [protected]
Referenced by edit(), SinglePopupEditor(), and testPopup().
QLineEdit* SinglePopupEditor::m_pNameEditor [protected]
Referenced by edit(), getMenu(), and SinglePopupEditor().
KviKvsPopupMenu* SinglePopupEditor::m_pTestPopup [protected]
Referenced by SinglePopupEditor(), testPopup(), and ~SinglePopupEditor().
QLineEdit* SinglePopupEditor::m_pTextEditor [protected]
Referenced by edit(), saveLastSelectedItem(), selectionChanged(), and SinglePopupEditor().
QTreeWidget* SinglePopupEditor::m_pTreeWidget [protected]
Referenced by contextNewEpilogue(), contextNewPrologue(), contextPasteAbove(), createNewItemAboveLastSelected(), createNewItemBelowLastSelected(), createNewItemInsideLastSelected(), customContextMenuRequested(), edit(), getMenu(), newItem(), newItemAbove(), populateMenu(), selectionChanged(), SinglePopupEditor(), and testModeMenuItemClicked().
The documentation for this class was generated from the following files:
src/modules/popupeditor/PopupEditorWindow.h
src/modules/popupeditor/PopupEditorWindow.cpp