KVIrc: KviStatusBarApplet Class Reference
KviStatusBarApplet Class Reference
#include <kvi_statusbarapplet.h>
Public Member Functions
KviStatusBarAppletDescriptor * descriptor ()
KviFrame * frame ()
int index ()
bool isSelected ()
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void select (bool bSelect=true)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Protected Member Functions
virtual void fillContextPopup (KviTalPopupMenu *)
virtual void loadState (const char *, KviConfig *)
virtual void paintEvent (QPaintEvent *e)
virtual void saveState (const char *, KviConfig *)
virtual QString tipText (const QPoint &)
Protected Attributes
bool m_bSelected
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Friends
class KviStatusBar
Constructor & Destructor Documentation
KviStatusBarApplet::KviStatusBarApplet (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
References m_bSelected, m_pDescriptor, m_pStatusBar, KviStatusBar::registerApplet(), and KviStatusBarAppletDescriptor::registerApplet().
KviStatusBarApplet::~KviStatusBarApplet () [virtual]
References m_pDescriptor, m_pStatusBar, KviStatusBar::unregisterApplet(), and KviStatusBarAppletDescriptor::unregisterApplet().
Member Function Documentation
KviStatusBarAppletDescriptor* KviStatusBarApplet::descriptor () [inline]
Referenced by KviStatusBar::contextPopupAboutToShow(), and KviStatusBar::tipRequest().
virtual void KviStatusBarApplet::fillContextPopup (KviTalPopupMenu *) [inline, protected, virtual]
Reimplemented in KviStatusBarClock, KviStatusBarConnectionTimer, KviStatusBarAwayIndicator, and KviStatusBarUpdateIndicator.
Referenced by KviStatusBar::contextPopupAboutToShow().
KviFrame* KviStatusBarApplet::frame () [inline]
int KviStatusBarApplet::index () [inline]
Referenced by KviStatusBar::appletsPopupActivated(), and KviStatusBar::mouseReleaseEvent().
bool KviStatusBarApplet::isSelected () [inline]
virtual void KviStatusBarApplet::loadState (const char * , KviConfig *) [inline, protected, virtual]
Reimplemented in KviStatusBarClock, KviStatusBarConnectionTimer, KviStatusBarAwayIndicator, and KviStatusBarUpdateIndicator.
Referenced by KviStatusBar::load().
void KviStatusBarApplet::paintEvent (QPaintEvent * e) [protected, virtual]
References KVI_OPTION_FONT, KviOption_fontIrcToolBarApplet, and m_bSelected.
virtual void KviStatusBarApplet::saveState (const char * , KviConfig *) [inline, protected, virtual]
Reimplemented in KviStatusBarClock, KviStatusBarConnectionTimer, KviStatusBarAwayIndicator, and KviStatusBarUpdateIndicator.
void KviStatusBarApplet::select (bool bSelect = true)
References m_bSelected.
Referenced by KviStatusBar::mousePressEvent(), and KviStatusBar::mouseReleaseEvent().
void KviStatusBarApplet::setIndex (int i) [inline]
Referenced by CreateStatusBarAwayIndicator(), CreateStatusBarClock(), CreateStatusBarConnectionTimer(), CreateStatusBarLagIndicator(), CreateStatusBarSeparator(), CreateStatusBarUpdateIndicator(), and KviStatusBar::mouseReleaseEvent().
KviStatusBar* KviStatusBarApplet::statusBar () [inline]
Referenced by KviStatusBarLagIndicator::mouseDoubleClickEvent(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviStatusBarLagIndicator::tipText(), KviStatusBarAwayIndicator::tipText(), KviStatusBarLagIndicator::updateDisplay(), and KviStatusBarAwayIndicator::updateDisplay().
QString KviStatusBarApplet::tipText (const QPoint &) [protected, virtual]
Reimplemented in KviStatusBarAwayIndicator, KviStatusBarLagIndicator, and KviStatusBarUpdateIndicator.
Referenced by KviStatusBar::tipRequest().
Friends And Related Function Documentation
friend class KviStatusBar [friend]
Member Data Documentation
bool KviStatusBarApplet::m_bSelected [protected]
Referenced by KviStatusBarApplet(), paintEvent(), and select().
KviStatusBarAppletDescriptor* KviStatusBarApplet::m_pDescriptor [protected]
Referenced by KviStatusBarApplet(), and ~KviStatusBarApplet().
KviStatusBar* KviStatusBarApplet::m_pStatusBar [protected]
Referenced by KviStatusBarApplet(), and ~KviStatusBarApplet().
int KviStatusBarApplet::mIndex [protected]
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_statusbarapplet.h
src/kvirc/ui/kvi_statusbarapplet.cpp