KVIrc: KviTalListWidgetText Class Reference
KviTalListWidgetText Class Reference
#include <kvi_tal_listwidget.h>
Public Types
enum { RTTI = 1 }
Public Member Functions
int height (const KviTalListWidget *) const
KviTalListWidgetText (const QString &text=QString())
KviTalListWidgetText (KviTalListWidget *listbox, const QString &text=QString())
int rtti () const
int width (const KviTalListWidget *) const
~KviTalListWidgetText ()
Protected Member Functions
virtual void paint (QPainter *)
Member Enumeration Documentation
anonymous enum
Enumerator:
RTTI
Constructor & Destructor Documentation
KviTalListWidgetText::KviTalListWidgetText (KviTalListWidget * listbox, const QString & text = QString())
KviTalListWidgetText::KviTalListWidgetText (const QString & text = QString())
KviTalListWidgetText::~KviTalListWidgetText ()
Member Function Documentation
int KviTalListWidgetText::height (const KviTalListWidget * lb) const
Referenced by paint().
void KviTalListWidgetText::paint (QPainter * painter) [protected, virtual]
References height(), and KviTalListWidgetItem::listWidget().
int KviTalListWidgetText::rtti () const
References RTTI.
int KviTalListWidgetText::width (const KviTalListWidget * lb) const
Reimplemented in KviTopicListBoxItem.
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/tal/kvi_tal_listwidget.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/tal/kvi_tal_listwidget.cpp