KVIrc: KviKvsTreeNodeModuleFunctionCall Class Reference
KviKvsTreeNodeModuleFunctionCall Class Reference
#include <KviKvsTreeNodeModuleFunctionCall.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeModuleFunctionCall (const QChar *pLocation, const QString &szModuleName, const QString &szFncName, KviKvsTreeNodeDataList *pParams)
~KviKvsTreeNodeModuleFunctionCall ()
Public Member Functions inherited from KviKvsTreeNodeFunctionCall
virtual bool canEvaluateToObjectReference ()
virtual bool isFunctionCall ()
KviKvsTreeNodeFunctionCall (const QChar *pLocation, const QString &szFunctionName, KviKvsTreeNodeDataList *pParams)
~KviKvsTreeNodeFunctionCall ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
QString m_szModuleName
Protected Attributes inherited from KviKvsTreeNodeFunctionCall
KviKvsTreeNodeDataList * m_pParams
QString m_szFunctionName
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeModuleFunctionCall::KviKvsTreeNodeModuleFunctionCall (const QChar * pLocation, const QString & szModuleName, const QString & szFncName, KviKvsTreeNodeDataList * pParams)
References m_szModuleName.
KviKvsTreeNodeModuleFunctionCall::~KviKvsTreeNodeModuleFunctionCall ()
Member Function Documentation
void KviKvsTreeNodeModuleFunctionCall::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeFunctionCall.
References KviKvsTreeNodeFunctionCall::m_szFunctionName, and m_szModuleName.
void KviKvsTreeNodeModuleFunctionCall::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeFunctionCall.
References KviKvsTreeNodeDataList::dump(), KviKvsTreeNodeFunctionCall::m_pParams, KviKvsTreeNodeFunctionCall::m_szFunctionName, and m_szModuleName.
bool KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsRunTimeContext::error(), KviKvsTreeNodeDataList::evaluate(), g_pModuleManager, KviModuleManager::getModule(), KviKvsModuleInterface::kvsFindFunction(), l, KviModuleManager::lastError(), m, KviKvsTreeNodeFunctionCall::m_pParams, KviKvsTreeNodeFunctionCall::m_szFunctionName, m_szModuleName, KviKvsRunTimeContext::setDefaultReportLocation(), and KviKvsVariant::setNothing().
Member Data Documentation
QString KviKvsTreeNodeModuleFunctionCall::m_szModuleName protected
Referenced by contextDescription(), dump(), evaluateReadOnly(), and KviKvsTreeNodeModuleFunctionCall().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeModuleFunctionCall.h
src/kvirc/kvs/tree/KviKvsTreeNodeModuleFunctionCall.cpp