KVIrc: RegisteredUsersDialogItemBase Class Reference
RegisteredUsersDialogItemBase Class Reference
#include <RegisteredUsersDialog.h>
Public Types
enum Types { User, Group }
Public Member Functions
RegisteredUsersDialogItemBase::Types type ()
Protected Member Functions
RegisteredUsersDialogItemBase (Types type, KviRegisteredUsersListView *par)
RegisteredUsersDialogItemBase (Types type, QTreeWidgetItem *par)
~RegisteredUsersDialogItemBase ()
Private Attributes
RegisteredUsersDialogItemBase::Types m_iType
Member Enumeration Documentation
enum RegisteredUsersDialogItemBase::Types
Enumerator:
User
Group
Constructor & Destructor Documentation
RegisteredUsersDialogItemBase::RegisteredUsersDialogItemBase (Types type, KviRegisteredUsersListView * par) [inline, protected]
RegisteredUsersDialogItemBase::RegisteredUsersDialogItemBase (Types type, QTreeWidgetItem * par) [inline, protected]
RegisteredUsersDialogItemBase::~RegisteredUsersDialogItemBase () [inline, protected]
Member Function Documentation
RegisteredUsersDialogItemBase::Types RegisteredUsersDialogItemBase::type () [inline]
References m_iType.
Referenced by RegisteredUsersDialog::editClicked(), RegisteredUsersDialog::exportClicked(), RegisteredUsersDialog::itemDoubleClicked(), RegisteredUsersDialog::itemPressed(), RegisteredUsersDialog::moveToGroupMenuClicked(), RegisteredUsersDialogItemDelegate::paint(), RegisteredUsersDialog::removeClicked(), RegisteredUsersDialog::rightButtonPressed(), and RegisteredUsersDialogItemDelegate::sizeHint().
Member Data Documentation
RegisteredUsersDialogItemBase::Types RegisteredUsersDialogItemBase::m_iType [private]
Referenced by type().
The documentation for this class was generated from the following file:
src/modules/reguser/RegisteredUsersDialog.h