KVIrc: MessageColorListWidgetItem Class Reference
MessageColorListWidgetItem Class Reference
#include <OptionsWidget_message.h>
Public Member Functions
int clrIdx ()
MessageColorListWidgetItem (KviTalListWidget *b, int idx)
~MessageColorListWidgetItem ()
Public Member Functions inherited from KviTalListWidgetText
int height (const KviTalListWidget *) const
KviTalListWidgetText (KviTalListWidget *listbox, const QString &text=QString())
KviTalListWidgetText (const QString &text=QString())
int rtti () const
int width (const KviTalListWidget *) const
~KviTalListWidgetText ()
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Public Attributes
int m_iClrIdx
Additional Inherited Members
Public Types inherited from KviTalListWidgetText
enum { RTTI = 1 }
Protected Member Functions inherited from KviTalListWidgetText
virtual void paint (QPainter *)
Constructor & Destructor Documentation
MessageColorListWidgetItem::MessageColorListWidgetItem (KviTalListWidget * b, int idx)
References __tr2qs_ctx(), KVI_OPTION_MIRCCOLOR, KviTalListWidgetItem::listWidget(), and m_iClrIdx.
MessageColorListWidgetItem::~MessageColorListWidgetItem ()
Member Function Documentation
int MessageColorListWidgetItem::clrIdx () inline
References m_iClrIdx.
Referenced by MessageColorListWidgetItemDelegate::paint().
Member Data Documentation
int MessageColorListWidgetItem::m_iClrIdx
Referenced by clrIdx(), MessageColorListWidgetItem(), and OptionsWidget_messageColors::saveLastItem().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_message.h
src/modules/options/OptionsWidget_message.cpp