KVIrc: KviMainWindow Class Reference
KviMainWindow Class Reference
#include <KviMainWindow.h>
Public Slots
void customizeToolBars ()
void executeInternalCommand (int index)
void newConsole ()
void toggleStatusBar ()
Signals
void activeConnectionAwayStateChanged ()
void activeConnectionLagChanged ()
void activeConnectionNickNameChanged ()
void activeConnectionServerInfoChanged ()
void activeConnectionUserModeChanged ()
void activeContextChanged ()
void activeContextStateChanged ()
void activeWindowChanged ()
void activeWindowSelectionStateChanged (bool bGotSelectionNow)
void signalMaximizeMdiChildWindow (KviMdiChild *lpC)
Public Member Functions
KviIrcConnection * activeConnection ()
KviIrcContext * activeContext ()
void addWindow (KviWindow *wnd, bool bShow=true)
void closeWindow (KviWindow *wnd)
unsigned int consoleCount ()
KviConsoleWindow * createNewConsole (bool bFirstInFrame=false, bool bShowIt=true)
void fillIconSizePopup (QMenu *p)
void fillToolBarsPopup (QMenu *p)
KviConsoleWindow * firstConsole ()
KviConsoleWindow * firstNotConnectedConsole ()
void freeAccelleratorKeySequence (QString &key)
KviMainWindow ()
KviMenuBar * mainMenuBar ()
KviStatusBar * mainStatusBar ()
KviMdiManager * mdiManager ()
KviMexToolBar * moduleExtensionToolBar (int extensionId)
void saveWindowProperties (KviWindow *wnd, const QString &szSection)
void setActiveWindow (KviWindow *wnd)
void setButtonStyle (unsigned int uStyle)
void setIconSize (unsigned int uSize)
void setTrayIcon (KviTrayIcon *e)
QSplitter * splitter ()
KviTrayIcon * trayIcon ()
bool windowExists (KviWindow *wnd)
KviPointerList< KviWindow > * windowList ()
KviWindowListBase * windowListWidget ()
~KviMainWindow ()
Public Member Functions inherited from KviTalMainWindow
KviTalMainWindow (QWidget *pParent, const char *pcName)
Constructs the mainwindow object.
~KviTalMainWindow ()
Destroys the mainwindow object.
Protected Slots
void accelActivated ()
void buttonStylePopupSelected (QAction *pAction)
void iconSizePopupSelected (QAction *pAction)
void maximizeWindow ()
void minimizeWindow ()
void switchToNextHighlightedWindow ()
void switchToNextWindow ()
void switchToNextWindowInContext ()
void switchToPrevHighlightedWindow ()
void switchToPrevWindow ()
void switchToPrevWindowInContext ()
void toolbarsPopupSelected (QAction *pAction)
Protected Member Functions
void applyOptions ()
virtual void changeEvent (QEvent *event)
void childConnectionAwayStateChange (KviIrcConnection *c)
void childConnectionLagChange (KviIrcConnection *c)
void childConnectionNickNameChange (KviIrcConnection *c)
void childConnectionServerInfoChange (KviIrcConnection *c)
void childConnectionUserModeChange (KviIrcConnection *c)
void childContextStateChange (KviIrcContext *c)
void childWindowActivated (KviWindow *wnd, bool bForce=false)
void childWindowCloseRequest (KviWindow *wnd)
void childWindowSelectionStateChange (KviWindow *pWnd, bool bGotSelectionNow)
virtual void closeEvent (QCloseEvent *e)
virtual void contextMenuEvent (QContextMenuEvent *event)
void createWindowList ()
KviMdiChild * dockWindow (KviWindow *wnd)
virtual bool focusNextPrevChild (bool next)
virtual void hideEvent (QHideEvent *e)
void installAccelerators ()
virtual void moveEvent (QMoveEvent *e)
void recreateWindowList ()
void registerModuleExtensionToolBar (KviMexToolBar *t)
virtual void resizeEvent (QResizeEvent *e)
void restoreModuleExtensionToolBars ()
void saveModuleExtensionToolBars ()
void undockWindow (KviWindow *wnd)
void unregisterModuleExtensionToolBar (KviMexToolBar *t)
void updatePseudoTransparency ()
Protected Attributes
KviPointerList< QShortcut > * m_pAccellerators
KviIrcContext * m_pActiveContext
KviMdiManager * m_pMdi
KviMenuBar * m_pMenuBar
KviPointerList< KviMexToolBar > * m_pModuleExtensionToolBarList
QSplitter * m_pSplitter
KviStatusBar * m_pStatusBar
KviTrayIcon * m_pTrayIcon
KviWindowListBase * m_pWindowList
KviPointerList< KviWindow > * m_pWinList
Private Member Functions
void restoreToolBarPositions ()
void saveToolBarPositions ()
Friends
class KviApplication
class KviConsoleWindow
class KviIrcConnection
class KviIrcContext
class KviIrcServerParser
class KviLagMeter
class KviMdiManager
class KviMexToolBar
class KviUserListView
class KviUserListViewArea
class KviWindow
Constructor & Destructor Documentation
KviMainWindow::KviMainWindow ()
References applyOptions(), createWindowList(), g_pApp, g_pIconManager, g_pMainWindow, KviIconManager::getSmallIcon(), installAccelerators(), KVI_DEFAULT_FRAME_CAPTION, KVI_OPTION_BOOL, KVI_OPTION_RECT, KVI_OPTION_UINT, KviMdiManager, KviOption_boolFrameIsMaximized, KviOption_boolStatusBarVisible, KviOption_rectFrameGeometry, KviOption_uintToolBarButtonStyle, KviOption_uintToolBarIconSize, KviIconManager::KVIrc, KviStatusBar::load(), m_pAccellerators, m_pActiveContext, m_pMdi, m_pMenuBar, m_pModuleExtensionToolBarList, m_pSplitter, m_pStatusBar, m_pTrayIcon, m_pWindowList, m_pWinList, KviMemory::move(), NULL, r, KviPointerList< T >::setAutoDelete(), setButtonStyle(), setIconSize(), x, and y.
KviMainWindow::~KviMainWindow ()
References KviPointerList< T >::at(), closeWindow(), KviWindow::Console, KviPointerList< T >::count(), KviTrayIcon::die(), KviPointerList< T >::first(), KviApplication::frameDestructorCallback(), g_pApp, g_pMainWindow, i, KviCustomToolBarManager::instance(), KviMdiManager::isInSDIMode(), KVI_OPTION_BOOL, KVI_OPTION_RECT, KviOption_boolFrameIsMaximized, KviOption_boolMdiManagerInSdiMode, KviOption_boolShowDockExtension, KviOption_boolStatusBarVisible, KviOption_rectFrameGeometry, m_pAccellerators, m_pMdi, m_pModuleExtensionToolBarList, m_pStatusBar, m_pTrayIcon, m_pWinList, NULL, saveModuleExtensionToolBars(), saveToolBarPositions(), KviCustomToolBarManager::storeVisibilityState(), t(), KviWindow::type(), x, and y.
Member Function Documentation
void KviMainWindow::accelActivated () protected slot
References g_pActiveWindow, KviEvent_OnAccelKeyPressed, KVS_TRIGGER_EVENT_1, and KviStringConversion::toString().
Referenced by installAccelerators().
KviIrcConnection * KviMainWindow::activeConnection ()
References KviIrcContext::connection(), and m_pActiveContext.
Referenced by KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviStatusBarLagIndicator::mouseDoubleClickEvent(), KviStatusBarAwayIndicator::tipText(), and KviStatusBarLagIndicator::tipText().
void KviMainWindow::activeConnectionAwayStateChanged () signal
Referenced by childConnectionAwayStateChange(), and KviStatusBarAwayIndicator::KviStatusBarAwayIndicator().
void KviMainWindow::activeConnectionLagChanged () signal
Referenced by childConnectionLagChange(), and KviStatusBarLagIndicator::KviStatusBarLagIndicator().
void KviMainWindow::activeConnectionNickNameChanged () signal
Referenced by childConnectionNickNameChange().
void KviMainWindow::activeConnectionServerInfoChanged () signal
Referenced by childConnectionServerInfoChange().
void KviMainWindow::activeConnectionUserModeChanged () signal
Referenced by childConnectionUserModeChange().
KviIrcContext* KviMainWindow::activeContext () inline
Referenced by KviConnectAction::activate(), KviAction::activeContextChanged(), KviConnectAction::activeContextStateChanged(), KviGoAwayAction::activeContextStateChanged(), KviAction::activeContextStateChanged(), KviAction::activeWindowChanged(), KviConnectAction::addToPopupMenu(), KviGoAwayAction::addToPopupMenu(), executeInternalCommand(), KviStatusBar::mouseDoubleClickEvent(), KviStatusBar::setPermanentMessage(), KviAction::setup(), KviStatusBar::tipRequest(), KviStatusBarAwayIndicator::updateDisplay(), KviStatusBarLagIndicator::updateDisplay(), and KviMenuBar::updateMainPopup().
void KviMainWindow::activeContextChanged () signal
Referenced by childWindowActivated(), KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), and KviStatusBarLagIndicator::KviStatusBarLagIndicator().
void KviMainWindow::activeContextStateChanged () signal
Referenced by childContextStateChange(), KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), and KviStatusBarLagIndicator::KviStatusBarLagIndicator().
void KviMainWindow::activeWindowChanged () signal
Referenced by childWindowActivated().
void KviMainWindow::activeWindowSelectionStateChanged (bool bGotSelectionNow) signal
Referenced by childWindowSelectionStateChange().
void KviMainWindow::addWindow (KviWindow * wnd, bool bShow = true)
References KviPointerList< T >::append(), KviWindow::Channel, childWindowActivated(), KviWindow::context(), KviPointerList< T >::count(), KviWindow::createWindowListItem(), dockWindow(), g_pActiveWindow, KviWindow::getConfigGroupName(), KviConfigurationFile::hasGroup(), KVI_OPTION_BOOL, KviOption_boolWindowsRememberProperties, KviWindow::loadProperties(), m_pActiveContext, m_pMdi, m_pWinList, KviWindow::maximize(), KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readRectEntry(), KviConfigurationFile::setGroup(), KviMdiManager::showAndActivate(), KviWindow::triggerCreationEvents(), KviWindow::type(), KviWindow::typeString(), KviWindow::windowName(), and KviWindow::youAreUndocked().
Referenced by actioneditor_kvs_cmd_open(), DccBroker::activeVideoExecute(), DccBroker::activeVoiceExecute(), aliaseditor_kvs_cmd_open(), classeditor_kvs_cmd_open(), codetester_kvs_cmd_open(), KviIrcConnection::createChannel(), createNewConsole(), KviIrcConnection::createQuery(), eventeditor_kvs_cmd_open(), DccBroker::executeChat(), filetransferwindow_alloc(), KviDebugWindow::getInstance(), help_kvs_cmd_open(), KvsObject_window::init(), iograph_module_cmd_open(), links_kvs_cmd_open(), list_kvs_cmd_open(), logview_kvs_cmd_open(), DccBroker::passiveVideoExecute(), DccBroker::passiveVoiceExecute(), popupeditor_kvs_cmd_open(), raweditor_kvs_cmd_open(), sharedfileswindow_kvs_cmd_open(), socketspy_kvs_cmd_open(), term_kvs_cmd_open(), url_kvs_cmd_list(), and window_kvs_fnc_open().
void KviMainWindow::applyOptions () protected
References KviWindowListBase::applyOptions(), KviTextIconManager::applyOptions(), KviPointerList< T >::first(), g_pTextIconManager, m_pMdi, m_pWindowList, m_pWinList, and KviPointerList< T >::next().
Referenced by KviMainWindow(), and KviApplication::updateGui().
void KviMainWindow::buttonStylePopupSelected (QAction * pAction) protected slot
References setButtonStyle().
void KviMainWindow::changeEvent (QEvent * event) protected virtual
References childWindowActivated(), g_pActiveWindow, KviWindow::lostUserFocus(), setActiveWindow(), and KviWindow::windowName().
void KviMainWindow::childConnectionAwayStateChange (KviIrcConnection * c) protected
References activeConnectionAwayStateChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::changeAwayState().
void KviMainWindow::childConnectionLagChange (KviIrcConnection * c) protected
References activeConnectionLagChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviLagMeter::timerEvent().
void KviMainWindow::childConnectionNickNameChange (KviIrcConnection * c) protected
References activeConnectionNickNameChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::nickChange().
void KviMainWindow::childConnectionServerInfoChange (KviIrcConnection * c) protected
References activeConnectionServerInfoChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::serverInfoReceived().
void KviMainWindow::childConnectionUserModeChange (KviIrcConnection * c) protected
References activeConnectionUserModeChanged(), KviIrcConnection::context(), and m_pActiveContext.
Referenced by KviIrcConnection::changeUserMode().
void KviMainWindow::childContextStateChange (KviIrcContext * c) protected
References activeContextStateChanged(), and m_pActiveContext.
Referenced by KviIrcContext::setState().
void KviMainWindow::childWindowActivated (KviWindow * wnd, bool bForce = false) protected
References activeContextChanged(), activeWindowChanged(), KviIrcView::clearUnreaded(), KviWindow::context(), g_pActiveWindow, KviEvent_OnWindowActivated, KVS_TRIGGER_EVENT_0, KviWindow::lostUserFocus(), m_pActiveContext, m_pWindowList, KviWindowListBase::setActiveItem(), KviWindow::view(), and KviWindow::windowListItem().
Referenced by addWindow(), changeEvent(), closeWindow(), KviWindow::eventFilter(), KviWindow::focusInEvent(), and KviMdiManager::processWindowStateChanged().
void KviMainWindow::childWindowCloseRequest (KviWindow * wnd) protected
References closeWindow().
Referenced by KviWindow::closeEvent().
void KviMainWindow::childWindowSelectionStateChange (KviWindow * pWnd, bool bGotSelectionNow) protected
References activeWindowSelectionStateChanged(), and g_pActiveWindow.
Referenced by KviUserListView::insertUserEntry(), KviUserListViewArea::keyPressEvent(), KviUserListViewArea::mouseMoveEvent(), KviUserListViewArea::mousePressEvent(), KviUserListView::partInternal(), KviUserListView::removeAllEntries(), and KviUserListView::select().
void KviMainWindow::closeEvent (QCloseEvent * e) protected virtual
References __tr2qs, KviWindow::Console, executeInternalCommand(), KviPointerList< T >::first(), g_pApp, KVI_INTERNALCOMMAND_TRAYICON_SHOW, KVI_OPTION_BOOL, KviOption_boolCloseInTray, KviOption_boolConfirmCloseWhenThereAreConnections, KviOption_boolFrameIsMaximized, m_pWinList, KviPointerList< T >::next(), KviApplication::setKviClosingDown(), trayIcon(), w, and KviMessageBox::warning().
void KviMainWindow::closeWindow (KviWindow * wnd)
References childWindowActivated(), consoleCount(), KviMdiManager::destroyChild(), KviPointerList< T >::first(), g_pActiveWindow, g_pApp, KviWindow::getConfigGroupName(), KVI_OPTION_BOOL, KviApplication::kviClosingDown(), KviEvent_OnFrameWindowDestroyed, KviEvent_OnKVIrcShutdown, KviOption_boolWindowsRememberProperties, KVS_TRIGGER_EVENT_0, m_pActiveContext, m_pMdi, m_pWinList, KviWindow::mdiParent(), KviPointerList< T >::next(), NULL, KviPointerList< T >::removeRef(), saveWindowProperties(), and KviWindow::triggerDestructionEvents().
Referenced by actioneditor_module_cleanup(), aliaseditor_module_cleanup(), childWindowCloseRequest(), classeditor_module_cleanup(), KviIrcContext::closeAllContextWindows(), KviIrcContext::closeAllDeadChannels(), KviIrcContext::closeAllDeadQueries(), eventeditor_module_cleanup(), filetransferwindow_module_cleanup(), iograph_module_cleanup(), logview_module_cleanup(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralPart(), popupeditor_module_cleanup(), raweditor_module_cleanup(), sharedfileswindow_module_cleanup(), and ~KviMainWindow().
unsigned int KviMainWindow::consoleCount ()
References KviWindow::Console, KviPointerList< T >::first(), m_pWinList, and KviPointerList< T >::next().
Referenced by KviConsoleWindow::closeEvent(), and closeWindow().
void KviMainWindow::contextMenuEvent (QContextMenuEvent * event) protected virtual
KviConsoleWindow * KviMainWindow::createNewConsole (bool bFirstInFrame = false, bool bShowIt = true)
References addWindow(), c, KviCustomToolBarManager::createToolBarsVisibleAtStartup(), KviActionManager::delayedRegisterAccelerators(), KviCustomToolBarManager::instance(), KviActionManager::instance(), KVI_CONSOLE_FLAG_FIRSTINFRAME, KviConsoleWindow, restoreModuleExtensionToolBars(), and restoreToolBarPositions().
Referenced by KviApplication::createFrame(), KviKvsCoreSimpleCommands::KVSCSC(), newConsole(), and KviIrcUrl::run().
void KviMainWindow::createWindowList () protected
References KviWindowListBase::currentDockArea(), KVI_OPTION_BOOL, KviOption_boolUseTreeWindowListWindowList, and m_pWindowList.
Referenced by KviMainWindow(), and recreateWindowList().
void KviMainWindow::customizeToolBars () slot
References g_pActiveWindow, and KviIrcUrl::run().
Referenced by fillToolBarsPopup().
KviMdiChild * KviMainWindow::dockWindow (KviWindow * wnd) protected
References m_pMdi, KviMdiManager::manageChild(), KviWindow::mdiParent(), KviMdiChild::setClient(), and KviWindow::youAreDocked().
Referenced by addWindow(), and KviWindow::dock().
void KviMainWindow::executeInternalCommand (int index) slot
References activeContext(), KviIrcContext::console(), KviIrcView::console(), firstConsole(), kvi_getInternalCommandBuffer(), and KviIrcUrl::run().
Referenced by KviMenuBar::actionTriggered(), closeEvent(), KviApplication::createFrame(), KviTrayIconWidget::executeInternalCommand(), ThemeManagementDialog::getMoreThemes(), KviIrcConnectionTargetResolver::haveServerIp(), hideEvent(), KviIrcConnection::linkAttemptFailed(), KviIrcConnection::linkTerminated(), KviIrcConnection::loginComplete(), KviApplication::optionResetUpdate(), OptionsWidget_tray::setEnabled(), KviApplication::setup(), KviIrcConnection::start(), KviConsoleWindow::triggerCreationEvents(), and KviIrcConnection::~KviIrcConnection().
void KviMainWindow::fillIconSizePopup (QMenu * p)
void KviMainWindow::fillToolBarsPopup (QMenu * p)
References __tr2qs, connect(), KviPointerHashTableIterator< Key, T >::current(), customizeToolBars(), d, KviPointerList< T >::first(), g_pIconManager, g_pModuleExtensionManager, KviModuleExtensionManager::getExtensionList(), KviIconManager::getImage(), KviIconManager::getSmallIcon(), KviCustomToolBarManager::instance(), l, moduleExtensionToolBar(), KviPointerList< T >::next(), KviIconManager::ToolBar, and toolbarsPopupSelected().
Referenced by KviToolBar::mousePressEvent(), and KviMenuBar::updateToolbarsPopup().
KviConsoleWindow * KviMainWindow::firstConsole ()
References KviWindow::Console, KviPointerList< T >::first(), m_pWinList, KviPointerList< T >::next(), and NULL.
Referenced by KviApplication::activeConsole(), KviApplication::createFrame(), dcc_kvs_parse_default_parameters(), DccChatWindow::event(), DccVideoWindow::event(), executeInternalCommand(), KviApplication::ipcMessage(), KviApplication::loadDefaultScript(), KviModuleManager::loadModule(), KviMenuBar::modulesToolsTriggered(), KviMenuBar::newConnectionToServer(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), restoreModuleExtensionToolBars(), toolbarsPopupSelected(), and KviModuleManager::unloadModule().
KviConsoleWindow * KviMainWindow::firstNotConnectedConsole ()
References KviWindow::Console, KviPointerList< T >::first(), m_pWinList, and KviPointerList< T >::next().
Referenced by KviKvsCoreSimpleCommands::KVSCSC(), and KviIrcUrl::run().
bool KviMainWindow::focusNextPrevChild (bool next) protected virtual
References v, and w.
void KviMainWindow::freeAccelleratorKeySequence (QString & key)
References KviPointerList< T >::first(), m_pAccellerators, KviPointerList< T >::next(), and KviPointerList< T >::removeRef().
Referenced by KviAction::registerAccelerator().
void KviMainWindow::hideEvent (QHideEvent * e) protected virtual
References executeInternalCommand(), KVI_INTERNALCOMMAND_TRAYICON_SHOW, KVI_OPTION_BOOL, KviOption_boolFrameIsMaximized, KviOption_boolMinimizeInTray, and trayIcon().
void KviMainWindow::iconSizePopupSelected (QAction * pAction) protected slot
References g_pApp, KviApplication::optionResetUpdate(), and setIconSize().
void KviMainWindow::installAccelerators () protected
References accelActivated(), KviPointerList< T >::append(), KviShortcut::create(), i, KVI_SHORTCUTS_WIN_MAXIMIZE, KVI_SHORTCUTS_WIN_MINIMIZE, KVI_SHORTCUTS_WIN_NEXT, KVI_SHORTCUTS_WIN_NEXT_CONTEXT, KVI_SHORTCUTS_WIN_NEXT_HIGHLIGHT, KVI_SHORTCUTS_WIN_PREV, KVI_SHORTCUTS_WIN_PREV_CONTEXT, KVI_SHORTCUTS_WIN_PREV_HIGHLIGHT, m_pAccellerators, maximizeWindow(), minimizeWindow(), switchToNextHighlightedWindow(), switchToNextWindow(), switchToNextWindowInContext(), switchToPrevHighlightedWindow(), switchToPrevWindow(), and switchToPrevWindowInContext().
Referenced by KviMainWindow().
KviMenuBar* KviMainWindow::mainMenuBar () inline
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
KviStatusBar* KviMainWindow::mainStatusBar () inline
Referenced by KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), torrent_module_init(), and KviMenuBar::updateSettingsPopup().
void KviMainWindow::maximizeWindow (void) protected slot
References g_pActiveWindow, KviWindow::isMaximized(), KviWindow::maximize(), and KviWindow::restore().
Referenced by installAccelerators().
KviMdiManager* KviMainWindow::mdiManager () inline
Referenced by KviMenuBar::KviMenuBar(), KviThemedLineEdit::paintEvent(), KviThemedComboBox::paintEvent(), KviThemedLabel::paintEvent(), KviThemedTreeWidget::paintEvent(), FileTransferWidget::paintEvent(), KviToolBarGraphicalApplet::paintEvent(), UrlDialogTreeWidget::paintEvent(), KviIOGraphWindow::paintEvent(), KviIrcView::paintEvent(), KviUserListViewArea::paintEvent(), KviInputEditor::paintEvent(), and register_core_actions().
void KviMainWindow::minimizeWindow (void) protected slot
References g_pActiveWindow, and KviWindow::minimize().
Referenced by installAccelerators().
KviMexToolBar * KviMainWindow::moduleExtensionToolBar (int extensionId)
References KviPointerList< T >::first(), m_pModuleExtensionToolBarList, KviPointerList< T >::next(), and t().
Referenced by fillToolBarsPopup(), and toolbarsPopupSelected().
void KviMainWindow::moveEvent (QMoveEvent * e) protected virtual
References KVI_OPTION_RECT, KviOption_rectFrameGeometry, updatePseudoTransparency(), x, and y.
void KviMainWindow::newConsole () slot
References createNewConsole().
void KviMainWindow::recreateWindowList () protected
References createWindowList(), KviWindow::createWindowListItem(), KviWindow::destroyWindowListItem(), KviPointerList< T >::first(), g_pActiveWindow, m_pWindowList, m_pWinList, KviPointerList< T >::next(), KviWindowListBase::setActiveItem(), w, and KviWindow::windowListItem().
Referenced by KviApplication::optionResetUpdate().
void KviMainWindow::registerModuleExtensionToolBar (KviMexToolBar * t) protected
References KviPointerList< T >::append(), and m_pModuleExtensionToolBarList.
Referenced by KviMexToolBar::KviMexToolBar().
void KviMainWindow::resizeEvent (QResizeEvent * e) protected virtual
References KVI_OPTION_RECT, KviOption_rectFrameGeometry, x, and y.
void KviMainWindow::restoreModuleExtensionToolBars () protected
References KviModuleExtensionManager::allocateExtension(), firstConsole(), g_pModuleExtensionManager, KVI_OPTION_STRINGLIST, and KviOption_stringlistModuleExtensionToolbars.
Referenced by createNewConsole().
void KviMainWindow::restoreToolBarPositions () private
References KviApplication::Config, f, g_pApp, KviApplication::getLocalKvircDirectory(), KVI_CONFIGFILE_TOOLBARS, and m_pWindowList.
Referenced by createNewConsole().
void KviMainWindow::saveModuleExtensionToolBars () protected
References KviPointerList< T >::first(), KVI_OPTION_STRINGLIST, KviOption_stringlistModuleExtensionToolbars, m_pModuleExtensionToolBarList, KviPointerList< T >::next(), s, and t().
Referenced by ~KviMainWindow().
void KviMainWindow::saveToolBarPositions () private
References KviApplication::Config, f, g_pApp, KviApplication::getLocalKvircDirectory(), and KVI_CONFIGFILE_TOOLBARS.
Referenced by ~KviMainWindow().
void KviMainWindow::saveWindowProperties (KviWindow * wnd, const QString & szSection)
References KviConfigurationFile::clearGroup(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviConfigurationFile::groupsCount(), KviWindow::isDocked(), KviWindow::isMaximized(), KviWindow::mdiParent(), KviMdiChild::normalGeometry(), KviWindow::saveProperties(), KviConfigurationFile::setGroup(), and KviConfigurationFile::writeEntry().
Referenced by closeWindow(), and KviWindow::savePropertiesAsDefault().
void KviMainWindow::setActiveWindow (KviWindow * wnd)
References KviWindow::delayedAutoRaise(), KviWindow::isMinimized(), m_pMdi, KviWindow::mdiParent(), KviWindow::restore(), and KviMdiManager::showAndActivate().
Referenced by changeEvent(), KviIrcConnection::createChannel(), KviIrcConnection::createQuery(), KviWindow::dock(), KviKvsCoreSimpleCommands::KVSCSC(), NotifierWindowTab::mouseDoubleClickEvent(), KviIrcView::mouseDoubleClickEvent(), KviTreeWindowListTreeWidget::mousePressEvent(), KviWindowListButton::mousePressEvent(), UrlDialog::sayToWin(), and KviWindowListBase::switchWindow().
void KviMainWindow::setButtonStyle (unsigned int uStyle)
References KviPointerListIterator< T >::current(), KviPointerHashTableIterator< Key, T >::current(), d, KviCustomToolBarManager::instance(), KVI_OPTION_UINT, KviOption_uintToolBarButtonStyle, m_pModuleExtensionToolBarList, and t().
Referenced by buttonStylePopupSelected(), and KviMainWindow().
void KviMainWindow::setIconSize (unsigned int uSize)
References KviPointerListIterator< T >::current(), KviPointerHashTableIterator< Key, T >::current(), d, KviCustomToolBarManager::instance(), KVI_OPTION_UINT, KviOption_uintToolBarIconSize, m_pModuleExtensionToolBarList, and t().
Referenced by iconSizePopupSelected(), and KviMainWindow().
void KviMainWindow::setTrayIcon (KviTrayIcon * e) inline
References e, and m_pTrayIcon.
Referenced by KviTrayIconWidget::KviTrayIconWidget(), and KviTrayIconWidget::~KviTrayIconWidget().
void KviMainWindow::signalMaximizeMdiChildWindow (KviMdiChild * lpC) signal
QSplitter* KviMainWindow::splitter () inline
Referenced by CustomizeToolBarsDialog::display(), AddonManagementDialog::display(), ThemeManagementDialog::display(), help_kvs_cmd_open(), options_kvs_cmd_dialog(), reguser_kvs_cmd_edit(), and term_kvs_cmd_open().
void KviMainWindow::switchToNextHighlightedWindow (void) protected slot
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviMainWindow::switchToNextWindow (void) protected slot
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by KviMdiManager::eventFilter(), and installAccelerators().
void KviMainWindow::switchToNextWindowInContext (void) protected slot
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviMainWindow::switchToPrevHighlightedWindow (void) protected slot
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviMainWindow::switchToPrevWindow (void) protected slot
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by KviMdiManager::eventFilter(), and installAccelerators().
void KviMainWindow::switchToPrevWindowInContext (void) protected slot
References m_pWindowList, and KviWindowListBase::switchWindow().
Referenced by installAccelerators().
void KviMainWindow::toggleStatusBar () slot
References KviStatusBar::load(), and m_pStatusBar.
void KviMainWindow::toolbarsPopupSelected (QAction * pAction) protected slot
References KviModuleExtensionManager::allocateExtension(), KviCustomToolBarDescriptor::createToolBar(), KviCustomToolBarManager::findDescriptorByInternalId(), firstConsole(), g_pModuleExtensionManager, KviCustomToolBarManager::instance(), moduleExtensionToolBar(), t(), and KviCustomToolBarDescriptor::toolBar().
Referenced by fillToolBarsPopup().
KviTrayIcon* KviMainWindow::trayIcon () inline
References m_pTrayIcon.
Referenced by KviClassicWindowList::addItem(), KviIrcView::clearUnreaded(), closeEvent(), hideEvent(), KviTreeWindowListItem::highlight(), KviWindowListButton::highlight(), KviClassicWindowList::removeItem(), KviTreeWindowList::setActiveItem(), KviClassicWindowList::setActiveItem(), KviTreeWindowListItem::unhighlight(), and KviWindowListButton::unhighlight().
void KviMainWindow::undockWindow (KviWindow * wnd) protected
References KviMdiManager::destroyChild(), m_pMdi, KviWindow::mdiParent(), KviMdiChild::unsetClient(), and KviWindow::youAreUndocked().
Referenced by KviWindow::undock().
void KviMainWindow::unregisterModuleExtensionToolBar (KviMexToolBar * t) protected
References m_pModuleExtensionToolBarList, and KviPointerList< T >::removeRef().
Referenced by KviMexToolBar::~KviMexToolBar().
void KviMainWindow::updatePseudoTransparency () protected
References KviPointerList< T >::first(), KVI_OPTION_UINT, KviOption_uintGlobalWindowOpacityPercent, m_pMdi, m_pWindowList, m_pWinList, KviPointerList< T >::next(), and KviWindowListBase::updatePseudoTransparency().
Referenced by moveEvent(), and KviApplication::updatePseudoTransparency().
bool KviMainWindow::windowExists (KviWindow * wnd) inline
KviPointerList<KviWindow>* KviMainWindow::windowList () inline
Referenced by context_kvs_fnc_list(), KviKvsCoreSimpleCommands::KVSCSC(), and UrlDialog::popup().
KviWindowListBase* KviMainWindow::windowListWidget () inline
Referenced by KviTrayIconWidget::event(), and KviTrayIconWidget::grabActivityInfo().
Friends And Related Function Documentation
friend class KviApplication friend
friend class KviConsoleWindow friend
Referenced by createNewConsole().
friend class KviIrcConnection friend
friend class KviIrcContext friend
friend class KviIrcServerParser friend
Referenced by KviApplication::setup().
friend class KviLagMeter friend
friend class KviMdiManager friend
Referenced by KviMainWindow().
friend class KviMexToolBar friend
friend class KviUserListView friend
friend class KviUserListViewArea friend
friend class KviWindow friend
Member Data Documentation
KviPointerList<QShortcut>* KviMainWindow::m_pAccellerators protected
Referenced by freeAccelleratorKeySequence(), installAccelerators(), KviMainWindow(), and ~KviMainWindow().
KviIrcContext* KviMainWindow::m_pActiveContext protected
Referenced by activeConnection(), addWindow(), childConnectionAwayStateChange(), childConnectionLagChange(), childConnectionNickNameChange(), childConnectionServerInfoChange(), childConnectionUserModeChange(), childContextStateChange(), childWindowActivated(), closeWindow(), and KviMainWindow().
KviMdiManager* KviMainWindow::m_pMdi protected
Referenced by addWindow(), applyOptions(), closeWindow(), dockWindow(), KviMainWindow(), setActiveWindow(), undockWindow(), updatePseudoTransparency(), and ~KviMainWindow().
KviMenuBar* KviMainWindow::m_pMenuBar protected
Referenced by KviMainWindow().
KviPointerList<KviMexToolBar>* KviMainWindow::m_pModuleExtensionToolBarList protected
Referenced by KviMainWindow(), moduleExtensionToolBar(), registerModuleExtensionToolBar(), saveModuleExtensionToolBars(), setButtonStyle(), setIconSize(), unregisterModuleExtensionToolBar(), and ~KviMainWindow().
QSplitter* KviMainWindow::m_pSplitter protected
Referenced by KviMainWindow().
KviStatusBar* KviMainWindow::m_pStatusBar protected
Referenced by KviMainWindow(), toggleStatusBar(), and ~KviMainWindow().
KviTrayIcon* KviMainWindow::m_pTrayIcon protected
Referenced by KviMainWindow(), and ~KviMainWindow().
KviWindowListBase* KviMainWindow::m_pWindowList protected
Referenced by applyOptions(), childWindowActivated(), createWindowList(), KviWindow::createWindowListItem(), KviWindow::destroyWindowListItem(), KviMainWindow(), recreateWindowList(), restoreToolBarPositions(), switchToNextHighlightedWindow(), switchToNextWindow(), switchToNextWindowInContext(), switchToPrevHighlightedWindow(), switchToPrevWindow(), switchToPrevWindowInContext(), and updatePseudoTransparency().
KviPointerList<KviWindow>* KviMainWindow::m_pWinList protected
Referenced by addWindow(), applyOptions(), closeEvent(), closeWindow(), consoleCount(), firstConsole(), firstNotConnectedConsole(), KviMainWindow(), recreateWindowList(), updatePseudoTransparency(), and ~KviMainWindow().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviMainWindow.h
src/kvirc/ui/KviMainWindow.cpp