KVIrc: KviThread Class Reference
KviThread Class Reference
#include <KviThread.h>
Public Member Functions
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Static Public Member Functions
static void msleep (unsigned long msec)
static void sleep (unsigned long sec)
static void usleep (unsigned long usec)
Protected Member Functions
void exit ()
void postEvent (QObject *o, QEvent *e)
virtual void run ()
Private Member Functions
void setRunning (bool bRunning)
void setStartingUp (bool bStartingUp)
Private Attributes
bool m_bRunning
bool m_bStartingUp
KviPointerList< QEvent > * m_pLocalEventQueue
KviMutex * m_pRunningMutex
kvi_thread_t m_thread
Constructor & Destructor Documentation
KviThread::KviThread ()
References m_pRunningMutex, KviThreadManager::registerSlaveThread(), setRunning(), and setStartingUp().
KviThread::~KviThread () [virtual]
References m_pRunningMutex, KviThreadManager::unregisterSlaveThread(), and wait().
Member Function Documentation
void KviThread::exit () [protected]
References setRunning().
void KviThread::internalThreadRun_doNotTouchThis ()
References kvi_threadInitialize(), run(), setRunning(), and setStartingUp().
bool KviThread::isRunning ()
References KviMutex::lock(), m_bRunning, m_pRunningMutex, and KviMutex::unlock().
Referenced by start(), startIdentService(), and wait().
bool KviThread::isStartingUp ()
References KviMutex::lock(), m_bStartingUp, m_pRunningMutex, and KviMutex::unlock().
Referenced by start(), startIdentService(), and wait().
void KviThread::msleep (unsigned long msec) [static]
References usleep().
Referenced by KviIdentDaemon::run(), DccSendThread::run(), DccRecvThread::run(), DccChatThread::run(), DccRecvThread::sendAck(), and KviIrcContext::terminateConnectionRequest().
void KviThread::postEvent (QObject * o, QEvent * e) [protected]
References KviThreadManager::postSlaveEvent().
Referenced by DccVideoThread::handleIncomingData(), DccChatThread::handleIncomingData(), DccThread::postErrorEvent(), KviIdentDaemon::postMessage(), DccThread::postMessageEvent(), DccRecvThread::postMessageEvent(), KviSoundThread::run(), KviIdentDaemon::run(), DccSendThread::run(), DccRecvThread::run(), DccVoiceThread::startPlaying(), DccVideoThread::startPlaying(), DccVoiceThread::startRecording(), DccVideoThread::startRecording(), DccVoiceThread::stopPlaying(), DccVideoThread::stopPlaying(), DccVoiceThread::stopRecording(), and DccVideoThread::stopRecording().
virtual void KviThread::run () [inline, protected, virtual]
Reimplemented in DccChatThread, DccSendThread, DccRecvThread, DccVideoThread, DccVoiceThread, KviIdentDaemon, and KviSoundThread.
Referenced by internalThreadRun_doNotTouchThis().
void KviThread::setRunning (bool bRunning) [private]
References KviMutex::lock(), m_bRunning, m_pRunningMutex, and KviMutex::unlock().
Referenced by exit(), internalThreadRun_doNotTouchThis(), and KviThread().
void KviThread::setStartingUp (bool bStartingUp) [private]
References KviMutex::lock(), m_bStartingUp, m_pRunningMutex, and KviMutex::unlock().
Referenced by internalThreadRun_doNotTouchThis(), KviThread(), and start().
void KviThread::sleep (unsigned long sec) [static]
bool KviThread::start ()
References internal_start_thread(), isRunning(), isStartingUp(), m_thread, and setStartingUp().
Referenced by DccVoiceWindow::connected(), DccFileTransfer::connected(), DccChatWindow::connected(), and startIdentService().
void KviThread::usleep (unsigned long usec) [static]
References s.
Referenced by msleep(), DccVideoThread::run(), and wait().
void KviThread::wait ()
References isRunning(), isStartingUp(), KviThreadManager::threadEnteredWaitState(), KviThreadManager::threadLeftWaitState(), and usleep().
Referenced by KviSensitiveThread::terminate(), and ~KviThread().
Member Data Documentation
bool KviThread::m_bRunning [private]
Referenced by isRunning(), and setRunning().
bool KviThread::m_bStartingUp [private]
Referenced by isStartingUp(), and setStartingUp().
KviPointerList<QEvent>* KviThread::m_pLocalEventQueue [private]
Reimplemented in KviSensitiveThread.
KviMutex* KviThread::m_pRunningMutex [private]
Referenced by isRunning(), isStartingUp(), KviThread(), setRunning(), setStartingUp(), and ~KviThread().
kvi_thread_t KviThread::m_thread [private]
Referenced by start().
The documentation for this class was generated from the following files:
src/kvilib/system/KviThread.h
src/kvilib/system/KviThread.cpp