KVIrc: OptionsWidget_dccGeneral Class Reference
OptionsWidget_dccGeneral Class Reference
#include <OptionsWidget_dcc.h>
Public Member Functions
OptionsWidget_dccGeneral (QWidget *parent)
~OptionsWidget_dccGeneral ()
Constructor & Destructor Documentation
OptionsWidget_dccGeneral::OptionsWidget_dccGeneral (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::createLayout(), KviOption_boolCantAcceptIncomingDccConnections, and KviOptionsWidget::mergeTip().
OptionsWidget_dccGeneral::~OptionsWidget_dccGeneral ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_dcc.h
src/modules/options/OptionsWidget_dcc.cpp