KVIrc: KviKvsModuleFunctionCall Class Reference
KviKvsModuleFunctionCall Class Reference
#include <KviKvsModuleInterface.h>
Public Member Functions
KviKvsModuleFunctionCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams, KviKvsVariant *pResult)
KviKvsVariant * returnValue ()
~KviKvsModuleFunctionCall ()
Protected Attributes
KviKvsVariant * m_pResult
Friends
class KviKvsTreeNodeModuleFunctionCall
Constructor & Destructor Documentation
KviKvsModuleFunctionCall::KviKvsModuleFunctionCall (KviModule * pModule, KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams, KviKvsVariant * pResult) [inline]
KviKvsModuleFunctionCall::~KviKvsModuleFunctionCall () [inline]
Member Function Documentation
KviKvsVariant* KviKvsModuleFunctionCall::returnValue () [inline]
Referenced by action_kvs_fnc_exists(), action_kvs_fnc_isEnabled(), addon_kvs_fnc_exists(), addon_kvs_fnc_version(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), chan_kvs_fnc_admincount(), chan_kvs_fnc_bancount(), chan_kvs_fnc_banexceptioncount(), chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_common(), chan_kvs_fnc_getflag(), chan_kvs_fnc_getUrl(), chan_kvs_fnc_halfopcount(), chan_kvs_fnc_invitecount(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_isdead(), chan_kvs_fnc_ison(), chan_kvs_fnc_key(), chan_kvs_fnc_limit(), chan_kvs_fnc_maskcount(), chan_kvs_fnc_masklist(), chan_kvs_fnc_matchban(), chan_kvs_fnc_matchbanexception(), chan_kvs_fnc_matchinvite(), chan_kvs_fnc_matchmask(), chan_kvs_fnc_matchqban(), chan_kvs_fnc_modeParam(), chan_kvs_fnc_name(), chan_kvs_fnc_opcount(), chan_kvs_fnc_ownercount(), chan_kvs_fnc_topic(), chan_kvs_fnc_topicsetat(), chan_kvs_fnc_topicsetby(), chan_kvs_fnc_usercount(), chan_kvs_fnc_userjointime(), chan_kvs_fnc_userlastactiontime(), chan_kvs_fnc_usermodelevel(), chan_kvs_fnc_useropcount(), chan_kvs_fnc_users(), chan_kvs_fnc_voicecount(), config_kvs_fnc_filelist(), config_kvs_fnc_filename(), config_kvs_fnc_hassection(), config_kvs_fnc_id(), config_kvs_fnc_keylist(), config_kvs_fnc_open(), config_kvs_fnc_read(), config_kvs_fnc_readonly(), config_kvs_fnc_section(), config_kvs_fnc_sectionlist(), context_kvs_fnc_getSSLCertInfo(), context_kvs_fnc_list(), context_kvs_fnc_queueSize(), dcc_kvs_fnc_averageSpeed(), dcc_kvs_fnc_connectionType(), dcc_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_ircContext(), dcc_kvs_fnc_isFileDownload(), dcc_kvs_fnc_isFileTransfer(), dcc_kvs_fnc_isFileUpload(), dcc_kvs_fnc_localFileName(), dcc_kvs_fnc_localFileSize(), dcc_kvs_fnc_localHost(), dcc_kvs_fnc_localIp(), dcc_kvs_fnc_localNick(), dcc_kvs_fnc_localPort(), dcc_kvs_fnc_localUser(), dcc_kvs_fnc_protocol(), dcc_kvs_fnc_remoteFileName(), dcc_kvs_fnc_remoteFileSize(), dcc_kvs_fnc_remoteHost(), dcc_kvs_fnc_remoteIp(), dcc_kvs_fnc_remoteNick(), dcc_kvs_fnc_remotePort(), dcc_kvs_fnc_remoteUser(), dcc_kvs_fnc_session(), dcc_kvs_fnc_sessionList(), dcc_kvs_fnc_transferredBytes(), dcc_kvs_fnc_transferStatus(), dialog_kvs_fnc_yesno(), file_kvs_fnc_allSizes(), file_kvs_fnc_cwd(), file_kvs_fnc_digest(), file_kvs_fnc_diskSpace(), file_kvs_fnc_exists(), file_kvs_fnc_extractfilename(), file_kvs_fnc_extractpath(), file_kvs_fnc_fixpath(), file_kvs_fnc_globaldir(), file_kvs_fnc_homedir(), file_kvs_fnc_localdir(), file_kvs_fnc_ls(), file_kvs_fnc_ps(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), file_kvs_fnc_rootdir(), file_kvs_fnc_size(), file_kvs_fnc_type(), language_kvs_cmd_detect(), log_kvs_fnc_export(), log_kvs_fnc_file(), mask_kvs_fnc_hasnumerichost(), mask_kvs_fnc_host(), mask_kvs_fnc_match(), mask_kvs_fnc_nick(), mask_kvs_fnc_user(), math_kvs_fnc_e(), math_kvs_fnc_isinf(), math_kvs_fnc_pi(), math_kvs_fnc_pow(), my_kvs_fnc_globalIdle(), my_kvs_fnc_host(), my_kvs_fnc_ip(), my_kvs_fnc_network(), my_kvs_fnc_nick(), my_kvs_fnc_server(), my_kvs_fnc_serverIsIPV6(), my_kvs_fnc_serverIsSSL(), my_kvs_fnc_umode(), my_kvs_fnc_user(), notifier_kvs_fnc_isEnabled(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_classes(), objects_kvs_fnc_exists(), objects_kvs_fnc_instances(), objects_kvs_fnc_listObjects(), objects_kvs_fnc_name(), objects_kvs_fnc_variables(), options_kvs_fnc_isdialog(), perl_kvs_fnc_isAvailable(), PluginManager::pluginCall(), popup_kvs_fnc_currentItemId(), popup_kvs_fnc_exists(), popup_kvs_fnc_isEmpty(), proxydb_kvs_fnc_protocol(), python_kvs_fnc_isAvailable(), regchan_kvs_fnc_find(), regchan_kvs_fnc_list(), regchan_kvs_fnc_match(), regchan_kvs_fnc_property(), reguser_kvs_fnc_exactMatch(), reguser_kvs_fnc_getIgnoreFlags(), reguser_kvs_fnc_isIgnoreEnabled(), reguser_kvs_fnc_list(), reguser_kvs_fnc_mask(), reguser_kvs_fnc_match(), reguser_kvs_fnc_matchProperty(), reguser_kvs_fnc_property(), serverdb_kvs_fnc_networkExists(), serverdb_kvs_fnc_serverExists(), snd_kvs_fnc_ismuted(), str_kvs_fnc_append(), str_kvs_fnc_charsum(), str_kvs_fnc_chop(), str_kvs_fnc_cmp(), str_kvs_fnc_contains(), str_kvs_fnc_digest(), str_kvs_fnc_equal(), str_kvs_fnc_evpSign(), str_kvs_fnc_evpVerify(), str_kvs_fnc_find(), str_kvs_fnc_findfirst(), str_kvs_fnc_findlast(), str_kvs_fnc_fromclipboard(), str_kvs_fnc_grep(), str_kvs_fnc_insert(), str_kvs_fnc_isempty(), str_kvs_fnc_isnumber(), str_kvs_fnc_isunsignednumber(), str_kvs_fnc_join(), str_kvs_fnc_left(), str_kvs_fnc_lefttofirst(), str_kvs_fnc_lefttolast(), str_kvs_fnc_len(), str_kvs_fnc_localelowcase(), str_kvs_fnc_localeupcase(), str_kvs_fnc_lowcase(), str_kvs_fnc_match(), str_kvs_fnc_mid(), str_kvs_fnc_prepend(), str_kvs_fnc_printf(), str_kvs_fnc_replace(), str_kvs_fnc_right(), str_kvs_fnc_rightfromfirst(), str_kvs_fnc_rightfromlast(), str_kvs_fnc_section(), str_kvs_fnc_split(), str_kvs_fnc_strip(), str_kvs_fnc_stripcolors(), str_kvs_fnc_stripleft(), str_kvs_fnc_stripright(), str_kvs_fnc_token(), str_kvs_fnc_upcase(), str_kvs_fnc_urlencode(), str_kvs_fnc_word(), system_kvs_fnc_checkModule(), system_kvs_fnc_clipboard(), system_kvs_fnc_dbus(), system_kvs_fnc_getenv(), system_kvs_fnc_hostname(), system_kvs_fnc_osmachine(), system_kvs_fnc_osname(), system_kvs_fnc_osnodename(), system_kvs_fnc_osrelease(), system_kvs_fnc_ostype(), system_kvs_fnc_osversion(), system_kvs_fnc_selection(), texticons_kvs_fnc_get(), theme_kvs_fnc_info(), theme_kvs_fnc_list(), tmphighlight_kvs_fnc_ischannelhighlighted(), tmphighlight_kvs_fnc_isnickhighlighted(), toolbar_kvs_fnc_exists(), toolbar_kvs_fnc_isVisible(), toolbar_kvs_fnc_items(), toolbar_kvs_fnc_list(), trayicon_kvs_fnc_isvisible(), upnp_kvs_fnc_getExternalIpAddress(), upnp_kvs_fnc_isGatewayAvailable(), userlist_kvs_fnc_selected(), window_kvs_fnc_activityLevel(), window_kvs_fnc_activityTemperature(), window_kvs_fnc_caption(), window_kvs_fnc_console(), window_kvs_fnc_context(), window_kvs_fnc_exists(), window_kvs_fnc_hasInput(), window_kvs_fnc_hasOutput(), window_kvs_fnc_hasUserFocus(), window_kvs_fnc_highlightLevel(), window_kvs_fnc_inputText(), window_kvs_fnc_isDocked(), window_kvs_fnc_isMaximized(), window_kvs_fnc_isMinimized(), window_kvs_fnc_list(), window_kvs_fnc_open(), and window_kvs_fnc_type().
Friends And Related Function Documentation
friend class KviKvsTreeNodeModuleFunctionCall [friend]
Member Data Documentation
KviKvsVariant* KviKvsModuleFunctionCall::m_pResult [protected]
The documentation for this class was generated from the following file:
src/kvirc/kvs/KviKvsModuleInterface.h