KVIrc: KviIrcUserDataBase Class Reference
KviIrcUserDataBase Class Reference
The class which manages the user database.
#include <kvi_ircuserdb.h>
Public Member Functions
void clear ()
Clears the database.
QColor * customColor (const QString &nick)
Returns the custom color of the user.
KviPointerHashTable< QString,
KviIrcUserEntry > * dict ()
Returns the database dictionary.
KviIrcUserEntry * find (const QString &nick)
Searches for a user in the database.
bool haveCustomColor (const QString &nick)
Returns true if the user has custom colors set.
KviIrcUserEntry * insertUser (const QString &nick, const QString &user, const QString &hostname)
Adds the user to the database.
KviIrcUserDataBase ()
Constructs the Irc user database object.
KviRegisteredUser * registeredUser (const QString &nick)
Returns the registered user, if any, or 0.
KviRegisteredUser * registeredUser (const QString &nick, const QString &user, const QString &host)
Returns the registered user, if any, or 0.
bool removeUser (const QString &nick, KviIrcUserEntry *e)
Decrements the user reference count and if it reaches 0 then deletes the user from the database.
void setupConnectionWithReguserDb ()
Initialize the database by connecting signals and slots.
~KviIrcUserDataBase ()
Destoys the object.
Protected Slots
void registeredDatabaseCleared ()
Slot called when the database is cleared.
void registeredUserAdded (const QString &szUser)
Slot called when a registered user is added.
void registeredUserChanged (const QString &szUser)
Slot called when a registered user is changed.
void registeredUserRemoved (const QString &szUser)
Slot called when a registered user is removed.
Private Attributes
KviPointerHashTable< QString,
KviIrcUserEntry > * m_pDict
Detailed Description
The class which manages the user database.
Constructor & Destructor Documentation
KviIrcUserDataBase::KviIrcUserDataBase ()
Constructs the Irc user database object.
Returns:
KviIrcUserDataBase
References m_pDict, KviPointerHashTable< Key, T >::setAutoDelete(), and setupConnectionWithReguserDb().
KviIrcUserDataBase::~KviIrcUserDataBase ()
Destoys the object.
References m_pDict.
Member Function Documentation
void KviIrcUserDataBase::clear ()
Clears the database.
Returns:
void
References m_pDict, and KviPointerHashTable< Key, T >::setAutoDelete().
QColor * KviIrcUserDataBase::customColor (const QString & nick)
Returns the custom color of the user.
Parameters:
nick The nickname of the user
Returns:
QColor *
References find(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, KviIrcUserEntry::m_cachedColor, KviIrcUserEntry::m_szLastRegisteredMatchNick, and registeredUser().
Referenced by KviUserListEntry::color(), and KviUserListViewArea::paintEvent().
KviPointerHashTable<QString,KviIrcUserEntry>* KviIrcUserDataBase::dict () [inline]
Returns the database dictionary.
Returns:
KviPointerHashTable<QString,KviIrcUserEntry> *
KviIrcUserEntry* KviIrcUserDataBase::find (const QString & nick) [inline]
Searches for a user in the database.
Parameters:
nick The nickname of the user to find
Returns:
KviIrcUserEntry *
Referenced by KviConsole::currentAvatar(), customColor(), KviIrcView::doLinkToolTip(), KviQuery::getInfoLabelText(), KviQuery::getInfoLabelTipText(), KviIsOnNotifyListManager::handleIsOn(), haveCustomColor(), KviKvsCoreSimpleCommands::KVSCSC(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviConsole::outputPrivmsg(), KviServerParser::parseCtcpReplyAvatar(), KviServerParser::parseCtcpReplyUserinfo(), KviServerParser::parseLiteralKick(), KviServerParser::parseLiteralNick(), KviServerParser::parseNumericWhoisAway(), KviServerParser::parseNumericWhoisServer(), KviServerParser::parseNumericWhoisUser(), KviServerParser::parseNumericWhoReply(), registeredUser(), KviConsole::setAvatar(), KviConsole::setAvatarFromOptions(), and KviIrcConnection::userInfoReceived().
bool KviIrcUserDataBase::haveCustomColor (const QString & nick)
Returns true if the user has custom colors set.
Parameters:
nick The nickname of the user
Returns:
bool
References find(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, KviIrcUserEntry::m_bUseCustomColor, KviIrcUserEntry::m_szLastRegisteredMatchNick, and registeredUser().
Referenced by KviUserListEntry::color(), and KviUserListViewArea::paintEvent().
KviIrcUserEntry * KviIrcUserDataBase::insertUser (const QString & nick, const QString & user, const QString & hostname)
Adds the user to the database.
Parameters:
nick The nickname of the user
user The username of the user
hostname The hostname of the user
Returns:
KviIrcUserEntry *
References KviPointerHashTable< Key, T >::find(), KviOsInfo::hostname(), KviPointerHashTable< Key, T >::insert(), KviIrcUserEntry::m_nRefs, m_pDict, KviIrcUserEntry::m_szHost, and KviIrcUserEntry::m_szUser.
Referenced by KviUserListView::join().
void KviIrcUserDataBase::registeredDatabaseCleared () [protected, slot]
Slot called when the database is cleared.
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, m_pDict, and KviIrcUserEntry::m_szRegisteredUserName.
Referenced by setupConnectionWithReguserDb().
KviRegisteredUser * KviIrcUserDataBase::registeredUser (const QString & nick, const QString & user, const QString & host)
Returns the registered user, if any, or 0.
Parameters:
nick The nickname of the user
user The username of the user
host The hostname of the user
Returns:
KviRegisteredUser *
References find(), KviRegisteredUserDataBase::findMatchingUser(), KviStringConversion::fromString(), g_pRegisteredUserDataBase, KviRegisteredUser::getBoolProperty(), KviRegisteredUser::getProperty(), KviRegisteredUserDataBase::getUser(), KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasUser(), KviIrcUserEntry::host(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, KviIrcUserEntry::m_bUseCustomColor, KviIrcUserEntry::m_cachedColor, KviIrcUserEntry::m_szLastRegisteredMatchNick, KviIrcUserEntry::m_szRegisteredUserName, KviRegisteredUser::name(), and KviIrcUserEntry::user().
KviRegisteredUser * KviIrcUserDataBase::registeredUser (const QString & nick)
Returns the registered user, if any, or 0.
Parameters:
nick The nickname of the user
Returns:
KviRegisteredUser *
References find(), KviIrcUserEntry::host(), and KviIrcUserEntry::user().
Referenced by KviConsole::applyHighlighting(), KviConsole::avatarChanged(), KviConsole::checkDefaultAvatar(), KviUserListEntry::color(), customColor(), haveCustomColor(), KviServerParser::parseCtcpRequest(), KviServerParser::parseCtcpRequestDcc(), KviServerParser::parseLiteralInvite(), KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
void KviIrcUserDataBase::registeredUserAdded (const QString & szUser) [protected, slot]
Slot called when a registered user is added.
Parameters:
szUser The user added
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, m_pDict, and KviIrcUserEntry::m_szRegisteredUserName.
Referenced by setupConnectionWithReguserDb().
void KviIrcUserDataBase::registeredUserChanged (const QString & szUser) [protected, slot]
Slot called when a registered user is changed.
Parameters:
szUser The user changed
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, m_pDict, and KviIrcUserEntry::m_szRegisteredUserName.
Referenced by setupConnectionWithReguserDb().
void KviIrcUserDataBase::registeredUserRemoved (const QString & szUser) [protected, slot]
Slot called when a registered user is removed.
Parameters:
szUser The user removed
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), KviIrcUserEntry::m_bNotFoundRegUserLoockup, m_pDict, and KviIrcUserEntry::m_szRegisteredUserName.
Referenced by setupConnectionWithReguserDb().
bool KviIrcUserDataBase::removeUser (const QString & nick, KviIrcUserEntry * e)
Decrements the user reference count and if it reaches 0 then deletes the user from the database.
Parameters:
nick The nickname of the user
e The entry of the user
Returns:
true if the reference count reached 0 and false otherwise (so true if the user was completely deleted from the db)
References KviIrcUserEntry::m_nRefs, m_pDict, and KviPointerHashTable< Key, T >::remove().
Referenced by KviUserListView::partInternal(), and KviUserListView::removeAllEntries().
void KviIrcUserDataBase::setupConnectionWithReguserDb ()
Initialize the database by connecting signals and slots.
Returns:
void
References g_pRegisteredUserDataBase, registeredDatabaseCleared(), registeredUserAdded(), registeredUserChanged(), and registeredUserRemoved().
Referenced by KviIrcUserDataBase().
Member Data Documentation
KviPointerHashTable<QString,KviIrcUserEntry>* KviIrcUserDataBase::m_pDict [private]
Referenced by clear(), insertUser(), KviIrcUserDataBase(), registeredDatabaseCleared(), registeredUserAdded(), registeredUserChanged(), registeredUserRemoved(), removeUser(), and ~KviIrcUserDataBase().
The documentation for this class was generated from the following files:
src/kvilib/irc/kvi_ircuserdb.h
src/kvilib/irc/kvi_ircuserdb.cpp