KVIrc: OptionsDialog Class Reference
OptionsDialog Class Reference
#include <OptionsDialog.h>
Public Member Functions
OptionsDialog (QWidget *par, const QString &szGroup)
void search (const QStringList &lKeywords)
void search (const QString &szKeywords)
~OptionsDialog ()
Protected Member Functions
void apply (bool bDialogAboutToClose)
virtual void closeEvent (QCloseEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
bool recursiveSearch (OptionsDialogTreeWidgetItem *pItem, const QStringList &lKeywords)
bool searchInSelectors (KviOptionsWidget *pWidget, const QStringList &lKeywords)
virtual void showEvent (QShowEvent *e)
Private Slots
void applyClicked ()
void cancelClicked ()
void okClicked ()
void pageWantsToSwitchToAdvancedPage (KviOptionsWidget *pPage)
void searchClicked ()
void searchLineEditTextChanged (const QString &)
void treeWidgetItemSelectionChanged (QTreeWidgetItem *it, QTreeWidgetItem *prev)
Private Member Functions
void fillTreeWidget (QTreeWidgetItem *p, KviPointerList< OptionsWidgetInstanceEntry > *l, const QString &szGroup, bool bNotContainedOnly=false)
void recursiveCommit (OptionsDialogTreeWidgetItem *it)
Private Attributes
QLabel * m_pCategoryLabel
OptionsDialogFrontWidget * m_pFrontWidget
QToolButton * m_pSearchButton
QLineEdit * m_pSearchLineEdit
QTreeWidget * m_pTreeWidget
QStackedWidget * m_pWidgetStack
QString m_szGroup
Constructor & Destructor Documentation
OptionsDialog::OptionsDialog (QWidget * par, const QString & szGroup)
References __tr2qs_ctx(), KviIconManager::Accept, KviTalToolTip::add(), applyClicked(), cancelClicked(), connect(), KviIconManager::Discard, KviQString::equalCI(), f, fillTreeWidget(), g_pIconManager, KviIconManager::getSmallIcon(), OptionsInstanceManager::instanceEntryTree(), KVI_OPTION_RECT, KviOption_rectGeneralOptionsDialogGeometry, KviIconManager::KVIrc, m_pCategoryLabel, m_pFrontWidget, m_pSearchButton, m_pSearchLineEdit, m_pTreeWidget, m_pWidgetStack, m_szGroup, KviMemory::move(), okClicked(), KviIconManager::Search, searchClicked(), searchLineEditTextChanged(), KviTalHBox::setMargin(), KviTalVBox::setMargin(), KviTalHBox::setSpacing(), KviTalVBox::setSpacing(), KviTalVBox::setStretchFactor(), spl, treeWidgetItemSelectionChanged(), x, and y.
OptionsDialog::~OptionsDialog ()
References KVI_OPTION_RECT, KviOption_rectGeneralOptionsDialogGeometry, m_szGroup, KviPointerHashTable< Key, T >::remove(), x, and y.
Member Function Documentation
void OptionsDialog::apply (bool bDialogAboutToClose) [protected]
References g_pApp, i, OptionsDialogTreeWidgetItem::m_pOptionsWidget, m_pTreeWidget, recursiveCommit(), KviApplication::saveConfiguration(), KviOptionsWidget::tabWidget(), and treeWidgetItemSelectionChanged().
Referenced by applyClicked(), and okClicked().
void OptionsDialog::applyClicked () [private, slot]
References apply().
Referenced by OptionsDialog().
void OptionsDialog::cancelClicked () [private, slot]
Referenced by OptionsDialog().
void OptionsDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void OptionsDialog::fillTreeWidget (QTreeWidgetItem * p, KviPointerList< OptionsWidgetInstanceEntry > * l, const QString & szGroup, bool bNotContainedOnly = false) [private]
References _OptionsWidgetInstanceEntry::bDoInsert, _OptionsWidgetInstanceEntry::bIsContainer, _OptionsWidgetInstanceEntry::bIsNotContained, e, KviQString::equalCI(), KviPointerList< T >::first(), OptionsInstanceManager::getInstance(), KviPointerList< T >::insert(), _OptionsWidgetInstanceEntry::iPriority, OptionsDialogTreeWidgetItem::m_pInstanceEntry, OptionsDialogTreeWidgetItem::m_pOptionsWidget, m_pTreeWidget, m_pWidgetStack, KviPointerList< T >::next(), _OptionsWidgetInstanceEntry::pChildList, KviPointerList< T >::setAutoDelete(), and _OptionsWidgetInstanceEntry::szGroup.
Referenced by OptionsDialog().
void OptionsDialog::keyPressEvent (QKeyEvent * e) [protected, virtual]
void OptionsDialog::okClicked () [private, slot]
References apply().
Referenced by OptionsDialog().
void OptionsDialog::pageWantsToSwitchToAdvancedPage (KviOptionsWidget * pPage) [private, slot]
void OptionsDialog::recursiveCommit (OptionsDialogTreeWidgetItem * it) [private]
References KviOptionsWidget::commit(), i, and OptionsDialogTreeWidgetItem::m_pOptionsWidget.
Referenced by apply().
bool OptionsDialog::recursiveSearch (OptionsDialogTreeWidgetItem * pItem, const QStringList & lKeywords) [protected]
References KviQString::equalCIN(), OptionsInstanceManager::getInstance(), i, j, OptionsDialogTreeWidgetItem::m_pInstanceEntry, OptionsDialogTreeWidgetItem::m_pOptionsWidget, m_pWidgetStack, searchInSelectors(), _OptionsWidgetInstanceEntry::szKeywords, and KviOptionsWidget::tabWidget().
Referenced by search().
void OptionsDialog::search (const QString & szKeywords)
Referenced by searchClicked().
void OptionsDialog::search (const QStringList & lKeywords)
References i, m_pTreeWidget, and recursiveSearch().
void OptionsDialog::searchClicked () [private, slot]
References m_pSearchLineEdit, and search().
Referenced by OptionsDialog().
bool OptionsDialog::searchInSelectors (KviOptionsWidget * pWidget, const QStringList & lKeywords) [protected]
References KviPointerList< T >::at(), KviPointerList< T >::count(), i, j, KviOptionsWidget::selectors(), KviSelectorInterface::textForSearch(), and KviSelectorInterface::widgetToHighlight().
Referenced by recursiveSearch().
void OptionsDialog::searchLineEditTextChanged (const QString &) [private, slot]
References m_pSearchButton, and m_pSearchLineEdit.
Referenced by OptionsDialog().
void OptionsDialog::showEvent (QShowEvent * e) [protected, virtual]
References g_pApp, g_pMainWindow, h, r, and w.
void OptionsDialog::treeWidgetItemSelectionChanged (QTreeWidgetItem * it, QTreeWidgetItem * prev) [private, slot]
References OptionsInstanceManager::getInstance(), i, m_pCategoryLabel, OptionsDialogTreeWidgetItem::m_pInstanceEntry, OptionsDialogTreeWidgetItem::m_pOptionsWidget, and m_pWidgetStack.
Referenced by apply(), and OptionsDialog().
Member Data Documentation
QLabel* OptionsDialog::m_pCategoryLabel [private]
Referenced by OptionsDialog(), and treeWidgetItemSelectionChanged().
OptionsDialogFrontWidget* OptionsDialog::m_pFrontWidget [private]
Referenced by OptionsDialog().
QToolButton* OptionsDialog::m_pSearchButton [private]
Referenced by OptionsDialog(), and searchLineEditTextChanged().
QLineEdit* OptionsDialog::m_pSearchLineEdit [private]
Referenced by OptionsDialog(), searchClicked(), and searchLineEditTextChanged().
QTreeWidget* OptionsDialog::m_pTreeWidget [private]
Referenced by apply(), fillTreeWidget(), OptionsDialog(), and search().
QStackedWidget* OptionsDialog::m_pWidgetStack [private]
Referenced by fillTreeWidget(), OptionsDialog(), recursiveSearch(), and treeWidgetItemSelectionChanged().
QString OptionsDialog::m_szGroup [private]
Referenced by OptionsDialog(), and ~OptionsDialog().
The documentation for this class was generated from the following files:
src/modules/options/OptionsDialog.h
src/modules/options/OptionsDialog.cpp