KVIrc: KviTheoraDecoder Class Reference
KviTheoraDecoder Class Reference
An ogg/theora+irct decoder class; accepts a proper ogg stream, outputs argb32 images and binary text.
#include <kvi_oggtheora.h>
Public Member Functions
void addData (KviDataBuffer *stream)
Feeds the decoded with some received data to decode.
KviTheoraDecoder (KviDataBuffer *videoSignal, KviDataBuffer *textSignal)
Constructs the KviTheoraDecoder object.
virtual ~KviTheoraDecoder ()
Destroys the KviTheoraEncoder object.
Private Member Functions
int queue_page (ogg_page *page)
Internal function that queues an ogg page to the codec decoders.
void video_write (void)
Internal function that takes a theora yuv buffer, transforms it and appends to the video stream.
Private Attributes
KviTheoraGeometry geometry
int irct_p
int lu_B [256]
int lu_GU [256]
int lu_GV [256]
int lu_R [256]
int lu_Y [256]
KviDataBuffer * m_pTextSignal
KviDataBuffer * m_pVideoSignal
ogg_page og
ogg_packet op
ogg_sync_state oy
int pp_inc
int pp_level
int pp_level_max
th_pixel_fmt px_fmt
unsigned char * RGBbuffer
int stateflag
th_comment tc
th_dec_ctx * td
bool thda
int theora_p
bool thtic
th_info ti
ogg_stream_state to
th_setup_info * ts
ogg_int64_t videobuf_granulepos
int videobuf_ready
double videobuf_time
ogg_stream_state zo
Detailed Description
An ogg/theora+irct decoder class; accepts a proper ogg stream, outputs argb32 images and binary text.
Constructor & Destructor Documentation
KviTheoraDecoder::KviTheoraDecoder (KviDataBuffer * videoSignal, KviDataBuffer * textSignal)
Constructs the KviTheoraDecoder object.
Parameters:
videoSignal the output video stream object
textSignal the output text stream object
Returns:
KviTheoraDecoder
References NULL.
KviTheoraDecoder::~KviTheoraDecoder () [virtual]
Destroys the KviTheoraEncoder object.
References KviOggIrcText::irct_encode_clear().
Member Function Documentation
void KviTheoraDecoder::addData (KviDataBuffer * stream)
Feeds the decoded with some received data to decode.
Parameters:
stream the databuffer containing the received data
Returns:
void
References KviDataBuffer::clear(), KviDataBuffer::data(), KviOggIrcText::irct_decode_headerin(), KviOggIrcText::irct_decode_packetin(), and KviDataBuffer::size().
int KviTheoraDecoder::queue_page (ogg_page * page) [private]
Internal function that queues an ogg page to the codec decoders.
Returns:
int
void KviTheoraDecoder::video_write (void) [private]
Internal function that takes a theora yuv buffer, transforms it and appends to the video stream.
Returns:
int
References ARGB32_BPP, and OC_CLAMP255.
Member Data Documentation
KviTheoraGeometry KviTheoraDecoder::geometry [private]
Stream geometry definition
int KviTheoraDecoder::irct_p [private]
True if the ogg stream contains an irct stream
int KviTheoraDecoder::lu_B[256] [private]
Surface used in yuv->rgb processing (B)
int KviTheoraDecoder::lu_GU[256] [private]
Surface used in yuv->rgb processing (GU)
int KviTheoraDecoder::lu_GV[256] [private]
Surface used in yuv->rgb processing (GV)
int KviTheoraDecoder::lu_R[256] [private]
Surface used in yuv->rgb processing (R)
int KviTheoraDecoder::lu_Y[256] [private]
Surface used in yuv->rgb processing (Y)
KviDataBuffer* KviTheoraDecoder::m_pTextSignal [private]
Output text stream pointer
KviDataBuffer* KviTheoraDecoder::m_pVideoSignal [private]
Output video stream pointer
ogg_page KviTheoraDecoder::og [private]
One Ogg bitstream page. Vorbis packets are inside
ogg_packet KviTheoraDecoder::op [private]
One raw packet of encoded data
ogg_sync_state KviTheoraDecoder::oy [private]
int KviTheoraDecoder::pp_inc [private]
Theora postprocessing: increment
int KviTheoraDecoder::pp_level [private]
Theora postprocessing: current level
int KviTheoraDecoder::pp_level_max [private]
Theora postprocessing: max level
th_pixel_fmt KviTheoraDecoder::px_fmt [private]
Theora stream pixel format definition
unsigned char* KviTheoraDecoder::RGBbuffer [private]
RGB decoded surface pointer
int KviTheoraDecoder::stateflag [private]
Internal flag used in stream processing
th_comment KviTheoraDecoder::tc [private]
Theora stream comments struct
th_dec_ctx* KviTheoraDecoder::td [private]
Theora stream decoding struct
bool KviTheoraDecoder::thda [private]
Theora decode alloc state
int KviTheoraDecoder::theora_p [private]
True if the ogg stream contains a theora stream
bool KviTheoraDecoder::thtic [private]
Theora setup clear state
th_info KviTheoraDecoder::ti [private]
Theora stream info struct
ogg_stream_state KviTheoraDecoder::to [private]
Take physical pages, weld into a logical stream of theora packets
th_setup_info* KviTheoraDecoder::ts [private]
Theora stream setup info struct
ogg_int64_t KviTheoraDecoder::videobuf_granulepos [private]
Single frame video buffering : granule position
int KviTheoraDecoder::videobuf_ready [private]
Single frame video buffering : ready state
double KviTheoraDecoder::videobuf_time [private]
Single frame video buffering : duration
ogg_stream_state KviTheoraDecoder::zo [private]
Take physical pages, weld into a logical stream of irct packets
The documentation for this class was generated from the following files:
src/kvilib/ext/kvi_oggtheora.h
src/kvilib/ext/kvi_oggtheora.cpp