KVIrc: SetupWizard Class Reference
SetupWizard Class Reference
#include <SetupWizard.h>
Public Slots
virtual void accept ()
void chooseDataPath ()
void chooseIncomingPath ()
void chooseOldDataPath ()
void newDataTextChanged (const QString &)
void newDirClicked ()
void newIncomingTextChanged (const QString &)
void nickSelectorTextChanged (const QString &)
void oldDataTextChanged (const QString &)
void oldDirClicked ()
void portableClicked ()
virtual void reject ()
Public Member Functions
SetupWizard ()
~SetupWizard ()
Public Member Functions inherited from KviTalWizard
void addPage (QWidget *pWidget, const QString &szTitle)
QPushButton * backButton ()
QPushButton * cancelButton ()
QWidget * currentPage ()
QPushButton * finishButton ()
QPushButton * helpButton ()
void insertPage (QWidget *pWidget, const QString &szTitle, int iIndex)
KviTalWizard (QWidget *pParent)
QPushButton * nextButton ()
void setBackEnabled (QWidget *pWidget, bool bEnabled)
void setCancelEnabled (QWidget *pWidget, bool bEnabled)
bool setCurrentPage (QWidget *pWidget)
void setFinishEnabled (QWidget *pWidget, bool bEnabled)
void setHelpEnabled (QWidget *pWidget, bool bEnabled)
void setNextEnabled (QWidget *pWidget, bool bEnabled)
bool setPageEnabled (QWidget *pWidget, bool bEnabled)
bool setPageTitle (QWidget *pWidget, const QString &szTitle)
~KviTalWizard ()
Public Attributes
QComboBox * m_pAgeCombo
QCheckBox * m_pCreateDesktopShortcut
QCheckBox * m_pCreateUrlHandlers
QLineEdit * m_pDataPathEdit
SetupPage * m_pDesktopIntegration
KviTalGroupBox * m_pDirButtonGroup
SetupPage * m_pDirectory
QRadioButton * m_pDirUseNew
QRadioButton * m_pDirUsePrev
QComboBox * m_pGenderCombo
SetupPage * m_pIdentity
QLineEdit * m_pIncomingPathEdit
QPixmap * m_pLabelPixmap
KviStringSelector * m_pLanguagesSelector
SetupPage * m_pLicense
KviStringSelector * m_pLocationSelector
KviTalHBox * m_pNewIncomingBox
KviTalHBox * m_pNewPathBox
KviStringSelector * m_pNickSelector
QLineEdit * m_pOldDataPathEdit
KviTalHBox * m_pOldPathBox
KviStringSelector * m_pRealNameSelector
KviStringSelector * m_pServerHostSelector
KviUIntSelector * m_pServerPortSelector
SetupPage * m_pServers
KviStringSelector * m_pServerUrlSelector
SetupPage * m_pTheme
QGroupBox * m_pThemeButtonGroup
QRadioButton * m_pThemeHiRes
QRadioButton * m_pThemeLoRes
QRadioButton * m_pThemeNone
SetupPage * m_pWelcome
QString m_szServerConfigFile
QString m_szServerHost
QString m_szServerUrl
unsigned int m_uServerPort
Protected Member Functions
void enableOrDisableIdentityPageNextButton ()
void makeLink ()
void setUrlHandlers ()
virtual void showEvent (QShowEvent *e)
Protected Member Functions inherited from KviTalWizard
virtual void closeEvent (QCloseEvent *e)
void setCurrentPage (KviTalWizardPageData *pData)
Additional Inherited Members
Signals inherited from KviTalWizard
void helpClicked ()
void pageChanged (QString title)
Protected Slots inherited from KviTalWizard
void backButtonClicked ()
void cancelButtonClicked ()
void finishButtonClicked ()
void helpButtonClicked ()
void nextButtonClicked ()
Protected Attributes inherited from KviTalWizard
KviTalWizardPrivate * m_p
Constructor & Destructor Documentation
SetupWizard::SetupWizard ()
References __tr, __tr2qs, KviTalWizard::addPage(), KviFileUtils::adjustFilePath(), chooseDataPath(), chooseIncomingPath(), chooseOldDataPath(), KviApplication::Config, connect(), enableOrDisableIdentityPageNextButton(), KviQString::ensureLastCharIs(), KviQString::equalCI(), KviFileUtils::extractFileName(), KviFileUtils::extractFilePath(), KviFileUtils::fileExists(), KviMemory::free(), g_bFoundMirc, g_pApp, KviApplication::getGlobalKvircDirectory(), KviConfigurationFile::hasGroup(), i, KVI_DEFAULT_INCOMING_SUBDIRECTORY_NAME, KVI_LOCAL_KVIRC_SUBDIRECTORY_NAME, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_boolShowChannelsJoinOnIrc, KviOption_boolShowServersConnectDialogOnStart, KviOption_stringCtcpUserInfoAge, KviOption_stringCtcpUserInfoGender, KviOption_stringCtcpUserInfoLanguages, KviOption_stringCtcpUserInfoLocation, KviOption_stringNickname1, KviOption_stringNickname2, KviOption_stringRealname, KviOption_stringUsername, l, KviApplication::License, KviStringSelector::lineEdit(), KviFileUtils::loadFile(), m_pAgeCombo, m_pCreateDesktopShortcut, m_pCreateUrlHandlers, m_pDataPathEdit, m_pDesktopIntegration, m_pDirButtonGroup, m_pDirectory, m_pDirUseNew, m_pDirUsePrev, m_pGenderCombo, m_pIdentity, m_pIncomingPathEdit, m_pLabelPixmap, m_pLanguagesSelector, m_pLicense, m_pLocationSelector, m_pNewIncomingBox, m_pNewPathBox, m_pNickSelector, m_pOldDataPathEdit, m_pOldPathBox, m_pRealNameSelector, SetupPage::m_pTextLabel, m_pTheme, m_pThemeButtonGroup, m_pThemeHiRes, m_pThemeLoRes, m_pThemeNone, SetupPage::m_pVBox, m_pWelcome, newDataTextChanged(), newDirClicked(), newIncomingTextChanged(), nickSelectorTextChanged(), oldDataTextChanged(), oldDirClicked(), KviApplication::Pics, portableClicked(), KviConfigurationFile::Read, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readEntry(), KviConfigurationFile::readIntEntry(), KviTalWizard::setBackEnabled(), KviTalWizard::setFinishEnabled(), KviConfigurationFile::setGroup(), KviTalWizard::setHelpEnabled(), KviTalHBox::setMargin(), KviStringSelector::setMinimumLabelWidth(), KviTalWizard::setPageEnabled(), KviTalHBox::setSpacing(), KviTalVBox::setStretchFactor(), KviTalHBox::setStretchFactor(), KviStringSelector::setText(), KviStringSelector::setValidator(), szMircIni, and v.
SetupWizard::~SetupWizard ()
References m_pLabelPixmap.
Member Function Documentation
void SetupWizard::accept () virtual slot
References __tr, KviFileUtils::adjustFilePath(), bNeedToApplyDefaults, KviStringSelector::commit(), KviFileUtils::directoryExists(), KviQString::ensureLastCharIs(), g_bFoundMirc, g_iThemeToApply, g_pApp, g_szChoosenIncomingDirectory, i, KVI_DEFAULT_NICKNAME1, KVI_DEFAULT_NICKNAME2, KVI_DEFAULT_NICKNAME3, KVI_DEFAULT_NICKNAME4, KVI_DEFAULT_NICKNAME_TOKEN, KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringCtcpUserInfoAge, KviOption_stringCtcpUserInfoGender, KviOption_stringNickname1, KviOption_stringNickname2, KviOption_stringNickname3, KviOption_stringNickname4, m_pAgeCombo, m_pCreateDesktopShortcut, m_pCreateUrlHandlers, m_pDataPathEdit, m_pDirectory, m_pDirUseNew, m_pDirUsePrev, m_pGenderCombo, m_pIdentity, m_pIncomingPathEdit, m_pLanguagesSelector, m_pLocationSelector, m_pNickSelector, m_pOldDataPathEdit, m_pRealNameSelector, m_pTheme, m_pThemeHiRes, m_pThemeLoRes, KviApplication::m_szGlobalKvircDir, KviApplication::m_szLocalKvircDir, KviFileUtils::makeDir(), makeLink(), Q_UNUSED(), KviApplication::saveKvircDirectory(), KviTalWizard::setCurrentPage(), setUrlHandlers(), szMircServers, THEME_APPLY_HIRES, THEME_APPLY_LORES, THEME_APPLY_NONE, KviMessageBox::warning(), and KviFileUtils::writeFile().
void SetupWizard::chooseDataPath () slot
References __tr2qs, KviFileUtils::adjustFilePath(), KviQString::ensureLastCharIs(), KviTalFileDialog::getExistingDirectoryPath(), KVI_PATH_SEPARATOR_CHAR, m_pDataPathEdit, and szBuffer.
Referenced by SetupWizard().
void SetupWizard::chooseIncomingPath () slot
References __tr2qs, KviFileUtils::adjustFilePath(), KviTalFileDialog::getExistingDirectoryPath(), m_pIncomingPathEdit, and szBuffer.
Referenced by SetupWizard().
void SetupWizard::chooseOldDataPath () slot
References __tr2qs, KviFileUtils::adjustFilePath(), KviApplication::checkLocalKvircDirectory(), KviQString::ensureLastCharIs(), g_pApp, KviTalFileDialog::getExistingDirectoryPath(), KVI_PATH_SEPARATOR_CHAR, m_pDataPathEdit, m_pOldDataPathEdit, and szBuffer.
Referenced by SetupWizard().
void SetupWizard::enableOrDisableIdentityPageNextButton () protected
References KviStringSelector::currentText(), m_pIdentity, m_pNickSelector, and KviTalWizard::setNextEnabled().
Referenced by nickSelectorTextChanged(), and SetupWizard().
void SetupWizard::makeLink () protected
References KviQString::ensureLastCharIs(), g_pApp, KVI_PATH_SEPARATOR_CHAR, KviApplication::m_szGlobalKvircDir, NULL, and KviFileUtils::writeFile().
Referenced by accept().
void SetupWizard::newDataTextChanged (const QString & str) slot
References m_pDirectory, m_pIncomingPathEdit, and KviTalWizard::setNextEnabled().
Referenced by SetupWizard().
void SetupWizard::newDirClicked () slot
References m_pDataPathEdit, m_pDirectory, m_pIdentity, m_pIncomingPathEdit, m_pNewIncomingBox, m_pNewPathBox, m_pOldPathBox, m_pServers, m_pTheme, KviTalWizard::setNextEnabled(), and KviTalWizard::setPageEnabled().
Referenced by SetupWizard().
void SetupWizard::newIncomingTextChanged (const QString & str) slot
References m_pDataPathEdit, m_pDirectory, and KviTalWizard::setNextEnabled().
Referenced by SetupWizard().
void SetupWizard::nickSelectorTextChanged (const QString & str) slot
References enableOrDisableIdentityPageNextButton().
Referenced by SetupWizard().
void SetupWizard::oldDataTextChanged (const QString & str) slot
References m_pDirectory, and KviTalWizard::setNextEnabled().
Referenced by SetupWizard().
void SetupWizard::oldDirClicked () slot
References m_pDirectory, m_pIdentity, m_pNewIncomingBox, m_pNewPathBox, m_pOldDataPathEdit, m_pOldPathBox, m_pServers, m_pTheme, KviTalWizard::setNextEnabled(), and KviTalWizard::setPageEnabled().
Referenced by SetupWizard().
void SetupWizard::portableClicked () slot
References m_pDirectory, m_pIdentity, m_pNewIncomingBox, m_pNewPathBox, m_pOldPathBox, m_pServers, m_pTheme, KviTalWizard::setNextEnabled(), and KviTalWizard::setPageEnabled().
Referenced by SetupWizard().
void SetupWizard::reject () virtual slot
References __tr2qs, KviControlCodes::Escape, and KviMessageBox::warning().
void SetupWizard::setUrlHandlers () protected
References g_pApp, KviApplication::m_szGlobalKvircDir, and KviFileUtils::writeFile().
Referenced by accept().
void SetupWizard::showEvent (QShowEvent * e) protected virtual
Displays the first page if no other page is shown yet.
Reimplemented from KviTalWizard.
References g_pApp, h, r, KviTalWizard::showEvent(), and w.
Member Data Documentation
QComboBox* SetupWizard::m_pAgeCombo
Referenced by accept(), and SetupWizard().
QCheckBox* SetupWizard::m_pCreateDesktopShortcut
Referenced by accept(), and SetupWizard().
QCheckBox* SetupWizard::m_pCreateUrlHandlers
Referenced by accept(), and SetupWizard().
QLineEdit* SetupWizard::m_pDataPathEdit
Referenced by accept(), chooseDataPath(), chooseOldDataPath(), newDirClicked(), newIncomingTextChanged(), and SetupWizard().
SetupPage* SetupWizard::m_pDesktopIntegration
Referenced by SetupWizard().
KviTalGroupBox* SetupWizard::m_pDirButtonGroup
Referenced by SetupWizard().
SetupPage* SetupWizard::m_pDirectory
Referenced by accept(), newDataTextChanged(), newDirClicked(), newIncomingTextChanged(), oldDataTextChanged(), oldDirClicked(), portableClicked(), and SetupWizard().
QRadioButton* SetupWizard::m_pDirUseNew
Referenced by accept(), and SetupWizard().
QRadioButton* SetupWizard::m_pDirUsePrev
Referenced by accept(), and SetupWizard().
QComboBox* SetupWizard::m_pGenderCombo
Referenced by accept(), and SetupWizard().
SetupPage* SetupWizard::m_pIdentity
Referenced by accept(), enableOrDisableIdentityPageNextButton(), newDirClicked(), oldDirClicked(), portableClicked(), and SetupWizard().
QLineEdit* SetupWizard::m_pIncomingPathEdit
Referenced by accept(), chooseIncomingPath(), newDataTextChanged(), newDirClicked(), and SetupWizard().
QPixmap* SetupWizard::m_pLabelPixmap
Referenced by SetupPage::SetupPage(), SetupWizard(), and ~SetupWizard().
KviStringSelector* SetupWizard::m_pLanguagesSelector
Referenced by accept(), and SetupWizard().
SetupPage* SetupWizard::m_pLicense
Referenced by SetupWizard().
KviStringSelector* SetupWizard::m_pLocationSelector
Referenced by accept(), and SetupWizard().
KviTalHBox* SetupWizard::m_pNewIncomingBox
Referenced by newDirClicked(), oldDirClicked(), portableClicked(), and SetupWizard().
KviTalHBox* SetupWizard::m_pNewPathBox
Referenced by newDirClicked(), oldDirClicked(), portableClicked(), and SetupWizard().
KviStringSelector* SetupWizard::m_pNickSelector
Referenced by accept(), enableOrDisableIdentityPageNextButton(), and SetupWizard().
QLineEdit* SetupWizard::m_pOldDataPathEdit
Referenced by accept(), chooseOldDataPath(), oldDirClicked(), and SetupWizard().
KviTalHBox* SetupWizard::m_pOldPathBox
Referenced by newDirClicked(), oldDirClicked(), portableClicked(), and SetupWizard().
KviStringSelector* SetupWizard::m_pRealNameSelector
Referenced by accept(), and SetupWizard().
KviStringSelector* SetupWizard::m_pServerHostSelector
KviUIntSelector* SetupWizard::m_pServerPortSelector
SetupPage* SetupWizard::m_pServers
Referenced by newDirClicked(), oldDirClicked(), and portableClicked().
KviStringSelector* SetupWizard::m_pServerUrlSelector
SetupPage* SetupWizard::m_pTheme
Referenced by accept(), newDirClicked(), oldDirClicked(), portableClicked(), and SetupWizard().
QGroupBox* SetupWizard::m_pThemeButtonGroup
Referenced by SetupWizard().
QRadioButton* SetupWizard::m_pThemeHiRes
Referenced by accept(), and SetupWizard().
QRadioButton* SetupWizard::m_pThemeLoRes
Referenced by accept(), and SetupWizard().
QRadioButton* SetupWizard::m_pThemeNone
Referenced by SetupWizard().
SetupPage* SetupWizard::m_pWelcome
Referenced by SetupWizard().
QString SetupWizard::m_szServerConfigFile
QString SetupWizard::m_szServerHost
QString SetupWizard::m_szServerUrl
unsigned int SetupWizard::m_uServerPort
The documentation for this class was generated from the following files:
src/modules/setup/SetupWizard.h
src/modules/setup/SetupWizard.cpp