KVIrc: OptionsWidgetContainer Class Reference
OptionsWidgetContainer Class Reference
#include <OptionsWidgetContainer.h>
Public Member Functions
OptionsWidgetContainer (QWidget *par, bool bModal=false)
void setLeftCornerWidget (QWidget *pWidget)
void setNextToLeft (QWidget *pWidget)
void setup (KviOptionsWidget *w)
~OptionsWidgetContainer ()
Protected Slots
void cancelClicked ()
void okClicked ()
void optionsWidgetDestroyed ()
Protected Member Functions
virtual void childEvent (QChildEvent *e)
virtual void closeEvent (QCloseEvent *e)
virtual void reject ()
virtual void showEvent (QShowEvent *e)
Protected Attributes
QPushButton * m_pCancel
QGridLayout * m_pLayout
KviOptionsWidget * m_pOptionsWidget
Constructor & Destructor Documentation
OptionsWidgetContainer::OptionsWidgetContainer (QWidget * par, bool bModal = false)
References m_pLayout, and m_pOptionsWidget.
OptionsWidgetContainer::~OptionsWidgetContainer ()
References m_pOptionsWidget.
Member Function Documentation
void OptionsWidgetContainer::cancelClicked () protected slot
Referenced by closeEvent(), reject(), and setup().
void OptionsWidgetContainer::childEvent (QChildEvent * e) protected virtual
References m_pOptionsWidget, and optionsWidgetDestroyed().
void OptionsWidgetContainer::closeEvent (QCloseEvent * e) protected virtual
References cancelClicked().
void OptionsWidgetContainer::okClicked () protected slot
References KviOptionsWidget::commit(), g_pApp, m_pOptionsWidget, and KviApplication::saveOptions().
Referenced by setup().
void OptionsWidgetContainer::optionsWidgetDestroyed () protected slot
References m_pOptionsWidget.
Referenced by childEvent(), and setup().
void OptionsWidgetContainer::reject () protected virtual
References cancelClicked().
void OptionsWidgetContainer::setLeftCornerWidget (QWidget * pWidget)
References m_pLayout.
Referenced by OptionsWidget_servers::OptionsWidget_servers().
void OptionsWidgetContainer::setNextToLeft (QWidget * pWidget)
References m_pLayout.
void OptionsWidgetContainer::setup (KviOptionsWidget * w)
References __tr2qs_ctx(), KviIconManager::Accept, KviTalToolTip::add(), cancelClicked(), connect(), KviIconManager::Discard, e, _OptionsWidgetInstanceEntry::eIcon, OptionsInstanceManager::findInstanceEntry(), g_pIconManager, KviIconManager::getSmallIcon(), m_pCancel, m_pLayout, m_pOptionsWidget, okClicked(), optionsWidgetDestroyed(), _OptionsWidgetInstanceEntry::szName, and w.
Referenced by options_kvs_cmd_edit().
void OptionsWidgetContainer::showEvent (QShowEvent * e) protected virtual
References g_pApp, g_pMainWindow, m_pCancel, and KviMemory::move().
Member Data Documentation
QPushButton* OptionsWidgetContainer::m_pCancel protected
Referenced by setup(), and showEvent().
QGridLayout* OptionsWidgetContainer::m_pLayout protected
Referenced by OptionsWidgetContainer(), setLeftCornerWidget(), setNextToLeft(), and setup().
KviOptionsWidget* OptionsWidgetContainer::m_pOptionsWidget protected
Referenced by childEvent(), okClicked(), OptionsWidgetContainer(), optionsWidgetDestroyed(), setup(), and ~OptionsWidgetContainer().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidgetContainer.h
src/modules/options/OptionsWidgetContainer.cpp