KVIrc: KviKvsTreeNodeGlobalVariable Class Reference
KviKvsTreeNodeGlobalVariable Class Reference
#include <kvi_kvs_treenode_globalvariable.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
KviKvsTreeNodeGlobalVariable (const QChar *pLocation, const QString &szIdentifier)
~KviKvsTreeNodeGlobalVariable ()
Constructor & Destructor Documentation
KviKvsTreeNodeGlobalVariable::KviKvsTreeNodeGlobalVariable (const QChar * pLocation, const QString & szIdentifier)
KviKvsTreeNodeGlobalVariable::~KviKvsTreeNodeGlobalVariable ()
Member Function Documentation
void KviKvsTreeNodeGlobalVariable::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeVariable::m_szIdentifier.
void KviKvsTreeNodeGlobalVariable::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeData.
References debug, and KviKvsTreeNodeVariable::m_szIdentifier.
bool KviKvsTreeNodeGlobalVariable::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::copyFrom(), KviKvsHash::find(), KviKvsRunTimeContext::globalVariables(), KviKvsTreeNodeVariable::m_szIdentifier, and KviKvsVariant::setNothing().
KviKvsRWEvaluationResult * KviKvsTreeNodeGlobalVariable::evaluateReadWrite (KviKvsRunTimeContext * c) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsHash::get(), KviKvsRunTimeContext::globalVariables(), and KviKvsTreeNodeVariable::m_szIdentifier.
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_globalvariable.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_globalvariable.cpp