KVIrc: NotifierWindow Class Reference
NotifierWindow Class Reference
#include <NotifierWindow.h>
Public Slots
void hideNow ()
void slotTabCloseRequested (int index)
void toggleLineEdit ()
Public Member Functions
void addMessage (KviWindow *pWnd, const QString &szImageId, const QString &szText, unsigned int uMessageTime)
int countTabs () const
void doHide (bool bDoAnimate)
void doShow (bool bDoAnimate)
NotifierWindow ()
void setDisableHideOnMainWindowGotAttention (bool b)
void showLineEdit (bool bShow)
State state () const
int textWidth ()
~NotifierWindow ()
Protected Slots
void blink ()
void disableFor15Minutes ()
void disableFor1Minute ()
void disableFor30Minutes ()
void disableFor5Minutes ()
void disableFor60Minutes ()
void disablePermanently ()
void disableUntilKVIrcRestarted ()
void fillContextPopup ()
void heartbeat ()
void progressUpdate ()
void returnPressed ()
void updateGui ()
Protected Member Functions
virtual void enterEvent (QEvent *e)
virtual bool eventFilter (QObject *pEdit, QEvent *e)
virtual void hideEvent (QHideEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
virtual void leaveEvent (QEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
virtual void showEvent (QShowEvent *e)
Protected Attributes
bool m_bBlinkOn
bool m_bCloseDown
bool m_bCrashShowWorkAround
bool m_bDiagonalResizing
bool m_bDisableHideOnMainWindowGotAttention
bool m_bDragging
bool m_bLeftButtonIsPressed
bool m_bNextDown
bool m_bPrevDown
bool m_bResizing
bool m_bWriteDown
QCursor m_cursor
double m_dOpacity
State m_eState
int m_iBlinkCount
QTimer * m_pAutoHideTimer
QTimer * m_pBlinkTimer
QMenu * m_pContextPopup
NotifierMessage * m_pCurrentMessage
QMenu * m_pDisablePopup
KviThemedLineEdit * m_pLineEdit
QPoint m_pntClick
QPoint m_pntDrag
QPoint m_pntPos
QProgressBar * m_pProgressBar
QTimer * m_pShowHideTimer
KviWindow * m_pWindowToRaise
NotifierWindowBorder * m_pWndBorder
QTabWidget * m_pWndTabs
QTime m_qtStartedAt
kvi_time_t m_tAutoHideAt
kvi_time_t m_tStartedAt
int m_whereResizing
QRect m_wndRect
Private Member Functions
bool checkResizing (QPoint)
void contextPopup (const QPoint &pos)
void redrawText ()
void resize (QPoint p, bool=true)
void setCursor (int)
bool shouldHideIfMainWindowGotAttention ()
void startAutoHideTimer ()
void startBlinking ()
void stopAutoHideTimer ()
void stopBlinkTimer ()
void stopShowHideTimer ()
Constructor & Destructor Documentation
NotifierWindow::NotifierWindow ()
References NotifierWindowBorder::bodyRect(), connect(), g_pApp, Hidden, m_bBlinkOn, m_bCloseDown, m_bDiagonalResizing, m_bDisableHideOnMainWindowGotAttention, m_bDragging, m_bLeftButtonIsPressed, m_bNextDown, m_bPrevDown, m_bResizing, m_bWriteDown, m_dOpacity, m_eState, m_pAutoHideTimer, m_pBlinkTimer, m_pContextPopup, m_pDisablePopup, m_pLineEdit, m_pProgressBar, m_pShowHideTimer, m_pWndBorder, m_pWndTabs, m_tAutoHideAt, m_tStartedAt, m_wndRect, r, returnPressed(), slotTabCloseRequested(), SPACING, updateGui(), WDG_MIN_HEIGHT, and WDG_MIN_WIDTH.
NotifierWindow::~NotifierWindow ()
References m_pWndBorder, m_pWndTabs, stopAutoHideTimer(), stopBlinkTimer(), and stopShowHideTimer().
Member Function Documentation
void NotifierWindow::addMessage (KviWindow * pWnd, const QString & szImageId, const QString & szText, unsigned int uMessageTime)
References NotifierWindowTab::appendMessage(), g_pIconManager, KviIconManager::getImage(), KviWindow::hasAttention(), i, kvi_time_t, kvi_unixTime, m_bDisableHideOnMainWindowGotAttention, m_eState, m_pWndTabs, m_tAutoHideAt, KviWindow::MainWindowIsVisible, startAutoHideTimer(), startBlinking(), stopAutoHideTimer(), and Visible.
Referenced by notifier_kvs_cmd_message(), notifier_module_ctrl(), and returnPressed().
void NotifierWindow::blink () [protected, slot]
References doHide(), m_bBlinkOn, m_iBlinkCount, shouldHideIfMainWindowGotAttention(), and stopBlinkTimer().
Referenced by startBlinking().
bool NotifierWindow::checkResizing (QPoint e) [private]
References m_bLeftButtonIsPressed, m_bResizing, m_whereResizing, setCursor(), WDG_BORDER_THICKNESS, WDG_DWN, WDG_DWNDX, WDG_DWNSX, WDG_DX, WDG_SX, WDG_UP, WDG_UPDX, and WDG_UPSX.
Referenced by mouseMoveEvent(), and mousePressEvent().
void NotifierWindow::contextPopup (const QPoint & pos) [private]
References connect(), fillContextPopup(), m_pContextPopup, and m_pDisablePopup.
Referenced by mousePressEvent().
int NotifierWindow::countTabs () const [inline]
References m_pWndTabs.
Referenced by notifier_kvs_cmd_show().
void NotifierWindow::disableFor15Minutes () [protected, slot]
References g_tNotifierDisabledUntil, hideNow(), kvi_time_t, and kvi_unixTime.
Referenced by fillContextPopup().
void NotifierWindow::disableFor1Minute () [protected, slot]
References g_tNotifierDisabledUntil, hideNow(), kvi_time_t, and kvi_unixTime.
Referenced by fillContextPopup().
void NotifierWindow::disableFor30Minutes () [protected, slot]
References g_tNotifierDisabledUntil, hideNow(), kvi_time_t, and kvi_unixTime.
Referenced by fillContextPopup().
void NotifierWindow::disableFor5Minutes () [protected, slot]
References g_tNotifierDisabledUntil, hideNow(), kvi_time_t, and kvi_unixTime.
Referenced by fillContextPopup().
void NotifierWindow::disableFor60Minutes () [protected, slot]
References g_tNotifierDisabledUntil, hideNow(), kvi_time_t, and kvi_unixTime.
Referenced by fillContextPopup().
void NotifierWindow::disablePermanently () [protected, slot]
References hideNow(), KVI_OPTION_BOOL, and KviOption_boolEnableNotifier.
Referenced by fillContextPopup().
void NotifierWindow::disableUntilKVIrcRestarted () [protected, slot]
References g_tNotifierDisabledUntil, hideNow(), kvi_time_t, and kvi_unixTime.
Referenced by fillContextPopup().
void NotifierWindow::doHide (bool bDoAnimate)
References connect(), heartbeat(), Hidden, hideNow(), Hiding, m_dOpacity, m_eState, m_pShowHideTimer, m_pWndBorder, OPACITY_STEP, Showing, stopAutoHideTimer(), stopBlinkTimer(), stopShowHideTimer(), Visible, NotifierWindowBorder::x(), x, NotifierWindowBorder::y(), and y.
Referenced by blink(), notifier_kvs_cmd_hide(), and progressUpdate().
void NotifierWindow::doShow (bool bDoAnimate)
References connect(), g_tNotifierDisabledUntil, heartbeat(), Hidden, Hiding, KVI_OPTION_BOOL, kvi_time_t, kvi_unixTime, KviOption_boolDontShowNotifierIfActiveWindowIsFullScreen, KviOption_boolEnableNotifier, m_bBlinkOn, m_bCloseDown, m_bCrashShowWorkAround, m_bDragging, m_bNextDown, m_bPrevDown, m_bWriteDown, m_dOpacity, m_eState, m_pShowHideTimer, OPACITY_STEP, Showing, startAutoHideTimer(), startBlinking(), stopBlinkTimer(), stopShowHideTimer(), and Visible.
Referenced by notifier_kvs_cmd_message(), notifier_kvs_cmd_show(), and notifier_module_ctrl().
void NotifierWindow::enterEvent (QEvent * e) [protected, virtual]
References connect(), FocusingOn, heartbeat(), m_eState, and m_pShowHideTimer.
bool NotifierWindow::eventFilter (QObject * pEdit, QEvent * e) [protected, virtual]
References hideNow(), m_bBlinkOn, m_pLineEdit, m_tAutoHideAt, stopAutoHideTimer(), and stopBlinkTimer().
void NotifierWindow::fillContextPopup () [protected, slot]
References __tr2qs_ctx(), KviIconManager::Close, disableFor15Minutes(), disableFor1Minute(), disableFor30Minutes(), disableFor5Minutes(), disableFor60Minutes(), disablePermanently(), disableUntilKVIrcRestarted(), KviIconManager::Editor, g_pIconManager, KviIconManager::getSmallIcon(), hideNow(), m_pContextPopup, m_pDisablePopup, KviIconManager::Quit, KviIconManager::Time, and toggleLineEdit().
Referenced by contextPopup().
void NotifierWindow::heartbeat () [protected, slot]
References FocusingOff, FocusingOn, Hidden, hideNow(), Hiding, KVI_OPTION_UINT, KviOption_uintNotifierActiveTransparency, KviOption_uintNotifierInactiveTransparency, m_dOpacity, m_eState, OPACITY_STEP, shouldHideIfMainWindowGotAttention(), Showing, startAutoHideTimer(), startBlinking(), stopShowHideTimer(), and Visible.
Referenced by doHide(), doShow(), enterEvent(), and leaveEvent().
void NotifierWindow::hideEvent (QHideEvent * e) [protected, virtual]
References Hidden, m_bCrashShowWorkAround, m_bDisableHideOnMainWindowGotAttention, m_eState, m_tAutoHideAt, stopAutoHideTimer(), stopBlinkTimer(), and stopShowHideTimer().
void NotifierWindow::hideNow () [slot]
References Hidden, m_dOpacity, m_eState, m_tAutoHideAt, stopAutoHideTimer(), stopBlinkTimer(), and stopShowHideTimer().
Referenced by disableFor15Minutes(), disableFor1Minute(), disableFor30Minutes(), disableFor5Minutes(), disableFor60Minutes(), disablePermanently(), disableUntilKVIrcRestarted(), doHide(), eventFilter(), fillContextPopup(), heartbeat(), keyPressEvent(), NotifierWindowTab::mouseDoubleClickEvent(), mouseReleaseEvent(), and slotTabCloseRequested().
void NotifierWindow::keyPressEvent (QKeyEvent * e) [protected, virtual]
References hideNow().
void NotifierWindow::leaveEvent (QEvent * e) [protected, virtual]
References connect(), FocusingOff, heartbeat(), Hidden, m_bResizing, m_eState, m_pShowHideTimer, m_pWndBorder, NotifierWindowBorder::resetIcons(), and setCursor().
void NotifierWindow::mouseMoveEvent (QMouseEvent * e) [protected, virtual]
References NotifierWindowBorder::captionRect(), checkResizing(), NotifierWindowBorder::closeRect(), m_bDragging, m_bLeftButtonIsPressed, m_bResizing, m_pntDrag, m_pntPos, m_pWndBorder, m_wndRect, resize(), NotifierWindowBorder::setCloseIcon(), setCursor(), WDG_ICON_OUT, and WDG_ICON_OVER.
void NotifierWindow::mousePressEvent (QMouseEvent * e) [protected, virtual]
References NotifierWindowBorder::captionRect(), checkResizing(), NotifierWindowBorder::closeRect(), contextPopup(), m_bBlinkOn, m_bCloseDown, m_bDragging, m_bLeftButtonIsPressed, m_bResizing, m_pLineEdit, m_pntClick, m_pntDrag, m_pntPos, m_pWndBorder, m_tAutoHideAt, NotifierWindowBorder::rect(), NotifierWindowBorder::setCloseIcon(), stopAutoHideTimer(), stopBlinkTimer(), and WDG_ICON_CLICKED.
void NotifierWindow::mouseReleaseEvent (QMouseEvent * e) [protected, virtual]
References NotifierWindowBorder::captionRect(), NotifierWindowBorder::closeRect(), hideNow(), m_bCloseDown, m_bDragging, m_bLeftButtonIsPressed, m_bNextDown, m_bPrevDown, m_bResizing, m_bWriteDown, m_pWndBorder, and setCursor().
void NotifierWindow::paintEvent (QPaintEvent * e) [protected, virtual]
References NotifierWindowBorder::draw(), NotifierWindowBorder::height(), KVI_OPTION_COLOR, KVI_OPTION_FONT, KviOption_colorNotifierTitleForeground, KviOption_fontNotifierTitle, m_bBlinkOn, m_pWndBorder, m_pWndTabs, KviWindow::plainTextCaption(), NotifierWindowBorder::resize(), NotifierWindowBorder::titleRect(), NotifierWindowBorder::width(), and NotifierWindowTab::wnd().
void NotifierWindow::progressUpdate () [protected, slot]
References doHide(), kvi_time_t, kvi_unixTime, m_pProgressBar, m_tAutoHideAt, m_tStartedAt, and stopAutoHideTimer().
Referenced by startAutoHideTimer().
void NotifierWindow::redrawText () [private]
void NotifierWindow::resize (QPoint p, bool = true) [private]
References m_pLineEdit, m_whereResizing, m_wndRect, showLineEdit(), WDG_DWN, WDG_DWNDX, WDG_DWNSX, WDG_DX, WDG_MIN_HEIGHT, WDG_MIN_WIDTH, WDG_SX, WDG_UP, WDG_UPDX, WDG_UPSX, x, and y.
Referenced by mouseMoveEvent().
void NotifierWindow::returnPressed () [protected, slot]
References addMessage(), KviCString::Format, m_pLineEdit, m_pWndTabs, KviIconManager::OwnPrivMsg, KviIrcUrl::parse(), KviCString::ptr(), and NotifierWindowTab::wnd().
Referenced by NotifierWindow().
void NotifierWindow::setCursor (int iCur) [inline, private]
References m_cursor.
Referenced by checkResizing(), leaveEvent(), mouseMoveEvent(), and mouseReleaseEvent().
void NotifierWindow::setDisableHideOnMainWindowGotAttention (bool b) [inline]
References m_bDisableHideOnMainWindowGotAttention.
Referenced by notifier_kvs_cmd_show().
bool NotifierWindow::shouldHideIfMainWindowGotAttention () [private]
References KviWindow::hasAttention(), m_bDisableHideOnMainWindowGotAttention, m_pWndTabs, and NotifierWindowTab::wnd().
Referenced by blink(), and heartbeat().
void NotifierWindow::showEvent (QShowEvent * e) [protected, virtual]
References m_wndRect.
void NotifierWindow::showLineEdit (bool bShow)
References __tr2qs_ctx(), m_pLineEdit, and m_pWndTabs.
Referenced by resize(), and toggleLineEdit().
void NotifierWindow::slotTabCloseRequested (int index) [slot]
References hideNow(), and m_pWndTabs.
Referenced by NotifierWindowTab::closeMe(), and NotifierWindow().
void NotifierWindow::startAutoHideTimer () [private]
References connect(), kvi_unixTime, m_pAutoHideTimer, m_tAutoHideAt, m_tStartedAt, progressUpdate(), and stopAutoHideTimer().
Referenced by addMessage(), doShow(), and heartbeat().
void NotifierWindow::startBlinking () [private]
References blink(), connect(), KVI_OPTION_BOOL, KviOption_boolNotifierFlashing, m_bBlinkOn, m_iBlinkCount, m_pBlinkTimer, and stopBlinkTimer().
Referenced by addMessage(), doShow(), and heartbeat().
State NotifierWindow::state () const [inline]
References m_eState.
void NotifierWindow::stopAutoHideTimer () [private]
References m_pAutoHideTimer, and m_pProgressBar.
Referenced by addMessage(), doHide(), eventFilter(), hideEvent(), hideNow(), mousePressEvent(), progressUpdate(), startAutoHideTimer(), and ~NotifierWindow().
void NotifierWindow::stopBlinkTimer () [private]
References m_pBlinkTimer.
Referenced by blink(), doHide(), doShow(), eventFilter(), hideEvent(), hideNow(), mousePressEvent(), startBlinking(), and ~NotifierWindow().
void NotifierWindow::stopShowHideTimer () [private]
References m_pShowHideTimer.
Referenced by doHide(), doShow(), heartbeat(), hideEvent(), hideNow(), and ~NotifierWindow().
int NotifierWindow::textWidth ()
void NotifierWindow::toggleLineEdit () [slot]
References m_pLineEdit, and showLineEdit().
Referenced by fillContextPopup().
void NotifierWindow::updateGui () [protected, slot]
References i, KVI_OPTION_COLOR, KVI_OPTION_FONT, KviOption_colorNotifierForeground, KviOption_fontNotifier, m_pLineEdit, and m_pWndTabs.
Referenced by NotifierWindow().
Member Data Documentation
bool NotifierWindow::m_bBlinkOn [protected]
Referenced by blink(), doShow(), eventFilter(), mousePressEvent(), NotifierWindow(), paintEvent(), and startBlinking().
bool NotifierWindow::m_bCloseDown [protected]
Referenced by doShow(), mousePressEvent(), mouseReleaseEvent(), and NotifierWindow().
bool NotifierWindow::m_bCrashShowWorkAround [protected]
Referenced by doShow(), and hideEvent().
bool NotifierWindow::m_bDiagonalResizing [protected]
Referenced by NotifierWindow().
bool NotifierWindow::m_bDisableHideOnMainWindowGotAttention [protected]
Referenced by addMessage(), hideEvent(), NotifierWindow(), setDisableHideOnMainWindowGotAttention(), and shouldHideIfMainWindowGotAttention().
bool NotifierWindow::m_bDragging [protected]
Referenced by doShow(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and NotifierWindow().
bool NotifierWindow::m_bLeftButtonIsPressed [protected]
Referenced by checkResizing(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and NotifierWindow().
bool NotifierWindow::m_bNextDown [protected]
Referenced by doShow(), mouseReleaseEvent(), and NotifierWindow().
bool NotifierWindow::m_bPrevDown [protected]
Referenced by doShow(), mouseReleaseEvent(), and NotifierWindow().
bool NotifierWindow::m_bResizing [protected]
Referenced by checkResizing(), leaveEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and NotifierWindow().
bool NotifierWindow::m_bWriteDown [protected]
Referenced by doShow(), mouseReleaseEvent(), and NotifierWindow().
QCursor NotifierWindow::m_cursor [protected]
Referenced by setCursor().
double NotifierWindow::m_dOpacity [protected]
Referenced by doHide(), doShow(), heartbeat(), hideNow(), and NotifierWindow().
State NotifierWindow::m_eState [protected]
Referenced by addMessage(), doHide(), doShow(), enterEvent(), heartbeat(), hideEvent(), hideNow(), leaveEvent(), NotifierWindow(), and state().
int NotifierWindow::m_iBlinkCount [protected]
Referenced by blink(), and startBlinking().
QTimer* NotifierWindow::m_pAutoHideTimer [protected]
Referenced by NotifierWindow(), startAutoHideTimer(), and stopAutoHideTimer().
QTimer* NotifierWindow::m_pBlinkTimer [protected]
Referenced by NotifierWindow(), startBlinking(), and stopBlinkTimer().
QMenu* NotifierWindow::m_pContextPopup [protected]
Referenced by contextPopup(), fillContextPopup(), and NotifierWindow().
NotifierMessage* NotifierWindow::m_pCurrentMessage [protected]
QMenu* NotifierWindow::m_pDisablePopup [protected]
Referenced by contextPopup(), fillContextPopup(), and NotifierWindow().
KviThemedLineEdit* NotifierWindow::m_pLineEdit [protected]
Referenced by eventFilter(), mousePressEvent(), NotifierWindow(), resize(), returnPressed(), showLineEdit(), toggleLineEdit(), and updateGui().
QPoint NotifierWindow::m_pntClick [protected]
Referenced by mousePressEvent().
QPoint NotifierWindow::m_pntDrag [protected]
Referenced by mouseMoveEvent(), and mousePressEvent().
QPoint NotifierWindow::m_pntPos [protected]
Referenced by mouseMoveEvent(), and mousePressEvent().
QProgressBar* NotifierWindow::m_pProgressBar [protected]
Referenced by NotifierWindow(), progressUpdate(), and stopAutoHideTimer().
QTimer* NotifierWindow::m_pShowHideTimer [protected]
Referenced by doHide(), doShow(), enterEvent(), leaveEvent(), NotifierWindow(), and stopShowHideTimer().
KviWindow* NotifierWindow::m_pWindowToRaise [protected]
NotifierWindowBorder* NotifierWindow::m_pWndBorder [protected]
Referenced by doHide(), leaveEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), NotifierWindow(), paintEvent(), and ~NotifierWindow().
QTabWidget* NotifierWindow::m_pWndTabs [protected]
Referenced by addMessage(), countTabs(), NotifierWindow(), paintEvent(), returnPressed(), shouldHideIfMainWindowGotAttention(), showLineEdit(), slotTabCloseRequested(), updateGui(), and ~NotifierWindow().
QTime NotifierWindow::m_qtStartedAt [protected]
kvi_time_t NotifierWindow::m_tAutoHideAt [protected]
Referenced by addMessage(), eventFilter(), hideEvent(), hideNow(), mousePressEvent(), NotifierWindow(), progressUpdate(), and startAutoHideTimer().
kvi_time_t NotifierWindow::m_tStartedAt [protected]
Referenced by NotifierWindow(), progressUpdate(), and startAutoHideTimer().
int NotifierWindow::m_whereResizing [protected]
Referenced by checkResizing(), and resize().
QRect NotifierWindow::m_wndRect [protected]
Referenced by mouseMoveEvent(), NotifierWindow(), resize(), and showEvent().
The documentation for this class was generated from the following files:
src/modules/notifier/NotifierWindow.h
src/modules/notifier/NotifierWindow.cpp