KVIrc: KviIrcConnection Class Reference
KviIrcConnection Class Reference
An abstraction of a connection to an IRC server.
#include <KviIrcConnection.h>
Public Types
enum State { Idle, Connecting, Connected }
The possible "high level" states of this connection.
Public Slots
void restartNotifyList ()
Called to restart the notify list.
void unhighlightAllChannels ()
Called when we unhighlight all channels.
void unhighlightAllQueries ()
Called when we unhighlight all queries.
Signals
void awayStateChanged ()
Emitted when the away state changes.
void chanListChanged ()
Emitted when the channels list change.
void channelRegistered (KviChannelWindow *pChan)
Emitted when we register a channel.
void channelUnregistered (KviChannelWindow *pChan)
Emitted when we unregister a channel.
void nickNameChanged ()
Emitted when the nickname changes.
void userModeChanged ()
Emitted when the user modes change.
Public Member Functions
KviIrcConnectionAntiCtcpFloodData * antiCtcpFloodData ()
Returns a pointer to the KviIrcConnectionAntiCtcpFloodData object.
KviIrcConnectionAsyncWhoisData * asyncWhoisData ()
Returns a pointer to the KviIrcConnectionAsyncWhoisData object.
KviPointerList
< KviChannelWindow > * channelList ()
Returns the list of the channels bound to the current connection.
void clearOutputQueue (bool bPrivateMessagesOnly)
void closeAllChannels ()
Closes all the currently open channels not marked as dead.
void closeAllQueries ()
Closes all the currently open queries not marked as dead.
KviConsoleWindow * console ()
Returns a pointer to the owning console.
KviIrcContext * context ()
Returns a pointer to the owning KviIrcContext.
KviChannelWindow * createChannel (const QString &szName)
Creates a new channel with the specified name.
KviQueryWindow * createQuery (const QString &szNick)
Creates a query with the specified nick as target.
const QString & currentNetworkName ()
Helper that provides a shortcut for really common access to serverInfo()->networkName()
const QString & currentNickName ()
Helper that provides a shortcut for really common access to userInfo()->nickName()
const QString & currentServerName ()
Helper that provides a shortcut for really common access to serverInfo()->name()
const QString & currentUserName ()
Helper that provides a shortcut for really common access to userInfo()->userName()
QString decodeText (const char *szText)
Decodes the specified text by using the server codec.
QByteArray encodeText (const QString &szText)
Encodes the specified text by using the local text codec.
KviChannelWindow * findChannel (const QString &szName)
Finds the channel with the specified unicode name.
KviQueryWindow * findQuery (const QString &szNick)
Finds the query with the specified nick.
int getCommonChannels (const QString &szNick, QString &szChansBuffer, bool bAddEscapeSequences=true)
Returns a list of channels bound to the current connection.
void incomingMessage (const char *pcMessage)
This function is part of the networking stack.
void incomingMessageNoFilter (const char *pcMessage)
This function is part of the networking stack.
void keepChannelsOpenAfterDisconnect ()
Marks all the currently existing channels as DEAD.
void keepQueriesOpenAfterDisconnect ()
Marks all the currently open queries as DEAD.
KviLagMeter * lagMeter ()
Returns a pointer to the current KviLagMeter.
KviIrcLink * link ()
Returns the underlying KviIrcLink object.
KviIrcConnectionNetsplitDetectorData * netsplitDetectorData ()
Returns a pointer to the KviIrcConnectionNetsplitDetectorData object.
KviNotifyListManager * notifyListManager ()
Returns a pointer to the current KviNotifyListManager.
KviPointerList< KviQueryWindow > * queryList ()
Returns the list of the currently open queries.
void registerChannel (KviChannelWindow *c)
void registerQuery (KviQueryWindow *q)
KviIrcConnectionRequestQueue * requestQueue ()
Returns a pointer to the current KviIrcConnectionRequestQueue.
void restartLagMeter ()
void resurrectDeadQueries ()
This is the inverse of keepQueriesOpenAfterDisconnect().
bool sendData (const char *pcBuffer, int iBuflen=-1)
Sends the specified text on the connected link (and thus socket).
bool sendFmtData (const char *pcFmt,...)
Sends the specified text on the connected link (and thus socket).
QTextCodec * serverCodec ()
Returns a pointer to the current global codec for inbound data.
KviIrcConnectionServerInfo * serverInfo ()
Returns a pointer to the KviIrcConnectionServerInfo object.
void setEncoding (const QString &szEncoding)
Sets the global encoding for this connection.
State state ()
Returns the current state of the connection.
KviIrcConnectionStateData * stateData ()
Returns a pointer to the KviIrcConnectionStateData object.
KviIrcConnectionStatistics * statistics ()
Returns a pointer to the KviIrcConnectionStatistics object.
KviIrcConnectionTarget * target ()
Returns the target of this connection.
QTextCodec * textCodec ()
Returns a pointer to the current global codec for outbound text.
void unregisterChannel (KviChannelWindow *c)
void unregisterQuery (KviQueryWindow *q)
KviIrcUserDataBase * userDataBase ()
Returns a pointer to the big connection user database.
KviIrcConnectionUserInfo * userInfo ()
Returns a pointer to the KviIrcConnectionUserInfo object.
Protected Member Functions
void abort ()
Kills any running connection or attempt.
void changeAwayState (bool bAway)
Called to update the away state.
bool changeUserMode (char cMode, bool bSet)
Called when MODE is received for each mode character.
void delayedStartNotifyList ()
Starts the notify list in 15 seconds.
void endInitialCapNegotiation ()
Called when we want to end CAP negotiation and go on wi the login.
void endOfMotdReceived ()
Called to start the notify lists when RPL_ENDOFMOTD is received.
void handleAuthenticate (KviCString &szResponse)
Called when AUTHENTICATE answer is received.
void handleFailedInitialCapLs ()
Called when CAP LS negotiation fails.
void handleInitialCapAck ()
Called when CAP ACK answer is received.
void handleInitialCapLs ()
Called when CAP LS answer is received.
void handleInitialCapNak ()
Called when CAP NAK answer is received.
void heartbeat (kvi_time_t tNow)
Called once in a while (every 5 secs at the moment)
KviIrcConnection (KviIrcContext *pContext, KviIrcConnectionTarget *pTarget, KviUserIdentity *pIdentity)
Creates a KviIrcConnection object.
void linkAttemptFailed (int iError)
This signals that the connection attempt has failed.
void linkEstabilished ()
Called by KviIrcLink when the socket state changes to Connected.
void linkTerminated ()
Called by KviIrcLink when the socket state changes to Ready.
void loginComplete (const QString &szNickName)
Called on the first numeric received from server.
void loginToIrcServer ()
Logins to the irc server.
void nickChange (const QString &szNewNick)
Called when NICK is received.
QString pickNextLoginNickName (bool bForceDefaultIfPrimaryNicknamesEmpty, const QString &szBaseNickForRandomChoices, QString &szChoiceDescriptionBuffer)
void resolveLocalHost ()
Resolves the localhost into an IP address.
void serverInfoReceived (const QString &szServerName, const QString &szUserModes, const QString &szChanModes)
Called when RPL_SERVINFO (004) is received and sets the info.
void start ()
This starts an asynchronous connection attempt.
void useProfileData (KviIdentityProfileSet *pSet, const QString &szNetwork)
Uses the profiles' data as connection data.
void useRealName (const QString &szRealName)
void userInfoReceived (const QString &szUserName, const QString &szHostName)
Called on each JOIN and sets the info.
~KviIrcConnection ()
Destroys a KviIrcConnection object. KviConsoleWindow uses this.
Private Slots
void hostNameLookupTerminated (KviDnsResolver *pDns)
Called when the hostname lookup is finished.
Private Member Functions
void setupSrvCodec ()
Setups the codec for the server.
void setupTextCodec ()
Setups the codec for the text.
Private Attributes
bool m_bIdentdAttached
State m_eState
KviIrcConnectionAntiCtcpFloodData * m_pAntiCtcpFloodData
KviIrcConnectionAsyncWhoisData * m_pAsyncWhoisData
KviPointerList
< KviChannelWindow > * m_pChannelList
KviConsoleWindow * m_pConsole
KviIrcContext * m_pContext
KviLagMeter * m_pLagMeter
KviIrcLink * m_pLink
KviDnsResolver * m_pLocalhostDns
KviIrcConnectionNetsplitDetectorData * m_pNetsplitDetectorData
KviNotifyListManager * m_pNotifyListManager
QTimer * m_pNotifyListTimer
KviPointerList< KviQueryWindow > * m_pQueryList
KviIrcConnectionRequestQueue * m_pRequestQueue
KviIrcConnectionServerInfo * m_pServerInfo
QTextCodec * m_pSrvCodec
KviIrcConnectionStateData * m_pStateData
KviIrcConnectionStatistics * m_pStatistics
KviIrcConnectionTarget * m_pTarget
QTextCodec * m_pTextCodec
KviIrcUserDataBase * m_pUserDataBase
KviUserIdentity * m_pUserIdentity
KviIrcConnectionUserInfo * m_pUserInfo
Friends
class KviConsoleWindow
class KviIrcContext
class KviIrcLink
class KviIrcServerParser
Detailed Description
An abstraction of a connection to an IRC server.
This class deals with the high-level logic of a connection to an IRC server. It's always attached to a KviIrcContext and thus to a KviConsoleWindow window. The connection has a KviIrcConnectionTarget object which specifies the data of the server that needs to be contacted and a KviUserIdentity object which specifies the user data to use.
The connection is the upper layer of the KVIrc networking stack. It owns KviIrcLink which is the layer immediately below and which in turn contains a KviIrcSocket.
The connection creates and manages a lot of objects that handle runtime information. These objects include a KviIrcConnectionUserInfo which contains the ACTUAL user information, KviIrcConnectionServerInfo which contains the ACTUAL server information, KviIrcUserDataBase which is substantially a big hash table containing all the users visible to KVIrc in this connection, a list of channels, a list of queries etc...
Member Enumeration Documentation
enum KviIrcConnection::State
The possible "high level" states of this connection.
Enumerator:
Idle
The connection is doing nothing
Connecting
A connection attempt is in progress
Connected
We're connected to an IRC server
Constructor & Destructor Documentation
KviIrcConnection::KviIrcConnection (KviIrcContext * pContext, KviIrcConnectionTarget * pTarget, KviUserIdentity * pIdentity) [protected]
Creates a KviIrcConnection object.
This is actually used only by KviConsoleWindow.
pContext must not be NULL and is kept as shallow pointer (that is, it's not owned and must persists for the entire life of KviIrcConnection: caller is responsable for that).
pTarget must not be NULL and must be allocated with new as this class takes the ownership.
pIdentity must not be NULL and must be allocated with new as this class takes the ownership.
Parameters:
pContext The KviIrcContext we're attacched to
pTarget The server data
pIdentity User information to use in ths connection
Returns:
KviIrcConnection
References KviIrcContext::console(), Idle, KviIrcLink, m_bIdentdAttached, m_eState, m_pAntiCtcpFloodData, m_pAsyncWhoisData, m_pChannelList, m_pConsole, m_pContext, m_pLagMeter, m_pLink, m_pLocalhostDns, m_pNetsplitDetectorData, m_pNotifyListManager, m_pNotifyListTimer, m_pQueryList, m_pRequestQueue, m_pServerInfo, m_pStateData, m_pStatistics, m_pTarget, m_pUserDataBase, m_pUserIdentity, m_pUserInfo, KviPointerList< T >::setAutoDelete(), setupSrvCodec(), and setupTextCodec().
KviIrcConnection::~KviIrcConnection () [protected]
Destroys a KviIrcConnection object. KviConsoleWindow uses this.
References KviMainWindow::executeInternalCommand(), g_pMainWindow, KviDnsResolver::isRunning(), KVI_INTERNALCOMMAND_IDENT_STOP, m_bIdentdAttached, m_pAntiCtcpFloodData, m_pAsyncWhoisData, m_pChannelList, m_pLagMeter, m_pLink, m_pLocalhostDns, m_pNetsplitDetectorData, m_pNotifyListManager, m_pNotifyListTimer, m_pQueryList, m_pRequestQueue, m_pServerInfo, m_pStateData, m_pStatistics, m_pTarget, m_pUserDataBase, m_pUserIdentity, and m_pUserInfo.
Member Function Documentation
void KviIrcConnection::abort () [protected]
Kills any running connection or attempt.
Returns:
void
References KviIrcLink::abort(), and m_pLink.
Referenced by KviIrcContext::terminateConnectionRequest().
KviIrcConnectionAntiCtcpFloodData* KviIrcConnection::antiCtcpFloodData () [inline]
Returns a pointer to the KviIrcConnectionAntiCtcpFloodData object.
It contains data private to the Anti CTCP Flood engine. Very similar to KviIrcConnectionStateData but dedicated to Ctcp flood. The returned pointer is never NULL. Include "KviIrcConnectionAntiCtcpFloodData.h" as the class is only forwarded here.
Returns:
KviIrcConnectionAntiCtcpFloodData *
Referenced by KviIrcServerParser::checkCtcpFlood().
KviIrcConnectionAsyncWhoisData* KviIrcConnection::asyncWhoisData () [inline]
Returns a pointer to the KviIrcConnectionAsyncWhoisData object.
It contains data private to the async whois engine. Very similar to KviIrcConnectionStateData but dedicated to async whois. The returned pointer is never NULL. Include "KviIrcConnectionAsyncWhoisData.h" as the class is only forwarded here.
Returns:
KviIrcConnectionAsyncWhoisData *
Referenced by KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), and KviIrcServerParser::parseNumericWhoisUser().
void KviIrcConnection::awayStateChanged () [signal]
Emitted when the away state changes.
Returns:
void
Referenced by changeAwayState().
void KviIrcConnection::changeAwayState (bool bAway) [protected]
Called to update the away state.
Parameters:
bAway Whether we enter the away mode
Returns:
void
References awayStateChanged(), KviMainWindow::childConnectionAwayStateChange(), KviWindow::frame(), m_pConsole, m_pUserInfo, KviIrcConnectionUserInfo::setAway(), KviIrcConnectionUserInfo::setBack(), and KviWindow::updateCaption().
Referenced by KviIrcServerParser::parseNumericAway(), and KviIrcServerParser::parseNumericBackFromAway().
bool KviIrcConnection::changeUserMode (char cMode, bool bSet) [protected]
Called when MODE is received for each mode character.
Parameters:
cMode The mode flag :)
bSet Whether to set the mode
Returns:
bool
References KviIrcConnectionUserInfo::addUserMode(), KviMainWindow::childConnectionUserModeChange(), console(), KviWindow::frame(), KviIrcConnectionUserInfo::hasUserMode(), m_pConsole, m_pUserInfo, KviIrcConnectionUserInfo::removeUserMode(), KviWindow::updateCaption(), and userModeChanged().
Referenced by KviIrcServerParser::parseUserMode().
void KviIrcConnection::chanListChanged () [signal]
Emitted when the channels list change.
Returns:
void
Referenced by registerChannel(), and unregisterChannel().
KviPointerList<KviChannelWindow>* KviIrcConnection::channelList () [inline]
Returns the list of the channels bound to the current connection.
The pointer itself is never null (though the list may be empty).
Returns:
KviPointerList<KviChannelWindow> *
Referenced by KviConsoleWindow::avatarChangedUpdateWindows(), KviIrcContext::connectionTerminated(), KviConsoleWindow::getWindowListTipText(), KviIsOnNotifyListManager::handleIsOn(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralQuit(), KviIrcUrl::run(), and KviConsoleWindow::updateUri().
void KviIrcConnection::channelRegistered (KviChannelWindow * pChan) [signal]
Emitted when we register a channel.
Parameters:
pChan The channel :)
Returns:
void
Referenced by registerChannel().
void KviIrcConnection::channelUnregistered (KviChannelWindow * pChan) [signal]
Emitted when we unregister a channel.
Parameters:
pChan The channel :)
Returns:
void
Referenced by unregisterChannel().
void KviIrcConnection::clearOutputQueue (bool bPrivateMessagesOnly)
Clears the underlying output queue. Exposed basically for /context.clearQueue You shouldn't need it for any other reason :)
References KviIrcLink::clearOutputQueue(), and m_pLink.
Referenced by context_kvs_cmd_clearQueue().
void KviIrcConnection::closeAllChannels ()
Closes all the currently open channels not marked as dead.
Returns:
void
References KviPointerList< T >::first(), and m_pChannelList.
Referenced by KviIrcContext::destroyConnection().
void KviIrcConnection::closeAllQueries ()
Closes all the currently open queries not marked as dead.
Returns:
void
References KviPointerList< T >::first(), and m_pQueryList.
Referenced by KviIrcContext::destroyConnection().
KviConsoleWindow* KviIrcConnection::console () [inline]
Returns a pointer to the owning console.
The pointer is never NULL
Returns:
KviConsoleWindow *
Referenced by changeUserMode(), heartbeat(), KviIrcConnectionTargetResolver::KviIrcConnectionTargetResolver(), KviIrcLink::KviIrcLink(), KviIrcMessage::KviIrcMessage(), KviNotifyListManager::KviNotifyListManager(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviLagMeter::lagCheckRegister(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviAsyncAvatarSelectionDialog::okClicked(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviLagMeter::timerEvent(), and useRealName().
KviIrcContext* KviIrcConnection::context () [inline]
Returns a pointer to the owning KviIrcContext.
The returned value is never NULL
Returns:
KviIrcContext *
Referenced by KviMainWindow::childConnectionAwayStateChange(), KviMainWindow::childConnectionLagChange(), KviMainWindow::childConnectionNickNameChange(), KviMainWindow::childConnectionServerInfoChange(), KviMainWindow::childConnectionUserModeChange(), incomingMessage(), linkAttemptFailed(), linkEstabilished(), linkTerminated(), loginComplete(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), sendData(), and sendFmtData().
KviChannelWindow * KviIrcConnection::createChannel (const QString & szName)
Creates a new channel with the specified name.
This should be called in response to a JOIN message. This function _assumes_ that such a channel doesn't exist yet (or if it exists then it's actually in DEAD state). You can assume that channel creation never fails: if the returned pointer is NULL then we're screwed anyway as virtual memory is exausted.
Parameters:
szName The name of the channel
Returns:
KviChannelWindow *
References KviMainWindow::addWindow(), c, KviIrcContext::findDeadChannel(), KviWindow::frame(), KVI_OPTION_BOOL, KviOption_boolCreateMinimizedChannels, KviOption_boolPasteLastLogOnChannelJoin, m_pConsole, m_pContext, KviChannelWindow::pasteLastLog(), KviChannelWindow::setAliveChan(), and KviWindow::setFocus().
Referenced by KviIrcServerParser::parseLiteralJoin().
KviQueryWindow * KviIrcConnection::createQuery (const QString & szNick)
Creates a query with the specified nick as target.
This function assumes that such a query doesn't exist yet (or if it exists it's actually marked as dead and needs to be resurrected).
Parameters:
szNick The nickname of the user
Returns:
KviQueryWindow *
References KviMainWindow::addWindow(), KviIrcContext::findDeadQuery(), findQuery(), KviWindow::frame(), KVI_OPTION_BOOL, KviOption_boolCreateMinimizedQuery, m_pConsole, m_pContext, q, KviQueryWindow::setAliveQuery(), and KviWindow::setFocus().
Referenced by loginComplete(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
const QString & KviIrcConnection::currentNetworkName ()
Helper that provides a shortcut for really common access to serverInfo()->networkName()
Returns:
const QString &
References m_pServerInfo, and KviIrcConnectionServerInfo::networkName().
Referenced by KviWindowListBase::getTextForConsole(), and KviStatusBar::mouseDoubleClickEvent().
const QString & KviIrcConnection::currentNickName ()
Helper that provides a shortcut for really common access to userInfo()->nickName()
Returns:
const QString &
References KviIrcConnectionUserInfo::nickName(), and userInfo().
Referenced by avatar_kvs_cmd_notify(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KviUserListEntry::color(), KviIrcContextDisplay::drawContents(), KviQueryWindow::fillCaptionBuffers(), KviChannelWindow::fillCaptionBuffers(), KviApplication::fillRecentNicknamesPopup(), KviIrcView::getTextLine(), KviChannelWindow::ownAction(), KviUserListViewArea::paintEvent(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseNumericCodePageSet(), KviStatusBar::setPermanentMessage(), KviWatchNotifyListManager::start(), KviStupidNotifyListManager::start(), KviIsOnNotifyListManager::start(), KviWatchNotifyListManager::stop(), KviStupidNotifyListManager::stop(), and KviIsOnNotifyListManager::stop().
const QString & KviIrcConnection::currentServerName ()
Helper that provides a shortcut for really common access to serverInfo()->name()
Returns:
const QString &
References KviIrcConnectionServerInfo::name(), and serverInfo().
Referenced by ListWindow::connectionStateChange(), LinksWindow::connectionStateChange(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcContextDisplay::drawContents(), KviQueryWindow::fillCaptionBuffers(), KviChannelWindow::fillCaptionBuffers(), KviWindowListBase::getTextForConsole(), KviStatusBar::mouseDoubleClickEvent(), KviIrcServerParser::parseLiteralNotice(), KviIrcMessage::safePrefix(), KviStatusBar::setPermanentMessage(), and KviIrcContextDisplay::tipRequest().
const QString & KviIrcConnection::currentUserName ()
Helper that provides a shortcut for really common access to userInfo()->userName()
Returns:
const QString &
References userInfo(), and KviIrcConnectionUserInfo::userName().
QString KviIrcConnection::decodeText (const char * szText)
Decodes the specified text by using the server codec.
You should first attempt to decode the text by using the window codec (if you belong to a window).
Parameters:
szText The text to decode
Returns:
QString
References m_pSrvCodec.
Referenced by KviIrcMessage::decodeAndSplitMask(), KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviWatchNotifyListManager::handleWatchReply(), KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCommandEndOfHelp(), KviIrcServerParser::parseCommandHelp(), KviIrcServerParser::parseCommandSyntaxHelp(), KviIrcServerParser::parseCtcpReply(), KviIrcServerParser::parseCtcpRequest(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseCtcpRequestPage(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralError(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericCommandSyntax(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfStats(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericInfo(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericMotd(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericNoSuchChannel(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericServerAdminInfoAdminContact(), KviIrcServerParser::parseNumericServerAdminInfoAdminName(), KviIrcServerParser::parseNumericServerAdminInfoServerName(), KviIrcServerParser::parseNumericServerAdminInfoTitle(), KviIrcServerParser::parseNumericStats(), KviIrcServerParser::parseNumericTime(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericUnavailResource(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhowasUser(), and ListWindow::processData().
void KviIrcConnection::delayedStartNotifyList () [protected]
Starts the notify list in 15 seconds.
We have this delay to wait an eventual RPL_PROTOCTL from the server telling us that the WATCH notify list method is supported
Returns:
void
References connect(), KVI_ASSERT, m_pNotifyListTimer, and restartNotifyList().
Referenced by loginComplete().
QByteArray KviIrcConnection::encodeText (const QString & szText)
Encodes the specified text by using the local text codec.
You should first attempt to encode the text by using the window codec (if you belong to a window).
Parameters:
szText The text to encode
Returns:
QByteArray
References m_pSrvCodec.
Referenced by KviMaskInputDialog::accept(), avatar_kvs_cmd_notify(), avatar_kvs_cmd_query(), KviChannelWindow::closeEvent(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), DccChatWindow::connectionInProgress(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_module_reply_errmsg(), dccModuleParseDccGet(), TrayIcon::doAway(), DccFileTransfer::doResume(), KviKvsTreeNodeAliasSimpleCommand::execute(), handleAuthenticate(), DccBroker::handleResumeRequest(), heartbeat(), ListWindow::itemDoubleClicked(), KviKvsCoreSimpleCommands::KVSCSC(), loginComplete(), loginToIrcServer(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpRequestPing(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLoginNicknameProblem(), KviUserInput::parseNonCommand(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviChannelWindow::removeMasks(), KviIrcServerParser::replyCtcp(), ListWindow::requestList(), DccBroker::rsendExecute(), KviIrcUrl::run(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), KviChannelWindow::setAliveChan(), KviChannelWindow::setMode(), KviWatchNotifyListManager::start(), DccFileTransfer::startConnection(), KviIrcContext::terminateConnectionRequest(), KviLagMeter::timerEvent(), KviIrcConnectionRequestQueue::timerSlot(), KviChannelWindow::toggleListModeEditor(), and KviChannelWindow::topicSelected().
void KviIrcConnection::endInitialCapNegotiation () [protected]
Called when we want to end CAP negotiation and go on wi the login.
Returns:
void
References loginToIrcServer(), m_pStateData, sendFmtData(), and KviIrcConnectionStateData::setInsideAuthenticate().
Referenced by handleInitialCapAck(), handleInitialCapLs(), handleInitialCapNak(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), and KviIrcServerParser::parseNumericSaslSuccess().
void KviIrcConnection::endOfMotdReceived () [protected]
Called to start the notify lists when RPL_ENDOFMOTD is received.
Returns:
void
References m_pNotifyListTimer, and restartNotifyList().
Referenced by KviIrcServerParser::parseNumericMotd().
KviChannelWindow * KviIrcConnection::findChannel (const QString & szName)
Finds the channel with the specified unicode name.
Returns the pointer to the channel found or NULL if there is no such channel.
Parameters:
szName The name of the channel
Returns:
KviChannelWindow *
References c, KviQString::equalCI(), KviPointerList< T >::first(), m_pChannelList, and KviPointerList< T >::next().
Referenced by KviIrcView::doLinkToolTip(), KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), KviApplication::fillRecentChannelsPopup(), KviKvsCoreFunctions::KVSCF(), KviIrcServerParser::otherChannelError(), KviIrcServerParser::parseChannelHelp(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralTopic(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericCannotSend(), KviIrcServerParser::parseNumericCannotSendColor(), KviIrcServerParser::parseNumericCantJoinChannel(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericInviting(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), and KviIrcServerParser::parseNumericWhoReply().
KviQueryWindow * KviIrcConnection::findQuery (const QString & szNick)
Finds the query with the specified nick.
Returns the pointer to the query found or NULL if there is no such query.
Parameters:
szNick The nickname of the user
Returns:
KviQueryWindow *
References c, KviQString::equalCI(), KviPointerList< T >::first(), m_pQueryList, and KviPointerList< T >::next().
Referenced by createQuery(), KviKvsCoreFunctions::KVSCF(), loginComplete(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPart(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralQuit(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), and KviIrcServerParser::parseNumericWhoReply().
int KviIrcConnection::getCommonChannels (const QString & szNick, QString & szChansBuffer, bool bAddEscapeSequences = true)
Returns a list of channels bound to the current connection.
This is actually the list of channels that the local user has in common with the specified user. The list is returned as a comma separated string. If bAddEscapeSequences is true, then the string includes special escape sequences for KviIrcView that will make the channel names clickable.
Returns the number of channels found.
Parameters:
szNick The nickname of the user
szChansBuffer The buffer where to store data
bAddEscapeSequences Whether to include escape sequences
Returns:
int
References KviQString::appendFormatted(), c, KviPointerList< T >::first(), m_pChannelList, and KviPointerList< T >::next().
Referenced by chan_kvs_fnc_common(), KviQueryWindow::getInfoLabelText(), KviQueryWindow::getInfoLabelTipText(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralPart(), and KviQueryWindow::setTarget().
void KviIrcConnection::handleAuthenticate (KviCString & szResponse) [protected]
Called when AUTHENTICATE answer is received.
Returns:
void
References KviSASL::dh_blowfishMethod(), encodeText(), KviIrcConnectionStateData::isInsideAuthenticate(), m_pStateData, KviSASL::plainMethod(), KviCString::ptr(), sendFmtData(), and target().
Referenced by KviIrcServerParser::parseLiteralAuthenticate().
void KviIrcConnection::handleFailedInitialCapLs () [protected]
Called when CAP LS negotiation fails.
Returns:
void
References loginToIrcServer(), m_pStateData, and KviIrcConnectionStateData::setInsideInitialCapLs().
Referenced by KviIrcServerParser::parseNumericNotRegistered().
void KviIrcConnection::handleInitialCapAck () [protected]
Called when CAP ACK answer is received.
Returns:
void
References KviIrcConnectionStateData::enabledCaps(), endInitialCapNegotiation(), KviIrcConnectionStateData::isInsideInitialCapReq(), KVI_OPTION_BOOL, KviOption_boolUseSaslIfAvailable, m_pStateData, sendFmtData(), KviIrcConnectionStateData::setInsideAuthenticate(), KviIrcConnectionStateData::setInsideInitialCapReq(), and target().
Referenced by KviIrcServerParser::parseLiteralCap().
void KviIrcConnection::handleInitialCapLs () [protected]
Called when CAP LS answer is received.
Returns:
void
References endInitialCapNegotiation(), KviIrcConnectionStateData::isInsideInitialCapLs(), KVI_OPTION_BOOL, KviOption_boolUseSaslIfAvailable, KviOption_boolUseStartTlsIfAvailable, link(), m_pStateData, sendFmtData(), serverInfo(), KviIrcConnectionStateData::setInsideInitialCapLs(), KviIrcConnectionStateData::setInsideInitialCapReq(), and target().
Referenced by KviIrcServerParser::parseLiteralCap().
void KviIrcConnection::handleInitialCapNak () [protected]
Called when CAP NAK answer is received.
Returns:
void
References endInitialCapNegotiation().
Referenced by KviIrcServerParser::parseLiteralCap().
void KviIrcConnection::heartbeat (kvi_time_t tNow) [protected]
Called once in a while (every 5 secs at the moment)
Parameters:
tNow The current time
Returns:
void
References __tr2qs, _OUTPUT_PARANOIC, Connected, console(), encodeText(), KviPointerList< T >::first(), KviCString::Format, KVI_OPTION_BOOL, KVI_OUT_VERBOSE, kvi_time_t, KviOption_boolEnableAwayListUpdates, KviLagMeter::lagCheckRegister(), lagMeter(), KviChannelWindow::lastReceivedWhoReply(), m_eState, m_pChannelList, KviPointerList< T >::next(), KviWindow::output(), sendFmtData(), KviIrcConnectionStateData::setLastSentChannelWhoRequest(), KviChannelWindow::setSentSyncWhoRequest(), stateData(), and KviWindow::windowName().
Referenced by KviIrcContext::timerEvent().
void KviIrcConnection::hostNameLookupTerminated (KviDnsResolver * pDns) [private, slot]
Called when the hostname lookup is finished.
Returns:
void
References __tr2qs, KviDnsResolver::error(), KviDnsResolver::firstIpAddress(), KviError::getDescription(), KviIrcConnectionUserInfo::hostIp(), KVI_OUT_SYSTEMMESSAGE, m_pConsole, m_pLocalhostDns, m_pUserInfo, KviWindow::output(), KviIrcConnectionUserInfo::setHostIp(), KviDnsResolver::state(), and KviError::Success.
Referenced by userInfoReceived().
void KviIrcConnection::incomingMessage (const char * pcMessage)
This function is part of the networking stack.
It's called by KviIrcLink OR KviMexLinkFilter when a message is arriving from the server. Needs to be public because subclasses of KviMexLinkFilter may call it.
Parameters:
pcMessage The message :)
Returns:
void
References context(), g_pServerParser, kvi_unixTime, l, m, m_pStatistics, KviIrcServerParser::parseMessage(), and KviIrcConnectionStatistics::setLastMessageTime().
Referenced by KviIrcLink::processData().
void KviIrcConnection::incomingMessageNoFilter (const char * pcMessage)
This function is part of the networking stack.
It's called by KviIrcDataStreamMonitor subclasses when they want to inject some message without getting it filtered again
Parameters:
pcMessage The message :)
Returns:
void
References g_pServerParser, kvi_unixTime, m_pStatistics, KviIrcServerParser::parseMessage(), and KviIrcConnectionStatistics::setLastMessageTime().
void KviIrcConnection::keepChannelsOpenAfterDisconnect ()
Marks all the currently existing channels as DEAD.
They are preserved across connections. Marking a channel as dead actually removes the ownership of KviChannelWindow from KviIrcConnection and moves it to KviIrcContext (as the contex is preserved across connections).
Returns:
void
References __tr2qs, c, KviPointerList< T >::first(), KVI_OUT_SOCKETERROR, and m_pChannelList.
Referenced by KviIrcContext::connectionTerminated().
void KviIrcConnection::keepQueriesOpenAfterDisconnect ()
Marks all the currently open queries as DEAD.
They are kept open after a disconnect. Marking a query as dead removes ownership from this class and gives it to KviIrcContext (which survives disconnects).
Returns:
void
References __tr2qs, KviPointerList< T >::first(), KVI_OUT_SOCKETERROR, m_pQueryList, and q.
Referenced by KviIrcContext::connectionTerminated().
KviLagMeter* KviIrcConnection::lagMeter () [inline]
Returns a pointer to the current KviLagMeter.
The returned pointer is NULL if lag measurement is disabled for the current connection.
Returns:
KviLagMeter *
Referenced by KviIrcContextDisplay::drawContents(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), heartbeat(), KviStatusBarLagIndicator::mouseDoubleClickEvent(), KviIrcServerParser::parseCtcpReplyLagcheck(), KviIrcServerParser::parseLiteralPong(), KviIrcServerParser::parseNumericEndOfWho(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), KviStupidNotifyListManager::stop(), KviIsOnNotifyListManager::stop(), KviIrcConnectionRequestQueue::timerSlot(), KviIrcContextDisplay::tipRequest(), KviStatusBarLagIndicator::tipText(), and KviStatusBarLagIndicator::updateDisplay().
KviIrcLink* KviIrcConnection::link () [inline]
Returns the underlying KviIrcLink object.
The returned pointer is never NULL.
Returns:
KviIrcLink *
Referenced by dcc_kvs_get_listen_ip_address(), handleInitialCapLs(), and resolveLocalHost().
void KviIrcConnection::linkAttemptFailed (int iError) [protected]
This signals that the connection attempt has failed.
Parameters:
iError The error code
Returns:
void
References KviIrcContext::connectionFailed(), context(), KviMainWindow::executeInternalCommand(), g_pMainWindow, Idle, KVI_INTERNALCOMMAND_IDENT_STOP, m_bIdentdAttached, and m_eState.
Referenced by KviIrcLink::resolverTerminated(), and KviIrcLink::socketStateChange().
void KviIrcConnection::linkEstabilished () [protected]
Called by KviIrcLink when the socket state changes to Connected.
Returns:
void
References Connected, KviIrcContext::connectionEstabilished(), context(), kvi_unixTime, l, loginToIrcServer(), m, m_eState, m_pServerInfo, m_pStateData, m_pStatistics, KviOsInfo::name(), resolveLocalHost(), sendFmtData(), KviIrcConnectionStatistics::setConnectionStartTime(), KviIrcConnectionStateData::setIgnoreOneYouHaveNotRegisteredError(), KviIrcConnectionStateData::setInsideInitialCapLs(), KviIrcConnectionStatistics::setLastMessageTime(), KviIrcConnectionServerInfo::setName(), KviIrcConnectionServerInfo::setNetworkName(), and target().
Referenced by KviIrcLink::socketStateChange().
void KviIrcConnection::linkTerminated () [protected]
Called by KviIrcLink when the socket state changes to Ready.
Returns:
void
References KviIrcContext::connectionTerminated(), context(), KviMainWindow::executeInternalCommand(), g_pMainWindow, Idle, KVI_INTERNALCOMMAND_IDENT_STOP, l, m, m_bIdentdAttached, m_eState, m_pLagMeter, and m_pNotifyListManager.
Referenced by KviIrcLink::socketStateChange().
void KviIrcConnection::loginComplete (const QString & szNickName) [protected]
Called on the first numeric received from server.
Parameters:
szNickName The nickname to use
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, KviApplication::addRecentNickname(), KviIrcServer::autoJoinChannelList(), KviIrcNetwork::autoJoinChannelList(), KviWindow::autoRaise(), KviIrcServer::clearReconnectInfo(), KviIrcConnectionStateData::commandToExecAfterConnect(), KviIrcContext::Connected, context(), createQuery(), delayedStartNotifyList(), e, encodeText(), KviMainWindow::executeInternalCommand(), KviIrcUserDataBase::find(), findQuery(), KviWindow::frame(), g_pApp, g_pMainWindow, KviIrcUserEntry::host(), KviIrcServer::initUMode(), KVI_INTERNALCOMMAND_CHANNELSJOIN_OPEN, KVI_INTERNALCOMMAND_IDENT_STOP, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_IRC, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_VERBOSE, KviEvent_OnIRC, KviOption_boolMinimizeConsoleAfterConnect, KviOption_boolShowChannelsJoinOnIrc, KviOption_stringDefaultUserMode, KVS_TRIGGER_EVENT_0_HALTED, l, KviIrcContext::loginComplete(), m_bIdentdAttached, m_pConsole, m_pStateData, m_pUserIdentity, m_pUserInfo, KviIrcServerReconnectInfo::m_szJoinChannels, KviIrcServerReconnectInfo::m_szOpenQueryes, KviWindow::minimize(), KviIrcConnectionTarget::network(), KviUserListView::nickChange(), KviIrcConnectionUserInfo::nickName(), KviConsoleWindow::notifyListView(), KviUserIdentity::onLoginCommand(), KviIrcServer::onLoginCommand(), KviIrcNetwork::onLoginCommand(), KviWindow::output(), KviWindow::outputNoFmt(), KviCString::ptr(), KviIrcServer::reconnectInfo(), restartLagMeter(), resurrectDeadQueries(), KviIrcUrl::run(), sendFmtData(), KviIrcConnectionTarget::server(), KviWindow::setFocus(), KviIrcConnectionStateData::setIgnoreOneYouHaveNotRegisteredError(), KviIrcConnectionUserInfo::setNickName(), KviQueryWindow::setTarget(), state(), szHost, target(), KviIrcUserEntry::user(), and userDataBase().
Referenced by KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumeric002(), KviIrcServerParser::parseNumeric003(), KviIrcServerParser::parseNumeric004(), and KviIrcServerParser::parseNumeric005().
void KviIrcConnection::loginToIrcServer () [protected]
Logins to the irc server.
Returns:
void
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_VERBOSE, KviIrcUserEntry::avatar(), KviUserListView::avatarChanged(), KviConsoleWindow::defaultAvatarFromOptions(), e, encodeText(), KviIrcUserEntry::Female, KviIrcUserDataBase::find(), KviIrcServer::hostName(), KviIdentityProfileSet::instance(), KviIdentityProfileSet::isEmpty(), KviIdentityProfileSet::isEnabled(), KviUserListView::join(), KVI_ASSERT, KVI_DEFAULT_USERNAME, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_VERBOSE, KviOption_boolPrependAvatarInfoToRealname, KviOption_boolPrependGenderInfoToRealname, KviOption_boolPrependNickColorInfoToRealname, KviOption_boolUseSpecifiedSmartColorForOwnNick, KviOption_stringCtcpUserInfoGender, KviOption_stringMyAvatar, KviOption_stringRealname, KviOption_stringUsername, KviOption_uintUserIrcViewOwnBackground, KviOption_uintUserIrcViewOwnForeground, m_pConsole, m_pServerInfo, m_pStateData, m_pUserIdentity, m_pUserInfo, KviIrcServerReconnectInfo::m_szNick, KviIrcServerReconnectInfo::m_szPass, KviIrcUserEntry::Male, KviIrcNetwork::name(), KviIrcConnectionTarget::network(), KviIrcConnectionUserInfo::nickName(), KviConsoleWindow::notifyListView(), KviUserIdentity::onConnectCommand(), KviIrcServer::onConnectCommand(), KviIrcNetwork::onConnectCommand(), KviWindow::output(), KviWindow::outputNoFmt(), KviIrcConnectionUserInfo::password(), KviIrcNetwork::password(), KviIrcServer::password(), pickNextLoginNickName(), KviIrcConnectionUserInfo::realName(), KviIrcNetwork::realName(), KviIrcServer::realName(), KviIrcServer::reconnectInfo(), KviMircCntrl::Reset, KviIrcUrl::run(), sendFmtData(), KviIrcConnectionTarget::server(), KviIrcUserEntry::setAvatar(), KviIrcUserEntry::setGender(), KviIrcConnectionStateData::setLoginNickNameState(), KviIrcConnectionServerInfo::setName(), KviIrcConnectionUserInfo::setNickName(), KviIrcConnectionUserInfo::setPassword(), setupTextCodec(), KviIrcConnectionUserInfo::setUserName(), target(), KviIrcConnectionStateData::UsedConnectionSpecificNickName, useProfileData(), userDataBase(), useRealName(), userInfo(), KviIrcConnectionUserInfo::userName(), KviIrcNetwork::userName(), and KviIrcServer::userName().
Referenced by endInitialCapNegotiation(), handleFailedInitialCapLs(), and linkEstabilished().
KviIrcConnectionNetsplitDetectorData* KviIrcConnection::netsplitDetectorData () [inline]
Returns a pointer to the KviIrcConnectionNetsplitDetectorData object.
It contains data private to the netsplit detector engine. Very similar to KviIrcConnectionStateData but dedicated to netsplit detection. The returned pointer is never NULL. Include "KviIrcConnectionNetsplitDetectorData.h" as the class is only forwarded here.
Returns:
KviIrcConnectionNetsplitDetectorData *
Referenced by KviIrcServerParser::parseLiteralQuit().
void KviIrcConnection::nickChange (const QString & szNewNick) [protected]
Called when NICK is received.
Parameters:
szNewNick The new nickname for the user
Returns:
void
References __tr2qs, KviApplication::addRecentNickname(), KviMainWindow::childConnectionNickNameChange(), KviWindow::frame(), g_pApp, KVI_OUT_NICK, m_pConsole, m_pUserInfo, KviUserListView::nickChange(), KviIrcConnectionUserInfo::nickName(), nickNameChanged(), KviConsoleWindow::notifyListView(), KviWindow::output(), KviIrcConnectionUserInfo::setNickName(), and KviWindow::updateCaption().
Referenced by KviIrcServerParser::parseLiteralNick().
void KviIrcConnection::nickNameChanged () [signal]
Emitted when the nickname changes.
Returns:
void
Referenced by nickChange().
KviNotifyListManager* KviIrcConnection::notifyListManager () [inline]
Returns a pointer to the current KviNotifyListManager.
The returned pointer is NULL if notify list management is disabled for the current connection.
Returns:
KviNotifyListManager *
Referenced by KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericUserhost(), and KviIrcServerParser::parseNumericWatch().
QString KviIrcConnection::pickNextLoginNickName (bool bForceDefaultIfPrimaryNicknamesEmpty, const QString & szBaseNickForRandomChoices, QString & szChoiceDescriptionBuffer) [protected]
Picks the next login nickname to be tried. If bForceDefaultIfPrimaryNicknamesEmpty is true then the algorithm will return a default nickname in case the primary setting in the options is empty. If bForceDefaultIfPrimaryNicknamesEmpty is false then the algorithm will try the alternative nicknames instead, then try some random options and finally return an empty string signaling that no suitable choice could be made. bForceDefaultIfPrimaryNicknamesEmpty should be set to true only in loginToIrcServer(), that is, the first time this function is called (otherwise there exists a possibility of infinite nickname loop because of the repeated fallback choice). szBaseNickForRandomChoices will be used for the random alternatives as the first left 7 characters. Upon return szChoiceDescriptionBuffer will contain the textual description of the choice made (network specific, alternative, server specific, global etc...).
References __tr2qs, KviIrcNetwork::alternativeNickName(), KviIrcServer::alternativeNickName(), KviIdentityProfileSet::findNetwork(), KviIdentityProfileSet::instance(), KviIdentityProfileSet::isEmpty(), KviIdentityProfileSet::isEnabled(), KVI_ASSERT, KVI_DEFAULT_NICKNAME1, KVI_OPTION_STRING, KviOption_stringNickname1, KviOption_stringNickname2, KviOption_stringNickname3, KviOption_stringNickname4, KviIrcConnectionStateData::loginNickNameState(), m_pStateData, KviIrcNetwork::name(), KviIrcConnectionTarget::network(), KviIdentityProfile::nick(), KviIrcNetwork::nickName(), KviIrcServer::nickName(), KviIrcConnectionTarget::server(), KviIrcConnectionStateData::setLoginNickNameState(), target(), KviIrcConnectionStateData::UsedAlternativeNetworkSpecificNickName, KviIrcConnectionStateData::UsedAlternativeProfileSpecificNickName, KviIrcConnectionStateData::UsedAlternativeServerSpecificNickName, KviIrcConnectionStateData::UsedGlobalNickName1, KviIrcConnectionStateData::UsedGlobalNickName2, KviIrcConnectionStateData::UsedGlobalNickName3, KviIrcConnectionStateData::UsedGlobalNickName4, KviIrcConnectionStateData::UsedManualNickname, KviIrcConnectionStateData::UsedNetworkSpecificNickName, KviIrcConnectionStateData::UsedProfileSpecificNickName, KviIrcConnectionStateData::UsedRandomNickName1, KviIrcConnectionStateData::UsedRandomNickName2, KviIrcConnectionStateData::UsedRandomNickName3, KviIrcConnectionStateData::UsedRandomNickName4, and KviIrcConnectionStateData::UsedServerSpecificNickName.
Referenced by loginToIrcServer(), and KviIrcServerParser::parseLoginNicknameProblem().
KviPointerList<KviQueryWindow>* KviIrcConnection::queryList () [inline]
Returns the list of the currently open queries.
The returned pointer is never NULL (the list may be empty though).
Returns:
KviPointerList<KviQueryWindow> *
Referenced by KviConsoleWindow::avatarChangedUpdateWindows(), KviIrcContext::connectionTerminated(), KviConsoleWindow::getWindowListTipText(), and KviIrcServerParser::parseLiteralNick().
void KviIrcConnection::registerChannel (KviChannelWindow * c)
This is called by KviChannelWindow upon creation. You shouldn't need to call it.
FIXME: Could be made protected.
References KviApplication::addRecentChannel(), KviPointerList< T >::append(), chanListChanged(), channelRegistered(), g_pApp, KVI_OPTION_BOOL, KviOption_boolLogChannelHistory, m_pChannelList, m_pServerInfo, KviIrcConnectionServerInfo::networkName(), and KviWindow::windowName().
Referenced by KviChannelWindow::KviChannelWindow(), and KviChannelWindow::setAliveChan().
void KviIrcConnection::registerQuery (KviQueryWindow * q)
This is called by KviQueryWindow upon creation, you shouldn't need to use it.
FIXME: Could be made protected.
References KviPointerList< T >::append(), and m_pQueryList.
Referenced by KviQueryWindow::KviQueryWindow(), and KviQueryWindow::setAliveQuery().
KviIrcConnectionRequestQueue* KviIrcConnection::requestQueue () [inline]
Returns a pointer to the current KviIrcConnectionRequestQueue.
Returns:
KviIrcConnectionRequestQueue *
Referenced by KviIrcContext::connectionTerminated(), KviIrcServerParser::parseLiteralJoin(), and unregisterChannel().
void KviIrcConnection::resolveLocalHost () [protected]
Resolves the localhost into an IP address.
Returns:
void
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, KviNetUtils::isValidStringIp(), KVI_OPTION_STRING, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviOption_stringLocalHostIp, link(), KviIrcConnectionUserInfo::localHostIp(), m_pConsole, m_pUserInfo, KviWindow::output(), KviIrcConnectionUserInfo::setHostIp(), KviIrcConnectionUserInfo::setHostName(), KviIrcConnectionUserInfo::setLocalHostIp(), and target().
Referenced by linkEstabilished().
void KviIrcConnection::restartLagMeter ()
This function actually restarts the lag meter.
FIXME: Why ?
References KVI_OPTION_BOOL, KviOption_boolUseLagMeterEngine, and m_pLagMeter.
Referenced by loginComplete().
void KviIrcConnection::restartNotifyList () [slot]
Called to restart the notify list.
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, KVI_OPTION_BOOL, KVI_OUT_VERBOSE, KviOption_boolUseIntelligentNotifyListManager, KviOption_boolUseNotifyList, KviOption_boolUseWatchListIfAvailable, m_pConsole, m_pNotifyListManager, m_pNotifyListTimer, KviWindow::output(), serverInfo(), KviNotifyListManager::start(), and KviNotifyListManager::stop().
Referenced by delayedStartNotifyList(), and endOfMotdReceived().
void KviIrcConnection::resurrectDeadQueries ()
This is the inverse of keepQueriesOpenAfterDisconnect().
It's meant to be called upon reconnection (as queries don't need a JOIN message to be opened).
Returns:
void
References __tr2qs, KviIrcContext::firstDeadQuery(), KVI_OUT_SOCKETMESSAGE, m_pContext, and q.
Referenced by loginComplete().
bool KviIrcConnection::sendData (const char * pcBuffer, int iBuflen = -1)
Sends the specified text on the connected link (and thus socket).
This function basically works like sprintf(). Please note that you should send only ENCODED text to the server. This is why the accepted parameter is a const char *. IRC is an 8 (I'd say even 7 sometimes) bit protocol.
Please note that you don't actually need to append a CRLF pair to your buffer: the implementation of the networking stack will do it for you. Hovewer you can send multiple IRC commands by separating them by CRLF pairs. Just take care of avoiding a CRLF after the last command you specify.
Returns true on success or false if the data can't be actually enqueued/sent (and this usually means that there is no connection at the moment). Please note that it MAY happen that a send attempt on a correctly connected link causes the link to actually disconnect (or rather "discover" the fact that it's disconnected at OS level).
Parameters:
pcBuffer The _encoded_ text data to send
iBuflen The length of the data: if -1 the length is determined via strlen().
Returns:
bool
References __tr2qs, _OUTPUT_MUTE, KviConsoleWindow::activeWindow(), context(), KviDataBuffer::data(), KVI_OUT_SOCKETWARNING, KviEvent_OnOutboundTraffic, KVS_TRIGGER_EVENT_1, l, m, m_pConsole, m_pLink, KviMemory::move(), KviWindow::outputNoFmt(), and KviIrcLink::sendPacket().
Referenced by DccChatWindow::connectionInProgress(), KviKvsTreeNodeAliasSimpleCommand::execute(), LinksWindow::hostPopupClicked(), and KviIrcUrl::run().
bool KviIrcConnection::sendFmtData (const char * pcFmt, ...)
Sends the specified text on the connected link (and thus socket).
This function basically works like sprintf(). Please note that you should send only ENCODED text to the server. This is why the accepted parameter is a const char *. IRC is an 8 (I'd say even 7 sometimes) bit protocol.
Please note that you don't actually need to append a CRLF pair to your buffer: the implementation of the networking stack will do it for you. Hovewer you can send multiple IRC commands by separating them by CRLF pairs. Just take care of avoiding a CRLF after the last command you specify.
Returns true on success or false if the data can't be actually enqueued/sent (and this usually means that there is no connection at the moment). Please note that it MAY happen that a send attempt on a correctly connected link causes the link to actually disconnect (or rather "discover" the fact that it's disconnected at OS level).
Parameters:
pcFmt The format string to be first sprintf'ed with the variadic params and then sent
... The variadic arguments (see man sprintf for an explaination)
Returns:
bool
FIXME: change name to sendFormattedData() ?
References __tr2qs, _OUTPUT_MUTE, KviConsoleWindow::activeWindow(), context(), KviDataBuffer::data(), kvi_irc_vsnprintf(), KVI_OUT_SOCKETWARNING, kvi_va_end, kvi_va_list, kvi_va_start, KviEvent_OnOutboundTraffic, KVS_TRIGGER_EVENT_1, l, m, m_pConsole, m_pLink, KviWindow::outputNoFmt(), KviDataBuffer::resize(), and KviIrcLink::sendPacket().
Referenced by KviMaskInputDialog::accept(), avatar_kvs_cmd_notify(), avatar_kvs_cmd_query(), KviChannelWindow::closeEvent(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_module_reply_errmsg(), dccModuleParseDccGet(), TrayIcon::doAway(), DccFileTransfer::doResume(), endInitialCapNegotiation(), handleAuthenticate(), handleInitialCapAck(), handleInitialCapLs(), DccBroker::handleResumeRequest(), heartbeat(), ListWindow::itemDoubleClicked(), KviKvsCoreSimpleCommands::KVSCSC(), linkEstabilished(), loginComplete(), loginToIrcServer(), KviQueryWindow::ownAction(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralPing(), KviIrcServerParser::parseLoginNicknameProblem(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviChannelWindow::removeMasks(), KviIrcServerParser::replyCtcp(), LinksWindow::requestLinks(), ListWindow::requestList(), DccBroker::rsendExecute(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), KviChannelWindow::setAliveChan(), KviChannelWindow::setMode(), KviWatchNotifyListManager::start(), DccFileTransfer::startConnection(), KviWatchNotifyListManager::stop(), ListWindow::stoplistdownload(), KviIrcContext::terminateConnectionRequest(), KviLagMeter::timerEvent(), KviIrcConnectionRequestQueue::timerSlot(), KviChannelWindow::toggleListModeEditor(), and KviChannelWindow::topicSelected().
QTextCodec* KviIrcConnection::serverCodec () [inline]
Returns a pointer to the current global codec for inbound data.
This codec is a global setting and may be overridden by specific windows. The returned pointer may be null if things really went wrong.
Returns:
QTextCodec *
KviIrcConnectionServerInfo* KviIrcConnection::serverInfo () [inline]
Returns a pointer to the KviIrcConnectionServerInfo object.
It contains runtime information about the current server. This includes the current servername, the server capabilities and other stuff that KviConnectionTarget actually doesn't contain (or has only "default" values for). The returned pointer is never NULL. Include "KviIrcConnectionServerInfo.h" as the class is only forwarded here.
Returns:
KviIrcConnectionServerInfo *
Referenced by currentServerName(), KviConsoleWindow::fillStatusString(), KviUserListView::getUserFlag(), handleInitialCapLs(), KviUserListView::insertUserEntry(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric005(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseUserMode(), KviChangeUserModeAction::popupAboutToShow(), KviWindow::preprocessMessage(), restartNotifyList(), KviChannelWindow::serverInfo(), serverInfoReceived(), KviTopicWidget::switchMode(), KviLagMeter::timerEvent(), and KviChannelWindow::updateModeLabel().
void KviIrcConnection::serverInfoReceived (const QString & szServerName, const QString & szUserModes, const QString & szChanModes) [protected]
Called when RPL_SERVINFO (004) is received and sets the info.
Parameters:
szServerName The name of the server
szUserModes The user modes supported by the server
szChanModes The chan modes supported by the server
Returns:
void
References KviMainWindow::childConnectionServerInfoChange(), KviWindow::frame(), m_pConsole, serverInfo(), KviIrcConnectionServerInfo::setName(), KviIrcConnectionServerInfo::setSupportedChannelModes(), KviIrcConnectionServerInfo::setSupportedUserModes(), and KviWindow::updateCaption().
Referenced by KviIrcServerParser::parseNumeric004().
void KviIrcConnection::setEncoding (const QString & szEncoding)
Sets the global encoding for this connection.
This is a default value and can be overridden by specific windows.
Parameters:
szEncoding The encoding to use
Returns:
void
FIXME: This is quite unclear (why it forces encoding to all the windows?)
References __tr2qs, _OUTPUT_VERBOSE, c, KviLocale::codecForName(), KviPointerList< T >::first(), KVI_OUT_SYSTEMERROR, KVI_OUT_VERBOSE, m_pChannelList, m_pConsole, m_pQueryList, m_pTextCodec, KviPointerList< T >::next(), KviWindow::output(), q, and KviWindow::setTextEncoding().
Referenced by KviIrcServerParser::parseNumericCodePageSet().
void KviIrcConnection::setupSrvCodec () [private]
Setups the codec for the server.
Returns:
void
References KviLocale::codecForName(), KviApplication::defaultSrvCodec(), KviIrcNetwork::encoding(), KviIrcServer::encoding(), m_pConsole, m_pSrvCodec, m_pTarget, KviIrcConnectionTarget::network(), KviIrcConnectionTarget::server(), and KviWindow::setTextEncoding().
Referenced by KviIrcConnection().
void KviIrcConnection::setupTextCodec () [private]
Setups the codec for the text.
Returns:
void
References KviLocale::codecForName(), KviApplication::defaultTextCodec(), m_pTarget, m_pTextCodec, KviIrcConnectionTarget::network(), KviIrcConnectionTarget::server(), KviIrcNetwork::textEncoding(), and KviIrcServer::textEncoding().
Referenced by KviIrcConnection(), and loginToIrcServer().
void KviIrcConnection::start () [protected]
This starts an asynchronous connection attempt.
You must return control to the Qt core for the connection operations to be initiated
Returns:
void
References Connecting, KviMainWindow::executeInternalCommand(), g_pMainWindow, KVI_INTERNALCOMMAND_IDENT_START, KVI_OPTION_BOOL, KviOption_boolUseIdentService, KviOption_boolUseIdentServiceOnlyOnConnect, m_bIdentdAttached, m_eState, m_pLink, and KviIrcLink::start().
Referenced by KviIrcContext::connectToCurrentServer().
State KviIrcConnection::state () [inline]
Returns the current state of the connection.
Returns:
State
Referenced by loginComplete(), KviStatusBarLagIndicator::mouseDoubleClickEvent(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviLagMeter::timerEvent(), KviStatusBarLagIndicator::tipText(), and KviStatusBarAwayIndicator::tipText().
KviIrcConnectionStateData* KviIrcConnection::stateData () [inline]
Returns a pointer to the KviIrcConnectionStateData object.
It contains _generic_ connection state data. This includes the current nickname index at login time, flags that signal "micro-states" etc... This data *could* be part of KviIrcConnection itself but we prefer to keep it in a separate class in order to cleanup the implementation. The returned pointer is never NULL. Include "KviIrcConnectionStateData.h" as the class is only forwarded here.
Returns:
KviIrcConnectionStateData *
Referenced by KviIrcContext::connectionTerminated(), KviIrcContext::connectToCurrentServer(), heartbeat(), KviIrcServerParser::parseLiteralCap(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseMessage(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNotRegistered(), KviIrcServerParser::parseNumericSaslFail(), KviIrcServerParser::parseNumericSaslLogin(), KviIrcServerParser::parseNumericSaslSuccess(), KviIrcServerParser::parseNumericStartTls(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcContext::terminateConnectionRequest(), and KviIrcConnectionRequestQueue::timerSlot().
KviIrcConnectionStatistics* KviIrcConnection::statistics () [inline]
Returns a pointer to the KviIrcConnectionStatistics object.
It contains runtime statistics about the connection. Very similar to KviIrcConnectionStateData but dedicated to statistics. The returned pointer is never NULL. Include "KviIrcConnectionStatistics.h" as the class is only forwarded here.
Returns:
KviIrcConnectionStatistics *
Referenced by KviStatusBarConnectionTimer::timerEvent().
KviIrcConnectionTarget* KviIrcConnection::target () [inline]
Returns the target of this connection.
Please note that the target doesn't necessairly contain up-to-date data. You might want to look at serverInfo() instead. The returned pointer is never NULL.
Returns:
KviIrcConnectionTarget *
Referenced by chan_kvs_fnc_getUrl(), KviIrcContext::connectionFailed(), handleAuthenticate(), handleInitialCapAck(), handleInitialCapLs(), KviConsoleWindow::isIPv6Connection(), KviIrcLink::KviIrcLink(), linkEstabilished(), loginComplete(), loginToIrcServer(), KviIrcServerParser::parseLiteralNotice(), pickNextLoginNickName(), resolveLocalHost(), KviIrcUrl::run(), KviMdiChild::setClient(), and KviConsoleWindow::updateUri().
QTextCodec* KviIrcConnection::textCodec () [inline]
Returns a pointer to the current global codec for outbound text.
This codec is a global setting and may be overridden by specific windows. The returned pointer may be null if things really went wrong.
Returns:
QTextCodec *
Referenced by KviWindow::defaultTextCodec().
void KviIrcConnection::unhighlightAllChannels () [slot]
Called when we unhighlight all channels.
Returns:
void
References c, KviPointerList< T >::first(), m_pChannelList, and KviPointerList< T >::next().
void KviIrcConnection::unhighlightAllQueries () [slot]
Called when we unhighlight all queries.
Returns:
void
References c, KviPointerList< T >::first(), m_pQueryList, and KviPointerList< T >::next().
void KviIrcConnection::unregisterChannel (KviChannelWindow * c)
This is called by KviChannelWindow just before destruction. You shouldn't need to call it.
FIXME: Could be made protected.
References chanListChanged(), channelUnregistered(), KviIrcConnectionRequestQueue::dequeueChannel(), m_pChannelList, KviPointerList< T >::removeRef(), and requestQueue().
Referenced by KviChannelWindow::setDeadChan(), and KviChannelWindow::~KviChannelWindow().
void KviIrcConnection::unregisterQuery (KviQueryWindow * q)
This is called by KviQueryWindow just before destruction, you shouldn't need to use it.
FIXME: Could be made protected.
References m_pQueryList, and KviPointerList< T >::removeRef().
Referenced by KviQueryWindow::setDeadQuery(), and KviQueryWindow::~KviQueryWindow().
void KviIrcConnection::useProfileData (KviIdentityProfileSet * pSet, const QString & szNetwork) [protected]
Uses the profiles' data as connection data.
It checks if the identity profiles are enabled and updates the data of the connection if a profile rule matches the network name
Parameters:
pSet The instance of the network identity profile set
szNetwork The name of the network
Returns:
void
References KviIdentityProfileSet::findNetwork(), m_pUserInfo, KviIdentityProfile::realName(), KviIrcConnectionUserInfo::setUserName(), useRealName(), and KviIdentityProfile::userName().
Referenced by loginToIrcServer().
KviIrcUserDataBase* KviIrcConnection::userDataBase () [inline]
Returns a pointer to the big connection user database.
The database contains ALL the users KVIrc can "see" in this connection. The returned pointer is never NULL.
Returns:
KviIrcUserDataBase *
Referenced by KviConsoleWindow::applyHighlighting(), avatar_kvs_cmd_notify(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KviConsoleWindow::avatarChanged(), KviConsoleWindow::checkDefaultAvatar(), KviUserListEntry::color(), KviConsoleWindow::currentAvatar(), KviIrcView::doLinkToolTip(), KviQueryWindow::getInfoLabelText(), KviQueryWindow::getInfoLabelTipText(), KviIsOnNotifyListManager::handleIsOn(), loginComplete(), loginToIrcServer(), KviConsoleWindow::outputPrivmsg(), KviUserListViewArea::paintEvent(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpReplyUserinfo(), KviIrcServerParser::parseCtcpRequest(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviQueryWindow::setAliveQuery(), KviConsoleWindow::setAvatar(), KviConsoleWindow::setAvatarFromOptions(), and userInfoReceived().
void KviIrcConnection::useRealName (const QString & szRealName) [protected]
Sets the specified real name in the user information set after evaluating it via KVS engine (so identifiers are substituted). Call this function instead of m_pUserInfo->setRealName().
References KviKvsVariant::asString(), console(), KviQString::escapeKvs(), KviKvsScript::evaluate(), m_pUserInfo, KviQString::PermitFunctions, KviQString::PermitVariables, and KviIrcConnectionUserInfo::setRealName().
Referenced by loginToIrcServer(), and useProfileData().
KviIrcConnectionUserInfo* KviIrcConnection::userInfo () [inline]
Returns a pointer to the KviIrcConnectionUserInfo object.
It contains runtime information about the user. This includes the current nickname, username, flags and other stuff that KviUserIdentity actually doesn't contain (or has only "default" values for). The returned pointer is never NULL. Include "KviIrcConnectionUserInfo.h" as the class is only forwarded here.
Returns:
KviIrcConnectionUserInfo *
Referenced by KviGoAwayAction::activeContextStateChanged(), KviMaskEditor::addClicked(), KviGoAwayAction::addToPopupMenu(), KviConsoleWindow::applyHighlighting(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), KviIrcContext::connectionFailed(), DccFileTransfer::connectionInProgress(), DccChatWindow::connectionInProgress(), KviIrcContext::connectionTerminated(), currentNickName(), currentUserName(), dcc_fill_local_nick_user_host(), dcc_kvs_parse_default_parameters(), TrayIcon::doAway(), KviIrcContextDisplay::drawContents(), TrayIcon::fillContextPopup(), KviConsoleWindow::fillStatusString(), KviMaskEditor::itemDoubleClicked(), loginToIrcServer(), KviStatusBar::mouseDoubleClickEvent(), KviModeWidget::mouseDoubleClickEvent(), KviConsoleWindow::outputPrivmsg(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCtcpRequestFinger(), KviIrcServerParser::parseLoginNicknameProblem(), KviUserInput::parseNonCommand(), KviIrcServerParser::parseNumeric001(), KviIrcServerParser::parseNumericBackFromAway(), KviChangeUserModeAction::popupAboutToShow(), KviChangeUserModeAction::popupActivated(), KviStatusBar::setPermanentMessage(), KviTopicWidget::switchMode(), KviLagMeter::timerEvent(), KviIrcContextDisplay::tipRequest(), KviStatusBarAwayIndicator::tipText(), KviStatusBarAwayIndicator::updateDisplay(), KviModeEditor::updateOpStatus(), KviMaskEditor::updateOpStatus(), and userInfoReceived().
void KviIrcConnection::userInfoReceived (const QString & szUserName, const QString & szHostName) [protected]
Called on each JOIN and sets the info.
It's called meaningful almost only on the first time
Parameters:
szUserName The username
szHostName The hostname
Returns:
void FIXME: call it also on other messages ?
References __tr2qs, _OUTPUT_MUTE, KviDnsResolver::Any, connect(), e, KviQString::equalCS(), KviIrcUserDataBase::find(), KviIrcConnectionUserInfo::hostIp(), KviIrcConnectionUserInfo::hostName(), hostNameLookupTerminated(), KviNetUtils::isRoutableIpString(), KviNetUtils::isValidStringIp(), KVI_OPTION_BOOL, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviOption_boolDccBrokenBouncerHack, KviOption_boolDccGuessIpFromServerWhenLocalIsUnroutable, KviIrcConnectionUserInfo::localHostIp(), KviDnsResolver::lookup(), m_pConsole, m_pLocalhostDns, m_pUserInfo, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcUserEntry::setHost(), KviIrcConnectionUserInfo::setHostIp(), KviIrcConnectionUserInfo::setHostName(), KviIrcUserEntry::setUser(), KviIrcConnectionUserInfo::setUserName(), KviIrcConnectionUserInfo::unmaskedHostName(), userDataBase(), and userInfo().
Referenced by KviIrcServerParser::parseLiteralJoin(), and KviIrcServerParser::parseNumeric001().
void KviIrcConnection::userModeChanged () [signal]
Emitted when the user modes change.
Returns:
void
Referenced by changeUserMode().
Friends And Related Function Documentation
friend class KviConsoleWindow [friend]
friend class KviIrcContext [friend]
friend class KviIrcLink [friend]
Referenced by KviIrcConnection().
friend class KviIrcServerParser [friend]
Member Data Documentation
bool KviIrcConnection::m_bIdentdAttached [private]
Referenced by KviIrcConnection(), linkAttemptFailed(), linkTerminated(), loginComplete(), start(), and ~KviIrcConnection().
State KviIrcConnection::m_eState [private]
Referenced by heartbeat(), KviIrcConnection(), linkAttemptFailed(), linkEstabilished(), linkTerminated(), and start().
KviIrcConnectionAntiCtcpFloodData* KviIrcConnection::m_pAntiCtcpFloodData [private]
Referenced by KviIrcConnection(), and ~KviIrcConnection().
KviIrcConnectionAsyncWhoisData* KviIrcConnection::m_pAsyncWhoisData [private]
Referenced by KviIrcConnection(), and ~KviIrcConnection().
KviPointerList<KviChannelWindow>* KviIrcConnection::m_pChannelList [private]
Referenced by closeAllChannels(), findChannel(), getCommonChannels(), heartbeat(), keepChannelsOpenAfterDisconnect(), KviIrcConnection(), registerChannel(), setEncoding(), unhighlightAllChannels(), unregisterChannel(), and ~KviIrcConnection().
KviConsoleWindow* KviIrcConnection::m_pConsole [private]
Referenced by changeAwayState(), changeUserMode(), KviNotifyListManager::console(), createChannel(), createQuery(), hostNameLookupTerminated(), KviIrcConnection(), loginComplete(), loginToIrcServer(), nickChange(), resolveLocalHost(), restartNotifyList(), sendData(), sendFmtData(), serverInfoReceived(), setEncoding(), setupSrvCodec(), and userInfoReceived().
KviIrcContext* KviIrcConnection::m_pContext [private]
Referenced by createChannel(), createQuery(), KviIrcConnection(), and resurrectDeadQueries().
KviLagMeter* KviIrcConnection::m_pLagMeter [private]
Referenced by KviIrcConnection(), linkTerminated(), restartLagMeter(), and ~KviIrcConnection().
KviIrcLink* KviIrcConnection::m_pLink [private]
Referenced by abort(), clearOutputQueue(), KviIrcConnection(), sendData(), sendFmtData(), start(), and ~KviIrcConnection().
KviDnsResolver* KviIrcConnection::m_pLocalhostDns [private]
Referenced by hostNameLookupTerminated(), KviIrcConnection(), userInfoReceived(), and ~KviIrcConnection().
KviIrcConnectionNetsplitDetectorData* KviIrcConnection::m_pNetsplitDetectorData [private]
Referenced by KviIrcConnection(), and ~KviIrcConnection().
KviNotifyListManager* KviIrcConnection::m_pNotifyListManager [private]
Referenced by KviIrcConnection(), linkTerminated(), restartNotifyList(), and ~KviIrcConnection().
QTimer* KviIrcConnection::m_pNotifyListTimer [private]
Referenced by delayedStartNotifyList(), endOfMotdReceived(), KviIrcConnection(), restartNotifyList(), and ~KviIrcConnection().
KviPointerList<KviQueryWindow>* KviIrcConnection::m_pQueryList [private]
Referenced by closeAllQueries(), findQuery(), keepQueriesOpenAfterDisconnect(), KviIrcConnection(), registerQuery(), setEncoding(), unhighlightAllQueries(), unregisterQuery(), and ~KviIrcConnection().
KviIrcConnectionRequestQueue* KviIrcConnection::m_pRequestQueue [private]
Referenced by KviIrcConnection(), and ~KviIrcConnection().
KviIrcConnectionServerInfo* KviIrcConnection::m_pServerInfo [private]
Referenced by currentNetworkName(), KviIrcConnection(), linkEstabilished(), loginToIrcServer(), registerChannel(), and ~KviIrcConnection().
QTextCodec* KviIrcConnection::m_pSrvCodec [private]
Referenced by decodeText(), encodeText(), and setupSrvCodec().
KviIrcConnectionStateData* KviIrcConnection::m_pStateData [private]
Referenced by endInitialCapNegotiation(), handleAuthenticate(), handleFailedInitialCapLs(), handleInitialCapAck(), handleInitialCapLs(), KviIrcConnection(), linkEstabilished(), loginComplete(), loginToIrcServer(), pickNextLoginNickName(), and ~KviIrcConnection().
KviIrcConnectionStatistics* KviIrcConnection::m_pStatistics [private]
Referenced by incomingMessage(), incomingMessageNoFilter(), KviIrcConnection(), linkEstabilished(), and ~KviIrcConnection().
KviIrcConnectionTarget* KviIrcConnection::m_pTarget [private]
Referenced by KviIrcConnection(), setupSrvCodec(), setupTextCodec(), and ~KviIrcConnection().
QTextCodec* KviIrcConnection::m_pTextCodec [private]
Referenced by setEncoding(), and setupTextCodec().
KviIrcUserDataBase* KviIrcConnection::m_pUserDataBase [private]
Referenced by KviIrcConnection(), and ~KviIrcConnection().
KviUserIdentity* KviIrcConnection::m_pUserIdentity [private]
Referenced by KviIrcConnection(), loginComplete(), loginToIrcServer(), and ~KviIrcConnection().
KviIrcConnectionUserInfo* KviIrcConnection::m_pUserInfo [private]
Referenced by changeAwayState(), changeUserMode(), hostNameLookupTerminated(), KviIrcConnection(), loginComplete(), loginToIrcServer(), nickChange(), resolveLocalHost(), useProfileData(), useRealName(), userInfoReceived(), and ~KviIrcConnection().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnection.h
src/kvirc/kernel/KviIrcConnection.cpp