KVIrc: OptionsWidget_messageColors Class Reference
OptionsWidget_messageColors Class Reference
#include <OptionsWidget_message.h>
Public Member Functions
OptionsWidget_messageColors (QWidget *parent)
void saveLastItem ()
~OptionsWidget_messageColors ()
Public Member Functions inherited from KviOptionsWidget
void addAdvancedButton (int x1, int y1, int x2, int y2)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
virtual void commit ()
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Public Attributes
MessageColorListWidgetItem * m_pBackItems [17]
KviTalListWidget * m_pBackListWidget
MessageColorListWidgetItemDelegate * m_pBackListWidgetDelegate
QCheckBox * m_pEnableLogging
MessageColorListWidgetItem * m_pForeItems [16]
KviTalListWidget * m_pForeListWidget
MessageColorListWidgetItemDelegate * m_pForeListWidgetDelegate
QToolButton * m_pIconButton
QMenu * m_pIconPopup
MessageListWidgetItem * m_pLastItem
KviTalListWidget * m_pLevelListWidget
MessageListWidget * m_pListView
MessageListWidgetItemDelegate * m_pListViewItemDelegate
Protected Slots
void colorChanged ()
virtual void commit ()
void iconButtonClicked ()
void itemChanged ()
virtual void load ()
void newIconSelected (KviIconManager::SmallIcon eIcon)
virtual void save ()
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
void switchToAdvancedPage ()
Friends
class KviTalListWidget
Additional Inherited Members
Signals inherited from KviOptionsWidget
void wantToSwitchToAdvancedPage (KviOptionsWidget *)
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_messageColors::OptionsWidget_messageColors (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addWidgetToLayout(), colorChanged(), connect(), KviOptionsWidget::createLayout(), h, i, iconButtonClicked(), itemChanged(), KVI_NUM_MSGTYPE_OPTIONS, KVI_OPTION_FONT, KviIconWidget, KviOption_fontIrcView, KviTalListWidget, KviOptionsWidget::layout(), load(), m_pBackItems, m_pBackListWidget, m_pBackListWidgetDelegate, m_pEnableLogging, m_pForeItems, m_pForeListWidget, m_pForeListWidgetDelegate, m_pIconButton, m_pIconPopup, m_pLastItem, m_pLevelListWidget, m_pListView, m_pListViewItemDelegate, newIconSelected(), save(), and KviControlCodes::Transparent.
OptionsWidget_messageColors::~OptionsWidget_messageColors ()
References i, m_pBackItems, m_pBackListWidget, m_pEnableLogging, m_pForeItems, m_pForeListWidget, m_pIconButton, m_pIconPopup, m_pLevelListWidget, and m_pListView.
Member Function Documentation
void OptionsWidget_messageColors::colorChanged () protected slot
References m_pLastItem, and saveLastItem().
Referenced by OptionsWidget_messageColors().
void OptionsWidget_messageColors::commit (void) protected virtual slot
References KviOptionsWidget::commit(), i, KVI_OPTION_MSGTYPE, m_pListView, KviOptionsWidget::mergeResetFlag(), MessageListWidgetItem::msgType(), MessageListWidgetItem::optionId(), and saveLastItem().
void OptionsWidget_messageColors::iconButtonClicked () protected slot
References m_pIconPopup.
Referenced by OptionsWidget_messageColors().
void OptionsWidget_messageColors::itemChanged () protected slot
References g_pIconManager, KviIconManager::getSmallIcon(), m_pBackItems, m_pBackListWidget, m_pEnableLogging, m_pForeItems, m_pForeListWidget, m_pIconButton, m_pLastItem, m_pLevelListWidget, m_pListView, and saveLastItem().
Referenced by load(), and OptionsWidget_messageColors().
void OptionsWidget_messageColors::load () protected virtual slot
References __tr2qs_ctx(), KviFileDialog::askForOpenFileName(), KviMessageTypeSettings::back(), KviMessageTypeSettings::enableLogging(), KviMessageTypeSettings::fore(), g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), i, KviIconManager::IconCount, itemChanged(), KviMessageTypeSettings::level(), KviMessageTypeSettings::logEnabled(), m_pListView, KviApplication::MsgColors, MessageListWidgetItem::msgType(), MessageListWidgetItem::optionId(), KviMessageTypeSettings::pixId(), Q_UNUSED(), KviConfigurationFile::Read, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readIntEntry(), KviMessageTypeSettings::setBack(), KviMessageTypeSettings::setFore(), KviConfigurationFile::setGroup(), KviMessageTypeSettings::setLevel(), KviMessageTypeSettings::setPixId(), and KviControlCodes::Transparent.
Referenced by OptionsWidget_messageColors().
void OptionsWidget_messageColors::newIconSelected (KviIconManager::SmallIcon eIcon) protected slot
References g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::IconCount, m_pIconButton, m_pLastItem, m_pListView, MessageListWidgetItem::msgType(), and KviMessageTypeSettings::setPixId().
Referenced by OptionsWidget_messageColors().
void OptionsWidget_messageColors::save () protected virtual slot
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), KviMessageTypeSettings::back(), KviMessageTypeSettings::fore(), g_pApp, KviApplication::getLocalKvircDirectory(), i, KviMessageTypeSettings::level(), KviMessageTypeSettings::logEnabled(), m_pLastItem, m_pListView, KviApplication::MsgColors, MessageListWidgetItem::msgType(), MessageListWidgetItem::optionId(), KviMessageTypeSettings::pixId(), KviCString::ptr(), saveLastItem(), KviConfigurationFile::setGroup(), KviCString::sprintf(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by OptionsWidget_messageColors().
void OptionsWidget_messageColors::saveLastItem ()
References KviMessageTypeSettings::enableLogging(), MessageColorListWidgetItem::m_iClrIdx, m_pBackListWidget, m_pEnableLogging, m_pForeListWidget, m_pLastItem, m_pLevelListWidget, m_pListView, MessageListWidgetItem::msgType(), KviMessageTypeSettings::setBack(), KviMessageTypeSettings::setFore(), and KviMessageTypeSettings::setLevel().
Referenced by colorChanged(), commit(), itemChanged(), and save().
Friends And Related Function Documentation
friend class KviTalListWidget friend
Referenced by OptionsWidget_messageColors().
Member Data Documentation
MessageColorListWidgetItem* OptionsWidget_messageColors::m_pBackItems[17]
Referenced by itemChanged(), OptionsWidget_messageColors(), and ~OptionsWidget_messageColors().
KviTalListWidget* OptionsWidget_messageColors::m_pBackListWidget
Referenced by itemChanged(), OptionsWidget_messageColors(), saveLastItem(), and ~OptionsWidget_messageColors().
MessageColorListWidgetItemDelegate* OptionsWidget_messageColors::m_pBackListWidgetDelegate
Referenced by OptionsWidget_messageColors().
QCheckBox* OptionsWidget_messageColors::m_pEnableLogging
Referenced by itemChanged(), OptionsWidget_messageColors(), saveLastItem(), and ~OptionsWidget_messageColors().
MessageColorListWidgetItem* OptionsWidget_messageColors::m_pForeItems[16]
Referenced by itemChanged(), OptionsWidget_messageColors(), and ~OptionsWidget_messageColors().
KviTalListWidget* OptionsWidget_messageColors::m_pForeListWidget
Referenced by itemChanged(), OptionsWidget_messageColors(), saveLastItem(), and ~OptionsWidget_messageColors().
MessageColorListWidgetItemDelegate* OptionsWidget_messageColors::m_pForeListWidgetDelegate
Referenced by OptionsWidget_messageColors().
QToolButton* OptionsWidget_messageColors::m_pIconButton
Referenced by itemChanged(), newIconSelected(), OptionsWidget_messageColors(), and ~OptionsWidget_messageColors().
QMenu* OptionsWidget_messageColors::m_pIconPopup
Referenced by iconButtonClicked(), OptionsWidget_messageColors(), and ~OptionsWidget_messageColors().
MessageListWidgetItem* OptionsWidget_messageColors::m_pLastItem
Referenced by colorChanged(), itemChanged(), newIconSelected(), OptionsWidget_messageColors(), save(), and saveLastItem().
KviTalListWidget* OptionsWidget_messageColors::m_pLevelListWidget
Referenced by itemChanged(), OptionsWidget_messageColors(), saveLastItem(), and ~OptionsWidget_messageColors().
MessageListWidget* OptionsWidget_messageColors::m_pListView
Referenced by commit(), itemChanged(), load(), newIconSelected(), OptionsWidget_messageColors(), save(), saveLastItem(), and ~OptionsWidget_messageColors().
MessageListWidgetItemDelegate* OptionsWidget_messageColors::m_pListViewItemDelegate
Referenced by OptionsWidget_messageColors().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_message.h
src/modules/options/OptionsWidget_message.cpp