KVIrc: KviDataBuffer Class Reference
KviDataBuffer Class Reference
#include <KviDataBuffer.h>
Public Member Functions
void addSize (int uSize)
void append (const unsigned char *data, int uSize)
void append (const KviDataBuffer &b)
void clear ()
unsigned char * data () const
int find (unsigned char c)
int find (const unsigned char *block, int uSize)
KviDataBuffer (int uSize, const unsigned char *data=0)
KviDataBuffer ()
void remove (int uSize)
void resize (int uSize)
int size () const
~KviDataBuffer ()
Private Attributes
unsigned char * m_pData
int m_uSize
Constructor & Destructor Documentation
KviDataBuffer::KviDataBuffer (int uSize, const unsigned char * data = 0)
References KviMemory::allocate(), KVI_ASSERT, m_pData, m_uSize, and KviMemory::move().
KviDataBuffer::KviDataBuffer ()
References m_pData, and m_uSize.
KviDataBuffer::~KviDataBuffer ()
References KviMemory::free(), KVI_ASSERT, m_pData, and m_uSize.
Member Function Documentation
void KviDataBuffer::addSize (int uSize) inline
Referenced by DccVoiceAdpcmCodec::decode(), DccVoiceAdpcmCodec::encode(), and DccVoiceThread::soundStep().
void KviDataBuffer::append (const unsigned char * data, int uSize)
References m_pData, m_uSize, KviMemory::move(), and KviMemory::reallocate().
Referenced by DccVoiceNullCodec::decode(), DccVideoSJpegCodec::decode(), DccVoiceNullCodec::encode(), DccVideoSJpegCodec::encodeText(), DccVideoSJpegCodec::encodeVideo(), KviHttpRequest::processData(), DccVideoThread::textStep(), and DccVideoThread::videoStep().
void KviDataBuffer::append (const KviDataBuffer & b) inline
References append(), data(), and size().
Referenced by append().
void KviDataBuffer::clear () inline
Referenced by KviOggTheoraDecoder::addData(), DccVideoSJpegCodec::decode(), DccVideoSJpegCodec::encodeText(), DccVideoTheoraCodec::encodeText(), DccVideoSJpegCodec::encodeVideo(), DccVideoTheoraCodec::encodeVideo(), KviHttpRequest::processData(), KviHttpRequest::resetInternalStatus(), and DccVideoThread::textStep().
unsigned char* KviDataBuffer::data () const inline
Referenced by KviOggTheoraDecoder::addData(), append(), KviStatusBarUpdateIndicator::binaryDataReceived(), DccVoiceNullCodec::decode(), DccVoiceAdpcmCodec::decode(), DccVideoSJpegCodec::decode(), KviHttpRequest::emitLines(), DccVoiceNullCodec::encode(), DccVoiceAdpcmCodec::encode(), DccVideoSJpegCodec::encodeText(), DccVideoTheoraCodec::encodeText(), DccVideoSJpegCodec::encodeVideo(), DccVideoTheoraCodec::encodeVideo(), KviIrcSocket::flushSendQueue(), KviHttpRequest::processData(), KviIrcSocket::queue_removePrivateMessages(), DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), KviIrcConnection::sendData(), KviIrcConnection::sendFmtData(), KviIrcSocket::sendRawData(), KviHttpRequest::slotSocketDisconnected(), KviHttpRequest::slotSocketReadDataReady(), DccVoiceThread::soundStep(), DccVideoThread::textStep(), and DccVideoThread::videoStep().
int KviDataBuffer::find (unsigned char c)
References e, m_pData, m_uSize, and p.
Referenced by DccVideoSJpegCodec::decode(), KviHttpRequest::emitLines(), and KviHttpRequest::processData().
int KviDataBuffer::find (const unsigned char * block, int uSize)
References i, j, m_pData, and m_uSize.
void KviDataBuffer::remove (int uSize)
References KviMemory::free(), KVI_ASSERT, m_pData, m_uSize, KviMemory::move(), and KviMemory::reallocate().
Referenced by DccVoiceAdpcmCodec::decode(), DccVideoSJpegCodec::decode(), KviHttpRequest::emitLines(), DccVoiceAdpcmCodec::encode(), KviIrcSocket::flushSendQueue(), KviHttpRequest::processData(), DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), and DccVoiceThread::soundStep().
void KviDataBuffer::resize (int uSize)
References KviMemory::free(), KVI_ASSERT, m_pData, m_uSize, and KviMemory::reallocate().
Referenced by DccVoiceNullCodec::decode(), DccVoiceNullCodec::encode(), DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), KviIrcConnection::sendFmtData(), KviHttpRequest::slotSocketReadDataReady(), and DccVoiceThread::soundStep().
int KviDataBuffer::size () const inline
Referenced by KviOggTheoraDecoder::addData(), append(), KviStatusBarUpdateIndicator::binaryDataReceived(), DccVoiceNullCodec::decode(), DccVoiceAdpcmCodec::decode(), DccVideoSJpegCodec::decode(), DccVideoTheoraCodec::decode(), DccVoiceNullCodec::encode(), DccVoiceAdpcmCodec::encode(), DccVideoSJpegCodec::encodeText(), DccVideoTheoraCodec::encodeText(), DccVideoSJpegCodec::encodeVideo(), DccVideoTheoraCodec::encodeVideo(), KviIrcSocket::flushSendQueue(), KviHttpRequest::processData(), KviIrcSocket::queue_removePrivateMessages(), DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), DccVoiceThread::run(), KviHttpRequest::slotSocketDisconnected(), DccVoiceThread::soundStep(), DccVideoThread::textStep(), and DccVideoThread::videoStep().
Member Data Documentation
unsigned char* KviDataBuffer::m_pData private
Referenced by append(), find(), KviDataBuffer(), remove(), resize(), and ~KviDataBuffer().
int KviDataBuffer::m_uSize private
Referenced by append(), find(), KviDataBuffer(), remove(), resize(), and ~KviDataBuffer().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviDataBuffer.h
src/kvilib/ext/KviDataBuffer.cpp