KVIrc: KviIrcConnectionUserInfo Class Reference
KviIrcConnectionUserInfo Class Reference
#include <KviIrcConnectionUserInfo.h>
Public Member Functions
const QString & awayReason ()
time_t awayTime ()
bool hasUserMode (const QChar &m)
const QString & hostIp ()
const QString & hostName ()
bool isAway ()
const QString & localHostIp ()
const QString & nickName ()
const QString & nickNameBeforeAway ()
const QString & password ()
const QString & realName ()
const QString & unmaskedHostName ()
const QString & userMode ()
const QString & userName ()
Protected Member Functions
bool addUserMode (const QChar &m)
KviIrcConnectionUserInfo ()
bool removeUserMode (const QChar &m)
void setAway ()
void setAwayReason (const QString &szReazon)
void setBack ()
void setHostIp (const QString &szHostIp)
void setHostName (const QString &szHostName)
void setLocalHostIp (const QString &szLocalHostIp)
void setNickName (const QString &szNickName)
void setPassword (const QString &szPassword)
void setRealName (const QString &szRealName)
void setUnmaskedHostName (const QString &szHostName)
void setUserMode (const QString &szUserMode)
void setUserName (const QString &szUserName)
~KviIrcConnectionUserInfo ()
Private Attributes
bool m_bAway
QString m_szAwayReason
QString m_szHostIp
QString m_szHostName
QString m_szLocalHostIp
QString m_szNickBeforeAway
QString m_szNickName
QString m_szPassword
QString m_szRealName
QString m_szUnmaskedHostName
QString m_szUserMode
QString m_szUserName
kvi_time_t m_tAway
Friends
class KviConsoleWindow
class KviIrcConnection
class KviIrcServerParser
Constructor & Destructor Documentation
KviIrcConnectionUserInfo::KviIrcConnectionUserInfo () [protected]
References m_bAway.
KviIrcConnectionUserInfo::~KviIrcConnectionUserInfo () [inline, protected]
Member Function Documentation
bool KviIrcConnectionUserInfo::addUserMode (const QChar & m) [protected]
References hasUserMode(), and m_szUserMode.
Referenced by KviIrcConnection::changeUserMode().
const QString& KviIrcConnectionUserInfo::awayReason () [inline]
Referenced by KviIrcContext::connectionTerminated().
time_t KviIrcConnectionUserInfo::awayTime () [inline]
Referenced by KviIrcServerParser::parseNumericBackFromAway(), and KviStatusBarAwayIndicator::tipText().
bool KviIrcConnectionUserInfo::hasUserMode (const QChar & m)
References m_szUserMode.
Referenced by KviMaskEditor::addClicked(), addUserMode(), KviIrcConnection::changeUserMode(), KviMaskEditor::itemDoubleClicked(), KviModeWidget::mouseDoubleClickEvent(), KviChangeUserModeAction::popupAboutToShow(), KviChangeUserModeAction::popupActivated(), KviTopicWidget::switchMode(), KviModeEditor::updateOpStatus(), and KviMaskEditor::updateOpStatus().
const QString& KviIrcConnectionUserInfo::hostIp () [inline]
Referenced by DccFileTransfer::connectionInProgress(), DccChatWindow::connectionInProgress(), KviIrcConnection::hostNameLookupTerminated(), and KviIrcConnection::userInfoReceived().
const QString& KviIrcConnectionUserInfo::hostName () [inline]
Referenced by avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), dcc_fill_local_nick_user_host(), dcc_kvs_parse_default_parameters(), KviStatusBar::mouseDoubleClickEvent(), KviConsoleWindow::outputPrivmsg(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseChannelMode(), and KviIrcConnection::userInfoReceived().
bool KviIrcConnectionUserInfo::isAway () [inline]
Referenced by KviGoAwayAction::activeContextStateChanged(), KviGoAwayAction::addToPopupMenu(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviTrayIconWidget::doAway(), KviIrcContextDisplay::drawContents(), KviTrayIconWidget::fillContextPopup(), KviStatusBar::mouseDoubleClickEvent(), KviUserInput::parseNonCommand(), KviIrcServerParser::parseNumericBackFromAway(), KviStatusBarAwayIndicator::tipText(), and KviStatusBarAwayIndicator::updateDisplay().
const QString& KviIrcConnectionUserInfo::localHostIp () [inline]
Referenced by KviStatusBar::mouseDoubleClickEvent(), KviIrcConnection::resolveLocalHost(), and KviIrcConnection::userInfoReceived().
const QString& KviIrcConnectionUserInfo::nickName () [inline]
Referenced by KviConsoleWindow::applyHighlighting(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), KviIrcConnection::currentNickName(), dcc_fill_local_nick_user_host(), dcc_kvs_parse_default_parameters(), KviConsoleWindow::fillStatusString(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviStatusBar::mouseDoubleClickEvent(), KviIrcConnection::nickChange(), KviConsoleWindow::outputPrivmsg(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseLoginNicknameProblem(), KviChangeUserModeAction::popupActivated(), KviLagMeter::timerEvent(), and KviIrcContextDisplay::tipRequest().
const QString& KviIrcConnectionUserInfo::nickNameBeforeAway () [inline]
Referenced by KviIrcContext::connectionFailed(), KviIrcContext::connectionTerminated(), and KviIrcServerParser::parseNumericBackFromAway().
const QString& KviIrcConnectionUserInfo::password () [inline]
Referenced by KviIrcContext::connectionTerminated(), and KviIrcConnection::loginToIrcServer().
const QString& KviIrcConnectionUserInfo::realName () [inline]
Referenced by KviIrcConnection::loginToIrcServer().
bool KviIrcConnectionUserInfo::removeUserMode (const QChar & m) [protected]
References m_szUserMode.
Referenced by KviIrcConnection::changeUserMode().
void KviIrcConnectionUserInfo::setAway () [protected]
References kvi_unixTime, m_bAway, m_szNickBeforeAway, m_szNickName, and m_tAway.
Referenced by KviIrcConnection::changeAwayState().
void KviIrcConnectionUserInfo::setAwayReason (const QString & szReazon) [inline, protected]
void KviIrcConnectionUserInfo::setBack () [protected]
References m_bAway, and m_szNickBeforeAway.
Referenced by KviIrcConnection::changeAwayState().
void KviIrcConnectionUserInfo::setHostIp (const QString & szHostIp) [inline, protected]
Referenced by KviIrcConnection::hostNameLookupTerminated(), KviIrcConnection::resolveLocalHost(), and KviIrcConnection::userInfoReceived().
void KviIrcConnectionUserInfo::setHostName (const QString & szHostName) [inline, protected]
Referenced by KviIrcConnection::resolveLocalHost(), and KviIrcConnection::userInfoReceived().
void KviIrcConnectionUserInfo::setLocalHostIp (const QString & szLocalHostIp) [inline, protected]
Referenced by KviIrcConnection::resolveLocalHost().
void KviIrcConnectionUserInfo::setNickName (const QString & szNickName) [inline, protected]
Referenced by KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviIrcConnection::nickChange(), KviIrcServerParser::parseLoginNicknameProblem(), and KviIrcServerParser::parseNumeric001().
void KviIrcConnectionUserInfo::setPassword (const QString & szPassword) [inline, protected]
Referenced by KviIrcConnection::loginToIrcServer().
void KviIrcConnectionUserInfo::setRealName (const QString & szRealName) [inline, protected]
Referenced by KviIrcConnection::useRealName().
void KviIrcConnectionUserInfo::setUnmaskedHostName (const QString & szHostName) [inline, protected]
Referenced by KviIrcServerParser::parseNumeric001().
void KviIrcConnectionUserInfo::setUserMode (const QString & szUserMode) [inline, protected]
void KviIrcConnectionUserInfo::setUserName (const QString & szUserName) [inline, protected]
Referenced by KviIrcConnection::loginToIrcServer(), KviIrcConnection::useProfileData(), and KviIrcConnection::userInfoReceived().
const QString& KviIrcConnectionUserInfo::unmaskedHostName () [inline]
Referenced by KviIrcConnection::userInfoReceived().
const QString& KviIrcConnectionUserInfo::userMode () [inline]
Referenced by KviIrcContextDisplay::drawContents(), KviConsoleWindow::fillStatusString(), KviStatusBar::mouseDoubleClickEvent(), KviStatusBar::setPermanentMessage(), and KviIrcContextDisplay::tipRequest().
const QString& KviIrcConnectionUserInfo::userName () [inline]
Referenced by avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), KviIrcConnection::currentUserName(), dcc_fill_local_nick_user_host(), dcc_kvs_parse_default_parameters(), KviIrcConnection::loginToIrcServer(), KviStatusBar::mouseDoubleClickEvent(), KviConsoleWindow::outputPrivmsg(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseChannelMode(), and KviIrcServerParser::parseCtcpRequestFinger().
Friends And Related Function Documentation
friend class KviConsoleWindow [friend]
friend class KviIrcConnection [friend]
friend class KviIrcServerParser [friend]
Member Data Documentation
bool KviIrcConnectionUserInfo::m_bAway [private]
Referenced by KviIrcConnectionUserInfo(), setAway(), and setBack().
QString KviIrcConnectionUserInfo::m_szAwayReason [private]
QString KviIrcConnectionUserInfo::m_szHostIp [private]
QString KviIrcConnectionUserInfo::m_szHostName [private]
QString KviIrcConnectionUserInfo::m_szLocalHostIp [private]
QString KviIrcConnectionUserInfo::m_szNickBeforeAway [private]
Referenced by setAway(), and setBack().
QString KviIrcConnectionUserInfo::m_szNickName [private]
Referenced by setAway().
QString KviIrcConnectionUserInfo::m_szPassword [private]
QString KviIrcConnectionUserInfo::m_szRealName [private]
QString KviIrcConnectionUserInfo::m_szUnmaskedHostName [private]
QString KviIrcConnectionUserInfo::m_szUserMode [private]
Referenced by addUserMode(), hasUserMode(), and removeUserMode().
QString KviIrcConnectionUserInfo::m_szUserName [private]
kvi_time_t KviIrcConnectionUserInfo::m_tAway [private]
Referenced by setAway().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionUserInfo.h
src/kvirc/kernel/KviIrcConnectionUserInfo.cpp