KVIrc: KviTalGroupBox Class Reference
KviTalGroupBox Class Reference
Toolkit Abstraction Layer: groupbox class.
#include <KviTalGroupBox.h>
Public Member Functions
void addSpace (int iSpace)
Adds a space.
int insideMargin ()
Returns the inside margin.
int insideSpacing ()
Returns the inside spacing.
KviTalGroupBox (QWidget *pParent, char *pcName=0)
Constructs the groupbox object.
KviTalGroupBox (QWidget *pParent=0)
Constructs the groupbox object.
KviTalGroupBox (const QString &szTitle, QWidget *pParent=0)
Constructs the groupbox object.
KviTalGroupBox (Qt::Orientation orientation, QWidget *pParent=0)
Constructs the groupbox object.
KviTalGroupBox (Qt::Orientation orientation, const QString &szTitle, QWidget *pParent=0)
Constructs the groupbox object.
void setInsideMargin (int iMargin)
Sets the inside margin.
void setInsideSpacing (int iSpacing)
Sets the inside spacing.
void setLayout (QLayout *newLayout)
Sets a new layout.
void setOrientation (Qt::Orientation orientation)
Sets the orientation.
~KviTalGroupBox ()
Destroys the groupbox object.
Protected Member Functions
virtual void childEvent (QChildEvent *e)
Protected Attributes
QLayout * m_pLayout
Qt::Orientation mOrientation
Detailed Description
Toolkit Abstraction Layer: groupbox class.
Constructor & Destructor Documentation
KviTalGroupBox::KviTalGroupBox (QWidget * pParent, char * pcName = 0)
Constructs the groupbox object.
Parameters
pParent The parent object
pcName the name of the groupbox
Returns
KviTalGroupBox
References m_pLayout.
KviTalGroupBox::KviTalGroupBox (QWidget * pParent = 0)
Constructs the groupbox object.
Parameters
pParent The parent object
Returns
KviTalGroupBox
References m_pLayout.
KviTalGroupBox::KviTalGroupBox (const QString & szTitle, QWidget * pParent = 0)
Constructs the groupbox object.
Parameters
szTitle The title of the groupbox
pParent The parent object
Returns
KviTalGroupBox
References m_pLayout.
KviTalGroupBox::KviTalGroupBox (Qt::Orientation orientation, QWidget * pParent = 0)
Constructs the groupbox object.
Parameters
orientation The orientation of the groupbox
pParent The parent object
Returns
KviTalGroupBox
References m_pLayout.
KviTalGroupBox::KviTalGroupBox (Qt::Orientation orientation, const QString & szTitle, QWidget * pParent = 0)
Constructs the groupbox object.
Parameters
orientation The orientation of the groupbox
szTitle The title of the groupbox
pParent The parent object
Returns
KviTalGroupBox
References m_pLayout, and mOrientation.
KviTalGroupBox::~KviTalGroupBox () default
Destroys the groupbox object.
Member Function Documentation
void KviTalGroupBox::addSpace (int iSpace)
Adds a space.
Parameters
iSpace The space in pixels
Returns
void
References m_pLayout, and mOrientation.
void KviTalGroupBox::childEvent (QChildEvent * e) protected virtual
References m_pLayout.
int KviTalGroupBox::insideMargin () inline
Returns the inside margin.
Returns
int
int KviTalGroupBox::insideSpacing () inline
Returns the inside spacing.
Returns
int
void KviTalGroupBox::setInsideMargin (int iMargin) inline
Sets the inside margin.
Parameters
iMargin The margin in pixels
Returns
void
void KviTalGroupBox::setInsideSpacing (int iSpacing) inline
Sets the inside spacing.
Parameters
iSpacing The spacing in pixels
Returns
void
Referenced by ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions().
void KviTalGroupBox::setLayout (QLayout * newLayout)
Sets a new layout.
Parameters
newLayout The new layout
Returns
void
References m_pLayout.
Referenced by IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), OptionsWidget_highlighting::OptionsWidget_highlighting(), and OptionsWidget_textEncoding::OptionsWidget_textEncoding().
void KviTalGroupBox::setOrientation (Qt::Orientation orientation)
Sets the orientation.
Parameters
orientation The orientation :)
Returns
void
References m_pLayout, and mOrientation.
Referenced by KvsObject_groupBox::init().
Member Data Documentation
QLayout* KviTalGroupBox::m_pLayout protected
Referenced by addSpace(), childEvent(), KviTalGroupBox(), setLayout(), and setOrientation().
Qt::Orientation KviTalGroupBox::mOrientation protected
Referenced by addSpace(), KviTalGroupBox(), and setOrientation().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalGroupBox.h
src/kvilib/tal/KviTalGroupBox.cpp