KVIrc: KviStatusBarAppletDescriptor Class Reference
KviStatusBarAppletDescriptor Class Reference
#include <kvi_statusbarapplet.h>
Public Member Functions
QPixmap * icon ()
int id ()
const QString & internalName ()
KviStatusBarAppletDescriptor (const QString &szVisibleName, const QString &szInternalName, CreateAppletCallback pProc, const QString &szPreloadModule=QString(), const QPixmap &pixIcon=QPixmap())
const QString & preloadModule ()
const QString & visibleName ()
virtual ~KviStatusBarAppletDescriptor ()
Protected Member Functions
KviStatusBarApplet * create (KviStatusBar *pBar)
void registerApplet (KviStatusBarApplet *a)
void unregisterApplet (KviStatusBarApplet *a)
Protected Attributes
int m_iId
KviPointerList
< KviStatusBarApplet > * m_pAppletList
QPixmap * m_pIcon
CreateAppletCallback m_pProc
QString m_szInternalName
QString m_szPreloadModule
QString m_szVisibleName
Friends
class KviStatusBar
class KviStatusBarApplet
Constructor & Destructor Documentation
KviStatusBarAppletDescriptor::KviStatusBarAppletDescriptor (const QString & szVisibleName, const QString & szInternalName, CreateAppletCallback pProc, const QString & szPreloadModule = QString(), const QPixmap & pixIcon = QPixmap())
References m_iId, m_pAppletList, m_pIcon, m_pProc, m_szInternalName, m_szPreloadModule, m_szVisibleName, and KviPointerList< T >::setAutoDelete().
KviStatusBarAppletDescriptor::~KviStatusBarAppletDescriptor () [virtual]
References KviPointerList< T >::first(), m_pAppletList, and m_pIcon.
Member Function Documentation
KviStatusBarApplet * KviStatusBarAppletDescriptor::create (KviStatusBar * pBar) [protected]
References m_pProc.
Referenced by KviStatusBar::createApplet().
QPixmap* KviStatusBarAppletDescriptor::icon () [inline]
int KviStatusBarAppletDescriptor::id () [inline]
const QString& KviStatusBarAppletDescriptor::internalName () [inline]
Referenced by KviStatusBar::registerAppletDescriptor().
const QString& KviStatusBarAppletDescriptor::preloadModule () [inline]
void KviStatusBarAppletDescriptor::registerApplet (KviStatusBarApplet * a) [protected]
References KviPointerList< T >::append(), and m_pAppletList.
Referenced by KviStatusBarApplet::KviStatusBarApplet().
void KviStatusBarAppletDescriptor::unregisterApplet (KviStatusBarApplet * a) [protected]
References m_pAppletList, and KviPointerList< T >::removeRef().
Referenced by KviStatusBarApplet::~KviStatusBarApplet().
const QString& KviStatusBarAppletDescriptor::visibleName () [inline]
Referenced by KviStatusBar::contextPopupAboutToShow(), and KviStatusBar::tipRequest().
Friends And Related Function Documentation
friend class KviStatusBar [friend]
friend class KviStatusBarApplet [friend]
Member Data Documentation
int KviStatusBarAppletDescriptor::m_iId [protected]
Referenced by KviStatusBarAppletDescriptor().
KviPointerList<KviStatusBarApplet>* KviStatusBarAppletDescriptor::m_pAppletList [protected]
Referenced by KviStatusBarAppletDescriptor(), registerApplet(), unregisterApplet(), and ~KviStatusBarAppletDescriptor().
QPixmap* KviStatusBarAppletDescriptor::m_pIcon [protected]
Referenced by KviStatusBarAppletDescriptor(), and ~KviStatusBarAppletDescriptor().
CreateAppletCallback KviStatusBarAppletDescriptor::m_pProc [protected]
Referenced by create(), and KviStatusBarAppletDescriptor().
QString KviStatusBarAppletDescriptor::m_szInternalName [protected]
Referenced by KviStatusBarAppletDescriptor().
QString KviStatusBarAppletDescriptor::m_szPreloadModule [protected]
Referenced by KviStatusBarAppletDescriptor().
QString KviStatusBarAppletDescriptor::m_szVisibleName [protected]
Referenced by KviStatusBarAppletDescriptor().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_statusbarapplet.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_statusbarapplet.cpp