KVIrc: KviConsoleWindow Class Reference
KviConsoleWindow Class Reference
#include <KviConsoleWindow.h>
Public Types
enum OutputPrivmsgFlags { NoWindowFlashing = 1, NoNotifier = 2, NoHighlighting = 4, NoNotifications = 7 }
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Slots
void executeInternalCommand (int index)
void recentUrlsChanged ()
void updateUri ()
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void reloadImages ()
void savePropertiesAsDefault ()
void undock ()
Public Member Functions
KviWindow * activeWindow ()
void addHighlightedChannel (const QString &szChan)
Adds a channel to the highlight list.
int applyHighlighting (KviWindow *wnd, int type, const QString &nick, const QString &user, const QString &host, const QString &szMsg)
void avatarChanged (KviAvatar *avatar, const QString &nick, const QString &user, const QString &host, const QString &textLine)
void avatarChangedUpdateWindows (const QString &nick, const QString &textLine)
void checkDefaultAvatar (KviIrcUserEntry *e, const QString &nick, const QString &user, const QString &host)
void completeChannel (const QString &word, KviPointerList< QString > *matches)
void completeServer (const QString &word, KviPointerList< QString > *matches)
void connectionAttached ()
void connectionDetached ()
bool connectionInProgress ()
KviIrcContext * context ()
KviAvatar * currentAvatar ()
QString currentNetworkName ()
KviAvatar * defaultAvatarFromOptions ()
void getUserTipText (const QString &nick, KviIrcUserEntry *e, QString &buffer)
bool isConnected ()
bool isHighlightedChannel (const QString &szChan)
Returns true if the channel is highlighted.
bool isIPv6Connection ()
bool isNotConnected ()
KviUserListView * notifyListView ()
void outputPrivmsg (KviWindow *wnd, int type, const QString &nick, const QString &user, const QString &host, const QString &msg, int iFlags=0, const QString &prefix=QString(), const QString &suffix=QString(), const QDateTime &datetime=QDateTime())
void removeHighlightedChannel (const QString &szChan)
Removes a channel from the highlight list.
void resetAvatarForMatchingUsers (KviRegisteredUser *u)
int selectedCount ()
KviAvatar * setAvatar (const QString &nick, const QString &user, const QString &host, const QString &szLocalPath, const QString &szName)
void setAvatarFromOptions ()
KviIrcContext::State state ()
const QString & statusString ()
void terminateConnectionRequest (bool bForce=false, const char *quitMsg=0)
~KviConsoleWindow ()
Public Member Functions inherited from KviWindow
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0, const QDateTime &datetime=QDateTime())
bool isChannel () const
bool isConsole () const
bool isDocked ()
bool isQuery () const
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, QString szFmt,...)
void output (int iMsgType, const QDateTime &datetime, const char *pcFormat,...)
void output (int iMsgType, const QDateTime &datetime, const kvi_wchar_t *pwFormat,...)
void output (int iMsgType, const QDateTime &datetime, QString szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual KviWindow * outputProxy ()
virtual void ownAction (const QString &)
virtual void ownMessage (const QString &, bool=true)
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
void setWindowTitle (QString &szTitle)
KviTalSplitter * splitter ()
Returns the splitter of this window.
virtual const QString & target ()
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Protected Slots
void ircUriChanged (const QString &)
void textViewRightClicked ()
void toggleNotifyView ()
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual void applyOptions ()
virtual void closeEvent (QCloseEvent *e)
void destroyConnection ()
virtual void fillCaptionBuffers ()
void fillStatusString ()
virtual void getBaseLogFileName (QString &buffer)
virtual void getWindowListTipText (QString &buffer)
KviConsoleWindow (int iFlags)
virtual void loadProperties (KviConfigurationFile *cfg)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfigurationFile *cfg)
void showNotifyList (bool bShow, bool bIgnoreSizeChange=false)
virtual QSize sizeHint () const
virtual void triggerCreationEvents ()
int triggerOnHighlight (KviWindow *wnd, int type, const QString &nick, const QString &user, const QString &host, const QString &szMsg, const QString &trigger)
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void inputMethodEvent (QInputMethodEvent *e)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual void preprocessMessage (QString &szMessage)
void setType (Type eType)
virtual void triggerDestructionEvents ()
virtual void youAreDocked ()
virtual void youAreUndocked ()
Static Protected Member Functions
static int getSmartColorHashForNick (QString *szNick)
Protected Attributes
int m_iFlags
KviThemedComboBox * m_pAddressEdit
KviIrcContext * m_pContext
KviUserListView * m_pNotifyListView
KviWindowToolPageButton * m_pNotifyViewButton
QStringList * m_pTmpHighLightedChannels
QList< int > m_SplitterSizesList
QString m_szOwnSmartColor
QString m_szStatusString
Protected Attributes inherited from KviWindow
bool m_bIsDocked
bool m_bProcessingInputEvent
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Friends
class KviChannelWindow
class KviIrcContext
class KviIrcSocket
class KviMainWindow
class KviQueryWindow
Additional Inherited Members
Signals inherited from KviWindow
void windowNameChanged ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Member Enumeration Documentation
enum KviConsoleWindow::OutputPrivmsgFlags
Enumerator
NoWindowFlashing
NoNotifier
NoHighlighting
NoNotifications
Constructor & Destructor Documentation
KviConsoleWindow::KviConsoleWindow (int iFlags) protected
References __tr2qs, KviTalToolTip::add(), connect(), g_pApp, g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::HideListView, KVI_CONSOLE_FLAG_FIRSTINAPP, KVI_OPTION_BOOL, KviOption_boolAutoLogConsole, KviTalSplitter, KviIconManager::ShowListView, and KviIconManager::Url.
KviConsoleWindow::~KviConsoleWindow ()
References context(), KviEvent_OnIrcContextDestroyed, KVS_TRIGGER_EVENT_0, m_pContext, m_pTmpHighLightedChannels, and KviIrcContext::terminateConnectionRequest().
Member Function Documentation
KviWindow * KviConsoleWindow::activeWindow ()
References KviWindow::console(), and g_pActiveWindow.
Referenced by KviIrcServerParser::echoCtcpReply(), KviIrcServerParser::echoCtcpRequest(), KviKvsCoreFunctions::KVSCF(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviIrcServerParser::parseCtcpReplyPing(), KviIrcServerParser::parseCtcpRequestAction(), KviIrcServerParser::parseLiteralInvite(), KviIrcServerParser::parseLiteralMode(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseLiteralWallops(), KviIrcServerParser::parseNumeric367(), KviIrcServerParser::parseNumeric368(), KviIrcServerParser::parseNumeric486(), KviIrcServerParser::parseNumericAway(), KviIrcServerParser::parseNumericBackFromAway(), KviIrcServerParser::parseNumericChannelModeIs(), KviIrcServerParser::parseNumericChanUrl(), KviIrcServerParser::parseNumericCodePageScheme(), KviIrcServerParser::parseNumericCreationTime(), KviIrcServerParser::parseNumericEndOfNames(), KviIrcServerParser::parseNumericEndOfQuietList(), KviIrcServerParser::parseNumericEndOfWho(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericEndOfWhowas(), KviIrcServerParser::parseNumericForward(), KviIrcServerParser::parseNumericHiddenHost(), KviIrcServerParser::parseNumericIsOn(), KviIrcServerParser::parseNumericNames(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNotEnoughParams(), KviIrcServerParser::parseNumericNoTopic(), KviIrcServerParser::parseNumericOftcEndOfQuietList(), KviIrcServerParser::parseNumericOftcQuietList(), KviIrcServerParser::parseNumericPasswordIncorrect(), KviIrcServerParser::parseNumericQuietList(), KviIrcServerParser::parseNumericSnomask(), KviIrcServerParser::parseNumericTopic(), KviIrcServerParser::parseNumericTopicWhoTime(), KviIrcServerParser::parseNumericTryAgain(), KviIrcServerParser::parseNumericUnknownCommand(), KviIrcServerParser::parseNumericUserhost(), KviIrcServerParser::parseNumericUserMode(), KviIrcServerParser::parseNumericUsersDontMatch(), KviIrcServerParser::parseNumericWatch(), KviIrcServerParser::parseNumericWhoisActually(), KviIrcServerParser::parseNumericWhoisAuth(), KviIrcServerParser::parseNumericWhoisAway(), KviIrcServerParser::parseNumericWhoisChannels(), KviIrcServerParser::parseNumericWhoisIdle(), KviIrcServerParser::parseNumericWhoisOther(), KviIrcServerParser::parseNumericWhoisRegistered(), KviIrcServerParser::parseNumericWhoisServer(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhoReply(), KviIrcServerParser::parseNumericWhospcrpl(), KviIrcServerParser::parseNumericWhowasUser(), KviIrcConnection::sendData(), and KviIrcConnection::sendFmtData().
void KviConsoleWindow::addHighlightedChannel (const QString & szChan)
Adds a channel to the highlight list.
Parameters
szChan The channel name
Returns
void
References m_pTmpHighLightedChannels.
int KviConsoleWindow::applyHighlighting (KviWindow * wnd, int type, const QString & nick, const QString & user, const QString & host, const QString & szMsg)
References KviWindow::Channel, KviWindow::connection(), KviRegisteredUser::getBoolProperty(), isHighlightedChannel(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_STRINGLIST, KviOption_boolAlwaysHighlightNick, KviOption_boolCaseSensitiveHighlighting, KviOption_boolUseFullWordHighlighting, KviOption_boolUseWordHighlighting, KviOption_stringlistHighlightWords, KviOption_stringWordSplitters, KviIrcConnectionUserInfo::nickName(), KviIrcUserDataBase::registeredUser(), KviControlCodes::stripControlBytes(), triggerOnHighlight(), KviWindow::type(), u, KviIrcConnection::userDataBase(), KviIrcConnection::userInfo(), and KviWindow::windowName().
Referenced by outputPrivmsg(), and KviIrcServerParser::parseCtcpRequestAction().
void KviConsoleWindow::applyOptions () protected virtual
Reimplemented from KviWindow.
References KviThemedComboBox::applyOptions(), KviInput::applyOptions(), KviIrcView::applyOptions(), KviUserListView::applyOptions(), KviWindow::applyOptions(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolUseSpecifiedSmartColorForOwnNick, KviOption_uintUserIrcViewOwnBackground, KviOption_uintUserIrcViewOwnForeground, m_pAddressEdit, KviWindow::m_pInput, KviWindow::m_pIrcView, m_pNotifyListView, m_szOwnSmartColor, and KviControlCodes::Transparent.
void KviConsoleWindow::avatarChanged (KviAvatar * avatar, const QString & nick, const QString & user, const QString & host, const QString & textLine)
References avatarChangedUpdateWindows(), KviWindow::connection(), currentNetworkName(), KviQString::equalCI(), KviAvatar::identificationString(), KviAvatarCache::instance(), KVI_OPTION_BOOL, KviOption_boolSetLastAvatarAsDefaultForRegisteredUsers, KviIrcUserDataBase::registeredUser(), KviAvatarCache::remove(), KviAvatarCache::replace(), KviRegisteredUser::setProperty(), u, and KviIrcConnection::userDataBase().
Referenced by avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), currentAvatar(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseLiteralJoin(), setAvatar(), and setAvatarFromOptions().
void KviConsoleWindow::avatarChangedUpdateWindows (const QString & nick, const QString & textLine)
References _OUTPUT_QUIET, KviUserListView::avatarChanged(), c, KviIrcConnection::channelList(), KviWindow::connection(), first(), KviPointerList< T >::first(), KVI_OUT_AVATAR, m_pNotifyListView, KviPointerList< T >::next(), q, and KviIrcConnection::queryList().
Referenced by avatarChanged(), checkDefaultAvatar(), and resetAvatarForMatchingUsers().
void KviConsoleWindow::checkDefaultAvatar (KviIrcUserEntry * e, const QString & nick, const QString & user, const QString & host)
References avatarChangedUpdateWindows(), KviWindow::connection(), currentNetworkName(), KviFileUtils::extractFileName(), g_pIconManager, KviIconManager::getAvatar(), KviRegisteredUser::getProperty(), KviAvatarCache::instance(), KviAvatarCache::lookup(), KviIrcUserDataBase::registeredUser(), KviAvatarCache::remove(), KviIrcUserEntry::setAvatar(), u, and KviIrcConnection::userDataBase().
Referenced by KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhospcrpl(), and KviQueryWindow::setTarget().
void KviConsoleWindow::closeEvent (QCloseEvent * e) protected virtual
Reimplemented from KviWindow.
References __tr2qs, KviWindow::closeEvent(), KviIrcContext::Connected, KviMainWindow::consoleCount(), context(), g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KviOption_boolAlwaysDisconnectClosingConnectedConsole, KviOption_boolAlwaysQuitKVIrcClosingLastConsole, KviIrcContext::state(), KviIrcContext::terminateConnectionRequest(), and KviMessageBox::warning().
void KviConsoleWindow::completeChannel (const QString & word, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), currentNetworkName(), KviQString::equalCIN(), g_pApp, and KviApplication::recentChannelsForNetwork().
Referenced by KviInputEditor::completion().
void KviConsoleWindow::completeServer (const QString & word, KviPointerList< QString > * matches)
References KviPointerList< T >::append(), KviQString::cutFromLast(), KviQString::cutToFirst(), KviQString::equalCIN(), KVI_OPTION_STRINGLIST, and KviOption_stringlistRecentServers.
Referenced by KviInputEditor::completion().
void KviConsoleWindow::connectionAttached ()
References connect(), KviIrcContext::connection(), KviWindow::connection(), m_pContext, m_pNotifyListView, KviUserListView::setUserDataBase(), and updateUri().
Referenced by KviIrcContext::connectToCurrentServer().
void KviConsoleWindow::connectionDetached ()
References m_pNotifyListView, KviUserListView::partAll(), and KviUserListView::setUserDataBase().
Referenced by KviIrcContext::destroyConnection().
bool KviConsoleWindow::connectionInProgress ()
References context(), KviIrcContext::Idle, and state().
Referenced by KviIrcUrl::run().
KviIrcContext* KviConsoleWindow::context () inline
Referenced by closeEvent(), KviWindow::connection(), connectionInProgress(), LinksWindow::connectionStateChange(), ListWindow::connectionStateChange(), KviWindow::context(), context_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_ircContext(), KviWindowListButton::drawButtonLabel(), KviIrcContextDisplay::drawContents(), SocketSpyWindow::fillCaptionBuffers(), LinksWindow::fillCaptionBuffers(), ListWindow::fillCaptionBuffers(), KviTrayIconWidget::fillContextPopup(), fillStatusString(), KviApplication::findConsole(), getBaseLogFileName(), KviQueryWindow::getBaseLogFileName(), getWindowListTipText(), isNotConnected(), LinksWindow::LinksWindow(), ListWindow::ListWindow(), KviTreeWindowListItemDelegate::paint(), KviIrcServerParser::parseNumericEndOfLinks(), KviIrcServerParser::parseNumericLinks(), KviIrcServerParser::parseNumericList(), KviIrcServerParser::parseNumericListEnd(), KviIrcServerParser::parseNumericListStart(), KviIrcContextDisplay::tipRequest(), ~KviConsoleWindow(), LinksWindow::~LinksWindow(), and ListWindow::~ListWindow().
KviAvatar * KviConsoleWindow::currentAvatar ()
References a, KviIrcUserEntry::avatar(), avatarChanged(), KviWindow::connection(), defaultAvatarFromOptions(), e, KviIrcUserDataBase::find(), KviIrcUserEntry::setAvatar(), and KviIrcConnection::userDataBase().
Referenced by KviIrcServerParser::parseCtcpRequestAvatar().
QString KviConsoleWindow::currentNetworkName () inline
References KviWindow::connection().
Referenced by avatarChanged(), checkDefaultAvatar(), completeChannel(), LinksWindow::connectionStateChange(), ListWindow::connectionStateChange(), KviTrayIconWidget::fillContextPopup(), ChannelsJoinDialog::fillListView(), KviApplication::fillRecentChannelsPopup(), KviQueryWindow::getBaseLogFileName(), KviQueryWindow::pasteLastLog(), and KviChannelWindow::pasteLastLog().
KviAvatar * KviConsoleWindow::defaultAvatarFromOptions ()
References KviAvatar::isValid(), KVI_OPTION_PIXMAP, KVI_OPTION_STRING, KviOption_pixmapMyAvatar, and KviOption_stringMyAvatar.
Referenced by currentAvatar(), KviIrcConnection::loginToIrcServer(), KviIrcServerParser::parseLiteralJoin(), and setAvatarFromOptions().
void KviConsoleWindow::destroyConnection () protected
void KviConsoleWindow::executeInternalCommand (int index) slot
References kvi_getInternalCommandBuffer(), and KviKvsScript::run().
void KviConsoleWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References fillStatusString(), KviWindow::m_szPlainTextCaption, m_szStatusString, and KviWindow::windowName().
void KviConsoleWindow::fillStatusString () protected
References __tr2qs, KviIrcContext::Connected, KviIrcContext::Connecting, KviWindow::connection(), context(), KviIrcContext::Idle, KviIrcContext::LoggingIn, m_szStatusString, KviIrcConnectionServerInfo::name(), KviIrcConnectionUserInfo::nickName(), KviIrcContext::PendingReconnection, KviIrcConnection::serverInfo(), state(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userMode().
Referenced by fillCaptionBuffers(), and getWindowListTipText().
void KviConsoleWindow::getBaseLogFileName (QString & buffer) protected virtual
Reimplemented from KviWindow.
References context().
static int KviConsoleWindow::getSmartColorHashForNick (QString * szNick) static protected
void KviConsoleWindow::getUserTipText (const QString & nick, KviIrcUserEntry * e, QString & buffer)
References __tr2qs, KviIrcUserEntry::accountName(), KviIrcUserEntry::avatar(), KviWindow::connection(), KviRegisteredUserDataBase::findMatchingMask(), g_pRegisteredUserDataBase, KviIrcUserEntry::gender(), KviRegisteredUser::getProperty(), KviRegisteredUser::group(), KviIrcUserEntry::hasAccountName(), KviIrcUserEntry::hasHops(), KviIrcUserEntry::hasRealName(), KviIrcUserEntry::hasServer(), KviIrcUserEntry::hops(), KviIrcUserEntry::host(), KviIrcUserEntry::isAway(), KviAvatar::localPath(), KviIrcUserEntry::Male, KviRegisteredUserMask::mask(), KviIrcMask::mask(), KviRegisteredUser::name(), KviIrcUserEntry::realName(), KviIrcUserEntry::server(), KviAvatar::size(), KviControlCodes::stripControlBytes(), KviQString::toHtmlEscaped(), u, KviIrcUserEntry::Unknown, KviRegisteredUserMask::user(), and KviIrcUserEntry::user().
Referenced by KviIrcView::doLinkToolTip(), KviQueryWindow::getWindowListTipText(), and KviUserListView::maybeTip().
void KviConsoleWindow::getWindowListTipText (QString & buffer) protected virtual
Reimplemented from KviWindow.
References __tr2qs, KviIrcConnection::channelList(), KviIrcContext::Connected, KviWindow::connection(), context(), KviPointerList< T >::count(), END_TABLE_BOLD_ROW, fillStatusString(), KviTimeUtils::formatTimeInterval(), KVI_OPTION_UINT, kvi_secondsSince, KviOption_uintOutputDatetimeFormat, m_szStatusString, KviTimeUtils::NoLeadingEmptyIntervals, KviTimeUtils::NoLeadingZeroes, KviIrcConnection::queryList(), START_TABLE_BOLD_ROW, START_TABLE_NORMAL_ROW, and state().
void KviConsoleWindow::ircUriChanged (const QString & text) protected slot
References __tr2qs, KviIrcUrl::CurrentContext, KviIrcUrl::InvalidProtocol, KviIrcUrl::InvalidUrl, KviWindow::m_pInput, KviIrcUrl::run(), KviInput::setFocus(), and KviMessageBox::warning().
bool KviConsoleWindow::isConnected () inline
References KviWindow::context(), and KviIrcContext::isConnected().
Referenced by KviChannelWindow::closeEvent(), dcc_kvs_get_listen_ip_address(), dcc_kvs_parse_default_parameters(), KviTrayIconWidget::doAway(), KviIrcContextDisplay::drawContents(), KviTrayIconWidget::fillContextPopup(), KviApplication::fillRecentChannelsPopup(), KviApplication::fillRecentNicknamesPopup(), KviApplication::findConsole(), KviWindowListBase::getTextForConsole(), KviKvsCoreSimpleCommands::KVSCSC(), myIconPtr(), KviIrcServerParser::parseNumericNicknameProblem(), KviIrcServerParser::parseNumericUnavailResource(), KviChangeUserModeAction::popupActivated(), LinksWindow::requestLinks(), ListWindow::requestList(), ListWindow::stoplistdownload(), and KviApplication::topmostConnectedConsole().
bool KviConsoleWindow::isHighlightedChannel (const QString & szChan) inline
Returns true if the channel is highlighted.
Parameters
szChan The channel name
Returns
bool
Referenced by applyHighlighting().
bool KviConsoleWindow::isIPv6Connection () inline
References KviWindow::connection(), KviIrcServer::isIPv6(), KVI_ASSERT, KviIrcConnectionTarget::server(), and KviIrcConnection::target().
Referenced by dcc_kvs_get_listen_ip_address(), and KviIrcServerParser::parseCtcpRequestDcc().
bool KviConsoleWindow::isNotConnected () inline
References context(), KviIrcContext::Idle, and state().
Referenced by tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), and tmphighlight_kvs_fnc_isnickhighlighted().
void KviConsoleWindow::loadProperties (KviConfigurationFile * cfg) protected virtual
Reimplemented from KviWindow.
References KviWindow::loadProperties(), KviWindow::m_pSplitter, m_SplitterSizesList, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readIntListEntry(), and showNotifyList().
QPixmap * KviConsoleWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References KviIconManager::Console, g_pIconManager, KviIconManager::getSmallIcon(), isConnected(), and KviIconManager::Links.
KviUserListView* KviConsoleWindow::notifyListView () inline
Referenced by KviIsOnNotifyListManager::doMatchUser(), KviWatchNotifyListManager::doMatchUser(), KviIsOnNotifyListManager::handleIsOn(), KviStupidNotifyListManager::handleIsOn(), KviWatchNotifyListManager::handleWatchReply(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviIrcConnection::nickChange(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviIrcServerParser::parseLoginNicknameProblem(), KviIsOnNotifyListManager::start(), KviStupidNotifyListManager::start(), KviWatchNotifyListManager::start(), KviIsOnNotifyListManager::stop(), KviStupidNotifyListManager::stop(), and KviWatchNotifyListManager::stop().
void KviConsoleWindow::outputPrivmsg (KviWindow * wnd, int type, const QString & nick, const QString & user, const QString & host, const QString & msg, int iFlags = 0, const QString & prefix = QString(), const QString & suffix = QString(), const QDateTime & datetime = QDateTime())
References KviQString::appendFormatted(), applyHighlighting(), KviControlCodes::Bold, KviWindow::Channel, KviWindow::connection(), KviWindow::demandAttention(), KviIrcUserDataBase::find(), g_pApp, KviNickColors::getSmartColor(), KviNickColors::getSmartColorForNick(), KviWindow::hasAttention(), KviIrcConnectionUserInfo::hostName(), KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_HIGHLIGHT, KVI_OUT_QUERYNOTICE, KVI_OUT_QUERYNOTICECRYPTED, KviOption_boolBoldedNicks, KviOption_boolColorNicks, KviOption_boolFlashWindowOnHighlightedMessages, KviOption_boolPopupNotifierOnHighlightedMessages, KviOption_boolShowChannelUserFlagInPrivmsgView, KviOption_boolShowUserAndHostInPrivmsgView, KviOption_boolStripMircColorsInUserMessages, KviOption_boolUseExtendedPrivmsgView, KviOption_boolUseSpecifiedSmartColorForOwnNick, KviOption_stringExtendedPrivmsgPostfix, KviOption_stringExtendedPrivmsgPrefix, KviOption_uintNotifierAutoHideTime, m_szOwnSmartColor, KviWindow::MainWindowIsVisible, KviIrcConnectionUserInfo::nickName(), NoHighlighting, NoNotifier, KviApplication::notifierMessage(), NoWindowFlashing, KviIrcUserEntry::setSmartNickColor(), KviIrcUserEntry::smartNickColor(), KviControlCodes::stripControlBytes(), KviQString::toHtmlEscaped(), KviWindow::type(), KviIrcConnection::userDataBase(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
Referenced by DccChatWindow::event(), DccVideoWindow::event(), KviKvsCoreSimpleCommands::KVSCSC(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), KviQueryWindow::ownMessage(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseLiteralNotice(), and KviIrcServerParser::parseLiteralPrivmsg().
void KviConsoleWindow::recentUrlsChanged () slot
References g_pIconManager, KviIconManager::getSmallIcon(), i, KVI_OPTION_STRINGLIST, KviOption_stringlistRecentIrcUrls, m_pAddressEdit, and KviIconManager::Url.
void KviConsoleWindow::removeHighlightedChannel (const QString & szChan)
Removes a channel from the highlight list.
Parameters
szChan The channel name
Returns
void
References m_pTmpHighLightedChannels.
void KviConsoleWindow::resetAvatarForMatchingUsers (KviRegisteredUser * u)
References a, avatarChangedUpdateWindows(), KviWindow::connection(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), e, g_pIconManager, KviIconManager::getAvatar(), KviRegisteredUser::getProperty(), and KviRegisteredUser::matchesFixed().
Referenced by KviApplication::resetAvatarForMatchingUsers().
void KviConsoleWindow::resizeEvent (QResizeEvent * e) protected virtual
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, and KviWindow::m_pSplitter.
void KviConsoleWindow::saveProperties (KviConfigurationFile * cfg) protected virtual
Reimplemented from KviWindow.
References m_pNotifyViewButton, KviWindow::m_pSplitter, m_SplitterSizesList, KviWindow::saveProperties(), and KviConfigurationFile::writeEntry().
int KviConsoleWindow::selectedCount () inline
References m_pNotifyListView, and KviUserListView::selectedCount().
KviAvatar * KviConsoleWindow::setAvatar (const QString & nick, const QString & user, const QString & host, const QString & szLocalPath, const QString & szName)
References __tr2qs, _OUTPUT_PARANOIC, avatarChanged(), KviWindow::connection(), e, KviQString::equalCI(), KviIrcUserDataBase::find(), g_pIconManager, KviIconManager::getAvatar(), KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasUser(), KviIrcUserEntry::host(), KVI_OUT_VERBOSE, KviWindow::output(), KviIrcUserEntry::setAvatar(), KviIrcUserEntry::user(), and KviIrcConnection::userDataBase().
Referenced by KviApplication::fileDownloadTerminated().
void KviConsoleWindow::setAvatarFromOptions ()
References a, avatarChanged(), KviWindow::connection(), defaultAvatarFromOptions(), e, KviIrcUserDataBase::find(), KviIrcUserEntry::setAvatar(), and KviIrcConnection::userDataBase().
Referenced by KviApplication::setAvatarFromOptions().
void KviConsoleWindow::showNotifyList (bool bShow, bool bIgnoreSizeChange = false) protected
References m_pNotifyListView, m_pNotifyViewButton, KviWindow::m_pSplitter, and m_SplitterSizesList.
Referenced by loadProperties(), and toggleNotifyView().
QSize KviConsoleWindow::sizeHint () const protected virtual
References KviInput::heightHint(), KviWindow::m_pInput, KviWindow::m_pIrcView, and KviIrcView::sizeHint().
KviIrcContext::State KviConsoleWindow::state () inline
References KviWindow::context(), and KviIrcContext::state().
Referenced by connectionInProgress(), fillStatusString(), getWindowListTipText(), and isNotConnected().
const QString& KviConsoleWindow::statusString () inline
Referenced by KviWindowListBase::getTextForConsole().
void KviConsoleWindow::terminateConnectionRequest (bool bForce = false, const char * quitMsg = 0)
void KviConsoleWindow::textViewRightClicked () protected slot
References KviEvent_OnConsolePopupRequest, and KVS_TRIGGER_EVENT_0.
void KviConsoleWindow::toggleNotifyView () protected slot
References m_pNotifyListView, and showNotifyList().
void KviConsoleWindow::triggerCreationEvents () protected virtual
Reimplemented from KviWindow.
References KviMainWindow::executeInternalCommand(), g_pMainWindow, KVI_CONSOLE_FLAG_FIRSTINAPP, KVI_CONSOLE_FLAG_FIRSTINFRAME, KVI_INTERNALCOMMAND_TIP_OPEN, KVI_OPTION_BOOL, KviEvent_OnFrameWindowCreated, KviEvent_OnIrcContextCreated, KviEvent_OnKVIrcStartup, KviOption_boolShowTipAtStartup, KVS_TRIGGER_EVENT_0, and m_iFlags.
int KviConsoleWindow::triggerOnHighlight (KviWindow * wnd, int type, const QString & nick, const QString & user, const QString & host, const QString & szMsg, const QString & trigger) protected
References KviWindow::connection(), KviWindow::hasAttention(), KviRegisteredUser::Highlight, KviRegisteredUser::isIgnoreEnabledFor(), KVI_OPTION_STRING, KVI_OUT_ACTION, KVI_OUT_HIGHLIGHT, KviEvent_OnHighlight, KviOption_stringOnHighlightedMessageSound, KVS_TRIGGER_EVENT_7_HALTED, KviIrcUserDataBase::registeredUser(), KviKvsScript::run(), u, and KviIrcConnection::userDataBase().
Referenced by applyHighlighting().
void KviConsoleWindow::updateUri () slot
References c, KviIrcConnection::channelList(), KviWindow::connection(), first(), i, KviIrcUrl::join(), KviPointerList< T >::last(), m_pAddressEdit, KviPointerList< T >::next(), KviIrcConnectionTarget::server(), and KviIrcConnection::target().
Referenced by connectionAttached().
Friends And Related Function Documentation
friend class KviChannelWindow friend
friend class KviIrcContext friend
friend class KviIrcSocket friend
friend class KviMainWindow friend
friend class KviQueryWindow friend
Member Data Documentation
int KviConsoleWindow::m_iFlags protected
Referenced by triggerCreationEvents().
KviThemedComboBox* KviConsoleWindow::m_pAddressEdit protected
Referenced by applyOptions(), recentUrlsChanged(), and updateUri().
KviIrcContext* KviConsoleWindow::m_pContext protected
Referenced by connectionAttached(), and ~KviConsoleWindow().
KviUserListView* KviConsoleWindow::m_pNotifyListView protected
Referenced by applyOptions(), avatarChangedUpdateWindows(), connectionAttached(), connectionDetached(), selectedCount(), showNotifyList(), and toggleNotifyView().
KviWindowToolPageButton* KviConsoleWindow::m_pNotifyViewButton protected
Referenced by saveProperties(), and showNotifyList().
QStringList* KviConsoleWindow::m_pTmpHighLightedChannels protected
Referenced by addHighlightedChannel(), removeHighlightedChannel(), and ~KviConsoleWindow().
QList<int> KviConsoleWindow::m_SplitterSizesList protected
Referenced by loadProperties(), saveProperties(), and showNotifyList().
QString KviConsoleWindow::m_szOwnSmartColor protected
Referenced by applyOptions(), and outputPrivmsg().
QString KviConsoleWindow::m_szStatusString protected
Referenced by fillCaptionBuffers(), fillStatusString(), and getWindowListTipText().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviConsoleWindow.h
src/kvirc/ui/KviConsoleWindow.cpp