KVIrc: KviRegisteredMask Class Reference
KviRegisteredMask Class Reference
#include <kvi_regusersdb.h>
Public Member Functions
KviRegisteredMask (KviRegisteredUser *u, KviIrcMask *m)
KviIrcMask * mask ()
int nonWildChars ()
KviRegisteredUser * user ()
~KviRegisteredMask ()
Private Attributes
int m_iMaskNonWildChars
KviIrcMask * m_pMask
KviRegisteredUser * m_pUser
Constructor & Destructor Documentation
KviRegisteredMask::KviRegisteredMask (KviRegisteredUser * u, KviIrcMask * m)
References m_iMaskNonWildChars, m_pMask, m_pUser, and KviIrcMask::nonWildChars().
KviRegisteredMask::~KviRegisteredMask () [inline]
Member Function Documentation
KviIrcMask* KviRegisteredMask::mask () [inline]
Referenced by KviConsole::getUserTipText(), and KviRegisteredUserDataBase::removeMask().
int KviRegisteredMask::nonWildChars () [inline]
Referenced by append_mask_to_list().
KviRegisteredUser* KviRegisteredMask::user () [inline]
Referenced by KviRegisteredUserDataBase::findMatchingUser(), KviRegisteredUserDataBase::findUserWithMask(), and KviConsole::getUserTipText().
Member Data Documentation
int KviRegisteredMask::m_iMaskNonWildChars [private]
Referenced by KviRegisteredMask().
KviIrcMask* KviRegisteredMask::m_pMask [private]
Referenced by KviRegisteredMask().
KviRegisteredUser* KviRegisteredMask::m_pUser [private]
Referenced by KviRegisteredMask().
The documentation for this class was generated from the following files:
src/kvilib/ext/kvi_regusersdb.h
src/kvilib/ext/kvi_regusersdb.cpp