KVIrc: KviTalToolTipHelper Class Reference
KviTalToolTipHelper Class Reference
#include <kvi_tal_tooltip.h>
Public Member Functions
KviTalToolTipHelper (KviTalToolTip *pToolTip, QWidget *pWidget)
~KviTalToolTipHelper ()
Protected Member Functions
virtual bool eventFilter (QObject *pObject, QEvent *pEvent)
void toolTipDying ()
Protected Attributes
KviTalToolTip * m_pToolTip
Friends
class KviTalToolTip
Constructor & Destructor Documentation
KviTalToolTipHelper::KviTalToolTipHelper (KviTalToolTip * pToolTip, QWidget * pWidget)
References m_pToolTip.
KviTalToolTipHelper::~KviTalToolTipHelper ()
References KviTalToolTip::helperDying(), and m_pToolTip.
Member Function Documentation
bool KviTalToolTipHelper::eventFilter (QObject * pObject, QEvent * pEvent) [protected, virtual]
References m_pToolTip, and KviTalToolTip::maybeTip().
void KviTalToolTipHelper::toolTipDying () [protected]
References m_pToolTip.
Referenced by KviTalToolTip::~KviTalToolTip().
Friends And Related Function Documentation
friend class KviTalToolTip [friend]
Member Data Documentation
KviTalToolTip* KviTalToolTipHelper::m_pToolTip [protected]
Referenced by eventFilter(), KviTalToolTipHelper(), toolTipDying(), and ~KviTalToolTipHelper().
The documentation for this class was generated from the following files:
src/kvilib/tal/kvi_tal_tooltip.h
src/kvilib/tal/kvi_tal_tooltip.cpp