KVIrc: ScriptEditorSyntaxHighlighter Class Reference
ScriptEditorSyntaxHighlighter Class Reference
#include <ScriptEditorImplementation.h>
Classes
struct KviScriptHighlightingRule
Public Member Functions
void highlightBlock (const QString &szText)
ScriptEditorSyntaxHighlighter (ScriptEditorWidget *pWidget)
QTextEdit * textEdit ()
void updateSyntaxtTextFormat ()
virtual ~ScriptEditorSyntaxHighlighter ()
Public Attributes
QTextEdit * m_pTextEdit
Private Attributes
QTextCharFormat bracketFormat
QRegExp commentEndExpression
QTextCharFormat commentFormat
QRegExp commentStartExpression
QTextCharFormat findFormat
QTextCharFormat functionFormat
QVector
< KviScriptHighlightingRule > highlightingRules
QTextCharFormat keywordFormat
QTextCharFormat normaltextFormat
QTextCharFormat punctuationFormat
QTextCharFormat variableFormat
Constructor & Destructor Documentation
ScriptEditorSyntaxHighlighter::ScriptEditorSyntaxHighlighter (ScriptEditorWidget * pWidget)
References bracketFormat, ScriptEditorSyntaxHighlighter::KviScriptHighlightingRule::format, functionFormat, highlightingRules, keywordFormat, ScriptEditorSyntaxHighlighter::KviScriptHighlightingRule::pattern, punctuationFormat, updateSyntaxtTextFormat(), and variableFormat.
ScriptEditorSyntaxHighlighter::~ScriptEditorSyntaxHighlighter () [virtual]
Member Function Documentation
void ScriptEditorSyntaxHighlighter::highlightBlock (const QString & szText)
References commentFormat, findFormat, ScriptEditorSyntaxHighlighter::KviScriptHighlightingRule::format, highlightingRules, keywordFormat, ScriptEditorWidget::m_szFind, ScriptEditorSyntaxHighlighter::KviScriptHighlightingRule::pattern, SKIP_SPACES, and textEdit().
QTextEdit* ScriptEditorSyntaxHighlighter::textEdit () [inline]
References m_pTextEdit.
Referenced by highlightBlock().
void ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat ()
References bracketFormat, commentFormat, findFormat, functionFormat, g_clrBracket(), g_clrComment(), g_clrFind(), g_clrFunction(), g_clrKeyword(), g_clrPunctuation(), g_clrVariable(), keywordFormat, punctuationFormat, and variableFormat.
Referenced by ScriptEditorSyntaxHighlighter().
Member Data Documentation
QTextCharFormat ScriptEditorSyntaxHighlighter::bracketFormat [private]
Referenced by ScriptEditorSyntaxHighlighter(), and updateSyntaxtTextFormat().
QRegExp ScriptEditorSyntaxHighlighter::commentEndExpression [private]
QTextCharFormat ScriptEditorSyntaxHighlighter::commentFormat [private]
Referenced by highlightBlock(), and updateSyntaxtTextFormat().
QRegExp ScriptEditorSyntaxHighlighter::commentStartExpression [private]
QTextCharFormat ScriptEditorSyntaxHighlighter::findFormat [private]
Referenced by highlightBlock(), and updateSyntaxtTextFormat().
QTextCharFormat ScriptEditorSyntaxHighlighter::functionFormat [private]
Referenced by ScriptEditorSyntaxHighlighter(), and updateSyntaxtTextFormat().
QVector<KviScriptHighlightingRule> ScriptEditorSyntaxHighlighter::highlightingRules [private]
Referenced by highlightBlock(), and ScriptEditorSyntaxHighlighter().
QTextCharFormat ScriptEditorSyntaxHighlighter::keywordFormat [private]
Referenced by highlightBlock(), ScriptEditorSyntaxHighlighter(), and updateSyntaxtTextFormat().
QTextEdit* ScriptEditorSyntaxHighlighter::m_pTextEdit
Referenced by textEdit().
QTextCharFormat ScriptEditorSyntaxHighlighter::normaltextFormat [private]
QTextCharFormat ScriptEditorSyntaxHighlighter::punctuationFormat [private]
Referenced by ScriptEditorSyntaxHighlighter(), and updateSyntaxtTextFormat().
QTextCharFormat ScriptEditorSyntaxHighlighter::variableFormat [private]
Referenced by ScriptEditorSyntaxHighlighter(), and updateSyntaxtTextFormat().
The documentation for this class was generated from the following files:
src/modules/editor/ScriptEditorImplementation.h
src/modules/editor/ScriptEditorImplementation.cpp