KVIrc: KviThemedLabel Class Reference
KviThemedLabel Class Reference
#include <KviThemedLabel.h>
Signals
void doubleClicked ()
Public Member Functions
void applyOptions ()
int dummyRead () const
KviThemedLabel (QWidget *par, KviWindow *pWindow, const char *name)
~KviThemedLabel ()
Protected Member Functions
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *event)
Properties
int TransparencyCapable
Private Attributes
KviWindow * m_pKviWindow
Constructor & Destructor Documentation
KviThemedLabel::KviThemedLabel (QWidget * par, KviWindow * pWindow, const char * name)
References applyOptions(), and m_pKviWindow.
KviThemedLabel::~KviThemedLabel ()
Member Function Documentation
void KviThemedLabel::applyOptions ()
References KviControlCodes::Bold, g_pApp, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_FONT, KVI_OPTION_MIRCCOLOR, KVI_OPTION_MSGTYPE, KVI_OUT_NONE, KviOption_boolUseCompositingForTransparency, KviOption_colorLabelBackground, KviOption_colorLabelForeground, KviOption_fontLabel, KviOsInfo::name(), and KviApplication::supportsCompositing().
Referenced by ListWindow::applyOptions(), LinksWindow::applyOptions(), KviTopicWidget::applyOptions(), and KviThemedLabel().
void KviThemedLabel::doubleClicked () [signal]
Referenced by mouseDoubleClickEvent().
int KviThemedLabel::dummyRead () const [inline]
void KviThemedLabel::mouseDoubleClickEvent (QMouseEvent * e) [protected, virtual]
References doubleClicked().
void KviThemedLabel::paintEvent (QPaintEvent * event) [protected, virtual]
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_uintGlobalTransparencyChildFadeFactor, m_pKviWindow, KviMainWindow::mdiManager(), KviWindow::mdiParent(), p, KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
Member Data Documentation
KviWindow* KviThemedLabel::m_pKviWindow [private]
Referenced by KviThemedLabel(), and paintEvent().
Property Documentation
int KviThemedLabel::TransparencyCapable [read]
The documentation for this class was generated from the following files:
src/kvirc/ui/KviThemedLabel.h
src/kvirc/ui/KviThemedLabel.cpp