KVIrc: KviKvsTreeNodeSpecialCommandUnset Class Reference
KviKvsTreeNodeSpecialCommandUnset Class Reference
#include <KviKvsTreeNodeSpecialCommandUnset.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandUnset (const QChar *pLocation, KviPointerList< KviKvsTreeNodeVariable > *pVarList)
~KviKvsTreeNodeSpecialCommandUnset ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommand
KviKvsTreeNodeSpecialCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeSpecialCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviPointerList
< KviKvsTreeNodeVariable > * m_pVariableList
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandUnset::KviKvsTreeNodeSpecialCommandUnset (const QChar * pLocation, KviPointerList< KviKvsTreeNodeVariable > * pVarList)
References KviPointerList< T >::first(), m_pVariableList, and KviPointerList< T >::next().
KviKvsTreeNodeSpecialCommandUnset::~KviKvsTreeNodeSpecialCommandUnset ()
References m_pVariableList.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandUnset::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandUnset::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
References KviPointerList< T >::first(), m_pVariableList, and KviPointerList< T >::next().
bool KviKvsTreeNodeSpecialCommandUnset::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviPointerList< T >::first(), m_pVariableList, KviPointerList< T >::next(), r, KviKvsRWEvaluationResult::result(), and KviKvsVariant::setNothing().
Member Data Documentation
KviPointerList<KviKvsTreeNodeVariable>* KviKvsTreeNodeSpecialCommandUnset::m_pVariableList private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandUnset(), and ~KviKvsTreeNodeSpecialCommandUnset().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandUnset.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandUnset.cpp