KVIrc: KviIrcServerParser Class Reference
KviIrcServerParser Class Reference
#include <KviIrcServerParser.h>
Public Member Functions
KviIrcServerParser ()
void parseMessage (const char *message, KviIrcConnection *pConnection)
~KviIrcServerParser ()
Static Public Member Functions
static const char * decodeCtcpEscape (const char *msg_ptr, KviCString &buffer)
static const char * decodeCtcpEscape (const char *msg_ptr, QByteArray &buffer)
static void encodeCtcpParameter (const char *param, QString &buffer, bool bSpaceBreaks=true)
static void encodeCtcpParameter (const char *param, KviCString &buffer, bool bSpaceBreaks=true)
static const char * extractCtcpParameter (const char *msg_ptr, QString &buffer, bool bSpaceBreaks=true, bool bSafeOnly=false)
static const char * extractCtcpParameter (const char *msg_ptr, KviCString &buffer, bool bSpaceBreaks=true, bool bSafeOnly=false)
Private Member Functions
bool checkCtcpFlood (KviCtcpMessage *msg)
void echoCtcpReply (KviCtcpMessage *msg)
void echoCtcpRequest (KviCtcpMessage *msg)
void otherChannelError (KviIrcMessage *msg)
void parseChannelHelp (KviIrcMessage *msg)
void parseChannelMode (const QString &szNick, const QString &szUser, const QString &szHost, KviChannelWindow *chan, KviCString &modefl, KviIrcMessage *msg, int curParam)
void parseCommandEndOfHelp (KviIrcMessage *msg)
void parseCommandHelp (KviIrcMessage *msg)
void parseCommandSyntaxHelp (KviIrcMessage *msg)
void parseCtcpReply (KviCtcpMessage *msg)
void parseCtcpReplyAvatar (KviCtcpMessage *msg)
void parseCtcpReplyGeneric (KviCtcpMessage *msg)
void parseCtcpReplyLagcheck (KviCtcpMessage *msg)
void parseCtcpReplyPing (KviCtcpMessage *msg)
void parseCtcpReplyUserinfo (KviCtcpMessage *msg)
void parseCtcpRequest (KviCtcpMessage *msg)
void parseCtcpRequestAction (KviCtcpMessage *msg)
void parseCtcpRequestAvatar (KviCtcpMessage *msg)
void parseCtcpRequestClientinfo (KviCtcpMessage *msg)
void parseCtcpRequestDcc (KviCtcpMessage *msg)
void parseCtcpRequestFinger (KviCtcpMessage *msg)
void parseCtcpRequestPage (KviCtcpMessage *msg)
void parseCtcpRequestPing (KviCtcpMessage *msg)
void parseCtcpRequestSource (KviCtcpMessage *msg)
void parseCtcpRequestTime (KviCtcpMessage *msg)
void parseCtcpRequestUserinfo (KviCtcpMessage *msg)
void parseCtcpRequestVersion (KviCtcpMessage *msg)
void parseLiteralAuthenticate (KviIrcMessage *msg)
void parseLiteralCap (KviIrcMessage *msg)
void parseLiteralError (KviIrcMessage *msg)
void parseLiteralInvite (KviIrcMessage *msg)
void parseLiteralJoin (KviIrcMessage *msg)
void parseLiteralKick (KviIrcMessage *msg)
void parseLiteralMode (KviIrcMessage *msg)
void parseLiteralNick (KviIrcMessage *msg)
void parseLiteralNotice (KviIrcMessage *msg)
void parseLiteralPart (KviIrcMessage *msg)
void parseLiteralPing (KviIrcMessage *msg)
void parseLiteralPong (KviIrcMessage *msg)
void parseLiteralPrivmsg (KviIrcMessage *msg)
void parseLiteralQuit (KviIrcMessage *msg)
void parseLiteralTopic (KviIrcMessage *msg)
void parseLiteralWallops (KviIrcMessage *msg)
void parseLoginNicknameProblem (KviIrcMessage *msg)
void parseNumeric001 (KviIrcMessage *msg)
void parseNumeric002 (KviIrcMessage *msg)
void parseNumeric003 (KviIrcMessage *msg)
void parseNumeric004 (KviIrcMessage *msg)
void parseNumeric005 (KviIrcMessage *msg)
void parseNumeric020 (KviIrcMessage *msg)
void parseNumeric367 (KviIrcMessage *msg)
void parseNumeric368 (KviIrcMessage *msg)
void parseNumericAList (KviIrcMessage *msg)
void parseNumericAway (KviIrcMessage *)
void parseNumericBackFromAway (KviIrcMessage *)
void parseNumericCannotSend (KviIrcMessage *msg)
void parseNumericCannotSendColor (KviIrcMessage *msg)
void parseNumericCantJoinChannel (KviIrcMessage *msg)
void parseNumericChannelModeIs (KviIrcMessage *msg)
void parseNumericChanUrl (KviIrcMessage *msg)
void parseNumericCodePageScheme (KviIrcMessage *msg)
void parseNumericCodePageSet (KviIrcMessage *msg)
void parseNumericCommandSyntax (KviIrcMessage *msg)
void parseNumericCreationTime (KviIrcMessage *msg)
void parseNumericEndOfAList (KviIrcMessage *msg)
void parseNumericEndOfExceptList (KviIrcMessage *msg)
void parseNumericEndOfInviteList (KviIrcMessage *msg)
void parseNumericEndOfLinks (KviIrcMessage *msg)
void parseNumericEndOfNames (KviIrcMessage *msg)
void parseNumericEndOfQList (KviIrcMessage *msg)
void parseNumericEndOfReopList (KviIrcMessage *msg)
void parseNumericEndOfSpamFilterList (KviIrcMessage *msg)
void parseNumericEndOfStats (KviIrcMessage *msg)
void parseNumericEndOfWho (KviIrcMessage *msg)
void parseNumericEndOfWhois (KviIrcMessage *msg)
void parseNumericEndOfWhowas (KviIrcMessage *msg)
void parseNumericExceptList (KviIrcMessage *msg)
void parseNumericInfo (KviIrcMessage *msg)
void parseNumericInfoEnd (KviIrcMessage *msg)
void parseNumericInfoStart (KviIrcMessage *msg)
void parseNumericInviteList (KviIrcMessage *msg)
void parseNumericInviting (KviIrcMessage *msg)
void parseNumericIsOn (KviIrcMessage *msg)
void parseNumericLinks (KviIrcMessage *msg)
void parseNumericList (KviIrcMessage *msg)
void parseNumericListEnd (KviIrcMessage *msg)
void parseNumericListStart (KviIrcMessage *msg)
void parseNumericMotd (KviIrcMessage *msg)
void parseNumericNames (KviIrcMessage *msg)
void parseNumericNicknameProblem (KviIrcMessage *msg)
void parseNumericNoSuchChannel (KviIrcMessage *msg)
void parseNumericNoSuchNick (KviIrcMessage *msg)
void parseNumericNoSuchServer (KviIrcMessage *msg)
void parseNumericNoTopic (KviIrcMessage *msg)
void parseNumericNotRegistered (KviIrcMessage *msg)
void parseNumericQList (KviIrcMessage *msg)
void parseNumericReopList (KviIrcMessage *msg)
void parseNumericSaslFail (KviIrcMessage *msg)
void parseNumericSaslLogin (KviIrcMessage *msg)
void parseNumericSaslSuccess (KviIrcMessage *msg)
void parseNumericServerAdminInfoAdminContact (KviIrcMessage *msg)
void parseNumericServerAdminInfoAdminName (KviIrcMessage *msg)
void parseNumericServerAdminInfoServerName (KviIrcMessage *msg)
void parseNumericServerAdminInfoTitle (KviIrcMessage *msg)
void parseNumericSpamFilterList (KviIrcMessage *msg)
void parseNumericStartTls (KviIrcMessage *msg)
void parseNumericStats (KviIrcMessage *msg)
void parseNumericTime (KviIrcMessage *msg)
void parseNumericTopic (KviIrcMessage *msg)
void parseNumericTopicWhoTime (KviIrcMessage *msg)
void parseNumericUnavailResource (KviIrcMessage *msg)
void parseNumericUserhost (KviIrcMessage *msg)
void parseNumericUserMode (KviIrcMessage *msg)
void parseNumericWatch (KviIrcMessage *msg)
void parseNumericWhoisActually (KviIrcMessage *msg)
void parseNumericWhoisAuth (KviIrcMessage *msg)
void parseNumericWhoisAway (KviIrcMessage *)
void parseNumericWhoisChannels (KviIrcMessage *msg)
void parseNumericWhoisIdle (KviIrcMessage *msg)
void parseNumericWhoisOther (KviIrcMessage *msg)
void parseNumericWhoisServer (KviIrcMessage *msg)
void parseNumericWhoisUser (KviIrcMessage *msg)
void parseNumericWhoReply (KviIrcMessage *msg)
void parseNumericWhowasUser (KviIrcMessage *msg)
void parseUserMode (KviIrcMessage *msg, const char *modeflptr)
void replyCtcp (KviCtcpMessage *msg, const QString &data)
Private Attributes
KviCString m_szLastParserError
Static Private Attributes
static KviCtcpMessageParseStruct m_ctcpReplyParseProcTable []
static KviCtcpMessageParseStruct m_ctcpRequestParseProcTable []
static KviLiteralMessageParseStruct m_literalParseProcTable []
static messageParseProc m_numericParseProcTable [1000]
Constructor & Destructor Documentation
KviIrcServerParser::KviIrcServerParser ()
KviIrcServerParser::~KviIrcServerParser ()
Member Function Documentation
bool KviIrcServerParser::checkCtcpFlood (KviCtcpMessage * msg) [private]
References KviIrcConnection::antiCtcpFloodData(), _KviCtcpMessage::bIsFlood, KviIrcMessage::connection(), KviIrcConnectionAntiCtcpFloodData::ctcpCount(), d, KviIrcConnectionAntiCtcpFloodData::increaseCtcpCount(), KVI_OPTION_BOOL, KVI_OPTION_UINT, kvi_time_t, kvi_unixTime, KviOption_boolUseCtcpFloodProtection, KviOption_uintCtcpFloodCheckInterval, KviOption_uintMaxCtcpRequests, KviIrcConnectionAntiCtcpFloodData::lastCtcpTime(), _KviCtcpMessage::msg, KviIrcConnectionAntiCtcpFloodData::setCtcpCount(), and KviIrcConnectionAntiCtcpFloodData::setLastCtcpTime().
Referenced by parseCtcpReplyAvatar(), parseCtcpRequestAvatar(), parseCtcpRequestClientinfo(), parseCtcpRequestDcc(), parseCtcpRequestFinger(), parseCtcpRequestPage(), parseCtcpRequestPing(), parseCtcpRequestSource(), parseCtcpRequestTime(), parseCtcpRequestUserinfo(), and parseCtcpRequestVersion().
const char * KviIrcServerParser::decodeCtcpEscape (const char * msg_ptr, KviCString & buffer) [static]
References KviCString::append(), and c.
Referenced by extractCtcpParameter().
const char * KviIrcServerParser::decodeCtcpEscape (const char * msg_ptr, QByteArray & buffer) [static]
References c.
void KviIrcServerParser::echoCtcpReply (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_CTCPREPLY, KVI_OUT_CTCPREPLYUNKNOWN, KVI_OUT_SYSTEMWARNING, KviOption_boolCtcpRepliesToActiveWindow, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, and KviIrcMask::user().
Referenced by parseCtcpReply(), parseCtcpReplyGeneric(), and parseCtcpReplyUserinfo().
void KviIrcServerParser::echoCtcpRequest (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), _KviCtcpMessage::bIgnored, _KviCtcpMessage::bIsFlood, _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_CTCPREQUESTFLOOD, KVI_OUT_CTCPREQUESTIGNORED, KVI_OUT_CTCPREQUESTREPLIED, KVI_OUT_CTCPREQUESTUNKNOWN, KVI_OUT_SYSTEMWARNING, KviEvent_OnCTCPFlood, KviOption_boolCtcpRequestsToActiveWindow, KVS_TRIGGER_EVENT_6_HALTED, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviControlCodes::Reset, _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, and KviIrcMask::user().
Referenced by parseCtcpRequest(), parseCtcpRequestAvatar(), parseCtcpRequestClientinfo(), parseCtcpRequestDcc(), parseCtcpRequestFinger(), parseCtcpRequestPage(), parseCtcpRequestPing(), parseCtcpRequestSource(), parseCtcpRequestTime(), parseCtcpRequestUserinfo(), and parseCtcpRequestVersion().
void KviIrcServerParser::encodeCtcpParameter (const char * param, KviCString & buffer, bool bSpaceBreaks = true) [static]
References KviCString::append().
Referenced by avatar_kvs_cmd_notify(), DccFileTransfer::connectionInProgress(), DccFileTransfer::doResume(), DccBroker::handleResumeRequest(), parseCtcpReplyAvatar(), parseCtcpRequestAvatar(), and DccFileTransfer::startConnection().
void KviIrcServerParser::encodeCtcpParameter (const char * param, QString & buffer, bool bSpaceBreaks = true) [static]
const char * KviIrcServerParser::extractCtcpParameter (const char * msg_ptr, KviCString & buffer, bool bSpaceBreaks = true, bool bSafeOnly = false) [static]
References KviCString::append(), and decodeCtcpEscape().
Referenced by parseCtcpReply(), parseCtcpReplyAvatar(), parseCtcpReplyLagcheck(), parseCtcpReplyPing(), parseCtcpRequest(), parseCtcpRequestClientinfo(), and parseCtcpRequestDcc().
const char * KviIrcServerParser::extractCtcpParameter (const char * msg_ptr, QString & buffer, bool bSpaceBreaks = true, bool bSafeOnly = false) [static]
References decodeCtcpEscape().
void KviIrcServerParser::otherChannelError (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseChannelHelp (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseChannelMode (const QString & szNick, const QString & szUser, const QString & szHost, KviChannelWindow * chan, KviCString & modefl, KviIrcMessage * msg, int curParam) [private]
References __tr2qs, CHANNEL_MODE, CHANUSER_MODE, KviIrcMessage::connection(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviIrcConnectionUserInfo::hostName(), IS_ME, KviIrcConnectionServerInfo::isSupportedModeFlag(), KVI_OPTION_BOOL, KVI_OUT_BAN, KVI_OUT_BANEXCEPT, KVI_OUT_BANUNEXCEPT, KVI_OUT_CHANADMIN, KVI_OUT_CHANMODE, KVI_OUT_CHANOWNER, KVI_OUT_DECHANADMIN, KVI_OUT_DECHANOWNER, KVI_OUT_DEOP, KVI_OUT_DEVOICE, KVI_OUT_HALFDEOP, KVI_OUT_HALFOP, KVI_OUT_INVITEEXCEPT, KVI_OUT_INVITEUNEXCEPT, KVI_OUT_KEY, KVI_OUT_LIMIT, KVI_OUT_MEBAN, KVI_OUT_MEBANEXCEPT, KVI_OUT_MEBANUNEXCEPT, KVI_OUT_MECHANADMIN, KVI_OUT_MECHANOWNER, KVI_OUT_MEDECHANADMIN, KVI_OUT_MEDECHANOWNER, KVI_OUT_MEDEHALFOP, KVI_OUT_MEDEOP, KVI_OUT_MEDEUSEROP, KVI_OUT_MEDEVOICE, KVI_OUT_MEHALFOP, KVI_OUT_MEINVITEEXCEPT, KVI_OUT_MEINVITEUNEXCEPT, KVI_OUT_MEOP, KVI_OUT_MEUNBAN, KVI_OUT_MEUSEROP, KVI_OUT_MEVOICE, KVI_OUT_OP, KVI_OUT_UNBAN, KVI_OUT_USERDEOP, KVI_OUT_USEROP, KVI_OUT_VOICE, kvi_strEqualCS(), KviEvent_OnBan, KviEvent_OnBanException, KviEvent_OnBanExceptionRemove, KviEvent_OnChanAdmin, KviEvent_OnChannelModeChange, KviEvent_OnChanOwner, KviEvent_OnDeChanAdmin, KviEvent_OnDeChanOwner, KviEvent_OnDeHalfOp, KviEvent_OnDeOp, KviEvent_OnDeUserOp, KviEvent_OnDeVoice, KviEvent_OnHalfOp, KviEvent_OnInviteException, KviEvent_OnInviteExceptionRemove, KviEvent_OnKeySet, KviEvent_OnKeyUnset, KviEvent_OnLimitSet, KviEvent_OnLimitUnset, KviEvent_OnMeBan, KviEvent_OnMeBanException, KviEvent_OnMeBanExceptionRemove, KviEvent_OnMeChanAdmin, KviEvent_OnMeChanOwner, KviEvent_OnMeDeChanAdmin, KviEvent_OnMeDeChanOwner, KviEvent_OnMeDeHalfOp, KviEvent_OnMeDeOp, KviEvent_OnMeDeUserOp, KviEvent_OnMeDeVoice, KviEvent_OnMeHalfOp, KviEvent_OnMeInviteException, KviEvent_OnMeInviteExceptionRemove, KviEvent_OnMeOp, KviEvent_OnMeUnban, KviEvent_OnMeUserOp, KviEvent_OnMeVoice, KviEvent_OnOp, KviEvent_OnUnban, KviEvent_OnUserOp, KviEvent_OnVoice, KviOption_boolShowCompactModeChanges, KVS_TRIGGER_EVENT_3_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviIrcMask::matchesFixed(), KviIrcConnectionUserInfo::nickName(), KviWindow::output(), KviCString::ptr(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviIrcConnection::serverInfo(), KviChannelWindow::setChanAdmin(), KviChannelWindow::setChannelMode(), KviChannelWindow::setChannelModeWithParam(), KviChannelWindow::setChanOwner(), KviIrcMessage::setHaltOutput(), KviChannelWindow::setModeInList(), KviIrcConnectionServerInfo::supportedListModes(), KviIrcConnectionServerInfo::supportedParameterModes(), KviIrcConnectionServerInfo::supportedParameterWhenSetModes(), szHost, KviWindow::updateCaption(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
Referenced by parseLiteralMode(), and parseNumericChannelModeIs().
void KviIrcServerParser::parseCommandEndOfHelp (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::output(), and KviIrcMessage::safeParam().
void KviIrcServerParser::parseCommandHelp (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::outputNoFmt(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseCommandSyntaxHelp (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_HELP, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseCtcpReply (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), echoCtcpReply(), KviQString::equalCS(), extractCtcpParameter(), KviIrcMask::host(), i, KVI_CTCP_MESSAGE_PARSE_TRIGGERNOEVENT, KviEvent_OnCTCPReply, KVS_TRIGGER_EVENT_6_HALTED, m_ctcpReplyParseProcTable, _KviCtcpMessage::msg, _KviCtcpMessageParseStruct::msgName, KviIrcMask::nick(), _KviCtcpMessage::pData, _KviCtcpMessageParseStruct::proc, _KviCtcpMessage::pSource, _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, KviQString::upperISO88591(), and KviIrcMask::user().
Referenced by parseLiteralNotice().
void KviIrcServerParser::parseCtcpReplyAvatar (KviCtcpMessage * msg) [private]
References __tr2qs, _OUTPUT_VERBOSE, KviQString::appendFormatted(), KviConsoleWindow::avatarChanged(), KviApplication::Avatars, checkCtcpFlood(), KviIrcMessage::connection(), KviIrcMessage::console(), KviQString::cutToLast(), KviWindow::decodeText(), e, encodeCtcpParameter(), KviIrcConnection::encodeText(), KviQString::equalCIN(), KviQString::escapeKvs(), KviQString::EscapeSpace, extractCtcpParameter(), KviIrcUserEntry::Female, KviIrcUserDataBase::find(), g_pApp, g_pIconManager, KviIconManager::getAvatar(), KviApplication::getLocalKvircDirectory(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_AVATAR, KviOption_boolRequestMissingAvatars, KviOption_uintMaximumRequestedAvatarSize, KviIrcUserEntry::Male, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::outputNoFmt(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviKvsScript::run(), KviIrcConnection::sendFmtData(), KviIrcUserEntry::setAvatar(), KviApplication::setAvatarOnFileReceived(), KviIrcUserEntry::setGender(), _KviCtcpMessage::szTarget, KviIrcUserEntry::Unknown, KviIconManager::urlToCachedFileName(), KviIrcMask::user(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseCtcpReplyGeneric (KviCtcpMessage * msg) [private]
References echoCtcpReply().
void KviIrcServerParser::parseCtcpReplyLagcheck (KviCtcpMessage * msg) [private]
References KviWindow::connection(), KviIrcMessage::console(), extractCtcpParameter(), KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), _KviCtcpMessage::msg, _KviCtcpMessage::pData, and KviCString::ptr().
void KviIrcServerParser::parseCtcpReplyPing (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), _KviCtcpMessage::bUnknown, KviIrcMessage::connection(), KviIrcMessage::console(), KviCString::contains(), KviCString::cutFromFirst(), KviCString::cutToFirst(), extractCtcpParameter(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviIrcMask::host(), IS_ME, kvi_gettimeofday(), KVI_OPTION_BOOL, KVI_OUT_CTCPREPLY, KVI_OUT_CTCPREPLYUNKNOWN, KVI_OUT_SYSTEMWARNING, KviOption_boolCtcpRepliesToActiveWindow, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, _KviCtcpMessage::szTarget, KviCString::toUInt(), and KviIrcMask::user().
void KviIrcServerParser::parseCtcpReplyUserinfo (KviCtcpMessage * msg) [private]
References c, KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), e, echoCtcpReply(), KviQString::equalCS(), KviIrcUserEntry::Female, KviIrcUserDataBase::find(), g_pActiveWindow, KviIrcUserEntry::Male, _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviIrcUserEntry::setGender(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseCtcpRequest (KviCtcpMessage * msg) [private]
References __tr2qs, _KviCtcpMessage::bUnknown, KviRegisteredUser::Channel, KviIrcMessage::connection(), KviIrcMessage::console(), KviRegisteredUser::Ctcp, KviIrcConnection::decodeText(), echoCtcpRequest(), KviQString::equalCS(), extractCtcpParameter(), KviIrcMask::host(), i, IS_ME, KviRegisteredUser::isIgnoreEnabledFor(), KVI_CTCP_MESSAGE_PARSE_TRIGGERNOEVENT, KVI_OPTION_BOOL, KVI_OUT_IGNORE, KviEvent_OnCTCPRequest, KviOption_boolIgnoreCtcpDcc, KviOption_boolVerboseIgnore, KVS_TRIGGER_EVENT_6_HALTED, m_ctcpReplyParseProcTable, m_ctcpRequestParseProcTable, _KviCtcpMessage::msg, _KviCtcpMessageParseStruct::msgName, KviIrcMask::nick(), KviWindow::output(), _KviCtcpMessage::pData, _KviCtcpMessageParseStruct::proc, _KviCtcpMessage::pSource, KviRegisteredUser::Query, KviIrcUserDataBase::registeredUser(), _KviCtcpMessage::szTag, _KviCtcpMessage::szTarget, u, KviQString::upperISO88591(), KviIrcMask::user(), and KviIrcConnection::userDataBase().
Referenced by parseLiteralPrivmsg().
void KviIrcServerParser::parseCtcpRequestAction (KviCtcpMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviConsoleWindow::applyHighlighting(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createQuery(), KviIrcConnection::decodeText(), KviWindow::decodeText(), KviWindow::demandAttention(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pApp, KviWindow::hasAttention(), KviIrcMask::host(), IS_ME, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_UINT, KVI_OUT_ACTION, KVI_OUT_HIGHLIGHT, KVI_OUT_SYSTEMWARNING, KviEvent_OnAction, KviEvent_OnQueryWindowRequest, KviOption_boolCreateQueryOnPrivmsg, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolFlashWindowOnHighlightedMessages, KviOption_boolPopupNotifierOnHighlightedMessages, KviOption_boolStripMircColorsInUserMessages, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviWindow::MainWindowIsVisible, _KviCtcpMessage::msg, KviIrcMask::nick(), KviApplication::notifierMessage(), KviWindow::output(), KviWindow::outputNoFmt(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviCString::ptr(), KviIrcMessage::setHaltOutput(), KviQueryWindow::setTarget(), KviControlCodes::stripControlBytes(), _KviCtcpMessage::szTarget, KviOsInfo::type(), and KviIrcMask::user().
void KviIrcServerParser::parseCtcpRequestAvatar (KviCtcpMessage * msg) [private]
References __tr2qs, _OUTPUT_VERBOSE, a, KviSharedFilesManager::addSharedFile(), _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::console(), KviConsoleWindow::currentAvatar(), echoCtcpRequest(), encodeCtcpParameter(), g_pSharedFilesManager, IS_ME, KviAvatar::isRemote(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KviOption_boolDCCFileTransferReplaceOutgoingSpacesWithUnderscores, KviOption_boolIgnoreChannelAvatarRequestsWhenNoAvatarSet, KviOption_boolIgnoreCtcpAvatar, KviOption_stringCtcpUserInfoGender, KviOption_uintAvatarOfferTimeoutInSecs, KviAvatar::localPath(), KviIrcMask::mask(), _KviCtcpMessage::msg, KviAvatar::name(), KviWindow::output(), _KviCtcpMessage::pSource, replyCtcp(), and _KviCtcpMessage::szTarget.
void KviIrcServerParser::parseCtcpRequestClientinfo (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), ctcpTagTable, echoCtcpRequest(), extractCtcpParameter(), KviCString::Format, i, KviCString::isEmpty(), KVI_OPTION_BOOL, KVI_RELEASE_NAME, KVI_SOURCES_DATE, kvi_strEqualCS(), KVI_VERSION, KviOption_boolIgnoreCtcpClientinfo, _KviCtcpMessage::pData, KviCString::ptr(), replyCtcp(), _KviCtcpMessage::szTag, KviCString::toUpperISO88591(), and KviCString::trim().
void KviIrcServerParser::parseCtcpRequestDcc (KviCtcpMessage * msg) [private]
References __tr2qs, _KviDccRequest::bIPv6, checkCtcpFlood(), KviIrcMessage::connection(), KviIrcMessage::console(), _KviDccRequest::ctcpMsg, KviRegisteredUser::Dcc, KviWindow::decodeText(), echoCtcpRequest(), extractCtcpParameter(), KviApplication::findPendingAvatarChange(), g_pApp, g_pModuleManager, KviModuleManager::getModule(), KviModule::getSymbol(), KviIrcMessage::haltOutput(), KviIrcMask::host(), KviRegisteredUser::isIgnoreEnabledFor(), KviConsoleWindow::isIPv6Connection(), KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KVI_OUT_DCCREQUEST, kvi_strEqualCI(), KviOption_boolVerboseIgnore, KviModuleManager::lastError(), m, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), KviWindow::outputNoFmt(), p, _KviDccRequest::pConsole, _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviCString::ptr(), KviIrcUserDataBase::registeredUser(), _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, _KviDccRequest::szParam5, _KviCtcpMessage::szTag, _KviDccRequest::szType, u, KviIrcMask::user(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseCtcpRequestFinger (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::connection(), echoCtcpRequest(), KviCString::Format, KviCString::isEmpty(), KVI_OPTION_BOOL, KviOption_boolIgnoreCtcpFinger, _KviCtcpMessage::msg, KviCString::ptr(), replyCtcp(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
void KviIrcServerParser::parseCtcpRequestPage (KviCtcpMessage * msg) [private]
References KviCtcpPageDialog::addPage(), _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::connection(), KviIrcConnection::decodeText(), echoCtcpRequest(), g_pCtcpPageDialog, KviIrcMask::host(), IS_ME, KVI_DEFAULT_CTCP_PAGE_REPLY, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolIgnoreCtcpPage, KviOption_boolShowDialogOnChannelCtcpPage, KviOption_boolShowDialogOnCtcpPage, KviOption_stringCtcpPageReply, _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pData, KviCtcpPageDialog::popup(), _KviCtcpMessage::pSource, KviCString::ptr(), replyCtcp(), _KviCtcpMessage::szTarget, and KviIrcMask::user().
void KviIrcServerParser::parseCtcpRequestPing (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), KviIrcMessage::connection(), echoCtcpRequest(), KviIrcConnection::encodeText(), KVI_OPTION_BOOL, KviOption_boolIgnoreCtcpPing, _KviCtcpMessage::msg, _KviCtcpMessage::pData, and replyCtcp().
void KviIrcServerParser::parseCtcpRequestSource (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), echoCtcpRequest(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_RELEASE_NAME, KVI_VERSION, KviOption_boolIgnoreCtcpSource, KviOption_stringCtcpSourcePostfix, replyCtcp(), and KviOsInfo::version().
void KviIrcServerParser::parseCtcpRequestTime (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), echoCtcpRequest(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolIgnoreCtcpTime, KviOption_uintOutputDatetimeFormat, and replyCtcp().
void KviIrcServerParser::parseCtcpRequestUserinfo (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, checkCtcpFlood(), echoCtcpRequest(), KVI_DEFAULT_CTCP_USERINFO_REPLY, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolIgnoreCtcpUserinfo, KviOption_stringCtcpUserInfoAge, KviOption_stringCtcpUserInfoGender, KviOption_stringCtcpUserInfoLanguages, KviOption_stringCtcpUserInfoLocation, KviOption_stringCtcpUserInfoOther, and replyCtcp().
void KviIrcServerParser::parseCtcpRequestVersion (KviCtcpMessage * msg) [private]
References _KviCtcpMessage::bIgnored, KviBuildInfo::buildDate(), KviBuildInfo::buildRevision(), checkCtcpFlood(), echoCtcpRequest(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_RELEASE_NAME, KVI_SOURCES_DATE, KVI_VERSION, KviOption_boolIgnoreCtcpVersion, KviOption_stringCtcpVersionPostfix, KviOsInfo::name(), KviOsInfo::release(), replyCtcp(), and KviOsInfo::version().
void KviIrcServerParser::parseLiteralAuthenticate (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcConnection::handleAuthenticate(), and KviIrcMessage::safeParam().
void KviIrcServerParser::parseLiteralCap (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcConnectionServerInfo::addSupportedCaps(), KviIrcConnectionStateData::changeEnabledCapList(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviIrcConnection::handleInitialCapAck(), KviIrcConnection::handleInitialCapLs(), KviIrcConnection::handleInitialCapNak(), KviIrcConnectionStateData::isInsideInitialCapLs(), KviIrcConnectionStateData::isInsideInitialCapReq(), KVI_OUT_CAP, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), and KviIrcConnection::stateData().
void KviIrcServerParser::parseLiteralError (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERERROR, KviEvent_OnError, KVS_TRIGGER_EVENT_2_HALTED, KviWindow::output(), KviIrcMessage::safePrefix(), and KviIrcMessage::setHaltOutput().
void KviIrcServerParser::parseLiteralInvite (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviRegisteredUser::Invite, IS_ME, KviRegisteredUser::isIgnoreEnabledFor(), KVI_OPTION_BOOL, KVI_OUT_IGNORE, KVI_OUT_INVITE, KviEvent_OnInvite, KviOption_boolAutoJoinOnInvite, KviOption_boolInvitesToActiveWindow, KviOption_boolVerboseIgnore, KVS_TRIGGER_EVENT_4_HALTED, KviWindow::output(), KviIrcUserDataBase::registeredUser(), KviIrcMessage::safeParam(), KviIrcConnection::sendFmtData(), KviIrcMessage::setHaltOutput(), szHost, u, UNRECOGNIZED_MESSAGE, and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseLiteralJoin (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviIrcUserEntry::avatar(), KviConsoleWindow::avatarChanged(), KviConsoleWindow::checkDefaultAvatar(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createChannel(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviConsoleWindow::defaultAvatarFromOptions(), KviIrcConnectionRequestQueue::enqueueChannel(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), KviIrcConnection::getCommonChannels(), KviUserListEntry::globalData(), KviIrcMessage::haltOutput(), IS_ME, KviChannelWindow::join(), KVI_OPTION_BOOL, KVI_OUT_JOIN, KVI_OUT_QUERYTRACE, KviEvent_OnJoin, KviEvent_OnMeJoin, KviOption_boolEnableQueryTracing, KVS_TRIGGER_EVENT_0_HALTED, KVS_TRIGGER_EVENT_3_HALTED, KviIrcConnectionServerInfo::modeFlagFromModeChar(), KviQueryWindow::notifyCommonChannels(), KviWindow::output(), q, KviIrcConnection::requestQueue(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcUserEntry::setAvatar(), KviIrcMessage::setHaltOutput(), szHost, UNRECOGNIZED_MESSAGE, KviWindow::updateCaption(), KviQueryWindow::updateLabelText(), and KviIrcConnection::userInfoReceived().
void KviIrcServerParser::parseLiteralKick (KviIrcMessage * msg) [private]
References __tr, __tr2qs, _OUTPUT_VERBOSE, KviChannelWindow::channelModeParam(), KviMainWindow::closeWindow(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), e, KviIrcConnection::encodeText(), KviIrcUserDataBase::find(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pMainWindow, KviIrcConnection::getCommonChannels(), KviIrcMessage::haltOutput(), KviChannelWindow::hasChannelMode(), KviIrcUserEntry::host(), IS_ME, KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_KICK, KVI_OUT_MEKICK, KVI_OUT_QUERYTRACE, KVI_OUT_SYSTEMMESSAGE, KVI_USERACTION_KICK, KviEvent_OnKick, KviEvent_OnMeKick, KviOption_boolEnableQueryTracing, KviOption_boolKeepChannelOpenOnKick, KviOption_boolRejoinChannelOnKick, KviOption_stringOnMeKickedSound, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviQueryWindow::notifyCommonChannels(), KviWindow::output(), KviChannelWindow::part(), q, KviIrcUrl::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviChannelWindow::setDeadChan(), KviIrcMessage::setHaltOutput(), szHost, UNRECOGNIZED_MESSAGE, KviIrcUserEntry::user(), KviChannelWindow::userAction(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseLiteralMode (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), IS_ME, KVI_OUT_MODE, KVI_USERACTION_CHANMODE, KviWindow::output(), parseChannelMode(), parseUserMode(), KviIrcMessage::safeParam(), szHost, UNRECOGNIZED_MESSAGE, and KviChannelWindow::userAction().
void KviIrcServerParser::parseLiteralNick (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, c, KviIrcConnection::channelList(), KviMainWindow::closeWindow(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviWindow::delayedAutoRaise(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), KviPointerList< T >::first(), g_pActiveWindow, g_pMainWindow, KviIrcConnection::getCommonChannels(), KviIrcMessage::haltOutput(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_NICK, KVI_OUT_QUERYTRACE, KVI_OUT_SYSTEMWARNING, KVI_USERACTION_NICK, KviEvent_OnMeNickChange, KviEvent_OnNickChange, KviOption_boolEnableQueryTracing, KVS_TRIGGER_EVENT_2_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KviQueryWindow::mergeQuery(), KviPointerList< T >::next(), KviQueryWindow::nickChange(), KviIrcConnection::nickChange(), KviQueryWindow::notifyCommonChannels(), KviWindow::output(), q, KviIrcConnection::queryList(), KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), KviIrcUserEntry::setSmartNickColor(), szHost, KviQueryWindow::userAction(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseLiteralNotice (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), _KviCtcpMessage::bIgnored, _KviCtcpMessage::bIsFlood, _KviCtcpMessage::bUnknown, c, Channel, KviWindow::Channel, KviWindow::connection(), KviIrcMessage::connection(), KviWindow::Console, KviIrcMessage::console(), KviIrcConnection::createQuery(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), KviCString::cutLeft(), KviCString::cutRight(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), DECRYPT_IF_NEEDED, KviWindow::demandAttention(), KviQString::equalCI(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pApp, KviIrcMessage::haltOutput(), KviWindow::hasAttention(), KviNickServRule::identifyCommand(), IS_ME, KviNickServRuleSet::isEmpty(), KviNickServRuleSet::isEnabled(), KviRegisteredUser::isIgnoreEnabledFor(), KviIrcConnectionServerInfo::isSupportedModePrefix(), kvi_mayBeSpam(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_BROADCASTNOTICE, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_CHANSERV, KVI_OUT_IGNORE, KVI_OUT_MEMOSERV, KVI_OUT_NICKSERV, KVI_OUT_QUERYNOTICE, KVI_OUT_QUERYNOTICECRYPTED, KVI_OUT_SERVERNOTICE, KVI_OUT_SPAM, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KVI_USERACTION_NOTICE, KviEvent_OnBroadcastNotice, KviEvent_OnChannelNotice, KviEvent_OnChanServNotice, KviEvent_OnMemoServNotice, KviEvent_OnNickServNotice, KviEvent_OnQueryNotice, KviEvent_OnQueryWindowRequest, KviEvent_OnServerNotice, KviOption_boolCreateQueryOnNotice, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolFlashQueryWindowOnNewMessages, KviOption_boolPasteLastLogOnQueryJoin, KviOption_boolPopupNotifierOnNewQueryMessages, KviOption_boolServerNoticesToActiveWindow, KviOption_boolServicesNoticesToActiveWindow, KviOption_boolSilentAntiSpam, KviOption_boolUseAntiSpamOnNotice, KviOption_boolVerboseIgnore, KviOption_stringOnNewQueryOpenedSound, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_2_HALTED, KVS_TRIGGER_EVENT_3_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviCString::lastCharIs(), KviCString::len(), KviWindow::MainWindowIsVisible, KviNickServRuleSet::matchRule(), _KviCtcpMessage::msg, KviIrcConnectionTarget::network(), KviIrcNetwork::nickServRuleSet(), KviConsoleWindow::NoNotifier, KviRegisteredUser::Notice, KviApplication::notifierMessage(), KviConsoleWindow::NoWindowFlashing, KviWindow::output(), KviWindow::outputNoFmt(), KviConsoleWindow::outputPrivmsg(), parseCtcpReply(), KviQueryWindow::pasteLastLog(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviCString::ptr(), KviWindow::Query, KviIconManager::QueryNotice, r, KviIrcUserDataBase::registeredUser(), KviIrcUrl::run(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcMessage::setHaltOutput(), KviQueryWindow::setTarget(), szBuffer, szHost, _KviCtcpMessage::szTarget, KviIrcConnection::target(), KviIrcMessage::trailingString(), KviWindow::type(), u, KviChannelWindow::userAction(), KviQueryWindow::userAction(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseLiteralPart (KviIrcMessage * msg) [private]
References __tr, __tr2qs, KviChannelWindow::closeOnPart(), KviMainWindow::closeWindow(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pMainWindow, KviIrcConnection::getCommonChannels(), KviIrcMessage::haltOutput(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_PART, KVI_OUT_QUERYTRACE, KviEvent_OnMePart, KviEvent_OnPart, KviOption_boolEnableQueryTracing, KviOption_boolKeepChannelOpenOnPart, KviOption_boolShowOwnParts, KVS_TRIGGER_EVENT_1_HALTED, KVS_TRIGGER_EVENT_4_HALTED, KviQueryWindow::notifyCommonChannels(), KviWindow::output(), KviIrcMessage::paramCount(), KviChannelWindow::part(), q, KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviChannelWindow::setDeadChan(), KviIrcMessage::setHaltOutput(), szHost, and UNRECOGNIZED_MESSAGE.
void KviIrcServerParser::parseLiteralPing (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_SERVERPING, KviEvent_OnPing, KviOption_boolShowPingPong, KVS_TRIGGER_EVENT_2_HALTED, KviWindow::output(), KviIrcMessage::safePrefix(), KviIrcConnection::sendFmtData(), and KviIrcMessage::setHaltOutput().
void KviIrcServerParser::parseLiteralPong (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_SERVERPING, KviEvent_OnPong, KviOption_boolShowPingPong, KVS_TRIGGER_EVENT_2_HALTED, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), KviWindow::output(), KviIrcMessage::safePrefix(), and KviIrcMessage::setHaltOutput().
void KviIrcServerParser::parseLiteralPrivmsg (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), _KviCtcpMessage::bIgnored, _KviCtcpMessage::bIsFlood, _KviCtcpMessage::bUnknown, c, KviRegisteredUser::Channel, Channel, KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::createQuery(), KviCString::cutLeft(), KviCString::cutRight(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), DECRYPT_IF_NEEDED, KviWindow::demandAttention(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), g_pApp, KviIrcMessage::haltOutput(), KviWindow::hasAttention(), KviIrcConnectionStateData::identifyMsgCapabilityEnabled(), IdentifyMsgCapNotUsed, IdentifyMsgCapUsedIdentified, IdentifyMsgCapUsedNotIdentified, IS_ME, KviRegisteredUser::isIgnoreEnabledFor(), KviIrcConnectionServerInfo::isSupportedModePrefix(), kvi_mayBeSpam(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_BROADCASTPRIVMSG, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_IGNORE, KVI_OUT_QUERYPRIVMSG, KVI_OUT_QUERYPRIVMSGCRYPTED, KVI_OUT_SPAM, KVI_USERACTION_PRIVMSG, KviEvent_OnChannelMessage, KviEvent_OnIgnoredMessage, KviEvent_OnQueryMessage, KviEvent_OnQueryWindowRequest, KviOption_boolCreateQueryOnPrivmsg, KviOption_boolExternalMessagesToActiveWindow, KviOption_boolFlashQueryWindowOnNewMessages, KviOption_boolOperatorMessagesToActiveWindow, KviOption_boolPasteLastLogOnQueryJoin, KviOption_boolPopupNotifierOnNewQueryMessages, KviOption_boolSilentAntiSpam, KviOption_boolUseAntiSpamOnPrivmsg, KviOption_boolVerboseIgnore, KviOption_stringOnNewQueryOpenedSound, KviOption_stringOnQueryMessageSound, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_4_HALTED, KVS_TRIGGER_EVENT_5_HALTED, KviCString::lastCharIs(), KviCString::len(), KviWindow::MainWindowIsVisible, _KviCtcpMessage::msg, KviConsoleWindow::NoNotifier, KviApplication::notifierMessage(), KviConsoleWindow::NoWindowFlashing, KviWindow::output(), KviConsoleWindow::outputPrivmsg(), parseCtcpRequest(), KviQueryWindow::pasteLastLog(), _KviCtcpMessage::pData, _KviCtcpMessage::pSource, KviCString::ptr(), KviRegisteredUser::Query, KviIconManager::QueryPrivMsg, KviIrcUserDataBase::registeredUser(), KviIrcUrl::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcMessage::setHaltOutput(), KviQueryWindow::setTarget(), KviIrcConnection::stateData(), szBuffer, szHost, _KviCtcpMessage::szTarget, KviIrcMessage::trailingString(), KviWindow::type(), u, KviChannelWindow::userAction(), KviQueryWindow::userAction(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseLiteralQuit (KviIrcMessage * msg) [private]
References __tr2qs, KviKvsVariantList::append(), c, KviIrcConnection::channelList(), KviIrcMessage::connection(), KviWindow::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviQString::equalCI(), KviIrcConnection::findQuery(), KviPointerList< T >::first(), KviIrcMessage::haltOutput(), KviKvsEventManager::instance(), KVI_OUT_QUIT, KVI_OUT_SPLIT, kvi_unixTime, KviEvent_OnNetsplit, KviEvent_OnQuit, KVS_TRIGGER_EVENT_2_HALTED, KviIrcConnectionNetsplitDetectorData::lastNetsplitOnQuitReason(), KviIrcConnectionNetsplitDetectorData::lastNetsplitOnQuitTime(), KviIrcConnection::netsplitDetectorData(), KviPointerList< T >::next(), KviWindow::output(), p, KviCString::ptr(), q, KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitReason(), KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitTime(), and szHost.
void KviIrcServerParser::parseLiteralTopic (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::decodeAndSplitPrefix(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_UINT, KVI_OUT_TOPIC, KVI_USERACTION_TOPIC, KviEvent_OnTopic, KviOption_uintOutputDatetimeFormat, KVS_TRIGGER_EVENT_4_HALTED, KviWindow::output(), KviControlCodes::Reset, KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), KviTopicWidget::setTopic(), KviTopicWidget::setTopicSetAt(), KviTopicWidget::setTopicSetBy(), szHost, KviChannelWindow::topicWidget(), UNRECOGNIZED_MESSAGE, and KviChannelWindow::userAction().
void KviIrcServerParser::parseLiteralWallops (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::decodeAndSplitPrefix(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WALLOPS, KviEvent_OnWallops, KviOption_boolOperatorMessagesToActiveWindow, KVS_TRIGGER_EVENT_4_HALTED, KviWindow::output(), KviIrcMessage::safeTrailing(), KviIrcMessage::setHaltOutput(), and szHost.
void KviIrcServerParser::parseLoginNicknameProblem (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_VERBOSE, KviIrcMessage::connection(), KviIrcMessage::console(), d, KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KVI_OUT_NICKNAMEPROBLEM, KviUserListView::nickChange(), KviIrcConnectionUserInfo::nickName(), KviConsoleWindow::notifyListView(), KviIrcMessage::numeric(), KviWindow::output(), KviWindow::outputNoFmt(), KviIrcConnection::pickNextLoginNickName(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviIrcConnectionUserInfo::setNickName(), and KviIrcConnection::userInfo().
Referenced by parseNumericNicknameProblem(), and parseNumericUnavailResource().
void KviIrcServerParser::parseMessage (const char * message, KviIrcConnection * pConnection)
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_PARANOIC, KviIrcMessage::allParams(), KviKvsVariantList::append(), KviIrcMessage::command(), KviIrcConnection::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcMessage::firstParam(), KviIrcMessage::haltOutput(), KviKvsEventManager::hasAppHandlers(), KviKvsEventManager::hasRawHandlers(), i, KviKvsEventManager::instance(), KviIrcMessage::isEmpty(), KviIrcMessage::isNumeric(), KVI_OUT_UNHANDLED, KVI_OUT_UNRECOGNIZED, kvi_strEqualCS(), kvi_time_t, kvi_unixTime, KviEvent_OnUnhandledLiteral, KviIrcConnectionStateData::lastReceivedWhoisReply(), m_literalParseProcTable, m_numericParseProcTable, m_szLastParserError, _KviLiteralMessageParseStruct::msgName, KviIrcMessage::nextParam(), KviIrcMessage::numeric(), KviWindow::output(), KviIrcMessage::paramCount(), parseNumericWhoisOther(), KviIrcMessage::prefix(), _KviLiteralMessageParseStruct::proc, KviCString::ptr(), KviIrcMessage::safePrefix(), KviIrcMessage::setHaltOutput(), KviIrcConnection::stateData(), KviKvsEventManager::trigger(), KviKvsEventManager::triggerRaw(), and KviIrcMessage::unrecognized().
Referenced by KviIrcConnection::incomingMessage(), and KviIrcConnection::incomingMessageNoFilter().
void KviIrcServerParser::parseNumeric001 (KviIrcMessage * msg) [private]
References KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviIrcConnection::loginComplete(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::safeTrailing(), KviIrcConnectionUserInfo::setNickName(), KviIrcConnectionUserInfo::setUnmaskedHostName(), KviIrcContext::state(), KviIrcConnection::userInfo(), and KviIrcConnection::userInfoReceived().
void KviIrcServerParser::parseNumeric002 (KviIrcMessage * msg) [private]
References KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviIrcConnection::loginComplete(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::safeTrailing(), and KviIrcContext::state().
void KviIrcServerParser::parseNumeric003 (KviIrcMessage * msg) [private]
References KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviIrcConnection::loginComplete(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::safeTrailing(), and KviIrcContext::state().
void KviIrcServerParser::parseNumeric004 (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, _OUTPUT_QUIET, KviCString::append(), KviIrcContext::Connected, KviIrcMessage::connection(), KviIrcMessage::console(), KviCString::contains(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcConnectionServerInfo::getChannelModeDescription(), KviIrcConnectionServerInfo::getUserModeDescription(), KviIrcMessage::haltOutput(), KviCString::hasData(), KVI_OPTION_BOOL, KVI_OUT_SERVERINFO, KVI_OUT_SYSTEMWARNING, KviOption_boolShowExtendedServerInfo, KviIrcConnection::loginComplete(), KviCString::occurences(), KviWindow::output(), KviWindow::outputNoFmt(), KviIrcMessage::param(), KviIrcMessage::paramCount(), KviCString::ptr(), KviIrcMessage::safeParam(), KviIrcConnection::serverInfo(), KviIrcConnection::serverInfoReceived(), KviIrcConnectionServerInfo::setServerVersion(), KviIrcContext::state(), and KviOsInfo::version().
void KviIrcServerParser::parseNumeric005 (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, KviIrcMessage::allParams(), KviIrcContext::Connected, KviWindow::connection(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::context(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviCString::hasData(), i, KVI_OPTION_BOOL, KVI_OUT_SERVERINFO, kvi_strEqualCI(), kvi_strEqualCIN(), KviOption_boolShowExtendedServerInfo, KviCString::len(), KviIrcConnection::loginComplete(), KviWindow::output(), KviWindow::outputNoFmt(), p, KviIrcMessage::param(), KviIrcMessage::paramCount(), KviCString::ptr(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviIrcConnection::serverInfo(), KviIrcConnectionServerInfo::setMaxModeChanges(), KviIrcConnectionServerInfo::setMaxTopicLen(), KviIrcConnectionServerInfo::setNetworkName(), KviIrcConnectionServerInfo::setSupportedChannelModes(), KviIrcConnectionServerInfo::setSupportedChannelTypes(), KviIrcConnectionServerInfo::setSupportedModePrefixes(), KviIrcConnectionServerInfo::setSupportsCodePages(), KviIrcConnectionServerInfo::setSupportsWatchList(), and KviIrcContext::state().
void KviIrcServerParser::parseNumeric020 (KviIrcMessage * msg) [private]
References KviControlCodes::Bold, KviIrcMessage::console(), KviWindow::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_CONNECTION, KviWindow::output(), KviIrcMessage::safePrefix(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumeric367 (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), getDateTimeStringFromCharTimeT(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_BAN, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviChannelWindow::sentListRequest(), KviIrcConnection::serverInfo(), KviChannelWindow::setModeInList(), and KviIrcConnectionServerInfo::supportedListModes().
void KviIrcServerParser::parseNumeric368 (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_BAN, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviChannelWindow::sentListRequest(), KviIrcConnection::serverInfo(), KviChannelWindow::setListRequestDone(), and KviIrcConnectionServerInfo::supportedListModes().
void KviIrcServerParser::parseNumericAList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericAway (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_PARANOIC, KviConsoleWindow::activeWindow(), KviIrcConnection::changeAwayState(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_AWAY, KviEvent_OnMeAway, KviOption_boolAutoGeneratedAwayNick, KviOption_boolChangeNickAway, KviOption_boolServerRepliesToActiveWindow, KviOption_stringCustomAwayNick, KVS_TRIGGER_EVENT_1_HALTED, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), and KviIrcMessage::setHaltOutput().
void KviIrcServerParser::parseNumericBackFromAway (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_PARANOIC, KviConsoleWindow::activeWindow(), KviIrcConnectionUserInfo::awayTime(), KviIrcConnection::changeAwayState(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::encodeText(), KviIrcMessage::haltOutput(), KviIrcConnectionUserInfo::isAway(), KVI_OPTION_BOOL, KVI_OUT_AWAY, kvi_unixTime, KviEvent_OnMeBack, KviOption_boolChangeNickAway, KviOption_boolServerRepliesToActiveWindow, KVS_TRIGGER_EVENT_2_HALTED, KviIrcConnectionUserInfo::nickNameBeforeAway(), KviWindow::output(), KviIrcMessage::safeTrailing(), KviIrcConnection::sendFmtData(), KviIrcMessage::setHaltOutput(), and KviIrcConnection::userInfo().
void KviIrcServerParser::parseNumericCannotSend (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericCannotSendColor (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericCantJoinChannel (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_JOINERROR, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericChannelModeIs (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), IS_CHANNEL_TYPE_FLAG, KVI_OPTION_BOOL, KVI_OUT_CHANMODE, KVI_OUT_MODE, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), parseChannelMode(), KviIrcMessage::safeParam(), and KviIrcMessage::safePrefix().
void KviIrcServerParser::parseNumericChanUrl (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_CHANURL, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), and szUrl.
void KviIrcServerParser::parseNumericCodePageScheme (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::allParams(), KviControlCodes::Bold, KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcConnection::console(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KVI_OUT_WHOISOTHER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::prefix(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnection::serverInfo(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviIrcConnectionServerInfo::supportsCodePages().
void KviIrcServerParser::parseNumericCodePageSet (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviLocale::codecForName(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcConnection::console(), KviIrcMessage::console(), KviIrcConnection::currentNickName(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviLocale::instance(), KVI_OUT_TEXTENCODING, KVI_OUT_UNHANDLED, KviWindow::output(), KviIrcMessage::prefix(), KviIrcMessage::safeParam(), KviIrcConnection::serverInfo(), KviIrcConnection::setEncoding(), KviWindow::setTextEncoding(), and KviIrcConnectionServerInfo::supportsCodePages().
void KviIrcServerParser::parseNumericCommandSyntax (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_STATS, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericCreationTime (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviCString::isUnsignedNum(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_CREATIONTIME, KviOption_boolServerRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviWindow::output(), KviIrcMessage::safeParam(), KviCString::toUInt(), and UNRECOGNIZED_MESSAGE.
void KviIrcServerParser::parseNumericEndOfAList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericEndOfExceptList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericEndOfInviteList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericEndOfLinks (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviConsoleWindow::context(), KviExternalServerDataParser::control(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_ENDOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LINKS, KviIrcContext::linksWindow(), and KviWindow::output().
void KviIrcServerParser::parseNumericEndOfNames (KviIrcMessage * msg) [private]
References __tr2qs, _OUTPUT_MUTE, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviChannelWindow::hasAllNames(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), and KviChannelWindow::setHasAllNames().
void KviIrcServerParser::parseNumericEndOfQList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericEndOfReopList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericEndOfSpamFilterList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericEndOfStats (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_STATS, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericEndOfWho (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviChannelWindow::clearSentSyncWhoRequest(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviCString::Format, KviIrcMessage::haltOutput(), KviChannelWindow::hasWhoList(), IS_CHANNEL_TYPE_FLAG, KVI_OPTION_BOOL, KVI_OUT_WHO, kvi_time_t, kvi_unixTime, KviOption_boolServerRepliesToActiveWindow, KviLagMeter::lagCheckComplete(), KviIrcConnection::lagMeter(), KviWindow::output(), KviIrcMessage::safeParam(), KviChannelWindow::sentSyncWhoRequest(), KviChannelWindow::setHasWhoList(), KviIrcConnectionStateData::setLastReceivedChannelWhoReply(), KviChannelWindow::setLastReceivedWhoReply(), KviIrcConnection::stateData(), KviUserListView::updateArea(), and KviChannelWindow::userListView().
void KviIrcServerParser::parseNumericEndOfWhois (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviKvsVariantList::append(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), g_pApp, KviIrcMessage::haltOutput(), i, KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviKvsScript::PreserveParams, KviAsyncWhoisInfo::pWindow, KviIrcConnectionAsyncData< T >::remove(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviIrcMessage::safePrefix(), KviKvsVariantList::setAutoDelete(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szAdditional, KviAsyncWhoisInfo::szAuth, KviAsyncWhoisInfo::szAway, KviAsyncWhoisInfo::szChannels, KviAsyncWhoisInfo::szHost, KviAsyncWhoisInfo::szIdle, KviAsyncWhoisInfo::szNick, KviAsyncWhoisInfo::szReal, KviAsyncWhoisInfo::szServer, KviAsyncWhoisInfo::szSignon, KviAsyncWhoisInfo::szUser, and KviApplication::windowExists().
void KviIrcServerParser::parseNumericEndOfWhowas (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcMessage::safePrefix().
void KviIrcServerParser::parseNumericExceptList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericInfo (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericInfoEnd (KviIrcMessage * msg) [private]
References __tr2qs, KviControlCodes::Bold, KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::output(), and KviIrcMessage::prefix().
void KviIrcServerParser::parseNumericInfoStart (KviIrcMessage * msg) [private]
References __tr2qs, KviControlCodes::Bold, KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::output(), and KviIrcMessage::prefix().
void KviIrcServerParser::parseNumericInviteList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericInviting (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OUT_INVITE, KviWindow::output(), and KviIrcMessage::safeParam().
void KviIrcServerParser::parseNumericIsOn (KviIrcMessage * msg) [private]
References KviConsoleWindow::activeWindow(), KviIrcMessage::allParams(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviNotifyListManager::handleIsOn(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviIrcConnection::notifyListManager(), KviWindow::output(), and KviIrcMessage::safePrefix().
void KviIrcServerParser::parseNumericLinks (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviIrcMessage::connection(), KviIrcMessage::console(), KviConsoleWindow::context(), KviIrcContext::createLinksWindow(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_LINKS, KviIrcContext::linksWindow(), KviWindow::output(), and KviExternalServerDataParser::processData().
void KviIrcServerParser::parseNumericList (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::allParams(), KviIrcMessage::connection(), KviIrcMessage::console(), KviConsoleWindow::context(), KviExternalServerDataParser::control(), KviIrcContext::createListWindow(), KviIrcConnection::decodeText(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_STARTOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LIST, KviIrcContext::listWindow(), KviWindow::output(), and KviExternalServerDataParser::processData().
void KviIrcServerParser::parseNumericListEnd (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviConsoleWindow::context(), KviExternalServerDataParser::control(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_ENDOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LIST, KviIrcContext::listWindow(), and KviWindow::output().
void KviIrcServerParser::parseNumericListStart (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::console(), KviConsoleWindow::context(), KviExternalServerDataParser::control(), KviIrcContext::createListWindow(), EXTERNAL_SERVER_DATA_PARSER_CONTROL_STARTOFDATA, KviIrcMessage::haltOutput(), KVI_OUT_LIST, KviIrcContext::listWindow(), and KviWindow::output().
void KviIrcServerParser::parseNumericMotd (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::endOfMotdReceived(), KviIrcMessage::haltOutput(), KVI_OUT_MOTD, KviIrcMessage::numeric(), KviWindow::outputNoFmt(), RPL_ENDOFMOTD, and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericNames (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviChannelWindow::enableUserListUpdates(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviChannelWindow::hasAllNames(), KviIrcConnectionServerInfo::isSupportedModePrefix(), KviChannelWindow::join(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviIrcConnectionServerInfo::modeFlagFromPrefixChar(), KviChannelWindow::myFlags(), KviWindow::output(), KviCString::ptr(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailingString(), KviTheme::save(), KviIrcConnection::serverInfo(), and KviWindow::updateCaption().
void KviIrcServerParser::parseNumericNicknameProblem (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviConsoleWindow::isConnected(), KVI_OUT_NICKNAMEPROBLEM, KviWindow::output(), parseLoginNicknameProblem(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericNoSuchChannel (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviWindow::output(), and KviIrcMessage::safeParam().
void KviIrcServerParser::parseNumericNoSuchNick (KviIrcMessage * msg) [private]
References KviConsoleWindow::activeWindow(), KviKvsVariantList::append(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), ERR_NOSUCHNICK, KviIrcConnection::findQuery(), g_pApp, KviIrcMessage::haltOutput(), i, KVI_OUT_NICKNAMEPROBLEM, KviIrcConnectionAsyncData< T >::lookup(), KviIrcMessage::numeric(), KviWindow::output(), KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviKvsScript::PreserveParams, KviAsyncWhoisInfo::pWindow, KviIrcConnectionAsyncData< T >::remove(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviKvsVariantList::setAutoDelete(), KviAsyncWhoisInfo::szNick, and KviApplication::windowExists().
void KviIrcServerParser::parseNumericNoSuchServer (KviIrcMessage * msg) [private]
References __tr2qs, KviKvsVariantList::append(), KviIrcConnection::asyncWhoisData(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), g_pApp, KviIrcMessage::haltOutput(), i, KVI_OUT_GENERICERROR, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviKvsScript::PreserveParams, KviAsyncWhoisInfo::pWindow, KviIrcConnectionAsyncData< T >::remove(), KviKvsScript::run(), KviIrcMessage::safeParam(), KviKvsVariantList::setAutoDelete(), KviAsyncWhoisInfo::szNick, and KviApplication::windowExists().
void KviIrcServerParser::parseNumericNoTopic (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_TOPIC, KviOption_boolEchoNumericTopic, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcMessage::safeParam(), KviTopicWidget::setTopic(), and KviChannelWindow::topicWidget().
void KviIrcServerParser::parseNumericNotRegistered (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviIrcConnection::handleFailedInitialCapLs(), KviIrcConnectionStateData::ignoreOneYouHaveNotRegisteredError(), KviIrcConnectionStateData::isInsideInitialCapLs(), KviIrcConnectionStateData::isInsideInitialStartTls(), KVI_OUT_GENERICERROR, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setIgnoreOneYouHaveNotRegisteredError(), and KviIrcConnection::stateData().
void KviIrcServerParser::parseNumericQList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericReopList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericSaslFail (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::endInitialCapNegotiation(), KviIrcMessage::haltOutput(), KviIrcConnectionStateData::isInsideAuthenticate(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::safeTrailing(), and KviIrcConnection::stateData().
void KviIrcServerParser::parseNumericSaslLogin (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::endInitialCapNegotiation(), KviIrcMessage::haltOutput(), KviIrcConnectionStateData::isInsideAuthenticate(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::safeParam(), and KviIrcConnection::stateData().
void KviIrcServerParser::parseNumericSaslSuccess (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::endInitialCapNegotiation(), KviIrcMessage::haltOutput(), KviIrcConnectionStateData::isInsideAuthenticate(), KVI_OUT_SERVERINFO, KviWindow::outputNoFmt(), and KviIrcConnection::stateData().
void KviIrcServerParser::parseNumericServerAdminInfoAdminContact (KviIrcMessage * msg) [private]
References __tr2qs, KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericServerAdminInfoAdminName (KviIrcMessage * msg) [private]
References __tr2qs, KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericServerAdminInfoServerName (KviIrcMessage * msg) [private]
References __tr2qs, KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericServerAdminInfoTitle (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::outputNoFmt(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericSpamFilterList (KviIrcMessage * msg) [private]
void KviIrcServerParser::parseNumericStartTls (KviIrcMessage * msg) [private]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OUT_GENERICERROR, KviIrcMessage::numeric(), KviWindow::output(), parseNumericWhoisOther(), RPL_STARTTLSFAIL, RPL_STARTTLSOK, KviIrcConnectionStateData::sentStartTls(), and KviIrcConnection::stateData().
void KviIrcServerParser::parseNumericStats (KviIrcMessage * msg) [private]
References KviCString::append(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::firstParam(), KviIrcMessage::haltOutput(), KviCString::hasData(), KVI_OUT_STATS, KviIrcMessage::nextParam(), KviWindow::outputNoFmt(), p, KviIrcMessage::paramCount(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericTime (KviIrcMessage * msg) [private]
References __tr2qs, KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OUT_SERVERINFO, KviWindow::output(), KviIrcMessage::prefix(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericTopic (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_TOPIC, KviOption_boolEchoNumericTopic, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviTopicWidget::setTopic(), KviTopicWidget::setTopicSetBy(), and KviChannelWindow::topicWidget().
void KviIrcServerParser::parseNumericTopicWhoTime (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcConnection::findChannel(), KviIrcMessage::haltOutput(), KviCString::hasData(), KviIrcMask::hasHost(), KviIrcMask::hasUser(), KviIrcMask::host(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_TOPIC, KviOption_boolEchoNumericTopic, KviOption_boolServerRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviIrcMask::nick(), KviWindow::output(), KviIrcMessage::safeParam(), KviTopicWidget::setTopicSetAt(), KviTopicWidget::setTopicSetBy(), t(), KviChannelWindow::topicWidget(), KviCString::toUInt(), and KviIrcMask::user().
void KviIrcServerParser::parseNumericUnavailResource (KviIrcMessage * msg) [private]
References KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviConsoleWindow::isConnected(), KVI_OUT_NICKNAMEPROBLEM, KviWindow::output(), parseLoginNicknameProblem(), KviIrcMessage::safeParam(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericUserhost (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KviNotifyListManager::handleUserhost(), KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, KviOption_boolServerRepliesToActiveWindow, KviIrcConnection::notifyListManager(), KviWindow::output(), and KviIrcMessage::safeTrailing().
void KviIrcServerParser::parseNumericUserMode (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcMessage::console(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_MODE, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), parseUserMode(), and KviIrcMessage::safeParam().
void KviIrcServerParser::parseNumericWatch (KviIrcMessage * msg) [private]
References KviConsoleWindow::activeWindow(), KviIrcMessage::allParams(), KviIrcMessage::command(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcMessage::haltOutput(), KviNotifyListManager::handleWatchReply(), KVI_OPTION_BOOL, KVI_OUT_UNHANDLED, KviOption_boolServerRepliesToActiveWindow, KviIrcConnection::notifyListManager(), KviWindow::output(), and KviIrcMessage::prefix().
void KviIrcServerParser::parseNumericWhoisActually (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), i, KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviAsyncWhoisInfo::szAdditional.
void KviIrcServerParser::parseNumericWhoisAuth (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviIrcMessage::numeric(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviAsyncWhoisInfo::szAuth.
void KviIrcServerParser::parseNumericWhoisAway (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), KviIrcMessage::haltOutput(), i, KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcUserEntry::setAway(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szAway, KviQueryWindow::updateLabelText(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseNumericWhoisChannels (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviQString::appendFormatted(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), i, IS_CHANNEL_TYPE_FLAG, IS_USER_MODE_PREFIX, KVI_OPTION_BOOL, KVI_OUT_WHOISCHANNELS, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szChannels, and szR.
void KviIrcServerParser::parseNumericWhoisIdle (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), i, KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_WHOISIDLE, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviOption_uintOutputDatetimeFormat, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szIdle, KviAsyncWhoisInfo::szSignon, KviCString::toUInt(), and UNRECOGNIZED_MESSAGE.
void KviIrcServerParser::parseNumericWhoisOther (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), i, KVI_OPTION_BOOL, KVI_OUT_WHOISOTHER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcConnection::stateData(), and KviAsyncWhoisInfo::szAdditional.
Referenced by parseMessage(), and parseNumericStartTls().
void KviIrcServerParser::parseNumericWhoisServer (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviWindow::decodeText(), KviIrcConnection::decodeText(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), KviIrcMessage::haltOutput(), i, KVI_OPTION_BOOL, KVI_OUT_WHOISSERVER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcUserEntry::setServer(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szServer, KviQueryWindow::updateLabelText(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseNumericWhoisUser (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviIrcConnection::asyncWhoisData(), KviIrcUserEntry::avatar(), KviControlCodes::Bold, KviConsoleWindow::checkDefaultAvatar(), KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviQString::equalCS(), KviIrcUserDataBase::find(), KviIrcConnection::findQuery(), g_pActiveWindow, KviIrcUserEntry::gender(), KviIrcMessage::haltOutput(), i, IS_ME, KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, kvi_unixTime, KviOption_boolWhoisRepliesToActiveWindow, KviIrcConnectionAsyncData< T >::lookup(), KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), KviIrcUserEntry::setHost(), KviIrcConnectionStateData::setLastReceivedWhoisReply(), KviIrcUserEntry::setRealName(), KviIrcUserEntry::setUser(), KviIrcConnection::stateData(), KviAsyncWhoisInfo::szHost, szHost, KviAsyncWhoisInfo::szNick, KviAsyncWhoisInfo::szReal, KviAsyncWhoisInfo::szUser, KviControlCodes::Underline, KviIrcUserEntry::Unknown, KviQueryWindow::updateLabelText(), and KviIrcConnection::userDataBase().
void KviIrcServerParser::parseNumericWhoReply (KviIrcMessage * msg) [private]
References __tr2qs, KviIrcUserEntry::avatar(), KviIrcUserEntry::avatarRequested(), KviControlCodes::Bold, KviWindow::connection(), d, KviIrcUserDataBase::find(), KviIrcConnection::findChannel(), KviIrcConnection::findQuery(), KviCString::getToken(), KviChannelWindow::hasWhoList(), IS_ME, KVI_OPTION_BOOL, KVI_OUT_WHO, KviOption_boolRequestMissingAvatars, KviOption_boolServerRepliesToActiveWindow, KviWindow::output(), KviCString::ptr(), KviControlCodes::Reset, KviChannelWindow::sentSyncWhoRequest(), KviIrcUserEntry::setAvatarRequested(), KviIrcUserEntry::setAway(), KviIrcUserEntry::setHops(), KviIrcUserEntry::setHost(), KviIrcUserEntry::setIrcOp(), KviIrcUserEntry::setRealName(), KviIrcUserEntry::setServer(), KviIrcUserEntry::setUser(), KviIrcUserEntry::setUserFlags(), szHost, KviCString::toInt(), KviControlCodes::Underline, and KviQueryWindow::updateLabelText().
void KviIrcServerParser::parseNumericWhowasUser (KviIrcMessage * msg) [private]
References __tr2qs, KviConsoleWindow::activeWindow(), KviControlCodes::Bold, KviIrcMessage::connection(), KviIrcMessage::console(), KviIrcConnection::decodeText(), KviIrcMessage::haltOutput(), KVI_OPTION_BOOL, KVI_OUT_WHOISUSER, KviOption_boolWhoisRepliesToActiveWindow, KviWindow::output(), KviIrcMessage::safeParam(), KviIrcMessage::safeTrailing(), szHost, and KviControlCodes::Underline.
void KviIrcServerParser::parseUserMode (KviIrcMessage * msg, const char * modeflptr) [private]
References KviIrcConnection::changeUserMode(), KviIrcMessage::connection(), KviIrcMessage::console(), KviKvsEventManager::hasAppHandlers(), KviKvsEventManager::instance(), KviEvent_OnNickServAuth, KviEvent_OnUserModeChange, KviIrcConnectionServerInfo::registerModeChar(), KviIrcConnection::serverInfo(), KviIrcMessage::setHaltOutput(), and KviKvsEventManager::trigger().
Referenced by parseLiteralMode(), and parseNumericUserMode().
void KviIrcServerParser::replyCtcp (KviCtcpMessage * msg, const QString & data) [private]
References KviIrcMessage::connection(), KviIrcConnection::encodeText(), _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pSource, KviIrcConnection::sendFmtData(), and _KviCtcpMessage::szTag.
Referenced by parseCtcpRequestAvatar(), parseCtcpRequestClientinfo(), parseCtcpRequestFinger(), parseCtcpRequestPage(), parseCtcpRequestPing(), parseCtcpRequestSource(), parseCtcpRequestTime(), parseCtcpRequestUserinfo(), and parseCtcpRequestVersion().
Member Data Documentation
KviCtcpMessageParseStruct KviIrcServerParser::m_ctcpReplyParseProcTable [static, private]
Initial value:
{
        { "ACTION"     , PTM(parseCtcpRequestAction)     , 0 },
        { "AVATAR"     , PTM(parseCtcpReplyAvatar)       , 0 },
        { "CLIENTINFO" , PTM(parseCtcpReplyGeneric)      , 0 },
        { "DCC"        , PTM(parseCtcpRequestDcc)        , 0 },
        { "FINGER"     , PTM(parseCtcpReplyGeneric)      , 0 },
        { "LAGCHECK"   , PTM(parseCtcpReplyLagcheck)     , KVI_CTCP_MESSAGE_PARSE_TRIGGERNOEVENT },
        { "PAGE"       , PTM(parseCtcpReplyGeneric)      , 0 },
        { "PING"       , PTM(parseCtcpReplyPing)         , 0 },
        { "SOURCE"     , PTM(parseCtcpReplyGeneric)      , 0 },
        { "TDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { "TIME"       , PTM(parseCtcpReplyGeneric)      , 0 },
        { "USERINFO"   , PTM(parseCtcpReplyUserinfo)     , 0 },
        { "VERSION"    , PTM(parseCtcpReplyGeneric)      , 0 },
        { "XDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { 0            , 0                               , 0 }
}
Referenced by parseCtcpReply(), and parseCtcpRequest().
KviCtcpMessageParseStruct KviIrcServerParser::m_ctcpRequestParseProcTable [static, private]
Initial value:
{
        { "ACTION"     , PTM(parseCtcpRequestAction)     , 0 },
        { "AVATAR"     , PTM(parseCtcpRequestAvatar)     , 0 },
        { "CLIENTINFO" , PTM(parseCtcpRequestClientinfo) , 0 },
        { "DCC"        , PTM(parseCtcpRequestDcc)        , 0 },
        { "FINGER"     , PTM(parseCtcpRequestFinger)     , 0 },
        { "PAGE"       , PTM(parseCtcpRequestPage)       , 0 },
        { "PING"       , PTM(parseCtcpRequestPing)       , 0 },
        { "SOURCE"     , PTM(parseCtcpRequestSource)     , 0 },
        { "TDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { "TIME"       , PTM(parseCtcpRequestTime)       , 0 },
        { "USERINFO"   , PTM(parseCtcpRequestUserinfo)   , 0 },
        { "VERSION"    , PTM(parseCtcpRequestVersion)    , 0 },
        { "XDCC"       , PTM(parseCtcpRequestDcc)        , 0 },
        { 0            , 0                               , 0 }
}
Referenced by parseCtcpRequest().
KviLiteralMessageParseStruct KviIrcServerParser::m_literalParseProcTable [static, private]
Initial value:
{
        { "AUTHENTICATE" , PTM(parseLiteralAuthenticate) },
        { "CAP"          , PTM(parseLiteralCap)          },
        { "ERROR"        , PTM(parseLiteralError)        },
        { "INVITE"       , PTM(parseLiteralInvite)       },
        { "JOIN"         , PTM(parseLiteralJoin)         },
        { "KICK"         , PTM(parseLiteralKick)         },
        { "MODE"         , PTM(parseLiteralMode)         },
        { "NICK"         , PTM(parseLiteralNick)         },
        { "NOTICE"       , PTM(parseLiteralNotice)       },
        { "PART"         , PTM(parseLiteralPart)         },
        { "PING"         , PTM(parseLiteralPing)         },
        { "PONG"         , PTM(parseLiteralPong)         },
        { "PRIVMSG"      , PTM(parseLiteralPrivmsg)      },
        { "QUIT"         , PTM(parseLiteralQuit)         },
        { "TOPIC"        , PTM(parseLiteralTopic)        },
        { "WALLOPS"      , PTM(parseLiteralWallops)      },
        { 0              , 0                             }
}
Referenced by parseMessage().
messageParseProc KviIrcServerParser::m_numericParseProcTable [static, private]
Referenced by parseMessage().
KviCString KviIrcServerParser::m_szLastParserError [private]
Referenced by parseMessage().
The documentation for this class was generated from the following files:
src/kvirc/sparser/KviIrcServerParser.h
src/kvirc/sparser/KviIrcServerParser.cpp
src/kvirc/sparser/KviIrcServerParser_ctcp.cpp
src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp
src/kvirc/sparser/KviIrcServerParser_numericHandlers.cpp
src/kvirc/sparser/KviIrcServerParser_tables.cpp