KVIrc: KvsObject_toolButton Class Reference
KvsObject_toolButton Class Reference
#include <KvsObject_toolButton.h>
Signals
void clicked ()
Public Member Functions
QWidget * widget ()
Protected Slots
void slotClicked ()
Protected Member Functions
bool autoRaise (KviKvsObjectFunctionCall *c)
bool clickEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool openPopup (KviKvsObjectFunctionCall *c)
bool setAutoRaise (KviKvsObjectFunctionCall *c)
bool setImage (KviKvsObjectFunctionCall *c)
bool setOn (KviKvsObjectFunctionCall *c)
bool setPopup (KviKvsObjectFunctionCall *c)
bool setTextLabel (KviKvsObjectFunctionCall *c)
bool setTextPosition (KviKvsObjectFunctionCall *c)
bool setToggleButton (KviKvsObjectFunctionCall *c)
bool setUsesBigPixmap (KviKvsObjectFunctionCall *c)
bool setUsesTextLabel (KviKvsObjectFunctionCall *c)
bool textLabel (KviKvsObjectFunctionCall *c)
bool textPosition (KviKvsObjectFunctionCall *c)
bool toggle (KviKvsObjectFunctionCall *c)
bool usesBigPixmap (KviKvsObjectFunctionCall *c)
bool usesTextLabel (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_toolButton::autoRaise (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_toolButton::clicked () [signal]
bool KvsObject_toolButton::clickEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_toolButton::openPopup (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setAutoRaise (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setImage (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setOn (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setPopup (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setTextLabel (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setTextPosition (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setToggleButton (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setUsesBigPixmap (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::setUsesTextLabel (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_toolButton::slotClicked () [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_toolButton::textLabel (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::textPosition (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::toggle (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::usesBigPixmap (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_toolButton::usesTextLabel (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_toolButton::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_toolButton.h
src/modules/objects/KvsObject_toolButton.cpp