KVIrc: KviDebugWindow Class Reference
KviDebugWindow Class Reference
#include <kvi_debugwindow.h>
Public Member Functions
KviDebugWindow ()
~KviDebugWindow ()
Static Public Member Functions
static KviDebugWindow * getInstance ()
static KviDebugWindow * instance ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &buffer)
virtual void loadProperties (KviConfig *cfg)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfig *cfg)
virtual QSize sizeHint () const
Static Protected Attributes
static KviDebugWindow * m_pInstance = 0
Constructor & Destructor Documentation
KviDebugWindow::KviDebugWindow ()
References g_pFrame, KviWindow::KviInput, KviWindow::m_pInput, m_pInstance, KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviWindow::updateCaption().
Referenced by getInstance().
KviDebugWindow::~KviDebugWindow ()
References m_pInstance.
Member Function Documentation
void KviDebugWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_szPlainTextCaption, and KviWindow::windowName().
void KviDebugWindow::getBaseLogFileName (QString & buffer) [protected, virtual]
Reimplemented from KviWindow.
KviDebugWindow * KviDebugWindow::getInstance () [static]
References KviFrame::addWindow(), g_pFrame, KVI_OPTION_BOOL, KviDebugWindow(), KviOption_boolShowMinimizedDebugWindow, m_pInstance, and KviWindow::minimize().
Referenced by KviKvsCoreSimpleCommands::KVSCSC(), and KviKvsReport::report().
static KviDebugWindow* KviDebugWindow::instance () [inline, static]
Referenced by KviKvsReport::report().
void KviDebugWindow::loadProperties (KviConfig * cfg) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, KviConfig::readIntListEntry(), and KviTalSplitter::setSizes().
QPixmap * KviDebugWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KVI_SMALLICON_BUG.
void KviDebugWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pInput, and KviWindow::m_pSplitter.
void KviDebugWindow::saveProperties (KviConfig * cfg) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, KviTalSplitter::sizes(), and KviConfig::writeEntry().
QSize KviDebugWindow::sizeHint () const [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pInput, KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviIrcView::sizeHint().
Member Data Documentation
KviDebugWindow * KviDebugWindow::m_pInstance = 0 [static, protected]
Referenced by getInstance(), KviDebugWindow(), and ~KviDebugWindow().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_debugwindow.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_debugwindow.cpp