KVIrc: KvsObject_wizard Class Reference
KvsObject_wizard Class Reference
#include <KvsObject_wizard.h>
Public Member Functions
bool accept ()
void backClicked ()
void nextClicked ()
bool reject ()
QWidget * widget ()
Protected Member Functions
bool addPage (KviKvsObjectFunctionCall *c)
bool backClickedEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertPage (KviKvsObjectFunctionCall *c)
bool nextClickedEvent (KviKvsObjectFunctionCall *c)
bool removePage (KviKvsObjectFunctionCall *c)
bool setBackBtnText (KviKvsObjectFunctionCall *c)
bool setBackEnabled (KviKvsObjectFunctionCall *c)
bool setFinishBtnText (KviKvsObjectFunctionCall *c)
bool setFinishEnabled (KviKvsObjectFunctionCall *c)
bool setHelpBtnText (KviKvsObjectFunctionCall *c)
bool setHelpEnabled (KviKvsObjectFunctionCall *c)
bool setNextBtnText (KviKvsObjectFunctionCall *c)
bool setNextEnabled (KviKvsObjectFunctionCall *c)
bool setTitle (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_wizard::accept ()
References KviKvsObject::callFunction().
Referenced by KviKvsMdmWizard::accept().
bool KvsObject_wizard::addPage (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_wizard::backClicked ()
References KviKvsObject::callFunction().
Referenced by KviKvsMdmWizard::slotBackClicked().
bool KvsObject_wizard::backClickedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
bool KvsObject_wizard::insertPage (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_wizard::nextClicked ()
References KviKvsObject::callFunction().
Referenced by KviKvsMdmWizard::slotNextClicked().
bool KvsObject_wizard::nextClickedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::reject ()
References KviKvsObject::callFunction().
Referenced by KviKvsMdmWizard::reject().
bool KvsObject_wizard::removePage (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setBackBtnText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setBackEnabled (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setFinishBtnText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setFinishEnabled (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setHelpBtnText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setHelpEnabled (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setNextBtnText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setNextEnabled (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_wizard::setTitle (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_wizard::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_wizard.h
src/modules/objects/KvsObject_wizard.cpp