KVIrc: OptionsWidget_inputFeatures Class Reference
OptionsWidget_inputFeatures Class Reference
#include <OptionsWidget_input.h>
Public Member Functions
OptionsWidget_inputFeatures (QWidget *parent)
~OptionsWidget_inputFeatures ()
Constructor & Destructor Documentation
OptionsWidget_inputFeatures::OptionsWidget_inputFeatures (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), c, connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolBashLikeNickCompletion, KviOption_boolCommandlineInUserFriendlyModeByDefault, KviOption_boolEnableInputHistory, KviOption_boolHideInputToolButtons, KviOption_boolInputHistoryCursorAtEnd, KviOption_boolUseNickCompletionPostfixForFirstWordOnly, KviOption_boolZshLikeNickCompletion, KviOption_stringNickCompletionPostfix, and KviOption_uintSpacesToExpandTabulationInput.
OptionsWidget_inputFeatures::~OptionsWidget_inputFeatures ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_input.h
src/modules/options/OptionsWidget_input.cpp