KVIrc: KviDnsResult Class Reference
KviDnsResult Class Reference
#include <kvi_dns.h>
Public Member Functions
int error ()
KviPointerList< QString > * hostnameList ()
KviPointerList< QString > * ipAddressList ()
const QString & query ()
~KviDnsResult ()
Protected Member Functions
void appendAddress (const QString &addr)
void appendHostname (const QString &host)
KviDnsResult ()
void setError (int iError)
void setQuery (const QString &query)
Protected Attributes
int m_iError
KviPointerList< QString > * m_pHostnameList
KviPointerList< QString > * m_pIpAddressList
QString m_szQuery
Friends
class KviDns
class KviDnsThread
Constructor & Destructor Documentation
KviDnsResult::KviDnsResult () [protected]
References KviError_success, m_iError, m_pHostnameList, m_pIpAddressList, and KviPointerList< T >::setAutoDelete().
KviDnsResult::~KviDnsResult ()
References m_pHostnameList, and m_pIpAddressList.
Member Function Documentation
void KviDnsResult::appendAddress (const QString & addr) [protected]
References KviPointerList< T >::append(), and m_pIpAddressList.
Referenced by KviDnsThread::run().
void KviDnsResult::appendHostname (const QString & host) [protected]
References KviPointerList< T >::append(), and m_pHostnameList.
Referenced by KviDnsThread::run().
int KviDnsResult::error () [inline]
Referenced by KviDns::error(), and KviDns::event().
KviPointerList<QString>* KviDnsResult::hostnameList () [inline]
Referenced by KviDns::firstHostname(), KviDns::hostnameCount(), and KviDns::hostnameList().
KviPointerList<QString>* KviDnsResult::ipAddressList () [inline]
Referenced by KviDns::firstIpAddress(), KviDns::ipAddressCount(), and KviDns::ipAddressList().
const QString& KviDnsResult::query () [inline]
References KviDnsThread::m_szQuery.
Referenced by KviDns::query().
void KviDnsResult::setError (int iError) [inline, protected]
Referenced by KviDnsThread::postDnsError(), and KviDnsThread::run().
void KviDnsResult::setQuery (const QString & query) [inline, protected]
References KviDnsThread::m_szQuery.
Referenced by KviDnsThread::run().
Friends And Related Function Documentation
friend class KviDns [friend]
friend class KviDnsThread [friend]
Member Data Documentation
int KviDnsResult::m_iError [protected]
Referenced by KviDnsResult().
KviPointerList<QString>* KviDnsResult::m_pHostnameList [protected]
Referenced by appendHostname(), KviDnsResult(), and ~KviDnsResult().
KviPointerList<QString>* KviDnsResult::m_pIpAddressList [protected]
Referenced by appendAddress(), KviDnsResult(), and ~KviDnsResult().
QString KviDnsResult::m_szQuery [protected]
The documentation for this class was generated from the following files:
src/kvilib/net/kvi_dns.h
src/kvilib/net/kvi_dns.cpp