KVIrc: DccVideoSJpegCodec Class Reference
DccVideoSJpegCodec Class Reference
#include <DccVoiceCodec.h>
Public Member Functions
DccVideoSJpegCodec ()
virtual void decode (KviDataBuffer *stream, KviDataBuffer *videoSignal, KviDataBuffer *textSignal)
virtual int decodedFrameSize ()
virtual int encodedFrameSize ()
virtual void encodeText (KviDataBuffer *textSignal, KviDataBuffer *stream)
virtual void encodeVideo (KviDataBuffer *videoSignal, KviDataBuffer *stream)
virtual ~DccVideoSJpegCodec ()
Public Member Functions inherited from DccVideoCodec
DccVideoCodec ()
const char * name ()
virtual ~DccVideoCodec ()
Additional Inherited Members
Protected Attributes inherited from DccVideoCodec
KviCString m_szName
Constructor & Destructor Documentation
DccVideoSJpegCodec::DccVideoSJpegCodec ()
References DccVideoCodec::m_szName.
DccVideoSJpegCodec::~DccVideoSJpegCodec () virtual
Member Function Documentation
void DccVideoSJpegCodec::decode (KviDataBuffer * stream, KviDataBuffer * videoSignal, KviDataBuffer * textSignal) virtual
Reimplemented from DccVideoCodec.
References KviDataBuffer::append(), KviDataBuffer::clear(), KviDataBuffer::data(), KviDataBuffer::find(), KviDataBuffer::remove(), and KviDataBuffer::size().
int DccVideoSJpegCodec::decodedFrameSize () virtual
Reimplemented from DccVideoCodec.
int DccVideoSJpegCodec::encodedFrameSize () virtual
Reimplemented from DccVideoCodec.
void DccVideoSJpegCodec::encodeText (KviDataBuffer * textSignal, KviDataBuffer * stream) virtual
Reimplemented from DccVideoCodec.
References KviDataBuffer::append(), KviDataBuffer::clear(), KviDataBuffer::data(), and KviDataBuffer::size().
void DccVideoSJpegCodec::encodeVideo (KviDataBuffer * videoSignal, KviDataBuffer * stream) virtual
Reimplemented from DccVideoCodec.
References KviDataBuffer::append(), KviDataBuffer::clear(), KviDataBuffer::data(), and KviDataBuffer::size().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceCodec.h
src/modules/dcc/DccVoiceCodec.cpp