KVIrc: KviIrcContextDisplay Class Reference
KviIrcContextDisplay Class Reference
#include <KviIrcToolBar.h>
Public Member Functions
KviIrcContextDisplay (QWidget *par, const char *name=0)
~KviIrcContextDisplay ()
Public Member Functions inherited from KviToolBarGraphicalApplet
KviToolBarGraphicalApplet (QWidget *par, const char *name=0)
virtual QSize sizeHint () const
~KviToolBarGraphicalApplet ()
Protected Slots
void tipRequest (KviDynamicToolTip *tip, const QPoint &)
Protected Member Functions
virtual void drawContents (QPainter *p)
Protected Member Functions inherited from KviToolBarGraphicalApplet
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
Constructor & Destructor Documentation
KviIrcContextDisplay::KviIrcContextDisplay (QWidget * par, const char * name = 0)
References connect(), and tipRequest().
KviIrcContextDisplay::~KviIrcContextDisplay ()
Member Function Documentation
void KviIrcContextDisplay::drawContents (QPainter * p) protected virtual
Reimplemented from KviToolBarGraphicalApplet.
References __tr2qs, KviQString::appendFormatted(), c, KviWindow::connection(), KviWindow::console(), KviConsoleWindow::context(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), g_pActiveWindow, KviIrcContext::id(), KviIrcConnectionUserInfo::isAway(), KviConsoleWindow::isConnected(), KVI_APPLETIRCCONTEXTINDICATORWIDTH, KVI_NUM_ICCOLOR_OPTIONS, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_ICCOLOR, KviOption_boolShowLagOnContextDisplay, KviOption_colorIrcToolBarAppletForegroundHighContrastActive1, KviOption_colorIrcToolBarAppletForegroundMidContrast, KviLagMeter::lag(), KviIrcConnection::lagMeter(), spp, KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userMode().
void KviIrcContextDisplay::tipRequest (KviDynamicToolTip * tip, const QPoint &) protected slot
References __tr2qs, KviCString::append(), KviQString::appendFormatted(), c, KviWindow::connection(), KviWindow::console(), KviConsoleWindow::context(), KviIrcConnection::currentServerName(), KviCString::Format, g_pActiveWindow, KviIrcContext::id(), KVI_OPTION_BOOL, KviOption_boolShowLagOnContextDisplay, KviLagMeter::lag(), KviIrcConnection::lagMeter(), KviIrcConnectionUserInfo::nickName(), KviCString::ptr(), KviDynamicToolTip::tip(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userMode().
Referenced by KviIrcContextDisplay().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviIrcToolBar.h
src/kvirc/ui/KviIrcToolBar.cpp