KVIrc: KviQuery Class Reference
KviQuery Class Reference
The class which manages a query.
#include <kvi_query.h>
Public Member Functions
virtual void applyOptions ()
Applies the options.
bool avatarChanged (const QString &szNick)
Called when the target changes the avatar.
QFrame * buttonContainer ()
Returns the button container.
bool isDeadQuery ()
Returns true if the query is dead.
KviQuery (KviFrame *lpFrm, KviConsole *lpConsole, const QString &szNick)
Constructs the query object.
QByteArray loadLogFile (const QString &szFileName, bool bGzip)
Loads a log file.
void mergeQuery (KviQuery *q)
Merges a query into the one we're using.
bool nickChange (const QString &szOldNick, const QString &szNewNick)
Called when the target changes the nick.
void notifyCommonChannels (const QString &szNick, const QString &szUser, const QString &szHost, int iChans, const QString &szChans)
Notify us if we have common channels with the target.
void ownAction (const QString &szBuffer)
Called when we perform an action.
void ownMessage (const QString &szBuffer)
Called when we send a message to the query target.
void pasteLastLog ()
Pastes the most recent channel log into the buffer.
int selectedCount ()
Returns the number of selected users in the userlist.
void setAliveQuery ()
Sets the status of the query as alive.
void setDeadQuery ()
Sets the status of the query as dead.
KviUserListEntry * setTarget (const QString &szNick, const QString &szUser, const QString &szHost)
Sets the target of the query.
void showListView (bool bShow)
Shows the userlist view.
virtual QSize sizeHint () const
Returns the size of the query object.
virtual const QString & target ()
Returns the name of the query target.
void updateLabelText ()
Updates the text of the tooltip.
void userAction (const QString &szNick, const QString &szUser, const QString &szHost, unsigned int uActionType)
Called when a user performs an action.
void userAction (const QString &szNick, unsigned int uActionType)
Called when a user performs an action.
void userAction (KviIrcMask *user, unsigned int uActionType)
Called when a user performs an action.
~KviQuery ()
Destroys the query object.
Protected Slots
void slotDndEvents (const QString &pcFile)
Triggers the OnQueryFileDropped event.
void textViewRightClicked ()
Triggers the OnQueryPopupRequest event.
void toggleListView ()
Toggles the userlist view.
Protected Member Functions
virtual void fillCaptionBuffers ()
Fills in the caption buffers.
virtual void getBaseLogFileName (QString &szBuffer)
Gets the base of the log file name.
QString getInfoLabelText ()
Gets the info of the text in the upper part of the query.
QString getInfoLabelTipText ()
Gets the info of the tooltip text.
virtual void loadProperties (KviConfig *cfg)
Loads the properties from file.
virtual QPixmap * myIconPtr ()
Returns the icon associated to the query.
void notifyTargetChange (const QString &szOldNick, const QString &szOldUser, const QString &szOldHost, const QString &szNick, const QString &szUser, const QString &szHost)
Called to notify us that the target of the query is changed.
virtual void resizeEvent (QResizeEvent *e)
virtual void saveProperties (KviConfig *cfg)
Saves the properties to file.
virtual void triggerCreationEvents ()
Trigger the OnQueryWindowCreated event.
Protected Attributes
int m_iFlags
QFrame * m_pButtonGrid
KviThemedLabel * m_pLabel
KviWindowToolPageButton * m_pListViewButton
KviUserListView * m_pUserListView
Detailed Description
The class which manages a query.
Constructor & Destructor Documentation
KviQuery::KviQuery (KviFrame * lpFrm, KviConsole * lpConsole, const QString & szNick)
Constructs the query object.
Parameters:
lpFrm The parent frame
szNick The nickname with who we open a query
Returns:
KviQuery
References __tr2qs, buttonContainer(), KviWindow::connection(), KviWindow::createCryptControllerButton(), KviWindow::createTextEncodingButton(), KviIrcView::enableDnd(), KVI_OPTION_BOOL, KVI_SMALLICON_HIDELISTVIEW, KVI_SMALLICON_SHOWLISTVIEW, KviWindow::KviInput, KviOption_boolAutoLogQueries, m_iFlags, KviWindow::m_pButtonBox, m_pButtonGrid, KviWindow::m_pInput, KviWindow::m_pIrcView, m_pLabel, m_pListViewButton, KviWindow::m_pSplitter, m_pUserListView, KviIrcConnection::registerQuery(), KviTalHBox::setStretchFactor(), slotDndEvents(), KviIrcView::startLogging(), textViewRightClicked(), toggleListView(), KviWindow::updateCaption(), and updateLabelText().
KviQuery::~KviQuery ()
Destroys the query object.
References KviWindow::connection(), KviWindow::context(), KVI_WINDOW_TYPE_DEADQUERY, m_pUserListView, KviUserListView::partAll(), KviWindow::type(), KviIrcContext::unregisterDeadQuery(), and KviIrcConnection::unregisterQuery().
Member Function Documentation
void KviQuery::applyOptions () [virtual]
Applies the options.
Returns:
void
Reimplemented from KviWindow.
References KviUserListView::applyOptions(), m_pUserListView, and updateLabelText().
bool KviQuery::avatarChanged (const QString & szNick) [inline]
Called when the target changes the avatar.
Parameters:
szNick The nickname of the user
Returns:
bool
QFrame* KviQuery::buttonContainer () [inline, virtual]
Returns the button container.
Returns:
QFrame *
Reimplemented from KviWindow.
Referenced by KviQuery().
void KviQuery::fillCaptionBuffers () [protected, virtual]
Fills in the caption buffers.
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), KviWindow::m_szPlainTextCaption, and KviWindow::windowName().
void KviQuery::getBaseLogFileName (QString & szBuffer) [protected, virtual]
Gets the base of the log file name.
Parameters:
szBuffer The buffer where to save the info
Returns:
void
Reimplemented from KviWindow.
References KviWindow::connection(), KviWindow::console(), KviConsole::context(), KviWindow::context(), KviConsole::currentNetworkName(), KviIrcContext::id(), and KviWindow::windowName().
QString KviQuery::getInfoLabelText () [protected]
Gets the info of the text in the upper part of the query.
Returns:
QString
References __tr2qs, KviWindow::connection(), e, KviIrcUserDataBase::find(), KviIrcConnection::getCommonChannels(), KviIrcUserEntry::hasHops(), KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasRealName(), KviIrcUserEntry::hasServer(), KviIrcUserEntry::hasUser(), KviIrcUserEntry::hops(), KviIrcUserEntry::host(), KviIrcUserEntry::isAway(), KVI_OPTION_BOOL, KviOption_boolShowExtendedInfoInQueryLabel, KviWindow::m_szName, KviIrcUserEntry::realName(), KviIrcUserEntry::server(), KviMircCntrl::stripControlBytes(), KviIrcUserEntry::user(), and KviIrcConnection::userDataBase().
Referenced by updateLabelText().
QString KviQuery::getInfoLabelTipText () [protected]
Gets the info of the tooltip text.
Returns:
QString
References __tr2qs, KviWindow::connection(), e, END_TABLE_BOLD_ROW, KviIrcUserDataBase::find(), KviIrcConnection::getCommonChannels(), KviIrcUserEntry::hasHops(), KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasRealName(), KviIrcUserEntry::hasServer(), KviIrcUserEntry::hasUser(), KviIrcUserEntry::hops(), KviIrcUserEntry::host(), KviIrcUserEntry::isAway(), KviWindow::m_szName, KviIrcUserEntry::realName(), KviIrcUserEntry::server(), START_TABLE_BOLD_ROW, KviMircCntrl::stripControlBytes(), KviIrcUserEntry::user(), and KviIrcConnection::userDataBase().
Referenced by updateLabelText().
bool KviQuery::isDeadQuery () [inline]
Returns true if the query is dead.
Returns:
bool
References KVI_QUERY_FLAG_DEAD.
Referenced by myIconPtr().
QByteArray KviQuery::loadLogFile (const QString & szFileName, bool bGzip)
Loads a log file.
It opens a logfile, gzipped or not, and returns the content in a buffer
Parameters:
szFileName The filename of the log file
bGzip Whether the log file is gzipped
Returns:
QByteArray
References debug.
Referenced by pasteLastLog().
void KviQuery::loadProperties (KviConfig * cfg) [protected, virtual]
Loads the properties from file.
Parameters:
cfg The configuration file
Returns:
void
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, KviConfig::readBoolEntry(), KviConfig::readIntListEntry(), KviTalSplitter::setSizes(), and showListView().
void KviQuery::mergeQuery (KviQuery * q)
Merges a query into the one we're using.
Parameters:
q The source query
Returns:
void
References KviIrcView::appendMessagesFrom(), KviWindow::m_pIrcView, and updateLabelText().
Referenced by KviServerParser::parseLiteralNick().
QPixmap * KviQuery::myIconPtr () [protected, virtual]
Returns the icon associated to the query.
Returns:
QPixmap *
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), isDeadQuery(), KVI_SMALLICON_DEADQUERY, and KVI_SMALLICON_QUERY.
bool KviQuery::nickChange (const QString & szOldNick, const QString & szNewNick)
Called when the target changes the nick.
Parameters:
szOldNick The old nickname of the user
szNewNick The new nickname of the user
Returns:
bool
References m_pUserListView, KviUserListView::nickChange(), KviWindow::setWindowName(), KviWindow::updateCaption(), and updateLabelText().
Referenced by KviServerParser::parseLiteralNick().
void KviQuery::notifyCommonChannels (const QString & szNick, const QString & szUser, const QString & szHost, int iChans, const QString & szChans)
Notify us if we have common channels with the target.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
iChans The number of common channels
szChans The common channels
Returns:
void
References __tr2qs, KVI_OUT_QUERYTRACE, KviWindow::output(), and updateLabelText().
Referenced by KviServerParser::parseLiteralJoin(), KviServerParser::parseLiteralKick(), KviServerParser::parseLiteralNick(), KviServerParser::parseLiteralPart(), and setTarget().
void KviQuery::notifyTargetChange (const QString & szOldNick, const QString & szOldUser, const QString & szOldHost, const QString & szNick, const QString & szUser, const QString & szHost) [protected]
Called to notify us that the target of the query is changed.
Parameters:
szOldNick The old nickname of the target
szOldUser The old username of the target
szOldHost The old hostname of the target
szNewNick The new nickname of the target
szNewUser The new username of the target
szNewHost The new hostname of the target
Returns:
void
References __tr2qs, KVI_OUT_QUERYTRACE, KviWindow::output(), and updateLabelText().
Referenced by userAction().
void KviQuery::ownAction (const QString & szBuffer) [virtual]
Called when we perform an action.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), KviWindow::encodeText(), KVI_OPTION_BOOL, KVI_OUT_ACTION, KVI_OUT_SYSTEMWARNING, KVI_USERACTION_ACTION, KviEvent_OnMeAction, KviOption_boolStripMircColorsInUserMessages, KVS_TRIGGER_EVENT_2_HALTED, m_pUserListView, KviWindow::output(), KviWindow::outputNoFmt(), KviIrcConnection::sendFmtData(), KviMircCntrl::stripControlBytes(), KviUserListView::userAction(), and KviWindow::windowName().
void KviQuery::ownMessage (const QString & szBuffer) [virtual]
Called when we send a message to the query target.
Parameters:
szBuffer The buffer where to store the data
Returns:
void
Reimplemented from KviWindow.
References __tr2qs, KviWindow::connection(), d, KviWindow::decodeText(), KviWindow::encodeText(), KviIrcConnection::encodeText(), KviIrcConnectionUserInfo::hostName(), KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMWARNING, KVI_TEXT_CRYPTESCAPE, KVI_USERACTION_PRIVMSG, KviWindow::m_pConsole, KviWindow::makeEncoder(), KviIrcConnectionUserInfo::nickName(), KviConsole::NoNotifications, KviWindow::output(), KviWindow::outputNoFmt(), KviConsole::outputPrivmsg(), KviStr::ptr(), KviIrcConnection::sendFmtData(), userAction(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), and KviWindow::windowName().
void KviQuery::pasteLastLog ()
Pastes the most recent channel log into the buffer.
It searches for the most recent channel log of the channel we have just joined, and pastes into the buffer the last N lines, where N is get from the options
Returns:
void
References __tr2qs, KviWindow::console(), KviConsole::currentNetworkName(), g_pApp, KviApp::getLocalKvircDirectory(), KVI_OPTION_UINT, KVI_OUT_QUERYPRIVMSG, KviOption_uintDaysIntervalToPasteOnQueryJoin, KviOption_uintLinesToPasteOnQueryJoin, loadLogFile(), KviApp::Log, KviWindow::output(), and target().
Referenced by KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
void KviQuery::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, and KviWindow::m_pSplitter.
void KviQuery::saveProperties (KviConfig * cfg) [protected, virtual]
Saves the properties to file.
Parameters:
cfg The configuration file
Returns:
void
Reimplemented from KviWindow.
References KviWindow::m_pSplitter, m_pUserListView, KviTalSplitter::sizes(), and KviConfig::writeEntry().
int KviQuery::selectedCount () [inline]
Returns the number of selected users in the userlist.
Returns:
int
void KviQuery::setAliveQuery ()
Sets the status of the query as alive.
Returns:
void
References KviWindow::connection(), KviWindow::context(), KviIrcView::isLogging(), KVI_QUERY_FLAG_DEAD, KVI_WINDOW_TYPE_QUERY, m_iFlags, KviWindow::m_pIrcView, m_pUserListView, KviIrcConnection::registerQuery(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcView::startLogging(), KviIrcContext::unregisterDeadQuery(), KviWindow::updateCaption(), KviWindow::updateIcon(), and updateLabelText().
Referenced by KviIrcConnection::createQuery().
void KviQuery::setDeadQuery ()
Sets the status of the query as dead.
Returns:
void
References KviWindow::connection(), KviWindow::context(), KviUserListView::enableUpdates(), KVI_QUERY_FLAG_DEAD, KVI_WINDOW_TYPE_DEADQUERY, m_iFlags, m_pUserListView, KviUserListView::partAll(), KviIrcContext::registerDeadQuery(), KviWindow::setType(), KviUserListView::setUserDataBase(), KviIrcConnection::unregisterQuery(), KviWindow::updateCaption(), KviWindow::updateIcon(), and updateLabelText().
KviUserListEntry * KviQuery::setTarget (const QString & szNick, const QString & szUser, const QString & szHost)
Sets the target of the query.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
Returns:
KviUserListEntry *
References KviIrcUserEntry::avatar(), KviConsole::checkDefaultAvatar(), KviWindow::connection(), e, KviIrcConnection::getCommonChannels(), KviUserListEntry::globalData(), KviUserListView::join(), KVI_OPTION_BOOL, KviEvent_OnQueryTargetAdded, KviOption_boolEnableQueryTracing, KVS_TRIGGER_EVENT_3, KviWindow::m_pConsole, m_pUserListView, notifyCommonChannels(), KviWindow::setWindowName(), KviWindow::updateCaption(), and updateLabelText().
Referenced by KviIrcConnection::loginComplete(), KviServerParser::parseCtcpRequestAction(), KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
void KviQuery::showListView (bool bShow)
Shows the userlist view.
Parameters:
bShow Whether to show or hide the view
Returns:
void
References m_pListViewButton, and m_pUserListView.
Referenced by loadProperties(), and toggleListView().
QSize KviQuery::sizeHint () const [virtual]
Returns the size of the query object.
Returns:
QSize
References KviInput::heightHint(), KviWindow::m_pInput, KviWindow::m_pIrcView, KviWindow::m_pSplitter, and KviIrcView::sizeHint().
void KviQuery::slotDndEvents (const QString & pcFile) [protected, slot]
Triggers the OnQueryFileDropped event.
Parameters:
pcFile The file dropped in the query
Returns:
void
References KviEvent_OnQueryFileDropped, and KVS_TRIGGER_EVENT_1.
Referenced by KviQuery().
virtual const QString& KviQuery::target () [inline, virtual]
Returns the name of the query target.
Returns:
const QString &
Reimplemented from KviWindow.
References KviWindow::windowName().
Referenced by pasteLastLog().
void KviQuery::textViewRightClicked () [protected, slot]
Triggers the OnQueryPopupRequest event.
Returns:
void
References KviEvent_OnQueryPopupRequest, and KVS_TRIGGER_EVENT_0.
Referenced by KviQuery().
void KviQuery::toggleListView () [protected, slot]
Toggles the userlist view.
Returns:
void
References m_pUserListView, and showListView().
Referenced by KviQuery().
void KviQuery::triggerCreationEvents () [protected, virtual]
Trigger the OnQueryWindowCreated event.
Returns:
void
Reimplemented from KviWindow.
References KVI_OPTION_STRING, KviEvent_OnQueryWindowCreated, KviOption_stringOnNewQueryOpenedSound, KVS_TRIGGER_EVENT_0, and KviIrcUrl::run().
void KviQuery::updateLabelText ()
Updates the text of the tooltip.
Returns:
void
References KviTalToolTip::add(), getInfoLabelText(), getInfoLabelTipText(), and m_pLabel.
Referenced by applyOptions(), KviQuery(), mergeQuery(), nickChange(), notifyCommonChannels(), notifyTargetChange(), KviServerParser::parseLiteralJoin(), KviServerParser::parseNumericWhoisAway(), KviServerParser::parseNumericWhoisServer(), KviServerParser::parseNumericWhoisUser(), KviServerParser::parseNumericWhoReply(), setAliveQuery(), setDeadQuery(), setTarget(), and userAction().
void KviQuery::userAction (const QString & szNick, const QString & szUser, const QString & szHost, unsigned int uActionType)
Called when a user performs an action.
Parameters:
szNick The nickname of the user
szUser The username of the user
szHost The hostname of the user
uActionType The type of the action
Returns:
void
References kvi_getUserActionTemperature(), KVI_OPTION_BOOL, KviOption_boolEnableQueryTracing, m_pUserListView, notifyTargetChange(), updateLabelText(), KviUserListView::userAction(), and KviUserListView::userActionVerifyMask().
void KviQuery::userAction (const QString & szNick, unsigned int uActionType)
Called when a user performs an action.
Parameters:
szNick The nickname of the user
uActionType The type of the action
Returns:
void
References kvi_getUserActionTemperature(), m_pUserListView, updateLabelText(), and KviUserListView::userAction().
void KviQuery::userAction (KviIrcMask * user, unsigned int uActionType)
Called when a user performs an action.
Parameters:
user The source user
uActionType The type of the action
Returns:
void
References KviIrcMask::host(), kvi_getUserActionTemperature(), KVI_OPTION_BOOL, KviOption_boolEnableQueryTracing, m_pUserListView, KviIrcMask::nick(), notifyTargetChange(), updateLabelText(), KviIrcMask::user(), KviUserListView::userAction(), and KviUserListView::userActionVerifyMask().
Referenced by ownMessage(), KviServerParser::parseLiteralNick(), KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().
Member Data Documentation
int KviQuery::m_iFlags [protected]
Referenced by KviQuery(), setAliveQuery(), and setDeadQuery().
QFrame* KviQuery::m_pButtonGrid [protected]
Referenced by KviQuery().
KviThemedLabel* KviQuery::m_pLabel [protected]
Referenced by KviQuery(), and updateLabelText().
KviWindowToolPageButton* KviQuery::m_pListViewButton [protected]
Referenced by KviQuery(), and showListView().
KviUserListView* KviQuery::m_pUserListView [protected]
Referenced by applyOptions(), KviQuery(), nickChange(), ownAction(), saveProperties(), setAliveQuery(), setDeadQuery(), setTarget(), showListView(), toggleListView(), userAction(), and ~KviQuery().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_query.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_query.cpp