KVIrc: KviStringListSelector Class Reference
KviStringListSelector Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
virtual void commit ()
KviStringListSelector (QWidget *par, const QString &txt, QStringList *pOption, bool bEnabled)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviStringListSelector ()
Public Member Functions inherited from KviTalVBox
void addStretch (int iStretch)
Adds the stretch factor.
KviTalVBox (QWidget *pParent, char *pcName=0)
Constructs a vertical box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box for a child object.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpacing)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalVBox ()
Destroys a vertical box object.
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual ~KviSelectorInterface ()
Private Slots
void addClicked ()
void itemSelectionChanged ()
void removeClicked ()
void textChanged (const QString &str)
Private Attributes
QPushButton * m_pAddButton
QLabel * m_pLabel
QLineEdit * m_pLineEdit
KviTalListWidget * m_pListWidget
QStringList * m_pOption
QPushButton * m_pRemoveButton
Additional Inherited Members
Protected Member Functions inherited from KviTalVBox
virtual void childEvent (QChildEvent *e)
Constructor & Destructor Documentation
KviStringListSelector::KviStringListSelector (QWidget * par, const QString & txt, QStringList * pOption, bool bEnabled)
References __tr2qs, addClicked(), connect(), itemSelectionChanged(), m_pAddButton, m_pLabel, m_pLineEdit, m_pListWidget, m_pOption, m_pRemoveButton, removeClicked(), setEnabled(), KviTalVBox::setSpacing(), KviTalVBox::setStretchFactor(), and textChanged().
KviStringListSelector::~KviStringListSelector () default
Member Function Documentation
void KviStringListSelector::addClicked () private slot
References m_pLineEdit, and m_pListWidget.
Referenced by KviStringListSelector().
void KviStringListSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pListWidget, m_pOption, and u.
void KviStringListSelector::itemSelectionChanged () private slot
References m_pListWidget, and m_pRemoveButton.
Referenced by KviStringListSelector().
void KviStringListSelector::removeClicked () private slot
References m_pListWidget, and u.
Referenced by KviStringListSelector().
void KviStringListSelector::setEnabled (bool bEnabled) virtual slot
References m_pAddButton, m_pLabel, m_pLineEdit, m_pListWidget, and m_pRemoveButton.
Referenced by KviStringListSelector(), and OptionsWidget_antispam::reenableStuff().
void KviStringListSelector::textChanged (const QString & str) private slot
References m_pAddButton.
Referenced by KviStringListSelector().
QString KviStringListSelector::textForSearch () inline virtual
Reimplemented from KviSelectorInterface.
QWidget* KviStringListSelector::widgetToHighlight () inline virtual
Reimplemented from KviSelectorInterface.
Member Data Documentation
QPushButton* KviStringListSelector::m_pAddButton private
Referenced by KviStringListSelector(), setEnabled(), and textChanged().
QLabel* KviStringListSelector::m_pLabel private
Referenced by KviStringListSelector(), and setEnabled().
QLineEdit* KviStringListSelector::m_pLineEdit private
Referenced by addClicked(), KviStringListSelector(), and setEnabled().
KviTalListWidget* KviStringListSelector::m_pListWidget private
Referenced by addClicked(), commit(), itemSelectionChanged(), KviStringListSelector(), removeClicked(), and setEnabled().
QStringList* KviStringListSelector::m_pOption private
Referenced by commit(), and KviStringListSelector().
QPushButton* KviStringListSelector::m_pRemoveButton private
Referenced by itemSelectionChanged(), KviStringListSelector(), and setEnabled().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp