KVIrc: KviHttpRequest Class Reference
KviHttpRequest Class Reference
#include <KviHttpRequest.h>
Public Types
enum ExistingFileAction { Overwrite, RenameIncoming, RenameExisting, Resume }
enum ProcessingType {
HeadersOnly, WholeFile, Blocks, Lines,
StoreToFile
}
Signals
void binaryData (const KviDataBuffer &data)
void connectionEstablished ()
void contactingHost (const QString &ipandport)
void data (const KviCString &data)
void header (KviPointerHashTable< const char *, KviCString > *hdr)
void receivedResponse (const QString &response)
void requestSent (const QStringList &request)
void resolvingHost (const QString &hostname)
void status (const QString &message)
void terminated (bool bSuccess)
Public Member Functions
void abort ()
unsigned int contentOffset ()
ExistingFileAction existingFileAction ()
const QString & fileName ()
bool followRedirects () const
bool get (const KviUrl &u, ProcessingType p=WholeFile, const QString &szFileName=QString())
KviHttpRequest ()
const QString & lastError ()
unsigned int maxContentLength ()
void * privateData ()
ProcessingType processingType ()
unsigned int receivedSize ()
void reset ()
void setConnectionTimeout (unsigned int uConnectionTimeout)
void setContentOffset (int uContentOffset)
void setExistingFileAction (ExistingFileAction a)
void setFileName (const QString &szFileName)
void setFollowRedirects (bool bFollow)
void setMaxContentLength (int uMaxContentLength)
void setMaximumRedirectCount (unsigned int uCount)
void setPostData (const QString &szPostData)
void setPrivateData (void *ptr)
void setProcessingType (ProcessingType t)
void setUrl (const KviUrl &u)
bool start ()
unsigned int totalSize ()
const KviUrl & url ()
virtual ~KviHttpRequest ()
Protected Attributes
bool m_bChunkedTransferEncoding
bool m_bFollowRedirects
bool m_bGzip
bool m_bHeaderProcessed
bool m_bIgnoreRemainingData
KviUrl m_connectionUrl
ExistingFileAction m_eExistingFileAction
ProcessingType m_eProcessingType
void * m_pPrivateData
QString m_szFileName
QString m_szLastError
QString m_szPostData
unsigned int m_uConnectionTimeout
unsigned int m_uContentOffset
unsigned int m_uMaxContentLength
unsigned int m_uMaximumRedirectCount
unsigned int m_uReceivedSize
unsigned int m_uRedirectCount
unsigned int m_uRemainingChunkSize
KviUrl m_url
unsigned int m_uTotalSize
Private Slots
void slotConnectionTimedOut ()
void slotSocketConnected ()
void slotSocketDisconnected ()
void slotSocketError (QAbstractSocket::SocketError socketError)
void slotSocketHostResolved ()
void slotSocketReadDataReady ()
Private Member Functions
void closeSocket ()
bool doConnect ()
void emitLines (KviDataBuffer *pDataBuffer)
bool openFile ()
void processData (KviDataBuffer *data)
bool processHeader (KviCString &szHeader)
void resetData ()
void resetInternalStatus ()
void resetStatus ()
Private Attributes
KviHttpRequestPrivate * m_p
Member Enumeration Documentation
enum KviHttpRequest::ExistingFileAction
Enumerator
Overwrite
RenameIncoming
RenameExisting
Resume
enum KviHttpRequest::ProcessingType
Enumerator
HeadersOnly
WholeFile
Blocks
Lines
StoreToFile
Constructor & Destructor Documentation
KviHttpRequest::KviHttpRequest ()
References KviHttpRequestPrivate::bIsSSL, m_bFollowRedirects, m_bHeaderProcessed, m_p, m_pPrivateData, m_uConnectionTimeout, m_uMaximumRedirectCount, m_uRedirectCount, KviHttpRequestPrivate::pBuffer, KviHttpRequestPrivate::pConnectTimeoutTimer, KviHttpRequestPrivate::pFile, KviHttpRequestPrivate::pSocket, resetData(), and resetStatus().
KviHttpRequest::~KviHttpRequest () virtual
References KVI_ASSERT, m_p, KviHttpRequestPrivate::pBuffer, KviHttpRequestPrivate::pFile, KviHttpRequestPrivate::pSocket, and resetInternalStatus().
Member Function Documentation
void KviHttpRequest::abort ()
References __tr2qs, m_szLastError, resetInternalStatus(), and terminated().
Referenced by HttpFileTransfer::abort().
void KviHttpRequest::binaryData (const KviDataBuffer & data) signal
Referenced by processData(), and slotSocketDisconnected().
void KviHttpRequest::closeSocket () private
References m_p, KviHttpRequestPrivate::pSocket, slotSocketConnected(), slotSocketDisconnected(), and slotSocketError().
Referenced by doConnect(), and resetInternalStatus().
void KviHttpRequest::connectionEstablished () signal
Referenced by slotSocketConnected().
void KviHttpRequest::contactingHost (const QString & ipandport) signal
Referenced by slotSocketHostResolved().
unsigned int KviHttpRequest::contentOffset () inline
void KviHttpRequest::data (const KviCString & data) signal
Referenced by emitLines(), and slotSocketDisconnected().
bool KviHttpRequest::doConnect () private
References KviHttpRequestPrivate::bIsSSL, closeSocket(), connect(), KviUrl::host(), m_connectionUrl, m_p, m_uConnectionTimeout, KviHttpRequestPrivate::pConnectTimeoutTimer, KviUrl::port(), KviHttpRequestPrivate::pSocket, resolvingHost(), slotConnectionTimedOut(), slotSocketConnected(), slotSocketDisconnected(), slotSocketError(), slotSocketHostResolved(), slotSocketReadDataReady(), and KviHttpRequestPrivate::uPort.
Referenced by start().
void KviHttpRequest::emitLines (KviDataBuffer * pDataBuffer) private
References KviDataBuffer::data(), data(), KviDataBuffer::find(), m_p, KviHttpRequestPrivate::pBuffer, KviDataBuffer::remove(), and KviCString::stripRight().
Referenced by processData().
ExistingFileAction KviHttpRequest::existingFileAction () inline
const QString& KviHttpRequest::fileName () inline
Referenced by HttpFileTransfer::displayPaint(), HttpFileTransfer::localFileName(), and HttpFileTransfer::transferTerminated().
bool KviHttpRequest::followRedirects () const inline
bool KviHttpRequest::get (const KviUrl & u, ProcessingType p = WholeFile, const QString & szFileName = QString())
References reset(), setFileName(), setProcessingType(), setUrl(), and start().
Referenced by KviStatusBarUpdateIndicator::checkVersion(), KviRemoteMircServerImportWizard::start(), and AvatarDownloadDialog::startDownload().
void KviHttpRequest::header (KviPointerHashTable< const char *, KviCString > * hdr) signal
Referenced by processHeader().
const QString& KviHttpRequest::lastError () inline
Referenced by AvatarDownloadDialog::downloadTerminated(), KviRemoteMircServerImportWizard::getListTerminated(), http_kvs_complete_get(), and HttpFileTransfer::transferTerminated().
unsigned int KviHttpRequest::maxContentLength () inline
bool KviHttpRequest::openFile () private
References __tr2qs, d, i, m_eExistingFileAction, m_eProcessingType, m_p, m_szFileName, m_szLastError, Overwrite, KviHttpRequestPrivate::pFile, RenameExisting, RenameIncoming, resetInternalStatus(), Resume, StoreToFile, and terminated().
Referenced by processData().
void* KviHttpRequest::privateData () inline
void KviHttpRequest::processData (KviDataBuffer * data) private
References __tr2qs, KviDataBuffer::append(), binaryData(), Blocks, KviDataBuffer::clear(), KviCString::cutFromFirst(), KviDataBuffer::data(), emitLines(), KviDataBuffer::find(), Lines, m_bChunkedTransferEncoding, m_bHeaderProcessed, m_bIgnoreRemainingData, m_eProcessingType, m_p, m_szLastError, m_uMaxContentLength, m_uReceivedSize, m_uRemainingChunkSize, m_uTotalSize, openFile(), KviHttpRequestPrivate::pBuffer, KviHttpRequestPrivate::pFile, processHeader(), KviCString::ptr(), KviDataBuffer::remove(), resetInternalStatus(), KviDataBuffer::size(), StoreToFile, and terminated().
Referenced by slotSocketReadDataReady().
bool KviHttpRequest::processHeader (KviCString & szHeader) private
References __tr2qs, KviPointerList< T >::append(), KviCString::cutLeft(), KviCString::cutToFirst(), KviCString::equalsCI(), KviPointerHashTable< Key, T >::find(), KviCString::findFirstIdx(), KviPointerList< T >::first(), KviCString::hasData(), header(), HeadersOnly, kvi_strEqualCI(), kvi_strEqualCSN(), KviCString::left(), m_bChunkedTransferEncoding, m_bFollowRedirects, m_bGzip, m_connectionUrl, m_eProcessingType, m_szLastError, m_uMaxContentLength, m_uMaximumRedirectCount, m_uRedirectCount, m_uRemainingChunkSize, m_url, m_uTotalSize, KviPointerList< T >::next(), KviCString::ptr(), receivedResponse(), KviPointerHashTable< Key, T >::replace(), resetInternalStatus(), s, KviPointerHashTable< Key, T >::setAutoDelete(), KviPointerList< T >::setAutoDelete(), start(), status(), szR, terminated(), KviCString::toUInt(), KviCString::trim(), KviUrl::url(), and url().
Referenced by processData().
ProcessingType KviHttpRequest::processingType () inline
void KviHttpRequest::receivedResponse (const QString & response) signal
Referenced by processHeader().
unsigned int KviHttpRequest::receivedSize () inline
Referenced by HttpFileTransfer::displayPaint().
void KviHttpRequest::requestSent (const QStringList & request) signal
Referenced by slotSocketConnected().
void KviHttpRequest::reset ()
References resetData(), resetInternalStatus(), and resetStatus().
Referenced by get().
void KviHttpRequest::resetData () private
References m_bChunkedTransferEncoding, m_bGzip, m_bIgnoreRemainingData, m_connectionUrl, m_eExistingFileAction, m_eProcessingType, m_szFileName, m_uContentOffset, m_uMaxContentLength, m_uRedirectCount, m_uRemainingChunkSize, m_url, RenameIncoming, and WholeFile.
Referenced by KviHttpRequest(), and reset().
void KviHttpRequest::resetInternalStatus () private
References KviDataBuffer::clear(), closeSocket(), m_bHeaderProcessed, m_p, KviHttpRequestPrivate::pBuffer, KviHttpRequestPrivate::pConnectTimeoutTimer, KviHttpRequestPrivate::pFile, and KviHttpRequestPrivate::pSocket.
Referenced by abort(), openFile(), processData(), processHeader(), reset(), slotConnectionTimedOut(), slotSocketConnected(), slotSocketDisconnected(), slotSocketError(), start(), and ~KviHttpRequest().
void KviHttpRequest::resetStatus () private
References __tr2qs, m_szLastError, m_uReceivedSize, and m_uTotalSize.
Referenced by KviHttpRequest(), reset(), and start().
void KviHttpRequest::resolvingHost (const QString & hostname) signal
Referenced by doConnect().
void KviHttpRequest::setConnectionTimeout (unsigned int uConnectionTimeout) inline
Referenced by http_kvs_complete_get().
void KviHttpRequest::setContentOffset (int uContentOffset) inline
Referenced by http_kvs_complete_get().
void KviHttpRequest::setExistingFileAction (ExistingFileAction a) inline
References a.
Referenced by http_kvs_complete_get(), and AvatarDownloadDialog::startDownload().
void KviHttpRequest::setFileName (const QString & szFileName) inline
Referenced by get(), and http_kvs_complete_get().
void KviHttpRequest::setFollowRedirects (bool bFollow) inline
void KviHttpRequest::setMaxContentLength (int uMaxContentLength) inline
Referenced by http_kvs_complete_get().
void KviHttpRequest::setMaximumRedirectCount (unsigned int uCount) inline
void KviHttpRequest::setPostData (const QString & szPostData) inline
Referenced by http_kvs_complete_get().
void KviHttpRequest::setPrivateData (void * ptr) inline
void KviHttpRequest::setProcessingType (ProcessingType t) inline
References t().
Referenced by get(), and http_kvs_complete_get().
void KviHttpRequest::setUrl (const KviUrl & u) inline
References u.
Referenced by get(), and http_kvs_complete_get().
void KviHttpRequest::slotConnectionTimedOut () private slot
References __tr2qs, m_szLastError, resetInternalStatus(), and terminated().
Referenced by doConnect().
void KviHttpRequest::slotSocketConnected () private slot
References __tr2qs, KviCString::append(), connectionEstablished(), KviCString::Format, HeadersOnly, KviUrl::host(), m_connectionUrl, m_eProcessingType, m_p, m_szLastError, m_szPostData, m_uContentOffset, KviUrl::path(), KviHttpRequestPrivate::pConnectTimeoutTimer, KviHttpRequestPrivate::pSocket, KviCString::ptr(), requestSent(), resetInternalStatus(), status(), and terminated().
Referenced by closeSocket(), and doConnect().
void KviHttpRequest::slotSocketDisconnected () private slot
References __tr2qs, binaryData(), Blocks, KviDataBuffer::data(), data(), Lines, m_eProcessingType, m_p, m_szLastError, KviHttpRequestPrivate::pBuffer, KviHttpRequestPrivate::pFile, resetInternalStatus(), KviDataBuffer::size(), StoreToFile, terminated(), and WholeFile.
Referenced by closeSocket(), doConnect(), slotSocketError(), and slotSocketReadDataReady().
void KviHttpRequest::slotSocketError (QAbstractSocket::SocketError socketError) private slot
References KVI_ASSERT, m_p, m_szLastError, KviHttpRequestPrivate::pSocket, resetInternalStatus(), slotSocketDisconnected(), and terminated().
Referenced by closeSocket(), and doConnect().
void KviHttpRequest::slotSocketHostResolved () private slot
References __tr2qs, contactingHost(), KviUrl::host(), m_connectionUrl, m_p, status(), and KviHttpRequestPrivate::uPort.
Referenced by doConnect().
void KviHttpRequest::slotSocketReadDataReady () private slot
References KviDataBuffer::data(), KVI_ASSERT, m_p, processData(), KviHttpRequestPrivate::pSocket, KviDataBuffer::resize(), and slotSocketDisconnected().
Referenced by doConnect().
bool KviHttpRequest::start ()
References __tr2qs, KviHttpRequestPrivate::bIsSSL, doConnect(), KviQString::equalCI(), KviUrl::host(), m_connectionUrl, m_eExistingFileAction, m_eProcessingType, m_p, m_szFileName, m_szLastError, m_uContentOffset, KviUrl::protocol(), resetInternalStatus(), resetStatus(), Resume, and StoreToFile.
Referenced by get(), processHeader(), and HttpFileTransfer::startDownload().
void KviHttpRequest::status (const QString & message) signal
Referenced by processHeader(), slotSocketConnected(), and slotSocketHostResolved().
void KviHttpRequest::terminated (bool bSuccess) signal
Referenced by abort(), openFile(), processData(), processHeader(), slotConnectionTimedOut(), slotSocketConnected(), slotSocketDisconnected(), and slotSocketError().
unsigned int KviHttpRequest::totalSize () inline
Referenced by HttpFileTransfer::displayPaint().
const KviUrl& KviHttpRequest::url () inline
Referenced by HttpFileTransfer::displayPaint(), processHeader(), and HttpFileTransfer::transferTerminated().
Member Data Documentation
bool KviHttpRequest::m_bChunkedTransferEncoding protected
Referenced by processData(), processHeader(), and resetData().
bool KviHttpRequest::m_bFollowRedirects protected
Referenced by KviHttpRequest(), and processHeader().
bool KviHttpRequest::m_bGzip protected
Referenced by processHeader(), and resetData().
bool KviHttpRequest::m_bHeaderProcessed protected
Referenced by KviHttpRequest(), processData(), and resetInternalStatus().
bool KviHttpRequest::m_bIgnoreRemainingData protected
Referenced by processData(), and resetData().
KviUrl KviHttpRequest::m_connectionUrl protected
Referenced by doConnect(), processHeader(), resetData(), slotSocketConnected(), slotSocketHostResolved(), and start().
ExistingFileAction KviHttpRequest::m_eExistingFileAction protected
Referenced by openFile(), resetData(), and start().
ProcessingType KviHttpRequest::m_eProcessingType protected
Referenced by openFile(), processData(), processHeader(), resetData(), slotSocketConnected(), slotSocketDisconnected(), and start().
KviHttpRequestPrivate* KviHttpRequest::m_p private
Referenced by closeSocket(), doConnect(), emitLines(), KviHttpRequest(), openFile(), processData(), resetInternalStatus(), slotSocketConnected(), slotSocketDisconnected(), slotSocketError(), slotSocketHostResolved(), slotSocketReadDataReady(), start(), and ~KviHttpRequest().
void* KviHttpRequest::m_pPrivateData protected
Referenced by KviHttpRequest().
QString KviHttpRequest::m_szFileName protected
Referenced by openFile(), resetData(), and start().
QString KviHttpRequest::m_szLastError protected
Referenced by abort(), openFile(), processData(), processHeader(), resetStatus(), slotConnectionTimedOut(), slotSocketConnected(), slotSocketDisconnected(), slotSocketError(), and start().
QString KviHttpRequest::m_szPostData protected
Referenced by slotSocketConnected().
unsigned int KviHttpRequest::m_uConnectionTimeout protected
Referenced by doConnect(), and KviHttpRequest().
unsigned int KviHttpRequest::m_uContentOffset protected
Referenced by resetData(), slotSocketConnected(), and start().
unsigned int KviHttpRequest::m_uMaxContentLength protected
Referenced by processData(), processHeader(), and resetData().
unsigned int KviHttpRequest::m_uMaximumRedirectCount protected
Referenced by KviHttpRequest(), and processHeader().
unsigned int KviHttpRequest::m_uReceivedSize protected
Referenced by processData(), and resetStatus().
unsigned int KviHttpRequest::m_uRedirectCount protected
Referenced by KviHttpRequest(), processHeader(), and resetData().
unsigned int KviHttpRequest::m_uRemainingChunkSize protected
Referenced by processData(), processHeader(), and resetData().
KviUrl KviHttpRequest::m_url protected
Referenced by processHeader(), and resetData().
unsigned int KviHttpRequest::m_uTotalSize protected
Referenced by processData(), processHeader(), and resetStatus().
The documentation for this class was generated from the following files:
src/kvilib/net/KviHttpRequest.h
src/kvilib/net/KviHttpRequest.cpp