KVIrc: KviKvsModuleCallbackCommandCall Class Reference
KviKvsModuleCallbackCommandCall Class Reference
#include <KviKvsModuleInterface.h>
Public Member Functions
const KviKvsScript * callback ()
virtual bool getParameterCode (unsigned int uParamIdx, QString &szParamBuffer)
KviKvsModuleCallbackCommandCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams, KviKvsSwitchList *pSwitches, const KviKvsScript *pCallback, KviKvsTreeNodeDataList *pDataList)
~KviKvsModuleCallbackCommandCall ()
Public Member Functions inherited from KviKvsModuleCommandCall
KviKvsVariant * getSwitch (unsigned short u, const QString &szSwitch)
bool hasSwitch (unsigned short u, const QString &szSwitch)
KviKvsModuleCommandCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams, KviKvsSwitchList *pSwitches)
KviKvsSwitchList * switches ()
KviKvsSwitchList * switchList ()
~KviKvsModuleCommandCall ()
Public Member Functions inherited from KviKvsModuleRunTimeCall
KviKvsModuleRunTimeCall (KviModule *pModule, KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
KviModule * module ()
~KviKvsModuleRunTimeCall ()
Public Member Functions inherited from KviKvsRunTimeCall
KviKvsRunTimeContext * context ()
void enterBlockingSection ()
bool error (QString szFmt,...)
KviKvsVariant * firstParam ()
KviKvsRunTimeCall (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool leaveBlockingSection ()
KviKvsVariant * nextParam ()
unsigned int paramCount ()
unsigned int parameterCount ()
KviKvsVariantList * parameterList ()
KviKvsVariantList * params ()
void warning (QString szFmt,...)
KviWindow * window ()
virtual ~KviKvsRunTimeCall ()
Protected Attributes
const KviKvsScript * m_pCallback
KviKvsTreeNodeDataList * m_pParameterDataList
Protected Attributes inherited from KviKvsModuleCommandCall
KviKvsSwitchList * m_pSwitchList
Protected Attributes inherited from KviKvsModuleRunTimeCall
KviModule * m_pModule
Protected Attributes inherited from KviKvsRunTimeCall
KviKvsRunTimeContext * m_pContext
KviKvsVariantList * m_pParams
Constructor & Destructor Documentation
KviKvsModuleCallbackCommandCall::KviKvsModuleCallbackCommandCall (KviModule * pModule, KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams, KviKvsSwitchList * pSwitches, const KviKvsScript * pCallback, KviKvsTreeNodeDataList * pDataList) inline
KviKvsModuleCallbackCommandCall::~KviKvsModuleCallbackCommandCall () inline
Member Function Documentation
const KviKvsScript* KviKvsModuleCallbackCommandCall::callback () inline
Referenced by action_kvs_cmd_create(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), dialog_kvs_cmd_file(), dialog_kvs_cmd_image(), dialog_kvs_cmd_message(), dialog_kvs_cmd_textinput(), http_kvs_cmd_asyncGet(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addItem(), and popup_kvs_cmd_addPrologue().
bool KviKvsModuleCallbackCommandCall::getParameterCode (unsigned int uParamIdx, QString & szParamBuffer) virtual
Reimplemented from KviKvsRunTimeCall.
References d, KviKvsTreeNodeData::endingLocation(), KviKvsTreeNodeDataList::item(), KviKvsTreeNode::location(), and m_pParameterDataList.
Referenced by action_kvs_cmd_create(), and addon_kvs_cmd_register().
Member Data Documentation
const KviKvsScript* KviKvsModuleCallbackCommandCall::m_pCallback protected
KviKvsTreeNodeDataList* KviKvsModuleCallbackCommandCall::m_pParameterDataList protected
Referenced by getParameterCode().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsModuleInterface.h
src/kvirc/kvs/KviKvsModuleInterface.cpp