KVIrc: KviKvsTreeNodeSpecialCommandSwitchLabelDefault Class Reference
KviKvsTreeNodeSpecialCommandSwitchLabelDefault Class Reference
#include <kvi_kvs_treenode_specialcommandswitch.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool execute (KviKvsRunTimeContext *c, KviKvsVariant *pRealParameter)
KviKvsTreeNodeSpecialCommandSwitchLabelDefault (const QChar *pLocation)
~KviKvsTreeNodeSpecialCommandSwitchLabelDefault ()
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandSwitchLabelDefault::KviKvsTreeNodeSpecialCommandSwitchLabelDefault (const QChar * pLocation)
KviKvsTreeNodeSpecialCommandSwitchLabelDefault::~KviKvsTreeNodeSpecialCommandSwitchLabelDefault ()
Member Function Documentation
void KviKvsTreeNodeSpecialCommandSwitchLabelDefault::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeSpecialCommandSwitchLabelDefault::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
References KviKvsTreeNodeInstruction::dump(), and KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction.
bool KviKvsTreeNodeSpecialCommandSwitchLabelDefault::execute (KviKvsRunTimeContext * c, KviKvsVariant * pRealParameter) [virtual]
Implements KviKvsTreeNodeSpecialCommandSwitchLabel.
References KviKvsTreeNodeInstruction::execute(), KviKvsTreeNodeSpecialCommandSwitchLabel::m_bHasTerminatingBreak, KviKvsTreeNodeSpecialCommandSwitchLabel::m_pInstruction, and KviKvsRunTimeContext::setBreakPending().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_treenode_specialcommandswitch.h
src/kvirc/kvs/kvi_kvs_treenode_specialcommandswitch.cpp