KVIrc: KviKvsTreeNodeExpressionUnaryOperatorLogicalNot Class Reference
KviKvsTreeNodeExpressionUnaryOperatorLogicalNot Class Reference
#include <KviKvsTreeNodeExpression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
KviKvsTreeNodeExpressionUnaryOperatorLogicalNot (const QChar *pLocation, KviKvsTreeNodeExpression *pData)
virtual int precedence ()
~KviKvsTreeNodeExpressionUnaryOperatorLogicalNot ()
Public Member Functions inherited from KviKvsTreeNodeExpressionUnaryOperator
bool evaluateOperand (KviKvsRunTimeContext *c)
KviKvsTreeNodeExpressionUnaryOperator (const QChar *pLocation, KviKvsTreeNodeExpression *pData)
~KviKvsTreeNodeExpressionUnaryOperator ()
Public Member Functions inherited from KviKvsTreeNodeExpressionOperator
KviKvsTreeNodeExpressionOperator (const QChar *pLocation)
~KviKvsTreeNodeExpressionOperator ()
Public Member Functions inherited from KviKvsTreeNodeExpression
virtual int firstBinaryOperator ()
KviKvsTreeNodeExpression (const QChar *pLocation)
virtual KviKvsTreeNodeExpression * left ()
KviKvsTreeNodeExpression * parentExpression ()
virtual KviKvsTreeNodeExpression * parentWithPrecedenceLowerThan (int iPrec)
virtual KviKvsTreeNodeExpression * right ()
virtual void setLeft (KviKvsTreeNodeExpression *pLeft)
void setParentExpression (KviKvsTreeNodeExpression *pParent)
virtual void setRight (KviKvsTreeNodeExpression *pRight)
~KviKvsTreeNodeExpression ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Attributes inherited from KviKvsTreeNodeExpressionUnaryOperator
KviKvsNumber m_nData
KviKvsTreeNodeExpression * m_pData
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::KviKvsTreeNodeExpressionUnaryOperatorLogicalNot (const QChar * pLocation, KviKvsTreeNodeExpression * pData)
KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::~KviKvsTreeNodeExpressionUnaryOperatorLogicalNot ()
Member Function Documentation
void KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeExpressionUnaryOperator.
void KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeExpressionUnaryOperator.
References KviKvsTreeNodeExpression::dump(), and KviKvsTreeNodeExpressionUnaryOperator::m_pData.
bool KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariant::asBoolean(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperator::m_pData, KviKvsVariant::setBoolean(), and v.
int KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::precedence () virtual
Reimplemented from KviKvsTreeNodeExpression.
References PREC_OP_LOGICALNOT.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.h
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.cpp