KVIrc: KviTalFileDialog Class Reference
KviTalFileDialog Class Reference
Toolkit Abstraction Layer: filedialog class.
#include <KviTalFileDialog.h>
Public Types
enum FileMode {
AnyFile, ExistingFile, ExistingFiles, Directory,
DirectoryOnly
}
Indicate what the user may select in the file dialog.
Public Member Functions
KviTalFileDialog (const QString &szDirName, const QString &szFilter=QString(), QWidget *pParent=0, const char *pcName=0, bool bModal=false)
Constructs the filedialog object.
void setDirectory (const QString &szDirectory)
Sets the current directory.
void setFileMode (FileMode m)
Sets the file mode.
~KviTalFileDialog ()
Destroys the filedialog object.
Static Public Member Functions
static QString getExistingDirectoryPath (const QString &szDir=QString(), const QString &szCaption=QString(), QWidget *pParent=0)
Returns an existing directory selected by the user.
Detailed Description
Toolkit Abstraction Layer: filedialog class.
Member Enumeration Documentation
enum KviTalFileDialog::FileMode
Indicate what the user may select in the file dialog.
Enumerator:
AnyFile
The name of a file, whether it exists or not
ExistingFile
The name of a single existing file
ExistingFiles
The names of zero or more existing files
Directory
The name of a directory. Both files and directories are displayed
DirectoryOnly
The name of a directory. The file dialog will only display directories
Constructor & Destructor Documentation
KviTalFileDialog::KviTalFileDialog (const QString & szDirName, const QString & szFilter = QString(), QWidget * pParent = 0, const char * pcName = 0, bool bModal = false)
Constructs the filedialog object.
Parameters:
szDirName The initial directory to display
szFilter The filter to use to display
pParent The parent object
pcName The caption name of the dialog
bModal Whether the dialog is modal
Returns:
KviTalFileDialog
KviTalFileDialog::~KviTalFileDialog ()
Destroys the filedialog object.
Member Function Documentation
static QString KviTalFileDialog::getExistingDirectoryPath (const QString & szDir = QString(), const QString & szCaption = QString(), QWidget * pParent = 0) [inline, static]
Returns an existing directory selected by the user.
Parameters:
szDir The directory to display
szCaption The caption of the dialog
pParent The parent object
Returns:
QString
Referenced by SetupWizard::chooseDataPath(), SetupWizard::chooseIncomingPath(), and SetupWizard::chooseOldDataPath().
void KviTalFileDialog::setDirectory (const QString & szDirectory)
Sets the current directory.
Parameters:
szDirectory The directory
Returns:
void
void KviTalFileDialog::setFileMode (FileMode m)
Sets the file mode.
Parameters:
m The mode :)
Returns:
void
References AnyFile, Directory, DirectoryOnly, ExistingFile, and ExistingFiles.
Referenced by KviFileDialog::askForDirectoryName(), KviFileDialog::askForOpenFileName(), KviFileDialog::askForOpenFileNames(), KviFileDialog::askForSaveFileName(), and dialog_kvs_cmd_file().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalFileDialog.h
src/kvilib/tal/KviTalFileDialog.cpp