KVIrc: OptionsWidget_ircGeneral Class Reference
OptionsWidget_ircGeneral Class Reference
#include <OptionsWidget_irc.h>
Public Member Functions
OptionsWidget_ircGeneral (QWidget *parent)
~OptionsWidget_ircGeneral ()
Constructor & Destructor Documentation
OptionsWidget_ircGeneral::OptionsWidget_ircGeneral (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::createLayout(), KviOption_boolMinimizeConsoleAfterConnect, KviOption_boolShowNetworkNameForConsoleWindowListEntry, and KviOptionsWidget::mergeTip().
OptionsWidget_ircGeneral::~OptionsWidget_ircGeneral ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_irc.h
src/modules/options/OptionsWidget_irc.cpp