KVIrc: KviKvsTreeNodeCommandWithParameters Class Reference
KviKvsTreeNodeCommandWithParameters Class Reference
#include <KviKvsTreeNodeCommandWithParameters.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
void dumpParameterList (const char *prefix)
KviKvsTreeNodeCommandWithParameters (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
KviKvsTreeNodeDataList * params ()
~KviKvsTreeNodeCommandWithParameters ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
virtual bool execute (KviKvsRunTimeContext *c)=0
This is the main entry point to the tree visit.
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
KviKvsTreeNodeDataList * m_pParams
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeCommandWithParameters::KviKvsTreeNodeCommandWithParameters (const QChar * pLocation, const QString & szCmdName, KviKvsTreeNodeDataList * params)
References m_pParams, params(), and KviKvsTreeNode::setParent().
KviKvsTreeNodeCommandWithParameters::~KviKvsTreeNodeCommandWithParameters ()
References m_pParams.
Member Function Documentation
void KviKvsTreeNodeCommandWithParameters::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeCommand.
Reimplemented in KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeCallbackCommand, KviKvsTreeNodeModuleSimpleCommand, and KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommand::m_szCmdName.
void KviKvsTreeNodeCommandWithParameters::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeCommand.
Reimplemented in KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeCallbackCommand, KviKvsTreeNodeModuleSimpleCommand, and KviKvsTreeNodeSimpleCommand.
References dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), and KviKvsTreeNodeCommand::m_szCmdName.
void KviKvsTreeNodeCommandWithParameters::dumpParameterList (const char * prefix)
References KviKvsTreeNodeDataList::dump(), and m_pParams.
Referenced by KviKvsTreeNodeSimpleCommand::dump(), KviKvsTreeNodeCallbackCommand::dump(), KviKvsTreeNodeModuleSimpleCommand::dump(), KviKvsTreeNodeCoreSimpleCommand::dump(), KviKvsTreeNodeModuleCallbackCommand::dump(), dump(), KviKvsTreeNodeCoreCallbackCommand::dump(), and KviKvsTreeNodeAliasSimpleCommand::dump().
KviKvsTreeNodeDataList* KviKvsTreeNodeCommandWithParameters::params () inline
Referenced by KviKvsTreeNodeCommandWithParameters().
Member Data Documentation
KviKvsTreeNodeDataList* KviKvsTreeNodeCommandWithParameters::m_pParams protected
Referenced by dumpParameterList(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeCoreSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeCoreCallbackCommand::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsTreeNodeCommandWithParameters(), and ~KviKvsTreeNodeCommandWithParameters().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeCommandWithParameters.h
src/kvirc/kvs/tree/KviKvsTreeNodeCommandWithParameters.cpp