KVIrc: KviStatusBar Class Reference
KviStatusBar Class Reference
Status Bar class.
#include <kvi_statusbar.h>
Public Member Functions
KviStatusBarApplet * appletAt (const QPoint &pnt, bool bBestMatch=false)
Returns the applet at the given point.
bool appletExists (KviStatusBarApplet *pApplet)
Returns true if the applet exists, false otherwise.
KviFrame * frame ()
Returns the frame pointer.
int insertPermanentWidgetAtTheEnd (QWidget *widget, int stretch=0)
Inserts an applet at the end of the statusbar as a permanent widget and returns its index.
KviStatusBar (KviFrame *pFrame)
Constructs the statusbar object.
void queueMessage (KviStatusBarMessage *pMsg)
Queue a statusbar message in the stack.
void registerAppletDescriptor (KviStatusBarAppletDescriptor *d)
Registers the applet descriptor.
~KviStatusBar ()
Destroys the statusbar object.
Protected Slots
void appletsPopupAboutToShow ()
Shows the per-applet popup menu.
void appletsPopupActivated (int iId)
Called when the user activates the per-applet popup.
void contextMenuRequested (const QPoint &pos)
Called when the user requests a context menu.
void contextPopupAboutToShow ()
Shows the applet common popup menu.
void messageTimerFired ()
Called when the timer timeouts.
void removeClickedApplet ()
Called when the user removes an applet from the statusbar.
void setPermanentMessage ()
Sets the permanent message to be shown.
Protected Member Functions
KviStatusBarApplet * createApplet (const QString &szInternalName)
Create an applet.
void dragEnterEvent (QDragEnterEvent *event)
void dragMoveEvent (QDragMoveEvent *de)
void dropEvent (QDropEvent *de)
virtual bool event (QEvent *e)
void load ()
Saves the statusbar stack.
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
void recalcMinimumHeight ()
Recalculates the minimum height of the status bar.
void registerApplet (KviStatusBarApplet *pApplet)
Registers the given applet in the statusbar.
void save ()
Saves the statusbar stack.
void showFirstMessageInQueue ()
Shows the first message in the queue stack.
void showLayoutHelp ()
Shows the common help for every applet.
void tipRequest (QHelpEvent *e)
Shows the right tooltip.
void unregisterApplet (KviStatusBarApplet *pApplet)
Unegisters the given applet in the statusbar.
Protected Attributes
bool m_bStopLayoutOnAddRemove
int m_iLastMinimumHeight
KviPointerHashTable< QString,
KviStatusBarAppletDescriptor > * m_pAppletDescriptors
KviPointerList
< KviStatusBarApplet > * m_pAppletList
KviTalPopupMenu * m_pAppletsPopup
KviTalHBox * m_pBox
KviStatusBarApplet * m_pClickedApplet
KviTalPopupMenu * m_pContextPopup
KviFrame * m_pFrame
QLabel * m_pMessageLabel
KviPointerList
< KviStatusBarMessage > * m_pMessageQueue
QTimer * m_pMessageTimer
KviDynamicToolTip * m_pToolTip
Friends
class KviFrame
class KviStatusBarApplet
Detailed Description
Status Bar class.
Constructor & Destructor Documentation
KviStatusBar::KviStatusBar (KviFrame * pFrame)
Constructs the statusbar object.
Parameters:
pFrame The parent frame class
Returns:
KviStatusBar
References contextMenuRequested(), m_bStopLayoutOnAddRemove, m_iLastMinimumHeight, m_pAppletDescriptors, m_pAppletList, m_pAppletsPopup, m_pClickedApplet, m_pContextPopup, m_pFrame, m_pMessageLabel, m_pMessageQueue, m_pMessageTimer, KviStatusBarSeparator::selfRegister(), KviStatusBarUpdateIndicator::selfRegister(), KviStatusBarConnectionTimer::selfRegister(), KviStatusBarLagIndicator::selfRegister(), KviStatusBarAwayIndicator::selfRegister(), KviStatusBarClock::selfRegister(), KviPointerList< T >::setAutoDelete(), KviPointerHashTable< Key, T >::setAutoDelete(), and setPermanentMessage().
KviStatusBar::~KviStatusBar ()
Destroys the statusbar object.
References m_bStopLayoutOnAddRemove, m_pAppletDescriptors, m_pAppletList, m_pMessageLabel, m_pMessageQueue, m_pMessageTimer, and save().
Member Function Documentation
KviStatusBarApplet * KviStatusBar::appletAt (const QPoint & pnt, bool bBestMatch = false)
Returns the applet at the given point.
If bBestMatch is specified and no applets are found, the last applet will be returned
Parameters:
pnt The source point
bBestMatch Whether to return the best match
Returns:
KviStatusBarApplet *
Warning:
pnt is global!
References KviPointerList< T >::first(), KviPointerList< T >::last(), m_pAppletList, and KviPointerList< T >::next().
Referenced by contextMenuRequested(), and tipRequest().
bool KviStatusBar::appletExists (KviStatusBarApplet * pApplet)
Returns true if the applet exists, false otherwise.
Parameters:
pApplet The pointer to the applet to check existance
Returns:
bool
References KviPointerList< T >::findRef(), and m_pAppletList.
Referenced by contextPopupAboutToShow(), dragMoveEvent(), and removeClickedApplet().
void KviStatusBar::appletsPopupAboutToShow () [protected, slot]
Shows the per-applet popup menu.
Returns:
void
References KviTalPopupMenu::clear(), KviPointerHashTableIterator< Key, T >::current(), d, g_pModuleManager, KviTalPopupMenu::insertItem(), KviModuleManager::loadModulesByCaps(), m_pAppletDescriptors, m_pAppletsPopup, and KviTalPopupMenu::setItemParameter().
Referenced by contextPopupAboutToShow().
void KviStatusBar::appletsPopupActivated (int iId) [protected, slot]
Called when the user activates the per-applet popup.
Parameters:
iId The id of the applet
Returns:
void
References KviPointerHashTableIterator< Key, T >::current(), d, KviPointerList< T >::findRef(), KviPointerList< T >::inSort(), KviTalPopupMenu::itemParameter(), m_bStopLayoutOnAddRemove, m_pAppletDescriptors, m_pAppletList, m_pAppletsPopup, m_pClickedApplet, KviPointerList< T >::removeRef(), and showLayoutHelp().
Referenced by contextPopupAboutToShow().
void KviStatusBar::contextMenuRequested (const QPoint & pos) [protected, slot]
Called when the user requests a context menu.
Parameters:
pos The position of the mouse
Returns:
void
References appletAt(), contextPopupAboutToShow(), m_pClickedApplet, and m_pContextPopup.
Referenced by KviStatusBar().
void KviStatusBar::contextPopupAboutToShow () [protected, slot]
Shows the applet common popup menu.
Returns:
void
References __tr2qs, appletExists(), appletsPopupAboutToShow(), appletsPopupActivated(), KviTalPopupMenu::clear(), KviStatusBarApplet::descriptor(), KviStatusBarApplet::fillContextPopup(), KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), m_pAppletsPopup, m_pClickedApplet, m_pContextPopup, removeClickedApplet(), KviQString::sprintf(), and KviStatusBarAppletDescriptor::visibleName().
Referenced by contextMenuRequested().
KviStatusBarApplet * KviStatusBar::createApplet (const QString & szInternalName) [protected]
Create an applet.
It searches for the given name and if found in the applet descriptor stack, it will passes creates the applet
Parameters:
szInternalName The internal name of the applet
Returns:
KviStatusBarApplet *
References KviStatusBarAppletDescriptor::create(), d, KviPointerHashTable< Key, T >::find(), and m_pAppletDescriptors.
Referenced by load().
void KviStatusBar::dragEnterEvent (QDragEnterEvent * event) [protected]
void KviStatusBar::dragMoveEvent (QDragMoveEvent * de) [protected]
References appletExists(), KviPointerList< T >::first(), KviStatusBarApplet::index(), KviPointerList< T >::last(), m_pAppletList, m_pClickedApplet, KviPointerList< T >::prev(), KviStatusBarApplet::setIndex(), and KviPointerList< T >::sort().
void KviStatusBar::dropEvent (QDropEvent * de) [protected]
References m_pClickedApplet.
bool KviStatusBar::event (QEvent * e) [protected, virtual]
References tipRequest().
KviFrame* KviStatusBar::frame () [inline]
Returns the frame pointer.
Returns:
KviFrame *
Referenced by KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), KviStatusBarLagIndicator::KviStatusBarLagIndicator(), KviStatusBarLagIndicator::mouseDoubleClickEvent(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviStatusBarLagIndicator::tipText(), KviStatusBarAwayIndicator::tipText(), KviStatusBarLagIndicator::updateDisplay(), and KviStatusBarAwayIndicator::updateDisplay().
int KviStatusBar::insertPermanentWidgetAtTheEnd (QWidget * widget, int stretch = 0)
Inserts an applet at the end of the statusbar as a permanent widget and returns its index.
Parameters:
widget The widget to insert
stretch Stretch factor used to compute widget size when the statusbar gets resized. Defaults to 0.
Returns:
int
References KviPointerList< T >::count(), and m_pAppletList.
Referenced by CreateStatusBarAwayIndicator(), CreateStatusBarClock(), CreateStatusBarConnectionTimer(), CreateStatusBarLagIndicator(), CreateStatusBarSeparator(), and CreateStatusBarUpdateIndicator().
void KviStatusBar::load () [protected]
Saves the statusbar stack.
Returns:
void
References createApplet(), KviStr::Format, g_pApp, g_pModuleManager, KviModuleManager::getModule(), KviApp::getReadOnlyConfigPath(), KviStatusBarApplet::loadState(), KviStr::ptr(), KviConfig::Read, KviConfig::readEntry(), KviConfig::readIntEntry(), and KviConfig::setGroup().
Referenced by KviFrame::KviFrame(), and KviFrame::toggleStatusBar().
void KviStatusBar::messageTimerFired () [protected, slot]
Called when the timer timeouts.
Remove the first item from the stack and sets the second one as permanent
Returns:
void
References KviPointerList< T >::isEmpty(), m_pMessageQueue, m_pMessageTimer, KviPointerList< T >::removeFirst(), setPermanentMessage(), and showFirstMessageInQueue().
Referenced by showFirstMessageInQueue().
void KviStatusBar::mouseDoubleClickEvent (QMouseEvent * e) [protected, virtual]
References __tr2qs, KviFrame::activeContext(), c, KviIrcContext::Connected, KviIrcContext::connection(), KviIrcConnection::currentServerName(), KviIrcConnectionUserInfo::hostName(), KviIrcConnectionUserInfo::isAway(), KviIrcConnectionUserInfo::localHostIp(), m_pFrame, KviIrcConnection::networkName(), KviIrcConnectionUserInfo::nickName(), KviIrcContext::state(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userMode(), and KviIrcConnectionUserInfo::userName().
void KviStatusBar::mousePressEvent (QMouseEvent * e) [protected, virtual]
References KviStatusBarApplet::index(), m_pAppletList, m_pClickedApplet, and KviPointerList< T >::sort().
void KviStatusBar::queueMessage (KviStatusBarMessage * pMsg)
Queue a statusbar message in the stack.
Parameters:
pMsg The pointer to the message to queue
Returns:
void
Warning:
It takes the ownership of pMsg
References KviPointerList< T >::append(), KviPointerList< T >::count(), KviPointerList< T >::first(), m_pMessageQueue, m_pMessageTimer, KviPointerList< T >::prepend(), KviStatusBarMessage::priority(), and showFirstMessageInQueue().
Referenced by showLayoutHelp().
void KviStatusBar::recalcMinimumHeight () [protected]
Recalculates the minimum height of the status bar.
Returns:
void
References KviPointerList< T >::last(), m_iLastMinimumHeight, m_pAppletList, m_pMessageLabel, KviPointerList< T >::prev(), RICHTEXTLABELTRICK, and VMARGIN.
void KviStatusBar::registerApplet (KviStatusBarApplet * pApplet) [protected]
Registers the given applet in the statusbar.
Parameters:
pApplet The pointer to the applet
Returns:
void
References KviPointerList< T >::inSort(), and m_pAppletList.
Referenced by KviStatusBarApplet::KviStatusBarApplet().
void KviStatusBar::registerAppletDescriptor (KviStatusBarAppletDescriptor * d)
Registers the applet descriptor.
Parameters:
d The applet description to register
Returns:
void
References d, KviStatusBarAppletDescriptor::internalName(), m_pAppletDescriptors, and KviPointerHashTable< Key, T >::replace().
Referenced by KviStatusBarUpdateIndicator::selfRegister(), KviStatusBarSeparator::selfRegister(), KviStatusBarConnectionTimer::selfRegister(), KviStatusBarClock::selfRegister(), KviStatusBarLagIndicator::selfRegister(), and KviStatusBarAwayIndicator::selfRegister().
void KviStatusBar::removeClickedApplet () [protected, slot]
Called when the user removes an applet from the statusbar.
Returns:
void
References appletExists(), and m_pClickedApplet.
Referenced by contextPopupAboutToShow().
void KviStatusBar::save () [protected]
Saves the statusbar stack.
Returns:
void
References KviApp::Config, KviPointerList< T >::count(), KviPointerList< T >::first(), KviStr::Format, g_pApp, KviApp::getLocalKvircDirectory(), m_pAppletList, KviPointerList< T >::next(), KviStr::ptr(), KviConfig::setGroup(), KviPointerList< T >::sort(), KviConfig::Write, and KviConfig::writeEntry().
Referenced by ~KviStatusBar().
void KviStatusBar::setPermanentMessage () [protected, slot]
Sets the permanent message to be shown.
The message varies upon the connection status
Returns:
void
References __tr2qs, KviFrame::activeContext(), c, KviIrcContext::Connected, KviIrcContext::Connecting, KviIrcContext::connection(), KviIrcConnection::currentNickName(), KviIrcConnection::currentServerName(), KviIrcContext::LoggingIn, m_pFrame, m_pMessageLabel, m_pMessageTimer, KviIrcContext::state(), KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userMode().
Referenced by KviStatusBar(), and messageTimerFired().
void KviStatusBar::showFirstMessageInQueue () [protected]
Shows the first message in the queue stack.
Returns:
void
References KviPointerList< T >::first(), m_pMessageLabel, m_pMessageQueue, m_pMessageTimer, messageTimerFired(), KviStatusBarMessage::text(), and KviStatusBarMessage::timeout().
Referenced by messageTimerFired(), and queueMessage().
void KviStatusBar::showLayoutHelp () [protected]
Shows the common help for every applet.
Returns:
void
References __tr2qs, and queueMessage().
Referenced by appletsPopupActivated().
void KviStatusBar::tipRequest (QHelpEvent * e) [protected]
Shows the right tooltip.
If an applet is found at the position of the triggered event, the right tooltip will be show, otherwise a common one will be show
Parameters:
e The event triggered
Returns:
void
References __tr2qs, KviFrame::activeContext(), appletAt(), c, KviIrcContext::Connected, KviStatusBarApplet::descriptor(), m_pFrame, KviIrcContext::state(), KviStatusBarApplet::tipText(), and KviStatusBarAppletDescriptor::visibleName().
Referenced by event().
void KviStatusBar::unregisterApplet (KviStatusBarApplet * pApplet) [protected]
Unegisters the given applet in the statusbar.
Parameters:
pApplet The pointer to the applet
Returns:
void
References m_pAppletList, and KviPointerList< T >::removeRef().
Referenced by KviStatusBarApplet::~KviStatusBarApplet().
Friends And Related Function Documentation
friend class KviFrame [friend]
friend class KviStatusBarApplet [friend]
Member Data Documentation
bool KviStatusBar::m_bStopLayoutOnAddRemove [protected]
Referenced by appletsPopupActivated(), KviStatusBar(), and ~KviStatusBar().
int KviStatusBar::m_iLastMinimumHeight [protected]
Referenced by KviStatusBar(), and recalcMinimumHeight().
KviPointerHashTable<QString,KviStatusBarAppletDescriptor>* KviStatusBar::m_pAppletDescriptors [protected]
Referenced by appletsPopupAboutToShow(), appletsPopupActivated(), createApplet(), KviStatusBar(), registerAppletDescriptor(), and ~KviStatusBar().
KviPointerList<KviStatusBarApplet>* KviStatusBar::m_pAppletList [protected]
Referenced by appletAt(), appletExists(), appletsPopupActivated(), dragMoveEvent(), insertPermanentWidgetAtTheEnd(), KviStatusBar(), mousePressEvent(), recalcMinimumHeight(), registerApplet(), save(), unregisterApplet(), and ~KviStatusBar().
KviTalPopupMenu* KviStatusBar::m_pAppletsPopup [protected]
Referenced by appletsPopupAboutToShow(), appletsPopupActivated(), contextPopupAboutToShow(), and KviStatusBar().
KviTalHBox* KviStatusBar::m_pBox [protected]
KviStatusBarApplet* KviStatusBar::m_pClickedApplet [protected]
Referenced by appletsPopupActivated(), contextMenuRequested(), contextPopupAboutToShow(), dragMoveEvent(), dropEvent(), KviStatusBar(), mousePressEvent(), and removeClickedApplet().
KviTalPopupMenu* KviStatusBar::m_pContextPopup [protected]
Referenced by contextMenuRequested(), contextPopupAboutToShow(), and KviStatusBar().
KviFrame* KviStatusBar::m_pFrame [protected]
Referenced by KviStatusBar(), mouseDoubleClickEvent(), setPermanentMessage(), and tipRequest().
QLabel* KviStatusBar::m_pMessageLabel [protected]
Referenced by KviStatusBar(), recalcMinimumHeight(), setPermanentMessage(), showFirstMessageInQueue(), and ~KviStatusBar().
KviPointerList<KviStatusBarMessage>* KviStatusBar::m_pMessageQueue [protected]
Referenced by KviStatusBar(), messageTimerFired(), queueMessage(), showFirstMessageInQueue(), and ~KviStatusBar().
QTimer* KviStatusBar::m_pMessageTimer [protected]
Referenced by KviStatusBar(), messageTimerFired(), queueMessage(), setPermanentMessage(), showFirstMessageInQueue(), and ~KviStatusBar().
KviDynamicToolTip* KviStatusBar::m_pToolTip [protected]
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_statusbar.h
src/kvirc/ui/kvi_statusbar.cpp