KVIrc: SharedFilesTreeWidgetItem Class Reference
SharedFilesTreeWidgetItem Class Reference
#include <SharedFilesWindow.h>
Public Member Functions
KviSharedFile * readOnlySharedFilePointer ()
SharedFilesTreeWidgetItem (QTreeWidget *lv, KviSharedFile *f)
~SharedFilesTreeWidgetItem ()
Protected Attributes
KviSharedFile * m_pSharedFilePointer
Constructor & Destructor Documentation
SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem (QTreeWidget * lv, KviSharedFile * f)
References __tr2qs_ctx(), KviSharedFile::absFilePath(), KviSharedFile::expires(), KviSharedFile::expireTime(), f, m_pSharedFilePointer, KviSharedFile::name(), and KviSharedFile::userMask().
SharedFilesTreeWidgetItem::~SharedFilesTreeWidgetItem ()
Member Function Documentation
KviSharedFile* SharedFilesTreeWidgetItem::readOnlySharedFilePointer () [inline]
References m_pSharedFilePointer.
Referenced by SharedFilesWindow::editClicked(), and SharedFilesWindow::removeClicked().
Member Data Documentation
KviSharedFile* SharedFilesTreeWidgetItem::m_pSharedFilePointer [protected]
Referenced by readOnlySharedFilePointer(), and SharedFilesTreeWidgetItem().
The documentation for this class was generated from the following files:
src/modules/sharedfileswindow/SharedFilesWindow.h
src/modules/sharedfileswindow/SharedFilesWindow.cpp