KVIrc: KviOptionsWidget Class Reference
KviOptionsWidget Class Reference
#include <KviOptionsWidget.h>
Public Member Functions
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
QPushButton * addPushButton (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
virtual void commit ()
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void childOptionsWidgetDestroyed ()
Protected Member Functions
void commitOptionsReset ()
void commitSelectors ()
Private Attributes
int m_iResetFlags
int m_iSelectors
QGridLayout * m_pLayout
KviPointerList
< KviSelectorInterface > * m_pSelectorInterfaceList
QTabWidget * m_pTabWidget
Static Private Attributes
static QString m_szBasicTipEnd
static QString m_szBasicTipStart
Constructor & Destructor Documentation
KviOptionsWidget::KviOptionsWidget (QWidget * parent, const char * name = 0, bool bSunken = true)
References __tr2qs, m_iResetFlags, m_iSelectors, m_pLayout, m_pSelectorInterfaceList, m_pTabWidget, m_szBasicTipEnd, m_szBasicTipStart, and KviPointerList< T >::setAutoDelete().
KviOptionsWidget::~KviOptionsWidget ()
References m_pSelectorInterfaceList.
Member Function Documentation
KviBoolSelector * KviOptionsWidget::addBoolSelector (int x1, int y1, int x2, int y2, const QString & txt, bool * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), and m_pSelectorInterfaceList.
Referenced by addBoolSelector(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_antispam::OptionsWidget_antispam(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_channelGeneral::OptionsWidget_channelGeneral(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccGeneral::OptionsWidget_dccGeneral(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_ignore::OptionsWidget_ignore(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures(), OptionsWidget_ircAdvanced::OptionsWidget_ircAdvanced(), OptionsWidget_ircGeneral::OptionsWidget_ircGeneral(), OptionsWidget_ircOutput::OptionsWidget_ircOutput(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_theme::OptionsWidget_theme(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_timestamp::OptionsWidget_timestamp(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_uparser::OptionsWidget_uparser(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListFeatures::OptionsWidget_userListFeatures(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), OptionsWidget_windowList::OptionsWidget_windowList(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), and OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures().
KviBoolSelector * KviOptionsWidget::addBoolSelector (QWidget * pParent, const QString & txt, bool * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), and m_pSelectorInterfaceList.
KviBoolSelector * KviOptionsWidget::addBoolSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addBoolSelector(), d, g_boolOptionsTable, KVI_OPTION_BOOL, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviBoolSelector * KviOptionsWidget::addBoolSelector (QWidget * pParnt, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addBoolSelector(), d, g_boolOptionsTable, KVI_OPTION_BOOL, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviColorSelector * KviOptionsWidget::addColorSelector (int x1, int y1, int x2, int y2, const QString & txt, QColor * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), m_pSelectorInterfaceList, and s.
Referenced by addColorSelector(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_standardColors::OptionsWidget_standardColors(), OptionsWidget_themeToolBarApplets::OptionsWidget_themeToolBarApplets(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_topicLabel::OptionsWidget_topicLabel(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground(), and OptionsWidget_windowListTreeForeground::OptionsWidget_windowListTreeForeground().
KviColorSelector * KviOptionsWidget::addColorSelector (QWidget * pParent, const QString & txt, QColor * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), m_pSelectorInterfaceList, and s.
KviColorSelector * KviOptionsWidget::addColorSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addColorSelector(), d, g_colorOptionsTable, KVI_OPTION_COLOR, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviColorSelector * KviOptionsWidget::addColorSelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addColorSelector(), d, g_colorOptionsTable, KVI_OPTION_COLOR, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviDirectorySelector * KviOptionsWidget::addDirectorySelector (int x1, int y1, int x2, int y2, const QString & txt, QString * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
Referenced by addDirectorySelector(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), and OptionsWidget_logging::OptionsWidget_logging().
KviDirectorySelector * KviOptionsWidget::addDirectorySelector (QWidget * pParent, const QString & txt, QString * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
KviDirectorySelector * KviOptionsWidget::addDirectorySelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addDirectorySelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviDirectorySelector * KviOptionsWidget::addDirectorySelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addDirectorySelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviFileSelector * KviOptionsWidget::addFileSelector (int x1, int y1, int x2, int y2, const QString & txt, QString * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
Referenced by addFileSelector(), and OptionsWidget_connectionSsl::OptionsWidget_connectionSsl().
KviFileSelector * KviOptionsWidget::addFileSelector (QWidget * pParent, const QString & txt, QString * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
KviFileSelector * KviOptionsWidget::addFileSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addFileSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviFileSelector * KviOptionsWidget::addFileSelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addFileSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviFontSelector * KviOptionsWidget::addFontSelector (int x1, int y1, int x2, int y2, const QString & txt, QFont * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), f, and m_pSelectorInterfaceList.
Referenced by addFontSelector(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_theme::OptionsWidget_theme(), OptionsWidget_topicLabel::OptionsWidget_topicLabel(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), and OptionsWidget_windowListTreeForeground::OptionsWidget_windowListTreeForeground().
KviFontSelector * KviOptionsWidget::addFontSelector (QWidget * pParent, const QString & txt, QFont * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), f, and m_pSelectorInterfaceList.
KviFontSelector * KviOptionsWidget::addFontSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addFontSelector(), d, g_fontOptionsTable, KVI_OPTION_FONT, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviFontSelector * KviOptionsWidget::addFontSelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addFontSelector(), d, g_fontOptionsTable, KVI_OPTION_FONT, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviTalGroupBox * KviOptionsWidget::addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString & txt, bool bEnabled = true)
References addWidgetToLayout(), and g.
Referenced by KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_antispam::OptionsWidget_antispam(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_channelGeneral::OptionsWidget_channelGeneral(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_ignore::OptionsWidget_ignore(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures(), OptionsWidget_ircOutput::OptionsWidget_ircOutput(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground(), and OptionsWidget_windowListTreeForeground::OptionsWidget_windowListTreeForeground().
QLabel * KviOptionsWidget::addLabel (int x1, int y1, int x2, int y2, const QString & text, bool bEnabled = true)
References addWidgetToLayout(), and l.
Referenced by OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_general::OptionsWidget_general(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_sounds::OptionsWidget_sounds(), OptionsWidget_standardColors::OptionsWidget_standardColors(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), OptionsWidget_tools::OptionsWidget_tools(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), and OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground().
QLabel * KviOptionsWidget::addLabel (QWidget * pParent, const QString & text, bool bEnabled = true)
References l.
QLineEdit * KviOptionsWidget::addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled = true)
References addWidgetToLayout(), and l.
KviMircTextColorSelector * KviOptionsWidget::addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString & txt, unsigned int * uFore, unsigned int * uBack, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), m_pSelectorInterfaceList, and s.
Referenced by addMircTextColorSelector(), OptionsWidget_privmsg::OptionsWidget_privmsg(), and OptionsWidget_timestamp::OptionsWidget_timestamp().
KviMircTextColorSelector * KviOptionsWidget::addMircTextColorSelector (QWidget * pParent, const QString & txt, unsigned int * uFore, unsigned int * uBack, bool bEnabled = true)
References KviPointerList< T >::append(), m_pSelectorInterfaceList, and s.
KviMircTextColorSelector * KviOptionsWidget::addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString & txt, int optForeId, int optBackId, bool bEnabled = true)
References KviTalToolTip::add(), addMircTextColorSelector(), d, g_uintOptionsTable, KVI_OPTION_UINT, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviMircTextColorSelector * KviOptionsWidget::addMircTextColorSelector (QWidget * pParent, const QString & txt, int optForeId, int optBackId, bool bEnabled = true)
References KviTalToolTip::add(), addMircTextColorSelector(), d, g_uintOptionsTable, KVI_OPTION_UINT, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
void KviOptionsWidget::addOptionsWidget (const QString & szText, const QIcon & iconSet, KviOptionsWidget * pWidget)
References KviPointerList< T >::append(), childOptionsWidgetDestroyed(), connect(), KviPointerList< T >::findRef(), layout(), m_pSelectorInterfaceList, and m_pTabWidget.
Referenced by OptionsInstanceManager::getInstance().
KviPasswordSelector * KviOptionsWidget::addPasswordSelector (int x1, int y1, int x2, int y2, const QString & txt, QString * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
Referenced by addPasswordSelector(), and OptionsWidget_connectionSsl::OptionsWidget_connectionSsl().
KviPasswordSelector * KviOptionsWidget::addPasswordSelector (QWidget * pParent, const QString & txt, QString * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
KviPasswordSelector * KviOptionsWidget::addPasswordSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addPasswordSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviPasswordSelector * KviOptionsWidget::addPasswordSelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addPasswordSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviPixmapSelector * KviOptionsWidget::addPixmapSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), d, g_pixmapOptionsTable, KVI_OPTION_PIXMAP, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
Referenced by OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_themeToolBarApplets::OptionsWidget_themeToolBarApplets(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_topicLabel::OptionsWidget_topicLabel(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), and OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground().
KviPixmapSelector * KviOptionsWidget::addPixmapSelector (int x1, int y1, int x2, int y2, const QString & txt, KviPixmap * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), and m_pSelectorInterfaceList.
QPushButton * KviOptionsWidget::addPushButton (int x1, int y1, int x2, int y2, const QString & text, bool bEnabled = true)
References addWidgetToLayout().
Referenced by OptionsWidget_standardColors::OptionsWidget_standardColors().
void KviOptionsWidget::addRowSpacer (int x1, int y1, int x2, int y2)
References addWidgetToLayout(), layout(), and w.
Referenced by KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_channelGeneral::OptionsWidget_channelGeneral(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccGeneral::OptionsWidget_dccGeneral(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_general::OptionsWidget_general(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_ignore::OptionsWidget_ignore(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures(), OptionsWidget_ircAdvanced::OptionsWidget_ircAdvanced(), OptionsWidget_ircGeneral::OptionsWidget_ircGeneral(), OptionsWidget_ircOutput::OptionsWidget_ircOutput(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_sounds::OptionsWidget_sounds(), OptionsWidget_standardColors::OptionsWidget_standardColors(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), OptionsWidget_theme::OptionsWidget_theme(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_timestamp::OptionsWidget_timestamp(), OptionsWidget_tools::OptionsWidget_tools(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_uparser::OptionsWidget_uparser(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListFeatures::OptionsWidget_userListFeatures(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), OptionsWidget_windowList::OptionsWidget_windowList(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures(), and OptionsWidget_windowListTreeForeground::OptionsWidget_windowListTreeForeground().
QFrame * KviOptionsWidget::addSeparator (int x1, int y1, int x2, int y2)
References addWidgetToLayout(), and f.
Referenced by OptionsWidget_uparser::OptionsWidget_uparser().
KviSoundSelector * KviOptionsWidget::addSoundSelector (int x1, int y1, int x2, int y2, const QString & txt, QString * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
Referenced by addSoundSelector(), and OptionsWidget_sounds::OptionsWidget_sounds().
KviSoundSelector * KviOptionsWidget::addSoundSelector (QWidget * pParent, const QString & txt, QString * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
KviSoundSelector * KviOptionsWidget::addSoundSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addSoundSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviSoundSelector * KviOptionsWidget::addSoundSelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addSoundSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviStringListSelector * KviOptionsWidget::addStringListSelector (int x1, int y1, int x2, int y2, const QString & txt, QStringList * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
Referenced by addStringListSelector(), OptionsWidget_antispam::OptionsWidget_antispam(), and OptionsWidget_highlighting::OptionsWidget_highlighting().
KviStringListSelector * KviOptionsWidget::addStringListSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addStringListSelector(), d, g_stringlistOptionsTable, KVI_OPTION_STRINGLIST, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviStringSelector * KviOptionsWidget::addStringSelector (int x1, int y1, int x2, int y2, const QString & txt, QString * pOption, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
Referenced by addStringSelector(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_timestamp::OptionsWidget_timestamp(), and OptionsWidget_urlHandlers::OptionsWidget_urlHandlers().
KviStringSelector * KviOptionsWidget::addStringSelector (QWidget * pParent, const QString & txt, QString * pOption, bool bEnabled = true)
References KviPointerList< T >::append(), d, and m_pSelectorInterfaceList.
KviStringSelector * KviOptionsWidget::addStringSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addStringSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviStringSelector * KviOptionsWidget::addStringSelector (QWidget * pParent, const QString & txt, int optId, bool bEnabled = true)
References KviTalToolTip::add(), addStringSelector(), d, g_stringOptionsTable, KVI_OPTION_STRING, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviUIntSelector * KviOptionsWidget::addUIntSelector (int x1, int y1, int x2, int y2, const QString & txt, unsigned int * pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), m_pSelectorInterfaceList, and u.
Referenced by addUIntSelector(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), and OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures().
KviUIntSelector * KviOptionsWidget::addUIntSelector (QWidget * pParent, const QString & txt, unsigned int * pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled = true)
References KviPointerList< T >::append(), m_pSelectorInterfaceList, and u.
KviUIntSelector * KviOptionsWidget::addUIntSelector (int x1, int y1, int x2, int y2, const QString & txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled = true)
References KviTalToolTip::add(), addUIntSelector(), d, g_uintOptionsTable, KVI_OPTION_UINT, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviUIntSelector * KviOptionsWidget::addUIntSelector (QWidget * pParent, const QString & txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled = true)
References KviTalToolTip::add(), addUIntSelector(), d, g_uintOptionsTable, KVI_OPTION_UINT, m_iResetFlags, m_szBasicTipEnd, and m_szBasicTipStart.
KviUIntSelector * KviOptionsWidget::addUShortIntSelector (int x1, int y1, int x2, int y2, const QString & txt, unsigned short int * pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled = true)
References addWidgetToLayout(), KviPointerList< T >::append(), m_pSelectorInterfaceList, and u.
void KviOptionsWidget::addWidgetToLayout (QWidget * w, int x1, int y1, int x2, int y2)
References layout().
Referenced by addBoolSelector(), addColorSelector(), addDirectorySelector(), addFileSelector(), addFontSelector(), addGroupBox(), addLabel(), addLineEdit(), addMircTextColorSelector(), addPasswordSelector(), addPixmapSelector(), addPushButton(), addRowSpacer(), addSeparator(), addSoundSelector(), addStringListSelector(), addStringSelector(), addUIntSelector(), addUShortIntSelector(), createTabbedPage(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_ircOutput::OptionsWidget_ircOutput(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_messageColors::OptionsWidget_messageColors(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_timestamp::OptionsWidget_timestamp(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), and OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground().
void KviOptionsWidget::childEvent (QChildEvent * e) virtual
References childOptionsWidgetDestroyed(), m_pSelectorInterfaceList, and KviPointerList< T >::removeRef().
void KviOptionsWidget::childOptionsWidgetDestroyed () protected slot
References m_pSelectorInterfaceList, and KviPointerList< T >::removeRef().
Referenced by addOptionsWidget(), childEvent(), and eventFilter().
void KviOptionsWidget::commit (void) virtual
Reimplemented from KviSelectorInterface.
Reimplemented in OptionsWidget_servers, OptionsWidget_identityProfile, OptionsWidget_identityAdvanced, OptionsWidget_identityAvatar, KviIdentityGeneralOptionsWidget, OptionsWidget_userListGrid, OptionsWidget_proxy, OptionsWidget_identService, OptionsWidget_ircViewMarker, OptionsWidget_windowListTreeBackground, OptionsWidget_nickServ, OptionsWidget_mediaTypes, OptionsWidget_textIcons, OptionsWidget_soundGeneral, OptionsWidget_channelAdvanced, OptionsWidget_ircViewLook, OptionsWidget_userListBackground, OptionsWidget_highlighting, OptionsWidget_textEncoding, OptionsWidget_ircOutput, OptionsWidget_inputLook, OptionsWidget_notifierLook, and OptionsWidget_urlHandlers.
References commitOptionsReset(), and commitSelectors().
Referenced by OptionsWidget_urlHandlers::commit(), OptionsWidget_inputLook::commit(), OptionsWidget_notifierLook::commit(), OptionsWidget_ircOutput::commit(), OptionsWidget_highlighting::commit(), OptionsWidget_userListBackground::commit(), OptionsWidget_ircViewLook::commit(), OptionsWidget_channelAdvanced::commit(), OptionsWidget_soundGeneral::commit(), OptionsWidget_textIcons::commit(), OptionsWidget_nickServ::commit(), OptionsWidget_windowListTreeBackground::commit(), OptionsWidget_identService::commit(), OptionsWidget_ircViewMarker::commit(), OptionsWidget_proxy::commit(), OptionsWidget_userListGrid::commit(), KviIdentityGeneralOptionsWidget::commit(), OptionsWidget_messageColors::commit(), OptionsWidget_identityAvatar::commit(), OptionsWidget_identityAdvanced::commit(), OptionsWidget_identityProfile::commit(), OptionsWidget_servers::commit(), OptionsWidgetContainer::okClicked(), and OptionsDialog::recursiveCommit().
void KviOptionsWidget::commitOptionsReset () protected
References g_pApp, m_iResetFlags, and KviApplication::optionResetUpdate().
Referenced by commit().
void KviOptionsWidget::commitSelectors () protected
References KviPointerList< T >::first(), i, m_pSelectorInterfaceList, and KviPointerList< T >::next().
Referenced by commit().
void KviOptionsWidget::createLayout ()
References g_pApp, and m_pLayout.
Referenced by createTabbedPage(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsDialogFrontWidget::OptionsDialogFrontWidget(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_antispam::OptionsWidget_antispam(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_channelGeneral::OptionsWidget_channelGeneral(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccGeneral::OptionsWidget_dccGeneral(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_general::OptionsWidget_general(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_ignore::OptionsWidget_ignore(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures(), OptionsWidget_ircAdvanced::OptionsWidget_ircAdvanced(), OptionsWidget_ircGeneral::OptionsWidget_ircGeneral(), OptionsWidget_ircOutput::OptionsWidget_ircOutput(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_mediaTypes::OptionsWidget_mediaTypes(), OptionsWidget_messageColors::OptionsWidget_messageColors(), OptionsWidget_nickServ::OptionsWidget_nickServ(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_protection::OptionsWidget_protection(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_sounds::OptionsWidget_sounds(), OptionsWidget_standardColors::OptionsWidget_standardColors(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), OptionsWidget_textIcons::OptionsWidget_textIcons(), OptionsWidget_theme::OptionsWidget_theme(), OptionsWidget_themeToolBarApplets::OptionsWidget_themeToolBarApplets(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_timestamp::OptionsWidget_timestamp(), OptionsWidget_tools::OptionsWidget_tools(), OptionsWidget_topicLabel::OptionsWidget_topicLabel(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_uparser::OptionsWidget_uparser(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), OptionsWidget_userListFeatures::OptionsWidget_userListFeatures(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), OptionsWidget_windowList::OptionsWidget_windowList(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground(), OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures(), and OptionsWidget_windowListTreeForeground::OptionsWidget_windowListTreeForeground().
void KviOptionsWidget::createTabbedPage ()
References addWidgetToLayout(), createLayout(), layout(), and m_pTabWidget.
Referenced by OptionsInstanceManager::getInstance().
bool KviOptionsWidget::eventFilter (QObject * watched, QEvent * e) virtual
References childOptionsWidgetDestroyed(), e, m_pSelectorInterfaceList, m_pTabWidget, and KviPointerList< T >::removeRef().
QGridLayout* KviOptionsWidget::layout () inline
Referenced by addOptionsWidget(), addRowSpacer(), addWidgetToLayout(), createTabbedPage(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsDialogFrontWidget::OptionsDialogFrontWidget(), OptionsWidget_antispam::OptionsWidget_antispam(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_mediaTypes::OptionsWidget_mediaTypes(), OptionsWidget_messageColors::OptionsWidget_messageColors(), OptionsWidget_nickServ::OptionsWidget_nickServ(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_standardColors::OptionsWidget_standardColors(), OptionsWidget_textIcons::OptionsWidget_textIcons(), OptionsWidget_themeToolBarApplets::OptionsWidget_themeToolBarApplets(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_topicLabel::OptionsWidget_topicLabel(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), and OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground().
void KviOptionsWidget::mergeResetFlag (int flag) inline
Referenced by OptionsWidget_messageColors::commit().
void KviOptionsWidget::mergeTip (QWidget * w, const QString & tip)
References KviTalToolTip::add(), and s.
Referenced by KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_channelGeneral::OptionsWidget_channelGeneral(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccGeneral::OptionsWidget_dccGeneral(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_ircAdvanced::OptionsWidget_ircAdvanced(), OptionsWidget_ircGeneral::OptionsWidget_ircGeneral(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_mediaTypes::OptionsWidget_mediaTypes(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_textIcons::OptionsWidget_textIcons(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_uparser::OptionsWidget_uparser(), OptionsWidget_userListFeatures::OptionsWidget_userListFeatures(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), and OptionsWidget_windowList::OptionsWidget_windowList().
void KviOptionsWidget::removeSelector (KviSelectorInterface * pInterface)
References KVI_ASSERT, m_pSelectorInterfaceList, and KviPointerList< T >::removeRef().
Referenced by OptionsWidget_servers::slotShowThisDialogAtStartupSelectorDestroyed().
KviPointerList<KviSelectorInterface>* KviOptionsWidget::selectors () inline
Referenced by OptionsDialog::searchInSelectors().
QTabWidget* KviOptionsWidget::tabWidget () inline
Referenced by OptionsDialog::apply(), OptionsInstanceManager::getInstance(), and OptionsDialog::recursiveSearch().
Member Data Documentation
int KviOptionsWidget::m_iResetFlags private
Referenced by addBoolSelector(), addColorSelector(), addDirectorySelector(), addFileSelector(), addFontSelector(), addMircTextColorSelector(), addPasswordSelector(), addPixmapSelector(), addSoundSelector(), addStringListSelector(), addStringSelector(), addUIntSelector(), commitOptionsReset(), and KviOptionsWidget().
int KviOptionsWidget::m_iSelectors private
Referenced by KviOptionsWidget().
QGridLayout* KviOptionsWidget::m_pLayout private
Referenced by createLayout(), and KviOptionsWidget().
KviPointerList<KviSelectorInterface>* KviOptionsWidget::m_pSelectorInterfaceList private
Referenced by addBoolSelector(), addColorSelector(), addDirectorySelector(), addFileSelector(), addFontSelector(), addMircTextColorSelector(), addOptionsWidget(), addPasswordSelector(), addPixmapSelector(), addSoundSelector(), addStringListSelector(), addStringSelector(), addUIntSelector(), addUShortIntSelector(), childEvent(), childOptionsWidgetDestroyed(), commitSelectors(), eventFilter(), KviOptionsWidget(), removeSelector(), and ~KviOptionsWidget().
QTabWidget* KviOptionsWidget::m_pTabWidget private
Referenced by addOptionsWidget(), createTabbedPage(), eventFilter(), and KviOptionsWidget().
QString KviOptionsWidget::m_szBasicTipEnd static private
Referenced by addBoolSelector(), addColorSelector(), addDirectorySelector(), addFileSelector(), addFontSelector(), addMircTextColorSelector(), addPasswordSelector(), addPixmapSelector(), addSoundSelector(), addStringListSelector(), addStringSelector(), addUIntSelector(), and KviOptionsWidget().
QString KviOptionsWidget::m_szBasicTipStart static private
Referenced by addBoolSelector(), addColorSelector(), addDirectorySelector(), addFileSelector(), addFontSelector(), addMircTextColorSelector(), addPasswordSelector(), addPixmapSelector(), addSoundSelector(), addStringListSelector(), addStringSelector(), addUIntSelector(), and KviOptionsWidget().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviOptionsWidget.h
src/kvirc/ui/KviOptionsWidget.cpp