KVIrc: KviKvsPopupManager Class Reference
KviKvsPopupManager Class Reference
#include <KviKvsPopupManager.h>
Signals
void popupRefresh (const QString &szPopupName)
Public Member Functions
void add (const QString &szPopupName, KviKvsPopupMenu *pPopup)
void clear ()
void emitRefresh (const QString &szPopupName)
KviKvsPopupMenu * get (const QString &szPopupName)
void load (const QString &filename)
KviKvsPopupMenu * lookup (const QString &szPopupName)
int popupCount ()
KviPointerHashTable< QString,
KviKvsPopupMenu > * popupDict ()
void remove (const QString &szPopupName)
void save (const QString &filename)
Static Public Member Functions
static void done ()
static void init ()
static KviKvsPopupManager * instance ()
Protected Member Functions
KviKvsPopupManager ()
~KviKvsPopupManager ()
Protected Attributes
KviPointerHashTable< QString,
KviKvsPopupMenu > * m_pPopupDict
Static Protected Attributes
static KviKvsPopupManager * m_pInstance = 0
Constructor & Destructor Documentation
KviKvsPopupManager::KviKvsPopupManager () [protected]
References m_pInstance, m_pPopupDict, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviKvsPopupManager::~KviKvsPopupManager () [protected]
References m_pPopupDict.
Member Function Documentation
void KviKvsPopupManager::add (const QString & szPopupName, KviKvsPopupMenu * pPopup)
References m_pPopupDict, popupRefresh(), and KviPointerHashTable< Key, T >::replace().
Referenced by KviKvsTreeNodeSpecialCommandDefpopup::execute(), get(), and popup_kvs_cmd_create().
void KviKvsPopupManager::clear () [inline]
void KviKvsPopupManager::done () [static]
References instance().
void KviKvsPopupManager::emitRefresh (const QString & szPopupName)
References popupRefresh().
Referenced by KviKvsTreeNodeSpecialCommandDefpopup::execute(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addExtPopup(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addLabel(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_addSeparator(), popup_kvs_cmd_addSubPopup(), popup_kvs_cmd_clear(), popup_kvs_cmd_create(), popup_kvs_cmd_delItem(), and popup_kvs_cmd_destroy().
KviKvsPopupMenu * KviKvsPopupManager::get (const QString & szPopupName)
References add(), lookup(), and m.
Referenced by PopupEditorWidget::commit().
void KviKvsPopupManager::init () [static]
References instance(), and KviKvsPopupManager().
static KviKvsPopupManager* KviKvsPopupManager::instance () [inline, static]
Referenced by KviApplication::checkSuggestRestoreDefaultScript(), PopupEditorWidget::commit(), done(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), KviKvsPopupMenuItemExtMenu::fill(), init(), KviKvsCoreSimpleCommands::KVSCSC(), PopupEditorWidget::oneTimeSetup(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addExtPopup(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addLabel(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_addSeparator(), popup_kvs_cmd_addSubPopup(), popup_kvs_cmd_clear(), popup_kvs_cmd_create(), popup_kvs_cmd_delItem(), popup_kvs_cmd_destroy(), popup_kvs_cmd_show(), popup_kvs_fnc_exists(), and PopupEditorWidget::popupRefresh().
void KviKvsPopupManager::load (const QString & filename)
References KviPointerList< T >::append(), KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviPointerList< T >::first(), KviPointerHashTable< Key, T >::insert(), l, KviKvsPopupMenu::load(), m, m_pPopupDict, KviPointerList< T >::next(), KviConfigurationFile::Read, s, KviPointerList< T >::setAutoDelete(), and KviConfigurationFile::setGroup().
KviKvsPopupMenu* KviKvsPopupManager::lookup (const QString & szPopupName) [inline]
Referenced by KviKvsTreeNodeSpecialCommandDefpopup::execute(), KviKvsPopupMenuItemExtMenu::fill(), get(), KviKvsCoreSimpleCommands::KVSCSC(), popup_kvs_cmd_destroy(), popup_kvs_cmd_show(), and popup_kvs_fnc_exists().
int KviKvsPopupManager::popupCount () [inline]
KviPointerHashTable<QString,KviKvsPopupMenu>* KviKvsPopupManager::popupDict () [inline]
Referenced by PopupEditorWidget::oneTimeSetup(), and PopupEditorWidget::popupRefresh().
void KviKvsPopupManager::popupRefresh (const QString & szPopupName) [signal]
Referenced by add(), and emitRefresh().
void KviKvsPopupManager::remove (const QString & szPopupName) [inline]
Referenced by PopupEditorWidget::commit(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), and popup_kvs_cmd_destroy().
void KviKvsPopupManager::save (const QString & filename)
References KviConfigurationFile::clear(), KviPointerHashTableIterator< Key, T >::current(), m_pPopupDict, KviKvsPopupMenu::popupName(), KviKvsPopupMenu::save(), KviConfigurationFile::setGroup(), and KviConfigurationFile::Write.
Member Data Documentation
KviKvsPopupManager * KviKvsPopupManager::m_pInstance = 0 [static, protected]
Referenced by KviKvsPopupManager().
KviPointerHashTable<QString,KviKvsPopupMenu>* KviKvsPopupManager::m_pPopupDict [protected]
Referenced by add(), KviKvsPopupManager(), load(), save(), and ~KviKvsPopupManager().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsPopupManager.h
src/kvirc/kvs/KviKvsPopupManager.cpp