KVIrc: OptionsWidget_ircViewMarker Class Reference
OptionsWidget_ircViewMarker Class Reference
#include <OptionsWidget_ircView.h>
Public Member Functions
virtual void commit ()
OptionsWidget_ircViewMarker (QWidget *pParent)
~OptionsWidget_ircViewMarker ()
Private Attributes
QComboBox * m_pMarkerStyle
Constructor & Destructor Documentation
OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker (QWidget * pParent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), KVI_OPTION_UINT, KviOption_boolTrackLastReadTextViewLine, KviOption_colorIrcViewMarkLine, KviOption_uintIrcViewMarkerSize, KviOption_uintIrcViewMarkerStyle, m_pMarkerStyle, s, and KviUIntSelector::setSuffix().
OptionsWidget_ircViewMarker::~OptionsWidget_ircViewMarker ()
Member Function Documentation
void OptionsWidget_ircViewMarker::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintIrcViewMarkerStyle, and m_pMarkerStyle.
Member Data Documentation
QComboBox* OptionsWidget_ircViewMarker::m_pMarkerStyle [private]
Referenced by commit(), and OptionsWidget_ircViewMarker().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_ircView.h
src/modules/options/OptionsWidget_ircView.cpp