KVIrc: KviTalListWidgetItem Class Reference
KviTalListWidgetItem Class Reference
#include <KviTalListWidget.h>
Public Member Functions
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Constructor & Destructor Documentation
KviTalListWidgetItem::KviTalListWidgetItem () [inline]
KviTalListWidgetItem::KviTalListWidgetItem (KviTalListWidget * pParent) [inline]
KviTalListWidgetItem::KviTalListWidgetItem (KviTalListWidget * pParent, QString & label) [inline]
virtual KviTalListWidgetItem::~KviTalListWidgetItem () [inline, virtual]
Member Function Documentation
KviTalListWidget* KviTalListWidgetItem::listWidget () [inline]
Referenced by MessageColorListWidgetItem::MessageColorListWidgetItem(), KviImageDialogItem::paint(), KviTalListWidgetPixmap::paint(), and KviTalListWidgetText::paint().
The documentation for this class was generated from the following file:
src/kvilib/tal/KviTalListWidget.h