KVIrc: KvsObject_colorDialog Class Reference
KvsObject_colorDialog Class Reference
#include <KvsObject_colorDialog.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void slotColorSelected (const QColor &col)
void slotCurrentColorChanged (const QColor &col)
Protected Member Functions
bool colorSelectedEvent (KviKvsObjectFunctionCall *c)
bool currentColorChangedEvent (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool setCurrentColor (KviKvsObjectFunctionCall *c)
bool setOptions (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_colorDialog::colorSelectedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_colorDialog::currentColorChangedEvent (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_colorDialog::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_dialog.
References connect(), and d.
bool KvsObject_colorDialog::setCurrentColor (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_colorDialog::setOptions (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_colorDialog::slotColorSelected (const QColor & col) [protected, slot]
References KviKvsObject::callFunction(), and KviKvsHash::set().
void KvsObject_colorDialog::slotCurrentColorChanged (const QColor & col) [protected, slot]
References KviKvsObject::callFunction(), and KviKvsHash::set().
QWidget* KvsObject_colorDialog::widget () [inline]
Reimplemented from KvsObject_dialog.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_colorDialog.h
src/modules/objects/KvsObject_colorDialog.cpp