KVIrc: RegistrationWizard Class Reference
RegistrationWizard Class Reference
#include <RegistrationWizard.h>
Public Member Functions
RegistrationWizard (const QString &startMask, KviRegisteredUserDataBase *db=0, QWidget *par=0, bool bModal=false)
~RegistrationWizard ()
Public Member Functions inherited from KviTalWizard
void addPage (QWidget *pWidget, const QString &szTitle)
QPushButton * backButton ()
QPushButton * cancelButton ()
QWidget * currentPage ()
QPushButton * finishButton ()
QPushButton * helpButton ()
void insertPage (QWidget *pWidget, const QString &szTitle, int iIndex)
KviTalWizard (QWidget *pParent)
QPushButton * nextButton ()
void setBackEnabled (QWidget *pWidget, bool bEnabled)
void setCancelEnabled (QWidget *pWidget, bool bEnabled)
bool setCurrentPage (QWidget *pWidget)
void setFinishEnabled (QWidget *pWidget, bool bEnabled)
void setHelpEnabled (QWidget *pWidget, bool bEnabled)
void setNextEnabled (QWidget *pWidget, bool bEnabled)
bool setPageEnabled (QWidget *pWidget, bool bEnabled)
bool setPageTitle (QWidget *pWidget, const QString &szTitle)
~KviTalWizard ()
Public Attributes
bool m_bModal
KviPixmap * m_pAvatar
KviPixmapSelector * m_pAvatarSelector
KviRegisteredUserDataBase * m_pDb
QLineEdit * m_pEditRealName
QLineEdit * m_pHostEdit1
QLineEdit * m_pHostEdit2
QLabel * m_pLabel1
QLabel * m_pLabel2
QLabel * m_pLabel3
QLabel * m_pLabel4
QLineEdit * m_pNicknameEdit1
QLineEdit * m_pNicknameEdit2
QCheckBox * m_pNotifyCheck
QLineEdit * m_pNotifyNickEdit1
QLineEdit * m_pNotifyNickEdit2
QLabel * m_pNotifyNickLabel1
QLabel * m_pNotifyNickLabel2
QWidget * m_pPage1
QWidget * m_pPage2
QWidget * m_pPage3
QWidget * m_pPage4
QWidget * m_pPage5
QLabel * m_pTextLabel5
QLineEdit * m_pUsernameEdit1
QLineEdit * m_pUsernameEdit2
KviCString m_szStartMask
Protected Slots
void maskChanged (const QString &str)
void notifyCheckToggled (bool)
void notifyNickChanged (const QString &)
void realNameChanged (const QString &str)
Protected Slots inherited from KviTalWizard
void backButtonClicked ()
void cancelButtonClicked ()
void finishButtonClicked ()
void helpButtonClicked ()
void nextButtonClicked ()
Protected Member Functions
virtual void accept ()
virtual void reject ()
virtual void showEvent (QShowEvent *e)
Protected Member Functions inherited from KviTalWizard
virtual void closeEvent (QCloseEvent *e)
void setCurrentPage (KviTalWizardPageData *pData)
Additional Inherited Members
Signals inherited from KviTalWizard
void helpClicked ()
void pageChanged (QString title)
Protected Attributes inherited from KviTalWizard
KviTalWizardPrivate * m_p
Constructor & Destructor Documentation
RegistrationWizard::RegistrationWizard (const QString & startMask, KviRegisteredUserDataBase * db = 0, QWidget * par = 0, bool bModal = false)
References __tr2qs_ctx(), KviTalWizard::addPage(), KviPointerList< T >::append(), connect(), f, g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Linux, m_bModal, m_pAvatar, m_pAvatarSelector, m_pDb, m_pEditRealName, m_pHostEdit1, m_pHostEdit2, m_pLabel1, m_pLabel2, m_pLabel3, m_pLabel4, m_pNicknameEdit1, m_pNicknameEdit2, m_pNotifyCheck, m_pNotifyNickEdit1, m_pNotifyNickEdit2, m_pNotifyNickLabel1, m_pNotifyNickLabel2, m_pPage1, m_pPage2, m_pPage3, m_pPage4, m_pPage5, m_pTextLabel5, m_pUsernameEdit1, m_pUsernameEdit2, maskChanged(), notifyCheckToggled(), notifyNickChanged(), realNameChanged(), and KviTalWizard::setFinishEnabled().
RegistrationWizard::~RegistrationWizard ()
References m_pAvatar, KviPointerList< T >::removeRef(), and KviPointerList< T >::setAutoDelete().
Member Function Documentation
void RegistrationWizard::accept () protected virtual
References KviRegisteredUserDataBase::addMask(), KviRegisteredUserDataBase::addUser(), KviPixmapSelector::commit(), KviRegisteredUserDataBase::findUserByName(), g_pApp, g_pRegisteredUserDataBase, KviPixmap::isNull(), m_pAvatar, m_pAvatarSelector, m_pDb, m_pEditRealName, m_pHostEdit1, m_pHostEdit2, m_pNicknameEdit1, m_pNicknameEdit2, m_pNotifyCheck, m_pNotifyNickEdit1, m_pNotifyNickEdit2, m_pUsernameEdit1, m_pUsernameEdit2, KviPixmap::path(), KviRegisteredUserDataBase::removeMask(), KviApplication::resetAvatarForMatchingUsers(), KviApplication::restartNotifyLists(), KviRegisteredUser::setProperty(), and u.
void RegistrationWizard::maskChanged (const QString & str) protected slot
References KviCString::Format, KviCString::isEmpty(), m_pHostEdit1, m_pNicknameEdit1, m_pPage2, m_pUsernameEdit1, KviCString::ptr(), and KviTalWizard::setNextEnabled().
Referenced by RegistrationWizard().
void RegistrationWizard::notifyCheckToggled (bool) protected slot
References m_pNotifyCheck, m_pNotifyNickEdit1, m_pNotifyNickEdit2, m_pNotifyNickLabel1, m_pNotifyNickLabel2, and notifyNickChanged().
Referenced by RegistrationWizard().
void RegistrationWizard::notifyNickChanged (const QString &) protected slot
References KviCString::hasData(), m_pNotifyCheck, m_pNotifyNickEdit1, m_pNotifyNickEdit2, m_pPage4, and KviTalWizard::setNextEnabled().
Referenced by notifyCheckToggled(), and RegistrationWizard().
void RegistrationWizard::realNameChanged (const QString & str) protected slot
References m_pEditRealName, m_pPage1, and KviTalWizard::setNextEnabled().
Referenced by RegistrationWizard().
void RegistrationWizard::reject () protected virtual
References m_bModal.
void RegistrationWizard::showEvent (QShowEvent * e) protected virtual
Displays the first page if no other page is shown yet.
Reimplemented from KviTalWizard.
References g_pApp, and KviMemory::move().
Member Data Documentation
bool RegistrationWizard::m_bModal
Referenced by RegistrationWizard(), and reject().
KviPixmap* RegistrationWizard::m_pAvatar
Referenced by accept(), RegistrationWizard(), and ~RegistrationWizard().
KviPixmapSelector* RegistrationWizard::m_pAvatarSelector
Referenced by accept(), and RegistrationWizard().
KviRegisteredUserDataBase* RegistrationWizard::m_pDb
Referenced by accept(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pEditRealName
Referenced by accept(), realNameChanged(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pHostEdit1
Referenced by accept(), maskChanged(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pHostEdit2
Referenced by accept(), and RegistrationWizard().
QLabel* RegistrationWizard::m_pLabel1
Referenced by RegistrationWizard().
QLabel* RegistrationWizard::m_pLabel2
Referenced by RegistrationWizard().
QLabel* RegistrationWizard::m_pLabel3
Referenced by RegistrationWizard().
QLabel* RegistrationWizard::m_pLabel4
Referenced by RegistrationWizard().
QLineEdit* RegistrationWizard::m_pNicknameEdit1
Referenced by accept(), maskChanged(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pNicknameEdit2
Referenced by accept(), and RegistrationWizard().
QCheckBox* RegistrationWizard::m_pNotifyCheck
Referenced by accept(), notifyCheckToggled(), notifyNickChanged(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pNotifyNickEdit1
Referenced by accept(), notifyCheckToggled(), notifyNickChanged(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pNotifyNickEdit2
Referenced by accept(), notifyCheckToggled(), notifyNickChanged(), and RegistrationWizard().
QLabel* RegistrationWizard::m_pNotifyNickLabel1
Referenced by notifyCheckToggled(), and RegistrationWizard().
QLabel* RegistrationWizard::m_pNotifyNickLabel2
Referenced by notifyCheckToggled(), and RegistrationWizard().
QWidget* RegistrationWizard::m_pPage1
Referenced by realNameChanged(), and RegistrationWizard().
QWidget* RegistrationWizard::m_pPage2
Referenced by maskChanged(), and RegistrationWizard().
QWidget* RegistrationWizard::m_pPage3
Referenced by RegistrationWizard().
QWidget* RegistrationWizard::m_pPage4
Referenced by notifyNickChanged(), and RegistrationWizard().
QWidget* RegistrationWizard::m_pPage5
Referenced by RegistrationWizard().
QLabel* RegistrationWizard::m_pTextLabel5
Referenced by RegistrationWizard().
QLineEdit* RegistrationWizard::m_pUsernameEdit1
Referenced by accept(), maskChanged(), and RegistrationWizard().
QLineEdit* RegistrationWizard::m_pUsernameEdit2
Referenced by accept(), and RegistrationWizard().
KviCString RegistrationWizard::m_szStartMask
The documentation for this class was generated from the following files:
src/modules/reguser/RegistrationWizard.h
src/modules/reguser/RegistrationWizard.cpp