KVIrc: KviRegisteredChannelDataBase Class Reference
KviRegisteredChannelDataBase Class Reference
#include <KviRegisteredChannelDataBase.h>
Public Member Functions
void add (KviRegisteredChannel *pChan)
QHash< QString,
KviRegisteredChannelList * > * channelDict ()
KviRegisteredChannel * find (const QString &szName, const QString &szNetMask)
KviRegisteredChannel * findExact (const QString &szName, const QString &szNetMask)
KviRegisteredChannelDataBase ()
void load (const QString &szFilename)
void remove (KviRegisteredChannel *pChan)
void save (const QString &szFilename)
~KviRegisteredChannelDataBase ()
Protected Attributes
QHash< QString,
KviRegisteredChannelList * > * m_pChannelDict
Constructor & Destructor Documentation
KviRegisteredChannelDataBase::KviRegisteredChannelDataBase ()
References m_pChannelDict.
KviRegisteredChannelDataBase::~KviRegisteredChannelDataBase ()
References m_pChannelDict.
Member Function Documentation
void KviRegisteredChannelDataBase::add (KviRegisteredChannel * pChan)
References findExact(), KVI_ASSERT, l, m_pChannelDict, KviRegisteredChannel::name(), KviRegisteredChannel::netMask(), o, KviRegisteredChannel::property(), KviRegisteredChannel::propertyDict(), and KviRegisteredChannel::setProperty().
Referenced by load(), and regchan_kvs_cmd_add().
QHash<QString,KviRegisteredChannelList *>* KviRegisteredChannelDataBase::channelDict () [inline]
Referenced by ChannelsJoinDialog::fillListView(), regchan_kvs_cmd_showlist(), and regchan_kvs_fnc_list().
KviRegisteredChannel * KviRegisteredChannelDataBase::find (const QString & szName, const QString & szNetMask)
References c, l, m_pChannelDict, and KviQString::matchWildExpressions().
Referenced by ChannelsJoinDialog::deleteClicked(), regchan_kvs_cmd_remove(), regchan_kvs_cmd_setProperty(), regchan_kvs_fnc_find(), regchan_kvs_fnc_match(), and regchan_kvs_fnc_property().
KviRegisteredChannel * KviRegisteredChannelDataBase::findExact (const QString & szName, const QString & szNetMask)
References c, KviQString::equalCI(), l, and m_pChannelDict.
Referenced by add(), regchan_kvs_cmd_remove(), and regchan_kvs_cmd_setProperty().
void KviRegisteredChannelDataBase::load (const QString & szFilename)
References add(), c, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviQString::cutToLast(), d, KviConfigurationFile::dict(), KviQString::leftToLast(), m_pChannelDict, KviConfigurationFile::Read, s, KviRegisteredChannel::setProperty(), and sit.
Referenced by KviApplication::setup().
void KviRegisteredChannelDataBase::remove (KviRegisteredChannel * pChan)
References KVI_TRACE_FUNCTION, l, m_pChannelDict, and KviRegisteredChannel::name().
Referenced by ChannelsJoinDialog::deleteClicked(), and regchan_kvs_cmd_remove().
void KviRegisteredChannelDataBase::save (const QString & szFilename)
References c, KviConfigurationFile::clear(), KVI_ASSERT, l, m_pChannelDict, KviConfigurationFile::preserveEmptyGroups(), KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveRegisteredChannels().
Member Data Documentation
QHash<QString,KviRegisteredChannelList *>* KviRegisteredChannelDataBase::m_pChannelDict [protected]
Referenced by add(), find(), findExact(), KviRegisteredChannelDataBase(), load(), remove(), save(), and ~KviRegisteredChannelDataBase().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviRegisteredChannelDataBase.h
src/kvilib/ext/KviRegisteredChannelDataBase.cpp