KVIrc: OptionsWidget_sounds Class Reference
OptionsWidget_sounds Class Reference
#include <OptionsWidget_sound.h>
Public Member Functions
OptionsWidget_sounds (QWidget *parent)
~OptionsWidget_sounds ()
Constructor & Destructor Documentation
OptionsWidget_sounds::OptionsWidget_sounds (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addSoundSelector(), KviOptionsWidget::createLayout(), KviOption_stringOnHighlightedMessageSound, KviOption_stringOnMeKickedSound, KviOption_stringOnNewQueryOpenedSound, and KviOption_stringOnQueryMessageSound.
OptionsWidget_sounds::~OptionsWidget_sounds ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_sound.h
src/modules/options/OptionsWidget_sound.cpp