KVIrc: KviKvsTreeNodeAliasSimpleCommand Class Reference
KviKvsTreeNodeAliasSimpleCommand Class Reference
Treenode alias simple command call class.
#include <KviKvsTreeNodeAliasSimpleCommand.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Alias Simple Command.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool execute (KviKvsRunTimeContext *c)
Evaluates the command.
KviKvsTreeNodeAliasSimpleCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *pParams)
Constructs the treenode alias simple command call object.
~KviKvsTreeNodeAliasSimpleCommand ()
Destroys the treenode alias simple command call object.
Public Member Functions inherited from KviKvsTreeNodeSimpleCommand
KviKvsTreeNodeSimpleCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
~KviKvsTreeNodeSimpleCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommandWithParameters
void dumpParameterList (const char *prefix)
KviKvsTreeNodeCommandWithParameters (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
KviKvsTreeNodeDataList * params ()
~KviKvsTreeNodeCommandWithParameters ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Detailed Description
Treenode alias simple command call class.
Constructor & Destructor Documentation
KviKvsTreeNodeAliasSimpleCommand::KviKvsTreeNodeAliasSimpleCommand (const QChar * pLocation, const QString & szCmdName, KviKvsTreeNodeDataList * pParams)
Constructs the treenode alias simple command call object.
Parameters:
pLocation The location char of the instruction
szCmdName The name of the command
pParams The parameters' list
Returns:
KviKvsTreeNodeAliasSimpleCommand
KviKvsTreeNodeAliasSimpleCommand::~KviKvsTreeNodeAliasSimpleCommand ()
Destroys the treenode alias simple command call object.
Member Function Documentation
void KviKvsTreeNodeAliasSimpleCommand::contextDescription (QString & szBuffer) virtual
Sets the buffer as Alias Simple Command.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommand::m_szCmdName.
void KviKvsTreeNodeAliasSimpleCommand::dump (const char * prefix) virtual
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSimpleCommand.
References KviKvsTreeNodeCommandWithParameters::dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), and KviKvsTreeNodeCommand::m_szCmdName.
bool KviKvsTreeNodeAliasSimpleCommand::execute (KviKvsRunTimeContext * c) virtual
Evaluates the command.
Parameters:
c The context where the command is bound to
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsVariantList::allAsString(), KviWindow::connection(), KviWindow::context(), KviMemory::copy(), KviIrcConnection::encodeText(), KviKvsRunTimeContext::error(), KviKvsTreeNodeDataList::evaluate(), KviKvsTreeNodeSwitchList::evaluate(), KviKvsAliasManager::instance(), KVI_OPTION_BOOL, KVI_OUT_RAW, KviOption_boolSendUnknownCommandsAsRaw, l, KviKvsAliasManager::lookup(), KviKvsTreeNodeCommandWithParameters::m_pParams, KviKvsTreeNodeCommand::m_pSwitches, KviKvsTreeNodeCommand::m_szCmdName, KviWindow::output(), KviKvsScript::PreserveParams, KviKvsScript::run(), s, KviIrcConnection::sendData(), swl, KviKvsRunTimeContext::warning(), and KviKvsRunTimeContext::window().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeAliasSimpleCommand.h
src/kvirc/kvs/tree/KviKvsTreeNodeAliasSimpleCommand.cpp