KVIrc: MpInterface Class Reference
MpInterface Class Reference
#include <MpInterface.h>
Public Types
enum PlayerStatus { Unknown, Stopped, Playing, Paused }
Public Member Functions
virtual QString album ()
virtual QString amipEval (const QString &cmd)
virtual bool amipExec (const QString &cmd)
virtual QString artist ()
virtual int bitRate ()
virtual int channels ()
virtual QString comment ()
virtual int detect (bool bStart)=0
virtual QString genre ()
virtual int getEqData (kvs_int_t &i_val)
virtual int getListLength ()
virtual int getPlayListPos ()
virtual bool getRepeat ()
virtual bool getShuffle ()
virtual int getVol ()
virtual bool hide ()
virtual bool jumpTo (kvs_int_t &iPos)
const QString & lastError () const
virtual int length ()
virtual QString mediaType ()
virtual bool minimize ()
MpInterface ()
virtual QString mrl ()=0
virtual bool mute ()
virtual bool next ()=0
virtual QString nowPlaying ()=0
virtual bool pause ()=0
virtual bool play ()=0
virtual bool playMrl (const QString &mrl)
virtual int position ()
virtual bool prev ()=0
virtual bool quit ()
virtual int sampleRate ()
virtual bool setEqData (kvs_int_t &iPos, kvs_int_t &iVal)
void setLastError (const QString &szLastError)
virtual bool setPlayListPos (kvs_int_t &iPos)
virtual bool setRepeat (bool &bVal)
virtual bool setShuffle (bool &bVal)
virtual bool setVol (kvs_int_t &iVol)
virtual bool show ()
virtual MpInterface::PlayerStatus status ()
virtual bool stop ()=0
virtual QString title ()
virtual QString year ()
virtual ~MpInterface ()
Protected Member Functions
QString getLocalFile ()
void notImplemented ()
Protected Attributes
QString m_szLastError
Member Enumeration Documentation
enum MpInterface::PlayerStatus
Enumerator:
Unknown
Stopped
Playing
Paused
Constructor & Destructor Documentation
MpInterface::MpInterface () [inline]
virtual MpInterface::~MpInterface () [inline, virtual]
Member Function Documentation
QString MpInterface::album () [virtual]
References SCAN_MP3_FILE.
QString MpInterface::amipEval (const QString & cmd) [virtual]
Referenced by MP_KVS_FUNCTION().
bool MpInterface::amipExec (const QString & cmd) [virtual]
References notImplemented().
Referenced by MP_KVS_COMMAND().
QString MpInterface::artist () [virtual]
References SCAN_MP3_FILE.
int MpInterface::bitRate () [virtual]
References header_bitrate(), and SCAN_MP3_FILE_RET_INT.
int MpInterface::channels () [virtual]
References header_channels(), and SCAN_MP3_FILE_RET_INT.
QString MpInterface::comment () [virtual]
References SCAN_MP3_FILE.
virtual int MpInterface::detect (bool bStart) [pure virtual]
Implemented in KviXmmsInterface.
Referenced by auto_detect_player().
QString MpInterface::genre () [virtual]
References get_typegenre(), and SCAN_MP3_FILE.
int MpInterface::getEqData (kvs_int_t & i_val) [virtual]
References notImplemented().
Referenced by MP_KVS_FUNCTION().
int MpInterface::getListLength () [virtual]
References notImplemented().
QString MpInterface::getLocalFile () [protected]
References mrl().
int MpInterface::getPlayListPos () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
bool MpInterface::getRepeat () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
bool MpInterface::getShuffle () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
int MpInterface::getVol () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
bool MpInterface::hide () [virtual]
References notImplemented().
bool MpInterface::jumpTo (kvs_int_t & iPos) [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
Referenced by MP_KVS_COMMAND().
const QString& MpInterface::lastError () const [inline]
References m_szLastError.
Referenced by MP_KVS_COMMAND(), and MP_KVS_FUNCTION().
int MpInterface::length () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
QString MpInterface::mediaType () [virtual]
References mrl().
bool MpInterface::minimize () [virtual]
References notImplemented().
virtual QString MpInterface::mrl () [pure virtual]
Implemented in KviXmmsInterface.
Referenced by getLocalFile(), mediaType(), and MP_KVS_FUNCTION().
bool MpInterface::mute () [virtual]
References notImplemented().
virtual bool MpInterface::next () [pure virtual]
Implemented in KviXmmsInterface.
void MpInterface::notImplemented () [protected]
References __tr2qs_ctx(), and setLastError().
Referenced by amipExec(), getEqData(), getListLength(), getPlayListPos(), getRepeat(), getShuffle(), getVol(), hide(), jumpTo(), length(), minimize(), mute(), playMrl(), position(), quit(), setEqData(), setPlayListPos(), setRepeat(), setShuffle(), setVol(), show(), and status().
virtual QString MpInterface::nowPlaying () [pure virtual]
Implemented in KviXmmsInterface.
virtual bool MpInterface::pause () [pure virtual]
Implemented in KviXmmsInterface.
virtual bool MpInterface::play () [pure virtual]
Implemented in KviXmmsInterface.
bool MpInterface::playMrl (const QString & mrl) [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
Referenced by MP_KVS_COMMAND().
int MpInterface::position () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
virtual bool MpInterface::prev () [pure virtual]
Implemented in KviXmmsInterface.
bool MpInterface::quit () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
int MpInterface::sampleRate () [virtual]
References header_frequency(), and SCAN_MP3_FILE_RET_INT.
bool MpInterface::setEqData (kvs_int_t & iPos, kvs_int_t & iVal) [virtual]
References notImplemented().
Referenced by MP_KVS_COMMAND().
void MpInterface::setLastError (const QString & szLastError) [inline]
References m_szLastError.
Referenced by KviXmmsInterface::lookupSymbol(), and notImplemented().
bool MpInterface::setPlayListPos (kvs_int_t & iPos) [virtual]
References notImplemented().
Referenced by MP_KVS_COMMAND().
bool MpInterface::setRepeat (bool & bVal) [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
Referenced by MP_KVS_COMMAND().
bool MpInterface::setShuffle (bool & bVal) [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
Referenced by MP_KVS_COMMAND().
bool MpInterface::setVol (kvs_int_t & iVol) [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented().
Referenced by MP_KVS_COMMAND().
bool MpInterface::show () [virtual]
References notImplemented().
MpInterface::PlayerStatus MpInterface::status () [virtual]
Reimplemented in KviXmmsInterface.
References notImplemented(), and Unknown.
Referenced by MP_KVS_FUNCTION().
virtual bool MpInterface::stop () [pure virtual]
Implemented in KviXmmsInterface.
QString MpInterface::title () [virtual]
References SCAN_MP3_FILE.
QString MpInterface::year () [virtual]
References SCAN_MP3_FILE.
Member Data Documentation
QString MpInterface::m_szLastError [protected]
Referenced by lastError(), and setLastError().
The documentation for this class was generated from the following files:
src/modules/mediaplayer/MpInterface.h
src/modules/mediaplayer/MpInterface.cpp