KVIrc: KviIdentityProfileSet Class Reference
KviIdentityProfileSet Class Reference
Class which manages the list of identity profiles.
#include <KviIdentityProfileSet.h>
Public Member Functions
void addProfile (KviIdentityProfile *pProfile)
Adds a profile to the set.
void clear ()
Clears the list.
void copyFrom (const KviIdentityProfileSet &src)
Carbon copy.
unsigned int count ()
Returns the number of instances of the class.
KviIdentityProfile * findName (const QString &szName)
Searches for a profile name. Returns true if the profile exists.
KviIdentityProfile * findNetwork (const QString &szNetwork)
Searches for a profile network. Returns true if the profile exists.
bool isEmpty ()
Returns true if the profile set is empty.
bool isEnabled ()
Returns true if the profile set is enabled.
KviIdentityProfileSet ()
Constructs the identity profile set object.
KviIdentityProfileSet (const KviIdentityProfileSet &set)
Constructs the identity profile set object.
void load (const QString &szConfigFile)
Loads the configuration of the profiles from file.
KviPointerList
< KviIdentityProfile > * profiles ()
Returns the profiles set.
void save (const QString &szConfigFile)
Saves the configuration of the profiles to file.
void save (KviConfigurationFile *pCfg, const QString &szPrefix)
Saves the configuration of the profiles.
void setEnabled (bool bEnabled)
Enables the profile set.
~KviIdentityProfileSet ()
Destroys the identity profile set object.
Static Public Member Functions
static void done ()
Destroys the class instance.
static void init ()
Initializes the class instance.
static KviIdentityProfileSet * instance ()
Returns the instance of the class.
Protected Member Functions
bool loadPrivate (KviConfigurationFile *pCfg, const QString &szPrefix, unsigned int uEntries)
Loads the configuration of the profiles from file.
Protected Attributes
bool m_bEnabled
KviPointerList
< KviIdentityProfile > * m_pProfiles
Static Private Attributes
static KviIdentityProfileSet * m_pSelf = NULL
static unsigned int m_uCount = 0
Detailed Description
Class which manages the list of identity profiles.
Constructor & Destructor Documentation
KviIdentityProfileSet::KviIdentityProfileSet ()
Constructs the identity profile set object.
Returns
KviIdentityProfileSet
References m_bEnabled, and m_pProfiles.
Referenced by init().
KviIdentityProfileSet::KviIdentityProfileSet (const KviIdentityProfileSet & set)
Constructs the identity profile set object.
This is a carbon copy.
Parameters
set A profile set to copy from
Returns
KviIdentityProfileSet
References copyFrom(), and m_pProfiles.
KviIdentityProfileSet::~KviIdentityProfileSet ()
Destroys the identity profile set object.
References m_pProfiles.
Member Function Documentation
void KviIdentityProfileSet::addProfile (KviIdentityProfile * pProfile)
Adds a profile to the set.
Parameters
pProfile The source profile to add
Returns
void
References KviPointerList< T >::append(), m_pProfiles, and KviPointerList< T >::setAutoDelete().
Referenced by OptionsWidget_identityProfile::commit().
void KviIdentityProfileSet::clear ()
Clears the list.
Returns
void
References m_bEnabled, and m_pProfiles.
Referenced by OptionsWidget_identityProfile::commit(), and load().
void KviIdentityProfileSet::copyFrom (const KviIdentityProfileSet & src)
Carbon copy.
Parameters
src The source profile set
Returns
void
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviIdentityProfile::copyFrom(), KviPointerList< T >::first(), KviPointerList< T >::isEmpty(), m_bEnabled, m_pProfiles, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by KviIdentityProfileSet().
unsigned int KviIdentityProfileSet::count () inline
Returns the number of instances of the class.
Returns
unsigned int
Referenced by done(), and init().
void KviIdentityProfileSet::done () static
Destroys the class instance.
Returns
void
References count(), m_pSelf, and m_uCount.
Referenced by KviApplication::~KviApplication().
KviIdentityProfile * KviIdentityProfileSet::findName (const QString & szName)
Searches for a profile name. Returns true if the profile exists.
Parameters
szName The name of the profile
Returns
KviIdentityProfile *
References KviPointerList< T >::first(), m_pProfiles, KviQString::matchString(), KviIdentityProfile::name(), and KviPointerList< T >::next().
KviIdentityProfile * KviIdentityProfileSet::findNetwork (const QString & szNetwork)
Searches for a profile network. Returns true if the profile exists.
Parameters
szNetwork The network name of the profile
Returns
KviIdentityProfile *
References KviPointerList< T >::first(), m_pProfiles, KviQString::matchString(), KviIdentityProfile::network(), and KviPointerList< T >::next().
Referenced by KviIrcConnection::pickNextLoginNickName(), and KviIrcConnection::useProfileData().
void KviIdentityProfileSet::init () static
Initializes the class instance.
Returns
void
References count(), KviIdentityProfileSet(), m_pSelf, and m_uCount.
Referenced by KviApplication::setup().
static KviIdentityProfileSet* KviIdentityProfileSet::instance () inline static
Returns the instance of the class.
Returns
KviIdentityProfileSet *
Referenced by OptionsWidget_identityProfile::commit(), KviIrcConnection::loginToIrcServer(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), KviIrcConnection::pickNextLoginNickName(), KviApplication::saveIdentityProfiles(), and KviApplication::setup().
bool KviIdentityProfileSet::isEmpty () inline
Returns true if the profile set is empty.
Returns
bool
Referenced by KviIrcConnection::loginToIrcServer(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), and KviIrcConnection::pickNextLoginNickName().
bool KviIdentityProfileSet::isEnabled () inline
Returns true if the profile set is enabled.
Returns
bool
Referenced by KviIrcConnection::loginToIrcServer(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), and KviIrcConnection::pickNextLoginNickName().
void KviIdentityProfileSet::load (const QString & szConfigFile)
Loads the configuration of the profiles from file.
Parameters
szConfigFile The file where to load
Returns
void
References clear(), loadPrivate(), KviConfigurationFile::Read, and KviConfigurationFile::readUIntEntry().
Referenced by KviApplication::setup().
bool KviIdentityProfileSet::loadPrivate (KviConfigurationFile * pCfg, const QString & szPrefix, unsigned int uEntries) protected
Loads the configuration of the profiles from file.
Parameters
pCfg The configuration file
szPrefix The prefix of the rules
uEntries The number of entries
Returns
bool
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviPointerList< T >::isEmpty(), KviIdentityProfile::load(), m_bEnabled, m_pProfiles, KviConfigurationFile::readBoolEntry(), KviPointerList< T >::setAutoDelete(), and u.
Referenced by load().
KviPointerList<KviIdentityProfile>* KviIdentityProfileSet::profiles () inline
Returns the profiles set.
Returns
KviPointerList<KviIdentityProfile> *
Referenced by OptionsWidget_identityProfile::OptionsWidget_identityProfile().
void KviIdentityProfileSet::save (const QString & szConfigFile)
Saves the configuration of the profiles to file.
Parameters
szConfigFile The file to save
Returns
void
References KviConfigurationFile::clear(), and KviConfigurationFile::Write.
Referenced by KviApplication::saveIdentityProfiles().
void KviIdentityProfileSet::save (KviConfigurationFile * pCfg, const QString & szPrefix)
Saves the configuration of the profiles.
Parameters
pCfg The configuration file
szPrefix The prefix of the rules
Returns
void
References KviPointerList< T >::count(), KviPointerList< T >::first(), KviPointerList< T >::isEmpty(), m_bEnabled, m_pProfiles, KviPointerList< T >::next(), and KviConfigurationFile::writeEntry().
void KviIdentityProfileSet::setEnabled (bool bEnabled) inline
Enables the profile set.
Parameters
bEnabled Whether to enable the profile set
Returns
void
Referenced by OptionsWidget_identityProfile::commit().
Member Data Documentation
bool KviIdentityProfileSet::m_bEnabled protected
Referenced by clear(), copyFrom(), KviIdentityProfileSet(), loadPrivate(), and save().
KviPointerList<KviIdentityProfile>* KviIdentityProfileSet::m_pProfiles protected
Referenced by addProfile(), clear(), copyFrom(), findName(), findNetwork(), KviIdentityProfileSet(), loadPrivate(), save(), and ~KviIdentityProfileSet().
KviIdentityProfileSet * KviIdentityProfileSet::m_pSelf = NULL static private
Referenced by done(), and init().
unsigned int KviIdentityProfileSet::m_uCount = 0 static private
Referenced by done(), and init().
The documentation for this class was generated from the following files:
src/kvilib/irc/KviIdentityProfileSet.h
src/kvilib/irc/KviIdentityProfileSet.cpp