KVIrc: OptionsWidget_ignore Class Reference
OptionsWidget_ignore Class Reference
#include <OptionsWidget_ignore.h>
Public Member Functions
OptionsWidget_ignore (QWidget *parent)
~OptionsWidget_ignore ()
Public Attributes
KviBoolSelector * m_pIgnoreNotice
KviBoolSelector * m_pIgnorePrivmsg
KviBoolSelector * m_pVerboseIgnore
Protected Slots
void enableVerbose (bool)
Constructor & Destructor Documentation
OptionsWidget_ignore::OptionsWidget_ignore (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), connect(), KviOptionsWidget::createLayout(), enableVerbose(), g, KVI_OPTION_BOOL, KviOption_boolEnableIgnoreOnNotice, KviOption_boolEnableIgnoreOnPrivMsg, KviOption_boolVerboseIgnore, m_pIgnoreNotice, m_pIgnorePrivmsg, and m_pVerboseIgnore.
OptionsWidget_ignore::~OptionsWidget_ignore ()
Member Function Documentation
void OptionsWidget_ignore::enableVerbose (bool) [protected, slot]
References m_pIgnoreNotice, m_pIgnorePrivmsg, m_pVerboseIgnore, and KviBoolSelector::setEnabled().
Referenced by OptionsWidget_ignore().
Member Data Documentation
KviBoolSelector* OptionsWidget_ignore::m_pIgnoreNotice
Referenced by enableVerbose(), and OptionsWidget_ignore().
KviBoolSelector* OptionsWidget_ignore::m_pIgnorePrivmsg
Referenced by enableVerbose(), and OptionsWidget_ignore().
KviBoolSelector* OptionsWidget_ignore::m_pVerboseIgnore
Referenced by enableVerbose(), and OptionsWidget_ignore().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_ignore.h
src/modules/options/OptionsWidget_ignore.cpp