KVIrc: OptionsWidget_dccSendAdvanced Class Reference
OptionsWidget_dccSendAdvanced Class Reference
#include <OptionsWidget_dcc.h>
Public Member Functions
OptionsWidget_dccSendAdvanced (QWidget *parent)
~OptionsWidget_dccSendAdvanced ()
Constructor & Destructor Documentation
OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolAcceptBrokenFileNameDccResumeRequests, KviOption_boolAcceptMismatchedPortDccResumeRequests, KviOption_boolDCCFileTransferReplaceOutgoingSpacesWithUnderscores, KviOption_boolDccSendForceIdleStep, KviOption_boolLimitDccRecvSpeed, KviOption_boolLimitDccSendSpeed, KviOption_boolSendZeroAckInDccRecv, KviOption_boolUseFastDccSend, KviOption_uintDccSendIdleStepInMSec, KviOption_uintDccSendPacketSize, KviOption_uintMaxDccRecvSpeed, KviOption_uintMaxDccSendSpeed, KviOption_uintMaxDccSendTransfers, KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_dccSendAdvanced::~OptionsWidget_dccSendAdvanced ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_dcc.h
src/modules/options/OptionsWidget_dcc.cpp