KVIrc: UserWindow Class Reference
UserWindow Class Reference
#include <UserWindow.h>
Public Types
enum CreationFlags { HasInput = 1 }
Public Member Functions
void setWindowTitleStrings (const QString &szPlainText)
UserWindow (KviMainWindow *pFrm, const char *pcName, QString &szIcon, KviConsoleWindow *pConsole=0, int iCreationFlags=0)
~UserWindow ()
Protected Member Functions
virtual void fillCaptionBuffers ()
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *)
Protected Attributes
QString m_szIcon
Member Enumeration Documentation
enum UserWindow::CreationFlags
Enumerator:
HasInput
Constructor & Destructor Documentation
UserWindow::UserWindow (KviMainWindow * pFrm, const char * pcName, QString & szIcon, KviConsoleWindow * pConsole = 0, int iCreationFlags = 0)
References KviPointerList< T >::append(), KviWindow::context(), KviWindow::fillSingleColorCaptionBuffers(), HasInput, KviWindow::KviInput, KviWindow::m_pInput, KviWindow::m_pIrcView, m_szIcon, KviWindow::m_szPlainTextCaption, and KviIrcContext::registerContextWindow().
UserWindow::~UserWindow ()
References KviWindow::context(), KviPointerList< T >::removeRef(), and KviIrcContext::unregisterContextWindow().
Member Function Documentation
void UserWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
QPixmap * UserWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getImage(), KviIconManager::getSmallIcon(), and m_szIcon.
void UserWindow::resizeEvent (QResizeEvent *) [protected, virtual]
References KviInput::heightHint(), KviWindow::m_pInput, and KviWindow::m_pIrcView.
void UserWindow::setWindowTitleStrings (const QString & szPlainText)
References KviWindow::m_szPlainTextCaption, and KviWindow::updateCaption().
Member Data Documentation
QString UserWindow::m_szIcon [protected]
Referenced by myIconPtr(), and UserWindow().
The documentation for this class was generated from the following files:
src/modules/window/UserWindow.h
src/modules/window/UserWindow.cpp