KVIrc: KviUserListViewArea Class Reference
KviUserListViewArea Class Reference
User list area management.
#include <KviUserListView.h>
Public Member Functions
int dummyRead () const
A dummy function that always returns 0.
KviUserListViewArea (KviUserListView *pPar)
Constructs the user listview area object.
~KviUserListViewArea ()
Destroys the user listview are object.
Protected Slots
void scrollBarMoved (int iNewVal)
Called when the scrollbar is moved.
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *e)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
virtual void resizeEvent (QResizeEvent *e)
virtual void wheelEvent (QWheelEvent *e)
Protected Attributes
bool m_bIgnoreScrollBar
int m_iLastScrollBarVal
int m_iTopItemOffset
KviUserListEntry * m_pLastEntryUnderMouse
KviUserListView * m_pListView
QScrollBar * m_pScrollBar
Properties
int TransparencyCapable
Friends
class KviUserListView
Detailed Description
User list area management.
Constructor & Destructor Documentation
KviUserListViewArea::KviUserListViewArea (KviUserListView * pPar)
Constructs the user listview area object.
Parameters
pPar The parent widget
Returns
KviUserListViewArea
References connect(), m_bIgnoreScrollBar, m_iLastScrollBarVal, m_iTopItemOffset, m_pLastEntryUnderMouse, m_pListView, m_pScrollBar, and scrollBarMoved().
KviUserListViewArea::~KviUserListViewArea ()
Destroys the user listview are object.
Member Function Documentation
int KviUserListViewArea::dummyRead () const inline
A dummy function that always returns 0.
Returns
int
void KviUserListViewArea::keyPressEvent (QKeyEvent * e) protected virtual
References KviMainWindow::childWindowSelectionStateChange(), KviUserListView::ensureVisible(), g_pMainWindow, i, KviWindow::input(), KviUserListEntry::m_bSelected, KviUserListView::m_iSelectedCount, KviUserListView::m_pHeadItem, KviUserListView::m_pKviWindow, m_pListView, KviUserListEntry::m_pNext, KviUserListEntry::m_pPrev, KviUserListView::m_pTailItem, KviUserListEntry::nick(), KviUserListView::select(), and KviUserListView::selectedCount().
void KviUserListViewArea::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
References KviUserListView::emitDoubleClick(), and m_pListView.
void KviUserListViewArea::mouseMoveEvent (QMouseEvent * e) protected virtual
References KviMainWindow::childWindowSelectionStateChange(), g_pMainWindow, KviUserListView::itemAt(), KVI_USERLIST_BORDER_WIDTH, KviUserListEntry::m_bSelected, KviUserListEntry::m_iHeight, KviUserListView::m_iSelectedCount, m_iTopItemOffset, KviUserListView::m_pHeadItem, KviUserListView::m_pKviWindow, m_pLastEntryUnderMouse, m_pListView, KviUserListEntry::m_pNext, m_pScrollBar, KviUserListView::m_pTailItem, KviUserListView::m_pTopItem, and KviUserListEntry::next().
void KviUserListViewArea::mousePressEvent (QMouseEvent * e) protected virtual
References KviMainWindow::childWindowSelectionStateChange(), KviPointerHashTableIterator< Key, T >::current(), KviUserListView::emitRightClick(), g_pMainWindow, KviUserListView::itemAt(), KviUserListEntry::m_bSelected, KviUserListView::m_iSelectedCount, KviUserListView::m_pEntryDict, KviUserListView::m_pHeadItem, KviUserListView::m_pKviWindow, m_pLastEntryUnderMouse, m_pListView, and KviUserListEntry::m_pNext.
void KviUserListViewArea::mouseReleaseEvent (QMouseEvent * e) protected virtual
References m_pLastEntryUnderMouse.
void KviUserListViewArea::paintEvent (QPaintEvent * e) protected virtual
References KviIrcUserEntry::ChanAdmin, KviIconManager::ChanAdmin, KviIconManager::ChanAdminAway, KviIrcUserEntry::ChanOwner, KviIconManager::ChanOwner, KviIconManager::ChanOwnerAway, KviWindow::connection(), KviIrcConnection::currentNickName(), KviIrcUserDataBase::customColor(), KviPixmapUtils::drawPixmapWithPainter(), g_pApp, g_pIconManager, g_pMainWindow, g_pUserChanStatePixmap, KviIrcUserEntry::gender(), KviIconManager::getSmallIcon(), KviUserListView::getUserFlag(), KviUserListEntry::globalData(), KviIrcUserEntry::HalfOp, KviIconManager::HalfOp, KviIconManager::HalfOpAway, KviIrcUserDataBase::haveCustomColor(), KviIrcUserEntry::isAway(), KviIrcUserEntry::isBot(), KviIrcUserEntry::isIrcOp(), KVI_COLD_TEMPERATURE, KVI_HALF_COLD_TEMPERATURE, KVI_HALF_HOT_TEMPERATURE, KVI_HOT_TEMPERATURE, KVI_MID_TEMPERATURE, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, kvi_time_t, kvi_unixTime, KVI_USERLIST_BORDER_WIDTH, KVI_USERLISTVIEW_GRIDTYPE_3DGRID, KVI_USERLISTVIEW_GRIDTYPE_DOTGRID, KVI_USERLISTVIEW_GRIDTYPE_PLAINGRID, KviOption_boolDrawGenderIcons, KviOption_boolShowAvatarsInUserlist, KviOption_boolShowUserChannelIcons, KviOption_boolShowUserChannelState, KviOption_boolUseCompositingForTransparency, KviOption_boolUseDifferentColorForOwnNick, KviOption_boolUserListViewDrawGrid, KviOption_colorGlobalTransparencyFade, KviOption_colorUserListViewAwayForeground, KviOption_colorUserListViewBackground, KviOption_colorUserListViewChanAdminForeground, KviOption_colorUserListViewChanOwnerForeground, KviOption_colorUserListViewGrid, KviOption_colorUserListViewHalfOpForeground, KviOption_colorUserListViewIrcOpForeground, KviOption_colorUserListViewNormalForeground, KviOption_colorUserListViewOpForeground, KviOption_colorUserListViewOwnForeground, KviOption_colorUserListViewSelectionBackground, KviOption_colorUserListViewSelectionForeground, KviOption_colorUserListViewUserOpForeground, KviOption_colorUserListViewVoiceForeground, KviOption_pixmapUserListViewBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviOption_uintUserListPixmapAlign, KviOption_uintUserListViewGridType, KviUserListEntry::m_bSelected, KviUserListEntry::m_iFlags, KviUserListView::m_iFontHeight, KviUserListEntry::m_iHeight, KviUserListEntry::m_iTemperature, m_iTopItemOffset, KviUserListEntry::m_lastActionTime, KviUserListEntry::m_pAvatarPixmap, KviUserListView::m_pKviWindow, m_pListView, KviUserListEntry::m_pNext, m_pScrollBar, KviUserListView::m_pTopItem, KviUserListEntry::m_szNick, KviIrcUserEntry::Male, KviMainWindow::mdiManager(), KviWindow::mdiParent(), KviIrcUserEntry::Op, KviIconManager::Op, KviIconManager::OpAway, p, KviAnimatedPixmap::pixmap(), r, KviMdiManager::scrollBarsOffset(), KviIconManager::SexBot, KviIconManager::SexFemale, KviIconManager::SexIrcOp, KviIconManager::SexMale, KviApplication::supportsCompositing(), KviIrcUserEntry::Unknown, KviIrcConnection::userDataBase(), KviIconManager::UserOp, KviIconManager::UserOpAway, KviIrcUserEntry::Voice, KviIconManager::Voice, KviIconManager::VoiceAway, and KviUserListView::window().
void KviUserListViewArea::resizeEvent (QResizeEvent * e) protected virtual
References KviUserListView::m_iFontHeight, m_pListView, and m_pScrollBar.
void KviUserListViewArea::scrollBarMoved (int iNewVal) protected slot
Called when the scrollbar is moved.
Parameters
iNewVal The new value of the scrollbar
Returns
void
References m_bIgnoreScrollBar, KviUserListEntry::m_iHeight, m_iLastScrollBarVal, m_iTopItemOffset, m_pListView, KviUserListEntry::m_pNext, KviUserListEntry::m_pPrev, and KviUserListView::m_pTopItem.
Referenced by KviUserListViewArea().
void KviUserListViewArea::wheelEvent (QWheelEvent * e) protected virtual
References g_pApp, and m_pScrollBar.
Friends And Related Function Documentation
friend class KviUserListView friend
Member Data Documentation
bool KviUserListViewArea::m_bIgnoreScrollBar protected
Referenced by KviUserListView::avatarChanged(), KviUserListView::insertUserEntry(), KviUserListViewArea(), KviUserListView::partInternal(), KviUserListView::removeAllEntries(), and scrollBarMoved().
int KviUserListViewArea::m_iLastScrollBarVal protected
Referenced by KviUserListView::avatarChanged(), KviUserListView::ensureVisible(), KviUserListView::insertUserEntry(), KviUserListViewArea(), KviUserListView::partInternal(), KviUserListView::removeAllEntries(), and scrollBarMoved().
int KviUserListViewArea::m_iTopItemOffset protected
Referenced by KviUserListView::animatedAvatarUpdated(), KviUserListView::insertUserEntry(), KviUserListView::itemAt(), KviUserListView::itemVisible(), KviUserListViewArea(), mouseMoveEvent(), paintEvent(), KviUserListView::removeAllEntries(), and scrollBarMoved().
KviUserListEntry* KviUserListViewArea::m_pLastEntryUnderMouse protected
Referenced by KviUserListViewArea(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
KviUserListView* KviUserListViewArea::m_pListView protected
Referenced by keyPressEvent(), KviUserListViewArea(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), paintEvent(), resizeEvent(), and scrollBarMoved().
QScrollBar* KviUserListViewArea::m_pScrollBar protected
Referenced by KviUserListView::applyOptions(), KviUserListView::avatarChanged(), KviUserListView::ensureVisible(), KviUserListView::insertUserEntry(), KviUserListViewArea(), mouseMoveEvent(), paintEvent(), KviUserListView::partInternal(), KviUserListView::removeAllEntries(), resizeEvent(), KviUserListView::updateScrollBarRange(), and wheelEvent().
Property Documentation
int KviUserListViewArea::TransparencyCapable read
The documentation for this class was generated from the following files:
src/kvirc/ui/KviUserListView.h
src/kvirc/ui/KviUserListView.cpp