KVIrc: KviIpEditor Class Reference
KviIpEditor Class Reference
#include <KviIpEditor.h>
Public Types
enum AddressType { IPv4, IPv6 }
Public Member Functions
QString address () const
AddressType addressType () const
void clear ()
bool hasEmptyFields () const
KviIpEditor (QWidget *parent, AddressType=IPv4, const QString &ipAddr=QString(), const char *name=0)
bool setAddress (const QString &ipAddr)
void setAddressType (AddressType addrType)
virtual void setEnabled (bool bEnabled)
~KviIpEditor ()
Protected Member Functions
virtual bool eventFilter (QObject *o, QEvent *e)
virtual void resizeEvent (QResizeEvent *e)
virtual QSize sizeHint () const
Private Member Functions
void recreateChildren ()
Private Attributes
AddressType m_addrType
QLineEdit * m_pEdit [8]
QLabel * m_pLabel [7]
Member Enumeration Documentation
enum KviIpEditor::AddressType
Enumerator:
IPv4
IPv6
Constructor & Destructor Documentation
KviIpEditor::KviIpEditor (QWidget * parent, AddressType addrType = IPv4, const QString & ipAddr = QString(), const char * name = 0)
References i, m_pEdit, m_pLabel, setAddress(), and setAddressType().
KviIpEditor::~KviIpEditor ()
Member Function Documentation
QString KviIpEditor::address () const
References i, IPv6, m_addrType, and m_pEdit.
Referenced by IrcServerDetailsWidget::fillData(), and OptionsWidget_proxy::saveLastItem().
KviIpEditor::AddressType KviIpEditor::addressType () const
References m_addrType.
void KviIpEditor::clear ()
References i, IPv4, m_addrType, and m_pEdit.
Referenced by setAddress().
bool KviIpEditor::eventFilter (QObject * o, QEvent * e) protected virtual
References c, i, IPv4, m_addrType, m_pEdit, and s.
bool KviIpEditor::hasEmptyFields () const
References i, and m_pEdit.
Referenced by IrcServerDetailsWidget::fillData(), and OptionsWidget_proxy::saveLastItem().
void KviIpEditor::recreateChildren () private
References KviHtmlGenerator::Background, i, IPv4, m_addrType, m_pEdit, m_pLabel, resizeEvent(), and sizeHint().
Referenced by setAddressType().
void KviIpEditor::resizeEvent (QResizeEvent * e) protected virtual
References i, IPv4, m_addrType, m_pEdit, and m_pLabel.
Referenced by recreateChildren().
bool KviIpEditor::setAddress (const QString & ipAddr)
References c, clear(), i, IPv4, m_addrType, and m_pEdit.
Referenced by OptionsWidget_proxy::currentItemChanged(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIpEditor().
void KviIpEditor::setAddressType (AddressType addrType)
References IPv4, IPv6, m_addrType, and recreateChildren().
Referenced by OptionsWidget_proxy::currentItemChanged(), OptionsWidget_proxy::ipV6CheckToggled(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviIpEditor(), and IrcServerDetailsWidget::useIPV6CheckToggled().
void KviIpEditor::setEnabled (bool bEnabled) virtual
References KviHtmlGenerator::Background, i, m_pEdit, and m_pLabel.
Referenced by OptionsWidget_proxy::currentItemChanged().
QSize KviIpEditor::sizeHint () const protected virtual
References IPv4, m_addrType, m_pEdit, and m_pLabel.
Referenced by recreateChildren().
Member Data Documentation
AddressType KviIpEditor::m_addrType private
Referenced by address(), addressType(), clear(), eventFilter(), recreateChildren(), resizeEvent(), setAddress(), setAddressType(), and sizeHint().
QLineEdit* KviIpEditor::m_pEdit[8] private
Referenced by address(), clear(), eventFilter(), hasEmptyFields(), KviIpEditor(), recreateChildren(), resizeEvent(), setAddress(), setEnabled(), and sizeHint().
QLabel* KviIpEditor::m_pLabel[7] private
Referenced by KviIpEditor(), recreateChildren(), resizeEvent(), setEnabled(), and sizeHint().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviIpEditor.h
src/kvirc/ui/KviIpEditor.cpp