KVIrc: KviIrcConnectionRequestQueue Class Reference
KviIrcConnectionRequestQueue Class Reference
Class to enqueue commands to IRC server.
#include <KviIrcConnectionRequestQueue.h>
Public Member Functions
void clearAll ()
Clears the queue stack.
void dequeueChannel (KviChannelWindow *pChan)
Removes the channel from the queue stack.
void enqueueChannel (KviChannelWindow *pChan)
Enqueues the channel in the queue stack.
bool isQueued (KviChannelWindow *pChan)
Checks if a channel is in the queue stack.
KviIrcConnectionRequestQueue ()
Constructs the request queue objects.
virtual ~KviIrcConnectionRequestQueue ()
Destroys the request queue objects.
Protected Types
enum RequestTypes {
Mode = 0, BanException = 1, Invite = 2, Who = 3,
QuietBan = 4, Ban = 5
}
Protected Attributes
QQueue< KviChannelWindow * > m_channels
RequestTypes m_curType
QTimer m_timer
Private Slots
void timerSlot ()
Performs time based requests.
Detailed Description
Class to enqueue commands to IRC server.
This class is designed to delay channel requests like MODE and WHO to avoid excess floods on some servers
Member Enumeration Documentation
enum KviIrcConnectionRequestQueue::RequestTypes protected
Warning
MODE s b MUST BE THE LAST AUTOMATIC CHANNEL QUERY so we get RPL_ENDOFBANLIST as the last reply and we know that the channel is in sync
Enumerator
Mode
Channel modes request
BanException
Ban exceptions request
Invite
Invites request
Who
Who request
QuietBan
Quiet ban request
Ban
Ban request
Constructor & Destructor Documentation
KviIrcConnectionRequestQueue::KviIrcConnectionRequestQueue ()
Constructs the request queue objects.
Returns
KviIrcConnectionRequestQueue
References connect(), m_curType, m_timer, Mode, and timerSlot().
KviIrcConnectionRequestQueue::~KviIrcConnectionRequestQueue () virtual
Destroys the request queue objects.
References m_timer, and timerSlot().
Member Function Documentation
void KviIrcConnectionRequestQueue::clearAll ()
Clears the queue stack.
Returns
void
References m_channels, m_curType, m_timer, and Mode.
Referenced by KviIrcContext::connectionTerminated(), and timerSlot().
void KviIrcConnectionRequestQueue::dequeueChannel (KviChannelWindow * pChan)
Removes the channel from the queue stack.
Parameters
pChan The channel to dequeue
Returns
void
References m_channels, and m_timer.
Referenced by KviIrcConnection::unregisterChannel().
void KviIrcConnectionRequestQueue::enqueueChannel (KviChannelWindow * pChan)
Enqueues the channel in the queue stack.
Parameters
pChan The channel to enqueue
Returns
void
References KVI_OPTION_UINT, KviOption_uintOnJoinRequestsDelay, m_channels, and m_timer.
Referenced by KviIrcServerParser::parseLiteralJoin().
bool KviIrcConnectionRequestQueue::isQueued (KviChannelWindow * pChan) inline
Checks if a channel is in the queue stack.
Parameters
pChan The channel to check
Returns
bool
void KviIrcConnectionRequestQueue::timerSlot () private slot
Performs time based requests.
Returns
void
References Ban, BanException, KviChannelWindow::checkChannelSync(), clearAll(), KviWindow::connection(), KviIrcConnection::encodeText(), KviIrcConnectionServerInfo::getNeedsOpToListModeseI(), Invite, KviChannelWindow::isMeOp(), KVI_OPTION_BOOL, kvi_unixTime, KviOption_boolDisableBanExceptionListRequestOnJoin, KviOption_boolDisableBanListRequestOnJoin, KviOption_boolDisableInviteListRequestOnJoin, KviOption_boolDisableQuietBanListRequestOnJoin, KviOption_boolDisableWhoRequestOnJoin, KviLagMeter::lagCheckRegister(), KviIrcConnection::lagMeter(), m_channels, m_curType, m_timer, Mode, KviCString::ptr(), QuietBan, KviIrcConnection::sendFmtData(), KviChannelWindow::serverInfo(), KviIrcConnectionStateData::setLastSentChannelWhoRequest(), KviChannelWindow::setSentListRequest(), KviChannelWindow::setSentWhoRequest(), KviCString::sprintf(), KviIrcConnection::stateData(), KviIrcConnectionServerInfo::supportedListModes(), KviChannelWindow::target(), and Who.
Referenced by KviIrcConnectionRequestQueue(), and ~KviIrcConnectionRequestQueue().
Member Data Documentation
QQueue<KviChannelWindow *> KviIrcConnectionRequestQueue::m_channels protected
Referenced by clearAll(), dequeueChannel(), enqueueChannel(), and timerSlot().
RequestTypes KviIrcConnectionRequestQueue::m_curType protected
Referenced by clearAll(), KviIrcConnectionRequestQueue(), and timerSlot().
QTimer KviIrcConnectionRequestQueue::m_timer protected
Referenced by clearAll(), dequeueChannel(), enqueueChannel(), KviIrcConnectionRequestQueue(), timerSlot(), and ~KviIrcConnectionRequestQueue().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcConnectionRequestQueue.h
src/kvirc/kernel/KviIrcConnectionRequestQueue.cpp