KVIrc: KviKvsTreeNodeModuleCallbackCommand Class Reference
KviKvsTreeNodeModuleCallbackCommand Class Reference
#include <KviKvsTreeNodeModuleCallbackCommand.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeModuleCallbackCommand (const QChar *pLocation, const QString &szModuleName, const QString &szCmdName, KviKvsTreeNodeDataList *params, KviKvsScript *pCallback)
~KviKvsTreeNodeModuleCallbackCommand ()
Public Member Functions inherited from KviKvsTreeNodeCallbackCommand
void dumpCallback (const char *prefix)
KviKvsTreeNodeCallbackCommand (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params, KviKvsScript *pCallback)
~KviKvsTreeNodeCallbackCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommandWithParameters
void dumpParameterList (const char *prefix)
KviKvsTreeNodeCommandWithParameters (const QChar *pLocation, const QString &szCmdName, KviKvsTreeNodeDataList *params)
KviKvsTreeNodeDataList * params ()
~KviKvsTreeNodeCommandWithParameters ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
QString m_szModuleName
Protected Attributes inherited from KviKvsTreeNodeCallbackCommand
KviKvsScript * m_pCallback
Protected Attributes inherited from KviKvsTreeNodeCommandWithParameters
KviKvsTreeNodeDataList * m_pParams
Protected Attributes inherited from KviKvsTreeNodeCommand
KviKvsTreeNodeSwitchList * m_pSwitches
QString m_szCmdName
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNodeCommand
void setSwitchList (KviKvsTreeNodeSwitchList *sw)
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeModuleCallbackCommand::KviKvsTreeNodeModuleCallbackCommand (const QChar * pLocation, const QString & szModuleName, const QString & szCmdName, KviKvsTreeNodeDataList * params, KviKvsScript * pCallback)
References m_szModuleName.
KviKvsTreeNodeModuleCallbackCommand::~KviKvsTreeNodeModuleCallbackCommand () default
Member Function Documentation
void KviKvsTreeNodeModuleCallbackCommand::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeCallbackCommand.
References KviKvsTreeNodeCommand::m_szCmdName, and m_szModuleName.
void KviKvsTreeNodeModuleCallbackCommand::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeCallbackCommand.
References KviKvsTreeNodeCallbackCommand::dumpCallback(), KviKvsTreeNodeCommandWithParameters::dumpParameterList(), KviKvsTreeNodeCommand::dumpSwitchList(), KviKvsTreeNodeCommand::m_szCmdName, and m_szModuleName.
bool KviKvsTreeNodeModuleCallbackCommand::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters
c The source context
Returns
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx(), KviKvsRunTimeContext::error(), KviKvsTreeNodeDataList::evaluate(), KviKvsTreeNodeSwitchList::evaluate(), g_pModuleManager, KviModuleManager::getModule(), KviKvsModuleInterface::kvsFindCallbackCommand(), l, KviModuleManager::lastError(), m, KviKvsTreeNodeCallbackCommand::m_pCallback, KviKvsTreeNodeCommandWithParameters::m_pParams, KviKvsTreeNodeCommand::m_pSwitches, KviKvsTreeNodeCommand::m_szCmdName, m_szModuleName, KviKvsVariantList::setAutoDelete(), KviKvsRunTimeContext::setDefaultReportLocation(), and swl.
Member Data Documentation
QString KviKvsTreeNodeModuleCallbackCommand::m_szModuleName protected
Referenced by contextDescription(), dump(), execute(), and KviKvsTreeNodeModuleCallbackCommand().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeModuleCallbackCommand.h
src/kvirc/kvs/tree/KviKvsTreeNodeModuleCallbackCommand.cpp