KVIrc: KviIdentSentinel Class Reference
KviIdentSentinel Class Reference
#include <libkviident.h>
Public Member Functions
KviIdentSentinel ()
~KviIdentSentinel ()
Protected Member Functions
virtual bool event (QEvent *e)
Constructor & Destructor Documentation
KviIdentSentinel::KviIdentSentinel ()
KviIdentSentinel::~KviIdentSentinel ()
References KviThreadManager::killPendingEvents().
Member Function Documentation
bool KviIdentSentinel::event (QEvent * e) [protected, virtual]
References __tr, _OUTPUT_PARANOIC, _OUTPUT_VERBOSE, KviApplication::activeConsole(), d, g_pActiveWindow, g_pApp, KviCString::hasData(), KVI_IDENT_THREAD_EVENT_EXITING, KVI_IDENT_THREAD_EVENT_EXITING_ON_REQUEST, KVI_OPTION_UINT, KVI_OUT_IDENT, KVI_THREAD_EVENT, KVI_THREAD_EVENT_DATA, KviOption_uintIdentdOutputMode, KviWindow::output(), KviWindow::outputNoFmt(), KviCString::ptr(), KviIdentdOutputMode::Quiet, stopIdentService(), _KviIdentMessageData::szAux, _KviIdentMessageData::szHost, _KviIdentMessageData::szMessage, KviIdentdOutputMode::ToActiveWindow, and _KviIdentMessageData::uPort.
The documentation for this class was generated from the following files:
src/modules/ident/libkviident.h
src/modules/ident/libkviident.cpp