KVIrc: KviKvsTreeNodeSingleParameterIdentifier Class Reference
KviKvsTreeNodeSingleParameterIdentifier Class Reference
#include <KviKvsTreeNodeSingleParameterIdentifier.h>
Public Member Functions
virtual bool canEvaluateToObjectReference ()
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeSingleParameterIdentifier (const QChar *pLocation, int iStart)
~KviKvsTreeNodeSingleParameterIdentifier ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Attributes
int m_iStart
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Constructor & Destructor Documentation
KviKvsTreeNodeSingleParameterIdentifier::KviKvsTreeNodeSingleParameterIdentifier (const QChar * pLocation, int iStart)
References m_iStart.
KviKvsTreeNodeSingleParameterIdentifier::~KviKvsTreeNodeSingleParameterIdentifier ()
Member Function Documentation
bool KviKvsTreeNodeSingleParameterIdentifier::canEvaluateToObjectReference () virtual
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeSingleParameterIdentifier::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
References KviQString::appendFormatted(), and m_iStart.
void KviKvsTreeNodeSingleParameterIdentifier::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
References m_iStart.
bool KviKvsTreeNodeSingleParameterIdentifier::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsVariantList::at(), KviKvsVariant::copyFrom(), m_iStart, KviKvsRunTimeContext::parameterList(), KviKvsVariant::setNothing(), and v.
Member Data Documentation
int KviKvsTreeNodeSingleParameterIdentifier::m_iStart protected
Referenced by contextDescription(), dump(), evaluateReadOnly(), and KviKvsTreeNodeSingleParameterIdentifier().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSingleParameterIdentifier.h
src/kvirc/kvs/tree/KviKvsTreeNodeSingleParameterIdentifier.cpp