KVIrc: KviTalVBox Class Reference
KviTalVBox Class Reference
Toolkit Abstraction Layer: vbox class.
#include <kvi_tal_vbox.h>
Public Member Functions
void addStretch (int iStretch)
Adds the stretch factor.
KviTalVBox (QWidget *pParent, char *pcName=0)
Constructs a vertical box object.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box for a child object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpacing)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalVBox ()
Destroys a vertical box object.
Protected Member Functions
virtual void childEvent (QChildEvent *e)
Private Attributes
QVBoxLayout * m_pLayout
Detailed Description
Toolkit Abstraction Layer: vbox class.
Constructor & Destructor Documentation
KviTalVBox::KviTalVBox (QWidget * pParent, char * pcName = 0)
Constructs a vertical box object.
Parameters:
pParent The parent object
pcName The name of the box
Returns:
KviTalVBox
References m_pLayout.
KviTalVBox::~KviTalVBox ()
Destroys a vertical box object.
Member Function Documentation
void KviTalVBox::addStretch (int iStretch)
Adds the stretch factor.
Parameters:
iStretch The stretch factor
Returns:
void
References m_pLayout.
void KviTalVBox::childEvent (QChildEvent * e) [protected, virtual]
References m_pLayout.
void KviTalVBox::setAlignment (QWidget * pChild, Qt::Alignment alignment)
Sets the alignment of the box for a child object.
Parameters:
pChild The object to align
alignment The alignment
Returns:
void
References m_pLayout.
void KviTalVBox::setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
Parameters:
alignment The alignment
Returns:
void
References m_pLayout.
void KviTalVBox::setMargin (int iMargin)
Sets the margin of the box.
Parameters:
iMargin The margin in pixels
Returns:
void
References m_pLayout.
void KviTalVBox::setSpacing (int iSpacing)
Sets the spacing of the box.
Parameters:
iSpacing The space in pixels
Returns:
void
References m_pLayout.
Referenced by KviChannelListSelector::KviChannelListSelector(), and KviStringListSelector::KviStringListSelector().
void KviTalVBox::setStretchFactor (QWidget * pChild, int iStretch)
Sets the stretch factor for an object.
Parameters:
pChild The object to stretch
iStretch The stretch factor to use
Returns:
void
References m_pLayout.
Referenced by KviChannelListSelector::KviChannelListSelector(), and KviStringListSelector::KviStringListSelector().
Member Data Documentation
QVBoxLayout* KviTalVBox::m_pLayout [private]
Referenced by addStretch(), childEvent(), KviTalVBox(), setAlignment(), setMargin(), setSpacing(), and setStretchFactor().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/tal/kvi_tal_vbox.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/tal/kvi_tal_vbox.cpp