KVIrc: KviKvsTreeNodeOperationArrayAppend Class Reference
KviKvsTreeNodeOperationArrayAppend Class Reference
#include <kvi_kvs_treenode_operation.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeOperationArrayAppend (const QChar *pLocation, KviKvsTreeNodeData *pRightSide)
~KviKvsTreeNodeOperationArrayAppend ()
Protected Attributes
KviKvsTreeNodeData * m_pRightSide
Constructor & Destructor Documentation
KviKvsTreeNodeOperationArrayAppend::KviKvsTreeNodeOperationArrayAppend (const QChar * pLocation, KviKvsTreeNodeData * pRightSide)
References m_pRightSide, and KviKvsTreeNode::setParent().
KviKvsTreeNodeOperationArrayAppend::~KviKvsTreeNodeOperationArrayAppend ()
References m_pRightSide.
Member Function Documentation
void KviKvsTreeNodeOperationArrayAppend::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
void KviKvsTreeNodeOperationArrayAppend::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeOperation.
References KviKvsTreeNodeData::dump(), m_pRightSide, and KviKvsTreeNodeOperation::m_pTargetData.
bool KviKvsTreeNodeOperationArrayAppend::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariantData::Array, KviKvsVariant::array(), KviKvsArray::at(), KviKvsVariant::convertToArray(), KviKvsHash::dict(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsVariant::hash(), KviKvsVariantData::Hash, m_pRightSide, KviKvsTreeNodeOperation::m_pTargetData, KviKvsVariantData::Nothing, KviKvsRWEvaluationResult::result(), s, KviKvsArray::set(), KviKvsArray::size(), and KviKvsVariant::type().
Member Data Documentation
KviKvsTreeNodeData* KviKvsTreeNodeOperationArrayAppend::m_pRightSide [protected]
Referenced by dump(), execute(), KviKvsTreeNodeOperationArrayAppend(), and ~KviKvsTreeNodeOperationArrayAppend().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.cpp