KVIrc: KviKvsObjectFunctionCall Class Reference
KviKvsObjectFunctionCall Class Reference
#include <KviKvsObjectFunctionCall.h>
Public Member Functions
KviKvsObjectFunctionCall (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams, KviKvsVariant *pResult)
KviKvsVariant * returnValue ()
~KviKvsObjectFunctionCall ()
Public Member Functions inherited from KviKvsRunTimeCall
KviKvsRunTimeContext * context ()
void enterBlockingSection ()
bool error (const QString &szFmt,...)
KviKvsVariant * firstParam ()
virtual bool getParameterCode (unsigned int uParamIdx, QString &szParamBuffer)
KviKvsRunTimeCall (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool leaveBlockingSection ()
KviKvsVariant * nextParam ()
unsigned int paramCount ()
unsigned int parameterCount ()
KviKvsVariantList * parameterList ()
KviKvsVariantList * params ()
void warning (const QString &szFmt,...)
KviWindow * window ()
virtual ~KviKvsRunTimeCall ()
Protected Attributes
KviKvsVariant * m_pResult
Protected Attributes inherited from KviKvsRunTimeCall
KviKvsRunTimeContext * m_pContext
KviKvsVariantList * m_pParams
Constructor & Destructor Documentation
KviKvsObjectFunctionCall::KviKvsObjectFunctionCall (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams, KviKvsVariant * pResult) inline
KviKvsObjectFunctionCall::~KviKvsObjectFunctionCall () inline
Member Function Documentation
KviKvsVariant* KviKvsObjectFunctionCall::returnValue () inline
Referenced by KviKvsObjectScriptFunctionHandler::call(), KviKvsObjectStandardTrueReturnFunctionHandler::call(), KviKvsObjectStandardFalseReturnFunctionHandler::call(), KviKvsObjectStandardNothingReturnFunctionHandler::call(), KviKvsObject::function_childCount(), KviKvsObject::function_children(), KviKvsObject::function_className(), KviKvsObject::function_findChild(), KviKvsObject::function_listProperties(), KviKvsObject::function_name(), KviKvsObject::function_parent(), KviKvsObject::function_property(), KviKvsObject::function_setProperty(), KviKvsObject::function_signalName(), KviKvsObject::function_signalSender(), KviKvsObject::function_startTimer(), KvsObject_textedit::functionAtBeginning(), KvsObject_textedit::functionAtEnd(), KvsObject_textedit::functionbold(), KvsObject_http::functionCurrentId(), KvsObject_textedit::functionCursorPosition(), KvsObject_http::functionErrorString(), KvsObject_http::functionGet(), KvsObject_textedit::functionisUndoRedoEnabled(), KvsObject_textedit::functionitalic(), KvsObject_textedit::functionlines(), KvsObject_textedit::functionMaxLines(), KvsObject_textedit::functionModified(), KvsObject_textedit::functionNumLines(), KvsObject_http::functionPost(), KvsObject_http::functionReadAll(), KvsObject_textedit::functionText(), KvsObject_textedit::functiontextFormat(), KvsObject_textedit::functionTextLine(), KvsObject_textedit::functionunderline(), and KvsObject_textedit::functionWordWrap().
Member Data Documentation
KviKvsVariant* KviKvsObjectFunctionCall::m_pResult protected
The documentation for this class was generated from the following file:
src/kvirc/kvs/object/KviKvsObjectFunctionCall.h