KVIrc: OptionsWidget_connection Class Reference
OptionsWidget_connection Class Reference
#include <OptionsWidget_connection.h>
Public Member Functions
OptionsWidget_connection (QWidget *parent)
~OptionsWidget_connection ()
Constructor & Destructor Documentation
OptionsWidget_connection::OptionsWidget_connection (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), KVI_OPTION_BOOL, KviOption_boolAutoReconnectOnUnexpectedDisconnect, KviOption_boolKeepChannelsOpenOnDisconnect, KviOption_boolKeepChannelsOpenOnUnexpectedDisconnect, KviOption_boolKeepQueriesOpenOnDisconnect, KviOption_boolKeepQueriesOpenOnUnexpectedDisconnect, KviOption_boolRejoinChannelsAfterReconnect, KviOption_boolReopenQueriesAfterReconnect, KviOption_uintAutoReconnectDelay, KviOption_uintMaxAutoReconnectAttempts, KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_connection::~OptionsWidget_connection ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_connection.h
src/modules/options/OptionsWidget_connection.cpp