KVIrc: SharedFileEditDialog Class Reference
SharedFileEditDialog Class Reference
#include <SharedFilesWindow.h>
Public Member Functions
KviSharedFile * getResult ()
SharedFileEditDialog (QWidget *par, KviSharedFile *f=0)
~SharedFileEditDialog ()
Public Attributes
QPushButton * m_pBrowseButton
QCheckBox * m_pExpireCheckBox
QDateTimeEdit * m_pExpireDateTimeEdit
QLineEdit * m_pFilePathEdit
QLineEdit * m_pShareNameEdit
QLineEdit * m_pUserMaskEdit
Protected Slots
void browse ()
void okClicked ()
Constructor & Destructor Documentation
SharedFileEditDialog::SharedFileEditDialog (QWidget * par, KviSharedFile * f = 0)
References __tr2qs_ctx(), KviSharedFile::absFilePath(), KviIconManager::Accept, browse(), connect(), KviIconManager::Discard, KviSharedFile::expires(), KviSharedFile::expireTime(), g, g_pIconManager, KviIconManager::getSmallIcon(), l, m_pBrowseButton, m_pExpireCheckBox, m_pExpireDateTimeEdit, m_pFilePathEdit, m_pShareNameEdit, m_pUserMaskEdit, KviSharedFile::name(), okClicked(), and KviSharedFile::userMask().
SharedFileEditDialog::~SharedFileEditDialog ()
Member Function Documentation
void SharedFileEditDialog::browse () [protected, slot]
References __tr2qs, KviFileDialog::askForOpenFileName(), and m_pFilePathEdit.
Referenced by SharedFileEditDialog().
KviSharedFile * SharedFileEditDialog::getResult ()
References f, m_pExpireCheckBox, m_pExpireDateTimeEdit, m_pFilePathEdit, m_pShareNameEdit, and m_pUserMaskEdit.
Referenced by SharedFilesWindow::addClicked().
void SharedFileEditDialog::okClicked () [protected, slot]
References __tr2qs_ctx(), f, m_pExpireCheckBox, m_pExpireDateTimeEdit, m_pFilePathEdit, m_pShareNameEdit, and KviMessageBox::warning().
Referenced by SharedFileEditDialog().
Member Data Documentation
QPushButton* SharedFileEditDialog::m_pBrowseButton
Referenced by SharedFileEditDialog().
QCheckBox* SharedFileEditDialog::m_pExpireCheckBox
Referenced by getResult(), okClicked(), and SharedFileEditDialog().
QDateTimeEdit* SharedFileEditDialog::m_pExpireDateTimeEdit
Referenced by getResult(), okClicked(), and SharedFileEditDialog().
QLineEdit* SharedFileEditDialog::m_pFilePathEdit
Referenced by browse(), getResult(), okClicked(), and SharedFileEditDialog().
QLineEdit* SharedFileEditDialog::m_pShareNameEdit
Referenced by getResult(), okClicked(), and SharedFileEditDialog().
QLineEdit* SharedFileEditDialog::m_pUserMaskEdit
Referenced by getResult(), and SharedFileEditDialog().
The documentation for this class was generated from the following files:
src/modules/sharedfileswindow/SharedFilesWindow.h
src/modules/sharedfileswindow/SharedFilesWindow.cpp