KVIrc: OptionsWidget_channelAdvanced Class Reference
OptionsWidget_channelAdvanced Class Reference
#include <OptionsWidget_channel.h>
Public Member Functions
virtual void commit ()
OptionsWidget_channelAdvanced (QWidget *parent)
~OptionsWidget_channelAdvanced ()
Protected Attributes
QComboBox * m_pBanTypeCombo
Constructor & Destructor Documentation
OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), KviOptionsWidget::addWidgetToLayout(), connect(), KviOptionsWidget::createLayout(), g, i, KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolDisableBanExceptionListRequestOnJoin, KviOption_boolDisableBanListRequestOnJoin, KviOption_boolDisableInviteListRequestOnJoin, KviOption_boolDisableQuietBanListRequestOnJoin, KviOption_boolDisableWhoRequestOnJoin, KviOption_boolEchoNumericTopic, KviOption_boolEnableAwayListUpdates, KviOption_boolLogChannelHistory, KviOption_boolPasteLastLogOnChannelJoin, KviOption_boolShowChannelSyncTime, KviOption_uintDaysIntervalToPasteOnChannelJoin, KviOption_uintDefaultBanType, KviOption_uintLinesToPasteOnChannelJoin, KviOption_uintOnJoinRequestsDelay, m_pBanTypeCombo, KviIrcMask::mask(), KviOptionsWidget::mergeTip(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_channelAdvanced::~OptionsWidget_channelAdvanced ()
Member Function Documentation
void OptionsWidget_channelAdvanced::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintDefaultBanType, and m_pBanTypeCombo.
Member Data Documentation
QComboBox* OptionsWidget_channelAdvanced::m_pBanTypeCombo [protected]
Referenced by commit(), and OptionsWidget_channelAdvanced().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_channel.h
src/modules/options/OptionsWidget_channel.cpp