KVIrc: KviTreeWindowListItem Class Reference
KviTreeWindowListItem Class Reference
#include <KviTreeWindowList.h>
Public Member Functions
virtual void applyOptions ()
virtual void captionChanged ()
virtual void highlight (int iLevel=1)
virtual QString key () const
KviTreeWindowListItem (QTreeWidget *par, KviWindow *wnd)
KviTreeWindowListItem (KviTreeWindowListItem *par, KviWindow *wnd)
virtual void setProgress (int progress)
virtual void unhighlight ()
~KviTreeWindowListItem ()
Public Member Functions inherited from KviWindowListItem
virtual bool active ()
int highlightLevel ()
KviWindow * kviWindow ()
KviWindowListItem (KviWindow *wnd)
int progress ()
virtual ~KviWindowListItem ()
Protected Member Functions
bool operator< (const QTreeWidgetItem &other) const
void setActive (bool bActive)
Friends
class KviTreeWindowList
class KviTreeWindowListItemInternal
class KviTreeWindowListTreeWidget
Additional Inherited Members
Protected Attributes inherited from KviWindowListItem
int m_iHighlightLevel
int m_iProgress
KviWindow * m_pWindow
Constructor & Destructor Documentation
KviTreeWindowListItem::KviTreeWindowListItem (QTreeWidget * par, KviWindow * wnd)
References applyOptions().
KviTreeWindowListItem::KviTreeWindowListItem (KviTreeWindowListItem * par, KviWindow * wnd)
References applyOptions().
KviTreeWindowListItem::~KviTreeWindowListItem () default
Member Function Documentation
void KviTreeWindowListItem::applyOptions () virtual
Referenced by KviTreeWindowListItem().
void KviTreeWindowListItem::captionChanged () virtual
Reimplemented from KviWindowListItem.
References KviWindow::Channel, KviWindow::Console, KviWindow::DeadChannel, KviWindow::DeadQuery, KviWindowListBase::getTextForConsole(), KviWindowListItem::m_pWindow, KviWindow::plainTextCaption(), KviWindow::Query, KviWindow::type(), and KviWindow::windowName().
void KviTreeWindowListItem::highlight (int iLevel = 1) virtual
Reimplemented from KviWindowListItem.
References g_pMainWindow, KVI_TTBID_HIGHLIGHT, KviWindowListItem::m_iHighlightLevel, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
QString KviTreeWindowListItem::key () const virtual
References KviWindow::Channel, KviWindow::Console, KviWindow::DeadChannel, KviWindow::DeadQuery, KviWindowListBase::getTextForConsole(), KVI_OPTION_BOOL, KviOption_boolSortWindowListItemsByName, KviWindowListItem::m_pWindow, KviWindow::Query, KviWindow::type(), and KviWindow::windowName().
bool KviTreeWindowListItem::operator< (const QTreeWidgetItem & other) const inline protected
void KviTreeWindowListItem::setActive (bool bActive) protected
References unhighlight().
void KviTreeWindowListItem::setProgress (int progress) virtual
Reimplemented from KviWindowListItem.
References KVI_TTBID_PROGRESS, KviWindowListItem::m_iProgress, and KviWindowListItem::progress().
void KviTreeWindowListItem::unhighlight () virtual
Reimplemented from KviWindowListItem.
References g_pMainWindow, KVI_TTBID_HIGHLIGHT, KviWindowListItem::m_iHighlightLevel, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
Referenced by setActive().
Friends And Related Function Documentation
friend class KviTreeWindowList friend
friend class KviTreeWindowListItemInternal friend
friend class KviTreeWindowListTreeWidget friend
The documentation for this class was generated from the following files:
src/kvirc/ui/KviTreeWindowList.h
src/kvirc/ui/KviTreeWindowList.cpp