KVIrc: KviTalListWidgetPixmap Class Reference
KviTalListWidgetPixmap Class Reference
#include <KviTalListWidget.h>
Public Types
enum { RTTI = 2 }
Public Member Functions
int height (const KviTalListWidget *) const
KviTalListWidgetPixmap (KviTalListWidget *listbox, const QPixmap &)
KviTalListWidgetPixmap (const QPixmap &)
KviTalListWidgetPixmap (KviTalListWidget *listbox, const QPixmap &, const QString &)
KviTalListWidgetPixmap (const QPixmap &, const QString &)
const QPixmap * pixmap () const
int rtti () const
int width (const KviTalListWidget *) const
~KviTalListWidgetPixmap ()
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Protected Member Functions
virtual void paint (QPainter *)
Private Attributes
QPixmap pm
Member Enumeration Documentation
anonymous enum
Enumerator:
RTTI
Constructor & Destructor Documentation
KviTalListWidgetPixmap::KviTalListWidgetPixmap (KviTalListWidget * listbox, const QPixmap & pixmap)
References pixmap(), and pm.
KviTalListWidgetPixmap::KviTalListWidgetPixmap (const QPixmap & pixmap)
References pixmap(), and pm.
KviTalListWidgetPixmap::KviTalListWidgetPixmap (KviTalListWidget * listbox, const QPixmap & pix, const QString & text)
References pm.
KviTalListWidgetPixmap::KviTalListWidgetPixmap (const QPixmap & pix, const QString & text)
References pm.
KviTalListWidgetPixmap::~KviTalListWidgetPixmap ()
Member Function Documentation
int KviTalListWidgetPixmap::height (const KviTalListWidget * lb) const
Reimplemented in KviImageDialogItem.
References h, and pm.
Referenced by paint().
void KviTalListWidgetPixmap::paint (QPainter * painter) protected virtual
Reimplemented in KviImageDialogItem.
References height(), KviTalListWidgetItem::listWidget(), pixmap(), and pm.
const QPixmap* KviTalListWidgetPixmap::pixmap () const inline
Referenced by KviImageDialogItem::height(), KviTalListWidgetPixmap(), KviImageDialogItem::paint(), paint(), and KviImageDialogItem::width().
int KviTalListWidgetPixmap::rtti () const
References RTTI.
int KviTalListWidgetPixmap::width (const KviTalListWidget * lb) const
Reimplemented in KviImageDialogItem.
References pm.
Member Data Documentation
QPixmap KviTalListWidgetPixmap::pm private
Referenced by height(), KviTalListWidgetPixmap(), KviImageDialogItem::paint(), paint(), and width().
The documentation for this class was generated from the following files:
src/kvilib/tal/KviTalListWidget.h
src/kvilib/tal/KviTalListWidget.cpp