KVIrc: PackAddonDialog Class Reference
PackAddonDialog Class Reference
Wizard for addon creation.
#include <PackAddonDialog.h>
Public Member Functions
PackAddonDialog (QWidget *pParent)
Creates the wizard object.
~PackAddonDialog ()
Destroys the wizard object.
Protected Member Functions
virtual void accept ()
Runs the packAddon() function and closes the wizard.
bool checkDirTree (QString *pszError)
Ensures the sources directory is complete.
bool createInstaller (QString *pszError)
Creates the installer file.
bool packAddon ()
Creates the addon package.
Protected Attributes
PackAddonFileSelectionWidget * m_pPackAddonFileSelectionWidget
PackAddonInfoPackageWidget * m_pPackAddonInfoPackageWidget
PackAddonSaveSelectionWidget * m_pPackAddonSaveSelectionWidget
PackAddonSummaryFilesWidget * m_pPackAddonSummaryFilesWidget
PackAddonSummaryInfoWidget * m_pPackAddonSummaryInfoWidget
QString m_szAuthor
QString m_szDescription
QString m_szDirPath
QString m_szIcon
QString m_szMinVersion
QString m_szName
QString m_szSavePath
QString m_szVersion
Detailed Description
Wizard for addon creation.
Constructor & Destructor Documentation
PackAddonDialog::PackAddonDialog (QWidget * pParent)
Creates the wizard object.
Parameters:
pParent The parent widget
Returns:
PackAddonDialog
References __tr2qs_ctx(), g_pIconManager, KviIconManager::getBigIcon(), m_pPackAddonFileSelectionWidget, m_pPackAddonInfoPackageWidget, m_pPackAddonSaveSelectionWidget, and m_pPackAddonSummaryInfoWidget.
PackAddonDialog::~PackAddonDialog ()
Destroys the wizard object.
Member Function Documentation
void PackAddonDialog::accept () [protected, virtual]
Runs the packAddon() function and closes the wizard.
Returns:
void
References packAddon().
bool PackAddonDialog::checkDirTree (QString * pszError) [protected]
Ensures the sources directory is complete.
Parameters:
pszError The buffer containing errors
Returns:
bool
References __tr2qs_ctx(), init(), and m_szDirPath.
Referenced by packAddon().
bool PackAddonDialog::createInstaller (QString * pszError) [protected]
Creates the installer file.
Parameters:
pszError The buffer containing errors
Returns:
bool
bool PackAddonDialog::packAddon () [protected]
Creates the addon package.
Returns:
bool
References __tr2qs_ctx(), KviPackageWriter::addDirectory(), KviPackageWriter::addFile(), KviPackageWriter::addInfoField(), checkDirTree(), KviQString::ensureLastCharIs(), KviMessageBox::information(), KVI_CURRENT_ADDONS_ENGINE_VERSION, KVI_FILEEXTENSION_ADDONPACKAGE, KVI_PATH_SEPARATOR_CHAR, KVI_SOURCES_DATE, KVI_VERSION, KviPackageIOEngine::lastError(), m_pPackAddonSummaryFilesWidget, m_szAuthor, m_szDescription, m_szDirPath, m_szIcon, m_szMinVersion, m_szName, m_szSavePath, m_szVersion, KviPackageWriter::pack(), and PackAddonSummaryFilesWidget::setPath().
Referenced by accept().
Member Data Documentation
PackAddonFileSelectionWidget* PackAddonDialog::m_pPackAddonFileSelectionWidget [protected]
Referenced by PackAddonDialog().
PackAddonInfoPackageWidget* PackAddonDialog::m_pPackAddonInfoPackageWidget [protected]
Referenced by PackAddonDialog().
PackAddonSaveSelectionWidget* PackAddonDialog::m_pPackAddonSaveSelectionWidget [protected]
Referenced by PackAddonDialog().
PackAddonSummaryFilesWidget* PackAddonDialog::m_pPackAddonSummaryFilesWidget [protected]
Referenced by packAddon().
PackAddonSummaryInfoWidget* PackAddonDialog::m_pPackAddonSummaryInfoWidget [protected]
Referenced by PackAddonDialog().
QString PackAddonDialog::m_szAuthor [protected]
Referenced by packAddon().
QString PackAddonDialog::m_szDescription [protected]
Referenced by packAddon().
QString PackAddonDialog::m_szDirPath [protected]
Referenced by checkDirTree(), and packAddon().
QString PackAddonDialog::m_szIcon [protected]
Referenced by packAddon().
QString PackAddonDialog::m_szMinVersion [protected]
Referenced by packAddon().
QString PackAddonDialog::m_szName [protected]
Referenced by packAddon().
QString PackAddonDialog::m_szSavePath [protected]
Referenced by packAddon().
QString PackAddonDialog::m_szVersion [protected]
Referenced by packAddon().
The documentation for this class was generated from the following files:
src/modules/addon/PackAddonDialog.h
src/modules/addon/PackAddonDialog.cpp