KVIrc: Kopete::AV::VideoDevice Class Reference
Kopete::AV::VideoDevice Class Reference
#include <videodevice.h>
Public Member Functions
bool canAsyncIO ()
bool canCapture ()
bool canChromakey ()
bool canOverlay ()
bool canRead ()
bool canScale ()
bool canStream ()
virtual int close ()
Closes the device.
int currentInput ()
int detectPixelFormats ()
int detectSignalStandards ()
QString fileName ()
int getControlValue (quint32 ctrl_id, qint32 *value)
Reads the value of a video-control.
virtual int getFrame ()
virtual int getFrame (imagebuffer *imgbuffer)
virtual int getImage (QImage *qimage)
QList< ActionVideoControl > getSupportedActionControls ()
Returns the supported action-controls for the current input.
QList< BooleanVideoControl > getSupportedBooleanControls ()
Returns the supported boolean controls for the current input.
QList< MenuVideoControl > getSupportedMenuControls ()
Returns the supported menu-controls for the current input.
QList< NumericVideoControl > getSupportedNumericControls ()
Returns the supported numeric controls for the current input.
int height ()
int inputs ()
virtual bool isOpen ()
int maxHeight ()
int maxWidth ()
int minHeight ()
int minWidth ()
virtual int open ()
int pixelFormatCode (pixel_format pixelformat)
int pixelFormatDepth (pixel_format pixelformat)
pixel_format pixelFormatForPalette (int palette)
QString pixelFormatName (pixel_format pixelformat)
QString pixelFormatName (int pixelformat)
int selectInput (int input)
int setControlValue (quint32 ctrl_id, qint32 value)
Sets the value of a video-control.
int setFileName (QString filename)
virtual pixel_format setPixelFormat (pixel_format newformat)
virtual int setSize (int newwidth, int newheight)
void setUdi (const QString &)
int showDeviceCapabilities ()
__u64 signalStandardCode (signal_standard standard)
QString signalStandardName (signal_standard standard)
QString signalStandardName (int standard)
virtual int startCapturing ()
virtual int stopCapturing ()
QString udi () const
VideoDevice ()
int width ()
virtual ~VideoDevice ()
Public Attributes
QVector< Kopete::AV::VideoInput > m_input
QString m_name
Protected Types
enum imgctrl_id {
IMGCTRL_ID_V4L1_BRIGHTNESS, IMGCTRL_ID_V4L1_HUE, IMGCTRL_ID_V4L1_COLOR, IMGCTRL_ID_V4L1_CONTRAST,
IMGCTRL_ID_V4L1_WHITENESS, IMGCTRL_ID_SOFT_AUTOBRIGHTNESSCONTRASTCORR, IMGCTRL_ID_SOFT_AUTOCOLORCORR, IMGCTRL_ID_SOFT_VFLIP,
IMGCTRL_ID_SOFT_HFLIP
}
Protected Member Functions
virtual int checkDevice ()
int errnoReturn (const char *s)
virtual int initDevice ()
int initMmap ()
int initRead ()
int initUserptr ()
void setupControls ()
Sets up the supported video-controls for the current input.
int xioctl (int request, void *arg)
Protected Attributes
int currentheight
int currentwidth
int descriptor
QString full_filename
QList< ActionVideoControl > m_actionCtrls
QList< BooleanVideoControl > m_booleanCtrls
int m_buffer_size
int m_current_input
imagebuffer m_currentbuffer
videodev_driver m_driver
io_method m_io_method
QList< MenuVideoControl > m_menuCtrls
QString m_model
QList< NumericVideoControl > m_numericCtrls
pixel_format m_pixelformat
QVector< rawbuffer > m_rawbuffers
unsigned int m_streambuffers
QString m_udi
bool m_videoasyncio
bool m_videocapture
bool m_videochromakey
bool m_videooverlay
bool m_videoread
bool m_videoscale
bool m_videostream
int maxheight
int maxwidth
int minheight
int minwidth
Member Enumeration Documentation
enum Kopete::AV::VideoDevice::imgctrl_id protected
Enumerator:
IMGCTRL_ID_V4L1_BRIGHTNESS
IMGCTRL_ID_V4L1_HUE
IMGCTRL_ID_V4L1_COLOR
IMGCTRL_ID_V4L1_CONTRAST
IMGCTRL_ID_V4L1_WHITENESS
IMGCTRL_ID_SOFT_AUTOBRIGHTNESSCONTRASTCORR
IMGCTRL_ID_SOFT_AUTOCOLORCORR
IMGCTRL_ID_SOFT_VFLIP
IMGCTRL_ID_SOFT_HFLIP
Constructor & Destructor Documentation
Kopete::AV::VideoDevice::VideoDevice ()
References descriptor, m_current_input, and m_streambuffers.
Kopete::AV::VideoDevice::~VideoDevice () virtual
References close().
Member Function Documentation
bool Kopete::AV::VideoDevice::canAsyncIO ()
References m_videoasyncio.
Referenced by showDeviceCapabilities().
bool Kopete::AV::VideoDevice::canCapture ()
References m_videocapture.
Referenced by showDeviceCapabilities().
bool Kopete::AV::VideoDevice::canChromakey ()
References m_videochromakey.
Referenced by showDeviceCapabilities().
bool Kopete::AV::VideoDevice::canOverlay ()
References m_videooverlay.
Referenced by showDeviceCapabilities().
bool Kopete::AV::VideoDevice::canRead ()
References m_videoread.
Referenced by showDeviceCapabilities().
bool Kopete::AV::VideoDevice::canScale ()
References m_videoscale.
Referenced by showDeviceCapabilities().
bool Kopete::AV::VideoDevice::canStream ()
References m_videostream.
Referenced by showDeviceCapabilities().
int Kopete::AV::VideoDevice::checkDevice () protected virtual
References CLEAR, detectPixelFormats(), detectSignalStandards(), full_filename, Kopete::AV::VideoInput::hastuner, isOpen(), m_driver, m_input, m_model, m_name, Kopete::AV::VideoInput::m_standards, m_videoasyncio, m_videocapture, m_videochromakey, m_videooverlay, m_videoread, m_videoscale, m_videostream, maxheight, maxwidth, minheight, minwidth, Kopete::AV::VideoInput::name, pixelFormatName(), Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
Referenced by open().
int Kopete::AV::VideoDevice::close () virtual
Closes the device.
Returns:
The success of the operation: EXIT_SUCCESS or EXIT_FAILURE Stops capturing, resets internal data and closes the device.
References descriptor, isOpen(), m_actionCtrls, m_booleanCtrls, m_driver, m_menuCtrls, m_numericCtrls, stopCapturing(), and Kopete::AV::VIDEODEV_DRIVER_NONE.
Referenced by open(), and ~VideoDevice().
int Kopete::AV::VideoDevice::currentInput ()
Todo:
implement me
References isOpen(), and m_current_input.
int Kopete::AV::VideoDevice::detectPixelFormats ()
References m_driver, Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, Kopete::AV::PIXELFORMAT_YYUV, pixelFormatName(), setPixelFormat(), Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
Referenced by checkDevice().
int Kopete::AV::VideoDevice::detectSignalStandards ()
this must be done once for each input.
References isOpen(), m_driver, signalStandardName(), Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
Referenced by checkDevice().
int Kopete::AV::VideoDevice::errnoReturn (const char * s) protected
Todo:
implement me
Referenced by getFrame(), initMmap(), initUserptr(), startCapturing(), and stopCapturing().
QString Kopete::AV::VideoDevice::fileName ()
References full_filename.
int Kopete::AV::VideoDevice::getControlValue (quint32 ctrl_id, qint32 * value)
Reads the value of a video-control.
Parameters:
ctrl_id ID of the video-control
value Pointer to the variable, which recieves the value of the querried video-control. For boolean controls, the value is 0 or 1. For menu-controls, the value is the index of the currently selected option.
Returns:
The result-code, currently EXIT_SUCCESS or EXIT_FAILURE
References CLEAR, IMGCTRL_ID_SOFT_AUTOBRIGHTNESSCONTRASTCORR, IMGCTRL_ID_SOFT_AUTOCOLORCORR, IMGCTRL_ID_SOFT_HFLIP, IMGCTRL_ID_SOFT_VFLIP, IMGCTRL_ID_V4L1_BRIGHTNESS, IMGCTRL_ID_V4L1_COLOR, IMGCTRL_ID_V4L1_CONTRAST, IMGCTRL_ID_V4L1_HUE, IMGCTRL_ID_V4L1_WHITENESS, isOpen(), m_current_input, m_driver, m_input, Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
int Kopete::AV::VideoDevice::getFrame () virtual
Todo:
implement me
References CLEAR, Kopete::AV::imagebuffer::data, descriptor, errnoReturn(), i, Kopete::AV::IO_METHOD_MMAP, Kopete::AV::IO_METHOD_NONE, Kopete::AV::IO_METHOD_READ, Kopete::AV::IO_METHOD_USERPTR, isOpen(), m_currentbuffer, m_io_method, m_rawbuffers, m_streambuffers, and xioctl().
Referenced by getFrame().
int Kopete::AV::VideoDevice::getFrame (imagebuffer * imgbuffer) virtual
References Kopete::AV::imagebuffer::data, getFrame(), Kopete::AV::imagebuffer::height, m_currentbuffer, Kopete::AV::imagebuffer::pixelformat, and Kopete::AV::imagebuffer::width.
int Kopete::AV::VideoDevice::getImage (QImage * qimage) virtual
Todo:
implement me
References bayer2rgb24(), c, d, Kopete::AV::imagebuffer::data, e, KviMemory::free(), g, height(), m_current_input, m_currentbuffer, m_input, p, Kopete::AV::imagebuffer::pixelformat, Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, Kopete::AV::PIXELFORMAT_YYUV, r, s, sonix_decompress(), sonix_decompress_init(), width(), x, and y.
QList< ActionVideoControl > Kopete::AV::VideoDevice::getSupportedActionControls ()
Returns the supported action-controls for the current input.
Returns:
A list of all supported action-controls for the current input
References m_actionCtrls.
QList< BooleanVideoControl > Kopete::AV::VideoDevice::getSupportedBooleanControls ()
Returns the supported boolean controls for the current input.
Returns:
A list of all supported boolean controls for the current input
References m_booleanCtrls.
QList< MenuVideoControl > Kopete::AV::VideoDevice::getSupportedMenuControls ()
Returns the supported menu-controls for the current input.
Returns:
A list of all supported menu-controls for the current input
References m_menuCtrls.
QList< NumericVideoControl > Kopete::AV::VideoDevice::getSupportedNumericControls ()
Returns the supported numeric controls for the current input.
Returns:
A list of all supported numeric controls for the current input
References m_numericCtrls.
int Kopete::AV::VideoDevice::height ()
References currentheight.
Referenced by getImage(), and setSize().
int Kopete::AV::VideoDevice::initDevice () protected virtual
Todo:
implement me
References CLEAR, descriptor, full_filename, Kopete::AV::IO_METHOD_MMAP, Kopete::AV::IO_METHOD_NONE, Kopete::AV::IO_METHOD_READ, m_driver, m_io_method, m_videoasyncio, m_videoread, m_videostream, showDeviceCapabilities(), Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
Referenced by open().
int Kopete::AV::VideoDevice::initMmap () protected
Todo:
implement me
References BUFFERS, CLEAR, Kopete::AV::imagebuffer::data, descriptor, errnoReturn(), full_filename, isOpen(), m_currentbuffer, m_rawbuffers, m_streambuffers, NULL, and xioctl().
Referenced by setSize().
int Kopete::AV::VideoDevice::initRead () protected
Todo:
implement me
References isOpen(), m_buffer_size, and m_rawbuffers.
Referenced by setSize().
int Kopete::AV::VideoDevice::initUserptr () protected
Todo:
implement me
References CLEAR, errnoReturn(), full_filename, isOpen(), m_buffer_size, m_rawbuffers, m_streambuffers, and xioctl().
Referenced by setSize().
int Kopete::AV::VideoDevice::inputs ()
References m_input.
Referenced by selectInput(), and showDeviceCapabilities().
bool Kopete::AV::VideoDevice::isOpen () virtual
References descriptor.
Referenced by checkDevice(), close(), currentInput(), detectSignalStandards(), getControlValue(), getFrame(), initMmap(), initRead(), initUserptr(), open(), selectInput(), setControlValue(), setSize(), showDeviceCapabilities(), startCapturing(), and stopCapturing().
int Kopete::AV::VideoDevice::maxHeight ()
References maxheight.
Referenced by showDeviceCapabilities().
int Kopete::AV::VideoDevice::maxWidth ()
References maxwidth.
Referenced by showDeviceCapabilities().
int Kopete::AV::VideoDevice::minHeight ()
References minheight.
Referenced by showDeviceCapabilities().
int Kopete::AV::VideoDevice::minWidth ()
References minwidth.
Referenced by showDeviceCapabilities().
int Kopete::AV::VideoDevice::open () virtual
Todo:
implement me
References checkDevice(), close(), descriptor, full_filename, initDevice(), isOpen(), m_current_input, and selectInput().
int Kopete::AV::VideoDevice::pixelFormatCode (pixel_format pixelformat)
References m_driver, Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, Kopete::AV::PIXELFORMAT_YYUV, and Kopete::AV::VIDEODEV_DRIVER_NONE.
Referenced by setPixelFormat().
int Kopete::AV::VideoDevice::pixelFormatDepth (pixel_format pixelformat)
References Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, and Kopete::AV::PIXELFORMAT_YYUV.
Referenced by setPixelFormat(), and setSize().
pixel_format Kopete::AV::VideoDevice::pixelFormatForPalette (int palette)
References m_driver, Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, Kopete::AV::PIXELFORMAT_YYUV, and Kopete::AV::VIDEODEV_DRIVER_NONE.
Referenced by setPixelFormat().
QString Kopete::AV::VideoDevice::pixelFormatName (pixel_format pixelformat)
References Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, and Kopete::AV::PIXELFORMAT_YYUV.
Referenced by checkDevice(), detectPixelFormats(), pixelFormatName(), and setSize().
QString Kopete::AV::VideoDevice::pixelFormatName (int pixelformat)
References m_driver, Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_DV, Kopete::AV::PIXELFORMAT_ET61X251, Kopete::AV::PIXELFORMAT_GREY, Kopete::AV::PIXELFORMAT_HI240, Kopete::AV::PIXELFORMAT_HM12, Kopete::AV::PIXELFORMAT_JPEG, Kopete::AV::PIXELFORMAT_MJPEG, Kopete::AV::PIXELFORMAT_MPEG, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_PWC1, Kopete::AV::PIXELFORMAT_PWC2, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_RGB332, Kopete::AV::PIXELFORMAT_RGB444, Kopete::AV::PIXELFORMAT_RGB555, Kopete::AV::PIXELFORMAT_RGB555X, Kopete::AV::PIXELFORMAT_RGB565, Kopete::AV::PIXELFORMAT_RGB565X, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_WNVA, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, Kopete::AV::PIXELFORMAT_YYUV, pixelFormatName(), and Kopete::AV::VIDEODEV_DRIVER_NONE.
int Kopete::AV::VideoDevice::selectInput (int input)
Todo:
implement me
References descriptor, inputs(), isOpen(), m_current_input, m_driver, m_input, setupControls(), and Kopete::AV::VIDEODEV_DRIVER_NONE.
Referenced by open().
int Kopete::AV::VideoDevice::setControlValue (quint32 ctrl_id, qint32 value)
Sets the value of a video-control.
Parameters:
ctrl_id ID of the video-control
value The value that should be set. For boolean controls, the value must be 0 or 1. For menu-controls, the value must be the index of the option. For action-controls, the value is ignored.
Returns:
The result-code, currently EXIT_SUCCESS or EXIT_FAILURE
References CLEAR, IMGCTRL_ID_SOFT_AUTOBRIGHTNESSCONTRASTCORR, IMGCTRL_ID_SOFT_AUTOCOLORCORR, IMGCTRL_ID_SOFT_HFLIP, IMGCTRL_ID_SOFT_VFLIP, IMGCTRL_ID_V4L1_BRIGHTNESS, IMGCTRL_ID_V4L1_COLOR, IMGCTRL_ID_V4L1_CONTRAST, IMGCTRL_ID_V4L1_HUE, IMGCTRL_ID_V4L1_WHITENESS, isOpen(), m_current_input, m_driver, m_input, Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
int Kopete::AV::VideoDevice::setFileName (QString filename)
Todo:
implement me
References full_filename.
pixel_format Kopete::AV::VideoDevice::setPixelFormat (pixel_format newformat) virtual
References m_driver, m_pixelformat, Kopete::AV::PIXELFORMAT_NONE, pixelFormatCode(), pixelFormatDepth(), pixelFormatForPalette(), Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
Referenced by detectPixelFormats(), and setSize().
int Kopete::AV::VideoDevice::setSize (int newwidth, int newheight) virtual
References currentheight, currentwidth, Kopete::AV::imagebuffer::data, height(), initMmap(), initRead(), initUserptr(), Kopete::AV::IO_METHOD_MMAP, Kopete::AV::IO_METHOD_NONE, Kopete::AV::IO_METHOD_READ, Kopete::AV::IO_METHOD_USERPTR, isOpen(), m_buffer_size, m_currentbuffer, m_driver, m_io_method, m_pixelformat, maxheight, maxwidth, minheight, minwidth, Kopete::AV::imagebuffer::pixelformat, Kopete::AV::PIXELFORMAT_BGR24, Kopete::AV::PIXELFORMAT_BGR32, Kopete::AV::PIXELFORMAT_NONE, Kopete::AV::PIXELFORMAT_RGB24, Kopete::AV::PIXELFORMAT_RGB32, Kopete::AV::PIXELFORMAT_SBGGR8, Kopete::AV::PIXELFORMAT_SN9C10X, Kopete::AV::PIXELFORMAT_UYVY, Kopete::AV::PIXELFORMAT_YUV420P, Kopete::AV::PIXELFORMAT_YUV422P, Kopete::AV::PIXELFORMAT_YUYV, pixelFormatDepth(), pixelFormatName(), setPixelFormat(), Kopete::AV::VIDEODEV_DRIVER_NONE, width(), and xioctl().
void Kopete::AV::VideoDevice::setUdi (const QString & udi)
References m_udi, and udi().
void Kopete::AV::VideoDevice::setupControls () protected
Sets up the supported video-controls for the current input.
Determines which video-controls are supported for the current input, reads all needed informations about them and stores the data to the local members
References __tr, CLEAR, Kopete::AV::ActionVideoControl::id, IMGCTRL_ID_SOFT_AUTOBRIGHTNESSCONTRASTCORR, IMGCTRL_ID_SOFT_AUTOCOLORCORR, IMGCTRL_ID_SOFT_HFLIP, IMGCTRL_ID_SOFT_VFLIP, IMGCTRL_ID_V4L1_BRIGHTNESS, IMGCTRL_ID_V4L1_COLOR, IMGCTRL_ID_V4L1_CONTRAST, IMGCTRL_ID_V4L1_HUE, IMGCTRL_ID_V4L1_WHITENESS, k, m_actionCtrls, m_booleanCtrls, m_driver, m_menuCtrls, m_numericCtrls, Kopete::AV::ActionVideoControl::name, Kopete::AV::BooleanVideoControl::value_default, Kopete::AV::NumericVideoControl::value_max, Kopete::AV::NumericVideoControl::value_min, Kopete::AV::NumericVideoControl::value_step, Kopete::AV::VIDEODEV_DRIVER_NONE, and xioctl().
Referenced by selectInput().
int Kopete::AV::VideoDevice::showDeviceCapabilities ()
References canAsyncIO(), canCapture(), canChromakey(), canOverlay(), canRead(), canScale(), canStream(), inputs(), isOpen(), m_input, m_model, m_name, maxHeight(), maxWidth(), minHeight(), and minWidth().
Referenced by initDevice().
__u64 Kopete::AV::VideoDevice::signalStandardCode (signal_standard standard)
References m_driver, Kopete::AV::STANDARD_525_60, Kopete::AV::STANDARD_625_50, Kopete::AV::STANDARD_ALL, Kopete::AV::STANDARD_ATSC, Kopete::AV::STANDARD_ATSC_16_VSB, Kopete::AV::STANDARD_ATSC_8_VSB, Kopete::AV::STANDARD_B, Kopete::AV::STANDARD_DK, Kopete::AV::STANDARD_GH, Kopete::AV::STANDARD_MN, Kopete::AV::STANDARD_NTSC, Kopete::AV::STANDARD_NTSC_443, Kopete::AV::STANDARD_NTSC_M, Kopete::AV::STANDARD_NTSC_M_JP, Kopete::AV::STANDARD_NTSC_M_KR, Kopete::AV::STANDARD_PAL, Kopete::AV::STANDARD_PAL_60, Kopete::AV::STANDARD_PAL_B, Kopete::AV::STANDARD_PAL_B1, Kopete::AV::STANDARD_PAL_BG, Kopete::AV::STANDARD_PAL_D, Kopete::AV::STANDARD_PAL_D1, Kopete::AV::STANDARD_PAL_DK, Kopete::AV::STANDARD_PAL_G, Kopete::AV::STANDARD_PAL_H, Kopete::AV::STANDARD_PAL_I, Kopete::AV::STANDARD_PAL_K, Kopete::AV::STANDARD_PAL_M, Kopete::AV::STANDARD_PAL_N, Kopete::AV::STANDARD_PAL_Nc, Kopete::AV::STANDARD_SECAM, Kopete::AV::STANDARD_SECAM_B, Kopete::AV::STANDARD_SECAM_D, Kopete::AV::STANDARD_SECAM_DK, Kopete::AV::STANDARD_SECAM_G, Kopete::AV::STANDARD_SECAM_H, Kopete::AV::STANDARD_SECAM_K, Kopete::AV::STANDARD_SECAM_K1, Kopete::AV::STANDARD_SECAM_L, Kopete::AV::STANDARD_SECAM_LC, Kopete::AV::STANDARD_UNKNOWN, and Kopete::AV::VIDEODEV_DRIVER_NONE.
QString Kopete::AV::VideoDevice::signalStandardName (signal_standard standard)
References Kopete::AV::STANDARD_525_60, Kopete::AV::STANDARD_625_50, Kopete::AV::STANDARD_ALL, Kopete::AV::STANDARD_ATSC, Kopete::AV::STANDARD_ATSC_16_VSB, Kopete::AV::STANDARD_ATSC_8_VSB, Kopete::AV::STANDARD_B, Kopete::AV::STANDARD_DK, Kopete::AV::STANDARD_GH, Kopete::AV::STANDARD_MN, Kopete::AV::STANDARD_NTSC, Kopete::AV::STANDARD_NTSC_443, Kopete::AV::STANDARD_NTSC_M, Kopete::AV::STANDARD_NTSC_M_JP, Kopete::AV::STANDARD_NTSC_M_KR, Kopete::AV::STANDARD_PAL, Kopete::AV::STANDARD_PAL_60, Kopete::AV::STANDARD_PAL_B, Kopete::AV::STANDARD_PAL_B1, Kopete::AV::STANDARD_PAL_BG, Kopete::AV::STANDARD_PAL_D, Kopete::AV::STANDARD_PAL_D1, Kopete::AV::STANDARD_PAL_DK, Kopete::AV::STANDARD_PAL_G, Kopete::AV::STANDARD_PAL_H, Kopete::AV::STANDARD_PAL_I, Kopete::AV::STANDARD_PAL_K, Kopete::AV::STANDARD_PAL_M, Kopete::AV::STANDARD_PAL_N, Kopete::AV::STANDARD_PAL_Nc, Kopete::AV::STANDARD_SECAM, Kopete::AV::STANDARD_SECAM_B, Kopete::AV::STANDARD_SECAM_D, Kopete::AV::STANDARD_SECAM_DK, Kopete::AV::STANDARD_SECAM_G, Kopete::AV::STANDARD_SECAM_H, Kopete::AV::STANDARD_SECAM_K, Kopete::AV::STANDARD_SECAM_K1, Kopete::AV::STANDARD_SECAM_L, Kopete::AV::STANDARD_SECAM_LC, and Kopete::AV::STANDARD_UNKNOWN.
Referenced by detectSignalStandards(), and signalStandardName().
QString Kopete::AV::VideoDevice::signalStandardName (int standard)
References m_driver, signalStandardName(), Kopete::AV::STANDARD_525_60, Kopete::AV::STANDARD_625_50, Kopete::AV::STANDARD_ALL, Kopete::AV::STANDARD_ATSC, Kopete::AV::STANDARD_ATSC_16_VSB, Kopete::AV::STANDARD_ATSC_8_VSB, Kopete::AV::STANDARD_B, Kopete::AV::STANDARD_DK, Kopete::AV::STANDARD_GH, Kopete::AV::STANDARD_MN, Kopete::AV::STANDARD_NTSC, Kopete::AV::STANDARD_NTSC_443, Kopete::AV::STANDARD_NTSC_M, Kopete::AV::STANDARD_NTSC_M_JP, Kopete::AV::STANDARD_NTSC_M_KR, Kopete::AV::STANDARD_PAL, Kopete::AV::STANDARD_PAL_60, Kopete::AV::STANDARD_PAL_B, Kopete::AV::STANDARD_PAL_B1, Kopete::AV::STANDARD_PAL_BG, Kopete::AV::STANDARD_PAL_D, Kopete::AV::STANDARD_PAL_D1, Kopete::AV::STANDARD_PAL_DK, Kopete::AV::STANDARD_PAL_G, Kopete::AV::STANDARD_PAL_H, Kopete::AV::STANDARD_PAL_I, Kopete::AV::STANDARD_PAL_K, Kopete::AV::STANDARD_PAL_M, Kopete::AV::STANDARD_PAL_N, Kopete::AV::STANDARD_PAL_Nc, Kopete::AV::STANDARD_SECAM, Kopete::AV::STANDARD_SECAM_B, Kopete::AV::STANDARD_SECAM_D, Kopete::AV::STANDARD_SECAM_DK, Kopete::AV::STANDARD_SECAM_G, Kopete::AV::STANDARD_SECAM_H, Kopete::AV::STANDARD_SECAM_K, Kopete::AV::STANDARD_SECAM_K1, Kopete::AV::STANDARD_SECAM_L, Kopete::AV::STANDARD_SECAM_LC, Kopete::AV::STANDARD_UNKNOWN, VIDEO_MODE_NTSC_JP, VIDEO_MODE_PAL_M, VIDEO_MODE_PAL_N, and Kopete::AV::VIDEODEV_DRIVER_NONE.
int Kopete::AV::VideoDevice::startCapturing () virtual
References CLEAR, errnoReturn(), Kopete::AV::IO_METHOD_MMAP, Kopete::AV::IO_METHOD_NONE, Kopete::AV::IO_METHOD_READ, Kopete::AV::IO_METHOD_USERPTR, isOpen(), m_io_method, m_rawbuffers, m_streambuffers, KviOsInfo::type(), and xioctl().
int Kopete::AV::VideoDevice::stopCapturing () virtual
Todo:
implement me
References errnoReturn(), Kopete::AV::IO_METHOD_MMAP, Kopete::AV::IO_METHOD_NONE, Kopete::AV::IO_METHOD_READ, Kopete::AV::IO_METHOD_USERPTR, isOpen(), m_io_method, m_rawbuffers, m_streambuffers, KviOsInfo::type(), and xioctl().
Referenced by close().
QString Kopete::AV::VideoDevice::udi () const
References m_udi.
Referenced by Kopete::AV::VideoDevicePool::deviceRemoved(), and setUdi().
int Kopete::AV::VideoDevice::width ()
References currentwidth.
Referenced by getImage(), and setSize().
int Kopete::AV::VideoDevice::xioctl (int request, void * arg) protected
References descriptor, and r.
Referenced by checkDevice(), detectPixelFormats(), detectSignalStandards(), getControlValue(), getFrame(), initDevice(), initMmap(), initUserptr(), setControlValue(), setPixelFormat(), setSize(), setupControls(), startCapturing(), and stopCapturing().
Member Data Documentation
int Kopete::AV::VideoDevice::currentheight protected
Referenced by height(), and setSize().
int Kopete::AV::VideoDevice::currentwidth protected
Referenced by setSize(), and width().
int Kopete::AV::VideoDevice::descriptor protected
Referenced by close(), getFrame(), initDevice(), initMmap(), isOpen(), open(), selectInput(), VideoDevice(), and xioctl().
QString Kopete::AV::VideoDevice::full_filename protected
Referenced by checkDevice(), fileName(), initDevice(), initMmap(), initUserptr(), open(), and setFileName().
QList<ActionVideoControl> Kopete::AV::VideoDevice::m_actionCtrls protected
Supported action-controls for the current input
Referenced by close(), getSupportedActionControls(), and setupControls().
QList<BooleanVideoControl> Kopete::AV::VideoDevice::m_booleanCtrls protected
Supported boolean controls for the current input
Referenced by close(), getSupportedBooleanControls(), and setupControls().
int Kopete::AV::VideoDevice::m_buffer_size protected
Referenced by initRead(), initUserptr(), and setSize().
int Kopete::AV::VideoDevice::m_current_input protected
Referenced by currentInput(), getControlValue(), getImage(), open(), selectInput(), setControlValue(), and VideoDevice().
imagebuffer Kopete::AV::VideoDevice::m_currentbuffer protected
Referenced by getFrame(), getImage(), initMmap(), and setSize().
videodev_driver Kopete::AV::VideoDevice::m_driver protected
Referenced by checkDevice(), close(), detectPixelFormats(), detectSignalStandards(), getControlValue(), initDevice(), pixelFormatCode(), pixelFormatForPalette(), pixelFormatName(), selectInput(), setControlValue(), setPixelFormat(), setSize(), setupControls(), signalStandardCode(), and signalStandardName().
QVector<Kopete::AV::VideoInput> Kopete::AV::VideoDevice::m_input
Referenced by checkDevice(), getControlValue(), getImage(), inputs(), selectInput(), setControlValue(), and showDeviceCapabilities().
io_method Kopete::AV::VideoDevice::m_io_method protected
Referenced by getFrame(), initDevice(), setSize(), startCapturing(), and stopCapturing().
QList<MenuVideoControl> Kopete::AV::VideoDevice::m_menuCtrls protected
Supported menu-controls for the current input
Referenced by close(), getSupportedMenuControls(), and setupControls().
QString Kopete::AV::VideoDevice::m_model protected
Referenced by checkDevice(), and showDeviceCapabilities().
QString Kopete::AV::VideoDevice::m_name
Referenced by checkDevice(), and showDeviceCapabilities().
QList<NumericVideoControl> Kopete::AV::VideoDevice::m_numericCtrls protected
Supported muneric controls for the current input
Referenced by close(), getSupportedNumericControls(), and setupControls().
pixel_format Kopete::AV::VideoDevice::m_pixelformat protected
Referenced by setPixelFormat(), and setSize().
QVector<rawbuffer> Kopete::AV::VideoDevice::m_rawbuffers protected
Referenced by getFrame(), initMmap(), initRead(), initUserptr(), startCapturing(), and stopCapturing().
unsigned int Kopete::AV::VideoDevice::m_streambuffers protected
Referenced by getFrame(), initMmap(), initUserptr(), startCapturing(), stopCapturing(), and VideoDevice().
QString Kopete::AV::VideoDevice::m_udi protected
Referenced by setUdi(), and udi().
bool Kopete::AV::VideoDevice::m_videoasyncio protected
Referenced by canAsyncIO(), checkDevice(), and initDevice().
bool Kopete::AV::VideoDevice::m_videocapture protected
Referenced by canCapture(), and checkDevice().
bool Kopete::AV::VideoDevice::m_videochromakey protected
Referenced by canChromakey(), and checkDevice().
bool Kopete::AV::VideoDevice::m_videooverlay protected
Referenced by canOverlay(), and checkDevice().
bool Kopete::AV::VideoDevice::m_videoread protected
Referenced by canRead(), checkDevice(), and initDevice().
bool Kopete::AV::VideoDevice::m_videoscale protected
Referenced by canScale(), and checkDevice().
bool Kopete::AV::VideoDevice::m_videostream protected
Referenced by canStream(), checkDevice(), and initDevice().
int Kopete::AV::VideoDevice::maxheight protected
Referenced by checkDevice(), maxHeight(), and setSize().
int Kopete::AV::VideoDevice::maxwidth protected
Referenced by checkDevice(), maxWidth(), and setSize().
int Kopete::AV::VideoDevice::minheight protected
Referenced by checkDevice(), minHeight(), and setSize().
int Kopete::AV::VideoDevice::minwidth protected
Referenced by checkDevice(), minWidth(), and setSize().
The documentation for this class was generated from the following files:
src/kvilib/ext/avdevice/videodevice.h
src/kvilib/ext/avdevice/videodevice.cpp