KVIrc: KvsObject_spinBox Class Reference
KvsObject_spinBox Class Reference
#include <KvsObject_spinBox.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void valueChanged (int)
Protected Member Functions
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool lineStep (KviKvsObjectFunctionCall *c)
bool maxValue (KviKvsObjectFunctionCall *c)
bool minValue (KviKvsObjectFunctionCall *c)
bool setLineStep (KviKvsObjectFunctionCall *c)
bool setMaxValue (KviKvsObjectFunctionCall *c)
bool setMinValue (KviKvsObjectFunctionCall *c)
bool setPrefix (KviKvsObjectFunctionCall *c)
bool setSpecialValueText (KviKvsObjectFunctionCall *c)
bool setSuffix (KviKvsObjectFunctionCall *c)
bool setTracking (KviKvsObjectFunctionCall *c)
bool setValue (KviKvsObjectFunctionCall *c)
bool specialValueText (KviKvsObjectFunctionCall *c)
bool value (KviKvsObjectFunctionCall *c)
bool valueChangedEvent (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_spinBox::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_spinBox::lineStep (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::maxValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::minValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setLineStep (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setMaxValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setMinValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setPrefix (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setSpecialValueText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setSuffix (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setTracking (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::setValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::specialValueText (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_spinBox::value (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_spinBox::valueChanged (int value) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_spinBox::valueChangedEvent (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_spinBox::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_spinBox.h
src/modules/objects/KvsObject_spinBox.cpp