KVIrc: KviKvsAction Class Reference
KviKvsAction Class Reference
This class handles the actions.
#include <KviKvsAction.h>
Public Member Functions
virtual void activate ()
Executes the action.
KviKvsAction (QObject *pParent, const QString &szName, const QString &szScriptCode, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Contructs the action object.
const QString & scriptCode ()
Returns the code of the script contained in the action.
virtual ~KviKvsAction ()
Destroys the action object.
Public Member Functions inherited from KviAction
virtual QAction * addToCustomToolBar (KviCustomToolBar *pParentToolBar)
Adds the action to the given toolbar.
virtual bool addToPopupMenu (QMenu *pMenu)
Adds the action to the given popup.
QPixmap * bigIcon ()
Returns the big icon associated to the action.
const QString & bigIconId () const
Returns the id of the big icon associated to the action.
KviActionCategory * category () const
Returns the category of the action.
virtual const QString & description ()
Returns the description of the action.
unsigned int flags ()
Returns the flag associated to the action.
bool isEnabled () const
Returns true if the action is enabled.
virtual bool isKviUserActionNeverOverrideThis ()
Returns true if the action is user-defined.
const QString & keySequence () const
Returns the shortcut of the action.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const QString &szSmallIconId=QString(), unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
KviAction (QObject *pParent, const QString &szName, const QString &szVisibleName, const QString &szDescription, KviActionCategory *pCategory=NULL, const QString &szBigIconId=QString(), const KviIconManager::SmallIcon eIcon=KviIconManager::None, unsigned int uFlags=0, const QString &szKeySequence=QString())
Constructs the action object.
const QString & name () const
Returns the name of the action.
virtual void setEnabled (bool bEnabled)
Enables the action.
QPixmap * smallIcon ()
Returns the small icon associated to the action.
const QString & smallIconId () const
Returns the id of the small icon associated to the action.
void suicide ()
Destroys itself. Maybe the best function in the whole APIs :)
virtual const QString & visibleName ()
Returns the visible name of the action.
virtual ~KviAction ()
Destroys the action object.
Protected Attributes
QString m_szScript
Protected Attributes inherited from KviAction
QString m_eIcon
QPointer< QShortcut > m_pAccel
KviPointerList< QAction > * m_pActionList
KviActionCategory * m_pCategory
QString m_szBigIconId
QString m_szDescription
QString m_szKeySequence
QString m_szName
QString m_szSmallIconId
QString m_szVisibleName
unsigned int m_uFlags
unsigned short int m_uInternalFlags
Additional Inherited Members
Public Types inherited from KviAction
enum Flags {
NeedsContext = 1, NeedsConnection = 2, WindowConsole = 4, WindowChannel = 8,
WindowQuery = 16, WindowDccChat = 32, InternalWindowMask = WindowConsole | WindowChannel | WindowQuery | WindowDccChat, EnableAtLogin = 64,
WindowOnlyIfUsersSelected = 128
}
Holds the flags of an action.
enum InternalFlags { Enabled = 1, SetupDone = 2 }
Holds the internal flags of an action.
Public Slots inherited from KviAction
Signals inherited from KviAction
void activated ()
Emitted when the action is being activated.
Static Public Member Functions inherited from KviAction
static int validateFlags (int iFlagsToValidate)
Validates the flags of the action.
Protected Slots inherited from KviAction
virtual void actionDestroyed ()
Removes the action from the list.
virtual void activeContextChanged ()
Enables or disables the action upon checking the active context.
virtual void activeContextStateChanged ()
Enables or disables the action upon checking the active context.
virtual void activeWindowChanged ()
Enables or disables the action upon checking the active window.
virtual void activeWindowSelectionStateChanged (bool bSelectedNow)
Enables or disables the action upon checking the active window.
virtual void reloadImages ()
Reloads the images.
Protected Member Functions inherited from KviAction
KviPointerList< QAction > * actionList ()
Returns the list of actions associated to the action.
void registerAccelerator ()
Registers the action shortcut in the application.
void registerAction (QAction *pAction)
Adds the action to the list.
virtual void setup ()
Enables or disables the action upon starting KVIrc.
bool setupDone () const
Returns true if the setup is finished.
void unregisterAccelerator ()
Removes the action shortcut from the application.
Detailed Description
This class handles the actions.
Constructor & Destructor Documentation
KviKvsAction::KviKvsAction (QObject * pParent, const QString & szName, const QString & szScriptCode, const QString & szVisibleName, const QString & szDescription, KviActionCategory * pCategory = NULL, const QString & szBigIconId = QString(), const QString & szSmallIconId = QString(), unsigned int uFlags = 0, const QString & szKeySequence = QString())
Contructs the action object.
Parameters:
pParent The parent object
szName The name of the action
szScriptCode The code of the script contained in the action
szVisibleName Permanent visible name, visible at least in the action drawer
szDescription The description of the action
pCategory One of KviActionManager::category*() or 0 (default category)
szBigIconId The id of a big icon (32x32)
szSmallIconId The id of a small icon (16x16)
uFlags Flags of the action like connection needed, context needed, ...
szKeySequence The shortcut to activate the action
Returns:
KviKvsAction
References m_szScript.
KviKvsAction::~KviKvsAction () virtual
Destroys the action object.
Member Function Documentation
void KviKvsAction::activate () virtual
Executes the action.
Returns:
void
Reimplemented from KviAction.
References g_pActiveWindow, KviAction::isEnabled(), m_szScript, and KviIrcUrl::run().
Referenced by KviSubmenuAction::addToCustomToolBar(), KviGoAwayAction::addToCustomToolBar(), KviGoAwayAction::addToPopupMenu(), KviChangeNickAction::popupActivated(), and KviConnectToServerAction::popupActivated().
const QString & KviKvsAction::scriptCode ()
Returns the code of the script contained in the action.
Returns:
const QString &
References m_szScript.
Referenced by KviSubmenuAction::addToCustomToolBar(), and KviKvsUserAction::exportToKvs().
Member Data Documentation
QString KviKvsAction::m_szScript protected
Referenced by activate(), KviKvsAction(), KviKvsUserAction::load(), KviKvsUserAction::save(), and scriptCode().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsAction.h
src/kvirc/kvs/KviKvsAction.cpp