KVIrc: KviSplashScreen Class Reference
KviSplashScreen Class Reference
Splash screen class.
#include <KviSplashScreen.h>
Public Member Functions
void die ()
Kills the splash screen.
KviSplashScreen ()
Constructs the splash screen object.
void setProgress (int iProgress)
Sets the progress in steps.
virtual ~KviSplashScreen ()
Destroys the splash screen object.
Protected Slots
void fadeTimerShot ()
Sets the fading effect.
void suicide ()
Called when we want to kill the splash screen.
Protected Member Functions
virtual void hideEvent (QHideEvent *e)
virtual void showEvent (QShowEvent *e)
Private Attributes
bool m_bIncreasing
QTime m_creationTime
QTimer * m_pFadeTimer
QPixmap * m_pOverlay
QTimer * m_pTimer
qreal m_rTransparency
Detailed Description
Splash screen class.
Constructor & Destructor Documentation
KviSplashScreen::KviSplashScreen ()
Constructs the splash screen object.
Returns
KviSplashScreen
References connect(), KviQString::ensureLastCharIs(), fadeTimerShot(), KviFileUtils::fileExists(), KviApplication::findImage(), g_pApp, KviApplication::getLocalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, m_bIncreasing, m_pFadeTimer, m_pOverlay, m_pTimer, m_rTransparency, KviFileUtils::readFile(), suicide(), and KviApplication::Themes.
KviSplashScreen::~KviSplashScreen () virtual
Destroys the splash screen object.
References g_pSplashScreen, m_pOverlay, and m_pTimer.
Member Function Documentation
void KviSplashScreen::die ()
Kills the splash screen.
Returns
void
References m_bIncreasing, and m_pFadeTimer.
Referenced by KviApplication::destroySplashScreen().
void KviSplashScreen::fadeTimerShot () protected slot
Sets the fading effect.
Returns
void
References m_bIncreasing, m_pFadeTimer, m_rTransparency, and suicide().
Referenced by KviSplashScreen().
void KviSplashScreen::hideEvent (QHideEvent * e) protected virtual
References suicide().
void KviSplashScreen::setProgress (int iProgress)
Sets the progress in steps.
Parameters
iProgress The progress step
Returns
void
References g_pApp, and m_pOverlay.
void KviSplashScreen::showEvent (QShowEvent * e) protected virtual
References g_pApp, m_creationTime, and KviMemory::move().
void KviSplashScreen::suicide () protected slot
Called when we want to kill the splash screen.
Returns
void
References g_pSplashScreen.
Referenced by fadeTimerShot(), hideEvent(), and KviSplashScreen().
Member Data Documentation
bool KviSplashScreen::m_bIncreasing private
Referenced by die(), fadeTimerShot(), and KviSplashScreen().
QTime KviSplashScreen::m_creationTime private
Referenced by showEvent().
QTimer* KviSplashScreen::m_pFadeTimer private
Referenced by die(), fadeTimerShot(), and KviSplashScreen().
QPixmap* KviSplashScreen::m_pOverlay private
Referenced by KviSplashScreen(), setProgress(), and ~KviSplashScreen().
QTimer* KviSplashScreen::m_pTimer private
Referenced by KviSplashScreen(), and ~KviSplashScreen().
qreal KviSplashScreen::m_rTransparency private
Referenced by fadeTimerShot(), and KviSplashScreen().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSplashScreen.h
src/kvirc/ui/KviSplashScreen.cpp