KVIrc: KvsObject_comboBox Class Reference
KvsObject_comboBox Class Reference
#include <KvsObject_comboBox.h>
Public Member Functions
QWidget * widget ()
Public Member Functions inherited from KvsObject_widget
QWidget * widget ()
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Protected Slots
void editTextChanged (const QString &)
void slotActivated (int)
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Protected Member Functions
bool activatedEvent (KviKvsObjectFunctionCall *c)
bool changeItem (KviKvsObjectFunctionCall *c)
bool clear (KviKvsObjectFunctionCall *c)
bool count (KviKvsObjectFunctionCall *c)
bool current (KviKvsObjectFunctionCall *c)
bool currentItem (KviKvsObjectFunctionCall *c)
bool editable (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool insertItem (KviKvsObjectFunctionCall *c)
bool maxCount (KviKvsObjectFunctionCall *c)
bool popup (KviKvsObjectFunctionCall *c)
bool removeItem (KviKvsObjectFunctionCall *c)
bool setCurrentItem (KviKvsObjectFunctionCall *c)
bool setEditable (KviKvsObjectFunctionCall *c)
bool setEditText (KviKvsObjectFunctionCall *c)
bool setInsertionPolicy (KviKvsObjectFunctionCall *c)
bool setMaxCount (KviKvsObjectFunctionCall *c)
bool setTextLineEdit (KviKvsObjectFunctionCall *c)
bool textAt (KviKvsObjectFunctionCall *c)
bool textChangedEvent (KviKvsObjectFunctionCall *c)
bool textLineEdit (KviKvsObjectFunctionCall *c)
Protected Member Functions inherited from KvsObject_widget
bool addWidgetToWrappedLayout (KviKvsObjectFunctionCall *c)
bool backgroundColor (KviKvsObjectFunctionCall *c)
bool centerToScreen (KviKvsObjectFunctionCall *c)
bool colorPalette (KviKvsObjectFunctionCall *c)
virtual bool eventFilter (QObject *o, QEvent *e)
bool fontAscent (KviKvsObjectFunctionCall *c)
bool fontDescent (KviKvsObjectFunctionCall *c)
bool fontMetricsHeight (KviKvsObjectFunctionCall *c)
bool fontMetricsLineSpacing (KviKvsObjectFunctionCall *c)
bool fontMetricsWidth (KviKvsObjectFunctionCall *c)
bool foregroundColor (KviKvsObjectFunctionCall *c)
bool geometry (KviKvsObjectFunctionCall *c)
bool globalCursorX (KviKvsObjectFunctionCall *c)
bool globalCursorY (KviKvsObjectFunctionCall *c)
bool grab (KviKvsObjectFunctionCall *)
bool hasFocus (KviKvsObjectFunctionCall *c)
bool height (KviKvsObjectFunctionCall *)
bool hide (KviKvsObjectFunctionCall *)
bool insertIntoStatusBar (KviKvsObjectFunctionCall *c)
bool isEnabled (KviKvsObjectFunctionCall *c)
bool isTopLevel (KviKvsObjectFunctionCall *c)
bool isVisible (KviKvsObjectFunctionCall *c)
bool loadInterface (KviKvsObjectFunctionCall *c)
bool lower (KviKvsObjectFunctionCall *)
bool mapFromGlobal (KviKvsObjectFunctionCall *c)
bool mapToGlobal (KviKvsObjectFunctionCall *c)
bool move (KviKvsObjectFunctionCall *c)
bool parentWidget (KviKvsObjectFunctionCall *c)
bool raise (KviKvsObjectFunctionCall *)
bool removeFromStatusBar (KviKvsObjectFunctionCall *c)
bool repaint (KviKvsObjectFunctionCall *c)
bool resize (KviKvsObjectFunctionCall *c)
bool screenResolution (KviKvsObjectFunctionCall *c)
bool setAttribute (KviKvsObjectFunctionCall *c)
bool setBackgroundColor (KviKvsObjectFunctionCall *c)
bool setBackgroundImage (KviKvsObjectFunctionCall *c)
bool setEnabled (KviKvsObjectFunctionCall *c)
bool setFocus (KviKvsObjectFunctionCall *c)
bool setFocusPolicy (KviKvsObjectFunctionCall *c)
bool setFont (KviKvsObjectFunctionCall *c)
bool setForegroundColor (KviKvsObjectFunctionCall *c)
bool setGeometry (KviKvsObjectFunctionCall *c)
bool setKeyShortcut (KviKvsObjectFunctionCall *c)
bool setMask (KviKvsObjectFunctionCall *c)
bool setMaximumHeight (KviKvsObjectFunctionCall *c)
bool setMaximumWidth (KviKvsObjectFunctionCall *c)
bool setMinimumHeight (KviKvsObjectFunctionCall *c)
bool setMinimumWidth (KviKvsObjectFunctionCall *c)
bool setMouseTracking (KviKvsObjectFunctionCall *c)
bool setParent (KviKvsObjectFunctionCall *c)
bool setStyleSheet (KviKvsObjectFunctionCall *c)
bool setToolTip (KviKvsObjectFunctionCall *)
bool setWFlags (KviKvsObjectFunctionCall *c)
bool setWindowIcon (KviKvsObjectFunctionCall *c)
bool setWindowTitle (KviKvsObjectFunctionCall *c)
bool show (KviKvsObjectFunctionCall *c)
bool sizeHint (KviKvsObjectFunctionCall *c)
bool update (KviKvsObjectFunctionCall *c)
bool width (KviKvsObjectFunctionCall *)
bool windowTitle (KviKvsObjectFunctionCall *c)
bool x (KviKvsObjectFunctionCall *)
bool y (KviKvsObjectFunctionCall *)
Protected Member Functions inherited from KviKvsObject
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Additional Inherited Members
Signals inherited from KvsObject_widget
void aboutToDie ()
Protected Attributes inherited from KvsObject_widget
KviKvsRunTimeContext * m_pContext
QGraphicsDropShadowEffect * pGraphicsEffect
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Member Function Documentation
bool KvsObject_comboBox::activatedEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::changeItem (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::clear (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::count (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::current (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::currentItem (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::editable (KviKvsObjectFunctionCall * c) protected
void KvsObject_comboBox::editTextChanged (const QString & text) protected slot
References KviKvsObject::callFunction().
bool KvsObject_comboBox::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) protected virtual
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_comboBox::insertItem (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::maxCount (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::popup (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::removeItem (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::setCurrentItem (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::setEditable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::setEditText (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::setInsertionPolicy (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::setMaxCount (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::setTextLineEdit (KviKvsObjectFunctionCall * c) protected
void KvsObject_comboBox::slotActivated (int i) protected slot
References KviKvsObject::callFunction().
bool KvsObject_comboBox::textAt (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::textChangedEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_comboBox::textLineEdit (KviKvsObjectFunctionCall * c) protected
QWidget* KvsObject_comboBox::widget () inline
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_comboBox.h
src/modules/objects/KvsObject_comboBox.cpp