KVIrc: KviDockExtension Class Reference
KviDockExtension Class Reference
#include <kvi_frame.h>
Public Member Functions
virtual void die ()
Qt::WindowStates getPrevWindowState ()
KviDockExtension ()
virtual void refresh ()
void setPrevWindowState (Qt::WindowStates state)
virtual ~KviDockExtension ()
Protected Attributes
Qt::WindowStates m_uStoredWindowState
Constructor & Destructor Documentation
KviDockExtension::KviDockExtension () [inline]
virtual KviDockExtension::~KviDockExtension () [inline, virtual]
Member Function Documentation
virtual void KviDockExtension::die () [inline, virtual]
Referenced by KviFrame::~KviFrame().
Qt::WindowStates KviDockExtension::getPrevWindowState () [inline]
virtual void KviDockExtension::refresh () [inline, virtual]
Referenced by KviClassicWindowList::addItem(), KviIrcView::clearUnreaded(), KviTreeWindowListItem::highlight(), KviWindowListButton::highlight(), KviClassicWindowList::removeItem(), KviTreeWindowList::setActiveItem(), KviClassicWindowList::setActiveItem(), KviTreeWindowListItem::unhighlight(), and KviWindowListButton::unhighlight().
void KviDockExtension::setPrevWindowState (Qt::WindowStates state) [inline]
Member Data Documentation
Qt::WindowStates KviDockExtension::m_uStoredWindowState [protected]
The documentation for this class was generated from the following file:
src/kvirc/ui/kvi_frame.h