KVIrc: KviHtmlDialog Class Reference
KviHtmlDialog Class Reference
#include <KviHtmlDialog.h>
Public Member Functions
KviHtmlDialog (QWidget *pParent, KviHtmlDialogData *pData)
~KviHtmlDialog ()
Static Public Member Functions
static int display (QWidget *pParent, KviHtmlDialogData *pData)
Protected Slots
void button1Pressed ()
void button2Pressed ()
void button3Pressed ()
Protected Member Functions
virtual void reject ()
Protected Attributes
KviHtmlDialogData * m_pData
Constructor & Destructor Documentation
KviHtmlDialog::KviHtmlDialog (QWidget * pParent, KviHtmlDialogData * pData)
References __tr2qs, button1Pressed(), button2Pressed(), button3Pressed(), connect(), KviHtmlDialogData::ForceMinimumSize, g, KviHtmlDialogData::iCancelButton, KviHtmlDialogData::iDefaultButton, KviHtmlDialogData::iFlags, KviHtmlDialogData::iMinimumHeight, KviHtmlDialogData::iMinimumWidth, KviHtmlDialogData::iSelectedButton, l, m_pData, KviHtmlDialogData::m_pDoc, KviHtmlDialogData::pixIcon, KviHtmlDialogData::szButton1Text, KviHtmlDialogData::szButton2Text, KviHtmlDialogData::szButton3Text, KviHtmlDialogData::szCaption, KviHtmlDialogData::szHtmlText, KviHtmlDialogData::szLowerLabelText, and KviHtmlDialogData::szUpperLabelText.
Referenced by display().
KviHtmlDialog::~KviHtmlDialog ()
Member Function Documentation
void KviHtmlDialog::button1Pressed () protected slot
References KviHtmlDialogData::iSelectedButton, and m_pData.
Referenced by KviHtmlDialog().
void KviHtmlDialog::button2Pressed () protected slot
References KviHtmlDialogData::iSelectedButton, and m_pData.
Referenced by KviHtmlDialog().
void KviHtmlDialog::button3Pressed () protected slot
References KviHtmlDialogData::iSelectedButton, and m_pData.
Referenced by KviHtmlDialog().
int KviHtmlDialog::display (QWidget * pParent, KviHtmlDialogData * pData) static
References KviHtmlDialogData::iSelectedButton, and KviHtmlDialog().
Referenced by AddonFunctions::installAddonPackage(), and ThemeFunctions::installThemePackage().
void KviHtmlDialog::reject () protected virtual
References KviHtmlDialogData::iCancelButton, KviHtmlDialogData::iSelectedButton, and m_pData.
Member Data Documentation
KviHtmlDialogData* KviHtmlDialog::m_pData protected
Referenced by button1Pressed(), button2Pressed(), button3Pressed(), KviHtmlDialog(), and reject().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviHtmlDialog.h
src/kvirc/ui/KviHtmlDialog.cpp