KVIrc: OptionsWidget_ircAdvanced Class Reference
OptionsWidget_ircAdvanced Class Reference
#include <OptionsWidget_irc.h>
Public Member Functions
OptionsWidget_ircAdvanced (QWidget *parent)
~OptionsWidget_ircAdvanced ()
Constructor & Destructor Documentation
OptionsWidget_ircAdvanced::OptionsWidget_ircAdvanced (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::createLayout(), KviOption_boolForceBrutalQuit, KviOption_boolPrependAvatarInfoToRealname, KviOption_boolPrependGenderInfoToRealname, KviOption_boolPrependNickColorInfoToRealname, and KviOptionsWidget::mergeTip().
OptionsWidget_ircAdvanced::~OptionsWidget_ircAdvanced ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_irc.h
src/modules/options/OptionsWidget_irc.cpp