KVIrc: KviMutex Class Reference
KviMutex Class Reference
#include <KviThread.h>
Public Member Functions
KviMutex ()
void lock ()
bool locked ()
void unlock ()
virtual ~KviMutex ()
Private Attributes
kvi_mutex_t m_mutex
Constructor & Destructor Documentation
KviMutex::KviMutex () [inline]
virtual KviMutex::~KviMutex () [inline, virtual]
Member Function Documentation
void KviMutex::lock () [inline]
Referenced by DccBroker::chooseSaveFileName(), OptionsWidget_mediaTypes::commit(), KviSensitiveThread::dequeueEvent(), KviSensitiveThread::enqueueEvent(), KviThreadManager::eventsPending(), OptionsWidget_mediaTypes::fillTreeWidget(), DccSendThread::initGetInfo(), DccRecvThread::initGetInfo(), KviThread::isRunning(), KviThread::isStartingUp(), KviThreadManager::killPendingEventsByReceiver(), KviThreadManager::postSlaveEvent(), KviThreadManager::registerSlaveThread(), DccVoiceThread::run(), DccSendThread::run(), DccRecvThread::run(), KviApplication::saveMediaTypes(), DccChatThread::sendRawData(), KviThread::setRunning(), KviThread::setStartingUp(), KviApplication::setup(), KviThreadManager::threadEnteredWaitState(), KviThreadManager::threadLeftWaitState(), DccChatThread::tryFlushOutBuffers(), KviThreadManager::unregisterSlaveThread(), DccVoiceWindow::updateInfo(), DccSendThread::updateStats(), DccRecvThread::updateStats(), KviSensitiveThread::~KviSensitiveThread(), and KviThreadManager::~KviThreadManager().
bool KviMutex::locked ()
References m_mutex.
Referenced by KviMediaManager::findMediaType(), KviMediaManager::findMediaTypeByFileMask(), KviMediaManager::findMediaTypeByIanaType(), KviMediaManager::insertMediaType(), KviMediaManager::load(), KviMediaManager::save(), and DccThread::~DccThread().
void KviMutex::unlock () [inline]
Referenced by DccBroker::chooseSaveFileName(), OptionsWidget_mediaTypes::commit(), KviSensitiveThread::dequeueEvent(), DccSendThread::doneGetInfo(), DccRecvThread::doneGetInfo(), KviSensitiveThread::enqueueEvent(), KviThreadManager::eventsPending(), OptionsWidget_mediaTypes::fillTreeWidget(), KviThread::isRunning(), KviThread::isStartingUp(), KviThreadManager::killPendingEventsByReceiver(), KviThreadManager::postSlaveEvent(), KviThreadManager::registerSlaveThread(), DccVoiceThread::run(), DccSendThread::run(), DccRecvThread::run(), KviApplication::saveMediaTypes(), DccChatThread::sendRawData(), KviThread::setRunning(), KviThread::setStartingUp(), KviApplication::setup(), KviThreadManager::threadEnteredWaitState(), KviThreadManager::threadLeftWaitState(), DccChatThread::tryFlushOutBuffers(), KviThreadManager::unregisterSlaveThread(), DccVoiceWindow::updateInfo(), DccSendThread::updateStats(), DccRecvThread::updateStats(), KviSensitiveThread::~KviSensitiveThread(), and KviThreadManager::~KviThreadManager().
Member Data Documentation
kvi_mutex_t KviMutex::m_mutex [private]
Referenced by locked().
The documentation for this class was generated from the following files:
src/kvilib/system/KviThread.h
src/kvilib/system/KviThread.cpp