KVIrc: KviKvsHash Class Reference
KviKvsHash Class Reference
This class defines a new data type which contains hash data.
#include <KviKvsHash.h>
Public Member Functions
void appendAsString (QString &szBuffer) const
Appends data to the hash converting it into a string.
void clear ()
clear the hash
const KviPointerHashTable
< QString, KviKvsVariant > * dict ()
Returns the internal dictionary of the hash.
KviKvsVariant * find (const QString &szKey) const
Returns the element associated to the given key.
KviKvsVariant * get (const QString &szKey)
Returns the element associated to the given key.
bool isEmpty () const
Returns true if the hash is empty.
KviKvsHash ()
Constructs the hash data.
KviKvsHash (const KviKvsHash &hash)
Constructs the hash data.
void serialize (QString &szResult)
Serializes the hash to a given buffer.
void set (const QString &szKey, KviKvsVariant *pVal)
Sets an element into the hash.
kvs_uint_t size () const
Returns the size of the hash.
void unset (const QString &szKey)
Unsets an element from the hash.
~KviKvsHash ()
Destroys the array data.
Private Attributes
KviPointerHashTable< QString,
KviKvsVariant > * m_pDict
Detailed Description
This class defines a new data type which contains hash data.
Warning
This class must not have virtual functions nor destructor. Otherwise it will happily crash on windows when it is allocated in modules and destroyed anywhere else around
Constructor & Destructor Documentation
KviKvsHash::KviKvsHash ()
Constructs the hash data.
Returns
KviKvsHash
References m_pDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviKvsHash::KviKvsHash (const KviKvsHash & hash)
Constructs the hash data.
This is a carbon copy
Parameters
hash The hash to copy from
Returns
KviKvsHash
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pDict, KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
KviKvsHash::~KviKvsHash ()
Destroys the array data.
References m_pDict.
Member Function Documentation
void KviKvsHash::appendAsString (QString & szBuffer) const
Appends data to the hash converting it into a string.
Parameters
szBuffer The string to append
Returns
void
References KviPointerHashTableIterator< Key, T >::current(), and m_pDict.
Referenced by KviKvsVariant::appendAsString(), and KviKvsVariant::asString().
void KviKvsHash::clear ()
clear the hash
References KviPointerHashTable< Key, T >::clear(), and m_pDict.
const KviPointerHashTable< QString, KviKvsVariant > * KviKvsHash::dict ()
Returns the internal dictionary of the hash.
Returns
const KviPointerHashTable<QString,KviKvsVariant> *
References m_pDict.
Referenced by KviKvsVariant::castToArray(), KviKvsVariant::convertToArray(), KviKvsVariant::dump(), KviKvsTreeNodeOperationArrayAppend::execute(), KviKvsCoreFunctions::KVSCF(), objects_kvs_fnc_variables(), and OptionsWidget_textEncoding::OptionsWidget_textEncoding().
KviKvsVariant * KviKvsHash::find (const QString & szKey) const
Returns the element associated to the given key.
Parameters
szKey The key of the element to retrieve
Returns
KviKvsVariant *
References KviPointerHashTable< Key, T >::find(), and m_pDict.
Referenced by KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly(), KviKvsTreeNodeGlobalVariable::evaluateReadOnly(), KviKvsTreeNodeLocalVariable::evaluateReadOnly(), KviKvsTreeNodeObjectField::evaluateReadOnlyInObjectScope(), and KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope().
KviKvsVariant * KviKvsHash::get (const QString & szKey)
Returns the element associated to the given key.
If the element doesn't exists, it returns an empty element. If the index is out of hash bounds, it increases the hash size, fillin the hash in with empty strings.
Parameters
szKey The key of the element to retrieve
Returns
KviKvsVariant *
References KviPointerHashTable< Key, T >::find(), m_pDict, and KviPointerHashTable< Key, T >::replace().
Referenced by KviKvsTreeNodeExtendedScopeVariable::evaluateReadWrite(), KviKvsTreeNodeGlobalVariable::evaluateReadWrite(), KviKvsTreeNodeLocalVariable::evaluateReadWrite(), KviKvsTreeNodeObjectField::evaluateReadWriteInObjectScope(), and KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope().
bool KviKvsHash::isEmpty () const
Returns true if the hash is empty.
Returns
bool
References KviPointerHashTable< Key, T >::isEmpty(), and m_pDict.
Referenced by KviKvsVariant::asBoolean(), KviKvsVariantComparison::compareBoolHash(), KviKvsVariantComparison::compareHObjectHash(), KviKvsVariantComparison::compareIntHash(), KviKvsVariantComparison::compareRealHash(), KviKvsVariantComparison::compareStringHash(), KviKvsVariant::isEmpty(), and KviKvsVariant::isEqualToNothing().
void KviKvsHash::serialize (QString & szResult)
Serializes the hash to a given buffer.
Parameters
szResult The buffer to store
Returns
void
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pDict, and KviKvsVariant::serializeString().
Referenced by KviKvsVariant::serialize().
void KviKvsHash::set (const QString & szKey, KviKvsVariant * pVal)
Sets an element into the hash.
Parameters
szKey The key of the element to set
pVal The value to set
Returns
void
References m_pDict, and KviPointerHashTable< Key, T >::replace().
Referenced by file_kvs_fnc_diskSpace(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), language_kvs_cmd_detect(), KviIrcMessage::messageTagsKvsHash(), package_kvs_fnc_info(), KvsObject_colorDialog::slotColorSelected(), KvsObject_colorDialog::slotCurrentColorChanged(), spellchecker_enumerate_dicts(), KviXmlHandler::startElement(), texticons_kvs_fnc_get(), theme_kvs_fnc_info(), and KviKvsVariant::unserializeHash().
kvs_uint_t KviKvsHash::size () const
Returns the size of the hash.
Returns
kvs_uint_t
References KviPointerHashTable< Key, T >::count(), and m_pDict.
Referenced by KviKvsVariant::castToInteger(), KviKvsVariant::compare(), KviKvsVariantComparison::compareArrayHash(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), and KviKvsCoreFunctions::KVSCF().
void KviKvsHash::unset (const QString & szKey)
Unsets an element from the hash.
Parameters
szKey The key of the element to unset
Returns
void
References m_pDict, and KviPointerHashTable< Key, T >::remove().
Referenced by KviKvsHashElement::~KviKvsHashElement().
Member Data Documentation
KviPointerHashTable<QString, KviKvsVariant>* KviKvsHash::m_pDict private
Referenced by appendAsString(), clear(), dict(), find(), get(), isEmpty(), KviKvsHash(), serialize(), set(), size(), unset(), and ~KviKvsHash().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsHash.h
src/kvirc/kvs/KviKvsHash.cpp