KVIrc: TipFrame Class Reference
TipFrame Class Reference
#include <libkvitip.h>
Public Member Functions
void setText (const QString &text)
TipFrame (QWidget *par)
~TipFrame ()
Private Attributes
QLabel * m_pLabel1
QLabel * m_pLabel2
Constructor & Destructor Documentation
TipFrame::TipFrame (QWidget * par)
References KviApplication::findImage(), g_pApp, m_pLabel1, and m_pLabel2.
TipFrame::~TipFrame ()
Member Function Documentation
void TipFrame::setText (const QString & text)
References m_pLabel2.
Referenced by TipWindow::nextTip(), and TipWindow::prevTip().
Member Data Documentation
QLabel* TipFrame::m_pLabel1 [private]
Referenced by TipFrame().
QLabel* TipFrame::m_pLabel2 [private]
Referenced by setText(), and TipFrame().
The documentation for this class was generated from the following files:
src/modules/tip/libkvitip.h
src/modules/tip/libkvitip.cpp