KVIrc: KviIdentDaemon Class Reference
KviIdentDaemon Class Reference
#include <libkviident.h>
Public Member Functions
KviIdentDaemon ()
virtual void run ()
~KviIdentDaemon ()
Public Member Functions inherited from KviSensitiveThread
void enqueueEvent (KviThreadEvent *e)
KviSensitiveThread ()
void terminate ()
virtual ~KviSensitiveThread ()
Public Member Functions inherited from KviThread
void internalThreadRun_doNotTouchThis ()
bool isRunning ()
bool isStartingUp ()
KviThread ()
bool start ()
void wait ()
virtual ~KviThread ()
Protected Member Functions
void postMessage (const char *message, KviIdentRequest *r, const char *szAux=0)
Protected Member Functions inherited from KviSensitiveThread
KviThreadEvent * dequeueEvent ()
Protected Member Functions inherited from KviThread
void exit ()
void postEvent (QObject *o, QEvent *e)
Private Attributes
bool m_bEnableIPv6
bool m_bIPv6ContainsIPv4
KviPointerList< KviIdentRequest > * m_pRequestList
kvi_socket_t m_sock
kvi_socket_t m_sock6
KviCString m_szUser
kvi_u32_t m_uPort
Additional Inherited Members
Static Public Member Functions inherited from KviThread
static void msleep (unsigned long msec)
static void sleep (unsigned long sec)
static void usleep (unsigned long usec)
Protected Attributes inherited from KviSensitiveThread
KviPointerList< KviThreadEvent > * m_pLocalEventQueue
KviMutex * m_pLocalEventQueueMutex
Constructor & Destructor Documentation
KviIdentDaemon::KviIdentDaemon ()
References KviCString::isEmpty(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KviOption_boolIdentdEnableIPv6, KviOption_boolIdentdIPv6ContainsIPv4, KviOption_stringIdentdUser, KviOption_uintIdentdPort, m_bEnableIPv6, m_bIPv6ContainsIPv4, m_szUser, and m_uPort.
KviIdentDaemon::~KviIdentDaemon ()
References g_iIdentDaemonRunningUsers, and KviSensitiveThread::terminate().
Member Function Documentation
void KviIdentDaemon::postMessage (const char * message, KviIdentRequest * r, const char * szAux = 0) protected
References d, e, KVI_THREAD_EVENT_DATA, KviIdentRequest::m_szHost, KviIdentRequest::m_uPort, KviThread::postEvent(), and KviThreadDataEvent< TData >::setData().
Referenced by run().
void KviIdentDaemon::run () virtual
COMPILE_IPV6_SUPPORT
COMPILE_IPV6_SUPPORT
Reimplemented from KviThread.
References __tr, _OUTPUT_PARANOIC, KviSockaddr::addressLength(), KviCString::append(), KviPointerList< T >::append(), KviPointerList< T >::clear(), KviCString::cutLeft(), KviSensitiveThread::dequeueEvent(), e, KviCString::findFirstIdx(), KviPointerList< T >::first(), KviCString::Format, KviSockaddr::getStringAddress(), KviCString::hasData(), KVI_IDENT_THREAD_EVENT_EXITING, KVI_IDENT_THREAD_EVENT_EXITING_ON_REQUEST, KVI_INVALID_SOCKET, kvi_socket_accept(), kvi_socket_bind(), kvi_socket_close, kvi_socket_create(), kvi_socket_error(), kvi_socket_listen(), KVI_SOCKET_PF_INET, KVI_SOCKET_PF_INET6, KVI_SOCKET_PROTO_TCP, kvi_socket_recoverableConnectError(), kvi_socket_recv(), kvi_socket_select(), kvi_socket_setNonBlocking(), kvi_socket_setsockopt(), KVI_SOCKET_TYPE_STREAM, kvi_socket_write, kvi_strEqualCI(), KviCString::left(), KviCString::len(), m_bEnableIPv6, m_bIPv6ContainsIPv4, m_pRequestList, KviIdentRequest::m_sock, m_sock, m_sock6, KviIdentRequest::m_szData, m_szUser, KviIdentRequest::m_tStart, m_uPort, KviThread::msleep(), KviPointerList< T >::next(), KviSockaddr::port(), KviThread::postEvent(), postMessage(), KviCString::ptr(), r, KviPointerList< T >::removeRef(), KviPointerList< T >::setAutoDelete(), KviSockaddr::socketAddress(), szHost, and KviCString::trim().
Member Data Documentation
bool KviIdentDaemon::m_bEnableIPv6 private
Referenced by KviIdentDaemon(), and run().
bool KviIdentDaemon::m_bIPv6ContainsIPv4 private
Referenced by KviIdentDaemon(), and run().
KviPointerList<KviIdentRequest>* KviIdentDaemon::m_pRequestList private
Referenced by run().
kvi_socket_t KviIdentDaemon::m_sock private
Referenced by run().
kvi_socket_t KviIdentDaemon::m_sock6 private
Referenced by run().
KviCString KviIdentDaemon::m_szUser private
Referenced by KviIdentDaemon(), and run().
kvi_u32_t KviIdentDaemon::m_uPort private
Referenced by KviIdentDaemon(), and run().
The documentation for this class was generated from the following files:
src/modules/ident/libkviident.h
src/modules/ident/libkviident.cpp