KVIrc: OptionsWidget_privmsg Class Reference
OptionsWidget_privmsg Class Reference
#include <OptionsWidget_message.h>
Public Member Functions
OptionsWidget_privmsg (QWidget *parent)
~OptionsWidget_privmsg ()
Public Attributes
KviMircTextColorSelector * m_pSmartColorSelector
KviBoolSelector * m_pSpecialSmartColorSelector
KviBoolSelector * m_pUseSmartColorSelector
Protected Slots
void enableDisableSmartColorSelector (bool)
Constructor & Destructor Documentation
OptionsWidget_privmsg::OptionsWidget_privmsg (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addMircTextColorSelector(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), connect(), KviOptionsWidget::createLayout(), enableDisableSmartColorSelector(), g, KVI_OPTION_BOOL, KviOption_boolBoldedNicks, KviOption_boolColorNicks, KviOption_boolDrawEmoticons, KviOption_boolIrcViewShowImages, KviOption_boolShowChannelUserFlagInPrivmsgView, KviOption_boolShowUserAndHostInPrivmsgView, KviOption_boolStripMircColorsInUserMessages, KviOption_boolUseExtendedPrivmsgView, KviOption_boolUseSpecifiedSmartColorForOwnNick, KviOption_boolUseUserListColorsAsNickColors, KviOption_stringExtendedPrivmsgPostfix, KviOption_stringExtendedPrivmsgPrefix, KviOption_uintUserIrcViewOwnBackground, KviOption_uintUserIrcViewOwnForeground, l, m_pSmartColorSelector, m_pSpecialSmartColorSelector, m_pUseSmartColorSelector, KviTalVBox::setSpacing(), and KviTalHBox::setSpacing().
OptionsWidget_privmsg::~OptionsWidget_privmsg ()
Member Function Documentation
void OptionsWidget_privmsg::enableDisableSmartColorSelector (bool) [protected, slot]
References m_pSmartColorSelector, m_pUseSmartColorSelector, and KviMircTextColorSelector::setEnabled().
Referenced by OptionsWidget_privmsg().
Member Data Documentation
KviMircTextColorSelector* OptionsWidget_privmsg::m_pSmartColorSelector
Referenced by enableDisableSmartColorSelector(), and OptionsWidget_privmsg().
KviBoolSelector* OptionsWidget_privmsg::m_pSpecialSmartColorSelector
Referenced by OptionsWidget_privmsg().
KviBoolSelector* OptionsWidget_privmsg::m_pUseSmartColorSelector
Referenced by enableDisableSmartColorSelector(), and OptionsWidget_privmsg().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_message.h
src/modules/options/OptionsWidget_message.cpp