KVIrc: NotifierWindowBorder Class Reference
NotifierWindowBorder Class Reference
#include <NotifierWindowBorder.h>
Public Member Functions
int baseLine () const
QRect bodyRect () const
QRect captionRect () const
QRect closeRect () const
void draw (QPainter *, bool b=false)
int height () const
NotifierWindowBorder (QSize=QSize(WDG_MIN_WIDTH, WDG_MIN_HEIGHT))
QRect rect () const
void resetIcons ()
void resize (int w, int h)
void resize (QSize r)
void setCloseIcon (int state)
void setGeometry (QPoint p, QSize s)
void setGeometry (QRect r)
void setHeight (int h)
void setPics (bool b=false)
void setPoint (int x, int y)
void setWidth (int w)
QRect titleRect () const
int width () const
int x () const
int y () const
~NotifierWindowBorder ()
Private Member Functions
void loadImages ()
void recalculatePositions ()
Private Attributes
QRect m_bodyRect
QRect m_captionRect
QRect m_closeIconRect
int m_eIconState
int m_iRctHeight
int m_iRctWidth
QPixmap * m_pixCaptionBKG
QPixmap m_pixCaptionBKG_HL
QPixmap m_pixCaptionBKG_N
QPixmap * m_pixCaptionDX
QPixmap m_pixCaptionDX_HL
QPixmap m_pixCaptionDX_N
QPixmap * m_pixCaptionSX
QPixmap m_pixCaptionSX_HL
QPixmap m_pixCaptionSX_N
QPixmap * m_pixDWN
QPixmap m_pixDWN_HL
QPixmap m_pixDWN_N
QPixmap * m_pixDWNDX
QPixmap m_pixDWNDX_HL
QPixmap m_pixDWNDX_N
QPixmap * m_pixDWNSX
QPixmap m_pixDWNSX_HL
QPixmap m_pixDWNSX_N
QPixmap * m_pixDX
QPixmap m_pixDX_HL
QPixmap m_pixDX_N
QPixmap * m_pixIconClose
QPixmap * m_pixIconClose_clicked
QPixmap m_pixIconClose_clicked_HL
QPixmap m_pixIconClose_clicked_N
QPixmap * m_pixIconClose_out
QPixmap m_pixIconClose_out_HL
QPixmap m_pixIconClose_out_N
QPixmap * m_pixIconClose_over
QPixmap m_pixIconClose_over_HL
QPixmap m_pixIconClose_over_N
QPixmap * m_pixSX
QPixmap m_pixSX_HL
QPixmap m_pixSX_N
QPoint m_pnt
QRect m_rct
QRect m_titleRect
Constructor & Destructor Documentation
NotifierWindowBorder::NotifierWindowBorder (QSize s = QSize(WDG_MIN_WIDTH,WDG_MIN_HEIGHT))
References loadImages(), and resize().
NotifierWindowBorder::~NotifierWindowBorder ()
Member Function Documentation
int NotifierWindowBorder::baseLine () const [inline]
References height(), and y().
QRect NotifierWindowBorder::bodyRect () const [inline]
References m_bodyRect.
Referenced by NotifierWindow::NotifierWindow().
QRect NotifierWindowBorder::captionRect () const [inline]
References m_captionRect.
Referenced by NotifierWindow::mouseMoveEvent(), NotifierWindow::mousePressEvent(), and NotifierWindow::mouseReleaseEvent().
QRect NotifierWindowBorder::closeRect () const [inline]
References m_closeIconRect.
Referenced by NotifierWindow::mouseMoveEvent(), NotifierWindow::mousePressEvent(), and NotifierWindow::mouseReleaseEvent().
void NotifierWindowBorder::draw (QPainter * p, bool b = false)
References m_bodyRect, m_captionRect, m_closeIconRect, m_eIconState, m_pixCaptionBKG, m_pixCaptionDX, m_pixCaptionSX, m_pixDWN, m_pixDWNDX, m_pixDWNSX, m_pixDX, m_pixIconClose, m_pixSX, setCloseIcon(), and setPics().
Referenced by NotifierWindow::paintEvent().
int NotifierWindowBorder::height () const [inline]
References m_rct.
Referenced by baseLine(), and NotifierWindow::paintEvent().
void NotifierWindowBorder::loadImages () [private]
References g_pIconManager, KviIconManager::getPixmap(), m_captionRect, m_pixCaptionBKG, m_pixCaptionBKG_HL, m_pixCaptionBKG_N, m_pixCaptionDX, m_pixCaptionDX_HL, m_pixCaptionDX_N, m_pixCaptionSX, m_pixCaptionSX_HL, m_pixCaptionSX_N, m_pixDWN_HL, m_pixDWN_N, m_pixDWNDX_HL, m_pixDWNDX_N, m_pixDWNSX_HL, m_pixDWNSX_N, m_pixDX_HL, m_pixDX_N, m_pixIconClose_clicked_HL, m_pixIconClose_clicked_N, m_pixIconClose_out_HL, m_pixIconClose_out_N, m_pixIconClose_over_HL, m_pixIconClose_over_N, m_pixSX_HL, m_pixSX_N, p, setCloseIcon(), setPics(), and WDG_ICON_OUT.
Referenced by NotifierWindowBorder().
void NotifierWindowBorder::recalculatePositions () [private]
References m_bodyRect, m_captionRect, m_closeIconRect, m_iRctHeight, m_iRctWidth, m_pixCaptionDX, m_pixCaptionSX, m_pixDWN, m_pixIconClose, m_rct, and m_titleRect.
Referenced by setHeight(), and setWidth().
QRect NotifierWindowBorder::rect () const [inline]
References m_rct.
Referenced by NotifierWindow::mousePressEvent().
void NotifierWindowBorder::resetIcons ()
References setCloseIcon(), and WDG_ICON_OUT.
Referenced by NotifierWindow::leaveEvent().
void NotifierWindowBorder::resize (int w, int h) [inline]
References setHeight(), and setWidth().
Referenced by NotifierWindowBorder(), and NotifierWindow::paintEvent().
void NotifierWindowBorder::resize (QSize r) [inline]
References setHeight(), and setWidth().
void NotifierWindowBorder::setCloseIcon (int state)
References m_eIconState, m_pixIconClose, m_pixIconClose_clicked, m_pixIconClose_out, m_pixIconClose_over, WDG_ICON_CLICKED, WDG_ICON_OUT, and WDG_ICON_OVER.
Referenced by draw(), loadImages(), NotifierWindow::mouseMoveEvent(), NotifierWindow::mousePressEvent(), and resetIcons().
void NotifierWindowBorder::setGeometry (QPoint p, QSize s) [inline]
References setHeight(), setPoint(), and setWidth().
void NotifierWindowBorder::setGeometry (QRect r) [inline]
void NotifierWindowBorder::setHeight (int h)
References h, m_iRctHeight, and recalculatePositions().
Referenced by resize(), and setGeometry().
void NotifierWindowBorder::setPics (bool b = false)
References m_pixCaptionBKG, m_pixCaptionBKG_HL, m_pixCaptionBKG_N, m_pixCaptionDX, m_pixCaptionDX_HL, m_pixCaptionDX_N, m_pixCaptionSX, m_pixCaptionSX_HL, m_pixCaptionSX_N, m_pixDWN, m_pixDWN_HL, m_pixDWN_N, m_pixDWNDX, m_pixDWNDX_HL, m_pixDWNDX_N, m_pixDWNSX, m_pixDWNSX_HL, m_pixDWNSX_N, m_pixDX, m_pixDX_HL, m_pixDX_N, m_pixIconClose_clicked, m_pixIconClose_clicked_HL, m_pixIconClose_clicked_N, m_pixIconClose_out, m_pixIconClose_out_HL, m_pixIconClose_out_N, m_pixIconClose_over, m_pixIconClose_over_HL, m_pixIconClose_over_N, m_pixSX, m_pixSX_HL, and m_pixSX_N.
Referenced by draw(), and loadImages().
void NotifierWindowBorder::setPoint (int x, int y) [inline]
References m_pnt, and m_rct.
Referenced by setGeometry().
void NotifierWindowBorder::setWidth (int w)
References m_iRctWidth, recalculatePositions(), and w.
Referenced by resize(), and setGeometry().
QRect NotifierWindowBorder::titleRect () const [inline]
References m_titleRect.
Referenced by NotifierWindow::paintEvent().
int NotifierWindowBorder::width () const [inline]
References m_rct.
Referenced by NotifierWindow::paintEvent().
int NotifierWindowBorder::x () const [inline]
References m_pnt.
Referenced by NotifierWindow::doHide().
int NotifierWindowBorder::y () const [inline]
References m_pnt.
Referenced by baseLine(), and NotifierWindow::doHide().
Member Data Documentation
QRect NotifierWindowBorder::m_bodyRect [private]
Referenced by bodyRect(), draw(), and recalculatePositions().
QRect NotifierWindowBorder::m_captionRect [private]
Referenced by captionRect(), draw(), loadImages(), and recalculatePositions().
QRect NotifierWindowBorder::m_closeIconRect [private]
Referenced by closeRect(), draw(), and recalculatePositions().
int NotifierWindowBorder::m_eIconState [private]
Referenced by draw(), and setCloseIcon().
int NotifierWindowBorder::m_iRctHeight [private]
Referenced by recalculatePositions(), and setHeight().
int NotifierWindowBorder::m_iRctWidth [private]
Referenced by recalculatePositions(), and setWidth().
QPixmap* NotifierWindowBorder::m_pixCaptionBKG [private]
Referenced by draw(), loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixCaptionBKG_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixCaptionBKG_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixCaptionDX [private]
Referenced by draw(), loadImages(), recalculatePositions(), and setPics().
QPixmap NotifierWindowBorder::m_pixCaptionDX_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixCaptionDX_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixCaptionSX [private]
Referenced by draw(), loadImages(), recalculatePositions(), and setPics().
QPixmap NotifierWindowBorder::m_pixCaptionSX_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixCaptionSX_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixDWN [private]
Referenced by draw(), recalculatePositions(), and setPics().
QPixmap NotifierWindowBorder::m_pixDWN_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixDWN_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixDWNDX [private]
Referenced by draw(), and setPics().
QPixmap NotifierWindowBorder::m_pixDWNDX_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixDWNDX_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixDWNSX [private]
Referenced by draw(), and setPics().
QPixmap NotifierWindowBorder::m_pixDWNSX_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixDWNSX_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixDX [private]
Referenced by draw(), and setPics().
QPixmap NotifierWindowBorder::m_pixDX_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixDX_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixIconClose [private]
Referenced by draw(), recalculatePositions(), and setCloseIcon().
QPixmap* NotifierWindowBorder::m_pixIconClose_clicked [private]
Referenced by setCloseIcon(), and setPics().
QPixmap NotifierWindowBorder::m_pixIconClose_clicked_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixIconClose_clicked_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixIconClose_out [private]
Referenced by setCloseIcon(), and setPics().
QPixmap NotifierWindowBorder::m_pixIconClose_out_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixIconClose_out_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixIconClose_over [private]
Referenced by setCloseIcon(), and setPics().
QPixmap NotifierWindowBorder::m_pixIconClose_over_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixIconClose_over_N [private]
Referenced by loadImages(), and setPics().
QPixmap* NotifierWindowBorder::m_pixSX [private]
Referenced by draw(), and setPics().
QPixmap NotifierWindowBorder::m_pixSX_HL [private]
Referenced by loadImages(), and setPics().
QPixmap NotifierWindowBorder::m_pixSX_N [private]
Referenced by loadImages(), and setPics().
QPoint NotifierWindowBorder::m_pnt [private]
Referenced by setPoint(), x(), and y().
QRect NotifierWindowBorder::m_rct [private]
Referenced by height(), recalculatePositions(), rect(), setPoint(), and width().
QRect NotifierWindowBorder::m_titleRect [private]
Referenced by recalculatePositions(), and titleRect().
The documentation for this class was generated from the following files:
src/modules/notifier/NotifierWindowBorder.h
src/modules/notifier/NotifierWindowBorder.cpp