KVIrc: KviKvsTreeNodeSpecialCommandFor Class Reference
KviKvsTreeNodeSpecialCommandFor Class Reference
#include <KviKvsTreeNodeSpecialCommandFor.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandFor (const QChar *pLocation, KviKvsTreeNodeInstruction *pInit, KviKvsTreeNodeExpression *pCond, KviKvsTreeNodeInstruction *pUpd, KviKvsTreeNodeInstruction *pLoop)
~KviKvsTreeNodeSpecialCommandFor ()
Public Member Functions inherited from KviKvsTreeNodeSpecialCommand
KviKvsTreeNodeSpecialCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeSpecialCommand ()
Public Member Functions inherited from KviKvsTreeNodeCommand
const QString & commandName ()
void dumpSwitchList (const char *prefix)
KviKvsTreeNodeCommand (const QChar *pLocation, const QString &szCmdName)
~KviKvsTreeNodeCommand ()
Public Member Functions inherited from KviKvsTreeNodeInstruction
KviKvsTreeNodeInstruction (const QChar *pLocation)
Constructs the treenode instruction object.
~KviKvsTreeNodeInstruction ()
Destroys the treenode instruction object.
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Private Attributes
KviKvsTreeNodeExpression * m_pCondition
KviKvsTreeNodeInstruction * m_pInitialization
KviKvsTreeNodeInstruction * m_pLoop
KviKvsTreeNodeInstruction * m_pUpdate
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandFor::KviKvsTreeNodeSpecialCommandFor (const QChar * pLocation, KviKvsTreeNodeInstruction * pInit, KviKvsTreeNodeExpression * pCond, KviKvsTreeNodeInstruction * pUpd, KviKvsTreeNodeInstruction * pLoop)
References m_pCondition, m_pInitialization, m_pLoop, m_pUpdate, and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandFor::~KviKvsTreeNodeSpecialCommandFor ()
References m_pCondition, m_pInitialization, m_pLoop, and m_pUpdate.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandFor::contextDescription (QString & szBuffer) virtual
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandFor::dump (const char * prefix) virtual
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
References KviKvsTreeNodeInstruction::dump(), KviKvsTreeNodeExpression::dump(), m_pCondition, m_pInitialization, m_pLoop, and m_pUpdate.
bool KviKvsTreeNodeSpecialCommandFor::execute (KviKvsRunTimeContext * c) virtual
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References KviKvsVariant::asBoolean(), KviKvsRunTimeContext::breakPending(), KviKvsRunTimeContext::continuePending(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeInstruction::execute(), KviKvsRunTimeContext::handleBreak(), KviKvsRunTimeContext::handleContinue(), m_pCondition, m_pInitialization, m_pLoop, m_pUpdate, and v.
Member Data Documentation
KviKvsTreeNodeExpression* KviKvsTreeNodeSpecialCommandFor::m_pCondition private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandFor(), and ~KviKvsTreeNodeSpecialCommandFor().
KviKvsTreeNodeInstruction* KviKvsTreeNodeSpecialCommandFor::m_pInitialization private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandFor(), and ~KviKvsTreeNodeSpecialCommandFor().
KviKvsTreeNodeInstruction* KviKvsTreeNodeSpecialCommandFor::m_pLoop private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandFor(), and ~KviKvsTreeNodeSpecialCommandFor().
KviKvsTreeNodeInstruction* KviKvsTreeNodeSpecialCommandFor::m_pUpdate private
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandFor(), and ~KviKvsTreeNodeSpecialCommandFor().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandFor.h
src/kvirc/kvs/tree/KviKvsTreeNodeSpecialCommandFor.cpp