KVIrc: OptionsWidget_dccAdvanced Class Reference
OptionsWidget_dccAdvanced Class Reference
#include <OptionsWidget_dcc.h>
Public Member Functions
OptionsWidget_dccAdvanced (QWidget *parent)
~OptionsWidget_dccAdvanced ()
Constructor & Destructor Documentation
OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addStringSelector(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolDccBrokenBouncerHack, KviOption_boolDccGuessIpFromServerWhenLocalIsUnroutable, KviOption_boolDccListenOnSpecifiedInterfaceByDefault, KviOption_boolDccSendFakeAddressByDefault, KviOption_boolNotifyFailedDccHandshakes, KviOption_boolUserDefinedPortRange, KviOption_stringDccListenDefaultInterface, KviOption_stringDefaultDccFakeAddress, KviOption_uintDccMaxPort, KviOption_uintDccMinPort, KviOption_uintDccSocketTimeout, KviOption_uintMaxDccSlots, KviOptionsWidget::mergeTip(), s, KviTalHBox::setSpacing(), KviUIntSelector::setSuffix(), and u.
OptionsWidget_dccAdvanced::~OptionsWidget_dccAdvanced ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_dcc.h
src/modules/options/OptionsWidget_dcc.cpp