KVIrc: DccVideoWindow Class Reference
DccVideoWindow Class Reference
#include <DccVideoWindow.h>
Public Member Functions
DccVideoWindow (DccDescriptor *dcc, const char *name)
~DccVideoWindow ()
Public Member Functions inherited from DccWindow
virtual const char * dccMarshalOutputContextString ()
virtual KviWindow * dccMarshalOutputWindow ()
DccWindow (KviWindow::Type eType, const char *name, DccDescriptor *d)
DccDescriptor * descriptor ()
virtual DccThread * getSlaveThread ()
const DccMarshal * marshal ()
~DccWindow ()
Public Member Functions inherited from KviWindow
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual void applyOptions ()
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0, const QDateTime &datetime=QDateTime())
bool isChannel () const
bool isConsole () const
bool isDocked ()
bool isQuery () const
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
QTextEncoder * makeEncoder ()
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, QString szFmt,...)
void output (int iMsgType, const QDateTime &datetime, const char *pcFormat,...)
void output (int iMsgType, const QDateTime &datetime, const kvi_wchar_t *pwFormat,...)
void output (int iMsgType, const QDateTime &datetime, QString szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0, const QDateTime &datetime=QDateTime())
virtual KviWindow * outputProxy ()
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
void setWindowTitle (QString &szTitle)
KviTalSplitter * splitter ()
Returns the splitter of this window.
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Public Member Functions inherited from DccMarshalOutputContext
DccMarshalOutputContext ()
virtual ~DccMarshalOutputContext ()
Protected Slots
void connected ()
void connectionInProgress ()
void handleMarshalError (KviError::Code eError)
void slotUpdateImage ()
void startOrStopTalking (bool bStart)
void textViewRightClicked ()
void videoInputChanged (int)
Protected Slots inherited from KviWindow
void childDestroyed ()
void cryptControllerFinished ()
void cryptSessionInfoDestroyed ()
void systemTextEncodingPopupActivated (QAction *pAction)
void textEncodingButtonClicked ()
void toggleCryptController ()
Protected Member Functions
virtual bool event (QEvent *e)
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &buffer)
virtual const QString & localNick ()
virtual QPixmap * myIconPtr ()
virtual void ownAction (const QString &text)
virtual void ownMessage (const QString &text, bool bUserFeedback=true)
virtual void resizeEvent (QResizeEvent *)
virtual QSize sizeHint () const
void startConnection ()
void startTalking ()
void stopTalking ()
virtual const QString & target ()
virtual void triggerCreationEvents ()
virtual void triggerDestructionEvents ()
Protected Member Functions inherited from KviWindow
virtual void childEvent (QChildEvent *pEvent)
void childInserted (QWidget *pObject)
void childRemoved (QWidget *pObject)
virtual void childrenTreeChanged (QWidget *pAdded)
virtual void closeEvent (QCloseEvent *pEvent)
void createCryptControllerButton (QWidget *pPar)
void createSystemTextEncodingPopup ()
void createTextEncodingButton (QWidget *pPar)
QToolButton * createToolButton (QWidget *pPar, const char *pcName, KviIconManager::SmallIcon eIcon, const QString &szToolTip, bool bOn)
virtual void createWindowListItem ()
virtual void destroyWindowListItem ()
bool eventFilter (QObject *pObject, QEvent *pEvent)
void fillSingleColorCaptionBuffers (const QString &szName)
virtual void focusInEvent (QFocusEvent *)
virtual bool focusNextPrevChild (bool bNext)
virtual void inputMethodEvent (QInputMethodEvent *e)
virtual void loadProperties (KviConfigurationFile *pCfg)
virtual void lostUserFocus ()
virtual void moveEvent (QMoveEvent *pEvent)
virtual void preprocessMessage (QString &szMessage)
virtual void saveProperties (KviConfigurationFile *pCfg)
void setType (Type eType)
virtual void youAreDocked ()
virtual void youAreUndocked ()
Protected Attributes
QCamera * m_pCamera
QImage * m_pCameraImage
QCameraViewfinder * m_pCameraView
QComboBox * m_pCDevices
QComboBox * m_pCInputs
QWidget * m_pContainerWidget
QComboBox * m_pCStandards
QLabel * m_pInVideoLabel
KviThemedLabel * m_pLabel
QGridLayout * m_pLayout
DccVideoThread * m_pSlaveThread
QString * m_pszTarget
QLabel * m_pVideoLabel [3]
QString m_szLocalNick
QTimer m_Timer
QByteArray m_tmpTextDataOut
Protected Attributes inherited from DccWindow
DccDescriptor * m_pDescriptor
DccMarshal * m_pMarshal
Protected Attributes inherited from KviWindow
bool m_bIsDocked
bool m_bProcessingInputEvent
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Friends
class DccVideoThread
Additional Inherited Members
Public Types inherited from KviWindow
enum ActivityTemperature {
Ice = 0, VeryCold = 1, Cold = 2, Undefined = 3,
Hot = 4, VeryHot = 5, Fire = 6
}
Holds the activity meter in temperature scale.
enum ActivityValue {
None = 0, VeryLow = 1, Low = 2, Medium = 3,
High = 4, VeryHigh = 5
}
Holds the activity meter in value scale.
enum AttentionLevel { VisibleAndActive = 0, MainWindowIsVisible = 1 }
attention levels usable in hasAttention()
enum Type {
Console = 0, Channel = 1, Query = 2, DeadChannel = 3,
DeadQuery = 4, Editor = 5, Help = 6, Terminal = 7,
SocketSpy = 8, Links = 9, List = 10, DccChat = 11,
DccTransfer = 12, DccCanvas = 13, DccVoice = 14, DccVideo = 15,
UserWindow = 16, Tool = 17, IOGraph = 18, DirBrowser = 19,
ScriptEditor = 20, ScriptObject = 21, LogView = 22, Offer = 23,
Debug = 24, Unknown = 25, TypeCount = 26
}
Holds the types of a window; these are used by the KVIrc core and distributed modules.
Public Slots inherited from KviWindow
void autoRaise ()
void dock ()
void reloadImages ()
void savePropertiesAsDefault ()
void undock ()
Signals inherited from KviWindow
void windowNameChanged ()
Static Protected Attributes inherited from KviWindow
static const char * m_typeTable [TypeCount]
Properties inherited from KviWindow
int KviProperty_ChildFocusOwner
Constructor & Destructor Documentation
DccVideoWindow::DccVideoWindow (DccDescriptor * dcc, const char * name)
References __tr2qs_ctx(), connect(), connected(), connectionInProgress(), KviWindow::createCryptControllerButton(), KviWindow::createTextEncodingButton(), DccMarshalOutputContext::DccMarshal, FRAME_DURATION, handleMarshalError(), KVI_OPTION_BOOL, KviWindow::KviInput, KviOption_boolAutoLogDccChat, KviTalSplitter, KviWindow::m_pButtonBox, m_pCamera, m_pCameraImage, m_pCameraView, m_pCDevices, m_pCInputs, m_pContainerWidget, m_pCStandards, DccWindow::m_pDescriptor, KviWindow::m_pInput, m_pInVideoLabel, KviWindow::m_pIrcView, m_pLabel, m_pLayout, DccWindow::m_pMarshal, m_pSlaveThread, KviWindow::m_pSplitter, m_pszTarget, m_pVideoLabel, m_Timer, KviTalHBox::setStretchFactor(), slotUpdateImage(), startConnection(), KviIrcView::startLogging(), textViewRightClicked(), and videoInputChanged().
DccVideoWindow::~DccVideoWindow ()
References KviThreadManager::killPendingEvents(), m_pCamera, m_pCameraImage, m_pCameraView, m_pCDevices, m_pCInputs, m_pCStandards, m_pInVideoLabel, m_pLayout, m_pSlaveThread, m_pszTarget, m_pVideoLabel, KviSensitiveThread::terminate(), and DccBroker::unregisterDccWindow().
Member Function Documentation
void DccVideoWindow::connected () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, DccVideoThread, kvi_dcc_video_get_codec(), KVI_OUT_DCCMSG, DccMarshal::localIp(), DccMarshal::localPort(), DccWindow::m_pDescriptor, DccWindow::m_pMarshal, m_pSlaveThread, DccVideoCodec::name(), KviWindow::output(), _KviDccVideoThreadOptions::pCodec, KviCString::ptr(), DccMarshal::releaseSocket(), DccMarshal::remoteIp(), DccMarshal::remotePort(), DccDescriptor::szCodec, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szPort, and KviWindow::updateCaption().
Referenced by DccVideoWindow().
void DccVideoWindow::connectionInProgress () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bSendRequest, KviWindow::connection(), DccDescriptor::console(), KviIrcConnection::encodeText(), DccDescriptor::iSampleRate, KVI_OUT_DCCMSG, DccMarshal::localIp(), DccMarshal::localPort(), DccWindow::m_pDescriptor, DccWindow::m_pMarshal, KviWindow::output(), KviCString::ptr(), KviIrcConnection::sendFmtData(), KviNetUtils::stringIpToBinaryIp(), DccDescriptor::szCodec, DccDescriptor::szFakeIp, DccDescriptor::szFakePort, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szNick, and DccDescriptor::szPort.
Referenced by DccVideoWindow().
bool DccVideoWindow::event (QEvent * e) protected virtual
References __tr2qs_ctx(), __tr_no_xgettext_ctx, KviCString::cutLeft(), KviCString::cutRight(), d, KviIconManager::DccChatMsg, KviWindow::decodeText(), KviCryptEngine::DecryptOkWasEncoded, KviCryptEngine::DecryptOkWasEncrypted, KviCryptEngine::DecryptOkWasPlainText, KviWindow::demandAttention(), KviCString::firstCharIs(), KviMainWindow::firstConsole(), g_pApp, g_pMainWindow, KviError::getDescription(), KviWindow::hasAttention(), DccDescriptor::idString(), KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_THREAD_EVENT_DATA, KVI_DCC_THREAD_EVENT_ERROR, KVI_DCC_THREAD_EVENT_MESSAGE, KVI_DCC_VIDEO_THREAD_ACTION_GRAB_FRAME, KVI_DCC_VIDEO_THREAD_ACTION_START_PLAYING, KVI_DCC_VIDEO_THREAD_ACTION_START_RECORDING, KVI_DCC_VIDEO_THREAD_ACTION_STOP_PLAYING, KVI_DCC_VIDEO_THREAD_ACTION_STOP_RECORDING, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_UINT, KVI_OUT_ACTION, KVI_OUT_DCCCHATMSG, KVI_OUT_DCCERROR, KVI_OUT_DCCMSG, KVI_OUT_SYSTEMERROR, kvi_strEqualCIN(), KVI_THREAD_EVENT, KviEvent_OnDCCChatMessage, KviOption_boolFlashDccChatWindowOnNewMessages, KviOption_boolPopupNotifierOnNewDccChatMessages, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_2_HALTED, KviCString::lastCharIs(), m_pCameraImage, m_pCameraView, DccWindow::m_pDescriptor, KviWindow::MainWindowIsVisible, KviApplication::notifierMessage(), KviWindow::output(), KviWindow::outputNoFmt(), KviConsoleWindow::outputPrivmsg(), KviCString::ptr(), KviCString::stripLeftWhiteSpace(), DccDescriptor::szHost, DccDescriptor::szNick, DccDescriptor::szUser, and KviQString::toHtmlEscaped().
void DccVideoWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References KviCString::Format, DccWindow::m_pDescriptor, KviWindow::m_szPlainTextCaption, DccDescriptor::szIp, DccDescriptor::szLocalFileName, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccVideoWindow::getBaseLogFileName (QString & buffer) protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, DccDescriptor::szLocalFileName, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccVideoWindow::handleMarshalError (KviError::Code eError) protected slot
References __tr2qs_ctx(), KviError::getDescription(), KVI_OUT_DCCERROR, and KviWindow::output().
Referenced by DccVideoWindow(), and startConnection().
const QString & DccVideoWindow::localNick () protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, m_szLocalNick, and DccDescriptor::szLocalNick.
QPixmap * DccVideoWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References KviIconManager::DccVoice, g_pIconManager, and KviIconManager::getSmallIcon().
void DccVideoWindow::ownAction (const QString & text) protected virtual
Reimplemented from KviWindow.
References __tr2qs_ctx(), d, KviWindow::encodeText(), KviCString::Format, KVI_OPTION_BOOL, KVI_OUT_ACTION, KVI_OUT_SYSTEMWARNING, KviOption_boolStripMircColorsInUserMessages, KviCString::len(), DccWindow::m_pDescriptor, m_pSlaveThread, m_tmpTextDataOut, KviWindow::output(), KviCString::ptr(), KviControlCodes::stripControlBytes(), and DccDescriptor::szLocalNick.
void DccVideoWindow::ownMessage (const QString & text, bool bUserFeedback = true) protected virtual
Reimplemented from KviWindow.
References __tr2qs_ctx(), KviControlCodes::CryptEscape, d, KviWindow::decodeText(), KviCryptEngine::Encoded, KviWindow::encodeText(), KviCryptEngine::Encrypted, KviMainWindow::firstConsole(), KviCString::Format, g_pMainWindow, KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMWARNING, KviCString::len(), DccWindow::m_pDescriptor, m_pSlaveThread, m_tmpTextDataOut, KviConsoleWindow::NoNotifications, KviWindow::output(), KviConsoleWindow::outputPrivmsg(), KviCString::ptr(), DccDescriptor::szLocalHost, DccDescriptor::szLocalNick, and DccDescriptor::szLocalUser.
void DccVideoWindow::resizeEvent (QResizeEvent *) protected virtual
References KviInput::heightHint(), KviWindow::m_pButtonBox, KviWindow::m_pInput, and KviWindow::m_pSplitter.
QSize DccVideoWindow::sizeHint () const protected virtual
References KviWindow::m_pButtonBox, m_pContainerWidget, and KviWindow::m_pSplitter.
void DccVideoWindow::slotUpdateImage () protected slot
References DccVideoThread::m_inImage, m_pInVideoLabel, and m_pSlaveThread.
Referenced by DccVideoWindow().
void DccVideoWindow::startConnection () protected
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bDoTimeout, DccMarshal::dccConnect(), DccMarshal::dccListen(), handleMarshalError(), KVI_OUT_DCCMSG, DccWindow::m_pDescriptor, DccWindow::m_pMarshal, KviWindow::output(), KviError::Success, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, and DccDescriptor::szPort.
Referenced by DccVideoWindow().
void DccVideoWindow::startOrStopTalking (bool bStart) protected slot
References startTalking(), and stopTalking().
void DccVideoWindow::startTalking () protected
References e, KviSensitiveThread::enqueueEvent(), KVI_DCC_THREAD_EVENT_ACTION, m_pSlaveThread, and KviThreadDataEvent< TData >::setData().
Referenced by startOrStopTalking().
void DccVideoWindow::stopTalking () protected
References e, KviSensitiveThread::enqueueEvent(), KVI_DCC_THREAD_EVENT_ACTION, m_pSlaveThread, and KviThreadDataEvent< TData >::setData().
Referenced by startOrStopTalking().
const QString & DccVideoWindow::target () protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, m_pszTarget, DccDescriptor::szIp, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccVideoWindow::textViewRightClicked () protected slot
References DccDescriptor::idString(), KviEvent_OnDCCChatPopupRequest, KVS_TRIGGER_EVENT_1, and DccWindow::m_pDescriptor.
Referenced by DccVideoWindow().
void DccVideoWindow::triggerCreationEvents () protected virtual
Reimplemented from KviWindow.
References DccDescriptor::idString(), KviEvent_OnDCCChatWindowCreated, KVS_TRIGGER_EVENT_1, and DccWindow::m_pDescriptor.
void DccVideoWindow::triggerDestructionEvents () protected virtual
Reimplemented from KviWindow.
References DccDescriptor::idString(), KviEvent_OnDCCChatWindowClosing, KVS_TRIGGER_EVENT_1, and DccWindow::m_pDescriptor.
void DccVideoWindow::videoInputChanged (int) protected slot
Referenced by DccVideoWindow().
Friends And Related Function Documentation
friend class DccVideoThread friend
Referenced by connected().
Member Data Documentation
QCamera* DccVideoWindow::m_pCamera protected
Referenced by DccVideoWindow(), and ~DccVideoWindow().
QImage* DccVideoWindow::m_pCameraImage protected
Referenced by DccVideoWindow(), event(), and ~DccVideoWindow().
QCameraViewfinder* DccVideoWindow::m_pCameraView protected
Referenced by DccVideoWindow(), event(), and ~DccVideoWindow().
QComboBox* DccVideoWindow::m_pCDevices protected
Referenced by DccVideoWindow(), and ~DccVideoWindow().
QComboBox* DccVideoWindow::m_pCInputs protected
Referenced by DccVideoWindow(), and ~DccVideoWindow().
QWidget* DccVideoWindow::m_pContainerWidget protected
Referenced by DccVideoWindow(), and sizeHint().
QComboBox* DccVideoWindow::m_pCStandards protected
Referenced by DccVideoWindow(), and ~DccVideoWindow().
QLabel* DccVideoWindow::m_pInVideoLabel protected
Referenced by DccVideoWindow(), slotUpdateImage(), and ~DccVideoWindow().
KviThemedLabel* DccVideoWindow::m_pLabel protected
Referenced by DccVideoWindow().
QGridLayout* DccVideoWindow::m_pLayout protected
Referenced by DccVideoWindow(), and ~DccVideoWindow().
DccVideoThread* DccVideoWindow::m_pSlaveThread protected
Referenced by connected(), DccVideoWindow(), ownAction(), ownMessage(), slotUpdateImage(), startTalking(), stopTalking(), and ~DccVideoWindow().
QString* DccVideoWindow::m_pszTarget protected
Referenced by DccVideoWindow(), target(), and ~DccVideoWindow().
QLabel* DccVideoWindow::m_pVideoLabel[3] protected
Referenced by DccVideoWindow(), and ~DccVideoWindow().
QString DccVideoWindow::m_szLocalNick protected
Referenced by localNick().
QTimer DccVideoWindow::m_Timer protected
Referenced by DccVideoWindow().
QByteArray DccVideoWindow::m_tmpTextDataOut protected
Referenced by ownAction(), and ownMessage().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVideoWindow.h
src/modules/dcc/DccVideoWindow.cpp