KVIrc: KviTextIconManager Class Reference
KviTextIconManager Class Reference
The class that manages the icons.
#include <KviTextIconManager.h>
Signals
void changed ()
Called when the default associations change.
Public Member Functions
void applyOptions ()
Applies the options.
void checkDefaultAssociations ()
Checks and updates the default associations.
void clear ()
Clears the dictionary.
void insert (const QString &szName, int iId)
Inserts an icon in the dictionary.
void insert (const QString &szName, KviTextIcon &icon)
Inserts an icon in the dictionary.
KviTextIconManager ()
Constructs the icon manager object.
void load ()
Loads the dictionary.
KviTextIcon * lookupTextIcon (const QString &szName)
Returns the text of the icon.
void save ()
Saves the dictionary.
KviPointerHashTable< QString,
KviTextIcon > * textIconDict ()
Returns the dictionary of the icons.
~KviTextIconManager ()
Destroys the icon manager object.
Protected Member Functions
int load (const QString &szFileName, bool bMerge=false)
Loads the dictionary from a file.
void save (const QString &szFileName)
Saves the dictionary to a file.
Private Attributes
KviPointerHashTable< QString,
KviTextIcon > * m_pTextIconDict
Friends
class KviTextIconsOptionsWidget
class KviTextIconWindow
Detailed Description
The class that manages the icons.
Constructor & Destructor Documentation
KviTextIconManager::KviTextIconManager ()
Constructs the icon manager object.
Returns
KviTextIconManager
References m_pTextIconDict, and KviPointerHashTable< Key, T >::setAutoDelete().
KviTextIconManager::~KviTextIconManager ()
Destroys the icon manager object.
References m_pTextIconDict.
Member Function Documentation
void KviTextIconManager::applyOptions ()
Applies the options.
Returns
void
References KviPointerHashTable< Key, T >::first(), KVI_OPTION_BOOL, KviOption_boolEnableAnimatedSmiles, m_pTextIconDict, and KviPointerHashTable< Key, T >::next().
Referenced by KviMainWindow::applyOptions().
void KviTextIconManager::changed () signal
Called when the default associations change.
Returns
void
Referenced by checkDefaultAssociations(), insert(), and load().
void KviTextIconManager::checkDefaultAssociations ()
Checks and updates the default associations.
Returns
void
References changed(), KviPointerHashTable< Key, T >::find(), i, insert(), _KviTextIconAssocEntry::iVal, m_pTextIconDict, _KviTextIconAssocEntry::name, and KviOsInfo::name().
Referenced by OptionsWidget_textIcons::restoreClicked().
void KviTextIconManager::clear ()
Clears the dictionary.
Returns
void
References KviPointerHashTable< Key, T >::clear(), and m_pTextIconDict.
Referenced by OptionsWidget_textIcons::commit().
void KviTextIconManager::insert (const QString & szName, int iId)
Inserts an icon in the dictionary.
Parameters
szName The name of the icon
iId The id of the icon
Returns
void
References changed(), g_pIconManager, KviIconManager::iconName(), m_pTextIconDict, and KviPointerHashTable< Key, T >::replace().
Referenced by checkDefaultAssociations(), OptionsWidget_textIcons::commit(), and texticons_kvs_cmd_set().
void KviTextIconManager::insert (const QString & szName, KviTextIcon & icon)
Inserts an icon in the dictionary.
Parameters
szName The name of the icon
icon The icon
Returns
void
References changed(), m_pTextIconDict, and KviPointerHashTable< Key, T >::replace().
void KviTextIconManager::load ()
Loads the dictionary.
Returns
void
References KviApplication::Config, g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviApplication::getReadOnlyConfigPath(), KVI_CONFIGFILE_TEXTICONS, KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, TEXTICONMANAGER_CURRENT_CONFIG_UPDATE, and KviApplication::Themes.
Referenced by KviApplication::setup().
int KviTextIconManager::load (const QString & szFileName, bool bMerge = false) protected
Loads the dictionary from a file.
This is the real load() function It returns the config update
Parameters
szFileName The filename from where to load
bMerge Whether to merge the existing dictionary with the loaded one
Returns
int
References KviPointerList< T >::append(), changed(), KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), g_pIconManager, KviIconManager::getPixmap(), KviIconManager::getSmallIcon(), KviIconManager::Help, KviIconManager::iconName(), m_pTextIconDict, KviPointerList< T >::next(), KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviConfigurationFile::readIntEntry(), KviPointerHashTable< Key, T >::replace(), s, KviPointerList< T >::setAutoDelete(), and KviConfigurationFile::setGroup().
KviTextIcon* KviTextIconManager::lookupTextIcon (const QString & szName) inline
Returns the text of the icon.
Parameters
szName The name of the icon
Returns
KviTextIcon *
Referenced by KviHtmlGenerator::convertToHtml(), KviIrcView::getTextLine(), KviInputEditor::mousePressEvent(), KviTopicWidget::paintColoredText(), KviIrcView::paintEvent(), texticons_kvs_cmd_set(), and texticons_kvs_fnc_get().
void KviTextIconManager::save ()
Saves the dictionary.
Returns
void
References KviApplication::Config, g_pApp, KviApplication::getLocalKvircDirectory(), KVI_CONFIGFILE_TEXTICONS, KVI_OPTION_STRING, KVI_PATH_SEPARATOR_CHAR, KviOption_stringIconThemeSubdir, and KviApplication::Themes.
Referenced by OptionsWidget_textIcons::commit(), and KviApplication::saveTextIcons().
void KviTextIconManager::save (const QString & szFileName) protected
Saves the dictionary to a file.
This is the real save() function
Parameters
szFileName The filename where to save
Returns
void
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pTextIconDict, KviConfigurationFile::setGroup(), TEXTICONMANAGER_CURRENT_CONFIG_UPDATE, KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
KviPointerHashTable<QString,KviTextIcon>* KviTextIconManager::textIconDict () inline
Returns the dictionary of the icons.
Returns
KviPointerHashTable<QString,KviTextIcon> *
Referenced by KviTextIconWindow::fill(), OptionsWidget_textIcons::fillTable(), KviInputEditor::mousePressEvent(), texticons_kvs_cmd_set(), and texticons_kvs_fnc_get().
Friends And Related Function Documentation
friend class KviTextIconsOptionsWidget friend
friend class KviTextIconWindow friend
Member Data Documentation
KviPointerHashTable<QString,KviTextIcon>* KviTextIconManager::m_pTextIconDict private
Referenced by applyOptions(), checkDefaultAssociations(), clear(), insert(), KviTextIconManager(), load(), save(), and ~KviTextIconManager().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviTextIconManager.h
src/kvirc/kernel/KviTextIconManager.cpp