KVIrc: OptionsWidget_userListBackground Class Reference
OptionsWidget_userListBackground Class Reference
#include <OptionsWidget_userList.h>
Public Member Functions
virtual void commit ()
OptionsWidget_userListBackground (QWidget *parent)
~OptionsWidget_userListBackground ()
Protected Attributes
QComboBox * m_pHorizontalAlign
QComboBox * m_pVerticalAlign
Constructor & Destructor Documentation
OptionsWidget_userListBackground::OptionsWidget_userListBackground (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addLabel(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), g, KVI_OPTION_UINT, KviOption_colorUserListViewBackground, KviOption_colorUserListViewSelectionBackground, KviOption_pixmapUserListViewBackground, KviOption_uintUserListPixmapAlign, KviOptionsWidget::layout(), m_pHorizontalAlign, and m_pVerticalAlign.
OptionsWidget_userListBackground::~OptionsWidget_userListBackground ()
Member Function Documentation
void OptionsWidget_userListBackground::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintUserListPixmapAlign, m_pHorizontalAlign, and m_pVerticalAlign.
Member Data Documentation
QComboBox* OptionsWidget_userListBackground::m_pHorizontalAlign [protected]
Referenced by commit(), and OptionsWidget_userListBackground().
QComboBox* OptionsWidget_userListBackground::m_pVerticalAlign [protected]
Referenced by commit(), and OptionsWidget_userListBackground().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_userList.h
src/modules/options/OptionsWidget_userList.cpp