KVIrc: EventEditorEventTreeWidgetItem Class Reference
EventEditorEventTreeWidgetItem Class Reference
#include <EventEditorWindow.h>
Public Member Functions
EventEditorEventTreeWidgetItem (QTreeWidget *par, unsigned int uEvIdx, const QString &name, const QString &params)
QString name () const
void setName (const QString &szName)
~EventEditorEventTreeWidgetItem ()
Public Attributes
QString m_szName
QString m_szParams
unsigned int m_uEventIdx
Constructor & Destructor Documentation
EventEditorEventTreeWidgetItem::EventEditorEventTreeWidgetItem (QTreeWidget * par, unsigned int uEvIdx, const QString & name, const QString & params)
References setName().
EventEditorEventTreeWidgetItem::~EventEditorEventTreeWidgetItem () [inline]
Member Function Documentation
QString EventEditorEventTreeWidgetItem::name () const [inline]
References m_szName.
Referenced by EventEditor::eventHandlerDisabled().
void EventEditorEventTreeWidgetItem::setName (const QString & szName)
References m_szName.
Referenced by EventEditorEventTreeWidgetItem().
Member Data Documentation
QString EventEditorEventTreeWidgetItem::m_szName
Referenced by name(), and setName().
QString EventEditorEventTreeWidgetItem::m_szParams
unsigned int EventEditorEventTreeWidgetItem::m_uEventIdx
The documentation for this class was generated from the following files:
src/modules/eventeditor/EventEditorWindow.h
src/modules/eventeditor/EventEditorWindow.cpp