KVIrc: KviAsyncAvatarSelectionDialog Class Reference
KviAsyncAvatarSelectionDialog Class Reference
#include <libkviavatar.h>
Public Member Functions
KviAsyncAvatarSelectionDialog (QWidget *par, const QString &szInitialPath, KviIrcConnection *c)
~KviAsyncAvatarSelectionDialog ()
Protected Slots
void cancelClicked ()
void chooseFileClicked ()
void okClicked ()
Protected Member Functions
const QString & avatarName ()
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
KviIrcConnection * m_pConnection
QLineEdit * m_pLineEdit
QString m_szAvatarName
Constructor & Destructor Documentation
KviAsyncAvatarSelectionDialog::KviAsyncAvatarSelectionDialog (QWidget * par, const QString & szInitialPath, KviIrcConnection * c)
References __tr2qs, KviPointerList< T >::append(), c, cancelClicked(), chooseFileClicked(), connect(), g, h, l, m_pConnection, m_pLineEdit, okClicked(), and KviTalHBox::setSpacing().
KviAsyncAvatarSelectionDialog::~KviAsyncAvatarSelectionDialog ()
References KviPointerList< T >::removeRef().
Member Function Documentation
const QString& KviAsyncAvatarSelectionDialog::avatarName () [inline, protected]
References m_szAvatarName.
void KviAsyncAvatarSelectionDialog::cancelClicked () [protected, slot]
Referenced by KviAsyncAvatarSelectionDialog().
void KviAsyncAvatarSelectionDialog::chooseFileClicked () [protected, slot]
References __tr2qs, KviFileDialog::askForOpenFileName(), and m_pLineEdit.
Referenced by KviAsyncAvatarSelectionDialog().
void KviAsyncAvatarSelectionDialog::closeEvent (QCloseEvent * e) [protected, virtual]
void KviAsyncAvatarSelectionDialog::okClicked () [protected, slot]
References KviApplication::connectionExists(), KviIrcConnection::console(), KviQString::escapeKvs(), KviQString::EscapeSpace, g_pApp, m_pConnection, m_pLineEdit, m_szAvatarName, KviIrcUrl::run(), and szBuffer.
Referenced by KviAsyncAvatarSelectionDialog().
Member Data Documentation
KviIrcConnection* KviAsyncAvatarSelectionDialog::m_pConnection [protected]
Referenced by KviAsyncAvatarSelectionDialog(), and okClicked().
QLineEdit* KviAsyncAvatarSelectionDialog::m_pLineEdit [protected]
Referenced by chooseFileClicked(), KviAsyncAvatarSelectionDialog(), and okClicked().
QString KviAsyncAvatarSelectionDialog::m_szAvatarName [protected]
Referenced by avatarName(), and okClicked().
The documentation for this class was generated from the following files:
src/modules/avatar/libkviavatar.h
src/modules/avatar/libkviavatar.cpp