KVIrc: OptionsWidget_dccChat Class Reference
OptionsWidget_dccChat Class Reference
#include <OptionsWidget_dcc.h>
Public Member Functions
OptionsWidget_dccChat (QWidget *parent)
~OptionsWidget_dccChat ()
Constructor & Destructor Documentation
OptionsWidget_dccChat::OptionsWidget_dccChat (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), connect(), KviOptionsWidget::createLayout(), g, KVI_OPTION_BOOL, KviOption_boolAutoAcceptDccChat, KviOption_boolCreateMinimizedDccChat, KviOption_boolCreateMinimizedDccChatWhenAutoAccepted, KviOption_boolFlashDccChatWindowOnNewMessages, KviOption_boolPopupNotifierOnNewDccChatMessages, and KviOptionsWidget::mergeTip().
OptionsWidget_dccChat::~OptionsWidget_dccChat ()
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_dcc.h
src/modules/options/OptionsWidget_dcc.cpp