KVIrc: KviKvsTreeNode Class Reference
KviKvsTreeNode Class Reference
Treenode class.
#include <kvi_kvs_treenode_base.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)=0
Sets the buffer.
virtual void dump (const char *prefix)=0
Dumps the tree.
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Protected Member Functions
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Friends
class KviKvsParser
Detailed Description
Treenode class.
Constructor & Destructor Documentation
KviKvsTreeNode::KviKvsTreeNode (const QChar * pLocation)
Constructs the treenode object.
Parameters:
pLocation The location char of the instruction
Returns:
KviKvsTreeNode
References m_pLocation, and m_pParent.
virtual KviKvsTreeNode::~KviKvsTreeNode () [inline, virtual]
Destroys the treenode object.
Member Function Documentation
virtual void KviKvsTreeNode::contextDescription (QString & szBuffer) [pure virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implemented in KviKvsTreeNodeAliasFunctionCall, KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeArrayCount, KviKvsTreeNodeArrayElement, KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeBaseObjectFunctionCall, KviKvsTreeNodeCallbackCommand, KviKvsTreeNodeCommand, KviKvsTreeNodeCommandWithParameters, KviKvsTreeNodeCompositeData, KviKvsTreeNodeConstantData, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeCoreFunctionCall, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeData, KviKvsTreeNodeDataList, KviKvsTreeNodeExpression, KviKvsTreeNodeExpressionVariableOperand, KviKvsTreeNodeExpressionConstantOperand, KviKvsTreeNodeExpressionOperator, KviKvsTreeNodeExpressionUnaryOperator, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionBinaryOperator, KviKvsTreeNodeExpressionReturn, KviKvsTreeNodeExtendedScopeVariable, KviKvsTreeNodeFunctionCall, KviKvsTreeNodeGlobalVariable, KviKvsTreeNodeHashCount, KviKvsTreeNodeHashElement, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeInstruction, KviKvsTreeNodeInstructionBlock, KviKvsTreeNodeLocalVariable, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeModuleFunctionCall, KviKvsTreeNodeModuleSimpleCommand, KviKvsTreeNodeMultipleParameterIdentifier, KviKvsTreeNodeObjectField, KviKvsTreeNodeObjectFunctionCall, KviKvsTreeNodeOperation, KviKvsTreeNodeOperationAssignment, KviKvsTreeNodeOperationDecrement, KviKvsTreeNodeOperationIncrement, KviKvsTreeNodeOperationSelfAnd, KviKvsTreeNodeOperationSelfDivision, KviKvsTreeNodeOperationSelfModulus, KviKvsTreeNodeOperationSelfMultiplication, KviKvsTreeNodeOperationSelfOr, KviKvsTreeNodeOperationSelfShl, KviKvsTreeNodeOperationSelfShr, KviKvsTreeNodeOperationSelfSubtraction, KviKvsTreeNodeOperationSelfSum, KviKvsTreeNodeOperationSelfXor, KviKvsTreeNodeOperationStringAppend, KviKvsTreeNodeOperationArrayAppend, KviKvsTreeNodeOperationStringAppendWithComma, KviKvsTreeNodeOperationStringAppendWithSpace, KviKvsTreeNodeOperationStringTransliteration, KviKvsTreeNodeOperationStringSubstitution, KviKvsTreeNodeParameterReturn, KviKvsTreeNodeRebindingSwitch, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeSimpleCommand, KviKvsTreeNodeSingleParameterIdentifier, KviKvsTreeNodeSpecialCommand, KviKvsTreeNodeSpecialCommandBreak, KviKvsTreeNodeSpecialCommandClassFunctionDefinition, KviKvsTreeNodeSpecialCommandClass, KviKvsTreeNodeSpecialCommandContinue, KviKvsTreeNodeSpecialCommandDefpopupLabelSeparator, KviKvsTreeNodeSpecialCommandDefpopupLabelExtpopup, KviKvsTreeNodeSpecialCommandDefpopupLabelItem, KviKvsTreeNodeSpecialCommandDefpopupLabelLabel, KviKvsTreeNodeSpecialCommandDefpopupLabelPrologue, KviKvsTreeNodeSpecialCommandDefpopupLabelEpilogue, KviKvsTreeNodeSpecialCommandDefpopupLabelPopup, KviKvsTreeNodeSpecialCommandDefpopup, KviKvsTreeNodeSpecialCommandDo, KviKvsTreeNodeSpecialCommandFor, KviKvsTreeNodeSpecialCommandForeach, KviKvsTreeNodeSpecialCommandIf, KviKvsTreeNodeSpecialCommandSwitchLabelCase, KviKvsTreeNodeSpecialCommandSwitchLabelMatch, KviKvsTreeNodeSpecialCommandSwitchLabelRegexp, KviKvsTreeNodeSpecialCommandSwitchLabelDefault, KviKvsTreeNodeSpecialCommandSwitch, KviKvsTreeNodeSpecialCommandUnset, KviKvsTreeNodeSpecialCommandWhile, KviKvsTreeNodeStringCast, KviKvsTreeNodeSwitchList, KviKvsTreeNodeThisObjectFunctionCall, and KviKvsTreeNodeVoidFunctionCall.
Referenced by KviKvsRunTimeContext::report().
virtual void KviKvsTreeNode::dump (const char * prefix) [pure virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implemented in KviKvsTreeNodeAliasFunctionCall, KviKvsTreeNodeAliasSimpleCommand, KviKvsTreeNodeArrayCount, KviKvsTreeNodeArrayElement, KviKvsTreeNodeArrayReferenceAssert, KviKvsTreeNodeBaseObjectFunctionCall, KviKvsTreeNodeCallbackCommand, KviKvsTreeNodeCommand, KviKvsTreeNodeCommandWithParameters, KviKvsTreeNodeCompositeData, KviKvsTreeNodeConstantData, KviKvsTreeNodeCoreCallbackCommand, KviKvsTreeNodeCoreFunctionCall, KviKvsTreeNodeCoreSimpleCommand, KviKvsTreeNodeData, KviKvsTreeNodeDataList, KviKvsTreeNodeExpression, KviKvsTreeNodeExpressionVariableOperand, KviKvsTreeNodeExpressionConstantOperand, KviKvsTreeNodeExpressionOperator, KviKvsTreeNodeExpressionUnaryOperator, KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, KviKvsTreeNodeExpressionUnaryOperatorLogicalNot, KviKvsTreeNodeExpressionBinaryOperator, KviKvsTreeNodeExpressionReturn, KviKvsTreeNodeExtendedScopeVariable, KviKvsTreeNodeFunctionCall, KviKvsTreeNodeGlobalVariable, KviKvsTreeNodeHashCount, KviKvsTreeNodeHashElement, KviKvsTreeNodeHashReferenceAssert, KviKvsTreeNodeInstruction, KviKvsTreeNodeInstructionBlock, KviKvsTreeNodeLocalVariable, KviKvsTreeNodeModuleCallbackCommand, KviKvsTreeNodeModuleFunctionCall, KviKvsTreeNodeModuleSimpleCommand, KviKvsTreeNodeMultipleParameterIdentifier, KviKvsTreeNodeObjectField, KviKvsTreeNodeObjectFunctionCall, KviKvsTreeNodeOperation, KviKvsTreeNodeOperationAssignment, KviKvsTreeNodeOperationDecrement, KviKvsTreeNodeOperationIncrement, KviKvsTreeNodeOperationSelfAnd, KviKvsTreeNodeOperationSelfDivision, KviKvsTreeNodeOperationSelfModulus, KviKvsTreeNodeOperationSelfMultiplication, KviKvsTreeNodeOperationSelfOr, KviKvsTreeNodeOperationSelfShl, KviKvsTreeNodeOperationSelfShr, KviKvsTreeNodeOperationSelfSubtraction, KviKvsTreeNodeOperationSelfSum, KviKvsTreeNodeOperationSelfXor, KviKvsTreeNodeOperationStringAppend, KviKvsTreeNodeOperationArrayAppend, KviKvsTreeNodeOperationStringAppendWithComma, KviKvsTreeNodeOperationStringAppendWithSpace, KviKvsTreeNodeOperationStringTransliteration, KviKvsTreeNodeOperationStringSubstitution, KviKvsTreeNodeParameterReturn, KviKvsTreeNodeRebindingSwitch, KviKvsTreeNodeScopeOperator, KviKvsTreeNodeSimpleCommand, KviKvsTreeNodeSingleParameterIdentifier, KviKvsTreeNodeSpecialCommand, KviKvsTreeNodeSpecialCommandBreak, KviKvsTreeNodeSpecialCommandClassFunctionDefinition, KviKvsTreeNodeSpecialCommandClass, KviKvsTreeNodeSpecialCommandContinue, KviKvsTreeNodeSpecialCommandDefpopupLabelSeparator, KviKvsTreeNodeSpecialCommandDefpopupLabelExtpopup, KviKvsTreeNodeSpecialCommandDefpopupLabelItem, KviKvsTreeNodeSpecialCommandDefpopupLabelLabel, KviKvsTreeNodeSpecialCommandDefpopupLabelPrologue, KviKvsTreeNodeSpecialCommandDefpopupLabelEpilogue, KviKvsTreeNodeSpecialCommandDefpopupLabelPopup, KviKvsTreeNodeSpecialCommandDefpopup, KviKvsTreeNodeSpecialCommandDo, KviKvsTreeNodeSpecialCommandFor, KviKvsTreeNodeSpecialCommandForeach, KviKvsTreeNodeSpecialCommandIf, KviKvsTreeNodeSpecialCommandSwitchLabelCase, KviKvsTreeNodeSpecialCommandSwitchLabelMatch, KviKvsTreeNodeSpecialCommandSwitchLabelRegexp, KviKvsTreeNodeSpecialCommandSwitchLabelDefault, KviKvsTreeNodeSpecialCommandSwitch, KviKvsTreeNodeSpecialCommandUnset, KviKvsTreeNodeSpecialCommandWhile, KviKvsTreeNodeStringCast, KviKvsTreeNodeSwitchList, KviKvsTreeNodeThisObjectFunctionCall, and KviKvsTreeNodeVoidFunctionCall.
const QChar* KviKvsTreeNode::location () [inline]
Returns the location char.
Returns:
const QChar *
Referenced by KviKvsModuleCallbackCommandCall::getParameterCode(), KviKvsParser::parseCommand(), KviKvsParser::parseExpressionOperand(), KviKvsParser::parseVoidFunctionCallOrOperation(), and KviKvsRunTimeContext::report().
KviKvsTreeNode* KviKvsTreeNode::parent () [inline]
Returns the parent object.
Returns:
KviKvsTreeNode *
Referenced by KviKvsRunTimeContext::report().
void KviKvsTreeNode::setLocation (const QChar * pLocation) [inline, protected]
Sets the location char.
This is called only by KviKvsParser
Parameters:
pLocation The location char
Returns:
void
Referenced by KviKvsParser::parseCommand().
void KviKvsTreeNode::setParent (KviKvsTreeNode * p) [inline]
Sets the parent object.
Parameters:
p The parent treenode
Returns:
void
Referenced by KviKvsTreeNodeSpecialCommandClass::addFunctionDefinition(), KviKvsTreeNodeInstructionBlock::addInstruction(), KviKvsTreeNodeDataList::addItem(), KviKvsTreeNodeSpecialCommandSwitch::addLabel(), KviKvsTreeNodeSpecialCommandDefpopupLabelPopup::addLabel(), KviKvsTreeNodeSwitchList::addLong(), KviKvsTreeNodeSwitchList::addShort(), KviKvsTreeNodeArrayElement::KviKvsTreeNodeArrayElement(), KviKvsTreeNodeCommandEvaluation::KviKvsTreeNodeCommandEvaluation(), KviKvsTreeNodeCommandWithParameters::KviKvsTreeNodeCommandWithParameters(), KviKvsTreeNodeExpressionReturn::KviKvsTreeNodeExpressionReturn(), KviKvsTreeNodeExpressionUnaryOperator::KviKvsTreeNodeExpressionUnaryOperator(), KviKvsTreeNodeExpressionVariableOperand::KviKvsTreeNodeExpressionVariableOperand(), KviKvsTreeNodeFunctionCall::KviKvsTreeNodeFunctionCall(), KviKvsTreeNodeHashElement::KviKvsTreeNodeHashElement(), KviKvsTreeNodeIndirectData::KviKvsTreeNodeIndirectData(), KviKvsTreeNodeOperationArrayAppend::KviKvsTreeNodeOperationArrayAppend(), KviKvsTreeNodeOperationAssignment::KviKvsTreeNodeOperationAssignment(), KviKvsTreeNodeOperationSelfAnd::KviKvsTreeNodeOperationSelfAnd(), KviKvsTreeNodeOperationSelfDivision::KviKvsTreeNodeOperationSelfDivision(), KviKvsTreeNodeOperationSelfModulus::KviKvsTreeNodeOperationSelfModulus(), KviKvsTreeNodeOperationSelfMultiplication::KviKvsTreeNodeOperationSelfMultiplication(), KviKvsTreeNodeOperationSelfOr::KviKvsTreeNodeOperationSelfOr(), KviKvsTreeNodeOperationSelfShl::KviKvsTreeNodeOperationSelfShl(), KviKvsTreeNodeOperationSelfShr::KviKvsTreeNodeOperationSelfShr(), KviKvsTreeNodeOperationSelfSubtraction::KviKvsTreeNodeOperationSelfSubtraction(), KviKvsTreeNodeOperationSelfSum::KviKvsTreeNodeOperationSelfSum(), KviKvsTreeNodeOperationSelfXor::KviKvsTreeNodeOperationSelfXor(), KviKvsTreeNodeOperationStringAppend::KviKvsTreeNodeOperationStringAppend(), KviKvsTreeNodeOperationStringAppendWithComma::KviKvsTreeNodeOperationStringAppendWithComma(), KviKvsTreeNodeOperationStringAppendWithSpace::KviKvsTreeNodeOperationStringAppendWithSpace(), KviKvsTreeNodeOperationStringSubstitution::KviKvsTreeNodeOperationStringSubstitution(), KviKvsTreeNodeOperationStringTransliteration::KviKvsTreeNodeOperationStringTransliteration(), KviKvsTreeNodeParameterReturn::KviKvsTreeNodeParameterReturn(), KviKvsTreeNodeRebindingSwitch::KviKvsTreeNodeRebindingSwitch(), KviKvsTreeNodeScopeOperator::KviKvsTreeNodeScopeOperator(), KviKvsTreeNodeSpecialCommandClass::KviKvsTreeNodeSpecialCommandClass(), KviKvsTreeNodeSpecialCommandDefpopup::KviKvsTreeNodeSpecialCommandDefpopup(), KviKvsTreeNodeSpecialCommandDo::KviKvsTreeNodeSpecialCommandDo(), KviKvsTreeNodeSpecialCommandFor::KviKvsTreeNodeSpecialCommandFor(), KviKvsTreeNodeSpecialCommandForeach::KviKvsTreeNodeSpecialCommandForeach(), KviKvsTreeNodeSpecialCommandIf::KviKvsTreeNodeSpecialCommandIf(), KviKvsTreeNodeSpecialCommandSwitch::KviKvsTreeNodeSpecialCommandSwitch(), KviKvsTreeNodeSpecialCommandWhile::KviKvsTreeNodeSpecialCommandWhile(), KviKvsTreeNodeStringCast::KviKvsTreeNodeStringCast(), KviKvsTreeNodeDataList::prependItem(), KviKvsTreeNodeInstructionBlock::releaseFirst(), KviKvsTreeNodeSpecialCommandSwitchLabel::setInstruction(), KviKvsTreeNodeExpressionBinaryOperator::setLeft(), KviKvsTreeNodeSpecialCommandSwitchLabel::setParameter(), KviKvsTreeNodeExpressionBinaryOperator::setRight(), KviKvsTreeNodeCommand::setSwitchList(), and KviKvsTreeNodeOperation::setTargetVariableReference().
Friends And Related Function Documentation
friend class KviKvsParser [friend]
Reimplemented in KviKvsTreeNodeCommand, and KviKvsTreeNodeDataList.
Member Data Documentation
const QChar* KviKvsTreeNode::m_pLocation [protected]
Referenced by KviKvsTreeNode().
KviKvsTreeNode* KviKvsTreeNode::m_pParent [protected]
Referenced by KviKvsTreeNode().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_treenode_base.h
src/kvirc/kvs/kvi_kvs_treenode_base.cpp