KVIrc: KviChangeNickAction Class Reference
KviChangeNickAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
KviChangeNickAction (QObject *pParent)
Protected Slots
void popupAboutToShow ()
void popupActivated (int)
Constructor & Destructor Documentation
KviChangeNickAction::KviChangeNickAction (QObject * pParent)
Member Function Documentation
void KviChangeNickAction::popupAboutToShow () [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References __tr2qs, c, KviWindow::console(), KviApplication::fillRecentNicknamesPopup(), g_pActiveWindow, g_pApp, KviTalPopupMenu::insertItem(), KviTalPopupMenu::insertSeparator(), KviSubmenuAction::m_pPopup, and KviAction::smallIcon().
void KviChangeNickAction::popupActivated (int id) [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References __tr2qs, KviKvsAction::activate(), c, KviWindow::console(), g_pActiveWindow, KviSubmenuAction::m_pPopup, KviIrcUrl::run(), and KviTalPopupMenu::text().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp