KVIrc: KviKvsTreeNodeSpecialCommandClass Class Reference
KviKvsTreeNodeSpecialCommandClass Class Reference
#include <kvi_kvs_treenode_specialcommandclass.h>
Public Member Functions
void addFunctionDefinition (KviKvsTreeNodeSpecialCommandClassFunctionDefinition *pDef)
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Instruction.
virtual void dump (const char *prefix)
Dumps the instructions tree.
virtual bool execute (KviKvsRunTimeContext *c)
This is the main entry point to the tree visit.
KviKvsTreeNodeSpecialCommandClass (const QChar *pLocation, KviKvsTreeNodeDataList *pParams)
virtual ~KviKvsTreeNodeSpecialCommandClass ()
Protected Attributes
KviPointerList
< KviKvsTreeNodeSpecialCommandClassFunctionDefinition > * m_pFunctions
KviKvsTreeNodeDataList * m_pParams
Constructor & Destructor Documentation
KviKvsTreeNodeSpecialCommandClass::KviKvsTreeNodeSpecialCommandClass (const QChar * pLocation, KviKvsTreeNodeDataList * pParams)
References m_pFunctions, m_pParams, KviPointerList< T >::setAutoDelete(), and KviKvsTreeNode::setParent().
KviKvsTreeNodeSpecialCommandClass::~KviKvsTreeNodeSpecialCommandClass () [virtual]
References m_pFunctions, and m_pParams.
Member Function Documentation
void KviKvsTreeNodeSpecialCommandClass::addFunctionDefinition (KviKvsTreeNodeSpecialCommandClassFunctionDefinition * pDef)
References KviPointerList< T >::append(), m_pFunctions, and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseSpecialCommandClass().
void KviKvsTreeNodeSpecialCommandClass::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Instruction.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
void KviKvsTreeNodeSpecialCommandClass::dump (const char * prefix) [virtual]
Dumps the instructions tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeSpecialCommand.
References d, KviKvsTreeNodeDataList::dump(), KviPointerList< T >::first(), m_pFunctions, m_pParams, and KviPointerList< T >::next().
bool KviKvsTreeNodeSpecialCommandClass::execute (KviKvsRunTimeContext * c) [virtual]
This is the main entry point to the tree visit.
It returns false when the tree visiting has to be stopped and returns true when it has been successfully completed. A false return value may signal an error but is also used by break, halt, return and similar. The error condition is signaled by KviKvsRunTimeContext::error().
Parameters:
c The source context
Returns:
bool
Implements KviKvsTreeNodeInstruction.
References __tr2qs_ctx, KviKvsVariant::asString(), d, KviQString::equalCI(), KviKvsRunTimeContext::error(), KviKvsTreeNodeDataList::evaluate(), KviPointerList< T >::first(), KviKvsVariantList::first(), KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), m_pFunctions, m_pParams, KviKvsObjectClass::name(), KviPointerList< T >::next(), KviKvsVariantList::next(), KviKvsKernel::objectController(), KviKvsObjectClass::parentClass(), and KviKvsObjectClass::registerFunctionHandler().
Member Data Documentation
KviPointerList<KviKvsTreeNodeSpecialCommandClassFunctionDefinition>* KviKvsTreeNodeSpecialCommandClass::m_pFunctions [protected]
Referenced by addFunctionDefinition(), dump(), execute(), KviKvsTreeNodeSpecialCommandClass(), and ~KviKvsTreeNodeSpecialCommandClass().
KviKvsTreeNodeDataList* KviKvsTreeNodeSpecialCommandClass::m_pParams [protected]
Referenced by dump(), execute(), KviKvsTreeNodeSpecialCommandClass(), and ~KviKvsTreeNodeSpecialCommandClass().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_treenode_specialcommandclass.h
src/kvirc/kvs/kvi_kvs_treenode_specialcommandclass.cpp