KVIrc: KviNotifyListManager Class Reference
KviNotifyListManager Class Reference
#include <kvi_notifylist.h>
Public Member Functions
KviConsole * console ()
Protected Member Functions
virtual bool handleIsOn (KviIrcMessage *msg)
virtual bool handleUserhost (KviIrcMessage *msg)
virtual bool handleWatchReply (KviIrcMessage *msg)
KviNotifyListManager (KviIrcConnection *pConnection)
void notifyOffLine (const QString &nick, const QString &user=QString(), const QString &host=QString(), const QString &szReason=QString())
void notifyOnLine (const QString &nick, const QString &user=QString(), const QString &host=QString(), const QString &szReason=QString(), bool bJoin=true)
virtual void start ()
virtual void stop ()
~KviNotifyListManager ()
Protected Attributes
KviIrcConnection * m_pConnection
KviConsole * m_pConsole
Friends
class KviConnectionInfo
class KviConsole
class KviIrcConnection
class KviServerParser
Constructor & Destructor Documentation
KviNotifyListManager::KviNotifyListManager (KviIrcConnection * pConnection) [protected]
References KviIrcConnection::console(), m_pConnection, and m_pConsole.
KviNotifyListManager::~KviNotifyListManager () [protected]
Member Function Documentation
KviConsole* KviNotifyListManager::console () [inline]
References KviIrcConnection::m_pConsole.
Referenced by KviIsOnNotifyListManager::handleIsOn().
bool KviNotifyListManager::handleIsOn (KviIrcMessage * msg) [protected, virtual]
Reimplemented in KviIsOnNotifyListManager, and KviStupidNotifyListManager.
Referenced by KviServerParser::parseNumericIsOn().
bool KviNotifyListManager::handleUserhost (KviIrcMessage * msg) [protected, virtual]
Reimplemented in KviIsOnNotifyListManager.
Referenced by KviServerParser::parseNumericUserhost().
bool KviNotifyListManager::handleWatchReply (KviIrcMessage * msg) [protected, virtual]
Reimplemented in KviWatchNotifyListManager.
Referenced by KviServerParser::parseNumericWatch().
void KviNotifyListManager::notifyOffLine (const QString & nick, const QString & user = QString(), const QString & host = QString(), const QString & szReason = QString()) [protected]
References __tr2qs, _OUTPUT_VERBOSE, KviConsole::activeWindow(), KviPointerHashTableIterator< Key, T >::current(), d, g_pRegisteredUserDataBase, KVI_OPTION_BOOL, KVI_OUT_NOTIFYOFFLINE, KviEvent_OnNotifyOffLine, KviOption_boolNotifyListChangesToActiveWindow, KVS_TRIGGER_EVENT_1_HALTED, m_pConsole, KviConsole::notifyListView(), KviWindow::outputNoFmt(), KviUserListView::part(), KviQString::sprintf(), and KviRegisteredUserDataBase::userDict().
Referenced by KviWatchNotifyListManager::doMatchUser(), KviIsOnNotifyListManager::doMatchUser(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), and KviWatchNotifyListManager::handleWatchReply().
void KviNotifyListManager::notifyOnLine (const QString & nick, const QString & user = QString(), const QString & host = QString(), const QString & szReason = QString(), bool bJoin = true) [protected]
References __tr2qs, _OUTPUT_VERBOSE, KviConsole::activeWindow(), KviPointerHashTableIterator< Key, T >::current(), d, KviWindow::demandAttention(), g_pApp, g_pRegisteredUserDataBase, KviWindow::hasAttention(), KviUserListView::join(), KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_UINT, KVI_OUT_NOTIFYONLINE, KviEvent_OnNotifyOnLine, KviOption_boolFlashWindowOnNotifyOnLine, KviOption_boolNotifyListChangesToActiveWindow, KviOption_boolPopupNotifierOnNotifyOnLine, KviOption_uintNotifierAutoHideTime, KVS_TRIGGER_EVENT_1_HALTED, m_pConsole, KviApp::notifierMessage(), KviConsole::notifyListView(), KviWindow::outputNoFmt(), KviQString::sprintf(), and KviRegisteredUserDataBase::userDict().
Referenced by KviWatchNotifyListManager::doMatchUser(), KviIsOnNotifyListManager::doMatchUser(), and KviStupidNotifyListManager::handleIsOn().
void KviNotifyListManager::start () [protected, virtual]
Reimplemented in KviIsOnNotifyListManager, KviStupidNotifyListManager, and KviWatchNotifyListManager.
Referenced by KviIrcConnection::restartNotifyList().
void KviNotifyListManager::stop () [protected, virtual]
Reimplemented in KviIsOnNotifyListManager, KviStupidNotifyListManager, and KviWatchNotifyListManager.
Referenced by KviIrcConnection::restartNotifyList().
Friends And Related Function Documentation
friend class KviConnectionInfo [friend]
friend class KviConsole [friend]
Reimplemented in KviIsOnNotifyListManager, KviStupidNotifyListManager, and KviWatchNotifyListManager.
friend class KviIrcConnection [friend]
Reimplemented in KviIsOnNotifyListManager, KviStupidNotifyListManager, and KviWatchNotifyListManager.
friend class KviServerParser [friend]
Reimplemented in KviIsOnNotifyListManager, KviStupidNotifyListManager, and KviWatchNotifyListManager.
Member Data Documentation
KviIrcConnection* KviNotifyListManager::m_pConnection [protected]
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviWatchNotifyListManager::handleWatchReply(), KviNotifyListManager(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), KviWatchNotifyListManager::start(), KviStupidNotifyListManager::start(), KviIsOnNotifyListManager::start(), KviWatchNotifyListManager::stop(), KviStupidNotifyListManager::stop(), and KviIsOnNotifyListManager::stop().
KviConsole* KviNotifyListManager::m_pConsole [protected]
Referenced by KviIsOnNotifyListManager::delayedIsOnSession(), KviIsOnNotifyListManager::delayedNotifySession(), KviIsOnNotifyListManager::delayedUserhostSession(), KviWatchNotifyListManager::doMatchUser(), KviIsOnNotifyListManager::doMatchUser(), KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviWatchNotifyListManager::handleWatchReply(), KviNotifyListManager(), KviIsOnNotifyListManager::newNotifySession(), KviIsOnNotifyListManager::newUserhostSession(), notifyOffLine(), notifyOnLine(), KviStupidNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendIsOn(), KviIsOnNotifyListManager::sendUserhost(), KviWatchNotifyListManager::start(), KviStupidNotifyListManager::start(), KviIsOnNotifyListManager::start(), KviWatchNotifyListManager::stop(), KviStupidNotifyListManager::stop(), and KviIsOnNotifyListManager::stop().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_notifylist.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_notifylist.cpp