KVIrc: OptionsWidget_nickServ Class Reference
OptionsWidget_nickServ Class Reference
#include <OptionsWidget_nickserv.h>
Public Member Functions
virtual void commit ()
OptionsWidget_nickServ (QWidget *parent)
~OptionsWidget_nickServ ()
Public Member Functions inherited from KviOptionsWidget
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
QPushButton * addPushButton (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void addNickServRule ()
void delNickServRule ()
void editNickServRule ()
void enableDisableNickServControls ()
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
Protected Attributes
QPushButton * m_pAddRuleButton
QPushButton * m_pDelRuleButton
QPushButton * m_pEditRuleButton
QCheckBox * m_pNickServCheck
QTreeWidget * m_pNickServTreeWidget
Additional Inherited Members
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_nickServ::OptionsWidget_nickServ (QWidget * parent)
References __tr2qs_ctx(), KviTalToolTip::add(), addNickServRule(), connect(), KviOptionsWidget::createLayout(), delNickServRule(), editNickServRule(), enableDisableNickServControls(), KviPointerList< T >::first(), g_pNickServRuleSet, KviNickServRuleSet::isEmpty(), KviNickServRuleSet::isEnabled(), KviOptionsWidget::layout(), m_pAddRuleButton, m_pDelRuleButton, m_pEditRuleButton, m_pNickServCheck, m_pNickServTreeWidget, KviPointerList< T >::next(), and KviNickServRuleSet::rules().
OptionsWidget_nickServ::~OptionsWidget_nickServ () default
Member Function Documentation
void OptionsWidget_nickServ::addNickServRule () protected slot
References NickServRuleEditor::editRule(), KviNickServRule::identifyCommand(), m_pNickServTreeWidget, KviNickServRule::messageRegexp(), KviNickServRule::nickServMask(), r, KviNickServRule::registeredNick(), and KviNickServRule::serverMask().
Referenced by OptionsWidget_nickServ().
void OptionsWidget_nickServ::commit (void) virtual
Reimplemented from KviOptionsWidget.
References KviNickServRuleSet::addRule(), KviNickServRuleSet::clear(), KviOptionsWidget::commit(), KviNickServRule::createInstance(), g_pNickServRuleSet, i, m_pNickServCheck, m_pNickServTreeWidget, and KviNickServRuleSet::setEnabled().
void OptionsWidget_nickServ::delNickServRule () protected slot
References enableDisableNickServControls(), and m_pNickServTreeWidget.
Referenced by OptionsWidget_nickServ().
void OptionsWidget_nickServ::editNickServRule () protected slot
References m_pNickServTreeWidget, and r.
Referenced by OptionsWidget_nickServ().
void OptionsWidget_nickServ::enableDisableNickServControls () protected slot
References m_pAddRuleButton, m_pDelRuleButton, m_pEditRuleButton, m_pNickServCheck, and m_pNickServTreeWidget.
Referenced by delNickServRule(), and OptionsWidget_nickServ().
Member Data Documentation
QPushButton* OptionsWidget_nickServ::m_pAddRuleButton protected
Referenced by enableDisableNickServControls(), and OptionsWidget_nickServ().
QPushButton* OptionsWidget_nickServ::m_pDelRuleButton protected
Referenced by enableDisableNickServControls(), and OptionsWidget_nickServ().
QPushButton* OptionsWidget_nickServ::m_pEditRuleButton protected
Referenced by enableDisableNickServControls(), and OptionsWidget_nickServ().
QCheckBox* OptionsWidget_nickServ::m_pNickServCheck protected
Referenced by commit(), enableDisableNickServControls(), and OptionsWidget_nickServ().
QTreeWidget* OptionsWidget_nickServ::m_pNickServTreeWidget protected
Referenced by addNickServRule(), commit(), delNickServRule(), editNickServRule(), enableDisableNickServControls(), and OptionsWidget_nickServ().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_nickserv.h
src/modules/options/OptionsWidget_nickserv.cpp