KVIrc: DccVideoTheoraCodec Class Reference
DccVideoTheoraCodec Class Reference
#include <DccVoiceCodec.h>
Public Member Functions
DccVideoTheoraCodec ()
virtual void decode (KviDataBuffer *stream, KviDataBuffer *videoSignal, KviDataBuffer *textSignal)
virtual int decodedFrameSize ()
virtual int encodedFrameSize ()
virtual void encodeText (KviDataBuffer *textSignal, KviDataBuffer *stream)
virtual void encodeVideo (KviDataBuffer *videoSignal, KviDataBuffer *stream)
virtual ~DccVideoTheoraCodec ()
Private Attributes
KviOggTheoraDecoder * m_pDecoder
KviOggTheoraEncoder * m_pEncoder
Constructor & Destructor Documentation
DccVideoTheoraCodec::DccVideoTheoraCodec ()
References m_pDecoder, m_pEncoder, and DccVideoCodec::m_szName.
DccVideoTheoraCodec::~DccVideoTheoraCodec () [virtual]
References m_pDecoder, and m_pEncoder.
Member Function Documentation
void DccVideoTheoraCodec::decode (KviDataBuffer * stream, KviDataBuffer * videoSignal, KviDataBuffer * textSignal) [virtual]
Reimplemented from DccVideoCodec.
References KviOggTheoraDecoder::addData(), m_pDecoder, and KviDataBuffer::size().
int DccVideoTheoraCodec::decodedFrameSize () [virtual]
Reimplemented from DccVideoCodec.
int DccVideoTheoraCodec::encodedFrameSize () [virtual]
Reimplemented from DccVideoCodec.
void DccVideoTheoraCodec::encodeText (KviDataBuffer * textSignal, KviDataBuffer * stream) [virtual]
Reimplemented from DccVideoCodec.
References KviOggTheoraEncoder::addTextFrame(), KviDataBuffer::clear(), KviDataBuffer::data(), m_pEncoder, and KviDataBuffer::size().
void DccVideoTheoraCodec::encodeVideo (KviDataBuffer * videoSignal, KviDataBuffer * stream) [virtual]
Reimplemented from DccVideoCodec.
References KviOggTheoraEncoder::addVideoFrame(), KviDataBuffer::clear(), KviDataBuffer::data(), m_pEncoder, and KviDataBuffer::size().
Member Data Documentation
KviOggTheoraDecoder* DccVideoTheoraCodec::m_pDecoder [private]
Referenced by DccVideoTheoraCodec(), decode(), and ~DccVideoTheoraCodec().
KviOggTheoraEncoder* DccVideoTheoraCodec::m_pEncoder [private]
Referenced by DccVideoTheoraCodec(), encodeText(), encodeVideo(), and ~DccVideoTheoraCodec().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceCodec.h
src/modules/dcc/DccVoiceCodec.cpp