KVIrc: KviProxy Class Reference
KviProxy Class Reference
#include <KviProxy.h>
Public Types
enum Protocol { Socks4, Socks5, Http }
Public Member Functions
bool hasPass () const
bool hasUser () const
const QString & hostName () const
const QString & ip () const
bool isIPv6 () const
KviProxy (const KviProxy &prx)
KviProxy ()
void normalizeUserAndPass ()
const QString & pass () const
unsigned int passLen () const
kvi_u32_t port () const
Protocol protocol () const
const QString protocolName () const
void setHostname (const QString &h)
void setIp (const QString &i)
void setIPv6 (bool b)
void setNamedProtocol (const char *proto)
void setPass (const QString &p)
void setPort (kvi_u32_t &p)
void setProtocol (Protocol p)
void setUser (const QString &u)
const QString & user () const
unsigned int userLen () const
~KviProxy ()
Static Public Member Functions
static void getSupportedProtocolNames (QStringList &buf)
Public Attributes
bool m_bIsIPv6
Protocol m_protocol
QString m_szHostname
QString m_szIp
QString m_szPass
QString m_szUser
kvi_u32_t m_uPort
Member Enumeration Documentation
enum KviProxy::Protocol
Enumerator:
Socks4
Socks5
Http
Constructor & Destructor Documentation
KviProxy::KviProxy ()
References m_bIsIPv6, m_protocol, m_szHostname, m_uPort, and Socks4.
KviProxy::KviProxy (const KviProxy & prx)
References m_bIsIPv6, m_protocol, m_szHostname, m_szIp, m_szPass, m_szUser, and m_uPort.
KviProxy::~KviProxy ()
Member Function Documentation
void KviProxy::getSupportedProtocolNames (QStringList & buf) [static]
References i, and proxy_protocols_table.
Referenced by OptionsWidget_proxy::OptionsWidget_proxy().
bool KviProxy::hasPass () const [inline]
Referenced by KviIrcSocket::proxyLoginV4(), and KviIrcSocket::proxyLoginV5().
bool KviProxy::hasUser () const [inline]
Referenced by KviIrcSocket::proxyLoginHttp(), and KviIrcSocket::proxyLoginV5().
const QString& KviProxy::hostName () const [inline]
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), and KviIrcConnectionTargetResolver::lookupProxyHostname().
const QString& KviProxy::ip () const [inline]
Referenced by KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcSocket::startConnection().
bool KviProxy::isIPv6 () const [inline]
Referenced by OptionsWidget_proxy::currentItemChanged(), KviProxyDataBase::findProxy(), KviIrcConnectionTargetResolver::lookupProxyHostname(), and KviIrcSocket::startConnection().
void KviProxy::normalizeUserAndPass ()
References m_szPass, and m_szUser.
Referenced by KviIrcSocket::proxyLoginV4(), and KviIrcSocket::proxyLoginV5().
const QString& KviProxy::pass () const [inline]
Referenced by KviIrcSocket::proxyAuthUserPassV5(), KviIrcSocket::proxyLoginHttp(), and KviIrcSocket::proxyLoginV4().
unsigned int KviProxy::passLen () const [inline]
Referenced by KviIrcSocket::proxyAuthUserPassV5().
kvi_u32_t KviProxy::port () const [inline]
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), and KviIrcSocket::startConnection().
Protocol KviProxy::protocol () const [inline]
Referenced by KviIrcSocket::connectedToProxy(), KviProxyDataBase::findProxy(), KviIrcConnectionTargetResolver::lookupProxyHostname(), proxydb_kvs_fnc_protocol(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), and KviIrcSocket::startConnection().
const QString KviProxy::protocolName () const
References Http, m_protocol, proxy_protocols_table, and Socks5.
Referenced by KviIrcConnectionTargetResolver::asyncStartResolve(), and OptionsWidget_proxy::currentItemChanged().
void KviProxy::setHostname (const QString & h) [inline]
References h.
Referenced by proxydb_kvs_cmd_addProxy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), and proxydb_kvs_fnc_protocol().
void KviProxy::setIp (const QString & i) [inline]
References i.
Referenced by KviIrcConnectionTargetResolver::lookupProxyHostname(), proxydb_kvs_cmd_setIp(), and KviIrcConnectionTargetResolver::proxyLookupTerminated().
void KviProxy::setIPv6 (bool b) [inline]
Referenced by proxydb_kvs_cmd_addProxy(), and proxydb_kvs_cmd_setIPv6().
void KviProxy::setNamedProtocol (const char * proto)
References Http, kvi_strEqualCI(), m_protocol, Socks4, and Socks5.
Referenced by KviProxyDataBase::load(), and OptionsWidget_proxy::saveLastItem().
void KviProxy::setPass (const QString & p) [inline]
References p.
Referenced by proxydb_kvs_cmd_addProxy().
void KviProxy::setPort (kvi_u32_t & p) [inline]
References p.
Referenced by proxydb_kvs_cmd_addProxy(), and proxydb_kvs_cmd_setPort().
void KviProxy::setProtocol (Protocol p) [inline]
References p.
Referenced by proxydb_kvs_cmd_addProxy(), and proxydb_kvs_cmd_setProtocol().
void KviProxy::setUser (const QString & u) [inline]
References u.
Referenced by proxydb_kvs_cmd_addProxy().
const QString& KviProxy::user () const [inline]
Referenced by KviIrcSocket::proxyAuthUserPassV5(), KviIrcSocket::proxyLoginHttp(), and KviIrcSocket::proxyLoginV4().
unsigned int KviProxy::userLen () const [inline]
Referenced by KviIrcSocket::proxyAuthUserPassV5().
Member Data Documentation
bool KviProxy::m_bIsIPv6
Referenced by KviProxy(), KviProxyDataBase::load(), and OptionsWidget_proxy::saveLastItem().
Protocol KviProxy::m_protocol
Referenced by KviProxy(), protocolName(), and setNamedProtocol().
QString KviProxy::m_szHostname
Referenced by OptionsWidget_proxy::currentItemChanged(), KviProxyDataBase::findProxy(), KviProxy(), KviProxyDataBase::load(), ProxyOptionsTreeWidgetItem::ProxyOptionsTreeWidgetItem(), and OptionsWidget_proxy::saveLastItem().
QString KviProxy::m_szIp
Referenced by OptionsWidget_proxy::currentItemChanged(), KviProxy(), KviProxyDataBase::load(), and OptionsWidget_proxy::saveLastItem().
QString KviProxy::m_szPass
Referenced by OptionsWidget_proxy::currentItemChanged(), KviProxy(), KviProxyDataBase::load(), normalizeUserAndPass(), and OptionsWidget_proxy::saveLastItem().
QString KviProxy::m_szUser
Referenced by OptionsWidget_proxy::currentItemChanged(), KviProxy(), KviProxyDataBase::load(), normalizeUserAndPass(), and OptionsWidget_proxy::saveLastItem().
kvi_u32_t KviProxy::m_uPort
Referenced by OptionsWidget_proxy::currentItemChanged(), KviProxyDataBase::findProxy(), KviProxy(), KviProxyDataBase::load(), and OptionsWidget_proxy::saveLastItem().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviProxy.h
src/kvilib/ext/KviProxy.cpp