KVIrc: PopupEditorWidget Class Reference
PopupEditorWidget Class Reference
#include <PopupEditorWindow.h>
Public Member Functions
void commit ()
void exportPopups (bool)
PopupEditorWidget (QWidget *par)
~PopupEditorWidget ()
Public Attributes
bool m_bOneTimeSetupDone
bool m_bSaving
KviTalPopupMenu * m_pContextPopup
SinglePopupEditor * m_pEditor
KviTalPopupMenu * m_pEmptyContextPopup
MenuTreeWidgetItem * m_pLastEditedItem
QTreeWidget * m_pTreeWidget
Protected Slots
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *prev)
void customContextMenuRequested (const QPoint &pnt)
void exportAll ()
void exportCurrentPopup ()
void exportSelected ()
void newPopup ()
void popupRefresh (const QString &szName)
void removeCurrentPopup ()
Protected Member Functions
void getExportPopupBuffer (QString &buffer, MenuTreeWidgetItem *it)
void showEvent (QShowEvent *e)
Private Member Functions
void getUniquePopupName (MenuTreeWidgetItem *it, QString &buffer)
void oneTimeSetup ()
void saveLastEditedItem ()
Constructor & Destructor Documentation
PopupEditorWidget::PopupEditorWidget (QWidget * par)
References __tr2qs_ctx(), connect(), currentItemChanged(), exportAll(), exportSelected(), l, m_bOneTimeSetupDone, m_bSaving, m_pContextPopup, m_pEditor, m_pEmptyContextPopup, m_pLastEditedItem, m_pTreeWidget, and spl.
PopupEditorWidget::~PopupEditorWidget ()
Member Function Documentation
void PopupEditorWidget::commit (void)
References KviMemory::copy(), KviKvsPopupMenu::copyFrom(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviKvsPopupMenu::doClear(), g_pApp, KviKvsPopupManager::get(), i, KviKvsPopupManager::instance(), m_bOneTimeSetupDone, m_bSaving, MenuTreeWidgetItem::m_pPopup, m_pTreeWidget, p, KviKvsPopupMenu::popupName(), KviKvsPopupManager::remove(), KviPointerHashTable< Key, T >::remove(), saveLastEditedItem(), KviApplication::savePopups(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by PopupEditorWindow::applyClicked(), and PopupEditorWindow::okClicked().
void PopupEditorWidget::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem * prev) [protected, slot]
References SinglePopupEditor::edit(), m_pEditor, m_pLastEditedItem, and saveLastEditedItem().
Referenced by oneTimeSetup(), PopupEditorWidget(), and removeCurrentPopup().
void PopupEditorWidget::customContextMenuRequested (const QPoint & pnt) [protected, slot]
References __tr2qs_ctx(), KviTalPopupMenu::clear(), exportCurrentPopup(), KviIconManager::Folder, g_pIconManager, KviIconManager::getSmallIcon(), KviTalPopupMenu::insertItem(), KVI_ASSERT, m_bOneTimeSetupDone, m_pContextPopup, m_pEmptyContextPopup, m_pTreeWidget, newPopup(), KviIconManager::Popup, KviIconManager::Quit, removeCurrentPopup(), and KviTalPopupMenu::setItemEnabled().
Referenced by oneTimeSetup().
void PopupEditorWidget::exportAll () [protected, slot]
References exportPopups().
Referenced by PopupEditorWidget().
void PopupEditorWidget::exportCurrentPopup () [protected, slot]
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), KviKvsPopupMenu::generateDefPopup(), KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, m_pLastEditedItem, MenuTreeWidgetItem::popup(), KviKvsPopupMenu::popupName(), saveLastEditedItem(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by customContextMenuRequested().
void PopupEditorWidget::exportPopups (bool bSelectedOnly)
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), KviKvsPopupMenu::generateDefPopup(), i, KVI_FILTER_SCRIPT, KVI_PATH_SEPARATOR, m_pTreeWidget, MenuTreeWidgetItem::popup(), saveLastEditedItem(), KviMessageBox::warning(), and KviFileUtils::writeFile().
Referenced by exportAll(), and exportSelected().
void PopupEditorWidget::exportSelected () [protected, slot]
References exportPopups().
Referenced by PopupEditorWidget().
void PopupEditorWidget::getExportPopupBuffer (QString & buffer, MenuTreeWidgetItem * it) [protected]
void PopupEditorWidget::getUniquePopupName (MenuTreeWidgetItem * it, QString & buffer) [private]
References __tr2qs_ctx(), KviQString::equalCI(), i, KVI_ASSERT, m_bOneTimeSetupDone, MenuTreeWidgetItem::m_pPopup, m_pTreeWidget, and KviKvsPopupMenu::popupName().
Referenced by newPopup(), and saveLastEditedItem().
void PopupEditorWidget::newPopup () [protected, slot]
References getUniquePopupName(), and m_pTreeWidget.
Referenced by customContextMenuRequested().
void PopupEditorWidget::oneTimeSetup () [private]
References a, connect(), KviMemory::copy(), KviKvsPopupMenu::copyFrom(), KviPointerHashTableIterator< Key, T >::current(), currentItemChanged(), customContextMenuRequested(), KviKvsPopupManager::instance(), m_bOneTimeSetupDone, m_pTreeWidget, KviKvsPopupManager::popupDict(), KviKvsPopupMenu::popupName(), and popupRefresh().
Referenced by showEvent().
void PopupEditorWidget::popupRefresh (const QString & szName) [protected, slot]
References __tr2qs_ctx(), KviKvsPopupMenu::copyFrom(), SinglePopupEditor::edit(), KviQString::equalCI(), KviControlCodes::Escape, KviPointerHashTable< Key, T >::find(), i, KviKvsPopupManager::instance(), m_bSaving, m_pEditor, m_pLastEditedItem, MenuTreeWidgetItem::m_pPopup, m_pTreeWidget, KviKvsPopupManager::popupDict(), KviKvsPopupMenu::popupName(), MenuTreeWidgetItem::replacePopup(), and KviMessageBox::warning().
Referenced by oneTimeSetup().
void PopupEditorWidget::removeCurrentPopup () [protected, slot]
References currentItemChanged(), and m_pLastEditedItem.
Referenced by customContextMenuRequested().
void PopupEditorWidget::saveLastEditedItem () [private]
References KviQString::equalCI(), SinglePopupEditor::getMenu(), getUniquePopupName(), m, m_pEditor, m_pLastEditedItem, MenuTreeWidgetItem::m_pPopup, KviKvsPopupMenu::popupName(), MenuTreeWidgetItem::replacePopup(), and KviKvsPopupMenu::setPopupName().
Referenced by commit(), currentItemChanged(), exportCurrentPopup(), and exportPopups().
void PopupEditorWidget::showEvent (QShowEvent * e) [protected]
References oneTimeSetup().
Member Data Documentation
bool PopupEditorWidget::m_bOneTimeSetupDone
Referenced by commit(), customContextMenuRequested(), getUniquePopupName(), oneTimeSetup(), and PopupEditorWidget().
bool PopupEditorWidget::m_bSaving
Referenced by commit(), PopupEditorWidget(), and popupRefresh().
KviTalPopupMenu* PopupEditorWidget::m_pContextPopup
Referenced by customContextMenuRequested(), and PopupEditorWidget().
SinglePopupEditor* PopupEditorWidget::m_pEditor
Referenced by currentItemChanged(), PopupEditorWidget(), popupRefresh(), and saveLastEditedItem().
KviTalPopupMenu* PopupEditorWidget::m_pEmptyContextPopup
Referenced by customContextMenuRequested(), and PopupEditorWidget().
MenuTreeWidgetItem* PopupEditorWidget::m_pLastEditedItem
Referenced by currentItemChanged(), exportCurrentPopup(), PopupEditorWidget(), popupRefresh(), removeCurrentPopup(), and saveLastEditedItem().
QTreeWidget* PopupEditorWidget::m_pTreeWidget
Referenced by commit(), customContextMenuRequested(), exportPopups(), getUniquePopupName(), newPopup(), oneTimeSetup(), PopupEditorWidget(), and popupRefresh().
The documentation for this class was generated from the following files:
src/modules/popupeditor/PopupEditorWindow.h
src/modules/popupeditor/PopupEditorWindow.cpp