KVIrc: KviIrcDataStreamMonitor Class Reference
KviIrcDataStreamMonitor Class Reference
#include <KviIrcDataStreamMonitor.h>
Public Member Functions
virtual void connectionInitiated ()
virtual void connectionTerminated ()
virtual void die ()
virtual bool incomingMessage (const char *)=0
KviIrcDataStreamMonitor (KviIrcContext *pContext)
virtual bool outgoingMessage (const char *)=0
virtual ~KviIrcDataStreamMonitor ()
Protected Attributes
KviIrcContext * m_pMyContext
Constructor & Destructor Documentation
KviIrcDataStreamMonitor::KviIrcDataStreamMonitor (KviIrcContext * pContext)
References m_pMyContext, and KviIrcContext::registerDataStreamMonitor().
KviIrcDataStreamMonitor::~KviIrcDataStreamMonitor () [virtual]
References m_pMyContext, and KviIrcContext::unregisterDataStreamMonitor().
Member Function Documentation
virtual void KviIrcDataStreamMonitor::connectionInitiated () [inline, virtual]
Reimplemented in SocketSpyWindow.
virtual void KviIrcDataStreamMonitor::connectionTerminated () [inline, virtual]
Reimplemented in SocketSpyWindow.
virtual void KviIrcDataStreamMonitor::die () [inline, virtual]
Reimplemented in SocketSpyWindow.
Referenced by KviIrcContext::~KviIrcContext().
virtual bool KviIrcDataStreamMonitor::incomingMessage (const char *) [pure virtual]
Implemented in SocketSpyWindow.
virtual bool KviIrcDataStreamMonitor::outgoingMessage (const char *) [pure virtual]
Implemented in SocketSpyWindow.
Member Data Documentation
KviIrcContext* KviIrcDataStreamMonitor::m_pMyContext [protected]
Referenced by KviIrcDataStreamMonitor(), and ~KviIrcDataStreamMonitor().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcDataStreamMonitor.h
src/kvirc/kernel/KviIrcDataStreamMonitor.cpp