KVIrc: PluginManager Class Reference
PluginManager Class Reference
#include <Plugin.h>
Public Member Functions
bool checkUnload ()
bool pluginCall (KviKvsModuleFunctionCall *c)
PluginManager ()
void unloadAll ()
~PluginManager ()
Protected Member Functions
bool findPlugin (QString &szName)
Plugin * getPlugin (const QString &szPluginPath)
bool isPluginLoaded (const QString &szFileNameOrPathToLoad)
bool loadPlugin (const QString &szPluginPath)
Private Attributes
bool m_bCanUnload
KviPointerHashTable< QString,
Plugin > * m_pPluginDict
Constructor & Destructor Documentation
PluginManager::PluginManager ()
References m_bCanUnload, m_pPluginDict, and KviPointerHashTable< Key, T >::setAutoDelete().
PluginManager::~PluginManager ()
References m_pPluginDict.
Member Function Documentation
bool PluginManager::checkUnload ()
References Plugin::canunload(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_bCanUnload, m_pPluginDict, KviPointerHashTableIterator< Key, T >::moveNext(), KviPointerHashTable< Key, T >::remove(), and Plugin::unload().
Referenced by system_module_can_unload().
bool PluginManager::findPlugin (QString & szName) [protected]
References KviApplication::EasyPlugins, KviFileUtils::extractFileName(), KviFileUtils::fileExists(), g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), and KviFileUtils::isAbsolutePath().
Referenced by pluginCall().
Plugin * PluginManager::getPlugin (const QString & szPluginPath) [protected]
References KviPointerHashTable< Key, T >::find(), m_pPluginDict, and p.
Referenced by loadPlugin(), and pluginCall().
bool PluginManager::isPluginLoaded (const QString & szFileNameOrPathToLoad) [protected]
References KviPointerHashTable< Key, T >::find(), m_pPluginDict, and p.
Referenced by loadPlugin().
bool PluginManager::loadPlugin (const QString & szPluginPath) [protected]
References getPlugin(), KviPointerHashTable< Key, T >::insert(), isPluginLoaded(), KviTheme::load(), m_pPluginDict, and plugin.
Referenced by pluginCall().
bool PluginManager::pluginCall (KviKvsModuleFunctionCall * c)
References __tr2qs, KviKvsVariant::asString(), KviKvsVariantList::at(), Plugin::call(), KviKvsRunTimeCall::error(), findPlugin(), KviMemory::free(), getPlugin(), i, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, loadPlugin(), KviKvsRunTimeCall::parameterCount(), KviKvsRunTimeCall::params(), Plugin::pfree(), plugin, r, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), KviKvsRunTimeCall::warning(), and x.
Referenced by system_kvs_fnc_plugin_call().
void PluginManager::unloadAll ()
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), m_pPluginDict, KviPointerHashTableIterator< Key, T >::moveNext(), KviPointerHashTable< Key, T >::remove(), and Plugin::unload().
Referenced by system_module_cleanup().
Member Data Documentation
bool PluginManager::m_bCanUnload [private]
Referenced by checkUnload(), and PluginManager().
KviPointerHashTable<QString,Plugin>* PluginManager::m_pPluginDict [private]
Referenced by checkUnload(), getPlugin(), isPluginLoaded(), loadPlugin(), PluginManager(), unloadAll(), and ~PluginManager().
The documentation for this class was generated from the following files:
src/modules/system/Plugin.h
src/modules/system/Plugin.cpp