KVIrc: KviKvsObjectController Class Reference
KviKvsObjectController Class Reference
#include <KviKvsObjectController.h>
Public Member Functions
KviPointerHashTable< QString,
KviKvsObjectClass > * classDict ()
void clearInstances ()
void clearUserClasses ()
void deleteClass (KviKvsObjectClass *pClass)
void flushUserClasses ()
void init ()
void killAllObjectsWithClass (KviKvsObjectClass *pClass)
KviKvsObjectController ()
KviKvsObjectClass * lookupClass (const QString &szClass, bool bBuiltinOnly=false)
KviKvsObject * lookupObject (kvs_hobject_t hObject)
KviPointerHashTable< void
*, KviKvsObject > * objectDict ()
~KviKvsObjectController ()
Protected Member Functions
void registerClass (KviKvsObjectClass *pClass)
void registerObject (KviKvsObject *pObject)
void unregisterClass (KviKvsObjectClass *pClass)
void unregisterObject (KviKvsObject *pObject)
Protected Attributes
KviPointerHashTable< QString,
KviKvsObjectClass > * m_pClassDict
KviKvsObjectClass * m_pObjectClass
KviPointerHashTable< void
*, KviKvsObject > * m_pObjectDict
KviPointerList< KviKvsObject > * m_pTopLevelObjectList
Friends
class KviKvsObject
class KviKvsObjectClass
Constructor & Destructor Documentation
KviKvsObjectController::KviKvsObjectController ()
References m_pClassDict, m_pObjectDict, m_pTopLevelObjectList, KviPointerHashTable< Key, T >::setAutoDelete(), and KviPointerList< T >::setAutoDelete().
KviKvsObjectController::~KviKvsObjectController ()
References KviKvsObject::dieNow(), KviPointerList< T >::first(), flushUserClasses(), m_pClassDict, m_pObjectClass, m_pObjectDict, and m_pTopLevelObjectList.
Member Function Documentation
KviPointerHashTable<QString,KviKvsObjectClass>* KviKvsObjectController::classDict () [inline]
void KviKvsObjectController::clearInstances ()
References KviKvsObject::dieNow(), KviPointerList< T >::first(), m_pObjectDict, m_pTopLevelObjectList, KviPointerHashTable< Key, T >::setAutoDelete(), and KviPointerList< T >::setAutoDelete().
Referenced by KviApplication::frameDestructorCallback(), and objects_kvs_cmd_clearObjects().
void KviKvsObjectController::clearUserClasses ()
References KviPointerList< T >::append(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTable< Key, T >::findRef(), KviPointerList< T >::first(), flushUserClasses(), KviKvsObjectClass::isBuiltin(), m_pClassDict, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by objects_kvs_cmd_clearObjects().
void KviKvsObjectController::deleteClass (KviKvsObjectClass * pClass)
References KviApplication::Classes, KviKvsObjectClass::clearDirtyFlag(), g_pApp, KviApplication::getLocalKvircDirectory(), KVI_ASSERT, KviKvsObjectClass::name(), and KviFileUtils::removeFile().
Referenced by ClassEditorWidget::build(), objects_kvs_cmd_killClass(), ClassEditorWidget::removeItem(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameNamespace(), and ClassEditorWidget::saveNotBuiltClasses().
void KviKvsObjectController::flushUserClasses ()
References c, KviApplication::Classes, KviPointerHashTableIterator< Key, T >::current(), g_pApp, KviApplication::getLocalKvircDirectory(), and m_pClassDict.
Referenced by ClassEditorWidget::build(), clearUserClasses(), unregisterClass(), and ~KviKvsObjectController().
void KviKvsObjectController::init ()
References KviKvsObject::function_childCount(), KviKvsObject::function_children(), KviKvsObject::function_className(), KviKvsObject::function_destructor(), KviKvsObject::function_emit(), KviKvsObject::function_findChild(), KviKvsObject::function_killTimer(), KviKvsObject::function_listProperties(), KviKvsObject::function_name(), KviKvsObject::function_parent(), KviKvsObject::function_property(), KviKvsObject::function_setProperty(), KviKvsObject::function_signalName(), KviKvsObject::function_signalSender(), KviKvsObject::function_startTimer(), KviPointerHashTable< Key, T >::insert(), KVI_PTR2MEMBER, KviKvsObjectClass, m_pClassDict, m_pObjectClass, objectClassCreateInstance(), KviKvsObjectClass::registerFunctionHandler(), and KviKvsObjectClass::registerStandardNothingReturnFunctionHandler().
Referenced by KviKvsKernel::KviKvsKernel().
void KviKvsObjectController::killAllObjectsWithClass (KviKvsObjectClass * pClass)
References KviPointerList< T >::append(), KviPointerList< T >::first(), KviKvsObject::getClass(), KviKvsObject::killAllChildrenWithClass(), m_pObjectDict, m_pTopLevelObjectList, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by objects_kvs_cmd_killClass(), and KviKvsObjectClass::~KviKvsObjectClass().
KviKvsObjectClass * KviKvsObjectController::lookupClass (const QString & szClass, bool bBuiltinOnly = false)
References KviApplication::Classes, KviKvsObjectClass::clearDirtyFlag(), KviFileUtils::fileExists(), KviPointerHashTable< Key, T >::find(), g_pApp, g_pModuleManager, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviModuleManager::getModule(), KviKvsObjectClass::isBuiltin(), KviKvsObjectClass::load(), and m_pClassDict.
Referenced by ClassEditorWidget::build(), KvsObject_widget::eventFilter(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsObject::inheritsClass(), KviKvsCoreFunctions::KVSCF(), KVSO_CLASS_FUNCTION(), objects_kvs_cmd_killClass(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_instances(), ClassEditorWidget::oneTimeSetup(), KvsObject_tableWidget::paint(), ClassEditorWidget::removeItem(), ClassEditorWidget::removeItemChildren(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), ClassEditorWidget::renameNamespace(), ClassEditorWidget::saveNotBuiltClasses(), and KvsObject_socket::slotNewConnection().
KviKvsObject* KviKvsObjectController::lookupObject (kvs_hobject_t hObject) [inline]
Referenced by KviKvsObject::emitSignal(), KvsObject_widget::eventFilter(), KviKvsObject::function_setProperty(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), KviKvsTreeNodeScopeOperator::objectFromVariant(), objects_kvs_cmd_connect(), objects_kvs_cmd_disconnect(), objects_kvs_fnc_exists(), objects_kvs_fnc_name(), objects_kvs_fnc_variables(), KvsObject_tableWidget::paint(), and KvsObject_socket::slotNewConnection().
KviPointerHashTable<void *,KviKvsObject>* KviKvsObjectController::objectDict () [inline]
Referenced by objects_kvs_fnc_instances().
void KviKvsObjectController::registerClass (KviKvsObjectClass * pClass) [protected]
References KviPointerHashTable< Key, T >::insert(), m_pClassDict, and KviKvsObjectClass::name().
Referenced by KviKvsObjectClass::KviKvsObjectClass().
void KviKvsObjectController::registerObject (KviKvsObject * pObject) [protected]
References KviPointerList< T >::append(), KviKvsObject::handle(), KviPointerHashTable< Key, T >::insert(), m_pObjectDict, and m_pTopLevelObjectList.
Referenced by KviKvsObject::KviKvsObject().
void KviKvsObjectController::unregisterClass (KviKvsObjectClass * pClass) [protected]
References flushUserClasses(), KviKvsObjectClass::isBuiltin(), KviKvsObjectClass::isDirty(), m_pClassDict, KviKvsObjectClass::name(), and KviPointerHashTable< Key, T >::remove().
Referenced by KviKvsObjectClass::~KviKvsObjectClass().
void KviKvsObjectController::unregisterObject (KviKvsObject * pObject) [protected]
References KviKvsObject::handle(), m_pObjectDict, m_pTopLevelObjectList, KviPointerHashTable< Key, T >::remove(), and KviPointerList< T >::removeRef().
Referenced by KviKvsObject::~KviKvsObject().
Friends And Related Function Documentation
friend class KviKvsObject [friend]
Referenced by objectClassCreateInstance().
friend class KviKvsObjectClass [friend]
Referenced by init().
Member Data Documentation
KviPointerHashTable<QString,KviKvsObjectClass>* KviKvsObjectController::m_pClassDict [protected]
Referenced by clearUserClasses(), flushUserClasses(), init(), KviKvsObjectController(), lookupClass(), registerClass(), unregisterClass(), and ~KviKvsObjectController().
KviKvsObjectClass* KviKvsObjectController::m_pObjectClass [protected]
Referenced by init(), and ~KviKvsObjectController().
KviPointerHashTable<void *,KviKvsObject>* KviKvsObjectController::m_pObjectDict [protected]
Referenced by clearInstances(), killAllObjectsWithClass(), KviKvsObjectController(), registerObject(), unregisterObject(), and ~KviKvsObjectController().
KviPointerList<KviKvsObject>* KviKvsObjectController::m_pTopLevelObjectList [protected]
Referenced by clearInstances(), killAllObjectsWithClass(), KviKvsObjectController(), registerObject(), unregisterObject(), and ~KviKvsObjectController().
The documentation for this class was generated from the following files:
src/kvirc/kvs/object/KviKvsObjectController.h
src/kvirc/kvs/object/KviKvsObjectController.cpp