KVIrc: KviUIntSelector Class Reference
KviUIntSelector Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
virtual void commit ()
KviUIntSelector (QWidget *par, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled, bool bShortInt=false)
virtual void setPrefix (const QString &txt)
virtual void setSuffix (const QString &txt)
QString textForSearch ()
QWidget * widgetToHighlight ()
~KviUIntSelector ()
Public Member Functions inherited from KviTalHBox
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual ~KviSelectorInterface ()
Private Attributes
bool m_bIsShortInt
QLabel * m_pLabel
unsigned int * m_pOption
QSpinBox * m_pSpinBox
unsigned int m_uDefault
unsigned int m_uHighBound
unsigned int m_uLowBound
Additional Inherited Members
Protected Member Functions inherited from KviTalHBox
virtual void childEvent (QChildEvent *e)
Constructor & Destructor Documentation
KviUIntSelector::KviUIntSelector (QWidget * par, const QString & txt, unsigned int * pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled, bool bShortInt = false)
References m_bIsShortInt, m_pLabel, m_pOption, m_pSpinBox, m_uDefault, m_uHighBound, m_uLowBound, setEnabled(), KviTalHBox::setMargin(), and KviTalHBox::setStretchFactor().
KviUIntSelector::~KviUIntSelector () inline
Member Function Documentation
void KviUIntSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_bIsShortInt, m_pOption, m_pSpinBox, m_uDefault, m_uHighBound, m_uLowBound, and KviCString::toUInt().
void KviUIntSelector::setEnabled (bool bEnabled) virtual slot
References m_pLabel, and m_pSpinBox.
Referenced by KviUIntSelector(), and OptionsWidget_alerts::OptionsWidget_alerts().
void KviUIntSelector::setPrefix (const QString & txt) virtual
References m_pSpinBox.
void KviUIntSelector::setSuffix (const QString & txt) virtual
References m_pSpinBox.
Referenced by OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), and OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures().
QString KviUIntSelector::textForSearch () inline virtual
Reimplemented from KviSelectorInterface.
QWidget* KviUIntSelector::widgetToHighlight () inline virtual
Reimplemented from KviSelectorInterface.
Member Data Documentation
bool KviUIntSelector::m_bIsShortInt private
Referenced by commit(), and KviUIntSelector().
QLabel* KviUIntSelector::m_pLabel private
Referenced by KviUIntSelector(), and setEnabled().
unsigned int* KviUIntSelector::m_pOption private
Referenced by commit(), and KviUIntSelector().
QSpinBox* KviUIntSelector::m_pSpinBox private
Referenced by commit(), KviUIntSelector(), setEnabled(), setPrefix(), and setSuffix().
unsigned int KviUIntSelector::m_uDefault private
Referenced by commit(), and KviUIntSelector().
unsigned int KviUIntSelector::m_uHighBound private
Referenced by commit(), and KviUIntSelector().
unsigned int KviUIntSelector::m_uLowBound private
Referenced by commit(), and KviUIntSelector().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp