KVIrc: KviKvsTreeNodeCommandEvaluation Class Reference
KviKvsTreeNodeCommandEvaluation Class Reference
#include <KviKvsTreeNodeCommandEvaluation.h>
Public Member Functions
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeCommandEvaluation (const QChar *pLocation, KviKvsTreeNodeInstruction *pInstruction)
~KviKvsTreeNodeCommandEvaluation ()
Protected Attributes
KviKvsTreeNodeInstruction * m_pInstruction
Constructor & Destructor Documentation
KviKvsTreeNodeCommandEvaluation::KviKvsTreeNodeCommandEvaluation (const QChar * pLocation, KviKvsTreeNodeInstruction * pInstruction)
References m_pInstruction, and KviKvsTreeNode::setParent().
KviKvsTreeNodeCommandEvaluation::~KviKvsTreeNodeCommandEvaluation ()
References m_pInstruction.
Member Function Documentation
bool KviKvsTreeNodeCommandEvaluation::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeInstruction::execute(), m_pInstruction, and KviKvsRunTimeContext::swapReturnValuePointer().
Member Data Documentation
KviKvsTreeNodeInstruction* KviKvsTreeNodeCommandEvaluation::m_pInstruction [protected]
Referenced by evaluateReadOnly(), KviKvsTreeNodeCommandEvaluation(), and ~KviKvsTreeNodeCommandEvaluation().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeCommandEvaluation.h
src/kvirc/kvs/tree/KviKvsTreeNodeCommandEvaluation.cpp