KVIrc: KviAnimatedPixmapCache Class Reference
KviAnimatedPixmapCache Class Reference
#include <KviAnimatedPixmapCache.h>
Classes
class Data
class FrameInfo
Static Public Member Functions
static void done ()
static QPixmap * dummyPixmap ()
static void free (Data *data)
static void init ()
static Data * load (const QString &szFileName, int iWidth=0, int iHeight=0)
static void notifyDelete (KviAnimatedPixmapInterface *receiver)
static Data * resize (Data *data, const QSize &size)
static void scheduleFrameChange (uint delay, KviAnimatedPixmapInterface *receiver)
Protected Slots
virtual void timeoutEvent ()
Protected Member Functions
void internalFree (Data *data)
Data * internalLoad (const QString &szFile, int iWidth=0, int iHeight=0)
void internalNotifyDelete (KviAnimatedPixmapInterface *receiver)
Data * internalResize (Data *data, const QSize &size)
void internalScheduleFrameChange (uint delay, KviAnimatedPixmapInterface *receiver)
KviAnimatedPixmapCache ()
virtual ~KviAnimatedPixmapCache ()
Protected Attributes
QTimer m_animationTimer
QMutex m_cacheMutex
QMultiHash< QString, Data * > m_hCache
QMultiMap< long long,
KviAnimatedPixmapInterface * > m_timerData
QMutex m_timerMutex
Static Protected Attributes
static KviAnimatedPixmapCache * m_pInstance = nullptr
Constructor & Destructor Documentation
KviAnimatedPixmapCache::KviAnimatedPixmapCache () protected
References connect(), FRAME_DELAY, m_animationTimer, m_pInstance, and timeoutEvent().
Referenced by init().
KviAnimatedPixmapCache::~KviAnimatedPixmapCache () protected virtual
References g_pDummyPixmap, and m_pInstance.
Member Function Documentation
void KviAnimatedPixmapCache::done () static
References m_pInstance.
Referenced by KviApplication::~KviApplication().
QPixmap * KviAnimatedPixmapCache::dummyPixmap () static
References g_pDummyPixmap.
Referenced by KviAnimatedPixmap::pixmap().
static void KviAnimatedPixmapCache::free (Data * data) inline static
Referenced by KviAnimatedPixmap::~KviAnimatedPixmap().
void KviAnimatedPixmapCache::init () static
References KviAnimatedPixmapCache(), and m_pInstance.
Referenced by KviApplication::setup().
void KviAnimatedPixmapCache::internalFree (Data * data) protected
References KviAnimatedPixmapCache::Data::file, i, m_cacheMutex, m_hCache, and KviAnimatedPixmapCache::Data::refs.
Referenced by internalResize().
KviAnimatedPixmapCache::Data * KviAnimatedPixmapCache::internalLoad (const QString & szFile, int iWidth = 0, int iHeight = 0) protected
References i, m_cacheMutex, m_hCache, KviAnimatedPixmapCache::Data::refs, and KviAnimatedPixmapCache::Data::size.
void KviAnimatedPixmapCache::internalNotifyDelete (KviAnimatedPixmapInterface * receiver) protected
References i, m_timerData, and m_timerMutex.
KviAnimatedPixmapCache::Data * KviAnimatedPixmapCache::internalResize (Data * data, const QSize & size) protected
References KviAnimatedPixmapCache::Data::file, i, internalFree(), m_cacheMutex, m_hCache, KviAnimatedPixmapCache::Data::refs, KviAnimatedPixmapCache::Data::resized, and KviAnimatedPixmapCache::Data::size.
void KviAnimatedPixmapCache::internalScheduleFrameChange (uint delay, KviAnimatedPixmapInterface * receiver) protected
References KviTimeUtils::getCurrentTimeMills(), m_animationTimer, m_timerData, and m_timerMutex.
static Data* KviAnimatedPixmapCache::load (const QString & szFileName, int iWidth = 0, int iHeight = 0) inline static
Referenced by KviAnimatedPixmap::KviAnimatedPixmap().
static void KviAnimatedPixmapCache::notifyDelete (KviAnimatedPixmapInterface * receiver) inline static
Referenced by KviAnimatedPixmap::~KviAnimatedPixmap().
static Data* KviAnimatedPixmapCache::resize (Data * data, const QSize & size) inline static
Referenced by KviAnimatedPixmap::resize().
static void KviAnimatedPixmapCache::scheduleFrameChange (uint delay, KviAnimatedPixmapInterface * receiver) inline static
Referenced by KviAnimatedPixmap::nextFrame(), and KviAnimatedPixmap::start().
void KviAnimatedPixmapCache::timeoutEvent () protected virtual slot
References FRAME_DELAY, KviTimeUtils::getCurrentTimeMills(), i, m_animationTimer, and m_timerData.
Referenced by KviAnimatedPixmapCache().
Member Data Documentation
QTimer KviAnimatedPixmapCache::m_animationTimer protected
Referenced by internalScheduleFrameChange(), KviAnimatedPixmapCache(), and timeoutEvent().
QMutex KviAnimatedPixmapCache::m_cacheMutex mutable protected
Referenced by internalFree(), internalLoad(), and internalResize().
QMultiHash<QString, Data *> KviAnimatedPixmapCache::m_hCache protected
Referenced by internalFree(), internalLoad(), and internalResize().
KviAnimatedPixmapCache * KviAnimatedPixmapCache::m_pInstance = nullptr static protected
Referenced by done(), init(), KviAnimatedPixmapCache(), and ~KviAnimatedPixmapCache().
QMultiMap<long long, KviAnimatedPixmapInterface *> KviAnimatedPixmapCache::m_timerData protected
Referenced by internalNotifyDelete(), internalScheduleFrameChange(), and timeoutEvent().
QMutex KviAnimatedPixmapCache::m_timerMutex mutable protected
Referenced by internalNotifyDelete(), and internalScheduleFrameChange().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviAnimatedPixmapCache.h
src/kvilib/ext/KviAnimatedPixmapCache.cpp