KVIrc: KviSoundPlayer Class Reference
KviSoundPlayer Class Reference
#include <libkvisnd.h>
Public Member Functions
void detectSoundSystem ()
void getAvailableSoundSystems (QStringList *l)
bool havePlayingSounds ()
bool isMuted ()
KviSoundPlayer ()
bool play (const QString &szFileName)
void setMuted (bool muted)
virtual ~KviSoundPlayer ()
Protected Member Functions
void cleanupAfterLastPlayerEntry ()
void cleanupNull ()
void cleanupQt ()
virtual bool event (QEvent *e)
bool playNull (const QString &szFileName)
bool playQt (const QString &szFileName)
COMPILE_PHONON_SUPPORT.
void registerSoundThread (KviSoundThread *t)
void stopAllSoundThreads ()
void unregisterSoundThread (KviSoundThread *t)
Protected Attributes
KviSoundPlayerEntry * m_pLastUsedSoundPlayerEntry
COMPILE_PHONON_SUPPORT.
KviPointerHashTable< QString,
KviSoundPlayerEntry > * m_pSoundSystemDict
KviPointerList< KviSoundThread > * m_pThreadList
Friends
class KviSoundThread
Constructor & Destructor Documentation
KviSoundPlayer::KviSoundPlayer ()
COMPILE_PHONON_SUPPORT
COMPILE_PHONON_SUPPORT
COMPILE_ON_WINDOWS
COMPILE_ON_WINDOWS
References cleanupNull(), cleanupQt(), KviPointerHashTable< Key, T >::insert(), KVI_PTR2MEMBER, m_pLastUsedSoundPlayerEntry, m_pSoundSystemDict, m_pThreadList, NULL, playNull(), playQt(), KviPointerHashTable< Key, T >::setAutoDelete(), and KviPointerList< T >::setAutoDelete().
KviSoundPlayer::~KviSoundPlayer () [virtual]
References cleanupAfterLastPlayerEntry(), KviThreadManager::killPendingEvents(), m_pLastUsedSoundPlayerEntry, m_pSoundSystemDict, m_pThreadList, and stopAllSoundThreads().
Member Function Documentation
void KviSoundPlayer::cleanupAfterLastPlayerEntry () [protected]
References KviSoundPlayerEntry::cleanupRoutine(), m_pLastUsedSoundPlayerEntry, NULL, r, and stopAllSoundThreads().
Referenced by play(), and ~KviSoundPlayer().
void KviSoundPlayer::cleanupNull () [protected]
Referenced by KviSoundPlayer().
void KviSoundPlayer::cleanupQt () [protected]
Referenced by KviSoundPlayer().
void KviSoundPlayer::detectSoundSystem ()
References KVI_OPTION_STRING, KviOption_stringSoundSystem, and NULL.
Referenced by play(), snd_kvs_cmd_autodetect(), and snd_module_ctrl().
bool KviSoundPlayer::event (QEvent * e) [protected, virtual]
References KVI_THREAD_EVENT, and t().
void KviSoundPlayer::getAvailableSoundSystems (QStringList * l)
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), and m_pSoundSystemDict.
Referenced by snd_module_ctrl().
bool KviSoundPlayer::havePlayingSounds ()
References KviPointerList< T >::count(), and m_pThreadList.
Referenced by snd_module_can_unload().
bool KviSoundPlayer::isMuted () [inline]
References KVI_OPTION_BOOL, and KviOption_boolMuteAllSounds.
Referenced by play(), playQt(), and snd_kvs_fnc_ismuted().
bool KviSoundPlayer::play (const QString & szFileName)
References cleanupAfterLastPlayerEntry(), detectSoundSystem(), e, KviQString::equalCI(), KviPointerHashTable< Key, T >::find(), isMuted(), KVI_OPTION_STRING, KviOption_stringSoundSystem, m_pLastUsedSoundPlayerEntry, m_pSoundSystemDict, KviSoundPlayerEntry::playRoutine(), and r.
Referenced by playQt(), snd_kvs_cmd_play(), and snd_module_ctrl().
bool KviSoundPlayer::playNull (const QString & szFileName) [protected]
Referenced by KviSoundPlayer().
bool KviSoundPlayer::playQt (const QString & szFileName) [protected]
COMPILE_PHONON_SUPPORT.
COMPILE_ON_WINDOWS COMPILE_ON_WINDOWS
References isMuted(), and play().
Referenced by KviSoundPlayer().
void KviSoundPlayer::registerSoundThread (KviSoundThread * t) [protected]
References KviPointerList< T >::append(), and m_pThreadList.
Referenced by KviSoundThread::KviSoundThread().
void KviSoundPlayer::setMuted (bool muted) [inline]
References KVI_OPTION_BOOL, and KviOption_boolMuteAllSounds.
Referenced by snd_kvs_cmd_mute(), and snd_kvs_cmd_unmute().
void KviSoundPlayer::stopAllSoundThreads () [protected]
References KviPointerList< T >::first(), m_pThreadList, KviPointerList< T >::setAutoDelete(), and t().
Referenced by cleanupAfterLastPlayerEntry(), and ~KviSoundPlayer().
void KviSoundPlayer::unregisterSoundThread (KviSoundThread * t) [protected]
References m_pThreadList, and KviPointerList< T >::removeRef().
Referenced by KviSoundThread::~KviSoundThread().
Friends And Related Function Documentation
friend class KviSoundThread [friend]
Member Data Documentation
KviSoundPlayerEntry* KviSoundPlayer::m_pLastUsedSoundPlayerEntry [protected]
COMPILE_PHONON_SUPPORT.
Referenced by cleanupAfterLastPlayerEntry(), KviSoundPlayer(), play(), and ~KviSoundPlayer().
KviPointerHashTable<QString,KviSoundPlayerEntry>* KviSoundPlayer::m_pSoundSystemDict [protected]
Referenced by getAvailableSoundSystems(), KviSoundPlayer(), play(), and ~KviSoundPlayer().
KviPointerList<KviSoundThread>* KviSoundPlayer::m_pThreadList [protected]
Referenced by havePlayingSounds(), KviSoundPlayer(), registerSoundThread(), stopAllSoundThreads(), unregisterSoundThread(), and ~KviSoundPlayer().
The documentation for this class was generated from the following files:
src/modules/snd/libkvisnd.h
src/modules/snd/libkvisnd.cpp