KVIrc: OptionsWidget_tray Class Reference
OptionsWidget_tray Class Reference
#include <OptionsWidget_tray.h>
Public Member Functions
OptionsWidget_tray (QWidget *parent)
~OptionsWidget_tray ()
Protected Slots
void setEnabled (bool)
Protected Attributes
KviBoolSelector * m_pCloseInTray
KviBoolSelector * m_pEnable
KviBoolSelector * m_pEnableFlashing
KviBoolSelector * m_pLevelBasedNotify
KviTalGroupBox * m_pLevelsGroup
Constructor & Destructor Documentation
OptionsWidget_tray::OptionsWidget_tray (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addRowSpacer(), KviOptionsWidget::addUIntSelector(), connect(), KviOptionsWidget::createLayout(), KviOption_boolCloseInTray, KviOption_boolEnableTrayIconFlashing, KviOption_boolShowDockExtension, KviOption_boolUseLevelBasedTrayNotification, KviOption_uintMinTrayHighLevelMessage, KviOption_uintMinTrayLowLevelMessage, m_pCloseInTray, m_pEnable, m_pEnableFlashing, m_pLevelBasedNotify, m_pLevelsGroup, and setEnabled().
OptionsWidget_tray::~OptionsWidget_tray ()
Member Function Documentation
void OptionsWidget_tray::setEnabled (bool) [protected, slot]
References KviMainWindow::executeInternalCommand(), g_pMainWindow, KVI_INTERNALCOMMAND_TRAYICON_HIDE, KVI_INTERNALCOMMAND_TRAYICON_SHOW, m_pCloseInTray, m_pEnable, m_pEnableFlashing, m_pLevelBasedNotify, m_pLevelsGroup, and KviBoolSelector::setEnabled().
Referenced by OptionsWidget_tray().
Member Data Documentation
KviBoolSelector* OptionsWidget_tray::m_pCloseInTray [protected]
Referenced by OptionsWidget_tray(), and setEnabled().
KviBoolSelector* OptionsWidget_tray::m_pEnable [protected]
Referenced by OptionsWidget_tray(), and setEnabled().
KviBoolSelector* OptionsWidget_tray::m_pEnableFlashing [protected]
Referenced by OptionsWidget_tray(), and setEnabled().
KviBoolSelector* OptionsWidget_tray::m_pLevelBasedNotify [protected]
Referenced by OptionsWidget_tray(), and setEnabled().
KviTalGroupBox* OptionsWidget_tray::m_pLevelsGroup [protected]
Referenced by OptionsWidget_tray(), and setEnabled().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_tray.h
src/modules/options/OptionsWidget_tray.cpp