KVIrc: KviRijndaelEngine Class Reference
KviRijndaelEngine Class Reference
#include <libkvirijndael_cryptopp.h>
Public Member Functions
virtual
KviCryptEngine::DecryptResult decrypt (const char *pcInBuffer, KviCString &szPlainText)
virtual
KviCryptEngine::EncryptResult encrypt (const char *pcPlainText, KviCString &szOutBuffer)
virtual bool init (const char *pcEncKey, int iEncKeyLen, const char *pcDecKey, int iDecKeyLen)
KviRijndaelEngine ()
virtual ~KviRijndaelEngine ()
Protected Member Functions
virtual int getEncoding ()
virtual int getKeyLen ()
Private Attributes
std::string m_szDecKey
std::string m_szEncKey
Constructor & Destructor Documentation
KviRijndaelEngine::KviRijndaelEngine ()
References KviPointerList< T >::append(), m_szDecKey, and m_szEncKey.
KviRijndaelEngine::~KviRijndaelEngine () [virtual]
References m_szDecKey, m_szEncKey, and KviPointerList< T >::removeRef().
Member Function Documentation
KviCryptEngine::DecryptResult KviRijndaelEngine::decrypt (const char * pcInBuffer, KviCString & szPlainText) [virtual]
References __tr2qs, KviMircCntrl::CryptEscape, KviCryptEngine::DecryptError, KviCryptEngine::DecryptOkWasEncrypted, KviCryptEngine::DecryptOkWasPlainText, e, getEncoding(), KVI_RIJNDAEL_B64, KVI_RIJNDAEL_HEX, m_szDecKey, and u.
KviCryptEngine::EncryptResult KviRijndaelEngine::encrypt (const char * pcPlainText, KviCString & szOutBuffer) [virtual]
References __tr2qs, KviMircCntrl::CryptEscape, e, KviCryptEngine::Encrypted, KviCryptEngine::EncryptError, getEncoding(), KVI_RIJNDAEL_B64, KVI_RIJNDAEL_HEX, m_szEncKey, KviCString::prepend(), and u.
virtual int KviRijndaelEngine::getEncoding () [inline, protected, virtual]
Reimplemented in KviRijndael128HexEngine, KviRijndael192HexEngine, KviRijndael256HexEngine, KviRijndael128Base64Engine, KviRijndael192Base64Engine, and KviRijndael256Base64Engine.
Referenced by decrypt(), and encrypt().
virtual int KviRijndaelEngine::getKeyLen () [inline, protected, virtual]
Reimplemented in KviRijndael128HexEngine, KviRijndael192HexEngine, KviRijndael256HexEngine, KviRijndael128Base64Engine, KviRijndael192Base64Engine, and KviRijndael256Base64Engine.
Referenced by init().
bool KviRijndaelEngine::init (const char * pcEncKey, int iEncKeyLen, const char * pcDecKey, int iDecKeyLen) [virtual]
References __tr2qs, getKeyLen(), m_szDecKey, and m_szEncKey.
Member Data Documentation
std::string KviRijndaelEngine::m_szDecKey [private]
Referenced by decrypt(), init(), KviRijndaelEngine(), and ~KviRijndaelEngine().
std::string KviRijndaelEngine::m_szEncKey [private]
Referenced by encrypt(), init(), KviRijndaelEngine(), and ~KviRijndaelEngine().
The documentation for this class was generated from the following files:
src/modules/rijndael/libkvirijndael_cryptopp.h
src/modules/rijndael/libkvirijndael_cryptopp.cpp