KVIrc: KviKvsTreeNodeDataList Class Reference
KviKvsTreeNodeDataList Class Reference
#include <KviKvsTreeNodeDataList.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
bool evaluate (KviKvsRunTimeContext *c, KviKvsVariantList *pBuffer)
KviKvsTreeNodeData * item (unsigned int uIdx)
KviKvsTreeNodeDataList (const QChar *pLocation)
KviKvsTreeNodeData * releaseFirst ()
~KviKvsTreeNodeDataList ()
Protected Member Functions
void addItem (KviKvsTreeNodeData *p)
void prependItem (KviKvsTreeNodeData *p)
Protected Attributes
KviPointerList
< KviKvsTreeNodeData > * m_pDataList
Friends
class KviKvsParser
Constructor & Destructor Documentation
KviKvsTreeNodeDataList::KviKvsTreeNodeDataList (const QChar * pLocation)
References m_pDataList, and KviPointerList< T >::setAutoDelete().
KviKvsTreeNodeDataList::~KviKvsTreeNodeDataList ()
References m_pDataList.
Member Function Documentation
void KviKvsTreeNodeDataList::addItem (KviKvsTreeNodeData * p) [protected]
References KviPointerList< T >::append(), m_pDataList, and KviKvsTreeNode::setParent().
Referenced by KviKvsParser::parseCommandParameterList(), KviKvsParser::parseCommaSeparatedParameterList(), and KviKvsParser::parseSpecialCommandHelp().
void KviKvsTreeNodeDataList::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Implements KviKvsTreeNode.
void KviKvsTreeNodeDataList::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Implements KviKvsTreeNode.
References KviPointerList< T >::first(), m_pDataList, KviPointerList< T >::next(), and t.
Referenced by KviKvsTreeNodeThisObjectFunctionCall::dump(), KviKvsTreeNodeSpecialCommandForeach::dump(), KviKvsTreeNodeSpecialCommandClass::dump(), KviKvsTreeNodeParameterReturn::dump(), KviKvsTreeNodeObjectFunctionCall::dump(), KviKvsTreeNodeModuleFunctionCall::dump(), KviKvsTreeNodeCoreFunctionCall::dump(), KviKvsTreeNodeBaseObjectFunctionCall::dump(), KviKvsTreeNodeAliasFunctionCall::dump(), and KviKvsTreeNodeCommandWithParameters::dumpParameterList().
bool KviKvsTreeNodeDataList::evaluate (KviKvsRunTimeContext * c, KviKvsVariantList * pBuffer)
References KviKvsVariantList::append(), KviKvsVariantList::clear(), KviPointerListIterator< T >::current(), m_pDataList, t, and v.
Referenced by KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeCoreFunctionCall::evaluateReadOnly(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeThisObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeBaseObjectFunctionCall::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeSpecialCommandForeach::execute(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsTreeNodeParameterReturn::execute(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeCoreSimpleCommand::execute(), KviKvsTreeNodeCoreCallbackCommand::execute(), and KviKvsTreeNodeAliasSimpleCommand::execute().
KviKvsTreeNodeData * KviKvsTreeNodeDataList::item (unsigned int uIdx)
References KviPointerList< T >::at(), KviPointerList< T >::count(), and m_pDataList.
Referenced by KviKvsModuleCallbackCommandCall::getParameterCode().
void KviKvsTreeNodeDataList::prependItem (KviKvsTreeNodeData * p) [protected]
References m_pDataList, KviPointerList< T >::prepend(), and KviKvsTreeNode::setParent().
KviKvsTreeNodeData * KviKvsTreeNodeDataList::releaseFirst ()
References d, KviPointerList< T >::first(), m_pDataList, KviPointerList< T >::removeFirst(), and KviPointerList< T >::setAutoDelete().
Friends And Related Function Documentation
friend class KviKvsParser [friend]
Reimplemented from KviKvsTreeNode.
Member Data Documentation
KviPointerList<KviKvsTreeNodeData>* KviKvsTreeNodeDataList::m_pDataList [protected]
Referenced by addItem(), dump(), evaluate(), item(), KviKvsTreeNodeDataList(), prependItem(), releaseFirst(), and ~KviKvsTreeNodeDataList().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeDataList.h
src/kvirc/kvs/tree/KviKvsTreeNodeDataList.cpp