KVIrc: RegisteredUsersDialogItem Class Reference
RegisteredUsersDialogItem Class Reference
#include <RegisteredUsersDialog.h>
Public Member Functions
virtual QString key (int, bool) const
RegisteredUsersDialogItem (QTreeWidgetItem *par, KviRegisteredUser *u)
void setUser (KviRegisteredUser *u)
KviRegisteredUser * user ()
~RegisteredUsersDialogItem ()
Public Member Functions inherited from RegisteredUsersDialogItemBase
RegisteredUsersDialogItemBase::Types type ()
Protected Attributes
QTextDocument m_pText
KviRegisteredUser * m_pUser
Friends
class RegisteredUsersDialogItemDelegate
Additional Inherited Members
Public Types inherited from RegisteredUsersDialogItemBase
enum Types { User, Group }
Protected Member Functions inherited from RegisteredUsersDialogItemBase
RegisteredUsersDialogItemBase (Types type, KviRegisteredUsersListView *par)
RegisteredUsersDialogItemBase (Types type, QTreeWidgetItem *par)
~RegisteredUsersDialogItemBase ()
Constructor & Destructor Documentation
RegisteredUsersDialogItem::RegisteredUsersDialogItem (QTreeWidgetItem * par, KviRegisteredUser * u)
References __tr2qs_ctx(), KviRegisteredUser::getProperty(), m_pText, m_pUser, KviRegisteredUser::name(), and t().
RegisteredUsersDialogItem::~RegisteredUsersDialogItem ()
Member Function Documentation
QString RegisteredUsersDialogItem::key (int , bool) const virtual
References m_pUser, and KviRegisteredUser::name().
void RegisteredUsersDialogItem::setUser (KviRegisteredUser * u) inline
References m_pUser, and u.
Referenced by RegisteredUsersDialog::editItem().
KviRegisteredUser* RegisteredUsersDialogItem::user () inline
References m_pUser.
Referenced by RegisteredUsersDialog::editItem(), RegisteredUsersDialog::itemPressed(), and RegisteredUsersDialogItemDelegate::paint().
Friends And Related Function Documentation
friend class RegisteredUsersDialogItemDelegate friend
Member Data Documentation
QTextDocument RegisteredUsersDialogItem::m_pText protected
Referenced by RegisteredUsersDialogItemDelegate::paint(), and RegisteredUsersDialogItem().
KviRegisteredUser* RegisteredUsersDialogItem::m_pUser protected
Referenced by key(), RegisteredUsersDialogItem(), setUser(), and user().
The documentation for this class was generated from the following files:
src/modules/reguser/RegisteredUsersDialog.h
src/modules/reguser/RegisteredUsersDialog.cpp