KVIrc: KviTextIcon Class Reference
KviTextIcon Class Reference
The class that holds the icons.
#include <KviTextIconManager.h>
Public Member Functions
KviAnimatedPixmap * animatedPixmap ()
Returns the animated pixmap associated to the icon.
QString filename ()
Returns the filename of the icon.
KviIconManager::SmallIcon id ()
Returns the id of the icon.
KviTextIcon (KviIconManager::SmallIcon eIcon)
Constructs the icon object.
KviTextIcon (QString szFile)
Constructs the icon object.
KviTextIcon (KviTextIcon *pIcon)
Constructs the icon object.
QPixmap * pixmap ()
Returns the pixmap associated to the icon.
void setFilename (QString szFileName)
Sets the filename of the icon.
void setId (int iIcon)
Sets the id of the icon.
void setId (KviIconManager::SmallIcon eIcon)
Sets the id of the icon.
void setPixmap (QPixmap *pIcon)
~KviTextIcon ()
Destroys the icon object.
Protected Attributes
KviIconManager::SmallIcon m_eIcon
KviAnimatedPixmap * m_pAnimatedPixmap
QString m_szFileName
Detailed Description
The class that holds the icons.
Constructor & Destructor Documentation
KviTextIcon::KviTextIcon (KviIconManager::SmallIcon eIcon)
Constructs the icon object.
Parameters:
eIcon The id of the icon
Returns:
KviTextIcon
KviTextIcon::KviTextIcon (QString szFile)
Constructs the icon object.
Parameters:
szFile The filename the icon
Returns:
KviTextIcon
References KviApplication::findImage(), g_pApp, KVI_OPTION_BOOL, KviOption_boolEnableAnimatedSmiles, m_pAnimatedPixmap, NULL, KviAnimatedPixmap::start(), and KviAnimatedPixmap::stop().
KviTextIcon::KviTextIcon (KviTextIcon * pIcon)
Constructs the icon object.
Parameters:
pIcon The pointer to the icon
Returns:
KviTextIcon
References id(), m_eIcon, m_pAnimatedPixmap, m_szFileName, and NULL.
KviTextIcon::~KviTextIcon ()
Destroys the icon object.
References m_pAnimatedPixmap.
Member Function Documentation
KviAnimatedPixmap* KviTextIcon::animatedPixmap () [inline]
Returns the animated pixmap associated to the icon.
Returns:
KviAnimatedPixmap *
References m_pAnimatedPixmap.
Referenced by KviIrcView::getTextLine(), and KviIrcView::paintEvent().
QString KviTextIcon::filename () [inline]
Returns the filename of the icon.
Returns:
QString
Referenced by texticons_kvs_fnc_get().
KviIconManager::SmallIcon KviTextIcon::id () [inline]
Returns the id of the icon.
Returns:
KviIconManager::SmallIcon
Referenced by KviHtmlGenerator::convertToHtml(), KviTextIcon(), and texticons_kvs_fnc_get().
QPixmap * KviTextIcon::pixmap ()
Returns the pixmap associated to the icon.
Returns:
QPixmap *
References g_pIconManager, KviIconManager::getPixmap(), KviIconManager::getSmallIcon(), m_eIcon, m_pAnimatedPixmap, m_szFileName, and KviAnimatedPixmap::pixmap().
Referenced by OptionsWidget_textIcons::chooseFromFile(), OptionsWidget_textIcons::iconSelected(), KviInputEditor::mousePressEvent(), KviTopicWidget::paintColoredText(), KviIrcView::paintEvent(), TextIconTableItem::setId(), and TextIconTableItem::TextIconTableItem().
void KviTextIcon::setFilename (QString szFileName)
Sets the filename of the icon.
Parameters:
szFileName The filename of the icon
Returns:
void
References KviApplication::findImage(), g_pApp, KVI_OPTION_BOOL, KviOption_boolEnableAnimatedSmiles, m_eIcon, m_pAnimatedPixmap, m_szFileName, KviIconManager::None, NULL, KviAnimatedPixmap::start(), and KviAnimatedPixmap::stop().
Referenced by OptionsWidget_textIcons::chooseFromFile(), and texticons_kvs_cmd_set().
void KviTextIcon::setId (KviIconManager::SmallIcon eIcon)
Sets the id of the icon.
Parameters:
eIcon The id of the icon
Returns:
void
References m_eIcon, and m_szFileName.
Referenced by OptionsWidget_textIcons::iconSelected(), TextIconTableItem::setId(), and texticons_kvs_cmd_set().
void KviTextIcon::setId (int iIcon)
Sets the id of the icon.
Parameters:
iIcon The id of the icon
Note:
This function is provided for convenience
Returns:
void
References g_pIconManager, KviIconManager::iconName(), m_eIcon, and m_szFileName.
void KviTextIcon::setPixmap (QPixmap * pIcon)
Member Data Documentation
KviIconManager::SmallIcon KviTextIcon::m_eIcon [protected]
Referenced by KviTextIcon(), pixmap(), setFilename(), and setId().
KviAnimatedPixmap* KviTextIcon::m_pAnimatedPixmap [protected]
Referenced by KviTextIcon(), pixmap(), setFilename(), and ~KviTextIcon().
QString KviTextIcon::m_szFileName [protected]
Referenced by KviTextIcon(), pixmap(), setFilename(), and setId().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviTextIconManager.h
src/kvirc/kernel/KviTextIconManager.cpp