KVIrc: KviWindowStack Class Reference
KviWindowStack Class Reference
Handles all docked KviWindow windows.
#include <KviWindowStack.h>
Public Member Functions
void addWindow (KviWindow *pWnd)
Add an KviWindow to the area.
void destroyWindow (KviWindow *pWnd)
Remove and delete the subwindow.
KviWindowStack (QWidget *pParent, const char *pcName)
Constructs the Mdi manager object.
void showAndActivate (KviWindow *pWnd)
Show the KviWindow and bring it to the front.
QMenu * windowPopup ()
Returns the window popup.
~KviWindowStack ()
Destroys the Mdi manager object.
Protected Slots
void currentWindowChanged (int iIdx)
void fillWindowPopup ()
void menuActivated (QAction *pAction)
Protected Attributes
QMenu * m_pWindowPopup
Filters out some events: (de)activation events, window switching.
Detailed Description
Handles all docked KviWindow windows.
Constructor & Destructor Documentation
KviWindowStack::KviWindowStack (QWidget * pParent, const char * pcName)
Constructs the Mdi manager object.
Parameters
pParent The parent widget
pcName The name of the manager
Returns
KviWindowStack
References connect(), currentWindowChanged(), fillWindowPopup(), m_pWindowPopup, and menuActivated().
KviWindowStack::~KviWindowStack () default
Destroys the Mdi manager object.
Member Function Documentation
void KviWindowStack::addWindow (KviWindow * pWnd)
Add an KviWindow to the area.
Parameters
pWnd The KviWindow
Returns
void
Referenced by KviMainWindow::dockWindow().
void KviWindowStack::currentWindowChanged (int iIdx) protected slot
References g_pMainWindow, and KviMainWindow::windowActivated().
Referenced by KviWindowStack().
void KviWindowStack::destroyWindow (KviWindow * pWnd)
Remove and delete the subwindow.
Parameters
pWnd The KviWindow which will be destroyed.
Returns
void
Referenced by KviMainWindow::closeWindow().
void KviWindowStack::fillWindowPopup () protected slot
References m_pWindowPopup, KviWindow::myIconPtr(), and w.
Referenced by KviWindowStack().
void KviWindowStack::menuActivated (QAction * pAction) protected slot
References showAndActivate(), and w.
Referenced by KviWindowStack().
void KviWindowStack::showAndActivate (KviWindow * pWnd)
Show the KviWindow and bring it to the front.
Parameters
pWnd The KviWindow which will be shown.
Returns
void
Referenced by KviMainWindow::addWindow(), menuActivated(), and KviMainWindow::setActiveWindow().
QMenu* KviWindowStack::windowPopup () inline
Returns the window popup.
Returns
QMenu *
Referenced by KviMenuBar::KviMenuBar().
Member Data Documentation
QMenu* KviWindowStack::m_pWindowPopup protected
Filters out some events: (de)activation events, window switching.
Returns
boolHolds the specialized window popup
Referenced by fillWindowPopup(), and KviWindowStack().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviWindowStack.h
src/kvirc/ui/KviWindowStack.cpp