KVIrc: KviProxyDataBase Class Reference
KviProxyDataBase Class Reference
#include <KviProxyDataBase.h>
Public Member Functions
void clear ()
KviProxy * currentProxy ()
KviProxy * findProxy (const KviProxy *pProxy, bool bName)
void insertProxy (KviProxy *prx)
KviProxyDataBase ()
void load (const QString &filename)
KviPointerList< KviProxy > * proxyList ()
void save (const QString &filename)
void setCurrentProxy (KviProxy *prx)
void updateProxyIp (const char *proxy, const char *ip)
~KviProxyDataBase ()
Private Attributes
KviProxy * m_pCurrentProxy
KviPointerList< KviProxy > * m_pProxyList
Constructor & Destructor Documentation
KviProxyDataBase::KviProxyDataBase ()
References m_pCurrentProxy, m_pProxyList, and KviPointerList< T >::setAutoDelete().
KviProxyDataBase::~KviProxyDataBase ()
References m_pProxyList.
Member Function Documentation
void KviProxyDataBase::clear ()
References m_pCurrentProxy, m_pProxyList, and KviPointerList< T >::setAutoDelete().
Referenced by OptionsWidget_proxy::commit(), and load().
KviProxy* KviProxyDataBase::currentProxy () inline
Referenced by OptionsWidget_proxy::commit(), KviIrcContext::connectToCurrentServer(), and OptionsWidget_proxy::fillProxyList().
KviProxy * KviProxyDataBase::findProxy (const KviProxy * pProxy, bool bName)
References KviPointerList< T >::first(), KviProxy::isIPv6(), m_pProxyList, KviProxy::m_szHostname, KviProxy::m_uPort, KviPointerList< T >::next(), p, and KviProxy::protocol().
Referenced by proxydb_get_helper(), proxydb_kvs_cmd_addProxy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), and proxydb_kvs_fnc_protocol().
void KviProxyDataBase::insertProxy (KviProxy * prx) inline
Referenced by OptionsWidget_proxy::commit(), and proxydb_kvs_cmd_addProxy().
void KviProxyDataBase::load (const QString & filename)
References KviPointerList< T >::append(), clear(), KviPointerList< T >::first(), KviCString::Format, i, KviProxy::m_bIsIPv6, m_pCurrentProxy, m_pProxyList, KviProxy::m_szHostname, KviProxy::m_szIp, KviProxy::m_szPass, KviProxy::m_szUser, KviProxy::m_uPort, p, KviCString::ptr(), KviConfigurationFile::Read, KviConfigurationFile::readBoolEntry(), KviConfigurationFile::readEntry(), KviConfigurationFile::readUIntEntry(), KviProxy::setNamedProtocol(), KviCString::sprintf(), and KviRuntimeInfo::type().
Referenced by KviApplication::setup().
KviPointerList<KviProxy>* KviProxyDataBase::proxyList () inline
Referenced by OptionsWidget_proxy::commit(), OptionsWidget_proxy::fillProxyList(), IrcServerDetailsWidget::IrcServerDetailsWidget(), and KviIrcServer::proxyServer().
void KviProxyDataBase::save (const QString & filename)
References KviConfigurationFile::clear(), KviPointerList< T >::count(), KviPointerList< T >::first(), KviCString::Format, KviProxy::Http, i, m_pCurrentProxy, m_pProxyList, KviPointerList< T >::next(), p, KviCString::ptr(), KviProxy::Socks5, KviCString::sprintf(), KviRuntimeInfo::type(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveProxyDataBase().
void KviProxyDataBase::setCurrentProxy (KviProxy * prx) inline
Referenced by OptionsWidget_proxy::commit().
void KviProxyDataBase::updateProxyIp (const char * proxy, const char * ip)
References KviPointerList< T >::first(), m_pProxyList, and KviPointerList< T >::next().
Referenced by KviIrcConnectionTargetResolver::proxyLookupTerminated().
Member Data Documentation
KviProxy* KviProxyDataBase::m_pCurrentProxy private
Referenced by clear(), KviProxyDataBase(), load(), and save().
KviPointerList<KviProxy>* KviProxyDataBase::m_pProxyList private
Referenced by clear(), findProxy(), KviProxyDataBase(), load(), save(), updateProxyIp(), and ~KviProxyDataBase().
The documentation for this class was generated from the following files:
src/kvilib/ext/KviProxyDataBase.h
src/kvilib/ext/KviProxyDataBase.cpp