KVIrc: KviMessageCatalogue Class Reference
KviMessageCatalogue Class Reference
The KviMessageCatalogue class.
#include <KviMessageCatalogue.h>
Public Member Functions
KviMessageCatalogue ()
Creates an instance of KviMessageCatalogue.
bool load (const QString &szName)
const char * translate (const char *pcText)
Translates the string.
const QString & translateToQString (const char *pcText)
Translates the string.
~KviMessageCatalogue ()
Destroys the instance of KviMessageCatalogue and frees all the relevant resources.
Protected Attributes
KviPointerHashTable< const
char *, KviTranslationEntry > * m_pMessages
QTextCodec * m_pTextCodec
Detailed Description
The KviMessageCatalogue class.
Author
Szymon Stefanek This file was originally part of KviLocale.h
Constructor & Destructor Documentation
KviMessageCatalogue::KviMessageCatalogue ()
Creates an instance of KviMessageCatalogue.
Returns
KviMessageCatalogue
References m_pMessages, m_pTextCodec, and KviPointerHashTable< Key, T >::setAutoDelete().
KviMessageCatalogue::~KviMessageCatalogue ()
Destroys the instance of KviMessageCatalogue and frees all the relevant resources.
References m_pMessages.
Member Function Documentation
bool KviMessageCatalogue::load (const QString & szName)
Parameters
szName
Returns
bool
References KviMemory::allocate(), KviLocale::codecForName(), KviCString::cutFromFirst(), KviCString::cutLeft(), e, f, KviCString::findFirstIdx(), KviMemory::free(), KviCString::hasData(), i, KviPointerHashTable< Key, T >::insert(), KviLocale::instance(), kvi_getFirstBiggerPrime(), KVI_LOCALE_MAGIC, KVI_LOCALE_MAGIC_SWAPPED, KVI_SWAP_IF_NEEDED, KviCString::len(), m_pMessages, m_pTextCodec, KviTranslationEntry::m_szEncodedTranslation, KviTranslationEntry::m_szKey, GnuMoFileHeader::magic, MO_REVISION_NUMBER, GnuMoFileHeader::nstrings, GnuMoFileHeader::orig_tab_offset, KviCString::ptr(), GnuMoFileHeader::revision, KviPointerHashTable< Key, T >::setAutoDelete(), GnuMoFileHeader::trans_tab_offset, and KviCString::trim().
Referenced by KviLocale::KviLocale(), and KviLocale::loadCatalogue().
const char * KviMessageCatalogue::translate (const char * pcText)
Translates the string.
Parameters
pcText The text to translate
Returns
const char *
References KviPointerHashTable< Key, T >::find(), m_pMessages, KviTranslationEntry::m_szEncodedTranslation, and KviCString::ptr().
Referenced by KviLocale::translate().
const QString & KviMessageCatalogue::translateToQString (const char * pcText)
Translates the string.
Parameters
pcText The text to translate
Returns
const QString &
References KviPointerHashTable< Key, T >::find(), KviPointerHashTable< Key, T >::insert(), m_pMessages, m_pTextCodec, KviTranslationEntry::m_pTranslation, KviTranslationEntry::m_szEncodedTranslation, KviTranslationEntry::m_szKey, and KviCString::ptr().
Referenced by KviKvsCoreFunctions::KVSCF(), KviTranslator::translate(), and KviLocale::translateToQString().
Member Data Documentation
KviPointerHashTable<const char *,KviTranslationEntry>* KviMessageCatalogue::m_pMessages protected
Referenced by KviMessageCatalogue(), load(), translate(), translateToQString(), and ~KviMessageCatalogue().
QTextCodec* KviMessageCatalogue::m_pTextCodec protected
Referenced by KviMessageCatalogue(), load(), and translateToQString().
The documentation for this class was generated from the following files:
src/kvilib/locale/KviMessageCatalogue.h
src/kvilib/locale/KviMessageCatalogue.cpp