KVIrc: HelpWidget Class Reference
HelpWidget Class Reference
#include <HelpWidget.h>
Public Member Functions
HelpWidget (QWidget *par, bool bIsStandalone=false)
virtual QSize sizeHint () const
QTextBrowser * textBrowser ()
~HelpWidget ()
Protected Slots
void showIndex ()
Protected Member Functions
virtual void resizeEvent (QResizeEvent *e)
Private Attributes
bool m_bIsStandalone
QToolButton * m_pBtnBackward
QToolButton * m_pBtnForward
QToolButton * m_pBtnIndex
QTextBrowser * m_pTextBrowser
KviTalHBox * m_pToolBar
Constructor & Destructor Documentation
HelpWidget::HelpWidget (QWidget * par, bool bIsStandalone = false)
References KviPointerList< T >::append(), connect(), g_pIconManager, KviIconManager::getBigIcon(), KVI_BIGICON_HELPBACK, KVI_BIGICON_HELPCLOSE, KVI_BIGICON_HELPFORWARD, KVI_BIGICON_HELPINDEX, m_bIsStandalone, m_pBtnBackward, m_pBtnForward, m_pBtnIndex, m_pTextBrowser, m_pToolBar, KviTalHBox::setStretchFactor(), and showIndex().
HelpWidget::~HelpWidget ()
References m_bIsStandalone, and KviPointerList< T >::removeRef().
Member Function Documentation
void HelpWidget::resizeEvent (QResizeEvent * e) [protected, virtual]
References m_pTextBrowser, and m_pToolBar.
void HelpWidget::showIndex () [protected, slot]
References g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::Help, and m_pTextBrowser.
Referenced by HelpWidget().
QSize HelpWidget::sizeHint () const [virtual]
References m_pTextBrowser, m_pToolBar, and s.
QTextBrowser* HelpWidget::textBrowser () [inline]
References m_pTextBrowser.
Referenced by help_kvs_cmd_open().
Member Data Documentation
bool HelpWidget::m_bIsStandalone [private]
Referenced by HelpWidget(), and ~HelpWidget().
QToolButton* HelpWidget::m_pBtnBackward [private]
Referenced by HelpWidget().
QToolButton* HelpWidget::m_pBtnForward [private]
Referenced by HelpWidget().
QToolButton* HelpWidget::m_pBtnIndex [private]
Referenced by HelpWidget().
QTextBrowser* HelpWidget::m_pTextBrowser [private]
Referenced by HelpWidget(), resizeEvent(), showIndex(), sizeHint(), and textBrowser().
KviTalHBox* HelpWidget::m_pToolBar [private]
Referenced by HelpWidget(), resizeEvent(), and sizeHint().
The documentation for this class was generated from the following files:
src/modules/help/HelpWidget.h
src/modules/help/HelpWidget.cpp