KVIrc: BanFrame Class Reference
BanFrame Class Reference
#include <libkviurl.h>
Public Member Functions
BanFrame (QWidget *parent=0, const char *name=0, bool banEnable=false)
void saveBans (KviConfigurationFile *cfg)
~BanFrame ()
Protected Slots
void addBan ()
void enableClicked ()
void removeBan ()
Private Attributes
QPushButton * m_pAddBtn
QListWidget * m_pBanList
QCheckBox * m_pEnable
QPushButton * m_pRemoveBtn
Constructor & Destructor Documentation
BanFrame::BanFrame (QWidget * parent = 0, const char * name = 0, bool banEnable = false)
References __tr2qs, addBan(), connect(), enableClicked(), KviPointerList< T >::first(), g, loadBanList(), m_pAddBtn, m_pBanList, m_pEnable, m_pRemoveBtn, KviPointerList< T >::next(), and removeBan().
BanFrame::~BanFrame ()
Member Function Documentation
void BanFrame::addBan () [protected, slot]
References __tr2qs, KviPointerList< T >::append(), m_pBanList, and Normal.
Referenced by BanFrame().
void BanFrame::enableClicked () [protected, slot]
References m_pAddBtn, m_pBanList, m_pEnable, and m_pRemoveBtn.
Referenced by BanFrame().
void BanFrame::removeBan () [protected, slot]
References __tr2qs, KviPointerList< T >::first(), m_pBanList, KviPointerList< T >::next(), KviPointerList< T >::removeCurrent(), and KviMessageBox::warning().
Referenced by BanFrame().
void BanFrame::saveBans (KviConfigurationFile * cfg)
References m_pEnable, saveBanList(), and KviConfigurationFile::writeEntry().
Referenced by ConfigDialog::acceptbtn().
Member Data Documentation
QPushButton* BanFrame::m_pAddBtn [private]
Referenced by BanFrame(), and enableClicked().
QListWidget* BanFrame::m_pBanList [private]
Referenced by addBan(), BanFrame(), enableClicked(), and removeBan().
QCheckBox* BanFrame::m_pEnable [private]
Referenced by BanFrame(), enableClicked(), and saveBans().
QPushButton* BanFrame::m_pRemoveBtn [private]
Referenced by BanFrame(), and enableClicked().
The documentation for this class was generated from the following files:
src/modules/url/libkviurl.h
src/modules/url/libkviurl.cpp