KVIrc: KviRegisteredChannel Class Reference
KviRegisteredChannel Class Reference
#include <kvi_regchan.h>
Public Member Functions
KviRegisteredChannel (const KviStr &name, const KviStr &netmask)
const KviStr & name ()
const KviStr & netMask ()
KviStr * property (const char *name)
KviPointerHashTable< const
char *, KviStr > * propertyDict ()
void removeProperty (const char *name)
void setProperty (const char *name, KviStr *val)
~KviRegisteredChannel ()
Protected Attributes
KviPointerHashTable< const
char *, KviStr > * m_pPropertyDict
KviStr m_szName
KviStr m_szNetMask
Friends
class KviRegisteredChannelDataBase
Constructor & Destructor Documentation
KviRegisteredChannel::KviRegisteredChannel (const KviStr & name, const KviStr & netmask)
References m_pPropertyDict, m_szName, m_szNetMask, and KviPointerHashTable< Key, T >::setAutoDelete().
KviRegisteredChannel::~KviRegisteredChannel ()
References m_pPropertyDict.
Member Function Documentation
const KviStr& KviRegisteredChannel::name () [inline]
Referenced by KviRegisteredChannelDataBase::add(), and KviRegisteredChannelDataBase::remove().
const KviStr& KviRegisteredChannel::netMask () [inline]
Referenced by KviRegisteredChannelDataBase::add().
KviStr* KviRegisteredChannel::property (const char * name) [inline]
References KviStr::find().
Referenced by KviRegisteredChannelDataBase::add().
KviPointerHashTable<const char *,KviStr>* KviRegisteredChannel::propertyDict () [inline]
Referenced by KviRegisteredChannelDataBase::add().
void KviRegisteredChannel::removeProperty (const char * name) [inline]
void KviRegisteredChannel::setProperty (const char * name, KviStr * val) [inline]
Referenced by KviRegisteredChannelDataBase::add(), and KviRegisteredChannelDataBase::load().
Friends And Related Function Documentation
friend class KviRegisteredChannelDataBase [friend]
Member Data Documentation
KviPointerHashTable<const char *,KviStr>* KviRegisteredChannel::m_pPropertyDict [protected]
Referenced by KviRegisteredChannel(), and ~KviRegisteredChannel().
KviStr KviRegisteredChannel::m_szName [protected]
Referenced by KviRegisteredChannel().
KviStr KviRegisteredChannel::m_szNetMask [protected]
Referenced by KviRegisteredChannel().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/ext/kvi_regchan.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/ext/kvi_regchan.cpp