KVIrc: KviStatusBarUpdateIndicator Class Reference
KviStatusBarUpdateIndicator Class Reference
#include <KviStatusBarApplet.h>
Public Member Functions
KviStatusBarUpdateIndicator (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
virtual ~KviStatusBarUpdateIndicator ()
Public Member Functions inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * descriptor ()
KviMainWindow * frame ()
int index () const
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Static Public Member Functions
static void selfRegister (KviStatusBar *pBar)
Protected Slots
void binaryDataReceived (const KviDataBuffer &)
void requestCompleted (bool status)
void responseReceived (const QString &)
void toggleRevision ()
void toggleStartup ()
void updateDisplay ()
Protected Member Functions
void checkVersion ()
virtual void fillContextPopup (QMenu *p)
void getNewVersion ()
virtual void loadState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void saveState (const char *pcPrefix, KviConfigurationFile *pCfg)
virtual QString tipText (const QPoint &)
Private Attributes
bool m_bCheckDone
bool m_bCheckFailed
bool m_bUpdateOnStartup
bool m_bUpdateRevision
bool m_bUpdateStatus
KviHttpRequest * m_pHttpRequest
QString m_szHttpResponse
QString m_szNewVersion
Additional Inherited Members
Protected Attributes inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Constructor & Destructor Documentation
KviStatusBarUpdateIndicator::KviStatusBarUpdateIndicator (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
References g_pIconManager, KviIconManager::getSmallIcon(), m_bCheckDone, m_bCheckFailed, m_bUpdateOnStartup, m_bUpdateRevision, m_bUpdateStatus, m_pHttpRequest, KviIconManager::NotUpdate, and updateDisplay().
KviStatusBarUpdateIndicator::~KviStatusBarUpdateIndicator () virtual default
Member Function Documentation
void KviStatusBarUpdateIndicator::binaryDataReceived (const KviDataBuffer & buffer) protected slot
References KviBuildInfo::buildRevision(), KviMiscUtils::compareVersions(), KviDataBuffer::data(), getNewVersion(), KVI_VERSION, m_bUpdateOnStartup, m_bUpdateRevision, m_bUpdateStatus, m_szNewVersion, KviDataBuffer::size(), and updateDisplay().
Referenced by checkVersion().
void KviStatusBarUpdateIndicator::checkVersion () protected
References binaryDataReceived(), connect(), KviHttpRequest::get(), m_bCheckDone, m_bUpdateRevision, m_pHttpRequest, requestCompleted(), responseReceived(), szUrl, and KviHttpRequest::WholeFile.
Referenced by loadState(), and mouseDoubleClickEvent().
void KviStatusBarUpdateIndicator::fillContextPopup (QMenu * p) protected virtual
Reimplemented from KviStatusBarApplet.
References __tr2qs, m_bUpdateOnStartup, m_bUpdateRevision, toggleRevision(), and toggleStartup().
void KviStatusBarUpdateIndicator::getNewVersion () protected
References KviBuildInfo::buildSystemName(), g_pActiveWindow, m_bUpdateRevision, m_szNewVersion, KviKvsScript::run(), and szUrl.
Referenced by binaryDataReceived(), and mouseDoubleClickEvent().
void KviStatusBarUpdateIndicator::loadState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References checkVersion(), KviCString::Format, m_bUpdateOnStartup, m_bUpdateRevision, KviCString::ptr(), and KviConfigurationFile::readBoolEntry().
void KviStatusBarUpdateIndicator::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
References checkVersion(), getNewVersion(), and m_bUpdateStatus.
void KviStatusBarUpdateIndicator::requestCompleted (bool status) protected slot
References m_pHttpRequest.
Referenced by checkVersion().
void KviStatusBarUpdateIndicator::responseReceived (const QString & szResponse) protected slot
References m_bCheckFailed, m_szHttpResponse, and updateDisplay().
Referenced by checkVersion().
void KviStatusBarUpdateIndicator::saveState (const char * pcPrefix, KviConfigurationFile * pCfg) protected virtual
Reimplemented from KviStatusBarApplet.
References KviCString::Format, m_bUpdateOnStartup, m_bUpdateRevision, KviCString::ptr(), and KviConfigurationFile::writeEntry().
void KviStatusBarUpdateIndicator::selfRegister (KviStatusBar * pBar) static
References __tr2qs, CreateStatusBarUpdateIndicator(), d, g_pIconManager, KviIconManager::getSmallIcon(), KviStatusBar::registerAppletDescriptor(), and KviIconManager::Update.
Referenced by KviStatusBar::KviStatusBar().
QString KviStatusBarUpdateIndicator::tipText (const QPoint &) protected virtual
Reimplemented from KviStatusBarApplet.
References __tr2qs, m_bCheckDone, m_bCheckFailed, m_bUpdateStatus, and m_szHttpResponse.
void KviStatusBarUpdateIndicator::toggleRevision () protected slot
References m_bUpdateRevision, m_bUpdateStatus, and updateDisplay().
Referenced by fillContextPopup().
void KviStatusBarUpdateIndicator::toggleStartup () protected slot
References m_bUpdateOnStartup.
Referenced by fillContextPopup().
void KviStatusBarUpdateIndicator::updateDisplay () protected slot
References KviIconManager::FailUpdate, g_pIconManager, KviIconManager::getSmallIcon(), m_bCheckFailed, m_bUpdateStatus, KviIconManager::NotUpdate, and KviIconManager::Update.
Referenced by binaryDataReceived(), KviStatusBarUpdateIndicator(), responseReceived(), and toggleRevision().
Member Data Documentation
bool KviStatusBarUpdateIndicator::m_bCheckDone private
Referenced by checkVersion(), KviStatusBarUpdateIndicator(), and tipText().
bool KviStatusBarUpdateIndicator::m_bCheckFailed private
Referenced by KviStatusBarUpdateIndicator(), responseReceived(), tipText(), and updateDisplay().
bool KviStatusBarUpdateIndicator::m_bUpdateOnStartup private
Referenced by binaryDataReceived(), fillContextPopup(), KviStatusBarUpdateIndicator(), loadState(), saveState(), and toggleStartup().
bool KviStatusBarUpdateIndicator::m_bUpdateRevision private
Referenced by binaryDataReceived(), checkVersion(), fillContextPopup(), getNewVersion(), KviStatusBarUpdateIndicator(), loadState(), saveState(), and toggleRevision().
bool KviStatusBarUpdateIndicator::m_bUpdateStatus private
Referenced by binaryDataReceived(), KviStatusBarUpdateIndicator(), mouseDoubleClickEvent(), tipText(), toggleRevision(), and updateDisplay().
KviHttpRequest* KviStatusBarUpdateIndicator::m_pHttpRequest private
Referenced by checkVersion(), KviStatusBarUpdateIndicator(), and requestCompleted().
QString KviStatusBarUpdateIndicator::m_szHttpResponse private
Referenced by responseReceived(), and tipText().
QString KviStatusBarUpdateIndicator::m_szNewVersion private
Referenced by binaryDataReceived(), and getNewVersion().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviStatusBarApplet.h
src/kvirc/ui/KviStatusBarApplet.cpp