KVIrc: PackThemeImageWidget Class Reference
PackThemeImageWidget Class Reference
#include <PackThemeDialog.h>
Public Member Functions
PackThemeImageWidget (PackThemeDialog *pParent)
~PackThemeImageWidget ()
Protected Slots
void imageSelectionChanged (const QString &szImagePath)
Protected Attributes
QLabel * m_pImageLabel
KviFileSelector * m_pImageSelector
QString m_szImagePath
Constructor & Destructor Documentation
PackThemeImageWidget::PackThemeImageWidget (PackThemeDialog * pParent)
References __tr2qs_ctx(), connect(), imageSelectionChanged(), KVI_FILTER_IMAGE, m_pImageLabel, m_pImageSelector, and m_szImagePath.
PackThemeImageWidget::~PackThemeImageWidget ()
Member Function Documentation
void PackThemeImageWidget::imageSelectionChanged (const QString & szImagePath) [protected, slot]
References __tr2qs_ctx(), m_pImageLabel, m_pImageSelector, and KviFileSelector::setSelection().
Referenced by PackThemeImageWidget().
Member Data Documentation
QLabel* PackThemeImageWidget::m_pImageLabel [protected]
Referenced by imageSelectionChanged(), and PackThemeImageWidget().
KviFileSelector* PackThemeImageWidget::m_pImageSelector [protected]
Referenced by imageSelectionChanged(), and PackThemeImageWidget().
QString PackThemeImageWidget::m_szImagePath [protected]
Referenced by PackThemeImageWidget().
The documentation for this class was generated from the following files:
src/modules/theme/PackThemeDialog.h
src/modules/theme/PackThemeDialog.cpp