KVIrc: KvsObject_slider Class Reference
KvsObject_slider Class Reference
#include <KvsObject_slider.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void valueChanged (int)
Protected Member Functions
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool lineStep (KviKvsObjectFunctionCall *c)
bool maxValue (KviKvsObjectFunctionCall *c)
bool minValue (KviKvsObjectFunctionCall *c)
bool pageStep (KviKvsObjectFunctionCall *c)
bool setLineStep (KviKvsObjectFunctionCall *c)
bool setMaxValue (KviKvsObjectFunctionCall *c)
bool setMinValue (KviKvsObjectFunctionCall *c)
bool setOrientation (KviKvsObjectFunctionCall *c)
bool setPageStep (KviKvsObjectFunctionCall *c)
bool setTickInterval (KviKvsObjectFunctionCall *c)
bool setTickmarks (KviKvsObjectFunctionCall *c)
bool setTracking (KviKvsObjectFunctionCall *c)
bool setValue (KviKvsObjectFunctionCall *c)
bool value (KviKvsObjectFunctionCall *c)
bool valueChangedEvent (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_slider::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_widget.
References connect(), and SET_OBJECT.
bool KvsObject_slider::lineStep (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::maxValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::minValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::pageStep (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setLineStep (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setMaxValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setMinValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setOrientation (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setPageStep (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setTickInterval (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setTickmarks (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setTracking (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::setValue (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_slider::value (KviKvsObjectFunctionCall * c) [protected]
void KvsObject_slider::valueChanged (int value) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_slider::valueChangedEvent (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_slider::widget () [inline]
Reimplemented from KvsObject_widget.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_slider.h
src/modules/objects/KvsObject_slider.cpp