KVIrc: HttpFileTransfer Class Reference
HttpFileTransfer Class Reference
#include <HttpFileTransfer.h>
Public Member Functions
virtual bool active ()
virtual int displayHeight (int iLineSpacing)
virtual void displayPaint (QPainter *p, int column, QRect rect)
virtual void fillContextPopup (QMenu *m)
HttpFileTransfer ()
virtual QString localFileName ()
KviHttpRequest * request ()
void setAutoClean (bool bAutoClean)
void setCompletionCallback (const QString &szCallback)
void setMagicIdentifier (const KviKvsVariant &vIdentifier)
void setNoOutput (bool bNoOutput)
void setNotifyCompletion (bool bNotify)
virtual bool startDownload ()
virtual QString tipText ()
~HttpFileTransfer ()
Public Member Functions inherited from KviFileTransfer
virtual void die ()
void displayUpdate ()
int id ()
void invokeTransferWindow (bool bCreateMinimized=false, bool bNoRaise=false)
KviFileTransfer ()
KviFileTransferManager * manager ()
KviWindow * outputWindow ()
virtual QString retryCommand ()
void setDisplayItem (KviTalTableWidgetItemEx *i)
bool terminated ()
KviWindow * transferWindow ()
~KviFileTransfer ()
Static Public Member Functions
static void done ()
static void init ()
static unsigned int runningTransfers ()
Protected Slots
void abort ()
void autoClean ()
void connectionEstablished ()
void contactingHost (const QString &ipandport)
void headersReceived (KviPointerHashTable< const char *, KviCString > *h)
void receivedResponse (const QString &response)
void requestSent (const QStringList &sl)
void resolvingHost (const QString &hostname)
void statusMessage (const QString &txt)
void transferTerminated (bool bSuccess)
Private Types
enum GeneralStatus {
Initializing, Connecting, Downloading, Success,
Failure
}
Private Attributes
bool m_bAutoClean
bool m_bNoOutput
bool m_bNotifyCompletion
GeneralStatus m_eGeneralStatus
QStringList m_lHeaders
QStringList m_lRequest
QTimer * m_pAutoCleanTimer
KviHttpRequest * m_pHttpRequest
QString m_szCompletionCallback
QString m_szStatusString
int m_TimerId
kvi_time_t m_tStartTime
kvi_time_t m_tTransferEndTime
kvi_time_t m_tTransferStartTime
KviKvsVariant m_vMagicIdentifier
Additional Inherited Members
Protected Attributes inherited from KviFileTransfer
int m_iId
KviTalTableWidgetItemEx * m_pDisplayItem
Member Enumeration Documentation
enum HttpFileTransfer::GeneralStatus private
Enumerator
Initializing
Connecting
Downloading
Success
Failure
Constructor & Destructor Documentation
HttpFileTransfer::HttpFileTransfer ()
References __tr2qs_ctx(), KviPointerList< T >::append(), connect(), connectionEstablished(), contactingHost(), headersReceived(), init(), Initializing, kvi_unixTime, m_bAutoClean, m_bNoOutput, m_bNotifyCompletion, m_eGeneralStatus, m_pAutoCleanTimer, m_pHttpRequest, m_szStatusString, m_tStartTime, m_tTransferEndTime, m_tTransferStartTime, receivedResponse(), requestSent(), resolvingHost(), statusMessage(), KviFileTransfer::terminated(), and transferTerminated().
HttpFileTransfer::~HttpFileTransfer ()
References m_pAutoCleanTimer, m_pHttpRequest, and KviPointerList< T >::removeRef().
Member Function Documentation
void HttpFileTransfer::abort () protected slot
References KviHttpRequest::abort(), and m_pHttpRequest.
Referenced by fillContextPopup().
bool HttpFileTransfer::active () virtual
Implements KviFileTransfer.
References Connecting, Downloading, and m_eGeneralStatus.
Referenced by fillContextPopup().
void HttpFileTransfer::autoClean () protected slot
References KviFileTransfer::die(), and m_TimerId.
Referenced by transferTerminated().
void HttpFileTransfer::connectionEstablished () protected slot
References __tr2qs_ctx(), KviFileTransfer::displayUpdate(), and m_szStatusString.
Referenced by HttpFileTransfer().
void HttpFileTransfer::contactingHost (const QString & ipandport) protected slot
References __tr2qs_ctx(), KviFileTransfer::displayUpdate(), and m_szStatusString.
Referenced by HttpFileTransfer().
int HttpFileTransfer::displayHeight (int iLineSpacing) virtual
Reimplemented from KviFileTransfer.
void HttpFileTransfer::displayPaint (QPainter * p, int column, QRect rect) virtual
Implements KviFileTransfer.
References __tr2qs_ctx(), COLUMN_FILEINFO, COLUMN_PROGRESS, COLUMN_TRANSFERTYPE, Connecting, Downloading, Failure, KviHttpRequest::fileName(), KviNetUtils::formatNetworkBandwidthString(), g_pHttpIcon, Initializing, kvi_timeSpan, kvi_unixTime, m_eGeneralStatus, m_pHttpRequest, m_szStatusString, m_tTransferEndTime, m_tTransferStartTime, KviQString::makeSizeReadable(), KviHttpRequest::receivedSize(), KviTimeUtils::secondsToDaysHoursMinsSecs(), Success, KviHttpRequest::totalSize(), KviUrl::url(), and KviHttpRequest::url().
void HttpFileTransfer::done () static
References KviPointerList< T >::first(), g_pHttpFileTransfers, g_pHttpIcon, and t().
Referenced by http_module_cleanup().
void HttpFileTransfer::fillContextPopup (QMenu * m) virtual
Implements KviFileTransfer.
References __tr2qs_ctx(), abort(), and active().
void HttpFileTransfer::headersReceived (KviPointerHashTable< const char *, KviCString > * h) protected slot
References __tr2qs_ctx(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KVI_OUT_GENERICSTATUS, m_bNoOutput, m_lHeaders, KviWindow::output(), s, and KviFileTransfer::transferWindow().
Referenced by HttpFileTransfer().
void HttpFileTransfer::init () static
References g_pHttpIcon, g_pIconManager, KviIconManager::getImage(), and KviPointerList< T >::setAutoDelete().
Referenced by http_module_init(), and HttpFileTransfer().
QString HttpFileTransfer::localFileName () virtual
Reimplemented from KviFileTransfer.
References KviHttpRequest::fileName(), and m_pHttpRequest.
void HttpFileTransfer::receivedResponse (const QString & response) protected slot
References __tr2qs_ctx(), KviFileTransfer::displayUpdate(), Downloading, kvi_unixTime, m_eGeneralStatus, m_lHeaders, m_szStatusString, and m_tTransferStartTime.
Referenced by HttpFileTransfer().
KviHttpRequest* HttpFileTransfer::request () inline
References m_pHttpRequest.
Referenced by http_kvs_complete_get().
void HttpFileTransfer::requestSent (const QStringList & sl) protected slot
References __tr2qs_ctx(), KviFileTransfer::displayUpdate(), KVI_OUT_GENERICSTATUS, m_bNoOutput, m_lRequest, m_szStatusString, KviWindow::output(), and KviFileTransfer::transferWindow().
Referenced by HttpFileTransfer().
void HttpFileTransfer::resolvingHost (const QString & hostname) protected slot
References __tr2qs_ctx(), KviFileTransfer::displayUpdate(), and m_szStatusString.
Referenced by HttpFileTransfer().
unsigned int HttpFileTransfer::runningTransfers () static
References KviPointerList< T >::count().
Referenced by http_module_can_unload().
void HttpFileTransfer::setAutoClean (bool bAutoClean) inline
References m_bAutoClean.
Referenced by http_kvs_complete_get().
void HttpFileTransfer::setCompletionCallback (const QString & szCallback) inline
References m_szCompletionCallback.
Referenced by http_kvs_complete_get().
void HttpFileTransfer::setMagicIdentifier (const KviKvsVariant & vIdentifier) inline
References m_vMagicIdentifier.
Referenced by http_kvs_complete_get().
void HttpFileTransfer::setNoOutput (bool bNoOutput) inline
References m_bNoOutput.
Referenced by http_kvs_complete_get().
void HttpFileTransfer::setNotifyCompletion (bool bNotify) inline
References m_bNotifyCompletion.
Referenced by http_kvs_complete_get().
bool HttpFileTransfer::startDownload () virtual
References Connecting, m_eGeneralStatus, m_pHttpRequest, and KviHttpRequest::start().
Referenced by http_kvs_complete_get().
void HttpFileTransfer::statusMessage (const QString & txt) protected slot
References KVI_OUT_GENERICSTATUS, m_bNoOutput, KviWindow::output(), and KviFileTransfer::transferWindow().
Referenced by HttpFileTransfer().
QString HttpFileTransfer::tipText () virtual
Reimplemented from KviFileTransfer.
References m_lHeaders, m_lRequest, and s.
void HttpFileTransfer::transferTerminated (bool bSuccess) protected slot
References __tr2qs_ctx(), KviApplication::activeConsole(), KviKvsVariantList::append(), autoClean(), connect(), KviFileTransfer::displayUpdate(), Failure, KviApplication::fileDownloadTerminated(), KviHttpRequest::fileName(), g_pApp, KVI_OUT_GENERICERROR, KVI_OUT_GENERICSUCCESS, kvi_unixTime, KviEvent_OnHTTPGetTerminated, KVS_TRIGGER_EVENT, KviHttpRequest::lastError(), m_bAutoClean, m_bNoOutput, m_bNotifyCompletion, m_eGeneralStatus, m_pAutoCleanTimer, m_pHttpRequest, m_szCompletionCallback, m_szStatusString, m_TimerId, m_tTransferEndTime, m_vMagicIdentifier, KviWindow::output(), KviKvsScript::run(), Success, KviFileTransfer::transferWindow(), KviUrl::url(), and KviHttpRequest::url().
Referenced by HttpFileTransfer().
Member Data Documentation
bool HttpFileTransfer::m_bAutoClean private
Referenced by HttpFileTransfer(), setAutoClean(), and transferTerminated().
bool HttpFileTransfer::m_bNoOutput private
Referenced by headersReceived(), HttpFileTransfer(), requestSent(), setNoOutput(), statusMessage(), and transferTerminated().
bool HttpFileTransfer::m_bNotifyCompletion private
Referenced by HttpFileTransfer(), setNotifyCompletion(), and transferTerminated().
GeneralStatus HttpFileTransfer::m_eGeneralStatus private
Referenced by active(), displayPaint(), HttpFileTransfer(), receivedResponse(), startDownload(), and transferTerminated().
QStringList HttpFileTransfer::m_lHeaders private
Referenced by headersReceived(), receivedResponse(), and tipText().
QStringList HttpFileTransfer::m_lRequest private
Referenced by requestSent(), and tipText().
QTimer* HttpFileTransfer::m_pAutoCleanTimer private
Referenced by HttpFileTransfer(), transferTerminated(), and ~HttpFileTransfer().
KviHttpRequest* HttpFileTransfer::m_pHttpRequest private
Referenced by abort(), displayPaint(), HttpFileTransfer(), localFileName(), request(), startDownload(), transferTerminated(), and ~HttpFileTransfer().
QString HttpFileTransfer::m_szCompletionCallback private
Referenced by setCompletionCallback(), and transferTerminated().
QString HttpFileTransfer::m_szStatusString private
Referenced by connectionEstablished(), contactingHost(), displayPaint(), HttpFileTransfer(), receivedResponse(), requestSent(), resolvingHost(), and transferTerminated().
int HttpFileTransfer::m_TimerId private
Referenced by autoClean(), and transferTerminated().
kvi_time_t HttpFileTransfer::m_tStartTime private
Referenced by HttpFileTransfer().
kvi_time_t HttpFileTransfer::m_tTransferEndTime private
Referenced by displayPaint(), HttpFileTransfer(), and transferTerminated().
kvi_time_t HttpFileTransfer::m_tTransferStartTime private
Referenced by displayPaint(), HttpFileTransfer(), and receivedResponse().
KviKvsVariant HttpFileTransfer::m_vMagicIdentifier private
Referenced by setMagicIdentifier(), and transferTerminated().
The documentation for this class was generated from the following files:
src/modules/http/HttpFileTransfer.h
src/modules/http/HttpFileTransfer.cpp