KVIrc: KviUserIdentityManager Class Reference
KviUserIdentityManager Class Reference
The class to manage the user identity.
#include <KviUserIdentityManager.h>
Public Member Functions
void copyFrom (KviUserIdentityManager *pWorkingCopy)
Carbon copy.
KviUserIdentityManager * createWorkingCopy ()
Creates a new working copy.
const KviUserIdentity * defaultIdentity ()
Returns the default identity It's NEVER null.
const KviUserIdentity * findIdentity (const QString &szId)
Searches fot an identity.
KviPointerHashTable< QString,
KviUserIdentity > * identityDict ()
Returns the identity dictionary.
void load (const QString &szFileName)
Loads the user identity database.
void releaseWorkingCopy (KviUserIdentityManager *pWorkingCopy)
Deletes the working copy.
void save (const QString &szFileName)
Saves the user identity database.
void setDefaultIdentity (const QString &szIdentityId)
Sets the default identity.
Static Public Member Functions
static void done ()
Deletese the user identity.
static void init ()
Initializes a new user identity.
static KviUserIdentityManager * instance ()
Returns the instance of the identity.
Protected Member Functions
KviUserIdentityManager ()
Constructs the user identity manager object.
~KviUserIdentityManager ()
Destroys the user identity manager object.
Protected Attributes
KviPointerHashTable< QString,
KviUserIdentity > * m_pIdentityDict
QString m_szDefaultIdentity
Static Protected Attributes
static KviUserIdentityManager * m_pInstance = nullptr
Detailed Description
The class to manage the user identity.
Constructor & Destructor Documentation
KviUserIdentityManager::KviUserIdentityManager () protected
Constructs the user identity manager object.
Returns
KviUserIdentityManager
References m_pIdentityDict, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by createWorkingCopy(), and init().
KviUserIdentityManager::~KviUserIdentityManager () protected
Destroys the user identity manager object.
References m_pIdentityDict.
Member Function Documentation
void KviUserIdentityManager::copyFrom (KviUserIdentityManager * pWorkingCopy)
Carbon copy.
Parameters
pWorkingCopy The source working copy
Returns
void
References KviPointerHashTable< Key, T >::clear(), KviUserIdentity::copyFrom(), KviPointerHashTableIterator< Key, T >::current(), KviUserIdentity::id(), m_pIdentityDict, m_szDefaultIdentity, and KviPointerHashTable< Key, T >::replace().
Referenced by createWorkingCopy().
KviUserIdentityManager * KviUserIdentityManager::createWorkingCopy ()
Creates a new working copy.
Returns
KviUserIdentityManager *
References copyFrom(), and KviUserIdentityManager().
const KviUserIdentity * KviUserIdentityManager::defaultIdentity ()
Returns the default identity It's NEVER null.
Returns
const KviUserIdentity *
References __tr2qs, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTable< Key, T >::find(), KviUserIdentity::id(), KVI_DEFAULT_NICKNAME1, KVI_DEFAULT_NICKNAME2, KVI_DEFAULT_NICKNAME3, KVI_DEFAULT_NICKNAME4, KVI_DEFAULT_NICKNAME_TOKEN, KVI_DEFAULT_PART_MESSAGE, KVI_DEFAULT_QUIT_MESSAGE, KVI_DEFAULT_REALNAME, KVI_DEFAULT_USERNAME, m_pIdentityDict, m_szDefaultIdentity, KviPointerHashTable< Key, T >::replace(), KviUserIdentity::setAltNickName1(), KviUserIdentity::setAltNickName2(), KviUserIdentity::setAltNickName3(), KviUserIdentity::setId(), KviUserIdentity::setNickName(), KviUserIdentity::setPartMessage(), KviUserIdentity::setQuitMessage(), KviUserIdentity::setRealName(), and KviUserIdentity::setUserName().
Referenced by KviIrcContext::connectToCurrentServer().
void KviUserIdentityManager::done () static
Deletese the user identity.
Returns
void
References m_pInstance.
Referenced by KviApplication::~KviApplication().
const KviUserIdentity* KviUserIdentityManager::findIdentity (const QString & szId) inline
Searches fot an identity.
Parameters
szId The identity id to find
Returns
const KviUserIdentity *
Referenced by KviIrcContext::connectToCurrentServer().
KviPointerHashTable<QString, KviUserIdentity>* KviUserIdentityManager::identityDict () inline
Returns the identity dictionary.
Returns
KviPointerHashTable<QString,KviUserIdentity> *
void KviUserIdentityManager::init () static
Initializes a new user identity.
Returns
void
References KviUserIdentityManager(), and m_pInstance.
Referenced by KviApplication::setup().
static KviUserIdentityManager* KviUserIdentityManager::instance () inline static
Returns the instance of the identity.
Returns
KviUserIdentityManager *
Referenced by KviIrcContext::connectToCurrentServer(), KviApplication::saveIdentities(), and KviApplication::setup().
void KviUserIdentityManager::load (const QString & szFileName)
Loads the user identity database.
Parameters
szFileName The filename where to load
Returns
void
References KviPointerHashTable< Key, T >::clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviQString::equalCI(), KviUserIdentity::id(), KviUserIdentity::load(), m_pIdentityDict, m_szDefaultIdentity, KviConfigurationFile::Read, KviConfigurationFile::readEntry(), KviPointerHashTable< Key, T >::replace(), and KviConfigurationFile::setGroup().
Referenced by KviApplication::setup().
void KviUserIdentityManager::releaseWorkingCopy (KviUserIdentityManager * pWorkingCopy)
Deletes the working copy.
Parameters
pWorkingCopy The source working copy
Returns
void
void KviUserIdentityManager::save (const QString & szFileName)
Saves the user identity database.
Parameters
szFileName The filename where to save
Returns
void
References KviConfigurationFile::clear(), KviPointerHashTableIterator< Key, T >::current(), m_pIdentityDict, m_szDefaultIdentity, KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveIdentities().
void KviUserIdentityManager::setDefaultIdentity (const QString & szIdentityId) inline
Sets the default identity.
Parameters
szIdentityId The identity id to set
Returns
void
Member Data Documentation
KviPointerHashTable<QString, KviUserIdentity>* KviUserIdentityManager::m_pIdentityDict protected
Referenced by copyFrom(), defaultIdentity(), KviUserIdentityManager(), load(), save(), and ~KviUserIdentityManager().
KviUserIdentityManager * KviUserIdentityManager::m_pInstance = nullptr static protected
Referenced by done(), and init().
QString KviUserIdentityManager::m_szDefaultIdentity protected
Referenced by copyFrom(), defaultIdentity(), load(), and save().
The documentation for this class was generated from the following files:
src/kvilib/irc/KviUserIdentityManager.h
src/kvilib/irc/KviUserIdentityManager.cpp