KVIrc: KviIrcUserEntry Class Reference
KviIrcUserEntry Class Reference
A class to handle the entries of the user database.
#include <KviIrcUserEntry.h>
Public Types
enum Gender { Male = 0, Female = 1, Unknown = 3 }
Defines the gender of the user.
enum UserMode {
UserOp = 1, Voice = 2, HalfOp = 4, Op = 8,
ChanAdmin = 16, ChanOwner = 32, ModeMask = UserOp | Voice | HalfOp | Op | ChanAdmin | ChanOwner
}
Defines the user mode in a channel.
Public Member Functions
KviAvatar * avatar ()
Returns the avatar of the user.
bool avatarRequested () const
Returns true if kvirc already made an attempt to download user's avatar.
KviAvatar * forgetAvatar ()
Removes the avatar associated to the user.
Gender gender ()
Returns the gender of the user.
bool hasHops ()
Returns true if the user has hops set.
bool hasHost ()
Returns true if the user has the hostname set.
bool hasRealName ()
Returns true if the user has the realname set.
bool hasServer ()
Returns true if the user has the server set.
bool hasUser ()
Returns true if the user has the username set.
int hops ()
Returns the number of hops.
const QString & host ()
Returns the hostname of the user.
bool isAway () const
Returns true if the user is in away mode.
bool isBot ()
Returns true if the user is marked as a bot.
bool isIrcOp () const
Returns true if the user is an irc operator.
KviIrcUserEntry (const QString &user, const QString &host)
Constructs the entry object.
int nRefs ()
Returns the number of references of the user in the database.
const QString & realName ()
Returns the realname of the user.
const QString & server ()
Returns the server of the user.
void setAvatar (KviAvatar *pAvatar=0)
Sets the avatar of the user.
void setAvatarRequested ()
Mark that kvirc is trying (already tried) to get user's avatar.
void setAway (bool bAway)
Sets the away state of the user.
void setBot (bool bIsBot)
Sets the user as a bot.
void setGender (Gender g)
Sets the gender of the user.
void setHops (int iHops)
Sets the number of hops of the user.
void setHost (const QString &szHost)
Sets the hostname of the user.
void setIrcOp (bool bIrcOp)
Sets the irc operator state of the user.
void setRealName (const QString &szReal)
Sets the realname of the user.
void setServer (const QString &szServ)
Sets the server of the user.
void setSmartNickColor (const int iColor)
Sets the ircview smart nick color of the user.
void setUser (const QString &szUser)
Sets the username of the user.
void setUserFlags (const QString &szFlags)
Sets the user global flags (eg: "G*")
int smartNickColor ()
Returns the ircview smart nick color of the user.
const QString & user ()
Returns the username of the user.
const QString & userFlags ()
Returns the user flags.
~KviIrcUserEntry ()
Destroys the object.
Protected Attributes
bool m_bAvatarRequested
bool m_bAway
bool m_bBot
bool m_bIrcOp
bool m_bNotFoundRegUserLoockup
bool m_bUseCustomColor
QColor m_cachedColor
Gender m_eGender
int m_iHops
int m_iSmartNickColor
int m_nRefs
KviAvatar * m_pAvatar
QString m_szHost
QString m_szLastRegisteredMatchNick
QString m_szRealName
QString m_szRegisteredUserName
QString m_szServer
QString m_szUser
QString m_szUserFlags
Friends
class KviIrcUserDataBase
Detailed Description
A class to handle the entries of the user database.
Member Enumeration Documentation
enum KviIrcUserEntry::Gender
Defines the gender of the user.
Enumerator
Male
Male
Female
Female
Unknown
Unknown
enum KviIrcUserEntry::UserMode
Defines the user mode in a channel.
Enumerator
UserOp
the user is an userop of the channel
Voice
the user is a voice of the channel
HalfOp
the user is a halfop of the channel
Op
the user is an operator of the channel
ChanAdmin
the user is an admin of the channel
ChanOwner
the user is an owner of the channel
ModeMask
Constructor & Destructor Documentation
KviIrcUserEntry::KviIrcUserEntry (const QString & user, const QString & host)
Constructs the entry object.
Parameters
user The user to add
host The host of the user
Returns
KviIrcUserEntry
References m_bAvatarRequested, m_bAway, m_bBot, m_bIrcOp, m_bNotFoundRegUserLoockup, m_bUseCustomColor, m_eGender, m_iHops, m_iSmartNickColor, m_nRefs, m_pAvatar, m_szHost, m_szUser, szHost, and Unknown.
KviIrcUserEntry::~KviIrcUserEntry ()
Destroys the object.
References m_pAvatar.
Member Function Documentation
KviAvatar* KviIrcUserEntry::avatar () inline
Returns the avatar of the user.
Returns
KviAvatar
Referenced by avatar_kvs_cmd_notify(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KviConsoleWindow::currentAvatar(), KviConsoleWindow::getUserTipText(), KviIrcConnection::loginToIrcServer(), KviApplication::notifierMessage(), KviIrcServerParser::parseLiteralJoin(), KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhoReply(), KviQueryWindow::setTarget(), and KviUserListEntry::updateAvatarData().
bool KviIrcUserEntry::avatarRequested () const inline
Returns true if kvirc already made an attempt to download user's avatar.
Returns
bool
Referenced by KviIrcServerParser::parseNumericWhoReply().
KviAvatar * KviIrcUserEntry::forgetAvatar ()
Removes the avatar associated to the user.
Returns
KviAvatar *
References m_pAvatar.
Referenced by KviUserListView::nickChange().
Gender KviIrcUserEntry::gender () inline
Returns the gender of the user.
Returns
Gender
Referenced by KviConsoleWindow::getUserTipText(), KviKvsCoreFunctions::KVSCF(), KviUserListView::nickChange(), KviUserListViewArea::paintEvent(), and KviIrcServerParser::parseNumericWhoisUser().
bool KviIrcUserEntry::hasHops () inline
Returns true if the user has hops set.
Returns
bool
Referenced by KviQueryWindow::getInfoLabelText(), and KviConsoleWindow::getUserTipText().
bool KviIrcUserEntry::hasHost () inline
Returns true if the user has the hostname set.
Returns
bool
Referenced by KviQueryWindow::getInfoLabelText(), KviKvsCoreFunctions::KVSCF(), KviIrcUserDataBase::registeredUser(), and KviConsoleWindow::setAvatar().
bool KviIrcUserEntry::hasRealName () inline
Returns true if the user has the realname set.
Returns
bool
Referenced by KviQueryWindow::getInfoLabelText(), and KviConsoleWindow::getUserTipText().
bool KviIrcUserEntry::hasServer () inline
Returns true if the user has the server set.
Returns
bool
Referenced by KviQueryWindow::getInfoLabelText(), and KviConsoleWindow::getUserTipText().
bool KviIrcUserEntry::hasUser () inline
Returns true if the user has the username set.
Returns
bool
Referenced by KviQueryWindow::getInfoLabelText(), KviKvsCoreFunctions::KVSCF(), KviIrcUserDataBase::registeredUser(), and KviConsoleWindow::setAvatar().
int KviIrcUserEntry::hops () inline
Returns the number of hops.
Returns
int
Referenced by KviQueryWindow::getInfoLabelText(), and KviConsoleWindow::getUserTipText().
const QString& KviIrcUserEntry::host () inline
Returns the hostname of the user.
Returns
const QString &
Referenced by chan_kvs_fnc_users(), KviUserListView::completeNickBashLike(), KviUserListView::completeNickStandard(), KviQueryWindow::getInfoLabelText(), KviConsoleWindow::getUserTipText(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviIrcConnection::loginComplete(), KviUserListView::nickChange(), KviIrcServerParser::parseLiteralKick(), KviIrcUserDataBase::registeredUser(), KviQueryWindow::setAliveQuery(), KviConsoleWindow::setAvatar(), and KviUserListView::userActionVerifyMask().
bool KviIrcUserEntry::isAway () const inline
Returns true if the user is in away mode.
Returns
bool
Referenced by KviQueryWindow::getInfoLabelText(), KviConsoleWindow::getUserTipText(), and KviUserListViewArea::paintEvent().
bool KviIrcUserEntry::isBot () inline
Returns true if the user is marked as a bot.
Returns
bool
Referenced by KviKvsCoreFunctions::KVSCF(), KviUserListView::nickChange(), and KviUserListViewArea::paintEvent().
bool KviIrcUserEntry::isIrcOp () const inline
Returns true if the user is an irc operator.
Returns
bool
Referenced by KviUserListView::insertUserEntry(), KviUserListView::maybeTip(), KviUserListViewArea::paintEvent(), KviUserListView::partInternal(), and KviUserListView::userStats().
int KviIrcUserEntry::nRefs () inline
Returns the number of references of the user in the database.
Returns
int
const QString& KviIrcUserEntry::realName () inline
Returns the realname of the user.
Returns
const QString &
Referenced by KviQueryWindow::getInfoLabelText(), KviConsoleWindow::getUserTipText(), and KviKvsCoreFunctions::KVSCF().
const QString& KviIrcUserEntry::server () inline
Returns the server of the user.
Returns
const QString &
Referenced by KviQueryWindow::getInfoLabelText(), and KviConsoleWindow::getUserTipText().
void KviIrcUserEntry::setAvatar (KviAvatar * pAvatar = 0)
Sets the avatar of the user.
Parameters
pAvatar The avatar
Returns
void
Warning
The ownership passes to this class!
References m_pAvatar.
Referenced by avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), KviConsoleWindow::checkDefaultAvatar(), KviConsoleWindow::currentAvatar(), KviIrcConnection::loginToIrcServer(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseLiteralJoin(), KviConsoleWindow::setAvatar(), and KviConsoleWindow::setAvatarFromOptions().
void KviIrcUserEntry::setAvatarRequested () inline
Mark that kvirc is trying (already tried) to get user's avatar.
Referenced by KviIrcServerParser::parseNumericWhoReply().
void KviIrcUserEntry::setAway (bool bAway) inline
Sets the away state of the user.
Parameters
bAway The away state
Returns
void
Referenced by KviIrcServerParser::parseNumericWhoisAway(), and KviIrcServerParser::parseNumericWhoReply().
void KviIrcUserEntry::setBot (bool bIsBot) inline
Sets the user as a bot.
Parameters
bIsBot If the user is a bot
Returns
void
Referenced by setRealName().
void KviIrcUserEntry::setGender (Gender g) inline
Sets the gender of the user.
Parameters
g The gender
Returns
void
References g.
Referenced by KviIrcConnection::loginToIrcServer(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseCtcpReplyUserinfo(), and setRealName().
void KviIrcUserEntry::setHops (int iHops) inline
Sets the number of hops of the user.
Parameters
iHops The number of hops
Returns
void
Referenced by KviIrcServerParser::parseNumericWhoReply().
void KviIrcUserEntry::setHost (const QString & szHost) inline
Sets the hostname of the user.
Parameters
szHost The hostname
Returns
void
References szHost.
Referenced by KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhoReply(), KviUserListView::userAction(), KviUserListView::userActionVerifyMask(), and KviIrcConnection::userInfoReceived().
void KviIrcUserEntry::setIrcOp (bool bIrcOp) inline
Sets the irc operator state of the user.
Parameters
bIrcOp The ircop state
Returns
void
Referenced by KviIrcServerParser::parseNumericWhoReply().
void KviIrcUserEntry::setRealName (const QString & szReal)
Sets the realname of the user.
Parameters
szReal The realname
Returns
void
References Female, KviNickColors::getSmartColorIntByMircColor(), KviControlCodes::getUnicodeColorBytes(), m_szRealName, Male, KviControlCodes::Reset, setBot(), setGender(), and setSmartNickColor().
Referenced by KviIrcServerParser::parseNumericWhoisUser(), and KviIrcServerParser::parseNumericWhoReply().
void KviIrcUserEntry::setServer (const QString & szServ) inline
Sets the server of the user.
Parameters
szServ The server
Returns
void
Referenced by KviIrcServerParser::parseNumericWhoisServer(), and KviIrcServerParser::parseNumericWhoReply().
void KviIrcUserEntry::setSmartNickColor (const int iColor) inline
Sets the ircview smart nick color of the user.
Parameters
iColor The color value
Returns
void
Referenced by KviConsoleWindow::outputPrivmsg(), KviIrcServerParser::parseLiteralNick(), and setRealName().
void KviIrcUserEntry::setUser (const QString & szUser) inline
Sets the username of the user.
Parameters
szUser The username
Returns
void
Referenced by KviIrcServerParser::parseNumericWhoisUser(), KviIrcServerParser::parseNumericWhoReply(), KviUserListView::userAction(), KviUserListView::userActionVerifyMask(), and KviIrcConnection::userInfoReceived().
void KviIrcUserEntry::setUserFlags (const QString & szFlags) inline
Sets the user global flags (eg: "G*")
Parameters
szFlags
Returns
void
Referenced by KviIrcServerParser::parseNumericWhoReply().
int KviIrcUserEntry::smartNickColor () inline
Returns the ircview smart nick color of the user.
Returns
int
Referenced by KviConsoleWindow::outputPrivmsg().
const QString& KviIrcUserEntry::user () inline
Returns the username of the user.
Returns
const QString &
Referenced by chan_kvs_fnc_users(), KviUserListView::completeNickBashLike(), KviUserListView::completeNickStandard(), KviQueryWindow::getInfoLabelText(), KviConsoleWindow::getUserTipText(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviIrcConnection::loginComplete(), KviUserListView::nickChange(), KviIrcServerParser::parseLiteralKick(), KviIrcUserDataBase::registeredUser(), KviQueryWindow::setAliveQuery(), KviConsoleWindow::setAvatar(), and KviUserListView::userActionVerifyMask().
const QString& KviIrcUserEntry::userFlags () inline
Returns the user flags.
Returns
const QString &
Referenced by KviKvsCoreFunctions::KVSCF().
Friends And Related Function Documentation
friend class KviIrcUserDataBase friend
Member Data Documentation
bool KviIrcUserEntry::m_bAvatarRequested protected
Referenced by KviIrcUserEntry().
bool KviIrcUserEntry::m_bAway protected
Referenced by KviIrcUserEntry().
bool KviIrcUserEntry::m_bBot protected
Referenced by KviIrcUserEntry().
bool KviIrcUserEntry::m_bIrcOp protected
Referenced by KviIrcUserEntry().
bool KviIrcUserEntry::m_bNotFoundRegUserLoockup protected
Referenced by KviIrcUserDataBase::customColor(), KviIrcUserDataBase::haveCustomColor(), KviIrcUserEntry(), KviIrcUserDataBase::registeredDatabaseCleared(), KviIrcUserDataBase::registeredUser(), KviIrcUserDataBase::registeredUserAdded(), and KviIrcUserDataBase::registeredUserChanged().
bool KviIrcUserEntry::m_bUseCustomColor protected
Referenced by KviIrcUserDataBase::haveCustomColor(), KviIrcUserEntry(), and KviIrcUserDataBase::registeredUser().
QColor KviIrcUserEntry::m_cachedColor protected
Referenced by KviIrcUserDataBase::customColor(), and KviIrcUserDataBase::registeredUser().
Gender KviIrcUserEntry::m_eGender protected
Referenced by KviIrcUserEntry().
int KviIrcUserEntry::m_iHops protected
Referenced by KviIrcUserEntry().
int KviIrcUserEntry::m_iSmartNickColor protected
Referenced by KviIrcUserEntry().
int KviIrcUserEntry::m_nRefs protected
Referenced by KviIrcUserDataBase::insertUser(), KviIrcUserEntry(), and KviIrcUserDataBase::removeUser().
KviAvatar* KviIrcUserEntry::m_pAvatar protected
Referenced by forgetAvatar(), KviIrcUserEntry(), setAvatar(), and ~KviIrcUserEntry().
QString KviIrcUserEntry::m_szHost protected
Referenced by KviIrcUserDataBase::insertUser(), and KviIrcUserEntry().
QString KviIrcUserEntry::m_szLastRegisteredMatchNick protected
Referenced by KviIrcUserDataBase::customColor(), KviIrcUserDataBase::haveCustomColor(), and KviIrcUserDataBase::registeredUser().
QString KviIrcUserEntry::m_szRealName protected
Referenced by setRealName().
QString KviIrcUserEntry::m_szRegisteredUserName protected
Referenced by KviIrcUserDataBase::registeredDatabaseCleared(), KviIrcUserDataBase::registeredUser(), KviIrcUserDataBase::registeredUserAdded(), and KviIrcUserDataBase::registeredUserChanged().
QString KviIrcUserEntry::m_szServer protected
QString KviIrcUserEntry::m_szUser protected
Referenced by KviIrcUserDataBase::insertUser(), and KviIrcUserEntry().
QString KviIrcUserEntry::m_szUserFlags protected
The documentation for this class was generated from the following files:
src/kvilib/irc/KviIrcUserEntry.h
src/kvilib/irc/KviIrcUserEntry.cpp