KVIrc: XmlFunctions Class Reference
XmlFunctions Class Reference
#include <XmlFunctions.h>
Static Public Member Functions
static QDomNode getNode (const QDomNode &rootNode, const QString &path)
static QString getNodeAttribute (const QDomNode &node, const QString &attribute)
static QDomNode getNodeChildByKey (const QDomNodeList &childNodes, const QString &keyTagName, const QString &keyValue)
static QString getNodeValue (const QDomNode &rootNode, const QString &path)
static QString getSource (const QDomNode &node, int indent=0)
Detailed Description
Some helper functions to make the handling of QDom easier.
Author:
Diederik van der Boor
Member Function Documentation
QDomNode XmlFunctions::getNode (const QDomNode & rootNode, const QString & path) [static]
References i.
Referenced by getNodeValue(), UPnP::RootService::gotInformationResponse(), and UPnP::Service::slotRequestFinished().
QString XmlFunctions::getNodeAttribute (const QDomNode & node, const QString & attribute) [static]
QDomNode XmlFunctions::getNodeChildByKey (const QDomNodeList & childNodes, const QString & keyTagName, const QString & keyValue) [static]
References i.
Referenced by UPnP::RootService::getServiceById(), and UPnP::RootService::getServiceByType().
QString XmlFunctions::getNodeValue (const QDomNode & rootNode, const QString & path) [static]
References getNode().
Referenced by UPnP::RootService::addDeviceServices(), UPnP::RootService::getServiceById(), UPnP::RootService::getServiceByType(), UPnP::Service::gotActionErrorResponse(), and UPnP::RootService::gotInformationResponse().
QString XmlFunctions::getSource (const QDomNode & node, int indent = 0) [static]
The documentation for this class was generated from the following files:
src/modules/upnp/XmlFunctions.h
src/modules/upnp/XmlFunctions.cpp