KVIrc: AddonListViewItem Class Reference
AddonListViewItem Class Reference
#include <AddonManagementDialog.h>
Public Member Functions
KviKvsScriptAddon * addon ()
AddonListViewItem (KviTalListWidget *v, KviKvsScriptAddon *a)
~AddonListViewItem ()
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Protected Attributes
KviKvsScriptAddon * m_pAddon
QPixmap * m_pIcon
QListWidget * m_pListWidget
QTextDocument * m_pText
QString m_szKey
Constructor & Destructor Documentation
AddonListViewItem::AddonListViewItem (KviTalListWidget * v, KviKvsScriptAddon * a)
References KviKvsScriptAddon::description(), KviKvsScriptAddon::icon(), m_pAddon, m_pListWidget, KviKvsScriptAddon::name(), p, t(), v, KviKvsScriptAddon::version(), and KviKvsScriptAddon::visibleName().
AddonListViewItem::~AddonListViewItem ()
References m_pAddon.
Member Function Documentation
KviKvsScriptAddon* AddonListViewItem::addon () inline
References m_pAddon.
Referenced by AddonManagementDialog::configureScript(), AddonManagementDialog::currentChanged(), AddonManagementDialog::showScriptHelp(), and AddonManagementDialog::uninstallScript().
Member Data Documentation
KviKvsScriptAddon* AddonListViewItem::m_pAddon protected
Referenced by addon(), AddonListViewItem(), and ~AddonListViewItem().
QPixmap* AddonListViewItem::m_pIcon protected
QListWidget* AddonListViewItem::m_pListWidget protected
Referenced by AddonListViewItem().
QTextDocument* AddonListViewItem::m_pText protected
QString AddonListViewItem::m_szKey protected
The documentation for this class was generated from the following files:
src/modules/addon/AddonManagementDialog.h
src/modules/addon/AddonManagementDialog.cpp