KVIrc: KvsObject_checkBox Class Reference
KvsObject_checkBox Class Reference
#include <KvsObject_checkBox.h>
Public Member Functions
QWidget * widget ()
Protected Slots
void toggled (bool b)
Protected Member Functions
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
bool isChecked (KviKvsObjectFunctionCall *c)
bool setChecked (KviKvsObjectFunctionCall *c)
bool setText (KviKvsObjectFunctionCall *c)
bool toggleEvent (KviKvsObjectFunctionCall *c)
Member Function Documentation
bool KvsObject_checkBox::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) [protected, virtual]
Reimplemented from KvsObject_button.
References connect().
bool KvsObject_checkBox::isChecked (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_checkBox::setChecked (KviKvsObjectFunctionCall * c) [protected]
bool KvsObject_checkBox::setText (KviKvsObjectFunctionCall * c) [protected]
Reimplemented from KvsObject_button.
void KvsObject_checkBox::toggled (bool b) [protected, slot]
References KviKvsObject::callFunction().
bool KvsObject_checkBox::toggleEvent (KviKvsObjectFunctionCall * c) [protected]
QWidget* KvsObject_checkBox::widget () [inline]
Reimplemented from KvsObject_button.
References KviKvsObject::object().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_checkBox.h
src/modules/objects/KvsObject_checkBox.cpp