KVIrc: KviSockaddr Class Reference
KviSockaddr Class Reference
#include <kvi_netutils.h>
Public Member Functions
int addressFamily ()
size_t addressLength ()
bool getStringAddress (QString &szBuffer)
bool isIPv6 ()
KviSockaddr (kvi_u32_t uPort, bool bIPv6, bool bUdp=false)
KviSockaddr (const char *szIpAddress, kvi_u32_t uPort, bool bIPv6, bool bUdp=false)
kvi_u32_t port ()
struct sockaddr * socketAddress ()
~KviSockaddr ()
Private Attributes
struct addrinfo * m_pData
Constructor & Destructor Documentation
KviSockaddr::KviSockaddr (const char * szIpAddress, kvi_u32_t uPort, bool bIPv6, bool bUdp = false)
References KviStr::Format, kvi_memset(), m_pData, and KviStr::ptr().
KviSockaddr::KviSockaddr (kvi_u32_t uPort, bool bIPv6, bool bUdp = false)
References KviStr::Format, kvi_memset(), m_pData, and KviStr::ptr().
KviSockaddr::~KviSockaddr ()
References m_pData.
Member Function Documentation
int KviSockaddr::addressFamily ()
References m_pData.
Referenced by isIPv6().
size_t KviSockaddr::addressLength ()
References m_pData.
Referenced by KviIrcSocket::startConnection().
bool KviSockaddr::getStringAddress (QString & szBuffer)
References kvi_binaryIpToStringIp(), and m_pData.
bool KviSockaddr::isIPv6 ()
References addressFamily(), and m_pData.
kvi_u32_t KviSockaddr::port ()
References m_pData.
struct sockaddr * KviSockaddr::socketAddress () [read]
References m_pData.
Referenced by KviIrcSocket::startConnection().
Member Data Documentation
struct addrinfo* KviSockaddr::m_pData [read, private]
Referenced by addressFamily(), addressLength(), getStringAddress(), isIPv6(), KviSockaddr(), port(), socketAddress(), and ~KviSockaddr().
The documentation for this class was generated from the following files:
src/kvilib/net/kvi_netutils.h
src/kvilib/net/kvi_netutils.cpp