KVIrc: KviImageDialog Class Reference
KviImageDialog Class Reference
#include <KviImageDialog.h>
Public Member Functions
KviImageDialog (QWidget *par, const QString &szCaption=QString(), int types=KID_TYPE_ALL, int initialType=0, const QString &szInitialDir=QString(), int maxPreviewFileSize=256000, bool modal=false)
const QString & selectedImage ()
virtual ~KviImageDialog ()
Protected Slots
void cancelClicked ()
void heartbeat ()
void itemDoubleClicked (QListWidgetItem *it)
void jobTypeSelected (int index)
void okClicked ()
void tipRequest (KviDynamicToolTip *, const QPoint &pnt)
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
void jobTerminated ()
void startJob (int type, const QString &szInitialPath=QString())
Protected Attributes
int m_iJobIndexHelper
int m_iJobType
int m_iMaxPreviewFileSize
QStringList m_lJobFileList
KviTalListWidget * m_pListBox
QTimer * m_pTimer
KviDynamicToolTip * m_pTip
QComboBox * m_pTypeComboBox
QList< int > * m_pTypeList
QString m_szInitialPath
QString m_szJobPath
QString m_szSelectedImage
Constructor & Destructor Documentation
KviImageDialog::KviImageDialog (QWidget * par, const QString & szCaption = QString(), int types = KID_TYPE_ALL, int initialType = 0, const QString & szInitialDir = QString(), int maxPreviewFileSize = 256000, bool modal = false)
References __tr2qs, cancelClicked(), connect(), g, heartbeat(), itemDoubleClicked(), jobTypeSelected(), KID_TYPE_ALL, KID_TYPE_BUILTIN_IMAGES_SMALL, KID_TYPE_FULL_PATH, l, m_iMaxPreviewFileSize, m_pListBox, m_pTimer, m_pTip, m_pTypeComboBox, m_pTypeList, m_szInitialPath, okClicked(), and tipRequest().
KviImageDialog::~KviImageDialog () [virtual]
References m_pTimer, and m_pTypeList.
Member Function Documentation
void KviImageDialog::cancelClicked () [protected, slot]
References m_szSelectedImage.
Referenced by KviImageDialog().
void KviImageDialog::closeEvent (QCloseEvent * e) [protected, virtual]
References m_szSelectedImage.
void KviImageDialog::heartbeat () [protected, slot]
References __tr2qs, g_pIconManager, KviIconManager::getBigIcon(), KviIconManager::getSmallIcon(), KviIconManager::getSmallIconName(), i, KviIconManager::IconCount, jobTerminated(), KID_TYPE_BUILTIN_IMAGES_SMALL, KID_TYPE_FULL_PATH, KVI_BIGICON_FOLDER, KVI_PATH_SEPARATOR, m_iJobIndexHelper, m_iJobType, m_iMaxPreviewFileSize, m_lJobFileList, m_pListBox, and m_szJobPath.
Referenced by KviImageDialog().
void KviImageDialog::itemDoubleClicked (QListWidgetItem * it) [protected, slot]
References g_pApp, i, KviImageDialogItem::imageId(), KviImageDialogItem::isFolder(), KID_TYPE_FULL_PATH, m_szSelectedImage, KviApplication::mapImageFile(), and startJob().
Referenced by KviImageDialog(), and okClicked().
void KviImageDialog::jobTerminated () [protected]
References m_pTimer.
Referenced by heartbeat().
void KviImageDialog::jobTypeSelected (int index) [protected, slot]
References KVI_OPTION_STRING, KviOption_stringLastImageDialogPath, m_pTypeList, m_szInitialPath, and startJob().
Referenced by KviImageDialog().
void KviImageDialog::okClicked () [protected, slot]
References itemDoubleClicked(), and m_pListBox.
Referenced by KviImageDialog().
const QString& KviImageDialog::selectedImage () [inline]
Referenced by SingleActionEditor::chooseBigIcon(), SingleActionEditor::chooseSmallIcon(), KviKvsCallbackImageDialog::done(), and CustomToolBarPropertiesDialog::iconButtonClicked().
void KviImageDialog::startJob (int type, const QString & szInitialPath = QString()) [protected]
References d, Hidden, KID_TYPE_FULL_PATH, KVI_OPTION_STRING, KviOption_stringLastImageDialogPath, m_iJobIndexHelper, m_iJobType, m_lJobFileList, m_pTimer, m_szJobPath, and KviOsInfo::type().
Referenced by itemDoubleClicked(), and jobTypeSelected().
void KviImageDialog::tipRequest (KviDynamicToolTip * , const QPoint & pnt) [protected, slot]
References i, m_pListBox, m_pTip, r, KviDynamicToolTip::tip(), and KviImageDialogItem::tipText().
Referenced by KviImageDialog().
Member Data Documentation
int KviImageDialog::m_iJobIndexHelper [protected]
Referenced by heartbeat(), and startJob().
int KviImageDialog::m_iJobType [protected]
Referenced by heartbeat(), and startJob().
int KviImageDialog::m_iMaxPreviewFileSize [protected]
Referenced by heartbeat(), and KviImageDialog().
QStringList KviImageDialog::m_lJobFileList [protected]
Referenced by heartbeat(), and startJob().
KviTalListWidget* KviImageDialog::m_pListBox [protected]
Referenced by heartbeat(), KviImageDialog(), okClicked(), and tipRequest().
QTimer* KviImageDialog::m_pTimer [protected]
Referenced by jobTerminated(), KviImageDialog(), startJob(), and ~KviImageDialog().
KviDynamicToolTip* KviImageDialog::m_pTip [protected]
Referenced by KviImageDialog(), and tipRequest().
QComboBox* KviImageDialog::m_pTypeComboBox [protected]
Referenced by KviImageDialog().
QList<int>* KviImageDialog::m_pTypeList [protected]
Referenced by jobTypeSelected(), KviImageDialog(), and ~KviImageDialog().
QString KviImageDialog::m_szInitialPath [protected]
Referenced by jobTypeSelected(), and KviImageDialog().
QString KviImageDialog::m_szJobPath [protected]
Referenced by heartbeat(), and startJob().
QString KviImageDialog::m_szSelectedImage [protected]
Referenced by cancelClicked(), closeEvent(), and itemDoubleClicked().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviImageDialog.h
src/kvirc/ui/KviImageDialog.cpp