KVIrc: KviServerDataBase Class Reference
KviServerDataBase Class Reference
Irc server database handling class.
#include <kvi_ircserverdb.h>
Public Member Functions
void addNetwork (KviNetwork *n)
Adds a network to the database.
KviPointerList< KviNetwork > * autoConnectOnStartupNetworks ()
Returns a list of networks to connect on startup This list is computed when the data are loaded from disk during the startup and is used by KviApp to start the connections. The pointer is zero if there are no autoConnect networks. The list is valid only during the startup phase because it contains shallow pointers to the networks really contained in the server/network list and it is never updated later.
KviPointerList< KviServer > * autoConnectOnStartupServers ()
Returns a list of servers to connect on startup This list is computed when the data are loaded from disk during the startup and is used by KviApp to start the connections. The pointer is zero if there are no autoConnect servers. The list is valid only during the startup phase because it contains shallow pointers to the servers really contained in the server/network list and it is never updated later.
void clear ()
Deletes the database.
void clearAutoConnectOnStartupNetworks ()
Deletes the list of autoconnect networks.
void clearAutoConnectOnStartupServers ()
Deletes the list of autoconnect servers.
KviNetwork * currentNetwork ()
Returns the current network.
const QString & currentNetworkName ()
Returns the current network name.
KviNetwork * findNetwork (const QString &name)
Searches for a network.
void importFromMircIni (const QString &filename, const QString &szMircIni, QStringList &recentServers)
Import servers and networks from a mirc ini file.
KviServerDataBase ()
Constructs the server database object.
void load (const QString &filename)
Loads the database data.
bool makeCurrentBestServerInNetwork (const QString &szNetName, KviNetwork *d, QString &szError)
Marks the current servers as the best in the network.
bool makeCurrentServer (KviServerDefinition *d, QString &szError)
Marks a server as current.
unsigned int networkCount () const
Returns the number of networks.
KviPointerHashTable< QString,
KviNetwork > * recordDict ()
Returns the record dictionary of the database.
void save (const QString &filename)
Saves the database data.
void setCurrentNetwork (const QString &szNetName)
Sets the current network.
~KviServerDataBase ()
Destroys the server database object.
Private Attributes
KviPointerList< KviNetwork > * m_pAutoConnectOnStartupNetworks
KviPointerList< KviServer > * m_pAutoConnectOnStartupServers
KviPointerHashTable< QString,
KviNetwork > * m_pRecords
QString m_szCurrentNetwork
Detailed Description
Irc server database handling class.
Constructor & Destructor Documentation
KviServerDataBase::KviServerDataBase ()
Constructs the server database object.
Returns:
KviServerDataBase
References m_pAutoConnectOnStartupNetworks, m_pAutoConnectOnStartupServers, m_pRecords, and KviPointerHashTable< Key, T >::setAutoDelete().
KviServerDataBase::~KviServerDataBase ()
Destroys the server database object.
References m_pAutoConnectOnStartupNetworks, m_pAutoConnectOnStartupServers, and m_pRecords.
Member Function Documentation
void KviServerDataBase::addNetwork (KviNetwork * n)
Adds a network to the database.
Parameters:
n The source network
Returns:
void
References m_pRecords, KviNetwork::name(), and KviPointerHashTable< Key, T >::replace().
Referenced by importFromMircIni(), and load().
KviPointerList<KviNetwork>* KviServerDataBase::autoConnectOnStartupNetworks () [inline]
Returns a list of networks to connect on startup This list is computed when the data are loaded from disk during the startup and is used by KviApp to start the connections. The pointer is zero if there are no autoConnect networks. The list is valid only during the startup phase because it contains shallow pointers to the networks really contained in the server/network list and it is never updated later.
Returns:
KviPointerList<KviNetwork> *
Referenced by KviApp::autoConnectToServers(), and KviApp::createFrame().
KviPointerList<KviServer>* KviServerDataBase::autoConnectOnStartupServers () [inline]
Returns a list of servers to connect on startup This list is computed when the data are loaded from disk during the startup and is used by KviApp to start the connections. The pointer is zero if there are no autoConnect servers. The list is valid only during the startup phase because it contains shallow pointers to the servers really contained in the server/network list and it is never updated later.
Returns:
KviPointerList<KviServer> *
Referenced by KviApp::autoConnectToServers(), and KviApp::createFrame().
void KviServerDataBase::clear ()
Deletes the database.
Returns:
void
References KviPointerHashTable< Key, T >::clear(), m_pRecords, and m_szCurrentNetwork.
Referenced by importFromMircIni(), and load().
void KviServerDataBase::clearAutoConnectOnStartupNetworks ()
Deletes the list of autoconnect networks.
Returns:
void
References m_pAutoConnectOnStartupNetworks.
Referenced by KviApp::autoConnectToServers().
void KviServerDataBase::clearAutoConnectOnStartupServers ()
Deletes the list of autoconnect servers.
Returns:
void
References m_pAutoConnectOnStartupServers.
Referenced by KviApp::autoConnectToServers().
KviNetwork * KviServerDataBase::currentNetwork ()
Returns the current network.
Returns:
KviNetwork
References KviPointerHashTable< Key, T >::find(), m_pRecords, and m_szCurrentNetwork.
Referenced by KviIrcContext::connectToCurrentServer().
const QString& KviServerDataBase::currentNetworkName () [inline]
Returns the current network name.
Returns:
const QString &
KviNetwork * KviServerDataBase::findNetwork (const QString & name)
Searches for a network.
Parameters:
name The name of the network to find
Returns:
KviNetwork
References KviPointerHashTable< Key, T >::find(), and m_pRecords.
Referenced by importFromMircIni().
void KviServerDataBase::importFromMircIni (const QString & filename, const QString & szMircIni, QStringList & recentServers)
Import servers and networks from a mirc ini file.
Parameters:
filename The database file where to add new servers
szMircIni The source mirc ini file to import
recentServers The list of recent servers where to add new servers
Returns:
void
References addNetwork(), KviPointerList< T >::append(), clear(), findNetwork(), KviConfig::hasGroup(), KviNetwork::m_pServerList, m_szCurrentNetwork, KviServer::m_szDescription, KviServer::m_szHostname, KviServer::m_uPort, parseMircServerRecord(), KviConfig::Read, KviConfig::readEntry(), KviConfig::readQStringEntry(), s, KviConfig::setGroup(), and KviQString::sprintf().
void KviServerDataBase::load (const QString & filename)
Loads the database data.
Parameters:
filename The filename of the database data to load
Returns:
void
References addNetwork(), KviPointerList< T >::append(), KviServer::autoConnect(), clear(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfig::dict(), KviPointerList< T >::first(), KviServer::load(), KviNetwork::m_bAutoConnect, m_pAutoConnectOnStartupNetworks, m_pAutoConnectOnStartupServers, KviNetwork::m_pCurrentServer, KviNetwork::m_pNickServRuleSet, KviNetwork::m_pServerList, m_szCurrentNetwork, KviNetwork::m_szDescription, KviNetwork::m_szEncoding, KviNetwork::m_szNickName, KviNetwork::m_szOnConnectCommand, KviNetwork::m_szOnLoginCommand, KviNetwork::m_szPass, KviNetwork::m_szRealName, KviNetwork::m_szTextEncoding, KviNetwork::m_szUserIdentityId, KviNetwork::m_szUserName, KviConfig::Read, KviConfig::readBoolEntry(), KviConfig::readIntEntry(), KviConfig::readQStringEntry(), KviConfig::readStringListEntry(), s, KviPointerList< T >::setAutoDelete(), KviNetwork::setAutoJoinChannelList(), KviConfig::setGroup(), and KviQString::sprintf().
Referenced by KviApp::setup().
bool KviServerDataBase::makeCurrentBestServerInNetwork (const QString & szNetName, KviNetwork * d, QString & szError)
Marks the current servers as the best in the network.
Parameters:
szNetName The name of the network
d The source network
szError The container for a possible error
Returns:
bool
References __tr2qs, KviQString::equalCI(), KviPointerList< T >::first(), KviPointerList< T >::isEmpty(), KviNetwork::m_pServerList, m_szCurrentNetwork, KviPointerList< T >::next(), s, KviNetwork::setCurrentServer(), and KviQString::sprintf().
Referenced by makeCurrentServer().
bool KviServerDataBase::makeCurrentServer (KviServerDefinition * d, QString & szError)
Marks a server as current.
Parameters:
d The server definition
szError The container for a possible error
Returns:
bool
References __tr2qs, _KviServerDefinition::bIPv6, _KviServerDefinition::bPortIsValid, _KviServerDefinition::bSSL, KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), KviQString::equalCIN(), KviPointerHashTable< Key, T >::find(), KviPointerList< T >::first(), KviNetUtils::isValidStringIp(), m_pRecords, m_szCurrentNetwork, KviServer::m_szHostname, KviServer::m_szInitUMode, KviServer::m_szIp, KviServer::m_szNick, KviServer::m_szPass, makeCurrentBestServerInNetwork(), KviNetwork::name(), KviPointerList< T >::next(), KviPointerHashTable< Key, T >::replace(), s, KviNetwork::serverList(), KviServer::setCacheIp(), KviNetwork::setCurrentServer(), _KviServerDefinition::szId, _KviServerDefinition::szInitUMode, _KviServerDefinition::szLinkFilter, _KviServerDefinition::szNick, _KviServerDefinition::szPass, _KviServerDefinition::szServer, KviPointerHashTableIterator< Key, T >::toFirst(), and _KviServerDefinition::uPort.
Referenced by KviIrcContext::connectToCurrentServer().
unsigned int KviServerDataBase::networkCount () const
Returns the number of networks.
Returns:
unsigned integer
References KviPointerHashTable< Key, T >::count(), and m_pRecords.
Referenced by KviIrcContext::connectToCurrentServer().
KviPointerHashTable<QString,KviNetwork>* KviServerDataBase::recordDict () [inline]
Returns the record dictionary of the database.
Returns:
KviPointerHashTable<QString,KviNetwork> *
void KviServerDataBase::save (const QString & filename)
Saves the database data.
Parameters:
filename The filename of the database data to save
Returns:
void
References KviConfig::clear(), KviPointerHashTableIterator< Key, T >::current(), m_pRecords, m_szCurrentNetwork, s, KviConfig::setGroup(), KviQString::sprintf(), KviConfig::Write, and KviConfig::writeEntry().
Referenced by KviApp::saveIrcServerDataBase().
void KviServerDataBase::setCurrentNetwork (const QString & szNetName) [inline]
Sets the current network.
Parameters:
szNetName The name of the network
Returns:
void
Member Data Documentation
KviPointerList<KviNetwork>* KviServerDataBase::m_pAutoConnectOnStartupNetworks [private]
Referenced by clearAutoConnectOnStartupNetworks(), KviServerDataBase(), load(), and ~KviServerDataBase().
KviPointerList<KviServer>* KviServerDataBase::m_pAutoConnectOnStartupServers [private]
Referenced by clearAutoConnectOnStartupServers(), KviServerDataBase(), load(), and ~KviServerDataBase().
KviPointerHashTable<QString,KviNetwork>* KviServerDataBase::m_pRecords [private]
Referenced by addNetwork(), clear(), currentNetwork(), findNetwork(), KviServerDataBase(), makeCurrentServer(), networkCount(), save(), and ~KviServerDataBase().
QString KviServerDataBase::m_szCurrentNetwork [private]
Referenced by clear(), currentNetwork(), importFromMircIni(), load(), makeCurrentBestServerInNetwork(), makeCurrentServer(), and save().
The documentation for this class was generated from the following files:
src/kvilib/irc/kvi_ircserverdb.h
src/kvilib/irc/kvi_ircserverdb.cpp