KVIrc: KviFile Class Reference
KviFile Class Reference
KVIrc File class.
#include <KviFile.h>
Public Member Functions
KviFile ()
Constructs file object.
KviFile (const QString &szName)
Constructs file object.
bool load (kvi_u64_t &file)
Loads a file.
bool load (KviPointerList< KviCString > *pData)
Loads a file from a list.
bool load (kvi_i64_t &file)
Loads a file.
bool load (kvi_u32_t &file)
Loads a file.
bool load (kvi_i32_t &file)
Loads a file.
bool load (kvi_i8_t &file)
Loads a file.
bool load (kvi_u16_t &file)
Loads a file.
bool load (kvi_i16_t &file)
Loads a file.
bool load (kvi_u8_t &file)
Loads a file.
bool load (KviCString &szData)
Loads a file.
bool load (QByteArray &data)
Loads a file.
bool load (QString &szData)
Loads a file.
bool save (const KviCString &szData)
Saves a file.
bool save (KviPointerList< KviCString > *pData)
Saves a file to a list.
bool save (const QString &szData)
Saves a file.
bool save (kvi_u16_t file)
Saves a file.
bool save (kvi_u64_t file)
Saves a file.
bool save (kvi_i8_t file)
Saves a file.
bool save (kvi_u8_t file)
Saves a file.
bool save (const QByteArray &data)
Saves a file.
bool save (kvi_i64_t file)
Saves a file.
bool save (kvi_i32_t file)
Saves a file.
bool save (kvi_u32_t file)
Saves a file.
bool save (kvi_i16_t file)
Saves a file.
bool skipFirst (const KviCString &szText, unsigned int uMaxDist=0xffffffff)
Skips the first occurrence of the given string for a given dimension.
bool skipFirst (char t, unsigned int uMaxDist=0xffffffff)
Skips the first occurrence of the given char for a given dimension.
~KviFile ()
Destroys file object.
Detailed Description
KVIrc File class.
Constructor & Destructor Documentation
KviFile::KviFile ()
Constructs file object.
Returns:
KviFile
KviFile::KviFile (const QString & szName)
Constructs file object.
Parameters:
szName The name of the file
Returns:
KviFile
KviFile::~KviFile ()
Destroys file object.
Member Function Documentation
bool KviFile::load (kvi_u64_t & file)
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References KviByteOrder::littleEndianToLocalCpu32().
Referenced by RegisteredUsersDialog::importClicked(), load(), KviPackageReader::readHeaderInternal(), KviPackageReader::unpackFile(), and KviPackageReader::unpackInternal().
bool KviFile::load (kvi_i32_t & file) [inline]
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load().
Referenced by load().
bool KviFile::load (kvi_u16_t & file)
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References KviByteOrder::littleEndianToLocalCpu16().
bool KviFile::load (kvi_i16_t & file) [inline]
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load().
Referenced by load().
bool KviFile::load (QString & szData)
Loads a file.
Parameters:
szData The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load().
bool KviFile::load (kvi_u8_t & file)
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
bool KviFile::load (kvi_i8_t & file) [inline]
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load().
Referenced by load().
bool KviFile::load (KviCString & szData)
Loads a file.
Parameters:
szData The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load(), KviCString::ptr(), and KviCString::setLength().
bool KviFile::load (QByteArray & data)
Loads a file.
Parameters:
data The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load().
bool KviFile::load (kvi_i64_t & file) [inline]
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References load().
Referenced by load().
bool KviFile::load (KviPointerList< KviCString > * pData)
Loads a file from a list.
Parameters:
pData The list of files to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References KviPointerList< T >::append(), KviPointerList< T >::clear(), i, load(), and s.
bool KviFile::load (kvi_u32_t & file)
Loads a file.
Parameters:
file The file to load
Warning:
This function loads LITTLE ENDIAN DATA!
Returns:
bool
References KviByteOrder::littleEndianToLocalCpu32().
bool KviFile::save (kvi_u64_t file)
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References KviByteOrder::localCpuToLittleEndian64().
Referenced by RegisteredUsersDialog::exportClicked(), KviPackageWriter::packFile(), KviPackageWriter::packInternal(), and save().
bool KviFile::save (kvi_u8_t file)
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
bool KviFile::save (KviPointerList< KviCString > * pData)
Saves a file to a list.
Parameters:
pData The list where file to save is
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References KviPointerList< T >::count(), KviPointerList< T >::first(), KviPointerList< T >::next(), s, and save().
bool KviFile::save (kvi_i64_t file) [inline]
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References save().
Referenced by save().
bool KviFile::save (kvi_u16_t file)
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References KviByteOrder::localCpuToLittleEndian16().
bool KviFile::save (const QString & szData)
Saves a file.
Parameters:
szData The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References c, and save().
bool KviFile::save (kvi_i8_t file) [inline]
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References save().
Referenced by save().
bool KviFile::save (const KviCString & szData)
Saves a file.
Parameters:
szData The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References KviCString::len(), KviCString::ptr(), and save().
bool KviFile::save (kvi_i32_t file) [inline]
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References save().
Referenced by save().
bool KviFile::save (kvi_i16_t file) [inline]
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References save().
Referenced by save().
bool KviFile::save (const QByteArray & data)
Saves a file.
Parameters:
data The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References save().
bool KviFile::save (kvi_u32_t file)
Saves a file.
Parameters:
file The file to save
Warning:
This function saves LITTLE ENDIAN DATA!
Returns:
bool
References KviByteOrder::localCpuToLittleEndian32().
bool KviFile::skipFirst (char t, unsigned int uMaxDist = 0xffffffff)
Skips the first occurrence of the given char for a given dimension.
Parameters:
t The char to find and skip
uMaxDist The dimension of the search field
Returns:
bool
References c.
bool KviFile::skipFirst (const KviCString & szText, unsigned int uMaxDist = 0xffffffff)
Skips the first occurrence of the given string for a given dimension.
Parameters:
szText The string to find and skip
uMaxDist The dimension of the search field
Returns:
bool
References c, and KviCString::ptr().
The documentation for this class was generated from the following files:
src/kvilib/file/KviFile.h
src/kvilib/file/KviFile.cpp