KVIrc: KvsObject_textedit Class Reference
KvsObject_textedit Class Reference
#include <KvsObject_multiLineEdit.h>
Public Member Functions
QWidget * widget ()
Protected Member Functions
bool functionAppend (KviKvsObjectFunctionCall *c)
bool functionAtBeginning (KviKvsObjectFunctionCall *c)
bool functionAtEnd (KviKvsObjectFunctionCall *c)
bool functionbold (KviKvsObjectFunctionCall *c)
bool functionclear (KviKvsObjectFunctionCall *c)
bool functionCopy (KviKvsObjectFunctionCall *c)
bool functionCursorPosition (KviKvsObjectFunctionCall *c)
bool functionCut (KviKvsObjectFunctionCall *c)
bool functiondel (KviKvsObjectFunctionCall *c)
bool functionInsert (KviKvsObjectFunctionCall *c)
bool functionInsertLine (KviKvsObjectFunctionCall *c)
bool functionisRedoAvailable (KviKvsObjectFunctionCall *c)
bool functionisUndoAvailable (KviKvsObjectFunctionCall *c)
bool functionisUndoRedoEnabled (KviKvsObjectFunctionCall *c)
bool functionitalic (KviKvsObjectFunctionCall *c)
bool functionLength (KviKvsObjectFunctionCall *c)
bool functionlines (KviKvsObjectFunctionCall *c)
bool functionloadFile (KviKvsObjectFunctionCall *c)
bool functionMaxLines (KviKvsObjectFunctionCall *c)
bool functionModified (KviKvsObjectFunctionCall *c)
bool functionNumLines (KviKvsObjectFunctionCall *c)
bool functionPaste (KviKvsObjectFunctionCall *c)
bool functionredo (KviKvsObjectFunctionCall *c)
bool functionRemoveLine (KviKvsObjectFunctionCall *c)
bool functionselectAll (KviKvsObjectFunctionCall *c)
bool functionsetAlignment (KviKvsObjectFunctionCall *c)
bool functionsetBold (KviKvsObjectFunctionCall *c)
bool functionsetColor (KviKvsObjectFunctionCall *c)
bool functionsetFamily (KviKvsObjectFunctionCall *c)
bool functionsetHtmlText (KviKvsObjectFunctionCall *c)
bool functionsetItalic (KviKvsObjectFunctionCall *c)
bool functionSetMaxLines (KviKvsObjectFunctionCall *c)
bool functionsetModified (KviKvsObjectFunctionCall *c)
bool functionsetPlainText (KviKvsObjectFunctionCall *c)
bool functionsetPointSize (KviKvsObjectFunctionCall *c)
bool functionSetReadOnly (KviKvsObjectFunctionCall *c)
bool functionsetText (KviKvsObjectFunctionCall *c)
bool functionsetTextFormat (KviKvsObjectFunctionCall *c)
bool functionsetUnderline (KviKvsObjectFunctionCall *c)
bool functionsetUndoRedoEnabled (KviKvsObjectFunctionCall *c)
bool functionSetWordWrap (KviKvsObjectFunctionCall *c)
bool functionText (KviKvsObjectFunctionCall *c)
bool functiontextFormat (KviKvsObjectFunctionCall *c)
bool functionTextLine (KviKvsObjectFunctionCall *c)
bool functionunderline (KviKvsObjectFunctionCall *c)
bool functionundo (KviKvsObjectFunctionCall *c)
bool functionWordWrap (KviKvsObjectFunctionCall *c)
bool functionzoomIn (KviKvsObjectFunctionCall *c)
bool functionzoomOut (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
Protected Member Functions inherited from KvsObject_widget
bool addWidgetToWrappedLayout (KviKvsObjectFunctionCall *c)
bool backgroundColor (KviKvsObjectFunctionCall *c)
bool centerToScreen (KviKvsObjectFunctionCall *c)
bool colorPalette (KviKvsObjectFunctionCall *c)
virtual bool eventFilter (QObject *o, QEvent *e)
bool fontAscent (KviKvsObjectFunctionCall *c)
bool fontDescent (KviKvsObjectFunctionCall *c)
bool fontMetricsHeight (KviKvsObjectFunctionCall *c)
bool fontMetricsLineSpacing (KviKvsObjectFunctionCall *c)
bool fontMetricsWidth (KviKvsObjectFunctionCall *c)
bool foregroundColor (KviKvsObjectFunctionCall *c)
bool geometry (KviKvsObjectFunctionCall *c)
bool globalCursorX (KviKvsObjectFunctionCall *c)
bool globalCursorY (KviKvsObjectFunctionCall *c)
bool grab (KviKvsObjectFunctionCall *)
bool hasFocus (KviKvsObjectFunctionCall *c)
bool height (KviKvsObjectFunctionCall *)
bool hide (KviKvsObjectFunctionCall *)
bool insertIntoStatusBar (KviKvsObjectFunctionCall *c)
bool isEnabled (KviKvsObjectFunctionCall *c)
bool isTopLevel (KviKvsObjectFunctionCall *c)
bool isVisible (KviKvsObjectFunctionCall *c)
bool loadInterface (KviKvsObjectFunctionCall *c)
bool lower (KviKvsObjectFunctionCall *)
bool mapFromGlobal (KviKvsObjectFunctionCall *c)
bool mapToGlobal (KviKvsObjectFunctionCall *c)
bool move (KviKvsObjectFunctionCall *c)
bool parentWidget (KviKvsObjectFunctionCall *c)
bool raise (KviKvsObjectFunctionCall *)
bool removeFromStatusBar (KviKvsObjectFunctionCall *c)
bool repaint (KviKvsObjectFunctionCall *c)
bool resize (KviKvsObjectFunctionCall *c)
bool screenResolution (KviKvsObjectFunctionCall *c)
bool setAttribute (KviKvsObjectFunctionCall *c)
bool setBackgroundColor (KviKvsObjectFunctionCall *c)
bool setBackgroundImage (KviKvsObjectFunctionCall *c)
bool setEnabled (KviKvsObjectFunctionCall *c)
bool setFocus (KviKvsObjectFunctionCall *c)
bool setFocusPolicy (KviKvsObjectFunctionCall *c)
bool setFont (KviKvsObjectFunctionCall *c)
bool setForegroundColor (KviKvsObjectFunctionCall *c)
bool setGeometry (KviKvsObjectFunctionCall *c)
bool setKeyShortcut (KviKvsObjectFunctionCall *c)
bool setMask (KviKvsObjectFunctionCall *c)
bool setMaximumHeight (KviKvsObjectFunctionCall *c)
bool setMaximumWidth (KviKvsObjectFunctionCall *c)
bool setMinimumHeight (KviKvsObjectFunctionCall *c)
bool setMinimumWidth (KviKvsObjectFunctionCall *c)
bool setMouseTracking (KviKvsObjectFunctionCall *c)
bool setParent (KviKvsObjectFunctionCall *c)
bool setStyleSheet (KviKvsObjectFunctionCall *c)
bool setToolTip (KviKvsObjectFunctionCall *)
bool setWFlags (KviKvsObjectFunctionCall *c)
bool setWindowIcon (KviKvsObjectFunctionCall *c)
bool setWindowTitle (KviKvsObjectFunctionCall *c)
bool show (KviKvsObjectFunctionCall *c)
bool sizeHint (KviKvsObjectFunctionCall *c)
bool update (KviKvsObjectFunctionCall *c)
bool width (KviKvsObjectFunctionCall *)
bool windowTitle (KviKvsObjectFunctionCall *c)
bool x (KviKvsObjectFunctionCall *)
bool y (KviKvsObjectFunctionCall *)
Protected Member Functions inherited from KviKvsObject
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Additional Inherited Members
Signals inherited from KvsObject_widget
void aboutToDie ()
Protected Attributes inherited from KvsObject_widget
KviKvsRunTimeContext * m_pContext
QGraphicsDropShadowEffect * pGraphicsEffect
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Member Function Documentation
bool KvsObject_textedit::functionAppend (KviKvsObjectFunctionCall * c) protected
References KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionAtBeginning (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionAtEnd (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionbold (KviKvsObjectFunctionCall * c) protected
References KviControlCodes::Bold, KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionclear (KviKvsObjectFunctionCall * c) protected
References clear(), and widget().
bool KvsObject_textedit::functionCopy (KviKvsObjectFunctionCall * c) protected
References KviMemory::copy(), and widget().
bool KvsObject_textedit::functionCursorPosition (KviKvsObjectFunctionCall * c) protected
References a, KviKvsObjectFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and widget().
bool KvsObject_textedit::functionCut (KviKvsObjectFunctionCall * c) protected
References widget().
bool KvsObject_textedit::functiondel (KviKvsObjectFunctionCall * c) protected
bool KvsObject_textedit::functionInsert (KviKvsObjectFunctionCall * c) protected
References KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionInsertLine (KviKvsObjectFunctionCall * c) protected
bool KvsObject_textedit::functionisRedoAvailable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_textedit::functionisUndoAvailable (KviKvsObjectFunctionCall * c) protected
bool KvsObject_textedit::functionisUndoRedoEnabled (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionitalic (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionLength (KviKvsObjectFunctionCall * c) protected
bool KvsObject_textedit::functionlines (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setInteger(), and widget().
bool KvsObject_textedit::functionloadFile (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsRunTimeCall::warning(), and widget().
bool KvsObject_textedit::functionMaxLines (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setInteger(), and widget().
bool KvsObject_textedit::functionModified (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionNumLines (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setInteger(), and widget().
bool KvsObject_textedit::functionPaste (KviKvsObjectFunctionCall * c) protected
References widget().
bool KvsObject_textedit::functionredo (KviKvsObjectFunctionCall * c) protected
References widget().
bool KvsObject_textedit::functionRemoveLine (KviKvsObjectFunctionCall * c) protected
bool KvsObject_textedit::functionselectAll (KviKvsObjectFunctionCall * c) protected
References widget().
bool KvsObject_textedit::functionsetAlignment (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsRunTimeCall::warning(), and widget().
bool KvsObject_textedit::functionsetBold (KviKvsObjectFunctionCall * c) protected
References KviControlCodes::Bold, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, Normal, and widget().
bool KvsObject_textedit::functionsetColor (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsArray::at(), KviKvsVariantList::count(), KviKvsRunTimeCall::error(), KviKvsVariant::isArray(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsRunTimeCall::params(), KviKvsArray::size(), KviKvsRunTimeCall::warning(), and widget().
bool KvsObject_textedit::functionsetFamily (KviKvsObjectFunctionCall * c) protected
References KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetHtmlText (KviKvsObjectFunctionCall * c) protected
References KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetItalic (KviKvsObjectFunctionCall * c) protected
References KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionSetMaxLines (KviKvsObjectFunctionCall * c) protected
References KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetModified (KviKvsObjectFunctionCall * c) protected
References KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetPlainText (KviKvsObjectFunctionCall * c) protected
References KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetPointSize (KviKvsObjectFunctionCall * c) protected
References KVS_PT_REAL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionSetReadOnly (KviKvsObjectFunctionCall * c) protected
References KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetText (KviKvsObjectFunctionCall * c) protected
References KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetTextFormat (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsRunTimeCall::warning(), and widget().
bool KvsObject_textedit::functionsetUnderline (KviKvsObjectFunctionCall * c) protected
References KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionsetUndoRedoEnabled (KviKvsObjectFunctionCall * c) protected
References KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widget().
bool KvsObject_textedit::functionSetWordWrap (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsRunTimeCall::warning(), and widget().
bool KvsObject_textedit::functionText (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setString(), and widget().
bool KvsObject_textedit::functiontextFormat (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setString(), and widget().
bool KvsObject_textedit::functionTextLine (KviKvsObjectFunctionCall * c) protected
References __tr2qs_ctx(), KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setString(), KviKvsRunTimeCall::warning(), and widget().
bool KvsObject_textedit::functionunderline (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and widget().
bool KvsObject_textedit::functionundo (KviKvsObjectFunctionCall * c) protected
References widget().
bool KvsObject_textedit::functionWordWrap (KviKvsObjectFunctionCall * c) protected
References KviKvsObjectFunctionCall::returnValue(), KviKvsVariant::setString(), and widget().
bool KvsObject_textedit::functionzoomIn (KviKvsObjectFunctionCall * c) protected
References KVS_PF_OPTIONAL, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObject::object(), and widget().
bool KvsObject_textedit::functionzoomOut (KviKvsObjectFunctionCall * c) protected
References KVS_PF_OPTIONAL, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObject::object(), and widget().
bool KvsObject_textedit::init (KviKvsRunTimeContext * pContext, KviKvsVariantList * pParams) protected virtual
Reimplemented from KvsObject_widget.
Reimplemented in KvsObject_textBrowser.
References SET_OBJECT.
QWidget* KvsObject_textedit::widget () inline
Reimplemented from KvsObject_widget.
Reimplemented in KvsObject_textBrowser.
References KviKvsObject::object().
Referenced by functionAppend(), functionAtBeginning(), functionAtEnd(), functionbold(), functionclear(), functionCopy(), functionCursorPosition(), functionCut(), functionInsert(), functionisUndoRedoEnabled(), functionitalic(), functionlines(), functionloadFile(), functionMaxLines(), functionModified(), functionNumLines(), functionPaste(), functionredo(), functionselectAll(), functionsetAlignment(), functionsetBold(), functionsetColor(), functionsetFamily(), functionsetHtmlText(), functionsetItalic(), functionSetMaxLines(), functionsetModified(), functionsetPlainText(), functionsetPointSize(), functionSetReadOnly(), functionsetText(), functionsetTextFormat(), functionsetUnderline(), functionsetUndoRedoEnabled(), functionSetWordWrap(), functionText(), functiontextFormat(), functionTextLine(), functionunderline(), functionundo(), functionWordWrap(), functionzoomIn(), and functionzoomOut().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_multiLineEdit.h
src/modules/objects/KvsObject_multiLineEdit.cpp