KVIrc: KvsObject_ftp Class Reference
KvsObject_ftp Class Reference
#include <KvsObject_ftp.h>
Protected Slots
void slotCommandFinished (int id, bool error)
void slotCommandStarted (int id)
void slotDataTransferProgress (qint64 done, qint64 total)
void slotDone (bool error)
void slotListInfo (const QUrlInfo &i)
void slotRawCommandReply (int replyCode, const QString &detail)
void slotReadyRead ()
void slotStateChanged (int state)
Protected Slots inherited from KviKvsObject
void delayedDie ()
void objectDestroyed ()
Protected Member Functions
bool abort (KviKvsObjectFunctionCall *c)
bool cd (KviKvsObjectFunctionCall *c)
bool close (KviKvsObjectFunctionCall *c)
bool commandFinishedEvent (KviKvsObjectFunctionCall *c)
bool dataTransferProgressEvent (KviKvsObjectFunctionCall *c)
bool functionConnect (KviKvsObjectFunctionCall *c)
bool get (KviKvsObjectFunctionCall *c)
bool list (KviKvsObjectFunctionCall *c)
bool listInfoEvent (KviKvsObjectFunctionCall *c)
bool login (KviKvsObjectFunctionCall *c)
bool put (KviKvsObjectFunctionCall *c)
bool stateChangedEvent (KviKvsObjectFunctionCall *c)
Protected Member Functions inherited from KviKvsObject
virtual bool eventFilter (QObject *o, QEvent *e)
bool function_childCount (KviKvsObjectFunctionCall *c)
bool function_children (KviKvsObjectFunctionCall *c)
bool function_className (KviKvsObjectFunctionCall *c)
bool function_destructor (KviKvsObjectFunctionCall *c)
bool function_emit (KviKvsObjectFunctionCall *c)
bool function_findChild (KviKvsObjectFunctionCall *c)
bool function_killTimer (KviKvsObjectFunctionCall *c)
bool function_listProperties (KviKvsObjectFunctionCall *c)
bool function_name (KviKvsObjectFunctionCall *c)
bool function_parent (KviKvsObjectFunctionCall *c)
bool function_property (KviKvsObjectFunctionCall *c)
bool function_setProperty (KviKvsObjectFunctionCall *c)
bool function_signalName (KviKvsObjectFunctionCall *c)
bool function_signalSender (KviKvsObjectFunctionCall *c)
bool function_startTimer (KviKvsObjectFunctionCall *c)
virtual bool init (KviKvsRunTimeContext *pContext, KviKvsVariantList *pParams)
void registerChild (KviKvsObject *c)
void registerConnection (KviKvsObjectConnection *con)
virtual void timerEvent (QTimerEvent *e)
void unregisterChild (KviKvsObject *c)
bool unregisterConnection (KviKvsObjectConnection *con)
Protected Attributes
QFtp * m_pFtp
Protected Attributes inherited from KviKvsObject
bool m_bAboutToDie
bool m_bDestructorCalled
bool m_bInDelayedDeath
bool m_bObjectOwner
kvs_hobject_t m_hObject
kvs_hobject_t m_hSignalSender
KviPointerList< KviKvsObject > * m_pChildList
KviKvsObjectClass * m_pClass
KviKvsObjectConnectionList * m_pConnectionList
KviKvsHash * m_pDataContainer
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * m_pFunctionHandlers
QObject * m_pObject
KviPointerHashTable< QString,
KviKvsObjectConnectionList > * m_pSignalDict
QString m_szName
QString m_szSignalName
Additional Inherited Members
Public Member Functions inherited from KviKvsObject
bool callFunction (KviKvsObject *pCaller, const QString &fncName, const QString &classOverride, KviKvsRunTimeContext *pContext, KviKvsVariant *pRetVal, KviKvsVariantList *pParams)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariantList *pParams=0)
bool callFunction (KviKvsObject *pCaller, const QString &fncName, KviKvsVariant *pRetVal, KviKvsVariantList *pParams=0)
bool connectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
KviKvsHash * dataContainer ()
bool die ()
bool dieNow ()
bool disconnectSignal (const QString &sigName, KviKvsObjectConnection *con)
bool disconnectSignal (const QString &sigName, KviKvsObject *target, const QString &slotName)
int emitSignal (const QString &sigName, KviKvsObjectFunctionCall *pOuterCall, KviKvsVariantList *pParams=0)
KviKvsObject * findChild (const QString &szClass, const QString &szName)
KviPointerHashTable< QString,
KviKvsObjectFunctionHandler > * functionHandlers ()
KviKvsObjectClass * getClass (const QString &classOverride=QString())
KviKvsObjectClass * getExactClass ()
const QString & getName ()
kvs_hobject_t handle ()
bool inheritsClass (KviKvsObjectClass *pClass)
bool inheritsClass (const QString &szClass)
void killAllChildrenWithClass (KviKvsObjectClass *cl)
KviKvsObject (KviKvsObjectClass *pClass, KviKvsObject *pParent, const QString &szName)
KviKvsObjectFunctionHandler * lookupFunctionHandler (const QString &funcName, const QString &classOverride=QString())
QObject * object () const
KviKvsObject * parentObject ()
QWidget * parentScriptWidget ()
void registerPrivateImplementation (const QString &szFunctionName, const QString &szCode)
void setObject (QObject *o, bool bIsOwned=true)
void setSignalName (const QString &szSigName)
void setSignalSender (kvs_hobject_t hObject)
kvs_hobject_t signalSender ()
virtual ~KviKvsObject ()
Member Function Documentation
bool KvsObject_ftp::abort (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::cd (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::close (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::commandFinishedEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::dataTransferProgressEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::functionConnect (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::get (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::list (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::listInfoEvent (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::login (KviKvsObjectFunctionCall * c) protected
bool KvsObject_ftp::put (KviKvsObjectFunctionCall * c) protected
void KvsObject_ftp::slotCommandFinished (int id, bool error) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), QFtp::Cd, QFtp::Close, QFtp::ConnectToHost, QFtp::currentCommand(), QFtp::currentDevice(), QFtp::errorString(), QFtp::Get, QFtp::List, QFtp::Login, m_pFtp, QFtp::Mkdir, QFtp::None, QFtp::Put, QFtp::RawCommand, QFtp::Remove, QFtp::Rename, QFtp::Rmdir, QFtp::SetProxy, and QFtp::SetTransferMode.
void KvsObject_ftp::slotCommandStarted (int id) protected slot
void KvsObject_ftp::slotDataTransferProgress (qint64 done, qint64 total) protected slot
References KviKvsVariantList::append(), and KviKvsObject::callFunction().
void KvsObject_ftp::slotDone (bool error) protected slot
void KvsObject_ftp::slotListInfo (const QUrlInfo & i) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), and QUrlInfo::name().
void KvsObject_ftp::slotRawCommandReply (int replyCode, const QString & detail) protected slot
void KvsObject_ftp::slotReadyRead () protected slot
void KvsObject_ftp::slotStateChanged (int state) protected slot
References KviKvsVariantList::append(), KviKvsObject::callFunction(), QFtp::Closing, QFtp::Connected, QFtp::Connecting, QFtp::HostLookup, QFtp::LoggedIn, and QFtp::Unconnected.
bool KvsObject_ftp::stateChangedEvent (KviKvsObjectFunctionCall * c) protected
Member Data Documentation
QFtp* KvsObject_ftp::m_pFtp protected
Referenced by slotCommandFinished().
The documentation for this class was generated from the following files:
src/modules/objects/KvsObject_ftp.h
src/modules/objects/KvsObject_ftp.cpp