KVIrc: KviHttpRequestThread Class Reference
KviHttpRequestThread Class Reference
#include <kvi_http.h>
Public Types
enum RequestMethod { Post, Get, Head }
Public Member Functions
~KviHttpRequestThread ()
Protected Member Functions
bool connectToRemoteHost ()
bool failure (const char *error=0)
KviHttpRequestThread (KviHttpRequest *r, const QString &szHost, const QString &szIp, unsigned short uPort, const QString &szPath, unsigned int uContentOffset, RequestMethod m, const QString &szPostData=QString(), bool bUseSSL=false)
bool processInternalEvents ()
bool readDataStep ()
virtual void run ()
void runInternal ()
bool selectForRead (int iTimeoutInSecs)
int selectForReadStep ()
bool selectForWrite (int iTimeoutInSecs)
bool sendBuffer (const char *buffer, int bufLen, int iTimeoutInSecs)
bool sslFailure ()
Protected Attributes
bool m_bUseSSL
RequestMethod m_eRequestMethod
KviHttpRequest * m_pRequest
kvi_socket_t m_sock
QString m_szHost
QString m_szIp
QString m_szPath
QString m_szPostData
unsigned int m_uContentOffset
unsigned short m_uPort
Friends
class KviHttpRequest
Member Enumeration Documentation
enum KviHttpRequestThread::RequestMethod
Enumerator:
Post
Get
Head
Constructor & Destructor Documentation
KviHttpRequestThread::KviHttpRequestThread (KviHttpRequest * r, const QString & szHost, const QString & szIp, unsigned short uPort, const QString & szPath, unsigned int uContentOffset, RequestMethod m, const QString & szPostData = QString(), bool bUseSSL = false) [protected]
References KVI_INVALID_SOCKET, m_bUseSSL, m_eRequestMethod, m_pRequest, m_sock, m_szHost, m_szIp, m_szPath, m_szPostData, m_uContentOffset, and m_uPort.
KviHttpRequestThread::~KviHttpRequestThread ()
Member Function Documentation
bool KviHttpRequestThread::connectToRemoteHost () [protected]
References __tr_no_lookup, failure(), KviError::getUntranslatedDescription(), KVI_INVALID_SOCKET, kvi_socket_connect(), kvi_socket_create(), kvi_socket_error(), kvi_socket_getsockopt(), KVI_SOCKET_PF_INET, kvi_socket_recoverableConnectError(), kvi_socket_recoverableError(), kvi_socket_setNonBlocking(), KVI_SOCKET_TYPE_STREAM, KviError_unknownError, m_bUseSSL, m_sock, m_szIp, m_uPort, selectForRead(), selectForWrite(), sslFailure(), KviNetUtils::stringIpToBinaryIp(), and KviError::translateSystemError().
Referenced by runInternal().
bool KviHttpRequestThread::failure (const char * error = 0) [protected]
References KVI_THREAD_EVENT_ERROR, m_pRequest, and KviThread::postEvent().
Referenced by connectToRemoteHost(), readDataStep(), runInternal(), selectForRead(), selectForReadStep(), selectForWrite(), sendBuffer(), and sslFailure().
bool KviHttpRequestThread::processInternalEvents () [protected]
References debug, KviSensitiveThread::dequeueEvent(), and KVI_THREAD_EVENT_TERMINATE.
Referenced by selectForRead(), selectForWrite(), and sendBuffer().
bool KviHttpRequestThread::readDataStep () [protected]
References failure(), KviError::getUntranslatedDescription(), kvi_socket_error(), kvi_socket_read, KVI_THREAD_EVENT_BINARYDATA, KVI_THREAD_EVENT_SUCCESS, m_pRequest, m_sock, KviThread::postEvent(), selectForRead(), selectForWrite(), sslFailure(), and KviError::translateSystemError().
Referenced by runInternal().
void KviHttpRequestThread::run () [protected, virtual]
Reimplemented from KviThread.
References KVI_INVALID_SOCKET, kvi_socket_close, kvi_socket_isValid(), m_sock, and runInternal().
void KviHttpRequestThread::runInternal () [protected]
References __tr_no_lookup, KviStr::append(), connectToRemoteHost(), failure(), KviStr::Format, Get, Head, KVI_HTTP_REQUEST_THREAD_EVENT_CONNECTED, KVI_HTTP_REQUEST_THREAD_EVENT_REQUESTSENT, m_bUseSSL, m_eRequestMethod, m_pRequest, m_szHost, m_szPath, m_szPostData, m_uContentOffset, Post, KviThread::postEvent(), KviStr::ptr(), readDataStep(), sendBuffer(), and KviQString::toUtf8().
Referenced by run().
bool KviHttpRequestThread::selectForRead (int iTimeoutInSecs) [protected]
References __tr_no_lookup, failure(), processInternalEvents(), selectForReadStep(), and KviThread::usleep().
Referenced by connectToRemoteHost(), readDataStep(), and sendBuffer().
int KviHttpRequestThread::selectForReadStep () [protected]
References failure(), KviError::getUntranslatedDescription(), kvi_socket_error(), kvi_socket_select(), m_sock, and KviError::translateSystemError().
Referenced by selectForRead().
bool KviHttpRequestThread::selectForWrite (int iTimeoutInSecs) [protected]
References __tr_no_lookup, failure(), KviError::getUntranslatedDescription(), kvi_socket_error(), kvi_socket_select(), kvi_time_t, kvi_unixTime, m_sock, processInternalEvents(), KviError::translateSystemError(), and KviThread::usleep().
Referenced by connectToRemoteHost(), readDataStep(), and sendBuffer().
bool KviHttpRequestThread::sendBuffer (const char * buffer, int bufLen, int iTimeoutInSecs) [protected]
References __tr_no_lookup, failure(), KviError::getUntranslatedDescription(), kvi_socket_error(), kvi_socket_send(), m_sock, processInternalEvents(), selectForRead(), selectForWrite(), sslFailure(), KviError::translateSystemError(), and KviThread::usleep().
Referenced by runInternal().
bool KviHttpRequestThread::sslFailure () [protected]
References __tr_no_lookup, failure(), and KviStr::ptr().
Referenced by connectToRemoteHost(), readDataStep(), and sendBuffer().
Friends And Related Function Documentation
friend class KviHttpRequest [friend]
Member Data Documentation
bool KviHttpRequestThread::m_bUseSSL [protected]
Referenced by connectToRemoteHost(), KviHttpRequestThread(), and runInternal().
RequestMethod KviHttpRequestThread::m_eRequestMethod [protected]
Referenced by KviHttpRequestThread(), and runInternal().
KviHttpRequest* KviHttpRequestThread::m_pRequest [protected]
Referenced by failure(), KviHttpRequestThread(), readDataStep(), and runInternal().
kvi_socket_t KviHttpRequestThread::m_sock [protected]
Referenced by connectToRemoteHost(), KviHttpRequestThread(), readDataStep(), run(), selectForReadStep(), selectForWrite(), and sendBuffer().
QString KviHttpRequestThread::m_szHost [protected]
Referenced by KviHttpRequestThread(), and runInternal().
QString KviHttpRequestThread::m_szIp [protected]
Referenced by connectToRemoteHost(), and KviHttpRequestThread().
QString KviHttpRequestThread::m_szPath [protected]
Referenced by KviHttpRequestThread(), and runInternal().
QString KviHttpRequestThread::m_szPostData [protected]
Referenced by KviHttpRequestThread(), and runInternal().
unsigned int KviHttpRequestThread::m_uContentOffset [protected]
Referenced by KviHttpRequestThread(), and runInternal().
unsigned short KviHttpRequestThread::m_uPort [protected]
Referenced by connectToRemoteHost(), and KviHttpRequestThread().
The documentation for this class was generated from the following files:
src/kvilib/net/kvi_http.h
src/kvilib/net/kvi_http.cpp