KVIrc: KviActionDrawerPageListWidgetItem Class Reference
KviActionDrawerPageListWidgetItem Class Reference
#include <KviActionDrawer.h>
Public Member Functions
QPixmap * icon ()
KviActionDrawerPageListWidgetItem (KviTalListWidget *pList, KviAction *pAction)
Constructs an action drawer page list item object.
const QString & name ()
~KviActionDrawerPageListWidgetItem ()
Destroys an action drawer page list item object.
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Protected Attributes
QPixmap * m_pIcon
KviTalListWidget * m_pListWidget
QString m_szKey
QString m_szName
Constructor & Destructor Documentation
KviActionDrawerPageListWidgetItem::KviActionDrawerPageListWidgetItem (KviTalListWidget * pList, KviAction * pAction)
Constructs an action drawer page list item object.
Parameters:
pList The list where to add the item
pAction The action associated to the item
Returns:
KviActionDrawerPageListWidget
References __tr2qs, KviAction::bigIcon(), KviAction::description(), KviAction::isKviUserActionNeverOverrideThis(), m_pListWidget, m_szKey, m_szName, KviAction::name(), p, and KviAction::visibleName().
KviActionDrawerPageListWidgetItem::~KviActionDrawerPageListWidgetItem ()
Destroys an action drawer page list item object.
Member Function Documentation
QPixmap* KviActionDrawerPageListWidgetItem::icon () inline
const QString& KviActionDrawerPageListWidgetItem::name () inline
Referenced by KviActionDrawerPageListWidget::mousePressEvent().
Member Data Documentation
QPixmap* KviActionDrawerPageListWidgetItem::m_pIcon protected
KviTalListWidget* KviActionDrawerPageListWidgetItem::m_pListWidget protected
Referenced by KviActionDrawerPageListWidgetItem().
QString KviActionDrawerPageListWidgetItem::m_szKey protected
Referenced by KviActionDrawerPageListWidgetItem().
QString KviActionDrawerPageListWidgetItem::m_szName protected
Referenced by KviActionDrawerPageListWidgetItem().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviActionDrawer.h
src/kvirc/ui/KviActionDrawer.cpp