KVIrc: ThemeListWidgetItem Class Reference
ThemeListWidgetItem Class Reference
#include <ThemeManagementDialog.h>
Public Member Functions
KviThemeInfo * themeInfo ()
ThemeListWidgetItem (KviTalListWidget *pBox, KviThemeInfo *pInfo)
virtual ~ThemeListWidgetItem ()
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Public Attributes
KviThemeInfo * m_pThemeInfo
Constructor & Destructor Documentation
ThemeListWidgetItem::ThemeListWidgetItem (KviTalListWidget * pBox, KviThemeInfo * pInfo)
References __tr2qs_ctx(), KviThemeInfo::author(), KviThemeInfo::description(), m_pThemeInfo, KviThemeInfo::name(), and KviThemeInfo::version().
ThemeListWidgetItem::~ThemeListWidgetItem () virtual
References m_pThemeInfo.
Member Function Documentation
KviThemeInfo* ThemeListWidgetItem::themeInfo () inline
References m_pThemeInfo.
Referenced by ThemeManagementDialog::applyCurrentTheme(), ThemeManagementDialog::contextMenuRequested(), ThemeManagementDialog::deleteTheme(), and ThemeManagementDialog::enableDisableButtons().
Member Data Documentation
KviThemeInfo* ThemeListWidgetItem::m_pThemeInfo
Referenced by themeInfo(), ThemeListWidgetItem(), and ~ThemeListWidgetItem().
The documentation for this class was generated from the following files:
src/modules/theme/ThemeManagementDialog.h
src/modules/theme/ThemeManagementDialog.cpp