KVIrc: OptionsWidget_inputLook Class Reference
OptionsWidget_inputLook Class Reference
#include <OptionsWidget_input.h>
Public Member Functions
virtual void commit ()
OptionsWidget_inputLook (QWidget *parent)
~OptionsWidget_inputLook ()
Private Attributes
QComboBox * m_pHorizontalAlign
QComboBox * m_pVerticalAlign
Constructor & Destructor Documentation
OptionsWidget_inputLook::OptionsWidget_inputLook (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addColorSelector(), KviOptionsWidget::addFontSelector(), KviOptionsWidget::addLabel(), KviOptionsWidget::addPixmapSelector(), KviOptionsWidget::addWidgetToLayout(), KviOptionsWidget::createLayout(), KVI_OPTION_UINT, KviOption_colorInputBackground, KviOption_colorInputControl, KviOption_colorInputCursor, KviOption_colorInputForeground, KviOption_colorInputSelectionBackground, KviOption_colorInputSelectionForeground, KviOption_fontInput, KviOption_pixmapInputBackground, KviOption_uintInputPixmapAlign, KviOptionsWidget::layout(), m_pHorizontalAlign, and m_pVerticalAlign.
OptionsWidget_inputLook::~OptionsWidget_inputLook ()
Member Function Documentation
void OptionsWidget_inputLook::commit (void) [virtual]
Reimplemented from KviOptionsWidget.
References KVI_OPTION_UINT, KviOption_uintInputPixmapAlign, m_pHorizontalAlign, and m_pVerticalAlign.
Member Data Documentation
QComboBox* OptionsWidget_inputLook::m_pHorizontalAlign [private]
Referenced by commit(), and OptionsWidget_inputLook().
QComboBox* OptionsWidget_inputLook::m_pVerticalAlign [private]
Referenced by commit(), and OptionsWidget_inputLook().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_input.h
src/modules/options/OptionsWidget_input.cpp