KVIrc: KviKvsTreeNodeHashCount Class Reference
KviKvsTreeNodeHashCount Class Reference
#include <KviKvsTreeNodeHashCount.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeHashCount (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeHashCount ()
Public Member Functions inherited from KviKvsTreeNodeIndirectData
virtual bool canEvaluateInObjectScope ()
KviKvsTreeNodeIndirectData (const QChar *pLocation, KviKvsTreeNodeData *pSource)
~KviKvsTreeNodeIndirectData ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeIndirectData
KviKvsTreeNodeData * m_pSource
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeHashCount::KviKvsTreeNodeHashCount (const QChar * pLocation, KviKvsTreeNodeData * pSource)
KviKvsTreeNodeHashCount::~KviKvsTreeNodeHashCount ()
Member Function Documentation
void KviKvsTreeNodeHashCount::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeData.
void KviKvsTreeNodeHashCount::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeData.
bool KviKvsTreeNodeHashCount::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References evaluateReadOnlyInObjectScope().
bool KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope (KviKvsObject * o, KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) virtual
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsVariant::getTypeName(), KviKvsVariant::hash(), KviKvsVariant::isHash(), KviKvsVariant::isNothing(), KviKvsTreeNodeIndirectData::m_pSource, KviKvsVariant::setInteger(), KviKvsHash::size(), and KviKvsRunTimeContext::warning().
Referenced by evaluateReadOnly().
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeHashCount.h
src/kvirc/kvs/tree/KviKvsTreeNodeHashCount.cpp