KVIrc: KviKvsScript Class Reference
KviKvsScript Class Reference
The KVIrc Script class.
#include <KviKvsScript.h>
Public Types
enum RunFlags { PreserveParams = 1, AssumeLocals = 2, Pedantic = 4, Quiet = 8 }
Holds the run flags of the script.
enum RunStatus { Error = 0, Success = 1, HaltEncountered = 2 }
Holds the run status of the script.
enum ScriptType { InstructionList, Expression, Parameter }
Holds the type of the script.
Public Member Functions
const QString & code () const
Returns the code of the script.
void dump (const char *prefix)
Dumps the instructions tree.
KviKvsScript (const KviKvsScript &src)
Constructs a KVIrc Script object.
KviKvsScript (const QString &szName, const QString &szBuffer, ScriptType eType=InstructionList)
Constructs a KVIrc Script object.
bool locked () const
Returns true if the script is locked, false otherwise.
const QString & name () const
Returns the name of the script context.
int run (KviWindow *pWnd, KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0, int iRunFlags=0, KviKvsExtendedRunTimeData *pExtData=0)
Runs the script.
int run (KviWindow *pWnd, KviKvsVariantList *pParams, QString &szRetVal, int iRunFlags=0, KviKvsExtendedRunTimeData *pExtData=0)
Runs the script.
int run (KviKvsRunTimeContext *pContext, int iRunFlags=0)
Runs the script.
void setName (const QString &szName)
Sets the name of the script context.
~KviKvsScript ()
Destroys a KVIrc Script object.
Static Public Member Functions
static int evaluate (const QString &szCode, KviWindow *pWindow, KviKvsVariantList *pParams, KviKvsVariant *pRetVal)
Static helper for quick evaluating parameters.
static int evaluateAsString (const QString &szCode, KviWindow *pWindow, KviKvsVariantList *pParams, QString &szRetVal)
Static helper for quick evaluating parameters.
static int run (const QString &szCode, KviWindow *pWindow, KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0)
Static helper for quick running.
Protected Member Functions
const QChar * buffer () const
Returns the data of the script.
void detach ()
Detaches this script from any other shallow copies.
int execute (KviWindow *pWnd, KviKvsVariantList *pParams=0, KviKvsVariant *pRetVal=0, int iRunFlags=0, KviKvsExtendedRunTimeData *pExtData=0)
Runs the script.
int executeInternal (KviKvsRunTimeContext *pContext)
Runs the script.
KviKvsScript (const QString &szName, const QString &szBuffer, KviKvsTreeNodeInstruction *pPreparsedTree, ScriptType eType=InstructionList)
Constructs a KVIrc Script object.
bool parse (KviWindow *pOutput=0, int iRunFlags=0)
Returns true after a succesfull parsing, false otherwise.
Private Attributes
KviKvsScriptData * m_pData
Friends
class KviKvsObject
class KviKvsParser
class KviKvsRunTimeContext
Detailed Description
The KVIrc Script class.
Member Enumeration Documentation
enum KviKvsScript::RunFlags
Holds the run flags of the script.
Enumerator
PreserveParams
Do not delete the eventual parameters passed (only execute() and run())
AssumeLocals
Assume that the variables are local unless explicitly declared (flag used only for parse())
Pedantic
Be more pedantic: spit more warnings and sometimes more errors
Quiet
Don't print any errors
enum KviKvsScript::RunStatus
Holds the run status of the script.
Enumerator
Error
The script returned an error
Success
The script ran successfully
HaltEncountered
The script ran successfully and halt was encountered
enum KviKvsScript::ScriptType
Holds the type of the script.
Enumerator
InstructionList
The most common script type: a sequence of instructions
Expression
An expression to be evaluated as in a $() call (pRetVal should be always set!)
Parameter
A parameter to be evaluated (pRetVal should be always set!)
Constructor & Destructor Documentation
KviKvsScript::KviKvsScript (const KviKvsScript & src)
Constructs a KVIrc Script object.
This is a shallow copy of the script data useful when a script can be destroyed while running (like in timers)
Parameters
src The source script
Returns
KviKvsScript
References m_pData, and KviKvsScriptData::m_uRefs.
Referenced by KviKvsScriptAddon::allocateScripts(), KviKvsScriptAddon::setConfigureCallback(), and KviKvsScriptAddon::setHelpCallback().
KviKvsScript::KviKvsScript (const QString & szName, const QString & szBuffer, ScriptType eType = InstructionList)
Constructs a KVIrc Script object.
Parameters
szName The name of the context
szBuffer The buffer :)
eType The type of the code in the buffer
Returns
KviKvsScript
References KviKvsScriptData::m_eType, KviKvsScriptData::m_pBuffer, m_pData, KviKvsScriptData::m_pTree, KviKvsScriptData::m_szBuffer, KviKvsScriptData::m_szName, KviKvsScriptData::m_uLock, KviKvsScriptData::m_uRefs, and szBuffer.
KviKvsScript::~KviKvsScript ()
Destroys a KVIrc Script object.
References m_pData, KviKvsScriptData::m_pTree, KviKvsScriptData::m_uLock, and KviKvsScriptData::m_uRefs.
KviKvsScript::KviKvsScript (const QString & szName, const QString & szBuffer, KviKvsTreeNodeInstruction * pPreparsedTree, ScriptType eType = InstructionList) protected
Constructs a KVIrc Script object.
Parameters
szName The name of the context
szBuffer The buffer :)
pPreparsedTree The synthax tree
eType The type of the code in the buffer
Returns
KviKvsScript
References KviKvsScriptData::m_eType, KviKvsScriptData::m_pBuffer, m_pData, KviKvsScriptData::m_pTree, KviKvsScriptData::m_szBuffer, KviKvsScriptData::m_szName, KviKvsScriptData::m_uLock, KviKvsScriptData::m_uRefs, and szBuffer.
Member Function Documentation
const QChar * KviKvsScript::buffer () const protected
Returns the data of the script.
Returns
const QChar *
References KviKvsScriptData::m_pBuffer, and m_pData.
Referenced by KviKvsRunTimeContext::report().
const QString & KviKvsScript::code () const
Returns the code of the script.
Returns
const QString &
References m_pData, and KviKvsScriptData::m_szBuffer.
Referenced by action_kvs_cmd_create(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), AliasEditorWidget::aliasRefresh(), KviKvsScriptAddon::configureCallbackCode(), KviKvsScriptAddon::description(), KviKvsUserAction::description(), KviKvsScriptAddon::descriptionCode(), KviKvsUserAction::descriptionCode(), dialog_kvs_cmd_file(), dialog_kvs_cmd_image(), dialog_kvs_cmd_message(), dialog_kvs_cmd_textinput(), SinglePopupEditor::findMatchingItem(), KviKvsPopupMenu::generateDefPopupCore(), KviKvsScriptAddon::helpCallbackCode(), http_kvs_cmd_asyncGet(), KviKvsScriptAddon::KviKvsScriptAddon(), KviCustomToolBarDescriptor::label(), KviCustomToolBarDescriptor::labelCode(), AliasEditorWidget::oneTimeSetup(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addPrologue(), KviKvsAliasManager::save(), KviCustomToolBarDescriptor::save(), KviKvsUserAction::save(), KviKvsPopupMenu::save(), KviKvsObjectScriptFunctionHandler::scriptHandlerCode(), KviKvsScriptAddon::uninstallCallbackCode(), KviKvsScriptAddon::visibleName(), KviKvsUserAction::visibleName(), KviKvsScriptAddon::visibleNameCode(), and KviKvsUserAction::visibleNameCode().
void KviKvsScript::detach () protected
Detaches this script from any other shallow copies.
Returns
void
References d, KviKvsScriptData::m_eType, KviKvsScriptData::m_pBuffer, m_pData, KviKvsScriptData::m_pTree, KviKvsScriptData::m_szBuffer, KviKvsScriptData::m_uLock, and KviKvsScriptData::m_uRefs.
Referenced by parse(), and setName().
void KviKvsScript::dump (const char * prefix)
Dumps the instructions tree.
Parameters
prefix The prefix of the instruction
Returns
void
References KviKvsTreeNodeInstruction::dump(), m_pData, and KviKvsScriptData::m_pTree.
Referenced by KviKvsTreeNodeCallbackCommand::dumpCallback().
int KviKvsScript::evaluate (const QString & szCode, KviWindow * pWindow, KviKvsVariantList * pParams, KviKvsVariant * pRetVal) static
Static helper for quick evaluating parameters.
Returns a combination of RunStatus flags (nonzero on no error) It does NOT take params ownership. pRetVal CAN'T be zero here since we're evaluating stuff here
Parameters
szCode The source code to run
pWindow The window that the command has to be bound to
pParams The parameter list
pRetVal Return value buffer
Returns
int
References Parameter, PreserveParams, run(), and s.
Referenced by KviChannelWindow::closeEvent(), KviWindow::getDefaultLogFileName(), KviKvsCoreFunctions::KVSCF(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), KviIrcContext::terminateConnectionRequest(), and KviIrcConnection::useRealName().
int KviKvsScript::evaluateAsString (const QString & szCode, KviWindow * pWindow, KviKvsVariantList * pParams, QString & szRetVal) static
Static helper for quick evaluating parameters.
Returns a combination of RunStatus flags (nonzero on no error) It does NOT take params ownership. The QString return buffer CAN'T be zero here since we're evaluating stuff here
Parameters
szCode The source code to run
pWindow The window that the command has to be bound to
pParams The parameter list
szRetVal Return value buffer
Returns
int
References KviKvsVariant::asString(), Parameter, PreserveParams, run(), and s.
int KviKvsScript::execute (KviWindow * pWnd, KviKvsVariantList * pParams = 0, KviKvsVariant * pRetVal = 0, int iRunFlags = 0, KviKvsExtendedRunTimeData * pExtData = 0) protected
Runs the script.
Returns 0 (KviKvsScript::RunFailure) on error Returns a nonzero combination of RunStatus flags on success
Parameters
pWnd The window that the command has to be bound to
pParams The parameter list (0 if you don't pass params)
pRetVal Return value buffer (0 if you ignore it)
iRunFlags A combination of run flags (usually default)
pExtData Extended data (usually 0)
Returns
int
References KviKvsRunTimeContext::disableReporting(), KviKvsKernel::emptyParameterList(), Error, executeInternal(), KviKvsKernel::instance(), KVI_OUT_PARSERERROR, m_pData, KviKvsScriptData::m_pTree, KviWindow::outputNoFmt(), PreserveParams, and Quiet.
Referenced by run().
int KviKvsScript::executeInternal (KviKvsRunTimeContext * pContext) protected
Runs the script.
Returns 0 (KviKvsScript::RunFailure) on error Returns a nonzero combination of RunStatus flags on success
Parameters
pContext The context where the script is bound to
Returns
int
References Error, KviKvsRunTimeContext::error(), KviKvsTreeNodeInstruction::execute(), KviKvsRunTimeContext::haltCalled(), HaltEncountered, m_pData, KviKvsScriptData::m_pTree, KviKvsScriptData::m_uLock, and Success.
Referenced by execute(), and run().
bool KviKvsScript::locked () const
Returns true if the script is locked, false otherwise.
The lock is set while the script is being executed
Returns
bool
References m_pData, and KviKvsScriptData::m_uLock.
const QString & KviKvsScript::name () const
Returns the name of the script context.
Returns
const QString &
References m_pData, and KviKvsScriptData::m_szName.
Referenced by KviKvsAliasManager::completeCommand(), AliasEditorWidget::oneTimeSetup(), KviKvsPopupMenu::removeItemByName(), KviKvsRunTimeContext::report(), KviKvsParser::report(), KviKvsAliasManager::save(), KviKvsPopupMenu::save(), and KviKvsEventManager::triggerHandlers().
bool KviKvsScript::parse (KviWindow * pOutput = 0, int iRunFlags = 0) protected
Returns true after a succesfull parsing, false otherwise.
pOutput is useful only for printing errors; if 0, no errors are printed
Parameters
pOutput The output window for errors
iRunFlags A combination of run flags (usually default)
Returns
bool
References KviKvsParser::AssumeLocals, AssumeLocals, detach(), KviKvsParser::error(), Expression, InstructionList, KviKvsScriptData::m_eType, KviKvsScriptData::m_pBuffer, m_pData, KviKvsScriptData::m_pTree, KviKvsScriptData::m_uLock, KviKvsScriptData::m_uRefs, p, Parameter, KviKvsParser::parse(), KviKvsParser::parseAsExpression(), KviKvsParser::parseAsParameter(), KviKvsParser::Pedantic, Pedantic, and Quiet.
Referenced by run().
int KviKvsScript::run (KviWindow * pWnd, KviKvsVariantList * pParams = 0, KviKvsVariant * pRetVal = 0, int iRunFlags = 0, KviKvsExtendedRunTimeData * pExtData = 0)
Runs the script.
Returns 0 (KviKvsScript::RunFailure) on error Returns a nonzero combination of RunStatus flags on success
If PreserverParams is not used, the ownership is transferred. Extended data is used if you need to pass extended scope variables or alias switch lists...)
Parameters
pWnd The window that the command has to be bound to
pParams The parameter list (0 if you don't pass params)
pRetVal Return value buffer (0 if you ignore it)
iRunFlags A combination of run flags (usually default)
pExtData Extended data (usually 0)
Returns
int
References Error, execute(), m_pData, KviKvsScriptData::m_pTree, parse(), and PreserveParams.
Referenced by KviKvsAction::activate(), KviApplication::autoConnectToServers(), avatar_kvs_cmd_set(), KviScriptUserButton::btnClicked(), ClassEditorWidget::build(), KviKvsObjectScriptFunctionHandler::call(), ChannelsJoinDialog::clearClicked(), OptionsWidget_textEncoding::commit(), OptionsWidget_servers::connectCurrentClicked(), KviIrcContext::connectToCurrentServer(), KviApplication::createFrame(), KviIrcContext::createLinksWindow(), KviIrcContext::createListWindow(), KviMainWindow::customizeToolBars(), UrlDialog::dblclk_url(), KviKvsScriptAddon::description(), KviKvsUserAction::description(), KviKvsDnsManager::dnsLookupTerminated(), KviInputEditor::dropEvent(), evaluate(), evaluateAsString(), KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), CodeTesterWidget::execute(), KviKvsCallbackObject::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsScriptAddon::executeConfigureCallback(), KviKvsScriptAddon::executeHelpCallback(), KviMainWindow::executeInternalCommand(), KviConsoleWindow::executeInternalCommand(), KviKvsScriptAddon::executeUninstallCallback(), AddonManagementDialog::getMoreScripts(), KviStatusBarUpdateIndicator::getNewVersion(), AddonFunctions::installAddonPackage(), KviFileTransferManager::invokeTransferWindow(), KviApplication::ipcMessage(), ChannelsJoinDialog::joinClicked(), KviKvsCoreSimpleCommands::KVSCSC(), KviCustomToolBarDescriptor::label(), KviKvsObjectClass::load(), KviApplication::loadDefaultScript(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviKvsAsyncDnsOperation::lookupTerminated(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), KviIrcView::mouseDoubleClickEvent(), ClassEditorWidget::newClass(), KviMenuBar::newConnectionToServer(), KviAsyncAvatarSelectionDialog::okClicked(), KviIrcServerParser::parseCtcpReplyAvatar(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviIrcServerParser::parseNumericEndOfWhois(), KviIrcServerParser::parseNumericNoSuchNick(), KviIrcServerParser::parseNumericNoSuchServer(), KviInputEditor::pasteFile(), KviInputEditor::pasteSlow(), KviSoundSelector::playSound(), KviJoinChannelAction::popupActivated(), KviChangeNickAction::popupActivated(), KviConnectToServerAction::popupActivated(), KviChangeUserModeAction::popupActivated(), OptionsWidget_servers::recentServersPopupClicked(), ChannelsJoinDialog::regClicked(), DccFileTransfer::retryDCC(), DccFileTransfer::retryRevDCC(), DccFileTransfer::retryTDCC(), KviIrcUrl::run(), run(), UrlDialog::sayToWin(), setup_finish(), KviInputEditor::stopPasteSlow(), KviKvsTimerManager::timerEvent(), HttpFileTransfer::transferTerminated(), KviKvsProcessAsyncOperation::trigger(), KviKvsEventManager::triggerHandlers(), KviIrcView::triggerMouseRelatedKvsEvents(), KviConsoleWindow::triggerOnHighlight(), KviKvsScriptAddon::visibleName(), and KviKvsUserAction::visibleName().
int KviKvsScript::run (KviWindow * pWnd, KviKvsVariantList * pParams, QString & szRetVal, int iRunFlags = 0, KviKvsExtendedRunTimeData * pExtData = 0)
Runs the script.
Returns 0 (KviKvsScript::RunFailure) on error Returns a nonzero combination of RunStatus flags on success
The QString return buffer is useful only for evaluating InstructionList scripts. If PreserverParams is not used, the ownership is transferred. Extended data is used if you need to pass extended scope variables or alias switch lists...)
Parameters
pWnd The window that the command has to be bound to
pParams The parameter list (0 if you don't pass params)
szRetVal Return value buffer
iRunFlags A combination of run flags (usually default)
pExtData Extended data (usually 0)
Returns
int
References KviKvsVariant::asString(), and run().
int KviKvsScript::run (KviKvsRunTimeContext * pContext, int iRunFlags = 0)
Runs the script.
Returns 0 (KviKvsScript::RunFailure) on error Returns a nonzero combination of RunStatus flags on success
This is probably used only in /eval
Parameters
pContext The context where the script is bound to
iRunFlags A combination of run flags (usually default)
Returns
int
References KviKvsRunTimeContext::disableReporting(), KviKvsRunTimeContext::enableReporting(), Error, executeInternal(), m_pData, KviKvsScriptData::m_pTree, parse(), Quiet, KviKvsRunTimeContext::reportingDisabled(), and KviKvsRunTimeContext::window().
int KviKvsScript::run (const QString & szCode, KviWindow * pWindow, KviKvsVariantList * pParams = 0, KviKvsVariant * pRetVal = 0) static
Static helper for quick running.
Returns a combination of RunStatus flags (nonzero on no error) It does NOT take params ownership
Parameters
szCode The source code to run
pWindow The window that the command has to be bound to
pParams The parameter list (0 if you don't pass params)
pRetVal Return value buffer (0 if you ignore it)
Returns
int
References PreserveParams, run(), and s.
void KviKvsScript::setName (const QString & szName)
Sets the name of the script context.
Parameters
szName The name of the context
Returns
void
References detach(), m_pData, KviKvsScriptData::m_szName, and KviKvsScriptData::m_uRefs.
Referenced by KviKvsCoreCallbackCommands::KVSCCC().
Friends And Related Function Documentation
friend class KviKvsObject friend
friend class KviKvsParser friend
friend class KviKvsRunTimeContext friend
Member Data Documentation
KviKvsScriptData* KviKvsScript::m_pData private
Referenced by buffer(), code(), detach(), dump(), execute(), executeInternal(), KviKvsScript(), locked(), name(), parse(), run(), setName(), and ~KviKvsScript().
The documentation for this class was generated from the following files:
src/kvirc/kvs/KviKvsScript.h
src/kvirc/kvs/KviKvsScript.cpp