KVIrc: KviKvsTreeNodeAliasFunctionCall Class Reference
KviKvsTreeNodeAliasFunctionCall Class Reference
Treenode alias function call class.
#include <kvi_kvs_treenode_aliasfunctioncall.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer as Alias Function Call.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
Evaluates the script in read-only mode.
KviKvsTreeNodeAliasFunctionCall (const QChar *pLocation, const QString &szAliasName, KviKvsTreeNodeDataList *pParams)
Constructs the treenode alias function call object.
~KviKvsTreeNodeAliasFunctionCall ()
Destroys the treenode alias function call object.
Detailed Description
Treenode alias function call class.
Constructor & Destructor Documentation
KviKvsTreeNodeAliasFunctionCall::KviKvsTreeNodeAliasFunctionCall (const QChar * pLocation, const QString & szAliasName, KviKvsTreeNodeDataList * pParams)
Constructs the treenode alias function call object.
Parameters:
pLocation The location char of the instruction
szAliasName The name of the alias
pParams The parameters' list
Returns:
KviKvsTreeNodeAliasFunctionCall
KviKvsTreeNodeAliasFunctionCall::~KviKvsTreeNodeAliasFunctionCall ()
Destroys the treenode alias function call object.
Member Function Documentation
void KviKvsTreeNodeAliasFunctionCall::contextDescription (QString & szBuffer) [virtual]
Sets the buffer as Alias Function Call.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeFunctionCall.
References KviKvsTreeNodeFunctionCall::m_szFunctionName, and KviQString::sprintf().
void KviKvsTreeNodeAliasFunctionCall::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeFunctionCall.
References KviKvsTreeNodeDataList::dump(), KviKvsTreeNodeFunctionCall::m_pParams, and KviKvsTreeNodeFunctionCall::m_szFunctionName.
bool KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Evaluates the script in read-only mode.
Parameters:
c The context where the alias is bound to
pBuffer The data buffer
Returns:
bool
Reimplemented from KviKvsTreeNodeData.
References __tr2qs_ctx, KviKvsRunTimeContext::error(), KviKvsTreeNodeDataList::evaluate(), KviKvsAliasManager::instance(), KviKvsAliasManager::lookup(), KviKvsTreeNodeFunctionCall::m_pParams, KviKvsTreeNodeFunctionCall::m_szFunctionName, KviKvsScript::PreserveParams, KviKvsScript::run(), s, KviKvsVariant::setNothing(), and KviKvsRunTimeContext::window().
The documentation for this class was generated from the following files:
src/kvirc/kvs/kvi_kvs_treenode_aliasfunctioncall.h
src/kvirc/kvs/kvi_kvs_treenode_aliasfunctioncall.cpp