KVIrc: SocketSpyWindow Class Reference
SocketSpyWindow Class Reference
#include <SocketSpyWindow.h>
Public Member Functions
virtual void connectionInitiated ()
virtual void connectionTerminated ()
virtual void die ()
virtual bool incomingMessage (const char *message)
virtual bool outgoingMessage (const char *message)
virtual QSize sizeHint () const
SocketSpyWindow (KviMainWindow *lpFrm, KviConsoleWindow *lpConsole)
~SocketSpyWindow ()
Protected Member Functions
virtual void applyOptions ()
virtual void fillCaptionBuffers ()
virtual void getBaseLogFileName (QString &buffer)
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
Constructor & Destructor Documentation
SocketSpyWindow::SocketSpyWindow (KviMainWindow * lpFrm, KviConsoleWindow * lpConsole)
References KviPointerList< T >::append(), KviTalSplitter, KviWindow::m_pIrcView, and KviWindow::m_pSplitter.
SocketSpyWindow::~SocketSpyWindow ()
References KviPointerList< T >::removeRef().
Member Function Documentation
void SocketSpyWindow::applyOptions () [protected, virtual]
Reimplemented from KviWindow.
References KviIrcView::applyOptions(), and KviWindow::m_pIrcView.
void SocketSpyWindow::connectionInitiated () [virtual]
Reimplemented from KviIrcDataStreamMonitor.
References __tr2qs, KVI_OUT_SOCKETWARNING, and KviWindow::output().
void SocketSpyWindow::connectionTerminated () [virtual]
Reimplemented from KviIrcDataStreamMonitor.
References __tr2qs, KVI_OUT_SOCKETWARNING, and KviWindow::output().
void SocketSpyWindow::die () [virtual]
Reimplemented from KviIrcDataStreamMonitor.
Referenced by socketspy_module_cleanup().
void SocketSpyWindow::fillCaptionBuffers () [protected, virtual]
Reimplemented from KviWindow.
References __tr2qs, KviConsoleWindow::context(), KviIrcContext::id(), KviWindow::m_pConsole, and KviWindow::m_szPlainTextCaption.
void SocketSpyWindow::getBaseLogFileName (QString & buffer) [protected, virtual]
Reimplemented from KviWindow.
References KviWindow::context().
bool SocketSpyWindow::incomingMessage (const char * message) [virtual]
Implements KviIrcDataStreamMonitor.
References KviWindow::console(), KviWindow::decodeText(), KVI_OUT_SOCKETMESSAGE, and KviWindow::outputNoFmt().
QPixmap * SocketSpyWindow::myIconPtr () [protected, virtual]
Reimplemented from KviWindow.
References g_pIconManager, KviIconManager::getSmallIcon(), and KviIconManager::Spy.
bool SocketSpyWindow::outgoingMessage (const char * message) [virtual]
Implements KviIrcDataStreamMonitor.
References KviWindow::console(), KviWindow::decodeText(), KVI_OUT_RAW, and KviWindow::outputNoFmt().
void SocketSpyWindow::resizeEvent (QResizeEvent * e) [protected, virtual]
References KviWindow::m_pSplitter.
QSize SocketSpyWindow::sizeHint () const [virtual]
References KviWindow::m_pIrcView, and KviIrcView::sizeHint().
The documentation for this class was generated from the following files:
src/modules/socketspy/SocketSpyWindow.h
src/modules/socketspy/SocketSpyWindow.cpp