KVIrc: QHttpPGHRequest Class Reference
QHttpPGHRequest Class Reference
Public Member Functions
QHttpPGHRequest (const QHttpRequestHeader &h, QIODevice *d, QIODevice *t)
QHttpPGHRequest (const QHttpRequestHeader &h, QByteArray *d, QIODevice *t)
void start (QHttp *) override
~QHttpPGHRequest () override=default
Public Member Functions inherited from QHttpNormalRequest
QIODevice * destinationDevice () override
bool hasRequestHeader () override
QHttpNormalRequest (const QHttpRequestHeader &h, QIODevice *d, QIODevice *t)
QHttpNormalRequest (const QHttpRequestHeader &h, QByteArray *d, QIODevice *t)
QHttpRequestHeader requestHeader () override
void setRequestHeader (const QHttpRequestHeader &h)
QIODevice * sourceDevice () override
~QHttpNormalRequest () override
Public Member Functions inherited from QHttpRequest
QHttpRequest ()
virtual ~QHttpRequest ()=default
Additional Inherited Members
Public Attributes inherited from QHttpRequest
bool finished
int id
Protected Attributes inherited from QHttpNormalRequest
QHttpRequestHeader header
Constructor & Destructor Documentation
QHttpPGHRequest::QHttpPGHRequest (const QHttpRequestHeader & h, QIODevice * d, QIODevice * t) inline
QHttpPGHRequest::QHttpPGHRequest (const QHttpRequestHeader & h, QByteArray * d, QIODevice * t) inline
QHttpPGHRequest::~QHttpPGHRequest () override default
Member Function Documentation
void QHttpPGHRequest::start (QHttp * http) override virtual
Reimplemented from QHttpNormalRequest.
References QHttp::d, QHttpNormalRequest::header, QHttpHeader::setValue(), and QHttpNormalRequest::start().
Referenced by QHttpAuthenticatorPrivate::parseDigestAuthenticationChallenge().
The documentation for this class was generated from the following file:
src/modules/objects/qthttp/qhttp.cpp