KVIrc: KviKvsTreeNodeExpressionUnaryOperator Class Reference
KviKvsTreeNodeExpressionUnaryOperator Class Reference
#include <kvi_kvs_treenode_expression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
bool evaluateOperand (KviKvsRunTimeContext *c)
KviKvsTreeNodeExpressionUnaryOperator (const QChar *pLocation, KviKvsTreeNodeExpression *pData)
~KviKvsTreeNodeExpressionUnaryOperator ()
Protected Attributes
KviKvsNumber m_nData
KviKvsTreeNodeExpression * m_pData
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionUnaryOperator::KviKvsTreeNodeExpressionUnaryOperator (const QChar * pLocation, KviKvsTreeNodeExpression * pData)
References m_pData, KviKvsTreeNode::setParent(), and KviKvsTreeNodeExpression::setParentExpression().
KviKvsTreeNodeExpressionUnaryOperator::~KviKvsTreeNodeExpressionUnaryOperator ()
References m_pData.
Member Function Documentation
void KviKvsTreeNodeExpressionUnaryOperator::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeExpressionOperator.
Reimplemented in KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, and KviKvsTreeNodeExpressionUnaryOperatorLogicalNot.
void KviKvsTreeNodeExpressionUnaryOperator::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeExpressionOperator.
Reimplemented in KviKvsTreeNodeExpressionUnaryOperatorNegate, KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot, and KviKvsTreeNodeExpressionUnaryOperatorLogicalNot.
References KviKvsTreeNodeExpression::dump(), and m_pData.
bool KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand (KviKvsRunTimeContext * c)
References __tr2qs_ctx, KviKvsVariant::asNumber(), KviKvsRunTimeContext::error(), KviKvsTreeNodeData::evaluateReadOnly(), m_nData, and m_pData.
Referenced by KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly(), and KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly().
Member Data Documentation
KviKvsNumber KviKvsTreeNodeExpressionUnaryOperator::m_nData [protected]
Referenced by evaluateOperand(), KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::evaluateReadOnly(), and KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly().
KviKvsTreeNodeExpression* KviKvsTreeNodeExpressionUnaryOperator::m_pData [protected]
Referenced by KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::dump(), KviKvsTreeNodeExpressionUnaryOperatorBitwiseNot::dump(), KviKvsTreeNodeExpressionUnaryOperatorNegate::dump(), dump(), evaluateOperand(), KviKvsTreeNodeExpressionUnaryOperatorLogicalNot::evaluateReadOnly(), KviKvsTreeNodeExpressionUnaryOperator(), and ~KviKvsTreeNodeExpressionUnaryOperator().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_expression.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_expression.cpp