KVIrc: KviStatusBarSeparator Class Reference
KviStatusBarSeparator Class Reference
#include <KviStatusBarApplet.h>
Public Member Functions
KviStatusBarSeparator (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
virtual ~KviStatusBarSeparator ()
Public Member Functions inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * descriptor ()
KviMainWindow * frame ()
int index () const
KviStatusBarApplet (KviStatusBar *pParent, KviStatusBarAppletDescriptor *pDescriptor)
void setIndex (int i)
KviStatusBar * statusBar ()
virtual ~KviStatusBarApplet ()
Static Public Member Functions
static void selfRegister (KviStatusBar *pBar)
Additional Inherited Members
Protected Member Functions inherited from KviStatusBarApplet
virtual void fillContextPopup (QMenu *)
virtual void loadState (const char *, KviConfigurationFile *)
virtual void saveState (const char *, KviConfigurationFile *)
virtual QString tipText (const QPoint &)
Protected Attributes inherited from KviStatusBarApplet
KviStatusBarAppletDescriptor * m_pDescriptor
KviStatusBar * m_pStatusBar
int mIndex
Constructor & Destructor Documentation
KviStatusBarSeparator::KviStatusBarSeparator (KviStatusBar * pParent, KviStatusBarAppletDescriptor * pDescriptor)
KviStatusBarSeparator::~KviStatusBarSeparator () virtual
Member Function Documentation
void KviStatusBarSeparator::selfRegister (KviStatusBar * pBar) static
References __tr2qs, CreateStatusBarSeparator(), d, and KviStatusBar::registerAppletDescriptor().
Referenced by KviStatusBar::KviStatusBar().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviStatusBarApplet.h
src/kvirc/ui/KviStatusBarApplet.cpp