KVIrc: KviKvsTreeNodeCoreFunctionCall Class Reference
KviKvsTreeNodeCoreFunctionCall Class Reference
#include <kvi_kvs_treenode_corefunctioncall.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
KviKvsTreeNodeCoreFunctionCall (const QChar *pLocation, const QString &szFncName, KviKvsCoreFunctionExecRoutine *r, KviKvsTreeNodeDataList *pParams)
~KviKvsTreeNodeCoreFunctionCall ()
Protected Attributes
KviKvsCoreFunctionExecRoutine * m_pExecRoutine
Constructor & Destructor Documentation
KviKvsTreeNodeCoreFunctionCall::KviKvsTreeNodeCoreFunctionCall (const QChar * pLocation, const QString & szFncName, KviKvsCoreFunctionExecRoutine * r, KviKvsTreeNodeDataList * pParams)
References m_pExecRoutine.
KviKvsTreeNodeCoreFunctionCall::~KviKvsTreeNodeCoreFunctionCall ()
Member Function Documentation
void KviKvsTreeNodeCoreFunctionCall::contextDescription (QString & szBuffer) [virtual]
Sets the buffer.
Parameters:
szBuffer The buffer :)
Returns:
void
Reimplemented from KviKvsTreeNodeFunctionCall.
References KviKvsTreeNodeFunctionCall::m_szFunctionName, and KviQString::sprintf().
void KviKvsTreeNodeCoreFunctionCall::dump (const char * prefix) [virtual]
Dumps the tree.
Parameters:
prefix The prefix of the instruction
Returns:
void
Reimplemented from KviKvsTreeNodeFunctionCall.
References debug, KviKvsTreeNodeDataList::dump(), KviKvsTreeNodeFunctionCall::m_pParams, and KviKvsTreeNodeFunctionCall::m_szFunctionName.
bool KviKvsTreeNodeCoreFunctionCall::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pBuffer) [virtual]
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeDataList::evaluate(), m_pExecRoutine, KviKvsTreeNodeFunctionCall::m_pParams, _KviKvsCoreFunctionExecRoutine::proc, KviKvsRunTimeContext::setDefaultReportLocation(), and KviKvsVariant::setNothing().
Member Data Documentation
KviKvsCoreFunctionExecRoutine* KviKvsTreeNodeCoreFunctionCall::m_pExecRoutine [protected]
Referenced by evaluateReadOnly(), and KviKvsTreeNodeCoreFunctionCall().
The documentation for this class was generated from the following files:
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_corefunctioncall.h
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kvs/kvi_kvs_treenode_corefunctioncall.cpp