KVIrc: KviIrcView Class Reference
KviIrcView Class Reference
#include <KviIrcView.h>
Public Types
enum AppendTextFlags { NoRepaint = 1, NoTimestamp = 2, SetLineMark = 4, TriggersNotification = 8 }
Public Slots
void chooseBackground ()
void chooseFont ()
void clearBuffer ()
void decreaseFontSize ()
void flushLog ()
void increaseFontSize ()
void resetBackground ()
void resetDefaultFont ()
void showToolsPopup ()
void toggleToolWidget ()
Signals
void dndEntered ()
void fileDropped (const QString &)
void rightClicked ()
Public Member Functions
void add2Log (const QString &szBuffer, int iMsgType=0, bool bPrependDate=false)
void appendMessagesFrom (KviIrcView *v)
void appendText (int msg_type, const kvi_wchar_t *data_ptr, int iFlags=0, const QDateTime &datetime=QDateTime())
void applyOptions ()
void clearLineMark (bool bRepaint=false)
void clearUnreaded ()
KviConsoleWindow * console ()
int dummyRead () const
void emptyBuffer (bool bRepaint=true)
void enableDnd (bool bEnable)
void findNext (const QString &szText, bool bCaseS=false, bool bRegExp=false, bool bExtended=false)
void findPrev (const QString &szText, bool bCaseS=false, bool bRegExp=false, bool bExtended=false)
void getLogFileName (QString &buffer)
bool getPaintOnScreen () const
void getTextBuffer (QString &buffer)
bool hasLineMark ()
bool hasPrivateBackgroundPixmap ()
bool haveUnreadedHighlightedMessages ()
bool haveUnreadedMessages ()
bool isLogging ()
void joinMessagesFrom (KviIrcView *v)
KviIrcView (QWidget *parent, KviWindow *pWnd)
const QString & lastLineOfText ()
const QString & lastMessageText ()
int maxBufferSize ()
bool messageShouldGoToMessageView (int iMsgType)
void nextLine ()
void nextPage ()
KviWindow * parentKviWindow ()
void prevLine ()
void prevPage ()
void removeHeadLine (bool bRepaint=false)
bool saveBuffer (const char *filename)
void scrollToMarker ()
virtual void setFont (const QFont &f)
void setMasterView (KviIrcView *v)
void setMaxBufferSize (int maxBufSize, bool bRepaint=true)
void setPaintOnScreen (bool bFlag)
void setPrivateBackgroundPixmap (const QPixmap &pixmap, bool bRepaint=true)
virtual QSize sizeHint () const
void splitMessagesTo (KviIrcView *v)
bool startLogging (const QString &fname=QString(), bool bPrependCurBuffer=false)
void stopLogging ()
~KviIrcView ()
Protected Slots
void animatedIconChange ()
void masterDead ()
virtual void scrollBarPositionChanged (int newValue)
Protected Member Functions
virtual void dragEnterEvent (QDragEnterEvent *e)
virtual void dropEvent (QDropEvent *e)
virtual bool event (QEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
virtual void leaveEvent (QEvent *)
void maybeTip (const QPoint &pnt)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *)
virtual void paintEvent (QPaintEvent *)
virtual void resizeEvent (QResizeEvent *)
virtual void timerEvent (QTimerEvent *e)
virtual void wheelEvent (QWheelEvent *e)
Properties
int TransparencyCapable
bool usePaintOnScreen
Private Member Functions
void addControlCharacter (KviIrcViewLineChunk *pC, QString &szSelectionText)
void appendLine (KviIrcViewLine *ptr, bool bRepaint)
void calculateLineWraps (KviIrcViewLine *ptr, int maxWidth)
bool checkMarkerArea (const QPoint &mousePos)
bool checkSelectionBlock (KviIrcViewLine *line, int bufIndex)
void doLinkToolTip (const QRect &rct, QString &linkCmd, QString &linkText)
void doMarkerToolTip ()
void ensureLineVisible (KviIrcViewLine *pLineToShow)
void fastScroll (int lines=1)
void getLinkEscapeCommand (QString &buffer, const QString &escape_cmd, const QString &escape_label)
KviIrcViewWrappedBlock * getLinkUnderMouse (int xPos, int yPos, QRect *pRect=0, QString *linkCmd=0, QString *linkText=0)
const kvi_wchar_t * getTextLine (int msg_type, const kvi_wchar_t *data_ptr, KviIrcViewLine *line_ptr, bool bEnableTimeStamp=true, const QDateTime &datetime=QDateTime())
int getVisibleCharIndexAt (KviIrcViewLine *line, int xPos, int yPos)
KviIrcViewLine * getVisibleLineAt (int yPos)
void postUpdateEvent ()
void reapplyMessageColors ()
void recalcFontVariables (const QFontMetrics &fm, const QFontInfo &fi)
void setCursorLine (KviIrcViewLine *l)
void triggerMouseRelatedKvsEvents (QMouseEvent *e)
Private Attributes
bool m_bAcceptDrops
bool m_bCtrlPressed
bool m_bHaveUnreadedHighlightedMessages
bool m_bHaveUnreadedMessages
bool m_bMouseIsDown
bool m_bPostedPaintEventPending
bool m_bShiftPressed
bool m_bSkipScrollBarRepaint
QMultiHash< KviIrcViewLine
*, KviAnimatedPixmap * > m_hAnimatedSmiles
int m_iFlushTimer
int m_iFontCharacterWidth [256]
int m_iFontDescent
int m_iFontLineSpacing
int m_iFontLineWidth
int m_iIconSideSpacing
int m_iIconWidth
int m_iLastLinkRectHeight
int m_iLastLinkRectTop
int m_iLastScrollBarValue
int m_iMaxLines
int m_iMinimumPaintWidth
int m_iMouseTimer
int m_iNumLines
int m_iRelativePixmapY
int m_iSelectionEndCharIndex
int m_iSelectionInitCharIndex
int m_iSelectTimer
int m_iUnprocessedPaintEventRequests
int m_iWrapMargin
QRect m_lineMarkArea
QPoint m_mouseCurrentPos
QPoint m_mousePressPos
KviIrcViewLine * m_pCurLine
KviIrcViewLine * m_pCursorLine
KviIrcViewLine * m_pFirstLine
QFontMetrics * m_pFm
KviMainWindow * m_pFrm
KviWindow * m_pKviWindow
QMouseEvent * m_pLastEvent
KviIrcViewLine * m_pLastLine
KviIrcViewWrappedBlock * m_pLastLinkUnderMouse
QFile * m_pLogFile
KviIrcView * m_pMasterView
KviPointerList< KviIrcViewLine > * m_pMessagesStoppedWhileSelecting
QPixmap * m_pPrivateBackgroundPixmap
QScrollBar * m_pScrollBar
KviIrcViewLine * m_pSelectionEndLine
KviIrcViewLine * m_pSelectionInitLine
QToolButton * m_pToolsButton
QMenu * m_pToolsPopup
KviIrcViewToolTip * m_pToolTip
KviIrcViewToolWidget * m_pToolWidget
KviIrcViewWrappedBlockSelectionInfo * m_pWrappedBlockSelectionInfo
unsigned int m_uLineMarkLineIndex
unsigned int m_uNextLineIndex
Friends
class KviIrcViewToolTip
class KviIrcViewToolWidget
Member Enumeration Documentation
enum KviIrcView::AppendTextFlags
Enumerator
NoRepaint
NoTimestamp
SetLineMark
TriggersNotification
Constructor & Destructor Documentation
KviIrcView::KviIrcView (QWidget * parent, KviWindow * pWnd)
References __tr2qs, KviTalToolTip::add(), applyOptions(), connect(), g_pIconManager, KviIconManager::getSmallIcon(), KVI_IRCVIEW_INVALID_LINE_MARK_INDEX, KVI_IRCVIEW_MINIMUM_HEIGHT, KVI_IRCVIEW_MINIMUM_WIDTH, KVI_OPTION_UINT, KviIrcViewToolTip, KviOption_uintAutoFlushLogs, KviOption_uintIrcViewMaxBufferSize, m_bAcceptDrops, m_bHaveUnreadedHighlightedMessages, m_bHaveUnreadedMessages, m_bMouseIsDown, m_bPostedPaintEventPending, m_bSkipScrollBarRepaint, m_iFlushTimer, m_iFontDescent, m_iFontLineSpacing, m_iFontLineWidth, m_iLastLinkRectHeight, m_iLastLinkRectTop, m_iLastScrollBarValue, m_iMaxLines, m_iMouseTimer, m_iNumLines, m_iSelectionEndCharIndex, m_iSelectionInitCharIndex, m_iSelectTimer, m_iUnprocessedPaintEventRequests, m_pCurLine, m_pCursorLine, m_pFirstLine, m_pFm, m_pKviWindow, m_pLastLine, m_pLastLinkUnderMouse, m_pLogFile, m_pMasterView, m_pMessagesStoppedWhileSelecting, m_pPrivateBackgroundPixmap, m_pScrollBar, m_pSelectionEndLine, m_pSelectionInitLine, m_pToolsButton, m_pToolsPopup, m_pToolTip, m_pToolWidget, m_pWrappedBlockSelectionInfo, m_uLineMarkLineIndex, m_uNextLineIndex, KviIconManager::PopupMenu, scrollBarPositionChanged(), and showToolsPopup().
KviIrcView::~KviIrcView ()
References delete_text_line(), emptyBuffer(), l, m_hAnimatedSmiles, m_iFlushTimer, m_iMouseTimer, m_iSelectTimer, m_pFm, m_pMessagesStoppedWhileSelecting, m_pPrivateBackgroundPixmap, m_pToolTip, m_pToolWidget, m_pWrappedBlockSelectionInfo, and stopLogging().
Member Function Documentation
void KviIrcView::add2Log (const QString & szBuffer, int iMsgType = 0, bool bPrependDate = false)
References KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolStripMsgTypeInLogs, KviOption_uintOutputDatetimeFormat, and m_pLogFile.
Referenced by appendLine(), appendText(), startLogging(), and stopLogging().
void KviIrcView::addControlCharacter (KviIrcViewLineChunk * pC, QString & szSelectionText) private
References _KviIrcViewLineChunk::back, KviControlCodes::Bold, _KviIrcViewLineChunk::colors, _KviIrcViewLineChunk::fore, KviControlCodes::NoChange, KviControlCodes::Reset, KviControlCodes::Reverse, KviControlCodes::Transparent, _KviIrcViewLineChunk::type, and KviControlCodes::Underline.
Referenced by mouseReleaseEvent().
void KviIrcView::animatedIconChange () protected slot
Referenced by getTextLine().
void KviIrcView::appendLine (KviIrcViewLine * ptr, bool bRepaint) private
References add2Log(), _KviIrcViewLine::iMsgType, KVI_ASSERT, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KviOption_boolStripControlCodesInLogs, m_bMouseIsDown, m_bSkipScrollBarRepaint, m_iLastScrollBarValue, m_iMaxLines, m_iNumLines, m_pCurLine, m_pFirstLine, m_pLastLine, m_pLogFile, m_pMasterView, m_pMessagesStoppedWhileSelecting, m_pScrollBar, m_uNextLineIndex, _KviIrcViewLine::pNext, postUpdateEvent(), _KviIrcViewLine::pPrev, removeHeadLine(), _KviIrcViewLine::szText, and _KviIrcViewLine::uIndex.
Referenced by appendText(), and mouseReleaseEvent().
void KviIrcView::appendMessagesFrom (KviIrcView * v)
References m_iLastScrollBarValue, m_iNumLines, m_pCurLine, m_pCursorLine, m_pFirstLine, m_pLastLine, m_pScrollBar, _KviIrcViewLine::pNext, and _KviIrcViewLine::pPrev.
Referenced by KviQueryWindow::mergeQuery().
void KviIrcView::appendText (int msg_type, const kvi_wchar_t * data_ptr, int iFlags = 0, const QDateTime & datetime = QDateTime())
References add2Log(), appendLine(), getTextLine(), _KviIrcViewLine::iBlockCount, _KviIrcViewLine::iMaxLineWidth, _KviIrcViewLine::iMsgType, KVI_ASSERT, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OUT_ACTION, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_DCCCHATMSG, KVI_OUT_DCCCHATMSGCRYPTED, KVI_OUT_HIGHLIGHT, KVI_OUT_QUERYPRIVMSG, KVI_OUT_QUERYPRIVMSGCRYPTED, KviOption_boolStripControlCodesInLogs, KviOption_boolTrackLastReadTextViewLine, m_bHaveUnreadedHighlightedMessages, m_bHaveUnreadedMessages, m_pLastLinkUnderMouse, m_pLogFile, m_pMasterView, m_uLineMarkLineIndex, NoRepaint, NoTimestamp, SetLineMark, TriggersNotification, _KviIrcViewLine::uIndex, and _KviIrcViewLine::uLineWraps.
Referenced by KviWindow::internalOutput().
void KviIrcView::applyOptions ()
References flushLog(), KVI_OPTION_FONT, KVI_OPTION_UINT, KviOption_fontIrcView, KviOption_uintAutoFlushLogs, m_iFlushTimer, reapplyMessageColors(), and setFont().
Referenced by SocketSpyWindow::applyOptions(), LinksWindow::applyOptions(), KviConsoleWindow::applyOptions(), FileTransferWindow::applyOptions(), ListWindow::applyOptions(), KviWindow::applyOptions(), KviChannelWindow::applyOptions(), and KviIrcView().
void KviIrcView::calculateLineWraps (KviIrcViewLine * ptr, int maxWidth) private
References KviMemory::allocate(), _KviIrcViewWrappedBlock::block_len, _KviIrcViewWrappedBlock::block_start, _KviIrcViewWrappedBlock::block_width, KviMemory::free(), _KviIrcViewLine::iBlockCount, KviControlCodes::Icon, _KviIrcViewLine::iMaxLineWidth, IRCVIEW_WCHARWIDTH, _KviIrcViewLineChunk::iTextLen, _KviIrcViewLineChunk::iTextStart, KVI_OPTION_BOOL, KviOption_boolIrcViewWrapMargin, m_iIconWidth, m_iWrapMargin, p, _KviIrcViewLine::pBlocks, _KviIrcViewWrappedBlock::pChunk, _KviIrcViewLine::pChunks, KviMemory::reallocate(), _KviIrcViewLine::szText, _KviIrcViewLineChunk::type, _KviIrcViewLine::uChunkCount, and _KviIrcViewLine::uLineWraps.
Referenced by ensureLineVisible(), fastScroll(), and paintEvent().
bool KviIrcView::checkMarkerArea (const QPoint & mousePos) private
References m_lineMarkArea.
Referenced by maybeTip(), mouseMoveEvent(), and mousePressEvent().
bool KviIrcView::checkSelectionBlock (KviIrcViewLine * line, int bufIndex) private
References _KviIrcViewWrappedBlock::block_len, _KviIrcViewWrappedBlock::block_start, _KviIrcViewWrappedBlock::block_width, i, KviControlCodes::Icon, init(), IRCVIEW_WCHARWIDTH, KVI_IRCVIEW_BLOCK_SELECTION_CENTRAL, KVI_IRCVIEW_BLOCK_SELECTION_ICON, KVI_IRCVIEW_BLOCK_SELECTION_LEFT, KVI_IRCVIEW_BLOCK_SELECTION_RIGHT, KVI_IRCVIEW_BLOCK_SELECTION_TOTAL, m_iSelectionEndCharIndex, m_iSelectionInitCharIndex, m_pSelectionEndLine, m_pSelectionInitLine, m_pWrappedBlockSelectionInfo, p, _KviIrcViewWrappedBlockSelectionInfoTag::part_1_length, _KviIrcViewWrappedBlockSelectionInfoTag::part_1_width, _KviIrcViewWrappedBlockSelectionInfoTag::part_2_length, _KviIrcViewWrappedBlockSelectionInfoTag::part_2_width, _KviIrcViewWrappedBlockSelectionInfoTag::part_3_length, _KviIrcViewWrappedBlockSelectionInfoTag::part_3_width, _KviIrcViewLine::pBlocks, _KviIrcViewWrappedBlock::pChunk, _KviIrcViewWrappedBlockSelectionInfoTag::selection_type, _KviIrcViewLine::szText, _KviIrcViewLineChunk::type, and _KviIrcViewLine::uIndex.
Referenced by paintEvent().
void KviIrcView::chooseBackground () slot
References __tr2qs, KviFileDialog::askForOpenFileName(), f, KviMessageBox::information(), p, and setPrivateBackgroundPixmap().
Referenced by showToolsPopup().
void KviIrcView::chooseFont () slot
COMPILE_ON_MAC
COMPILE_ON_MAC
References __tr, f, and setFont().
Referenced by showToolsPopup().
void KviIrcView::clearBuffer () slot
References emptyBuffer(), m_iNumLines, and m_pScrollBar.
Referenced by LogViewWindow::deleteCurrent(), LogViewWindow::itemSelected(), showToolsPopup(), and window_kvs_cmd_clearOutput().
void KviIrcView::clearLineMark (bool bRepaint = false)
References clearUnreaded(), KVI_IRCVIEW_INVALID_LINE_MARK_INDEX, and m_uLineMarkLineIndex.
Referenced by KviWindow::lostUserFocus(), and KviChannelWindow::lostUserFocus().
void KviIrcView::clearUnreaded ()
References g_pMainWindow, m_bHaveUnreadedHighlightedMessages, m_bHaveUnreadedMessages, KviTrayIcon::refresh(), and KviMainWindow::trayIcon().
Referenced by clearLineMark(), and KviMainWindow::windowActivated().
KviConsoleWindow * KviIrcView::console ()
References KviWindow::console(), and m_pKviWindow.
Referenced by doLinkToolTip(), KviMainWindow::executeInternalCommand(), mouseDoubleClickEvent(), and triggerMouseRelatedKvsEvents().
void KviIrcView::decreaseFontSize () slot
References f, p, and setFont().
Referenced by showToolsPopup(), and KviInputEditor::zoomOut().
void KviIrcView::dndEntered () signal
Referenced by dragEnterEvent().
void KviIrcView::doLinkToolTip (const QRect & rct, QString & linkCmd, QString & linkText) private
References __tr2qs, KviQString::appendFormatted(), c, KviWindow::Channel, KviIconManager::Channel, KviWindow::connection(), console(), KviChannelWindow::count(), KviIrcViewToolTip::doTip(), e, KviIrcUserDataBase::find(), KviIrcConnection::findChannel(), g_pIconManager, KviChannelWindow::getChannelModeString(), getLinkEscapeCommand(), KviIconManager::getSmallIconResourceName(), KviConsoleWindow::getUserTipText(), KviIrcUrl::join(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolEnableChannelLinkToolTip, KviOption_boolEnableEscapeLinkToolTip, KviOption_boolEnableHostLinkToolTip, KviOption_boolEnableModeLinkToolTip, KviOption_boolEnableNickLinkToolTip, KviOption_boolEnableServerLinkToolTip, KviOption_boolEnableUrlLinkToolTip, KviOption_uintUrlMouseClickNum, m_pKviWindow, m_pToolTip, KviIconManager::Proxy, KviIconManager::Server, KviControlCodes::stripControlBytes(), szUrl, KviQString::toHtmlEscaped(), KviTopicWidget::topic(), KviChannelWindow::topicWidget(), KviWindow::type(), KviIconManager::Url, KviIrcConnection::userDataBase(), and KviWindow::windowName().
Referenced by maybeTip().
void KviIrcView::doMarkerToolTip () private
References __tr2qs, KviIrcViewToolTip::doTip(), g_pIconManager, KviIconManager::getSmallIconResourceName(), m_lineMarkArea, m_pToolTip, and KviIconManager::UnreadText.
Referenced by maybeTip().
void KviIrcView::dragEnterEvent (QDragEnterEvent * e) protected virtual
References dndEntered(), and m_bAcceptDrops.
void KviIrcView::dropEvent (QDropEvent * e) protected virtual
References fileDropped(), and m_bAcceptDrops.
int KviIrcView::dummyRead () const inline
void KviIrcView::emptyBuffer (bool bRepaint = true)
References m_pLastLine, and removeHeadLine().
Referenced by clearBuffer(), splitMessagesTo(), and ~KviIrcView().
void KviIrcView::enableDnd (bool bEnable)
References m_bAcceptDrops.
Referenced by KviQueryWindow::KviQueryWindow().
void KviIrcView::ensureLineVisible (KviIrcViewLine * pLineToShow) private
References calculateLineWraps(), _KviIrcViewLine::iMaxLineWidth, KVI_IRCVIEW_DOUBLEBORDER_WIDTH, KVI_IRCVIEW_PIXMAP_AND_SEPARATOR, KVI_IRCVIEW_VERTICAL_BORDER, KVI_OPTION_BOOL, KviOption_boolIrcViewShowImages, m_iFontDescent, m_iFontLineSpacing, m_iLastScrollBarValue, m_iMinimumPaintWidth, m_pCurLine, m_pScrollBar, m_pToolWidget, _KviIrcViewLine::pNext, _KviIrcViewLine::pPrev, _KviIrcViewLine::uIndex, and _KviIrcViewLine::uLineWraps.
Referenced by scrollToMarker(), and setCursorLine().
bool KviIrcView::event (QEvent * e) protected virtual
References KVI_ASSERT, m_bPostedPaintEventPending, and m_iUnprocessedPaintEventRequests.
void KviIrcView::fastScroll (int lines = 1) private
References calculateLineWraps(), _KviIrcViewLine::iMaxLineWidth, KVI_IRCVIEW_DOUBLEBORDER_WIDTH, KVI_IRCVIEW_PIXMAP_AND_SEPARATOR, KVI_OPTION_BOOL, KviOption_boolIrcViewShowImages, l, m_iFontDescent, m_iFontLineSpacing, m_iLastLinkRectHeight, m_iLastLinkRectTop, m_iUnprocessedPaintEventRequests, m_pCurLine, m_pFm, m_pScrollBar, _KviIrcViewLine::pPrev, and _KviIrcViewLine::uLineWraps.
Referenced by postUpdateEvent().
void KviIrcView::fileDropped (const QString &) signal
Referenced by dropEvent().
void KviIrcView::findNext (const QString & szText, bool bCaseS = false, bool bRegExp = false, bool bExtended = false)
References __tr2qs, _KviIrcViewLine::iMsgType, l, m_pCurLine, m_pCursorLine, m_pFirstLine, m_pToolWidget, KviIrcViewToolWidget::messageEnabled(), _KviIrcViewLine::pNext, setCursorLine(), KviIrcViewToolWidget::setFindResult(), and _KviIrcViewLine::szText.
Referenced by KviIrcViewToolWidget::findNext().
void KviIrcView::findPrev (const QString & szText, bool bCaseS = false, bool bRegExp = false, bool bExtended = false)
References __tr2qs, _KviIrcViewLine::iMsgType, l, m_pCurLine, m_pCursorLine, m_pLastLine, m_pToolWidget, KviIrcViewToolWidget::messageEnabled(), _KviIrcViewLine::pPrev, setCursorLine(), KviIrcViewToolWidget::setFindResult(), and _KviIrcViewLine::szText.
Referenced by KviIrcViewToolWidget::findPrev().
void KviIrcView::flushLog () slot
References flushLog(), KVI_OPTION_BOOL, KviOption_boolGzipLogs, m_pLogFile, and m_pMasterView.
Referenced by applyOptions(), flushLog(), log_kvs_cmd_flush(), and timerEvent().
void KviIrcView::getLinkEscapeCommand (QString & buffer, const QString & escape_cmd, const QString & escape_label) private
Referenced by doLinkToolTip(), mouseDoubleClickEvent(), and triggerMouseRelatedKvsEvents().
KviIrcViewWrappedBlock * KviIrcView::getLinkUnderMouse (int xPos, int yPos, QRect * pRect = 0, QString * linkCmd = 0, QString * linkText = 0) private
References _KviIrcViewLineChunk::back, _KviIrcViewWrappedBlock::block_len, _KviIrcViewWrappedBlock::block_start, _KviIrcViewWrappedBlock::block_width, KviControlCodes::Bold, _KviIrcViewLineChunk::colors, KviControlCodes::Escape, _KviIrcViewLineChunk::fore, i, _KviIrcViewLine::iBlockCount, KviControlCodes::Icon, k, KVI_IRCVIEW_HORIZONTAL_BORDER, KVI_IRCVIEW_PIXMAP_AND_SEPARATOR, KVI_IRCVIEW_VERTICAL_BORDER, KVI_OPTION_BOOL, kvi_wstrlen(), KviOption_boolIrcViewShowImages, KviOption_boolIrcViewWrapMargin, l, m_iFontDescent, m_iFontLineSpacing, m_iWrapMargin, m_pCurLine, m_pToolWidget, KviControlCodes::NoChange, _KviIrcViewLine::pBlocks, _KviIrcViewWrappedBlock::pChunk, _KviIrcViewLine::pPrev, KviControlCodes::Reset, KviControlCodes::Reverse, _KviIrcViewLineChunk::szPayload, _KviIrcViewLine::szText, _KviIrcViewLineChunk::type, _KviIrcViewLine::uLineWraps, KviControlCodes::Underline, and KviControlCodes::UnEscape.
Referenced by maybeTip(), mouseDoubleClickEvent(), mouseMoveEvent(), and triggerMouseRelatedKvsEvents().
void KviIrcView::getLogFileName (QString & buffer)
References m_pLogFile.
Referenced by log_kvs_fnc_file().
bool KviIrcView::getPaintOnScreen () const inline
void KviIrcView::getTextBuffer (QString & buffer)
References l, m_pFirstLine, and m_pLastLine.
Referenced by saveBuffer(), and startLogging().
const kvi_wchar_t * KviIrcView::getTextLine (int msg_type, const kvi_wchar_t * data_ptr, KviIrcViewLine * line_ptr, bool bEnableTimeStamp = true, const QDateTime & datetime = QDateTime()) private
References KviMemory::allocate(), animatedIconChange(), KviTextIcon::animatedPixmap(), APPEND_LAST_TEXT_BLOCK, APPEND_LAST_TEXT_BLOCK_HIDDEN_FROM_NOW, APPEND_ZERO_LENGTH_BLOCK, _KviIrcViewLineChunk::back, KviControlCodes::Bold, KviWindow::Channel, KviUserListEntry::color(), _KviIrcViewLineChunk::colors, connect(), KviWindow::connection(), KviMemory::copy(), KviIrcConnection::currentNickName(), _KviIrcViewLineChunk::customFore, e, KviControlCodes::Escape, _KviIrcViewLineChunk::fore, g_pTextIconManager, KviControlCodes::getColorBytesW(), i, KviControlCodes::Icon, _KviIrcViewLineChunk::iTextLen, _KviIrcViewLineChunk::iTextStart, KVI_COLOR_CUSTOM, KVI_COLOR_OWN, KVI_OPTION_BOOL, KVI_OPTION_MSGTYPE, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_ACTION, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_DCCCHATMSG, KVI_OUT_HIGHLIGHT, KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, KVI_OUT_QUERYNOTICE, KVI_OUT_QUERYNOTICECRYPTED, KVI_OUT_QUERYPRIVMSG, KVI_OUT_QUERYPRIVMSGCRYPTED, KVI_OUT_URL, KviEvent_OnURL, KviOption_boolColorNicks, KviOption_boolDrawEmoticons, KviOption_boolIrcViewTimestamp, KviOption_boolIrcViewTimestampUTC, KviOption_boolIrcViewUrlHighlighting, KviOption_boolUseSpecialColorForTimestamp, KviOption_boolUseUserListColorsAsNickColors, KviOption_stringIrcViewTimestampFormat, KviOption_uintTimeStampBackground, KviOption_uintTimeStampForeground, KVS_TRIGGER_EVENT_1, KviTextIconManager::lookupTextIcon(), m_hAnimatedSmiles, m_pKviWindow, NEW_LINE_CHUNK, KviControlCodes::NoChange, p, _KviIrcViewLine::pChunks, KviWindow::Query, KviMemory::reallocate(), KviControlCodes::Reset, KviControlCodes::Reverse, KviTheme::save(), skip_to_end_of_url(), _KviIrcViewLineChunk::szPayload, _KviIrcViewLineChunk::szSmileId, _KviIrcViewLine::szText, _KviIrcViewLineChunk::type, KviWindow::type(), _KviIrcViewLine::uChunkCount, KviControlCodes::Underline, KviControlCodes::UnEscape, KviControlCodes::UnIcon, and url_compare_helper().
Referenced by appendText().
int KviIrcView::getVisibleCharIndexAt (KviIrcViewLine * line, int xPos, int yPos) private
References _KviIrcViewWrappedBlock::block_start, _KviIrcViewWrappedBlock::block_width, i, _KviIrcViewLine::iBlockCount, KVI_IRCVIEW_HORIZONTAL_BORDER, KVI_IRCVIEW_PIXMAP_AND_SEPARATOR, KVI_IRCVIEW_VERTICAL_BORDER, KVI_OPTION_BOOL, KviOption_boolIrcViewShowImages, KviOption_boolIrcViewWrapMargin, l, m_iFontCharacterWidth, m_iFontDescent, m_iFontLineSpacing, m_iWrapMargin, m_pCurLine, m_pFm, m_pToolWidget, _KviIrcViewLine::pBlocks, _KviIrcViewWrappedBlock::pChunk, _KviIrcViewLine::pPrev, _KviIrcViewLine::szText, and _KviIrcViewLine::uLineWraps.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
KviIrcViewLine * KviIrcView::getVisibleLineAt (int yPos) private
References KVI_IRCVIEW_VERTICAL_BORDER, l, m_iFontDescent, m_iFontLineSpacing, m_pCurLine, m_pToolWidget, _KviIrcViewLine::pPrev, and _KviIrcViewLine::uLineWraps.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool KviIrcView::hasLineMark () inline
References KVI_IRCVIEW_INVALID_LINE_MARK_INDEX.
Referenced by KviWindow::internalOutput(), KviWindow::lostUserFocus(), KviChannelWindow::lostUserFocus(), and KviInputEditor::scrollToLastReadLine().
bool KviIrcView::hasPrivateBackgroundPixmap () inline
bool KviIrcView::haveUnreadedHighlightedMessages () inline
bool KviIrcView::haveUnreadedMessages () inline
void KviIrcView::increaseFontSize () slot
References f, and setFont().
Referenced by showToolsPopup(), and KviInputEditor::zoomIn().
bool KviIrcView::isLogging () inline
Referenced by KviApplication::heartbeat(), KviChannelWindow::setAliveChan(), and KviQueryWindow::setAliveQuery().
void KviIrcView::joinMessagesFrom (KviIrcView * v)
References m_iLastScrollBarValue, m_iNumLines, m_pCurLine, m_pCursorLine, m_pFirstLine, m_pLastLine, m_pScrollBar, _KviIrcViewLine::pNext, _KviIrcViewLine::pPrev, and _KviIrcViewLine::uIndex.
Referenced by KviChannelWindow::showDoubleView().
void KviIrcView::keyPressEvent (QKeyEvent * e) protected virtual
References nextPage(), and prevPage().
const QString & KviIrcView::lastLineOfText ()
References KviQString::Empty, m_pLastLine, and _KviIrcViewLine::szText.
Referenced by KviWindow::lastLineOfText().
const QString & KviIrcView::lastMessageText ()
References KviQString::Empty, _KviIrcViewLine::iMsgType, KVI_OUT_ACTION, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_HIGHLIGHT, KVI_OUT_OWNPRIVMSG, KVI_OUT_OWNPRIVMSGCRYPTED, m_pLastLine, _KviIrcViewLine::pPrev, and _KviIrcViewLine::szText.
Referenced by KviWindow::lastMessageText().
void KviIrcView::leaveEvent (QEvent *) protected virtual
References m_pLastLinkUnderMouse.
void KviIrcView::masterDead () protected slot
References m_pMasterView.
Referenced by setMasterView().
int KviIrcView::maxBufferSize () inline
void KviIrcView::maybeTip (const QPoint & pnt) protected
References checkMarkerArea(), doLinkToolTip(), doMarkerToolTip(), getLinkUnderMouse(), and m_pLastLinkUnderMouse.
Referenced by KviIrcViewToolTip::maybeTip().
bool KviIrcView::messageShouldGoToMessageView (int iMsgType)
References KVI_OUT_ACTION, KVI_OUT_CHANNELNOTICE, KVI_OUT_CHANNELNOTICECRYPTED, KVI_OUT_CHANPRIVMSG, KVI_OUT_CHANPRIVMSGCRYPTED, KVI_OUT_HIGHLIGHT, KVI_OUT_OWNPRIVMSG, and KVI_OUT_OWNPRIVMSGCRYPTED.
Referenced by KviChannelWindow::outputMessage(), and splitMessagesTo().
void KviIrcView::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
References __tr2qs, KviKvsVariantList::append(), c, KviWindow::Channel, console(), KviQString::equalCI(), g_pMainWindow, getLinkEscapeCommand(), getLinkUnderMouse(), KVI_OPTION_UINT, KVI_OUT_HOSTLOOKUP, KviEvent_OnChannelNickDefaultActionRequest, KviEvent_OnNickLinkDefaultActionRequest, KviEvent_OnQueryNickDefaultActionRequest, KviEvent_OnTextViewDoubleClicked, KviEvent_OnURLLinkClick, KviOption_uintUrlMouseClickNum, KVS_TRIGGER_EVENT, KVS_TRIGGER_EVENT_0, m_iMouseTimer, m_pKviWindow, m_pLastEvent, KviWindow::output(), KviWindow::Query, KviKvsScript::run(), KviMainWindow::setActiveWindow(), and KviWindow::type().
void KviIrcView::mouseMoveEvent (QMouseEvent * e) protected virtual
References checkMarkerArea(), getLinkUnderMouse(), getVisibleCharIndexAt(), getVisibleLineAt(), KVI_IRCVIEW_SELECT_REPAINT_INTERVAL, KVI_IRCVIEW_VERTICAL_BORDER, m_bMouseIsDown, m_iLastLinkRectHeight, m_iLastLinkRectTop, m_iSelectionEndCharIndex, m_iSelectTimer, m_pLastLinkUnderMouse, m_pSelectionEndLine, nextLine(), prevLine(), and r.
void KviIrcView::mousePressEvent (QMouseEvent * e) protected virtual
References checkMarkerArea(), getVisibleCharIndexAt(), getVisibleLineAt(), KviWindow::input(), m_bCtrlPressed, m_bMouseIsDown, m_bShiftPressed, m_iMouseTimer, m_iSelectionEndCharIndex, m_iSelectionInitCharIndex, m_mouseCurrentPos, m_mousePressPos, m_pCursorLine, m_pKviWindow, m_pLastEvent, m_pSelectionEndLine, m_pSelectionInitLine, m_pToolWidget, scrollToMarker(), KviInput::setFocus(), and triggerMouseRelatedKvsEvents().
void KviIrcView::mouseReleaseEvent (QMouseEvent * e) protected virtual
References addControlCharacter(), appendLine(), c, getVisibleCharIndexAt(), getVisibleLineAt(), i, init(), _KviIrcViewLineChunk::iTextLen, _KviIrcViewLineChunk::iTextStart, KVI_OPTION_BOOL, KviOption_boolRequireControlToCopy, l, m_bCtrlPressed, m_bMouseIsDown, m_bShiftPressed, m_iSelectionEndCharIndex, m_iSelectionInitCharIndex, m_iSelectTimer, m_pMessagesStoppedWhileSelecting, m_pSelectionEndLine, m_pSelectionInitLine, _KviIrcViewLine::pChunks, _KviIrcViewLine::pNext, _KviIrcViewLine::szText, _KviIrcViewLine::uChunkCount, and _KviIrcViewLine::uIndex.
void KviIrcView::nextLine ()
References m_pScrollBar.
Referenced by mouseMoveEvent(), and KviInputEditor::nextLine().
void KviIrcView::nextPage ()
References m_pScrollBar.
Referenced by keyPressEvent(), and KviInputEditor::nextPage().
void KviIrcView::paintEvent (QPaintEvent * p) protected virtual
References KviTextIcon::animatedPixmap(), _KviIrcViewLineChunk::back, KviControlCodes::Black, _KviIrcViewWrappedBlock::block_len, _KviIrcViewWrappedBlock::block_start, _KviIrcViewWrappedBlock::block_width, KviControlCodes::Bold, calculateLineWraps(), checkSelectionBlock(), _KviIrcViewLineChunk::colors, _KviIrcViewLineChunk::customFore, DRAW_NORMAL_TEXT, DRAW_SELECTED_TEXT, KviPixmapUtils::drawPixmapWithPainter(), KviControlCodes::Escape, _KviIrcViewLineChunk::fore, g_pApp, g_pIconManager, g_pMainWindow, g_pTextIconManager, KviIconManager::getSmallIcon(), KviIconManager::Help, i, _KviIrcViewLine::iBlockCount, KviControlCodes::Icon, _KviIrcViewLine::iMaxLineWidth, _KviIrcViewLine::iMsgType, KviWindow::isDocked(), KVI_DEF_BACK, KVI_IRCVIEW_BLOCK_SELECTION_CENTRAL, KVI_IRCVIEW_BLOCK_SELECTION_ICON, KVI_IRCVIEW_BLOCK_SELECTION_LEFT, KVI_IRCVIEW_BLOCK_SELECTION_RIGHT, KVI_IRCVIEW_BLOCK_SELECTION_TOTAL, KVI_IRCVIEW_DOUBLEBORDER_WIDTH, KVI_IRCVIEW_HORIZONTAL_BORDER, KVI_IRCVIEW_PIXMAP_AND_SEPARATOR, KVI_IRCVIEW_VERTICAL_BORDER, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_MIRCCOLOR, KVI_OPTION_MSGTYPE, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KVI_OUT_LINK, KVI_OUT_SEARCH, KVI_OUT_SELECT, kvi_wstrlen(), KviOption_boolIrcViewShowImages, KviOption_boolIrcViewWrapMargin, KviOption_boolTrackLastReadTextViewLine, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorIrcViewBackground, KviOption_colorIrcViewMarkLine, KviOption_pixmapIrcViewBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviOption_uintIrcViewMarkerSize, KviOption_uintIrcViewMarkerStyle, KviOption_uintIrcViewPixmapAlign, KviTextIconManager::lookupTextIcon(), m_bMouseIsDown, m_iFontDescent, m_iFontLineSpacing, m_iIconSideSpacing, m_iMinimumPaintWidth, m_iRelativePixmapY, m_iUnprocessedPaintEventRequests, m_iWrapMargin, m_lineMarkArea, m_pCurLine, m_pCursorLine, m_pFm, m_pKviWindow, m_pLastLinkUnderMouse, m_pPrivateBackgroundPixmap, m_pScrollBar, m_pToolWidget, m_pWrappedBlockSelectionInfo, m_uLineMarkLineIndex, KviControlCodes::NoChange, _KviIrcViewWrappedBlockSelectionInfoTag::part_1_length, _KviIrcViewWrappedBlockSelectionInfoTag::part_1_width, _KviIrcViewWrappedBlockSelectionInfoTag::part_2_length, _KviIrcViewWrappedBlockSelectionInfoTag::part_2_width, _KviIrcViewWrappedBlockSelectionInfoTag::part_3_length, _KviIrcViewWrappedBlockSelectionInfoTag::part_3_width, _KviIrcViewLine::pBlocks, _KviIrcViewWrappedBlock::pChunk, KviAnimatedPixmap::pixmap(), KviTextIcon::pixmap(), _KviIrcViewLine::pNext, _KviIrcViewLine::pPrev, r, recalcFontVariables(), KviControlCodes::Reset, KviControlCodes::Reverse, _KviIrcViewWrappedBlockSelectionInfoTag::selection_type, SET_ANTI_ALIASING, SET_PEN, KviApplication::supportsCompositing(), _KviIrcViewLineChunk::szSmileId, _KviIrcViewLine::szText, KviControlCodes::Transparent, _KviIrcViewLineChunk::type, _KviIrcViewLine::uIndex, _KviIrcViewLine::uLineWraps, KviControlCodes::Underline, KviControlCodes::UnEscape, KviIconManager::UnreadText, x, and y.
Referenced by KviIrcViewToolWidget::forceRepaint().
KviWindow* KviIrcView::parentKviWindow () inline
Referenced by KviIrcViewToolWidget::KviIrcViewToolWidget(), and KviIrcViewToolWidget::~KviIrcViewToolWidget().
void KviIrcView::postUpdateEvent () private
References e, fastScroll(), g_pApp, KVI_OPTION_BOOL, KVI_OPTION_PIXMAP, KviOption_boolUseCompositingForTransparency, KviOption_pixmapIrcViewBackground, m_bPostedPaintEventPending, m_iUnprocessedPaintEventRequests, and m_pPrivateBackgroundPixmap.
Referenced by appendLine().
void KviIrcView::prevLine ()
References m_pScrollBar.
Referenced by mouseMoveEvent(), and KviInputEditor::previousLine().
void KviIrcView::prevPage ()
References m_pScrollBar.
Referenced by keyPressEvent(), and KviInputEditor::previousPage().
void KviIrcView::reapplyMessageColors () private
References _KviIrcViewLineChunk::back, _KviIrcViewLineChunk::colors, _KviIrcViewLineChunk::fore, _KviIrcViewLine::iMaxLineWidth, _KviIrcViewLine::iMsgType, KVI_OPTION_MSGTYPE, m_pFirstLine, _KviIrcViewLine::pChunks, _KviIrcViewLine::pNext, u, and _KviIrcViewLine::uChunkCount.
Referenced by applyOptions().
void KviIrcView::recalcFontVariables (const QFontMetrics & fm, const QFontInfo & fi) private
References i, KVI_IRCVIEW_PIXMAP_SIZE, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolIrcViewShowImages, KviOption_boolIrcViewTimestamp, KviOption_boolIrcViewTimestampUTC, KviOption_stringIrcViewTimestampFormat, m_iFontCharacterWidth, m_iFontDescent, m_iFontLineSpacing, m_iFontLineWidth, m_iIconSideSpacing, m_iIconWidth, m_iMinimumPaintWidth, m_iRelativePixmapY, m_iWrapMargin, and m_pFm.
Referenced by paintEvent().
void KviIrcView::removeHeadLine (bool bRepaint = false)
References delete_text_line(), m_hAnimatedSmiles, m_iNumLines, m_pCurLine, m_pCursorLine, m_pFirstLine, m_pLastLine, _KviIrcViewLine::pNext, and _KviIrcViewLine::pPrev.
Referenced by appendLine(), emptyBuffer(), and setMaxBufferSize().
void KviIrcView::resetBackground () slot
References setPrivateBackgroundPixmap().
Referenced by showToolsPopup().
void KviIrcView::resetDefaultFont () slot
References KVI_OPTION_FONT, KviOption_fontIrcView, and setFont().
Referenced by KviInputEditor::zoomDefault().
void KviIrcView::resizeEvent (QResizeEvent *) protected virtual
References h, m_pScrollBar, m_pToolsButton, and m_pToolWidget.
void KviIrcView::rightClicked () signal
Referenced by triggerMouseRelatedKvsEvents().
bool KviIrcView::saveBuffer (const char * filename)
References f, and getTextBuffer().
void KviIrcView::scrollBarPositionChanged (int newValue) protected virtual slot
References m_bSkipScrollBarRepaint, m_iLastScrollBarValue, m_pCurLine, _KviIrcViewLine::pNext, and _KviIrcViewLine::pPrev.
Referenced by KviIrcView().
void KviIrcView::scrollToMarker ()
References ensureLineVisible(), m_pCurLine, m_pFirstLine, m_uLineMarkLineIndex, _KviIrcViewLine::pPrev, and _KviIrcViewLine::uIndex.
Referenced by mousePressEvent(), and KviInputEditor::scrollToLastReadLine().
void KviIrcView::setCursorLine (KviIrcViewLine * l) private
References ensureLineVisible(), l, and m_pCursorLine.
Referenced by findNext(), and findPrev().
void KviIrcView::setFont (const QFont & f) virtual
References _KviIrcViewLine::iMaxLineWidth, l, m_pFirstLine, m_pFm, and _KviIrcViewLine::pNext.
Referenced by applyOptions(), chooseFont(), decreaseFontSize(), increaseFontSize(), and resetDefaultFont().
void KviIrcView::setMasterView (KviIrcView * v)
References connect(), m_pMasterView, masterDead(), and v.
Referenced by KviChannelWindow::showDoubleView().
void KviIrcView::setMaxBufferSize (int maxBufSize, bool bRepaint = true)
References m_iMaxLines, m_iNumLines, m_pScrollBar, and removeHeadLine().
Referenced by LogViewWindow::LogViewWindow().
void KviIrcView::setPaintOnScreen (bool bFlag) inline
void KviIrcView::setPrivateBackgroundPixmap (const QPixmap & pixmap, bool bRepaint = true)
References m_pPrivateBackgroundPixmap.
Referenced by chooseBackground(), KviChannelWindow::loadProperties(), resetBackground(), and KviChannelWindow::showDoubleView().
void KviIrcView::showToolsPopup () slot
References __tr2qs, chooseBackground(), chooseFont(), clearBuffer(), decreaseFontSize(), g_pIconManager, KviIconManager::getSmallIcon(), increaseFontSize(), m_pToolsButton, m_pToolsPopup, KviIconManager::Minus, KviIconManager::Plus, resetBackground(), s, KviIconManager::Search, and toggleToolWidget().
Referenced by KviIrcView().
QSize KviIrcView::sizeHint () const virtual
References KVI_IRCVIEW_SIZEHINT_HEIGHT, and KVI_IRCVIEW_SIZEHINT_WIDTH.
Referenced by SocketSpyWindow::sizeHint(), KviDebugWindow::sizeHint(), DccChatWindow::sizeHint(), KviConsoleWindow::sizeHint(), KviQueryWindow::sizeHint(), LogViewWindow::sizeHint(), DccVoiceWindow::sizeHint(), and KviChannelWindow::sizeHint().
void KviIrcView::splitMessagesTo (KviIrcView * v)
References emptyBuffer(), _KviIrcViewLine::iMsgType, l, m_iLastScrollBarValue, m_iNumLines, m_pCurLine, m_pCursorLine, m_pFirstLine, m_pLastLine, m_pScrollBar, messageShouldGoToMessageView(), _KviIrcViewLine::pNext, and _KviIrcViewLine::pPrev.
Referenced by KviChannelWindow::showDoubleView().
bool KviIrcView::startLogging (const QString & fname = QString(), bool bPrependCurBuffer = false)
References __tr2qs, add2Log(), KviWindow::getDefaultLogFileName(), getTextBuffer(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolGzipLogs, KviOption_uintOutputDatetimeFormat, m_pKviWindow, m_pLogFile, and stopLogging().
Referenced by DccChatWindow::DccChatWindow(), DccVideoWindow::DccVideoWindow(), KviApplication::heartbeat(), KviChannelWindow::KviChannelWindow(), KviQueryWindow::KviQueryWindow(), log_kvs_cmd_start(), KviChannelWindow::setAliveChan(), and KviQueryWindow::setAliveQuery().
void KviIrcView::stopLogging ()
References __tr2qs, add2Log(), KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolGzipLogs, KviOption_uintOutputDatetimeFormat, and m_pLogFile.
Referenced by log_kvs_cmd_stop(), startLogging(), and ~KviIrcView().
void KviIrcView::timerEvent (QTimerEvent * e) protected virtual
References flushLog(), m_iFlushTimer, m_iMouseTimer, m_iSelectTimer, m_mouseCurrentPos, m_pLastEvent, and triggerMouseRelatedKvsEvents().
void KviIrcView::toggleToolWidget () slot
References KviIrcViewToolWidget::focusStringToFind(), h, KviWindow::input(), KviIrcViewToolWidget, m_pCursorLine, m_pKviWindow, m_pScrollBar, KviIrcViewToolWidget::m_pStringToFind, m_pToolWidget, and KviInput::setFocus().
Referenced by LogViewWindow::keyPressEvent(), KviInputEditor::search(), and showToolsPopup().
void KviIrcView::triggerMouseRelatedKvsEvents (QMouseEvent * e) private
References KviKvsVariantList::append(), KviWindow::Channel, console(), KviQString::equalCI(), getLinkEscapeCommand(), getLinkUnderMouse(), KVI_OPTION_UINT, KviEvent_OnChannelLinkClick, KviEvent_OnChannelLinkPopupRequest, KviEvent_OnChannelNickLinkClick, KviEvent_OnChannelNickPopupRequest, KviEvent_OnConsoleNickLinkClick, KviEvent_OnHostLinkClick, KviEvent_OnHostLinkPopupRequest, KviEvent_OnNickLinkPopupRequest, KviEvent_OnQueryNickLinkClick, KviEvent_OnQueryNickPopupRequest, KviEvent_OnServerLinkClick, KviEvent_OnServerLinkPopupRequest, KviEvent_OnURLLinkClick, KviEvent_OnURLLinkPopupRequest, KviEvent_OnWindowPopupRequest, KviOption_uintUrlMouseClickNum, KVS_TRIGGER_EVENT, KVS_TRIGGER_EVENT_0, m_pKviWindow, KviWindow::Query, rightClicked(), KviKvsScript::run(), and KviWindow::type().
Referenced by mousePressEvent(), and timerEvent().
void KviIrcView::wheelEvent (QWheelEvent * e) protected virtual
References g_pApp, and m_pScrollBar.
Friends And Related Function Documentation
friend class KviIrcViewToolTip friend
Referenced by KviIrcView().
friend class KviIrcViewToolWidget friend
Referenced by toggleToolWidget().
Member Data Documentation
bool KviIrcView::m_bAcceptDrops private
Referenced by dragEnterEvent(), dropEvent(), enableDnd(), and KviIrcView().
bool KviIrcView::m_bCtrlPressed private
Referenced by mousePressEvent(), and mouseReleaseEvent().
bool KviIrcView::m_bHaveUnreadedHighlightedMessages private
Referenced by appendText(), clearUnreaded(), and KviIrcView().
bool KviIrcView::m_bHaveUnreadedMessages private
Referenced by appendText(), clearUnreaded(), and KviIrcView().
bool KviIrcView::m_bMouseIsDown private
Referenced by appendLine(), KviIrcView(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
bool KviIrcView::m_bPostedPaintEventPending private
Referenced by event(), KviIrcView(), and postUpdateEvent().
bool KviIrcView::m_bShiftPressed private
Referenced by mousePressEvent(), and mouseReleaseEvent().
bool KviIrcView::m_bSkipScrollBarRepaint private
Referenced by appendLine(), KviIrcView(), and scrollBarPositionChanged().
QMultiHash<KviIrcViewLine *, KviAnimatedPixmap *> KviIrcView::m_hAnimatedSmiles private
Referenced by getTextLine(), removeHeadLine(), and ~KviIrcView().
int KviIrcView::m_iFlushTimer private
Referenced by applyOptions(), KviIrcView(), timerEvent(), and ~KviIrcView().
int KviIrcView::m_iFontCharacterWidth[256] private
Referenced by getVisibleCharIndexAt(), and recalcFontVariables().
int KviIrcView::m_iFontDescent private
Referenced by ensureLineVisible(), fastScroll(), getLinkUnderMouse(), getVisibleCharIndexAt(), getVisibleLineAt(), KviIrcView(), paintEvent(), and recalcFontVariables().
int KviIrcView::m_iFontLineSpacing private
Referenced by ensureLineVisible(), fastScroll(), getLinkUnderMouse(), getVisibleCharIndexAt(), getVisibleLineAt(), KviIrcView(), paintEvent(), and recalcFontVariables().
int KviIrcView::m_iFontLineWidth private
Referenced by KviIrcView(), and recalcFontVariables().
int KviIrcView::m_iIconSideSpacing private
Referenced by paintEvent(), and recalcFontVariables().
int KviIrcView::m_iIconWidth private
Referenced by calculateLineWraps(), and recalcFontVariables().
int KviIrcView::m_iLastLinkRectHeight private
Referenced by fastScroll(), KviIrcView(), and mouseMoveEvent().
int KviIrcView::m_iLastLinkRectTop private
Referenced by fastScroll(), KviIrcView(), and mouseMoveEvent().
int KviIrcView::m_iLastScrollBarValue private
Referenced by appendLine(), appendMessagesFrom(), ensureLineVisible(), joinMessagesFrom(), KviIrcView(), scrollBarPositionChanged(), and splitMessagesTo().
int KviIrcView::m_iMaxLines private
Referenced by appendLine(), KviIrcView(), and setMaxBufferSize().
int KviIrcView::m_iMinimumPaintWidth private
Referenced by ensureLineVisible(), paintEvent(), and recalcFontVariables().
int KviIrcView::m_iMouseTimer private
Referenced by KviIrcView(), mouseDoubleClickEvent(), mousePressEvent(), timerEvent(), and ~KviIrcView().
int KviIrcView::m_iNumLines private
Referenced by appendLine(), appendMessagesFrom(), clearBuffer(), joinMessagesFrom(), KviIrcView(), removeHeadLine(), setMaxBufferSize(), and splitMessagesTo().
int KviIrcView::m_iRelativePixmapY private
Referenced by paintEvent(), and recalcFontVariables().
int KviIrcView::m_iSelectionEndCharIndex private
Referenced by checkSelectionBlock(), KviIrcView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
int KviIrcView::m_iSelectionInitCharIndex private
Referenced by checkSelectionBlock(), KviIrcView(), mousePressEvent(), and mouseReleaseEvent().
int KviIrcView::m_iSelectTimer private
Referenced by KviIrcView(), mouseMoveEvent(), mouseReleaseEvent(), timerEvent(), and ~KviIrcView().
int KviIrcView::m_iUnprocessedPaintEventRequests private
Referenced by event(), fastScroll(), KviIrcView(), paintEvent(), and postUpdateEvent().
int KviIrcView::m_iWrapMargin private
Referenced by calculateLineWraps(), getLinkUnderMouse(), getVisibleCharIndexAt(), paintEvent(), and recalcFontVariables().
QRect KviIrcView::m_lineMarkArea private
Referenced by checkMarkerArea(), doMarkerToolTip(), and paintEvent().
QPoint KviIrcView::m_mouseCurrentPos private
Referenced by mousePressEvent(), and timerEvent().
QPoint KviIrcView::m_mousePressPos private
Referenced by mousePressEvent().
KviIrcViewLine* KviIrcView::m_pCurLine private
Referenced by appendLine(), appendMessagesFrom(), ensureLineVisible(), fastScroll(), findNext(), findPrev(), getLinkUnderMouse(), getVisibleCharIndexAt(), getVisibleLineAt(), joinMessagesFrom(), KviIrcView(), paintEvent(), removeHeadLine(), scrollBarPositionChanged(), scrollToMarker(), and splitMessagesTo().
KviIrcViewLine* KviIrcView::m_pCursorLine private
Referenced by appendMessagesFrom(), findNext(), KviIrcViewToolWidget::findNextHelper(), findPrev(), joinMessagesFrom(), KviIrcView(), mousePressEvent(), paintEvent(), removeHeadLine(), setCursorLine(), splitMessagesTo(), and toggleToolWidget().
KviIrcViewLine* KviIrcView::m_pFirstLine private
Referenced by appendLine(), appendMessagesFrom(), findNext(), KviIrcViewToolWidget::findNextHelper(), getTextBuffer(), joinMessagesFrom(), KviIrcView(), reapplyMessageColors(), removeHeadLine(), scrollToMarker(), setFont(), and splitMessagesTo().
QFontMetrics* KviIrcView::m_pFm private
Referenced by fastScroll(), getVisibleCharIndexAt(), KviIrcView(), paintEvent(), recalcFontVariables(), setFont(), and ~KviIrcView().
KviMainWindow* KviIrcView::m_pFrm private
KviWindow* KviIrcView::m_pKviWindow private
Referenced by console(), doLinkToolTip(), getTextLine(), KviIrcView(), mouseDoubleClickEvent(), mousePressEvent(), paintEvent(), startLogging(), toggleToolWidget(), and triggerMouseRelatedKvsEvents().
QMouseEvent* KviIrcView::m_pLastEvent private
Referenced by mouseDoubleClickEvent(), mousePressEvent(), and timerEvent().
KviIrcViewLine* KviIrcView::m_pLastLine private
Referenced by appendLine(), appendMessagesFrom(), emptyBuffer(), findPrev(), getTextBuffer(), joinMessagesFrom(), KviIrcView(), lastLineOfText(), lastMessageText(), removeHeadLine(), and splitMessagesTo().
KviIrcViewWrappedBlock* KviIrcView::m_pLastLinkUnderMouse private
Referenced by appendText(), KviIrcView(), leaveEvent(), maybeTip(), mouseMoveEvent(), and paintEvent().
QFile* KviIrcView::m_pLogFile private
Referenced by add2Log(), appendLine(), appendText(), flushLog(), getLogFileName(), KviIrcView(), startLogging(), and stopLogging().
KviIrcView* KviIrcView::m_pMasterView private
Referenced by appendLine(), appendText(), flushLog(), KviIrcView(), masterDead(), and setMasterView().
KviPointerList<KviIrcViewLine>* KviIrcView::m_pMessagesStoppedWhileSelecting private
Referenced by appendLine(), KviIrcView(), mouseReleaseEvent(), and ~KviIrcView().
QPixmap* KviIrcView::m_pPrivateBackgroundPixmap private
Referenced by KviIrcView(), paintEvent(), postUpdateEvent(), setPrivateBackgroundPixmap(), and ~KviIrcView().
QScrollBar* KviIrcView::m_pScrollBar private
Referenced by appendLine(), appendMessagesFrom(), clearBuffer(), ensureLineVisible(), fastScroll(), joinMessagesFrom(), KviIrcView(), nextLine(), nextPage(), paintEvent(), prevLine(), prevPage(), resizeEvent(), setMaxBufferSize(), splitMessagesTo(), toggleToolWidget(), and wheelEvent().
KviIrcViewLine* KviIrcView::m_pSelectionEndLine private
Referenced by checkSelectionBlock(), KviIrcView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
KviIrcViewLine* KviIrcView::m_pSelectionInitLine private
Referenced by checkSelectionBlock(), KviIrcView(), mousePressEvent(), and mouseReleaseEvent().
QToolButton* KviIrcView::m_pToolsButton private
Referenced by KviIrcView(), resizeEvent(), and showToolsPopup().
QMenu* KviIrcView::m_pToolsPopup private
Referenced by KviIrcView(), and showToolsPopup().
KviIrcViewToolTip* KviIrcView::m_pToolTip private
Referenced by doLinkToolTip(), doMarkerToolTip(), KviIrcView(), and ~KviIrcView().
KviIrcViewToolWidget* KviIrcView::m_pToolWidget private
Referenced by ensureLineVisible(), findNext(), findPrev(), getLinkUnderMouse(), getVisibleCharIndexAt(), getVisibleLineAt(), KviIrcView(), mousePressEvent(), paintEvent(), resizeEvent(), toggleToolWidget(), and ~KviIrcView().
KviIrcViewWrappedBlockSelectionInfo* KviIrcView::m_pWrappedBlockSelectionInfo private
Referenced by checkSelectionBlock(), KviIrcView(), paintEvent(), and ~KviIrcView().
unsigned int KviIrcView::m_uLineMarkLineIndex private
Referenced by appendText(), clearLineMark(), KviIrcView(), paintEvent(), and scrollToMarker().
unsigned int KviIrcView::m_uNextLineIndex private
Referenced by appendLine(), and KviIrcView().
Property Documentation
int KviIrcView::TransparencyCapable read
bool KviIrcView::usePaintOnScreen read write
The documentation for this class was generated from the following files:
src/kvirc/ui/KviIrcView.h
src/kvirc/ui/KviIrcView.cpp
src/kvirc/ui/KviIrcView_events.cpp
src/kvirc/ui/KviIrcView_getTextLine.cpp
src/kvirc/ui/KviIrcView_loghandling.cpp