KVIrc: KviMexServerImport Class Reference
KviMexServerImport Class Reference abstract
#include <KviMexServerImport.h>
Signals
void server (const KviIrcServer &s, const QString &network)
Public Member Functions
virtual void die ()=0
KviMexServerImport (KviModuleExtensionDescriptor *d)
virtual void start ()=0
~KviMexServerImport ()
Public Member Functions inherited from KviModuleExtension
KviModuleExtensionDescriptor * descriptor ()
KviModuleExtension (KviModuleExtensionDescriptor *d)
virtual ~KviModuleExtension ()
Additional Inherited Members
Static Public Member Functions inherited from KviModuleExtension
static KviModuleExtensionManager * manager ()
Constructor & Destructor Documentation
KviMexServerImport::KviMexServerImport (KviModuleExtensionDescriptor * d)
KviMexServerImport::~KviMexServerImport () default
Member Function Documentation
virtual void KviMexServerImport::die () pure virtual
Implements KviModuleExtension.
Implemented in KviRemoteMircServersIniImport, and KviMircServersIniImport.
Referenced by OptionsWidget_servers::importPopupActivated(), and OptionsWidget_servers::~OptionsWidget_servers().
void KviMexServerImport::server (const KviIrcServer & s, const QString & network) signal
Referenced by KviMircServersIniImport::doImport().
virtual void KviMexServerImport::start () pure virtual
Implemented in KviRemoteMircServersIniImport, and KviMircServersIniImport.
Referenced by OptionsWidget_servers::importPopupActivated().
The documentation for this class was generated from the following files:
src/kvirc/module/KviMexServerImport.h
src/kvirc/module/KviMexServerImport.cpp