KVIrc: KviMdiChild Class Reference
KviMdiChild Class Reference
Class of an MDI window.
#include <kvi_mdichild.h>
Public Types
enum MdiChildState { Maximized = 0, Minimized, Normal }
This is the state of the child window.
Public Slots
void maximize ()
Maximizes this window.
void minimize ()
Minimizes this window.
void restore ()
Restore it's latest postition/state.
void windowStateChangedEvent (Qt::WindowStates oldState, Qt::WindowStates newState)
Triggered when the state of a window changes.
Public Member Functions
void activate ()
Activates this subwindow.
QWidget * client ()
Returns the currently in the window visible widget.
const QPixmap * icon ()
Returns current window icon.
KviMdiChild (KviMdiManager *pPar, const char *pcName=0)
Constructs the Mdi child object.
KviMdiManager * manager ()
Returns the current KviMdiManager of the subwindow.
const QString & plainCaption ()
Returns plain text caption.
QRect restoredGeometry ()
Read the current geometry.
void setClient (QWidget *w)
Sets the client widget which is shown in the subwindow.
void setIcon (QPixmap pix)
Sets the window icon.
void setRestoredGeometry (const QRect &r)
Sets the new geomentry.
void setWindowTitle (const QString &szPlain)
Sets the window title.
MdiChildState state ()
Gets the current window state.
void unsetClient ()
Removes the client widget.
~KviMdiChild ()
Destroys the Mdi child object.
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
Hooks into close event to make user decisions possible.
virtual void moveEvent (QMoveEvent *e)
Updates the widget background when moving.
Protected Attributes
KviMdiManager * m_pManager
Contains the according KviMdiManager object.
Private Slots
void transparencyWorkaround ()
This is an ugly woraround for qt 4.6.1 that otherway will display the first console window as transparent.
void updateSystemPopup ()
Updates the system popup.
Private Member Functions
void updateCaption ()
Updates the caption of the child.
Private Attributes
QWidget * m_pClient
The widget docked into our MDI window.
QPixmap m_pIcon
Contains the current window Icon.
QRect m_restoredGeometry
Saves the geometry of the window for restoring it's position.
QString m_szPlainCaption
Caption as plain text.
Friends
class KviMdiManager
Detailed Description
Class of an MDI window.
Member Enumeration Documentation
enum KviMdiChild::MdiChildState
This is the state of the child window.
Enumerator:
Maximized
The child window is maximized
Minimized
The child window is minimized
Normal
The child window is normal
Constructor & Destructor Documentation
KviMdiChild::KviMdiChild (KviMdiManager * pPar, const char * pcName = 0)
Constructs the Mdi child object.
Parameters:
pPar The mdi-manager the mdi-child belongs to.
pcName The name of the mdi-child
Returns:
KviMdiChild
References m_pClient, m_pManager, m_restoredGeometry, transparencyWorkaround(), updateSystemPopup(), and windowStateChangedEvent().
KviMdiChild::~KviMdiChild ()
Destroys the Mdi child object.
References KviMdiManager::focusPreviousTopChild(), m_pClient, and m_pManager.
Member Function Documentation
void KviMdiChild::activate ()
Activates this subwindow.
Returns:
void
References m_pManager, KviMdiManager::setTopChild(), and KviMdiManager::topChild().
Referenced by KviWindow::activateSelf(), and KviMdiManager::showAndActivate().
QWidget* KviMdiChild::client () [inline]
Returns the currently in the window visible widget.
Returns:
QWidget *
void KviMdiChild::closeEvent (QCloseEvent * e) [protected, virtual]
Hooks into close event to make user decisions possible.
Returns:
void
References KviWindow::delayedClose().
const QPixmap * KviMdiChild::icon ()
Returns current window icon.
Returns:
const QPixmap *
References m_pIcon.
Referenced by KviMdiManager::fillWindowPopup().
KviMdiManager* KviMdiChild::manager () [inline]
Returns the current KviMdiManager of the subwindow.
Returns:
KviMdiManager *
void KviMdiChild::maximize () [slot]
Maximizes this window.
Returns:
void
Referenced by KviMdiManager::focusPreviousTopChild(), and KviWindow::maximize().
void KviMdiChild::minimize () [slot]
Minimizes this window.
Returns:
void
Referenced by KviWindow::minimize(), and KviMdiManager::minimizeAll().
void KviMdiChild::moveEvent (QMoveEvent * e) [protected, virtual]
Updates the widget background when moving.
Returns:
void
References m_pClient.
const QString& KviMdiChild::plainCaption () [inline]
Returns plain text caption.
Returns:
const QString &
void KviMdiChild::restore () [slot]
Restore it's latest postition/state.
Returns:
void
Referenced by KviMdiManager::ensureNoMaximized(), KviMdiManager::menuActivated(), KviWindow::restore(), and KviMdiManager::restoreAll().
QRect KviMdiChild::restoredGeometry ()
Read the current geometry.
Returns:
QRect
Referenced by KviWindow::externalGeometry().
void KviMdiChild::setClient (QWidget * w)
Sets the client widget which is shown in the subwindow.
Parameters:
w The new client widget which is docked into our KviMdiChild
Returns:
void
Warning:
The widget has to inherit of KviWindow!
References __range_valid, KviStr::Format, m_pClient, KviNetwork::name(), KviIrcConnectionTarget::network(), and KviIrcConnection::target().
Referenced by KviFrame::dockWindow().
void KviMdiChild::setIcon (QPixmap pix)
Sets the window icon.
Parameters:
pix The new icon
Returns:
void
References m_pIcon.
void KviMdiChild::setRestoredGeometry (const QRect & r)
Sets the new geomentry.
Parameters:
r The geometry the window will take when it will be restored
Returns:
void
References m_restoredGeometry.
Referenced by KviFrame::addWindow().
void KviMdiChild::setWindowTitle (const QString & szPlain)
Sets the window title.
Parameters:
szPlain Plain text of caption
Returns:
void
References m_szPlainCaption.
Referenced by KviWindow::updateCaption().
KviMdiChild::MdiChildState KviMdiChild::state ()
Gets the current window state.
Returns:
MdiChildState
For details see the MdiChildState declaration
References Maximized, Minimized, and Normal.
Referenced by KviMdiManager::cascadeMaximized(), KviMdiManager::ensureNoMaximized(), KviMdiManager::expandHorizontal(), KviMdiManager::expandVertical(), KviMdiManager::fillWindowPopup(), KviMdiManager::focusPreviousTopChild(), KviMdiManager::menuActivated(), KviMdiManager::minimizeAll(), KviMdiManager::restoreAll(), and KviMdiManager::tileAllInternal().
void KviMdiChild::transparencyWorkaround () [private, slot]
This is an ugly woraround for qt 4.6.1 that otherway will display the first console window as transparent.
Returns:
void
Referenced by KviMdiChild().
void KviMdiChild::unsetClient ()
Removes the client widget.
Returns:
void
References __range_valid, and m_pClient.
Referenced by KviFrame::undockWindow().
void KviMdiChild::updateCaption () [private]
Updates the caption of the child.
Returns:
void
References m_pClient.
Referenced by windowStateChangedEvent().
void KviMdiChild::updateSystemPopup () [private, slot]
Updates the system popup.
Returns:
void
References m_pClient.
Referenced by KviMdiChild().
void KviMdiChild::windowStateChangedEvent (Qt::WindowStates oldState, Qt::WindowStates newState) [slot]
Triggered when the state of a window changes.
This event is used to catch minmize event of the KviMdiSubWindow
Parameters:
oldState The old state of the window
newState The new state of the window
Returns:
void
References KviMdiManager::focusPreviousTopChild(), m_pManager, KviMdiManager::setIsInSDIMode(), and updateCaption().
Referenced by KviMdiChild().
Friends And Related Function Documentation
friend class KviMdiManager [friend]
Member Data Documentation
QWidget* KviMdiChild::m_pClient [private]
The widget docked into our MDI window.
Referenced by KviMdiChild(), moveEvent(), setClient(), unsetClient(), updateCaption(), updateSystemPopup(), and ~KviMdiChild().
QPixmap KviMdiChild::m_pIcon [private]
Contains the current window Icon.
Referenced by icon(), and setIcon().
KviMdiManager* KviMdiChild::m_pManager [protected]
Contains the according KviMdiManager object.
Referenced by activate(), KviMdiChild(), windowStateChangedEvent(), and ~KviMdiChild().
QRect KviMdiChild::m_restoredGeometry [private]
Saves the geometry of the window for restoring it's position.
Referenced by KviMdiChild(), and setRestoredGeometry().
QString KviMdiChild::m_szPlainCaption [private]
Caption as plain text.
Referenced by setWindowTitle().
The documentation for this class was generated from the following files:
src/kvirc/ui/kvi_mdichild.h
src/kvirc/ui/kvi_mdichild.cpp