KVIrc: KviChangeUserModeAction Class Reference
KviChangeUserModeAction Class Reference
#include <KviCoreActions.h>
Public Member Functions
KviChangeUserModeAction (QObject *pParent)
Protected Slots
void popupAboutToShow ()
void popupActivated (int)
Constructor & Destructor Documentation
KviChangeUserModeAction::KviChangeUserModeAction (QObject * pParent)
Member Function Documentation
void KviChangeUserModeAction::popupAboutToShow () [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References __tr2qs, c, KviTalPopupMenu::clear(), KviWindow::connection(), KviWindow::console(), g_pActiveWindow, g_pIconManager, KviIconManager::getSmallIcon(), KviIrcConnectionUserInfo::hasUserMode(), KviTalPopupMenu::insertItem(), KviIconManager::Invisible, KviSubmenuAction::m_pPopup, KviIconManager::Mode, KviIrcConnection::serverInfo(), KviIconManager::ServerNotice, KviTalPopupMenu::setItemChecked(), KviIrcConnectionServerInfo::supportedUserModes(), KviIrcConnection::userInfo(), and KviIconManager::WallOps.
void KviChangeUserModeAction::popupActivated (int id) [protected, virtual, slot]
Reimplemented from KviSubmenuAction.
References c, KviWindow::connection(), KviWindow::console(), KviQString::escapeKvs(), g_pActiveWindow, KviIrcConnectionUserInfo::hasUserMode(), KviConsoleWindow::isConnected(), m, KviSubmenuAction::m_pPopup, KviIrcConnectionUserInfo::nickName(), KviIrcUrl::run(), KviTalPopupMenu::text(), and KviIrcConnection::userInfo().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCoreActions.h
src/kvirc/kernel/KviCoreActions.cpp