KVIrc: KviImageDialogItem Class Reference
KviImageDialogItem Class Reference
#include <KviImageDialog.h>
Public Member Functions
virtual int height (const KviTalListWidget *) const
const QString & imageId ()
bool isFolder ()
KviImageDialogItem (KviTalListWidget *b, const QPixmap &thumb, const QString &szFile, const QString &image_id, const QString &szTipText=QString(), bool bIsFolder=false)
virtual void paint (QPainter *p)
const QString & tipText ()
virtual int width (const KviTalListWidget *) const
~KviImageDialogItem ()
Public Member Functions inherited from KviTalListWidgetPixmap
KviTalListWidgetPixmap (KviTalListWidget *listbox, const QPixmap &)
KviTalListWidgetPixmap (const QPixmap &)
KviTalListWidgetPixmap (KviTalListWidget *listbox, const QPixmap &, const QString &)
KviTalListWidgetPixmap (const QPixmap &, const QString &)
const QPixmap * pixmap () const
int rtti () const
~KviTalListWidgetPixmap ()
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Public Attributes
bool m_bIsFolder
QString m_szImageId
QString m_szTipText
Additional Inherited Members
Public Types inherited from KviTalListWidgetPixmap
enum { RTTI = 2 }
Constructor & Destructor Documentation
KviImageDialogItem::KviImageDialogItem (KviTalListWidget * b, const QPixmap & thumb, const QString & szFile, const QString & image_id, const QString & szTipText = QString(), bool bIsFolder = false) inline
KviImageDialogItem::~KviImageDialogItem () inline
Member Function Documentation
int KviImageDialogItem::height (const KviTalListWidget * lb) const virtual
Reimplemented from KviTalListWidgetPixmap.
References KviTalListWidgetPixmap::pixmap().
const QString& KviImageDialogItem::imageId () inline
References m_szImageId.
Referenced by KviImageDialog::itemDoubleClicked().
bool KviImageDialogItem::isFolder () inline
References m_bIsFolder.
Referenced by KviImageDialog::itemDoubleClicked().
void KviImageDialogItem::paint (QPainter * p) virtual
Reimplemented from KviTalListWidgetPixmap.
References KviTalListWidgetItem::listWidget(), m_bIsFolder, KviTalListWidgetPixmap::pixmap(), KviTalListWidgetPixmap::pm, and t().
const QString& KviImageDialogItem::tipText () inline
References m_szTipText.
Referenced by KviImageDialog::tipRequest().
int KviImageDialogItem::width (const KviTalListWidget * lb) const virtual
Reimplemented from KviTalListWidgetPixmap.
References KviTalListWidgetPixmap::pixmap(), and w.
Member Data Documentation
bool KviImageDialogItem::m_bIsFolder
Referenced by isFolder(), and paint().
QString KviImageDialogItem::m_szImageId
Referenced by imageId().
QString KviImageDialogItem::m_szTipText
Referenced by tipText().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviImageDialog.h
src/kvirc/ui/KviImageDialog.cpp