KVIrc: KviInputEditor Class Reference
KviInputEditor Class Reference
Input editor class.
#include <KviInputEditor.h>
Classes
class EditCommand
Holds the command used in the {un,re}do operations.
Public Slots
void clear ()
Clears the input line.
void copyToClipboard ()
Copies the text to the system clipboard.
void copyToSelection (bool bDonNotCopyToClipboard=true)
Copies the text to the system clipboard.
void cut ()
Cuts the selection from the input line.
void iconPopupActivated (QAction *pAction)
Opens the icon popup with icon description.
void pasteClipboardWithConfirmation ()
Pastes the text to the system clipboard.
void pasteFile ()
Pastes a file to the buffer.
void pasteSelectionWithConfirmation ()
Pastes the text to the system clipboard.
void pasteSlow ()
Starts a slow paste in the buffer.
void redo ()
Redo the last undo-ed action.
void removeSelected ()
Removes the selected text.
void selectAll ()
Selects all text in the input line.
void stopPasteSlow ()
Stops a slow paste in the buffer.
void undo ()
Undo the last action.
Signals
void enterPressed ()
Called when the user press enter/return.
void escapePressed ()
Called when the user press escape.
Public Member Functions
void applyOptions (bool bRefreshCachedMetrics=true)
Applies the options and update.
void clearUndoStack ()
Clears the undo stack.
int heightHint () const
Returns the height of the editor.
void insertChar (QChar c)
Inserts a character at the current position.
void insertText (const QString &szTxt)
Inserts the text at the current position.
bool isReadOnly () const
Returns true if the input line is in read only state.
KviInputEditor (QWidget *pPar, KviWindow *pWnd, KviUserListView *pView=0)
Constructs the input editor object.
void setMaxBufferSize (int iSize)
Sets the maximum buffer size.
void setReadOnly (bool bReadOnly)
Sets the read only state for the input line.
void setText (const QString szText)
Sets the text in the input line.
QString text ()
Returns the text in the buffer.
QString textBeforeCursor ()
Returns the text before the cursor.
~KviInputEditor ()
Destroys the Input editor object.
Protected Member Functions
bool checkWordSpelling (const QString &szWord)
void completionEscapeUnsafeToken (QString &szToken)
virtual void dragEnterEvent (QDragEnterEvent *e)
virtual void drawContents (QPainter *)
virtual void dropEvent (QDropEvent *e)
void fillSpellCheckerCorrectionsPopup ()
KviInputEditorSpellCheckerBlock * findSpellCheckerBlockAtCursor (KviPointerList< KviInputEditorSpellCheckerBlock > &lBlocks)
virtual void focusInEvent (QFocusEvent *e)
virtual void focusOutEvent (QFocusEvent *e)
virtual void inputMethodEvent (QInputMethodEvent *e)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
void insertIconCode (const QString &szCode)
void installShortcuts ()
virtual void keyPressEvent (QKeyEvent *e)
virtual void keyReleaseEvent (QKeyEvent *e)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
void rebuildTextBlocks ()
void splitTextIntoSpellCheckerBlocks (const QString &szText, KviPointerList< KviInputEditorSpellCheckerBlock > &lBuffer)
virtual void timerEvent (QTimerEvent *e)
Protected Attributes
bool m_bCursorOn
bool m_bIMComposing
bool m_bLastCompletionFinished
bool m_bReadOnly
bool m_bSpSlowFlag
bool m_bUpdatesEnabled
int m_iCurHistoryIdx
int m_iCursorPosition
int m_iCursorTimer
int m_iCursorWidth
int m_iDragTimer
int m_iIMLength
int m_iIMSelectionBegin
int m_iIMSelectionLength
int m_iIMStart
int m_iLastCompletionCursorPosition
int m_iMaxBufferSize
int m_iSelectionAnchorChar
int m_iSelectionBegin
int m_iSelectionEnd
KviInputEditorPrivate * m_p
KviPointerList< QString > * m_pHistory
QMenu * m_pIconMenu
QWidget * m_pInputParent
KviWindow * m_pKviWindow
KviPointerList< EditCommand > * m_pRedoStack
The redo stack.
KviPointerList< EditCommand > * m_pUndoStack
The undo stack.
KviUserListView * m_pUserListView
QMenu m_SpellCheckerPopup
KviCString m_szAltKeyCode
QString m_szIMText
QString m_szLastCompletedNick
QString m_szLastCompletionBuffer
KviCString m_szSaveTextBuffer
QString m_szTextBuffer
Static Protected Attributes
static int g_iCachedHeight = 0
static int g_iInputFontCharWidth [256]
static int g_iInputInstances = 0
static QFontMetricsF * g_pLastFontMetrics = nullptr
Properties
int TransparencyCapable
Private Slots
void backspaceHit ()
Run when backspace key is pressed.
void copyInternal ()
Copies to clipboard.
void cutInternal ()
Cuts to clipboard.
void deleteHit ()
Run when delete key is pressed.
void deleteNextWord ()
Deletes next word.
void deletePreviousWord ()
Deletes previous word.
void dummy ()
Does nothing but grabs some keys combinations.
void endInternal ()
Moves the cursor at the end.
void endInternalSelection ()
Selects until the end.
void escapeHit ()
Run when escape key is pressed.
void historyNext ()
Moves forward in the command history and in the history popup.
void historyPrev ()
Moves backward in the command history and in the history popup.
void homeInternal ()
Moves the cursor at the beginning.
void homeInternalSelection ()
Selects until the beginning.
void insertBold ()
Inserts bold control character.
void insertColor ()
Inserts color control character.
void insertIcon ()
Inserts icon control character.
void insertPlainText ()
Inserts non-crypt (plain text) control character.
void insertReset ()
Inserts reset control character.
void insertReverse ()
Inserts reverse control character.
void insertUnderline ()
Inserts underline control character.
void nextChar ()
Moves to the next character.
void nextCharSelection ()
Selects up to the next character.
void nextLine ()
Scrolls the output window down one line.
void nextPage ()
Scrolls the output window down one page.
void nextWord ()
Moves to the end of the next word.
void nextWordSelection ()
Selects up to the end of the next word.
void openHistory ()
Opens the history popup.
void pasteInternal ()
Pastes clipboard contents.
void popupTextIconWindow ()
void previousChar ()
Moves to the previous character.
void previousCharSelection ()
Selects up to the previous character.
void previousLine ()
Scrolls the output window up one line.
void previousPage ()
Scrolls the output window up one page.
void previousWord ()
Moves to the beginning of the previous word.
void previousWordSelection ()
Selects up to the beginning of the previous word.
void redoInternal ()
Redoes last action.
void returnHit ()
Run when return/enter key is pressed.
void scrollToLastReadLine ()
Scrolls the ircview to the last read line.
void search ()
Opens the search window.
void selectAllInternal ()
Selects all.
void sendKvs ()
Sends the message assuming it's kvs code.
void sendPlain ()
Sends plain text, ignoring initial token starting with / (a command)
void showContextPopup (const QPoint &pos)
void showContextPopupHere ()
void showSpellCheckerCorrectionsPopup ()
void spellCheckerPopupCorrectionActionTriggered ()
void toggleCommandMode ()
Toggles the commandline's KVS/User-friendly mode.
void toggleMultiLineEditor ()
Toggles the multiline editor.
void undoInternal ()
Undoes last action.
void zoomDefault ()
Restore the ircview font (and its size)
void zoomIn ()
Increase the ircview font size.
void zoomOut ()
Decrease the ircview font size.
Private Member Functions
void addUndo (EditCommand *pCommand)
Inserts one action in the undo stack.
int charIndexFromXPosition (qreal fXPos)
Returns the current character from a given position.
void clearSelection ()
void completion (bool bShift)
Autocompletion function.
void end ()
Moves the cursor to the end of the input line.
void ensureCursorVisible ()
Makes sure that the cursor is visible.
QFontMetricsF * getLastFontMetrics (const QFont &font)
Returns the current input editor font metrics (globally shared)
void getWordBeforeCursor (QString &szBuffer, bool *bIsFirstWordInLine)
Gets the word before the cursor and puts it to the buffer.
void handleDragSelection ()
Handles the drag selection.
bool hasSelection ()
Returns true if the input line has focus.
void home ()
Moves the cursor to the start of the input line.
void internalCursorLeft (bool bShift)
Moves the cursor one character to the left.
void internalCursorRight (bool bShift)
Moves the cursor one character to the right.
bool isRedoAvailable () const
Returns true is there are some action in the redo stack.
bool isUndoAvailable () const
Returns true is there are some action in the undo stack.
void killDragTimer ()
Kills the drag timer.
void moveCursorTo (int iIdx, bool bRepaint=true)
Moves the cursor to the specified position.
void repaintWithCursorOn ()
Repaints the input line with the visible cursor.
int replaceSegment (int iStart, int iLength, const QString &szString)
Replace characters in the buffer.
void replaceWordBeforeCursor (const QString &szWord, const QString &szReplacement, bool bRepaint=true)
Replaces the word before the cursor.
void returnPressed (bool bRepaint=true)
Adds the text to the history.
void standardNickCompletion (bool bAddMask, QString &szWord, bool bFirstWordInLine, bool bInCommand)
Completes the nickname specified by szWord (inserts the completed text to the input line)
void standardNickCompletionInsertCompletedText (const QString &szReplacedWord, const QString &szCompletedText, bool bFirstWordInLine, bool bInCommand)
Internal helper for standardNickCompletion()
qreal xPositionFromCharIndex (int iChIdx)
Returns the current position from a given character.
Static Private Member Functions
static QChar getSubstituteChar (unsigned short uControlCode)
Gets the substitute character for control codes.
Friends
class KviTextIconWindow
class KviTopicWidget
Detailed Description
Input editor class.
Constructor & Destructor Documentation
KviInputEditor::KviInputEditor (QWidget * pPar, KviWindow * pWnd, KviUserListView * pView = 0)
Constructs the input editor object.
Parameters
pPar The parent widget
pWnd The KviWindow object
pView The userlist
Returns
KviInputEditor
References applyOptions(), KviInputEditorPrivate::bTextBlocksDirty, connect(), KviInputEditorPrivate::fXOffset, g_iInputInstances, iconPopupActivated(), installShortcuts(), KVI_INPUT_MARGIN, KVI_INPUT_MAX_BUFFER_SIZE, m_bCursorOn, m_bIMComposing, m_bReadOnly, m_bUpdatesEnabled, m_iCurHistoryIdx, m_iCursorPosition, m_iCursorTimer, m_iDragTimer, m_iIMLength, m_iIMSelectionBegin, m_iIMSelectionLength, m_iIMStart, m_iMaxBufferSize, m_iSelectionAnchorChar, m_iSelectionBegin, m_iSelectionEnd, m_p, m_pHistory, m_pIconMenu, m_pInputParent, m_pKviWindow, m_pRedoStack, m_pUndoStack, m_pUserListView, KviPointerList< T >::setAutoDelete(), and KviInputEditorPrivate::szFontElision.
KviInputEditor::~KviInputEditor ()
Destroys the Input editor object.
References g_iInputInstances, g_pLastFontMetrics, killDragTimer(), KviInputEditorPrivate::lTextBlocks, m_iCursorTimer, m_p, m_pHistory, m_pIconMenu, m_pRedoStack, and m_pUndoStack.
Member Function Documentation
void KviInputEditor::addUndo (EditCommand * pCommand) private
Inserts one action in the undo stack.
Parameters
pCommand The command representing the action
Returns
void
References KVI_INPUT_MAX_UNDO_SIZE, and m_pUndoStack.
Referenced by backspaceHit(), clear(), cut(), insertChar(), insertText(), removeSelected(), replaceSegment(), and setText().
void KviInputEditor::applyOptions (bool bRefreshCachedMetrics = true)
Applies the options and update.
Returns
void
References g_pLastFontMetrics, getLastFontMetrics(), KVI_OPTION_BOOL, KVI_OPTION_FONT, KVI_OPTION_UINT, KviOption_boolEnableCustomCursorWidth, KviOption_fontInput, KviOption_uintCustomCursorWidth, and m_iCursorWidth.
Referenced by KviInput::applyOptions(), and KviInputEditor().
void KviInputEditor::backspaceHit () private slot
Run when backspace key is pressed.
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), ensureCursorVisible(), hasSelection(), m_bReadOnly, m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, KviInputEditor::EditCommand::RemoveText, and repaintWithCursorOn().
Referenced by keyPressEvent().
int KviInputEditor::charIndexFromXPosition (qreal fXPos) private
Returns the current character from a given position.
Parameters
iXPos The position to grab
Returns
int
References KviInputEditorPrivate::bTextBlocksDirty, KviInputEditorPrivate::fFontElisionWidth, KviInputEditorTextBlock::fWidth, KviInputEditorPrivate::fXOffset, getLastFontMetrics(), KviInputEditorTextBlock::iLength, KVI_INPUT_MARGIN, KviInputEditorPrivate::lTextBlocks, m_p, rebuildTextBlocks(), KviInputEditorPrivate::szFontElision, and KviInputEditorTextBlock::szText.
Referenced by handleDragSelection(), mouseDoubleClickEvent(), and mousePressEvent().
bool KviInputEditor::checkWordSpelling (const QString & szWord) protected
References KviKvsVariant::asBoolean(), c, KviKvsScript::evaluate(), KviWindow::isChannel(), KviChannelWindow::isOn(), and m_pKviWindow.
Referenced by splitTextIntoSpellCheckerBlocks().
void KviInputEditor::clear () slot
Clears the input line.
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), home(), m_p, m_szTextBuffer, and KviInputEditor::EditCommand::RemoveText.
Referenced by showContextPopup(), and toggleMultiLineEditor().
void KviInputEditor::clearSelection () private
References KviInputEditorPrivate::bTextBlocksDirty, m_iSelectionBegin, m_iSelectionEnd, and m_p.
Referenced by backspaceHit(), clear(), cut(), deleteHit(), endInternal(), handleDragSelection(), historyNext(), historyPrev(), homeInternal(), insertChar(), internalCursorLeft(), internalCursorRight(), mousePressEvent(), removeSelected(), replaceWordBeforeCursor(), setText(), and standardNickCompletion().
void KviInputEditor::clearUndoStack ()
Clears the undo stack.
References m_pRedoStack, and m_pUndoStack.
Referenced by KviInput::inputEditorEnterPressed().
void KviInputEditor::completion (bool bShift) private
Autocompletion function.
To autocomplete, this function looks for a nickname, a directory, or a nickname.
Parameters
bShift Whether to complete with the mask of the nickname
Returns
void
References __tr2qs, KviConsoleWindow::completeChannel(), KviKvsKernel::completeCommand(), KviApplication::completeDirectory(), KviKvsKernel::completeFunction(), KviUserListView::completeNickBashLike(), KviConsoleWindow::completeServer(), completionEscapeUnsafeToken(), KviWindow::console(), KviPointerList< T >::count(), KviQString::equalCI(), KviQString::equalCIN(), KviPointerList< T >::first(), g_pApp, getWordBeforeCursor(), KviKvsKernel::instance(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_SYSTEMMESSAGE, KviOption_boolBashLikeNickCompletion, KviOption_boolUseNickCompletionPostfixForFirstWordOnly, KviOption_boolZshLikeNickCompletion, KviOption_stringNickCompletionPostfix, m_pKviWindow, m_pUserListView, m_szLastCompletedNick, m_szTextBuffer, KviPointerList< T >::next(), KviWindow::output(), KviWindow::outputNoFmt(), repaintWithCursorOn(), replaceWordBeforeCursor(), KviPointerList< T >::setAutoDelete(), standardNickCompletion(), and KviWindow::windowName().
Referenced by keyPressEvent().
void KviInputEditor::completionEscapeUnsafeToken (QString & szToken) protected
References KviQString::escapeKvs(), KviQString::EscapeSpace, and m_pInputParent.
Referenced by completion(), and standardNickCompletionInsertCompletedText().
void KviInputEditor::copyInternal () private slot
Copies to clipboard.
Returns
void
References copyToClipboard().
Referenced by installShortcuts().
void KviInputEditor::copyToClipboard () slot
Copies the text to the system clipboard.
Returns
void
References hasSelection(), m_iSelectionBegin, m_iSelectionEnd, m_szTextBuffer, and repaintWithCursorOn().
Referenced by copyInternal(), and showContextPopup().
void KviInputEditor::copyToSelection (bool bDonNotCopyToClipboard = true) slot
Copies the text to the system clipboard.
If the system supports the mouse clipboard, the text will be copied there
Parameters
bDonNotCopyToClipboard Whether to copy the text to the system clipboard
Returns
void
References hasSelection(), m_iSelectionBegin, m_iSelectionEnd, m_szTextBuffer, and repaintWithCursorOn().
Referenced by mouseReleaseEvent().
void KviInputEditor::cut () slot
Cuts the selection from the input line.
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), hasSelection(), m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, moveCursorTo(), KviInputEditor::EditCommand::RemoveText, and repaintWithCursorOn().
Referenced by cutInternal(), and showContextPopup().
void KviInputEditor::cutInternal () private slot
Cuts to clipboard.
Returns
void
References cut(), and m_bReadOnly.
Referenced by installShortcuts().
void KviInputEditor::deleteHit () private slot
Run when delete key is pressed.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), ensureCursorVisible(), hasSelection(), m_bReadOnly, m_iCursorPosition, m_p, m_szTextBuffer, removeSelected(), and repaintWithCursorOn().
Referenced by keyPressEvent().
void KviInputEditor::deleteNextWord () private slot
Deletes next word.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, hasSelection(), m_bReadOnly, m_iCursorPosition, m_p, m_szTextBuffer, removeSelected(), and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::deletePreviousWord () private slot
Deletes previous word.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, hasSelection(), m_bReadOnly, m_iCursorPosition, m_p, m_szTextBuffer, removeSelected(), and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::dragEnterEvent (QDragEnterEvent * e) protected virtual
void KviInputEditor::drawContents (QPainter * p) protected virtual
References KviInputEditorPrivate::bTextBlocksDirty, KviInputEditorTextBlock::fWidth, KviInputEditorPrivate::fXOffset, getLastFontMetrics(), KviInputEditorTextBlock::IsBold, KviInputEditorTextBlock::IsControlBlock, KviInputEditorTextBlock::IsSelected, KviInputEditorTextBlock::IsSpellingMistake, KviInputEditorTextBlock::IsUnderline, KVI_INPUT_DEF_BACK, KVI_INPUT_DEF_FORE, KVI_INPUT_MARGIN, KVI_INPUT_XTRAPADDING, KVI_OPTION_COLOR, KVI_OPTION_MIRCCOLOR, KviOption_colorInputBackground, KviOption_colorInputControl, KviOption_colorInputCursor, KviOption_colorInputForeground, KviOption_colorInputSelectionBackground, KviOption_colorInputSelectionForeground, KviInputEditorPrivate::lTextBlocks, m_bCursorOn, m_bIMComposing, m_iCursorPosition, m_iCursorWidth, m_iIMLength, m_iIMSelectionBegin, m_iIMSelectionLength, m_iIMStart, m_p, rebuildTextBlocks(), KviInputEditorTextBlock::szText, KviInputEditorTextBlock::uBackground, KviInputEditorTextBlock::uFlags, KviInputEditorTextBlock::uForeground, and xPositionFromCharIndex().
Referenced by paintEvent().
void KviInputEditor::dropEvent (QDropEvent * e) protected virtual
References KviQString::escapeKvs(), KviQString::EscapeSpace, insertText(), KVI_FILEEXTENSION_SCRIPT, m_pKviWindow, and KviKvsScript::run().
void KviInputEditor::dummy () private slot
Does nothing but grabs some keys combinations.
Warning
This is an hack. The keys combinations grabbed by this function write a non-printable chars which cause some troubles, eg duplication of chars opening/closing more times the multiline
Returns
void
Referenced by installShortcuts().
void KviInputEditor::end () private
Moves the cursor to the end of the input line.
Returns
void
References ensureCursorVisible(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by endInternal(), endInternalSelection(), historyNext(), historyPrev(), selectAll(), and setText().
void KviInputEditor::endInternal () private slot
Moves the cursor at the end.
Returns
void
References clearSelection(), and end().
Referenced by installShortcuts().
void KviInputEditor::endInternalSelection () private slot
Selects until the end.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, end(), m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, m_p, and m_szTextBuffer.
Referenced by installShortcuts().
void KviInputEditor::ensureCursorVisible () private
Makes sure that the cursor is visible.
References KviInputEditorPrivate::fXOffset, getLastFontMetrics(), KVI_INPUT_MARGIN, m_iCursorPosition, m_p, m_szTextBuffer, and xPositionFromCharIndex().
Referenced by backspaceHit(), deleteHit(), end(), handleDragSelection(), home(), insertChar(), internalCursorLeft(), internalCursorRight(), moveCursorTo(), and sendPlain().
void KviInputEditor::enterPressed () signal
Called when the user press enter/return.
Returns
void
Referenced by returnPressed().
void KviInputEditor::escapeHit () private slot
Run when escape key is pressed.
Returns
void
References escapePressed().
Referenced by installShortcuts().
void KviInputEditor::escapePressed () signal
Called when the user press escape.
Returns
void
Referenced by escapeHit().
void KviInputEditor::fillSpellCheckerCorrectionsPopup () protected
References __tr2qs, KviKvsArrayCast::array(), KviKvsVariant::asString(), KviKvsArray::at(), KviInputEditorSpellCheckerBlock::bSpellCheckable, KviKvsVariant::castToArray(), KviKvsScript::evaluate(), findSpellCheckerBlockAtCursor(), g_pInputPopup, i, m_SpellCheckerPopup, m_szTextBuffer, pArray, s, KviKvsArray::size(), spellCheckerPopupCorrectionActionTriggered(), splitTextIntoSpellCheckerBlocks(), KviInputEditorSpellCheckerBlock::szText, and v.
Referenced by showContextPopup(), and showSpellCheckerCorrectionsPopup().
KviInputEditorSpellCheckerBlock * KviInputEditor::findSpellCheckerBlockAtCursor (KviPointerList< KviInputEditorSpellCheckerBlock > & lBlocks) protected
References KviPointerList< T >::first(), m_iCursorPosition, and KviPointerList< T >::next().
Referenced by fillSpellCheckerCorrectionsPopup(), showContextPopup(), and spellCheckerPopupCorrectionActionTriggered().
void KviInputEditor::focusInEvent (QFocusEvent * e) protected virtual
References KVI_INPUT_BLINK_TIME, m_bCursorOn, and m_iCursorTimer.
void KviInputEditor::focusOutEvent (QFocusEvent * e) protected virtual
References m_bCursorOn, and m_iCursorTimer.
QFontMetricsF * KviInputEditor::getLastFontMetrics (const QFont & font) private
Returns the current input editor font metrics (globally shared)
Parameters
font The current input editor font
Returns
QFontMetricsF *
References KviInputEditorPrivate::fFontElisionWidth, g_iCachedHeight, g_pLastFontMetrics, h, KVI_INPUT_MARGIN, KVI_INPUT_XTRAPADDING, m_p, KviInputEditorPrivate::szFontElision, and w.
Referenced by applyOptions(), charIndexFromXPosition(), drawContents(), ensureCursorVisible(), rebuildTextBlocks(), and xPositionFromCharIndex().
QChar KviInputEditor::getSubstituteChar (unsigned short uControlCode) static private
Gets the substitute character for control codes.
Parameters
uControlCode The control code inserted
Returns
QChar
References KviControlCodes::Bold, KviControlCodes::CryptEscape, KviControlCodes::Icon, KviControlCodes::Reset, KviControlCodes::Reverse, and KviControlCodes::Underline.
Referenced by rebuildTextBlocks().
void KviInputEditor::getWordBeforeCursor (QString & szBuffer, bool * bIsFirstWordInLine) private
Gets the word before the cursor and puts it to the buffer.
Parameters
szBuffer The buffer where to put the word got
bIsFirstWordInLine Returns true if the word is the first
Returns
void
References m_iCursorPosition, and m_szTextBuffer.
Referenced by completion(), and standardNickCompletion().
void KviInputEditor::handleDragSelection () private
Handles the drag selection.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, charIndexFromXPosition(), clearSelection(), ensureCursorVisible(), m_iCursorPosition, m_iSelectionAnchorChar, m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, and repaintWithCursorOn().
Referenced by timerEvent().
bool KviInputEditor::hasSelection () private
Returns true if the input line has focus.
Returns
bool
References m_iSelectionBegin, and m_iSelectionEnd.
Referenced by backspaceHit(), copyToClipboard(), copyToSelection(), cut(), deleteHit(), deleteNextWord(), deletePreviousWord(), mouseReleaseEvent(), removeSelected(), and showContextPopup().
int KviInputEditor::heightHint () const
Returns the height of the editor.
Returns
int
References g_iCachedHeight.
Referenced by KviInput::heightHint(), and showContextPopupHere().
void KviInputEditor::historyNext () private slot
Moves forward in the command history and in the history popup.
Returns
void
References KviPointerList< T >::at(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), KviPointerList< T >::count(), end(), home(), KVI_OPTION_BOOL, KviOption_boolInputHistoryCursorAtEnd, m_bReadOnly, m_iCurHistoryIdx, m_p, m_pHistory, m_szSaveTextBuffer, and m_szTextBuffer.
Referenced by installShortcuts().
void KviInputEditor::historyPrev () private slot
Moves backward in the command history and in the history popup.
Returns
void
References KviPointerList< T >::at(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), KviPointerList< T >::count(), end(), home(), KVI_OPTION_BOOL, KviOption_boolInputHistoryCursorAtEnd, m_bReadOnly, m_iCurHistoryIdx, m_p, m_pHistory, m_szSaveTextBuffer, and m_szTextBuffer.
Referenced by installShortcuts().
void KviInputEditor::home () private
Moves the cursor to the start of the input line.
Returns
void
References ensureCursorVisible(), m_iCursorPosition, and repaintWithCursorOn().
Referenced by clear(), historyNext(), historyPrev(), homeInternal(), homeInternalSelection(), and KviTopicWidget::switchMode().
void KviInputEditor::homeInternal () private slot
Moves the cursor at the beginning.
Returns
void
References clearSelection(), home(), and m_iCursorPosition.
Referenced by installShortcuts().
void KviInputEditor::homeInternalSelection () private slot
Selects until the beginning.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, home(), m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, and m_p.
Referenced by installShortcuts().
void KviInputEditor::iconPopupActivated (QAction * pAction) slot
Opens the icon popup with icon description.
Parameters
iId The id of the icon
Returns
void
References KviControlCodes::Icon, insertText(), and m_bReadOnly.
Referenced by KviInputEditor().
void KviInputEditor::inputMethodEvent (QInputMethodEvent * e) protected virtual
References m_bIMComposing, m_bReadOnly, m_bUpdatesEnabled, m_iCursorPosition, m_iIMLength, m_iIMSelectionBegin, m_iIMSelectionLength, m_iIMStart, moveCursorTo(), removeSelected(), repaintWithCursorOn(), and replaceSegment().
virtual QVariant KviInputEditor::inputMethodQuery (Qt::InputMethodQuery query) const protected virtual
void KviInputEditor::insertBold () private slot
Inserts bold control character.
Returns
void
References KviControlCodes::Bold, insertChar(), and m_bReadOnly.
Referenced by installShortcuts().
void KviInputEditor::insertChar (QChar c)
Inserts a character at the current position.
Parameters
c The character to insert
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), ensureCursorVisible(), KviInputEditor::EditCommand::InsertText, m_bUpdatesEnabled, m_iCursorPosition, m_iMaxBufferSize, m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, removeSelected(), and repaintWithCursorOn().
Referenced by insertBold(), KviInput::insertChar(), insertColor(), insertIcon(), insertIconCode(), insertPlainText(), insertReset(), insertReverse(), insertUnderline(), and keyReleaseEvent().
void KviInputEditor::insertColor () private slot
Inserts color control character.
Returns
void
References insertChar(), m_bReadOnly, m_iCursorPosition, KviColorWindow::popup(), and xPositionFromCharIndex().
Referenced by installShortcuts().
void KviInputEditor::insertIcon () private slot
Inserts icon control character.
Returns
void
References KviControlCodes::Icon, insertChar(), m_bReadOnly, and popupTextIconWindow().
Referenced by installShortcuts().
void KviInputEditor::insertIconCode (const QString & szCode) protected
References KviControlCodes::Icon, insertChar(), insertText(), m_iCursorPosition, and m_szTextBuffer.
void KviInputEditor::insertPlainText () private slot
Inserts non-crypt (plain text) control character.
Returns
void
References KviControlCodes::CryptEscape, insertChar(), and m_bReadOnly.
Referenced by installShortcuts().
void KviInputEditor::insertReset () private slot
Inserts reset control character.
Returns
void
References insertChar(), m_bReadOnly, and KviControlCodes::Reset.
Referenced by installShortcuts().
void KviInputEditor::insertReverse () private slot
Inserts reverse control character.
Returns
void
References insertChar(), m_bReadOnly, and KviControlCodes::Reverse.
Referenced by installShortcuts().
void KviInputEditor::insertText (const QString & szTxt)
Inserts the text at the current position.
Parameters
szTxt The text to insert
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, KviInputEditor::EditCommand::InsertText, KVI_OPTION_UINT, KviOption_uintSpacesToExpandTabulationInput, m_bUpdatesEnabled, m_iCursorPosition, m_iMaxBufferSize, m_p, m_szTextBuffer, moveCursorTo(), removeSelected(), and returnPressed().
Referenced by dropEvent(), iconPopupActivated(), insertIconCode(), KviTopicWidget::insertText(), KviInput::insertText(), keyPressEvent(), pasteClipboardWithConfirmation(), pasteSelectionWithConfirmation(), and spellCheckerPopupCorrectionActionTriggered().
void KviInputEditor::insertUnderline () private slot
Inserts underline control character.
Returns
void
References insertChar(), m_bReadOnly, and KviControlCodes::Underline.
Referenced by installShortcuts().
void KviInputEditor::installShortcuts () protected
References copyInternal(), KviShortcut::create(), cutInternal(), deleteNextWord(), deletePreviousWord(), dummy(), endInternal(), endInternalSelection(), escapeHit(), historyNext(), historyPrev(), homeInternal(), homeInternalSelection(), insertBold(), insertColor(), insertIcon(), insertPlainText(), insertReset(), insertReverse(), insertUnderline(), KVI_SHORTCUTS_INPUT_BOLD, KVI_SHORTCUTS_INPUT_COLOR, KVI_SHORTCUTS_INPUT_COMMANDLINE, KVI_SHORTCUTS_INPUT_COPY, KVI_SHORTCUTS_INPUT_CORRECT_SPELLING, KVI_SHORTCUTS_INPUT_CUT, KVI_SHORTCUTS_INPUT_DELETE_NEXT_WORD, KVI_SHORTCUTS_INPUT_DELETE_PREV_WORD, KVI_SHORTCUTS_INPUT_DUMMY, KVI_SHORTCUTS_INPUT_END, KVI_SHORTCUTS_INPUT_END_SELECT, KVI_SHORTCUTS_INPUT_ESCAPE, KVI_SHORTCUTS_INPUT_HISTORY, KVI_SHORTCUTS_INPUT_HISTORY_NEXT, KVI_SHORTCUTS_INPUT_HISTORY_PREV, KVI_SHORTCUTS_INPUT_HOME, KVI_SHORTCUTS_INPUT_HOME_SELECT, KVI_SHORTCUTS_INPUT_ICON, KVI_SHORTCUTS_INPUT_MENU, KVI_SHORTCUTS_INPUT_NEXT_CHAR, KVI_SHORTCUTS_INPUT_NEXT_CHAR_SELECT, KVI_SHORTCUTS_INPUT_NEXT_WORD, KVI_SHORTCUTS_INPUT_NEXT_WORD_SELECT, KVI_SHORTCUTS_INPUT_PASTE, KVI_SHORTCUTS_INPUT_PLAINTEXT, KVI_SHORTCUTS_INPUT_PREV_CHAR, KVI_SHORTCUTS_INPUT_PREV_CHAR_SELECT, KVI_SHORTCUTS_INPUT_PREV_WORD, KVI_SHORTCUTS_INPUT_PREV_WORD_SELECT, KVI_SHORTCUTS_INPUT_REDO, KVI_SHORTCUTS_INPUT_RESET, KVI_SHORTCUTS_INPUT_REVERSE, KVI_SHORTCUTS_INPUT_SELECT_ALL, KVI_SHORTCUTS_INPUT_SEND_PLAIN, KVI_SHORTCUTS_INPUT_SEND_PLAIN_2, KVI_SHORTCUTS_INPUT_UNDERLINE, KVI_SHORTCUTS_INPUT_UNDO, KVI_SHORTCUTS_WIN_NEXT_LINE, KVI_SHORTCUTS_WIN_NEXT_PAGE, KVI_SHORTCUTS_WIN_PREV_LINE, KVI_SHORTCUTS_WIN_PREV_PAGE, KVI_SHORTCUTS_WIN_SCROLL_TO_LAST_READ_LINE, KVI_SHORTCUTS_WIN_SEARCH, KVI_SHORTCUTS_WIN_ZOOM_DEFAULT, KVI_SHORTCUTS_WIN_ZOOM_IN, KVI_SHORTCUTS_WIN_ZOOM_OUT, nextChar(), nextCharSelection(), nextLine(), nextPage(), nextWord(), nextWordSelection(), openHistory(), pasteInternal(), previousChar(), previousCharSelection(), previousLine(), previousPage(), previousWord(), previousWordSelection(), redoInternal(), scrollToLastReadLine(), search(), selectAllInternal(), sendPlain(), showContextPopupHere(), showSpellCheckerCorrectionsPopup(), toggleCommandMode(), undoInternal(), zoomDefault(), zoomIn(), and zoomOut().
Referenced by KviInputEditor().
void KviInputEditor::internalCursorLeft (bool bShift) private
Moves the cursor one character to the left.
Parameters
bShift Whether to shift the selection
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), ensureCursorVisible(), m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, and m_p.
Referenced by previousChar(), previousCharSelection(), previousWord(), and previousWordSelection().
void KviInputEditor::internalCursorRight (bool bShift) private
Moves the cursor one character to the right.
Parameters
bShift Whether to shift the selection
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), ensureCursorVisible(), m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, m_p, and m_szTextBuffer.
Referenced by nextChar(), nextCharSelection(), nextWord(), and nextWordSelection().
bool KviInputEditor::isReadOnly () const inline
Returns true if the input line is in read only state.
Returns
bool
Referenced by KviTopicWidget::acceptClicked().
bool KviInputEditor::isRedoAvailable () const inline private
Returns true is there are some action in the redo stack.
Returns
bool
Referenced by redo(), and showContextPopup().
bool KviInputEditor::isUndoAvailable () const inline private
Returns true is there are some action in the undo stack.
Returns
bool
Referenced by showContextPopup(), and undo().
void KviInputEditor::keyPressEvent (QKeyEvent * e) protected virtual
References backspaceHit(), completion(), deleteHit(), insertText(), m_bIMComposing, m_bLastCompletionFinished, m_bReadOnly, m_szAltKeyCode, and returnHit().
void KviInputEditor::keyReleaseEvent (QKeyEvent * e) protected virtual
References KviCString::hasData(), insertChar(), m_szAltKeyCode, and KviCString::toUShort().
void KviInputEditor::killDragTimer () private
Kills the drag timer.
Returns
void
References m_iDragTimer.
Referenced by mouseDoubleClickEvent(), mousePressEvent(), mouseReleaseEvent(), and ~KviInputEditor().
void KviInputEditor::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
References KviInputEditorPrivate::bTextBlocksDirty, charIndexFromXPosition(), killDragTimer(), m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, and moveCursorTo().
void KviInputEditor::mousePressEvent (QMouseEvent * e) protected virtual
References charIndexFromXPosition(), clearSelection(), killDragTimer(), KVI_INPUT_DRAG_TIMEOUT, m_iCursorPosition, m_iDragTimer, m_iSelectionAnchorChar, pasteSelectionWithConfirmation(), repaintWithCursorOn(), and showContextPopup().
void KviInputEditor::mouseReleaseEvent (QMouseEvent * e) protected virtual
References copyToSelection(), hasSelection(), killDragTimer(), m_iDragTimer, and m_iSelectionAnchorChar.
void KviInputEditor::moveCursorTo (int iIdx, bool bRepaint = true) private
Moves the cursor to the specified position.
Parameters
iIdx The index of the character to move the cursor to
bRepaint Whether to repaint the input line
Returns
void
References ensureCursorVisible(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by cut(), inputMethodEvent(), insertText(), mouseDoubleClickEvent(), redo(), removeSelected(), replaceWordBeforeCursor(), and undo().
void KviInputEditor::nextChar () private slot
Moves to the next character.
Returns
void
References internalCursorRight(), and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::nextCharSelection () private slot
Selects up to the next character.
Returns
void
References internalCursorRight(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::nextLine () private slot
Scrolls the output window down one line.
Returns
void
References m_pKviWindow, KviIrcView::nextLine(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::nextPage () private slot
Scrolls the output window down one page.
Returns
void
References m_pKviWindow, KviIrcView::nextPage(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::nextWord () private slot
Moves to the end of the next word.
Returns
void
References internalCursorRight(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::nextWordSelection () private slot
Selects up to the end of the next word.
Returns
void
References internalCursorRight(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::openHistory () private slot
Opens the history popup.
Returns
void
References KVI_OPTION_BOOL, KviOption_boolEnableInputHistory, and m_pInputParent.
Referenced by installShortcuts().
void KviInputEditor::paintEvent (QPaintEvent * e) protected virtual
References drawContents(), KviPixmapUtils::drawPixmapWithPainter(), g_pApp, g_pMainWindow, KviWindow::isDocked(), KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_PIXMAP, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_colorInputBackground, KviOption_pixmapInputBackground, KviOption_uintGlobalTransparencyChildFadeFactor, KviOption_uintInputPixmapAlign, m_pKviWindow, p, r, and KviApplication::supportsCompositing().
void KviInputEditor::pasteClipboardWithConfirmation () slot
Pastes the text to the system clipboard.
Returns
void
References KviWindow::id(), insertText(), KviEvent_OnInputBarPaste, KVS_TRIGGER_EVENT_2_HALTED, m_pInputParent, and m_pKviWindow.
Referenced by pasteInternal(), and showContextPopup().
void KviInputEditor::pasteFile () slot
Pastes a file to the buffer.
Returns
void
References KviQString::escapeKvs(), KviQString::EscapeSpace, g_pActiveWindow, m_bSpSlowFlag, and KviKvsScript::run().
Referenced by showContextPopup().
void KviInputEditor::pasteInternal () private slot
Pastes clipboard contents.
Returns
void
References m_bReadOnly, and pasteClipboardWithConfirmation().
Referenced by installShortcuts().
void KviInputEditor::pasteSelectionWithConfirmation () slot
Pastes the text to the system clipboard.
If the system supports the mouse clipboard, the text will be copied there
Returns
void
References KviWindow::id(), insertText(), KviEvent_OnInputBarPaste, KVS_TRIGGER_EVENT_2_HALTED, m_pInputParent, and m_pKviWindow.
Referenced by mousePressEvent().
void KviInputEditor::pasteSlow () slot
Starts a slow paste in the buffer.
Returns
void
References g_pActiveWindow, m_bSpSlowFlag, and KviKvsScript::run().
Referenced by showContextPopup().
void KviInputEditor::popupTextIconWindow () private slot
Shows the text icon window at cursor position
References KVI_TEXTICON_WIN_HEIGHT, KviTextIconWindow, m_bReadOnly, m_iCursorPosition, KviTextIconWindow::popup(), and xPositionFromCharIndex().
Referenced by insertIcon(), and showContextPopup().
void KviInputEditor::previousChar () private slot
Moves to the previous character.
Returns
void
References internalCursorLeft(), and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::previousCharSelection () private slot
Selects up to the previous character.
Returns
void
References internalCursorLeft(), m_iCursorPosition, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::previousLine () private slot
Scrolls the output window up one line.
Returns
void
References m_pKviWindow, KviIrcView::prevLine(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::previousPage () private slot
Scrolls the output window up one page.
Returns
void
References m_pKviWindow, KviIrcView::prevPage(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::previousWord () private slot
Moves to the beginning of the previous word.
Returns
void
References internalCursorLeft(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::previousWordSelection () private slot
Selects up to the beginning of the previous word.
Returns
void
References internalCursorLeft(), m_iCursorPosition, m_szTextBuffer, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::rebuildTextBlocks () protected
References ADD_SPELLCHECKER_BLOCK, KviControlCodes::Bold, KviInputEditorPrivate::bTextBlocksDirty, c, KviControlCodes::CryptEscape, e, KviPointerList< T >::first(), KviInputEditorTextBlock::fWidth, getLastFontMetrics(), getSubstituteChar(), KviControlCodes::getUnicodeColorBytes(), KviControlCodes::Icon, KviInputEditorTextBlock::iLength, KviInputEditorTextBlock::IsBold, KviInputEditorTextBlock::IsControlBlock, KviPointerList< T >::isEmpty(), KviInputEditorTextBlock::IsSelected, KviInputEditorTextBlock::IsSpellingMistake, KviInputEditorTextBlock::IsUnderline, KVI_INPUT_DEF_BACK, KVI_INPUT_DEF_FORE, KviInputEditorPrivate::lTextBlocks, m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, KviPointerList< T >::next(), KviControlCodes::NoChange, NOT_CONTROL_CHAR, p, KviControlCodes::Reset, KviControlCodes::Reverse, KviPointerList< T >::setAutoDelete(), splitTextIntoSpellCheckerBlocks(), KviInputEditorTextBlock::szText, KviInputEditorTextBlock::uBackground, KviInputEditorTextBlock::uFlags, KviInputEditorTextBlock::uForeground, and KviControlCodes::Underline.
Referenced by charIndexFromXPosition(), drawContents(), and xPositionFromCharIndex().
void KviInputEditor::redo () slot
Redo the last undo-ed action.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, KviInputEditor::EditCommand::InsertText, isRedoAvailable(), KVI_INPUT_MAX_UNDO_SIZE, m_iSelectionBegin, m_iSelectionEnd, m_p, m_pRedoStack, m_pUndoStack, m_szTextBuffer, moveCursorTo(), KviInputEditor::EditCommand::RemoveText, KviInputEditor::EditCommand::startPosition(), KviInputEditor::EditCommand::text(), and KviInputEditor::EditCommand::type().
Referenced by redoInternal(), and showContextPopup().
void KviInputEditor::redoInternal () private slot
Redoes last action.
Returns
void
References m_bReadOnly, and redo().
Referenced by installShortcuts().
void KviInputEditor::removeSelected () slot
Removes the selected text.
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), hasSelection(), m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, moveCursorTo(), KviInputEditor::EditCommand::RemoveText, and repaintWithCursorOn().
Referenced by deleteHit(), deleteNextWord(), deletePreviousWord(), inputMethodEvent(), insertChar(), and insertText().
void KviInputEditor::repaintWithCursorOn () private
Repaints the input line with the visible cursor.
Returns
void
References m_bCursorOn, and m_bUpdatesEnabled.
Referenced by backspaceHit(), completion(), copyToClipboard(), copyToSelection(), cut(), deleteHit(), deleteNextWord(), deletePreviousWord(), end(), handleDragSelection(), home(), inputMethodEvent(), insertChar(), mousePressEvent(), moveCursorTo(), nextChar(), nextCharSelection(), nextWord(), nextWordSelection(), previousChar(), previousCharSelection(), previousWord(), previousWordSelection(), removeSelected(), replaceSegment(), replaceWordBeforeCursor(), selectAllInternal(), sendKvs(), and sendPlain().
int KviInputEditor::replaceSegment (int iStart, int iLength, const QString & szString) private
Replace characters in the buffer.
Returns the length of the text inserted (different from text.length() only if the buffer was truncated.
Parameters
iStart The starting character
iLength The length of the string to replace
szString The string to replace with
Returns
int
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, KviInputEditor::EditCommand::InsertText, m_iMaxBufferSize, m_p, m_szTextBuffer, and repaintWithCursorOn().
Referenced by inputMethodEvent().
void KviInputEditor::replaceWordBeforeCursor (const QString & szWord, const QString & szReplacement, bool bRepaint = true) private
Replaces the word before the cursor.
Parameters
szWord The word to replace
szReplacement The new word to use
bRepaint Whether to repain the input line
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), m_iCursorPosition, m_iMaxBufferSize, m_p, m_szTextBuffer, moveCursorTo(), and repaintWithCursorOn().
Referenced by completion(), and standardNickCompletionInsertCompletedText().
void KviInputEditor::returnHit () private slot
Run when return/enter key is pressed.
Returns
void
References returnPressed().
Referenced by keyPressEvent().
void KviInputEditor::returnPressed (bool bRepaint = true) private
Adds the text to the history.
Triggered when the user press return
Parameters
bRepaint Whether to repain the input line
Returns
void
References KviInputHistory::add(), KviPointerList< T >::count(), enterPressed(), KviPointerList< T >::insert(), KviInputHistory::instance(), KVI_ASSERT, KVI_INPUT_MAX_LOCAL_HISTORY_ENTRIES, m_iCurHistoryIdx, m_pHistory, m_pInputParent, m_szTextBuffer, and KviPointerList< T >::removeLast().
Referenced by insertText(), and returnHit().
void KviInputEditor::scrollToLastReadLine () private slot
Scrolls the ircview to the last read line.
Returns
void
References KviIrcView::hasLineMark(), m_pKviWindow, KviIrcView::scrollToMarker(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::search () private slot
Opens the search window.
Returns
void
References m_pKviWindow, KviIrcView::toggleToolWidget(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::selectAll () slot
Selects all text in the input line.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, end(), m_iSelectionBegin, m_iSelectionEnd, m_p, and m_szTextBuffer.
Referenced by showContextPopup().
void KviInputEditor::selectAllInternal () private slot
Selects all.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, and repaintWithCursorOn().
Referenced by installShortcuts().
void KviInputEditor::sendKvs () private slot
Sends the message assuming it's kvs code.
Returns
void
References KviInputHistory::add(), KviInputEditorPrivate::bTextBlocksDirty, KviPointerList< T >::count(), KviPointerList< T >::insert(), KviInputHistory::instance(), KVI_ASSERT, KVI_INPUT_MAX_LOCAL_HISTORY_ENTRIES, m_iCurHistoryIdx, m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, m_p, m_pHistory, m_pInputParent, m_pKviWindow, m_szTextBuffer, KviUserInput::parseCommand(), KviPointerList< T >::removeLast(), repaintWithCursorOn(), and szBuffer.
void KviInputEditor::sendPlain () private slot
Sends plain text, ignoring initial token starting with / (a command)
Returns
void
References KviInputHistory::add(), KviInputEditorPrivate::bTextBlocksDirty, KviPointerList< T >::count(), ensureCursorVisible(), KviPointerList< T >::insert(), KviInputHistory::instance(), KVI_ASSERT, KVI_INPUT_MAX_LOCAL_HISTORY_ENTRIES, m_iCurHistoryIdx, m_iCursorPosition, m_iSelectionBegin, m_iSelectionEnd, m_p, m_pHistory, m_pInputParent, m_pKviWindow, m_szTextBuffer, KviUserInput::parseNonCommand(), KviPointerList< T >::removeLast(), repaintWithCursorOn(), and szBuffer.
Referenced by installShortcuts().
void KviInputEditor::setMaxBufferSize (int iSize) inline
Sets the maximum buffer size.
Parameters
iSize The size of the buffer to set
Returns
void
Referenced by KviTopicWidget::switchMode().
void KviInputEditor::setReadOnly (bool bReadOnly) inline
Sets the read only state for the input line.
Parameters
bReadOnly Whether to set the read only state
Returns
void
Referenced by KviTopicWidget::switchMode().
void KviInputEditor::setText (const QString szText)
Sets the text in the input line.
Parameters
szText The text to set
Returns
void
References addUndo(), KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), end(), m_iMaxBufferSize, m_p, m_szTextBuffer, and KviInputEditor::EditCommand::RemoveText.
Referenced by KviTopicWidget::complete(), KviInput::inputEditorEnterPressed(), KviInput::multiLineEditorButtonToggled(), KviInput::setText(), and KviTopicWidget::switchMode().
void KviInputEditor::showContextPopup (const QPoint & pos) private slot
Shows the contextual popup menu at the global position pos
References __tr2qs, ACCEL_KEY, KviInputEditorSpellCheckerBlock::bCorrect, KviIconManager::BigGrin, KviInputEditorSpellCheckerBlock::bSpellCheckable, KviWindow::Channel, clear(), copyToClipboard(), cut(), KviWindow::DccChat, END_TABLE_BOLD_ROW, fillSpellCheckerCorrectionsPopup(), findSpellCheckerBlockAtCursor(), g_pApp, g_pIconManager, g_pInputPopup, KviIconManager::getSmallIcon(), hasSelection(), i, isRedoAvailable(), isUndoAvailable(), m_bReadOnly, m_bSpSlowFlag, m_pKviWindow, m_SpellCheckerPopup, m_szTextBuffer, pasteClipboardWithConfirmation(), pasteFile(), pasteSlow(), popupTextIconWindow(), KviWindow::Query, redo(), selectAll(), splitTextIntoSpellCheckerBlocks(), START_TABLE_BOLD_ROW, stopPasteSlow(), KviInputEditorSpellCheckerBlock::szText, KviWindow::type(), undo(), V, X, Y, and Z.
Referenced by mousePressEvent(), and showContextPopupHere().
void KviInputEditor::showContextPopupHere () private slot
Shows the context popup menu at the current cursor position
References heightHint(), KVI_INPUT_MARGIN, KVI_INPUT_XTRAPADDING, m_iCursorPosition, showContextPopup(), and xPositionFromCharIndex().
Referenced by installShortcuts().
void KviInputEditor::showSpellCheckerCorrectionsPopup () private slot
Show the spell checker corrections popup.
References fillSpellCheckerCorrectionsPopup(), m_iCursorPosition, m_SpellCheckerPopup, and xPositionFromCharIndex().
Referenced by installShortcuts().
void KviInputEditor::spellCheckerPopupCorrectionActionTriggered () private slot
Handles spellchecker suggestions popup
References KviInputEditorPrivate::bTextBlocksDirty, findSpellCheckerBlockAtCursor(), KviInputEditorSpellCheckerBlock::iLength, insertText(), KviInputEditorSpellCheckerBlock::iStart, m_iSelectionBegin, m_iSelectionEnd, m_p, m_szTextBuffer, and splitTextIntoSpellCheckerBlocks().
Referenced by fillSpellCheckerCorrectionsPopup().
void KviInputEditor::splitTextIntoSpellCheckerBlocks (const QString & szText, KviPointerList< KviInputEditorSpellCheckerBlock > & lBuffer) protected
References ADD_SPELLCHECKER_BLOCK, checkWordSpelling(), e, and p.
Referenced by fillSpellCheckerCorrectionsPopup(), rebuildTextBlocks(), showContextPopup(), and spellCheckerPopupCorrectionActionTriggered().
void KviInputEditor::standardNickCompletion (bool bAddMask, QString & szWord, bool bFirstWordInLine, bool bInCommand) private
Completes the nickname specified by szWord (inserts the completed text to the input line)
Parameters
bAddMask Whether to complete with the mask of the nickname
szWord The nickname to complete
bFirstWordInLine Whether the word to complete is the first word in the text line (so the suffix from option panel is added)
bInCommand Whether the completion happens inside a kvs command (and thus the completed word should be kvs-escaped)
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, clearSelection(), KviUserListView::completeNickStandard(), getWordBeforeCursor(), m_bLastCompletionFinished, m_iCursorPosition, m_iLastCompletionCursorPosition, m_p, m_pUserListView, m_szLastCompletedNick, m_szLastCompletionBuffer, m_szTextBuffer, standardNickCompletionInsertCompletedText(), and szBuffer.
Referenced by completion().
void KviInputEditor::standardNickCompletionInsertCompletedText (const QString & szReplacedWord, const QString & szCompletedText, bool bFirstWordInLine, bool bInCommand) private
Internal helper for standardNickCompletion()
Parameters
szReplacedWord The word replaced before the cursor
szCompletedText The text to be completed
bFirstWordInLine Whether the word to complete is the first word in the text line (so the suffix from option panel is added)
bInCommand Whether the completion happens inside a kvs command (and thus the completed word should be kvs-escaped)
Returns
void
References completionEscapeUnsafeToken(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseNickCompletionPostfixForFirstWordOnly, KviOption_stringNickCompletionPostfix, replaceWordBeforeCursor(), and szBuffer.
Referenced by standardNickCompletion().
void KviInputEditor::stopPasteSlow () slot
Stops a slow paste in the buffer.
Returns
void
References g_pActiveWindow, m_bSpSlowFlag, and KviKvsScript::run().
Referenced by showContextPopup().
QString KviInputEditor::text () inline
Returns the text in the buffer.
Returns
QString
Referenced by KviTopicWidget::acceptClicked(), KviInput::inputEditorEnterPressed(), KviInput::multiLineEditorButtonToggled(), KviInput::multiLinePaste(), and KviInput::text().
QString KviInputEditor::textBeforeCursor ()
Returns the text before the cursor.
References m_iCursorPosition, and m_szTextBuffer.
void KviInputEditor::timerEvent (QTimerEvent * e) protected virtual
References handleDragSelection(), m_bCursorOn, and m_iCursorTimer.
void KviInputEditor::toggleCommandMode () private slot
Toggles the commandline's KVS/User-friendly mode.
Returns
void
References m_pInputParent.
Referenced by installShortcuts().
void KviInputEditor::toggleMultiLineEditor () private slot
Toggles the multiline editor.
Returns
void
References clear(), m_pInputParent, and m_szTextBuffer.
void KviInputEditor::undo () slot
Undo the last action.
Returns
void
References KviInputEditorPrivate::bTextBlocksDirty, KviInputEditor::EditCommand::InsertText, isUndoAvailable(), KVI_INPUT_MAX_UNDO_SIZE, m_iSelectionBegin, m_iSelectionEnd, m_p, m_pRedoStack, m_pUndoStack, m_szTextBuffer, moveCursorTo(), KviInputEditor::EditCommand::RemoveText, KviInputEditor::EditCommand::startPosition(), KviInputEditor::EditCommand::text(), and KviInputEditor::EditCommand::type().
Referenced by showContextPopup(), and undoInternal().
void KviInputEditor::undoInternal () private slot
Undoes last action.
Returns
void
References m_bReadOnly, and undo().
Referenced by installShortcuts().
qreal KviInputEditor::xPositionFromCharIndex (int iChIdx) private
Returns the current position from a given character.
Parameters
iChIdx Th index of the character
Returns
int
References KviInputEditorPrivate::bTextBlocksDirty, KviInputEditorTextBlock::fWidth, KviInputEditorPrivate::fXOffset, getLastFontMetrics(), KviInputEditorTextBlock::iLength, KVI_INPUT_MARGIN, KviInputEditorPrivate::lTextBlocks, m_p, rebuildTextBlocks(), and KviInputEditorTextBlock::szText.
Referenced by drawContents(), ensureCursorVisible(), insertColor(), popupTextIconWindow(), showContextPopupHere(), and showSpellCheckerCorrectionsPopup().
void KviInputEditor::zoomDefault () private slot
Restore the ircview font (and its size)
Returns
void
References m_pKviWindow, KviIrcView::resetDefaultFont(), and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::zoomIn () private slot
Increase the ircview font size.
Returns
void
References KviIrcView::increaseFontSize(), m_pKviWindow, and KviWindow::view().
Referenced by installShortcuts().
void KviInputEditor::zoomOut () private slot
Decrease the ircview font size.
Returns
void
References KviIrcView::decreaseFontSize(), m_pKviWindow, and KviWindow::view().
Referenced by installShortcuts().
Friends And Related Function Documentation
friend class KviTextIconWindow friend
Referenced by popupTextIconWindow().
friend class KviTopicWidget friend
Member Data Documentation
int KviInputEditor::g_iCachedHeight = 0 static protected
Referenced by getLastFontMetrics(), and heightHint().
int KviInputEditor::g_iInputFontCharWidth[256] static protected
int KviInputEditor::g_iInputInstances = 0 static protected
Referenced by KviInputEditor(), and ~KviInputEditor().
QFontMetricsF * KviInputEditor::g_pLastFontMetrics = nullptr static protected
Referenced by applyOptions(), getLastFontMetrics(), and ~KviInputEditor().
bool KviInputEditor::m_bCursorOn protected
Referenced by drawContents(), focusInEvent(), focusOutEvent(), KviInputEditor(), repaintWithCursorOn(), and timerEvent().
bool KviInputEditor::m_bIMComposing protected
Referenced by drawContents(), inputMethodEvent(), keyPressEvent(), and KviInputEditor().
bool KviInputEditor::m_bLastCompletionFinished protected
Referenced by keyPressEvent(), and standardNickCompletion().
bool KviInputEditor::m_bReadOnly protected
Referenced by backspaceHit(), cutInternal(), deleteHit(), deleteNextWord(), deletePreviousWord(), historyNext(), historyPrev(), iconPopupActivated(), inputMethodEvent(), insertBold(), insertColor(), insertIcon(), insertPlainText(), insertReset(), insertReverse(), insertUnderline(), keyPressEvent(), KviInputEditor(), pasteInternal(), popupTextIconWindow(), redoInternal(), showContextPopup(), and undoInternal().
bool KviInputEditor::m_bSpSlowFlag protected
Referenced by pasteFile(), pasteSlow(), showContextPopup(), and stopPasteSlow().
bool KviInputEditor::m_bUpdatesEnabled protected
Referenced by inputMethodEvent(), insertChar(), insertText(), KviInputEditor(), and repaintWithCursorOn().
int KviInputEditor::m_iCurHistoryIdx protected
Referenced by historyNext(), historyPrev(), KviInputEditor(), returnPressed(), sendKvs(), and sendPlain().
int KviInputEditor::m_iCursorPosition protected
Referenced by backspaceHit(), deleteHit(), deleteNextWord(), deletePreviousWord(), drawContents(), end(), endInternalSelection(), ensureCursorVisible(), findSpellCheckerBlockAtCursor(), getWordBeforeCursor(), handleDragSelection(), home(), homeInternal(), homeInternalSelection(), inputMethodEvent(), insertChar(), insertColor(), insertIconCode(), insertText(), internalCursorLeft(), internalCursorRight(), KviInputEditor(), mousePressEvent(), moveCursorTo(), nextCharSelection(), nextWord(), nextWordSelection(), popupTextIconWindow(), previousCharSelection(), previousWord(), previousWordSelection(), replaceWordBeforeCursor(), selectAllInternal(), sendKvs(), sendPlain(), showContextPopupHere(), showSpellCheckerCorrectionsPopup(), standardNickCompletion(), and textBeforeCursor().
int KviInputEditor::m_iCursorTimer protected
Referenced by focusInEvent(), focusOutEvent(), KviInputEditor(), timerEvent(), and ~KviInputEditor().
int KviInputEditor::m_iCursorWidth protected
Referenced by applyOptions(), and drawContents().
int KviInputEditor::m_iDragTimer protected
Referenced by killDragTimer(), KviInputEditor(), mousePressEvent(), and mouseReleaseEvent().
int KviInputEditor::m_iIMLength protected
Referenced by drawContents(), inputMethodEvent(), and KviInputEditor().
int KviInputEditor::m_iIMSelectionBegin protected
Referenced by drawContents(), inputMethodEvent(), and KviInputEditor().
int KviInputEditor::m_iIMSelectionLength protected
Referenced by drawContents(), inputMethodEvent(), and KviInputEditor().
int KviInputEditor::m_iIMStart protected
Referenced by drawContents(), inputMethodEvent(), and KviInputEditor().
int KviInputEditor::m_iLastCompletionCursorPosition protected
Referenced by standardNickCompletion().
int KviInputEditor::m_iMaxBufferSize protected
Referenced by insertChar(), insertText(), KviInputEditor(), replaceSegment(), replaceWordBeforeCursor(), and setText().
int KviInputEditor::m_iSelectionAnchorChar protected
Referenced by handleDragSelection(), KviInputEditor(), mousePressEvent(), and mouseReleaseEvent().
int KviInputEditor::m_iSelectionBegin protected
Referenced by backspaceHit(), clearSelection(), copyToClipboard(), copyToSelection(), cut(), endInternalSelection(), handleDragSelection(), hasSelection(), homeInternalSelection(), insertChar(), internalCursorLeft(), internalCursorRight(), KviInputEditor(), mouseDoubleClickEvent(), rebuildTextBlocks(), redo(), removeSelected(), selectAll(), selectAllInternal(), sendKvs(), sendPlain(), spellCheckerPopupCorrectionActionTriggered(), and undo().
int KviInputEditor::m_iSelectionEnd protected
Referenced by backspaceHit(), clearSelection(), copyToClipboard(), copyToSelection(), cut(), endInternalSelection(), handleDragSelection(), hasSelection(), homeInternalSelection(), insertChar(), internalCursorLeft(), internalCursorRight(), KviInputEditor(), mouseDoubleClickEvent(), rebuildTextBlocks(), redo(), removeSelected(), selectAll(), selectAllInternal(), sendKvs(), sendPlain(), spellCheckerPopupCorrectionActionTriggered(), and undo().
KviInputEditorPrivate* KviInputEditor::m_p protected
Referenced by backspaceHit(), charIndexFromXPosition(), clear(), clearSelection(), cut(), deleteHit(), deleteNextWord(), deletePreviousWord(), drawContents(), endInternalSelection(), ensureCursorVisible(), getLastFontMetrics(), handleDragSelection(), historyNext(), historyPrev(), homeInternalSelection(), insertChar(), insertText(), internalCursorLeft(), internalCursorRight(), KviInputEditor(), mouseDoubleClickEvent(), rebuildTextBlocks(), redo(), removeSelected(), replaceSegment(), replaceWordBeforeCursor(), selectAll(), selectAllInternal(), sendKvs(), sendPlain(), setText(), spellCheckerPopupCorrectionActionTriggered(), standardNickCompletion(), undo(), xPositionFromCharIndex(), and ~KviInputEditor().
KviPointerList<QString>* KviInputEditor::m_pHistory protected
Referenced by historyNext(), historyPrev(), KviInputEditor(), returnPressed(), sendKvs(), sendPlain(), and ~KviInputEditor().
QMenu* KviInputEditor::m_pIconMenu protected
Referenced by KviInputEditor(), and ~KviInputEditor().
QWidget* KviInputEditor::m_pInputParent protected
Referenced by completionEscapeUnsafeToken(), KviInputEditor(), openHistory(), pasteClipboardWithConfirmation(), pasteSelectionWithConfirmation(), returnPressed(), sendKvs(), sendPlain(), toggleCommandMode(), and toggleMultiLineEditor().
KviWindow* KviInputEditor::m_pKviWindow protected
Referenced by checkWordSpelling(), completion(), dropEvent(), KviInputEditor(), nextLine(), nextPage(), paintEvent(), pasteClipboardWithConfirmation(), pasteSelectionWithConfirmation(), previousLine(), previousPage(), scrollToLastReadLine(), search(), sendKvs(), sendPlain(), showContextPopup(), zoomDefault(), zoomIn(), and zoomOut().
KviInputEditor::m_pRedoStack protected
The redo stack.
Contains owned pointers and has autodelete set to true. The most recently undone command is at the end. Null when no redo is available.
Referenced by clearUndoStack(), KviInputEditor(), redo(), undo(), and ~KviInputEditor().
KviInputEditor::m_pUndoStack protected
The undo stack.
Contains owned pointers and has autodelete set to true. The most recent command is at the end. Null when no undo is available.
Referenced by addUndo(), clearUndoStack(), KviInputEditor(), redo(), undo(), and ~KviInputEditor().
KviUserListView* KviInputEditor::m_pUserListView protected
Referenced by completion(), KviInputEditor(), and standardNickCompletion().
QMenu KviInputEditor::m_SpellCheckerPopup protected
Referenced by fillSpellCheckerCorrectionsPopup(), showContextPopup(), and showSpellCheckerCorrectionsPopup().
KviCString KviInputEditor::m_szAltKeyCode protected
Referenced by keyPressEvent(), and keyReleaseEvent().
QString KviInputEditor::m_szIMText protected
QString KviInputEditor::m_szLastCompletedNick protected
Referenced by completion(), and standardNickCompletion().
QString KviInputEditor::m_szLastCompletionBuffer protected
Referenced by standardNickCompletion().
KviCString KviInputEditor::m_szSaveTextBuffer protected
Referenced by historyNext(), and historyPrev().
QString KviInputEditor::m_szTextBuffer protected
Referenced by backspaceHit(), clear(), completion(), copyToClipboard(), copyToSelection(), cut(), deleteHit(), deleteNextWord(), deletePreviousWord(), end(), endInternalSelection(), ensureCursorVisible(), fillSpellCheckerCorrectionsPopup(), getWordBeforeCursor(), handleDragSelection(), historyNext(), historyPrev(), insertChar(), insertIconCode(), insertText(), internalCursorRight(), mouseDoubleClickEvent(), moveCursorTo(), nextCharSelection(), nextWord(), nextWordSelection(), previousWord(), previousWordSelection(), rebuildTextBlocks(), redo(), removeSelected(), replaceSegment(), replaceWordBeforeCursor(), returnPressed(), selectAll(), selectAllInternal(), sendKvs(), sendPlain(), setText(), showContextPopup(), spellCheckerPopupCorrectionActionTriggered(), standardNickCompletion(), textBeforeCursor(), toggleMultiLineEditor(), and undo().
Property Documentation
int KviInputEditor::TransparencyCapable read
The documentation for this class was generated from the following files:
src/kvirc/ui/KviInputEditor.h
src/kvirc/ui/KviInputEditor.cpp