KVIrc: RawTreeWidgetItem Class Reference
RawTreeWidgetItem Class Reference
#include <RawEditorWindow.h>
Public Member Functions
RawTreeWidgetItem (QTreeWidget *par, int idx, bool bEnabled)
void setEnabled (bool bEnabled)
~RawTreeWidgetItem ()
Public Attributes
int m_iIdx
Constructor & Destructor Documentation
RawTreeWidgetItem::RawTreeWidgetItem (QTreeWidget * par, int idx, bool bEnabled)
References m_iIdx, and setEnabled().
RawTreeWidgetItem::~RawTreeWidgetItem () [inline]
Member Function Documentation
void RawTreeWidgetItem::setEnabled (bool bEnabled) [inline]
References g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::RawEvent, and KviIconManager::RawEventNoHandlers.
Referenced by RawEditorWidget::addHandlerForCurrentRaw(), RawTreeWidgetItem(), and RawEditorWidget::removeCurrentHandler().
Member Data Documentation
int RawTreeWidgetItem::m_iIdx
Referenced by RawTreeWidgetItem().
The documentation for this class was generated from the following files:
src/modules/raweditor/RawEditorWindow.h
src/modules/raweditor/RawEditorWindow.cpp