KVIrc: KviKvsTreeNodeExpressionUnaryOperatorNegate Class Reference
KviKvsTreeNodeExpressionUnaryOperatorNegate Class Reference
#include <KviKvsTreeNodeExpression.h>
Public Member Functions
virtual void contextDescription (QString &szBuffer)
Sets the buffer.
virtual void dump (const char *prefix)
Dumps the tree.
virtual bool evaluateReadOnly (KviKvsRunTimeContext *c, KviKvsVariant *pResult)
KviKvsTreeNodeExpressionUnaryOperatorNegate (const QChar *pLocation, KviKvsTreeNodeExpression *pData)
virtual int precedence ()
~KviKvsTreeNodeExpressionUnaryOperatorNegate ()
Public Member Functions inherited from KviKvsTreeNodeExpressionUnaryOperator
bool evaluateOperand (KviKvsRunTimeContext *c)
KviKvsTreeNodeExpressionUnaryOperator (const QChar *pLocation, KviKvsTreeNodeExpression *pData)
~KviKvsTreeNodeExpressionUnaryOperator ()
Public Member Functions inherited from KviKvsTreeNodeExpressionOperator
KviKvsTreeNodeExpressionOperator (const QChar *pLocation)
~KviKvsTreeNodeExpressionOperator ()
Public Member Functions inherited from KviKvsTreeNodeExpression
virtual int firstBinaryOperator ()
KviKvsTreeNodeExpression (const QChar *pLocation)
virtual KviKvsTreeNodeExpression * left ()
KviKvsTreeNodeExpression * parentExpression ()
virtual KviKvsTreeNodeExpression * parentWithPrecedenceLowerThan (int iPrec)
virtual KviKvsTreeNodeExpression * right ()
virtual void setLeft (KviKvsTreeNodeExpression *pLeft)
void setParentExpression (KviKvsTreeNodeExpression *pParent)
virtual void setRight (KviKvsTreeNodeExpression *pRight)
~KviKvsTreeNodeExpression ()
Public Member Functions inherited from KviKvsTreeNodeData
virtual bool canEvaluateInObjectScope ()
virtual bool canEvaluateToObjectReference ()
virtual bool convertStringConstantToNumeric ()
const QChar * endingLocation ()
virtual bool evaluateReadOnlyInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c, KviKvsVariant *pBuffer)
virtual KviKvsRWEvaluationResult * evaluateReadWrite (KviKvsRunTimeContext *c)
virtual KviKvsRWEvaluationResult * evaluateReadWriteInObjectScope (KviKvsObject *o, KviKvsRunTimeContext *c)
virtual bool isFunctionCall ()
virtual bool isReadOnly ()
KviKvsTreeNodeData (const QChar *pLocation)
void setEndingLocation (const QChar *pEndingLocation)
~KviKvsTreeNodeData ()
Public Member Functions inherited from KviKvsTreeNode
KviKvsTreeNode (const QChar *pLocation)
Constructs the treenode object.
const QChar * location ()
Returns the location char.
KviKvsTreeNode * parent ()
Returns the parent object.
void setParent (KviKvsTreeNode *p)
Sets the parent object.
virtual ~KviKvsTreeNode ()
Destroys the treenode object.
Additional Inherited Members
Protected Member Functions inherited from KviKvsTreeNode
void setLocation (const QChar *pLocation)
Sets the location char.
Protected Attributes inherited from KviKvsTreeNodeExpressionUnaryOperator
KviKvsNumber m_nData
KviKvsTreeNodeExpression * m_pData
Protected Attributes inherited from KviKvsTreeNodeExpression
KviKvsTreeNodeExpression * m_pParentExpression
Protected Attributes inherited from KviKvsTreeNodeData
const QChar * m_pEndingLocation
Protected Attributes inherited from KviKvsTreeNode
const QChar * m_pLocation
KviKvsTreeNode * m_pParent
Constructor & Destructor Documentation
KviKvsTreeNodeExpressionUnaryOperatorNegate::KviKvsTreeNodeExpressionUnaryOperatorNegate (const QChar * pLocation, KviKvsTreeNodeExpression * pData)
KviKvsTreeNodeExpressionUnaryOperatorNegate::~KviKvsTreeNodeExpressionUnaryOperatorNegate ()
Member Function Documentation
void KviKvsTreeNodeExpressionUnaryOperatorNegate::contextDescription (QString & szBuffer) virtual
Sets the buffer.
Parameters
szBuffer The buffer :)
Returns
void
Reimplemented from KviKvsTreeNodeExpressionUnaryOperator.
void KviKvsTreeNodeExpressionUnaryOperatorNegate::dump (const char * prefix) virtual
Dumps the tree.
Parameters
prefix The prefix of the instruction
Returns
void
Reimplemented from KviKvsTreeNodeExpressionUnaryOperator.
References KviKvsTreeNodeExpression::dump(), and KviKvsTreeNodeExpressionUnaryOperator::m_pData.
bool KviKvsTreeNodeExpressionUnaryOperatorNegate::evaluateReadOnly (KviKvsRunTimeContext * c, KviKvsVariant * pResult) virtual
Reimplemented from KviKvsTreeNodeData.
References KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand(), KviKvsNumber::integer(), KviKvsNumber::isReal(), KviKvsTreeNodeExpressionUnaryOperator::m_nData, KviKvsNumber::real(), KviKvsVariant::setInteger(), and KviKvsVariant::setReal().
int KviKvsTreeNodeExpressionUnaryOperatorNegate::precedence () virtual
Reimplemented from KviKvsTreeNodeExpression.
References PREC_OP_NEGATE.
The documentation for this class was generated from the following files:
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.h
src/kvirc/kvs/tree/KviKvsTreeNodeExpression.cpp