KVIrc: KviThemedComboBox Class Reference
KviThemedComboBox Class Reference
#include <KviThemedComboBox.h>
Signals
void returnPressed (QString)
Public Member Functions
void applyOptions ()
int dummyRead () const
KviThemedComboBox (QWidget *par, KviWindow *pWindow, const char *name)
~KviThemedComboBox ()
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *e)
virtual void paintEvent (QPaintEvent *event)
Properties
int TransparencyCapable
Private Attributes
KviWindow * m_pKviWindow
Constructor & Destructor Documentation
KviThemedComboBox::KviThemedComboBox (QWidget * par, KviWindow * pWindow, const char * name)
References applyOptions(), and m_pKviWindow.
KviThemedComboBox::~KviThemedComboBox ()
Member Function Documentation
void KviThemedComboBox::applyOptions ()
References KviControlCodes::Bold, g_pApp, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_FONT, KVI_OPTION_MIRCCOLOR, KVI_OPTION_MSGTYPE, KVI_OUT_NONE, KviOption_boolUseCompositingForTransparency, KviOption_colorLabelBackground, KviOption_colorLabelForeground, KviOption_fontLabel, KviOsInfo::name(), and KviApplication::supportsCompositing().
Referenced by KviConsoleWindow::applyOptions(), and KviThemedComboBox().
int KviThemedComboBox::dummyRead () const inline
void KviThemedComboBox::keyPressEvent (QKeyEvent * e) protected virtual
References returnPressed().
void KviThemedComboBox::paintEvent (QPaintEvent * event) protected virtual
References g_pApp, g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_COLOR, KVI_OPTION_UINT, KviOption_boolUseCompositingForTransparency, KviOption_colorGlobalTransparencyFade, KviOption_uintGlobalTransparencyChildFadeFactor, m_pKviWindow, KviMainWindow::mdiManager(), KviWindow::mdiParent(), p, r, KviMdiManager::scrollBarsOffset(), and KviApplication::supportsCompositing().
void KviThemedComboBox::returnPressed (QString) signal
Referenced by keyPressEvent().
Member Data Documentation
KviWindow* KviThemedComboBox::m_pKviWindow private
Referenced by KviThemedComboBox(), and paintEvent().
Property Documentation
int KviThemedComboBox::TransparencyCapable read
The documentation for this class was generated from the following files:
src/kvirc/ui/KviThemedComboBox.h
src/kvirc/ui/KviThemedComboBox.cpp