KVIrc: KviTrayIconWidget Class Reference
KviTrayIconWidget Class Reference
#include <libkvitrayicon.h>
Public Member Functions
virtual void die ()
KviTrayIconWidget ()
virtual void refresh ()
void updateIcon ()
~KviTrayIconWidget ()
Public Member Functions inherited from KviTrayIcon
Qt::WindowStates getPrevWindowState ()
KviTrayIcon ()
void setPrevWindowState (Qt::WindowStates state)
virtual ~KviTrayIcon ()
Protected Slots
void activatedSlot (QSystemTrayIcon::ActivationReason reason)
void disableTrayIcon ()
void doAway (bool)
void executeInternalCommand (bool)
void fillContextPopup ()
void flashingTimerShot ()
void toggleParentFrame ()
Protected Member Functions
virtual bool event (QEvent *e)
void grabActivityInfo ()
Protected Attributes
bool m_bFlashed
bool m_bHidden
QPixmap m_CurrentPixmap
unsigned int m_iChannels
unsigned int m_iConsoles
unsigned int m_iOther
unsigned int m_iQueries
QAction * m_pAwayMenuId
QMenu * m_pAwayPopup
QMenu * m_pContextPopup
QTimer * m_pFlashingTimer
QLabel * m_pTitleLabel
QAction * m_pToggleFrame
KviDynamicToolTip m_Tip
Constructor & Destructor Documentation
KviTrayIconWidget::KviTrayIconWidget ()
References __tr2qs, activatedSlot(), KviIconManager::Away, connect(), KviIconManager::DefaultIcon, disableTrayIcon(), executeInternalCommand(), fillContextPopup(), flashingTimerShot(), g_pDock1, g_pIconManager, g_pMainWindow, KviIconManager::getSmallIcon(), KviIconManager::Info, KVI_INTERNALCOMMAND_ABOUT_ABOUTKVIRC, KVI_INTERNALCOMMAND_OPTIONS_DIALOG, m_bFlashed, m_bHidden, m_iChannels, m_iConsoles, m_iOther, m_iQueries, m_pAwayMenuId, m_pAwayPopup, m_pContextPopup, m_pFlashingTimer, m_pTitleLabel, m_pToggleFrame, Normal, KviIconManager::Options, p, KviIconManager::QuitApp, KviMainWindow::setTrayIcon(), toggleParentFrame(), and KviIconManager::TrayIcon.
KviTrayIconWidget::~KviTrayIconWidget ()
References g_pMainWindow, m_bHidden, m_pAwayPopup, m_pContextPopup, m_pFlashingTimer, m_pTitleLabel, and KviMainWindow::setTrayIcon().
Member Function Documentation
void KviTrayIconWidget::activatedSlot (QSystemTrayIcon::ActivationReason reason) protected slot
COMPILE_ON_MAC
COMPILE_ON_MAC
References g_pMainWindow, KVI_OPTION_BOOL, KviOption_boolCloseInTray, KviOption_boolMinimizeInTray, and toggleParentFrame().
Referenced by KviTrayIconWidget().
void KviTrayIconWidget::die () virtual
Reimplemented from KviTrayIcon.
void KviTrayIconWidget::disableTrayIcon () protected slot
References KviMainWindow::executeInternalCommand(), g_pMainWindow, KVI_INTERNALCOMMAND_TRAYICON_HIDE, KVI_OPTION_BOOL, KviOption_boolShowDockExtension, and m_bHidden.
Referenced by KviTrayIconWidget().
void KviTrayIconWidget::doAway (bool) protected slot
References KviWindow::connection(), KviPointerHashTableIterator< Key, T >::current(), KviIrcConnection::encodeText(), KviApplication::findConsole(), g_pApp, g_pGlobalWindowDict, KviIrcConnectionUserInfo::isAway(), KviConsoleWindow::isConnected(), KVI_OPTION_STRING, KviOption_stringAwayMessage, KviIrcConnection::sendFmtData(), and KviIrcConnection::userInfo().
Referenced by fillContextPopup().
bool KviTrayIconWidget::event (QEvent * e) protected virtual
References __tr2qs_no_xgettext, first(), KviWindowListBase::firstItem(), g_pMainWindow, idlemsgs, m_Tip, KviWindowListBase::nextItem(), NIDLEMSGS, t(), KviDynamicToolTip::tip(), and KviMainWindow::windowListWidget().
void KviTrayIconWidget::executeInternalCommand (bool) protected slot
References KviMainWindow::executeInternalCommand(), and g_pMainWindow.
Referenced by KviTrayIconWidget().
void KviTrayIconWidget::fillContextPopup () protected slot
References __tr2qs, KviIconManager::Away, KviWindow::connection(), KviConsoleWindow::context(), KviPointerHashTableIterator< Key, T >::current(), KviConsoleWindow::currentNetworkName(), doAway(), g_pApp, g_pGlobalWindowDict, g_pIconManager, g_pMainWindow, KviIconManager::getSmallIcon(), KviIrcContext::id(), KviIrcConnectionUserInfo::isAway(), KviConsoleWindow::isConnected(), m_pAwayMenuId, m_pAwayPopup, m_pToggleFrame, KviIconManager::NotAway, KviApplication::topmostConnectedConsole(), and KviIrcConnection::userInfo().
Referenced by KviTrayIconWidget().
void KviTrayIconWidget::flashingTimerShot () protected slot
References m_bFlashed, and refresh().
Referenced by KviTrayIconWidget().
void KviTrayIconWidget::grabActivityInfo () protected
References KviWindow::Channel, KviWindow::Console, KviWindowListBase::firstItem(), g_pMainWindow, KVI_OPTION_BOOL, KVI_OPTION_UINT, KviOption_boolUseLevelBasedTrayNotification, KviOption_uintMinTrayHighLevelMessage, KviOption_uintMinTrayLowLevelMessage, m_iChannels, m_iConsoles, m_iOther, m_iQueries, KviWindowListBase::nextItem(), KviWindow::Query, t(), and KviMainWindow::windowListWidget().
Referenced by refresh().
void KviTrayIconWidget::refresh () virtual
Reimplemented from KviTrayIcon.
References g_pDock1, g_pDock2, g_pDock3, g_pIconManager, KviIconManager::getSmallIcon(), grabActivityInfo(), ICON_SIZE, KVI_OPTION_BOOL, KviOption_boolEnableTrayIconFlashing, m_bFlashed, m_CurrentPixmap, m_iChannels, m_iConsoles, m_iOther, m_iQueries, m_pFlashingTimer, KviIconManager::Message, and updateIcon().
Referenced by flashingTimerShot().
void KviTrayIconWidget::toggleParentFrame () protected slot
References g_pMainWindow, KVI_OPTION_BOOL, and KviOption_boolFrameIsMaximized.
Referenced by activatedSlot(), and KviTrayIconWidget().
void KviTrayIconWidget::updateIcon ()
References m_CurrentPixmap.
Referenced by refresh().
Member Data Documentation
bool KviTrayIconWidget::m_bFlashed protected
Referenced by flashingTimerShot(), KviTrayIconWidget(), and refresh().
bool KviTrayIconWidget::m_bHidden protected
Referenced by disableTrayIcon(), KviTrayIconWidget(), and ~KviTrayIconWidget().
QPixmap KviTrayIconWidget::m_CurrentPixmap protected
Referenced by refresh(), and updateIcon().
unsigned int KviTrayIconWidget::m_iChannels protected
Referenced by grabActivityInfo(), KviTrayIconWidget(), and refresh().
unsigned int KviTrayIconWidget::m_iConsoles protected
Referenced by grabActivityInfo(), KviTrayIconWidget(), and refresh().
unsigned int KviTrayIconWidget::m_iOther protected
Referenced by grabActivityInfo(), KviTrayIconWidget(), and refresh().
unsigned int KviTrayIconWidget::m_iQueries protected
Referenced by grabActivityInfo(), KviTrayIconWidget(), and refresh().
QAction* KviTrayIconWidget::m_pAwayMenuId protected
Referenced by fillContextPopup(), and KviTrayIconWidget().
QMenu* KviTrayIconWidget::m_pAwayPopup protected
Referenced by fillContextPopup(), KviTrayIconWidget(), and ~KviTrayIconWidget().
QMenu* KviTrayIconWidget::m_pContextPopup protected
Referenced by KviTrayIconWidget(), and ~KviTrayIconWidget().
QTimer* KviTrayIconWidget::m_pFlashingTimer protected
Referenced by KviTrayIconWidget(), refresh(), and ~KviTrayIconWidget().
QLabel* KviTrayIconWidget::m_pTitleLabel protected
Referenced by KviTrayIconWidget(), and ~KviTrayIconWidget().
QAction* KviTrayIconWidget::m_pToggleFrame protected
Referenced by fillContextPopup(), and KviTrayIconWidget().
KviDynamicToolTip KviTrayIconWidget::m_Tip protected
Referenced by event().
The documentation for this class was generated from the following files:
src/modules/trayicon/libkvitrayicon.h
src/modules/trayicon/libkvitrayicon.cpp