KVIrc: KviScriptEditor Class Reference
KviScriptEditor Class Reference
#include <KviScriptEditor.h>
Public Member Functions
virtual int getCursor ()
virtual void getText (QByteArray &txt)
virtual void getText (QString &txt)
virtual bool isModified ()
virtual void setCursorPosition (int)
virtual void setFindLineeditReadOnly (bool b)
virtual void setFindText (const QString &text)
virtual void setInfoText (const QString &text)
virtual void setModified (bool)
virtual void setReadOnly (bool bReadonly)
virtual void setText (const char *txt)
virtual void setText (const QString &txt)
virtual void setText (const QByteArray &txt)
virtual void setUnHighlightedText (const QString &szText)
Static Public Member Functions
static KviScriptEditor * createInstance (QWidget *par)
static void destroyInstance (KviScriptEditor *e)
static KviScriptEditor * getDummyEditor (QWidget *par)
Protected Member Functions
KviScriptEditor (QWidget *par)
~KviScriptEditor ()
Protected Attributes
QLineEdit * m_pFindLineedit
Constructor & Destructor Documentation
KviScriptEditor::KviScriptEditor (QWidget * par) [protected]
Referenced by getDummyEditor().
KviScriptEditor::~KviScriptEditor () [protected]
Member Function Documentation
KviScriptEditor * KviScriptEditor::createInstance (QWidget * par) [static]
References editorModuleCreateScriptEditor, g_pModuleManager, getDummyEditor(), KviModuleManager::getModule(), KviModule::getSymbol(), and m.
Referenced by AliasEditorWidget::AliasEditorWidget(), ClassEditorWidget::ClassEditorWidget(), CodeTesterWidget::CodeTesterWidget(), EventEditor::EventEditor(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviInput::multiLineEditorButtonToggled(), RawEditorWidget::RawEditorWidget(), SingleActionEditor::SingleActionEditor(), and SinglePopupEditor::SinglePopupEditor().
void KviScriptEditor::destroyInstance (KviScriptEditor * e) [static]
References e, editorModuleDestroyScriptEditor, g_pModuleManager, KviModuleManager::getModule(), KviModule::getSymbol(), and m.
Referenced by KviInput::multiLineEditorButtonToggled(), AliasEditorWidget::~AliasEditorWidget(), CodeTesterWidget::~CodeTesterWidget(), EventEditor::~EventEditor(), IrcNetworkDetailsWidget::~IrcNetworkDetailsWidget(), IrcServerDetailsWidget::~IrcServerDetailsWidget(), KviInput::~KviInput(), RawEditorWidget::~RawEditorWidget(), and SinglePopupEditor::~SinglePopupEditor().
int KviScriptEditor::getCursor () [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by AliasEditorWidget::renameItem(), EventEditor::saveLastEditedItem(), ClassEditorWidget::saveLastEditedItem(), and AliasEditorWidget::saveLastEditedItem().
KviScriptEditor * KviScriptEditor::getDummyEditor (QWidget * par) [static]
References KviScriptEditor().
Referenced by createInstance().
void KviScriptEditor::getText (QByteArray & txt) [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by SingleActionEditor::commit(), CodeTesterWidget::execute(), IrcServerDetailsWidget::fillData(), IrcNetworkDetailsWidget::fillData(), getText(), KviInput::keyPressEvent(), KviInput::multiLineEditorButtonToggled(), AliasEditorWidget::renameItem(), RawEditorWidget::saveLastEditedItem(), EventEditor::saveLastEditedItem(), ClassEditorWidget::saveLastEditedItem(), AliasEditorWidget::saveLastEditedItem(), SinglePopupEditor::saveLastSelectedItem(), and KviInput::text().
void KviScriptEditor::getText (QString & txt) [virtual]
Reimplemented in ScriptEditorImplementation.
References getText().
bool KviScriptEditor::isModified () [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by ClassEditorWidget::saveLastEditedItem(), and AliasEditorWidget::saveLastEditedItem().
void KviScriptEditor::setCursorPosition (int) [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by EventEditor::currentItemChanged(), ClassEditorWidget::currentItemChanged(), and AliasEditorWidget::currentItemChanged().
void KviScriptEditor::setFindLineeditReadOnly (bool b) [virtual]
void KviScriptEditor::setFindText (const QString & text) [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by ClassEditorWidget::slotFind(), AliasEditorWidget::slotFind(), ClassEditorWidget::slotFindWord(), AliasEditorWidget::slotFindWord(), ClassEditorWidget::slotReplaceAll(), and AliasEditorWidget::slotReplaceAll().
void KviScriptEditor::setInfoText (const QString & text) [virtual]
virtual void KviScriptEditor::setModified (bool) [inline, virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by ClassEditorWidget::build().
void KviScriptEditor::setReadOnly (bool bReadonly) [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by ClassEditorWidget::currentItemChanged().
void KviScriptEditor::setText (const char * txt) [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by AliasEditorWidget::aliasRefresh(), RawEditorWidget::currentItemChanged(), EventEditor::currentItemChanged(), ClassEditorWidget::currentItemChanged(), AliasEditorWidget::currentItemChanged(), SinglePopupEditor::edit(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviInput::keyPressEvent(), KviInput::multiLineEditorButtonToggled(), KviInput::multiLinePaste(), SinglePopupEditor::selectionChanged(), SingleActionEditor::setActionData(), setText(), and KviInput::setText().
void KviScriptEditor::setText (const QString & txt) [virtual]
Reimplemented in ScriptEditorImplementation.
References setText().
void KviScriptEditor::setText (const QByteArray & txt) [virtual]
Reimplemented in ScriptEditorImplementation.
void KviScriptEditor::setUnHighlightedText (const QString & szText) [virtual]
Reimplemented in ScriptEditorImplementation.
Referenced by ClassEditorWidget::currentItemChanged().
Member Data Documentation
QLineEdit* KviScriptEditor::m_pFindLineedit [protected]
The documentation for this class was generated from the following files:
src/kvirc/ui/KviScriptEditor.h
src/kvirc/ui/KviScriptEditor.cpp