KVIrc: KviThreadDataEvent< TData > Class Template Reference
KviThreadDataEvent< TData > Class Template Reference
#include <KviThread.h>
Public Member Functions
TData * data ()
TData * getData ()
KviThreadDataEvent (int evId, TData *pData=0, KviThread *sender=0)
void setData (TData *d)
virtual ~KviThreadDataEvent ()
Public Member Functions inherited from KviThreadEvent
int id ()
KviThreadEvent (int evId, KviThread *sender=0)
KviThread * sender ()
virtual ~KviThreadEvent ()
Protected Attributes
TData * m_pData
Protected Attributes inherited from KviThreadEvent
int m_eventId
KviThread * m_pSender
Constructor & Destructor Documentation
template<class TData> KviThreadDataEvent< TData >::KviThreadDataEvent (int evId, TData * pData = 0, KviThread * sender = 0) inline
References KviThreadDataEvent< TData >::m_pData.
template<class TData> virtual KviThreadDataEvent< TData >::~KviThreadDataEvent () inline virtual
References KviThreadDataEvent< TData >::m_pData.
Member Function Documentation
template<class TData> TData* KviThreadDataEvent< TData >::data () inline
References KviThreadDataEvent< TData >::m_pData.
template<class TData> TData* KviThreadDataEvent< TData >::getData () inline
References KviThreadDataEvent< TData >::m_pData.
template<class TData> void KviThreadDataEvent< TData >::setData (TData * d) inline
References d, and KviThreadDataEvent< TData >::m_pData.
Referenced by DccChatThread::handleIncomingData(), DccVideoThread::handleIncomingData(), DccThread::postErrorEvent(), KviIdentDaemon::postMessage(), DccThread::postMessageEvent(), DccRecvThread::postMessageEvent(), DccSendThread::run(), DccVideoThread::startPlaying(), DccVoiceThread::startPlaying(), DccVideoThread::startRecording(), DccVoiceThread::startRecording(), DccVoiceWindow::startTalking(), DccVideoWindow::startTalking(), DccVideoThread::stopPlaying(), DccVoiceThread::stopPlaying(), DccVideoThread::stopRecording(), DccVoiceThread::stopRecording(), DccVoiceWindow::stopTalking(), DccVideoWindow::stopTalking(), and DccVideoThread::videoStep().
Member Data Documentation
template<class TData> TData* KviThreadDataEvent< TData >::m_pData protected
Referenced by KviThreadDataEvent< TData >::data(), KviThreadDataEvent< TData >::getData(), KviThreadDataEvent< TData >::KviThreadDataEvent(), KviThreadDataEvent< TData >::setData(), and KviThreadDataEvent< TData >::~KviThreadDataEvent().
The documentation for this class was generated from the following file:
src/kvilib/system/KviThread.h