KVIrc: KviCustomToolBarManager Class Reference
KviCustomToolBarManager Class Reference
#include <KviCustomToolBarManager.h>
Public Member Functions
void clear ()
KviCustomToolBarDescriptor * create (const QString &szId, const QString &szLabelCode)
void createToolBarsVisibleAtStartup ()
int descriptorCount ()
KviPointerHashTable< QString,
KviCustomToolBarDescriptor > * descriptors ()
bool destroyDescriptor (const QString &szId)
KviCustomToolBarDescriptor * find (const QString &szId)
KviCustomToolBarDescriptor * findDescriptorByInternalId (int id)
KviCustomToolBar * firstExistingToolBar ()
QString idForNewToolBar (const QString &szTemplate)
void load (const QString &szFileName)
bool renameDescriptor (const QString &szId, const QString &szNewId, const QString &szNewLabelCode)
void save (const QString &szFileName)
void storeVisibilityState ()
void updateVisibleToolBars ()
int visibleToolBarCount ()
Static Public Member Functions
static void done ()
static void init ()
static KviCustomToolBarManager * instance ()
Protected Member Functions
KviCustomToolBarManager ()
~KviCustomToolBarManager ()
Protected Attributes
KviPointerHashTable< QString,
KviCustomToolBarDescriptor > * m_pDescriptors
Static Protected Attributes
static KviCustomToolBarManager * m_pInstance = 0
Constructor & Destructor Documentation
KviCustomToolBarManager::KviCustomToolBarManager () [protected]
References m_pDescriptors, and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by init().
KviCustomToolBarManager::~KviCustomToolBarManager () [protected]
References m_pDescriptors.
Member Function Documentation
void KviCustomToolBarManager::clear ()
References KviPointerHashTable< Key, T >::clear(), and m_pDescriptors.
Referenced by KviDefaultScriptManager::restoreInternal().
KviCustomToolBarDescriptor * KviCustomToolBarManager::create (const QString & szId, const QString & szLabelCode)
References d, KviPointerHashTable< Key, T >::find(), m_pDescriptors, and KviPointerHashTable< Key, T >::replace().
Referenced by toolbar_kvs_cmd_create().
void KviCustomToolBarManager::createToolBarsVisibleAtStartup ()
References KviPointerHashTableIterator< Key, T >::current(), d, and m_pDescriptors.
Referenced by KviMainWindow::createNewConsole().
int KviCustomToolBarManager::descriptorCount () [inline]
KviPointerHashTable<QString,KviCustomToolBarDescriptor>* KviCustomToolBarManager::descriptors () [inline]
bool KviCustomToolBarManager::destroyDescriptor (const QString & szId)
References d, KviPointerHashTable< Key, T >::find(), m_pDescriptors, and KviPointerHashTable< Key, T >::remove().
Referenced by toolbar_kvs_cmd_hide().
void KviCustomToolBarManager::done () [static]
References m_pInstance.
KviCustomToolBarDescriptor* KviCustomToolBarManager::find (const QString & szId) [inline]
Referenced by toolbar_kvs_cmd_additem(), toolbar_kvs_cmd_clear(), toolbar_kvs_cmd_create(), toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_removeitem(), toolbar_kvs_cmd_show(), toolbar_kvs_fnc_isVisible(), and toolbar_kvs_fnc_items().
KviCustomToolBarDescriptor * KviCustomToolBarManager::findDescriptorByInternalId (int id)
References KviPointerHashTableIterator< Key, T >::current(), d, and m_pDescriptors.
Referenced by KviMainWindow::toolbarsPopupSelected().
KviCustomToolBar * KviCustomToolBarManager::firstExistingToolBar ()
References KviPointerHashTableIterator< Key, T >::current(), d, and m_pDescriptors.
QString KviCustomToolBarManager::idForNewToolBar (const QString & szTemplate)
References KviPointerHashTable< Key, T >::find(), m_pDescriptors, and s.
Referenced by CustomToolBarPropertiesDialog::labelTextChanged(), and CustomToolBarPropertiesDialog::okClicked().
void KviCustomToolBarManager::init () [static]
References KviCustomToolBarManager(), and m_pInstance.
static KviCustomToolBarManager* KviCustomToolBarManager::instance () [inline, static]
Referenced by KviApplication::checkSuggestRestoreDefaultScript(), ActionEditor::commit(), KviMainWindow::createNewConsole(), KviMainWindow::fillToolBarsPopup(), CustomToolBarPropertiesDialog::labelTextChanged(), CustomizeToolBarsDialog::newToolBar(), CustomToolBarPropertiesDialog::okClicked(), KviDefaultScriptManager::restoreInternal(), KviApplication::saveConfiguration(), KviApplication::saveToolBars(), KviApplication::setup(), KviMainWindow::setUsesBigPixmaps(), toolbar_kvs_cmd_additem(), toolbar_kvs_cmd_clear(), toolbar_kvs_cmd_create(), toolbar_kvs_cmd_destroy(), toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_removeitem(), toolbar_kvs_cmd_show(), toolbar_kvs_fnc_exists(), toolbar_kvs_fnc_isVisible(), toolbar_kvs_fnc_items(), toolbar_kvs_fnc_list(), KviMainWindow::toolbarsPopupSelected(), and KviMainWindow::~KviMainWindow().
void KviCustomToolBarManager::load (const QString & szFileName)
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, KviConfigurationFile::dict(), KviCustomToolBarDescriptor::load(), KviCustomToolBarDescriptor::m_bVisibleAtStartup, m_pDescriptors, KviConfigurationFile::Read, KviConfigurationFile::readIntEntry(), KviPointerHashTable< Key, T >::replace(), and KviConfigurationFile::setGroup().
Referenced by KviApplication::setup().
bool KviCustomToolBarManager::renameDescriptor (const QString & szId, const QString & szNewId, const QString & szNewLabelCode)
References d, KviPointerHashTable< Key, T >::find(), m_pDescriptors, KviPointerHashTable< Key, T >::remove(), KviCustomToolBarDescriptor::rename(), KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
void KviCustomToolBarManager::save (const QString & szFileName)
References KviPointerHashTableIterator< Key, T >::current(), d, m_pDescriptors, KviConfigurationFile::setGroup(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
Referenced by KviApplication::saveToolBars().
void KviCustomToolBarManager::storeVisibilityState ()
References KviPointerHashTableIterator< Key, T >::current(), d, and m_pDescriptors.
Referenced by KviApplication::saveConfiguration(), and KviMainWindow::~KviMainWindow().
void KviCustomToolBarManager::updateVisibleToolBars ()
References KviPointerHashTableIterator< Key, T >::current(), d, and m_pDescriptors.
Referenced by ActionEditor::commit().
int KviCustomToolBarManager::visibleToolBarCount ()
References KviPointerHashTableIterator< Key, T >::current(), d, and m_pDescriptors.
Member Data Documentation
KviPointerHashTable<QString,KviCustomToolBarDescriptor>* KviCustomToolBarManager::m_pDescriptors [protected]
Referenced by clear(), create(), createToolBarsVisibleAtStartup(), destroyDescriptor(), findDescriptorByInternalId(), firstExistingToolBar(), idForNewToolBar(), KviCustomToolBarManager(), load(), renameDescriptor(), save(), storeVisibilityState(), updateVisibleToolBars(), visibleToolBarCount(), and ~KviCustomToolBarManager().
KviCustomToolBarManager * KviCustomToolBarManager::m_pInstance = 0 [static, protected]
Referenced by done(), and init().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviCustomToolBarManager.h
src/kvirc/kernel/KviCustomToolBarManager.cpp