KVIrc: OptionsWidget_proxy Class Reference
OptionsWidget_proxy Class Reference
#include <OptionsWidget_proxy.h>
Public Member Functions
virtual void commit ()
OptionsWidget_proxy (QWidget *parent)
~OptionsWidget_proxy ()
Public Member Functions inherited from KviOptionsWidget
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParent, const QString &txt, bool *pOption, bool bEnabled=true)
KviBoolSelector * addBoolSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviBoolSelector * addBoolSelector (QWidget *pParnt, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, QColor *pOption, bool bEnabled=true)
KviColorSelector * addColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviColorSelector * addColorSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviDirectorySelector * addDirectorySelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviFileSelector * addFileSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFileSelector * addFileSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, QFont *pOption, bool bEnabled=true)
KviFontSelector * addFontSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviFontSelector * addFontSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviTalGroupBox * addGroupBox (int x1, int y1, int x2, int y2, Qt::Orientation o, const QString &txt, bool bEnabled=true)
QLabel * addLabel (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
QLabel * addLabel (QWidget *pParent, const QString &text, bool bEnabled=true)
QLineEdit * addLineEdit (int x1, int y1, int x2, int y2, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, unsigned int *uFore, unsigned int *uBack, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (int x1, int y1, int x2, int y2, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
KviMircTextColorSelector * addMircTextColorSelector (QWidget *pParent, const QString &txt, int optForeId, int optBackId, bool bEnabled=true)
void addOptionsWidget (const QString &szText, const QIcon &iconSet, KviOptionsWidget *pWidget)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPasswordSelector * addPasswordSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviPixmapSelector * addPixmapSelector (int x1, int y1, int x2, int y2, const QString &txt, KviPixmap *pOption, bool bEnabled=true)
QPushButton * addPushButton (int x1, int y1, int x2, int y2, const QString &text, bool bEnabled=true)
void addRowSpacer (int x1, int y1, int x2, int y2)
QFrame * addSeparator (int x1, int y1, int x2, int y2)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviSoundSelector * addSoundSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviSoundSelector * addSoundSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, QStringList *pOption, bool bEnabled=true)
KviStringListSelector * addStringListSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, QString *pOption, bool bEnabled=true)
KviStringSelector * addStringSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, bool bEnabled=true)
KviStringSelector * addStringSelector (QWidget *pParent, const QString &txt, int optId, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, unsigned int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (int x1, int y1, int x2, int y2, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUIntSelector (QWidget *pParent, const QString &txt, int optId, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
KviUIntSelector * addUShortIntSelector (int x1, int y1, int x2, int y2, const QString &txt, unsigned short int *pOption, unsigned int uLowBound, unsigned int uHighBound, unsigned int uDefault, bool bEnabled=true)
void addWidgetToLayout (QWidget *w, int x1, int y1, int x2, int y2)
virtual void childEvent (QChildEvent *e)
void createLayout ()
void createTabbedPage ()
virtual bool eventFilter (QObject *watched, QEvent *e)
KviOptionsWidget (QWidget *parent, const char *name=0, bool bSunken=true)
QGridLayout * layout ()
void mergeResetFlag (int flag)
void mergeTip (QWidget *w, const QString &tip)
void removeSelector (KviSelectorInterface *pInterface)
KviPointerList
< KviSelectorInterface > * selectors ()
QTabWidget * tabWidget ()
~KviOptionsWidget ()
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual QString textForSearch ()
virtual QWidget * widgetToHighlight ()
virtual ~KviSelectorInterface ()
Protected Slots
void currentItemChanged (QTreeWidgetItem *it, QTreeWidgetItem *prev)
void customContextMenuRequested (const QPoint &pnt)
void ipV6CheckToggled (bool bEnabled)
void newProxy ()
void removeCurrent ()
Protected Slots inherited from KviOptionsWidget
void childOptionsWidgetDestroyed ()
Protected Attributes
QMenu * m_pContextPopup
KviIpEditor * m_pIpEditor
QLabel * m_pIpLabel
QCheckBox * m_pIPv6Check
ProxyOptionsTreeWidgetItem * m_pLastEditedItem
QLineEdit * m_pPassEdit
QLabel * m_pPassLabel
QLineEdit * m_pPortEdit
QLabel * m_pPortLabel
QComboBox * m_pProtocolBox
QLabel * m_pProtocolLabel
QLineEdit * m_pProxyEdit
QLabel * m_pProxyLabel
QTreeWidget * m_pTreeWidget
KviBoolSelector * m_pUseProxySelector
QLineEdit * m_pUserEdit
QLabel * m_pUserLabel
Private Member Functions
void enableDisableUseProxySelector ()
void fillProxyList ()
void saveLastItem ()
Additional Inherited Members
Protected Member Functions inherited from KviOptionsWidget
void commitOptionsReset ()
void commitSelectors ()
Constructor & Destructor Documentation
OptionsWidget_proxy::OptionsWidget_proxy (QWidget * parent)
References __tr2qs_ctx(), KviOptionsWidget::addBoolSelector(), KviOptionsWidget::addGroupBox(), KviOptionsWidget::addWidgetToLayout(), connect(), KviOptionsWidget::createLayout(), currentItemChanged(), customContextMenuRequested(), fillProxyList(), g_pIconManager, KviIconManager::getSmallIcon(), KviProxy::getSupportedProtocolNames(), KviIpEditor::IPv4, ipV6CheckToggled(), KviOption_boolUseProxyHost, l, KviOptionsWidget::layout(), m_pContextPopup, m_pIpEditor, m_pIpLabel, m_pIPv6Check, m_pLastEditedItem, m_pPassEdit, m_pPassLabel, m_pPortEdit, m_pPortLabel, m_pProtocolBox, m_pProtocolLabel, m_pProxyEdit, m_pProxyLabel, m_pTreeWidget, m_pUseProxySelector, m_pUserEdit, m_pUserLabel, KviOptionsWidget::mergeTip(), newProxy(), KviIconManager::NewProxy, KviIconManager::Remove, and removeCurrent().
OptionsWidget_proxy::~OptionsWidget_proxy () default
Member Function Documentation
void OptionsWidget_proxy::commit (void) virtual
Reimplemented from KviOptionsWidget.
References KviProxyDataBase::clear(), KviOptionsWidget::commit(), KviProxyDataBase::currentProxy(), KviPointerList< T >::first(), g_pProxyDataBase, i, KviProxyDataBase::insertProxy(), m_pLastEditedItem, ProxyOptionsTreeWidgetItem::m_pProxyData, m_pTreeWidget, KviProxyDataBase::proxyList(), saveLastItem(), and KviProxyDataBase::setCurrentProxy().
void OptionsWidget_proxy::currentItemChanged (QTreeWidgetItem * it, QTreeWidgetItem * prev) protected slot
References enableDisableUseProxySelector(), KviCString::Format, i, KviIpEditor::IPv4, KviIpEditor::IPv6, KviProxy::isIPv6(), kvi_strEqualCI(), m_pIpEditor, m_pIpLabel, m_pIPv6Check, m_pLastEditedItem, m_pPassEdit, m_pPassLabel, m_pPortEdit, m_pPortLabel, m_pProtocolBox, m_pProtocolLabel, ProxyOptionsTreeWidgetItem::m_pProxyData, m_pProxyEdit, m_pProxyLabel, m_pUserEdit, m_pUserLabel, KviProxy::m_szHostname, KviProxy::m_szIp, KviProxy::m_szPass, KviProxy::m_szUser, KviProxy::m_uPort, KviProxy::protocolName(), KviCString::ptr(), saveLastItem(), KviIpEditor::setAddress(), KviIpEditor::setAddressType(), and KviIpEditor::setEnabled().
Referenced by fillProxyList(), OptionsWidget_proxy(), and removeCurrent().
void OptionsWidget_proxy::customContextMenuRequested (const QPoint & pnt) protected slot
References __tr2qs_ctx(), g_pIconManager, KviIconManager::getSmallIcon(), m_pContextPopup, m_pTreeWidget, newProxy(), KviIconManager::NewProxy, KviIconManager::Remove, and removeCurrent().
Referenced by OptionsWidget_proxy().
void OptionsWidget_proxy::enableDisableUseProxySelector () private
References m_pTreeWidget, m_pUseProxySelector, and KviBoolSelector::setEnabled().
Referenced by currentItemChanged(), and fillProxyList().
void OptionsWidget_proxy::fillProxyList () private
References currentItemChanged(), KviProxyDataBase::currentProxy(), enableDisableUseProxySelector(), KviPointerList< T >::first(), g_pIconManager, g_pProxyDataBase, KviIconManager::getSmallIcon(), l, m_pTreeWidget, KviPointerList< T >::next(), p, KviIconManager::Proxy, and KviProxyDataBase::proxyList().
Referenced by OptionsWidget_proxy().
void OptionsWidget_proxy::ipV6CheckToggled (bool bEnabled) protected slot
References KviIpEditor::IPv4, KviIpEditor::IPv6, m_pIpEditor, and KviIpEditor::setAddressType().
Referenced by OptionsWidget_proxy().
void OptionsWidget_proxy::newProxy () protected slot
References g_pIconManager, KviIconManager::getSmallIcon(), m_pTreeWidget, and KviIconManager::Proxy.
Referenced by customContextMenuRequested(), and OptionsWidget_proxy().
void OptionsWidget_proxy::removeCurrent () protected slot
References currentItemChanged(), m_pLastEditedItem, and m_pTreeWidget.
Referenced by customContextMenuRequested(), and OptionsWidget_proxy().
void OptionsWidget_proxy::saveLastItem () private
References KviIpEditor::address(), KviQString::equalCI(), KviIpEditor::hasEmptyFields(), KviCString::isEmpty(), KviNetUtils::isValidStringIp(), KviProxy::m_bIsIPv6, m_pIpEditor, m_pIPv6Check, m_pLastEditedItem, m_pPassEdit, m_pPortEdit, m_pProtocolBox, ProxyOptionsTreeWidgetItem::m_pProxyData, m_pProxyEdit, m_pUserEdit, KviProxy::m_szHostname, KviProxy::m_szIp, KviProxy::m_szPass, KviProxy::m_szUser, KviProxy::m_uPort, KviCString::ptr(), KviProxy::setNamedProtocol(), KviCString::toUInt(), and uPort.
Referenced by commit(), and currentItemChanged().
Member Data Documentation
QMenu* OptionsWidget_proxy::m_pContextPopup protected
Referenced by customContextMenuRequested(), and OptionsWidget_proxy().
KviIpEditor* OptionsWidget_proxy::m_pIpEditor protected
Referenced by currentItemChanged(), ipV6CheckToggled(), OptionsWidget_proxy(), and saveLastItem().
QLabel* OptionsWidget_proxy::m_pIpLabel protected
Referenced by currentItemChanged(), and OptionsWidget_proxy().
QCheckBox* OptionsWidget_proxy::m_pIPv6Check protected
Referenced by currentItemChanged(), OptionsWidget_proxy(), and saveLastItem().
ProxyOptionsTreeWidgetItem* OptionsWidget_proxy::m_pLastEditedItem protected
Referenced by commit(), currentItemChanged(), OptionsWidget_proxy(), removeCurrent(), and saveLastItem().
QLineEdit* OptionsWidget_proxy::m_pPassEdit protected
Referenced by currentItemChanged(), OptionsWidget_proxy(), and saveLastItem().
QLabel* OptionsWidget_proxy::m_pPassLabel protected
Referenced by currentItemChanged(), and OptionsWidget_proxy().
QLineEdit* OptionsWidget_proxy::m_pPortEdit protected
Referenced by currentItemChanged(), OptionsWidget_proxy(), and saveLastItem().
QLabel* OptionsWidget_proxy::m_pPortLabel protected
Referenced by currentItemChanged(), and OptionsWidget_proxy().
QComboBox* OptionsWidget_proxy::m_pProtocolBox protected
Referenced by currentItemChanged(), OptionsWidget_proxy(), and saveLastItem().
QLabel* OptionsWidget_proxy::m_pProtocolLabel protected
Referenced by currentItemChanged(), and OptionsWidget_proxy().
QLineEdit* OptionsWidget_proxy::m_pProxyEdit protected
Referenced by currentItemChanged(), OptionsWidget_proxy(), and saveLastItem().
QLabel* OptionsWidget_proxy::m_pProxyLabel protected
Referenced by currentItemChanged(), and OptionsWidget_proxy().
QTreeWidget* OptionsWidget_proxy::m_pTreeWidget protected
Referenced by commit(), customContextMenuRequested(), enableDisableUseProxySelector(), fillProxyList(), newProxy(), OptionsWidget_proxy(), and removeCurrent().
KviBoolSelector* OptionsWidget_proxy::m_pUseProxySelector protected
Referenced by enableDisableUseProxySelector(), and OptionsWidget_proxy().
QLineEdit* OptionsWidget_proxy::m_pUserEdit protected
Referenced by currentItemChanged(), OptionsWidget_proxy(), and saveLastItem().
QLabel* OptionsWidget_proxy::m_pUserLabel protected
Referenced by currentItemChanged(), and OptionsWidget_proxy().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_proxy.h
src/modules/options/OptionsWidget_proxy.cpp