KVIrc: KviPasswordSelector Class Reference
KviPasswordSelector Class Reference
#include <KviSelectors.h>
Public Slots
virtual void setEnabled (bool bEnabled)
Public Member Functions
virtual void commit ()
KviPasswordSelector (QWidget *par, const QString &txt, QString *pOption, bool bEnabled)
void setMinimumLabelWidth (unsigned int uWidth)
void setText (const QString &text)
void setValidator (QValidator *v)
~KviPasswordSelector ()
Public Member Functions inherited from KviTalHBox
void addSpacing (int iSpace)
Adds a non-stretchable spacing item.
void addStretch (int iStretch)
Adds the stretch factor.
KviTalHBox (QWidget *pParent, char *pcName=0)
Constructs an horizontal box object.
void setAlignment (Qt::Alignment alignment)
Sets the alignment of the box.
void setAlignment (QWidget *pChild, Qt::Alignment alignment)
Sets the alignment of the box.
void setMargin (int iMargin)
Sets the margin of the box.
void setSpacing (int iSpace)
Sets the spacing of the box.
void setStretchFactor (QWidget *pChild, int iStretch)
Sets the stretch factor for an object.
~KviTalHBox ()
Destroys an horizontal box object.
Public Member Functions inherited from KviSelectorInterface
KviSelectorInterface ()
virtual ~KviSelectorInterface ()
Protected Slots
void checkToggled (int state)
Protected Member Functions
QString textForSearch ()
QWidget * widgetToHighlight ()
Protected Member Functions inherited from KviTalHBox
virtual void childEvent (QChildEvent *e)
Protected Attributes
QCheckBox * m_pCheckBox
QLabel * m_pLabel
QLineEdit * m_pLineEdit
QString * m_pOption
Constructor & Destructor Documentation
KviPasswordSelector::KviPasswordSelector (QWidget * par, const QString & txt, QString * pOption, bool bEnabled)
References KviTalHBox::addSpacing(), checkToggled(), connect(), m_pCheckBox, m_pLabel, m_pLineEdit, m_pOption, setEnabled(), KviTalHBox::setMargin(), KviTalHBox::setSpacing(), and KviTalHBox::setStretchFactor().
KviPasswordSelector::~KviPasswordSelector ()
Member Function Documentation
void KviPasswordSelector::checkToggled (int state) protected slot
References m_pLineEdit, and Normal.
Referenced by KviPasswordSelector().
void KviPasswordSelector::commit (void) virtual
Reimplemented from KviSelectorInterface.
References m_pLineEdit, and m_pOption.
void KviPasswordSelector::setEnabled (bool bEnabled) virtual slot
References m_pCheckBox, m_pLabel, and m_pLineEdit.
Referenced by KviPasswordSelector().
void KviPasswordSelector::setMinimumLabelWidth (unsigned int uWidth) inline
void KviPasswordSelector::setText (const QString & text)
References m_pLineEdit.
void KviPasswordSelector::setValidator (QValidator * v) inline
QString KviPasswordSelector::textForSearch () inline protected virtual
Reimplemented from KviSelectorInterface.
QWidget* KviPasswordSelector::widgetToHighlight () inline protected virtual
Reimplemented from KviSelectorInterface.
Member Data Documentation
QCheckBox* KviPasswordSelector::m_pCheckBox protected
Referenced by KviPasswordSelector(), and setEnabled().
QLabel* KviPasswordSelector::m_pLabel protected
Referenced by KviPasswordSelector(), and setEnabled().
QLineEdit* KviPasswordSelector::m_pLineEdit protected
Referenced by checkToggled(), commit(), KviPasswordSelector(), setEnabled(), and setText().
QString* KviPasswordSelector::m_pOption protected
Referenced by commit(), and KviPasswordSelector().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviSelectors.h
src/kvirc/ui/KviSelectors.cpp