KVIrc: KviIrcSocket Class Reference
KviIrcSocket Class Reference
This class is the lowest level of the KVIrc networking stack.
#include <KviIrcSocket.h>
Public Types
enum SocketState {
Idle, Connecting, ProxyLogin, ProxyHttpError,
Connected, ProxyFinalV4, ProxyFinalV5, ProxyFinalHttp,
ProxySelectAuthMethodV5, ProxyUserPassV5, SSLHandshake
}
Public Member Functions
void abort ()
Aborts the connection.
void clearOutputQueue (bool bPrivateMessagesOnly)
Clears the output queue.
KviConsoleWindow * console ()
Returns the console.
bool getLocalHostIp (QString &szIp, bool bIPv6)
Gets the localhost IP.
unsigned int id ()
Returns the id of the socket.
bool isConnected ()
Returns true if the socket is connected.
KviIrcSocket (KviIrcLink *pLink)
Constructs the IRC socket object.
int lastError ()
Returns the last error.
KviIrcLink * link ()
Returns the link.
unsigned int outputQueueSize ()
Returns the current size of the output queue.
unsigned int readBytes ()
Returns the number of bytes read.
bool sendPacket (KviDataBuffer *pData)
Returns true if the packet is sent to the socket.
unsigned int sentBytes ()
Returns the number of bytes sent.
unsigned int sentPackets ()
Returns the number of packets sent.
KviError::Code startConnection (KviIrcServer *pServer, KviProxy *pProxy=0, const char *pcBindAddress=0)
Starts the connection.
SocketState state ()
Returns the state of the socket.
bool usingSSL ()
Returns true if the socket is a Secure Socket Layer (SSL)
~KviIrcSocket ()
Destroys the IRC socket object.
Protected Slots
void connectionTimedOut ()
Called when the connection timeouts.
void doSSLHandshake (int)
Starts the SSL handshake.
void flushSendQueue ()
Attempts to send as much as possible to the server.
void readData (int)
Called when the read notifier is enabled.
void readHttpProxyErrorData (int)
Called when the proxy read notifier encounters an error.
void readProxyData (int)
Called when the proxy read notifier is enabled.
void writeNotifierFired (int)
Called when the write notifier is enabled.
Protected Member Functions
void connectedToIrcServer ()
Called when the connection to the irc server has been established.
void connectedToProxy ()
Called when the connection to the proxy has been established.
void connectionEstabilished ()
Called when the connection has been estabilished.
void free_msgEntry (KviIrcSocketMsgEntry *e)
Removes the message entry.
void handleInvalidSocketRead (int iReadLength)
Checks if the socket error is a transient error.
void linkUp ()
Connection established. Sets the link up.
void proxyAuthUserPassV5 ()
Starts the negotiation of user/pass for the proxy.
void proxyHandleHttpFinalReply (const char *pcBuffer, int iBufLen)
Gets the final HTTP reply and handles it.
void proxyHandleV4FinalReply (unsigned char cReply)
Gets the final SOCKSv4 reply and handles it.
void proxyHandleV5AuthReply (unsigned char cReply)
Gets the authentication reply and handles it.
void proxyHandleV5FinalReply (unsigned char cReply)
Gets the final SOCKSv5 reply and handles it.
void proxyHandleV5MethodReply (unsigned char cReply)
Gets the method selection reply and handles it.
void proxyLoginHttp ()
Called to login to an HTTP proxy.
void proxyLoginV4 ()
Called to login to a SOCKSv4 proxy.
void proxyLoginV5 ()
Called to login to a SOCKSv5 proxy.
void proxySendTargetDataV5 ()
Sends the request details.
virtual void queue_insertMessage (KviIrcSocketMsgEntry *pMsg)
Appends a KviIrcSocketMsgEntry to the tail of the message queue.
void queue_removeAllMessages ()
Removes all messages from the queue.
bool queue_removeMessage ()
Removes a message from the head of the queue.
void queue_removePrivateMessages ()
Removes private messages from the queue.
void raiseError (KviError::Code eError)
Raises an error.
virtual void reset ()
Resets the connection.
bool sendRawData (const char *pcBuffer, int iBufLen)
Sends raw data to the socket.
virtual void setState (SocketState state)
Sets the state of the socket.
Protected Attributes
bool m_bInProcessData
KviError::Code m_eLastError
KviConsoleWindow * m_pConsole
QTimer * m_pFlushTimer
KviIrcServer * m_pIrcServer
KviIrcLink * m_pLink
KviProxy * m_pProxy
QSocketNotifier * m_pRsn
KviIrcSocketMsgEntry * m_pSendQueueHead
KviIrcSocketMsgEntry * m_pSendQueueTail
QTimer * m_pTimeoutTimer
QSocketNotifier * m_pWsn
kvi_socket_t m_sock
SocketState m_state
struct timeval m_tAntiFloodLastMessageTime
unsigned int m_uId
unsigned int m_uReadBytes
unsigned int m_uSentBytes
unsigned int m_uSentPackets
Private Member Functions
void outputProxyError (const QString &szMsg)
Outputs a proxy error.
void outputProxyMessage (const QString &szMsg)
Outputs a proxy message.
void outputSocketError (const QString &szMsg)
Outputs a socket error.
void outputSocketMessage (const QString &szMsg)
Outputs a socket message.
void outputSocketWarning (const QString &szMsg)
Outputs a socket warning.
void outputSSLError (const QString &szMsg)
Outputs a SSL error.
void outputSSLMessage (const QString &szMsg)
Outputs a SSL message.
Detailed Description
This class is the lowest level of the KVIrc networking stack.
It sends and receives raw data packets from the underlying system socket. It should output only verbose "progress" messages.
Member Enumeration Documentation
enum KviIrcSocket::SocketState
Enumerator:
Idle
Socket idling
Connecting
Socket connecting
ProxyLogin
Socket loggin in to a proxy
ProxyHttpError
Socket error on http proxy
Connected
Socket connected
ProxyFinalV4
Socket received the final proxy v4 reply
ProxyFinalV5
Socket received the final proxy v5 reply
ProxyFinalHttp
Socket received the final proxy http reply
ProxySelectAuthMethodV5
Socket received v5 method select reply
ProxyUserPassV5
Socket received user/pass reply
SSLHandshake
Socket is doing the SSL handshake
Constructor & Destructor Documentation
KviIrcSocket::KviIrcSocket (KviIrcLink * pLink)
Constructs the IRC socket object.
Parameters:
pLink The middle networking stack class
Returns:
KviIrcSocket
References connect(), KviIrcLink::console(), flushSendQueue(), g_uNextIrcLinkId, Idle, KVI_INVALID_SOCKET, KVI_OPTION_UINT, KviOption_uintSocketQueueFlushTimeout, m_bInProcessData, m_eLastError, m_pConsole, m_pFlushTimer, m_pIrcServer, m_pLink, m_pProxy, m_pRsn, m_pSendQueueHead, m_pSendQueueTail, m_pTimeoutTimer, m_pWsn, m_sock, m_state, m_tAntiFloodLastMessageTime, m_uId, m_uReadBytes, m_uSentBytes, m_uSentPackets, and KviError::Success.
KviIrcSocket::~KviIrcSocket ()
Destroys the IRC socket object.
References m_pFlushTimer, and reset().
Member Function Documentation
void KviIrcSocket::abort ()
Aborts the connection.
Returns:
void
References Connected, flushSendQueue(), m_state, KviError::OperationAborted, raiseError(), and reset().
Referenced by KviIrcLink::abort().
void KviIrcSocket::clearOutputQueue (bool bPrivateMessagesOnly)
Clears the output queue.
Parameters:
bPrivateMessagesOnly Whether to clear only private messages
Returns:
void
References queue_removeAllMessages(), and queue_removePrivateMessages().
Referenced by KviIrcLink::clearOutputQueue().
void KviIrcSocket::connectedToIrcServer () [protected]
Called when the connection to the irc server has been established.
Returns:
void
References linkUp(), m_pIrcServer, and KviIrcServer::useSSL().
Referenced by connectionEstabilished(), proxyHandleHttpFinalReply(), proxyHandleV4FinalReply(), and proxyHandleV5FinalReply().
void KviIrcSocket::connectedToProxy () [protected]
Called when the connection to the proxy has been established.
Returns:
void
References connect(), KviProxy::Http, m_pProxy, m_pRsn, m_sock, KviProxy::protocol(), ProxyLogin, proxyLoginHttp(), proxyLoginV4(), proxyLoginV5(), readProxyData(), setState(), and KviProxy::Socks5.
Referenced by connectionEstabilished().
void KviIrcSocket::connectionEstabilished () [protected]
Called when the connection has been estabilished.
If it's a proxy we need to perform the login operations, otherwise we're connected to the irc server
Returns:
void
References connectedToIrcServer(), connectedToProxy(), KVI_INVALID_SOCKET, m_pProxy, and m_sock.
Referenced by writeNotifierFired().
void KviIrcSocket::connectionTimedOut () [protected, slot]
Called when the connection timeouts.
Returns:
void
References KviError::ConnectionTimedOut, raiseError(), and reset().
Referenced by startConnection().
KviConsoleWindow* KviIrcSocket::console () [inline]
Returns the console.
Returns:
KviConsoleWindow *
void KviIrcSocket::doSSLHandshake (int) [protected, slot]
Starts the SSL handshake.
Returns:
void
References connect(), KVI_ASSERT, kvi_socket_error(), kvi_socket_recoverableError(), linkUp(), m_pRsn, m_pWsn, m_sock, raiseError(), KviError::RemoteEndClosedConnection, reset(), KviError::SSLError, KviError::Success, KviError::translateSystemError(), and KviError::UnknownError.
void KviIrcSocket::flushSendQueue () [protected, slot]
Attempts to send as much as possible to the server.
If fails (happens only on really lagged servers) calls itself with a QTimer shot after KVI_OPTION_UINT(KviOption_uintSocketQueueFlushTimeout) ms to retry again...
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, KviDataBuffer::data(), KVI_ASSERT, kvi_gettimeofday(), KVI_OPTION_BOOL, KVI_OPTION_UINT, kvi_socket_error(), kvi_socket_send(), KviOption_boolLimitOutgoingTraffic, KviOption_uintOutgoingTrafficLimitUSeconds, KviOption_uintSocketQueueFlushTimeout, m_pFlushTimer, m_pSendQueueHead, m_sock, m_state, m_tAntiFloodLastMessageTime, m_uSentBytes, m_uSentPackets, outputSocketWarning(), _KviIrcSocketMsgEntry::pData, queue_removeMessage(), raiseError(), KviError::RemoteEndClosedConnection, KviDataBuffer::remove(), reset(), KviDataBuffer::size(), KviError::SSLError, and KviError::translateSystemError().
Referenced by abort(), KviIrcSocket(), readData(), sendPacket(), and sendRawData().
void KviIrcSocket::free_msgEntry (KviIrcSocketMsgEntry * e) [protected]
Removes the message entry.
Parameters:
e The entry
Returns:
void
References KviMemory::free(), and _KviIrcSocketMsgEntry::pData.
Referenced by queue_removePrivateMessages().
bool KviIrcSocket::getLocalHostIp (QString & szIp, bool bIPv6)
Gets the localhost IP.
Parameters:
szIp The source IP address
bIPv6 Whether to use IPv6 sockets
Returns:
bool
References KviNetUtils::binaryIpToStringIp(), Connected, kvi_socket_getsockname(), m_sock, m_state, and KviOsInfo::name().
Referenced by dcc_kvs_get_listen_ip_address().
void KviIrcSocket::handleInvalidSocketRead (int iReadLength) [protected]
Checks if the socket error is a transient error.
If it is not a transient error it resets the socket and fires the appropriate event. Otherwise it does nothing.
Parameters:
iReadLength The number of bytes read
Returns:
void
References KVI_ASSERT, kvi_socket_error(), raiseError(), KviError::RemoteEndClosedConnection, reset(), and KviError::translateSystemError().
Referenced by readData(), readHttpProxyErrorData(), and readProxyData().
unsigned int KviIrcSocket::id () [inline]
Returns the id of the socket.
Returns:
unsigned int
bool KviIrcSocket::isConnected () [inline]
Returns true if the socket is connected.
Returns:
bool
int KviIrcSocket::lastError () [inline]
Returns the last error.
Returns:
int
Referenced by KviIrcLink::socketStateChange().
KviIrcLink* KviIrcSocket::link () [inline]
Returns the link.
Returns:
KviIrcLink *
void KviIrcSocket::linkUp () [protected]
Connection established. Sets the link up.
Returns:
void
References connect(), Connected, KVI_INVALID_SOCKET, m_pRsn, m_pWsn, m_sock, readData(), and setState().
Referenced by connectedToIrcServer(), and doSSLHandshake().
void KviIrcSocket::outputProxyError (const QString & szMsg) [private]
Outputs a proxy error.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SOCKETERROR, m_pConsole, and KviWindow::output().
Referenced by proxyHandleHttpFinalReply().
void KviIrcSocket::outputProxyMessage (const QString & szMsg) [private]
Outputs a proxy message.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SOCKETMESSAGE, m_pConsole, and KviWindow::output().
Referenced by proxyHandleHttpFinalReply(), proxyHandleV4FinalReply(), proxyHandleV5AuthReply(), proxyHandleV5FinalReply(), proxyHandleV5MethodReply(), proxyLoginHttp(), proxyLoginV4(), proxyLoginV5(), and readHttpProxyErrorData().
unsigned int KviIrcSocket::outputQueueSize ()
Returns the current size of the output queue.
Returns:
unsigned int
References m_pSendQueueTail, and _KviIrcSocketMsgEntry::next_ptr.
Referenced by KviIrcLink::outputQueueSize().
void KviIrcSocket::outputSocketError (const QString & szMsg) [private]
Outputs a socket error.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SOCKETERROR, m_pConsole, and KviWindow::output().
Referenced by raiseError().
void KviIrcSocket::outputSocketMessage (const QString & szMsg) [private]
Outputs a socket message.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SOCKETMESSAGE, m_pConsole, and KviWindow::output().
Referenced by raiseError(), and startConnection().
void KviIrcSocket::outputSocketWarning (const QString & szMsg) [private]
Outputs a socket warning.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SOCKETWARNING, m_pConsole, and KviWindow::output().
Referenced by flushSendQueue(), and startConnection().
void KviIrcSocket::outputSSLError (const QString & szMsg) [private]
Outputs a SSL error.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SSL, m_pConsole, and KviWindow::output().
void KviIrcSocket::outputSSLMessage (const QString & szMsg) [private]
Outputs a SSL message.
Parameters:
szMsg The message :)
Returns:
void
References __tr2qs, KVI_OUT_SSL, m_pConsole, and KviWindow::output().
void KviIrcSocket::proxyAuthUserPassV5 () [protected]
Starts the negotiation of user/pass for the proxy.
Returns:
void
References m_pProxy, KviMemory::move(), KviProxy::pass(), KviProxy::passLen(), ProxyUserPassV5, sendRawData(), setState(), KviProxy::user(), and KviProxy::userLen().
Referenced by proxyHandleV5MethodReply().
void KviIrcSocket::proxyHandleHttpFinalReply (const char * pcBuffer, int iBufLen) [protected]
Gets the final HTTP reply and handles it.
Parameters:
pcBuffer The buffer containing the proxy reply
iBufLen Size of the buffer containing the proxy reply
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, connect(), connectedToIrcServer(), KviCString::cutFromFirst(), KviWindow::decodeText(), KviCString::findFirstIdx(), kvi_strEqualCIN(), m_pConsole, m_pRsn, m_pWsn, m_sock, outputProxyError(), outputProxyMessage(), ProxyHttpError, KviCString::ptr(), readHttpProxyErrorData(), setState(), and KviCString::trim().
Referenced by readProxyData().
void KviIrcSocket::proxyHandleV4FinalReply (unsigned char cReply) [protected]
Gets the final SOCKSv4 reply and handles it.
Parameters:
cReply The proxy reply
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, connectedToIrcServer(), outputProxyMessage(), KviError::ProxyReply91RequestFailed, KviError::ProxyReply92IdentFailed, KviError::ProxyReply93IdentNotMatching, raiseError(), reset(), and KviError::UnrecognizedProxyReply.
Referenced by readProxyData().
void KviIrcSocket::proxyHandleV5AuthReply (unsigned char cReply) [protected]
Gets the authentication reply and handles it.
Parameters:
cReply The proxy reply
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, outputProxyMessage(), KviError::ProxyAuthFailed, proxySendTargetDataV5(), raiseError(), and reset().
Referenced by readProxyData().
void KviIrcSocket::proxyHandleV5FinalReply (unsigned char cReply) [protected]
Gets the final SOCKSv5 reply and handles it.
Parameters:
cReply The proxy reply
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, connectedToIrcServer(), outputProxyMessage(), KviError::ProxyReply01GeneralSOCKSFailure, KviError::ProxyReply02ConnectionNotAllowed, KviError::ProxyReply03NetworkUnreachable, KviError::ProxyReply04HostUnreachable, KviError::ProxyReply05ConnectionRefused, KviError::ProxyReply06TTLExpired, KviError::ProxyReply07CommandNotSupported, KviError::ProxyReply08AddressTypeNotSupported, KviError::ProxyReply09InvalidAddress, raiseError(), reset(), and KviError::UnrecognizedProxyReply.
Referenced by readProxyData().
void KviIrcSocket::proxyHandleV5MethodReply (unsigned char cReply) [protected]
Gets the method selection reply and handles it.
Parameters:
cReply The proxy reply
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, outputProxyMessage(), proxyAuthUserPassV5(), KviError::ProxyNoAcceptableAuthMethod, proxySendTargetDataV5(), raiseError(), reset(), and KviError::UnrecognizedProxyReply.
Referenced by readProxyData().
void KviIrcSocket::proxyLoginHttp () [protected]
Called to login to an HTTP proxy.
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, KviCString::append(), KviCString::bufferToBase64(), KviCString::Format, KviProxy::hasUser(), KviIrcServer::hostName(), KviCString::len(), m_pIrcServer, m_pProxy, outputProxyMessage(), KviProxy::pass(), KviIrcServer::port(), ProxyFinalHttp, KviCString::ptr(), sendRawData(), setState(), and KviProxy::user().
Referenced by connectedToProxy().
void KviIrcSocket::proxyLoginV4 () [protected]
Called to login to a SOCKSv4 proxy.
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, KviCString::append(), KviCString::hasData(), KviProxy::hasPass(), KviIrcServer::ip(), KviCString::len(), m_pIrcServer, m_pProxy, KviMemory::move(), KviProxy::normalizeUserAndPass(), outputProxyMessage(), KviProxy::pass(), KviIrcServer::port(), ProxyFinalV4, KviCString::ptr(), sendRawData(), setState(), KviNetUtils::stringIpToBinaryIp(), and KviProxy::user().
Referenced by connectedToProxy().
void KviIrcSocket::proxyLoginV5 () [protected]
Called to login to a SOCKSv5 proxy.
Returns:
void
References __tr2qs, _OUTPUT_VERBOSE, KviProxy::hasPass(), KviProxy::hasUser(), m_pProxy, KviProxy::normalizeUserAndPass(), outputProxyMessage(), ProxySelectAuthMethodV5, sendRawData(), and setState().
Referenced by connectedToProxy().
void KviIrcSocket::proxySendTargetDataV5 () [protected]
Sends the request details.
Returns:
void
References KviMemory::allocate(), KviIrcServer::cacheIp(), KviMemory::free(), KviIrcServer::hostName(), KviIrcServer::ip(), KviIrcServer::isIPv6(), KviNetUtils::isValidStringIp(), m_pIrcServer, KviMemory::move(), KviIrcServer::port(), ProxyFinalV5, sendRawData(), setState(), and KviNetUtils::stringIpToBinaryIp().
Referenced by proxyHandleV5AuthReply(), and proxyHandleV5MethodReply().
void KviIrcSocket::queue_insertMessage (KviIrcSocketMsgEntry * pMsg) [protected, virtual]
Appends a KviIrcSocketMsgEntry to the tail of the message queue.
The pMsg for this message is set to 0.
Parameters:
pMsg The message to append to the queue
Returns:
void
References KVI_ASSERT, m_pSendQueueHead, m_pSendQueueTail, and _KviIrcSocketMsgEntry::next_ptr.
Referenced by sendPacket(), and sendRawData().
void KviIrcSocket::queue_removeAllMessages () [protected]
Removes all messages from the queue.
Returns:
void
References m_pSendQueueHead, and queue_removeMessage().
Referenced by clearOutputQueue(), and reset().
bool KviIrcSocket::queue_removeMessage () [protected]
Removes a message from the head of the queue.
Returns:
bool
References KviMemory::free(), KVI_ASSERT, m_pSendQueueHead, m_pSendQueueTail, _KviIrcSocketMsgEntry::next_ptr, and _KviIrcSocketMsgEntry::pData.
Referenced by flushSendQueue(), and queue_removeAllMessages().
void KviIrcSocket::queue_removePrivateMessages () [protected]
Removes private messages from the queue.
Returns:
void
References KviDataBuffer::data(), free_msgEntry(), kvi_strEqualCIN(), m_pSendQueueHead, m_pSendQueueTail, _KviIrcSocketMsgEntry::next_ptr, _KviIrcSocketMsgEntry::pData, and KviDataBuffer::size().
Referenced by clearOutputQueue().
void KviIrcSocket::raiseError (KviError::Code eError) [protected]
Raises an error.
Parameters:
eError The error to raise
Returns:
void
References KviError::getDescription(), m_eLastError, m_state, outputSocketError(), outputSocketMessage(), ProxyHttpError, and KviError::RemoteEndClosedConnection.
Referenced by abort(), connectionTimedOut(), doSSLHandshake(), flushSendQueue(), handleInvalidSocketRead(), proxyHandleV4FinalReply(), proxyHandleV5AuthReply(), proxyHandleV5FinalReply(), proxyHandleV5MethodReply(), readData(), readProxyData(), and writeNotifierFired().
unsigned int KviIrcSocket::readBytes () [inline]
Returns the number of bytes read.
Returns:
unsigned int
void KviIrcSocket::readData (int) [protected, slot]
Called when the read notifier is enabled.
Returns:
void
References flushSendQueue(), handleInvalidSocketRead(), kvi_socket_recv(), m_bInProcessData, m_pLink, m_pRsn, m_pSendQueueHead, m_sock, m_uReadBytes, KviIrcLink::processData(), raiseError(), reset(), and KviError::SSLError.
Referenced by linkUp().
void KviIrcSocket::readHttpProxyErrorData (int) [protected, slot]
Called when the proxy read notifier encounters an error.
Returns:
void
References KviWindow::decodeText(), handleInvalidSocketRead(), kvi_socket_recv(), m_pConsole, m_sock, and outputProxyMessage().
Referenced by proxyHandleHttpFinalReply().
void KviIrcSocket::readProxyData (int) [protected, slot]
Called when the proxy read notifier is enabled.
Returns:
void
References handleInvalidSocketRead(), kvi_socket_recv(), m_sock, m_state, ProxyFinalHttp, ProxyFinalV4, ProxyFinalV5, proxyHandleHttpFinalReply(), proxyHandleV4FinalReply(), proxyHandleV5AuthReply(), proxyHandleV5FinalReply(), proxyHandleV5MethodReply(), ProxySelectAuthMethodV5, ProxyUserPassV5, raiseError(), reset(), and KviError::UnrecognizedProxyReply.
Referenced by connectedToProxy().
void KviIrcSocket::reset () [protected, virtual]
Resets the connection.
Returns:
void
References KVI_INVALID_SOCKET, kvi_socket_destroy(), kvi_socket_isValid(), m_bInProcessData, m_pFlushTimer, m_pIrcServer, m_pProxy, m_pRsn, m_pTimeoutTimer, m_pWsn, m_sock, m_tAntiFloodLastMessageTime, m_uReadBytes, m_uSentBytes, m_uSentPackets, queue_removeAllMessages(), and setState().
Referenced by abort(), connectionTimedOut(), doSSLHandshake(), flushSendQueue(), handleInvalidSocketRead(), proxyHandleV4FinalReply(), proxyHandleV5AuthReply(), proxyHandleV5FinalReply(), proxyHandleV5MethodReply(), readData(), readProxyData(), startConnection(), writeNotifierFired(), and ~KviIrcSocket().
bool KviIrcSocket::sendPacket (KviDataBuffer * pData)
Returns true if the packet is sent to the socket.
Parameters:
pData The source data packet
Returns:
bool
References KviMemory::allocate(), Connected, flushSendQueue(), m_bInProcessData, m_state, _KviIrcSocketMsgEntry::pData, and queue_insertMessage().
Referenced by KviIrcLink::sendPacket().
bool KviIrcSocket::sendRawData (const char * pcBuffer, int iBufLen) [protected]
Sends raw data to the socket.
Parameters:
pcBuffer The data buffer
iBufLen The size of the buffer
Returns:
bool
References KviMemory::allocate(), Connecting, KviDataBuffer::data(), flushSendQueue(), m_bInProcessData, m_state, KviMemory::move(), _KviIrcSocketMsgEntry::pData, and queue_insertMessage().
Referenced by proxyAuthUserPassV5(), proxyLoginHttp(), proxyLoginV4(), proxyLoginV5(), and proxySendTargetDataV5().
unsigned int KviIrcSocket::sentBytes () [inline]
Returns the number of bytes sent.
Returns:
unsigned int
unsigned int KviIrcSocket::sentPackets () [inline]
Returns the number of packets sent.
Returns:
unsigned int
void KviIrcSocket::setState (SocketState state) [protected, virtual]
Sets the state of the socket.
Parameters:
state The state :)
Returns:
void
References m_pLink, m_state, KviIrcLink::socketStateChange(), and state().
Referenced by connectedToProxy(), linkUp(), proxyAuthUserPassV5(), proxyHandleHttpFinalReply(), proxyLoginHttp(), proxyLoginV4(), proxyLoginV5(), proxySendTargetDataV5(), reset(), and startConnection().
KviError::Code KviIrcSocket::startConnection (KviIrcServer * pServer, KviProxy * pProxy = 0, const char * pcBindAddress = 0)
Starts the connection.
Parameters:
pServer The server where to connect to
pProxy The proxy to use during connection
pcBindAddress The address to bind the connection to
Returns:
int
References __tr2qs, _OUTPUT_VERBOSE, KviSockaddr::addressLength(), KviError::AnotherConnectionInProgress, KviError::AsyncSocketFailed, connect(), Connecting, connectionTimedOut(), KviProxy::Http, KviError::InvalidIpAddress, KviError::InvalidProxyAddress, KviIrcServer::ip(), KviProxy::ip(), KviIrcServer::isIPv6(), KviProxy::isIPv6(), KviNetUtils::isValidStringIp(), KVI_OPTION_UINT, kvi_socket_bind(), kvi_socket_connect(), kvi_socket_create(), kvi_socket_error(), kvi_socket_getsockopt(), KVI_SOCKET_PF_INET, KVI_SOCKET_PF_INET6, KVI_SOCKET_PROTO_TCP, kvi_socket_recoverableConnectError(), kvi_socket_setNonBlocking(), KVI_SOCKET_TYPE_STREAM, KviOption_uintIrcSocketTimeout, m_pIrcServer, m_pProxy, m_pTimeoutTimer, m_pWsn, m_sock, m_state, KviError::NoIPv6Support, KviError::NoSSLSupport, outputSocketMessage(), outputSocketWarning(), KviIrcServer::port(), KviProxy::port(), KviProxy::protocol(), reset(), setState(), KviSockaddr::socketAddress(), KviError::SocketCreationFailed, KviProxy::Socks4, KviProxy::Socks5, KviError::SocksV4LacksIPv6Support, KviError::Success, KviError::translateSystemError(), KviError::UnknownError, KviIrcServer::useSSL(), and writeNotifierFired().
Referenced by KviIrcLink::resolverTerminated().
SocketState KviIrcSocket::state () [inline]
Returns the state of the socket.
Returns:
SocketState
Referenced by KviIrcLink::processData(), setState(), and KviIrcLink::socketStateChange().
bool KviIrcSocket::usingSSL () [inline]
Returns true if the socket is a Secure Socket Layer (SSL)
Returns:
bool
Referenced by context_kvs_fnc_getSSLCertInfo().
void KviIrcSocket::writeNotifierFired (int) [protected, slot]
Called when the write notifier is enabled.
Returns:
void
References connectionEstabilished(), kvi_socket_getsockopt(), m_pTimeoutTimer, m_pWsn, m_sock, raiseError(), reset(), KviError::translateSystemError(), and KviError::UnknownError.
Referenced by startConnection().
Member Data Documentation
bool KviIrcSocket::m_bInProcessData [protected]
Referenced by KviIrcSocket(), readData(), reset(), sendPacket(), and sendRawData().
KviError::Code KviIrcSocket::m_eLastError [protected]
Referenced by KviIrcSocket(), and raiseError().
KviConsoleWindow* KviIrcSocket::m_pConsole [protected]
Referenced by KviIrcLink::console(), KviIrcSocket(), outputProxyError(), outputProxyMessage(), outputSocketError(), outputSocketMessage(), outputSocketWarning(), outputSSLError(), outputSSLMessage(), proxyHandleHttpFinalReply(), and readHttpProxyErrorData().
QTimer* KviIrcSocket::m_pFlushTimer [protected]
Referenced by flushSendQueue(), KviIrcSocket(), reset(), and ~KviIrcSocket().
KviIrcServer* KviIrcSocket::m_pIrcServer [protected]
Referenced by connectedToIrcServer(), KviIrcSocket(), proxyLoginHttp(), proxyLoginV4(), proxySendTargetDataV5(), reset(), and startConnection().
KviIrcLink* KviIrcSocket::m_pLink [protected]
Referenced by KviIrcSocket(), readData(), and setState().
KviProxy* KviIrcSocket::m_pProxy [protected]
Referenced by connectedToProxy(), connectionEstabilished(), KviIrcSocket(), proxyAuthUserPassV5(), proxyLoginHttp(), proxyLoginV4(), proxyLoginV5(), reset(), and startConnection().
QSocketNotifier* KviIrcSocket::m_pRsn [protected]
Referenced by connectedToProxy(), doSSLHandshake(), KviIrcSocket(), linkUp(), proxyHandleHttpFinalReply(), readData(), and reset().
KviIrcSocketMsgEntry* KviIrcSocket::m_pSendQueueHead [protected]
Referenced by flushSendQueue(), KviIrcSocket(), queue_insertMessage(), queue_removeAllMessages(), queue_removeMessage(), queue_removePrivateMessages(), and readData().
KviIrcSocketMsgEntry* KviIrcSocket::m_pSendQueueTail [protected]
Referenced by KviIrcSocket(), outputQueueSize(), queue_insertMessage(), queue_removeMessage(), and queue_removePrivateMessages().
QTimer* KviIrcSocket::m_pTimeoutTimer [protected]
Referenced by KviIrcSocket(), reset(), startConnection(), and writeNotifierFired().
QSocketNotifier* KviIrcSocket::m_pWsn [protected]
Referenced by doSSLHandshake(), KviIrcSocket(), linkUp(), proxyHandleHttpFinalReply(), reset(), startConnection(), and writeNotifierFired().
kvi_socket_t KviIrcSocket::m_sock [protected]
Referenced by connectedToProxy(), connectionEstabilished(), doSSLHandshake(), flushSendQueue(), getLocalHostIp(), KviIrcSocket(), linkUp(), proxyHandleHttpFinalReply(), readData(), readHttpProxyErrorData(), readProxyData(), reset(), startConnection(), and writeNotifierFired().
SocketState KviIrcSocket::m_state [protected]
Referenced by abort(), flushSendQueue(), getLocalHostIp(), KviIrcSocket(), raiseError(), readProxyData(), sendPacket(), sendRawData(), setState(), and startConnection().
struct timeval KviIrcSocket::m_tAntiFloodLastMessageTime [protected]
Referenced by flushSendQueue(), KviIrcSocket(), and reset().
unsigned int KviIrcSocket::m_uId [protected]
Referenced by KviIrcSocket().
unsigned int KviIrcSocket::m_uReadBytes [protected]
Referenced by KviIrcSocket(), readData(), and reset().
unsigned int KviIrcSocket::m_uSentBytes [protected]
Referenced by flushSendQueue(), KviIrcSocket(), and reset().
unsigned int KviIrcSocket::m_uSentPackets [protected]
Referenced by flushSendQueue(), KviIrcSocket(), and reset().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviIrcSocket.h
src/kvirc/kernel/KviIrcSocket.cpp