KVIrc: MessageListWidgetItem Class Reference
MessageListWidgetItem Class Reference
#include <OptionsWidget_message.h>
Public Member Functions
MessageListWidgetItem (MessageListWidget *l, int optId)
KviMessageTypeSettings * msgType ()
int optionId ()
~MessageListWidgetItem ()
Public Member Functions inherited from KviTalListWidgetItem
KviTalListWidgetItem ()
KviTalListWidgetItem (KviTalListWidget *pParent)
KviTalListWidgetItem (KviTalListWidget *pParent, QString &label)
KviTalListWidget * listWidget ()
virtual ~KviTalListWidgetItem ()
Private Attributes
int m_iOptId
KviMessageTypeSettings * m_pMsgType
Constructor & Destructor Documentation
MessageListWidgetItem::MessageListWidgetItem (MessageListWidget * l, int optId)
References __tr2qs_no_xgettext, g_msgtypeOptionsTable, g_pIconManager, KviIconManager::getSmallIcon(), KVI_MSGTYPE_OPTIONS_PREFIX_LEN, KVI_OPTION_MSGTYPE, m_iOptId, m_pMsgType, KviMessageTypeSettings::pixId(), and KviMessageTypeSettings::type().
MessageListWidgetItem::~MessageListWidgetItem ()
References m_pMsgType.
Member Function Documentation
KviMessageTypeSettings* MessageListWidgetItem::msgType () inline
References m_pMsgType.
Referenced by OptionsWidget_messageColors::commit(), OptionsWidget_messageColors::load(), OptionsWidget_messageColors::newIconSelected(), MessageListWidgetItemDelegate::paint(), OptionsWidget_messageColors::save(), and OptionsWidget_messageColors::saveLastItem().
int MessageListWidgetItem::optionId () inline
References m_iOptId.
Referenced by OptionsWidget_messageColors::commit(), OptionsWidget_messageColors::load(), and OptionsWidget_messageColors::save().
Member Data Documentation
int MessageListWidgetItem::m_iOptId private
Referenced by MessageListWidgetItem(), and optionId().
KviMessageTypeSettings* MessageListWidgetItem::m_pMsgType private
Referenced by MessageListWidgetItem(), msgType(), and ~MessageListWidgetItem().
The documentation for this class was generated from the following files:
src/modules/options/OptionsWidget_message.h
src/modules/options/OptionsWidget_message.cpp