KVIrc: KviKvsScriptEventHandler Class Reference
KviKvsScriptEventHandler Class Reference
#include <KviKvsEventHandler.h>
Public Member Functions
const QString & code ()
bool isEnabled ()
KviKvsScriptEventHandler (const QString &szHandlerName, const QString &szContextName, const QString &szCode, bool bEnabled=true)
const QString & name ()
KviKvsScript * script ()
void setEnabled (bool bEnabled)
virtual ~KviKvsScriptEventHandler ()
Public Member Functions inherited from KviKvsEventHandler
KviKvsEventHandler (Type t)
Type type ()
virtual ~KviKvsEventHandler ()
Static Public Member Functions
static KviKvsScriptEventHandler * createInstance (const QString &szHandlerName, const QString &szContextName, const QString &szCode, bool bEnabled=true)
Protected Attributes
bool m_bEnabled
KviKvsScript * m_pScript
QString m_szName
Protected Attributes inherited from KviKvsEventHandler
Type m_type
Additional Inherited Members
Public Types inherited from KviKvsEventHandler
enum Type { Script, Module }
Constructor & Destructor Documentation
KviKvsScriptEventHandler::KviKvsScriptEventHandler (const QString & szHandlerName, const QString & szContextName, const QString & szCode, bool bEnabled = true)
References m_pScript.
Referenced by createInstance().
KviKvsScriptEventHandler::~KviKvsScriptEventHandler () virtual
References m_pScript.
Member Function Documentation
const QString& KviKvsScriptEventHandler::code () inline
KviKvsScriptEventHandler * KviKvsScriptEventHandler::createInstance (const QString & szHandlerName, const QString & szContextName, const QString & szCode, bool bEnabled = true) static
References KviKvsScriptEventHandler().
Referenced by EventEditor::commit().
bool KviKvsScriptEventHandler::isEnabled () inline
Referenced by KviKvsCoreFunctions::KVSCF().
const QString& KviKvsScriptEventHandler::name () inline
KviKvsScript* KviKvsScriptEventHandler::script () inline
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviKvsScriptEventHandler::setEnabled (bool bEnabled) inline
Referenced by KviKvsEventManager::enableScriptAppHandler(), KviKvsEventManager::enableScriptRawHandler(), and KviKvsEventManager::loadRawEvents().
Member Data Documentation
bool KviKvsScriptEventHandler::m_bEnabled protected
KviKvsScript* KviKvsScriptEventHandler::m_pScript protected
Referenced by KviKvsScriptEventHandler(), and ~KviKvsScriptEventHandler().
QString KviKvsScriptEventHandler::m_szName protected
The documentation for this class was generated from the following files:
src/kvirc/kvs/event/KviKvsEventHandler.h
src/kvirc/kvs/event/KviKvsEventHandler.cpp