KVIrc: PackAddonSaveSelectionWidget Class Reference
PackAddonSaveSelectionWidget Class Reference
Wizard page for saving package.
#include <PackAddonDialog.h>
Public Member Functions
PackAddonSaveSelectionWidget (PackAddonDialog *pParent)
Create the wizard save page object.
~PackAddonSaveSelectionWidget ()
Destroys the wizard save page object.
Protected Member Functions
virtual void initializePage ()
Perform initial tasks before showing the widget.
Protected Attributes
KviFileSelector * m_pSavePathSelector
QString m_szFilePath
Detailed Description
Wizard page for saving package.
Constructor & Destructor Documentation
PackAddonSaveSelectionWidget::PackAddonSaveSelectionWidget (PackAddonDialog * pParent)
Create the wizard save page object.
Parameters:
pParent The parent widget
Returns:
PackAddonSaveSelectionWidget
References __tr2qs_ctx(), KviFileSelector::ChooseSaveFileName, KVI_FILTER_ADDON, m_pSavePathSelector, m_szFilePath, and KviFileSelector::VerticalLayout.
PackAddonSaveSelectionWidget::~PackAddonSaveSelectionWidget ()
Destroys the wizard save page object.
Member Function Documentation
void PackAddonSaveSelectionWidget::initializePage () [protected, virtual]
Perform initial tasks before showing the widget.
Returns:
void
References KviQString::ensureLastCharIs(), KVI_FILEEXTENSION_ADDONPACKAGE, KVI_PATH_SEPARATOR_CHAR, m_pSavePathSelector, and KviFileSelector::setTmpFile().
Member Data Documentation
KviFileSelector* PackAddonSaveSelectionWidget::m_pSavePathSelector [protected]
Referenced by initializePage(), and PackAddonSaveSelectionWidget().
QString PackAddonSaveSelectionWidget::m_szFilePath [protected]
Referenced by PackAddonSaveSelectionWidget().
The documentation for this class was generated from the following files:
src/modules/addon/PackAddonDialog.h
src/modules/addon/PackAddonDialog.cpp