KVIrc: DccVoiceWindow Class Reference
DccVoiceWindow Class Reference
#include <DccVoiceWindow.h>
Public Member Functions
DccVoiceWindow (DccDescriptor *dcc, const char *name)
~DccVoiceWindow ()
Public Member Functions inherited from DccWindow
virtual const char * dccMarshalOutputContextString ()
virtual KviWindow * dccMarshalOutputWindow ()
DccWindow (KviWindow::Type eType, const char *name, DccDescriptor *d)
DccDescriptor * descriptor ()
virtual DccThread * getSlaveThread ()
const DccMarshal * marshal ()
~DccWindow ()
Public Member Functions inherited from KviWindow
void activateSelf ()
virtual bool activityMeter (unsigned int *puActivityValue, unsigned int *puActivityTemperature)
virtual void applyOptions ()
virtual QFrame * buttonContainer ()
KviIrcConnection * connection ()
Returns the current IRC connection (if any)
KviConsoleWindow * console ()
Returns the console that this window belongs to.
KviIrcContext * context ()
void contextPopup ()
QString decodeText (const char *pcText)
virtual QTextCodec * defaultTextCodec ()
void delayedAutoRaise ()
void delayedClose ()
void demandAttention ()
Notify the window manager that this window demands attention.
QByteArray encodeText (const QString &szText)
void forceTextCodec (QTextCodec *pCodec)
virtual void getConfigGroupName (QString &szBuffer)
void getDefaultLogFileName (QString &szBuffer)
virtual void getWindowListTipText (QString &szBuffer)
bool hasAttention (AttentionLevel eLevel=VisibleAndActive)
Returns whether this window is the active one.
virtual bool highlightMe (unsigned int uValue)
virtual bool highlightMeter (unsigned int *puValue)
QString id ()
Returns the global ID of this window.
KviInput * input ()
void internalOutput (KviIrcView *pView, int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
bool isDocked ()
bool isMaximized ()
bool isMinimized ()
KviWindow (Type eType, const QString &szName, KviConsoleWindow *pConsole=0)
Constructs the window object.
const QString & lastLineOfText ()
const QString & lastMessageText ()
void listWindowTypes ()
virtual const QString & localNick ()
QTextEncoder * makeEncoder ()
KviMdiChild * mdiParent ()
Returns the mdiParent widget.
unsigned long int numericId ()
Returns the global ID of this window.
virtual void output (int iMsgType, const char *pcFormat,...)
virtual void output (int iMsgType, const kvi_wchar_t *pwFormat,...)
virtual void output (int iMsgType, const QString &szFmt,...)
virtual void outputNoFmt (int iMsgType, const char *pcText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const kvi_wchar_t *pwText, int iFlags=0)
virtual void outputNoFmt (int iMsgType, const QString &szText, int iFlags=0)
virtual KviWindow * outputProxy ()
virtual void ownAction (const QString &)
virtual void ownMessage (const QString &, bool=true)
virtual const QString & plainTextCaption ()
void setFixedCaption (const QString &szCaption)
void setProgress (int iProgress)
Sets the progress for the WindowList item.
bool setTextEncoding (const QString &szTextEncoding)
void setWindowName (const QString &szName)
Sets the name of the window.
KviTalSplitter * splitter ()
Returns the splitter of this window.
QTextCodec * textCodec ()
const QString & textEncoding ()
virtual void toggleButtonContainer ()
Type type () const
Returns the type of the window.
virtual const char * typeString ()
Returns a descriptive name of the window type.
void unhighlight ()
void updateBackgrounds (QObject *pObj=0)
virtual void updateCaption ()
virtual void updateIcon ()
KviIrcView * view () const
Returns the KviIrcView of this window.
KviWindowListItem * windowListItem ()
Returns the windowList item.
const QString & windowName ()
Returns the name of this window.
virtual ~KviWindow ()
Destroys the window object.
Public Member Functions inherited from DccMarshalOutputContext
DccMarshalOutputContext ()
virtual ~DccMarshalOutputContext ()
Protected Slots
void connected ()
void connectionInProgress ()
void handleMarshalError (KviError::Code eError)
void setMixerVolume (int)
void startOrStopTalking (bool bStart)
void updateInfo ()
Protected Member Functions
virtual bool event (QEvent *e)
virtual void fillCaptionBuffers ()
virtual void focusInEvent (QFocusEvent *)
virtual void getBaseLogFileName (QString &buffer)
int getMixerVolume (void) const
virtual QPixmap * myIconPtr ()
virtual void resizeEvent (QResizeEvent *e)
virtual QSize sizeHint () const
void startConnection ()
void startTalking ()
void stopTalking ()
virtual const QString & target ()
Protected Attributes
KviTalHBox * m_pHBox
QLabel * m_pInputLabel
QLabel * m_pOutputLabel
QLabel * m_pPlayingLabel
QLabel * m_pRecordingLabel
DccVoiceThread * m_pSlaveThread
QToolButton * m_pTalkButton
QTimer * m_pUpdateTimer
QSlider * m_pVolumeSlider
QString m_szTarget
Protected Attributes inherited from DccWindow
DccDescriptor * m_pDescriptor
DccMarshal * m_pMarshal
Protected Attributes inherited from KviWindow
bool m_bIsDocked
Type m_eType
KviTalHBox * m_pButtonBox
KviConsoleWindow * m_pConsole
QWidget * m_pFocusHandler
QToolButton * m_pHideToolsButton
KviInput * m_pInput
KviIrcView * m_pIrcView
QWidget * m_pLastFocusedChild
KviTalSplitter * m_pSplitter
QTextCodec * m_pTextCodec
QToolButton * m_pTextEncodingButton
KviWindowListItem * m_pWindowListItem
QString m_szName
QString m_szPlainTextCaption
QString m_szTextEncoding
unsigned long int m_uId
Constructor & Destructor Documentation
DccVoiceWindow::DccVoiceWindow (DccDescriptor * dcc, const char * name)
References __tr2qs_ctx(), connect(), connected(), connectionInProgress(), DccMarshalOutputContext::DccMarshal, g_pIconManager, KviIconManager::getBigIcon(), getMixerVolume(), KviIconManager::getSmallIcon(), handleMarshalError(), KVI_BIGICON_CONNECTED, KVI_BIGICON_DISCONNECTED, KviTalSplitter, DccWindow::m_pDescriptor, m_pHBox, m_pInputLabel, KviWindow::m_pIrcView, DccWindow::m_pMarshal, m_pOutputLabel, m_pPlayingLabel, m_pRecordingLabel, m_pSlaveThread, KviWindow::m_pSplitter, m_pTalkButton, m_pUpdateTimer, m_pVolumeSlider, Normal, KviIconManager::Play, KviIconManager::Record, KviTalHBox::setMargin(), setMixerVolume(), KviTalHBox::setSpacing(), KviTalVBox::setSpacing(), KviTalHBox::setStretchFactor(), startConnection(), and startOrStopTalking().
DccVoiceWindow::~DccVoiceWindow ()
References KviThreadManager::killPendingEvents(), m_pSlaveThread, m_pUpdateTimer, KviSensitiveThread::terminate(), and DccBroker::unregisterDccWindow().
Member Function Documentation
void DccVoiceWindow::connected () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, _KviDccVoiceThreadOptions::bForceHalfDuplex, connect(), _KviDccVoiceThreadOptions::iPreBufferSize, _KviDccVoiceThreadOptions::iSampleRate, DccDescriptor::iSampleRate, kvi_dcc_voice_get_codec(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OPTION_UINT, KVI_OUT_DCCMSG, KviOption_boolDccVoiceForceHalfDuplex, KviOption_stringDccVoiceSoundDevice, KviOption_uintDccVoicePreBufferSize, DccMarshal::localIp(), DccMarshal::localPort(), DccWindow::m_pDescriptor, DccWindow::m_pMarshal, m_pSlaveThread, m_pTalkButton, m_pUpdateTimer, DccVoiceCodec::name(), KviWindow::output(), _KviDccVoiceThreadOptions::pCodec, KviCString::ptr(), DccMarshal::releaseSocket(), DccMarshal::remoteIp(), DccMarshal::remotePort(), KviThread::start(), DccDescriptor::szCodec, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szPort, _KviDccVoiceThreadOptions::szSoundDevice, KviWindow::updateCaption(), and updateInfo().
Referenced by DccVoiceWindow().
void DccVoiceWindow::connectionInProgress () protected slot
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bSendRequest, KviWindow::connection(), DccDescriptor::console(), KviIrcConnection::encodeText(), DccDescriptor::iSampleRate, KVI_OUT_DCCMSG, DccMarshal::localIp(), DccMarshal::localPort(), DccWindow::m_pDescriptor, DccWindow::m_pMarshal, KviWindow::output(), KviCString::ptr(), KviIrcConnection::sendFmtData(), KviNetUtils::stringIpToBinaryIp(), DccDescriptor::szCodec, DccDescriptor::szFakeIp, DccDescriptor::szFakePort, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szNick, and DccDescriptor::szPort.
Referenced by DccVoiceWindow().
bool DccVoiceWindow::event (QEvent * e) protected virtual
References __tr2qs_ctx(), __tr_no_xgettext_ctx, KviError::getDescription(), KVI_DCC_THREAD_EVENT_ACTION, KVI_DCC_THREAD_EVENT_ERROR, KVI_DCC_THREAD_EVENT_MESSAGE, KVI_DCC_VOICE_THREAD_ACTION_START_PLAYING, KVI_DCC_VOICE_THREAD_ACTION_START_RECORDING, KVI_DCC_VOICE_THREAD_ACTION_STOP_PLAYING, KVI_DCC_VOICE_THREAD_ACTION_STOP_RECORDING, KVI_OUT_DCCERROR, KVI_OUT_DCCMSG, KVI_THREAD_EVENT, m_pPlayingLabel, m_pRecordingLabel, m_pTalkButton, m_pUpdateTimer, KviWindow::output(), KviWindow::outputNoFmt(), KviCString::ptr(), and updateInfo().
void DccVoiceWindow::fillCaptionBuffers () protected virtual
Reimplemented from KviWindow.
References KviCString::Format, DccWindow::m_pDescriptor, KviWindow::m_szPlainTextCaption, DccDescriptor::szIp, DccDescriptor::szLocalFileName, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccVoiceWindow::focusInEvent (QFocusEvent * e) protected virtual
Reimplemented from KviWindow.
References getMixerVolume(), m_pVolumeSlider, and setMixerVolume().
void DccVoiceWindow::getBaseLogFileName (QString & buffer) protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, DccDescriptor::szLocalFileName, DccDescriptor::szNick, and DccDescriptor::szPort.
int DccVoiceWindow::getMixerVolume (void) const protected
References KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolDccVoiceVolumeSliderControlsPCM, and KviOption_stringDccVoiceMixerDevice.
Referenced by DccVoiceWindow(), and focusInEvent().
void DccVoiceWindow::handleMarshalError (KviError::Code eError) protected slot
References __tr2qs_ctx(), KviError::getDescription(), KVI_OUT_DCCERROR, m_pPlayingLabel, m_pRecordingLabel, m_pTalkButton, and KviWindow::output().
Referenced by DccVoiceWindow(), and startConnection().
QPixmap * DccVoiceWindow::myIconPtr () protected virtual
Reimplemented from KviWindow.
References KviIconManager::DccVoice, g_pIconManager, and KviIconManager::getSmallIcon().
void DccVoiceWindow::resizeEvent (QResizeEvent * e) protected virtual
References m_pHBox, and KviWindow::m_pSplitter.
void DccVoiceWindow::setMixerVolume (int vol) protected slot
References __tr2qs_ctx(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolDccVoiceVolumeSliderControlsPCM, KviOption_stringDccVoiceMixerDevice, and m_pVolumeSlider.
Referenced by DccVoiceWindow(), and focusInEvent().
QSize DccVoiceWindow::sizeHint () const protected virtual
References m_pHBox, KviWindow::m_pIrcView, KviIrcView::sizeHint(), and w.
void DccVoiceWindow::startConnection () protected
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bDoTimeout, DccMarshal::dccConnect(), DccMarshal::dccListen(), handleMarshalError(), KVI_OUT_DCCMSG, DccWindow::m_pDescriptor, DccWindow::m_pMarshal, KviWindow::output(), KviError::Success, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, and DccDescriptor::szPort.
Referenced by DccVoiceWindow().
void DccVoiceWindow::startOrStopTalking (bool bStart) protected slot
References startTalking(), and stopTalking().
Referenced by DccVoiceWindow().
void DccVoiceWindow::startTalking () protected
References e, KviSensitiveThread::enqueueEvent(), KVI_DCC_THREAD_EVENT_ACTION, m_pSlaveThread, and KviThreadDataEvent< TData >::setData().
Referenced by startOrStopTalking().
void DccVoiceWindow::stopTalking () protected
References e, KviSensitiveThread::enqueueEvent(), KVI_DCC_THREAD_EVENT_ACTION, m_pSlaveThread, and KviThreadDataEvent< TData >::setData().
Referenced by startOrStopTalking().
const QString & DccVoiceWindow::target () protected virtual
Reimplemented from KviWindow.
References DccWindow::m_pDescriptor, m_szTarget, DccDescriptor::szIp, DccDescriptor::szNick, and DccDescriptor::szPort.
void DccVoiceWindow::updateInfo () protected slot
References __tr_ctx, KviCString::Format, KviMutex::lock(), DccVoiceThread::m_iInputBufferSize, DccVoiceThread::m_iOutputBufferSize, DccVoiceThread::m_pInfoMutex, m_pInputLabel, m_pOutputLabel, m_pSlaveThread, KviCString::ptr(), KviCString::sprintf(), and KviMutex::unlock().
Referenced by connected(), and event().
Member Data Documentation
KviTalHBox* DccVoiceWindow::m_pHBox protected
Referenced by DccVoiceWindow(), resizeEvent(), and sizeHint().
QLabel* DccVoiceWindow::m_pInputLabel protected
Referenced by DccVoiceWindow(), and updateInfo().
QLabel* DccVoiceWindow::m_pOutputLabel protected
Referenced by DccVoiceWindow(), and updateInfo().
QLabel* DccVoiceWindow::m_pPlayingLabel protected
Referenced by DccVoiceWindow(), event(), and handleMarshalError().
QLabel* DccVoiceWindow::m_pRecordingLabel protected
Referenced by DccVoiceWindow(), event(), and handleMarshalError().
DccVoiceThread* DccVoiceWindow::m_pSlaveThread protected
Referenced by connected(), DccVoiceWindow(), startTalking(), stopTalking(), updateInfo(), and ~DccVoiceWindow().
QToolButton* DccVoiceWindow::m_pTalkButton protected
Referenced by connected(), DccVoiceWindow(), event(), and handleMarshalError().
QTimer* DccVoiceWindow::m_pUpdateTimer protected
Referenced by connected(), DccVoiceWindow(), event(), and ~DccVoiceWindow().
QSlider* DccVoiceWindow::m_pVolumeSlider protected
Referenced by DccVoiceWindow(), focusInEvent(), and setMixerVolume().
QString DccVoiceWindow::m_szTarget protected
Referenced by target().
The documentation for this class was generated from the following files:
src/modules/dcc/DccVoiceWindow.h
src/modules/dcc/DccVoiceWindow.cpp