KVIrc: UPnP::RootService Class Reference
UPnP::RootService Class Reference
#include <RootService.h>
Public Member Functions
QString getDeviceType () const
ServiceParameters getServiceById (const QString &serviceId) const
bool getServiceById (const QString &serviceId, const QString &deviceUdn, ServiceParameters &params) const
ServiceParameters getServiceByType (const QString &serviceType) const
bool getServiceByType (const QString &serviceType, const QString &deviceUdn, ServiceParameters &params) const
void queryDevice ()
RootService (const QString &hostname, int port, const QString &rootUrl)
virtual ~RootService ()
Public Member Functions inherited from UPnP::Service
int getPendingRequests () const
Service (const QString &hostname, int port, const QString &informationUrl)
Service (const ServiceParameters &params)
virtual ~Service ()
Protected Member Functions
virtual void gotInformationResponse (const QDomNode &response)
Protected Member Functions inherited from UPnP::Service
int callAction (const QString &actionName, const QString &prefix)
int callAction (const QString &actionName, const QMap< QString, QString > &arguments, const QString &prefix)
int callInformationUrl ()
virtual void gotActionErrorResponse (const QDomNode &response)
virtual void gotActionResponse (const QString &responseType, const QMap< QString, QString > &resultValues)
Private Member Functions
void addDeviceServices (const QDomNode &device)
Private Attributes
QMap< QString, QDomNodeList > m_deviceServices
int m_iPort
QString m_szDeviceType
QString m_szHostname
QString m_szRootUdn
Additional Inherited Members
Signals inherited from UPnP::Service
void queryFinished (bool error)
Detailed Description
The services of a device can be retrieved using the device root service. The URL of the root service is returned by an SSDP broadcast. The root service returns the meta information and list of services the device supports.
Author
Diederik van der Boor
Constructor & Destructor Documentation
UPnP::RootService::RootService (const QString & hostname, int port, const QString & rootUrl)
UPnP::RootService::~RootService () virtual
Member Function Documentation
void UPnP::RootService::addDeviceServices (const QDomNode & device) private
References __tr2qs, __tr2qs_ctx(), KviApplication::activeConsole(), g_pApp, XmlFunctions::getNodeValue(), i, InternetGatewayDeviceType, KVI_OUT_GENERICSTATUS, m_deviceServices, and KviWindow::output().
Referenced by gotInformationResponse().
QString UPnP::RootService::getDeviceType () const
References m_szDeviceType.
ServiceParameters UPnP::RootService::getServiceById (const QString & serviceId) const
References UPnP::ServiceParameters::controlUrl, i, and m_deviceServices.
bool UPnP::RootService::getServiceById (const QString & serviceId, const QString & deviceUdn, ServiceParameters & params) const
References UPnP::ServiceParameters::controlUrl, XmlFunctions::getNodeChildByKey(), XmlFunctions::getNodeValue(), UPnP::ServiceParameters::hostname, m_deviceServices, m_iPort, m_szHostname, UPnP::ServiceParameters::port, UPnP::ServiceParameters::scpdUrl, UPnP::ServiceParameters::serviceId, and UPnP::ServiceParameters::serviceType.
ServiceParameters UPnP::RootService::getServiceByType (const QString & serviceType) const
References UPnP::ServiceParameters::controlUrl, i, and m_deviceServices.
Referenced by UPnP::IgdControlPoint::slotDeviceQueried().
bool UPnP::RootService::getServiceByType (const QString & serviceType, const QString & deviceUdn, ServiceParameters & params) const
References UPnP::ServiceParameters::controlUrl, XmlFunctions::getNodeChildByKey(), XmlFunctions::getNodeValue(), UPnP::ServiceParameters::hostname, m_deviceServices, m_iPort, m_szHostname, UPnP::ServiceParameters::port, UPnP::ServiceParameters::scpdUrl, UPnP::ServiceParameters::serviceId, and UPnP::ServiceParameters::serviceType.
void UPnP::RootService::gotInformationResponse (const QDomNode & response) protected virtual
Reimplemented from UPnP::Service.
References addDeviceServices(), XmlFunctions::getNode(), XmlFunctions::getNodeValue(), m_deviceServices, m_szDeviceType, and m_szRootUdn.
void UPnP::RootService::queryDevice ()
References UPnP::Service::callInformationUrl().
Referenced by UPnP::IgdControlPoint::initialize().
Member Data Documentation
QMap<QString,QDomNodeList> UPnP::RootService::m_deviceServices private
Referenced by addDeviceServices(), getServiceById(), getServiceByType(), and gotInformationResponse().
int UPnP::RootService::m_iPort private
Referenced by getServiceById(), and getServiceByType().
QString UPnP::RootService::m_szDeviceType private
Referenced by getDeviceType(), and gotInformationResponse().
QString UPnP::RootService::m_szHostname private
Referenced by getServiceById(), and getServiceByType().
QString UPnP::RootService::m_szRootUdn private
Referenced by gotInformationResponse().
The documentation for this class was generated from the following files:
src/modules/upnp/RootService.h
src/modules/upnp/RootService.cpp