KVIrc: KviMenuBar Class Reference
KviMenuBar Class Reference
#include <KviMenuBar.h>
Public Member Functions
void addMenu (const QString &text, KviKvsPopupMenu *p, int index)
int getDefaultItemRealIndex (int iDefaultIndex)
KviMenuBar (KviMainWindow *par, const char *name)
bool removeMenu (const QString &text)
~KviMenuBar ()
Protected Slots
void actionTriggered (QAction *pAction)
void actionTriggered (bool)
void menuDestroyed ()
void modulesToolsTriggered (QAction *pAction)
void newConnectionToServer (QAction *pAction)
void setupHelpPopup (QMenu *pop=0)
void setupMainPopup (QMenu *pop=0)
void setupScriptingPopup (QMenu *pop=0)
void setupSettingsPopup (QMenu *pop=0)
void setupToolsPopup (QMenu *pop=0)
void updateActionsToolsPopup ()
void updateMainPopup ()
void updateModulesToolsPopup ()
void updateRecentServersPopup ()
void updateSettingsPopup ()
void updateToolbarsPopup ()
void updateToolsPopup ()
Protected Member Functions
void addDefaultItem (const QString &text, QMenu *pop)
KviScriptMenuBarItem * findMenu (const QString &text)
KviScriptMenuBarItem * findMenu (KviKvsPopupMenu *p)
Protected Attributes
QAction * m_pActionsToolsAction
QMenu * m_pActionsToolsPopup
QAction * m_pDisconnectAction
KviMainWindow * m_pFrm
QAction * m_pModulesToolsAction
QMenu * m_pModulesToolsPopup
QMenu * m_pRecentServersPopup
KviPointerList
< KviScriptMenuBarItem > * m_pScriptItemList
QAction * m_pStatusBarAction
QMenu * m_pToolbarsPopup
Constructor & Destructor Documentation
KviMenuBar::KviMenuBar (KviMainWindow * par, const char * name)
References __tr2qs, ACTION_POPUP_ITEM, actionTriggered(), addDefaultItem(), connect(), KVI_COREACTION_GENERALOPTIONS, KVI_INTERNALCOMMAND_ABOUT_ABOUTKVIRC, m_pActionsToolsPopup, m_pFrm, m_pModulesToolsPopup, m_pRecentServersPopup, m_pScriptItemList, m_pToolbarsPopup, KviMainWindow::mdiManager(), modulesToolsTriggered(), newConnectionToServer(), setupHelpPopup(), setupMainPopup(), setupScriptingPopup(), setupSettingsPopup(), setupToolsPopup(), updateActionsToolsPopup(), updateMainPopup(), updateModulesToolsPopup(), updateRecentServersPopup(), updateSettingsPopup(), updateToolbarsPopup(), updateToolsPopup(), and KviMdiManager::windowPopup().
KviMenuBar::~KviMenuBar ()
References m_pScriptItemList.
Member Function Documentation
void KviMenuBar::actionTriggered (QAction * pAction) [protected, slot]
References KviMainWindow::executeInternalCommand(), and m_pFrm.
Referenced by actionTriggered(), KviMenuBar(), setupMainPopup(), and setupToolsPopup().
void KviMenuBar::actionTriggered (bool) [protected, slot]
References actionTriggered().
void KviMenuBar::addDefaultItem (const QString & text, QMenu * pop) [protected]
Referenced by KviMenuBar().
void KviMenuBar::addMenu (const QString & text, KviKvsPopupMenu * p, int index)
References KviPointerList< T >::append(), connect(), m_pScriptItemList, menuDestroyed(), p, _KviScriptMenuBarItem::pPopup, KviPointerList< T >::setAutoDelete(), _KviScriptMenuBarItem::szPopupName, and _KviScriptMenuBarItem::szText.
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
KviScriptMenuBarItem * KviMenuBar::findMenu (KviKvsPopupMenu * p) [protected]
References KviPointerList< T >::first(), i, m_pScriptItemList, and KviPointerList< T >::next().
KviScriptMenuBarItem * KviMenuBar::findMenu (const QString & text) [protected]
References KviQString::equalCI(), KviPointerList< T >::first(), i, m_pScriptItemList, and KviPointerList< T >::next().
Referenced by menuDestroyed(), and removeMenu().
int KviMenuBar::getDefaultItemRealIndex (int iDefaultIndex)
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviMenuBar::menuDestroyed () [protected, slot]
References findMenu(), i, m_pScriptItemList, and KviPointerList< T >::removeRef().
Referenced by addMenu(), and removeMenu().
void KviMenuBar::modulesToolsTriggered (QAction * pAction) [protected, slot]
References KviModuleExtensionManager::allocateExtension(), KviMainWindow::firstConsole(), g_pModuleExtensionManager, and m_pFrm.
Referenced by KviMenuBar().
void KviMenuBar::newConnectionToServer (QAction * pAction) [protected, slot]
References __tr2qs, KviApplication::activeConsole(), KviMainWindow::firstConsole(), g_pApp, KVI_IRCURL_CONTEXT_FIRSTFREE, m_pFrm, KviIrcUrl::parse(), KviCString::ptr(), and KviIrcUrl::run().
Referenced by KviMenuBar().
bool KviMenuBar::removeMenu (const QString & text)
References findMenu(), i, m_pScriptItemList, menuDestroyed(), _KviScriptMenuBarItem::pPopup, removeAction(), and KviPointerList< T >::removeRef().
Referenced by KviKvsCoreSimpleCommands::KVSCSC().
void KviMenuBar::setupHelpPopup (QMenu * pop = 0) [protected, slot]
References __tr2qs, ACTION_POPUP_ITEM, KviIconManager::Bomb, KviIconManager::Channel, g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::Help, KviIconManager::HomePage, KviIconManager::Idea, KviLocale::instance(), KVI_COREACTION_HELPINDEX, KVI_INTERNALCOMMAND_ABOUT_ABOUTKVIRC, KVI_INTERNALCOMMAND_HELP_NEWSTATICWINDOW, KVI_INTERNALCOMMAND_KVIRC_HOMEPAGE, KVI_INTERNALCOMMAND_KVIRC_HOMEPAGE_FR, KVI_INTERNALCOMMAND_KVIRC_HOMEPAGE_RU, KVI_INTERNALCOMMAND_OPENURL_KVIRC_BUGTRACK, KVI_INTERNALCOMMAND_OPENURL_KVIRC_FR_ON_EUROPNET, KVI_INTERNALCOMMAND_OPENURL_KVIRC_FR_ON_FREENODE, KVI_INTERNALCOMMAND_OPENURL_KVIRC_IT_ON_AZZURRA, KVI_INTERNALCOMMAND_OPENURL_KVIRC_MAILINGLIST, KVI_INTERNALCOMMAND_OPENURL_KVIRC_ON_FREENODE, KVI_INTERNALCOMMAND_TIP_OPEN, kvi_strEqualCIN(), KviIconManager::KVIrc, and KviIconManager::Message.
Referenced by KviMenuBar().
void KviMenuBar::setupMainPopup (QMenu * pop = 0) [protected, slot]
References __tr2qs, ACTION_POPUP_ITEM, actionTriggered(), g_pIconManager, g_pMainWindow, KviIconManager::getSmallIcon(), KVI_COREACTION_NEWIRCCONTEXT, KVI_INTERNALCOMMAND_QUIT, m_pDisconnectAction, m_pRecentServersPopup, main(), KviIconManager::Quit, KviIconManager::QuitApp, and KviIconManager::World.
Referenced by KviMenuBar().
void KviMenuBar::setupScriptingPopup (QMenu * pop = 0) [protected, slot]
References __tr2qs, ACTION_POPUP_ITEM, g_pApp, g_pIconManager, KviIconManager::getSmallIcon(), KVI_COREACTION_ACTIONEDITOR, KVI_COREACTION_ALIASEDITOR, KVI_COREACTION_CLASSEDITOR, KVI_COREACTION_CODETESTER, KVI_COREACTION_EVENTEDITOR, KVI_COREACTION_EXECUTEKVS, KVI_COREACTION_POPUPEDITOR, KVI_COREACTION_RAWEDITOR, and KviIconManager::TextExclamative.
Referenced by KviMenuBar().
void KviMenuBar::setupSettingsPopup (QMenu * pop = 0) [protected, slot]
References __tr2qs, ACTION_POPUP_ITEM, g_pIconManager, KviIconManager::getSmallIcon(), KVI_COREACTION_EDITREGUSERS, KVI_COREACTION_GENERALOPTIONS, KVI_COREACTION_MANAGEADDONS, KVI_COREACTION_MANAGETHEMES, KVI_COREACTION_SERVEROPTIONS, KVI_COREACTION_THEMEOPTIONS, KVI_COREACTION_TOOLBAREDITOR, m_pFrm, m_pStatusBarAction, m_pToolbarsPopup, and KviIconManager::StatusBar.
Referenced by KviMenuBar().
void KviMenuBar::setupToolsPopup (QMenu * pop = 0) [protected, slot]
References __tr2qs, ACTION_POPUP_ITEM, actionTriggered(), g_pIconManager, KviIconManager::getSmallIcon(), KviIconManager::IconManager, KVI_COREACTION_CHANNELLIST, KVI_COREACTION_FILETRANSFER, KVI_COREACTION_IOGRAPH, KVI_COREACTION_JOINCHANNELS, KVI_COREACTION_LOGVIEWER, KVI_COREACTION_NETWORKLINKS, KVI_COREACTION_SCREENSHOT, KVI_COREACTION_SHAREDFILES, KVI_COREACTION_SOCKETSPY, KVI_COREACTION_URLLIST, KVI_INTERNALCOMMAND_TERM_OPEN, m, m_pActionsToolsAction, m_pActionsToolsPopup, m_pModulesToolsAction, m_pModulesToolsPopup, and KviIconManager::Terminal.
Referenced by KviMenuBar().
void KviMenuBar::updateActionsToolsPopup () [protected, slot]
References KviPointerList< T >::first(), KviActionManager::instance(), KviPointerList< T >::isEmpty(), KviActionManager::listActionsByCategory(), m_pActionsToolsPopup, and KviPointerList< T >::next().
Referenced by KviMenuBar().
void KviMenuBar::updateMainPopup () [protected, slot]
References KviMainWindow::activeContext(), KviIrcContext::Connected, m_pDisconnectAction, m_pFrm, and KviIrcContext::state().
Referenced by KviMenuBar().
void KviMenuBar::updateModulesToolsPopup () [protected, slot]
References d, KviPointerList< T >::first(), g_pModuleExtensionManager, KviModuleExtensionManager::getExtensionList(), l, m_pModulesToolsPopup, and KviPointerList< T >::next().
Referenced by KviMenuBar().
void KviMenuBar::updateRecentServersPopup () [protected, slot]
References __tr2qs, KviApplication::fillRecentServersPopup(), g_pApp, g_pIconManager, KviIconManager::getSmallIcon(), m, and KviIconManager::Server.
Referenced by KviMenuBar().
void KviMenuBar::updateSettingsPopup () [protected, slot]
References m_pFrm, m_pStatusBarAction, and KviMainWindow::mainStatusBar().
Referenced by KviMenuBar().
void KviMenuBar::updateToolbarsPopup () [protected, slot]
References KviMainWindow::fillToolBarsPopup(), m_pFrm, and m_pToolbarsPopup.
Referenced by KviMenuBar().
void KviMenuBar::updateToolsPopup () [protected, slot]
References g_pModuleExtensionManager, KviModuleExtensionManager::getExtensionList(), KviActionManager::instance(), KviPointerList< T >::isEmpty(), l, KviActionManager::listActionsByCategory(), m_pActionsToolsAction, and m_pModulesToolsAction.
Referenced by KviMenuBar().
Member Data Documentation
QAction* KviMenuBar::m_pActionsToolsAction [protected]
Referenced by setupToolsPopup(), and updateToolsPopup().
QMenu* KviMenuBar::m_pActionsToolsPopup [protected]
Referenced by KviMenuBar(), setupToolsPopup(), and updateActionsToolsPopup().
QAction* KviMenuBar::m_pDisconnectAction [protected]
Referenced by setupMainPopup(), and updateMainPopup().
KviMainWindow* KviMenuBar::m_pFrm [protected]
Referenced by actionTriggered(), KviMenuBar(), modulesToolsTriggered(), newConnectionToServer(), setupSettingsPopup(), updateMainPopup(), updateSettingsPopup(), and updateToolbarsPopup().
QAction* KviMenuBar::m_pModulesToolsAction [protected]
Referenced by setupToolsPopup(), and updateToolsPopup().
QMenu* KviMenuBar::m_pModulesToolsPopup [protected]
Referenced by KviMenuBar(), setupToolsPopup(), and updateModulesToolsPopup().
QMenu* KviMenuBar::m_pRecentServersPopup [protected]
Referenced by KviMenuBar(), and setupMainPopup().
KviPointerList<KviScriptMenuBarItem>* KviMenuBar::m_pScriptItemList [protected]
Referenced by addMenu(), findMenu(), KviMenuBar(), menuDestroyed(), removeMenu(), and ~KviMenuBar().
QAction* KviMenuBar::m_pStatusBarAction [protected]
Referenced by setupSettingsPopup(), and updateSettingsPopup().
QMenu* KviMenuBar::m_pToolbarsPopup [protected]
Referenced by KviMenuBar(), setupSettingsPopup(), and updateToolbarsPopup().
The documentation for this class was generated from the following files:
src/kvirc/ui/KviMenuBar.h
src/kvirc/ui/KviMenuBar.cpp