KVIrc: KviKvsObjectScriptFunctionHandler Class Reference
KviKvsObjectScriptFunctionHandler Class Reference
#include <KviKvsObjectFunctionHandlerImpl.h>
Public Member Functions
virtual ~KviKvsObjectScriptFunctionHandler ()
Public Member Functions inherited from KviKvsObjectFunctionHandler
unsigned int flags ()
bool isClone ()
void setClone (bool bCl)
virtual ~KviKvsObjectFunctionHandler ()
Protected Member Functions
virtual bool call (KviKvsObject *pObject, KviKvsObjectFunctionCall *pCall)
virtual
KviKvsObjectFunctionHandler * clone ()
virtual bool isScriptHandler ()
KviKvsObjectScriptFunctionHandler (const QString &szScriptContext, const QString &szCode, const QString &szReminder, unsigned int uFlags=0)
KviKvsObjectScriptFunctionHandler (const KviKvsObjectScriptFunctionHandler &h)
virtual QString reminder ()
virtual QString scriptHandlerCode ()
virtual void setReminder (const QString &szReminder)
Protected Member Functions inherited from KviKvsObjectFunctionHandler
KviKvsObjectFunctionHandler (unsigned int uFlags=0)
Protected Attributes
KviKvsScript * m_pHandler
QString m_szReminder
Protected Attributes inherited from KviKvsObjectFunctionHandler
bool m_bClone
unsigned int m_uFlags
Friends
class KviKvsObject
class KviKvsObjectClass
Additional Inherited Members
Public Types inherited from KviKvsObjectFunctionHandler
enum Flags { Internal = 1 }
Constructor & Destructor Documentation
KviKvsObjectScriptFunctionHandler::KviKvsObjectScriptFunctionHandler (const QString & szScriptContext, const QString & szCode, const QString & szReminder, unsigned int uFlags = 0) protected
References KviKvsScript::InstructionList, m_pHandler, and m_szReminder.
Referenced by clone().
KviKvsObjectScriptFunctionHandler::KviKvsObjectScriptFunctionHandler (const KviKvsObjectScriptFunctionHandler & h) protected
References m_pHandler.
KviKvsObjectScriptFunctionHandler::~KviKvsObjectScriptFunctionHandler () virtual
References m_pHandler.
Member Function Documentation
bool KviKvsObjectScriptFunctionHandler::call (KviKvsObject * pObject, KviKvsObjectFunctionCall * pCall) protected virtual
Implements KviKvsObjectFunctionHandler.
References m_pHandler, KviKvsRunTimeCall::params(), KviKvsScript::PreserveParams, KviKvsObjectFunctionCall::returnValue(), KviKvsScript::run(), and KviKvsRunTimeCall::window().
KviKvsObjectFunctionHandler * KviKvsObjectScriptFunctionHandler::clone () protected virtual
Implements KviKvsObjectFunctionHandler.
References KviKvsObjectScriptFunctionHandler().
bool KviKvsObjectScriptFunctionHandler::isScriptHandler () protected virtual
Reimplemented from KviKvsObjectFunctionHandler.
QString KviKvsObjectScriptFunctionHandler::reminder () protected virtual
Reimplemented from KviKvsObjectFunctionHandler.
References m_szReminder.
QString KviKvsObjectScriptFunctionHandler::scriptHandlerCode () protected virtual
Reimplemented from KviKvsObjectFunctionHandler.
References KviKvsScript::code(), and m_pHandler.
virtual void KviKvsObjectScriptFunctionHandler::setReminder (const QString & szReminder) inline protected virtual
Reimplemented from KviKvsObjectFunctionHandler.
Friends And Related Function Documentation
friend class KviKvsObject friend
Reimplemented from KviKvsObjectFunctionHandler.
friend class KviKvsObjectClass friend
Reimplemented from KviKvsObjectFunctionHandler.
Member Data Documentation
KviKvsScript* KviKvsObjectScriptFunctionHandler::m_pHandler protected
Referenced by call(), KviKvsObjectScriptFunctionHandler(), scriptHandlerCode(), and ~KviKvsObjectScriptFunctionHandler().
QString KviKvsObjectScriptFunctionHandler::m_szReminder protected
Referenced by KviKvsObjectScriptFunctionHandler(), and reminder().
The documentation for this class was generated from the following files:
src/kvirc/kvs/object/KviKvsObjectFunctionHandlerImpl.h
src/kvirc/kvs/object/KviKvsObjectFunctionHandlerImpl.cpp