KVIrc: KviFileTransferManager Class Reference
KviFileTransferManager Class Reference
#include <KviFileTransfer.h>
Signals
void transferRegistered (KviFileTransfer *t)
void transferUnregistering (KviFileTransfer *t)
Public Member Functions
void invokeTransferWindow (KviWindow *pWnd=0, bool bCreateMinimized=false, bool bNoRaise=false)
void killAllTransfers ()
void killTerminatedTransfers ()
KviFileTransferManager ()
KviPointerList< KviFileTransfer > * transferList ()
KviWindow * transferWindow ()
~KviFileTransferManager ()
Static Public Member Functions
static KviFileTransferManager * instance ()
Protected Member Functions
void registerTransfer (KviFileTransfer *t)
void setTransferWindow (KviWindow *wnd)
void unregisterTransfer (KviFileTransfer *t)
Static Protected Member Functions
static void cleanup ()
Protected Attributes
KviPointerList< KviFileTransfer > * m_pTransferList
KviWindow * m_pTransferWindow
Friends
class FileTransferWindow
class KviApplication
class KviFileTransfer
Constructor & Destructor Documentation
KviFileTransferManager::KviFileTransferManager ()
References m_pTransferList, and m_pTransferWindow.
Referenced by instance().
KviFileTransferManager::~KviFileTransferManager ()
References killAllTransfers().
Member Function Documentation
void KviFileTransferManager::cleanup () [static, protected]
References g_pFileTransferManager.
Referenced by KviApplication::~KviApplication().
KviFileTransferManager * KviFileTransferManager::instance () [static]
References g_pFileTransferManager, and KviFileTransferManager().
Referenced by FileTransferWindow::clearAll(), FileTransferWindow::clearTerminated(), FileTransferWindow::FileTransferWindow(), FileTransferWindow::fillTransferView(), invokeTransferWindow(), KviFileTransfer::manager(), and FileTransferWindow::~FileTransferWindow().
void KviFileTransferManager::invokeTransferWindow (KviWindow * pWnd = 0, bool bCreateMinimized = false, bool bNoRaise = false)
References d, instance(), KVI_FILE_TRANSFER_WINDOW_EXTENSION_NAME, m_pTransferWindow, KviPointerHashTable< Key, T >::replace(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by KviFileTransfer::invokeTransferWindow().
void KviFileTransferManager::killAllTransfers ()
References KviFileTransfer::die(), KviPointerList< T >::first(), m_pTransferList, and t.
Referenced by FileTransferWindow::clearAll(), and ~KviFileTransferManager().
void KviFileTransferManager::killTerminatedTransfers ()
References KviPointerList< T >::append(), d, f, KviPointerList< T >::first(), l, m_pTransferList, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
Referenced by FileTransferWindow::clearTerminated().
void KviFileTransferManager::registerTransfer (KviFileTransfer * t) [protected]
References KviPointerList< T >::append(), m_pTransferList, KviPointerList< T >::setAutoDelete(), and transferRegistered().
Referenced by KviFileTransfer::KviFileTransfer().
void KviFileTransferManager::setTransferWindow (KviWindow * wnd) [inline, protected]
Referenced by FileTransferWindow::FileTransferWindow(), and FileTransferWindow::~FileTransferWindow().
KviPointerList<KviFileTransfer>* KviFileTransferManager::transferList () [inline]
Referenced by FileTransferWindow::fillTransferView().
void KviFileTransferManager::transferRegistered (KviFileTransfer * t) [signal]
Referenced by registerTransfer().
void KviFileTransferManager::transferUnregistering (KviFileTransfer * t) [signal]
Referenced by unregisterTransfer().
KviWindow* KviFileTransferManager::transferWindow () [inline]
void KviFileTransferManager::unregisterTransfer (KviFileTransfer * t) [protected]
References KviPointerList< T >::isEmpty(), m_pTransferList, KviPointerList< T >::removeRef(), and transferUnregistering().
Referenced by KviFileTransfer::~KviFileTransfer().
Friends And Related Function Documentation
friend class FileTransferWindow [friend]
friend class KviApplication [friend]
friend class KviFileTransfer [friend]
Member Data Documentation
KviPointerList<KviFileTransfer>* KviFileTransferManager::m_pTransferList [protected]
Referenced by killAllTransfers(), killTerminatedTransfers(), KviFileTransferManager(), registerTransfer(), and unregisterTransfer().
KviWindow* KviFileTransferManager::m_pTransferWindow [protected]
Referenced by invokeTransferWindow(), and KviFileTransferManager().
The documentation for this class was generated from the following files:
src/kvirc/kernel/KviFileTransfer.h
src/kvirc/kernel/KviFileTransfer.cpp