KVIrc: src/modules/dcc/DccUtils.cpp File Reference
DccUtils.cpp File Reference
#include "DccUtils.h"
#include "KviOptions.h"
#include "KviLocale.h"
#include "KviNetUtils.h"
#include "KviIrcSocket.h"
#include "KviIrcLink.h"
#include "KviQString.h"
Macros
#define _UTILS_CPP_
Functions
bool dcc_kvs_get_listen_ip_address (KviKvsModuleCommandCall *c, KviConsoleWindow *pConsole, QString &szListenIp)
Macro Definition Documentation
#define _UTILS_CPP_
Function Documentation
bool dcc_kvs_get_listen_ip_address (KviKvsModuleCommandCall * c, KviConsoleWindow * pConsole, QString & szListenIp)
References __tr2qs_ctx(), KviWindow::connection(), KviQString::equalCI(), KviNetUtils::getInterfaceAddress(), KviIrcSocket::getLocalHostIp(), KviConsoleWindow::isConnected(), KviConsoleWindow::isIPv6Connection(), KviNetUtils::isValidStringIp(), kvi_getLocalHostAddress(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolDccListenOnSpecifiedInterfaceByDefault, KviOption_stringDccListenDefaultInterface, KviIrcConnection::link(), KviIrcLink::socket(), and KviKvsRunTimeCall::warning().
Referenced by dcc_kvs_parse_default_parameters(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRSend(), and dccModuleParseDccSend().