KVIrc: src/modules/dcc/DccVideoWindow.cpp File Reference
src/modules/dcc/DccVideoWindow.cpp File Reference
#include "kvi_settings.h"
#include "DccVideoWindow.h"
#include "DccMarshal.h"
#include "DccBroker.h"
#include "KviIconManager.h"
#include "KviIrcView.h"
#include "KviKvsEventTriggers.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviNetUtils.h"
#include "KviOptions.h"
#include "KviConsoleWindow.h"
#include "KviMemory.h"
#include "kvi_socket.h"
#include "KviIrcConnection.h"
#include "KviTalVBox.h"
#include "KviControlCodes.h"
#include "KviMainWindow.h"
#include <QToolTip>
#include <QByteArray>
#include <QBuffer>
#include <QTextDocument>
#include <sys/ioctl.h>
#include "m_DccVideoWindow.moc"
Defines
#define FRAME_DURATION 200
Functions
static DccVideoCodec * kvi_dcc_video_get_codec (const char *codecName)
bool kvi_dcc_video_is_valid_codec (const char *codecName)
Variables
int g_iVideoDevicePoolInstances = 0
DccBroker * g_pDccBroker
Kopete::AV::VideoDevicePool * g_pVideoDevicePool = 0
Define Documentation
#define FRAME_DURATION 200
Referenced by DccVideoWindow::DccVideoWindow(), and DccVideoThread::run().
Function Documentation
static DccVideoCodec* kvi_dcc_video_get_codec (const char * codecName) [static]
References kvi_strEqualCI(), and Q_UNUSED().
Referenced by DccVideoWindow::connected().
bool kvi_dcc_video_is_valid_codec (const char * codecName)
References kvi_strEqualCI().
Referenced by dcc_kvs_cmd_video(), and dccModuleParseDccVideo().
Variable Documentation
int g_iVideoDevicePoolInstances = 0
Referenced by DccVideoThread::DccVideoThread(), and DccVideoThread::~DccVideoThread().
DccBroker* g_pDccBroker
Kopete::AV::VideoDevicePool* g_pVideoDevicePool = 0