KVIrc: src/modules/dcc/DccVoiceWindow.cpp File Reference
src/modules/dcc/DccVoiceWindow.cpp File Reference
#include "DccVoiceWindow.h"
#include "DccMarshal.h"
#include "DccBroker.h"
#include "DccVoiceAdpcmCodec.h"
#include "DccVoiceGsmCodec.h"
#include "kvi_settings.h"
#include "KviIconManager.h"
#include "KviIrcView.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviNetUtils.h"
#include "KviOptions.h"
#include "KviConsoleWindow.h"
#include "KviMemory.h"
#include "kvi_socket.h"
#include "KviIrcConnection.h"
#include "KviTalVBox.h"
#include <QFrame>
#include <QSlider>
#include <QToolTip>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include "m_DccVoiceWindow.moc"
Defines
#define COMPILE_DISABLE_DCC_VOICE
#define KVI_FORMAT AFMT_S16_LE
#define KVI_FRAGMENT_SIZE_IN_BYTES 512
#define KVI_NUM_CHANNELS 1
#define KVI_SNDCTL_FRAG_SIZE 0x00B00009
Functions
static DccVoiceCodec * kvi_dcc_voice_get_codec (const char *codecName)
bool kvi_dcc_voice_is_valid_codec (const char *codecName)
Variables
DccBroker * g_pDccBroker
Define Documentation
#define COMPILE_DISABLE_DCC_VOICE
#define KVI_FORMAT AFMT_S16_LE
Referenced by DccVoiceThread::openSoundcard().
#define KVI_FRAGMENT_SIZE_IN_BYTES 512
Referenced by DccVoiceThread::soundStep().
#define KVI_NUM_CHANNELS 1
Referenced by DccVoiceThread::openSoundcard().
#define KVI_SNDCTL_FRAG_SIZE 0x00B00009
Referenced by DccVoiceThread::openSoundcard().
Function Documentation
static DccVoiceCodec* kvi_dcc_voice_get_codec (const char * codecName) [static]
References kvi_strEqualCI().
Referenced by DccVoiceWindow::connected().
bool kvi_dcc_voice_is_valid_codec (const char * codecName)
References kvi_strEqualCI().
Referenced by dcc_kvs_cmd_voice(), and dccModuleParseDccVoice().
Variable Documentation
DccBroker* g_pDccBroker