KVIrc: src/modules/language/detector.h File Reference
src/modules/language/detector.h File Reference
Classes
struct _LanguageAndEncodingMatch
struct _LanguageAndEncodingResult
Defines
#define DLE_NUM_BEST_MATCHES 4
#define DLE_STRICT_UTF8_CHECKING 1
Typedefs
typedef struct
_LanguageAndEncodingMatch LanguageAndEncodingMatch
typedef struct
_LanguageAndEncodingResult LanguageAndEncodingResult
Functions
void detect_language_and_encoding (const char *data, LanguageAndEncodingResult *retBuffer, int iFlags)
Define Documentation
#define DLE_NUM_BEST_MATCHES 4
Referenced by detect_language_and_encoding(), and language_kvs_cmd_detect().
#define DLE_STRICT_UTF8_CHECKING 1
Referenced by detect_language_and_encoding().
Typedef Documentation
typedef struct _LanguageAndEncodingMatch LanguageAndEncodingMatch
typedef struct _LanguageAndEncodingResult LanguageAndEncodingResult
Function Documentation
void detect_language_and_encoding (const char * data, LanguageAndEncodingResult * retBuffer, int iFlags)
References compute_descriptor_score(), _LanguageAndEncodingResult::dAccuracy, DLE_NUM_BEST_MATCHES, DLE_STRICT_UTF8_CHECKING, _LanguageAndEncodingMatch::dScore, i, j, k, _LanguageAndEncodingResult::match, NUM_DESCRIPTORS, _DetectorDescriptor::szEncoding, _LanguageAndEncodingMatch::szEncoding, _DetectorDescriptor::szLanguage, _LanguageAndEncodingMatch::szLanguage, unknown_string, and utf8score().
Referenced by language_kvs_cmd_detect().