KVIrc: src/kvilib/system/kvi_thread.cpp File Reference
src/kvilib/system/kvi_thread.cpp File Reference
#include "kvi_thread.h"
#include "kvi_settings.h"
#include "kvi_heapobject.h"
#include "kvi_string.h"
#include <QObject>
#include <QSocketNotifier>
#include "kvi_pointerlist.h"
#include <QEvent>
#include <unistd.h>
#include <signal.h>
#include <fcntl.h>
#include <errno.h>
#include "kvi_error.h"
#include <QApplication>
Defines
#define KVI_THREAD_MAX_EVENT_QUEUE_LENGTH 50
#define KVI_THREAD_PIPE_SIDE_MASTER 0
#define KVI_THREAD_PIPE_SIDE_SLAVE 1
Functions
static void * internal_start_thread (void *arg)
static void kvi_threadCatchSigpipe ()
static void kvi_threadIgnoreSigalarm ()
static void kvi_threadInitialize ()
static void kvi_threadSigpipeHandler (int)
Variables
static KviThreadManager * g_pThreadManager = 0
Define Documentation
#define KVI_THREAD_MAX_EVENT_QUEUE_LENGTH 50
Referenced by KviThreadManager::postSlaveEvent().
#define KVI_THREAD_PIPE_SIDE_MASTER 0
Referenced by KviThreadManager::KviThreadManager(), and KviThreadManager::~KviThreadManager().
#define KVI_THREAD_PIPE_SIDE_SLAVE 1
Referenced by KviThreadManager::KviThreadManager(), KviThreadManager::postSlaveEvent(), and KviThreadManager::~KviThreadManager().
Function Documentation
static void* internal_start_thread (void * arg) [static]
Referenced by KviThread::start().
static void kvi_threadCatchSigpipe () [static]
References kvi_threadSigpipeHandler().
Referenced by kvi_threadInitialize().
static void kvi_threadIgnoreSigalarm () [static]
Referenced by kvi_threadInitialize().
static void kvi_threadInitialize () [static]
References kvi_threadCatchSigpipe(), and kvi_threadIgnoreSigalarm().
Referenced by KviThreadManager::globalInit(), and KviThread::internalThreadRun_doNotTouchThis().
static void kvi_threadSigpipeHandler (int) [static]
Referenced by kvi_threadCatchSigpipe().
Variable Documentation
KviThreadManager* g_pThreadManager = 0 [static]