KVIrc: /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_useraction.cpp File Reference
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_useraction.cpp File Reference
#include "kvi_useraction.h"
Functions
int kvi_getUserActionTemperature (unsigned int uIdx)
Variables
static int useraction_table [KVI_NUM_USERACTION_TYPES]
Function Documentation
int kvi_getUserActionTemperature (unsigned int uIdx)
References useraction_table.
Referenced by KviChannel::nickChange(), KviChannel::part(), KviQuery::userAction(), and KviChannel::userAction().
Variable Documentation
int useraction_table[KVI_NUM_USERACTION_TYPES] [static]
Initial value:
{
        25,
        25,
        25,
        20,
        5,
        -5,
        -20,
        -25,
        -25
}
Referenced by kvi_getUserActionTemperature().