KVIrc: src/kvilib/core/kvi_string.h File Reference
src/kvilib/core/kvi_string.h File Reference
#include "kvi_settings.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <QtGlobal>
#include <QString>
#include <QByteArray>
#include "kvi_inttypes.h"
#include "kvi_heapobject.h"
#include "kvi_stdarg.h"
Classes
class KviStr
Defines
#define __KVI_EXTERN extern
#define kvi_matchString kvi_matchStringCI
#define kvi_strEqualNoLocaleCI(str1, str2) kvi_strEqualCI(str1,str2)
#define kvi_strEqualNoLocaleCIN(str1, str2, len) kvi_strEqualCIN(str1,str2,len)
#define kvi_strLen(str) strlen(str)
Typedefs
typedef kvi_u16_t kvi_wchar_t
typedef kvi_u32_t kvi_wslen_t
Functions
int kvi_compare (const KviStr *p1, const KviStr *p2)
__KVI_EXTERN KVILIB_API const
char * kvi_extractToken (KviStr &str, const char *aux_ptr, char sep=' ')
__KVI_EXTERN KVILIB_API const
char * kvi_extractUpTo (KviStr &str, const char *aux_ptr, char sep=' ')
__KVI_EXTERN KVILIB_API int kvi_irc_vsnprintf (char *buffer, const char *fmt, kvi_va_list list, bool *bTruncated)
__KVI_EXTERN KVILIB_API bool kvi_matchStringCI (register const char *exp, register const char *str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringCS (register const char *exp, register const char *str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringWithTerminator (register const char *exp, register const char *str, char terminator, const char **r1, const char **r2)
__KVI_EXTERN KVILIB_API bool kvi_matchWildExpr (register const char *m1, register const char *m2)
__KVI_EXTERN KVILIB_API bool kvi_matchWildExprWithTerminator (register const char *m1, register const char *m2, char terminator, const char **r1, const char **r2)
__KVI_EXTERN KVILIB_API bool kvi_qstringEqualCI (const QString &s1, const QString &s2)
__KVI_EXTERN KVILIB_API int kvi_strcmpCI (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API int kvi_strcmpCS (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCI (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCIN (const char *str1, const char *str2, int len)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCS (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCSN (const char *str1, const char *str2, int len)
__KVI_EXTERN KVILIB_API int kvi_strMatchRevCS (const char *str1, const char *str2, int index=-1)
__KVI_EXTERN KVILIB_API int kvi_vsnprintf (char *buffer, int len, const char *fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API kvi_wslen_t kvi_wstrlen (const kvi_wchar_t *str)
__KVI_EXTERN KVILIB_API int kvi_wvsnprintcf (kvi_wchar_t *buffer, kvi_wslen_t len, const char *fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API int kvi_wvsnprintf (kvi_wchar_t *buffer, kvi_wslen_t len, const kvi_wchar_t *fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API bool operator!= (const char *left, const KviStr &right)
__KVI_EXTERN KVILIB_API bool operator!= (const KviStr &left, const char *right)
__KVI_EXTERN KVILIB_API bool operator!= (const KviStr &left, const KviStr &right)
__KVI_EXTERN KVILIB_API KviStr operator+ (char left, const KviStr &right)
__KVI_EXTERN KVILIB_API KviStr operator+ (const KviStr &left, char right)
__KVI_EXTERN KVILIB_API KviStr operator+ (const char *left, const KviStr &right)
__KVI_EXTERN KVILIB_API KviStr operator+ (const KviStr &left, const char *right)
__KVI_EXTERN KVILIB_API KviStr operator+ (const KviStr &left, const KviStr &right)
__KVI_EXTERN KVILIB_API bool operator== (const char *left, const KviStr &right)
__KVI_EXTERN KVILIB_API bool operator== (const KviStr &left, const char *right)
__KVI_EXTERN KVILIB_API bool operator== (const KviStr &left, const KviStr &right)
Define Documentation
#define __KVI_EXTERN extern
#define kvi_matchString kvi_matchStringCI
Referenced by KviRegisteredChannelDataBase::find().
#define kvi_strEqualNoLocaleCI (str1, str2) kvi_strEqualCI(str1,str2)
#define kvi_strEqualNoLocaleCIN (str1, str2, len) kvi_strEqualCIN(str1,str2,len)
#define kvi_strLen (str) strlen(str)
Referenced by kvi_hash_key_copy(), and parseArgs().
Typedef Documentation
typedef kvi_u16_t kvi_wchar_t
typedef kvi_u32_t kvi_wslen_t
Function Documentation
int kvi_compare (const KviStr * p1, const KviStr * p2) [inline]
References kvi_strcmpCI(), and KviStr::ptr().
Referenced by KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::inSort(), and KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::merge().
__KVI_EXTERN KVILIB_API const char* kvi_extractToken (KviStr & str, const char * aux_ptr, char sep = ' ')
References __range_valid, kvi_fastmove(), kvi_realloc, KviStr::m_len, and KviStr::m_ptr.
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), and KviParameterList::KviParameterList().
__KVI_EXTERN KVILIB_API const char* kvi_extractUpTo (KviStr & str, const char * aux_ptr, char sep = ' ')
References __range_valid, kvi_fastmove(), kvi_realloc, KviStr::m_len, and KviStr::m_ptr.
__KVI_EXTERN KVILIB_API int kvi_irc_vsnprintf (char * buffer, const char * fmt, kvi_va_list list, bool * bTruncated)
References __range_valid, kvi_va_arg, s, and KviQString::toUtf8().
Referenced by KviIrcConnection::sendFmtData().
__KVI_EXTERN KVILIB_API bool kvi_matchStringCI (register const char * exp, register const char * str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringCS (register const char * exp, register const char * str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringWithTerminator (register const char * exp, register const char * str, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
__KVI_EXTERN KVILIB_API bool kvi_matchWildExpr (register const char * m1, register const char * m2)
Referenced by KviMediaManager::findMediaTypeForRegularFile().
__KVI_EXTERN KVILIB_API bool kvi_matchWildExprWithTerminator (register const char * m1, register const char * m2, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
__KVI_EXTERN KVILIB_API bool kvi_qstringEqualCI (const QString & s1, const QString & s2)
__KVI_EXTERN KVILIB_API int kvi_strcmpCI (const char * str1, const char * str2)
References __range_valid.
Referenced by kvi_compare().
__KVI_EXTERN KVILIB_API int kvi_strcmpCS (const char * str1, const char * str2)
References __range_valid.
__KVI_EXTERN KVILIB_API bool kvi_strEqualCI (const char * str1, const char * str2)
References __range_valid.
Referenced by KviApp::checkFileAssociations(), KviStr::equalsCI(), KviRegisteredChannelDataBase::findExact(), KviMediaManager::findMediaTypeByFileMask(), KviMediaManager::findMediaTypeByIanaType(), KviLocale::init(), parseArgs(), KviServerParser::parseCtcpRequestDcc(), KviServerParser::parseNumeric005(), KviHttpRequest::processHeader(), and KviProxy::setNamedProtocol().
__KVI_EXTERN KVILIB_API bool kvi_strEqualCIN (const char * str1, const char * str2, int len)
References __range_valid.
Referenced by KviApp::checkFileAssociations(), KviLocale::codecForName(), KviStr::contains(), KviStr::equalsCIN(), KviStr::ext_contains(), KviStr::find(), KviStr::findFirstIdx(), KviStr::findLastIdx(), KviStr::findRev(), KviStr::occurences(), KviIrcUrl::parse(), parseArgs(), KviServerParser::parseNumeric005(), KviIrcSocket::proxyHandleHttpFinalReply(), and KviMenuBar::setupHelpPopup().
__KVI_EXTERN KVILIB_API bool kvi_strEqualCS (const char * str1, const char * str2) [inline]
References __range_valid.
Referenced by KviStr::equalsCS(), KviParameterList::getBool(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviModuleManager::loadModule(), operator!=(), operator==(), KviServerParser::parseChannelMode(), KviServerParser::parseCtcpRequestClientinfo(), and KviServerParser::parseMessage().
__KVI_EXTERN KVILIB_API bool kvi_strEqualCSN (const char * str1, const char * str2, int len) [inline]
References __range_valid.
Referenced by KviStr::contains(), KviStr::equalsCSN(), KviStr::ext_contains(), KviStr::find(), KviStr::findFirstIdx(), KviStr::findLastIdx(), KviStr::findRev(), KviStr::occurences(), and KviHttpRequest::processHeader().
__KVI_EXTERN KVILIB_API int kvi_strMatchRevCS (const char * str1, const char * str2, int index = -1)
References __range_valid.
__KVI_EXTERN KVILIB_API int kvi_vsnprintf (char * buffer, int len, const char * fmt, kvi_va_list list)
References __range_valid, kvi_va_arg, s, and KviQString::toUtf8().
Referenced by KviStr::append(), KviStr::KviStr(), and KviStr::sprintf().
__KVI_EXTERN KVILIB_API kvi_wslen_t kvi_wstrlen (const kvi_wchar_t * str)
Referenced by KviIrcView::appendText(), KviIrcView::getLinkUnderMouse(), KviStr::KviStr(), and KviIrcView::paintEvent().
__KVI_EXTERN KVILIB_API int kvi_wvsnprintcf (kvi_wchar_t * buffer, kvi_wslen_t len, const char * fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API int kvi_wvsnprintf (kvi_wchar_t * buffer, kvi_wslen_t len, const kvi_wchar_t * fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API bool operator!= (const char * left, const KviStr & right) [inline]
References kvi_strEqualCS(), and KviStr::m_ptr.
__KVI_EXTERN KVILIB_API bool operator!= (const KviStr & left, const char * right) [inline]
References kvi_strEqualCS(), and KviStr::m_ptr.
__KVI_EXTERN KVILIB_API bool operator!= (const KviStr & left, const KviStr & right) [inline]
References kvi_strEqualCS(), and KviStr::m_ptr.
__KVI_EXTERN KVILIB_API KviStr operator+ (char left, const KviStr & right) [inline]
__KVI_EXTERN KVILIB_API KviStr operator+ (const KviStr & left, char right) [inline]
__KVI_EXTERN KVILIB_API KviStr operator+ (const char * left, const KviStr & right) [inline]
__KVI_EXTERN KVILIB_API KviStr operator+ (const KviStr & left, const char * right) [inline]
__KVI_EXTERN KVILIB_API KviStr operator+ (const KviStr & left, const KviStr & right) [inline]
__KVI_EXTERN KVILIB_API bool operator== (const char * left, const KviStr & right) [inline]
References kvi_strEqualCS(), and KviStr::m_ptr.
__KVI_EXTERN KVILIB_API bool operator== (const KviStr & left, const char * right) [inline]
References kvi_strEqualCS(), and KviStr::m_ptr.
__KVI_EXTERN KVILIB_API bool operator== (const KviStr & left, const KviStr & right) [inline]
References kvi_strEqualCS(), KviStr::m_len, and KviStr::m_ptr.