KVIrc: /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_antispam.cpp File Reference
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_antispam.cpp File Reference
#include "kvi_antispam.h"
#include "kvi_options.h"
Defines
#define _KVI_ANTISPAM_CPP_
Functions
bool kvi_mayBeSpam (KviStr *msg, KviStr &spamWord)
Define Documentation
#define _KVI_ANTISPAM_CPP_
Function Documentation
bool kvi_mayBeSpam (KviStr * msg, KviStr & spamWord)
References KviStr::findFirstIdx(), KVI_OPTION_STRINGLIST, and KviOption_stringlistSpamWords.
Referenced by KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().