KVIrc: /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_antispam.h File Reference
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_antispam.h File Reference
#include "kvi_settings.h"
#include "kvi_string.h"
Functions
KVIRC_API bool kvi_mayBeSpam (KviStr *msg, KviStr &spamWord)
Function Documentation
KVIRC_API bool kvi_mayBeSpam (KviStr * msg, KviStr & spamWord)
References KviStr::findFirstIdx(), KVI_OPTION_STRINGLIST, and KviOption_stringlistSpamWords.
Referenced by KviServerParser::parseLiteralNotice(), and KviServerParser::parseLiteralPrivmsg().