KVIrc: /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/core/kvi_string.cpp File Reference
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/core/kvi_string.cpp File Reference
#include "kvi_debug.h"
#include "kvi_string.h"
#include "kvi_memmove.h"
#include "kvi_malloc.h"
#include "kvi_qstring.h"
Defines
#define _KVI_DEBUG_CHECK_RANGE_
#define _KVI_STRING_CPP_
#define NOT_AT_END(__str) (*__str && (*__str != terminator))
#define NOT_AT_END(__str) (*__str && (*__str != terminator))
Functions
static unsigned char get_base64_idx (char base64)
static char get_decimal_from_hex_digit_char (char dgt)
const char * kvi_extractToken (KviStr &str, const char *aux_ptr, char sep)
const char * kvi_extractUpTo (KviStr &str, const char *aux_ptr, char sep)
int kvi_irc_vsnprintf (char *buffer, const char *fmt, kvi_va_list list, bool *bTruncated)
bool kvi_matchStringCI (register const char *exp, register const char *str)
bool kvi_matchStringCS (register const char *exp, register const char *str)
bool kvi_matchStringWithTerminator (register const char *exp, register const char *str, char terminator, const char **r1, const char **r2)
bool kvi_matchWildExpr (register const char *m1, register const char *m2)
bool kvi_matchWildExprWithTerminator (register const char *m1, register const char *m2, char terminator, const char **r1, const char **r2)
bool kvi_qstringEqualCI (const QString &s1, const QString &s2)
int kvi_strcmpCI (const char *str1, const char *str2)
int kvi_strcmpCS (const char *str1, const char *str2)
bool kvi_strEqualCI (const char *str1, const char *str2)
bool kvi_strEqualCIN (const char *str1, const char *str2, int len)
bool kvi_strEqualCS (const char *str1, const char *str2)
bool kvi_strEqualCSN (const char *str1, const char *str2, int len)
int kvi_strMatchRevCS (const char *str1, const char *str2, int index)
int kvi_vsnprintf (char *buffer, int len, const char *fmt, kvi_va_list list)
kvi_wslen_t kvi_wstrlen (const kvi_wchar_t *str)
Variables
static const char * base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static KviStr g_szApplicationWideEmptyString
static char hexdigits [16] = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' }
unsigned char iso88591_toLower_map [256]
unsigned char iso88591_toUpper_map [256]
Define Documentation
#define _KVI_DEBUG_CHECK_RANGE_
#define _KVI_STRING_CPP_
#define NOT_AT_END (__str) (*__str && (*__str != terminator))
#define NOT_AT_END (__str) (*__str && (*__str != terminator))
Referenced by kvi_matchStringWithTerminator(), and kvi_matchWildExprWithTerminator().
Function Documentation
static unsigned char get_base64_idx (char base64) [static]
Referenced by KviStr::base64ToBuffer().
static char get_decimal_from_hex_digit_char (char dgt) [static]
Referenced by KviStr::hexDecode(), and KviStr::hexToBuffer().
const char* kvi_extractToken (KviStr & str, const char * aux_ptr, char sep)
References __range_valid, kvi_fastmove(), kvi_realloc, KviStr::m_len, and KviStr::m_ptr.
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), and KviParameterList::KviParameterList().
const char* kvi_extractUpTo (KviStr & str, const char * aux_ptr, char sep)
References __range_valid, kvi_fastmove(), kvi_realloc, KviStr::m_len, and KviStr::m_ptr.
int kvi_irc_vsnprintf (char * buffer, const char * fmt, kvi_va_list list, bool * bTruncated)
References __range_valid, kvi_va_arg, s, and KviQString::toUtf8().
Referenced by KviIrcConnection::sendFmtData().
bool kvi_matchStringCI (register const char * exp, register const char * str)
bool kvi_matchStringCS (register const char * exp, register const char * str)
bool kvi_matchStringWithTerminator (register const char * exp, register const char * str, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
bool kvi_matchWildExpr (register const char * m1, register const char * m2)
Referenced by KviMediaManager::findMediaTypeForRegularFile().
bool kvi_matchWildExprWithTerminator (register const char * m1, register const char * m2, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
bool kvi_qstringEqualCI (const QString & s1, const QString & s2)
int kvi_strcmpCI (const char * str1, const char * str2)
References __range_valid.
Referenced by kvi_compare().
int kvi_strcmpCS (const char * str1, const char * str2)
References __range_valid.
bool kvi_strEqualCI (const char * str1, const char * str2)
References __range_valid.
Referenced by KviApp::checkFileAssociations(), KviStr::equalsCI(), KviRegisteredChannelDataBase::findExact(), KviMediaManager::findMediaTypeByFileMask(), KviMediaManager::findMediaTypeByIanaType(), KviLocale::init(), parseArgs(), KviServerParser::parseCtcpRequestDcc(), KviServerParser::parseNumeric005(), KviHttpRequest::processHeader(), and KviProxy::setNamedProtocol().
bool kvi_strEqualCIN (const char * str1, const char * str2, int len)
References __range_valid.
Referenced by KviApp::checkFileAssociations(), KviLocale::codecForName(), KviStr::contains(), KviStr::equalsCIN(), KviStr::ext_contains(), KviStr::find(), KviStr::findFirstIdx(), KviStr::findLastIdx(), KviStr::findRev(), KviStr::occurences(), KviIrcUrl::parse(), parseArgs(), KviServerParser::parseNumeric005(), KviIrcSocket::proxyHandleHttpFinalReply(), and KviMenuBar::setupHelpPopup().
bool kvi_strEqualCS (const char * str1, const char * str2) [inline]
References __range_valid.
bool kvi_strEqualCSN (const char * str1, const char * str2, int len) [inline]
References __range_valid.
int kvi_strMatchRevCS (const char * str1, const char * str2, int index)
References __range_valid.
int kvi_vsnprintf (char * buffer, int len, const char * fmt, kvi_va_list list)
References __range_valid, kvi_va_arg, s, and KviQString::toUtf8().
Referenced by KviStr::append(), KviStr::KviStr(), and KviStr::sprintf().
kvi_wslen_t kvi_wstrlen (const kvi_wchar_t * str)
Referenced by KviIrcView::appendText(), KviIrcView::getLinkUnderMouse(), KviStr::KviStr(), and KviIrcView::paintEvent().
Variable Documentation
const char* base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" [static]
Referenced by KviStr::bufferToBase64().
KviStr g_szApplicationWideEmptyString [static]
char hexdigits[16] = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' } [static]
Referenced by KviStr::bufferToHex(), and KviStr::hexEncodeWithTable().
unsigned char iso88591_toLower_map[256]
Referenced by KviQString::lowerISO88591(), and KviStr::toLowerISO88591().
unsigned char iso88591_toUpper_map[256]
Referenced by KviStr::toUpperISO88591(), and KviQString::upperISO88591().