KVIrc: /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/core/kvi_strasm.h File Reference
/home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/core/kvi_strasm.h File Reference
Functions
bool kvi_strEqualCS (const char *pcStr1, const char *pcStr2)
bool kvi_strEqualCSN (const char *pcStr1, const char *pcStr2, int iLen)
bool kvi_strEqualNoLocaleCI (const char *pcStr1, const char *pcStr2)
bool kvi_strEqualNoLocaleCIN (const char *pcStr1, const char *pcStr2, int iLen)
int kvi_strLen (const char *pcStr)
Function Documentation
bool kvi_strEqualCS (const char * pcStr1, const char * pcStr2) [inline]
Referenced by KviStr::equalsCS(), KviParameterList::getBool(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviModuleManager::loadModule(), operator!=(), operator==(), KviServerParser::parseChannelMode(), KviServerParser::parseCtcpRequestClientinfo(), and KviServerParser::parseMessage().
bool kvi_strEqualCSN (const char * pcStr1, const char * pcStr2, int iLen) [inline]
Referenced by KviStr::contains(), KviStr::equalsCSN(), KviStr::ext_contains(), KviStr::find(), KviStr::findFirstIdx(), KviStr::findLastIdx(), KviStr::findRev(), KviStr::occurences(), and KviHttpRequest::processHeader().
bool kvi_strEqualNoLocaleCI (const char * pcStr1, const char * pcStr2) [inline]
bool kvi_strEqualNoLocaleCIN (const char * pcStr1, const char * pcStr2, int iLen) [inline]
int kvi_strLen (const char * pcStr) [inline]