KVIrc: src/kvilib/net/kvi_netutils.h File Reference
src/kvilib/net/kvi_netutils.h File Reference
#include "kvi_settings.h"
#include "kvi_inttypes.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include "kvi_string.h"
Classes
class KviSockaddr
Namespaces
namespace KviNetUtils
Functions
bool KviNetUtils::binaryIpToStringIp (struct in_addr in, QString &szBuffer)
void KviNetUtils::formatNetworkBandwidthString (QString &szBuffer, unsigned int uBytesPerSec)
bool KviNetUtils::getInterfaceAddress (const QString &, QString &)
COMPILE_GET_INTERFACE_ADDRESS.
bool KviNetUtils::isRoutableIp (const char *ipaddr)
bool KviNetUtils::isRoutableIpString (const QString &szIpString)
bool KviNetUtils::isValidStringIp (const QString &szIp)
KVILIB_API bool kvi_getLocalHostAddress (QString &buffer)
KVILIB_API bool kvi_isRoutableIp (const char *ipaddr)
KVILIB_API bool kvi_isRoutableIpString (const char *ipstring)
KVILIB_API bool kvi_select (int fd, bool *bCanRead, bool *bCanWrite, int iUSecs=0)
bool KviNetUtils::stringIpToBinaryIp (const QString &szStringIp, struct in_addr *address)
Function Documentation
KVILIB_API bool kvi_getLocalHostAddress (QString & buffer)
References kvi_binaryIpToStringIp(), and kvi_isRoutableIp().
KVILIB_API bool kvi_isRoutableIp (const char * ipaddr)
Referenced by kvi_getLocalHostAddress(), and kvi_isRoutableIpString().
KVILIB_API bool kvi_isRoutableIpString (const char * ipstring)
References kvi_isRoutableIp(), and kvi_stringIpToBinaryIp().
KVILIB_API bool kvi_select (int fd, bool * bCanRead, bool * bCanWrite, int iUSecs = 0)