KVIrc: src/kvilib/net/kvi_socket.h File Reference
src/kvilib/net/kvi_socket.h File Reference
#include "kvi_settings.h"
#include "kvi_sockettype.h"
#include <errno.h>
#include "kvi_inttypes.h"
#include <sys/time.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <unistd.h>
Defines
#define KVI_INVALID_SOCKET (-1)
(defined(COMPILE_ON_WINDOWS) || (defined(COMPILE_ON_MINGW) && !defined(OS2))
#define kvi_socket_close kvi_socket_destroy
#define kvi_socket_open kvi_socket_create
#define KVI_SOCKET_PF_INET PF_INET
MSG_NOSIGNAL.
#define KVI_SOCKET_PF_INET6 PF_INET6
#define KVI_SOCKET_PF_UNIX PF_UNIX
#define KVI_SOCKET_PROTO_TCP 0
#define kvi_socket_read kvi_socket_recv
#define KVI_SOCKET_TYPE_DGRAM SOCK_DGRAM
#define KVI_SOCKET_TYPE_STREAM SOCK_STREAM
#define kvi_socket_write kvi_socket_send
#define MSG_NOSIGNAL 0
(defined(COMPILE_ON_WINDOWS) || (defined(COMPILE_ON_MINGW) && !defined(OS2))
Functions
kvi_socket_t kvi_socket_accept (kvi_socket_t sock, struct sockaddr *sa, int *salen)
bool kvi_socket_bind (kvi_socket_t sock, const struct sockaddr *sa, int salen)
bool kvi_socket_connect (kvi_socket_t sock, const struct sockaddr *sa, int salen)
kvi_socket_t kvi_socket_create (int pf, int type, int proto)
void kvi_socket_destroy (kvi_socket_t sock)
int kvi_socket_error ()
void kvi_socket_flushTrafficCounters ()
bool kvi_socket_getsockname (kvi_socket_t sock, struct sockaddr *addr, int *addrlen)
bool kvi_socket_getsockopt (kvi_socket_t sock, int level, int optname, void *optval, int *optlen)
bool kvi_socket_isValid (kvi_socket_t sock)
bool kvi_socket_listen (kvi_socket_t sock, int backlog)
bool kvi_socket_recoverableConnectError (int err)
bool kvi_socket_recoverableError (int err)
int kvi_socket_recv (kvi_socket_t sock, void *buf, int maxlen)
int kvi_socket_select (int nhpo, fd_set *r, fd_set *w, fd_set *e, struct timeval *t)
int kvi_socket_send (kvi_socket_t sock, const void *buf, int size)
bool kvi_socket_setNonBlocking (kvi_socket_t sock)
bool kvi_socket_setsockopt (kvi_socket_t sock, int level, int optname, const void *optval, int optlen)
Variables
KVILIB_API kvi_u64_t g_uIncomingTraffic
KVILIB_API kvi_u64_t g_uOutgoingTraffic
Define Documentation
#define KVI_INVALID_SOCKET (-1)
(defined(COMPILE_ON_WINDOWS) || (defined(COMPILE_ON_MINGW) && !defined(OS2))
Referenced by KviIrcSocket::connectionEstabilished(), DccMarshal::dccConnect(), DccMarshal::dccListen(), DccMarshal::DccMarshal(), DccMarshal::doConnect(), DccMarshal::doListen(), kvi_socket_isValid(), KviIrcSocket::KviIrcSocket(), KviIrcSocket::linkUp(), DccMarshal::releaseSocket(), DccMarshal::reset(), KviIrcSocket::reset(), KviIdentDaemon::run(), DccVoiceThread::run(), DccVideoThread::run(), DccSendThread::run(), DccRecvThread::run(), DccChatThread::run(), DccMarshal::snActivated(), and DccThread::~DccThread().
#define kvi_socket_close kvi_socket_destroy
Referenced by DccMarshal::reset(), KviIdentDaemon::run(), DccVoiceThread::run(), DccVideoThread::run(), DccSendThread::run(), DccRecvThread::run(), DccChatThread::run(), DccMarshal::snActivated(), DccThread::~DccThread(), and KviIdentRequest::~KviIdentRequest().
#define kvi_socket_open kvi_socket_create
#define KVI_SOCKET_PF_INET PF_INET
MSG_NOSIGNAL.
Referenced by DccMarshal::doConnect(), DccMarshal::doListen(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
#define KVI_SOCKET_PF_INET6 PF_INET6
Referenced by DccMarshal::doConnect(), DccMarshal::doListen(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
#define KVI_SOCKET_PF_UNIX PF_UNIX
#define KVI_SOCKET_PROTO_TCP 0
Referenced by DccMarshal::doConnect(), DccMarshal::doListen(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
#define kvi_socket_read kvi_socket_recv
#define KVI_SOCKET_TYPE_DGRAM SOCK_DGRAM
#define KVI_SOCKET_TYPE_STREAM SOCK_STREAM
Referenced by DccMarshal::doConnect(), DccMarshal::doListen(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
#define kvi_socket_write kvi_socket_send
Referenced by KviIdentDaemon::run().
#define MSG_NOSIGNAL 0
(defined(COMPILE_ON_WINDOWS) || (defined(COMPILE_ON_MINGW) && !defined(OS2))
Referenced by kvi_socket_recv(), and kvi_socket_send().
Function Documentation
kvi_socket_t kvi_socket_accept (kvi_socket_t sock, struct sockaddr * sa, int * salen) [inline]
Referenced by KviIdentDaemon::run(), and DccMarshal::snActivated().
bool kvi_socket_bind (kvi_socket_t sock, const struct sockaddr * sa, int salen) [inline]
Referenced by DccMarshal::doListen(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
bool kvi_socket_connect (kvi_socket_t sock, const struct sockaddr * sa, int salen) [inline]
References connect().
Referenced by DccMarshal::doConnect(), and KviIrcSocket::startConnection().
kvi_socket_t kvi_socket_create (int pf, int type, int proto) [inline]
Referenced by DccMarshal::doConnect(), DccMarshal::doListen(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
void kvi_socket_destroy (kvi_socket_t sock) [inline]
Referenced by KviIrcSocket::reset().
int kvi_socket_error () [inline]
Referenced by DccMarshal::doConnect(), DccMarshal::doSSLHandshake(), KviIrcSocket::doSSLHandshake(), KviIrcSocket::flushSendQueue(), DccThread::handleInvalidSocketRead(), KviIrcSocket::handleInvalidSocketRead(), KviIdentDaemon::run(), DccSendThread::run(), DccRecvThread::sendAck(), KviIrcSocket::startConnection(), and DccChatThread::tryFlushOutBuffers().
void kvi_socket_flushTrafficCounters () [inline]
References g_uIncomingTraffic, and g_uOutgoingTraffic.
Referenced by KviApplication::KviApplication().
bool kvi_socket_getsockname (kvi_socket_t sock, struct sockaddr * addr, int * addrlen) [inline]
Referenced by DccMarshal::doListen(), KviIrcSocket::getLocalHostIp(), and DccMarshal::snActivated().
bool kvi_socket_getsockopt (kvi_socket_t sock, int level, int optname, void * optval, int * optlen) [inline]
Referenced by DccMarshal::doConnect(), DccMarshal::snActivated(), KviIrcSocket::startConnection(), and KviIrcSocket::writeNotifierFired().
bool kvi_socket_isValid (kvi_socket_t sock) [inline]
References KVI_INVALID_SOCKET.
Referenced by KviIrcSocket::reset().
bool kvi_socket_listen (kvi_socket_t sock, int backlog) [inline]
Referenced by DccMarshal::doListen(), and KviIdentDaemon::run().
bool kvi_socket_recoverableConnectError (int err) [inline]
Referenced by DccMarshal::doConnect(), KviIdentDaemon::run(), and KviIrcSocket::startConnection().
bool kvi_socket_recoverableError (int err) [inline]
Referenced by DccMarshal::doSSLHandshake(), and KviIrcSocket::doSSLHandshake().
int kvi_socket_recv (kvi_socket_t sock, void * buf, int maxlen) [inline]
References g_uIncomingTraffic, and MSG_NOSIGNAL.
Referenced by KviIrcSocket::readData(), KviIrcSocket::readHttpProxyErrorData(), KviIrcSocket::readProxyData(), DccVoiceThread::readWriteStep(), DccVideoThread::readWriteStep(), KviIdentDaemon::run(), DccSendThread::run(), DccRecvThread::run(), and DccChatThread::run().
int kvi_socket_select (int nhpo, fd_set * r, fd_set * w, fd_set * e, struct timeval * t) [inline]
Referenced by KviIdentDaemon::run().
int kvi_socket_send (kvi_socket_t sock, const void * buf, int size) [inline]
References g_uOutgoingTraffic, and MSG_NOSIGNAL.
Referenced by KviIrcSocket::flushSendQueue(), DccVoiceThread::readWriteStep(), DccVideoThread::readWriteStep(), DccSendThread::run(), DccRecvThread::sendAck(), and DccChatThread::tryFlushOutBuffers().
bool kvi_socket_setNonBlocking (kvi_socket_t sock) [inline]
Referenced by DccMarshal::doConnect(), KviIdentDaemon::run(), DccMarshal::snActivated(), and KviIrcSocket::startConnection().
bool kvi_socket_setsockopt (kvi_socket_t sock, int level, int optname, const void * optval, int optlen) [inline]
Referenced by KviIdentDaemon::run().
Variable Documentation
KVILIB_API kvi_u64_t g_uIncomingTraffic
Referenced by kvi_socket_flushTrafficCounters(), kvi_socket_recv(), KviIOGraphWidget::KviIOGraphWidget(), KviKvsCoreFunctions::KVSCF(), and KviIOGraphWidget::timerEvent().
KVILIB_API kvi_u64_t g_uOutgoingTraffic
Referenced by kvi_socket_flushTrafficCounters(), kvi_socket_send(), KviIOGraphWidget::KviIOGraphWidget(), KviKvsCoreFunctions::KVSCF(), and KviIOGraphWidget::timerEvent().