KVIrc: src/kvirc/kernel/kvi_coreactions.cpp File Reference
src/kvirc/kernel/kvi_coreactions.cpp File Reference
#include "kvi_coreactions.h"
#include "kvi_shortcuts.h"
#include "kvi_frame.h"
#include "kvi_locale.h"
#include "kvi_irccontext.h"
#include "kvi_iconmanager.h"
#include "kvi_app.h"
#include "kvi_customtoolbar.h"
#include "kvi_actiondrawer.h"
#include "kvi_actionmanager.h"
#include "kvi_kvs_action.h"
#include "kvi_mdimanager.h"
#include "kvi_irctoolbar.h"
#include "kvi_ircurl.h"
#include "kvi_ircconnection.h"
#include "kvi_ircconnectionuserinfo.h"
#include "kvi_settings.h"
#include "kvi_qstring.h"
#include "kvi_time.h"
#include "kvi_inttypes.h"
#include <QStringList>
#include "kvi_kvs_script.h"
#include "kvi_tal_popupmenu.h"
#include <QObject>
Defines
#define SCRIPT_ACTION(__name, __code, __visible, __description, __category, __icon, __smallicon, __flags, __accel)
#define SLOT_ACTION(__name, __object, __slot, __visible, __description, __category, __icon, __smallicon, __flags, __accel)
Functions
void register_core_actions (KviActionManager *m)
Define Documentation
#define SCRIPT_ACTION (__name, __code, __visible, __description, __category, __icon, __smallicon, __flags, __accel)
Value:
a = new KviKvsAction(m, \
                QString(__name), \
                QString(__code), \
                QString(__visible), \
                QString(__description), \
                __category, \
                QString(__icon), \
                QString("%1").arg(__smallicon), \
                __flags, \
                __accel); \
        m->registerAction(a)
Referenced by register_core_actions().
#define SLOT_ACTION (__name, __object, __slot, __visible, __description, __category, __icon, __smallicon, __flags, __accel)
Value:
a = new KviAction(m, \
                QString(__name), \
                QString(__visible), \
                QString(__description), \
                __category, \
                QString(__icon), \
                QString("%1").arg(__smallicon), \
                __flags, \
                __accel); \
        QObject::connect(a,SIGNAL(activated()),__object,__slot); \
        m->registerAction(a)
Referenced by register_core_actions().
Function Documentation
void register_core_actions (KviActionManager * m)
References __tr2qs, KviActionManager::categoryGeneric(), KviActionManager::categoryGUI(), KviActionManager::categoryIrc(), KviActionManager::categoryScripting(), KviActionManager::categorySettings(), g_pApp, g_pFrame, KVI_COREACTION_ACTIONEDITOR, KVI_COREACTION_ALIASEDITOR, KVI_COREACTION_CASCADEWINDOWS, KVI_COREACTION_CHANNELLIST, KVI_COREACTION_CLASSEDITOR, KVI_COREACTION_CODETESTER, KVI_COREACTION_EDITREGUSERS, KVI_COREACTION_EVENTEDITOR, KVI_COREACTION_EXECUTEKVS, KVI_COREACTION_GENERALOPTIONS, KVI_COREACTION_HELPINDEX, KVI_COREACTION_IDENTITYOPTIONS, KVI_COREACTION_JOINCHANNELS, KVI_COREACTION_KVIRCHOMEPAGE, KVI_COREACTION_KVIRCMAILINGLIST, KVI_COREACTION_KVIRCRUHOMEPAGE, KVI_COREACTION_MANAGEADDONS, KVI_COREACTION_MANAGETHEMES, KVI_COREACTION_MINIMIZEALLWINDOWS, KVI_COREACTION_NETWORKLINKS, KVI_COREACTION_NEWIRCCONTEXT, KVI_COREACTION_POPUPEDITOR, KVI_COREACTION_QUITKVIRC, KVI_COREACTION_RAWEDITOR, KVI_COREACTION_SCREENSHOT, KVI_COREACTION_SERVEROPTIONS, KVI_COREACTION_SOCKETSPY, KVI_COREACTION_THEMEOPTIONS, KVI_COREACTION_TILEWINDOWS, KVI_COREACTION_TOOLBAREDITOR, KVI_SHORTCUTS_CONTEXT, KVI_SHORTCUTS_EDITORS_ACTION, KVI_SHORTCUTS_EDITORS_ALIAS, KVI_SHORTCUTS_EDITORS_CLASS, KVI_SHORTCUTS_EDITORS_EVENT, KVI_SHORTCUTS_EDITORS_POPUP, KVI_SHORTCUTS_EDITORS_RAW, KVI_SHORTCUTS_EDITORS_TESTER, KVI_SHORTCUTS_EDITORS_TOOLBAR, KVI_SHORTCUTS_EXEC, KVI_SHORTCUTS_HELP, KVI_SHORTCUTS_IDENTITY, KVI_SHORTCUTS_JOIN, KVI_SHORTCUTS_MANAGE_ADDONS, KVI_SHORTCUTS_MANAGE_THEMES, KVI_SHORTCUTS_OPTIONS, KVI_SHORTCUTS_SERVERS, KVI_SHORTCUTS_THEME, KVI_SHORTCUTS_USERS, KVI_SMALLICON_ADDONS, KVI_SMALLICON_ALIAS, KVI_SMALLICON_BOMB, KVI_SMALLICON_CASCADEWINDOWS, KVI_SMALLICON_CHANNEL, KVI_SMALLICON_CLASSEDITOR, KVI_SMALLICON_CONSOLE, KVI_SMALLICON_EVENT, KVI_SMALLICON_FOLDER, KVI_SMALLICON_HELP, KVI_SMALLICON_KVIRC, KVI_SMALLICON_LINKS, KVI_SMALLICON_LIST, KVI_SMALLICON_MESSAGE, KVI_SMALLICON_MINIMIZE, KVI_SMALLICON_OPTIONS, KVI_SMALLICON_POPUP, KVI_SMALLICON_QUITAPP, KVI_SMALLICON_RAWEVENT, KVI_SMALLICON_REGUSERS, KVI_SMALLICON_SCREENSHOT, KVI_SMALLICON_SCRIPTACTION, KVI_SMALLICON_SERVER, KVI_SMALLICON_SPY, KVI_SMALLICON_THEME, KVI_SMALLICON_THEMEOPTIONS, KVI_SMALLICON_TILEWINDOWS, KVI_SMALLICON_TOOLBAR, KVI_SMALLICON_WHO, KviFrame::mdiManager(), KviAction::NeedsConnection, KviAction::NeedsContext, KviActionManager::registerAction(), SCRIPT_ACTION, and SLOT_ACTION.
Referenced by KviActionManager::getAction(), and KviActionManager::loadAllAvailableActions().