KVIrc: src/kvirc/kvs/kvi_kvs_moduleinterface.cpp File Reference
src/kvirc/kvs/kvi_kvs_moduleinterface.cpp File Reference
#include "kvi_kvs_moduleinterface.h"
#include "kvi_kvs_eventmanager.h"
#include "kvi_module.h"
#include "kvi_modulemanager.h"
#include "kvi_locale.h"
#include "kvi_kvs_treenode_data.h"
#include "kvi_kvs_treenode_datalist.h"
Defines
#define COMPLETE_WORD_BY_DICT(__word, __list, __type, __dict)
Functions
static bool default_module_kvs_cmd_load (KviKvsModuleCommandCall *)
static bool default_module_kvs_cmd_unload (KviKvsModuleCommandCall *c)
Define Documentation
#define COMPLETE_WORD_BY_DICT (__word, __list, __type, __dict)
Value:
{ \
                KviPointerHashTableIterator<QString,__type> it(*__dict); \
                int l = __word.length(); \
                while(it.current()) \
                { \
                        if(KviQString::equalCIN(__word,it.currentKey(),l)) \
                                __list->append(new QString(it.currentKey())); \
                        ++it; \
                } \
        }
Referenced by KviKvsModuleInterface::completeCommand(), and KviKvsModuleInterface::completeFunction().
Function Documentation
static bool default_module_kvs_cmd_load (KviKvsModuleCommandCall *) [static]
Referenced by KviKvsModuleInterface::registerDefaultCommands().
static bool default_module_kvs_cmd_unload (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx, KviKvsSwitchList::find(), g_pModuleManager, KviModule::isLocked(), KviKvsModuleRunTimeCall::module(), KviModule::name(), KviKvsModuleCommandCall::switches(), KviModuleManager::unloadModule(), and KviKvsRunTimeCall::warning().
Referenced by KviKvsModuleInterface::registerDefaultCommands().