KVIrc: src/kvilib/core/kvi_memmove.h File Reference
src/kvilib/core/kvi_memmove.h File Reference
This file contains an internal implementation of the memove/memcpy functions.
#include "kvi_settings.h"
Functions
void kvi_fastmove (void *dst_ptr, const void *src_ptr, int len)
Moves len bytes from src_ptr to dst_ptr.
void kvi_fastmoveodd (void *dst_ptr, const void *src_ptr, int len)
Moves an odd number of bytes (specified in len) from src_ptr to dst_ptr.
void * kvi_memmove (void *dst_ptr, const void *src_ptr, int len)
Moves len bytes from src_ptr to dst_ptr.
void * kvi_memmoveodd (void *dst_ptr, const void *src_ptr, int len)
Moves an odd number of bytes (specified in len) from src_ptr to dst_ptr.
void * kvi_memset (void *dst_ptr, char c, int len)
Initializes len bytes of memory starting from dst_ptr to c.
Detailed Description
This file contains an internal implementation of the memove/memcpy functions.
Author:
Szymon Stefanek If COMPILE_WITH_SYSTEM_MEMMOVE is disabled, kvirc will use its internal implementation of the memmove/memcpy family of functions. If COMPILE_ix86_ASM is enabled, the implementation is based on x86 (32-bit only) asm.
Function Documentation
void kvi_fastmove (void * dst_ptr, const void * src_ptr, int len)
Moves len bytes from src_ptr to dst_ptr.
Parameters:
dst_ptr The destination memory pointer
src_ptr The source memory pointer
len the number of bytes to move
Returns:
void *
Warning:
In fastmove the src and dst may not overlap
References __range_valid.
Referenced by KviStr::append(), KviStr::extractFromString(), KviStr::getLine(), KviStr::getToken(), KviStr::insert(), kvi_extractToken(), kvi_extractUpTo(), kvi_hash_key_copy(), KviStr::KviStr(), KviStr::operator=(), KviStr::prepend(), and KviStr::replaceAll().
void kvi_fastmoveodd (void * dst_ptr, const void * src_ptr, int len)
Moves an odd number of bytes (specified in len) from src_ptr to dst_ptr.
Parameters:
dst_ptr The destination memory pointer
src_ptr The source memory pointer
len the number of bytes to move; has to be odd
Returns:
void *
Warning:
In fastmove the src and dst may not overlap
References __range_valid.
Referenced by KviIrcView::getTextLine().
void* kvi_memmove (void * dst_ptr, const void * src_ptr, int len)
Moves len bytes from src_ptr to dst_ptr.
Parameters:
dst_ptr The destination memory pointer
src_ptr The source memory pointer
len the number of bytes to move
Returns:
void *
References __range_valid.
Referenced by KviDataBuffer::append(), KviStr::cut(), KviStr::cutLeft(), KviStr::hexDecode(), KviStr::hexEncodeWithTable(), KviStr::insert(), KviDataBuffer::KviDataBuffer(), KviConfig::load(), KviStr::operator=(), KviStr::prepend(), KviIrcLink::processData(), KviIrcSocket::proxyAuthUserPassV5(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), KviDataBuffer::remove(), KviIrcConnection::sendData(), KviIrcSocket::sendRawData(), KviStr::setStr(), KviStr::stripLeft(), KviStr::stripLeftWhiteSpace(), KviStr::stripSpace(), and KviStr::trimmed().
void* kvi_memmoveodd (void * dst_ptr, const void * src_ptr, int len)
Moves an odd number of bytes (specified in len) from src_ptr to dst_ptr.
Parameters:
dst_ptr The destination memory pointer
src_ptr The source memory pointer
len the number of bytes to move; has to be odd
Returns:
void *
References __range_valid.
void* kvi_memset (void * dst_ptr, char c, int len)
Initializes len bytes of memory starting from dst_ptr to c.
Parameters:
dst_ptr The destination memory pointer
c The character that will fill the memory
len the number of bytes to initialize
Returns:
void *
References __range_valid.
Referenced by KviIrcViewToolWidget::filterLoad(), kvi_sendIpcMessage(), and KviSockaddr::KviSockaddr().