KVIrc: src/kvirc/kernel/KviActionManager.cpp File Reference
KviActionManager.cpp File Reference
#include "KviActionManager.h"
#include "KviModuleManager.h"
#include "KviCoreActions.h"
#include "KviCustomToolBar.h"
#include "KviCustomToolBarManager.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviKvsUserAction.h"
#include "KviConfigurationFile.h"
#include "KviMainWindow.h"
Macros
#define CATEGORY(__var, __name, __vname, __descr)
Functions
void register_core_actions (KviActionManager *)
Macro Definition Documentation
#define CATEGORY (__var, __name, __vname, __descr)
Value:
__var = new KviActionCategory(__name, __vname, __descr); \
        m_pCategories->replace(__name, __var)
Referenced by KviActionManager::KviActionManager().
Function Documentation
void register_core_actions (KviActionManager *)
References __tr2qs, a, KviIconManager::ActionEditor, KviIconManager::Addons, KviIconManager::AliasEditor, KviIconManager::Bomb, KviActionManager::categoryGeneric(), KviActionManager::categoryIrc(), KviActionManager::categoryScripting(), KviActionManager::categorySettings(), KviIconManager::Channel, KviIconManager::ClassEditor, KviIconManager::EventEditor, KviIconManager::FileTransfer, KviIconManager::Folder, g_pApp, g_pMainWindow, KviIconManager::Help, KviIconManager::HomePage, KviIconManager::Identity, KVI_COREACTION_ACTIONEDITOR, KVI_COREACTION_ALIASEDITOR, KVI_COREACTION_CHANNELLIST, KVI_COREACTION_CLASSEDITOR, KVI_COREACTION_CODETESTER, KVI_COREACTION_EDITREGUSERS, KVI_COREACTION_EVENTEDITOR, KVI_COREACTION_EXECUTEKVS, KVI_COREACTION_FILETRANSFER, KVI_COREACTION_GENERALOPTIONS, KVI_COREACTION_HELPINDEX, KVI_COREACTION_IDENTITYOPTIONS, KVI_COREACTION_IOGRAPH, KVI_COREACTION_JOINCHANNELS, KVI_COREACTION_KVIRCHOMEPAGE, KVI_COREACTION_KVIRCMAILINGLIST, KVI_COREACTION_KVIRCRUHOMEPAGE, KVI_COREACTION_LOGVIEWER, KVI_COREACTION_MANAGEADDONS, KVI_COREACTION_MANAGETHEMES, KVI_COREACTION_NETWORKLINKS, KVI_COREACTION_NEWIRCCONTEXT, KVI_COREACTION_POPUPEDITOR, KVI_COREACTION_QUITKVIRC, KVI_COREACTION_RAWEDITOR, KVI_COREACTION_SCREENSHOT, KVI_COREACTION_SERVEROPTIONS, KVI_COREACTION_SHAREDFILES, KVI_COREACTION_SOCKETSPY, KVI_COREACTION_THEMEOPTIONS, KVI_COREACTION_TOOLBAREDITOR, KVI_COREACTION_URLLIST, KVI_SHORTCUTS_CONTEXT, KVI_SHORTCUTS_EDITORS_ACTION, KVI_SHORTCUTS_EDITORS_ALIAS, KVI_SHORTCUTS_EDITORS_CLASS, KVI_SHORTCUTS_EDITORS_EVENT, KVI_SHORTCUTS_EDITORS_POPUP, KVI_SHORTCUTS_EDITORS_RAW, KVI_SHORTCUTS_EDITORS_TESTER, KVI_SHORTCUTS_EDITORS_TOOLBAR, KVI_SHORTCUTS_EXEC, KVI_SHORTCUTS_HELP, KVI_SHORTCUTS_IDENTITY, KVI_SHORTCUTS_JOIN, KVI_SHORTCUTS_MANAGE_ADDONS, KVI_SHORTCUTS_MANAGE_THEMES, KVI_SHORTCUTS_OPTIONS, KVI_SHORTCUTS_QUIT, KVI_SHORTCUTS_SERVERS, KVI_SHORTCUTS_THEME, KVI_SHORTCUTS_USERS, KviIconManager::Links, KviIconManager::List, KviIconManager::Log, KviIconManager::Message, KviAction::NeedsConnection, KviAction::NeedsContext, KviIconManager::NewItem, KviIconManager::Options, KviIconManager::PopupEditor, quit(), KviIconManager::QuitApp, KviIconManager::RawEventEditor, KviActionManager::registerAction(), KviIconManager::RegUsers, KviIconManager::ScreenShot, SCRIPT_ACTION, KviIconManager::ServerConfiguration, KviIconManager::SharedFiles, SLOT_ACTION, KviIconManager::Spy, KviIconManager::SysMonitor, KviIconManager::Theme, KviIconManager::ThemeOptions, KviIconManager::ToolBarEditor, and KviIconManager::Url.
Referenced by KviActionManager::getAction(), and KviActionManager::loadAllAvailableActions().