KVIrc: src/kvilib/core/KviCString.cpp File Reference
src/kvilib/core/KviCString.cpp File Reference
#include "kvi_debug.h"
#include "KviCString.h"
#include "KviMemory.h"
Defines
#define _KVI_STRING_CPP_
#define NOT_AT_END(__str) (*__str && (*__str != terminator))
#define NOT_AT_END(__str) (*__str && (*__str != terminator))
Functions
static unsigned char get_base64_idx (char base64)
static char get_decimal_from_hex_digit_char (char dgt)
const char * kvi_extractToken (KviCString &str, const char *aux_ptr, char sep)
const char * kvi_extractUpTo (KviCString &str, const char *aux_ptr, char sep)
int kvi_irc_vsnprintf (char *buffer, const char *fmt, kvi_va_list list, bool *bTruncated)
bool kvi_matchStringCI (register const char *exp, register const char *str)
bool kvi_matchStringCS (register const char *exp, register const char *str)
bool kvi_matchStringWithTerminator (register const char *exp, register const char *str, char terminator, const char **r1, const char **r2)
bool kvi_matchWildExpr (register const char *m1, register const char *m2)
bool kvi_matchWildExprWithTerminator (register const char *m1, register const char *m2, char terminator, const char **r1, const char **r2)
bool kvi_qstringEqualCI (const QString &s1, const QString &s2)
int kvi_strcmpCI (const char *str1, const char *str2)
int kvi_strcmpCS (const char *str1, const char *str2)
bool kvi_strEqualCI (const char *str1, const char *str2)
bool kvi_strEqualCIN (const char *str1, const char *str2, int len)
bool kvi_strEqualCS (const char *str1, const char *str2)
bool kvi_strEqualCSN (const char *str1, const char *str2, int len)
int kvi_strMatchRevCS (const char *str1, const char *str2, int index)
int kvi_vsnprintf (char *buffer, int len, const char *fmt, kvi_va_list list)
kvi_wslen_t kvi_wstrlen (const kvi_wchar_t *str)
Variables
static const char * base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
static KviCString g_szApplicationWideEmptyString
static char hexdigits [16] = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' }
unsigned char iso88591_toLower_map [256]
unsigned char iso88591_toUpper_map [256]
Define Documentation
#define _KVI_STRING_CPP_
#define NOT_AT_END (__str) (*__str && (*__str != terminator))
#define NOT_AT_END (__str) (*__str && (*__str != terminator))
Referenced by kvi_matchStringWithTerminator(), and kvi_matchWildExprWithTerminator().
Function Documentation
static unsigned char get_base64_idx (char base64) [static]
Referenced by KviCString::base64ToBuffer().
static char get_decimal_from_hex_digit_char (char dgt) [static]
Referenced by KviCString::hexDecode(), and KviCString::hexToBuffer().
const char* kvi_extractToken (KviCString & str, const char * aux_ptr, char sep)
References KviMemory::copy(), KVI_ASSERT, KviCString::m_len, KviCString::m_ptr, p, and KviMemory::reallocate().
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), and KviParameterList::KviParameterList().
const char* kvi_extractUpTo (KviCString & str, const char * aux_ptr, char sep)
References KviMemory::copy(), KVI_ASSERT, KviCString::m_len, KviCString::m_ptr, p, and KviMemory::reallocate().
int kvi_irc_vsnprintf (char * buffer, const char * fmt, kvi_va_list list, bool * bTruncated)
References KVI_ASSERT, kvi_va_arg, p, s, and t.
Referenced by KviIrcConnection::sendFmtData().
bool kvi_matchStringCI (register const char * exp, register const char * str)
bool kvi_matchStringCS (register const char * exp, register const char * str)
bool kvi_matchStringWithTerminator (register const char * exp, register const char * str, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
bool kvi_matchWildExpr (register const char * m1, register const char * m2)
Referenced by KviMediaManager::findMediaTypeForRegularFile().
bool kvi_matchWildExprWithTerminator (register const char * m1, register const char * m2, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
bool kvi_qstringEqualCI (const QString & s1, const QString & s2)
References l.
int kvi_strcmpCI (const char * str1, const char * str2)
References KVI_ASSERT.
Referenced by kvi_compare().
int kvi_strcmpCS (const char * str1, const char * str2)
References KVI_ASSERT.
bool kvi_strEqualCI (const char * str1, const char * str2)
References KVI_ASSERT.
Referenced by KviApplication::checkFileAssociations(), OptionsWidget_proxy::currentItemChanged(), dccModuleParseDccChat(), KviCString::equalsCI(), OptionsInstanceManager::findInstanceEntry(), KviMediaManager::findMediaTypeByFileMask(), KviMediaManager::findMediaTypeByIanaType(), LinksWindow::getItemByHost(), DccBroker::handleResumeRequest(), KviLocale::init(), kvi_dcc_video_get_codec(), kvi_dcc_video_is_valid_codec(), kvi_dcc_voice_get_codec(), kvi_dcc_voice_is_valid_codec(), mediaplayer_module_ctrl(), notifier_module_ctrl(), parseArgs(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseNumeric005(), KviHttpRequest::processHeader(), DccFileTransfer::resumeAccepted(), KviIdentDaemon::run(), KviProxy::setNamedProtocol(), snd_module_ctrl(), and system_kvs_fnc_dbus().
bool kvi_strEqualCIN (const char * str1, const char * str2, int len)
References KVI_ASSERT.
Referenced by KviApplication::checkFileAssociations(), KviLocale::codecForName(), KviCString::contains(), KviCString::equalsCIN(), DccVideoWindow::event(), DccChatWindow::event(), KviCString::ext_contains(), KviCString::find(), KviCString::findFirstIdx(), KviCString::findLastIdx(), KviCString::findRev(), KviCString::occurences(), KviIrcUrl::parse(), parseArgs(), KviIrcServerParser::parseNumeric005(), KviIrcSocket::proxyHandleHttpFinalReply(), KviIrcSocket::queue_removePrivateMessages(), and KviMenuBar::setupHelpPopup().
bool kvi_strEqualCS (const char * str1, const char * str2)
References KVI_ASSERT.
Referenced by dccModuleCtcpDccParseRoutine(), dccModuleParseDccSend(), KviCString::equalsCS(), KviParameterList::getBool(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviModuleManager::loadModule(), operator!=(), operator==(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCtcpRequestClientinfo(), KviIrcServerParser::parseMessage(), perlcore_module_ctrl(), and pythoncore_module_ctrl().
bool kvi_strEqualCSN (const char * str1, const char * str2, int len)
References KVI_ASSERT.
Referenced by KviCString::contains(), KviCString::equalsCSN(), KviCString::ext_contains(), KviCString::find(), KviCString::findFirstIdx(), KviCString::findLastIdx(), KviCString::findRev(), KviCString::occurences(), and KviHttpRequest::processHeader().
int kvi_strMatchRevCS (const char * str1, const char * str2, int index)
References KVI_ASSERT.
int kvi_vsnprintf (char * buffer, int len, const char * fmt, kvi_va_list list)
References hexdigits, KVI_ASSERT, kvi_va_arg, p, s, and t.
Referenced by KviCString::append(), KviCString::KviCString(), KviCString::sprintf(), and KviCString::vsprintf().
kvi_wslen_t kvi_wstrlen (const kvi_wchar_t * str)
Referenced by KviIrcView::getLinkUnderMouse(), KviCString::KviCString(), and KviIrcView::paintEvent().
Variable Documentation
const char* base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" [static]
Referenced by KviCString::bufferToBase64().
KviCString g_szApplicationWideEmptyString [static]
Referenced by KviCString::emptyString().
char hexdigits[16] = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' } [static]
Referenced by KviCString::bufferToHex(), KviCString::hexEncodeWithTable(), and kvi_vsnprintf().
unsigned char iso88591_toLower_map[256]
Referenced by KviQString::lowerISO88591(), and KviCString::toLowerISO88591().
unsigned char iso88591_toUpper_map[256]
Referenced by KviCString::toUpperISO88591(), and KviQString::upperISO88591().