KVIrc: src/kvilib/core/KviCString.h File Reference
src/kvilib/core/KviCString.h File Reference
#include "kvi_settings.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <QtGlobal>
#include <QString>
#include <QByteArray>
#include "kvi_inttypes.h"
#include "KviHeapObject.h"
#include "kvi_stdarg.h"
Classes
class KviCString
Defines
#define __KVI_EXTERN extern
#define kvi_matchString kvi_matchStringCI
#define kvi_strEqualNoLocaleCI(str1, str2) kvi_strEqualCI(str1,str2)
#define kvi_strEqualNoLocaleCIN(str1, str2, len) kvi_strEqualCIN(str1,str2,len)
#define kvi_strLen(str) strlen(str)
Typedefs
typedef kvi_u16_t kvi_wchar_t
typedef kvi_u32_t kvi_wslen_t
Functions
int kvi_compare (const KviCString *p1, const KviCString *p2)
__KVI_EXTERN KVILIB_API const
char * kvi_extractToken (KviCString &str, const char *aux_ptr, char sep=' ')
__KVI_EXTERN KVILIB_API const
char * kvi_extractUpTo (KviCString &str, const char *aux_ptr, char sep=' ')
__KVI_EXTERN KVILIB_API int kvi_irc_vsnprintf (char *buffer, const char *fmt, kvi_va_list list, bool *bTruncated)
__KVI_EXTERN KVILIB_API bool kvi_matchStringCI (register const char *exp, register const char *str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringCS (register const char *exp, register const char *str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringWithTerminator (register const char *exp, register const char *str, char terminator, const char **r1, const char **r2)
__KVI_EXTERN KVILIB_API bool kvi_matchWildExpr (register const char *m1, register const char *m2)
__KVI_EXTERN KVILIB_API bool kvi_matchWildExprWithTerminator (register const char *m1, register const char *m2, char terminator, const char **r1, const char **r2)
__KVI_EXTERN KVILIB_API bool kvi_qstringEqualCI (const QString &s1, const QString &s2)
__KVI_EXTERN KVILIB_API int kvi_strcmpCI (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API int kvi_strcmpCS (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCI (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCIN (const char *str1, const char *str2, int len)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCS (const char *str1, const char *str2)
__KVI_EXTERN KVILIB_API bool kvi_strEqualCSN (const char *str1, const char *str2, int len)
__KVI_EXTERN KVILIB_API int kvi_strMatchRevCS (const char *str1, const char *str2, int index=-1)
__KVI_EXTERN KVILIB_API int kvi_vsnprintf (char *buffer, int len, const char *fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API kvi_wslen_t kvi_wstrlen (const kvi_wchar_t *str)
__KVI_EXTERN KVILIB_API int kvi_wvsnprintcf (kvi_wchar_t *buffer, kvi_wslen_t len, const char *fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API int kvi_wvsnprintf (kvi_wchar_t *buffer, kvi_wslen_t len, const kvi_wchar_t *fmt, kvi_va_list list)
__KVI_EXTERN bool operator!= (const KviCString &left, const char *right)
__KVI_EXTERN bool operator!= (const KviCString &left, const KviCString &right)
__KVI_EXTERN bool operator!= (const char *left, const KviCString &right)
__KVI_EXTERN KviCString operator+ (char left, const KviCString &right)
__KVI_EXTERN KviCString operator+ (const KviCString &left, const KviCString &right)
__KVI_EXTERN KviCString operator+ (const KviCString &left, char right)
__KVI_EXTERN KviCString operator+ (const char *left, const KviCString &right)
__KVI_EXTERN KviCString operator+ (const KviCString &left, const char *right)
__KVI_EXTERN bool operator== (const char *left, const KviCString &right)
__KVI_EXTERN bool operator== (const KviCString &left, const char *right)
__KVI_EXTERN bool operator== (const KviCString &left, const KviCString &right)
Define Documentation
#define __KVI_EXTERN extern
#define kvi_matchString kvi_matchStringCI
#define kvi_strEqualNoLocaleCI (str1, str2) kvi_strEqualCI(str1,str2)
#define kvi_strEqualNoLocaleCIN (str1, str2, len) kvi_strEqualCIN(str1,str2,len)
#define kvi_strLen (str) strlen(str)
Referenced by kvi_hash_key_copy(), parseArgs(), and str_kvs_fnc_printf().
Typedef Documentation
typedef kvi_u16_t kvi_wchar_t
typedef kvi_u32_t kvi_wslen_t
Function Documentation
int kvi_compare (const KviCString * p1, const KviCString * p2) [inline]
References kvi_strcmpCI(), and KviCString::ptr().
Referenced by KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::inSort(), and KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::merge().
__KVI_EXTERN KVILIB_API const char* kvi_extractToken (KviCString & str, const char * aux_ptr, char sep = ' ')
References KviMemory::copy(), KVI_ASSERT, KviCString::m_len, KviCString::m_ptr, p, and KviMemory::reallocate().
Referenced by KviStupidNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), and KviParameterList::KviParameterList().
__KVI_EXTERN KVILIB_API const char* kvi_extractUpTo (KviCString & str, const char * aux_ptr, char sep = ' ')
References KviMemory::copy(), KVI_ASSERT, KviCString::m_len, KviCString::m_ptr, p, and KviMemory::reallocate().
__KVI_EXTERN KVILIB_API int kvi_irc_vsnprintf (char * buffer, const char * fmt, kvi_va_list list, bool * bTruncated)
References KVI_ASSERT, kvi_va_arg, p, s, and t.
Referenced by KviIrcConnection::sendFmtData().
__KVI_EXTERN KVILIB_API bool kvi_matchStringCI (register const char * exp, register const char * str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringCS (register const char * exp, register const char * str)
__KVI_EXTERN KVILIB_API bool kvi_matchStringWithTerminator (register const char * exp, register const char * str, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
__KVI_EXTERN KVILIB_API bool kvi_matchWildExpr (register const char * m1, register const char * m2)
Referenced by KviMediaManager::findMediaTypeForRegularFile().
__KVI_EXTERN KVILIB_API bool kvi_matchWildExprWithTerminator (register const char * m1, register const char * m2, char terminator, const char ** r1, const char ** r2)
References NOT_AT_END.
__KVI_EXTERN KVILIB_API bool kvi_qstringEqualCI (const QString & s1, const QString & s2)
References l.
__KVI_EXTERN KVILIB_API int kvi_strcmpCI (const char * str1, const char * str2)
References KVI_ASSERT.
Referenced by kvi_compare().
__KVI_EXTERN KVILIB_API int kvi_strcmpCS (const char * str1, const char * str2)
References KVI_ASSERT.
__KVI_EXTERN KVILIB_API bool kvi_strEqualCI (const char * str1, const char * str2)
References KVI_ASSERT.
Referenced by KviApplication::checkFileAssociations(), OptionsWidget_proxy::currentItemChanged(), dccModuleParseDccChat(), KviCString::equalsCI(), OptionsInstanceManager::findInstanceEntry(), KviMediaManager::findMediaTypeByFileMask(), KviMediaManager::findMediaTypeByIanaType(), LinksWindow::getItemByHost(), DccBroker::handleResumeRequest(), KviLocale::init(), kvi_dcc_video_get_codec(), kvi_dcc_video_is_valid_codec(), kvi_dcc_voice_get_codec(), kvi_dcc_voice_is_valid_codec(), mediaplayer_module_ctrl(), notifier_module_ctrl(), parseArgs(), KviIrcServerParser::parseCtcpRequestDcc(), KviIrcServerParser::parseNumeric005(), KviHttpRequest::processHeader(), DccFileTransfer::resumeAccepted(), KviIdentDaemon::run(), KviProxy::setNamedProtocol(), snd_module_ctrl(), and system_kvs_fnc_dbus().
__KVI_EXTERN KVILIB_API bool kvi_strEqualCIN (const char * str1, const char * str2, int len)
References KVI_ASSERT.
Referenced by KviApplication::checkFileAssociations(), KviLocale::codecForName(), KviCString::contains(), KviCString::equalsCIN(), DccVideoWindow::event(), DccChatWindow::event(), KviCString::ext_contains(), KviCString::find(), KviCString::findFirstIdx(), KviCString::findLastIdx(), KviCString::findRev(), KviCString::occurences(), KviIrcUrl::parse(), parseArgs(), KviIrcServerParser::parseNumeric005(), KviIrcSocket::proxyHandleHttpFinalReply(), KviIrcSocket::queue_removePrivateMessages(), and KviMenuBar::setupHelpPopup().
__KVI_EXTERN KVILIB_API bool kvi_strEqualCS (const char * str1, const char * str2)
References KVI_ASSERT.
Referenced by dccModuleCtcpDccParseRoutine(), dccModuleParseDccSend(), KviCString::equalsCS(), KviParameterList::getBool(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviModuleManager::loadModule(), operator!=(), operator==(), KviIrcServerParser::parseChannelMode(), KviIrcServerParser::parseCtcpRequestClientinfo(), KviIrcServerParser::parseMessage(), perlcore_module_ctrl(), and pythoncore_module_ctrl().
__KVI_EXTERN KVILIB_API bool kvi_strEqualCSN (const char * str1, const char * str2, int len)
References KVI_ASSERT.
Referenced by KviCString::contains(), KviCString::equalsCSN(), KviCString::ext_contains(), KviCString::find(), KviCString::findFirstIdx(), KviCString::findLastIdx(), KviCString::findRev(), KviCString::occurences(), and KviHttpRequest::processHeader().
__KVI_EXTERN KVILIB_API int kvi_strMatchRevCS (const char * str1, const char * str2, int index = -1)
References KVI_ASSERT.
__KVI_EXTERN KVILIB_API int kvi_vsnprintf (char * buffer, int len, const char * fmt, kvi_va_list list)
References hexdigits, KVI_ASSERT, kvi_va_arg, p, s, and t.
Referenced by KviCString::append(), KviCString::KviCString(), KviCString::sprintf(), and KviCString::vsprintf().
__KVI_EXTERN KVILIB_API kvi_wslen_t kvi_wstrlen (const kvi_wchar_t * str)
Referenced by KviIrcView::getLinkUnderMouse(), KviCString::KviCString(), and KviIrcView::paintEvent().
__KVI_EXTERN KVILIB_API int kvi_wvsnprintcf (kvi_wchar_t * buffer, kvi_wslen_t len, const char * fmt, kvi_va_list list)
__KVI_EXTERN KVILIB_API int kvi_wvsnprintf (kvi_wchar_t * buffer, kvi_wslen_t len, const kvi_wchar_t * fmt, kvi_va_list list)
__KVI_EXTERN bool operator!= (const KviCString & left, const char * right) [inline]
References kvi_strEqualCS(), and KviCString::m_ptr.
__KVI_EXTERN bool operator!= (const KviCString & left, const KviCString & right) [inline]
References kvi_strEqualCS(), and KviCString::m_ptr.
__KVI_EXTERN bool operator!= (const char * left, const KviCString & right) [inline]
References kvi_strEqualCS(), and KviCString::m_ptr.
__KVI_EXTERN KviCString operator+ (char left, const KviCString & right) [inline]
__KVI_EXTERN KviCString operator+ (const KviCString & left, const KviCString & right) [inline]
__KVI_EXTERN KviCString operator+ (const KviCString & left, char right) [inline]
__KVI_EXTERN KviCString operator+ (const char * left, const KviCString & right) [inline]
__KVI_EXTERN KviCString operator+ (const KviCString & left, const char * right) [inline]
__KVI_EXTERN bool operator== (const char * left, const KviCString & right) [inline]
References kvi_strEqualCS(), and KviCString::m_ptr.
__KVI_EXTERN bool operator== (const KviCString & left, const char * right) [inline]
References kvi_strEqualCS(), and KviCString::m_ptr.
__KVI_EXTERN bool operator== (const KviCString & left, const KviCString & right) [inline]
References kvi_strEqualCS(), KviCString::m_len, and KviCString::m_ptr.