KVIrc: src/kvirc/ui/KviIrcView_getTextLine.cpp File Reference
KviIrcView_getTextLine.cpp File Reference
#include "KviChannelWindow.h"
#include "KviIrcView.h"
#include "KviIrcView_private.h"
#include "KviKvsEventTriggers.h"
#include "KviMemory.h"
#include "KviControlCodes.h"
#include "KviOptions.h"
#include "kvi_out.h"
#include "KviTextIconManager.h"
#include "KviWindow.h"
#include <QDateTime>
#include <QChar>
Macros
#define APPEND_LAST_TEXT_BLOCK(__data_ptr, __data_len)
#define APPEND_LAST_TEXT_BLOCK_HIDDEN_FROM_NOW(__data_ptr, __data_len)
#define APPEND_ZERO_LENGTH_BLOCK(__data_ptr) /* does nothing */
#define NEW_LINE_CHUNK(_chunk_type)
#define WSTRINGCONFIG_SAFE_TO_MEMCPY_QCHAR 1
Functions
void kvi_appendWCharToQStringWithLength (QString *qstrptr, const kvi_wchar_t *ptr, kvi_wslen_t len)
static const kvi_wchar_t * skip_to_end_of_url (const kvi_wchar_t *p)
static bool url_compare_helper (const kvi_wchar_t *pData1, const kvi_wchar_t *pData2, int iData2Len)
Macro Definition Documentation
#define APPEND_LAST_TEXT_BLOCK (__data_ptr, __data_len)
Value:
blockLen = (__data_len);                                                         \
        line_ptr->pChunks[iCurChunk].iTextLen += blockLen;                               \
    kvi_appendWCharToQStringWithLength(&(line_ptr->szText), __data_ptr, __data_len); \
        iTextIdx += blockLen;
Referenced by KviIrcView::getTextLine().
#define APPEND_LAST_TEXT_BLOCK_HIDDEN_FROM_NOW (__data_ptr, __data_len)
Value:
blockLen = (__data_len);                                                         \
    kvi_appendWCharToQStringWithLength(&(line_ptr->szText), __data_ptr, __data_len); \
        iTextIdx += blockLen;
Referenced by KviIrcView::getTextLine().
#define APPEND_ZERO_LENGTH_BLOCK (__data_ptr) /* does nothing */
Referenced by KviIrcView::getTextLine().
#define NEW_LINE_CHUNK (_chunk_type)
Value:
line_ptr->uChunkCount++;                                                                    \
        line_ptr->pChunks = (KviIrcViewLineChunk *)KviMemory::reallocate((void *)line_ptr->pChunks, \
            line_ptr->uChunkCount * sizeof(KviIrcViewLineChunk));                                   \
        iCurChunk++;                                                                                \
        line_ptr->pChunks[iCurChunk].type = _chunk_type;                                            \
        line_ptr->pChunks[iCurChunk].iTextStart = iTextIdx;                                         \
        line_ptr->pChunks[iCurChunk].iTextLen = 0;                                                  \
        line_ptr->pChunks[iCurChunk].customFore = iCurChunk ? line_ptr->pChunks[iCurChunk - 1].customFore : QColor();
Referenced by KviIrcView::getTextLine().
#define WSTRINGCONFIG_SAFE_TO_MEMCPY_QCHAR 1
Function Documentation
void kvi_appendWCharToQStringWithLength (QString * qstrptr, const kvi_wchar_t * ptr, kvi_wslen_t len)
References c, KviMemory::copy(), and KVI_ASSERT.
static const kvi_wchar_t* skip_to_end_of_url (const kvi_wchar_t * p) static
References p.
Referenced by KviIrcView::getTextLine().
static bool url_compare_helper (const kvi_wchar_t * pData1, const kvi_wchar_t * pData2, int iData2Len) inline static
References KVI_ASSERT.
Referenced by KviIrcView::getTextLine().