KVIrc: src/kvirc/kvs/parser/KviKvsParser.cpp File Reference
KviKvsParser.cpp File Reference
#include "KviKvsParser.h"
#include "KviKvsTreeNode.h"
#include "KviKvsReport.h"
#include "KviKvsKernel.h"
#include "KviKvsScript.h"
#include "KviKvsParserMacros.h"
#include "KviLocale.h"
#include "KviOptions.h"
Macros
#define _REG_CNTRL_CMD(__cntrlCmdName, __parsingRoutine)
#define LITERAL_PARAM_PARSING_FUNCTION_BEGIN(__funcname)
#define LITERAL_PARAM_PARSING_FUNCTION_END_WITH_EXPECTED_TERMINATOR
#define LITERAL_PARAM_PARSING_FUNCTION_GENERIC_END
#define LITERAL_PARAM_PARSING_FUNCTION_WARN_NESTED_TERMINATOR
Functions
Q_UNUSED (pStart)
Q_UNUSED (iNestedTerminators)
Variables
case __pad0__
__pad1__
case __pad2__
case
Macro Definition Documentation
#define _REG_CNTRL_CMD (__cntrlCmdName, __parsingRoutine)
Value:
{ \
        KviKvsSpecialCommandParsingRoutine * r = new KviKvsSpecialCommandParsingRoutine; \
        r->proc = KVI_PTR2MEMBER(KviKvsParser::__parsingRoutine); \
                pKern->registerSpecialCommandParsingRoutine(QString(__cntrlCmdName),r); \
        }
Referenced by KviKvsParser::init().
#define LITERAL_PARAM_PARSING_FUNCTION_BEGIN (__funcname)
Value:
KviKvsTreeNodeConstantData * KviKvsParser::__funcname() \
{ \
        QString szValue; \
\
        const QChar * pStart = KVSP_curCharPointer; \
        const QChar * pBegin = KVSP_curCharPointer; \
        int iLen = 0; \
        int iNestedTerminators = 0; \
 \
        for(;;) \
        { \
                switch(KVSP_curCharUnicode) \
                {
#define LITERAL_PARAM_PARSING_FUNCTION_END_WITH_EXPECTED_TERMINATOR
Value:
if(iNestedTerminators > 0) \
                                { \
                    if(!_OUTPUT_MUTE) \
                        warning(KVSP_curCharPointer,__tr2qs_ctx("Skipping nested terminator character %q","kvs"),KVSP_curCharPointer); \
                    KVSP_skipChar; \
                                        iNestedTerminators--; \
                                        iLen++; \
                                } else { \
                    if(iLen > 0)szValue.append(QString(pBegin,iLen)); \
                                        { \
                                                bool bOk; \
                        kvs_int_t iVal = szValue.toLong(&bOk); \
                        if(bOk)return new KviKvsTreeNodeConstantData(pBegin,new KviKvsVariant(iVal)); \
                                                kvs_real_t dVal = szValue.toDouble(&bOk); \
                                                if(bOk)return new KviKvsTreeNodeConstantData(pBegin,new KviKvsVariant(dVal)); \
                                        } \
                                        return new KviKvsTreeNodeConstantData(pBegin,new KviKvsVariant(szValue)); \
                                } \
                        break;
#define LITERAL_PARAM_PARSING_FUNCTION_GENERIC_END
#define LITERAL_PARAM_PARSING_FUNCTION_WARN_NESTED_TERMINATOR
Value:
if(!_OUTPUT_MUTE) \
                    warning(KVSP_curCharPointer,__tr2qs_ctx("Nested character %q corresponding to expected terminator, this might confuse me a bit: it is a good idea to enclose it in quotes","kvs"),KVSP_curCharPointer); \
                KVSP_skipChar; \
                                iNestedTerminators++; \
                                iLen++; \
                        break;
Function Documentation
Q_UNUSED (pStart)
Referenced by SetupWizard::accept(), RegisteredUsersDialog::fillList(), get_id3(), HelpIndex::HelpIndex(), KvsObject_vBox::init(), kvi_dcc_video_get_codec(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), OptionsWidget_messageColors::load(), KviKvsCoreSimpleCommands::multipleModeCommand(), and MpInterface::year().
Q_UNUSED (iNestedTerminators)
Variable Documentation
case __pad0__
__pad1__
case __pad2__
case
Initial value:
{':
LITERAL_PARAM_PARSING_FUNCTION_WARN_NESTED_TERMINATOR
                        case '}':
LITERAL_PARAM_PARSING_FUNCTION_END_WITH_EXPECTED_TERMINATOR
                        case 0:
                        case '$':
                        case '%':
                        case '@':
                        case '\r':
                        case '\n':
                        case '"':
                        case '\t':
                        case ' ':
LITERAL_PARAM_PARSING_FUNCTION_GENERIC_END
                        Q_UNUSED(pStart)