KVIrc: src/kvilib/irc/KviMircCntrl.h File Reference
src/kvilib/irc/KviMircCntrl.h File Reference
#include "kvi_settings.h"
#include "KviCString.h"
Namespaces
namespace KviMircCntrl
Defines
#define KVI_MIRCCOLOR_MAX_BACKGROUND 15
#define KVI_MIRCCOLOR_MAX_FOREGROUND 15
Enumerations
enum KviMircCntrl::Color {
KviMircCntrl::White = 0, KviMircCntrl::Black = 1, KviMircCntrl::DarkBlue = 2, KviMircCntrl::DarkGreen = 3,
KviMircCntrl::Red = 4, KviMircCntrl::DarkRed = 5, KviMircCntrl::DarkViolet = 6, KviMircCntrl::Orange = 7,
KviMircCntrl::Yellow = 8, KviMircCntrl::LightGreen = 9, KviMircCntrl::BlueMarine = 10, KviMircCntrl::LightBlue = 11,
KviMircCntrl::Blue = 12, KviMircCntrl::LightViolet = 13, KviMircCntrl::DarkGray = 14, KviMircCntrl::LightGray = 15,
KviMircCntrl::Transparent = 100, KviMircCntrl::NoChange = 101
}
Contains mIRC color codes.
enum KviMircCntrl::Control {
KviMircCntrl::CTCP = 0x01, KviMircCntrl::Bold = 0x02, KviMircCntrl::Color = 0x03, KviMircCntrl::Escape = 0x04,
KviMircCntrl::UnEscape = 0x05, KviMircCntrl::UnIcon = 0x06, KviMircCntrl::Reset = 0x0f, KviMircCntrl::Reverse = 0x16,
KviMircCntrl::Icon = 0x1d, KviMircCntrl::CryptEscape = 0x1e, KviMircCntrl::Underline = 0x1f
}
Contains mIRC control codes.
Functions
KVILIB_API const char * getColorBytes (const char *data_ptr, unsigned char *byte_1, unsigned char *byte_2)
KVILIB_API const kvi_wchar_t * getColorBytesW (const kvi_wchar_t *data_ptr, unsigned char *byte_1, unsigned char *byte_2)
const QChar * getUnicodeColorBytes (const QChar *pData, unsigned char *byte_1, unsigned char *byte_2)
KVILIB_API unsigned int getUnicodeColorBytes (const QString &szData, unsigned int charIdx, unsigned char *byte_1, unsigned char *byte_2)
QString KviMircCntrl::stripControlBytes (const QString &szData)
Removes control bytes from the given string.
Define Documentation
#define KVI_MIRCCOLOR_MAX_BACKGROUND 15
Referenced by KviMircTextColorSelector::KviMircTextColorSelector(), and KviMircTextColorSelector::setButtonPalette().
#define KVI_MIRCCOLOR_MAX_FOREGROUND 15
Referenced by KviMircTextColorSelector::KviMircTextColorSelector(), and KviMircTextColorSelector::setButtonPalette().
Function Documentation
KVILIB_API const char* getColorBytes (const char * data_ptr, unsigned char * byte_1, unsigned char * byte_2)
References KviMircCntrl::NoChange.
KVILIB_API const kvi_wchar_t* getColorBytesW (const kvi_wchar_t * data_ptr, unsigned char * byte_1, unsigned char * byte_2)
References KviMircCntrl::NoChange.
Referenced by KviIrcView::getTextLine(), and getUnicodeColorBytes().
const QChar* getUnicodeColorBytes (const QChar * pData, unsigned char * byte_1, unsigned char * byte_2) [inline]
References getColorBytesW().
KVILIB_API unsigned int getUnicodeColorBytes (const QString & szData, unsigned int charIdx, unsigned char * byte_1, unsigned char * byte_2)
References c, and KviMircCntrl::NoChange.
Referenced by KviHtmlGenerator::convertToHtml(), KviInputEditor::extractNextBlock(), KviTopicWidget::paintColoredText(), KviInputEditor::runUpToTheFirstVisibleChar(), KviIrcUserEntry::setRealName(), and KviMircCntrl::stripControlBytes().