KVIrc: src/kvirc/kernel/KviMain.cpp File Reference
src/kvirc/kernel/KviMain.cpp File Reference
#include "KviApplication.h"
#include "KviCString.h"
#include "kvi_settings.h"
#include "KviIrcUrl.h"
#include "kvi_defaults.h"
#include "kvi_sourcesdate.h"
#include "KviMessageBox.h"
#include "KviBuildInfo.h"
#include <QtGlobal>
#include <QMessageBox>
Classes
struct _ParseArgs
Defines
#define KVI_ARGS_RETCODE_ERROR 1
#define KVI_ARGS_RETCODE_OK 0
#define KVI_ARGS_RETCODE_STOP 2
Typedefs
typedef struct _ParseArgs ParseArgs
Functions
bool kvi_sendIpcMessage (const char *message)
int main (int argc, char **argv)
int parseArgs (ParseArgs *a)
Define Documentation
#define KVI_ARGS_RETCODE_ERROR 1
Referenced by main(), and parseArgs().
#define KVI_ARGS_RETCODE_OK 0
Referenced by main(), and parseArgs().
#define KVI_ARGS_RETCODE_STOP 2
Referenced by parseArgs().
Typedef Documentation
typedef struct _ParseArgs ParseArgs
Function Documentation
bool kvi_sendIpcMessage (const char * message)
COMPILE_NO_X
References e, KVI_WINDOWS_IPC_MESSAGE, NULL, and KviMemory::set().
Referenced by main().
int main (int argc, char ** argv)
References a, KviCString::append(), _ParseArgs::argc, _ParseArgs::argv, _ParseArgs::bExecuteCommandAndClose, _ParseArgs::bForceNewSession, _ParseArgs::bShowPopup, _ParseArgs::bShowSplashScreen, _ParseArgs::configFile, _ParseArgs::createFile, KviCString::Format, KviCString::hasData(), KviMessageBox::information(), init(), KviCString::isEmpty(), KVI_ARGS_RETCODE_ERROR, KVI_ARGS_RETCODE_OK, kvi_sendIpcMessage(), KVI_VERSION, KviApplication::m_bCreateConfig, KviApplication::m_bShowSplashScreen, KviApplication::m_szConfigFile, KviApplication::m_szExecAfterStartup, parseArgs(), KviCString::ptr(), KviApplication::setup(), _ParseArgs::szExecCommand, and _ParseArgs::szExecRemoteCommand.
Referenced by KviMenuBar::setupMainPopup().
int parseArgs (ParseArgs * a)
References KviCString::append(), KviQString::appendFormatted(), _ParseArgs::argc, _ParseArgs::argv, _ParseArgs::bExecuteCommandAndClose, _ParseArgs::bForceNewSession, _ParseArgs::bShowPopup, _ParseArgs::bShowSplashScreen, KviBuildInfo::buildDate(), _ParseArgs::configFile, _ParseArgs::createFile, KviQString::equalCI(), KviCString::hasData(), KVI_ARGS_RETCODE_ERROR, KVI_ARGS_RETCODE_OK, KVI_ARGS_RETCODE_STOP, KVI_HOME_CONFIG_FILE_NAME, KVI_RELEASE_NAME, KVI_SOURCES_DATE, kvi_strEqualCI(), kvi_strEqualCIN(), kvi_strLen, KVI_VERSION, p, KviCString::replaceAll(), KviCString::right(), _ParseArgs::szExecCommand, and _ParseArgs::szExecRemoteCommand.
Referenced by main().