KVIrc: src/kvilib/irc/KviMircCntrl.cpp File Reference
src/kvilib/irc/KviMircCntrl.cpp File Reference
#include "KviMircCntrl.h"
Namespaces
namespace KviMircCntrl
Defines
#define _KVI_MIRCCNTRL_CPP_
Functions
KVILIB_API const char * getColorBytes (const char *data_ptr, unsigned char *byte_1, unsigned char *byte_2)
KVILIB_API const kvi_wchar_t * getColorBytesW (const kvi_wchar_t *data_ptr, unsigned char *byte_1, unsigned char *byte_2)
KVILIB_API unsigned int getUnicodeColorBytes (const QString &szData, unsigned int charIdx, unsigned char *byte_1, unsigned char *byte_2)
QString KviMircCntrl::stripControlBytes (const QString &szData)
Removes control bytes from the given string.
Define Documentation
#define _KVI_MIRCCNTRL_CPP_
Function Documentation
KVILIB_API const char* getColorBytes (const char * data_ptr, unsigned char * byte_1, unsigned char * byte_2)
References KviMircCntrl::NoChange.
KVILIB_API const kvi_wchar_t* getColorBytesW (const kvi_wchar_t * data_ptr, unsigned char * byte_1, unsigned char * byte_2)
References KviMircCntrl::NoChange.
Referenced by KviIrcView::getTextLine(), and getUnicodeColorBytes().
KVILIB_API unsigned int getUnicodeColorBytes (const QString & szData, unsigned int charIdx, unsigned char * byte_1, unsigned char * byte_2)
References c, and KviMircCntrl::NoChange.
Referenced by KviHtmlGenerator::convertToHtml(), KviInputEditor::extractNextBlock(), KviTopicWidget::paintColoredText(), KviInputEditor::runUpToTheFirstVisibleChar(), KviIrcUserEntry::setRealName(), and KviMircCntrl::stripControlBytes().