KVIrc: src/kvilib/net/KviNetUtils.cpp File Reference
KviNetUtils.cpp File Reference
#include "KviNetUtils.h"
#include "KviMemory.h"
#include <QStringList>
#include <sys/time.h>
#include <unistd.h>
#include <netdb.h>
#include <sys/types.h>
#include <ctype.h>
#include <errno.h>
Namespaces
KviNetUtils
Macros
#define _KVI_NETUTILS_CPP_
Functions
bool KviNetUtils::binaryIpToStringIp (struct in_addr in, QString &szBuffer)
void KviNetUtils::formatNetworkBandwidthString (QString &szBuffer, unsigned int uBytesPerSec)
bool KviNetUtils::getInterfaceAddress (const QString &, QString &)
COMPILE_GET_INTERFACE_ADDRESS.
bool KviNetUtils::isRoutableIp (const char *ipaddr)
bool KviNetUtils::isRoutableIpString (const QString &szIpString)
bool KviNetUtils::isValidStringIp (const QString &szIp)
bool kvi_binaryIpToStringIp (struct in_addr in, QString &szBuffer)
HAVE_INET_ATON.
bool kvi_getLocalHostAddress (QString &buffer)
bool kvi_isRoutableIp (const char *ipaddr)
bool kvi_isRoutableIpString (const char *ipstring)
bool kvi_isValidStringIp (const char *szIp)
bool kvi_select (int fd, bool *bCanRead, bool *bCanWrite, int iUSecs)
bool kvi_stringIpToBinaryIp (const char *szIp, struct in_addr *address)
bool KviNetUtils::stringIpToBinaryIp (const QString &szStringIp, struct in_addr *address)
Macro Definition Documentation
#define _KVI_NETUTILS_CPP_
Function Documentation
bool kvi_binaryIpToStringIp (struct in_addr in, QString & szBuffer)
HAVE_INET_ATON.
References a, c, d, and s.
Referenced by KviSockaddr::getStringAddress(), and kvi_getLocalHostAddress().
bool kvi_getLocalHostAddress (QString & buffer)
References h, kvi_binaryIpToStringIp(), and kvi_isRoutableIp().
Referenced by dcc_kvs_get_listen_ip_address(), and upnp_kvs_cmd_addPortMapping().
bool kvi_isRoutableIp (const char * ipaddr)
Referenced by kvi_getLocalHostAddress(), and kvi_isRoutableIpString().
bool kvi_isRoutableIpString (const char * ipstring)
References kvi_isRoutableIp(), and kvi_stringIpToBinaryIp().
Referenced by DccChatWindow::connectionInProgress().
bool kvi_isValidStringIp (const char * szIp)
References kvi_stringIpToBinaryIp().
bool kvi_select (int fd, bool * bCanRead, bool * bCanWrite, int iUSecs)
Referenced by DccVideoThread::readWriteStep(), DccVoiceThread::readWriteStep(), DccChatThread::run(), DccSendThread::run(), and DccRecvThread::run().
bool kvi_stringIpToBinaryIp (const char * szIp, struct in_addr * address)
References c, and n.
Referenced by kvi_isRoutableIpString(), and kvi_isValidStringIp().