KVIrc: src/kvirc/ui/KviStatusBarApplet.cpp File Reference
src/kvirc/ui/KviStatusBarApplet.cpp File Reference
#include "KviStatusBarApplet.h"
#include "KviMainWindow.h"
#include "KviIconManager.h"
#include "KviWindow.h"
#include "KviIrcContext.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionUserInfo.h"
#include "KviIrcConnectionStatistics.h"
#include "KviLocale.h"
#include "KviApplication.h"
#include "KviConfigurationFile.h"
#include "KviModuleManager.h"
#include "KviConsoleWindow.h"
#include "KviLagMeter.h"
#include "KviOptions.h"
#include "KviKvsScript.h"
#include "KviTimeUtils.h"
#include "KviQString.h"
#include "KviBuildInfo.h"
#include "kvi_settings.h"
#include "KviMiscUtils.h"
#include "KviHttpRequest.h"
#include "KviUrl.h"
#include "KviTalPopupMenu.h"
#include "KviTalToolTip.h"
#include "KviDataBuffer.h"
#include <QPainter>
#include <QStyle>
#include <QLayout>
#include <QTimer>
#include <QCursor>
#include <QPixmap>
#include <QFont>
#include <QEvent>
#include <QMouseEvent>
Functions
KviStatusBarApplet * CreateStatusBarAwayIndicator (KviStatusBar *pBar, KviStatusBarAppletDescriptor *pDescriptor)
KviStatusBarApplet * CreateStatusBarClock (KviStatusBar *pBar, KviStatusBarAppletDescriptor *pDescriptor)
KviStatusBarApplet * CreateStatusBarConnectionTimer (KviStatusBar *pBar, KviStatusBarAppletDescriptor *pDescriptor)
KviStatusBarApplet * CreateStatusBarLagIndicator (KviStatusBar *pBar, KviStatusBarAppletDescriptor *pDescriptor)
KviStatusBarApplet * CreateStatusBarSeparator (KviStatusBar *pBar, KviStatusBarAppletDescriptor *pDescriptor)
KviStatusBarApplet * CreateStatusBarUpdateIndicator (KviStatusBar *pBar, KviStatusBarAppletDescriptor *pDescriptor)
Function Documentation
KviStatusBarApplet* CreateStatusBarAwayIndicator (KviStatusBar * pBar, KviStatusBarAppletDescriptor * pDescriptor)
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by KviStatusBarAwayIndicator::selfRegister().
KviStatusBarApplet* CreateStatusBarClock (KviStatusBar * pBar, KviStatusBarAppletDescriptor * pDescriptor)
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by KviStatusBarClock::selfRegister().
KviStatusBarApplet* CreateStatusBarConnectionTimer (KviStatusBar * pBar, KviStatusBarAppletDescriptor * pDescriptor)
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by KviStatusBarConnectionTimer::selfRegister().
KviStatusBarApplet* CreateStatusBarLagIndicator (KviStatusBar * pBar, KviStatusBarAppletDescriptor * pDescriptor)
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by KviStatusBarLagIndicator::selfRegister().
KviStatusBarApplet* CreateStatusBarSeparator (KviStatusBar * pBar, KviStatusBarAppletDescriptor * pDescriptor)
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by KviStatusBarSeparator::selfRegister().
KviStatusBarApplet* CreateStatusBarUpdateIndicator (KviStatusBar * pBar, KviStatusBarAppletDescriptor * pDescriptor)
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by KviStatusBarUpdateIndicator::selfRegister().