KVIrc: src/modules/objects/KvsObject_layout.cpp File Reference
src/modules/objects/KvsObject_layout.cpp File Reference
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KvsObject_layout.h"
#include <QGridLayout>
#include "m_KvsObject_layout.moc"
Defines
#define _KVI_DEBUG_CHECK_RANGE_
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (layout, addWidget)
KVSO_CLASS_FUNCTION (layout, setAlignment)
KVSO_CLASS_FUNCTION (layout, setResizeMode)
KVSO_CLASS_FUNCTION (layout, addColSpacing)
KVSO_CLASS_FUNCTION (layout, addRowSpacing)
KVSO_CLASS_FUNCTION (layout, setSpacing)
KVSO_CLASS_FUNCTION (layout, setMargin)
KVSO_CLASS_FUNCTION (layout, setColumnStretch)
KVSO_CLASS_FUNCTION (layout, setRowStretch)
KVSO_CLASS_FUNCTION (layout, addMultiCellWidget)
Variables
const int align_cod []
const char *const align_tbl []
Define Documentation
#define _KVI_DEBUG_CHECK_RANGE_
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (layout , addWidget)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (layout , setAlignment)
References __tr2qs_ctx(), align_cod, align_num, align_tbl, c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KviKvsKernel::instance(), j, KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (layout , setResizeMode)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and r.
KVSO_CLASS_FUNCTION (layout , addColSpacing)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (layout , addRowSpacing)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (layout , setSpacing)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (layout , setMargin)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (layout , setColumnStretch)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (layout , setRowStretch)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (layout , addMultiCellWidget)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
Variable Documentation
const int align_cod[]
Initial value:
 {
                        Qt::AlignLeft,
                        Qt::AlignRight,
                        Qt::AlignHCenter,
                        Qt::AlignVCenter,
                        Qt::AlignCenter,
                        Qt::AlignTop,
                        Qt::AlignBottom,
        }
const char* const align_tbl[]
Initial value:
 {
                                "Left",
                                "Right",
                                "HCenter",
                                "VCenter",
                                "Center",
                                "Top",
                                "Bottom",
                                }