KVIrc: src/modules/objects/KvsObject_tableWidget.cpp File Reference
KvsObject_tableWidget.cpp File Reference
#include "KvsObject_tableWidget.h"
#include "KvsObject_painter.h"
#include "KvsObject_pixmap.h"
#include "kvi_debug.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviError.h"
#include "KviIconManager.h"
#include "KviFile.h"
#include "KviKvsArrayCast.h"
#include <QTableWidget>
#include <QHeaderView>
#include <QPainter>
#include <QApplication>
#include <QPoint>
#include <QPaintEvent>
#include <QTableWidgetItem>
#include <QRect>
Macros
#define itemflags_num (sizeof(itemflags_tbl) / sizeof(itemflags_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (tableWidget, clear)
KVSO_CLASS_FUNCTION (tableWidget, resizeRowsToContents)
KVSO_CLASS_FUNCTION (tableWidget, resizeColumnsToContents)
KVSO_CLASS_FUNCTION (tableWidget, setForeground)
KVSO_CLASS_FUNCTION (tableWidget, setText)
KVSO_CLASS_FUNCTION (tableWidget, setNumber)
KVSO_CLASS_FUNCTION (tableWidget, insertRow)
KVSO_CLASS_FUNCTION (tableWidget, insertColumn)
KVSO_CLASS_FUNCTION (tableWidget, removeRow)
KVSO_CLASS_FUNCTION (tableWidget, removeColumn)
KVSO_CLASS_FUNCTION (tableWidget, setIcon)
KVSO_CLASS_FUNCTION (tableWidget, text)
KVSO_CLASS_FUNCTION (tableWidget, setRowCount)
KVSO_CLASS_FUNCTION (tableWidget, rowCount)
KVSO_CLASS_FUNCTION (tableWidget, currentRow)
KVSO_CLASS_FUNCTION (tableWidget, currentColumn)
KVSO_CLASS_FUNCTION (tableWidget, columnCount)
KVSO_CLASS_FUNCTION (tableWidget, itemRowColAt)
KVSO_CLASS_FUNCTION (tableWidget, setToolTip)
KVSO_CLASS_FUNCTION (tableWidget, setColumnCount)
KVSO_CLASS_FUNCTION (tableWidget, hideColumn)
KVSO_CLASS_FUNCTION (tableWidget, showColumn)
KVSO_CLASS_FUNCTION (tableWidget, hideRow)
KVSO_CLASS_FUNCTION (tableWidget, showRow)
KVSO_CLASS_FUNCTION (tableWidget, setHorizontalHeaderLabels)
KVSO_CLASS_FUNCTION (tableWidget, setVerticalHeaderLabels)
KVSO_CLASS_FUNCTION (tableWidget, setCellWidget)
KVSO_CLASS_FUNCTION (tableWidget, hideHorizontalHeader)
KVSO_CLASS_FUNCTION (tableWidget, hideVerticalHeader)
KVSO_CLASS_FUNCTION (tableWidget, showHorizontalHeader)
KVSO_CLASS_FUNCTION (tableWidget, showVerticalHeader)
KVSO_CLASS_FUNCTION (tableWidget, setItemFlags)
KVSO_CLASS_FUNCTION (tableWidget, itemEnteredEvent)
KVSO_CLASS_FUNCTION (tableWidget, cellActivatedEvent)
KVSO_CLASS_FUNCTION (tableWidget, cellDoubleClickedEvent)
KVSO_REGISTER_HANDLER (KvsObject_tableWidget,"itemEnteredEvent", itemEnteredEvent)
KVSO_REGISTER_HANDLER (KvsObject_tableWidget,"cellActivatedEvent", cellActivatedEvent)
KVSO_REGISTER_HANDLER (KvsObject_tableWidget,"cellDoubleClickedEvent", cellDoubleClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_tableWidget, setItemFlags)
Variables
const int item_flags []
const char *const itemflags_tbl []
Macro Definition Documentation
#define itemflags_num (sizeof(itemflags_tbl) / sizeof(itemflags_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (tableWidget , clear)
References CHECK_INTERNAL_POINTER, and clear().
KVSO_CLASS_FUNCTION (tableWidget , resizeRowsToContents)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tableWidget , resizeColumnsToContents)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tableWidget , setForeground)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsArray::at(), c, CHECK_INTERNAL_POINTER, KviKvsVariant::isArray(), KviKvsVariant::isString(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_UNSIGNEDINTEGER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (tableWidget , setText)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , setNumber)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , insertRow)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , insertColumn)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , removeRow)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , removeColumn)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , setIcon)
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsVariant::asString(), c, g_pIconManager, KviIconManager::getImage(), KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isHObject(), KVS_PT_UNSIGNEDINTEGER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tableWidget , text)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , setRowCount)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , rowCount)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tableWidget , currentRow)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tableWidget , currentColumn)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tableWidget , columnCount)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tableWidget , itemRowColAt)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, pArray, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (tableWidget , setToolTip)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , setColumnCount)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , hideColumn)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , showColumn)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , hideRow)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , showRow)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , setHorizontalHeaderLabels)
References a, KviKvsArrayCast::array(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, KVS_PT_ARRAYCAST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and v.
KVSO_CLASS_FUNCTION (tableWidget , setVerticalHeaderLabels)
References a, KviKvsArrayCast::array(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, KVS_PT_ARRAYCAST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and v.
KVSO_CLASS_FUNCTION (tableWidget , setCellWidget)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tableWidget , hideHorizontalHeader)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (tableWidget , hideVerticalHeader)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (tableWidget , showHorizontalHeader)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (tableWidget , showVerticalHeader)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (tableWidget , setItemFlags)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), i, item_flags, itemflags_num, itemflags_tbl, j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tableWidget , itemEnteredEvent)
References c.
KVSO_CLASS_FUNCTION (tableWidget , cellActivatedEvent)
References c.
KVSO_CLASS_FUNCTION (tableWidget , cellDoubleClickedEvent)
References c.
KVSO_REGISTER_HANDLER (KvsObject_tableWidget , "itemEnteredEvent" , itemEnteredEvent)
KVSO_REGISTER_HANDLER (KvsObject_tableWidget , "cellActivatedEvent" , cellActivatedEvent)
KVSO_REGISTER_HANDLER (KvsObject_tableWidget , "cellDoubleClickedEvent" , cellDoubleClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_tableWidget , setItemFlags)
Variable Documentation
const int item_flags[]
Initial value:
= {
        Qt::NoItemFlags,
        Qt::ItemIsSelectable,
        Qt::ItemIsEditable,
        Qt::ItemIsDragEnabled,
        Qt::ItemIsDropEnabled,
        Qt::ItemIsUserCheckable,
        Qt::ItemIsEnabled,
        Qt::ItemIsTristate
}
Referenced by KVSO_CLASS_FUNCTION().
const char* const itemflags_tbl[]
Initial value:
= {
        "noitemflag",
        "selectable",
        "editable",
        "dragEnabled",
        "dropEnabled",
        "userCheckable",
        "enabled",
        "tristate"
}
Referenced by KVSO_CLASS_FUNCTION().