KVIrc: src/modules/objects/KvsObject_trayIcon.cpp File Reference
KvsObject_trayIcon.cpp File Reference
#include "KvsObject_trayIcon.h"
#include "KvsObject_popupMenu.h"
#include "KviIconManager.h"
#include "kvi_debug.h"
#include "KviError.h"
#include "KviLocale.h"
#include <QSystemTrayIcon>
Functions
connect (m_pTrayIcon, SIGNAL(activated(QSystemTrayIcon::ActivationReason)), this, SLOT(slotActivated(QSystemTrayIcon::ActivationReason)))
connect (m_pTrayIcon, SIGNAL(messageClicked()), this, SLOT(slotMessageClicked()))
KVSO_CLASS_FUNCTION (trayIcon, setIcon)
KVSO_CLASS_FUNCTION (trayIcon, setTooltip)
KVSO_CLASS_FUNCTION (trayIcon, show)
KVSO_CLASS_FUNCTION (trayIcon, hide)
KVSO_CLASS_FUNCTION (trayIcon, isVisible)
KVSO_CLASS_FUNCTION (trayIcon, showMessage)
KVSO_CLASS_FUNCTION (trayIcon, setContextMenu)
KVSO_CLASS_FUNCTION (trayIcon, activatedEvent)
KVSO_CLASS_FUNCTION (trayIcon, messageClickedEvent)
Variables
m_pTrayIcon = new QSystemTrayIcon(nullptr)
Function Documentation
connect (m_pTrayIcon , SIGNAL(activated(QSystemTrayIcon::ActivationReason)) , this , SLOT(slotActivated(QSystemTrayIcon::ActivationReason)))
connect (m_pTrayIcon , SIGNAL(messageClicked()) , this , SLOT(slotMessageClicked()))
KVSO_CLASS_FUNCTION (trayIcon , setIcon)
References c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (trayIcon , setTooltip)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTrayIcon.
KVSO_CLASS_FUNCTION (trayIcon , show)
References CHECK_INTERNAL_POINTER, and m_pTrayIcon.
KVSO_CLASS_FUNCTION (trayIcon , hide)
References CHECK_INTERNAL_POINTER, and m_pTrayIcon.
KVSO_CLASS_FUNCTION (trayIcon , isVisible)
References c, CHECK_INTERNAL_POINTER, and m_pTrayIcon.
KVSO_CLASS_FUNCTION (trayIcon , showMessage)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVS_PT_UINT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTrayIcon.
KVSO_CLASS_FUNCTION (trayIcon , setContextMenu)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pTrayIcon, KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (trayIcon , activatedEvent)
References c.
KVSO_CLASS_FUNCTION (trayIcon , messageClickedEvent)
References c.
Variable Documentation
delete m_pTrayIcon = new QSystemTrayIcon(nullptr)
Referenced by KVSO_CLASS_FUNCTION(), KviMainWindow::setTrayIcon(), and KviMainWindow::trayIcon().