KVIrc: src/modules/objects/KvsObject_tabWidget.cpp File Reference
src/modules/objects/KvsObject_tabWidget.cpp File Reference
#include "KvsObject_tabWidget.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QTabWidget>
#include "m_KvsObject_tabWidget.moc"
Functions
tabsList clear ()
KVSO_CLASS_FUNCTION (tabWidget, tabCloseRequestEvent)
KVSO_CLASS_FUNCTION (tabWidget, currentChangedEvent)
KVSO_CLASS_FUNCTION (tabWidget, setTabPosition)
KVSO_CLASS_FUNCTION (tabWidget, changeTab)
KVSO_CLASS_FUNCTION (tabWidget, removePage)
KVSO_CLASS_FUNCTION (tabWidget, currentTabLabel)
KVSO_CLASS_FUNCTION (tabWidget, count)
KVSO_CLASS_FUNCTION (tabWidget, tabLabel)
KVSO_CLASS_FUNCTION (tabWidget, currentPageIndex)
KVSO_CLASS_FUNCTION (tabWidget, setTabLabel)
KVSO_CLASS_FUNCTION (tabWidget, removeTabToolTip)
KVSO_CLASS_FUNCTION (tabWidget, setTabToolTip)
KVSO_CLASS_FUNCTION (tabWidget, setCurrentPage)
KVSO_CLASS_FUNCTION (tabWidget, insertTab)
KVSO_CLASS_FUNCTION (tabWidget, widgetAt)
KVSO_CLASS_FUNCTION (tabWidget, indexOf)
KVSO_CLASS_FUNCTION (tabWidget, addTab)
KVSO_CLASS_FUNCTION (tabWidget, setTabsClosable)
Function Documentation
tabsList clear ()
KVSO_CLASS_FUNCTION (tabWidget , tabCloseRequestEvent)
References c.
KVSO_CLASS_FUNCTION (tabWidget , currentChangedEvent)
References c.
KVSO_CLASS_FUNCTION (tabWidget , setTabPosition)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tabWidget , changeTab)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , removePage)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , currentTabLabel)
References c, CHECK_INTERNAL_POINTER, and i.
KVSO_CLASS_FUNCTION (tabWidget , count)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tabWidget , tabLabel)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tabWidget , currentPageIndex)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (tabWidget , setTabLabel)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , removeTabToolTip)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , setTabToolTip)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , setCurrentPage)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tabWidget , insertTab)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , widgetAt)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (tabWidget , indexOf)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , addTab)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (tabWidget , setTabsClosable)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.