KVIrc: src/modules/objects/KvsObject_groupBox.cpp File Reference
src/modules/objects/KvsObject_groupBox.cpp File Reference
#include <KviTalGroupBox.h>
#include "KvsObject_groupBox.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
Defines
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (groupBox, setTitle)
KVSO_CLASS_FUNCTION (groupBox, setOrientation)
KVSO_CLASS_FUNCTION (groupBox, alignment)
KVSO_CLASS_FUNCTION (groupBox, setAlignment)
KVSO_CLASS_FUNCTION (groupBox, addSpace)
KVSO_CLASS_FUNCTION (groupBox, insideSpacing)
KVSO_CLASS_FUNCTION (groupBox, setInsideSpacing)
KVSO_CLASS_FUNCTION (groupBox, insideMargin)
KVSO_CLASS_FUNCTION (groupBox, setInsideMargin)
KVSO_CLASS_FUNCTION (groupBox, isChecked)
KVSO_CLASS_FUNCTION (groupBox, setChecked)
KVSO_CLASS_FUNCTION (groupBox, isCheckable)
KVSO_CLASS_FUNCTION (groupBox, setCheckable)
KVSO_CLASS_FUNCTION (groupBox, isFlat)
KVSO_CLASS_FUNCTION (groupBox, setFlat)
KVSO_CLASS_FUNCTION (groupBox, title)
Variables
const int align_cod []
const char *const align_tbl []
Define Documentation
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (groupBox , setTitle)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , setOrientation)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , alignment)
References align_cod, align_num, align_tbl, c, CHECK_INTERNAL_POINTER, and i.
KVSO_CLASS_FUNCTION (groupBox , setAlignment)
References __tr2qs_ctx(), align_cod, align_num, align_tbl, c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), i, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , addSpace)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , insideSpacing)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (groupBox , setInsideSpacing)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , insideMargin)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (groupBox , setInsideMargin)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , isChecked)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (groupBox , setChecked)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , isCheckable)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (groupBox , setCheckable)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , isFlat)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (groupBox , setFlat)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (groupBox , title)
References c, and CHECK_INTERNAL_POINTER.
Variable Documentation
const int align_cod[]
Initial value:
 {
        Qt::AlignLeft,
        Qt::AlignRight,
        Qt::AlignHCenter
}
const char* const align_tbl[]
Initial value:
 {
        "Left",
        "Right",
        "HCenter"
}