KVIrc: src/modules/objects/KvsObject_treeWidget.cpp File Reference
src/modules/objects/KvsObject_treeWidget.cpp File Reference
#include "KvsObject_treeWidget.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QTreeWidget>
#include <QSqlDatabase>
#include <QEvent>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QHeaderView>
#include <QUrl>
#include "m_KvsObject_treeWidget.moc"
Functions
KVSO_CLASS_FUNCTION (treeWidget, setHeaderLabels)
KVSO_CLASS_FUNCTION (treeWidget, itemChangedEvent)
KVSO_CLASS_FUNCTION (treeWidget, setColumnText)
KVSO_CLASS_FUNCTION (treeWidget, itemExpandedEvent)
KVSO_CLASS_FUNCTION (treeWidget, setAcceptDrops)
KVSO_CLASS_FUNCTION (treeWidget, clear)
KVSO_CLASS_FUNCTION (treeWidget, currentChangedEvent)
KVSO_CLASS_FUNCTION (treeWidget, selectionChangedEvent)
KVSO_CLASS_FUNCTION (treeWidget, itemClickedEvent)
KVSO_CLASS_FUNCTION (treeWidget, listViewHeaderIsVisible)
KVSO_CLASS_FUNCTION (treeWidget, itemActivatedEvent)
KVSO_CLASS_FUNCTION (treeWidget, hideListViewHeader)
KVSO_CLASS_FUNCTION (treeWidget, onItemEvent)
KVSO_CLASS_FUNCTION (treeWidget, setRootIsDecorated)
KVSO_CLASS_FUNCTION (treeWidget, selectedItems)
KVSO_CLASS_FUNCTION (treeWidget, setSorting)
KVSO_CLASS_FUNCTION (treeWidget, itemCollapsedEvent)
KVSO_CLASS_FUNCTION (treeWidget, firstChild)
KVSO_CLASS_FUNCTION (treeWidget, currentItem)
KVSO_CLASS_FUNCTION (treeWidget, setColumnCount)
KVSO_CLASS_FUNCTION (treeWidget, setSelectionMode)
KVSO_CLASS_FUNCTION (treeWidget, topLevelItem)
KVSO_CLASS_FUNCTION (treeWidget, itemAt)
KVSO_CLASS_FUNCTION (treeWidget, addColumn)
KVSO_CLASS_FUNCTION (treeWidget, showListViewHeader)
KVSO_CLASS_FUNCTION (treeWidget, setSortingEnabled)
KVSO_CLASS_FUNCTION (treeWidget, setAllColumnsShowFocus)
KVSO_CLASS_FUNCTION (treeWidget, topLevelItemCount)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, selectionChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, itemExpandedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, itemChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, setAcceptDrops)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, onItemEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, itemActivatedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, currentChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, itemClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget, itemCollapsedEvent)
Function Documentation
KVSO_CLASS_FUNCTION (treeWidget , setHeaderLabels)
References c, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , itemChangedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , setColumnText)
References c, KVS_PT_INT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , itemExpandedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , setAcceptDrops)
References c, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , clear)
References c, clear(), and Q_UNUSED().
KVSO_CLASS_FUNCTION (treeWidget , currentChangedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , selectionChangedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , itemClickedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , listViewHeaderIsVisible)
References c.
KVSO_CLASS_FUNCTION (treeWidget , itemActivatedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , hideListViewHeader)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (treeWidget , onItemEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , setRootIsDecorated)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , selectedItems)
References c, i, KvsObject_treeWidgetItem::itemToHandle(), pArray, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (treeWidget , setSorting)
References __tr2qs_ctx(), c, KviQString::equalCI(), KVS_PT_INT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , itemCollapsedEvent)
References c.
KVSO_CLASS_FUNCTION (treeWidget , firstChild)
References c, and KvsObject_treeWidgetItem::itemToHandle().
KVSO_CLASS_FUNCTION (treeWidget , currentItem)
References c, and KvsObject_treeWidgetItem::itemToHandle().
KVSO_CLASS_FUNCTION (treeWidget , setColumnCount)
References c, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , setSelectionMode)
References __tr2qs_ctx(), c, KviQString::equalCI(), KVS_PT_NONEMPTYSTRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , topLevelItem)
References c, KvsObject_treeWidgetItem::itemToHandle(), KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , itemAt)
References c, KvsObject_treeWidgetItem::itemToHandle(), KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , addColumn)
References c, KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , showListViewHeader)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (treeWidget , setSortingEnabled)
References c, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , setAllColumnsShowFocus)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (treeWidget , topLevelItemCount)
References c.
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , selectionChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , itemExpandedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , itemChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , setAcceptDrops)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , onItemEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , itemActivatedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , currentChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , itemClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidget , itemCollapsedEvent)