KVIrc: src/modules/objects/KvsObject_hBox.cpp File Reference
src/modules/objects/KvsObject_hBox.cpp File Reference
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KvsObject_hBox.h"
#include "KviTalHBox.h"
Defines
#define _KVI_DEBUG_CHECK_RANGE_
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (hBox, setMargin)
KVSO_CLASS_FUNCTION (hBox, setAlignment)
KVSO_CLASS_FUNCTION (hBox, addStretch)
KVSO_CLASS_FUNCTION (hBox, setStretchFactor)
KVSO_CLASS_FUNCTION (hBox, setSpacing)
Variables
const int align_cod []
const char *const align_tbl []
Define Documentation
#define _KVI_DEBUG_CHECK_RANGE_
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (hBox , setMargin)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (hBox , setAlignment)
References __tr2qs_ctx(), align_cod, align_num, align_tbl, c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KviKvsKernel::instance(), j, KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (hBox , addStretch)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (hBox , setStretchFactor)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (hBox , setSpacing)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
Variable Documentation
const int align_cod[]
Initial value:
 {
        Qt::AlignLeft,
        Qt::AlignRight,
        Qt::AlignHCenter,
        Qt::AlignVCenter,
        Qt::AlignCenter,
        Qt::AlignTop,
        Qt::AlignBottom,
        Qt::AlignJustify,
}
const char* const align_tbl[]
Initial value:
 {
        "Left",
        "Right",
        "HCenter",
        "VCenter",
        "Center",
        "Top",
        "Bottom",
        "WordBreak"
}