KVIrc: src/modules/objects/KvsObject_xmlreader.cpp File Reference
src/modules/objects/KvsObject_xmlreader.cpp File Reference
#include "KvsObject_xmlreader.h"
#include "KvsObject_memoryBuffer.h"
#include "KviLocale.h"
#include "KviKvsVariantList.h"
#include "KviKvsHash.h"
#include <qxml.h>
Classes
class KviXmlHandler
Functions
KVSO_CLASS_FUNCTION (xmlReader, parse)
KVSO_CLASS_FUNCTION (xmlReader, lastError)
Function Documentation
KVSO_CLASS_FUNCTION (xmlReader , parse)
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsVariant::asString(), c, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isHObject(), KviKvsVariant::isString(), KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (xmlReader , lastError)
References c.