KVIrc: src/modules/objects/KvsObject_toolButton.cpp File Reference
KvsObject_toolButton.cpp File Reference
#include "KvsObject_toolButton.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QMenu>
Functions
KVSO_CLASS_FUNCTION (toolButton, setImage)
KVSO_CLASS_FUNCTION (toolButton, setUsesBigPixmap)
KVSO_CLASS_FUNCTION (toolButton, usesBigPixmap)
KVSO_CLASS_FUNCTION (toolButton, setUsesTextLabel)
KVSO_CLASS_FUNCTION (toolButton, usesTextLabel)
KVSO_CLASS_FUNCTION (toolButton, setAutoRaise)
KVSO_CLASS_FUNCTION (toolButton, autoRaise)
KVSO_CLASS_FUNCTION (toolButton, setOn)
KVSO_CLASS_FUNCTION (toolButton, setToggleButton)
KVSO_CLASS_FUNCTION (toolButton, toggle)
KVSO_CLASS_FUNCTION (toolButton, setTextLabel)
KVSO_CLASS_FUNCTION (toolButton, textLabel)
KVSO_CLASS_FUNCTION (toolButton, setPopup)
KVSO_CLASS_FUNCTION (toolButton, openPopup)
KVSO_CLASS_FUNCTION (toolButton, setTextPosition)
KVSO_CLASS_FUNCTION (toolButton, textPosition)
KVSO_CLASS_FUNCTION (toolButton, clickEvent)
Function Documentation
KVSO_CLASS_FUNCTION (toolButton , setImage)
References c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , setUsesBigPixmap)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , usesBigPixmap)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , setUsesTextLabel)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , usesTextLabel)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , setAutoRaise)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , autoRaise)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , setOn)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , setToggleButton)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , toggle)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , setTextLabel)
References c, CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , textLabel)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , setPopup)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (toolButton , openPopup)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , setTextPosition)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (toolButton , textPosition)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (toolButton , clickEvent)
References c.