KVIrc: src/modules/objects/KvsObject_comboBox.cpp File Reference
src/modules/objects/KvsObject_comboBox.cpp File Reference
#include "KviError.h"
#include "KviLocale.h"
#include "kvi_debug.h"
#include "KvsObject_list.h"
#include "KvsObject_comboBox.h"
#include <QLineEdit>
#include <QString>
#include <QComboBox>
#include "m_KvsObject_comboBox.moc"
Functions
KVSO_CLASS_FUNCTION (comboBox, insertItem)
KVSO_CLASS_FUNCTION (comboBox, activatedEvent)
KVSO_CLASS_FUNCTION (comboBox, textChangedEvent)
KVSO_CLASS_FUNCTION (comboBox, setInsertionPolicy)
KVSO_CLASS_FUNCTION (comboBox, popup)
KVSO_CLASS_FUNCTION (comboBox, setCurrentItem)
KVSO_CLASS_FUNCTION (comboBox, changeItem)
KVSO_CLASS_FUNCTION (comboBox, setEditText)
KVSO_CLASS_FUNCTION (comboBox, editable)
KVSO_CLASS_FUNCTION (comboBox, setTextLineEdit)
KVSO_CLASS_FUNCTION (comboBox, setEditable)
KVSO_CLASS_FUNCTION (comboBox, textLineEdit)
KVSO_CLASS_FUNCTION (comboBox, currentItem)
KVSO_CLASS_FUNCTION (comboBox, current)
KVSO_CLASS_FUNCTION (comboBox, count)
KVSO_CLASS_FUNCTION (comboBox, maxCount)
KVSO_CLASS_FUNCTION (comboBox, setMaxCount)
KVSO_CLASS_FUNCTION (comboBox, removeItem)
KVSO_CLASS_FUNCTION (comboBox, textAt)
KVSO_CLASS_FUNCTION (comboBox, clear)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_comboBox, setEditable)
Function Documentation
KVSO_CLASS_FUNCTION (comboBox , insertItem)
References c, CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , activatedEvent)
References c.
KVSO_CLASS_FUNCTION (comboBox , textChangedEvent)
References c.
KVSO_CLASS_FUNCTION (comboBox , setInsertionPolicy)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , popup)
References c, and Q_UNUSED().
KVSO_CLASS_FUNCTION (comboBox , setCurrentItem)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , changeItem)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , setEditText)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_BOOLEAN, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , editable)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (comboBox , setTextLineEdit)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , setEditable)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , textLineEdit)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (comboBox , currentItem)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (comboBox , current)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (comboBox , count)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (comboBox , maxCount)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (comboBox , setMaxCount)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , removeItem)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , textAt)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (comboBox , clear)
References CHECK_INTERNAL_POINTER, and clear().
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_comboBox , setEditable)