KVIrc: src/modules/objects/KvsObject_label.cpp File Reference
src/modules/objects/KvsObject_label.cpp File Reference
#include "KviError.h"
#include "kvi_debug.h"
#include "KvsObject_label.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QFont>
#include <QPixmap>
#include <QMessageBox>
#include <QLabel>
Defines
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
#define frame_num (sizeof(frame_tbl) / sizeof(frame_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (label, setText)
KVSO_CLASS_FUNCTION (label, setImage)
KVSO_CLASS_FUNCTION (label, frameStyle)
KVSO_CLASS_FUNCTION (label, setFrameStyle)
KVSO_CLASS_FUNCTION (label, clear)
KVSO_CLASS_FUNCTION (label, alignment)
KVSO_CLASS_FUNCTION (label, setAlignment)
KVSO_CLASS_FUNCTION (label, margin)
KVSO_CLASS_FUNCTION (label, setMargin)
KVSO_CLASS_FUNCTION (label, text)
Variables
const int align_cod []
const char *const align_tbl []
const int frame_cod []
const char *const frame_tbl []
Define Documentation
#define align_num (sizeof(align_tbl) / sizeof(align_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
#define frame_num (sizeof(frame_tbl) / sizeof(frame_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (label , setText)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (label , setImage)
References c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (label , frameStyle)
References c, CHECK_INTERNAL_POINTER, frame_cod, frame_num, frame_tbl, and i.
KVSO_CLASS_FUNCTION (label , setFrameStyle)
References __tr2qs_ctx(), align_num, c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), frame_cod, frame_tbl, j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (label , clear)
References CHECK_INTERNAL_POINTER, and clear().
KVSO_CLASS_FUNCTION (label , alignment)
References align_cod, align_num, align_tbl, c, CHECK_INTERNAL_POINTER, and i.
KVSO_CLASS_FUNCTION (label , setAlignment)
References __tr2qs_ctx(), align_cod, align_num, align_tbl, c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (label , margin)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (label , setMargin)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (label , text)
References c, and CHECK_INTERNAL_POINTER.
Variable Documentation
const int align_cod[]
Initial value:
 {
        Qt::AlignLeft,
        Qt::AlignRight,
        Qt::AlignHCenter,
        Qt::AlignVCenter,
        Qt::AlignCenter,
        Qt::AlignTop,
        Qt::AlignBottom,
        Qt::AlignJustify,
}
const char* const align_tbl[]
Initial value:
 {
        "Left",
        "Right",
        "HCenter",
        "VCenter",
        "Center",
        "Top",
        "Bottom",
        "WordBreak"
}
const int frame_cod[]
Initial value:
 {
        QFrame::NoFrame,
        QFrame::Box,
        QFrame::Panel,
        QFrame::WinPanel,
        QFrame::HLine,
        QFrame::Plain,
        QFrame::Raised,
        QFrame::Sunken
}
Referenced by KVSO_CLASS_FUNCTION().
const char* const frame_tbl[]
Initial value:
 {
        "NoFrame",
        "Box",
        "Panel",
        "WinPanel",
        "Hline",
        "Plain",
        "Raised",
        "Sunken"
}
Referenced by KVSO_CLASS_FUNCTION().