KVIrc: src/modules/objects/KvsObject_dockWindow.cpp File Reference
KvsObject_dockWindow.cpp File Reference
#include "KvsObject_dockWindow.h"
#include "KviMainWindow.h"
#include "KviLocale.h"
#include "KviQString.h"
#include <QDockWidget>
#include <QLayout>
Macros
#define _pDockWindow ((QDockWidget *)widget())
#define QT_DOCK_WINDOW QDockWidget
Functions
KVSO_CLASS_FUNCTION (dockWindow, addWidget)
KVSO_CLASS_FUNCTION (dockWindow, setAllowedDockAreas)
KVSO_CLASS_FUNCTION (dockWindow, dock)
Macro Definition Documentation
#define _pDockWindow ((QDockWidget *)widget())
Referenced by KVSO_CLASS_FUNCTION().
#define QT_DOCK_WINDOW QDockWidget
Function Documentation
KVSO_CLASS_FUNCTION (dockWindow , addWidget)
References __tr2qs_ctx(), _pDockWindow, c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (dockWindow , setAllowedDockAreas)
References _pDockWindow, c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (dockWindow , dock)
References __tr2qs_ctx(), _pDockWindow, c, CHECK_INTERNAL_POINTER, g_pMainWindow, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.