KVIrc: src/modules/objects/KvsObject_http.cpp File Reference
KvsObject_http.cpp File Reference
#include "KvsObject_http.h"
#include "kvi_debug.h"
#include "KviError.h"
#include "KviLocale.h"
#include <QHttp>
#include <QUrl>
#include <QUrlInfo>
#include <QSslError>
Functions
getDict clear ()
pFile close ()
connect (m_pHttp, SIGNAL(requestFinished(int, bool)), this, SLOT(slotRequestFinished(int, bool)))
connect (m_pHttp, SIGNAL(done(bool)), this, SLOT(slotDone(bool)))
connect (m_pHttp, SIGNAL(requestStarted(int)), this, SLOT(slotRequestStarted(int)))
connect (m_pHttp, SIGNAL(dataSendProgress(int, int)), this, SLOT(slotDataSendProgress(int, int)))
connect (m_pHttp, SIGNAL(dataReadProgress(int, int)), this, SLOT(slotDataReadProgress(int, int)))
connect (m_pHttp, SIGNAL(responseHeaderReceived(const QHttpResponseHeader &)), this, SLOT(slotResponseHeaderReceived(const QHttpResponseHeader &)))
connect (m_pHttp, SIGNAL(readyRead(const QHttpResponseHeader &)), this, SLOT(slotReadyRead(const QHttpResponseHeader &)))
connect (m_pHttp, SIGNAL(sslErrors(const QList< QSslError > &)), this, SLOT(slotSslErrors(const QList< QSslError > &)))
connect (m_pHttp, SIGNAL(stateChanged(int)), this, SLOT(slotStateChanged(int)))
t next ()
QHashIterator< int, QFile * > t (getDict)
Variables
int key =t.key()
m_bAbort =false
m_bEnableForceRedirect =false
m_pHttp = new QHttp()
QFile * pFile =getDict.value(key)
const char *const ssl_errors_tbl []
Function Documentation
getDict clear ()
pFile close ()
Referenced by EventEditorWindow::cancelClicked(), RawEditorWindow::cancelClicked(), AliasEditorWindow::cancelClicked(), ActionEditorWindow::cancelClicked(), PopupEditorWindow::cancelClicked(), ClassEditorWindow::cancelClicked(), UrlDialog::close_slot(), DccVoiceThread::closeSoundcard(), KviWindow::delayedClose(), SocketSpyWindow::die(), KviIOGraphWindow::die(), LinksWindow::die(), SharedFilesWindow::die(), ListWindow::die(), FileTransferWindow::die(), LogViewWindow::die(), DccVoiceWindow::getMixerVolume(), HelpWidget::HelpWidget(), kvi_socket_destroy(), KviTrayIconWidget::KviTrayIconWidget(), KviApplication::notifierMessage(), EventEditorWindow::okClicked(), RawEditorWindow::okClicked(), AliasEditorWindow::okClicked(), ActionEditorWindow::okClicked(), PopupEditorWindow::okClicked(), OptionsDialog::OptionsDialog(), OptionsWidget_servers::OptionsWidget_servers(), DccVoiceWindow::setMixerVolume(), KviMenuBar::setupMainPopup(), TipWindow::TipWindow(), and KviThreadManager::~KviThreadManager().
connect (m_pHttp , SIGNAL(requestFinished(int, bool)) , this , SLOT(slotRequestFinished(int, bool)))
connect (m_pHttp , SIGNAL(done(bool)) , this , SLOT(slotDone(bool)))
connect (m_pHttp , SIGNAL(requestStarted(int)) , this , SLOT(slotRequestStarted(int)))
connect (m_pHttp , SIGNAL(dataSendProgress(int, int)) , this , SLOT(slotDataSendProgress(int, int)))
connect (m_pHttp , SIGNAL(dataReadProgress(int, int)) , this , SLOT(slotDataReadProgress(int, int)))
connect (m_pHttp , SIGNAL(responseHeaderReceived(const QHttpResponseHeader &)) , this , SLOT(slotResponseHeaderReceived(const QHttpResponseHeader &)))
connect (m_pHttp , SIGNAL(readyRead(const QHttpResponseHeader &)) , this , SLOT(slotReadyRead(const QHttpResponseHeader &)))
connect (m_pHttp , SIGNAL(sslErrors(const QList< QSslError > &)) , this , SLOT(slotSslErrors(const QList< QSslError > &)))
connect (m_pHttp , SIGNAL(stateChanged(int)) , this , SLOT(slotStateChanged(int)))
t next ()
Referenced by mediaplayer_module_init().
QHashIterator<int,QFile *> t (getDict)
Referenced by ActionEditorTreeWidgetItem::ActionEditorTreeWidgetItem(), KviIrcContextDisplayAction::activeContextChanged(), KviIrcContextDisplayAction::activeContextStateChanged(), AddonListViewItem::AddonListViewItem(), KviKvsTimerManager::addTimer(), KviConnectAction::addToPopupMenu(), KviGoAwayAction::addToPopupMenu(), DccBroker::addZeroPortTag(), KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::append(), KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::at(), OptionsWidget_mediaTypes::commit(), KviApplication::completeDirectory(), KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::copyFrom(), FileTransferWindow::copyLocalFileToClipboard(), CustomizeToolBarsDialog::CustomizeToolBarsDialog(), dcc_kvs_cmd_chat(), DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog(), dccModuleParseDccChat(), dccModuleParseDccSend(), KviKvsTimerManager::deleteAllTimers(), KviKvsTimerManager::deleteTimer(), CustomizeToolBarsDialog::deleteToolBar(), HttpFileTransfer::done(), DccFileTransfer::done(), KviKvsTreeNodeDataList::dump(), KviKvsTreeNodeDataList::evaluate(), KviTrayIconWidget::event(), KviSoundPlayer::event(), CustomizeToolBarsDialog::exportToolBar(), FileTransferItem::FileTransferItem(), FileTransferWindow::fillTransferView(), OptionsWidget_mediaTypes::fillTreeWidget(), KviKvsSwitchList::find(), FileTransferWindow::findItem(), KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::findRef(), DccBroker::findZeroPortTag(), KviStringConversion::fromString(), KviTrayIconWidget::grabActivityInfo(), DccFileTransfer::handleResumeAccepted(), DccBroker::handleResumeRequest(), DccFileTransfer::handleResumeRequest(), KviFileTransferManager::killAllTransfers(), kvi_irc_vsnprintf(), kvi_vsnprintf(), KviKvsPopupMenuItem::KviKvsPopupMenuItem(), KVSO_CLASS_FUNCTION(), KviTheme::load(), OptionsWidget_soundGeneral::mediaFillBox(), KviMainWindow::moduleExtensionToolBar(), SinglePopupEditor::newItemAbove(), SinglePopupEditor::newItemBelow(), CustomizeToolBarsDialog::newToolBar(), KviPointerHashTable< QString, KviActionCategory >::next(), KviPointerHashTable< QString, KviActionCategory >::nextEntry(), DccFileTransfer::nonFailedTransferWithLocalFileName(), objects_kvs_fnc_variables(), FileTransferWindow::openFilePopupActivated(), FileTransferWindow::openLocalFile(), FileTransferWindow::openLocalFileFolder(), FileTransferWindow::openLocalFileTerminal(), FileTransferWindow::openLocalFileWith(), KviImageDialogItem::paint(), KviIrcServerParser::parseNumericTopicWhoTime(), PopupTreeWidgetItem::PopupTreeWidgetItem(), KviPointerList< KviPointerHashTableEntry< QString, KviAction > >::prepend(), HelpIndex::query(), RegisteredUsersDialogItem::RegisteredUsersDialogItem(), KviCustomToolBarDescriptor::registerToolBar(), CustomizeToolBarsDialog::renameToolBar(), DccBroker::rsendExecute(), DccFileTransfer::runningTransfersCount(), OptionsWidget_mediaTypes::saveLastItem(), KviMainWindow::saveModuleExtensionToolBars(), HelpWindow::searchInIndex(), Idle::secondsIdle(), SingleActionEditor::setActionData(), KviMainWindow::setButtonStyle(), KviIrcConnectionStatistics::setConnectionStartTime(), KviActionManager::setCurrentToolBar(), KviMainWindow::setIconSize(), KviIrcConnectionStatistics::setLastMessageTime(), KviIrcConnectionNetsplitDetectorData::setLastNetsplitOnQuitTime(), KviHttpRequest::setProcessingType(), DccDescriptor::setTransfer(), AliasEditorTreeWidgetItem::setType(), HelpIndex::setupDummyTerm(), KvsObject_http::slotRequestFinished(), OptionsWidget_soundGeneral::soundFillBox(), KviIrcConnectionTargetResolver::start(), KviSoundPlayer::stopAllSoundThreads(), KviKvsTimerManager::timerEvent(), KviStatusBarClock::timerEvent(), KviMainWindow::toolbarsPopupSelected(), window_kvs_fnc_activityLevel(), window_kvs_fnc_activityTemperature(), KviMainWindow::~KviMainWindow(), and KviThreadManager::~KviThreadManager().
Variable Documentation
int key =t.key()
Referenced by KviMainWindow::accelActivated(), KviMircServersIniImport::doImport(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviIpEditor::eventFilter(), KvsObject_widget::eventFilter(), RegisteredUsersDialog::exportClicked(), KviKvsCoreFunctions::KVSCF(), KviLagMeter::lagCheckAbort(), KviLagMeter::lagCheckComplete(), KviLagMeter::lagCheckRegister(), KviTreeWindowListItem::operator<(), HelpIndex::readDict(), reguser_kvs_cmd_showlist(), and UPnP::Service::slotRequestFinished().
m_bAbort =false
m_bEnableForceRedirect =false
delete m_pHttp = new QHttp()
delete pFile =getDict.value(key)
Referenced by LogViewWindow::filterNext(), KvsObject_http::functionGet(), KvsObject_http::functionPost(), KVSO_CLASS_FUNCTION(), KvsObject_http::redirect(), DccSendThread::run(), KviSharedFilesManager::save(), and KvsObject_http::slotRequestFinished().
const char* const ssl_errors_tbl[]
Initial value:
= {
                "NoError",
                "UnableToGetIssuerCertificate",
                "UnableToDecryptCertificateSignature",
                "UnableToDecodeIssuerPublicKey",
                "CertificateSignatureFailed",
                "CertificateNotYetValid",
                "CertificateExpired",
                "InvalidNotBeforeField",
                "InvalidNotAfterField",
                "SelfSignedCertificate",
                "SelfSignedCertificateInChain",
                "UnableToGetLocalIssuerCertificate",
                "UnableToVerifyFirstCertificate",
                "CertificateRevoked",
                "InvalidCaCertificate",
                "PathLengthExceeded",
                "InvalidPurpose",
                "CertificateUntrusted",
                "CertificateRejected",
                "SubjectIssuerMismatch",
                "AuthorityIssuerSerialNumberMismatch",
                "NoPeerCertificate",
                "HostNameMismatch",
                "UnspecifiedError",
                "NoSslSupport"
        }
Referenced by KvsObject_http::slotSslErrors().