KVIrc: src/modules/objects/KvsObject_workspace.cpp File Reference
KvsObject_workspace.cpp File Reference
#include "KvsObject_workspace.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QMdiArea>
#include <QMdiSubWindow>
#include <QHash>
#include <QMimeData>
Functions
if (pWidgetDict)
KVSO_CLASS_FUNCTION (workspace, addSubWindow)
KVSO_CLASS_FUNCTION (workspace, removeSubWindow)
KVSO_CLASS_FUNCTION (workspace, cascade)
KVSO_CLASS_FUNCTION (workspace, tile)
KVSO_CLASS_FUNCTION (workspace, closeActiveWindow)
KVSO_CLASS_FUNCTION (workspace, closeAllWindows)
KVSO_CLASS_FUNCTION (workspace, activateNextWindow)
KVSO_CLASS_FUNCTION (workspace, activatePrevWindow)
KVSO_CLASS_FUNCTION (workspace, activeWindow)
KVSO_CLASS_FUNCTION (workspace, scrollBarsEnabled)
KVSO_CLASS_FUNCTION (workspace, setscrollBarsEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, addSubWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, removeSubWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, activeWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, scrollBarsEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, setscrollBarsEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, cascade)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, tile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, closeActiveWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, closeAllWindows)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, activateNextWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace, activatePrevWindow)
Variables
pWidgetDict = new QHash<kvs_hobject_t, QMdiSubWindow *>
Function Documentation
if (pWidgetDict)
References pWidgetDict.
KVSO_CLASS_FUNCTION (workspace , addSubWindow)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), KviKvsKernel::objectController(), and pWidgetDict.
KVSO_CLASS_FUNCTION (workspace , removeSubWindow)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), and pWidgetDict.
KVSO_CLASS_FUNCTION (workspace , cascade)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , tile)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , closeActiveWindow)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , closeAllWindows)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , activateNextWindow)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , activatePrevWindow)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , activeWindow)
References c, CHECK_INTERNAL_POINTER, pWidgetDict, and t().
KVSO_CLASS_FUNCTION (workspace , scrollBarsEnabled)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (workspace , setscrollBarsEnabled)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , addSubWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , removeSubWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , activeWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , scrollBarsEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , setscrollBarsEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , cascade)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , tile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , closeActiveWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , closeAllWindows)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , activateNextWindow)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_workspace , activatePrevWindow)
Variable Documentation
pWidgetDict = new QHash<kvs_hobject_t, QMdiSubWindow *>
Referenced by if(), and KVSO_CLASS_FUNCTION().