KVIrc: src/modules/objects/KvsObject_memoryBuffer.cpp File Reference
src/modules/objects/KvsObject_memoryBuffer.cpp File Reference
#include "KvsObject_memoryBuffer.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "kvi_settings.h"
#include "KviLocale.h"
#include "QProcess"
#include "KviFileUtils.h"
#include "KviFile.h"
#include <QFileInfo>
#include "m_KvsObject_memoryBuffer.moc"
Functions
KVSO_CLASS_FUNCTION (memoryBuffer, clear)
KVSO_CLASS_FUNCTION (memoryBuffer, size)
KVSO_CLASS_FUNCTION (memoryBuffer, readByteAt)
KVSO_CLASS_FUNCTION (memoryBuffer, saveToFile)
KVSO_CLASS_FUNCTION (memoryBuffer, loadFromFile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer, saveToFile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer, clear)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer, readByteAt)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer, loadFromFile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer, size)
Variables
m_pBuffer = new QByteArray()
mIdx = 0
Function Documentation
KVSO_CLASS_FUNCTION (memoryBuffer , clear)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (memoryBuffer , size)
References c, CHECK_INTERNAL_POINTER, and m_pBuffer.
KVSO_CLASS_FUNCTION (memoryBuffer , readByteAt)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pBuffer.
KVSO_CLASS_FUNCTION (memoryBuffer , saveToFile)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, f, KVS_PT_NONEMPTYSTRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pBuffer.
KVSO_CLASS_FUNCTION (memoryBuffer , loadFromFile)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, f, KviFileUtils::fileExists(), KVS_PT_NONEMPTYSTRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pBuffer.
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer , saveToFile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer , clear)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer , readByteAt)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer , loadFromFile)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_memoryBuffer , size)
Variable Documentation
delete m_pBuffer = new QByteArray()
Referenced by KVSO_CLASS_FUNCTION().
mIdx = 0