KVIrc: src/modules/objects/KvsObject_button.cpp File Reference
KvsObject_button.cpp File Reference
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviError.h"
#include "KviIconManager.h"
#include "KviFile.h"
#include "KvsObject_button.h"
#include "KvsObject_pixmap.h"
#include <QIcon>
#include <QPushButton>
Functions
KVSO_CLASS_FUNCTION (button, text)
KVSO_CLASS_FUNCTION (button, setText)
KVSO_CLASS_FUNCTION (button, setImage)
KVSO_CLASS_FUNCTION (button, clickEvent)
Function Documentation
KVSO_CLASS_FUNCTION (button , text)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (button , setText)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (button , setImage)
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isHObject(), KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (button , clickEvent)
References c.