KVIrc: src/modules/objects/KvsObject_socket.cpp File Reference
KvsObject_socket.cpp File Reference
#include "KvsObject_socket.h"
#include "KvsObject_memoryBuffer.h"
#include "KvsObject_file.h"
#include "kvi_settings.h"
#include "KviQString.h"
#include "kvi_debug.h"
#include "KviFile.h"
#include "KviFileUtils.h"
#include "KviLocale.h"
#include "KviNetUtils.h"
#include "KviDnsResolver.h"
#include "KviError.h"
#include "kvi_socket.h"
#include "KviMemory.h"
#include "KviDataBuffer.h"
#include <QByteArray>
#include <QTcpSocket>
#include <QUdpSocket>
#include <QHostAddress>
Functions
if (m_pSocket &&!bIsSetFromExternal)
if (m_pServer) delete m_pServer
KVSO_CLASS_FUNCTION (socket, status)
KVSO_CLASS_FUNCTION (socket, close)
KVSO_CLASS_FUNCTION (socket, remotePort)
KVSO_CLASS_FUNCTION (socket, remoteIp)
KVSO_CLASS_FUNCTION (socket, localPort)
KVSO_CLASS_FUNCTION (socket, bytesAvailable)
KVSO_CLASS_FUNCTION (socket, localIp)
KVSO_CLASS_FUNCTION (socket, read)
KVSO_CLASS_FUNCTION (socket, write)
KVSO_CLASS_FUNCTION (socket, setProtocol)
KVSO_CLASS_FUNCTION (socket, functionConnect)
KVSO_CLASS_FUNCTION (socket, listen)
KVSO_CLASS_FUNCTION (socket, incomingConnectionEvent)
KVSO_CLASS_FUNCTION (socket, dataAvailableEvent)
KVSO_CLASS_FUNCTION (socket, connectedEvent)
KVSO_CLASS_FUNCTION (socket, disconnectedEvent)
KVSO_CLASS_FUNCTION (socket, errorEvent)
KVSO_CLASS_FUNCTION (socket, hostFoundEvent)
KVSO_CLASS_FUNCTION (socket, stateChangedEvent)
Variables
m_pServer = nullptr
m_pSocket = nullptr
const char *const sockerrors_tbl []
const char *const sockstate_tbl []
Function Documentation
if (m_pSocket &&! bIsSetFromExternal)
References m_pSocket.
if (m_pServer)
KVSO_CLASS_FUNCTION (socket , status)
References c, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , close)
References c, m_pSocket, and Q_UNUSED().
KVSO_CLASS_FUNCTION (socket , remotePort)
References c, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , remoteIp)
References c, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , localPort)
References c, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , bytesAvailable)
References c, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , localIp)
References c, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , read)
References __tr2qs_ctx(), KviMemory::allocate(), c, KviMemory::free(), i, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_INTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pSocket, and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (socket , write)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asHObject(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsArray::at(), c, f, KviFileUtils::fileExists(), i, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isArray(), KviKvsVariant::isHObject(), KviKvsVariant::isString(), KVS_PF_OPTIONAL, KVS_PT_UNSIGNEDINTEGER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pSocket, KviKvsKernel::objectController(), p, pArray, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (socket , setProtocol)
References c, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , functionConnect)
References __tr2qs_ctx(), c, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pSocket.
KVSO_CLASS_FUNCTION (socket , listen)
References __tr2qs_ctx(), c, connect(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pServer.
KVSO_CLASS_FUNCTION (socket , incomingConnectionEvent)
References c.
KVSO_CLASS_FUNCTION (socket , dataAvailableEvent)
References c.
KVSO_CLASS_FUNCTION (socket , connectedEvent)
References c.
KVSO_CLASS_FUNCTION (socket , disconnectedEvent)
References c.
KVSO_CLASS_FUNCTION (socket , errorEvent)
References c.
KVSO_CLASS_FUNCTION (socket , hostFoundEvent)
References c.
KVSO_CLASS_FUNCTION (socket , stateChangedEvent)
References c.
Variable Documentation
m_pServer = nullptr
Referenced by KvsObject_socket::init(), KVSO_CLASS_FUNCTION(), and KviIrcConnectionTarget::server().
m_pSocket = nullptr
Referenced by if(), KvsObject_socket::init(), KVSO_CLASS_FUNCTION(), and KviIrcLink::socket().
const char* const sockerrors_tbl[]
Initial value:
= {
        "ConnectionRefused",
        "RemoteHostClosed",
        "HostNotFound",
        "SocketAccess",
        "SocketResource",
        "SocketTimeout",
        "DatagramTooLarge",
        "Network",
        "AddressInUse",
        "SocketAddressNotAvailable",
        "UnsupportedSocketOperation",
        "ProxyAuthenticationRequired",
        "SslHandshakeFailed",
        "UnfinishedSocketOperation",
        "ProxyConnectionRefused",
        "ProxyConnectionClosed",
        "ProxyConnectionTimeout",
        "ProxyNotFound",
        "ProxyProtocol",
        "UnknownSocket"
}
Referenced by KvsObject_socket::slotError().
const char* const sockstate_tbl[]
Initial value:
= {
        "Unconnected",
        "HostLookUp",
        "Connecting",
        "Connected",
        "Bound",
        "Listening",
        "Closing"
}
Referenced by KvsObject_socket::getStateString().