KVIrc: src/modules/objects/KvsObject_list.cpp File Reference
src/modules/objects/KvsObject_list.cpp File Reference
#include "kvi_debug.h"
#include "KviMemory.h"
#include "KviLocale.h"
#include "KvsObject_list.h"
#include <stdlib.h>
Functions
m_pDataList first ()
int kvi_compare (const KviKvsVariant *p1, const KviKvsVariant *p2)
KVSO_CLASS_FUNCTION (list, isEmpty)
KVSO_CLASS_FUNCTION (list, sort)
KVSO_CLASS_FUNCTION (list, removeLast)
KVSO_CLASS_FUNCTION (list, clear)
KVSO_CLASS_FUNCTION (list, count)
KVSO_CLASS_FUNCTION (list, prepend)
KVSO_CLASS_FUNCTION (list, insert)
KVSO_CLASS_FUNCTION (list, at)
KVSO_CLASS_FUNCTION (list, remove)
KVSO_CLASS_FUNCTION (list, removeFirst)
KVSO_CLASS_FUNCTION (list, removeCurrent)
KVSO_CLASS_FUNCTION (list, moveFirst)
KVSO_CLASS_FUNCTION (list, eof)
KVSO_CLASS_FUNCTION (list, moveNext)
KVSO_CLASS_FUNCTION (list, movePrev)
KVSO_CLASS_FUNCTION (list, moveLast)
KVSO_CLASS_FUNCTION (list, append)
KVSO_CLASS_FUNCTION (list, current)
m_pDataList setAutoDelete (true)
Variables
m_pDataList = new KviPointerList<KviKvsVariant>
Function Documentation
m_pDataList first ()
Referenced by ActionEditor::ActionEditor(), KviConsoleWindow::avatarChangedUpdateWindows(), KviIrcContext::connectionTerminated(), TrayIcon::event(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), KviParameterList::init(), KviKvsEventManager::removeAllModuleAppHandlers(), KviKvsEventManager::removeAllModuleRawHandlers(), KviKvsEventManager::removeAllScriptRawHandlers(), KviKvsEventManager::removeModuleAppHandler(), KviKvsEventManager::removeModuleRawHandler(), KviKvsEventManager::removeScriptAppHandler(), KviKvsEventManager::removeScriptRawHandler(), KviKvsEventManager::saveAppEvents(), KviKvsEventManager::saveRawEvents(), and KviConsoleWindow::updateUri().
int kvi_compare (const KviKvsVariant * p1, const KviKvsVariant * p2) [inline]
References KviKvsVariant::compare().
KVSO_CLASS_FUNCTION (list , isEmpty)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , sort)
References CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , removeLast)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , clear)
References CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , count)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , prepend)
References c, CHECK_INTERNAL_POINTER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pDataList.
KVSO_CLASS_FUNCTION (list , insert)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UINT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pDataList.
KVSO_CLASS_FUNCTION (list , at)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UINT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_pDataList, and v.
KVSO_CLASS_FUNCTION (list , remove)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UINT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pDataList.
KVSO_CLASS_FUNCTION (list , removeFirst)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , removeCurrent)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , moveFirst)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , eof)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , moveNext)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , movePrev)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , moveLast)
References c, CHECK_INTERNAL_POINTER, and m_pDataList.
KVSO_CLASS_FUNCTION (list , append)
References c, CHECK_INTERNAL_POINTER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pDataList.
KVSO_CLASS_FUNCTION (list , current)
References c, CHECK_INTERNAL_POINTER, and v.
m_pDataList setAutoDelete (true)
Variable Documentation
delete m_pDataList = new KviPointerList<KviKvsVariant>
Referenced by KVSO_CLASS_FUNCTION().