KVIrc: src/modules/objects/KvsObject_buttonGroup.cpp File Reference
KvsObject_buttonGroup.cpp File Reference
#include "KvsObject_buttonGroup.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QButtonGroup>
#include <QRadioButton>
Functions
btnDict clear ()
KVSO_CLASS_FUNCTION (buttonGroup, addButton)
KVSO_CLASS_FUNCTION (buttonGroup, checkedButton)
btnDict setAutoDelete (false)
Variables
m_iId =0
m_pButtonGroup =new QButtonGroup()
Function Documentation
btnDict clear ()
Referenced by KviKvsPopupMenu::clearMenuContents(), KviKvsPopupMenu::doClear(), KviHistoryWindow::fill(), KvsObject_textedit::functionclear(), KVSO_CLASS_FUNCTION(), KviKvsParameterProcessor::process(), KviKvsParameterProcessor::setDefaultValue(), KviKvsPopupMenu::setupMenuContents(), AliasEditorTreeWidget::~AliasEditorTreeWidget(), and ClassEditorTreeWidget::~ClassEditorTreeWidget().
KVSO_CLASS_FUNCTION (buttonGroup , addButton)
References __tr2qs_ctx(), c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_iId, KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (buttonGroup , checkedButton)
References c, CHECK_INTERNAL_POINTER, and m_pButtonGroup.
btnDict setAutoDelete (false)
Referenced by KviKvsParameterProcessor::process(), and KviKvsParameterProcessor::setDefaultValue().
Variable Documentation
m_iId =0
Referenced by KviStatusBarAppletDescriptor::id(), KviModuleExtensionDescriptor::id(), KviKvsTimer::id(), KviFileTransfer::id(), and KVSO_CLASS_FUNCTION().
delete m_pButtonGroup =new QButtonGroup()
Referenced by KVSO_CLASS_FUNCTION().