KVIrc: src/modules/objects/KvsObject_ftp.cpp File Reference
KvsObject_ftp.cpp File Reference
#include "KvsObject_ftp.h"
#include "kvi_debug.h"
#include "KviError.h"
#include "KviLocale.h"
#include <qftp.h>
#include <QHashIterator>
Functions
connect (m_pFtp, SIGNAL(commandFinished(int, bool)), this, SLOT(slotCommandFinished(int, bool)))
connect (m_pFtp, SIGNAL(commandStarted(int)), this, SLOT(slotCommandStarted(int)))
connect (m_pFtp, SIGNAL(dataTransferProgress(qint64, qint64)), this, SLOT(slotDataTransferProgress(qint64, qint64)))
connect (m_pFtp, SIGNAL(done(bool)), this, SLOT(slotDone(bool)))
connect (m_pFtp, SIGNAL(listInfo(const QUrlInfo)), this, SLOT(slotListInfo(const QUrlInfo)))
connect (m_pFtp, SIGNAL(readyRead()), this, SLOT(slotReadyRead()))
connect (m_pFtp, SIGNAL(stateChanged(int)), this, SLOT(slotStateChanged(int)))
KVSO_CLASS_FUNCTION (ftp, functionConnect)
KVSO_CLASS_FUNCTION (ftp, login)
KVSO_CLASS_FUNCTION (ftp, get)
KVSO_CLASS_FUNCTION (ftp, put)
KVSO_CLASS_FUNCTION (ftp, cd)
KVSO_CLASS_FUNCTION (ftp, list)
KVSO_CLASS_FUNCTION (ftp, abort)
KVSO_CLASS_FUNCTION (ftp, close)
KVSO_CLASS_FUNCTION (ftp, commandFinishedEvent)
KVSO_CLASS_FUNCTION (ftp, dataTransferProgressEvent)
KVSO_CLASS_FUNCTION (ftp, listInfoEvent)
KVSO_CLASS_FUNCTION (ftp, stateChangedEvent)
Variables
m_pFtp = new QFtp()
Function Documentation
connect (m_pFtp , SIGNAL(commandFinished(int, bool)) , this , SLOT(slotCommandFinished(int, bool)))
Referenced by AboutDialog::AboutDialog(), ActionEditor::ActionEditor(), ActionEditorWindow::ActionEditorWindow(), DccBroker::activeVideoManage(), DccBroker::activeVoiceManage(), KviKvsDnsManager::addDns(), KviMenuBar::addMenu(), AddonManagementDialog::AddonManagementDialog(), KviOptionsWidget::addOptionsWidget(), KviConnectAction::addToCustomToolBar(), KviSubmenuAction::addToCustomToolBar(), KviGoAwayAction::addToCustomToolBar(), KviAction::addToCustomToolBar(), AliasEditorWidget::AliasEditorWidget(), AliasEditorWindow::AliasEditorWindow(), KviInput::applyOptions(), KvsObject_painter::attachDevice(), AvatarDownloadDialog::AvatarDownloadDialog(), AvatarSelectionDialog::AvatarSelectionDialog(), BanFrame::BanFrame(), KviIrcContext::beginAsynchronousConnect(), UPnP::Service::callActionInternal(), UPnP::Service::callInformationUrl(), ChannelsJoinDialog::ChannelsJoinDialog(), KviStatusBarUpdateIndicator::checkVersion(), KviWindow::childInserted(), ClassEditorWidget::ClassEditorWidget(), ClassEditorWindow::ClassEditorWindow(), CodeTesterWidget::CodeTesterWidget(), ConfigDialog::ConfigDialog(), DccFileTransfer::configureBandwidth(), ScriptEditorImplementation::configureColors(), DccVoiceWindow::connected(), KviIrcSocket::connectedToProxy(), KviConsoleWindow::connectionAttached(), QFtpDTP::connectToHost(), KviStatusBar::contextMenuRequested(), NotifierWindow::contextPopup(), KviStatusBar::contextPopupAboutToShow(), ScriptEditorWidget::createCompleter(), KviWindow::createCryptControllerButton(), KviIrcLink::createSocket(), KviWindow::createSystemTextEncodingPopup(), KviWindow::createTextEncodingButton(), OptionsWidget_textIcons::currentItemChanged(), CustomizeToolBarsDialog::CustomizeToolBarsDialog(), CustomToolBarPropertiesDialog::CustomToolBarPropertiesDialog(), DccAcceptDialog::DccAcceptDialog(), DccChatWindow::DccChatWindow(), DccFileTransfer::DccFileTransfer(), DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog(), DccRenameDialog::DccRenameDialog(), DccVideoWindow::DccVideoWindow(), DccVoiceWindow::DccVoiceWindow(), KviIrcConnection::delayedStartNotifyList(), DccMarshal::doConnect(), KviHttpRequest::doConnect(), NotifierWindow::doHide(), DccMarshal::doListen(), OptionsWidget_textIcons::doPopup(), NotifierWindow::doShow(), DccMarshal::doSSLHandshake(), KviIrcSocket::doSSLHandshake(), NotifierWindow::enterEvent(), EventEditor::EventEditor(), EventEditorWindow::EventEditorWindow(), FileTransferWindow::FileTransferWindow(), KviKvsPopupMenuItemLabel::fill(), KviStatusBarClock::fillContextPopup(), KviMainWindow::fillToolBarsPopup(), KviCustomToolBar::filterChild(), TrashcanLabel::flash(), OptionsInstanceManager::getInstance(), ThemeManagementDialog::getMoreThemes(), KviIrcView::getTextLine(), DccBroker::handleChatRequest(), HelpIndex::HelpIndex(), HelpWidget::HelpWidget(), HelpWindow::HelpWindow(), HttpFileTransfer::HttpFileTransfer(), OptionsWidget_textIcons::iconSelected(), IdentityProfileEditor::IdentityProfileEditor(), Idle::Idle(), UPnP::IgdControlPoint::IgdControlPoint(), OptionsWidget_servers::importPopupActivated(), KvsObject_button::init(), KvsObject_listWidget::init(), KvsObject_slider::init(), KvsObject_spinBox::init(), KvsObject_tabWidget::init(), KvsObject_radioButton::init(), KvsObject_toolButton::init(), KvsObject_checkBox::init(), KvsObject_colorDialog::init(), KvsObject_comboBox::init(), KvsObject_popupMenu::init(), KvsObject_textBrowser::init(), KvsObject_dateTimeEdit::init(), KvsObject_lineEdit::init(), KvsObject_treeWidget::init(), KvsObject_tableWidget::init(), QHttpPrivate::init(), UPnP::Manager::initialize(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), kvi_socket_connect(), KviAnimatedPixmapCache::KviAnimatedPixmapCache(), KviAsyncAvatarSelectionDialog::KviAsyncAvatarSelectionDialog(), KviChannelListSelector::KviChannelListSelector(), KviChannelWindow::KviChannelWindow(), KviClassEditorDialog::KviClassEditorDialog(), KviClassEditorFunctionDialog::KviClassEditorFunctionDialog(), KviColorSelector::KviColorSelector(), KviConsoleWindow::KviConsoleWindow(), KviCtcpPageDialog::KviCtcpPageDialog(), KviCustomToolBar::KviCustomToolBar(), KviDefaultScriptDialog::KviDefaultScriptDialog(), KviFileSelector::KviFileSelector(), KviFontSelector::KviFontSelector(), KviHistoryWindow::KviHistoryWindow(), KviHtmlDialog::KviHtmlDialog(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), KviImageDialog::KviImageDialog(), KviInput::KviInput(), KviInputEditor::KviInputEditor(), KviIrcConnectionRequestQueue::KviIrcConnectionRequestQueue(), KviIrcContextDisplay::KviIrcContextDisplay(), KviIrcSocket::KviIrcSocket(), KviIrcView::KviIrcView(), KviIrcViewToolWidget::KviIrcViewToolWidget(), KviIsOnNotifyListManager::KviIsOnNotifyListManager(), KviKvsAsyncDnsOperation::KviKvsAsyncDnsOperation(), KviKvsCallbackTextInput::KviKvsCallbackTextInput(), KviKvsMdmWizard::KviKvsMdmWizard(), KviKvsPopupMenu::KviKvsPopupMenu(), KviMaskEditor::KviMaskEditor(), KviMaskInputDialog::KviMaskInputDialog(), KviMenuBar::KviMenuBar(), KviMircTextColorSelector::KviMircTextColorSelector(), KviModeEditor::KviModeEditor(), KviModuleManager::KviModuleManager(), KviPasswordLineEdit::KviPasswordLineEdit(), KviPasswordSelector::KviPasswordSelector(), KviPixmapSelector::KviPixmapSelector(), KviQueryWindow::KviQueryWindow(), KviRemoteMircServerImportWizard::KviRemoteMircServerImportWizard(), KviScriptUserButton::KviScriptUserButton(), KviSharedFilesManager::KviSharedFilesManager(), KviSoundSelector::KviSoundSelector(), KviStatusBar::KviStatusBar(), KviStatusBarAwayIndicator::KviStatusBarAwayIndicator(), KviStatusBarLagIndicator::KviStatusBarLagIndicator(), KviStringListSelector::KviStringListSelector(), KviTalApplication::KviTalApplication(), KviTalWizard::KviTalWizard(), KviTextIconWindow::KviTextIconWindow(), KviThreadManager::KviThreadManager(), KviTopicWidget::KviTopicWidget(), KviTrayIconWidget::KviTrayIconWidget(), KviTreeWindowList::KviTreeWindowList(), KviUserListViewArea::KviUserListViewArea(), KviWindow::KviWindow(), KviWindowListBase::KviWindowListBase(), KviWindowListButton::KviWindowListButton(), KviWindowStack::KviWindowStack(), KVSO_CLASS_FUNCTION(), NotifierWindow::leaveEvent(), LinksWindow::LinksWindow(), KviIrcSocket::linkUp(), ListWindow::ListWindow(), LogViewWindow::LogViewWindow(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::lookupServerHostname(), KvsObject_socket::makeConnections(), KviToolBar::mousePressEvent(), KviTopicWidget::mousePressEvent(), NickAlternativesDialog::NickAlternativesDialog(), NickServRuleEditor::NickServRuleEditor(), KviApplication::notifierMessage(), NotifierWindow::NotifierWindow(), NotifierWindowTab::NotifierWindowTab(), EventEditor::oneTimeSetup(), AliasEditorWidget::oneTimeSetup(), PopupEditorWidget::oneTimeSetup(), ClassEditorWidget::oneTimeSetup(), OptionsDialog::OptionsDialog(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_antispam::OptionsWidget_antispam(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_ignore::OptionsWidget_ignore(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_mediaTypes::OptionsWidget_mediaTypes(), OptionsWidget_messageColors::OptionsWidget_messageColors(), OptionsWidget_nickServ::OptionsWidget_nickServ(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_standardColors::OptionsWidget_standardColors(), OptionsWidget_textIcons::OptionsWidget_textIcons(), OptionsWidget_theme::OptionsWidget_theme(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_timestamp::OptionsWidget_timestamp(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), PackAddonSummaryFilesWidget::PackAddonSummaryFilesWidget(), PackThemeImageWidget::PackThemeImageWidget(), DccBroker::passiveVideoExecute(), SlowPasteController::pasteClipboardInit(), SlowPasteController::pasteFileInit(), KviHistoryWindow::popup(), KviTextIconWindow::popup(), UrlDialog::popup(), PopupEditorWidget::PopupEditorWidget(), PopupEditorWindow::PopupEditorWindow(), ListWindow::processData(), KviIrcSocket::proxyHandleHttpFinalReply(), QFtp::QFtp(), QFtpDTP::QFtpDTP(), QFtpPI::QFtpPI(), RawEditorWidget::RawEditorWidget(), RawEditorWindow::RawEditorWindow(), DccBroker::recvFileManage(), KviAction::registerAccelerator(), KviActionManager::registerAction(), KviAction::registerAction(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), RegisteredUserMaskDialog::RegisteredUserMaskDialog(), RegisteredUserPropertiesDialog::RegisteredUserPropertiesDialog(), RegisteredUsersDialog::RegisteredUsersDialog(), RegistrationWizard::RegistrationWizard(), DccBroker::renameOverwriteResume(), FileTransferWindow::rightButtonPressed(), RegisteredUsersDialog::rightButtonPressed(), SaveThemeDialog::SaveThemeDialog(), ScriptEditorImplementation::ScriptEditorImplementation(), ScriptEditorReplaceDialog::ScriptEditorReplaceDialog(), ScriptEditorWidget::ScriptEditorWidget(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), KviTalTabDialog::setCancelButton(), KviIrcView::setMasterView(), KviKvsObject::setObject(), KviTalTabDialog::setOkButton(), QHttpPrivate::setSock(), OptionsWidgetContainer::setup(), KviSubmenuAction::setup(), KviIrcContextDisplayAction::setup(), KviGoAwayAction::setup(), KviAction::setup(), KviIrcUserDataBase::setupConnectionWithReguserDb(), QFtpDTP::setupSocket(), SetupWizard::SetupWizard(), SharedFileEditDialog::SharedFileEditDialog(), SharedFilesWindow::SharedFilesWindow(), KviChannelWindow::showDoubleView(), KviStatusBar::showFirstMessageInQueue(), KviIconManager::showIconWidget(), SingleActionEditor::SingleActionEditor(), SinglePopupEditor::SinglePopupEditor(), UPnP::IgdControlPoint::slotDeviceQueried(), ScriptEditorWidget::slotReplace(), UPnP::SsdpConnection::SsdpConnection(), KviRemoteMircServerImportWizard::start(), KviIrcConnectionTargetResolver::start(), KviKvsProcessAsyncOperation::start(), KviIrcLink::start(), NotifierWindow::startAutoHideTimer(), NotifierWindow::startBlinking(), KviIrcSocket::startConnection(), DccFileTransfer::startConnection(), AvatarDownloadDialog::startDownload(), StatusBarApplet::StatusBarApplet(), KviTopicWidget::switchMode(), SinglePopupEditor::testPopup(), ThemeManagementDialog::ThemeManagementDialog(), TipWindow::TipWindow(), KviWindow::toggleCryptController(), KviChannelWindow::toggleListModeEditor(), KviChannelWindow::toggleModeEditor(), HttpFileTransfer::transferTerminated(), TrashcanLabel::TrashcanLabel(), KviUserListEntry::updateAvatarData(), UrlDialog::UrlDialog(), and KviIrcConnection::userInfoReceived().
connect (m_pFtp , SIGNAL(commandStarted(int)) , this , SLOT(slotCommandStarted(int)))
connect (m_pFtp , SIGNAL(dataTransferProgress(qint64, qint64)) , this , SLOT(slotDataTransferProgress(qint64, qint64)))
connect (m_pFtp , SIGNAL(done(bool)) , this , SLOT(slotDone(bool)))
connect (m_pFtp , SIGNAL(listInfo(const QUrlInfo)) , this , SLOT(slotListInfo(const QUrlInfo)))
connect (m_pFtp , SIGNAL(readyRead()) , this , SLOT(slotReadyRead()))
connect (m_pFtp , SIGNAL(stateChanged(int)) , this , SLOT(slotStateChanged(int)))
KVSO_CLASS_FUNCTION (ftp , functionConnect)
References c, CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and szHost.
KVSO_CLASS_FUNCTION (ftp , login)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , get)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , put)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , cd)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , list)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , abort)
References CHECK_INTERNAL_POINTER, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , close)
References CHECK_INTERNAL_POINTER, and m_pFtp.
KVSO_CLASS_FUNCTION (ftp , commandFinishedEvent)
References c.
KVSO_CLASS_FUNCTION (ftp , dataTransferProgressEvent)
References c.
KVSO_CLASS_FUNCTION (ftp , listInfoEvent)
References c.
KVSO_CLASS_FUNCTION (ftp , stateChangedEvent)
References c.
Variable Documentation
delete m_pFtp = new QFtp()
Referenced by KVSO_CLASS_FUNCTION().