KVIrc: src/modules/objects/KvsObject_widget.cpp File Reference
KvsObject_widget.cpp File Reference
#include "KvsObject_widget.h"
#include "KvsObject_pixmap.h"
#include "KviMemory.h"
#include "kvi_debug.h"
#include "KviError.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include "KviWindow.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviStatusBar.h"
#include "KvsObject_painter.h"
#include <QKeyEvent>
#include <QDesktopWidget>
#include <QWidget>
#include <QToolTip>
#include <QFont>
#include <QVariant>
#include <QCursor>
#include <QColor>
#include <QLayout>
#include <QBitmap>
#include <QMetaObject>
#include <QIcon>
#include <QStatusBar>
#include <QUrl>
#include <QPainter>
#include <QApplication>
#include <QPoint>
#include <QContextMenuEvent>
Macros
#define colorrole_num (sizeof(colorrole_tbl) / sizeof(colorrole_tbl[0]))
#define QT_WIDGET_CLICKFOCUS Qt::ClickFocus
#define QT_WIDGET_NOFOCUS Qt::NoFocus
#define QT_WIDGET_STRONGFOCUS Qt::StrongFocus
#define QT_WIDGET_TABFOCUS Qt::TabFocus
#define widgetattributes_num (sizeof(widgetattributes_tbl) / sizeof(widgetattributes_tbl[0]))
#define widgettypes_num (sizeof(widgettypes_tbl) / sizeof(widgettypes_tbl[0]))
Functions
emit aboutToDie ()
KVSO_CLASS_FUNCTION (widget, show)
KVSO_CLASS_FUNCTION (widget, update)
KVSO_CLASS_FUNCTION (widget, setEnabled)
KVSO_CLASS_FUNCTION (widget, isEnabled)
KVSO_CLASS_FUNCTION (widget, fontDescent)
KVSO_CLASS_FUNCTION (widget, fontAscent)
KVSO_CLASS_FUNCTION (widget, repaint)
KVSO_CLASS_FUNCTION (widget, fontMetricsWidth)
KVSO_CLASS_FUNCTION (widget, fontMetricsHeight)
KVSO_CLASS_FUNCTION (widget, fontMetricsLineSpacing)
KVSO_CLASS_FUNCTION (widget, screenResolution)
KVSO_CLASS_FUNCTION (widget, geometry)
KVSO_CLASS_FUNCTION (widget, setGeometry)
KVSO_CLASS_FUNCTION (widget, mapToGlobal)
KVSO_CLASS_FUNCTION (widget, mapFromGlobal)
KVSO_CLASS_FUNCTION (widget, centerToScreen)
KVSO_CLASS_FUNCTION (widget, setForegroundColor)
KVSO_CLASS_FUNCTION (widget, setBackgroundColor)
KVSO_CLASS_FUNCTION (widget, backgroundColor)
KVSO_CLASS_FUNCTION (widget, foregroundColor)
KVSO_CLASS_FUNCTION (widget, parentWidget)
KVSO_CLASS_FUNCTION (widget, setMouseTracking)
KVSO_CLASS_FUNCTION (widget, setWindowTitle)
KVSO_CLASS_FUNCTION (widget, windowTitle)
KVSO_CLASS_FUNCTION (widget, isTopLevel)
KVSO_CLASS_FUNCTION (widget, isVisible)
KVSO_CLASS_FUNCTION (widget, raise)
KVSO_CLASS_FUNCTION (widget, lower)
KVSO_CLASS_FUNCTION (widget, hasFocus)
KVSO_CLASS_FUNCTION (widget, setFocus)
KVSO_CLASS_FUNCTION (widget, hide)
KVSO_CLASS_FUNCTION (widget, setToolTip)
KVSO_CLASS_FUNCTION (widget, x)
KVSO_CLASS_FUNCTION (widget, y)
KVSO_CLASS_FUNCTION (widget, width)
KVSO_CLASS_FUNCTION (widget, height)
KVSO_CLASS_FUNCTION (widget, setMinimumWidth)
KVSO_CLASS_FUNCTION (widget, setMinimumHeight)
KVSO_CLASS_FUNCTION (widget, setMaximumWidth)
KVSO_CLASS_FUNCTION (widget, setMaximumHeight)
KVSO_CLASS_FUNCTION (widget, move)
KVSO_CLASS_FUNCTION (widget, sizeHint)
KVSO_CLASS_FUNCTION (widget, resize)
KVSO_CLASS_FUNCTION (widget, setFocusPolicy)
KVSO_CLASS_FUNCTION (widget, setWFlags)
KVSO_CLASS_FUNCTION (widget, setFont)
KVSO_CLASS_FUNCTION (widget, addWidgetToWrappedLayout)
KVSO_CLASS_FUNCTION (widget, setParent)
KVSO_CLASS_FUNCTION (widget, setWindowIcon)
KVSO_CLASS_FUNCTION (widget, setBackgroundImage)
KVSO_CLASS_FUNCTION (widget, globalCursorX)
KVSO_CLASS_FUNCTION (widget, globalCursorY)
KVSO_CLASS_FUNCTION (widget, setMask)
KVSO_CLASS_FUNCTION (widget, setAttribute)
KVSO_CLASS_FUNCTION (widget, colorPalette)
KVSO_CLASS_FUNCTION (widget, setStyleSheet)
KVSO_CLASS_FUNCTION (widget, setKeyShortcut)
KVSO_CLASS_FUNCTION (widget, insertIntoStatusBar)
KVSO_CLASS_FUNCTION (widget, removeFromStatusBar)
KVSO_CLASS_FUNCTION (widget, grab)
Variables
const QPalette::ColorRole colorrole_cod []
const char *const colorrole_tbl []
const Qt::WidgetAttribute widgetattributes_cod []
const char *const widgetattributes_tbl []
const Qt::WindowType widgettypes_cod []
const char *const widgettypes_tbl []
Macro Definition Documentation
#define colorrole_num (sizeof(colorrole_tbl) / sizeof(colorrole_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
#define QT_WIDGET_CLICKFOCUS Qt::ClickFocus
Referenced by KVSO_CLASS_FUNCTION().
#define QT_WIDGET_NOFOCUS Qt::NoFocus
Referenced by KVSO_CLASS_FUNCTION().
#define QT_WIDGET_STRONGFOCUS Qt::StrongFocus
Referenced by KVSO_CLASS_FUNCTION().
#define QT_WIDGET_TABFOCUS Qt::TabFocus
Referenced by KVSO_CLASS_FUNCTION().
#define widgetattributes_num (sizeof(widgetattributes_tbl) / sizeof(widgetattributes_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
#define widgettypes_num (sizeof(widgettypes_tbl) / sizeof(widgettypes_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
emit aboutToDie ()
KVSO_CLASS_FUNCTION (widget , show)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , update)
References c, CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setEnabled)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , isEnabled)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , fontDescent)
References c, CHECK_INTERNAL_POINTER, and d.
KVSO_CLASS_FUNCTION (widget , fontAscent)
References c, CHECK_INTERNAL_POINTER, and d.
KVSO_CLASS_FUNCTION (widget , repaint)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , fontMetricsWidth)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , fontMetricsHeight)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , fontMetricsLineSpacing)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , screenResolution)
References a, c, CHECK_INTERNAL_POINTER, g_pApp, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , geometry)
References a, c, CHECK_INTERNAL_POINTER, r, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , setGeometry)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsArray::at(), c, CHECK_INTERNAL_POINTER, KviKvsVariant::isArray(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (widget , mapToGlobal)
References a, c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , mapFromGlobal)
References a, c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , centerToScreen)
References CHECK_INTERNAL_POINTER, and g_pApp.
KVSO_CLASS_FUNCTION (widget , setForegroundColor)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsArray::at(), c, CHECK_INTERNAL_POINTER, KviKvsVariant::isArray(), KviKvsVariant::isString(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, p, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (widget , setBackgroundColor)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsArray::at(), c, CHECK_INTERNAL_POINTER, KviKvsVariant::isArray(), KviKvsVariant::isString(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, p, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (widget , backgroundColor)
References a, c, CHECK_INTERNAL_POINTER, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , foregroundColor)
References a, c, CHECK_INTERNAL_POINTER, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , parentWidget)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , setMouseTracking)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setWindowTitle)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , windowTitle)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , isTopLevel)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , isVisible)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , raise)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , lower)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , hasFocus)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , setFocus)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , hide)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , setToolTip)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , x)
References c, CHECK_INTERNAL_POINTER, and x.
KVSO_CLASS_FUNCTION (widget , y)
References c, CHECK_INTERNAL_POINTER, and y.
KVSO_CLASS_FUNCTION (widget , width)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , height)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (widget , setMinimumWidth)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setMinimumHeight)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setMaximumWidth)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setMaximumHeight)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , move)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsArray::at(), c, CHECK_INTERNAL_POINTER, KviKvsVariant::isArray(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (widget , sizeHint)
References a, c, CHECK_INTERNAL_POINTER, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , resize)
References __tr2qs_ctx(), KviKvsVariant::array(), KviKvsVariant::asInteger(), KviKvsArray::at(), c, CHECK_INTERNAL_POINTER, KviKvsVariant::isArray(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::size().
KVSO_CLASS_FUNCTION (widget , setFocusPolicy)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, QT_WIDGET_CLICKFOCUS, QT_WIDGET_NOFOCUS, QT_WIDGET_STRONGFOCUS, and QT_WIDGET_TABFOCUS.
KVSO_CLASS_FUNCTION (widget , setWFlags)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widgettypes_num.
KVSO_CLASS_FUNCTION (widget , setFont)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), i, KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , addWidgetToWrappedLayout)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (widget , setParent)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (widget , setWindowIcon)
References c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setBackgroundImage)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , globalCursorX)
References c, CHECK_INTERNAL_POINTER, and x.
KVSO_CLASS_FUNCTION (widget , globalCursorY)
References c, CHECK_INTERNAL_POINTER, and y.
KVSO_CLASS_FUNCTION (widget , setMask)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (widget , setAttribute)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), j, KVS_PT_BOOLEAN, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and widgetattributes_num.
KVSO_CLASS_FUNCTION (widget , colorPalette)
References __tr2qs_ctx(), a, c, CHECK_INTERNAL_POINTER, colorrole_num, KviQString::equalCI(), j, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (widget , setStyleSheet)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , setKeyShortcut)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (widget , insertIntoStatusBar)
References CHECK_INTERNAL_POINTER, g_pMainWindow, KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviMainWindow::mainStatusBar().
KVSO_CLASS_FUNCTION (widget , removeFromStatusBar)
References CHECK_INTERNAL_POINTER, and g_pMainWindow.
KVSO_CLASS_FUNCTION (widget , grab)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsObject::handle(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupClass(), KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
Variable Documentation
const QPalette::ColorRole colorrole_cod[]
Initial value:
= {
        QPalette::Window,
        QPalette::Background,
        QPalette::WindowText,
        QPalette::Foreground,
        QPalette::Base,
        QPalette::AlternateBase,
        QPalette::Text,
        QPalette::Button,
        QPalette::ButtonText,
        QPalette::BrightText,
        QPalette::Highlight,
        QPalette::HighlightedText
}
const char* const colorrole_tbl[]
Initial value:
= {
        "Window",
        "Background",
        "WindowText",
        "Foreground",
        "Base",
        "AlternateBase",
        "Text",
        "Button",
        "ButtonText",
        "BrightText",
        "Highlight",
        "HighlightedText"
}
const Qt::WidgetAttribute widgetattributes_cod[]
Initial value:
= {
        Qt::WA_OpaquePaintEvent,
        Qt::WA_NoSystemBackground,
        Qt::WA_PaintOnScreen,
        Qt::WA_NoMousePropagation
}
const char* const widgetattributes_tbl[]
Initial value:
= {
        "opaquePaintEvent",
        "noSystemBackground",
        "paintOnScreen",
        "noMousePropagation"
}
const Qt::WindowType widgettypes_cod[]
Initial value:
= {
        Qt::Window,
        Qt::Dialog,
        Qt::Popup,
        Qt::Desktop,
        Qt::WindowTitleHint,
        Qt::WindowStaysOnTopHint,
        Qt::WindowSystemMenuHint,
        Qt::WindowMinimizeButtonHint,
        Qt::WindowMaximizeButtonHint,
        Qt::SubWindow,
        Qt::FramelessWindowHint
}
const char* const widgettypes_tbl[]
Initial value:
= {
        "Window",
        "Dialog",
        "Popup",
        "Desktop",
        "Title",
        "StaysOnTop",
        "SysMenu",
        "Minimize",
        "Maximize",
        "Subwindow",
        "FramelessWindow"
}