KVIrc: src/modules/objects/KvsObject_window.cpp File Reference
src/modules/objects/KvsObject_window.cpp File Reference
#include "KvsObject_window.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviIconManager.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
#include "m_KvsObject_window.moc"
Functions
if (widget()) g_pMainWindow->closeWindow(((KviKvsScriptWindowWindow *) widget()))
KVSO_CLASS_FUNCTION (window, setCentralWidget)
KVSO_CLASS_FUNCTION (window, setIcon)
KVSO_CLASS_FUNCTION (window, setWindowTitle)
Function Documentation
if (widget())
KVSO_CLASS_FUNCTION (window , setCentralWidget)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (window , setIcon)
References c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (window , setWindowTitle)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.