KVIrc: src/modules/objects/KvsObject_lcd.cpp File Reference
src/modules/objects/KvsObject_lcd.cpp File Reference
#include "KvsObject_lcd.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QLCDNumber>
Functions
KVSO_CLASS_FUNCTION (lcd, displayInt)
KVSO_CLASS_FUNCTION (lcd, checkOverflow)
KVSO_CLASS_FUNCTION (lcd, setSmallDecimalPoint)
KVSO_CLASS_FUNCTION (lcd, setNumDigits)
KVSO_CLASS_FUNCTION (lcd, setSegmentStyle)
KVSO_CLASS_FUNCTION (lcd, setMode)
KVSO_CLASS_FUNCTION (lcd, displayDouble)
KVSO_CLASS_FUNCTION (lcd, displayStr)
Function Documentation
KVSO_CLASS_FUNCTION (lcd , displayInt)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , checkOverflow)
References c, CHECK_INTERNAL_POINTER, KVS_PT_DOUBLE, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , setSmallDecimalPoint)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , setNumDigits)
References c, CHECK_INTERNAL_POINTER, KVS_PT_DOUBLE, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , setSegmentStyle)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , setMode)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , displayDouble)
References c, CHECK_INTERNAL_POINTER, KVS_PT_DOUBLE, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lcd , displayStr)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.