KVIrc: src/modules/objects/KvsObject_popupMenu.cpp File Reference
src/modules/objects/KvsObject_popupMenu.cpp File Reference
#include "KvsObject_popupMenu.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QCursor>
#include <QMenu>
#include <QAction>
#include "m_KvsObject_popupMenu.moc"
Functions
static int addActionToDict (QAction *pAction)
static QAction * getAction (int idx)
KVSO_CLASS_FUNCTION (popupMenu, highlightedEvent)
KVSO_CLASS_FUNCTION (popupMenu, insertItem)
KVSO_CLASS_FUNCTION (popupMenu, addMenu)
KVSO_CLASS_FUNCTION (popupMenu, removeItem)
KVSO_CLASS_FUNCTION (popupMenu, exec)
KVSO_CLASS_FUNCTION (popupMenu, setTitle)
KVSO_CLASS_FUNCTION (popupMenu, insertSeparator)
KVSO_CLASS_FUNCTION (popupMenu, activatedEvent)
static void removeAction (int idx)
static void removeMenuAllActions (QMenu *pMenu)
Variables
static QHash< int, QAction * > actionsDict
static int iIdentifier = 0
Function Documentation
static int addActionToDict (QAction * pAction) [static]
References actionsDict, and iIdentifier.
Referenced by KVSO_CLASS_FUNCTION().
static QAction* getAction (int idx) [static]
References actionsDict.
Referenced by action_kvs_fnc_exists(), and KVSO_CLASS_FUNCTION().
KVSO_CLASS_FUNCTION (popupMenu , highlightedEvent)
References c.
KVSO_CLASS_FUNCTION (popupMenu , insertItem)
References __tr2qs_ctx(), addActionToDict(), c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (popupMenu , addMenu)
References __tr2qs_ctx(), actionsDict, addActionToDict(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (popupMenu , removeItem)
References c, CHECK_INTERNAL_POINTER, getAction(), KVS_PT_INTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and removeAction().
KVSO_CLASS_FUNCTION (popupMenu , exec)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (popupMenu , setTitle)
References c, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (popupMenu , insertSeparator)
References c, CHECK_INTERNAL_POINTER, getAction(), KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (popupMenu , activatedEvent)
References c.
static void removeAction (int idx) [static]
References actionsDict.
Referenced by KviCustomToolBar::dragLeaveEvent(), KviCustomToolBar::dragMoveEvent(), KviCustomToolBar::eventFilter(), KVSO_CLASS_FUNCTION(), and KviMenuBar::removeMenu().
static void removeMenuAllActions (QMenu * pMenu) [static]
References actionsDict, and i.
Referenced by KvsObject_popupMenu::aboutToDie().
Variable Documentation
QHash<int,QAction*> actionsDict [static]
Referenced by addActionToDict(), getAction(), KVSO_CLASS_FUNCTION(), removeAction(), removeMenuAllActions(), KvsObject_popupMenu::slothovered(), and KvsObject_popupMenu::slottriggered().
int iIdentifier = 0 [static]
Referenced by addActionToDict().