KVIrc: src/modules/objects/KvsObject_sql.cpp File Reference
src/modules/objects/KvsObject_sql.cpp File Reference
#include "kvi_debug.h"
#include "KviMemory.h"
#include "KviLocale.h"
#include "KvsObject_sql.h"
#include <QtSql>
#include "KvsObject_memoryBuffer.h"
#include <stdlib.h>
#include <QHash>
Defines
#define CHECK_QUERY_IS_INIT
Functions
if (m_pCurrentSQlQuery) delete m_pCurrentSQlQuery
KVSO_CLASS_FUNCTION (sql, lastError)
KVSO_CLASS_FUNCTION (sql, queryRecord)
KVSO_CLASS_FUNCTION (sql, queryLast)
KVSO_CLASS_FUNCTION (sql, queryFirst)
KVSO_CLASS_FUNCTION (sql, queryResultsSize)
KVSO_CLASS_FUNCTION (sql, queryPrevious)
KVSO_CLASS_FUNCTION (sql, queryNext)
KVSO_CLASS_FUNCTION (sql, queryExec)
KVSO_CLASS_FUNCTION (sql, queryBindValue)
KVSO_CLASS_FUNCTION (sql, queryPrepare)
KVSO_CLASS_FUNCTION (sql, queryFinish)
KVSO_CLASS_FUNCTION (sql, tablesList)
KVSO_CLASS_FUNCTION (sql, closeConnection)
KVSO_CLASS_FUNCTION (sql, commit)
KVSO_CLASS_FUNCTION (sql, beginTransaction)
KVSO_CLASS_FUNCTION (sql, features)
KVSO_CLASS_FUNCTION (sql, queryLastInsertId)
KVSO_CLASS_FUNCTION (sql, connectionNames)
KVSO_CLASS_FUNCTION (sql, setConnection)
Variables
m_pCurrentSQlQuery = 0
Define Documentation
#define CHECK_QUERY_IS_INIT
Value:
if (!m_pCurrentSQlQuery)\
                        {\
                        c->error("No connection has been initialized!");\
                        return false;}
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
if (m_pCurrentSQlQuery)
KVSO_CLASS_FUNCTION (sql , lastError)
References c, CHECK_QUERY_IS_INIT, KVS_PF_OPTIONAL, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryRecord)
References KviKvsObjectClass::allocateInstance(), c, CHECK_QUERY_IS_INIT, KviKvsObject::handle(), i, KviKvsKernel::instance(), KviKvsObjectController::lookupClass(), m_pCurrentSQlQuery, KviKvsKernel::objectController(), and KviKvsVariant::type().
KVSO_CLASS_FUNCTION (sql , queryLast)
References c, CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryFirst)
References c, CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryResultsSize)
References c, CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryPrevious)
References c, CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryNext)
References c, CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryExec)
References c, CHECK_QUERY_IS_INIT, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryBindValue)
References __tr2qs_ctx(), KviKvsVariant::asBoolean(), KviKvsVariant::asHObject(), KviKvsVariant::asInteger(), KviKvsVariant::asReal(), KviKvsVariant::asString(), c, CHECK_QUERY_IS_INIT, KviKvsVariant::getTypeName(), i, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isBoolean(), KviKvsVariant::isHObject(), KviKvsVariant::isInteger(), KviKvsVariant::isNothing(), KviKvsVariant::isReal(), KviKvsVariant::isString(), KVS_PT_STRING, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pCurrentSQlQuery, KviKvsKernel::objectController(), and v.
KVSO_CLASS_FUNCTION (sql , queryPrepare)
References c, CHECK_QUERY_IS_INIT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , queryFinish)
References CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , tablesList)
References c, i, pArray, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (sql , closeConnection)
References __tr2qs_ctx(), c, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , commit)
References c.
KVSO_CLASS_FUNCTION (sql , beginTransaction)
References c.
KVSO_CLASS_FUNCTION (sql , features)
References __tr2qs_ctx(), c, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (sql , queryLastInsertId)
References c, CHECK_QUERY_IS_INIT, and m_pCurrentSQlQuery.
KVSO_CLASS_FUNCTION (sql , connectionNames)
References c, i, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, pArray, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (sql , setConnection)
References __tr2qs_ctx(), c, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pCurrentSQlQuery.
Variable Documentation
m_pCurrentSQlQuery = 0
Referenced by KVSO_CLASS_FUNCTION().