KVIrc: src/modules/objects/KvsObject_pixmap.cpp File Reference
KvsObject_pixmap.cpp File Reference
#include "KvsObject_pixmap.h"
#include "KvsObject_widget.h"
#include "KvsObject_memoryBuffer.h"
#include "KviAnimatedPixmap.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include <QFile>
Functions
emit aboutToDie ()
KVSO_CLASS_FUNCTION (pixmap, fill)
KVSO_CLASS_FUNCTION (pixmap, resize)
KVSO_CLASS_FUNCTION (pixmap, setPixel)
KVSO_CLASS_FUNCTION (pixmap, pixel)
KVSO_CLASS_FUNCTION (pixmap, rotate)
KVSO_CLASS_FUNCTION (pixmap, mirrored)
KVSO_CLASS_FUNCTION (pixmap, scale)
KVSO_CLASS_FUNCTION (pixmap, loadAnimation)
KVSO_CLASS_FUNCTION (pixmap, startAnimation)
KVSO_CLASS_FUNCTION (pixmap, stopAnimation)
KVSO_CLASS_FUNCTION (pixmap, load)
KVSO_CLASS_FUNCTION (pixmap, save)
KVSO_CLASS_FUNCTION (pixmap, loadFromMemoryBuffer)
KVSO_CLASS_FUNCTION (pixmap, grabWidget)
KVSO_CLASS_FUNCTION (pixmap, height)
KVSO_CLASS_FUNCTION (pixmap, width)
KVSO_CLASS_FUNCTION (pixmap, frameChangedEvent)
Variables
m_currentType = Image
m_pAnimatedPixmap = 0
m_pImage = 0
m_pPixmap = 0
Function Documentation
emit aboutToDie ()
Referenced by KvsObject_painter::attachDevice(), KvsObject_painter::detachDevice(), and KvsObject_popupMenu::init().
KVSO_CLASS_FUNCTION (pixmap , fill)
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), c, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_STRING, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pAnimatedPixmap, and m_pImage.
KVSO_CLASS_FUNCTION (pixmap , resize)
References c, KVS_PT_INTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pAnimatedPixmap, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , setPixel)
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), c, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_INTEGER, KVS_PT_STRING, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , pixel)
References __tr2qs_ctx(), c, KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pImage, m_pPixmap, pArray, KviKvsArray::set(), and KviKvsHash::set().
KVSO_CLASS_FUNCTION (pixmap , rotate)
References __tr2qs_ctx(), c, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_DOUBLE, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , mirrored)
References __tr2qs_ctx(), c, KVS_PT_BOOLEAN, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , scale)
References __tr2qs_ctx(), c, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pAnimatedPixmap, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , loadAnimation)
References __tr2qs_ctx(), c, connect(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_pAnimatedPixmap, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , startAnimation)
References c, m_pAnimatedPixmap, and Q_UNUSED().
KVSO_CLASS_FUNCTION (pixmap , stopAnimation)
References c, m_pAnimatedPixmap, and Q_UNUSED().
KVSO_CLASS_FUNCTION (pixmap , load)
References __tr2qs_ctx(), c, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, and m_pImage.
KVSO_CLASS_FUNCTION (pixmap , save)
References __tr2qs_ctx(), c, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_currentType, m_pAnimatedPixmap, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , loadFromMemoryBuffer)
References __tr2qs_ctx(), c, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pAnimatedPixmap, m_pPixmap, and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (pixmap , grabWidget)
References c, CHECK_HOBJECT_IS_WIDGET, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pAnimatedPixmap, m_pPixmap, and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (pixmap , height)
References c, m_currentType, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , width)
References c, m_currentType, m_pImage, and m_pPixmap.
KVSO_CLASS_FUNCTION (pixmap , frameChangedEvent)
References c.
Variable Documentation
m_currentType = Image
Referenced by KVSO_CLASS_FUNCTION().
delete m_pAnimatedPixmap = 0
Referenced by KviTextIcon::animatedPixmap(), and KVSO_CLASS_FUNCTION().
delete m_pImage = 0
Referenced by KVSO_CLASS_FUNCTION().
delete m_pPixmap = 0
Referenced by KviAvatar::animatedPixmap(), KviAvatar::isAnimated(), KviAvatar::isValid(), KVSO_CLASS_FUNCTION(), KviCachedPixmap::pixmap(), KviAvatar::pixmap(), and KviAvatar::size().