KVIrc: src/modules/objects/KvsObject_colorDialog.cpp File Reference
src/modules/objects/KvsObject_colorDialog.cpp File Reference
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KvsObject_colorDialog.h"
#include <QColorDialog>
#include "m_KvsObject_colorDialog.moc"
Defines
#define option_num (sizeof(option_tbl) / sizeof(option_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (colorDialog, setCurrentColor)
KVSO_CLASS_FUNCTION (colorDialog, colorSelectedEvent)
KVSO_CLASS_FUNCTION (colorDialog, currentColorChangedEvent)
KVSO_CLASS_FUNCTION (colorDialog, setOptions)
Variables
const int option_cod []
const char *const option_tbl []
Define Documentation
#define option_num (sizeof(option_tbl) / sizeof(option_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (colorDialog , setCurrentColor)
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_STRING, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (colorDialog , colorSelectedEvent)
References c.
KVSO_CLASS_FUNCTION (colorDialog , currentColorChangedEvent)
References c.
KVSO_CLASS_FUNCTION (colorDialog , setOptions)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, option_cod, option_num, and option_tbl.
Variable Documentation
const int option_cod[]
Initial value:
 {
        QColorDialog::ShowAlphaChannel,
        QColorDialog::NoButtons,
        QColorDialog::DontUseNativeDialog
}
Referenced by KVSO_CLASS_FUNCTION().
const char* const option_tbl[]
Initial value:
 {
        "ShowAlphaChannel",
        "NoButtons",
        "DontUseNativeDialog"
}
Referenced by KVSO_CLASS_FUNCTION().