KVIrc: src/modules/objects/KvsObject_treeWidgeteItem.cpp File Reference
KvsObject_treeWidgeteItem.cpp File Reference
#include "KvsObject_treeWidgeteItem.h"
#include "KvsObject_pixmap.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QIcon>
Macros
#define itemflags_num (sizeof(itemflags_tbl) / sizeof(itemflags_tbl[0]))
Functions
if (m_pTreeWidgetItem) delete m_pTreeWidgetItem
KVSO_CLASS_FUNCTION (treeWidgetItem, setText)
KVSO_CLASS_FUNCTION (treeWidgetItem, setItemEditable)
KVSO_CLASS_FUNCTION (treeWidgetItem, isItemEditable)
KVSO_CLASS_FUNCTION (treeWidgetItem, setFlags)
KVSO_CLASS_FUNCTION (treeWidgetItem, setEnabled)
KVSO_CLASS_FUNCTION (treeWidgetItem, isEnabled)
KVSO_CLASS_FUNCTION (treeWidgetItem, setOpen)
KVSO_CLASS_FUNCTION (treeWidgetItem, isOpen)
KVSO_CLASS_FUNCTION (treeWidgetItem, setChecked)
KVSO_CLASS_FUNCTION (treeWidgetItem, isChecked)
KVSO_CLASS_FUNCTION (treeWidgetItem, setCheckable)
KVSO_CLASS_FUNCTION (treeWidgetItem, isCheckable)
KVSO_CLASS_FUNCTION (treeWidgetItem, text)
KVSO_CLASS_FUNCTION (treeWidgetItem, setPixmap)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setPixmap)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setItemEditable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, isItemEditable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, isEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setOpen)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, isOpen)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setCheckable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, isCheckable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, isChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem, setFlags)
Variables
const int item_flags []
const char *const itemflags_tbl []
m_pTreeWidgetItem = nullptr
Macro Definition Documentation
#define itemflags_num (sizeof(itemflags_tbl) / sizeof(itemflags_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
if (m_pTreeWidgetItem)
KVSO_CLASS_FUNCTION (treeWidgetItem , setText)
References c, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setItemEditable)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , isItemEditable)
References c, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setFlags)
References __tr2qs_ctx(), c, KviQString::equalCI(), i, item_flags, itemflags_num, itemflags_tbl, j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setEnabled)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , isEnabled)
References c, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setOpen)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , isOpen)
References c, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setChecked)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , isChecked)
References c, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setCheckable)
References c, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , isCheckable)
References c, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , text)
References c, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pTreeWidgetItem.
KVSO_CLASS_FUNCTION (treeWidgetItem , setPixmap)
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsVariant::asString(), c, g_pIconManager, KviIconManager::getImage(), KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isEmpty(), KviKvsVariant::isHObject(), KVS_PT_UNSIGNEDINTEGER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pTreeWidgetItem, and KviKvsKernel::objectController().
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setPixmap)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setItemEditable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , isItemEditable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , isEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setOpen)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , isOpen)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setCheckable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , isCheckable)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , isChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_treeWidgetItem , setFlags)
Variable Documentation
const int item_flags[]
Initial value:
= {
        Qt::NoItemFlags,
        Qt::ItemIsSelectable,
        Qt::ItemIsEditable,
        Qt::ItemIsDragEnabled,
        Qt::ItemIsDropEnabled,
        Qt::ItemIsUserCheckable,
        Qt::ItemIsEnabled,
        Qt::ItemIsTristate
}
Referenced by KVSO_CLASS_FUNCTION().
const char* const itemflags_tbl[]
Initial value:
= {
        "noitemflag",
        "selectable",
        "editable",
        "dragEnabled",
        "dropEnabled",
        "userCheckable",
        "enabled",
        "tristate"
}
Referenced by KVSO_CLASS_FUNCTION().
m_pTreeWidgetItem = nullptr
Referenced by KVSO_CLASS_FUNCTION().