KVIrc: src/modules/objects/KvsObject_lineEdit.cpp File Reference
src/modules/objects/KvsObject_lineEdit.cpp File Reference
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KvsObject_lineEdit.h"
#include <QRegExpValidator>
#include <QLineEdit>
#include <QCompleter>
#include "m_KvsObject_lineEdit.moc"
Defines
#define mode_num (sizeof(mode_tbl) / sizeof(mode_tbl[0]))
Functions
if (m_pCompleter)
KVSO_CLASS_FUNCTION (lineEdit, textChangedEvent)
KVSO_CLASS_FUNCTION (lineEdit, lostFocusEvent)
KVSO_CLASS_FUNCTION (lineEdit, returnPressedEvent)
KVSO_CLASS_FUNCTION (lineEdit, unsetCompleter)
KVSO_CLASS_FUNCTION (lineEdit, disableCompleter)
KVSO_CLASS_FUNCTION (lineEdit, enableCompleter)
KVSO_CLASS_FUNCTION (lineEdit, setCompleter)
KVSO_CLASS_FUNCTION (lineEdit, setInputMask)
KVSO_CLASS_FUNCTION (lineEdit, setReadOnly)
KVSO_CLASS_FUNCTION (lineEdit, dragAndDrop)
KVSO_CLASS_FUNCTION (lineEdit, clear)
KVSO_CLASS_FUNCTION (lineEdit, setEchoMode)
KVSO_CLASS_FUNCTION (lineEdit, echoMode)
KVSO_CLASS_FUNCTION (lineEdit, paste)
KVSO_CLASS_FUNCTION (lineEdit, cut)
KVSO_CLASS_FUNCTION (lineEdit, copy)
KVSO_CLASS_FUNCTION (lineEdit, setSelection)
KVSO_CLASS_FUNCTION (lineEdit, selectAll)
KVSO_CLASS_FUNCTION (lineEdit, setCursorPosition)
KVSO_CLASS_FUNCTION (lineEdit, cursorPosition)
KVSO_CLASS_FUNCTION (lineEdit, setFrame)
KVSO_CLASS_FUNCTION (lineEdit, frame)
KVSO_CLASS_FUNCTION (lineEdit, setMaxLength)
KVSO_CLASS_FUNCTION (lineEdit, maxLength)
KVSO_CLASS_FUNCTION (lineEdit, setInputValidator)
KVSO_CLASS_FUNCTION (lineEdit, setText)
KVSO_CLASS_FUNCTION (lineEdit, text)
Variables
m_pCompleter = 0
static const int mode_cod []
static const char * mode_tbl []
Define Documentation
#define mode_num (sizeof(mode_tbl) / sizeof(mode_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
if (m_pCompleter)
References m_pCompleter.
KVSO_CLASS_FUNCTION (lineEdit , textChangedEvent)
References c.
KVSO_CLASS_FUNCTION (lineEdit , lostFocusEvent)
References c.
KVSO_CLASS_FUNCTION (lineEdit , returnPressedEvent)
References c.
KVSO_CLASS_FUNCTION (lineEdit , unsetCompleter)
References CHECK_INTERNAL_POINTER, and m_pCompleter.
KVSO_CLASS_FUNCTION (lineEdit , disableCompleter)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , enableCompleter)
References CHECK_INTERNAL_POINTER, and m_pCompleter.
KVSO_CLASS_FUNCTION (lineEdit , setCompleter)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pCompleter.
KVSO_CLASS_FUNCTION (lineEdit , setInputMask)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , setReadOnly)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , dragAndDrop)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , clear)
References CHECK_INTERNAL_POINTER, and clear().
KVSO_CLASS_FUNCTION (lineEdit , setEchoMode)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), i, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, mode_cod, mode_num, and mode_tbl.
KVSO_CLASS_FUNCTION (lineEdit , echoMode)
References c, CHECK_INTERNAL_POINTER, i, mode_cod, mode_num, and mode_tbl.
KVSO_CLASS_FUNCTION (lineEdit , paste)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , cut)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , copy)
References CHECK_INTERNAL_POINTER, and KviMemory::copy().
KVSO_CLASS_FUNCTION (lineEdit , setSelection)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , selectAll)
References CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , setCursorPosition)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , cursorPosition)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , setFrame)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , frame)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , setMaxLength)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , maxLength)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (lineEdit , setInputValidator)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , setText)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (lineEdit , text)
References c, and CHECK_INTERNAL_POINTER.
Variable Documentation
m_pCompleter = 0
Referenced by if(), and KVSO_CLASS_FUNCTION().
const int mode_cod[] [static]
Initial value:
  {
                QLineEdit::Normal,
                QLineEdit::NoEcho,
                QLineEdit::Password
                        }
Referenced by KVSO_CLASS_FUNCTION().
const char* mode_tbl[] [static]
Initial value:
 {
                        "Normal",
                        "NoEcho",
                        "Password"
                          }
Referenced by KVSO_CLASS_FUNCTION().