KVIrc: src/modules/objects/KvsObject_wizard.cpp File Reference
src/modules/objects/KvsObject_wizard.cpp File Reference
#include <KviTalWizard.h>
#include "KvsObject_wizard.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include <QPushButton>
#include "m_KvsObject_wizard.moc"
Functions
KVSO_CLASS_FUNCTION (wizard, addPage)
KVSO_CLASS_FUNCTION (wizard, backClickedEvent)
KVSO_CLASS_FUNCTION (wizard, setFinishEnabled)
KVSO_CLASS_FUNCTION (wizard, setHelpEnabled)
KVSO_CLASS_FUNCTION (wizard, setBackBtnText)
KVSO_CLASS_FUNCTION (wizard, setNextBtnText)
KVSO_CLASS_FUNCTION (wizard, setHelpBtnText)
KVSO_CLASS_FUNCTION (wizard, setFinishBtnText)
KVSO_CLASS_FUNCTION (wizard, nextClickedEvent)
KVSO_CLASS_FUNCTION (wizard, setNextEnabled)
KVSO_CLASS_FUNCTION (wizard, insertPage)
KVSO_CLASS_FUNCTION (wizard, setTitle)
KVSO_CLASS_FUNCTION (wizard, setBackEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, nextClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setBackBtnText)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setNextEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setBackEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setFinishEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setFinishBtnText)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setHelpEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, backClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setNextBtnText)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard, setHelpBtnText)
Function Documentation
KVSO_CLASS_FUNCTION (wizard , addPage)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (wizard , backClickedEvent)
References c.
KVSO_CLASS_FUNCTION (wizard , setFinishEnabled)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_BOOL, KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (wizard , setHelpEnabled)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_BOOL, KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (wizard , setBackBtnText)
References KviTalWizard::backButton(), c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (wizard , setNextBtnText)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviTalWizard::nextButton().
KVSO_CLASS_FUNCTION (wizard , setHelpBtnText)
References c, CHECK_INTERNAL_POINTER, KviTalWizard::helpButton(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (wizard , setFinishBtnText)
References c, CHECK_INTERNAL_POINTER, KviTalWizard::finishButton(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (wizard , nextClickedEvent)
References c.
KVSO_CLASS_FUNCTION (wizard , setNextEnabled)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_BOOL, KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (wizard , insertPage)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (wizard , setTitle)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (wizard , setBackEnabled)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_BOOL, KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , nextClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setBackBtnText)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setNextEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setBackEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setFinishEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setFinishBtnText)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setHelpEnabled)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , backClickedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setNextBtnText)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_wizard , setHelpBtnText)