KVIrc: src/modules/objects/KvsObject_file.cpp File Reference
src/modules/objects/KvsObject_file.cpp File Reference
#include "KvsObject_file.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviError.h"
#include "KviFile.h"
#include "KviFileUtils.h"
#include "KvsObject_memoryBuffer.h"
#include <QStringList>
#include <QTextStream>
Defines
#define CHECK_FILE_IS_OPEN
#define mod_num (sizeof(mod_tbl) / sizeof(mod_tbl[0]))
Functions
if (m_pFile) delete m_pFile
KVSO_CLASS_FUNCTION (file, writeHexBlock)
KVSO_CLASS_FUNCTION (file, readHexBlock)
KVSO_CLASS_FUNCTION (file, writeLine)
KVSO_CLASS_FUNCTION (file, readLine)
KVSO_CLASS_FUNCTION (file, writeBlock)
KVSO_CLASS_FUNCTION (file, write)
KVSO_CLASS_FUNCTION (file, read)
KVSO_CLASS_FUNCTION (file, readBlock)
KVSO_CLASS_FUNCTION (file, unGetch)
KVSO_CLASS_FUNCTION (file, readByte)
KVSO_CLASS_FUNCTION (file, getch)
KVSO_CLASS_FUNCTION (file, putch)
KVSO_CLASS_FUNCTION (file, resize)
KVSO_CLASS_FUNCTION (file, seek)
KVSO_CLASS_FUNCTION (file, where)
KVSO_CLASS_FUNCTION (file, atEnd)
KVSO_CLASS_FUNCTION (file, size)
KVSO_CLASS_FUNCTION (file, flush)
KVSO_CLASS_FUNCTION (file, close)
KVSO_CLASS_FUNCTION (file, isOpen)
KVSO_CLASS_FUNCTION (file, open)
KVSO_CLASS_FUNCTION (file, name)
KVSO_CLASS_FUNCTION (file, setName)
Variables
m_pFile = new KviFile()
const QIODevice::OpenMode mod_cod []
const char *const mod_tbl []
Define Documentation
#define CHECK_FILE_IS_OPEN
Value:
if (!m_pFile->isOpen())\
        {c->warning(__tr2qs_ctx("File is not open!","objects"));return true;}
Referenced by KVSO_CLASS_FUNCTION().
#define mod_num (sizeof(mod_tbl) / sizeof(mod_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
if (m_pFile)
Referenced by HelpIndex::query().
KVSO_CLASS_FUNCTION (file , writeHexBlock)
References __tr2qs_ctx(), c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, i, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , readHexBlock)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, i, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , writeLine)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , readLine)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , writeBlock)
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isHObject(), KviKvsVariant::isString(), KVS_PF_OPTIONAL, KVS_PT_UNSIGNEDINTEGER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pFile, and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (file , write)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , read)
References __tr2qs_ctx(), KviKvsVariant::array(), c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KviKvsVariant::hash(), KviKvsVariant::isArray(), KviKvsVariant::isHash(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_pFile, and KviKvsVariant::unserialize().
KVSO_CLASS_FUNCTION (file , readBlock)
References __tr2qs_ctx(), c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), m_pFile, and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (file , unGetch)
References __tr2qs_ctx(), c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , readByte)
References __tr2qs_ctx(), c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , getch)
References __tr2qs_ctx(), c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , putch)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , resize)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KVS_PT_INTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , seek)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and m_pFile.
KVSO_CLASS_FUNCTION (file , where)
References c, CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , atEnd)
References c, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , size)
References c, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , flush)
References CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , close)
References CHECK_FILE_IS_OPEN, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , isOpen)
References c, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , open)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, m_pFile, mod_cod, mod_num, and mod_tbl.
KVSO_CLASS_FUNCTION (file , name)
References c, CHECK_INTERNAL_POINTER, and m_pFile.
KVSO_CLASS_FUNCTION (file , setName)
References c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
Variable Documentation
m_pFile = new KviFile()
Referenced by KVSO_CLASS_FUNCTION().
const QIODevice::OpenMode mod_cod[]
Initial value:
 {
        QIODevice::Unbuffered,
        QIODevice::ReadOnly,
        QIODevice::WriteOnly,
        QIODevice::ReadWrite,
        QIODevice::Append,
        QIODevice::Truncate
}
Referenced by KVSO_CLASS_FUNCTION().
const char* const mod_tbl[]
Initial value:
 {
        "Raw",
        "ReadOnly",
        "WriteOnly",
        "ReadWrite",
        "Append",
        "Truncate"
}
Referenced by KVSO_CLASS_FUNCTION().