KVIrc: src/modules/objects/KvsObject_mainWindow.cpp File Reference
src/modules/objects/KvsObject_mainWindow.cpp File Reference
#include "KviTalMainWindow.h"
#include "KvsObject_mainWindow.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
Functions
KVSO_CLASS_FUNCTION (mainWindow, setCentralWidget)
Function Documentation
KVSO_CLASS_FUNCTION (mainWindow , setCentralWidget)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().