KVIrc: src/modules/objects/KvsObject_slider.cpp File Reference
src/modules/objects/KvsObject_slider.cpp File Reference
#include "KvsObject_slider.h"
#include "KviError.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QSlider>
#include "m_KvsObject_slider.moc"
Functions
KVSO_CLASS_FUNCTION (slider, setTracking)
KVSO_CLASS_FUNCTION (slider, setValue)
KVSO_CLASS_FUNCTION (slider, setMinValue)
KVSO_CLASS_FUNCTION (slider, setMaxValue)
KVSO_CLASS_FUNCTION (slider, pageStep)
KVSO_CLASS_FUNCTION (slider, setLineStep)
KVSO_CLASS_FUNCTION (slider, setPageStep)
KVSO_CLASS_FUNCTION (slider, setTickInterval)
KVSO_CLASS_FUNCTION (slider, value)
KVSO_CLASS_FUNCTION (slider, minValue)
KVSO_CLASS_FUNCTION (slider, maxValue)
KVSO_CLASS_FUNCTION (slider, lineStep)
KVSO_CLASS_FUNCTION (slider, setTickmarks)
KVSO_CLASS_FUNCTION (slider, setOrientation)
KVSO_CLASS_FUNCTION (slider, valueChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, value)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setTracking)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, maxValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, lineStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setMinValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setPageStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setOrientation)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, valueChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, minValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setLineStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, pageStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setTickInterval)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setMaxValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider, setTickmarks)
Function Documentation
KVSO_CLASS_FUNCTION (slider , setTracking)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , setValue)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , setMinValue)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , setMaxValue)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , pageStep)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (slider , setLineStep)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , setPageStep)
References c, CHECK_INTERNAL_POINTER, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , setTickInterval)
References c, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , value)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (slider , minValue)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (slider , maxValue)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (slider , lineStep)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (slider , setTickmarks)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , setOrientation)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (slider , valueChangedEvent)
References c.
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , value)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setTracking)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , maxValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , lineStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setMinValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setPageStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setOrientation)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , valueChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , minValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setLineStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , pageStep)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setTickInterval)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setMaxValue)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_slider , setTickmarks)