KVIrc: src/modules/objects/KvsObject_listWidget.cpp File Reference
src/modules/objects/KvsObject_listWidget.cpp File Reference
#include "KviError.h"
#include "KviLocale.h"
#include "kvi_debug.h"
#include "KvsObject_list.h"
#include "KvsObject_listWidget.h"
#include "KvsObject_pixmap.h"
#include "KviIconManager.h"
#include <QListWidget>
#include "m_KvsObject_listWidget.moc"
Defines
#define itemflags_num (sizeof(itemflags_tbl) / sizeof(itemflags_tbl[0]))
Functions
KVSO_CLASS_FUNCTION (listWidget, insertItem)
KVSO_CLASS_FUNCTION (listWidget, itemEnteredEvent)
KVSO_CLASS_FUNCTION (listWidget, setFlags)
KVSO_CLASS_FUNCTION (listWidget, currentItemChangedEvent)
KVSO_CLASS_FUNCTION (listWidget, setCurrentItem)
KVSO_CLASS_FUNCTION (listWidget, itemAt)
KVSO_CLASS_FUNCTION (listWidget, setSelectionMode)
KVSO_CLASS_FUNCTION (listWidget, selectionMode)
KVSO_CLASS_FUNCTION (listWidget, insertWidgetItem)
KVSO_CLASS_FUNCTION (listWidget, selectedItems)
KVSO_CLASS_FUNCTION (listWidget, setSelected)
KVSO_CLASS_FUNCTION (listWidget, isSelected)
KVSO_CLASS_FUNCTION (listWidget, setChecked)
KVSO_CLASS_FUNCTION (listWidget, textAt)
KVSO_CLASS_FUNCTION (listWidget, isChecked)
KVSO_CLASS_FUNCTION (listWidget, itemRect)
KVSO_CLASS_FUNCTION (listWidget, itemChangedEvent)
KVSO_CLASS_FUNCTION (listWidget, removeItem)
KVSO_CLASS_FUNCTION (listWidget, setFont)
KVSO_CLASS_FUNCTION (listWidget, setIcon)
KVSO_CLASS_FUNCTION (listWidget, setForeground)
KVSO_CLASS_FUNCTION (listWidget, clear)
KVSO_CLASS_FUNCTION (listWidget, changeItem)
KVSO_CLASS_FUNCTION (listWidget, count)
KVSO_CLASS_FUNCTION (listWidget, currentText)
KVSO_CLASS_FUNCTION (listWidget, currentItem)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, itemAt)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, textAt)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, itemChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, isChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setSelectionMode)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, itemRect)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setForeground)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, currentItemChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, selectedItems)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setCurrentItem)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setFont)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, isSelected)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, selectionMode)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, itemEnteredEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setIcon)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget, setSelected)
Variables
const int item_flags []
const char *const itemflags_tbl []
Define Documentation
#define itemflags_num (sizeof(itemflags_tbl) / sizeof(itemflags_tbl[0]))
Referenced by KVSO_CLASS_FUNCTION().
Function Documentation
KVSO_CLASS_FUNCTION (listWidget , insertItem)
References c, CHECK_INTERNAL_POINTER, KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , itemEnteredEvent)
References c.
KVSO_CLASS_FUNCTION (listWidget , setFlags)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), i, item_flags, itemflags_num, itemflags_tbl, j, KVS_PF_OPTIONAL, KVS_PT_STRINGLIST, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , currentItemChangedEvent)
References c.
KVSO_CLASS_FUNCTION (listWidget , setCurrentItem)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , itemAt)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , setSelectionMode)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PT_STRING, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , selectionMode)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (listWidget , insertWidgetItem)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_INT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), KviKvsObject::object(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (listWidget , selectedItems)
References c, CHECK_INTERNAL_POINTER, i, pArray, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (listWidget , setSelected)
References c, CHECK_INTERNAL_POINTER, KVS_PT_BOOLEAN, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , isSelected)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , setChecked)
References c, KVS_PT_BOOL, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , textAt)
References c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , isChecked)
References c, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , itemRect)
References a, c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, and KviKvsArray::set().
KVSO_CLASS_FUNCTION (listWidget , itemChangedEvent)
References c.
KVSO_CLASS_FUNCTION (listWidget , removeItem)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , setFont)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), i, KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVS_PT_STRINGLIST, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , setIcon)
References __tr2qs_ctx(), KviKvsVariant::asHObject(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, g_pIconManager, KviIconManager::getImage(), KviKvsObject::inheritsClass(), KviKvsKernel::instance(), KviKvsVariant::isEmpty(), KviKvsVariant::isHObject(), KVS_PT_UNSIGNEDINTEGER, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KVSO_CLASS_FUNCTION (listWidget , setForeground)
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), c, CHECK_INTERNAL_POINTER, KviQString::equalCI(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_INTEGER, KVS_PT_STRING, KVS_PT_VARIANT, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , clear)
References CHECK_INTERNAL_POINTER, and clear().
KVSO_CLASS_FUNCTION (listWidget , changeItem)
References __tr2qs_ctx(), c, CHECK_INTERNAL_POINTER, KVS_PT_STRING, KVS_PT_UNSIGNEDINTEGER, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, and KVSO_PARAMETERS_END.
KVSO_CLASS_FUNCTION (listWidget , count)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (listWidget , currentText)
References c, and CHECK_INTERNAL_POINTER.
KVSO_CLASS_FUNCTION (listWidget , currentItem)
References c, and CHECK_INTERNAL_POINTER.
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , itemAt)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , textAt)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , itemChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , isChecked)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setSelectionMode)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , itemRect)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setForeground)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , currentItemChangedEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , selectedItems)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setCurrentItem)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setFont)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , isSelected)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , selectionMode)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , itemEnteredEvent)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setIcon)
KVSO_REGISTER_HANDLER_BY_NAME (KvsObject_listWidget , setSelected)
Variable Documentation
const int item_flags[]
Initial value:
 {
        Qt::NoItemFlags,
        Qt::ItemIsSelectable,
        Qt::ItemIsEditable,
        Qt::ItemIsDragEnabled,
        Qt::ItemIsDropEnabled,
        Qt::ItemIsUserCheckable,
        Qt::ItemIsEnabled,
        Qt::ItemIsTristate
}
Referenced by KVSO_CLASS_FUNCTION().
const char* const itemflags_tbl[]
Initial value:
 {
        "noitemflag",
        "selectable",
        "editable",
        "dragEnabled",
        "dropEnabled",
        "userCheckable",
        "enabled",
        "tristate"
}
Referenced by KVSO_CLASS_FUNCTION().