KVIrc: src/modules/toolbar/libkvitoolbar.cpp File Reference
src/modules/toolbar/libkvitoolbar.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviWindow.h"
#include "KviApplication.h"
#include "KviError.h"
#include "KviCommandFormatter.h"
#include "KviCustomToolBar.h"
#include "KviCustomToolBarDescriptor.h"
#include "KviCustomToolBarManager.h"
#include "KviActionManager.h"
#include "KviKvsUserAction.h"
Functions
static bool toolbar_kvs_cmd_additem (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_cmd_clear (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_cmd_create (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_cmd_destroy (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_cmd_hide (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_cmd_removeitem (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_cmd_show (KviKvsModuleCommandCall *c)
static bool toolbar_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool toolbar_kvs_fnc_isVisible (KviKvsModuleFunctionCall *c)
static bool toolbar_kvs_fnc_items (KviKvsModuleFunctionCall *c)
static bool toolbar_kvs_fnc_list (KviKvsModuleFunctionCall *c)
static bool toolbar_module_cleanup (KviModule *)
static bool toolbar_module_init (KviModule *m)
Function Documentation
static bool toolbar_kvs_cmd_additem (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviCustomToolBarDescriptor::addAction(), d, KviKvsSwitchList::find(), KviCustomToolBarManager::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_cmd_clear (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviCustomToolBarDescriptor::clear(), d, KviKvsSwitchList::find(), KviCustomToolBarManager::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_cmd_create (KviKvsModuleCommandCall * c) [static]
References KviCustomToolBarDescriptor::clear(), KviCustomToolBarManager::create(), d, KviKvsSwitchList::find(), KviCustomToolBarManager::find(), KviCustomToolBarManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviCustomToolBarDescriptor::rename(), KviCustomToolBarDescriptor::setIconId(), and KviKvsModuleCommandCall::switches().
Referenced by toolbar_module_init().
static bool toolbar_kvs_cmd_destroy (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviKvsSwitchList::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_cmd_hide (KviKvsModuleCommandCall * c) [static]
References __tr2qs, d, KviCustomToolBarManager::destroyDescriptor(), KviKvsSwitchList::find(), KviCustomToolBarManager::find(), KviCustomToolBarDescriptor::id(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), KviCustomToolBarDescriptor::toolBar(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_cmd_removeitem (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviKvsVariant::asInteger(), KviKvsVariant::asString(), d, KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviCustomToolBarManager::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviCustomToolBarDescriptor::removeAction(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_cmd_show (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviCustomToolBarDescriptor::createToolBar(), d, KviKvsSwitchList::find(), KviCustomToolBarManager::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), KviCustomToolBarDescriptor::toolBar(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_fnc_exists (KviKvsModuleFunctionCall * c) [static]
References KviQString::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by toolbar_module_init().
static bool toolbar_kvs_fnc_isVisible (KviKvsModuleFunctionCall * c) [static]
References d, KviCustomToolBarManager::find(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviCustomToolBarDescriptor::toolBar().
Referenced by toolbar_module_init().
static bool toolbar_kvs_fnc_items (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, a, KviCustomToolBarDescriptor::actions(), d, KviCustomToolBarManager::find(), KviPointerList< T >::first(), KviCustomToolBarManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviPointerList< T >::next(), KviKvsModuleFunctionCall::returnValue(), s, KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by toolbar_module_init().
static bool toolbar_kvs_fnc_list (KviKvsModuleFunctionCall * c) [static]
References a, KviPointerHashTableIterator< Key, T >::current(), d, KviCustomToolBarManager::instance(), KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by toolbar_module_init().
static bool toolbar_module_cleanup (KviModule *) [static]
static bool toolbar_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, toolbar_kvs_cmd_additem(), toolbar_kvs_cmd_clear(), toolbar_kvs_cmd_create(), toolbar_kvs_cmd_destroy(), toolbar_kvs_cmd_hide(), toolbar_kvs_cmd_removeitem(), toolbar_kvs_cmd_show(), toolbar_kvs_fnc_exists(), toolbar_kvs_fnc_isVisible(), toolbar_kvs_fnc_items(), and toolbar_kvs_fnc_list().