KVIrc: src/modules/addon/libkviaddon.cpp File Reference
src/modules/addon/libkviaddon.cpp File Reference
#include "AddonManagementDialog.h"
#include "AddonFunctions.h"
#include "KviModule.h"
#include "KviKvsScriptAddonManager.h"
#include "KviLocale.h"
#include "KviQString.h"
#include "KviParameterList.h"
#include "KviCommandFormatter.h"
#include "KviError.h"
#include "kvi_out.h"
#include "KviIconManager.h"
#include "KviControlCodes.h"
#include "KviConfigurationFile.h"
#include "kvi_sourcesdate.h"
#include "KviMiscUtils.h"
#include "KviFileUtils.h"
#include "KviFileDialog.h"
#include <QFileInfo>
Functions
static bool addon_kvs_cmd_configure (KviKvsModuleCommandCall *c)
static bool addon_kvs_cmd_dialog (KviKvsModuleCommandCall *c)
static bool addon_kvs_cmd_help (KviKvsModuleCommandCall *c)
static bool addon_kvs_cmd_install (KviKvsModuleCommandCall *c)
static bool addon_kvs_cmd_installfiles (KviKvsModuleCommandCall *c)
static bool addon_kvs_cmd_list (KviKvsModuleCommandCall *c)
static bool addon_kvs_cmd_register (KviKvsModuleCallbackCommandCall *c)
static bool addon_kvs_cmd_setconfigurecallback (KviKvsModuleCallbackCommandCall *c)
static bool addon_kvs_cmd_sethelpcallback (KviKvsModuleCallbackCommandCall *c)
static bool addon_kvs_cmd_uninstall (KviKvsModuleCommandCall *c)
static bool addon_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool addon_kvs_fnc_version (KviKvsModuleFunctionCall *c)
static bool addon_module_can_unload (KviModule *)
static bool addon_module_cleanup (KviModule *m)
static bool addon_module_init (KviModule *m)
QRect g_rectManagementDialogGeometry (0, 0, 0, 0)
Function Documentation
static bool addon_kvs_cmd_configure (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsScriptAddon::configureCallbackCode(), KviKvsScriptAddon::executeConfigureCallback(), KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddonManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by addon_module_init().
static bool addon_kvs_cmd_dialog (KviKvsModuleCommandCall * c) [static]
References AddonManagementDialog::display(), and KviKvsModuleCommandCall::hasSwitch().
Referenced by addon_module_init().
static bool addon_kvs_cmd_help (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsScriptAddon::executeHelpCallback(), KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddon::helpCallbackCode(), KviKvsScriptAddonManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by addon_module_init().
static bool addon_kvs_cmd_install (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), AddonFunctions::installAddonPackage(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by addon_module_init().
static bool addon_kvs_cmd_installfiles (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsScriptAddon::addInstalledFile(), KviFileUtils::adjustFilePath(), KviFileUtils::copyFile(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), g_pApp, KviApplication::getLocalKvircDirectory(), Hidden, KviKvsScriptAddonManager::instance(), KVI_OUT_SYSTEMMESSAGE, KVI_PATH_SEPARATOR_CHAR, KVS_PT_NONEMPTYSTRING, KVS_PT_STRINGLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviFileUtils::makeDir(), KviApplication::None, KviWindow::output(), KviKvsModuleCommandCall::switches(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by addon_module_init().
static bool addon_kvs_cmd_list (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsScriptAddonManager::addonDict(), KviControlCodes::Bold, KviPointerHashTableIterator< Key, T >::current(), KviKvsScriptAddonManager::instance(), KVI_OUT_SYSTEMMESSAGE, KviWindow::output(), and KviKvsRunTimeCall::window().
Referenced by addon_module_init().
static bool addon_kvs_cmd_register (KviKvsModuleCallbackCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviMiscUtils::compareVersions(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), KviKvsModuleCallbackCommandCall::getParameterCode(), KviKvsScriptAddonManager::instance(), KviMiscUtils::isValidVersionString(), KVI_OUT_SYSTEMMESSAGE, KVI_SOURCES_DATE, KVI_VERSION, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETER_IGNORED, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::output(), KviKvsScriptAddonManager::registerAddon(), KviKvsModuleCommandCall::switches(), KviKvsScriptAddonRegistrationData::szDescriptionScript, KviKvsScriptAddonRegistrationData::szIconId, KviKvsScriptAddonRegistrationData::szName, KviKvsScriptAddonRegistrationData::szUninstallCallbackScript, KviKvsScriptAddonRegistrationData::szVersion, KviKvsScriptAddonRegistrationData::szVisibleNameScript, KviKvsScriptAddonManager::unregisterAddon(), KviKvsScriptAddon::version(), and KviKvsRunTimeCall::window().
Referenced by addon_module_init().
static bool addon_kvs_cmd_setconfigurecallback (KviKvsModuleCallbackCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddonManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsScriptAddon::setConfigureCallback(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by addon_module_init().
static bool addon_kvs_cmd_sethelpcallback (KviKvsModuleCallbackCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddonManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsScriptAddon::setHelpCallback(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by addon_module_init().
static bool addon_kvs_cmd_uninstall (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), a, KviKvsSwitchList::find(), KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddonManager::instance(), KVI_OUT_SYSTEMMESSAGE, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::output(), KviKvsModuleCommandCall::switches(), KviKvsScriptAddonManager::unregisterAddon(), KviKvsScriptAddon::version(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by addon_module_init().
static bool addon_kvs_fnc_exists (KviKvsModuleFunctionCall * c) [static]
References a, KviMiscUtils::compareVersions(), KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddonManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviKvsScriptAddon::version().
Referenced by addon_module_init().
static bool addon_kvs_fnc_version (KviKvsModuleFunctionCall * c) [static]
References a, KviKvsScriptAddonManager::findAddon(), KviKvsScriptAddonManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), KviKvsVariant::setString(), and KviKvsScriptAddon::version().
Referenced by addon_module_init().
static bool addon_module_can_unload (KviModule *) [static]
References AddonManagementDialog::instance().
static bool addon_module_cleanup (KviModule * m) [static]
References AddonManagementDialog::cleanup(), g_rectManagementDialogGeometry, KviModule::getDefaultConfigFileName(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
static bool addon_module_init (KviModule * m) [static]
References addon_kvs_cmd_configure(), addon_kvs_cmd_dialog(), addon_kvs_cmd_help(), addon_kvs_cmd_install(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_list(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), addon_kvs_fnc_exists(), addon_kvs_fnc_version(), g_rectManagementDialogGeometry, KviModule::getDefaultConfigFileName(), KVSM_REGISTER_CALLBACK_COMMAND, KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, KviConfigurationFile::Read, and KviConfigurationFile::readRectEntry().
QRect g_rectManagementDialogGeometry (0 , 0 , 0 , 0)