KVIrc: src/modules/popup/libkvipopup.cpp File Reference
src/modules/popup/libkvipopup.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviKvsPopupManager.h"
Defines
#define GET_KVS_POPUP(LOCKING_CHECK)
#define GET_KVS_POPUP_FNC
Functions
static bool popup_kvs_cmd_addEpilogue (KviKvsModuleCallbackCommandCall *c)
static bool popup_kvs_cmd_addExtPopup (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_addItem (KviKvsModuleCallbackCommandCall *c)
static bool popup_kvs_cmd_addLabel (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_addPrologue (KviKvsModuleCallbackCommandCall *c)
static bool popup_kvs_cmd_addSeparator (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_addSubPopup (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_clear (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_create (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_delItem (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_destroy (KviKvsModuleCommandCall *c)
static bool popup_kvs_cmd_show (KviKvsModuleCommandCall *c)
static bool popup_kvs_fnc_currentItemId (KviKvsModuleFunctionCall *c)
static bool popup_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool popup_kvs_fnc_isEmpty (KviKvsModuleFunctionCall *c)
static bool popup_module_can_unload (KviModule *)
static bool popup_module_cleanup (KviModule *)
static bool popup_module_init (KviModule *m)
Define Documentation
#define GET_KVS_POPUP (LOCKING_CHECK)
Referenced by popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addExtPopup(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addLabel(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_addSeparator(), popup_kvs_cmd_addSubPopup(), popup_kvs_cmd_clear(), and popup_kvs_cmd_delItem().
#define GET_KVS_POPUP_FNC
Referenced by popup_kvs_fnc_isEmpty().
Function Documentation
static bool popup_kvs_cmd_addEpilogue (KviKvsModuleCallbackCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsModuleCommandCall::hasSwitch(), KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_cmd_addExtPopup (KviKvsModuleCommandCall * c) [static]
References KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by popup_module_init().
static bool popup_kvs_cmd_addItem (KviKvsModuleCallbackCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsModuleCommandCall::hasSwitch(), KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_cmd_addLabel (KviKvsModuleCommandCall * c) [static]
References KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by popup_module_init().
static bool popup_kvs_cmd_addPrologue (KviKvsModuleCallbackCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsModuleCommandCall::hasSwitch(), KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_cmd_addSeparator (KviKvsModuleCommandCall * c) [static]
References KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by popup_module_init().
static bool popup_kvs_cmd_addSubPopup (KviKvsModuleCommandCall * c) [static]
References KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by popup_module_init().
static bool popup_kvs_cmd_clear (KviKvsModuleCommandCall * c) [static]
References KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsPopupManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by popup_module_init().
static bool popup_kvs_cmd_create (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsPopupManager::add(), KviKvsPopupManager::emitRefresh(), KviKvsModuleCommandCall::hasSwitch(), KviKvsPopupManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_cmd_delItem (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsPopupManager::emitRefresh(), GET_KVS_POPUP, KviKvsModuleCommandCall::hasSwitch(), KviKvsPopupManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_cmd_destroy (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsPopupManager::emitRefresh(), KviKvsModuleCommandCall::hasSwitch(), KviKvsPopupManager::instance(), KviKvsPopupMenu::isSoftLocked(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsPopupManager::lookup(), KviKvsPopupManager::remove(), and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_cmd_show (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsVariantList::append(), KviKvsVariant::asString(), KviKvsPopupMenu::doPopup(), KviKvsRunTimeCall::error(), KviKvsVariantList::first(), KviKvsModuleCommandCall::getSwitch(), KviKvsPopupManager::instance(), KviKvsPopupMenu::isSoftLocked(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsPopupManager::lookup(), KviKvsVariantList::next(), KviKvsRunTimeCall::params(), szX, v, KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by popup_module_init().
static bool popup_kvs_fnc_currentItemId (KviKvsModuleFunctionCall * c) [static]
References KviKvsRunTimeCall::context(), KviKvsRunTimeContext::popupId(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Referenced by popup_module_init().
static bool popup_kvs_fnc_exists (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviKvsPopupMenu::findChildPopupByName(), KviKvsPopupManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsPopupManager::lookup(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviKvsRunTimeCall::warning().
Referenced by popup_module_init().
static bool popup_kvs_fnc_isEmpty (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_POPUP_FNC, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by popup_module_init().
static bool popup_module_can_unload (KviModule *) [static]
static bool popup_module_cleanup (KviModule *) [static]
static bool popup_module_init (KviModule * m) [static]
References KVSM_REGISTER_CALLBACK_COMMAND, KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addExtPopup(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addLabel(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_addSeparator(), popup_kvs_cmd_addSubPopup(), popup_kvs_cmd_clear(), popup_kvs_cmd_create(), popup_kvs_cmd_delItem(), popup_kvs_cmd_destroy(), popup_kvs_cmd_show(), popup_kvs_fnc_currentItemId(), popup_kvs_fnc_exists(), and popup_kvs_fnc_isEmpty().