KVIrc: src/modules/raweditor/libkviraweditor.cpp File Reference
src/modules/raweditor/libkviraweditor.cpp File Reference
#include "RawEditorWindow.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
Functions
static bool raweditor_kvs_cmd_open (KviKvsModuleCommandCall *)
static bool raweditor_module_can_unload (KviModule *)
static bool raweditor_module_cleanup (KviModule *)
static bool raweditor_module_init (KviModule *m)
Variables
RawEditorWindow * g_pRawEditorWindow = 0
Function Documentation
static bool raweditor_kvs_cmd_open (KviKvsModuleCommandCall *) [static]
References KviMainWindow::addWindow(), and g_pMainWindow.
Referenced by raweditor_module_init().
static bool raweditor_module_can_unload (KviModule *) [static]
static bool raweditor_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool raweditor_module_init (KviModule * m) [static]
References KVSM_REGISTER_SIMPLE_COMMAND, and raweditor_kvs_cmd_open().
Variable Documentation
RawEditorWindow* g_pRawEditorWindow = 0