KVIrc: src/modules/python/libkvipython.cpp File Reference
src/modules/python/libkvipython.cpp File Reference
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviModuleManager.h"
#include "KviLocale.h"
Defines
#define KVS_CHECK_MODULE_STATE(_m, _c)
#define KVS_CHECK_PYTHONCORE(_m, _c)
Functions
static bool python_kvs_cmd_begin (KviKvsModuleCommandCall *c)
static bool python_kvs_cmd_destroy (KviKvsModuleCommandCall *c)
static bool python_kvs_fnc_isAvailable (KviKvsModuleFunctionCall *c)
static bool python_module_cleanup (KviModule *)
static bool python_module_init (KviModule *m)
Variables
static KviModule * g_pPythonCoreModule = 0
Define Documentation
#define KVS_CHECK_MODULE_STATE (_m, _c)
Value:
if(!_c->switches()->find('q',"quiet")) \
                        _c->warning(__tr2qs_ctx("This KVIrc executable has been compiled without python scripting support","python")); \
                return true;
Referenced by python_kvs_cmd_begin(), and python_kvs_cmd_destroy().
#define KVS_CHECK_PYTHONCORE (_m, _c)
Function Documentation
static bool python_kvs_cmd_begin (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::context(), KviModule::ctrl(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviKvsVariantList::first(), KVI_PYTHONCORECTRLCOMMAND_EXECUTE, KVS_CHECK_MODULE_STATE, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviKvsVariantList::next(), KviKvsRunTimeContext::returnValue(), KviKvsVariant::setString(), KviKvsModuleCommandCall::switches(), _KviPythonCoreCtrlCommand_execute::uSize, v, and KviKvsRunTimeCall::warning().
Referenced by python_module_init().
static bool python_kvs_cmd_destroy (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviModule::ctrl(), KviKvsSwitchList::find(), KVI_PYTHONCORECTRLCOMMAND_DESTROY, KVS_CHECK_MODULE_STATE, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviKvsModuleCommandCall::switches(), _KviPythonCoreCtrlCommand_destroy::uSize, and KviKvsRunTimeCall::warning().
Referenced by python_module_init().
static bool python_kvs_fnc_isAvailable (KviKvsModuleFunctionCall * c) [static]
References g_pModuleManager, KviModuleManager::getModule(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by python_module_init().
static bool python_module_cleanup (KviModule *) [static]
static bool python_module_init (KviModule * m) [static]
References g_pModuleManager, KviModuleManager::getModule(), KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, python_kvs_cmd_begin(), python_kvs_cmd_destroy(), and python_kvs_fnc_isAvailable().
Variable Documentation
KviModule* g_pPythonCoreModule = 0 [static]