KVIrc: src/modules/filetransferwindow/libkvifiletransferwindow.cpp File Reference
src/modules/filetransferwindow/libkvifiletransferwindow.cpp File Reference
#include "FileTransferWindow.h"
#include "KviModule.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QSplitter>
Functions
static KviModuleExtension * filetransferwindow_extension_alloc (KviModuleExtensionAllocStruct *s)
static bool filetransferwindow_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool filetransferwindow_module_can_unload (KviModule *)
static bool filetransferwindow_module_cleanup (KviModule *)
static bool filetransferwindow_module_init (KviModule *m)
Variables
FileTransferWindow * g_pFileTransferWindow = 0
Function Documentation
static KviModuleExtension* filetransferwindow_extension_alloc (KviModuleExtensionAllocStruct * s) [static]
References KviMainWindow::addWindow(), KviWindow::delayedAutoRaise(), KviPointerHashTable< Key, T >::find(), g_pFileTransferWindow, g_pMainWindow, KviWindow::minimize(), _KviModuleExtensionAllocStructTag::pDescriptor, _KviModuleExtensionAllocStructTag::pParams, and v.
Referenced by filetransferwindow_module_init().
static bool filetransferwindow_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References __tr, KviModuleExtensionDescriptor::allocate(), d, KviModule::findExtensionDescriptor(), KviKvsModuleCommandCall::hasSwitch(), KVI_FILE_TRANSFER_WINDOW_EXTENSION_NAME, KviKvsModuleRunTimeCall::module(), KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by filetransferwindow_module_init().
static bool filetransferwindow_module_can_unload (KviModule *) [static]
static bool filetransferwindow_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool filetransferwindow_module_init (KviModule * m) [static]
References __tr2qs, d, KviIconManager::FileTransfer, filetransferwindow_extension_alloc(), filetransferwindow_kvs_cmd_open(), g_pIconManager, KviIconManager::getSmallIcon(), KVI_FILE_TRANSFER_WINDOW_EXTENSION_NAME, KVSM_REGISTER_SIMPLE_COMMAND, KviModule::registerExtension(), and KviModuleExtensionDescriptor::setIcon().
Variable Documentation
FileTransferWindow* g_pFileTransferWindow = 0
Referenced by filetransferwindow_extension_alloc().