KVIrc: src/modules/classeditor/libkviclasseditor.cpp File Reference
src/modules/classeditor/libkviclasseditor.cpp File Reference
#include "ClassEditorWindow.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
Functions
static bool classeditor_kvs_cmd_open (KviKvsModuleCommandCall *)
static bool classeditor_module_can_unload (KviModule *)
static bool classeditor_module_cleanup (KviModule *)
static bool classeditor_module_init (KviModule *m)
Variables
KviModule * g_pClassEditorModule = 0
ClassEditorWindow * g_pClassEditorWindow = 0
Function Documentation
static bool classeditor_kvs_cmd_open (KviKvsModuleCommandCall *) [static]
References KviMainWindow::addWindow(), and g_pMainWindow.
Referenced by classeditor_module_init().
static bool classeditor_module_can_unload (KviModule *) [static]
static bool classeditor_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool classeditor_module_init (KviModule * m) [static]
References classeditor_kvs_cmd_open(), KVSM_REGISTER_SIMPLE_COMMAND, and m.
Variable Documentation
KviModule* g_pClassEditorModule = 0
ClassEditorWindow* g_pClassEditorWindow = 0