KVIrc: src/modules/toolbareditor/libkvitoolbareditor.cpp File Reference
src/modules/toolbareditor/libkvitoolbareditor.cpp File Reference
#include "CustomizeToolBarsDialog.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
#include "KviActionManager.h"
#include "KviConfigurationFile.h"
#include "KviApplication.h"
Functions
QRect g_rectToolBarEditorDialogGeometry (0, 0, 0, 0)
static bool toolbareditor_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool toolbareditor_module_can_unload (KviModule *)
static bool toolbareditor_module_cleanup (KviModule *m)
static bool toolbareditor_module_init (KviModule *m)
Function Documentation
QRect g_rectToolBarEditorDialogGeometry (0 , 0 , 0 , 0)
static bool toolbareditor_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References CustomizeToolBarsDialog::display(), and KviKvsModuleCommandCall::hasSwitch().
Referenced by toolbareditor_module_init().
static bool toolbareditor_module_can_unload (KviModule *) [static]
References CustomizeToolBarsDialog::instance().
static bool toolbareditor_module_cleanup (KviModule * m) [static]
References CustomizeToolBarsDialog::cleanup(), g_rectToolBarEditorDialogGeometry, KviModule::getDefaultConfigFileName(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
static bool toolbareditor_module_init (KviModule * m) [static]
References g_rectToolBarEditorDialogGeometry, KviModule::getDefaultConfigFileName(), KVSM_REGISTER_SIMPLE_COMMAND, KviConfigurationFile::Read, KviConfigurationFile::readRectEntry(), and toolbareditor_kvs_cmd_open().