KVIrc: src/modules/upnp/libkviupnp.cpp File Reference
libkviupnp.cpp File Reference
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviCString.h"
#include "KviNetUtils.h"
#include "Manager.h"
Functions
static bool upnp_kvs_cmd_addPortMapping (KviKvsModuleCommandCall *c)
static bool upnp_kvs_cmd_delPortMapping (KviKvsModuleCommandCall *c)
static bool upnp_kvs_cmd_refresh (KviKvsModuleCommandCall *)
static bool upnp_kvs_fnc_getExternalIpAddress (KviKvsModuleFunctionCall *c)
static bool upnp_kvs_fnc_isGatewayAvailable (KviKvsModuleFunctionCall *c)
static bool upnp_module_can_unload (KviModule *)
static bool upnp_module_cleanup (KviModule *)
static bool upnp_module_init (KviModule *m)
Variables
UPnP::Manager * g_pManager = nullptr
Function Documentation
static bool upnp_kvs_cmd_addPortMapping (KviKvsModuleCommandCall * c) static
References UPnP::Manager::addPortMapping(), KviKvsVariant::asString(), KviKvsSwitchList::find(), kvi_getLocalHostAddress(), KVS_PT_INT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsModuleCommandCall::switches().
Referenced by upnp_module_init().
static bool upnp_kvs_cmd_delPortMapping (KviKvsModuleCommandCall * c) static
References UPnP::Manager::deletePortMapping(), KVS_PT_INT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by upnp_module_init().
static bool upnp_kvs_cmd_refresh (KviKvsModuleCommandCall *) static
References g_pManager, and UPnP::Manager::instance().
Referenced by upnp_module_init().
static bool upnp_kvs_fnc_getExternalIpAddress (KviKvsModuleFunctionCall * c) static
References UPnP::Manager::getExternalIpAddress(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by upnp_module_init().
static bool upnp_kvs_fnc_isGatewayAvailable (KviKvsModuleFunctionCall * c) static
References UPnP::Manager::isGatewayAvailable(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by upnp_module_init().
static bool upnp_module_can_unload (KviModule *) static
References UPnP::Manager::isGatewayAvailable().
static bool upnp_module_cleanup (KviModule *) static
References g_pManager.
static bool upnp_module_init (KviModule * m) static
References g_pManager, UPnP::Manager::instance(), KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, upnp_kvs_cmd_addPortMapping(), upnp_kvs_cmd_delPortMapping(), upnp_kvs_cmd_refresh(), upnp_kvs_fnc_getExternalIpAddress(), and upnp_kvs_fnc_isGatewayAvailable().
Variable Documentation
UPnP::Manager* g_pManager = nullptr
Referenced by upnp_kvs_cmd_refresh(), upnp_module_cleanup(), and upnp_module_init().