KVIrc: src/modules/perlcore/libkviperlcore.cpp File Reference
src/modules/perlcore/libkviperlcore.cpp File Reference
#include "KviModule.h"
#include "kvi_settings.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviWindow.h"
#include "KviApplication.h"
#include "KviKvsScript.h"
#include "KviKvsVariant.h"
#include "KviUserInput.h"
#include "KviPointerHashTable.h"
#include <QByteArray>
Functions
static bool perlcore_module_can_unload (KviModule *)
static bool perlcore_module_cleanup (KviModule *)
static bool perlcore_module_ctrl (KviModule *, const char *cmd, void *param)
static bool perlcore_module_init (KviModule *)
Function Documentation
static bool perlcore_module_can_unload (KviModule *) [static]
References KviPointerHashTable< Key, T >::count().
static bool perlcore_module_cleanup (KviModule *) [static]
static bool perlcore_module_ctrl (KviModule * , const char * cmd, void * param) [static]
References _KviPerlCoreCtrlCommand_execute::bExitOk, _KviPerlCoreCtrlCommand_execute::bQuiet, KVI_PERLCORECTRLCOMMAND_DESTROY, KVI_PERLCORECTRLCOMMAND_EXECUTE, kvi_strEqualCS(), _KviPerlCoreCtrlCommand_execute::lArgs, _KviPerlCoreCtrlCommand_execute::lWarnings, m, _KviPerlCoreCtrlCommand_execute::pKvsContext, _KviPerlCoreCtrlCommand_execute::szCode, _KviPerlCoreCtrlCommand_destroy::szContext, _KviPerlCoreCtrlCommand_execute::szContext, _KviPerlCoreCtrlCommand_execute::szError, _KviPerlCoreCtrlCommand_execute::szRetVal, _KviPerlCoreCtrlCommand_destroy::uSize, and _KviPerlCoreCtrlCommand_execute::uSize.
static bool perlcore_module_init (KviModule *) [static]
References NULL, and KviPointerHashTable< Key, T >::setAutoDelete().