KVIrc: src/modules/links/libkvilinks.cpp File Reference
src/modules/links/libkvilinks.cpp File Reference
#include "LinksWindow.h"
#include "KviModule.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include <QSplitter>
Functions
static bool links_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool links_module_can_unload (KviModule *)
static bool links_module_cleanup (KviModule *)
static bool links_module_init (KviModule *m)
Variables
KviPointerList< LinksWindow > * g_pLinksWindowList = 0
Function Documentation
static bool links_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviMainWindow::addWindow(), KviWindow::console(), KviKvsRunTimeCall::context(), KviWindow::context(), KviKvsRunTimeContext::errorNoIrcContext(), KviWindow::frame(), KviIrcContext::linksWindow(), w, KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by links_module_init().
static bool links_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool links_module_cleanup (KviModule *) [static]
References LinksWindow::die(), KviPointerList< T >::first(), and g_pLinksWindowList.
static bool links_module_init (KviModule * m) [static]
References KVSM_REGISTER_SIMPLE_COMMAND, links_kvs_cmd_open(), and KviPointerList< T >::setAutoDelete().
Variable Documentation
KviPointerList<LinksWindow>* g_pLinksWindowList = 0
Referenced by links_module_cleanup().