KVIrc: src/modules/theme/libkvitheme.cpp File Reference
libkvitheme.cpp File Reference
#include "ThemeManagementDialog.h"
#include "ThemeFunctions.h"
#include "KviKvsArrayCast.h"
#include "KviMessageBox.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviParameterList.h"
#include "KviCommandFormatter.h"
#include "KviError.h"
#include "kvi_out.h"
#include "KviMainWindow.h"
#include "KviIconManager.h"
#include "KviConfigurationFile.h"
#include "kvi_sourcesdate.h"
#include "KviFileUtils.h"
#include "KviFileDialog.h"
#include "KviTheme.h"
#include <QFileInfo>
#include <QMessageBox>
Functions
QRect g_rectManagementDialogGeometry (0, 0, 0, 0)
static bool theme_kvs_cmd_apply (KviKvsModuleCommandCall *c)
static bool theme_kvs_cmd_dialog (KviKvsModuleCommandCall *c)
static bool theme_kvs_cmd_install (KviKvsModuleCommandCall *c)
static bool theme_kvs_cmd_pack (KviKvsModuleCommandCall *c)
static bool theme_kvs_cmd_screenshot (KviKvsModuleCommandCall *c)
static bool theme_kvs_fnc_info (KviKvsModuleFunctionCall *c)
static bool theme_module_can_unload (KviModule *)
static bool theme_module_cleanup (KviModule *m)
static bool theme_module_init (KviModule *m)
Function Documentation
QRect g_rectManagementDialogGeometry (0 , 0 , 0 , 0)
Referenced by theme_module_cleanup(), and theme_module_init().
static bool theme_kvs_cmd_apply (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviTheme::apply(), KviThemeInfo::Auto, KviThemeInfo::Builtin, KviKvsRunTimeCall::error(), KviThemeInfo::External, KviKvsSwitchList::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviThemeInfo::lastError(), KviKvsModuleCommandCall::switches(), and KviThemeInfo::User.
Referenced by theme_module_init().
static bool theme_kvs_cmd_dialog (KviKvsModuleCommandCall * c) static
References ThemeManagementDialog::display(), and KviKvsModuleCommandCall::hasSwitch().
Referenced by theme_module_init().
static bool theme_kvs_cmd_install (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), ThemeFunctions::installThemePackage(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by theme_module_init().
static bool theme_kvs_cmd_pack (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviPointerList< T >::append(), KviKvsArrayCast::array(), KviKvsVariant::asString(), KviKvsArray::at(), KviKvsRunTimeCall::error(), KviThemeInfo::External, i, KviPointerList< T >::isEmpty(), KVS_PT_ARRAYCAST, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviThemeInfo::lastError(), KviThemeInfo::load(), ThemeFunctions::packageThemes(), pArray, s, KviPointerList< T >::setAutoDelete(), KviKvsArray::size(), and v.
Referenced by theme_module_init().
static bool theme_kvs_cmd_screenshot (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviFileUtils::adjustFilePath(), KviFileDialog::askForSaveFileName(), KviKvsRunTimeCall::enterBlockingSection(), KviKvsRunTimeCall::error(), g_pMainWindow, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::leaveBlockingSection(), and ThemeFunctions::makeKVIrcScreenshot().
Referenced by theme_module_init().
static bool theme_kvs_fnc_info (KviKvsModuleFunctionCall * c) static
References __tr2qs_ctx(), KviThemeInfo::author(), KviThemeInfo::Auto, KviThemeInfo::description(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviThemeInfo::load(), KviThemeInfo::name(), KviKvsModuleFunctionCall::returnValue(), KviKvsHash::set(), KviKvsVariant::setHash(), KviThemeInfo::version(), and KviKvsRunTimeCall::warning().
Referenced by theme_module_init().
static bool theme_module_can_unload (KviModule *) static
References ThemeManagementDialog::instance().
static bool theme_module_cleanup (KviModule * m) static
References ThemeManagementDialog::cleanup(), g_rectManagementDialogGeometry(), KviModule::getDefaultConfigFileName(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
static bool theme_module_init (KviModule * m) static
References g_rectManagementDialogGeometry(), KviModule::getDefaultConfigFileName(), KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, KviConfigurationFile::Read, KviConfigurationFile::readRectEntry(), theme_kvs_cmd_apply(), theme_kvs_cmd_dialog(), theme_kvs_cmd_install(), theme_kvs_cmd_pack(), theme_kvs_cmd_screenshot(), and theme_kvs_fnc_info().