KVIrc: src/modules/regchan/libkviregchan.cpp File Reference
src/modules/regchan/libkviregchan.cpp File Reference
#include "KviModule.h"
#include "KviRegisteredChannelDataBase.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviControlCodes.h"
#include "KviWindow.h"
#include "kvi_debug.h"
Functions
static bool regchan_kvs_cmd_add (KviKvsModuleCommandCall *c)
static bool regchan_kvs_cmd_remove (KviKvsModuleCommandCall *c)
static bool regchan_kvs_cmd_setProperty (KviKvsModuleCommandCall *c)
static bool regchan_kvs_cmd_showlist (KviKvsModuleCommandCall *c)
static bool regchan_kvs_fnc_find (KviKvsModuleFunctionCall *c)
static bool regchan_kvs_fnc_list (KviKvsModuleFunctionCall *c)
static bool regchan_kvs_fnc_match (KviKvsModuleFunctionCall *c)
static bool regchan_kvs_fnc_property (KviKvsModuleFunctionCall *c)
static bool regchan_module_can_unload (KviModule *)
static bool regchan_module_cleanup (KviModule *)
static bool regchan_module_init (KviModule *m)
Variables
KVIRC_API
KviRegisteredChannelDataBase * g_pRegisteredChannelDataBase
Function Documentation
static bool regchan_kvs_cmd_add (KviKvsModuleCommandCall * c) [static]
References KviRegisteredChannelDataBase::add(), g_pRegisteredChannelDataBase, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by regchan_module_init().
static bool regchan_kvs_cmd_remove (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredChannelDataBase::find(), KviRegisteredChannelDataBase::findExact(), g_pRegisteredChannelDataBase, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredChannelDataBase::remove(), and KviKvsRunTimeCall::warning().
Referenced by regchan_module_init().
static bool regchan_kvs_cmd_setProperty (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredChannelDataBase::find(), KviRegisteredChannelDataBase::findExact(), g_pRegisteredChannelDataBase, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredChannel::removeProperty(), KviRegisteredChannel::setProperty(), and KviKvsRunTimeCall::warning().
Referenced by regchan_module_init().
static bool regchan_kvs_cmd_showlist (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviControlCodes::Bold, KviRegisteredChannelDataBase::channelDict(), g_pRegisteredChannelDataBase, KVI_ASSERT, KVI_OUT_SYSTEMMESSAGE, l, KviWindow::output(), KviWindow::outputNoFmt(), and KviKvsRunTimeCall::window().
Referenced by regchan_module_init().
static bool regchan_kvs_fnc_find (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredChannelDataBase::find(), g_pRegisteredChannelDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by regchan_module_init().
static bool regchan_kvs_fnc_list (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredChannelDataBase::channelDict(), g_pRegisteredChannelDataBase, KVI_ASSERT, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviQString::matchWildExpressions(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by regchan_module_init().
static bool regchan_kvs_fnc_match (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredChannelDataBase::find(), g_pRegisteredChannelDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by regchan_module_init().
static bool regchan_kvs_fnc_property (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredChannelDataBase::find(), g_pRegisteredChannelDataBase, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredChannel::property(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by regchan_module_init().
static bool regchan_module_can_unload (KviModule *) [static]
static bool regchan_module_cleanup (KviModule *) [static]
static bool regchan_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, regchan_kvs_cmd_add(), regchan_kvs_cmd_remove(), regchan_kvs_cmd_setProperty(), regchan_kvs_cmd_showlist(), regchan_kvs_fnc_find(), regchan_kvs_fnc_list(), regchan_kvs_fnc_match(), and regchan_kvs_fnc_property().
Variable Documentation
KVIRC_API KviRegisteredChannelDataBase* g_pRegisteredChannelDataBase
Referenced by ChannelsJoinDialog::deleteClicked(), ChannelsJoinDialog::fillListView(), regchan_kvs_cmd_add(), regchan_kvs_cmd_remove(), regchan_kvs_cmd_setProperty(), regchan_kvs_cmd_showlist(), regchan_kvs_fnc_find(), regchan_kvs_fnc_list(), regchan_kvs_fnc_match(), regchan_kvs_fnc_property(), KviApplication::saveRegisteredChannels(), KviApplication::setup(), and KviApplication::~KviApplication().