KVIrc: src/modules/dcc/libkvidcc.cpp File Reference
libkvidcc.cpp File Reference
#include "DccVoiceGsmCodec.h"
#include "DccBroker.h"
#include "DccVoiceWindow.h"
#include "DccVideoWindow.h"
#include "DccUtils.h"
#include "DccFileTransfer.h"
#include "DccWindow.h"
#include "kvi_debug.h"
#include "kvi_settings.h"
#include "KviCString.h"
#include "KviModule.h"
#include "KviIrcServerParser.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviConsoleWindow.h"
#include "KviNetUtils.h"
#include "KviMainWindow.h"
#include "KviError.h"
#include "KviOptions.h"
#include "kvi_defaults.h"
#include "KviApplication.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionUserInfo.h"
#include <QFileInfo>
Functions
static bool dcc_kvs_cmd_abort (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_chat (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_get (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_recv (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_rsend (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_send (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_setBandwidthLimit (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_video (KviKvsModuleCommandCall *c)
static bool dcc_kvs_cmd_voice (KviKvsModuleCommandCall *c)
static DccDescriptor * dcc_kvs_find_dcc_descriptor (const kvs_uint_t &uId, KviKvsModuleRunTimeCall *c, bool bWarn=true)
static bool dcc_kvs_fnc_averageSpeed (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_connectionType (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_getSSLCertInfo (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_ircContext (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_isFileDownload (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_isFileTransfer (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_isFileUpload (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localFileName (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localFileSize (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localHost (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localIp (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localNick (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localPort (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_localUser (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_protocol (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remoteFileName (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remoteFileSize (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remoteHost (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remoteIp (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remoteNick (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remotePort (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_remoteUser (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_session (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_sessionList (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_transferredBytes (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_fnc_transferStatus (KviKvsModuleFunctionCall *c)
static bool dcc_kvs_parse_default_parameters (DccDescriptor *d, KviKvsModuleCommandCall *c)
static bool dcc_module_can_unload (KviModule *)
static bool dcc_module_cleanup (KviModule *)
static bool dcc_module_init (KviModule *m)
static void dcc_module_set_dcc_type (DccDescriptor *d, const char *szBaseType)
Variables
DccBroker * g_pDccBroker = 0
Function Documentation
static bool dcc_kvs_cmd_abort (KviKvsModuleCommandCall * c) static
References DccFileTransfer::abort(), dcc_kvs_find_dcc_descriptor(), KviWindow::delayedClose(), KviKvsSwitchList::find(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), DccDescriptor::transfer(), and DccDescriptor::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_chat (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), DccBroker::addZeroPortTag(), DccDescriptor::bActive, DccDescriptor::bSendRequest, KviWindow::connection(), DccDescriptor::console(), KviWindow::console(), d, dcc_kvs_parse_default_parameters(), dcc_module_set_dcc_type(), KviIrcConnection::encodeText(), KviKvsRunTimeCall::error(), DccBroker::executeChat(), KviKvsSwitchList::find(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviDccZeroPortTag::m_szTag, KviIrcConnection::sendFmtData(), KviKvsModuleCommandCall::switches(), DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szNick, DccDescriptor::szPort, DccDescriptor::szType, DccDescriptor::szUser, t(), DccDescriptor::triggerCreationEvent(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_get (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviWindow::connection(), KviWindow::console(), KviQString::cutToLast(), KviIrcConnection::encodeText(), KviKvsSwitchList::find(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, KviCString::prepend(), KviCString::ptr(), KviIrcConnection::sendFmtData(), KviKvsModuleCommandCall::switches(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_recv (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsIncomingAvatar, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bRecvFile, DccDescriptor::bResume, DccDescriptor::bSendRequest, DccDescriptor::console(), KviWindow::console(), d, dcc_kvs_parse_default_parameters(), dcc_module_set_dcc_type(), KviKvsSwitchList::find(), KviApplication::findPendingAvatarChange(), g_pApp, KVI_OPTION_BOOL, KviOption_boolAutoAcceptDccSend, KviOption_boolAutoAcceptIncomingAvatars, KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccBroker::recvFileManage(), KviKvsModuleCommandCall::switches(), DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szNick, DccDescriptor::szPort, DccDescriptor::szUser, DccDescriptor::triggerCreationEvent(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_rsend (KviKvsModuleCommandCall * c) static
COMPILE_SSL_SUPPORT
References __tr2qs_ctx(), DccDescriptor::bIsTdcc, KviWindow::console(), d, dcc_module_set_dcc_type(), KviKvsSwitchList::find(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, DccBroker::rsendManage(), DccDescriptor::setZeroPortRequestTag(), KviKvsModuleCommandCall::switches(), DccDescriptor::szLocalFileName, DccDescriptor::szNick, DccDescriptor::triggerCreationEvent(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_send (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), __tr_ctx, KviKvsVariant::asInteger(), KviKvsVariant::asString(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsIncomingAvatar, DccDescriptor::bNoAcks, DccDescriptor::bRecvFile, DccDescriptor::bResume, DccDescriptor::bSendRequest, KviWindow::console(), d, dcc_kvs_parse_default_parameters(), dcc_module_set_dcc_type(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviKvsVariant::isBoolean(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccBroker::recvFileManage(), DccBroker::sendFileExecute(), DccBroker::sendFileManage(), KviKvsModuleCommandCall::switches(), DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szLocalFileName, DccDescriptor::szNick, DccDescriptor::szPort, DccDescriptor::szUser, DccDescriptor::triggerCreationEvent(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_setBandwidthLimit (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), dcc_kvs_find_dcc_descriptor(), KviKvsSwitchList::find(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccFileTransfer::setBandwidthLimit(), KviKvsModuleCommandCall::switches(), DccDescriptor::transfer(), and KviKvsRunTimeCall::warning().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_video (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), DccBroker::activeVideoExecute(), DccDescriptor::bActive, DccDescriptor::bSendRequest, KviWindow::console(), d, dcc_kvs_parse_default_parameters(), dcc_module_set_dcc_type(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), kvi_dcc_video_is_valid_codec(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccBroker::passiveVideoExecute(), KviKvsModuleCommandCall::switches(), DccDescriptor::szCodec, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szNick, DccDescriptor::szPort, DccDescriptor::szUser, DccDescriptor::triggerCreationEvent(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_cmd_voice (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), DccBroker::activeVoiceExecute(), DccDescriptor::bActive, DccDescriptor::bSendRequest, KviWindow::console(), d, dcc_kvs_parse_default_parameters(), dcc_module_set_dcc_type(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), DccDescriptor::iSampleRate, kvi_dcc_voice_is_valid_codec(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccBroker::passiveVoiceExecute(), KviKvsModuleCommandCall::switches(), DccDescriptor::szCodec, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szNick, DccDescriptor::szPort, DccDescriptor::szUser, DccDescriptor::triggerCreationEvent(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static DccDescriptor* dcc_kvs_find_dcc_descriptor (const kvs_uint_t & uId, KviKvsModuleRunTimeCall * c, bool bWarn = true) static
References __tr2qs_ctx(), DccDescriptor::find(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by dcc_kvs_cmd_abort(), dcc_kvs_cmd_setBandwidthLimit(), dcc_kvs_fnc_averageSpeed(), dcc_kvs_fnc_connectionType(), dcc_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_ircContext(), dcc_kvs_fnc_isFileDownload(), dcc_kvs_fnc_isFileTransfer(), dcc_kvs_fnc_isFileUpload(), dcc_kvs_fnc_localFileName(), dcc_kvs_fnc_localFileSize(), dcc_kvs_fnc_localHost(), dcc_kvs_fnc_localIp(), dcc_kvs_fnc_localNick(), dcc_kvs_fnc_localPort(), dcc_kvs_fnc_localUser(), dcc_kvs_fnc_protocol(), dcc_kvs_fnc_remoteFileName(), dcc_kvs_fnc_remoteFileSize(), dcc_kvs_fnc_remoteHost(), dcc_kvs_fnc_remoteIp(), dcc_kvs_fnc_remoteNick(), dcc_kvs_fnc_remotePort(), dcc_kvs_fnc_remoteUser(), dcc_kvs_fnc_transferredBytes(), and dcc_kvs_fnc_transferStatus().
static bool dcc_kvs_fnc_averageSpeed (KviKvsModuleFunctionCall * c) static
References DccFileTransfer::averageSpeed(), dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and DccDescriptor::transfer().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_connectionType (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), DccDescriptor::isActive(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_getSSLCertInfo (KviKvsModuleFunctionCall * c) static
References __tr2qs_ctx(), dcc_kvs_find_dcc_descriptor(), DccWindow::getSlaveThread(), DccFileTransfer::getSlaveThread(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), DccDescriptor::transfer(), KviKvsRunTimeCall::warning(), and DccDescriptor::window().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_ircContext (KviKvsModuleFunctionCall * c) static
References __tr2qs_ctx(), DccDescriptor::console(), KviConsoleWindow::context(), dcc_kvs_find_dcc_descriptor(), KviKvsRunTimeCall::error(), g_pApp, KviIrcContext::id(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviApplication::windowExists().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_isFileDownload (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), DccDescriptor::isFileDownload(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_isFileTransfer (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), DccDescriptor::isFileTransfer(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_isFileUpload (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), DccDescriptor::isFileUpload(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localFileName (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localFileName(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localFileSize (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localFileSize(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localHost (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localHost(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localIp (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localIp(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localNick (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localNick(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localPort (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localPort(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_localUser (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::localUser(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_protocol (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::protocol(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remoteFileName (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remoteFileName(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remoteFileSize (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remoteFileSize(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remoteHost (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remoteHost(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remoteIp (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remoteIp(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remoteNick (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remoteNick(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remotePort (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remotePort(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_remoteUser (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, DccDescriptor::remoteUser(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_session (KviKvsModuleFunctionCall * c) static
References __tr2qs_ctx(), KviApplication::findWindow(), g_pApp, DccDescriptor::id(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_sessionList (KviKvsModuleFunctionCall * c) static
References a, KviPointerHashTableIterator< Key, T >::current(), DccDescriptor::descriptorDict(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_transferredBytes (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), DccDescriptor::transfer(), and DccFileTransfer::transferredBytes().
Referenced by dcc_module_init().
static bool dcc_kvs_fnc_transferStatus (KviKvsModuleFunctionCall * c) static
References dcc_kvs_find_dcc_descriptor(), DccFileTransfer::fillStatusString(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and DccDescriptor::transfer().
Referenced by dcc_module_init().
static bool dcc_kvs_parse_default_parameters (DccDescriptor * d, KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviKvsVariant::asBoolean(), KviKvsVariant::asString(), DccDescriptor::bDoTimeout, DccDescriptor::bIsTdcc, DccDescriptor::bOverrideMinimize, KviWindow::connection(), DccDescriptor::console(), d, dcc_kvs_get_listen_ip_address(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviMainWindow::firstConsole(), g_pMainWindow, KviNetUtils::getInterfaceAddress(), KviIrcConnectionUserInfo::hostName(), KviConsoleWindow::isConnected(), KVI_ASSERT, KVI_DEFAULT_NICKNAME1, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolDccSendFakeAddressByDefault, KviOption_stringDefaultDccFakeAddress, KviOption_stringNickname1, KviIrcConnectionUserInfo::nickName(), DccDescriptor::setConsole(), KviKvsModuleCommandCall::switches(), DccDescriptor::szFakeIp, DccDescriptor::szFakePort, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szLocalHost, DccDescriptor::szLocalNick, DccDescriptor::szLocalUser, KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), and KviKvsRunTimeCall::warning().
Referenced by dcc_kvs_cmd_chat(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_send(), dcc_kvs_cmd_video(), and dcc_kvs_cmd_voice().
static bool dcc_module_can_unload (KviModule *) static
References DccBroker::canUnload().
static bool dcc_module_cleanup (KviModule *) static
References g_pDccBroker.
static bool dcc_module_init (KviModule * m) static
References dcc_kvs_cmd_abort(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_setBandwidthLimit(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_fnc_averageSpeed(), dcc_kvs_fnc_connectionType(), dcc_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_ircContext(), dcc_kvs_fnc_isFileDownload(), dcc_kvs_fnc_isFileTransfer(), dcc_kvs_fnc_isFileUpload(), dcc_kvs_fnc_localFileName(), dcc_kvs_fnc_localFileSize(), dcc_kvs_fnc_localHost(), dcc_kvs_fnc_localIp(), dcc_kvs_fnc_localNick(), dcc_kvs_fnc_localPort(), dcc_kvs_fnc_localUser(), dcc_kvs_fnc_protocol(), dcc_kvs_fnc_remoteFileName(), dcc_kvs_fnc_remoteFileSize(), dcc_kvs_fnc_remoteHost(), dcc_kvs_fnc_remoteIp(), dcc_kvs_fnc_remoteNick(), dcc_kvs_fnc_remotePort(), dcc_kvs_fnc_remoteUser(), dcc_kvs_fnc_session(), dcc_kvs_fnc_sessionList(), dcc_kvs_fnc_transferredBytes(), dcc_kvs_fnc_transferStatus(), KVSM_REGISTER_FUNCTION, and KVSM_REGISTER_SIMPLE_COMMAND.
static void dcc_module_set_dcc_type (DccDescriptor * d, const char * szBaseType) static
References DccDescriptor::bIsTdcc, and DccDescriptor::szType.
Referenced by dcc_kvs_cmd_chat(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_video(), and dcc_kvs_cmd_voice().
Variable Documentation
DccBroker* g_pDccBroker = 0
Referenced by dcc_module_cleanup().