KVIrc: src/modules/iograph/libkviiograph.cpp File Reference
src/modules/iograph/libkviiograph.cpp File Reference
#include <math.h>
#include "libkviiograph.h"
#include "KviMainWindow.h"
#include "KviIconManager.h"
#include "KviLocale.h"
#include "KviMdiManager.h"
#include "KviModule.h"
#include "KviOptions.h"
#include "kvi_socket.h"
#include <QPainter>
#include <QPaintEvent>
#include "libkviiograph.moc"
Functions
static bool iograph_module_can_unload (KviModule *)
static bool iograph_module_cleanup (KviModule *)
static bool iograph_module_cmd_open (KviKvsModuleCommandCall *c)
static bool iograph_module_init (KviModule *m)
Variables
KviIOGraphWindow * g_pIOGraphWindow = 0
Function Documentation
static bool iograph_module_can_unload (KviModule *) [static]
static bool iograph_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool iograph_module_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviMainWindow::addWindow(), KviWindow::delayedAutoRaise(), g_pMainWindow, KviKvsModuleCommandCall::hasSwitch(), and KviWindow::minimize().
Referenced by iograph_module_init().
static bool iograph_module_init (KviModule * m) [static]
References iograph_module_cmd_open(), and KVSM_REGISTER_SIMPLE_COMMAND.
Variable Documentation
KviIOGraphWindow* g_pIOGraphWindow = 0