KVIrc: src/modules/notifier/libkvinotifier.cpp File Reference
src/modules/notifier/libkvinotifier.cpp File Reference
#include "NotifierWindow.h"
#include "NotifierMessage.h"
#include "KviModule.h"
#include "KviKvsVariant.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include "KviTimeUtils.h"
#include "KviOptions.h"
#include <QSplitter>
Functions
static bool notifier_kvs_cmd_hide (KviKvsModuleCommandCall *c)
static bool notifier_kvs_cmd_message (KviKvsModuleCommandCall *c)
static bool notifier_kvs_cmd_show (KviKvsModuleCommandCall *c)
static bool notifier_kvs_fnc_isEnabled (KviKvsModuleFunctionCall *c)
static bool notifier_module_can_unload (KviModule *)
static bool notifier_module_cleanup (KviModule *)
static bool notifier_module_ctrl (KviModule *, const char *pcOperation, void *pParam)
static bool notifier_module_init (KviModule *m)
Variables
NotifierWindow * g_pNotifierWindow = 0
kvi_time_t g_tNotifierDisabledUntil = 0
Function Documentation
static bool notifier_kvs_cmd_hide (KviKvsModuleCommandCall * c) [static]
References NotifierWindow::doHide(), and KviKvsModuleCommandCall::hasSwitch().
Referenced by notifier_module_init().
static bool notifier_kvs_cmd_message (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), NotifierWindow::addMessage(), KviKvsVariant::asInteger(), NotifierWindow::doShow(), KviApplication::findWindow(), g_pApp, KviKvsSwitchList::getAsStringIfExisting(), KviKvsModuleCommandCall::getSwitch(), KviKvsModuleCommandCall::hasSwitch(), KVI_OPTION_UINT, KviOption_uintNotifierAutoHideTime, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by notifier_module_init().
static bool notifier_kvs_cmd_show (KviKvsModuleCommandCall * c) [static]
References NotifierWindow::countTabs(), NotifierWindow::doShow(), KviKvsModuleCommandCall::hasSwitch(), and NotifierWindow::setDisableHideOnMainWindowGotAttention().
Referenced by notifier_module_init().
static bool notifier_kvs_fnc_isEnabled (KviKvsModuleFunctionCall * c) [static]
References g_tNotifierDisabledUntil, KVI_OPTION_BOOL, kvi_unixTime, KviOption_boolEnableNotifier, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by notifier_module_init().
static bool notifier_module_can_unload (KviModule *) [static]
static bool notifier_module_cleanup (KviModule *) [static]
References g_pNotifierWindow.
static bool notifier_module_ctrl (KviModule * , const char * pcOperation, void * pParam) [static]
References NotifierWindow::addMessage(), NotifierWindow::doShow(), KVI_OPTION_BOOL, kvi_strEqualCI(), KviOption_boolNotifierFading, p, _KviNotifierMessageParam::pWindow, _KviNotifierMessageParam::szIcon, _KviNotifierMessageParam::szMessage, and _KviNotifierMessageParam::uMessageLifetime.
static bool notifier_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, notifier_kvs_cmd_hide(), notifier_kvs_cmd_message(), notifier_kvs_cmd_show(), and notifier_kvs_fnc_isEnabled().
Variable Documentation
NotifierWindow* g_pNotifierWindow = 0
Referenced by notifier_module_cleanup().
kvi_time_t g_tNotifierDisabledUntil = 0
Referenced by NotifierWindow::disableFor15Minutes(), NotifierWindow::disableFor1Minute(), NotifierWindow::disableFor30Minutes(), NotifierWindow::disableFor5Minutes(), NotifierWindow::disableFor60Minutes(), NotifierWindow::disableUntilKVIrcRestarted(), NotifierWindow::doShow(), and notifier_kvs_fnc_isEnabled().