KVIrc: src/modules/logview/libkvilogview.cpp File Reference
src/modules/logview/libkvilogview.cpp File Reference
#include "LogViewWidget.h"
#include "LogViewWindow.h"
#include "KviConfigurationFile.h"
#include "KviModule.h"
#include "KviMainWindow.h"
#include "KviIconManager.h"
#include "KviLocale.h"
#include "KviApplication.h"
Defines
#define LOGVIEW_MODULE_EXTENSION_NAME "Log viewer extension"
Functions
static KviModuleExtension * logview_extension_alloc (KviModuleExtensionAllocStruct *s)
static bool logview_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool logview_module_can_unload (KviModule *)
static bool logview_module_cleanup (KviModule *)
static bool logview_module_ctrl (KviModule *, const char *pcOperation, void *pParam)
static bool logview_module_init (KviModule *m)
Variables
LogViewWindow * g_pLogViewWindow = 0
static QRect g_rectLogViewGeometry
Define Documentation
#define LOGVIEW_MODULE_EXTENSION_NAME "Log viewer extension"
Referenced by logview_kvs_cmd_open(), and logview_module_init().
Function Documentation
static KviModuleExtension* logview_extension_alloc (KviModuleExtensionAllocStruct * s) [static]
References KviMainWindow::addWindow(), KviWindow::delayedAutoRaise(), KviPointerHashTable< Key, T >::find(), g_pLogViewWindow, g_pMainWindow, KviWindow::minimize(), _KviModuleExtensionAllocStructTag::pDescriptor, _KviModuleExtensionAllocStructTag::pParams, and v.
Referenced by logview_module_init().
static bool logview_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviModuleExtensionDescriptor::allocate(), d, KviModule::findExtensionDescriptor(), KviKvsModuleCommandCall::hasSwitch(), LOGVIEW_MODULE_EXTENSION_NAME, KviKvsModuleRunTimeCall::module(), KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by logview_module_init().
static bool logview_module_can_unload (KviModule *) [static]
static bool logview_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool logview_module_ctrl (KviModule * , const char * pcOperation, void * pParam) [static]
References LogViewWindow::createLog(), LogFile::HTML, kvi_strEqualCI(), LogFile::PlainText, _LogFileData::szFile, _LogFileData::szName, and _LogFileData::szType.
static bool logview_module_init (KviModule * m) [static]
References __tr2qs_ctx(), d, g_pIconManager, KviIconManager::getSmallIcon(), KVSM_REGISTER_SIMPLE_COMMAND, KviIconManager::Log, logview_extension_alloc(), logview_kvs_cmd_open(), LOGVIEW_MODULE_EXTENSION_NAME, KviModule::registerExtension(), and KviModuleExtensionDescriptor::setIcon().
Variable Documentation
LogViewWindow* g_pLogViewWindow = 0
Referenced by logview_extension_alloc().
QRect g_rectLogViewGeometry [static]