KVIrc: src/modules/term/libkviterm.cpp File Reference
src/modules/term/libkviterm.cpp File Reference
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviWindow.h"
#include "KviMainWindow.h"
#include "KviPointerList.h"
#include <QSplitter>
Functions
static bool term_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool term_module_cleanup (KviModule *)
static bool term_module_init (KviModule *m)
Variables
KviModule * g_pTermModule = 0
Function Documentation
static bool term_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviMainWindow::addWindow(), g_pMainWindow, KviKvsModuleCommandCall::hasSwitch(), KviModule::lock(), KviKvsModuleRunTimeCall::module(), KviMainWindow::splitter(), w, and KviKvsRunTimeCall::warning().
Referenced by term_module_init().
static bool term_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first().
static bool term_module_init (KviModule * m) [static]
References KVSM_REGISTER_SIMPLE_COMMAND, m, KviPointerList< T >::setAutoDelete(), and term_kvs_cmd_open().
Variable Documentation
KviModule* g_pTermModule = 0