KVIrc: src/modules/dialog/libkvidialog.cpp File Reference
src/modules/dialog/libkvidialog.cpp File Reference
#include "libkvidialog.h"
#include "KviLocale.h"
#include "KviModule.h"
#include "KviModuleManager.h"
#include "KviError.h"
#include "KviApplication.h"
#include "KviIconManager.h"
#include "KviConsoleWindow.h"
#include "KviKvsScript.h"
#include "KviMessageBox.h"
#include "KviTalHBox.h"
#include <QMessageBox>
#include <QLayout>
#include <QLineEdit>
#include <QLabel>
#include <QPushButton>
#include <QDesktopWidget>
#include <QEvent>
#include <QCloseEvent>
#include <QTextEdit>
#include "libkvidialog.moc"
Functions
static bool dialog_kvs_cmd_file (KviKvsModuleCallbackCommandCall *c)
static bool dialog_kvs_cmd_image (KviKvsModuleCallbackCommandCall *c)
static bool dialog_kvs_cmd_message (KviKvsModuleCallbackCommandCall *c)
static bool dialog_kvs_cmd_textinput (KviKvsModuleCallbackCommandCall *c)
static bool dialog_kvs_fnc_yesno (KviKvsModuleFunctionCall *c)
static bool dialog_module_can_unload (KviModule *)
static bool dialog_module_cleanup (KviModule *)
static bool dialog_module_init (KviModule *m)
Variables
static KviPointerList< QWidget > * g_pDialogModuleDialogList
Function Documentation
static bool dialog_kvs_cmd_file (KviKvsModuleCallbackCommandCall * c) [static]
References KviTalFileDialog::AnyFile, KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviTalFileDialog::DirectoryOnly, KviQString::equalCI(), KviTalFileDialog::ExistingFile, KviTalFileDialog::ExistingFiles, KviKvsModuleCommandCall::hasSwitch(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviTalFileDialog::setFileMode(), and KviKvsRunTimeCall::window().
Referenced by dialog_module_init().
static bool dialog_kvs_cmd_image (KviKvsModuleCallbackCommandCall * c) [static]
References KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsModuleCommandCall::hasSwitch(), KID_TYPE_ALL, KID_TYPE_BUILTIN_IMAGES_SMALL, KID_TYPE_FULL_PATH, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::window().
Referenced by dialog_module_init().
static bool dialog_kvs_cmd_message (KviKvsModuleCallbackCommandCall * c) [static]
References KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsModuleCommandCall::hasSwitch(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::window().
Referenced by dialog_module_init().
static bool dialog_kvs_cmd_textinput (KviKvsModuleCallbackCommandCall * c) [static]
References KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsSwitchList::find(), KviKvsSwitchList::getAsStringIfExisting(), KviKvsModuleCommandCall::hasSwitch(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::window().
Referenced by dialog_module_init().
static bool dialog_kvs_fnc_yesno (KviKvsModuleFunctionCall * c) [static]
References KviKvsRunTimeCall::enterBlockingSection(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::leaveBlockingSection(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviMessageBox::yesNo().
Referenced by dialog_module_init().
static bool dialog_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool dialog_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first(), and g_pDialogModuleDialogList.
static bool dialog_module_init (KviModule * m) [static]
References dialog_kvs_cmd_file(), dialog_kvs_cmd_image(), dialog_kvs_cmd_message(), dialog_kvs_cmd_textinput(), dialog_kvs_fnc_yesno(), KVSM_REGISTER_CALLBACK_COMMAND, KVSM_REGISTER_FUNCTION, and KviPointerList< T >::setAutoDelete().
Variable Documentation
KviPointerList<QWidget>* g_pDialogModuleDialogList [static]
Referenced by dialog_module_cleanup().