KVIrc: src/modules/socketspy/libkvisocketspy.cpp File Reference
src/modules/socketspy/libkvisocketspy.cpp File Reference
#include "SocketSpyWindow.h"
#include "KviModule.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include <QSplitter>
Functions
static bool socketspy_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool socketspy_module_can_unload (KviModule *)
static bool socketspy_module_cleanup (KviModule *)
static bool socketspy_module_init (KviModule *m)
Variables
KviPointerList< SocketSpyWindow > * g_pSocketSpyWindowList = 0
Function Documentation
static bool socketspy_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviMainWindow::addWindow(), KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsRunTimeContext::errorNoIrcContext(), g_pMainWindow, w, and KviKvsRunTimeCall::window().
Referenced by socketspy_module_init().
static bool socketspy_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool socketspy_module_cleanup (KviModule *) [static]
References SocketSpyWindow::die(), KviPointerList< T >::first(), and g_pSocketSpyWindowList.
static bool socketspy_module_init (KviModule * m) [static]
References KVSM_REGISTER_SIMPLE_COMMAND, KviPointerList< T >::setAutoDelete(), and socketspy_kvs_cmd_open().
Variable Documentation
KviPointerList<SocketSpyWindow>* g_pSocketSpyWindowList = 0
Referenced by socketspy_module_cleanup().