KVIrc: src/modules/serverdb/libkviserverdb.cpp File Reference
src/modules/serverdb/libkviserverdb.cpp File Reference
#include "KviModule.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviIrcServer.h"
#include "KviIrcServerDataBase.h"
#include <QString>
Defines
#define BEGIN_SERVERDB_GET_NETWORK_PROPERTY(__functionName)
#define BEGIN_SERVERDB_GET_SERVER_PROPERTY(__functionName)
#define END_SERVERDB_GET_NETWORK_PROPERTY
#define END_SERVERDB_GET_SERVER_PROPERTY
#define SERVERDB_GET_NETWORK_PROPERTY(__functionName, __callName)
#define SERVERDB_GET_SERVER_PROPERTY(__functionName, __callName, __variantSetCallName)
#define SERVERDB_SET_NETWORK_PROPERTY(__functionName, __callName)
#define SERVERDB_SET_SERVER_PROPERTY(__functionName, __callName)
Functions
if (pAutoJoinChannels)
c returnValue ()->setArray(pArray)
static
END_SERVERDB_GET_SERVER_PROPERTY
bool serverdb_kvs_cmd_addNetwork (KviKvsModuleCommandCall *c)
static bool serverdb_kvs_cmd_addServer (KviKvsModuleCommandCall *c)
static bool serverdb_kvs_fnc_networkExists (KviKvsModuleFunctionCall *c)
static bool serverdb_kvs_fnc_serverExists (KviKvsModuleFunctionCall *c)
static bool serverdb_module_can_unload (KviModule *)
static bool serverdb_module_cleanup (KviModule *)
static bool serverdb_module_init (KviModule *m)
Variables
KVIRC_API KviIrcServerDataBase * g_pServerDataBase
KviKvsArray * pArray = new KviKvsArray()
QStringList * pAutoJoinChannels = pNetwork->autoJoinChannelList()
Define Documentation
#define BEGIN_SERVERDB_GET_NETWORK_PROPERTY (__functionName)
Value:
static bool __functionName(KviKvsModuleFunctionCall * c) \
        { \
                QString szName; \
                \
                KVSM_PARAMETERS_BEGIN(c) \
                        KVSM_PARAMETER("name",KVS_PT_STRING,0,szName) \
                KVSM_PARAMETERS_END(c) \
                \
                if(szName.isEmpty()) \
                { \
                        c->error(__tr2qs_ctx("You must provide the network name as parameter","serverdb")); \
                        return false; \
                } \
                \
                KviIrcNetwork * pNetwork = g_pServerDataBase->findNetwork(szName); \
                if(!pNetwork) \
                { \
                        c->error(__tr2qs_ctx("The specified network does not exist","serverdb")); \
                        return false; \
                }
#define BEGIN_SERVERDB_GET_SERVER_PROPERTY (__functionName)
#define END_SERVERDB_GET_NETWORK_PROPERTY
Value:
return true; \
        }
#define END_SERVERDB_GET_SERVER_PROPERTY
Value:
return true; \
        }
#define SERVERDB_GET_NETWORK_PROPERTY (__functionName, __callName)
Value:
BEGIN_SERVERDB_GET_NETWORK_PROPERTY(__functionName) \
                \
                c->returnValue()->setString(pNetwork->__callName()); \
                \
        END_SERVERDB_GET_NETWORK_PROPERTY
#define SERVERDB_GET_SERVER_PROPERTY (__functionName, __callName, __variantSetCallName)
Value:
BEGIN_SERVERDB_GET_SERVER_PROPERTY(__functionName) \
                c->returnValue()->__variantSetCallName(pServer->__callName()); \
                END_SERVERDB_GET_SERVER_PROPERTY
#define SERVERDB_SET_NETWORK_PROPERTY (__functionName, __callName)
Value:
static bool __functionName(KviKvsModuleCommandCall * c) \
        { \
                QString szName, szPropertyValue; \
                \
                KVSM_PARAMETERS_BEGIN(c) \
                        KVSM_PARAMETER("name",KVS_PT_STRING,0,szName) \
                        KVSM_PARAMETER("property",KVS_PT_STRING,KVS_PF_APPENDREMAINING,szPropertyValue) \
                KVSM_PARAMETERS_END(c) \
                \
                if(szName.isEmpty()) \
                { \
                        c->error(__tr2qs_ctx("You must provide the network name as parameter","serverdb")); \
                        return false; \
                } \
                \
                KviIrcNetwork * pNetwork = g_pServerDataBase->findNetwork(szName); \
                if(!pNetwork) \
                { \
                        if(c->switches()->find('q',"quiet")) return true; \
                        c->error(__tr2qs_ctx("The specified network does not exist","serverdb")); \
                        return false; \
                } \
                \
                pNetwork->__callName(szPropertyValue); \
                \
                return true; \
        }
#define SERVERDB_SET_SERVER_PROPERTY (__functionName, __callName)
Function Documentation
if (pAutoJoinChannels)
References pArray, and KviKvsArray::set().
c returnValue ()
References KviIrcContext::Connected, KviIrcContext::Connecting, GET_CONSOLE_FROM_STANDARD_PARAMS, KviIrcContext::Idle, and KviIrcContext::LoggingIn.
static END_SERVERDB_GET_SERVER_PROPERTY bool serverdb_kvs_cmd_addNetwork (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviIrcServerDataBase::addNetwork(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviIrcServerDataBase::findNetwork(), g_pServerDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcNetwork::setAutoConnect(), and KviKvsModuleCommandCall::switches().
Referenced by serverdb_module_init().
static bool serverdb_kvs_cmd_addServer (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviIrcServerDataBase::findNetwork(), KviIrcNetwork::findServer(), g_pServerDataBase, KviKvsSwitchList::getAsStringIfExisting(), KviIrcNetwork::insertServer(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcServer::setAutoConnect(), KviIrcServer::setCacheIp(), KviIrcServer::setHostName(), KviIrcServer::setIPv6(), KviIrcServer::setPassword(), KviIrcServer::setPort(), KviIrcServer::setUseSSL(), KviKvsModuleCommandCall::switches(), and uPort.
Referenced by serverdb_module_init().
static bool serverdb_kvs_fnc_networkExists (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviIrcServerDataBase::findNetwork(), g_pServerDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by serverdb_module_init().
static bool serverdb_kvs_fnc_serverExists (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviPointerHashTableIterator< Key, T >::current(), KviKvsRunTimeCall::error(), KviIrcServerDataBase::findNetwork(), KviIrcNetwork::findServer(), KviPointerList< T >::first(), g_pServerDataBase, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviPointerList< T >::next(), r, KviIrcServerDataBase::recordDict(), KviKvsModuleFunctionCall::returnValue(), s, and KviKvsVariant::setBoolean().
Referenced by serverdb_module_init().
static bool serverdb_module_can_unload (KviModule *) [static]
static bool serverdb_module_cleanup (KviModule *) [static]
static bool serverdb_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, serverdb_kvs_cmd_addNetwork(), serverdb_kvs_cmd_addServer(), serverdb_kvs_fnc_networkExists(), and serverdb_kvs_fnc_serverExists().
Variable Documentation
KVIRC_API KviIrcServerDataBase* g_pServerDataBase
Referenced by KviApplication::autoConnectToServers(), OptionsWidget_servers::commit(), KviIrcContext::connectToCurrentServer(), KviApplication::createFrame(), OptionsWidget_servers::fillServerList(), KviApplication::saveIrcServerDataBase(), serverdb_kvs_cmd_addNetwork(), serverdb_kvs_cmd_addServer(), serverdb_kvs_fnc_networkExists(), serverdb_kvs_fnc_serverExists(), KviApplication::setup(), setup_finish(), and KviApplication::~KviApplication().
END_SERVERDB_GET_NETWORK_PROPERTY KviKvsArray * pArray = new KviKvsArray()
Referenced by KviKvsVariant::castToArray(), chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_masklist(), chan_kvs_fnc_users(), config_kvs_fnc_filelist(), config_kvs_fnc_keylist(), config_kvs_fnc_sectionlist(), context_kvs_fnc_list(), KviKvsVariant::convertToArray(), file_kvs_cmd_writeBytes(), file_kvs_fnc_readBytes(), if(), KviKvsArrayElement::KviKvsArrayElement(), KviKvsVariant::KviKvsVariant(), KVSO_CLASS_FUNCTION(), MP_KVS_FUNCTION(), objects_kvs_fnc_classes(), regchan_kvs_fnc_list(), reguser_kvs_fnc_list(), reguser_kvs_fnc_mask(), KviKvsVariant::setArray(), KvsObject_http::slotSslErrors(), TC_KVS_FUNCTION(), KviKvsVariant::unserializeArray(), and window_kvs_fnc_list().
QStringList * pAutoJoinChannels = pNetwork->autoJoinChannelList()