KVIrc: src/modules/file/libkvifile.cpp File Reference
src/modules/file/libkvifile.cpp File Reference
#include "KviModule.h"
#include "KviFileUtils.h"
#include "KviLocale.h"
#include "KviMemory.h"
#include "KviApplication.h"
#include "KviOptions.h"
#include "KviKvsArrayCast.h"
#include "KviFile.h"
#include <QFileInfo>
#include <QDir>
#include <QTextStream>
#include <QTextCodec>
#include <QByteArray>
#include <QCryptographicHash>
Functions
static bool file_kvs_cmd_addimagepath (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_copy (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_delimagepath (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_mkdir (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_remove (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_rename (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_rmdir (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_write (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_writeBytes (KviKvsModuleCommandCall *c)
static bool file_kvs_cmd_writeLines (KviKvsModuleCommandCall *c)
static bool file_kvs_fnc_allSizes (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_cwd (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_digest (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_extractfilename (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_extractpath (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_fixpath (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_globaldir (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_homedir (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_localdir (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_ls (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_ps (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_read (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_readBytes (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_readLines (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_rootdir (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_size (KviKvsModuleFunctionCall *c)
static bool file_kvs_fnc_type (KviKvsModuleFunctionCall *c)
static bool file_module_cleanup (KviModule *)
static bool file_module_init (KviModule *m)
Function Documentation
static bool file_kvs_cmd_addimagepath (KviKvsModuleCommandCall * c) [static]
References KviFileUtils::adjustFilePath(), KVI_OPTION_STRINGLIST, KviOption_stringlistImageSearchPaths, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by file_module_init().
static bool file_kvs_cmd_copy (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviFileUtils::copyFile(), KviFileUtils::fileExists(), KviKvsSwitchList::find(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_cmd_delimagepath (KviKvsModuleCommandCall * c) [static]
References KviFileUtils::adjustFilePath(), KVI_OPTION_STRINGLIST, KviOption_stringlistImageSearchPaths, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by file_module_init().
static bool file_kvs_cmd_mkdir (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviFileUtils::makeDir(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_cmd_remove (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviKvsSwitchList::find(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviFileUtils::removeFile(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_cmd_rename (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviFileUtils::fileExists(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviFileUtils::renameFile(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_cmd_rmdir (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviKvsSwitchList::find(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviFileUtils::removeDir(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_cmd_write (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviKvsSwitchList::find(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), KviKvsRunTimeCall::warning(), KviFileUtils::writeFile(), and KviFileUtils::writeFileLocal8Bit().
Referenced by file_module_init().
static bool file_kvs_cmd_writeBytes (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsArray::at(), KviKvsRunTimeCall::error(), f, KviKvsSwitchList::find(), i, KVS_PT_ARRAY, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, NULL, pArray, KviKvsArray::size(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_cmd_writeLines (KviKvsModuleCommandCall * c) [static]
References __tr2qs, a, KviFileUtils::adjustFilePath(), KviKvsArrayCast::array(), KviKvsVariant::asString(), KviKvsArray::at(), f, KviKvsSwitchList::find(), KVS_PT_ARRAYCAST, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsArray::size(), KviKvsModuleCommandCall::switches(), u, v, and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_allSizes (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, a, KviFileUtils::adjustFilePath(), d, f, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_cwd (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), KviQString::ensureLastCharIs(), KVI_PATH_SEPARATOR_CHAR, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_digest (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, NULL, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), u, and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_exists (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), f, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by file_module_init().
static bool file_kvs_fnc_extractfilename (KviKvsModuleFunctionCall * c) [static]
References KviQString::cutToLast(), KviFileUtils::extractFileName(), KVI_PATH_SEPARATOR_CHAR, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_extractpath (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_fixpath (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_globaldir (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), g_pApp, KviApplication::getGlobalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviApplication::None, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_homedir (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), KviQString::ensureLastCharIs(), KVI_PATH_SEPARATOR_CHAR, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_localdir (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), g_pApp, KviApplication::getLocalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviApplication::None, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_ls (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, a, KviFileUtils::adjustFilePath(), d, Hidden, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_ps (KviKvsModuleFunctionCall * c) [static]
References KVI_PATH_SEPARATOR_CHAR, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_read (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviMemory::allocate(), KviKvsVariantList::count(), f, KviMemory::free(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::params(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_readBytes (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviFileUtils::adjustFilePath(), KviMemory::allocate(), KviKvsVariantList::count(), f, KviMemory::free(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, p, KviKvsRunTimeCall::params(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), u, and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_readLines (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, a, KviFileUtils::adjustFilePath(), KviKvsVariantList::count(), f, i, KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::params(), KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by file_module_init().
static bool file_kvs_fnc_rootdir (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), KviQString::ensureLastCharIs(), KVI_PATH_SEPARATOR_CHAR, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_kvs_fnc_size (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), f, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by file_module_init().
static bool file_kvs_fnc_type (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), f, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by file_module_init().
static bool file_module_cleanup (KviModule *) [static]
static bool file_module_init (KviModule * m) [static]
References file_kvs_cmd_addimagepath(), file_kvs_cmd_copy(), file_kvs_cmd_delimagepath(), file_kvs_cmd_mkdir(), file_kvs_cmd_remove(), file_kvs_cmd_rename(), file_kvs_cmd_rmdir(), file_kvs_cmd_write(), file_kvs_cmd_writeBytes(), file_kvs_cmd_writeLines(), file_kvs_fnc_allSizes(), file_kvs_fnc_cwd(), file_kvs_fnc_digest(), file_kvs_fnc_exists(), file_kvs_fnc_extractfilename(), file_kvs_fnc_extractpath(), file_kvs_fnc_fixpath(), file_kvs_fnc_globaldir(), file_kvs_fnc_homedir(), file_kvs_fnc_localdir(), file_kvs_fnc_ls(), file_kvs_fnc_ps(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), file_kvs_fnc_readLines(), file_kvs_fnc_rootdir(), file_kvs_fnc_size(), file_kvs_fnc_type(), KVSM_REGISTER_FUNCTION, and KVSM_REGISTER_SIMPLE_COMMAND.