KVIrc: src/modules/action/libkviaction.cpp File Reference
libkviaction.cpp File Reference
#include "KviModule.h"
#include "KviAction.h"
#include "KviActionManager.h"
#include "KviLocale.h"
#include "KviQString.h"
#include "KviParameterList.h"
#include "KviCommandFormatter.h"
#include "KviError.h"
#include "kvi_out.h"
#include "KviIconManager.h"
#include "KviControlCodes.h"
#include "KviKvsUserAction.h"
#include "KviKvsScript.h"
Functions
static bool action_kvs_cmd_create (KviKvsModuleCallbackCommandCall *c)
static bool action_kvs_cmd_destroy (KviKvsModuleCommandCall *c)
static bool action_kvs_cmd_disable (KviKvsModuleCommandCall *c)
static bool action_kvs_cmd_enable (KviKvsModuleCommandCall *c)
static bool action_kvs_cmd_list (KviKvsModuleCommandCall *c)
static bool action_kvs_cmd_trigger (KviKvsModuleCommandCall *c)
static bool action_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool action_kvs_fnc_isEnabled (KviKvsModuleFunctionCall *c)
static bool action_module_cleanup (KviModule *)
static bool action_module_init (KviModule *m)
Function Documentation
static bool action_kvs_cmd_create (KviKvsModuleCallbackCommandCall * c) static
References __tr2qs, a, KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), KviKvsUserAction::createInstance(), KviAction::EnableAtLogin, KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviActionManager::getAction(), KviKvsSwitchList::getAsStringIfExisting(), KviKvsModuleCallbackCommandCall::getParameterCode(), KviActionManager::instance(), KviAction::isKviUserActionNeverOverrideThis(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETER_IGNORED, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviAction::NeedsConnection, KviAction::NeedsContext, KviActionManager::registerAction(), KviAction::suicide(), KviKvsModuleCommandCall::switches(), KviAction::validateFlags(), KviKvsRunTimeCall::warning(), KviAction::WindowChannel, KviAction::WindowConsole, KviAction::WindowDccChat, KviAction::WindowOnlyIfUsersSelected, and KviAction::WindowQuery.
Referenced by action_module_init().
static bool action_kvs_cmd_destroy (KviKvsModuleCommandCall * c) static
References __tr2qs, a, KviKvsSwitchList::find(), KviActionManager::getAction(), KviActionManager::instance(), KviAction::isKviUserActionNeverOverrideThis(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviAction::suicide(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by action_module_init().
static bool action_kvs_cmd_disable (KviKvsModuleCommandCall * c) static
References __tr2qs, a, KviKvsSwitchList::find(), KviActionManager::getAction(), KviActionManager::instance(), KviAction::isEnabled(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviAction::setEnabled(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by action_module_init().
static bool action_kvs_cmd_enable (KviKvsModuleCommandCall * c) static
References __tr2qs, a, KviKvsSwitchList::find(), KviActionManager::getAction(), KviActionManager::instance(), KviAction::isEnabled(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviAction::setEnabled(), KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by action_module_init().
static bool action_kvs_cmd_list (KviKvsModuleCommandCall * c) static
References __tr2qs, a, KviControlCodes::Bold, KviPointerHashTableIterator< Key, T >::current(), KviActionManager::instance(), KVI_OUT_VERBOSE, KviWindow::output(), and KviKvsRunTimeCall::window().
Referenced by action_module_init().
static bool action_kvs_cmd_trigger (KviKvsModuleCommandCall * c) static
References __tr2qs, a, KviAction::activate(), KviKvsSwitchList::find(), KviActionManager::getAction(), KviActionManager::instance(), KviAction::isEnabled(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::warning().
Referenced by action_module_init().
static bool action_kvs_fnc_exists (KviKvsModuleFunctionCall * c) static
References getAction(), KviActionManager::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by action_module_init().
static bool action_kvs_fnc_isEnabled (KviKvsModuleFunctionCall * c) static
References a, KviActionManager::getAction(), KviActionManager::instance(), KviAction::isEnabled(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by action_module_init().
static bool action_module_cleanup (KviModule *) static
static bool action_module_init (KviModule * m) static
References action_kvs_cmd_create(), action_kvs_cmd_destroy(), action_kvs_cmd_disable(), action_kvs_cmd_enable(), action_kvs_cmd_list(), action_kvs_cmd_trigger(), action_kvs_fnc_exists(), action_kvs_fnc_isEnabled(), KVSM_REGISTER_CALLBACK_COMMAND, KVSM_REGISTER_FUNCTION, and KVSM_REGISTER_SIMPLE_COMMAND.