KVIrc: src/modules/help/libkvihelp.cpp File Reference
src/modules/help/libkvihelp.cpp File Reference
#include "HelpWidget.h"
#include "HelpWindow.h"
#include "HelpIndex.h"
#include "KviLocale.h"
#include "KviModule.h"
#include "KviFileUtils.h"
#include "kvi_sourcesdate.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include <QDir>
#include <QFileInfo>
#include <QSplitter>
Functions
static bool help_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool help_module_can_unload (KviModule *)
static bool help_module_cleanup (KviModule *)
static bool help_module_init (KviModule *m)
Variables
HelpIndex * g_pDocIndex = 0
KviPointerList< HelpWidget > * g_pHelpWidgetList = 0
KviPointerList< HelpWindow > * g_pHelpWindowList = 0
Function Documentation
static bool help_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviMainWindow::addWindow(), HelpIndex::documentList(), f, KviFileUtils::fileExists(), KviKvsSwitchList::find(), g_pApp, g_pMainWindow, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviApplication::Help, i, KVI_SOURCES_DATE, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, HelpIndex::makeIndex(), HelpIndex::readDict(), KviMainWindow::splitter(), KviKvsModuleCommandCall::switches(), HelpWindow::textBrowser(), HelpWidget::textBrowser(), HelpIndex::titlesList(), w, and HelpIndex::writeDict().
Referenced by help_module_init().
static bool help_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool help_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first(), g_pDocIndex, g_pHelpWidgetList, and g_pHelpWindowList.
static bool help_module_init (KviModule * m) [static]
References g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviApplication::Help, help_kvs_cmd_open(), KVI_SOURCES_DATE, KVSM_REGISTER_SIMPLE_COMMAND, KviPointerList< T >::setAutoDelete(), HelpIndex::setDictionaryFile(), and HelpIndex::setDocListFile().
Variable Documentation
HelpIndex* g_pDocIndex = 0
Referenced by help_module_cleanup().
KviPointerList<HelpWidget>* g_pHelpWidgetList = 0
Referenced by help_module_cleanup().
KviPointerList<HelpWindow>* g_pHelpWindowList = 0
Referenced by help_module_cleanup().