KVIrc: src/modules/config/libkviconfig.cpp File Reference
src/modules/config/libkviconfig.cpp File Reference
#include "KviModule.h"
#include "KviCString.h"
#include "KviConfigurationFile.h"
#include "KviFileUtils.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviPointerHashTable.h"
Functions
static bool config_kvs_cmd_clear (KviKvsModuleCommandCall *c)
static bool config_kvs_cmd_clearsection (KviKvsModuleCommandCall *c)
static bool config_kvs_cmd_close (KviKvsModuleCommandCall *c)
static bool config_kvs_cmd_flush (KviKvsModuleCommandCall *c)
static bool config_kvs_cmd_setsection (KviKvsModuleCommandCall *c)
static bool config_kvs_cmd_write (KviKvsModuleCommandCall *c)
static bool config_kvs_fnc_filelist (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_filename (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_hassection (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_id (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_keylist (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_open (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_read (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_readonly (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_section (KviKvsModuleFunctionCall *c)
static bool config_kvs_fnc_sectionlist (KviKvsModuleFunctionCall *c)
static bool config_module_can_unload (KviModule *)
static bool config_module_cleanup (KviModule *)
static bool config_module_init (KviModule *m)
Variables
static int g_iNextConfigId = 0
static KviPointerHashTable
< QString,
KviConfigurationFile > * g_pConfigDict = 0
Function Documentation
static bool config_kvs_cmd_clear (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviConfigurationFile::clear(), KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_cmd_clearsection (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviConfigurationFile::clearGroup(), KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_cmd_close (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviConfigurationFile::dirty(), KviConfigurationFile::fileName(), KviPointerHashTable< Key, T >::find(), KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviConfigurationFile::readOnly(), KviPointerHashTable< Key, T >::remove(), KviConfigurationFile::sync(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_cmd_flush (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviConfigurationFile::readOnly(), KviConfigurationFile::sync(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_cmd_setsection (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviConfigurationFile::setGroup(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_cmd_write (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviConfigurationFile::clearKey(), KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::warning(), and KviConfigurationFile::writeEntry().
Referenced by config_module_init().
static bool config_kvs_fnc_filelist (KviKvsModuleFunctionCall * c) [static]
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by config_module_init().
static bool config_kvs_fnc_filename (KviKvsModuleFunctionCall * c) [static]
References KviConfigurationFile::fileName(), KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by config_module_init().
static bool config_kvs_fnc_hassection (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviPointerHashTable< Key, T >::find(), KviConfigurationFile::hasGroup(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_fnc_id (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), KviApplication::ConfigScripts, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviQString::equalCI(), KviConfigurationFile::fileName(), g_pApp, KviApplication::getLocalKvircDirectory(), KviFileUtils::isAbsolutePath(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by config_module_init().
static bool config_kvs_fnc_keylist (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, KviConfigurationFile::dict(), KviPointerHashTable< Key, T >::find(), KviConfigurationFile::group(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_fnc_open (KviKvsModuleFunctionCall * c) [static]
References KviFileUtils::adjustFilePath(), KviApplication::ConfigScripts, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviQString::equalCI(), KviConfigurationFile::fileName(), g_iNextConfigId, g_pApp, KviApplication::getLocalKvircDirectory(), KviPointerHashTable< Key, T >::insert(), KviFileUtils::isAbsolutePath(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviConfigurationFile::Read, KviConfigurationFile::readOnly(), KviConfigurationFile::ReadWrite, KviKvsModuleFunctionCall::returnValue(), KviConfigurationFile::setReadOnly(), KviKvsVariant::setString(), and KviConfigurationFile::Write.
Referenced by config_module_init().
static bool config_kvs_fnc_read (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviPointerHashTable< Key, T >::find(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviConfigurationFile::readEntry(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_fnc_readonly (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviConfigurationFile::readOnly(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), KviKvsVariant::setInteger(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_fnc_section (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviPointerHashTable< Key, T >::find(), KviConfigurationFile::group(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_kvs_fnc_sectionlist (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviConfigurationFile::dict(), KviPointerHashTable< Key, T >::find(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by config_module_init().
static bool config_module_can_unload (KviModule *) [static]
References KviPointerHashTable< Key, T >::isEmpty().
static bool config_module_cleanup (KviModule *) [static]
References g_pConfigDict.
static bool config_module_init (KviModule * m) [static]
References config_kvs_cmd_clear(), config_kvs_cmd_clearsection(), config_kvs_cmd_close(), config_kvs_cmd_flush(), config_kvs_cmd_setsection(), config_kvs_cmd_write(), config_kvs_fnc_filelist(), config_kvs_fnc_filename(), config_kvs_fnc_hassection(), config_kvs_fnc_id(), config_kvs_fnc_keylist(), config_kvs_fnc_open(), config_kvs_fnc_read(), config_kvs_fnc_readonly(), config_kvs_fnc_section(), config_kvs_fnc_sectionlist(), KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, and KviPointerHashTable< Key, T >::setAutoDelete().
Variable Documentation
int g_iNextConfigId = 0 [static]
Referenced by config_kvs_fnc_open().
KviPointerHashTable<QString,KviConfigurationFile>* g_pConfigDict = 0 [static]
Referenced by config_module_cleanup().