KVIrc: src/modules/tmphighlight/libkvitmphighlight.cpp File Reference
src/modules/tmphighlight/libkvitmphighlight.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviChannelWindow.h"
Functions
static bool tmphighlight_kvs_cmd_addchannel (KviKvsModuleCommandCall *c)
static bool tmphighlight_kvs_cmd_addnick (KviKvsModuleCommandCall *c)
static bool tmphighlight_kvs_cmd_removechannel (KviKvsModuleCommandCall *c)
static bool tmphighlight_kvs_cmd_removenick (KviKvsModuleCommandCall *c)
static bool tmphighlight_kvs_fnc_ischannelhighlighted (KviKvsModuleFunctionCall *c)
static bool tmphighlight_kvs_fnc_isnickhighlighted (KviKvsModuleFunctionCall *c)
static bool tmphighlight_module_can_unload (KviModule *)
static bool tmphighlight_module_cleanup (KviModule *)
static bool tmphighlight_module_init (KviModule *m)
Function Documentation
static bool tmphighlight_kvs_cmd_addchannel (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviWindow::Channel, KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsVariantList::count(), KviKvsRunTimeContext::errorNoIrcContext(), KviApplication::findWindow(), g_pApp, KviConsoleWindow::isNotConnected(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::parameterList(), KviWindow::type(), KviKvsRunTimeCall::warning(), KviKvsRunTimeCall::window(), and KviWindow::windowName().
Referenced by tmphighlight_module_init().
static bool tmphighlight_kvs_cmd_addnick (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviWindow::Channel, KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsRunTimeContext::errorNoIrcContext(), KviConsoleWindow::isNotConnected(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::type(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by tmphighlight_module_init().
static bool tmphighlight_kvs_cmd_removechannel (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviWindow::Channel, KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsVariantList::count(), KviKvsRunTimeContext::errorNoIrcContext(), KviApplication::findWindow(), g_pApp, KviConsoleWindow::isNotConnected(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::parameterList(), KviWindow::type(), KviKvsRunTimeCall::warning(), KviKvsRunTimeCall::window(), and KviWindow::windowName().
Referenced by tmphighlight_module_init().
static bool tmphighlight_kvs_cmd_removenick (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviWindow::Channel, KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsRunTimeContext::errorNoIrcContext(), KviConsoleWindow::isNotConnected(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::type(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by tmphighlight_module_init().
static bool tmphighlight_kvs_fnc_ischannelhighlighted (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviWindow::Channel, KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsVariantList::count(), KviKvsRunTimeContext::errorNoIrcContext(), KviApplication::findWindow(), g_pApp, KviConsoleWindow::isNotConnected(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::parameterList(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), KviWindow::type(), KviKvsRunTimeCall::warning(), KviKvsRunTimeCall::window(), and KviWindow::windowName().
Referenced by tmphighlight_module_init().
static bool tmphighlight_kvs_fnc_isnickhighlighted (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviWindow::Channel, KviWindow::console(), KviKvsRunTimeCall::context(), KviKvsRunTimeContext::errorNoIrcContext(), KviConsoleWindow::isNotConnected(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), KviWindow::type(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by tmphighlight_module_init().
static bool tmphighlight_module_can_unload (KviModule *) [static]
static bool tmphighlight_module_cleanup (KviModule *) [static]
static bool tmphighlight_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, tmphighlight_kvs_cmd_addchannel(), tmphighlight_kvs_cmd_addnick(), tmphighlight_kvs_cmd_removechannel(), tmphighlight_kvs_cmd_removenick(), tmphighlight_kvs_fnc_ischannelhighlighted(), and tmphighlight_kvs_fnc_isnickhighlighted().