KVIrc: src/modules/mediaplayer/libkvimediaplayer.cpp File Reference
libkvimediaplayer.cpp File Reference
#include "MpInterface.h"
#include "MpAmipInterface.h"
#include "MpMprisInterface.h"
#include "MpWinampInterface.h"
#include "MpXmmsInterface.h"
#include "KviModule.h"
#include "KviOptions.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include <QUrl>
Macros
#define MP_KVS_COMMAND(__name) static bool mediaplayer_kvs_cmd_##__name(KviKvsModuleCommandCall * c)
#define MP_KVS_FAIL_ON_NO_INTERFACE
#define MP_KVS_FUNCTION(__name) static bool mediaplayer_kvs_fnc_##__name(KviKvsModuleFunctionCall * c)
#define MP_KVS_REGCMD(__name, __stringname) KVSM_REGISTER_SIMPLE_COMMAND(m, __stringname, mediaplayer_kvs_cmd_##__name)
#define MP_KVS_REGFNC(__name, __stringname) KVSM_REGISTER_FUNCTION(m, __stringname, mediaplayer_kvs_fnc_##__name)
#define MP_KVS_SIMPLE_BOOL_FUNCTION(__name, __ifacecommand)
#define MP_KVS_SIMPLE_COMMAND(__name, __ifacecommand)
#define MP_KVS_SIMPLE_INT_FUNCTION(__name, __ifacecommand)
#define MP_KVS_SIMPLE_STRING_FUNCTION(__name, __ifacecommand)
Functions
static MpInterface * auto_detect_player (KviWindow *pOut=nullptr)
static bool mediaplayer_module_can_unload (KviModule *)
static bool mediaplayer_module_cleanup (KviModule *)
static bool mediaplayer_module_ctrl (KviModule *, const char *operation, void *param)
static bool mediaplayer_module_init (KviModule *m)
MP_KVS_COMMAND (detect)
MP_KVS_COMMAND (setPlayer)
MP_KVS_COMMAND (playMrl)
MP_KVS_COMMAND (amipExec)
MP_KVS_COMMAND (jumpTo)
MP_KVS_COMMAND (setVol)
MP_KVS_COMMAND (setPlayListPos)
MP_KVS_COMMAND (setEqData)
MP_KVS_COMMAND (setRepeat)
MP_KVS_COMMAND (setShuffle)
MP_KVS_FUNCTION (player)
MP_KVS_FUNCTION (playerList)
MP_KVS_FUNCTION (getEqData)
MP_KVS_FUNCTION (localFile)
MP_KVS_FUNCTION (amipEval)
MP_KVS_FUNCTION (status)
Variables
static KviPointerList
< MpInterfaceDescriptor > * g_pDescriptorList = nullptr
static MpInterface * g_pMPInterface = nullptr
Macro Definition Documentation
#define MP_KVS_COMMAND (__name) static bool mediaplayer_kvs_cmd_##__name(KviKvsModuleCommandCall * c)
#define MP_KVS_FAIL_ON_NO_INTERFACE
Value:
if(!g_pMPInterface)                                                                                       \
        {                                                                                                         \
        c->warning(__tr2qs_ctx("No mediaplayer interface selected. Try /mediaplayer.detect", "mediaplayer")); \
                return true;                                                                                          \
        }
Referenced by MP_KVS_COMMAND(), and MP_KVS_FUNCTION().
#define MP_KVS_FUNCTION (__name) static bool mediaplayer_kvs_fnc_##__name(KviKvsModuleFunctionCall * c)
#define MP_KVS_REGCMD (__name, __stringname) KVSM_REGISTER_SIMPLE_COMMAND(m, __stringname, mediaplayer_kvs_cmd_##__name)
Referenced by mediaplayer_module_init().
#define MP_KVS_REGFNC (__name, __stringname) KVSM_REGISTER_FUNCTION(m, __stringname, mediaplayer_kvs_fnc_##__name)
Referenced by mediaplayer_module_init().
#define MP_KVS_SIMPLE_BOOL_FUNCTION (__name, __ifacecommand)
Value:
MP_KVS_FUNCTION(__name)                                 \
        {                                                       \
                MP_KVS_FAIL_ON_NO_INTERFACE                         \
                bool bRet = g_pMPInterface->__ifacecommand();       \
        c->returnValue()->setBoolean(bRet);                 \
                return true;                                        \
        }
#define MP_KVS_SIMPLE_COMMAND (__name, __ifacecommand)
Value:
MP_KVS_COMMAND(__name)                                                                                                              \
        {                                                                                                                                   \
        KVSM_PARAMETERS_BEGIN(c)                                                                                                        \
        KVSM_PARAMETERS_END(c)                                                                                                          \
                                                                                                                                        \
        MP_KVS_FAIL_ON_NO_INTERFACE                                                                                                     \
                                                                                                                                        \
        if(!g_pMPInterface->__ifacecommand())                                                                                           \
                {                                                                                                                               \
            if(!c->hasSwitch('q', "quiet"))                                                                                             \
                        {                                                                                                                           \
                c->warning(__tr2qs_ctx("The selected media player interface failed to execute the requested function", "mediaplayer")); \
                                QString tmp = __tr2qs_ctx("Last interface error: ", "mediaplayer");                                                     \
                                tmp += g_pMPInterface->lastError();                                                                                     \
                c->warning(tmp);                                                                                                        \
                        }                                                                                                                           \
                }                                                                                                                               \
                return true;                                                                                                                    \
        }
#define MP_KVS_SIMPLE_INT_FUNCTION (__name, __ifacecommand)
Value:
MP_KVS_FUNCTION(__name)                                \
        {                                                      \
                MP_KVS_FAIL_ON_NO_INTERFACE                        \
                int iRet = g_pMPInterface->__ifacecommand();       \
        c->returnValue()->setInteger(iRet);                \
                return true;                                       \
        }
#define MP_KVS_SIMPLE_STRING_FUNCTION (__name, __ifacecommand)
Value:
MP_KVS_FUNCTION(__name)                                   \
        {                                                         \
                MP_KVS_FAIL_ON_NO_INTERFACE                           \
                QString szRet = g_pMPInterface->__ifacecommand();     \
        c->returnValue()->setString(szRet);                   \
                return true;                                          \
        }
Function Documentation
static MpInterface* auto_detect_player (KviWindow * pOut = nullptr) static
References __tr2qs_ctx(), d, MpInterface::detect(), KviPointerList< T >::first(), i, MpInterfaceDescriptor::instance(), KVI_OPTION_STRING, KVI_OUT_MULTIMEDIA, KviOption_stringPreferredMediaPlayer, MpInterfaceDescriptor::name(), and KviPointerList< T >::next().
Referenced by mediaplayer_module_ctrl(), mediaplayer_module_init(), and MP_KVS_COMMAND().
static bool mediaplayer_module_can_unload (KviModule *) static
static bool mediaplayer_module_cleanup (KviModule *) static
References g_pDescriptorList.
static bool mediaplayer_module_ctrl (KviModule * , const char * operation, void * param) static
References auto_detect_player(), d, KviPointerList< T >::first(), kvi_strEqualCI(), l, and KviPointerList< T >::next().
static bool mediaplayer_module_init (KviModule * m) static
References KviPointerList< T >::append(), auto_detect_player(), d, KviPointerList< T >::first(), KVI_OPTION_STRING, KviOption_stringPreferredMediaPlayer, MP_CREATE_DESCRIPTOR, MP_KVS_REGCMD, MP_KVS_REGFNC, KviPointerList< T >::next(), quit(), and KviPointerList< T >::setAutoDelete().
MP_KVS_COMMAND (detect)
References auto_detect_player(), and c.
MP_KVS_COMMAND (setPlayer)
References c, d, KviPointerList< T >::first(), KVI_OPTION_STRING, KviOption_stringPreferredMediaPlayer, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviPointerList< T >::next().
MP_KVS_COMMAND (playMrl)
References __tr2qs_ctx(), c, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::playMrl().
MP_KVS_COMMAND (amipExec)
References __tr2qs_ctx(), MpInterface::amipExec(), c, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), and MP_KVS_FAIL_ON_NO_INTERFACE.
MP_KVS_COMMAND (jumpTo)
References __tr2qs_ctx(), c, MpInterface::jumpTo(), KVS_PT_INT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), and MP_KVS_FAIL_ON_NO_INTERFACE.
MP_KVS_COMMAND (setVol)
References __tr2qs_ctx(), c, KVS_PT_INT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::setVol().
MP_KVS_COMMAND (setPlayListPos)
References __tr2qs_ctx(), c, KVS_PT_INT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::setPlayListPos().
MP_KVS_COMMAND (setEqData)
References __tr2qs_ctx(), c, KVS_PT_INT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::setEqData().
MP_KVS_COMMAND (setRepeat)
References __tr2qs_ctx(), c, KVS_PT_BOOL, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::setRepeat().
MP_KVS_COMMAND (setShuffle)
References __tr2qs_ctx(), c, KVS_PT_BOOL, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::setShuffle().
MP_KVS_FUNCTION (player)
References c, KVI_OPTION_STRING, and KviOption_stringPreferredMediaPlayer.
MP_KVS_FUNCTION (playerList)
References c, d, KviPointerList< T >::first(), KviPointerList< T >::next(), pArray, and KviKvsArray::set().
MP_KVS_FUNCTION (getEqData)
References __tr2qs_ctx(), c, MpInterface::getEqData(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MpInterface::lastError(), and MP_KVS_FAIL_ON_NO_INTERFACE.
MP_KVS_FUNCTION (localFile)
References c, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MP_KVS_FAIL_ON_NO_INTERFACE, and MpInterface::mrl().
MP_KVS_FUNCTION (amipEval)
References MpInterface::amipEval(), c, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and MP_KVS_FAIL_ON_NO_INTERFACE.
MP_KVS_FUNCTION (status)
References c, MP_KVS_FAIL_ON_NO_INTERFACE, MpInterface::Paused, MpInterface::Playing, MpInterface::status(), and MpInterface::Stopped.
Variable Documentation
KviPointerList<MpInterfaceDescriptor>* g_pDescriptorList = nullptr static
Referenced by mediaplayer_module_cleanup().
MpInterface* g_pMPInterface = nullptr static