KVIrc: src/modules/mircimport/libkvimircimport.cpp File Reference
src/modules/mircimport/libkvimircimport.cpp File Reference
#include "libkvimircimport.h"
#include "KviModule.h"
#include "KviFileDialog.h"
#include "KviFileUtils.h"
#include "kvi_fileextensions.h"
#include "KviLocale.h"
#include "KviConfigurationFile.h"
#include "KviApplication.h"
#include "KviTalVBox.h"
#include <QMessageBox>
#include <QDir>
#include <QPushButton>
#include "libkvimircimport.moc"
Defines
#define KVI_WWWMIRCCOUK_SERVERSINI "http://www.mirc.co.uk/servers.ini"
Functions
static KviModuleExtension * mircimport_local_filter_alloc (KviModuleExtensionAllocStruct *s)
static bool mircimport_module_can_unload (KviModule *)
static bool mircimport_module_cleanup (KviModule *)
static bool mircimport_module_init (KviModule *m)
static KviModuleExtension * mircimport_remote_filter_alloc (KviModuleExtensionAllocStruct *s)
Variables
KviMircServersIniImport * g_pMircServersIniImport = 0
KviRemoteMircServersIniImport * g_pRemoteMircServersIniImport = 0
Define Documentation
#define KVI_WWWMIRCCOUK_SERVERSINI "http://www.mirc.co.uk/servers.ini"
Referenced by KviRemoteMircServerImportWizard::KviRemoteMircServerImportWizard(), and KviRemoteMircServerImportWizard::start().
Function Documentation
static KviModuleExtension* mircimport_local_filter_alloc (KviModuleExtensionAllocStruct * s) [static]
References g_pMircServersIniImport, and _KviModuleExtensionAllocStructTag::pDescriptor.
Referenced by mircimport_module_init().
static bool mircimport_module_can_unload (KviModule *) [static]
static bool mircimport_module_cleanup (KviModule *) [static]
References g_pMircServersIniImport, and g_pRemoteMircServersIniImport.
static bool mircimport_module_init (KviModule * m) [static]
References __tr, d, KviApplication::findImage(), g_pApp, mircimport_local_filter_alloc(), mircimport_remote_filter_alloc(), KviModule::registerExtension(), and KviModuleExtensionDescriptor::setIcon().
static KviModuleExtension* mircimport_remote_filter_alloc (KviModuleExtensionAllocStruct * s) [static]
References g_pRemoteMircServersIniImport, and _KviModuleExtensionAllocStructTag::pDescriptor.
Referenced by mircimport_module_init().
Variable Documentation
KviMircServersIniImport* g_pMircServersIniImport = 0
Referenced by mircimport_local_filter_alloc(), and mircimport_module_cleanup().
KviRemoteMircServersIniImport* g_pRemoteMircServersIniImport = 0
Referenced by mircimport_module_cleanup(), and mircimport_remote_filter_alloc().