KVIrc: src/modules/sharedfile/libkvisharedfile.cpp File Reference
src/modules/sharedfile/libkvisharedfile.cpp File Reference
#include "KviModule.h"
#include "KviSharedFilesManager.h"
#include "KviIrcMask.h"
#include "KviFileUtils.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviControlCodes.h"
#include "KviWindow.h"
#include "KviMainWindow.h"
#include "KviPointerHashTable.h"
#include <time.h>
Functions
static bool sharedfile_kvs_cmd_add (KviKvsModuleCommandCall *c)
static bool sharedfile_kvs_cmd_clear (KviKvsModuleCommandCall *)
static bool sharedfile_kvs_cmd_list (KviKvsModuleCommandCall *c)
static bool sharedfile_kvs_cmd_remove (KviKvsModuleCommandCall *c)
static bool sharedfile_module_can_unload (KviModule *)
static bool sharedfile_module_cleanup (KviModule *)
static bool sharedfile_module_init (KviModule *m)
Variables
KVIRC_API KviSharedFilesManager * g_pSharedFilesManager
Function Documentation
static bool sharedfile_kvs_cmd_add (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviSharedFilesManager::addSharedFile(), KviQString::cutToLast(), KviKvsSwitchList::find(), g_pSharedFilesManager, KviFileUtils::isReadable(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcMask::mask(), n, KviKvsModuleCommandCall::switches(), szm, u, v, and KviKvsRunTimeCall::warning().
Referenced by sharedfile_module_init().
static bool sharedfile_kvs_cmd_clear (KviKvsModuleCommandCall *) [static]
References KviSharedFilesManager::clear(), and g_pSharedFilesManager.
Referenced by sharedfile_module_init().
static bool sharedfile_kvs_cmd_list (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviControlCodes::Bold, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), g_pSharedFilesManager, KVI_OUT_NONE, l, o, KviWindow::output(), KviWindow::outputNoFmt(), KviSharedFilesManager::sharedFileListDict(), and KviKvsRunTimeCall::window().
Referenced by sharedfile_module_init().
static bool sharedfile_kvs_cmd_remove (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), g_pSharedFilesManager, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviSharedFilesManager::removeSharedFile(), and KviKvsRunTimeCall::warning().
Referenced by sharedfile_module_init().
static bool sharedfile_module_can_unload (KviModule *) [static]
static bool sharedfile_module_cleanup (KviModule *) [static]
static bool sharedfile_module_init (KviModule * m) [static]
References KVSM_REGISTER_SIMPLE_COMMAND, sharedfile_kvs_cmd_add(), sharedfile_kvs_cmd_clear(), sharedfile_kvs_cmd_list(), and sharedfile_kvs_cmd_remove().
Variable Documentation
KVIRC_API KviSharedFilesManager* g_pSharedFilesManager