KVIrc: src/modules/url/libkviurl.cpp File Reference
libkviurl.cpp File Reference
#include "libkviurl.h"
#include "KviModule.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviMenuBar.h"
#include "KviMdiManager.h"
#include "KviInternalCommand.h"
#include "KviIconManager.h"
#include "KviAction.h"
#include "KviActionManager.h"
#include "KviWindowListBase.h"
#include "KviPointerList.h"
#include "KviKvsEventManager.h"
#include "KviWindow.h"
#include "KviOptions.h"
#include "KviQString.h"
#include "kvi_out.h"
#include <QFileDialog>
#include <QMessageBox>
#include <QCursor>
#include <QDateTime>
#include <QHeaderView>
#include <QTextStream>
#include <QMouseEvent>
#include <QPainter>
#include <QMenu>
Classes
struct _UrlDlgList
Macros
#define KVI_URL_EXTENSION_NAME "URL module extenstion"
Typedefs
typedef struct _UrlDlgList UrlDlgList
Functions
int check_url (KviWindow *w, const QString &szUrl)
UrlDlgList * findFrame ()
void loadBanList ()
void loadUrlList ()
void saveBanList ()
void saveUrlList ()
static bool url_kvs_cmd_config (KviKvsModuleCommandCall *)
static bool url_kvs_cmd_list (KviKvsModuleCommandCall *)
static bool url_module_can_unload (KviModule *)
static bool url_module_cleanup (KviModule *)
void url_module_config ()
void url_module_help ()
static bool url_module_init (KviModule *m)
bool urllist_module_event_onUrl (KviKvsModuleEventCall *c)
Variables
KviPointerList< QString > * g_pBanList
const char * g_pBanListFilename = "/list.kviban"
ConfigDialog * g_pConfigDialog
KviPointerList< KviUrl > * g_pList
KviPointerList< UrlDlgList > * g_pUrlDlgList
const char * g_pUrlListFilename = "/list.kviurl"
QString szConfigPath
Macro Definition Documentation
#define KVI_URL_EXTENSION_NAME "URL module extenstion"
Typedef Documentation
typedef struct _UrlDlgList UrlDlgList
Function Documentation
int check_url (KviWindow * w, const QString & szUrl)
References KviPointerList< T >::first(), i, KviPointerList< T >::next(), KviWindow::plainTextCaption(), szUrl, and u.
Referenced by urllist_module_event_onUrl().
UrlDlgList * findFrame ()
References KviPointerList< T >::append(), KviPointerList< T >::current(), _UrlDlgList::dlg, KviPointerList< T >::first(), and _UrlDlgList::menu_id.
Referenced by url_kvs_cmd_list(), and UrlDialog::~UrlDialog().
void loadBanList ()
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviApplication::ConfigPlugins, g_pApp, g_pBanListFilename, KviApplication::getLocalKvircDirectory(), and i.
Referenced by BanFrame::BanFrame(), and url_module_init().
void loadUrlList ()
References KviPointerList< T >::append(), KviPointerList< T >::clear(), KviApplication::ConfigPlugins, KviPointerList< T >::first(), g_pApp, g_pUrlListFilename, KviApplication::getLocalKvircDirectory(), i, KviPointerList< T >::next(), and KviUrl::url().
Referenced by UrlDialog::loadList(), and url_module_init().
void saveBanList ()
References KviApplication::ConfigPlugins, KviPointerList< T >::count(), KviPointerList< T >::first(), g_pApp, g_pBanListFilename, KviApplication::getLocalKvircDirectory(), and KviPointerList< T >::next().
Referenced by BanFrame::saveBans().
void saveUrlList ()
References KviApplication::ConfigPlugins, KviPointerList< T >::count(), KviPointerList< T >::first(), g_pApp, g_pUrlListFilename, KviApplication::getLocalKvircDirectory(), and KviPointerList< T >::next().
Referenced by UrlDialog::saveList(), and url_module_cleanup().
static bool url_kvs_cmd_config (KviKvsModuleCommandCall *) static
Referenced by url_module_init().
static bool url_kvs_cmd_list (KviKvsModuleCommandCall *) static
References UrlDialog::addUrl(), KviMainWindow::addWindow(), _UrlDlgList::dlg, findFrame(), KviPointerList< T >::first(), g_pMainWindow, and KviPointerList< T >::next().
Referenced by url_module_init().
static bool url_module_can_unload (KviModule *) static
static bool url_module_cleanup (KviModule *) static
References KviPointerList< T >::first(), g_pBanList, g_pList, g_pUrlDlgList, KviPointerList< T >::next(), KviConfigurationFile::Read, KviConfigurationFile::readBoolEntry(), saveUrlList(), KviConfigurationFile::setGroup(), and szConfigPath.
void url_module_config ()
void url_module_help ()
static bool url_module_init (KviModule * m) static
References KviPointerList< T >::append(), KviApplication::ConfigPlugins, _UrlDlgList::dlg, g_pApp, KviApplication::getLocalKvircDirectory(), KviEvent_OnURL, KVSM_REGISTER_SIMPLE_COMMAND, KviKvsModuleInterface::kvsRegisterAppEventHandler(), loadBanList(), loadUrlList(), KviPointerList< T >::setAutoDelete(), szConfigPath, url_kvs_cmd_config(), url_kvs_cmd_list(), and urllist_module_event_onUrl().
bool urllist_module_event_onUrl (KviKvsModuleEventCall * c)
References KviPointerList< T >::append(), KviKvsVariant::asString(), check_url(), d, KviPointerList< T >::first(), KviKvsRunTimeCall::firstParam(), KviPointerList< T >::next(), KviWindow::plainTextCaption(), szUrl, KviUrl::url(), and KviKvsRunTimeCall::window().
Referenced by url_module_init().
Variable Documentation
KviPointerList<QString>* g_pBanList
Referenced by url_module_cleanup().
const char* g_pBanListFilename = "/list.kviban"
Referenced by loadBanList(), and saveBanList().
ConfigDialog* g_pConfigDialog
KviPointerList<KviUrl>* g_pList
Referenced by url_module_cleanup().
KviPointerList<UrlDlgList>* g_pUrlDlgList
Referenced by url_module_cleanup().
const char* g_pUrlListFilename = "/list.kviurl"
Referenced by loadUrlList(), and saveUrlList().
QString szConfigPath
Referenced by ConfigDialog::acceptbtn(), ConfigDialog::ConfigDialog(), url_module_cleanup(), url_module_init(), and UrlDialog::UrlDialog().