KVIrc: src/modules/str/libkvistr.cpp File Reference
src/modules/str/libkvistr.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviControlCodes.h"
#include "KviQString.h"
#include "kvi_debug.h"
#include "kvi_settings.h"
#include "KviMemory.h"
#include "KviKvsArrayCast.h"
#include "KviOptions.h"
#include <QRegExp>
#include <QClipboard>
#include <QCryptographicHash>
Defines
#define INCREMENT_MEM
#define INCREMENT_MEM_BY(numchars)
#define MEMINCREMENT 32
Functions
static bool str_kvs_cmd_toClipboard (KviKvsModuleCommandCall *c)
static bool str_kvs_fnc_append (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_charsum (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_chop (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_cmp (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_contains (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_digest (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_equal (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_evpSign (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_evpVerify (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_find (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_findfirst (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_findlast (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_fromclipboard (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_grep (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_insert (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_isempty (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_isnumber (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_isunsignednumber (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_join (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_left (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_lefttofirst (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_lefttolast (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_len (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_localelowcase (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_localeupcase (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_lowcase (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_match (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_mid (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_prepend (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_printf (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_replace (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_right (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_rightfromfirst (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_rightfromlast (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_section (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_split (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_strip (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_stripcolors (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_stripleft (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_stripright (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_token (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_upcase (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_urlencode (KviKvsModuleFunctionCall *c)
static bool str_kvs_fnc_word (KviKvsModuleFunctionCall *c)
static bool str_module_cleanup (KviModule *)
static bool str_module_init (KviModule *m)
Define Documentation
#define INCREMENT_MEM
Value:
{ \
                        allocsize += MEMINCREMENT; \
                        buffer = (QChar *)KviMemory::reallocate(buffer,sizeof(QChar) * allocsize); \
                        p = buffer + reallen; \
                }
#define INCREMENT_MEM_BY (numchars)
Value:
{ \
                        allocsize += numchars + MEMINCREMENT; \
                        buffer = (QChar *)KviMemory::reallocate(buffer,sizeof(QChar) * allocsize); \
                        p = buffer + reallen; \
                }
#define MEMINCREMENT 32
Function Documentation
static bool str_kvs_cmd_toClipboard (KviKvsModuleCommandCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by str_module_init().
static bool str_kvs_fnc_append (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_charsum (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by str_module_init().
static bool str_kvs_fnc_chop (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, n, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_cmp (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by str_module_init().
static bool str_kvs_fnc_contains (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by str_module_init().
static bool str_kvs_fnc_digest (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, i, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, NULL, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by str_module_init().
static bool str_kvs_fnc_equal (KviKvsModuleFunctionCall * c) [static]
References KviQString::equalCI(), KviQString::equalCS(), KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by str_module_init().
static bool str_kvs_fnc_evpSign (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviMemory::allocate(), f, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseSSLPrivateKey, KviOption_stringSSLPrivateKeyPass, KviOption_stringSSLPrivateKeyPath, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYCSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, NULL, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), sig, and KviKvsRunTimeCall::warning().
Referenced by str_module_init().
static bool str_kvs_fnc_evpVerify (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, f, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseSSLCertificate, KviOption_stringSSLCertificatePass, KviOption_stringSSLCertificatePath, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYCSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, NULL, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by str_module_init().
static bool str_kvs_fnc_find (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by str_module_init().
static bool str_kvs_fnc_findfirst (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by str_module_init().
static bool str_kvs_fnc_findlast (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by str_module_init().
static bool str_kvs_fnc_fromclipboard (KviKvsModuleFunctionCall * c) [static]
References KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_grep (KviKvsModuleFunctionCall * c) [static]
References a, KviKvsArrayCast::array(), KviKvsVariant::asString(), KviKvsArray::at(), i, j, KVS_PF_OPTIONAL, KVS_PT_ARRAYCAST, KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, n, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsArray::size(), and v.
Referenced by str_module_init().
static bool str_kvs_fnc_insert (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_isempty (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and v.
Referenced by str_module_init().
static bool str_kvs_fnc_isnumber (KviKvsModuleFunctionCall * c) [static]
References KviKvsVariant::asNumber(), KVS_PT_VARIANT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and v.
Referenced by str_module_init().
static bool str_kvs_fnc_isunsignednumber (KviKvsModuleFunctionCall * c) [static]
References KviKvsVariant::asNumber(), KviKvsNumber::integer(), KviKvsNumber::isInteger(), KVS_PT_VARIANT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsNumber::real(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and v.
Referenced by str_module_init().
static bool str_kvs_fnc_join (KviKvsModuleFunctionCall * c) [static]
References a, KviKvsArrayCast::array(), KviKvsVariant::asString(), KVS_PF_OPTIONAL, KVS_PT_ARRAYCAST, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and v.
Referenced by str_module_init().
static bool str_kvs_fnc_left (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_lefttofirst (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_lefttolast (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_len (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by str_module_init().
static bool str_kvs_fnc_localelowcase (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_localeupcase (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_lowcase (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviQString::lowerISO88591(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_match (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviQString::matchString(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by str_module_init().
static bool str_kvs_fnc_mid (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_prepend (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_printf (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviMemory::allocate(), KviKvsVariant::asInteger(), KviKvsVariant::asReal(), KviKvsVariant::asString(), KviKvsVariantList::first(), KviMemory::free(), INCREMENT_MEM, INCREMENT_MEM_BY, kvi_strLen, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, MEMINCREMENT, KviKvsVariantList::next(), p, KviKvsModuleFunctionCall::returnValue(), s, KviTheme::save(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by str_module_init().
static bool str_kvs_fnc_replace (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_right (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_rightfromfirst (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_rightfromlast (KviKvsModuleFunctionCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_section (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_INT, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_split (KviKvsModuleFunctionCall * c) [static]
References a, KviKvsVariantList::count(), KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::params(), KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by str_module_init().
static bool str_kvs_fnc_strip (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_stripcolors (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviControlCodes::stripControlBytes().
Referenced by str_module_init().
static bool str_kvs_fnc_stripleft (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_stripright (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_token (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, n, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_upcase (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviQString::upperISO88591().
Referenced by str_module_init().
static bool str_kvs_fnc_urlencode (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_kvs_fnc_word (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_INT, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by str_module_init().
static bool str_module_cleanup (KviModule *) [static]
static bool str_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, str_kvs_cmd_toClipboard(), str_kvs_fnc_append(), str_kvs_fnc_charsum(), str_kvs_fnc_chop(), str_kvs_fnc_cmp(), str_kvs_fnc_contains(), str_kvs_fnc_digest(), str_kvs_fnc_equal(), str_kvs_fnc_evpSign(), str_kvs_fnc_evpVerify(), str_kvs_fnc_find(), str_kvs_fnc_findfirst(), str_kvs_fnc_findlast(), str_kvs_fnc_fromclipboard(), str_kvs_fnc_grep(), str_kvs_fnc_insert(), str_kvs_fnc_isempty(), str_kvs_fnc_isnumber(), str_kvs_fnc_isunsignednumber(), str_kvs_fnc_join(), str_kvs_fnc_left(), str_kvs_fnc_lefttofirst(), str_kvs_fnc_lefttolast(), str_kvs_fnc_len(), str_kvs_fnc_localelowcase(), str_kvs_fnc_localeupcase(), str_kvs_fnc_lowcase(), str_kvs_fnc_match(), str_kvs_fnc_mid(), str_kvs_fnc_prepend(), str_kvs_fnc_printf(), str_kvs_fnc_replace(), str_kvs_fnc_right(), str_kvs_fnc_rightfromfirst(), str_kvs_fnc_rightfromlast(), str_kvs_fnc_section(), str_kvs_fnc_split(), str_kvs_fnc_strip(), str_kvs_fnc_stripcolors(), str_kvs_fnc_stripleft(), str_kvs_fnc_stripright(), str_kvs_fnc_token(), str_kvs_fnc_upcase(), str_kvs_fnc_urlencode(), and str_kvs_fnc_word().