KVIrc: src/modules/avatar/libkviavatar.cpp File Reference
libkviavatar.cpp File Reference
#include "libkviavatar.h"
#include "KviModule.h"
#include "KviFileUtils.h"
#include "KviLocale.h"
#include "KviMemory.h"
#include "KviApplication.h"
#include "KviOptions.h"
#include "KviHttpRequest.h"
#include "KviIconManager.h"
#include "KviAvatar.h"
#include "KviIrcUserDataBase.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionUserInfo.h"
#include "KviConsoleWindow.h"
#include "KviFileDialog.h"
#include "KviPointerList.h"
#include "KviMainWindow.h"
#include "KviSharedFilesManager.h"
#include "KviIrcServerParser.h"
#include "kvi_out.h"
#include "KviIrcMask.h"
#include "KviTalHBox.h"
#include <QLineEdit>
#include <QPushButton>
#include <QMessageBox>
#include <QTimer>
#include <QLabel>
#include <QLayout>
#include <QCloseEvent>
#include <QByteArray>
Functions
static bool avatar_kvs_cmd_notify (KviKvsModuleCommandCall *c)
static bool avatar_kvs_cmd_query (KviKvsModuleCommandCall *c)
static bool avatar_kvs_cmd_set (KviKvsModuleCommandCall *c)
static bool avatar_kvs_cmd_unset (KviKvsModuleCommandCall *c)
static bool avatar_kvs_fnc_name (KviKvsModuleFunctionCall *c)
static bool avatar_kvs_fnc_path (KviKvsModuleFunctionCall *c)
static bool avatar_module_can_unload (KviModule *)
static bool avatar_module_cleanup (KviModule *)
static bool avatar_module_init (KviModule *m)
Variables
static KviPointerList
< KviAsyncAvatarSelectionDialog > * g_pAvatarSelectionDialogList = 0
KVIRC_API KviSharedFilesManager * g_pSharedFilesManager
Function Documentation
static bool avatar_kvs_cmd_notify (KviKvsModuleCommandCall * c) static
References __tr2qs, _OUTPUT_VERBOSE, KviSharedFile::absFilePath(), KviSharedFilesManager::addSharedFile(), KviIrcUserEntry::avatar(), KviWindow::connection(), KviIrcConnection::currentNickName(), e, KviIrcServerParser::encodeCtcpParameter(), KviIrcConnection::encodeText(), KviSharedFile::fileSize(), KviKvsSwitchList::find(), KviIrcUserDataBase::find(), g_pSharedFilesManager, KVI_OPTION_BOOL, KVI_OPTION_UINT, KVI_OUT_AVATAR, KVI_OUT_SYSTEMMESSAGE, KviOption_boolDCCFileTransferReplaceOutgoingSpacesWithUnderscores, KviOption_uintAvatarOfferTimeoutInSecs, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, KviAvatar::localPath(), KviSharedFilesManager::lookupSharedFile(), KviAvatar::name(), o, KviWindow::output(), KviIrcConnection::sendFmtData(), KviKvsModuleCommandCall::switches(), u, KviIrcConnection::userDataBase(), KviSharedFile::userMask(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by avatar_module_init().
static bool avatar_kvs_cmd_query (KviKvsModuleCommandCall * c) static
References KviWindow::connection(), KviIrcConnection::encodeText(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, KviIrcConnection::sendFmtData(), and KviKvsRunTimeCall::window().
Referenced by avatar_module_init().
static bool avatar_kvs_cmd_set (KviKvsModuleCommandCall * c) static
References __tr2qs, KviConsoleWindow::avatarChanged(), KviApplication::Avatars, KviWindow::connection(), KviWindow::console(), KviIrcConnection::currentNickName(), d, e, KviQString::equalCIN(), KviQString::escapeKvs(), KviIrcUserDataBase::find(), g_pApp, g_pIconManager, g_pMainWindow, KviIconManager::getAvatar(), KviApplication::getLocalKvircDirectory(), KviIrcConnectionUserInfo::hostName(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, KviIrcConnectionUserInfo::nickName(), KviKvsScript::run(), KviIrcUserEntry::setAvatar(), KviApplication::setAvatarOnFileReceived(), KviIconManager::urlToCachedFileName(), KviIrcConnection::userDataBase(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by avatar_module_init().
static bool avatar_kvs_cmd_unset (KviKvsModuleCommandCall * c) static
References __tr2qs, KviConsoleWindow::avatarChanged(), KviWindow::connection(), KviWindow::console(), KviIrcConnection::currentNickName(), e, KviIrcUserDataBase::find(), KviIrcConnectionUserInfo::hostName(), KVSM_REQUIRE_CONNECTION, KviIrcConnectionUserInfo::nickName(), KviIrcUserEntry::setAvatar(), KviIrcConnection::userDataBase(), KviIrcConnection::userInfo(), KviIrcConnectionUserInfo::userName(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by avatar_module_init().
static bool avatar_kvs_fnc_name (KviKvsModuleFunctionCall * c) static
References KviIrcUserEntry::avatar(), KviWindow::connection(), KviIrcConnection::currentNickName(), e, KviIrcUserDataBase::find(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, KviAvatar::name(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), KviKvsVariant::setString(), KviIrcConnection::userDataBase(), and KviKvsRunTimeCall::window().
Referenced by avatar_module_init().
static bool avatar_kvs_fnc_path (KviKvsModuleFunctionCall * c) static
References KviIrcUserEntry::avatar(), KviWindow::connection(), KviIrcConnection::currentNickName(), e, KviIrcUserDataBase::find(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSM_REQUIRE_CONNECTION, KviAvatar::localPath(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), KviKvsVariant::setString(), KviIrcConnection::userDataBase(), and KviKvsRunTimeCall::window().
Referenced by avatar_module_init().
static bool avatar_module_can_unload (KviModule *) static
References KviPointerList< T >::isEmpty().
static bool avatar_module_cleanup (KviModule *) static
References d, KviPointerList< T >::first(), and g_pAvatarSelectionDialogList.
static bool avatar_module_init (KviModule * m) static
References avatar_kvs_cmd_notify(), avatar_kvs_cmd_query(), avatar_kvs_cmd_set(), avatar_kvs_cmd_unset(), avatar_kvs_fnc_name(), avatar_kvs_fnc_path(), KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, and KviPointerList< T >::setAutoDelete().
Variable Documentation
KviPointerList<KviAsyncAvatarSelectionDialog>* g_pAvatarSelectionDialogList = 0 static
Referenced by avatar_module_cleanup().
KVIRC_API KviSharedFilesManager* g_pSharedFilesManager