KVIrc: src/modules/pythoncore/libkvipythoncore.cpp File Reference
src/modules/pythoncore/libkvipythoncore.cpp File Reference
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviLocale.h"
Functions
static bool pythoncore_module_can_unload (KviModule *)
static bool pythoncore_module_cleanup (KviModule *)
static bool pythoncore_module_ctrl (KviModule *, const char *cmd, void *param)
static bool pythoncore_module_init (KviModule *)
Function Documentation
static bool pythoncore_module_can_unload (KviModule *) [static]
References KviPointerHashTable< Key, T >::count().
static bool pythoncore_module_cleanup (KviModule *) [static]
static bool pythoncore_module_ctrl (KviModule * , const char * cmd, void * param) [static]
References _KviPythonCoreCtrlCommand_execute::bExitOk, _KviPythonCoreCtrlCommand_execute::bQuiet, KVI_PYTHONCORECTRLCOMMAND_DESTROY, KVI_PYTHONCORECTRLCOMMAND_EXECUTE, kvi_strEqualCS(), _KviPythonCoreCtrlCommand_execute::lArgs, _KviPythonCoreCtrlCommand_execute::lWarnings, m, _KviPythonCoreCtrlCommand_execute::pKvsContext, _KviPythonCoreCtrlCommand_execute::szCode, _KviPythonCoreCtrlCommand_destroy::szContext, _KviPythonCoreCtrlCommand_execute::szContext, _KviPythonCoreCtrlCommand_execute::szError, _KviPythonCoreCtrlCommand_execute::szRetVal, _KviPythonCoreCtrlCommand_destroy::uSize, and _KviPythonCoreCtrlCommand_execute::uSize.
static bool pythoncore_module_init (KviModule *) [static]
References KviPointerHashTable< Key, T >::setAutoDelete().