KVIrc: src/modules/texticons/libkvitexticons.cpp File Reference
src/modules/texticons/libkvitexticons.cpp File Reference
#include "KviModule.h"
#include "KviIconManager.h"
#include "KviTextIconManager.h"
Functions
static bool texticons_kvs_cmd_set (KviKvsModuleCommandCall *c)
static bool texticons_kvs_fnc_get (KviKvsModuleFunctionCall *c)
static bool texticons_module_cleanup (KviModule *)
static bool texticons_module_init (KviModule *m)
Function Documentation
static bool texticons_kvs_cmd_set (KviKvsModuleCommandCall * c) [static]
References g_pTextIconManager, KviTextIconManager::insert(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviTextIconManager::lookupTextIcon(), KviIconManager::None, KviPointerHashTable< Key, T >::remove(), KviTextIcon::setFilename(), KviTextIcon::setId(), and KviTextIconManager::textIconDict().
Referenced by texticons_module_init().
static bool texticons_kvs_fnc_get (KviKvsModuleFunctionCall * c) [static]
References KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviTextIcon::filename(), g_pTextIconManager, i, KviTextIcon::id(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviTextIconManager::lookupTextIcon(), KviKvsModuleFunctionCall::returnValue(), KviKvsHash::set(), KviKvsVariant::setHash(), KviKvsVariant::setInteger(), KviKvsVariant::setString(), KviTextIconManager::textIconDict(), and KviKvsRunTimeCall::warning().
Referenced by texticons_module_init().
static bool texticons_module_cleanup (KviModule *) [static]
static bool texticons_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, texticons_kvs_cmd_set(), and texticons_kvs_fnc_get().