KVIrc: src/modules/editor/libkvieditor.cpp File Reference
src/modules/editor/libkvieditor.cpp File Reference
#include "ScriptEditorImplementation.h"
#include "KviModule.h"
#include "KviWindow.h"
Functions
static bool editor_module_can_unload (KviModule *)
static bool editor_module_cleanup (KviModule *)
KVIMODULEEXPORTFUNC void editor_module_destroyScriptEditor (KviScriptEditor *e)
static bool editor_module_init (KviModule *m)
KVIRC_MODULE ("Editor","4.0.0","Copyright (C) 2000 Szymon Stefanek (pragma at kvirc dot net)","Text editor extension", editor_module_init, editor_module_can_unload, 0, editor_module_cleanup,"editor") KVIMODULEEXPORTFUNC KviScriptEditor *editor_module_createScriptEditor(QWidget *par)
Variables
KviModule * g_pEditorModulePointer = 0
KviPointerList
< ScriptEditorImplementation > * g_pScriptEditorWindowList = 0
Function Documentation
static bool editor_module_can_unload (KviModule *) [static]
References KviPointerList< T >::count().
static bool editor_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first(), g_pScriptEditorWindowList, and w.
KVIMODULEEXPORTFUNC void editor_module_destroyScriptEditor (KviScriptEditor * e)
static bool editor_module_init (KviModule * m) [static]
References m, and KviPointerList< T >::setAutoDelete().
KVIRC_MODULE ("Editor" , "4.0.0" , "Copyright (C) 2000 Szymon Stefanek (pragma at kvirc dot net)" , "Text editor extension" , editor_module_init , editor_module_can_unload , 0 , editor_module_cleanup , "editor")
Variable Documentation
KviModule* g_pEditorModulePointer = 0
KviPointerList<ScriptEditorImplementation>* g_pScriptEditorWindowList = 0
Referenced by editor_module_cleanup().