KVIrc: src/modules/popupeditor/libkvipopupeditor.cpp File Reference
libkvipopupeditor.cpp File Reference
#include "PopupEditorWindow.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
Functions
static bool popupeditor_kvs_cmd_open (KviKvsModuleCommandCall *)
static bool popupeditor_module_can_unload (KviModule *)
static bool popupeditor_module_cleanup (KviModule *)
static bool popupeditor_module_init (KviModule *m)
Variables
PopupEditorWindow * g_pPopupEditorWindow = nullptr
Function Documentation
static bool popupeditor_kvs_cmd_open (KviKvsModuleCommandCall *) static
References KviMainWindow::addWindow(), and g_pMainWindow.
Referenced by popupeditor_module_init().
static bool popupeditor_module_can_unload (KviModule *) static
static bool popupeditor_module_cleanup (KviModule *) static
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool popupeditor_module_init (KviModule * m) static
References KVSM_REGISTER_SIMPLE_COMMAND, and popupeditor_kvs_cmd_open().
Variable Documentation
PopupEditorWindow* g_pPopupEditorWindow = nullptr