KVIrc: src/modules/userlist/libkviuserlist.cpp File Reference
src/modules/userlist/libkviuserlist.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviChannelWindow.h"
#include "KviUserListView.h"
Defines
#define GET_KVS_FNC_WINDOW_ID
#define GET_KVS_WINDOW_ID_AND_NICK
Functions
static bool userlist_kvs_cmd_ensureVisible (KviKvsModuleCommandCall *c)
static bool userlist_kvs_cmd_select (KviKvsModuleCommandCall *c)
static bool userlist_kvs_fnc_selected (KviKvsModuleFunctionCall *c)
static bool userlist_module_can_unload (KviModule *)
static bool userlist_module_cleanup (KviModule *)
static bool userlist_module_init (KviModule *m)
Define Documentation
#define GET_KVS_FNC_WINDOW_ID
Value:
QString szWnd; \
        KviWindow * pWnd; \
        KVSM_PARAMETERS_BEGIN(c) \
                KVSM_PARAMETER("window_id",KVS_PT_STRING,KVS_PF_OPTIONAL,szWnd) \
        KVSM_PARAMETERS_END(c) \
        if(c->parameterList()->count() == 0) \
        { \
                pWnd = c->window(); \
        } else { \
                pWnd = g_pApp->findWindow(szWnd.toUtf8().data()); \
                if(!pWnd) \
                        return true; \
        } \
        if(!pWnd) \
        { \
                return true; \
        } \
Referenced by userlist_kvs_fnc_selected().
#define GET_KVS_WINDOW_ID_AND_NICK
Value:
QString szWnd, szNick; \
        KviWindow * pWnd; \
        KVSM_PARAMETERS_BEGIN(c) \
                KVSM_PARAMETER("nick",KVS_PT_NONEMPTYSTRING,0,szNick) \
                KVSM_PARAMETER("window_id",KVS_PT_STRING,KVS_PF_OPTIONAL,szWnd) \
        KVSM_PARAMETERS_END(c) \
        if(c->parameterList()->count() == 1) \
        { \
                pWnd = c->window(); \
        } else { \
                pWnd = g_pApp->findWindow(szWnd.toUtf8().data()); \
                if(!pWnd) \
                { \
                        if(!c->hasSwitch('q',"quiet")) \
                                c->warning(__tr2qs("The window with id '%s' does not exist"),szWnd.toUtf8().data()); \
                        return true; \
                } \
        } \
        if(!pWnd) \
          return true;
Referenced by userlist_kvs_cmd_ensureVisible(), and userlist_kvs_cmd_select().
Function Documentation
static bool userlist_kvs_cmd_ensureVisible (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviWindow::Channel, GET_KVS_WINDOW_ID_AND_NICK, and KviKvsRunTimeCall::warning().
Referenced by userlist_module_init().
static bool userlist_kvs_cmd_select (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviWindow::Channel, GET_KVS_WINDOW_ID_AND_NICK, and KviKvsRunTimeCall::warning().
Referenced by userlist_module_init().
static bool userlist_kvs_fnc_selected (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), a, KviWindow::Channel, GET_KVS_FNC_WINDOW_ID, i, KviKvsModuleFunctionCall::returnValue(), s, KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsVariant::setNothing(), and KviKvsRunTimeCall::warning().
Referenced by userlist_module_init().
static bool userlist_module_can_unload (KviModule *) [static]
static bool userlist_module_cleanup (KviModule *) [static]
static bool userlist_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, userlist_kvs_cmd_ensureVisible(), userlist_kvs_cmd_select(), and userlist_kvs_fnc_selected().