KVIrc: src/modules/perl/libkviperl.cpp File Reference
libkviperl.cpp File Reference
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviFileUtils.h"
#include "KviLocale.h"
#include "KviApplication.h"
#include "KviOptions.h"
#include "KviModuleManager.h"
#include "kvi_out.h"
Macros
#define KVS_CHECK_MODULE_STATE(_m, _c)
#define KVS_CHECK_PERLCORE(_m, _c)
Functions
static bool perl_kvs_cmd_begin (KviKvsModuleCommandCall *c)
static bool perl_kvs_cmd_destroy (KviKvsModuleCommandCall *c)
static bool perl_kvs_fnc_isAvailable (KviKvsModuleFunctionCall *c)
static bool perl_module_cleanup (KviModule *)
static bool perl_module_init (KviModule *m)
Macro Definition Documentation
#define KVS_CHECK_MODULE_STATE (_m, _c)
Value:
if(!_c->switches()->find('q', "quiet"))                                                                         \
                _c->warning(__tr2qs_ctx("This KVIrc executable has been compiled without Perl scripting support", "perl")); \
        return true;
Referenced by perl_kvs_cmd_begin(), and perl_kvs_cmd_destroy().
#define KVS_CHECK_PERLCORE (_m, _c)
Function Documentation
static bool perl_kvs_cmd_begin (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviKvsRunTimeCall::context(), KviModule::ctrl(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviKvsVariantList::first(), KVI_PERLCORECTRLCOMMAND_EXECUTE, KVS_CHECK_MODULE_STATE, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviKvsVariantList::next(), KviKvsRunTimeContext::returnValue(), KviKvsVariant::setString(), KviKvsModuleCommandCall::switches(), _KviPerlCoreCtrlCommand_execute::uSize, v, and KviKvsRunTimeCall::warning().
Referenced by perl_module_init().
static bool perl_kvs_cmd_destroy (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviModule::ctrl(), KviKvsSwitchList::find(), KVI_PERLCORECTRLCOMMAND_DESTROY, KVS_CHECK_MODULE_STATE, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviKvsModuleCommandCall::switches(), _KviPerlCoreCtrlCommand_destroy::uSize, and KviKvsRunTimeCall::warning().
Referenced by perl_module_init().
static bool perl_kvs_fnc_isAvailable (KviKvsModuleFunctionCall * c) static
References g_pModuleManager, KviModuleManager::getModule(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by perl_module_init().
static bool perl_module_cleanup (KviModule *) static
static bool perl_module_init (KviModule * m) static
References g_pModuleManager, KviModuleManager::getModule(), KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, perl_kvs_cmd_begin(), perl_kvs_cmd_destroy(), and perl_kvs_fnc_isAvailable().