KVIrc: src/modules/trayicon/libkvitrayicon.cpp File Reference
src/modules/trayicon/libkvitrayicon.cpp File Reference
#include "libkvitrayicon.h"
#include "kvi_settings.h"
#include "KviApplication.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMemory.h"
#include "KviWindowListBase.h"
#include "KviWindow.h"
#include "KviDynamicToolTip.h"
#include "KviIconManager.h"
#include "KviInternalCommand.h"
#include "KviConsoleWindow.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionUserInfo.h"
#include "KviOptions.h"
#include "KviIrcView.h"
#include "KviTalPopupMenu.h"
#include <QPixmap>
#include <QPainter>
#include <QTimer>
#include <QEvent>
#include <QRegExp>
#include <stdlib.h>
#include <time.h>
#include "libkvitrayicon.moc"
Defines
#define ICON_SIZE 22
#define NIDLEMSGS 18
Functions
static TrayIcon * trayicon_find (KviMainWindow *f)
static bool trayicon_kvs_cmd_hide (KviKvsModuleCommandCall *c)
static bool trayicon_kvs_cmd_hidewindow (KviKvsModuleCommandCall *c)
static bool trayicon_kvs_cmd_show (KviKvsModuleCommandCall *c)
static bool trayicon_kvs_fnc_isvisible (KviKvsModuleFunctionCall *c)
static bool trayicon_module_can_unload (KviModule *)
static bool trayicon_module_cleanup (KviModule *)
static bool trayicon_module_init (KviModule *m)
Variables
static QPixmap * g_pDock1 = 0
static QPixmap * g_pDock2 = 0
static QPixmap * g_pDock3 = 0
KVIRC_API KviPointerHashTable
< QString, KviWindow > * g_pGlobalWindowDict
static KviPointerList< TrayIcon > * g_pTrayIconList = 0
static const char * idlemsgs [NIDLEMSGS]
Define Documentation
#define ICON_SIZE 22
Referenced by TrayIcon::refresh().
#define NIDLEMSGS 18
Referenced by TrayIcon::event().
Function Documentation
static TrayIcon* trayicon_find (KviMainWindow * f) [static]
References f, KviPointerList< T >::first(), KviPointerList< T >::next(), and w.
Referenced by trayicon_kvs_cmd_hide(), trayicon_kvs_cmd_hidewindow(), trayicon_kvs_cmd_show(), and trayicon_kvs_fnc_isvisible().
static bool trayicon_kvs_cmd_hide (KviKvsModuleCommandCall * c) [static]
References KviWindow::frame(), trayicon_find(), w, and KviKvsRunTimeCall::window().
Referenced by trayicon_module_init().
static bool trayicon_kvs_cmd_hidewindow (KviKvsModuleCommandCall * c) [static]
References KviWindow::frame(), trayicon_find(), w, and KviKvsRunTimeCall::window().
Referenced by trayicon_module_init().
static bool trayicon_kvs_cmd_show (KviKvsModuleCommandCall * c) [static]
References KviWindow::frame(), trayicon_find(), w, and KviKvsRunTimeCall::window().
Referenced by trayicon_module_init().
static bool trayicon_kvs_fnc_isvisible (KviKvsModuleFunctionCall * c) [static]
References KviWindow::frame(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), trayicon_find(), and KviKvsRunTimeCall::window().
Referenced by trayicon_module_init().
static bool trayicon_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool trayicon_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first(), g_pDock1, g_pDock2, g_pDock3, and g_pTrayIconList.
static bool trayicon_module_init (KviModule * m) [static]
References KviApplication::findImage(), g_pApp, g_pDock1, g_pDock2, g_pDock3, KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, KviPointerList< T >::setAutoDelete(), trayicon_kvs_cmd_hide(), trayicon_kvs_cmd_hidewindow(), trayicon_kvs_cmd_show(), and trayicon_kvs_fnc_isvisible().
Variable Documentation
QPixmap* g_pDock1 = 0 [static]
Referenced by TrayIcon::refresh(), TrayIcon::TrayIcon(), trayicon_module_cleanup(), and trayicon_module_init().
QPixmap* g_pDock2 = 0 [static]
Referenced by TrayIcon::refresh(), trayicon_module_cleanup(), and trayicon_module_init().
QPixmap* g_pDock3 = 0 [static]
Referenced by TrayIcon::refresh(), trayicon_module_cleanup(), and trayicon_module_init().
KVIRC_API KviPointerHashTable<QString,KviWindow>* g_pGlobalWindowDict
KviPointerList<TrayIcon>* g_pTrayIconList = 0 [static]
Referenced by trayicon_module_cleanup().
const char* idlemsgs[NIDLEMSGS] [static]
Initial value:
{
        __tr("Nothing is happening..."),
        __tr("Just idling..."),
        __tr("Dum de dum de dum..."),
        __tr("Hey man... do something!"),
        __tr("Umpf!"),
        __tr("Silence speaking"),
        __tr("Are ya here?"),
        __tr("The world has stopped?"),
        __tr("Everything is all right"),
        __tr("idle()"),
        __tr("It's so cold here..."),
        __tr("Do not disturb... watching TV"),
        __tr("Just vegetating"),
        __tr("Hey... are ya sure that your network is up?"),
        __tr("Seems like the world has stopped spinning"),
        __tr("This silence is freaking me out!"),
        __tr("Mieeeeeowww!"),
        __tr("idle idle idle idle!")
}
Referenced by TrayIcon::event().