KVIrc: src/modules/package/libkvipackage.cpp File Reference
libkvipackage.cpp File Reference
#include "KviModule.h"
#include "KviPackageReader.h"
#include "KviLocale.h"
#include "KviKvsHash.h"
#include "KviKvsArray.h"
#include "KviFileUtils.h"
#include "KviApplication.h"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <stdlib.h>
Functions
static QString createRandomDir ()
static bool package_kvs_cmd_extractField (KviKvsModuleCommandCall *c)
static bool package_kvs_fnc_info (KviKvsModuleFunctionCall *c)
static bool package_module_cleanup (KviModule *)
static bool package_module_init (KviModule *m)
Function Documentation
static QString createRandomDir () static
References i, and n.
Referenced by package_kvs_fnc_info().
static bool package_kvs_cmd_extractField (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviPackageIOEngine::binaryInfoFields(), KviPointerHashTable< Key, T >::find(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviPackageIOEngine::lastError(), r, KviPackageReader::readHeader(), KviKvsRunTimeCall::warning(), and KviFileUtils::writeFile().
Referenced by package_module_init().
static bool package_kvs_fnc_info (KviKvsModuleFunctionCall * c) static
References KviKvsArray::append(), KviPackageIOEngine::binaryInfoFields(), createRandomDir(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), KviFileUtils::deleteDir(), KviQString::ensureLastCharIs(), g_pApp, KviFileUtils::getFileListing(), KviApplication::getLocalKvircDirectory(), KVI_PATH_SEPARATOR_CHAR, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviPackageIOEngine::lastError(), KviPointerHashTableIterator< Key, T >::moveNext(), r, KviKvsModuleFunctionCall::returnValue(), KviKvsHash::set(), KviKvsVariant::setHash(), KviPackageIOEngine::stringInfoFields(), KviApplication::Tmp, and KviPackageReader::unpack().
Referenced by package_module_init().
static bool package_module_cleanup (KviModule *) static
static bool package_module_init (KviModule * m) static
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, package_kvs_cmd_extractField(), and package_kvs_fnc_info().