KVIrc: src/modules/objects/libkviobjects.cpp File Reference
src/modules/objects/libkviobjects.cpp File Reference
#include "KvsObject_button.h"
#include "KvsObject_checkBox.h"
#include "KvsObject_comboBox.h"
#include "KvsObject_dialog.h"
#include "KvsObject_dockWindow.h"
#include "KvsObject_file.h"
#include "KvsObject_ftp.h"
#include "KvsObject_groupBox.h"
#include "KvsObject_buttonGroup.h"
#include "KvsObject_hBox.h"
#include "KvsObject_http.h"
#include "KvsObject_label.h"
#include "KvsObject_layout.h"
#include "KvsObject_lcd.h"
#include "KvsObject_lineEdit.h"
#include "KvsObject_list.h"
#include "KvsObject_listWidget.h"
#include "KvsObject_mainWindow.h"
#include "KvsObject_memoryBuffer.h"
#include "KvsObject_menuBar.h"
#include "KvsObject_multiLineEdit.h"
#include "KvsObject_painter.h"
#include "KvsObject_pixmap.h"
#include "KvsObject_popupMenu.h"
#include "KvsObject_process.h"
#include "KvsObject_progressBar.h"
#include "KvsObject_radioButton.h"
#include "KvsObject_slider.h"
#include "KvsObject_socket.h"
#include "KvsObject_spinBox.h"
#include "KvsObject_tabWidget.h"
#include "KvsObject_tableWidget.h"
#include "KvsObject_textBrowser.h"
#include "KvsObject_toolBar.h"
#include "KvsObject_toolButton.h"
#include "KvsObject_trayIcon.h"
#include "KvsObject_treeWidget.h"
#include "KvsObject_treeWidgeteItem.h"
#include "KvsObject_vBox.h"
#include "KvsObject_widget.h"
#include "KvsObject_window.h"
#include "KvsObject_wizard.h"
#include "KvsObject_workspace.h"
#include "KvsObject_wrapper.h"
#include "KvsObject_xmlreader.h"
#include "KvsObject_sql.h"
#include "KvsObject_dateTimeEdit.h"
#include "KviIconManager.h"
#include "KviWindow.h"
#include "kvi_out.h"
#include "KviMircCntrl.h"
#include "KviApplication.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviError.h"
#include "KviCommandFormatter.h"
#include "KviFileUtils.h"
#include <QDir>
#include <QImage>
Functions
static void dumpChildObjects (KviWindow *pWnd, QObject *parent, const char *spacing, bool bWidgetsOnly, KviKvsArray *n, int &idx)
static bool objects_kvs_cmd_clearObjects (KviKvsModuleCommandCall *c)
static bool objects_kvs_cmd_connect (KviKvsModuleCommandCall *c)
static bool objects_kvs_cmd_disconnect (KviKvsModuleCommandCall *c)
static bool objects_kvs_cmd_killClass (KviKvsModuleCommandCall *c)
static bool objects_kvs_fnc_classAllHandlers (KviKvsModuleFunctionCall *c)
static bool objects_kvs_fnc_classes (KviKvsModuleFunctionCall *c)
static bool objects_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool objects_kvs_fnc_instances (KviKvsModuleFunctionCall *c)
static bool objects_kvs_fnc_listObjects (KviKvsModuleFunctionCall *cmd)
static bool objects_kvs_fnc_name (KviKvsModuleFunctionCall *c)
static bool objects_kvs_fnc_variables (KviKvsModuleFunctionCall *c)
static bool objects_module_can_unload (KviModule *)
static bool objects_module_cleanup (KviModule *)
static bool objects_module_init (KviModule *m)
Function Documentation
static void dumpChildObjects (KviWindow * pWnd, QObject * parent, const char * spacing, bool bWidgetsOnly, KviKvsArray * n, int & idx) [static]
References KviMircCntrl::Bold, i, n, KviWindow::output(), KviKvsArray::set(), KviKvsVariant::setString(), and v.
Referenced by objects_kvs_fnc_listObjects().
static bool objects_kvs_cmd_clearObjects (KviKvsModuleCommandCall * c) [static]
References KviKvsObjectController::clearInstances(), KviKvsObjectController::clearUserClasses(), KviKvsSwitchList::find(), KviKvsKernel::instance(), KviKvsKernel::objectController(), and KviKvsModuleCommandCall::switches().
Referenced by objects_module_init().
static bool objects_kvs_cmd_connect (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsObject::connectSignal(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_kvs_cmd_disconnect (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsObject::disconnectSignal(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_kvs_cmd_killClass (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsObjectController::deleteClass(), KviKvsModuleCommandCall::hasSwitch(), KviKvsKernel::instance(), KviKvsObjectClass::isBuiltin(), KviKvsObjectController::killAllObjectsWithClass(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsObjectController::lookupClass(), KviKvsKernel::objectController(), and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_kvs_fnc_classAllHandlers (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviKvsObjectClass::getFunctionCode(), KviKvsObjectClass::getHandlers(), KviKvsKernel::instance(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupClass(), KviKvsObjectClass::lookupFunctionHandler(), KviKvsKernel::objectController(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setHash(), and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_kvs_fnc_classes (KviKvsModuleFunctionCall * c) [static]
References KviApplication::Classes, KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, g_pApp, KviApplication::getLocalKvircDirectory(), KviPointerHashTable< Key, T >::insert(), KviKvsKernel::instance(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviPointerHashTable< Key, T >::setAutoDelete().
Referenced by objects_module_init().
static bool objects_kvs_fnc_exists (KviKvsModuleFunctionCall * c) [static]
References KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by objects_module_init().
static bool objects_kvs_fnc_instances (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviPointerHashTableIterator< Key, T >::current(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupClass(), KviKvsKernel::objectController(), KviKvsObjectController::objectDict(), KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_kvs_fnc_listObjects (KviKvsModuleFunctionCall * cmd) [static]
References KviMircCntrl::Bold, dumpChildObjects(), g_pApp, i, KVS_PT_BOOL, KVSO_PARAMETER, KVSO_PARAMETERS_BEGIN, KVSO_PARAMETERS_END, n, KviWindow::output(), KviCString::ptr(), KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsVariant::setString(), v, and KviKvsRunTimeCall::window().
Referenced by objects_module_init().
static bool objects_kvs_fnc_name (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviKvsObject::getName(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_kvs_fnc_variables (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviKvsObject::dataContainer(), KviKvsHash::dict(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KVSO_PARAMETER, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setHash(), t, and KviKvsRunTimeCall::warning().
Referenced by objects_module_init().
static bool objects_module_can_unload (KviModule *) [static]
static bool objects_module_cleanup (KviModule *) [static]
static bool objects_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, objects_kvs_cmd_clearObjects(), objects_kvs_cmd_connect(), objects_kvs_cmd_disconnect(), objects_kvs_cmd_killClass(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_classes(), objects_kvs_fnc_exists(), objects_kvs_fnc_instances(), objects_kvs_fnc_listObjects(), objects_kvs_fnc_name(), and objects_kvs_fnc_variables().