KVIrc: src/modules/channelsjoin/libkvichannelsjoin.cpp File Reference
src/modules/channelsjoin/libkvichannelsjoin.cpp File Reference
#include "ChannelsJoinDialog.h"
#include "KviModule.h"
#include "KviWindow.h"
#include "KviMainWindow.h"
#include "KviLocale.h"
#include "KviConfigurationFile.h"
#include <QSplitter>
Functions
static bool channelsjoin_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool channelsjoin_module_can_unload (KviModule *)
static bool channelsjoin_module_cleanup (KviModule *m)
static bool channelsjoin_module_init (KviModule *m)
Variables
ChannelsJoinDialog * g_pChannelsWindow = 0
QRect g_rectChannelsJoinGeometry
Function Documentation
static bool channelsjoin_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviWindow::console(), KviWindow::frame(), ChannelsJoinDialog::setConsole(), and KviKvsRunTimeCall::window().
Referenced by channelsjoin_module_init().
static bool channelsjoin_module_can_unload (KviModule *) [static]
static bool channelsjoin_module_cleanup (KviModule * m) [static]
References g_pChannelsWindow, g_rectChannelsJoinGeometry, KviModule::getDefaultConfigFileName(), KviConfigurationFile::Write, and KviConfigurationFile::writeEntry().
static bool channelsjoin_module_init (KviModule * m) [static]
References channelsjoin_kvs_cmd_open(), g_rectChannelsJoinGeometry, KviModule::getDefaultConfigFileName(), KVSM_REGISTER_SIMPLE_COMMAND, KviConfigurationFile::Read, and KviConfigurationFile::readRectEntry().
Variable Documentation
ChannelsJoinDialog* g_pChannelsWindow = 0
Referenced by channelsjoin_module_cleanup().
QRect g_rectChannelsJoinGeometry
Referenced by channelsjoin_module_cleanup(), channelsjoin_module_init(), ChannelsJoinDialog::ChannelsJoinDialog(), and ChannelsJoinDialog::~ChannelsJoinDialog().