KVIrc: src/modules/sharedfileswindow/libkvisharedfileswindow.cpp File Reference
src/modules/sharedfileswindow/libkvisharedfileswindow.cpp File Reference
#include "SharedFilesWindow.h"
#include "KviModule.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include <QSplitter>
Defines
#define KVI_SHARED_FILES_WINDOW_EXTENSION_NAME "Shared files window extension"
Functions
static KviModuleExtension * sharedfileswindow_extension_alloc (KviModuleExtensionAllocStruct *s)
static bool sharedfileswindow_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool sharedfileswindow_module_can_unload (KviModule *)
static bool sharedfileswindow_module_cleanup (KviModule *)
static bool sharedfileswindow_module_init (KviModule *m)
Variables
SharedFilesWindow * g_pSharedFilesWindow = 0
Define Documentation
#define KVI_SHARED_FILES_WINDOW_EXTENSION_NAME "Shared files window extension"
Referenced by sharedfileswindow_kvs_cmd_open(), and sharedfileswindow_module_init().
Function Documentation
static KviModuleExtension* sharedfileswindow_extension_alloc (KviModuleExtensionAllocStruct * s) [static]
References KviMainWindow::addWindow(), KviWindow::delayedAutoRaise(), KviPointerHashTable< Key, T >::find(), g_pMainWindow, g_pSharedFilesWindow, KviWindow::minimize(), _KviModuleExtensionAllocStructTag::pDescriptor, _KviModuleExtensionAllocStructTag::pParams, and v.
Referenced by sharedfileswindow_module_init().
static bool sharedfileswindow_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviModuleExtensionDescriptor::allocate(), d, KviModule::findExtensionDescriptor(), KviKvsModuleCommandCall::hasSwitch(), KVI_SHARED_FILES_WINDOW_EXTENSION_NAME, KviKvsModuleRunTimeCall::module(), KviPointerHashTable< Key, T >::replace(), KviPointerHashTable< Key, T >::setAutoDelete(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by sharedfileswindow_module_init().
static bool sharedfileswindow_module_can_unload (KviModule *) [static]
static bool sharedfileswindow_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool sharedfileswindow_module_init (KviModule * m) [static]
References __tr2qs_ctx(), d, g_pIconManager, KviIconManager::getSmallIcon(), KVI_SHARED_FILES_WINDOW_EXTENSION_NAME, KVSM_REGISTER_SIMPLE_COMMAND, KviModule::registerExtension(), KviModuleExtensionDescriptor::setIcon(), KviIconManager::SharedFiles, sharedfileswindow_extension_alloc(), and sharedfileswindow_kvs_cmd_open().
Variable Documentation
SharedFilesWindow* g_pSharedFilesWindow = 0
Referenced by sharedfileswindow_extension_alloc().