KVIrc: src/modules/log/libkvilog.cpp File Reference
libkvilog.cpp File Reference
#include "../logview/LogFile.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include "KviIrcView.h"
#include "KviModule.h"
#include "KviModuleManager.h"
Functions
static bool log_kvs_cmd_flush (KviKvsModuleCommandCall *c)
static bool log_kvs_cmd_start (KviKvsModuleCommandCall *c)
static bool log_kvs_cmd_stop (KviKvsModuleCommandCall *c)
static bool log_kvs_fnc_export (KviKvsModuleFunctionCall *c)
static bool log_kvs_fnc_file (KviKvsModuleFunctionCall *c)
static bool log_module_cleanup (KviModule *)
static bool log_module_init (KviModule *m)
Function Documentation
static bool log_kvs_cmd_flush (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviApplication::findWindow(), KviIrcView::flushLog(), g_pApp, KviKvsSwitchList::getAsStringIfExisting(), KviKvsModuleCommandCall::hasSwitch(), KviKvsModuleCommandCall::switches(), KviWindow::view(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by log_module_init().
static bool log_kvs_cmd_start (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviApplication::findWindow(), g_pApp, KviKvsSwitchList::getAsStringIfExisting(), KviWindow::getDefaultLogFileName(), KviKvsModuleCommandCall::hasSwitch(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcView::startLogging(), KviKvsModuleCommandCall::switches(), KviWindow::view(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by log_module_init().
static bool log_kvs_cmd_stop (KviKvsModuleCommandCall * c) static
References __tr2qs_ctx(), KviApplication::findWindow(), g_pApp, KviKvsSwitchList::getAsStringIfExisting(), KviKvsModuleCommandCall::hasSwitch(), KviIrcView::stopLogging(), KviKvsModuleCommandCall::switches(), KviWindow::view(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by log_module_init().
static bool log_kvs_fnc_export (KviKvsModuleFunctionCall * c) static
References __tr2qs_ctx(), KviModule::ctrl(), KviKvsRunTimeCall::error(), g_pModuleManager, KviModuleManager::getModule(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), _LogFileData::szFile, _LogFileData::szName, and _LogFileData::szType.
Referenced by log_module_init().
static bool log_kvs_fnc_file (KviKvsModuleFunctionCall * c) static
References __tr2qs_ctx(), KviApplication::findWindow(), g_pApp, KviIrcView::getLogFileName(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), szBuffer, KviWindow::view(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by log_module_init().
static bool log_module_cleanup (KviModule *) static
static bool log_module_init (KviModule * m) static
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), log_kvs_fnc_export(), and log_kvs_fnc_file().