KVIrc: src/modules/my/libkvimy.cpp File Reference
src/modules/my/libkvimy.cpp File Reference
#include "KviModule.h"
#include "KviConsoleWindow.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviIrcLink.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionUserInfo.h"
#include "KviIrcConnectionServerInfo.h"
#include "KviIrcServer.h"
#include "Idle.h"
Defines
#define GET_KVS_CONSOLE
Functions
static bool my_kvs_cmd_startIdleTimer (KviKvsModuleCommandCall *)
static bool my_kvs_cmd_stopIdleTimer (KviKvsModuleCommandCall *)
static bool my_kvs_fnc_globalIdle (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_host (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_ip (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_network (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_nick (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_server (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_serverIsIPV6 (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_serverIsSSL (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_umode (KviKvsModuleFunctionCall *c)
static bool my_kvs_fnc_user (KviKvsModuleFunctionCall *c)
static bool my_module_can_unload (KviModule *)
static bool my_module_cleanup (KviModule *)
static bool my_module_init (KviModule *m)
Variables
Idle * g_pIdle
Define Documentation
#define GET_KVS_CONSOLE
Value:
kvs_uint_t  uiWnd; \
        KviConsoleWindow *wnd =0; \
        KVSM_PARAMETERS_BEGIN(c) \
                KVSM_PARAMETER("context_id",KVS_PT_UINT,KVS_PF_OPTIONAL,uiWnd) \
        KVSM_PARAMETERS_END(c) \
        if(!c->parameterList()->count()) \
        { \
                if(c->window()->console()) wnd = c->window()->console(); \
                        else c->warning(__tr2qs("This window has no associated irc context")); \
        } \
        else \
        { \
                wnd = g_pApp->findConsole(uiWnd); \
                if(!wnd)c->warning(__tr2qs("No such irc context (%d)"),uiWnd); \
        }
Referenced by my_kvs_fnc_host(), my_kvs_fnc_ip(), my_kvs_fnc_network(), my_kvs_fnc_nick(), my_kvs_fnc_server(), my_kvs_fnc_serverIsIPV6(), my_kvs_fnc_serverIsSSL(), my_kvs_fnc_umode(), and my_kvs_fnc_user().
Function Documentation
static bool my_kvs_cmd_startIdleTimer (KviKvsModuleCommandCall *) [static]
References Idle::start().
Referenced by my_module_init().
static bool my_kvs_cmd_stopIdleTimer (KviKvsModuleCommandCall *) [static]
References Idle::stop().
Referenced by my_module_init().
static bool my_kvs_fnc_globalIdle (KviKvsModuleFunctionCall * c) [static]
References __tr2qs, KviKvsRunTimeCall::error(), KviKvsModuleFunctionCall::returnValue(), Idle::secondsIdle(), and KviKvsVariant::setInteger().
Referenced by my_module_init().
static bool my_kvs_fnc_host (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_kvs_fnc_ip (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_kvs_fnc_network (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_kvs_fnc_nick (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_kvs_fnc_server (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_kvs_fnc_serverIsIPV6 (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by my_module_init().
static bool my_kvs_fnc_serverIsSSL (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by my_module_init().
static bool my_kvs_fnc_umode (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_kvs_fnc_user (KviKvsModuleFunctionCall * c) [static]
References GET_KVS_CONSOLE, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by my_module_init().
static bool my_module_can_unload (KviModule *) [static]
References g_pIdle.
static bool my_module_cleanup (KviModule *) [static]
References g_pIdle.
static bool my_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, my_kvs_cmd_startIdleTimer(), my_kvs_cmd_stopIdleTimer(), my_kvs_fnc_globalIdle(), my_kvs_fnc_host(), my_kvs_fnc_ip(), my_kvs_fnc_network(), my_kvs_fnc_nick(), my_kvs_fnc_server(), my_kvs_fnc_serverIsIPV6(), my_kvs_fnc_serverIsSSL(), my_kvs_fnc_umode(), and my_kvs_fnc_user().
Variable Documentation
Idle* g_pIdle
Referenced by my_module_can_unload(), and my_module_cleanup().