KVIrc: src/modules/math/libkvimath.cpp File Reference
libkvimath.cpp File Reference
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviCString.h"
#include <cmath>
Macros
#define MATH_KVS_1PARAM_FUNCTION(__fncname, __paramname, __mathcallname)
Functions
static bool math_kvs_fnc_e (KviKvsModuleFunctionCall *c)
static bool math_kvs_fnc_isinf (KviKvsModuleFunctionCall *c)
static bool math_kvs_fnc_isnan (KviKvsModuleFunctionCall *c)
static bool math_kvs_fnc_pi (KviKvsModuleFunctionCall *c)
static bool math_kvs_fnc_pow (KviKvsModuleFunctionCall *c)
static bool math_module_cleanup (KviModule *)
static bool math_module_init (KviModule *m)
Macro Definition Documentation
#define MATH_KVS_1PARAM_FUNCTION (__fncname, __paramname, __mathcallname)
Value:
static bool __fncname(KviKvsModuleFunctionCall * c)                  \
        {                                                                    \
        kvs_real_t dReal;                                                \
        KVSM_PARAMETERS_BEGIN(c)                                         \
        KVSM_PARAMETER(__paramname, KVS_PT_REAL, 0, dReal)               \
        KVSM_PARAMETERS_END(c)                                           \
        c->returnValue()->setReal(__mathcallname(dReal));                \
                return true;                                                     \
        }
Function Documentation
static bool math_kvs_fnc_e (KviKvsModuleFunctionCall * c) static
References KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setReal().
Referenced by math_module_init().
static bool math_kvs_fnc_isinf (KviKvsModuleFunctionCall * c) static
References KVS_PT_REAL, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by math_module_init().
static bool math_kvs_fnc_isnan (KviKvsModuleFunctionCall * c) static
References KVS_PT_REAL, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by math_module_init().
static bool math_kvs_fnc_pi (KviKvsModuleFunctionCall * c) static
References KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setReal().
Referenced by math_module_init().
static bool math_kvs_fnc_pow (KviKvsModuleFunctionCall * c) static
References KVS_PT_REAL, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setReal().
Referenced by math_module_init().
static bool math_module_cleanup (KviModule *) static
static bool math_module_init (KviModule * m) static
References KVSM_REGISTER_FUNCTION, math_kvs_fnc_e(), math_kvs_fnc_isinf(), math_kvs_fnc_isnan(), math_kvs_fnc_pi(), and math_kvs_fnc_pow().