KVIrc: src/modules/lamerizer/libkvilamerizer.cpp File Reference
libkvilamerizer.cpp File Reference
#include "libkvilamerizer.h"
#include "KviModule.h"
#include "kvi_debug.h"
#include "KviLocale.h"
Functions
static bool lamerizer_module_can_unload (KviModule *)
static bool lamerizer_module_cleanup (KviModule *m)
static bool lamerizer_module_init (KviModule *m)
Function Documentation
static bool lamerizer_module_can_unload (KviModule *) static
References KviPointerList< T >::isEmpty().
static bool lamerizer_module_cleanup (KviModule * m) static
References KviPointerList< T >::first().
static bool lamerizer_module_init (KviModule * m) static
References __tr2qs, KviCryptEngine::CanEncrypt, d, KviModule::m_szName, and KviPointerList< T >::setAutoDelete().