KVIrc: src/modules/chan/libkvichan.cpp File Reference
src/modules/chan/libkvichan.cpp File Reference
#include "KviModule.h"
#include "KviCString.h"
#include "KviApplication.h"
#include "KviChannelWindow.h"
#include "KviLocale.h"
#include "KviTopicWidget.h"
#include "KviIrcMask.h"
#include "KviMaskEditor.h"
#include "KviIrcUrl.h"
#include "KviIrcConnectionTarget.h"
#include "KviIrcConnection.h"
Defines
#define IS_KVS_FUNC(__clbkname, __chanfunc)
#define IS_ME_KVS_FUNC(__clbkname, __chanfunc)
Functions
static KviChannelWindow * chan_kvs_find_channel (KviKvsModuleFunctionCall *c, QString &szChan, bool bNoWarnings=false)
static bool chan_kvs_fnc_admincount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_bancount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_banexceptioncount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_banexceptionlist (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_banlist (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_common (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_getflag (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_getUrl (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_halfopcount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_invitecount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_invitelist (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_isdead (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_ison (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_key (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_limit (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_maskcount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_masklist (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_matchban (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_matchbanexception (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_matchinvite (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_matchmask (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_matchqban (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_mode (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_modeParam (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_name (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_opcount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_ownercount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_topic (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_topicsetat (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_topicsetby (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_usercount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_userjointime (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_userlastactiontime (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_usermodelevel (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_useropcount (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_users (KviKvsModuleFunctionCall *c)
static bool chan_kvs_fnc_voicecount (KviKvsModuleFunctionCall *c)
static bool chan_module_cleanup (KviModule *)
static bool chan_module_init (KviModule *m)
Define Documentation
#define IS_KVS_FUNC (__clbkname, __chanfunc)
Value:
static bool __clbkname(KviKvsModuleFunctionCall * c) \
{ \
        QString szId,szNick;\
        KVSM_PARAMETERS_BEGIN(c)\
                KVSM_PARAMETER("nickname",KVS_PT_NONEMPTYSTRING,0,szNick)\
                KVSM_PARAMETER("window id",KVS_PT_STRING,KVS_PF_OPTIONAL,szId)\
        KVSM_PARAMETERS_END(c)\
        KviChannelWindow * ch = chan_kvs_find_channel(c,szId); \
        if(ch) c->returnValue()->setBoolean(ch->__chanfunc(szNick,true)); \
        return true; \
}
#define IS_ME_KVS_FUNC (__clbkname, __chanfunc)
Value:
static bool __clbkname(KviKvsModuleFunctionCall * c) \
{ \
        QString szId;\
        KVSM_PARAMETERS_BEGIN(c)\
                KVSM_PARAMETER("window id",KVS_PT_STRING,KVS_PF_OPTIONAL,szId)\
        KVSM_PARAMETERS_END(c)\
        KviChannelWindow * ch = chan_kvs_find_channel(c,szId); \
        if(ch) c->returnValue()->setBoolean(ch->__chanfunc(true)); \
        return true; \
}
Function Documentation
static KviChannelWindow* chan_kvs_find_channel (KviKvsModuleFunctionCall * c, QString & szChan, bool bNoWarnings = false) [static]
References __tr2qs, KviWindow::Channel, KviWindow::DeadChannel, KviApplication::findWindow(), g_pApp, KviWindow::type(), w, KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by chan_kvs_fnc_admincount(), chan_kvs_fnc_bancount(), chan_kvs_fnc_banexceptioncount(), chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_common(), chan_kvs_fnc_getflag(), chan_kvs_fnc_getUrl(), chan_kvs_fnc_halfopcount(), chan_kvs_fnc_invitecount(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_isdead(), chan_kvs_fnc_ison(), chan_kvs_fnc_key(), chan_kvs_fnc_limit(), chan_kvs_fnc_maskcount(), chan_kvs_fnc_masklist(), chan_kvs_fnc_matchban(), chan_kvs_fnc_matchbanexception(), chan_kvs_fnc_matchinvite(), chan_kvs_fnc_matchmask(), chan_kvs_fnc_matchqban(), chan_kvs_fnc_mode(), chan_kvs_fnc_modeParam(), chan_kvs_fnc_name(), chan_kvs_fnc_opcount(), chan_kvs_fnc_ownercount(), chan_kvs_fnc_topic(), chan_kvs_fnc_topicsetat(), chan_kvs_fnc_topicsetby(), chan_kvs_fnc_usercount(), chan_kvs_fnc_userjointime(), chan_kvs_fnc_userlastactiontime(), chan_kvs_fnc_usermodelevel(), chan_kvs_fnc_useropcount(), chan_kvs_fnc_users(), and chan_kvs_fnc_voicecount().
static bool chan_kvs_fnc_admincount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::chanAdminCount(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_bancount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviChannelWindow::maskCount(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_banexceptioncount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviChannelWindow::maskCount(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_banexceptionlist (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviChannelWindow::modeMasks(), KviPointerList< T >::next(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by chan_module_init().
static bool chan_kvs_fnc_banlist (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviChannelWindow::modeMasks(), KviPointerList< T >::next(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by chan_module_init().
static bool chan_kvs_fnc_common (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviWindow::connection(), KviIrcConnection::getCommonChannels(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_getflag (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviUserListView::getUserFlag(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), KviKvsVariant::setString(), and KviChannelWindow::userListView().
Referenced by chan_module_init().
static bool chan_kvs_fnc_getUrl (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::channelModeParam(), KviWindow::connection(), KviKvsRunTimeCall::error(), KviChannelWindow::hasChannelMode(), KviIrcUrl::join(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviIrcConnectionTarget::server(), KviKvsVariant::setString(), KviIrcConnection::target(), KviKvsRunTimeCall::window(), and KviWindow::windowName().
Referenced by chan_module_init().
static bool chan_kvs_fnc_halfopcount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::halfOpCount(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_invitecount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviChannelWindow::maskCount(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_invitelist (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviChannelWindow::modeMasks(), KviPointerList< T >::next(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by chan_module_init().
static bool chan_kvs_fnc_isdead (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviWindow::DeadChannel, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviWindow::type().
Referenced by chan_module_init().
static bool chan_kvs_fnc_ison (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::isOn(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by chan_module_init().
static bool chan_kvs_fnc_key (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::channelModeParam(), KviChannelWindow::hasChannelMode(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_limit (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::channelModeParam(), KviChannelWindow::hasChannelMode(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_maskcount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviChannelWindow::maskCount(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_masklist (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviChannelWindow::modeMasks(), KviPointerList< T >::next(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), and KviKvsVariant::setArray().
Referenced by chan_module_init().
static bool chan_kvs_fnc_matchban (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviQString::matchString(), KviChannelWindow::modeMasks(), KviPointerList< T >::next(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_matchbanexception (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviQString::matchString(), KviChannelWindow::modeMasks(), KviPointerList< T >::next(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_matchinvite (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviQString::matchString(), KviChannelWindow::modeMasks(), KviPointerList< T >::next(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_matchmask (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviQString::matchString(), KviChannelWindow::modeMasks(), KviPointerList< T >::next(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_matchqban (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), e, KviPointerList< T >::first(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, l, KviQString::matchString(), KviChannelWindow::modeMasks(), KviPointerList< T >::next(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setNothing(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_mode (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::getChannelModeString(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by chan_module_init().
static bool chan_kvs_fnc_modeParam (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::channelModeParam(), KviChannelWindow::hasChannelMode(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by chan_module_init().
static bool chan_kvs_fnc_name (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviWindow::windowName().
Referenced by chan_module_init().
static bool chan_kvs_fnc_opcount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviChannelWindow::opCount(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_ownercount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::chanOwnerCount(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_topic (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), KviTopicWidget::topic(), and KviChannelWindow::topicWidget().
Referenced by chan_module_init().
static bool chan_kvs_fnc_topicsetat (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), KviTopicWidget::topicSetAt(), and KviChannelWindow::topicWidget().
Referenced by chan_module_init().
static bool chan_kvs_fnc_topicsetby (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), KviTopicWidget::topicSetBy(), and KviChannelWindow::topicWidget().
Referenced by chan_module_init().
static bool chan_kvs_fnc_usercount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviChannelWindow::count(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by chan_module_init().
static bool chan_kvs_fnc_userjointime (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviUserListView::getUserJoinTime(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviChannelWindow::userListView().
Referenced by chan_module_init().
static bool chan_kvs_fnc_userlastactiontime (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviUserListView::getUserLastActionTime(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviChannelWindow::userListView().
Referenced by chan_module_init().
static bool chan_kvs_fnc_usermodelevel (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviUserListView::getUserModeLevel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviChannelWindow::userListView().
Referenced by chan_module_init().
static bool chan_kvs_fnc_useropcount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviChannelWindow::userOpCount().
Referenced by chan_module_init().
static bool chan_kvs_fnc_users (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KviIrcUserEntry::ChanAdmin, e, KviUserListView::firstItem(), KviUserListEntry::flags(), KviUserListEntry::globalData(), KviIrcUserEntry::HalfOp, KviIrcUserEntry::host(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcMask::matchesFixed(), KviIrcUserEntry::ModeMask, KviUserListEntry::next(), KviUserListEntry::nick(), KviIrcUserEntry::Op, pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviIrcUserEntry::user(), KviChannelWindow::userListView(), KviIrcUserEntry::UserOp, KviIrcUserEntry::Voice, and x.
Referenced by chan_module_init().
static bool chan_kvs_fnc_voicecount (KviKvsModuleFunctionCall * c) [static]
References chan_kvs_find_channel(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviChannelWindow::voiceCount().
Referenced by chan_module_init().
static bool chan_module_cleanup (KviModule *) [static]
static bool chan_module_init (KviModule * m) [static]
References chan_kvs_fnc_admincount(), chan_kvs_fnc_bancount(), chan_kvs_fnc_banexceptioncount(), chan_kvs_fnc_banexceptionlist(), chan_kvs_fnc_banlist(), chan_kvs_fnc_common(), chan_kvs_fnc_getflag(), chan_kvs_fnc_getUrl(), chan_kvs_fnc_halfopcount(), chan_kvs_fnc_invitecount(), chan_kvs_fnc_invitelist(), chan_kvs_fnc_isdead(), chan_kvs_fnc_ison(), chan_kvs_fnc_key(), chan_kvs_fnc_limit(), chan_kvs_fnc_maskcount(), chan_kvs_fnc_masklist(), chan_kvs_fnc_matchban(), chan_kvs_fnc_matchbanexception(), chan_kvs_fnc_matchinvite(), chan_kvs_fnc_matchmask(), chan_kvs_fnc_matchqban(), chan_kvs_fnc_mode(), chan_kvs_fnc_modeParam(), chan_kvs_fnc_name(), chan_kvs_fnc_opcount(), chan_kvs_fnc_ownercount(), chan_kvs_fnc_topic(), chan_kvs_fnc_topicsetat(), chan_kvs_fnc_topicsetby(), chan_kvs_fnc_usercount(), chan_kvs_fnc_userjointime(), chan_kvs_fnc_userlastactiontime(), chan_kvs_fnc_usermodelevel(), chan_kvs_fnc_useropcount(), chan_kvs_fnc_users(), chan_kvs_fnc_voicecount(), and KVSM_REGISTER_FUNCTION.