KVIrc: src/modules/window/libkviwindow.cpp File Reference
libkviwindow.cpp File Reference
#include "UserWindow.h"
#include "KviModule.h"
#include "KviConsoleWindow.h"
#include "KviOptions.h"
#include "KviIrcSocket.h"
#include "KviMainWindow.h"
#include "KviLocale.h"
#include "KviApplication.h"
#include "KviError.h"
#include "KviIrcView.h"
#include "KviInput.h"
#include "KviIconManager.h"
#include "KviModuleManager.h"
#include "KviMemory.h"
#include "KviMdiChild.h"
#include "KviChannelWindow.h"
#include "KviPointerHashTable.h"
#include <QTimer>
Macros
#define GET_KVS_FNC_WINDOW_ID
#define GET_KVS_WINDOW_ID
Functions
static bool window_kvs_cmd_activate (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_clearOutput (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_close (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_demandAttention (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_dock (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_highlight (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_insertInInputText (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_listtypes (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_maximize (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_minimize (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_restore (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_savePropertiesAsDefault (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_setBackground (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_setCryptEngine (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_setInputText (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_setWindowTitle (KviKvsModuleCommandCall *c)
static bool window_kvs_cmd_undock (KviKvsModuleCommandCall *c)
static bool window_kvs_fnc_activityLevel (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_activityTemperature (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_caption (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_console (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_context (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_cryptEngine (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_exists (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_hasInput (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_hasOutput (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_hasUserFocus (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_highlightLevel (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_inputText (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_isDocked (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_isMaximized (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_isMinimized (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_list (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_open (KviKvsModuleFunctionCall *c)
static bool window_kvs_fnc_type (KviKvsModuleFunctionCall *c)
static bool window_module_can_unload (KviModule *)
static bool window_module_cleanup (KviModule *)
static bool window_module_init (KviModule *m)
Variables
KVIRC_API KviPointerHashTable
< QString, KviWindow > * g_pGlobalWindowDict
KviPointerList< UserWindow > * g_pUserWindowList = 0
Macro Definition Documentation
#define GET_KVS_FNC_WINDOW_ID
Value:
QString szWnd; \
        KviWindow * pWnd; \
    KVSM_PARAMETERS_BEGIN(c) \
        KVSM_PARAMETER("window_id",KVS_PT_STRING,KVS_PF_OPTIONAL,szWnd) \
    KVSM_PARAMETERS_END(c) \
    if(c->parameterList()->count() == 0) \
        { \
                pWnd = c->window(); \
        } else { \
                pWnd = g_pApp->findWindow(szWnd.toUtf8().data()); \
        if(!pWnd) \
                        return true; \
        }
Referenced by window_kvs_fnc_activityLevel(), window_kvs_fnc_activityTemperature(), window_kvs_fnc_caption(), window_kvs_fnc_console(), window_kvs_fnc_context(), window_kvs_fnc_cryptEngine(), window_kvs_fnc_exists(), window_kvs_fnc_hasInput(), window_kvs_fnc_hasOutput(), window_kvs_fnc_hasUserFocus(), window_kvs_fnc_highlightLevel(), window_kvs_fnc_inputText(), window_kvs_fnc_isDocked(), window_kvs_fnc_isMaximized(), window_kvs_fnc_isMinimized(), and window_kvs_fnc_type().
#define GET_KVS_WINDOW_ID
Value:
QString szWnd; \
        KviWindow * pWnd; \
    KVSM_PARAMETERS_BEGIN(c) \
        KVSM_PARAMETER("window_id",KVS_PT_STRING,KVS_PF_OPTIONAL,szWnd) \
    KVSM_PARAMETERS_END(c) \
    if(c->parameterList()->count() == 0) \
        { \
                pWnd = c->window(); \
        } else { \
                pWnd = g_pApp->findWindow(szWnd.toUtf8().data()); \
        if(!pWnd) \
                { \
            if(!c->hasSwitch('q',"quiet")) \
                                c->warning(__tr2qs("The window with id '%s' does not exist"),szWnd.toUtf8().data()); \
                        return true; \
                } \
        }
Referenced by window_kvs_cmd_activate(), window_kvs_cmd_clearOutput(), window_kvs_cmd_close(), window_kvs_cmd_demandAttention(), window_kvs_cmd_dock(), window_kvs_cmd_maximize(), window_kvs_cmd_minimize(), window_kvs_cmd_restore(), window_kvs_cmd_savePropertiesAsDefault(), and window_kvs_cmd_undock().
Function Documentation
static bool window_kvs_cmd_activate (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_clearOutput (KviKvsModuleCommandCall * c) static
References KviWindow::Channel, KviIrcView::clearBuffer(), GET_KVS_WINDOW_ID, and KviChannelWindow::messageView().
Referenced by window_module_init().
static bool window_kvs_cmd_close (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_demandAttention (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_dock (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_highlight (KviKvsModuleCommandCall * c) static
References __tr2qs, KviKvsVariantList::count(), KviApplication::findWindow(), g_pApp, KviKvsModuleCommandCall::hasSwitch(), KviWindow::highlightMe(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsRunTimeCall::parameterList(), KviWindow::unhighlight(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by window_module_init().
static bool window_kvs_cmd_insertInInputText (KviKvsModuleCommandCall * c) static
References __tr2qs, KviApplication::findWindow(), g_pApp, KviKvsModuleCommandCall::hasSwitch(), KviWindow::input(), KviInput::insertText(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by window_module_init().
static bool window_kvs_cmd_listtypes (KviKvsModuleCommandCall * c) static
References KviWindow::listWindowTypes(), and KviKvsRunTimeCall::window().
Referenced by window_module_init().
static bool window_kvs_cmd_maximize (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_minimize (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_restore (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_savePropertiesAsDefault (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_cmd_setBackground (KviKvsModuleCommandCall * c) static
References __tr2qs, KviApplication::findWindow(), g_pApp, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsRunTimeCall::warning().
Referenced by window_module_init().
static bool window_kvs_cmd_setCryptEngine (KviKvsModuleCommandCall * c) static
References __tr2qs, e, KviApplication::findWindow(), g_pApp, g_pModuleManager, KviKvsModuleCommandCall::hasSwitch(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviModuleManager::loadModulesByCaps(), and KviKvsRunTimeCall::warning().
Referenced by window_module_init().
static bool window_kvs_cmd_setInputText (KviKvsModuleCommandCall * c) static
References __tr2qs, KviApplication::findWindow(), g_pApp, KviKvsModuleCommandCall::hasSwitch(), KviWindow::input(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviInput::setText(), and KviKvsRunTimeCall::warning().
Referenced by window_module_init().
static bool window_kvs_cmd_setWindowTitle (KviKvsModuleCommandCall * c) static
References __tr2qs, KviApplication::findWindow(), g_pApp, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::type(), KviWindow::UserWindow, and KviKvsRunTimeCall::warning().
Referenced by window_module_init().
static bool window_kvs_cmd_undock (KviKvsModuleCommandCall * c) static
References GET_KVS_WINDOW_ID.
Referenced by window_module_init().
static bool window_kvs_fnc_activityLevel (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), t(), and v.
Referenced by window_module_init().
static bool window_kvs_fnc_activityTemperature (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), t(), and v.
Referenced by window_module_init().
static bool window_kvs_fnc_caption (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by window_module_init().
static bool window_kvs_fnc_console (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by window_module_init().
static bool window_kvs_fnc_context (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by window_module_init().
static bool window_kvs_fnc_cryptEngine (KviKvsModuleFunctionCall * c) static
COMPILE_CRYPT_SUPPORT
COMPILE_CRYPT_SUPPORT
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by window_module_init().
static bool window_kvs_fnc_exists (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_hasInput (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_hasOutput (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_hasUserFocus (KviKvsModuleFunctionCall * c) static
References g_pActiveWindow, GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_highlightLevel (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and v.
Referenced by window_module_init().
static bool window_kvs_fnc_inputText (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by window_module_init().
static bool window_kvs_fnc_isDocked (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_isMaximized (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_isMinimized (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by window_module_init().
static bool window_kvs_fnc_list (KviKvsModuleFunctionCall * c) static
References __tr2qs, KviWindow::console(), KviWindow::context(), KviPointerHashTableIterator< Key, T >::current(), KviQString::equalCI(), g_pGlobalWindowDict, KviIrcContext::id(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by window_module_init().
static bool window_kvs_fnc_open (KviKvsModuleFunctionCall * c) static
References __tr2qs, KviMainWindow::addWindow(), KviKvsVariantList::count(), KviApplication::findConsole(), g_pApp, g_pIconManager, g_pMainWindow, KviIconManager::getImage(), UserWindow::HasInput, KviWindow::id(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::minimize(), KviKvsRunTimeCall::parameterList(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setInteger(), and KviKvsRunTimeCall::warning().
Referenced by window_module_init().
static bool window_kvs_fnc_type (KviKvsModuleFunctionCall * c) static
References GET_KVS_FNC_WINDOW_ID, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by window_module_init().
static bool window_module_can_unload (KviModule *) static
References KviPointerList< T >::isEmpty().
static bool window_module_cleanup (KviModule *) static
References KviPointerList< T >::first(), g_pUserWindowList, and w.
static bool window_module_init (KviModule * m) static
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, KviPointerList< T >::setAutoDelete(), window_kvs_cmd_activate(), window_kvs_cmd_clearOutput(), window_kvs_cmd_close(), window_kvs_cmd_demandAttention(), window_kvs_cmd_dock(), window_kvs_cmd_highlight(), window_kvs_cmd_insertInInputText(), window_kvs_cmd_listtypes(), window_kvs_cmd_maximize(), window_kvs_cmd_minimize(), window_kvs_cmd_restore(), window_kvs_cmd_savePropertiesAsDefault(), window_kvs_cmd_setBackground(), window_kvs_cmd_setCryptEngine(), window_kvs_cmd_setInputText(), window_kvs_cmd_setWindowTitle(), window_kvs_cmd_undock(), window_kvs_fnc_activityLevel(), window_kvs_fnc_activityTemperature(), window_kvs_fnc_caption(), window_kvs_fnc_console(), window_kvs_fnc_context(), window_kvs_fnc_cryptEngine(), window_kvs_fnc_exists(), window_kvs_fnc_hasInput(), window_kvs_fnc_hasOutput(), window_kvs_fnc_hasUserFocus(), window_kvs_fnc_highlightLevel(), window_kvs_fnc_inputText(), window_kvs_fnc_isDocked(), window_kvs_fnc_isMaximized(), window_kvs_fnc_isMinimized(), window_kvs_fnc_list(), window_kvs_fnc_open(), and window_kvs_fnc_type().
Variable Documentation
KVIRC_API KviPointerHashTable<QString,KviWindow>* g_pGlobalWindowDict
Referenced by KviApplication::connectionExists(), KviTrayIconWidget::doAway(), KviTrayIconWidget::fillContextPopup(), KviApplication::findConsole(), KviApplication::findWindow(), KviApplication::findWindowByCaption(), KviApplication::heartbeat(), KviApplication::registerWindow(), KviApplication::resetAvatarForMatchingUsers(), KviApplication::restartLagMeters(), KviApplication::restartNotifyLists(), KviIrcUrl::run(), KviApplication::setAvatarFromOptions(), KviApplication::setup(), KviApplication::topmostConnectedConsole(), KviApplication::unregisterWindow(), window_kvs_fnc_list(), KviApplication::windowCount(), KviApplication::windowExists(), and KviApplication::~KviApplication().
KviPointerList<UserWindow>* g_pUserWindowList = 0
Referenced by window_module_cleanup().