KVIrc: src/modules/tip/libkvitip.cpp File Reference
libkvitip.cpp File Reference
#include "libkvitip.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviApplication.h"
#include "KviIconManager.h"
#include "KviOptions.h"
#include "KviFileUtils.h"
#include <QPushButton>
#include <QFont>
#include <QPainter>
#include <QDesktopWidget>
#include <QCloseEvent>
Functions
static bool tip_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool tip_module_can_unload (KviModule *)
static bool tip_module_cleanup (KviModule *)
static bool tip_module_init (KviModule *m)
Variables
TipWindow * g_pTipWindow = 0
Function Documentation
static bool tip_kvs_cmd_open (KviKvsModuleCommandCall * c) static
References KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, TipWindow::nextTip(), and TipWindow::openConfig().
Referenced by tip_module_init().
static bool tip_module_can_unload (KviModule *) static
static bool tip_module_cleanup (KviModule *) static
static bool tip_module_init (KviModule * m) static
References KVSM_REGISTER_SIMPLE_COMMAND, and tip_kvs_cmd_open().
Variable Documentation
TipWindow* g_pTipWindow = 0