KVIrc: src/modules/eventeditor/libkvieventeditor.cpp File Reference
src/modules/eventeditor/libkvieventeditor.cpp File Reference
#include "EventEditorWindow.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
Functions
static bool eventeditor_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool eventeditor_module_can_unload (KviModule *)
static bool eventeditor_module_cleanup (KviModule *)
static bool eventeditor_module_init (KviModule *m)
Variables
EventEditorWindow * g_pEventEditorWindow = 0
Function Documentation
static bool eventeditor_kvs_cmd_open (KviKvsModuleCommandCall * c) [static]
References KviMainWindow::addWindow(), KviWindow::frame(), KviWindow::setFocus(), and KviKvsRunTimeCall::window().
Referenced by eventeditor_module_init().
static bool eventeditor_module_can_unload (KviModule *) [static]
static bool eventeditor_module_cleanup (KviModule *) [static]
References KviMainWindow::closeWindow(), and g_pMainWindow.
static bool eventeditor_module_init (KviModule * m) [static]
References eventeditor_kvs_cmd_open(), and KVSM_REGISTER_SIMPLE_COMMAND.
Variable Documentation
EventEditorWindow* g_pEventEditorWindow = 0