KVIrc: src/modules/rijndael/libkvirijndael.cpp File Reference
src/modules/rijndael/libkvirijndael.cpp File Reference
#include "libkvirijndael.h"
#include "Rijndael.h"
#include "KviModule.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviControlCodes.h"
#include "UglyBase64.h"
#include "InitVectorEngine.h"
Functions
static bool rijndael_module_can_unload (KviModule *)
static bool rijndael_module_cleanup (KviModule *m)
static bool rijndael_module_init (KviModule *m)
Function Documentation
static bool rijndael_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool rijndael_module_cleanup (KviModule * m) [static]
References KviPointerList< T >::first().
static bool rijndael_module_init (KviModule * m) [static]
References __tr2qs, KviCryptEngine::CanDecrypt, KviCryptEngine::CanEncrypt, d, KviModule::m_szName, KviPointerList< T >::setAutoDelete(), KviCryptEngine::WantDecryptKey, and KviCryptEngine::WantEncryptKey.