KVIrc: src/modules/list/libkvilist.cpp File Reference
libkvilist.cpp File Reference
#include "ListWindow.h"
#include "KviModule.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include <QSplitter>
Functions
static bool list_kvs_cmd_open (KviKvsModuleCommandCall *c)
static bool list_module_can_unload (KviModule *)
static bool list_module_cleanup (KviModule *)
static bool list_module_init (KviModule *m)
Variables
KviPointerList< ListWindow > * g_pListWindowList = 0
Function Documentation
static bool list_kvs_cmd_open (KviKvsModuleCommandCall * c) static
References __tr2qs, KviMainWindow::addWindow(), KviWindow::console(), KviKvsRunTimeCall::context(), KviWindow::context(), KviKvsRunTimeContext::errorNoIrcContext(), g_pMainWindow, KviIrcContext::listWindow(), w, KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by list_module_init().
static bool list_module_can_unload (KviModule *) static
References KviPointerList< T >::isEmpty().
static bool list_module_cleanup (KviModule *) static
References ListWindow::die(), KviPointerList< T >::first(), and g_pListWindowList.
static bool list_module_init (KviModule * m) static
References KVSM_REGISTER_SIMPLE_COMMAND, list_kvs_cmd_open(), and KviPointerList< T >::setAutoDelete().
Variable Documentation
KviPointerList<ListWindow>* g_pListWindowList = 0
Referenced by list_module_cleanup().