KVIrc: src/modules/system/libkvisystem.cpp File Reference
libkvisystem.cpp File Reference
#include "Plugin.h"
#include "kvi_settings.h"
#include "KviModule.h"
#include "KviCString.h"
#include "KviThread.h"
#include "KviLocale.h"
#include "KviApplication.h"
#include "KviEnvironment.h"
#include "KviRuntimeInfo.h"
#include "KviModuleManager.h"
#include "KviByteOrder.h"
#include <QClipboard>
#include <QByteArray>
#include <sys/utsname.h>
#include <stdlib.h>
#include <unistd.h>
#include <QProcess>
#include <QStringList>
Functions
static bool system_kvs_cmd_runcmd (KviKvsModuleCommandCall *c)
static bool system_kvs_cmd_setClipboard (KviKvsModuleCommandCall *c)
static bool system_kvs_cmd_setenv (KviKvsModuleCommandCall *c)
static bool system_kvs_cmd_setSelection (KviKvsModuleCommandCall *c)
static bool system_kvs_fnc_checkModule (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_clipboard (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_dbus (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_getenv (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_hostname (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_htoni (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_ntohi (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_osmachine (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_osname (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_osnodename (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_osrelease (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_ostype (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_osversion (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_plugin_call (KviKvsModuleFunctionCall *c)
static bool system_kvs_fnc_selection (KviKvsModuleFunctionCall *c)
static bool system_module_can_unload (KviModule *)
static bool system_module_cleanup (KviModule *)
static bool system_module_init (KviModule *m)
Variables
PluginManager * g_pPluginManager
Function Documentation
static bool system_kvs_cmd_runcmd (KviKvsModuleCommandCall * c) static
References __tr2qs, KviKvsRunTimeCall::error(), KviKvsSwitchList::getAsStringIfExisting(), KVS_PF_APPENDREMAINING, KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviKvsModuleCommandCall::switches().
Referenced by system_module_init().
static bool system_kvs_cmd_setClipboard (KviKvsModuleCommandCall * c) static
References g_pApp, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by system_module_init().
static bool system_kvs_cmd_setenv (KviKvsModuleCommandCall * c) static
References KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviEnvironment::setVariable(), and KviEnvironment::unsetVariable().
Referenced by system_module_init().
static bool system_kvs_cmd_setSelection (KviKvsModuleCommandCall * c) static
References g_pApp, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by system_module_init().
static bool system_kvs_fnc_checkModule (KviKvsModuleFunctionCall * c) static
References g_pModuleManager, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviModuleManager::loadModule(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by system_module_init().
static bool system_kvs_fnc_clipboard (KviKvsModuleFunctionCall * c) static
References g_pApp, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_dbus (KviKvsModuleFunctionCall * c) static
References __tr2qs, KviCString::cutToFirst(), KviCString::isEmpty(), kvi_strEqualCI(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVS_PT_STRINGLIST, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviCString::leftToFirst(), KviCString::ptr(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setArray(), KviKvsVariant::setInteger(), KviKvsVariant::setString(), KviCString::toInt(), KviCString::toUInt(), v, and KviKvsRunTimeCall::warning().
Referenced by system_module_init().
static bool system_kvs_fnc_getenv (KviKvsModuleFunctionCall * c) static
References KviEnvironment::getVariable(), KVS_PT_NONEMPTYSTRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_hostname (KviKvsModuleFunctionCall * c) static
References KviRuntimeInfo::hostname(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_htoni (KviKvsModuleFunctionCall * c) static
References __tr2qs, KviKvsRunTimeCall::error(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviByteOrder::localCpuToNetworkByteOrder16(), KviByteOrder::localCpuToNetworkByteOrder32(), KviByteOrder::localCpuToNetworkByteOrder64(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by system_module_init().
static bool system_kvs_fnc_ntohi (KviKvsModuleFunctionCall * c) static
References __tr2qs, KviKvsRunTimeCall::error(), KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviByteOrder::networkByteOrderToLocalCpu16(), KviByteOrder::networkByteOrderToLocalCpu32(), KviByteOrder::networkByteOrderToLocalCpu64(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by system_module_init().
static bool system_kvs_fnc_osmachine (KviKvsModuleFunctionCall * c) static
References KviRuntimeInfo::machine(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_osname (KviKvsModuleFunctionCall * c) static
References KviRuntimeInfo::name(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_osnodename (KviKvsModuleFunctionCall * c) static
References KviRuntimeInfo::nodename(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_osrelease (KviKvsModuleFunctionCall * c) static
References KviRuntimeInfo::release(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_kvs_fnc_ostype (KviKvsModuleFunctionCall * c) static
References KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviRuntimeInfo::type().
Referenced by system_module_init().
static bool system_kvs_fnc_osversion (KviKvsModuleFunctionCall * c) static
References KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviRuntimeInfo::version().
Referenced by system_module_init().
static bool system_kvs_fnc_plugin_call (KviKvsModuleFunctionCall * c) static
References PluginManager::pluginCall().
Referenced by system_module_init().
static bool system_kvs_fnc_selection (KviKvsModuleFunctionCall * c) static
References g_pApp, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by system_module_init().
static bool system_module_can_unload (KviModule *) static
References PluginManager::checkUnload().
static bool system_module_cleanup (KviModule *) static
References g_pPluginManager, and PluginManager::unloadAll().
static bool system_module_init (KviModule * m) static
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, system_kvs_cmd_runcmd(), system_kvs_cmd_setClipboard(), system_kvs_cmd_setenv(), system_kvs_cmd_setSelection(), system_kvs_fnc_checkModule(), system_kvs_fnc_clipboard(), system_kvs_fnc_dbus(), system_kvs_fnc_getenv(), system_kvs_fnc_hostname(), system_kvs_fnc_htoni(), system_kvs_fnc_ntohi(), system_kvs_fnc_osmachine(), system_kvs_fnc_osname(), system_kvs_fnc_osnodename(), system_kvs_fnc_osrelease(), system_kvs_fnc_ostype(), system_kvs_fnc_osversion(), system_kvs_fnc_plugin_call(), and system_kvs_fnc_selection().
Variable Documentation
PluginManager* g_pPluginManager
Referenced by system_module_cleanup().