KVIrc: src/modules/codetester/libkvicodetester.cpp File Reference
src/modules/codetester/libkvicodetester.cpp File Reference
#include "CodeTesterWindow.h"
#include "KviModule.h"
#include "KviLocale.h"
#include "KviMainWindow.h"
#include "KviPointerList.h"
Functions
static bool codetester_kvs_cmd_open (KviKvsModuleCommandCall *)
static bool codetester_module_can_unload (KviModule *)
static bool codetester_module_cleanup (KviModule *)
static bool codetester_module_init (KviModule *m)
Variables
KviPointerList
< CodeTesterWindow > * g_pCodeTesterWindowList = 0
Function Documentation
static bool codetester_kvs_cmd_open (KviKvsModuleCommandCall *) [static]
References KviMainWindow::addWindow(), g_pMainWindow, and w.
Referenced by codetester_module_init().
static bool codetester_module_can_unload (KviModule *) [static]
References KviPointerList< T >::count().
static bool codetester_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first(), and w.
static bool codetester_module_init (KviModule * m) [static]
References codetester_kvs_cmd_open(), KVSM_REGISTER_SIMPLE_COMMAND, and KviPointerList< T >::setAutoDelete().
Variable Documentation
KviPointerList<CodeTesterWindow>* g_pCodeTesterWindowList = 0