KVIrc: src/modules/torrent/libkvitorrent.cpp File Reference
libkvitorrent.cpp File Reference
#include "TorrentInterface.h"
#include "KTorrentDbusInterface.h"
#include "StatusBarApplet.h"
#include "KviModule.h"
#include "KviOptions.h"
#include "KviMainWindow.h"
#include "KviLocale.h"
#include "kvi_out.h"
Macros
#define TC_KVS_COMMAND(__name) static bool torrent_kvs_cmd_ ## __name (KviKvsModuleCommandCall * c)
#define TC_KVS_COMMAND_ERROR
#define TC_KVS_FAIL_ON_NO_INTERFACE
#define TC_KVS_FLOATRET_FUNCTION(__name, __ifacecommand)
#define TC_KVS_FUNCTION(__name) static bool torrent_kvs_fnc_ ## __name (KviKvsModuleFunctionCall * c)
#define TC_KVS_INT_COMMAND(__name, __ifacecommand, __argname)
#define TC_KVS_INT_INT_STRING_COMMAND(__name, __ifacecommand, __argname1, __argname2, __argname3)
#define TC_KVS_INTRET_FUNCTION(__name, __ifacecommand)
#define TC_KVS_INTRET_INT_FUNCTION(__name, __ifacecommand, __argname)
#define TC_KVS_INTRET_INT_INT_FUNCTION(__name, __ifacecommand, __argname1, __argname2)
#define TC_KVS_REGCMD(__name, __stringname) KVSM_REGISTER_SIMPLE_COMMAND(m, __stringname, torrent_kvs_cmd_ ## __name)
#define TC_KVS_REGFNC(__name, __stringname) KVSM_REGISTER_FUNCTION(m, __stringname, torrent_kvs_fnc_ ## __name)
#define TC_KVS_SIMPLE_COMMAND(__name, __ifacecommand)
#define TC_KVS_STRINGRET_FUNCTION(__name, __ifacecommand)
#define TC_KVS_STRINGRET_INT_FUNCTION(__name, __ifacecommand, __argname)
#define TC_KVS_STRINGRET_INT_INT_FUNCTION(__name, __ifacecommand, __argname1, __argname2)
Functions
static TorrentInterface * auto_detect_torrent_client (KviWindow *pOut=0)
TC_KVS_COMMAND (detect)
TC_KVS_COMMAND (setClient)
TC_KVS_FUNCTION (client)
TC_KVS_FUNCTION (clientList)
static bool torrent_module_can_unload (KviModule *)
static bool torrent_module_cleanup (KviModule *)
static bool torrent_module_ctrl (KviModule *, const char *, void *)
static bool torrent_module_init (KviModule *m)
Variables
static KviPointerList
< TorrentInterfaceDescriptor > * g_pDescriptorList = 0
Macro Definition Documentation
#define TC_KVS_COMMAND (__name) static bool torrent_kvs_cmd_ ## __name (KviKvsModuleCommandCall * c)
#define TC_KVS_COMMAND_ERROR
Value:
if (!c->hasSwitch('q',"quiet")) \
                        { \
                c->warning(__tr2qs_ctx("The selected torrent client interface failed to execute the requested function", "torrent")); \
                                QString tmp = __tr2qs_ctx("Last interface error: ", "torrent"); \
                                tmp += TorrentInterface::selected()->lastError(); \
                c->warning(tmp); \
                        } \
#define TC_KVS_FAIL_ON_NO_INTERFACE
Value:
if (!TorrentInterface::selected()) \
        { \
        c->warning(__tr2qs_ctx("No torrent client interface selected. Try /torrent.detect", "torrent")); \
                return true; \
        }
#define TC_KVS_FLOATRET_FUNCTION (__name, __ifacecommand)
Value:
TC_KVS_FUNCTION(__name) \
        { \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        kvs_real_t ret = TorrentInterface::selected()->__ifacecommand(); \
        c->returnValue()->setReal(ret); \
                return true; \
        }
#define TC_KVS_FUNCTION (__name) static bool torrent_kvs_fnc_ ## __name (KviKvsModuleFunctionCall * c)
#define TC_KVS_INT_COMMAND (__name, __ifacecommand, __argname)
Value:
TC_KVS_COMMAND(__name) \
        { \
        kvs_int_t arg; \
        KVSM_PARAMETERS_BEGIN(c) \
            KVSM_PARAMETER(__argname, KVS_PT_INT, 0, arg) \
        KVSM_PARAMETERS_END(c) \
        \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        \
        if (!TorrentInterface::selected()->__ifacecommand(arg)) \
                { \
            TC_KVS_COMMAND_ERROR \
                } \
                return true; \
        }
#define TC_KVS_INT_INT_STRING_COMMAND (__name, __ifacecommand, __argname1, __argname2, __argname3)
Value:
TC_KVS_COMMAND(__name) \
        { \
        kvs_int_t arg1; \
        kvs_int_t arg2; \
                QString arg3; \
        KVSM_PARAMETERS_BEGIN(c) \
            KVSM_PARAMETER(__argname1, KVS_PT_INT, 0, arg1) \
            KVSM_PARAMETER(__argname2, KVS_PT_INT, 0, arg2) \
            KVSM_PARAMETER(__argname3, KVS_PT_STRING, 0, arg3) \
        KVSM_PARAMETERS_END(c) \
        \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        \
        if (!TorrentInterface::selected()->__ifacecommand(arg1, arg2, arg3)) \
                { \
            TC_KVS_COMMAND_ERROR \
                } \
                return true; \
        }
#define TC_KVS_INTRET_FUNCTION (__name, __ifacecommand)
Value:
TC_KVS_FUNCTION(__name) \
        { \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        kvs_int_t ret = TorrentInterface::selected()->__ifacecommand(); \
        c->returnValue()->setInteger(ret); \
                return true; \
        }
#define TC_KVS_INTRET_INT_FUNCTION (__name, __ifacecommand, __argname)
Value:
TC_KVS_FUNCTION(__name) \
        { \
        kvs_int_t arg; \
        KVSM_PARAMETERS_BEGIN(c) \
            KVSM_PARAMETER(__argname, KVS_PT_INT, 0, arg) \
        KVSM_PARAMETERS_END(c) \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        kvs_int_t ret = TorrentInterface::selected()->__ifacecommand(arg); \
        c->returnValue()->setInteger(ret); \
                return true; \
        }
#define TC_KVS_INTRET_INT_INT_FUNCTION (__name, __ifacecommand, __argname1, __argname2)
Value:
TC_KVS_FUNCTION(__name) \
        { \
        kvs_int_t arg1; \
        kvs_int_t arg2; \
        KVSM_PARAMETERS_BEGIN(c) \
            KVSM_PARAMETER(__argname1, KVS_PT_INT, 0, arg1) \
            KVSM_PARAMETER(__argname2, KVS_PT_INT, 0, arg2) \
        KVSM_PARAMETERS_END(c) \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        kvs_int_t ret = TorrentInterface::selected()->__ifacecommand(arg1, arg2); \
        c->returnValue()->setInteger(ret); \
                return true; \
        }
#define TC_KVS_REGCMD (__name, __stringname) KVSM_REGISTER_SIMPLE_COMMAND(m, __stringname, torrent_kvs_cmd_ ## __name)
Referenced by torrent_module_init().
#define TC_KVS_REGFNC (__name, __stringname) KVSM_REGISTER_FUNCTION(m, __stringname, torrent_kvs_fnc_ ## __name)
Referenced by torrent_module_init().
#define TC_KVS_SIMPLE_COMMAND (__name, __ifacecommand)
Value:
TC_KVS_COMMAND(__name) \
        { \
        KVSM_PARAMETERS_BEGIN(c) \
        KVSM_PARAMETERS_END(c) \
        \
        TC_KVS_FAIL_ON_NO_INTERFACE \
        \
        if (!TorrentInterface::selected()->__ifacecommand()) \
                { \
            TC_KVS_COMMAND_ERROR \
                } \
                return true; \
        }
#define TC_KVS_STRINGRET_FUNCTION (__name, __ifacecommand)
Value:
TC_KVS_FUNCTION(__name) \
        { \
                TC_KVS_FAIL_ON_NO_INTERFACE \
                QString szRet = TorrentInterface::selected()->__ifacecommand(); \
        c->returnValue()->setString(szRet); \
                return true; \
        }
#define TC_KVS_STRINGRET_INT_FUNCTION (__name, __ifacecommand, __argname)
Value:
TC_KVS_FUNCTION(__name) \
        { \
        kvs_int_t arg; \
        KVSM_PARAMETERS_BEGIN(c) \
            KVSM_PARAMETER(__argname, KVS_PT_INT, 0, arg) \
        KVSM_PARAMETERS_END(c) \
                TC_KVS_FAIL_ON_NO_INTERFACE \
                QString szRet = TorrentInterface::selected()->__ifacecommand(arg); \
        c->returnValue()->setString(szRet); \
                return true; \
        }
#define TC_KVS_STRINGRET_INT_INT_FUNCTION (__name, __ifacecommand, __argname1, __argname2)
Value:
TC_KVS_FUNCTION(__name) \
        { \
        kvs_int_t arg1; \
        kvs_int_t arg2; \
        KVSM_PARAMETERS_BEGIN(c) \
            KVSM_PARAMETER(__argname1, KVS_PT_INT, 0, arg1) \
            KVSM_PARAMETER(__argname2, KVS_PT_INT, 0, arg2) \
        KVSM_PARAMETERS_END(c) \
                TC_KVS_FAIL_ON_NO_INTERFACE \
                QString szRet = TorrentInterface::selected()->__ifacecommand(arg1, arg2); \
        c->returnValue()->setString(szRet); \
                return true; \
        }
Function Documentation
static TorrentInterface* auto_detect_torrent_client (KviWindow * pOut = 0) static
References __tr2qs_ctx(), d, TorrentInterface::detect(), KviPointerList< T >::first(), i, TorrentInterfaceDescriptor::instance(), KVI_OPTION_STRING, KVI_OUT_TORRENT, KviOption_stringPreferredTorrentClient, TorrentInterfaceDescriptor::name(), and KviPointerList< T >::next().
Referenced by TC_KVS_COMMAND(), and torrent_module_init().
TC_KVS_COMMAND (detect)
References auto_detect_torrent_client(), c, and TorrentInterface::select().
TC_KVS_COMMAND (setClient)
References __tr2qs_ctx(), c, d, KviPointerList< T >::first(), KVI_OPTION_STRING, KVI_OUT_TORRENT, KviOption_stringPreferredTorrentClient, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviPointerList< T >::next(), and TorrentInterface::select().
TC_KVS_FUNCTION (client)
References c, KVI_OPTION_STRING, and KviOption_stringPreferredTorrentClient.
TC_KVS_FUNCTION (clientList)
References c, d, KviPointerList< T >::first(), KviPointerList< T >::next(), pArray, and KviKvsArray::set().
static bool torrent_module_can_unload (KviModule *) static
static bool torrent_module_cleanup (KviModule *) static
References g_pDescriptorList.
static bool torrent_module_ctrl (KviModule * , const char * , void *) static
static bool torrent_module_init (KviModule * m) static
References KviPointerList< T >::append(), auto_detect_torrent_client(), d, KviPointerList< T >::first(), g_pMainWindow, KVI_OPTION_STRING, KviOption_stringPreferredMediaPlayer, KviOption_stringPreferredTorrentClient, KviMainWindow::mainStatusBar(), KviOsInfo::name(), KviPointerList< T >::next(), TorrentInterface::select(), StatusBarApplet::selfRegister(), KviPointerList< T >::setAutoDelete(), TC_KVS_REGCMD, and TC_KVS_REGFNC.
Variable Documentation
KviPointerList<TorrentInterfaceDescriptor>* g_pDescriptorList = 0 static
Referenced by torrent_module_cleanup().