KVIrc: src/modules/proxydb/libkviproxydb.cpp File Reference
src/modules/proxydb/libkviproxydb.cpp File Reference
#include "KviModule.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviProxy.h"
#include "KviProxyDataBase.h"
#include <QString>
#include <QHostAddress>
Defines
#define PROXYDB_GET_PROPERTY(__functionName, __callName, __variantSetCallName)
#define PROXYDB_SET_PROPERTY(__functionName, __callName)
Functions
static bool proxydb_kvs_cmd_addProxy (KviKvsModuleCommandCall *c)
static bool proxydb_kvs_cmd_setIp (KviKvsModuleCommandCall *c)
static bool proxydb_kvs_cmd_setIPv6 (KviKvsModuleCommandCall *c)
static bool proxydb_kvs_cmd_setPort (KviKvsModuleCommandCall *c)
static bool proxydb_kvs_cmd_setProtocol (KviKvsModuleCommandCall *c)
static bool proxydb_kvs_fnc_protocol (KviKvsModuleFunctionCall *c)
static bool proxydb_module_can_unload (KviModule *)
static bool proxydb_module_cleanup (KviModule *)
static bool proxydb_module_init (KviModule *m)
Variables
KVIRC_API KviProxyDataBase * g_pProxyDataBase
Define Documentation
#define PROXYDB_GET_PROPERTY (__functionName, __callName, __variantSetCallName)
Value:
static bool __functionName(KviKvsModuleFunctionCall * c) \
        { \
                QString szProxy; \
                \
                KVSM_PARAMETERS_BEGIN(c) \
                        KVSM_PARAMETER("proxy",KVS_PT_STRING,0,szProxy) \
                KVSM_PARAMETERS_END(c) \
                \
                if(szProxy.isEmpty()) \
                { \
                        c->error(__tr2qs_ctx("You must provide the proxy hostname as parameter","serverdb")); \
                        return false; \
                } \
                \
                KviProxy * pProxy = new KviProxy(); \
                pProxy->setHostname(szProxy); \
                \
                KviProxy * pRecord = g_pProxyDataBase->findProxy(pProxy,true); \
                if(!pRecord) \
                { \
                        c->error(__tr2qs_ctx("The specified proxy does not exist","serverdb")); \
                        return false; \
                } \
                \
                c->returnValue()->__variantSetCallName(pRecord->__callName()); \
                \
                return true; \
        }
#define PROXYDB_SET_PROPERTY (__functionName, __callName)
Function Documentation
static bool proxydb_kvs_cmd_addProxy (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviProxyDataBase::findProxy(), g_pProxyDataBase, KviProxy::Http, KviProxyDataBase::insertProxy(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviProxy::setHostname(), KviProxy::setIPv6(), KviProxy::setPass(), KviProxy::setPort(), KviProxy::setProtocol(), KviProxy::setUser(), KviProxy::Socks4, KviProxy::Socks5, and uPort.
Referenced by proxydb_module_init().
static bool proxydb_kvs_cmd_setIp (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviProxyDataBase::findProxy(), g_pProxyDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviProxy::setHostname(), KviProxy::setIp(), and KviKvsModuleCommandCall::switches().
Referenced by proxydb_module_init().
static bool proxydb_kvs_cmd_setIPv6 (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviProxyDataBase::findProxy(), g_pProxyDataBase, KVS_PT_BOOLEAN, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviProxy::setHostname(), KviProxy::setIPv6(), and KviKvsModuleCommandCall::switches().
Referenced by proxydb_module_init().
static bool proxydb_kvs_cmd_setPort (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviProxyDataBase::findProxy(), g_pProxyDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviProxy::setHostname(), KviProxy::setPort(), KviKvsModuleCommandCall::switches(), and uPort.
Referenced by proxydb_module_init().
static bool proxydb_kvs_cmd_setProtocol (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviKvsSwitchList::find(), KviProxyDataBase::findProxy(), g_pProxyDataBase, KviProxy::Http, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviProxy::setHostname(), KviProxy::setProtocol(), KviProxy::Socks4, KviProxy::Socks5, and KviKvsModuleCommandCall::switches().
Referenced by proxydb_module_init().
static bool proxydb_kvs_fnc_protocol (KviKvsModuleFunctionCall * c) [static]
References __tr2qs_ctx(), KviKvsRunTimeCall::error(), KviProxyDataBase::findProxy(), g_pProxyDataBase, KviProxy::Http, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviProxy::protocol(), KviKvsModuleFunctionCall::returnValue(), KviProxy::setHostname(), KviKvsVariant::setString(), KviProxy::Socks4, and KviProxy::Socks5.
Referenced by proxydb_module_init().
static bool proxydb_module_can_unload (KviModule *) [static]
static bool proxydb_module_cleanup (KviModule *) [static]
static bool proxydb_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, proxydb_kvs_cmd_addProxy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), and proxydb_kvs_fnc_protocol().
Variable Documentation
KVIRC_API KviProxyDataBase* g_pProxyDataBase
Referenced by OptionsWidget_proxy::commit(), KviIrcContext::connectToCurrentServer(), OptionsWidget_proxy::fillProxyList(), IrcServerDetailsWidget::IrcServerDetailsWidget(), proxydb_kvs_cmd_addProxy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), proxydb_kvs_fnc_protocol(), KviIrcConnectionTargetResolver::proxyLookupTerminated(), KviApplication::saveProxyDataBase(), KviApplication::setup(), and KviApplication::~KviApplication().