KVIrc: src/modules/http/libkvihttp.cpp File Reference
src/modules/http/libkvihttp.cpp File Reference
#include "HttpFileTransfer.h"
#include "KviModule.h"
#include "KviCString.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviFileDialog.h"
#include "KviWindow.h"
#include "KviError.h"
#include "KviCommandFormatter.h"
Functions
static bool http_kvs_cmd_asyncGet (KviKvsModuleCallbackCommandCall *c)
static bool http_kvs_cmd_get (KviKvsModuleCommandCall *c)
static bool http_kvs_complete_get (KviKvsModuleCommandCall *c, QString &szUrl, QString &szFileName, const QString &szCallback)
static bool http_module_can_unload (KviModule *)
static bool http_module_cleanup (KviModule *)
static bool http_module_init (KviModule *m)
Function Documentation
static bool http_kvs_cmd_asyncGet (KviKvsModuleCallbackCommandCall * c) [static]
References KviKvsModuleCallbackCommandCall::callback(), KviKvsScript::code(), http_kvs_complete_get(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and szUrl.
Referenced by http_module_init().
static bool http_kvs_cmd_get (KviKvsModuleCommandCall * c) [static]
References http_kvs_complete_get(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and szUrl.
Referenced by http_module_init().
static bool http_kvs_complete_get (KviKvsModuleCommandCall * c, QString & szUrl, QString & szFileName, const QString & szCallback) [static]
References __tr2qs_ctx(), KviFileDialog::askForSaveFileName(), KviQString::equalCI(), KviKvsSwitchList::find(), g_pApp, KviKvsSwitchList::getAsStringIfExisting(), KviApplication::getLocalKvircDirectory(), KviHttpRequest::HeadersOnly, KviApplication::Incoming, KviFileTransfer::invokeTransferWindow(), KviHttpRequest::lastError(), KviHttpRequest::Overwrite, KviHttpRequest::RenameExisting, KviHttpRequest::RenameIncoming, HttpFileTransfer::request(), KviHttpRequest::Resume, HttpFileTransfer::setAutoClean(), HttpFileTransfer::setCompletionCallback(), KviHttpRequest::setConnectionTimeout(), KviHttpRequest::setContentOffset(), KviHttpRequest::setExistingFileAction(), KviHttpRequest::setFileName(), HttpFileTransfer::setMagicIdentifier(), KviHttpRequest::setMaxContentLength(), HttpFileTransfer::setNoOutput(), HttpFileTransfer::setNotifyCompletion(), KviHttpRequest::setPostData(), KviHttpRequest::setProcessingType(), KviHttpRequest::setUrl(), HttpFileTransfer::startDownload(), KviHttpRequest::StoreToFile, KviKvsModuleCommandCall::switches(), szUrl, v, KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by http_kvs_cmd_asyncGet(), and http_kvs_cmd_get().
static bool http_module_can_unload (KviModule *) [static]
References HttpFileTransfer::runningTransfers().
static bool http_module_cleanup (KviModule *) [static]
References HttpFileTransfer::done().
static bool http_module_init (KviModule * m) [static]
References http_kvs_cmd_asyncGet(), http_kvs_cmd_get(), HttpFileTransfer::init(), KVSM_REGISTER_CALLBACK_COMMAND, and KVSM_REGISTER_SIMPLE_COMMAND.