KVIrc: src/modules/rijndael/libkvirijndael_cryptopp.cpp File Reference
src/modules/rijndael/libkvirijndael_cryptopp.cpp File Reference
#include "libkvirijndael_cryptopp.h"
#include "KviModule.h"
#include "kvi_debug.h"
#include "KviLocale.h"
#include "KviMircCntrl.h"
#include "KviPointerList.h"
#include "KviCryptEngineDescription.h"
#include <cryptopp/aes.h>
#include <cryptopp/blowfish.h>
#include <cryptopp/modes.h>
#include <cryptopp/base64.h>
#include <cryptopp/hex.h>
#include <cryptopp/osrng.h>
#include <string>
Functions
static KviCryptEngine * allocMircryptionEngine ()
static KviCryptEngine * allocRijndael128Base64Engine ()
static KviCryptEngine * allocRijndael128HexEngine ()
static KviCryptEngine * allocRijndael192Base64Engine ()
static KviCryptEngine * allocRijndael192HexEngine ()
static KviCryptEngine * allocRijndael256Base64Engine ()
static KviCryptEngine * allocRijndael256HexEngine ()
static void deallocRijndaelCryptEngine (KviCryptEngine *e)
static bool rijndael_module_can_unload (KviModule *)
static bool rijndael_module_cleanup (KviModule *m)
static bool rijndael_module_init (KviModule *m)
Variables
static KviPointerList
< KviCryptEngine > * g_pEngineList = 0
Function Documentation
static KviCryptEngine* allocMircryptionEngine () [static]
Referenced by rijndael_module_init().
static KviCryptEngine* allocRijndael128Base64Engine () [static]
Referenced by rijndael_module_init().
static KviCryptEngine* allocRijndael128HexEngine () [static]
Referenced by rijndael_module_init().
static KviCryptEngine* allocRijndael192Base64Engine () [static]
Referenced by rijndael_module_init().
static KviCryptEngine* allocRijndael192HexEngine () [static]
Referenced by rijndael_module_init().
static KviCryptEngine* allocRijndael256Base64Engine () [static]
Referenced by rijndael_module_init().
static KviCryptEngine* allocRijndael256HexEngine () [static]
Referenced by rijndael_module_init().
static void deallocRijndaelCryptEngine (KviCryptEngine * e) [static]
References e.
Referenced by rijndael_module_init().
static bool rijndael_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool rijndael_module_cleanup (KviModule * m) [static]
References KviPointerList< T >::first(), and g_pEngineList.
static bool rijndael_module_init (KviModule * m) [static]
References __tr2qs, allocMircryptionEngine(), allocRijndael128Base64Engine(), allocRijndael128HexEngine(), allocRijndael192Base64Engine(), allocRijndael192HexEngine(), allocRijndael256Base64Engine(), allocRijndael256HexEngine(), KviCryptEngine::CanDecrypt, KviCryptEngine::CanEncrypt, d, deallocRijndaelCryptEngine(), KviModule::m_szName, KviPointerList< T >::setAutoDelete(), KviCryptEngine::WantDecryptKey, and KviCryptEngine::WantEncryptKey.
Variable Documentation
KviPointerList<KviCryptEngine>* g_pEngineList = 0 [static]
Referenced by lamerizer_module_cleanup(), rijndael_module_cleanup(), and rot13_module_cleanup().