KVIrc: src/modules/context/libkvicontext.cpp File Reference
libkvicontext.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviQString.h"
#include "KviWindow.h"
#include "KviMainWindow.h"
#include "KviConsoleWindow.h"
#include "KviApplication.h"
#include "KviIrcServer.h"
#include "KviIrcNetwork.h"
#include "KviIrcContext.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionServerInfo.h"
#include "KviIrcConnectionUserInfo.h"
#include "KviIrcConnectionTarget.h"
#include "KviIrcConnectionStatistics.h"
#include "KviIrcLink.h"
#include "KviIrcSocket.h"
Macros
#define GET_CONNECTION_FROM_STANDARD_PARAMS
#define GET_CONSOLE_FROM_STANDARD_PARAMS
#define STANDARD_IRC_CONNECTION_TARGET_PARAMETER(_fncName, _setCall)
#define STANDARD_SERVERINFO_TARGET_PARAMETER(_fncName, _setCall)
Functions
static bool context_kvs_cmd_clearQueue (KviKvsModuleCommandCall *c)
static bool context_kvs_fnc_getSSLCertInfo (KviKvsModuleFunctionCall *c)
static bool context_kvs_fnc_list (KviKvsModuleFunctionCall *c)
static bool context_kvs_fnc_queueSize (KviKvsModuleFunctionCall *c)
static bool context_module_cleanup (KviModule *)
static bool context_module_init (KviModule *m)
c returnValue () -> setString(pConnection->target() ->network() ->name())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverHostName, c->returnValue() ->setString(pConnection->currentServerName())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverdbServerHostName, c->returnValue() ->setString(pConnection->target() ->server() ->hostName())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverIpAddress, c->returnValue() ->setString(pConnection->target() ->server() ->ip())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverIsIPV6, c->returnValue() ->setBoolean(pConnection->target() ->server() ->isIPv6())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverIsSSL, c->returnValue() ->setBoolean(pConnection->target() ->server() ->useSSL())) STANDARD_SERVERINFO_TARGET_PARAMETER(context_kvs_fnc_serverSoftware, c->returnValue() ->setString(pConnection->serverInfo() ->software())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverPassword, c->returnValue() ->setString(pConnection->target() ->server() ->password())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverPort, c->returnValue() ->setInteger(pConnection->target() ->server() ->port())) static bool context_kvs_fnc_state(KviKvsModuleFunctionCall *c)
STANDARD_IRC_CONNECTION_TARGET_PARAMETER (context_kvs_fnc_networkName, c->returnValue() ->setString(pConnection->currentNetworkName())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverdbNetworkName
STANDARD_IRC_CONNECTION_TARGET_PARAMETER (context_kvs_fnc_connectionStartTime, c->returnValue() ->setInteger((kvs_int_t)(pConnection->statistics() ->connectionStartTime()));) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_lastMessageTime
Macro Definition Documentation
#define GET_CONNECTION_FROM_STANDARD_PARAMS
Value:
GET_CONSOLE_FROM_STANDARD_PARAMS        \
        KviIrcConnection * pConnection = NULL;  \
    if(pConsole)                            \
                pConnection = pConsole->context()->connection();
Referenced by context_kvs_fnc_queueSize().
#define GET_CONSOLE_FROM_STANDARD_PARAMS
Value:
kvs_uint_t iContextId;                                                     \
    KVSM_PARAMETERS_BEGIN(c)                                                   \
    KVSM_PARAMETER("irc_context_id", KVS_PT_UINT, KVS_PF_OPTIONAL, iContextId) \
    KVSM_PARAMETERS_END(c)                                                     \
        KviConsoleWindow * pConsole = NULL;                                        \
    if(c->parameterCount() > 0)                                                \
                pConsole = g_pApp->findConsole(iContextId);                            \
        else                                                                       \
                pConsole = c->window()->console();
Referenced by returnValue().
#define STANDARD_IRC_CONNECTION_TARGET_PARAMETER (_fncName, _setCall)
Value:
static bool _fncName(KviKvsModuleFunctionCall * c)               \
        {                                                                \
        GET_CONNECTION_FROM_STANDARD_PARAMS                          \
        if(pConnection)                                              \
                {                                                            \
            if(pConnection->target())                                \
                        {                                                        \
                                _setCall;                                            \
                                return true;                                         \
                        }                                                        \
                }                                                            \
        c->returnValue()->setNothing();                              \
                return true;                                                 \
        }
#define STANDARD_SERVERINFO_TARGET_PARAMETER (_fncName, _setCall)
Value:
static bool _fncName(KviKvsModuleFunctionCall * c)           \
        {                                                            \
        GET_CONNECTION_FROM_STANDARD_PARAMS                      \
        if(pConnection)                                          \
                {                                                        \
            if(pConnection->serverInfo())                        \
                        {                                                    \
                                _setCall;                                        \
                                return true;                                     \
                        }                                                    \
                }                                                        \
        c->returnValue()->setNothing();                          \
                return true;                                             \
        }
Function Documentation
static bool context_kvs_cmd_clearQueue (KviKvsModuleCommandCall * c) static
References KviIrcConnection::clearOutputQueue(), KviWindow::connection(), KviKvsSwitchList::find(), KVSM_REQUIRE_CONNECTION, KviKvsModuleCommandCall::switches(), and KviKvsRunTimeCall::window().
Referenced by context_module_init().
static bool context_kvs_fnc_getSSLCertInfo (KviKvsModuleFunctionCall * c) static
References __tr2qs, KviIrcContext::connection(), KviWindow::console(), KviConsoleWindow::context(), KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcConnection::link(), KviKvsRunTimeCall::parameterCount(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), KviIrcLink::socket(), KviIrcSocket::usingSSL(), KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by context_module_init().
static bool context_kvs_fnc_list (KviKvsModuleFunctionCall * c) static
References KviWindow::Console, KviPointerList< T >::first(), g_pMainWindow, KviPointerList< T >::next(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), and KviMainWindow::windowList().
Referenced by context_module_init().
static bool context_kvs_fnc_queueSize (KviKvsModuleFunctionCall * c) static
References GET_CONNECTION_FROM_STANDARD_PARAMS, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setInteger().
Referenced by context_module_init().
static bool context_module_cleanup (KviModule *) static
static bool context_module_init (KviModule * m) static
References context_kvs_cmd_clearQueue(), context_kvs_fnc_getSSLCertInfo(), context_kvs_fnc_list(), context_kvs_fnc_queueSize(), KVSM_REGISTER_FUNCTION, and KVSM_REGISTER_SIMPLE_COMMAND.
c returnValue () -> setString(pConnection->target() ->network() ->name())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverHostName, c->returnValue() ->setString(pConnection->currentServerName())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverdbServerHostName, c->returnValue() ->setString(pConnection->target() ->server() ->hostName())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverIpAddress, c->returnValue() ->setString(pConnection->target() ->server() ->ip())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverIsIPV6, c->returnValue() ->setBoolean(pConnection->target() ->server() ->isIPv6())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverIsSSL, c->returnValue() ->setBoolean(pConnection->target() ->server() ->useSSL())) STANDARD_SERVERINFO_TARGET_PARAMETER(context_kvs_fnc_serverSoftware, c->returnValue() ->setString(pConnection->serverInfo() ->software())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverPassword, c->returnValue() ->setString(pConnection->target() ->server() ->password())) STANDARD_IRC_CONNECTION_TARGET_PARAMETER(context_kvs_fnc_serverPort, c->returnValue() ->setInteger(pConnection->target() ->server() ->port())) static bool context_kvs_fnc_state(KviKvsModuleFunctionCall *c)
References KviIrcContext::Connected, KviIrcContext::Connecting, GET_CONSOLE_FROM_STANDARD_PARAMS, KviIrcContext::Idle, KviIrcContext::LoggingIn, and KviIrcContext::PendingReconnection.
STANDARD_IRC_CONNECTION_TARGET_PARAMETER (context_kvs_fnc_networkName , c-> returnValue) ->setString(pConnection->currentNetworkName())
STANDARD_IRC_CONNECTION_TARGET_PARAMETER (context_kvs_fnc_connectionStartTime , c->returnValue() ->setInteger((kvs_int_t)(pConnection->statistics() ->connectionStartTime()));)