KVIrc: src/modules/snd/libkvisnd.cpp File Reference
src/modules/snd/libkvisnd.cpp File Reference
#include "libkvisnd.h"
#include "KviModule.h"
#include "kvi_debug.h"
#include "KviFileUtils.h"
#include "KviMemory.h"
#include "KviWindow.h"
#include "kvi_out.h"
#include "KviLocale.h"
#include "KviQString.h"
#include <QSound>
#include <QFile>
#include <unistd.h>
#include <errno.h>
#include "libkvisnd.moc"
Functions
static bool snd_kvs_cmd_autodetect (KviKvsModuleCommandCall *c)
static bool snd_kvs_cmd_mute (KviKvsModuleCommandCall *c)
static bool snd_kvs_cmd_play (KviKvsModuleCommandCall *c)
COMPILE_ON_WINDOWS.
static bool snd_kvs_cmd_unmute (KviKvsModuleCommandCall *c)
static bool snd_kvs_fnc_ismuted (KviKvsModuleFunctionCall *c)
static bool snd_module_can_unload (KviModule *)
static bool snd_module_cleanup (KviModule *)
static bool snd_module_ctrl (KviModule *, const char *operation, void *param)
static bool snd_module_init (KviModule *m)
Variables
static KviSoundPlayer * g_pSoundPlayer = 0
COMPILE_PHONON_SUPPORT.
Function Documentation
static bool snd_kvs_cmd_autodetect (KviKvsModuleCommandCall * c) [static]
References __tr2qs, KviSoundPlayer::detectSoundSystem(), KviQString::equalCI(), KVI_OPTION_STRING, KVI_OUT_SYSTEMERROR, KVI_OUT_SYSTEMMESSAGE, KviOption_stringSoundSystem, KviWindow::output(), KviWindow::outputNoFmt(), and KviKvsRunTimeCall::window().
Referenced by snd_module_init().
static bool snd_kvs_cmd_mute (KviKvsModuleCommandCall * c) [static]
References KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviSoundPlayer::setMuted().
Referenced by snd_module_init().
static bool snd_kvs_cmd_play (KviKvsModuleCommandCall * c) [static]
COMPILE_ON_WINDOWS.
References __tr2qs, KviFileUtils::fileExists(), KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviSoundPlayer::play(), and KviKvsRunTimeCall::warning().
Referenced by snd_module_init().
static bool snd_kvs_cmd_unmute (KviKvsModuleCommandCall * c) [static]
References KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviSoundPlayer::setMuted().
Referenced by snd_module_init().
static bool snd_kvs_fnc_ismuted (KviKvsModuleFunctionCall * c) [static]
References KviSoundPlayer::isMuted(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by snd_module_init().
static bool snd_module_can_unload (KviModule *) [static]
References KviSoundPlayer::havePlayingSounds().
static bool snd_module_cleanup (KviModule *) [static]
References g_pSoundPlayer.
static bool snd_module_ctrl (KviModule * , const char * operation, void * param) [static]
References KviSoundPlayer::detectSoundSystem(), KviSoundPlayer::getAvailableSoundSystems(), kvi_strEqualCI(), l, and KviSoundPlayer::play().
static bool snd_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, snd_kvs_cmd_autodetect(), snd_kvs_cmd_mute(), snd_kvs_cmd_play(), snd_kvs_cmd_unmute(), and snd_kvs_fnc_ismuted().
Variable Documentation
KviSoundPlayer* g_pSoundPlayer = 0 [static]
COMPILE_PHONON_SUPPORT.
COMPILE_ON_WINDOWS
Referenced by snd_module_cleanup().