KVIrc: src/modules/spaste/libkvispaste.cpp File Reference
libkvispaste.cpp File Reference
#include "libkvispaste.h"
#include "SlowPasteController.h"
#include "KviModule.h"
#include "KviFileUtils.h"
#include "KviQString.h"
#include "KviApplication.h"
#include "KviLocale.h"
#include "KviConsoleWindow.h"
#include "KviOptions.h"
#include "kvi_out.h"
#include <QFile>
#include <QClipboard>
#include <unistd.h>
Functions
static SlowPasteController * spaste_find_controller (KviWindow *w)
static bool spaste_kvs_cmd_clipboard (KviKvsModuleCommandCall *c)
static bool spaste_kvs_cmd_file (KviKvsModuleCommandCall *c)
static bool spaste_kvs_cmd_list (KviKvsModuleCommandCall *c)
static bool spaste_kvs_cmd_setdelay (KviKvsModuleCommandCall *c)
static bool spaste_kvs_cmd_stop (KviKvsModuleCommandCall *c)
static KviWindow * spaste_kvs_find_window (QString &win, KviKvsModuleCommandCall *c)
static bool spaste_module_can_unload (KviModule *)
static bool spaste_module_cleanup (KviModule *)
static bool spaste_module_init (KviModule *m)
Variables
int ctrlId = 0
KviPointerList
< SlowPasteController > * g_pControllerList = 0
Function Documentation
static SlowPasteController* spaste_find_controller (KviWindow * w) static
References KviPointerList< T >::first(), KviPointerList< T >::next(), and w.
Referenced by spaste_kvs_cmd_clipboard(), and spaste_kvs_cmd_file().
static bool spaste_kvs_cmd_clipboard (KviKvsModuleCommandCall * c) static
References ctrlId, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, SlowPasteController::pasteClipboardInit(), spaste_find_controller(), and spaste_kvs_find_window().
Referenced by spaste_module_init().
static bool spaste_kvs_cmd_file (KviKvsModuleCommandCall * c) static
References __tr2qs, ctrlId, KviFileUtils::fileExists(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, SlowPasteController::pasteFileInit(), spaste_find_controller(), spaste_kvs_find_window(), and KviKvsRunTimeCall::warning().
Referenced by spaste_module_init().
static bool spaste_kvs_cmd_list (KviKvsModuleCommandCall * c) static
References __tr2qs, KviPointerListIterator< T >::current(), SlowPasteController::getId(), KviWindow::id(), KVI_OUT_NONE, KviWindow::output(), SlowPasteController::window(), and KviKvsRunTimeCall::window().
Referenced by spaste_module_init().
static bool spaste_kvs_cmd_setdelay (KviKvsModuleCommandCall * c) static
References KVI_OPTION_UINT, KviOption_uintPasteDelay, KVS_PT_INTEGER, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, and KVSM_PARAMETERS_END.
Referenced by spaste_module_init().
static bool spaste_kvs_cmd_stop (KviKvsModuleCommandCall * c) static
References __tr2qs, KviWindow::Channel, KviPointerListIterator< T >::current(), KviWindow::DccChat, KviWindow::DeadChannel, KviWindow::DeadQuery, KviQString::equalCS(), KviPointerList< T >::first(), SlowPasteController::getId(), KviKvsModuleCommandCall::hasSwitch(), KviWindow::id(), KVS_PF_OPTIONAL, KVS_PT_UNSIGNEDINTEGER, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviWindow::Query, KviWindow::type(), KviKvsRunTimeCall::warning(), SlowPasteController::window(), and KviKvsRunTimeCall::window().
Referenced by spaste_module_init().
static KviWindow* spaste_kvs_find_window (QString & win, KviKvsModuleCommandCall * c) static
References __tr, __tr2qs, KviWindow::Channel, KviWindow::DccChat, KviApplication::findWindow(), g_pApp, KviWindow::Query, KviWindow::type(), w, KviKvsRunTimeCall::warning(), and KviKvsRunTimeCall::window().
Referenced by spaste_kvs_cmd_clipboard(), and spaste_kvs_cmd_file().
static bool spaste_module_can_unload (KviModule *) static
References KviPointerList< T >::isEmpty().
static bool spaste_module_cleanup (KviModule *) static
References KviPointerList< T >::first(), and g_pControllerList.
static bool spaste_module_init (KviModule * m) static
References KVSM_REGISTER_SIMPLE_COMMAND, KviPointerList< T >::setAutoDelete(), spaste_kvs_cmd_clipboard(), spaste_kvs_cmd_file(), spaste_kvs_cmd_list(), spaste_kvs_cmd_setdelay(), and spaste_kvs_cmd_stop().
Variable Documentation
int ctrlId = 0
Referenced by spaste_kvs_cmd_clipboard(), and spaste_kvs_cmd_file().
KviPointerList<SlowPasteController>* g_pControllerList = 0
Referenced by spaste_module_cleanup().