KVIrc: src/modules/ident/libkviident.cpp File Reference
src/modules/ident/libkviident.cpp File Reference
#include "libkviident.h"
#include "KviModule.h"
#include "kvi_socket.h"
#include "KviApplication.h"
#include "kvi_out.h"
#include "KviNetUtils.h"
#include "KviLocale.h"
#include "KviWindow.h"
#include "KviOptions.h"
#include "kvi_defaults.h"
#include "libkviident.moc"
Defines
#define KVI_IDENT_THREAD_EVENT_EXITING KVI_THREAD_USER_EVENT_BASE + 111
#define KVI_IDENT_THREAD_EVENT_EXITING_ON_REQUEST KVI_THREAD_USER_EVENT_BASE + 112
Functions
static bool ident_kvs_cmd_start (KviKvsModuleCommandCall *)
static bool ident_kvs_cmd_stop (KviKvsModuleCommandCall *)
static bool ident_module_can_unload (KviModule *)
static bool ident_module_cleanup (KviModule *)
static bool ident_module_init (KviModule *m)
void startIdentService ()
void stopIdentService ()
Variables
KVIRC_API int g_iIdentDaemonRunningUsers
xml parser
static KviIdentDaemon * g_pIdentDaemon = 0
static KviIdentSentinel * g_pIdentSentinel = 0
Define Documentation
#define KVI_IDENT_THREAD_EVENT_EXITING KVI_THREAD_USER_EVENT_BASE + 111
Referenced by KviIdentSentinel::event(), and KviIdentDaemon::run().
#define KVI_IDENT_THREAD_EVENT_EXITING_ON_REQUEST KVI_THREAD_USER_EVENT_BASE + 112
Referenced by KviIdentSentinel::event(), and KviIdentDaemon::run().
Function Documentation
static bool ident_kvs_cmd_start (KviKvsModuleCommandCall *) [static]
References g_iIdentDaemonRunningUsers, and startIdentService().
Referenced by ident_module_init().
static bool ident_kvs_cmd_stop (KviKvsModuleCommandCall *) [static]
References g_iIdentDaemonRunningUsers, and stopIdentService().
Referenced by ident_module_init().
static bool ident_module_can_unload (KviModule *) [static]
References g_pIdentDaemon.
static bool ident_module_cleanup (KviModule *) [static]
References g_pIdentSentinel, and stopIdentService().
static bool ident_module_init (KviModule * m) [static]
References ident_kvs_cmd_start(), ident_kvs_cmd_stop(), and KVSM_REGISTER_SIMPLE_COMMAND.
void startIdentService ()
References KviThread::isRunning(), KviThread::isStartingUp(), and KviThread::start().
Referenced by ident_kvs_cmd_start().
void stopIdentService ()
References g_pIdentDaemon.
Referenced by KviIdentSentinel::event(), ident_kvs_cmd_stop(), and ident_module_cleanup().
Variable Documentation
KVIRC_API int g_iIdentDaemonRunningUsers
xml parser
Referenced by ident_kvs_cmd_start(), ident_kvs_cmd_stop(), KviApplication::optionResetUpdate(), and KviIdentDaemon::~KviIdentDaemon().
KviIdentDaemon* g_pIdentDaemon = 0 [static]
Referenced by ident_module_can_unload(), and stopIdentService().
KviIdentSentinel* g_pIdentSentinel = 0 [static]
Referenced by ident_module_cleanup().