KVIrc: src/modules/spellchecker/libkvispellchecker.cpp File Reference
libkvispellchecker.cpp File Reference
#include "KviModule.h"
#include "KviOptions.h"
#include <enchant.h>
Functions
static void spellchecker_enumerate_dicts (const char *szLang, const char *, const char *szDesc, const char *, void *pData)
static bool spellchecker_kvs_available_dictionaries (KviKvsModuleFunctionCall *c)
static bool spellchecker_kvs_check (KviKvsModuleFunctionCall *c)
static bool spellchecker_kvs_reload_dictionaries (KviKvsModuleCommandCall *c)
static bool spellchecker_module_cleanup (KviModule *)
static bool spellchecker_module_init (KviModule *m)
static void spellchecker_reload_dicts ()
Variables
static EnchantBroker * g_pEnchantBroker = NULL
static KviPointerList
< EnchantDict > * g_pEnchantDicts = NULL
Function Documentation
static void spellchecker_enumerate_dicts (const char * szLang, const char * , const char * szDesc, const char * , void * pData) static
References KviKvsHash::set().
Referenced by spellchecker_kvs_available_dictionaries().
static bool spellchecker_kvs_available_dictionaries (KviKvsModuleFunctionCall * c) static
References g_pEnchantBroker, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setHash(), and spellchecker_enumerate_dicts().
Referenced by spellchecker_module_init().
static bool spellchecker_kvs_check (KviKvsModuleFunctionCall * c) static
References KviPointerList< T >::isEmpty(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviPointerListIterator< T >::moveFirst(), KviPointerListIterator< T >::moveNext(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by spellchecker_module_init().
static bool spellchecker_kvs_reload_dictionaries (KviKvsModuleCommandCall * c) static
References KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and spellchecker_reload_dicts().
Referenced by spellchecker_module_init().
static bool spellchecker_module_cleanup (KviModule *) static
References g_pEnchantBroker, g_pEnchantDicts, KviPointerList< T >::isEmpty(), NULL, and KviPointerList< T >::takeFirst().
static bool spellchecker_module_init (KviModule * m) static
References g_pEnchantBroker, KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, spellchecker_kvs_available_dictionaries(), spellchecker_kvs_check(), spellchecker_kvs_reload_dictionaries(), and spellchecker_reload_dicts().
static void spellchecker_reload_dicts () static
References KviPointerList< T >::append(), g_pEnchantBroker, KviPointerList< T >::isEmpty(), KVI_OPTION_STRINGLIST, KviOption_stringlistSpellCheckerDictionaries, and KviPointerList< T >::takeFirst().
Referenced by spellchecker_kvs_reload_dictionaries(), and spellchecker_module_init().
Variable Documentation
EnchantBroker* g_pEnchantBroker = NULL static
Referenced by spellchecker_kvs_available_dictionaries(), spellchecker_module_cleanup(), spellchecker_module_init(), and spellchecker_reload_dicts().
KviPointerList<EnchantDict>* g_pEnchantDicts = NULL static
Referenced by spellchecker_module_cleanup().