KVIrc: src/modules/mask/libkvimask.cpp File Reference
src/modules/mask/libkvimask.cpp File Reference
#include "KviModule.h"
#include "KviLocale.h"
#include "KviCString.h"
#include "KviIrcMask.h"
Functions
static bool mask_kvs_fnc_hasnumerichost (KviKvsModuleFunctionCall *c)
static bool mask_kvs_fnc_host (KviKvsModuleFunctionCall *c)
static bool mask_kvs_fnc_match (KviKvsModuleFunctionCall *c)
static bool mask_kvs_fnc_nick (KviKvsModuleFunctionCall *c)
static bool mask_kvs_fnc_user (KviKvsModuleFunctionCall *c)
static bool mask_module_cleanup (KviModule *)
static bool mask_module_init (KviModule *m)
Function Documentation
static bool mask_kvs_fnc_hasnumerichost (KviKvsModuleFunctionCall * c) [static]
References KviIrcMask::hasNumericHost(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by mask_module_init().
static bool mask_kvs_fnc_host (KviKvsModuleFunctionCall * c) [static]
References KviIrcMask::host(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by mask_module_init().
static bool mask_kvs_fnc_match (KviKvsModuleFunctionCall * c) [static]
References KviIrcMask::host(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcMask::matchesFixed(), KviIrcMask::nick(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and KviIrcMask::user().
Referenced by mask_module_init().
static bool mask_kvs_fnc_nick (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcMask::nick(), KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setString().
Referenced by mask_module_init().
static bool mask_kvs_fnc_user (KviKvsModuleFunctionCall * c) [static]
References KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and KviIrcMask::user().
Referenced by mask_module_init().
static bool mask_module_cleanup (KviModule *) [static]
static bool mask_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, mask_kvs_fnc_hasnumerichost(), mask_kvs_fnc_host(), mask_kvs_fnc_match(), mask_kvs_fnc_nick(), and mask_kvs_fnc_user().