KVIrc: src/modules/reguser/libkvireguser.cpp File Reference
src/modules/reguser/libkvireguser.cpp File Reference
#include "RegisteredUserEntryDialog.h"
#include "RegistrationWizard.h"
#include "KviIrcConnection.h"
#include "dialog.h"
#include "KviModule.h"
#include "KviRegisteredUserDataBase.h"
#include "KviIrcUserDataBase.h"
#include "kvi_out.h"
#include "KviMircCntrl.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviPointerList.h"
#include <QSplitter>
Functions
static bool reguser_kvs_cmd_add (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_addmask (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_delmask (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_edit (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_remove (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_setIgnoreEnabled (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_setIgnoreFlags (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_setproperty (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_showlist (KviKvsModuleCommandCall *c)
static bool reguser_kvs_cmd_wizard (KviKvsModuleCommandCall *c)
static bool reguser_kvs_fnc_exactMatch (KviKvsModuleFunctionCall *c)
static bool reguser_kvs_fnc_getIgnoreFlags (KviKvsModuleFunctionCall *c)
static bool reguser_kvs_fnc_isIgnoreEnabled (KviKvsModuleFunctionCall *c)
static bool reguser_kvs_fnc_list (KviKvsModuleFunctionCall *c)
static bool reguser_kvs_fnc_mask (KviKvsModuleFunctionCall *c)
*
static bool reguser_kvs_fnc_match (KviKvsModuleFunctionCall *c)
static bool reguser_kvs_fnc_matchProperty (KviKvsModuleFunctionCall *c)
static bool reguser_kvs_fnc_property (KviKvsModuleFunctionCall *c)
static bool reguser_module_can_unload (KviModule *)
static bool reguser_module_cleanup (KviModule *)
static bool reguser_module_init (KviModule *m)
Variables
KVIRC_API
KviRegisteredUserDataBase * g_pRegisteredUserDataBase
RegisteredUsersDialog * g_pRegisteredUsersDialog = 0
KviPointerList
< RegistrationWizard > * g_pRegistrationWizardList = 0
Function Documentation
static bool reguser_kvs_cmd_add (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredUserDataBase::addMask(), KviRegisteredUserDataBase::addUser(), KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviKvsSwitchList::getAsStringIfExisting(), KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviRegisteredUser::name(), KviRegisteredUserDataBase::removeUser(), KviRegisteredUser::setGroup(), KviKvsModuleCommandCall::switches(), u, and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_addmask (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredUserDataBase::addMask(), KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUser::name(), KviRegisteredUserDataBase::removeMask(), u, and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_delmask (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), g_pRegisteredUserDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUserDataBase::removeMask(), and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_edit (KviKvsModuleCommandCall * c) [static]
References KviWindow::frame(), KviKvsModuleCommandCall::hasSwitch(), KviMainWindow::splitter(), and KviKvsRunTimeCall::window().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_remove (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), g_pApp, g_pRegisteredUserDataBase, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUserDataBase::removeUser(), KviApplication::restartNotifyLists(), and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_setIgnoreEnabled (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviKvsModuleCommandCall::hasSwitch(), KVS_PT_BOOL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUser::setIgnoreEnabled(), u, and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_setIgnoreFlags (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredUser::Channel, KviRegisteredUser::Ctcp, KviRegisteredUser::Dcc, KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviKvsModuleCommandCall::hasSwitch(), KviRegisteredUser::Invite, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUser::Notice, KviRegisteredUser::Query, KviRegisteredUser::setIgnoreFlags(), u, and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_setproperty (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviRegisteredUserDataBase::findUserByName(), g_pApp, g_pRegisteredUserDataBase, KviKvsModuleCommandCall::hasSwitch(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviApplication::resetAvatarForMatchingUsers(), KviApplication::restartNotifyLists(), KviRegisteredUser::setProperty(), u, and KviKvsRunTimeCall::warning().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_showlist (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), KviMircCntrl::Bold, KviPointerHashTable< Key, T >::count(), KviPointerList< T >::count(), KviPointerHashTableIterator< Key, T >::current(), KviPointerHashTableIterator< Key, T >::currentKey(), d, KviPointerList< T >::first(), g_pRegisteredUserDataBase, KVI_OUT_SYSTEMMESSAGE, KVI_OUT_SYSTEMWARNING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviPointerList< T >::next(), KviWindow::output(), KviWindow::outputNoFmt(), u, KviRegisteredUserDataBase::userDict(), and KviKvsRunTimeCall::window().
Referenced by reguser_module_init().
static bool reguser_kvs_cmd_wizard (KviKvsModuleCommandCall * c) [static]
References KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and w.
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_exactMatch (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredUserDataBase::findUserWithMask(), g_pRegisteredUserDataBase, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUser::name(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and u.
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_getIgnoreFlags (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredUser::Channel, KviRegisteredUser::Ctcp, KviRegisteredUser::Dcc, KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviRegisteredUser::ignoreFlags(), KviRegisteredUser::Invite, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUser::Notice, KviRegisteredUser::Query, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and u.
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_isIgnoreEnabled (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviRegisteredUser::ignoreEnagled(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setBoolean(), and u.
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_list (KviKvsModuleFunctionCall * c) [static]
References KviPointerList< T >::count(), KviPointerHashTableIterator< Key, T >::current(), d, g_pRegisteredUserDataBase, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), u, and KviRegisteredUserDataBase::userDict().
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_mask (KviKvsModuleFunctionCall * c) [static]
*
References KviPointerList< T >::at(), KviRegisteredUserDataBase::findUserByName(), KviPointerList< T >::first(), g_pRegisteredUserDataBase, KviCString::hasData(), KviIrcMask::host(), KviCString::isUnsignedNum(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, m, KviRegisteredUser::maskList(), n, KviPointerList< T >::next(), KviIrcMask::nick(), pArray, KviKvsModuleFunctionCall::returnValue(), KviKvsArray::set(), KviKvsVariant::setArray(), KviKvsVariant::setString(), KviCString::toInt(), u, and KviIrcMask::user().
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_match (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredUserDataBase::findMatchingUser(), g_pRegisteredUserDataBase, KviIrcMask::host(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviRegisteredUser::name(), KviIrcMask::nick(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), u, and KviIrcMask::user().
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_matchProperty (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredUserDataBase::findMatchingUser(), g_pRegisteredUserDataBase, KviRegisteredUser::getProperty(), KviIrcMask::host(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviIrcMask::nick(), KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), u, and KviIrcMask::user().
Referenced by reguser_module_init().
static bool reguser_kvs_fnc_property (KviKvsModuleFunctionCall * c) [static]
References KviRegisteredUserDataBase::findUserByName(), g_pRegisteredUserDataBase, KviRegisteredUser::getProperty(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), KviKvsVariant::setString(), and u.
Referenced by reguser_module_init().
static bool reguser_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool reguser_module_cleanup (KviModule *) [static]
References KviPointerList< T >::first(), g_pRegisteredUsersDialog, g_pRegistrationWizardList, and w.
static bool reguser_module_init (KviModule * m) [static]
References g_pLocalRegisteredUserDataBase, KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, reguser_kvs_cmd_add(), reguser_kvs_cmd_addmask(), reguser_kvs_cmd_delmask(), reguser_kvs_cmd_edit(), reguser_kvs_cmd_remove(), reguser_kvs_cmd_setIgnoreEnabled(), reguser_kvs_cmd_setIgnoreFlags(), reguser_kvs_cmd_setproperty(), reguser_kvs_cmd_showlist(), reguser_kvs_cmd_wizard(), reguser_kvs_fnc_exactMatch(), reguser_kvs_fnc_getIgnoreFlags(), reguser_kvs_fnc_isIgnoreEnabled(), reguser_kvs_fnc_list(), reguser_kvs_fnc_mask(), reguser_kvs_fnc_match(), reguser_kvs_fnc_matchProperty(), reguser_kvs_fnc_property(), and KviPointerList< T >::setAutoDelete().
Variable Documentation
KVIRC_API KviRegisteredUserDataBase* g_pRegisteredUserDataBase
RegisteredUsersDialog* g_pRegisteredUsersDialog = 0
Referenced by reguser_module_cleanup().
KviPointerList<RegistrationWizard>* g_pRegistrationWizardList = 0
Referenced by reguser_module_cleanup().