KVIrc: src/modules/rot13/libkvirot13.cpp File Reference
src/modules/rot13/libkvirot13.cpp File Reference
#include "libkvirot13.h"
#include "KviModule.h"
#include "kvi_debug.h"
#include "KviLocale.h"
Functions
static bool rot13_module_can_unload (KviModule *)
static bool rot13_module_cleanup (KviModule *m)
static bool rot13_module_init (KviModule *m)
Function Documentation
static bool rot13_module_can_unload (KviModule *) [static]
References KviPointerList< T >::isEmpty().
static bool rot13_module_cleanup (KviModule * m) [static]
References KviPointerList< T >::first(), and g_pEngineList.
static bool rot13_module_init (KviModule * m) [static]
References __tr2qs, KviCryptEngine::CanEncrypt, d, and KviPointerList< T >::setAutoDelete().