KVIrc: src/modules/options/libkvioptions.cpp File Reference
src/modules/options/libkvioptions.cpp File Reference
#include "OptionsWidgetContainer.h"
#include "OptionsInstanceManager.h"
#include "OptionsDialog.h"
#include "KviModule.h"
#include "KviOptions.h"
#include "KviApplication.h"
#include "KviMainWindow.h"
#include "KviWindow.h"
#include "KviLocale.h"
#include "KviControlCodes.h"
#include "kvi_out.h"
#include "KviSplashScreen.h"
#include "KviPointerHashTable.h"
#include <QSplitter>
Functions
static bool options_kvs_cmd_dialog (KviKvsModuleCommandCall *c)
static bool options_kvs_cmd_edit (KviKvsModuleCommandCall *c)
static bool options_kvs_cmd_pages (KviKvsModuleCommandCall *c)
static bool options_kvs_cmd_save (KviKvsModuleCommandCall *)
static bool options_kvs_fnc_isdialog (KviKvsModuleFunctionCall *c)
static void options_kvs_module_print_pages (KviKvsModuleCommandCall *c, OptionsWidgetInstanceEntry *e, const char *prefix)
static bool options_module_can_unload (KviModule *)
static bool options_module_cleanup (KviModule *m)
static bool options_module_init (KviModule *m)
Variables
int g_iOptionWidgetInstances
KviPointerHashTable< QString,
OptionsDialog > * g_pOptionsDialogDict = 0
OptionsInstanceManager * g_pOptionsInstanceManager = 0
Function Documentation
static bool options_kvs_cmd_dialog (KviKvsModuleCommandCall * c) [static]
References d, KviPointerHashTable< Key, T >::find(), g_pMainWindow, KviKvsModuleCommandCall::hasSwitch(), KviPointerHashTable< Key, T >::insert(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, and KviMainWindow::splitter().
Referenced by options_module_init().
static bool options_kvs_cmd_edit (KviKvsModuleCommandCall * c) [static]
References __tr2qs_ctx(), connect(), e, OptionsInstanceManager::findInstanceEntry(), g_pSplashScreen, OptionsInstanceManager::getInstance(), KviKvsModuleCommandCall::hasSwitch(), KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, _OptionsWidgetInstanceEntry::pWidget, OptionsWidgetContainer::setup(), and KviKvsRunTimeCall::warning().
Referenced by options_module_init().
static bool options_kvs_cmd_pages (KviKvsModuleCommandCall * c) [static]
References e, KviPointerList< T >::first(), OptionsInstanceManager::instanceEntryTree(), l, KviPointerList< T >::next(), and options_kvs_module_print_pages().
Referenced by options_module_init().
static bool options_kvs_cmd_save (KviKvsModuleCommandCall *) [static]
References g_pApp, and KviApplication::saveConfiguration().
Referenced by options_module_init().
static bool options_kvs_fnc_isdialog (KviKvsModuleFunctionCall * c) [static]
References KviPointerHashTable< Key, T >::find(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSM_PARAMETER, KVSM_PARAMETERS_BEGIN, KVSM_PARAMETERS_END, KviKvsModuleFunctionCall::returnValue(), and KviKvsVariant::setBoolean().
Referenced by options_module_init().
static void options_kvs_module_print_pages (KviKvsModuleCommandCall * c, OptionsWidgetInstanceEntry * e, const char * prefix) [static]
References KviCString::append(), KviControlCodes::Bold, KviPointerList< T >::first(), KVI_OUT_SYSTEMMESSAGE, KviPointerList< T >::next(), KviWindow::output(), _OptionsWidgetInstanceEntry::pChildList, KviCString::ptr(), _OptionsWidgetInstanceEntry::szClassName, _OptionsWidgetInstanceEntry::szName, and KviKvsRunTimeCall::window().
Referenced by options_kvs_cmd_pages().
static bool options_module_can_unload (KviModule *) [static]
References g_iOptionWidgetInstances, and KviPointerHashTable< Key, T >::isEmpty().
static bool options_module_cleanup (KviModule * m) [static]
References KviPointerList< T >::append(), OptionsInstanceManager::cleanup(), KviPointerHashTableIterator< Key, T >::current(), d, KviPointerList< T >::first(), g_pOptionsDialogDict, g_pOptionsInstanceManager, l, KviPointerList< T >::next(), and KviPointerList< T >::setAutoDelete().
static bool options_module_init (KviModule * m) [static]
References KVSM_REGISTER_FUNCTION, KVSM_REGISTER_SIMPLE_COMMAND, options_kvs_cmd_dialog(), options_kvs_cmd_edit(), options_kvs_cmd_pages(), options_kvs_cmd_save(), options_kvs_fnc_isdialog(), and KviPointerHashTable< Key, T >::setAutoDelete().
Variable Documentation
int g_iOptionWidgetInstances
Referenced by OptionsInstanceManager::getInstance(), options_module_can_unload(), and OptionsInstanceManager::widgetDestroyed().
KviPointerHashTable<QString,OptionsDialog>* g_pOptionsDialogDict = 0
Referenced by options_module_cleanup().
OptionsInstanceManager* g_pOptionsInstanceManager = 0
Referenced by options_module_cleanup().