KVIrc: src/modules/mediaplayer/MpMp3.h File Reference
src/modules/mediaplayer/MpMp3.h File Reference
#include "kvi_settings.h"
#include <stdio.h>
#include <stdlib.h>
#include <QString>
#include <unistd.h>
#include <sys/stat.h>
#include <ctype.h>
#include <string.h>
Classes
struct id3tag
struct mp3header
struct mp3info
Defines
#define FRAME_HEADER_SIZE 4
#define INT_FIELD_LEN 4
#define MIN_CONSEC_GOOD_FRAMES 4
#define MIN_FRAME_SIZE 21
#define NUM_SAMPLES 4
#define TEXT_FIELD_LEN 30
Enumerations
enum VBR_REPORT { VBR_VARIABLE, VBR_AVERAGE, VBR_MEDIAN }
Functions
int frame_length (mp3header *header)
int get_first_header (mp3info *mp3, long startpos)
int get_header (FILE *file, mp3header *header)
int get_id3 (mp3info *mp3)
int get_mp3_info (mp3info *mp3)
const char * get_typegenre (int idx)
int header_bitrate (mp3header *h)
int header_channels (mp3header *h)
int header_crc (mp3header *h)
const char * header_emphasis (mp3header *h)
int header_frequency (mp3header *h)
int header_layer (mp3header *h)
const char * header_mode (mp3header *h)
double header_version (mp3header *h)
char * pad (char *string, int length)
void resetmp3infoStruct (mp3info *i)
int sameConstant (mp3header *h1, mp3header *h2)
bool scan_mp3_file (QString &szFileName, mp3info *i)
char * unpad (char *string)
Define Documentation
#define FRAME_HEADER_SIZE 4
Referenced by get_first_header(), and get_header().
#define INT_FIELD_LEN 4
#define MIN_CONSEC_GOOD_FRAMES 4
Referenced by get_first_header().
#define MIN_FRAME_SIZE 21
Referenced by get_header().
#define NUM_SAMPLES 4
Referenced by get_mp3_info().
#define TEXT_FIELD_LEN 30
Enumeration Type Documentation
enum VBR_REPORT
Enumerator:
VBR_VARIABLE
VBR_AVERAGE
VBR_MEDIAN
Function Documentation
int frame_length (mp3header * header)
References frame_size_index, header_bitrate(), header_frequency(), mp3header::layer, mp3header::padding, mp3header::sync, and mp3header::version.
Referenced by get_header(), and get_mp3_info().
int get_first_header (mp3info * mp3, long startpos)
References c, mp3info::datasize, mp3info::file, FRAME_HEADER_SIZE, get_header(), h, mp3info::header, mp3info::header_isvalid, k, l, MIN_CONSEC_GOOD_FRAMES, and sameConstant().
Referenced by get_mp3_info().
int get_header (FILE * file, mp3header * header)
References mp3header::bitrate, mp3header::copyright, mp3header::crc, mp3header::emphasis, mp3header::extension, FRAME_HEADER_SIZE, frame_length(), mp3header::freq, mp3header::layer, MIN_FRAME_SIZE, mp3header::mode, mp3header::mode_extension, mp3header::original, mp3header::padding, mp3header::sync, and mp3header::version.
Referenced by get_first_header().
int get_id3 (mp3info * mp3)
References id3tag::album, id3tag::artist, id3tag::comment, mp3info::datasize, mp3info::file, id3tag::genre, mp3info::id3, mp3info::id3_isvalid, id3tag::title, id3tag::track, unpad(), and id3tag::year.
Referenced by get_mp3_info().
int get_mp3_info (mp3info * mp3)
References mp3header::bitrate, bitrate, mp3info::datasize, mp3info::file, mp3info::filename, frame_length(), mp3info::frames, get_first_header(), get_id3(), mp3info::header, header_bitrate(), NUM_SAMPLES, mp3info::seconds, mp3info::vbr, and mp3info::vbr_average.
Referenced by scan_mp3_file().
const char* get_typegenre (int idx)
References MAXGENRE, and typegenre.
Referenced by MpInterface::genre().
int header_bitrate (mp3header * h)
References bitrate, mp3header::bitrate, mp3header::layer, and mp3header::version.
Referenced by MpInterface::bitRate(), frame_length(), and get_mp3_info().
int header_channels (mp3header * h)
References mp3header::mode.
Referenced by MpInterface::channels().
int header_crc (mp3header * h)
References mp3header::crc.
const char* header_emphasis (mp3header * h)
References mp3header::emphasis, and emphasis_text.
int header_frequency (mp3header * h)
References mp3header::freq, frequencies, and mp3header::version.
Referenced by frame_length(), and MpInterface::sampleRate().
int header_layer (mp3header * h)
References mp3header::layer, and layer_tab.
const char* header_mode (mp3header * h)
References mp3header::mode, and mode_text.
double header_version (mp3header * h)
char* pad (char * string, int length)
References l.
void resetmp3infoStruct (mp3info * i)
References mp3info::badframes, mp3info::datasize, mp3info::file, mp3info::frames, mp3info::header, mp3info::header_isvalid, mp3info::id3, mp3info::id3_isvalid, mp3info::seconds, mp3info::vbr, and mp3info::vbr_average.
Referenced by scan_mp3_file().
int sameConstant (mp3header * h1, mp3header * h2)
Referenced by get_first_header().
bool scan_mp3_file (QString & szFileName, mp3info * i)
References mp3info::file, mp3info::filename, get_mp3_info(), mp3info::id3_isvalid, and resetmp3infoStruct().
char* unpad (char * string)
Referenced by get_id3().