KVIrc: src/modules/mediaplayer/MpXmmsInterface.cpp File Reference
MpXmmsInterface.cpp File Reference
#include "MpXmmsInterface.h"
#include "KviLocale.h"
Macros
#define XMMS_SIMPLE_CALL(__symname)
Functions
audacious __tr2qs_ctx ("An interface to the popular UNIX audacious media player.\n""Download it from http://audacious-media-player.org\n","mediaplayer")) static const char *xmms_lib_names[]
MP_IMPLEMENT_DESCRIPTOR (KviXmmsInterface,"xmms", __tr2qs_ctx("An interface to the popular UNIX xmms media player.\n""Download it from http://legacy.xmms2.org\n","mediaplayer")) MP_IMPLEMENT_DESCRIPTOR(KviAudaciousClassicInterface
Variables
static const char * audacious_lib_names []
audacious classic
Macro Definition Documentation
#define XMMS_SIMPLE_CALL (__symname)
Value:
void (*sym)(int) = (void (*)(int))lookupSymbol(__symname); \
        if(!sym)return false; \
        sym(0); \
        return true;
Referenced by KviXmmsInterface::next(), KviXmmsInterface::pause(), KviXmmsInterface::play(), KviXmmsInterface::prev(), KviXmmsInterface::quit(), and KviXmmsInterface::stop().
Function Documentation
audacious __tr2qs_ctx ("An interface to the popular UNIX audacious media player.\n""Download it from http://audacious-media-player.org\n" , "mediaplayer") const
Referenced by DccFileTransfer::abort(), AboutDialog::AboutDialog(), ActionEditor::ActionEditor(), ActionEditorTreeView::ActionEditorTreeView(), ActionEditorWindow::ActionEditorWindow(), DccBroker::activeVideoManage(), DccBroker::activeVoiceManage(), OptionsWidget_textIcons::addClicked(), UPnP::RootService::addDeviceServices(), RegisteredUsersDialog::addGroupClicked(), EventEditor::addHandlerForCurrentEvent(), RawEditorWidget::addHandlerForCurrentRaw(), addon_kvs_cmd_configure(), addon_kvs_cmd_help(), addon_kvs_cmd_install(), addon_kvs_cmd_installfiles(), addon_kvs_cmd_list(), addon_kvs_cmd_register(), addon_kvs_cmd_setconfigurecallback(), addon_kvs_cmd_sethelpcallback(), addon_kvs_cmd_uninstall(), AddonManagementDialog::AddonManagementDialog(), RawEditorWidget::addRaw(), CustomToolBarPropertiesDialog::advancedClicked(), AliasEditorTreeWidget::AliasEditorTreeWidget(), AliasEditorWidget::AliasEditorWidget(), AliasEditorWindow::AliasEditorWindow(), AliasEditorWidget::aliasRefresh(), KviKvsObjectClass::allocateInstance(), ThemeManagementDialog::applyCurrentTheme(), AliasEditorWidget::askForAliasName(), AliasEditorWidget::askForNamespaceName(), ClassEditorWidget::askForNamespaceName(), auto_detect_player(), auto_detect_torrent_client(), AvatarDownloadDialog::AvatarDownloadDialog(), AvatarSelectionDialog::AvatarSelectionDialog(), ClassEditorWidget::build(), KviKvsObject::callFunction(), AvatarDownloadDialog::cancelClicked(), PackAddonDialog::checkDirTree(), DccVoiceThread::checkSoundcard(), OptionsWidget_identityAvatar::chooseAvatar(), AvatarSelectionDialog::chooseFileClicked(), DccBroker::chooseSaveFileName(), ClassEditorTreeWidget::ClassEditorTreeWidget(), ClassEditorWidget::ClassEditorWidget(), ClassEditorWindow::ClassEditorWindow(), FileTransferWindow::clearAll(), AvatarDownloadDialog::closeEvent(), CodeTesterWidget::CodeTesterWidget(), OptionsWidget_textEncoding::commit(), DccChatWindow::connected(), DccVoiceWindow::connected(), DccVideoWindow::connected(), DccFileTransfer::connected(), HttpFileTransfer::connectionEstabilished(), DccChatWindow::connectionInProgress(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), HttpFileTransfer::contactingHost(), ScriptEditorWidget::contextMenuEvent(), ThemeManagementDialog::contextMenuRequested(), LogViewWindow::createLog(), EventEditor::currentItemChanged(), RawEditorWidget::currentItemChanged(), AliasEditorWidget::currentItemChanged(), OptionsWidget_servers::currentItemChanged(), ClassEditorWidget::currentItemChanged(), OptionsWidget_proxy::customContextMenuRequested(), RawEditorWidget::customContextMenuRequested(), AliasEditorWidget::customContextMenuRequested(), SinglePopupEditor::customContextMenuRequested(), PopupEditorWidget::customContextMenuRequested(), OptionsWidget_servers::customContextMenuRequested(), ClassEditorWidget::customContextMenuRequested(), CustomizeToolBarsDialog::CustomizeToolBarsDialog(), CustomToolBarPropertiesDialog::CustomToolBarPropertiesDialog(), dcc_fill_local_nick_user_host(), dcc_kvs_cmd_chat(), dcc_kvs_cmd_get(), dcc_kvs_cmd_recv(), dcc_kvs_cmd_rsend(), dcc_kvs_cmd_send(), dcc_kvs_cmd_setBandwidthLimit(), dcc_kvs_cmd_video(), dcc_kvs_cmd_voice(), dcc_kvs_find_dcc_descriptor(), dcc_kvs_fnc_getSSLCertInfo(), dcc_kvs_fnc_ircContext(), dcc_kvs_fnc_session(), dcc_kvs_get_listen_ip_address(), dcc_kvs_parse_default_parameters(), dcc_module_check_concurrent_transfers_limit(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_request_error(), DccAcceptDialog::DccAcceptDialog(), DccFileTransfer::DccFileTransfer(), DccFileTransferBandwidthDialog::DccFileTransferBandwidthDialog(), dccModuleCtcpDccParseRoutine(), dccModuleParseDccAccept(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccResume(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), dccModuleParseDccVoice(), DccRenameDialog::DccRenameDialog(), DccVideoWindow::DccVideoWindow(), DccVoiceWindow::DccVoiceWindow(), KviXmlHandler::decodeException(), default_module_kvs_cmd_unload(), LogViewWindow::deleteCurrent(), FileTransferWindow::deleteLocalFile(), ThemeManagementDialog::deleteTheme(), CustomizeToolBarsDialog::deleteToolBar(), HttpFileTransfer::displayPaint(), DccFileTransfer::displayPaint(), KviKvsDnsManager::dnsLookupTerminated(), DccFileTransfer::doResume(), RegisteredUsersDialog::editGroup(), OptionsWidget_identityProfile::editProfileOkPressed(), KviKvsObject::emitSignal(), KviKvsParser::errorBadChar(), KviKvsRunTimeContext::errorNoIrcContext(), KviKvsPopupMenuItem::evaluateCondition(), KviKvsPopupMenuItemWithTextAndIcon::evaluateIcon(), KviKvsTreeNodeArrayElement::evaluateIndex(), KviKvsTreeNodeExpressionUnaryOperator::evaluateOperand(), KviKvsTreeNodeExpressionBinaryOperator::evaluateOperands(), KviKvsTreeNodeExtendedScopeVariable::evaluateReadOnly(), KviKvsTreeNodeData::evaluateReadOnly(), KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeHashCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeData::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeHashReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayCount::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeArrayReferenceAssert::evaluateReadOnlyInObjectScope(), KviKvsTreeNodeExtendedScopeVariable::evaluateReadWrite(), KviKvsTreeNodeData::evaluateReadWrite(), KviKvsTreeNodeHashElement::evaluateReadWriteInObjectScope(), KviKvsTreeNodeData::evaluateReadWriteInObjectScope(), KviKvsTreeNodeArrayElement::evaluateReadWriteInObjectScope(), KviKvsPopupMenuItemWithTextAndIcon::evaluateText(), DccChatWindow::event(), DccVoiceWindow::event(), DccVideoWindow::event(), DccFileTransfer::event(), EventEditor::EventEditor(), EventEditorTreeWidget::EventEditorTreeWidget(), EventEditorWindow::EventEditorWindow(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviKvsTreeNodeRebindingSwitch::execute(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsTreeNodeOperationDecrement::execute(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviKvsTreeNodeOperationIncrement::execute(), KviKvsTreeNodeOperationSelfAnd::execute(), KviKvsTreeNodeOperationSelfDivision::execute(), KviKvsTreeNodeOperationSelfModulus::execute(), KviKvsTreeNodeOperationSelfMultiplication::execute(), KviKvsTreeNodeOperationSelfOr::execute(), KviKvsTreeNodeOperationSelfShl::execute(), KviKvsTreeNodeOperationSelfShr::execute(), KviKvsTreeNodeOperationSelfSubtraction::execute(), KviKvsTreeNodeSpecialCommandDefpopup::execute(), KviKvsTreeNodeOperationSelfSum::execute(), KviKvsTreeNodeOperationSelfXor::execute(), KviKvsTreeNodeOperationStringSubstitution::execute(), KviKvsPopupMenu::executeEpilogues(), KviKvsPopupMenu::executePrologues(), ActionEditor::exportActions(), AliasEditorWidget::exportAliases(), EventEditor::exportAllEvents(), RawEditorWidget::exportAllEvents(), ClassEditorWidget::exportClasses(), RegisteredUsersDialog::exportClicked(), EventEditor::exportCurrentHandler(), RawEditorWidget::exportCurrentHandler(), PopupEditorWidget::exportCurrentPopup(), PopupEditorWidget::exportPopups(), AliasEditorWidget::exportSelectionInSinglesFiles(), ClassEditorWidget::exportSelectionInSinglesFiles(), CustomizeToolBarsDialog::exportToolBar(), FileTransferWidget::FileTransferWidget(), KviKvsPopupMenuItemExtMenu::fill(), CodeTesterWindow::fillCaptionBuffers(), SharedFilesWindow::fillCaptionBuffers(), FileTransferWindow::fillCaptionBuffers(), LogViewWindow::fillCaptionBuffers(), EventEditorWindow::fillCaptionBuffers(), RawEditorWindow::fillCaptionBuffers(), PopupEditorWindow::fillCaptionBuffers(), HttpFileTransfer::fillContextPopup(), NotifierWindow::fillContextPopup(), DccFileTransfer::fillContextPopup(), RegisteredUsersDialog::fillList(), LogViewWindow::filterNext(), KviKvsObject::function_listProperties(), KviKvsObject::function_property(), KviKvsObject::function_setProperty(), KvsObject_http::functionGet(), KvsObject_textedit::functionloadFile(), KvsObject_textedit::functionsetAlignment(), KvsObject_textedit::functionsetColor(), KvsObject_http::functionSetHost(), KvsObject_textedit::functionsetTextFormat(), KvsObject_textedit::functionSetWordWrap(), KvsObject_textedit::functionTextLine(), ThemeFunctions::getThemeHtmlDescription(), EventEditor::getUniqueHandlerName(), RawEditorWidget::getUniqueHandlerName(), PopupEditorWidget::getUniquePopupName(), DccBroker::handleChatRequest(), DccChatWindow::handleMarshalError(), DccVoiceWindow::handleMarshalError(), DccVideoWindow::handleMarshalError(), DccFileTransfer::handleMarshalError(), KviKvsParameterProcessor::handleParameterTypeError(), HttpFileTransfer::headersReceived(), HelpWindow::HelpWindow(), http_kvs_complete_get(), HttpFileTransfer::HttpFileTransfer(), CustomToolBarPropertiesDialog::iconButtonClicked(), IdentityProfileEditor::IdentityProfileEditor(), SaveThemeDialog::imageSelectionChanged(), PackThemeImageWidget::imageSelectionChanged(), RegisteredUsersDialog::importClicked(), OptionsWidget_servers::importPopupActivated(), KvsObject_layout::init(), KvsObject_treeWidgetItem::init(), KvsObject_wrapper::init(), PopupTreeWidgetItem::init(), PackAddonSummaryInfoWidget::initializePage(), AddonFunctions::installAddonPackage(), ThemeManagementDialog::installFromFile(), AddonManagementDialog::installScript(), ThemeFunctions::installThemePackage(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), EventEditor::itemPressed(), AliasEditorWidget::itemRenamed(), KviClassEditorDialog::KviClassEditorDialog(), KviClassEditorFunctionDialog::KviClassEditorFunctionDialog(), KviIdentityGeneralOptionsWidget::KviIdentityGeneralOptionsWidget(), KviRegisteredUsersListView::KviRegisteredUsersListView(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreFunctions::KVSCF(), KviXmlHandler::kvsCodeAbort(), KviXmlHandler::kvsCodeFailure(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), OptionsWidget_messageColors::load(), ScriptEditorImplementation::loadFromFile(), log_kvs_cmd_flush(), log_kvs_cmd_start(), log_kvs_cmd_stop(), log_kvs_fnc_export(), log_kvs_fnc_file(), LogListViewItemType::LogListViewItemType(), LogViewListView::LogViewListView(), LogViewWindow::LogViewWindow(), KviXmmsInterface::lookupSymbol(), KviKvsAsyncDnsOperation::lookupTerminated(), SaveThemeDialog::makeScreenshot(), MessageColorListWidgetItem::MessageColorListWidgetItem(), MP_KVS_COMMAND(), MP_KVS_FUNCTION(), KviKvsCoreSimpleCommands::multipleModeCommand(), ActionEditor::newAction(), AliasEditorWidget::newAlias(), OptionsWidget_mediaTypes::newMediaType(), AliasEditorWidget::newNamespace(), ClassEditorWidget::newNamespace(), OptionsWidget_servers::newNetwork(), OptionsWidget_servers::newServer(), CustomizeToolBarsDialog::newToolBar(), NickAlternativesDialog::NickAlternativesDialog(), NickServRuleEditor::NickServRuleEditor(), AddonFunctions::notAValidAddonPackage(), ThemeFunctions::notAValidThemePackage(), notifier_kvs_cmd_message(), MpInterface::notImplemented(), KviKvsTreeNodeScopeOperator::objectFromVariant(), objects_kvs_cmd_connect(), objects_kvs_cmd_disconnect(), objects_kvs_cmd_killClass(), objects_kvs_fnc_classAllHandlers(), objects_kvs_fnc_instances(), objects_kvs_fnc_name(), objects_kvs_fnc_variables(), SharedFileEditDialog::okClicked(), CustomToolBarPropertiesDialog::okClicked(), DccVoiceThread::openSoundcard(), DccVoiceThread::openSoundcardWithDuplexOption(), options_kvs_cmd_edit(), OptionsDialog::OptionsDialog(), OptionsWidget_alerts::OptionsWidget_alerts(), OptionsWidget_antispam::OptionsWidget_antispam(), OptionsWidget_avatar::OptionsWidget_avatar(), OptionsWidget_away::OptionsWidget_away(), OptionsWidget_channelAdvanced::OptionsWidget_channelAdvanced(), OptionsWidget_channelGeneral::OptionsWidget_channelGeneral(), OptionsWidget_connection::OptionsWidget_connection(), OptionsWidget_connectionSocket::OptionsWidget_connectionSocket(), OptionsWidget_connectionSsl::OptionsWidget_connectionSsl(), OptionsWidget_ctcp::OptionsWidget_ctcp(), OptionsWidget_ctcpFloodProtection::OptionsWidget_ctcpFloodProtection(), OptionsWidget_dccAdvanced::OptionsWidget_dccAdvanced(), OptionsWidget_dccChat::OptionsWidget_dccChat(), OptionsWidget_dccGeneral::OptionsWidget_dccGeneral(), OptionsWidget_dccSendAdvanced::OptionsWidget_dccSendAdvanced(), OptionsWidget_dccSendGeneral::OptionsWidget_dccSendGeneral(), OptionsWidget_dccVoice::OptionsWidget_dccVoice(), OptionsWidget_general::OptionsWidget_general(), OptionsWidget_highlighting::OptionsWidget_highlighting(), OptionsWidget_identityAdvanced::OptionsWidget_identityAdvanced(), OptionsWidget_identityAvatar::OptionsWidget_identityAvatar(), OptionsWidget_identityProfile::OptionsWidget_identityProfile(), OptionsWidget_identService::OptionsWidget_identService(), OptionsWidget_ignore::OptionsWidget_ignore(), OptionsWidget_inputFeatures::OptionsWidget_inputFeatures(), OptionsWidget_inputLook::OptionsWidget_inputLook(), OptionsWidget_interfaceFeatures::OptionsWidget_interfaceFeatures(), OptionsWidget_ircAdvanced::OptionsWidget_ircAdvanced(), OptionsWidget_ircGeneral::OptionsWidget_ircGeneral(), OptionsWidget_ircOutput::OptionsWidget_ircOutput(), OptionsWidget_ircViewFeatures::OptionsWidget_ircViewFeatures(), OptionsWidget_ircViewLook::OptionsWidget_ircViewLook(), OptionsWidget_ircViewMarker::OptionsWidget_ircViewMarker(), OptionsWidget_lag::OptionsWidget_lag(), OptionsWidget_logging::OptionsWidget_logging(), OptionsWidget_mediaTypes::OptionsWidget_mediaTypes(), OptionsWidget_messageColors::OptionsWidget_messageColors(), OptionsWidget_nickServ::OptionsWidget_nickServ(), OptionsWidget_notifier::OptionsWidget_notifier(), OptionsWidget_notifierLook::OptionsWidget_notifierLook(), OptionsWidget_notify::OptionsWidget_notify(), OptionsWidget_privmsg::OptionsWidget_privmsg(), OptionsWidget_proxy::OptionsWidget_proxy(), OptionsWidget_query::OptionsWidget_query(), OptionsWidget_servers::OptionsWidget_servers(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), OptionsWidget_sounds::OptionsWidget_sounds(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), OptionsWidget_textIcons::OptionsWidget_textIcons(), OptionsWidget_theme::OptionsWidget_theme(), OptionsWidget_themeMdiArea::OptionsWidget_themeMdiArea(), OptionsWidget_themeToolBarApplets::OptionsWidget_themeToolBarApplets(), OptionsWidget_themeTransparency::OptionsWidget_themeTransparency(), OptionsWidget_timestamp::OptionsWidget_timestamp(), OptionsWidget_tools::OptionsWidget_tools(), OptionsWidget_topicLabel::OptionsWidget_topicLabel(), OptionsWidget_tray::OptionsWidget_tray(), OptionsWidget_uparser::OptionsWidget_uparser(), OptionsWidget_urlHandlers::OptionsWidget_urlHandlers(), OptionsWidget_userListBackground::OptionsWidget_userListBackground(), OptionsWidget_userListFeatures::OptionsWidget_userListFeatures(), OptionsWidget_userListForeground::OptionsWidget_userListForeground(), OptionsWidget_userListGrid::OptionsWidget_userListGrid(), OptionsWidget_windowList::OptionsWidget_windowList(), OptionsWidget_windowListClassic::OptionsWidget_windowListClassic(), OptionsWidget_windowListTreeBackground::OptionsWidget_windowListTreeBackground(), OptionsWidget_windowListTreeFeatures::OptionsWidget_windowListTreeFeatures(), OptionsWidget_windowListTreeForeground::OptionsWidget_windowListTreeForeground(), DccChatWindow::ownAction(), DccVideoWindow::ownAction(), DccChatWindow::ownMessage(), DccVideoWindow::ownMessage(), PackAddonDialog::packAddon(), PackAddonDialog::PackAddonDialog(), PackAddonFileSelectionWidget::PackAddonFileSelectionWidget(), PackAddonInfoPackageWidget::PackAddonInfoPackageWidget(), PackAddonSaveSelectionWidget::PackAddonSaveSelectionWidget(), PackAddonSummaryFilesWidget::PackAddonSummaryFilesWidget(), PackAddonSummaryInfoWidget::PackAddonSummaryInfoWidget(), PackThemeDialog::packTheme(), PackThemeDataWidget::PackThemeDataWidget(), PackThemeDialog::PackThemeDialog(), PackThemeImageWidget::PackThemeImageWidget(), PackThemeInfoWidget::PackThemeInfoWidget(), PackThemeSaveWidget::PackThemeSaveWidget(), KviKvsParser::parse(), KviKvsParser::parseAsExpression(), KviKvsParser::parseAsParameter(), KviKvsParser::parseBindingOperation(), KviKvsParser::parseCommand(), KviKvsParser::parseCommandSwitchList(), KviKvsParser::parseCommaSeparatedParameterList(), KviKvsParser::parseCommaSeparatedParameterListNoTree(), KviKvsParser::parseComment(), KviKvsParser::parseDollar(), KviKvsParser::parseExpressionBinaryOperator(), KviKvsParser::parseExpressionOperand(), KviKvsParser::parseExpressionOperandCore(), KviKvsParser::parseInstruction(), KviKvsParser::parseInstructionBlock(), KviKvsParser::parseOperation(), KviKvsParser::parsePercent(), KviKvsParser::parseSpecialCommandBreak(), KviKvsParser::parseSpecialCommandClass(), KviKvsParser::parseSpecialCommandContinue(), KviKvsParser::parseSpecialCommandDefpopup(), KviKvsParser::parseSpecialCommandDefpopupLabelPopup(), KviKvsParser::parseSpecialCommandDo(), KviKvsParser::parseSpecialCommandFor(), KviKvsParser::parseSpecialCommandForeach(), KviKvsParser::parseSpecialCommandGlobal(), KviKvsParser::parseSpecialCommandIf(), KviKvsParser::parseSpecialCommandSwitch(), KviKvsParser::parseSpecialCommandUnset(), KviKvsParser::parseSpecialCommandWhile(), PackThemeDataWidget::parseThemes(), KviKvsParser::parseVoidFunctionCallOrOperation(), DccBroker::passiveVideoExecute(), perl_kvs_cmd_begin(), perl_kvs_cmd_destroy(), popup_kvs_cmd_addEpilogue(), popup_kvs_cmd_addItem(), popup_kvs_cmd_addPrologue(), popup_kvs_cmd_create(), popup_kvs_cmd_delItem(), popup_kvs_cmd_destroy(), popup_kvs_cmd_show(), popup_kvs_fnc_exists(), PopupEditorWidget::PopupEditorWidget(), PopupEditorWindow::PopupEditorWindow(), PopupEditorWidget::popupRefresh(), KviKvsParameterProcessor::process(), proxydb_kvs_cmd_addProxy(), proxydb_kvs_cmd_setIp(), proxydb_kvs_cmd_setIPv6(), proxydb_kvs_cmd_setPort(), proxydb_kvs_cmd_setProtocol(), proxydb_kvs_fnc_protocol(), python_kvs_cmd_begin(), python_kvs_cmd_destroy(), RawEditorWidget::RawEditorWidget(), RawEditorWindow::RawEditorWindow(), HttpFileTransfer::receivedResponse(), DccBroker::recvFileManage(), regchan_kvs_cmd_remove(), regchan_kvs_cmd_setProperty(), regchan_kvs_cmd_showlist(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), RegisteredUserMaskDialog::RegisteredUserMaskDialog(), RegisteredUserPropertiesDialog::RegisteredUserPropertiesDialog(), RegisteredUsersDialog::RegisteredUsersDialog(), RegisteredUsersDialogItem::RegisteredUsersDialogItem(), RegistrationWizard::RegistrationWizard(), reguser_kvs_cmd_add(), reguser_kvs_cmd_addmask(), reguser_kvs_cmd_delmask(), reguser_kvs_cmd_remove(), reguser_kvs_cmd_setIgnoreEnabled(), reguser_kvs_cmd_setIgnoreFlags(), reguser_kvs_cmd_setproperty(), reguser_kvs_cmd_showlist(), AliasEditorWidget::removeItem(), ClassEditorWidget::removeItem(), ClassEditorWidget::renameClass(), DccBroker::renameDccSendFile(), ClassEditorWidget::renameFunction(), AliasEditorWidget::renameItem(), ClassEditorWidget::renameNamespace(), DccBroker::renameOverwriteResume(), CustomizeToolBarsDialog::renameToolBar(), KviKvsReport::report(), KviKvsRunTimeContext::report(), KviKvsParser::report(), HttpFileTransfer::requestSent(), HttpFileTransfer::resolvingHost(), DccFileTransfer::resumeAccepted(), LogViewWindow::rightButtonClicked(), FileTransferWindow::rightButtonPressed(), RegisteredUsersDialog::rightButtonPressed(), DccBroker::rsendAskForFileName(), DccBroker::rsendExecute(), DccSendThread::run(), OptionsWidget_messageColors::save(), OptionsWidget_mediaTypes::saveLastItem(), OptionsWidget_servers::saveLastItem(), SaveThemeDialog::saveTheme(), SaveThemeDialog::SaveThemeDialog(), ScriptEditorImplementation::saveToFile(), ScriptEditorImplementation::ScriptEditorImplementation(), ScriptEditorReplaceDialog::ScriptEditorReplaceDialog(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), StatusBarApplet::selfRegister(), DccBroker::sendFileExecute(), DccBroker::sendFileManage(), serverdb_kvs_cmd_addNetwork(), serverdb_kvs_cmd_addServer(), serverdb_kvs_fnc_networkExists(), serverdb_kvs_fnc_serverExists(), DccVoiceWindow::setMixerVolume(), OptionsWidgetContainer::setup(), sharedfile_kvs_cmd_add(), sharedfile_kvs_cmd_list(), sharedfile_kvs_cmd_remove(), SharedFileEditDialog::SharedFileEditDialog(), SharedFilesTreeWidgetItem::SharedFilesTreeWidgetItem(), SharedFilesWindow::SharedFilesWindow(), NotifierWindow::showLineEdit(), SingleActionEditor::SingleActionEditor(), SinglePopupEditor::SinglePopupEditor(), KviKvsParser::skipToEndOfForControlBlock(), AliasEditorWidget::slotFind(), ClassEditorWidget::slotFind(), ScriptEditorWidget::slotReplace(), DccMarshal::snActivated(), DccChatWindow::sslError(), DccFileTransfer::sslError(), DccChatWindow::startConnection(), DccVoiceWindow::startConnection(), DccVideoWindow::startConnection(), DccFileTransfer::startConnection(), AvatarDownloadDialog::startDownload(), DccChatWindow::startingSSLHandshake(), DccFileTransfer::startingSSLHandshake(), StatusBarApplet::StatusBarApplet(), TC_KVS_COMMAND(), theme_kvs_cmd_apply(), theme_kvs_cmd_install(), theme_kvs_cmd_screenshot(), theme_kvs_fnc_info(), ThemeListWidgetItem::ThemeListWidgetItem(), ThemeManagementDialog::ThemeManagementDialog(), KviKvsTimerManager::timerEvent(), DccFileTransfer::tipText(), HttpFileTransfer::transferTerminated(), TrashcanLabel::TrashcanLabel(), KviKvsProcessAsyncOperation::trigger(), KviKvsEventManager::triggerHandlers(), AddonManagementDialog::uninstallScript(), StatusBarApplet::update(), ScriptEditorImplementation::updateRowColLabel(), userlist_kvs_cmd_ensureVisible(), userlist_kvs_cmd_select(), userlist_kvs_fnc_selected(), NickServRuleEditor::validate(), KviKvsRunTimeContext::warningMissingParameter(), and KviKvsRunTimeContext::warningNoIrcConnection().
MP_IMPLEMENT_DESCRIPTOR (KviXmmsInterface , "xmms" , __tr2qs_ctx("An interface to the popular UNIX xmms media player.\n""Download it from http://legacy.xmms2.org\n","mediaplayer"))
Variable Documentation
const char* audacious_lib_names[] static
Initial value:
{
        "libaudacious.so",
        "libaudacious.so.4",
        "/usr/lib/libaudacious.so",
        "/usr/lib/libaudacious.so.4",
        "/usr/local/lib/libaudacious.so",
        "/usr/local/lib/libaudacious.so.4",
        0
}
Referenced by KviAudaciousClassicInterface::KviAudaciousClassicInterface().
audacious classic