KVIrc: KviSASL Namespace Reference
KviSASL Namespace Reference
This namespace implement some SASL authentication methods.
Functions
bool dh_blowfishMethod (KviCString &szIn, KviCString &szOut, QByteArray &baNick, QByteArray &baPass)
Create the auth message for DH-BLOWFISH authentication.
bool plainMethod (KviCString &szIn, KviCString &szOut, QByteArray &baNick, QByteArray &baPass)
Create the auth message for PLAIN authentication.
Detailed Description
This namespace implement some SASL authentication methods.
Currently implementhed methods are PLAIN and DH-BLOWFISH
Function Documentation
KVILIB_API bool KviSASL::dh_blowfishMethod (KviCString & szIn, KviCString & szOut, QByteArray & baNick, QByteArray & baPass)
Create the auth message for DH-BLOWFISH authentication.
Parameters
szIn The server-provided token
szOut A KviCString that will be filled with the authentication message
baNick The username
baPass The password
Returns
bool
Referenced by KviIrcConnection::handleAuthenticate().
KVILIB_API bool KviSASL::plainMethod (KviCString & szIn, KviCString & szOut, QByteArray & baNick, QByteArray & baPass)
Create the auth message for PLAIN authentication.
Parameters
szIn The server-provided token
szOut A KviCString that will be filled with the authentication message
baNick The username
baPass The password
Returns
bool
References KviMemory::allocate(), KviCString::bufferToBase64(), and KviMemory::free().
Referenced by KviIrcConnection::handleAuthenticate().