KVIrc: KviTheme Namespace Reference
KviTheme Namespace Reference
Functions
void installedThemes (QStringList &slThemes, bool bBuiltin)
bool load (const QString &szThemeDir, KviThemeInfo &buffer, bool bBuiltin)
bool save (KviThemeInfo &options)
bool saveScreenshots (KviThemeInfo &options, const QString &szOriginalScreenshotPath)
Function Documentation
void KVIRC_API KviTheme::installedThemes (QStringList & slThemes, bool bBuiltin)
References d, g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), and KviApplication::Themes.
Referenced by ThemeManagementDialog::fillThemeBox().
bool KVIRC_API KviTheme::load (const QString & szThemeName, KviThemeInfo & buffer, bool bBuiltin = false)
Attempt to load (apply) a theme from globaldir::theme (bBuiltin=true) or from localdir::theme. Will return true on success and false on failure. On success this function will return the theme information in the buffer. On failure this function will also set buffer.lastError() to a meaningful value Note that for convenience this function is implemented in KviOptions.cpp
References KviApplication::findImage(), KviStringConversion::fromString(), g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pApp, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, KviThemeInfo::getCompleteDirPath(), KviApplication::getLocalKvircDirectory(), KviConfigurationFile::hasKey(), i, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KVI_OPTION_STRING, KVI_THEMEDATA_CONFIG_GROUP, KVI_THEMEDATA_FILE_NAME, KviOption_stringIconThemeSubdir, KviThemeInfo::load(), KviOsInfo::name(), KviApplication::optionResetUpdate(), KviConfigurationFile::Read, READ_ALL_OPTIONS, READ_OPTIONS, KviConfigurationFile::readEntry(), KviFileUtils::removeFile(), KviConfigurationFile::setGroup(), szBuffer, t(), KviApplication::Themes, and KviFileUtils::writeFile().
Referenced by ThemeManagementDialog::applyCurrentTheme(), KviAnimatedPixmap::KviAnimatedPixmap(), PluginManager::loadPlugin(), setup_finish(), and theme_kvs_cmd_apply().
bool KVIRC_API KviTheme::save (KviThemeInfo & options)
Save a theme given the specified options. Will return true on success and false on failure. On failure this function will also set options.lastError() to a meaningful value This function requires both absoluteDirectory() and subdirectory() to be set to the right values. In theory this function could save a theme in a directory different than $KVIRC_LOCAL_DIR/themes/subdirectory but this feature is actually unused. Note that for convenience this function is implemented in KviOptions.cpp
References __tr2qs, KviFileUtils::copyFile(), d, KviFileUtils::directoryExists(), g_boolOptionsTable, g_colorOptionsTable, g_fontOptionsTable, g_iccolorOptionsTable, g_mirccolorOptionsTable, g_msgtypeOptionsTable, g_pApp, g_pIconManager, g_pixmapOptionsTable, g_rectOptionsTable, g_stringlistOptionsTable, g_stringOptionsTable, g_uintOptionsTable, KviThemeInfo::getCompleteDirPath(), KviApplication::getGlobalKvircDirectory(), KviIconManager::getPixmapWithCache(), KviIconManager::getSmallIcon(), KviIconManager::getSmallIconName(), i, KviIconManager::IconCount, j, KVI_NUM_BOOL_OPTIONS, KVI_NUM_COLOR_OPTIONS, KVI_NUM_FONT_OPTIONS, KVI_NUM_ICCOLOR_OPTIONS, KVI_NUM_MIRCCOLOR_OPTIONS, KVI_NUM_MSGTYPE_OPTIONS, KVI_NUM_PIXMAP_OPTIONS, KVI_NUM_RECT_OPTIONS, KVI_NUM_STRING_OPTIONS, KVI_NUM_STRINGLIST_OPTIONS, KVI_NUM_UINT_OPTIONS, KVI_PATH_SEPARATOR_CHAR, KVI_SMALLICONS_SUBDIRECTORY, KVI_THEMEDATA_CONFIG_GROUP, KVI_THEMEDATA_FILE_NAME, KVI_THEMEINFO_FILE_NAME, KviFileUtils::makeDir(), KviOsInfo::name(), p, KviCachedPixmap::path(), KviApplication::Pics, KviThemeInfo::save(), KviConfigurationFile::setGroup(), KviThemeInfo::setLastError(), KviThemeInfo::subdirectory(), KviConfigurationFile::Write, WRITE_OPTIONS, and KviConfigurationFile::writeEntry().
Referenced by compute_descriptor_score(), KviIrcView::getTextLine(), KviIrcServerParser::parseNumericNames(), SaveThemeDialog::saveTheme(), str_kvs_fnc_printf(), KviConfigurationFile::sync(), and KviCString::vsprintf().
bool KVIRC_API KviTheme::saveScreenshots (KviThemeInfo & options, const QString & szOriginalScreenshotPath)
Save the theme screenshots in the given EXISTING directory and given an existing screenshot on disk (usually in the tmp directory).
References __tr2qs, KviThemeInfo::getCompleteDirPath(), KVI_THEME_LARGE_SCREENSHOT_NAME, KVI_THEME_MEDIUM_SCREENSHOT_NAME, KVI_THEME_SMALL_SCREENSHOT_NAME, QIMAGE_SCALE_MIN, and KviThemeInfo::setLastError().
Referenced by SaveThemeDialog::saveTheme().