KVIrc: KviByteOrder Namespace Reference
KviByteOrder Namespace Reference
Functions
kvi_u16_t bigEndianToLocalCpu16 (kvi_u16_t u)
kvi_u32_t bigEndianToLocalCpu32 (kvi_u32_t u)
kvi_u64_t bigEndianToLocalCpu64 (kvi_u64_t u)
kvi_u16_t littleEndianToLocalCpu16 (kvi_u16_t u)
kvi_u32_t littleEndianToLocalCpu32 (kvi_u32_t u)
kvi_u64_t littleEndianToLocalCpu64 (kvi_u64_t u)
kvi_u16_t localCpuToBigEndian16 (kvi_u16_t u)
kvi_u32_t localCpuToBigEndian32 (kvi_u32_t u)
kvi_u64_t localCpuToBigEndian64 (kvi_u64_t u)
kvi_u16_t localCpuToLittleEndian16 (kvi_u16_t u)
kvi_u32_t localCpuToLittleEndian32 (kvi_u32_t u)
kvi_u64_t localCpuToLittleEndian64 (kvi_u64_t u)
kvi_u16_t localCpuToNetworkByteOrder16 (kvi_u16_t u)
kvi_u32_t localCpuToNetworkByteOrder32 (kvi_u32_t u)
kvi_u64_t localCpuToNetworkByteOrder64 (kvi_u64_t u)
kvi_u16_t networkByteOrderToLocalCpu16 (kvi_u16_t u)
kvi_u32_t networkByteOrderToLocalCpu32 (kvi_u32_t u)
kvi_u64_t networkByteOrderToLocalCpu64 (kvi_u64_t u)
kvi_u16_t swap16 (kvi_u16_t i)
Swaps the endianness of a kvi_u16_t.
kvi_u32_t swap32 (kvi_u32_t i)
Swaps the endianness of a kvi_u32_t.
kvi_u64_t swap64 (kvi_u64_t i)
Swaps the endianness of a kvi_u64_t.
Function Documentation
kvi_u16_t KviByteOrder::bigEndianToLocalCpu16 (kvi_u16_t u) inline
References swap16().
kvi_u32_t KviByteOrder::bigEndianToLocalCpu32 (kvi_u32_t u) inline
References swap32().
kvi_u64_t KviByteOrder::bigEndianToLocalCpu64 (kvi_u64_t u) inline
References swap64().
kvi_u16_t KviByteOrder::littleEndianToLocalCpu16 (kvi_u16_t u) inline
References u.
Referenced by KviFile::load().
kvi_u32_t KviByteOrder::littleEndianToLocalCpu32 (kvi_u32_t u) inline
References u.
Referenced by KviFile::load().
kvi_u64_t KviByteOrder::littleEndianToLocalCpu64 (kvi_u64_t u) inline
References u.
kvi_u16_t KviByteOrder::localCpuToBigEndian16 (kvi_u16_t u) inline
References swap16().
kvi_u32_t KviByteOrder::localCpuToBigEndian32 (kvi_u32_t u) inline
References swap32().
kvi_u64_t KviByteOrder::localCpuToBigEndian64 (kvi_u64_t u) inline
References swap64().
kvi_u16_t KviByteOrder::localCpuToLittleEndian16 (kvi_u16_t u) inline
References u.
Referenced by KviFile::save().
kvi_u32_t KviByteOrder::localCpuToLittleEndian32 (kvi_u32_t u) inline
References u.
Referenced by KviFile::save().
kvi_u64_t KviByteOrder::localCpuToLittleEndian64 (kvi_u64_t u) inline
References u.
Referenced by KviFile::save().
kvi_u16_t KviByteOrder::localCpuToNetworkByteOrder16 (kvi_u16_t u) inline
References swap16().
Referenced by system_kvs_fnc_htoni().
kvi_u32_t KviByteOrder::localCpuToNetworkByteOrder32 (kvi_u32_t u) inline
References swap32().
Referenced by system_kvs_fnc_htoni().
kvi_u64_t KviByteOrder::localCpuToNetworkByteOrder64 (kvi_u64_t u) inline
References swap64().
Referenced by system_kvs_fnc_htoni().
kvi_u16_t KviByteOrder::networkByteOrderToLocalCpu16 (kvi_u16_t u) inline
References swap16().
Referenced by system_kvs_fnc_ntohi().
kvi_u32_t KviByteOrder::networkByteOrderToLocalCpu32 (kvi_u32_t u) inline
References swap32().
Referenced by system_kvs_fnc_ntohi().
kvi_u64_t KviByteOrder::networkByteOrderToLocalCpu64 (kvi_u64_t u) inline
References swap64().
Referenced by system_kvs_fnc_ntohi().
kvi_u16_t KviByteOrder::swap16 (kvi_u16_t i) inline
Swaps the endianness of a kvi_u16_t.
Parameters
i the original value
Returns
kvi_u16_t
Referenced by bigEndianToLocalCpu16(), localCpuToBigEndian16(), localCpuToNetworkByteOrder16(), and networkByteOrderToLocalCpu16().
kvi_u32_t KviByteOrder::swap32 (kvi_u32_t i) inline
Swaps the endianness of a kvi_u32_t.
Parameters
i the original value
Returns
kvi_u32_t
Referenced by bigEndianToLocalCpu32(), localCpuToBigEndian32(), localCpuToNetworkByteOrder32(), and networkByteOrderToLocalCpu32().
kvi_u64_t KviByteOrder::swap64 (kvi_u64_t i) inline
Swaps the endianness of a kvi_u64_t.
Parameters
i the original value
Returns
kvi_u64_t
Referenced by bigEndianToLocalCpu64(), localCpuToBigEndian64(), localCpuToNetworkByteOrder64(), and networkByteOrderToLocalCpu64().