KVIrc: AddonFunctions Namespace Reference
AddonFunctions Namespace Reference
Functions
QString createRandomDir ()
bool installAddonPackage (const QString &szAddonPackageFileName, QString &szError, QWidget *pDialogParent)
bool notAValidAddonPackage (QString &szError)
Function Documentation
QString AddonFunctions::createRandomDir ()
References i, and n.
Referenced by installAddonPackage().
bool AddonFunctions::installAddonPackage (const QString & szAddonPackageFileName, QString & szError, QWidget * pDialogParent)
References __tr2qs_ctx(), KviHtmlDialogData::addHtmlResource(), KviHtmlDialogData::addImageResource(), KviIconManager::Addons, KviPackageIOEngine::binaryInfoFields(), KviMiscUtils::compareVersions(), createRandomDir(), KviFileUtils::deleteDir(), KviHtmlDialog::display(), KviQString::ensureLastCharIs(), KviQString::equalCI(), KviQString::escapeKvs(), KviQString::EscapeSpace, KviPointerHashTable< Key, T >::find(), KviHtmlDialogData::ForceMinimumSize, g_pActiveWindow, g_pApp, g_pIconManager, KviIconManager::getBigIcon(), KviApplication::getLocalKvircDirectory(), KviIconManager::getSmallIcon(), KviPackageReader::getStringInfoField(), i, KviHtmlDialogData::iCancelButton, KviHtmlDialogData::iDefaultButton, KviHtmlDialogData::iFlags, KviHtmlDialogData::iMinimumHeight, KviHtmlDialogData::iMinimumWidth, KVI_BIGICON_ADDONS, KVI_CURRENT_ADDONS_ENGINE_VERSION, KVI_PATH_SEPARATOR_CHAR, KviPackageIOEngine::lastError(), notAValidAddonPackage(), NULL, KviHtmlDialogData::pixIcon, r, KviPackageReader::readHeader(), KviKvsScript::run(), KviPackageIOEngine::stringInfoFields(), KviHtmlDialogData::szButton1Text, KviHtmlDialogData::szButton2Text, KviHtmlDialogData::szCaption, KviHtmlDialogData::szHtmlText, KviHtmlDialogData::szLowerLabelText, KviHtmlDialogData::szUpperLabelText, KviApplication::Tmp, KviPackageReader::unpack(), and KviMessageBox::warning().
Referenced by addon_kvs_cmd_install(), and AddonManagementDialog::installScript().
bool AddonFunctions::notAValidAddonPackage (QString & szError)
References __tr2qs_ctx().
Referenced by installAddonPackage(), and AddonManagementDialog::installScript().