KVIrc: KviKvsCoreCallbackCommands Namespace Reference
KviKvsCoreCallbackCommands Namespace Reference
Functions
void init ()
KVSCCC (timer)
KVSCCC (privateimpl)
KVSCCC (exec)
KVSCCC (event)
KVSCCC (button)
KVSCCC (awhois)
KVSCCC (alias)
KVSCCC (ahost)
Function Documentation
void KviKvsCoreCallbackCommands::init ()
References _REGCMD, and KviKvsKernel::instance().
KviKvsCoreCallbackCommands::KVSCCC (timer)
References __tr2qs_ctx, KviKvsVariantList::append(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviKvsTimerManager::instance(), KviKvsVariant::isEmpty(), KVSCCC_pCallback, KVSCCC_pContext, KVSCCC_pParams, KVSCCC_pSwitches, KviKvsTimer::Persistent, KviKvsVariantList::setAutoDelete(), KviKvsTimer::SingleShot, and KviKvsTimer::WindowLifetime.
KviKvsCoreCallbackCommands::KVSCCC (privateimpl)
References __tr2qs_ctx, KviKvsKernel::instance(), KVS_PT_HOBJECT, KVS_PT_NONEMPTYSTRING, KVSCCC_PARAMETER, KVSCCC_PARAMETERS_BEGIN, KVSCCC_PARAMETERS_END, KVSCCC_pCallback, KVSCCC_pContext, KviKvsObjectController::lookupObject(), KviKvsKernel::objectController(), and Q_UNUSED().
KviKvsCoreCallbackCommands::KVSCCC (exec)
References __tr2qs_ctx, KviKvsVariant::asInteger(), d, _KviKvsProcessDescriptorData::iFlags, _KviKvsProcessDescriptorData::iMaxRunTime, _KviKvsProcessDescriptorData::iPingTimeout, KVI_KVS_PROCESSDESCRIPTOR_KILLIFNOWINDOW, KVI_KVS_PROCESSDESCRIPTOR_NOSHELL, KVI_KVS_PROCESSDESCRIPTOR_OUTPUTBYBLOCKS, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTARTED, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDERR, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERSTDOUT, KVI_KVS_PROCESSDESCRIPTOR_TRIGGERTERMINATED, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANT, KVSCCC_PARAMETER, KVSCCC_PARAMETERS_BEGIN, KVSCCC_PARAMETERS_END, KVSCCC_pCallback, KVSCCC_pContext, KVSCCC_pSwitches, _KviKvsProcessDescriptorData::pCallback, _KviKvsProcessDescriptorData::pMagic, _KviKvsProcessDescriptorData::pWnd, KviKvsProcessAsyncOperation::start(), _KviKvsProcessDescriptorData::szCommandline, and _KviKvsProcessDescriptorData::szShell.
KviKvsCoreCallbackCommands::KVSCCC (event)
References __tr2qs_ctx, KviKvsEventManager::addAppHandler(), KviKvsEventManager::addRawHandler(), KviKvsEventManager::findAppEventIndexByName(), KviKvsEventManager::instance(), KviKvsEventManager::isValidRawEvent(), KVS_PT_NONEMPTYSTRING, KVSCCC_PARAMETER, KVSCCC_PARAMETERS_BEGIN, KVSCCC_PARAMETERS_END, KVSCCC_pCallback, KVSCCC_pContext, KVSCCC_pSwitches, KviKvsEventManager::removeScriptAppHandler(), KviKvsEventManager::removeScriptRawHandler(), and KviQString::sprintf().
KviKvsCoreCallbackCommands::KVSCCC (button)
References __tr2qs_ctx, KviTalToolTip::add(), g_pIconManager, KviIconManager::getImage(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANT, KVSCCC_PARAMETER, KVSCCC_PARAMETERS_BEGIN, KVSCCC_PARAMETERS_END, KVSCCC_pCallback, KVSCCC_pContext, KVSCCC_pSwitches, KVSCCC_pWindow, and KviTalToolTip::remove().
KviKvsCoreCallbackCommands::KVSCCC (awhois)
References KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANT, KVSCCC_PARAMETER, KVSCCC_PARAMETERS_BEGIN, KVSCCC_PARAMETERS_END, KVSCCC_pCallback, KVSCCC_pConnection, KVSCCC_pSwitches, KVSCCC_pWindow, KVSCCC_REQUIRE_CONNECTION, KviAsyncWhoisInfo::pCallback, KviAsyncWhoisInfo::pMagic, KviAsyncWhoisInfo::pWindow, and KviAsyncWhoisInfo::szNick.
KviKvsCoreCallbackCommands::KVSCCC (alias)
References __tr2qs_ctx, KviKvsAliasManager::add(), KviKvsVariant::asString(), KviKvsAliasManager::instance(), KviKvsVariant::isEmpty(), KVSCCC_pCallback, KVSCCC_pContext, KVSCCC_pParams, KVSCCC_pSwitches, KviKvsAliasManager::remove(), and KviKvsScript::setName().
KviKvsCoreCallbackCommands::KVSCCC (ahost)
References KviDns::Any, KviDns::IPv4, KviDns::IPv6, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANT, KVSCCC_PARAMETER, KVSCCC_PARAMETERS_BEGIN, KVSCCC_PARAMETERS_END, KVSCCC_pCallback, KVSCCC_pContext, and KVSCCC_pSwitches.