KVIrc: ThemeFunctions Namespace Reference
ThemeFunctions Namespace Reference
Functions
void getThemeHtmlDescription (QString &szBuffer, const QString &szThemeName, const QString &szThemeVersion, const QString &szThemeDescription, const QString &szThemeSubdirectory, const QString &szThemeApplication, const QString &szThemeAuthor, const QString &szThemeDate, const QString &szThemeThemeEngineVersion, const QPixmap &pixScreenshot, int iUniqueIndexInDocument, KviHtmlDialogData *hd)
bool installThemePackage (const QString &szThemePackageFileName, QString &szError, QWidget *pDialogParent)
bool makeKVIrcScreenshot (const QString &szSavePngFilePath, bool bMaximizeFrame)
static bool notAValidThemePackage (QString &szError)
Function Documentation
void ThemeFunctions::getThemeHtmlDescription (QString & szBuffer, const QString & szThemeName, const QString & szThemeVersion, const QString & szThemeDescription, const QString & szThemeSubdirectory, const QString & szThemeApplication, const QString & szThemeAuthor, const QString & szThemeDate, const QString & szThemeThemeEngineVersion, const QPixmap & pixScreenshot, int iUniqueIndexInDocument, KviHtmlDialogData * hd)
References __tr2qs_ctx(), and KviHtmlDialogData::addImageResource().
Referenced by installThemePackage(), and PackThemeDataWidget::parseThemes().
bool ThemeFunctions::installThemePackage (const QString & szThemePackageFileName, QString & szError, QWidget * pDialogParent)
References __tr2qs_ctx(), KviHtmlDialogData::addHtmlResource(), KviHtmlDialogData::addImageResource(), KviPackageIOEngine::binaryInfoFields(), KviMiscUtils::compareVersions(), KviHtmlDialog::display(), KviQString::equalCI(), KviPointerHashTable< Key, T >::find(), KviHtmlDialogData::ForceMinimumSize, g_pApp, g_pIconManager, KviIconManager::getBigIcon(), KviApplication::getLocalKvircDirectory(), KviIconManager::getSmallIcon(), KviPackageReader::getStringInfoField(), getThemeHtmlDescription(), i, KviHtmlDialogData::iCancelButton, KviHtmlDialogData::iDefaultButton, KviHtmlDialogData::iFlags, KviHtmlDialogData::iMinimumHeight, KviHtmlDialogData::iMinimumWidth, KVI_BIGICON_THEME, KVI_CURRENT_THEME_ENGINE_VERSION, KviPackageIOEngine::lastError(), notAValidThemePackage(), KviHtmlDialogData::pixIcon, r, KviPackageReader::readHeader(), KviPackageIOEngine::stringInfoFields(), KviHtmlDialogData::szButton1Text, KviHtmlDialogData::szButton2Text, KviHtmlDialogData::szCaption, KviHtmlDialogData::szHtmlText, KviHtmlDialogData::szLowerLabelText, KviHtmlDialogData::szUpperLabelText, KviIconManager::Theme, KviApplication::Themes, and KviPackageReader::unpack().
Referenced by ThemeManagementDialog::installFromFile(), and theme_kvs_cmd_install().
bool ThemeFunctions::makeKVIrcScreenshot (const QString & szSavePngFilePath, bool bMaximizeFrame)
References g_pMainWindow.
Referenced by SaveThemeDialog::makeScreenshot(), and theme_kvs_cmd_screenshot().
static bool ThemeFunctions::notAValidThemePackage (QString & szError) static
References __tr2qs_ctx().
Referenced by installThemePackage().