KVIrc: KviStringConversion Namespace Reference
KviStringConversion Namespace Reference
Functions
void decodePath (QString &szBuffer)
void decodePath (QStringList &buffer)
void encodePath (QString &szBuffer)
void encodePath (QStringList &buffer)
bool fromString (const QString &szValue, bool &bBuffer)
bool fromString (const QString &szValue, int &iBuffer)
bool fromString (const QString &szValue, unsigned int &uBuffer)
bool fromString (const QString &szValue, QRect &buffer)
bool fromString (const QString &szValue, QString &szBuffer)
bool fromString (const QString &szValue, KviPixmap &buffer)
bool fromString (const QString &szValue, KviMessageTypeSettings &buffer)
bool fromString (const QString &szValue, QColor &buffer)
bool fromString (const QString &szValue, QFont &buffer)
bool fromString (const QString &szValue, QStringList &buffer)
void init (const QString &szGlobalDir, const QString &szLocalDir)
void toString (const bool bValue, QString &szBuffer)
void toString (const int iValue, QString &szBuffer)
void toString (const unsigned int uValue, QString &szBuffer)
void toString (const QRect &rValue, QString &szBuffer)
void toString (const QString &szValue, QString &szBuffer)
void toString (const KviPixmap &pixmap, QString &szBuffer)
void toString (const KviMessageTypeSettings &mValue, QString &szBuffer)
void toString (const QColor &value, QString &szBuffer)
void toString (const QFont &font, QString &szBuffer)
void toString (const QStringList &list, QString &szBuffer)
Function Documentation
KVILIB_API void KviStringConversion::decodePath (QString & szBuffer)
References g_szGlobalDir, and g_szLocalDir.
Referenced by decodePath(), fromString(), KviApplication::loadOptions(), and KviApplication::saveOptions().
KVILIB_API void KviStringConversion::decodePath (QStringList & buffer)
References decodePath().
KVILIB_API void KviStringConversion::encodePath (QString & szBuffer)
References g_szGlobalDir, and g_szLocalDir.
Referenced by encodePath(), KviApplication::saveOptions(), and toString().
KVILIB_API void KviStringConversion::encodePath (QStringList & buffer)
References encodePath().
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, bool & bBuffer)
References KviQString::equalCI(), and KviQString::equalCS().
Referenced by KviDefaultScriptManager::compareVersions(), KviDefaultScriptManager::isDefscriptUpToDate(), KviTheme::load(), LogFile::LogFile(), KviConfigurationFile::readMsgTypeEntry(), KviConfigurationFile::readPixmapEntry(), KviConfigurationFile::readRectEntry(), KviIrcUserDataBase::registeredUser(), RegisteredUserEntryDialog::RegisteredUserEntryDialog(), KviConfigurationFile::setFontProperties(), and KviApplication::setOptionValue().
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, int & iBuffer)
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, unsigned int & uBuffer)
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, QRect & buffer)
References c, h, l, t(), and w.
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, QString & szBuffer)
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, KviPixmap & buffer)
References decodePath(), KviPixmap::load(), and KviPixmap::setNull().
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, KviMessageTypeSettings & buffer)
References KviMessageTypeSettings::m_szType.
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, QColor & buffer)
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, QFont & buffer)
References KviCString::contains(), KviCString::getToken(), i, KviCString::isEmpty(), KviCString::ptr(), and KviCString::toInt().
KVILIB_API bool KviStringConversion::fromString (const QString & szValue, QStringList & buffer)
KVILIB_API void KviStringConversion::init (const QString & szGlobalDir, const QString & szLocalDir)
References g_szGlobalDir, and g_szLocalDir.
KVILIB_API void KviStringConversion::toString (const bool bValue, QString & szBuffer)
Referenced by KviMainWindow::accelActivated(), KviConfigurationFile::getFontProperties(), KVSO_CLASS_FUNCTION(), RegisteredUserEntryDialog::okClicked(), and KviConfigurationFile::writeEntry().
KVILIB_API void KviStringConversion::toString (const int iValue, QString & szBuffer)
KVILIB_API void KviStringConversion::toString (const unsigned int uValue, QString & szBuffer)
KVILIB_API void KviStringConversion::toString (const QRect & rValue, QString & szBuffer)
KVILIB_API void KviStringConversion::toString (const QString & szValue, QString & szBuffer)
KVILIB_API void KviStringConversion::toString (const KviPixmap & pixmap, QString & szBuffer)
References encodePath(), and KviPixmap::path().
KVILIB_API void KviStringConversion::toString (const KviMessageTypeSettings & mValue, QString & szBuffer)
References KviMessageTypeSettings::m_bLogEnabled, KviMessageTypeSettings::m_cBackColor, KviMessageTypeSettings::m_cForeColor, KviMessageTypeSettings::m_iLevel, and KviMessageTypeSettings::m_iPixId.
KVILIB_API void KviStringConversion::toString (const QColor & value, QString & szBuffer)
KVILIB_API void KviStringConversion::toString (const QFont & font, QString & szBuffer)
KVILIB_API void KviStringConversion::toString (const QStringList & list, QString & szBuffer)