KVIrc: KviRuntimeInfo Namespace Reference
KviRuntimeInfo Namespace Reference
Functions
QString hostname ()
QString machine ()
QString name ()
QString nodename ()
QString qtTheme ()
QString qtVersion ()
QString release ()
QString type ()
QString version ()
Function Documentation
KVILIB_API QString KviRuntimeInfo::hostname ()
References KviQString::Empty.
Referenced by UPnP::IgdControlPoint::IgdControlPoint(), KviKvsCoreFunctions::init(), and system_kvs_fnc_hostname().
KVILIB_API QString KviRuntimeInfo::machine ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), and system_kvs_fnc_osmachine().
KVILIB_API QString KviRuntimeInfo::name ()
References KviQString::Empty.
Referenced by _q_parseDosDir(), _q_parseUnixDir(), AboutDialog::AboutDialog(), KviTheme::apply(), KviThemedLineEdit::applyOptions(), KviThemedLabel::applyOptions(), KviThemedComboBox::applyOptions(), KviThemedTreeWidget::applyOptions(), KviKvsObject::callFunction(), KviTextIconManager::checkDefaultAssociations(), KviChannelWindow::closeEvent(), KviHtmlGenerator::convertToHtml(), KviCast::dynamic(), KviKvsObject::emitSignal(), EventEditor::eventHandlerDisabled(), KviKvsEventManager::findAppEventByName(), KviKvsEventManager::findAppEventIndexByName(), ClassEditorWidget::findFunction(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), KviKvsObject::function_className(), KviChannelWindow::getConfigGroupName(), KviIrcSocket::getLocalHostIp(), KviKvsCoreFunctions::KVSCF(), KviIrcConnection::linkEstablished(), KviKvsEventManager::loadAppEvents(), ActionEditor::newAction(), RegisteredUserEntryDialog::okClicked(), EventEditor::oneTimeSetup(), RawEditorWidget::oneTimeSetup(), KviChannelWindow::ownAction(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseCtcpRequestVersion(), KviKvsEventManager::removeScriptAppHandler(), KviKvsEventManager::removeScriptRawHandler(), KviTheme::save(), KviKvsEventManager::saveAppEvents(), ClassEditorWidget::saveNotBuiltClasses(), KviKvsEventManager::saveRawEvents(), KvsObject_http::slotRequestFinished(), system_kvs_fnc_osname(), KviChannelWindow::topicSelected(), and torrent_module_init().
KVILIB_API QString KviRuntimeInfo::nodename ()
References KviQString::Empty.
Referenced by system_kvs_fnc_osnodename().
KVILIB_API QString KviRuntimeInfo::qtTheme ()
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviRuntimeInfo::qtVersion ()
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviRuntimeInfo::release ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), KviIrcServerParser::parseCtcpRequestVersion(), and system_kvs_fnc_osrelease().
KVILIB_API QString KviRuntimeInfo::type ()
Referenced by AliasEditorWidget::appendAllItems(), AliasEditorWidget::appendAllItemsRecursive(), QHttpHeader::contentType(), RegisteredUsersDialog::exportClicked(), KviIrcMessageCheckListItem::KviIrcMessageCheckListItem(), KviKvsCoreSimpleCommands::KVSCSC(), KviProxyDataBase::load(), KviKvsPopupMenu::load(), KviTextBrowser::loadResource(), KviDnsResolver::lookup(), KviIrcServerParser::parseCtcpRequestAction(), KviProxyDataBase::save(), KviDnsResolverThread::setQuery(), KviImageDialog::startJob(), and system_kvs_fnc_ostype().
KVILIB_API QString KviRuntimeInfo::version ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), KviKvsCoreFunctions::init(), KviOggIrcText::irct_decode_headerin(), KviBasicIrcServerInfo::KviBasicIrcServerInfo(), KviIrcServerParser::parseCtcpRequestSource(), KviIrcServerParser::parseCtcpRequestVersion(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseNumeric004(), KviIrcServerParser::parseNumeric344(), KviIrcServerParser::parseNumeric345(), KviIrcServerParser::parseNumeric480(), KviIrcServerParser::parseNumeric486(), KviIrcServerParser::parseNumeric728(), KviIrcServerParser::parseNumeric729(), KviIrcServerParser::parseNumericSaslLogin(), and system_kvs_fnc_osversion().