KVIrc: KviMircCntrl Namespace Reference
KviMircCntrl Namespace Reference
Enumerations
enum Color {
White = 0, Black = 1, DarkBlue = 2, DarkGreen = 3,
Red = 4, DarkRed = 5, DarkViolet = 6, Orange = 7,
Yellow = 8, LightGreen = 9, BlueMarine = 10, LightBlue = 11,
Blue = 12, LightViolet = 13, DarkGray = 14, LightGray = 15,
Transparent = 100, NoChange = 101
}
Contains mIRC color codes.
enum Control {
CTCP = 0x01, Bold = 0x02, Color = 0x03, Escape = 0x04,
UnEscape = 0x05, UnIcon = 0x06, Reset = 0x0f, Reverse = 0x16,
Icon = 0x1d, CryptEscape = 0x1e, Underline = 0x1f
}
Contains mIRC control codes.
Functions
QString stripControlBytes (const QString &szData)
Removes control bytes from the given string.
Enumeration Type Documentation
enum KviMircCntrl::Color
Contains mIRC color codes.
Enumerator:
White
White
Black
Black
DarkBlue
Dark blue
DarkGreen
Dark green
Red
Red
DarkRed
Dark red
DarkViolet
Dark violet
Orange
Orange
Yellow
Yellow
LightGreen
Light green
BlueMarine
Blue marine
LightBlue
Light blue
Blue
Blue
LightViolet
Light violet
DarkGray
Dark gray
LightGray
Light gray
Transparent
Transparent, non standard color code for KviIrcView
NoChange
No change, non standard color code for KviIrcView
enum KviMircCntrl::Control
Contains mIRC control codes.
Enumerator:
CTCP
CTCP, IRC control code
Bold
Bold
Color
Color
Escape
Escape, totally artificial and internal to KviIrcView
UnEscape
Unescape, totally artificial and internal to KviIrcView
UnIcon
Unicon, totally artificial and internal to KviIrcView
Reset
Reset
Reverse
Reverse
Icon
Icon, KVIrc control code
CryptEscape
Crypt escape, KVIrc control code
Underline
Underline
Function Documentation
KVILIB_API QString KviMircCntrl::stripControlBytes (const QString & szData)
Removes control bytes from the given string.
Parameters:
szData The stringe to clean
Returns:
QString
References Bold, CryptEscape, CTCP, getUnicodeColorBytes(), i, Icon, l, Reset, Reverse, and Underline.
Referenced by KviConsoleWindow::applyHighlighting(), KviIrcView::doLinkToolTip(), KviQueryWindow::getInfoLabelText(), KviQueryWindow::getInfoLabelTipText(), KviConsoleWindow::getUserTipText(), KviApplication::notifierMessage(), ChannelTreeWidgetItem::operator<(), KviConsoleWindow::outputPrivmsg(), DccVideoWindow::ownAction(), DccChatWindow::ownAction(), KviQueryWindow::ownAction(), KviChannelWindow::ownAction(), KviIrcServerParser::parseCtcpRequestAction(), KviWindow::preprocessMessage(), KviChannelWindow::preprocessMessage(), ChannelTreeWidgetItemDelegate::sizeHint(), KviTopicListBoxItemDelegate::sizeHint(), str_kvs_fnc_stripcolors(), and KviTopicListBoxItem::width().