KVIrc: KviQString Namespace Reference
KviQString Namespace Reference
A namespace for QString helper functions.
Enumerations
enum EscapeKvsFlags { EscapeSpace = 0x1, PermitVariables = 0x2, PermitFunctions = 0x4, PermitMultiLine = 0x8 }
Functions
void appendFormatted (QString &szSrc, const QString &szFmt,...)
Appends a formatted string.
void appendNumber (QString &szSrc, int iInteger)
Appends the given number to the source string.
void appendNumber (QString &szSrc, double dReal)
Appends the given number to the source string.
void appendNumber (QString &szSrc, kvi_u64_t uInteger)
Appends the given number to the source string.
void appendNumber (QString &szSrc, unsigned int uInteger)
Appends the given number to the source string.
void appendNumber (QString &szSrc, kvi_i64_t iInteger)
Appends the given number to the source string.
void bufferToHex (QString &szRetBuffer, const unsigned char *pcBuffer, unsigned int uLen)
Returns an hexadecimal converted string starting from a buffer.
int cmpCI (const QString &sz1, const QString &sz2, bool bNonAlphaGreater=false)
Compares two strings with case insensitive.
int cmpCIN (const QString &sz1, const QString &sz2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
int cmpCS (const QString &sz1, const QString &sz2)
Compares two strings with case sensitive.
void cutFromFirst (QString &szSrc, const QChar &c, bool bIncluded=true)
Cuts the string after the first occurrence of the given char.
void cutFromFirst (QString &szSrc, const QString &szFind, bool bIncluded=true)
Cuts the string after the first occurrence of the given char.
void cutFromLast (QString &szSrc, const QChar &c, bool bIncluded=true)
Cuts the string after the last occurrence of the given char.
void cutFromLast (QString &szSrc, const QString &szFind, bool bIncluded=true)
Cuts the string after the last occurrence of the given char.
void cutToFirst (QString &szSrc, const QChar &c, bool bIncluded=true, bool bClearIfNotFound=false)
Cuts the string until the first occurrence of the given char is found.
void cutToFirst (QString &szSrc, const QString &szFind, bool bIncluded=true, bool bClearIfNotFound=false)
Cuts the string until the first occurrence of the given char is found.
void cutToLast (QString &szSrc, const QChar &c, bool bIncluded=true, bool bClearIfNotFound=false)
Cuts the string until the last occurrence of the given char is found.
void cutToLast (QString &szSrc, const QString &szFind, bool bIncluded=true, bool bClearIfNotFound=false)
Cuts the string until the last occurrence of the given char is found.
void detach (QString &szSrc)
Resets the size of the string.
void ensureLastCharIs (QString &szSrc, const QChar &c)
Ensures the last char of a string is the given char.
bool equalCI (const QString &sz1, const char *pc2)
Compares two strings with case insensitive.
bool equalCI (const QString &sz1, const QChar *pC2)
Compares two strings with case insensitive.
bool equalCI (const QString &sz1, const QString &sz2)
Compares two strings with case insensitive.
bool equalCI (const char *pc1, const QString &sz2)
Compares two strings with case insensitive.
bool equalCI (const QChar *pC1, const QString &sz2)
Compares two strings with case insensitive.
bool equalCIN (const QString &sz1, const QString &sz2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
bool equalCIN (const QString &sz1, const char *pc2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
bool equalCIN (const QString &sz1, const QChar *pC2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
bool equalCIN (const char *pc1, const QString &sz2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
bool equalCIN (const QChar *pC1, const QString &sz2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
bool equalCS (const QString &sz1, const char *pc2)
Compares two strings with case sensitive.
bool equalCS (const char *pc1, const QString &sz2)
Compares two strings with case sensitive.
bool equalCS (const QString &sz1, const QString &sz2)
Compares two strings with case sensitive.
bool equalCSN (const QString &sz1, const QString &sz2, unsigned int uLen)
Compares two strings with case sensitive up to N chars.
bool equalCSN (const char *pc1, const QString &sz2, unsigned int uLen)
Compares two strings with case sensitive up to N chars.
bool equalCSN (const QString &sz1, const char *pc2, unsigned int uLen)
Compares two strings with case sensitive up to N chars.
void escapeKvs (QString *szData, uint uFlags=0)
Escapes any kvs special character from a string.
int find (const QString &szSrc, const char *pcStr, int iIndex=0, bool bCs=true)
Returns the index position of the last occurrence of the string.
int find (const QString &szSrc, QChar c, int iIndex=0, bool bCs=true)
Returns the index position of the last occurrence of the character.
int find (const QString &szSrc, char c, int iIndex=0, bool bCs=true)
Returns the index position of the last occurrence of the character.
int find (const QString &szSrc, const QString &szStr, int iIndex=0, bool bCs=true)
Returns the index position of the last occurrence of the string.
int find (const QString &szSrc, const QRegExp &rx, int iIndex=0)
Returns the index position of the last occurrence of the string.
int findRev (const QString &szSrc, const char *pcStr, int iIndex=-1, bool bCs=true)
Returns the index position of the last occurrence of the given string.
int findRev (const QString &szSrc, QChar c, int iIndex=-1, bool bCs=true)
Returns the index position of the last occurrence of the character.
int findRev (const QString &szSrc, const QRegExp &rx, int iIndex=-1)
Returns the index position of the last match of the regexp.
int findRev (const QString &szSrc, char c, int iIndex=-1, bool bCs=true)
Returns the index position of the last occurrence of the character.
int findRev (const QString &szSrc, const QString &szStr, int iIndex=-1, bool bCs=true)
Returns the index position of the last occurrence of the given string.
QString getToken (QString &szSrc, const QChar &sep)
Returns a token from a string.
bool lastCharIs (QString &szSrc, const QChar &c)
Returns true if the string ends with the given character.
QString leftToFirst (QString &szSrc, const QChar &c, bool bIncluded=true, bool bReturnFullStringIfNotFound=true)
Returns the string up to the the first occurrence of the given char.
QString leftToFirst (QString &szSrc, const QString &szFind, bool bIncluded=true, bool bReturnFullStringIfNotFound=true)
Returns the string up to the first occurrence of the given string.
QString leftToLast (QString &szSrc, const QChar &c, bool bIncluded=true, bool bReturnFullStringIfNotFound=true)
Returns the string up to the last occurrence of the given char.
QString leftToLast (QString &szSrc, const QString &szFind, bool bIncluded=true, bool bReturnFullStringIfNotFound=true)
Returns the string up to the last occurrence of the given string.
QString lowerISO88591 (const QString &szSrc)
Returns an ISO-8859-1 lower case string.
QString makeSizeReadable (quint64 size)
Returns a readable size in byte's multiples.
bool matchString (const QString &szExp, const QString &szStr, bool bIsRegExp=false, bool bExact=false, bool bCs=false)
Matches two string containging wildcards (* and ?) or regular expressions.
bool matchWildExpressions (const QString &szM1, const QString &szM2)
Matches two strings containging wildcards (* and ?)
const QChar * nullTerminatedArray (const QString &szSrc)
Returns a pointer to the data stored in the string.
QString & sprintf (QString &szSrc, const QString &szFmt,...)
Writes to the character string.
void stripLeft (QString &szSrc, const QChar &c)
Trims all c chars at the start of the given string.
void stripRight (QString &szSrc, const QChar &c)
Trims all c chars at the end of the given string.
void stripRightWhiteSpace (QString &szSrc)
Trims all the whitespaces at the end of the given string.
kvi_i64_t toI64 (QString &szNumber, bool *bOk)
Return the string converted to a long.
QByteArray toLocal8Bit (const QString &szSrc)
Return the local 8-bit representation of the string.
kvi_u64_t toU64 (QString &szNumber, bool *bOk)
Return the string converted to an unsigned long.
QByteArray toUtf8 (const QString &szSrc)
Return a UTF-8 formatted string.
void transliterate (QString &szSrc, const QString &szToFind, const QString &szReplacement)
Replaces a string with another.
QString trimmed (const QString &szSrc)
Return a whitespace-trimmed string.
QString upperISO88591 (const QString &szSrc)
Returns an ISO-8859-1 upper case string.
void vsprintf (QString &szSrc, const QString &szFmt, kvi_va_list list)
Writes to the character string.
Variables
static char cHexDigits [16] = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' }
const QString Empty
A global empty string (note that this is ALSO NULL under Qt 3.x)
Detailed Description
A namespace for QString helper functions.
This namespace contains several helper functions that are used when dealing with QString.
Enumeration Type Documentation
enum KviQString::EscapeKvsFlags
Enumerator:
EscapeSpace
PermitVariables
PermitFunctions
PermitMultiLine
Function Documentation
KVILIB_API void KviQString::appendFormatted (QString & szSrc, const QString & szFmt, ...)
Appends a formatted string.
Parameters:
szSrc The source string
szFmt The format string
... Format string parameters
Returns:
void
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, and vsprintf().
Referenced by KviKvsTreeNodeSingleParameterIdentifier::contextDescription(), KviKvsTreeNodeMultipleParameterIdentifier::contextDescription(), KviIrcView::doLinkToolTip(), KviIrcContextDisplay::drawContents(), KviKvsPopupMenu::generateDefPopupCore(), KviIrcConnection::getCommonChannels(), KviApp::getGlobalKvircDirectory(), KviApp::getTmpFileName(), KviKvsParameterProcessor::handleParameterTypeError(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviModuleManager::loadModule(), KviConsole::outputPrivmsg(), parseArgs(), KviServerParser::parseCtcpReplyAvatar(), KviServerParser::parseNumericWhoisChannels(), KviStupidNotifyListManager::sendIsOn(), KviWatchNotifyListManager::start(), KviIrcContextDisplay::tipRequest(), KviStatusBarLagIndicator::tipText(), and KviChannel::updateModeLabel().
KVILIB_API void KviQString::appendNumber (QString & szSrc, int iInteger)
Appends the given number to the source string.
Parameters:
szSrc The source string
iInteger Number in int format
Returns:
void
References sprintf().
KVILIB_API void KviQString::appendNumber (QString & szSrc, double dReal)
Appends the given number to the source string.
Parameters:
szSrc The source string
dReal Number in double format
Returns:
void
References sprintf().
Referenced by KviKvsVariant::appendAsString().
KVILIB_API void KviQString::appendNumber (QString & szSrc, kvi_u64_t uInteger)
Appends the given number to the source string.
Parameters:
szSrc The source string
uInteger Number in kvi_i64_t format
Returns:
void
References sprintf().
KVILIB_API void KviQString::appendNumber (QString & szSrc, unsigned int uInteger)
Appends the given number to the source string.
Parameters:
szSrc The source string
uInteger Number in unsigned int format
Returns:
void
References sprintf().
KVILIB_API void KviQString::appendNumber (QString & szSrc, kvi_i64_t iInteger)
Appends the given number to the source string.
Parameters:
szSrc The source string
iInteger Number in kvi_i64_t format
Returns:
void
References sprintf().
KVILIB_API void KviQString::bufferToHex (QString & szRetBuffer, const unsigned char * pcBuffer, unsigned int uLen)
Returns an hexadecimal converted string starting from a buffer.
Parameters:
szRetBuffer The buffer to hold the hexadecimal string
pcBuffer The buffer containing the string to convert
uLen The max length of the original string
References cHexDigits.
KVILIB_API int KviQString::cmpCI (const QString & sz1, const QString & sz2, bool bNonAlphaGreater = false)
Compares two strings with case insensitive.
Note that greater here means that come AFTER in the alphabetic order return < 0 ---> str1 < str2 return = 0 ---> str1 = str2 return > 0 ---> str1 > str2
Parameters:
sz1 The first string
sz2 The second string
bNonAlphaGreater Wheter to check if strings are not alphabetics
Returns:
int
Referenced by KviKvsVariant::compare(), KviKvsVariantComparison::compareIntString(), KviKvsVariantComparison::compareRealString(), KviClassicWindowList::insertButton(), and KviUserListView::insertUserEntry().
KVILIB_API int KviQString::cmpCIN (const QString & sz1, const QString & sz2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
Note that greater here means that come AFTER in the alphabetic order return < 0 ---> str1 < str2 return = 0 ---> str1 = str2 return > 0 ---> str1 > str2
Parameters:
sz1 The first string
sz2 The second string
uLen The number of chars to check
Returns:
int
References MY_MIN.
Referenced by KviUserListView::completeNickStandard().
KVILIB_API int KviQString::cmpCS (const QString & sz1, const QString & sz2)
Compares two strings with case sensitive.
Note that greater here means that come AFTER in the alphabetic order return < 0 ---> str1 < str2 return = 0 ---> str1 = str2 return > 0 ---> str1 > str2
Parameters:
sz1 The first string
sz2 The second string
Returns:
int
KVILIB_API void KviQString::cutFromFirst (QString & szSrc, const QChar & c, bool bIncluded = true)
Cuts the string after the first occurrence of the given char.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
c The char to search for
bIncluded Wheter to include the given char
Returns:
void
Referenced by KviWindow::systemTextEncodingPopupSmartActivated(), KviWindow::systemTextEncodingPopupSmartUtf8Activated(), and KviWindow::systemTextEncodingPopupStandardActivated().
KVILIB_API void KviQString::cutFromFirst (QString & szSrc, const QString & szFind, bool bIncluded = true)
Cuts the string after the first occurrence of the given char.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
szFind The string to search for
bIncluded Wheter to include the given string
Returns:
void
KVILIB_API void KviQString::cutFromLast (QString & szSrc, const QChar & c, bool bIncluded = true)
Cuts the string after the last occurrence of the given char.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
c The char to search for
bIncluded Wheter to include the given char
Returns:
void
Referenced by KviApp::completeDirectory(), KviModuleManager::completeModuleNames(), and KviConsole::completeServer().
KVILIB_API void KviQString::cutFromLast (QString & szSrc, const QString & szFind, bool bIncluded = true)
Cuts the string after the last occurrence of the given char.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
szFind The string to search for
bIncluded Wheter to include the given string
Returns:
void
KVILIB_API void KviQString::cutToFirst (QString & szSrc, const QChar & c, bool bIncluded = true, bool bClearIfNotFound = false)
Cuts the string until the first occurrence of the given char is found.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
c The char to search for
bIncluded Wheter to include the given char in the cut
bClearIfNotFound Wheter to cut the whole string if the char is not found
Returns:
void
Referenced by KviModuleManager::completeModuleNames(), KviConsole::completeServer(), and KviApp::mapImageFile().
KVILIB_API void KviQString::cutToFirst (QString & szSrc, const QString & szFind, bool bIncluded = true, bool bClearIfNotFound = false)
Cuts the string until the first occurrence of the given char is found.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
szFind The string to search for
bIncluded Wheter to include the given string in the cut
bClearIfNotFound Wheter to cut the whole string if the string is not found
Returns:
void
KVILIB_API void KviQString::cutToLast (QString & szSrc, const QChar & c, bool bIncluded = true, bool bClearIfNotFound = false)
Cuts the string until the last occurrence of the given char is found.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
c The char to search for
bIncluded Wheter to include the given char in the cut
bClearIfNotFound Wheter to cut the whole string if the char is not found
Returns:
void
Referenced by KviApp::completeDirectory(), KviModuleManager::completeModuleNames(), KviRegisteredChannelDataBase::load(), KviModuleManager::loadModulesByCaps(), and KviServerParser::parseCtcpReplyAvatar().
KVILIB_API void KviQString::cutToLast (QString & szSrc, const QString & szFind, bool bIncluded = true, bool bClearIfNotFound = false)
Cuts the string until the last occurrence of the given char is found.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
szFind The string to search for
bIncluded Wheter to include the given string in the cut
bClearIfNotFound Wheter to cut the whole string if the string is not found
Returns:
void
KVILIB_API void KviQString::detach (QString & szSrc)
Resets the size of the string.
Parameters:
szSrc The source string
Returns:
void
Referenced by KviKvsScript::detach().
KVILIB_API void KviQString::ensureLastCharIs (QString & szSrc, const QChar & c)
Ensures the last char of a string is the given char.
If the string does not end with the given char, it appends it
Parameters:
szSrc The source string
c The char to check
Returns:
void
References lastCharIs().
Referenced by KviPackageWriter::addDirectory(), KviApp::completeDirectory(), KviApp::findAudioFile(), KviLocale::findCatalogue(), KviApp::findImage(), KviApp::findImageInImageSearchPath(), KviApp::findSmallIcon(), KviApp::getGlobalKvircDirectory(), KviApp::getLocalKvircDirectory(), KviApp::getTmpFileName(), KviSplashScreen::KviSplashScreen(), KviKvsCoreSimpleCommands::KVSCSC(), KviThemeInfo::largeScreenshot(), KviTheme::load(), KviApp::mapImageFile(), KviThemeInfo::mediumScreenshot(), KviTheme::saveScreenshots(), KviApp::setupBegin(), KviThemeInfo::smallScreenshot(), KviThemeInfo::smallScreenshotPath(), KviPackageReader::unpackFile(), and KviFileUtils::writeFile().
KVILIB_API bool KviQString::equalCI (const QString & sz1, const char * pc2)
Compares two strings with case insensitive.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
pc2 Second string
Returns:
bool
KVILIB_API bool KviQString::equalCI (const QString & sz1, const QChar * pC2)
Compares two strings with case insensitive.
It returns true if the strings are equal, false otherwise. The parameter pC2 is assumed to be null terminated here!
Parameters:
sz1 First string
pC2 Second string
Returns:
bool
KVILIB_API bool KviQString::equalCI (const QString & sz1, const QString & sz2)
Compares two strings with case insensitive.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
sz2 Second string
Returns:
bool
Referenced by KviConsole::avatarChanged(), KviUserListView::completeNickStandard(), KviInputEditor::completion(), KviIrcLink::createSocket(), KviWindow::createSystemTextEncodingPopup(), KviKvsObject::disconnectSignal(), equalCI(), KviKvsTreeNodeSpecialCommandClass::execute(), KviKvsEventManager::findAppEventByName(), KviKvsEventManager::findAppEventIndexByName(), KviIrcConnection::findChannel(), KviKvsObject::findChild(), KviKvsPopupMenu::findChildPopupByName(), KviApp::findConsole(), KviIrcContext::findDeadChannel(), KviIrcContext::findDeadQuery(), KviRegisteredChannelDataBase::findExact(), KviMenuBar::findMenu(), KviIrcConnection::findQuery(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), KviNetwork::findServer(), KviApp::findWindowByCaption(), KviStringConversion::fromString(), KviRegisteredUser::getBoolProperty(), KviKvsObject::getClass(), KviIsOnNotifyListManager::handleIsOn(), KviIsOnNotifyListManager::handleUserhost(), KviChannel::internalMask(), kvi_hash_key_equal(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviUserIdentityManager::load(), KviRegisteredUserDataBase::load(), KviIrcConnectionAsyncTemplateData< KviAsyncWhoisInfo >::lookup(), KviServerDataBase::makeCurrentBestServerInNetwork(), KviServerDataBase::makeCurrentServer(), KviIrcView::mouseDoubleClickEvent(), KviIrcView::mouseRealPressEvent(), KviPixmap::operator=(), KviIrcMask::operator==(), parseArgs(), KviKvsParser::parseCommand(), KviServerParser::parseCtcpReply(), KviServerParser::parseCtcpRequest(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralQuit(), KviUserListView::partAllButOne(), KviKvsPopupMenu::removeItemByName(), KviMaskEditor::removeMask(), KviKvsEventManager::removeScriptAppHandler(), KviKvsEventManager::removeScriptRawHandler(), KviSharedFilesManager::removeSharedFile(), KviWindow::saveProperties(), KviWindow::savePropertiesAsDefault(), KviIrcConnectionTargetResolver::serverLookupTerminated(), KviConsole::setAvatar(), KviApp::setOptionValue(), KviHttpRequest::start(), and KviUserListView::userActionVerifyMask().
bool KviQString::equalCI (const char * pc1, const QString & sz2) [inline]
Compares two strings with case insensitive.
It returns true if the strings are equal, false otherwise.
Parameters:
pc1 First string
sz2 Second string
Returns:
bool
References equalCI().
bool KviQString::equalCI (const QChar * pC1, const QString & sz2) [inline]
Compares two strings with case insensitive.
It returns true if the strings are equal, false otherwise. The parameter pC1 is assumed to be null terminated here!
Parameters:
pC1 First string
sz2 Second string
Returns:
bool
References equalCI().
KVILIB_API bool KviQString::equalCIN (const QString & sz1, const QString & sz2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
sz2 Second string
uLen The length of the string to check
Returns:
bool
References MY_MIN.
Referenced by KviConsole::completeChannel(), KviKvsAliasManager::completeCommand(), KviApp::completeDirectory(), KviKvsKernel::completeFunction(), KviModuleManager::completeModuleNames(), KviUserListView::completeNickBashLike(), KviConsole::completeServer(), KviInputEditor::completion(), equalCIN(), KviApp::fileDownloadTerminated(), KviIconManager::getAvatar(), KviAvatar::KviAvatar(), KviKvsCoreSimpleCommands::KVSCSC(), KviServerDataBase::makeCurrentServer(), KviServerParser::parseCtcpReplyAvatar(), KviApp::setOptionValue(), KviIrcUrl::split(), KviKvsVariant::unserializeBool(), and KviKvsVariant::unserializeNull().
KVILIB_API bool KviQString::equalCIN (const QString & sz1, const char * pc2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
pc2 Second string
uLen The length of the string to check
Returns:
bool
KVILIB_API bool KviQString::equalCIN (const QString & sz1, const QChar * pC2, unsigned int uLen)
Compares two strings with case insensitive up to N chars.
It returns true if the strings are equal, false otherwise pC2 is assumed to be null terminated here!
Parameters:
sz1 First string
pC2 Second string
uLen The length of the string to check
Returns:
bool
bool KviQString::equalCIN (const char * pc1, const QString & sz2, unsigned int uLen) [inline]
Compares two strings with case insensitive up to N chars.
It returns true if the strings are equal, false otherwise
Parameters:
pc1 First string
sz2 Second string
uLen The length of the string to check
Returns:
bool
References equalCIN().
bool KviQString::equalCIN (const QChar * pC1, const QString & sz2, unsigned int uLen) [inline]
Compares two strings with case insensitive up to N chars.
It returns true if the strings are equal, false otherwise pC1 is assumed to be null terminated here!
Parameters:
pC1 First string
sz2 Second string
uLen The length of the string to check
Returns:
bool
References equalCIN().
KVILIB_API bool KviQString::equalCS (const QString & sz1, const char * pc2)
Compares two strings with case sensitive.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
pc2 Second string
Returns:
bool
bool KviQString::equalCS (const char * pc1, const QString & sz2) [inline]
Compares two strings with case sensitive.
It returns true if the strings are equal, false otherwise
Parameters:
pc1 First string
sz2 Second string
Returns:
bool
References equalCS().
KVILIB_API bool KviQString::equalCS (const QString & sz1, const QString & sz2)
Compares two strings with case sensitive.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
sz2 Second string
Returns:
bool
Referenced by KviPackageWriter::addDirectory(), KviApp::completeDirectory(), equalCS(), KviApp::fillRecentNicknamesPopup(), KviStringConversion::fromString(), KviRegisteredUser::getBoolProperty(), kvi_hash_key_equal(), KviSharedFilesManager::lookupSharedFile(), KviServerParser::parseCtcpReplyUserinfo(), KviServerParser::parseNumericWhoisUser(), KviUserListView::userAction(), KviUserListView::userActionVerifyMask(), and KviIrcConnection::userInfoReceived().
KVILIB_API bool KviQString::equalCSN (const QString & sz1, const QString & sz2, unsigned int uLen)
Compares two strings with case sensitive up to N chars.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
sz2 Second string
uLen The length of the string to check
Returns:
bool
References MY_MIN.
Referenced by KviApp::completeDirectory(), equalCSN(), and KviRegisteredUserDataBase::load().
bool KviQString::equalCSN (const char * pc1, const QString & sz2, unsigned int uLen) [inline]
Compares two strings with case sensitive up to N chars.
It returns true if the strings are equal, false otherwise
Parameters:
pc1 First string
sz2 Second string
uLen The length of the string to check
Returns:
bool
References equalCSN().
KVILIB_API bool KviQString::equalCSN (const QString & sz1, const char * pc2, unsigned int uLen)
Compares two strings with case sensitive up to N chars.
It returns true if the strings are equal, false otherwise
Parameters:
sz1 First string
pc2 Second string
uLen The length of the string to check
Returns:
bool
KVILIB_API void KviQString::escapeKvs (QString * szData, uint uFlags = 0)
Escapes any kvs special character from a string.
Parameters:
szData The string to escape
Returns:
void
References EscapeSpace, PermitFunctions, PermitMultiLine, and PermitVariables.
Referenced by KviChannel::closeEvent(), KviInputEditor::completionEscapeUnsafeToken(), KviInputEditor::dropEvent(), KviKvsVariant::KviKvsVariant(), KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), KviServerParser::parseCtcpReplyAvatar(), KviInputEditor::pasteFile(), KviChangeUserModeAction::popupActivated(), KviIrcContext::terminateConnectionRequest(), and KviIrcConnection::useRealName().
int KviQString::find (const QString & szSrc, const char * pcStr, int iIndex = 0, bool bCs = true) [inline]
Returns the index position of the last occurrence of the string.
The search is made forward starting from index.
Parameters:
szSrc The source string
pcStr The string to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
int KviQString::find (const QString & szSrc, QChar c, int iIndex = 0, bool bCs = true) [inline]
Returns the index position of the last occurrence of the character.
The search is made forward starting from index.
Parameters:
szSrc The source string
c The character to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
Referenced by KviStringConversion::decodePath(), KviStringConversion::encodePath(), and parseMircServerRecord().
int KviQString::find (const QString & szSrc, char c, int iIndex = 0, bool bCs = true) [inline]
Returns the index position of the last occurrence of the character.
The search is made forward starting from index.
Parameters:
szSrc The source string
c The character to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
int KviQString::find (const QString & szSrc, const QString & szStr, int iIndex = 0, bool bCs = true) [inline]
Returns the index position of the last occurrence of the string.
The search is made forward starting from index.
Parameters:
szSrc The source string
szStr The string to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
int KviQString::find (const QString & szSrc, const QRegExp & rx, int iIndex = 0) [inline]
Returns the index position of the last occurrence of the string.
The search is made forward starting from index.
Parameters:
szSrc The source string
rx The regexp to match
iIndex The index to start from
Returns:
int
int KviQString::findRev (const QString & szSrc, const char * pcStr, int iIndex = -1, bool bCs = true) [inline]
Returns the index position of the last occurrence of the given string.
The search is made backward. If index is -1 the search starts at the last character.
Parameters:
szSrc The source string
pcStr The string to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
int KviQString::findRev (const QString & szSrc, QChar c, int iIndex = -1, bool bCs = true) [inline]
Returns the index position of the last occurrence of the character.
The search is made backward. If index is -1 the search starts at the last character.
Parameters:
szSrc The source string
c The character to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
Referenced by KviPackageReader::unpackFile().
int KviQString::findRev (const QString & szSrc, const QRegExp & rx, int iIndex = -1) [inline]
Returns the index position of the last match of the regexp.
The search is made backward. If index is -1 the search starts at the last character.
Parameters:
szSrc The source string
rx The regexp to match
iIndex The index to start from
Returns:
int
int KviQString::findRev (const QString & szSrc, char c, int iIndex = -1, bool bCs = true) [inline]
Returns the index position of the last occurrence of the character.
The search is made backward. If index is -1 the search starts at the last character.
Parameters:
szSrc The source string
c The character to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
int KviQString::findRev (const QString & szSrc, const QString & szStr, int iIndex = -1, bool bCs = true) [inline]
Returns the index position of the last occurrence of the given string.
The search is made backward. If index is -1 the search starts at the last character.
Parameters:
szSrc The source string
szStr The string to find
iIndex The index to start from
bCs Case sensitive search
Returns:
int
KVILIB_API QString KviQString::getToken (QString & szSrc, const QChar & sep)
Returns a token from a string.
Parameters:
szSrc The source string
sep The token to find
Returns:
QString
Referenced by KviFileUtils::makeDir().
bool KviQString::lastCharIs (QString & szSrc, const QChar & c) [inline]
Returns true if the string ends with the given character.
Parameters:
szSrc The source string
c The char to check
Returns:
bool
Referenced by KviStr::ensureLastCharIs(), and ensureLastCharIs().
KVILIB_API QString KviQString::leftToFirst (QString & szSrc, const QChar & c, bool bIncluded = true, bool bReturnFullStringIfNotFound = true)
Returns the string up to the the first occurrence of the given char.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
c The char to search for
bIncluded Wheter to include the given char in the returned string
bReturnFullStringIfNotFound True if we want the function to return the whole string if the char isn't found and false if we want the function to return an empty string in this case.
Returns:
void
KVILIB_API QString KviQString::leftToFirst (QString & szSrc, const QString & szFind, bool bIncluded = true, bool bReturnFullStringIfNotFound = true)
Returns the string up to the first occurrence of the given string.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
szFind The string to search for
bIncluded Wheter to include the given string in the returned string
bReturnFullStringIfNotFound True if we want the function to return the whole string if the string isn't found and false if we want the function to return an empty string in this case.
Returns:
void
KVILIB_API QString KviQString::leftToLast (QString & szSrc, const QChar & c, bool bIncluded = true, bool bReturnFullStringIfNotFound = true)
Returns the string up to the last occurrence of the given char.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
c The char to search for
bIncluded Wheter to include the given char in the returned string
bReturnFullStringIfNotFound True if we want the function to return the whole string if the char isn't found and false if we want the function to return an empty string in this case.
Returns:
void
Referenced by KviRegisteredChannelDataBase::load().
KVILIB_API QString KviQString::leftToLast (QString & szSrc, const QString & szFind, bool bIncluded = true, bool bReturnFullStringIfNotFound = true)
Returns the string up to the last occurrence of the given string.
If the char is not found, the string is returned as it is.
Parameters:
szSrc The source string
szFind The string to search for
bIncluded Wheter to include the given string in the returned string
bReturnFullStringIfNotFound True if we want the function to return the whole string if the string isn't found and false if we want the function to return an empty string in this case.
Returns:
void
KVILIB_API QString KviQString::lowerISO88591 (const QString & szSrc)
Returns an ISO-8859-1 lower case string.
Parameters:
szSrc The source string
Returns:
QString
References iso88591_toLower_map, kvi_free, kvi_malloc, and nullTerminatedArray().
KVILIB_API QString KviQString::makeSizeReadable (quint64 size)
Returns a readable size in byte's multiples.
This will return strings like KiB, MiB, GiB, TiB and so on
Parameters:
size The size of the file
Returns:
QString
References __tr2qs.
KVILIB_API bool KviQString::matchString (const QString & szExp, const QString & szStr, bool bIsRegExp = false, bool bExact = false, bool bCs = false)
Matches two string containging wildcards (* and ?) or regular expressions.
Parameters:
szExp The regular expression to match
szStr The source string
bIsRegExp Wheter to use a wildcard or regexp matching
bExact Wheter to match the whole string
bCs Wheter to match with case sensitive
Returns:
bool
Referenced by KviIdentityProfileSet::findName(), KviIdentityProfileSet::findNetwork(), KviIrcMask::matchesFixed(), and KviNickServRuleSet::matchRule().
KVILIB_API bool KviQString::matchWildExpressions (const QString & szM1, const QString & szM2)
Matches two strings containging wildcards (* and ?)
Parameters:
szM1 The first string to match
szM2 The second string to match
Returns:
bool
Referenced by KviRegisteredChannelDataBase::find(), and KviIrcMask::matches().
KVILIB_API const QChar * KviQString::nullTerminatedArray (const QString & szSrc)
Returns a pointer to the data stored in the string.
This makes the string szSrc appear as a null terminated array. It MAY RETURN 0 when the string is null!
Parameters:
szSrc The source string
Returns:
QChar *
Referenced by KviIrcConnectionServerInfo::buildModePrefixTable(), KviInputEditor::completion(), KviKvsScript::detach(), KviKvsTreeNodeOperationStringSubstitution::execute(), KviIrcMask::getHostDomainMask(), KviIrcMask::hasNumericHost(), KviIrcMask::hasWildNick(), kvi_hash_hash(), KviIrcMask::KviIrcMask(), KviKvsScript::KviKvsScript(), lowerISO88591(), KviIrcMask::nonWildChars(), KviWindow::output(), KviChannel::outputMessage(), KviWindow::outputNoFmt(), KviServerParser::parseLiteralJoin(), upperISO88591(), and vsprintf().
KVILIB_API QString & KviQString::sprintf (QString & szSrc, const QString & szFmt, ...)
Writes to the character string.
Parameters:
szSrc The source string
szFmt The format string
... The list of format parameters
Returns:
QString
References kvi_va_end, kvi_va_list, kvi_va_start_by_reference, and vsprintf().
Referenced by KviKvsPopupMenu::addEpilogue(), KviKvsPopupMenu::addExtPopup(), KviKvsPopupMenu::addItem(), KviKvsPopupMenu::addLabel(), KviKvsPopupMenu::addPopup(), KviKvsPopupMenu::addPrologue(), KviKvsPopupMenu::addSeparator(), appendNumber(), KviConsole::applyOptions(), KviFileDialog::askForSaveFileName(), KviKvsVariant::asString(), KviUserListView::completeNickBashLike(), KviIrcContext::connectionFailed(), KviKvsTreeNodeSpecialCommandClassFunctionDefinition::contextDescription(), KviKvsTreeNodeCoreSimpleCommand::contextDescription(), KviKvsTreeNodeCoreFunctionCall::contextDescription(), KviKvsTreeNodeCoreCallbackCommand::contextDescription(), KviKvsTreeNodeCommandWithParameters::contextDescription(), KviKvsTreeNodeCommand::contextDescription(), KviKvsTreeNodeCallbackCommand::contextDescription(), KviKvsTreeNodeBaseObjectFunctionCall::contextDescription(), KviKvsTreeNodeAliasSimpleCommand::contextDescription(), KviKvsTreeNodeAliasFunctionCall::contextDescription(), KviStatusBar::contextPopupAboutToShow(), KviWindow::createSystemTextEncodingPopup(), KviHttpRequest::dnsLookupDone(), KviIrcView::doLinkToolTip(), KviKvsPopupMenuItemExtMenu::fill(), KviLocale::findCatalogue(), KviKvsReport::findLineColAndListing(), KviIrcView::findNext(), KviIrcView::findPrev(), KviNetUtils::formatNetworkBandwidthString(), KviTimeUtils::formatTimeInterval(), KviKvsObject::function_listProperties(), KviKvsPopupMenu::generateDefPopup(), KviServer::generateUniqueId(), KviApp::getChannelDumpLogFileName(), KviWindow::getDefaultLogFileName(), KviKvsParameterProcessor::handleParameterTypeError(), KviHttpRequest::haveServerIp(), KviImageDialog::heartbeat(), KviServerDataBase::importFromMircIni(), KviModeEditor::KviModeEditor(), KviKvsCoreCallbackCommands::KVSCCC(), KviKvsCoreFunctions::KVSCF(), KviKvsPopupMenu::load(), KviThemeInfo::load(), KviNickServRule::load(), KviNickServRuleSet::load(), KviServerDataBase::load(), KviServer::load(), KviIdentityProfileSet::load(), KviIdentityProfile::load(), KviSharedFilesManager::load(), KviKvsEventManager::loadAppEvents(), KviNickServRuleSet::loadPrivate(), KviIdentityProfileSet::loadPrivate(), KviKvsEventManager::loadRawEvents(), KviIconManager::loadSmallIcon(), KviServerDataBase::makeCurrentBestServerInNetwork(), KviIrcView::mouseDoubleClickEvent(), KviActionManager::nameForAutomaticAction(), KviNotifyListManager::notifyOffLine(), KviNotifyListManager::notifyOnLine(), KviHttpRequest::openFile(), KviConsole::outputPrivmsg(), KviPackageWriter::packFile(), KviServerParser::parseChannelMode(), KviServerParser::parseCtcpReplyAvatar(), KviServerParser::parseLiteralNotice(), KviServerParser::parseLiteralPrivmsg(), KviServerParser::parseNumeric004(), KviServerParser::parseNumericBackFromAway(), KviServerParser::parseNumericTopicWhoTime(), KviKvsParameterProcessor::process(), KviKvsRunTimeContext::report(), KviKvsParser::report(), KviKvsPopupMenu::save(), KviKvsObjectClass::save(), KviNickServRule::save(), KviNickServRuleSet::save(), KviServerDataBase::save(), KviServer::save(), KviIdentityProfileSet::save(), KviIdentityProfile::save(), KviSharedFilesManager::save(), KviRegisteredUserDataBase::save(), KviKvsEventManager::saveAppEvents(), KviKvsEventManager::saveRawEvents(), KviIrcSocket::startConnection(), KviHttpRequest::startDnsLookup(), KviStatusBarClock::timerEvent(), KviConsole::triggerOnHighlight(), KviPackageReader::unpackFile(), and KviStatusBarLagIndicator::updateDisplay().
KVILIB_API void KviQString::stripLeft (QString & szSrc, const QChar & c)
Trims all c chars at the start of the given string.
Parameters:
szSrc The source string
c The char to trim
Returns:
void
Referenced by KviFileUtils::makeDir().
KVILIB_API void KviQString::stripRight (QString & szSrc, const QChar & c)
Trims all c chars at the end of the given string.
Parameters:
szSrc The source string
c The char to trim
Returns:
void
References c.
KVILIB_API void KviQString::stripRightWhiteSpace (QString & szSrc)
Trims all the whitespaces at the end of the given string.
Parameters:
szSrc The source string
Returns:
void
kvi_i64_t KviQString::toI64 (QString & szNumber, bool * bOk) [inline]
Return the string converted to a long.
Parameters:
szNumber The source number
bOk The conversion error handling
Returns:
kvi_i64_t
Referenced by KviKvsVariant::asBoolean(), KviKvsVariant::asInteger(), and KviKvsVariant::castToInteger().
QByteArray KviQString::toLocal8Bit (const QString & szSrc) [inline]
Return the local 8-bit representation of the string.
Parameters:
szSrc The source string
Returns:
QByteArray
Referenced by KviApp::checkFileAssociations(), and KviConfig::save().
kvi_u64_t KviQString::toU64 (QString & szNumber, bool * bOk) [inline]
Return the string converted to an unsigned long.
Parameters:
szNumber The source number
bOk The conversion error handling
Returns:
kvi_u64_t
QByteArray KviQString::toUtf8 (const QString & szSrc) [inline]
Return a UTF-8 formatted string.
Parameters:
szSrc The source string
Returns:
QByteArray
Warning:
: DO NOT USE CONSTRUCTS LIKE char * c = KviQString::toUtf8(something).data(); They are dangerous since with many compilers the returned string gets destroyed at the end of the instruction and the c pointer gets thus invalidated. Use QByteArray tmp = KviQString::toUtf8(something); char * c = tmp.data(); instead. Yes, I know that it sucks, but it's the only way to transit to Qt 4.x more or less cleanly...
Referenced by KviIrcView::add2Log(), KviSharedFilesManager::addSharedFile(), KviStr::append(), KviConsole::avatarChanged(), KviWindow::focusInEvent(), KviStringConversion::fromString(), KviLocale::getLoadedCatalogue(), KviIrcConnectionTargetResolver::haveServerIp(), kvi_irc_vsnprintf(), kvi_vsnprintf(), KviStr::KviStr(), KviThreadManager::KviThreadManager(), KviKvsCoreFunctions::KVSCF(), KviMessageCatalogue::load(), KviLocale::loadCatalogue(), KviIrcConnection::loginToIrcServer(), KviFileUtils::makeDir(), KviStr::operator=(), KviPackageWriter::packFile(), KviServerParser::parseCtcpRequest(), KviServerParser::parseNumericServerAdminInfoTitle(), KviServerParser::parseNumericStats(), KviRegisteredUserDataBase::removeUser(), KviDnsThread::run(), KviHttpRequestThread::runInternal(), KviFile::save(), KviConfig::save(), KviIrcView::saveBuffer(), KviNetUtils::stringIpToBinaryIp(), KviStringConversion::toString(), KviLocale::unloadCatalogue(), and KviFileUtils::writeFile().
KVILIB_API void KviQString::transliterate (QString & szSrc, const QString & szToFind, const QString & szReplacement)
Replaces a string with another.
Parameters:
szSrc The source string
szToFind The string to replace
szReplacement The string to replace with
Returns:
void
References MY_MIN.
Referenced by KviKvsTreeNodeOperationStringTransliteration::execute().
QString KviQString::trimmed (const QString & szSrc) [inline]
Return a whitespace-trimmed string.
Spaces are trimmed at start and end of the string
Parameters:
szSrc The source string
Returns:
QString
Referenced by KviNickServRule::load(), KviIdentityProfile::load(), KviIrcConnection::loginToIrcServer(), KviDns::lookup(), KviFileUtils::makeDir(), and KviServerParser::parseLoginNicknameProblem().
KVILIB_API QString KviQString::upperISO88591 (const QString & szSrc)
Returns an ISO-8859-1 upper case string.
Parameters:
szSrc The source string
Returns:
QString
References iso88591_toUpper_map, kvi_free, kvi_malloc, and nullTerminatedArray().
KVILIB_API void KviQString::vsprintf (QString & szSrc, const QString & szFmt, kvi_va_list list)
Writes to the character string.
Parameters:
szSrc The source string
szFmt The format string
list The list of format parameters
Returns:
void
References INCREMENT_MEM, INCREMENT_MEM_BY, kvi_free, kvi_malloc, kvi_va_arg, KviStr::len(), MEMINCREMENT, nullTerminatedArray(), and KviStr::ptr().
Referenced by appendFormatted(), KviMessageBox::information(), KviWindow::output(), KviKvsRunTimeContext::report(), KviKvsParser::report(), sprintf(), KviMessageBox::warning(), and KviMessageBox::yesNo().
Variable Documentation
char KviQString::cHexDigits[16] = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' } [static]
Referenced by bufferToHex().
KVILIB_API const QString KviQString::Empty
A global empty string (note that this is ALSO NULL under Qt 3.x)
Referenced by KviKvsScriptAddon::configureCallbackCode(), KviDns::firstHostname(), KviDns::firstIpAddress(), KviBasicIrcServerInfo::getChannelModeDescription(), KviRegisteredUser::getProperty(), KviBasicIrcServerInfo::getUserModeDescription(), KviKvsScriptAddon::helpCallbackCode(), kvi_hash_key_default(), KviWindow::lastLineOfText(), KviIrcView::lastLineOfText(), KviWindow::lastMessageText(), KviIrcView::lastMessageText(), KviWindow::loadProperties(), KviWindow::localNick(), KviAvatarCache::lookup(), KviWindow::saveProperties(), KviKvsVariant::string(), and KviWindow::target().