KVIrc: KviError Namespace Reference
KviError Namespace Reference
This namespace handle the error codes.
Enumerations
enum Code {
Success = 0, UnknownError = 1, InternalError = 2, UnknownCommand = 3,
MissingClosingBrace = 4, UnexpectedEndInString = 5, UnexpectedEndInDictionaryKey = 6, SwitchDashWithoutSwitchLetter = 7,
UnknownFunction = 8, UnexpectedEndInParenthesis = 9, UnexpectedEndInFunctionParams = 10, MissingVariableName = 11,
VariableOrIdentifierExpected = 12, LeftOperandIsNotANumber = 13, MultipleOpsNotSupportedForOperator = 14, DivisionByZero = 15,
ModuloByZero = 16, RightOperandIsNotANumber = 17, UnterminatedExpression = 18, UnterminatedSubexpression = 19,
UnexpectedCharacter = 20, UnknownOperator = 21, NoHostToResolve = 22, UnsupportedAddressFamily = 23,
ValidNameButNoIpAddress = 24, UnrecoverableNameserverError = 25, DNSTemporaneousFault = 26, DNSInternalErrorBadFlags = 27,
DNSInternalErrorOutOfMemory = 28, DNSInternalErrorServiceNotSupported = 29, DNSNoName = 30, DNSInternalErrorUnsupportedSocketType = 31,
DNSQueryFailed = 32, NoIPv6Support = 33, HostNotFound = 34, DNSInternalIPCFailure = 35,
AnotherConnectionInProgress = 36, InvalidIpAddress = 37, SocketCreationFailed = 38, AsyncSocketFailed = 39,
BadFileDescriptor = 40, OutOfAddressSpace = 41, ConnectionRefused = 42, KernelNetworkingPanic = 43,
ConnectionTimedOut = 44, NetworkUnreachable = 45, BrokenPipe = 46, InvalidProxyAddress = 47,
RemoteEndClosedConnection = 48, InvalidIrcContextId = 49, ErrorInLoadingModule = 50, NoSuchModuleCommand = 51,
NoSuchModuleFunction = 52, LeftOperandIsNotADictionaryReference = 53, RightOperandIsNotADictionaryReference = 54, MissingObjectClassName = 55,
NoSuchObjectClass = 56, NoSuchObject = 57, NoSuchObjectFunction = 58, InvalidLeftOperand = 59,
NotEnoughParameters = 60, IntegerParameterExpected = 61, InvalidParameter = 62, NoSuchFile = 63,
OpenParenthesisExpected = 64, OpenBraceExpected = 65, CantKillABuiltinClass = 66, SocksV4LacksIPv6Support = 67,
UnrecognizedProxyReply = 68, ProxyAuthFailed = 69, ProxyNoAcceptableAuthMethod = 70, ProxyReply91RequestFailed = 71,
ProxyReply92IdentFailed = 72, ProxyReply93IdentNotMatching = 73, ProxyReply01GeneralSOCKSFailure = 74, ProxyReply02ConnectionNotAllowed = 75,
ProxyReply03NetworkUnreachable = 76, ProxyReply04HostUnreachable = 77, ProxyReply05ConnectionRefused = 78, ProxyReply06TTLExpired = 79,
ProxyReply07CommandNotSupported = 80, ProxyReply08AddressTypeNotSupported = 81, ProxyReply09InvalidAddress = 82, InvalidPortNumber = 83,
SocketNotConnected = 84, InsufficientResources = 85, BindFailed = 86, CantResolveLocalhost = 87,
UnsupportedImageFormat = 88, CantOpenFileForAppending = 89, CantOpenFileForWriting = 90, FileIOError = 91,
AcknowledgeError = 92, CantOpenFileForReading = 93, CantSendAZeroSizeFile = 94, MissingPopupName = 95,
ItemPopupOrSeparatorExpected = 96, SelfModificationNotAllowed = 97, FeatureNotAvailable = 98, UnexpectedCharactersInArrayIndex = 99,
UnexpectedEndInExpression = 100, UnexpectedEndInArrayIndex = 101, ProxyHttpFailure = 102, CaseMatchRegexpDefaultOrBreakExpected = 103,
AccessDenied = 104, AddressAlreadyInUse = 105, CantAssignRequestedAddress = 106, ConnectionResetByPeer = 107,
HostUnreachable = 108, VariableExpected = 109, InvalidArrayIndex = 110, ListenFailed = 111,
NoSSLSupport = 112, SSLError = 113, SlashCharacterExpected = 114, UnknownStringManipulationOperator = 115,
OperationAborted = 116, UnexpectedToken = 117, ScopeObjectAlreadyDefined = 118, NoThisObject = 119,
ErrorCount = 120
}
Contains all error codes.
Functions
QString getDescription (KviError::Code eError)
Returns the description of the error.
const char * getUntranslatedDescription (KviError::Code eError)
Returns an untranslated description of the error.
KviError::Code translateSystemError (int iErrNo)
Gets system errors and returns their code number.
Detailed Description
This namespace handle the error codes.
Enumeration Type Documentation
enum KviError::Code
Contains all error codes.
Enumerator
Success
UnknownError
InternalError
UnknownCommand
MissingClosingBrace
UnexpectedEndInString
UnexpectedEndInDictionaryKey
SwitchDashWithoutSwitchLetter
UnknownFunction
UnexpectedEndInParenthesis
UnexpectedEndInFunctionParams
MissingVariableName
VariableOrIdentifierExpected
LeftOperandIsNotANumber
MultipleOpsNotSupportedForOperator
DivisionByZero
ModuloByZero
RightOperandIsNotANumber
UnterminatedExpression
UnterminatedSubexpression
UnexpectedCharacter
UnknownOperator
NoHostToResolve
UnsupportedAddressFamily
ValidNameButNoIpAddress
UnrecoverableNameserverError
DNSTemporaneousFault
DNSInternalErrorBadFlags
DNSInternalErrorOutOfMemory
DNSInternalErrorServiceNotSupported
DNSNoName
DNSInternalErrorUnsupportedSocketType
DNSQueryFailed
NoIPv6Support
HostNotFound
DNSInternalIPCFailure
AnotherConnectionInProgress
InvalidIpAddress
SocketCreationFailed
AsyncSocketFailed
BadFileDescriptor
OutOfAddressSpace
ConnectionRefused
KernelNetworkingPanic
ConnectionTimedOut
NetworkUnreachable
BrokenPipe
InvalidProxyAddress
RemoteEndClosedConnection
InvalidIrcContextId
ErrorInLoadingModule
NoSuchModuleCommand
NoSuchModuleFunction
LeftOperandIsNotADictionaryReference
RightOperandIsNotADictionaryReference
MissingObjectClassName
NoSuchObjectClass
NoSuchObject
NoSuchObjectFunction
InvalidLeftOperand
NotEnoughParameters
IntegerParameterExpected
InvalidParameter
NoSuchFile
OpenParenthesisExpected
OpenBraceExpected
CantKillABuiltinClass
SocksV4LacksIPv6Support
UnrecognizedProxyReply
ProxyAuthFailed
ProxyNoAcceptableAuthMethod
ProxyReply91RequestFailed
ProxyReply92IdentFailed
ProxyReply93IdentNotMatching
ProxyReply01GeneralSOCKSFailure
ProxyReply02ConnectionNotAllowed
ProxyReply03NetworkUnreachable
ProxyReply04HostUnreachable
ProxyReply05ConnectionRefused
ProxyReply06TTLExpired
ProxyReply07CommandNotSupported
ProxyReply08AddressTypeNotSupported
ProxyReply09InvalidAddress
InvalidPortNumber
SocketNotConnected
InsufficientResources
BindFailed
CantResolveLocalhost
UnsupportedImageFormat
CantOpenFileForAppending
CantOpenFileForWriting
FileIOError
AcknowledgeError
CantOpenFileForReading
CantSendAZeroSizeFile
MissingPopupName
ItemPopupOrSeparatorExpected
SelfModificationNotAllowed
FeatureNotAvailable
UnexpectedCharactersInArrayIndex
UnexpectedEndInExpression
UnexpectedEndInArrayIndex
ProxyHttpFailure
CaseMatchRegexpDefaultOrBreakExpected
AccessDenied
AddressAlreadyInUse
CantAssignRequestedAddress
ConnectionResetByPeer
HostUnreachable
VariableExpected
InvalidArrayIndex
ListenFailed
NoSSLSupport
SSLError
SlashCharacterExpected
UnknownStringManipulationOperator
OperationAborted
UnexpectedToken
ScopeObjectAlreadyDefined
NoThisObject
ErrorCount
Function Documentation
KVILIB_API QString KviError::getDescription (KviError::Code eError)
Returns the description of the error.
Parameters
eError The code number of the error
Returns
QString
References __tr2qs_no_xgettext, and getUntranslatedDescription().
Referenced by KviDnsResolver::errorString(), DccChatWindow::event(), DccVoiceWindow::event(), DccVideoWindow::event(), DccFileTransfer::event(), DccChatWindow::handleMarshalError(), DccVoiceWindow::handleMarshalError(), DccVideoWindow::handleMarshalError(), DccFileTransfer::handleMarshalError(), KviIrcConnection::hostNameLookupTerminated(), KviThreadManager::KviThreadManager(), KviIrcSocket::raiseError(), and KviIrcLink::resolverTerminated().
KVILIB_API const char * KviError::getUntranslatedDescription (KviError::Code eError)
Returns an untranslated description of the error.
Parameters
eError The code number of the error
Returns
const char *
References ErrorCount, g_errorTable, and UnknownError.
Referenced by getDescription().
KVILIB_API KviError::Code KviError::translateSystemError (int iErrNo)
Gets system errors and returns their code number.
Parameters
iErrNo The code number of the system error
Returns
int
References AccessDenied, AddressAlreadyInUse, BadFileDescriptor, BrokenPipe, CantAssignRequestedAddress, ConnectionRefused, ConnectionResetByPeer, ConnectionTimedOut, HostUnreachable, InsufficientResources, KernelNetworkingPanic, NetworkUnreachable, OutOfAddressSpace, SocketNotConnected, UnknownError, and UnsupportedAddressFamily.
Referenced by DccMarshal::doConnect(), DccMarshal::doSSLHandshake(), KviIrcSocket::doSSLHandshake(), KviIrcSocket::flushSendQueue(), DccThread::handleInvalidSocketRead(), KviIrcSocket::handleInvalidSocketRead(), KviThreadManager::KviThreadManager(), DccSendThread::run(), DccMarshal::snActivated(), KviIrcSocket::startConnection(), DccChatThread::tryFlushOutBuffers(), and KviIrcSocket::writeNotifierFired().