KVIrc: KviMemory Namespace Reference
KviMemory Namespace Reference
Functions
void * allocate (int size)
COMPILE_MEMORY_PROFILE.
void copy (void *dst_ptr, const void *src_ptr, int len)
Moves len bytes from src_ptr to dst_ptr.
void free (void *ptr)
COMPILE_MEMORY_CHECKS.
void move (void *dst_ptr, const void *src_ptr, int len)
COMPILE_MEMORY_PROFILE.
void * reallocate (void *ptr, int size)
void set (void *dst_ptr, char c, int len)
Initializes len bytes of memory starting from dst_ptr to c.
Function Documentation
void* KviMemory::allocate (int size) [inline]
COMPILE_MEMORY_PROFILE.
COMPILE_MEMORY_CHECKS
Referenced by KviCString::base64ToBuffer(), KviIrcConnectionServerInfo::buildModePrefixTable(), KviIrcView::calculateLineWraps(), UglyBase64::decode(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), KviKvsArray::getAt(), KviNickColors::getSmartColorIntByMircColor(), KviIrcView::getTextLine(), KviCString::hexToBuffer(), KviOggIrcText::irct_decode_headerin(), KviOggIrcText::irct_decode_packetin(), KviOggIrcText::irct_encode_headerout(), KviOggIrcText::irct_encode_packetout(), kvi_hash_key_copy(), KviCString::KviCString(), KviDataBuffer::KviDataBuffer(), KviIrcViewToolWidget::KviIrcViewToolWidget(), KviKvsArray::KviKvsArray(), KVSO_CLASS_FUNCTION(), KviMessageCatalogue::load(), KviConfigurationFile::load(), KviQString::lowerISO88591(), KviSASL::plainMethod(), KviIrcLink::processData(), KviIrcSocket::proxySendTargetDataV5(), DccSendThread::run(), KviIrcSocket::sendPacket(), KviIrcSocket::sendRawData(), KviKvsArray::set(), KviCString::splitToArray(), str_kvs_fnc_evpSign(), str_kvs_fnc_printf(), DccVideoThread::textStep(), KviQString::upperISO88591(), and KviQString::vsprintf().
void KviMemory::copy (void * dst_ptr, const void * src_ptr, int len) [inline]
Moves len bytes from src_ptr to dst_ptr.
Parameters:
dst_ptr The destination memory pointer
src_ptr The source memory pointer
len the number of bytes to move
Returns:
void *
Warning:
In fastmove the src and dst may not overlap
Referenced by KviKvsObjectClass::allocateInstance(), KviCString::append(), KviKvsPopupMenuItemMenu::clone(), PopupEditorWidget::commit(), KviKvsDnsManager::dnsLookupTerminated(), KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly(), KviKvsTreeNodeAliasSimpleCommand::execute(), KviCString::extractFromString(), KvsObject_textedit::functionCopy(), KviCString::getLine(), KviIrcView::getTextLine(), KviCString::getToken(), KviCString::insert(), kvi_appendWCharToQStringWithLength(), kvi_extractToken(), kvi_extractUpTo(), kvi_hash_key_copy(), KviCString::KviCString(), KviDefaultScriptManager::KviDefaultScriptManager(), KviKvsCoreSimpleCommands::KVSCSC(), KVSO_CLASS_FUNCTION(), PopupEditorWidget::oneTimeSetup(), KviCString::operator=(), KviCString::prepend(), KviCString::replaceAll(), KviKvsTimerManager::timerEvent(), and KviKvsEventManager::triggerHandlers().
void KviMemory::free (void * ptr) [inline]
COMPILE_MEMORY_CHECKS.
Referenced by KviCString::base64ToBuffer(), KviIrcConnectionServerInfo::buildModePrefixTable(), KviIrcView::calculateLineWraps(), KviApplication::checkFileAssociations(), KviMircryptionEngine::decrypt(), delete_text_line(), file_kvs_fnc_read(), file_kvs_fnc_readBytes(), KviKvsArray::findNewSize(), KviIrcSocket::free_msgEntry(), KviCString::freeArray(), KviCString::freeBuffer(), Kopete::AV::VideoDevice::getImage(), KviNickColors::getSmartColorIntByMircColor(), DccVideoThread::handleIncomingData(), DccChatThread::handleIncomingData(), KviCString::hexDecode(), KviCString::hexEncodeWithTable(), KviCString::hexToBuffer(), kvi_hash_key_destroy(), KVSO_CLASS_FUNCTION(), KviMessageCatalogue::load(), KviConfigurationFile::load(), KviQString::lowerISO88591(), KviSASL::plainMethod(), PluginManager::pluginCall(), KviIrcLink::processData(), KviIrcSocket::proxySendTargetDataV5(), KviIrcSocket::queue_removeMessage(), KviDataBuffer::remove(), KviDataBuffer::resize(), DccSendThread::run(), DccChatThread::run(), SetupWizard::SetupWizard(), str_kvs_fnc_printf(), KviQString::upperISO88591(), KviQString::vsprintf(), KviAnimatedPixmap::~KviAnimatedPixmap(), KviCString::~KviCString(), KviDataBuffer::~KviDataBuffer(), KviIrcConnectionServerInfo::~KviIrcConnectionServerInfo(), KviIrcLink::~KviIrcLink(), and KviKvsArray::~KviKvsArray().
void KviMemory::move (void * dst_ptr, const void * src_ptr, int len) [inline]
COMPILE_MEMORY_PROFILE.
Moves len bytes from src_ptr to dst_ptr
Parameters:
dst_ptr The destination memory pointer
src_ptr The source memory pointer
len the number of bytes to move
Returns:
void *
Referenced by AddonManagementDialog::AddonManagementDialog(), KviDataBuffer::append(), KviCtcpPageDialog::center(), ChannelsJoinDialog::ChannelsJoinDialog(), CustomizeToolBarsDialog::CustomizeToolBarsDialog(), KviCString::cut(), KviCString::cutLeft(), DccVideoThread::handleIncomingData(), DccChatThread::handleIncomingData(), KviCString::hexDecode(), KviCString::hexEncodeWithTable(), KviCString::insert(), KviDataBuffer::KviDataBuffer(), KviIpcSentinel::KviIpcSentinel(), KviMainWindow::KviMainWindow(), KviConfigurationFile::load(), KviCString::operator=(), OptionsDialog::OptionsDialog(), KviCString::prepend(), KviIrcLink::processData(), KviIrcSocket::proxyAuthUserPassV5(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), RegisteredUsersDialog::RegisteredUsersDialog(), KviDataBuffer::remove(), KviIrcConnection::sendData(), KviIrcSocket::sendRawData(), KviCString::setStr(), CustomizeToolBarsDialog::showEvent(), TipWindow::showEvent(), RegistrationWizard::showEvent(), OptionsWidgetContainer::showEvent(), KviKvsCallbackTextInput::showEvent(), DccRenameDialog::showEvent(), DccAcceptDialog::showEvent(), KviSplashScreen::showEvent(), KviCString::stripLeft(), KviCString::stripLeftWhiteSpace(), KviCString::stripSpace(), ThemeManagementDialog::ThemeManagementDialog(), and KviCString::trim().
void* KviMemory::reallocate (void * ptr, int size) [inline]
Referenced by KviDataBuffer::append(), KviCString::append(), KviCString::base64ToBuffer(), KviCString::bufferToBase64(), KviCString::bufferToHex(), KviIrcView::calculateLineWraps(), KviCString::clear(), KviCString::cut(), KviCString::cutLeft(), KviCString::cutRight(), KviCString::extractFromString(), KviKvsArray::findNewSize(), KviKvsArray::getAt(), KviCString::getLine(), KviIrcView::getTextLine(), KviCString::getToken(), DccVideoThread::handleIncomingData(), DccChatThread::handleIncomingData(), KviCString::hexDecode(), KviCString::hexEncodeWithTable(), KviCString::insert(), kvi_extractToken(), kvi_extractUpTo(), KviCString::KviCString(), KviConfigurationFile::load(), KviCString::operator=(), KviCString::prepend(), KviIrcLink::processData(), KviDataBuffer::remove(), KviCString::replaceAll(), KviDataBuffer::resize(), DccChatThread::run(), KviKvsArray::set(), KviCString::setLen(), KviCString::setLength(), KviCString::setNum(), KviCString::setStr(), KviCString::splitToArray(), KviCString::sprintf(), KviCString::stripLeft(), KviCString::stripLeftWhiteSpace(), KviCString::stripRight(), KviCString::stripRightWhiteSpace(), KviCString::stripSpace(), KviCString::trim(), and KviCString::vsprintf().
void KviMemory::set (void * dst_ptr, char c, int len) [inline]
Initializes len bytes of memory starting from dst_ptr to c.
Parameters:
dst_ptr The destination memory pointer
c The character that will fill the memory
len the number of bytes to initialize
Returns:
void *
References c.
Referenced by KviIrcViewToolWidget::filterLoad(), kvi_sendIpcMessage(), and KviSockaddr::KviSockaddr().