KVIrc: KviBuildInfo Namespace Reference
KviBuildInfo Namespace Reference
This namespace contains information gathered at KVIrc build time.
Functions
QString buildCommand ()
Returns the build command used by cmake to create the KVIrc executable.
QString buildCompiler ()
Returns a description of the compiler.
QString buildCompilerFlags ()
Returns a description of the compiler flags.
QString buildCPU ()
Returns a description of the CPU.
QString buildDate ()
Retrieve the latest kvilib/kvirc build date.
QString buildFlags ()
Returns the build flags.
QString buildRevision ()
Returns the Git revision number of the local repository.
QString buildSourcesDate ()
Returns the date tag applied to the currently compiled Git sources.
QString buildSystem ()
Returns a description of the system.
QString buildSystemName ()
Returns the name part of the system.
QString buildSystemVersion ()
Returns the version part of the system.
QString features ()
Returns the list of features compiled in the KVIrc executable.
QString qtVersion ()
Returns the Qt version used to build the KVIrc executable.
Detailed Description
This namespace contains information gathered at KVIrc build time.
This, in fact, is the last time that "cmake" ran and successfully generated the kvilib Makefile. Since kvilib is generally built with the KVIrc executable, then you can assume that the information returned from this namespace strictly applies also to KVIrc.
Function Documentation
KVILIB_API QString KviBuildInfo::buildCommand ()
Returns the build command used by cmake to create the KVIrc executable.
Returns
QString
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviBuildInfo::buildCompiler ()
Returns a description of the compiler.
The compiler refers to the one used to build the KVIrc executable.
Returns
QString
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviBuildInfo::buildCompilerFlags ()
Returns a description of the compiler flags.
The flags refer to the ones used to build the KVIrc executable.
Returns
QString
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviBuildInfo::buildCPU ()
Returns a description of the CPU.
The CPU refers to the one used to build the KVIrc executable.
Returns
QString
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviBuildInfo::buildDate ()
Retrieve the latest kvilib/kvirc build date.
Returns
QString
Referenced by AboutDialog::AboutDialog(), KviKvsCoreFunctions::full_version_helper(), KviKvsCoreFunctions::KVSCF(), parseArgs(), and KviIrcServerParser::parseCtcpRequestVersion().
KVILIB_API QString KviBuildInfo::buildFlags ()
Returns the build flags.
The build flags were worked out by CMake at compilation time.
Returns
QString
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviBuildInfo::buildRevision ()
Returns the Git revision number of the local repository.
Returns
QString
Referenced by AboutDialog::AboutDialog(), KviStatusBarUpdateIndicator::binaryDataReceived(), KviKvsCoreFunctions::full_version_helper(), KviKvsCoreFunctions::KVSCF(), and KviIrcServerParser::parseCtcpRequestVersion().
KVILIB_API QString KviBuildInfo::buildSourcesDate ()
Returns the date tag applied to the currently compiled Git sources.
Returns
QString
References KVI_SOURCES_DATE.
Referenced by AboutDialog::AboutDialog(), KviKvsCoreFunctions::full_version_helper(), and KviKvsCoreFunctions::KVSCF().
KVILIB_API QString KviBuildInfo::buildSystem ()
Returns a description of the system.
The system refers to the one used to build the KVIrc executable.
Returns
QString
Referenced by AboutDialog::AboutDialog().
KVILIB_API QString KviBuildInfo::buildSystemName ()
Returns the name part of the system.
The system name refers to the one used to build the KVIrc executable.
Returns
QString
Referenced by KviStatusBarUpdateIndicator::getNewVersion().
KVILIB_API QString KviBuildInfo::buildSystemVersion ()
Returns the version part of the system.
The system version refers to the one used to build the KVIrc executable.
Returns
QString
KVILIB_API QString KviBuildInfo::features ()
Returns the list of features compiled in the KVIrc executable.
Returns
QString
References feature_array, and i.
Referenced by AboutDialog::AboutDialog(), KviWindowListBase::applyOptions(), KviClassicWindowList::doLayout(), KviKvsCoreFunctions::init(), KVSO_CLASS_FUNCTION(), and KviWindowListBase::updateDockLocation().
KVILIB_API QString KviBuildInfo::qtVersion ()
Returns the Qt version used to build the KVIrc executable.
Returns
QString
Referenced by AboutDialog::AboutDialog().