KVIrc: KviEnvironment Namespace Reference
KviEnvironment Namespace Reference
Functions
char * getVariable (const char *name)
Gets environment variable.
home hellvis69 Progetti KVIrc
svn trunk kvirc src kvilib
system KviEnvironment cpp bool setVariable (const char *name, const char *value)
Sets environment variable.
void unsetVariable (const char *name)
Unsets environment variable.
Function Documentation
char* KviEnvironment::getVariable (const char * name) [inline]
Gets environment variable.
Parameters:
name The name of the variable to get
Returns:
char *
Referenced by KviLocale::KviLocale(), SetupWizard::SetupWizard(), and system_kvs_fnc_getenv().
KVILIB_API bool KviEnvironment::setVariable (const char * name, const char * value)
Sets environment variable.
Parameters:
name The name of the variable to set
value The value of the variable
Returns:
bool
Referenced by KviApplication::KviApplication(), and system_kvs_cmd_setenv().
KVILIB_API void KviEnvironment::unsetVariable (const char * name)
Unsets environment variable.
Parameters:
name The name of the variable to set
Returns:
void
Referenced by system_kvs_cmd_setenv().