KVIrc: KviKvsCoreSimpleCommands Namespace Reference
KviKvsCoreSimpleCommands Namespace Reference
Functions
home hellvis69 Progetti KVIrc
svn trunk kvirc src kvirc kvs
KviKvsCoreSimpleCommands cpp
void init ()
KVSCSC (whowas)
KVSCSC (whois)
KVSCSC (who)
KVSCSC (warning)
KVSCSC (voice)
KVSCSC (userop)
KVSCSC (unban)
KVSCSC (away)
KVSCSC (trload)
KVSCSC (topic)
KVSCSC (srand)
KVSCSC (squery)
KVSCSC (setreturn)
KVSCSC (setmenu)
KVSCSC (server)
KVSCSC (say)
KVSCSC (run)
KVSCSC (rebind)
KVSCSC (returnCKEYWORDWORKAROUND)
KVSCSC (raw)
KVSCSC (raise)
KVSCSC (quit)
KVSCSC (query)
KVSCSC (privmsg)
KVSCSC (popup)
KVSCSC (play)
KVSCSC (part)
KVSCSC (parse)
KVSCSC (option)
KVSCSC (openurl)
KVSCSC (op)
KVSCSC (notice)
KVSCSC (nick)
KVSCSC (mode)
KVSCSC (me)
KVSCSC (listtimers)
KVSCSC (killtimer)
KVSCSC (kick)
KVSCSC (join)
KVSCSC (buttonctl)
KVSCSC (host)
KVSCSC (help)
KVSCSC (halt)
KVSCSC (halfop)
KVSCSC (exit)
KVSCSC (eventctl)
KVSCSC (eval)
KVSCSC (error)
KVSCSC (echo)
KVSCSC (echoprivmsg)
KVSCSC (devoice)
KVSCSC (deuserop)
KVSCSC (deop)
KVSCSC (delpopupitem)
KVSCSC (deleteCKEYWORDWORKAROUND)
KVSCSC (dehalfop)
KVSCSC (dechanowner)
KVSCSC (dechanadmin)
KVSCSC (debugCKEYWORDWORKAROUND)
KVSCSC (ctcp)
KVSCSC (chanowner)
KVSCSC (chanadmin)
KVSCSC (cap)
KVSCSC (inject)
KVSCSC (beep)
KVSCSC (ban)
KVSCSC (back)
KVSCSC (trunload)
KVSCSC (rfc2812wrapper)
bool multipleModeCommand (KviKvsRunTimeContext *__pContext, KviKvsVariantList *__pParams, KviKvsSwitchList *__pSwitches, char plusminus, char flag)
Function Documentation
void KviKvsCoreSimpleCommands::init ()
References _REGCMD, KviKvsKernel::instance(), KviIrcUrl::join(), KviIrcUrl::parse(), quit(), KviIrcUrl::run(), and KviMessageBox::warning().
KviKvsCoreSimpleCommands::KVSCSC (whowas)
References KVS_PF_APPENDREMAINING, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (whois)
References KVS_PF_APPENDREMAINING, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (who)
References __tr2qs_ctx(), Channel, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (warning)
References KVSCSC_pContext, KVSCSC_pParams, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (voice)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (userop)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (unban)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (away)
References KviWindow::connection(), KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), KviIrcConnection::encodeText(), KviConsoleWindow::isConnected(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseAwayMessage, KviOption_stringAwayMessage, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_REQUIRE_CONNECTION, KviIrcConnection::sendFmtData(), and szR.
KviKvsCoreSimpleCommands::KVSCSC (trload)
References __tr2qs_ctx(), g_pApp, KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviLocale::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviLocale::loadCatalogue(), and KviApplication::Locale.
KviKvsCoreSimpleCommands::KVSCSC (topic)
References __tr2qs_ctx(), Channel, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (srand)
References i, KVS_PF_OPTIONAL, KVS_PT_INT, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pParams, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (squery)
References KVI_OUT_OWNPRIVMSG, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and w.
KviKvsCoreSimpleCommands::KVSCSC (setreturn)
References KVSCSC_pContext, KVSCSC_pParams, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (setmenu)
References __tr2qs_ctx(), KviMenuBar::addMenu(), g_pMainWindow, KviMenuBar::getDefaultItemRealIndex(), KviKvsPopupManager::instance(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviKvsPopupManager::lookup(), KviMainWindow::mainMenuBar(), p, and KviMenuBar::removeMenu().
KviKvsCoreSimpleCommands::KVSCSC (server)
References __tr2qs_ctx(), KviAsynchronousConnectionData::bPortIsOk, KviAsynchronousConnectionData::bSTARTTLS, KviAsynchronousConnectionData::bUseIPv6, KviAsynchronousConnectionData::bUseLastServerInContext, KviAsynchronousConnectionData::bUseSSL, KviMainWindow::createNewConsole(), d, KviMainWindow::firstNotConnectedConsole(), g_pMainWindow, KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KviAsynchronousConnectionData::m_pReconnectInfo, KviIrcServerReconnectInfo::m_szNick, KviIrcServerReconnectInfo::m_szPass, KviAsynchronousConnectionData::szBindAddress, KviAsynchronousConnectionData::szCommandToExecAfterConnect, KviAsynchronousConnectionData::szLinkFilter, KviAsynchronousConnectionData::szNick, KviAsynchronousConnectionData::szPass, KviAsynchronousConnectionData::szServer, KviAsynchronousConnectionData::uPort, and uPort.
KviKvsCoreSimpleCommands::KVSCSC (say)
References __tr2qs_ctx(), KVS_PF_APPENDREMAINING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KviUserInput::parse(), and KviUserInput::parseNonCommand().
KviKvsCoreSimpleCommands::KVSCSC (run)
References KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_STRINGLIST, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, l, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (rebind)
References __tr2qs_ctx(), KviApplication::findWindow(), g_pApp, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and KVSCSC_pSwitches.
KviKvsCoreSimpleCommands::KVSCSC (returnCKEYWORDWORKAROUND)
References KVSCSC_pContext, KVSCSC_pParams, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (raw)
References __tr2qs_ctx(), KVI_OUT_RAW, KVS_PF_APPENDREMAINING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, and KVSCSC_REQUIRE_CONNECTION.
KviKvsCoreSimpleCommands::KVSCSC (raise)
References g_pMainWindow, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (quit)
References g_pApp, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and quit().
KviKvsCoreSimpleCommands::KVSCSC (query)
References __tr2qs_ctx(), KviIrcConnection::CreateQueryVisibilityFollowSettings, KviIrcConnection::CreateQueryVisibilityMinimized, KviIrcConnection::CreateQueryVisibilityVisible, e, KviIrcUserDataBase::find(), KviIrcUserEntry::host(), KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, Q_UNUSED(), and KviIrcUserEntry::user().
KviKvsCoreSimpleCommands::KVSCSC (privmsg)
References KVI_OUT_OWNPRIVMSG, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and w.
KviKvsCoreSimpleCommands::KVSCSC (popup)
References KviKvsVariant::asString(), KviKvsVariantList::count(), i, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_VARIANTLIST, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviKvsScript::PreserveParams, KviKvsScript::run(), and s.
KviKvsCoreSimpleCommands::KVSCSC (play)
References __tr2qs_ctx(), g_pModuleManager, KviModuleManager::getModule(), KVSCSC_pContext, KVSCSC_pParams, KVSCSC_pSwitches, KviKvsModuleInterface::kvsFindSimpleCommand(), and m.
KviKvsCoreSimpleCommands::KVSCSC (part)
References __tr2qs_ctx(), Channel, KviWindow::encodeText(), KVI_OPTION_STRING, KviOption_stringPartMessage, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and KviChannelWindow::partMessageSent().
KviKvsCoreSimpleCommands::KVSCSC (parse)
References __tr2qs_ctx(), KviFileUtils::adjustFilePath(), KviFileDialog::askForOpenFileName(), KviFileUtils::directoryExists(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), KVI_PATH_SEPARATOR_CHAR, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANTLIST, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviFileUtils::loadFile(), KviKvsVariantList::prepend(), KviKvsScript::PreserveParams, KviKvsScript::run(), s, and szBuffer.
KviKvsCoreSimpleCommands::KVSCSC (option)
References __tr2qs_ctx(), g_pApp, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pWindow, KviApplication::listAvailableOptions(), Q_UNUSED(), and KviApplication::setOptionValue().
KviKvsCoreSimpleCommands::KVSCSC (openurl)
References __tr2qs_ctx(), KviKvsVariantList::append(), KviIrcUrl::DoNotPartChans, KviQString::equalCIN(), KviIrcUrl::InvalidProtocol, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseSystemUrlHandlers, KviOption_stringUrlFileCommand, KviOption_stringUrlFtpCommand, KviOption_stringUrlHttpCommand, KviOption_stringUrlHttpsCommand, KviOption_stringUrlMailtoCommand, KviOption_stringUrlUnknownCommand, KVS_PF_APPENDREMAINING, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pWindow, NULL, KviKvsScript::PreserveParams, Q_UNUSED(), KviKvsScript::run(), KviIrcUrl::run(), szUrl, and KviIrcUrl::TryEveryContext.
KviKvsCoreSimpleCommands::KVSCSC (op)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (notice)
References KVI_OUT_OWNPRIVMSG, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, and w.
KviKvsCoreSimpleCommands::KVSCSC (nick)
References KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (mode)
References KVS_PF_APPENDREMAINING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
home hellvis69 Progetti KVIrc svn trunk kvirc src kvirc kvs KviKvsCoreSimpleCommands_mr cpp KviKvsCoreSimpleCommands::KVSCSC (me)
References __tr2qs_ctx(), KviWindow::Channel, KviWindow::DccChat, KviWindow::DccVideo, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, Q_UNUSED(), and KviWindow::Query.
KviKvsCoreSimpleCommands::KVSCSC (listtimers)
References __tr2qs_ctx(), KviPointerHashTableIterator< Key, T >::current(), KviKvsTimerManager::instance(), KVI_OUT_VERBOSE, KVSCSC_pContext, KviKvsTimer::Persistent, Q_UNUSED(), KviKvsTimer::SingleShot, KviKvsTimerManager::timerDict(), and KviKvsTimer::WindowLifetime.
KviKvsCoreSimpleCommands::KVSCSC (killtimer)
References __tr2qs_ctx(), KviKvsTimerManager::deleteAllTimers(), KviKvsTimerManager::deleteCurrentTimer(), KviKvsTimerManager::instance(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and KVSCSC_pSwitches.
KviKvsCoreSimpleCommands::KVSCSC (kick)
References __tr2qs_ctx(), Channel, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, Q_UNUSED(), szR, and szU.
KviKvsCoreSimpleCommands::KVSCSC (join)
References f, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (buttonctl)
References __tr2qs_ctx(), KviTalToolTip::add(), g_pIconManager, KviIconManager::getImage(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, o, and KviTalToolTip::remove().
KviKvsCoreSimpleCommands::KVSCSC (host)
References KviDnsResolver::Any, KviDnsResolver::IPv4, KviDnsResolver::IPv6, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and KVSCSC_pSwitches.
KviKvsCoreSimpleCommands::KVSCSC (help)
References KviQString::escapeKvs(), KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviKvsScript::run(), and s.
KviKvsCoreSimpleCommands::KVSCSC (halt)
References KVSCSC_pContext, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (halfop)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (exit)
References g_pApp, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (eventctl)
References __tr2qs_ctx(), KviMemory::copy(), KviKvsEventManager::enableScriptRawHandler(), KviKvsEventManager::findAppEventIndexByName(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), h, KviKvsEventManager::instance(), KviKvsEventManager::isValidRawEvent(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_VARIANTLIST, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KviKvsScript::PreserveParams, KviKvsEventManager::removeScriptRawHandler(), KviKvsScript::run(), s, and KviKvsScriptEventHandler::script().
KviKvsCoreSimpleCommands::KVSCSC (eval)
References KVS_PF_APPENDREMAINING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviKvsScript::Quiet, and s.
KviKvsCoreSimpleCommands::KVSCSC (error)
References KVSCSC_pContext, KVSCSC_pParams, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (echo)
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviApplication::findWindow(), g_pApp, KviDebugWindow::getInstance(), KVI_NUM_MSGTYPE_OPTIONS, KVI_OUT_NONE, KVSCSC_pContext, KVSCSC_pParams, KVSCSC_pSwitches, KviIrcView::NoTimestamp, KviWindow::outputNoFmt(), and v.
KviKvsCoreSimpleCommands::KVSCSC (echoprivmsg)
References __tr2qs_ctx(), KviApplication::activeConsole(), KviKvsVariant::asInteger(), KviKvsVariant::asString(), KviWindow::console(), KviApplication::findWindow(), g_pApp, KVI_NUM_MSGTYPE_OPTIONS, KVI_OUT_NONE, KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KviConsoleWindow::NoHighlighting, KviConsoleWindow::NoNotifier, KviConsoleWindow::NoWindowFlashing, KviConsoleWindow::outputPrivmsg(), szHost, KviOsInfo::type(), and v.
KviKvsCoreSimpleCommands::KVSCSC (devoice)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (deuserop)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (deop)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (delpopupitem)
References KviQString::escapeKvs(), KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviKvsScript::run(), and s.
KviKvsCoreSimpleCommands::KVSCSC (deleteCKEYWORDWORKAROUND)
References __tr2qs_ctx(), KviKvsObject::die(), KviKvsObject::dieNow(), KviKvsKernel::instance(), KVS_PT_HOBJECT, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, KVSCSC_pSwitches, KviKvsObjectController::lookupObject(), o, and KviKvsKernel::objectController().
KviKvsCoreSimpleCommands::KVSCSC (dehalfop)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (dechanowner)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (dechanadmin)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (debugCKEYWORDWORKAROUND)
References KviDebugWindow::getInstance(), KVI_OUT_NONE, KVSCSC_pParams, KVSCSC_pSwitches, KviWindow::outputNoFmt(), and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (ctcp)
References KviQString::appendFormatted(), KviQString::equalCI(), kvi_gettimeofday(), KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, and KVSCSC_REQUIRE_CONNECTION.
KviKvsCoreSimpleCommands::KVSCSC (chanowner)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (chanadmin)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (cap)
References KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
KviKvsCoreSimpleCommands::KVSCSC (inject)
References __tr2qs_ctx(), Channel, KviWindow::console(), KviWindow::Console, KviWindow::context(), KviPointerList< T >::first(), g_pMainWindow, KVI_OUT_SOCKETMESSAGE, KVS_PF_APPENDREMAINING, KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, KviPointerList< T >::next(), KviWindow::output(), Q_UNUSED(), KviWindow::Query, KviWindow::SocketSpy, and KviMainWindow::windowList().
KviKvsCoreSimpleCommands::KVSCSC (beep)
References __tr2qs_ctx(), KviKvsVariant::asInteger(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and KVSCSC_pSwitches.
KviKvsCoreSimpleCommands::KVSCSC (ban)
References multipleModeCommand().
KviKvsCoreSimpleCommands::KVSCSC (back)
References KviWindow::connection(), KviWindow::Console, KviPointerHashTableIterator< Key, T >::current(), KviConsoleWindow::isConnected(), KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pSwitches, KVSCSC_REQUIRE_CONNECTION, Q_UNUSED(), and KviIrcConnection::sendFmtData().
KviKvsCoreSimpleCommands::KVSCSC (trunload)
References __tr2qs_ctx(), KviLocale::instance(), KVS_PT_NONEMPTYSTRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pContext, and KVSCSC_pSwitches.
KviKvsCoreSimpleCommands::KVSCSC (rfc2812wrapper)
References KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_REQUIRE_CONNECTION, and Q_UNUSED().
bool KviKvsCoreSimpleCommands::multipleModeCommand (KviKvsRunTimeContext * __pContext, KviKvsVariantList * __pParams, KviKvsSwitchList * __pSwitches, char plusminus, char flag)
References __tr2qs_ctx(), Channel, KVS_PF_APPENDREMAINING, KVS_PT_STRING, KVSCSC_PARAMETER, KVSCSC_PARAMETERS_BEGIN, KVSCSC_PARAMETERS_END, KVSCSC_pConnection, KVSCSC_pContext, KVSCSC_pWindow, KVSCSC_REQUIRE_CONNECTION, KviIrcConnectionServerInfo::maxModeChanges(), and Q_UNUSED().
Referenced by KVSCSC().