KVIrc: KviIrcUrl Namespace Reference
KviIrcUrl Namespace Reference
Enumerations
enum KviIrcUrlContextSpec {
FirstFreeContext = 1, NewContext = 2, CurrentContext = 4, TryCurrentContext = 8,
TryEveryContext = 32, DoNotPartChans = 16
}
enum KviIrcUrlParserError { InvalidProtocol = 1, InvalidPort = 2, NeedNewContext = 4, InvalidUrl = 8 }
Functions
KVIRC_API void join (QString &url, KviIrcServer *server)
KVIRC_API void makeJoinCmd (const QStringList &chans, QString &szJoinCommand)
KVIRC_API bool parse (const char *url, KviCString &cmdBuffer, int contextSpec=KVI_IRCURL_CONTEXT_FIRSTFREE)
KVIRC_API int run (const QString &url, int contextSpec=FirstFreeContext, KviConsoleWindow *pConsole=0)
KVIRC_API void split (QString url, KviIrcUrlParts &parts)
Enumeration Type Documentation
enum KviIrcUrl::KviIrcUrlContextSpec
Enumerator:
FirstFreeContext
NewContext
CurrentContext
TryCurrentContext
TryEveryContext
DoNotPartChans
enum KviIrcUrl::KviIrcUrlParserError
Enumerator:
InvalidProtocol
InvalidPort
NeedNewContext
InvalidUrl
Function Documentation
void KviIrcUrl::join (QString & url, KviIrcServer * server)
References KviIrcServer::hostName(), KviIrcServer::isIPv6(), KviIrcServer::port(), and KviIrcServer::useSSL().
Referenced by chan_kvs_fnc_getUrl(), KviIrcContext::connectionEstabilished(), KviIrcView::doLinkToolTip(), KviKvsCoreSimpleCommands::init(), and KviConsoleWindow::updateUri().
void KviIrcUrl::makeJoinCmd (const QStringList & chans, QString & szJoinCommand)
Referenced by run().
bool KviIrcUrl::parse (const char * url, KviCString & cmdBuffer, int contextSpec = KVI_IRCURL_CONTEXT_FIRSTFREE)
References KviCString::append(), _KviIrcUrlParts::bIPv6, _KviIrcUrlParts::bSsl, _KviIrcUrlParts::chanList, KviCString::Format, i, _KviIrcUrlParts::iError, InvalidUrl, _KviIrcUrlParts::iPort, KVI_IRCURL_CONTEXT_FIRSTFREE, KVI_IRCURL_CONTEXT_NEW, split(), and _KviIrcUrlParts::szHost.
Referenced by KviKvsCoreSimpleCommands::init(), KviInput::inputEditorEnterPressed(), KviInput::keyPressEvent(), KviMenuBar::newConnectionToServer(), KviConnectToServerAction::popupActivated(), and NotifierWindow::returnPressed().
int KviIrcUrl::run (const QString & url, int contextSpec = FirstFreeContext, KviConsoleWindow * pConsole = 0)
References KviApplication::addRecentUrl(), _KviIrcUrlParts::bIPv6, _KviIrcUrlParts::bSsl, c, _KviIrcUrlParts::chanList, KviIrcConnection::channelList(), KviWindow::connection(), KviConsoleWindow::connectionInProgress(), KviWindow::Console, KviMainWindow::createNewConsole(), KviPointerHashTableIterator< Key, T >::current(), CurrentContext, DoNotPartChans, KviIrcConnection::encodeText(), KviPointerList< T >::first(), FirstFreeContext, KviMainWindow::firstNotConnectedConsole(), g_pApp, g_pGlobalWindowDict, g_pMainWindow, KviIrcServer::hostName(), _KviIrcUrlParts::iError, InvalidProtocol, InvalidUrl, _KviIrcUrlParts::iPort, KviIrcServer::isIPv6(), makeJoinCmd(), KviPointerList< T >::next(), KviIrcServer::port(), KviKvsScript::run(), KviIrcConnection::sendData(), KviIrcConnectionTarget::server(), split(), _KviIrcUrlParts::szHost, KviIrcConnection::target(), TryCurrentContext, TryEveryContext, and KviIrcServer::useSSL().
Referenced by KviKvsAction::activate(), KviApplication::autoConnectToServers(), ClassEditorWidget::build(), ChannelsJoinDialog::clearClicked(), OptionsWidget_servers::connectCurrentClicked(), KviApplication::createFrame(), KviIrcContext::createLinksWindow(), KviIrcContext::createListWindow(), KviMainWindow::customizeToolBars(), UrlDialog::dblclk_url(), KviInputEditor::dropEvent(), CodeTesterWidget::execute(), KviMainWindow::executeInternalCommand(), KviConsoleWindow::executeInternalCommand(), AddonManagementDialog::getMoreScripts(), KviStatusBarUpdateIndicator::getNewVersion(), KviKvsCoreSimpleCommands::init(), KviFileTransferManager::invokeTransferWindow(), KviApplication::ipcMessage(), KviConsoleWindow::ircUriChanged(), ChannelsJoinDialog::joinClicked(), KviKvsCoreSimpleCommands::KVSCSC(), KviKvsObjectClass::load(), KviApplication::loadDefaultScript(), KviIrcConnection::loginComplete(), KviIrcConnection::loginToIrcServer(), KviStatusBarAwayIndicator::mouseDoubleClickEvent(), ClassEditorWidget::newClass(), KviMenuBar::newConnectionToServer(), KviAsyncAvatarSelectionDialog::okClicked(), FileTransferWindow::openFilePopupActivated(), FileTransferWindow::openLocalFile(), FileTransferWindow::openLocalFileFolder(), KviIrcServerParser::parseLiteralKick(), KviIrcServerParser::parseLiteralNotice(), KviIrcServerParser::parseLiteralPrivmsg(), KviInputEditor::pasteFile(), KviInputEditor::pasteSlow(), KviSoundSelector::playSound(), KviJoinChannelAction::popupActivated(), KviChangeNickAction::popupActivated(), KviConnectToServerAction::popupActivated(), KviChangeUserModeAction::popupActivated(), OptionsWidget_servers::recentServersPopupClicked(), ChannelsJoinDialog::regClicked(), DccFileTransfer::retryDCC(), DccFileTransfer::retryRevDCC(), DccFileTransfer::retryTDCC(), UrlDialog::sayToWin(), KviInputEditor::stopPasteSlow(), HttpFileTransfer::transferTerminated(), and KviIrcView::triggerMouseRelatedKvsEvents().
void KviIrcUrl::split (QString url, KviIrcUrlParts & parts)
References _KviIrcUrlParts::bIPv6, _KviIrcUrlParts::bSsl, _KviIrcUrlParts::chanList, _KviIrcUrlParts::iError, InvalidPort, InvalidUrl, _KviIrcUrlParts::iPort, and _KviIrcUrlParts::szHost.
Referenced by parse(), run(), and OptionsWidget_servers::selectBestServerByUrl().