KVIrc: KviUserInput Namespace Reference
KviUserInput Namespace Reference
Namespace that contains parsing function for the user input.
Functions
KVIRC_API void escapeString (QString &szData)
Escapes any kvs special character from a string.
bool parse (QString &szData, KviWindow *pWindow, const QString &szContext=KviQString::Empty, bool bUserFriendlyCommandline=false)
Returns false if szData is a command and it fails to run.
bool parseCommand (const QString &szData, KviWindow *pWindow, const QString &szContext=KviQString::Empty, bool bUserFriendlyCommandline=false)
Returns true if the command run.
void parseNonCommand (QString &szData, KviWindow *pWindow)
Parses the non command input data.
Detailed Description
Namespace that contains parsing function for the user input.
Function Documentation
KVIRC_API void KviUserInput::escapeString (QString & szData)
Escapes any kvs special character from a string.
Parameters
szData The string to escape
Returns
void
KVIRC_API bool KviUserInput::parse (QString & szData, KviWindow * pWindow, const QString & szContext = KviQString::Empty, bool bUserFriendlyCommandline = false)
Returns false if szData is a command and it fails to run.
Parameters
szData The input data to parse
pWindow The window associated to the input
szContext The context associated to the input
bUserFriendlyCommandline Whether the commandline is in user friendly mode
Returns
bool
Warning
May destroy szData
References c, KviEvent_OnTextInput, KVS_TRIGGER_EVENT_1_HALTED, parseCommand(), and parseNonCommand().
Referenced by KviInput::inputEditorEnterPressed(), KviInput::keyPressEvent(), KviKvsCoreSimpleCommands::KVSCSC(), and NotifierWindow::returnPressed().
KVIRC_API bool KviUserInput::parseCommand (const QString & szData, KviWindow * pWindow, const QString & szContext = KviQString::Empty, bool bUserFriendlyCommandline = false)
Returns true if the command run.
Parameters
szData The input data to parse
pWindow The window associated to the input
szContext The context associated to the input
bUserFriendlyCommandline Whether the commandline is in user friendly mode
Returns
bool
References __tr2qs, KviKvsScript::Error, KviQString::escapeKvs(), and KviQString::EscapeParenthesis.
Referenced by parse(), parseNonCommand(), and KviInputEditor::sendKvs().
KVIRC_API void KviUserInput::parseNonCommand (QString & szData, KviWindow * pWindow)
Parses the non command input data.
Parameters
szData The input data to parse
pWindow The window associated to the input
Returns
void
References __tr2qs, KviWindow::Channel, KviWindow::connection(), KviWindow::Console, KviWindow::console(), KviWindow::DccChat, KviWindow::DccVideo, KviIrcConnection::encodeText(), KviIrcConnectionUserInfo::isAway(), KVI_OPTION_BOOL, KVI_OUT_PARSERERROR, KVI_OUT_RAW, KviOption_boolExitAwayOnInput, KviWindow::output(), KviWindow::ownMessage(), parseCommand(), KviWindow::Query, KviWindow::type(), and KviIrcConnection::userInfo().
Referenced by KviKvsCoreSimpleCommands::KVSCSC(), parse(), and KviInputEditor::sendPlain().