KVIrc: KviNetUtils Namespace Reference
KviNetUtils Namespace Reference
Functions
bool binaryIpToStringIp (struct in_addr in, QString &szBuffer)
void formatNetworkBandwidthString (QString &szBuffer, unsigned int uBytesPerSec)
bool getInterfaceAddress (const QString &, QString &)
COMPILE_GET_INTERFACE_ADDRESS.
bool isRoutableIp (const char *ipaddr)
bool isRoutableIpString (const QString &szIpString)
bool isValidStringIp (const QString &szIp)
bool stringIpToBinaryIp (const QString &szStringIp, struct in_addr *address)
Function Documentation
KVILIB_API bool KviNetUtils::binaryIpToStringIp (struct in_addr in, QString & szBuffer)
Referenced by dcc_module_normalize_target_data(), KviIrcSocket::getLocalHostIp(), KviDnsResolverThread::run(), and DccMarshal::snActivated().
KVILIB_API void KviNetUtils::formatNetworkBandwidthString (QString & szBuffer, unsigned int uBytesPerSec)
Referenced by HttpFileTransfer::displayPaint(), and DccFileTransfer::displayPaint().
KVILIB_API bool KviNetUtils::getInterfaceAddress (const QString & , QString &)
COMPILE_GET_INTERFACE_ADDRESS.
COMPILE_GET_INTERFACE_ADDRESS
Referenced by dcc_kvs_get_listen_ip_address(), dcc_kvs_parse_default_parameters(), and KviIrcConnectionTargetResolver::validateLocalAddress().
KVILIB_API bool KviNetUtils::isRoutableIp (const char * ipaddr)
Referenced by isRoutableIpString().
KVILIB_API bool KviNetUtils::isRoutableIpString (const QString & szIpString)
References isRoutableIp(), and stringIpToBinaryIp().
Referenced by DccFileTransfer::connectionInProgress(), and KviIrcConnection::userInfoReceived().
KVILIB_API bool KviNetUtils::isValidStringIp (const QString & szIp)
References stringIpToBinaryIp().
Referenced by dcc_kvs_get_listen_ip_address(), DccMarshal::doConnect(), DccMarshal::doListen(), IrcServerDetailsWidget::fillData(), KviIrcConnectionTargetResolver::lookupProxyHostname(), KviIrcConnectionTargetResolver::lookupServerHostname(), KviIrcServerDataBase::makeCurrentServer(), KviIrcSocket::proxySendTargetDataV5(), KviIrcConnection::resolveLocalHost(), OptionsWidget_proxy::saveLastItem(), KviIrcSocket::startConnection(), KviIrcConnection::userInfoReceived(), and KviIrcConnectionTargetResolver::validateLocalAddress().
KVILIB_API bool KviNetUtils::stringIpToBinaryIp (const QString & szStringIp, struct in_addr * address)
References i.
Referenced by DccChatWindow::connectionInProgress(), DccVoiceWindow::connectionInProgress(), DccVideoWindow::connectionInProgress(), DccFileTransfer::connectionInProgress(), dcc_module_normalize_target_data(), isRoutableIpString(), isValidStringIp(), KviIrcSocket::proxyLoginV4(), KviIrcSocket::proxySendTargetDataV5(), and KviDnsResolverThread::run().