KVIrc: KviKvsParameterProcessor Namespace Reference
KviKvsParameterProcessor Namespace Reference
Classes
class ParameterFormat
Functions
bool handleParameterTypeError (KviKvsRunTimeContext *pContext, KviKvsParameterProcessor::ParameterFormat *pFmtArray, KviKvsVariant *v, const char *szExpectedType)
bool process (KviKvsVariantList *pVariantList, KviKvsRunTimeContext *pContext, KviKvsParameterProcessor::ParameterFormat *pFmtArray)
void setDefaultValue (KviKvsParameterProcessor::ParameterFormat *pFmtArray)
Function Documentation
bool KviKvsParameterProcessor::handleParameterTypeError (KviKvsRunTimeContext * pContext, KviKvsParameterProcessor::ParameterFormat * pFmtArray, KviKvsVariant * v, const char * szExpectedType)
References __tr2qs_ctx(), KviQString::appendFormatted(), KviKvsRunTimeContext::error(), KviKvsVariant::getTypeName(), KviKvsVariant::isEmpty(), KviKvsVariant::isString(), KVS_PF_OPTIONAL, setDefaultValue(), KviKvsVariant::string(), KviKvsParameterProcessor::ParameterFormat::szName, and KviKvsParameterProcessor::ParameterFormat::uFlags.
Referenced by process().
KVIRC_API bool KviKvsParameterProcessor::process (KviKvsVariantList * pVariantList, KviKvsRunTimeContext * pContext, KviKvsParameterProcessor::ParameterFormat * pFmtArray)
References __tr2qs_ctx(), KviKvsVariant::appendAsString(), KviKvsVariant::array(), KviKvsVariant::asBoolean(), KviKvsVariant::asHObject(), KviKvsVariant::asInteger(), KviKvsVariant::asReal(), KviKvsVariant::asString(), KviKvsVariant::castToArray(), clear(), KviKvsRunTimeContext::error(), KviKvsVariantList::first(), handleParameterTypeError(), KviKvsVariant::hash(), KviKvsVariant::isArray(), KviKvsVariant::isHash(), KVS_PF_APPENDREMAINING, KVS_PF_OPTIONAL, KVS_PT_ARRAY, KVS_PT_ARRAYCAST, KVS_PT_BOOL, KVS_PT_CSTRING, KVS_PT_DOUBLE, KVS_PT_HASH, KVS_PT_HOBJECT, KVS_PT_IGNORE, KVS_PT_INT, KVS_PT_NONEMPTYCSTRING, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVS_PT_STRINGLIST, KVS_PT_UINT, KVS_PT_VARIANT, KVS_PT_VARIANTLIST, KviKvsVariantList::next(), KviKvsParameterProcessor::ParameterFormat::pContainer, setAutoDelete(), setDefaultValue(), KviKvsParameterProcessor::ParameterFormat::szName, KviKvsParameterProcessor::ParameterFormat::uFlags, KviKvsParameterProcessor::ParameterFormat::uType, and v.
void KviKvsParameterProcessor::setDefaultValue (KviKvsParameterProcessor::ParameterFormat * pFmtArray)
References clear(), KVS_PT_ARRAY, KVS_PT_ARRAYCAST, KVS_PT_BOOL, KVS_PT_CSTRING, KVS_PT_DOUBLE, KVS_PT_HASH, KVS_PT_HOBJECT, KVS_PT_IGNORE, KVS_PT_INT, KVS_PT_NONEMPTYCSTRING, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVS_PT_STRINGLIST, KVS_PT_UINT, KVS_PT_VARIANT, KVS_PT_VARIANTLIST, KviKvsParameterProcessor::ParameterFormat::pContainer, setAutoDelete(), and KviKvsParameterProcessor::ParameterFormat::uType.
Referenced by handleParameterTypeError(), and process().