KVIrc: KviNickColors Namespace Reference
KviNickColors Namespace Reference
Functions
const char * getSmartColor (int iPos)
int getSmartColorForNick (QString *szNick)
int getSmartColorIntByMircColor (unsigned char iFore, unsigned char iBack)
Variables
static const char * g_nickColors [KVI_NUM_NICK_COLORS]
Function Documentation
KVILIB_API const char * KviNickColors::getSmartColor (int iPos)
References g_nickColors, and KVI_NUM_NICK_COLORS.
Referenced by KviConsoleWindow::outputPrivmsg().
KVILIB_API int KviNickColors::getSmartColorForNick (QString * szNick)
References i.
Referenced by KviConsoleWindow::outputPrivmsg().
KVILIB_API int KviNickColors::getSmartColorIntByMircColor (unsigned char iFore, unsigned char iBack)
References KviMemory::allocate(), KviMemory::free(), g_nickColors, i, and KVI_NUM_NICK_COLORS.
Referenced by KviIrcUserEntry::setRealName().
Variable Documentation
const char* KviNickColors::g_nickColors[KVI_NUM_NICK_COLORS] static
Initial value:
=
        {
                "0,1"  ,"0,2"  ,"0,3"  ,"0,4"  ,"0,5"  ,"0,6"  ,"0,10" ,"0,12" ,"0,14" ,
                "1,0"  ,"1,4"  ,"1,7"  ,"1,8"  ,"1,9"  ,"1,11" ,"1,15" ,
                "2,0"  ,"2,4"  ,"2,7"  ,"2,8"  ,"2,9"  ,"2,11" ,"2,15" ,
                "3,8"  ,"3,9"  ,"3,0"  ,"3,15" ,
                "4,0"  ,"4,1"  ,"4,8"  ,"4,9"  ,"4,11" ,"4,15" ,
                "5,0"  ,"5,7"  ,"5,8"  ,"5,15" ,
                "6,0"  ,"6,7"  ,"6,8"  ,"6,9"  ,"6,10" ,"6,11" ,"6,15" ,
                "7,1"  ,"7,2"  ,"7,5"  ,"7,6"  ,"7,14" ,
                "8,1"  ,"8,2"  ,"8,3"  ,"8,4"  ,"8,5"  ,"8,6"  ,"8,7"  ,"8,10" ,"8,12" ,"8,14" ,
                "9,1"  ,"9,2"  ,"9,3"  ,"9,5"  ,"9,6"  ,"9,14" ,
                "10,1" ,"10,2" ,
                "11,1" ,"11,2" ,"11,3" ,"11,5" ,"11,6" ,"11,14",
                "12,0" ,"12,7" ,"12,8" ,"12,9" ,"12,10","12,11","12,15",
                "13,0" ,"13,1" ,"13,6" ,"13,8" ,"13,11","13,15",
                "14,0" ,"14,8" ,"14,11","14,15",
                "15,1" ,"15,2" ,"15,3" ,"15,6" ,"15,14"
        }
Referenced by getSmartColor(), and getSmartColorIntByMircColor().