KVIrc: KviLocale Namespace Reference
KviLocale Namespace Reference
Classes
struct _EncodingDescription
Typedefs
typedef struct
KviLocale::_EncodingDescription EncodingDescription
Functions
QTextCodec * codecForName (const char *szName)
void done (QApplication *app)
EncodingDescription * encodingDescription (int iIdx)
const char * encodingGroup (int iIdx)
bool findCatalogue (QString &szBuffer, const QString &szName, const QString &szLocaleDir)
KviMessageCatalogue * getLoadedCatalogue (const QString &name)
void init (QApplication *app, const QString &localeDir)
bool loadCatalogue (const QString &name, const QString &szLocaleDir)
const KviCString & localeName ()
const char * translate (const char *text, const char *context)
const QString & translateToQString (const char *text, const char *context)
bool unloadCatalogue (const QString &name)
Variables
static const char * encoding_groups []
static EncodingDescription supported_encodings []
Typedef Documentation
typedef struct KviLocale::_EncodingDescription KviLocale::EncodingDescription
Function Documentation
KVILIB_API QTextCodec * KviLocale::codecForName (const char * szName)
References c, KviCString::cutFromFirst(), KviPointerHashTable< Key, T >::find(), KviCString::findFirstIdx(), kvi_strEqualCIN(), KviSmartTextCodec::ok(), KviCString::ptr(), KviPointerHashTable< Key, T >::replace(), and KviCString::replaceAll().
Referenced by KviApplication::defaultSrvCodec(), KviApplication::defaultTextCodec(), KviSmartTextCodec::KviSmartTextCodec(), KviMessageCatalogue::load(), mediaplayer_get_codec(), HelpIndex::parseDocument(), KviIrcServerParser::parseNumericCodePageSet(), KviIrcConnection::setEncoding(), KviWindow::setTextEncoding(), KviApplication::setup(), KviIrcConnection::setupSrvCodec(), and KviIrcConnection::setupTextCodec().
KVILIB_API void KviLocale::done (QApplication * app)
References g_pCatalogueDict, g_pMainCatalogue, g_pSmartCodecDict, and g_pTranslator.
Referenced by KviCustomToolBar::childEvent(), KviWindow::toggleCryptController(), KviChannelWindow::toggleModeEditor(), DccBroker::~DccBroker(), and KviApplication::~KviApplication().
KVILIB_API EncodingDescription * KviLocale::encodingDescription (int iIdx)
References KVI_NUM_ENCODINGS, and supported_encodings.
Referenced by KviWindow::createSystemTextEncodingPopup(), IrcServerDetailsWidget::fillData(), IrcNetworkDetailsWidget::fillData(), IrcNetworkDetailsWidget::IrcNetworkDetailsWidget(), IrcServerDetailsWidget::IrcServerDetailsWidget(), OptionsWidget_soundGeneral::OptionsWidget_soundGeneral(), and OptionsWidget_textEncoding::OptionsWidget_textEncoding().
KVILIB_API const char * KviLocale::encodingGroup (int iIdx)
References encoding_groups, and KVI_NUM_ENCODING_GROUPS.
Referenced by KviWindow::createSystemTextEncodingPopup().
KVILIB_API bool KviLocale::findCatalogue (QString & szBuffer, const QString & szName, const QString & szLocaleDir)
References KviCString::cutFromFirst(), KviQString::ensureLastCharIs(), KviFileUtils::fileExists(), KviCString::findFirstIdx(), g_szLang, KVI_PATH_SEPARATOR_CHAR, KviCString::ptr(), and KviCString::toLower().
Referenced by init(), and loadCatalogue().
KVILIB_API KviMessageCatalogue * KviLocale::getLoadedCatalogue (const QString & name)
References KviPointerHashTable< Key, T >::find().
Referenced by KviKvsCoreFunctions::KVSCF().
KVILIB_API void KviLocale::init (QApplication * app, const QString & localeDir)
References KviCString::cutFromFirst(), KviFileUtils::fileExists(), findCatalogue(), g_pMainCatalogue, g_szLang, KviEnvironment::getVariable(), KviCString::hasData(), KviCString::isEmpty(), kvi_strEqualCI(), KviMessageCatalogue::load(), KviCString::ptr(), KviFileUtils::readFile(), KviPointerHashTable< Key, T >::setAutoDelete(), szBuffer, KviCString::toLower(), and KviCString::trimmed().
KVILIB_API bool KviLocale::loadCatalogue (const QString & name, const QString & szLocaleDir)
References c, KviPointerHashTable< Key, T >::find(), findCatalogue(), KviPointerHashTable< Key, T >::insert(), KviMessageCatalogue::load(), and szBuffer.
Referenced by KviKvsCoreFunctions::KVSCF(), KviKvsCoreSimpleCommands::KVSCSC(), and KviModuleManager::loadModule().
KVILIB_API const KviCString & KviLocale::localeName ()
References g_szLang.
Referenced by KviApplication::getGlobalKvircDirectory(), KviApplication::getLocalKvircDirectory(), KviKvsCoreFunctions::KVSCF(), TipWindow::nextTip(), OptionsWidget_textEncoding::OptionsWidget_textEncoding(), TipWindow::prevTip(), and KviMenuBar::setupHelpPopup().
KVILIB_API const char * KviLocale::translate (const char * text, const char * context)
References c, KviPointerHashTable< Key, T >::find(), g_pMainCatalogue, KviPointerHashTable< Key, T >::insert(), and KviMessageCatalogue::translate().
KVILIB_API const QString & KviLocale::translateToQString (const char * text, const char * context)
References c, KviPointerHashTable< Key, T >::find(), g_pMainCatalogue, KviPointerHashTable< Key, T >::insert(), and KviMessageCatalogue::translateToQString().
KVILIB_API bool KviLocale::unloadCatalogue (const QString & name)
References KviPointerHashTable< Key, T >::remove().
Referenced by KviKvsCoreSimpleCommands::KVSCSC(), KviModuleManager::loadModule(), and KviModuleManager::unloadModule().
Variable Documentation
const char* KviLocale::encoding_groups[] [static]
Initial value:
        {
                "Unicode",
                "West European",
                "East European",
                "Cyrillic",
                "Middle Eastern",
                "Chinese",
                "Japanese",
                "Other asiatic",
                0
        }
Referenced by encodingGroup().
EncodingDescription KviLocale::supported_encodings[] [static]
Referenced by encodingDescription().