KVIrc: KviControlCodes Namespace Reference
KviControlCodes Namespace Reference
Holds all text control code KVIrc uses.
Enumerations
enum Color {
White = 0, Black = 1, DarkBlue = 2, DarkGreen = 3,
Red = 4, DarkRed = 5, DarkViolet = 6, Orange = 7,
Yellow = 8, LightGreen = 9, BlueMarine = 10, LightBlue = 11,
Blue = 12, LightViolet = 13, DarkGray = 14, LightGray = 15,
Transparent = 100, NoChange = 101
}
Contains mIRC color codes.
enum Control {
CTCP = 0x01, Bold = 0x02, Color = 0x03, Escape = 0x04,
UnEscape = 0x05, UnIcon = 0x06, Reset = 0x0f, Reverse = 0x16,
Icon = 0x1d, CryptEscape = 0x1e, Underline = 0x1f, SpellingMistake = 0xE942
}
Contains mIRC control codes.
Functions
const kvi_wchar_t * getColorBytesW (const kvi_wchar_t *pwData, unsigned char *pcByte1, unsigned char *pcByte2)
unsigned int getUnicodeColorBytes (const QString &szData, unsigned int iChar, unsigned char *pcByte1, unsigned char *pcByte2)
QString stripControlBytes (const QString &szData)
Removes control bytes from the given string.
Detailed Description
Holds all text control code KVIrc uses.
Enumeration Type Documentation
enum KviControlCodes::Color
Contains mIRC color codes.
Enumerator
White
White
Black
Black
DarkBlue
Dark blue
DarkGreen
Dark green
Red
Red
DarkRed
Dark red
DarkViolet
Dark violet
Orange
Orange
Yellow
Yellow
LightGreen
Light green
BlueMarine
Blue marine
LightBlue
Light blue
Blue
Blue
LightViolet
Light violet
DarkGray
Dark gray
LightGray
Light gray
Transparent
Transparent, non standard color code for KviIrcView
NoChange
No change, non standard color code for KviIrcView
enum KviControlCodes::Control
Contains mIRC control codes.
Enumerator
CTCP
CTCP, IRC control code
Bold
Bold
Color
Color
Escape
Escape, totally artificial and internal to KviIrcView
UnEscape
Unescape, totally artificial and internal to KviIrcView
UnIcon
Unicon, totally artificial and internal to KviIrcView
Reset
Reset
Reverse
Reverse
Icon
Icon, KVIrc control code
CryptEscape
Crypt escape, KVIrc control code
Underline
Underline
SpellingMistake
Totally artificial and internal to KviInputEditor. This is a character from unicode private use area
Function Documentation
KVILIB_API const kvi_wchar_t * KviControlCodes::getColorBytesW (const kvi_wchar_t * pwData, unsigned char * pcByte1, unsigned char * pcByte2)
References NoChange.
Referenced by KviIrcView::getTextLine().
KVILIB_API unsigned int KviControlCodes::getUnicodeColorBytes (const QString & szData, unsigned int iChar, unsigned char * pcByte1, unsigned char * pcByte2)
References c, and NoChange.
Referenced by KviHtmlGenerator::convertToHtml(), KviInputEditor::extractNextBlock(), KviTopicWidget::paintColoredText(), KviInputEditor::runUpToTheFirstVisibleChar(), KviIrcUserEntry::setRealName(), and stripControlBytes().
KVILIB_API QString KviControlCodes::stripControlBytes (const QString & szData)
Removes control bytes from the given string.
Parameters
szData The string to clean
Returns
QString
References Bold, CryptEscape, CTCP, getUnicodeColorBytes(), i, Icon, Reset, Reverse, and Underline.
Referenced by KviConsoleWindow::applyHighlighting(), LogViewWindow::createLog(), KviIrcView::doLinkToolTip(), KviQueryWindow::getInfoLabelText(), KviConsoleWindow::getUserTipText(), KviApplication::notifierMessage(), ChannelTreeWidgetItem::operator<(), KviConsoleWindow::outputPrivmsg(), DccChatWindow::ownAction(), DccVideoWindow::ownAction(), KviQueryWindow::ownAction(), KviChannelWindow::ownAction(), KviIrcServerParser::parseCtcpRequestAction(), KviWindow::preprocessMessage(), KviChannelWindow::preprocessMessage(), KviTopicListBoxItemDelegate::sizeHint(), ChannelTreeWidgetItemDelegate::sizeHint(), str_kvs_fnc_stripcolors(), and KviTopicListBoxItem::width().