KVIrc: KviPixmapUtils Namespace Reference
KviPixmapUtils Namespace Reference
Functions
home hellvis69 Progetti KVIrc
svn trunk kvirc src kvilib ext
KviPixmapUtils cpp void drawPixmapWithPainter (QPainter *p, QPixmap *pix, int flags, const QRect &paintRect, int iWidgetWidth, int iWidgetHeight, int dx, int dy)
void drawPixmapWithPainter (QPainter *p, QPixmap *pix, int flags, const QRect &paintRect, int iWidgetWidth, int iWidgetHeight)
Function Documentation
KVILIB_API void KviPixmapUtils::drawPixmapWithPainter (QPainter * p, QPixmap * pix, int flags, const QRect & paintRect, int iWidgetWidth, int iWidgetHeight, int dx, int dy)
References x, and y.
Referenced by drawPixmapWithPainter(), NotifierWindowTab::paintEvent(), KviUserListViewArea::paintEvent(), KviTreeWindowListTreeWidget::paintEvent(), KviIrcView::paintEvent(), KviToolBarGraphicalApplet::paintEvent(), and KviInputEditor::paintEvent().
void KviPixmapUtils::drawPixmapWithPainter (QPainter * p, QPixmap * pix, int flags, const QRect & paintRect, int iWidgetWidth, int iWidgetHeight) [inline]
References drawPixmapWithPainter().