KVIrc: KviMessageBox Namespace Reference
KviMessageBox Namespace Reference
COMPILE_WITH_KDE.
Functions
void information (QString fmt,...)
void warning (QString fmt,...)
bool yesNo (const QString &caption, QString fmt,...)
Detailed Description
COMPILE_WITH_KDE.
Function Documentation
KVIRC_API void KviMessageBox::information (QString fmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start, s, and KviQString::vsprintf().
Referenced by AliasEditorWidget::askForAliasName(), AliasEditorWidget::askForNamespaceName(), ClassEditorWidget::askForNamespaceName(), KviFileDialog::askForSaveFileName(), KviIrcView::chooseBackground(), ThemeManagementDialog::installFromFile(), main(), CustomToolBarPropertiesDialog::okClicked(), PackAddonDialog::packAddon(), PackThemeDialog::packTheme(), ClassEditorWidget::renameClass(), ClassEditorWidget::renameFunction(), AliasEditorWidget::renameItem(), ClassEditorWidget::renameNamespace(), SaveThemeDialog::saveTheme(), and yesNo().
KVIRC_API void KviMessageBox::warning (QString fmt, ...)
References kvi_va_end, kvi_va_list, kvi_va_start, s, and KviQString::vsprintf().
Referenced by SetupWizard::accept(), AliasEditorWidget::aliasRefresh(), AliasEditorWidget::askForAliasName(), AliasEditorWidget::askForNamespaceName(), ClassEditorWidget::askForNamespaceName(), OptionsWidget_identityAvatar::chooseAvatar(), FileTransferWindow::clearAll(), KviConsoleWindow::closeEvent(), KviMainWindow::closeEvent(), FileTransferWindow::deleteLocalFile(), KviMircServersIniImport::doImport(), OptionsWidget_identityProfile::editProfileOkPressed(), ActionEditor::exportActions(), AliasEditorWidget::exportAliases(), EventEditor::exportAllEvents(), RawEditorWidget::exportAllEvents(), ClassEditorWidget::exportClasses(), RegisteredUsersDialog::exportClicked(), EventEditor::exportCurrentHandler(), RawEditorWidget::exportCurrentHandler(), PopupEditorWidget::exportCurrentPopup(), ListWindow::exportList(), PopupEditorWidget::exportPopups(), AliasEditorWidget::exportSelectionInSinglesFiles(), ClassEditorWidget::exportSelectionInSinglesFiles(), CustomizeToolBarsDialog::exportToolBar(), KviIrcViewToolWidget::filterLoad(), KviIrcViewToolWidget::filterSave(), KviApplication::findGlobalKvircDirectory(), RegisteredUsersDialog::importClicked(), OptionsWidget_servers::importPopupActivated(), KviKvsCoreSimpleCommands::init(), AddonFunctions::installAddonPackage(), KviConsoleWindow::ircUriChanged(), ScriptEditorImplementation::loadFromFile(), SharedFileEditDialog::okClicked(), KviKvsParser::parseSpecialCommandBreak(), PopupEditorWidget::popupRefresh(), SetupWizard::reject(), UrlDialog::remove(), BanFrame::removeBan(), KviDefaultScriptManager::restore(), KviApplication::saveOptions(), ScriptEditorImplementation::saveToFile(), UrlDialog::sayToWin(), KviApplication::setupBegin(), KviApplication::setupFinish(), HelpWindow::startSearch(), and NickServRuleEditor::validate().
KVIRC_API bool KviMessageBox::yesNo (const QString & caption, QString fmt, ...)
References KviControlCodes::Escape, information(), kvi_va_end, kvi_va_list, kvi_va_start, s, and KviQString::vsprintf().
Referenced by ThemeManagementDialog::applyCurrentTheme(), ThemeManagementDialog::deleteTheme(), and dialog_kvs_fnc_yesno().