KVIrc: KviKvs Namespace Reference
KviKvs Namespace Reference
Functions
void clearAliases ()
void clearAppEvents ()
void clearPopups ()
void clearRawEvents ()
void clearScriptAddons ()
void done ()
void flushUserClasses ()
void init ()
void loadAliases (const QString &szFileName)
void loadAppEvents (const QString &szFileName)
void loadPopups (const QString &szFileName)
void loadRawEvents (const QString &szFileName)
void loadScriptAddons (const QString &szFileName)
void saveAliases (const QString &szFileName)
void saveAppEvents (const QString &szFileName)
void savePopups (const QString &szFileName)
void saveRawEvents (const QString &szFileName)
void saveScriptAddons (const QString &szFileName)
Function Documentation
void KviKvs::clearAliases ()
References KviKvsAliasManager::clear(), and KviKvsAliasManager::instance().
Referenced by KviDefaultScriptManager::restoreInternal().
void KviKvs::clearAppEvents ()
References KviKvsEventManager::instance(), and KviKvsEventManager::removeAllScriptAppHandlers().
Referenced by KviDefaultScriptManager::restoreInternal().
void KviKvs::clearPopups ()
References KviKvsPopupManager::clear(), and KviKvsPopupManager::instance().
Referenced by KviDefaultScriptManager::restoreInternal().
void KviKvs::clearRawEvents ()
References KviKvsEventManager::instance(), and KviKvsEventManager::removeAllScriptRawHandlers().
Referenced by KviDefaultScriptManager::restoreInternal().
void KviKvs::clearScriptAddons ()
References KviKvsScriptAddonManager::clear(), and KviKvsScriptAddonManager::instance().
Referenced by KviDefaultScriptManager::restoreInternal().
void KviKvs::done ()
Referenced by KviCustomToolBar::childEvent(), KviWindow::toggleCryptController(), KviChannelWindow::toggleModeEditor(), DccBroker::~DccBroker(), and KviApplication::~KviApplication().
void KviKvs::flushUserClasses ()
References KviKvsObjectController::flushUserClasses(), KviKvsKernel::instance(), and KviKvsKernel::objectController().
Referenced by KviApplication::saveConfiguration().
void KviKvs::init ()
void KviKvs::loadAliases (const QString & szFileName)
References KviKvsAliasManager::instance(), and KviKvsAliasManager::load().
Referenced by KviApplication::setup().
void KviKvs::loadAppEvents (const QString & szFileName)
References KviKvsEventManager::instance(), and KviKvsEventManager::loadAppEvents().
Referenced by KviApplication::setup().
void KviKvs::loadPopups (const QString & szFileName)
References KviKvsPopupManager::instance(), and KviKvsPopupManager::load().
Referenced by KviApplication::setup().
void KviKvs::loadRawEvents (const QString & szFileName)
References KviKvsEventManager::instance(), and KviKvsEventManager::loadRawEvents().
Referenced by KviApplication::setup().
void KviKvs::loadScriptAddons (const QString & szFileName)
References KviKvsScriptAddonManager::instance(), and KviKvsScriptAddonManager::load().
Referenced by KviApplication::setup().
void KviKvs::saveAliases (const QString & szFileName)
References KviKvsAliasManager::instance(), and KviKvsAliasManager::save().
void KviKvs::saveAppEvents (const QString & szFileName)
References KviKvsEventManager::instance(), and KviKvsEventManager::saveAppEvents().
void KviKvs::savePopups (const QString & szFileName)
References KviKvsPopupManager::instance(), and KviKvsPopupManager::save().
void KviKvs::saveRawEvents (const QString & szFileName)
References KviKvsEventManager::instance(), and KviKvsEventManager::saveRawEvents().
void KviKvs::saveScriptAddons (const QString & szFileName)
References KviKvsScriptAddonManager::instance(), and KviKvsScriptAddonManager::save().