KVIrc: UglyBase64 Namespace Reference
UglyBase64 Namespace Reference
Functions
void byteswap_buffer (unsigned char *p, int len)
void decode (KviCString &szText, unsigned char **buf, int *len)
void encode (const unsigned char *out, const int len, KviCString &szText)
unsigned int fake_base64dec (unsigned char c)
Variables
static unsigned char fake_base64 [] = "./0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
Function Documentation
void UglyBase64::byteswap_buffer (unsigned char * p, int len)
Referenced by decode(), and encode().
void UglyBase64::decode (KviCString & szText, unsigned char ** buf, int * len)
References KviMemory::allocate(), byteswap_buffer(), e, fake_base64dec(), i, KviCString::len(), p, KviCString::ptr(), and KviCString::setLen().
void UglyBase64::encode (const unsigned char * out, const int len, KviCString & szText)
References byteswap_buffer(), fake_base64, p, KviCString::ptr(), and KviCString::setLen().
unsigned int UglyBase64::fake_base64dec (unsigned char c)
References c, fake_base64, and i.
Referenced by decode().
Variable Documentation
unsigned char UglyBase64::fake_base64[] = "./0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" [static]
Referenced by encode(), and fake_base64dec().