KVIrc: KviOsInfo Namespace Reference
KviOsInfo Namespace Reference
Functions
QString hostname ()
QString machine ()
QString name ()
QString nodename ()
QString release ()
QString type ()
QString version ()
Function Documentation
KVILIB_API QString KviOsInfo::hostname ()
References KviQString::Empty.
Referenced by UPnP::IgdControlPoint::IgdControlPoint(), KviKvsCoreFunctions::init(), and system_kvs_fnc_hostname().
KVILIB_API QString KviOsInfo::machine ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), and system_kvs_fnc_osmachine().
KVILIB_API QString KviOsInfo::name ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), KviThemedLineEdit::applyOptions(), KviThemedTreeWidget::applyOptions(), KviThemedComboBox::applyOptions(), KviThemedLabel::applyOptions(), KviKvsObject::callFunction(), KviTextIconManager::checkDefaultAssociations(), KviChannelWindow::closeEvent(), KviHtmlGenerator::convertToHtml(), KviKvsObject::emitSignal(), EventEditor::eventHandlerDisabled(), Kopete::AV::VideoDevicePool::fillInputQComboBox(), KviKvsEventManager::findAppEventByName(), KviKvsEventManager::findAppEventIndexByName(), ClassEditorWidget::findFunction(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), KviKvsObject::function_className(), KviChannelWindow::getConfigGroupName(), KviIrcSocket::getLocalHostIp(), KviKvsCoreFunctions::KVSCF(), KviIrcConnection::linkEstabilished(), KviTheme::load(), KviKvsEventManager::loadAppEvents(), ActionEditor::newAction(), RegisteredUserEntryDialog::okClicked(), EventEditor::oneTimeSetup(), RawEditorWidget::oneTimeSetup(), KviChannelWindow::ownAction(), KviChannelWindow::ownMessage(), KviIrcServerParser::parseCtcpRequestVersion(), KviKvsEventManager::removeScriptAppHandler(), KviKvsEventManager::removeScriptRawHandler(), KviTheme::save(), KviKvsEventManager::saveAppEvents(), Kopete::AV::VideoDevicePool::saveCurrentDeviceConfig(), ClassEditorWidget::saveNotBuiltClasses(), KviKvsEventManager::saveRawEvents(), KviApplication::setOptionValue(), KvsObject_http::slotRequestFinished(), system_kvs_fnc_osname(), theme_kvs_fnc_info(), KviChannelWindow::topicSelected(), and torrent_module_init().
KVILIB_API QString KviOsInfo::nodename ()
References KviQString::Empty.
Referenced by system_kvs_fnc_osnodename().
KVILIB_API QString KviOsInfo::release ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), KviIrcServerParser::parseCtcpRequestVersion(), and system_kvs_fnc_osrelease().
KVILIB_API QString KviOsInfo::type ()
Referenced by AliasEditorWidget::appendAllItems(), AliasEditorWidget::appendAllItemsRecursive(), dccModuleCtcpDccParseRoutine(), RegisteredUsersDialog::exportClicked(), KviIrcMessageCheckListItem::KviIrcMessageCheckListItem(), KviKvsCoreSimpleCommands::KVSCSC(), KviProxyDataBase::load(), KviKvsPopupMenu::load(), KviTextBrowser::loadResource(), KviDnsResolver::lookup(), KviIrcServerParser::parseCtcpRequestAction(), KviProxyDataBase::save(), KviDnsResolverThread::setQuery(), Kopete::AV::VideoDevice::startCapturing(), KviImageDialog::startJob(), Kopete::AV::VideoDevice::stopCapturing(), and system_kvs_fnc_ostype().
KVILIB_API QString KviOsInfo::version ()
References KviQString::Empty.
Referenced by AboutDialog::AboutDialog(), KviKvsCoreFunctions::init(), KviOggIrcText::irct_decode_headerin(), KviBasicIrcServerInfo::KviBasicIrcServerInfo(), KviIrcServerParser::parseCtcpRequestSource(), KviIrcServerParser::parseCtcpRequestVersion(), KviIrcServerParser::parseNumeric004(), system_kvs_fnc_osversion(), and theme_kvs_fnc_info().