KVIrc: KviKvsCoreFunctions Namespace Reference
KviKvsCoreFunctions Namespace Reference
Functions
static QString g_szStaticStrayConstantAt ("@")
home hellvis69 Progetti KVIrc
svn trunk kvirc src kvirc kvs
KviKvsCoreFunctions cpp void init ()
KVSCF (version)
KVSCF (username)
KVSCF (unserialize)
KVSCF (unixtime)
KVSCF (unicode)
KVSCF (uflags)
KVSCF (u)
KVSCF (typeofCKEYWORDWORKAROUND)
KVSCF (trueCKEYWORDWORKAROUND)
KVSCF (tr)
KVSCF (timeCFUNCTIONWORKAROUND)
KVSCF (thisCKEYWORDWORKAROUND)
KVSCF (target)
KVSCF (sw)
KVSCF (string)
KVSCF (split)
KVSCF (sort)
KVSCF (server)
KVSCF (serialize)
KVSCF (sentBytes)
KVSCF (selected)
KVSCF (rsort)
KVSCF (receivedBytes)
KVSCF (realname)
KVSCF (real)
KVSCF (rand)
KVSCF (r)
KVSCF (query)
KVSCF (option)
KVSCF (o)
KVSCF (nullCKEYWORDWORKAROUND)
KVSCF (nothing)
KVSCF (newCKEYWORDWORKAROUND)
KVSCF (msgtype)
KVSCF (me)
KVSCF (mask)
KVSCF (listtimers)
KVSCF (link)
KVSCF (lf)
KVSCF (length)
KVSCF (lang)
KVSCF (lag)
KVSCF (keys)
KVSCF (k)
KVSCF (isWellKnown)
KVSCF (isTimer)
KVSCF (isSet)
KVSCF (isMainWindowMinimized)
KVSCF (isMainWindowActive)
KVSCF (isMeVoice)
KVSCF (isMeHalfOp)
KVSCF (isMeUserOp)
KVSCF (isMeOp)
KVSCF (isNumeric)
KVSCF (isEventEnabled)
KVSCF (isEmpty)
KVSCF (isAnyConsoleConnected)
KVSCF (integer)
KVSCF (iconName)
KVSCF (icon)
KVSCF (hptimestamp)
KVSCF (hostname)
KVSCF (hexToAscii)
KVSCF (inputText)
KVSCF (hash)
KVSCF (globals)
KVSCF (fmtlink)
KVSCF (flatten)
KVSCF (firstConnectedConsole)
KVSCF (features)
KVSCF (falseCKEYWORDWORKAROUND)
KVSCF (escape)
KVSCF (date)
KVSCF (cr)
KVSCF (countStatusBarItems)
KVSCF (context)
KVSCF (console)
KVSCF (classDefined)
KVSCF (charCKEYWORDWORKAROUND)
KVSCF (channel)
KVSCF (certificate)
KVSCF (boolean)
KVSCF (base64ToAscii)
KVSCF (b)
KVSCF (away)
KVSCF (avatar)
KVSCF (asciiToHex)
KVSCF (asciiToBase64)
KVSCF (array)
KVSCF (aliasBody)
KVSCF (active)
KVSCF (mightBeStrayAtOrThis)
KVSCF (strayAt)
KVSCF (window)
Function Documentation
static QString KviKvsCoreFunctions::g_szStaticStrayConstantAt ("@") [static]
Referenced by KVSCF().
void KviKvsCoreFunctions::init ()
References _REGFNC, KviOsInfo::hostname(), KviKvsKernel::instance(), k, o, r, u, and KviOsInfo::version().
KviKvsCoreFunctions::KVSCF (version)
References KviBuildInfo::buildDate(), KviBuildInfo::buildRevision(), KviBuildInfo::buildSourcesDate(), KVI_RELEASE_NAME, KVI_VERSION, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (username)
References e, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, and KviIrcUserEntry::user().
KviKvsCoreFunctions::KVSCF (unserialize)
References KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviKvsVariant::unserialize().
KviKvsCoreFunctions::KVSCF (unixtime)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (unicode)
References a, i, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviKvsArray::set().
KviKvsCoreFunctions::KVSCF (uflags)
References e, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, and KviIrcUserEntry::userFlags().
KviKvsCoreFunctions::KVSCF (u)
References KVSCF_pRetBuffer, Q_UNUSED(), and KviMircCntrl::Underline.
KviKvsCoreFunctions::KVSCF (typeofCKEYWORDWORKAROUND)
References KviKvsVariant::getTypeName(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (trueCKEYWORDWORKAROUND)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (tr)
References __tr2qs_ctx_no_xgettext, __tr2qs_no_xgettext, g_pApp, KviApplication::getGlobalKvircDirectory(), KviLocale::getLoadedCatalogue(), KviApplication::getLocalKvircDirectory(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, KviLocale::loadCatalogue(), KviApplication::Locale, and KviMessageCatalogue::translateToQString().
KviKvsCoreFunctions::KVSCF (timeCFUNCTIONWORKAROUND)
KviKvsCoreFunctions::KVSCF (thisCKEYWORDWORKAROUND)
References KviKvsObject::handle(), KVSCF_pContext, KVSCF_pRetBuffer, o, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (target)
References __tr2qs_ctx(), KviApplication::findWindow(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (sw)
References __tr2qs_ctx(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (string)
References KviKvsVariant::asString(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (split)
KviKvsCoreFunctions::KVSCF (sort)
References a, KviKvsArrayCast::array(), KVS_PT_ARRAYCAST, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviKvsArray::sort().
KviKvsCoreFunctions::KVSCF (server)
References __tr2qs_ctx(), KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (serialize)
References KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, KviKvsVariant::serialize(), and szBuffer.
KviKvsCoreFunctions::KVSCF (sentBytes)
References g_uOutgoingTraffic, KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (selected)
References KviKvsScript::evaluate(), KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (rsort)
References a, KviKvsArrayCast::array(), KVS_PT_ARRAYCAST, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviKvsArray::rsort().
KviKvsCoreFunctions::KVSCF (receivedBytes)
References g_uIncomingTraffic, KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (realname)
References e, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, and KviIrcUserEntry::realName().
KviKvsCoreFunctions::KVSCF (real)
References KviKvsVariant::asReal(), KviKvsVariant::castToInteger(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (rand)
References KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (r)
References KVSCF_pRetBuffer, Q_UNUSED(), and KviMircCntrl::Reverse.
KviKvsCoreFunctions::KVSCF (query)
References __tr2qs_ctx(), KviWindow::connection(), KviApplication::findConsole(), KviIrcConnection::findQuery(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, KVSCF_pRetBuffer, and KviWindow::Query.
KviKvsCoreFunctions::KVSCF (option)
References __tr2qs_ctx(), g_pApp, KviApplication::getOptionString(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (o)
References KVSCF_pRetBuffer, Q_UNUSED(), and KviMircCntrl::Reset.
KviKvsCoreFunctions::KVSCF (nullCKEYWORDWORKAROUND)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (nothing)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (newCKEYWORDWORKAROUND)
References __tr2qs_ctx(), KviKvsObject::handle(), KviKvsKernel::instance(), KVS_PF_OPTIONAL, KVS_PT_HOBJECT, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVS_PT_VARIANTLIST, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, KviKvsObjectController::lookupClass(), KviKvsObjectController::lookupObject(), and KviKvsKernel::objectController().
KviKvsCoreFunctions::KVSCF (msgtype)
References KviQString::equalCI(), g_msgtypeOptionsTable, i, KVI_NUM_MSGTYPE_OPTIONS, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviOsInfo::name().
KviKvsCoreFunctions::KVSCF (me)
References __tr2qs_ctx(), KviWindow::DccChat, KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (mask)
References e, KviIrcUserEntry::host(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, KviIrcMask::mask(), KviIrcMask::setHost(), KviIrcMask::setNick(), KviIrcMask::setUsername(), u, and KviIrcUserEntry::user().
KviKvsCoreFunctions::KVSCF (listtimers)
References a, KviPointerHashTableIterator< Key, T >::current(), KviKvsTimerManager::instance(), KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, KVSM_PARAMETER, KviKvsArray::set(), and KviKvsTimerManager::timerDict().
KviKvsCoreFunctions::KVSCF (link)
References KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (lf)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (length)
References KviKvsVariant::array(), KviKvsVariantData::Array, KviKvsVariant::asString(), KviKvsVariant::hash(), KviKvsVariantData::Hash, KviKvsVariantData::HObject, KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, KviKvsHash::size(), KviKvsArray::size(), and KviKvsVariant::type().
KviKvsCoreFunctions::KVSCF (lang)
References KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviLocale::localeName().
KviKvsCoreFunctions::KVSCF (lag)
References __tr2qs_ctx(), KVSCF_pContext, KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (keys)
References a, KviKvsHash::dict(), KVS_PF_OPTIONAL, KVS_PT_HASH, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (k)
References KviQString::appendFormatted(), KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (isWellKnown)
References e, KviIrcUserEntry::hasHost(), KviIrcUserEntry::hasUser(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (isTimer)
References KviKvsTimerManager::instance(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (isSet)
References KviKvsVariant::isEmpty(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (isMainWindowMinimized)
References g_pMainWindow, KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (isMainWindowActive)
References g_pMainWindow, KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (isMeVoice)
KviKvsCoreFunctions::KVSCF (isMeHalfOp)
KviKvsCoreFunctions::KVSCF (isMeUserOp)
KviKvsCoreFunctions::KVSCF (isMeOp)
KviKvsCoreFunctions::KVSCF (isNumeric)
References KviKvsVariant::asNumber(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, n, and v.
KviKvsCoreFunctions::KVSCF (isEventEnabled)
References __tr2qs_ctx(), KviKvsEventManager::findAppEventIndexByName(), KviKvsEventManager::findScriptAppHandler(), KviKvsEventManager::findScriptRawHandler(), h, KviKvsEventManager::instance(), KviKvsScriptEventHandler::isEnabled(), KviKvsEventManager::isValidRawEvent(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (isEmpty)
References KviKvsVariant::isEmpty(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (isAnyConsoleConnected)
KviKvsCoreFunctions::KVSCF (integer)
References KviKvsVariant::castToInteger(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (iconName)
References g_pIconManager, KviIconManager::getSmallIconName(), KviIconManager::IconCount, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (icon)
References g_pIconManager, KviIconManager::getSmallIconIdFromName(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (hptimestamp)
References kvi_gettimeofday(), KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (hostname)
References e, KviIrcUserEntry::host(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (hexToAscii)
References KviCString::freeBuffer(), KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (inputText)
KviKvsCoreFunctions::KVSCF (hash)
References a, KVSCF_pParams, KVSCF_pRetBuffer, Q_UNUSED(), and KviKvsHash::set().
KviKvsCoreFunctions::KVSCF (globals)
References KviKvsKernel::instance(), KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (fmtlink)
References KviQString::appendFormatted(), KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (flatten)
References a, KviKvsVariantData::Array, KviKvsArray::at(), KviKvsHash::dict(), h, KviKvsVariantData::Hash, KVSCF_pParams, KVSCF_pRetBuffer, Q_UNUSED(), KviKvsArray::set(), KviKvsArray::size(), v, and z.
KviKvsCoreFunctions::KVSCF (firstConnectedConsole)
References c, g_pApp, KviWindow::id(), KVSCF_pRetBuffer, Q_UNUSED(), and KviApplication::topmostConnectedConsole().
KviKvsCoreFunctions::KVSCF (features)
References a, KviQString::equalCI(), i, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviKvsArray::set().
KviKvsCoreFunctions::KVSCF (falseCKEYWORDWORKAROUND)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (escape)
References KviQString::escapeKvs(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (date)
References __tr2qs_ctx(), i, KVS_PF_OPTIONAL, KVS_PT_INT, KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (cr)
References KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (countStatusBarItems)
References g_pMainWindow, KVSCF_pRetBuffer, KviMainWindow::mainStatusBar(), and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (context)
References KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (console)
References __tr2qs_ctx(), KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (classDefined)
References KviKvsKernel::instance(), KVS_PT_NONEMPTYSTRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (charCKEYWORDWORKAROUND)
References KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (channel)
References __tr2qs_ctx(), Channel, KviWindow::connection(), KviIrcConnection::findChannel(), KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_NONEMPTYSTRING, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (certificate)
References __tr2qs, __tr2qs_ctx(), f, KVI_OPTION_BOOL, KVI_OPTION_STRING, KviOption_boolUseSSLCertificate, KviOption_stringSSLCertificatePass, KviOption_stringSSLCertificatePath, KVS_PF_OPTIONAL, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pRetBuffer, and NULL.
KviKvsCoreFunctions::KVSCF (boolean)
References KviKvsVariant::castToInteger(), KVS_PT_VARIANT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and v.
KviKvsCoreFunctions::KVSCF (base64ToAscii)
References KviCString::freeBuffer(), KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (b)
References KviMircCntrl::Bold, KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (away)
References __tr2qs_ctx(), KviApplication::findConsole(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (avatar)
KviKvsCoreFunctions::KVSCF (asciiToHex)
References KviCString::bufferToHex(), KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviCString::ptr().
KviKvsCoreFunctions::KVSCF (asciiToBase64)
References KviCString::bufferToBase64(), KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviCString::ptr().
KviKvsCoreFunctions::KVSCF (array)
References a, KVSCF_pParams, KVSCF_pRetBuffer, Q_UNUSED(), KviKvsArray::set(), and v.
KviKvsCoreFunctions::KVSCF (aliasBody)
References KviKvsAliasManager::instance(), KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pRetBuffer, and KviKvsAliasManager::lookup().
KviKvsCoreFunctions::KVSCF (active)
References KviConsoleWindow::activeWindow(), KviApplication::findConsole(), g_pActiveWindow, g_pApp, KVS_PF_OPTIONAL, KVS_PT_UINT, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pParams, and KVSCF_pRetBuffer.
KviKvsCoreFunctions::KVSCF (mightBeStrayAtOrThis)
References g_szStaticStrayConstantAt(), KviKvsObject::handle(), KVSCF_pContext, KVSCF_pRetBuffer, o, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (strayAt)
References g_szStaticStrayConstantAt(), KVSCF_pRetBuffer, and Q_UNUSED().
KviKvsCoreFunctions::KVSCF (window)
References KviApplication::findWindowByCaption(), g_pApp, KVS_PF_OPTIONAL, KVS_PT_INTEGER, KVS_PT_STRING, KVSCF_PARAMETER, KVSCF_PARAMETERS_BEGIN, KVSCF_PARAMETERS_END, KVSCF_pContext, KVSCF_pParams, KVSCF_pRetBuffer, and KviWindow::numericId().