KVIrc: KviTimeUtils Namespace Reference
KviTimeUtils Namespace Reference
Time utilities.
Enumerations
enum FormatTimeSpanFlags { NoLeadingEmptyIntervals = 1, NoLeadingZeroes = 2, FillWithHypens = 4 }
Functions
QString formatTimeInterval (unsigned int uSeconds, int iFlags=0)
Returns a string formatted like x d x h xx m xx s.
long long getCurrentTimeMills ()
Returns the current time mills.
void secondsToDaysHoursMinsSecs (unsigned int uSecs, unsigned int *uD, unsigned int *uH, unsigned int *uM, unsigned int *uS)
Splits the time span uSecs in days, hours, minutes and seconds.
Detailed Description
Time utilities.
Enumeration Type Documentation
enum KviTimeUtils::FormatTimeSpanFlags
Enumerator:
NoLeadingEmptyIntervals
Causes the leading empty intervals to be omitted
NoLeadingZeroes
No leading zeroes are printed in hours and seconds
FillWithHypens
Uses only -- d -- h -- etc.. discards all other flags
Function Documentation
KVILIB_API QString KviTimeUtils::formatTimeInterval (unsigned int uSeconds, int iFlags = 0)
Returns a string formatted like x d x h xx m xx s.
Parameters:
uSeconds The number of seconds to format
iFlags The flags to format the time string
Returns:
QString
References __tr2qs, d, FillWithHypens, h, m, NoLeadingEmptyIntervals, NoLeadingZeroes, s, and secondsToDaysHoursMinsSecs().
Referenced by DccFileTransfer::displayPaint(), KviConsoleWindow::getWindowListTipText(), KviStatusBarConnectionTimer::timerEvent(), and KviStatusBarAwayIndicator::tipText().
KVILIB_API long long KviTimeUtils::getCurrentTimeMills ()
Returns the current time mills.
Returns:
long long
References kvi_gettimeofday().
Referenced by KviAnimatedPixmapCache::internalScheduleFrameChange(), and KviAnimatedPixmapCache::timeoutEvent().
KVILIB_API void KviTimeUtils::secondsToDaysHoursMinsSecs (unsigned int uSecs, unsigned int * uD, unsigned int * uH, unsigned int * uM, unsigned int * uS)
Splits the time span uSecs in days, hours, minutes and seconds.
Parameters:
uSecs The amount of seconds to span
uD Where to store days data
uH Where to store hours data
uM Where to store minutes data
uS Where to store seconds data
Returns:
void
Referenced by HttpFileTransfer::displayPaint(), and formatTimeInterval().