KVIrc: KviHtmlGenerator Namespace Reference
KviHtmlGenerator Namespace Reference
A namespace to handle html-related functions.
Enumerations
enum DefaultColor { Background = 100, Foreground = 101 }
Defines back and foreground colors.
Functions
QString convertToHtml (const QString &szText, bool bEscape=false)
Converts a raw irc message to its html equivalent text.
Detailed Description
A namespace to handle html-related functions.
Enumeration Type Documentation
enum KviHtmlGenerator::DefaultColor
Defines back and foreground colors.
Enumerator
Background
Foreground
Function Documentation
KVIRC_API QString KviHtmlGenerator::convertToHtml (const QString & szText, bool bEscape = false)
Converts a raw irc message to its html equivalent text.
Parameters
szText Const reference to a message text
bEscape Whether to escape chars to HTML entities
Returns
QString
References Background, KviControlCodes::Bold, c, Foreground, g_pIconManager, g_pTextIconManager, KviIconManager::getSmallIconResourceName(), KviControlCodes::getUnicodeColorBytes(), KviControlCodes::Icon, KviTextIcon::id(), KVI_OPTION_BOOL, KVI_OPTION_MIRCCOLOR, KviOption_boolDrawEmoticons, KviTextIconManager::lookupTextIcon(), KviOsInfo::name(), KviControlCodes::NoChange, KviControlCodes::Reset, KviControlCodes::Reverse, KviQString::toHtmlEscaped(), and KviControlCodes::Underline.
Referenced by ChannelTreeWidgetItem::ChannelTreeWidgetItem(), LogViewWindow::createLog(), KviTopicWidget::reset(), KviTopicWidget::setTopic(), NotifierMessage::updateGui(), and KviTopicWidget::updateToolTip().