KVIrc: KviCommandFormatter Namespace Reference
KviCommandFormatter Namespace Reference
Functions
KVILIB_API void addBlockBraces (KviCString &szBuffer)
KVILIB_API void addBlockBraces (QString &szBuffer)
void addLeading (KviCString **pszArray, char c)
void addLeading (QStringList &list, const QChar &c)
void blockFromBuffer (KviCString &szBuffer)
void blockFromBuffer (QString &szBuffer)
void bufferFromBlock (KviCString &szBuffer)
void bufferFromBlock (QString &szBuffer)
svn trunk kvirc src kvilib ext
KviCommandFormatter cpp bool hasLeadingChars (KviCString **pszArray, char c)
bool hasLeadingChars (QStringList &list, const QChar &c)
KVILIB_API bool hasLeadingChars (KviCString *pszArray, char c)
void indent (KviCString &szBuffer)
void indent (QString &szBuffer)
KVILIB_API void trimBlockBraces (QString &szBuffer)
KVILIB_API void trimBlockBraces (KviCString &szBuffer)
void trimLeading (KviCString **pszArray)
void trimLeading (QStringList &list)
void unindent (QString &szBuffer)
void unindent (KviCString &szBuffer)
Function Documentation
KVILIB_API void KviCommandFormatter::addBlockBraces (KviCString & szBuffer)
KVILIB_API void KviCommandFormatter::addBlockBraces (QString & szBuffer)
KVILIB_API void KviCommandFormatter::addLeading (KviCString ** pszArray, char c)
Referenced by indent().
KVILIB_API void KviCommandFormatter::addLeading (QStringList & list, const QChar & c)
KVILIB_API void KviCommandFormatter::blockFromBuffer (KviCString & szBuffer)
References KviCString::append(), KviCString::ensureLastCharIs(), indent(), KviCString::prepend(), and KviCString::stripRightWhiteSpace().
Referenced by ClassEditorWidget::exportClassBuffer(), KviKvsUserAction::exportToKvs(), KviKvsPopupMenu::generateDefPopup(), KviKvsPopupMenu::generateDefPopupCore(), AliasEditorWidget::getExportAliasBuffer(), RawEditorWidget::getExportEventBuffer(), EventEditor::getExportEventBuffer(), and KviKvsObjectClass::save().
KVILIB_API void KviCommandFormatter::blockFromBuffer (QString & szBuffer)
References KviQString::ensureLastCharIs(), indent(), and KviQString::stripRightWhiteSpace().
KVILIB_API void KviCommandFormatter::bufferFromBlock (KviCString & szBuffer)
References KviCString::cutLeft(), KviCString::cutRight(), KviCString::lastCharIs(), KviCString::ptr(), KviCString::trim(), and unindent().
Referenced by KviKvsParser::parseCommand(), KviKvsParser::parseSpecialCommandClass(), and KviKvsParser::parseSpecialCommandDefpopupLabelPopup().
KVILIB_API void KviCommandFormatter::bufferFromBlock (QString & szBuffer)
References unindent().
svn trunk kvirc src kvilib ext KviCommandFormatter cpp bool KviCommandFormatter::hasLeadingChars (KviCString ** pszArray, char c)
References KviCString::hasData(), and KviCString::trim().
Referenced by unindent().
KVILIB_API bool KviCommandFormatter::hasLeadingChars (QStringList & list, const QChar & c)
References c.
KVILIB_API bool KviCommandFormatter::hasLeadingChars (KviCString * pszArray, char c)
KVILIB_API void KviCommandFormatter::indent (KviCString & szBuffer)
References addLeading(), KviCString::freeArray(), KviCString::joinFromArray(), and KviCString::splitToArray().
Referenced by blockFromBuffer(), EventEditor::currentItemChanged(), ClassEditorWidget::exportClassBuffer(), and KviKvsObjectClass::save().
KVILIB_API void KviCommandFormatter::indent (QString & szBuffer)
References addLeading().
KVILIB_API void KviCommandFormatter::trimBlockBraces (QString & szBuffer)
KVILIB_API void KviCommandFormatter::trimBlockBraces (KviCString & szBuffer)
KVILIB_API void KviCommandFormatter::trimLeading (KviCString ** pszArray)
Referenced by unindent().
KVILIB_API void KviCommandFormatter::trimLeading (QStringList & list)
KVILIB_API void KviCommandFormatter::unindent (QString & szBuffer)
References hasLeadingChars(), and trimLeading().
KVILIB_API void KviCommandFormatter::unindent (KviCString & szBuffer)
References KviCString::freeArray(), hasLeadingChars(), KviCString::joinFromArray(), KviCString::splitToArray(), and trimLeading().
Referenced by bufferFromBlock().