KVIrc: src/modules/dcc/requests.cpp File Reference
src/modules/dcc/requests.cpp File Reference
#include "DccVoiceGsmCodec.h"
#include "DccBroker.h"
#include "DccVideoWindow.h"
#include "DccVoiceWindow.h"
#include "DccUtils.h"
#include "DccFileTransfer.h"
#include "kvi_debug.h"
#include "kvi_settings.h"
#include "KviCString.h"
#include "KviModule.h"
#include "KviIrcServerParser.h"
#include "KviLocale.h"
#include "kvi_out.h"
#include "KviConsoleWindow.h"
#include "KviNetUtils.h"
#include "KviMainWindow.h"
#include "KviError.h"
#include "KviOptions.h"
#include "kvi_defaults.h"
#include "KviSharedFilesManager.h"
#include "KviMircCntrl.h"
#include "KviApplication.h"
#include "KviIrcConnection.h"
#include "KviIrcConnectionUserInfo.h"
#include <QFileInfo>
Classes
struct _dccParseProcEntry
Defines
#define _KVI_DEBUG_CHECK_RANGE_
#define KVI_NUM_KNOWN_DCC_TYPES 28
Typedefs
typedef void(* dccParseProc)(KviDccRequest *)
typedef struct _dccParseProcEntry dccParseProcEntry
Functions
static void dcc_fill_local_nick_user_host (DccDescriptor *d, KviDccRequest *dcc)
static bool dcc_module_check_concurrent_transfers_limit (KviDccRequest *dcc)
static bool dcc_module_check_limits (KviDccRequest *dcc)
static bool dcc_module_normalize_target_data (KviDccRequest *dcc, KviCString &ipaddr, KviCString &port)
static void dcc_module_reply_errmsg (KviDccRequest *dcc, const QString &errText)
static void dcc_module_request_error (KviDccRequest *dcc, const QString &errText)
static void dcc_module_set_dcc_type (DccDescriptor *d, const char *szBaseType)
KVIMODULEEXPORTFUNC void dccModuleCtcpDccParseRoutine (KviDccRequest *dcc)
static void dccModuleParseDccAccept (KviDccRequest *dcc)
static void dccModuleParseDccCanvas (KviDccRequest *dcc)
static void dccModuleParseDccChat (KviDccRequest *dcc)
static void dccModuleParseDccGet (KviDccRequest *dcc)
static void dccModuleParseDccList (KviDccRequest *)
static void dccModuleParseDccRecv (KviDccRequest *dcc)
static void dccModuleParseDccResume (KviDccRequest *dcc)
static void dccModuleParseDccRSend (KviDccRequest *dcc)
static void dccModuleParseDccSend (KviDccRequest *dcc)
static void dccModuleParseDccVideo (KviDccRequest *dcc)
static void dccModuleParseDccVoice (KviDccRequest *dcc)
Variables
static dccParseProcEntry dccParseProcTable [KVI_NUM_KNOWN_DCC_TYPES]
DccBroker * g_pDccBroker
KVIRC_API KviSharedFilesManager * g_pSharedFilesManager
Define Documentation
#define _KVI_DEBUG_CHECK_RANGE_
#define KVI_NUM_KNOWN_DCC_TYPES 28
Referenced by dccModuleCtcpDccParseRoutine().
Typedef Documentation
typedef void(* dccParseProc)(KviDccRequest *)
typedef struct _dccParseProcEntry dccParseProcEntry
Function Documentation
static void dcc_fill_local_nick_user_host (DccDescriptor * d, KviDccRequest * dcc) [static]
References __tr2qs_ctx(), __tr_ctx, KviWindow::connection(), KviIrcConnectionUserInfo::hostName(), KviIrcConnectionUserInfo::nickName(), _KviDccRequest::pConsole, DccDescriptor::szLocalHost, DccDescriptor::szLocalNick, DccDescriptor::szLocalUser, KviIrcConnection::userInfo(), and KviIrcConnectionUserInfo::userName().
Referenced by dccModuleParseDccCanvas(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), and dccModuleParseDccVoice().
static bool dcc_module_check_concurrent_transfers_limit (KviDccRequest * dcc) [static]
References __tr2qs_ctx(), dcc_module_request_error(), KVI_OPTION_UINT, KviOption_uintMaxDccSendTransfers, and DccFileTransfer::runningTransfersCount().
Referenced by dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), and dccModuleParseDccSend().
static bool dcc_module_check_limits (KviDccRequest * dcc) [static]
References __tr2qs_ctx(), dcc_module_request_error(), DccBroker::dccBoxCount(), DccBroker::dccWindowsCount(), KVI_OPTION_UINT, and KviOption_uintMaxDccSlots.
Referenced by dccModuleParseDccCanvas(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), and dccModuleParseDccVoice().
static bool dcc_module_normalize_target_data (KviDccRequest * dcc, KviCString & ipaddr, KviCString & port) [static]
References __tr2qs_ctx(), KviNetUtils::binaryIpToStringIp(), _KviDccRequest::bIPv6, _KviDccRequest::ctcpMsg, dcc_module_request_error(), KviIrcMessage::haltOutput(), KviCString::isUnsignedNum(), _KviCtcpMessage::msg, KviCString::ptr(), KviNetUtils::stringIpToBinaryIp(), and KviCString::toULong().
Referenced by dccModuleParseDccCanvas(), dccModuleParseDccChat(), dccModuleParseDccRecv(), dccModuleParseDccSend(), dccModuleParseDccVideo(), and dccModuleParseDccVoice().
static void dcc_module_reply_errmsg (KviDccRequest * dcc, const QString & errText) [static]
References KviWindow::connection(), KviIrcMessage::console(), _KviDccRequest::ctcpMsg, KviIrcConnection::encodeText(), _KviCtcpMessage::msg, KviIrcMask::nick(), _KviCtcpMessage::pSource, and KviIrcConnection::sendFmtData().
Referenced by dcc_module_request_error().
static void dcc_module_request_error (KviDccRequest * dcc, const QString & errText) [static]
References __tr2qs_ctx(), KviIrcMessage::console(), _KviDccRequest::ctcpMsg, dcc_module_reply_errmsg(), KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KviOption_boolNotifyFailedDccHandshakes, _KviCtcpMessage::msg, KviWindow::output(), KviCString::ptr(), and _KviDccRequest::szType.
Referenced by dcc_module_check_concurrent_transfers_limit(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dccModuleCtcpDccParseRoutine(), dccModuleParseDccAccept(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccResume(), dccModuleParseDccRSend(), and dccModuleParseDccSend().
static void dcc_module_set_dcc_type (DccDescriptor * d, const char * szBaseType) [static]
References DccDescriptor::bIsTdcc, and DccDescriptor::szType.
Referenced by dccModuleParseDccCanvas(), dccModuleParseDccChat(), dccModuleParseDccGet(), dccModuleParseDccRecv(), dccModuleParseDccRSend(), dccModuleParseDccSend(), dccModuleParseDccVideo(), and dccModuleParseDccVoice().
KVIMODULEEXPORTFUNC void dccModuleCtcpDccParseRoutine (KviDccRequest * dcc)
References __tr2qs_ctx(), _KviDccRequest::ctcpMsg, dcc_module_request_error(), KviIrcMessage::haltOutput(), i, KVI_NUM_KNOWN_DCC_TYPES, kvi_strEqualCS(), _KviCtcpMessage::msg, _dccParseProcEntry::proc, KviCString::ptr(), _KviDccRequest::szType, KviCString::toUpper(), and KviOsInfo::type().
static void dccModuleParseDccAccept (KviDccRequest * dcc) [static]
References __tr2qs_ctx(), _KviDccRequest::ctcpMsg, dcc_module_request_error(), KviIrcMessage::haltOutput(), DccBroker::handleResumeAccepted(), _KviCtcpMessage::msg, KviCString::ptr(), _KviDccRequest::szParam1, _KviDccRequest::szParam2, and _KviDccRequest::szParam4.
static void dccModuleParseDccCanvas (KviDccRequest * dcc) [static]
References DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bOverrideMinimize, _KviDccRequest::ctcpMsg, d, dcc_fill_local_nick_user_host(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_set_dcc_type(), KviIrcMask::host(), KVI_OPTION_BOOL, KviOption_boolAutoAcceptDccCanvas, KviIrcMask::nick(), _KviDccRequest::pConsole, _KviCtcpMessage::pSource, KviCString::ptr(), DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szNick, _KviDccRequest::szParam2, _KviDccRequest::szParam3, DccDescriptor::szPort, DccDescriptor::szUser, and DccDescriptor::triggerCreationEvent().
static void dccModuleParseDccChat (KviDccRequest * dcc) [static]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::console(), KviIrcMessage::console(), KviCString::contains(), _KviDccRequest::ctcpMsg, KviCString::cutRight(), d, dcc_fill_local_nick_user_host(), dcc_kvs_get_listen_ip_address(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_request_error(), dcc_module_set_dcc_type(), DccBroker::findZeroPortTag(), KviIrcMessage::haltOutput(), DccBroker::handleChatRequest(), KviCString::hasData(), KviIrcMask::host(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_DCCMSG, kvi_strEqualCI(), KviOption_boolAutoAcceptDccChat, KviOption_boolDccSendFakeAddressByDefault, KviOption_stringDefaultDccFakeAddress, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviDccRequest::pConsole, _KviCtcpMessage::pSource, KviCString::ptr(), DccBroker::removeZeroPortTag(), DccDescriptor::setZeroPortRequestTag(), DccDescriptor::szFakeIp, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, DccDescriptor::szPort, _KviDccRequest::szType, DccDescriptor::szUser, t, DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
static void dccModuleParseDccGet (KviDccRequest * dcc) [static]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs_ctx(), __tr_ctx, KviSharedFile::absFilePath(), KviSharedFilesManager::addSharedFile(), DccDescriptor::bActive, DccDescriptor::bDoTimeout, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bOverrideMinimize, DccDescriptor::bRecvFile, DccDescriptor::bSendRequest, KviWindow::connection(), DccDescriptor::console(), KviIrcMessage::console(), KviCString::contains(), _KviDccRequest::ctcpMsg, KviCString::cutRight(), d, dcc_fill_local_nick_user_host(), dcc_kvs_get_listen_ip_address(), dcc_module_check_concurrent_transfers_limit(), dcc_module_check_limits(), dcc_module_request_error(), dcc_module_set_dcc_type(), KviWindow::decodeText(), KviIrcConnection::encodeText(), KviSharedFile::fileSize(), g_pSharedFilesManager, KviIrcMessage::haltOutput(), KviIrcMask::host(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_DCCMSG, KviOption_boolCantAcceptIncomingDccConnections, KviOption_boolDccSendFakeAddressByDefault, KviOption_stringDefaultDccFakeAddress, KviSharedFilesManager::lookupSharedFile(), KviIrcMask::mask(), _KviCtcpMessage::msg, KviSharedFile::name(), KviIrcMask::nick(), KviIrcMask::NickUserHost, o, KviWindow::output(), _KviDccRequest::pConsole, KviCString::prepend(), _KviCtcpMessage::pSource, KviCString::ptr(), DccBroker::sendFileExecute(), KviIrcConnection::sendFmtData(), DccDescriptor::szFakeIp, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szLocalFileName, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, DccDescriptor::szPort, DccDescriptor::szType, _KviDccRequest::szType, DccDescriptor::szUser, KviCString::toUInt(), DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
static void dccModuleParseDccList (KviDccRequest *) [static]
static void dccModuleParseDccRecv (KviDccRequest * dcc) [static]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs_ctx(), KviSharedFile::absFilePath(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bDoTimeout, DccDescriptor::bIsIncomingAvatar, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, KviMircCntrl::Bold, DccDescriptor::bOverrideMinimize, DccDescriptor::bRecvFile, KviIrcMessage::console(), KviCString::contains(), _KviDccRequest::ctcpMsg, KviCString::cutRight(), KviCString::cutToLast(), d, dcc_fill_local_nick_user_host(), dcc_module_check_concurrent_transfers_limit(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_request_error(), dcc_module_set_dcc_type(), KviSharedFile::fileSize(), g_pSharedFilesManager, KviIrcMessage::haltOutput(), KviIrcMask::host(), KviCString::isUnsignedNum(), KVI_OUT_DCCMSG, KviSharedFilesManager::lookupSharedFile(), _KviCtcpMessage::msg, KviIrcMask::nick(), o, KviWindow::output(), KviWindow::outputNoFmt(), _KviDccRequest::pConsole, KviCString::prepend(), _KviCtcpMessage::pSource, KviCString::ptr(), DccBroker::sendFileExecute(), DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szLocalFileName, DccDescriptor::szLocalFileSize, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, DccDescriptor::szPort, _KviDccRequest::szType, DccDescriptor::szUser, KviCString::toUInt(), DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
Referenced by dccModuleParseDccSend().
static void dccModuleParseDccResume (KviDccRequest * dcc) [static]
References __tr2qs_ctx(), _KviDccRequest::ctcpMsg, dcc_module_request_error(), KviIrcMessage::haltOutput(), DccBroker::handleResumeRequest(), _KviCtcpMessage::msg, KviCString::ptr(), _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, and KviCString::toULongLong().
static void dccModuleParseDccRSend (KviDccRequest * dcc) [static]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs_ctx(), __tr_ctx, DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsIncomingAvatar, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bOverrideMinimize, DccDescriptor::bRecvFile, DccDescriptor::bResume, DccDescriptor::bSendRequest, DccDescriptor::console(), KviIrcMessage::console(), KviCString::contains(), _KviDccRequest::ctcpMsg, KviCString::cutRight(), KviCString::cutToLast(), d, dcc_fill_local_nick_user_host(), dcc_kvs_get_listen_ip_address(), dcc_module_check_concurrent_transfers_limit(), dcc_module_check_limits(), dcc_module_request_error(), dcc_module_set_dcc_type(), KviWindow::decodeText(), KviApplication::findPendingAvatarChange(), g_pApp, KviIrcMessage::haltOutput(), KviIrcMask::host(), KviCString::isUnsignedNum(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_DCCMSG, KviOption_boolAutoAcceptDccSend, KviOption_boolAutoAcceptIncomingAvatars, KviOption_boolDccSendFakeAddressByDefault, KviOption_stringDefaultDccFakeAddress, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviDccRequest::pConsole, _KviCtcpMessage::pSource, KviCString::ptr(), DccBroker::recvFileManage(), DccDescriptor::szFakeIp, DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, DccDescriptor::szPort, _KviDccRequest::szType, DccDescriptor::szUser, DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
static void dccModuleParseDccSend (KviDccRequest * dcc) [static]
COMPILE_SSL_SUPPORT
COMPILE_SSL_SUPPORT
References __tr2qs_ctx(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsIncomingAvatar, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bOverrideMinimize, DccDescriptor::bRecvFile, DccDescriptor::bResume, DccDescriptor::bSendRequest, DccDescriptor::console(), KviIrcMessage::console(), KviCString::contains(), _KviDccRequest::ctcpMsg, KviCString::cutRight(), KviCString::cutToLast(), d, dcc_fill_local_nick_user_host(), dcc_kvs_get_listen_ip_address(), dcc_module_check_concurrent_transfers_limit(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_request_error(), dcc_module_set_dcc_type(), dccModuleParseDccRecv(), KviWindow::decodeText(), KviApplication::findPendingAvatarChange(), DccBroker::findZeroPortTag(), g_pApp, KviIrcMessage::haltOutput(), KviCString::hasData(), KviIrcMask::host(), KviCString::isUnsignedNum(), DccDescriptor::isZeroPortRequest(), KVI_OPTION_BOOL, KVI_OPTION_STRING, KVI_OUT_DCCMSG, kvi_strEqualCS(), KviOption_boolAutoAcceptDccSend, KviOption_boolAutoAcceptIncomingAvatars, KviOption_boolDccSendFakeAddressByDefault, KviOption_stringDefaultDccFakeAddress, KviDccZeroPortTag::m_uResumePosition, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviDccRequest::pConsole, _KviCtcpMessage::pSource, KviCString::ptr(), DccBroker::recvFileManage(), DccBroker::removeZeroPortTag(), DccDescriptor::setZeroPortRequestTag(), KviCString::sprintf(), DccDescriptor::szFakeIp, DccDescriptor::szFileName, DccDescriptor::szFileSize, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szListenIp, DccDescriptor::szListenPort, DccDescriptor::szLocalFileSize, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, _KviDccRequest::szParam5, DccDescriptor::szPort, _KviDccRequest::szType, DccDescriptor::szUser, t, DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
static void dccModuleParseDccVideo (KviDccRequest * dcc) [static]
References __tr2qs_ctx(), DccBroker::activeVideoManage(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bOverrideMinimize, KviIrcMessage::console(), _KviDccRequest::ctcpMsg, d, dcc_fill_local_nick_user_host(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_set_dcc_type(), KviIrcMessage::haltOutput(), KviIrcMask::host(), kvi_dcc_video_is_valid_codec(), KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KviOption_boolAutoAcceptDccVideo, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviDccRequest::pConsole, _KviCtcpMessage::pSource, KviCString::ptr(), DccDescriptor::szCodec, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, DccDescriptor::szPort, DccDescriptor::szUser, DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
static void dccModuleParseDccVoice (KviDccRequest * dcc) [static]
References __tr2qs_ctx(), DccBroker::activeVoiceManage(), DccDescriptor::bActive, DccDescriptor::bAutoAccept, DccDescriptor::bIsTdcc, DccDescriptor::bNoAcks, DccDescriptor::bOverrideMinimize, KviIrcMessage::console(), _KviDccRequest::ctcpMsg, d, dcc_fill_local_nick_user_host(), dcc_module_check_limits(), dcc_module_normalize_target_data(), dcc_module_set_dcc_type(), KviIrcMessage::haltOutput(), KviIrcMask::host(), DccDescriptor::iSampleRate, kvi_dcc_voice_is_valid_codec(), KVI_OPTION_BOOL, KVI_OUT_DCCERROR, KVI_OUT_DCCMSG, KviOption_boolAutoAcceptDccVoice, _KviCtcpMessage::msg, KviIrcMask::nick(), KviWindow::output(), _KviDccRequest::pConsole, _KviCtcpMessage::pSource, KviCString::ptr(), DccDescriptor::szCodec, DccDescriptor::szHost, DccDescriptor::szIp, DccDescriptor::szNick, _KviDccRequest::szParam1, _KviDccRequest::szParam2, _KviDccRequest::szParam3, _KviDccRequest::szParam4, DccDescriptor::szPort, DccDescriptor::szUser, KviCString::toInt(), DccDescriptor::triggerCreationEvent(), and KviIrcMask::user().
Variable Documentation
dccParseProcEntry dccParseProcTable[KVI_NUM_KNOWN_DCC_TYPES] [static]
DccBroker* g_pDccBroker
KVIRC_API KviSharedFilesManager* g_pSharedFilesManager