KVIrc: src/modules/editor/ScriptEditorImplementation.cpp File Reference
src/modules/editor/ScriptEditorImplementation.cpp File Reference
#include "ScriptEditorImplementation.h"
#include "KviFileUtils.h"
#include "kvi_fileextensions.h"
#include "KviLocale.h"
#include "KviFileDialog.h"
#include "KviQString.h"
#include "KviConfigurationFile.h"
#include "KviModule.h"
#include "KviPointerList.h"
#include "KviApplication.h"
#include "KviConsoleWindow.h"
#include "KviWindow.h"
#include "KviIconManager.h"
#include "KviKvsKernel.h"
#include "KviModuleManager.h"
#include "KviTalVBox.h"
#include "KviTalHBox.h"
#include "KviTalGroupBox.h"
#include <QScrollBar>
#include <QLayout>
#include <QMessageBox>
#include <QTimer>
#include <QCursor>
#include <QFont>
#include <QRect>
#include <QEvent>
#include <QKeyEvent>
#include <QMenu>
#include <QListWidget>
#include <QPainter>
Defines
#define KVI_SCRIPTEDITOR_DEFAULT_FONT "Monospace"
#define SKIP_SPACES
Functions
static QColor g_clrBackground (0, 0, 0)
static QColor g_clrBracket (255, 0, 0)
static QColor g_clrComment (0, 120, 0)
static QColor g_clrFind (255, 0, 0)
static QColor g_clrFunction (255, 255, 0)
static QColor g_clrKeyword (120, 120, 150)
static QColor g_clrNormalText (100, 255, 0)
static QColor g_clrPunctuation (180, 180, 0)
static QColor g_clrVariable (200, 200, 200)
static QFont g_fntNormal (KVI_SCRIPTEDITOR_DEFAULT_FONT, 8)
Variables
static bool bCompleterReady = false
static bool bSemaphore = false
KviModule * g_pEditorModulePointer
KVIRC_API KviModuleManager * g_pModuleManager
KviPointerList
< ScriptEditorImplementation > * g_pScriptEditorWindowList
Define Documentation
#define KVI_SCRIPTEDITOR_DEFAULT_FONT "Monospace"
Referenced by ScriptEditorImplementation::loadOptions().
#define SKIP_SPACES
Value:
while(iIndexStart < szText.size()) \
        { \
                if(szText.at(iIndexStart).unicode()=='\t' || szText.at(iIndexStart).unicode()==' ') \
                { \
                        iIndexStart++; \
                } else { \
                        break; \
                } \
        } \
Referenced by ScriptEditorSyntaxHighlighter::highlightBlock().
Function Documentation
static QColor g_clrBackground (0 , 0 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorWidget::updateOptions().
static QColor g_clrBracket (255 , 0 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QColor g_clrComment (0 , 120 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QColor g_clrFind (255 , 0 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorImplementation::ScriptEditorImplementation(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), ScriptEditorWidget::updateOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QColor g_clrFunction (255 , 255 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QColor g_clrKeyword (120 , 120 , 150) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QColor g_clrNormalText (100 , 255 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorWidget::updateOptions().
static QColor g_clrPunctuation (180 , 180 , 0) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QColor g_clrVariable (200 , 200 , 200) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorSyntaxHighlighter::updateSyntaxtTextFormat().
static QFont g_fntNormal (KVI_SCRIPTEDITOR_DEFAULT_FONT , 8) [static]
Referenced by ScriptEditorImplementation::loadOptions(), ScriptEditorImplementation::saveOptions(), ScriptEditorWidgetColorOptions::ScriptEditorWidgetColorOptions(), and ScriptEditorWidget::updateOptions().
Variable Documentation
bool bCompleterReady = false [static]
Referenced by ScriptEditorWidget::asyncCompleterCreation(), and ScriptEditorWidget::checkReadyCompleter().
bool bSemaphore = false [static]
Referenced by ScriptEditorWidget::ScriptEditorWidget().
KviModule* g_pEditorModulePointer
KVIRC_API KviModuleManager* g_pModuleManager
Referenced by KviModuleExtensionManager::allocateExtension(), KviModuleExtensionManager::allocateExtensionGetDescriptorList(), KviStatusBar::appletsPopupAboutToShow(), ScriptEditorWidget::asyncCompleterCreation(), KviKvsKernel::completeCommand(), KviKvsKernel::completeFunction(), KviKvsKernel::completeModuleCommand(), KviKvsKernel::completeModuleFunction(), KviScriptEditor::createInstance(), default_module_kvs_cmd_unload(), KviScriptEditor::destroyInstance(), KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly(), KviKvsTreeNodeModuleSimpleCommand::execute(), KviKvsTreeNodeModuleCallbackCommand::execute(), KviActionManager::getAction(), KviModuleExtensionManager::getExtensionList(), OptionsWidget_servers::importPopupAboutToShow(), OptionsWidget_servers::importPopupActivated(), IrcServerDetailsWidget::IrcServerDetailsWidget(), KviKvsCoreSimpleCommands::KVSCSC(), KviStatusBar::load(), KviActionManager::loadAllAvailableActions(), KviKvsObjectController::lookupClass(), OptionsWidget_soundGeneral::mediaAutoDetect(), OptionsWidget_soundGeneral::mediaFillBox(), KviApplication::notifierMessage(), ClassEditorWidget::oneTimeSetup(), KviIrcServerParser::parseCtcpRequestDcc(), perl_kvs_fnc_isAvailable(), perl_module_init(), python_kvs_fnc_isAvailable(), python_module_init(), KviApplication::setup(), OptionsWidget_soundGeneral::soundAutoDetect(), OptionsWidget_soundGeneral::soundFillBox(), OptionsWidget_soundGeneral::soundTest(), system_kvs_fnc_checkModule(), window_kvs_cmd_setCryptEngine(), and KviApplication::~KviApplication().
KviPointerList<ScriptEditorImplementation>* g_pScriptEditorWindowList
Referenced by editor_module_cleanup().