KVIrc: src/modules/torrent/StatusBarApplet.cpp File Reference
StatusBarApplet.cpp File Reference
#include "TorrentInterface.h"
#include "StatusBarApplet.h"
#include "KviLocale.h"
#include "KviIconManager.h"
#include "QTimer"
Functions
static KviStatusBarApplet * CreateTorrentClientApplet (KviStatusBar *bar, KviStatusBarAppletDescriptor *desc)
QString formatSize (float sz)
Function Documentation
static KviStatusBarApplet* CreateTorrentClientApplet (KviStatusBar * bar, KviStatusBarAppletDescriptor * desc) static
References KviStatusBar::insertPermanentWidgetAtTheEnd(), and KviStatusBarApplet::setIndex().
Referenced by StatusBarApplet::selfRegister().
QString formatSize (float sz)
References f.
Referenced by StatusBarApplet::update().